### ISSUE TITLE
目前有没有 快速上手 文档或实例？

### ISSUE THREAD

**Issue by guixue** [ant-design/ant-design-mobile#10]
源码中有 kitchen-sink， 但是用bisheng run起来的，具体项目没有参考性。

没有类似 antd-init 生成例子，或者 yoeman 的实例项目？

或者文档类似：
http://ant.design/docs/react/getting-started

**Comment by yiminghe** [comment]
https://github.com/ant-design/ant-design-mobile/issues/56

**Comment by guixue** [comment]
@yiminghe  感谢！
https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo

**Comment by ninjai001** [comment]
https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo

这个工程，我们没法覆盖ant mobile 的组件库的样式，所有我想下载按需下载组件，并能修改ant-mobile的样式

**Comment by ninjai001** [comment]
@guixue  **源码中有 kitchen-sink， 但是用bisheng run起来的**  ？我这边跑不起来，模块找不到
 ERROR in ./~/.0.16.3@bisheng/tmp/entry.index.js
[0] Module not found: Error: Cannot resolve module 'D:antant-design-mobile-maste
rant-design-mobile-mastersite   heme' in D:\ant\ant-design-mobile-master\ant-des
ign-mobile-master\node_modules\.0.16.3@bisheng\tmp
[0]  @ ./~/.0.16.3@bisheng/tmp/entry.index.js 55:17-144

模

**Comment by warmhug** [comment]
@ninjai001 上手示例里从没提到用 源码仓库，你为什么要用？看 #56 里的各种示例、找个符合你需要的参考

**Comment by ninjai001** [comment]
1：我们要修改其中的一些组件，包括样式和对外接口，
2：我们想引用部分组件，不想要全家桶。
3：安装 ant-init 方式搭建的环境，我们很难覆盖组件内样式。

**Comment by ninjai001** [comment]
@warmhug
 1：我们要修改其中的一些组件，包括样式和对外接口，
2：我们想引用部分组件，不想要全家桶。
3：安装 ant-init 方式搭建的环境，我们很难覆盖组件内样式。
方便有个旺旺给我，我的旺旺：嵇康

**Comment by warmhug** [comment]
@ninjai001 在这里讨论，刚才那是 demo 贴里不讨论这个。在内网也有类似你这个需求，也有相应库。后续也会抽时间开源出来。

**Comment by ninjai001** [comment]
@warmhug 好大坑，我们花了3个礼拜学习react，然后学习redux并你们dva，开始用ant mobile做项目了，发现样式没法覆盖，现在告诉我们没有更好办法。而且全家桶好大。

**Comment by ninjai001** [comment]
@warmhug 只要这个源码能跑起来，我们就能部分引用组件，在装dva，就能正常进行项目了。

**Comment by warmhug** [comment]
> 发现样式没法覆盖

样式是可以覆盖的。

另外你是想修改对外接口，就相当于在 antd-mobile 基础上包装了个自己的 UI 库，你要拷贝 antd-mobile 仓库、再在上边修改，这样做成本确实很大的。我们内部有做类似项目，现在还有数据未脱敏不方便开源。这几天我抽个 demo 出来供你参考

办法是有的！别放弃哈

**Comment by ninjai001** [comment]
@warmhug  目前kitchen-sink源码跑不起来，是什么原因？

**Comment by ninjai001** [comment]
@warmhug   按需加载的需求肯定有的

**Comment by ninjai001** [comment]
@warmhug 能否提上议程，实在是痛苦，开发效率极具下降

**Comment by afc163** [comment]
为啥没办法覆盖，antd-mobile 的样式也是标准样式。

**Comment by ninjai001** [comment]
@afc163 我们目前是在index.html 定义class去覆盖，但是不是特别好，我们想去修改他的样式文件。不知道如何去修改，我们用antd-init 创建的项目  是将mobile- ant 全部引入，我们其实想用部分的组件。
现在组件定义的基准 font-size是50px；我们项目都是用这个基准来做的。但是组件内的高度，和左边距等等都是写死了，我们想去修改，只能在index.html去覆盖，我们很想去修改组件内的样式，而且不想全部引入组件库，只要部分组件就行了；

**Comment by afc163** [comment]
1. antd-mobile 目前没办法全部引入，都是用 babel-plugin-import 来按需加载的。https://mobile.ant.design/docs/react/introduce#%E4%BD%BF%E7%94%A8

2. 在业务的 css 文件中（你总要写 css 的）按优先级覆盖样式即可。

**Comment by ninjai001** [comment]
@afc163 有些样式的class 是组件库内的，我们到哪里去覆盖？

**Comment by ninjai001** [comment]
@afc163 @warmhug @yiminghe 谁能帮我们把工程搭搭起来，我们公司在黄龙国际后面，真的很着急啊

**Comment by warmhug** [comment]
我现在做个示例、一会儿发链接给你。。方法其实有很多、要自己多探索

**Comment by ninjai001** [comment]
@warmhug 感谢了！

**Comment by ninjai001** [comment]
@warmhug 我发了一封gmail邮件给你。

**Comment by warmhug** [comment]
@ninjai001 看这个示例 https://github.com/warmhug/__/tree/master/_react/antd_custom_ui

**Comment by ninjai001** [comment]
![image](https://cloud.githubusercontent.com/assets/12545571/21338670/320a0372-c6b3-11e6-867e-1d189ee05548.png)
 路径解析出错

**Comment by ninjai001** [comment]
@warmhug 我很想知道bisheng是谁？

**Comment by warmhug** [comment]
@benjycui 看下 bisheng 是不是不支持 windows ？

**Comment by warmhug** [comment]
@ninjai001 你可以在 windows 装个 Linux 虚拟机试试看有没问题

**Comment by ninjai001** [comment]
@warmhug @yiminghe @afc163 
![image](https://cloud.githubusercontent.com/assets/12545571/21346868/3041d50a-c6e1-11e6-9ad3-5713ca5cc4c2.png)
这样为什么css的样式覆盖不了，webpack需要怎么配置，我用dvasheng生成的工程

**Comment by ninjai001** [comment]
![image](https://cloud.githubusercontent.com/assets/12545571/21347644/86b8666c-c6e4-11e6-9673-e6f40a074cc1.png)
这样写样式又是OK的，我真的不知道怎么去配置

**Comment by warmhug** [comment]
css modules 忽略了 node_modules 下的 css 名字，用
```css
:global {
  .am-search {...}
}
```

**Comment by benjycui** [comment]
bisheng 时间也没环境适配 windows。。
