### ISSUE TITLE
popup弹出层组件，弹出页面滚动会触发被遮罩的页面滚动。

### ISSUE THREAD

**Issue by suncn** [ant-design/ant-design-mobile#1000]
手机iPhone6
1. 官网提供的demo只是半屏的内容弹出，官方提供解决方案是禁止页面滚动，但是我的需求是弹出整页，需要滚动。
2. 在整页弹出层中输入文字，ios自带浏览器会让弹出层错位。

如果上述描述不清楚，我稍后再补充图片

**Comment by paranoidjk** [comment]
提供一个可复现的在线demo http://codepen.io/paranoidjk/pen/LWpaKe

**Comment by warmhug** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/996#issuecomment-287017937

**Comment by suncn** [comment]
@warmhug 我加上了好像没效果，如果把wrapProps里面的注释打开，页面不能滑动，我不希望那个那样子，因为我的弹层是个页面，里面需要有弹框，我回家做一个在线demo吧。

**Comment by suncn** [comment]
const {
  Popup, List, Button, Icon
} = window['antd-mobile'];

// fix touch to scroll background page on iOS
// https://github.com/ant-design/ant-design-mobile/issues/307
// https://github.com/ant-design/ant-design-mobile/issues/163
const isIPhone = new RegExp('\\biPhone\\b|\\biPod\\b', 'i').test(window.navigator.userAgent);
let wrapProps;
if (isIPhone) {
  // Note: the popup content will not scroll.
  wrapProps = {
    // onTouchStart: e => e.preventDefault(),
  };
}
var Hello = React.createClass({
 onClick : () => {
    Popup.show(<div>
        <div style={{height: "500px"}} >滑动我有bug</div>
        <div style ={{height:"500px", overflow:"scroll"}}>
         <List 
          className="popup-list"
          {_.map(new Array(500), (i, index) => (
            <List.Item key={index}>我是弹出层 滑动我有bug{index}</List.Item>
          ))}
        </List>
       </div>
      
     
    </div>, { animationType: 'slide-up', wrapProps, maskClosable: false });
  },
  onClose : (sel) => {
    this.setState({ sel });
    Popup.hide();
  },
  render() {
    return (<div style={{ height: '100%' }}>
      <Button onClick={this.onClick}>显示</Button>
        <List 
          className="popup-list"
          style={{height: document.documentElement.clientHight}}>
          {_.map(new Array(1000), (i, index) => (
            <List.Item key={index}>我是底层{index}</List.Item>
          ))}
        </List>
    </div>);
  }
});

ReactDOM.render(<Hello />,
  document.getElementById('container')
);
if ('addEventListener' in document) {
  window.addEventListener('load', function() {
    FastClick.attach(document.body);
  }, false);
}


pen我不太会用分享，把这个代码弄进去，放在iPhone6手机上看，bug很明显。

**Comment by suncn** [comment]
`const {
  Popup, List, Button, Icon
} = window['antd-mobile'];

// fix touch to scroll background page on iOS
// https://github.com/ant-design/ant-design-mobile/issues/307
// https://github.com/ant-design/ant-design-mobile/issues/163
const isIPhone = new RegExp('\\biPhone\\b|\\biPod\\b', 'i').test(window.navigator.userAgent);
let wrapProps;
if (isIPhone) {
  // Note: the popup content will not scroll.
  wrapProps = {
    // onTouchStart: e => e.preventDefault(),
  };
}
var Hello = React.createClass({
 onClick : () => {
    Popup.show(<div>
        <div style={{height: "500px"}} >滑动我有bug</div>
        <div style ={{height:"500px", overflow:"scroll"}}>
         <List 
          className="popup-list"
          {_.map(new Array(500), (i, index) => (
            <List.Item key={index}>我是弹出层 滑动我有bug{index}</List.Item>
          ))}
        </List>
       </div>
      
     
    </div>, { animationType: 'slide-up', wrapProps, maskClosable: false });
  },
  onClose : (sel) => {
    this.setState({ sel });
    Popup.hide();
  },
  render() {
    return (<div style={{ height: '100%' }}>
      <Button onClick={this.onClick}>显示</Button>
        <List 
          className="popup-list"
          style={{height: document.documentElement.clientHight}}>
          {_.map(new Array(1000), (i, index) => (
            <List.Item key={index}>我是底层{index}</List.Item>
          ))}
        </List>
    </div>);
  }
});

ReactDOM.render(<Hello />,
  document.getElementById('container')
);
if ('addEventListener' in document) {
  window.addEventListener('load', function() {
    FastClick.attach(document.body);
  }, false);
}`

**Comment by suncn** [comment]
[这里是pen](http://codepen.io/liys/pen/oZGrRB?editors=0011)

**Comment by suncn** [comment]
https://codepen.io/liys/pen/MpEMKq

上面是我做的在线pen，我打开iframe中的url用手机看，存在问题。

**Comment by warmhug** [comment]
抱歉截图里 API 写错了，看最新代码，已提交

**Comment by aizigao** [comment]
我试了下凡是用了rc-dialog的，现在在手机safari都有滑动的问题，我认为原因是在这个句上
https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L311

```js
addScrollingEffect = () => {
    openCount++;
    if (openCount !== 1) {
      return;
    }
    this.checkScrollbar();
    this.setScrollbar();
    document.body.style.overflow = 'hidden';   // safari下 body上设置 overflow失效
    // this.adjustDialog();
  }
```

* safari下在body上设置overflow是失效的,https://benfrain.com/preventing-body-scroll-for-modals-in-ios/
* 现在有这个问题有 action-sheet picker date-picker popup等，
* 是否可以开放出最外层标签的api，把overflow操作放到 react的container上

**Comment by paranoidjk** [comment]
@zinkey 

我在 iPhone 6sp safari 上好像并没有复现？另外 Modal 也是基于 rc-dialog。

请提供可复现的 demo。如有解决方案也欢迎 Pull Request 来修复。

**Comment by aizigao** [comment]
发现在body上加上下面这句就可以了
```css
html, body {
  /* 解决弹窗 ios上 overhidden 失效的问题 */
  width: 100%;
  height: 100%;
  overflow: scroll;
  -webkit-overflow-scrolling: touch;
}
```
