### ISSUE TITLE
Carousel 双击高度变为0

### ISSUE THREAD

**Issue by suncn** [ant-design/ant-design-mobile#1001]
iPhone6 手机看官方demo
https://mobile.ant.design/kitchen-sink/components/carousel?lang=zh-CN#

点击上述链接中的Carousel大图片，Carousel高度出现问题，跟我说的高度现象一致，不知道是不是一个问题。

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/1002

**Comment by warmhug** [comment]
已修复，看更新后的 demo
