### ISSUE TITLE
ImagePicker引用出错

### ISSUE THREAD

**Issue by tilamisu520114** [ant-design/ant-design-mobile#1003]
之前引用的组件版本在页面中是可以实现上传图片的功能的，更新版本后，该功能失效，在页面中引用新的该组件，页面报了语法错误，无法使用，麻烦帮忙解决下。谢谢！

**Comment by paranoidjk** [comment]
报错你最少要提供报错的内容。

请仔细阅读issue模板，提bug要给出必要的信息
