### ISSUE TITLE
Drawer中的sidebar在操作onClick事件时第一个list的节点会被新选种替换掉

### ISSUE THREAD

**Issue by wenshan** [ant-design/ant-design-mobile#1005]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.5
- Browser (or mark react-native) and its version（浏览器或react-native版本）: Chrome
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）: MAC

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
1.sidebar传入React dom 的列表
2.onOpenChange时，列表的第一个节点会被新触发的节点替换，初始化第一个节点就永远消失不存在。

#### What do you expected?（预期的正常效果）

sidebar的onClick正常不能替代列表dom。

#### What happen?（发生了何种非正常现象）
![snip20170317_1](https://cloud.githubusercontent.com/assets/3085424/24027223/ca824cf4-0b00-11e7-8a4e-e922b36a0841.png)
![snip20170317_2](https://cloud.githubusercontent.com/assets/3085424/24027229/d145adce-0b00-11e7-9ede-e7ca5f6bf876.png)

**Comment by paranoidjk** [comment]
Re-producible online demo (可复现的在线demo)

**Comment by wenshan** [comment]
已经找到问题。

**Comment by paranoidjk** [comment]
自己关issue
