### ISSUE TITLE
【请教】高清方案使用之后，如何在组件中动态计算高度，求问下关于这方面的最佳实践

### ISSUE THREAD

**Issue by ufohjl** [ant-design/ant-design-mobile#1006]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: latest

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

.item {
  height: 80px;
  line-height: 80px;
}

转换成rem为0.8rem，在iphone6下实际是80像素，在iphone6plus实际是120像素。

现在要监听滚动事件，需要在js中动态计算出item高度，求问下关于这方面的最佳实践？非常感谢~

**Comment by suncn** [comment]
我这也有同样的问题
页面上有header和list
比如header设置高度0.8rem
list的高度怎么计算并且除header高度以后剩下的窗口
List可以设置style属性
用document.documentElement.clientHeight-document.getElementById("header").style.height 这样可以吗？
官方demo如下
<ListView.IndexedList
        dataSource={this.state.dataSource}
        renderHeader={() => <span>头部内容请自定义</span>}
        renderFooter={() => <span>尾部内容请自定义</span>}
        renderSectionHeader={sectionData => (<div className="ih">{sectionData}</div>)}
        renderRow={rowData => (<Item>{rowData}</Item>)}
        className="fortest"
        style={{
          height: document.documentElement.clientHeight * 3 / 4,
          overflow: 'auto',
        }}
        quickSearchBarStyle={{
          position: 'absolute',
          top: 20,
        }}
        delayTime={10}
        delayActivityIndicator={<div style={{ padding: 25, textAlign: 'center' }}>渲染中...</div>}
      />


demo中的height: document.documentElement.clientHeight * 3 / 4 是什么意思？

**Comment by paranoidjk** [comment]
@ufohjl https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

@suncn 贴不格式话的代码没人愿意看的。

**Comment by suncn** [comment]
`<ListView.IndexedList
dataSource={this.state.dataSource}
renderHeader={() => 头部内容请自定义}
renderFooter={() => 尾部内容请自定义}
renderSectionHeader={sectionData => (

{sectionData}
)}
renderRow={rowData => ({rowData})}
className="fortest"
style={{
height: document.documentElement.clientHeight * 3 / 4,
overflow: 'auto',
}}
quickSearchBarStyle={{
position: 'absolute',
top: 20,
}}
delayTime={10}
delayActivityIndicator={<div style={{ padding: 25, textAlign: 'center' }}>渲染中...}
/>`
