### ISSUE TITLE
Carousel组件: A标签设置的url点击没有反应,我错在哪里了?

### ISSUE THREAD

**Issue by caohaijiang** [ant-design/ant-design-mobile#1007]
#### Environment(required) | 环境（必填）

- antd-mobile version: 1.0.5
- Browser : chrome  57.0.2987.98
- Operating environment: macOS Sierra 10.12.3

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

使用Carousel组件
```
<Carousel
                className='my-carousel' 
                autoplay={true} infinite= {true} dots={false}
                afterChange={ index =>handleChange(index)} 
            >
                {  
                    imgtexts.map(ii => (
                    <a key={ii}  href='http://www.baidu.com' > 
                        <img src= {require(`assets/img/${ii.img}`)} />
                    </a>
                    ))
                }
            </Carousel>
```
#### What do you expected?（预期的正常效果）
点击图片,跳转到指定url

#### What happen?（发生了何种非正常现象）
没有反应,组件之外正常.

**Comment by paranoidjk** [comment]
issue 模板写的很清楚

- 提问题上问答社区。
- 提bug请提供可复现的demo.

**Comment by warmhug** [comment]
在`beforeChange`里手动调用 location.href ，由于手势操作用了 touch 事件的缘故
