### ISSUE TITLE
Steps title & desc 接收 React.Node

### ISSUE THREAD

**Issue by kingdujiabo** [ant-design/ant-design-mobile#1008]
您好:  
  工作中常用到Steps, 但是由于各种不同情况和需求,  有些需求是描述信息是有点击效果的(可点击跳转的), 有的需求是描述信息里需要展示文字和图片的 . 
  但是查看源码, 发现描述信息放在了<Text></Text>中, 故无法实现想要的效果.  
   希望您有时间能添加下这些功能, 我想很多用户都会使用到
                                                                         
                                                                                       十分感谢.

**Comment by paranoidjk** [comment]
> 但是查看源码, 发现描述信息放在了中, 故无法实现想要的效果.
文字描述请写清楚，这里明显少了字，不懂你的意思。

title 和 description 都可以是 React.element，你完全可以传链接或图片，只是可能布局样式需要你自己调整。

**Comment by kingdujiabo** [comment]
不好意思,打扰了, 上次的提问漏字了
[源码StepsItem.tsx 文件](https://github.com/ant-design/ant-design-mobile/blob/master/components/steps/StepsItem.tsx) , 我看源码是把 Steps的 description 放在了 组件 Text 中,不知道是不是这个问题.
![rlg7wmxid2h fz_ s t n](https://cloud.githubusercontent.com/assets/21137759/24087594/dfae09da-0d5b-11e7-896b-04de28887851.png)
麻烦你看下我的代码, 我在后面传入一个<View>组件, 不知道这样传, 写法对不对, 会报错
![qh2t xozdby cu4kqi4orn3](https://cloud.githubusercontent.com/assets/21137759/24087614/11ed3b50-0d5c-11e7-86f8-7de18be60f46.png)
报错: 
![screenshot_1489978352](https://cloud.githubusercontent.com/assets/21137759/24087627/4509d624-0d5c-11e7-9328-84ce3aebcc9f.png)

**Comment by paranoidjk** [comment]
RN的组件你至少注明是RN，我当做是Web的来查的，完全浪费时间。

issue模板写得很清楚

**Comment by paranoidjk** [comment]
@silentcloud  看下这个需求

RN 的 StepsItem 的 title 和 description 改成用 View 包裹有没有问题？没问题我就改下
https://github.com/ant-design/ant-design-mobile/blob/master/components/steps/StepsItem.tsx#L92

**Comment by paranoidjk** [comment]
ping @silentcloud 看下我上面的方案

**Comment by paranoidjk** [comment]
@kingdujiabo 等本周五 1.0.7

**Comment by kingdujiabo** [comment]
很高兴收到您的回复, 再此对您说声十分感谢, 谢谢您, 辛苦了.

在 2017-03-22 14:57:49，"paranoidjk" <notifications@github.com> 写道：


@kingdujiabo 等本周五 1.0.7

**Comment by kingdujiabo** [comment]
你好, 我使用了更新后的 1.0.7版本后的Steps 但是还是报错, 
```
  <Steps size="small" current={1}>
        <Step title="03:00 已完成" description={<View><Text>测试</Text></View>}/>
        <Step title="进行中" description="这里是信息的描述" />
        <Step title="待运行" description="这里是信息的描述" />
  </Steps>
```


初步怀疑是因为[StepsItem.tsx](https://github.com/ant-design/ant-design-mobile/blob/master/components/steps/StepsItem.tsx)源码中 第99行 View标签后多了一个空格麻烦您测试下

**Comment by paranoidjk** [comment]
@kingdujiabo 报错是什么？这个空格应该不会有影响的，你试试改下node_modules里面的代码验证下呢？

**Comment by kingdujiabo** [comment]
TaskQueue: Error with task : RawText " " must be wrapped in an explicit <Text> component.
mountComponent
报错信息,

 node_modules是编译后的代码, 额有点看不懂......., 我认为编译前,运行到组件 `StepsItem.tsx`时就报了错

**Comment by paranoidjk** [comment]
https://www.reddit.com/r/reactnative/comments/4xjpxa/error_raw_text_must_be_wrapped_in_an_explicit/
@kingdujiabo 
有可能是空格问题，我这边看下。

**Comment by kingdujiabo** [comment]
好的, 麻烦您了

**Comment by paranoidjk** [comment]
@kingdujiabo 我这边测试 Android IOS 都ok。

**Comment by kingdujiabo** [comment]
好的, 谢谢您
