### ISSUE TITLE
【2.0】Pagination current 改成从 1 开始计数

### ISSUE THREAD

**Issue by wenshan** [ant-design/ant-design-mobile#1009]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:1.0.5
- Browser (or mark react-native) and its version（浏览器或react-native版本）:chrome
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:mac os

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
current值和展示的当前页码不一致

#### What do you expected?（预期的正常效果）
current值和展示的当前页码一致

#### What happen?（发生了何种非正常现象）
![snip20170317_3](https://cloud.githubusercontent.com/assets/3085424/24034540/9cac9a1a-0b2c-11e7-8fb3-a626eeafaaad.png)

![snip20170317_4](https://cloud.githubusercontent.com/assets/3085424/24034685/4f568612-0b2d-11e7-8087-e749d59f4f49.png)

#### Re-producible online demo (可复现的在线demo)
https://mobile.ant.design/components/pagination/

**Comment by paranoidjk** [comment]
cc @warmhug @silentcloud 我们 current 是从 0 开始计数的，文档也没写，这有点误导啊。

看了下 antd 的 current  是从 1 开始的。

但这个又属于 breakchange， 不能随便改，讨论一下

**Comment by warmhug** [comment]
antd 的 current 是从 1 开始的，这个合理些。记下、放到大版本改吧

**Comment by wenshan** [comment]
谢谢~
