### ISSUE TITLE
有没有新增懒加载图片的ImageLazy组件的计划

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design-mobile#1013]
请问有计划新增懒加载图片的ImageLazy组件吗？

**Comment by paranoidjk** [comment]
抱歉，这个暂时没有，移动端一般是长列表或图墙才有可能需要懒加载吧。

你可以先自己封装或者使用开源方案。

方然，任何时候，Pull Request 帮助我们来做都是欢迎的 😄
