### ISSUE TITLE
自定义主题时，修改searchbar 高度， 但是没有提供清除按钮的自定义，导致修改高度后显示不居中

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design-mobile#1014]
search-bar-input-height: 66px

清除按钮是绝对定位，但是没有提供自定义，结果是修改searchbar后清除按钮的位置还是之前的位置，导致显示效果不居中

**Comment by paranoidjk** [comment]
有兴趣来个pr帮我们修复吗？ ：）
