### ISSUE TITLE
iphone 6 iphone 6 plus 高清解决方案问题

### ISSUE THREAD

**Issue by hnsylitao** [ant-design/ant-design-mobile#1016]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 0.8.7
- Browser (or mark react-native) and its version（浏览器或react-native版本）: 浏览器
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）: chrome

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
微信上打开 http://starm.linanonline.com

![starm](https://cloud.githubusercontent.com/assets/17537749/24089859/f34ae548-0d75-11e7-8e93-8a64ec249932.gif)

iphone6 上 picker 组件 基本显示 ok

但是在6 plus 上组件就 显示太小了

webpack.config.js
```js
 postcss: [pxtorem({
    rootValue: 50,
    propWhiteList: [],
  })],
```
因为我们前面开发 是按照375*667 开发 所以rootValue 设置 为50
 我不知道是不是和这个有关系

**Comment by paranoidjk** [comment]
> 因为我们前面开发 是按照375*667 开发

设计师给你的psd肯定宽度是750才对吧？

**Comment by paranoidjk** [comment]
给个可以重现的demo吧，我没看出问题在哪。

**Comment by paranoidjk** [comment]
cc @pingan1927

**Comment by pingan1927** [comment]
https://mobile.ant.design/kitchen-sink/components/picker?lang=zh-CN#picker-demo-0

@hnsylitao 我拿官网demo示例看了下 正常的。

你的录像确实有问题，最好可以拿个demo可以再现，现在这样看不出来具体哪里出了问题，

**Comment by hnsylitao** [comment]
@pingan1927 
http://starm.linanonline.com 这个请用微信打开访问 就是picker 出现了这个问题
如果需要上传demo 的话待会我去写一个

**Comment by hnsylitao** [comment]
基本上是整体的组件都缩小了。 包括modal弹框 和 button 组件

**Comment by pingan1927** [comment]
@hnsylitao 在微信可以打开，但是无法查看代码，不知道具体哪里问题了，所以还是搞个demo哈

**Comment by pingan1927** [comment]
http://riddle.alibaba-inc.com/ 能在这个进行代码片段创建吗？

**Comment by paranoidjk** [comment]
@pingan1927 riddle不是内网的么...

**Comment by hnsylitao** [comment]
@pingan1927  codepen 我创建不好，所以上传了一个项目到github 了
https://github.com/hnsylitao/demo 麻烦帮忙看一下
antd-mobile 版本是 0.8.7

**Comment by paranoidjk** [comment]
@hnsylitao 0.8.x 我们其实已经不再维护了，尽量使用最新版吧

**Comment by hnsylitao** [comment]
@paranoidjk 我升级了1.0.6 显示也是一样

**Comment by warmhug** [comment]
关联 #683 ，根据自己需求可以使用其他高清方案脚本。

**Comment by hnsylitao** [comment]
@warmhug 谢谢
现在我为了基于android 高清屏 加了一点新的适配
```js
  if ((matches && matches[1] > 534  || isUCHd) && dpr >= 3) {
    // 如果为 android4.3 、 UC 内核, dpr >=3 重新设置 = 2;
    dpr = 2;
  }
  if (isIos && dpr == 3) {
    // 如果为 iOS, 按 2x 处理，dpr 设为 2;
    dpr = 2;
  }
```
