### ISSUE TITLE
有几个组件的样式建议优化一下

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design-mobile#1017]
antd-mobile:1.0.5

①Toast组件没有高度居中，整体偏下，很难看。
需要改进的样式： .am-toast-notice  
可以加上    top: 50%; margin-top: -50px;（大部分时候，Toast的高度是99px，所以设置-50px，如果完美的话，那就动态计算高度）。

②InputItem组件，
应用场景是:输入的内容默认向右靠齐，聚焦的时候是左靠齐。
需要改进的样式是：  .am-input-clear
加上clear属性后，建议输入框未获取焦点的时候隐藏掉.am-input-clear。否则清除图标会占据右侧的空间，

这两个问题应该很容易找到，所以没有做demo,如果需要的话，留言。

**Comment by pingan1927** [comment]
inputItem 这个建议好有道理，这周会优化。有兴趣提个PR？

Toast也会详细评估下！

**Comment by MotorFu** [comment]
恩恩。谢谢，目前时间有限，以后有时间的话，可以尝试一下。
