### ISSUE TITLE
Carousel组件在安卓系统滑动时卡顿、掉帧

### ISSUE THREAD

**Issue by zoope** [ant-design/ant-design-mobile#1019]
#### Environment(required) | 环境（必填）windows

- antd-mobile version（antd-mobile版本）: 1.0.5
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）: Android（手头所有测试机）

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
以下是组件引用的代码，content里面用到了ref，但是在DidMount使用，理论上不影响加载后的滑动流畅度
```jsx
<Carousel
  slideWidth={0.9}
  selectedIndex={current}
  className="my-carousel"
  infinite
  dots={false}
  afterChange={next => this.handleNextCurrent(current, next)}
>
  ...(content)
  })}
</Carousel>
```
#### What do you expected?（预期的正常效果）

流畅滑动，优美体验，可以实现首尾相连的滑动

#### What happen?（发生了何种非正常现象）

非正常卡顿、闪屏
+ 滑动过程中，图片的加载非常会有较明显的闪动，而且滑动动画不流畅，滑动偶尔不跟手
+ 首到尾和尾到首切换的时候，会有非常明显的闪动（先消失，再出现）  

介于这个组件官方只是封装了[nuka-carousel](https://github.com/FormidableLabs/nuka-carousel)的轮播，而且tabs组件的滑动在Android也不流畅，期待官方更新组件的源码~

#### Re-producible online demo (可复现的在线demo)

domo晚点更新

**Comment by paranoidjk** [comment]
官方demo找了台android机跑着还好啊？

能帮忙提供个codepen demo我看看？

**Comment by paranoidjk** [comment]
close for no response.
