### ISSUE TITLE
ImagePicker 在Android webview中无法弹出选择图片组件，在手机浏览器上可以弹出选择文件目录，但是页面灰色，不可选状态

### ISSUE THREAD

**Issue by wuxia510** [ant-design/ant-design-mobile#1021]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.5
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What do you expected?（预期的正常效果）
在Android和ios都可以选择文件

https://mobile.ant.design/components/image-picker/
#### What happen?（发生了何种非正常现象）
点击选择附件按钮，未弹出选择文件页面，无反应

#### Re-producible online demo (可复现的在线demo)
http://devcommunity.silinkeji.com/task?token=a440454673957849c13a16d7fef84e32&appid=wuguan&userguid=0b3607be-72e2-4296-a246-99aa1a67634f#/

从列表进入详情页面后 点击 底部曲别针按钮选择附件

**Comment by warmhug** [comment]
测试 Android iOS 都可以弹出

**Comment by pingan1927** [comment]
@wuxia510 测试三星S6自带Android浏览器可以打开正常拍照，
另外，这个网站的样式使用的是px为单位，建议外链的样式文件通过工具自动转换成rem，写在js或者html里的手动换算成rem。要不在dpr为3或者4或者1的机器上效果很不一样

**Comment by wuxia510** [comment]
主要是Android 的 webview调页面的时候，点选择附件的按钮没反应，无法弹出文件列表。用OPPO r9、魅族m2  也是  。都没反应。ios那边是正常的 。webview还需要另外设置什么吗？目前设置如下：
  settings.setJavaScriptEnabled(true);
        settings.setDomStorageEnabled(true);
        settings.setAllowFileAccess(true);
        settings.setDatabaseEnabled(true);
        settings.setUseWideViewPort(true);// 调整到适合webview大小
        settings.setJavaScriptCanOpenWindowsAutomatically(true);

**Comment by warmhug** [comment]
确认 Android 上的 浏览器 是没有问题吧？
至于 native 的 webview 组件、看你以上设置应该 OK 的，有问题可以再参考 react-native 对 webview 的封装方法，或自己查找其他资料。

**Comment by wuxia510** [comment]
嗯 Android  浏览器没问题  ，这个已经解决了 ，需要webview  重写一些方法才可以调文件系统 ，挺麻烦的。  最终实现了。具体参考这个解决的:http://www.cnblogs.com/nmdzwps/p/5841509.html    希望可以帮到别人。
