### ISSUE TITLE
Android 设备打开官方demo后内容丢失

### ISSUE THREAD

**Issue by caigehui** [ant-design/ant-design-mobile#1025]
小米、华为、魅族手机打开官方demo：https://mobile.ant.design/kitchen-sink/?lang=zh-CN
均不显示内容，白屏

**Comment by paranoidjk** [comment]
能说下 Android 的版本吗？ 光提供机型没多少参考信息啊

**Comment by paranoidjk** [comment]
我手边没有低版本Android，能帮忙看看 console 有报错么，这种情况很大可能是某个api不支持

**Comment by caigehui** [comment]
@paranoidjk  Android 7.0

**Comment by paranoidjk** [comment]
我这边正好是Android7.0， 实测没问题啊。你能提供更多信息吗？

**Comment by caigehui** [comment]
@paranoidjk 
华为/小米 7.0都不行，一访问https://mobile.ant.design/ 就会白屏，要不你换几台设备试试？
![1jriq_4_qdr1b2h8bi1a-0g74yeusys3k_y8irtiw96arp7etitwjuxs-faqybsb4qic1szwo4zk2trt3rlzv3w](https://cloud.githubusercontent.com/assets/9214907/24145900/4395777c-0e6e-11e7-8de5-95edef9805a7.jpg)

**Comment by caigehui** [comment]
使用jsconsole.com 发现 Uncaught ReferenceError: Symbol is not defined
引入babel-polyfill后恢复正常
@paranoidjk 检查一下demo吧

**Comment by warmhug** [comment]
@paranoidjk 跟进下看看代码，是否哪里用了太新的特性了。没解决的 issue 先开着

**Comment by paranoidjk** [comment]
@pingan1927 你那边有真机可以帮忙看下报什么错吗？ 这个很奇怪，其实一直都有 babel-polyfill

https://github.com/ant-design/ant-design-mobile/blob/master/site/kitchen/src/static/template.html#L61

**Comment by paranoidjk** [comment]
@caigehui 已经修复，可以验证下。

@warmhug  `intl` 的兼容性问题。
