### ISSUE TITLE
Icon在RN上，ios的配置不生效，报Unrecognized font family 'anticon'

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design-mobile#1027]
![image](https://cloud.githubusercontent.com/assets/18158633/24143626/4e86ab96-0e65-11e7-9d87-717964cd6b0a.png)
网站上的这段关于ios的配置能再说具体点吗，没做过ios开发，我是按下图这么弄的，不知道哪里有问题。
react-native@0.42.0
antd-mobile@1.0.6
![image](https://cloud.githubusercontent.com/assets/18158633/24144084/e9af926c-0e66-11e7-893a-60e9a60018ed.png)
![image](https://cloud.githubusercontent.com/assets/18158633/24144103/f9b82d4a-0e66-11e7-9ea6-e192e2bd03bf.png)

**Comment by silentcloud** [comment]
@zhulichao 路径不对，你先放在根目录下面试试

**Comment by silentcloud** [comment]
@zhulichao 解决了么？

**Comment by zhulichao** [comment]
没有哎，我试过放在根目录下，也没好使。现在使用的react-native-vector-icons。

**Comment by NewBen001** [comment]
@zhulichao 你可能需要添加target Membership，将项目和文件链接起来
![ttf](https://cloud.githubusercontent.com/assets/17876049/24385386/65bd5a12-139c-11e7-9474-76a5fe85c11c.png)

**Comment by silentcloud** [comment]
参看一下 demo app 实例：

![image](https://cloud.githubusercontent.com/assets/1698185/24386272/4ecdcc4c-13a1-11e7-8318-18018f1b414c.png)

![image](https://cloud.githubusercontent.com/assets/1698185/24386276/5a00d262-13a1-11e7-96d8-7bcdce85b2bb.png)

**Comment by Naiba01** [comment]
问题解决了吗？

**Comment by zhulichao** [comment]
我使用react-native-vector-icons了，没再试过antd-mobile的Icon。

**Comment by lulut** [comment]
我遇到的问题是一样的，anticon.ttf放在任何地方都不可以。target membership设置了，Info.plist里面也添加了，Build Phases 里面copy bundle resources里面也有对应的信息。但始终提示：
Unrecognized font family 'anticon'

**Comment by Naiba01** [comment]
@lulut 要将iconfont项目里面的font-family改成anticon才行，要不然ios里面查看的文件信息还是iconfont，antd-mobile不认。
![image 1](https://user-images.githubusercontent.com/14135956/33021974-8c522420-ce3e-11e7-905f-c610ef465b46.png)

**Comment by HideOnBushTuT** [comment]
@Naiba01  请问在哪里修改iconfont项目里的font-family

**Comment by Naiba01** [comment]
@HideOnBushTuT 
![image 1](https://user-images.githubusercontent.com/14135956/40403685-02e86d56-5e86-11e8-922a-a11820e091b9.png)更多操作里面

**Comment by llwcy8801** [comment]
不要使用anticon 使用iconfont 就好了
