### ISSUE TITLE
官网文档部分无法访问

### ISSUE THREAD

**Issue by JunQiGenYuan** [ant-design/ant-design-mobile#1029]
谢谢antd的开源和贡献，非常喜欢你们的库。
最近这两天，官网的文档无法打开，比如：https://mobile.ant.design/components/action-sheet/
控制台里提示如下：
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at e (common.js:1)
    at index.js:33
    at window.webpackJsonp (common.js:1)
    at /components/action-sheet/index.en-US.md.js:1
```

**Comment by paranoidjk** [comment]
在什么设备，什么浏览器？

**Comment by afc163** [comment]
『我这里是好的』

**Comment by JunQiGenYuan** [comment]
谷歌浏览器Chrome，版本 56.0.2924.87 (64-bit)
前些天可以的，这两天，关闭浏览器也打不开部分的，但是有的组件还是可以打开

**Comment by paranoidjk** [comment]
@JunQiGenYuan 我的chrome版本和你相同没有问题，我是 mac osx。

一次性给我能让我们定位问题的必要信息吧。比如你的控制台截个图。

**Comment by JunQiGenYuan** [comment]
隐私模式下可以查看，然后我清空浏览器缓存后可以正常访问了

**Comment by paranoidjk** [comment]
@JunQiGenYuan 你的描述我无法理解, 不知道哪个是好，哪个不好。

> 前些天可以的，这两天，关闭浏览器也打不开部分的，但是有的组件还是可以打开
> 隐私模式下可以查看，然后我清空浏览器缓存后可以正常访问了

**Comment by JunQiGenYuan** [comment]
前面强制刷新等等都没有用，清除浏览器的缓存后才可以发访问。
虽然不知道为什么，但是已经可以正常访问了，谢谢大家

**Comment by JunQiGenYuan** [comment]
是这样的，比如这个：https://mobile.ant.design/components/action-sheet/
在chrome隐私模式下访问正常，但在正常模式下访问不了。
在清除浏览器所有缓存后，两个模式下都可以正常访问了，可能是缓存的问题，而且CTRL+F5强制刷新页面也不生效，必须清除浏览器缓存

**Comment by paranoidjk** [comment]
@JunQiGenYuan 你早这么描述不就清楚很多了... 可能是由于我们静态资源没加版本号，后面我们会优化下。

**Comment by IPOjzt** [comment]
ant design官网不能访问 ，是不是变成拉闸的KPI项目了，我的依赖项目怎么办，，，

**Comment by paranoidjk** [comment]
@IPOjzt 网络环境原因，不可抗力。
trace https://github.com/ant-design/ant-design/issues/7895

**Comment by IPOjzt** [comment]
我改了host 公司还翻墙状态可以看Google和YouTube视频，一个蚂蚁国内开源项目观看难度比这些都高，，，

**Comment by silentcloud** [comment]
@IPOjzt 翻墙应该是 ok 的，我这边也是翻了，但是域名本身没问题

![image](https://user-images.githubusercontent.com/1698185/31881591-a92d7bea-b7a9-11e7-95cd-7c05f94cc2f7.png)

**Comment by paranoidjk** [comment]
官网地址: http://mobile.ant.design
国内镜像: http://antd-mobile.gitee.io

**Comment by jsjlj1988** [comment]
https://pro.ant.design/index-cn
pro地址打不开，
那pro国内的镜像有吗？
