### ISSUE TITLE
组件的颜色搭配如何自定义呢？

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#103]
如题，难道要一个个强制修改么？

**Comment by silentcloud** [comment]
利用 prefixCls 自己写样式文件

**Comment by minooo** [comment]
可以再说的详细点吗，如何利用prefixCls。谢谢了

**Comment by silentcloud** [comment]
举个例子：<Button prefixCls="xx-button" />

 默认 button 的样式前缀是 am-buttom，加了prefixCls 后，样式前缀就是 xx-button， 你就可以自己以这个前缀来重新写样式，比如：

```css
.xx-button {
   ...
   &-primary {
      ....
   }
}

```

**Comment by minooo** [comment]
这个添加 prefixCls 是如何实现的，抱歉，我对 prefixCls 一无所知。

**Comment by qq645381995** [comment]
@silentcloud   那怎么继承原来的 button 样式   这个less 要怎么写

**Comment by silentcloud** [comment]
@qq645381995 你用了 prefixCls 的话就没办法继承了，如果要继承就只能覆写了

**Comment by paranoidjk** [comment]
要继承使用 className 新加

**Comment by paranoidjk** [comment]
或者prefixCls is使用空格来hack
