### ISSUE TITLE
Alert, Switch 样式是否应该区分 Android/IOS 平台

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design-mobile#1030]
ios 
![image](https://cloud.githubusercontent.com/assets/7971419/24183807/673c5a6e-0f05-11e7-8b43-632c9f29182e.png)

安卓

![image](https://cloud.githubusercontent.com/assets/7971419/24183841/9ee9bb5a-0f05-11e7-9e57-5c3c5c6c2cdd.png)

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/971#issuecomment-285360628

这是By design， 我完善下文档

**Comment by qq645381995** [comment]
@paranoidjk  那有可以一个样式的吗？  不用原生的

**Comment by paranoidjk** [comment]
@qq645381995 暂时没做这个配置，假如用一个，也很难决定用哪套样式吧？

**Comment by qq645381995** [comment]
@paranoidjk  因为做开发 ui 肯定是不管安卓ios  ui肯定是一样的，所以 期望modal alert  可以有个css的样式 而不是原生  那样我们可以根据ui再修改

**Comment by qq645381995** [comment]
做 rn 原生的也许更好  但是 web  就不管是安卓和ios了 ui 统一化才是

**Comment by paranoidjk** [comment]
@qq645381995 和设计师讨论过后的结论是

`Modal`, `Switch` 等相关组件增加一个 `styleMode` 的 props, 其值默认是 `auto`, 即目前的现有逻辑，根据平台自动切换样式。用户可以手动设置为 `android`, `ios`

**Comment by qq645381995** [comment]
好的
