### ISSUE TITLE
关于高清方案的建议，针对mac retina屏，适用于antd和antd-mobile

### ISSUE THREAD

**Issue by nalantianyi** [ant-design/ant-design-mobile#1032]
适用于antd和antd-mobile<br/>
虽然antd-mobile使用pc端访问可能性不大，但是目前市面上retina屏幕的设备也越来越多，所以建议高清方案中，增加判断<br/>
`if (!isIos && !(matches && matches[1] > 534) && !isUCHd) {
                // 如果非iOS, 非Android4.3以上, 非UC内核, 就不执行高清, dpr设为1;
                dpr = 1;
            }`
            **`//添加mac等高清屏幕检测处理
            if (/Macintosh/.test(navigator.userAgent)) {
                dpr = win.devicePixelRatio;
            }`**<br/>
否则pc的retina屏幕dpr会被设置为1，影响展示效果，望采纳或者有更好的解决方案<br/>
@sorrycc @luolonghao

**Comment by pingan1927** [comment]
可以考虑

**Comment by paranoidjk** [comment]
高清方案的这段脚本不是强绑定在antd-mobile源码里，如果业务上有需要处理PC，自己在脚本里加就好了。解决方案只覆盖它需要处理的场景，保持简单。

@pingan1927 可以加点说明在wiki里，用户可以根据需求进行怎样的定制修改。

**Comment by pingan1927** [comment]
@nalantianyi 你说的建议不可行，chrome浏览器不切模拟成device则无法根据viewport的`initial-scale`动态调整`layout viewport`，也就是说iframe里宽度设置为375px，不管viewport怎么设置，都无法改变`document.documentElement.clientWidth`的值为750px。
