### ISSUE TITLE
DatePicker 组件，默认日期没设置在 minDate 和 maxDate 范围内

### ISSUE THREAD

**Issue by meng009** [ant-design/ant-design-mobile#1033]
DatePicker组件，设置了最大值和最小值，如果当前日期没有在这个范围里面，点击选择日期，在不拉选日期时，直接确定。默认的是当前的日期。那么设置最大值和最小值就失去了意义了。

**Comment by warmhug** [comment]
这个我觉得需要你自己去保障在范围内，不要用默认的当前的日期即可。
现在你可以这么理解：最大最小日期范围、就是给你在滑动选择时的一个限制。
组件也可以考虑增强下、把默认日期、设置到最大最小范围内。

------
> 建议： issue 的标题、正文，不要写的一样。请认真提 issue ！！

**Comment by paranoidjk** [comment]
这个优化合理，我来做吧，`default = min ？ Math.min(now, min) ： now`

**Comment by paranoidjk** [comment]
@meng009 你的描述有问题

> ，点击选择日期，在不拉选日期时，直接确定。默认的是当前的日期。

这里你不拉选，datePicker默认的是起始日期，并没有默认取当前的逻辑，请你给个可重现demo
