### ISSUE TITLE
roadhog 打包 处理svg和处理CSS bug问题

### ISSUE THREAD

**Issue by 247687009** [ant-design/ant-design-mobile#1034]
.roadhogrc.js
```javascript
import path from 'path';
const pxtorem = require('postcss-pxtorem');

const svgSpriteDirs = [
    require.resolve('antd-mobile').replace(/warn\.js$/, ''), // antd-mobile 内置svg
    path.resolve(__dirname, 'src/assets/svg'),  // 业务代码本地私有 svg 存放目录
];
export default {
    svgSpriteLoaderDirs: svgSpriteDirs,
    entry: "src/index.js",
    publicPath: "/",
    theme: "./theme.config.js",
    extraBabelPlugins: [
        'transform-runtime',
        ['import', {'libraryName': 'antd-mobile', 'libraryDirectory': 'lib', 'style': true}]
    ],
    extraPostCSSPlugins: [
        pxtorem({
            rootValue: 100,
            propWhiteList: [],
        }),
    ],
}
```

当  "roadhog": "^0.5.3" 配置为0.5.3 时，能够正确的在build的是处理CSS 但是不能处理SVG
https://mobile.ant.design/components/icon --- svg组件需要的版本为 >= 0.6.0-beta1
但是使用 该beta版本的roadhog时，CSS处理不生效

**Comment by yesmeck** [comment]
@ant-design-bot markdown

**Comment by paranoidjk** [comment]
@yesmeck cool, this hook service is provided by who? give me a link, i whould like to take a look, maybe add more.

**Comment by paranoidjk** [comment]
@247687009 不懂你说的 【CSS处理不生效】不生效是什么意思？参考这个官方demo

https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog

**Comment by 247687009** [comment]
@paranoidjk 请问你知道怎么在使用roadhog.js中配置的env么

**Comment by paranoidjk** [comment]
@247687009 去roadhog提issue，我和其他维护者同样会帮你看，解决问题要直接，不要浪费大家的时间
