### ISSUE TITLE
【2.0】DatePicker 自定义 children API 变更

### ISSUE THREAD

**Issue by xoptimal** [ant-design/ant-design-mobile#1036]
#### Environment(required) | 环境（必填）

1.0.3 / browser / google chrome 56.0.2924.87 

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

improt DatePicker 

code: 
```
        <DatePicker
          mode="date"
          title="选择日期"
          value={zhNow}
          {...getFieldProps('date1', {
            initialValue: zhNow,
            onChange(e){
              dispatch({
                type   : 'UserModel/save',
                payload: {
                  birthday: moment(e).format('YYYY-MM-DD')
                }
              });
            }
          })}
          minDate={minDate}
          maxDate={maxDate}
        >
          <div className={styles.item}>
            <span>出生日期</span>
            <div className={styles.value}>
              <span>{props.birthday}</span>
            </div>
            <div className={styles.icon_next}/>
          </div>
        </DatePicker>
```

#### What happen?（发生了何种非正常现象）

console output : 

```
Warning: Unknown prop `extra` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

```

#### What do you expected?（预期的正常效果）

console no warning hint

**Comment by paranoidjk** [comment]
先请试下 1.0.6 最新是不是已修复，谢谢

**Comment by paranoidjk** [comment]
我这边没有 1.0.6 复现，请提供可复现的demo

**Comment by warmhug** [comment]
这是正常现象，仔细看 extra api 说明 以及示例

**Comment by paranoidjk** [comment]
@warmhug 
https://github.com/ant-design/ant-design-mobile/blob/master/components/date-picker/index.web.tsx#L67
这个命名值得多考虑，叫 extra 只是为了搭配 ListItem 使用的场景，设计之初选一个合法的 html 属性名可能好一点

另外，类似的场景，感觉 rc-slider handle 这样子的api设计好一点，不依赖component嵌套，潜规则的props传递，而是显示的告诉用户 https://github.com/react-component/slider/blob/master/examples/handle.js#L34

**Comment by paranoidjk** [comment]
我的想法是下个大版本改下API：
```js
const customHandle = ({value, onClick}) => {
   return <List.Item arrow="horizontal" extra={value} onClick={onClick}>日期(CST)</List.Item>
}

const Demo = () => (
  <DatePicker
    mode="date"
    title="选择日期"
    extra="可选,小于结束日期"
    minDate={minDate}
    maxDate={maxDate}
    handle={customHandle}
  >
  </DatePicker>
)
```

@warmhug 这样如何？

**Comment by warmhug** [comment]
可以的，可以再讨论讨论、这个感觉不用着急。 

另外记得，semver 版本号 1.x 版本要兼容升级，2.x 版本才能有 break change 的

**Comment by warmhug** [comment]
@paranoidjk 再次评估下改动的成本收益、这几天确定结论

**Comment by paranoidjk** [comment]
目前这种api 其实对 children 接收的 props 是有潜规则要求的，很容易就会有用户在自定义 children 这块出问题。

ref: https://github.com/ant-design/ant-design-mobile/issues/1801 https://github.com/ant-design/ant-design/issues/5165

cc @silentcloud @afc163 @benjycui 发表下意见

**Comment by paranoidjk** [comment]
先不改 api，完善文档。
