### ISSUE TITLE
表单组件如何添加 required 选项？？

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#104]
在 `InputItem` 组件的API中并没有找到这样一个选项，求指教。

**Comment by warmhug** [comment]
表单组件，拆分出更多demo、加入更多验证选项、模拟真实业务场景 (现在一堆放一起不好)，并在文档里加入 rc-form 链接介绍。 @pingan1927 原来你做的？再改改？

**Comment by pingan1927** [comment]
这个抽时间完善吧 先把组件重新标注搞了

**Comment by pingan1927** [comment]
https://github.com/react-component/form 请先看看这个库 @minooo

**Comment by minooo** [comment]
好的，谢谢。
