### ISSUE TITLE
Modal可以实现无边框吗

### ISSUE THREAD

**Issue by ronankim** [ant-design/ant-design-mobile#1040]
比如点击一张图片，modal弹出大图，无圆滑border、无padding，无header保留位。

现在可以看到可以重置以下的css可以达到目的...

```
.am-modal-content {
  border-radius: 0;
  padding-top: 0;
}

.am-modal-body {
  padding: 0;
}
```

有什么办法不修改源码就实现上述的效果吗

**Comment by silentcloud** [comment]
可以使用 rc-component 里的组件自己实现

**Comment by paranoidjk** [comment]
@ronankim 

常见的 UI 模式，比如 Alert， Prompt 是有比较统一的 UI 规范的。你的需求其实只是一个普通的弹出层而已，建议你自己实现或者覆盖 antd-mobile 的 css，组件暂时不考虑在 Modal 上加很多个性化的样式配置。
