### ISSUE TITLE
【PC Only】Popup弹出时自动滚动到了页面底部

### ISSUE THREAD

**Issue by SevenUMR** [ant-design/ant-design-mobile#1041]
- antd-mobile version（antd-mobile版本）：1.0.6

- Browser (or mark react-native) and its version（浏览器或react-native版本）: safari

What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
    使用了Popup弹出层

What do you expected?（预期的正常效果）
    弹出时固定在当时的滚动位置。

What happen?（发生了何种非正常现象）
    容器滚动到了最下方

Re-producible online demo (可复现的在线demo)
https://codepen.io/fzzz/pen/OpZzyN

**Comment by paranoidjk** [comment]
@silentcloud 这里会导致页面滚动到最底部 

https://github.com/ant-design/ant-design-mobile/blob/master/components/popup/index.web.tsx#L17

**Comment by paranoidjk** [comment]
@warmhug https://github.com/ant-design/ant-design-mobile/blob/master/components/popup/index.web.tsx#L12 默认滚动到底是为什么?文档写的RN only

**Comment by warmhug** [comment]
没测出这个问题。
@SevenUMR 你给的示例有问题，要在本地项目里测试下再反馈。
@paranoidjk  代码没问题，动画类型只是区分向上弹出或向下弹出，下次测试尽量本地起 server https://github.com/ant-design/antd-mobile-samples/tree/master/web-typescript 在电脑模拟或真机里测

**Comment by paranoidjk** [comment]
@warmhug 有问题的，那个codepen可以复现，popup弹出后底下的整个页面（ListView）滚到最底部了

**Comment by SevenUMR** [comment]
@warmhug 就是本地测出这个问题，才去那边写了个demo来提issue。

**Comment by warmhug** [comment]
我在 iOS 模拟器里和 Android 真机上没测出问题

**Comment by SevenUMR** [comment]
去真机试了下。还真的没有问题。之前在本地起server是在电脑模拟器上看的，没上真机。
@warmhug 不好意思了

**Comment by paranoidjk** [comment]
原因在这里  https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L85

**Comment by paranoidjk** [comment]
修改有问题，先回滚： https://github.com/ant-design/ant-design-mobile/commit/9b6be0e80dd1c21ab29fad75da4047229e98a9ac

**Comment by onlyLiru** [comment]
请问这个bug怎么解决？有些手机浏览器也存在

**Comment by warmhug** [comment]
@onlyLiru 具体哪些？

**Comment by Meeeeow** [comment]
@warmhug @paranoidjk Android Chrome Beta 59.0.3071.82

**Comment by chuncui0207** [comment]
+1 我在ios 微信上也出现了

**Comment by cncolder** [comment]
问题应该不在 `mousePosition` 上，因为 `Popup.show(content, { mousePosition: false })` 或者 `Popup.show(content, { mousePosition: { x: 0, y: 0 } })` 都没能解决问题。

我暂时用笨方法：

```
const y = scrollY
Popup.show()
scrollTo(undefined, y)
```

**Comment by xdkaka** [comment]
@warmhug PC和移动端的chrome还是有问题

**Comment by silentcloud** [comment]
2.0 我试了，貌似没问题了

如果还有问题，再继续 reopen
