### ISSUE TITLE
ImagePicer组件错误

### ISSUE THREAD

**Issue by Qiupengcheng** [ant-design/ant-design-mobile#1043]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:  1.0.6
- Browser (or mark react-native) and its version（浏览器或react-native版本）:  web
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:  64bit window7

#### 出现状况  
import {ImagePicker} from 'antd-mobile';  

以上import 语句会报错，提示有一个文件依赖未能找到  

#### 解决办法  
查看源码，发现 antd-mobile\lib\image-picker\style\css.web 第一行require()的文件非必要... ...   
貌似...是作者忘记删了吗？？  
于是...我就自己动手...干掉了~

**Comment by paranoidjk** [comment]
https://mobile.ant.design/docs/react/introduce#Web-使用方式

**Comment by paranoidjk** [comment]
@ant-design-bot document

**Comment by paranoidjk** [comment]
@ant-design-bot Usage

**Comment by paranoidjk** [comment]
close，如果还有问题继续回复。
