### ISSUE TITLE
tag组件不支持 onClick属性，有时候希望onClick时 不修改selected

### ISSUE THREAD

**Issue by pwz1985** [ant-design/ant-design-mobile#1044]
- antd-mobile 1.0.6

**Comment by paranoidjk** [comment]
> 有时候希望onClick时 不修改selected 

这个需求的原因是什么？

**Comment by pwz1985** [comment]
就是类似于商品规格选择。。至少要选择 1个规格。自己实现好了

**Comment by paranoidjk** [comment]
没 get 到你的意思

> 至少要选择 1个规格

这个完全可以在业务代码层面做限制

**Comment by miaojiuchen** [comment]
@paranoidjk 请问受控属性怎么支持呢？
