### ISSUE TITLE
使用tabs组件的时候，在Android的 webview上发现刚进入页面时，tab下边那条线的宽度有时候不一致。切换tab之后变为一致

### ISSUE THREAD

**Issue by wuxia510** [ant-design/ant-design-mobile#1046]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:  1.0.5
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
刚进入列表后，有时候出现tab下边的线的宽度不够一个正常tab的宽度，来回切换之后就好了。

import {SegmentedControl, WingBlank, Icon, NavBar, Tabs} from 'antd-mobile';
tabs代码：
 <Tabs defaultActiveKey={this.state.defaultActiveKey} onChange={that.tabCallback.bind(this)} pageSize={4}
                      swipeable={false}>
                    <TabPane tab="我处理的" key="1">
                        <div
                            className="task_list_contaner">
                            <DealTaskList onCellClick={this.onCellClick.bind(this)}></DealTaskList>
                        </div>
                    </TabPane>
                    <TabPane tab="我创建的" key="2">
                        <div>
                            <CreateTaskList onCellClick={this.onCellClick.bind(this)}></CreateTaskList>
                        </div>
                    </TabPane>
                    <TabPane tab="我参与的" key="3">
                        <div>
                            <JoinedTaskList onCellClick={this.onCellClick.bind(this)}></JoinedTaskList>
                        </div>
                    </TabPane>
                    <TabPane tab="组内工单" key="4">
                        <div>
                            <GroupTaskList onCellClick={this.onCellClick.bind(this)}></GroupTaskList>
                        </div>
                    </TabPane>
                    <TabPane tab="完成工单" key="5">
                        <div>
                            <DoneTaskList onCellClick={this.onCellClick.bind(this)}></DoneTaskList>
                        </div>
                    </TabPane>
                </Tabs>

==============》
其中DealTaskList 组件中引入Listview,关键代码如下：
   return (
            <ListView
                dataSource={this.state.dataSource}
                renderRow={row}
                renderSeparator={separator}
                scrollRenderAheadDistance={200}
                scrollEventThrottle={20}
                onScroll={this.onScroll}
                style={{
                    height: height,
                    margin: '-0.1rem 0',
                }}
                scrollerOptions={{scrollbars: true}}
                refreshControl={<RefreshControl
                    refreshing={this.state.refreshing}
                    onRefresh={this.onRefresh.bind(this)}
                />}
            />
        )

#### What do you expected?（预期的正常效果）
tab下边的横线始终保持宽度一致，如图
![screenshot_2017-03-23-16-43-33-18](https://cloud.githubusercontent.com/assets/16182215/24239200/f07dfba6-0fe7-11e7-921c-296a2414cbf3.png)

https://mobile.ant.design/components/tabs/
#### What happen?（发生了何种非正常现象）
刚进入列表二面时，有时出现tab下边的横线宽度不一致，来回切换tab之后才变为正常

![na svv x 3 8ed j tf5](https://cloud.githubusercontent.com/assets/16182215/24238904/c93817c6-0fe6-11e7-8174-158ebcfbcdc2.png)

#### Re-producible online demo (可复现的在线demo)
http://devcommunity.silinkeji.com/task?token=a440454673957849c13a16d7fef84e32&appid=wuguan&userguid=0b3607be-72e2-4296-a246-99aa1a67634f#/

**Comment by paranoidjk** [comment]
我这边 galaxy s3, android 7.0 测试你的 demo ok，具体说下你那边是什么设备下有问题？

**Comment by Aus0049** [comment]
我今天也遇到了
![image](https://cloud.githubusercontent.com/assets/12423008/24247779/029cf63c-1008-11e7-903d-cd31b911ecc2.png)

我是按照文档 正常使用的
关键代码
`
<Tabs defaultActiveKey="inside" className="inbox-tab">
    <TabPane tab="编制内岗位" key="inside">
        ....
    </TabPane>
    <TabPane tab="编制外岗位" key="outside">
        ...
    </TabPane>
</Tabs>
`
但是是在微信开发者模拟器上看到的 真实手机上还没尝试 因为还没开发完 不知道会不会也有这个现象

**Comment by wuxia510** [comment]
魅族 m2   魅族note2，Android5.1

**Comment by paranoidjk** [comment]
@Aus0049 微信模拟器的问题暂时没有精力处理，我们优先处理真机上的问题。

@wuxia510 我在 魅蓝Note2 Android5.1 上测试官方demo以及你的网站都正常，你能提供一个可复现的demo吗？

**Comment by nekronhuang** [comment]
我也碰到过，不过因为不是必现的，所以没有再深究下去~

目前发现的是，tabs的`InkTabBar`在componentDidMount的时候activetab还没撑开，所以去取offsetWidth值不正确。

**Comment by paranoidjk** [comment]
@nekronhuang 都追得这么深了不考虑帮我们来个PR修复下么 👍

**Comment by nekronhuang** [comment]
@paranoidjk 因为没法稳定复现~所以不搞了。。。

**Comment by celleychen** [comment]
请问您怎么解决scrollbarview和竖直方向listview没法滚动问题？

**Comment by paranoidjk** [comment]
因为无法复现，先关闭。

如果有遇到这个问题的用户，先用 [forceupdate](https://facebook.github.io/react/docs/react-component.html#forceupdate) 解决吧。
