### ISSUE TITLE
SearchBar 查询输入后点“x”号取消输入时,placeholder 显示不正确

### ISSUE THREAD

**Issue by weiq** [ant-design/ant-design-mobile#1047]
1.antd-mobile最新版本
2.chrome及手机浏览器

可以仿问已下地址查看效果
http://codepen.io/weiq/pen/jBxxJx?editors=0010

重现步骤
1. 在查询框随意输入字符
2. 点击右侧"x"号取消
1.antd-mobile最新版本
2.chrome及手机浏览器

可以仿问已下地址查看效果
http://codepen.io/weiq/pen/jBxxJx?editors=0010

重现步骤
1. 在查询框随意输入字符
2. 点击右侧"x"号取消
![capture_2017323_183401](https://cloud.githubusercontent.com/assets/1697158/24244187/da2842a6-0ff8-11e7-9921-8332a8c8b050.jpg)
![capture_2017323_183532](https://cloud.githubusercontent.com/assets/1697158/24244191/db141654-0ff8-11e7-9bb9-b2ea9f907b4b.jpg)

**Comment by paranoidjk** [comment]
感谢反馈，等本周五的 1.0.7

**Comment by weiq** [comment]
@paranoidjk 问题依然有，这回是最后一个字没有了 http://codepen.io/weiq/pen/jBxxJx?editors=0010 最后一个“入”字消失

**Comment by paranoidjk** [comment]
@weiq 你这个demo有点奇怪，我本地测试时没问题的，你试试在chrome模拟器或真机先看看？

**Comment by paranoidjk** [comment]
@weiq 只在 PC 上有， offsetWidth 获取的宽度不包含小数，可能是 chrome 的bug

**Comment by weiq** [comment]
@paranoidjk 用ios自带的safari同样有相同的问题。
![2017-04-07 085907](https://cloud.githubusercontent.com/assets/1697158/24783987/3d0e71a8-1b82-11e7-9dfe-31cea9d83373.png)
![2017-04-07 085912](https://cloud.githubusercontent.com/assets/1697158/24783990/40c8629a-1b82-11e7-92f8-748838dd90a9.png)

**Comment by paranoidjk** [comment]
@weiq 我这边没问题啊，建议你访问官方demo测试 https://mobile.ant.design/components/search-bar

**Comment by chaixuhong** [comment]
同样的问题 "antd-mobile": "^1.3.0"   显示不全

**Comment by snowlocked** [comment]
the same problem in version 1.4.2

**Comment by paranoidjk** [comment]
@chaixuhong @snowlocked 
A reproducible demo, please, eg: https://codepen.io/paranoidjk/pen/LWpaKe

**Comment by movingStars** [comment]
the same problem in version 1.6.0

**Comment by movingStars** [comment]
I find a way to solve this issue.When the input is focued,set placeholder as ''

Here is my code.

<SearchBar placeholder={!this.state.focus ? placeholder : ''} maxLength={10} onBlur={this.searchBarFocus} onFocus={this.searchBarFocus}/>

searchBarFocus = () => {
        this.setState({
            focus: !this.state.focus
        })
    }

I hope it will help you.

**Comment by nmgwddj** [comment]
I have the same problem.

antd-mobile version: 

![2017-10-12 17 22 26](https://user-images.githubusercontent.com/13995319/31488989-01158620-af05-11e7-8958-5412c0e96353.png)

this is my code:

```
const Search = ({ searchText, searchSubmit, showSearchBar }) => {
  return (
    <div style={showSearchBar ? {} : { display: 'none' }}>
      <SearchBar
        placeholder={searchText}
        maxLength={50}
        cancelText='取消'
        onClear={(value) => {
          searchSubmit(null)
        }}
        onSubmit={(value) => {
          searchSubmit(value)
        }} />
    </div>
  )
}
```

In chrome 61.0.3163.100

<img width="401" alt="2017-10-12 17 18 17" src="https://user-images.githubusercontent.com/13995319/31488908-ccd53946-af04-11e7-8803-af57a87e46e3.png">
<img width="398" alt="2017-10-12 17 18 22" src="https://user-images.githubusercontent.com/13995319/31488910-cd4a92b8-af04-11e7-8e51-2a9fd34caea1.png">
<img width="696" alt="2017-10-12 17 18 29" src="https://user-images.githubusercontent.com/13995319/31488911-cd8c31b4-af04-11e7-9dd7-ae13858f4788.png">

In safari 

<img width="410" alt="2017-10-12 17 19 27" src="https://user-images.githubusercontent.com/13995319/31488951-e60ceac6-af04-11e7-82fd-8f6b551ece1f.png">

**Comment by silentcloud** [comment]
没能重现

**Comment by silentcloud** [comment]
@nmgwddj 你是必现么，是的话方便给个 demo 出来

issue 先关掉了
