### ISSUE TITLE
Which router library works well with ant-mobile?

### ISSUE THREAD

**Issue by loszer** [ant-design/ant-design-mobile#1048]
Which router library works well with ant-mobile? I have found many places but not find a good practice.Can I get a suggestion for this?

**Comment by paranoidjk** [comment]
sorry, no suggestion for you.  

In my opinion,  mutli page application is more common in mobile web nowadays, so router library is not necessary,  just as [dva-mobile](https://github.com/dvajs/dva/blob/master/docs/API_zh-CN.md#dvamobile)  did.

But if you still want single page application, just use react-router or ant thing else you like.
