### ISSUE TITLE
ActionSheet组件show状态是，页面返回时，怎么隐藏

### ISSUE THREAD

**Issue by NTmemoir** [ant-design/ant-design-mobile#1049]
当从A页面进入到B页面时，触发ActionSheet使其显示，然后按下手机的返回键，返回到A页面时，ActionSheet没有关闭，一直存在

**Comment by paranoidjk** [comment]
在 componentWillUnmount 里面调用 close https://mobile.ant.design/components/action-sheet-cn#static-close()---(web、android-only)-programmatically-close.

**Comment by PatWu16** [comment]
@paranoidjk 
我也遇到了同样的情况，但使用close()没有生效，请问应该如何关闭ActionSheet？

subscriptions: {
    setup({ dispatch, history }) {
      return history.listen(({ pathname }) => {
        console.log('close'); 
        close();
      });
    },
  },
