### ISSUE TITLE
InputItem 和 TextareaItem 在快达到maxLength的时候，不能输入中文。

### ISSUE THREAD

**Issue by linfaxin** [ant-design/ant-design-mobile#105]
#### 本地环境

- antd-mobile 版本：0.7.2
- 操作系统及其版本：ios
- 浏览器及其版本：safari

InputItem 和 TextareaItem 在快达到maxLength的时候，不能输入中文，会被截断成拼音。

**Comment by pingan1927** [comment]
fixed
