### ISSUE TITLE
tab组件下划线长度自定义

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design-mobile#1050]
当前tab选中的**下划线**是整个tab的长度， 长度能不能变成为**字体的长度**，或者是**整个tab长度**这两种显示方式

<img width="354" alt="2017-03-24 00 04 57" src="https://cloud.githubusercontent.com/assets/8924156/24257367/ab76220c-1025-11e7-9a38-84e9c499f5e0.png">

**Comment by paranoidjk** [comment]
你试试自己覆盖css不能做到吗？
另外文字长度可能不一样，这有点不太好

**Comment by yezongyang** [comment]
谢谢

**Comment by cuitianze** [comment]
同样有这个需求，覆盖CSS不容易啊。
下划线是用position定位的，不同tab数值不同，感觉仅覆盖CSS不能解决问题，还需要懂JS。

**Comment by cuitianze** [comment]
![tabs](https://user-images.githubusercontent.com/5918515/33313247-19b30164-d465-11e7-86f0-7b72fb43f954.jpeg)
如图，
position left 在css里不太好改吧。
underline如果能包裹一层容器就好了，这样就可以使用居中。

**Comment by zhang740** [comment]
文档：https://mobile.ant.design/components/tabs-cn/#Tabs

简单自定义使用tabBarUnderlineStyle，复杂自定义替换整个TabBar，可以继承默认实现然后覆盖想修改的地方。

@yesmeck

**Comment by sunny-wanghaiqing** [comment]
自定义替换了整个TabBar后，tabBarUnderlineStyle样式不起作用了，有好的方法自定义下划线吗？

**Comment by ZhangMingZhao1** [comment]
@sunny-wanghaiqing 同遇到这个问题 解决了吗

**Comment by h476564406** [comment]
可以解决
![image](https://user-images.githubusercontent.com/19324642/84489261-febb8300-acd3-11ea-8b7b-fde24a29a52c.png)

**Comment by fbixiaoyu** [comment]
滚动的时候 翻页显示不一致，有遇到吗 
![image](https://user-images.githubusercontent.com/40888647/135042873-77a1d4da-dd10-447e-b6ba-769b9c32af3a.png)

**Comment by Jasonlee6789** [comment]
> 可以解决 ![image](https://user-images.githubusercontent.com/19324642/84489261-febb8300-acd3-11ea-8b7b-fde24a29a52c.png)

这个是网页端可以用这个类名吗？我怎么试了下没生效？

**Comment by h476564406** [comment]
已经收到。
