### ISSUE TITLE
通过npm  安装的 antd-mobile 内置 icon的svg并没有被包含进来

### ISSUE THREAD

**Issue by andy1028** [ant-design/ant-design-mobile#1053]
![image](https://cloud.githubusercontent.com/assets/13925688/24280107/2bc4414c-1089-11e7-823e-7e3a78b72dbd.png)

对应的 目录下面并没任何的svg文件：
/node_modules/antd-mobile/lib/icon/style
发现这个文件夹里面是空的
2个疑问：
1、这个是故意不放进去的吗？
2、如果不放进去，如何使用内置的svg icon

**Comment by yezongyang** [comment]
查看icon 组件使用说明

**Comment by warmhug** [comment]
刚安装看了 lib/icon/style 目录不为空，icon 在里边的 assets 目录里。

**Comment by paranoidjk** [comment]
@andy1028 svg文件的路径如 @warmhug 所说

不过不建议你自己去require svg文件，可以阅读 Icon 组件的文档 https://mobile.ant.design/components/icon#如何使用-(WEB-版)

**Comment by andy1028** [comment]
@paranoidjk   截图代码，不是我自己的，  是icon组件里面的

**Comment by andy1028** [comment]
@warmhug  好我删除再安装下

**Comment by andy1028** [comment]
@warmhug   奇怪了，重新安装下果然有了

**Comment by andy1028** [comment]
@warmhug   我试了下   通过 yarn  安装 目录里面是没有的   通过npm  安装 是有的
![image](https://cloud.githubusercontent.com/assets/13925688/24282023/f18e1c3c-1097-11e7-9227-3667b6028aff.png)
