### ISSUE TITLE
Popup 组件show的时候导致页面滚动

### ISSUE THREAD

**Issue by Jeffy2012** [ant-design/ant-design-mobile#1054]
当页面可以滚动时，Popup.show 会导致页面滚动

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/1041

**Comment by Jeffy2012** [comment]
https://riddle.alibaba-inc.com/riddles/bf82de98

**Comment by paranoidjk** [comment]
@Jeffy2012 
参考上面的issue，是不是只有PC下有这个问题？

riddle还没有对外开放，尽量先别发在外面吧 :)

**Comment by Jeffy2012** [comment]
好像确实是只在pc上出现这个问题，我用钉钉看没这个问题

**Comment by paranoidjk** [comment]
close since duplicated. track at  https://github.com/ant-design/ant-design-mobile/issues/1041
