### ISSUE TITLE
建议增加图片预览组件，可支持滑动，自由缩放。

### ISSUE THREAD

**Issue by liuxingling** [ant-design/ant-design-mobile#1055]
如题。目的是，在使用完ImagePicker后，点击略缩图可查看大图，并能自由缩放。

**Comment by paranoidjk** [comment]
这个 feature 优先级比较低，可能等后面有空了才会来做。

欢迎你给我们PR。

**Comment by tianbaolin** [comment]
我遇到了同样的需求，希望优先级可以提高。

**Comment by warmhug** [comment]
目前没计划支持，可以使用 Modal 组件自己实现 @tianbaolin

**Comment by cfxmj2014** [comment]
+1

**Comment by dazhi007** [comment]
求增加不要随便关闭使用频率比较高的场景么.

**Comment by dd1994** [comment]
这个使用场景挺多的啊。。

**Comment by eric-projects** [comment]
+1

**Comment by zds-d** [comment]
+1

**Comment by qianjin1017** [comment]
+1支持了吗 @warmhug @dd1994 @dazer007 @paranoidjk @cfxmj2014
