### ISSUE TITLE
给Picker组件样式提个建议

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design-mobile#1057]
![wechatimg217 3](https://cloud.githubusercontent.com/assets/3940888/24288053/e7ed50d4-10b6-11e7-94d0-16152b7f051c.jpeg)

强迫症犯了。。。
参照上图：
希望能够将Picker,DatePicker组件的选中值  即.am-list-extra的样式颜色 与InputItem组件输入框字体颜色一致，当没有选中的时候显示的“请选择”字样应该与inputItem组件中的placeholder效果是一致的。

否则导致目前填写表单的时候，需要刻意修改原有的样式，导致代码不够简洁干净。

另外 请问两周之前提的多次点击Picker组件遮罩层被初始化的问题，解决了么？#978

**Comment by paranoidjk** [comment]
Antd-Mobile 样式是完全开放可定制的。

> 如何自定义主题？[见此文档](https://github.com/ant-design/antd-init/blob/master/examples/customize-antd-theme/README.zh-CN.md)，

https://github.com/ant-design/ant-design-mobile/blob/master/components/style/themes/default.less#L12

https://github.com/ant-design/ant-design-mobile/blob/master/components/style/themes/default.less#L10


Picker 的问题抱歉最近比较忙不过来，我们会尽量抽空解决，也欢迎你来帮忙 fix.
