### ISSUE TITLE
刷新页面时Carousel高度不正确

### ISSUE THREAD

**Issue by PatWu16** [ant-design/ant-design-mobile#1058]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:"antd-mobile": "^1.0.4",
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What happen?（发生了何种非正常现象）

![Uploading 1490347974(1).jpg…]()

![Uploading 1490348149(1).jpg…]()

初次加载和每次刷新时，轮播高度便很小，要到下一个图片时才会正常，在问题里找了半天，但没找到合适的解决方案，请问现在有了吗？

**Comment by paranoidjk** [comment]
关联 
https://github.com/ant-design/ant-design-mobile/issues/1002

https://github.com/ant-design/ant-design-mobile/issues/1001

**Comment by paranoidjk** [comment]
官方文档以及更新了处理方法 https://mobile.ant.design/components/carousel
