### ISSUE TITLE
InputItem 和 TextareaItem API 修改建议

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#106]
![image](https://cloud.githubusercontent.com/assets/2011119/17732031/988572e4-64a2-11e6-8c64-633bb3e3b5f5.png)

现在看着有点别扭，建议：

- type 改为 displayType
- format 改为 type

如果只支持 hasLine 也可以就不给配置项了.  http://mobile.ant.design/components/input-item#API

**Comment by yiminghe** [comment]
@pingan1927 评估，决策

**Comment by pingan1927** [comment]
先移除`type`。
`format` 改为 `type`
