### ISSUE TITLE
react-navite  List.Item 定制styles props报错

### ISSUE THREAD

**Issue by alert888** [ant-design/ant-design-mobile#1060]
·styles· is not a supported property of View, did you mean `style` (singular)

**Comment by alert888** [comment]
![image](https://cloud.githubusercontent.com/assets/12854505/24330345/7ab70dea-124e-11e7-87b1-99d80adb4b54.png)

**Comment by paranoidjk** [comment]
Please give us  your demo code. (You should read the issue template first !)

**Comment by paranoidjk** [comment]
你的报错信息已经很明显的， ~~`styles`~~ --> `style`

**Comment by alert888** [comment]
我知道很明显， 问题是styles props 属性是antd-mobile 提供给开发者重置内置样式的入口，
![image](https://cloud.githubusercontent.com/assets/12854505/24331886/b4d4b362-126f-11e7-8999-79e39f8b2474.png)

**Comment by alert888** [comment]
<List.Item styles={{Line:{backgroundColor:'white'}}} ></List.Item>

**Comment by alert888** [comment]
rn版本 0.42.3

**Comment by paranoidjk** [comment]
- `styles`这个props并不会被直接加到React-Native的component上面去
- 你的报错是 `styles`被传递给`<View>`了, check 下这个报错发生在哪个组件？是不是在你业务代码里面？

另外，你截图的代码我看并不是 Antd-Mobile 最新的代码，请确认你的 Andt-Mobile 版本。

反馈bug提供版本和设备信息这些在issue模板里写的很清楚，应该是最早就被提供的信息。
