### ISSUE TITLE
建议加入vscode工作区设置

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1062]
既然这是一个使用 Typescript 所写的项目，我相信参与编写的人里有90%以上的是用的 vscode。

vscode 有一种十分优雅的方法，隐藏同一目录下编译生成的代码。

```js
// .vscode/settings.json

{
  "files.exclude": {
    "components/**/*.js*": {
      "when": "$(basename).tsx"
    }
  }
}
```

#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.7
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）: OSX

#### What do you expected?（预期的正常效果）

隐藏 `components/**/*.jsx?`

![2017-03-27 10 58 30](https://cloud.githubusercontent.com/assets/127009/24339410/08333894-12de-11e7-9700-e5b0244ad3a9.png)

#### What happen?（发生了何种非正常现象）

目前三种后缀 .tsx .jsx .js 同时显示。

**Comment by paranoidjk** [comment]
感谢提醒，目前我们的确是这样处理的。

https://github.com/ant-design/ant-design/issues/4941#issuecomment-281739156

但是IDE相关的配置加到源码里感觉还是不太好。

**Comment by paranoidjk** [comment]
已经添加到 wiki 里。 https://github.com/ant-design/ant-design-mobile/wiki/TypeScript-Tips

**Comment by cncolder** [comment]
只是个建议，可以参考 [https://github.com/apollographql/apollo-client/blob/master/.vscode/settings.json](https://github.com/apollographql/apollo-client/blob/master/.vscode/settings.json)，他们就是把 .vscode 放在源码里，同时还规定了 tab size 和 rule 等。

**Comment by paranoidjk** [comment]
cc  @afc163 有没有必要都加一下 vscode 配置？

**Comment by afc163** [comment]
目前是用 gitignore 来隐藏的：https://github.com/ant-design/ant-design-mobile/blob/master/.gitignore#L40-L41 VSCode 不识别？

---

> @afc163 有没有必要都加一下 vscode 配置？

我觉得可以。

**Comment by warmhug** [comment]
我估计有些人是我这种 vs code 用法，问下这个设置还能有效吗、或者有没什么负面影响？
![image](https://cloud.githubusercontent.com/assets/2011119/24339774/72f58bf8-12e0-11e7-860d-8847d2bda4fd.png)
不是一个项目一个 vs project ，多个项目都在一个 project 里

**Comment by cncolder** [comment]
@warmhug 我试了下打开上一级目录，这个配置失效了。显然 vscode 只认当前目录下的 .vscode 文件夹。

**Comment by paranoidjk** [comment]
@afc163 vscode 和 sublime 都不会隐藏 .gitignore 匹配的文件的，这也是合理的。
