### ISSUE TITLE
Stepper组件在web端会自动获取光标，怎么才能禁止自动获取光标，不弹出软键盘？

### ISSUE THREAD

**Issue by nowui** [ant-design/ant-design-mobile#1064]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.7
- Browser (or mark react-native) and its version（浏览器或react-native版本）:微信浏览器
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:微信IOS端

#### What do you expected?（预期的正常效果）
![wechatimg203](https://cloud.githubusercontent.com/assets/3635163/24345701/e801801e-1303-11e7-99f9-3c78b10c44bc.png)

#### What happen?（发生了何种非正常现象）
![wechatimg204](https://cloud.githubusercontent.com/assets/3635163/24345725/faf8d528-1303-11e7-8b35-171d3eca03d0.png)

**Comment by paranoidjk** [comment]
- 并不会自动获取光标的，你可以看官方demo。请检查是否是微信浏览器或业务代码的问题
- 有个 `readOnly` api. https://mobile.ant.design/components/stepper#API

**Comment by nowui** [comment]
@paranoidjk  我把代码放在了网上：http://codepen.io/anon/pen/VpEYMB
我的问题是  用手机端访问的时候就会自动弹出软键盘  你可以用手机访问看看效果:http://zed.nowui.com/
帮我解决一下   谢谢啦

**Comment by cncolder** [comment]
这个问题似乎只存在于 safari 浏览器上，问下 @afc163 在 rc-input-number 中连续两个版本修复 safari bug 是指的这个吗？我在 @nowui 的 codepen 里放入两个 Stepper 结果 Safari 浏览器窗口失去响应了。

**Comment by evershy** [comment]
我不在微信浏览器也会出现这个问题，android和ios都会有。点击确定后会弹出软键盘，stepper的input自动聚焦，之前用0.9.x版本不会，现在升级到1.0.7出现的。按钮和题主一样，是固定在底部的，会不会与使用了position:fixed有关。

**Comment by freestyle21** [comment]
同样遇到这个问题，stepper组件会自动获取焦点弹出软键盘。

**Comment by paranoidjk** [comment]
iphone6sp ios10.3.2 safari 无法复现。
