### ISSUE TITLE
toast建议增加一个设置className的接口

### ISSUE THREAD

**Issue by jaune001** [ant-design/ant-design-mobile#1065]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.7
- Browser (or mark react-native) and its version（浏览器或react-native版本）:chrome最新版本
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:浏览器模拟iPhone6

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
![image](https://cloud.githubusercontent.com/assets/19927938/24345673/c23c1ea2-1303-11e7-9e02-c3c5319d5516.png)

引入了toast组件

#### What do you expected?（预期的正常效果）
每个问号对应的toast的位置与样式不同

希望toast能增加一个className的接口

**Comment by paranoidjk** [comment]
你这是toast组件?

**Comment by paranoidjk** [comment]
看起来明明是 ant-design 的 tooltip 才对吧。

**Comment by jaune001** [comment]
不是的哦，我用的toast，只是自己增加了一个箭头而已呢

**Comment by paranoidjk** [comment]
所以你其实是自己定制了 toast ？ 那你完全可以把 antd-mobile 的 toast 包一层的

**Comment by jaune001** [comment]
传递 React.Node 类型的 content?  不懂是啥意思。可以说的详细点么 @paranoidjk

**Comment by paranoidjk** [comment]
```js
  Toast.info(<div className="my-tooltip">这是React.Node类型的tooltip</div>, 1);
```

**Comment by jaune001** [comment]
好的，我先试试看，thanks @paranoidjk
