### ISSUE TITLE
InputItem type=number onChange设置正则匹配只能输入数字，，但是可以输入＋－

### ISSUE THREAD

**Issue by zhouzefei** [ant-design/ant-design-mobile#1070]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:1.0.4
- Browser (or mark react-native) and its version（浏览器或react-native版本）:all
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）: all

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

<pre>

  type="number"
  value={ apply_loan_amount }
  onChange={ (apply_loan_amount) => {
     apply_loan_amount = apply_loan_amount.replace(/\D/g,'');
     this.setState({
       apply_loan_amount
     });
  }}
</pre>
#### What do you expected?（预期的正常效果）
唤起数字键盘，并只能输入数字

#### What happen?（发生了何种非正常现象）
可以输入＋－

**Comment by zhouzefei** [comment]
@pingan1927 什么时候修复

**Comment by pingan1927** [comment]
不好意思修复晚了，这周五发布的小版本会修复。

**Comment by pingan1927** [comment]
参见 #1073 #1134
