### ISSUE TITLE
ImagePicker组件 在app上如何控制显示上传按钮

### ISSUE THREAD

**Issue by aiien007** [ant-design/ant-design-mobile#1071]
上传图片达到数量限制，不需要再显示上传图片按钮
看了开发文档 有selectable(web only)属性 
貌似在app端无法应用，请问在APP端如何实现？

**Comment by paranoidjk** [comment]
> APP端

是指你是 React-Native 吗？

issue 模板不要直接删掉，里面写了详细的你应该提供的信息

**Comment by aiien007** [comment]
@paranoidjk 刚用GitHub，见谅
用的antd-mobile版本是^1.0.4 安卓模拟器端 
用ImagePicker 组件 实现 上传图片功能
当前的效果是每次添加一张图片，添加新图片按钮都会存在
要实现的效果是当图片数量达到3次后不再显示添加新图片的按钮
selectable无法实现的话  React-Native如何实现呢？谢谢

**Comment by paranoidjk** [comment]
>【安卓模拟器端】

你还是没有说清楚是 React-Native 还是 Web，但按我理解你是React-Native

- web 版用 `selectable` 是可以实现的，参考官方demo就有
- RN 版暂时不支持这个api，你可以尝试传入以下props隐藏按钮 https://github.com/ant-design/ant-design-mobile/blob/master/components/image-picker/index.tsx#L152

最后。**请阅读 issue 模板**
![https://zos.alipayobjects.com/rmsportal/MWftpFCOTCyPUWEaKMGC.png](https://zos.alipayobjects.com/rmsportal/MWftpFCOTCyPUWEaKMGC.png)
