### ISSUE TITLE
ActionSheet must provide a valid successCallback

### ISSUE THREAD

**Issue by F-happy** [ant-design/ant-design-mobile#1072]
####  环境

- antd-mobile版本:  1.0.7
- react-native版本: 0.42.3
- 操作系统版本: Mac OS 10.12.3 ios 虚拟机

#### 请提供复现步骤

复制 ActionSheet demo 中的代码
```javascript
const icons = [...iconList];
    icons.length = 4;
    ActionSheet.showShareActionSheetWithOptions({
      options: icons,
      message: '我是描述我是描述'
    },
    (buttonIndex) => {
      this.setState({ clicked1: buttonIndex > -1 ? icons[buttonIndex].title : 'cancel' });
      // also support Promise
      return new Promise((resolve) => {
        Toast.info('1000ms 后关闭');
        setTimeout(resolve, 1000);
      });
    });
```

#### 预期的正常效果

期望像官方demo一样正常展示

#### 发生了何种非正常现象

![wx20170328-110209](https://cloud.githubusercontent.com/assets/8241236/24387291/e8735b5a-13a6-11e7-9b69-8b8320d4cf0f.png)

**Comment by silentcloud** [comment]
官方 demo 运行直接报这个错么？ @F-happy

**Comment by F-happy** [comment]
是额，三个 demo 我直接复制的，只有第一个能用，后面两个都是这个错误。。。 @silentcloud

**Comment by silentcloud** [comment]
@F-happy  你是 RN 的环境，要复制 basic.tsx 里的代码来跑的，我看你贴的代码是 web 环境下的 code

**Comment by F-happy** [comment]
😂原来是这样的啊。。

**Comment by warmhug** [comment]
看来也要把 native 的 demo 代码也展示到网站上了。 @benjycui 一起看看、有什么简单方法？

**Comment by paranoidjk** [comment]
@warmhug 可以调研下这个 https://blog.expo.io/sketch-a-playground-for-react-native-16b2401f44a2

**Comment by silentcloud** [comment]
react-native 官方 demo，appetize.io

**Comment by silentcloud** [comment]
demo app 很早就实现了扫码预览的功能，只是网站一直没实现展示 rn 代码，能展示后，直接拿 iOS  demo app 扫生成的二维码预览即可，或者接 appetize.io（只不过速度比较慢）

**Comment by paranoidjk** [comment]
@silentcloud 开个issue整理下可能的方案？ 后面空了把这个做上来

**Comment by silentcloud** [comment]
好，重新开个 issue，这个 issue 关了

**Comment by zmGitHub** [comment]
我靠 官网文档 写的真的是够了 浪费开发者时间啊

**Comment by zmGitHub** [comment]
RN 的代码能不能和 web 的区分下 唉 后悔用了
