### ISSUE TITLE
InputItem type='number' 的bug

### ISSUE THREAD

**Issue by liuxingling** [ant-design/ant-design-mobile#1073]
Environment(required) | 环境（必填）

antd-mobile version（antd-mobile版本）:1.0.6
What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
<InputItem
  type="number"
  maxLength={4}
  placeholder="请输入验证码"
>
What do you expected?（预期的正常效果）

唤起数字键盘，并只能输入数字，最大字符限定四位

What happen?（发生了何种非正常现象）

输入方面：
ios正常。
pc谷歌浏览器可以输入＋－ 英文字母e。
安卓手机可以切换输入法，还能输入表情等。但如果type='phone'，却都限制好了。

字符控制方面：
maxLength无效了

![image](https://cloud.githubusercontent.com/assets/26077947/24387742/7a1add06-13a9-11e7-91dc-c99f04b41a03.png)

**Comment by pingan1927** [comment]
已修复。本周小版本更新后会解决

**Comment by zhouzefei** [comment]
貌似安卓手机不能唤起数字键盘，而且不能输入小数点 @pingan1927

**Comment by paranoidjk** [comment]
@zhouzefei 
- 原生的小数点键盘需要native配合。
- `antd-mobile@1.3.0` 新增了虚拟数字键盘，请使用 `type="money"`

**Comment by zhouzefei** [comment]
![img_3756](https://user-images.githubusercontent.com/8566935/27008595-c0cefe82-4ea8-11e7-8142-ca5c5342cd4c.png)
可是好丑啊 @pingan1927

**Comment by paranoidjk** [comment]
请提供一个可复现demo，这个样式不对，正确效果请看官方demo

**Comment by motorguo** [comment]
@paranoidjk Hello! `InputItem type='money'` 与 `Popup` 组合使用，提供了个 demo, 请问这算不算是个 bug. 

[Demo: ![1](https://user-images.githubusercontent.com/16831715/29268354-02a0ea0c-811f-11e7-939d-74ce8106376a.gif)](https://codepen.io/ThomasOzil/pen/PKJWgx?editors=0010)

**Comment by paranoidjk** [comment]
@motorguo 这个 bug 我记得 @pingan1927 已经修复了，请用最新版的 antd-mobile 测试下？

**Comment by motorguo** [comment]
用的是 `1.6.0`，不过在线 demo 也是一样。

**Comment by paranoidjk** [comment]
@motorguo 用 https://github.com/ant-design/ant-design-mobile/releases/tag/1.6.5 再测试下？

**Comment by paranoidjk** [comment]
close for no response.

If anyone still got problems with the newest antd-mobile version, just commet here with a reproducible demo, and i will check it.
