### ISSUE TITLE
ImagePicker在Ios上报错

### ISSUE THREAD

**Issue by 1049017200** [ant-design/ant-design-mobile#1074]
undefined is not an object (evaluating 'RCTCameraRollManager.getPhotos')

**Comment by 1049017200** [comment]
![qq20170328-111544](https://cloud.githubusercontent.com/assets/17327793/24387901/5ecd3af2-13aa-11e7-87ad-9bbf1b7eb672.png)

**Comment by paranoidjk** [comment]
给出你的demo代码，仔细看issue模板

**Comment by paranoidjk** [comment]
http://stackoverflow.com/questions/33293814/undefined-is-not-an-object-evaluating-rctcamerarollmanager-getphotos

please try google first，obviously this Error is from react-native

**Comment by silentcloud** [comment]
@1049017200 没有在 info.plist 添加权限，需要添加权限才能访问相册

**Comment by paranoidjk** [comment]
补充相关的链接： https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content
