### ISSUE TITLE
网站展示 RN demo 代码

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1075]
关联 #1072  #23 （刚开始还讨论过这个问题）

- 方案1：网站展示对应的 RN demo 代码，提供二维码，利用 demo app 的扫码功能（目前暂只有 iOS）来预览对应组件 demo；每次 gh-pages 发布的时候，build 出 bundle，放在 gh-pages 里，bundle 可以根据当前 组件名来路由跳转；

- 方案2： 网站展示 demo 代码，接入 appetize.io

**Comment by silentcloud** [comment]
@benjycui 这个 doc 有计划搞么

**Comment by benjycui** [comment]
这个先设计下网站的布局，这样才知道技术上要怎么调整。

@silentcloud 你找下设计？

**Comment by silentcloud** [comment]
@benjycui ，好，我去内网记个 issue 给设计师

**Comment by paranoidjk** [comment]
RN 的优先级降低吧。目前已经做了  expo demo，足够方便了。
