### ISSUE TITLE
去掉 navigator.userAgent 依赖以支持服务端渲染

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1079]
原计划采用类似 #1077 中的办法，增加 userAgent 属性，但是 ListItem Modal Switch 这三个组件中已经有一个 platform 属性了。只是在 Modal 里用正则判断 `isIPhone` 的时候条件不够严谨。

[Modal.web.tsx#L117](https://github.com/ant-design/ant-design-mobile/blob/241e8f2a39880eb08c67acc9d83eec1ca30f1edd/components/modal/Modal.web.tsx#L117)

```js
const isIPhone = new RegExp('\\biPhone\\b|\\biPod\\b', 'i').test(window.navigator.userAgent);
// 此处是否可以改成
const isIPhone = platform === 'ios' || (platform === 'cross' && !!navigator.userAgent.match(/\b(iPhone|iPod)\b/i));
```

这种写法有个问题就是用户必须严肃对待 platform 属性，如果在 Android 机型上故意设置 `platform='ios'` 会触发接下来的一段 hacker 代码 `{ onTouchStart: e => this.isInModal(e) }`

这里的 `new RegExp` 和之前的写法不统一，不过 `/regexp/i.test(string)` 比 `!!string.match(/regexp/i)` 更简洁。

另外 platform 的值是不是只有 'android' 'ios' 'cross' 这三种？因为代码中从没出现过 'ios'，如果是的话 `PropTypes.tsx` 里也应该改成 `platform?:  'android'|'ios'|'cross';`

#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.7
- Browser (or mark react-native) and its version（浏览器或react-native版本）: node
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

- List.Item
- Modal
- Switch

#### What do you expected?（预期的正常效果）

去掉 navigator.userAgent 依赖

**Comment by paranoidjk** [comment]
[这里](https://github.com/ant-design/ant-design-mobile/blob/241e8f2a39880eb08c67acc9d83eec1ca30f1edd/components/modal/Modal.web.tsx#L117) 移到 componentDidMount 里面应该也行，只是为了 fix [这个](https://github.com/ant-design/ant-design-mobile/blob/241e8f2a39880eb08c67acc9d83eec1ca30f1edd/components/modal/Modal.web.tsx#L23)

**Comment by warmhug** [comment]
@silentcloud 跟进下这个。另外 https://github.com/ant-design/ant-design-mobile/blob/b59af4f2dd9ea553e1b7efb50ba4501a511f500c/components/modal/Modal.web.tsx#L118 这里和 Popup 组件做法不一样，再测试下这个是否确实没问题？
关联 https://github.com/ant-design/ant-design-mobile/commit/8ba8162683af7c9da08890dc4d6954d36a18f280  https://github.com/ant-design/ant-design-mobile/commit/9b6be0e80dd1c21ab29fad75da4047229e98a9ac

**Comment by cncolder** [comment]
@paranoidjk 能说的更详细一些吗？

是把 `wrapProps` 放在 state 里，`componentDidMount` 的时候 `if (isIPhone) this.setState({ onTouchStart: e => this.isInModal(e) })` 这样吗？
