### ISSUE TITLE
关于全局box-sizing

### ISSUE THREAD

**Issue by nekronhuang** [ant-design/ant-design-mobile#1081]
一般css框架都会重置**box-sizing**为**border-box**，antd也是如此，但为何antd-mobile并没有呢？

如果是用content-box，但很多组件内部又是指定了border-box，那为何全局不指定一下？如果有更深层的考量，望指教~

**Comment by paranoidjk** [comment]
cc @warmhug @pingan1927 有考虑过吗

**Comment by pingan1927** [comment]
这个是antui延续下来的，没有特别的考量

**Comment by yezongyang** [comment]
举个例子， 如果div设置box-sizing为border-box, height=28px, line-height=28px,  border="1px solid #000", 这样的话里面的字体就不是垂直居中的， 需要把line-height设置为26px

**Comment by warmhug** [comment]
pc 组件 dom 庞大、结构复杂，统一设置比较合理。移动端也可以考虑统一设置，但必要性相对不强。

现在大多组件都各自设置了`border-box`，部分组件有`content-box`设置，先看能否都统一掉，再考虑是否所有元素统一 reset 设置。

**Comment by silentcloud** [comment]
这个先自己在 css 里设置吧，issue 关掉了
