### ISSUE TITLE
List extra 字体大小配置

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design-mobile#1083]
<img width="405" alt="2017-03-30 09 24 44" src="https://cloud.githubusercontent.com/assets/8924156/24483479/014d86c0-152b-11e7-9496-30c4d5337aa1.png">

这个font-size 是固定的， 不知道是出于什么原因

**Comment by silentcloud** [comment]
@yezongyang 之前是视觉临时要求写死的，现已修改过来了
