### ISSUE TITLE
Picker组件 已呼出键盘情况下点击组件，初始化位置错误

### ISSUE THREAD

**Issue by LIN727** [ant-design/ant-design-mobile#1084]
#### 环境

版本：1.0.7
浏览器：微信浏览器
设备：iphone7 ios 10.2

问题：当已呼出键盘的情况下，点击Picker 组件会在屏幕上方闪一次再回到底部正确位置。

**Comment by paranoidjk** [comment]
请提供一个可复现的demo。

另外，请测试下是否在除了微信之外的其他浏览器ok?

**Comment by LIN727** [comment]
@paranoidjk 抱歉，很晚才看到你的回复。现在这个问题已得到修复，原因目前还不了解。非常感谢积极的回复。顺便说一下，当时出了在微信浏览器之外的浏览器里没有发现此Bug（安卓浏览器，mobile safari）

**Comment by paranoidjk** [comment]
已修复的自己关闭issue吧。
