### ISSUE TITLE
TextareaItem 输入框中输入表情时，显示异常

### ISSUE THREAD

**Issue by Linkinzoo** [ant-design/ant-design-mobile#1085]
- antd-mobile version（antd-mobile版本）: 0.9.13
- Browser (or mark react-native) and its version（浏览器或react-native版本）:^15.4.2
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）: iOS & Android

复现步骤：
1. 使用组件：TextareaItem,添加参数count={140}，限制输入字符为140个字。
2. 运行程序，在输入框内输入表情。
期待结果：输入框内的字符数量能按照count字段的参数进行限制（140/140）；
实际结果：输入框内的字符数量将每个表情识别1个字符，计数位置将表情识别为两个字符；输入133个文字和7个表情，计数位置将显示为：147/140；
重现机率：必现。
![image](https://cloud.githubusercontent.com/assets/16731012/24489650/43e69884-1551-11e7-840e-e2aad09e2009.png)

**Comment by silentcloud** [comment]
@Linkinzoo 欢迎提供 PR

**Comment by benjycui** [comment]
我就好奇如果这个是英文，又会怎么计算？

140 个字母么。。
