### ISSUE TITLE
Modal基本对话框怎么加动画效果

### ISSUE THREAD

**Issue by zhouzefei** [ant-design/ant-design-mobile#1086]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
没有动画效果
```javascript
<Modal
          title="这是 title"
          transparent
          maskClosable={false}
          visible={this.state.modal1}
          onClose={this.onClose('modal1')}
          footer={[{ text: '确定', onPress: () => { console.log('ok'); this.onClose('modal1')(); } }]}
>
          这是内容...<br />
          这是内容...<br />
</Modal>
```

#### What do you expected?（预期的正常效果）
类似Modal.alert的这种动画效果

**Comment by silentcloud** [comment]
@zhouzefei 提供了 `transitionName` 和 `maskTransitionName` 属性的， 默认 `animated = true` 的话是有默认动画的

**Comment by zhouzefei** [comment]
@silentcloud 
我想要的是Modal.alert的这种弹出的效果，，只有这两种效果么
```javascript
let anim = transitionName || (animated ? (transparent ? 'am-fade' : 'am-slide-up') : null);
let maskAnim = maskTransitionName || (animated ? (transparent ? 'am-fade' : 'am-slide-up') : null);
```

**Comment by silentcloud** [comment]
@zhouzefei  `am-zoom`

**Comment by yangxiufang1994** [comment]
@silentcloud 你好，我想问一下，2.1.3的Modal的动画可以禁止吗？有什么方法？在业务中用Modal来做详情了，有动画感觉卡顿。谢谢

**Comment by warmhug** [comment]
@yangxiufang1994 覆盖动画样式或动画名字

**Comment by miaosongjing** [comment]
@silentcloud  请问下 想实现从右侧划入的动画 怎么实现
