### ISSUE TITLE
Picker 设置默认选中值？

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design-mobile#1087]
当前显示picker弹窗时默认选中第一个， 能不能添加一个默认选中值？

**Comment by bccsafe** [comment]
可以用`value`属性

> 属性 | 说明 | 类型 | 默认值
> ----|-----|------|------
> | value   | 值, 格式[value1, value2, value3], 对应数据源的N级value    | Array  | - |

**Comment by yezongyang** [comment]
我的意思不是value, 想要的效果是设置一个默认值，但是在界面里不显示这个值，只是在弹窗里选中这个默认值

![Uploading 70789CC0-5389-4B3E-9679-455CB807C3AC.png…]()

**Comment by chenkangpeng** [comment]
how ？
