### ISSUE TITLE
【RN】Steps 自定义 Icon

### ISSUE THREAD

**Issue by lyw1991** [ant-design/ant-design-mobile#1088]
RN升级为1.0.7后，原项目的Steps.Step报错RawText “” must be wrapped in an explicit <Text> component 
description属性为< Text >xxxxx</ Text>
然后再问一下自定义颜色应该如何修改，官方文档上没有更新

**Comment by paranoidjk** [comment]
> RN升级为1.0.7后，原项目的Steps.Step报错RawText “” must be wrapped in an explicit component

这个会在今天的 1.0.8 fix。

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/1008

**Comment by paranoidjk** [comment]
> 然后再问一下自定义颜色应该如何修改，官方文档上没有更新

@lyw1991 你想要自定义什么颜色，说清楚你的需求？

**Comment by lyw1991** [comment]
![123](https://cloud.githubusercontent.com/assets/18585437/24574839/850a4420-16cb-11e7-9631-8b776e0b1a30.png)
@paranoidjk 1.0.7更新日志上写的支持自定义颜色了，但文档上没有写怎么修改颜色

**Comment by paranoidjk** [comment]
@lyw1991 

- sorry, changelog 写错了，是 **Slider 支持自定义颜色**，我更新下。
- 但是每个变动点后面都有相关 issue 链接的，点进去看的话也能找到答案。

**Comment by lyw1991** [comment]
@paranoidjk 请问一下Steps的自定义颜色是否有计划添加？类似于ant design里面的timeline可以替换圆圈的颜色

**Comment by silentcloud** [comment]
@lyw1991 rn 组件也支持自定义 theme 和自定义单个组件样式的

**Comment by paranoidjk** [comment]
@silentcloud 看起来 icon 不太对的样子。 https://github.com/ant-design/ant-design-mobile/blob/master/components/steps/StepsItem.tsx#L76

**Comment by silentcloud** [comment]
@lyw1991 rn icon 要添加字体的，详细见 icon 文档；

当然这里是个 bug，你可以先用 图片代替一下，我后面来修
