### ISSUE TITLE
介绍页面有一点问题

### ISSUE THREAD

**Issue by Unfantasy** [ant-design/ant-design-mobile#1090]
https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.en-US.md
![image](https://cloud.githubusercontent.com/assets/16619996/24576586/f33ae3f8-16f0-11e7-980d-6467f379b8ad.png)

**Comment by silentcloud** [comment]
额，为嘛没把 style 解析为标签？ 本地 markdown preview 的时候就正常的

**Comment by cncolder** [comment]
应该是很久前就不允许 script style，连 style 属性都不行，出于安全原因。

[https://github.com/github/markup/issues/119](https://github.com/github/markup/issues/119)

**Comment by afc163** [comment]
读这里就可以了：https://mobile.ant.design/docs/react/introduce 

那个只是源文件。
