### ISSUE TITLE
【RN】Steps vertical

### ISSUE THREAD

**Issue by celleychen** [ant-design/ant-design-mobile#1091]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

**Comment by silentcloud** [comment]
请按 issue 填写一下环境

**Comment by sharingjingang050241** [comment]
@silentcloud 一样的问题 ，"antd-mobile": "^1.0.7","react-native": "0.33.0",
direction="horizontal"这个没有起作用，是什么造成的呢；

**Comment by paranoidjk** [comment]
@celleychen @sharingjingang050241 

提问题写清楚描述信息，**进度条** 是 **Progress** 组件，没有 direction api

我理解你们说的应该是 **steps** 组件？steps 应该缺了样式。 @silentcloud  https://github.com/ant-design/ant-design-mobile/blob/master/components/steps/index.tsx#L39

**Comment by sharingjingang050241** [comment]
@silentcloud @paranoidjk 请问这个bug会在这周末修改么。着急用这个组件，如果说这周不能修改这个steps有横向属性，我们就得考虑自己封装咧。T.T～，谢谢

**Comment by silentcloud** [comment]
@sharingjingang050241 不是 bug，是目前 Steps rn 没有横向，一直抽不出时间做，欢迎提供 pr

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/issues/780

**Comment by paranoidjk** [comment]
@celleychen 
since dulplicate with #780, close this. please track progress at #780
