### ISSUE TITLE
高清方案的flex布局问题

### ISSUE THREAD

**Issue by schier** [ant-design/ant-design-mobile#1092]
flex布局下，每个flex:1的元素之间(dpr2+的设备上？)，有缝隙。（设置背景色可以看到）

**Comment by pingan1927** [comment]
是个bug，这周修复

**Comment by pingan1927** [comment]
请配个截图呗，验证了比较久，发现我遇到的问题不可解决，具体看看你说的问题是哪个情况？

**Comment by schier** [comment]
具体是不是高清方案引起的我没有深入了解。
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3.png…]()

**Comment by schier** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()
![Uploading 3.png…]()

应该是高清方案引起的，不过我没深入了解

**Comment by schier** [comment]
非常抱歉，这边不知为什么传不了图片。
给.am-flexbox加个背景色 .am-flexbox-item也加个背景色。就可以看到了。应该是高清方案引起的[https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE](url)

**Comment by schier** [comment]
非常抱歉，这边不知为什么传不了图片。
给.am-flexbox加个背景色 .am-flexbox-item也加个背景色。就可以看到了。应该是高清方案引起的【antd mobile 0.8 以上版本「高清」方案设置】

**Comment by paranoidjk** [comment]
不能复现，先 close。
