### ISSUE TITLE
Picker 组件可以自定义样式不?

### ISSUE THREAD

**Issue by junmaqiang** [ant-design/ant-design-mobile#1094]
下面是默认的样式

我希望可以保留 Picker 组件, 但是内容可以自定义样式. 知晓的朋友帮帮忙
非常感谢!

**Comment by paranoidjk** [comment]
- Antd-Mobile 基本上所有的组件都可以接受 `prefixCls` 来自定义样式
- 有些样式可以 [定义主题](https://github.com/ant-design/antd-init/blob/master/examples/customize-antd-theme/README.md)
- 最后一个方案，你可以自己覆盖样式

**Comment by AlexTMing** [comment]
你好 我想问一下 在安卓上怎么覆盖啊,在哪里写啊    InputItem 里面加style修改左边标题的宽度  不行,拿标题宽度要在哪里改呢  ,还有底边的边框,试了一下 使用margin到是可以全屏,但是我觉得这样不对   嗯 ,主要就是问下说覆盖样式的 到底怎么覆盖啊
