### ISSUE TITLE
关于SwipeAction在ListView上的应用

### ISSUE THREAD

**Issue by FrankFei** [ant-design/ant-design-mobile#1095]
#### Environment(required) | 环境

- antd-mobile version（antd-mobile版本）:antd-mobile 1.0.7
- Browser (or mark react-native) and its version（浏览器或react-native版本）:chrome
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:windows 10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

我在ListView的Item中引用了SwipeAction,注：没有使用ListView的useBodyScroll

#### What do you expected?（预期的正常效果）

在向左或向右滑动SwipeAction时，希望禁止ListView上下滑动

#### What happen?（发生了何种非正常现象）

在向左或向右滑动SwipeAction时，ListView上下滑动，感觉很不友好

**Comment by warmhug** [comment]
iOS 系统原生交互里，有在 左右滑动 时，禁止 上下滑动 吗？

**Comment by FrankFei** [comment]
iOS中如微信聊天或通讯录中，都有禁止 上下滑动功能！我们原来使用的SenchaTouch也有禁止 上下滑动的功能。

**Comment by FrankFei** [comment]
我如果在ListView中使用useBodyScroll，则在SwipeAction的onOpen中使用document.body.style.overflow = 'hidden';在onClose中使用document.body.style.overflow = '';可以解决我的问题。
但现在我没有使用useBodyScroll,不知有没有什么好的方法来处理？

**Comment by silentcloud** [comment]
这个我来弄个实例试试

**Comment by silentcloud** [comment]
@FrankFei 我在 safari 和 微信里都没重现；
SwipeAction 里在做滑出滑回的时候是做了限制的，只能水平方向操作  https://github.com/react-component/swipeout/blob/master/src/Swipeout.web.js#L216

**Comment by FrankFei** [comment]
下面的例子里可以重现：
http://www.chuang-cai.com:8086/pools

**Comment by paranoidjk** [comment]
关联  https://github.com/ant-design/ant-design-mobile/issues/1254

**Comment by paranoidjk** [comment]
同样的问题， 请关注 https://github.com/ant-design/ant-design-mobile/issues/1254 ， ListView 内部的横滑都会触发上下滑动。

**Comment by xxq260310** [comment]
@sileentcloud 为啥不能禁止上下滑动，在SwipeAction进行左右滑动的时候，FrankFei的例子就复现了这种场景。求帮助。

**Comment by paranoidjk** [comment]
@xx260310 为什么不看我上一条回复？ 本周五的版本修复

**Comment by qqis314860100** [comment]
都2019了这个不完美的效果还没被修复吗？

**Comment by qqis314860100** [comment]
我也遇到这个问题，请教楼上各位大佬是如何解决的？
