### ISSUE TITLE
Tabs在react-native中的两个问题

### ISSUE THREAD

**Issue by kimjuny** [ant-design/ant-design-mobile#1096]
"antd-mobile": "^1.0.7"

1. Tabs.pageSize

之前用在web项目中是可以的，但是在rn的项目中好像不起作用。这是bug吗。

2. Tabs的背景色问题

我试着在Tabs、TabPane和Tabs的父组件，都设置成backgroundColor: 'white'，组件背景却依然是系统默认的灰色，只有字体附近的背景才是白色。请问要如何修改这个灰色附近的背景 -> 白色?

<b>截图</b> - pageSize设置为4，backgroundColor都设置成了'white'

![img](http://i.imgur.com/8pNPaUL.jpg)

**Comment by paranoidjk** [comment]
文档有写， `pageSize` 目前是 `web only` 的, RN 版还不支持

**Comment by kimjuny** [comment]
@paranoidjk 源码的`tabs/index.xx.md`里有这个`pageSize`的api说明，官网里就木有了~ 我也是看了下源码才找到这个instruction

**Comment by kimjuny** [comment]
1. [components/tabs/Tabs.tsx](http://i.imgur.com/zyGWIKR.jpg)
![img0](http://i.imgur.com/zyGWIKR.jpg)
2. [components/tabs/PropsType.tsx](http://imgur.com/FbqIcQa.jpg)
![img1](http://imgur.com/FbqIcQa.jpg)
3. [components/tabs/index.zh-CN.md](http://imgur.com/Ds0NVzT.jpg)
![img2](http://imgur.com/Ds0NVzT.jpg)
4. components/tabs/index.en-US.md(与#3相仿)

谁能尽快添加一下这个feature吗，我这里是commit不上去，可以解决rn中backgroundColor无法设置的问题。

**Comment by silentcloud** [comment]
@kimjuny  现在已经支持设置 bar 的样式的， `barStyle` 属性，https://github.com/ant-design/ant-design-mobile/blob/master/components/tabs/Tabs.tsx#L82

只是文档里没有加这个属性说明，我稍后补充上去
