### ISSUE TITLE
1.0.7中picker相关操作时，只要有setState，picker选中的选项就会自动回到第一个

### ISSUE THREAD

**Issue by lvjinpeng0** [ant-design/ant-design-mobile#1097]
#### Environment(required) | 环境

- antd-mobile version（antd-mobile版本）: antd-mobile 1.0.7
- Browser (or mark react-native) and its version（浏览器或react-native版本）: chrome iPhone6模拟器
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
在操作picker时，在onPickerChange里只要setState过，picker此时的选择就会自动回到第一个

#### What do you expected?（预期的正常效果）
应该是滑动到哪里就停止到哪里的

#### What happen?（发生了何种非正常现象）
但是却自动回到第一个

**Comment by paranoidjk** [comment]
能请提供一个代码demo吗？

关联 https://github.com/ant-design/ant-design-mobile/issues/978

**Comment by lvjinpeng0** [comment]
```javascript
class AppComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      data: [{
        label: 1,
        value: 2
      }, {
        label: 3,
        value: 4
      }],
      pickerValue: [2222, 5555]
    };
    this.onPickerChange = this.onPickerChange.bind(this);
  }

  onPickerChange(e) {
    this.setState({
      data: this.state.data
    })
  }

  render() {
    return (
      <div>
          <Picker
            title="选择报考城市"
            data={this.state.data}
            cols="2"
            onPickerChange={this.onPickerChange}
            value={this.state.pickerValue}
          >
            <List.Item>
              <span style={{color: 'red'}}>* </span>
              您的报考城市
            </List.Item>
          </Picker>
      </div>
    );
  }
}

export default AppComponent;
```

**Comment by bccsafe** [comment]
```
  onPickerChange(value) {
    this.setState({
      pickerValue: value
    })
  }
```

**Comment by paranoidjk** [comment]
@bccsafe 考虑下这种情况要不要加个warning

**Comment by paranoidjk** [comment]
@bccsafe  https://github.com/ant-design/ant-design/blob/master/components/_util/warning.tsx

**Comment by lvjinpeng0** [comment]
```javascript

      const data = [...this.state.data];
      const asyncValue = [...this.state.asyncValue];
      const cityListData = nextProps.cityListData.map((item, index) => {
        return {label: item.name, value: item.id};
      });
      data.forEach((item) => {
        if (this.state.getCityListDataFirstTime && cityListData[0].value != -1) {
          if (item.value == this.state.provinceListFirst) {
            item.children = [...cityListData];
            this.state.getCityListDataFirstTime = false;
            asyncValue.push(this.state.provinceListFirst, cityListData[0].value);
          }
        } else {
          if (item.value == asyncValue[0]) {
            if (JSON.stringify(item.children) != JSON.stringify(cityListData)) {
              item.children = [...cityListData];
              asyncValue.push(cityListData[0].value);
            }
          }
        }
      });
      this.setState({
        data,
        asyncValue
      });
```
还有像这种情况，选完第一列省份，这时候请求城市列表再用children包起来塞进去，再setState，在chrome模拟器里面没问题，但是再ios微信浏览器里选择完省份第二列需要用手指拖动一下列表才显示出来
![](https://raw.githubusercontent.com/lvjinpeng0/blog/master/images/external/WechatIMG53.jpeg)

**Comment by lvjinpeng0** [comment]
我又试了下，选完省份，第二列列表不显示，这时候就算拖动一下蒙层背景，第二列都会显示出来，但就是开始不会自动出来

**Comment by bccsafe** [comment]
@lvjinpeng0 

`asyncValue`的逻辑在`onPickerChange`里处理，别在`componentWillReceiveProps`里做，`onPickerChange`里会把选中的value(Array)丢给你的，不用手动去改

**Comment by bccsafe** [comment]
@paranoidjk 

children的检查 `rn-picker`做了 
https://github.com/react-component/m-picker/blob/master/src/PickerMixin.tsx#L36

data里没有这个value的情况，最好在`m-cascader`里做？
https://github.com/react-component/m-cascader/blob/master/src/Cascader.tsx#L49-L57
这里只做了value没有默认值的情况，没有做检查

**Comment by paranoidjk** [comment]
@bccsafe 可以过去提个 PR

**Comment by paranoidjk** [comment]
@lvjinpeng0 你的问题解决了吗？ 解决了建议自己关issue :)

**Comment by BarryLiu1995** [comment]
我也遇到同样问题，请问如何解决
