### ISSUE TITLE
antd1.0.7版本要求rn版本最低是多少么；

### ISSUE THREAD

**Issue by sharingjingang050241** [ant-design/ant-design-mobile#1098]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:0.8.7
- Browser (or mark react-native) and its version（浏览器或react-native版本）:react-native 0.33.0
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

react-native 0.33.0版本 更新 antd-mobile到现在版本 1.0.7  报错

 UNMET PEER DEPENDENCY react-native@0.33.0

这个是有版本依赖么。

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L123

贴一下完整的报错，看是哪个组件对RN 有 0.33.0 的 peer 依赖

**Comment by sharingjingang050241** [comment]
![issue](https://cloud.githubusercontent.com/assets/20335157/24748847/9c447c56-1af3-11e7-8b62-97e07e89b476.png)

**Comment by paranoidjk** [comment]
你这还是 0.8.7。

**Comment by sharingjingang050241** [comment]
![isu](https://cloud.githubusercontent.com/assets/20335157/24749147/92e6a070-1af4-11e7-9105-62adee2a6f6f.png)

**Comment by sharingjingang050241** [comment]
![is](https://cloud.githubusercontent.com/assets/20335157/24749180/b450d4d8-1af4-11e7-8b7e-1b0374239e67.png)
@paranoidjk 
这个是直接重新安装antd-mobile 出现的结果。

**Comment by paranoidjk** [comment]
@sharingjingang050241 `npm install antd-mobile` 出现的?

**Comment by sharingjingang050241** [comment]
@paranoidjk 嗯 npm install antd-mobile --save .
就出现这个

**Comment by paranoidjk** [comment]
我这边没这个问题，建议你找个空目录试下？
然后可以给出你的 npm 版本

**Comment by sharingjingang050241** [comment]
@paranoidjk 
新建的项目可以正常安装，就是这个项目出现这个问题，npm是 4.1.几
