### ISSUE TITLE
0.7.0 遗留问题整理汇总

### ISSUE THREAD

**Issue by liqi07** [ant-design/ant-design-mobile#11]
- [x] datepicker rn组件功能问题 @warmhug 
- [x] toast 穿透问题 @silentcloud 
- [x] rn 框架(router ScrollView) 导致部分组件demo无法工作(RefreshControl/Drawer) @silentcloud

**Comment by silentcloud** [comment]
rn 框架这个在1.0里处理，0.7里不做这个改动 @liqi07

**Comment by silentcloud** [comment]
[x] toast 穿透问题  0.7.x 分支，待发布

**Comment by warmhug** [comment]
第三个问题是我添加的，这种公共问题、最好能优先搞搞吧？ @silentcloud

**Comment by yiminghe** [comment]
这个需要修复 https://github.com/ant-design/ant-design-mobile/issues/13

**Comment by yiminghe** [comment]
0.7.1 released. 2016-08-01 19:48 GMT+8

**Comment by silentcloud** [comment]
@warmhug 改这个问题要把目前 app 的代码改动大部分，需要些时间的，不适合在 0.7改

**Comment by silentcloud** [comment]
@warmhug  第三个问题已经搞定
