### ISSUE TITLE
modal操作弹窗在Android机样式异常

### ISSUE THREAD

**Issue by PatWu16** [ant-design/ant-design-mobile#1100]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:1.0.5
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

![default](https://cloud.githubusercontent.com/assets/23301139/24781862/1fded652-1b75-11e7-8950-f62cab5fed95.png)

#### What do you expected?（预期的正常效果）
![default](https://cloud.githubusercontent.com/assets/23301139/24781869/27cfceac-1b75-11e7-8ddb-eecf7da039c0.png)

#### What happen?（发生了何种非正常现象）
![default](https://cloud.githubusercontent.com/assets/23301139/24781881/37ddb836-1b75-11e7-937c-4d84b2386144.png)

#### Re-producible online demo (可复现的在线demo)

操作弹窗组件在ios上显示正常，在Android上显示异常，请问有什么解决方案吗？

**Comment by paranoidjk** [comment]
提问前请先搜索，另外，文档 demo 也有，仔细看下。
https://mobile.ant.design/components/modal-cn

https://github.com/ant-design/ant-design-mobile/issues/1030
