### ISSUE TITLE
用antd-mobile的icon时有些痛

### ISSUE THREAD

**Issue by junmaqiang** [ant-design/ant-design-mobile#1104]
感觉Bootstrap的icon比较全,可以拿来即用
而antd-mobile的icon提供的是架子,想用还得找一找(内置的几个不够用)

要是ant-design的团队把Bootstrap的icon都给svg化后,在提供一套就棒棒哒了!

**Comment by silentcloud** [comment]
@junmaqiang 这里原 antd 的大部分都有的 https://github.com/ant-design/ant-design-icons

**Comment by junmaqiang** [comment]
@silentcloud  看起来不错!  解决了我的问题!   谢谢你!
