### ISSUE TITLE
Popover 组件会被父元素高度影响 造成遮挡吗？有图

### ISSUE THREAD

**Issue by sharingjingang050241** [ant-design/ant-design-mobile#1107]
### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:1.0.7
- Browser (or mark react-native) and its version（浏览器或react-native版本）:0.33
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）: 魅族pro6 6.0

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
安卓引用 Popover 组件 ，被遮挡

#### What do you expected?（预期的正常效果）

![right](https://cloud.githubusercontent.com/assets/20335157/24798211/69fa0b60-1bc7-11e7-91ca-2aa2135d3d2a.png)
图1

#### What happen?（发生了何种非正常现象）

![wrong](https://cloud.githubusercontent.com/assets/20335157/24824231/36b771fc-1c3a-11e7-9f1a-73405cf57a7f.png)
图2

```
<View style={styles.toolbar}>
                        <Text style={{color:'#ffffff',fontSize:18,marginLeft:5,marginTop:20}}>发布</Text>
                        <Popover 
                            overlay={[
                                (<Item key="4" value="scan"  data-seed="logId"><Text>扫一扫</Text></Item>),
                                (<Item key="5" value="scan"  ><Text>摇一摇</Text></Item>),
                                (<Item key="6" value="scan"  ><Text>踹一踹</Text></Item>)
                            ]}
                            overlayStyle={{flex:1,height:100,width:100,alignItems:'center',justifyContent:'center'}}
                            contextStyle={{flex:1}}
                            triggerStyle={{flex:1}}
                            >
                            <Image source={addIco} style={{height:25,width:25,marginTop:25}}/>
                    </Popover>
            </View>

toolbar: {
    flexDirection: 'row',
    backgroundColor: '#f85f48',
    alignItems: 'center',
    height: 58,
    position:'relative'
  },
```

### IOS上面是好的，像上面图1，图2 是安卓手机出现的问题，

**Comment by sharingjingang050241** [comment]
### 这是这段代码，
<View style={styles.toolbar}>
                        <Text style={{color:'#ffffff',fontSize:18,marginLeft:5,marginTop:20}}>发布</Text>
                        <Popover 
                            overlay={[
                                (<Item key="4" value="scan"  data-seed="logId"><Text>扫一扫</Text></Item>),
                                (<Item key="5" value="scan"  ><Text>摇一摇</Text></Item>),
                                (<Item key="6" value="scan"  ><Text>踹一踹</Text></Item>)
                            ]}
                            overlayStyle={{flex:1,height:100,width:100,alignItems:'center',justifyContent:'center'}}
                            contextStyle={{flex:1}}
                            triggerStyle={{flex:1}}
                            >
                            <Image source={addIco} style={{height:25,width:25,marginTop:25}}/>
                    </Popover>
            </View>

**Comment by sharingjingang050241** [comment]
` <View style={styles.toolbar}>
                        <Text style={{color:'#ffffff',fontSize:18,marginLeft:5,marginTop:20}}>发布</Text>
                        <Popover 
                            overlay={[
                                (<Item key="4" value="scan"  data-seed="logId"><Text>扫一扫</Text></Item>),
                                (<Item key="5" value="scan"  ><Text>摇一摇</Text></Item>),
                                (<Item key="6" value="scan"  ><Text>踹一踹</Text></Item>)
                            ]}
                            overlayStyle={{flex:1,height:100,width:100,alignItems:'center',justifyContent:'center'}}
                            contextStyle={{flex:1}}
                            triggerStyle={{flex:1}}
                            >
                            <Image source={addIco} style={{height:25,width:25,marginTop:25}}/>
                    </Popover>
            </View>`

**Comment by paranoidjk** [comment]
@ant-design-bot markdown

**Comment by warmhug** [comment]
麻烦给出能说明问题的 完整的、最少化代码

**Comment by paranoidjk** [comment]
close for no response.

**Comment by HelloHxz** [comment]
这个问题是popover实质是react-native-menu，但是 <MenuContext style={{ flex: 1 }}>需要作为容器，所以会出现被遮住的问题·· 所以popover的native版本其实是错误的·

**Comment by silentcloud** [comment]
@HelloHxz  2.0 会在时间的容许下对 popover 进行重构
