### ISSUE TITLE
react-native下Flex会影响TouchableHighlight的onPress事件

### ISSUE THREAD

**Issue by kimjuny** [ant-design/ant-design-mobile#1108]
例如

```
TouchableHighlight(onPress={xxx})
  View
     Flex
       ...
     Flex
       ...
     Flex
       ...
```

整体被TouchableHighlight包裹，当我按下Flex下的控件时onPress事件就无法触发，只有我按其余的空白处才能触发onPress。这是BUG吗？

**Comment by silentcloud** [comment]
@pingan1927 这个之前反馈过，要改的，Flex 不能内嵌 Touchable

**Comment by warmhug** [comment]
之前的问题在这里 https://github.com/ant-design/ant-design-mobile/pull/756  https://github.com/ant-design/ant-design-mobile/issues/769#issuecomment-277894527

**Comment by silentcloud** [comment]
https://github.com/facebook/react-native/issues/6796

Flex  和 FlexItem 嵌套 Touchable，感觉要把这个移出去，Touch 的处理交给 children 来搞 @pingan1927

**Comment by silentcloud** [comment]
下个 break change 版本将会把 Flex 内置的 TouchableWithoutFeedback 去掉，交给用户自己在 children 里去写

**Comment by silentcloud** [comment]
closed for https://github.com/ant-design/ant-design-mobile/pull/2095
