### ISSUE TITLE
tabs无法设置选中的tab背景色

### ISSUE THREAD

**Issue by aiien007** [ant-design/ant-design-mobile#1109]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:^1.0.4
- Browser (or mark react-native) and its version（浏览器或react-native版本）:RN:~15.4.1
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）: win7x64

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
![weixinpng](https://cloud.githubusercontent.com/assets/8551421/24827255/8cb2f204-1c79-11e7-872c-f810348e1e46.png)

#### What do you expected?（预期的正常效果）
可以设置选中后Tabs的背景色
我查了api tabs只能设置选中线条颜色 和 选中文字颜色 
请问支持设置 选中后tab的背景色吗？
不支持的话该怎么修改代码控制？
谢谢

**Comment by kimjuny** [comment]
这个[issue](https://github.com/ant-design/ant-design-mobile/issues/1096)会帮到你

**Comment by aiien007** [comment]
@kimjuny
我先看到了这个issue，和我的是两个问题，用你说的问题里的barStyle我试过了可以设置所有tabs的背景色，但是没法实现选中的tab背景色改变

**Comment by paranoidjk** [comment]
暂不支持

**Comment by silentcloud** [comment]
@aiien007 有需求的话，可以去这里先提一个 issue https://github.com/skv-headless/react-native-scrollable-tab-view
