### ISSUE TITLE
DatePicker 希望去掉 moment 必选依赖，做成可选

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#111]
业务反馈 moment 库的代码里还是相对比较大，希望去掉

**Comment by yiminghe** [comment]
升级 atool-build 就好了, track  https://github.com/moment/moment/pull/3344

原则： 优秀的开源类库必须用

**Comment by yup9** [comment]
有同样的需求 ，不知道这个 [date-fns](https://date-fns.org/) 符不符合要求， 可以考虑看看
