### ISSUE TITLE
发现一个比较诡异的问题，Tabs+InputItem组件+autoFocus属性，出现BUG

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design-mobile#1112]
版本：antd-mobile:1.0.x

设备：PC chrome浏览器，IOS浏览器...

问题：在Tabs组件中加入InputItem组件并且加上autoFocus属性，就会出现BUG。

PC chrome浏览器,切换Tabs组件菜单时界面闪现，

在IOS浏览器上，界面就出现偏移

在线参考DEMO：https://codepen.io/motorfu/pen/qrzJQO

**Comment by paranoidjk** [comment]
@pingan1927 看下是不是 js focus 引起的

**Comment by pingan1927** [comment]
@MotorFu 这个找到原因了，`autoFocus`会被input标签接收到并产生作用，这周小版本修复

**Comment by MotorFu** [comment]
好的，谢谢

**Comment by pingan1927** [comment]
你先把Tabs的animated设为false吧，input标签移除`autoFocus`，在真机也会有问题。看来是动画和唤起虚拟键盘冲突了。需要再研究下，最新版本的autoFocus只支持支付宝客户端，你如果不是在支付宝客户端内开发，就升级下版本吧。

**Comment by paranoidjk** [comment]
@pingan1927 已经修复的 issue close 掉， commit log 里面关联 issue。
