### ISSUE TITLE
视觉看起来变大了,有统一的地方整理不

### ISSUE THREAD

**Issue by junmaqiang** [ant-design/ant-design-mobile#1114]
以上是在手机浏览器上看到的效果,感觉好大呀, 请问兄弟们 哪里可以调整啊!  

我尝试过配置 .roadhog.js 文件里面的 theme,如下:

 ``` 
 theme : {
    "@primary-color": "#1DA57A",
    "@link-color": "#1DA57A",
    "@border-radius-base": "2px",
    "@font-size-base": "16px",
    "@line-height-base": "1.2"
  }
```

例如上面我把16px 修改为12px,仅仅部分小地方被修改了!
我想问,有么有解决方案,让我的视觉好看一些,至少尺寸比例好看一些!

**Comment by paranoidjk** [comment]
IMPORTANT: Please use the following link to create a new issue:

  http://new-issue.ant.design

If your issue was not created using the app above, it will be closed immediately.



注意：请使用下面的链接来新建 issue：

  http://new-issue.ant.design

不是用上面的链接创建的 issue 会被立即关闭。
