### ISSUE TITLE
服务端渲染renderToString listview

### ISSUE THREAD

**Issue by GZWZC** [ant-design/ant-design-mobile#1117]
if i want to use renderToString，how should i do with listview?

**Comment by GZWZC** [comment]
The first 10 is the server rendering，and the other is Client rendering

**Comment by paranoidjk** [comment]
@warmhug Does ListView support usage like this ?

@cncolder any suggestion or experience to share?

https://github.com/ant-design/ant-design-mobile/issues/1059

**Comment by cncolder** [comment]
ListView support server side render.

@GZWZC you need feed the first 10 rows to DataSource on server side.

Do you mean fetch more data on end reached about _other is Client rendering_? 

```jsx
class extend React.Component {
  constructor () {
    super()

    const dataSource = new ListView.DataSource({
      getSectionHeaderData: (data, sectionID) => sectionID,
      sectionHeaderHasChanged: (s1, s2) => s1 !== s2,
      getRowData: (data, sectionID, rowID) => data[rowID],
      rowHasChanged: (r1, r2) => r1 !== r2
    })

    this.state = {
      dataSource: dataSource.cloneWithRowsAndSections(
        ...this.createDataSource('Your first 10 rows data')
      )
    }
  }

  onEndReached (e) {
    if (loading || !e) return

    fetchMoreData()
  }

  render() {
    return (
      <ListView
        dataSource={dataSource}
        initialListSize={10}
        renderSectionHeader={this.renderSectionHeader}
        renderRow={this.renderRow}
        pageSize={10}
        useBodyScroll
        onEndReached={this.onEndReached}
      />
    )
  }
}
```

**Comment by GZWZC** [comment]
@cncolder thanks you,I have used ListView  For client Render in my code，Now I'm learning react-server-render， i send this issue so that i can write the code For ListView-Server-Render,
