### ISSUE TITLE
Update deprecation code for React@16

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1118]
updated by @paranoidjk

https://github.com/react-component/slider/pull/252
https://github.com/ant-design/ant-design/issues/5678
https://github.com/ant-design/ant-design-mobile/pull/1171

- [x] [rc-collapse](https://github.com/react-component/collapse) 1.7.0
- [x] [rc-table](https://github.com/react-component/table) 5.3.1
- [x] [rc-input-number](https://github.com/react-component/input-number]) 3.4.13
- [x] [rc-slider](https://github.com/react-component/collapse) 7.0.1
- [x] [rc-steps](https://github.com/react-component/steps) 2.5.1
- [x] [rc-tooltip](https://github.com/react-component/tooltip) 3.4.3
- [x] [rc-checkbox](https://github.com/react-component/checkbox) 2.0.0
- [x] [rc-tabs](https://github.com/react-component/tabs) 7.5.0
- [x] [rc-touchable](https://github.com/react-component/touchable) @cncolder 
- [x] https://github.com/react-component/m-picker @silentcloud
- [x] https://github.com/react-component/m-date-picker @silentcloud
- [x] https://github.com/react-component/m-cascader @silentcloud
- ~~[ ] https://github.com/react-component/m-select-list~~
- ~~[ ] https://github.com/react-component/m-pull-to-refresh~~
- ~~[x] [nuka-carousel](https://github.com/FormidableLabs/nuka-carousel/issues/216)~~ （move rmc-nuka-carousel）

even upgrade minor version in `~` syntax is unnecessary , still change it expicity in order to check on by one

### Version
1.0.8

### Environment
web

### Reproduction link
[https://github.com/facebook/react/releases/tag/v15.5.0](https://github.com/facebook/react/releases/tag/v15.5.0)

### Steps to reproduce
Search `React.createClass` in `./components`

### What is expected?
Transform `React.createClass` to plain JavaScript classes

### What is actually happening?
There are 8 results under `./components`

---
[React@15.5.0](https://github.com/facebook/react/releases/tag/v15.5.0) add two deprecation warning. `React.createClass` and `React.PropTypes`. We are lucky bcs we use Typescript to check prop types. But we still have 8 lines `React.createClass` stay there.

Also need update all react-components dependencies.

```
Warning: React.createClass is deprecated and will be removed in version 16.
  Use plain JavaScript classes instead.
  If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

**Comment by paranoidjk** [comment]
https://github.com/react-component/slider/pull/252

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design/issues/5678

**Comment by paranoidjk** [comment]
- [x] [rc-collapse](https://github.com/react-component/collapse) 1.7.0

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/pull/1171

**Comment by cncolder** [comment]
- [] [touchable](https://github.com/react-component/touchable)

**Comment by paranoidjk** [comment]
- [ ] https://github.com/react-component/m-picker

**Comment by warmhug** [comment]
m-select-list 现在已经不维护，先可以不用改

**Comment by paranoidjk** [comment]
@warmhug @silentcloud @pingan1927 这个剩下的各自来认领，尽量 clean 掉。也检查下还有没有漏的

**Comment by silentcloud** [comment]
好 认领一个 m-picker

**Comment by silentcloud** [comment]
https://github.com/react-component/m-picker/pull/25

**Comment by hb-bobo** [comment]
PopupPicker  还有报错

**Comment by silentcloud** [comment]
剩下两个，等发布，PR 已提交了

**Comment by paranoidjk** [comment]
I think we already fixed this. 😄
