### ISSUE TITLE
site style issues

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#1123]
<img width="343" alt="image" src="https://cloud.githubusercontent.com/assets/507615/24890526/f7cf6592-1ea2-11e7-8486-d3616ef4cfae.png">

---

<img width="176" alt="image" src="https://cloud.githubusercontent.com/assets/507615/24890552/1c16677a-1ea3-11e7-97a5-40a02d969663.png">

---

<img width="161" alt="image" src="https://cloud.githubusercontent.com/assets/507615/24890565/3394edcc-1ea3-11e7-8531-a192cf026cc7.png">

---

<img width="131" alt="image" src="https://cloud.githubusercontent.com/assets/507615/24890599/588c331a-1ea3-11e7-8ef9-451fd04fcc5b.png">

---

Mac Chome 版本 57.0.2987.133 (64-bit)

**Comment by paranoidjk** [comment]
第三个： https://github.com/ant-design/ant-design-mobile/pull/1076

第二个和第四个是啥问题？...没看出来

**Comment by afc163** [comment]
2 参考 ant design。
4 二维码看上去渲染的很诡异，估计是加粗了。
