### ISSUE TITLE
inputItem碰到了个问题，点击inputItem后出现输入法键盘开始编辑，但是点击手机上的返回键时，不是输入法取消而是退回到上一个页面。

### ISSUE THREAD

**Issue by jiangzhongxi123** [ant-design/ant-design-mobile#1127]
inputItem碰到了个问题，点击inputItem后出现输入法键盘开始编辑，但是点击手机上的返回键时，不是输入法取消而是退回到上一个页面。

**Comment by paranoidjk** [comment]
> 提issue要参考 http://new-issue.ant.design/ 给出必要信息。

手机返回键是组件无法控制的，给出你的机型，浏览器版本等。

**Comment by paranoidjk** [comment]
cc @pingan1927
