### ISSUE TITLE
Carousel 当只有一张图片时显示不正确

### ISSUE THREAD

**Issue by weiq** [ant-design/ant-design-mobile#1132]
### Version
1.0.8

### Environment
chrome, ios 

### Reproduction link
[http://codepen.io/weiq/pen/jBxxJx?editors=0010](http://codepen.io/weiq/pen/jBxxJx?editors=0010)

### Steps to reproduce
看代码中的注释，有三张图片时可以显示正确，当只有一张图片时高不正确

### What is expected?
一张图片时也可显示正确

### What is actually happening?
高度不正确

**Comment by warmhug** [comment]
1 张图片时 `selectedIndex={1}` 改为 0 ，或者不要设置

**Comment by silentcloud** [comment]
参见 warmhug 的方案，另外改后你的高度要设置好，issue 关了

**Comment by weiq** [comment]
@silentcloud @warmhug 去掉selectedIndex还是不好使，高度不是取的图片本身高度么？

http://codepen.io/weiq/pen/jBxxJx?editors=0010 麻烦可以看一下

![capture_2017412_151148](https://cloud.githubusercontent.com/assets/1697158/24945566/63b03710-1f92-11e7-8de5-c835a46085ce.jpg)

**Comment by silentcloud** [comment]
@weiq 没明白你 

```
this.setState({
       initialHeight: null,
});
```
这个代码是干嘛的，我去掉后，给 a 标签加了 display: 'block' 就可以了

**Comment by weiq** [comment]
@silentcloud 那个是文档例子里的写法，我也没看明白，加了block好使了 :)
