### ISSUE TITLE
ERROR in ./~/antd-mobile/lib/list-view/index.js

### ISSUE THREAD

**Issue by GZWZC** [ant-design/ant-design-mobile#1141]
ERROR in ./~/antd-mobile/lib/list-view/index.js
Module not found: Error: Can't resolve 'react-native' in 'E:\test\node_modules\antd-mobile\lib\list-view'

listView这个组件是否依赖react-native

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1119
