### ISSUE TITLE
已设置高清方案但是引入ant-moblie字体样式 很大

### ISSUE THREAD

**Issue by JSlife23** [ant-design/ant-design-mobile#1142]
样式如下：
![sd dl ekpqjl9tmd9z h](https://cloud.githubusercontent.com/assets/7855952/24987211/43749e42-2031-11e7-8374-42801c97bb61.png)

![2_ t 34 yqix b ybk6n](https://cloud.githubusercontent.com/assets/7855952/24987313/e4286a30-2031-11e7-87cc-0a28c26a76a8.png)
更官网样式相差太远
"antd-mobile": "^1.0.8"
"babel-plugin-import": "^1.1.1",

**Comment by jokerapi** [comment]
html上的font-size太大了

**Comment by pingan1927** [comment]
检查下viewport设置，不要写死，iPhone5生成的viewport应该是(因为window.devicePixelRatio=2)
`<meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=0.5,maximum-scale=0.5,minimum-scale=0.5">`
参考：
https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-以上版本「高清」方案设置

**Comment by JSlife23** [comment]
@pingan1927 谢谢是写死了viewport 问题解决了。

**Comment by paranoidjk** [comment]
@JSlife23 已解决的建议自己关闭issue
