### ISSUE TITLE
antd-mobile@1.0.8 when Toast after validateFields ,the screen can not move; this issue is very dangerous!!!

### ISSUE THREAD

**Issue by r4ggj** [ant-design/ant-design-mobile#1143]
`	this.props.form.validateFields((err, values) => {
		if (err) {
			Toast.info('sdfdsf',1.5);
                      return;

              }
           }`

**Comment by paranoidjk** [comment]
@ant-design-bot markdown

**Comment by r4ggj** [comment]
I use rc-form to manage my form,and when i validate form ,use this method `
this.props.form.validateFields((er,values)=>{
  if(err){
    Toast.info('this is a message',1.5); //this line cause the problem;after toast ,screen can not move anymore;
    return;
  }
});
`

**Comment by r4ggj** [comment]
sorry i'm chinese ,my english is poor ,so i can't do a demo

**Comment by paranoidjk** [comment]
@r4ggj demo 与你用什么语言无关，写出简要代码吧 http://codepen.io/paranoidjk/pen/LWpaKe 能帮我们节省很多时间，感谢~

**Comment by paranoidjk** [comment]
我本地测试没有问题，请给出可重现的demo。
