### ISSUE TITLE
【RN】Steps.Step的description换行问题

### ISSUE THREAD

**Issue by lyw1991** [ant-design/ant-design-mobile#1144]
![qq 20170413134928](https://cloud.githubusercontent.com/assets/18585437/24991797/195dea18-2050-11e7-8cd6-ba5488477829.png)
如图，我想在Step的description里进行换行，但这样写两个Text还是在同一行里显示，请问有没有什么解决方法？

**Comment by silentcloud** [comment]
@lyw1991 用 View 来做 container

**Comment by lyw1991** [comment]
@silentcloud 我试过用View的，但用View了以后description就不显示了

**Comment by silentcloud** [comment]
@lyw1991 没问题啊

![image](https://cloud.githubusercontent.com/assets/1698185/24992004/5c04d3ee-2051-11e7-9efa-b24a46a6f964.png)

**Comment by lyw1991** [comment]
@silentcloud sorry，是我Text里的样式写的有问题，谢谢拉！
