### ISSUE TITLE
[React-Native]TabBar设置icon会报错：Invalid data message - all must be length: 13

### ISSUE THREAD

**Issue by kimjuny** [ant-design/ant-design-mobile#1149]
### Version
1.0.7

### Environment
react-native@0.42.3, react@15.4.2

### Reproduction link
[http://codepen.io/kimjuny/pen/xdbgNb](http://codepen.io/kimjuny/pen/xdbgNb)

### Steps to reproduce
TabBar只要设置icon就会报错：Invalid data message - all must be length: 13

### What is expected?
正常显示

### What is actually happening?
报错

**Comment by silentcloud** [comment]
@kimjuny RN TabBar 只能传 imagesource

https://github.com/ant-design/ant-design-mobile/blob/master/components/tab-bar/TabBarItem.tsx#L46

RN 官方的 TabBar 不支持 Icon（字体），必须是 RN 的 Image 类型
