### ISSUE TITLE
RN 打包发布，Toast不显示

### ISSUE THREAD

**Issue by qinly** [ant-design/ant-design-mobile#1154]
### Version
1.0.8

### Environment
react-native@0.43.3

### Reproduction link
[https://github.com/facebook/react-native](https://github.com/facebook/react-native)

### Steps to reproduce
RN 打包发布后，Toast不出现。开发模式也要reload后才能加载出现Toast提示，是为什么呢？
```
import { NoticeBar, WhiteSpace, Icon, Toast } from 'antd-mobile';

Toast.success('已注册', 5, () => {});
```
同样的ActionSheet也类似无效，无奈换成这种方式：    
```import Toast from 'antd-mobile/lib/toast';```

打包方式：    
```
cd android && ./gradlew assembleRelease
```

### What is expected?
RN 打包发布后 Toast正常显示

### What is actually happening?
Toast不显示，代码不执行

**Comment by silentcloud** [comment]
> 同样的ActionSheet也类似无效，无奈换成这种方式：
> import Toast from 'antd-mobile/lib/toast';

换成这种可以显示？

**Comment by qinly** [comment]
目前实际使用到的Button, List, Stepper, Flex 组件正常
```
import { Button, List, Stepper, Flex } from 'antd-mobile';
const Item = List.Item;
const Brief = Item.Brief;
```
`Toast`/`ActionSheet`这种无效。

**Comment by silentcloud** [comment]
`import { Toast } from 'antd-mobile'  这种不行?
`import Toast from 'antd-mobile/lib/toast'`  这种可以？

不应当啊，代码打个包发上来吧

**Comment by paranoidjk** [comment]
close for no response.

**Comment by Caballarii** [comment]
同样遇到了Toast不显示的问题，主要是不显示图片，包括Checkbox不显示图片，主要是打包bundle的时候未能将图片打入assets(ios)/res(android)文件夹，需要手动拷过去就行，android需要将文件名里的／改成_放入drawable各文件夹下

**Comment by silentcloud** [comment]
@Caballarii 注意你自己的打包脚本是否正确。
参考 https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L159
