### ISSUE TITLE
Picker样式问题

### ISSUE THREAD

**Issue by AlexTMing** [ant-design/ant-design-mobile#1157]
#  在移动端 Picker里如何修改里面的样式 ??

下面是官网的例子 比如 我要修改里面的 extra 的字体颜色大小之类
<Picker
          data={seasons}
          title="选择季节"
          cascade={false}
          extra="请选择(可选)"
          value={this.state.sValue}
          onChange={v => this.setState({ sValue: v })}
        >
          <List.Item arrow="horizontal">选择季节（多列，不联动）</List.Item>
        </Picker>

查看了其他的issue 说是覆盖样式  这个在移动也可以吗?  如果可以这个要在哪里加呢
    prefixCls: 'am-picker',
    pickerPrefixCls: 'am-picker-col',

**Comment by paranoidjk** [comment]
props.prefixCls

**Comment by AlexTMing** [comment]
嗯 能多说几句吗?  这个我没听懂啊  不好意思 麻烦了
