### ISSUE TITLE
Tabs组件滑动会被卡住

### ISSUE THREAD

**Issue by jyz1508** [ant-design/ant-design-mobile#1159]
官网Tabs组件，第三个demo ，开启swipeable 在部分安卓机下会卡住不能滑动。   直接复制demo到chrome上就能复现，firefox下正常.    手机上ios和小米正常，魅蓝note3会被卡住

**Comment by paranoidjk** [comment]
PC上的问题暂时没有精力处理。

手机上滑动卡住， 具体是滑动 Tabs 的内容区 还是 头部区域？

**Comment by jyz1508** [comment]
都有，内容区域很明显卡住，头部区域只是偶尔回不到原位置

**Comment by jyz1508** [comment]
但是是自带浏览器没问题，是装的chrome会出现   安卓5.1  chrome版本57.0.2987.126

**Comment by warmhug** [comment]
@jyz1508 有相似 issue，注释里最好关联下 #741

**Comment by jyz1508** [comment]
好的，下次知道了，发帖后才发现有同样的issue

**Comment by paranoidjk** [comment]
since duplicate, close. Please track at https://github.com/ant-design/ant-design-mobile/issues/741
