### ISSUE TITLE
ListView转换成html以后有好多react-text字段,导致有很多空白

### ISSUE THREAD

**Issue by liche501** [ant-design/ant-design-mobile#1160]
### Version
1.0.5

### Environment
mac 10.12.3 (16D32) chrome

### Reproduction link
[http://mobilepos-staging.p2shop.cn/#/login?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JwSWQiOiIxIiwidXNlcklkIjoiODIiLCJhcHBsaWNhdGlvbklkIjoiNyIsImV4cCI6MTQ5MjY2ODMyOSwiaXNzIjoibG9naW4ifQ.dpnbDwnuw5AgwFsmUQ4mFKDc-RGTGXMvbrtvz6IeCzE](http://mobilepos-staging.p2shop.cn/#/login?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JwSWQiOiIxIiwidXNlcklkIjoiODIiLCJhcHBsaWNhdGlvbklkIjoiNyIsImV4cCI6MTQ5MjY2ODMyOSwiaXNzIjoibG9naW4ifQ.dpnbDwnuw5AgwFsmUQ4mFKDc-RGTGXMvbrtvz6IeCzE)

### Steps to reproduce
```javascript
<!-- react-text: 53 -->&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    <!-- /react-text -->
```
代码里有好多类似于这种的代码导致多余的空白。

### What is expected?
删除多余的空白

### What is actually happening?
listview里的item中有多余的空白

---
截图
http://wxshop-auto.oss-cn-shanghai.aliyuncs.com/img/iphone-img.png

**Comment by paranoidjk** [comment]
给出你的demo代码？渲染出这个多空格应该不是组件的问题。

cc @cncolder 你有过ssr使用经验，有发现这个问题吗？

**Comment by liche501** [comment]
@paranoidjk @cncolder 
我更新了截图，请参考

**Comment by paranoidjk** [comment]
你的截图我没看出问题，你给的网页代码里也没有你说的空白转义符。

请给出可重现的demo或代码。

**Comment by paranoidjk** [comment]
cc @warmhug ListView 原作者是你，看看有没有渲染多余空格的可能。

**Comment by warmhug** [comment]
ListView 是抽象的底层组件，不修改组件里具体的内容。麻烦检查下自己代码，帮忙确认问题
