### ISSUE TITLE
一个问题。

### ISSUE THREAD

**Issue by Jackie-Web** [ant-design/ant-design-mobile#1161]
我引用ui框架后，控制台会报错
![image](https://cloud.githubusercontent.com/assets/11611057/25087966/6056a470-23a5-11e7-9ec0-ba36372d76f0.png)
可能是react的最新版本已经不想去支持createClass 这个属性了，不知道是否能升级一下，在组件里做容错？还是去支持最新的写法。

**Comment by paranoidjk** [comment]
duplicated https://github.com/ant-design/ant-design-mobile/issues/1118
