### ISSUE TITLE
InputItem兼容性问题

### ISSUE THREAD

**Issue by jackYouth** [ant-design/ant-design-mobile#1162]
当type为phone时，在华为荣耀中，有兼容性问题，当输入第四位数字时，光标停留在第四个数字之前

![c3a645298eb1223b5476e66500e072bc](https://cloud.githubusercontent.com/assets/23489336/25114760/a5255dba-2433-11e7-98f0-dace5123ee67.jpg)
![07d7c1d5413eb52f96b3c085f0b2c410](https://cloud.githubusercontent.com/assets/23489336/25114764/a98fb8dc-2433-11e7-9cdd-b174a0cc056e.jpg)

**Comment by paranoidjk** [comment]
duplicated https://github.com/ant-design/ant-design-mobile/issues/810
