### ISSUE TITLE
关于searchBar取消按钮的建议

### ISSUE THREAD

**Issue by tolg** [ant-design/ant-design-mobile#117]
searchBar组件的取消按钮功能与清除图标的功能重复，没有太大意义，而很多场景中这里放置一个“搜索”按钮会更合适。建议把这个按钮作为可配置的，可以显示任何文字也可以始终不显示按钮（目前仅可配置文字），点击行为作为属性由外部传入，目前取消按钮会调用onCancel属性函数，但文档里没写，希望这个点击处理只执行外部传入的函数，而诸如清楚内容这些功能则由组件的方法提供。

**Comment by pingan1927** [comment]
这个我们会联系交互设计师考虑下。

`清除`操作搜索框还会继续获得光标。

`取消`则不再获得光标。

“搜索”设计上是通过点击虚拟键盘的enter键触发。

**Comment by pingan1927** [comment]
> 目前取消按钮会调用onCancel属性函数，但文档里没写，希望这个点击处理只执行外部传入的函数，而诸如清除内容这些功能则由组件的方法提供。

这个建议我们再慎重考虑下哈，多谢你的建议。

**Comment by pingan1927** [comment]
下一个大版本已经做放开取消按钮的行为，0.7.x版本缓两天再决定是否更新

**Comment by warmhug** [comment]
0.9 文档已有注释，此 issue 无效
