### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by liang869219658** [ant-design/ant-design-mobile#1170]
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-aDF0S1KtOesRBAL1RZ+4udo7TvBPG3BaH1xB81dOuWk='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by paranoidjk** [comment]
read the issue template.
