### ISSUE TITLE
DatePicker组件如何支持日期+小时的格式

### ISSUE THREAD

**Issue by aiien007** [ant-design/ant-design-mobile#1172]
### What problem does this feature solve?
业务需求是选择日期 小时来记录时间，DatePicker 组件mode中的datetime 点击控件弹出的是日期 时分的格式，是否支持只可以选择 日期 小时 或者 分钟固定无法选择调整

### What does the proposed API look like?
mode 支持 选择日期 小时 或者 无法修改分钟

**Comment by paranoidjk** [comment]
https://github.com/react-component/m-date-picker#api

`mode="datetime"`

**Comment by aiien007** [comment]
@paranoidjk  mode="datetime"带上了分钟 无法满足我的描述啊

**Comment by paranoidjk** [comment]
暂不支持，欢迎PR。
