### ISSUE TITLE
Icon 内置 svg 按需加载

### ISSUE THREAD

**Issue by xfcdxg** [ant-design/ant-design-mobile#1176]
Updated by @paranoidjk

## Proposal API 

type: string --> source: file object

```tsx
import  Icon from 'antd-mobile/lib/icon';
import  loading from 'antd-mobile/lib/svg/loading.svg'; 
// or may be this
// import loading from 'antd-mobile-icon/loading.svg';

import fooIcon from '../foo/bar/svg/fooIcon.svg';

<Icon source={loading} />
<Icon source={fooIcon} />
```

- - -
### What problem does this feature solve?
Icon打包后的文件大小过大

### What does the proposed API look like?
是否可以按需引用svg？

**Comment by paranoidjk** [comment]
内置的只有十几个 Icon，已经经过精简了。

@warmhug 下个版本考虑所以内置icon抽出来？

**Comment by xfcdxg** [comment]
@paranoidjk 主要有些业务场景下是只需要用到本地私有SVG的。

**Comment by paranoidjk** [comment]
- 考虑下个大版本改成按需加载
- 本周的patch会用 https://github.com/svg/svgo 把内置svg压缩处理一遍。

**Comment by pingan1927** [comment]
* 本周的patch会用 https://github.com/svg/svgo 把内置svg压缩处理一遍。

这个优化提交了

**Comment by paranoidjk** [comment]
@pingan1927 没看到commit，有统计大小有多少减少吗？

**Comment by pingan1927** [comment]
很多都可以减少50%左右。没必要统计出来吧。就更文件压缩一样。

**Comment by paranoidjk** [comment]
- es6 module 是静态的， [这行代码](https://github.com/ant-design/ant-design-mobile/blob/master/components/icon/index.web.tsx#L24) 的效果是引用 Icon 必然伴随引用内置的所有 svg 文件。
- 暂时没什么好的 lazyload 思路： https://www.zhihu.com/question/50167587。
- 2.0 可以考虑将  svg 源文件与 Icon 组件的引入分离。

cc @warmhug @afc163 一起看看有没有其他好的设计

**Comment by bear-new** [comment]
引入的本地svg图标，```<Icon type={require('../ant-design-icons/share/keep.svg')} />``` ,无效果，官方文档上通过icon使用svg图标写的需要配置wepack.config.js,但是我通过react-native-cli搭建的项目没有这个文件- -，你是怎么使用svg图标的啊，求指导

**Comment by xfcdxg** [comment]
@bear-new 我的是Web端项目，就是用Webpack来构建的。RN应该用不了自定义图标吧？具体可以咨询一下 antd项目组~ 0_0

**Comment by benjycui** [comment]
这个问题昨天和 @warmhug 讨论过，问题在于，无论是 webpack 的 require.ensure 还是 ESNext 的新语法，都会到时 antd-mobile 打包时生成 n 个文件，如：`antd-mobile.js` `antd-mobile-icon-xxx.js`。 这样使用起来会很麻烦的吧。

**Comment by benjycui** [comment]
想了下，antd-mobile web 版的使用方式有两种，dist 文件和 npm，用了 dist 文件基本意味着不在乎大小了。

所以是 npm 包使用的时候要按需加载 icon。

如果真的要支持 icon 按需加载，就意味着：
1. 发布构建时，如果是构建生成 dist 文件，就只打包成 antd-mobile.js(不然多个文件使用起来很蛋疼)。
2. 如果是 npm 包的引入方式，用户构建时才使用 webpack 或者 ESNext 的按需加载，但这样会跟工具绑定？

**Comment by benjycui** [comment]
然后就是 Icon 按需加载的粒度的问题。

**Comment by silentcloud** [comment]
@bear-new  rn 项目看一下 icon 文档，有说明的

**Comment by paranoidjk** [comment]
@benjycui svg-sprite-loader 构建后的产物不是 svg 文件，而是 js 代码，这段代码动态的往 html 里面插入 `<svg>` 标签

**Comment by bear-new** [comment]
@silentcloud  看了，但是用上没反应，你们有在rn中用到Icon来加载svg图标吗

**Comment by benjycui** [comment]
> @benjycui svg-sprite-loader 构建后的产物不是 svg 文件，而是 js 代码，这段代码动态的往 html 里面插入 <svg> 标签

所以就是我之前说的那样吧 https://github.com/ant-design/ant-design-mobile/issues/1176#issuecomment-300423005 https://github.com/ant-design/ant-design-mobile/issues/1176#issuecomment-300426825

**Comment by paranoidjk** [comment]
## Proposal API

```tsx
import  Icon from 'antd-mobile/lib/icon';
import  loading from 'antd-mobile/lib/svg/loading.svg'; 

import fooIcon from '../foo/bar/svg/fooIcon.svg';

<Icon source={loading} />
<FooIcon source={fooIcon} />
```

**Comment by paranoidjk** [comment]
https://stackoverflow.com/questions/25384360/how-to-prevent-moment-js-from-loading-locales-with-webpack/25426019#25426019

**Comment by paranoidjk** [comment]
close in favor of https://github.com/ant-design/ant-design-mobile/pull/1740
