### ISSUE TITLE
Upgrade react-native

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1177]
https://github.com/ant-design/ant-design-mobile/commit/88ff73439e3cd420713be3c49be42275ef477b69

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15610#issuecomment-294665430

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15610#issuecomment-295138235

**Comment by silentcloud** [comment]
这个现在升不到最新版 RN(0.43.4) 要求 react 要 16 才行，只能升到 0.42

**Comment by paranoidjk** [comment]
那如果有空的话就先升到 0.42 看看， 16 到时候一起升。
