### ISSUE TITLE
高清解决方案无效

### ISSUE THREAD

**Issue by liang869219658** [ant-design/ant-design-mobile#1178]
https://github.com/liang869219658/antd-mobile

**Comment by paranoidjk** [comment]
请至少给出必要的排查信息，请阅读issue模板。

**Comment by liang869219658** [comment]
<img width="1067" alt="2017-04-19 3 51 08" src="https://cloud.githubusercontent.com/assets/20026154/25168997/0e859b64-2518-11e7-8a81-374ae41a3d07.png">

**Comment by liang869219658** [comment]
但到了手机上就无效了

**Comment by paranoidjk** [comment]
抱歉你一张图片我看不出问题。

https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE

很多业务在用高清方案，check你自己的配置和使用。

**Comment by liang869219658** [comment]
已经提交到github了

**Comment by liang869219658** [comment]
你本地跑一下不就知道了
