### ISSUE TITLE
RefreshControl 有没有办法阻止click事件穿透问题。

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design-mobile#118]
#### 本地环境

- antd-mobile 版本：0.7.2
- 操作系统及其版本：
- 浏览器及其版本：

#### 你做了什么？
` <RefreshControl loadingFunction={this.loadingFunction} distanceToRefresh={60}  resistance={1} style={{position: relative, }}
                        hammerOptions={{
          touchAction: auto,
          recognizers: {
            pan: {
              threshold: 100,
            },
          },
        }} ><div onclick=function(){}></div></RefreshControl >`

有时正好点到div，onclick事件会等刷新完后执行。有没有办法阻止？

**Comment by warmhug** [comment]
阻止什么？阻止 click 事件执行吗？

**Comment by ksh033** [comment]
是

**Comment by warmhug** [comment]
这个阻止不合适吧？我试了下感觉没受到什么影响

**Comment by ksh033** [comment]
'<RefreshControl >
 <ListView>
    <div onclick="function(){history.push, {
          pathname:'url'
        }}">
<LisView>
</RefreshControl >'我列表的项的div有一个click事件做页面跳转，当我想下拉刷新时时候正好点了div，这样后面就马上做了页面跳转。我原本只想刷新的。

**Comment by ksh033** [comment]
@warmhug 换成<Hammer onPress={function{}}></Hammer> 就会不会了。原生的click确实有问题,click没办法判断是否在拖动还是点击。

**Comment by yiminghe** [comment]
业务使用 fastclick
