### ISSUE TITLE
高清方案在iPhone7p iPhone6p失效

### ISSUE THREAD

**Issue by liang869219658** [ant-design/ant-design-mobile#1180]
以下是我的问题项目链接
https://github.com/liang869219658/antd-mobile

**Comment by paranoidjk** [comment]
duplicated  https://github.com/ant-design/ant-design-mobile/issues/1178

请不要故意重复提isseu ！ 

需要排查问题，issue 模板写得很清楚, 非 http://new-issue.ant.design/ 都会关闭。
