### ISSUE TITLE
RN 样式文件改成纯对象，方便自定义单个组件

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1182]
目前也是可以支持自定义单个组件样式，但是有点绕，需要先 StyleSheet.flatten ，然后在 create；

将 StyleSheet.create 放在组件里去

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1174

**Comment by SweetJunY** [comment]
请具体的告诉一下自定义单个组件样式的方法，StyleSheet.flatten ，然后在 create？这个看不懂啊，谢谢请简单的事例一下，谢谢。

**Comment by xudaolong** [comment]
@silentcloud 
```
import ListItemStyle from 'antd-mobile/lib/list/style/index.js';
// 当前组件设定
const newStyle = {};
for (const key in ListItemStyle) {
    if (Object.prototype.hasOwnProperty.call(ListItemStyle, key)) {
        // StyleSheet.flatten返回的obj描述中的configurable、writable为false，所以这里要展开赋值
        newStyle[key] = { ...StyleSheet.flatten(ListItemStyle[key]) };
        if (key === 'Header') {
            newStyle[key].color = '#fff';
        }
    }
}

```
这个应用在list就不可以修改了.
提示
![image](https://cloud.githubusercontent.com/assets/9654838/26773520/353b124c-49fe-11e7-973e-caf8eea899ad.png)

**Comment by xudaolong** [comment]
@silentcloud  发现 listItem 是没有 _reactNative.StyleSheet.create 的...

**Comment by silentcloud** [comment]
@xudaolong 额，List 估计是最初改漏了，目前 List 已经是纯对象了，那就用纯对象的方式，不需要 StyleSheet.flatten 那么麻烦
