### ISSUE TITLE
Grid 子元素高度设置问题

### ISSUE THREAD

**Issue by yuyongmao** [ant-design/ant-design-mobile#1183]
可否试着Grid子元素的高度 ，如果能设置的话，怎么设置，谢谢了

**Comment by paranoidjk** [comment]
Grid 就是正方形布局，不支持设置高度。

**Comment by cncolder** [comment]
@yuyongmao 可以试着指定 renderItem 属性自定义单元格。

**Comment by yuyongmao** [comment]
@cncolder 没有效果，我用的flexwrap 算好宽度 这样效果跟grid 差不多的

**Comment by cncolder** [comment]
@yuyongmao 自从 1.0.9 Grid 重构以后，单元格正方形是在 renderItem 父级样式上控制的，所以现在 Grid 只能是正方形了。

**Comment by NICK-DUAN** [comment]
那能不能使用百分比设置grid的宽度？
