### ISSUE TITLE
[React-Native]InputItem的type检查bug

### ISSUE THREAD

**Issue by kimjuny** [ant-design/ant-design-mobile#1184]
1. type="phone"，电话检查不起作用，可以输入无限位
2. type="number"，没检查

**Comment by paranoidjk** [comment]
#1185

**Comment by silentcloud** [comment]
第一个问题：传 maxLength 控制输入位数（有些手机号不是11位，不能写死）， https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.tsx#L151 这里针对  `phone` 用了键盘类型限制；
第二个问题: type="number"，不需要检查，原因 https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.tsx#L148  keyboardType = 'numeric'

**Comment by silentcloud** [comment]
当然，模拟器里例外，但是最终以真机为准，模拟器仅仅是模拟器
