### ISSUE TITLE
如何给Modal.alert() 渲染的Modal添加platform属性区分IOS Android

### ISSUE THREAD

**Issue by yup9** [ant-design/ant-design-mobile#1186]
1.0.+版本的Modal， 新增了platform属性以区分不同平台上不同的弹窗样式
问题： 好像没办法给Modal.alert方法渲染的Modal添加platform 属性

**Comment by paranoidjk** [comment]
按现有的 api 设计不太好加，这个可能要等到 2.0 重构改一下这个 API。

cc @silentcloud

**Comment by silentcloud** [comment]
恩 目前确实不好加，至于 API 要保证 rn 和 web 统一，API 估计也不可能重构成别的。

可以在现有 api 的参数里在额外加一项

**Comment by paranoidjk** [comment]
close in favor of https://github.com/ant-design/ant-design-mobile/issues/1371
