### ISSUE TITLE
<TabPane /> 组件会导致页面字体模糊？

### ISSUE THREAD

**Issue by DaskV** [ant-design/ant-design-mobile#1187]
Tabs.TabPane 的 **am-tabs-ink-bar**  的css 属性 **transform:translate3d(0px, 0px, 0px)** 会导致 整体页面字体显得模糊

希望能改成translate2d  或者translateX、translateY

## 目前解决办法是 在所有被影响的模块 外增加一个div，并设置其css transform:translate(0)

**Comment by paranoidjk** [comment]
在什么设备什么浏览器？给个可复现的demo？

**Comment by paranoidjk** [comment]
另外你有解决方案欢迎PR

**Comment by DaskV** [comment]
@paranoidjk  
目前测试了 chrome  v.58.0 ,firefox 53.0 以及微信X5浏览器 QQ浏览器 都有模糊的问题

[发生问题的项目](https://github.com/DaskV/CNode)
![1](https://cloud.githubusercontent.com/assets/17246291/25266350/6e996238-26a3-11e7-8b46-237c3ea59972.gif)

**Comment by paranoidjk** [comment]
@DaskV 👍  有兴趣来个 PR 帮我们修复吗？
https://github.com/ant-design/ant-design/issues/3702
https://github.com/react-component/tabs/issues/61

另外你的 CNode demo很不错，愿意的话可以 PR 收集到 antd-mobile 的官方 demo 集合中来： https://github.com/ant-design/antd-mobile-samples

**Comment by zhang740** [comment]
ref #1556
