### ISSUE TITLE
高清方案与百度地图适配

### ISSUE THREAD

**Issue by mart1ntsang** [ant-design/ant-design-mobile#1189]
### What problem does this feature solve?
使用高清方案后，由于viewport中的scale不再是1，导致百度地图的比例变小了。

### What does the proposed API look like?
希望可以手动设置viewport的scale

**Comment by paranoidjk** [comment]
高清方案的脚本你可以随意修改。

https://github.com/ant-design/ant-design-mobile/issues/799
