### ISSUE TITLE
disabled 状态支持

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#119]
@ant-design/ant-design-team 

所有输入型组件都需要有个 disabled 属性.

ref:

- https://github.com/ant-design/ant-design-mobile/issues/90#issuecomment-239996836

**Comment by pingan1927** [comment]
属性名叫`editable` 还是 `disabled`呢？
- `InputItem`: `editable`
- `TextareaItem`: `editable`
- `Switch`: `disabled`
- `Radio`:  `disabled`
- `Checkbox`: `disabled`
- `SearchBar`: `disabled`
- `ImagePicker`: 需要吗？
- `Picker`: @warmhug 

其他的组件相关同学在罗列并梳理下吧

**Comment by yiminghe** [comment]
disabled 吧，现有很多组件都是

**Comment by pingan1927** [comment]
- `InputItem`: `editable`
- `TextareaItem`: `editable`

这两个组件新增属性`disabled `，原先的`editable `对应的是input的readOnly属性。
