### ISSUE TITLE
Tabs每个tabpane里面放ListView在钉钉里面打开左右无法正常滑动，上滑也会出现问题

### ISSUE THREAD

**Issue by itxuye** [ant-design/ant-design-mobile#1193]
### Version
1.0.8

### Environment
ant-moible 1.8   钉钉里面的浏览器也可能他是在webview中打开

### Reproduction link
在钉钉里面无法左右滑动，试过在微信QQ上没问题，所以没法提供复现链接

### Steps to reproduce
发送链接给朋友，放在钉钉里面打开。
tabs左右无法滑动，卡在中间位置。

### What is expected?
正常左右滑动

### What is actually happening?
无法左右滑动

**Comment by paranoidjk** [comment]
@itxuye 为什么关掉？找到原因了吗?

**Comment by itxuye** [comment]
@paranoidjk 暂时关掉吧，我现在关闭了左右滑动，五一调试有问题，我再来询问。
