### ISSUE TITLE
高清解决方案在相同手机下会有不同的效果。

### ISSUE THREAD

**Issue by xfcdxg** [ant-design/ant-design-mobile#1194]
### What does the proposed API look like?
请问如何避免此类问题的发生

![img_1427](https://cloud.githubusercontent.com/assets/16435465/25267885/2ff02e8a-26a9-11e7-8f7d-a3832665f92d.JPG)

**Comment by paranoidjk** [comment]
假设一下，你自己看了这样的一张图能排查出一个问题的原因吗？

请阅读 issue 模板。

**Comment by paranoidjk** [comment]
cc @pingan1927
