### ISSUE TITLE
React Native Demo Problem

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1199]
iphone6sp 

- [x] loading icon not work
- Popover style is ugly `这个组件我重写一下`
- [x] result title 
- [x] InputItem underline
- [x] pagination content text, activeStyle
- ~~[] switch controlled mode~~ `RN switch 默认行为`

**Comment by silentcloud** [comment]
- loading icon not work  这个直接从 demo 去掉好了，RN 有自己的 loading（activityIndicator）

**Comment by silentcloud** [comment]
@paranoidjk 当时你说的 result tilte 是啥问题？

> pagination content text, activeStyle

这个

**Comment by paranoidjk** [comment]
@silentcloud result title 是指result 每个demo的小标题 https://github.com/ant-design/ant-design-mobile/blob/master/components/result/demo/basic.tsx#L8 乱写的英文比较丑，改成有逻辑的把，参考web demo

**Comment by paranoidjk** [comment]
@silentcloud pagination的按钮都没有文字，而且点了之后activeStyle没消失
