### ISSUE TITLE
SearchBar的clear icon有时候不出现

### ISSUE THREAD

**Issue by 3610cn** [ant-design/ant-design-mobile#1204]
### Version
1.1.0

### Environment
chrome 56 (mac) / iphone 10.3 safari / android 6.0 (vivo)

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/search-bar?lang=zh-CN#search-bar-demo-0](https://mobile.ant.design/kitchen-sink/components/search-bar?lang=zh-CN#search-bar-demo-0)

### Steps to reproduce
1. 在搜索框中输入文字，clear icon正常展现
2. 使用删除键删除全部文字再输入，clear icon没有正常出现

### What is expected?
无论什么时候，只要搜索框有文字，clear icon应该出现

### What is actually happening?
使用删除键删除全部文字再输入，clear icon没有正常出现

---
还要一个问题，就是有时候点击clear icon无效，文字没有按预期被清空，也是多个平台可重现，但是重现不稳定。

**Comment by paranoidjk** [comment]
- 第一个问题，`使用删除键删除全部文字再输入，clear icon没有正常出现` 我在 chrome 56 (mac)  和 iPhone6ps 上无法复现
- 第二个问题，`是有时候点击clear icon无效，文字没有按预期被清空`, PC上点击是无效的。

**Comment by 3610cn** [comment]
不好意思，刚才看了一下，ios safari 版本是10.2.1，我录了个简单的gif，android上也比较容易复现，但不是太稳定。 [gif demo](http://file.3610.cn/1.gif)

**Comment by liqi07** [comment]
> 使用删除键删除全部文字再输入，clear icon没有正常出现 

这个我重现到了，的确有问题，我来修复下  

> 点击clear icon无效，文字没有按预期被清空，也是多个平台可重现  

暂未重现，请提供相关平台信息（如果PC上浏览，点击就是无效的）
