### ISSUE TITLE
结合react-native-web 高清方案如何将StyleSheet 样式转换rem

### ISSUE THREAD

**Issue by 289420843** [ant-design/ant-design-mobile#1206]
项目之前是app和web各自编写一套代码，这样维护复杂。
发现react-native-web这个库后，打算将两套代码合并在一起，这样代码几乎能达到一致，web端需要实现高清方案，但是无法将StyleSheet的样式转rem，请问如何能实现

**Comment by warmhug** [comment]
rn 不支持 rem 吧？

**Comment by paranoidjk** [comment]
rn应该是不支持rem的，毕竟底层是native，部分css属性的百分比也是近几个版本才支持
