### ISSUE TITLE
受控模式下 input rerender 造成光标位置丢失

### ISSUE THREAD

**Issue by jackYouth** [ant-design/ant-design-mobile#1208]
antd示例网页上就可以看到：https://mobile.ant.design/components/input-item-cn/。
inputItem类型为phone和bankCard时，如果从前几位开始删除，光标会自动跳转到最后
<img width="472" alt="111" src="https://cloud.githubusercontent.com/assets/23489336/25381351/f510b6aa-29e5-11e7-8062-895b12dfeb39.png">
<img width="460" alt="222" src="https://cloud.githubusercontent.com/assets/23489336/25381352/f548e296-29e5-11e7-943f-42d55ea89559.png">

**Comment by paranoidjk** [comment]
根本原因是，受控模式下，在`input` 的 `onChange` 里面用正则做了对 value 做了处理，会造成 第二次
 rerender，从而光标的位置被重置了，暂时没什么好方法修复

https://github.com/facebook/react/search?q=cursor&type=Issues&utf8=%E2%9C%93

**Comment by paranoidjk** [comment]
@pingan1927 这里如果不从 react 的角度上找解决办法，还一种就是利用 selection 和 range api 保存与恢复光标位置，不过这个 api 差异和兼容性问题比较复杂

**Comment by RickyShiJs** [comment]
Reopen it in https://github.com/ant-design/ant-design-mobile/issues/1553

**Comment by warmhug** [comment]
Trace #810
