### ISSUE TITLE
There was a problem with the Picker before upgrading the version

### ISSUE THREAD

**Issue by margin-0** [ant-design/ant-design-mobile#1210]
### Version
1.1.0

### Environment
antd-mobile ： 1.1.0

### Reproduction link
[https://mobile.ant.design/components/picker-cn/](https://mobile.ant.design/components/picker-cn/)

### Steps to reproduce
The previous version was 0.9.14 in my project I used the Picker component, according to the corresponding data structure to get the desired effect, but after I upgrade found Picker that piece of the error, return the version to try not to the error, have the test under the 1.0.7 also have an error, upgrade to 1.1.0 version of any error

### What is expected?
Normal use

### What is actually happening?
Error

---
My data structure resembles the three-level linkage of the city choice
![d025d341-ee01-4ab2-90f5-3fe0dd7bad3c](https://cloud.githubusercontent.com/assets/23308724/25417333/ec725e8c-2a75-11e7-9faa-d7dd9da6ddca.png)
![306f61dd-8b1c-4b02-997d-5644dbba40a8](https://cloud.githubusercontent.com/assets/23308724/25417334/ee122ec0-2a75-11e7-8d94-0a1700d0c81e.png)

```javascript
const PickerWrap = ({ seasons, serviceDate, handleChangeServiceDate }) => {
    console.log(seasons)
    return (
    <Picker data={ seasons }
        title="选择日期"
        cascade={false}
        extra= { serviceDate ? (serviceDate.join(' ')) : '请选择上门服务时间' }
        cols={2}
        onChange={v => handleChangeServiceDate(v)}
      >
        <ListItem arrow="horizontal" >预约时间</ListItem>
    </Picker>
    )
}
```

**Comment by paranoidjk** [comment]
@ant-design-bot markdown

**Comment by margin-0** [comment]
###Hello my question is:  
 the use of Picker components in 0.9.14 can be normal reference, but I upgraded to 1.1. After the 0 version, the same usage of the incoming data structure will error, the following is my reference method in the project and the simulated data I give
```javascript
//Same method, incoming data same, version different problems
const PickerWrap = ({ seasons, serviceDate, handleChangeServiceDate }) => {
    console.log(seasons)
    return (
    <Picker data={ seasons }
        title="选择日期"
        cascade={false}
        extra= { serviceDate ? (serviceDate.join(' ')) : '请选择上门服务时间' }
        cols={2}
        onChange={v => handleChangeServiceDate(v)}
      >
        <ListItem arrow="horizontal" >预约时间</ListItem>
    </Picker>
    )
}
```
####Here is my data structure  
```javascript
 let seasons = [ 
      {
      label: '2013',
      value: '2013',
      children: [
          {
              label:'10:00',
              value: '10:00'
          },
          {
              label:'11:30',
              value: '11:30'
          }
      ]
    },...
 ]
```
------
In addition, because only a small fraction of the project is used to discover problems, test case can not be given, if my description is not able to understand my problem, I try to submit a project after the afternoon I test demo, so temporarily I use the 0.9.14, this version of the project can be normal operation, no error.  
Thanks

**Comment by margin-0** [comment]
#### 你好，写了个简单的案例   
- [项目案例](http://codepen.io/anon/pen/xdRJJZ)  
-----
案例里面运行也会报同样的错误，也就是我升级版本(1.1.0)后才出现的问题，之前同样的写法在0.9.14 未出现这样的报错，我试了几个版本在1.0.7中也会有报错

**Comment by paranoidjk** [comment]
@margin-0 `cascade={false}`去掉

**Comment by paranoidjk** [comment]
@warmhug 0.9.x 升级到 1.0.x， picker 的这个  cascade api 有变更吗？文档里都没列出来，空了完善一下。

**Comment by warmhug** [comment]
是的，1.0 里 rmc-cascader 和 rmc-picker 都升级了大版本，文档变化可能漏了、你看看补充下？

**Comment by paranoidjk** [comment]
以前的 antd-mobile 文档里也没有透出这个 api。

依赖非文档说明的底层 API 不再升级考虑范围内。
