### ISSUE TITLE
refactor progress

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1211]
- use https://github.com/react-component/progress

**Comment by warmhug** [comment]
为什么用这个？可能需求会不太一样，比如移动端有入场动画

**Comment by paranoidjk** [comment]
一是我们缺圆形的progress
而是看到rc有，就看能否复用

**Comment by paranoidjk** [comment]
close. 暂时没时间做了。

**Comment by emersonlaurentino** [comment]
Do you guys want to use the rc-progress type line or leave it as stand and just add the type dashboard?

**Comment by paranoidjk** [comment]
@emersonlaurentino Sorry, i don't kown what do you mean, welcome to file a new issue about your feature request or bug report.

**Comment by emersonlaurentino** [comment]
The ant design have 3 type of progress (line, circle and dashboard), but ant design mobile have only 1 type (line). This refactor are add more types (circle and dashboard) or change line actual by line of rc-progress?
