### ISSUE TITLE
Provide a variable to custom the cancel text color in Searchbar

### ISSUE THREAD

**Issue by wuzhishuo** [ant-design/ant-design-mobile#1213]
### What problem does this feature solve?
When we custom the fill color to `brand_primary` of the Searchbar by override `search_bar_fill `, the Cancel text will be invisible in this scene. We meet this issue because the color of Cancel text is also `brand_primary` which come from the variable `color_link`. 

### What does the proposed API look like?
Provide a variable to custom the Cancel text color, for example: `search_bar_cancel_color`

**Comment by paranoidjk** [comment]
do you fill duplicated issue ?  why not list the relevance https://github.com/ant-design/ant-design-mobile/issues/1158 at here ?

**Comment by paranoidjk** [comment]
your use case is strange, why set the `search_bar_fill === brand_primary`?

**Comment by wuzhishuo** [comment]
It is not strange. Let's make it clear. In theory, the `search_bar_fill` should can be any color, so why it could't be set to the same as `brand_primary`? And how can we implement the design if the Cancel text color not the same as `brand_primary`? For now, I want to do something like this(the red color is brand color):
![qq20170426-175828](https://cloud.githubusercontent.com/assets/1937216/25428952/fd422650-2aa9-11e7-9850-9be2dc80e0da.png)

**Comment by paranoidjk** [comment]
hm, fair enough,  I will fix this in next version.

**Comment by paranoidjk** [comment]
@wuzhishuo I opend a PR to split these two color. But as your example, you may set the brandColor to red.

**Comment by wuzhishuo** [comment]
@paranoidjk Ok, thank you. I know what to do next after you split these two color. The example is not my project, I just want to do something like this.

**Comment by paranoidjk** [comment]
@wuzhishuo I am not sure https://github.com/ant-design/ant-design-mobile/pull/1215 will be merged in next patch relase, since this may be a break change, you can track the progress at that PR.

**Comment by silentcloud** [comment]
I hope you can understand Chinese, if you can, this issue will help you.

https://github.com/ant-design/ant-design-mobile/issues/1174
