### ISSUE TITLE
refactor DatePicker, make momentjs optional

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1217]

**Comment by paranoidjk** [comment]
@benjycui 不赞同的原因是？ 这个考虑主要是momentjs体积太大

**Comment by benjycui** [comment]
第一个考虑是：去掉 moment 之后，实际减小的体积大小有多少？以下只是个人考虑，没有数据支持，所以你最好能给出一个数据：
1. 时间类组件，本身就需要一个库来做各种时间相关的计算
1. 如果去掉 moment，为了满足第一点，我们还是需要 引入/自己写 一个类似 moment 的库
1. 考虑到时间计算本身的复杂度，我们 引入/自己写 的时间计算库，即使比 moment 小，本身的大小也不会小
1. 所以，计算去掉 moment 之后，减小的体积，并不是 moment 的体积，而是 moment 的体积减去新引入的库的体积

关于体积，再进一步的思考是：
1. 这次重构后，我们给开发者推荐使用的时间操作库是什么？
1. 我觉得不可能是我们自己实现的那个库，毕竟要满足各种业务场景，就会变得非常复杂
1. 所以我们应该不可能自己实现一个时间操作库，而是使用社区相对完善的一个时间操作库，同时也推荐用户使用这个事件操作库
1. 乐观的情况是用户使用了我们推荐的时间操作库，并且这个库的体积比 moment 小，所以这次重构能减小项目最终的 bundle size
1. 另一种情况是，我们选择的时间操作库满足不了用户的业务场景，所以用户需要引入 moment 这种被社区验证过能支持多种业务使用场景的库，结果是项目的 bundle size 不降反增

最后是升级成本，我们时间类组件用了新的时间操作的库，意味着我们暴露给用户的 API 如 onChange 中的参数就不是 moment 类型了，所以业务代码中需要修改的地方不少，并都需要回归。

**Comment by benjycui** [comment]
以上为个人思考，所以对于这个重构， -1

当然，如果其他人能给出证据证明这次重构是有优势的话，也可以啊。

**Comment by benjycui** [comment]
我们也可以什么都不做，坐等 moment modularize https://github.com/moment/moment/issues/2373

这样按需引用，也能减小 bundle size

**Comment by paranoidjk** [comment]
1. moment.min.js + 至少一种 locale.js 至少 20Kb 是有的 https://momentjs.com/
2. 移动端的 DatePicker 相比 PC 来说简单很多，没有区间选择 ，没有联动，预估不会涉及到很复杂的时间运算 https://mobile.ant.design/components/date-picker
3. 更重要的一点是，我们压根没有提供用户选择的余地，但是在移动端上很多人一看你一个 DatePicker 还强制捆绑了 momentjs， 他是天然反感甚至放弃使用的....

**Comment by warmhug** [comment]
moment modularize 感觉没进度，我们等不及。现在 moment 是所有依赖中单个体积最大的一个。
mobile 依赖 https://github.com/react-component/m-date-picker 、对 moment 使用也并没很多、还是自己做个简版的好。不管最终怎么样，先尝试做做吧。

**Comment by paranoidjk** [comment]
@yiminghe 不赞同的原因是什么，这个定个结论下来。 

目前来看 antd-mobile 的  DatePicker 其实就是三列的 PickerView， 相比 PC 简单很多

**Comment by benjycui** [comment]
如果是把 momentjs 替换成其他库，如 data-fns 之类 -1

如果是直接使用原生 Date 对象，可以一试，但还是要看实现的效果：

> 考虑到时间计算本身的复杂度，我们 引入/自己写 的时间计算库，即使比 moment 小，本身的大小也不会小

**Comment by yiminghe** [comment]
基础库不能变的，时间涉及时区，国际化一系列功能

**Comment by silentcloud** [comment]
我想用户权衡之下，可能会用 input[type=date/time] 比较多了，毕竟现在 datepicker 很大

**Comment by paranoidjk** [comment]
https://github.com/react-component/time-picker/issues/46
