### ISSUE TITLE
Modal - When setting 'maskClosable' to false, cannot use back button to go back

### ISSUE THREAD

**Issue by TsuryKnox** [ant-design/ant-design-mobile#1218]
### Version
1.1.0

### Environment
Android 7.1, React Native 0.41.2

### Reproduction link
[http://codepen.io/anon/pen/eWBwLq](http://codepen.io/anon/pen/eWBwLq)

### Steps to reproduce
Open a Modal with maskClosable={false} and try to press 'back' button

### What is expected?
Pressing the back button should close the modal.

### What is actually happening?
The modal is not closed. Only setting maskClosable={true} will make it close when pressing back button

---
It is a common behavior to allow closing with back button while disallowing pressing mask to close.

**Comment by paranoidjk** [comment]
what do you mean about `back button ` ?

you can use `props.visible` to make a controlled Modal. see our demo: https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/demo/basic.tsx#L112

**Comment by TsuryKnox** [comment]
I mean that it is impossible to handle a keypress on the Android b
ack button because your Modal component seems to be blocking it when [maskClosable}={false}.

**Comment by paranoidjk** [comment]
@TsuryKnox 
no，it shoud't have effct on events. 
You can push your demo project to github, i'd like to take a look.

**Comment by TsuryKnox** [comment]
I can't upload my code, it is commercial... Just make a modal component, set maskClosable to false and try to hit the back button - you will see that the modal will not close.

Now set maskCloseable to true and see that the back button closes the modal.

**Comment by paranoidjk** [comment]
@TsuryKnox 
- i am not familiar with android development, but can you listen the back event and use `props. visible ` to close the modal manually ?
- if the back event will cause page reload, i think there should be no problem.

**Comment by TsuryKnox** [comment]
The back even doesn't fire when I set maskCloseable to false and make the modal visible.

**Comment by silentcloud** [comment]
because of this line:  https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/Modal.tsx#L39

`onRequestClose` is android only, I will replace `if (this.props.maskClosable && this.props.onClose) ` with `if (this.props.onClose)`

**Comment by TsuryKnox** [comment]
Thanks.
