### ISSUE TITLE
Card web type defined 

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1221]
### Version
1.1.0

### Environment
web

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/07649b41204d4101457a94db74a9339d54adad32/components/card/CardBody.tsx#L7](https://github.com/ant-design/ant-design-mobile/blob/07649b41204d4101457a94db74a9339d54adad32/components/card/CardBody.tsx#L7)

### Steps to reproduce
```jsx
export default () => (
  <Card><Card.Body>card</Card.Body></Card
)
```

### What is expected?
Card body props is optional

### What is actually happening?
Typescript try to load `CardBody.d.ts` not 'CardBody.web.d.ts`

```bash
file: 'file:///Users/colder/Documents/proj1/card.tsx'
severity: '错误'
message: 'Property 'styles' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<CardHeader> & Readonly<{ children?: ReactNode; }> ...'.'
at: '133,9'
source: 'ts'
```

---
I think we need put all type define in to one file `PropsType.tsx`. Similar another components.

**Comment by paranoidjk** [comment]
> Typescript try to load CardBody.d.ts not 'CardBody.web.d.ts`

are you sure about this ?

**Comment by cncolder** [comment]
![2017-04-27 13 12 16](https://cloud.githubusercontent.com/assets/127009/25468988/0788dc38-2b4c-11e7-8be5-59cf8162a0c6.png)

```bash
☃  proj1 git:(typescript)✗ cat node_modules/antd-mobile/lib/card/CardBody.web.d.ts
/// <reference types="react" />
import React from 'react';
export interface CardBodyProps {
    prefixCls?: string;
    children?: any;
    className?: string;
    style?: {};
}
export default class CardBody extends React.Component<CardBodyProps, any> {
    static defaultProps: {
        prefixCls: string;
    };
    render(): JSX.Element;
}
☃  proj1 git:(typescript)✗ cat node_modules/antd-mobile/lib/card/CardBody.d.ts
/// <reference types="react" />
import React from 'react';
export interface CardBodyProps {
    children?: any;
    style?: {};
    styles: any;
}
export default class CardBody extends React.Component<CardBodyProps, any> {
    static defaultProps: {
        style: {};
    };
    render(): JSX.Element;
}
```

**Comment by cncolder** [comment]
`lib/index.web.d.ts` export from `export { default as Card } from './card/index.web';`

But `lib/card/index.web.d.ts` import CardBody like this `import CardBody from './CardBody';`

So we need refactor card component. Move all Card*Props in to one file `PropsType.tsx`. Change `styles` to `styles?` make it optional.

**Comment by paranoidjk** [comment]
> But lib/card/index.web.d.ts import CardBody like this import CardBody from './CardBody';

with below webpack config: 
```js
resolve: {
  modulesDirectories: ['node_modules', path.join(__dirname, '../node_modules')],
  extensions: ['', '.web.js', '.js', '.json'],
},
```

I think this is typescript issue ? do you think typescript should look `.d.ts` file follow the webpack resolve config ? or maybe there is some loader deal with this.

**Comment by paranoidjk** [comment]
maybe something like this https://github.com/TypeStrong/ts-loader#loaderoptionsplugin

**Comment by cncolder** [comment]
I'm not have webpack config. What about IDE e.g. vscode?
