### ISSUE TITLE
Pagination#current is required but default value is 0

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1224]
### Version
1.1.0

### Environment
web and rn

### Reproduction link
[http://mobile.ant.design](http://mobile.ant.design)

### Steps to reproduce
```tsx
// Property 'current' is missing. (current default 0)
<Pagination total={5} />
```

### What is expected?
Optional bcs default value is first page

### What is actually happening?
Must set `current={0}`

**Comment by paranoidjk** [comment]
duplicate https://github.com/ant-design/ant-design-mobile/issues/1009

**Comment by cncolder** [comment]
我想说的是，有默认值的属性，应该都是可选的，而现在 current 是必选的。

应该是不设置默认第1页。

**Comment by paranoidjk** [comment]
@cncolder 默认可选和默认值是两个问题，发现typescript定义有问题直接提PR修改
