### ISSUE TITLE
DatePicker support Range DatePicker

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#1232]
### What problem does this feature solve?
support Range DatePicker

### What does the proposed API look like?
```
<DatePicker
  type="multi"
  title="组合DatePicker"
  extra="开始日期至结束日期"
  minStartDate={minDate}
  maxStartDate={maxDate}
  minEndDate={minDate}
  maxEndDate={maxDate}
  onChange={(res) => {
    console.log(res);
  }}
>
  <List.Item arrow="horizontal">range(CST)</List.Item>
</DatePicker>
```

**Comment by pingan1927** [comment]
比较强烈常用的业务需求，奇岳 会提一个PR。

**Comment by pingan1927** [comment]
![default](https://cloud.githubusercontent.com/assets/347649/25512939/fa77b1c8-2c03-11e7-982e-e844c039d594.png)

**Comment by warmhug** [comment]
可以考虑下像 PickerView 一样、支持 非弹出式的 DatePicker

**Comment by pingan1927** [comment]
这个业务交互同学专门提供的设计，非弹出式的DatePicker 找万焱同学CC来，多支持一些。
