### ISSUE TITLE
IOS下高清方案二维码识别区域偏移

### ISSUE THREAD

**Issue by wtchaos** [ant-design/ant-design-mobile#1240]
### Version
1.1.0

### Environment
微信（ios）中识别长按识别二维码

### Reproduction link
[http://wap.mianhuaxiong.com/#/tchaos](http://wap.mianhuaxiong.com/#/tchaos)

### Steps to reproduce
在微信（ios）中打开页面长按图片识别二维码没反应，但长按图片下方区域会弹出识别二维码

### What is expected?
在微信（ios）中打开页面长按图片可以识别二维码

### What is actually happening?
在微信（ios）中打开页面长按图片不可以识别二维码

**Comment by paranoidjk** [comment]
这跟高清方案有什么关系？check 下你自己的布局

**Comment by paranoidjk** [comment]
帮你看了下，你搞了两个二维码，上面一张定位占位了真正二维码的上半部分。

**Comment by wtchaos** [comment]
@paranoidjk 你好··是因为识别不了我才采取了放两个二维码上去的方法，造成长按下面的二维码能识别的效果，其实这个时候识别的是我隐藏的上面的二维码的图

**Comment by Elvin1993** [comment]
你用的是flex布局吧 
display:flex, css position  会影响到二维码识别 
是微信浏览器的问题
