### ISSUE TITLE
change all `props.autoFocus` to `instance.focus()`

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1243]
Uptdaed: https://facebook.github.io/react/docs/refs-and-the-dom.html#when-to-use-refs

ref: https://github.com/ant-design/ant-design/issues/3790

https://github.com/ant-design/ant-design-mobile/search?utf8=%E2%9C%93&q=autoFocus&type=

https://github.com/ant-design/ant-design-mobile/search?q=autoFocus&type=Issues&utf8=%E2%9C%93

https://github.com/ant-design/ant-design-mobile/issues/1514

no messy job, if users want a input be focused automatic， use `refs.foo.focus()` in componentDidMount

cc @benjycui @pingan1927

**Comment by pingan1927** [comment]
good idea，it's be very ok

**Comment by paranoidjk** [comment]
@pingan1927 有空的话可以到 2.0 的分支上开始改。 https://github.com/ant-design/ant-design-mobile/tree/feature-2.0

**Comment by pingan1927** [comment]
嗯 这两周又开始通宵了！

**Comment by paranoidjk** [comment]
One more reason to remove this autoFocus feature

## UIWebView keyboardDisplayRequiresUserAction

> When this property is set to true, the user must explicitly tap the elements in the web view to display the keyboard (or other relevant input view) for that element. When set to false, a focus event on an element causes the input view to be displayed and associated with that element automatically.
The default value for this property is true.

https://developer.apple.com/documentation/uikit/uiwebview/1617967-keyboarddisplayrequiresuseractio

## WKWebView

Even do not have this api

**Comment by benjycui** [comment]
cc @silentcloud

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design/issues/3790

**Comment by paranoidjk** [comment]
- [ ] SearchBar https://github.com/ant-design/ant-design-mobile/blob/master/components/search-bar/index.tsx#L78
