### ISSUE TITLE
Picker使用疑惑问题 Cannot assign to read only property '0' of string

### ISSUE THREAD

**Issue by itxuye** [ant-design/ant-design-mobile#1244]
### Version
1.1.1

### Environment
MacOS Chrome

### Reproduction link
[https://github.com/itxuye/React-StartKit](https://github.com/itxuye/React-StartKit)

### Steps to reproduce
设置normalize，想得到String格式

### What is expected?
{XXX1:String,XXX2:String}

### What is actually happening?
 滑动过程或者得到form表单再次滑动出现Cannot assign to read only property '0' of string XXX

**Comment by paranoidjk** [comment]
picker 的 value 是 Array 类型的，你 return 一个 String 是什么意图？

如果是想把picker选中的值转换成string，应该这样

```js
  pickerToString(v) {
    return v.map(item => String(item));
  }
```

另外，简单的问题抽象一个简单的可复现demo，贴codepen或者关键代码就好了，上来就repo，我还要拉代码，装依赖，读你的代码，效率太低。

使用类的问题不要在issue提。
