### ISSUE TITLE
RN IOS配置Icon不成功，求大家帮助

### ISSUE THREAD

**Issue by singingBoy** [ant-design/ant-design-mobile#1245]
> 系统：mac

````
    "antd-mobile": "^1.1.1",
    "dva": "1.3.0-beta2",
    "git": "^0.1.5",
    "react": "~15.4.1",
    "react-native": "0.42.0"

````

>  报错信息：

![1140fa47-1834-46af-942b-76ab928eee89](https://cloud.githubusercontent.com/assets/22296047/25554253/3197950e-2cfb-11e7-836f-7909c7ac64b8.png)

> 文件路径：anticon.ttf 放在fonts 下

![de77a315-83a9-4290-b1e3-32e502faa6dc](https://cloud.githubusercontent.com/assets/22296047/25554285/ebd56536-2cfb-11e7-8f10-b37bd2460ffe.png)

> 配置：

![cdf24750-93ae-449d-9e3b-fd811450e63c](https://cloud.githubusercontent.com/assets/22296047/25554292/0881ec86-2cfc-11e7-86d2-1ae52343e382.png)

**Comment by silentcloud** [comment]
@singingBoy  你这个 key 貌似有问题

![image](https://cloud.githubusercontent.com/assets/1698185/25601559/9991fd68-2f1f-11e7-9148-5105a76b8843.png)
