### ISSUE TITLE
RN IOS，加入anticon.ttf 配置Icon不成功

### ISSUE THREAD

**Issue by singingBoy** [ant-design/ant-design-mobile#1246]
### Version
1.1.1

### Environment
mac系统、"antd-mobile": "^1.1.1",     "dva": "1.3.0-beta2",     "git": "^0.1.5",     "react": "~15.4.1",     "react-native": "0.42.0"

### Reproduction link
[https://mobile.ant.design/components/icon-cn/](https://mobile.ant.design/components/icon-cn/)

### Steps to reproduce
>  报错信息：

![1140fa47-1834-46af-942b-76ab928eee89](https://cloud.githubusercontent.com/assets/22296047/25554253/3197950e-2cfb-11e7-836f-7909c7ac64b8.png)

> 文件路径：anticon.ttf 放在fonts 下

![de77a315-83a9-4290-b1e3-32e502faa6dc](https://cloud.githubusercontent.com/assets/22296047/25554285/ebd56536-2cfb-11e7-8f10-b37bd2460ffe.png)

> 配置：

![cdf24750-93ae-449d-9e3b-fd811450e63c](https://cloud.githubusercontent.com/assets/22296047/25554292/0881ec86-2cfc-11e7-86d2-1ae52343e382.png)

### What is expected?
IOS配置Icon详细说明或例子(引入自定义ttf文件)

### What is actually happening?
无法使用自己的ttf，来使用Icon

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1027

提问前，先搜索已有issue。

**Comment by singingBoy** [comment]
之前看过了啦，我多个ttf文件放到不同路径下，也没解决。那个帖子的楼主好像也没解决吧

**Comment by singingBoy** [comment]
请老师不吝指教

**Comment by paranoidjk** [comment]
https://github.com/oblador/react-native-vector-icons#ios

**Comment by paranoidjk** [comment]
求助类的问题建议上问答社区。

**Comment by silentcloud** [comment]
应该是 key 不对，看这里 https://github.com/ant-design/ant-design-mobile/issues/1245
