### ISSUE TITLE
高清方案。html.style.fontSize疑问

### ISSUE THREAD

**Issue by miaowwwww** [ant-design/ant-design-mobile#1247]
### What problem does this feature solve?
我之前用lib-flexible.js，会把fontSize设置成10份，然后，想知道你这样是基于什么原因要设置成  doc.documentElement.style.fontSize = `${_baseFontSize / 2 * dpr * _fontscale}px`;

### What does the proposed API look like?
求回答。

**Comment by paranoidjk** [comment]
duplicated.  https://github.com/ant-design/ant-design-mobile/issues/1229
