### ISSUE TITLE
建议给Popover的遮罩层添加一个点击事件

### ISSUE THREAD

**Issue by MrGoodBye** [ant-design/ant-design-mobile#1249]
### What problem does this feature solve?
在结合[redux](http://redux.js.org/)开发时使用**Popover组件**,将当前显隐状态`visible`托管给`reducers`.如果Popover中的遮罩层能够有个点击事件`dispatch`修改visible的值用来隐藏该**Popover组件**,那么可以省去自己重新写一个遮罩层来完善这种场景.

### What does the proposed API look like?
遮罩层的点击回调事件**onMaskClick**

**Comment by paranoidjk** [comment]
Please look at our demo first: https://mobile.ant.design/components/popover

you can use `visiable` and `onVisibleChange ` to make popover controlled

**Comment by MrGoodBye** [comment]
I'm using [redux](http://redux.js.org/).
The event `onVisibleChange` will be invoked after `visible` changed.
I mean what if I want to click the `mask` by dispatching to the `reducers` to set the `visible` to `false` to cancel to popover. 
By the way,your word `visiable` is wrong.

**Comment by paranoidjk** [comment]
> The event onVisibleChange will be invoked after visible changed.

You are wrong, do not make a conclusion before you tried. 

Actually，`props.visible` will make this component controlled,  the only way to change this controlled popover show/hide status is to change `props.visible`, so as your use case, just use your redux store value as the `props.visible`, and dispatch action to change store when `onVisibleChange`.

suggest you learn about https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by MrGoodBye** [comment]
My mistake at the event `onVisibleChange`.
You are right, I've make a conclusion before I try it.
Thank you for explaining to me!
