### ISSUE TITLE
input 光标 从上方飞入

### ISSUE THREAD

**Issue by tonokim** [ant-design/ant-design-mobile#1251]
### Version
1.1.1

### Environment
iphone7 plus 、iphone7 plus 模拟器，iphone6 plus 模拟器

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item?lang=en-US](https://mobile.ant.design/kitchen-sink/components/input-item?lang=en-US)

### Steps to reproduce
高清屏方案。打开safari，https://mobile.ant.design/kitchen-sink/components/input-item?lang=en-US，点击 input输入框，光标会从input的上方飞入去，并且从小变大。

### What is expected?
光标直接出现，而不是从上方飞入

### What is actually happening?
光标会从input的上方飞入去，并且从小变大。

![image](https://github.com/tonokim/react-starter/blob/master/src/images/2017-05-01-21_04_55.gif)

**Comment by paranoidjk** [comment]
iphone6s plus 未复现。能否提供一个 gif 或录屏？

**Comment by tonokim** [comment]
https://github.com/tonokim/react-starter/blob/master/src/images/2017-05-01%2021_04_55.gif

**Comment by paranoidjk** [comment]
@tonokim 我这还是未复现，你的截图是官网吗？感觉样式不对，请提供下你详细的设备环境，复现步骤

**Comment by paranoidjk** [comment]
cc @pingan1927

**Comment by tonokim** [comment]
@paranoidjk 是官网的，截图用的是 Xcode 8.3.2 的ios模拟器，iphone7 plus 模拟器，iphone6 plus 模拟器都有这种现象。真机我这边只有iphone7 plus，系统是最新的10.3.2。 切换input输入框就能复现。

**Comment by paranoidjk** [comment]
实测，safari 上使用高清方案（viewport 缩放）的页面有此问题，如果想规避，可以根据业务场景决定是否使用 antd-mobile@1.x 的高清方案。

另外，antd-mobile@2.0 即将发布，默认将不再强依赖高清方案，也可解决此问题。
