### ISSUE TITLE
ListView && Carousel && SwipeAction 滑动手势控制

### ISSUE THREAD

**Issue by zerozaki0752** [ant-design/ant-design-mobile#1254]
Uptdated by @paranoidjk

## Problems
- Carousel 无法控制滑动手势灵敏度 
- Carousel 左右滑动触发 ListView 上下滑动
- SwipeAction 左右滑动触发 ListView 上下滑动

---

### What problem does this feature solve?
ListView包含Carousel（在header或row中）组件时，Carousel横划手势被触发时，竖划的手势不会向ListView传递。（常见的场景需求）

### What does the proposed API look like?
希望能在组件中提供一个属性来控制手势事件是否透

**Comment by zerozaki0752** [comment]
http://codepen.io/zerozaki/pen/WjOjBb
Carousel接收横划手势的使用 ListView还可以接收此时的竖划手势

**Comment by paranoidjk** [comment]
cc @silentcloud  @warmhug 

这里手势的问题我们无法控制，最近业务也遇到需求想要 carousel 的滑动更灵敏一点，比如在图片的一侧轻滑触发切换， nuka-carousel 得替换掉了或者 fork 过来自己维护了

**Comment by paranoidjk** [comment]
@zerozaki0752 临时方案可以试试在 Carousel onTouchStart  的时候设置整个 ListView `touch-action: pan-x`

**Comment by xxq260310** [comment]
不能禁止吗？左右滑动的时候，禁止上下滑动。

**Comment by paranoidjk** [comment]
@silentcloud 你看下 swipeAction 集成在 Listview 里的滑动问题，尝试在 swipeAction touch 事件里阻止冒泡？

**Comment by silentcloud** [comment]
@paranoidjk  swipeAction 是限制了只能在水平方向滑动的 
https://github.com/react-component/swipeout/blob/master/src/Swipeout.tsx#L222

**Comment by paranoidjk** [comment]
@silentcloud 
那调试一下为什么 SwipeAction 放在 ListView 里面横滑会触发 ListView 上下滚动？我这边业务复现了，但暂时没时间去看这个问题

**Comment by silentcloud** [comment]
如果实在我这边要处理的话，可以在 onPan 的时候判断哈 y 的距离，比如 y 必须为 0 的时候才能触发，但是这样在滑动的时候就太不灵活了，native 也是容许斜着滑动的

**Comment by paranoidjk** [comment]
@silentcloud SwipeAction自己水平垂直不管，需求是不触发外层的滚动，看能否把 SwipeAction touchEvent 阻止冒泡, 要么 ListView 需要处理？

**Comment by silentcloud** [comment]
应该是需要 listview 处理的，swipeaction 底层是  harmerjs

**Comment by warmhug** [comment]
使用 RefreshControl 会自动使用 https://github.com/yiminghe/zscroller ,  zscroller 会有此问题，其他情况都是使用浏览器原生滚动，无此问题。 cc @yiminghe

**Comment by yiminghe** [comment]
zscroller 0.3.0

**Comment by yufeisky** [comment]
选项卡里面使用listView也会有这个问题是吗？切换的时候正常应该禁止下拉，下拉的时候应该禁止tab切换的  但现在是切换的同时可以下拉

**Comment by carrollcai** [comment]
请问这个问题怎么解决，除了自己fork

**Comment by flemington** [comment]
这个问题解决了么
