### ISSUE TITLE
使用官方listview代码，不能翻页，onEndReached函数不触发

### ISSUE THREAD

**Issue by yemingsha** [ant-design/ant-design-mobile#1255]
用的是这个链接https://mobile.ant.design/components/list-view上的第二个代码

use <body> container
使用 html 的 body 作为滚动容器

问题：不能翻页，onEndReached函数不触发。
手脚架是用的这个：https://github.com/warmhug/__/tree/master/_react/demo

这是我的代码
[归档.zip](https://github.com/ant-design/ant-design-mobile/files/970909/default.zip)

问题出在哪里呢，怎么都调不出来。
谢谢大家帮看看了！

**Comment by warmhug** [comment]
index.less 里的去掉下边代码
```css
html {
  overflow: hidden;
}
```
