### ISSUE TITLE
网站多版本切换

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#126]
现在只展示最新版，怎么能看到上几个版本? 
![image](https://cloud.githubusercontent.com/assets/2011119/17809624/7d70cb94-664a-11e6-97f2-9526fda7ffd1.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/master/site/theme/index.js#L17

**Comment by yiminghe** [comment]
先回退了，1.0 离完整版本还早
