### ISSUE TITLE
Any plans to complete docs in english to same standard/level as antd for web?

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design-mobile#1261]
I love antd for web! I can't sing the praises enough. I'd really like to start using antd mobile for RN projects but I'm a little worried that some minor (but helpful) portions are not 100% translated (mostly in the demos but other places too). 

The antd for web docs are amazing. I know it probably isn't the number one priority, but is this on the somewhat-near-term roadmap?

**Comment by paranoidjk** [comment]
Thanks for your concern，it's in progress.
https://github.com/ant-design/ant-design-mobile/issues/329

**Comment by acomito** [comment]
@paranoidjk thanks. Any thoughts on using expo's Snack for examples and issues?

**Comment by paranoidjk** [comment]
@acomito 

1. Please file a issue if you find any problems.
2. We do have expo demo: https://expo.io/@silentcloud/antd-mobile
