### ISSUE TITLE
公共样式缺失对body的处理

### ISSUE THREAD

**Issue by kasinooya** [ant-design/ant-design-mobile#1264]
### Version
1.1.1

### Environment
any

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/master/components/style/index.less#L17](https://github.com/ant-design/ant-design-mobile/blob/master/components/style/index.less#L17)

### Steps to reproduce
check margin of body.

查看body的margin

### What is expected?
body { margin: 0}

为了更好的获取ListView等组件的使用体验，需要对body margin做normalize，margin:0

### What is actually happening?
body { margin: 8 | x }

**Comment by warmhug** [comment]
这属于 reset 不属于 normalize 吧，组件库不该做这些

**Comment by paranoidjk** [comment]
这个建议用户代码里自己加。

**Comment by paranoidjk** [comment]
@kasinooya 抱歉，是 normalize.css 的问题，他们已经回滚了，antd-mobile 这周的版本更新
https://github.com/necolas/normalize.css/commit/b4a8fdaf8321093b1e3cad612fb76cf2b7d3275d
