### ISSUE TITLE
[Bug report] New line characters cause TextareaItem word count corrupt 换行符导致 TextareaItem 字符计数错误

### ISSUE THREAD

**Issue by u9lyfish** [ant-design/ant-design-mobile#1265]
### Version
1.1.1

### Environment
iOS 10.3.1, Android 6.0.1

### Reproduction link
[https://mobile.ant.design/components/textarea-item](https://mobile.ant.design/components/textarea-item)

### Steps to reproduce
1. Set `count` prop for TextareaItem component
2. Input long enough text into TextareaItem; make sure to include new line characters

This can be reproduced on official demo page. (https://mobile.ant.design/components/textarea-item)

1. 为 TextareaItem 组件设置 `count` 属性
2. 输入足够长的文本，要包含换行符

### What is expected?
Consistent `count` display. Either displayed as 100/100 OR displayed as 99/100 & accepts input.

### What is actually happening?
99/100 but don't accept any more input.

**Comment by paranoidjk** [comment]
没复现你说的问题，一个换行符占一个字符。

请提供可复现的demo。

**Comment by u9lyfish** [comment]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3243940/25733002/c36097de-3187-11e7-8bc7-b7be1cf8fb29.gif)

是我没描述清楚，输入到接近 `count` 限制时，会出现字数未满而不能继续输入的情况。效果参见上图。官网 demo 即可复现。

**Comment by pingan1927** [comment]
@paranoidjk 现场复现了， @u9lyfish 具体机型给下，极有可能就是maxLength的计算方式和字符串长度的计算方式不一致导致。
应该是提交到服务端的字符串实际长度和前端计算的字符串长度以及maxLength的值保持一致。

**Comment by u9lyfish** [comment]
iPhone 6s
iOS 10.3.1

**Comment by huliyou** [comment]
此bug，有fix进度吗

**Comment by huliyou** [comment]
输入符合规则的文字+数字+英文+表情，可以输入超过字符限制

**Comment by paranoidjk** [comment]
fixed in https://github.com/ant-design/ant-design-mobile/issues/1663

**Comment by silentcloud** [comment]
@paranoidjk 这个跟那个问题不一样，现在基于 #1663 的修复，还是有问题的，输入 92 个汉字, 4 个换行，显示 96/100，没办法继续输入了

**Comment by paranoidjk** [comment]
> 输入 92 个汉字, 4 个换行，显示 96/100，没办法继续输入了

预期应该是显示 100/100，且 无法输入

@silentcloud  那这里的 bug 就是显示的 length 计算不正确，你加下对换行符的处理？

**Comment by silentcloud** [comment]
@paranoidjk 你先把你的那个改动在 master 上提交一下

**Comment by paranoidjk** [comment]
@silentcloud 昨天已经处理了，1.6.1， 1.6.2 都在 master 同步了

**Comment by silentcloud** [comment]
嗯，我没更新 master 代码，😓

**Comment by huliyou** [comment]
@silentcloud npm 发布了么？

**Comment by silentcloud** [comment]
@huliyou 急么？急的话我就发个版本，不急的话周五/六会发

**Comment by Roxyhuang** [comment]
该问题依然可以复现，

ios设备真机访问：https://mobile.ant.design/components/textarea-item

![image](https://user-images.githubusercontent.com/12892693/45076469-04f2f780-b11d-11e8-8259-25d9ebf240c0.png)

该问题可以参考：https://stackoverflow.com/questions/27279237/ios-8-0-max-length-issue

已提交pr（ #2823），增加了环境变量的判断，具体可以参考：

https://stackoverflow.com/questions/9038625/detect-if-device-is-ios
