### ISSUE TITLE
add preact snapshot test

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1267]
https://github.com/developit/preact/issues/560
https://github.com/developit/preact-render-to-string/issues/16
https://github.com/airbnb/enzyme/pull/742

**Comment by paranoidjk** [comment]
https://github.com/developit/preact/issues/560

**Comment by paranoidjk** [comment]
https://github.com/developit/preact-render-to-string/issues/16

**Comment by benjycui** [comment]
@yesmeck 其实单测可不可以这样写：

```jsx
import React from '../shared/ReactOrPreact';

...
```

```jsx
// ReactOrPreact

export default (function () {
  if (ENV === 'xxx') {
    return Preact
  }
  return React
})();
```

这样无论 Snapshot 还是单测都可以同时测试 Preact 和 React

**Comment by yesmeck** [comment]
应该可以把 React mock 掉，http://facebook.github.io/jest/docs/en/manual-mocks.html#content

**Comment by yesmeck** [comment]
但是需要 React 和 Preact 生成的 snapshot 一致。

**Comment by paranoidjk** [comment]
i will try this first https://github.com/ruyadorno/preact-jest-snapshot-test-boilerplate

**Comment by paranoidjk** [comment]
snapshot 跑通了，https://github.com/ant-design/ant-design-mobile/pull/1306

还剩一个问题是 https://github.com/developit/preact-render-to-string 没有把 html 元素的属性换行排列，所以与 react snaoshot 不一致，这个抽空过去 PR fix 掉。

**Comment by paranoidjk** [comment]
preact, inferno, react-lite 几个库跑 react 官方用例：

https://github.com/Lucifier129/react-core-unit-testing/pull/1/files

**Comment by paranoidjk** [comment]
https://github.com/developit/preact-render-to-string/issues/16#issuecomment-304465081
