### ISSUE TITLE
Warning: Unknown prop `platform` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

### ISSUE THREAD

**Issue by xiaobie123** [ant-design/ant-design-mobile#1278]
### Version
1.1.2

### Environment
浏览器

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog](https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog)

### Steps to reproduce
https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog     update  "antd-mobile": "^1.1.2",

### What is expected?
no Warning

### What is actually happening?

warning.js:36 Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

warning.js:36 Warning: Unknown prop `platform` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by ListItem)
    in Touchable (created by ListItem)
    in ListItem (created by MobileDemo)
    in div (created by PopupPicker)
    in PopupPicker (created by PopupDatePicker)
    in PopupDatePicker (created by DatePicker)
    in DatePicker (created by MobileDemo)
    in div (created by List)
    in div (created by List)
    in List (created by MobileDemo)
    in div (created by MobileDemo)
    in MobileDemo (created by Form(MobileDemo))
    in Form(MobileDemo) (created by Connect(Form(MobileDemo)))
    in Connect(Form(MobileDemo)) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Unknown)
    in Provider (created by Unknown)
    in Unknown

---
版本：1.1.2

https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog
今天刚把这个demo的ant-design-mobile版本更新到1.1.2，打开项目，在console里就又多了一个Warning: Unknown prop `platform` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by ListItem)
    in Touchable (created by ListItem)
    in ListItem (created by MobileDemo)
    in div (created by PopupPicker)
    in PopupPicker (created by PopupDatePicker)
    in PopupDatePicker (created by DatePicker)
    in DatePicker (created by MobileDemo)
    in div (created by List)
    in div (created by List)
    in List (created by MobileDemo)
    in div (created by MobileDemo)
    in MobileDemo (created by Form(MobileDemo))
    in Form(MobileDemo) (created by Connect(Form(MobileDemo)))
    in Connect(Form(MobileDemo)) (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Unknown)
    in Provider (created by Unknown)
    in Unknown

ps：还有这些警告
(unknown) Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
什么时候可以修复，

**Comment by chengky** [comment]
同样遇到，React 15.5.4，antd-mobile 1.1.2，用到List即会有此警告。使用antd-mobile 1.1.1没有问题。

**Comment by paranoidjk** [comment]
- List  `platform` 的 warning 本周五修复
- React 15.5 的 warning 还在修复中，具体进度追踪 https://github.com/ant-design/ant-design-mobile/issues/1118

**Comment by bccsafe** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/components/list/ListItem.web.tsx#L116

restProps里有`platform`，传进div里了
