### ISSUE TITLE
[SSR] Menu 默认高度依赖 clientHeight

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1279]
### What problem does this feature solve?

必须指定 height 才能通过服务端渲染，如果未指定 height 则取值于 clientHeight。

但是 height 是 number 类型，在服务端很难确定这个值。

### What does the proposed API look like?

默认高度使用类似 100% 这样的方法。

如果行不通，把 height 的类型改成 number | string。如此一来用户可以指定带单位的高度，如：'50vh' '50%' 'inherit' 等。

**Comment by paranoidjk** [comment]
- 可以把 height 的类型改成 number | string 
- 这里应该也可以重构精简掉，应该不需要这么多写死的高度在里面，指定menu容器的高度就好了，内部自动撑满适应 https://github.com/ant-design/ant-design-mobile/blob/master/components/menu/index.web.tsx#L72

**Comment by pingan1927** [comment]
指定一个高度即可，默认是整个屏幕高度的50%，给出其他合理的约定就可以把clientHeight移除掉

**Comment by cncolder** [comment]
这个讨论默认高度有结果吗？还是推迟到2.0？

**Comment by paranoidjk** [comment]
trace at https://github.com/ant-design/ant-design-mobile/issues/1521
