### ISSUE TITLE
【BREAK CHANGE】Upgrade svg-sptite-loader

### ISSUE THREAD

**Issue by Meeeeow** [ant-design/ant-design-mobile#1283]
# Notice

 antd-mobile `Icon` 所依赖的开源 webpack loader `svg-sprite-loader` 最近从 `0.3` 直接升级到了 `2.0`, 其配置方案发生了 break change.

但由于此 loader 的版本由用户代码控制，而功能被 antd-mobile 和用户代码所共同依赖， antd-mobile 团队只能选择在 `2.0` 对其进行升级，请各位用户在 `antd-mobile@1.x` 期间暂时不要升级 `svg-sprite-loader`，在项目里仍然使用 `svg-sprite-loader@0.3.x` 即可。[#1283](https://github.com/ant-design/ant-design-mobile/issues/1283)

- - -

### Version
1.1.2

### Environment
svg-sprite-loader@2, unrelated to other environments

### Steps to reproduce
1. Use svg-sprite-loader 2.0.0 to
2. Call `Toast.fail('Whoops')`
3. Reproduced

### What is expected?
Show toast

### What is actually happening?
Browser throw an exception

---
Variable `type` in index.web.js with svg-sprite-loader 0.x is string，like "#fail"
It's an object after upgrade to svg-sprite-loader 2.0+, include a  `default`  property，with sub property "id", "id" is the real `type`

**Comment by paranoidjk** [comment]
right now we haven't upgrade svg-sprite-loader, just use the package.json version
https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L118

**Comment by Meeeeow** [comment]
So you should tell user to install `svg-sprite-loader@0.3.1` in docs

**Comment by paranoidjk** [comment]
nope, you do not need to install svg-sprite-loader  by yourself, antd-mobile dependencies included it.

**Comment by paranoidjk** [comment]
@Meeeeow sorry, my mistake, it's devDeps, will not be install when you npm install antd-mobile

**Comment by Meeeeow** [comment]
Nope, I think `devDependencies` will not install when package install as a dependency. 
I'm using antd-mobile with `style: true` in `babel-plugin-import` options, so less file will passed to mine webpack installation

**Comment by paranoidjk** [comment]
@Meeeeow whould you like to PR to help use upgrade svg-sprite-loader?

**Comment by Meeeeow** [comment]
Yep, maybe tonight

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/commit/38e4ae2981807af30841bfe2b44bde413728f9ab?diff=unified
已经更新了文档，暂时先别升级，这个升级方案要仔细评估能否向下兼容，业务有太多依赖

```diff
-npm install svg-sprite-loader -D
+npm install svg-sprite-loader@0.3.1 -D
```

**Comment by Princess310** [comment]
今天尝试搭了一下mobile web
antd-mobile: 1.1.3
svg-sprite-loader 0.3.1
按官方文档写，貌似也没有显示Icon。

**Comment by paranoidjk** [comment]
https://github.com/kisenka/svg-sprite-loader/blob/master/2.0.md

**Comment by paranoidjk** [comment]
close in favor of https://github.com/ant-design/ant-design-mobile/pull/1740
