### ISSUE TITLE
TabBar 使用 rc-tabs  实现

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#129]
必要修改 pr 到 rc-tabs

**Comment by silentcloud** [comment]
我只是觉的 rc-tabs 对移动端太重了，有很多功能是移动端用不到的，而且 dom 嵌套很深，上次也发现在 webView 下面比较卡，不过一直没太多时间排查 @yiminghe

**Comment by silentcloud** [comment]
还有 tabbar 用了 rc-tabs 没办法跟 rn api 同步了 @yiminghe

**Comment by yiminghe** [comment]
主干已修改，有问题 pr rc-tabs

**Comment by silentcloud** [comment]
fixed

**Comment by warmhug** [comment]
> TabBar 使用 rc-tabs 实现

实践下来看，是个错误
