### ISSUE TITLE
switch support onClick

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#1290]
### What problem does this feature solve?
need onClick

### What does the proposed API look like?
onClick

**Comment by pingan1927** [comment]
when switch's prop disabled be true，onClick also can be triggered.

**Comment by pingan1927** [comment]
may be need support readonly.

**Comment by bccsafe** [comment]
除了实现上做限制外，propsType上可以考虑加上`readonly`
```
interface SwitchProps {
  readonly disabled?: boolean;
}
```

**Comment by paranoidjk** [comment]
@pingan1927 这个需求背景是什么？Switch 为什么需要 onClick, 有 onChange 不就足够了么？

**Comment by silentcloud** [comment]
同样不明白，为什么需要 onClick，另外 readonly 不就是受控模式么？

**Comment by pingan1927** [comment]
当switch disabled时，用户点击switch时需要提示用户去做其它操作。disabled时无法触发onChange事件。

**Comment by pingan1927** [comment]
readeOnly慢慢再考虑，react组件不需要完全跟web标准一样。

**Comment by paranoidjk** [comment]
@pingan1927 这个需求，业务在Switch外面再包一个div也能实现吧

**Comment by paranoidjk** [comment]
looks like https://github.com/pastaclub/react-bootstrap-tooltip-button
