### ISSUE TITLE
mobile.ant.design modal doc different from repo markdown

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1292]
### Version
1.1.2

### Environment
browser

### Reproduction link
[https://mobile.ant.design/components/modal-cn/](https://mobile.ant.design/components/modal-cn/)

### Steps to reproduce
[https://mobile.ant.design/components/modal-cn/](https://mobile.ant.design/components/modal-cn/) show `onpress`

[https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/index.zh-CN.md](https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/index.zh-CN.md) show `onPress`

### What is expected?
Sync doc

### What is actually happening?
```diff
- onPress
+ onpress
```

**Comment by paranoidjk** [comment]
weird ...
cc @benjycui

**Comment by benjycui** [comment]
@paranoidjk 本地 `rm -rf node_modules && npm i` 再重启看看对应的页面是否有问题。

**Comment by benjycui** [comment]
bisheng 和相关插件都没有用到 `toLowerCase`，不排除是底层依赖更新了的问题。

毕竟如果这个问题长期存在，写 API 的时候应该会有人注意到的。

**Comment by paranoidjk** [comment]
@benjycui 重装了还是有问题，bisheng 用哪个库来解析 markdown 的？

**Comment by benjycui** [comment]
https://github.com/benjycui/mark-twain/blob/master/package.json#L28

**Comment by paranoidjk** [comment]
```md
[ABC]
```
如上的 markdown 会被 remark  parse 为

```js
{
  "type": "root",
  "children": [
    {
      "type": "paragraph",
      "children": [
        {
          "type": "linkReference",
          "identifier": "abc",
          "referenceType": "shortcut",
          "children": [
            {
              "type": "text",
              "value": "ABC",
              "position": {
                "start": {
                  "line": 1,
                  "column": 2,
                  "offset": 1
                },
                "end": {
                  "line": 1,
                  "column": 5,
                  "offset": 4
                },
                "indent": []
              }
            }
          ],
          "position": {
            "start": {
              "line": 1,
              "column": 1,
              "offset": 0
            },
            "end": {
              "line": 1,
              "column": 6,
              "offset": 5
            },
            "indent": []
          }
        }
      ],
      "position": {
        "start": {
          "line": 1,
          "column": 1,
          "offset": 0
        },
        "end": {
          "line": 1,
          "column": 6,
          "offset": 5
        },
        "indent": []
      }
    }
  ],
  "position": {
    "start": {
      "line": 1,
      "column": 1,
      "offset": 0
    },
    "end": {
      "line": 1,
      "column": 6,
      "offset": 5
    }
  }
}
{
  "content": [
    "article",
    [
      "p",
      "[abc]"
    ]
  ],
  "meta": {}
}
```
而 mark-twain 的这里会取小写的 identifier
```js
  case 'linkReference':
      return `[${node.identifier}]`;
```
https://github.com/paranoidjk/mark-twain/blob/master/src/transformer.js#L73

**Comment by paranoidjk** [comment]
remark 提了一个 issue https://github.com/wooorm/remark/issues/258

在 https://github.com/benjycui/mark-twain/pull/20 先修复 @benjycui
