### ISSUE TITLE
安装的时候报错 

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design-mobile#13]
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:100:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:850:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:90:13)
npm WARN addRemoteGit     at Socket.emit (events.js:182:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:475:12)
npm WARN addRemoteGit  git+https://github.com/dancormier/react-native-swipeout.git#master resetting remote C:\Users\1\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-dancormier-react-native-swipeout-git-master-decd8cbf because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }

**Comment by warmhug** [comment]
什么命令按钮，描述下安装过程

**Comment by qq645381995** [comment]
npm 安装的时候  也许是源的问题

**Comment by yiminghe** [comment]
只能使用 npm 包，内网不能接触 github https://github.com/react-component/swipeout/blob/master/package.json#L45  @silentcloud

**Comment by silentcloud** [comment]
fixed
