### ISSUE TITLE
Add stylelint

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#1300]
https://github.com/stylelint/stylelint

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/commit/382dd8647528a9ecada5d494c8baa5928fc439b4

**Comment by benjycui** [comment]
This is easy enough, if someone want to try, just PR to us.

**Comment by benjycui** [comment]
This is easy enough, if someone want to try, just PR to us.
