### ISSUE TITLE
theme 里的 @radius-circle 看似没有被用到

### ISSUE THREAD

**Issue by hbrls** [ant-design/ant-design-mobile#1301]
Version

1.1.2

Environment

any

Reproduction link

https://github.com/ant-design/ant-design-mobile/blob/master/components/style/themes/default.less#L67

Steps to reproduce

any

What is expected?

我想改圆角样式，搜了一下发现这个变量并没有被用到，请帮忙确认一下

What is actually happening?

any

**Comment by silentcloud** [comment]
恩，样式里很多直接写了 50%，@hbrls 来个 pr？
