### ISSUE TITLE
Picker 滚动数据字体样式问题

### ISSUE THREAD

**Issue by darin-lao** [ant-design/ant-design-mobile#1303]
### What problem does this feature solve?
滚动列表字体现在修改不到样式和大小

### What does the proposed API look like?
滚动列表字体可以修改大小样式

**Comment by paranoidjk** [comment]
通过 `props.pickerPrefixCls` 设置 class， 然后写自定义样式

**Comment by darin-lao** [comment]
@paranoidjk ReactNative版也是这样设置？
