### ISSUE TITLE
[SSR] Modal render 方法依赖 navigator

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1305]
### What problem does this feature solve?

必须指定 platform 并且不能是 cross 才能通过服务端渲染，如果未指定 platform 则取值于 navigator.userAgent。

动态服务器端有能力指定 platform，但是像 bisheng 这样静态渲染就无能为力了。

### What does the proposed API look like?

Modal 的使用方法分两种：

1. 静态方法调用 alert/prompt/operation。
2. 当成组件使用。

对于方法1，可以不做改动，因为方法1涉及到 DOM 操作，服务端肯定无法直接调用。

对于方法2，考虑到 Modal 组件的特殊性，我认为可以排除掉用户首屏就直接显示 Modal 这种可能性，只有后续 visible 为 true 时才会显示，也就是说 Modal 只会在客户端显示。

由此我想到了一个讨巧的办法：

[components/modal/Modal.web.tsx#L88](https://github.com/ant-design/ant-design-mobile/blob/37fb7ded9826d552dc3df190d32b38b4412930be/components/modal/Modal.web.tsx#L88)

```jsx
const isAndroid = platform === 'android' ||
  (platform === 'cross' && this.props.visible && !!navigator.userAgent.match(/Android/i));
```

请 @paranoidjk @warmhug 评估。

**Comment by paranoidjk** [comment]
看起来没什么问题，相当于一直到真正渲染的时候才去计算 className。

提个 PR 看看吧

**Comment by paranoidjk** [comment]
关联 #1059

**Comment by cncolder** [comment]
其实我没太看懂 rc-dialog 内部实现，默认入口 DialogWrap 用到了 rc-util/lib/getContainerRenderMixin

Modal 是在 body 下另外创建 div 节点吗？而且是在 visible = true 时才开始创建的？

**Comment by cncolder** [comment]
如果 visible = false 时 rc-dialog render null，那我们的 Modal 是不是也可以这样：

```jsx
render() {
  if (!this.props.visible) return null

}
```
