### ISSUE TITLE
[SSR] Switch 依赖 navigator

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1308]
### What problem does this feature solve?

必须指定 platform 并且不能是 cross 才能通过服务端渲染，如果未指定 platform 则取值于 navigator.userAgent。

动态服务器端有能力指定 platform，但是像 bisheng 这样静态渲染就无能为力了。

### What does the proposed API look like?

之前在讨论一些组件如何改造时提到 componentDidMount 之后 setState 触发二次渲染，但是这种方法并不完美，如果两次 render 间隔较长，用户会看到这个变化过程。好在之前其他组件的改动都是曲线救国，没有用到这种方法。

Switch 是最后一个需要改造才能完美支持 SSR 的组件，它在两个平台显示两种样式是一个客观存在的事实。

征求一下意见，除了二次渲染，是不是没有其他办法了？

**Comment by paranoidjk** [comment]
真要说的话，服务端也是能拿到客户端 UA 的，可以做到注入platform...

**Comment by cncolder** [comment]
是的，但是我对 bisheng 不太了解，bisheng 是渲染以后当成静态页面显示吗？

**Comment by benjycui** [comment]
> 动态服务器端有能力指定 platform，但是像 bisheng 这样静态渲染就无能为力了。

是的，作为一个静态网站构建工具，bisheng 做不到。

> 之前在讨论一些组件如何改造时提到 componentDidMount 之后 setState 触发二次渲染，但是这种方法并不完美，如果两次 render 间隔较长，用户会看到这个变化过程。好在之前其他组件的改动都是曲线救国，没有用到这种方法。

Switch 组件 SSR 支持本身不需要考虑这个问题，就假设用户可以用动态服务器指定 platform 来做就好。

对于不希望用动态服务器的用户和我们的官网 demo 中，用以下方式适配即可。

```jsx
class CustomizedSwitch extends React.Component {
  componentDidMount() {
    this.setState({ platform: this.getPlatform() });
  }
  render() {
    return <Switch paltform={this.state.platform} />;
  }
}
```

**Comment by paranoidjk** [comment]
这些 platform 引起与 UA 牵扯的问题，细想起来当初 @yesmeck  提的 `PlatformProvider` 好像是一种更优雅的方案....

**Comment by cncolder** [comment]
我们没有引入额外的高阶组件就解决了除 Switch 以外的所有问题，这已经很成功了。

或许 Switch 保持现状也没什么问题，最多就是加一个判断条件 `typeof navigator !== 'undefined' && navigator.userAgent.match()`，这样可以把异常降低为 checksum 警告，只要用户指定了 platform 警告就消失了，或者我们在此之前就显示一个自己的警告，提示用户 Switch 在 SSR 模式下 platform 属性是必须的。

**Comment by warmhug** [comment]
Modal 里也有 navigator ，不影响吗

**Comment by cncolder** [comment]
@warmhug #1307 解决 Modal 问题（99%解决）。

**Comment by paranoidjk** [comment]
@cncolder 既然 Switch 不需要改造，这个 issue 可以 close 了。

**Comment by cncolder** [comment]
@paranoidjk 并不是说不需要改造，是讨论是否要加上 `typeof navigator !== 'undefined'`，不然接下来 node 环境的测试没办法进行。

**Comment by paranoidjk** [comment]
加一个判断好了 https://github.com/ant-design/ant-design-mobile/blob/master/components/switch/index.web.tsx#L37

```js
    const isAndroid = platform === 'android' || (platform === 'cross' && typeof navigator !== 'undefined' && !!navigator.userAgent.match(/Android/i));

```
