### ISSUE TITLE
svg-sprite-loader接口变更导致ant-design-mobile Icon出错

### ISSUE THREAD

**Issue by aircloud** [ant-design/ant-design-mobile#1309]
### Version
1.1.2

### Environment
svg-sprite-loader2.0 

### Reproduction link
[https://github.com/aircloud/antd-mobile-bug-example](https://github.com/aircloud/antd-mobile-bug-example)

### Steps to reproduce
我们采用2.0版本之后的svg-sprite-loader,然后使用<Icon>并且使用本地资源(比如<Icon type={require('./asset/homepage1.svg')} />)就会出错(webpack等均正确配置)

### What is expected?
应该不出错

### What is actually happening?
报错在这一行

`outerIcon?type.substr(1):type),true),(0,_defineProperty3["default"])(_classNames,.....`

(type这个时候是Object(之前版本的svg-sprite-loader返回string), substr 自然不存在的)

---
svg-sprite-loader更新之前(贵团队提供的demo用的0.2.0或者0.3.0)是没有问题的，因为只有一个name返回，可以参考
https://github.com/kisenka/svg-sprite-loader/tree/v0.3.0#configuration 但是现在更新这个插件之后返回的内容有所变化，我们可以看：https://github.com/kisenka/svg-sprite-loader#configuration 。(这个时候type实际上是一个对象)

但是Icon组建默认type是string，并且调用了string的方法，这个时候会出现错误。

因为目前npm下载svg-sprite-loader默认是最新的，所以这个错误会默认出现。

**Comment by paranoidjk** [comment]
duplicate https://github.com/ant-design/ant-design-mobile/issues/1283
