### ISSUE TITLE
webpack跑不通啊

### ISSUE THREAD

**Issue by bigbigbo** [ant-design/ant-design-mobile#131]
ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ActivityIndicator' in E:\workSpaces\probuck_by_react\node_modules\.0.30
0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 30:35-63

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ActivityIndicatorIOS' in E:\workSpaces\probuck_by_react\node_modules\.0
30.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 31:38-69

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ReactNativeART' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@
eact-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 32:21-46

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'DatePickerIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@r
act-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 33:31-55

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'DrawerLayoutAndroid' in E:\workSpaces\probuck_by_react\node_modules\.0.
0.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 34:37-67

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Image' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-nat
ve\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 35:23-39

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ImageEditor' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@rea
t-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 36:29-51

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ImageStore' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@reac
-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 37:28-49

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'KeyboardAvoidingView' in E:\workSpaces\probuck_by_react\node_modules\.0
30.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 38:38-69

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ListView' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-
ative\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 39:26-45

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'MapView' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-n
tive\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 40:25-43

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Modal' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-nat
ve\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 41:23-39

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Navigator' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 42:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'NavigatorIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@re
ct-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 43:30-53

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Picker' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-na
ive\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 44:24-41

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'PickerIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 45:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ProgressBarAndroid' in E:\workSpaces\probuck_by_react\node_modules\.0.3
.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 46:36-65

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ProgressViewIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0
react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 47:33-59

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ScrollView' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@reac
-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 48:28-49

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'SegmentedControlIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.
0.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 49:37-67

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Slider' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-na
ive\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 50:24-41

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'SliderIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 51:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'SnapshotViewIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0
react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 52:33-59

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Switch' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-na
ive\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 53:24-41

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'RecyclerViewBackedScrollView' in E:\workSpaces\probuck_by_react\node_mo
ules\.0.30.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 54:46-85

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'RefreshControl' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@
eact-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 55:32-57

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'StatusBar' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 56:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'SwitchAndroid' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@r
act-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 57:31-55

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'SwitchIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 58:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TabBarIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 59:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Text' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-nati
e\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 60:22-37

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TextInput' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 61:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ToastAndroid' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@re
ct-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 62:30-53

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ToolbarAndroid' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@
eact-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 63:32-57

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Touchable' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 64:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TouchableHighlight' in E:\workSpaces\probuck_by_react\node_modules\.0.3
.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 65:36-65

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TouchableNativeFeedback' in E:\workSpaces\probuck_by_react\node_modules
.0.30.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 66:41-75

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TouchableOpacity' in E:\workSpaces\probuck_by_react\node_modules\.0.30.
@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 67:34-61

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TouchableWithoutFeedback' in E:\workSpaces\probuck_by_react\node_module
\.0.30.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 68:42-77

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'View' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-nati
e\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 69:22-37

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ViewPagerAndroid' in E:\workSpaces\probuck_by_react\node_modules\.0.30.
@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 70:34-61

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'WebView' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-n
tive\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 71:25-43

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ActionSheetIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@
eact-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 74:32-57

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AdSupportIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@re
ct-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 75:30-53

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Alert' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-nat
ve\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 76:23-39

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AlertIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-
ative\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 77:26-45

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Animated' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-
ative\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 78:26-45

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AppRegistry' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@rea
t-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 79:29-51

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AppState' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-
ative\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 80:26-45

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AppStateIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@rea
t-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 81:29-51

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'AsyncStorage' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@re
ct-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 82:30-53

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'BackAndroid' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@rea
t-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 83:29-51

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'CameraRoll' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@reac
-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 84:28-49

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Clipboard' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 85:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'DatePickerAndroid' in E:\workSpaces\probuck_by_react\node_modules\.0.30
0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 86:35-63

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Dimensions' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@reac
-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 87:28-49

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Easing' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-na
ive\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 88:24-41

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ImagePickerIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@
eact-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 89:32-57

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'IntentAndroid' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@r
act-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 90:31-55

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'InteractionManager' in E:\workSpaces\probuck_by_react\node_modules\.0.3
.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 91:36-65

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Keyboard' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-
ative\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 92:26-45

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'LayoutAnimation' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0
react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 93:33-59

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Linking' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-n
tive\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 94:25-43

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'LinkingIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@reac
-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 95:28-49

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'NativeEventEmitter' in E:\workSpaces\probuck_by_react\node_modules\.0.3
.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 96:36-65

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'NavigationExperimental' in E:\workSpaces\probuck_by_react\node_modules\
0.30.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 97:40-73

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'NetInfo' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-n
tive\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 98:25-43

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'PanResponder' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@re
ct-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 99:30-53

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'PixelRatio' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@reac
-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 100:28-49

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'PushNotificationIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.
0.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 101:37-67

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Settings' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-
ative\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 102:26-45

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'StatusBarIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@re
ct-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 103:30-53

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'StyleSheet' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@reac
-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 104:28-49

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Systrace' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-
ative\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 105:26-45

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'TimePickerAndroid' in E:\workSpaces\probuck_by_react\node_modules\.0.30
0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 106:35-63

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'UIManager' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 107:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Vibration' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 108:27-47

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'VibrationIOS' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@re
ct-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 109:30-53

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'RCTDeviceEventEmitter' in E:\workSpaces\probuck_by_react\node_modules\.
.30.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 112:36-68

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'RCTNativeAppEventEmitter' in E:\workSpaces\probuck_by_react\node_module
\.0.30.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 113:39-74

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'NativeModules' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@r
act-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 114:31-55 148:13-37

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'Platform' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-
ative\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 115:26-45

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'processColor' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@re
ct-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 116:30-53

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'requireNativeComponent' in E:\workSpaces\probuck_by_react\node_modules\
0.30.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 117:40-73

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'ColorPropType' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@r
act-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 120:31-55

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'EdgeInsetsPropType' in E:\workSpaces\probuck_by_react\node_modules\.0.3
.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 121:36-65

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'PointPropType' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@r
act-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 122:31-55

ERROR in ./~/.0.30.0@react-native/Libraries/react-native/react-native.js
Module not found: Error: Cannot resolve module 'throwOnWrongReactAPI' in E:\workSpaces\probuck_by_react\node_modules\.0
30.0@react-native\Libraries\react-native
 @ ./~/.0.30.0@react-native/Libraries/react-native/react-native.js 179:31-62

ERROR in ./~/.0.30.0@react-native/lib/View.js
Module not found: Error: Cannot resolve module 'View' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react-nati
e\lib
 @ ./~/.0.30.0@react-native/lib/View.js 15:17-32

ERROR in ./~/.0.30.0@react-native/lib/UIManager.js
Module not found: Error: Cannot resolve module 'UIManager' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0@react
native\lib
 @ ./~/.0.30.0@react-native/lib/UIManager.js 15:17-37

ERROR in ./~/.0.30.0@react-native/lib/InitializeJavaScriptAppEngine.js
Module not found: Error: Cannot resolve module 'InitializeJavaScriptAppEngine' in E:\workSpaces\probuck_by_react\node_m
dules\.0.30.0@react-native\lib
 @ ./~/.0.30.0@react-native/lib/InitializeJavaScriptAppEngine.js 15:17-57

ERROR in ./~/.0.30.0@react-native/lib/RCTEventEmitter.js
Module not found: Error: Cannot resolve module 'RCTEventEmitter' in E:\workSpaces\probuck_by_react\node_modules\.0.30.0

**Comment by wZi** [comment]
+1

**Comment by silentcloud** [comment]
看着不像库的问题，你官方 init 的 demo 能跑？ 
或者你 clone https://github.com/ant-design/ant-design-mobile/issues/56 这里的 demo 试试能不能跑

**Comment by wZi** [comment]
我解决了，参考这个。。。
https://github.com/ant-design/ant-design-mobile/issues/66

**Comment by damiaozi** [comment]
看了 还是不知道怎么解决？
你是怎么解决的 后来？
