### ISSUE TITLE
ios9.3 系统中 searchbar 清除按钮点击不能清空

### ISSUE THREAD

**Issue by Cnax** [ant-design/ant-design-mobile#1312]
ios9.3 系统中 searchbar 清除按钮点击不能清空

**Comment by paranoidjk** [comment]
什么版本？能否提供可复现demo？另外是否只有ios 9.3Safari可复现？

**Comment by silentcloud** [comment]
我来确认一下这个问题

**Comment by silentcloud** [comment]
![test](https://cloud.githubusercontent.com/assets/1698185/26048451/c811d93c-3989-11e7-8a29-5d1b61b41524.gif)

@Cnax  没能重现

**Comment by silentcloud** [comment]
@Cnax 还有问题的话，再 reopen（传上你的 demo 和 gif）
