### ISSUE TITLE
当把 "svg-sprite-loader" 升级至最新版本 "^2.1.0"，“antd-mobile” 升级至最新版本 “^1.1.3”，Toast 组件(也可能是凡是涉及到Icon的组件)无法正常使用

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#1317]
报错信息为：
```
Uncaught (in promise) TypeError: type.substr is not a function
at Icon.render (eval at <anonymous> (http://m.college.duduapp.net/main.js725e3e7f4c3a73079bfa:1390:1)<anonymous>:40:16)
```

**Comment by paranoidjk** [comment]
duplicate https://github.com/ant-design/ant-design-mobile/issues/1283

先使用 svg-sprite-loader@0.3.0

**Comment by minooo** [comment]
@paranoidjk @silentcloud 问题重现步骤就在标题中，请确认这个BUG，谢谢！

**Comment by paranoidjk** [comment]
看我上面的回复

**Comment by asling** [comment]
在svg-sprite-loader@3.0.5上还会出现Uncaught TypeError: type.substr is not a function at Icon.render。请问要如何解决，还要先使用svg-sprite-loader@0.3.0吗？

**Comment by paranoidjk** [comment]
>antd-mobile Icon 所依赖的开源 webpack loader svg-sprite-loader 最近从 0.3 直接升级到了 2.0, 其配置方案发生了 break change，但由于此 loader 的版本由用户代码控制，而功能被 antd-mobile 和用户代码所共同依赖， antd-mobile 团队只能选择在 2.0 对其进行升级，请各位用户在 antd-mobile@1.x 期间暂时不要升级 svg-sprite-loader，在项目里仍然使用 svg-sprite-loader@0.3.x 即可。#1283

https://github.com/ant-design/ant-design-mobile/releases/tag/1.2.0

**Comment by jimwmg** [comment]
最后这个问题怎么解决的啊 @minooo

**Comment by minooo** [comment]
@jimwmg 把 svg-sprite-loader 的版本回退到0.3，直到antd-mobile 解决这个问题。

**Comment by iNikNik** [comment]
@minooo @jimwmg 
This code does the job with latest sprite-loader
```import likeIcon from 'common/components/ui-kit/icons/like.svg'
<Icon type={`#${likeIcon.id}`}/>
```
