### ISSUE TITLE
Toast组件的loading不显示svg图片

### ISSUE THREAD

**Issue by MailKiller** [ant-design/ant-design-mobile#1320]
### Version
1.1.3

### Environment
web

### Reproduction link
[http://192.168.1.103:3000/#/](http://192.168.1.103:3000/#/)

### Steps to reproduce
本地开发

### What is expected?
Toast.loading显示转圈的svg图片

### What is actually happening?
Toast.loading不显示转圈的svg图片

**Comment by paranoidjk** [comment]
svg-sprite-loader是否配置，什么版本，给出console 报错

**Comment by MailKiller** [comment]
svg-sprite-loader配置了，版本0.3.1。
client?7a7a:119 ./~/_antd-mobile@1.1.3@antd-mobile/lib/toast/style/assets/success.svg
Module build failed: Error: A valid query string passed to parseQuery should begin with '?'
    at Object.parseQuery (E:\webpack-demo\testapp\node_modules\_loader-utils@1.1.0@loader-utils\lib\parseQuery.js:13:9)
    at Object.module.exports (E:\webpack-demo\testapp\node_modules\svg-sprite-loader\index.js:14:27)

**Comment by paranoidjk** [comment]
请给出完整配置或你的项目，建议先自行搜索一下报错内容

**Comment by mosaic101** [comment]
I have a same problem. Reference to https://github.com/ant-design/ant-design-mobile/issues/1283  , may be helpful to you. @MailKiller

**Comment by paranoidjk** [comment]
close for no response, please follow https://mobile.ant.design/components/icon#如何使用-(WEB-版)

**Comment by McLemore** [comment]
所有icon都有问题，因为svg-sprite-loader2.0以后的版本向前不兼容，antd-mobile依赖svg-sprite-loader2.0，所以antd-mobile需要做对应的迁移，如何迁移见文档：https://github.com/kisenka/svg-sprite-loader/blob/master/2.0.md
