### ISSUE TITLE
SwipeAction can't work

### ISSUE THREAD

**Issue by KnightTQ** [ant-design/ant-design-mobile#1322]
### Version
1.1.3

### Environment
chrome

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/swipe-action?lang=zh-CN#swipe-action-demo-0](https://mobile.ant.design/kitchen-sink/components/swipe-action?lang=zh-CN#swipe-action-demo-0)

### Steps to reproduce
try https://mobile.ant.design/kitchen-sink/components/swipe-action?lang=zh-CN#swipe-action-demo-0

### What is expected?
it work

### What is actually happening?
not work

**Comment by paranoidjk** [comment]
duplicated https://github.com/ant-design/ant-design-mobile/issues/1321

**Comment by silentcloud** [comment]
@KnightTQ  先临时重装一下 node_modules，确定 rc-hammerjs 是 0.6.4

**Comment by KnightTQ** [comment]
@silentcloud 
├─┬ antd-mobile@1.1.3
│ ├─┬ rc-swipeout@1.3.3
│ │ └── rc-hammerjs@0.6.5
│ └── UNMET PEER DEPENDENCY react-native@*
└── UNMET PEER DEPENDENCY react@15.4.2

**Comment by paranoidjk** [comment]
`rm -rf node_modules && npm i`
