### ISSUE TITLE
ReactNative Picker组件列表中的字体样式设置

### ISSUE THREAD

**Issue by darin-lao** [ant-design/ant-design-mobile#1323]
### What problem does this feature solve?
现在默认体字太大了

### What does the proposed API look like?
可以通过属性设置样式

**Comment by silentcloud** [comment]
@darin-lao RN 标准组件（http://facebook.github.io/react-native/docs/picker.html）的大小，改不了的，你可以去 react-native 官方提 issue

**Comment by paranoidjk** [comment]
@silentcloud RN 官方组件的样式是跟随屏幕缩放的吗？

**Comment by silentcloud** [comment]
@paranoidjk 不是缩放，是按标准的 dp 来做的

**Comment by paranoidjk** [comment]
@silentcloud dp 是 native 单位，那 RN 的组件其实是在 native 侧实现的？

**Comment by silentcloud** [comment]
@paranoidjk  是的，其实就是这种 http://facebook.github.io/react-native/docs/native-components-ios.html

**Comment by silentcloud** [comment]
@paranoidjk picker 组件其实在 native（iOS ）就是 UIPickerView https://github.com/facebook/react-native/blob/master/React/Views/RCTPicker.m

**Comment by silentcloud** [comment]
这个还得 reopen，这个组件是经过 `rmc-cascader` 做了包装的，要在  `rmc-cascader` 里做个处理

**Comment by PatWu16** [comment]
@silentcloud 请问目前有解决方案可以参考吗？

**Comment by darin-lao** [comment]
@PatWu16 下一个版本增加了ItemStyle属性设置

**Comment by silentcloud** [comment]
恩是的，等下个版本，用 itemStyle

**Comment by PatWu16** [comment]
谢谢，期待
