### ISSUE TITLE
Carousel做轮播图 在安卓端有个小问题 iOS端正常显示

### ISSUE THREAD

**Issue by xqwIOS** [ant-design/ant-design-mobile#1328]
const imgs = [
	{image:'http://www.djwpz.cn/images/1.jpg'},
	{image:'http://www.djwpz.cn/images/2.jpg'},
	{image:'http://www.djwpz.cn/images/3.jpg'},
	{image:'http://www.djwpz.cn/images/4.jpg'}];
class Home extends Component {
	// 构造
	constructor(props) {
		super(props);
	}
	render() {
		return (
			<View style={ styles.container}>
				<HeadView
					titleView = '首页'/>
				<View style={styles.wrapper}>
					<Carousel
						style={styles.wrapper}
						autoplay
						infinite
						afterChange={this.onselectedIndexChange}>
						{imgs.map((item,i) => {
							console.log(item.image);
							return (
								<View key={i} style={[styles.container]}>
									<Image 
                                                                                  source={{uri:item.image}}  
                                                                                  style={{height:150,width:Screen.width}} />
								</View>
							);
						})}
					</Carousel>
				</View>
			</View>
		);
	}
}
const styles = StyleSheet.create({
	container: {
		flex: 1
	},
	wrapper:{
		width:Screen.width,
		height:150
	}
});
export default Home;

运行后四张图片就显示最后加载的那张图片

**Comment by xqwIOS** [comment]
在线等

**Comment by paranoidjk** [comment]
@ant-design-bot markdown
