### ISSUE TITLE
使用picker组件，新pull下来的代码生成依赖包报【semver】

### ISSUE THREAD

**Issue by tainanqi** [ant-design/ant-design-mobile#1329]
项目里面引入picker组件，自己本地的项目没有报错，但是重git上面新pull下来的代码生成依赖的时候都报了依赖【semver】，启动项目的时候报错，找不到rmc下的picker包
然后尝试修改在package里的dependencies引入 "rmc-picker":"3.0.7"然后重新生成依赖，启动没有报错，但是picker在antd-mobile封装的一些属性就不能用了。

**Comment by paranoidjk** [comment]
给出具体报错内容，antd-mobile 版本，最好给出你的可重现 demo
