### ISSUE TITLE
SearchBar 提供 defaultValue

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#133]
## 期待

指定 value 时应该完全受控，不应响应交互。

## 实际

现在的 value 指定后仍然可以输入修改。

## 演示

第一个例子

http://mobile.ant.design/components/search-bar

**Comment by warmhug** [comment]
InputItem 、TextareaItem ，也要提供 defaultValue ，在不设置 value 时使用 defaultValue 并允许输入，和 react 原生 input / textarea 行为保持一致

**Comment by warmhug** [comment]
@pingan1927 这几个需求什么时候做？业务需要。。

**Comment by pingan1927** [comment]
我晚上加好
