### ISSUE TITLE
SwipeAction Not Working

### ISSUE THREAD

**Issue by caigehui** [ant-design/ant-design-mobile#1334]
### Version
1.1.3

### Environment
lastest Chrome / iOS 10.3

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/swipe-action?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/swipe-action?lang=zh-CN)

### Steps to reproduce
Access the demo: https://mobile.ant.design/kitchen-sink/components/swipe-action?lang=zh-CN

Then you can't swipe the cell or do anything

### What is expected?
SwipeAction works normally

### What is actually happening?
Unfortunately it's broken and it logs TypeError

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1321

`rm -rf node_modiles && npm i ` 升级依赖
