### ISSUE TITLE
when use picker , click ok or cancel,  e.nativeEvent is not defined!

### ISSUE THREAD

**Issue by huyansheng3** [ant-design/ant-design-mobile#1336]
### Version
1.1.3

### Environment
chrome 

### Reproduction link
[http://github.com](http://github.com)

### Steps to reproduce
<Picker data={data} cols={1} {...getFieldProps('order_id')}>
	          <Item arrow="horizontal" className='feedback__picker'>请填写相关订单号(选填)</Item>
	        </Picker>

弹出选项后，选择其中一个选项，点击确定或者取消就报错了！
![image](https://cloud.githubusercontent.com/assets/11534583/26185880/31437d92-3bc0-11e7-8cfd-186a9315e476.png)
![image](https://cloud.githubusercontent.com/assets/11534583/26185882/37eae716-3bc0-11e7-9e2b-175acb40907e.png)

### What is expected?
不报错！

### What is actually happening?
提示 e.nativeEvent 为 undefined！
调用了 node_modules/rc-touchable/lib/PressEvent，最终的出错结果也在此文件中。、
function shouldFirePress(e) {
      var nativeEvent = e.nativeEvent,
          $longPressSeq = e.$longPressSeq;
  
      if (!nativeEvent.$longPressStopSeq) {
          return true;
      }
      return nativeEvent.$longPressStopSeq >= $longPressSeq;
  }

在点击事件对象传递的过程中 e.nativeEvent 不晓得为什么丢失了，所以在这里就报错了！

---
代码很简单，跟官方例子一样.
项目全局引入的 fastclick，是否有可能是此处的原因？ 
出错的调用栈应该为： 
node_modules/antd-mobile/lib/picker/index.js
"node_modules/rmc-cascader/lib/Popup.js
node_modules/rmc-picker/lib/Popup.js
node_modules/rc-touchable/lib/index.js
node_modules/rc-touchable/lib/PressEvent.js

**Comment by paranoidjk** [comment]
请先尝试 `rm -rf node_modules && npm i ` 升级依赖，最近 rc-touchable 有升级，请贴出你的 rc-touchable 版本

**Comment by huyansheng3** [comment]
执行 rm -rf node_modules && npm i 搞定了 3q!
