### ISSUE TITLE
哪些 样式变更 算 break change ?  如何处理

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#1340]
几种情况：

1. 更改 less 变量名，如`margin-top: @v-spacing-md;` => `margin-top: @v-spacing-sm;`
2. 更改 less 变量值，如`@tag-height: 48px;` => `@tag-height: 50px;`
3. 直接修改 css 值 (无 less 变量设置)，如`color: #ccc;` => `color: #ddd;`

**Comment by warmhug** [comment]
1 2 算 break, 3 不算。
版本号怎么定？考虑到 UI 细节变化比较快、对这类 break 建议升级 中间 版本号，不算完全遵循 semver 规则。

**Comment by afc163** [comment]
2 肯定不算。

**Comment by paranoidjk** [comment]
从用户升级成本的角度来考虑：

> 只考虑对官方支持的样式自定义方法进行兼容: theme + props.style + defaultPoprs.prefixCls

1. 不需要用户修改他的 `theme.less`
2. 不需要用户来修改他的业务样式（布局，对antd-mobile组件的外围样式）

**Comment by peter0011** [comment]
设计上变量分2层：多个组件使用（通用变量）+单一组件使用（组件变量）。最终希望通用变量能够精简并且保持稳定。

**Comment by silentcloud** [comment]
gitlab 有个需求： 将通用变量改名： `@fill-overlay-inverse` => `@toast-fill` 这个应该算是 break change 了

**Comment by afc163** [comment]
@fill-overlay-inverse 不变。增加一个 @toast-fill 指向 @fill-overlay-inverse

**Comment by warmhug** [comment]
在 要废弃的 less 变量边，写上注释 `// Deprecated` 便于下个版本移除。

那么现在只剩下 `margin-top: @v-spacing-md;` => `margin-top: @v-spacing-sm;` 这个变更没法兼容解决了？

**Comment by afc163** [comment]
这种算样式调整，不算不兼容问题。

**Comment by warmhug** [comment]
这种样式调整影响有点大：用户会疑惑改 theme 文件值，怎么相应组件样式没改、或怎么变乱了？
既然提供 theme 文件和 less 变量给用户，也要当成 API 对待吧。

**Comment by paranoidjk** [comment]
theme变量就是api，因为改动会涉及到用户改代码
