### ISSUE TITLE
Search组件在点击X清除后，安卓平台无法再次focus

### ISSUE THREAD

**Issue by welkang** [ant-design/ant-design-mobile#1341]
### Version
1.0.0

### Environment
安卓

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/search-bar?lang=zh-CN#search-bar-demo-0](https://mobile.ant.design/kitchen-sink/components/search-bar?lang=zh-CN#search-bar-demo-0)

### Steps to reproduce
search组件输入内容后点击X按钮清除，之后再点击search bar，无法focus。

### What is expected?
期望点击X保留focus状态，或者允许后续点击focus

### What is actually happening?
无法focus。

**Comment by paranoidjk** [comment]
请先尝试最新 1.1.3 是否没问题

**Comment by pingan1927** [comment]
我明天处理
