### ISSUE TITLE
修改web控件样式的问题

### ISSUE THREAD

**Issue by kimjuny** [ant-design/ant-design-mobile#1343]
### What problem does this feature solve?
发现很多控件的样式都需要用js的方式控制样式，比如TabBar控件，unselectedTintColor、tintColor、barTintColor这些值都要直接写在控件的props上，这样就导致一些值不好复用的问题。

现在假设我有一个theme.base.less，里面设置了统一的@tint-color: red，我现在的使用方式是通过修改控件本身的theme(官方推荐的less-vars-to-js覆盖控件主题的方式)修改的控件的默认样式。但问题是控件用的地方多，肯定会有一些自定义的样式，控件上的tintColor还是需要个别设置的情况，我的问题归根结底就是除了设置控件本身的theme外有没有其他方式可以让我从less上读取值然后赋值到特定的控件props上？

### What does the proposed API look like?
有没有某种优雅的方式可以让我从less取值赋值到控件中的props中

**Comment by paranoidjk** [comment]
> 有没有某种优雅的方式可以让我从less取值赋值到控件中的props中

less-vars-to-js 做的就是这件事

**Comment by kimjuny** [comment]
我把问题发到SO上了：http://stackoverflow.com/questions/44063762/how-can-i-read-less-variables-in-javascript
