### ISSUE TITLE
Tabs 组件的 swipeable 属性在 rn 环境中无效

### ISSUE THREAD

**Issue by F-happy** [ant-design/ant-design-mobile#1346]
### Version
1.1.3

### Environment
react-native 0.43.0

### Steps to reproduce
```
<Tabs activeKey={this.state.activeKey} swipeable={true}>
    <TabPane tab="A" key="1">
        <MerchantManage {...this.props}/>
    </TabPane>
    <TabPane tab="B" key="2">
         <MerchantPhotoPage {...this.props}/>
    </TabPane>
</Tabs>
```

### What is expected?
TabPane中的内容可以正常左右滑动

### What is actually happening?
并不能滑动，后面发现当swipeable设置成 false 的时候就能滑动了，是不是代码里面这里的判断写反了呢？

**Comment by junwei1114** [comment]
谷歌的手机模拟器中也无效   
          `<Tabs tabs={tabs}
                  initalPage={'t2'}
                  tabBarPosition="left"
                  tabDirection="vertical"
                  swipeable={false}
                  useOnPan={true}
            >`
