### ISSUE TITLE
icon图标无法显示

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design-mobile#1349]
### Version
1.1.3

### Environment
chrome ant-mobile：1.1.4-beta.1  "roadhog": "^0.6.0"

### Reproduction link
[https://github.com/SynChron1zed/AntMobileDemo](https://github.com/SynChron1zed/AntMobileDemo)

### Steps to reproduce
打开git

### What is expected?
显示图标

### What is actually happening?
不显示

---
按照官网上的说 将roadhog升级到0.6.0 但是图标还是不显示出来

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/26240422/8f396026-3cb3-11e7-9a60-5ce170331e0b.png)

是有哪里没有配置么

**Comment by paranoidjk** [comment]
https://github.com/ant-design/antd-mobile-samples/blob/master/antm-roadhog/.roadhogrc.js#L11

**Comment by paranoidjk** [comment]
.roadhogrc 删掉，.roadhogrc 优先级高，.roadhogrc.js 无效

**Comment by SynChron1zed** [comment]
@paranoidjk  thanks

**Comment by SynChron1zed** [comment]
@paranoidjk  麻烦你了 能不能在帮我看个问题  。

![image](https://cloud.githubusercontent.com/assets/18717051/26241155/403a62f6-3cb6-11e7-93a2-c8eec24b5633.png)
![image](https://cloud.githubusercontent.com/assets/18717051/26241168/4f11ff82-3cb6-11e7-95a9-9e433d6dbf38.png)

引用自定义的这个路径该怎么写 我试了几种都不对

**Comment by paranoidjk** [comment]
引用的路径与你 svgSpriteLoaderDirs 配置无关，按本地相对路径写。

**Comment by SynChron1zed** [comment]
@paranoidjk  是的  我看了其他例子改了 谢了
