### ISSUE TITLE
自定义内容时 Grid 单元格高度自适应

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1352]
正方形布局满足不了业务需求。

很多类似微信的表情面板，高度是固定，每行个数固定，宽度自适应。

**Comment by Jeffy2012** [comment]
根据格数控制宽度，搞定根据里面内容自动撑开(一般每格的高度一样，不用care高度不一样的情况)

**Comment by paranoidjk** [comment]
- Grid 格子的高度默认是正方形，但当自定义格子内容的时候，格子高度默认为0，随用户填充的内容高度变化
- Grid 每行格子的个数只允许 3个 / 4个 （对应两种尺寸的标注）

**Comment by paranoidjk** [comment]
Grid 布局的时候，格子之间的间距是顶端和底部间距的两倍，不满足实际业务的需求。

**Comment by paranoidjk** [comment]
![img_0036](https://user-images.githubusercontent.com/7971415/28607050-9e93da40-720c-11e7-8fd3-32eafd73c42d.PNG)

**Comment by paranoidjk** [comment]
<img src="https://gw.alipayobjects.com/zos/rmsportal/faOSXpZGjuRzfmeyyzgf.png">

<img src="https://gw.alipayobjects.com/zos/rmsportal/faOSXpZGjuRzfmeyyzgf.png">
