### ISSUE TITLE
Refactor all the ref: string to ref: function

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1354]
https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs

https://github.com/ant-design/ant-design/issues/5570

- [x] ImagePicker  https://github.com/ant-design/ant-design-mobile/pull/1487

**Comment by benjycui** [comment]
FYI，放到 2.0 的原因 https://github.com/ant-design/ant-design/pull/3979#issuecomment-262517396
