### ISSUE TITLE
React Native 自定义主题无效

### ISSUE THREAD

**Issue by icodytan** [ant-design/ant-design-mobile#1356]
### Version
1.1.3

### Environment
antd-mobile: 1.0.0\1.1.4-beta.1, react-native: 0.41.2

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui](https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui)

### Steps to reproduce
- npm i
- react-native run-android

### What is expected?
brand_primary 为 red 的 tag，border 为 green

### What is actually happening?
主题色没有变化

---
- 在项目中根据 https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui 进行修改主题色，但没有效果。
- 下载该例子运行，发现该例子主题色也没有变化。

**Comment by silentcloud** [comment]
![abc](https://cloud.githubusercontent.com/assets/1698185/26289960/b6b1b8d6-3ed6-11e7-826c-3cf9d96e1b15.gif)

@icodytan 没问题吧

**Comment by icodytan** [comment]
![jianguo](https://cloud.githubusercontent.com/assets/14866288/26318470/c46abea6-3f4d-11e7-885d-fede91dee4ff.gif)
)
![nexus](https://cloud.githubusercontent.com/assets/14866288/26318622/5a9c74c8-3f4e-11e7-820b-3e69986b9f1f.jpg)

@silentcloud 在 Android 真机及模拟器都无效

**Comment by silentcloud** [comment]
@icodytan 还是没能重现

![abc](https://cloud.githubusercontent.com/assets/1698185/26337451/61e64c1a-3fab-11e7-8f7d-6c5714c825e4.gif)

**Comment by silentcloud** [comment]
你是不是 `npm start` 运行的 server？不能直接 `react-native start` 或者 `npm run rn-start` 的

**Comment by icodytan** [comment]
@silentcloud 谢谢你，确实是没先运行 npm start 的问题
