### ISSUE TITLE
antd-mobile中的高清方案导致百度地图显示文字过小

### ISSUE THREAD

**Issue by jingchenxu** [ant-design/ant-design-mobile#1357]
### What problem does this feature solve?
项目中需要使用到百度地图，用于位置的显示，项目发布于移动端，根据教程设置了高清方案，设置了之后百度地图显示的文字比较小，难以查看。

### What does the proposed API look like?
对于百度地图中的文字正常显示，不要做高清适配的处理。

**Comment by pingan1927** [comment]
1：如果百度地图组件本身支持高清方案，可以仔细看看百度地图文档，加上相关参数。
2：如果地图渲染本身已经支持，仅仅可枚举的文字需要单独处理，可以业务上覆盖样式处理。
3：如果不想要高清方案，可以写死meta标签，固定initial-scale = 1，其他保持不变。

**Comment by warmhug** [comment]
ref #799

**Comment by jingchenxu** [comment]
经过自己的测试及搜索，百度地图不支持高清方案，地图中的样式都是内联样式，写的是px单位，该问题是项目后期产生的，如果此次取消高清方案，可能会对其它的页面造成影响，目前的解决方案是：单独为此页面修改meta，在路由跳转到该页面时，修改meta为：metaEl.setAttribute('content', 'width=device-width,user-scalable=no');，该页面的所有样式使用px，而不是用rem,当该页面卸载时恢复为原来的meta。
