### ISSUE TITLE
输入类组件中英文混输line-height异常，会被截断一部分

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#1358]
### Version
最新
![default](https://cloud.githubusercontent.com/assets/347649/26290584/3708c43a-3edb-11e7-8bca-b3b3b21f210f.png)

### Environment
iOS

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/3da49db5](https://riddle.alibaba-inc.com/riddles/3da49db5)

### Steps to reproduce
InputItem输入`gj中文`

### What is expected?
文字显示正常

### What is actually happening?
gj被截断

**Comment by warmhug** [comment]
iOS 10 模拟器上没发现问题

**Comment by silentcloud** [comment]
这个我重现了，我试了哈改 input 的 padding 貌似能 fix
