### ISSUE TITLE
npm run dist 失败，ci 失败

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1360]
排查了哈原因：大概是因为 uglifyjs-webpack-plugin 目前不支持 es 的压缩，

https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/33

https://github.com/mishoo/UglifyJS2/tree/harmony

**Comment by paranoidjk** [comment]
es下的文件没经过babel转码？

**Comment by paranoidjk** [comment]
我以为es和lib的目录只是使用 es6 module  而已，语法还是编译过后的 es5?

**Comment by silentcloud** [comment]
@paranoidjk 我看编译后貌似不是 es5了，会有 import export 等

我尝试了在自定义 webpack.config 里覆盖 UglifyJsPlugin 也没能搞定，囧

**Comment by paranoidjk** [comment]
只有 import 和 export 这个  module syntax, 其他 es6 语法还是转了的
https://unpkg.com/antd-mobile@1.1.4-beta.1/es/button/index.web.js

另外，es 目录下的不是不经过 uglify 吗？

**Comment by silentcloud** [comment]
@paranoidjk dist 是打包  antd-mobile.min.js

**Comment by paranoidjk** [comment]
打 antd-mobile.min.js umd bundle 的时候不应该牵扯 es 吧？保持原来的逻辑就好了，src -> babel -> lib -> webpack + uglify > min.js

**Comment by silentcloud** [comment]
@paranoidjk 现在的貌似是走的  src -> babel -> es -> webpack + uglify > min.js

**Comment by paranoidjk** [comment]
@yiminghe 
- dist 构建错导致你发的 1.1.4-beta.1 是少了 dist 的 https://unpkg.com/antd-mobile@1.1.4-beta.1/
- 而且 beta 版本不应该发到 latest 上 https://www.npmjs.com/package/antd-mobile

**Comment by paranoidjk** [comment]
去掉uglify plugin之后build success, 但是 bundle 并不是有效的 umd，还是一堆 **import '../components/xx'**

**Comment by paranoidjk** [comment]
这个 close. @warmhug 应该已经 fix 了，记得来这里把原因写下。

**Comment by squallvince** [comment]
本地运行“npm run dist”会报错，“Failed at the antd-mobile@1.1.4-beta.4 dist script 'BABEL_ENV=dist antd                                                                                -tools run dist'.”

**Comment by paranoidjk** [comment]
@saiyagg `rm -rf node_modules && npm i ` 重装依赖，如果使用 yarn 则 `yarn upgrade`, 这个问题已经在新版的 `antd-tools` 修复了，确保你升级到最新版。

**Comment by squallvince** [comment]
删除BABEL_ENV=dist后，脚本执行正确。

**Comment by warmhug** [comment]
@squallvince 看下 node npm 版本是否太老了。
---

原来报错原因主要有两点：

1. `.babelrc` 文件里的 react-native presets 优先级最高，覆盖了 antd-tools 里提供的 presets .
2. antd-tools 生成 es 目录、支持保留源码里的 `import .. from ..`和`export default ..`，但对这些语句 UglifyJsPlugin 压缩出错。
