### ISSUE TITLE
add doc about work with create-react-app/create-react-native-app

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1362]
https://ant.design/docs/react/use-with-create-react-app-cn

https://github.com/ant-design/ant-design-mobile/issues/1361

**Comment by paranoidjk** [comment]
also need create-react-native-app usage doc @silentcloud 

https://github.com/ant-design/babel-plugin-import/issues/131
https://github.com/ant-design/ant-design-mobile/issues/1333#issuecomment-302358107

**Comment by paranoidjk** [comment]
https://github.com/yarnball/antd-mobile-create-react-app/pull/1

**Comment by 15210873185** [comment]
antd-mobile里面的组件inputItem里面文字的大小怎么改变呢

**Comment by silentcloud** [comment]
@15210873185 react-native 还是 web ？
