### ISSUE TITLE
same code(design, behavior) for android web and ios web

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#1371]
- switch
- list
- modal

in order to reduce bundle size and complexity

**Comment by silentcloud** [comment]
List 现在是一致的

**Comment by silentcloud** [comment]
目前平台不一致的 web 端应该就 switch 和 modal，但底层代码基本差不多，样式区别

**Comment by paranoidjk** [comment]
ListItem android 有个点击水波纹效果 @pingan1927  加的

这个样式不一致，之前和设计师讨论过几轮，没个结论

**Comment by pingan1927** [comment]
处于`reduce bundle size`，我觉得重点应该是树立基于移动优先原则，把很多重依赖的，实际业务运行效果体验较差的从PC组件挪过来的组件重构。

**Comment by peter0011** [comment]
问题在于web组件是否要符合平台的特性。还是统一做一套？

**Comment by paranoidjk** [comment]
赞成2.0统一，目前依赖客户端ua检测给服务端渲染带来不少麻烦 https://github.com/ant-design/ant-design-mobile/pull/1061#issuecomment-312527396

**Comment by paranoidjk** [comment]
@peter0011 跟业务线的设计师收集下意见，定下来 2.0 这些有区别的组件统一成 ios 的样式是否 ok ?

**Comment by peter0011** [comment]
就设计这边的需求来说，肯定是希望组件在各自平台符合平台规范。这是前端上可以控制不强制调整样式，只提供可选。

**Comment by paranoidjk** [comment]
@peter0011 那就是 2.0 改成默认组件库都默认使用 ios 样式。但用户可以配置自动切换或者使用 android样式。

cc @warmhug

**Comment by peter0011** [comment]
yes

**Comment by silentcloud** [comment]
>   那就是 2.0 改成默认组件库都默认使用 ios 样式。但用户可以配置自动切换或者使用 android样式。

那感觉就还是现在这个样子么，issue 直接关了？

**Comment by paranoidjk** [comment]
@silentcloud 不是，现在默认是自动根据 ua 切换，这个行为要改

**Comment by silentcloud** [comment]
哦，对，理解错了，这个我等会来搞定
