### ISSUE TITLE
0.8 changelog

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#138]
changelog 收集

**Comment by silentcloud** [comment]
#### Web 组件
- Tabs 拆分为 SegmentedControl、TabBar、Tabs 组件；
#### RN 组件
- 新增 Tabs、SegmentedControl、TabBar 组件

**Comment by benjycui** [comment]
* 新增 rn-grid

**Comment by 214132049** [comment]
升级向下兼容吗？

**Comment by warmhug** [comment]
@214132049 大多API都兼容

**Comment by warmhug** [comment]
- Dropdown 效果和 `ActionSheet.showActionSheetWithCustom` 效果集成到新增的`Popup`组件里；`ActionSheet.showActionSheetWithCustom` API 移除

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/compare/0.7.x...master

**Comment by silentcloud** [comment]
@afc163 你这个整理起来太费时间了，大概的内容还是要写下

**Comment by afc163** [comment]
我只是留个链接方便查询，antd 都是这么做的，发布前按 commit 挨条写，这样不会漏。
