### ISSUE TITLE
重新整理和定义各组件的 style 

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1380]
目前的组件基本都是把 style 定义在最外层的那个容器元素上，但实际上可能这个 style  定义在内层某些具体元素上才更有意义，比如: InputItem  的 style 定义在 input 元素上会更好，还有 TextareaItem 等等

**Comment by huyansheng3** [comment]
是的！ 所以有什么比较好的办法解决这个问题吗？
 ant-mobile rn 组件 增加 style 也只是给最外层容器加，估计只能拷贝份 styles，然后改需要的 styles 属性。

**Comment by paranoidjk** [comment]
@huyansheng3 https://github.com/ant-design/ant-design-mobile/issues/1182

**Comment by silentcloud** [comment]
@huyansheng3 只能这么干，后期改成纯对象了其实也是类似，只不过少了一次 stylesheet.flatten 而已

**Comment by benjycui** [comment]
就从 web 组件的角度而言，`style` 和 `className` 应该是一一匹配才对？

e.g.

```txx
interface Component {
  style?: ...
  className?: ...
  subStyle?: ...
  subClassName?: ...
};
```
