### ISSUE TITLE
inputItem 优化建议

### ISSUE THREAD

**Issue by Cnax** [ant-design/ant-design-mobile#1383]
### What problem does this feature solve?
inputItem 设置type='number'， 不能唤起数字键盘，type='phone' 可以唤起

### What does the proposed API look like?
希望设置type='number'，可以唤起数字键盘

**Comment by pingan1927** [comment]
你想要的是带小数点的数字键盘？这个除非app支持自定义键盘，目前没法支持。
后续考虑用H5自己模拟一个。

**Comment by cncolder** [comment]
@pingan1927 模拟键盘还是交给用户自己吧，或者可能已经有 react-keyboard 这样的组件了。

因为一想到这个就会联想起各种网银登录时使用的所谓“安全键盘”，换着花样的难看又难用。

**Comment by pingan1927** [comment]
这里仅仅指基于alipayui的带小数点数字键盘，没啥花样，内部用户先满足掉，现在app提供自定义键盘的太伤了。

**Comment by silentcloud** [comment]
H5 是没办法模拟键盘的，这个至少在目前的 iOS 版本是不可能的

**Comment by pingan1927** [comment]
@silentcloud 不是模拟触发系统自带键盘，而是画一个跟支付宝客户端一样的键盘，因为只需要支持数字，所以可行性还是有的！
就跟`Picker`与系统自带Picker一样的关系

**Comment by paranoidjk** [comment]
-1 至少目前来看，要到用 H5 实现键盘的程度，优先级太低

**Comment by silentcloud** [comment]
@pingan1927 不行的，原生的键盘弹出的事件没有 native code 你是阻止不了的

**Comment by pingan1927** [comment]
这个我先在业务里实现。B端收款项目带小数点的自定义键盘是强需求，这是前提。
几个原因决定我需要尝试实现
* iOS和Android的处理方案完全两套，代码量以及复杂度急剧增加。而且不能通用化。
* iOS功能可用，但特定体验有欠缺，一旦交互复杂，例如input focus时需要input 上方的dom元素进行高度变化，则通过native实现的键盘需要重新初始化，出现键盘弹出 => 收起 => 再弹出。
* Android功能有问题，Android 目前的实现一些异常输入前端代码完全没法hold住，`.98`都不能格式化成`0.98`，虽然很多问题都是`input number` + `react`组合出来才会出现的问题。如果Android的自定义键盘不依赖于type=number是可以解决，但这个也需要等客户端升级之后才支持。
* 最大一点，现在自定义键盘的支持都依赖于特定的客户端，而antd-mobile的运行环境不可预知。如果能够在H5实现键盘，一切问题都迎刃而解，issues里关于number的InputItem 切合不支持小数点的疑问也就消停了。
* 可以看看支付宝里的理财小工具=> 汇率换算， @silentcloud 已经类似的H5实现。

**Comment by silentcloud** [comment]
> 可以看看支付宝里的理财小工具=> 汇率换算， @silentcloud 已经类似的H5实现。

恩，原来不是真正的输入框，这样的话确实可以画

**Comment by paranoidjk** [comment]
那就意味着不能用 `input` 触发了。

**Comment by pingan1927** [comment]
> 那就意味着不能用 `input` 触发了。

理想情况下，`InputItem`的`type`为`digit`暴露出来的API能够做到和其他type的表现一致。在我看来，这已经是实现带小数点的数字键盘之唯一可行通用方案。

**Comment by justLearner** [comment]
How do I use onChange property?
