### ISSUE TITLE
InputItems' keyboard hiding bottom items when pages opened inside android app

### ISSUE THREAD

**Issue by pimkle** [ant-design/ant-design-mobile#1385]
### Version
1.1.3

### Environment
MI 4L TE Android 6.0.1

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item?lang=zh-CN#input-item-demo-0](https://mobile.ant.design/kitchen-sink/components/input-item?lang=zh-CN#input-item-demo-0)

### Steps to reproduce
I wrote a page using antd-mobile, with a lot of InputItems, opening it in system default browser is okay, but when embeded in an android app, when I focus the bottom inputItem, keyboard shows up, hiding everything in the bottom, the scroller doesn't scroll as it does in default browsers.

### What is expected?
when a page with a lot of InputItems is embed in an android app, focusing the items in the bottom, keyboard shows up, scrollbar scrolls as well, not covering anything.

### What is actually happening?
when a page with a lot of InputItems is embed in an android app, focusing the items in the bottom, keyboard shows up, scrollbar doesn't scroll, keyboard block the bottom input items.

---
I want to know whether I've missed any props which led to this result, if not, I want to know when antd-mobile can fix it.

**Comment by paranoidjk** [comment]
We can not control the browser behavior. 

You can try to use [scrollIntoViewIfNeeded](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded) during InputItem `onFocus`

**Comment by pimkle** [comment]
thank you very much!
