### ISSUE TITLE
ios InputItem组件 原生键盘无法收回

### ISSUE THREAD

**Issue by aiien007** [ant-design/ant-design-mobile#1386]
### What problem does this feature solve?
rn版本：0.42.3
ios版本：8.2
我下载了antd-mobile demo里面的InputItem 例子都可以点击输入框以外的地方键盘收回
但是我把例子放到项目里 无法收回键盘

### What does the proposed API look like?
ios点击InputItem 失去焦点时，键盘不消失

**Comment by silentcloud** [comment]
@ant-design-bot  demo

**Comment by aiien007** [comment]
@silentcloud 
https://codepen.io/anon/pen/ZKZeqQ
这样子可以吗 搞了半天没法注册

**Comment by paranoidjk** [comment]
react-native 没法再 codepen 里跑，抽象一个简单的可复现 demo 提交到 github，给出地址吧

**Comment by silentcloud** [comment]
@aiien007 直接用确实是不能 blur 的，RN 官方的 TextInput 也是这样，demo 之所以会 blur，是外层套了 ScrollView 的

**Comment by aiien007** [comment]
@silentcloud 
外层套了 ScrollView能给点思路吗？我在源码没找到如何嵌套的？
