### ISSUE TITLE
IndexedList的listView官方演示demo在iphone5、6safari下点击左边quickSearchBar会出现底部一些数据消失

### ISSUE THREAD

**Issue by liangqi0518** [ant-design/ant-design-mobile#1388]
### Version
1.1.3

### Environment
ios7.1.2

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/list-view?lang=zh-CN#list-view-demo-3](https://mobile.ant.design/kitchen-sink/components/list-view?lang=zh-CN#list-view-demo-3)

### Steps to reproduce
进入页面后点击B往下任何一个索引

### What is expected?
显示该索引对应的数据

### What is actually happening?
数据没有显示

目前开发测试中也同样遇到了这个问题

**Comment by paranoidjk** [comment]
ios 7 的版本太低了吧，现在应该基本不维护了。

iPhone 6sp, ios 10.3, safari 测试没问题。

**Comment by liangqi0518** [comment]
我用iphon6也测试了，ios版本是10.2.1，也同样有这个问题，打开页面后第一次点击索引左边无数据

**Comment by liangqi0518** [comment]
![_20170526214415](https://cloud.githubusercontent.com/assets/28980309/26497080/ae8f73c6-425c-11e7-8647-f1f6f14ecab1.jpg)
@paranoidjk 上面是出问题的效果，比如点击索引H

**Comment by czewail** [comment]
我也遇到了这样的问题，请问有解决办法吗

**Comment by liangqi0518** [comment]
试试点击的时候弹出一下点中的字母，可以参照支付宝校园工作-更多-缴费大厅 
------------------ Original ------------------
