### ISSUE TITLE
Toast控件弹出的提示框 未以自身中心点 纵向居中

### ISSUE THREAD

**Issue by Linkinzoo** [ant-design/ant-design-mobile#1389]
### What problem does this feature solve?
Toast控件弹出的提示框 纵向位置不居中，用户不能调整其位置。

### What does the proposed API look like?
提供x,y参数来自行控制提示框的位置。

**Comment by paranoidjk** [comment]
目前是 flex 实现的水平垂直居中。

能否提供可复现的 demo ？

**Comment by Linkinzoo** [comment]
Demo from codepen:  https://codepen.io/LinkinZoo/pen/EmJmeL
附图：  http://chuantu.biz/t5/95/1495871971x2890174351.png
现象：现在是以弹窗顶部的像素点为基准，水平垂直居中的；
期待：让弹窗以其整体的中心点为基准，水平垂直居中；或提供API让用户自行调整。

**Comment by paranoidjk** [comment]
https://github.com/react-component/notification/commit/9fe383d4d6b8c5f18d2a794cf4e9cd11ccd1f0bb
