### ISSUE TITLE
高清方案设置在大屏幕上显示很小

### ISSUE THREAD

**Issue by Sean-Snow** [ant-design/ant-design-mobile#1390]
### What problem does this feature solve?
在iphone6SP 和大部分安卓手机显示都非常小，只有在iphone6上面显示

### What does the proposed API look like?
提供兼容的配置参数

**Comment by Sean-Snow** [comment]
![Uploading 6.png…](iPhone6 正常)

![Uploading android.png…]()

**Comment by paranoidjk** [comment]
给出你的 demo.

我们业务中广泛使用，没有问题，请仔细看文档和官方 demo.
