### ISSUE TITLE
RefreshControl for Popup SearchBar (focus not working)

### ISSUE THREAD

**Issue by yarnball** [ant-design/ant-design-mobile#1392]
### Version
1.1.3

### Environment
Browser

### Reproduction link
[https://github.com/yarnball/antd-mobile-create-react-app](https://github.com/yarnball/antd-mobile-create-react-app)

### Steps to reproduce
1. Slide down to see search bar appear (Popup)
2. Search bar will appear but not be auto focused

### What is expected?
1. The Search bar should auto focus as the state is set to true

### What is actually happening?
1. The setState focused should auto focus in SearchBar the when onRefresh occurs

---

**Comment by yarnball** [comment]
I just realised that the Div `am-refresh-control-ptr am-refresh-control-active am-refresh-control-loading` stays active even after the refresh. It change to `am-refresh-control-ptr` once the  refresh has complete- no?

**Comment by paranoidjk** [comment]
@yarnball If there is no problem, please close this issue by yourself.
