### ISSUE TITLE
建议Picker增加取消时的事件处理

### ISSUE THREAD

**Issue by Superman-wc** [ant-design/ant-design-mobile#1394]
### What problem does this feature solve?
我的版本：
antd-mobile   version": "0.9.17"

Picker可以设置取消选中的文案 dismissText
希望增加点击的事件处理 
同样点击okText 的时候也可以处理

### What does the proposed API look like?
（e）=>{
     e.cancel ===true //点击了取消 false时为点击ok 
}

**Comment by Superman-wc** [comment]
其实可以实现了， dismissText可以传ReactElement的

**Comment by paranoidjk** [comment]
是支持的，文档没写，我完善下
```tsx
props.onOk

props.onDismiss
```

**Comment by androidwt** [comment]
picker在react native使用时,支不支持点击空白区域弹窗消失?  @paranoidjk

**Comment by 947110021** [comment]
antd-mobile 弹出框的取消和确认可以换成自定义的图标吗
