### ISSUE TITLE
babel-plugin-antd 设置问题

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#14]
设为此
```
{
 "plugins": [["antd", { style: "css", libraryName: "antd-mobile" }]]
}
```
报错：
![image](https://cloud.githubusercontent.com/assets/2011119/17288625/a8b97454-5808-11e6-95f6-7486a9bd7f07.png)

把设置中的 style: "css" 改为 style: true ，正确

**Comment by warmhug** [comment]
@sorrycc @yiminghe

**Comment by warmhug** [comment]
没有依赖 antd-tools ，纯的 webpack + react 项目。（我们网站也没介绍必须依赖 antd-tools）
![image](https://cloud.githubusercontent.com/assets/2011119/17292897/60b24aca-581f-11e6-8b12-bcfef5d04f51.png)

**Comment by yiminghe** [comment]
重装 重新 npm run pub
