### ISSUE TITLE
关于 unable to resolve module @expo

### ISSUE THREAD

**Issue by xudaolong** [ant-design/ant-design-mobile#1403]
react-native 0.44.

各种安装都用不上了 这个 @expo ,前一个版本还是可以的

![image](https://cloud.githubusercontent.com/assets/9654838/26761543/e8457cd8-4963-11e7-9c5e-423fda1a4171.png)

**Comment by silentcloud** [comment]
@xudaolong 你是要在自己的项目里使用 antd-mobile 和 expo？

**Comment by xudaolong** [comment]
@silentcloud 不是的 我只是想用引入 antd-mobile 但是官方文档

`https://mobile.ant.design/docs/react/use-with-create-react-app-cn`

```
{
  "presets": ["babel-preset-expo"],
  "plugins": [["import", { "libraryName": "antd-mobile" }]],
  "env": {
    ...
  }
}

```

为何要引入 expo???

**Comment by silentcloud** [comment]
@xudaolong 你贴的这个文档地址是配合 `create-react-native-app` 工具使用的文档， 如果你仅仅是集成 antd-mobile，看这里 https://mobile.ant.design/docs/react/introduce#React-Native-usage
