### ISSUE TITLE
关于 Accordion.Panel 不能设置 style

### ISSUE THREAD

**Issue by xudaolong** [ant-design/ant-design-mobile#1407]
- rn 0.44
- antd-mobile 1.2.0

![image](https://cloud.githubusercontent.com/assets/9654838/26769868/e5c00c7c-49e4-11e7-94e9-fea6e3738726.png)

![image](https://cloud.githubusercontent.com/assets/9654838/26769874/f01cfe14-49e4-11e7-8ed9-475a4138d077.png)

- root.color 确认有值

**Comment by silentcloud** [comment]
下一个版本修复
