### ISSUE TITLE
navbar组件和picker组件一起使用的时候，在移动端浏览器中，picker的modal显示不出来，使用官方的例子

### ISSUE THREAD

**Issue by andy1028** [ant-design/ant-design-mobile#1409]
### Version
1.2.0

### Environment
移动端浏览器，Safari，qq浏览器

### Reproduction link
[http://www.demo.com/暂时没有](http://www.demo.com/暂时没有)

### Steps to reproduce
将官方的  navbar 和 picker 放在一起使用

### What is expected?
picker正常工作

### What is actually happening?
移动端无法正常工作，通过远程调试器查看，picker的dom已经被创建，但是就是没有显示出来

---
pc端模拟器一切正常

**Comment by paranoidjk** [comment]
close for no response.
