### ISSUE TITLE
Unable to resolve path to module 'antd-mobile'  import/no-unresolved

### ISSUE THREAD

**Issue by dancinglone** [ant-design/ant-design-mobile#141]
#### 本地环境
windows 10
cmd

- antd-mobile 版本： v0.7.8
- 操作系统及其版本： window 10
- 浏览器及其版本： chrome最新

#### 你做了什么？
1. 用了这个脚手架：https://github.com/coryhouse/react-slingshot
2. 然后安装了antd mobile, 安装babel-plugin-antd，
3. 修改项目根目录的   C:\Users\DCL\Desktop\reactslingshot-ppfix\.babelrc
```
 {
  "presets": [
    "es2015",
    "react",
    "stage-1"
  ],
  "env": {
    "development": {
      "presets": [
        "react-hmre"
      ],
      "plugins": [
          ["antd", { "style": "css", "libraryName": "antd-mobile" }]
      ]
    },
    "production": {
      "plugins": [
        "transform-react-constant-elements",
        "transform-react-remove-prop-types",
        ["antd", { "style": "css", "libraryName": "antd-mobile" }]
      ]
    }
  }
}
```

4.引入antd mobile:

```
import React from 'react';
import { Button } from 'antd-mobile';
// import 'antd-mobile/lib/button/style';
// import Button from 'antd-mobile/lib/button';

class TestPage extends React.Component {
  render() {
    const {number_now} = this.props;

    return (
        <div>
            <input type="text" value={number_now}/>
            <input type="button" onClick={this.props.addNum} value={'666'}/>
            <input type="button" onClick={this.props.fetch_click} value={'666'}/>


            <Button>按钮</Button>


        </div>
    );
  }
}

```
export default TestPage;

结果就报错了：

```
C:\Users\DCL\Desktop\reactslingshot-ppfix\src\components\test_page.js (1/3)
  ✖   2:24  Unable to resolve path to module 'antd-mobile'  import/no-unresolved
```

但却跑起来了，按钮似乎看起来也是正常的，样式正常，按下效果也正常

**Comment by dancinglone** [comment]
求各位指教，项目有点急T_T

**Comment by warmhug** [comment]
@sorrycc @yiminghe 这个问题遇到过吗？

**Comment by yiminghe** [comment]
use https://github.com/ant-design/ant-design-mobile/issues/56

**Comment by afc163** [comment]
没有 main 文件。可以自行关掉这个 eslint 的规则。

**Comment by dancinglone** [comment]
什么main文件？

**Comment by dancinglone** [comment]
今天重新装一次，竟然发现了这样的问题：

ERROR in ./src/components/order/OrderIndex.js
Module not found: Error: Cannot resolve module 'antd-mobile/lib/button/style/css' in C:\Users\DCL\Documents\dcl\svn\ppfix_svn\ppfixer_webapp\src\components\order
 @ ./src/components/order/OrderIndex.js 7:11-54

ERROR in ./~/.0.7.8@antd-mobile/lib/button/index.js
Module not found: Error: Cannot resolve module 'react-native' in C:\Users\DCL\Documents\dcl\svn\ppfix_svn\ppfixer_webapp\node_modules\.0.7.8@antd-mobile\lib\button
 @ ./~/.0.7.8@antd-mobile/lib/button/index.js 28:19-42

**Comment by dancinglone** [comment]
为什么会报RN的错误？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/issues/141#issuecomment-241944506

**Comment by dancinglone** [comment]
发现去掉webpack中的一个resolve就好了。。。
 resolve: {
    extensions: ['', '.js', '.jsx']
  },
不理解

**Comment by dancinglone** [comment]
谢谢

**Comment by dancinglone** [comment]
略懂了

**Comment by dancinglone** [comment]
贴出来方便大家:
https://github.com/ant-design/ant-design-mobile/issues/66

**Comment by chengky** [comment]
.eslintrc 中rules加上：
"import/no-unresolved": 0,

不知道还有什么好办法

**Comment by chengky** [comment]
是babel-plugin-import的锅，和antd-mobile无关
https://github.com/ant-design/babel-plugin-import/issues/77

**Comment by benjycui** [comment]
antd-mobile 的 style 目录与 antd 的不一样。。

antd-mobile
```bash
    └── style
        ├── css.web.js // here
        ├── index.css
        ├── index.less
        ├── index.web.d.ts
        └── index.web.js
```

antd
```bash
    ├── style
    │   ├── css.js
    │   ├── index.css
    │   ├── index.d.ts
    │   ├── index.js
    │   └── index.less
```

也就是说着类文件 `'antd-mobile/lib/button/style/css'` 的确是没有的。

**Comment by benjycui** [comment]
cc @warmhug @sorrycc

**Comment by sorrycc** [comment]
之前能运行，说明目录结构没问题，我看了是这样的，比如 `button`：

```bash
$ tree
.
├── PropsType.d.ts
├── PropsType.js
├── index.d.ts
├── index.js
├── index.web.d.ts
├── index.web.js
└── style
    ├── css.web.js
    ├── index.css
    ├── index.less
    ├── index.web.d.ts
    └── index.web.js

1 directory, 11 files
```

**Comment by warmhug** [comment]
什么时候加了 css.web.js 这个文件了？ @yiminghe

**Comment by yiminghe** [comment]
index.js css.js

index.web.js css.web.js
