### ISSUE TITLE
官网“在 create-react(-native)-app 中使用”的缺失及错误

### ISSUE THREAD

**Issue by roytan883** [ant-design/ant-design-mobile#1412]
[在 create-react(-native)-app 中使用](https://mobile.ant.design/docs/react/use-with-create-react-app-cn)
中有些没有写对

1，按照官网那样配置完svg会不显示，原因是：除了配置`svg-sprite-loader`还需要在`file-loader`中排除svg，
应该是这样才对：
```
 exclude: [
        ...
        /\.less$/,
        /\.svg$/,
        ...
      ]
```

2，文档没有写依赖库的安装
`yarn add --dev babel-plugin-import svg-sprite-loader@0.3.1 less less-loader postcss-pxtorem`

3，需要在webpack.config.dev.js中添加`const pxtorem = require('postcss-pxtorem');`

**最后，官网文档根本跑不通，但是issue中的很多官方回答都是查看官网。。。。。。死循环了**

**Comment by silentcloud** [comment]
@roytan883 欢迎提供 pr

**Comment by afc163** [comment]
？

**Comment by silentcloud** [comment]
@afc163 https://github.com/ant-design/ant-design-mobile/issues/1413 同样的 issue

**Comment by afc163** [comment]
关的时候要说明一下。
