### ISSUE TITLE
react-native components need more demos

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design-mobile#1414]
作为一名新人刚刚入坑 react-native，在看贵司的 Carousel 组件时，发现虽然在文档处表明了 web 和 rn only，但是给的 demo 却仍然使用了 web only 的属性，希望对 rn 能有更多的关爱，能给出更多的 rn demos ！

**Comment by silentcloud** [comment]
@RifeWang 请给出具体属性名

另外你可能弄错 rn 对应的 demo 代码了，官网 demo 只展示了 web 的 demo，rn 的 demo 在仓库对应 demo 下面的 basic.tsx 里

**Comment by paranoidjk** [comment]
@silentcloud 在 develope.md 里给一下 web 和 rn 源码的链接吧，这个好像被问挺多次了。

**Comment by silentcloud** [comment]
好
