### ISSUE TITLE
react native need more demos

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design-mobile#1415]
作为一名新人刚刚入坑 react-native，在看贵司的 Carousel 组件时，发现虽然在文档处表明了 web 和 rn only，但是给的 demo 却仍然使用了 web only 的属性，希望对 rn 能有更多的关爱，能给出更多的 rn demos ！

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1414
