### ISSUE TITLE
react native components need more demos

### ISSUE THREAD

**Issue by RifeWang** [ant-design/ant-design-mobile#1416]
### What problem does this feature solve?
作为一名新人刚刚入坑 react-native，在看贵司的 Carousel 组件时，发现虽然在文档处表明了 web 和 rn only，但是给的 demo 却仍然使用了 web only 的属性，希望对 rn 能有更多的关爱，能给出更多的 rn demos ！

### What does the proposed API look like?
对 web 和 react-native 有不同的 demo

**Comment by RifeWang** [comment]
首页 README 的 react native demo 很好，请问方便提供源码吗

**Comment by silentcloud** [comment]
@RifeWang 请给出具体属性名

另外你可能弄错 rn 对应的 demo 代码了，官网 demo 只展示了 web 的 demo，rn 的 demo 在仓库对应 demo 下面的 basic.tsx 里

> 首页 README 的 react native demo 很好，请问方便提供源码吗

在仓库里有：https://github.com/ant-design/ant-design-mobile/tree/master/rn-kitchen-sink

**Comment by RifeWang** [comment]
@silentcloud thanks ， I got it.
