### ISSUE TITLE
TabBar的bug

### ISSUE THREAD

**Issue by bucaixiaot** [ant-design/ant-design-mobile#1417]
在TabBar的选项卡中任何位置定义的onclick事件，不起作用，只要点击TabBar的四个切换按钮，onclick事件就会触发，不管onclick事件定义在TabBar选卡的任何字组件
这么大bug

**Comment by silentcloud** [comment]
你的环境下 https://mobile.ant.design/kitchen-sink/components/tab-bar 官方 demo 例子正常么？官方例子也是有 onClick 的
