### ISSUE TITLE
Popup  可否添加自定义遮罩等样式

### ISSUE THREAD

**Issue by margin-0** [ant-design/ant-design-mobile#1420]

**Comment by margin-0** [comment]
##### Functional requirements, the style of the component is global after packaging, and if the styles are different, you may want to add an on-demand custom style.

![Uploading 2A12519B-1999-4063-9CF3-1E3F853EB8EE.png…]()
##### There is such a problem after packaging, style modification is somewhat disturbing, so ask for help

**Comment by warmhug** [comment]
Currently, you can set `maskProps={{ className: 'am-popup-mask yourCls' }}`

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/search?utf8=%E2%9C%93&q=Popup&type=Issues

too many issue about popup custom style 

@warmhug api doc or demo need to be improved

**Comment by margin-0** [comment]
Yes, thank you

**Comment by margin-0** [comment]
##### Hello, found in the popup inside plus Maskprops after the click Mask can not close the popup, try to remove Maskprops will be able to see the API down on display popup and did not add Maskprops, can confirm whether it is because of the addition of the Maskprops after the click Mask can not be closed
```js
Popup.show(<ThemeChoose themeDatas={ themeDatas } handleThemeChange={ handleThemeChange } />, {
        transitionName: 'test1Animation',
        maskProps:      { className: 'am-popup-mask myselfam-popup-mask' },// Not when you add this.
      })
```js

**Comment by margin-0** [comment]
Hello, found in the popup inside plus Maskprops after the click Mask can not close the popup, try to remove Maskprops will be able to see the API down on display popup and did not add Maskprops, can confirm whether it is because of the addition of the Maskprops after the click Mask can not be closed
```js
Popup.show(<ThemeChoose themeDatas={ themeDatas } handleThemeChange={ handleThemeChange } />, {
        transitionName: 'test1Animation',
        maskProps:      { className: 'am-popup-mask myselfam-popup-mask' },// Not when you add this.
      })

```
