### ISSUE TITLE
Accordion组件demo例子报错

### ISSUE THREAD

**Issue by zhangkg** [ant-design/ant-design-mobile#1422]
console.error: "fontFamily 'anticon' is not a system font and has not been loaded through Exponent.Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Exponent.Font.loadAsync."

newConsoleFunc
    hashAssetFiles:49354:21
error
    hashAssetFiles:42367:16
processFontFamily
    hashAssetFiles:50759:22
diffProperties
    hashAssetFiles:13678:92
diffProperties
    hashAssetFiles:13685:41
mountComponent
    hashAssetFiles:28476:59
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountChildren
    hashAssetFiles:28647:56
initializeChildren
    hashAssetFiles:28423:41
mountComponent
    hashAssetFiles:28483:28
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountChildren
    hashAssetFiles:28647:56
initializeChildren
    hashAssetFiles:28423:41
mountComponent
    hashAssetFiles:28483:28
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountChildren
    hashAssetFiles:28647:56
initializeChildren
    hashAssetFiles:28423:41
mountComponent
    hashAssetFiles:28483:28
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountChildren
    hashAssetFiles:28647:56
initializeChildren
    hashAssetFiles:28423:41
mountComponent
    hashAssetFiles:28483:28
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountChildren
    hashAssetFiles:28647:56
initializeChildren
    hashAssetFiles:28423:41
mountComponent
    hashAssetFiles:28483:28
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountChildren
    hashAssetFiles:28647:56
initializeChildren
    hashAssetFiles:28423:41
mountComponent
    hashAssetFiles:28483:28
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountChildren
    hashAssetFiles:28647:56
initializeChildren
    hashAssetFiles:28423:41
mountComponent
    hashAssetFiles:28483:28
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountChildren
    hashAssetFiles:28647:56
initializeChildren
    hashAssetFiles:28423:41
mountComponent
    hashAssetFiles:28483:28
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountChildren
    hashAssetFiles:28647:56
initializeChildren
    hashAssetFiles:28423:41
mountComponent
    hashAssetFiles:28483:28
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountChildren
    hashAssetFiles:28647:56
initializeChildren
    hashAssetFiles:28423:41
mountComponent
    hashAssetFiles:28483:28
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
performInitialMount
    hashAssetFiles:25560:48
mountComponent
    hashAssetFiles:25464:40
mountComponent
    hashAssetFiles:24557:49
mountComponentIntoNode
    hashAssetFiles:22360:46
perform
    hashAssetFiles:25130:24
batchedMountComponentIntoNode
    hashAssetFiles:22367:22
perform
    hashAssetFiles:25130:24
renderComponent
    hashAssetFiles:22414:32
renderApplication
    hashAssetFiles:47295:21
runApplication
    hashAssetFiles:47124:26
__callFunction
    hashAssetFiles:3516:47
<unknown>
    hashAssetFiles:3374:29
__guard
    hashAssetFiles:3488:11
callFunctionReturnFlushedQueue
    hashAssetFiles:3373:19

**Comment by silentcloud** [comment]
你所指的是哪里的demo的报错? 该仓库？ 该仓库没用到  expo；

> If this is a custom font, be sure to load it with Exponent.Font.loadAsync.

@zhangkg   报错提示的很明显了，没加载自定义字体
