### ISSUE TITLE
scroll bar exception of autoHeight textareaItem on textarea focused or blurred

### ISSUE THREAD

**Issue by AidanDai** [ant-design/ant-design-mobile#1423]
### Version
1.2.0

### Environment
test env: ubuntu 16.04 １、chrome Version 57.0.2950.4 (正式版本) dev （64 位）　２、Firefox 53.0.3 (64 位) 

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/textarea-item?lang=zh-CN#textarea-item-demo-0](https://mobile.ant.design/kitchen-sink/components/textarea-item?lang=zh-CN#textarea-item-demo-0)

### Steps to reproduce
# test env

used autoHeight textareaItem component

## chrome Version 57.0.2950.4 (正式版本) dev （64 位）

- scroll
- textarea focused or blurred
- scroll bar exception

## Firefox 53.0.3 (64 位) 

- scroll
- textarea focused or blurred
- nomal

# My analysis

```javascript
// https://github.com/ant-design/ant-design-mobile/blob/master/components/textarea-item/index.web.tsx
// line 104
onBlur = (e) => {
    // this.debounceTimeout = setTimeout(() => {
    //   this.setState({
    //     focus: false,
    //   });
    // }, 100);
    // if (!('focused' in this.props)) {
    //   this.setState({
    //     focused: false,
    //   });
    // }
    const value = e.target.value;
    if (this.props.onBlur) {
      this.props.onBlur(value);
    }
  }

  onFocus = (e) => {
    // if (this.debounceTimeout) {
    //   clearTimeout(this.debounceTimeout);
    //   this.debounceTimeout = null;
    // }
    // if (!('focused' in this.props)) {
    //   this.setState({
    //     focused: true,
    //   });
    // }

    // this.setState({
    //   focus: true,
    // });
    const value = e.target.value;
    if (this.props.onFocus) {
      this.props.onFocus(value);
    }

    if (document.activeElement.tagName.toLowerCase() === 'textarea') {
      this.scrollIntoViewTimeout = setTimeout(() => {
        try {
          (document.activeElement as any).scrollIntoViewIfNeeded();
        } catch (e) { }
      }, 100);
    }
  }
```

textareaitem component rerender can cause scroll bar exception of autoHeight textareaItem on textarea focused or blurred; it is ok when stop it rerender. like above

what is why textareaItem had focus and focused state?

should we use props to control Element.scrollIntoViewIfNeeded()?
[https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded)

### What is expected?
fixed

### What is actually happening?
I don't know, but I hope someone to pay attention to it.

**Comment by paranoidjk** [comment]
@AidanDai 

Since antd-mobile is mobile ui components, can you confirm does it work fine in mobile browser？

The pc browser problems is low priority.

**Comment by AidanDai** [comment]
@paranoidjk 

ok, I will test in mobile.

but  I am concern about what is why?

**Comment by paranoidjk** [comment]
@AidanDai PC browser issue is very low priority, since antd-mobile is focus on mobile.

**Comment by paranoidjk** [comment]
close for no response.
