### ISSUE TITLE
同一个页面有多个ajax请求

### ISSUE THREAD

**Issue by FrankFei** [ant-design/ant-design-mobile#1424]
### Version
1.2.0

### Environment
chrome

### Reproduction link
[http://www.chuang-cai.com:8086/](http://www.chuang-cai.com:8086/)

### Steps to reproduce
重现链接中有2个ajax请求，一个是获取Banner的数据，一个是获取九功格的数据，

### What is expected?
Banner的数据和九功格的数据都要显示

### What is actually happening?
在很多情况下，Banner的数据和九功格的数据只有其一显示

**Comment by silentcloud** [comment]
试了 N 次都没能重现 

![image](https://user-images.githubusercontent.com/1698185/26858750-baedefb4-4b65-11e7-81d0-0434d9042421.png)

如果不是组件问题的话，请排查你自己的代码，组件跟 ajax 没关系。

这个问题需要你自己排查，这里关掉了
