### ISSUE TITLE
[ListView with RefreshControl] Get Warning: Uncaught Error: Stateless function components cannot have refs.

### ISSUE THREAD

**Issue by Princess310** [ant-design/ant-design-mobile#1426]
### Version
1.2.0

### Environment
MacBook Pro (15-inch, 2016)

### Reproduction link
[https://github.com/Princess310/antd-demo/blob/master/app/containers/Communicate/index.js#L84](https://github.com/Princess310/antd-demo/blob/master/app/containers/Communicate/index.js#L84)

### Steps (The github link is just for click event demo)
1. Just add the ListView component for page.
2.When I wanted to add some click event in the page(e.g. click the filter tag for fetching search data), It get warnining info: 

invariant.js:44 Uncaught Error: Stateless function components cannot have refs.

warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Notification component.

Notification.js?aa35:199 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node

3.Then, I remove the RefreshControl, the warning info disappeared.(But I found it triggered onEndReached event before I scroll list in the ListView)

### What is expected?
1. I think click event should not get warning things with RefreshControl.
2. I think click event in the page should not trigger the onEndReached if I don't scroll the list.

### What is actually happening?
Just happened what I said for reproduce...

---
中文描述 

1.经常会有页面上面有一些筛选的Tag来请求接口过滤list数据，但是当我在页面上触发点击事件去请求的时候，就会报错，有可能还会出现无限请求的问题。但是去除来refreshcontrol的话，就不会报错。

2.假如我没有滚动过ListView，我在页面上触发点击事件去请求list数据，发现会请求2次，因为触发了onEndReached事件，如果滚动过ListView再去点击请求的话，就不会出现这个问题。

1.1.3和1.2都会有这2个问题，今天才升级的。

**Comment by cncolder** [comment]
ListView 首页渲染就会触发 onEndReached 这个问题一直都存在，我的方法是通过判断 onEndReached 参数，有参数代表是滚动触发的，没参数就是首次渲染触发的。

**Comment by paranoidjk** [comment]
@cncolder 首次渲染就算没到屏幕底部也会触发 onEndReached 吗？ 看起来是 Bug，尝试修复下？

**Comment by warmhug** [comment]
onEndReached 问题 @cncolder 说的对，就是这么做的，这个行为跟 RN 的一样。

你的 demo 在 npm start 后，没有数据？demo 怎么完整启动起来？
我这里新做个 demo 试着重现下

**Comment by Princess310** [comment]
@warmhug 嗯，demo得登录账号才有数据...你做个demo看下，有refreshcontrol的listview，只要页面上加一个点击事件去请求数据，就会报错。我现在下拉和加载 先暂时不用listview

**Comment by warmhug** [comment]
@Princess310  已按你使用方式更新 demo 了，但没发现问题，这里都是 mock 数据，你拉下来跑跑看看？或者提个能重现你问题的 pr 最好。 https://github.com/ant-design/antd-mobile-samples/tree/master/web-webpack

**Comment by Princess310** [comment]
@warmhug 我找到报错的原因了， 你把你的代码里面，Button的点击事件改成onRefresh事件(因为页面上可能有筛选的tag，来刷新数据)，然后会发现onRefresh事件触发了2次。所以异步处理的时候会直接发出2次请求，导致报错。但demo 里面的componentWillReceiveProps判断貌似不起作用

**Comment by Princess310** [comment]
貌似就需要把调用方法分开了，页面上的点击事件不能再调用onRefresh的方法了。

**Comment by warmhug** [comment]
没太明白，你说的这个问题，那你是有解决办法了吧？

**Comment by Princess310** [comment]
原因大概就是在state或者redux的props传入新的refreshing状态的时候(比如请求第一页设置为true)，这个时候refreshcontrol会去再次调用它的onRefresh事件

**Comment by warmhug** [comment]
@Princess310 看新的写法 https://github.com/ant-design/antd-mobile-samples/commit/25ff346547c3fb61a85d9299219532135e0f8075  ，应该能解决你的问题。
我也更新下官方 demo 这个需求还是很常见的。

**Comment by Princess310** [comment]
@warmhug 嗯，好的。

**Comment by paranoidjk** [comment]
@warmhug  is this problem solved? If so, close issue in commit.

**Comment by warmhug** [comment]
@Princess310
