### ISSUE TITLE
Menu组件的两个bug

### ISSUE THREAD

**Issue by DavidSuns** [ant-design/ant-design-mobile#1427]
### Version
1.2.0

### Environment
mac chrome

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/c8afa086](https://riddle.alibaba-inc.com/riddles/c8afa086)

### Steps to reproduce
1. 不同一级菜单下的二级菜单value相同。
2. menu 的value值包含重复的二级value。

### What is expected?
1. 二级菜单的value值如果相同，如果一级父类不同，则相互不受影响。
2. 选中一个选项后，之前另一个一级菜单中的二级菜单取消选中。

### What is actually happening?
1. 二级菜单的value值如果相同，则menu的value值会影响所有值相同的value二级菜单的选中。
2. 选中一个选项后，之前另一个一级菜单中的二级菜单没有取消选中，还是原来的状态。

**Comment by pingan1927** [comment]
@DavidSuns 你来修复提PR吧，我来review

**Comment by paranoidjk** [comment]
@pingan1927 

和 @DavidSuns  是一个团队的吗？ 可以加为 collaborator。

另外确认的 Bug 评估下优先级，打上 label。

**Comment by pingan1927** [comment]
一个团队的

**Comment by paranoidjk** [comment]
@DavidSuns 

>  二级菜单的value值如果相同，如果一级父类不同，则相互不受影响。
选中一个选项后，之前另一个一级菜单中的二级菜单取消选中。
What is actually happening?

> 二级菜单的value值如果相同，则menu的value值会影响所有值相同的value二级菜单的选中。
选中一个选项后，之前另一个一级菜单中的二级菜单没有取消选中，还是原来的状态。

这几个描述真心没看懂。 riddle 上的例子我测试没发现有什么问题？不同的二级菜单下，就算 value 相同，选中状态应该也是独立的，这是我理解的 `正确状态`， 不知道你描述的是什么意思？

**Comment by DavidSuns** [comment]
@paranoidjk ，不同的二级菜单下，就算 value 相同，选中状态应该也是独立的，这是我理解的 正确状态，这就是我描述的意思

**Comment by paranoidjk** [comment]
对，那我看你给的riddle例子是正常的？

**Comment by DavidSuns** [comment]
不正常，在同一时刻，菜单应该只有一个选中值。
例子当中：
1. 初始化状态下， food， supermarket的二级菜单，均有元素被选中。
2. 在选中supermarket二级菜单中其它选项的情况下，切到food查看二级菜单，hot pot 选项仍然被选中

**Comment by paranoidjk** [comment]
@DavidSuns ok, 理解了。 👍
