### ISSUE TITLE
Popup does not close after adding Maskprops to the mask.

### ISSUE THREAD

**Issue by margin-0** [ant-design/ant-design-mobile#1428]
### Version
1.2.0

### Environment
In the browser can be

### Reproduction link
[测试demo](https://github.com/margin-0/Project-Testing/blob/master/menpiao/components/app.js)

### Steps to reproduce
Click to select the theme, at this time nothing choice, click the mask can not be closed

### What is expected?
Click the Mask to close

### What is actually happening?
Click Mask cannot close to close

---
Hello, found in the popup inside plus Maskprops after the click Mask can not close the popup, try to remove Maskprops will be able to see the API down on display popup and did not add Maskprops, can confirm whether it is because of the addition of the Maskprops after the click Mask can not be closed
```js
Popup.show(<ThemeChoose themeDatas={ themeDatas } handleThemeChange={ handleThemeChange } />, {
        transitionName: 'test1Animation',
        maskProps:      { className: 'am-popup-mask myselfam-popup-mask' },// Not when you add this.
      })

```

**Comment by warmhug** [comment]
最好在一个相关 issue 里提问，新开了就关联下老的 issue #1420

**Comment by warmhug** [comment]
等明天发 patch 版本

**Comment by margin-0** [comment]
好的，知道了

**Comment by margin-0** [comment]
#### 您好，onMaskClose 是在遮罩层关闭的时候的回调，但是我在点击出来的时候就触发了，这是为什么呢？然后点击遮罩并没有执行这个回调函数，请问是为什么？
```js
   Popup.show(<ThemeChoose themeDatas={ themeDatas } handleThemeChange={ handleThemeChange } />, {
        transitionName: 'test1Animation',
        maskProps:      { className: 'am-popup-mask myselfam-popup-mask' },
        onMaskClose:    handleMarkChange(3, false), // 这个是我想在点击蒙版后关闭Popup执行的事件函数
      })
      handleMarkChange(0, true)
```

**Comment by paranoidjk** [comment]
能否帮忙提供一个完整的codepen demo？

**Comment by margin-0** [comment]
##### 好的，这是  http://abchina.test.otosaas.com/menpiao/  

![2dfc7f1d-380a-4fda-8bb5-c0af2a7663dd](https://user-images.githubusercontent.com/23308724/27795337-477c7fcc-6038-11e7-9706-18d8c3ea5db8.png)

这个刚开始没有绑定会有个mask 删除这个DOM就可以点击了，谢谢
