### ISSUE TITLE
移动端设计指南中 Navigation > Pagination > Button with text and icon 样式 bug

### ISSUE THREAD

**Issue by littlemonkey19920204** [ant-design/ant-design-mobile#1429]
### Version
1.2.0

### Environment
OS X 10.11.2, Chrome 58

### Reproduction link
[https://mobile.ant.design/index-cn](https://mobile.ant.design/index-cn)

### Steps to reproduce
```
<div class="am-flexbox-item am-pagination-wrap-btn am-pagination-wrap-btn-prev">
<a role="button" class="am-button am-button-inline" aria-disabled="false">
<div class="arrow-align">
<svg class="am-icon am-icon-left am-icon-md">
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#left"></use>
</svg>
<!-- react-text: 31 -->上一步<!-- /react-text -->
</div>
</a>
</div>
```
Above-mentioned codes got style problem as the screenshot pasted below：

![image](https://user-images.githubusercontent.com/18202139/26867897-aac01caa-4b99-11e7-89b4-b15f510aedb6.png)

### What is expected?
- left arrow icon should be positioned in "Prev" button, and the icon should be center-align with the text
- right arrow icon got the same problem
- "Prev" button, pagination and "Next" button, these three elements should be center-aligned

### What is actually happening?
- arrow icon is not positioned in button, and not aligned with text
- "Prev" button, pagination and "Next" button are not aligned

**Comment by paranoidjk** [comment]
The official demo look fine at my browser https://mobile.ant.design/index-cn.

Please provide a reproducible demo.

**Comment by littlemonkey19920204** [comment]
> The official demo look fine at my browser https://mobile.ant.design/index-cn.
> 
> Please provide a reproducible demo.

@paranoidjk I visited the page with `Chrome 58`, and my desktop system is `OS X 10.11.2`. I just checked the page, still got layout problem with pagination as the screenshot shown below:

![image](https://user-images.githubusercontent.com/18202139/26909915-75ce2e0e-4c36-11e7-9ac8-83dc609e0426.png)

If the code looks fine, that might be a browser compatibility problem.

**Comment by warmhug** [comment]
![image](https://user-images.githubusercontent.com/2011119/26910542-2892b796-4c3a-11e7-9441-61de9298c08c.png)
选圈圈里选项就没问题了。
应该是页面宽度问题，scrollbar 占了宽度，需要修复。
