### ISSUE TITLE
feat: Flex[flex]

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design-mobile#143]
RN 的 `Flex` 是把用户配置的属性转为 `style` 再传给 `View`，但是没有 `flex` 属性，所以现在得这么写 `style={{ flex: 1 }}`，或者需要统一一下？

**Comment by silentcloud** [comment]
组件里可以这样写  <View style=[{ flex: 1 }, props.style]>

**Comment by benjycui** [comment]
现在是 Flex.Item 有 flex 属性，但是 Flex 没有，在嵌套 Flex 时这个属性还是要设置的。

**Comment by pingan1927** [comment]
@benjycui 了解。我修一下

**Comment by silentcloud** [comment]
@pingan1927 这个修了么，修了就 close了

**Comment by pingan1927** [comment]
给忘记了，先不关，我仔细看看

**Comment by warmhug** [comment]
看太久了，不用看了，关了。。。
