### ISSUE TITLE
Swipe Tabs issue.

### ISSUE THREAD

**Issue by ArtemSerga** [ant-design/ant-design-mobile#1430]
### Version
1.2.0

### Environment
Google Chrome v58.0.3029.83 on Android, any Google Chrome devTools mobile emulator (iPhone 5, 6, 6Plus, iPad, Galaxy S5...)

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/tabs?lang=en-US](https://mobile.ant.design/kitchen-sink/components/tabs?lang=en-US)

### Steps to reproduce
1. Open link https://mobile.ant.design/kitchen-sink/components/tabs?lang=en-US
2. Try to swipe tabs

### What is expected?
Tabs are swipable correctly.

### What is actually happening?
Tabs aren't swipable correctly. Looks like CSS issue.

---
It works correctly in Flame OS (Meizu) Browser v 6.3.105

**Comment by paranoidjk** [comment]
Can you give a screenshot or video?

Since i do not have Meizu mobile, i am not sure what your problem actually is ?

**Comment by ArtemSerga** [comment]
Hi @paranoidjk. Thanks for quick response!

Reproduced on Mac OS in Google Chrome (devTools, mobile view). 
Use link https://mobile.ant.design/kitchen-sink/components/tabs?lang=en-US
**The same result on Android in Google Chrome.**
http://www.youtube.com/watch?v=Ugshj2oZMZc

P.S. Works correctly on iPhone 5, Safari.

**Comment by paranoidjk** [comment]
@ArtemSerga Why close? Have your problem been fixed?

**Comment by ArtemSerga** [comment]
I found using tab's swipe action on WEB - is completely useless, because of ability to scroll window horizontally and vertically simultaneously.
So I completely stop using tabs (for WEB).
This issue still can be reproduced, but there is a lot of other more important issued related to tabs.

**Comment by paranoidjk** [comment]
Sorry, i just watched your screen recording.

There have been same issue, `tabs` should works fine except on chrome simulator or the latest version of android chrome browser. 

Please trace https://github.com/ant-design/ant-design-mobile/issues/741, we will fix this when we got time.

**Comment by ArtemSerga** [comment]
@paranoidjk  
I get it! Thanks!
