### ISSUE TITLE
Unable to resolve module `!svg-sprite

### ISSUE THREAD

**Issue by garyfoo** [ant-design/ant-design-mobile#1431]
### Version
1.2.0

### Environment
react-native version 0.44, iOS 10.3.2

### Reproduction link
[https://github.com/garyfoo/ant-mobile-demo/blob/master/App.js](https://github.com/garyfoo/ant-mobile-demo/blob/master/App.js)

### Steps to reproduce
1) create-react-native-app antm-demo
2) yarn add antd-mobile && yarn add babel-plugin-import --dev
3) Paste the following code in app.js
~~~~
<Button className="btn" loading>loading button</Button>
<Button className="btn" icon="check-circle-o">with icon</Button>
<Button className="btn" icon={require('!svg-sprite!./reload.svg')}>
~~~~

### What is expected?
Unable to resolve module `!svg-sprite!./reload.svg` from `/Users/garyfoo/Developer/antm-demo/App.js`: Module does not exist in the module map or in these directories:
  /Users/garyfoo/Developer/antm-demo/node_modules/!svg-sprite!.

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

ABI17_0_0RCTFatal
ABI17_0_0RCTSetFatalHandler
ABI17_0_0RCTSetFatalHandler
<redacted>
<redacted>
_dispatch_main_queue_callback_4CF
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
Exponent
<redacted>

### What is actually happening?
No idea. I suspect that it is not loading the SVG sprites in the antm module

---
Thanks alot for the hard work! I appreciate ant mobile alot! Would be great if you can help me resolve this  issue!

**Comment by paranoidjk** [comment]
react-native version of `Icon` component is not use svg, please see https://mobile.ant.design/components/icon#如何使用-(RN-版)

**Comment by paranoidjk** [comment]
by the way? can you read chinese? sorry about that our doc haven't finish translate to english yet

https://github.com/ant-design/ant-design-mobile/issues/329

**Comment by paranoidjk** [comment]
If you have problem with chinese doc, just let me know, I will start to translate Icon doc ASAP.

**Comment by garyfoo** [comment]
Hello! I'm able to read abit of chinese so I have followed the steps and fixed the issue. For some reason, the loading icons seem to be rotating really slowly though

If you have time, it'll be great if you can translate for the ones who don't speak chinese though ^^

Thank you so much!
