### ISSUE TITLE
the cross modal will show in IOS style after click OK in Android

### ISSUE THREAD

**Issue by changhui3067** [ant-design/ant-design-mobile#1433]
### Version
1.2.0

### Environment
android all version

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/modal?lang=en-US](https://mobile.ant.design/kitchen-sink/components/modal?lang=en-US)

### Steps to reproduce
1.open the link by chrome and trigger device toolbar
2.choose one android device
3.click the button names 'Modal对话框(自动检测平台)'
4.click the ok button in the modal

### What is expected?
the modal should closed immediately after clicked ok button

### What is actually happening?
the modal closed and then a IOS style modal shows for about 2 seconds and then disappear

---
I created an pull request to fix issue: https://github.com/ant-design/ant-design-mobile/pull/1432

**Comment by paranoidjk** [comment]
@changhui3067 sorry, I can not reproduce your problem, can you give more detail info? like a screenshot gif?

**Comment by paranoidjk** [comment]
<img src="https://zos.alipayobjects.com/rmsportal/MVLTnyltLFwueipmywlw.gif" width="600" height="400">

**Comment by changhui3067** [comment]
@paranoidjk please click the first button(names 'Modal对话框(自动检测平台)') in the basic section instead of the second button. 
this issue only reproducible when 'platform = cross' in Modal code.
