### ISSUE TITLE
range 组件，有警告

### ISSUE THREAD

**Issue by aibaiejoy** [ant-design/ant-design-mobile#1434]
### Version
1.2.0

### Environment
mac chrome

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/range?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/range?lang=zh-CN)

### Steps to reproduce
控制台有警告

### What is expected?
https://mobile.ant.design/kitchen-sink/components/range?lang=zh-CN

### What is actually happening?
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

**Comment by benjycui** [comment]
ref: https://github.com/react-component/slider/issues/258

但我这边没有重现，麻烦提供你的环境信息和必现步骤。

**Comment by paranoidjk** [comment]
Dulplicate, please trace at https://github.com/react-component/slider/issues/258#issuecomment-295555656
