### ISSUE TITLE
InputItem 当type="money"时 disabled={true}无效

### ISSUE THREAD

**Issue by chengky** [ant-design/ant-design-mobile#1437]
### Version
1.3.0

### Environment
antd-mobile 1.3.0,react 15.5.4 ,rc-form 1.3.1

### Reproduction link
[https://codepen.io/chengky/pen/MoyXzp](https://codepen.io/chengky/pen/MoyXzp)

### Steps to reproduce
点击输入框可以通过小键盘改变值

### What is expected?
InputItem 禁用

### What is actually happening?
InputItem 仍可编辑并能拉起小键盘

**Comment by pingan1927** [comment]
我这周修复

**Comment by itxuye** [comment]
@pingan1927 我这边好像editable也是有问题的。

**Comment by itxuye** [comment]
@pingan1927 我刚试了下editable={false} 是可以编辑的。应该也是有问题吧
