### ISSUE TITLE
Tabs 服务端渲染错误

### ISSUE THREAD

**Issue by perfmlin** [ant-design/ant-design-mobile#1440]
### Version
1.3.0

### Environment
服务端渲

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile](http://new-issue.ant.design/?repo=ant-design-mobile)

### Steps to reproduce
ReferenceError: window is not defined
    at Object.<anonymous> (node_modules\hammerjs\hammer.js:2643:4)

### What is expected?
ReferenceError: window is not defined
    at Object.<anonymous> (node_modules\hammerjs\hammer.js:2643:4)

### What is actually happening?
ReferenceError: window is not defined
    at Object.<anonymous> (node_modules\hammerjs\hammer.js:2643:4)

**Comment by paranoidjk** [comment]
@cncolder 有空帮忙看下吗？这里故意把原来ssr的兼容逻辑去掉了 https://github.com/react-component/react-hammerjs/blob/master/src/Hammer.js#L7

**Comment by cncolder** [comment]
@paranoidjk 我记得之前受影响的是 SwipeAction

**Comment by cncolder** [comment]
当初那段兼容代码是有必要的，不只是 Tabs， SwipeAction 等其他依赖 hammer 的组件都有相同的问题。

rc-hammerjs 是用 rc-tools 编译的，改成 `const Hammer = (typeof window !== 'undefined') ? require('hammerjs') : undefined;` 的话，混合使用 import 和 require 编译上有没有问题？

**Comment by paranoidjk** [comment]
你提pr吧

**Comment by paranoidjk** [comment]
Hammerjs加载的时候会自执行吗？如果不是可以尝试这样把hammerjs包一层

import RealHammer from ‘hammerjs’
const Hammer = typeof window === undefined ？undefined ：RealHammer；

export default Hammer；

**Comment by cncolder** [comment]
是 hammerjs 自己的问题，他们的文件结构是这样的：

```js
(function(window, document, exportName, undefined) {

})(window, document, 'Hammer');
```

rc-hammerjs 本身没问题，真正用到 hammerjs 是在 componentDidMount 之后。

**Comment by cncolder** [comment]
直接引入 [hammerjs/src/main](https://github.com/hammerjs/hammer.js/blob/master/src/main.js) 可行吗？

默认入口那个文件是 rollup 打包的，最外层包裹的函数是故意加上去的，意义不明。

**Comment by paranoidjk** [comment]
恩，hammerjs 的 main 是 umd 的, 他们又没对 window 做兼容。  https://unpkg.com/hammerjs@2.0.8/hammer.js

就是注释里的issue问题，看来官方是不打算解决了，https://github.com/react-component/react-hammerjs/blob/master/src/Hammer.js#L5

先按你这个修复吧 https://github.com/react-component/react-hammerjs/pull/6

**Comment by perfmlin** [comment]
nice thx
