### ISSUE TITLE
error TS2307: Cannot find module 'react-native'

### ISSUE THREAD

**Issue by ArtemSerga** [ant-design/ant-design-mobile#1444]
### Version
1.2.0

### Environment
Web project on TypeScript, antd-mobile >= 1.1.4-beta.0

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/pull/1280/files](https://github.com/ant-design/ant-design-mobile/pull/1280/files)

### Steps to reproduce
1. git clone https://github.com/ant-design/antd-mobile-samples.git
2. cd ./antd-mobile-samples/web-typescript
3. yarn
4. yarn upgrade antd-mobile@1.1.4-beta.0
5. yarn start 

### What is expected?
No TypeScript compile error

### What is actually happening?
TypeScript compile error

```
node_modules/antd-mobile/lib/baseType.d.ts(3,27): error TS2307: Cannot find module 'react-native'.
2:51:05 PM - Compilation complete. Watching for file changes.
```

---
This compile error starts from PR https://github.com/ant-design/ant-design-mobile/pull/1280/files

**Comment by paranoidjk** [comment]
This should be fixed in https://github.com/ant-design/ant-design-mobile/pull/1376

**Comment by adoji92** [comment]
![screenshot from 2018-05-06 00-39-33](https://user-images.githubusercontent.com/7765194/39664904-fc906d50-50c5-11e8-8b51-e12f1f859c40.png)

I got same error from modal props type
is it intended one? (= which means that i should install react-native package even if i use only for web?)

**Comment by adoji92** [comment]
my workaround:

1. `yarn add -D @types/react-native` // don't need react-native itself,
2. [killglobals](https://gist.github.com/rawrmaan/be47e71bd0df3f7493ead6cefd6b400c)
you can execute above script @ package.json > scripts > postintsall
