### ISSUE TITLE
Picker选择手速太快问题

### ISSUE THREAD

**Issue by czy0729** [ant-design/ant-design-mobile#1447]
### What problem does this feature solve?
用户在手机使用Picker的时候，很多时候不会去等完这个切换的动画 如：http://wx2.sinaimg.cn/mw690/715ed77dgy1fglravu3efg20ac0c20wn.gif
所以很多时候，根本不会触发onChange事件

### What does the proposed API look like?
我希望能切换的时候，马上到位。或者能不能给我一些改善的建议。

**Comment by paranoidjk** [comment]
see https://github.com/ant-design/ant-design-mobile/issues/918#issuecomment-296102502

**Comment by paranoidjk** [comment]
计划加一个 `onScroll: (value) => void` 的 API。

**Comment by zhang740** [comment]
`Picker` 无感知升级，`PickerView` 需要自己处理 `onScrollChange: (value) => void` 事件

**Comment by warmhug** [comment]
@zhang740 DatePicker / DatePickerView 也看下
