### ISSUE TITLE
Carousel 能不能提供和https://github.com/react-component/nuka-carousel一样的API？

### ISSUE THREAD

**Issue by xinconan** [ant-design/ant-design-mobile#1451]
### What problem does this feature solve?
在官网中，说更多参数可参考: https://github.com/react-component/nuka-carousel (web only)，然而很多方法并不通用，甚至是不一样的，我想要一个手动切换到不同slider的效果，官方的API只需要修改selectedIndex，然而这个切换很生硬，后面不得不直接使用 [nuka-carousel](https://github.com/react-component/nuka-carousel)，它提供了goToSlide的方法

### What does the proposed API look like?
希望是这样的：
```javascript
this.refs.carousel.goToSlide( slideIndex);
```

**Comment by paranoidjk** [comment]
这两者效果应该是一样的

https://github.com/react-component/nuka-carousel/blob/master/src/carousel.js#L155

**Comment by paranoidjk** [comment]
close for no response.

**Comment by zzh3319** [comment]
ant-mobile 轮播  如何跳转到指定位置    ?

**Comment by silentcloud** [comment]
@zzh3319  `selectedIndex `

**Comment by zzh3319** [comment]
@silentcloud 这个方法只能第一次render的时间 起作用  但是我是要render后的 在跳转到指定位置

需要像nuka-carousel的goToSlide这样的方法。

**Comment by silentcloud** [comment]
@zzh3319 通过 state 来改变 selectedIndex

**Comment by tonyerx** [comment]
selectedIndex doesn't work after once render

**Comment by tonyerx** [comment]
@silentcloud

**Comment by tonyerx** [comment]
1. 使用selectedIndex只能跳转一次 2. selectedIndex跳转的方式十分生硬，而不是通过滚动的方式切换。
对于上面这两个问题，请问有什么好的解决方法？

**Comment by warmhug** [comment]
> 使用selectedIndex只能跳转一次

能跳转多次的，没问题。

@tonyerx 新问题 新建 issue 提问
