### ISSUE TITLE
When the click of the Bullet window appears, press the phone physical return key still exists

### ISSUE THREAD

**Issue by margin-0** [ant-design/ant-design-mobile#1452]
### What problem does this feature solve?
On a page when the click of the window appears, such as Modal inside the alert, then press the phone physical return key back to the previous page but the window still exists

### What does the proposed API look like?
I wonder if there is a way in the global, when I press the physical return key to call within the component destruction cycle to prevent the return to the previous page still exist

![a33101f2-2505-48d6-95ae-4c25cec82f49](https://user-images.githubusercontent.com/23308724/27177058-b2eb8248-51f7-11e7-9265-58575de7ed0d.png)

![f9b60284-3020-4875-baa4-33d0ebaac1b3](https://user-images.githubusercontent.com/23308724/27176704-2bd2a6c0-51f6-11e7-8a3f-c42165fa05a2.png)

**Comment by paranoidjk** [comment]
- 你是单页应用，后退是 hash 路由 change ？ 不然不应该切换了页面之后，modal 还保留
- 物理的 back 键事件，你可以尝试看看 https://stackoverflow.com/questions/18997793/javascript-backbutton-event-listener-overrides-the-android-device-back-button
- Modal 本身提供了 `close` 方法，你可以按需调用。

**Comment by margin-0** [comment]
+  是路由切换的，在componentWillUnmount 这个周期里面做关闭一些弹窗的
+  好的
+  已经做了尝试

**Comment by paranoidjk** [comment]
所以你的意思是我们提供的close api不生效吗？

请提供一个可复现的demo，谢谢。

**Comment by margin-0** [comment]
您好今天早上使用另外的方法，close生效
