### ISSUE TITLE
Checkbox onChange或onClick改变选中状态后再修改其值时必须延时执行才能有效修改选中状态

### ISSUE THREAD

**Issue by chengky** [ant-design/ant-design-mobile#1453]
### Version
1.3.0

### Environment
antd-mobile 1.3.0,react 15.5.4 ,rc-form 1.3.1

### Reproduction link
[https://codepen.io/chengky/pen/RgoNBR](https://codepen.io/chengky/pen/RgoNBR)

### Steps to reproduce
```
点击“选项B”，能勾选；
点击“选项C”，勾选后很快变为非勾选状态(可见闪动)；
```

### What is expected?
```
点击“选项B”，最终变为非勾选状态
点击“选项C”，最终状态正确，是因为使用了setTimeout(,0)处理才得到正确状态。
```

### What is actually happening?
点击“选项B”，显示为已勾选，实际应变为非勾选，而且此时getFieldValue获取到的值也已经是非勾选

---
Checkbox能否增加一个阻止状态变更的方法？

**Comment by paranoidjk** [comment]
- 不知道我是否理解正确，你在A未选择的时候把B, C disable不行吗？ 
- 你的需求是在 onChange 里面把状态重置回去以达到不能选中的效果？那你的demo也写的太复杂了

建议写一个单纯的checkbox onchange demo，不要加上 rc-form 测试一下是否有问题

**Comment by chengky** [comment]
@paranoidjk 谢谢，你的理解没有问题。
单纯使用checkbox的defaultChecked,checked是可以的。好吧，特定场景下的问题，严格讲不是BUG。
