### ISSUE TITLE
Form表单集合的Demo里用到的 rc-form 模块找不到

### ISSUE THREAD

**Issue by small752** [ant-design/ant-design-mobile#146]
import { createForm } from 'rc-form';
LoginPage = createForm()(LoginPage);
#### 实际上的结果：

Module not found

**Comment by 214132049** [comment]
这个要自己安装  rc-form

**Comment by small752** [comment]
我能用ant design 的Form 吗， 引申一个问题是  ant design mobile 和 ant design 混杂一起用可以吗，这样好不好 ？？？

**Comment by 214132049** [comment]
我只用的mobile的  应该可以混用

**Comment by small752** [comment]
再问一下，怎么安装rc-form啊，我用npm 安装了不会用

**Comment by pingan1927** [comment]
`npm install rc-form --save`

文档参考这里：https://github.com/react-component/form，很强大

**Comment by silentcloud** [comment]
@small752 不推荐混合使用

**Comment by benjycui** [comment]
不考虑把 rc-form 集成进 antd-mobile 么？

**Comment by yiminghe** [comment]
close
