### ISSUE TITLE
Use the defaultChecked property of antd-mobile's CheckboxItem to report "Failed prop type: Invalid prop `defaultChecked` to `Checkbox`. supplied" error

### ISSUE THREAD

**Issue by HarryHuObject** [ant-design/ant-design-mobile#1464]
### Version
1.3.0

### Environment
web   chrome58

### Steps to reproduce

```
const CheckboxItem = Checkbox.CheckboxItem;
class Form extends React.Component{
render(){
return(
 <CheckboxItem
                            key="checked"
                            defaultChecked="true"
                            onChange={this.checkBoxChange}
                        />
）
}
}
export default createForm(Form);
```

### What is expected?
No warning

### What is actually happening?
warning.js:36 Warning: Failed prop type: Invalid prop `defaultChecked` supplied to `Checkbox`.
    in Checkbox (created by Checkbox)
    in Checkbox (created by CheckboxItem)
    in div (created by ListItem)
    in div (created by ListItem)
    in Touchable (created by ListItem)
    in ListItem (created by CheckboxItem)
    in CheckboxItem (created by Form)
    in div (created by List)
    in div (created by List)
    in List (created by Form)
    in div (created by List)
    in div (created by List)
    in List (created by Form)
    in div (created by Form)
    in Form (created by Form(Form))
    in Form(Form) (created by Demo)
    in div (created by Demo)
    in Demo (created by RouterContext)
    in div (created by Main)
    in Main (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by Index)
    in Index

**Comment by afc163** [comment]
```diff
- defaultChecked="true"
+ defaultChecked
```

or

```diff
- defaultChecked="true"
+ defaultChecked={true}
```
