### ISSUE TITLE
tab标签首次加载默认选中项没有正确显示选中状态

### ISSUE THREAD

**Issue by xiaoyanit** [ant-design/ant-design-mobile#1465]
### Version
1.3.0

### Environment
win7 Chrome  56.0.2924.87

### Reproduction link
[https://github.com/nowa-webpack/template-antdmobile/blob/master/proj/src/components/Form.jsx](https://github.com/nowa-webpack/template-antdmobile/blob/master/proj/src/components/Form.jsx)

### Steps to reproduce
import React from 'react';
import {createForm} from 'rc-form';
import moment from 'moment'; // moment.min ~= 48kb
import {district} from 'antd-mobile-demo-data';

import {
  Picker,
  Tabs,
  DatePicker,
  List,
  Checkbox,
  Button,
  Steps,
  NavBar,
  InputItem,
  WhiteSpace
} from 'antd-mobile';
import enUs from 'antd-mobile/lib/date-picker/locale/en_US';
import DrawerTest from './Drawer';
const CheckboxItem = Checkbox.CheckboxItem;
const TabPane = Tabs.TabPane;

function callback(key) {
  console.log('onChange', key);

 
}
function handleTabClick(key) {
  console.log('onTabClick', key);
}

// 如果不是使用 List.Item 作为 children
{/*
const CustomChildren = (props) => {
  return (
    <div
      onClick={props.onClick}
      style={{
      backgroundColor: '#fff',
      height: '0.9rem',
      lineHeight: '0.9rem',
      padding: '0 0.3rem'
    }}>
      {props.children}
      <span style={{
        float: 'right'
      }}>{props.extra}</span>
    </div>
  );
};
*/}
class Test extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      pickerValue: [],
      // pickerValue: ['340000', '340800', '340824'] dpValue: moment(),
      dpValue: null
    };
  }

  render() {
    const {getFieldProps} = this.props.form;
    const {pickerValue, dpValue} = this.state;
    return (

        <div>
          <Tabs defaultActiveKey="one" onChange={callback} onTabClick={handleTabClick}>
            <TabPane tab="选项卡一" key="one">
              <div
                style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                height: '5rem',
                backgroundColor: '#fff'
              }}>
                销售人员
              </div>
            </TabPane>
            <TabPane tab="选项卡二" key="two">
              <div
                style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                height: '5rem',
                backgroundColor: '#fff'
              }}>
               非销售人员
              </div>
            </TabPane>
            
          </Tabs>
          <WhiteSpace/>
        </div>

   
    );
  }
}

export default createForm()(Test);

### What is expected?
默认选中tab 1,tab2 状态未选中

### What is actually happening?
默认选中tab 1,tab2 状态都选中

---
重新步骤中的代码是在重现链接的代码上修改

**Comment by xiaoyanit** [comment]
OK , I use https://github.com/nowa-webpack/template-antdmobile/  source code and modify the /Form.jsx  as "Steps to reproduce" . Trouble is tab state is not  correct show . 
What is expected?    tab 1 should be active . tab 2 should not .
 What is actually happening? both of them is active state . 
I'm not know why it's there ?

[](https://github.com/xiaoyanit/antd-mobile/blob/master/%E6%96%B0%E5%BB%BA%E4%BD%8D%E5%9B%BE%E5%9B%BE%E5%83%8F.bmp)

**Comment by paranoidjk** [comment]
请先确认下在手机或chrome模拟器上是否有问题

**Comment by xiaoyanit** [comment]
@paranoidjk  已经试过了，是用的nowa-gui创建的项目，demo 的选项卡也是这样

**Comment by belief-cyf** [comment]
我也是这样的  坐等解决方案QAQ        
![image](https://user-images.githubusercontent.com/19991842/27281229-8cb3e588-551d-11e7-9881-a31f25e9da93.png)
![image](https://user-images.githubusercontent.com/19991842/27281244-a1e9e074-551d-11e7-8d7f-4d7ee46b2d37.png)

**Comment by xiaoyanit** [comment]
@belief-cyf 你用的是那个模板构建antdmobile 的，在添加InputItem的时候有报错么？
谢谢！

**Comment by belief-cyf** [comment]
你是指项目脚手架？   是我们自己搭的 ，开始是有报错  不过配置好了babel就好了。

**Comment by xiaoyanit** [comment]
@belief-cyf 能共享下脚手架么，我用官方的都有问题，会报错，已经提了issue ,目前没人回应呢。

**Comment by belief-cyf** [comment]
公司内的东西。。 共享不了
![image](https://user-images.githubusercontent.com/19991842/27313234-7c1dcc48-559f-11e7-8e83-12617f1d04b2.png) 我之前也报错 把.web.js排在.js前面就好了   你试下是不是这个问题   
![image](https://user-images.githubusercontent.com/19991842/27313264-98150aba-559f-11e7-9960-c815eb42bfb0.png)这是babel的配置    其他地方没什么特殊的地方

**Comment by belief-cyf** [comment]
我发现我从别的页面跳转进来的时候  tabs是正常的  但是我直接访问使用tabs的页面或者是在当前页面刷新的时候tabs显示就不正常了。

**Comment by xiaoyanit** [comment]
我用的是官网的nowa-GUI创建的antd-mobile ，我看其他实例也是正常的，但是去运行的时候就不行了。而且加入InputItem就无法编译通过了，挺郁闷的。我尝试用你的方法配置下，看是否会正常。

**Comment by belief-cyf** [comment]
我的项目是用webpack 构建的

**Comment by xiaoyanit** [comment]
我搜索个教程，也用webpack构建试下，官网反馈太慢了。

**Comment by belief-cyf** [comment]
这个问题没人回答了嘛？ @xiaoyanit  你解决了这个嘛？

**Comment by xiaoyanit** [comment]
@belief-cyf 貌似是没人解决呢，我看ant-mobile 官方的demo上tabs显示都是正常的，有可能是nowa-mobile脚手架代码的问题吧。尝试曲线救国，自己配置导入组件吧。我现在用salt ui的tabs组件替代。

**Comment by belief-cyf** [comment]
@xiaoyanit 我把官方代码clone进来 也还是有问题   我已经用css隐藏那个div   然后给活动的tabs className 加border-bottom 曲线救国了。。。

**Comment by paranoidjk** [comment]
@xiaoyanit @belief-cyf 官方 demo 无法复现，请提供你的代码库地址，我这边拉下来跑一下

**Comment by paranoidjk** [comment]
duplicate with https://github.com/ant-design/ant-design-mobile/issues/1046, please trace at https://github.com/ant-design/ant-design-mobile/issues/1046
