### ISSUE TITLE
When will react-native and react version be updated?

### ISSUE THREAD

**Issue by liuze692326532** [ant-design/ant-design-mobile#1466]
when I update react-native version to 0.45.1,the TabBar component is not working normal。

**Comment by silentcloud** [comment]
@liuze692326532 `react-native@0.45` needs `react@16.0.0-alpha.12`,  but now react@16 is alpha version, so we will update react and react-native after react@16.0 released

**Comment by paranoidjk** [comment]
```bash
ExceptionsManager.js:71 Warning: TouchableHighlight: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
```

**Comment by silentcloud** [comment]
@liuze692326532  `tab-bar` has been fixed in next version.

https://github.com/ant-design/ant-design-mobile/issues/1538

https://github.com/ant-design/ant-design-mobile/commit/30e0f608d9024c1185064ac0e2f481cb4e998324

**Comment by silentcloud** [comment]
已经在  https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo 测试了高版本的 react-native 兼容性，都已经 ok 了；

至于升级仓库 RN 版本，涉及很多对 react react-dom 的依赖，暂时先不用管了

这个 issue 先暂时关掉了，后期根据 react@16 的正式版情况再升级仓库
