### ISSUE TITLE
`Picker` with rc-form has waring

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#1467]
https://riddle.alibaba-inc.com/riddles/6aaf9c74

**Comment by warmhug** [comment]
ref https://github.com/react-component/m-cascader/blob/c18380199be09826078af90bf82a7e907215998a/src/Cascader.tsx#L91
 Picker 组件内部实现暂没支持 defaultValue ， rc-form 的 getFieldDecorator 方法自动设置 value 和 onChange，并提醒用户自己不要设置，所以不适合用到 Picker 组件上(PopupDatePicker 也不适合)。

**后续会去掉所有 demo 中的 rc-form 代码**，因为其体积大功能丰富、对移动端应用场景来说是大材小用，用户有需要可自己写或选其他轻量级表单验证库。 ref #1274

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/issues/3976

因为之前一直有用户使用了 `getFieldDecorator` 后，还给组件设置了 `value` 或者 `defaultValue`，这样代码运行会不符合预期，所以加了这个 warning。

只要把 Picker defaultProps 里面的 value 的默认值拿掉，然后在组件里面，需要用到 value 的地方写上默认值就可以了。

其实这个改动，也能保证 TypeScript 的那个 `strictNullCheck` 能通过。

**Comment by pingan1927** [comment]
@warmhug `rc-form`在B端的表单类业务里是必选

**Comment by paranoidjk** [comment]
@pingan1927 你的 riddle 我没看到有 warning？ 贴出 warning 内容看一下？

另外 `rc-form` 的功能在复杂表单是需要的，但在移动端体积太大。

@benjycui  
> 只要把 Picker defaultProps 里面的 value 的默认值拿掉，然后在组件里面，需要用到 value 的地方写上默认值就可以了。

这个是 anti-pattern 吧？ 默认值并不如 defaultProps 好维护。

**Comment by paranoidjk** [comment]
这个改动先不写到本周的 changelog 里，没理解改动的原因和意义。

**Comment by benjycui** [comment]
> 其实这个改动，也能保证 TypeScript 的那个 strictNullCheck 能通过。

@paranoidjk

**Comment by paranoidjk** [comment]
strictNullCheck 目前在 defaultProps 的场景都是有问题吧？ Typescript 类型推断不认 defaultProps

**Comment by paranoidjk** [comment]
我 reopen 的原因是我没复现这个 warning， @pingan1927 也没列出 warning 的具体内容，写的太不清晰了。

**Comment by warmhug** [comment]
能复现的、没问题

**Comment by paranoidjk** [comment]
@warmhug 这种 https://github.com/ant-design/ant-design-mobile/commit/4f1ad27aa781d0882d56cd16b1248f221cfabaee 是要避免的，默认值 和 defaultProps 语义不同，在 render 里面解构的时候取默认值，在其他地方 this.props.foo 还是 undefined，没有默认值，这就是区别

所以还是写清楚这个改动的原因
