### ISSUE TITLE
部分依赖未遵循语义化版本，造成 ant-design-mobile@0.9.17 版本依赖安装失败

### ISSUE THREAD

**Issue by pfdgithub** [ant-design/ant-design-mobile#1469]
### Version
0.9.17

### Environment
windows 7 ant-design-mobile@0.9.17 rmc-cascader@3.0.7 rmc-picker@3.10.5

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/0.9.x/package.json#L59](https://github.com/ant-design/ant-design-mobile/blob/0.9.x/package.json#L59)

### Steps to reproduce
历史项目，使用 ant-design-mobile@0.9.17 安装依赖时报错 Cannot resolve module 'rmc-picker/lib/Picker.web'  
分析后发现，是由于 rmc-picker 未遵循语义化版本造成，已经有人提过问题，却被作者忽略。  
[There is not an 'lib/index.web.js' in 3.9.1](https://github.com/react-component/m-picker/issues/21)  
[3.8.*and 3.9.*不兼容](https://github.com/react-component/m-picker/issues/22)  

antd-mobile@0.9.17 依赖 "rmc-cascader": "3.0.x"  
rmc-cascader@3.0.7 依赖 "rmc-picker": "3.x" 中的 Picker.web.tsx 文件  
rmc-picker@3.8.7 中含有 Picker.web.tsx 文件  
rmc-picker@3.9.0 至 rmc-picker@3.10.5 中不含该文件  

### What is expected?
希望官方能协调各开发者，梳理清楚依赖关系，并在 ant-design-mobile@0.9.x 中提供一个版本予以修复。  
毕竟遗留下来的项目，迁移至 ant-design-mobile@1.x 还是需要花费一些经历的。  

### What is actually happening?
```
ERROR in ./~/.3.0.7@rmc-cascader/lib/Cascader.web.js  
Module not found: Error: Cannot resolve module 'rmc-picker/lib/Picker.web'  
@ ./~/.3.0.7@rmc-cascader/lib/Cascader.web.js 15:14-50
```

**Comment by paranoidjk** [comment]
感谢返回，的确是我们的疏忽。
rmc-cascader@3.x 依赖 rmc-picker 的 Picker.web.tsx ， 而 rmc-picker 去 .web 后缀没遵循 semver

将会在 rmc-cascader@3.x 发一个 patch 版本取  .web 后缀来修复

**Comment by pfdgithub** [comment]
在官方未修复前，作为临时解决方案，可将 "rmc-picker": "3.8.7" 作为自己的项目依赖，放置于 "antd-mobile": "0.9.17" 之前，基于 npm3 的依赖安装顺序提前安装。

**Comment by kasinooya** [comment]
期望早日解决

**Comment by paranoidjk** [comment]
@pfdgithub fixed. Please try to upgrade your node_modules deps.
