### ISSUE TITLE
LisView sticky模式是否是只有window在scroll时候能才能调到onEndReached

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design-mobile#147]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：
#### 你做了什么？

```
<div style="height;50px"></div><div style="height:500px"> <ListView 
                            dataSource={dataSource}
                            renderFooter={() => <div style={{ padding: 30, textAlign: 'center' }}>
          {loading ? '加载中...' : '加载完毕'}
        </div>}
                            renderSectionHeader={(sectionData) => (
          <div>{sectionData}</div>
        )}
                            renderRow={row}
                            renderSeparator={separator}
                            pageSize={4}
                            scrollEventThrottle={20}
                            onScroll={() => { console.log('scroll'); }}
                            onEndnReached={this.onEndReached}
                            onEndReachedThreshold={10}
                          style={{height:"100%",padding:"0px",overflowY:"auto"}}
                            stickyHeader
                        /></div>
```
#### 你期待的结果是：

不希望整个页面滚动，只希望局部滚动，不加stickyHeader的时候没问题，加上stickyHeader发现滚到底部的时候，onEndReached事件调不到了。

**Comment by warmhug** [comment]
是这样的，0.7 可以禁止掉 sticky 效果，这样设置：
![image](https://cloud.githubusercontent.com/assets/2011119/17917571/3ebb4722-69f0-11e6-8da9-bb3b2125b5ff.png)

1.0 新增API `useBodyScroll` 可以用在 不需要`sticky` 效果、并想用 html 的 body 作为滚动容器的场景。https://github.com/ant-design/ant-design-mobile/blob/master/components/list-view/index.md

**Comment by ksh033** [comment]
那在局布div滚动里是不是不能使用sticky效果

**Comment by warmhug** [comment]
恩，目前不能

**Comment by ksh033** [comment]
这个能调整吗？因为我放到手机看页面的时候页面会被拖动，如果加` document.body.addEventListener('touchmove', function (event) {
    event.preventDefault();
  }, false)`这句的话页面不会被拖动，但是你listview组件的拖动也没办法做了。

**Comment by warmhug** [comment]
使用`useZscroller` API ，支持类似 iscroll 形式的滚动，不用滚动body 文档。 详细 https://mobile.ant.design/components/list-view/
