### ISSUE TITLE
InputItem cause build error !!!

### ISSUE THREAD

**Issue by xiaoyanit** [ant-design/ant-design-mobile#1470]
### Version
1.3.1

### Environment
win7,mac os 10.10.5 ,node v7.7.1

### Reproduction link
[https://github.com/nowa-webpack/template-antdmobile](https://github.com/nowa-webpack/template-antdmobile)

### Steps to reproduce
step1: checkout code https://github.com/nowa-webpack/template-antdmobile and build run env .
step2: modify Form.jsx like code [Link](https://raw.githubusercontent.com/xiaoyanit/antd-mobile/master/Form.jsx)

### What is expected?
InputItem should be display 

### What is actually happening?
Terminal show some issue report :
[Liink](https://raw.githubusercontent.com/xiaoyanit/antd-mobile/master/error.log)

---
I use source code https://github.com/nowa-webpack/template-antdmobile  and modify like "Steps to reproduce" , it looks all right , but failed !

**Comment by warmhug** [comment]
input-item 里 CustomKeyboard.less 引用的 png 图片换成 svg ，web 版不要有 相对路径 的 png 文件存在。less 文件名也不要大写。算了，我一起来改下。

**Comment by pingan1927** [comment]
png图表如无必要暂时不要换成svg。

**Comment by warmhug** [comment]
有必要，不然 webpack 需要增加处理 png 的配置

**Comment by pingan1927** [comment]
这个用户的webpack配置是自己搞的？

**Comment by xiaoyanit** [comment]
多谢两位，很高兴得到两位回复。这个问题之前已经和nowa-gui开发组的人沟通过了，通过修改webpack配置也能解决这个问题。

} else if (/\.css/.test(n.test)) {
改成
} else if (/css|png/.test(n.test)) {
@pingan1927 @warmhug 谢谢！

@warmhug  在使用rmc-select-list 的时候遇到点问题，已经发了邮件，能否给解决下呢，多谢！
https://github.com/react-component/m-select-list/issues/2
