### ISSUE TITLE
关于组件的svg无法显示的解决办法

### ISSUE THREAD

**Issue by wubianluoye** [ant-design/ant-design-mobile#1472]
### Version
1.3.1

### Environment
123

### Reproduction link
[https://mobile.ant.design/components/icon-cn/](https://mobile.ant.design/components/icon-cn/)

### Steps to reproduce
321

### What is expected?
123

### What is actually happening?
321

组件的svg不能显示也不报错，按照官网给的demo并不能跑通。
通过查看antm的github issue发现也有人遇到了这个问题。但他给出的解决方案在我这并没有用。
问题原地址:https://github.com/ant-design/ant-design-mobile/issues/1413（感谢这位兄弟）
不过在看他解决这个问题时说的要在file-loader中排除svg之后，结合了官网的文档，完成了以下配置，发现图标竟然能够显示了！
解决方法：
**以下全部都为配置webpack.config.dev.js文件**
1、添加
const svgDirs = [
  			require.resolve('antd-mobile').replace(/warn\.js$/, ''),  // 1. 属于 antd-mobile 内置 svg 文件
  			// path.resolve(__dirname, 'src/my-project-svg-foler'),  // 2. 自己私人的 svg 存放目录
];
2、除了配置svg-sprite-loader还需要在file-loader中排除svg，
应该是这样才对：
 exclude: [
		        ...
		        /\.less$/,
		        /\.svg$/,
 		       ...
		      ]

3、配置添加一个loaders
module.exports = {
		  module: {
		    loaders: [
		      {
		        test: /\.(svg)$/i,
 		       loader: 'svg-sprite',
		        include: svgDirs,  // 把 svgDirs 路径下的所有 svg 文件交给 svg-sprite-loader 插件处理
		      },
 		   ]
		  }
		};
新手上路，请多关照！

**Comment by warmhug** [comment]
@ant-design-bot markdown

**Comment by xmchyabi** [comment]
我也显示不出来，在这issue里搜索了不少，都是没有一个最终的，然后就被closed了。

**Comment by janeluck** [comment]
谢谢, 总结来说就是svg文件先被其他的loader处理了， 我用的是[https://github.com/davezuko/react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit])。 如果也有在使用的。再配置一下exclude就可以了
```js
const svgDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''),  // 1. 属于 antd-mobile 内置 svg 文件
  // path.resolve(__dirname, 'src/my-project-svg-foler'),  // 2. 自己私人的 svg 存放目录
]
// Fonts
// ------------------------------------
;
[
  ['woff', 'application/font-woff'],
  ['woff2', 'application/font-woff2'],
  ['otf', 'font/opentype'],
  ['ttf', 'application/octet-stream'],
  ['eot', 'application/vnd.ms-fontobject'],
  ['svg', 'image/svg+xml'],
].forEach((font) => {
  const extension = font[0]
  const mimetype = font[1]

  config.module.rules.push({
    test: new RegExp(`\\.${extension}$`),
    exclude: svgDirs,
    loader: 'url-loader',
    options: {
      name: 'fonts/[name].[ext]',
      limit: 10000,
      mimetype,
    },
  })
})


config.module.rules.push({
  test: /\.svg$/,
  include: svgDirs,
  loader: 'svg-sprite-loader'
})

```

**Comment by httol** [comment]
@janeluck 按照这个配置，我这里报错，怎么回事啊
![image](https://user-images.githubusercontent.com/4971746/69210878-37a8d480-0b97-11ea-9dff-56bbdfdfcce1.png)
