### ISSUE TITLE
强烈建议tabbar组件，在选中后还可以自定义点击事件

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [ant-design/ant-design-mobile#1473]
①现在用tabbar进入二级页面后，如果是项目激活后，就无法再次点击了，那也就是用户如果想返回只能后退 而不能通过点击来做

②另外如果tabbar的项目不激活，会出现内容无法显示，一直显示  加载中 。。。特别坑啊。。。

**Comment by paranoidjk** [comment]
并没理解你的描述，请给出可复现的demo
