### ISSUE TITLE
TabBar在iOS模拟器中正常，在Android真机上切换时，页面始终只显示第一次加载的页面

### ISSUE THREAD

**Issue by bluesky2525** [ant-design/ant-design-mobile#1474]
### Version
1.3.0

### Environment
react-native 0.45.1；react-native-router-flux; react-redux;

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
App启动后进入TabBar导航，正常显示第一个页面；随意通过TabBar切换任意页面时，无任何报错，但页面仍然为第一个页面（顶部导航Title有变化）

### What is expected?
点击TabBar的导航渲染相应页面

### What is actually happening?
始终显示第一个页面（在iOS模拟器中功能正常）

---
constructor(props) {
    super(props);
    this.state = {
      selectedTab: 'redTab',
    };
  }
  
  render() {
    return (
      <TabBar
        unselectedTintColor="#949494"
        tintColor="#33A3F4"
        barTintColor="white"
        style={{marginTop:10}}
      >
        <TabBar.Item
          title="我的应用"
          key="我的应用"
          selected={this.state.selectedTab === 'redTab'}
          icon={require('../../images/myapp.png')}
          selectedIcon={require('../../images/myapphover.png')}
          badge={'new'}
          onPress={() => {
            this.setState({
              selectedTab: 'redTab',
            });
            this.props.getApps();
          }}
          data-seed="logId"
        >
        <Home getApps={this.props.getApps}/>
        </TabBar.Item>
        <TabBar.Item
          title="消息"
          key="消息"
          selected={this.state.selectedTab === 'blueTab'}
          icon={require('../../images/message@2x.png')}
          selectedIcon={require('../../images/messagehover@2x.png')}
          badge={1}
          onPress={() => {
            this.setState({
              selectedTab: 'blueTab',
            });
            Actions.home();
          }}
          data-seed="logId1"
        >
          <Text>开发中，马上就绪，敬请期待</Text>
        </TabBar.Item>
        <TabBar.Item
          title="应用商店"
          key="应用商店"
          selected={this.state.selectedTab === 'whiteTab'}
          icon={require('../../images/store@2x.png')}
          selectedIcon={require('../../images/storehover@2x.png')}
          badge={'new'}
          onPress={() => {
            this.setState({
              selectedTab: 'whiteTab',
            });
          }}
          data-seed="logId2"
        >
        {this.state.selectedTab === 'whiteTab' && <AppStore />}
        </TabBar.Item>
        <TabBar.Item
          title="我"
          key="我"
          selected={this.state.selectedTab === 'blackTab'}
          icon={require('../../images/my@2x.png')}
          selectedIcon={require('../../images/myhover@2x.png')}
          onPress={() => {
            this.setState({
              selectedTab: 'blackTab',
            });
          }}
          data-seed="logId3"
        >
        {this.state.selectedTab === 'blackTab' && <UserSetting />}
        </TabBar.Item>
      </TabBar>
    );
  }

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
