### ISSUE TITLE
弹层pop不在Provider内

### ISSUE THREAD

**Issue by itxuye** [ant-design/ant-design-mobile#1479]
### Version
1.3.1

### Environment
Chrome 58 ，Mac OS

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile](http://new-issue.ant.design/?repo=ant-design-mobile)

### Steps to reproduce
弹出Pop之后发现不在provider里面,想问下怎么包裹弹层
![wechatimg281](https://user-images.githubusercontent.com/9589686/27377614-0cec10f0-56a8-11e7-90b7-e7bced14003d.jpeg)

**Comment by paranoidjk** [comment]
包裹弹层是什么意思？

请给出代码或demo

**Comment by afc163** [comment]
`getContainer` https://github.com/react-component/dialog ?

**Comment by itxuye** [comment]
@paranoidjk @afc163 Because I want to update the component ui in pop(component) with redux , but i can't get the redux provider.

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/794 https://github.com/ant-design/ant-design-mobile/issues/1125

@itxuye 暂时没什么好的方法，需要提供 一个 popupContainer 以供用户自定义，请关注上面两个 issue
