### ISSUE TITLE
ant design mobile 和 ant design 混在一起用, 这样的做法好不好

### ISSUE THREAD

**Issue by small752** [ant-design/ant-design-mobile#148]
把ant design mobile 和 ant design 混在一起用, 这样的做法好不好，
会不会存在一些资源过大，模块代码污染的问题

**Comment by dyf2015** [comment]
资源确实很大，建议分离

发自我的 iPhone

在 2016年8月24日，11:52，tardis <notifications@github.com<mailto:notifications@github.com>> 写道：


把ant design mobile 和 ant design 混在一起用, 这样的做法好不好，
会不会存在一些资源过大，模块代码污染的问题

―

**Comment by afc163** [comment]
不好，不要这么用。
