### ISSUE TITLE
Error:Cannot fund module 'antd-mobile/lib/nav-bar/style

### ISSUE THREAD

**Issue by xmchyabi** [ant-design/ant-design-mobile#1482]
### Version
1.3.1

### Environment
windows 7 webpack2.4.1

### Reproduction link
[https://codepen.io/xmchyabi/pen/qjjrpV](https://codepen.io/xmchyabi/pen/qjjrpV)

### Steps to reproduce
在已有的项目上引入antd-mobile
yarn add antd-mobile
yarn add --dev babel-plugin-import svg-sprite-loader@0.3.1 less less-loader postcss-pxtorem style-loader
yarn add --dev extract-text-webpack-plugin babel-preset-es2015

修改package.json：
  "babel": {
    "presets": [
      "react",
      "react-native-stage-0",
      "es2015"
    ],
    "plugins": [
      [
        "import",
        [
          {
            "libraryName": "antd-mobile",
            "style": true
          }
        ]
      ]
    ],
    "env": {
      "test": {
        "plugins": [
          "istanbul",
          "rewire"
        ]
      }
    }
  },

修改webpack.config.js:
见链接 https://codepen.io/xmchyabi/pen/qjjrpV，我把所有的config都贴上来了。

### What is expected?
能正常显示出 navbar 
  <NavBar leftContent="back"
          mode="light"
          onLeftClick={() => console.log('onLeftClick')}
          rightContent={[
            <Icon key="0" type="search" style={{ marginRight: '0.32rem' }} />,
            <Icon key="1" type="ellipsis" />,
          ]}
        >NavBar</NavBar>

### What is actually happening?
Error:Cannot fund module 'antd-mobile/lib/nav-bar/style

---
是不是还要修改   test: /\.css$/, 里的规则 ，我看官网里没有提到。
另外我有用到 服务端渲染，这个会有影响吗？
谢谢！！！

**Comment by silentcloud** [comment]
@xmchyabi 有没有配 extentions? https://mobile.ant.design/docs/react/introduce#Usage

**Comment by warmhug** [comment]
@ant-design-bot markdown

**Comment by warmhug** [comment]
把 babel-loader 配置里的

        include: [
          path.resolve(__dirname, '../src'),
        ],

去掉试试看

**Comment by paranoidjk** [comment]
webpack 2 的配置方法参考这里 https://github.com/ant-design/ant-design-mobile/issues/516#issuecomment-293632772

**Comment by paranoidjk** [comment]
文件是存在的，检测配置的问题 https://unpkg.com/antd-mobile@1.4.0/lib/nav-bar/style/

**Comment by xmchyabi** [comment]
@warmhug 
谢谢回复，我去掉那个配置，仍报一样的错误。

**Comment by Autumnwater** [comment]
一样在看，应该就是路径问题

**Comment by Autumnwater** [comment]
加了行 modulesDirectories: ['node_modules', path.join(__dirname, '../node_modules')],好了
 #516 (comment) 很对

**Comment by xmchyabi** [comment]
@Autumnwater  能分享看下你的webpack.config.js吗，我因为是需要在服务端渲染，怎么配置都不对。

**Comment by paranoidjk** [comment]
@xmchyabi 服务端渲染可以参考 https://github.com/ant-design/antd-mobile-samples/tree/master/web-ssr

**Comment by xmchyabi** [comment]
@paranoidjk  谢谢我再试下。。
