### ISSUE TITLE
Toast组件和Dva配合使用问题

### ISSUE THREAD

**Issue by chuncui0207** [ant-design/ant-design-mobile#1483]
**Version**

antd-mobile: 1.3.1
dva:1.2.1

**Environment**

Chrome 59

**Steps to reproduce**

在Dva里的model.effects 里调用Toast.success 没有反应，也不会报错。
是不是Toast只能在React 组件里才能使用？

**Comment by paranoidjk** [comment]
可以在effects里面使用，只要保证在 dom ready之后 
请提供可复现的demo
