### ISSUE TITLE
怎么转的rem

### ISSUE THREAD

**Issue by fangbao-0418** [ant-design/ant-design-mobile#1488]
怎么px转的rem

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE

**Comment by fangbao-0418** [comment]
Thank you
