### ISSUE TITLE
iOS Modal.prompt input hit area too small

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1489]
### Version
1.4.0

### Environment
iPhone5s Safari

### Reproduction link
[https://mobile.ant.design/components/modal-cn/](https://mobile.ant.design/components/modal-cn/)

### Steps to reproduce
点击 prompt 里的 input

### What is expected?
一次命中

### What is actually happening?
要很仔细的找准位置。

**Comment by cncolder** [comment]
之前听说过 Mobile safari focus 问题，实现不了 autofocus。

在只有一个 input 的情况下，能不能让整个 body 都做为 hit area？

**Comment by paranoidjk** [comment]
> 在只有一个 input 的情况下，能不能让整个 body 都做为 hit area？

这个我不赞成，点击区域扩得太大了。

这个尝试提供 focus. https://github.com/ant-design/ant-design-mobile/issues/1243

**Comment by silentcloud** [comment]
扩大到 body，太大了

**Comment by cncolder** [comment]
别激动，随口一说。😁

我自己的解决办法是增加 `line-height`

**Comment by paranoidjk** [comment]
实测居中是比较难点，要么样式上优化，要么提供 js 的 focus api

**Comment by paranoidjk** [comment]
@silentcloud Modal.Prompt 的 sketch 在哪？发我一份，input 感觉高度太小了

**Comment by silentcloud** [comment]
@paranoidjk 这个有点时间了，我本地是没有了，找设计师问问看还有没有

**Comment by afc163** [comment]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/507615/27578937-4f17e526-5b58-11e7-8555-8531719769e4.png">

```html
<label>
  <h2>标题</h2>
  <input />
</label>
```

套个 label。

**Comment by cncolder** [comment]
@afc163 `Modal.prompt` 没办法传入 children。

甚至都没办法指定 input text/password 以外的类型。

是不是应该再加一个 custom type，允许用户传入自己的 input，甚至允许任意 Element，只要接口符合就行。

```ts
interface {
  defaultValue: any
  focus: () => void
  onChange: (value: string) => void
}
```

**Comment by silentcloud** [comment]
@cncolder 
> 是不是应该再加一个 custom type，允许用户传入自己的 input，甚至允许任意 Element

那这个 api 方法就不好定了，而且还要 rn web 一致

**Comment by paranoidjk** [comment]
@cncolder 看 https://github.com/ant-design/ant-design-mobile/issues/1125， 我有提议在 2.0 将 API 改成声明式的

**Comment by linhanyang** [comment]
键盘遮挡按钮问题不知道大家如何解决呢？

**Comment by paranoidjk** [comment]
@linhanyang 

应该不会有键盘遮挡的问题，antd-mobile 做了 [处理](https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.web.tsx#L116)，实测也无法复现。

请提供可复现的 demo.

**Comment by linhanyang** [comment]
![image](https://user-images.githubusercontent.com/7603016/28452634-21e53f64-6e26-11e7-8c1c-2907b4e0dc87.png)

在react native平台

**Comment by paranoidjk** [comment]
@silentcloud 实测的确有键盘遮挡的问题，rn 有办法类似 web scrollIntoView 的方案吗？

**Comment by paranoidjk** [comment]
http://facebook.github.io/react-native/docs/keyboardavoidingview.html

**Comment by paranoidjk** [comment]
@linhanyang https://github.com/rccoder/blog/issues/25

**Comment by linhanyang** [comment]
嗯，是可以采用这个方法，此方法需要考虑兼容andorid平台

**Comment by linhanyang** [comment]
是否考虑在此组件加入这个方法呢？
@paranoidjk

**Comment by linhanyang** [comment]
遮挡问题没有解决哦，刚试了这个版本，还是有遮挡问题。
![image](https://user-images.githubusercontent.com/7603016/28704360-a576f09a-739c-11e7-9bf1-e5fe8c37800a.png)
![image](https://user-images.githubusercontent.com/7603016/28704362-a8fa05a4-739c-11e7-98c7-35fa14afe03f.png)

**Comment by linhanyang** [comment]
https://github.com/maxs15/react-native-modalbox/issues/87

**Comment by linhanyang** [comment]
https://github.com/raynor85/react-native-modal-wrapper

**Comment by linhanyang** [comment]
@paranoidjk

**Comment by paranoidjk** [comment]
@linhanyang 抱歉，最近比较忙，这个问题如上所说，你业务代码可以自己解决，优先级比较低。

组件内部实现的不完美的话，欢迎 PR 来帮我们修复。

**Comment by linhanyang** [comment]
嗯，我目前仅仅做了下调整，而且不是太好的办法。现在在ios上显示是个问题，不仅仅是业务问题。

**Comment by aizigao** [comment]
同样的问题，项一下

**Comment by aizigao** [comment]
我在rc-dialog下提了个pr https://github.com/react-component/dialog/pull/67 ， 参考[react-native中语网的写法](http://reactnative.cn/docs/0.47/keyboardavoidingview.html#content) ， 将keyboardavoidingview放在 Modal下可以解决这个问题

**Comment by linhanyang** [comment]
@paranoidjk 好像这个问题还是没解决吧？
