### ISSUE TITLE
List和Flex的type.d.ts会导致TS2604错误

### ISSUE THREAD

**Issue by bylevel** [ant-design/ant-design-mobile#1495]
### Version
1.4.0

### Environment
macOS 10.12.5, chrome, react@^15.5.4

### Steps to reproduce
```
<List>
      <List.Item>
        <Link to="/equipments" onClick={this.onMenuToggle}>设备列表</Link>
      </List.Item>
</List>
```

### What is actually happening?
error TS2604: JSX element type 'List.Item' does not have any construct or call signatures.

---
将 List 组件的 type.d.ts 中的static Item: ListItem; 改成 static Item: typeof ListItem; 就能正常编译

Flex组件也是同样的问题

**Comment by paranoidjk** [comment]
@bylevel why close ? does your problems solved?

**Comment by bylevel** [comment]
@paranoidjk because same #1502

**Comment by paranoidjk** [comment]
@bylevel #1502  is a Pull Request to fix this issue, so your issue must keep open until #1502 is merged, thanks for your report.

**Comment by bylevel** [comment]
at version 1.4.1 this problem solved.
