### ISSUE TITLE
add test for umd dist bundle

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1496]
Right now our test code both import from `src`, we can not guarantee the build output is ok.

**Comment by paranoidjk** [comment]
cc @yesmeck

**Comment by yesmeck** [comment]
我来搞下好了，antd 也搞一下。

**Comment by warmhug** [comment]
还需要加入 bundle 分析插件 [webpack-visualizer-plugin](https://www.npmjs.com/package/webpack-visualizer-plugin) ，这个能显示各个 module 体积和其所占总百分比的数据。

**Comment by paranoidjk** [comment]
https://github.com/facebook/react/pull/10090

**Comment by warmhug** [comment]
ref #1274

**Comment by paranoidjk** [comment]
https://github.com/ai/size-limit
