### ISSUE TITLE
why ios modal.alert is like this ?

### ISSUE THREAD

**Issue by weishijun14** [ant-design/ant-design-mobile#1498]
### Version
1.4.0

### Environment
ios: 8.1.2, 10.3.3 
react: 15.5
wechat: 6.5.9
### Steps to reproduce
```
onCancel(e,params){
      e.stopPropagation();
      alertModal('取消订单', '确定取消么?', [
        { text: '取消' , onPress: () => console.log('cancel')},
        { text: '确定', onPress: () => this.props.dispatch({
          type:'app/gotoCancel',
          payload:{
            orderid:params,
            page: 1,
            pagesize:10,
          }
        })},
      ])
    }
```

### What is expected?
![Image of alert](http://i2.kiimg.com/1949/904c975ce6f64001.png)

### What is actually happening?
![Image of alert](http://i2.kiimg.com/1949/d636fe601580dcad.png)

**Comment by cncolder** [comment]
显然是被你自己的样式给覆盖了，到 chrome devtools 里检查一下最后生效的样式来自于哪里。
