### ISSUE TITLE
Modal android fullscreen design

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1499]
### Version
1.4.0

### Environment
web android

### Reproduction link
[https://codepen.io/colder/pen/LLeGaN](https://codepen.io/colder/pen/LLeGaN)

### Steps to reproduce
```jsx
<Modal transparent={false} platform='android' />
```

### What is expected?
在 iOS 上是真正全屏的。

### What is actually happening?
在 Android 上，`padding: .3rem .48rem` 而且四周还是白色。

---
设计稿就是这样的吗？请问是遵从什么标准？

**Comment by paranoidjk** [comment]
- 看了下，padding 是为了内容区, Modal 是有 title 的，你看下官方 demo
- 白色是 Modal 默认的背景色，而内容区被你自定义成灰色了，所以有点丑.... 你要自定义样式的时候都自定义就该就好

**Comment by cncolder** [comment]
@paranoidjk 在 transparent=false 的时候，Modal 没有 title。

我看了 less，android 样式额外加的 padding 对 transparent=false 也生效了，应该是 BUG。

**Comment by silentcloud** [comment]
@cncolder 这个我来修了
