### ISSUE TITLE
为什么我打包的文件很大

### ISSUE THREAD

**Issue by hotmanxp** [ant-design/ant-design-mobile#150]
我在一个页面引入了 表单里的上次图片、多行文本域、滑块组件， 文件大小就增加了 100多K ，，使用了 babel-plugins-antd , webpack 开启了 优化压缩，不知道哪里有不对，，，

**Comment by dancinglone** [comment]
同觉得好大T_T

**Comment by warmhug** [comment]
@dancinglone 在持续优化体积
