### ISSUE TITLE
As official create-react-app with antd-mobile，there is no icon/style/assets folder，can not show the icons

### ISSUE THREAD

**Issue by LucasDvp** [ant-design/ant-design-mobile#1501]
### Version
1.4.0

### Environment
mac os10.12.5， chrome 59.0.3071.109， react 15.6.1, antd-mobile 1.4.0, svg-sprite-loader 0.3.1

### Reproduction link
[https://codepen.io/anon/pen/RgxVze](https://codepen.io/anon/pen/RgxVze)

### Steps to reproduce
1. steps：https://mobile.ant.design/docs/react/use-with-create-react-app
2. No icon/style/assets downloaded with **yarn add**

### What is expected?
show icons

### What is actually happening?
no icons

**Comment by LucasDvp** [comment]
问题解决了，create-react-app的file-loader和svg-sprite-loader有冲突，感觉是个bug，你们可以follow一下。

**Comment by paranoidjk** [comment]
@silentcloud 文档里突出要exclude file loader了吗？这个问题印象中有两个issue了

**Comment by silentcloud** [comment]
@paranoidjk web 的文档你再 check 一下吧，看看有没有什么要补充或者不对的地方

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1413
