### ISSUE TITLE
iOS safari money keyboard input item collapse in transparent modal

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1508]
### Version
1.4.0

### Environment
iOS safari

### Reproduction link
[https://codepen.io/colder/pen/MoQmjR](https://codepen.io/colder/pen/MoQmjR)

### Steps to reproduce
```jsx
<Modal visible transparent>
  <InputItem type='money' focused />
</Modal>
```

### What is expected?
数字键盘从底部出现

### What is actually happening?
键盘坍缩在对话框里了

![fullsizerender 2](https://user-images.githubusercontent.com/127009/27711191-f70123e4-5d54-11e7-90cf-f772df5a14df.jpg)

**Comment by cncolder** [comment]
css 可破

```css
.am-modal-body {
  overflow: visible;
}
```

**Comment by paranoidjk** [comment]
直接pr？

**Comment by cncolder** [comment]
影不影响 Modal 我不清楚

**Comment by paranoidjk** [comment]
![img](https://gw.alipayobjects.com/zos/rmsportal/WzrEXJeVHdAkmRzeTNiZ.png) 看着好像正常？

**Comment by pingan1927** [comment]
好多幺蛾子，555，还有就是大屏幕，每个数字键盘的高宽比不和谐..

**Comment by cncolder** [comment]
如果当初这个键盘像 Dialog 一样放在外面不知道会不会好点，反正这个键盘是肯定不会变的。

**Comment by paranoidjk** [comment]
@cncolder 你的意思是 create 一个 div， append 到 body 上，再把虚拟键盘 render 到这个 div ?

**Comment by cncolder** [comment]
@paranoidjk 只是一个想法，因为独立的 div肯定不会受外部容器的影响了。

**Comment by silentcloud** [comment]
@cncolder 这个想法我们当时在 review pr 的时候不是提出来了的么

**Comment by paranoidjk** [comment]
@cncolder can you test whether it been fixed in https://github.com/ant-design/ant-design-mobile/releases/tag/1.6.5 ?

**Comment by paranoidjk** [comment]
close for no response.

If anyone still got problems with newest version of antd-mobile, please commet here with a reproducible demo, and i will check it.
