### ISSUE TITLE
关于 antd-mobile 全局样式纠结的地方

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#151]
库的样式有个很暴力的设置就是 `a:hover, a:active { color: #0EA6EB}`  几乎引用咱们库的都要修改这个设置，然而这个修改起来很纠结，可否把这个设置删掉？

另外希望官方出一个修改样式的方案，最好可以自定义全局样式的那种，就更完美了！毕竟我们用这个库看重的是里面封装的几个常用的功能组件，比如swipe, 时间选择，城市选择，表单等。

**Comment by yiminghe** [comment]
这个谁搞的，不应该全局设置 a 啊

@ant-design/ant-design-team

**Comment by liqi07** [comment]
貌似之前谁给加了默认色，我给删掉好了

**Comment by liqi07** [comment]
https://github.com/ant-design/ant-design-mobile/commit/ca59fc948ae3531cff0d147d7960c6d9e6ddb8fe @pingan1927   这里全局设置没什么问题吧，类似base的处理，增加链接的默认色，不使用默认的就自己定制

**Comment by pingan1927** [comment]
`a:hover, a:active { color: #0EA6EB}`不合适就删掉。
https://github.com/ant-design/ant-design-mobile/blob/master/components/style/index.less#L18
现在这样有问题？

**Comment by liqi07** [comment]
建议保留，预设a的基本样式，和框架风格协调。  
pc上也做了类似的设置 https://github.com/ant-design/ant-design/blob/master/components/style/core/base.less#L56

**Comment by minooo** [comment]
@liqi07 @pingan1927  还是建议这个全局a的颜色去掉，对于引入antd-mobile 框架的项目有点反客为主了。
- 拿我的项目举例，我的 a 有些用的主色，底色是白色，有些是白色，底色是主色，不管a:hover,还是a:avtive  a的颜色都能维持原有颜色，但是你们的 `a:hover, a:active { color: #0EA6EB}` 破坏了这个平衡，你说我把 a:hover,a:active 的颜色设为主色还是白色，恐怕都不行。这样我就不得不把a的颜色重新挨个设置 a:hover , a:active 了。。。
- 另外，不知道你们说的修改是样式覆盖还是到包里面修改。
- 最后，全局样式覆盖，设置请给个文档说明，谢谢了！ 爱你们

**Comment by silentcloud** [comment]
base 应该只是一些基本的 reset， 对于颜色这类感觉不应该设置在全局里

**Comment by warmhug** [comment]
pc 上貌似很多组件库都有这设置，但移动可能必要性不太大，像 hover 明显来自pc 移动没有，感觉移动可以去掉

**Comment by warmhug** [comment]
```
background: transparent;
text-decoration: none;
outline: none;
```
这几个保留。颜色设置、做个 mixin 、分别加到单个组件里？

**Comment by yiminghe** [comment]
去掉吧，组件需要 a 样式，自己 mixin

**Comment by afc163** [comment]
这个要加回来，配置中有 @color-link 的配置，没有这个代码，设计配置平台就失效了。

https://github.com/ant-design/ant-design-mobile/wiki/%E8%AE%BE%E8%AE%A1%E5%8F%98%E9%87%8F%E8%A1%A8%E5%8F%8A%E5%91%BD%E5%90%8D%E8%A7%84%E8%8C%83

**Comment by benjycui** [comment]
从组件样式隔离来看，把 `a` 等标签的重置 mixin 进组件样式可能是比较好的选择，但是这样也无法确保全栈同学做的页面样式统一了，因为他们可能会忘了 minxin。

其次，antd-mobile 本来就是跟随 Ant Design Mobile 规范的，所以要求页面必须跟随同样的风格也是合理的？

最后，从一开始引入 [`normalize.css`](https://github.com/ant-design/ant-design-mobile/blob/master/components/style/index.web.tsx#L1) 时，antd-mobile 的样式就是侵入性的了。

**Comment by silentcloud** [comment]
这个最终的结论是什么？@afc163 @warmhug @benjycui

**Comment by afc163** [comment]
可以先把相关全局代码搞回来，但是不默认引入，我自己引用一下。

**Comment by warmhug** [comment]
就这段代码 https://github.com/ant-design/ant-design-mobile/blob/master/components/style/index.less 和 normalize.css 。mobile 全栈和 pc 的很不一样，a 标签还是不要设置默认颜色的好，normalize 对业务已有样式影响不大。
