### ISSUE TITLE
SearchBar iOS键盘类型不是搜索

### ISSUE THREAD

**Issue by caigehui** [ant-design/ant-design-mobile#1510]
### Version
1.4.0

### Environment
iOS 10.3.1 Safari

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/search-bar?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/search-bar?lang=zh-CN)

### Steps to reproduce
用iPhone进入SearchBar的Demo

激活任意一个SearchBar

发现键盘右下角的按键是“换行/return”而不是“搜索/search“

### What is expected?
键盘右下角的按键是“搜索/Search“

### What is actually happening?
键盘右下角的按键是“换行/return“

**Comment by silentcloud** [comment]
键盘要出现 search，要满足 1. type=search  2. 被 form 包括且有 action 属性

**Comment by caigehui** [comment]
请问有没有可能在SearchBar组件里面处理好这两个条件？毕竟是搜索条，键盘肯定是要显示Search的
@silentcloud

**Comment by paranoidjk** [comment]
@caigehui `antd-mobile@1.4.1`

**Comment by Manweill** [comment]
@paranoidjk 更新到1.4.2貌似还是会出现这个问题，IOS下是换行，安卓下是“回车”

**Comment by yangzonglong** [comment]
解决了 刚开始 加了 returnKeyType=search 没反应，我以为不可以，原来是我服务没有自动更新代码的问题

**Comment by zhangjunjia** [comment]
SearchBar ios placeholder disappear
