### ISSUE TITLE
TextareaItem:  remove focused autoFocus api

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1514]
https://github.com/ant-design/ant-design-mobile/blob/0265bdf0eed58c263522e03ffab8cac0e0cdd96a/components/textarea-item/index.web.tsx#L51-L52

cc @benjycui

**Comment by benjycui** [comment]
是 remove `this.state.focus`。

`props.focused` 可是 af-appx 依赖了的。。

**Comment by paranoidjk** [comment]
> focus 是用来控制样式的，是否显示删除icon  跟focused 不等价   要删可以试试

**Comment by pingan1927** [comment]
可以，这个也放到2.0去吧

**Comment by paranoidjk** [comment]
af-appx 已经不依赖了，这个可以删了。

**Comment by paranoidjk** [comment]
focus 相关的要梳理下，现在方式太多了 https://github.com/ant-design/ant-design-mobile/issues/1243
