### ISSUE TITLE
Simplify viewport and root font-size setting scripts

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1515]
```js
import { hd } from 'antd-mobile'

hd()
```

**Comment by paranoidjk** [comment]
现在的文档太长太复杂了... 我昨天自己翻译这个文档都受不了 😅

**Comment by benjycui** [comment]
`hd` => `enableHD` 😄

**Comment by paranoidjk** [comment]
变量命名专家 @benjycui

**Comment by benjycui** [comment]
考虑到 antd-mobiel 已经支持 SSR，正确用法应该是：

```jsx
import { enableHD } from 'antd-mobile'

if (isBrowser) {
  enableHD();
}
```

又或者 enableHD 内部自行处理。

**Comment by paranoidjk** [comment]
不能内部把这个吞掉，报错就好了，viewpoer 的设置必须在前端设置，所以文档里注明 `enableHD ` 一定要在浏览器端执行

**Comment by paranoidjk** [comment]
这是我梳理过后的文档，还是嫌多 https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE

https://github.com/ant-design/ant-design-mobile/wiki/Antd-Mobile-viewport-setting-wiki

@warmhug

**Comment by silentcloud** [comment]
同意这么改，看到这个高清方案文档这么长，就出门了

**Comment by cncolder** [comment]
我记得有一句：“请内联写到所有 css 引用之前, 否则部分安卓机有问题”。

如果用 import 的方式怎么保证在 css 之前加载？

**Comment by cpunion** [comment]
我查看编译后的 css，都是用的 px，既然内部会换算成 px，能否别自动设置？会和用户项目造成潜在冲突。目前似乎假定用户全部基于 antd-mobile 来构建，但实际会有遗留代码、第三方库之类的兼容性问题。

一点建议：能否不自动设置 html 的 font-size 和 viewpoint？包括减少全局样式设置。或者至少有个方便的选择，比如我可以引入一个缩减版的。

**Comment by paranoidjk** [comment]
@cpunion 
- 编译后的 css 以 `rem` 为单位，请仔细看
- 旧项目迁移请看 [wiki](https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE#%E6%97%A7%E9%A1%B9%E7%9B%AE%E8%BF%81%E7%A7%BB%E6%96%B0%E9%A1%B9%E7%9B%AE%E5%8F%AF%E4%BB%A5%E5%BF%BD%E7%95%A5%E8%BF%99%E4%B8%80%E9%83%A8%E5%88%86%E5%86%85%E5%AE%B9)

**Comment by cpunion** [comment]
这是统计结果：

```
编译后的 es 目录：
rem: 6 matches across 4 files
px: 842 matches across 79 files

lib 目录：
rem: 6 matches across 4 files
px: 842 matches across 79 files

dist/antd-mobile.css:
rem: 598 matches in 1 file
px: 0 matches
```
使用 `babel-plugin-import` 导入的是 lib 目录下的 css，通过 Chrome 查看：

![image](https://user-images.githubusercontent.com/8459/28298594-baaca2a4-6b39-11e7-8783-6e8ea8fc41ff.png)

这里的单位是 px。

感谢提供旧项目迁移指南。迁移有一定难度，我的建议是，如果像 lib 目录一样，只有 6 处（只有card 和 toast 组件）使用 rem，是否可以全部统一为 px？编译为 dist 时依然可以转为 rem 并添加上 html 等元素的样式。

**Comment by paranoidjk** [comment]
@cpunion Sorry, 这里的确有些问题

- 编译后的 umd  dist css 以 `rem` 为单位，see https://unpkg.com/antd-mobile@1.4.2/dist/
- 通过 babel-plugin-import 引用的 less 源码是以 px 为单位，这里没问题，需要用户通过 postcss px-to-rem 编译，参考 [antd mobile 0.8 以上版本「高清」方案设置
](https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE)
-  **通过 babel-plugin-import 引用的 css 文件仍然是以 px 为单位，这里我认为是有问题的**，我提议 compile 的时候，lib 和 es 下的 css 文件也要经过 px-to-rem 处理，即**对外的 css 文件都以 rem 为单位，提供的css文件不应该要求用户进行二次编译** @warmhug @pingan1927 
- 旧项目迁移请看 [wiki](https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE#%E6%97%A7%E9%A1%B9%E7%9B%AE%E8%BF%81%E7%A7%BB%E6%96%B0%E9%A1%B9%E7%9B%AE%E5%8F%AF%E4%BB%A5%E5%BF%BD%E7%95%A5%E8%BF%99%E4%B8%80%E9%83%A8%E5%88%86%E5%86%85%E5%AE%B9)

**Comment by pingan1927** [comment]
good

**Comment by cpunion** [comment]
@paranoidjk 我这个项目有点特殊，rem 设置冲突了。所以我去掉 `babel-plugin-import`，改为 `import 'antd-mobile/dist/antd-mobile.css'`，并使用 `postcss-remtopx` 反着转了，能满足我的使用场景，等重构时再统一。

谢谢你的提示。:-)

**Comment by aizigao** [comment]
有木有行内样式 px 转 2x rem 的方案 😆

**Comment by paranoidjk** [comment]
close in https://github.com/ant-design/ant-design-mobile/pull/1713/

## antd-mobile@2.0 适配方案
1.  @ustccjw 改造了1px 线的实现，默认不依赖 viewport 缩放，html 上加上 data-scale 属性的时候，回退到 normal 的border，即 viewport 缩放
2. 在 1 的前提下, antd-mobile 默认就不再依赖 viewport 缩放，则对外提供的都是 1 倍（375）的 px 样式。
3. 如果用户自己要使用 viewport 缩放，确保在 html 上加上 data-scale 属性，并用 post-css 处理样式 （会体现在文档）
