### ISSUE TITLE
iphone5的html 为什么是font-size:100px，没考虑高清的吗？iphone6也是100px

### ISSUE THREAD

**Issue by weianzi** [ant-design/ant-design-mobile#1520]
### Version
1.4.1

### Environment
chrome Version 58.0.3029.110 (64-bit)

### Reproduction link
[https://mobile.ant.design/kitchen-sink/](https://mobile.ant.design/kitchen-sink/)

### Steps to reproduce
官方DEMO: https://mobile.ant.design/kitchen-sink/

iphone5的html 为什么是font-size:100px？
iphone6的html 也是font-size:100px

### What is expected?
iphone5的html 是font-size:85px左右

### What is actually happening?
iphone5的html 为什么是font-size:100px

**Comment by paranoidjk** [comment]
see https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE

不同 dpr 的才会缩放，不是根据屏幕宽度来。
