### ISSUE TITLE
refactor menu to ssr friendly

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1521]
ref: https://github.com/ant-design/ant-design-mobile/pull/1337

problem code: https://github.com/ant-design/ant-design-mobile/blob/master/components/menu/index.web.tsx#L96

**Comment by cncolder** [comment]
Menu 有个简单的处理方法，同时支持用户传入数值和字符串。系统不提供默认高度，参见 `ListView.IndexedList without sticky` demo。用户不提供高度，组件就不加高度样式。

```js
const heightStyle = height ? { height } : {}
```
