### ISSUE TITLE
remove `require` in souce code, prefer use `import`

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1523]
https://github.com/ant-design/ant-design-mobile/search?l=TypeScript&q=require&type=&utf8=%E2%9C%93

**Comment by paranoidjk** [comment]
cc @warmhug @yesmeck @benjycui 

@silentcloud 也看下 rn 的是否可以这样改，应该是没问题的，这周的版本我全改成 es module 语法

**Comment by cncolder** [comment]
不是 `import('./abc.svg')` 吧？ 如果是 `import abcSvg from './abc.svg'` 的话我没问题。

**Comment by paranoidjk** [comment]
一般不会用 dynamic import，但是会有什么问题？

**Comment by silentcloud** [comment]
@paranoidjk RN 虽然也是可以的，但是不推荐这么改，我所接触对库里也没人这么用对，官方也是用对 require，说不定有其他潜在问题，还没发现。RN 的还是别改了，和官方保持一致，读代码也能立马知道引用对应对哪张图
