### ISSUE TITLE
split default locale when build with another LocaleProvider setting

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1524]
https://github.com/ant-design/ant-design-mobile/blob/master/components/date-picker/index.web.tsx#L30

**Comment by paranoidjk** [comment]
## 使用其他语言+不提供切换

默认语言 + 用户设置的语言会被打包到一起 --> 默认语言冗余

## 使用其他语言+ 提供切换

 默认语言 + 用户设置的语言 + 可以被切换的语言会被打包到一起 --> 一般切换语言会刷新页面，js 重新加载，这种情况其他语言的 locale 都是冗余

**Comment by paranoidjk** [comment]
https://github.com/ant-design/intl-example

**Comment by paranoidjk** [comment]
cc @benjycui

**Comment by paranoidjk** [comment]
close. Wait until there have a feature request.

**Comment by benjycui** [comment]
之前漏看了。。

要把默认语言从构建后的文件中移掉，我们就需要提供构建相关的 API，比如:

```bash
ANTD_LOCALE=en-US
```

然后代码这样写：

```jsx
let defaultLocale = null;
if (ANTD_LOCALE === 'zh-CN') {
  defaultLocale = { ... };
}
```

**Comment by benjycui** [comment]
感觉不是很有必要。。

**Comment by paranoidjk** [comment]
@benjycui 其实默认语言还是要打包在 main bundle 中的，我的意思只是把待切换的其它语言按需加载

```html
index-with-zh-CN.js
en-US.js
...
```

**Comment by benjycui** [comment]
> 我的意思只是把待切换的其它语言按需加载

如果是 webpack，已经是按需加载了：

```jsx
import enUS from 'antd/lib/locale-provider/en_US';
```

如果是 dist 文件，其实 locales 文件没多大。

antd 20-30 种语言，都打进来也只差 80k，用 dist 的人也不差这 80k 了吧。。 see: https://unpkg.com/antd@2.13.0/dist/
