### ISSUE TITLE
expected a component class got [object Object]

### ISSUE THREAD

**Issue by gaoxiaosong1113** [ant-design/ant-design-mobile#1526]
当我在`react-native`项目中使用 `ant-design-mobile`

引入 `NavBar` 组件，模拟器提示

![image](https://user-images.githubusercontent.com/16183057/27818213-52dd0d84-60c7-11e7-8ce8-df3e04ac1256.png)

下面是我的代码：

![image](https://user-images.githubusercontent.com/16183057/27818242-7087ce6e-60c7-11e7-989a-7012094822e5.png)

请问是我哪里出了错误？

**Comment by silentcloud** [comment]
@gaoxiaosong1113 NavBar 没有对应对 react-native 组件，主要是给 web 用的，不需要有 RN 的，原因：RN 有自己对 navigator 的，这里确实不应该报错，是代码的问题，我改一下。

NavBar 的话你直接用 RN 的
