### ISSUE TITLE
Discuss about better changelog & issue label

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1528]
- http://keepachangelog.com/en/1.0.0/
- https://github.com/eggjs/egg/pull/1152/files

**Comment by paranoidjk** [comment]
- https://github.com/ant-design/ant-design/labels
- https://github.com/eggjs/egg/labels

IMO, egg is better, we can learn from it.

**Comment by paranoidjk** [comment]
cc @ant-design/ant-design-team

**Comment by silentcloud** [comment]
labels 我觉得现有的也还好，不同类型的库；

当前需要改进的是 commit log

**Comment by paranoidjk** [comment]
- [git-commit-guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [git-commit-cli-tools](https://github.com/commitizen/cz-cli)

**Comment by paranoidjk** [comment]
renamed all issue label. https://github.com/ant-design/ant-design-mobile/labels
