### ISSUE TITLE
Picker - when click picker in iOS, it is ok, but in Android, it throws a exception. ReactNative: v0.44

### ISSUE THREAD

**Issue by phpSing** [ant-design/ant-design-mobile#1537]
### Version
1.4.1

### Environment
"antd-mobile": "^1.1.3", "react-native": "0.44.0", "react": "16.0.0-alpha.6",

### Reproduction link
[https://codepen.io/anon/pen/OgwOpj](https://codepen.io/anon/pen/OgwOpj)

### Steps to reproduce
use Picker in any React Native project, with version 0.44 and "antd-mobile": "^1.1.3", build into both iOS and  android, config the Picker to a single column select pick with anything of 2 options (e.g. [{ label: 'one', value: 1 }, { label: 'two', value: 2 }]), click the picker to choose, it runs ok with iOS, but in android version 5.X, it throws a exception described as below:

com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'this.itemHeight')

and this code is traced back to file "antd-mobile.js" line 45259

"this.itemHeight = this.refs.indicator.getBoundingClientRect().height;"

### What is expected?
error free in both android and ios

### What is actually happening?
 in android version 5.X, it throws a exception described as below:

com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'this.itemHeight')

and this code is traced back to file "antd-mobile.js" line 45259

"this.itemHeight = this.refs.indicator.getBoundingClientRect().height;"

**Comment by phpSing** [comment]
full exception below:

07 - 06 16: 11: 51.089 27733 - 27868 / ? E / AndroidRuntime : FATAL EXCEPTION: mqt_native_modules
Process: com.haiziwang.customapplication, PID: 27733
com.facebook.react.common.JavascriptException: undefined is not an object(evaluating 'this.itemHeight'), stack:
  value @883: 1371
u @69: 142
invokeGuardedCallback @69: 480
invokeGuardedCallbackAndCatchFirstError @69: 601
c @86: 386
a @86: 588
v @137: 522
g @137: 625
i @140: 95
processEventQueue @137: 1453
s @148: 88
handleTopLevel @148: 195 <
  unknown > @147: 593
a @84: 297
c @84: 60
perform @189: 596
batchedUpdates @200: 464
i @188: 358
i @84: 90
u @84: 150
_receiveRootNodeIDEvent @147: 565
receiveEvent @147: 675
value @20: 3000 <
  unknown > @20: 941
value @20: 2401
value @20: 913

at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java: 99)
at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java: 83)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java: 372)
at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java: 368)
at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java: 138)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java: 815)
at android.os.Handler.dispatchMessage(Handler.java: 104)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java: 31)
at android.os.Looper.loop(Looper.java: 194)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java: 208)
at java.lang.Thread.run(Thread.java: 818)

**Comment by phpSing** [comment]
minimal config code:

> Data:

`
const _data = [
    {
      label: '会员',
      value: 0,                
    },
    {
      label: '员工',
      value: 1,                
    },
]
`
Class 

> Method

`
  CustomPickerChildren = (props) => {
    const { searchType } = this.state
    return (
      <TouchableOpacity onPress={props.onClick}>      
        <View style={styles.pickerInner}>
          <Text style={styles.pickerLabel}>{searchType ? '员工' : '会员'}</Text>
          <Image style={styles.downArrow} source={require('../../assets/downArrow.png')} />
        </View>
      </TouchableOpacity>
    )
  }
`

> In Render Method:

`
              <Picker title='类型' onChange={handlePickerChange} data={_data} value={[searchType]} cols={1} extra=''>
                <CustomPickerChildren></CustomPickerChildren>
              </Picker>
`

**Comment by phpSing** [comment]
I will upgrade to 1.4.1 to see if it still exist

**Comment by paranoidjk** [comment]
It should been fixed  in https://github.com/ant-design/ant-design-mobile/issues/1450

**Comment by DeanTG** [comment]
i resolved this problem, cuz label and value of datasource requires String
