### ISSUE TITLE
In rn v0.46.0, the componet "tab-bar" of antd-mobile can't switch contents, it displays last tab's content. why?

### ISSUE THREAD

**Issue by alex-ling** [ant-design/ant-design-mobile#1538]
### Version
1.4.1

### Environment
rn v0.46

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
react-native init test
cd test
npm i antd-mobile --save
npm i babel-plugin-import --save-dev
copy "demo.tsx" code of tab-bar, and so on.
react-native run-android

### What is expected?
The tab-bar displays correct. But can't switch tab-bar's content, it all displays last one.
Then i changed RN's version to V0.44.0, All things worked correctly.
So, RN's V0.46.0 Is not compatible with the antd-mobile's tab-bar component.
RN's V0.45.0 not to try.

### What is actually happening?
RN's V0.46.0 Is not compatible with the antd-mobile's tab-bar component.

**Comment by silentcloud** [comment]
@alex-ling 
https://github.com/ant-design/ant-design-mobile/issues/1466
https://github.com/ant-design/ant-design-mobile/issues/1555#issuecomment-314619598

**Comment by JakimLi** [comment]
Any workaround for this?

**Comment by silentcloud** [comment]
@JakimLi please wait facebook to release react@16.0

**Comment by silentcloud** [comment]
@alex-ling @JakimLi  https://github.com/facebook/react-native/pull/15203

**Comment by silentcloud** [comment]
I have already replace `z-index` with `height` in android `tab-bar` component.
