### ISSUE TITLE
picker 联动时,可以保持其他列当前滑动的位置吗?

### ISSUE THREAD

**Issue by kiwi01** [ant-design/ant-design-mobile#1540]
### What problem does this feature solve?
用于预约取件,预约的时间有今天和明天。两天剩余的时间不同,所以在小时上是联动的,但是每小时的分钟数一样,所以在分钟上不希望联动。由于在日期上要求显示今天、明天,又没办法修改DatePicker的数据显示所以用了picker。或者说三列数据我只希望其中两列联动,

### What does the proposed API look like?
onPickerChange={this.onPickerChange}

**Comment by paranoidjk** [comment]
看不懂你的描述。

**Comment by weishijun14** [comment]
当一维数组的index 变化时， 二维数组的index不变。

**Comment by paranoidjk** [comment]
那就是不联动了。

或者你手动在回调里处理一级数组和二级数组之间index的关系
