### ISSUE TITLE
react-native customize component style

### ISSUE THREAD

**Issue by anhuiliujun** [ant-design/ant-design-mobile#1542]
### What problem does this feature solve?
I want to customize ListItem style. But when i read the document. It tell me to customize the global theme. What i want is only customize the `ListItem` style. And when i read the source code of `ListItem`. I found i can use the `style` prop and `styles` prop. So my question is: why not give us an example in the doc about how to customize it.

### What does the proposed API look like?
Customize component style. Tell us how to in the doc.

**Comment by paranoidjk** [comment]
see https://github.com/ant-design/ant-design-mobile/issues/1182

cc @silentcloud
