### ISSUE TITLE
create-react-app docment error

### ISSUE THREAD

**Issue by macmatilda** [ant-design/ant-design-mobile#1543]
### Version
1.4.1

### Environment
mac os 10.12.5，any browsers

### Reproduction link
[https://mobile.ant.design/docs/react/use-with-create-react-app-cn](https://mobile.ant.design/docs/react/use-with-create-react-app-cn)

### Steps to reproduce
https://mobile.ant.design/docs/react/use-with-create-react-app-cn
follow the doc step by step

### What is expected?
 runtime ok

### What is actually happening?
(1)
Failed to compile.

./src/index.css
Module build failed: ReferenceError: pxtorem is not defined
(2)svg not loader

---
https://mobile.ant.design/docs/react/use-with-create-react-app-cn
some issues in docment
（1）https://mobile.ant.design/docs/react/use-with-create-react-app#Import-antd-mobile
2 install devDependencies
yarn add --dev babel-plugin-import svg-sprite-loader@0.3.1 less less-loader postcss-pxtorem

babel-plugin-import has been add in before step, suggest remove

（2）https://mobile.ant.design/docs/react/use-with-create-react-app#Import-antd-mobile
3 Modify config/webpack.config.dev.js
extensions: ['.web.js', '.js', '.json', '.jsx'],

it not need change now, suggest remove

（3）https://mobile.ant.design/docs/react/use-with-create-react-app#Import-antd-mobile
3 Modify config/webpack.config.dev.js

it need add this 
const pxtorem = require('postcss-pxtorem');---------BUG

（4）svg error
-------------BUG
i think it is because it exclude .svg, i don't know why exclude it, 

rules: [
  {
    exclude: [
      ...
      /\.less$/,
      /\.svg$/,
      ...
    ]
  },
  ...

**Comment by paranoidjk** [comment]
@ant-design-bot markdown

**Comment by paranoidjk** [comment]
Please do not file duplicated issue https://github.com/ant-design/ant-design-mobile/issues/1544
