### ISSUE TITLE
create-react-app svg-loader config

### ISSUE THREAD

**Issue by macmatilda** [ant-design/ant-design-mobile#1544]
### Version
1.4.1

### Environment
all, all 

### Reproduction link
[http://new-issue.ant.design?repo=ant-design-mobile](http://new-issue.ant.design?repo=ant-design-mobile)

### Steps to reproduce
http://new-issue.ant.design?repo=ant-design-mobile
follow the doc, step by step

### What is expected?
import logo from './logo.svg';
<img src={logo} className="App-logo" alt="logo" />
            <Icon type="check"/>

both ok

### What is actually happening?
logo.svg not ok

---
svg file
1)antd svg file (like <Icon type="check"/>) expect using svg-sprite-loader
2)user svg file ./logo.svg expect using file-loader

1）antd-moble的svg 文件应该是要用 svg-sprite-loader来处理
2）用户自己的svg文件应该是用file-loader去处理

the doc set all svg file handle by svg-sprite-loader, because doc exclue .svg file
I think only exclude svg in antd-mobile is enough,

但是指导把所有的svg文件都让svg-sprite-loader处理了，指导在file-loader里面排除了svg文件，
我认为应该只要排除require.resolve('antd-mobile').replace(/warn\.js$/, '')即可

        exclude: [
......................
          /\.less$/,
          /\.svg$/,  //Bug删掉           
        ],
Change to
改成
        exclude: [
......................
          /\.less$/,
require.resolve('antd-mobile').replace(/warn\.js$/, ''),  // 1. 属于 antd-mobile 内置 svg 文件
        ],

我改成这样，工作正常
i change to this， it's works ok

**Comment by paranoidjk** [comment]
> 用户自己的svg文件应该是用file-loader去处理

- 如果你的 svg 文件是需要传给 antd-mobile `Icon` 的，你需要给 svg-sprite-loader 处理。
- 其他 svg 文件你按需自己配置就好，不要求。
