### ISSUE TITLE
InputItem中type为Phone和BankCard时候在chrome浏览器下没出现自动填入的空格光标会位移

### ISSUE THREAD

**Issue by RickyShiJs** [ant-design/ant-design-mobile#1553]
### Version
1.4.1

### Environment
Android 7.0.0; Chrome 59.0.3071.125;

### Reproduction link
[https://mobile.ant.design/components/input-item-cn/](https://mobile.ant.design/components/input-item-cn/)

### Steps to reproduce
1.打开重现页面
2.滚动到format区域
3.在手机号码中输入手机号码
4.输入第4个数字，光标错位，输入内容不正确

### What is expected?
光标应该保持位置继续正确输入

### What is actually happening?
光标错位，输入内容将错乱,不正确

**Comment by RickyShiJs** [comment]
duplicated #810

**Comment by paranoidjk** [comment]
清先测试手机浏览器是否可以复现问题

**Comment by paranoidjk** [comment]
iPhone6sp ios 10.3.2 safari 无法复现。

**Comment by paranoidjk** [comment]
@warmhug 用你的 android 机看看能否复现

**Comment by warmhug** [comment]
确实有错位问题

**Comment by lxlneo** [comment]
也有同样的问题 ，Android 下比较严重 要重新改回去了~

**Comment by warmhug** [comment]
确实有错位问题

Trace #810
