### ISSUE TITLE
react-native Popup 不支持flex: 1

### ISSUE THREAD

**Issue by wv1124** [ant-design/ant-design-mobile#1555]
Popup.show(<View style={{flex: 1, backgroundColor: 'blue'}}>
      <Text>123123</Text>
    </View>, {
      maskClosable: true,
      animationType: 'slide-up',
      onMaskClose: () =>
        new Promise(resolve => {
          setTimeout(resolve, 1000);
        })
    });

当上面flex: 0时中可以显示，flex:1  slide-up不显示， 向下弹出正常

    "react": "16.0.0-alpha.12",
    "react-dom": "16.0.0-alpha.12",
    "react-mixin": "^2.0.2",
    "react-native": "0.45.1",
    "rn-topview": "0.1.3",
    "rc-dialog": "~6.5.7",

**Comment by silentcloud** [comment]
@wv1124 目前我们只会在正式版的 react 下测试现有组件的兼容性，0.45 的 react-native 需要 react@16 alpha，所以请先使用 react@15 + react-native@0.42 试试有没有问题，0.45 下面的问题会在 react 正式发布 16 的时候去修复。

https://github.com/ant-design/ant-design-mobile/issues/1466

**Comment by silentcloud** [comment]
你这个问题跟 Popup 没关系，请先理解 flex 如何使用
