### ISSUE TITLE
Tabs组件优化

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#1556]
https://ant-design.github.io/ant-design-analysis/#antd-mobile/versions/2.0.0-alpha.1
有两点：
* Tabs组件按道理没那么复杂，现在依赖了hammerjs，光hammerjs就70k+，实在难以忍受。
* rc-tabs组件的代码实在太难看懂。目录结构，引用关系都不清晰。`preact`适配需要修复其中问题。

期望：
mobile first原则下，重写一个rmc-tabs

**Comment by paranoidjk** [comment]
> rc-tabs组件的代码实在太难看懂。目录结构，引用关系都不清晰。preact适配需要修复其中问题。

这一点不能算问题吧... 😓  rc-component 大面积用了 mixin cc @yiminghe 

> Tabs组件按道理没那么复杂，现在依赖了hammerjs，光hammerjs就70k+，实在难以忍受。


至于 hammerjs， 移动端总是需要处理滑动手势的，从 antd-mobile 整个 uikit 上层来看，底下必然要选一个手势库，@pingan1927 重写的话你有什么好的提议？

**Comment by pingan1927** [comment]
> rc-component 大面积用了 mixin

rc-tabs 不是一般的难看懂，比如我从index.js一直往下看，看了几遍都不知道为何会引用到其它文件去。

**Comment by paranoidjk** [comment]
@pingan1927 不至于吧.... 建议你先了解下 https://facebook.github.io/react/docs/react-without-es6.html#mixins

**Comment by pingan1927** [comment]
观察两个截图里，index.js文件的大小，相差43K。区别就是使用Tabs

![2](https://user-images.githubusercontent.com/347649/28053018-dadc617a-6640-11e7-95b3-f120857d7e74.png)
![default](https://user-images.githubusercontent.com/347649/28053019-dadeb7f4-6640-11e7-9218-2f9c2b2a09c1.png)

**Comment by pingan1927** [comment]
Mixin 我很清楚。

但看不懂rc-tabs里 **TabBar.js是如何被引用的。

**Comment by cncolder** [comment]
我以前用过 TabBar 后来决定自己套几层 DOM 再加上 antd-mobile 的样式。

就是一个 fixed 元素，选中的高亮就行了，不明白为什么要作为内容的父组件。

**Comment by pingan1927** [comment]
## Tabs

* 不需要keyDown事件
* 不需要ScrollableInkTabBar、ScrollableTabBar
* 移动端Tabs的TabBar设计上是不会超过固定个数的，也就不存在需要引入SwipeableInkTabBar的可能性。
* Tabs.tsx里render实现不觉得很怪吗？渲染TabBar, 需要clone 还需要把children传入，children本身dom很复杂的话，就造成了性能问题。待验证

## TabBar:
* 不需要基于Tabs开发，交互和视觉上的要求都很简单，最多要有动画效果，不需要手势支持。基于Tabs实现简直大才小用，性能又差。

还是回到Mobile First原则，最好是有一个rmc-tabs，再扩展出rc-tabs，而不是rc-tabs 包含了rmc-tabs.

**Comment by paranoidjk** [comment]
> 不需要ScrollableInkTabBar、ScrollableTabBar

这个不是问题，不需要的，antd-mobile 不会引入

> 移动端Tabs的TabBar设计上是不会超过固定个数的，也就不存在需要引入SwipeableInkTabBar的可能性。

头部可以滑动的 tabs 用的很多，我收到过很多咨询

> 不需要keyDown事件
和 rc-input-number 一样，可以做两套时间处理，MouseEvent or TouchEvent

> 还是回到Mobile First原则，最好是有一个rmc-tabs，再扩展出rc-tabs，而不是rc-tabs 包含了rmc-tabs.

这个看不懂，重做 rmc-tabs 不可能又在上扩展 rc-tabs 的

**Comment by pingan1927** [comment]
> 头部可以滑动的 tabs 用的很多，我收到过很多咨询

这个可以再找设计师确认下，如果有就继续保留。

> 这个看不懂，重做 rmc-tabs 不可能又在上扩展 rc-tabs 的

那就完全分开。

**Comment by paranoidjk** [comment]
> 头部可以滑动的 tabs 用的很多，我收到过很多咨询

这个就是内网的设计师提需求我做的，可以看 gitlab issue

**Comment by pingan1927** [comment]
嗯 那就继续支持。我刚review了下口碑新整理的交互稿，确实存在这种情况

**Comment by paranoidjk** [comment]
重做的话，
- 体积问题，抛开 hammerjs 这些依赖不谈， 在 rc-tabs 源码方面我并没有看到可以做多少精简，你要注意 antd-mobile 都是按模块引用的 rc-tabs https://github.com/ant-design/ant-design-mobile/blob/master/components/tabs/index.web.tsx#L7

**Comment by pingan1927** [comment]
参考下`framework7`的`Swipe To Delete`是没有依赖hammerjs的 实际体验非常好

**Comment by pingan1927** [comment]
## Tabs

* 不需要keyDown事件
* Tabs.tsx里render实现不觉得很怪吗？渲染TabBar, 需要clone 还需要把children传入，children本身dom很复杂的话，就造成了性能问题。（待验证）重做的话把这个方案给换掉。如上面 @cncolder 的疑问一样。
* 整个antd-mobile 目前我看下来有两个组件用到了hammerjs 一个是tabs 一个是SwipeAction，这两个组件的手势支持，是否有不需要hammerjs而自己实现最简单的手势功能的可能性？可行性有

## TabBar 

* 最早版本（antui做对应的react封装）有什么不能满足业务需求？如果满足，这样是最轻量的。

**Comment by paranoidjk** [comment]
ref https://github.com/ant-design/ant-design-mobile/issues/1287

**Comment by warmhug** [comment]
@zhang740 这里可以简要介绍下，新版 tabs 对比 老版本 的优化点，比如 体积大小、增删哪些功能等

**Comment by stonecold123** [comment]
@paranoidjk  Tabs.Pane is gone in 2.0.0-alpha.12. Can you show me how to render tabs with the new props `tab`?

**Comment by paranoidjk** [comment]
@stonecold123 

Please see http://beta.mobile.ant.design/index-cn.

And we will release the first official  `antd-mobile@2-beta`  version tomorrow.

**Comment by stonecold123** [comment]
@paranoidjk 
Thank you! The latest tabs seem to have solved the autofocus issue.

**Comment by xcyn** [comment]
tabs确实难用的一逼，禁不起机型的考验
