### ISSUE TITLE
Picker 组件在 Android 下特别卡

### ISSUE THREAD

**Issue by xwartz** [ant-design/ant-design-mobile#1559]
### Version
0.9.17

### Environment
react-native 0.37.0

### Reproduction link
[https://mobile.ant.design/components/picker-cn/](https://mobile.ant.design/components/picker-cn/)

### Steps to reproduce
Picker 组件在 Android 下滑动很卡，官方demo就可以重现。

### What is expected?
希望优化一下滑动性能

### What is actually happening?
Android 滑动卡顿

**Comment by silentcloud** [comment]
@xwartz 先升到 ~1.4 试试

**Comment by xwartz** [comment]
@silentcloud   ok，我先试试 1.4 的，0.9.17 是所有安卓设备滑动都卡

**Comment by silentcloud** [comment]
这个关掉了，我拿了一个很古老的 android 机测试（RAM 只有 512M），没问题

**Comment by cheft** [comment]
你们测试的是 web 还是 react-native , 我用 react-native 弹出来很卡，要一两秒，滑动选择也慢。手机不坚果 Pro 中端机。

**Comment by huangguozhen** [comment]
同样的问题，很卡。加载全国地区选择数据。手机 荣耀8, 中端机。

**Comment by sunzongzheng** [comment]
同卡，魅蓝X。RN新项目，应该不会是其他页面或页面其他元素导致的
