### ISSUE TITLE
Icon 支持使用 base64 / svg 图片

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#156]
移动端 iconfont 在低版本浏览器有兼容问题，需要使用 base64 替换。Icon 除了现在用 font 方式、希望再支持用 base64 图片方式

**Comment by afc163** [comment]
1. 移除现有 iconfont。
2. 图标导出三份文件。`xx.svg` `xx@2x.png` `xx@3x.png`
3. web 使用 svg。用样式 `svg { fill: @brand-primary; }`; 定义样式，方便 less 变量定制。
4. rn 使用图片，用 tintColor 进行色彩配置。

**Comment by afc163** [comment]
用 svg 来代替 iconfont，方便修改样式。

rn 用图片。

**Comment by afc163** [comment]
图标按这种方式搞一下，我只放了一个 search 图标。

```css
&-search {
  background-image: url("./assets/search.svg");
}
``

- https://github.com/ant-design/ant-design-mobile/blob/svg-icon/components/icon/style/index.less#L16-L18
https://github.com/ant-design/ant-design-mobile/tree/svg-icon/components/icon

@warmhug @liqi07

**Comment by warmhug** [comment]
svg 兼容性怎么样？

**Comment by afc163** [comment]
不知道，你得找 iconfont 不行的机器先试试。

**Comment by afc163** [comment]
iconfont 应该比 svg 的兼容性更好，weui 用的也是 iconfont，不同的地方是它把 iconfont 直接内联进来了。

https://res.wx.qq.com/open/libs/weui/0.4.3/weui.css

> 移动端 iconfont 在低版本浏览器有兼容问题

@warmhug 这里是否是网络的问题？

**Comment by afc163** [comment]
https://io-meter.com/2014/07/20/replace-icon-fonts-with-svg/

**Comment by afc163** [comment]
两种方式：

1. base64 的 iconfont
2. svg symbols

**Comment by afc163** [comment]
https://dmfrancisco.github.io/react-icons/

**Comment by SMbey0nd** [comment]
iconfont 在前两年，Android 上的问题非常多，很多 case 跟网络加载确实有关系，在加载过程中图标 icon 会变形或出现乱码之类的情况。内联进去是否能解决这个问题不太好说。

svg 我们一年前有过实践，整体感觉兼容性比 iconfont 要好。当时在测试机房里批量测试过，所以心里有底一些。业务上考虑的话可能会首选 svg 稳妥一点。

**Comment by warmhug** [comment]
@liqi07 尽量这周做完？支持 svg（base64 比较简单、只要有png 源文件即可、工具会自动处理成 base64）

**Comment by warmhug** [comment]
done
