### ISSUE TITLE
I got a big proble when I use Toast !

### ISSUE THREAD

**Issue by cielu** [ant-design/ant-design-mobile#1562]
### Version
1.4.2

### Environment
react-native@0.44.3 & react-navigation@1.0beta.11

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/tree/master/components/toast](https://github.com/ant-design/ant-design-mobile/tree/master/components/toast)

### Steps to reproduce
As the document show , the mask default value is true , and I don't set any value of it . But when i use Toast.loading('xxxx'),the top's button could be clicked ,though the middle and bottom part can't be click

使用toast的时候，虽然有膜层，但是顶部还是可以被点击，顶部以下不能被点击！

### What is expected?
The whole screen can't be clicked when I use Toast;

全屏幕都不能点击

### What is actually happening?
The top of screen could be clicked , but other parts not
顶部（导航）可以被点击，其他部分不能点击

**Comment by cielu** [comment]
another proble is the duration is not normally , sometimes Toast can show as I set the time ,but sometimes it just show 1 sec .

toast显示时间有问题，比如我设置了30秒，但是有时候1秒都没得，闪一下就没了。。。

**Comment by cielu** [comment]
import React, { Component } from 'react'
import {
    View,
    Image,
    Text,
    Alert,
    Platform,
    Dimensions,
    StyleSheet,
    TextInput,
    TouchableOpacity,
} from 'react-native'
import { Toast} from 'antd-mobile';
import Icon from 'react-native-vector-icons/Ionicons'
import ImagePicker from 'react-native-image-crop-picker'
import fetchRequest from '../../util/fetchRequest' 

const PhoneWidth = Dimensions.get('window').width
const options = {
    mediaType: 'photo',
    videoQuality: 'high',
    durationLimit: 10,
    aspectX: 2,
    aspectY: 1,
    angle: 0,
    allowsEditing: false,
    noData: false,
}

export default class CircleTopicScreen extends React.PureComponent {

    static navigationOptions = ({navigation, screenProps}) => ({
        headerTitle: 'Hey圈',
        // headerTitleStyle: {paddingLeft: Platform.OS === 'ios' ? 0 : 44},
        headerRight: <TouchableOpacity style={{flexDirection: 'row'}} onPress={() => {navigation.state.params.commitData()}}>
                        <Text style={{color:'#0086E5', fontSize: 15, marginRight: 12}}>发表</Text>
                    </TouchableOpacity>,
    })

    componentDidMount () {
        this.props.navigation.setParams({
            commitData:this.commitData,
        })
    }

    constructor (props) {
        super(props)
        this.state = {
            moment: '',
            images: [],
        }
    }

    render () {
        return (
            <View style={styles.container}>
                <TextInput
                    multiline={true}
                    maxLength={1000}
                    autoFocus={true}
                    numberOfLines={10}
                    style={styles.textInput}
                    underlineColorAndroid="transparent"
                    placeholder="说点什么..."
                    placeholderTextColor="#ccc"
                    onChangeText={(moment) => this.setState({moment})}
                    value={this.state.moment}
                />
                <View style={{alignItems:'flex-end'}}>
                    <Text style={{color:'#ccc'}}>({this.state.moment.length}/1000)</Text>
                </View>
                <View style={styles.imageList}>
                    {this.state.images ? this.state.images.map((i, index) => <View
                        key={index}>{this.renderImg(i, index)}</View>) : null}
                    <TouchableOpacity activeOpacity={0.88} style={styles.selectImage}
                                      onPress={() => {this.chooseImage()}}>
                        <Icon name="md-camera" size={30} color="#cdcdcd"/>
                    </TouchableOpacity>
                </View>
            </View>
        )
    }

    renderImg (i, index) {
        let images = this.state.images
        return (
            <Image style={styles.imagePreview} source={i}>
                <TouchableOpacity style={styles.IconStyle} onPress={() => {
                    this.setState({images: images.slice(0, index).concat(images.slice(index + 1, images.length))})
                }}>
                    <Icon name="ios-close" size={22} color="#fff"/>
                </TouchableOpacity>
            </Image>
        )
    }

    chooseImage () {
        if(this.state.images.length >= 6){
            Toast.info('最多只能选择6张图片!');
            return ;
        }
        let dataToPost = []
        if (Platform.OS === 'ios') {
            ImagePicker.openPicker({
                options
            }).then(images => {
                for (var i = 0; i < images.length; i++) {
                    dataToPost.push({
                        uri: images[i].path,
                        width: images[i].width,
                        height: images[i].height,
                        mime: images[i].mime,
                    })
                }
                this.setState({
                    images: this.state.images.concat(dataToPost)
                })

            }).catch(e =>
                Toast.fail(e.message?e.message:e)
            )

        } else {
            ImagePicker.openPicker({
                options
            }).then(image => {
                dataToPost.push({
                    uri: image.path,
                    width: image.width,
                    height: image.height,
                    mime: image.mime
                })
                this.setState({
                    images: this.state.images.concat(dataToPost)
                })
            }).catch(e => {
                Toast.fail(e.message?e.message:e)
            })
        }
    }
    
    //数据提交
    commitData = () => {
        const {navigation} = this.props ;
        if(!this.state.moment && !this.state.images.length || this.state.moment.length > 1000){
            Toast.info('先写点什么再发表吧！',1)
            return false;
        }
        Toast.loading('发表中...',30);
        const formData = new FormData();
        if (this.state.images) {
            this.state.images.map((img,i) => {
                let index = img.uri.lastIndexOf('\/')
                let name = img.uri.substring(index + 1, img.uri.length)
                formData.append('picture['+i+']', {uri: img.uri, type:'image/jpeg', name: escape(name)})
            })
        }
        formData.append('moment', this.state.moment)
        //提交表单
        fetchRequest('/moment', 'POST', formData,'multipart/form-data').then(res => {
            //请求成功
            if(res.status){
                Toast.success('发表成功',1)
                navigation.goBack(null)
            }else{
                Toast.fail(res.msg,1)
            }
        }).catch(err => {
            //请求失败
            Toast.fail('网络出错',1);
        })

    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 15,
        paddingTop:Platform.OS === 'ios' ? 10 : 5,
        backgroundColor: '#fff',
    },
    textInput: {
        height: 150,
        fontSize: 15,
        textAlignVertical: 'top'
    },
    imageList: {
        paddingTop: 20,
        flexWrap: 'wrap',
        flexDirection: 'row',
    },
    imagePreview: {
        height: (PhoneWidth - 50) / 4,
        width: (PhoneWidth - 50) / 4,
        alignItems: 'flex-end',
        margin: 2,
    },
    IconStyle: {
        backgroundColor: 'rgba(88,88,88,.7)',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        width: 20,
        height: 20,
    },
    selectImage: {
        height: (PhoneWidth - 50) / 4,
        width: (PhoneWidth - 50) / 4,
        justifyContent: 'center',
        alignItems: 'center',
        borderStyle: 'dashed',
        borderColor: '#cdcdcd',
        borderWidth: 1,
        margin: 2,
    },
})

**Comment by cielu** [comment]
this my source code ,  just replace the fetchRequest with fetch methed ,or delete it . 

you can run it base react-navigation . and you will find zhe top button could be clicked when toasting.

这个是我那个页面的源代码，你发的那个我不会用。
我觉得出现这个情况，究其根本还是react-navigation惹的货，导航栏的返回与发表按钮都是基于react-navigation的，但是使用toast的时候，确实还可以点击。。。

然后toast出现秒退的情况我不太清楚具体是怎么导致的，这个是偶尔的情况。。

 if I got these problems again , i'll show the detail step

**Comment by paranoidjk** [comment]
@ant-design-bot markdown

**Comment by paranoidjk** [comment]
@silentcloud 导航栏可以做到禁止点击么？


> toast显示时间有问题，比如我设置了30秒，但是有时候1秒都没得，闪一下就没了。。。

@cielu 请提供可复现 demo

**Comment by cielu** [comment]
一会儿录个gif传上来

**Comment by cielu** [comment]
[看这个视频](http://ofw9hx11l.bkt.clouddn.com/QQ20170713-150543.mp4)

**Comment by cielu** [comment]
那个toast闪退的是偶然情况，我不知道什么时候会出现，到时候也可以录个视频

**Comment by paranoidjk** [comment]
toast 你无法稳定复现就没法排查了

> 我觉得出现这个情况，究其根本还是react-navigation惹的货，导航栏的返回与发表按钮都是基于react-navigation的，但是使用toast的时候，确实还可以点击。。。

这个你自己也说了，请自己探索怎样禁用 react-navigation

**Comment by zhouzefei** [comment]
为什么不提供可操作的隐藏，现在好像只支持定时操作

**Comment by silentcloud** [comment]
@zhouzefei `Toast.hide()` 文档最后面有说的啊

**Comment by silentcloud** [comment]
@cielu toast 显示的时候，用户可以返回，这事理所当然的交互方式，能禁止用户点击页面的操作，但是不应该去禁止用户去返回，万一用户是进错了页面，还得得 toast time 才能返回回去

**Comment by cielu** [comment]
@silentcloud  这个toast 不纠结了咯，我发现好像还有很多问题哦，这个组件。。

我在使用 inputItem的时候，居然不能自定义字体大小。。。纠结啊。。。整个字体太大了。。。

**Comment by silentcloud** [comment]
@cielu 可以自定义的

1.x https://github.com/ant-design/ant-design-mobile/issues/1174
2.0 https://github.com/ant-design/ant-design-mobile/pull/1629

**Comment by cielu** [comment]
给styles属性，整个之前的样式都没了。。等于需要重写。。。

**Comment by cielu** [comment]
@silentcloud  没反应哦
![image](https://user-images.githubusercontent.com/13715811/29054801-f6754366-7c2a-11e7-9c2b-b7f8109abd5e.png)
![image](https://user-images.githubusercontent.com/13715811/29054810-040c470e-7c2b-11e7-88f9-b9ad3918e08f.png)
我是不是n哪里写错了。。。

**Comment by silentcloud** [comment]
@cielu 已经给你贴例子了，另一个 issue 里
