### ISSUE TITLE
navbar不能修改背景颜色

### ISSUE THREAD

**Issue by Yangzhedi** [ant-design/ant-design-mobile#1563]
### What problem does this feature solve?
可以让navbar组件更加定制化

### What does the proposed API look like?
现在的Navbar组件 只能选择两个mode dark下还只能是天蓝色。希望可以手动设置颜色

**Comment by paranoidjk** [comment]
`mode/dark` 不仅改变背景色，还改变文字颜色，所以这两个其实是两套预设的主题。

你的需求，可以通过 `props.className` 添加你自己的类名，从而应用自定义样式。
