### ISSUE TITLE
Unable to get babel-plugin-import to work when scripts are compiled from typescript (Android)

### ISSUE THREAD

**Issue by stonecold123** [ant-design/ant-design-mobile#1564]
### Version
1.4.2

### Environment
react-native

### Reproduction link
[https://github.com/stonecold123/antd-mobile-test-ts](https://github.com/stonecold123/antd-mobile-test-ts)

### Steps to reproduce
$ git clone https://github.com/stonecold123/antd-mobile-test-ts
$ npm install
$ npm start
$ react-native run-android 

### What is expected?
I've made two examples for android only, one written in raw js (run fine), and one written in typescript (not working):
https://github.com/stonecold123/antd-mobile-test-js
https://github.com/stonecold123/antd-mobile-test-ts

I was expecting the typescript example  to work perfectly without the console.error "Must use babel-plugin-import...." and render successfully like the first one which is written in JS. Both examples use the latest react native and react version.

### What is actually happening?
Can you please try this example:
https://github.com/stonecold123/antd-mobile-test-ts

I'm still getting the  "Must use babel-import...."  error even though the .babelrc file has updated to :
````
{
  "presets": ["react-native"],
  "plugins": [["import", { "libraryName": "antd-mobile" }]]
}
````
I suspect there's an issue related to babel-plugin-import when the ts example is compiled back into raw javascript. I have spent hours on it but still can't find a solution.

**Comment by paranoidjk** [comment]
Have you tried our [offcial react-native-demo](https://github.com/ant-design/antd-mobile-samples/tree/master/react-native)?

**Comment by stonecold123** [comment]
@paranoidjk 
I use typescript to write scripts then compile it back to javascript.
But the demo doesn't seem to use typescript

**Comment by paranoidjk** [comment]
You may want to look at [this](https://github.com/ant-design/ant-design-mobile/blob/master/.babelrc), which is the react-native babelrc config of our souce code.

I remember there do have some problems with babel + typescript + react-native-cli, cc @silentcloud  may give some explanation.

**Comment by stonecold123** [comment]
@paranoidjk 
Here's the compiled component 

````
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var react_navigation_1 = require("react-navigation");
var TestScreen_1 = require("./TestScreen");
var stack = react_navigation_1.StackNavigator({
    "Home": {
        screen: TestScreen_1.TestScreen,
    },
}, {
    initialRouteName: "Home",
    cardStyle: { backgroundColor: 'transparent' }
});
exports.Router = react_navigation_1.DrawerNavigator({
    Drawer22: {
        screen: stack
    }
});
````
Does it look fine to you?

**Comment by cncolder** [comment]
@stonecold123 Change your `tsconfig.json` tell tsc compile to es2015. `babel-plubin-import` only understand `import` style code.

```json
{
    "compilerOptions": {
        "module": "es2015"
    }
}
```

**Comment by stonecold123** [comment]
@cncolder 
Thanks! It works!

**Comment by stonecold123** [comment]
@cncolder , @paranoidjk 
There is a problem. I have a script that imports some common modules like this:

    import * as axios from "axios";
    import * as URIJS from "urijs"; 

If I change the module to `es2015`, these two imports would actually import the entire object, not the class! For example,  when I run 
`let uri = new URIJS("someurl")`

it will throw this error: 

    TypeError: URIJS is not a constructor

Is there any solution?

**Comment by cncolder** [comment]
@stonecold123 Change your `tsconfig.json` again

```json
{
    "compilerOptions": {
        "module": "es2015",
        "allowSyntheticDefaultImports": true
    }
}
```

Then write `import URIJS from 'urijs'` in your `.ts` file.
