### ISSUE TITLE
Remove hammerjs

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1565]
- [x] rc-tabs https://github.com/react-component/m-tabs
- [ ] rc-swipeout https://github.com/react-component/swipeout/pull/43

we just need horizontal  swipe ，but hammerjs gzip size is 7.34 kb.

cc @pingan1927 @warmhug @yiminghe  @silentcloud

**Comment by cncolder** [comment]
+1 hammer is too heavy.

**Comment by paranoidjk** [comment]
Released `rc-gesture@0.0.1`, 目的是用少的代码支持Hammerjs的大部分功能 https://react-component.github.io/gesture/examples/simple.html

**Comment by paranoidjk** [comment]
webpack 太可怕了，几百行代码 compile 之后竟然和几千行的 hammerjs 差不多大
https://unpkg.com/rc-gesture@0.0.2/ 插入了一堆模块的包裹代码

等待尝试三个方案：
- 不再经 webpack 打包，用 rollup
- webpack 3 scope hoisting
- rc-gesture 本身按手势模块化，按需加载

**Comment by paranoidjk** [comment]
ref https://github.com/react-component/rc-tools/issues/37
