### ISSUE TITLE
SearchBar.showCancelButton support auto/never/always

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1569]
## Proposal API
`SearchBar.showCancelButton`: `enum{auto, never, always}`
- `auto`: equal to right now `showCancelButton = false`, show in focus, hide in blur
- `never`: never show cancel button
- `always`: equal to right now `showCancelButton = true`, always keep display

**Comment by paranoidjk** [comment]
cc @shepherdwind

**Comment by warmhug** [comment]
这样的 API 有点复杂、尽量避免。never 这个情况、使用场景少的话、用户自己设置`display: none;`覆盖样式即可

**Comment by paranoidjk** [comment]
> never 这个情况、使用场景少的话、用户自己设置display: none;覆盖样式即可

覆盖样式的方法是最下下之选，考虑长远的维护性。

我的意见，API 设计复杂的话可以考虑怎么简化。

**Comment by paranoidjk** [comment]
这个我觉得其实也不复杂，类似于 `DatePicker.mode`

**Comment by paranoidjk** [comment]
cc @benjycui 变量命名专家给点意见 😄

**Comment by silentcloud** [comment]
别搞这么复杂吧，参考一下 iOS UISearchBar

https://developer.apple.com/documentation/uikit/uisearchbar?language=objc

https://developer.apple.com/documentation/uikit/uisearchbar/1624283-showscancelbutton?language=objc

**Comment by paranoidjk** [comment]
@silentcloud `showCancelButton: boolean` 满足不了这三个场景，还是你说哪一种场景不需要？

**Comment by pingan1927** [comment]
never: never show cancel button

一般不用，用的话直接css隐藏掉

**Comment by silentcloud** [comment]
我的意思就是说，不需要做这样的改造，就 show or hide 就行了

**Comment by paranoidjk** [comment]
主要是现在的 showCancelButton: boolean 满足不了想隐藏的场景。

@pingan1927 这里有个 js 动画，css 隐藏不太好

@silentcloud show or hide, 那 show 是对应目前 showCancelButton： boolean true 还是 false 呢？总是少一种场景的

**Comment by silentcloud** [comment]
<img src="https://user-images.githubusercontent.com/1698185/29594894-ba7b9b7c-87e6-11e7-96b0-ff480e5a1547.gif" width="240" />
<img src="https://user-images.githubusercontent.com/1698185/29594895-bc612b32-87e6-11e7-8201-911da420eeae.gif" width="240" />

我截了native 的交互形式，可以参照一下，我觉得这两种就够了，后面有人提需求了再说吧
有个细节，show 的时候，cancel 是灰的，focus 的时候才亮 

@paranoidjk

**Comment by paranoidjk** [comment]
@silentcloud 你的意思是去掉自动显示的那一种？

**Comment by silentcloud** [comment]
我记得不是有谁提个 issue 说那个动画性能差还是什么来着的？现在有的话，那就还是保留吧

我的截图只是个 交互方式参考

**Comment by paranoidjk** [comment]
close.

Suggest user use:

```css
.am-search-cancel {
  display: none;
}
```
