### ISSUE TITLE
Remove default background-color in components/style/index.less

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1570]
在 tiny ide 里，测试提了个 bug 就是跟这个有关，目前 ide 里有些组件， index.less 里的默认 background-color 覆盖了 window 下面定义的 backgroundColor；

目前临时解决方案是在 tiny 里内置的 html 里覆盖这个样式，但是感觉多了这么个处理，不是太好

**Comment by paranoidjk** [comment]
可以改 theme 变量？https://github.com/ant-design/ant-design-mobile/blob/master/components/style/index.less#L20

抄下设计师同学讨论下把

**Comment by silentcloud** [comment]
@paranoidjk tiny 里没办法

**Comment by paranoidjk** [comment]
> tiny-app 里没办法改 theme

@silentcloud 那应该会遇到很多类似的问题吧？

**Comment by silentcloud** [comment]
closed  for tiny native can not support
