### ISSUE TITLE
Can you provide a component which will not cover the ListView?

### ISSUE THREAD

**Issue by leonardgithub** [ant-design/ant-design-mobile#1571]
### What problem does this feature solve?
能否提供一个UI组件，类似actionSheet的，也是固定在底部，但是不会遮挡ListView，显示的时候把ListView推上去，隐藏的时候还原。有点类似输入法面板不遮挡输入区域的情况。

### What does the proposed API look like?
none

**Comment by cncolder** [comment]
看起来像是纵向的 Drawer

**Comment by leonardgithub** [comment]
@ant-design-bot This is a feature request!

**Comment by warmhug** [comment]
比较特殊，建议自己实现吧
