### ISSUE TITLE
DatePicker 12 hour am/pm format?

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design-mobile#1578]
### What problem does this feature solve?
Common to use 12 hour am/pm format in the US, rather than military time.

### What does the proposed API look like?
Either allow to pass in hh to the format, or have a prop (like antd web) 12hour={true}

**Comment by SpringsTea** [comment]
Doesn't appear to be working for me. 

`<DatePicker 
   showTime
   use12Hours = {true}
   allowClear={false}
   format="YYYY-MM-DD HH:mm"
   defaultValue={ moment(value) } 
   onChange={handleChange}/>`

Still showing 24 hour time

**Comment by yingdongzhang** [comment]
@SpringsTea  are you using React Native? It only works on web. https://mobile.ant.design/components/date-picker/

**Comment by SpringsTea** [comment]
Ah I see. For anyone else who gets stuck here, after digging through some doc I found something that mentioned that setting showTime to an object will be passed to the TimePicker, so you can make it work like this:

````
<DatePicker  
   showTime = {{ user12hours: true }} 
   allowClear={false}  
   format="YYYY-MM-DD HH:mm"  
   defaultValue={ moment(value) }   
   onChange={handleChange}/>

**Comment by developdeez** [comment]
Has anyone figured this out the method proposed by @SpringsTea doesn't work.

**Comment by developdeez** [comment]
I was able to get the 12 hour working using this but I can't get rid of the seconds...
```
 <DatePicker
                  showTime={{ use12Hours: true }}
                  format="YYYY-MM-DD HH:mm a"
                />
```

**Comment by flaviotsf** [comment]
@developdeez - this worked to format the time without seconds. Basically pass the format option to showTime as well:

```
  <DatePicker
              onChange={this.handleTimeChange}
              showTime={{ use12Hours: true, format: "HH:mm a" }}
              format="YYYY-MM-DD HH:mm a"
              value={this.props.socialEvent.eventDate}
            />
```

**Comment by chefThomas** [comment]
Interface directly with Moment object using format(). Docs [here](url).

`moment.format('HH:mm a')`

**Comment by sahilpaudel** [comment]
```
 <DatePicker
            className={styles.edit_start_time}
            format="DD-MM-YYYY HH:mm A"
            showTime={{ use12Hours: true, format: "HH:mm A" }}
            onChange={onChange} onOk={onOk} />
```

This one works but if I select time for PM it goes beyond 12h as `20-03-2021 15:58 PM` but I want it to be 20-03-2021 03:58 PM

**Comment by shubhankar30** [comment]
> ```
>  <DatePicker
>             className={styles.edit_start_time}
>             format="DD-MM-YYYY HH:mm A"
>             showTime={{ use12Hours: true, format: "HH:mm A" }}
>             onChange={onChange} onOk={onOk} />
> ```
> 
> This one works but if I select time for PM it goes beyond 12h as `20-03-2021 15:58 PM` but I want it to be 20-03-2021 03:58 PM

Use hh instead of HH

**Comment by rizkimcitra** [comment]
Hi, Im facing this problem right now, and the showTime props has gone in current version, how can I use 12 hour version?

**Comment by abdukadirov** [comment]
> Doesn't appear to be working for me.
> 
> ```
> <DatePicker  
>    showTime  
>    use12Hours = {true} 
>    allowClear={false}  
>    format="YYYY-MM-DD HH:mm"  
>    defaultValue={ moment(value) }   
>    onChange={handleChange}/>
> ```
> 
> Still showing 24 hour time

Hi, my friend, you don't need to use `use12Hours` in order to get 12 hours, you should just change the format `format="YYYY-MM-DD HH:mm"  ` to `format="YYYY-MM-DD hh:mm"  `, `HH` gives 24hours `hh` provides 12hours, I hope, I'm able to give you a solution
