### ISSUE TITLE
Ability to style Picker's extra/value on react-native

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design-mobile#1579]
### What problem does this feature solve?
Many times the selected value from the Picker needs more room than half the input (i.e. more room than the "extra" area). In my case, my form labels sit above the input, so I have a lot of extra room inside of the input, but the selected value is only showing on one-half of the input, and it's truncated.

![screen shot 2017-07-19 at 11 48 22 am](https://user-images.githubusercontent.com/12701635/28376763-f4829dfe-6c78-11e7-9383-9f5d6c1ddb4d.png)

I'm using Expo for this react-native app, so I am not sure I can do a custom npm script to provide my own styling (as is suggested in the docs for changing global styles in react-native).

### What does the proposed API look like?
Maybe a prop to set the columns for Title vs. Extra areas? or ability to pass in a style prop. Or maybe there's a simple way to solve this that I'm not thinking of or isn't in the docs examples.

**Comment by acomito** [comment]
@paranoidjk please let me know if I can clarify or help with this at all

**Comment by silentcloud** [comment]
@acomito 

![image](https://user-images.githubusercontent.com/1698185/28651818-b863ea3c-72b6-11e7-92d8-87a2fda6f267.png)

**Comment by paranoidjk** [comment]
@acomito Please aware that we recommend you use `List.Item` as `Picker` children element, so the `props.extra` is  actually for `List.Iem.props.extra`, so you should see List api doc https://mobile.ant.design/components/list#List.Item.

**Comment by acomito** [comment]
I maybe misread the documents. Thanks for taking the time out to respond @paranoidjk.
