### ISSUE TITLE
6-bit password component

### ISSUE THREAD

**Issue by rdmclin2** [ant-design/ant-design-mobile#1580]
### What problem does this feature solve?
For 6-bit short password input, such as bank password, 6-bit password input box is provided.

### What does the proposed API look like?
After the introduction of components, you can set the number of password frame, such as 6. Users enter the password with a black dot. After the input is completed, a complete event is triggered to  facilitate the request to verify the password.

![image](https://user-images.githubusercontent.com/4705237/28399666-1afd9506-6d41-11e7-8c6b-0b084b44dfda.png)

**Comment by paranoidjk** [comment]
![image](https://user-images.githubusercontent.com/7971415/28399752-83bfeea4-6d41-11e7-807b-20be302b5119.png)

**Comment by warmhug** [comment]
这个内部业务已经做过了、都在业务组件里，优先级先放低吧。
增加组件要找设计师一起讨论后再定。

**Comment by rdmclin2** [comment]
虽然之前做过了，但并没有基于React的实现，在基于React的项目中无法直接使用，这种短密码也是一种常见的业务组件了。

**Comment by warmhug** [comment]
有基于 react 实现的，钉钉里 @然则 来问下

**Comment by paranoidjk** [comment]
@warmhug 

有基于 react 的实现更好，等设计师那边提供好设计稿，我们可以作为 antd-mobile@2.0 的新增组件。

**Comment by jaune001** [comment]
type="idCard"，需要实现4位4位分隔，并可输入"X"字符

**Comment by weishijun14** [comment]
这个东西急需。。

**Comment by paranoidjk** [comment]
先关闭 @peter0011 评估下，有这个需求和设计的话，我们再打开。
