### ISSUE TITLE
ImagePicker does not have the function of camera

### ISSUE THREAD

**Issue by chebysheph** [ant-design/ant-design-mobile#1581]
### What problem does this feature solve?
if ImagePicker has camera function, like an icon of camera, when I click this icon, my app will open the camera on my phone to take photos, and add in the ImagePicker Component, instead of open the photograph of my phone.

### What does the proposed API look like?
I hope the ImagePicker Component can both open the photograph of my phone to add photos, and open the camera on my phone to take photos then add.

**Comment by benjycui** [comment]
It works fine now:

![image](https://user-images.githubusercontent.com/3580607/28407468-d19c3c20-6d66-11e7-8eeb-5b411c221734.png)

**Comment by paranoidjk** [comment]
It's just pure `input type="file"`, see [@link](https://github.com/ant-design/ant-design-mobile/blob/master/components/image-picker/index.web.tsx#L183)

If your device have problems,  you may want to use `onAddImageClick` to custom your image select way. see https://mobile.ant.design/components/image-picker#components-image-picker-demo-custom

**Comment by chebysheph** [comment]
But on my phone the component open without camera,like this picture,android system,open with wechat
[http://img.blog.csdn.net/20170720170919983?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvY2hlYnlzaGVwaA==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center](url)

**Comment by chebysheph** [comment]
like this , without camera. [http://img.blog.csdn.net/20170720170919983?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvY2hlYnlzaGVwaA==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center](url)

**Comment by paranoidjk** [comment]
@chebysheph antd-mobile have no way to control the browser behavior, I suggest you write a pure html file with `input type="file"`, and test it on your browser.

**Comment by chebysheph** [comment]
@paranoidjk I just scan the QR code on [https://mobile.ant.design/components/image-picker-cn/](url) and open with wechat, I did not write any of codes.

**Comment by paranoidjk** [comment]
Let me make myself clear again, this is browser problem, eg: https://segmentfault.com/q/1010000003833785

**Comment by paranoidjk** [comment]
If you want it to work cross browser, you may need cooperation  with webview and native staff.

eg: https://huang.sh/2017/03/iosandroid%E7%9A%84webview%E4%B8%AD%E7%94%A8file-input%E6%94%AF%E6%8C%81%E6%8B%8D%E7%85%A7%E6%88%96%E9%80%89%E6%8B%A9%E7%9B%B8%E5%86%8C%E7%9A%84%E7%85%A7%E7%89%87/

**Comment by Pysics** [comment]
It not works on Android WeChat builtin browser. Multiple mode not works, too.

**Comment by sOm2y** [comment]
hey @paranoidjk, just wondering how do you get camera open on CRNA, by the default from the code example it only shows photo library option.
`   <ImagePicker
          files={images}
          onChange={this.onChange}
          onImageClick={(index, fs) => console.log(index, fs)}
          selectable={images.length < 5}
          multiple={true}
        />`
