### ISSUE TITLE
TabBar组件，icon是否可以在左侧，菜单文字在右侧

### ISSUE THREAD

**Issue by crastyle** [ant-design/ant-design-mobile#1582]
### What problem does this feature solve?
我知道很奇葩，但是我们的app是为了老年人设计的。

### What does the proposed API look like?
TabBar.Item 我不想让icon在上面文字在下面，我想要icon在左面，文字在右边，请问可以实现吗。

**Comment by paranoidjk** [comment]
不支持，你可以尝试覆盖样式。
