### ISSUE TITLE
存在body滚动条的时候，无法实现滚动到顶部在下拉刷新

### ISSUE THREAD

**Issue by sujie056520** [ant-design/ant-design-mobile#1588]
### Version
1.4.2

### Environment
Google Chrome 57.0.2987.133

### Reproduction link
[https://mobile.ant.design/components/refresh-control-cn/](https://mobile.ant.design/components/refresh-control-cn/)

### Steps to reproduce
官方例子也有这个问题

### What is expected?
先触发body滚动条到顶部或者底部，然后在实现listviwe滚动

### What is actually happening?
在listview使用touch事件，无法触发body滚动条滚动

**Comment by paranoidjk** [comment]
没有理解你的意思。

请描述清楚一点，或者提供截图，gif, 代码 demo 等更清晰的信息。

**Comment by sujie056520** [comment]
![savxrupce4q48la6j598n w](https://user-images.githubusercontent.com/24262471/28452620-190bab1c-6e26-11e7-9879-15f34c4c9e10.png)
应该是滚动条滚动在最上面再实现下拉刷新

**Comment by sujie056520** [comment]
![11](https://user-images.githubusercontent.com/24262471/28452706-846befc0-6e26-11e7-93ee-74ab5bd5d053.png)
这样就会存在永远回不到页面的最顶端

**Comment by sujie056520** [comment]
@paranoidjk 不知道你懂我的意思没有，使用refreshControl就要使用useZscroller，使用useZscroller touch事件就会触发在listview上，而不会触发到外面的滚动条事件。我理解对吗？

**Comment by paranoidjk** [comment]
@sujie056520 不要看 PC，请看真机，外面的滚动条是不应该存在的。

**Comment by sujie056520** [comment]
@paranoidjk 我把页面分享到了手机上，也存在这个问题，真机指的是app吗？

**Comment by paranoidjk** [comment]
@sujie056520 就是只手机浏览器，我 iPhone6sp safari 测试没问题。

并不懂你说的无法滚动到最顶部，请注意 ListView 是被指定了一个局部的滚动容器的，所以你手指在离开容器之外滚动，就是滚动整个页面。

**Comment by sujie056520** [comment]
![2222](https://user-images.githubusercontent.com/24262471/28453604-9725f134-6e2a-11e7-9d21-147c3a243646.jpg)
难道我需要滚动最上面的部分才能把头部拉下来吗？

**Comment by sujie056520** [comment]
@paranoidjk

**Comment by sujie056520** [comment]
@paranoidjk 如果上面头部超出页面，我怎么拉下来？

**Comment by sujie056520** [comment]
@paranoidjk 我想你们应该可以提供滚动到最顶部在实现下拉刷新的解决方法，目前我没有找到，我用事件捕获机制也没有能实现成功

**Comment by paranoidjk** [comment]
@sujie056520 你既然用了局部滚动，那我理解页面顶部非 listview 的区域你是可以想办法禁止滚动的，比如 e.preventDefault, 比如控制 listview + 头部 的总高度不超出屏幕，这样页面本身不可以上下滑动的。

**Comment by sujie056520** [comment]
@paranoidjk 你说的也是一种解决方案，但是这样做，头部信息不就是永远固定了吗？如果头部内容过多体验效果就不美观了

**Comment by sujie056520** [comment]
@paranoidjk 现在可以提供一种像支付宝一样，滚动到顶部再实现下拉刷新的方案吗，而不是固定头部？我想很多人都会有这个需求？

**Comment by paranoidjk** [comment]
并不懂你的场景，有局部滚动的情况下，头部肯定是要固定的，支付宝首页的头部也是固定的，下拉刷新的是下面的 feeds 流，相当于我们的 ListView。

**Comment by sujie056520** [comment]
@paranoidjk 例如像[](https://m.baidu.com/?from=844b&vit=fps&normalload=1)这是百度的手机端，场景一样，页面不在最顶端实现页面滚动，页面达到最顶端实现下拉刷新

**Comment by sujie056520** [comment]
@paranoidjk https://m.baidu.com/?from=844b&vit=fps&normalload=1

**Comment by paranoidjk** [comment]
@sujie056520 ok, 理解了。

@warmhug 看下百度 h5 首页的滑动效果，体验很好。

**Comment by landmass** [comment]
@sujie056520 Have you solved your problem? Can you provide a solution if it's solved?
