### ISSUE TITLE
antm定制主题

### ISSUE THREAD

**Issue by carlos121493** [ant-design/ant-design-mobile#159]
能否像antd一样可以自定义主题？
https://github.com/ant-design/antd-init/tree/c0bde69268b528de4bf137e918dc7df9f339101d/examples/customize-antd-theme
而不是都用prefixCls这种方案？

#### 本地环境

- antd-mobile 版本：0.7.8
- 操作系统及其版本：mac
- 浏览器及其版本：chrome

**Comment by warmhug** [comment]
也同样支持的

**Comment by carlos121493** [comment]
新建一个主题，要引入哪几个less？
像antd引入的是这几个
```
@import "~antd/lib/style/themes/default.less";
@import "your-theme-file"; // 用于覆盖上面定义的变量
@import "~antd/lib/style/core/index.less";
@import "~antd/lib/style/components.less";
```
我试了antm的几个都不行，打开node_modules里看试了几个也不想

**Comment by warmhug** [comment]
等下午发布 antd-mobile@0.8.0 ，再试试。不要用 antm 了。
