### ISSUE TITLE
can't make it work with expo XDE

### ISSUE THREAD

**Issue by j2l** [ant-design/ant-design-mobile#1592]
got an error:
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.

Check your code at registerRootComponent.js:24.
    in ExponentRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:132)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:132)
    in View (at AppContainer.js:97)
    in AppContainer (at renderApplication.js:34)

**Comment by j2l** [comment]
Keep it this way to keep users away.

**Comment by paranoidjk** [comment]
code: https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo
demo: https://expo.io/@silentcloud/antd-mobile

**Comment by acomito** [comment]
@paranoidjk is there anyway to customize the theme with expo? It seems we don't get as much access to customize each component in react-native (no way to add a class or get to stylesheets). I'm not sure we can use npm scripts with expo?

**Comment by paranoidjk** [comment]
1. You can use `theme` to custom theme. see https://mobile.ant.design/docs/react/use-with-create-react-app#React-Native-project

2. Most component will receive `props.styles`, `props.style`, you can use those api to change style.


cc @silentcloud
