### ISSUE TITLE
Upgrade rmc-picker to v4

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1593]
https://github.com/react-component/m-picker#4x-beta-docs

**Comment by paranoidjk** [comment]
cc @yesmeck I will do it right now.

**Comment by paranoidjk** [comment]
https://github.com/react-component/m-cascader/blob/master/package.json#L67

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L63

**Comment by paranoidjk** [comment]
https://github.com/react-component/m-picker/tree/master#4x-beta-docs

**Comment by paranoidjk** [comment]
@silentcloud web 的我已经升级完了，本来想继续升级 rn，但 https://github.com/react-component/m-picker/commit/c12a3753556b3a86d8120ae7056c74b30094732a 这里跑不起来。

**Comment by silentcloud** [comment]
@paranoidjk   95325d4e8c840686284b47215d9c263953d2720e

**Comment by silentcloud** [comment]
https://github.com/react-component/m-cascader/commit/0a769b66977a5a698d190a18ef66c2db6a33a8ba

**Comment by silentcloud** [comment]
RN 的都已经更改了，issue 关了

**Comment by paranoidjk** [comment]
@silentcloud picker 和 picker-view 这两个组件忘改了...

**Comment by paranoidjk** [comment]
哦，不对，准确说是 rmc-cascader 升级 rmc-picker 之后我没升 major（因为保持了相同的api，没 break change)

**Comment by paranoidjk** [comment]
所以 antd-mobile@1.x 现在是嵌套依赖多个版本的 rmc-picker 的

**Comment by paranoidjk** [comment]
所以现在提议把 1.x 所有依赖到 rmc-picker 的都升级上来 https://github.com/react-component/m-date-picker/issues/34 （包括依赖的依赖）

**Comment by silentcloud** [comment]
@paranoidjk rmc-picker 没有 5.x 吧？

![image](https://user-images.githubusercontent.com/1698185/29344644-e3b78922-826b-11e7-868b-84256fd2bd8f.png)

**Comment by paranoidjk** [comment]
@silentcloud 那个issue的意思是 rmc-date-picker@5.x 就把 rmc-picker 升级到 4.x. 

目前 @warmhug 是在 rmc-date-picker@6.x 上做的这个升级，但 6.x 去了 moment， antd-mobile@1.x 用不上

**Comment by paranoidjk** [comment]
这个我来 PR.
