### ISSUE TITLE
SwipeAction组件能不能控制滑块的宽度

### ISSUE THREAD

**Issue by zhengshuai1001** [ant-design/ant-design-mobile#1595]
### What problem does this feature solve?
默认滑动出来的div是正方形，怎么让滑块根据文字多少自动变宽，自己改变CSS之后，滑块的总长度还是没变

### What does the proposed API look like?
希望可以自定义每个滑块的宽度

**Comment by zhengshuai1001** [comment]
JS是怎么控制滑块滑动的距离的？即滑块滑动时的CSS的 left 值可以修改吗？

**Comment by warmhug** [comment]
看代码应该是没法根据内容来自适应宽度的，是有点不灵活。

**Comment by zhengshuai1001** [comment]
请问能用js控制滑块移动的距离吗？
![tim 20170725100023](https://user-images.githubusercontent.com/9513530/28552335-778f1e9c-7120-11e7-880f-30a29e6929a9.png)
这个图是滑动后的效果，有四个滑块，本来每个滑块是正方形，我用CSS将宽度改窄了。但是右边多出来一截空白？

**Comment by silentcloud** [comment]
很多计算都是根据 这个 width 来做的，如果 width 可以自定义，在计算的时候就会很复杂，而且用户有可能没个 button 还不一样宽的话，就没办法做了

**Comment by silentcloud** [comment]
https://github.com/react-component/swipeout/issues/40

**Comment by keith890303** [comment]
in my local env i try change like blow , it's run ok. is there any question every body ?
```
//auto get children's total width method
function getBtnWidth(btns, width){
    var btnsWidth = 0;
    if(btns.length > 0) {
        btns.map(function (btn, i) {
            if (btn.style != undefined && btn.style.width != undefined && btn.style.width.indexOf("px")> 0) {
                btnsWidth += parseFloat(btn.style.width.replace("px",""));
            } else {
                btnsWidth += width / 5
            }
        })
    } else {
        btnsWidth = width / 5 * btns.length;
    }
    return btnsWidth;
}
```
```
//react didmount  set left and right buttons width
this.btnsLeftWidth = getBtnWidth(left,width);
this.btnsRightWidth = getBtnWidth(right,width);
//instead of the origin code
this.btnsLeftWidth = width / 5 * left.length;
this.btnsRightWidth = width / 5 * right.length;
```

**Comment by silentcloud** [comment]
6a90ba8b29a3d19031cd272d809982ddad1aa498
