### ISSUE TITLE
Controls the slider width of the SwipeAction Component

### ISSUE THREAD

**Issue by zhengshuai1001** [ant-design/ant-design-mobile#1596]
### What problem does this feature solve?
The default out put slider is a square, how to make the slider width automatically expand according to the number of words. After you change the CSS, the total length of the slider remains unchanged

### What does the proposed API look like?
DIY out put slider width

**Comment by zhengshuai1001** [comment]
How does the JS control the width of the slide?

**Comment by zhengshuai1001** [comment]
How does the JS control the width of the slide?

**Comment by silentcloud** [comment]
重复 issue https://github.com/ant-design/ant-design-mobile/issues/1596
