### ISSUE TITLE
InputItem组件没有type=‘idCard’

### ISSUE THREAD

**Issue by jaune001** [ant-design/ant-design-mobile#1599]
### Version
1.5.0

### Environment
chrome

### Reproduction link
[https://mobile.ant.design/components/input-item-cn](https://mobile.ant.design/components/input-item-cn)

### Steps to reproduce
查看文档中并没有InputItem组件type=“idCard”

### What is expected?
InputItem组件增加type=“idCard”，实现4位4位分隔

### What is actually happening?
InputItem组件没有type=“idCard”

**Comment by paranoidjk** [comment]
新增组件需要完整的交互和设计稿。ref https://github.com/ant-design/ant-design-mobile/issues/1580

**Comment by paranoidjk** [comment]
@peter0011

**Comment by peter0011** [comment]
这个不需要设计稿，只需要增加一种类型即可

**Comment by paranoidjk** [comment]
@peter0011 增加一种类型，主要是做成什么样子呢？**4位4位分隔** 视觉和交互还是要的
