### ISSUE TITLE
0.7.x 禁止组件 less 中引用非变量 less 

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#16]
https://github.com/ant-design/ant-design-mobile/blob/2cef3100e65637dda985918b7ecabd5e063912dc/components/badge/style/index.less

icon 在最终 build 中生成多份

@all  0.7.x 分支相关人照着这个改： https://github.com/ant-design/ant-design-mobile/commit/96c7db9a07444145cf6857b2e0c477bf68c565f0

**Comment by yiminghe** [comment]
0.7.x:  https://github.com/ant-design/ant-design-mobile/commit/9a7c02c6f36314b083d65dbf80d14483aa6518ad

**Comment by afc163** [comment]
直接 cherry-pick 过去？

**Comment by silentcloud** [comment]
@liqi07 badge 的非变量改一下
