### ISSUE TITLE
tabs组件不兼容RN0.44

### ISSUE THREAD

**Issue by nouh** [ant-design/ant-design-mobile#1600]
产生如下的报错： UnableToResolveError: Unable to resolve module `react-native/Libraries/Components/StaticContainer` from `/Users/zhengzhao/Workspace/gc_native/node_modules/react-native-scrollable-tab-view/SceneComponent.js`

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1466

**Comment by silentcloud** [comment]
[index.zip](https://github.com/ant-design/ant-design-mobile/files/1178570/index.zip)

@nouh 没能重现，我上传了 0.44 的 demo，你看看有没有得问题， react-native-scrollable-tab-view/SceneComponent.js 里没用到 react-native/Libraries/Components/StaticContainer， 建议你 删除 node_modules 重装
