### ISSUE TITLE
[Feature] Add a common ReactNative Input component with placeholder style ability

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1605]
https://stackoverflow.com/questions/35581548/how-to-change-styling-of-textinput-placeholder-in-react-native

**Comment by paranoidjk** [comment]
cc @silentcloud

**Comment by silentcloud** [comment]
@paranoidjk 需求来源？

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/pull/1603  这个issue，设计师的设计里面我们是要定制 placeholder 的样式的，web 可以用 css， rn 要做的话我们还是抽象一个内部的 util comopnent 好一点，目前 rn 我是干脆没做这个 feature

**Comment by silentcloud** [comment]
@paranoidjk 这个要搞的话，web 也扩展一下，刚好支持一下 tiny   的  `placeholder-class` 和 `placeholder-style`

![image](https://user-images.githubusercontent.com/1698185/28614152-5ba922ec-7227-11e7-9a73-0a7fc4e636d4.png)

**Comment by paranoidjk** [comment]
@silentcloud web 加这个 api 略奇怪啊... 明明是 css 的活 😅

**Comment by silentcloud** [comment]
嗯， 确实奇怪，但是 tiny 里没办法 css 来搞，都是 api 的方式

**Comment by paranoidjk** [comment]
rn 其实我也没想开放 api 的，只是为了支持设计师的样式需求，打算在内部包装一个

**Comment by paranoidjk** [comment]
@silentcloud 你评估下吧，如果真必要的话，我们加也可以

**Comment by silentcloud** [comment]
嗯，做一下吧，目前做 wx 小程序迁移的时候，类似这样的 api 目前都迁移不了

**Comment by paranoidjk** [comment]
`placeholder-style` 这个没法做，因为 react style 是不能写伪类的，除非我们抛弃 web 原生的 placeholder，改为自己实现。

cc @benjycui 伪类样式这个问题应该也算 styled-component 可以做的优势？

**Comment by silentcloud** [comment]
嗯是的，之前 tiny 里没去实现就是因为伪类

**Comment by benjycui** [comment]
如果我们没办法实现 `placeholder-style`，那么 styled-component 也不可能支持。

**Comment by paranoidjk** [comment]
@benjycui styled-component  不是插入 style 标签么？这样按理说任意 css 都可以写？

**Comment by silentcloud** [comment]
不过这个需求也是尴尬，rn 到时候也只能支持 placeholder-style， 支持不了 placeholder-class

**Comment by paranoidjk** [comment]
@silentcloud 那就只保留  placeholder-style 这个api。web 你也没法实现 placeholder-class 啊，除非抛弃原生的 placeholder

**Comment by silentcloud** [comment]
嗯 能支持 placeholder-style 就行了

**Comment by benjycui** [comment]
> @benjycui styled-component 不是插入 style 标签么？这样按理说任意 css 都可以写？

我以为你们说 RN。。。

**Comment by silentcloud** [comment]
RN 这边要实现，也要抛弃原有的 placeholder 了，stackoverflow 那个方法是不行的，目前 textInput 的 placeholder  是用 NSAttributedString 绘制的

**Comment by paranoidjk** [comment]
@silentcloud 为什么？就用普通的 Text + style 来模拟不就好了么

**Comment by silentcloud** [comment]
@paranoidjk RN 里 placeholder != TextInput.value，两个是不同的东西，所以要实现的话，只能当  输入内容为空的时候把 placeholder 作为 value 来弄，再加上一系列事件了

**Comment by paranoidjk** [comment]
@silentcloud web 里面也一样，placeholder != input.value, 是个互斥的。

只是细想这个输入状态的维护起来的确挺复杂，我觉得 web 要不然还是不做这个 api 算了

**Comment by silentcloud** [comment]
@paranoidjk 这个需求不搞了吧，issue 也关了好了，RN 其实 placeholderColor 就已经够了
