### ISSUE TITLE
Modal animation bug

### ISSUE THREAD

**Issue by sussertod891015** [ant-design/ant-design-mobile#1615]
### Version
1.5.0

### Environment
web

### Reproduction link
[https://codepen.io/sussertod891015/pen/eENYXy](https://codepen.io/sussertod891015/pen/eENYXy)

### Steps to reproduce
the Modal Appear

### What is expected?
the Modal should have fadeIn animation effects

### What is actually happening?
the Modal doesn't have animation effects.

---
it seems like there are two different "keyframes a" in css.

**Comment by paranoidjk** [comment]
Works fine at my device.

Please provide a reproducible demo.

**Comment by silentcloud** [comment]
close for no respond
