### ISSUE TITLE
如何使用prefixCls 来修改antd-mobile 中Tabs组件的样式

### ISSUE THREAD

**Issue by zjzjgxw** [ant-design/ant-design-mobile#1616]
我想要修改Tabs 组件中 选中线条的颜色，及选择线条的字体颜色。
设置prefixCls 为my_tabs 以后样式就全失效了。尝试过把原有的am-tabs 样式复制下来写到自己的样式文件中，然后将am-tabs改为 my_tabs 。但引用css时，由于dva 中会将css中的样式自动添加一段随机字符串防止样式同名。<Tabs defaultActiveKey="1" onChange={handleChange} onTabClick={handleTabClick} prefixCls=“my_tabs” >
`
我该怎么去写自己的my_tabs样式,及如何引用？

**Comment by paranoidjk** [comment]
使用 `className` 添加你自己的类名，然后应用样式。

`prefixCls` 的应用场景是你需要完全重写 antd-mobile 的样式的时候。

**Comment by zjzjgxw** [comment]
![image](https://user-images.githubusercontent.com/11347707/28651723-0d0bd6cc-72b6-11e7-9bfd-0c54e376186f.png)
@paranoidjk  我给tabs 加了一个className my_tabs ，然后写了样式
.my_tabs {
    overflow: hidden;
}

.my_tabs .am-tabs-bar .am-tabs-tab-active{
    color: #000000;
}
但是由于dva CSS模块 会把引入的样式自动添加随机字符串，变成了
.my_tabs___7rj6m {
  overflow: hidden;
}
.my_tabs___7rj6m .am-tabs-bar___1h9GQ .am-tabs-tab-active___1ZkYJ {
  color: #000000;
}
我该怎么写class 及如何引用？

**Comment by paranoidjk** [comment]
禁用 css modules: https://github.com/sorrycc/roadhog#disablecssmodules

**Comment by zjzjgxw** [comment]
@paranoidjk 项目中都是用className={styles.my_tabs}  方式来写的，如果禁用就整个项目的的样式都会有问题了。 css modules 不支持忽略某一个文件吗

**Comment by paranoidjk** [comment]
> 如果禁用就整个项目的的样式都会有问题了

并不会，请自行学习 css module 相关知识。

**Comment by afc163** [comment]
https://github.com/css-modules/css-modules#exceptions

**Comment by zjzjgxw** [comment]
@paranoidjk @afc163 谢谢，找到办法了。使用:global 就好了
