### ISSUE TITLE
List.Item.Brief requires styles prop and it override default styles

### ISSUE THREAD

**Issue by sunkibaek** [ant-design/ant-design-mobile#1618]
### Version
1.5.0

### Environment
MacOS, RN 0.46.2

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe?editors=0010](https://codepen.io/paranoidjk/pen/LWpaKe?editors=0010)

### Steps to reproduce
Try to use `List.Item.Brief` component in render method.

```
  <List.Item.Brief styles={{ Brief: {}, BriefTest: {} }}>
    Test text for Brief
  </List.Item.Brief>
```

### What is expected?
`styles` prop should be optional or it should ignore null or empty object.

### What is actually happening?
`styles` prop is required. When it is supplied with null or empty object it overwrites default styles.

**Comment by silentcloud** [comment]
@sunkibaek https://github.com/ant-design/ant-design-mobile/blob/master/components/list/ListItem.tsx#L10

**Comment by cncolder** [comment]
@silentcloud this issue about this line https://github.com/ant-design/ant-design-mobile/blob/1a622784ec17ee444fb9afb95f534fbfd67df641/components/list/PropsType.tsx#L71

code logic is right, type define is wrong.
