### ISSUE TITLE
Add a server render demo with egg.js

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1619]
https://eggjs.org

## antd-mobile-with-next.js
https://github.com/zeit/next.js/tree/v3-beta/examples/with-antd-mobile

**Comment by paranoidjk** [comment]
@cncolder require hacker 只能解决对指定后缀名的替换，这一行 https://github.com/ant-design/ant-design-mobile/blob/master/components/grid/style/index.web.tsx#L1， 加载文件夹的实测没法替换

**Comment by paranoidjk** [comment]
@cncolder https://github.com/ant-design/ant-design-mobile/commit/1a622784ec17ee444fb9afb95f534fbfd67df641

坑一个 require hacker 需要对应的文件必须首先存在，否则 nodejs 就 throw error 了

**Comment by cncolder** [comment]
`fs.existsSync`

[https://github.com/ant-design/antd-mobile-samples/blob/a8723f3a6233c7083339e434c1310ccdc37b0414/web-ssr/next.config.js#L13](https://github.com/ant-design/antd-mobile-samples/blob/a8723f3a6233c7083339e434c1310ccdc37b0414/web-ssr/next.config.js#L13)

**Comment by paranoidjk** [comment]
@cncolder 这段代码得不到机会执行的

```bash
/~/_antd-mobile@1.5.0@antd-mobile/lib/grid/style/index.web.js                                                                                                                                               jiangkai@jiangkaideMacBook-Pro
Module not found: Error: Cannot resolve directory '../../style' in /Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/grid/style
resolve directory ../../style in /Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/grid/style
  /Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/style/package.json doesn't exist (directory description file)
  directory default file index
    resolve file index in /Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/style
      /Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/style/index doesn't exist
      /Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/style/index.json doesn't exist
      /Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/style/index.js doesn't exist
      /Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/style/index.jsx doesn't exist
[/Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/style/index]
[/Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/style/index.json]
[/Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/style/index.js]
[/Users/jiangkai/gitlab/lippi-ding-node/node_modules/_antd-mobile@1.5.0@antd-mobile/lib/style/index.jsx]
 @ ./~/_antd-mobile@1.5.0@antd-mobile/lib/grid/style/index.web.js 3:0-23
./~/_antd-mobile@1.5.0@antd-mobile/lib/grid/style/index.web.js
```

**Comment by paranoidjk** [comment]
应该是由于这里是读文件夹，nodejs 读目录会优先尝试 pkg.main, 失败才会 fallback 到 index.{extension}, 而这个过程中 nodejs 就直接 throw error 退出了

**Comment by paranoidjk** [comment]
require-hacker 文档也写了 
> The require()d path must exist in the filesystem, otherwise an exception will be thrown: Cannot find module.

https://github.com/catamphetamine/require-hacker#hookfile_extension-resolve

**Comment by cncolder** [comment]
你看一下这个搜索过程，好像没有去找 `antd-mobile/lib/style/index.web.js`。看起来执行 `antd-mobile/lib/grid/style/index.web.js` 这个文件的时候 `require hacker` 没有生效。

**Comment by cncolder** [comment]
`babel-plugin-import` 转换后的结果是 `var _grid = require('antd-mobile/lib/grid')` 也是目录，node 尝试读取 `antd-mobile/lib/grid/index.js` 的时候我们篡改成 `antd-mobile/lib/grid/index.web.js`。

所以我看你的日志，似乎 `require hacker` 没生效。

不太清楚 egg.js 该把 `require extensions hacker` 插入在什么地方。

**Comment by paranoidjk** [comment]
但是区别是 grid 下面 index.js 真是存在，然后可以理解为 nodejs resolve 成功了，此后 require hacker 才能接手？

要看 require hacker 是用的 nodejs 哪个api，会在哪个阶段介入执行

**Comment by cncolder** [comment]
egg.js 是个服务端吧？我不建议做这个 ssr demo 尝试，即使是你解决了所有问题配置成功了，本质上就是 koa + react ssr。如果是渲染静态页面的话，nginx 足已。

next.js 到目前为止基本上已经代表了 react ssr 最佳实践，我从1代一直踪到现在的3代beta。

实际上 react ssr 项目，server 端不是每个页面都渲染，而是每个页面都**“能够”**渲染。也就是说每个页面都能当首屏，服务端灌注数据，不让首屏空白，之后的页面切换全部在客户端完成的，router/pushState/xhr，仅此而已。

**Comment by cncolder** [comment]
我去试试 style 目录这个问题，过去一直都是 `<link />` 引用的 css，一直都没有使用到打包的 less。

**Comment by paranoidjk** [comment]
egg 是 koa 之上的。

> 如果是渲染静态页面的话，nginx 足已。

nginx 肯定是远远不够的，真正业务上，服务端渲染的首屏应该也是有数据获取和填充的逻辑。

我印象中 egg 团队的 @dead-horse 有在尝试 next.js 相关的东西？

**Comment by cncolder** [comment]
@paranoidjk 我把 `antd-mobile/lib/grid/index.js` 改个名字，服务端客户端照常运行。

`require hacker` 会污染 `Module not found` error stack，但是你的 stack 里我没看到 `require hacker`。

**Comment by paranoidjk** [comment]
内部用户用 egg.js + antd-mobile + require-hacker 做服务端渲染的时候遇到的。

我稍后空的时候搞一个裸的 demo 来看看能不能复现

**Comment by cncolder** [comment]
可问题是 egg 与 react 并无关系。

之前有这样一行旧代码

```js
  requireHacker.resolver((filename, module) => {
    if (filename.endsWith('/style/css')) return requireHacker.resolve(`${filename}.web.js`, module)
  })
```

是因为有的组件 `import '../../style/css'`，而这里要解析成 `import '../../style/css.web.js'`

`import '../../style'` -> `import '../../style/index.web.js'` 应该等同于 `import 'antd-mobile/lib/grid'` -> `import 'antd-mobile/lib/grid/index.web.js'`，删掉 `index.js` 也不会报这个找不到模块的错误。

**Comment by cncolder** [comment]
`require hacker` 要放在一个只在服务端加载并且早于 `antd-mobile` 的地方。

**Comment by warmhug** [comment]
egg.js demo 现在感觉没必要加了。
1.x 引起的问题是不是可以不管了？如果 2.0 里没这些问题、issue 就关掉吧。

**Comment by paranoidjk** [comment]
2.0 服务端渲染不再需要 require hacker，只需要组件内部包装在 didMount 之前不使用 DOM API， 先关闭吧。

cc @silentcloud @zhang740 @pingan1927
