### ISSUE TITLE
RN 组件 review 情况

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#162]
- [x] list:  ios content 和 detail 在一行， android 显示有问题被截断

![image](https://cloud.githubusercontent.com/assets/1698185/17996269/3f90d0d0-6b9a-11e6-8f08-71d34f069fb4.png)
![image](https://cloud.githubusercontent.com/assets/1698185/17996287/5b18f8e6-6b9a-11e6-96b7-947e900310d0.png)

- [x] searchbar android 输入框字被截断

![image](https://cloud.githubusercontent.com/assets/1698185/17996309/7d90217e-6b9a-11e6-80e7-8c95028933b8.png)

- [x] Steps android  显示问题

![image](https://cloud.githubusercontent.com/assets/1698185/17996315/8acb4bc0-6b9a-11e6-8034-a2c48dbef31c.png)

- [x] tabbar android badge  问题

![image](https://cloud.githubusercontent.com/assets/1698185/17996336/b3305b1e-6b9a-11e6-9ff3-469ef34fb3c2.png)

- [x] ActivityIndicator android 显示问题 

![image](https://cloud.githubusercontent.com/assets/1698185/17996350/da587a14-6b9a-11e6-9247-7a161fca260d.png)

**Comment by afc163** [comment]
到现在还没跑起来 Android 环境。。

**Comment by silentcloud** [comment]
@afc163 用 wiki 里的方法，或者直接 android studio
