### ISSUE TITLE
Tabs 与scrollview手势不兼容

### ISSUE THREAD

**Issue by cielu** [ant-design/ant-design-mobile#1620]
### Version
1.5.0

### Environment
react-native@0.44.3

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
Tabs里面的某个tab使用了scrollView ，但是去滑动scrollview的时候，直接被tabs给过滤了，导致滑动scrollview不起作用。。

### What is expected?
scrollview与tabs可以手势兼容，scrollview能正常滑动

### What is actually happening?
scrollview不能正常滑动

---
这个英文不太好形容。。

**Comment by cielu** [comment]
然后我觉得滑动太敏感了，下拉的操作都有可能触发滑动切tab

**Comment by acomito** [comment]
I've also had trouble styling this easily. I was trying to give it a flex: 1 and I think was running into some issues.

**Comment by cielu** [comment]
@acomito give which one flex:1 ?

**Comment by cielu** [comment]
@acomito  Hey gays , I thought my problem is not the same as you . My problem is that when I use Scrollview in tabs , the scrollview went wrong

**Comment by silentcloud** [comment]
@cielu  https://github.com/ant-design/ant-design-mobile/pull/1457

**Comment by cielu** [comment]
@silentcloud 
![image](https://user-images.githubusercontent.com/13715811/28765833-4a375926-75ff-11e7-9f77-02c20b699eae.png)

**Comment by silentcloud** [comment]
@cielu 这个已经在  https://github.com/ant-design/ant-design-mobile/pull/1651 这里解决了
