### ISSUE TITLE
Expo app saying react-native-scripts: command not found when trying to run script to generate custom styles

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design-mobile#1624]
### Version
1.5.0

### Environment
npm 5.3.0, node v8.2.1, "antd-mobile": "^1.5.0", "expo": "^19.0.0",

### Reproduction link
[https://mobile.ant.design/docs/react/use-with-create-react-app#React-Native-project](https://mobile.ant.design/docs/react/use-with-create-react-app#React-Native-project)

### Steps to reproduce
create a fresh expo project, npm i -S antd-mobile, then follow these instructions: https://mobile.ant.design/docs/react/use-with-create-react-app#React-Native-project

### What is expected?
expected to output a styles file

### What is actually happening?
sh: react-native-scripts: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! myapp-rn@0.0.0 start: `node scripts/custom-rn-theme && react-native-scripts start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the myapp-rn@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

---
maybe related to npm version issue? 

https://github.com/react-community/create-react-native-app/issues/233

https://github.com/react-community/create-react-native-app/issues/239

**Comment by acomito** [comment]
Okay, figured it out. Maybe to improve the docs you can:

1. If you haven't, point to the list of variables: https://github.com/ant-design/ant-design-mobile/blob/master/components/style/themes/default.tsx#L137

2. mention that you may see an error message when you run the npm start script, but that it most likely did it's theme work anyway

3. mention that once you run this script, and change some variables, those variables are forever changed. You need to explicitly change them again.. in other words, if I change the border of the card to green and run "npm start", then my card borders are green. If I remove that variable from my theme file, and rerun "npm start", the script runs again but my cards will still be green (it doesnt go back to default). I would need to explicitly change the card border from green back to grey (the default) in my theme file.

**Comment by paranoidjk** [comment]
@acomito It will be great if you are willing to PR to help us enhance the document. 😄

**Comment by acomito** [comment]
@paranoidjk Okay. I wasn't sure if you wanted it in mandarin or not. I can look into doing a PR.

**Comment by paranoidjk** [comment]
@acomito Just english version is enough，we will help you with chinese translation.

**Comment by silentcloud** [comment]
@acomito I follow the doc and everything is ok.

```bash
npm install -g yarn
npm install -g create-react-native-app
create-react-native-app antm-demo
cd antm-demo
yarn add antd-mobile
yarn add babel-plugin-import --dev
```
then

follow: https://mobile.ant.design/docs/react/use-with-create-react-app#React-Native-project

**Comment by acomito** [comment]
Hey @silentcloud, yes everything is all set. It was my mistake. I had a suggestion to add more detail to the docs, but I haven't got around to it. Please feel free to close this issue though. 

Loving antd-mobile. Looking forward to 2.0
