### ISSUE TITLE
Discuss about which rc-component need to rewrite to rmc-component

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1625]
收集意见与评估下哪些 rc-component 需要拆分移动版，不再与 antd 使用公共的底层依赖。

因为 pc 组件有键盘访问，鼠标事件等很多其他 mobile 用不到的冗余特性，而目前也没有做好模块化和按需加载。

**Comment by paranoidjk** [comment]
优先级放低，看 2.0 的开发进度。

**Comment by silentcloud** [comment]
为了解决 preact 兼容性， dialog 要做改动 => m-dialog

- [ ] m-dialog @silentcloud

**Comment by silentcloud** [comment]
- [ ] rc-steps 需要去除 prop-types， 特定浏览器下的 fix 代码

**Comment by warmhug** [comment]
prop-types => ts  感觉可以在 2.0 发布时新增一个卖点，代码全部改为了 ts 、推荐用户使用 ts

**Comment by silentcloud** [comment]
> prop-types => ts 感觉可以在 2.0 发布时新增一个卖点，代码全部改为了 ts 、推荐用户使用 ts

这个 ok 的

rc 底层 prop-types => ts 这个暂时不处理了（min.js 不会有prop-types）, 在 antd-mobile 里做 ts 定义就行了
