### ISSUE TITLE
Can the Imagepicker component customize the Add button? such as a small icon, etc.

### ISSUE THREAD

**Issue by margin-0** [ant-design/ant-design-mobile#1628]
### What problem does this feature solve?
Most of the projects are click on the icon to pick up the album, if you can customize it will be convenient, more widely used

### What does the proposed API look like?
You can customize the style of a button or use an icon

**Comment by paranoidjk** [comment]
Sorry, right now we do not support this.

But you can set `selectable=false`, then antd-mobile will not render a add image icon, so you can add wahtever you like with your own code.

**Comment by margin-0** [comment]
Oh，Thank you
