### ISSUE TITLE
modal滚动穿透

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#163]
- antd-mobile 版本：0.7.8
- 操作系统及其版本：ios 手淘/支付宝容器
- 浏览器及其版本：手淘5.10.3

modal滚动穿透，`仅在容器会这样，浏览器不会`

**Comment by silentcloud** [comment]
@warmhug 帮忙瞅瞅，我大概看了哈没找到问题原因

**Comment by yiminghe** [comment]
@warmhug 看下 https://github.com/react-component/dialog/blob/master/src/Dialog.jsx#L337 这个是不是容器有啥兼容问题

**Comment by silentcloud** [comment]
手机 safari 浏览器也是的，不只是容器问题，但是没发现什么问题，理应当 overlow:hidden 就 ok 了的

**Comment by yiminghe** [comment]
framework7 同样问题，搜了下没什么好的方案

**Comment by xyqfer** [comment]
把 `modal` 上的 `touchmove` `preventDefault` 掉试试。。。

**Comment by lyboy2012** [comment]
发现webview  onTouchStart  onTouchMove 阻止事件，页面还是会滚动，这有解吗，浏览器里没问题
。

**Comment by aiqin-bao** [comment]
这个问题 有没有方案去解决那  ？？？？
