### ISSUE TITLE
H5数字键盘点击后自动隐藏

### ISSUE THREAD

**Issue by ccqiuqiu** [ant-design/ant-design-mobile#1630]
InputItem组件的type为money时，获得焦点会弹出 CustomKeyboard，但是，点击键盘上面的任意数字，键盘就自动隐藏了

在chrome浏览器的开发者工具里面切换为手机模式会有这个问题，电脑模式不会有。

**Comment by paranoidjk** [comment]
请优先测试真机是否有问题？

**Comment by madaono** [comment]
检查下你的组件key值是否是个不确定值，致使每次输入React都会认为是一个新的组件重新渲染

**Comment by WinterWoods** [comment]
我的也是自动消失,到底为什么呢.组件没有从新渲染
