### ISSUE TITLE
在preact 下使用antd-design的多个组件报错

### ISSUE THREAD

**Issue by buting2014** [ant-design/ant-design-mobile#1631]
### Version
1.6.0

### Environment
preact, antd-design lasted

### Reproduction link
[https://github.com/buting2014/preact-init-test](https://github.com/buting2014/preact-init-test)

### Steps to reproduce

由于是移动端项目 出于性能考虑 采用了[preact](https://github.com/developit/preact)作为框架
结合antd-design使用时
几个用到的组件Picker，DatePicker 以及 Carousel都出现了以下报错

Picker中
```
PopupMixin.js?f1af:39
Uncaught (in promise) TypeError: this.setState is not a function
```

Carousel中：

```
carousel.js?2723:649 Uncaught TypeError: this.setState is not a function
```

复现方式：
1. 直接clone https://github.com/buting2014/preact-init-test 
2. npm install 
3. sudo npm run dev

辛苦各位大神 ヾ(=･ω･=)o 

### What is expected?
能和preact兼容

### What is actually happening?
个别组件出现报错

**Comment by paranoidjk** [comment]
@buting2014 请先确认是 preact 的 bug 还是 antd-mobile 的 bug。

有些可以 antd-mobile 兼容，但大多数情况，antd-mobile 不应该需要做任何改动，因为 preact 是渲染兼容 react 的。


cc @pingan1927

**Comment by pingan1927** [comment]
这个2.0大版本会支持绝大部分组件 请稍等一段时间 @buting2014

**Comment by silentcloud** [comment]
组件和 preact 的兼容性:

[x] Accordion

**Comment by luolonghao** [comment]
`this.setState is not a function` 这个错误应该是没有引入 create-react-class 导致。

```
{
    // ...
    resolve: {
        alias: {
            'react': 'preact-compat',
            'react-dom': 'preact-compat',
            'create-react-class': 'preact-compat/lib/create-react-class'
        }
    }
    // ...
}
```

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1304
