### ISSUE TITLE
antd-mobile DatePicker demo was wrong

### ISSUE THREAD

**Issue by shilx** [ant-design/ant-design-mobile#1635]
### Version
1.6.0

### Environment
win10\chrome60

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/date-picker?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/date-picker?lang=zh-CN)

### Steps to reproduce
Open the link, click any input box, and view the console  
打开链接，点击任何输入框，然后查看控制台

### What is expected?
Run correctly  
正确运行

### What is actually happening?
The console reported an error  
控制台报告了错误

---
 forgive my machine translation
英语苦手，原谅我的机器翻译

**Comment by silentcloud** [comment]
![image](https://user-images.githubusercontent.com/1698185/28869441-4e136d94-77af-11e7-8736-29cba8013b32.png)

@warmhug

**Comment by warmhug** [comment]
@paranoidjk 看下是不是部署网站出问题了？1.x 本地运行没问题

**Comment by paranoidjk** [comment]
@shilx Sorry for the trouble, it had been fixed.

@warmhug yep, i deployed site with newer dependencies which installed in master branch.
