### ISSUE TITLE
antd-mobile Tabs中使用ListView的stickyHeader，切换Tab时sectionHeader全部消失

### ISSUE THREAD

**Issue by w771854332** [ant-design/ant-design-mobile#1636]
### Version
1.6.0

### Environment
mac/chrome-59/react-15.4.0

### Reproduction link
[https://codepen.io/771854332/pen/OjXYVL?editors=0010](https://codepen.io/771854332/pen/OjXYVL?editors=0010)

### 在Tabs中使用ListView
*多次点击切换Tab时，设置了stickyHeader的sectionHeader有时会全部消失*

*再次点击该Tab、或滚动页面，消失的sectionHeader才会出现*

### What is expected?
希望可以同时使用Tabs和ListView的stickyHeader效果

### What is actually happening?
运行错误

**Comment by warmhug** [comment]
这种不是必现的话，可能是 css 导致的页面 repaint/reflow 问题，欢迎帮助排查。

**Comment by paranoidjk** [comment]
不清楚怎么复现，另外请优先确认移动端真机是否有问题，建议提供 gif 或 录屏。
