### ISSUE TITLE
Carousel 走马灯问题（偶发）

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#164]
- antd-mobile 版本：0.7.8
- 操作系统及其版本：ios 手淘容器
- 浏览器及其版本：手淘5.10.3

页面上引入 Carousel ，刚开始能正常工作，停了一段时间，不能滑动走马灯、点击指示点也不能切换。

> ios Android 浏览器里没问题

**Comment by afc163** [comment]
需要升级 react-slick 依赖。

**Comment by warmhug** [comment]
我先来改下 package.json 。 @foriacus 再跟进测试下这个问题

**Comment by foriacus** [comment]
@warmhug 0.8.5还有这个问题吗？

**Comment by foriacus** [comment]
carousel暂时没给指示点加点击事件。

**Comment by warmhug** [comment]
试试没问题了
