### ISSUE TITLE
Failed to compile logo.svg

### ISSUE THREAD

**Issue by google88888888** [ant-design/ant-design-mobile#1640]
### Version
undefined

### Environment
chrome

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
compile

### What is expected?
compile success

### What is actually happening?
compile fail

**Comment by google88888888** [comment]
Failed to compile
./src/my-project-svg-foler/logo.svg
Module parse failed: D:\gitProject\mobile\antm-demo\src\my-project-svg-foler\logo.svg Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3">

**Comment by paranoidjk** [comment]
https://mobile.ant.design/components/icon-cn#如何使用-(WEB-版)
