### ISSUE TITLE
配置了svg-sprite依然不能编译

### ISSUE THREAD

**Issue by google88888888** [ant-design/ant-design-mobile#1641]
### Version
1.6.0

### Environment
chrome

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile](http://new-issue.ant.design/?repo=ant-design-mobile)

### Steps to reproduce
      {
        test: /\.(svg)$/i,
        loader: 'svg-sprite',
        include: [
          require.resolve('antd-mobile').replace(/warn\.js$/, ''),  // 1. svg files of antd-mobile
          path.resolve(__dirname, 'src/my-project-svg-foler'),  // folder of svg files in your project
          //path.resolve(__dirname, 'src/logo.svg'),
          //path.resolve(__dirname, 'src'),  // folder of svg files in your project
        ]
      },
依然

Failed to compile
./src/my-project-svg-foler/logo.svg
Module parse failed: D:\gitProject\mobile\antm-demo\src\my-project-svg-foler\logo.svg Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3">
|     <g fill="#61DAFB">

### What is expected?
编译成功

### What is actually happening?
编译失败

**Comment by google88888888** [comment]
按照官网在 create-react(-native)-app 中使用进行配置，不能编译成功

**Comment by paranoidjk** [comment]
提供可复现的 demo，参考。 https://github.com/ant-design/antd-mobile-samples/tree/master/create-react-app

文档一直被使用和验证，没有问题，请检查自己的配置。
