### ISSUE TITLE
refactor popover arrow

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1643]
https://github.com/ant-design/ant-design-mobile/blob/master/components/popover/style/index.less#L44

## Problem

https://mobile.ant.design/components/popover-cn

Right now it only suitable for popover content background color same as arrow color

eg: if we want to change arrow background color, the overflow content havn't been hidden

<img width="280" alt="2017-08-06 10 13 28" src="https://user-images.githubusercontent.com/7971415/29000008-f162f68a-7a8f-11e7-8de8-d84eb5403dd2.png">

**Comment by paranoidjk** [comment]
remove https://github.com/ant-design/ant-design-mobile/blob/master/components/popover/style/index.tsx~HEAD

**Comment by paranoidjk** [comment]
rc-tooltip's implementation is fine.

<img width="1365" alt="2017-08-06 13 24 53" src="https://user-images.githubusercontent.com/7971415/29000819-aaf76a3a-7aaa-11e7-91b5-b84525acec9d.png">

**Comment by paranoidjk** [comment]
cc @jljsj33

**Comment by paranoidjk** [comment]
ant-design is fine too. https://ant.design/components/popover-cn/

<img width="1142" alt="2017-08-06 13 39 23" src="https://user-images.githubusercontent.com/7971415/29000893-b1071450-7aac-11e7-9e73-623b41c35dc9.png">

**Comment by paranoidjk** [comment]
So,  rc-tooltip, ant-design, ant-design-mobile use different way to draw a arrow.

antd-mobile@2.0 will use @jljsj33 way from antstar.

<img width="805" alt="2017-08-06 13 44 41" src="https://user-images.githubusercontent.com/7971415/29000923-a2c60b3e-7aad-11e7-9224-7614d13edad9.png">

cc @afc163

**Comment by thakkarpanth** [comment]
Is there any way to hide arrow in popover ??
