### ISSUE TITLE
JavaScript evaluation error: 'ReferenceError: document is not defined'

### ISSUE THREAD

**Issue by google88888888** [ant-design/ant-design-mobile#1645]
### Version
1.6.0

### Environment
chorme

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile](http://new-issue.ant.design/?repo=ant-design-mobile)

### Steps to reproduce
按照官网步骤初始化项目后，在less文件中写入@width : `document.body.clientWidth`;
会报错JavaScript evaluation error: 'ReferenceError: document is not defined'。

### What is expected?
成功

### What is actually happening?
会报错JavaScript evaluation error: 'ReferenceError: document is not defined'。

**Comment by paranoidjk** [comment]
> 在less文件中写入@width : document.body.clientWidth;

http://lesscss.org/
