### ISSUE TITLE
Tabs 支持给各部分 dom 添加 data-* 

### ISSUE THREAD

**Issue by missjing** [ant-design/ant-design-mobile#1648]
### What problem does this feature solve?
在 Tracker 的埋点规则下，会在前端 dom 上埋一些属性 `data-aspm/data-aspm-click/data-aspm-expo/data-aspm-param`，目前在react一套下会使用到 antd-mobile 组件，但却不支持埋点属性，全部要手动Tracker.click的方式做很不人性。

### What does the proposed API look like?
```
<Flex.Item className="earn"
               onClick={toProfitList}
               data-aspm-click={spm.dPos}
               data-aspm-expo>收益明细
</Flex.Item>
```

**Comment by paranoidjk** [comment]
大部分组件应该都支持了 `data-*`, 你有发现哪个组件不支持吗？

**Comment by paranoidjk** [comment]
另外请确认 antd-mobile 版本，最新是 `1.6.0`

**Comment by missjing** [comment]
多谢，之前用的 `1.0.0`版本。升级到`1.6.0`就可以了～

**Comment by missjing** [comment]
本地测试发现 `Tabs`组件不支持`data-*`属性诶，看代码里似乎也没加？  https://github.com/ant-design/ant-design-mobile/blob/master/components/tabs/index.tsx#L54

**Comment by paranoidjk** [comment]
https://github.com/react-component/tabs/pull/92
