### ISSUE TITLE
Recommend exposing CheckboxItem‘s prefixCls

### ISSUE THREAD

**Issue by cisen** [ant-design/ant-design-mobile#1649]
### What problem does this feature solve?
CheckboxItem‘s API now contains
```
listPrefixCls?: any; // web only
  children?: any;
  extra?: any;
  onClick?: () => any;
  checkboxStyle?: any; // rn only
  checkboxProps?: Object;
```
but have not contained parameter `prefixCls`.
Without `prefixCls`, i can't diy CheckboxItem's style correctly. Hope supporting 'prefixCls', THX!

### What does the proposed API look like?
```
listPrefixCls?: any; // web only
  children?: any;
  extra?: any;
  onClick?: () => any;
  checkboxStyle?: any; // rn only
  checkboxProps?: Object;
  prefixCls?: string;
```

**Comment by paranoidjk** [comment]
There do have `prefixCls` api, we just forgot to add it to doc. 

https://github.com/ant-design/ant-design-mobile/blob/master/components/checkbox/CheckboxItem.tsx#L23

welcome PR to help us fix the documentation.
