### ISSUE TITLE
Stepper 步进器 iOS 容器问题

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#165]
- antd-mobile 版本：0.7.8
- 操作系统及其版本：ios 手淘/支付宝容器
- 浏览器及其版本：手淘5.10.3

快速点击加减按钮、反应迟钝或没反应（慢速一下下点击没问题）

> android 支付宝容器没问题；ios Safari 浏览器也没问题

**Comment by silentcloud** [comment]
我在支付宝容器试了没啥问题

**Comment by warmhug** [comment]
手机淘宝容器里看下，快速点击反应有点慢

**Comment by silentcloud** [comment]
我淘宝容器 ok
