### ISSUE TITLE
标签页报错

### ISSUE THREAD

**Issue by vecold** [ant-design/ant-design-mobile#1654]
代码如下
  <View style={{height:100}}>
                   <Tabs defaultActiveKey="1" >
      <TabPane tab={<Text>1<Text>} key="1">
       <Text>1<Text>
      </TabPane>
        <TabPane tab={<Text>2<Text>} key="2">
       <Text>2<Text>
      </TabPane>
       <TabPane tab={<Text>3<Text>} key="3">
       <Text>3<Text>
      </TabPane>
    </Tabs>
                    </View>
运行环境React-Native 
报错Did not get valid calls back from JS。。。

**Comment by vecold** [comment]
Taps组件报错

**Comment by silentcloud** [comment]
请按 issue 模板描述问题
