### ISSUE TITLE
SwipeAction只要向左滑动，不要向右滑动

### ISSUE THREAD

**Issue by aiien007** [ant-design/ant-design-mobile#1655]
### What problem does this feature solve?
我不需要左侧的按钮，但是SwipeAction在左侧部分依然可以向右滑动，希望可以解决这个问题

### What does the proposed API look like?
rn版本：0.42.3
antmobile版本：1.1.2，
我的代码：
![_20170809163716](https://user-images.githubusercontent.com/8551421/29112697-3c969614-7d21-11e7-9e60-7ae2861fd38f.png)

并没有传left属性值
然后看了下SwipeAction源码，
![_20170809163415](https://user-images.githubusercontent.com/8551421/29112517-b14136fa-7d20-11e7-874e-d68e30d0b98e.png)

发现left:[]属性会作为默认值传给Swipeout，导致向右滑动是肯定存在的

**Comment by paranoidjk** [comment]
@ant-design-bot markdown

**Comment by aiien007** [comment]
@paranoidjk 
format后 还是格式排版乱，我直接截图发了

**Comment by silentcloud** [comment]
@aiien007 嗯，这个 web 是处理的，RN 的遗漏了，我等会修掉

**Comment by aiien007** [comment]
@silentcloud 
问下，修掉后我这边需要升级到最新版本吗

**Comment by silentcloud** [comment]
@aiien007 要等发布

**Comment by aiien007** [comment]
@silentcloud 
好吧，周五的版本就有了是吧

**Comment by silentcloud** [comment]
本周会发版本的
