### ISSUE TITLE
官方demo Badge在ios10.3.3中显示不正常

### ISSUE THREAD

**Issue by xiaomak** [ant-design/ant-design-mobile#1658]
### Version
1.6.0

### Environment
ios 10.3.3 、微信ios

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/badge](https://mobile.ant.design/kitchen-sink/components/badge)

### Steps to reproduce
用苹果手机浏览https://mobile.ant.design/kitchen-sink/components/badge
![bug](https://user-images.githubusercontent.com/1825679/29115607-d27d80e4-7d2a-11e7-9e8e-ec8de9e91b2e.PNG)

### What is expected?
放在extra的badge应该是显示在右上角的

### What is actually happening?
放在extra的badge在ios10.3.3中显示在中间

**Comment by silentcloud** [comment]
demo 的单位写的有问题
