### ISSUE TITLE
引入高清方案后，由于viewports缩小而导至img,video,等图片多媒体本身ui变得很小

### ISSUE THREAD

**Issue by ok111net** [ant-design/ant-design-mobile#1659]
antd-mobile 版本：1.6.0
引入高清方案后，由于viewports缩小而导至img,video,等图片多媒体本身ui变得很小。

**Comment by paranoidjk** [comment]
>由于viewports缩小而导至img,video,等图片多媒体本身ui变得很小

要看你的样式怎么写的。

请提供可复现的 demo。

**Comment by ok111net** [comment]
就html5 video 和img等标签，设置了高清后自带的controls控制ui变小了，css样式没办法去重写它大小。如：<video src={require('../media/m.mp4')} controls autoPlay style={{width:'100%',height:'auto'}}/>
这里没办法上传图片

**Comment by paranoidjk** [comment]
@ok111net 给个 demo 吧。

如果实在有问题，你可以在你的业务中取消 viewport 缩放，然后写死 html 的 font-size 好了，这个只影响 1px 线。

另外 antd-mobile@2.0 会修改方案，高清方案会成为可选。

cc @pingan1927

**Comment by ok111net** [comment]
谢谢，现在只能去掉，影响不大。希望下版本能改进，这个高晰方案挺好的，可以改进用户体验。
