### ISSUE TITLE
Open demo in CodePen and Riddle

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#1662]
like antd does.

**Comment by paranoidjk** [comment]
Riddle already opened access for non alibaba-inc user?

**Comment by afc163** [comment]
Nope, there is a internal judgement.

**Comment by afc163** [comment]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/507615/29250775-f975c172-807a-11e7-92b9-95a3ba12cbce.png">

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/29250779-12ddb3ea-807b-11e7-91b7-e34364590660.gif)

**Comment by paranoidjk** [comment]
@afc163 Affix 好像处理不了这种？得我手动处理吧

**Comment by paranoidjk** [comment]
用 target 改变 sticky 的容器应该可以，我试试

**Comment by paranoidjk** [comment]
@afc163 一个 affix 没想好怎么实现这种效果，先手动处理下了 https://github.com/ant-design/ant-design-mobile/commit/adec22cd92e08d8185bc42a1389ad58a0de2eada
