### ISSUE TITLE
TextareaItem输入表情符号计数不正确的bug

### ISSUE THREAD

**Issue by marga8080** [ant-design/ant-design-mobile#1663]
### Version
1.6.0

### Environment
ios10

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/textarea-item](https://mobile.ant.design/kitchen-sink/components/textarea-item)

### Steps to reproduce
TextareaItem输入🇩🇪（德国国旗emoji）

### What is expected?
TextareaItem输入🇩🇪（德国国旗emoji）计算1个字符 

### What is actually happening?
会计算2个字符  ![Markdown](http://i1.bvimg.com/1949/5e2a6896d6abcca6.png)

**Comment by marga8080** [comment]
![img](http://i1.bvimg.com/1949/88f7c228f3451e5d.png)

**Comment by paranoidjk** [comment]
<img src="https://user-images.githubusercontent.com/7971415/29209232-0fd5e634-7ec0-11e7-81dd-640e0801742d.png" width="350">

**Comment by paranoidjk** [comment]
works fine, please provide a reproducible demo.

**Comment by marga8080** [comment]
你已经复现了bug。你输入的是3个表情字符，但是计数却为4。假如你输入100个国旗emoji，你会发现计数为200/100

**Comment by afc163** [comment]
很难说是 bug，emoji 本身就是多个字符组合的。

<img width="400" alt="image" src="https://user-images.githubusercontent.com/507615/29211121-bb9b6710-7ec9-11e7-91e4-aae0a2d7037d.png">

**Comment by marga8080** [comment]
count设置100，国旗emoji计数为2，那么我输入50个国旗emoji的时候就应该限制住不让再输，那么我现在却可以输入100个国旗emoji

**Comment by afc163** [comment]
感觉是有问题。@paranoidjk

**Comment by paranoidjk** [comment]
emoji 分很多平面区间的，要想完整覆盖，这个正则太长了 https://medium.com/reactnative/emojis-in-javascript-f693d0eb79fb#f66e

**Comment by paranoidjk** [comment]
@afc163 目前的实现只是用了个粗糙的正则把识别到的 emoji 算作一个字符 https://github.com/ant-design/ant-design-mobile/blob/master/components/textarea-item/index.tsx#L16

**Comment by paranoidjk** [comment]
<img width="596" alt="2017-08-11 20 21 10" src="https://user-images.githubusercontent.com/7971415/29212729-a339898c-7ed2-11e7-8da3-8f5a976d7bb5.png">

Twitter 也没有处理这个问题，我们的表现和它一致

**Comment by afc163** [comment]
OK，楼主描述的不算问题，一个 emoji 计数为 2 是对的。发现另外一个问题，我们输入 emoji 计数到 50 就不能再输入了。

<img width="492" alt="image" src="https://user-images.githubusercontent.com/507615/29212866-421b11d8-7ed3-11e7-9ff7-70f213a4f5c0.png">

还有，楼主截图里超出 100 是怎么做到的，我重现不出来。

**Comment by paranoidjk** [comment]
这里的问题在于：
- 显示的字符数是 js 处理过后的
- 控住输入框长度的是html 原生的 maxLength https://github.com/ant-design/ant-design-mobile/blob/master/components/textarea-item/index.tsx#L212

我感觉还不如直接不处理 emoji 比较好...

**Comment by paranoidjk** [comment]
<img width="1136" alt="2017-08-11 20 30 30" src="https://user-images.githubusercontent.com/7971415/29213010-f4fa00de-7ed3-11e7-84e3-feda296171d3.png">

感觉这种是做富文本输入组件才适合去解决的问题，我们就只是对原生的 textarea 包装了一下。

textarea maxLength 肯定是针对 `String.prototype.length` 的。

**Comment by paranoidjk** [comment]
想到了一个 trick.. 我改一下

**Comment by lgmcolin** [comment]
@paranoidjk  我这边测试还是遇到了这个问题，有表情情况下统计有问题
antd-mobile version: 1.6.11
ios 下测试表现看下图：
<img width="377" alt="2017-11-01 20 41 41" src="https://user-images.githubusercontent.com/5249520/32275311-cb9b73ea-bed8-11e7-8937-986ceec20ff6.png">

**Comment by silentcloud** [comment]
![image](https://user-images.githubusercontent.com/1698185/32599734-5e6d2ae2-c578-11e7-81c8-61a801254fc5.png)

正则替换一个 🇩🇪 是 2 个字符，value 取值是 4 个字符

**Comment by silentcloud** [comment]
![image](https://user-images.githubusercontent.com/1698185/32601985-73057106-c57f-11e7-86e2-65fbaf101582.png)

哪里能找到全的  emoji 正则

**Comment by silentcloud** [comment]
![image](https://user-images.githubusercontent.com/1698185/32602156-15ef2f7e-c580-11e7-976c-444eff4fa424.png)
怎么全？

**Comment by silentcloud** [comment]
textareaItem 不是富文本编辑器，这个问题目前就这样，也没有一个能覆盖全的正则，apple 也一直在新增 emoji。不处理了
