### ISSUE TITLE
设计稿宽度是750px时要怎么如何配置pxtorem的rootValue？

### ISSUE THREAD

**Issue by xd199153** [ant-design/ant-design-mobile#1665]
### Version
1.6.0

### Environment
任意环境

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE](https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE)

### Steps to reproduce
高清方案中提到默认1rem=100px ，也就是等于说antd的设计稿是1000px。
但我的设计稿是750px的。
在pxtorem 插件中设置rootValue为100还是设置75都会导致其中一个转换不正确。
(设置75，正常还原了设计稿，但antd组件显示偏大。设置为100，antd显示正常，但设计稿还原偏小。)
我要怎么做呢才能即还原设计稿又正常显示antd呢？

### What is expected?
正常转换px到rem

### What is actually happening?
未正常转换px到rem

---
实在万不得已开issue来问使用方法，翻看文档和教程和群友，好像都默认大家使用的设计稿是1000px的。😂

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE#2-%E7%94%A8%E6%88%B7%E4%B8%9A%E5%8A%A1%E6%A0%B7%E5%BC%8F%E4%BB%A3%E7%A0%81%E4%BB%A5-px-%E4%B8%BA%E5%8D%95%E4%BD%8D%E4%BD%BF%E7%94%A8-postcss-pxtorem-plugin-%E8%BD%AC%E6%88%90-rem-%E5%8D%95%E4%BD%8D

https://gw.alipayobjects.com/os/rmsportal/dVgyohpfmDMFFeDasFns.js

**Comment by xd199153** [comment]
这篇文章我看了不下10遍了😂。 能否点拨一下

**Comment by paranoidjk** [comment]
https://github.com/ant-design/antd-mobile-samples/blob/master/web-webpack/webpack.config.js#L67
