### ISSUE TITLE
i wanna my ImagePicker  contains 5 or other numbers of items in one row

### ISSUE THREAD

**Issue by hopperhuang** [ant-design/ant-design-mobile#1666]
### What problem does this feature solve?
it can resolve the problem that ImagePicker  can flexbly contains several numbers of items what ever you want 

### What does the proposed API look like?
```
<ImagePicker 
  howManyItemsInOneRow={serveral u want}
/>
```

**Comment by paranoidjk** [comment]
Normally ImagePicker will show 4 item one row, you can see ios photo or what ever other app.

Your use case is very rare，sorry that we do not have enough time to support it.

PS. Pull Request to help us support this feature is welcome.
