### ISSUE TITLE
when i run npm start to run my application via env 'developmemnt'

### ISSUE THREAD

**Issue by donggw2030521** [ant-design/ant-design-mobile#1668]
ERROR in ./node_modules/rmc-list-view/es/ListView.js
Module not found: Error: Can't resolve 'react-sticky' in '/Users/wacai/ProjectsOnGitlab/sfc-wechat/node_modules/rmc-list-view/es'
 @ ./node_modules/rmc-list-view/es/ListView.js 17:0-55
 @ ./node_modules/rmc-list-view/es/index.js
 @ ./node_modules/antd-mobile/lib/list-view/index.web.js
 @ ./app/components/mine/bill/bill-list/index.js
 @ ./app/containers/mine/bill/index.js
 @ ./app/routes/index.js
 @ ./app/index.js
 @ multi webpack-dev-server/client?http://172.18.105.194:8081/ webpack/hot/dev-server ./index

**Comment by donggw2030521** [comment]
这是你们的依赖吧，默认怎么没有？

**Comment by warmhug** [comment]
试试最新版 rmc-list-view
