### ISSUE TITLE
用代码切割，打包后运行报错：Uncaught Error: Minified React error #105;

### ISSUE THREAD

**Issue by wuyafeiJS** [ant-design/ant-design-mobile#1669]
### Version
1.6.0

### Environment
mac

### Reproduction link
[https://github.com/wuyafeiJS/antm-dva-webpack/blob/master/src/router.js](https://github.com/wuyafeiJS/antm-dva-webpack/blob/master/src/router.js)

### Steps to reproduce
代码拉下来运行，点击‘我的权益’切换路由

### What is expected?
能正常使用代码切割功能

### What is actually happening?
报错

---
再ant-design（pc）能正常使用

**Comment by deot** [comment]
#1650 #1646

**Comment by paranoidjk** [comment]
@wuyafeiJS `npm install & npm start` 没有报错，怎么复现？

**Comment by wuyafeiJS** [comment]
@paranoidjk ,页面能正常启动，也能正常切割出文件。报错发生在路由切换的时候。我之前google了这个报错，在MaterialUI上也出现过这种问题，它们的解决办法是切换相应的UI版本。我这边试了好几个ant-mobile的版本依旧还是报错。顺便说一句，在ant-design PC版则不会有这种问题。感谢解答！
