### ISSUE TITLE
tab 优化和增强

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#167]
1. tab切换给人感觉比较慢

2. 考虑增加这样的demo或功能：tab项中内容拉到底部、再拉动时、提示并自动切换到下一个 tab 项（来自业务需求，类似无线天猫详情页 https://detail.m.tmall.com/item.htm?id=43146395990 ）

![gg](https://cloud.githubusercontent.com/assets/2011119/17998181/a837b67a-6ba5-11e6-8a98-7a1a24fd022c.gif)

**Comment by silentcloud** [comment]
第一点，之前就发现了； 第二点属于业务需求，到时候增加一个 demo 好了

**Comment by yiminghe** [comment]
tab 慢，是不是动画时间长了

**Comment by silentcloud** [comment]
仔细看了天猫那个切换实现，那个跟 tab 没关系的，都是在一屏的内容里做的，这个太业务化，关掉了
