### ISSUE TITLE
RN中报错 ExceptionsManager.js:65 _react2.default.createClass is not a function

### ISSUE THREAD

**Issue by byk04712** [ant-design/ant-design-mobile#1684]
### Version
1.6.2

### Environment
mac 环境如下： node v8.1.4      npm v5.3.0        react-native-cli: 2.0.1        react-native: 0.47.1 

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/](https://github.com/ant-design/ant-design-mobile/)

### Steps to reproduce
mac 环境如下：
node v8.1.4
npm v5.3.0
react-native-cli: 2.0.1
react-native: 0.47.1 

根据错误查看到错误信息为 `node_modules/rn-topview` 中抛出的异常，到 package-lock.json 中搜索 `rn-topview` 查看到

![image](https://user-images.githubusercontent.com/6211302/29300905-2711721c-81ab-11e7-92cb-d66899462e61.png)

antd-mobile 在使用它，根据 [react](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) 官网给出如下说法
`
// Before (15.4 and below)
var React = require('react');

var Component = React.createClass({
  mixins: [MixinA],
  render() {
    return <Child />;
  }
});

// After (15.5)
var React = require('react');
var createReactClass = require('create-react-class');

var Component = createReactClass({
  mixins: [MixinA],
  render() {
    return <Child />;
  }
});
`

- 现在知道怎么解决这个报错了，terminal 进入到 node_modules/rn-topview 
- `npm install create-react-class --save`
- 在 topView.js 第一行添加导入 `var createReactClass = require('create-react-class');`
-  将代码中 _react2.default.createClass 替换为 createReactClass

此问题解决，如果出现其他类似错误，解决问题思路类似。
在此希望 antd-mobile 在后续的版本中修复这个 issues ，不然每次安装 antd-mobile 后都要做这么一步操作，太麻烦了。

### What is expected?
在terminal执行 `npm install antd-mobile` 之后就能使用 antd， 不需要做此步操作

### What is actually happening?
在terminal执行 `npm install antd-mobile` 之后， import antd-mobile 出现如标题所示的错误。

**Comment by paranoidjk** [comment]
请暂时先使用 react 15.

react 16 废弃了 createClass，rn-topview 还未对此做兼容。

**Comment by afc163** [comment]
rn-topview 怎么连 repo 都找不到。

**Comment by paranoidjk** [comment]
@afc163 在内网 @silentcloud 的个人仓库，我改一下吧。

**Comment by silentcloud** [comment]
嗯 好

**Comment by silentcloud** [comment]
fixed with rn-topview@0.1.4
