### ISSUE TITLE
Android  InputItem  type=number failed

### ISSUE THREAD

**Issue by weishijun14** [ant-design/ant-design-mobile#1687]
### Version
1.6.3

### Environment
Android   7.1.1 , weChat 6.5.10 , react 15.5.4 

### Steps to reproduce
```
             <InputItem
              type="number"
              placeholder="请输入6位验证码"
              maxLength="6"
              clear
            >验证码</InputItem>
```

### What is expected?
when focus on inputItem, soft number keyboard appear

### What is actually happening?
when focus on inputItem, soft QWERTY keyboard apper

---
其他的低版本安卓手机也有此问题。

**Comment by paranoidjk** [comment]
number keyboard need native support.

use input type="money".
