### ISSUE TITLE
i wanna my ImagePicker contains just one image for Avatar upload,just like antd-design, not to use flex four image,

### ISSUE THREAD

**Issue by jdwdw** [ant-design/ant-design-mobile#1688]
### What problem does this feature solve?
it can resolve the problem that upload Avatar just for one image ,not to use flex for image area, just like this in antd-design

### What does the proposed API look like?
<AvatarPicker 

/>

**Comment by margin-0** [comment]
He can also refer to uploading a picture,Is that what you're saying?
![efa95c2e-3792-4bf9-9f42-b6f76cdc75e3](https://user-images.githubusercontent.com/23308724/29399916-ac3fef3c-835d-11e7-8260-3a6bc26a274d.png)

**Comment by jdwdw** [comment]
![qq 20170817165259](https://user-images.githubusercontent.com/16699054/29404286-3682b53a-836d-11e7-9f49-531fd5700eeb.png)
@margin-0 thank you for your answer i have use rc-upload to make my AvatarPicker,what just like antd-design do, to fix my question, but i still hope there have an AvatarPicker in  antd-design-mobile .

**Comment by paranoidjk** [comment]
Sorry, we have no  plan to add this component. Since it's not a very common usage and you can simply implement it in your own project.
