### ISSUE TITLE
ios prompt bug...

### ISSUE THREAD

**Issue by weishijun14** [ant-design/ant-design-mobile#1689]
### Version
1.6.3

### Environment
ios v10.3.3 & v8.1.2, weChat v6.5.9 & v6.5.10

### Steps to reproduce
```
<div onClick={() => prompt('默认值', '默认值 defaultValue 类型', [
        { text: '取消' },
        { text: '提交', onPress: value => console.log(`输入的内容:${value}`) },
 ], 'plain-text', '100')} >
```
也可使用 iphone 微信端访问 https://mobile.ant.design/components/modal-cn/ 内的输入弹窗。

### What is expected?
输入弹窗无bug

### What is actually happening?
focus事件混乱，无法正确focus。

**Comment by silentcloud** [comment]
6.5.14 没重现

**Comment by weishijun14** [comment]
@silentcloud  iphone6 微信6.5.14 点击prompt输入框无法正确focus弹出软键盘。

**Comment by paranoidjk** [comment]
iPhone 6sp 微信 6.5.14 https://mobile.ant.design/components/modal-cn/ 没有复现。

欢迎排查下是否是特定机型特定微信版本的问题，可以测试 safari 内是否有此问题。

**Comment by Kroderia** [comment]
react-native 2.1.1版本中会出现同样情况。iPad 5th generation, 模拟器和真机上都会出现。
