### ISSUE TITLE
rc-table 太重、pc 属性强，感觉不适合用到移动端

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#169]

**Comment by silentcloud** [comment]
这个跟上次提及的 rc-tabs 一样

**Comment by silentcloud** [comment]
之前重写了 tabs 也是感觉 rc-tabs 太重，后来承玉还是强烈建议用 rc

**Comment by yiminghe** [comment]
怎么个重法？ 如果移动需要这样的rc-table功能，就用rc-table,和移动有什么关系，除非移动有自己的交互和表现

**Comment by 214132049** [comment]
@yiminghe  npm install 后没有引到 文件  怎么解决啊

**Comment by warmhug** [comment]
一般是 不需要这么多的rc-table功能，只需要 功能简单的普通 table

**Comment by SMbey0nd** [comment]
嗯 功能是一个主要的方面，另一方面是大小。我用 visualizer 看了下，目前项目里面需要实现一个 table 只需要 2.5K 就能满足需求，而引入 rc-table 需要 37.7K ，而且还没算 antd-mobile 的一层包装。其他组件应该也会有这个问题。

**Comment by yiminghe** [comment]
功能和大小相关， 大小问题 @afc163 看下，是否 rc-table 能够拆分成多个可以组合的模块

```
rc-table/lib/table
rc-table/lib/fixcolumntable
```

**Comment by yiminghe** [comment]
拆分参考： https://github.com/react-component/tabs/blob/7.x/examples/antd.js

**Comment by afc163** [comment]
http://mobile.ant.design/components/table/#components-table-demo-fastenedTitle

Mobile 里也有固定列的功能，拆分了这些代码还是要引入。

**Comment by silentcloud** [comment]
这个 issue 关掉了，先保持现状
