### ISSUE TITLE
Imagepicker components in some phones click No response

### ISSUE THREAD

**Issue by margin-0** [ant-design/ant-design-mobile#1693]
### Version
1.6.3

### Environment
Huawei , MEIZU , Mobile phone

### Reproduction link
[http://blm.test.otosaas.com/paotui/?customerUserId=test_long&customerUserPhone=13512119091](http://blm.test.otosaas.com/paotui/?customerUserId=test_long&customerUserPhone=13512119091)

### Steps to reproduce
On mobile phones such as meizu huawei xiaomi, click on the component to not respond, other phones are ok

### What is expected?
Click to get local album

### What is actually happening?
There was no reaction on the phone

---
I tested it , and the meizu phone was for filereader
![196b3a6f-ccef-4b90-b8cc-0c9e35aaf494](https://user-images.githubusercontent.com/23308724/29398146-84370cf8-8355-11e7-8f28-9acdcef87726.png)

**Comment by paranoidjk** [comment]
We just use a html tag `input` with `type=file`, i suggest you write a demo like below to test your phone. If it doesn't support this feature, neither can us do.

```html
<input type="file"></input>
```

**Comment by margin-0** [comment]
I tested a simple demo on the phone with my browser, and it was OK. And in my project to determine whether support, can be supported

**Comment by margin-0** [comment]
Sorry, for example, the example of a line is not responding to a test app.
```js
<input type='file' value='选择图片' />
```
