### ISSUE TITLE
并无issue，只是上来赞以下

### ISSUE THREAD

**Issue by donggw2030521** [ant-design/ant-design-mobile#1696]
webpack3.2.0以上版本，在你们1.6.3以前版本，使用webpack-dev-server的时候都会有bug，就是propTypes的报错！刚试了下已修复！赞！赞！赞！赞！赞！赞！赞！赞！赞！赞！赞！赞！赞！赞！赞！赞！赞！赞！赞！
不过ant-desigin还没修复!!!!

**Comment by afc163** [comment]
>  不过ant-desigin还没修复!!!!

能提供更多信息么？
