### ISSUE TITLE
antd 和 antd-mobile 共存问题

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#17]
![image](https://cloud.githubusercontent.com/assets/2011119/17293407/adef0b4a-5822-11e6-987a-d73752ccea91.png)

这个配置只能选择其一，能否支持 libraryName 为 antd 、antd-mobile 一起

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-antd/issues/41

**Comment by benjycui** [comment]
`antd` 和 `antd-mobile` 的样式是有冲突的，之前官网就碰到这个问题。

好像是盒模型都不一样，要兼容工作量有点大。。。

**Comment by yiminghe** [comment]
不是一起用，是一起打包而已
