### ISSUE TITLE
使用createreactapp创建，svg图片不显示，显示的是碎的图片

### ISSUE THREAD

**Issue by nicelj** [ant-design/ant-design-mobile#1703]
### Version
1.6.3

### Environment
windows7 chrome 59 react 15.6.1

### Reproduction link
[http://localhost:3000/](http://localhost:3000/)

### Steps to reproduce
按照官方文档配置，webpack.config.dev.js直接从官方demo拷贝，运行

### What is expected?
正常显示图片

### What is actually happening?
显示碎图

---
<img src={require('../static/images/tab.svg')} alt="pic"/>
只是这一行代码

**Comment by silentcloud** [comment]
@nicelj 这两个都加了么

![image](https://user-images.githubusercontent.com/1698185/29501308-3fc55b4e-865a-11e7-9603-cf39206dd9ea.png)

**Comment by nicelj** [comment]
都有的，我的webpack.config.dev.js整个文件内容都是从官网的demo里copy出来的，svg-sprite-loader版本也是0.3.1

**Comment by silentcloud** [comment]
@nicelj 代码打包传上来

**Comment by nicelj** [comment]
[fakenetease.zip](https://github.com/ant-design/ant-design-mobile/files/1237688/fakenetease.zip)

app.js里面用的一个img标签显示的svg

**Comment by guangming21** [comment]
@silentcloud roadhog具体怎么配置，dva直接创建的，官方文档太简略了，看不明白

**Comment by silentcloud** [comment]
@paranoidjk roadhog  的，你解答哈

**Comment by silentcloud** [comment]
@nicelj  你 svg 的用法写的有问题

svg 不能用 img 标签啊，

![image](https://user-images.githubusercontent.com/1698185/29504967-ea838ef0-8675-11e7-95c5-428b59ad80ec.png)

```js
import { Icon } from 'antd-mobile';

<Icon type={require('./tabfirst.svg')} />
```

**Comment by nicelj** [comment]
我的天，svg还是图片啊，为什么不能用img标签。。
