### ISSUE TITLE
ios native modal can't show on horizontal  screen

### ISSUE THREAD

**Issue by aizigao** [ant-design/ant-design-mobile#1704]
### Version
1.6.3

### Environment
react-native 0.47

### Reproduction link
[http://null](http://null)

### Steps to reproduce
null 

### What is expected?
ios native could show modal in horizontal screen

### What is actually happening?
ios native can't show modal in horizontal screen
![](https://user-images.githubusercontent.com/14126445/29450392-1d06f2be-8431-11e7-9e85-8d16218e0c64.png)

---
react-native ios上modal 只支持竖屏，需要添加一个 `supportedOrientations` ，rc-dialog上没有加上，已经在 `rc-dialog` 上提了pr，只简单的加一句
```
<Modal
        visible={true}
        supportedOrientations={['portrait', 'landscape']}  // 使ios上支持横屏显示
>
</Modal>
```
 [pr地址](https://github.com/react-component/dialog/pull/64) ， 一个小问题，希望尽快解决下

**Comment by silentcloud** [comment]
@aizigao PR 已合，等 rc-dialog 发个 fix 版本，重新 install 就可以了
