### ISSUE TITLE
ListView es module DataSource issus

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design-mobile#1705]
### Version
antd-mobile@1.6.3 or antd-mobile@2.0.0-alpha.5
rmc-list-view@0.8.5
babel-plugin-import@1.4.0

### Environment
web

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile](http://new-issue.ant.design/?repo=ant-design-mobile)

### Steps to reproduce
```json
{
    "plugins": [
        [
            "import",
            {
                "libraryName": "antd-mobile",
                "libraryDirectory": "es"
            }
        ]
    ]
}
```

```tsx
import {ListView} from 'antd-mobile'
console.log(ListView.DataSource)
```

```bash
> webpack -p
```

### What is expected?
```
ƒ e(t){_()(this,e),y()(t&&"function"==typeof t.rowHasChanged,"Must provide a rowHasChanged function."),this._rowHasChanged=t.rowHasChanged,this._getRowData=t.getRowData||o,this._sectionHeaderHasChanged…
```

### What is actually happening?
```
undefined
```

import lib 版本没问题，webpack-dev-server 没问题，antd-mobile@<=1.5.0 没问题。

直接 import { DataSource } from 'rmc-list-view' 也没问题。

该问题只有打包以后才出现。

**Comment by paranoidjk** [comment]
https://unpkg.com/antd-mobile@1.5.0/es/list-view/index.web.js
https://unpkg.com/rmc-list-view@0.8.5/es/index.js

看起来没问题。

@cncolder 把你的代码 push 到 github 发我本地试试？

**Comment by cncolder** [comment]
我还在研究问题的原因，新建的 next.js 项目中无法重现。

next.js 打包是多入口的，一个页面一个文件，common.js 里放公共代码，策略大概是超过半数的页面引用的代码会放在 common.js 里。

目前的进展改成引入 lib/* ，并且还要哄骗 next.js 把 ListView 和 Accordion 打包到 common.js，暂时解决这个问题。 当前只发现这两个组件有问题。

如果我找到原因，我会再来回复。

**Comment by cncolder** [comment]
又发现了一个 Modal

**Comment by silentcloud** [comment]
ping @warmhug

**Comment by warmhug** [comment]
@cncolder 再试试最新版 2.0-beta 有没问题？

**Comment by silentcloud** [comment]
先关了，有问题再 reopen

**Comment by bigdots** [comment]
请问我发现ListView 采用了StaticRender组件，但是我现在的需求需要触发它的re-render，有什么办法吗

**Comment by warmhug** [comment]
@bigdots 改变 dataSource 。或者比如每个 row 里自己构造组件、在自己组件内 re-render 。
