### ISSUE TITLE
undefined is not an object(evaluating '_react2.default.PropTypes.object')

### ISSUE THREAD

**Issue by byk04712** [ant-design/ant-design-mobile#1707]
### Version
1.6.3

### Environment
os：macos   react-native-cli: 2.0.1   react-native: 0.47.1  npm: 5.3.0   node:  v8.3.0

### Reproduction link
[https://mobile.ant.design](https://mobile.ant.design)

### Steps to reproduce
`npm install antd-mobile --save ` 之后，启动项目报错，`undefined is not an object(evaluating '_react2.default.PropTypes.object')`  查找后发现是 antd-mobile 中使用了 `react-native-camera-roll-picker`  ，而`react-native-camera-roll-picker`里的 ImageItem.js 中使用了 React.PropTypes.object，在新版中 React中，PropTypes 不包含在 React 中，需要单独安装 npm install prop-types --save 。而antd-mobile 中，不仅仅只有 react-native-camera-roll-picker 使用到了它 ，其他几个依赖的项也有使用到。希望官方尽快修复这个 issues。

### What is expected?
npm install antd-mobile 之后能直接使用，不用去修改里面的 React.PropTypes 为  `import PropTypes fron 'prop-types';`   PropTypes

### What is actually happening?
抛异常  undefined is not an object(evaluating '_react2.default.PropTypes.object')

**Comment by silentcloud** [comment]
@byk04712 wait https://github.com/jeanpan/react-native-camera-roll-picker/commit/7baff02d6306b84a471c5d44f7e6c0b5e3e13023 to release
