### ISSUE TITLE
dva 创建工具，不显示Icon,

### ISSUE THREAD

**Issue by guangming21** [ant-design/ant-design-mobile#1708]
看官方文档没看懂，groadhog具体怎么配置，请给出一个具体配置

**Comment by paranoidjk** [comment]
`antd-mobile@1` 的用户先别升级 `roadhog@1.x`: https://github.com/sorrycc/roadhog/issues/372#issuecomment-323042032

demo: https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog

**Comment by guangming21** [comment]
@paranoidjk thanks
