### ISSUE TITLE
使用toast的icon不显示

### ISSUE THREAD

**Issue by liuxingling** [ant-design/ant-design-mobile#1711]
### Version
1.6.3

### Environment
mac、谷歌浏览器60.0.3112.101

### Reproduction link
[https://mobile.ant.design/components/toast-cn/](https://mobile.ant.design/components/toast-cn/)

### Steps to reproduce
"antd-mobile": "^1.6.3",
"svg-sprite-loader": "0.3.1",

使用Toast.success()、Toast.fail()

### What is expected?
显示√和×的图标

### What is actually happening?
不显示√和×的图标

---
我用antd-mobile1.0.0的版本和svg-sprite-loader0.3.0的版本是可行的，升级了就不显示了

**Comment by paranoidjk** [comment]
按这个文档： https://mobile.ant.design/components/icon-cn

还有问题，请抽象出最小可复现的代码，push 到 github 发出来我看看。

**Comment by liuxingling** [comment]
@paranoidjk  我试了一下，roadhog更新到1.1.2，会显示不了icon 还原到之前的0.6.0-beta1版本可以显示
https://github.com/demo-icon/demo-icon/tree/master

**Comment by paranoidjk** [comment]
注：antd-mobile@1 的用户先别升，原因详见 https://github.com/sorrycc/roadhog/issues/372#issuecomment-323042032

https://github.com/sorrycc/roadhog/releases/tag/1.0.0
