### ISSUE TITLE
this is a functional extension on toast

### ISSUE THREAD

**Issue by gametheworld** [ant-design/ant-design-mobile#1712]
### What problem does this feature solve?
A friendly reminder

### What does the proposed API look like?
When I call validateFields method parameter error returned object is, in the form need to Toast display error, error two all need prompt, you can make it
https://ant.design/components/notification/

**Comment by paranoidjk** [comment]
I can not understand what's your problem.

Show some code, or use Chinese is ok.

**Comment by gametheworld** [comment]
error: `{"mname":{message: "张三的姓名为必填", field: "mname"},"zhansName":
{message: "姓名为必填", field: "zhansName"}}`



`this.props.form.validateFields({force:true},(error, values) => {
                    console.log('error',error,'values',values);
                    if(!error){
                        const formData = this.props.formData;
                        this.props.dispatch(setFormStatus());
                        this.props.dispatch(submittingForm(formData,this.props,this.state.actionPath));

                    }else{
                        for (let key in error)
                        {
                            error[key].errors.map((item,index)=>{
                                Toast.fail(item.message, 2);
                            });
                        }
                        this.props.dispatch(setFormStatus());
                    }
                });`


When the call to toast refers to prompt the last one

**Comment by gametheworld** [comment]
![qq 20170821144229](https://user-images.githubusercontent.com/6021628/29506590-0e9d5c22-867f-11e7-832b-62f5e4123012.png)

**Comment by paranoidjk** [comment]
@gametheworld 

When you call `Toast.fail`, we will clean the alreay exist toast in your screen, not like pc, antd-mobile don't support show multi toast at the same time.

And i think this is reasonable, since mobile screen is very small, we shoud't show multi message at the same time. 

You may need:

```js
 error[key].errors.map((item,index)=>{
   setTimeout(() => {
    Toast.fail(item.message, 2);
  }, 2 * index);
```

**Comment by gametheworld** [comment]
If use settimeout friendly to experience, settimeout blocks?The UI can't operation

**Comment by paranoidjk** [comment]
> settimeout blocks?

setTimeout do not block.


And IMO, i suggest you show all error message at one toast. Or you can just show the first error message.

No need to show multi form validate error.

**Comment by gametheworld** [comment]
Ok, I see, thank you.love you
