### ISSUE TITLE
use rc-touchable replace :active pseudo-class

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1717]
https://github.com/ant-design/ant-design-mobile/search?l=Less&q=%26%3Aactive&type=&utf8=%E2%9C%93

**Comment by paranoidjk** [comment]
Safari Mobile 默认不使用:active 状态，除非元素上或<body>上有一个touchstart 事件处理器。
Android 部分存在兼容性问题，且在 a 标签 和 非 a 标签上表现不同

https://github.com/ecomfe/saber-button/issues/1
https://github.com/doyoe/trip#user-content-active
https://developer.mozilla.org/zh-CN/docs/Web/CSS/:active#.E6.B5.8F.E8.A7.88.E5.99.A8.E5.85.BC.E5.AE.B9.E6.80.A7

**Comment by paranoidjk** [comment]
cc @warmhug

**Comment by paranoidjk** [comment]
cc @silentcloud

**Comment by paranoidjk** [comment]
May consider to use https://github.com/ant-design/ant-design-mobile/blob/0.8.x/components/_util/touchableFeedback.tsx replace rc-touchable

But the risk is we will drop support of `onLongPress`.

**Comment by silentcloud** [comment]
[WIP] Consider to drop support of onLongPress

**Comment by silentcloud** [comment]
大概了解了各种方案，权衡利弊，还是保持用 rc-touchable
