### ISSUE TITLE
SeachBar 口碑掌柜onClear时需要支持focus

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#1721]
### Version
1.6.3

### Environment
web

FT

**Comment by paranoidjk** [comment]
基于这个 https://github.com/ant-design/ant-design-mobile/issues/1243

在 onClear 的时候手动调用 focus 就好了

没必要把这些代码逻辑都集成到组件内部。

**Comment by pingan1927** [comment]
问题在于onClear的时候点击了非input区域，input失去了光标，按照交互要求，清楚内容时键盘不应该收起。需要快速再通过脚本获取光标。 #1243 的问题我具体看看 这周会再改一次searchbar

**Comment by silentcloud** [comment]
iOS  原生 searchBar 也是这么个交互，clear 的时候还是 focus 的

**Comment by paranoidjk** [comment]
那就按原生交互来，clear 的时候保证 Input 不要 blur。

**Comment by pingan1927** [comment]
0.9.x 还是好的 1.6.x 因为兼容性去掉了部分客户端的onClear后的focus 被怼的无话可说

**Comment by GuokrSun** [comment]
Version  1.6.4
现在onCancel 不好使了，点了跟 点clear 图标一个效果，不能恢复未点击的那个状态了

**Comment by paranoidjk** [comment]
@GuokrSun 什么机型？能否提供可复现的 demo？

**Comment by pingan1927** [comment]
`onCancel`的默认行为就是`onClear`

**Comment by GuokrSun** [comment]
它不应该回复到 未点击的状态吗

**Comment by paranoidjk** [comment]
@pingan1927 不是的，跟以前行为不一致了，以前点取消是收起 cancel。http://beta.mobile.ant.design/components/search-bar-cn

**Comment by GuokrSun** [comment]
通过『取消按钮』退出激活状态
就是现在不收取 取消 是对的是吗？ 按理应该退出激活状态啊

**Comment by pingan1927** [comment]
@GuokrSun 
```
  onCancel = () => {
    if (this.props.onCancel) {
      this.props.onCancel(this.state.value);
    } else {
      this.onClear();
    }
  }
```

**Comment by GuokrSun** [comment]
就是现在改成 得自己手动加代码了 是吗

**Comment by pingan1927** [comment]
@GuokrSun 你说的我明白，取消按钮的行为自行传入回调，试试看，onClear的代码必须优化。回头我会把onCancel的默认行为去掉。

**Comment by GuokrSun** [comment]
好的 谢谢各位大大

**Comment by paranoidjk** [comment]
Fixed in https://github.com/ant-design/ant-design-mobile/releases/tag/1.6.5
