### ISSUE TITLE
upgrade coverage percent to 80%

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#1722]

**Comment by paranoidjk** [comment]
cc @warmhug @silentcloud @zhang740  

besides source code and style, a component's owner should also be responsible for below things:
- It's test case
- It's api doc, demo code (both chinese and english)
- It's dependence (eg: react-component)

We will use this as a checklist before release 2.0.

**Comment by silentcloud** [comment]
test case 的优先级放低吧，先把专项问题搞定，等优先问题搞完，再补充

**Comment by weiesky** [comment]
80% 可能还只是一个粗放的数值，我们希望一些组件的核心case能够做到完整的覆盖。比如: 数字键盘的点击事件能够正确的输出。

**Comment by paranoidjk** [comment]
@weiesky 是的，这就是我们现在缺的，设计到事件交互上的测试，覆盖率只是参考指标，目的是覆盖核心功能。
