### ISSUE TITLE
请问RefreshControl 下拉刷新 组件，官网文档的代码演示中出现的this.refs.lv.getInnerViewNode()是什么？

### ISSUE THREAD

**Issue by zhengshuai1001** [ant-design/ant-design-mobile#1723]
### Version
1.4.2

### Environment
chrome60

### Reproduction link
[https://mobile.ant.design/components/refresh-control-cn/](https://mobile.ant.design/components/refresh-control-cn/)

### Steps to reproduce
按照官网文档的代码演示写，报错了：Uncaught TypeError: this.refs.lv.getInnerViewNode is not a function

### What is expected?
不报错呗

### What is actually happening?
Uncaught TypeError: this.refs.lv.getInnerViewNode is not a function

**Comment by zhang740** [comment]
演示代码里那两个事件监听是为了处理[#1588](https://github.com/ant-design/ant-design-mobile/issues/1588)这个问题，1.4.2这个版本还不包含这个修改，你可以删除这两个事件监听，或者升级antd-mobile版本。

**Comment by zhengshuai1001** [comment]
我升级ntd-mobile版本至1.6.4了。这会getInnerViewNode不报错了，但this.domScroller.options又是undefined

**Comment by zhang740** [comment]
注意onScroll里需要给`domScroller`赋值，如果还是有问题，请提供复现实例。
```jsx
  onScroll = (e) => {
    this.st = e.scroller.getValues().top;
    this.domScroller = e;
  }
```
