### ISSUE TITLE
请问，为什么我没有引用Icon，却报错Icon props.type is invalid

### ISSUE THREAD

**Issue by zhengshuai1001** [ant-design/ant-design-mobile#1725]
### Version
1.6.3

### Environment
chrome60

### Reproduction link
[https://mobile.ant.design/components/icon-cn/](https://mobile.ant.design/components/icon-cn/)

### Steps to reproduce
请问，npm安装了svg-sprite-loader@^0.3.1，webpack也配置了，页面都没有引用Icon，为什么还是报错了？

### What is expected?
不报错

### What is actually happening?
index.web.js:94

 Icon props.type is invalid, have you set svg-sprite-loader correctly? see https://goo.gl/kN8oiw

**Comment by zhengshuai1001** [comment]
![snipaste_20170823_153947](https://user-images.githubusercontent.com/9513530/29604259-8227e7d4-8819-11e7-92d2-4c9f761d336b.jpg)

**Comment by zhengshuai1001** [comment]
![snipaste_20170823_154149](https://user-images.githubusercontent.com/9513530/29604282-9996471c-8819-11e7-93b4-ea1ff3a85cbb.jpg)

**Comment by weishijun14** [comment]
全局搜索一下啊

**Comment by paranoidjk** [comment]
@zhengshuai1001 你使用了哪个组件？ 有些组件内部自身会引用 Icon 的

**Comment by paranoidjk** [comment]
也可以从 console error 的错误堆栈里面看是哪个文件引用的 icon/index.web.js

**Comment by zhengshuai1001** [comment]
@paranoidjk 我用了以下组件Modal, Popup, TextareaItem, Button, WhiteSpace, WingBlank, SearchBar, SwipeAction, List, ListView, RefreshControl

等一会能重现

**Comment by paranoidjk** [comment]
@zhang740 不少组件，比如 Button 就依赖 Icon。

检查你的 svg 相关配置配置吧。

如果查不出问题。提供一个最小可复现的代码仓库，给出 github 仓库地址。

**Comment by chengshengru** [comment]
我的Webpack@3也配置了这个,用Icon组件无法展示svg

```javascript
// ant  使用Icon需要
const svgDirs = [
    require.resolve('antd-mobile').replace(/warn\.js$/, ''), // 1. 属于 antd-mobile 内置 svg 文件
    // path.resolve(__dirname, 'src/my-project-svg-foler'),  // 2. 自己私人的 svg 存放目录
];
...
{
                test: /\.(svg)$/i,
                loader: 'svg-sprite-loader',
                include: svgDirs, // 把 svgDirs 路径下的所有 svg 文件交给 svg-sprite-loader 插件处理
 }
```

**Comment by paranoidjk** [comment]
@chengshengru 
https://mobile.ant.design/docs/react/introduce-cn#Web-使用方式

<img width="570" alt="2017-08-24 09 34 08" src="https://user-images.githubusercontent.com/7971415/29645329-6493f80c-88af-11e7-8e7d-a612f587c264.png">

**Comment by silentcloud** [comment]
可以直接把代码打包上传到 github 上来

**Comment by paranoidjk** [comment]
Close for no response. And i am pretty sure it must be config problem.

PS. Good news is antd-mobile@2.0 won't need svg loader staff. https://github.com/ant-design/ant-design-mobile/pull/1740

**Comment by zhenzong** [comment]
@chengshengru 
您好，我也用的webpack@3的版本，也按照官网形式配置了，也是报错，不显示icon。
请问，您那边怎么解决的？

**Comment by warmhug** [comment]
@zhenzong 注意 antd-mobile 版本、仔细看相应版本配置

**Comment by zhenzong** [comment]
@warmhug 
webpack: 3.6.0
antd-mobile是: 1.7.0
svg-sprite-loader: 是0.3.1
webpack配置是:
```javascript
var svgDirs = [
    require.resolve('antd-mobile').replace(/warn\.js$/, '')
]

var webpackConfig = {
    ...
    module: {
        rules: [
            ...
            {
                test: /\.(png|jpg|gif|jpeg)$/,
                use: {
                    loader: 'file-loader',
                    options: {
                        name: '[name].[ext]'
                    }
                }
            }, {
                test: /\.(svg)$/,
                exclude: svgDirs,
                use: {
                    loader: 'file-loader',
                    options: {
                        name: '[name].[ext]'
                    }
                }
            }, {
                test: /\.(svg)$/,
                include: svgDirs,
                use: 'svg-sprite-loader'          
            }
            ...
        ]
    }
    ...
}
```
报错信息：
```javascript
VM5756 41:94 Icon props.type is invalid, have you set svg-sprite-loader correctly? see https://goo.gl/kN8oiw
```

我在antd-mobile/Icon/index.web.js里的catch地方添加的log后：
```javascript
_this.renderSvg = function () {
    var type = _this.props.type;

    var svg = void 0;
    try {
        svg = require('./style/assets/' + type + '.svg');
    } catch (e) {console.log(e);} finally {
        return svg;
    }
};
```
显示的异常堆栈：
```javascript
VM5756 41:66 Error: Cannot find module './plus-circle-o.svg'.
    at webpackContextResolve (VM5966 515:28)
    at webpackContext (VM5966 515:23)
    at Icon._this.renderSvg (VM5756 41:65)
    at Icon.render (VM5756 41:88)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (VM5586 413:832)
    at ReactCompositeComponentWrapper._renderValidatedComponent (VM5586 413:859)
    at ReactCompositeComponentWrapper.performInitialMount (VM5586 413:383)
    at ReactCompositeComponentWrapper.mountComponent (VM5586 413:262)
    at Object.mountComponent (VM5519 61:47)
    at ReactDOMComponent.mountChildren (VM5581 411:242)
```
我确实使用plus-circle-o这个type，并且antd-mobile的icon/style/assets目录下却是没有这个svg。 求解！

**Comment by warmhug** [comment]
@zhenzong 是否是这样写的 `<Icon type={require('./plus-circle-o.svg')} />`

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1944

**Comment by zhenzong** [comment]
@warmhug  
不是，
```javascript
<Icon type="minus-circle-o" />
```
都是这么写的。

**Comment by warmhug** [comment]
改成我上边的写法，仔细看文档、你这属于自定义 icon 、antd-mobile 里没这个图标。

**Comment by zhenzong** [comment]
好吧，这个我的锅，，我是从0.x 版本直接升级过来的，没有注意到这个要去

ps： 一个小疑问，为何不全部支持了，是出于什么考虑呢？

**Comment by warmhug** [comment]
@zhenzong 现在升级请直接升级到 2.0 ，明天就发正式版了

**Comment by tylerrrkd** [comment]
`svg-sprite-loader` 不要使用最新版本 使用`0.3.1`即可解决问题。在老老老老老项目中遇到了相同问题。
