### ISSUE TITLE
react native Picker component display position error

### ISSUE THREAD

**Issue by cl1069573062** [ant-design/ant-design-mobile#1728]
### Version
1.6.3

### Environment
    "react-native": "^0.46.1",

### Reproduction link
[https://codepen.io/anon/pen/gxKLYx](https://codepen.io/anon/pen/gxKLYx)

### Steps to reproduce
 <Picker
              extra="请选择"
              data={district}
              title="选择地区"
              onOk={e => console.log("ok", e)}
              onDismiss={e => console.log("dismiss", e)}
            >
              <List.Item arrow="horizontal">选择目的地</List.Item>
            </Picker>
<img width="577" alt="d78572e4-3fb6-49cf-b780-e48050bcf27f" src="https://user-images.githubusercontent.com/15069666/29605753-a6c39188-881e-11e7-8001-8b6113e28710.png">

### What is expected?
fix bugs

### What is actually happening?
Did not fix the bug

**Comment by silentcloud** [comment]
Ok, we will check this

**Comment by cl1069573062** [comment]
@silentcloud  it's only show on Android 。

**Comment by silentcloud** [comment]
@cl1069573062 重新 install 一下
