### ISSUE TITLE
如何添加browserHistorty

### ISSUE THREAD

**Issue by rogerwei** [ant-design/ant-design-mobile#1729]

**Comment by rogerwei** [comment]
`import dva from 'dva';
import { browserHistory } from 'dva/router';
import createLoading from 'dva-loading';
import { Toast, WhiteSpace, WingBlank, Button, Icon } from 'antd-mobile';
import './index.html';
import './index.css';

const ERROR_MSG_DURATION = 3; // 3 秒

// 1. Initialize
const app = dva({
  history: browserHistory
});

// 2. Plugins
// app.use(createLoading());

// 3. Model
// Moved to router.js

// 4. Router
app.router(require('./router'));

// 5. Start
app.start('#root');`

但是不起作用。

**Comment by paranoidjk** [comment]
Please file issue at dva.

https://github.com/dvajs/dva/blob/20a13c3cc1fa01d429a5ab36bbefa551e3ddbd34/docs/API_zh-CN.md#dva-api
