### ISSUE TITLE
引入外部css无效的问题

### ISSUE THREAD

**Issue by ITtong** [ant-design/ant-design-mobile#1734]
![image](https://user-images.githubusercontent.com/19646825/29651287-9df27880-88d2-11e7-9e4b-eeb7c77b90c8.png)
首先贴出报错信息！
![image](https://user-images.githubusercontent.com/19646825/29651310-b1de8a64-88d2-11e7-8858-393d4fbf23fb.png)
CSS文件和组件在同一目录下；
![image](https://user-images.githubusercontent.com/19646825/29651325-c6d1265c-88d2-11e7-80f7-f1d5921e85c3.png)
用import引入css；样式并没有引入进来；
![image](https://user-images.githubusercontent.com/19646825/29651352-ed1c8b26-88d2-11e7-89b5-c2530d0d585b.png)
webpack.config.js配置
![image](https://user-images.githubusercontent.com/19646825/29651429-54dcfd04-88d3-11e7-90ea-5d4fcb54b99b.png)
.roadhogrc.js配置

请问如何配置才能成功引入Index.css

**Comment by paranoidjk** [comment]
Please file issue at roadhog.
