### ISSUE TITLE
antd-mobile 下拉刷新如何指定时间才能加载刷新

### ISSUE THREAD

**Issue by katherinewei** [ant-design/ant-design-mobile#1742]
### What problem does this feature solve?
防止重复调用后台接口

### What does the proposed API look like?
```javascript
refreshControl={
    <RefreshControl
    refreshing={refreshing}
    time={time}
    onRefresh={onRefresh} />
}
```

**Comment by zhang740** [comment]
`RefreshControl`提供`onRefresh`事件，而事件的后续逻辑应该业务自己来处理，防止重复可以在业务逻辑里添加节流或者其他的执行策略，而这种策略对组件本身没有意义。

**Comment by katherinewei** [comment]
在`onRefresh`可以防止下拉吗？

**Comment by warmhug** [comment]
onRefresh 中 setTimeout 设置你自己想要延迟的时间。
如果不想要下拉刷新效果、就不要设置 refreshControl 属性。

**Comment by zhang740** [comment]
`防止重复调用后台接口` 需要在`onRefresh`里使用节流函数或者其他策略的方法限制触发频率，简单的调用setTimeout是不可以的（当然，节流函数也是用setTimeout实现）。

防止在`加载数据的时候`用户重复下拉，可以在数据开始加载的时候将`refreshing`置为`true`，这时候会持续显示加载中，在数据加载完成后置回`false`。

**Comment by katherinewei** [comment]
你这样说的不也是重复调用了吗？官网目前的做法不就是你说的这样吗？我之前是用`settimeout`防止的，确实是无法实现的。我是想在一段时间内不重复调用，而不是在请求完成之后还能继续加载呀~一般情况下数据在几秒之内是不会有变化的，所以加载的还是相同数据，这样就重复请求了吧。

**Comment by zhang740** [comment]
那就加节流函数啊，根据你的业务策略来。

简单的例子：
```javascript
let timer;
throttle = () => {
  if (timer) return;

  // 执行你的业务逻辑，比如加载数据
  getData();

  timer = setTimeout(() => {
    timer = undefined;
  }, 60 * 1000);
};
```

如果连下拉刷新的组件都不想显示，让用户无法下拉，那么就需要控制refreshControl属性，置空就不显示。

**Comment by paranoidjk** [comment]
为什么不设计成一次下拉过程只触发一次 onRefresh (超过阈值且释放手势)?
