### ISSUE TITLE
cannot add image to use `imagePicker` in android webview 

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1743]

**Comment by paranoidjk** [comment]
华为原生浏览器，可以选择，无法预览

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/search?utf8=%E2%9C%93&q=ImagePicker+android&type=Issues

这个感觉不是 web 能解决的问题。我们只是普通的 `Input type = file`

**Comment by silentcloud** [comment]
额，貌似是我手机里原来图片有问题，我重新拍了一张，上传是 ok 的

**Comment by silentcloud** [comment]
其他人还遇到的话，就看看是不是 native 设置不对

http://www.cnblogs.com/nmdzwps/p/5841509.html

**Comment by paranoidjk** [comment]
@silentcloud 加到 https://github.com/ant-design/ant-design-mobile/wiki/FAQ
