### ISSUE TITLE
MoneyKeyboard 键盘 border 非高清（master 分支）

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1744]

**Comment by paranoidjk** [comment]
等 https://github.com/ant-design/ant-design-mobile/pull/1736 完成，我再来处理这个键盘高清样式。

cc @pingan1927

**Comment by paranoidjk** [comment]
@pingan1927 有兴趣的话也可以一起处理，将你 1.x 的代码搬到 master 的时候，会遇到边框使用 hairline mixin 替换的需求。
