### ISSUE TITLE
why 2.0 use 'px' replace 'rem'? does this breaking change still support HD screen?

### ISSUE THREAD

**Issue by postgetme** [ant-design/ant-design-mobile#1747]
### What problem does this feature solve?
help me to understand the breaking change.

### What does the proposed API look like?
no

**Comment by paranoidjk** [comment]
Please wait our upgrade doc.

Our code use px have no influence on your usage. You have confiugured postcss-px-to-rem in antd-mobile@1.x, you can keep it if you needed.

**Comment by WangYang-Rex** [comment]
@paranoidjk antd-mobile组件使用的px，在iphone6plus中显示过小，如何设置可以将组件的px转换为rem呢
![image](https://user-images.githubusercontent.com/7553998/31604916-5b5de578-b22a-11e7-922b-82924959a4e6.png)

**Comment by warmhug** [comment]
@WangYang-Rex 为什么不看升级文档呢

**Comment by WangYang-Rex** [comment]
不是从老版本升级上来的，就没去看，我去看看
