### ISSUE TITLE
SegmentedControl api 怎么不和 Tab 一致？

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#175]
如题，并且 SegmentedControl 的`selectedIndex`并不是受控的？这样难满足业务需求；其他API是否也需要再讨论下？

业务反馈 SegmentedControl 和原来 tab 组件的 http://mobile.ant.design/components/tabs/#components-tabs-demo-capsule 胶囊选项卡用法差别太大，不利于方便切换和复用。

**Comment by silentcloud** [comment]
segmentedControl 参见 rn  @warmhug

**Comment by warmhug** [comment]
selectedIndex 这个不是受控的？加个`componentWillReceiveProps` 改变下 selectedIndex 吧？

**Comment by warmhug** [comment]
文档上，也链接下 rn 文档吧，说明下是来自 rn ，不然很多人不能理解为什么不跟 tab 保持一致。

**Comment by silentcloud** [comment]
@warmhug ok，这个是遗漏了，bug， 我这会处理

**Comment by silentcloud** [comment]
09e6654be8a7671e104c27a8fcb48b9eb6e15021
