### ISSUE TITLE
2.0 hairline mixin 异常收集

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1750]
iOS webview 
- [x] Card
- [x] Modal.propmt
- [x] Button
- [x] InputItem[type="money"] 之 moneyKeyboard

**Comment by paranoidjk** [comment]
http://beta.mobile.ant.design/kitchen-sink/components/card?lang=zh-CN#card-demo-0

<img width="469" alt="2017-08-28 14 19 41" src="https://user-images.githubusercontent.com/7971415/29761512-f7a63264-8bfb-11e7-9d62-2b4f967717ed.png">

是指上面的边框有点不对？

**Comment by silentcloud** [comment]
@paranoidjk 

https://mobile.ant.design/kitchen-sink/components/card

![image](https://user-images.githubusercontent.com/1698185/29761974-94c41e24-8bfe-11e7-9dcd-4f4ba38dedfb.png)

**Comment by paranoidjk** [comment]
@ustccjw 帮忙看下？ http://beta.mobile.ant.design/kitchen-sink/components/card?lang=zh-CN#card-demo-0 在 2/3 倍屏下，带圆角的全边框实现有点瑕疵。

**Comment by warmhug** [comment]
plus 3x 屏下，貌似用 `(-webkit-min-device-pixel-ratio: 2), (min-resolution: 2dppx)` 这个 2x 的样式没问题

**Comment by silentcloud** [comment]
@paranoidjk  Modal prompt 输入框左边的线也没有了  android webview， iOS 正常

**Comment by silentcloud** [comment]
- [ ] Button 的圆角展示也有问题

**Comment by silentcloud** [comment]
我汇总到顶部

**Comment by paranoidjk** [comment]
cc @pingan1927

**Comment by pingan1927** [comment]
模拟的金额键盘的边框是通过td的border以及table的`border-collapse` 属性来实现。其他方式都会比较麻烦

**Comment by warmhug** [comment]
细线有 z-index 设置，需要 review 所有涉及到 z-index 顺序的组件，避免 组件组合使用时 z-index 显示错乱问题、如下图
![image](https://user-images.githubusercontent.com/2011119/29859129-3aff0386-8d93-11e7-92a3-e285231c395a.png)
