### ISSUE TITLE
svg 方案替换后，部分 demo 中的 svg 失去 fill-rule 控制，颜色展示问题

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1751]
比如： steps：
<img src="https://user-images.githubusercontent.com/1698185/29762004-b46867b2-8bfe-11e7-9311-5ad6e41adcfb.png" width="300" /><img src="https://user-images.githubusercontent.com/1698185/29762016-c09f8f10-8bfe-11e7-91c7-5e914844fc50.png" width="300" />

左边 master，右边之前的， 应该还有其他 demo 也是这种情况

https://stackoverflow.com/questions/24933430/img-src-svg-changing-the-fill-color

**Comment by paranoidjk** [comment]
这种 img  src 是我为了方便直接替换的 demo 代码，所以用了在线 svg 文件。

理论上在用户代码里，这个颜色需要他自己处理，可能是用一个 png 图片，可能是用 svg loader。

**Comment by silentcloud** [comment]
@paranoidjk 嗯，理解的，但是我们的 demo 要展示正常

**Comment by paranoidjk** [comment]
@warmhug 这种 demo 原来用到 require locale svg 的情况，有没有必要处理？要搞的话只能导出多个颜色的 png 算了，我是不太想在 antd-mobile@2.0 里为了 demo 代码又继续保留 svg-sprite-loader 的，我想把 svg 这个概念隐藏掉。

https://github.com/ant-design/ant-design-mobile/blob/master/components/steps/demo/basic.md

**Comment by silentcloud** [comment]
@paranoidjk 不用 svg-sprite-loader， 只需要把 img src 的那个 svg 手动在源代码里加上 fill 颜色，让 demo 看起来正常就行了，改好重新上传 cdn，改一下 src 地址就可以了

**Comment by paranoidjk** [comment]
@silentcloud 那我干脆在 sketch 里改颜色，导出不同颜色的 svg 算了。

**Comment by silentcloud** [comment]
嗯 也可以，都行的，我 issue 的意思仅仅让让 demo 看起来 ok

**Comment by paranoidjk** [comment]
Steps 文档注明： 只有使用 inline 的 svg icon，Steps 组件的自动添加 icon 颜色功能才能生效。

https://github.com/ant-design/ant-design-mobile/blob/master/components/steps/style/index.less#L26

**Comment by silentcloud** [comment]
@paranoidjk 

Toast  的 custom icon 例子也有这个问题
