### ISSUE TITLE
money keyboard cursor position

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1755]
https://mobile.ant.design/components/input-item-cn

**Comment by paranoidjk** [comment]
cc @pingan1927 看是改默认在左边，还是 @silentcloud  说的支持多种位置

**Comment by pingan1927** [comment]
前两天团结还发现的字体跟真实的input有些区别。mark下

**Comment by peter0011** [comment]
支持多种位置的场景是什么？暂时没有想到

**Comment by paranoidjk** [comment]
@peter0011 已经放出去的实现是在右边，在小版本不能直接改成左边，而又用户有需要要在左边，所以我想加个 api 控制一下。

**Comment by pingan1927** [comment]
刚刚看了下，要控制光标在左边，改动还不小。

**Comment by warmhug** [comment]
业务反馈：

- 首次没问题，输入内容、点 x 后再点进去，焦点有时候不能聚焦
- 点击 money keyboard 虚拟键盘 输入速度 比 系统原生键盘 慢
- 可以多次连续输入 小数点`.` 考虑能否组件内做控制

再仔细测试下

**Comment by paranoidjk** [comment]
- [ ] 事件加在 fakeInput container 上 eg: 业务为了实现左侧开始，覆盖了 fakeInput 的宽度导致无法唤起

**Comment by paranoidjk** [comment]
@warmhug 花呗的交互就是从左边开始，这个需求要做，我一起做掉

**Comment by paranoidjk** [comment]
@warmhug 
> 可以多次连续输入 小数点. 考虑能否组件内做控制

这一条我没复现，谁反馈的？至少给个可复现 demo。
