### ISSUE TITLE
组件InputItem的type为"number"时，因无法输入减号，不能展示负数

### ISSUE THREAD

**Issue by Linkinzoo** [ant-design/ant-design-mobile#1757]
### What problem does this feature solve?
组件InputItem的type为"number"时，因无法输入减号，不能展示负数

### What does the proposed API look like?
参考添加bool类型字段negative，控制组件是否可以输入减号

**Comment by paranoidjk** [comment]
@pingan1927 是否要放开这个限制？ https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.tsx#L225

**Comment by pingan1927** [comment]
@Linkinzoo @paranoidjk 如果放开这个限制，就无法唤起原生的数字键盘。这是鱼和熊掌不可兼得的生动写照。

**Comment by paranoidjk** [comment]
@pingan1927 那文档备注一下，input type number 不支持正负号，需要正负号的数字，请用 text。
