### ISSUE TITLE
各组件支持接收 data-* 放到元素上（web）

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#176]
业务埋点需要

**Comment by yiminghe** [comment]
直接外层套个标签，不需要组件改动

**Comment by warmhug** [comment]
弹出层类，套不了。这样做也不好看

**Comment by yiminghe** [comment]
能不加就不加，不符合正交原则

**Comment by silentcloud** [comment]
这种业务类的需求，跟组件没关系，不应该要组件来满足业务需求

**Comment by yiminghe** [comment]
弹出类需要的话这样加 https://github.com/react-component/m-date-picker/commit/f344435781aead87417aa40a042ec1741a0983f2
