### ISSUE TITLE
自定义svg 无法显示

### ISSUE THREAD

**Issue by chjm872** [ant-design/ant-design-mobile#1760]
var xlinkHref = this.renderSvg();
            var outerIcon = void 0;
            if (!xlinkHref) {
                outerIcon = true;
                xlinkHref = type;
                if (!/^#/.test(type)) {
                    console.error(warnMsg);
                }
            } else {
                if (!/^#/.test(xlinkHref)) {
                    console.error(warnMsg);
                }
                xlinkHref = '#' + type;
            }

这段代码判断什么意思，Icon type 自定义svg 无法显示，这段代码报错 ，type 必须 # 开头吗

**Comment by paranoidjk** [comment]
不是，这只是个校验。请确认你svg-sprite-loader版本和配置
