### ISSUE TITLE
能否增加属性用于控制Accordion展开动画的方向？

### ISSUE THREAD

**Issue by lmrwork** [ant-design/ant-design-mobile#1764]
### What problem does this feature solve?
因为目前Accordion展开动画的方向是与手指滑动方向相反，在Accordion内容区域较长的情况下，这样的体验并不是很舒服；所以希望增加属性用于控制Accordion展开动画的方向。

-------translate by google-------

Because the current Accordion expand animation direction and fingers sliding in the opposite direction, in the Accordion content area a long case, such an experience is not very comfortable;Want to increase property is used to control the direction of Accordion animated

### What does the proposed API look like?
<Accordion animationConfig={type:'fade', 'direction':‘down’} ...otherProps>

**Comment by warmhug** [comment]
还是不太懂你想要的动画方式是什么

**Comment by silentcloud** [comment]
@lmrwork  you can use `openAnimation` to do that, ref https://github.com/react-component/collapse#props-1
