### ISSUE TITLE
PickerView

### ISSUE THREAD

**Issue by XiaofanFTD** [ant-design/ant-design-mobile#1765]
### Version
1.6.5

### Environment
react: 16.0.0-alpha.12 react-native: 0.47.2

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
 <PickerView
                    ref={'pickerView'}
                    data={this.state.data}
                    value={this.state.value}
                    cascade={false}
                    cols={this.props.data.length}
                    onChange={this._onChange.bind(this)}
                >
     </PickerView>

### What is expected?
3列数据，横向排列

### What is actually happening?
3列数据，竖向排列

**Comment by paranoidjk** [comment]
Sorry, i dont't know what's your problem.  Please give more detail info.
