### ISSUE TITLE
PickerView

### ISSUE THREAD

**Issue by XiaofanFTD** [ant-design/ant-design-mobile#1766]
![pickerview](https://user-images.githubusercontent.com/13959304/29860292-433ef4d8-8d2b-11e7-81e2-43ef68c6265b.jpg)
### Version
1.6.5

### Environment
react: 16.0.0-alpha.12; react-native: 0.47.2

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
<PickerView
ref={'pickerView'}
data={this.state.data}
value={this.state.value}
cascade={false}
cols={this.props.data.length}
onChange={this._onChange.bind(this)}
/>

### What is expected?
flexdirection: row

### What is actually happening?
flexdirection: column

**Comment by silentcloud** [comment]
在这里已经修掉了  https://github.com/ant-design/ant-design-mobile/issues/1770
