### ISSUE TITLE
picker native 布局出错

### ISSUE THREAD

**Issue by aizigao** [ant-design/ant-design-mobile#1770]
### Version
1.6.5

### Environment
ios 10.3  react-native 0.44.3

### Reproduction link
[http://null](http://null)

### Steps to reproduce
我的代码如下，在 1.6.3下的好的， 新版本变成的 垂直布局
```jsx
import { Picker, List, WhiteSpace } from 'antd-mobile'
import React from 'react'
import { View, Text } from 'react-native'

const seasons = [
  [
    {
      label: '2013',
      value: '2013',
    },
    {
      label: '2014',
      value: '2014',
    },
  ],
  [
    {
      label: '春',
      value: '春',
    },
    {
      label: '夏',
      value: '夏',
    },
  ],
]

class PickerExample extends React.Component {
  state = {
    data: [],
    cols: 1,
    pickerValue: [],
    asyncValue: [],
    sValue: ['2013', '春'],
  };

  render() {
    return (
      <View>
        <WhiteSpace size='lg' />
        <List style={{ backgroundColor: 'white' }} className='picker-list'>
          <Picker
            data={seasons}
            title='选择季节'
            cascade={false}
            extra='请选择(可选)'
            value={this.state.sValue}
            onChange={v => this.setState({ sValue: v })}
          >
            <List.Item arrow='horizontal'>选择季节（多列，不联动）</List.Item>
          </Picker>
        </List>
      </View>)
  }
}

export default PickerExample

```

### What is expected?
正常显示
![image](https://user-images.githubusercontent.com/14126445/29862512-4f8b21c0-8d9f-11e7-8d1b-703d006c3f0e.png)

### What is actually happening?
显示如下
![image](https://user-images.githubusercontent.com/14126445/29862125-32fa20fc-8d9e-11e7-9889-41517e2fddab.png)

**Comment by silentcloud** [comment]
@aizigao 这个问题记得是修过的

https://github.com/react-component/m-cascader/commit/0a769b66977a5a698d190a18ef66c2db6a33a8ba

**Comment by aizigao** [comment]
@silentcloud 那估计是你 联动 cascade = false的时候没有改，我看了代码，cascade = false 的时候用的是rmc-picker不是rmc-cascader
https://github.com/ant-design/ant-design-mobile/blob/master/components/picker/AbstractPicker.tsx#L5

https://github.com/ant-design/ant-design-mobile/blob/master/components/picker/AbstractPicker.tsx#L85

**Comment by silentcloud** [comment]
@aizigao 嗯，是的，没注意看，已经修了，等发布就行了

**Comment by bengele** [comment]
老板，@silentcloud 这个bug的修复将会更新到哪个版本里面？

**Comment by aizigao** [comment]
啥时候发布，我不想复写 render方法了 @silentcloud

**Comment by silentcloud** [comment]
@bengele @aizigao 明天发

**Comment by silentcloud** [comment]
cc @zhang740 明天发个 1.6.6

**Comment by bengele** [comment]
thanks!!!
