### ISSUE TITLE
ios下，Modal组件，蒙层点击没有反应

### ISSUE THREAD

**Issue by WangXueZhi** [ant-design/ant-design-mobile#1771]
### Version
1.6.5

### Environment
ios

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/0b2c14f9a9a6439a6ea70e768137f7c1d48122a3/components/modal/Modal.tsx#L49](https://github.com/ant-design/ant-design-mobile/blob/0b2c14f9a9a6439a6ea70e768137f7c1d48122a3/components/modal/Modal.tsx#L49)

### Steps to reproduce
ios下，Modal组件，蒙层点击没有反应，onClose也不能回调，发现在如下位置阻止了默认事件

```javascript
(0, _createClass3['default'])(Modal, [{
        key: 'isInModal',
        value: function isInModal(e) {
            if (!/\biPhone\b|\biPod\b/i.test(navigator.userAgent)) {
                return;
            }
            // fix touch to scroll background page on iOS
            var prefixCls = this.props.prefixCls;
            var pNode = function (node) {
                while (node.parentNode && node.parentNode !== document.body) {
                    if (node.classList.contains(prefixCls)) {
                        return node;
                    }
                    node = node.parentNode;
                }
            }(e.target);
            if (!pNode) {
                e.preventDefault();
            }
            return true;
        }
    }, {
```

在chrome v60  上，会报警告[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080。

### What is expected?
点击蒙层关闭

### What is actually happening?
点击蒙层没反应

**Comment by paranoidjk** [comment]
@WangXueZhi 设置 `maskClosable={true}` 了吗？

**Comment by paranoidjk** [comment]
close for no response.
