### ISSUE TITLE
input-item 带 clear 的输入，点击 clear 的时候不应该丢失焦点

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1775]
和 native 一致
![show](https://user-images.githubusercontent.com/1698185/29903659-976fec8a-8e37-11e7-9ee6-c271559d939b.gif)

**Comment by paranoidjk** [comment]
和上次 SearchBar 做的一样？

**Comment by pingan1927** [comment]
input 也想做的这么复杂？
