### ISSUE TITLE
babel启用"transform-react-inline-elements"， ListView报错

### ISSUE THREAD

**Issue by hufeng** [ant-design/ant-design-mobile#178]
![image](https://cloud.githubusercontent.com/assets/533008/18078845/3dcef56e-6ec0-11e6-97c6-c5469cce126f.png)

**Comment by warmhug** [comment]
看起来是解析错误的缘故，为什么启用这个？

**Comment by hufeng** [comment]
@warmhug http://babeljs.io/docs/plugins/transform-react-inline-elements/
开启这个特性可以减少大量的React.createElement的时间

> Replaces the React.createElement function with a more optimized one for production: babelHelpers.jsx.

> his transform should be enabled only in production (e.g., just before minifying your code) because although it improves runtime performance, it makes warning messages more cryptic and skip important checks that happen in development mode, including propTypes.

**Comment by warmhug** [comment]
使用这种导入方法：
```js
import 'antd-mobile/lib/list-view/style/index.css';
import ListView from 'antd-mobile/lib/list-view';
```
不会报错
