### ISSUE TITLE
Modal组件产生的a标签的href属性是#，对于我们react-route来说会被默认为跳转到 / 路由

### ISSUE THREAD

**Issue by sml782** [ant-design/ant-design-mobile#1780]
Modal组件产生的a标签的href属性是#，对于我们react-route来说会被默认为跳转到 / 路由

**Comment by paranoidjk** [comment]
@sml782 Modal 哪里有 a 标签，能否给一个实例或者截图？

**Comment by silentcloud** [comment]
@paranoidjk 他说的 button， 这个我等会改一下，换成 span 标签

**Comment by paranoidjk** [comment]
@silentcloud Button 不要轻易改，我记得用 a 是有原因的

**Comment by silentcloud** [comment]
我这里的 button 不是用的 Button 组件

**Comment by silentcloud** [comment]
@sml782 我刚在 react-router 里试了哈，并没有重现

我先去掉 href="#"，你也可以在本地去去掉试试看看能行不，如果不行再反馈上来

**Comment by sml782** [comment]
就是这个href="#"的原因
