### ISSUE TITLE
radio rc-form getFieldDecorator

### ISSUE THREAD

**Issue by gametheworld** [ant-design/ant-design-mobile#1782]
### Version
1.4.0

### Environment
samsung galaxy s7 7.1.0 api 25

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile](http://new-issue.ant.design/?repo=ant-design-mobile)

### Steps to reproduce
this.DynamicKey:HomeIs
this.Rules:[ 
                {
                    "required" : true,
                    "message" : "家人是否知晓借款为必选"
                }
            ]
{getFieldDecorator(this.DynamicKey, {rules: this.Rules})(
                        <List renderHeader={() => this.state.label}>
                            {
                                this.state.options.map(i => (
                                    <RadioItem key={i.value} checked={value === i.value}
                                               onChange={()=>this.handleOnChange(i.value)}>
                                        {i.label}
                                    </RadioItem>
                                ))
                            }
                        </List>
                    )}

this.props.form.validateFields({force: true}, (error, values) => {}

If getFieldDecorator function packed in List outside,then validataFiedlds function prompt HomeIs null

If getFieldDecorator packed in List interior ,then page endless render

### What is expected?
If getFieldDecorator in List outside, then validataFiedlds proper functioning

### What is actually happening?
error

---
I don't know if I wrong usage

**Comment by paranoidjk** [comment]
@ant-design-bot markdown

**Comment by gametheworld** [comment]
``` javascript
this.DynamicKey:HomeIs
this.Rules:[
{
"required" : true,
"message" : "家人是否知晓借款为必选"
}
]



return (
                <List>
                    {getFieldDecorator(this.DynamicKey, {rules: this.Rules})(
                        <List renderHeader={() => this.state.label}>
                            {
                                this.state.options.map(i => (
                                    <RadioItem key={i.value} checked={value === i.value}
                                               onChange={()=>this.handleOnChange(i.value)}>
                                        {i.label}
                                    </RadioItem>
                                ))
                            }
                        </List>
                    )}
                </List>
            )
======================================================
rc-form
validateFields

this.props.form.validateFields({force: true}, (error, values) => {
                    console.log('error', error, 'values', values);
                    if (!error) {
                        const formData = this.props.formData;
                        this.props.dispatch(setFormStatus());
                        this.props.dispatch(submittingForm(formData, this.props, this.state.actionPath));
                    } else {
                        let message='';
                        for (let key in error) {
                            error[key].errors.map((item, index)=> {
                                message=message+item.message;
                            });
                        }
                        console.log('message',message);
                        Toast.fail(message, 2);
                        this.props.dispatch(setFormStatus());
                    }
                })



```

![qq 20170901145951](https://user-images.githubusercontent.com/6021628/29958836-49cb6c7a-8f27-11e7-9c3c-21ccdccf0b7f.png)
![qq 20170901150045](https://user-images.githubusercontent.com/6021628/29958842-4d6c4d0e-8f27-11e7-984b-8f76beb7a42a.png)

**Comment by gametheworld** [comment]
@ant-design-bot

**Comment by gametheworld** [comment]
@paranoidjk @ant-design-bot Are there examples of each component in the antd-mobile that matches the use of rc-form?

**Comment by gametheworld** [comment]
@paranoidjk @ant-design-bot 我们正在用antd和antd-mobile做动态表单，我们两个项目都已经开源了，
这个问题的地址是<a href='https://github.com/gametheworld/dynamicform-mobile-client/blob/master/src/components/elements/RadioGroup.js'>Radio Gropu</a>

目前有几个问题卡在表单提交的数据格式验证；pc端已经ok，
dynamicform-mobile-client<a href=''>dynamicform-mobile-client</a>中结合rc-form，一时半会儿还没有处理

**Comment by warmhug** [comment]
如果是 rc-form 的问题，提到 https://github.com/react-component/form 这里。

> 除了 rc-form 外，移动端 推荐 自己写或寻找 更轻量级的 form 验证功能

**Comment by paranoidjk** [comment]
@gametheworld https://github.com/react-component/form#option-object

Radio 的 value key 名是 `checked`， 你要设置 rc-form 的 `option.valuePropName`

**Comment by onreadystatechange** [comment]
@gametheworld 您好，我也遇到了同样的问题，看了您的代码，请问您现在解决了吗?期待您的回复。
