### ISSUE TITLE
在使用popup的时候，当调用show方法的时候，会弹出错误警告

### ISSUE THREAD

**Issue by andylidong** [ant-design/ant-design-mobile#1785]
Warning: BackAndroid is deprecated. Please use BackHandler instead

**Comment by silentcloud** [comment]
我 check 一下

**Comment by silentcloud** [comment]
组件自身没有使用过  `BackAndroid ` 这个控件，检查你自己的代码；

另外我官方 demo 没能重现

**Comment by andylidong** [comment]
好的，我再试一下，我一下我要用picker，怎么修改他的样式呢？在不修改官方的样式情况下

**Comment by paranoidjk** [comment]
@andylidong `props.style` `props.styles`, see source code or demo code.

**Comment by silentcloud** [comment]
@andylidong  RN 组件定义样式文档

http://beta.mobile.ant.design/docs/react/use-with-create-react-app-cn#完成的示例

**Comment by silentcloud** [comment]
@andylidong  看文档 

http://beta.mobile.ant.design/docs/react/use-with-create-react-app-cn#完整的示例

这里有实例和说明 https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui

**Comment by andylidong** [comment]
我想说的是取消和确定的字体颜色设置，因为他们共用一个样式，我不好分别设置他们的颜色

**Comment by silentcloud** [comment]
@andylidong 分别设置颜色要改底层组件，我稍后改一下

**Comment by silentcloud** [comment]
@andylidong 这个只在 2.0 支持哈

**Comment by andylidong** [comment]
好的，谢谢

**Comment by andylidong** [comment]
![image](https://user-images.githubusercontent.com/18454971/31545056-5aaafc90-afe3-11e7-9cae-9f73d9f66e4e.png)
为什么设置itemStyle没有用呢？版本是最新的，没有问题

**Comment by andylidong** [comment]
<Picker
          styles={StyleSheet.create(getPickerStyle())}
          data={area}
          value={areas}
          title={"请选择地区"}
          itemStyle={pickerItem}
          onOk={e => {
            isClick = true;
            this.setState({ areas: e });
          }}
        >
使用itemStyle没有用效果。在一列的时候，cascade没有设置itemStyle也没有用，设置了之后就有作用了，那多行联动的怎么才能产生效果

**Comment by andylidong** [comment]
<Picker
      styles={StyleSheet.create(getPickerStyle())}
      data={area}
      value={areas}
      title={"请选择地区"}
      itemStyle={pickerItem}
      onOk={e => {
        isClick = true;
        this.setState({ areas: e });
      }}
    >
使用itemStyle没有用效果。在一列的时候，cascade没有设置itemStyle也没有用，设置了之后就有作用了，那多行联动的怎么才能产生效果？？？？？

DatePicker的itemStyle怎么设置呢？？？？？

**Comment by silentcloud** [comment]
@andylidong 

> 使用itemStyle没有用效果。在一列的时候，cascade没有设置itemStyle也没有用，设置了之后就有作用了，那多行联动的怎么才能产生效果？？？？？

你版本好多，我 2.0 试没问题哈

> DatePicker的itemStyle怎么设置呢？？？？

这个之前没有自定义设置的需求，应该需要默认现在样式的，你要定制？这样定制的话感觉很奇怪

**Comment by andylidong** [comment]
DatePicker那怎么才能设置每一列的样式呢

**Comment by silentcloud** [comment]
@andylidong 这个暂时不支持，底层可以支持一下，但是不暴露文档给用户。
这个我稍后加一下 @andylidong

**Comment by andylidong** [comment]
再问一下，你们好像把popup移除掉了（在最近的版本中），如果还需要怎么用？

**Comment by silentcloud** [comment]
@andylidong 用 modal 实现，参看 modal 文档

**Comment by andylidong** [comment]
Toast的样式可以提供修改吗，我现在是2.0.0版本的，好像不可以修改样式
