### ISSUE TITLE
List.item中使用icon作为thumb，同时icon使用iconfont，右边距无法设置

### ISSUE THREAD

**Issue by nothingp** [ant-design/ant-design-mobile#1787]
### Version
1.6.5

### Environment
"react-native": "0.44.3",

### Reproduction link
[https://github.com/nothingp/react-native-nothing/blob/master/src/component/me.js](https://github.com/nothingp/react-native-nothing/blob/master/src/component/me.js)

### Steps to reproduce
 <Item
                        thumb={<Icon type={'\ue686'} color="#ff6666" />}
                        arrow="horizontal"
                        onClick={() => this.props.navigator.push({
                            screen: 'Address',
                            animated: false,
                            title: '地址'
                        })}
                    >地址</Item>

### What is expected?
能设置样式

### What is actually happening?
不知道怎么设置样式

**Comment by paranoidjk** [comment]
你的链接打不开。另外请说清楚你想设置什么样式？能否给个图片标注示意一下？

**Comment by silentcloud** [comment]
@nothingp Icon 外层套一个 View

![image](https://user-images.githubusercontent.com/1698185/30198796-4c45fa3a-94a2-11e7-830b-977d9252579c.png)
