### ISSUE TITLE
picker-view这个组件没有rn版本的？官网写的是有的，源码里面的demo却没有native的demo。

### ISSUE THREAD

**Issue by huangnan1994** [ant-design/ant-design-mobile#1788]
### What problem does this feature solve?
不弹框选择

### What does the proposed API look like?
不弹框选择

**Comment by paranoidjk** [comment]
这个组件 web & rn 通用，参考 web 代码 https://github.com/ant-design/ant-design-mobile/blob/1.x/components/picker-view/demo/basic.md

欢迎 PR 帮我们添加
