### ISSUE TITLE
web项目使用ant-mobile总是提示找不到ant-mobile模块

### ISSUE THREAD

**Issue by yuan1995913** [ant-design/ant-design-mobile#179]
本地环境
mac webstrom

- antd-mobile 版本：    "antd-mobile": "^0.7.8",

- 操作系统及其版本：osx
- 浏览器及其版本： chorme

#### 你做了什么？

引入了antd-mobile插件
#### 你期待的结果是：

 像官网一样正常显示

#### 实际上的结果：
按照官网文档操作，但是提示引入文件报错，尝试各种方法始终不行
提示缺少此插件
babelrc文件配置如下：
`{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": [
    ["antd", {
      "style": "css",  // 'less',
      "libraryName": "antd-mobile"
    }]
  ]
}`

报错如下：

ERROR in ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx
Module not found: Error: Cannot resolve module 'antd-mobile/lib/wing-blank/style/css' in /Users/yuan/ListenCloud/client/src/view/Mobile/WeChat/LogInToRegister
 @ ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx 7:11-58

ERROR in ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx
Module not found: Error: Cannot resolve module 'antd-mobile/lib/button/style/css' in /Users/yuan/ListenCloud/client/src/view/Mobile/WeChat/LogInToRegister
 @ ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx 13:12-55

ERROR in ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx
Module not found: Error: Cannot resolve module 'antd-mobile/lib/white-space/style/css' in /Users/yuan/ListenCloud/client/src/view/Mobile/WeChat/LogInToRegister
 @ ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx 19:12-60

ERROR in ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx
Module not found: Error: Cannot resolve module 'antd-mobile/lib/textarea-item/style/css' in /Users/yuan/ListenCloud/client/src/view/Mobile/WeChat/LogInToRegister
 @ ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx 25:12-62

ERROR in ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx
Module not found: Error: Cannot resolve module 'antd-mobile/lib/checkbox/style/css' in /Users/yuan/ListenCloud/client/src/view/Mobile/WeChat/LogInToRegister
 @ ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx 31:12-57

ERROR in ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx
Module not found: Error: Cannot resolve module 'antd-mobile/lib/radio/style/css' in /Users/yuan/ListenCloud/client/src/view/Mobile/WeChat/LogInToRegister
 @ ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx 37:12-54

ERROR in ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx
Module not found: Error: Cannot resolve module 'antd-mobile/lib/slider/style/css' in /Users/yuan/ListenCloud/client/src/view/Mobile/WeChat/LogInToRegister
 @ ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx 43:12-55

ERROR in ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx
Module not found: Error: Cannot resolve module 'antd-mobile/lib/stepper/style/css' in /Users/yuan/ListenCloud/client/src/view/Mobile/WeChat/LogInToRegister
 @ ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx 49:12-56

ERROR in ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx
Module not found: Error: Cannot resolve module 'antd-mobile/lib/switch/style/css' in /Users/yuan/ListenCloud/client/src/view/Mobile/WeChat/LogInToRegister
 @ ./client/src/view/Mobile/WeChat/LogInToRegister/index.jsx 55:12-55

**Comment by liqi07** [comment]
使用可参考项目示例 #56

**Comment by yuan1995913** [comment]
@liqi07 您好 ，按照示例使用
import List from 'antd-mobile/lib/textarea-item'
import InputItem from 'antd-mobile/lib/textarea-item'
方式引入 倒是没那么多报错了 但是还是有一个报错 提示：
ERROR in ./~/antd-mobile/lib/textarea-item/index.js
Module not found: Error: Cannot resolve module 'react-native' in /Users/yuan/ListenCloud/node_modules/antd-mobile/lib/textarea-item
 @ ./~/antd-mobile/lib/textarea-item/index.js 24:19-42

提示缺少react-native模块，按照demo配置了也没有效果

**Comment by liqi07** [comment]
@yuan1995913 这个可以参考 #66 处理

**Comment by yuan1995913** [comment]
@liqi07 看过了。。那个demo跑不起来……

**Comment by winnerweb** [comment]
@yuan1995913 我也遇到同样的问题，请问解决了么？

**Comment by xshua06** [comment]
@yuan1995913 
同样的问题，解决了么？
.babelrc都配置了，还是cannot find module

**Comment by afc163** [comment]
https://github.com/ant-tool/atool-build/blob/a4b3e3eec4ffc09b0e2352d7f9d279c4c28fdb99/src/getWebpackCommonConfig.js#L76

这句很关键。

**Comment by yuan1995913** [comment]
@winnerweb @xshua06  
https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo
我把这个demo下载到了本地 可以跑起来，但是在项目中始终不成功，还在研究中。。

**Comment by yuan1995913** [comment]
@afc163  谢谢 我在研究研究

**Comment by winnerweb** [comment]
@yuan1995913 @xshua06 我的问题解决了，.babelrc文件中一定要加 
["antd", { style: "css", libraryName: "antd-mobile" }]
像这样：
```
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": ["react-hot-loader/babel", ["antd", { style: "css", libraryName: "antd-mobile" }]]
}
```

resolve的这一段代码加不加我这里都能跑通
```
resolve: {
    modulesDirectories: ['node_modules', join(__dirname, '../node_modules')],
    extensions: ['', '.web.tsx', '.web.ts', '.web.jsx', '.web.js', '.ts', '.tsx', '.js', '.jsx', '.json'],
},
```

还有，一定要有css loader, 因为一直用sass，就没用加css loader ，也会出问题

**Comment by yuan1995913** [comment]
@winnerweb 谢谢。。可是还是提示没有样式和没有react-native模块。。

**Comment by GZWZC** [comment]
@smackgg 你好 .babelrc文件中一定要加
["antd", { style: "css", libraryName: "antd-mobile" }]
