### ISSUE TITLE
modal.operation 安卓设备上面存在多个选项是会挤在一起无法看清

### ISSUE THREAD

**Issue by hunjixin** [ant-design/ant-design-mobile#1791]
### What problem does this feature solve?
安卓设备会使用一个安卓的样式 使用了flex布局
.am-modal.am-modal-transparent.am-modal-android .am-modal-content .am-modal-footer .am-modal-button-group-v {
    display: -webkit-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    -webkit-box-pack: end;
    -ms-flex-pack: end;
    -webkit-justify-content: flex-end;
    justify-content: flex-end;
    overflow: hidden;
    padding: 0 24px;
}
多个operation情况下会全部挤在一起，基本无法使用了，自定义的style也无法加在flex容器上
是否能够和ios设备相同的，或者有什么办法可以修改

### What does the proposed API look like?
和ios设备差不多的样子

**Comment by hunjixin** [comment]
you can get demo on [https://codepen.io/hunjixin/pen/xLBMBp](url)

The simulator seems unable to reproduce my problem, which may be a version problem or runner problem.you can copy the code and run local. In example case only shows part of a string, but in the local case, text that is out of length will become an ellipsis.

local version   "antd-mobile": "^1.6.2",

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/pull/925
