### ISSUE TITLE
menu组件列表项支持双行

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#1792]
![menu](https://user-images.githubusercontent.com/347649/30029951-e40274a8-91bd-11e7-98d4-d9035f551c33.png)

**Comment by pingan1927** [comment]
按照正常迭代实现即可，也是业务上要求。1.x 和 2.0都支持。争取后续新需求来时不需要再业务上自己实现。

**Comment by silentcloud** [comment]
@zhang740 @DavidSuns 这个是否 PR 里已经支持？

**Comment by zhang740** [comment]
那个PR不是这个场景，不过我看 data 里 `label` 实际类型是 `ReactNode`，Item项的具体展现可以通过data传入，需要再特殊定制API么？

**Comment by silentcloud** [comment]
API  不用定制了，不过样式估计得处理一下

![image](https://user-images.githubusercontent.com/1698185/31602588-34226be8-b223-11e7-8f34-b8ad935b8d83.png)

**Comment by silentcloud** [comment]
API 不用处理了
