### ISSUE TITLE
内容都不能复制

### ISSUE THREAD

**Issue by sujie056520** [ant-design/ant-design-mobile#1793]
### What problem does this feature solve?
组件内容可复制

### What does the proposed API look like?
长按选择复制

**Comment by sujie056520** [comment]
例如你们的demo，[](https://mobile.ant.design/components/list-view-cn/)
![1](https://user-images.githubusercontent.com/24262471/30042891-cb05fb0a-9226-11e7-8e15-22e8d709ffa0.png)
里面的内容都是不能复制的

**Comment by pingan1927** [comment]
```
 user-select: text;
```
默认全局（body标签）禁用长按复制功能，对于局部需要启用长按复制，修改对应dom的css属性，参考如上代码。

**Comment by paranoidjk** [comment]
@pingan1927 不应该全局禁用，影响太大，我们只是组件库，细粒度的在组件内部需要的地方处理就好了。

**Comment by paranoidjk** [comment]
@pingan1927 准备 在 2.x 把这个去掉，1.x 不做修改。
