### ISSUE TITLE
remove :not()  pseudo-class 

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1796]
https://github.com/ant-design/ant-design-mobile/search?l=Less&q=%3Anot&type=&utf8=%E2%9C%93

http://caniuse.com/#search=%3Anot

cc @ustccjw @warmhug @silentcloud @zhang740

**Comment by warmhug** [comment]
http://caniuse.com/#feat=css-sel3
包含支持`:not()`

**Comment by paranoidjk** [comment]
ok, 有个 notice:

> Level 3 only allowed :not() to accept a single simple selector. Thus, :not(a):not(.b):not([c]) can instead be written as :not(a, .b, [c])

**Comment by silentcloud** [comment]
![image](https://user-images.githubusercontent.com/1698185/30198549-e0da2fc4-94a0-11e7-92e7-760732a21200.png)

![image](https://user-images.githubusercontent.com/1698185/30198561-f215692a-94a0-11e7-8def-dcaff6667c48.png)

issue 关掉了
