### ISSUE TITLE
react-native 使用 antd-mobile 用到Popup 组件，点击事件无法上弹或下弹，无法使用弹出

### ISSUE THREAD

**Issue by ln1778** [ant-design/ant-design-mobile#1798]
### Version
1.6.5

### Environment
react-native 0.40，ios 环境

### Reproduction link
[https://mobile.ant.design/components/popup-cn/#components-popup-demo-basic-up](https://mobile.ant.design/components/popup-cn/#components-popup-demo-basic-up)

### Steps to reproduce
      渲染方法内 代码 <Button onClick={()=>{console.log(22);Popup.show(<View><Text>fdfd</Text></View>,{ animationType: 'slide-up', maskClosable: false })}}>测试弹出</Button>，然后APP点击这个测试弹出按钮，有打印22，却无弹出 pupup组件，

### What is expected?
期望在 react-native ios 上能正常使用 antd-mobile的pupup 组件

### What is actually happening?
 react-native ios 上无法正常使用 pupup 组件

**Comment by paranoidjk** [comment]
官方 demo 正常。 请试下 react-native 0.42 版本下是否 ok？

或者请给出可重现的 demo。

**Comment by silentcloud** [comment]
@ln1778 官方 demo 不能重现  https://github.com/ant-design/ant-design-mobile/blob/1.x/components/popup/demo/basic.tsx

issue 先关了，如果还是有问题，麻烦传上你的代码来
