### ISSUE TITLE
Accordion bug Accordion.Panel在React.Component中封装一层后展开功能失效

### ISSUE THREAD

**Issue by jdwdw** [ant-design/ant-design-mobile#1799]
在 Accordion 中加入在新React.Component中包装的Accordion.Panel后展开功能会失效

`           <Accordion defaultActiveKey="0" className="my-accordion" onChange={this.onChange}>
              {mockData.map(data => (
                <NewAccordionPanel data={data}>
                  {data.datas.map(value => (
                    <Item extra={value.time} itemTitle={'Hey man'} extraActive TitleExtra={this.renderItemTitleExtra(value)} />
                  ))}
                </NewAccordionPanel>
              ))}
            </Accordion>`

在React.Component中包装 Accordion.Panel代码
`class NewAccordionPanel extends Component {
  constructor(props) {
    super(props);
    this.state = {

    };
    this.renderAccordionPanelHeader = this.renderAccordionPanelHeader.bind(this);
  }

  renderAccordionPanelHeader(data) {
    console.log(data.id);
    return (
      <div className={styles.AccordionPanelHeaderContainer}>
        <div className={styles.editIcon}>
          <svg className="icon" aria-hidden="true">
            <use xlinkHref="#ghgroup_pre" />
          </svg>
        </div>
        <div>
          {data.title}
        </div>
        <div>
          {'3/20'}
        </div>
      </div>
    );
  }

  render() {
    const { children, data } = this.props;
    return (
      <AccordionPanel header={this.renderAccordionPanelHeader(data)} prefixCls={'am-accordion'}>
        {children}
      </AccordionPanel>
    );
  }
}`

是我的写法有问题，还是组件本来就是这么设定？而且很多的这种情况 prefixCls 也会丢失。

**Comment by luania** [comment]
依旧没有解决

**Comment by luania** [comment]
只能把Accordion也放到组件里封装起来，在外面用activeKey控制
