### ISSUE TITLE
组件样式重构

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#18]
1. 按照 antui 样式规范进行重写，设计师会重做视觉稿，并进行细致全面的标注。
2. 严格按最新的变量规范和标注进行实现。
3. 使用 `components/style/themes/default.less` 里的变量完全替换原来的变量文件。

设计师出稿时间点：8.2-8.12

---

- [设计变量表及命名规范](https://github.com/ant-design/ant-design-mobile/wiki/%E8%AE%BE%E8%AE%A1%E5%8F%98%E9%87%8F%E8%A1%A8%E5%8F%8A%E5%91%BD%E5%90%8D%E8%A7%84%E8%8C%83)
- [前端变量文件](https://github.com/ant-design/ant-design-mobile/blob/master/components/style/themes/default.less)

**Comment by pingan1927** [comment]
一旦出稿，速度直线通知下

**Comment by afc163** [comment]
嗯，群里关注下。

**Comment by silentcloud** [comment]
这个关了
