### ISSUE TITLE
NoticeBar在iOS上运行正常, 在Android上不滚动显示是静止的

### ISSUE THREAD

**Issue by dongchuanlei** [ant-design/ant-design-mobile#1800]
### Version
1.6.5

### Environment
react-native 0.47.1

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
<NoticeBar marqueeProps={{loop:true,style:{color:'#666666',fontSize:13}}}  icon={null}>
       Notice: The arrival time of incomes and transfers of Yu &#39;E Bao will be delayed during National Day.
</NoticeBar>

### What is expected?
Android能和iOS一样在字数超过范围时能滚动显示

### What is actually happening?
Android在使用NoticeBar的时候字数超过显示范围时静止的

**Comment by paranoidjk** [comment]
你确定 ios 上运行正常？

目前 react-native 版的 NoticeBar 暂不支持超长自动滚动的功能。

cc @silentcloud

**Comment by dongchuanlei** [comment]
![untitled](https://user-images.githubusercontent.com/19383409/30089325-97c7b392-92de-11e7-91e3-107be43cc179.gif)
@paranoidjk iOS运行是正常的

**Comment by zhang740** [comment]
@dongchuanlei 在2.0版本已修复
