### ISSUE TITLE
react-native-navigation 与 antd-mobile一起使用时，Toast、Modal等控件使用不了

### ISSUE THREAD

**Issue by nothingp** [ant-design/ant-design-mobile#1802]
### Version
1.6.5

### Environment
 "react-native": "0.44.3",    "react-native-navigation": "latest"

### Reproduction link
[https://github.com/nothingp/react-native-nothing/blob/master/src/component/personal/index.js](https://github.com/nothingp/react-native-nothing/blob/master/src/component/personal/index.js)

### Steps to reproduce
this.props.navigator.push({
                              screen: 'RelationShip',
                              animated: false,
                              title: '紧急联系人'
                          })}
返回后，就不能使用Toast、Modal了

### What is expected?
Toast、Modal能正常使用

### What is actually happening?
Toast、Modal 不能弹出

**Comment by zhang740** [comment]
`react-native-navigation`的导航逻辑是端上启动独立页面然后单独加载scene组件，导致判断topview不准确。 @silentcloud

**Comment by silentcloud** [comment]
@nothingp @zengyue 官方 RN demo 也是用的 react-native-navigation， 没看到有问题啊

**Comment by nothingp** [comment]
@silentcloud @zengyue  你可以跑我的demo试试，这个问题急切解决！！！

**Comment by zhang740** [comment]
@nothingp 在App.js最初加载antd-mobile。
e.g:
```
import 'antd-mobile'; // <-----
import { Navigation } from 'react-native-navigation';
import { registerScreens, startLoginScreen, startTabsScreen } from './screens';
import Provider from './util/MobxRnnProvider';
import Stores from './stores';

registerScreens(Stores, Provider); // this is where you register all of your app's screens

//startLoginScreen();
startTabsScreen();
```
钩子加载的太晚了。。。 @silentcloud

**Comment by nothingp** [comment]
@zhang740  我刚push 了，但是还不行，this.props.navigator.push和Navigation.showModal都还不行

**Comment by zhang740** [comment]
临时解决方案：
找到node_modules/rn-topview
```
{
  key: "componentWillUnmount",
  value: function () {
    _reactNative.DeviceEventEmitter.removeAllListeners("topViewAdd"),
      _reactNative.DeviceEventEmitter.removeAllListeners("topViewRemove")
  }
},
```
替换为
```
{
  key: "componentWillUnmount",
  value: function () {
    _reactNative.DeviceEventEmitter.removeListener("topViewAdd", this.setTopView),
      _reactNative.DeviceEventEmitter.removeListener("topViewRemove", this.removeTopView)
  }
},
```

**Comment by nothingp** [comment]
@zhang740 sorry to say 'failed'

**Comment by zhang740** [comment]
@nothingp 我是拿你的代码试的，`node_modules/rn-topview/lib/topView.js`文件：
把`removeAllListeners `替换成`removeListener `

**Comment by laiyifeng77** [comment]
encountering this problem with React-Native-navigation，sometimes Toast will not work ，any solutions to solve it ？

**Comment by zhang740** [comment]
@laiyifeng77 temporary solution is edit the file:  `node_modules/rn-topview/lib/topView.js`
replace `removeAllListeners("topViewAdd")` to `removeListener("topViewAdd", this.setTopView)`
and `removeAllListeners("topViewRemove")` to `removeListener("topViewRemove", this.removeTopView)`.

**Comment by nothingp** [comment]
@zhang740 ok了，请问这个问题是不是会在近期升级版本

**Comment by zhang740** [comment]
@laiyifeng77 temporary solution:
edit the file : `node_modules/rn-topview/lib/topView.js`
replace `removeAllListeners("topViewAdd")` to `removeListener("topViewAdd", this.setTopView)` and replace `removeAllListeners("topViewRemove")` to `removeListener("topViewRemove", this. removeTopView)`.

**Comment by silentcloud** [comment]
@nothingp 照着 @zhang740 的方法是否能解决？

**Comment by silentcloud** [comment]
@nothingp 我试了，按照他的方案是可以的，我稍后发个 rn-topview 的版本

**Comment by silentcloud** [comment]
@nothingp  run `yarn upgrade`
