### ISSUE TITLE
antd-mobile@2.0 beta

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#1807]
TODOs

- [x] [mobile.ant.design](https://mobile.ant.design/index-cn) 页面顶部添加[提示](https://ant.design/components/alert-cn/#components-alert-demo-banner)
- [x] pc 网站组件页面 不同组件切换报错
- [x] 新版首页
- [x] 升级文档 / samples

**Comment by paranoidjk** [comment]
- [ ] 所有组件的 demo 和 文档自查

**Comment by paranoidjk** [comment]
- [ ] rmc-date-picker 多版本依赖统一 @zhang740 @warmhug 
- [ ] rmc-picker 多版本依赖统一 @silentcloud

**Comment by warmhug** [comment]
review 问题

- [ ] Drawer 组件高度不够、显示不对
- [ ] DatePicker limited demo 显示有问题
- [ ] Slider 圆圈位置稍微偏上
- [ ] 从下向上的弹出动画、有明显的中途卡顿现象

**Comment by paranoidjk** [comment]
- [ ] changelog & upgrade note 英文文档翻译

**Comment by paranoidjk** [comment]
- [ ]  网站和文档中体现与 preact 兼容

**Comment by paranoidjk** [comment]
## 正式发布时需要发 1.0 的底层依赖

- [ ] https://github.com/react-component/gesture

cc @zhang740 @silentcloud 新增的一些 rc-component 也要注意，到时候 antd-mobile@2.0 正式版要依赖这些底层依赖的 1.x

**Comment by warmhug** [comment]
@paranoidjk  只要不是发 alpha / beta 即可，不用一定是 1.0 吧

**Comment by paranoidjk** [comment]
@warmhug 发 1.0 的原因是为了 semver, 0.x 的话每次升级都是 major 升级，依赖是没法自动更新的
