### ISSUE TITLE
bundle size optimization

### ISSUE THREAD

**Issue by zhang740** [ant-design/ant-design-mobile#1811]
- [x] `create-react-class`:
- [x] ├─┬ rc-input-number@3.6.7
│ └── create-react-class@15.6.0
- [x] ├─┬ rc-tooltip@3.4.8
│ └─┬ rc-trigger@1.11.3
│   └── create-react-class@15.6.0
- [x] ├─┬ rmc-nuka-carousel@2.2.1
│ └── create-react-class@15.6.0
- [x] └─┬ rmc-picker@5.0.0-alpha.0
  └── create-react-class@15.6.0

- [x] `object-assign`:
├─┬ rmc-list-view@0.8.6
│ ├── object-assign@4.1.1
│ └─┬ react-mixin@3.1.0
│   └── object-assign@4.1.1
├─┬ rmc-nuka-carousel@2.2.1
│ └── object-assign@4.1.1

 - [x] `rc-touchable`:
├─┬ rc-input-number@3.6.7
│ └── rc-touchable@1.2.3
└─┬ rmc-picker@5.0.0-alpha.0
  └── rc-touchable@1.2.3

**Comment by paranoidjk** [comment]
@zhang740 把这个 issue 迁移整合到 https://github.com/ant-design/ant-design-mobile/issues/1625 两件事一起考虑

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/commit/4c67117f41db184a1acc1bc9e5f4cea6cc2f9459

**Comment by silentcloud** [comment]
- [ ] rc-align ==> prop-types
