### ISSUE TITLE
InputItem type="money"state初始value，点击弹出键盘，不能点击删除，会报substirng() 未定义,在输入之后才可以

### ISSUE THREAD

**Issue by yangxiufang1994** [ant-design/ant-design-mobile#1814]
### Version
1.6.5

### Environment
web

### Reproduction link
[https://codepen.io/xfYang1015/pen/PKvXbN](https://codepen.io/xfYang1015/pen/PKvXbN)

### Steps to reproduce
Inputtem type="money",用state初始化一个值，点击输入框时，弹出键盘，不能点击删除，会报value.substirng is function(), 再次输入某个数字之后才可以删除初始化的值 

### What is expected?
初始化的值，点击删除也是可以直接删除的

### What is actually happening?
会报错，然后必须再输入才可以删除

**Comment by paranoidjk** [comment]
@yangxiufang1994 
https://mobile.ant.design/components/input-item-cn/ 文档写明了 `value` 是 `string`.

cc @pingan1927
