### ISSUE TITLE
prompt的输入框没有事件接口

### ISSUE THREAD

**Issue by webdaniu** [ant-design/ant-design-mobile#1819]
给prompt的输入框提供个事件接口吧

**Comment by paranoidjk** [comment]
https://mobile.ant.design/components/modal-cn/#components-modal-demo-prompt

`Modal.prompt(title, message, callbackOrActions, type?, defaultValue?)`

**Comment by silentcloud** [comment]
prompt 只是个简单场景的组件，需要更复杂的校验什么的，需要你自己去包装
