### ISSUE TITLE
mobile demo site optimization.

### ISSUE THREAD

**Issue by zhang740** [ant-design/ant-design-mobile#1821]
- [ ] change to SPA.
- [x] 网站加载资源大小是否需要优化？kitchen-sink.js / css 大小
- [x] 资源文件都放到 cdn，提高首次加载速度（尽量从现在的 3s 提升到 1s 左右）

**Comment by warmhug** [comment]
- [ ] 网站加载资源大小优化，kitchen-sink.js / css 大小、 beta 版网站比正式版的还要大

**Comment by paranoidjk** [comment]
SPA 不用急，评估工作量和时间再决定要不要做

**Comment by zhang740** [comment]
@paranoidjk 嗯，没启动，目前只是搞cdn

**Comment by paranoidjk** [comment]
改 SPA 之后我担心性能更差，bundle 太大了 cc @benjycui

**Comment by benjycui** [comment]
本来不就是 SPA 了么。。

**Comment by silentcloud** [comment]
@zhang740 这个进度？ok 了就关了

**Comment by zhang740** [comment]
SPA先不搞，其他差不多了。
