### ISSUE TITLE
export default class BasicSwipeActionExample extends React.Component<any, any> {...}

### ISSUE THREAD

**Issue by yt7649757** [ant-design/ant-design-mobile#1826]
这个<any,any>是什么？ 没见过这种写法啊？

-------------------------------------------------------

showModal = key => (e) => {
    e.preventDefault(); // 修复 Android 上点击穿透
    this.setState({
      [key]: true,
    });
  }

web端模态框，，这个key是指的什么啊，，是传过来的参数吗？this.showModal('modal1') 比如就是这个modal1,，我只会最简单的这种写法，showModal = (key) => {} ，，能否解释下你这种写法呢？？

**Comment by paranoidjk** [comment]
> 这个<any,any>是什么？ 没见过这种写法啊？

TypeScript.

> web端模态框，，这个key是指的什么啊，，是传过来的参数吗？this.showModal('modal1') 比如就是这个modal1,，我只会最简单的这种写法，showModal = (key) => {} ，，能否解释下你这种写法呢？？

Es6 Arrow Fcuntion.
