### ISSUE TITLE
Calendar returns Expected a component class,got [object,object]

### ISSUE THREAD

**Issue by stonecold123** [ant-design/ant-design-mobile#1828]
### Version
2.0.0-beta.0

### Environment
react-native

### Reproduction link
[https://github.com/stonecold123/calendarTest](https://github.com/stonecold123/calendarTest)

### Steps to reproduce
I use `import {Calendar} from 'antd-mobile'` to import the Calendar class, but it returns `Expected a component class,got [object,object]`

### What is expected?
Calendar should be rendered without errors

### What is actually happening?
I wonder why the Calendar class fails to be imported with `import {Calendar} from 'antd-mobile'`. I started a new project and tried again, but still the Calendar class isn't a component class.

Here's my code:
````
import React, {Component} from 'react';
import {AppRegistry, StyleSheet, View} from 'react-native';
import {Button, Calendar} from 'antd-mobile'
export default class calendarTest extends Component {
    constructor(props) {
        super(props)
        this.state = {show:false}
    }

    render() {
        return (
            <View style={styles.container}>
                <Button onClick={() => this.state.show = true}>Open</Button>
                <Calendar visible={this.state.show}/>
            </View>
        );
    }
}
````

My package.json
````
{
	"name": "calendarTest",
	"version": "0.0.1",
	"private": true,
	"dependencies": {
		"@types/react": "^16.0.5",
		"@types/react-native": "^0.47.6",
		"antd-mobile": "^2.0.0-beta.0",
		"mobx": "^3.2.2",
		"mobx-react": "^4.2.2",
		"react": "^16.0.0-alpha.12",
		"react-dom": "^16.0.0-rc.2",
		"react-native": "0.47.2"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-plugin-import": "^1.4.0",
		"babel-preset-react-native": "2.1.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	}
}
````

**Comment by paranoidjk** [comment]
Sorry that calendar is a component we just add in v2, so it noly support web(react) right now.

You can see support platform explain below in api doc:  http://beta.mobile.ant.design/components/calendar/#API

**Comment by blackkey520** [comment]
Do you have a plan to support react native?

**Comment by paranoidjk** [comment]
We have no time to add this feature right now, but PR is welcome.
