### ISSUE TITLE
Update English locale for Picker component

### ISSUE THREAD

**Issue by ShMcK** [ant-design/ant-design-mobile#1833]
### What problem does this feature solve?
Currently the Picker component only supports Mandarin. 

### What does the proposed API look like?
Picker should likely use the same language values as DatePicker.

**Comment by silentcloud** [comment]
`Picker` has no built-in text.

https://mobile.ant.design/components/locale-provider/#Other-localization-needs

@ShMcK

**Comment by paranoidjk** [comment]
@silentcloud picker do have built-text, right now as default props https://github.com/ant-design/ant-design-mobile/blob/1.x/components/picker/AbstractPicker.tsx#L22

**Comment by paranoidjk** [comment]
@ShMcK Thanks for your report, we do need to make Picker works with locale.

**Comment by ShMcK** [comment]
Locale no longer working with the Picker. All language now reverts to Mandarin defaults and ignores overrides (okText, extra, dismissText).

- 2.0.0-beta.6 - locale can be set to English
- 2.0.0-rc.2 - locale Mandarin only.

This may be a product of 25163d7 or 4dfcda0.
