### ISSUE TITLE
Should we move default locale to English?

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1835]
Right now `antd-mobile@1` default locale is Mandarin.

And we support `props.okText` --> `props.locale.okText` --> `context.locale.okText`, eg: https://mobile.ant.design/components/date-picker-cn/

PS. In `antd-mobile@2.0`, component built-in text should all support locale.

## Locale Support CheckList

- [x] DatePicker: support okText, dismissText, should we move `extra` to locale too?
- [x] Picker: not support yet https://github.com/ant-design/ant-design-mobile/issues/1833
. . .

**Comment by paranoidjk** [comment]
Use https://github.com/ant-design/ant-design-mobile/issues/1835 `Picker` for example, `Picker` have 3 built-in text `okText`, `dismissText`, `extra` , if we make them all be english by default, i think most of our users will have to do locale setting.

**Comment by paranoidjk** [comment]
ref https://github.com/ant-design/ant-design/pull/7553

cc @benjycui @yesmeck

**Comment by paranoidjk** [comment]
One more thing, most of antd-mobile users are Chinese.

<img width="300" alt="2017-09-12 10 00 37" src="https://user-images.githubusercontent.com/7971415/30304682-5005c860-97a1-11e7-8f95-b572fcf9acaf.png">

**Comment by paranoidjk** [comment]
@silentcloud @zhang740 @warmhug 

We need check all components to see whether it can work with LocaleProvider, this will be a nice feature in `antd-mobile@2.0`.

**Comment by warmhug** [comment]
Still use Chinese by default.

> The same type of problems exists in multiple components, are best only by one person to modify, rather than assigned to multiple people. @paranoidjk

**Comment by warmhug** [comment]
> should we move extra to locale too?

I agree.

**Comment by silentcloud** [comment]
closed for https://github.com/ant-design/ant-design-mobile/pull/1923
