### ISSUE TITLE
MutationObserver do not trigger callback in UIWebView touchmove

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1838]
## Problem
 UIWebView + preact  + babel polyfill / bable-runtime 的页面，在 touchmove 里面触发 setState 会导致整个应用挂掉

## Reason
- preact 优先用 Promise 实现 next tick 调度 https://github.com/developit/preact/blob/master/src/util.js#L13
- 但 babel 的 core js 对 promise 支持检测很严格， 没有  PromiseRejectionEvent 都会自动 polyfill，而目前大多数浏览器都没有 https://github.com/zloirock/core-js/blob/master/modules/es6.promise.js#L34
- core js  promise polyfill 用到的 microtask 又是用 MutationObserver 实现 https://github.com/zloirock/core-js/blob/master/modules/_microtask.js#L34
- 而 UIWebView 的 MutationObserver 有 bug，在 touchmove 频繁过程中会停止触发回调
- 导致 preact 队列不会清空 https://github.com/developit/preact/blob/master/src/render-queue.js#L10

## Relative bug in vue
https://github.com/vuejs/vue/issues/3285
https://github.com/miccycn/vue-bug-demo

## temporary workaround

- UIWebview 上可以将 `window.PromiseRejectionEvent` polyfill 成一个 noop function 绕过 babel
- 或者业务上自行保证不要让 babel 来 polyfill promise 就行。

- - - 

## Vue Solution
- https://github.com/vuejs/vue/blob/master/src/core/util/env.js#L85

> MutationObserver has wider support, however it is seriously bugged in
  // UIWebView in iOS >= 9.3.3 when triggered in touch event handlers. It
  // completely stops working after triggering a few times... so, if native
  // Promise is available, we will use it:

- https://github.com/vuejs/vue/blob/master/src/core/util/env.js#L95
>   // in problematic UIWebViews, Promise.then doesn't completely break, but
      // it can get stuck in a weird state where callbacks are pushed into the
      // microtask queue but the queue isn't being flushed, until the browser
      // needs to do some other work, e.g. handle a timer. Therefore we can
      // "force" the microtask queue to be flushed by adding an empty timer.

**Comment by zhang740** [comment]
https://observer-bug.stackblitz.io
目前来看 MutationObserver 的实现方式也要比 Promise 慢很多
https://esbench.com/bench/59b756ba99634800a0349098

**Comment by paranoidjk** [comment]
preact author 完整的 benchmark https://esbench.com/bench/55d4d44e2efbca1100bf7251

**Comment by paranoidjk** [comment]
@zhang740 负责推动 core-js 调一下 promise polyfill 的实现顺序

**Comment by paranoidjk** [comment]
PS: vue 的 next tick 实现 https://github.com/vuejs/vue/blob/master/src/core/util/env.js#L90
