### ISSUE TITLE
Problem work with Preact

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1839]
## Won't fix
- https://github.com/ant-design/ant-design-mobile/issues/1838
- https://github.com/ant-design/ant-design-mobile/issues/2329
## Fixed
- https://github.com/developit/preact-compat/issues/422
- https://github.com/ant-design/ant-design-mobile/issues/1304
- https://github.com/ant-design/ant-design-mobile/issues/1631
- https://github.com/ant-design/ant-design-mobile/issues/2139

**Comment by warmhug** [comment]
preact 在 `componentWillReceiveProps` 里的问题
```js
componentWillReceiveProps(nextProps) {
  const curProps = this.props;
  this.setState((state, props) => {
    console.log(props === nextProps); // in react.js, it's true.
    console.log(props === curProps); // in preact.js, it's true.
  });
}
```
ref: https://github.com/react-component/m-list-view/commit/73c317b3a11cbaf0a44dd577cbd8237a30ee285b

**Comment by silentcloud** [comment]
https://github.com/react-component/m-dialog/issues/3

**Comment by silentcloud** [comment]
- [ ] popover 在 preact android 下面 click 问题 (trigger 的 document click 执行两次)

**Comment by paranoidjk** [comment]
Close since no more problems.

**Comment by warmhug** [comment]
- [ ] preact 把 className 转换为 class 添加到 dom ，导致 重复添加 css name 错误，见 InputItem 组件

**Comment by paranoidjk** [comment]
@zhang740 把 https://github.com/developit/preact-compat/pull/450 关联的 issue  添加过来

**Comment by paranoidjk** [comment]
https://github.com/developit/preact/pull/974
