### ISSUE TITLE
OnClick handler for Picker/ PickerView/ DatePicker

### ISSUE THREAD

**Issue by tvtri96** [ant-design/ant-design-mobile#1841]
### What problem does this feature solve?
The user can change the value of the Picker/ PickerView/ DatePicker by clicking the value and scroll to that value besides scrolling the picker.

### What does the proposed API look like?
<Picker onPickerClick={(value) => console.log(value) />

onPickerClick will return the value that is clicked.

**Comment by warmhug** [comment]
This is a good feature, but it is not easy to achieve now.

**Comment by warmhug** [comment]
Trace https://github.com/react-component/m-picker/issues/39
