### ISSUE TITLE
Add PullToRefresh Component

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1842]
We need a standalone Pull2Refresh Component.

May be  based on [rc-geture onPanDown](https://github.com/react-component/gesture#pan)

ref: 
https://github.com/ant-design/ant-design-mobile/issues/234

https://github.com/ant-design/ant-design-mobile/issues/814

- - -

**Comment by warmhug** [comment]
Pull2Refresh  改名为  PullToRefresh

**Comment by paranoidjk** [comment]
API may like this ?

```tsx
< PullToRefresh onRefresh={() => {}}>
  <div>fake content</div>
</ PullToRefresh>
```

**Comment by szwork2013** [comment]
I suggest making such the component(react-infinite-scroll-component). ListView is too complicated and too bloated.

**Comment by paranoidjk** [comment]
@warmhug Why there already have one ? https://github.com/react-component/m-pull-to-refresh
