### ISSUE TITLE
ListView.IndexedList not work

### ISSUE THREAD

**Issue by shi1hh** [ant-design/ant-design-mobile#1843]
### Version
2.0

### Environment
react-native

### Reproduction link
[http://native](http://native)

### Steps to reproduce
just a ListView.IndexedList demo,not work. the antd ListView.IndexedList demo for react native is not exists

### What is expected?
 a ListView.IndexedList demo and it can work

### What is actually happening?
no demo and not work

**Comment by zhang740** [comment]
Please provide a specific demo.

**Comment by shi1hh** [comment]
@zhang740 i see the ListView.IndexedList not have native version

**Comment by silentcloud** [comment]
> ListView.IndexedList demo for react native is not exists

@shi1hh  see http://facebook.github.io/react-native/releases/next/docs/listview.html

**Comment by warmhug** [comment]
https://github.com/ant-design/ant-design-mobile/commit/2aef628419db40bf6ffacce26232bcfbe365d56b#diff-4906357c65ddfb566b1600787a0b1194R14

![image](https://user-images.githubusercontent.com/2011119/30417794-85af7790-9963-11e7-89dc-9986709c1de6.png)
