### ISSUE TITLE
Add Filter Component

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#1847]
新增Filter组件

**Comment by paranoidjk** [comment]
@pingan1927 We'd better paste sketch ad api design at here.

**Comment by pingan1927** [comment]
`Array<{text, selected, icon, selectedIcon, onClick, className}>`

Properties | Descrition | Type | Default
----|-----|------|------
| text    |   显示文案     | `string or node`  |  |
| selected    |   是否选中     | `boolean`  |  |
| onClick    |   点击时间的回调，入参是整个该对象     | `(e: Object): void`  |  |
| icon(可选)    |   未选中状态的自定义icon     | `url`  |  |
| selectedIcon(可选)    |   已选中状态的自定义icon     | `url`  |  |
| className(可选)    |   定制的className     | `string`  |  |

**Comment by afc163** [comment]
```
<Filter>
  <Filter.Item open={boolean} onOpenChange={Function} dropdown={ReactNode}>
    xxx
  </Filter.Item>
  <Filter.Item dropdown={ReactNode}>
    xxx
  </Filter.Item>
</Filter>
```

**Comment by pingan1927** [comment]
`dropdown={ReactNode}` 不需要 filter 跟dropdown互相独立

**Comment by pingan1927** [comment]
没更多意见的话 这个API就按照我的设想来提交了
