### ISSUE TITLE
Styling Button's text in React Native

### ISSUE THREAD

**Issue by silvestreh** [ant-design/ant-design-mobile#1853]
It does look like the `Button` component takes a `styles` prop which you later use to apply the `Text` styles.

https://github.com/ant-design/ant-design-mobile/blob/c30d049c1a0ca7cd812cdd11d544fec75a10e4e7/components/button/index.native.tsx#L84

I can't find documentation on how to change the text color. I noticed I can switch between black and white by using the `type='primary'` prop, but I need other colors 😄 

Any hints would be greatly appreciated.

**Comment by paranoidjk** [comment]
You have to follow this object structure 
https://github.com/ant-design/ant-design-mobile/blob/master/components/button/style/index.native.tsx
for example

https://github.com/ant-design/antd-mobile-samples/blob/master/rn-custom-ui/inputStyle.js

**Comment by silvestreh** [comment]
Thanks! For people who might get here through a Google search here's how I solved using @paranoidjk hints:

```javascript
import ButtonStyle from 'antd-mobile/lib/button/style/index.native';

StyleSheet.create({
  ...ButtonStyle,

  defaultRawText: {
    color: 'red'
  }
});
```

**Comment by youngjuning** [comment]
@silvestreh how can i do?

**Comment by 1uokun** [comment]
Ref Blog: https://rn.mobile.ant.design/docs/blog/what-is-styles
