### ISSUE TITLE
react-native使用picker-view怎么自定义，或者说改源码的样式在哪里改

### ISSUE THREAD

**Issue by ZGahou** [ant-design/ant-design-mobile#1856]
### What problem does this feature solve?
用户自定义选择器样式

### What does the proposed API look like?
能支持在rn中修改样式更好

**Comment by silentcloud** [comment]
大家都不看文档啊

https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui#antd-mobile-with-rn-custom-ui

**Comment by ZGahou** [comment]
我现在用1.6.6版本，你确定picker-view的样式有export出来？都没有那个index.d.ts文件

**Comment by silentcloud** [comment]
@ZGahou you can use `itemStyle` and `indicatorStyle` to custom style
