### ISSUE TITLE
modal的prompt的输入弹窗形式，在iOS上点击触摸输入框有时候反应缓慢，官方demo中就可以复现

### ISSUE THREAD

**Issue by itxuye** [ant-design/ant-design-mobile#1857]
### Version
1.6.7

### Environment
iOS真机

### Reproduction link
[https://mobile.ant.design/kitchen-sink](https://mobile.ant.design/kitchen-sink)

### Steps to reproduce
modal  demo中prompt的几个输入弹窗，点击触摸输入框，反应缓慢或者有时候不弹出键盘，试几次才好。
还有种场景是隐藏键盘，再重新点击触摸输入框，键盘也是好几次才能调用起

### What is expected?
在Android的机器上，反应正常

### What is actually happening?
点击触摸输入框，反应缓慢或者有时候不弹出键盘，试几次才好。

**Comment by silentcloud** [comment]
Modal 目前样式里很多 fixed，结合 iOS 键盘情况后，会出现各种问题

https://dansajin.com/2012/12/07/fix-position-fixed/

1.x 临时修复的话估计得按照上面这种方式来
2.0 准备改成 position:absolute，这就需要 body 加 `{position: relative; width:100; height:100}` 应该算是 break change 了

**Comment by warmhug** [comment]
文章里说的 fixed 的问题、之前确实有。但这个不能确定 fixed 会跟键盘弹出速度有关吧？

**Comment by silentcloud** [comment]
键盘弹出是 setTimeout 问题，不过我实测，跟 fixed 也有关系

**Comment by silentcloud** [comment]
1.x 里 setTimeout 时间太长，我稍微改短一点，iOS 里 focus 问题比较多；
这个问题跟 modal fixed  也有关系，要彻底解决的话，还得看如何切换到 position: absolute

初步试了动态切 absolute 有问题

**Comment by silentcloud** [comment]
https://gist.github.com/avesus/957889b4941239490c6c441adbe32398#gistcomment-2193547

**Comment by silentcloud** [comment]
额，经过各种探测，影响弹出速度是因为 label 标签位置有问题，更改 label 标签位置，各方面都 ok 了

**Comment by warmhug** [comment]
具体原因是什么？这种比较少见，在代码里加个注释或链接吧

**Comment by itxuye** [comment]
请问修复好的版本会在哪个版本发布呢，目前项目在线上了。

**Comment by silentcloud** [comment]
具体原因就是我上面说的 label 标签位置有问题 @warmhug 
@itxuye 这个会在 1.6.9 上发布，稍等

**Comment by itxuye** [comment]
@silentcloud 目前看还是1.6.7版本，之后的版本最近不会上吗？

**Comment by silentcloud** [comment]
@itxuye 上周没有发 1.6.9， 可以先指定 1.6.9-beta.0， 或者你等会，我这会发个 1.6.9

**Comment by silentcloud** [comment]
@itxuye 1.6.9 has been released

**Comment by itxuye** [comment]
@silentcloud Thx .

**Comment by itxuye** [comment]
@silentcloud  你好，在iOS 中仍然有点慢，很难点，点输入框有时候点几次或者点左边才能触发焦点弹出键盘。

**Comment by silentcloud** [comment]
@itxuye 比之前没修复之前好很多，目前稍微有点延迟，这个应该跟 position:fixed 有关，但是改 position  涉及的改动很大，还需求 body height:100%  一直往下传，也要取决用户样式；

如果你觉得影响比较大大话，可以按我说大将 body height:100%  往下传，然后覆盖 modal position:fixed 相关样式
