### ISSUE TITLE
TextareaItem autoHeight 时，频幕滚动问题

### ISSUE THREAD

**Issue by LPegasus** [ant-design/ant-design-mobile#1858]
### Version
1.6.7

### Environment
ios 10.3 simulator、android 5.1motorola_XT1085、android 6.0 Samsung s6e

### Reproduction link
[https://gist.github.com/LPegasus/b5c109b85c56c234c4b946bad2b9c1a6](https://gist.github.com/LPegasus/b5c109b85c56c234c4b946bad2b9c1a6)

### Steps to reproduce
- 输入 TextareaItem 填写很多很多文字，使频幕可滚动
- 触发 TextareaItem 的 componentDidUpdate

- fill plenty of words into a the first TextareaItem with `autoHeight` prop till the body scrollbar appears
- do any action to trigger the first TextareaItem's `componentDidUpdate` function

### What is expected?
频幕稳定在原位置

window should be stable

### What is actually happening?
频幕滚动

window scroll to top

---
TextareaItem componentDidUpdate 中把
```js
textareaDom.style.height = ''; // 字数减少时能自动减小高度
textareaDom.style.height = textareaDom.scrollHeight +  'px';
```
延迟执行，可以解决此问题。

delay the above two code lines may useful.

**Comment by silentcloud** [comment]
延迟执行不能解决这个问题，应该是判断当前是不是 focus

**Comment by Lawrence51** [comment]
> 延迟执行不能解决这个问题，应该是判断当前是不是 focus

这个判断应该是在哪里啊
