### ISSUE TITLE
dva-cli 创建的项目svg 怎么配置

### ISSUE THREAD

**Issue by Ruanyang2015** [ant-design/ant-design-mobile#1860]
dva-cli 创建的项目svg 怎么配置,dva-cli创建的项目没有 webpack. 相关的配置文件啊,怎么办?
如果按照文档上的做法===>因为 .roadhogrc 配置文件优先级大于 .roadhogrc.js, 请先删除 .roadhogrc,那么原来的配置又写在哪里勒?
<img width="961" alt="2017-09-18 6 44 13" src="https://user-images.githubusercontent.com/13889247/30538638-8757d90c-9ca1-11e7-9499-9eef47e8d5d3.png">

**Comment by paranoidjk** [comment]
https://github.com/ant-design/antd-mobile-samples/tree/1.x/antm-roadhog
