### ISSUE TITLE
Tabs throw error when looping an array with just one item using map().

### ISSUE THREAD

**Issue by stonecold123** [ant-design/ant-design-mobile#1862]
### Version
2.0.0.beta.2

### Environment
react-native

### Reproduction link
[https://github.com/stonecold123/antdTabsTest](https://github.com/stonecold123/antdTabsTest)

### Steps to reproduce
Create a tabs component.
Use this array to create tab content: `const data = [{title:'A'}]`;
````
const data = [{title:'A'}];
export default class calendarTest extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Tabs tabs={data}>
                    {
                        data.map(row=>{
                            return <Text key={row.title}>{row.title}</Text>
                        })
                    }
                </Tabs>
            </View>
        );
    }
}
````
The app would crash. When I use arrays with more than one item, it works, for example: `const data = [{title:'A'},{title:'B'}];`

### What is expected?
One tab content should be rendered

### What is actually happening?
It throws error : `React.Children only expected to receive a single React element child.`

My array in the project is dynamic. Sometimes the array has one item, sometimes, two. 
Why would tabs throw such an error when there's only one item in the array? I have never seen this before. React usually works fine for that.

Edit: New demo updated.

**Comment by zhang740** [comment]
If your item(s) have `key`, your data also MUST have the same `key`. I will add some error tip and fault processing.

**Comment by zhang740** [comment]
reinstall `antd-mobile` to upgrade `rmc-tabs@1.2.2`.

**Comment by stonecold123** [comment]
@zhang740 
thanks, it works. Will you upgrade the `rmc-tabs` in the next antd mobile?

**Comment by zhang740** [comment]
@stonecold123 
antd-mobile not fixed the version of rmc-tabs, so antd-mobile is already.
