### ISSUE TITLE
Antd t-mobile external introduction of CSS file is invalid

### ISSUE THREAD

**Issue by Ruanyang2015** [ant-design/ant-design-mobile#1865]
<img width="450" alt="2017-09-19 3 48 50" src="https://user-images.githubusercontent.com/13889247/30581274-220fae6a-9d52-11e7-88f4-32593b01bae4.png">
**## **Here is my profile****
<img width="685" alt="2017-09-19 3 51 05" src="https://user-images.githubusercontent.com/13889247/30581382-7ab814d0-9d52-11e7-8fdc-3c2365055be8.png">

**Comment by warmhug** [comment]
@sorrycc @paranoidjk

**Comment by paranoidjk** [comment]
@Ruanyang2015 I don't konw what's your problem,  if it's about roadhog usage with antd-mobile, see https://github.com/ant-design/antd-mobile-samples/tree/1.x/antm-roadhog
