### ISSUE TITLE
Antd t-mobile external introduction of CSS file is invalid

### ISSUE THREAD

**Issue by Ruanyang2015** [ant-design/ant-design-mobile#1866]
### Version
1.6.8

### Environment
osx 10.12.4,Chrome浏览器60.0.3112.113（正式版本） （64 位）,dva-cli 创建的项目, React 最新版本

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/issues/1865#issuecomment-330459642](https://github.com/ant-design/ant-design-mobile/issues/1865#issuecomment-330459642)

### Steps to reproduce
import './index.css';
....
<div className="base">
        测试
</div>

### What is expected?
想改变文字的颜色

### What is actually happening?
文字的颜色没任何变化

**Comment by silentcloud** [comment]
I don't understand what's your problem

**Comment by Ruanyang2015** [comment]
**As shown below, it can display properly**
import NavBarStyle from './koubei.less';
<div className={NavBarStyle.main}>
Now,I change css style like this,but the style Without any effect,I don't know why
import './koubei.less';
<div className="main">

**Comment by warmhug** [comment]
这不是 antd-mobile 的问题，关掉 css modules 设置试试。

**Comment by silentcloud** [comment]
Are you using `css-modules`？ If you are, you need remove `css-modules`
