### ISSUE TITLE
安卓下tabs 切换后下划线没有切过去

### ISSUE THREAD

**Issue by KurobaZhang** [ant-design/ant-design-mobile#1867]
### Version
1.6.8

### Environment
react-native 0.48.0 react 16.0.0.aipha.12 antd-mobile 1.6.8

### Reproduction link
[https://codepen.io/kuroba12345/pen/eGJPaB](https://codepen.io/kuroba12345/pen/eGJPaB)

### Steps to reproduce
安卓RN下使用tabs 切换选中项

![点击查看图片](http://szdf.oss-cn-shenzhen.aliyuncs.com/2017/09/19/9e2675b0-7c6b-453a-9844-5720def385ee.png)

### What is expected?
希望当切换后下划线切过去

### What is actually happening?
 字体的高亮已经切过去了 但是下划线并没有切过去

**Comment by silentcloud** [comment]
@KurobaZhang 如果你要用 0.48 版本的 RN 的话， antd-mobile 用 2.0.0-beta2
