### ISSUE TITLE
 React-creat-app 改变了，移动版相关配置没有更新。  没有config和scripts文件了，需要修改相关配置

### ISSUE THREAD

**Issue by oldturkey** [ant-design/ant-design-mobile#1869]
### Version
1.6.8

### Environment
不需要

### Reproduction link
[https://ant.design/changelog-cn](https://ant.design/changelog-cn)

### Steps to reproduce
不需要

### What is expected?
可以尽快更新或者回答怎么解决配置问题。和PC版一样，重写关于《在 create-react-app 中使用》的文档

### What is actually happening?
不需要

**Comment by silentcloud** [comment]
@oldturkey 需要先`npm run eject `

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1829
