### ISSUE TITLE
The carousel cannot init the height in tabbar

### ISSUE THREAD

**Issue by SanPy** [ant-design/ant-design-mobile#1871]
### Version
1.6.8

### Environment
win10 chrome pc版本

### Reproduction link
[https://mobile.ant.design/components/carousel-cn/](https://mobile.ant.design/components/carousel-cn/)

### Steps to reproduce
Defined a carousel in tabBar, the height of carousel inited failed when from a tabBar's item back。

### What is expected?
The carousel height show normal when change the tabBar's item.

### What is actually happening?
The carolsel height inited failed, the pic of carousel have be covered

---
我在标签栏组件中的某个item中使用了一个走马灯。刷新页面进入走马灯所在的item时高度是正常的，但是从其他的item切换回来的时候，走马灯的高度就变得很小，以至于走马灯里的图片全部被遮挡了！

**Comment by warmhug** [comment]
carousel 强烈建议设置固定高度，或者参考 demo 自己在合适时机计算高度做设置。
