### ISSUE TITLE
Add customize theme document

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1872]
ref https://ant.design/docs/react/customize-theme-cn

antd-mobile theme variable name is not the same as antd, eg [@brand-primary](https://github.com/ant-design/ant-design-mobile/blob/1.x/components/style/themes/default.less#L33) , which caused some problems to users.

We'd better keep a customize theme document in our own site.

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/pull/1882
https://github.com/ant-design/ant-design-mobile/pull/1887
https://github.com/ant-design/ant-design-mobile/pull/1881
