### ISSUE TITLE
remove Non-null assertion operator assignment

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1873]
## 问题
TypeScript 对 `this.props.foo`  推断不会考虑 `defaultProps` 定义的值，所以 `foo` 的类型中固定会有 `undefined` , 导致调用的时候会有 `strictNullChecks` warning, 所以代码里有些用了 TypeScript [Non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator)  

有一种情况为了方便，避免在多处调用 this.props.foo 的时候加 `!`, 直接提前赋值，eg: [Grid](https://github.com/ant-design/ant-design-mobile/blob/master/components/grid/index.tsx#L130) 但这种编译过后没有被 uglify, 造成冗余。

![Uploading 屏幕快照 2017-09-21 15.18.37.png…](https://gw.alipayobjects.com/zos/rmsportal/PaROCUSGtkoUneEItEbl.png)
![Uploading 屏幕快照 2017-09-21 15.18.29.png…](https://gw.alipayobjects.com/zos/rmsportal/xOqbTmxUnlFDdfqKZwxP.png)
![xx](https://gw.alipayobjects.com/zos/rmsportal/lJECYXCGHAahsWvrmMIg.png)
https://unpkg.com/antd-mobile@2.0.0-beta.2/lib/grid/index.js

https://unpkg.com/antd-mobile@2.0.0-beta.2/dist/antd-mobile.js

https://unpkg.com/antd-mobile@2.0.0-beta.2/dist/antd-mobile.min.js

## 方案
- 都改成在调用的时候加 `!`
- 或者寻找其他方案

**Comment by paranoidjk** [comment]
cc @xufei

**Comment by silentcloud** [comment]
我一般都是类似  `this.props.xxxx!(args)`

**Comment by paranoidjk** [comment]
@silentcloud 恩，你这种编译过后没有残留，就是写起来麻烦，代码里散落着各种 `!`。

**Comment by paranoidjk** [comment]
最佳的方案是看有没有办法不依赖强制 cast

**Comment by paranoidjk** [comment]
cc @shepherdwind

**Comment by warmhug** [comment]
@paranoidjk 结论是什么？没结论关掉

**Comment by HerringtonDarkholme** [comment]
题主可以试用一下这种方法。

```ts
class Component<Props> {
  props: Props 
  static defaultProps: {}
}

interface BaseProps {
  columnNum?: number
}

interface GridProps extends BaseProps {
  className?: string 
}
type Default<C extends { defaultProps: {}}> = C['defaultProps'] 
class Grid extends Component<GridProps> {
  props: GridProps & Default<typeof Grid>
  static defaultProps = {
    columnNum: 123
  }
  render() {
    this.props.className.toString
    this.props.columnNum.toString
  }
}
```

这种方法的开销是手动写一个 props 的声明，不需要手动列出 DefaultProps。相比 https://github.com/Microsoft/TypeScript/issues/18675 会更简单
