### ISSUE TITLE
carousel组件native版本  如果infinity这是为true 默认显示第二个图

### ISSUE THREAD

**Issue by KurobaZhang** [ant-design/ant-design-mobile#1874]
### Version
1.6.8

### Environment
rn 0.48  react  16.0.0.alpha.12 

### Reproduction link
[https://codepen.io/kuroba12345/pen/veKjJB](https://codepen.io/kuroba12345/pen/veKjJB)

### Steps to reproduce
onLayout = (e) => {
    // for horizontal, get width, scollTo
    const props = this.props;
    const count = props.children ? props.children.length || 1 : 0;
    const selectedIndex = count > 1 ? Math.min(props.selectedIndex as number, count - 1) : 0;
    const width = e.nativeEvent.layout.width;
    const offsetX = width * (selectedIndex +  (props.infinite ? 1 : 0));
    this.setState({
      width,
      offset: { x: offsetX, y: 0 },
    }, () => {
      if (Platform.OS === 'android') {
        this.scrollviewRef.scrollTo({ y: 0, x: offsetX }, false);
      }
    });
  }

源码中这一段  const offsetX = width * (selectedIndex +  (props.infinite ? 1 : 0));  selectedIndex设置为0的时候，如果props.infinite为true offsetX就会成为第二屏的图片，

### What is expected?
selectedIndex为0   infinite为true  显示第一屏的图片

### What is actually happening?
如上文所说， 显示次序出错

**Comment by silentcloud** [comment]
@kasinooya 没问题哈，看这里代码 https://github.com/ant-design/ant-design-mobile/blob/1.6.10/components/carousel/index.tsx#L303

运行也是 ok 的哈

![show](https://user-images.githubusercontent.com/1698185/30801463-fc575118-a1a8-11e7-8582-72ce911e9105.gif)

**Comment by wrightjin** [comment]
@silentcloud 你是否有试过在Android里面测试？我在Android里面确实会出现这样的问题，而且好像所有的Carousel组件都会有，不仅仅是andt mobile

**Comment by zetaoWu** [comment]
some issues. Carousel selectedIndex is not work in Android. @wrightjin  How do you solve it?

**Comment by fuxianwei** [comment]
me too

**Comment by a88053443** [comment]
solve ?
