### ISSUE TITLE
Upgrade to react@16 / react-native@0.49 / enzyme@3

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1876]
> We'll include the license updates with React 16's release next week. 

-  https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
- https://github.com/facebook/react/issues/10294
- https://github.com/airbnb/enzyme/issues/928
- https://github.com/facebook/react-native/blob/master/package.json#L136

ref https://github.com/ant-design/ant-design/issues/5377

cc @ant-design/ant-design-team

**Comment by silentcloud** [comment]
react-native@0.49 must be with react@16

**Comment by paranoidjk** [comment]
> react-native@0.49 must be with react@16

所以升级是 react 和 react-native 一起升

> 上次我升级react@16 ,rn@0.48 可以的，主要是测试跑不过，react-native-mock 还没新版本

web 测试依赖 enzyme@3 正式版，rn 测试再调研下好了，优先级可以相对放低

**Comment by yesmeck** [comment]
enzyme 3 没碰到问题吗？

**Comment by silentcloud** [comment]
@yesmeck 碰到一个 https://github.com/facebook/react/issues/10320

**Comment by silentcloud** [comment]
还有比较奇怪，RN 本地除了 imager-picker 没跑过（依赖库要升级）外，其他都ok，ci 跑不动

**Comment by yesmeck** [comment]
https://github.com/airbnb/enzyme/blob/master/packages/enzyme-adapter-react-16/src/ReactSixteenAdapter.js#L3

RN 估计需要一个 enzyme-adapter-react-native

**Comment by silentcloud** [comment]
@yesmeck 我本地是跑过了的，RN 目前基本都是 mock

**Comment by yesmeck** [comment]
@silentcloud 确定下你本地的 react 版本

**Comment by paranoidjk** [comment]
- [ ] unstable_renderSubtreeIntoContainer  https://github.com/ant-design/ant-design-mobile/issues/1897 

还有很多问题没解决不要关 issue

**Comment by zhang740** [comment]
bisheng ref https://github.com/benjycui/bisheng/issues/102

**Comment by silentcloud** [comment]
@warmhug 
- [ ] 还差 listview 的问题没解决

**Comment by Manweill** [comment]
2.0 topview.js 0.49下报错，能做下兼容么

**Comment by silentcloud** [comment]
@Manweill 好 我等会看看，不过建议你使用 0.48.x

**Comment by Manweill** [comment]
@silentcloud 还是createReactClass的问题，你先看看吧。

**Comment by silentcloud** [comment]
@Manweill 我把仓库更新到 0.49.3，没重现； 另外 topview 没有 createReactClass 相关到代码，确定一下你本地 rn-topview 的版本是不是最新

**Comment by Manweill** [comment]
@silentcloud 我的是antd2.0.0-beta.5。是topview 里面调用react.default.createClass的问题。这个方法在react16已经移除。我人工替换调，可以成功build

**Comment by silentcloud** [comment]
@Manweill 我是说你本地 rn-topview 的版本是多少？topview 里没有用到 createClass

**Comment by Manweill** [comment]
@silentcloud rn-topview 版本是0.1.3

**Comment by silentcloud** [comment]
@Manweill 那就是版本不对，0.1.6 才是正确的

**Comment by Manweill** [comment]
@silentcloud antd-mobile内置的是0.1.3，你了解下。

**Comment by silentcloud** [comment]
@Manweill 没有内置 0.1.3 哈 https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L61

**Comment by Manweill** [comment]
@silentcloud 你看下你node_modules下的antd-mobile文件里里面，有单独有下载了个topview的

**Comment by Manweill** [comment]
@silentcloud 发现问题了，yarn.lock的锅。。。T.T

**Comment by silentcloud** [comment]
db8e2354bf55874cd111615bb6b2e2afd9e33c81
