### ISSUE TITLE
Add doc about how customize theme with webpack

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#1878]
> 这是本人踩了无数坑，试错，总结出一套 **步骤清晰，操作简便** 关于antd的自定义主题的通用解决方案！希望能帮助在这方面有困惑的同学。
> 
> 随着 antd-mobile 2.0（以下简称2.0）的到来（感谢开发组的杰出工作），包括本人在内的前端对2.0自定义主题的需求越来越迫切，然而如何给2.0自定义主题，截至笔者写这篇分享也没有找到一篇文章能把这个看似简单的问题说明白透彻的！
>
>包括官网给出的[自定义主题文档](https://ant.design/docs/react/customize-theme-cn)也是让人看的云里雾绕。由于本人自配脚手架，所以这里介绍 **如何结合webpack为2.0定义主题。**
###### 总共四步：
1. 首先，你的项目里需要安装依赖 `babel-plugin-import less less-loder` 。(当然，`style-loader css-loader`这些最基础的样式依赖肯定也是要有的)

    ```
    npm install --save-dev babel-plugin-import less less-loder
   ```
1. 其次，在你项目中的`.bablrc`文件中需要有以下配置

    ```
    {
        ...
        "plugins": [
            ["import", {"libraryName": "antd-mobile", "style": true}],
            ...
        ]
    }
   ```
1. 再次，在 `package.json` 文件中添加一个 theme 字段，里面将包含所有我们想要修改的主题样式。[全部主题样式参考这里](https://github.com/ant-design/ant-design-mobile/blob/master/components/style/themes/default.less)
    ```
    {
        ...
        "theme": {
            "brand-primary": "red",
            "color-text-base":  "#333",
            ...
        },
        ...
    }
   ```

1. 最后，在你的 webpack （建议版本3.0+） 配置文件里，添加如下配置，之后运行你的 `npm start`，看到惊喜了吗？
    ```
    const pkg = require('./package.json')

    module.exports = {
        ...
        module: {
            ...
            rules: [
                ...
                {
                    test: /\.css$/,
                    use: [
                        'style-loader',
                        'css-loader',
                    ],
                },
                {
                    test: /\.less$/,
                    use: [
                        'style-loader',
                        'css-loader',
                        {loader: 'less-loader', options: {modifyVars: pkg.theme}},
                    ],
                    include: /node_modules/,
                },
                ...
            ],
        },
        ...
    }
   ```
---
另外，**[高清方案](https://github.com/ant-design/ant-design-mobile/wiki/HD)在 2.0 中并不是必须的**，如果你想在2.0中使用高清方案，需要对其做下适配处理，操作很简单，在前面主题配置的第三步中，在 theme 字段中修改hd变量为 0.02rem 即可。
```
  {
      ...
      "theme": {
          "hd": "0.02rem",
          "brand-primary": "red",
          "color-text-base":  "#333",
          ...
      },
      ...
  }
  ```
后话：如果你对为什么要把hd 改为 0.02rem 感到好奇，欢迎访问[本人写的这篇博客](http://www.jianshu.com/p/985d26b40199)，此文中笔者对高清源码稍作修改，使该方案能灵活适用于百度地图这类特殊场景。

**Comment by paranoidjk** [comment]
> 在 theme 字段中修改hd变量为 0.02rem 即可。

这里取决于做法，我们推荐的是设置 `@hd: 2px`, 业务代码的样式也全部采用 px 为单位，通过 postcss 的 px-to-rem plugin 编译成 rem, 这样写样式的时候开发者不需要换算，简单一点。

**Comment by paranoidjk** [comment]
@minooo 👍 欢迎把你的这篇文档 Pull Request 加到我们官方文档里来，可以参考 ant-design 的文档写法优化一下 https://github.com/ant-design/ant-design/blob/master/docs/react/customize-theme.zh-CN.md

**Comment by paranoidjk** [comment]
另外高清方案在 2.0 中并不是必须的，这个可以在文档中体现一下。

**Comment by minooo** [comment]
> 这里取决于做法，我们推荐的是设置 @hd: 2px, 业务代码的样式也全部采用 px 为单位，通过 postcss 的 px-to-rem plugin 编译成 rem, 这样写样式的时候开发者不需要换算，简单一点。
@paranoidjk 有道理，不过你的方式又多了一层工具转换，而我的方式很容易转换，心算就可以了，比如57px => 0.57rem。不过我得需要说明下😄
