### ISSUE TITLE
Where is the  code of antd-mobile apk，I can download the apk file,but I can't find the code,THX!

### ISSUE THREAD

**Issue by xdkaka** [ant-design/ant-design-mobile#1880]
### Version
1.6.8

### Environment
react-native android

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
I can download the apk file,but I can't find the code!

### What is expected?
I can find the code of apk

### What is actually happening?
I can't find the code!

**Comment by zhang740** [comment]
https://github.com/ant-design/ant-design-mobile/tree/1.x/rn-kitchen-sink

**Comment by paranoidjk** [comment]
@zhang740 shall we add a explanation about the project directory structure in https://github.com/ant-design/ant-design-mobile/blob/master/development.zh-CN.md ? 

```bash
├── AUTHORS.txt
├── CHANGELOG.en-US.md
├── CHANGELOG.zh-CN.md
├── LICENSE
├── README.md
├── README.zh-CN.md
├── _site
├── ant-design-analysis
├── cdn-config.js
├── components
├── development.en-US.md
├── development.zh-CN.md
├── dist
├── docs
├── es
├── index.js
├── index.native.js
├── lib
├── node_modules
├── package.json
├── rn-kitchen-sink
├── scripts
├── site
├── tests
├── tsconfig.json
├── typings
├── webpack.config.js
└── yarn-error.log

```
