### ISSUE TITLE
移动版 DatePicker 日期选择 

### ISSUE THREAD

**Issue by GuiYangGan** [ant-design/ant-design-mobile#1883]
`<DatePicker mode="time" {...getFieldProps('time1')} minuteStep={5}>
     <List.Item arrow="horizontal">时间(local time)</List.Item>
</DatePicker>`

![1417175504396o6g](https://user-images.githubusercontent.com/24996770/30791306-313dd3e4-a1e4-11e7-86fd-e136f9589473.png)

这个例子在没有任何操作直接点确定的情况下，如果本地时间跟显示的时间不同，那么确定后会直接显示本地时间，请问怎么解决？

**Comment by paranoidjk** [comment]
duplicated with me https://github.com/ant-design/ant-design-mobile/issues/1884
