### ISSUE TITLE
about ant design mobile DatePicker problem

### ISSUE THREAD

**Issue by GuiYangGan** [ant-design/ant-design-mobile#1884]
### Version
undefined

### Environment
chrome(60.0.3112.113)

### Reproduction link
[https://mobile.ant.design/components/date-picker-cn/](https://mobile.ant.design/components/date-picker-cn/)

### Steps to reproduce
重现链接中的第二个时间选择例子，不做任何选择操作，直接点确定

### What is expected?
确定后页面显示选中的时间

### What is actually happening?
确定后页面显示的是本地的当前时间

**Comment by GuiYangGan** [comment]
Version

undefined

Environment

chrome(60.0.3112.113)

Reproduction link

https://mobile.ant.design/components/date-picker-cn/

Steps to reproduce

The second example of Reproduction link,
Don't do any choice,
Directly click ok.


What is expected?

After the page displays the selected time.

What is actually happening?

After the page displays the local time.

**Comment by warmhug** [comment]
This is normal behavior. ref https://github.com/react-component/m-date-picker/issues/27

**Comment by Mathieu-Lu** [comment]
我也遇到了同样的问题，希望能尽快解决

**Comment by GuiYangGan** [comment]
Local time : 14:50, Selected time : 14:00
Users will be in a puzzle.
When 14:00 is selected by default, and i click ok,why the time is 14:50 on the page.

**Comment by Mathieu-Lu** [comment]
@GuiYangGan 建议你先设置minuteStep属性为1，先解决业务的基本实现问题，等官方修复

**Comment by GuiYangGan** [comment]
@Mathieu-Lu 貌似也只能这样了....

**Comment by warmhug** [comment]
https://github.com/react-component/m-date-picker/commit/31bdd705e3db99b87cadb88466cf6cbefcbc337f
