### ISSUE TITLE
hairline problem in demo

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1885]
![image](https://user-images.githubusercontent.com/1698185/30793703-39bd0e10-a1f6-11e7-8f85-52cf8fb45b8a.png)

**Comment by paranoidjk** [comment]
这个粗线是 demo 里面写的元素和样式，不是组件。

除非把 https://github.com/ant-design/ant-design-mobile/blob/master/components/style/mixins/hairline.less 引用到 demo 里面使用

**Comment by paranoidjk** [comment]
cc @zhang740 @warmhug 看下这类情况如何处理比较好

用户如果 不使用 viewport 缩放 + antd-mobile@2.x ，那他就要自己实现 1px 线了，我们是否暴露一个 util 的类名或者 less mixin 出来？

**Comment by warmhug** [comment]
现在 内部 的 mixin 用户不能使用？

**Comment by paranoidjk** [comment]
内部的用户能使用，但我们 demo 代码里不太适合暴露这样的用法？

**Comment by paranoidjk** [comment]
这个要怎么处理？demo 里面总不能去 require antd-mobile mixin less 文件？在 demo 里再写一个 hairless 实现也不合适，没想到啥好方法。

有办法改这个的 reopen 吧。
