### ISSUE TITLE
InputItem setted 'type=text' cannot be input anything? 

### ISSUE THREAD

**Issue by SanPy** [ant-design/ant-design-mobile#1886]
### Version
1.6.8

### Environment
win10 chrome pc版本

### Reproduction link
[https://mobile.ant.design/components/input-item-cn/](https://mobile.ant.design/components/input-item-cn/)

### Steps to reproduce
不好重现，就是在我的项目中出现，但是我重新构建一个新的项目是没有问题的

### What is expected?
InputItem type=text can input text。

### What is actually happening?
InputItem type=text can not input text.

---
On chrome, i check the running code. i find that the input element'style is "display:none" under the InputItem code. But i donot know why

**Comment by SanPy** [comment]
I have resolved this problem. I find that all the component's style will be affected when you set dom element style.For example, when i set the input's style is "display:none"， then all the input of app  will have a style "display:none".

**Comment by silentcloud** [comment]
Can not reproduce.

**Comment by silentcloud** [comment]
If you have reproducible demo, please feel free to reopen the issue
