### ISSUE TITLE
Picker demo

### ISSUE THREAD

**Issue by lunarun** [ant-design/ant-design-mobile#1888]
### Version
1.6.11

### Environment
Google Chrome 60.0.3112.113（正式版本） （64 位）

### Reproduction link
[https://mobile.ant.design/components/picker-cn/](https://mobile.ant.design/components/picker-cn/)

### Steps to reproduce
Picker demo -->  ‘外部控制visible'--> click’取消‘

### What is expected?
It should close Picker wrapper.

### What is actually happening?
Picker wrapper haven't been closed.

**Comment by paranoidjk** [comment]
@zhang740 看看是 demo 写法问题还是源码 bug?
