### ISSUE TITLE
click   ,ImagePicker no response in iOS

### ISSUE THREAD

**Issue by itxuye** [ant-design/ant-design-mobile#1889]
### Version
1.6.11

### Environment
iOS 11 

### Reproduction link
[http://mobile.ant.design/kitchen-sink/](http://mobile.ant.design/kitchen-sink/)

### Steps to reproduce
imagpicker在iOS 上点击无响应，Android是好的，官方的demo就可以复现

### What is expected?
点击正常

### What is actually happening?
点击增加图片无反应

**Comment by paranoidjk** [comment]
works fine in iphone 6s plus safari ios11.

ImagePicker it's just a wrapper of `<input type="file"/>`.
