### ISSUE TITLE
[Android][Chrome] Focused InputItem jump page when click a button

### ISSUE THREAD

**Issue by EricThsi** [ant-design/ant-design-mobile#1891]
### Version
1.6.8

### Environment
Android 6.0； Chrome 61.0.3163.98；React 15.5.4

### Reproduction link
[http://www.hardint.com/food/diy/new?t=breakfast](http://www.hardint.com/food/diy/new?t=breakfast)

### Steps to reproduce
1. There has a InputItem, and another button(this button has bind a click callback , but callback
 don't has actions such as browserHistory push or link page);
2. Focus the InputItem when page init, and direct click the button element, current page jump to another;

### What is expected?
No page jump, trigger the button's callback.

### What is actually happening?
Current page link to another.

**Comment by paranoidjk** [comment]
@warmhug @zhang740  有 Android 的测试下

**Comment by zhang740** [comment]
Can you provide a reproduce path? @EricThsi

**Comment by EricThsi** [comment]
@zhang740 click this link [http://www.hardint.com/food/diy/new?t=breakfast](http://www.hardint.com/food/diy/new?t=breakfast) use wechat app.

**Comment by warmhug** [comment]
Please give the source code, or debug yourself

**Comment by silentcloud** [comment]
Close for no response.
