### ISSUE TITLE
2.0使用@hd 2px后，列表中下划线变的深浅不一，粗细不等

### ISSUE THREAD

**Issue by KingBarbarian** [ant-design/ant-design-mobile#1892]
### Version
2.0beta

### Environment
iPhone 6s ios11，chrome最新

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/](https://github.com/ant-design/ant-design-mobile/)

### Steps to reproduce
2.0使用@hd 2px后，列表中下划线变的深浅不一，粗细不等

### What is expected?
2.0使用@hd 2px后，列表中下划线变的深浅不一，粗细不等

### What is actually happening?
2.0使用@hd 2px后，列表中下划线变的深浅不一，粗细不等

**Comment by paranoidjk** [comment]
没有使用 antd-mobile@1.x 的高清方案脚本的话，直接去掉 html 标签上的 data-scale 属性。

**Comment by KingBarbarian** [comment]
请指脚下，这是删除data-scale和 antd-mobile@1.x脚本后的index.html,效果为全部放大
```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Lux</title>
  <meta id="viewport" name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1; user-scalable=no;">
  <link rel="stylesheet" href="/static/font.css">
  <script src="https://as.alipayobjects.com/g/component/fastclick/1.0.6/fastclick.js"></script>
  <script>
    if ('addEventListener' in document) {
      document.addEventListener('DOMContentLoaded', function () {
        FastClick.attach(document.body);
      }, false);
    }
    if (!window.Promise) {
      document.writeln('<script src="https://as.alipayobjects.com/g/component/es6-promise/3.2.2/es6-promise.min.js"' + '>' + '<' + '/' + 'script>');
    }
  </script>
  <style>
    .am-list-item.am-input-item {
      padding-left: 0px !important;
      padding-right: 0px !important
    }
  </style>
</head>

<body>
  <div id="app"></div>
</body>

</html>
```

**Comment by paranoidjk** [comment]
你这段代码什么都没有，看不出问题。

给出你的整个代码库，或者可复现的 demo。

> 请指脚下，这是删除data-scale和 antd-mobile@1.x脚本后的index.html,效果为全部放大

如果是 antd-mobile@2.0, 你删除所有高清方案和 viewport 缩放的配置之后，页面不可能放大。
