### ISSUE TITLE
Virtual Keyboard cover InputItem in Mobile Safari (React Web)/当InputItem聚焦时，虚拟键盘应该是InputItem字段的底部。

### ISSUE THREAD

**Issue by gordongordon** [ant-design/ant-design-mobile#1893]
### Version
1.6.11

### Environment
mobile Safari 11.0 browser, react 16.0.0 (doesn't matter what version), ios 11 (Doesn't matter what version)

### Reproduction link
[https://github.com/gordongordon/antd-mobile-input-issue](https://github.com/gordongordon/antd-mobile-input-issue)

### Steps to reproduce
yarn start, open the localhost: 3000 or your ip:3000 in iphone ios with Safari mobile.  and touch any field with placeholder from 4,5,6,..11. And you will see the virtual keyboard cover input field. It is not good for mobile user in ios. 

### What is expected?
Virtual keyboard should be right below an InputItem field, while focus. 
当InputItem聚焦时，虚拟键盘应该是InputItem字段的底部。

### What is actually happening?
Virtual keyboard cover an InputItem field with Placeholder after 4,5,6,...11.  So, out focus. It is working fine in android Chrome. 
当InputItem聚焦时，虚拟键盘覆盖InputItem (4,5,6,11)字段底部。 用户看不到要输入的内容？

---
It happens since, I use antd-mobile from 15.xx , react 15.xx

![inputitemissue](https://user-images.githubusercontent.com/21987380/30902230-1afd3754-a39d-11e7-9502-e529b153e12c.jpeg)

**Comment by niexiaofei1988** [comment]
安卓机(测试 华为P8) 一个列表中同时有多个，inputItem,不同类型,其中一个为money时,在切换原生虚拟键盘和自定义键盘时会出现闪屏问题

**Comment by niexiaofei1988** [comment]
定义type="money"时,光标只能定位在右侧,如若修改css可以将其设置在左侧,但光标不能跟随值的变化而移动(原生input的光标一直定位在右侧,输入值时光标跟随移动)源代码中也是根据DOM设置的，能不能设置一个before,将其content设置为输入的值,这样就能跟随移动了

**Comment by paranoidjk** [comment]
@niexiaofei1988 `moneyKeyboardAlign="left"` 光标从左开始 http://beta.mobile.ant.design/components/input-item-cn/#API

**Comment by paranoidjk** [comment]
@pingan1927 你虚拟键盘是什么布局的？弹出的时候会改变 webview 高度吗？是否是因为没改变 webview 高度，导致 InputItem onFocus 里面 scrollIntoViewIfNeeded 不起作用引起的

**Comment by silentcloud** [comment]
我调试了一下，去掉这段代码 https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.tsx#L132-L138 就可以了，但是不知道最初写这个有什么原因，怕有坑 @pingan1927

**Comment by silentcloud** [comment]
This will be fixed in antd-mobile@2.0.4
