### ISSUE TITLE
2.0 自定义 Icon 文档

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1894]
刚这边的有几个同学都在咨询 2.0 的自定义 Icon 使用的问题，这个在文档上还是要体现出来，现在没有

**Comment by paranoidjk** [comment]
如果是升级就看升级文档 http://beta.mobile.ant.design/docs/react/upgrade-notes-cn#svg-icon

如果是 2.0 新用户，不再提供自定义 Icon 这个东西，用户自己决定，可以用 img, 可以用 iconfont，可以用 svg 等等。

**Comment by paranoidjk** [comment]
有人问就把升级文档发他就好。

**Comment by warmhug** [comment]
我来补充下吧，文档还是要稍微多写一下的。比如，我们`.am-icon`这个基础样式对用户的自定义 icon 也是有用的。
