### ISSUE TITLE
input-item style with ellipsis instead

### ISSUE THREAD

**Issue by lunarun** [ant-design/ant-design-mobile#1895]
### Version
1.6.11

### Environment
IPhone7 plus ,  Chrome  61.0.3163.100

### Reproduction link
[http://beta.mobile.ant.design/kitchen-sink/components/input-item?lang=zh-CN#input-item-demo-0](http://beta.mobile.ant.design/kitchen-sink/components/input-item?lang=zh-CN#input-item-demo-0)

### Steps to reproduce
input control part: 'am-input-control' class with the style -->
    'width: auto;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;'
but the style doesn't work. 
If input content length exceeds input control visible length, there is no ellipsis  instead.

### What is expected?
I'm unsure about whether you developers want to show ellipsis instead,
 i just saw the ellipsis style, but there is no ellipsis shown.

### What is actually happening?
Maybe it should show ellipsis instead.

**Comment by paranoidjk** [comment]
I think there should be no `ellipsis` style in input, since users may want to see the content they text.

**Comment by lunarun** [comment]
So in 'am-input-control' style part, the code
'overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap',
are redundant? 
or where use them?

**Comment by silentcloud** [comment]
@lunarun 

```
'overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap',
```
just for use in `type=money`, I will fix this later
