### ISSUE TITLE
有兼容reactDom16的计划吗？

### ISSUE THREAD

**Issue by gxy01** [ant-design/ant-design-mobile#1897]
### What problem does this feature solve?
react更新了16。之前大家都用unstable_renderSubtreeIntoContainer来实现挂载在自定义dom节点的元素，比如portal。但是react16有一个变动 https://github.com/facebook/react/issues/10310 。 
今天发现CustomInput里面使用了这个方法，元素创建的时候，某些情况下会返回null，导致antmCustomKeyboard 为空，这样input组件销毁的时候清楚对应元素的时候就会出错。
我看在2.0beta的package.json里写了react16。不过这还是有问题啊。
建议：对unstable这种开头的api在大版本还是扫描一下？
总之就是兼容下react16吧。多谢

### What does the proposed API look like?
保持不变，但是兼容react16

**Comment by silentcloud** [comment]
@gxy01 嗯，目前正在做 16 的兼容处理

**Comment by paranoidjk** [comment]
trace https://github.com/ant-design/ant-design-mobile/issues/1876

**Comment by xiaochunyong** [comment]
这个问题好像还没解决诶

**Comment by zhang740** [comment]
@xiaochunyong 有版本判断的，具体哪个组件在16下有问题可以提Issue

**Comment by xiaochunyong** [comment]
@zhang740  已提issue #2040
