### ISSUE TITLE
Typescript在 next.js 环境下使用 antd-mobile 报错has no default export.

### ISSUE THREAD

**Issue by xjl271314** [ant-design/ant-design-mobile#1898]
### Version
1.6.11

### Environment
react,next.js,dva,系统版本MAC

### Reproduction link
[https://mobile.ant.design/docs/react/introduce-cn](https://mobile.ant.design/docs/react/introduce-cn)

### Steps to reproduce
正常运行的next.js，Typescript,react环境下 添加antd-mobild ，在 .babelrc里也配置了  ["import", { "style": "css", "libraryName": "antd-mobile" }]，运行环境后 加载任意一组件就报 各模块 has no default export.

### What is expected?
能够在 next.js，Typescript,react正常使用 antd-mobile 组件

### What is actually happening?
正常运行的next.js，Typescript,react环境下 添加antd-mobild ，在 .babelrc里也配置了  ["import", { "style": "css", "libraryName": "antd-mobile" }]，运行环境后 加载任意一组件就报 各模块 has no default export.

**Comment by paranoidjk** [comment]
https://github.com/zeit/next.js/tree/master/examples/with-antd-mobile

**Comment by xjl271314** [comment]
使用的 TypeScript 不是js,JS使用那是没问题

**Comment by qinyang1980** [comment]
(create react app + typescript + antd) without eject and without using Babel.

https://github.com/qinyang1980/create-react-antd-app.git

antd-mobile is same
