### ISSUE TITLE
alert

### ISSUE THREAD

**Issue by andylidong** [ant-design/ant-design-mobile#1899]
如何修改alert的样式，底部取消按钮和确认按钮的字体颜色，两个都不一样
    buttonText: {
        textAlign: 'center',
        color: "#9B9B9B",//_default2['default'].color_link,
        fontSize: 12, // _default2['default'].modal_button_font_size,
        backgroundColor: 'transparent'
    },

**Comment by silentcloud** [comment]
@andylidong 什么环境？ RN？

**Comment by andylidong** [comment]
RN,
import { Modal } from "antd-mobile";
const alerts = Modal.alert;
    alerts("", message, [
      {
        text: "取消",
        onPress: () => {
          if (onCancelClick) onCancelClick();
        }
      },
      {
        text: "确定",
        onPress: () => {
          if (onOkClick) onOkClick();
        }
      }
    ]);

**Comment by andylidong** [comment]
怎么修改样式呢，如果不能修改，有没有替代的组件，popup居中之后，下面的阴影就消失了

**Comment by andylidong** [comment]
我想分别需改字体的大小，取消和确定的字体的颜色

**Comment by silentcloud** [comment]
@andylidong 

```js
{ text: '取消', onPress: () => {}, style: { color: 'red', fontSize:  14} },
```

**Comment by andylidong** [comment]
![image](https://user-images.githubusercontent.com/18454971/35722690-48ade03c-0832-11e8-81c8-6be23d4fd560.png)
![image](https://user-images.githubusercontent.com/18454971/35722714-5a6b48b4-0832-11e8-943b-460c746911c1.png)

这样调用组件有问题吗
