### ISSUE TITLE
toast 动画样式统一

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#19]
参考 date-picker/action-sheet

**Comment by silentcloud** [comment]
@yiminghe  已经在本地改了，1.0 再上，同时修复了 toast 遮住 navibar 的问题

**Comment by warmhug** [comment]
modal 里把 maskAnimation 改为 maskTransitionName ？和 action-sheet 一样

**Comment by warmhug** [comment]
@silentcloud toast 和 modal 你那里一起改掉， cherry-pick 到 0.7 上吧。等 1.0 太久了。

**Comment by silentcloud** [comment]
toast & modal fixed
