### ISSUE TITLE
样式中的iconfont没有加载进来

### ISSUE THREAD

**Issue by huiop368** [ant-design/ant-design-mobile#190]
配置好 babel-plugin-antd, 然后import 相应的模块.
以top-notice 为例，`import { TopNotice } from 'antd-mobile'` 后， 基础样式都有了， 但是发现 x icon没有显示出来.
看了下 网络请求， 相应的 iconfont 没有下载.....

请问怎么回事?

**Comment by AmethystCat** [comment]
我也碰到了这个问题，还未解决。

**Comment by AmethystCat** [comment]
解决了，我本地webpack配置里的css-loader设置了sourceMap，去掉sourceMap后，字体图标能正常显示，具体原因还在查证。

**Comment by huiop368** [comment]
谢谢哈， 我试试~!!!

**Comment by zhoujun900113** [comment]
@AmethystCat 帮我看看，我的图标也不能显示
