### ISSUE TITLE
Picker issue

### ISSUE THREAD

**Issue by lzctbyong** [ant-design/ant-design-mobile#1900]
` [
        {
            label    : '成员',
            value    : 20,
            children : [
                {
                    label : '配偶',
                    value : 10,
                },
                {
                    label : '父母',
                    value : 20,
                },
                {
                    label : '儿女',
                    value : 30,
                },
                {
                    label : '亲戚',
                    value : 40,
                },
                {
                    label : '其他',
                    value : 99,
                } ]
        },
        {
            label    : '成员2',
            value    : 20,
            children : [
                {
                    label : '配偶2',
                    value : 10,
                },
                {
                    label : '父母2',
                    value : 20,
                },
                {
                    label : '儿女2',
                    value : 30,
                },
                {
                    label : '亲戚2',
                    value : 40,
                },
                {
                    label : '其他2',
                    value : 99,
                } ]
        },
    ]`

RN: 0. 48

it can't show normally, it 's no content when selected the item 1

**Comment by silentcloud** [comment]
@lzctbyong I suggest you use RN@0.42 with antd-mobile@1.x.

**Comment by lzctbyong** [comment]
i solve it , data must be String Type , Interge Type maybe have some issue
