### ISSUE TITLE
Use QQ Browser The page can't rendering  

### ISSUE THREAD

**Issue by 9262981** [ant-design/ant-design-mobile#1901]
page is white ,
The console information : 

Failed to load resource: net::ERR_INSECURE_RESPONSE
https://os.alipayobjects.com/rmsportal/VnttsLkEQmyLDBBluBQq.js Failed to load resource: net::ERR_INSECURE_RESPONSE
https://as.alipayobjects.com/g/component/??react/15.6.1/react.min.js,react/15.6.1/react-dom.min.js Failed to load resource: net::ERR_INSECURE_RESPONSE
https://os.alipayobjects.com/rmsportal/wzWaWInUcXErDyTwvySY.js Failed to load resource: net::ERR_INSECURE_RESPONSE
kitchen-sink.js:1 Uncaught ReferenceError: React is not defined(…)
https://as.alipayobjects.com/g/component/fastclick/1.0.6/fastclick.js Failed to load resource: net::ERR_INSECURE_RESPONSE
?lang=zh-CN:74 Uncaught ReferenceError: FastClick is not defined(…)
https://zos.alipayobjects.com/rmsportal/wIjMDnsrDoPPcIV.png Failed to load resource: net::ERR_INSECURE_RESPONSE

**Comment by 9262981** [comment]
https://mobile.ant.design/

not my page , is official page Url

**Comment by silentcloud** [comment]
I think `zos.alipayobjects.com` has been rejected by QQ Browser, try another Browser

**Comment by paranoidjk** [comment]
<img width="480" alt="2017-09-29 3 56 03" src="https://user-images.githubusercontent.com/7971415/31006303-c6a75e52-a4c1-11e7-9df4-6f477c5abbd1.png">
<img width="912" alt="2017-09-29 3 55 47" src="https://user-images.githubusercontent.com/7971415/31006304-c6aed7cc-a4c1-11e7-8b73-7d379c65d76e.png">
