### ISSUE TITLE
与其他 UI 库混用问题

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-design-mobile#1903]
### What problem does this feature solve?
之前也遇到过类似的问题，自己当时规避掉了，没有解决。

我现在再次遇到了这种问题，我们项目用 1.x 的版本，但是现在新增一个需求需要用到 Calendar ，我知道 2.0 有。但是我们目前没有升级的打算。于是，我就用了 rc-calendar 。

那么问题也出来了，我这么使用了高清方案，导致 rc-calendar 都显示的非常小，就是与正常 mobile 组件的比例不一致。

我该怎么去协调这种问题呢？

### What does the proposed API look like?
正常显示，无缝衔接。

**Comment by silentcloud** [comment]
@zjxpcyc 

一样的问题 https://github.com/ant-design/ant-design-mobile/issues/799

你直接把 rc-calendar 的 css copy 做个修改

**Comment by paranoidjk** [comment]
- 不管用什么手段，使用高清方案就要保证样式都是以 750 为基准写的两倍样式，比如用类似的脚本去将样式 `* 2` https://github.com/ant-design/ant-design-mobile/blob/master/scripts/rewrite-px.js

- 或者你不要使用 viewport 缩放的高清方案。

**Comment by silentcloud** [comment]
@zjxpcyc 还有一种比较好的方法，利用 https://www.npmjs.com/package/postcss-pxtorem 的 selectorBlackList 实现，比如 

```
pxtorem({
    rootValue: 100,
    selectorBlackList: [/^.rc-calendar*/]
}),
```
