### ISSUE TITLE
Possible to choose font color for InputItem's value in RN? Or just not documented?

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design-mobile#1904]
### What problem does this feature solve?
It seems like the style prop for InputItem is passed to a View tag (which makes sense), but is there any way to change the color of the inner font/text? This would be helpful if you use InputItem on a screen with a dark background (e.g. login screen/form with a dark purple background)

### What does the proposed API look like?
easiest:

`<InputItem textStyle={styles.whiteColorFont } style={styles.inputItemContainer} />`

or maybe allow to pass in the wrapper for the text value? eh,

```
<InputItem 
       innerValue={(value) => <Text style={styles.whiteColorFont }>{value}</Text> } 
       style={styles.inputItemContainer} 
/>

```

**Comment by paranoidjk** [comment]
In `antd-mobile@1`, you need to use `props.styles.input` 
- https://github.com/ant-design/ant-design-mobile/blob/1.x/components/input-item/index.tsx#L149
- https://github.com/ant-design/ant-design-mobile/blob/1.x/components/input-item/Input.tsx#L46

And `antd-mobile@2` is now in beta https://github.com/ant-design/ant-design-mobile/issues/1823

In `antd-mobile@2` `InputItem`, We just pass down all your props to react-native `TextInput` 

- https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/Input.native.tsx#L44

So you can use `props.style` to set all style attribute that react-native support https://facebook.github.io/react-native/docs/textinput.html#style

I suggest you give it a try.

**Comment by silentcloud** [comment]
@acomito see https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui

**Comment by acomito** [comment]
Thanks @silentcloud and @paranoidjk
