### ISSUE TITLE
Uncaught ReferenceError: TabBar is not defined

### ISSUE THREAD

**Issue by ccqiuqiu** [ant-design/ant-design-mobile#1907]
### Version
2.0.0-beta.3

### Environment
mac chrome

### Reproduction link
[https://github.com/ccqiuqiu/base-react](https://github.com/ccqiuqiu/base-react)

### Steps to reproduce
1、克隆项目
2、npm run build
3、访问dist目录下生成的文件index.html，在控制台看到报错 Uncaught ReferenceError: TabBar is not defined
4、而使用 npm run dev 不会出错

### What is expected?
正常访问

### What is actually happening?
js报错  Uncaught ReferenceError: TabBar is not defined

**Comment by silentcloud** [comment]
@ccqiuqiu 感觉是你项目哪里配置问题

![image](https://user-images.githubusercontent.com/1698185/31044091-f4b8a95a-a58d-11e7-993e-52939cb9aec0.png)

我都是可以打出变量的

![image](https://user-images.githubusercontent.com/1698185/31044093-05e19d0e-a58e-11e7-82f1-6edd4f076972.png)

**Comment by silentcloud** [comment]
我加了一行变量申明就可以了  

```
const Item = TabBar.Item;
```

**Comment by silentcloud** [comment]
build 的代码里都没解析

![image](https://user-images.githubusercontent.com/1698185/31044110-7cda4294-a58e-11e7-847d-a682c9d5d9d8.png)
