### ISSUE TITLE
build后出现Uncaught ReferenceError: TabBar is not defined

### ISSUE THREAD

**Issue by ccqiuqiu** [ant-design/ant-design-mobile#1908]
### Version
2.0.0-beta.3

### Environment
mac10.13  chrome node8

### Reproduction link
[http://ccqiuqiu.win/demo/base-react/#/todo](http://ccqiuqiu.win/demo/base-react/#/todo)

### Steps to reproduce
直接访问build后的网页

### What is expected?
正常访问

### What is actually happening?
页面加载失败，控制台报错Uncaught ReferenceError: TabBar is not defined

---
源码github地址 https://github.com/ccqiuqiu/base-react
此代码开发的时候没有问题，就是执行nom run build之后才会有问题

**Comment by silentcloud** [comment]
duplicate https://github.com/ant-design/ant-design-mobile/issues/1907
