### ISSUE TITLE
antd-mobile和Draft.js冲突

### ISSUE THREAD

**Issue by gutenye** [ant-design/ant-design-mobile#191]
CSS的 `user-select: none`, 会造成Draft.js编辑器在Safari Mobile下面不能用(不能选择和编辑文字), 但是其它平台Desktop, Android Mobile可以用. 只测试了Draft.js, 不过可以推测所有contenteditable的编辑器在Safari Mobile下面都不能用.

源文件: https://github.com/ant-design/ant-design-mobile/blob/master/components/style/index.less#L11

**Comment by gutenye** [comment]
Discussed at http://stackoverflow.com/questions/20823468/user-selectnone-breaking-safari-contenteditable

**Comment by silentcloud** [comment]
你要表达的意思？

如果需要这个特性，你本地重置 user-select 可以么？
