### ISSUE TITLE
和babel-preset-react-optimize插件冲突问题

### ISSUE THREAD

**Issue by ccqiuqiu** [ant-design/ant-design-mobile#1910]
### Version
2.0.0-beta.3

### Environment
mac10.13  chrome node8

### Reproduction link
[https://github.com/ccqiuqiu/base-react](https://github.com/ccqiuqiu/base-react)

### Steps to reproduce
1.打开项目根目录下 .babelrc文件  取消第11行（"presets": ["react-optimize"]）的注释
2.执行npm run build  访问项目目录dist下index.html, 控制台报错Uncaught ReferenceError: TabBar is not defined，对应 https://github.com/ant-design/ant-design-mobile/issues/1907
3.注释掉第11行不会出现这个问题

### What is expected?
不用注释.babelrc的第11行，build后也能正常使用

### What is actually happening?
不注释.babelrc的第11行，build后，访问/dist/index.html会报js错误

---
猜测是和babel-preset-react-optimize插件冲突了，希望能兼容

**Comment by silentcloud** [comment]
见不兼容不是 antd-mobile 来做的，这个issue 应该提给那个插件哈
