### ISSUE TITLE
tab pane can not be found in @2.0.0-beta4 

### ISSUE THREAD

**Issue by soju-cao** [ant-design/ant-design-mobile#1912]
### Version
2.0.0-beta.3

### Environment
mac react

### Reproduction link
[https://mock](https://mock)

### Steps to reproduce
import { Tabs } from 'antd-mobile';
const TabPane = Tabs.TabPane;

### What is expected?
TabPane woks.

### What is actually happening?
 React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `NovelIndex`.

---
I found that there is no tabpane in tab class in @2.0.0-beta4, but in previous version

**Comment by paranoidjk** [comment]
http://beta.mobile.ant.design/docs/react/upgrade-notes-cn#Tabs
