### ISSUE TITLE
The Conflict among Tabs swipeable in react-native and FlatList onRefreshing

### ISSUE THREAD

**Issue by Yangzhedi** [ant-design/ant-design-mobile#1913]
### Version
1.4.1

### Environment
react-native 0.47.2

### Reproduction link
[https://codepen.io/yangzhedi/pen/jGZvbE](https://codepen.io/yangzhedi/pen/jGZvbE)

### Steps to reproduce
将FlatList 放在Tabs 的TabPane 下时候，Tabs的左右滑动和FlatList的下拉刷新有冲突。

### What is expected?
如果不是纯x轴的滑动，不要触发Tabs的左右效果

### What is actually happening?
斜着下滑的时候会影响Flatlist的下拉刷新，下拉刷新会卡到一半

**Comment by silentcloud** [comment]
@Yangzhedi 你可以先用 2.0.0-beta 版本，2.0 Tabs 进行了重构；

1.x 不打算更改了，本身以来的外部库有你说的这个问题

https://github.com/ant-design/ant-design-mobile/pull/1651
