### ISSUE TITLE
custom icon document error

### ISSUE THREAD

**Issue by Cody1988** [ant-design/ant-design-mobile#1914]
### Version
2.0.0-beta.3

### Environment
任意

### Reproduction link
[https://github.com/Cody1988/antd-mobile-icon](https://github.com/Cody1988/antd-mobile-icon)

### Steps to reproduce
此issue主要为[自定义ICon文档错误](http://beta.mobile.ant.design/docs/react/upgrade-notes-cn#1.x-=>-2.0)

### What is expected?
期望能够修改此处文档

### What is actually happening?
目前为错误文档

---
const CustomIcon = ({ type, className = '', size = 'md', ...restProps }) => {
  return (
    <svg
      className={`am-icon am-icon-${type.default.id} am-icon-${size} ${className}`}
      {...restProps}
    >
      <use xlinkHref={`#${type.default.id}`} />
    </svg>
  );
};

<CustomIcon type={require('../assets/activity.svg')} />

**Comment by silentcloud** [comment]
这里是需要区分 svg-sprite-loader 版本，目前文档里写的是 0.3.x 的没问题

你这种写法是 > 0.3 版本的写法，另外你项目里 readme 里 `npm install svg-sprite-loader@0.3.1 -D` 是多余的，因为 roadhog 自己已经依赖里 > 0.3 版本的
