### ISSUE TITLE
too slow with react-native-navigation （With more than 10 list items）

### ISSUE THREAD

**Issue by nothingp** [ant-design/ant-design-mobile#1920]
### Version
1.6.6

### Environment
 "react-native": "0.44.3",

### Reproduction link
[https://github.com/nothingp/react-native-nothing](https://github.com/nothingp/react-native-nothing)

### Steps to reproduce
1 登录
2 个人中心
3 基本信息

### What is expected?
快速展现

### What is actually happening?
有重影

**Comment by zhang740** [comment]
`List` 本身不会控制渲染数量，渲染速度取决于你的布局/使用，如果 `ListItem` 复杂、数量多需要优化请使用`ListView`等方式替代。

**Comment by nothingp** [comment]
<ScrollView>
                {
                    status == 'N' || status == 'P' ?
                        <NoticeBar>
                            您的信息已经提交成功，等待审核中。
                        </NoticeBar>:
                        status == 'R'?
                            <NoticeBar>
                                您的信息已被拒绝，请重新完善信息。
                            </NoticeBar>:
                            null
                }

                <Item name="昵称：" text={prc_former_name}/>
                <Item name="性别：" text={sex? sex == 'M'? '男': '女': ''}/>
                <Item name="民族：" text={prc_nationality_desc}/>
                <Item name="生日：" text={dob}/>
                <Item name="籍贯：" text={district}/>
                <Item name="政治面貌：" text={prc_political_status_desc}/>
                <Item name="婚姻状况：" text={marital_status_desc}/>
                <Item name="最高学历：" text={prc_education_desc}/>
                <Item name="专业名称：" text={prc_major}/>
                <Item name="毕业时间：" text={prc_grade_gettime}/>
                <Item name="公司邮箱：" text={comp_email}/>
                <Item name="手机号码：" text={mobile_no}/>
                <Item name="家庭电话：" text={home_no}/>
                <Item name="QQ：" text={prc_qq}/>
                <Item name="个人邮箱：" text={pers_email}/>
                <Item name="办公号码：" text={office_no}/>
            </ScrollView>

item是封装过的，用了flex，就是那么多元素，在安卓机器下就会显示 有重影（this.props.navigator.push弹出界面）
<Flex style={ItemStyles.listItem}>
            <Flex.Item style={ItemStyles.titleWrap}>
                <Text style={ItemStyles.listTitle}>
                    {props.name?props.name:''}
                </Text>
            </Flex.Item>
            <Flex.Item style={ItemStyles.listContent}>
                <Text style={ItemStyles.listText}>
                    {props.text?props.text:''}
                </Text>
            </Flex.Item>
        </Flex>

**Comment by silentcloud** [comment]
@nothingp 测试一下直接渲染，不依赖 react-native-navigation 的情况

这个不应该是 List 有问题，有可能是 react-native-navigation 的问题哈
