### ISSUE TITLE
react native下使用tabs组件有错误提示

### ISSUE THREAD

**Issue by fuxianwei** [ant-design/ant-design-mobile#1921]
### Version
2.0.0-beta.5

### Environment
react-native：0.49.3

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
在react native下使用tabs组件报警告信息
Warning: StaticContainer has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extend React.Component if shouldComponentUpdate is used.

### What is expected?
不要出现这个警告

### What is actually happening?
ExceptionsManager.js:73 Warning: StaticContainer has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extend React.Component if shouldComponentUpdate is used.

**Comment by zhang740** [comment]
`rmc-tabs`手动更新到1.2.5，或者删掉`node_modules`重装一遍

**Comment by szwork2013** [comment]
antd-mobile 2.0.1 里 rmc-tabs 还没有更新到1.2.5

**Comment by zhang740** [comment]
antd-mobile使用的是版本号兼容写法，你安装的时候会安装到1.2.x的最新版本，如果是之前安装过的可以删掉node_modules重新安装。
@szwork2013
