### ISSUE TITLE
How to custom antd-mobile on React Native project

### ISSUE THREAD

**Issue by byk04712** [ant-design/ant-design-mobile#1924]
### What problem does this feature solve?
I want custom the ant-mobile ui components theme for my project

### What does the proposed API look like?
eg: Custom primary color, button height etc...

**Comment by silentcloud** [comment]
@byk04712 https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui

**Comment by amitava82** [comment]
This works fine in dev, how to integrate this with production build process?

**Comment by silentcloud** [comment]
@amitava82 run `node scripts/custom-rn-theme` before build
