### ISSUE TITLE
With regard to Tabs and List use problem

### ISSUE THREAD

**Issue by KingBarbarian** [ant-design/ant-design-mobile#1925]
### Version
2.0.0-beta.5

### Environment
mac os chrome and phone safari 

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
```
<Tabs
          tabs={tabs}
          initialPage={0}
          tabBarPosition="top"
          swipeable={false}
          renderTab={tab => <span>{tab.title}</span>}
        >
          <div style={{ height: `${height - 43.5}px` }}>
            <Machine />
          </div>
          <div style={{ height: `${height - 43.5}px` }}>
            <FillFarmers />
          </div>
          <div style={{ height: `${height - 43.5}px` }}>
            <Rent />
          </div>
          <div style={{ height: `${height - 43.5}px` }}>
            <FarmWork />
          </div>
          <div style={{ height: `${height - 43.5}px` }}>
            <Food />
          </div>
          <div style={{ height: `${height - 43.5}px` }}>
            <Labor />
          </div>
        </Tabs>
```
<Machine />,<FillFarmers />...this is list

expectation：textinput open keyboard page floating localize to this input
but：page jitter ,  position the same , No effect

### What is expected?
textinput open keyboard page floating localize to this input

### What is actually happening?
page jitter ,  position the same , No effect

**Comment by zhang740** [comment]
This question is only about `InputItem` component, this is a browser behavior of `Input`.
[Android] Under UC Browser is no problem, but Chrome is reproduced.
[iOS] UIWebView no problem, but WKWebView is reproduced.

min reproduce example without antd-mobile:
https://bug-of-input-scroll.stackblitz.io
