### ISSUE TITLE
run build error 

### ISSUE THREAD

**Issue by yuzhouisme** [ant-design/ant-design-mobile#1927]
npm start successed.

but when command "npm run build", get an error

---------
ZhoudeMacBook-Air:DoesMobile zhou$ npm run build

> @ build /Users/zhou/Downloads/DoesMobile
> roadhog build

module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zhou/Downloads/DoesMobile/node_modules/extract-text-webpack-plugin/ExtractedModule.js:30:42)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/zhou/Downloads/DoesMobile/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/zhou/.nvm/versions/node/v6.11.3/bin/node" "/Users/zhou/.nvm/versions/node/v6.11.3/bin/npm" "run" "build"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build: `roadhog build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'roadhog build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     roadhog build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhou/Downloads/DoesMobile/npm-debug.log

If I install webpack, will get an error "chunk has runtime"

-------
MY ENV 

npm version
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.11.3',
  openssl: '1.0.2l',
  uv: '1.11.0',
  v8: '5.1.281.107',
  zlib: '1.2.11' }

package.json

{
  "private": true,
  "scripts": {
    "start": "roadhog server",
    "build": "roadhog build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "engines": {
    "install-node": "6.11.1"
  },
  "dependencies": {
    "antd-mobile": "^1.6.11",
    "babel-runtime": "^6.9.2",
    "dva": "^1.2.1",
    "react": "^15.4.0",
    "react-dom": "^15.4.0"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "babel-plugin-dva-hmr": "^0.3.2",
    "babel-plugin-import": "^1.4.0",
    "babel-plugin-transform-runtime": "^6.9.0",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "expect": "^1.20.2",
    "husky": "^0.12.0",
    "postcss-pxtorem": "^3.3.1",
    "redbox-react": "^1.3.2",
    "roadhog": "^0.5.2"
  },
  "standard": {
    "parser": "babel-eslint",
    "globals": [
      "location",
      "localStorage"
    ]
  }
}

**Comment by yuzhouisme** [comment]
npm install webpack --save

&& npm run build

get an error below:

Creating an optimized production build...
/Users/zhou/Downloads/DoesMobile/node_modules/webpack/lib/Chunk.js:53
		throw new Error("Chunk.entry was removed. Use hasRuntime()");
....

**Comment by silentcloud** [comment]
@yuzhouisme 给个 git 地址，或者打包传上来吧
