### ISSUE TITLE
Popover visible为true时点击其他地方进行关闭，会同时触发下一层其他元素的点击事件

### ISSUE THREAD

**Issue by houjiazong** [ant-design/ant-design-mobile#1928]
react: 16.0.0
react-dom: 16.0.0
antd-mobile: 1.6.11
浏览器：Chrome(版本 61.0.3163.100 正式版本 64 位)

问题：Popover visible为true时点击mask进行关闭，会同时触发下一层其他元素的点击事件，每次都可以重新，不管mask是true还是false

**Comment by silentcloud** [comment]
@houjiazong 重复的 issue  哈  https://github.com/ant-design/ant-design-mobile/issues/1909
