### ISSUE TITLE
Typescript在 next.js 环境下使用 antd-mobile 报错has no default export.

### ISSUE THREAD

**Issue by xjl271314** [ant-design/ant-design-mobile#1929]
### Version
2.0.0-beta.5

### Environment
next.js，Typescript,react,dva,antd-mobild,都为最新版本

### Steps to reproduce
正常运行的next.js，Typescript,react环境下 添加antd-mobild ，在 .babelrc里也配置了 ["import", { "style": "css", "libraryName": "antd-mobile" }]，运行环境后 加载任意一组件就报 各模块 has no default export.

### What is expected?
能够在 next.js，Typescript,react正常使用 antd-mobile 组件

### What is actually happening?
正常运行的next.js，Typescript,react环境下 添加antd-mobild ，在 .babelrc里也配置了 ["import", { "style": "css", "libraryName": "antd-mobile" }]，运行环境后 加载任意一组件就报 各模块 has no default export.

---
正常运行的next.js，Typescript,react环境下 添加antd-mobild ，在 .babelrc里也配置了 ["import", { "style": "css", "libraryName": "antd-mobile" }]，运行环境后 加载任意一组件就报 各模块 has no default export.

**Comment by zhang740** [comment]
https://github.com/ant-design/antd-mobile-samples/tree/master/web-ssr

**Comment by xjl271314** [comment]
JS环境三正常，为需要typescript环境下运行

**Comment by zhang740** [comment]
一样是可以的 https://github.com/ant-design/antd-mobile-samples/tree/master/web-ssr-ts

**Comment by zhang740** [comment]
你是怎么配置ts的？
https://github.com/ant-design/antd-mobile-samples/tree/master/web-ssr-ts

**Comment by littlepoolshark** [comment]
why ant-design-mobile just use a little bit of Typescript features(interface),is there any plan to do code refactoring in Typescript way completely?

**Comment by tungh** [comment]
@zhang740 请问您发的这个demo里面scss或者less如何添加进去？我尝试了多次添加进去都不生效。

**Comment by zhang740** [comment]
Because many of the components write by JS before, we will continue to optimize in this regards. @littlepoolshark

**Comment by zhang740** [comment]
@tungh 那个例子主要是为了演示ssr，样式引用部分是写死的，https://github.com/ant-design/antd-mobile-samples/blob/master/web-ssr-ts/pages/_document.tsx
样式添加配合你的打包配置正常搞就好，没有什么特别的，可以参看其他demo

**Comment by tungh** [comment]
@zhang740 方便把这个demo加入scss或者less吗？ 搞不懂，似乎每次都没打包进去。

**Comment by czy0729** [comment]
@xjl271314 请问你的next用的是编译好的antd-mobile 的css 还是真的走编译了，本人也在用next做ssr，在处理antd-mobile的less这块毫无头绪

**Comment by littlepoolshark** [comment]
@zhang740 Well, look much forward to that,Tks!

**Comment by silentcloud** [comment]
@xjl271314 请确定

https://github.com/ant-design/antd-mobile-samples/blob/master/web-ssr-ts/tsconfig.json#L6

这个是否有配置，如果还有问题，请 reopen issue，并提供你的 demo
