### ISSUE TITLE
ImagePicker 在华为p9 plus中没有调用 this.props.onChange

### ISSUE THREAD

**Issue by MyNameDeXian** [ant-design/ant-design-mobile#1932]
### Version
2.0.0-beta.6

### Environment
在华为p9 plus自带浏览器

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/](https://github.com/ant-design/ant-design-mobile/)

### Steps to reproduce
  _this.getOrientation = function (file, callback) {
            var reader = new FileReader();
            reader.onload = function (e) { } //没有调用 reader.onload

### What is expected?
可以兼容 p9 plus

### What is actually happening?
目前不兼容

**Comment by silentcloud** [comment]
@MyNameDeXian 麻烦测试一下其他设备是否有这个问题

**Comment by silentcloud** [comment]
没这个机器，测试了 V9，没问题，如果你这边还有问题，帮忙再进一步定位一下，然后 reopen
