### ISSUE TITLE
Carousel with immutable List map not work

### ISSUE THREAD

**Issue by unordered** [ant-design/ant-design-mobile#1934]
### What problem does this feature solve?
can use immutable List map in Carousel

### What does the proposed API look like?
```
<Carousel>
  {List().map(i => ...)}
</Carousel>
```

**Comment by unordered** [comment]
[re produce demo https://codepen.io/unordered/pen/KXxpMO?editors=0111](https://codepen.io/unordered/pen/KXxpMO?editors=0111)

> The reason for the error may be that the immutable List obsolete the length attribute

**Comment by silentcloud** [comment]
@unordered  官方demo 也是这种场景

https://github.com/ant-design/ant-design-mobile/blob/master/components/carousel/demo/basic.md

**Comment by silentcloud** [comment]
你给的 codepen 的demo 也是ok 的

**Comment by unordered** [comment]
好吧，还是用中文舒坦
说明一下问题：
1. 这里的数据使用Immutable@3.8.2的List，这个版本已经去除了List的length属性
2. 渲染出来后第一个元素正常，自动滚动或者手动滚动到下一个元素后dots指示器会消失，而且后面的元素也会有缺失，控制台有错误输出：
```
Warning: `NaN` is an invalid value for the `left` css style property.

Check the render method of `Carousel`.
```

**Comment by silentcloud** [comment]
那这个问题就不应该是让 antd-mobile 来 fix， Carousel 本身是支持 map children 的

**Comment by pmg1989** [comment]
@silentcloud ,确实有这个bug存在，复现步骤跟上面的描述一致，感觉还是antd-mobile 来fix吧，第三方库只用了immutable呢。
