### ISSUE TITLE
2.1 Roadmap

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1935]
- [ ] ~~动效优化~~
- [ ] 测试用例 #1722

**Comment by warmhug** [comment]
- [ ] 怎么更好的提供“偏业务”非通用的组件？ 比如：支付宝6位密码框、[Filter](https://github.com/ant-design/ant-design-mobile/pull/1918)组件

**Comment by silentcloud** [comment]
- [ ] rc-gestrue 优化， https://github.com/ant-design/ant-design-mobile/issues/1954

**Comment by silentcloud** [comment]
- [ ] typescript 增强
