### ISSUE TITLE
Warning: render(...): Replacing React-rendered children with a new root component

### ISSUE THREAD

**Issue by icodytan** [ant-design/ant-design-mobile#1936]
### Version
2.0.0-beta.6

### Environment
Windows 10, Chrome 61.0.3163.100, react 16.0.0

### Reproduction link
[https://github.com/icodytan/antd-issue](https://github.com/icodytan/antd-issue)

### Steps to reproduce
```bash
git clone https://github.com/icodytan/antd-issue
yarn # or npm install
yarn start # or npm start
```

Click showAlert or showActionSheet

### What is expected?
No error and hide modal

### What is actually happening?
Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.

Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by silentcloud** [comment]
@icodytan I have fixed the error, but animation has not been fixed on dismissing modal.

Per facebook/react#9808, `Modal` is not recommended use with React 16.
