### ISSUE TITLE
can not change the color of ActivityIndicator

### ISSUE THREAD

**Issue by shi1hh** [ant-design/ant-design-mobile#1937]
## Version
2.0.0-beta.6

### Environment
native

### Reproduction link
[http://native](http://native)

### Steps to reproduce
ActivityIndicator toast  color="red"   

### What is expected?
color changed

### What is actually happening?
color still white.

---
when the length of text too long, this ActivityIndicator look unbeautiful

**Comment by silentcloud** [comment]
@shi1hh https://github.com/ant-design/ant-design-mobile/blob/master/components/activity-indicator/index.native.tsx#L34

toast 背景色是黑，白色的图标才会看的比较清楚。这种也是固定设计，所以没支持 toast 类型的自定义颜色

**Comment by shi1hh** [comment]
@silentcloud 一开始我就看了源码，我以为是BUG，因为indicator是有COLOR属性的，作为spiner是可以自定义COLOR的，但是作为toast却不可以，所以我以为是BUG，而且这个东西不影响啊，你可以默认白色，然后再开个接口，这是小CASE，至于设计的话，我也不懂，但我看到很多这种toast的indicator黑色背景，字体固定白色可以理解，但是indicator很多都不是纯白。
