### ISSUE TITLE
render和componentDidUpdate里使用Toast会报错

### ISSUE THREAD

**Issue by shengxinjing** [ant-design/ant-design-mobile#1939]

**Comment by silentcloud** [comment]
@shengxinjing 如果和这个 https://github.com/ant-design/ant-design-mobile/issues/1936 问题类似的话，`rm -rf node_modules && npm install`.

**Comment by troyz** [comment]
@silentcloud The same issue.

You can reproduce it by place below code in the `componentDidMount` function:
``` javascript
Toast.loading('Loading...', 1, () => {
    console.log('Load complete !!!');
});
```

It show errors like below:
×
TypeError: Cannot read property 'add' of null
notice
node_modules/rc-notification/es/Notification.js:138
  135 | var notification = ReactDOM.render(React.createElement(Notification, props), div);
  136 | return {
  137 |   notice: function notice(noticeProps) {
> 138 |     notification.add(noticeProps);
  139 |   },
  140 |   removeNotice: function removeNotice(key) {
  141 |     notification.remove(key);
View compiled

**Comment by silentcloud** [comment]
@troyz Already fixed in https://github.com/ant-design/ant-design-mobile/issues/1980
