### ISSUE TITLE
react-slick  报错 object.assign  undefined not a function

### ISSUE THREAD

**Issue by 214132049** [ant-design/ant-design-mobile#194]
#### 本地环境

- antd-mobile 版本：0.7.8
- 操作系统及其版本：osx 10.11.6
- 浏览器及其版本：chrome 52

#### 你做了什么？
resolve: {
  ...
  extensions: ['', '.web.js', '.js', '.json']
}
按照这种方式解决了 import antd-mobile的问题，但是在安卓版微信中轮播图报错，object.assign  undefined not a function, 通过修改引用的react-slick  --> lib -->  inner-slider.js文件可以正常工作

#### 你期待的结果是：
寻求更好的解决方案

**Comment by liqi07** [comment]
@214132049 这个在安卓的确有兼容问题，ref #87  

目前 0.8.0 已修复，请升级版本使用 😆

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/pull/447

**Comment by 214132049** [comment]
@liqi07  嗯  好的 谢谢
