### ISSUE TITLE
Unable to customize Picker's okText, dismissText and extra

### ISSUE THREAD

**Issue by kappa-gooner** [ant-design/ant-design-mobile#1941]
### Version
2.0.0-rc.2

### Environment
MacOS

### Source link
[https://github.com/ant-design/ant-design-mobile/blob/2.0.0-rc.2/components/picker/AbstractPicker.tsx#L109](https://github.com/ant-design/ant-design-mobile/blob/2.0.0-rc.2/components/picker/AbstractPicker.tsx#L109)

### Steps to reproduce
The current (beta) version of ant mobile doesn't allow you to customize the okText, dismissText and the cancel text. 
The problem is on the following line:
https://github.com/ant-design/ant-design-mobile/blob/2.0.0-rc.2/components/picker/AbstractPicker.tsx#L109

```
const { okText, dismissText, extra } = _locale;
```

The preference must be given to the value passed down from the prop rather than the one fetched from the locale. 

### What is expected?
The passed down prop values must be used

### What is actually happening?
The locale values are used

**Comment by silentcloud** [comment]
@kappa-gooner https://github.com/ant-design/ant-design-mobile/blob/master/components/locale-provider/demo/basic.md

http://beta.mobile.ant.design/kitchen-sink/components/locale-provider
