### ISSUE TITLE
1.6.11 下SwipeAction无法正常使用

### ISSUE THREAD

**Issue by xiaochanghai** [ant-design/ant-design-mobile#1942]
**Environment(required) | 环境**

antd-mobile version（antd-mobile版本）:antd-mobile 1.6.11
Browser (or mark react-native) and its version（浏览器或react-native版本）:chrome
Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:windows 7
What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

我在ListView的Item中引用了SwipeAction

**What do you expected?（预期的正常效果）**

在向左滑动SwipeAction时，action可以正常出现

**What happen?（发生了何种非正常现象）**

action无法出现

antd-mobile  1.2.0 下是正常的
经过调试 SwipeAction 的onOpen 方法已正常调用
麻烦帮忙看一下，谢谢

**Comment by silentcloud** [comment]
duplicated #1943
