### ISSUE TITLE
官网访问出问题了，什么时候可以修复？

### ISSUE THREAD

**Issue by Silence520** [ant-design/ant-design-mobile#1944]

**Comment by Silence520** [comment]
https://mobile.ant.design/

**Comment by silentcloud** [comment]
@Silence520 我这边没问题哈，看一下 chrome network 是哪个资源访问不到？

这个能打开？`https://www.google-analytics.com/analytics.js`

**Comment by justLearner** [comment]
I also had this kind of problem，so，how to resolve is?

**Comment by silentcloud** [comment]
@justLearner @Silence520  try again

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design/issues/7895

**Comment by paranoidjk** [comment]
just trace and discuss at https://github.com/ant-design/ant-design/issues/7895, no need to keep this open.

**Comment by silentcloud** [comment]
打不开的先使用国内镜像 http://antd-mobile.gitee.io
