### ISSUE TITLE
[2.0.0-rc.2]DatePicker set maxDate and minDate ,  year col not show  in  iphone7, ios11, weixin browser

### ISSUE THREAD

**Issue by zhongxia245** [ant-design/ant-design-mobile#1946]
### Version
2.0.0-rc.2

### Environment
iphone7 , ios11, weixin browser

### Reproduction link
[https://codepen.io/zhongxia245/pen/qPQpmg?editors=0010](https://codepen.io/zhongxia245/pen/qPQpmg?editors=0010)

### Steps to reproduce
1. use iphone browser open this  https://codepen.io/zhongxia245/pen/qPQpmg?editors=0010

### What is expected?
show year cols

### What is actually happening?
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fkl4u14y8uj30ku112abm.jpg)

**Comment by zhongxia245** [comment]
![](https://ws4.sinaimg.cn/large/006tKfTcly1fkl8cjnjbpj30m4062wf5.jpg)

**Comment by warmhug** [comment]
`new Date('2100-1-1')` 在 Safari 上是 Invalid Date
