### ISSUE TITLE
Modal.alert can not close when browser go back

### ISSUE THREAD

**Issue by Joslolz** [ant-design/ant-design-mobile#1948]
### Version
1.7.0

### Environment
IOS.10 Safari 

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN)

### Steps to reproduce
import {  Modal } from 'antd-mobile'
const alert = Modal.alert
alert(....)

click Safari native go back 

### What is expected?
alert close

### What is actually happening?
alert not close

---
maybe the same issue occurs on other modal

**Comment by silentcloud** [comment]
You can listen back event and use https://mobile.ant.design/components/modal-cn/#Modal.alert(title,-message,-actions?)
