### ISSUE TITLE
各组件 touch feedback 状态修复

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#195]
UC 内核浏览器下、不少组件有点击反馈细节问题，逐一测试修复
- 组件内嵌类似 button （包括自定义）的点击效果
- icon 按钮点击效果
- 列表项条目

**Comment by warmhug** [comment]
使用 js 修复方法、参考 https://github.com/ant-design/ant-design-mobile/blob/master/components/_util/touchableFeedback.tsx

**Comment by yiminghe** [comment]
@warmhug mousedown/up 处理下，pc demo 没法看

**Comment by warmhug** [comment]
需要做 tap feedback 的地方：

- Modal 组件里的 x 按钮、内嵌的一系列 确定/取消/按钮列表 等按钮 @silentcloud （是否可改成直接内嵌 button 组件）
- Picker / DatePicker 弹出层上的 确定/取消 按钮  @warmhug
- Stepper 按钮 uc 上无 tap 效果
- Icon 组件里的各个 icon 建议带有 tap 效果

**Comment by silentcloud** [comment]
外面包了一层组件之后，tsc 过不了

**Comment by warmhug** [comment]
Stepper 还没修复 @foriacus

**Comment by silentcloud** [comment]
Stepper 直接用的 rc，没办法处理

```
  return (
      <RcInputNumber
        ref="inputNumber"
        prefixCls={prefixCls}
        className={stepperClass}
        {...restProps}
      />
  );
```
