### ISSUE TITLE
can not change the height of DefaultTabBar

### ISSUE THREAD

**Issue by shi1hh** [ant-design/ant-design-mobile#1950]
### Version
2.0.0-rc.2

### Environment
native

### Reproduction link
[http://native](http://native)

### Steps to reproduce
the code
```

    return <View
      style={{
        ...Styles.TabBar.container,
        backgroundColor: tabBarBackgroundColor,
      }}
      onLayout={this.onContainerLayout}
    >

```
in [https://github.com/react-component/m-tabs/blob/master/src/DefaultTabBar.native.tsx](https://github.com/react-component/m-tabs/blob/master/src/DefaultTabBar.native.tsx)

Styles change to lowercase then can override the styles of DefaultTabBar

### What is expected?
change height

### What is actually happening?
not change

**Comment by zhang740** [comment]
upgrade to rmc-tabs@1.2.7.
