### ISSUE TITLE
swipeAction鼠标或者触控拖动的时候 , transitionDuration应该为0ms~

### ISSUE THREAD

**Issue by deepkolos** [ant-design/ant-design-mobile#1952]
### Version
2.0.0-rc.2

### Environment
win10 1703 chrome 61 stable 

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/swipe-action?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/swipe-action?lang=zh-CN)

### Steps to reproduce
向左swipe

### What is expected?
swipe的时候transitionDuration 应该为0ms

### What is actually happening?
因为不为0ms导致有迟钝感

**Comment by zhang740** [comment]
我这测试不存在你说的情况，在滑动的时候是会禁用transition的，如果设置动画就会卡顿。如果你出现了迟钝感请提供下具体的环境和例子？

**Comment by deepkolos** [comment]
我录制了一个gif

![bug2](https://user-images.githubusercontent.com/12824616/31698202-df38561a-b3ee-11e7-8ffb-3a2b1dfbb4e0.gif)

**Comment by deepkolos** [comment]
在演示页面的时候时候, 使用鼠标拖动

![bug3](https://user-images.githubusercontent.com/12824616/31698282-4274379e-b3ef-11e7-9617-70a9e5ef33ea.gif)

**Comment by zhang740** [comment]
@deepkolos 2.0的官网目前是 http://beta.mobile.ant.design，本周2.0正式版上线后会更新 http://mobile.ant.design
