### ISSUE TITLE
model通过层叠上下文来实现最顶层的显示是否会好一些?

### ISSUE THREAD

**Issue by deepkolos** [ant-design/ant-design-mobile#1953]
### Version
2.0.0-rc.2

### Environment
win10 1703 chrome 61 stable 

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN)

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
无

现在通过是通过相对于根层叠上下文+z-index: 999 来控制在顶层显示, 如果在#react-content 里元素的层叠使用z-index: 1000 , position: relative则不会覆盖.

![2017-10-18_100414](https://user-images.githubusercontent.com/12824616/31697960-29ffa4f2-b3ed-11e7-89e2-99e32ad9917b.png)

如果通过层叠上下文就可以在#react-content 里面使用任何值的z-index (虽然现在也足够了

不知道这样会不会好一些, 还有想问问, 通过overflow: hidden 来实现防止页面滚动, 是否会带来一些性能问题? 在移动端的时候 

[在移动端微信内置浏览器 , overflow 的 hidden/scroll 的 switch 花销好大啊, 要 170+ms , 手机 CPU 骁龙 801](https://www.v2ex.com/t/382323)

**Comment by silentcloud** [comment]
前面你说的那些没太能理解，最好能来个 PR 和应用场景。

性能那个，目前多数 UI 库都是这么干的，理论上不会有太大影响

**Comment by deepkolos** [comment]
@silentcloud overflow的问题, 因为接近根节点, 会触发很大面积的重绘, 重排哦, 如果页面复杂的话, 感觉会有问题, 所以觉得使用js来阻止滚动好一些~

**Comment by silentcloud** [comment]
有好的想法或者改善，来个 PR，issue 我先关掉来

**Comment by deepkolos** [comment]
@silentcloud 好~
