### ISSUE TITLE
哈~ 还是找到bug了, swipeAction滑动锁逻辑有缺陷~~

### ISSUE THREAD

**Issue by deepkolos** [ant-design/ant-design-mobile#1954]
### Version
2.0.0-rc.2

### Environment
win10 1703 chrome 61 stable 

### Reproduction link
[http://beta.mobile.ant.design/kitchen-sink/components/swipe-action?lang=zh-CN](http://beta.mobile.ant.design/kitchen-sink/components/swipe-action?lang=zh-CN)

### Steps to reproduce
see in gif
在chrome dev 设置 #react-content 的height: 200vh;

### What is expected?
无论有/没滚动条的时候, 都需要判断开始滑动的方向
如果是垂直滑动, 就冒泡到父节点, 不触发横向滚动逻辑, 
如果是横向滚动就阻止冒泡, 触发横向滚动逻辑~

### What is actually happening?
see in gif

![bug4](https://user-images.githubusercontent.com/12824616/31699785-88f37696-b3f7-11e7-90e8-ae097cc40db8.gif)

**Comment by paranoidjk** [comment]
try `direction` api https://github.com/react-component/gesture#common-props

**Comment by deepkolos** [comment]
还有一个不知道算不算问题~
就是, 直接横向滚动的时候, 在cell内滚动流程, 但是当把手指挪到cell变卡顿~

![bug5](https://user-images.githubusercontent.com/12824616/31707175-0bc759ea-b41e-11e7-81ab-72121bc26794.gif)

这是我自己认为比较合理的行为~ (其实我发现好多开源的组件框架都没把swipe行为定义好~ 下面是自己修改后的~ 基于vue

![show0](https://user-images.githubusercontent.com/12824616/31707341-a1a14eb2-b41e-11e7-9034-a1eabfa19a42.gif)

个人觉得, swipelock的事件定义是指, 只要一开始符合了条件, 事件将会锁定在该组件, 就是不会往上冒泡, 不符合就, 继续冒泡咯~

看了一下, 所提供链接的swipelock的逻辑, 怎么会放在touchend来处理的捏? 感觉奇怪啊, 不是应该放在touchmove的开始的时候做判断的么? 

这是我的swipelock的逻辑, 一个vue的derctive来的, 仅仅做swipe的事情~
https://github.com/deepkolos/we-vue/blob/master/src/custom/event/swipe.js

**Comment by paranoidjk** [comment]
@zhang740 看下？评估下，如果不是致命的问题，改动又比较麻烦的，可以放到 2.x 的后面迭代去慢慢优化

**Comment by zhang740** [comment]
预计 2.1 处理吧，m-tabs也有个相关问题。

**Comment by zhang740** [comment]
https://github.com/react-component/m-tabs/issues/7

**Comment by silentcloud** [comment]
@paranoidjk @zhang740 这个问题不大，不影响主功能，放在 2.1 着重搞

**Comment by justLearner** [comment]
![image](https://user-images.githubusercontent.com/22292102/31815682-f8b4ef7c-b5bf-11e7-8e64-f1070aedded2.png)
为什么不能把自提换成icon

**Comment by FrankFei** [comment]
这个问题在1.x时我提过，中间有段时间修复好了，现在我升级到2.0.2后，在ListView中使用SwipeAction时，会触发上下滑动，用户体验不太好！

**Comment by silentcloud** [comment]
@justLearner https://github.com/react-component/swipeout/blob/master/src/Swipeout.tsx#L213

**Comment by warmhug** [comment]
@deepkolos 请问你邮箱多少？有换工作想法吗？欢迎邮箱私聊 :-D

**Comment by deepkolos** [comment]
@warmhug 😄 我的邮箱 deepkolos@qq.com 现在大三~

**Comment by likezero** [comment]
@quentinyang  ref #1974  和这个很像

**Comment by quentinyang** [comment]
已经修复，主要推动依赖的rc-gesture和swipeout两个组件修复：
1. 修复touchmove的时候会触发scroll
2. 修复touchmove离开目标时会出现卡顿的现象
3. 修复两只手指同时移动同一个目标会出现按钮无法复原的问题

**Comment by warmhug** [comment]
@quentinyang 搞好了就尽快验证更新哈

**Comment by quentinyang** [comment]
已验证修复

**Comment by quentinyang** [comment]
rc-gesture的滚动问题引起其他问题。重新打开issue。
