### ISSUE TITLE
inputItem clear时存在不可预期的结果

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#1955]
### Version
1.6.11

### Environment
口碑掌柜 iOS

### What is actually happening?
不可预期，存在input的内容长度超过0了  clear Icon不出现

**Comment by pingan1927** [comment]
系统级bug

**Comment by silentcloud** [comment]
@pingan1927 那结论？关掉？

**Comment by pingan1927** [comment]
![image](https://user-images.githubusercontent.com/347649/31702437-9ee576c6-b39c-11e7-976d-2aba9f0a7371.png)

**Comment by silentcloud** [comment]
来个 PR 吧，刚好你也熟这个组件

**Comment by pingan1927** [comment]
已提 review之！ @silentcloud
