### ISSUE TITLE
Add new prop to NoticeBar to configure closing button style

### ISSUE THREAD

**Issue by meiyu1989** [ant-design/ant-design-mobile#1959]
### What problem does this feature solve?
In some business scenes, I need show some text like "不再提醒" to close the notice bar. but now i got an cross only. I'm planning to implement it. Is this necessary? thx

### What does the proposed API look like?
Add new prop to NoticeBar, maybe like this, 
<NoticeBar closedButton={ <Em>不再提醒</Em> } />

**Comment by silentcloud** [comment]
这个 2.0 支持
