### ISSUE TITLE
Grid   activeStyle 在网页版中不生效

### ISSUE THREAD

**Issue by wudashuaige** [ant-design/ant-design-mobile#1961]
<Grid
          activeStyle={false}
          square={false}
          columnNum={2}
          /* onClick={this.haedrsubmind} */
          data={datatwo}
          renderItem={dataItem => (
            <div className={styles.named}>
              <img src={dataItem.icon} className={styles.wen} alt="icon" />
            </div>
          )}
        />
我想如何去掉它的点击反馈效果，但是就是不生效

**Comment by zhang740** [comment]
具体版本以及demo？测试没有问题。 @wudashuaige

**Comment by wudashuaige** [comment]
antd-mobile: ^2.0.0-rc.2   我想把他的点击效果去掉但是不生效

**Comment by wudashuaige** [comment]
我自定义的样式，但是点击效果不好看，我想去掉，但是去不掉

**Comment by zhang740** [comment]
组件版本问题吧？看下m-feedback版本是否最新？或者是否有升级提示，禁用特性在两天前的1.0.2添加的。
@wudashuaige

**Comment by silentcloud** [comment]
这个删除 node_modules  yarn.lock 重新装一下，确认一下 m-feedback 是否最新
