### ISSUE TITLE
React 16 warning during test running

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1962]
`npm run test:web -- -u`

```bash
      Warning: Received `true` for non-boolean attribute `unselectable`. If this is expected, cast the value to a string.
```

**Comment by silentcloud** [comment]
![image](https://user-images.githubusercontent.com/1698185/31770548-0d2537a0-b49e-11e7-86b5-adf24497998a.png)

**Comment by silentcloud** [comment]
https://github.com/react-component/input-number/blob/master/src/index.js#L221

**Comment by silentcloud** [comment]
@zhang740 rmc-input-number 发个版本，版本号我已经改了，直接发
