### ISSUE TITLE
Ant Design Mobile 2.0 is here!

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#1965]
- English Version.
- 中文版请往下滑。

- - - 

![image | center](https://gw.alipayobjects.com/zos/rmsportal/LqiRkXlyzJElPBnENMzK.png)

Eight month ago we released `Ant Design Mobile 1.0`. After 47 times of 1.x version upgrade and one month of [2.0 beta](https://github.com/ant-design/ant-design-mobile/issues/1823), we are happy to announce that a **`More Lightweight`**, **`Easier-to-use`**, **`Better performance`**  `Ant Design Mobile 2.0` is officially released !

### Getting Started

`antd-mobile@2.0` is  out of the box, see example below:

```js
// install deps
npm install antd-mobile --save

// import component and style
import { Button } from 'antd-mobile';
import 'antd-mobile/dist/antd-mobile.css';

// here you go
ReactDOM.render(<Button loading>Start</Button>, mountNode);
```

### Mainly Feature

* **Framework upgrade**: Fully support for [react 15/16](https://github.com/facebook/react) and [preact](https://github.com/developit/preact). You may noticed that our [offcial mobile demo site](https://mobile.ant.design/kitchen-sink/) is running upon preact !
 
* **Huge reducing of Bundle Size**：We refactored the whole components dependencies to reduce bundle size, optimize performance. The minified bundle size is reduced by at least 35%：
 
  | antd-mobile.min.js version | Parsed size (min) | Gzip size |
  | :--- | :--- | :--- |
  | 1.7.1 | 560.1 kb | 144 kb |
  | 2.0.0 | 362.1 kb | 92.6 kb |

 
* **More Stable**: All low-level dependencies of components are maintained by our team, so we can gurantee to fix problems ASAP, and keep to optimize code.
 
* **More Easy to use**: 1.x “HD-Screen-resolution” and “SVG Icon” change to optional, no need of plenty configuration.
 
* **More Components**: Added `Calendar` ，`DatePickerView`， `PullToRefresh`, refactored `ListView`, `Tabs`. Right now we inclued **`47`**  web components and **`40`** native components.
* **i18n**：All of our compnents and doc supported English right now.

More deatil info: [antd-mobile@2.0 chaneglog](http://mobile.ant.design/changelog-cn#2.0.0)

### Relative Links

* Official website： [https://mobile.ant.design/](https://mobile.ant.design/)
* V2.0 upgarde note：[http://mobile.ant.design/docs/react/upgrade-notes-cn#1.x-=>-2.0](http://mobile.ant.design/docs/react/upgrade-notes-cn#1.x-=%3E-2.0)
* 2.0 changelog： [http://mobile.ant.design/changelog-cn#2.0.0](http://mobile.ant.design/changelog-cn#2.0.0)
* issue: [http://new-issue.ant.design/?repo=antd-mobile](http://new-issue.ant.design/?repo=antd-mobile)
* github: [https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)
* 2.0 beta log: [https://github.com/ant-design/ant-design-mobile/issues/1823](https://github.com/ant-design/ant-design-mobile/issues/1823)

Thanks for all contributors and bug reporters.

---

![image | center](https://gw.alipayobjects.com/zos/rmsportal/LqiRkXlyzJElPBnENMzK.png)

八个多月前我们发布了 Ant Design Mobile 1.0 ，一个多月前我们发布了 [2.0 beta](https://github.com/ant-design/ant-design-mobile/issues/1823)。历经 47 个 1.x 正式版的迭代，现在 **`更轻量`**，**`更易用`**，**`性能更好`** 的 2.0 正式版如期而至…

### 开始使用

2.0 无需任何高级配置，`npm install` 后直接可以引入使用：

```js
// install deps
npm install antd-mobile --save

// import component and style 
import { Button } from 'antd-mobile';
import 'antd-mobile/dist/antd-mobile.css';

// here you go
ReactDOM.render(<Button loading>Start</Button>, mountNode);
```

### 主要变化

- **兼容好**：完全支持 React（15/16） / preact，同时解决了许多与 preact 相关的细节问题。
    > 也就是说，antd-mobile@2.0 既可以配合 react 使用，也可以无缝迁移到 preact，用户选择底层框架更灵活。   
- **体积小**：各组件体积、性能、细节功能等全面优化，压缩版包体积减少了 **35+%** 
 
  | antd-mobile.min.js version | Parsed size (min) | Gzip size |
  | :--- | :--- | :--- |
  | 1.7.1 | 560.1 kb | 144 kb |
  | 2.0.0 | 362.1 kb | 92.6 kb |
  
- **更稳定**：所有底层依赖全部自己维护管控、保障了稳定性，**C 端业务** 完全可以放心使用。
- **更便捷**："高清方案" / "SVG Icon" 从“内置必选”改为“外置可选”。
- **更丰富**：新增了 Calendar ，DatePickerView， PullToRefresh 组件，ListView、Tabs 底层进行了重写；截止目前 web 组件 **`47`** 个，react-native 组件 **`40`** 个。
- **国际化**：内置中文文案的组件已全部支持国际化, 官方站点也已完全国际化。

完整变更请看 [antd-mobile@2.0 chaneglog](http://mobile.ant.design/changelog-cn#2.0.0)

### 相关链接

* 官网： [https://mobile.ant.design/](https://mobile.ant.design/)
* 2.0 升级指南：[http://mobile.ant.design/docs/react/upgrade-notes-cn#1.x-=>-2.0](http://mobile.ant.design/docs/react/upgrade-notes-cn#1.x-=>-2.0)
* 2.0 更新日志： [http://mobile.ant.design/changelog-cn#2.0.0](http://mobile.ant.design/changelog-cn#2.0.0)
* issue: [http://new-issue.ant.design/?repo=antd-mobile](http://new-issue.ant.design/?repo=antd-mobile)
* github: [https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)
* 2.0 beta 发布日志: [https://github.com/ant-design/ant-design-mobile/issues/1823](https://github.com/ant-design/ant-design-mobile/issues/1823)

感谢所有 contributors 和反馈问题的用户们，任何疑问和反馈请 [github issue](https://github.com/ant-design/ant-design-mobile/issues) 或钉钉联系我们：

![image | center](https://gw.alipayobjects.com/zos/rmsportal/xXvUCYPqlcuWTMLzMhEe.png "")

**Comment by afc163** [comment]
Need English doc.

**Comment by silentcloud** [comment]
English will be later

**Comment by ssssssssssss** [comment]
Congrats, please update Expo version too. :)

**Comment by silentcloud** [comment]
@ssssssssssss Expo app has been updated

**Comment by paranoidjk** [comment]
Added English Release Log.

**Comment by stefensuhat** [comment]
official site https://mobile.ant.design/ is error I think. On my console.log it says "React is undefined"

THanks
