### ISSUE TITLE
After setting the swipeable property to true, the page should not slide left or right when sliding up and down

### ISSUE THREAD

**Issue by movingStars** [ant-design/ant-design-mobile#1966]
### What problem does this feature solve?
When a tab page is very long, you need to scroll up and down to see more information, but when the page scrolls up and down the page will be slightly rolling around, the user experience is very bad, you want to scroll up and down do not trigger left and right scrolling. I tried to clear the default event when the page scrolls, but it does not work.

### What does the proposed API look like?
After setting the swipeable property to true, the page should not slide left or right when sliding up and down

**Comment by zhang740** [comment]
ref #1954

**Comment by movingStars** [comment]
@zhang740 ok, thank you so much
