### ISSUE TITLE
Picker选项值不能正确显示， 并且在选择中会报错

### ISSUE THREAD

**Issue by zjhiphop** [ant-design/ant-design-mobile#1967]
### Version
2.0.0

### Environment
Android & IOS，RN版本： 0.47.0

### Reproduction link
[http://codepen.io/paranoidjk/pen/LWpaKe](http://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
1. 使用一下代码在真机测试：
```
<Picker
                        value={this.state.coldInTemp}
                        data={coldInTempRange}
                        onOk={v => {
                            this.setState({
                                coldInTemp: v[0]
                            }, this.onChange)
                        }}
                        onDismiss={() => console.log('dismiss')}
                    >
                        <Item arrow="horizontal">制冷回水温度设定值</Item>
                    </Picker>
```

### What is expected?
在选择了某个选项之后，应该正确显示选择后的值
When i select one option, should show the option value correctly

### What is actually happening?
在选择某个选项时， 会报错“Can not assign to read only property 'xx' of String 'xx'”, 选择了选项之后， 不能显示选择后的值， 依然显示“请选择”
When i selecting one option,  there is a error happened: "Can not assign to read only property 'xx' of String 'xx'", After selected, the option value not shown, still shows 'Please select'

---
能不能在发布时候多在真机上测试一下？ 我今天升级之后，发现了两个bug， 麻烦能够提高一下测试质量， 非常感谢！
Can you help to test more in real device? I already found two bugs after update to version 2.0.0-rc3.

**Comment by silentcloud** [comment]
官方 demo 没问题，检查你自己的使用方式，或者提供可复现的代码

**Comment by silentcloud** [comment]
![error](https://user-images.githubusercontent.com/1698185/31929460-c8fd9e74-b861-11e7-8160-613e9a26fdb6.gif)

**Comment by silentcloud** [comment]
单独见了对应的例子，没能重现哈，检查你自己的代码，附测试例子：

```js
import { View, AppRegistry } from 'react-native';
import { Picker, List } from 'antd-mobile';
import React from 'react';

const seasons = [
  [
    {
      label: '2013',
      value: '2013',
    },
    {
      label: '2014',
      value: '2014',
    },
  ],
  [
    {
      label: '春',
      value: '春',
    },
    {
      label: '夏',
      value: '夏',
    },
  ],
];

class PickerExample extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: ['2013', '春'],
    };
  }
  onChange = (value) => {
    this.setState({ value });
  }
  render() {
    return (<View style={{ marginTop: 30 }}>
      <List>
        <Picker
          data={seasons}
          title="选择季节"
          cascade={false}
          extra="请选择(可选)"
          value={this.state.sValue}
          onChange={v => this.setState({ sValue: v })}
          onOk={v => this.setState({ sValue: v })}
        >
          <List.Item arrow="horizontal">Multiple</List.Item>
        </Picker>
      </List>
    </View>);
  }
}
```

```json
"dependencies": {
		"antd-mobile": "2.0.0",
		"react": "16.0.0-alpha.12",
		"react-native": "0.47.2"
	},
```

**Comment by szwork2013** [comment]
附上图片：
![picker2](https://user-images.githubusercontent.com/8146801/32320201-fd9957ce-bf8a-11e7-937b-bec3f7576831.jpeg)
![picker1](https://user-images.githubusercontent.com/8146801/32320202-fdd4befe-bf8a-11e7-838d-9eb184a7be57.jpeg)

**Comment by silentcloud** [comment]
@szwork2013 你这个 web 版本单独提个 issue

**Comment by witalobenicio** [comment]
@szwork2013 how did you solve that issue?

**Comment by ningzhenyi** [comment]
@zjhiphop  你是value赋值时出错了 ，value值, 格式是[value1], 对应数据源的相应级层value

**Comment by mushroomlb** [comment]
要显示必须设置value为state中的变量
