### ISSUE TITLE
字体的处理

### ISSUE THREAD

**Issue by shineliuhzz** [ant-design/ant-design-mobile#1968]
阅读了HD方案，对于字体也是用rem的方案来处理的么。用rem处理后的字体大小会比较奇怪。

**Comment by warmhug** [comment]
字体可以不用，在你需要用到 rem 的地方就用、不需要就不用。
可以参考：https://www.zhihu.com/question/25308946/answer/32240185

**Comment by shineliuhzz** [comment]
pxtorem会自动把所有的px都转换成rem，而且引入js高清文件以后，所有的组件也默认小了一倍。

**Comment by warmhug** [comment]
你不是从 1.x 升级到 2.0 吗？这个要看升级文档的，里边写了这么处理了。
