### ISSUE TITLE
contentSize is no longer defined within the `onChange` event.

### ISSUE THREAD

**Issue by silvestreh** [ant-design/ant-design-mobile#1970]
### Version
2.0.0

### Environment
React Native 0.49

### Reproduction link
[https://codepen.io/anon/pen/zEbeoj](https://codepen.io/anon/pen/zEbeoj)

### Steps to reproduce
There's not much to it. Just by using `TextareaItem`'s `autoHeight` prop will make the app crash because of this line of code:

https://github.com/ant-design/ant-design-mobile/blob/master/components/textarea-item/index.native.tsx#L58

`contentSize` is no longer in `event.nativeEvent` if you're using React Native `TextInput`'s `onChange` method. Instead, you should deal with `contentSize` changes in the new `onContentSizeChange` method as described in [React Native's documentation](http://facebook.github.io/react-native/docs/textinput.html#oncontentsizechange).

### What is expected?
The text area component should adjust its height.

### What is actually happening?
The app is crashing because `contentSize` is no longer defined in `event.nativeEvent`.

**Comment by silentcloud** [comment]
https://github.com/facebook/react-native/issues/11692

**Comment by silvestreh** [comment]
@silentcloud care to elaborate? I don't know why the issue is being closed, the demo app crashes when I enter text on a `TextareaItem`

**Comment by silentcloud** [comment]
@silvestreh  fixed in this commit: https://github.com/ant-design/ant-design-mobile/commit/a23235a57da94d5d7864e487959c472b9cf1bfe6, and will be released  later
