### ISSUE TITLE
希望 Grid 组件的 square 属性能够支持 React Native

### ISSUE THREAD

**Issue by someok** [ant-design/ant-design-mobile#1971]
### What problem does this feature solve?
当前的 Grid 在 React Native 下固定了高度（整个屏幕宽度的 1/4），调用方无法做任何处理，所以希望能够像 Web 那也支持正方形的功能。

### What does the proposed API look like?
类似 Grid 的 Web 版即可。

**Comment by lxlneo** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1919
2.1.0会修改的

**Comment by silentcloud** [comment]
@someok @lxlneo 这个不用等到 2.1.0， 本周的 2.0.3 将会添加这个功能, itemStyle 属性

**Comment by silentcloud** [comment]
closed for  https://github.com/ant-design/ant-design-mobile/pull/2046
