### ISSUE TITLE
grid示例中的Carousel没有swipeLock的设定 , 还有点击时候的按压感觉不应该在不判断方向的时候就触发~

### ISSUE THREAD

**Issue by deepkolos** [ant-design/ant-design-mobile#1974]
### Version
2.0.0

### Environment
win10 1703 chrome 62 stable 

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/grid?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/grid?lang=zh-CN)

### Steps to reproduce
看gif~

### What is expected?
左右滑动操作Carousel的时候不会触发scroll , 上下scroll的时候不会触发Carousel

同时就是是否触发按压效果需要判断是否是滑动的~
这个行为可以参考`:active`属性, 浏览器的原生也是都这一层判断, 不过在移动端`dom`有寻址和`click`不同的问题, 希望实现的时候可以避免~

### What is actually happening?
都触发了

![bug8](https://user-images.githubusercontent.com/12824616/31857941-af5a5128-b71d-11e7-9e69-5ccf9ef6d7dd.gif)

**Comment by deepkolos** [comment]
还有steps的问题, 一样都swipeLock的问题~ 就补贴图了, 都是小问题~~

**Comment by paranoidjk** [comment]
来个 PR？

**Comment by deepkolos** [comment]
@paranoidjk 不会react😂 前三个星期才开始学的vue, 现在在给一个vue的组件库做PR, 也是与swipeLock有关. 其实是antd-mobile 来拜师的~ 顺便看看有没有自己遇过的bug, 结果发现有~😂

**Comment by silentcloud** [comment]
grid 这个锁的话，要在 rmc-feedback 加相关一些代码，最后感觉和 rc-touchable 应该错不了多少，我再考虑要不要把  rc-touchable 换回来 @paranoidjk @warmhug

**Comment by warmhug** [comment]
能否在 _util 写代码 来解决这个问题。还是不要换回来好。

**Comment by doxiaodong** [comment]
@likezero
