### ISSUE TITLE
还发现在modal对话框的时候, 关闭事件是可以多次触发的, 行为上应该是仅仅允许关闭一次的~ 

### ISSUE THREAD

**Issue by deepkolos** [ant-design/ant-design-mobile#1975]
### Version
2.0.0

### Environment
win10 1703 chrome 62 stable 

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN)

### Steps to reproduce
看gif~

### What is expected?
同一个modal, 在活动的生命周期里, 只能执行一次关闭事件, 确认事件也一样~

### What is actually happening?
可以多次触发

今天我在WEUI也发现有这个bug~
https://github.com/Tencent/weui/issues/678

虽然很少用户会多次点击, 一个关闭~ 除非是十分焦急的时候~ 还是有可能的~ 

先看图~

![bug10](https://user-images.githubusercontent.com/12824616/31858034-5325f1e8-b720-11e7-919b-c1b17ad6a834.gif)

我其他测试了, 除了model有一些例子, 因为出现toast, 挡住了所以行为正确了, 其他都有问题, 虽然是小问题, 影响不大, 但是感觉大厂嘛~ 组件行为还是需要和原生靠近一些滴~~看两个大厂谁修得快~

**Comment by warmhug** [comment]
在 真机 上也有这个问题吗？

**Comment by silentcloud** [comment]
这玩意只在 android 下出现

**Comment by guiyujie** [comment]
ant-mobile Model.prompt按钮只能点一次?
![image](https://user-images.githubusercontent.com/7655349/33821540-11fe48fa-de8f-11e7-83c1-2659949564bf.png)

如果要继续操作怎么办?

**Comment by warmhug** [comment]
@silentcloud  这个锁，确实加的不对了。。直接导致了功能问题。 @zhang740 跟进下

**Comment by deepkolos** [comment]
触发关闭之后, 关闭动画未结束之前, popup会拦截输入事件, popup属于不可交互状态

所以可以选择在开始`关闭动画`的时候上锁, 来实现
