### ISSUE TITLE
在safari上Modal.alert("title","content")弹窗无法关闭

### ISSUE THREAD

**Issue by qqt2018** [ant-design/ant-design-mobile#1976]
### Version
2.0.0

### Environment
safari 浏览器

### Reproduction link
[https://mobile.ant.design/index-cn](https://mobile.ant.design/index-cn)

### Steps to reproduce
5五

### What is expected?
弹窗关闭

### What is actually happening?
弹窗无法关闭

---
import {Modal} from &quot;antd-mobile&quot;;

class Demo extends React.Component{
    render(){
        return &lt;div onClick={this.showAlert}&gt;test&lt;/div&gt;
    }
    showAlert(){
        Modal.alert(&quot;title&quot;, &quot;content&quot;);
    }
}

ReactDOM.render(
    &lt;Demo/&gt;,
    document.getElementById(&#x27;root&#x27;));

**Comment by silentcloud** [comment]
![error](https://user-images.githubusercontent.com/1698185/31869521-35f13008-b76e-11e7-9f05-ad3faf06a706.gif)

Mac safari， iOS safari 未重现

**Comment by qqt2018** [comment]
这个只在手机上复现，测试了火狐，safari 都无法回调，官网的demo在ios上可以正常使用，不确定官网的demo是否也是2.0.0版本的代码。自己使用2.0.0版本的antd-mobile写的demo，事件不会回调。之前用的2.0.0-rc1的版本是可以正常关闭弹窗。

**Comment by qqt2018** [comment]
![image](https://user-images.githubusercontent.com/30019416/31871556-d231b0f8-b77a-11e7-9d3c-73526597c14b.png)

**Comment by silentcloud** [comment]
我发的截图是 mac safari 的，确定一下你本地版本是不是正式版 2.0.0，2.0.0-rc.4 好像有一个版本有这个问题

**Comment by qqt2018** [comment]
![image](https://user-images.githubusercontent.com/30019416/31872064-69732818-b77e-11e7-89ee-3d379d21e5ee.png)
反复安装卸载了几次，版本没有问题，是用npm安装的。建议直接写个demo在手机上测试下。

**Comment by qqt2018** [comment]
测试环境是 IOS 10.3.1

**Comment by silentcloud** [comment]
我这边没有 10.3.1 的设备，iOS 11 safari 和 iOS 8.4 safari 测试都正常

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1982#issuecomment-338563168

**Comment by zuoge85** [comment]
@silentcloud 我觉得

onClose={this.onClose} 这行有问题，首先 Model 里面footer 里面的按钮 都会触发onClose

然后在AlertContainer 内实际上又触发了一次onClose
AlertContainer 内准备实现异步关闭，但是实际上。

在model 里面已经提前关闭了对话框。所以我认为应该
去掉 AlertContainer  内 onClose={this.onClose} 这行

**Comment by zuoge85** [comment]
@silentcloud 我说的是rn 下面 异步关闭不起作用的问题。哈哈。。

**Comment by silentcloud** [comment]
@zuoge85 哦，我以为你说都 web ， 我等会瞅瞅

**Comment by qqt2018** [comment]
用的react版本是16.0.0，不知道跟这有没有关系，测了2.0.0.rc1-rc4。 rc1，2可以关闭，rc3，4就不行了。
![image](https://user-images.githubusercontent.com/30019416/31876928-1abd5c36-b79a-11e7-8b50-3813f5dcbe14.png)

**Comment by silentcloud** [comment]
@qqt2018 好，我等会单独 init 一个例子看看

**Comment by silentcloud** [comment]
@qqt2018 `npm ls rmc-dialog` 看一下版本，应该是你本地的 rmc-dialog 版本不是最新版 (1.0.5)

**Comment by qqt2018** [comment]
什么时候会发新版本呢？

**Comment by silentcloud** [comment]
下午就发一个，这个问题影响可用性 @qqt2018

**Comment by flftfqwxf** [comment]
@silentcloud 新版本发布了么，遇到同样的问题，现在用的版本是2.1.8,依然有此问题，在ios的部分低版本下依然没法关闭，目前只能写一个modal

**Comment by warmhug** [comment]
The issue is old. Lock and close for #2486
