### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#1977]
![](https://gw.alipayobjects.com/zos/rmsportal/UHLnBnoZMHeGpnGotzzn.png)

序号有问题。

- [ ] https://mobile.ant.design/docs/react/use-with-create-react-app-cn
- [ ] https://mobile.ant.design/docs/react/customize-theme-cn

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/commit/0e92aa7b42b6c8ab04eee1b897e0de462f276bc9#diff-36e71054f00d3eb2d7db53632c1d25e7

https://github.com/ant-design/ant-design-mobile/commit/28c2251898a1eabf0c4b54a602b0ee6be76e6208#diff-36e71054f00d3eb2d7db53632c1d25e7

这里缩进一下序号就好了，但是站点渲染的时候有问题

第二个也是同样的问题，貌似是 bisheng 在解析渲染的时候问题？
