### ISSUE TITLE
被Popover包起来的元素，在this.setState 之后，内容不会被更新

### ISSUE THREAD

**Issue by qqt2018** [ant-design/ant-design-mobile#1978]
### Version
2.0.0

### Environment
任何环境

### Reproduction link
[  http://new-issue.ant.design?repo=ant-design-mobile](  http://new-issue.ant.design?repo=ant-design-mobile)

### Steps to reproduce
请看下面demo

### What is expected?
第一个按钮文本改变

### What is actually happening?
文本不变

**Comment by qqt2018** [comment]
![image](https://user-images.githubusercontent.com/30019416/31872005-0956e488-b77e-11e7-9163-c844c994b307.png)

**Comment by warmhug** [comment]
@silentcloud  这个是个问题， 1.x 没问题，查看下 rmc-tooltip 的改动是否正确。

**Comment by silentcloud** [comment]
@warmhug 正在看

**Comment by silentcloud** [comment]
@qqt2018 重装一下依赖，在 rmc-trigger 里修了

**Comment by tonypig93** [comment]
我这边使用preact，在热更新之后，被Popover包裹的组件就不能正常更新了
