### ISSUE TITLE
use `ActivityIndicator` in the `Tabs`

### ISSUE THREAD

**Issue by troyz** [ant-design/ant-design-mobile#1979]
### Version
2.0.0

### Environment
"react": "^16.0.0",     "react-dom": "^16.0.0",     "antd-mobile": "^2.0.0",

### Reproduction link
[https://codepen.io/TroyZ/pen/zEXQyL?editors=0010](https://codepen.io/TroyZ/pen/zEXQyL?editors=0010)

### Steps to reproduce
The `Tabs` have three `Tab`, each `Tab` have a `ActivityIndicator`, the `ActivityIndicator` display in the first `Tab` but not in the other tabs.

### What is expected?
Each `Tab` show it's own `ActivityIndicator`

### What is actually happening?
The `ActivityIndicator` display in the first `Tab` but not in the other tabs.

**Comment by zhang740** [comment]
This problem about `position: fixed` style, you can add `transform: translateZ(0)` to your Tab Content.
Like: https://codepen.io/anon/pen/VMNJop?editors=0011
@troyz

**Comment by troyz** [comment]
@zhang740 It works fine! Thanks!
