### ISSUE TITLE
use `Toast` api in `componentDidMount`

### ISSUE THREAD

**Issue by troyz** [ant-design/ant-design-mobile#1980]
### Version
2.0.0

### Environment
"react": "^16.0.0",     "react-dom": "^16.0.0",     "antd-mobile": "^2.0.0",

### Reproduction link
[https://codepen.io/TroyZ/pen/boJyJg?&editors=001](https://codepen.io/TroyZ/pen/boJyJg?&editors=001)

### Steps to reproduce
Just use `Toast` api in the `componentDidMount` function

### What is expected?
Display the toast correctly.

### What is actually happening?
Couldn't display the toast in `componentDidMount`, only displayed when click a button, etc.

**Comment by silentcloud** [comment]
https://github.com/react-component/notification/issues/21

**Comment by sachin9891** [comment]
Can anybody please tell me how to fix this issue , I am still facing problem with this issue

**Comment by paranoidjk** [comment]
@sachin9891  Please check your antd-mobile version, this problem has been fixed.

If you still have problems, please file a new issue with a reproducible demo.
