### ISSUE TITLE
Modal.alert 点击按钮不关闭对话框

### ISSUE THREAD

**Issue by zuoge85** [ant-design/ant-design-mobile#1982]
Modal.alert 点击任何按钮都会关闭对话框

我在点击的时候返回{then:()=>{}}，依然会关闭对话框

我认为应该有选项禁止这个行为

**Comment by zuoge85** [comment]
关闭吧，我看最新2.0 的代码和1.7.1都能实现不关闭兑换了

**Comment by vJane** [comment]
请问是怎么实现的 @zuoge85
