### ISSUE TITLE
calendar选择区间不能跳过disable的范围?

### ISSUE THREAD

**Issue by deepkolos** [ant-design/ant-design-mobile#1983]
### Version
2.0.0

### Environment
win10 1703 chrome 62 stable 

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/calendar?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/calendar?lang=zh-CN)

### Steps to reproduce
选十月,七点 到十一月,为终点

### What is expected?
跳过disable的那些天

### What is actually happening?
没有跳过, 无法选择

![bug10](https://user-images.githubusercontent.com/12824616/31875429-b0f96cba-b800-11e7-8b55-8308b0f5bd28.gif)

**Comment by zhang740** [comment]
因为返回结果只是给选择区间的起止时间，所以目前如果区间内包含disable的将不能选择，如果选择，会通过`onSelectHasDisableDate`事件给出。
@deepkolos

**Comment by deepkolos** [comment]
@zhang740 ok~
