### ISSUE TITLE
Ant - mobile 1.7 upgrade to version 2.0, when the switch to mobile browsing style small to almost invisible, I don't know why?

### ISSUE THREAD

**Issue by Ruanyang2015** [ant-design/ant-design-mobile#1985]
**这是新增的配置**
`const {injectBabelPlugin} = require('react-app-rewired');
module.exports = function override(config, env) {
    config = injectBabelPlugin(['import', {libraryName: 'antd-mobile', style: "css"}], config);
    return config;
};`
![image](https://user-images.githubusercontent.com/13889247/31893727-e2d0b9e8-b7d1-11e7-9b84-27ecb89077ca.png)

**Comment by warmhug** [comment]
看升级文档了吗？

**Comment by silentcloud** [comment]
@Ruanyang2015  

see https://mobile.ant.design/docs/react/upgrade-notes-cn#高清方案

https://mobile.ant.design/docs/react/introduce-cn#快速上手

**Comment by Ruanyang2015** [comment]
好了,还是这个方案解决了我的问题https://mobile.ant.design/docs/react/introduce-cn#快速上手
