### ISSUE TITLE
官方文档打不开

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-mobile#1986]
### Version
2.0.0

### Environment
win10 QQ浏览器最新版

### Reproduction link
[https://mobile.ant.design/](https://mobile.ant.design/)

### Steps to reproduce
访问https://mobile.ant.design/

### What is expected?
查看api文档

### What is actually happening?
网页无法访问

**Comment by l745230** [comment]
好像是网络问题，用4G能访问到。

**Comment by silentcloud** [comment]
@l745230 可以先尝试使用国内镜像 http://antd-mobile.gitee.io
