### ISSUE TITLE
RadioItem can not be checked in List?onChange() is invalid？

### ISSUE THREAD

**Issue by helloyhy** [ant-design/ant-design-mobile#1989]
### Version
2.0.0

### Environment
react 15.6.1 Google Chrome

### Reproduction link
[https://mobile.ant.design/components/radio-cn/](https://mobile.ant.design/components/radio-cn/)

### Steps to reproduce
onChange = (number) => {
        this.setState({
            value:number
        });
    };
const { value } = this.state;
const data = [
            { number: 0, label: 'doctor' },
            { number: 1, label: 'bachelor' },
        ];
<List renderHeader={() => 'RadioItem demo'}>
                    {data.map(i => (
                        <RadioItem key={i.number} checked={value === i.number} onChange={() => this.onChange(i.number)}>
                            {i.label}
                        </RadioItem>
                    ))}
</List>

### What is expected?
1,The first option is shown by default
2.To change Radio, you can choose second options

### What is actually happening?
1.Cannot default checked
2.onChange() invalid

---
1.remove<List>   can default checked
2. onClick() instead of onChange()    it will be normal

**Comment by zhang740** [comment]
provider a demo please, you can use codpen like this: https://codepen.io/anon/pen/oGRRdP?editors=0010

**Comment by silentcloud** [comment]
@helloyhy Same code and env， https://codepen.io/silentcloud/pen/ZXdjer， cannot repro, close and feel free to reopen if you still have any problems
