### ISSUE TITLE
ant mobile 2.0 使用了config-overrides.js之后 webpack.config.dev.js中的配置全部失效了, css module 等配置也用不了

### ISSUE THREAD

**Issue by Ruanyang2015** [ant-design/ant-design-mobile#1990]
ant mobile 2.0 使用了config-overrides.js之后 webpack.config.dev.js中的配置全部失效了, css module 等配置也用不了,就算我把webpack.config.dev.js里面的东西全部删除程序也能跑,那么我要做 webpack 配置怎么做在那里做?这些你们文档上都没写啊!

**Comment by silentcloud** [comment]
@Ruanyang2015 create-react-app 没有强制你使用哪种方式，只是推荐了用 react-app-rewired，如果你也打算用 react-app-rewired 的话，就需要你自己去看一下 react-app-rewired 的文档哈，比如 css-modules：

https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/examples/css-modules.md

**Comment by Ruanyang2015** [comment]
**问题1加了 css module 肯定对 ant mobile 样式有影响,之前这么做的**
`exclude: /node_modules|antd-mobile\.css/,`
你发的链接我全部都看了,好像没有提到这个问题,估计这个只有你们知道怎么写!
**问题2好像如果不用  react-app-rewired方案配置 webpack 的话, 组件样式就变得特别小**
这个问题好像是跟这个@hd: '2px'有关,可是文档的解决方案不是很详细

**Comment by silentcloud** [comment]
@Ruanyang2015 第一个问题，我稍后补充在这里 https://github.com/ant-design/antd-mobile-samples/tree/master/create-react-app，第二个问题看一下文档 https://mobile.ant.design/docs/react/upgrade-notes-cn#高清方案（1.x => 2.0 升级）
https://mobile.ant.design/docs/react/introduce-cn#Web-使用方式

**Comment by qinyang1980** [comment]
(create react app + typescript + antd) without eject and without using Babel.

https://github.com/qinyang1980/create-react-antd-app.git

antd-mobile is same
