### ISSUE TITLE
InputItem display text use Formatter & Parser

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1992]
## Problem

Right now `InputItem` `type` will have impact on the value format, not just the display text format, eg: `type="phone"` will got something like `"123 1234 5678"`. It may cause extra work when users want to post data to server etc.

### A

Just do a transform with display text, onChange always give  a rawValue `(rawValue: string) => {}`

#### B
Add a `formatter & parse` to do all custom display feature.
eg: antd `InputNumber`: `formatter & parse` https://ant.design/components/input-number-cn/#API

**Comment by silentcloud** [comment]
`A` may be better for no break changes.

**Comment by paranoidjk** [comment]
A still may  consider as a break change. `

Only if we make `(value: string, rawValue: string) => {}` , which may consider no break change, but i think it's no use, the users still need to know that they should get the second params.

Break change may leave to `antd-mobile@3`. This problem is not very emergency.

**Comment by silentcloud** [comment]
![image](https://user-images.githubusercontent.com/1698185/32434002-7ec6c2e0-c2a2-11e7-8b0e-be6f9ead4865.png)

**Comment by fly1688** [comment]
InputItem中的disabled和editable都不起作用，输入框还是可以操作

**Comment by terranc** [comment]
B
