### ISSUE TITLE
tabs not show by using react-native

### ISSUE THREAD

**Issue by jackple** [ant-design/ant-design-mobile#1995]
### Version
2.0.0

### Environment
react-native 0.49

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
import { Tabs } from 'antd-mobile'

// some of my code
```
<Tabs
            tabs={tabs} initialPage={1}
            onChange={(tab, index) => { console.log(index, tab) }}
            renderTab={tab => <Text>{tab.title}-{tab.sub}</Text>}
            renderTabBar={(props) => <Tabs.DefaultTabBar {...props} />}
          >
              <View><Text>1</Text></View>
              <View><Text>2</Text></View>
              <View><Text>3</Text></View>
          </Tabs>

const tabs = [
  { title: 'First Tab', sub: '1' },
  { title: 'Second Tab', sub: '2' },
  { title: 'Third Tab', sub: '3' },
]
```

### What is expected?
Tabs show

### What is actually happening?
nothing

**Comment by jackple** [comment]
I known why. We must set height to the container!!! I suggest to make it clear in doc

**Comment by zhang740** [comment]
not must，https://github.com/ant-design/ant-design-mobile/blob/master/components/tabs/demo/basic.native.tsx
