### ISSUE TITLE
[2.0]How to customize theme when used with create-react-app

### ISSUE THREAD

**Issue by blooddrunk** [ant-design/ant-design-mobile#1997]
### What problem does this feature solve?
I'm following the instructions in this section of [2.0 docs](https://mobile.ant.design/docs/react/use-with-create-react-app-cn) to use `antd-mobile` with `create-react-app`. But I can't figure out how theme customization will work with `react-app-rewired`. The [doc](https://mobile.ant.design/docs/react/customize-theme-cn) doesn't seem to cover this. 

### What does the proposed API look like?
Any suggestion?

**Comment by silentcloud** [comment]
I will add this in https://github.com/ant-design/antd-mobile-samples/tree/master/create-react-app later @blooddrunk

**Comment by blooddrunk** [comment]
Thanks. That'll be of great help

**Comment by max8hine** [comment]
How to edit the theme in AntD Mobile?

I tried that the 'modifyVars' method does not work in Mobile version.

**Comment by silentcloud** [comment]
@max8hine see https://mobile.ant.design/docs/react/customize-theme

**Comment by max8hine** [comment]
@silentcloud thank you for the reply. 
I think I didn't describe my question clearly, sorry about that. 

My issue is how to change the variables in `default.less` with the *create-react-app* project.
In the [customize-theme](https://mobile.ant.design/docs/react/customize-theme) link, only taught how to do it with webpack.
In the [antd-mobile-samples](https://github.com/ant-design/antd-mobile-samples/tree/master/create-react-app) link, only taught how to load less to *create-react-app*.

Thank you.

**Comment by silentcloud** [comment]
@max8hine If you use `create-react-app` with `react-app-rewired`, you can see https://github.com/ant-design/antd-mobile-samples/blob/master/create-react-app/config-overrides.js#L46, find the theme variables which you want to changes in `default.less`, then add them in `modifyVars` and change the value

**Comment by max8hine** [comment]
@silentcloud  Thanks a million, I did not check the code in that project, that's my fault =)

**Comment by sidharth016** [comment]
react-app-rewired not working with react-scripts 2.1.2
The readme steps for antd with create-reat-app is failing
