### ISSUE TITLE
ImagePicker在小米手机适配的问题

### ISSUE THREAD

**Issue by LeeeKevin** [ant-design/ant-design-mobile#1998]
在苹果手机和华为手机上，组件选择图片时，只能一张一张进行选择，但在小米手机上面可以选择多张，如何才能让组件在小米手机上也只能选择一张？

**Comment by silentcloud** [comment]
测试在小米4上只能选择一张，如果确实有这个问题那是操作系统底层，处理不了。

代码中 input type file 无 multiple
