### ISSUE TITLE
Picker 和 DatePicker 采用RN官方

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#20]
Android有自己的交互，现在的方式都是 iOS 的，后期 native UI 升级也比较方便

@warmhug

**Comment by warmhug** [comment]
picker 是用的 rn 官方，DatePicker 是用 Picker 拼成的，没用 DatePickerIOS

**Comment by yiminghe** [comment]
ios 没问题， android 可以考虑封装原生的， api 一致

**Comment by warmhug** [comment]
先 hold

**Comment by OUZICHENG** [comment]
不明真相的群众想问下，ant-design-mobile下的组件是只能做移动WEB的UI，还是也可以直接在RN中使用

**Comment by warmhug** [comment]
@OUZICHENG GitHub 仓库介绍

**Comment by OUZICHENG** [comment]
@warmhug Support web and native usages based on React Native.
群众看到了，谢谢
