### ISSUE TITLE
antd-mobile 引入之后样式出不来

### ISSUE THREAD

**Issue by lifengsbotlp** [ant-design/ant-design-mobile#2000]
![qq 20171025192141](https://user-images.githubusercontent.com/29885219/31996124-c90803ec-b9b9-11e7-839d-c49cecd540a5.png)
![Uploading QQ截图20171025192024.png…]()
![Uploading QQ截图20171025192038.png…]()
请求各位大牛的求助

**Comment by warmhug** [comment]
按 issue 模板，写出具体信息！！

**Comment by silentcloud** [comment]
closed for no response
