### ISSUE TITLE
Having trouble with antd-mobile 2.0 Picker and Expo v22

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design-mobile#2001]
### Version
2.0.0

### Environment
expo v22, iphone 7 

### Reproduction link
[https://github.com/acomito/antd-20-expo-22](https://github.com/acomito/antd-20-expo-22)

### Steps to reproduce
- download expo if you dont have it
- make sure you have the latest versions of expo client, etc
- clone the github repo
- yarn install
- run the app in expo
- send or publish the app and send link to your iphone
- there is only one screen which has a Picker
- try to choose a new value, note how onOk does not fire
- extra can't be set (always goesto default)
- okay/dismiss text not working

### What is expected?
- extra props should work
- okay/dismiss text props should work
- onOk should fire

### What is actually happening?
- extra can't be set (always goes to default text in chinese)
- okay/dismiss text not working
- try to choose a new value, note how onOk does not fire
- LocalProvider not working?

---
I used a pretty similar setup with no problems using expo v20/21 and antd-mobile pre-2.0

In general, for picker, is it better to use (for a single select) onChange or onOk?

**Comment by silentcloud** [comment]
@acomito 
- extra props should work
- okay/dismiss text props should work

 these have been fixed in https://github.com/ant-design/ant-design-mobile/commit/3b1a1317a6a0b730015a02a607da73333481c6e3   , #1984 

- onOk should fire

`onOk` will be fired with `onChange`, you need use `value` & `onChange` props

```js
state = {
   value: 'Art, Crafts, Handmade',
};
<Picker
      data={MAPPED_CATEGORY_OPTIONS}
      cols={1}
      extra="Category"
      title="Category"
      onOk={e => console.log(e)}
      okText="Okay"
      value={this.state.value}
      onChange={v => this.setState({ value: v })}
      onDismiss={e => console.log(e)}
>
    <List.Item arrow="horizontal" />
</Picker>
```

**Comment by acomito** [comment]
Thank you for your help @silentcloud

**Comment by acomito** [comment]
@silentcloud I'm nearly 100% okText is not taking in that reproduction repo.

**Comment by witalobenicio** [comment]
I agree with you @acomito.
I've tested right now with the most recent version, but OkText and dismissText remain chinese.

**Comment by silentcloud** [comment]
@acomito @witalobenicio Try to use version 2.0.1, this has been released 2 days ago.

**Comment by acomito** [comment]
It's perfect thanks @silentcloud

**Comment by witalobenicio** [comment]
@acomito It's working now. Thanks. I'm just not able to show my selected value on the <List.Item>

**Comment by witalobenicio** [comment]
@acomito onOk is not being called yet.

**Comment by silentcloud** [comment]
@witalobenicio `onOk` has been fixed in this commit https://github.com/ant-design/ant-design-mobile/commit/9e3069a305495bdd0e1de36516dc8233c63b9d14, and will be released later
