### ISSUE TITLE
calendar的日期时间中的小时选择顺序有点怪怪~

### ISSUE THREAD

**Issue by deepkolos** [ant-design/ant-design-mobile#2002]
### Version
2.0.0

### Environment
win10 1703 chrome 62 stable 

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/calendar?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/calendar?lang=zh-CN)

### Steps to reproduce
点开 选择日期时间

### What is expected?
时间的小时部分是用 1, 2, 3, .... 12

### What is actually happening?
12, 1, 2, 3 ,4...11 这个顺序有点怪怪的感觉

![bug](https://user-images.githubusercontent.com/12824616/32030696-4f92f802-ba2f-11e7-813e-aa7910287623.png)

![bug0](https://user-images.githubusercontent.com/12824616/32030729-922431e0-ba2f-11e7-93d7-c1dba1a3891e.png)

**Comment by warmhug** [comment]
@deepkolos  你点开一个日期，允许选全天，不就是从 0 点（上午 12 点）开始吗？你的建议是什么？

**Comment by deepkolos** [comment]
@warmhug 对喔
