### ISSUE TITLE
我对比了weui的picker行为, antd-mobile的缺少了一个支持点击选择~~

### ISSUE THREAD

**Issue by deepkolos** [ant-design/ant-design-mobile#2003]
### What problem does this feature solve?
小小的用户交互提升~

### What does the proposed API look like?
默认支持

![feature](https://user-images.githubusercontent.com/12824616/32030868-6351ca8e-ba30-11e7-89d1-900360f60d6f.gif)

**Comment by warmhug** [comment]
Trace https://github.com/react-component/m-picker/issues/39
