### ISSUE TITLE
Stepper onChange 报错：Maximum call stack size exceeded

### ISSUE THREAD

**Issue by singingBoy** [ant-design/ant-design-mobile#2005]
### Version
2.0.0

### Environment
 react-native 0.47

### Reproduction link
[https://mobile.ant.design/components/stepper-cn/](https://mobile.ant.design/components/stepper-cn/)

### Steps to reproduce
<Stepper
                style={{ width: 100,}}
                min={1}
                max={10}
                defaultValue={1}
                onChange={  num=> this.setState({num}) }
              />

### What is expected?
正常效果

### What is actually happening?
错误

---
组件是在 Modal popup中使用的，谢谢

**Comment by silentcloud** [comment]
我查哈 rmc-input-number

**Comment by silentcloud** [comment]
@singingBoy 重新安装 node_modules，确保 rmc-input-number 为 1.0.2 版本即可

**Comment by singingBoy** [comment]
@silentcloud 已经解决，谢谢哥！
