### ISSUE TITLE
2.0 TabBar display issue

### ISSUE THREAD

**Issue by chenkang084** [ant-design/ant-design-mobile#2006]
### Version
2.0.0

### Environment
android7 ,uc v11.7.0 react-mobile2.0

### Reproduction link
[https://github.com/chenkang084/react-jd/tree/mobile](https://github.com/chenkang084/react-jd/tree/mobile)

### Steps to reproduce
if you use my repps , set up belows steps:
npm i
npm run dll
npm start

### What is expected?
i want to the TabBar also stay the bottom of browser ,since i have added  `<div style={{ position: "fixed", height: "100%", width: "100%", top: 0 }}>`

in weichat browser ,it looks good.

### What is actually happening?
pls check the snapshot https://github.com/chenkang084/notes/blob/dev/imgs/blogs/20171026180742.png 

---
if you checkout the issue ,pls kindly contact me via chenkang084@163.com

**Comment by zhang740** [comment]
this is uc's problem, and you can use method of demo to ease.
https://mobile.ant.design/components/tab-bar-cn/

**Comment by chenkang084** [comment]
@zhang740 thx. i have referred to the demo , uc also looks good.
