### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by deific** [ant-design/ant-design-mobile#2007]
### What problem does this feature solve?
解决表单输入和对输入的校验功能

### What does the proposed API look like?
与ant-design桌面版Form组件类似

**Comment by zhang740** [comment]
https://mobile.ant.design/components/input-item-cn/#components-input-item-demo-error
@deific

**Comment by warmhug** [comment]
ref:
https://github.com/ant-design/ant-design-mobile/issues/1680#issuecomment-322137931
https://github.com/ant-design/ant-design-mobile/issues/630#issuecomment-266397728
https://github.com/ant-design/ant-design-mobile/issues/1782#issuecomment-329411063

Keep this issue open for some time.

**Comment by deific** [comment]
@zhang740 @warmhug 多谢，例子和#1680 (comment)，#630 (comment)，#1782 (comment)已查看，大概知道怎么玩了。另外，antd-mobile本身有计划提供轻量级form校验组件？

**Comment by silentcloud** [comment]
@deific 暂时没这个计划，结合使用 rc-form 即可，应该不会重复造轮子

**Comment by paranoidjk** [comment]
@afc163 Ready label 是什么意思？

@warmhug  为什么重新打开？准备做什么
