### ISSUE TITLE
picker如果快速操作会出现小问题~

### ISSUE THREAD

**Issue by deepkolos** [ant-design/ant-design-mobile#2008]
### Version
2.0.0

### Environment
win10 1703 chrome 62 stable 

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/picker?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/picker?lang=zh-CN)

### Steps to reproduce
看gif~
先滑动一栏, 随后快速滑动另一栏

### What is expected?
后面滑动的一栏状态都更新了

### What is actually happening?
后面滑动的一栏状态没有更新

![bug2](https://user-images.githubusercontent.com/12824616/32083327-70009b4c-baf4-11e7-8444-c395d2c45fb3.gif)

不知道动画之前更新列表好还是, 动画结束之后更新好?

**Comment by szwork2013** [comment]
还有这个错误：https://github.com/ant-design/ant-design-mobile/issues/1967

**Comment by zhang740** [comment]
@szwork2013 不是同一个问题不要关联

**Comment by silentcloud** [comment]
动画和代码执行都需要一定时间，联动都更加有联系性，这个问题关掉了

**Comment by deepkolos** [comment]
感觉是策略问题, 联动是在touchend的时候触发关联列表的更新, 还是在transitionend触发更新, 我感觉touchend的时候触发更新效果好一些, 就没有这个bug反馈也来的快些, 如果是联动的更新需要走网络的话, 响应速度也会快些, 因为和动画并行. 

没有, 只是建议, 我选择touchend触发更新~

**Comment by silentcloud** [comment]
https://github.com/react-component/m-picker/blob/master/src/Picker.tsx#L41
并行的话就有问题了，值已经更新了，但是动画的 transform 还没到，肯定是不同步了

**Comment by cpd0101** [comment]
我也遇到了，在页面元素较多的情况下，快速切换DatePicker，有时返回的是上一次选择的日期

**Comment by deepkolos** [comment]
感觉我的event库完成之后, 我提的issue我来尝试修复吧, 顺便学个react
