### ISSUE TITLE
提供页面加载指示，升级bisheng

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#201]
- http://mobile.ant.design/components/modal 请求合并 md 参考 http://ant.design/components/modal/

- 页面切换使用 http://ricostacruz.com/nprogress/ 显示进度

**Comment by liqi07** [comment]
@benjycui 看看nprogress为啥主站没生效呢，kitchen-sink是OK的

**Comment by yiminghe** [comment]
合并 md 还没

**Comment by liqi07** [comment]
@yiminghe 合并md已经改好了，之前是请求所有demo，改造后只请求对应组件的demo

**Comment by yiminghe** [comment]
对比 http://mobile.ant.design/components/modal/  http://ant.design/components/modal/ 还是不一样
