### ISSUE TITLE
onPress event bug on Modal.alert

### ISSUE THREAD

**Issue by Da-Sheng** [ant-design/ant-design-mobile#2012]
### Version
2.0.0

### Environment
ios 移动端浏览器safari qq内部   web

### Reproduction link
[https://mobile.ant.design/components/modal-cn/](https://mobile.ant.design/components/modal-cn/)

### Steps to reproduce
web      alert 中的onPress  ios真机点击无效，没有任何反应  安卓的话可以，但是动画卡顿，pc虚拟机没问题

### What is expected?
执行定义的函数or关闭alert

由于服务器资源缺乏，链接就附上官网的吧，不过官网貌似不是2.0.0吧，试着好像没问题
本人尝试修改了alert.js 
function onWrapTouchStart(e) {
        if (!/iPhone|iPod|iPad/i.test(navigator.userAgent)) {
            return;
        }
        e.preventDefault();
    }
e.preventDefault() 在ios好像不起作用， 直接return的话是可以继续下去的，因为不知道有没有其他的坑，还是希望大佬们看看修复一下，谢谢～

### What is actually happening?
没有任何变化，界面无法继续交互，modal一直存在

**Comment by silentcloud** [comment]
@Da-Sheng https://github.com/ant-design/ant-design-mobile/commit/ef32147ec8765bfe389a42bfcda9fcb39181470f
这里已经修了，等发布

**Comment by warmhug** [comment]
The issue is old. Lock and close for #2486
