### ISSUE TITLE
Tabs与ListView 下拉刷新组合的问题

### ISSUE THREAD

**Issue by jiang263** [ant-design/ant-design-mobile#2013]
tabs切换后ListView下拉第一次不能执行刷新，之后正常，tabs在左右滑动的时候ListView还可以下拉刷新，且左右滑动样式会不对，下一个tabs页面会有部分出现在当前tabs页面

**Comment by warmhug** [comment]
请按照 issue 模板写！

**Comment by zhang740** [comment]
ref #2030
