### ISSUE TITLE
About Drawer and Tabs z-index

### ISSUE THREAD

**Issue by Yangzhedi** [ant-design/ant-design-mobile#2014]
### Version
2.0.1

### Environment
chrome 版本 61.0.3163.100

### Reproduction link
[https://codepen.io/yangzhedi/pen/dZyQRm](https://codepen.io/yangzhedi/pen/dZyQRm)

### Steps to reproduce
tabs的z-index过于高，会覆盖到drawers上面，看起来就会特别奇怪

### What is expected?
tabs的am-tabs-default-bar-top 的z-index是999，    drawer的am-drawer-sidebar的z-index只有2，am-drawer-overlay的z-index只有1

### What is actually happening?
drawers可以覆盖tabs

**Comment by warmhug** [comment]
建议去掉 tabs bar 的 z-index 设置。

**Comment by silentcloud** [comment]
@zhang740 修了？close ？
