### ISSUE TITLE
How can I use Accordion and ListView together?

### ISSUE THREAD

**Issue by PierceTsu** [ant-design/ant-design-mobile#2016]
### What problem does this feature solve?
use "Accordion.Panel" as a row in ListView

### What does the proposed API look like?
```
<Accordion accordion openAnimation={{}} className="my-accordion">
          renderPanel={row}
</Accordion>
```

**Comment by warmhug** [comment]
It's interesting but It looks a bit hard to realize. What is more detailed advice? Detailed API design.

**Comment by silentcloud** [comment]
@PierceTsu I made an example for you. Also you can use `Accordion.Panel` as row of `ListView`

**Comment by PierceTsu** [comment]
That's what I want ,reall appreciate for your help @silentcloud .Thanks for your reminding @ant-design-bot
