### ISSUE TITLE
image-picker 组件选择图片的时候，只能选择图库中的图片，原因是 input中的accept="image/jpg,image/jpeg,image/png,image/gif"，将其改为accept="image/*" 即可，或者这里可以增加一个api。谢谢～

### ISSUE THREAD

**Issue by uames** [ant-design/ant-design-mobile#2017]
### Version
2.0.1

### Environment
ununtu下chrome

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
使用image-picker组件即可重现

### What is expected?
有一个api可以覆盖accept的值

### What is actually happening?
accept值为image/jpg,image/jpeg,image/png,image/gif且无法覆盖

**Comment by paranoidjk** [comment]
请确认用移动设备浏览器测试

**Comment by silentcloud** [comment]
用移动端设备测试，如果移动端测试还是有问题，请reopen issue

**Comment by paranoidjk** [comment]
本周处理 ImagePicker 的一些带确认问题，包括以下

- [ ] ImagePicker这个组件支持一下在选取多张吗

> multiple="multiple"

**Comment by lzj17600278322** [comment]
请问我想 在公众内选择上传图片的时候调出相机和相册应该怎么做呢
