### ISSUE TITLE
mask=true is not work in toast

### ISSUE THREAD

**Issue by shi1hh** [ant-design/ant-design-mobile#2019]
### Version
2.0.1

### Environment
native

### Reproduction link
[http://native](http://native)

### Steps to reproduce
   some code ,Toast.offline("网络请求失败",TOAST_SHOWTIME,()=>{},false);
i try tap the component under the toast mask,not thing happen.
then i try modify the code in this link
```

https://github.com/ant-design/ant-design-mobile/blob/master/components/toast/ToastContainer.native.tsx

```
line 112:
set to    
```

 <View style={[styles.container]} pointerEvents={mask ? undefined : 'none'}>

```
mask=false works fine

### What is expected?
mask=false works fine

### What is actually happening?
mask=false not work

**Comment by silentcloud** [comment]
@shi1hh  
http://facebook.github.io/react-native/docs/view.html#pointerevents

![image](https://user-images.githubusercontent.com/1698185/32432200-44defc6a-c29c-11e7-8f49-97a8d71b9a87.png)
