### ISSUE TITLE
DatePicker无法设置指定minDate，antd-mobile版本1.4.0

### ISSUE THREAD

**Issue by wooxyz** [ant-design/ant-design-mobile#2021]
官网DatePicker提供的API中，通过设置minDate（Date类型），即可设置最小日期选择，但总是报"this.getMinDate(...).year is not a function"错误！
       参考查找资料，引入moment，设置minDate={moment('1955-01-01', 'YYYY-MM-DD')}，即可。是不是应该将API中的Date类型改为moment？

**Comment by warmhug** [comment]
官网DatePicker 是 2.x 版本，注意看 右上角 的版本号！

**Comment by silentcloud** [comment]
@wooxyz 请升级自己的版本
