### ISSUE TITLE
how to define custom style  in React Native

### ISSUE THREAD

**Issue by nothingp** [ant-design/ant-design-mobile#2025]
### Version
2.0.1

### Environment
 "react-native": "0.44.3"

### Reproduction link
[https://github.com/nothingp/react-native-nothing](https://github.com/nothingp/react-native-nothing)

### Steps to reproduce
in 1.x ,   custom-rn-theme.js is for changing the theme， how to do in 2.x?

### What is expected?
modify the theme

### What is actually happening?
modify the theme

**Comment by silentcloud** [comment]
@nothingp 看文档 https://mobile.ant.design/docs/react/introduce-cn#更多增强-(非必须):
