### ISSUE TITLE
is it a bug of tabs?

### ISSUE THREAD

**Issue by shi1hh** [ant-design/ant-design-mobile#2027]
### Version
2.0.1

### Environment
native

### Reproduction link
[http://native](http://native)

### Steps to reproduce
i create a tabs. set the prerenderingSiblingsNumber=0

firstload just load one tab,work fine.

but when i try to goto tab index 6.

all tabs will render, i mean,tab index 0,1,2,3,4,5 rendered.

is it a bug? i check the code in.[https://github.com/react-component/m-tabs/blob/11119180d748b1827d7f54f3728b9c9d0f5b8ca4/src/Tabs.base.tsx](https://github.com/react-component/m-tabs/blob/11119180d748b1827d7f54f3728b9c9d0f5b8ca4/src/Tabs.base.tsx)line 147.

```

 this.setState({
        currentTab: index,
        ...this.getPrerenderRange(prerenderingSiblingsNumber, undefined, index) as any,
        ...newState,
      });

```

i guess the undefied make this thing happen.

### What is expected?
just render the active tab

### What is actually happening?
render all tab

**Comment by shi1hh** [comment]
```

import React, { PureComponent } from 'react';
import {View,Text} from 'react-native'
import {Tabs} from 'antd-mobile'

class Test extends PureComponent {

    constructor(props) {
        super(props);
        this.state={
            tabs:[{title:'一',index:0},{title:'二',index:1},{title:'三',index:2},{title:'四',index:3},{title:'五',index:4}]
        }
    }

    renderContent = (tab, index) => {
        return <Text>{tab.title}</Text>
    };

    render() {
        return (
            <Tabs
                prerenderingSiblingsNumber={0}
                tabs={this.state.tabs}
                initialPage={0}
            >
                {this.renderContent}
            </Tabs>
        )
    }
}
export default Test;

```

![image](http://chuantu.biz/t6/121/1509522585x989668841.gif)

**Comment by zhang740** [comment]
you can use `destroyInactiveTab` together, to achieve the effect.
Because the internal implementation does not cache the contents of tabs, `prerenderingSiblingsNumber` only affects the rendering range.

**Comment by shi1hh** [comment]
@zhang740  i tried.i just wanna load the activeTab, no destroyTab. just lazy load. as you can see.when i try to tap 5, 4,3,2 will load together.use destroyInactiveTab allways load activeTab,this effect i need.but without destroy.i mean..when i tab 5,just load 5,but 1 destroyed

**Comment by zhang740** [comment]
@shi1hh upgrade rmc-tabs to 1.2.15
