### ISSUE TITLE
如何修改ImagePicker 下的input 的name值

### ISSUE THREAD

**Issue by America-first-melon** [ant-design/ant-design-mobile#2028]
### Version
1.7.0

### Environment
chrome  antd -mobile 

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
<input type="file" accept="image/jpg,image/jpeg,image/png,image/gif">

### What is expected?
有没有方法可以加上<input name="????" type="file" accept="image/jpg,image/jpeg,image/png,image/gif">

### What is actually happening?
暂无

**Comment by silentcloud** [comment]
@America-first-melon 

```js
componentDidMount() {
  const input = this.imagePicker.refs.fileSelectorInput;
  input.setAttribute('name', 'xxx');
}
<ImagePicker ref={el => this.imagePicker = el} />
```

**Comment by America-first-melon** [comment]
3q
