### ISSUE TITLE
无法使用antd-mobile 

### ISSUE THREAD

**Issue by squallzhou** [ant-design/ant-design-mobile#203]
- antd-mobile 版本：0.8.0
- 操作系统及其版本：macOS10.11.6
- 浏览器及其版本：chrome 52.0

#### 你做了什么？

引入 antd-mobile 的 Button 

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

Module not found: Error: Cannot resolve module 'antd-mobile' in /Users/zhouxiaobo/Study/reactjs/mobile-demo

#### 可重现的在线演示

1. 安装了antd-mobile
2. 在项目的node_modules下有antd-mobile模块
3. 在index.js里只要有import { Button } from 'antd-mobile'这句话，就无法编译，说找不到antd-mobile模块。

**Comment by silentcloud** [comment]
按照 readme 里配置插件

**Comment by squallzhou** [comment]
我按照readme里的配置去做了，我的weback.config.js ：

module.exports = {
  entry: './index.js',

  output: {
    filename: 'bundle.js',
    publicPath: ''
  },
  module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader?presets[]=es2015&presets[]=react' },
      { test: /\.css$/, loader: "style!css" },
      { test: /\.less/,loader: 'style-loader!css-loader!less-loader'},
      { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192'}
    ]
  },
  resolve: {
    modulesDirectories: ['node_modules', path.join(__dirname, '../node_modules')],
    extensions: ['', '.web.js', '.js', '.json'],
  }
}

但是npm start后，有错误出来，说path没有定义。
![image](https://cloud.githubusercontent.com/assets/11225093/18153082/a6f61928-702d-11e6-8804-8919dd8fe189.png)

这个path是在哪里定义的呢？

**Comment by silentcloud** [comment]
主要是这个

```
webpackConfig.babel.plugins.push(['antd', {
    "style": "css",  // if true, use less
    "libraryName": "antd-mobile",
  }]);
  return webpackConfig;
```

**Comment by squallzhou** [comment]
![image](https://cloud.githubusercontent.com/assets/11225093/18155000/eab40220-703b-11e6-9ec6-2657532df5f3.png)
我搞好了，少了这行const path = require('path'); 看了原来的antd的脚手架项目的代码里，发现了这个

**Comment by AnxioVic** [comment]
我在自己的config里面配置了教程里的方法，但是报modulesDirectories找不到。
