### ISSUE TITLE
looking for a way to achieve [import on demand in one line] using antd-mobile with Microsoft/TypeScript-React-Starter

### ISSUE THREAD

**Issue by wyshmily** [ant-design/ant-design-mobile#2035]
### What problem does this feature solve?
[Microsoft/TypeScript-React-Starter](https://github.com/Microsoft/TypeScript-React-Starter) is a nice tool wiring up **TypeScript with React**. 

It uses **react-scripts-ts instead of react-scripts**：create-react-app my-app --scripts-version=react-scripts-ts

The problem is that **reat-scripts-ts removed the inside babel-loader**, and the way how we inject  babel-plugin-import configrations doesn't work.

Looking for a way to solve this problem. Currently I am importing js and css seperately, witch is quite annoing.

### What does the proposed API look like?
A way to achieve **import on demand** (just like the function of **babel-plugin-import**) with **react-scripts-ts**, which is used by [Microsoft/TypeScript-React-Starter](https://github.com/Microsoft/TypeScript-React-Starter), which **does not have** an inside **babel-loader**

**Comment by silentcloud** [comment]
@wyshmily https://github.com/Microsoft/TypeScript-React-Starter#ejecting

**Comment by qinyang1980** [comment]
(create react app + typescript + antd) without eject and without using Babel.

https://github.com/qinyang1980/create-react-antd-app.git

antd-mobile is same
