### ISSUE TITLE
Icon font doesn't show properly in Grid for react native

### ISSUE THREAD

**Issue by stonecold123** [ant-design/ant-design-mobile#2039]
### Version
2.0.1

### Environment
react-native 0.49.3

### Steps to reproduce
I need to render the grid items with the custom method `renderItem`. However, I found that  the icon component wrapped inside a Text view fails to show the icon font in the grid. I have tried it outside the grid and it works fine. 

````
let data = [{text:'AAA',value:2},{text:'BBB',value:3}]

render(){
     return (<Grid data={data}
          columnNum={3}
          renderItem={this._renderItem}/>)
}

_renderItem = (item)=>{
     return <View>
                   <Text>
                         some text <Icon type={"\ue639"}/>
                   </Text>
               </View>
}
````

### What is expected?
I expect the icon font to be shown probably in the grid item.

### What is actually happening?
Icon font fails to show.

**Comment by silentcloud** [comment]
@stonecold123  I cannot repro. Be sure you have already imported `anticon.ttf` to your xcode project.
![image](https://user-images.githubusercontent.com/1698185/32359693-cfa900e2-c01d-11e7-97b0-9a9c8dca9d02.png)
