### ISSUE TITLE
InputItem type为money类型时, routerRedux.replace跳转报错

### ISSUE THREAD

**Issue by xiaochunyong** [ant-design/ant-design-mobile#2040]
### Version
2.0.1

### Environment
react 16; react-router 4; antd-mobile 2;

### Reproduction link
[https://github.com/xiaochunyong/antd-mobile-issue](https://github.com/xiaochunyong/antd-mobile-issue)

### Steps to reproduce
clone 项目后yarn && yarn start,  点击确定按钮就可以看到报错信息

### What is expected?
无报错信息正常跳转

### What is actually happening?
报错, 无法跳转

**Comment by zhangfengrui** [comment]
what caused this problem, i used react16.0.0 and antd-design-mobile 2.1.2。 I also have this problem, i don't know how to resolve it ,please tell me the reason。

**Comment by zhangfengrui** [comment]
what caused this problem, i used react16.0.0 and antd-design-mobile 2.1.2。 I also have this problem, i don't know how to resolve it ,please tell me the reason。@ant-design-bot

**Comment by zhangfengrui** [comment]
I have resolved this question, the antd-mobile can't support react16.0.0. you should use the version of react below 16.0.0

**Comment by paranoidjk** [comment]
不要锁死依赖，删除 yarn.lock 更新依赖之后，测试正常。

**Comment by vince-fly** [comment]
componentWillUnmount() {
        window.antmCustomKeyboard={};
    }
it is ok,but is not sulotion.
