### ISSUE TITLE
Toast.hide() cant close it when more than one toast are showing.

### ISSUE THREAD

**Issue by huangliop** [ant-design/ant-design-mobile#2044]
### Version
2.0.1

### Environment
window 10 Chrome61\ react 16

### Steps to reproduce
    Toast.loading(1,0)
    Toast.loading(2,0)
    Toast.loading(3,0)
    Toast.hide();

### What is expected?
close all toast

### What is actually happening?
cant closee

---
react 15的时候没有这个问题,抱歉CodePen连接是无效，因为写代码在里面没有运行出来正确的结果

**Comment by silentcloud** [comment]
初步看了一下，rc-notification@3 newInstance 异步，下面的代码在 react@16下 加载的时候  instance notification 可能没返回
```js
componentDidMount() {
  Toast.loading(1,0)
  Toast.loading(2,0)
  Toast.loading(3,0)
  Toast.hide();
}
```
@benjycui 帮忙看一下这种情况怎么处理  https://github.com/ant-design/ant-design-mobile/blob/master/components/toast/index.tsx

**Comment by benjycui** [comment]
这个是已知问题，在 Toast 展示出来之前就把它 hide 了，这个场景没意义吧？

**Comment by silentcloud** [comment]
@huangliop 的理解可能是 toast.loading()  toast.hide 同步，也就是 hide 前 loading 已经显示了

**Comment by benjycui** [comment]
因为 React 16 的渲染也变成了异步的了，所以 ReactDOM.render 不会阻塞，这个行为的修改，我觉得组件是屏蔽不了的，所以还是业务代码调整吧。

**Comment by benjycui** [comment]
if (messageInstance) 那个判断，组件里面可以加另外一个flag，判断是否调用过。

**Comment by silentcloud** [comment]
组件里加另外一个 flag 也解决不里根本问题，这个 issue 关掉里，不存在这样的使用场景
