### ISSUE TITLE
2.0.1 Toast 组件在 ios 11.1 下不显示

### ISSUE THREAD

**Issue by SilenceM** [ant-design/ant-design-mobile#2045]
### Version
2.0.1

### Environment
chrome 61 、ios 11.1 webview

### Reproduction link
[https://mobile.ant.design/components/toast-cn/](https://mobile.ant.design/components/toast-cn/)

### Steps to reproduce
Toast.loading('Loading...', 0, null, false)

### What is expected?
显示 Toast

### What is actually happening?
不显示

---
react version 15.6.1
2.0.0 下的 Toast 没问题 但是 Modal.alert 点击事件无效（这个我看 2.0.1 已经 fix）

**Comment by silentcloud** [comment]
联系了 @SilenceM ，已经解决， 未能重现

**Comment by XIEJUNXIRUOFENG** [comment]
我这边ios的toast也是不显示，请问怎么解决的 @silentcloud
