### ISSUE TITLE
Add Style Property to Proptype of PullToRefresh 

### ISSUE THREAD

**Issue by wyshmily** [ant-design/ant-design-mobile#2047]
### What problem does this feature solve?
The Style Property is missing in the PropsType of PullToRefresh, causing not able to bind a height with it **with TypeScript**.

### What does the proposed API look like?
Add the missing Style Property

**Comment by silentcloud** [comment]
ping @warmhug 直接发版本，pkg version 我已经改了

**Comment by warmhug** [comment]
已发，更新 node_modules 即可
