### ISSUE TITLE
Is possible to set InputItem type to "email"?

### ISSUE THREAD

**Issue by witalobenicio** [ant-design/ant-design-mobile#2050]
It's possible to set type to "email" so the first letter will not be uppercase? I want all letters to be smallcaps.

**Comment by silentcloud** [comment]
@witalobenicio May be you want `autocapitalize="none"` ?

**Comment by witalobenicio** [comment]
Thanks @silentcloud I didn't find that on the docs

**Comment by witalobenicio** [comment]
@silentcloud the autocapitalize="none" didn't work. I'm trying to use it in React Native.

**Comment by silentcloud** [comment]
@witalobenicio Sorry, I missing the Capital charactor,  autocapitalize => `autoCapitalize`
