### ISSUE TITLE
Flex can't work,error:Uncaught ReferenceError: Flex is not defined

### ISSUE THREAD

**Issue by zidoshare** [ant-design/ant-design-mobile#2051]
### Version
2.0.1

### Environment
windows10,chrome 56,react 15.6.1

### Reproduction link
[https://github.com/zidoshare/mobile-runner-test/blob/master/src/app/routes/Home/components/Finder.js](https://github.com/zidoshare/mobile-runner-test/blob/master/src/app/routes/Home/components/Finder.js)

### Steps to reproduce
import { Flex } from 'antd-mobile'

const FlexContainer =  (props)=>(
  <Flex>
    <div/>
    <Flex.Item></Flex.Item>
  </Flex> 
)

### What is expected?
good work

### What is actually happening?
in development env it's good work.but in production env,it's bad

---
use webpack,use babel-plugin-import.other component is good,but only Flex cannot work.

I known the Flex component Has been packaged into the project by webpack-bundle-analyzer

**Comment by silentcloud** [comment]
@zidoshare 

First I define the variable `const Item = Flex.Item`, then replace `<Flex.Item ...` with `<Item ...`, everything is OK. I think your project with some wrong or missing configuration, please check.

![image](https://user-images.githubusercontent.com/1698185/32485370-d1fb5900-c368-11e7-9637-be27dfad7fef.png)

![image](https://user-images.githubusercontent.com/1698185/32485443-0f124268-c369-11e7-97f1-0f40e125c1e0.png)

**Comment by zidoshare** [comment]
This is probably because of webpack ? it cannot find Flex.Item? this is a problem.

**Comment by silentcloud** [comment]
@zidoshare It seems `babel-plugin-transform-class-properties` does not be used in production. I disabled `webpack.optimize.UglifyJsPlugin` and changed `.babelrc` like this:

```json
{
  "plugins": [
    "transform-runtime",
    "transform-object-rest-spread",
    "react-hot-loader/babel",
    "syntax-dynamic-import",
    "transform-class-properties",
    [
      "import",
      {
        "libraryName": "antd-mobile",
        "style": true
      }
    ]
  ],
    "presets": [
      "react"
    ]
}
```

Everything is OK.

**Comment by kwzm** [comment]
@silentcloud Hi,I have the same problem, can you explain in detail why `env.production.presets` causes this problem ?
