### ISSUE TITLE
给Toast加入关闭按钮

### ISSUE THREAD

**Issue by Manweill** [ant-design/ant-design-mobile#2053]
### What problem does this feature solve?
有需要主动关闭Toast的场景

### What does the proposed API look like?
Toast[method](content, duration, onClose, mask,closeable)

**Comment by silentcloud** [comment]
https://mobile.ant.design/components/toast-cn/#API

see `Toast.hide()`

**Comment by Manweill** [comment]
@silentcloud 是让用户点击Toast来关闭

**Comment by silentcloud** [comment]
@Manweill show 的时候 duration 传 0

**Comment by Manweill** [comment]
算了，当我没问

**Comment by LukerSpringtree** [comment]
> 算了，当我没问

哈哈哈 我懂你! 但是好像 他们 这边没有这个支持啊 要不要你搞一下啊
