### ISSUE TITLE
Auto-wrap in List footer dosen't work on Ipad

### ISSUE THREAD

**Issue by letcheng** [ant-design/ant-design-mobile#2057]
### Version
1.6.0

### Environment
Ipad，AlipayClient

### Reproduction link
[https://gw.alipayobjects.com/zos/rmsportal/uJyrvCfcrgvYTegyzSLB.png](https://gw.alipayobjects.com/zos/rmsportal/uJyrvCfcrgvYTegyzSLB.png)

### Steps to reproduce
Set the renderFooter property of List component with english content

### What is expected?
auto-wrap work 

### What is actually happening?
auto-wrap dosen`t work

**Comment by silentcloud** [comment]
@letcheng You can apply custom style by this:

`renderFooter={() => <div style={{ your custom style to wrap }}>....</div> }`
