### ISSUE TITLE
web采用 rem 和页面 scale 缩放方案，具体如何实践？

### ISSUE THREAD

**Issue by fddi** [ant-design/ant-design-mobile#206]
版本0.8.0
使用默认组件样式时尺寸过大，如何整体优化？
0.8.0版本更新：官方网站展示优化，demo 分类优化，web demo 采用 rem 和页面 scale 缩放方案，达到页面高清效果；具体如何实践？

**Comment by minooo** [comment]
更新到0.8之后，确实是过大！
![image](https://cloud.githubusercontent.com/assets/9410091/18152494/d09d873e-7028-11e6-898c-3a3e4ccdf035.png)

**Comment by silentcloud** [comment]
@liqi07 出一个高清方案的最佳实践，直接在 @yiminghe 写的那个脚手架里弄

**Comment by liqi07** [comment]
@fddi @minooo  先参考一下项目demo展示页面http://mobile.ant.design/kitchen-sink/ 的做法： 
 https://github.com/ant-design/ant-design-mobile/blob/8b077743ae31d4e214f7c76864fc4dd044bb97c2/site/mobile/static/template.html#L6

后面脚手架会做相应更新

**Comment by pingan1927** [comment]
https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8%E9%AB%98%E6%B8%85%E6%96%B9%E6%A1%88%E5%AE%9E%E8%B7%B5

**Comment by minooo** [comment]
@liqi07 谢谢,demo我看加了个这个 
`<meta name="viewport" content="width=device-width,user-scalable=no,initialscale=0.3333333333333333,maximum-scale=0.3333333333333333,minimumscale=0.3333333333333333">`
我比葫芦画瓢加了上去，结果，按钮恢复正常大小了，但是我写的样式就,,,,
![image](https://cloud.githubusercontent.com/assets/9410091/18153745/07b80f60-7032-11e6-8b01-b8bf3e54d5ff.png)

**Comment by silentcloud** [comment]
@minooo  一般以 iPhone6 的大小来，即宽度 750

**Comment by afc163** [comment]
需要补充到 changelog 中。

**Comment by Coohack** [comment]
html {
  font-size: 50px;
}

body {
  font-size: .28rem;
}
设置之后ant的字体还是px单位，这个怎么办，

**Comment by Coohack** [comment]
应该把这个链接https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8%E9%AB%98%E6%B8%85%E6%96%B9%E6%A1%88%E5%AE%9E%E8%B7%B5放到changelog里面啊，给我找好久

**Comment by zhaotoday** [comment]
我的临时解决方案，大家可以参考下：
https://github.com/zhaotoday/react-antd-mobile/blob/master/src/template/index.html
```html
<meta name="viewport" content="width=device-width,user-scalable=no,initialscale=0.5,maximum-scale=0.5,minimumscale=0.5">
<link rel="stylesheet" href="http://mobile.ant.design/kitchen-sink.css">
```
默认字体：
https://github.com/zhaotoday/react-antd-mobile/blob/master/src/themes/default/global/reset.scss#L2

**Comment by liqi07** [comment]
#56 项目示例已支持0.8.x

**Comment by qq645381995** [comment]
@zhaotoday  改了 就是不知道什么时候修复这个问题
