### ISSUE TITLE
React Native TabBar not work in Android~

### ISSUE THREAD

**Issue by HelloHxz** [ant-design/ant-design-mobile#2061]
Version
"antd-mobile": "2.0.0-beta.2"

[https://mobile.ant.design/components/tab-bar-cn/
](url)

Example:

Web: 
![1](https://user-images.githubusercontent.com/16659530/32640825-8392a738-c605-11e7-9915-c2fb0350a5ec.png)

Android:
![2](https://user-images.githubusercontent.com/16659530/32640828-8a5f47d8-c605-11e7-91c9-9e0655c44625.png)

`<View style={ { height: 400 }}>
          <TabBar
            unselectedTintColor="#949494"
            tintColor="#33A3F4"
            barTintColor="white"
            hidden={this.state.hidden}
            styles={{
              tabbar:{
                flex:1
              },
              content:{
                height:320
              },
              tabs:{
                80
              }
            }}
          >
`

**Any Demo Code for React Native????**

**Comment by silentcloud** [comment]
@HelloHxz 

https://github.com/ant-design/ant-design-mobile/blob/master/components/tab-bar/demo/basic.native.tsx
