### ISSUE TITLE
stepper 最小值为0 减少按钮无法至灰

### ISSUE THREAD

**Issue by meiyu1989** [ant-design/ant-design-mobile#2062]
### Version
2.0.2

### Environment
mobile

### Reproduction link
[https://codepen.io/NearImba/pen/jaygaw?editors=0010](https://codepen.io/NearImba/pen/jaygaw?editors=0010)

### Steps to reproduce
1、进入
2、跳转数值至最高然后最低

### What is expected?
最小值为了 当前选择为0 减少按钮至灰

### What is actually happening?
最小值为了 当前选择为0 减少按钮没有至灰

---
我已经提了一个pr至
https://github.com/react-component/input-number/pulls
修复此问题，帮忙cr一下 谢谢 ！！

By The Way
Stepper 还要顺便加两个个配置 
1、禁用 输入框手动编辑 只能跳转
2、暴露formtter配置

**Comment by silentcloud** [comment]
@meiyu1989 Thanks. Please send your PR to https://github.com/react-component/m-input-number

**Comment by meiyu1989** [comment]
@silentcloud 
done, thanks

**Comment by silentcloud** [comment]
`rm -rf node_modules yarn.lock`, then `yarn` or `npm i`
