### ISSUE TITLE
为什么 npm start 跑不起来？

### ISSUE THREAD

**Issue by huangyl15** [ant-design/ant-design-mobile#2064]
npm ERR! antd-mobile@2.0.2 start: `cross-env NODE_ENV=development concurrently "DEMO_ENV=react bisheng start -c ./site/bisheng.desktop.config.js" "DEMO_ENV=preact bisheng start -c ./site/bisheng.kitchen.config.js"`
npm ERR! Exit status 1

**Comment by silentcloud** [comment]
什么环境

**Comment by huangyl15** [comment]
window
node 6.11.3
npm 3.10.10
是不是window不能跑啊

**Comment by silentcloud** [comment]
@huangyl15 针对 antd-mobile 的源码仓库我们开发组都是 linux 或者 unix 的环境，没在 win 下面跑过。

**Comment by silentcloud** [comment]
@huangy15  重新 pull 一下，然后试试
