### ISSUE TITLE
为什么 Tabs 组件要用 position: absolute 实现

### ISSUE THREAD

**Issue by hotoo** [ant-design/ant-design-mobile#2067]
### Version
2.0.3

### Environment
iOS 11.0.3, Safari

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
Quick scroll when page enough height, Tabs component's bar will hide.

### What is expected?
Tabs component's bar is show when quick scroll.

### What is actually happening?
Tabs component's bar is hide when quick scroll page.

---
Why use {position: absolute} on `.am-tabs-default-bar-tab`

**Comment by zhang740** [comment]
你确定你用的2.x？2.x没有TabPane，请提供有问题的demo
