### ISSUE TITLE
Property "id" is missing in definition file

### ISSUE THREAD

**Issue by Meeeeow** [ant-design/ant-design-mobile#2068]
### Version
2.0.3

### Environment
TypeScript 2.6.1

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/master/components/button/index.tsx#L7](https://github.com/ant-design/ant-design-mobile/blob/master/components/button/index.tsx#L7)

### Steps to reproduce
1. Setup antd-mobile with typescript 2.6.1
2. import {Button} from 'antd'
3. 
```jsx
<Button id="foo">FooBar</Button>
```

### What is expected?
No errors

### What is actually happening?
Error:(589, 19) TS2339:Property 'id' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<{ children?: ReactNode; }> & Re...'.

---
Not able to reproduce on CodePen.

No "id" property in declare "Button", "ButtonProps", "BasePropsType"

**Comment by silentcloud** [comment]
@Meeeeow Wrap a label( eg: span) for doing this, like:

```js
<span id="foo"><Button /></span>
```
