### ISSUE TITLE
DatePicker 确定和取消都无效

### ISSUE THREAD

**Issue by caohaiyan** [ant-design/ant-design-mobile#2070]
antd-mobile版本  2.0.2 下  DatePicker 在 iphone6s plus 和 chrome 模拟器下打开后不能点击确定不能点击取消

浏览器console 有如下告警：

Picker.js:272 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by caohaiyan** [comment]
export default class CaoHaiYanDatePicker extends React.Component {

    static defaultProps = {
        mode: 'datetime',
        value: null,
        //minDate: null,
        //maxDate: null,
        use12Hours: false,
        minuteStep: 1,
        //locale:,
        disabled: false,
        //onChange:,
        //onValueChange:,
        format: modeFormat.datetime,
    };

    static propTypes = {
        //基础属性
        mode: PropTypes.string,
        value: PropTypes.instanceOf(Date),
        minDate: PropTypes.instanceOf(Date),
        maxDate: PropTypes.instanceOf(Date),
        use12Hours: PropTypes.bool,
        minuteStep: PropTypes.number,
        //locale: PropTypes.object,
        disabled: PropTypes.bool,
        onChange: PropTypes.func,
        onValueChange: PropTypes.func,
        //附加属性
        format:PropTypes.string,
    };

    constructor(props) {
        super(props);
        this.state = {
            value: null,
            tempValue: null,
        };
    }

    handleChange = () => {
        //设置内部动态改变值
        let value= this.state.tempValue;
        const onChange = this.props.onChange;
        if (onChange) {
            onChange(value);
        }
        this.setState({ value:value },()=>{
            this.setState({tempValue:null},()=>{
                ActionSheet.close();
            })
        });
    }

    componentWillReceiveProps(nextProps) {
        //设置外部动态改变值
        this.setState({value: nextProps.value});
    }

    componentDidMount(){
        //设置默认值
        let value=this.props.value;
        if(value){
            this.setState({value});
            const onChange = this.props.onChange;
            if (onChange) {
                onChange(value);
            }
        }
    }

    showDatePickerView = () => {
        ActionSheet.showActionSheetWithOptions({
                options: [],
                title: <Flex>
                            <Flex.Item>
                                <a onClick={() => {
                                        this.setState({tempValue:null},()=>{
                                            ActionSheet.close()
                                        })
                                   }}
                                   style={{color: '#2C9BEC',fontWeight: '500'}}
                                >取消</a>
                            </Flex.Item>
                            <Flex.Item style={{textAlign:'right'}}>
                                <a onClick={this.handleChange}
                                   style={{color: '#2C9BEC',fontWeight: '500'}}
                                >确定</a>
                            </Flex.Item>
                         </Flex>,
                message: <DatePickerView
                            style={{width:'100%',height:'100%',borderTop:'1px #ddd solid'}}
                            mode={this.props.mode}
                            minDate={this.props.minDate}
                            maxDate={this.props.maxDate}
                            use12Hours={this.props.use12Hours}
                            minuteStep={this.props.minuteStep}
                            disabled={this.props.disabled}

                            value={this.state.value}
                            onChange={(value) => {
                                this.setState({tempValue:value});
                            }}
                            onValueChange={(...args) => {
                                const onValueChange=this.props.onValueChange;
                                if(onValueChange){
                                    onValueChange(args)
                                }
                            }}
                        />,
                maskClosable: true,
            });
    }

    render() {
        return (
            <div className='bg-date-picker-box' onClick={() => {
                this.showDatePickerView()
            }}>
                {this.props.children}
            </div>
        );
    }
}
#####################################
用 ant 封装了一个

**Comment by silentcloud** [comment]
Closed for no response.

**Comment by streamBamboo** [comment]
Through the console I found that the "determination" and "Cancel" buttons were not high levels, lower than their parent "am-picker-popup-mask" and "am-picker-popup-wrap", but when the background color was added to them, they did not cover the "confirm" and "Cancel" buttons, which should be a bug
