### ISSUE TITLE
Error no export default 

### ISSUE THREAD

**Issue by xaclincoln** [ant-design/ant-design-mobile#2073]
node version:8.9.0
typescript version: 2.5.3
antd-mobile version: 2.0.3

Use TypeScript-React-Starter to create a starter app , add antd-mobile lib with yarn,  import Button from "antd-mobile/lib/button" in app.tsx, then yarn run start. Error : 'xxxx/react has no default export'.
![image](https://user-images.githubusercontent.com/10794955/32759745-141bd04a-c926-11e7-8e4c-873aa5e5ba8f.png)

tsconfig.json
![image](https://user-images.githubusercontent.com/10794955/32759998-298579a8-c927-11e7-9577-15637135529c.png)

The problem is react typescript definition file has no default export , as in the following picture
![image](https://user-images.githubusercontent.com/10794955/32759629-4a7fdc18-c925-11e7-9765-b74c2bdc6544.png)

A simple way to solve the problem is  replacing all  `import React from 'react';`  with `import  * as React from 'react';`  in antd-mobile lib. 
![image](https://user-images.githubusercontent.com/10794955/32759574-0e1f567c-c925-11e7-9d63-f34d446baecd.png)

**Comment by silentcloud** [comment]
@xaclincoln You can use the `allowSyntheticDefaultImports` compiler option

https://github.com/ant-design/ant-design-mobile/blob/master/tsconfig.json#L8

 https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#support-for-default-import-interop-with-systemjs
