### ISSUE TITLE
SwipeAction可以程序化的打开、关闭左右按钮组么？

### ISSUE THREAD

**Issue by ismjt** [ant-design/ant-design-mobile#2075]
### What problem does this feature solve?
SwipeAction在列表中的左右滑动操作不太灵敏，很容易触发上下滑动，希望可以通过程序化的开启、关闭方式，来辅助开启关闭左右侧按钮组
The component of SwipeAction's swipe left and right actions doesn't work well in list view，It is easy to trigger the slide up and down action, maybe SwipeAction can provide a prop or a function to control the swipe action state.

### What does the proposed API look like?
here is a possible implementation，`<SwipeAction  openBtn=“left”  />`

**Comment by ismjt** [comment]
<SwipeAction openBtn="left" />

**Comment by silentcloud** [comment]
https://github.com/react-component/swipeout/issues/17

> SwipeAction在列表中的左右滑动操作不太灵敏，很容易触发上下滑动

这个后面会进行优化

**Comment by ismjt** [comment]
好的 多谢
