### ISSUE TITLE
ListView配合PullToRefresh组件使用transform: translate3d的方式滑动页面

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-mobile#2076]
### What problem does this feature solve?
在移动端滚动使用transform: translate3d，滑动比浏览器自带的体验更好

### What does the proposed API look like?
在1.7版本中，listview就是使用transform滚动的实现方式,配合将整个页面的touchmove禁止掉，在移动端浏览器（微信浏/QQ）中滚动不会与整个页面下拉互相影响到。
 document.body.addEventListener('touchmove', (ev) => {ev.preventDefault(); });

升级到2.0后，发现listview的滚动发现被替换成浏览器的原生滚动，导致上行代码启用后，listview无法上拉，希望能加个配置项，使用1.7版本的listview滚动。

**Comment by warmhug** [comment]
看 升级文档 里有写，查看 [list-view zscroller](https://github.com/react-component/m-list-view/blob/master/HISTORY.md#zscroller) 这里的详细用法。
