### ISSUE TITLE
undefined is not a function (evaluating 'date.getFullYear()') formatIt  antd-mobile\lib\date-picker\utils.js:19:18 formatFn  \node_modules\antd-mobile\lib\date-picker\index.native.js:87:108  

### ISSUE THREAD

**Issue by ftb2010** [ant-design/ant-design-mobile#2078]
### Version
2.0.3

### Environment
win7/mac os 10.12.6      react-native 0.45.1

### Reproduction link
[https://codepen.io/anon/pen/JOJaRy?&editors=0010](https://codepen.io/anon/pen/JOJaRy?&editors=0010)

### Steps to reproduce
搭建native环境，运行代码

### What is expected?
不报错

### What is actually happening?
报错

---
native环境模拟不了，无法最小化重现

**Comment by silentcloud** [comment]
官方 demo 在你提供的环境下面测试没问题 

https://github.com/ant-design/ant-design-mobile/blob/master/components/date-picker/demo/basic.native.tsx

 测试 demo 见附件：  

[demo.zip](https://github.com/ant-design/ant-design-mobile/files/1470041/demo.zip)

你试试，如果还是有问题，麻烦将你 代码 传上来，然后 reopen issue

**Comment by ftb2010** [comment]
[demo.zip](https://github.com/ant-design/ant-design-mobile/files/1470388/demo.zip)
给你个demo
