### ISSUE TITLE
Feature: steps in horizontal in React Native

### ISSUE THREAD

**Issue by gengjiawen** [ant-design/ant-design-mobile#2081]
### What problem does this feature solve?
common design in steps.

### What does the proposed API look like?
```jsx
<Steps current={1} orientation="horizontal">
            {
              this.state.steps1.map((item, index) => (
                <Step key={index} title={item.title} description={item.description} status={item.status} />
              ))
           }
</Steps>
```
Something like this:
![image](https://user-images.githubusercontent.com/3759816/32818136-81ce6acc-c9fc-11e7-927d-95ce718b71bc.png)

**Comment by gengjiawen** [comment]
I review the api again, find the `direction` api. Sorry for this inconvenience.

**Comment by gengjiawen** [comment]
Just this is not available in react native, why is this ?

**Comment by silentcloud** [comment]
@gengjiawen  Yes, `horizontal ` is not available in react native now.

**Comment by gengjiawen** [comment]
I am working this, but I don't quite familiar with the source, where should I do to change the vertical line to horizontal. Thanks.

**Comment by gengjiawen** [comment]
I find it. It's controlled by css width and height.

**Comment by gengjiawen** [comment]
I start a pr https://github.com/ant-design/ant-design-mobile/pull/2090.
