### ISSUE TITLE
 when use mutile Modal， one close, all the modal will become invisible?

### ISSUE THREAD

**Issue by huyansheng3** [ant-design/ant-design-mobile#2082]
### Version
2.0.3

### Environment
react 16

### Reproduction link
可重现链接： https://codepen.io/huyansheng3/pen/POKRLQ

### Steps to reproduce
popup 中点击按钮弹出 alert，点击 alert，不仅 alert消失了，连 popup 也消失了。看起来是 DOM 被一起干掉了，所以猜测是 React 16 portal api导致的 bug? 

### What is expected?
点击 alert 确定按钮，仅 alert 消失，popup 仍然显示在界面上。

### What is actually happening?
不仅 alert消失了，连 popup 也消失了

**Comment by silentcloud** [comment]
@huyansheng3 reinstall node_modules
