### ISSUE TITLE
carousel的底部 slider-decorator-0 类自定义

### ISSUE THREAD

**Issue by missjing** [ant-design/ant-design-mobile#2083]
### What problem does this feature solve?
目前因为走马灯底部dots固定在内容块内部，并且组件里用了内联样式（如position: absolute等），导致实现我们的视觉需求（dots在内容块外部）时，需要异步去清除内联样式并且设置新样式

<img src="https://user-images.githubusercontent.com/2724034/32837699-715b9e92-ca49-11e7-80c3-c9c1e77690c9.png" width="300px" />

```
const bottom = $('.slider-decorator-0');
    $(bottom).css({
      'height': '0.6rem',
      'line-height': '0.6rem',
      'border-top': '1px solid #EDF0F3',
      'position': '',
      'bottom': '',
    });
```

### What does the proposed API look like?
支持 dotsDecorator 节点Node样式设置，或者传入dom结构

**Comment by silentcloud** [comment]
@missjing 外层在套一层 div 高度比实际内容高度再高一些即可，类似:

```js
<Carousel>
  <div style={{height: 300, width: 300}}> // 外层在包裹一层比实际内容要高 20-30px
    <div style={{height: 270, width: 300}} /> // 实际的内容
  </div>
</Carousel>
```

**Comment by missjing** [comment]
@silentcloud 实际内容的高度一般是异步获取的，这样还是免不了给最外层动态设置高度，渲染上其实会闪一下的
