### ISSUE TITLE
高清方案在android-26上的显示比例不对

### ISSUE THREAD

**Issue by wanglonglog** [ant-design/ant-design-mobile#2084]
引用高清方案的js， 在android-26的webview中显示比例不对， 页面会被放大很多，不能一个屏幕显示全部页面内容， 请问这个问题怎么解决， android-25就显示的很正常， 另外现在高清方案的介绍页面好像找不到了， 是否已经弃用高清方案了？

**Comment by silentcloud** [comment]
如果是用的 1.x 的话，看这里  http://1x.mobile.ant.design/docs/react/introduce-cn#Web-使用方式

至于说的 26 不正常，25 不正常，看一下文档配置有没问题，自己排查一下，不行的话给出你的demo。

2.x 的话看升级文档 https://mobile.ant.design/docs/react/upgrade-notes-cn#高清方案
