### ISSUE TITLE
Radio和ListView组合使用无法被选中

### ISSUE THREAD

**Issue by renijianxiao** [ant-design/ant-design-mobile#2086]
我的期望：ListView组件上拉加载下一页（每一页都是一行一行的Radio组件，需要可以被选中）。
结果：第一页可以随便选择每一行，当上拉加载下一页后就无法选中。
分析：应该是ListView组件里的定时器有影响，着么解决

**Comment by paranoidjk** [comment]
请给出最小可重现的例子

**Comment by silentcloud** [comment]
Closed for no response.

**Comment by warmhug** [comment]
@KgTong 增强下 ListView + Checkbox / Radio / Switch 的 demo 吧，更贴合实际场景点，也方便排查问题
