### ISSUE TITLE
使用Popover组件时报 Uncaught Error: Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by sundayha** [ant-design/ant-design-mobile#2087]
Version

2.0.3

Environment

macOS 10.12.6 (16G29)、
chrome 版本 61.0.3163.100（正式版本） （64 位）
react: 16.0.0
react-dom: 16.0.0
react-native: 0.50.1

Reproduction link

https://github.com/sundayha/test_app

Steps to reproduce

当我点击`navbar`上的`Popover`时，可以正常使用，但是我使用react-router-redux跳转到其它页面后，再跳转回带有Popover组件的页面时，之前点几次`Popover`就会报错几个 `invariant.js:42 Uncaught Error: Unable to find node on an unmounted component.` 以下是详细错误信息 
```
 Uncaught Error: Unable to find node on an unmounted component.
    at invariant (invariant.js:42)
    at findCurrentFiberUsingSlowPath (react-dom.development.js:1022)
    at findCurrentHostFiber (react-dom.development.js:1092)
    at Object.findHostInstance (react-dom.development.js:13450)
    at react-dom.development.js:16805
    at findDOMNode (react-dom.development.js:13863)
    at Trigger._this.onDocumentClick (Trigger.js:34)
    at batchedUpdates (react-dom.development.js:13238)
    at performFiberBatchedUpdates (react-dom.development.js:1646)
    at stackBatchedUpdates (react-dom.development.js:1637)
```

### What is expected?
去掉该报错信息 `invariant.js:42 Uncaught Error: Unable to find node on an unmounted component.`

### What is actually happening?
点击`navbar`上的`Popover`时，可以正常使用，但是我使用react-router-redux跳转到其它页面后，再跳转回带有Popover组件的页面时，之前点几次`Popover`就会报错几个`invariant.js:42 Uncaught Error: Unable to find node on an unmounted component.`

**Comment by paranoidjk** [comment]
请给出一个最小可重现的例子，可以将代码push到github提供仓库地址

**Comment by sundayha** [comment]
@paranoidjk sorry我这只能先贴个代码片段，在这个页面里点击`NavBar` 上的 `Popover` 组件，没有问题，但是当我使用`react-router-redux` 提供的 `goBack` 跳转到上一页后，再跳转回我所提供的代码片段的这个页面时会报`invariant.js:42 Uncaught Error: Unable to find node on an unmounted component.` 这个错误。但是并不影响使用只是每点一次页面都会报这个错误。
```
import React from 'react';
import {WhiteSpace, List, Button, NavBar, Popover, Icon} from 'antd-mobile';
const Item = List.Item;
import './myCenter.less';
import {goBack} from 'react-router-redux';
import {connect} from 'react-redux';

const myImg = src => <img src={`https://gw.alipayobjects.com/zos/rmsportal/${src}.svg`} className="am-icon am-icon-xs" alt="" />;

@connect()
class MyCenter extends React.Component {

    state = {
        visible: false,
        selected: '',
    };

    onSelect = (opt) => {
        // console.log(opt.props.value);
        this.setState({
            visible: false,
            selected: opt.props.value,
        });
    };

    handleVisibleChange = (visible) => {
        this.setState({
            visible,
        });
    };

    render() {

        return(
            <div className="myCenter-main-div">
                <NavBar
                    mode="light"
                    onLeftClick={() => this.props.dispatch(goBack())}
                    rightContent={
                        <Popover mask
                                 overlayClassName="fortest"
                                 overlayStyle={{ color: 'currentColor' }}
                                 visible={this.state.visible}
                                 overlay={[
                                     (<Popover.Item key="4" value="scan" icon={myImg('tOtXhkIWzwotgGSeptou')} data-seed="logId">Scan</Popover.Item>),
                                     (<Popover.Item key="5" value="special" icon={myImg('PKAgAqZWJVNwKsAJSmXd')} style={{ whiteSpace: 'nowrap' }}>My Qrcode</Popover.Item>),
                                     (<Popover.Item key="6" value="button ct" icon={myImg('uQIYTFeRrjPELImDRrPt')}>
                                         <span style={{ marginRight: 5 }}>Help</span>
                                     </Popover.Item>),
                                 ]}
                                 align={{
                                     overflow: { adjustY: 0, adjustX: 0 },
                                     offset: [-10, 0],
                                 }}
                                 onVisibleChange={this.handleVisibleChange}
                                 onSelect={this.onSelect}
                        >
                            <div style={{
                                height: '100%',
                                padding: '0 15px',
                                marginRight: '-15px',
                                display: 'flex',
                                alignItems: 'center',
                            }}
                            >
                                <Icon type="ellipsis" />
                            </div>
                        </Popover>
                    }
                >
                    NavBar
                </NavBar>
                <WhiteSpace size="sm" />
                <div className="user-show-div">
                    <img src="http://jwt.io/assets/icon.svg" className="head-image" />
                    <span style={{marginTop: '5px'}}>周星星</span>
                </div>
                <WhiteSpace size="sm" />
                <List>
                    <Item thumb="https://zos.alipayobjects.com/rmsportal/dNuvNrtqUztHCwM.png"
                          arrow="horizontal"
                    >
                        b0
                    </Item>
                    <Item thumb="https://zos.alipayobjects.com/rmsportal/dNuvNrtqUztHCwM.png"
                          arrow="horizontal"
                    >
                        b1
                    </Item>
                    <Item thumb="https://zos.alipayobjects.com/rmsportal/dNuvNrtqUztHCwM.png"
                          arrow="horizontal"
                    >
                        b2
                    </Item>
                </List>
                <WhiteSpace size="sm" />
                <Button type="primary" className="logout-button">b3</Button>
            </div>
        );
    }
}

export default MyCenter;
```

**Comment by sundayha** [comment]
@paranoidjk  我在`github`上提交了展示项目请帮我看看 多谢。[这里是展示项目](https://github.com/sundayha/test_app/tree/master)

**Comment by sundayha** [comment]
@paranoidjk 例子我提供完了 能不能忙我看下 多谢。

**Comment by sundayha** [comment]
没人回答我关了

**Comment by paranoidjk** [comment]
<img width="1356" alt="2017-11-20 14 37 39" src="https://user-images.githubusercontent.com/7971415/33005353-662af364-ce00-11e7-9cee-564ba5f11d96.png">


你提供的项目跑不起来。

**Comment by liangminhua** [comment]
[demo](https://codepen.io/liangminhua/pen/bYvxWB?editors=0011) here.May be caused by react version.

**Comment by sundayha** [comment]
@paranoidjk 多谢回答。项目可以跑起来 这个错只是我去掉了`reducers` 里面的引用。所以redux才会报错。没有正确输入路由地址 所以才是空白页面“我的错” 我应该在`README`写上正确地址。请访问`http://0.0.0.0:8081/appLayout/home` [这个地址](http://0.0.0.0:8081/appLayout/home)

**Comment by sundayha** [comment]
@liangminhua 你好，这几天真是不明白这个错误是怎么出的，我react版本也是16。跟你的demo版本一样。应该不是版本引起的问题。你出的这个demo没啥问题。但是到我项目里就会报上面的错误。麻烦你有时间看下我的项目到底是哪出的问题多谢。 项目地址`https://github.com/sundayha/test_app`

**Comment by liangminhua** [comment]
@sundayha [demo](https://codepen.io/liangminhua/pen/bYvxWB?editors=0011) isn't throw error on codepen ,but will throw error when local debugging，maybe ant-design-mobile is not compatible with react@16.

---------------------------------------------------------------------------------

[demo](https://codepen.io/liangminhua/pen/bYvxWB?editors=0011)在codepen是不会报错误的，但是在本地调试的时候会出现错误。可能是ant-design-mobile并不兼容react@16。

**Comment by zhang740** [comment]
@liangminhua codepen上的demo都是跑在react@16上的
![image](https://user-images.githubusercontent.com/7530656/33353704-0ab6de4e-d4ea-11e7-82ff-c996c1972474.png)

**Comment by liangminhua** [comment]
@zhang740 My judgment comes from [Pomax/react-onclickoutside#231 (comment)](https://github.com/Pomax/react-onclickoutside/issues/231#issuecomment-333174275).

**Comment by zhang740** [comment]
@liangminhua 并不是这个原因，m-trigger有bug，在某些情况下单周期多次调用componentDidUpdate时，重复添加了事件，因为组件抛到外面层级的，所以如果内部实例销毁，会出问题。

ref https://github.com/react-component/m-trigger/commit/55370141af2cc64bfd84eaa256a8421e6f585621

@sundayha 升级到 rmc-trigger@1.0.8，或者删除node_modules重装依赖

**Comment by 7-cat** [comment]
我也有同样的问题，升级rmc-grigger@1.0.8也不管用

**Comment by zhang740** [comment]
@7-cat 每个人的情况都未必一样，带上你的demo建个issue

**Comment by sundayha** [comment]
@paranoidjk 别关啊，问题还没解决完呢

**Comment by sundayha** [comment]
@zhang740 多谢修复，但是还有问题。升级到 rmc-trigger@1.0.8后。点击`Popover.Item`不会报错（不升级的时候会点击Popover.Item会直接报错）。但后来我使用`Popover.Item`包裹`<span>`，给`span`一个点击事件跳转到主页还是报之前的错误。详见`github` 问题代码我已经提交 `https://github.com/sundayha/test_app` 有时间帮我看下，多谢

**Comment by zhang740** [comment]
update to 1.0.9, @sundayha , @7-cat

**Comment by sundayha** [comment]
@zhang740 完美~ 多谢 问题解决了

**Comment by AlanZou007** [comment]
我update到了1.0.9, 但是路由跳转还是会报 " Uncaught Error: Unable to find node on an unmounted component."

**Comment by sundayha** [comment]
@AlanZou007 那不清楚是啥问题，我的升级到1.0.9就没问题了。你先 `npm cache clean` 然后 ` rm -rf node_modules && npm i` 试试

**Comment by sundayha** [comment]
@zhang740  你好，现在`popover`出现了一个新的问题。就是把项目打包发布，在`IOS`微信客户端打开后，点击`popover` ，弹出后，再点击蒙板，`popover`不隐藏。但是在安卓上点击蒙板就会隐藏。
```
系统环境：
IOS： 10.3.2(14F89)
iPhone：微信浏览器
iPhone：Safari浏览器
```
```
包版本：
"antd-mobile": "^2.0.3",
"react": "^16.0.0",
"react-dom": "^16.0.0",
```

**Comment by ajjing** [comment]
@sundayha Try this：

`
componentDidMount() {
    //两种写法 第1种好些
    //1.
    document.querySelector('body').setAttribute("style","cursor:pointer");
    document.querySelector('body').addEventListener('click',function (e) {
      if (e.target.classList.contains('am-popover-mask')) {
        setTimeout(that.setState({visible:0,}),0)
      }
    }, true);
    //2.
    // setTimeout(function () {
    //   var c=document.getElementsByClassName('am-popover-mask');
    //   var last_element = c[c.length - 1];
    //   last_element.addEventListener("click", function() {
    //     setTimeout(that.setState({visible:0,}),0)
    //   });
    // },1500);
  }
`
