### ISSUE TITLE
ImagePicker在安卓手机上选择不了（苹果可以），没反应

### ISSUE THREAD

**Issue by foolishcat** [ant-design/ant-design-mobile#2088]

**Comment by paranoidjk** [comment]
@foolishcat 请给出具体的机型，浏览器，以及用改手机访问 https://mobile.ant.design/index-cn 测试

@warmhug 用 android 机测试一下这个

**Comment by warmhug** [comment]
android 4.4 上 支付宝 webview 里测试，确实会经常出问题，偶尔正常。

**Comment by foolishcat** [comment]
弄好了 ，需要 naitve 端来解决，参考论坛里其他帖子 https://github.com/ant-design/ant-design-mobile/wiki/FAQ

**Comment by pudi2018** [comment]
> 弄好了 ，需要 naitve 端来解决，参考论坛里其他帖子 https://github.com/ant-design/ant-design-mobile/wiki/FAQ

具体怎么解决的看你发的链接也没看到是什么情况

**Comment by liKaiKaiGitHub** [comment]
目前开发也遇到了这个问题，这个 有具体的解决方案吗？目前 mate20 无法打开相册，

**Comment by liKaiKaiGitHub** [comment]
目前开发也遇到了这个问题，这个 有具体的解决方案吗？目前 mate20 无法打开相册，
