### ISSUE TITLE
Export Badge text color and backgroundColor

### ISSUE THREAD

**Issue by gengjiawen** [ant-design/ant-design-mobile#2091]
### What problem does this feature solve?
Can we export the two api.

### What does the proposed API look like?
```jsx
textColor: 'white'
badgeBackgroundColor: 'red'
```

**Comment by paranoidjk** [comment]
Please give more detail info about your feature request.

If you are talking about web badge, try use css or style props.

**Comment by gengjiawen** [comment]
I want to use it in React Native, but I have not found a way to change the Badge bg color and text color.

**Comment by paranoidjk** [comment]
- react native custom ui doc: https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui

- stylesheet file: https://github.com/ant-design/ant-design-mobile/blob/master/components/badge/style/index.native.tsx

**Comment by gengjiawen** [comment]
Use style overwrite looks a litter cumbersome, is it okay add two props for this component ?

**Comment by paranoidjk** [comment]
I think it’s not a good way to expose all stylesheet varaiable to props api.

**Comment by gengjiawen** [comment]
Yes, I give a second thought, you are probably right.
