### ISSUE TITLE
升级2.0后高清方案使用refreshControl,下拉刷新的图标文字定位异常

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design-mobile#2098]
### Version
2.0.3

### Environment
win8 QQ浏览器最新版

### Reproduction link
[https://gitee.com/linbq-b7/AntDMobile2.0refreshControlBugDemo](https://gitee.com/linbq-b7/AntDMobile2.0refreshControlBugDemo)

### Steps to reproduce
访问http://localhost:8000/#/page03
下拉刷新

### What is expected?
正常下拉刷新，loding图标在下拉空白位置的中间

### What is actually happening?
loding图标向下偏移，不同设备下的高度都是固定的25px，且默认显示的时候会看到点下拉刷新的提示文字。
```
.zscroller-refresh-control-indicator {
    color: grey;
    text-align: center;
    height: 0.25rem;
    line-height: 0.25rem;
    margin-top: -0.25rem;
}
```
默认的下拉显示，loding图标已经遮挡到下方的图片了
![image](https://user-images.githubusercontent.com/15940920/33000492-5de3af4c-cde3-11e7-87d0-3fa18ccb8e39.png)

手动修改后，正常显示 Microsoft lumia 950
![image](https://user-images.githubusercontent.com/15940920/33000548-d1dc39e6-cde3-11e7-9a34-547d2e6a3a14.png)

iphone6
![image](https://user-images.githubusercontent.com/15940920/33000609-2c2520de-cde4-11e7-947d-ebb673cb3698.png)

**Comment by warmhug** [comment]
注意：px 和 rem 不要混用。错误示例代码上传个 zip 包、或放到 GitHub 上去。

**Comment by l745230** [comment]
[AntDMobile2.0refreshControlBugDemo.zip](https://github.com/ant-design/ant-design-mobile/files/1493763/AntDMobile2.0refreshControlBugDemo.zip)

**Comment by warmhug** [comment]
因为你用了 viewport 缩放的 高清方案，需要按升级文档配置 `@hd: 2px` 对元素尺寸做处理。
`import 'rmc-list-view/assets/index.css';` 这样直接 import css 是没经过处理的、也不建议这么做，需要把里边用到的 css 拷贝到项目的 less 文件里、并 `x @hd` 来做处理。
