### ISSUE TITLE
input-item/PropsType.d.ts中有类型没有声明

### ISSUE THREAD

**Issue by wuyulong1990** [ant-design/ant-design-mobile#2099]
我发现你们别的方法都声明了 e?: any ,但是在InputItem中没有，就像下面这样：
onExtraClick?: (e?) => void;
onErrorClick?: (e?) => void;

文件位置:node_modules/antd-mobile/lib/input-item/PropsType.d.ts

这个导致我的tsc报错了。我使用的是2.0.3版本。

**Comment by paranoidjk** [comment]
dulplicated with https://github.com/ant-design/ant-design-mobile/issues/2100
