### ISSUE TITLE
0.8.x changelog

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#210]

**Comment by warmhug** [comment]
### 0.8.1
- 修复并整理各弹出层类组件 z-index 顺序 https://github.com/ant-design/ant-design-mobile/commit/bb875c2a924f61cc03b8d013fd1a8f5ee8e22972
- Tab 增加禁止 swipeable 的功能 #209

**Comment by Coohack** [comment]
为什么升级后toast和ActivityIndicator，还有modal变大了

**Comment by liqi07** [comment]
@Coohack  #206

**Comment by warmhug** [comment]
- 修复 RefreshControl scroll 问题 #222

**Comment by pingan1927** [comment]
### 0.8.2

- 给`body`标签设置默认背景色，以及默认的`font-size`,`html`设置默认的`font-size`。
- `Grid`属性扩展，每行列数可配置，提供`renderItem`方法。
- 修复`Checkbox`、`Radio`样式细节以及兼容性问题。
- `SearchBar`输入框`Blur`状态时`placeholder`固定靠左对齐。
- `Menu`高度计算bugfix。

**Comment by pingan1927** [comment]
### 0.8.3

- `Checkbox` 修复同意协议这种场景下，label中有协议无法触发`onClick`的bug。
- `SearchBar` 优化动画效果。

**Comment by warmhug** [comment]
### 0.8.4
- 修复 Picker 和 DatePicker `extra`设置在 ListItem 上不生效问题 #241
- 去除 Button  `size=small` 只在 `inline` 设置后生效的限制
- 修复 Button 组件在 pc 版本的 demo 里的按下效果 #244
- 优化 Picker / DatePicker 点击反馈效果 https://github.com/ant-design/ant-design-mobile/commit/adb5a45ae35e13f64d4f295dd328cf9da45aec57  #195 
- 去除 Stepper 组件的 input 不能输入限制，并更改`readOnly`默认值 https://github.com/ant-design/ant-design-mobile/commit/8325f6444970559e465d71df625e81cbe57c0b85#commitcomment-19012543
- 优化 Drawer / Popup 等组件 demo，网站展示细节优化

**Comment by foriacus** [comment]
### 0.8.6

- 修复Carousel dot样式问题 #302 
- 修复Tabbar文字居中问题 #310

**Comment by foriacus** [comment]
0.8.7

- 修复 Carousel dots 失效问题
- 修复 SegmentedControl 样式问题
- 网站 优化，移除useso iconfont

**Comment by motorguo** [comment]
`Accordion 手风琴`  `defaultActiveKey` 没有作用
