### ISSUE TITLE
金额键盘的确定按钮 Disabled 的颜色未跟随主题色改变

### ISSUE THREAD

**Issue by wSLecHayfIeNdock** [ant-design/ant-design-mobile#2101]
### Version
2.0.3

### Environment
Google Chrome 62.0.3202.94

### Reproduction link
[https://github.com/wSLecHayfIeNdock/antd-mobile-issue-demo](https://github.com/wSLecHayfIeNdock/antd-mobile-issue-demo)

### Steps to reproduce

![gif](https://user-images.githubusercontent.com/16831715/33003126-b72e9340-cdf3-11e7-9e9f-bfc0fa3decf9.gif)

### What is expected?
跟随主题色改变

### What is actually happening?
未跟随主题色改变

**Comment by paranoidjk** [comment]
You shoud change `brand-primary-tap`

https://github.com/ant-design/ant-design-mobile/blob/master/components/style/themes/default.less#L178

**Comment by wSLecHayfIeNdock** [comment]
@paranoidjk 解决了！谢谢
还有一个问题：` Toast` 无法正常显示

**Comment by paranoidjk** [comment]
给出最小可复现的demo ？ 另外请先 check 官网 demo 是否正常。

**Comment by wSLecHayfIeNdock** [comment]
@paranoidjk  https://github.com/wSLecHayfIeNdock/antd-mobile-issue-demo 
删了其他没用的代码
官网的是正常


![gif](https://user-images.githubusercontent.com/16831715/33004907-4bd728f4-cdfe-11e7-866a-81e0f61a7e55.gif)
