### ISSUE TITLE
Toast出现后点击，不会消失

### ISSUE THREAD

**Issue by scriptdw** [ant-design/ant-design-mobile#2103]
### Version
2.0.3

### Environment
Mac os， chrome

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/toast?lang=zh-CN#toast-demo-0](https://mobile.ant.design/kitchen-sink/components/toast?lang=zh-CN#toast-demo-0)

### Steps to reproduce
审查元素，切换移动设备，点击按钮Toast出来后连点Toast框，Toast不会消失

### What is expected?
希望能解决这个问题

### What is actually happening?
希望能解决这个问题

---
在ios微信浏览器上遇到的问题，只能贴官方的Demo了

**Comment by zhang740** [comment]
移动端可以复现么？Touch事件误触发了onMouseEnter，而且没有触发onMouseLeave，如果不消失的情况下你再在别的地方点击，可以消失。

**Comment by warmhug** [comment]
确实需要注意，Android / iOS 都会触发 mouse 事件，并且表现不一致。

**Comment by zhang740** [comment]
@warmhug 已迁移rmc-notification，去掉了mouse的监听。

**Comment by jeffie** [comment]
1.x什么时候修复?

**Comment by xinconan** [comment]
1.x在ios上也出现过同样的问题，Toast出现的时候，上下滑动屏幕，Toast就不会消失，希望1.x也迁移一下

**Comment by xinconan** [comment]
好像2.x也没有修复这个问题啊，官方demo中Toast出现的时候上下滑动屏幕Toast不会消失

**Comment by jeffie** [comment]
@xinconan 2.x应该没问题，1.x我自己先手动把 rc-notification替换成rmc-notification就可以了。

**Comment by xinconan** [comment]
我说的问题找到原因了，Toast使用fixed布局，导致出现toast的时候，在ios中页面上下滑动会阻塞setTimeout执行
