### ISSUE TITLE
iOS 11+  Web InputItem 唤起软键盘后会遮盖视野

### ISSUE THREAD

**Issue by cnzsb** [ant-design/ant-design-mobile#2104]
### What problem does this feature solve?
InputItem 源代码中使用了 scrollIntoViewIfNeeded 保证唤起键盘后 input 处于正确的视野区，但是 iOS 11.1.1 中实际效果为页面闪烁并且定位失败。使用自定义的 InputItem 在取消或使用 scrollIntoViewIfNeeded 后发现不使用该方法可以解决。

### What does the proposed API look like?
是否需要取消源码中的 scrollIntoViewIfNeeded，或者是否提供一个 api 用以手动开启或者关闭此功能。

**Comment by paranoidjk** [comment]
already fixed in https://github.com/ant-design/ant-design-mobile/issues/1893 by @silentcloud
