### ISSUE TITLE
为什么2.x的版本舍弃了1.x的高清适配方案？

### ISSUE THREAD

**Issue by NicholasNC** [ant-design/ant-design-mobile#2107]
### Version
2.0.3

***

不好意思，这不是一个issue，只是不是很明白为什么2.x的版本舍弃了1.x的高清适配方案？所以想跟大家讨论一下。

最早使用的适配方案是淘宝那个（[lib-flexible](https://github.com/amfe/lib-flexible)），lib-flexible的0.3.2的版本，使用rem，虽然设置根值方法的不同，但是和ant desigin mobile 1.x的高清适配方案雷同，在iPhone下（高倍屏）都将viewpoint的缩放比改成0.5。这种做法的一个坏处是：使用富文本时，如果富文本中设置了字体大小（一般都是直接设置标签的style属性），这时，当viewpoint的缩放是0.5时，字体就非常小。之前的做法是用js将这些富文本的字体通过正则表达式统一乘2。

这次2.x直接不用之前的高清适配方案，另外好像也没有使用rem，是否等于说做可以用别的方法做适配？

**Comment by paranoidjk** [comment]
并不是**舍弃**， 只是不再强制捆绑，而是改成默认不需要，用户也可以按需自行配置 https://mobile.ant.design/docs/react/upgrade-notes-cn#高清方案。

至于原因的话，高清方案的 postcss, px-to-rem 都会增加额外配置和使用成本，另外 viewport 缩放在一些 canvas 动画，地图等场景下会引起其他问题。

**Comment by NicholasNC** [comment]
@paranoidjk 请问，那现在2.x版本的适配我们是直接使用px？还是说我们在 `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" />` 即缩放比为1的前提下计算rem的跟值？

**Comment by paranoidjk** [comment]
2.x 新项目直接看官方上手文档，从 1.x 升级的话看升级文档

**Comment by yamakasiluke** [comment]
The document of 2.x doesn't show how to use rem or hd

**Comment by WangYang-Rex** [comment]
@paranoidjk 1.x hd高清方案对于iphonex适配是有问题的，怎么解决？
