### ISSUE TITLE
React Native 使用SwipeAction全部滑出问题

### ISSUE THREAD

**Issue by AmmiWang** [ant-design/ant-design-mobile#2108]
SwipeAction组件在React Native中使用会有全部滑出问题（如下图），请问有哪位大牛有解决方案吗？

![lssue](https://user-images.githubusercontent.com/26961020/33109083-7d0df88a-cf7a-11e7-90e1-dcfff640cc38.png)

**Comment by silentcloud** [comment]
@AmmiWang 试一下这边这个例子有没有问题  https://github.com/dancormier/react-native-swipeout

**Comment by AmmiWang** [comment]
@silentcloud  蚂蚁金服的这么没办法解决吗？项目基本用的都是蚂蚁金服的组件，基本没有其他外网找的哈~

**Comment by silentcloud** [comment]
@AmmiWang RN swipeaction 是基于我发的那个。
或者把你的demo 传上来看看

**Comment by AmmiWang** [comment]
@silentcloud    Demo就是官方给的那个Demo直接复制下来在react native上边用就有这个问题，难道antd没有发现这个问题吗？还是说发现了但是暂时没有办法解决？

**Comment by silentcloud** [comment]
@AmmiWang https://github.com/ant-design/ant-design-mobile/blob/master/components/swipe-action/demo/basic.native.tsx 这里的demo只写了一个 item， 你要处理 issue 这种情况的话，需要自己在 demo 里处理，参考 https://github.com/dancormier/react-native-swipeout/blob/master/example/SwipeoutExample.js，在组件里是没法实现的，只能在业务代码里实现

**Comment by DevilViy** [comment]
react-native-swipeout 这里面含有close属性所以业务代码可以实现关闭，但是antd-mobile没有close这个属性

**Comment by StoneYuan** [comment]
@MrSeaWave   hello，can you solve it ？
