### ISSUE TITLE
向inputItem加‘*’号

### ISSUE THREAD

**Issue by sunshihao** [ant-design/ant-design-mobile#2109]
使用inputItem时，我想在文字后加一个红色的‘*’号，作为必填的展示，antd有什么好的应对办法吗？
[ http://new-issue.ant.design?repo=ant-design-mobile](url)

**Comment by gengjiawen** [comment]
InputItem的extra属性，你试过没？

**Comment by sunshihao** [comment]
extra的属性是在右边加东西，并不能在左边

**Comment by sunshihao** [comment]
后来在inputItem间加view来自定义写了，解决了这个问题
