### ISSUE TITLE
rn app bug

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#211]
### webview

- ios 一直 loading 无法操作
- android 6.x 打开就是放大状态

**Comment by silentcloud** [comment]
@yiminghe ios 能打开，公司的网络可能有问题，手机翻墙 100% 能打开；
android 的需要开哈 mobile.ant.design/kitchen-sink/ ，直接显示的这个网站

**Comment by silentcloud** [comment]
android 的网站看哈 @liqi07 ，我大致看了哈，模拟器 全局 font-size 太大

![image](https://cloud.githubusercontent.com/assets/1698185/18264045/7b42ae1a-7440-11e6-8d20-22e0b6310c59.png)

这个模拟器下，font-size 是 150px，其实 50px 是对的

**Comment by liqi07** [comment]
@silentcloud app里面预设的问题吧，用android 上浏览器访问mobile.ant.design/kitchen-sink/ 也正常。

**Comment by silentcloud** [comment]
这个初步排查了哈，定位在 webview 上的问题，但是官方接口 `scalesPageToFit ` 已经包括了，还没查到具体问题所在，先保留 issue

**Comment by silentcloud** [comment]
dec4e7af7a53da65572d0723a7a776dfc45a51c2
