### ISSUE TITLE
Feature Request：InputItem need leftExtra in some cases

### ISSUE THREAD

**Issue by gengjiawen** [ant-design/ant-design-mobile#2110]
### What problem does this feature solve?
common design when need extra info in left side. 
![image](https://user-images.githubusercontent.com/3759816/33120350-ca3a81c8-cfac-11e7-9b0f-a664c58f620c.png)

### What does the proposed API look like?
add `leftExtra` prop to InputItem Props

**Comment by gengjiawen** [comment]
I finally solved this by write the layout using antd-style. Still thinking whether do we really need leftExtra.

**Comment by warmhug** [comment]
Don't consider support for now.
