### ISSUE TITLE
The Cancel button of SearchBar fired onBlur event,not OnCancel event

### ISSUE THREAD

**Issue by YaoHuiJi** [ant-design/ant-design-mobile#2111]
### Version
2.0.2

### Environment
react-native 0.50.1 on Mac OS

### Reproduction link
[https://codepen.io/anon/pen/qVYbmL?editors=1111](https://codepen.io/anon/pen/qVYbmL?editors=1111)

### Steps to reproduce
set showCancelButton to false, input some words, and then click the Cancel button of SearchBar

### What is expected?
fires the onCancel event

### What is actually happening?
the onCancel event is not fired, but only the onBlur event

---
I think maybe I know what happened now,If the TextInput has the focus, when you try to click the Cancel button, actually you didn't click the Cancel button, what you clicked is just some other place to let TextInput lose focus and close the keyboard.you need click the Cancel button again.but because when TextInput lost focus ,ant-mobile will hide the Cancel button, so you can never click it actually. I just set showCancelButton to true to make it work, but It`s not what I want. what should I do to make it right when showCancelButton is false?

**Comment by warmhug** [comment]
It seems no good way..
