### ISSUE TITLE
Tabs error--I used the official example

### ISSUE THREAD

**Issue by NerdC** [ant-design/ant-design-mobile#2113]
Error message：
Warning: There must be `tab` property on children of Tabs.

I wrote it entirely by way of example,But there was such a mistake.

**Comment by zhang740** [comment]
codepen: https://codepen.io/anon/pen/dZedLv?&editors=001

**Comment by NerdC** [comment]
@zhang740 thanks。I upgraded  to antd-mobile 2.0.3,problem solved。
