### ISSUE TITLE
DatePicker可以设置未选择前的默认定位日期

### ISSUE THREAD

**Issue by xfrogcn** [ant-design/ant-design-mobile#2114]
### What problem does this feature solve?
有时候，某些日期输入字段是选填的，在用户未明确选择之前，值为null，但是我们可能希望在打开DatePicker时，能够将日期默认定位在一个固定日期（如今天），而不是在最小日期哪里，这是因为，如果日期跨度太大（场景：大部分日期都集中在最近，但有少部分日期可能在很久以前，此时，必须设置最小日期来适应少部分需求），用户需要滚动很长的距离才能达到想要的位置。

### What does the proposed API look like?
增加一个 defaultValue 的props，打开DatePicker时，如果未选择值，先定位到defaultValue指定的日期。

**Comment by paranoidjk** [comment]
@xfrogcn 设置 `props.value` 即可

**Comment by paranoidjk** [comment]
- https://github.com/ant-design/ant-design-mobile/blob/master/components/date-picker/index.tsx#L71
- https://github.com/ant-design/ant-design-mobile/blob/master/components/date-picker/index.tsx#L86

@warmhug 为什么要把 value 和 defaultValue 两个 API 合并？你考虑一下这个设计

**Comment by warmhug** [comment]
defaultValue 可以得到支持 @zhang740 但应该不是用来解决这个问题。
对这个需求，解决方法参考 demo 示例中后两种写法
![image](https://user-images.githubusercontent.com/2011119/33302808-d959ce84-d439-11e7-977b-698cbc48d206.png)

**Comment by xfrogcn** [comment]
@warmhug  这种方式会设置value，但需求是，在不设置值的情况下，设定DatePicker打开后的默认定位日期，这主要是针对选填字段，用户可以不用选择日期，此时DatePicker的值必须为空，Demo中的方式，值已经被设置为具体日期了

**Comment by wk1017553772** [comment]
我也遇到了和樓主一樣的問題，

**Comment by zhang740** [comment]
@xfrogcn 日期展示的逻辑是可以自定义的，`DatePicker` 会给子组件传递 `extra` 属性，即为日期，上方例子，`CustomChildren` 组件的props上会有 `extra` 参数。

**Comment by gengjiawen** [comment]
还是有 defaultValue  更方便些。而且现在的设计选择后展示的日期是灰色的。应该是黑色的。

**Comment by vcing** [comment]
目前是这样解决的，简单封装一下

```
const DateSelector = (props) => {
  const { value, defaultValue = new Date(), extra: realExtra } = props
  const CustomChildren = ({ extra, onClick, children }) => (
    <div onClick={onClick}>
      {children}
      {value
        ? <span className={style.extra}>{extra}</span>
        : <span className={style.placeholder}>{realExtra}</span>}
    </div>
  )
  const _props = {...props}
  delete _props.value
  return (
    <DatePicker
      value={value || defaultValue}
      {..._props}>
      <CustomChildren />
    </DatePicker>
  )
}
```
不过还是期望能官方支持
BTW 这能提PR吗？

**Comment by linalinalin** [comment]
Why is there defaultDate on GitHub, but there is no defaultDate on API, and the code that runs GitHub locally will fail? @ant-design-bot 
https://github.com/ant-design/ant-design-mobile/tree/master/components/date-picker

**Comment by skidxjq** [comment]
放到feat中评估

**Comment by theshying** [comment]
+1
