### ISSUE TITLE
React Native: Radio, checkbox can customize themes, like buttons, set Primary properties

### ISSUE THREAD

**Issue by wfxphoebus** [ant-design/ant-design-mobile#2117]
### What problem does this feature solve?
nothing

### What does the proposed API look like?
nothing

**Comment by silentcloud** [comment]
@wfxphoebus see https://mobile.ant.design/docs/react/introduce-cn#更多增强-(非必须):

**Comment by wfxphoebus** [comment]
![1511752393514](https://user-images.githubusercontent.com/3102335/33249174-02d2e042-d364-11e7-8681-ce74c1e16198.jpg)

Can I customize the pictures of Radio and checkbox?
