### ISSUE TITLE
TabBar里的badge可以提供一个颜色设置吗

### ISSUE THREAD

**Issue by alwaysloseall** [ant-design/ant-design-mobile#2119]
### What problem does this feature solve?
在react-native项目中，希望可以自定义badge的颜色，无法通过prefixCls添加自定义样式覆盖，所以希望提供api

### What does the proposed API look like?
textColor='#fff'
backgroundColor: '#f00'

**Comment by silentcloud** [comment]
@alwaysloseall https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui
