### ISSUE TITLE
React Native: how to change Radio, checkbox blue

### ISSUE THREAD

**Issue by wfxphoebus** [ant-design/ant-design-mobile#2120]
### What problem does this feature solve?
Can be styled according to the theme

![1511752393514](https://user-images.githubusercontent.com/3102335/33254417-9abee422-d383-11e7-8c19-6dfcc263fae1.jpg)

### What does the proposed API look like?
To change the check image

**Comment by silentcloud** [comment]
Currently not.  It is only an image.
https://github.com/ant-design/ant-design-mobile/blob/master/components/radio/Radio.native.tsx#L63
https://github.com/ant-design/ant-design-mobile/blob/master/components/checkbox/Checkbox.native.tsx#L72

You can customize the images in node_modules and replace them. Also you can use a script to copy your images before `npm start`

**Comment by rajnish42413** [comment]
use this style
 style={{color: 'red',fontSize:25,marginVertical:5}}
