### ISSUE TITLE
In InputItem amount input, can I use touchstart as an option to handler click event

### ISSUE THREAD

**Issue by kaiqigong** [ant-design/ant-design-mobile#2121]
### What problem does this feature solve?
For some reason, fastclick does not work in android webview. We can still use touchstart to remove this 300ms delay.
So my proposal is a prop like,
```
<InputItem type="money"
          value={amount}
          useTouchstart />
```
if `useTouchstart` is set, then the numberPad binds click handler on `onTouchStart` event instead of `onClick`.

### What does the proposed API look like?
```
<InputItem type="money"
          value={amount}
          useTouchstart />
```
if `useTouchstart` is set, will avoid 300ms delay.

**Comment by warmhug** [comment]
You should not use it that will cause more problems. From the perspective of our entire component library, we will not add APIs such as `useTouchstart` to a single component.

You also need a comprehensive compatibility test, welcome to propose a more comprehensive solution.

**Comment by paranoidjk** [comment]
We will not add this api, but `InputItem` will pass your extra props to the original input element, so you still can add a `onTouchStart` handler, it's up to you, but we recommend use `onClick`

**Comment by kaiqigong** [comment]
@paranoidjk you mean it will pass extra props to the `input` element, not the `h5 keypad`, right?
But I need to remove the delay on `h5 keypad` tap.
🤦‍♀️

**Comment by paranoidjk** [comment]
I don't konw what's your mean about `h5 keypad`.

**Comment by ganxunzou** [comment]
use <InputItem type="money"/>  in  iOS UIWebView Container . I have the same problem （300ms delay）。Eliminate 300 msdelay with onTouchStart event。

**Comment by ganxunzou** [comment]
In addition ， Why recommend use `onClick`
