### ISSUE TITLE
babel-plugin-import doesn't work with ant-mobile in react-starter-kit

### ISSUE THREAD

**Issue by hyden-tan** [ant-design/ant-design-mobile#2122]
I want to use antd-mobile, so i cloned ant-design/react-starter-kit and made some changes in webpack-config.js. It's "/node_modules\/.*antd-mobile/" and "libraryName: 'antd-mobile'", but it doesn't work. I have failed many times.

**Comment by paranoidjk** [comment]
Suggest you push your code to github  and give us the link, so we can check out what is wrong here.

**Comment by hyden-tan** [comment]
I use antd-mobile in [this boilerplate](https://github.com/kriasoft/react-starter-kit/tree/feature/redux), and follow [this demo](https://github.com/ant-design/react-starter-kit) to config babel-import-plugin, but component 's styles doesn't work.My code is same as that demo, just change antd to be  antd-mobile in webpack.config.js. Thanks for your attention！
