### ISSUE TITLE
The range does not support react native, but the document says support

### ISSUE THREAD

**Issue by wfxphoebus** [ant-design/ant-design-mobile#2123]
### Version
2.0.3

### Environment
react native 0.49.3 、mac、

### Reproduction link
[https://mobile.ant.design/components/range-cn/](https://mobile.ant.design/components/range-cn/)

I tested it, I can't show it. Do you have any support?

### Steps to reproduce
nothing

### What is expected?
support

### What is actually happening?
does not support

**Comment by silentcloud** [comment]
![image](https://user-images.githubusercontent.com/1698185/33408593-354233a2-d5b2-11e7-9b86-43fdd53f25ec.png)

**Comment by zhang740** [comment]
之前文档有点问题。。。 @silentcloud 
ref https://github.com/ant-design/ant-design-mobile/commit/31ab9268f2f8180ed898b1c6065bf70692562169
