### ISSUE TITLE
tabs的underline如何自定义宽度

### ISSUE THREAD

**Issue by cuitianze** [ant-design/ant-design-mobile#2124]
### What problem does this feature solve?
能够高效还原设计师的设计图

### What does the proposed API look like?
same issue with https://github.com/ant-design/ant-design-mobile/issues/1050

**Comment by cuitianze** [comment]
@afc163 Aha? Why give me 👎 ?

**Comment by zhang740** [comment]
文档：https://mobile.ant.design/components/tabs-cn/#Tabs

简单自定义使用tabBarUnderlineStyle，复杂自定义替换整个TabBar，可以继承默认实现然后覆盖想修改的地方。

@cuitianze

**Comment by cuitianze** [comment]
@zhang740 您好，想请教下tabbar支持自定义替换TabBar.Item吗？
要实现的功能，如微博APP中间的 “+” 按钮，不需要title和icon同时存在。

**Comment by cuitianze** [comment]
@zhang740 谢谢，那我自定义TabBar吧。
不过感觉这不属于复杂的自定义，再写很多代码显得有些多余。
伸手党不该向开源社区提过多需求的，forgive me。
感谢AntDesign开源！

**Comment by zhang740** [comment]
@cuitianze tabBarUnderlineStyle这个API本身就是来实现简单需求的啊，tabBarUnderlineStyle 不能满足么？具体是什么场景？

**Comment by zhang740** [comment]
@cuitianze 看了下，如果你用了`tabBarUnderlineStyle`无法改变宽度，是因为`tabBarUnderlineStyle`优先级不够，调整了下，新发了 rmc-tabs@1.2.20。（安装rmc-tabs新版本，或者删了node_modules重装依赖）

**Comment by chenghaohao** [comment]
@zhang740 
![image](https://user-images.githubusercontent.com/23539868/33421604-93670d78-d5ed-11e7-9f77-6c87f05a07bf.png)
tabBarUnderlineStyle加个width 是这样的效果，下划线的left不会自适应居中呢

**Comment by zhang740** [comment]
@chenghaohao 升级到rmc-tabs@1.2.21
例子 https://react-component.github.io/m-tabs/examples/basic.html 最后一个
antd-mobile 中 `renderTabBar` 使用参照 https://mobile.ant.design/components/tabs-cn/#components-tabs-demo-sticky

**Comment by cuitianze** [comment]
@zhang740 Thanks。
既然上面提到了tabs和sticky，我想请问为什么sticky不能应用于tabBar？
比如将这个例子https://mobile.ant.design/components/tabs-cn/#components-tabs-demo-sticky，放置于TabBar.Item中。

可以帮忙看看么？

**Comment by zhang740** [comment]
@cuitianze 不明白什么意思。。。想要什么效果？请给个demo

**Comment by cuitianze** [comment]
@zhang740 

![sticky](https://user-images.githubusercontent.com/5918515/33513814-ee54c2be-d784-11e7-9223-1e813b974564.jpeg)

红色这块区域希望能吸顶。

最下面一排菜单是TabBar。

**Comment by cuitianze** [comment]
@zhang740 就比如 https://mobile.ant.design/components/tabs-cn/#components-tabs-demo-sticky 这个demo，是单独一个页面的时候，可以做到吸顶效果，但放到TabBar里就出现Bug了，无法吸顶。

**Comment by zhang740** [comment]
@cuitianze 可以先设置TabBar.Item的style，transform: 'none'，下个版本修复。

**Comment by cuitianze** [comment]
@zhang740 如果是这样的话，ListView理论上不是也应该无效么？
😭 我在ListView里应用确实无效，不知道官方例子放在Section里是如何有效的? 
![image](https://user-images.githubusercontent.com/5918515/33552810-450bb6aa-d931-11e7-8934-d9e9c564dac3.png)

**Comment by cuitianze** [comment]
@zhang740 ListView 的 Refresh 经常拉下来不自动收起来

**Comment by zhang740** [comment]
@cuitianze 新开一个ListView 的issue吧

**Comment by spicyboiledfish** [comment]
我这边改了源码之后，已经实现了这种效果。等间距，且underline自适应宽度，左移的时候的偏移量也会根据当前位置及滑动到中间位置去精确计算。请看下面我的效果图：

![等间距](https://user-images.githubusercontent.com/18587093/67670118-290f3900-f9ae-11e9-9b7d-5dc77b36ac74.gif)

**Comment by mingzizhennimafan** [comment]
可以试下： transform: scaleX(0.1);

**Comment by wvalen** [comment]
偷懒的下划线宽度控制方法：
`tabBarUnderlineStyle={{ width: "10%",  marginLeft: "20%" }}`

**Comment by Gallery2000** [comment]
@wvalen antd4.0 tabBarUnderlineStyle已经删除了

**Comment by wvalen** [comment]
> @wvalen antd4.0 tabBarUnderlineStyle已经删除了

我一脸懵逼，这里不是antd-mobiloe嘛，跟antd4.0有啥关系
