### ISSUE TITLE
height of TextareaItem

### ISSUE THREAD

**Issue by troyz** [ant-design/ant-design-mobile#2126]
Hi, `TextareaItem` component  have `rows`, `autoHeight` props, could you please add a `maxRows` or `maxHeight` property to restrict the height of `TextareaItem`?

**Comment by warmhug** [comment]
Try setting the style yourself.

**Comment by paranoidjk** [comment]
We just do a simple wrap of [textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea), right now have no plan to support other feature.

You may see https://github.com/ant-design/ant-design/blob/master/components/input/calculateNodeHeight.tsx as a example.
