### ISSUE TITLE
SwipeAction 建议加入onPress回调

### ISSUE THREAD

**Issue by qiuchengw** [ant-design/ant-design-mobile#213]
#### 本地环境

- antd-mobile 版本：0.8.0
- 操作系统及其版本：android 4.4

#### 你做了什么？

使用了SwipeAction，控件只能响应onLongPress事件。
建议再提供一个短按事件回调（onPress）给使用者处理。这个用处还是很大的。

**Comment by silentcloud** [comment]
你的使用场景？ 短按事件可以绑在 SwipeAction 的 children 上

**Comment by qiuchengw** [comment]
@silentcloud 绑定到children是不行的。比如如下代码：
```
<SwipeAction>
     <TouchableOpacity onPress={}>
         <view> .....
     </TouchableOpacity>
</SwipeAction>
```
那么TouchableOpacity的onPress可以正常响应，但是SwipeAction就完全失去响应了

**Comment by silentcloud** [comment]
`react-native-swipeout` 这个库不支持，估计得后期自己来改造

**Comment by qiuchengw** [comment]
好吧，那么这个问题先不关闭吧。看看以后能否有机会支持。
