### ISSUE TITLE
Modal.alert 点击按钮关闭Modal时报错。

### ISSUE THREAD

**Issue by jamieYou** [ant-design/ant-design-mobile#2135]
![2017-12-01 3 22 33](https://user-images.githubusercontent.com/19544032/33472118-b881c418-d6ab-11e7-9d6e-27a8c9b64f4b.png)

code:
```
Modal.alert('退出?', '确定要退出吗?', [
      { text: '取消', onPress: () => null },
      { text: '确定', onPress: authStore.logout },
    ])
```

关闭Modal时报错，并且只有背景消失，Modal没消失。
react版本为16以上，15不会出现这个错误。

**Comment by czy0729** [comment]
+1

**Comment by zhang740** [comment]
@czy0729 @jamieYou can you provide a re-producible demo?

**Comment by jamieYou** [comment]
I found the same situation with Picker components. But I can not reproduce it at https://codepen.io/pen. Do you have the same situation?

**Comment by zhang740** [comment]
Sorry, i cannot reproduce, you can provider a github repo also.
@jamieYou

**Comment by jamieYou** [comment]
The current problem is to locate the DialogWrap component of [rmc-dialog](https://github.com/react-component/m-dialog), do not know if it is not compatible with React@16
![2017-12-06 3 21 02](https://user-images.githubusercontent.com/19544032/33649512-1fcc4e72-da99-11e7-9b31-fee3d3c9f840.png)

**Comment by czy0729** [comment]
@jamieYou 
刚刚把依赖包全部重新下了一遍，这个问题就不存在了。然而我也没发现是什么原因导致的

之前的依赖
  "dependencies": {
    "antd-mobile": "^2.1.0",
    "babel-plugin-import": "^1.2.1",
    "classnames": "^2.2.5",
    "express": "^4.16.1",
    "isomorphic-unfetch": "^2.0.0",
    "lodash.debounce": "^4.0.8",
    "mobx": "^3.3.1",
    "mobx-react": "^4.3.3",
    "moment": "^2.18.1",
    "next": "^4.1.4",
    "prop-types": "^15.6.0",
    "rc-animate": "^2.4.1",
    "rc-form": "^1.4.8",
    "rc-upload": "^2.4.3",
    "react": "^16.2.0",
    "react-affixed": "^1.1.3",
    "react-dom": "^16.2.0",
    "react-player": "^0.25.2",
    "react-singleton": "^1.3.3",
    "react-sticky": "^6.0.1",
    "require-hacker": "^3.0.0",
    "svg-sprite-loader": "^0.3.1"
  },
  "devDependencies": {
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-module-alias": "^1.6.0",
    "cross-env": "^5.0.5"
  }

现在的依赖
  "dependencies": {
    "antd-mobile": "^2.1.0",
    "babel-plugin-import": "^1.6.2",
    "classnames": "^2.2.5",
    "express": "^4.16.2",
    "isomorphic-unfetch": "^2.0.0",
    "lodash.debounce": "^4.0.8",
    "mobx": "^3.3.3",
    "mobx-react": "^4.3.5",
    "moment": "^2.19.3",
    "next": "^4.2.0",
    "prop-types": "^15.6.0",
    "rc-animate": "^2.4.1",
    "rc-form": "^1.4.8",
    "rc-upload": "^2.4.4",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-player": "^0.25.3",
    "react-singleton": "^1.3.3",
    "react-sticky": "^6.0.1",
    "require-hacker": "^3.0.1",
    "svg-sprite-loader": "^0.3.1"
  },
  "devDependencies": {
    "babel-plugin-module-alias": "^1.6.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "cross-env": "^5.1.1"
  }

**Comment by jamieYou** [comment]
@czy0729 谢谢🙏，我把lock文件删掉，重装就好了。看来更新antd-mobile的时候还是需要卸载再更新。

@zhang740 I'm sorry, the problem has been solved. Thank you for your help.
