### ISSUE TITLE
之前的样式用的没问题，更新了0.8版本之后，样式出错

### ISSUE THREAD

**Issue by sananiki** [ant-design/ant-design-mobile#214]
.babelrc文件
{
  "presets": [ "react", "es2015", "stage-0" ],
  "plugins": [
    ["antd", {
      style: 'css',  // 'less',
      libraryName: 'antd-mobile',
    }]
  ]
}
0.8之前的版本，样式什么都是正常的，更新了0.8之后，样式不正常，字体变的很大

**Comment by liqi07** [comment]
https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8%E9%AB%98%E6%B8%85%E6%96%B9%E6%A1%88%E5%AE%9E%E8%B7%B5

**Comment by liqi07** [comment]
#56 参考脚手架已更新

**Comment by lichengit** [comment]
你好，我也遇到了这个问题，请问是如何解决的？跪求！

**Comment by warmhug** [comment]
@lichengit 仔细看文档，高清方案
