### ISSUE TITLE
列表PullToRefresh下拉刷新的时候，在IOS上会进入a链接的详情页面，请问如何解决？

### ISSUE THREAD

**Issue by wendesun** [ant-design/ant-design-mobile#2141]
列表PullToRefresh下拉刷新的时候，在IOS上会进入a链接的详情页面，请问如何解决？

**Comment by warmhug** [comment]
ref https://github.com/react-component/m-pull-to-refresh/issues/11

**Comment by warmhug** [comment]
重装 node_modules ，确保 rmc-pull-to-refresh 为 1.0.6

**Comment by XuChunxiao** [comment]
更新rmc-pull-to-refresh 到 1.0.6 后，该问题fix，但在Tabs 中使用 ListView pullToRefresh会使Tabs的左右滑动内容切换失效

**Comment by warmhug** [comment]
@XuChunxiao  升级到 rmc-pull-to-refresh@1.0.7
