### ISSUE TITLE
Modal keyboardType

### ISSUE THREAD

**Issue by digitaledge** [ant-design/ant-design-mobile#2143]
### What problem does this feature solve?
Set custom keyboardType to Model Input fields. I actually want to use the modal for a numeric pin input and need somehow to set a numeric keyboard.

### What does the proposed API look like?
Some new property (if it does not exist), e.g. "keyboardType= 'numeric'"

**Comment by zhang740** [comment]
why not use `InputItem`，type: 'money' ？https://mobile.ant.design/components/input-item-cn/
