### ISSUE TITLE
能否同时安装两个不同版本的antd-mobile

### ISSUE THREAD

**Issue by youshao** [ant-design/ant-design-mobile#2144]
虽然这么做不合理，但是目前还是有这个需求，不知道能否实现呢？

**Comment by paranoidjk** [comment]
不支持，npm 你怎么装多版本？

**Comment by youshao** [comment]
@paranoidjk 修改下antd-mobile的名称 就可以实现两个版本同时使用了；安装两个版本时为了在旧项目使用新版本的新组件；由于旧版本的组件在新版中以及被剔除，所以需要安装两个版本来解决这个问题
