### ISSUE TITLE
SearchBar not shown properly after following the official setup steps based on dva

### ISSUE THREAD

**Issue by lxc-xx** [ant-design/ant-design-mobile#2146]
### Version
2.1.0

### Environment
OSX 10.13, Chrome 62.0.3202.94

### Reproduction link
[https://github.com/lxc-xx/antdmobile_dva_searchbar](https://github.com/lxc-xx/antdmobile_dva_searchbar)

### Steps to reproduce
1. Download the minimal reporduction repo.
2. npm install && npm start

### What is expected?
The search bar should be displayed properly as the document shows (  https://mobile.ant.design/components/search-bar-cn/#components-search-bar-demo-basic )

### What is actually happening?
The text of the search bar is skewed towards to the right end. But after a few clicks, it will show properly.

---
The code I used to test search bar is https://gist.github.com/lxc-xx/99042da163110a85f9e1ae07ce67f2fa
It is the same as the code in the document https://mobile.ant.design/components/search-bar-cn/#components-search-bar-demo-basic. 

I create the project following the official instruction here.
https://mobile.ant.design/docs/react/practical-projects-cn
https://mobile.ant.design/docs/react/introduce-cn#快速上手

Actually, the search bar is working well in the create-react-app project.

**Comment by lxc-xx** [comment]
Anyone would like to reproduce the bug or make comments? It has been 8 days.

**Comment by warmhug** [comment]
Sorry, the reply is late. This problem is because css is loaded later than js. And there is no problem in the production environment. @sorrycc will track down the problem.
