### ISSUE TITLE
ListView  With PullToRefresh  

### ISSUE THREAD

**Issue by developerYangli** [ant-design/ant-design-mobile#2148]
### Version
2.0.3

### Environment
iOS 

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/pull-to-refresh#pull-to-refresh-demo-0](https://mobile.ant.design/kitchen-sink/components/pull-to-refresh#pull-to-refresh-demo-0)

### Steps to reproduce
Use Card as a listitem ，

<Card onClick={()=>{alert('nihao' item.id)}}>
                <Card.Header
                    title={<ChkIndexListAduitStatus status={item.audit_status}></ChkIndexListAduitStatus>}
                    extra={Thu.formatDate(item.created_at)}
                />
                <Card.Body>
                    <div>{student} - {item.grade}{item.subject}</div>
                </Card.Body>
                <Card.Footer content={<ChkIndexListCardFooter duration={item.duration} start={item.start_at} end={item.end_at}/>} />
            </Card>

### What is expected?
I pull to refresh this page only refreshing this page without other thiing 

### What is actually happening?
when I pull to refresh this page ,this clicking action is operated

**Comment by zhang740** [comment]
ref #2141 , upgrade version please.
