### ISSUE TITLE
Toast类型的指示器的大小可以控制或者随着指示器文本文字自动扩展大小

### ISSUE THREAD

**Issue by Mscynol** [ant-design/ant-design-mobile#2149]
### What problem does this feature solve?
解决了指示器文本偏多的情况UI界面不好看的情景

### What does the proposed API look like?
<ActivityIndicator
                    style={{...}}
                    toast
                    text="商品编码更新中..."
                    animating={this.state.animating}
                />
默认的指示器文本文字偏多的情况下出现换行，美观程度很低

**Comment by Mscynol** [comment]
What problem does this feature solve?
The situation in which the UI interface is not good is solved by the fact that the text of the indicator is too much.
What does the proposed API look like?
The default indicator has a very low aesthetic level when the text is much more text.

**Comment by paranoidjk** [comment]
cc @peter0011
