### ISSUE TITLE
ImagePicker  隐藏删除图标属性

### ISSUE THREAD

**Issue by P-Rain** [ant-design/ant-design-mobile#2150]
### What problem does this feature solve?
ImagePicker作为图片预览功能使用时（点击ImagePickeder中的小图展示大图），无法隐藏删除图标

### What does the proposed API look like?
clearicon boolean  true

**Comment by skidxjq** [comment]
此 feature 放到2.2 评估

**Comment by likezero** [comment]
close in #3185
