### ISSUE TITLE
antd-mobile  : Modal  alert确认对话框，360浏览器不兼容onPress方法吗？

### ISSUE THREAD

**Issue by bang0929** [ant-design/ant-design-mobile#2153]
Modal  alert确认对话框，360浏览器不兼容onPress方法吗？其他浏览器（没有测试IE）可以没有问题，360浏览器弹出对话框后，会出现点击按钮无反应

**Comment by paranoidjk** [comment]
具体机型，以及自己检查 console 是否有报错，把内容贴出来。

官方 demo 测试正常，无法复现。

**Comment by ANNNYG** [comment]
因为打包后生成了inset: 0，兼容一下低版本的谷歌内核可以解决
