### ISSUE TITLE
antd-mobile的Stepper当数值减到最小值时，再修改输入框的值，值会自动减到最小值

### ISSUE THREAD

**Issue by LitaryVan** [ant-design/ant-design-mobile#2154]

**Comment by LitaryVan** [comment]
Use antd-mobile's Stepper.When the value is reduced to a minimum, the value of the input box is modified and the value is automatically minimized.

**Comment by LitaryVan** [comment]
The official example is wrong.https://mobile.ant.design/components/stepper-cn/




Best wishes
在2017年12月08日 18:17，Ant Design GitHub Bot 写道：

Hello @LitaryVan. Please provide a re-producible demo: https://codepen.io/pen?template=LWpaKe&editors=0010

**Comment by paranoidjk** [comment]
trace https://github.com/ant-design/ant-design-mobile/issues/2350
