### ISSUE TITLE
Error message when import TabBar 

### ISSUE THREAD

**Issue by huang475** [ant-design/ant-design-mobile#216]
#### 本地环境

- antd-mobile 版本：0.8.1
- 操作系统及其版本：osx 10.11
- 浏览器及其版本：chrome

#### 你做了什么？

`import { TabBar } from 'ante-mobile';`
#### 你期待的结果是：
rock on

#### 实际上的结果：
error message Can't resolve 'react-native'

#### 可重现的在线演示

`ERROR in ./~/antd-mobile/lib/badge/style/index.js
Module not found: Error: Can't resolve 'react-native' in '*****/node_modules/antd-mobile/lib/badge/style'
 @ ./~/antd-mobile/lib/badge/style/index.js 7:19-42`

**Comment by huang475** [comment]
It's because the extensions configuration in the resolve part of webpack. `.web.js` should be at the front of `.js`.

**Comment by shanyu-e** [comment]
in v0.9.4.  there is still the same bug. i just want use it in web with meteor not wbpack. how can i use it.
