### ISSUE TITLE
RN project  use Picker component in android，the two Pickers is up-and-down ，I want they in  a line, it works in a line in IOS.

### ISSUE THREAD

**Issue by woshiqiang1** [ant-design/ant-design-mobile#2160]
![screenshot_1513134282](https://user-images.githubusercontent.com/26063561/33919775-8070ab68-dff5-11e7-8a19-247771159ead.png)

**Comment by woshiqiang1** [comment]
antd-mobile：1.6.5版本

**Comment by warmhug** [comment]
pls use antd-mobile 2.x.
1.x is out-of-date, we do not maintain it.
