### ISSUE TITLE
Picker support uncontrolled usage

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#2161]
## Problem

> https://github.com/ant-design/ant-design-mobile/blob/master/components/picker/AbstractPicker.tsx#L36

Right now get selected value always reading `props.value`. So if one just add `onChange` handler, not to change `props.value` at the same time, the displayed selected value  of `List.Item` will not be updated.

ref https://reactjs.org/docs/uncontrolled-components.html

**Comment by skidxjq** [comment]
放到feat中评估

**Comment by ziluo** [comment]
和 @paranoidjk 线下沟通了一下，暂时先不改，看后续社区是否有类似反馈
