### ISSUE TITLE
antd-mobile提示找不到react-dom

### ISSUE THREAD

**Issue by fangkyi03** [ant-design/ant-design-mobile#2162]
antd-mobile版本:2.1.1
rn版本0.43.3

![image](https://user-images.githubusercontent.com/30390014/33937242-a76b4398-e03d-11e7-8b53-283d97367591.png)

**Comment by laizhenhai88** [comment]
yarn add react-dom
or
npm i react-dom -S

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/issues/2168
