### ISSUE TITLE
Tabs组件纵向滚动的时候不会锁定方向

### ISSUE THREAD

**Issue by goodlau** [ant-design/ant-design-mobile#2163]
Tabs组件纵向滚动的时候不会锁定方向，导致纵向拖拽过程中，发生横向拖动会产生横向滑动效果
官方的演示demo，其中固定高度的tabs 可以将问题重现
https://mobile.ant.design/kitchen-sink/components/tabs?lang=zh-CN#tabs-demo-0
重现GIF图片动画
http://47.94.162.117/static/images/tabs.gif
当选中Second Tab，拖拽到最底部，然后从下向上右方向拖拽的时候会发现 First Tab 也显示出来了

**Comment by zhang740** [comment]
估计还是手势库那个问题， @paranoidjk
