### ISSUE TITLE
Modal.prompt default value cover the blank input value

### ISSUE THREAD

**Issue by moosePP** [ant-design/ant-design-mobile#2164]
Version  
2.1.1

Environment  
IOS

Steps to reproduce  
1. use Modal.prompt component, set defaultValue 100
`Modal.prompt(title, message, callbackOrActions, type?, defaultValue?, placeholders?, platform?)`
2. input blank value and press ok

What is expected?  
value in callbackOrActions is blank value('')

What is actually happening?  
value in callbackOrActions is 100

Note  
[source code](https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/prompt.tsx#L127)

**Comment by warmhug** [comment]
You're right, we have a problem before.
