### ISSUE TITLE
当datepicker 配合tabs 使用的时候，会存在穿透问题

### ISSUE THREAD

**Issue by goodlau** [ant-design/ant-design-mobile#2165]
当datepicker 配合tabs使用的时候，在datepicker 的遮罩层滑动，以及左右滑动datepicker区域会影响到 tabs

重现问题Gif动画
http://47.94.162.117/static/images/datepicker.gif

**Comment by wychl** [comment]
我也遇到类似的问题

**Comment by beyondxgb** [comment]
这问题解决了吗？我看现在还存在这个问题

**Comment by beyondxgb** [comment]
https://codepen.io/beyondxgb/pen/jvrVZQ this can reproduce the problem, you should preview it in mobile mode.
