### ISSUE TITLE
check inline style

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#2166]
web 平台不同于 native ，css 需要 被转换、加上 `-webkit-` 前缀等 来兼容 旧版本浏览器。
检查**所有组件的内联 css ，没必要使用内联的 都去掉、改为写在 less 文件里**

ref: 
https://github.com/ant-design/ant-design-mobile/commit/dbe8ce99bf1d18e3e68a0bba4c8d6907cc3c6e0f

https://github.com/ant-design/ant-design-mobile/blob/40dcbe0b7d054bf9eb20302a1e9ca1596be18c60/components/picker/AbstractPicker.tsx#L60

https://github.com/ant-design/ant-design-mobile/blob/40dcbe0b7d054bf9eb20302a1e9ca1596be18c60/components/picker/AbstractPicker.tsx#L143

**Comment by paranoidjk** [comment]
- [x] https://github.com/ant-design/ant-design-mobile/commit/dbe8ce99bf1d18e3e68a0bba4c8d6907cc3c6e0f
- [ ] https://github.com/react-component/m-cascader/blob/master/src/Cascader.tsx#L84 https://github.com/react-component/m-cascader/blob/master/assets/index.less#L9

**Comment by paranoidjk** [comment]
ref https://github.com/react-component/tabs/issues/65
