### ISSUE TITLE
can not found react-dom where expo publish

### ISSUE THREAD

**Issue by yuanzougaofei97** [ant-design/ant-design-mobile#2168]
### Version
undefined

### Environment
react-native expo

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
1.expo init {project}
2.expo install antd-mobile
3.use Carousel Grid ..
4.expo publish
5.show can not found react-dom error

### What is expected?
expo publish success

### What is actually happening?
show can not found react-dom error

**Comment by laizhenhai88** [comment]
yarn add react-dom
or
npm i react-dom -S

**Comment by paranoidjk** [comment]
antd-mobile 依赖 react/react-dom, 需要用户自己安装。

**Comment by DrakeXiang** [comment]
It should be mentioned in the readme...
