### ISSUE TITLE
Tabs的tabBarBackgroundColor属性在 react native 下无效

### ISSUE THREAD

**Issue by zhmeng** [ant-design/ant-design-mobile#2170]
### Version
2.1.1

### Environment
windows 10  "antd-mobile": "^2.1.1",     "react": "16.0.0-alpha.12",     "react-native": "^0.47.1",     

### Reproduction link
[https://gitee.com/ilkkzmz/finance.git](https://gitee.com/ilkkzmz/finance.git)

### Steps to reproduce
设置tab 的tabBarBackgroundColor 属性无法变色

### What is expected?
变为设置的颜色

### What is actually happening?
没有变颜色

**Comment by miniFrank** [comment]
i also met the same issue, anyone could help on this?

**Comment by zhang740** [comment]
upgrade rmc-tabs to 1.2.23
