### ISSUE TITLE
rn的List 中存在多余的边框

### ISSUE THREAD

**Issue by zim-lee** [ant-design/ant-design-mobile#2173]
### Version
2.1.1

### Environment
rn 0.50.3, antd-mobile 2.1.1

### Reproduction link
[http://oxr3qa4p3.bkt.clouddn.com/TIM-20171215123600.png](http://oxr3qa4p3.bkt.clouddn.com/TIM-20171215123600.png)

### Steps to reproduce
`Item`对应的`thumb`中放置足够大的图片，就会出现多余的边框，如截图:
![](http://oxr3qa4p3.bkt.clouddn.com/TIM-20171215123600.png)

### What is expected?
没有边框

### What is actually happening?
有边框

**Comment by warmhug** [comment]
自己覆盖样式吧，ref #1853 6ab912f9e1978ea6b7ea675f03970d1c66df897f
