### ISSUE TITLE
Carousel infinity&selectedIndex prop display error in rn Android

### ISSUE THREAD

**Issue by xiaocjin** [ant-design/ant-design-mobile#2174]
### Version
2.1.1

### Environment
react-native 0.49、0.50

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo](https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo)

### Steps to reproduce
1、use expo open antdm demo
2、delete component Carousel‘s  autoplay prop
3、run app on andrind
4、if set infinity prop, it will show the last view. if delete infinity prop,  it will show the first view, selectedIndex is not work
5、in all cases, the active dot is on the right place

### What is expected?
show the right view

### What is actually happening?
if set infinity prop, it will show the last view. if delete infinity prop,  it will show the first view

---
ios is fine

**Comment by zetaoWu** [comment]
+1

**Comment by shuicheng** [comment]
我这也是 infinite 功能不正常，不知道什么时候能修复？

**Comment by warmhug** [comment]
Very Sorry, `Carousel` component is very complicated, we don't have time to do better, so recommend to find other better `Carousel` component.
Of course, if you are willing to help us do it well, then please have a pr in https://github.com/ant-design/ant-design-mobile-rn
