### ISSUE TITLE
Uncaught TypeError: Cannot set property 'linkedInput' of null

### ISSUE THREAD

**Issue by icodytan** [ant-design/ant-design-mobile#2175]
### Version
2.1.1

### Environment
react 16.2.0, antd-mobile 2.1.1

### Reproduction link
[https://github.com/xiaochunyong/antd-mobile-issue](https://github.com/xiaochunyong/antd-mobile-issue)

### Steps to reproduce
`git clone https://github.com/xiaochunyong/antd-mobile-issue`

Change `package.json` `"antd-mobile": "^2.0.3"` → `"antd-mobile": "^2.1.1"`

`yarn`

`yarn start`

Input `额度` and click `确认`

Back `首页`

Input `额度`  again and it appears

### What is expected?
No error

### What is actually happening?
Error:

`Uncaught TypeError: Cannot set property 'linkedInput' of null`

`The above error occurred in the <NumberInput> component`

---
Once appeared in [#2040](https://github.com/ant-design/ant-design-mobile/issues/2040) and dealt with, but now in another case also appeared

**Comment by sundayha** [comment]
同样的问题

**Comment by warmhug** [comment]
@icodytan 你的 GitHub demo，怎么返回不了？没法重现

**Comment by zhangfengrui** [comment]
the same question, how to resolve it. Thank u

**Comment by zhangfengrui** [comment]
the same question, how to resolve it. Thank u!  @ant-design-bot

**Comment by zhangfengrui** [comment]
the same question, how to resolve it. Thank u! @ant-design-bot

**Comment by icodytan** [comment]
@warmhug 在浏览器的话，直接使用浏览器的返回键

**Comment by paranoidjk** [comment]
Same problem with https://github.com/ant-design/ant-design-mobile/issues/2207, please trace #2207
