### ISSUE TITLE
Modal\prompt, hard to focus, no cursor on ios11

### ISSUE THREAD

**Issue by MarvinXu** [ant-design/ant-design-mobile#2177]
### Version
2.1.2

### Environment
ios11.1.2、wechat6.6.0

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/modal](https://mobile.ant.design/kitchen-sink/components/modal)

### Steps to reproduce
Click Prompt->promise，tap the input，this is no cursor even when keyboard pops up

### What is expected?
easy to focus & show cursor

### What is actually happening?
hard to focus (usually needs serveral taps) & no cursor

**Comment by warmhug** [comment]
ref #1857

**Comment by yesmeck** [comment]
https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8

**Comment by paranoidjk** [comment]
seems webkit is very closed to fix this bug https://bugs.webkit.org/show_bug.cgi?id=176896

**Comment by whhlulu** [comment]
solved the problem?
Click Prompt->promise，tap the input，this is no cursor even when keyboard pops up

**Comment by whhlulu** [comment]
线上使用2.1.3，IOS上面还是不太好点，这个问题有什么备用方案解决吗

**Comment by zmayor** [comment]
有解决方案了吗..

**Comment by koupeng** [comment]
我这里是长按才能显示焦点！！！

**Comment by whhlulu** [comment]
在ios上面，Modal、prompt在2.1.3的时候不容易获取焦点，我就利用alert自己写TextareaItem，这样可以获取焦点，但是输入多行后不能修改焦点，不能滚动
事例：https://codepen.io/anon/pen/OQNdor

**Comment by koupeng** [comment]
@warmhug  人工点击下确定就能获取到焦点了。能不能通过模拟人工点击事件，先解决掉这个问题?

**Comment by quentinyang** [comment]
Fixed. Auto focus when clicking input. #2560
