### ISSUE TITLE
get error: TypeError: Cannot read property 'Item' of undefined

### ISSUE THREAD

**Issue by gzlinjialong** [ant-design/ant-design-mobile#2178]
I do not use the label, but use typescript change to es5 instead.

When I Use the follow code:
`
import List from 'antd-mobile/lib/list';

import 'antd-mobile/lib/list/style/css';

<List>....
   <List.Item>...</List.Item>
</List>
`
webpack build is not error. but when run, get the error:
get error: TypeError: Cannot read property 'Item' of undefined

**Comment by warmhug** [comment]
@ant-design-bot demo

**Comment by gzlinjialong** [comment]
the code an result
`
import * as React from 'react';
import { Component } from 'react'
import { render } from 'react-dom';
import List from 'antd-mobile/lib/list';
import 'antd-mobile/lib/list/style/css';


class Test extends React.Component<any, any>{
    constructor(props, context) {
        super(props, context);
    }
    render() {
        return (
            <div>
                <List>
                    <List.Item>test</List.Item>
                </List>
            </div>);
    }
}

render(< Test />, document.getElementById('root'));
`
![1](https://user-images.githubusercontent.com/30472606/34197588-237c18c2-e5a2-11e7-9680-616a5a07283b.png)

**Comment by gzlinjialong** [comment]
I think, maybe something with TypeScript.
when i use 
```
import { List } from 'antd-mobile';
```
compiler the follow code, is no problem. 
```
React.createElement(list_1, null,
                React.createElement(list_1.Item, null, "test"))));
```
when is use 
```
import List from 'antd-mobile/lib/list';
```
compiler the fllow code. has a error
```
            React.createElement(list_1.default, null,
                React.createElement(list_1.default.Item, null, "test"))));
···

**Comment by warmhug** [comment]
Please delete the code above. And gzip your project, upload it here.

**Comment by gzlinjialong** [comment]
I think that's pretty clear, right?
When TypeScript translate tsx to js(es5), there are different.

import { List } from 'antd-mobile';
compiler the follow code, is no problem.
React.createElement(list_1, null,
                React.createElement(list_1.Item, null, "test"))));
when use
import List from 'antd-mobile/lib/list';
compiler the fllow code. has a error
            React.createElement(list_1.default, null,
                React.createElement(list_1.default.Item, null, "test"))));
···

**Comment by paranoidjk** [comment]
https://unpkg.com/antd-mobile@2.1.3/lib/list/index.js

I think it should works fine, please give a reproducible demo, you can push your code to github and give us the link.

And you may see https://github.com/ant-design/antd-mobile-samples/tree/master/web-typescript as a example with typescript.
