### ISSUE TITLE
官方demo 在UC 浏览器下的兼容问题

### ISSUE THREAD

**Issue by NaughtBoy** [ant-design/ant-design-mobile#2179]
### Version
2.1.2

### Environment
华为手机（HUAWEI NXT-AL10）浏览器（v10.7.5.4070，内核是UC 浏览器）、UC 浏览器（v11.8.1.961）

### Reproduction link
[https://mobile.ant.design/kitchen-sink/](https://mobile.ant.design/kitchen-sink/)

### Steps to reproduce
1.在上述浏览器中打开官方demo ；
2.打开自己写的demo （包含Grid） 。

### What is expected?
在上述浏览器中能正常浏览官方demo；在UC 浏览器中使用Grid 组件能正常显示边框。

### What is actually happening?
1.打开官方demo 的时候一片空白，只有标题，而微信浏览器、QQ 浏览器、chrome 等可以正常显示；
2.打开自己的demo，组件Grid 在上述浏览器中显示的时候没法显示Item 的边框，而在chrome 、微信浏览器等可以显示出边框。

**Comment by paranoidjk** [comment]
duplicated with https://github.com/ant-design/ant-design-mobile/issues/2183
