### ISSUE TITLE
DatePicker 使用了onChange后，日期显示不正确

### ISSUE THREAD

**Issue by squallzhou** [ant-design/ant-design-mobile#218]
antd-mobile 版本：0.8.0
操作系统及其版本：macOS10.11.6
浏览器及其版本：chrome 52.0
你做了什么？

引入 antd-mobile 的 DatePicker，可以正常使用DatePicker选择日期，然后我使用onChange事件，想在日期选择后，给一个外部的变量赋值，如下图所示
![image](https://cloud.githubusercontent.com/assets/11225093/18231553/c263cb1a-72ee-11e6-9d64-31144deacbcf.png)

这样值是赋进去了，但是外面显示的日期lable 没有变化，而且好像没有办法对日期做格式化
![image](https://cloud.githubusercontent.com/assets/11225093/18231556/2188aeee-72ef-11e6-8f46-ad74a504ecbc.png)
确定后，
![image](https://cloud.githubusercontent.com/assets/11225093/18231562/30227e1c-72ef-11e6-8dbd-1ca35c0c0926.png)
![image](https://cloud.githubusercontent.com/assets/11225093/18231571/48e774de-72ef-11e6-9982-548240df1770.png)

你期待的结果是：

请选择那里应该变成我选中的日期

实际上的结果：

请选择那里没有任何变化，但是如果没有用onchange，一切正常

**Comment by silentcloud** [comment]
外面的 label 要做成一个 state，日期格式是 moment 类型，参见文档 

@squallzhou

**Comment by squallzhou** [comment]
文档上，就是没有怎么获取日期的代码实例呀。
<DatePicker onChange={function(e){alert(e)}} mode="date" {...getFieldProps('date')} >
      <List.Item arrow="horizontal">生日</List.Item>
</DatePicker>
现在问题就是，这样写onChange里的方法就不执行了。

这样写，就可以执行onChange里的方法，但是label的值不变了
<DatePicker mode="date" {...getFieldProps('date')} onChange={function(e){alert(e)}}>
      <List.Item arrow="horizontal">生日</List.Item>
</DatePicker>

**Comment by squallzhou** [comment]
知道了，要这样写,看了 (rc-form 文档)
<DatePicker mode="date" {...getFieldProps('date',{ onChange(e){ alert(e)}})}>
      <List.Item arrow="horizontal">生日</List.Item>
</DatePicker>

**Comment by squallzhou** [comment]
格式化一下，好了
```
<DatePicker mode="date" {...getFieldProps('date',{ onChange(e){ alert(moment(e).format('YYYY-MM-DD'))}})}>
            <List.Item arrow="horizontal">生日</List.Item>
 </DatePicker>
```

开发文档上最好把这个如果获取日期的内容补上去，不然新手使用很痛苦啊。。

**Comment by yiminghe** [comment]
不是用 onChange 获取的，学习 http://react-component.github.io/form/

**Comment by squallzhou** [comment]
嗯，是的，看了rc-form 文档，可以了
