### ISSUE TITLE
Upgrade next.js demo to antd-mobile@2

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#2181]
https://github.com/zeit/next.js/tree/canary/examples/with-antd-mobile

**Comment by thengor** [comment]
The demo loads the antd-mobile.min.css in _document.js.
`
<link rel='stylesheet' type='text/css' href='//unpkg.com/antd-mobile/dist/antd-mobile.min.css' />
`
 I wonder if there is a way to use modularized antd-mobile ?

I have tried, but I got the same error as [2287](https://github.com/ant-design/ant-design-mobile/issues/2287)

**Comment by code-coder** [comment]
Same problem！
When I was going to customize the antd-mobile theme.
```
You may need an appropriate loader to handle this file type.
|  */
|
> html {
|   line-height: 1.15; /* 1 */
|   -ms-text-size-adjust: 100%; /* 2 */

 @ ./node_modules/antd-mobile/lib/style/index.js 3:0-38
 @ ./node_modules/antd-mobile/lib/button/style/index.js
 @ ./pages/index.js
 @ multi ./pages/index.js
```
