### ISSUE TITLE
SegmentedControl 分段器在iOS上不能正常点击

### ISSUE THREAD

**Issue by LYBpig** [ant-design/ant-design-mobile#2182]

**Comment by scyankai** [comment]
我也遇到这样的问题，发现是SegmentedControl依赖的rmc-feedback的events引起的，每次点击rmc-feedback能triggerEvent，但是SegmentedControl无法触发click事件。我是在ios的微信浏览器中遇到这样的问题，原因不详！

**Comment by sundayha** [comment]
@paranoidjk  我也是这个问题 @scyankai

**Comment by sundayha** [comment]
@scyankai 兄弟你那现在好使了吗

**Comment by sundayha** [comment]
@paranoidjk 
```
系统环境：
IOS： 10.3.2(14F89)
iPhone：微信浏览器
iPhone：Safari浏览器
```
```
包版本：
"antd-mobile": "^2.0.3",
"react": "^16.0.0",
"react-dom": "^16.0.0",
```

```
问题代码：
<SegmentedControl values={['a, 'b']} onValueChange={this.onValueChange} />
```
#### 问题描述：
在iPhone下的Safari，分段器失效。在iPhone下的微信中访问分段器失效。安卓的可以正常使用。还有组件popover点击蒙板后无动作，不自动隐藏。同样安卓的可以正常使用。

**Comment by xfrogcn** [comment]
遇到相同问题.....官方是否有解决计划？？？

**Comment by xfrogcn** [comment]
临时解决方案：
覆盖样式：
.am-segment-item-inner{
    position: absolute;
    width: 100%;
    height: 100%;
    background-color: transparent;
}

**Comment by ajjing** [comment]
@xfrogcn Thanks,worked for me.

**Comment by warmhug** [comment]
Use `fastclick`

**Comment by modao** [comment]
You should import fastclick as the [official guide](https://mobile.ant.design/docs/react/introduce-cn#3.-%E4%BD%BF%E7%94%A8).
