### ISSUE TITLE
使用钉钉安卓客户端无法预览

### ISSUE THREAD

**Issue by linjianzao** [ant-design/ant-design-mobile#2183]
### Version
2.1.2

### Environment
荣耀V8、安卓7.0

### Reproduction link
[https://mobile.ant.design/index-cn](https://mobile.ant.design/index-cn)

### Steps to reproduce
使用钉钉客户端 在 https://mobile.ant.design/index-cn  扫二维码预览。

### What is expected?
可正常预览

### What is actually happening?
远程调试报错 Uncaught SyntaxError: Use of const in strict mode.

**Comment by paranoidjk** [comment]
https://github.com/babel/babel/issues/7054

**Comment by linjianzao** [comment]
官网的二维码无法用安卓预览。 不是我自己的代码。
