### ISSUE TITLE
Calendar can not select the past date

### ISSUE THREAD

**Issue by gzlinjialong** [ant-design/ant-design-mobile#2184]
Version:
2.1.1
I can not select the past date.

不能选择过去的日期，最小的日期是本月日期。

**Comment by zhang740** [comment]
下拉加载上一月

**Comment by gzlinjialong** [comment]
谢谢，在手机端测试可以下拉加载上一个月。chrome没有测试出来（汗）。
不过，这种操作还是有点慢，上拉快很多。
