### ISSUE TITLE
InputItem type 'number' overridden by 'text' 

### ISSUE THREAD

**Issue by MaronMariusz** [ant-design/ant-design-mobile#2186]
### Version
2.1.2

### Environment
Android 7, chrome 61.0.3

### Reproduction link
[https://codepen.io/anon/pen/dJXpbd](https://codepen.io/anon/pen/dJXpbd)

### Steps to reproduce
Just use `<InputItem type="number">`

### What is expected?
`<input type="number" />` instead of `<input type="text" />`

### What is actually happening?
Type 'number' is not passed to type attribute in rendered input. Input is rendered as input:text with pattern for numbers. It prevents me to use numeric keyboard (native one) while using phone. Do we have some workaround that allow me to use InputItem component and have numeric native keyboard on my phone while passing number ?

**Comment by warmhug** [comment]
I'm sorry for the late reply. Just use `<InputItem type="digit">`, it's native `<input type="number" />`.
