### ISSUE TITLE
拉动刷新和滑动操作相互冲突

### ISSUE THREAD

**Issue by duankt** [ant-design/ant-design-mobile#2188]
我再列表中加上滑动操作了，使用没有问题，然后我给列表增加拉动刷新，拉动刷新没有问题，但是滑动操作就不能使用啦

**Comment by warmhug** [comment]
请按 issue 模板填写详细内容！
另外查看这里 https://github.com/ant-design/antd-mobile-samples/tree/master/web-webpack3 的 demo 有没有同样的问题？

**Comment by duankt** [comment]
升级到 rmc-pull-to-refresh@1.0.7
