### ISSUE TITLE
When Stepper is synchronously refreshing, there is an autoregressive minimum.

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-design-mobile#2189]
### Version
2.1.2

### Environment
win10，chrom

### Reproduction link
[https://codepen.io/anon/pen/WdxqLP?editors=0010](https://codepen.io/anon/pen/WdxqLP?editors=0010)

### Steps to reproduce
1. click on the first Stepper +, and the two Stepper increases synchronously.
2. click second Stepper - until the minimum, two Stepper synchronization decreases.
3. again click on the first Stepper +, and it will eventually automatically return to the minimum value, no matter how many times.
4. at this time, click on second Stepper +, but it can increase in normal synchronism

### What is expected?
Normal update of Stepper value

### What is actually happening?
Autoregressive minimum value

**Comment by paranoidjk** [comment]
may be related with https://github.com/ant-design/ant-design-mobile/issues/2350
