### ISSUE TITLE
DatePicker 问题

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#219]
![image](https://cloud.githubusercontent.com/assets/1698185/18236860/6836edb0-735d-11e6-8236-26e2f986a946.png)

- div extra prop  
- className 没有透传
- 跟 rc-from 绑定太紧，离开 rc-form 没办法设置 `initialValue`

**Comment by warmhug** [comment]
用 value 设置 initialValue ，可脱离 rc-form 的，见 demo
