### ISSUE TITLE
ListView.DataSource的rowHasChanged：(row1, row2) => row1.total_count !== row2.total_count

### ISSUE THREAD

**Issue by dongodngtang** [ant-design/ant-design-mobile#2190]
ListView.DataSource的rowHasChanged：(row1, row2) => row1.total_count !== row2.total_count

数据变化了，但是没有更新，怎么处理才能更新呢。Web端React H5

**Comment by warmhug** [comment]
为什么用 total_count 比较？

**Comment by dongodngtang** [comment]
就是total_count变化啦，又出现一个新问题，build 后ListView数据加载不出来

**Comment by warmhug** [comment]
最好拿 rowId 来比较。ListView数据加载不出来、要确定能触发加载数据的条件。
