### ISSUE TITLE
按照官方文档步骤，无法做到按需加载

### ISSUE THREAD

**Issue by macmatilda** [ant-design/ant-design-mobile#2191]
### Version
2.1.2

### Environment
不涉及

### Reproduction link
[https://mobile.ant.design/docs/react/introduce-cn](https://mobile.ant.design/docs/react/introduce-cn)

### Steps to reproduce
https://mobile.ant.design/docs/react/introduce-cn
 按照官方步骤，配置按需加载，不生效

### What is expected?
按需加载组件

### What is actually happening?
加载了全部的antd-mobile组件。
说明：
官方项目的配置是可以按需加载的，
https://github.com/ant-design/antd-mobile-samples/blob/master/create-react-app/config-overrides.js
所以，文档应该是少写了一部分东西。

另外，文档很乱，跳来跳去的，写一个helloworld竟然也如此麻烦，实在是无语。

**Comment by gzlinjialong** [comment]
我没有使用babel，直接使用typescript翻译为ES5，也是无法按需加载，生成的js最小也有400kb（react没有打包进来）。
然后我手工加载 
```
import List from 'antd-mobile/lib/list';
```
会报错：TypeError: Cannot read property 'Item' of undefined

**Comment by macmatilda** [comment]
我直接测试官方demo的App.js，里面就import { Button, Icon } from 'antd-mobile';
直接跑官方的demo貌似是300多k，
但是如果不跑官方demo，按照官方的步骤，一步一步来，是800多k，崩溃啊

**Comment by macmatilda** [comment]
算了，其实是我死较真，直接引入单个组件也蛮好的。
import List from 'antd-mobile/lib/list';

**Comment by gzlinjialong** [comment]
直接用 import List from 'antd-mobile/lib/list';
在使用List.item的时候，不会出错吗？

**Comment by warmhug** [comment]
按需加载 跟 Environment 有关系的，要注明。
关于 ts 下的按需加载 demo https://github.com/ant-design/antd-mobile-samples/tree/master/web-typescript 如果需要 随后会做更新。

**Comment by zhang740** [comment]
按需加载的原理是使用 import 的情况下做的优化，你tsconfig的编译配置是什么？commonjs之类生成的是require的形式是无法优化的 @macmatilda

**Comment by w1505615755** [comment]
按照官方文档上的步骤来，一直是报错
Unable to resolve antd-mobile/lib/button" from "./H:\\代码\\test\\App.js"
试了各种方法都没有成功，求解
