### ISSUE TITLE
InputItem（type="phone"]）输入号码第5位时光标会移到第4数字前（测试机型：oneplus5） 

### ISSUE THREAD

**Issue by X-sirs** [ant-design/ant-design-mobile#2193]
issue：测试机型oneplus5在InputItem（type="phone"]）输入号码第5位时光标会移到第4数字前导致输入顺序错乱
<InputItem   type="phone"  placeholder = "input your phonenumber" 
                                { ...getFieldProps('phoneNumber', {
                                    rules: [{
                                        required: true
                                    }]
                                })
                                }
                                error = {this.state.phoneNumber}
                                onErrorClick = {() => _this.handleError("phoneNumber")} >
                                TEL:
</InputItem>

**Comment by paranoidjk** [comment]
@ant-design-bot markdown

**Comment by paranoidjk** [comment]
没有这个测试机型，能否帮忙排查？

另外请先确认 https://mobile.ant.design/components/input-item-cn/ 是否ok。

**Comment by micooz** [comment]
此问题已修复至 master，请等待下个版本发布。

Refs: #2532 #2537
