### ISSUE TITLE
icon of the Navbar cannot Setup size

### ISSUE THREAD

**Issue by LeeeKevin** [ant-design/ant-design-mobile#2194]
### Version
2.1.2

### Environment
win7 chrome63 antd-mobile1.0.6

### Reproduction link
[https://mobile.ant.design/components/nav-bar-cn/](https://mobile.ant.design/components/nav-bar-cn/)

### Steps to reproduce
<NavBar
     mode="light"
     icon={<Icon type="left" size='xs' />}
     onLeftClick={() => {window.location.href = `${this.returnUrl}`}}
>公司管理</NavBar>
icon设置size属性无效

### What is expected?
Icon maximun

### What is actually happening?
Icon unchanged

**Comment by LeeeKevin** [comment]
<NavBar
            mode="light"
            icon={<Icon type="left" size='xs' />}
            onLeftClick={() => {window.location.href = `${this.returnUrl}`}}
          >公司管理</NavBar>

**Comment by LeeeKevin** [comment]
<NavBar
            mode="light"
            icon={"<Icon type="left" size='xs' />"}
            onLeftClick={() => {window.location.href = `${this.returnUrl}`}}
          >公司管理</NavBar>

**Comment by LeeeKevin** [comment]
<NavBar
            mode="light"
            icon={'<'Icon type="left" size='xs' /'>'}
            onLeftClick={() => {window.location.href = `${this.returnUrl}`}}
          >公司管理</NavBar>

**Comment by warmhug** [comment]
1.x 没有 icon 属性，确保 antd-mobile 是 2.x
