### ISSUE TITLE
官方示例Tabs.TabPane提示Unresolved variable Tabs.TabPane

### ISSUE THREAD

**Issue by hleluo** [ant-design/ant-design-mobile#2195]
`import React from "react";
import {NoticeBar, Tabs} from "antd-mobile";

const TabPane = Tabs.TabPane;

class Home extends React.Component {

    state = {
        tabPanes: [{
            type: "comedy",
            name: "喜剧"
        }]
    };

    onTabChanged = (key) => {

    };

    render() {
        return (
            <Tabs defaultActiveKey="1" animated={false} onChange={this.onTabChanged}>
                <TabPane tab="选项卡一" key="1">
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
                        选项卡一内容
                    </div>
                </TabPane>
                <TabPane tab="选项卡二" key="2">
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
                        选项卡二内容
                    </div>
                </TabPane>
                <TabPane tab="选项卡三" key="3">
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
                        选项卡三内容
                    </div>
                </TabPane>
            </Tabs>
        );
    };

}

export default Home;`

antd-mobile版本2.1.2 
用官方示例写了一个简单的标签页，Tabs.TabPane提示Unresolved variable Tabs.TabPane错误。
浏览器运行报错：
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by zhang740** [comment]
哪里看到的示例？https://mobile.ant.design/components/tabs-cn/
