### ISSUE TITLE
Has any plan to provide Ant Design Mobile of Angular?

### ISSUE THREAD

**Issue by izee** [ant-design/ant-design-mobile#2197]
### What problem does this feature solve?
none

### What does the proposed API look like?
none

**Comment by zhaxi** [comment]
@izee Yes，we have angular version inside alibaba group，and we will contribute it to the github after fulled tested.

**Comment by icycore** [comment]
We plan to use ant design mobile in our project,it's realy nice! 
We need the angular version.
Do you guys have a roadmap to relrease it?
Waiting for your replay, thanks

**Comment by fisherspy** [comment]
> ### What problem does this feature solve?
> none
> 
> ### What does the proposed API look like?
> none

Ant Design Mobile of Angular has been released. Website: ng.mobile.ant.design

**Comment by fisherspy** [comment]
> We plan to use ant design mobile in our project,it's realy nice!
> We need the angular version.
> Do you guys have a roadmap to relrease it?
> Waiting for your replay, thanks

Ant Design Mobile of Angular has been released. Website: ng.mobile.ant.design
