### ISSUE TITLE
ListView的下拉刷新属性放开后，同一组件中的onTouchStart事件就不能触发

### ISSUE THREAD

**Issue by duankt** [ant-design/ant-design-mobile#2199]
ListView的下拉刷新属性放开后，同一组件中的onTouchStart事件就不能触发

**Comment by duankt** [comment]
var Events = {
        onTouchStart : this.onTouchStart.bind(obj.states, obj.id),
        onTouchMove :this.onTouchMove.bind(),
        onTouchEnd : this.onTouchEnd.bind( obj.id)
    }
      return (
      // <SwipeAction style={{ backgroundColor: 'gray' }} autoClose
      // right={[ 
      //   { text: 'Delete', onPress: () => 
      //   deleteapplay(rowID), 
      //   style: { backgroundColor: '#F4333C', color: 'white' }, },
      //  ]}>
        <div  key={rowID} {...Events} style={{ padding: '0 15px' }}>

        <div style={{ lineHeight: '45px', color: '', borderBottom: '1px solid #F6F6F6' }} >
          <Flex>
              <Flex.Item  style={{fontWeight: 'bold', fontSize: 18}}>{obj.requestName}</Flex.Item>
              {obj.states===0&&<Flex.Item style={{fontWeight: 'bold',textAlign:'right',color:'coral'}}>保存</Flex.Item>}
              {obj.states===1&&<Flex.Item style={{fontWeight: 'bold',textAlign:'right',color:'#108ee9'}}>审批中</Flex.Item>}
              {obj.states===2&&<Flex.Item style={{fontWeight: 'bold',textAlign:'right',color:'green'}}>审批通过</Flex.Item>}
              {obj.states===-2&&<Flex.Item style={{fontWeight: 'bold',textAlign:'right',color:'red'}}>已驳回</Flex.Item>}
          </Flex>
        </div>

        <div style={{ }}>
          <Flex>
          <Flex.Item style={{width:'70%',flex:'3'}}>
          <div style={{ display: '-webkit-box',  padding: '15px 0',flex:'10' }}>
            <Time value={obj.appDate} format="YYYY-MM-DD"/><span>&nbsp;</span>
            由<span style={{color:'#108ee9'}}>&nbsp;{ obj.applicantPerson }&nbsp;</span>申请
          </div>
            </Flex.Item>
            <Flex.Item style={{textAlign:'right', width:'30%'}}>
              ¥ 2800
            </Flex.Item>
          </Flex>
        </div>
        </div>
      // </SwipeAction>
      );
    };
    return (
           <ListView ref={el => this.lv = el} dataSource={this.state.dataSource} 
        //renderHeader={() => <span  style={{height:'5px'}}></span>}
        renderFooter={() => (<div style={{ padding: 30, textAlign: 'center' }}> {this.state.isLoading ? '正在加载...' : '加载完成'} </div>)}
        //renderSectionHeader={sectionData => (<div>{`Task ${sectionData.split(' ')[1]}`}</div>)}
        //renderBodyComponent={() => <MyBody />} 
        pullToRefresh={<PullToRefresh refreshing={this.state.refreshing} onRefresh={this.onRefresh}/>}
        renderRow={row} 
        renderSeparator={separator} 
        style={{ height: this.state.height,  overflow: 'auto',backgroundColor: '#F5F5F9',marginTop:'5px'}}
        pageSize={4} 
        onScroll={() => { console.log('scroll'); }} scrollRenderAheadDistance={500} 
        onEndReached={this.onEndReached} onEndReachedThreshold={10}
      />
    );
  }
}

**Comment by houankun** [comment]
我也遇到了，PullToRefresh组件的子组件，在ios上需要点击两次，一点都不流畅，同时子组件的onTouchStart事件不触发

**Comment by warmhug** [comment]
ref https://github.com/ant-design/ant-design-mobile/issues/2141#issuecomment-352638692
