### ISSUE TITLE
0.8

### ISSUE THREAD

**Issue by liqi07** [ant-design/ant-design-mobile#22]
### 计划 
- dealine `8月26日` 
- 发布时间 `8月31日`

### 样式
- [ ] https://github.com/ant-design/ant-design-mobile/issues/18  @ all

### RN组件    
- [x] checkbox @linfaxin @pingan1927 
- [x] radio @linfaxin @pingan1927 
- [x] Tabs @silentcloud 
- ~~- Tooltip @silentcloud~~
- [x] Steps @liqi07
- [x] Carousel @foriacus
- [ ] Grid @benjycui
- [ ] Menu @afc163 
- [x] SearchBar @afc163 
- [x] SegmentedControl @silentcloud
- [x] TabBar @silentcloud

### web组件  
- ~~Menu增加`勾选图标位置/selectIconPosition`、`对齐/align` (gitlab 114)  @pingan1927 新的视觉稿暂时没有这样的配置~~
- [x] InputItem配置项及样式优化(gitlab 113) @pingan1927 
- [x] Tabs 拆分为 SegmentedControl、TabBar、Tabs @silentcloud

### website  
 - [x] 网站改造、遗留问题优化 @liqi07 
 
### 测试反馈
- [x] Uploader建议优化 (gitlab 136)  @pingan1927  
- APIS样式问题 （gitlab 208)
   - [x] ~~ActionSheet 动作面板 @warmhug (invalid)~~
   - [x] ~~Dropdown 下拉菜单 @warmhug~~
   - [x] Modal 对话框 @silentcloud 
   - [x] Toast 轻提示 @silentcloud 
   
### 0.7遗留  
- [x] rn 框架(router ScrollView) 导致部分组件demo无法工作(RefreshControl/Drawer) @silentcloud

**Comment by silentcloud** [comment]
Tooltip 移除，详见 https://github.com/ant-design/ant-design-mobile/issues/50

**Comment by warmhug** [comment]
website 的工作量还是比较大的、另外涉及到 navbar 与具体组件交互细节问题还是比较多。 @liqi07 可以尽早开始做？做好后一起 review 下

**Comment by liqi07** [comment]
@warmhug website目前已在进行中，预计下周搞定主要调整，后续调整细节

**Comment by afc163** [comment]
Menu rn 移到 1.0 。

**Comment by qiuchengw** [comment]
严重期待今天的发布，我就可以去掉很多其它的依赖了！鼓掌！辛苦各位了！

**Comment by qiuchengw** [comment]
貌似今天不能发布0.8了么？这个版本推迟到哪天发布有确切的时间没？

**Comment by silentcloud** [comment]
@qiuchengw 昨晚已经发了，感谢关注
