### ISSUE TITLE
List / ListItem 修改建议

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#220]
### 功能缺失
- 目前只有`最左/最右`结构，正常情景应该是`左中右`都要有、并且像其中的`左中、中右、左右`形式都支持。
- listItem 的之间的分割线 divider、目前只有一种这样的 
  ![image](https://cloud.githubusercontent.com/assets/2011119/18252345/c42ac93a-73c0-11e6-8b67-c80aba49d668.png)
  ， 希望支持 longdivider 和 nodivider (Material Design)  

参考：https://onsen.io/v2/docs/js/ons-list-item.html#modifiers
### API 修改建议
- thumb =》 avatar
- extra =》 secondary （并支持多个）
- List.Item.Brief 去掉
- align 为什么不直接用 flex 的 align-items 及其值？

参考：https://material.angularjs.org/latest/api/directive/mdListItem

**Comment by pingan1927** [comment]
之前有个issues专门讨论这个List API https://github.com/ant-design/ant-design-mobile/issues/63

> thumb =》 avatar

这个需要好好调研下。

> extra =》 secondary （并支持多个） List.Item.Brief 去掉

这两个暂时不动，改起来伤筋动骨

> align 为什么不直接用 flex 的 align-items 及其值？

简化，更易理解。

**Comment by pingan1927** [comment]
目前整个支付宝的客户端基本上都只有左右结构，设计稿也只提供这样的。个人认为没有必要搞得大而全。

`divider`可以好好考虑

**Comment by warmhug** [comment]
左中右 结构，正是来自支付宝里新的业务需求

**Comment by pingan1927** [comment]
先跟视觉反馈给出基准的视觉稿吧。

**Comment by chenqizheng** [comment]
希望能有左中右，像其中的左中、中右、左右形式都支持。比如多选列表或者单选列表都有可能用得到。

**Comment by warmhug** [comment]
`divider可以好好考虑` 考虑好了吗？ 现在的 list 功能真不完善

**Comment by pingan1927** [comment]
@warmhug 先跟设计师提啊。

**Comment by motorguo** [comment]
建议给 `List` 加个控制  点击反馈的。
[验证表单 =>  确认信息/预定人数](https://mobile.ant.design/components/list/)
其实点击的是上面的元素， 这时整个 `List` 应该不需要有反馈。

**Comment by warmhug** [comment]
@motorguo 本来是添加 onClick 后的 list item 上才有点击反馈，现在这算是 bug ，下个版本修复

**Comment by motorguo** [comment]
@warmhug 印象中，我在 `v0.9.4` 还是 `0.9.5` 用的时候，当时不加 `onClick` 是不会有的。
