### ISSUE TITLE
modal组件罩着层下的页面会有滚动

### ISSUE THREAD

**Issue by renijianxiao** [ant-design/ant-design-mobile#2202]
### Version
2.1.1

### Environment
浏览器

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/issues/2201](https://github.com/ant-design/ant-design-mobile/issues/2201)

### Steps to reproduce
无

### What is expected?
modal组件罩着层下的页面不会滚动，有遮罩层禁止页面滚动

### What is actually happening?
modal组件罩着层下的页面会有滚动

**Comment by warmhug** [comment]
为什么不看 demo 怎么写呢？

**Comment by paranoidjk** [comment]
官方 demo 正常。https://mobile.ant.design/components/modal-cn/
