### ISSUE TITLE
pullToRefresh组件360手机N5S 适配问题

### ISSUE THREAD

**Issue by wendesun** [ant-design/ant-design-mobile#2208]
const hei = this.state.height - ReactDOM.findDOMNode(this.lv).offsetTop;
bug：ReactDOM.findDOMNode(this.lv).offsetTop   value=0； 
how to solve it ?

**Comment by warmhug** [comment]
在 360 1605-A01 360浏览器上没有重现。
没有你这个设备，希望能帮忙排查原因，谢谢！
