### ISSUE TITLE
antd的list组件引用报错

### ISSUE THREAD

**Issue by xupengfei2061** [ant-design/ant-design-mobile#2209]
ERROR in ./src/com/efounder/react/mainview/message/Message.jsx
Module not found: Error: Can't resolve 'antd/lib/list' in 'C:\Users\doudou\Desktop\react\react_demo\src\com\efounder\react\mainview\message'
 @ ./src/com/efounder/react/mainview/message/Message.jsx 11:12-36
 @ ./src/com/efounder/react/mainview/MainForm.jsx
 @ ./src/com/efounder/react/router/routes.jsx
 @ ./src/index.jsx
 @ multi ./~/_webpack-dev-server@2.9.7@webpack-dev-server/client?http://localhost:9000 ./src/index.jsx

ERROR in ./src/com/efounder/react/mainview/message/Message.jsx
Module not found: Error: Can't resolve 'antd/lib/list/style' in 'C:\Users\doudou\Desktop\react\react_demo\src\com\efounder\react\mainview\message'
 @ ./src/com/efounder/react/mainview/message/Message.jsx 45:0-30
 @ ./src/com/efounder/react/mainview/MainForm.jsx
 @ ./src/com/efounder/react/router/routes.jsx
 @ ./src/index.jsx
 @ multi ./~/_webpack-dev-server@2.9.7@webpack-dev-server/client?http://localhost:9000 ./src/index.jsx

**Comment by paranoidjk** [comment]
Please file issue in https://github.com/ant-design/ant-design.

And suggest you read https://ant.design/docs/react/introduce-cn first.

cc @yesmeck

**Comment by 2320390964** [comment]
I have the same problem.Have you solved the problem?
