### ISSUE TITLE
如何清空InputItem里的内容

### ISSUE THREAD

**Issue by squallzhou** [ant-design/ant-design-mobile#221]
antd-mobile 版本：0.8.0
操作系统及其版本：macOS10.11.6
浏览器及其版本：chrome 52.0

我要通过一个按钮，点击后，InputItem的值就消失，不知道如何去实现？

**Comment by silentcloud** [comment]
```
<InputItem value={this.state.value}>name</InputItem>

<Button onClick={() => { this.setState({
  value: ''
}) }}
```

不行？

**Comment by squallzhou** [comment]
因为第一次使用这个，所以，我以为input这值我没有用state,我现在定义了一个form,然后用jQuery来清空了。

**Comment by silentcloud** [comment]
建议您用了 react，就尽量不要再用 jq 去操作 dom 了

**Comment by squallzhou** [comment]
嗯，刚转过来使用React.js,我会把现在写的demo再重构一遍，谢谢
