### ISSUE TITLE
TextareaItem 在手机状态下滚动图标成滚动条，清空图标点击不起作用

### ISSUE THREAD

**Issue by duankt** [ant-design/ant-design-mobile#2212]
![image](https://user-images.githubusercontent.com/28881899/34507609-b98c6454-f072-11e7-95de-0fec50075bda.png)
TextareaItem 在手机状态下滚动图标成滚动条，清空图标点击不起作用

**Comment by paranoidjk** [comment]
> 滚动图标成滚动条 

是什么意思？

> 清空图标点击不起作用
请给出可复现 demo。

**Comment by duankt** [comment]
直接看官网mode就有这个问题
https://mobile.ant.design/components/textarea-item-cn/

![image](https://user-images.githubusercontent.com/28881899/34602885-86e95ed2-f23c-11e7-863d-2c6462b9d0fe.png)

**Comment by GankLun** [comment]
I also found this problem

**Comment by paranoidjk** [comment]
@duankt 不知道截的图是什么，受控组件那个 demo 都没有加 `props.clear`.

**Comment by duankt** [comment]
@paranoidjk 直接看官网mode就有这个问题
https://mobile.ant.design/components/textarea-item-cn/ 
作者没有发现在手机模式下，清空功能不能使用吗？ 输入多行的时候上下行切换图标变成滚动条了，这两种在手机模式下就会出现

**Comment by zackteng** [comment]
我也遇到了TexaareaItem清空功能不能使用的问题
