### ISSUE TITLE
Modal.alert actions

### ISSUE THREAD

**Issue by Mr-Kapok** [ant-design/ant-design-mobile#2213]
### Version
2.1.3

### Environment
chrome

### Reproduction link
[https://mobile.ant.design/components/modal-cn/](https://mobile.ant.design/components/modal-cn/)

### Steps to reproduce
调用Modal.alert，查看源码发现actions按钮组用的是a标签(参考官网案例)

### What is expected?
使用其他非A标签，或者整个可接受React.element

### What is actually happening?
目前是a标签

---
提这个建议是因为，业务上有电话呼叫，但因为按钮是a标签的原因，无法使用 a href="tel:xxx"

**Comment by zhang740** [comment]
特殊需求可以直接使用Modal组件在页面中布局

**Comment by quentinyang** [comment]
特殊需求先通过Modal使用自定义内容解决吧。

```
<Modal
  maskClosable={true}
  title="拨打电话"
  footer={[]}
>
  <div>
    <a href="tel:13000000000">13000000000</a>
  </div>
</Modal>
```
