### ISSUE TITLE
react-native中prompt控件底部按钮设置onPress返回promise也会立马关闭

### ISSUE THREAD

**Issue by JinYuSha0** [ant-design/ant-design-mobile#2214]
### Version
2.0.3

### Environment
 react-native^0.50.3

### Reproduction link
[https://mobile.ant.design/components/modal-cn/](https://mobile.ant.design/components/modal-cn/)

### Steps to reproduce
prompt('input name', 'please input your name',
      [
        { text: 'Cancel' },
        {
          text: 'Submit',
          onPress: value => new Promise((resolve) => {
            Toast.info('onPress promise', 1);
            setTimeout(() => {
              resolve();
              console.log(`value:${value}`);
            }, 1000);
          }),
        },
      ], 'default', null, ['input your name'])

### What is expected?
修复这个bug

### What is actually happening?
存在这个问题

---
感谢Ant Design的工作人员，这是一个很棒的项目，希望越做越好！

**Comment by alwaysloseall** [comment]
Toast和modal同时只能存在一个（topview.set）
``````javascript
onPress: value => new Promise((resolve) => {
  Toast.info('onPress promise', 1);
  setTimeout(() => {
  resolve();
  console.log(value:${value});
}, 1000);
``````
调用Toast.info会关掉prompt
onpress回调返回promise延迟关闭的问题，正在解决，之后我会提出PR

**Comment by stelalae** [comment]
希望 new Promise((resolve, reject) 在调用reject时modal不会关闭，同时Toast.info 时也不会导致 modal 关闭

**Comment by silentcloud** [comment]
上面的 PR 应该不能从根本解决问题吧？ @alwaysloseall
