### ISSUE TITLE
PickerView in @2.1.2 (web)  cascade doesnot work

### ISSUE THREAD

**Issue by chocking** [ant-design/ant-design-mobile#2215]
### Version
2.1.2

### Environment
chrome 63

### Reproduction link
[https://codepen.io/chocking/pen/wpqWgZ?editors=0010#0](https://codepen.io/chocking/pen/wpqWgZ?editors=0010#0)

### Steps to reproduce
according to the codepen link , PickerView 's cascade doesnot work

（请看codepen的链接 ，PickerView的cascade失效）

### What is expected?
PickerView 's cascade works
（PickerView的cascade有效）

### What is actually happening?
PickerView 's cascade doesnot work
（PickerView的cascade失效）

**Comment by warmhug** [comment]
测出三个问题：

- `value` `onChange` 不能是必选的，否则 cascade 模式下必须要设置它们，跟 rmc-cascader 表现不一致。
- ts type 类型和 rmc-cascader 里不对应，最好直接 import rmc-cascader 的 type。
- 缺少 cascade 模式的 demo。

**Comment by zhang740** [comment]
- PickerView 目前只支持受控模式，仅展示的组件非受控是否有意义？
- PickerView 不只是  rmc-cascader 怎么对应？只能用统一抽象接口

**Comment by fengyun2** [comment]
+1
