### ISSUE TITLE
List miss line in certain circumstances

### ISSUE THREAD

**Issue by gengjiawen** [ant-design/ant-design-mobile#2216]
### Version
2.1.3

### Environment
react-native 0.51.0

### Reproduction link
[https://github.com/gengjiawen/AntDesignBug](https://github.com/gengjiawen/AntDesignBug)

### Steps to reproduce
for more detail see the repo
```jsx
  render() {
    const cmps = [
      <Item key="cwd" arrow="horizontal" onClick={() => console.log('2')}>忘记密码 </Item>,
      <Item key="heihei" arrow="horizontal" onClick={() => console.log('3')}>修改密码 </Item>
    ]

    return (
      <View style={styles.container}>

        <List>
          <Item arrow="horizontal" onClick={() => console.log('1')}>收支明细</Item>
        </List>

        <View style={{height: 10}} />

        <List>
          <Item arrow="horizontal" onClick={() => console.log('1')}>提现账户 </Item>
          {cmps.map(comp => comp)}
        </List>
      </View>
    );
  }
```

### What is expected?
between item has line

### What is actually happening?
lost some line.

###
If previous has a single kid, it will result in the second list miss some line 
```jsx
<List>
      <Item arrow="horizontal" onClick={() => console.log('1')}>提现账户 </Item>
</List>
```
![image](https://user-images.githubusercontent.com/3759816/34556470-5b213bec-f171-11e7-9c12-8231f64d8f67.png)

**Comment by gengjiawen** [comment]
Actually middle view height to 20, the line appeared again.
```
<View style={{height: 20}} />
```

**Comment by gengjiawen** [comment]
@paranoidjk Any plan to investigate this ?

**Comment by warmhug** [comment]
The issue of view height ?

**Comment by warmhug** [comment]
Close for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452
