### ISSUE TITLE
搜索框样式问题

### ISSUE THREAD

**Issue by duankt** [ant-design/ant-design-mobile#2218]
版本2.1.3
清空图标在上面没有居中，提示字“北京”当光标在搜索框中后，只能显示“北”

**Comment by duankt** [comment]
![image](https://user-images.githubusercontent.com/28881899/34594657-544f486c-f20d-11e7-85c7-de014af162be.png)

**Comment by duankt** [comment]
![image](https://user-images.githubusercontent.com/28881899/34594663-5e24b70a-f20d-11e7-9660-ad1e9311c4b7.png)

**Comment by paranoidjk** [comment]
官方 demo 正常，给出可复现的例子。https://mobile.ant.design/components/search-bar-cn/

**Comment by duankt** [comment]
百度云盘中下载解决方案，VS中直接调试运行就可以
链接：https://pan.baidu.com/s/1jHPu9E2 密码：1sp1

**Comment by paranoidjk** [comment]
并没有 visual studio 调试环境，请给出简单可复现的 demo。

**Comment by duankt** [comment]
@paranoidjk 简单的demo不会有问题，关键就是dotnet core这种react环境下会有问题，可能是组件包版本问题

**Comment by duankt** [comment]
已经找到问题根源，是因为有个全局的CSS样式的问题，webkit-box-sizing: border-box;
    box-sizing: border-box;可以去掉这两个就行啦，

**Comment by warmhug** [comment]
close for #2510 #2447
