### ISSUE TITLE
Starting out: Should I use antd or antd mobile?

### ISSUE THREAD

**Issue by loganpowell** [ant-design/ant-design-mobile#2222]
First, I've been following antd for about a year now and have been eager to give it a try! It seems incredible how much work your team has put into it and it's a beautiful library!

I'm very sorry for the stupid question, but I'm having trouble understanding whether I should start using antd or antd mobile. It looks like antd mobile also works on the web? Are the APIs between the two projects the same? If I start with vanilla antd, would it be a seamless switch to port to antd mobile?

首先，我已经跟随了大约一年的时间，并已经急于尝试！你的团队投入了多少工作似乎不可思议，这是一个美丽的图书馆！

我很抱歉这个愚蠢的问题，但是我很难理解是否应该开始使用antd或antd mobile。它看起来像antd手机也可以在网上？这两个项目之间的API是相同的吗？如果我从vanilla antd开始，它会是一个无缝切换到端口到antd移动？

[courtesy of Google translate]

**Comment by paranoidjk** [comment]
antd-mobile is only for mobile webapp.

antd is mainly used on desktop website.

**Comment by acomito** [comment]
@paranoidjk I've used antd-mobile for react-native apps. But what do you think about antd-mobile for this case:

- creating a PWA webapp
- will be used on mobile 90% of the time (e.g. mobile screen size and mobile browsers)
- but it is possible some people may open and use it on their desktop browsers

Is it okay to use antd-mobile? Or should we just use antd? Or should we use a mix of antd-mobile and antd?

I would really value your opinion/thoughts. Thanks!
