### ISSUE TITLE
Modal.prompt 在 ios 环境中点击缓慢，需要点击5-6次才可以取得焦点

### ISSUE THREAD

**Issue by fe719319448** [ant-design/ant-design-mobile#2223]
### Version
2.1.3

### Environment
ios10   ios11

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN#modal-demo-2](https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN#modal-demo-2)

### Steps to reproduce
点击 modal.prompt   promise案例  ，点击输入框

### What is expected?
焦点在输入框

### What is actually happening?
需点击5-6次才可对焦

---
官网的 demo 没有加入 faskclick，我自己的项目里面加入了 fastclick，问题依旧

**Comment by fe719319448** [comment]
我用的官方给的 demo地址在 ios  系统的微信里面打开，mobal.prompt 组件输入框都是要点击很近的。
我还录了一个小视频，可以给一个邮箱吗？

**Comment by itxuye** [comment]
@fe719319448  https://github.com/ant-design/ant-design-mobile/issues/1857

**Comment by warmhug** [comment]
ref #2177

**Comment by paranoidjk** [comment]
重复 issue 关闭掉，请关注 https://github.com/ant-design/ant-design-mobile/issues/2177 的进度。
