### ISSUE TITLE
Modal.alert 默认样式内容区没有居中

### ISSUE THREAD

**Issue by HateTomatoes** [ant-design/ant-design-mobile#2225]
"antd-mobile": "^2.1.2",
"react-native": "0.51.0",
调用代码：
Modal.alert(
            'Title',
            'alert content',
            [
                { text: 'Cancel', onPress: () => console.log('cancel'), style: 'cancel' },
                { text: 'OK', onPress: () => console.log('ok') },
            ],
        );
问题如题
![antd222](https://user-images.githubusercontent.com/17923476/34637734-79cfb08c-f2f7-11e7-9eb3-071a852f1fb5.png)

**Comment by deboyblog** [comment]
+1

**Comment by Ben56** [comment]
I encountered the same problem

**Comment by liyanxi** [comment]
me too, did you solve it? @HateTomatoes @ant-design-bot

**Comment by warmhug** [comment]
Ref #2325 
Close for https://github.com/ant-design/ant-design-mobile/commit/eb0b1f28a870297cf8ce85686086745b07fe08f4
