### ISSUE TITLE
关于calendar在ios8中不能打开的issue

### ISSUE THREAD

**Issue by chenbin2015** [ant-design/ant-design-mobile#2226]
一直用calendar开发的，在ios8中测试时，不能打开弹框，后来我用ios8打开了官网的这个链接
https://mobile.ant.design/kitchen-sink/components/calendar?lang=zh-CN，依然不能弹窗calendar

**Comment by paranoidjk** [comment]
帮忙看下 console 里面有没有报错？报错内容发上来？没有 ios8 的设备

**Comment by luania** [comment]
也出现这个问题，现在已经解决了吗

**Comment by Ajuly** [comment]
同样出现这个问题请问已经解决了吗？
