### ISSUE TITLE
建议Popover浮动菜单增加背景遮罩层

### ISSUE THREAD

**Issue by jackyr** [ant-design/ant-design-mobile#223]
![image](https://cloud.githubusercontent.com/assets/4645227/18273285/0a8d3044-746f-11e6-956a-376da60c24bd.png)
当下面这块区域是iframe时，点击无法关闭浮动菜单。
建议增加类似Popup组件中的mask遮罩层，整个页面覆盖。并提供可选开关。

**Comment by warmhug** [comment]
iframe 里自己更改组件的 visible 状态

**Comment by pingan1927** [comment]
NavBar是父网页的，下面的空白部分是个iframe。

**Comment by silentcloud** [comment]
@warmhug 楼主的需求是合理的，native 实现这个东东也是类似有一层 mask 的

**Comment by yiminghe** [comment]
https://github.com/react-component/trigger  mask
