### ISSUE TITLE
The Button component onClick event fails in the component that the map function generates.

### ISSUE THREAD

**Issue by wksmile** [ant-design/ant-design-mobile#2230]
### Version
2.1.3

### Environment
windows10,chrom63,react16

### Reproduction link
[https://github.com/wksmile/applyjob/blob/master/src/component/user/user.js](https://github.com/wksmile/applyjob/blob/master/src/component/user/user.js)

### Steps to reproduce
Using the map function to generate multiple components, the Button on the inside element cannot trigger the click event,it is OK after plus z-index:100 on the Button.

### What is expected?
Hopefully you don't have to add anything else

### What is actually happening?
The z-index style must be added, which should be covered by other styles, and this is hard to find.

**Comment by warmhug** [comment]
Do have the same problem on mobile?

**Comment by wksmile** [comment]
@warmhug yes,I have test on cellphone,it's still a problem

**Comment by paranoidjk** [comment]
抽象一个简单可复现的 demo。你的代码并没有 map 生成多个 Button, 且 z-index 样式问题与这个应该毫无关系。
