### ISSUE TITLE
Toast 不起作用

### ISSUE THREAD

**Issue by showtan** [ant-design/ant-design-mobile#2232]
version
"antd-mobile": "^2.0.0",
 "react": "^16.0.0-alpha.12",
 "react-native": "^0.46.4",
 集成了热更新与推送  然后Toast就不起作用了？  未必还有影响？

**Comment by showtan** [comment]
Integrated heat update and push then Toast doesn't work? Does not necessarily have an impact?

**Comment by paranoidjk** [comment]
阅读 issue 规范，给出必要信息。http://new-issue.ant.design/?repo=antd-mobile
