### ISSUE TITLE
Tabs in react-native use initialPage to set default tab have a bug

### ISSUE THREAD

**Issue by niices** [ant-design/ant-design-mobile#2239]
### Version
2.1.3

### Environment
Mac 10.13.3  react-native 0.51.0  react 16.0.0

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
When I use `Tabs` component in react-native 
I want use `nitialPage={0}` to set first tab to be the default tab
Then there have some trouble to display
But it' normal on react but abnormal on react-native so I can't provide a repeat link

### What is expected?
use `nitialPage={0}` to set first tab to be the default tab

### What is actually happening?
use `nitialPage={0}` set first tab to be the default tab. then display is not normal

**Comment by niices** [comment]
![image](https://user-images.githubusercontent.com/8327775/34819419-a4c2975a-f6f8-11e7-9c3a-ed2fa7449f8f.png)

**Comment by warmhug** [comment]
Trace https://github.com/ant-design/ant-design-mobile-rn/issues/10
