### ISSUE TITLE
inputItem  fix touch to scroll background page on iOS

### ISSUE THREAD

**Issue by yipengmu** [ant-design/ant-design-mobile#2247]
就是 inputItem(andt2.0) 在iPhone 上有有和 actionSheet类似的事件透传问题，
但inputItem不支持wrapProps的属性，需要新增类似机制

// fix touch to scroll background page on iOS
// https://github.com/ant-design/ant-design-mobile/issues/307
// https://github.com/ant-design/ant-design-mobile/issues/163
const isIPhone = new RegExp('\\biPhone\\b|\\biPod\\b', 'i').test(window.navigator.userAgent);
let wrapProps;
if (isIPhone) {
  wrapProps = {
    onTouchStart: e => e.preventDefault(),
  };
}

**Comment by yipengmu** [comment]
示例说明：https://im4.ezgif.com/tmp/ezgif-4-2e0c71c161.gif

**Comment by warmhug** [comment]
自定义键盘、需要重构优化

- 页面中默认有键盘 dom 结构但隐藏，是否不妥？建议做成类似 Modal 的 dom 处理方式，显示时创建/关闭时销毁
- css 样式写法也修改为同 Modal 类似: wrapper 层 fixed 覆盖整个页面、并增加 wrapProps Api 功能也同 Modal 类似；table 层样式设置为 键盘高度。html 不需要改变。

@pingan1927 @silentcloud
