### ISSUE TITLE
The Stepper can get the focus and manually enter the value

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-design-mobile#2250]
### Version
2.1.3

### Environment
win10，chrom

### Reproduction link
[https://codepen.io/anon/pen/zpLaOV?&editors=001](https://codepen.io/anon/pen/zpLaOV?&editors=001)

### Steps to reproduce
1. click the number area in the middle of Stepper,You can get the cursor and manually enter any value.
2. bad is, for example, I set up (min=0 step=1), and then enter 1.1, click the   button, the value becomes 2.1, which is not reasonable.

### What is expected?
Stepper can't focus, or 1.1 click   become 2

### What is actually happening?
Stepper can focus, enter 1.1 clicks and turn to 2.1

**Comment by warmhug** [comment]
ref https://github.com/react-component/input-number
@afc163

**Comment by paranoidjk** [comment]
Notice `props.step`.
