### ISSUE TITLE
Calendar限制时间范围区间

### ISSUE THREAD

**Issue by jutian88** [ant-design/ant-design-mobile#2252]
请问Calendar组件在选择时间段方面, 如何限制在规定的范围(比如说先选择25日, 则只能选择24或26日)
![qq 20180115191339](https://user-images.githubusercontent.com/30802089/34939876-70a59eb2-fa28-11e7-9b78-eb991c372398.png)

**Comment by zhang740** [comment]
用户选择时的回调 onSelect，https://mobile.ant.design/components/calendar-cn/

**Comment by jutian88** [comment]
@zhang740 考虑过onSelect, 需求是取出日期区间, 但onSelect每次只能选择一个参数

**Comment by jutian88** [comment]
@zhang740 总的需求是通过获取别人选取的日期区间, 来限制别人不能选择大于3天的时间段

**Comment by zhang740** [comment]
onSelect 的返回参数就是用户的选择情况，你可以在这个回调中处理业务逻辑，包括给用户反馈提示，并且这个函数可以返回时间/时间区间，可以替换用户选择结果

函数签名：
(date: [Date, Date] | [Date]) => [Date, Date] | [Date] | void

https://mobile.ant.design/components/calendar-cn/

**Comment by jutian88** [comment]
@zhang740 请问哪里错了吗? 只能分别打印出时间, 而不是时间区间格式
![qq 20180117145549](https://user-images.githubusercontent.com/30802089/35029599-a72c9eda-fb96-11e7-87f9-e2e7b5a9dc9c.png)

**Comment by jutian88** [comment]
![qq 20180117145735](https://user-images.githubusercontent.com/30802089/35029624-c62d8524-fb96-11e7-8581-a238868d2c2e.png)

**Comment by zhang740** [comment]
onSelect 加了第二参数，为 **当次选择生效前** 的开始/结束时间 @jutian88
