### ISSUE TITLE
actionSheet 当内容超过指定高度，加滚动条不能滚动

### ISSUE THREAD

**Issue by yipengmu** [ant-design/ant-design-mobile#2253]
触发条件

:global {
  .am-action-sheet {
    height: 600px;
  }
  .am-action-sheet-button-list{
    height: 300px;
    overflow: scroll;
  }
}

ActionSheet.showActionSheetWithOptions({
            options: items,
            title: '选择',
            maskClosable: true,
            wrapProps,
          }, (Index) => {    }
          });

当options内容item内容超过300px 时，无法触发actionsheet的滚动

**Comment by zhang740** [comment]
外层wrapProps不要阻止默认事件行为
```
if (isIPhone) {
  wrapProps = {
    onTouchStart: e => e.preventDefault(), // 注释掉
  };
}
```

**Comment by zhang740** [comment]
mark 弹出部分滚动 和 阻止背景滚动 的问题

**Comment by warmhug** [comment]
1.x 在 mask 上处理过这个问题 https://github.com/ant-design/ant-design-mobile/blob/1.x/components/popup/index.web.tsx#L43

**Comment by warmhug** [comment]
https://github.com/react-component/m-dialog/commit/55b36d596605239b96ceaa4c946e306b69729aad
功能上已经支持，但 内容超过指定高度时，不建议使用 actionSheet
