### ISSUE TITLE
RN DatePickerView item text ellipsized

### ISSUE THREAD

**Issue by hitbear518** [ant-design/ant-design-mobile#2254]
### Version
2.1.3

### Environment
iOS
iPhone SE
iOS 11.2.2

### Reproduction link
[exp://exp.host/@silentcloud/antd-mobile](exp://exp.host/@silentcloud/antd-mobile)

### Steps to reproduce
Just check the official expo sample app's DatePickerView section with iPhone SE and system language of CN, which can reproduce this issue.

### What is expected?
every column show all text

### What is actually happening?
the year column has been ellipsized
![image](https://user-images.githubusercontent.com/5070531/34984952-7f3b0ffa-faed-11e7-8bf2-d185ef79b4e7.png)

**Comment by warmhug** [comment]
We just use react-native Picker.
https://github.com/react-component/m-picker/blob/79c60b7ba98ced8e230ab799740196ba9ce4b89d/src/NativePicker.ios.tsx#L1
So, it seems that nothing can be done?

**Comment by hitbear518** [comment]
![image](https://user-images.githubusercontent.com/5070531/40484180-4b1c1fb6-5f8d-11e8-8d66-53d5f674223d.png)
Can we mimic the official mode and style?

**Comment by warmhug** [comment]
Why not just use official DatePicker?

**Comment by hitbear518** [comment]
😅Because it’s iOS only.
But the point is component’s compatibility with small screen devices.

**Comment by warmhug** [comment]
Sorry, I'm afraid there is no good solution.

**Comment by warmhug** [comment]
Close for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452
