### ISSUE TITLE
prompt应支持修改密码类型

### ISSUE THREAD

**Issue by c305333655** [ant-design/ant-design-mobile#2255]
### What problem does this feature solve?
弹框修改密码

### What does the proposed API look like?
<Button onClick={() => prompt(
        '修改密码',
        null,
        (oldPassword, newPassword, regPassword) => dispatch({type: '', data: {
            oldPassword: oldPassword,
            newPassword: newPassword,
            regPassword: regPassword
          }
        }),
        'default',
        null,
        ['请输入原密码', '请输入新密码', '请输入确认密码'],
      )}
>修改密码</Button>

**Comment by warmhug** [comment]
不太可能覆盖全部类型的，业务自己定制吧
