### ISSUE TITLE
Loading Icon does not animate

### ISSUE THREAD

**Issue by gianpaj** [ant-design/ant-design-mobile#2256]
### Version
2.1.3

### Environment
react-native

### Reproduction link
[https://imgur.com/a/iDB9P](https://imgur.com/a/iDB9P)

### Steps to reproduce
Add font file via Xcode and add component:

`<Icon type="loading" />`

### What is expected?
Icon to animate

### What is actually happening?
Icon doesn't animate

---
see the icon beside the word "hello"

**Comment by gianpaj** [comment]
I believe this also affects the Pull to Refresh component:
https://mobile.ant.design/components/pull-to-refresh/

https://github.com/ant-design/ant-design-mobile/blob/master/components/pull-to-refresh/index.tsx

**Comment by silentcloud** [comment]
你可以在业务里自己实现一下，或者推荐用 http://facebook.github.io/react-native/docs/activityindicator.html
