### ISSUE TITLE
ReactNative下Grid组件 如果数据源的数量无法整除列数的时候表现不正常(设置了itemStyle属性)

### ISSUE THREAD

**Issue by deboyblog** [ant-design/ant-design-mobile#2257]
### Version
2.1.3

### Environment
ReactNative: 0.52.0

### Reproduction link
[https://github.com/deboyblog/react-native-antd-mobile-grid](https://github.com/deboyblog/react-native-antd-mobile-grid)

### Steps to reproduce
数据源7个 列设为3
那么最后一个表现不正常 明显偏离上一行的布局

### What is expected?
行于行之间间距一致

### What is actually happening?
最后一行于上一行之间间距明显与其他行不一致

---
在Accordion组件中使用 展示某种分类列表

**Comment by jack-jun** [comment]
请问你解决了吗？

**Comment by deboyblog** [comment]
@jack-jun 添加空白数据填充(使其达到能够整除列数) 然后添加特殊样式隐藏假数据就可以达到预期效果 但是我最后还是选择了自己重写组件

**Comment by hendrul** [comment]
English plssss, those glyphs are like chinese to me :)

**Comment by deboyblog** [comment]
@hendrul If the number of data sources is not divisible by the number of columns, the style does not behave properly. And I changed the `itemStyle` properties
Line spacing is consistent between rows. The last line is clearly spaced out from the other rows.

**Comment by warmhug** [comment]
It's really hard to meet all the situations, so you can rewrite components.
