### ISSUE TITLE
Simplify the use of InputItem components

### ISSUE THREAD

**Issue by zhangenming** [ant-design/ant-design-mobile#2258]
### What problem does this feature solve?
Make InputItem components more friendly to write / read

### What does the proposed API look like?
```
from
<InputItem value={this.state.a} >A</InputItem>
<InputItem value={this.state.b} >B</InputItem>
to
<InputItem value={this.state.a}  test='A' />
<InputItem value={this.state.b}  test='B' />
```

**Comment by zhangenming** [comment]
ding....

**Comment by warmhug** [comment]
This is a big change, and not sure if it is better.

**Comment by zhangenming** [comment]
@warmhug 
or <InputItem value={this.state.a}  children='A' /> ?

**Comment by warmhug** [comment]
I think not very good.
