### ISSUE TITLE
TextareaItem count property not work 

### ISSUE THREAD

**Issue by beysong** [ant-design/ant-design-mobile#2259]
### Version
2.1.3

### Environment
react-native 0.51

### Reproduction link
[https://mobile.ant.design/components/textarea-item-cn/](https://mobile.ant.design/components/textarea-item-cn/)

### Steps to reproduce
<TextareaItem
            {...getFieldProps('desc', {
              initialValue: '测试文字',
            })
            }
            clear
            placeholder="请填写简介"
            rows={5}
            count={100}
          />

### What is expected?
4/100

### What is actually happening?
0/100

**Comment by bang88** [comment]
Can not reproduce it with the latest version `2.1.8`. It works properly.

**Comment by warmhug** [comment]
After set `value`, then need set `onChange`.
