### ISSUE TITLE
Carousel display error

### ISSUE THREAD

**Issue by cycgit** [ant-design/ant-design-mobile#2261]
### Version
2.0.2

### Environment
alipay web

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/e79c0352](https://riddle.alibaba-inc.com/riddles/e79c0352)

### Steps to reproduce
return (
      <div className="channel-banner-list-container">
        <Carousel
          className="banner-list-carousel"
          autoplay={banners.length > 1}
          dots={banners.length > 1}
          afterChange={this.onBannerChange()}
          infinite={banners.length > 1}
          swiping={banners.length > 1}
        >
          {banners.map((banner, bannerIndex) => {
            return (
              <div
                className='image-container'
                key={bannerIndex}
                onClick={ this.onOpen(banner) }
                ref={item => {
                  item && cdpFeedshow(banner);
                }}>
                <img src={banner.hrefUrl} className="banner-img" alt="" />
              </div>
            );
          })}
        </Carousel>
      </div>
    );

### What is expected?
display normal

### What is actually happening?
display error

**Comment by zhang740** [comment]
```
              <img
                src={`https://zos.alipayobjects.com/rmsportal/${val}.png`}
                alt=""
                style={{ width: '100%', verticalAlign: 'top' }}
                onLoad={() => {
                  // fire window resize event to change height
                  window.dispatchEvent(new Event('resize'));
                  this.setState({ imgHeight: 'auto' });
                }}
              />
```

目前需要在图片加载完成后手动刷新
