### ISSUE TITLE
NoticeBar marquee loop InteractionManager.runAfterInteractions can not be call

### ISSUE THREAD

**Issue by wk1017553772** [ant-design/ant-design-mobile#2267]
when I use
`<NoticeBar marqueeProps={{ loop: true, leading: 500, trailing: 800, fps: 40 }}` in rn

it call be auto scroll well ,but other place use InteractionManager.runAfterInteractions can not be call ever more
 `InteractionManager.runAfterInteractions(() => {`
`     // some code .....  this code will not call when marquee run !!!`
`});`

I think the  Marquee animated should add
 `isInteraction: false`
can resolve this problem.

**Comment by Bubblex** [comment]
+1

**Comment by warmhug** [comment]
Why not have a pr~
