### ISSUE TITLE
custom style variable radius_md: 0 cause search bar wrong style at iphone 6 plus native app 

### ISSUE THREAD

**Issue by postgetme** [ant-design/ant-design-mobile#2272]
### Version
2.1.3

### Environment
react native iphone 6 plus

### Reproduction link
[http://no-link.io](http://no-link.io)

### Steps to reproduce
no

### What is expected?
get right style

### What is actually happening?
get wrong style

**Comment by postgetme** [comment]
![simulator screen shot 2018 1 22 8 46 45](https://user-images.githubusercontent.com/5118867/35221633-d5a4af82-ffb5-11e7-8db4-11c380d0a7e5.png)

**Comment by warmhug** [comment]
Set `style` to override it.
https://github.com/ant-design/ant-design-mobile/blob/1ebab6d092b97b98b015b347ed60b728c6b161f7/components/search-bar/index.native.tsx#L135
