### ISSUE TITLE
Calendar组件中的pickTime页面标题可以置换吗? 

### ISSUE THREAD

**Issue by jutian88** [ant-design/ant-design-mobile#2276]
![qq 20180123151434](https://user-images.githubusercontent.com/30802089/35262562-21a3467e-0050-11e8-85e8-c065a8a366d6.png)
使用renderHeader后标题(包括左右操作按钮)都会被替换

**Comment by jutian88** [comment]
![11](https://user-images.githubusercontent.com/30802089/35262730-cca46c6a-0050-11e8-8677-b2a8a4b3ac5b.png)

**Comment by jutian88** [comment]
使用renderHeader后标题(包括左右操作按钮)都会被替换

**Comment by zhang740** [comment]
目前没有改 TimePicker 标题的API，只能通过重写 locale 的方式hack

**Comment by likezero** [comment]
you can do like this:
```js
const locale = {
 selectTime: '自定义时间标题'
}
// and then
<Calendar locale={locale} />
```

![image](https://user-images.githubusercontent.com/2275857/39870068-88e9c86c-5492-11e8-90cb-f906c7a30516.png)

**Comment by LiLixikun** [comment]
自定义renderHeader后标题(包括左右操作按钮)都会被替换 我想实现清除按钮无法做到，并且下次进去不会默认选中，因为他没有value属性
