### ISSUE TITLE
Radio 单选框 BUG

### ISSUE THREAD

**Issue by shunanlove** [ant-design/ant-design-mobile#2277]
Radio 单选框 Radio.RadioItem文字多换行之后 点击item只有点击效果 不能进点击事件了

**Comment by shunanlove** [comment]
![image](https://user-images.githubusercontent.com/18024644/35271552-6fb04ce6-006d-11e8-87ad-1eb45e335ff9.png)

**Comment by shunanlove** [comment]
点击效果有 但是不进onChange

**Comment by paranoidjk** [comment]
无法复现。

**Comment by shunanlove** [comment]
@paranoidjk 内容写点 让他折行 3、4行左右吧，onChange不进 我已经把逻辑都改到onClick里了

**Comment by zhixinpeng** [comment]
我也遇到这个问题，onChange事件进不去，只能改成onClick事件 我找了半天没找到原因

**Comment by wZi** [comment]
mark 
同样的现象
连官网的 demo 也有此现象.
流程如下:
1. 当unChecked 时, 点击,触发 onChange
2.  当checked时, 点击, 不触发onChange
