### ISSUE TITLE
InputItem控件加上验证后跳转页面警告

### ISSUE THREAD

**Issue by xiaochong521** [ant-design/ant-design-mobile#228]
- antd-mobile 版本：0.8.1
- 操作系统及其版本：mac
- 浏览器及其版本：safari

页面中加入InputItem 控件 其中加入验证：
<InputItem
                                {...getFieldProps('input1', {
                                    initialValue: '',
                                    rules: [{required: true,message: '不能为空'},{type: 'string',min: 5,message: '最小长度为5',}],
                                    validateTrigger: null
                                })}
                                placeholder="123"
                                clear
                                error={(typeof getFieldError('input1') ==typeof undefined)?false:true}
                                maxLength={10}
                            >车主姓名</InputItem>
点击跳转按钮

页面跳转代码
this.props.form.validateFields((error, values) => {
            if (!error) {
                this.context.router.push('跳转页面');
            } else {
                console.log(error.input1);
                console.log('error', error, values);
            }
        });

页面跳转后报以下信息：
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

但是使用正常的input控件并未发现此问题。

**Comment by pingan1927** [comment]
这个可以忽略，你在`this.context.router.push('跳转页面');`这段代码的时候，InputItem组件正在销毁，同时InputItem会触发Blur事件，内部会setState，react正好出现报错。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.web.tsx#L99

setTimeout 的钩子在 componentWillUnmount 的时候一律要清空。

**Comment by pingan1927** [comment]
@afc163 我研究下，`componentWillUnmount`清空是合理的做法？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/2be285d2367e9dd59f225f762131b97260c0adff/components/spin/index.jsx#L40

**Comment by jf3096** [comment]
毕竟这个部分是第三方包存在于node_modules, 不建议直接修改, 下一次npm install的时候修改部分会被刷掉.

在不修改源码的情况下, 解决方式如下: 后续操作使用CustomInputItem, 不直接使用InputItem. 

这部分代码可以认为一个对InputItem的二次封装, 可以针对自己业务收窄InputItem暴露的功能, 所以即使antd团队后续修复这个"bug", 一下二次封装的控件仍可以保留.

方法#1:

class CustomInputItem extends InputItem {
    timeoutHooker;

    constructor(props) {
        super(props);
    }

    clearTimeoutHooker() {
        if (this.timeoutHooker) {
            clearTimeout(this.timeoutHooker);
        }
    }

    onInputBlur = (e) => {
        this.clearTimeoutHooker();
       
       // 以下部分为antd input-item源码
       // 源码地址: https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.web.tsx#L99
        this.timeoutHooker = setTimeout(() => {
            this.setState({
                focus: false,
            });
        }, 300);
        const value = e.target.value;
        this.props.onBlur(value);
    };

    componentWillUnmount() {
        this.clearTimeoutHooker();
    }
}



方法#2: 
(不推荐, 阿里大大使用setTimeout 300ms肯定有他们的考虑, 具体不清楚, 但是去除后仍可行)
同样继承InputItem, 然后去掉setTimeout, 代码如下.

class CustomInputItem extends InputItem {
    constructor(props) {
        super(props);
    }

    onInputBlur = (e) => {
        this.setState({
            focus: false,
        });
        const value = e.target.value;
        this.props.onBlur(value);
    };
}
