### ISSUE TITLE
高清方案为什么要导出一个flex函数到全局？

### ISSUE THREAD

**Issue by jieyou** [ant-design/ant-design-mobile#2283]
### Version
2.1.4

### Environment
代码层面的问题，任意环境

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/wiki/HD](https://github.com/ant-design/ant-design-mobile/wiki/HD)

### Steps to reproduce
https://github.com/ant-design/ant-design-mobile/wiki/HD 里面点击“ antm-viewport.min.js”，跳转到https://gw.alipayobjects.com/os/rmsportal/uDTmsEBmTUVrpmCBozbm.js ，这个js文件

### What is expected?
如果在别的地方不需要再使用flex，则推荐使用自执行的匿名函数，而不是将flex导入到全局window

### What is actually happening?
全局window下有一个变量flex

---

**Comment by warmhug** [comment]
谢谢提醒，但脚本代码可以自己修改。

**Comment by jieyou** [comment]
@warmhug 也就是自行修改为匿名自执行函数不要紧？这就是意味着没有别的地方需要使用flex函数了？

**Comment by warmhug** [comment]
别的地方不需要
