### ISSUE TITLE
ImagePicker multiple choice how to limit the number

### ISSUE THREAD

**Issue by FingersKey** [ant-design/ant-design-mobile#2284]
ImagePicker multiple choice how to limit the number

**Comment by warmhug** [comment]
`selectable` api.

**Comment by FingersKey** [comment]
@warmhug  那只是单选的情况下，如果我多选我还是可以选个几十张，使用`multiple ` api的情况下

**Comment by warmhug** [comment]
可以选个几十张，但能限制只展示出几张吧。

**Comment by FingersKey** [comment]
@warmhug  我现在是这样做的，但在体验上这样做并不太好不是吗.......  还是说浏览器提供的API并不支持多选的时候限制张数.....

**Comment by warmhug** [comment]
我印象中浏览器没提供这样的API
