### ISSUE TITLE
inputItem输入内容太长时，拖动光标将无法移动到未展示的部分去

### ISSUE THREAD

**Issue by alex89lj** [ant-design/ant-design-mobile#2286]
Version：
2.1.4

Environment：
微信浏览器

问题：
inputItem输入内容太长时，拖动光标将无法移动到未展示的部分去。在uc浏览器中可以正常拖动。

**Comment by micooz** [comment]
使用系统原生方式（在文本框上右滑，而非第三方键盘上右滑）可以正常展示，不影响功能。
