### ISSUE TITLE
RN InputItem clear doesn't  display in Android

### ISSUE THREAD

**Issue by tong233** [ant-design/ant-design-mobile#2288]
### Version
2.1.4

### Environment
android 5.1 & android 7.1    "react-native": "0.52.0"

### Steps to reproduce
```
render() {
    return (
      <List renderHeader={() => 'Show clear'}>
        <InputItem clear placeholder="displayed clear while typing">
         TITLE
        </InputItem>
      </List>
    )
  }
```
![image](https://user-images.githubusercontent.com/21073132/35430672-4662a430-02b4-11e8-840c-e56f0d921252.png)

### What is expected?
need a clear button When input

### What is actually happening?
never seen clear button

**Comment by rookieChan** [comment]
Is there a solution？

**Comment by wgy855** [comment]
After updating to the latest version, this problem is still unfixed.

"antd-mobile": "^2.1.8",
"react": "16.0.0",
"react-native": "0.50.1",

**Comment by Bealiah** [comment]
there is  a bug with  InputItem component . All the version2.X  have this bug ，and onChange function  isn‘t  triggered
