### ISSUE TITLE
ListView数据量大，苹果手机回退出现bug。

### ISSUE THREAD

**Issue by chenghaohao** [ant-design/ant-design-mobile#2297]
### Version
2.1.4

### Environment
苹果手机ios11.2.2 微信版本6.6.1

### Reproduction link
[https://github.com/ant-design/ant-design-mobile（公司项目，不方便提供演示地址）](https://github.com/ant-design/ant-design-mobile（公司项目，不方便提供演示地址）)

### Steps to reproduce
1：用listview渲染一个长列表。
2：点击listview的靠后面的item，进入详情界面。
3：回退到列表页面，此时会出现一个遮罩层挡住靠前的部分列表数据。
4：滑动一下列表，正常显示。（改问题只存在苹果手机端，安卓手机不存在此问题，电脑调试无法重现，微信访问页面基本都会出现，Safari浏览器偶尔出现）

### What is expected?
从详情界面回退到列表页面正常，不会出现遮罩层。

### What is actually happening?
从详情界面回退到列表页面显示异常，有遮罩层挡住部分数据。微信访问页面基本存在问题，手机自带浏览器偶尔出现问题。
异常见下面评论补图。麻烦请看下，谢谢。

---
微信访问页面异常明显。列表数据大的情况下。苹果手机存在问题，安卓手机不存在此问题

**Comment by chenghaohao** [comment]
![_20180128233321](https://user-images.githubusercontent.com/9986914/35484103-0afcbe16-0486-11e8-8198-4f71ec2eef7f.png)
![_20180128233328](https://user-images.githubusercontent.com/9986914/35484104-0bd2e6bc-0486-11e8-82de-99d44ca6acf2.jpg)

**Comment by chenghaohao** [comment]
@paranoidjk @warmhug  麻烦请大神看看呢，谢谢

**Comment by lichaoming1559731827** [comment]
一模一样的bug ,只要是 ios的浏览器和ios的手机就会出现这个问题，跪求看下

**Comment by bestv2** [comment]
你可以在listview的css中加上position: relative;试试

**Comment by chenghaohao** [comment]
![qq 20180131104824](https://user-images.githubusercontent.com/23539868/35602678-8cee1d44-0674-11e8-8630-c86b4b8e4dec.png)
设置relative没效果，按照文档这个设置height和overflow，不会出现上面说的问题，但是这个方法非常不可取，会导致设计好的样式错乱，并且滑动起来也非常慢，而且动态设置列表的高度也很麻烦。不知道为什么会这样，关键是只有苹果手机上才会出现，没法调试，目前没想出办法。

**Comment by warmhug** [comment]
ListView 有两种类型的滚动容器：

1. 局部 div 容器
    - 默认，注意：**需要手动给 ListView 设置高度**
2. html 的 body 容器
    - 设置`useBodyScroll`后生效 (不需要设置高度)

这两种容器下都测了，没发现你们说的问题。
**需要你们给出最小可重现 demo，谢谢！**

**Comment by chenghaohao** [comment]
@warmhug  感谢提醒，完整demo比较麻烦，所以就没有给了。我用了useBodyScroll，但是是嵌套在自定义的div里面的，没有手动设置高度。去掉了useBodyScroll，手动设置listview高度和overflow，然后没问题了。样式有点差异（我想让整个页面滚动，设置高度后只有listview的容器内容滚动，顶部的额外的DOM就成固定了，和RN的思路一样），但是能接受~

**Comment by ovaldi** [comment]
same issue +1

**Comment by 750973092** [comment]
same issue +1

**Comment by 750973092** [comment]
@ovaldi可有解决方法？

**Comment by 750973092** [comment]
我的bug是在列表的时候用了document.documentElement.scrollTop || document.body.scrollTop;这个所以导致返回的出现了遮罩不能点击，去掉就好了

**Comment by win7killer** [comment]
大家尝试验证下这个方案是不是同样适用，我这改后30次没再复现
加上属性：  automaticallyAdjustContentInsets={false}

来源：react-native
https://github.com/facebook/react-native/issues/721

**Comment by win7killer** [comment]
最终屈服了，折磨了我两天。
hack 一下，回退到这个页面的时候，自己 scroll 1px，触发 scroll 后，能展示。但是，那个白色的还会出现，闪一下

**Comment by win7killer** [comment]
@chenghaohao   你这算是修改了交互方案对吧~ 绕过了这个问题。我这需求和你一样，但是不能只在一个 div 内滚动
