### ISSUE TITLE
Android ImagePicker mobile phone in WeChat map multi component cannot

### ISSUE THREAD

**Issue by congjie** [ant-design/ant-design-mobile#2298]
### Version
2.1.4

### Environment
WeChat browser latest version

### Reproduction link
[http://t.diaoxun.wang/?#/test/img](http://t.diaoxun.wang/?#/test/img)

### Steps to reproduce
Click add pictures, select an album, Android can only choose a picture, but you can choose more pictures in apple

### What is expected?
In Android can choose more pictures

### What is actually happening?

Can only choose a picture

**Comment by JayenLee** [comment]
我也是这个问题。什么时候解决？？

**Comment by baixiaoshi** [comment]
请问解决了吗，原因是什么，我也遇到这个问题，太坑了
