### ISSUE TITLE
3 issue in ant-mobile@2.1.5. The SegmentedControl component invalid on IOS. The Popover component when click mask not hidden on IOS. The InputItem component when use type="money" , the keyboard cover this component.

### ISSUE THREAD

**Issue by sundayha** [ant-design/ant-design-mobile#2299]
### Version
2.1.5

### Environment
`antd-mobule@2.1.5`
`ios 10.3.2(14F89) 和 ios 11`

### Reproduction link
[https://github.com/sundayha/test_app](https://github.com/sundayha/test_app)

### Steps to reproduce
重现步骤点击提供的重现链接即可，很简单。

### What is expected?
fix it thanks

### What is actually happening?
The three component is did not work

---
一个`issue`提了3个问题，请帮忙看下。多谢。

**Comment by warmhug** [comment]
You did not import `fastclick`

**Comment by sundayha** [comment]
@warmhug I import `fastclick` still did not solve the problem.

**Comment by warmhug** [comment]
引入一下不调用，怎么起作用？为什么不仔细看官网文档？

**Comment by sundayha** [comment]
@warmhug 😂 哎从`Ant Design`用过来的，就略过二级菜单的第一项了，以为都跟`Ant Design`一样就直接就用组件了。我的错，十分抱歉增加了你们的工作量。下次我会好好注意的。十分抱歉。

**Comment by warmhug** [comment]
没事，也谢谢。这暴露了我们一个问题，我们文档也需要做优化。

**Comment by HelloHxz** [comment]
我们也遇到了苹果手机segment点击不了的问题；是因为segment `item中div遮住了点击元素的问题。我们使用css简单避开了；
```.am-segment-item-inner{
  display: none;
}```

**Comment by iamwangkj** [comment]
@HelloHxz your method solves my problem.thx.
