### ISSUE TITLE
RN 组件 demo 展示方式

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design-mobile#23]
使用专门的 App 进行预览，用对应版本 App 扫描 demo 的二维码即可。
## App

所有 demo 都打包进一个 bundle，App 每次打开都会尝试更新最新的 demo，二维码只是作为一个索引。

_Note:_ 每发布一个不兼容版本的 antd-mobile，都需要发布一个对应版本的 App 用于预览 demo。
## 网站

每个组件的 demo 代码分别放在两个 Tab 中，一个是 web 版的代码，另外一个是 RN 版的代码。RN 版 的 Tab 里，右侧用于动态演示的部份改为二维码，使用 App 扫描后可以预览 demo。

**Comment by benjycui** [comment]
网站的改动就麻烦 @liqi07 了，bisheng 这边应该不需要做改动。

**Comment by silentcloud** [comment]
> 每发布一个不兼容版本的 antd-mobile，都需要发布一个对应版本的 App 用于预览 demo。

这个最好不要发布 app，只更新 jsbundle

**Comment by benjycui** [comment]
主要是考虑有些还没来得及升级最新版的用户，需要查看旧版的 demo..

**Comment by dyf2015** [comment]
求app

发自我的 iPhone

在 2016年8月3日，09:22，Benjy Cui <notifications@github.com<mailto:notifications@github.com>> 写道：


主要是考虑有些还没来得及升级最新版的用户，需要查看旧版的 demo..

―

**Comment by benjycui** [comment]
@dyf2015 http://mobile.ant.design/changelog

既然决定了要用 App 预览，那么这个二维码也应该要放到显眼的地方？

**Comment by dyf2015** [comment]
感谢

发自我的 iPhone

在 2016年8月3日，10:34，Benjy Cui <notifications@github.com<mailto:notifications@github.com>> 写道：


@dyf2015<https://github.com/dyf2015> http://mobile.ant.design/changelog

既然决定了要用 App 预览，那么这个二维码也应该要放到显眼的地方？

―

**Comment by warmhug** [comment]
issue 无效，关闭
