### ISSUE TITLE
TextareaItem count 属性在用默认值的情况下没有计数

### ISSUE THREAD

**Issue by n417363620** [ant-design/ant-design-mobile#2303]
<TextareaItem
                rows={10}
                onChangeText={(indroduce) => {
                  this.setState({ indroduce: indroduce });
                }}
                value={“简介”}
                defaultValue = {“简介”}
                count={150}
              />

**Comment by warmhug** [comment]
Is it react-native version? **Please follow the issue template to write questions!!!**
