### ISSUE TITLE
Toast.hide()不能全局销毁

### ISSUE THREAD

**Issue by wentoos** [ant-design/ant-design-mobile#2304]
### Version
2.1.5

### Environment
react16.2 

### Reproduction link
[https://mobile.ant.design/components/toast-cn/](https://mobile.ant.design/components/toast-cn/)

### Steps to reproduce
每一个ajax Request Method:OPTIONS (可以销毁) 之后 （第二调用  Toast.loding() 之后） Request Method:POST Toast.hide() 并不能销毁组件

### What is expected?
可以全部销毁

### What is actually happening?
每一个ajax Request Method:OPTIONS (可以销毁) 之后 （第二调用  Toast.loding() 之后） Request Method:POST Toast.hide() 并不能销毁组件

---
export const Post=(url, data=null) =>{
  Toast.loading('加载中...', 0
  );
  return axios({
    method: 'post',
    url: .....,，
    data: data,
  })
    .then((res) => {
       Toast.hide()
        ....
    }).catch(
    err =>{
      Toast.hide()
    }
    )
}
Post(url,{})

**Comment by zongzi531** [comment]
我也遇到了这样的情况，我查看以前的issue是因为没有需求被关闭的，就没有提。过程中我发现toast生成的dom是没有id的，不像modal这样

**Comment by wentoos** [comment]
我还一直以为是 api open 引起的 后来 debug 在发现 第二次 调用 没 反应

**Comment by wentoos** [comment]
// Problem context
// Cross domain request
// 'OPTION' connection success
// Failure to uninstall after 'post' callback is successful


const {Toast, Button} = window["antd-mobile"];


class App extends React.Component{
   
  change = () => {
    var that = this
    Toast.loading('Loading...', 0);
    fetch(' ......',{method:' POST',contentType:'application/json'}).then(res=>{
      Toast.hide()
    }).catch(err=>{
       Toast.hide()
    })
}
  render(){
    return(
      <div>
        <Button type="warning" onClick={this.change}>warning</Button>
      </div>
    )
  }
}
ReactDOM.render(<App />, mountNode);

**Comment by zongzi531** [comment]
你试试这样能不能解决问题@wentoos

```javascript
let ToastFlag = true

export const post = (uri, obj = {}) => {
  ToastFlag && Toast.loading(Nloading, 0)
  ToastFlag = false

  return new Promise((resolve, reject) => {
    axios.post(uri, params)
      .then((res) => {
        ToastFlag = true
        Toast.hide()
        // ...
      })
      .catch((error) => {
        ToastFlag = true
        Toast.hide()
        // ...
  })
}
```

**Comment by joy-yi0905** [comment]
> 你试试这样能不能解决问题@wentoos
> 
> ```js
> let ToastFlag = true
> 
> export const post = (uri, obj = {}) => {
>   ToastFlag && Toast.loading(Nloading, 0)
>   ToastFlag = false
> 
>   return new Promise((resolve, reject) => {
>     axios.post(uri, params)
>       .then((res) => {
>         ToastFlag = true
>         Toast.hide()
>         // ...
>       })
>       .catch((error) => {
>         ToastFlag = true
>         Toast.hide()
>         // ...
>   })
> }
> ```

Not able to solve the problem of multiple Ajax parallel requests!

**Comment by zongzi531** [comment]
@joy-yi0905 I think `Promise.all` can solved this problem.

**Comment by joy-yi0905** [comment]
> @joy-yi0905 I think `Promise.all` can solved this problem.

Hmmm,This requires rewriting a lot of business code. Based on the original loading style, I took the time to rewrite a loading component myself.

**Comment by liufeisprit** [comment]
我也发现这个问题了 关键是多个ajax请求 一个关闭了 下一个toast就不显示了 或者两个toast.loading 写两行 hide就关闭不了

**Comment by sycreece** [comment]
> 我也发现这个问题了 关键是多个ajax请求 一个关闭了 下一个toast就不显示了 或者两个toast.loading 写两行 hide就关闭不了

@liufeisprit @yi-jy You can try code like this:
```bash
let ToastFlag = false;
const ToastArr = [];

// loading 是请求发起的时机
if (loading) {
    if (!ToastFlag) {
      Toast.loading('加载中...', 0);
      ToastFlag = true;
    }
    ToastArr.push('loading');
  } else {
    ToastArr.shift();
    !ToastArr.length && Toast.hide();
  }
```
