### ISSUE TITLE
modal prompt在ios上面输入框点击没有自动获取焦点，并且点击进入输入状态不灵敏

### ISSUE THREAD

**Issue by whhlulu** [ant-design/ant-design-mobile#2306]
### Version
2.1.5

### Environment
ios9.3.2

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/modal](https://mobile.ant.design/kitchen-sink/components/modal)

### Steps to reproduce
官网事例代码，用ios手机二维码扫描打开Modal Prompt，点击输入框不灵敏

### What is expected?
和安卓一样自动获取焦点，或者点击输入框灵敏

### What is actually happening?
IOS点击不灵敏

**Comment by warmhug** [comment]
Trace #2177
