### ISSUE TITLE
PullToRefresh单独页面的使用

### ISSUE THREAD

**Issue by 791060555** [ant-design/ant-design-mobile#2308]
### What problem does this feature solve?
1、tabbs页面一个页面使用pullToRefresh，但是其它的几个页面也能使用下拉刷新，这是我不希望看到的
2、pullToRefresh单独使用，下拉会刷新整个页面，这是不希望看到的，我只想下拉，但是也许并不是使用刷新页面，我可能做其它的操作

### What does the proposed API look like?
我希望在onRefresh回调函数中可以控制具体操作

**Comment by warmhug** [comment]
可以在单独 div 里使用

**Comment by 791060555** [comment]
我知道可以单独使用，请看清我的东西，我提的问题是他的bug和不足
1.首先我确定他是可以单独使用，但是在tabbs模式下会有bug，一个页面使用但是其它页面会should影响
2.下来刷新，我并不是想刷新页面，我也许想触发其它功能

**Comment by zhang740** [comment]
请给出具体的使用demo，预期行为
可以用codepen或者其他方式提供 https://codepen.io/anon/pen/LQyVOq?editors=0010

**Comment by 791060555** [comment]
我知道原因呢，但是我遇到另一个问题，我无法判断我滚动的页面是在顶部下拉，如果的滚动下拉的页面很长，当我滚动中间的时候，我再次下拉，会触发下拉刷新，但是我希望我的页面是在顶部的时候触发下拉刷新的

**Comment by 791060555** [comment]
滚动的内容很长，希望加一个距顶判断，如果滚动的内容到了顶部后才会触发下拉刷新

**Comment by warmhug** [comment]
这个需要自己判断吧，内部滚动，不应该外部文档滚动位置。

**Comment by 791060555** [comment]
问题解决，参考listview实现原理，使用rmc-list-view中的ScrollView就可以判断了

**Comment by qqis314860100** [comment]
请问楼主是如何解决的？我现在也遇到这个问题，在某个tab里下拉刷新发送请求，其余的tab也同时发送请求，如何解决，各tab页处理自己的pulltorefresh？
