### ISSUE TITLE
antd-mobile的单个组件引入时，会引入全局的body样式，这样做是不是有点多余呢，而且违反组件化原则

### ISSUE THREAD

**Issue by LiJiakai** [ant-design/ant-design-mobile#2309]
body {
  background-color: #f5f5f9;
  font-size: 14px;
}
字体大小的我觉得还可以接受，但是背景色，真的有点多余了

**Comment by hugeorange** [comment]
这个 issue 不修复了吗，，，我也是会在body上挂上这两个样式，，我在源码中没找到类似的样式，不知道啥时候挂上去的

**Comment by roytan883** [comment]
两年了，这个问题居然还存在，KPI项目的无奈

解决方法, 需要自己手动屏蔽
```
node_modules\antd-mobile\lib\style\index.less
node_modules\antd-mobile\es\style\index.less

//body {
//  background-color: @fill-body;
//  font-size: @font-size-base;
//}
```

**Comment by kangfenmao** [comment]
### 临时解决办法：

```css
body {
  background-color: #fff !important;
}
```

**Comment by yinsang** [comment]
> ### 临时解决办法：
> ```css
> body {
>   background-color: #fff !important;
> }
> ```

don't use important property。
```
html body{
   background-color: #fff !important;
}
```
is a better choose.

**Comment by yinsang** [comment]
> 两年了，这个问题居然还存在，KPI项目的无奈
> 
> 解决方法, 需要自己手动屏蔽
> 
> ```
> node_modules\antd-mobile\lib\style\index.less
> node_modules\antd-mobile\es\style\index.less
> 
> //body {
> //  background-color: @fill-body;
> //  font-size: @font-size-base;
> //}
> ```

Actually, common.css is import at first in style sheets. 
Normally, you can cover body by 
```
html body{}
```

**Comment by kangfenmao** [comment]
@yinsang 害

**Comment by yinsang** [comment]
> @yinsang 害

?
