### ISSUE TITLE
RefreshControl ReactNative和Web使用有差异

### ISSUE THREAD

**Issue by chenqizheng** [ant-design/ant-design-mobile#231]
- antd-mobile 版本：0.8.2
- 操作系统及其版本：mac
- 浏览器及其版本：Chrome

RefreshControl在ReactNative和Web的使用有差异，希望能封装这两者的差异。

* ReactNative使用如下 :（太长，👇简要的如下,其他无关属性就不贴了）：
`<ListView
 refreshControl={
                        <RefreshControl
                            refreshing={this.state.isRefreshing}
                            onRefresh={this._onRefresh}
                            tintColor="#ff0000"
                            title="Loading..."
                            titleColor="#00ff00"
                            colors={['#ff0000', '#00ff00', '#0000ff']}
                            progressBackgroundColor="#ffff00"
                        />
/>`
 
* Web上使用官网的例子是（太长，👇简要的如下）：

`<RefreshControl>
    <List>
    </List>
</RefreshControl>`

希望能封装这两者的差异。

**Comment by yiminghe** [comment]
ListView 需要重构，目前 refresh-control（局部滚动） 不能和 ListView 一起使用了  @warmhug

**Comment by wv1124** [comment]
最新版本还是不能用么?
< RefreshControl> <ListView> </ListView> </RefreshControl>
这样子,滚不动

**Comment by warmhug** [comment]
1.0-beta 中支持，预计明后天发下

**Comment by warmhug** [comment]
0.9.0-beta.0 已支持
