### ISSUE TITLE
component/tabs change color and use icons

### ISSUE THREAD

**Issue by JFE84** [ant-design/ant-design-mobile#2311]
Is there a way to change the blue text color and blue line color of the tabs component?
I have found this in tabs/style/index.css but nothing happens when modified
.am-tabs-default-bar-underline {
    position: absolute;
    border: 1px #108ee9 solid;
}
.am-tabs-default-bar-tab-active {
     color: #108ee9;
}

I'm also wondering if there is a way to use an icon in here with the same behaviour (change color when tab selected) this comes from the tabs/demo/basic.native.tsx
const tabs = [
        { title: 'First Tab' },
        { title: 'Second Tab' },
        { title: 'Third Tab' },
]
<Tabs
          tabs={tabs}
          initialPage={0}
>

**Comment by zhang740** [comment]
https://mobile.ant.design/components/tabs-cn/

**Comment by JFE84** [comment]
thanks
