### ISSUE TITLE
ListView renderHeader and renderFooter default style 

### ISSUE THREAD

**Issue by Mad-hu** [ant-design/ant-design-mobile#2312]
### Version
2.1.5

### Environment
windows10 Chrome58.0.3029.110 (64-bit)  create-react-app react 16.2.0

### Reproduction link
[https://mobile.ant.design/components/list-view-cn/#components-list-view-demo-basic-sticky](https://mobile.ant.design/components/list-view-cn/#components-list-view-demo-basic-sticky)

### Steps to reproduce
ListView renderHeader and renderFooter default style,Content in renderHeader and renderFooter is affected by default Styles.

### What is expected?
Delete default styles,Or delete the default. am-list-footer and. am-list-header when there a custom renderHeader

### What is actually happening?
when there a renderHeader, the default. Am-list-footer and. Am-list-header still exists,the default padding too bad.....

**Comment by Mad-hu** [comment]
![bug1](https://user-images.githubusercontent.com/13977755/35719644-49af29c6-0825-11e8-878f-6edc1e33158d.png)
![bug2](https://user-images.githubusercontent.com/13977755/35719645-49f69de2-0825-11e8-9869-8a02cda7dce6.png)
![bug3](https://user-images.githubusercontent.com/13977755/35719646-4a2a8e4a-0825-11e8-9194-33b8e1bc8de2.png)

**Comment by KgTong** [comment]
Most of cases，the header and footer is plain text，you can cover the style by yourself...
