### ISSUE TITLE
refactor type definitions

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design-mobile#2315]
Hi.

I try to refactoring `AntM` for `TypeScript` friendly on my fork at `refactor-ts` branch https://github.com/bang88/ant-design-mobile/tree/refactor-ts. if you have any thoughts in this you can checkout and contribute it or let me know.

TODO:

- Enable noImplicitAny
- Add missing type definitions for some components

Thanks.

**Comment by warmhug** [comment]
Welcome pr.

**Comment by bang88** [comment]
Ping @paranoidjk @warmhug 

Please track #2323 for discussions and improvements. but please don't merge it.

**Comment by bang88** [comment]
**summary:**

- [ ] _util
- [ ] accordion
- [ ] action-sheet
- [ ] activity-indicator
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] checkbox
- [ ] create-tooltip
- [ ] date-picker
- [ ] date-picker-view
- [ ] drawer
- [ ] flex
- [ ] grid
- [ ] icon
- [ ] image-picker
- [ ] input-item
- [ ] list
- [ ] list-view
- [ ] locale-provider
- [ ] menu
- [ ] modal
- [ ] nav-bar
- [ ] notice-bar
- [ ] pagination
- [ ] picker
- [ ] picker-view
- [ ] popover
- [ ] popup
- [ ] progress
- [ ] pull-to-refresh
- [ ] radio
- [ ] range
- [ ] refresh-control
- [ ] result
- [ ] search-bar
- [ ] segmented-control
- [ ] slider
- [ ] stepper
- [ ] steps
- [ ] swipe-action
- [ ] switch
- [ ] tab-bar
- [ ] tabs
- [ ] tag
- [ ] text
- [ ] textarea-item
- [ ] toast
- [ ] view
- [ ] white-space
- [ ] wing-blank

**Comment by paranoidjk** [comment]
👍 https://github.com/ant-design/ant-design-mobile/issues/1212

**Comment by bang88** [comment]
Its done  after https://github.com/react-component/m-date-picker/pull/52 merged

ping @paranoidjk @warmhug

**Comment by bang88** [comment]
🚶 

https://github.com/afc163/array-tree-filter/pull/4
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23389
