### ISSUE TITLE
TextareaItem in Modal alert, not change focus and not scroll in IOS

### ISSUE THREAD

**Issue by whhlulu** [ant-design/ant-design-mobile#2321]
### Version
2.1.3

### Environment
ios

### Reproduction link
[https://codepen.io/anon/pen/OQNdor](https://codepen.io/anon/pen/OQNdor)

### Steps to reproduce
clickModal1 = () => {
        alert('Delete', <TextareaItem
            rows={3}
            placeholder="fixed number of lines"
        />, [
            {text: 'Cancel', onPress: () => console.log('cancel'), style: 'default'},
            {text: 'OK', onPress: () => console.log('ok')},
        ]);
    }   
 render() {
        return (
            <div>
                <Button onClick={this.clickModal1}>test</Button>
            </div>
        );
    }

### What is expected?
可以滚动，可以改变焦点

### What is actually happening?
不能改变焦点

---
在ios上面，Modal、prompt在2.1.3的时候不容易获取焦点，我就利用alert自己写TextareaItem，这样可以获取焦点，但是输入多行后不能修改焦点，不能滚动

**Comment by quentinyang** [comment]
@whhlulu 看你codepen的demo，是没问题的。问下，现在还会重现吗？
