### ISSUE TITLE
Modal footer button vertical alignment

### ISSUE THREAD

**Issue by fi0** [ant-design/ant-design-mobile#2325]
### Version
antd mobile 2.1.6
react-native

### Environment
iOS simulator / iOS 11.2

### Steps to reproduce
https://imgur.com/a/WuXKj

```
import { Modal, Button } from 'antd-mobile';

const alert = Modal.alert;

        <Button onClick={() => alert('Title', 'message', [
          { text: '取消', onPress: () => console.log('cancel'), style: 'default' },
          { text: '取消', onPress: () => console.log('cancel'), style: 'default' }
        ])}
        >confirm</Button>
```

### What is expected?
The button should be vertically aligned centered

### What is actually happening?
There's extra spacing below the button text.

**Comment by fi0** [comment]
related to https://github.com/ant-design/ant-design-mobile/blob/2.1.6/components/modal/style/index.native.tsx#L100

**Comment by fi0** [comment]
Should we use `justifyContent: 'center'` here?

**Comment by liyanxi** [comment]
antd mobile 2.1.8
Modal.alert bottom button 
The button not vertically aligned centered as yet

**Comment by liyanxi** [comment]
@warmhug

**Comment by liyanxi** [comment]
@warmhug @fi0 did you solve it?

**Comment by warmhug** [comment]
Why not have a pr？
