### ISSUE TITLE
为什么atn-mobile中的边框都是用的伪元素生成而不是直接写边框样式呢？

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#233]
![image](https://cloud.githubusercontent.com/assets/9410091/18354611/d191049a-7618-11e6-8d42-0638d882a433.png)
如上图，ant-mobile中的边框几乎都是这种格式，为什么不直接写：
```css
    border-bottom: 1px solid #ddd;
```
我找些资料说的是
 > 因为边框要计算盒子模型.而我们在移动端可能使用的是自适应布局的方式.这样计算边框很费劲. 
因此,使用模拟边框的方法,就可以不用考虑边框的宽度的问题了,这样更加方便. 
当然,使用 box-sizing:border-box 这样的属性也可以将边框不计算在盒子模型里. 
而且这种方法在很多现代CSS框架上都使用着. 
但是我个人不推荐这种做法.因为,这样padding也不计算在盒子模型里面了. 
反正我不喜欢这样的做法.所以我就模拟边框啦!

不过这种说法不能让我完全信服，有人可以现身说法吗？

**Comment by minooo** [comment]
@silentcloud 可以解惑下吗？

**Comment by Justforfei** [comment]
另外：使用了postion:absolute; 就不需要再用用 display:block;了， 这里有点多余

**Comment by pingan1927** [comment]
没啥特殊的，
* 因为最后一个`List.Item`的下边框和`List.Body`的边框要重叠在一起。如果写的`border`，`Body`的`Border`就不好覆盖`List.Item`的边框。
* `List.Item`整个高度包含了边框，这样可以严格按照设计师的要求实现。

总之，伪元素或者直接写`border`如果效果一样，没有什么偏见的。

**Comment by pingan1927** [comment]
@Justforfei 代码还有很多值得推敲的，谢谢指正，会尽快确认。

**Comment by minooo** [comment]
谢谢回答，私以为完全可以用
```
:last-child { ... }
```
解决最后一个边框的问题嘛，不过这是个人的选择问题。

**Comment by pingan1927** [comment]
```
:last-child { ... }
```
把问题想的太简单了，这样不够
