### ISSUE TITLE
When is 3.0 out?

### ISSUE THREAD

**Issue by thelaith** [ant-design/ant-design-mobile#2332]
### What problem does this feature solve?
Hello

I've been checking out this project, thinking about using it for a mobile app. I saw that Ant Design 3.0 came out couple weeks ago, and was wondering when Ant Mobile 3.0 is gonna be out.

Best Regards, Laith

### What does the proposed API look like?
.

**Comment by warmhug** [comment]
Sorry, there is currently no specific schedule. Thanks for attention and welcome to use the latest 2.x version now.
