### ISSUE TITLE
界面问题，体验非常不好

### ISSUE THREAD

**Issue by zheng1013757145** [ant-design/ant-design-mobile#2334]
http://new-issue.ant.design?repo=ant-design-mobile

界面从下到上滚动会卡住  360极速浏览器

**Comment by paranoidjk** [comment]
> 学会如何提问。


哪个界面？给出链接。

**Comment by zheng1013757145** [comment]
所有的页面，都有这个毛病 卡屏闪屏（我想给你发截图，但是老报错）

**Comment by gaollard** [comment]
@zheng1013757145  I countered the same issue
