### ISSUE TITLE
建议：增加一个上拉加载下一页数据的组件，类似于下拉刷新

### ISSUE THREAD

**Issue by zhangbing609** [ant-design/ant-design-mobile#234]
#### 建议增加一个下拉加载下一页的组件

参考：https://vux.li/#!/component/pulldown-pullup
#### 建议升级flex组件，让其可用设置占宽比例

参考：https://vux.li/#!/component/flexbox

**Comment by silentcloud** [comment]
@zhangbing609  下拉加载下一页的组件 listView 已经有了 `onEndReached`

**Comment by huiop368** [comment]
@silentcloud  现在 加载更多 已经是和 listview 绑死了?

**Comment by silentcloud** [comment]
恩 是的， 和 react-native 保持 api 一致

**Comment by warmhug** [comment]
开始支持 https://github.com/react-component/m-list-view/commit/a6c4c1c43b2cb9f91c90a6cb8bea69a55ad53cf9

**Comment by warmhug** [comment]
不常用，暂不支持
