### ISSUE TITLE
How to use a Button to pop a Picker!!!

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design-mobile#2340]
### What problem does this feature solve?
Click a Button to init a Picker!!

### What does the proposed API look like?
Click a Button to init a Picker!!

**Comment by koupeng** [comment]
OK, I have used Modal+PickerView to solve the problem.

**Comment by zmayor** [comment]
I found a solution by adding`ref` attribute on the child of `Picker`.
[https://codepen.io/zmayor/pen/aGBzjV](url)

**Comment by miaoyuxinbaby** [comment]
@zmayor  thank you
