### ISSUE TITLE
请问在antd-mobile中通过create-react-app搭建环境，无法使用Tabs.TabPane，请问怎么解决

### ISSUE THREAD

**Issue by ashenBourne** [ant-design/ant-design-mobile#2342]
![image](https://user-images.githubusercontent.com/34472955/36317258-981ec3ac-1377-11e8-8f00-58717aa8dcf0.png)

**Comment by warmhug** [comment]
注意引用的版本号

**Comment by yamakasiluke** [comment]
can you fix this or not?
