### ISSUE TITLE
Tabs.DefaultTabBar is wrong

### ISSUE THREAD

**Issue by hrh94** [ant-design/ant-design-mobile#2344]
<Tabs
            tabs={monitor.all}
            prerenderingSiblingsNumber={0}
            usePaged
            // onChange={(tab, index) => { console.warn('onChange', index, tab); }}
            // onTabClick={(tab, index) => { console.warn('onTabClick', index, tab); }}
          >
            <Tabs.DefaultTabBar
              page={4}
            >
              {
                monitor.all.map((v, k) => (
                  <View key={k} style={{ width, height: 150, alignItems: 'center', justifyContent: 'center', backgroundColor: '#cccccc' }}>
                    {this.renderCell()}
                  </View>
                ))
              }
            </Tabs.DefaultTabBar>
          </Tabs>

TypeError: undefined is not an object(evaluating 'this.props.scrollValue.addListener')

**Comment by hrh94** [comment]
Is it wrong for me to use the wrong way ？

**Comment by zhang740** [comment]
https://mobile.ant.design/components/tabs-cn/
