### ISSUE TITLE
NoticeBar background color cannot be set

### ISSUE THREAD

**Issue by hrh94** [ant-design/ant-design-mobile#2345]

**Comment by warmhug** [comment]
Need a more detailed description.

**Comment by hrh94** [comment]
![tim 20180222153413](https://user-images.githubusercontent.com/16442574/36525745-37a86334-17e6-11e8-8ffd-d237e6ae966d.png)
Look at this. The background color of NoticeBar is light yellow. Now I want to modify the background color to be transparent in react-native.But I can't find how to change it
