### ISSUE TITLE
PullToRefresh拉动太远距离

### ISSUE THREAD

**Issue by www122** [ant-design/ant-design-mobile#2346]
### What problem does this feature solve?
可以定义拉动到多少距离不能再拉动，现在可以无限拉动

### What does the proposed API look like?
可以定义拉动距离，拉动到指定距离后不能再拉动，可参考原生下拉刷新

**Comment by zhang740** [comment]
https://github.com/react-component/m-pull-to-refresh/blob/f7f7cf84769ebc174b453f657f2452c131ec66f9/src/PullToRefresh.tsx#L187

**Comment by code-artisan** [comment]
+1

**Comment by lifengsbotlp** [comment]
同样想解决此问题，请问楼主解决没？
