### ISSUE TITLE
月份组件

### ISSUE THREAD

**Issue by wentoos** [ant-design/ant-design-mobile#2348]
### Version
2.1.5

### Environment
react

### Reproduction link
[https://mobile.ant.design/components/date-picker-cn/](https://mobile.ant.design/components/date-picker-cn/)

### Steps to reproduce
月份组件 value 值应该为 年 月 不应该年月日吧

### What is expected?
月份组件 value 值应该为 年 月 不应该年月日吧

### What is actually happening?
月份组件 value 值应该为 年 月 不应该年月日吧

**Comment by warmhug** [comment]
value 值不是年月日，一直是 Date 实例，不管 mode 设置为什么。所以，展示上可能需要自己 format 一下。

**Comment by wentoos** [comment]
![image](https://user-images.githubusercontent.com/27837972/36578431-2a13c80a-1898-11e8-9af0-911ae55701e3.png)
![image](https://user-images.githubusercontent.com/27837972/36578434-2ff86938-1898-11e8-8f20-ae2b818795e6.png)

**Comment by wentoos** [comment]
format 并不能解决

**Comment by wentoos** [comment]
既然是月份怎能显示其他的呢
