### ISSUE TITLE
Stepper 手动输入

### ISSUE THREAD

**Issue by Benjamin369** [ant-design/ant-design-mobile#2350]
### Version
2.1.6

### Environment
react

### Reproduction link
[https://mobile.ant.design/components/stepper-cn/](https://mobile.ant.design/components/stepper-cn/)

### Steps to reproduce
案例中，使用按钮将Show number value设为1，然后再手动输入更改值，输入值会自动递减直至1。
In the case, If you use a button, set the value to 1, and then manually enter the change value, and the input value will decrease automatically to 1.

### What is expected?
将Show number value设为1后，可以手动输入更改值

### What is actually happening?
暂无

**Comment by Benjamin369** [comment]
In the case, If you use a button, set the value to 1, and then manually enter the change value, and the input value will decrease automatically to 1.

**Comment by paranoidjk** [comment]
ping @zhang740 看 @warmhug 的评论

**Comment by doxiaodong** [comment]
升级最新版 ant-design-mobile ,重新安装依赖。
