### ISSUE TITLE
Iphone真机使用Modal,为什么长按才能获取input焦点

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design-mobile#2351]
### Version
2.1.6

### Environment
Iphone

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile](http://new-issue.ant.design/?repo=ant-design-mobile)

### Steps to reproduce
Iphone真机使用Modal,为什么长按才能获取input焦点

### What is expected?
Iphone真机使用Modal,单击或者自动获取焦点

### What is actually happening?
Iphone真机使用Modal,长按才能获取input焦点

**Comment by koupeng** [comment]
@paranoidjk

**Comment by zmayor** [comment]
同问

**Comment by warmhug** [comment]
Trace #2177
