### ISSUE TITLE
ImagePicker 的属性 onChange 所带参数缺少

### ISSUE THREAD

**Issue by s1nker** [ant-design/ant-design-mobile#2353]
## Version
2.1.6

## Environment
iOS WKWebview

## Steps to reproduce
点击 `ImagePicker` 组件的新增图片按钮，选定图片

## What is expected?
在 `onChange` 回调中的参数带有 `index`

## What is actually happening?
在 `onChange` 回调中的第三个参数输出为 `undefined`

## p.s.
line 98 in [ant-design-mobile/components/image-picker/index.tsx](https://github.com/ant-design/ant-design-mobile/blob/master/components/image-picker/index.tsx)

```
addImage = (imgItem) => {
    const { files = [] } = this.props;
    const newImages = files.concat(imgItem);
    if (this.props.onChange) {
      this.props.onChange(newImages, 'add');
    }
  }
```

**Comment by EdisonSu768** [comment]
same issue

**Comment by zhangwen1932** [comment]
same issue
