### ISSUE TITLE
Drawer在rn使用中，点击空白透明层收起，没有事件回调无法确定状态，进行管理

### ISSUE THREAD

**Issue by ahz549467483** [ant-design/ant-design-mobile#2355]
### Version
2.1.6

### Environment
 react-native 

### Reproduction link
[https://mobile.ant.design/components/drawer-cn/](https://mobile.ant.design/components/drawer-cn/)

### Steps to reproduce
点击空白透明层收起，没有事件回调无法确定状态，进行管理

### What is expected?
存在一个回调方法进行状态管理

### What is actually happening?
没有任何获取状态的方法

**Comment by warmhug** [comment]
`onOpenChange` 文档不是写了吗
