### ISSUE TITLE
Android SegmentedControl tintColor设置白色，title选中状态不对

### ISSUE THREAD

**Issue by yinchonging** [ant-design/ant-design-mobile#2359]
### Version
2.1.6

### Environment
"react-native": "^0.52.0","antd-mobile": "^2.1.6", Android 6.0

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/issues?utf8=%E2%9C%93&q=SegmentedControl](https://github.com/ant-design/ant-design-mobile/issues?utf8=%E2%9C%93&q=SegmentedControl)

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
无

---
源码是这么写的：

> var itemStyle = {
color: selected ? '#fff' : tintColor,
backgroundColor: selected ? tintColor : 'transparent',
borderColor: tintColor
};

color选中为白色，但ios显示为蓝色，android显示为白色，如果设置tintColor为白色，问题即出现

![2018-02-28 3 26 05](https://user-images.githubusercontent.com/2151476/36775471-218f298c-1c9d-11e8-98ba-93f7aefa9833.png)

**Comment by warmhug** [comment]
底色为蓝色引起的问题？这种颜色设置需要搭配着做吧...
