### ISSUE TITLE
How to style List Header???

### ISSUE THREAD

**Issue by yingliangzhang** [ant-design/ant-design-mobile#2360]
### What problem does this feature solve?
I can't find a way to style the header of a List. When I inspect the element I can see the Text component nested inside List as the header and it has styles, but how do I override these?

### What does the proposed API look like?
Add property `headerStyle` or `headerClass` to `List` component.

![snip20180301_9](https://user-images.githubusercontent.com/3793091/36825375-2009a060-1d5b-11e8-8b0e-fea767e0bd21.png)

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/components/list/style/index.native.tsx#L8

https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui#antd-mobile-with-rn-custom-ui
