### ISSUE TITLE
angular ver. of ant-design-mobile

### ISSUE THREAD

**Issue by icycore** [ant-design/ant-design-mobile#2361]
### What problem does this feature solve?
We plan to use ant design mobile in our project,it's realy nice!  
We plan to use the ant-design-mobile with angular.  
Do you guys have a roadmap to relrease it?  
Waiting for your replay, thanks 

### What does the proposed API look like?
angular ver. of ant-design-mobile

**Comment by paranoidjk** [comment]
Trace https://github.com/ant-design/ant-design-mobile/issues/2197

**Comment by fisherspy** [comment]
@icycore http://ng.mobile.ant.design

**Comment by icycore** [comment]
> @icycore http://ng.mobile.ant.design

already in use. many thanks~
