### ISSUE TITLE
InputItem focus event can't trigger keyboard in mobile

### ISSUE THREAD

**Issue by Chryseis** [ant-design/ant-design-mobile#2362]
### Version
2.1.6

### Environment
react ,iphone X,Safari 

### Reproduction link
[https://codesandbox.io/s/y230pn8091](https://codesandbox.io/s/y230pn8091)

### Steps to reproduce
mobile load Link 

### What is expected?
keyboard can be triggered

### What is actually happening?
keyboard can't be triggered

**Comment by micooz** [comment]
Please try:

```js
<InputItem
  placeholder="password"
  clear
  type="password"
  ref={ref => setTimeout(() => ref.focus())}
/>
```
