### ISSUE TITLE
can't close modal in React@16

### ISSUE THREAD

**Issue by belief-cyf** [ant-design/ant-design-mobile#2363]
### Version
2.1.6

### Environment
window 10  chrome

### Reproduction link
[https://mobile.ant.design/components/modal-cn/](https://mobile.ant.design/components/modal-cn/)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/19991842/36887217-1caa88c8-1e2b-11e8-981c-f19d6082551d.png)
![image](https://user-images.githubusercontent.com/19991842/36887244-3c1e6c1a-1e2b-11e8-806e-8ac6325f7522.png)
![image](https://user-images.githubusercontent.com/19991842/36887250-4662b212-1e2b-11e8-96fb-9e86aca3e5be.png)
click cancel
![image](https://user-images.githubusercontent.com/19991842/36887260-556c1370-1e2b-11e8-9bf6-8f56e93fbbaa.png)
![image](https://user-images.githubusercontent.com/19991842/36887270-644f35a2-1e2b-11e8-9474-83faec99dcb2.png)
mask is delete,bug modal is not delete.
react And ract-dom version is 16.2.0
### What is expected?
click cancel close modal

### What is actually happening?
can't close modal

**Comment by belief-cyf** [comment]
![image](https://user-images.githubusercontent.com/19991842/36887528-a3eaef7a-1e2c-11e8-9828-ebb7296d99c2.png)

**Comment by belief-cyf** [comment]
use Modal.alert(title, message, actions?, platform?).close() is same

**Comment by belief-cyf** [comment]
I experimented with react 15.X  is working.

**Comment by belief-cyf** [comment]
node V8.9.3      npm V5.5.1

**Comment by likezero** [comment]
can you upgrade antd-mobile to 2.1.8, and add fastclick to you project ?

**Comment by belief-cyf** [comment]
It's my project scaffolding problem. i will close this issues

**Comment by huang-xiao-jian** [comment]
@belief-cyf what's the problem? I have the same issue within create-react-app project?
