### ISSUE TITLE
The icon property of Tabbar.Item can not use the Icon component

### ISSUE THREAD

**Issue by Mydly** [ant-design/ant-design-mobile#2364]
### Version
2.1.6

### Environment
Operating system and version: MacOS 10.12 Browser and version: chrome 

### Reproduction link
[https://github.com/Mydly/moveapp/blob/master/App.js](https://github.com/Mydly/moveapp/blob/master/App.js)

### Steps to reproduce
sudo npm install
yarn run and

### What is expected?
display the icon on the Tabbar

### What is actually happening?
not display the icon on the tabbar

---
The follow is main code.

<TabBar
      unselectedTintColor="#949494"
      tintColor="#33A3F4"
      barTintColor="white"
      hidden={this.state.hidden}
    >
      <TabBar.Item
        title="Life"
        key="Life"
        icon={\<Icon type="search" size={20} \/>}
        selected={this.state.selectedTab === 'blueTab'}
        onPress={() => {
          this.setState({
            selectedTab: 'blueTab',
          });
        }}
      >
      </TabBar.Item>
</TabBar>

**Comment by olga-giza** [comment]
Try just `icon={require('./alipay.png')}`

**Comment by Mydly** [comment]
icon={<Icon type="search" size={20} />}
This cannot work.

**Comment by olga-giza** [comment]
In docs https://mobile.ant.design/components/tab-bar/ there is info that only types Image Source(rn) \ web ref demo can be passed. Icon component is not a valid argument.
Using only required image as argument works for me ;)

**Comment by Mydly** [comment]
In the ant-design-mobile source code, I see that the Image component including the Icon is usable. However, it cannot be displayed properly. May use Image component in future releases

**Comment by ecgan** [comment]
I am facing the same issue as well. Would like to see TabBar.Item able to support Icon component with font icon.

**Comment by ecgan** [comment]
Version
2.1.6

Environment
Operating system and version: MacOS
Using the component in react native. 

Steps to reproduce
I can put this into a `<View>` and it display a check properly.

<Icon type="check" /> 

<img width="412" alt="screen shot 2018-03-12 at 1 00 38 am" src="https://user-images.githubusercontent.com/417342/37256076-daed5baa-2590-11e8-99b8-2c105d742145.png">

However, when I put the check icon into TabBar.Item Icon property, I see a red error screen saying "non-std C++ exception". 

```
        <TabBar>
          <TabBar.Item
            title="Life"
            key="Life"
            icon={(<Icon type="check" />)}
            selected={true}
            badge={1}
          >
            <View><Text>tab 1</Text></View>
          </TabBar.Item>
        </TabBar>
```

<img width="409" alt="screen shot 2018-03-12 at 1 05 12 am" src="https://user-images.githubusercontent.com/417342/37256132-79d0a9e8-2591-11e8-809d-6df82f0aa31e.png">


What is expected?
The check icon font should be able to render properly in the TabBar. 

What is actually happening?
Red error screen.

**Comment by warmhug** [comment]
There is no problem in the Web version @Mydly .
@ecgan 's problem in the react native version, cc @zhang740

**Comment by bang88** [comment]
For RN version only accept `ImageSource` ATM.

**Comment by ecgan** [comment]
@warmhug , @bang88 , 
Thanks for the response. I hope there is a plan to make the TabBar.Item support the Icon component / font icon in React Native app.

**Comment by warmhug** [comment]
Close for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452
https://github.com/ant-design/ant-design-mobile/issues/2444#issuecomment-391607025
