### ISSUE TITLE
image-picker Android 低版本选图报错

### ISSUE THREAD

**Issue by q594989927** [ant-design/ant-design-mobile#2366]
### Version
2.0.0

### Environment
Android 4.1.1

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/image-picker?lang=zh-CN#image-picker-demo-0](https://mobile.ant.design/kitchen-sink/components/image-picker?lang=zh-CN#image-picker-demo-0)

### Steps to reproduce
使用系统自带浏览器打开image-picker 官方示例页面，点击选图，选中图片

### What is expected?
image-picker 成功添加一张已选择的图片

### What is actually happening?
没有出现已选择的图片，在AndroidStudio logcat 中看到js报错信息：
E/browser: Console: Uncaught TypeError: Object [object File] has no method 'slice' https://mobile.ant.design/kitchen-sink/components/image-picker/demo.js:1

---
ant-mobile 支持版本为 4.0 ，目前市场上仍然有相当一部分4.x的Android手机，希望能够有效支持这一部分低版本机型。

**Comment by q594989927** [comment]
问题在Android 4.0-4.3 都存在

**Comment by skidxjq** [comment]
在4.3机型上没有复现出来，目前4.0机型市面上很少
如有必要，麻烦提供详细机型

**Comment by q594989927** [comment]
使用Android模拟器测试时发生的，
