### ISSUE TITLE
Tab's initialPage value is ignored in React Native

### ISSUE THREAD

**Issue by stonecold123** [ant-design/ant-design-mobile#2368]
### Version
2.1.6

### Environment
React Native

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo](https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo)

### Steps to reproduce
Open the RN demo in expo.

### What is expected?
The content of second tab should be shown first when the value of `initialPage` is set to 1 in the demo.

### What is actually happening?
There's a bug regarding `initialPage` in react native. You can see the bug in the expo demo for RN version.

Unlike the web version, when `intiial page` is set to 1, the content of the first tab is rendered and shown first even though the TabBar has the "Second Tab" highlight in blue.

**Comment by zhang740** [comment]
RN version? iOS or Android?

**Comment by stonecold123** [comment]
@zhang740 
On android.

**Comment by warmhug** [comment]
It works properly in https://github.com/react-component/m-tabs . So it should work correctly in your project.
Maybe it is affected by other components in antd-mobile ? cc @silentcloud

**Comment by warmhug** [comment]
Close for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452

**Comment by huandie2012** [comment]
我也遇到了相似的问题

**Comment by huandie2012** [comment]
在页面不刷新的情况下，及时render已经重新渲染了，initialPage的值还是不变，导致tab-active不能回到初始位置
