### ISSUE TITLE
reactnative提示antd-mobile为unknown module

### ISSUE THREAD

**Issue by bjwulin** [ant-design/ant-design-mobile#237]
#### 本地环境

- antd-mobile 版本：0.8.1
- 操作系统及其版本：win7
- 浏览器及其版本：android6

#### 你做了什么？
import { Button } from 'antd-mobile';

`<Button>test</Button>`
#### 你期待的结果是：

正确显示按钮

#### 实际上的结果：

requiring unknown module "antd-mobile"

#### 可重现的在线演示

package.json:

  "dependencies": {
    "react": "15.3.1",
    "react-dom": "^15.3.1",
    "react-native": "0.32.0",
    "antd-mobile": "^0.8.1"
  },
  "devDependencies": {
    "babel-plugin-antd": "^0.5.1"
  }

.babelrc:
{
 "plugins": [["antd", { "style": "css", "libraryName": "antd-mobile" }]]
}

**Comment by yiminghe** [comment]
请自行研究 https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo

**Comment by huliyou** [comment]
@yiminghe  [https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo]( https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo)
项目无法运行

npm i & npm start
![image](https://cloud.githubusercontent.com/assets/3860373/18431568/08306dc0-7910-11e6-8587-82176c627f0a.png)

react-native run-ios // ios
![image](https://cloud.githubusercontent.com/assets/3860373/18431625/664002ae-7910-11e6-879a-964596ad44a4.png)

**Comment by summersky92** [comment]
@yiminghe    
https://github.com/ant-design/antd-init/blob/master/boilerplates/MobileDemo/index.web.js#L1里面都这么引用的 import { DatePicker, List } from 'antd-mobile'; 
跑了之后会显示unknown package，是因为无法直接import包名导致错误 ，但是单独引用没问题， 比如(import SegmentedControl from 'antd-mobile/lib/segmented-control';）

所以是改成了每个都要一个个import麽？类似，https://github.com/ant-design/ant-design-mobile/issues/300

**Comment by yiminghe** [comment]
https://github.com/ant-design/babel-plugin-import
