### ISSUE TITLE
ImagePicker in react native must the onAddImageClick method be implemented?

### ISSUE THREAD

**Issue by wfxphoebus** [ant-design/ant-design-mobile#2370]
### Version
2.1.6

### Environment
react-native

### Reproduction link
[https://mobile.ant.design/components/image-picker-cn/](https://mobile.ant.design/components/image-picker-cn/)

### Steps to reproduce
On the react native, use the imagepicker component.

### What is expected?
like web

### What is actually happening?
Unhandled JS Exception: TypeError: Cannot read property 'getPhotos' of undefined

**Comment by wfxphoebus** [comment]
我的意思是，ImagePicker有没有实现选择图片的功能，在 web 页面里是可以的，在 react native
可以直接选择图片么？

**Comment by paranoidjk** [comment]
可以
