### ISSUE TITLE
Tabs.DefaultTabBar covers the style of the renderTab

### ISSUE THREAD

**Issue by hrh94** [ant-design/ant-design-mobile#2371]
![tim 20180306114538](https://user-images.githubusercontent.com/16442574/37013340-4051d4dc-2134-11e8-87f6-634713defedf.png)
![tim 20180306114226](https://user-images.githubusercontent.com/16442574/37013344-4349cf46-2134-11e8-8368-46ddae97ceef.png)

**Comment by zhang740** [comment]
when use `renderTabBar` and `renderTab`, put `renderTab` to renderTabBar -> Tabs.DefaultTabBar's props.

**Comment by hrh94** [comment]
It works,thanks
