### ISSUE TITLE
TextareaItem里设置clear属性为true后点击清除按钮 内容并没有被清除

### ISSUE THREAD

**Issue by zackteng** [ant-design/ant-design-mobile#2372]
### Version
2.1.6

### Environment
macOS 10.13.3  Chrome 64.0.3282.186

### Reproduction link
[https://mobile.ant.design/components/textarea-item-cn/](https://mobile.ant.design/components/textarea-item-cn/)

### Steps to reproduce
在clear属性为true的TextareaItem里输入文字后 点击清除按钮

### What is expected?
TextareaItem里的文字被清除

### What is actually happening?
文字并没有被清除
http://o8qqvasyd.bkt.clouddn.com/ezgif.com-video-to-gif.gif

**Comment by zackteng** [comment]
@warmhug 有空帮看下呗

**Comment by paranoidjk** [comment]
测试正常，无法复现

**Comment by alwaysloseall** [comment]
@paranoidjk 就他发的那个复现链接里面的示例就是清除不掉的，代码里面也是有错误的

**Comment by paranoidjk** [comment]
不要在 PC 上测试，用真机，有些组件依赖 TouchEvent.

**Comment by zackteng** [comment]
@paranoidjk 
那我再补充一个真机上的gif吧
Version
2.1.6

Environment
Andriod 8.0.0
MIUI版本 MIUI9 8.3.8
浏览器 Chrome 64.0.3282.137

[gif图看不了点这里](http://o8qqvasyd.bkt.clouddn.com/textareaitem-clear-not-work.gif)
![gif图](http://o8qqvasyd.bkt.clouddn.com/textareaitem-clear-not-work.gif)

**Comment by paranoidjk** [comment]
IOS 无法复现。 @zhang740 @warmhug Android 机测试一下。

**Comment by paranoidjk** [comment]
<img width="532" alt="2018-03-22 11 39 39" src="https://user-images.githubusercontent.com/7971415/37750058-f2e8a8ee-2dc5-11e8-82bc-e137a1db9ba3.png">

**Comment by alwaysloseall** [comment]
@paranoidjk 这个问题在我那个pr里面是解决了的 不过已经被关了

**Comment by alwaysloseall** [comment]
@paranoidjk 原因就是onBlur会导致clear icon消失，解决方案就是参照inputItem同样的做法处理的

**Comment by modao** [comment]
So, is there any plan to fix this issue?
