### ISSUE TITLE
something wrong from component Drawer under iPhone

### ISSUE THREAD

**Issue by jun58** [ant-design/ant-design-mobile#2374]
### Version
2.1.6

### Environment
ios 11.2.5 safari

### Reproduction link
[https://mobile.ant.design/components/drawer-cn/](https://mobile.ant.design/components/drawer-cn/)

### Steps to reproduce
Scan QR code from [Drawer](https://mobile.ant.design/components/drawer-cn/) and open page on **iPhone safari**

### What is expected?
open and close Drawer no Shake

### What is actually happening?
open and close Drawer, **Shake happen**

---
when there are **many colors** on Drawer, shake is same, but the shake view is **more distinct!**

**Comment by paranoidjk** [comment]
没理解你说的意思，用中文表述吧，或者给出 gif 或 视频

**Comment by jun58** [comment]
@paranoidjk，就是Drawer（抽屉）组件，我之前用的时候在手机上，有抖动，然后我看官网的例子在手机上也有抖动，看了代码没发现什么问题，今天我又看，发现有没有抖动了 `~`
