### ISSUE TITLE
DatePicker的datetime模式，在iOS屏幕宽度不够时，左边的年不显示

### ISSUE THREAD

**Issue by wangjx3** [ant-design/ant-design-mobile#2378]

**Comment by warmhug** [comment]
是 不显示 还是 显示不全？

**Comment by wangjx3** [comment]
你可以试一下，iPone5s上，左边的年完全不显示，由于比较紧急，我已经用你们的Picker封装了一个DatePicker.现在可以正常使用




| |
邮箱：rockywzz@163.com
|

签名由 网易邮箱大师 定制

在2018年03月13日 15:08，warmhug 写道：

是 不显示 还是 显示不全？

**Comment by warmhug** [comment]
在iOS模拟器里没发现问题，估计跟系统版本有关系？你封装的 datepicker 是怎么解决你这个问题的？

**Comment by wangjx3** [comment]
年字不显示出来




| |
邮箱：rockywzz@163.com
|

签名由 网易邮箱大师 定制

在2018年03月13日 15:28，warmhug 写道：

在iOS模拟器里没发现问题，估计跟系统版本有关系？你封装的 datepicker 是怎么解决你这个问题的？

**Comment by wangjx3** [comment]
不会吧，我用模拟器会不显示左边的年份




| |
邮箱：rockywzz@163.com
|

签名由 网易邮箱大师 定制

在2018年03月13日 15:29，wangjx3 写道：
年字不显示出来




| |
邮箱：rockywzz@163.com
|

签名由 网易邮箱大师 定制

在2018年03月13日 15:28，warmhug 写道：

在iOS模拟器里没发现问题，估计跟系统版本有关系？你封装的 datepicker 是怎么解决你这个问题的？

**Comment by lzctbyong** [comment]
比如2007
只显示200...
iphone5小屏幕手机会出现这问题

**Comment by warmhug** [comment]
建议自己覆盖样式吧

**Comment by Roxyhuang** [comment]
该问题已成功复现
Demo:https://codepen.io/Neo_huang/pen/xJwoXg

![image](https://user-images.githubusercontent.com/12892693/42724660-2240db4c-87a9-11e8-912b-6593248294d3.png)

其实官网文档有如下提示：

注意：日期字符串在不同浏览器有不同的实现，例如 new Date('2017-1-1') 在 Safari 上是 Invalid Date，而在 Chrome 上是能正常解析的。

但是还是建议将该处默认值的文档修改，谢谢

![image](https://user-images.githubusercontent.com/12892693/42724675-54b3721a-87a9-11e8-9bea-18c328b05d5d.png)
