### ISSUE TITLE
Steps步骤条，怎样与ListView结合实现下拉刷新动态加载

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design-mobile#2379]
### What problem does this feature solve?
Steps步骤条，怎样与ListView结合实现下拉刷新动态加载

### What does the proposed API look like?
Steps步骤条，怎样与ListView结合实现下拉刷新动态加载

**Comment by koupeng** [comment]
配合使用PullToRefresh解决此问题。

**Comment by koupeng** [comment]
效果不好，还是想放到ListView中！！！

**Comment by warmhug** [comment]
没能清楚想象到你的需求，ListView 是个抽象组件、怎么放具体的功能效果？欢迎提供详细的建议和方案。

**Comment by koupeng** [comment]
@warmhug ListView下拉动态刷新，可以动态加载Steps中的step,,目前使用如下方法解决：ListView的row只有一行数据，在这个大行数据里动态加载step。
PS：我就是想在ListView中动态加载Step.但是Step又必须在Steps中才有连线效果，所以感觉放在ListView中不好放。
`<Steps>
  <Step title="第一步" />
  <Step title="第二步" />
  <Step title="第三步" />
</Steps>`
