### ISSUE TITLE
Carousel vertical invalid with  react native  

### ISSUE THREAD

**Issue by artOfWarBut** [ant-design/ant-design-mobile#2380]
### Version
2.1.5

### Environment
react-native 0.52.2

### Reproduction link
[https://mobile.ant.design/components/carousel-cn/#components-carousel-demo-basic](https://mobile.ant.design/components/carousel-cn/#components-carousel-demo-basic)

### Steps to reproduce
vertical invalid

### What is expected?
vertical  effective

### What is actually happening?
vertical invalid

**Comment by artOfWarBut** [comment]
Carousel 在 react native 不能垂直滚动 ，哪位用过的，指点一下，多谢

**Comment by warmhug** [comment]
Close for https://github.com/ant-design/ant-design-mobile/blob/f3b2687b63dc228ec4d1b9d7cff9ed52ea4766af/components/carousel/index.native.tsx#L94
ref https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452
