### ISSUE TITLE
ReferenceError: List is not defined

### ISSUE THREAD

**Issue by littletry** [ant-design/ant-design-mobile#2383]
请问一下  为什么会报这种错误  是List的引用有问题吗？  我并没有去改动过任何代码  就只是重新执行了一下 npm install 然后 就不能运行了。运行时就会报这个错，而且我确认List是引用了的。
这样引用不对了吗？
import { List } from 'antd-mobile';
如果把List相关代码删除了，又会报别的组件未定义
报错内容：
ReferenceError: List is not defined

**Comment by paranoidjk** [comment]
确认下 antd-mobile 版本，给出可复现例子。

按文档使用 https://mobile.ant.design/docs/react/introduce-cn

**Comment by littletry** [comment]
antd-mobile版本是2.1.3  在我本机的正常项目中可以运行  我把里面的代码复制到另外的项目里面 执行npm install 然后就不能运行了 就报这个错

**Comment by littletry** [comment]
项目是用dva创建的，原先一直用着都好好的，前几天发现这个问题的，项目重新拉的分支，在新的文件夹里面，执行npm install  然后发现就不能运行了

**Comment by littletry** [comment]
请问一下会不会是package.json里面的版本控制问题呢？我执行npm install的时候使用的版本和工程里面的不符合？
贴上 package.json代码
{
  "private": true,
  "scripts": {
    "start": "set port=8008 && roadhog server",
    "build": "roadhog build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "babel-plugin-import": "1.6.3",
    "dva": "2.1.0",
    "antd-mobile": "2.1.3",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "rc-form": "2.1.7",
    "moment": "2.20.1"
  },
  "devDependencies": {
    "mock": "^0.1.1",
    "moment": "^2.20.1",
    "rc-form": "latest",
    "roadhog-api-doc": "^1.0.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-compat": "^2.1.0",
    "antd-mobile": "^2.1.3",
    "babel-eslint": "^8.2.1",
    "babel-plugin-dva-hmr": "^0.3.2",
    "eslint": "^4.14.0",
    "eslint-config-umi": "^0.1.1",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "husky": "^0.12.0",
    "redbox-react": "^1.4.3",
    "roadhog": "^2.0.0"
  }
}

**Comment by littletry** [comment]
我非常确认代码是没有问题的，因为原始的项目是可以运行的，我现在都不敢删除原先项目的node_modules文件夹了，如果删除了重新npm install估计也还是会出现这个问题

**Comment by yesmeck** [comment]
`babel-plugin-import` 升级到最新。

**Comment by littletry** [comment]
谢谢啦 果然 升级了`babel-plugin-import`就可以了  非常感谢
