### ISSUE TITLE
How to use 'itemStyle' to make Picker's two column have different widths? 

### ISSUE THREAD

**Issue by littletry** [ant-design/ant-design-mobile#2385]
How to use 'itemStyle' to make Picker's two column have different widths? How to modify the value of  'flex'?
请问一下，picker里面包含两列，一列的每一行字数过多，一列的字数少，这两列所占的比列该怎么设置呢？因为字数多的那一列显示不完整！求救

**Comment by littletry** [comment]
请问一下picker的itemStyle可以对每一列的flex进行修改吗？具体该怎么写才能修改成功呢？

**Comment by littletry** [comment]
How to use 'itemStyle' to make Picker's two column have different widths?

**Comment by littletry** [comment]
picker里面的flex值可以修改吗？怎样才能修改正确？

**Comment by paranoidjk** [comment]
用 `itemStyle ` 自定义样式。

flex 使用请自行搜索。

**Comment by littletry** [comment]
您好，我试过itemStyle，它不能把两列的内容区分成不同的宽度。itemStyle不能更改am-picker-col的宽度，am-picker-col的宽度是固定的，不能改变。通过审查元素把am-picker-col的style改成style="flex: 2 1 0%;"这样才能改到每一列的宽度。这里不能发截图，很恼火，邮箱发您。

**Comment by littletry** [comment]
默认am-picker-col的style为如下
![image](https://user-images.githubusercontent.com/24276890/37411231-4d2f3352-27dd-11e8-976d-729385a3b223.png)
![image](https://user-images.githubusercontent.com/24276890/37411351-942de244-27dd-11e8-8a08-0435bbaba9a6.png)

**Comment by littletry** [comment]
itemStyle好像只能修改文字所在的那个am-picker-col-item 的宽度，改不了am-picker-col的宽度，所以没有效果
