### ISSUE TITLE
官网挂了，没人管吗。。。。。

### ISSUE THREAD

**Issue by SnowZhangXl** [ant-design/ant-design-mobile#2386]
官网挂了，没人管吗。。。。。

**Comment by zcfreestyle** [comment]
官网挂了真的是没人管，antd都有国内镜像网址，antd-mobile没有

**Comment by afc163** [comment]
没挂，两会期间被墙了，请翻墙。

**Comment by paranoidjk** [comment]
官网地址: http://mobile.ant.design
国内镜像: http://antd-mobile.gitee.io


http://www.anijue.com/p/q/antd-mobile/index.html
