### ISSUE TITLE
‘itemStyle’ can't modify the width of ‘div’ class ‘am-picker-col’

### ISSUE THREAD

**Issue by littletry** [ant-design/ant-design-mobile#2389]
您好，我试过itemStyle，它不能把两列的内容区分成不同的宽度。itemStyle不能更改am-picker-col的宽度，am-picker-col的宽度是固定的，不能改变。通过审查元素把am-picker-col的style改成style="flex: 2 1 0%;"这样才能改到每一列的宽度。
默认am-picker-col的style为如下，这个是没有审查元素修改的

![image](https://user-images.githubusercontent.com/24276890/37411231-4d2f3352-27dd-11e8-976d-729385a3b223.png)
![image](https://user-images.githubusercontent.com/24276890/37411351-942de244-27dd-11e8-8a08-0435bbaba9a6.png)

审查元素修改后

您好，我试过itemStyle，它不能把两列的内容区分成不同的宽度。itemStyle不能更改am-picker-col的宽度，am-picker-col的宽度是固定的，不能改变。通过审查元素把am-picker-col的style改成style="flex: 2 1 0%;"这样才能改到每一列的宽度。
![image](https://user-images.githubusercontent.com/24276890/37411092-f2d36900-27dc-11e8-89fd-b6df4e9b4e28.png)
![image](https://user-images.githubusercontent.com/24276890/37411438-c390a774-27dd-11e8-9bca-9b3d75c1f44f.png)

**Comment by paranoidjk** [comment]
仔细看了一下，暂时 API 做不到这个需求，你先用 css 覆盖样式吧。

除非未来某个版本改变 API，比如增加 `data.style`

```ts
export interface PickerData {
  value: string | number;
  label: string;
  children?: PickerData[];
  data: object;
}
```

或者采用组件嵌套来表达数据结构的 API 形式 https://github.com/react-component/m-picker#usage

**Comment by littletry** [comment]
多谢多谢，修改成功了
body :global(.am-picker-col:nth-child(2)) {
  flex: 2 !important;
}
