### ISSUE TITLE
组件间共享样式

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#239]
date-picker picker 完全是重复，以后注意. 

像机器人一样复制黏贴习惯了就真变成 android 了. 即使要妥协也要用 mixin

@warmhug @ant-design/ant-design-team 

 https://github.com/ant-design/ant-design-mobile/commit/b3bd19466acfc7985e9548097e3f4dd08bec3a48

**Comment by warmhug** [comment]
再仔细看下，不完全一样的
