### ISSUE TITLE
https://mobile.ant.design/ 打不开了，开发文档去哪里能下载保存？

### ISSUE THREAD

**Issue by sxbupt** [ant-design/ant-design-mobile#2391]
### Version
2.1.6

### Environment
react wap

### Reproduction link
[https://mobile.ant.design/](https://mobile.ant.design/)

### Steps to reproduce
https://mobile.ant.design/ 打不开了，开发文档去哪里能下载保存？

### What is expected?
https://mobile.ant.design/ 打不开了，开发文档去哪里能下载保存？

### What is actually happening?
https://mobile.ant.design/ 打不开了，无任何地址可查看

**Comment by cncolder** [comment]
https://antd-mobile.gitee.io

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/issues/2386
