### ISSUE TITLE
Not possible to override error text color in InputItem

### ISSUE THREAD

**Issue by mbrochh** [ant-design/ant-design-mobile#2394]
### What problem does this feature solve?
At the moment, it is impossible to override the error color of InputItem, due to this line:

https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.native.tsx#L193

### What does the proposed API look like?
I propose to add a new prop `errorColor` and change the offending line to:

`style={[styles.input, error ? { color: this.props.errorColor } : null]}`

Would this be a viable enhancement? Should I submit a pull request?

**Comment by paranoidjk** [comment]
You can change `styles.input` Follow https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui

**Comment by paranoidjk** [comment]
You are right, i suggest we add a API like `errorStyle?: object`, would you like PR?
