### ISSUE TITLE
关于switch组件的value值绑定

### ISSUE THREAD

**Issue by zongyuan-vale** [ant-design/ant-design-mobile#2396]
### What problem does this feature solve?
我在官方文档中看到的switch组件只能通过“rc-form”，去控制switch的状态，无法通过通常的 value<==>onChange() 进行数据绑定。我的业务场景是切换状态时会有一个弹窗提示再进行切换，以官网的例子似乎无法做到这一点。非常感谢您的解答

### What does the proposed API look like?
期望的switch组件使用方式：
```javascript
<Switch
	value={checked}
	onChange={checked => {
		this.setState({checked})
	}}
 />
```

**Comment by paranoidjk** [comment]
https://mobile.ant.design/components/switch-cn/#API
