### ISSUE TITLE
Make english obligatory

### ISSUE THREAD

**Issue by hendrul** [ant-design/ant-design-mobile#2397]
You are not alone in the world, here in occident we also need this library !

**Comment by paranoidjk** [comment]
We already had English version of doc, and welcome to help us complete it.
  
https://mobile.ant.design


https://github.com/ant-design/ant-design-mobile/issues/329

**Comment by hendrul** [comment]
I mean, Issues in english

**Comment by paranoidjk** [comment]
Yep, we do recommend discuss in English, we even have a robot who will auto remind the users open issue with English. But we have no way to force all the users, sorry.
