### ISSUE TITLE
The new typescript definition problems with Card.Footer extra in 2.17

### ISSUE THREAD

**Issue by stonecold123** [ant-design/ant-design-mobile#2398]
### Version
2.1.7

### Environment
React Native

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo](https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo)

### Steps to reproduce
1. Update antd mobile to 2.17

This code used to be type-error free:
````
<Card>
    <Card.Body>
           <Text>content</Text>
    </Card.Body>
    <Card.Footer content={<Text>Some text</Text>}/>
</Card>
````

### What is expected?
It should not have any type error like 2.16

### What is actually happening?
Now I'm getting a lot of these errors in `Card.Footer` extra or content on Webstorm:
````
Error:(160, 25) TS2322: Type '{ content: Element; extra: Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<CardFooter> & Readonly<{ children?: ReactNode; }> ...'.
  Type '{ content: Element; extra: Element; }' is not assignable to type 'Readonly<CardFooterProps>'.
    Types of property 'content' are incompatible.
      Type 'Element' is not assignable to type 'string | StatelessComponent<any> | ComponentClass<any>'.
        Type 'Element' is not assignable to type 'ComponentClass<any>'.
````
I just couldn't pass an entire React Element to these props like I used to be in 2.16.

What change should I make in order to remove these type errors in `Card.Footer extra`  `Card.Footer content` or `List renderHeader`?

**Comment by stonecold123** [comment]
@paranoidjk  @bang88  
There are still some issues with the new definitions. 
The title property in Modal, Card.Header etc should support string in react native

The `renderHeader` in `List` should not produce this error in this block

````
<List renderHeader={<Text>something</Text> }/>
````

I think List renderHeader should also work like this:
````
export interface ListPropsType {
    renderHeader?:  React.ReactType | JSX.Element;
    renderFooter?:  React.ReactType | JSX.Element;
    children?: false | JSX.Element | JSX.Element[];
}
```

**Comment by bang88** [comment]
> The title property in Modal, Card.Header etc should support string in react native

The React's type definition really sucks.

```ts
//
    // React Elements
    // ----------------------------------------------------------------------

    type ReactType<P = any> = string | ComponentType<P>;
    type ComponentType<P = {}> = ComponentClass<P> | StatelessComponent<P>;


 	namespace JSX {
    // tslint:disable-next-line:no-empty-interface
    interface Element extends React.ReactElement<any> { }
...
```
will update it ASAP.


> The renderHeader in List should not produce this error in this block.
> ```tsx<List renderHeader={<Text>something</Text> }/>```
> I do not get any error with this modified definition
>
> 
```ts
export interface ListPropsType {
    renderHeader?:  ReactNode| JSX.Element[] | JSX.Element;
    renderFooter?:  ReactNode | JSX.Element[] | JSX.Element;
    children?: false | JSX.Element | JSX.Element[];
}
```

This is not so true because both `renderHeader` and `renderFooter` are accept a function or `string`. can not use `React.ReactNode` here

**Comment by stonecold123** [comment]
@bang88 
`renderHeader` does work with putting an entire `React.ReactNode`

I've made a List wrapper just like this and the header text still appears
````
interface Props extends ListProps{
    headerText?:string
}

export const CustomList = ((props:Props)=>{
    return <List renderHeader={
        props.headerText?
            <Text>Header</Text>:null
    } {...props}/>
});
````

**Comment by bang88** [comment]
@stonecold123 Can you checkout the new definitions out here https://github.com/bang88/ant-design-mobile/commit/95941863ea1c97add00dc58475165d7ca47d96f1
