### ISSUE TITLE
make the space proportion of the content and extra content in List component configurable

### ISSUE THREAD

**Issue by vaggrant** [ant-design/ant-design-mobile#2402]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when I use List component,the extra content is simplely a button that 50px is enough,but the content on the left side need more space where i don't want wrap it consider from the UI,but now the space is fixed.

### What does the proposed API look like?
contentWidth={200} or contentWidth="80%"

**Comment by bang88** [comment]
Please provide some code snippets help us understand whats your problem.

**Comment by vaggrant** [comment]
the phone number may not be shown in a row.

 <List renderHeader={() => (
          <div style={{ display: 'flex', fontSize: 24, alignItems: 'center', justifyContent: 'space-between' }} >
            <div style={{ borderBottom: '2px solid #33a3f4' }} >
              <Icon type="user" />
              <span style={{ fontSize: 12 }} > 我的账户</span>
            </div>
            <Icon type="close" style={{ fontSize: 24 }} onClick={this.props.onClose} />
          </div>
        )} >
          <Item extra={<div style={{ width: 60, background: 'red' }} ></div>} >
            <Flex >
              <Flex.Item> <div >账号：</div></Flex.Item>
              <Flex.Item style={{ fontSize: 16, color: '#888' }} >{this.props.username ? `微信用户${this.props.username}` : '匿名'}</Flex.Item>
            </Flex>
          </Item>
          <Item extra={<Button style={{ width: 60 }} size="small" type="primary" >{this.props.mobilePhoneVerified ? '变更' : '绑定'}</Button>} >
            <Flex >
              <Flex.Item> <div >手机号：</div></Flex.Item>
              <Flex.Item style={{ fontSize: 16, color: '#888' }} >{this.props.mobilePhoneVerified ? this.props.mobilePhoneNumber : '未绑定'}</Flex.Item>
            </Flex>
          </Item>
          <Item extra={<div style={{ width: 60 }} ></div>} >
            <Flex >
              <Flex.Item> <div >余额</div></Flex.Item>
              <Flex.Item style={{ fontSize: 16, color: '#888' }} >0</Flex.Item>
            </Flex>
          </Item>
          <Picker
            title="支付方式"
            cols={1}
            extra="请选择"
            data={payData}
            onOk={(v) => { this.setState({ pay: v }) }}
            value={this.state.pay}
          >
            <List.Item arrow="horizontal">默认支付方式</List.Item>
          </Picker>
          <Picker
            title="地址"
            cols={1}
            extra="请选择"
            data={addressData}
            onOk={(v) => { this.setState({ address: v }) }}
            value={this.state.address}
          >
            <List.Item arrow="horizontal">默认地址</List.Item>
          </Picker>
        </List>

**Comment by vaggrant** [comment]
![tim 20180326094343](https://user-images.githubusercontent.com/11265594/37883023-99eacbd8-30da-11e8-86ad-810f4a70c13e.png)

**Comment by vaggrant** [comment]
@bang88

**Comment by warmhug** [comment]
自己设置样式覆盖吧
