### ISSUE TITLE
如何使用iframe在PC端模拟出手机环境

### ISSUE THREAD

**Issue by func-star** [ant-design/ant-design-mobile#2405]
如何使用iframe在PC端模拟出手机环境,且能支持touch事件，就像蚂蚁金服移动端组件库的demo展示那样的实现。

**Comment by zjxpcyc** [comment]
组件库里的 demo 也是不支持 touch 的吧？  

我这边就是直接 设置 iframe 的为 iphon6 的宽高就可以了，难道还有什么特殊的操作 ？

**Comment by warmhug** [comment]
There is no way.

**Comment by Hyattria** [comment]
https://github.com/hammerjs/touchemulator/blob/master/touch-emulator.js

**Comment by Hyattria** [comment]
```js
import TouchEmulator from 'hammer-touchemulator';
new TouchEmulator();
```
https://github.com/hammerjs/touchemulator/blob/master/touch-emulator.js
