### ISSUE TITLE
Antd -mobile Popover, and clicking on the mask layer on ios does not trigger onVisibleChange.

### ISSUE THREAD

**Issue by zmdmumu** [ant-design/ant-design-mobile#2406]
My code is tested on Windows and Android, and clicking on the mask closes the Popover, but it doesn't trigger the click event on ios.Why is that?The version I use is:
```
package.json:

 "dependencies": {
    "antd": "^2.7.4",
    "antd-mobile": "^1.4.0",
```
Version2.1.8Environment
Use an ios phone.Reproduction link
https://codepen.io/zmdmumu/pen/dmNejY?&editors=0010Steps to reproduce
Using an ios phone, click the option in the upper-right corner to display Popover, and then click on its mask to close the Popover.What is expected?
My code is tested on Windows and Android, and clicking on the mask closes the Popover, but it doesn't trigger the click event on ios.What is actually happening?
You can't close the Popover by clicking on the mask on ios.
@ant-design-bot Demo address： https://codepen.io/zmdmumu/pen/dmNejY?&editors=0010

**Comment by zmdmumu** [comment]
Ok, please click here: https://codepen.io/zmdmumu/pen/dmNejY?&editors=0010 , thank you.
I use the iPhone6s plus and the iPhone8's browser, or the WeChat QQ chat software test, all of which will have problems.

**Comment by Weipengzhou** [comment]
me to。。。。

**Comment by zmdmumu** [comment]
@Weipengzhou  Finally, I didn't use antd, and I wrote this component.

**Comment by zmdmumu** [comment]
@Weipengzhou 感觉强行翻译成英文好别扭，你也发现这个bug了吗

**Comment by warmhug** [comment]
Use `fastclick`

**Comment by zmdmumu** [comment]
why, it is not a matter of clicking the delay.
