### ISSUE TITLE
（已经解决）Picker和DatePicker右侧extra不生效 官网上的组件Demo也是

### ISSUE THREAD

**Issue by miss61008596** [ant-design/ant-design-mobile#241]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：OSX
- 浏览器及其版本：Google Chrome 51.0.2704.63 (64-bit)

#### 你做了什么？

Picker和DatePicker
#### 可重现的在线演示

![image](https://cloud.githubusercontent.com/assets/6361237/18424248/ad636f40-78e8-11e6-9b53-5b8ffd51eda4.png)
![image](https://cloud.githubusercontent.com/assets/6361237/18424259/ca47b152-78e8-11e6-9900-52890cf12bcd.png)
不明白官网上Demo为什么不正常，
在
https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo
也就是说使用dora 启动
"start": "dora --plugins \"proxy,webpack,livereload?enableJs=false&injectHost=127.0.0.1\""
中是正常的，不明白原因
![image](https://cloud.githubusercontent.com/assets/6361237/18424306/213b86f0-78e9-11e6-99ca-4da89e1b09f4.png)
![image](https://cloud.githubusercontent.com/assets/6361237/18424314/2d0d841a-78e9-11e6-84fd-049a31acaaee.png)
求解，

**Comment by OUZICHENG** [comment]
我是来一起吐槽的，没有试用过，不过装了官方DEMO，感觉这两个组合的RN版化验上没有WEB版的好，主要感觉是在选择时滑动的流畅程度上，不知道其他人有没有同感。

**Comment by miss61008596** [comment]
问题找到原因了
Picker组件 index.web.js    line:100
var childEl = React.cloneElement(children, children.type && children.type.name === 'ListItem' ? extraProps : {});
用atool-build构建后
![image](https://cloud.githubusercontent.com/assets/6361237/18433804/8844b372-7924-11e6-9818-3bbf16579977.png)
从ListItem变为t
![image](https://cloud.githubusercontent.com/assets/6361237/18433817/9b1f98f4-7924-11e6-8010-421e1787404d.png)
这一句判断在开发模式下有作用，在生产模式后就永远检查不到ListItem了，
去掉 && children.type.name 
改为
var childEl = React.cloneElement(children, children.type === 'ListItem' ? extraProps : {});
![image](https://cloud.githubusercontent.com/assets/6361237/18433865/d2a05aac-7924-11e6-9209-2dd56c36619a.png)
生效，
建议改为其他方式检查是否为ListItem子组件，多谢，

**Comment by warmhug** [comment]
谢谢帮忙排查问题

**Comment by OUZICHENG** [comment]
@miss61008596 well done
