### ISSUE TITLE
Carousel after adding infinite  The picture will be missing but can be a normal carousel

### ISSUE THREAD

**Issue by wanghqwe** [ant-design/ant-design-mobile#2410]
my code
                   <Carousel className="space-carousel"
                              frameOverflow="visible"
                              cellSpacing={11}
                              slideWidth={0.3}
                              dots={false}
                              infinite={true}
                             selectedIndex={this.state.slideIndex}
                              beforeChange={(from, to) => {
                                  console.log(`slide from ${from} to ${to}`)
                              }}
                              afterChange={index => this.setState({slideIndex: index})}
                    >
                        {this.state.data.map((val, index) => (
                            <div
                                key={val}
                                style={{
                                    display: 'inline-block',
                                    height: 176,
                                    transform: this.state.slideIndex === index ? 'scale(1.1)' : 'none',
                                    transiton: 'all 1s',
                                    boxShadow: '2px 1px 1px rgba(0, 0, 0, 0.2)',
                                    width: '100%'
                                }}
                            >
                                <img
                                    src={'http://img.taopic.com/uploads/allimg/120727/201995-120HG1030762.jpg'}
                                    alt=""
                                    style={{width: '100%', verticalAlign: 'top', height: '100%'}}
                                    onLoad={() => {
                                        // fire window resize event to change height
                                        window.dispatchEvent(new Event('resize'));
                                        this.setState({ imgHeight:176 });
                                    }}
                                />
                            </div>
                        ))}
                    </Carousel>
Carousel after adding infinite The picture will be missing but can be a normal carousel 
As shown in the picture
<img width="285" alt="qq20180320-164248 2x" src="https://user-images.githubusercontent.com/23471501/37644190-f3f3f64e-2c5d-11e8-98be-f9222787ea09.png">
<img width="313" alt="qq20180320-165030 2x" src="https://user-images.githubusercontent.com/23471501/37644462-dea6a79a-2c5e-11e8-98cb-1974116d7e36.png">

**Comment by wenJonSnow** [comment]
同样遇到

**Comment by rojer95** [comment]
同样遇到 
设置了cellSpacing后 当轮播的数量大于3个的时候回出现

这里我是5个轮播图片

![image](https://user-images.githubusercontent.com/20662049/50545983-ffd12f80-0c5a-11e9-91e0-a442ff42369f.png)
 
前2个正常 第三个开始左侧不显示

![image](https://user-images.githubusercontent.com/20662049/50545986-124b6900-0c5b-11e9-87e1-c8db2f20c543.png)

**Comment by rojer95** [comment]
复现 https://codepen.io/rojer95/pen/OrOPbb?&editors=0010
