### ISSUE TITLE
modal can not mask the StatusBar in android platform

### ISSUE THREAD

**Issue by h124551753** [ant-design/ant-design-mobile#2411]
![screenshot_1521536575](https://user-images.githubusercontent.com/12689580/37645103-d309a73c-2c60-11e8-8b3e-4896a6fba493.png)

As picture shown, when i use modal.alert and modal.prompt to show a dialog, the StatusBar has not been masked. i want to modal masked the StatusBar. while this problem not appear to iOS platform.

run environment：

platform： android 5.1.1
react-native： 0.51.0
antd-mobile: 2.1.1

**Comment by bang88** [comment]
Please check this https://github.com/facebook/react-native/issues/7474#issuecomment-288814366 should fix your problem.
