### ISSUE TITLE
Picker "Attempted to assign to readonly property"

### ISSUE THREAD

**Issue by lggege** [ant-design/ant-design-mobile#2412]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
Windows10、Android 8.1、react-native 0.54.2、ant-mobile 2.1.8

### Reproduction link
[https://github.com/lggege/issue-antd-mobile-picker](https://github.com/lggege/issue-antd-mobile-picker)

### Steps to reproduce
``` shell
git clone https://github.com/lggege/issue-antd-mobile-picker
cd issue-antd-mobile-picker
react-native run-android
```

页面上就一个`性别`下拉框，选择仅有`男`、`女`。切换选项则异常。

### What is expected?
能正常选择

### What is actually happening?
Attempted to assign to readonly property.
onChange
    C:\Users\colin\workspace\rn\myapptwo\node_modules\antd-mobile\lib\list\style\index.native.js:36:8
onValueChange
    C:\Users\colin\workspace\rn\myapptwo\node_modules\antd-mobile\lib\list\style\index.native.js:39:20
onValueChange
    
fireValueChange
    
doScrollingComplete
    C:\Users\colin\workspace\rn\myapptwo\node_modules\rmc-picker\lib\NativePicker.android.js:46:16
<unknown>
    C:\Users\colin\workspace\rn\myapptwo\node_modules\rmc-picker\lib\MultiPickerMixin.js:90
<unknown>
    C:\Users\colin\workspace\rn\myapptwo\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:258:23
_callTimer
    C:\Users\colin\workspace\rn\myapptwo\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:154:6
callTimers
    C:\Users\colin\workspace\rn\myapptwo\node_modules\react-native\Libraries\Core\Timers\JSTimers.js:407:17
__callFunction
    C:\Users\colin\workspace\rn\myapptwo\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:353:47
<unknown>
    C:\Users\colin\workspace\rn\myapptwo\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:118:26
__guardSafe
    C:\Users\colin\workspace\rn\myapptwo\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:316:6
callFunctionReturnFlushedQueue
    C:\Users\colin\workspace\rn\myapptwo\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:117:17

**Comment by qwlong** [comment]
OK, May be you just use const to assign value, just change it to this.state.xxx to solve it.

**Comment by warmhug** [comment]
![image](https://user-images.githubusercontent.com/2011119/40419133-f149ee22-5eb6-11e8-848f-0061dee64554.png)
Please read the document carefully!
