### ISSUE TITLE
一个页面内有2个使用Body容器的ListView，当下拉刷新其中某一个时，页面内所有的ListView都会刷新

### ISSUE THREAD

**Issue by xuexiaoao** [ant-design/ant-design-mobile#2415]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
IOS

### Reproduction link
[https://mobile.ant.design/components/list-view-cn/](https://mobile.ant.design/components/list-view-cn/)

### Steps to reproduce
下拉刷新某个ListView即可

### What is expected?
刷新某个ListView组件，不会影响其他ListView组件

### What is actually happening?
实际结果是牵一发而动全身

---
不仅仅下拉刷新有问题，onEndReached方法也会重复执行，在使用自定义容器后没有这些问题

**Comment by KgTong** [comment]
这种场景建议使用自定义容器

**Comment by nishuer** [comment]
当然会一起刷新，如果用body容器listview监听的就是body的滚动事件，body只有一个。建议用自定义高度。
