### ISSUE TITLE
RefreshControl/ListView web api 调整

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#242]
同

http://facebook.github.io/react-native/docs/refreshcontrol.html

http://facebook.github.io/react-native/docs/listview.html

一致。

例外 RefreshControl web 版本不需要 ScrollView 直接放到 children

**Comment by wv1124** [comment]
是不是不能
< RefreshControl>
   <ListView>
   </ListView>
</RefreshControl>
这样子,滚不动

**Comment by warmhug** [comment]
1.0-beta 中支持，预计明后天发下

**Comment by yiminghe** [comment]
约定 0.9.x

**Comment by warmhug** [comment]
0.9.0-beta.0  已支持
