### ISSUE TITLE
Using inputItem always show apple keyboard

### ISSUE THREAD

**Issue by witalobenicio** [ant-design/ant-design-mobile#2420]
I use GBoard keyboard in my iPhone, but when I use the <InputItem> component, it always shows the default keyboard instead of GBoard. There is a way to change this behavior?

**Comment by bang88** [comment]
@witalobenicio Can not reproduce it using Safari. are you using `React Native` version ?

**Comment by witalobenicio** [comment]
@bang88 yes, I'm using react native version. Sorry for not mentioning

**Comment by bang88** [comment]
Can you provide some code snippets I can test on my side.

**Comment by witalobenicio** [comment]
@bang88 sorry again, It's only when we set as password. I think that this behavior is expected.

**Comment by bang88** [comment]
@witalobenicio  As I know you can't use `secureTextEntry` alias `password` type here. because IOS do not allow a third-party Keyboard access sensitive informations. I guess so.

**Comment by witalobenicio** [comment]
Yep. That's correct. Closing this issue Thanks

**Comment by bang88** [comment]
😄
