### ISSUE TITLE
IOS Native Modal.prompt 有键盘遮挡问题

### ISSUE THREAD

**Issue by zhang-ning** [ant-design/ant-design-mobile#2421]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
IOS Native Modal.prompt 有键盘遮挡问题

### What does the proposed API look like?
IOS Native Modal.prompt 有键盘遮挡问题，通过键盘高度 规避遮挡问题

**Comment by Ben56** [comment]
确实有这个问题，希望能修复一下

**Comment by Ben56** [comment]
I encountered the same problem

**Comment by Geek-ch** [comment]
IOS Native Modal.prompt has keyboard occlusion issues +1 ,  (test on iPhone6s)

**Comment by warmhug** [comment]
cc @paranoidjk

**Comment by warmhug** [comment]
There is no solution yet.
Close for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452

**Comment by sej1228** [comment]
> 不能输入中文单词
> 不能输入中文，输入法也切换到中文了

请问你是怎么解决这个问题的？

**Comment by beysong** [comment]
> > 不能输入中文单词
> > 不能输入中文，输入法也切换到中文了
> 
> 请问你是怎么解决这个问题的？

好像模拟器上有问题，在手机上就好了，打个包到手机上试试

**Comment by sej1228** [comment]
> > > 不能输入中文单词
> > > 不能输入中文，输入法也切换到中文了
> > 
> > 
> > 请问你是怎么解决这个问题的？
> 
> 好像模拟器上有问题，在手机上就好了，打个包到手机上试试

好的，谢谢。 不过我自己写了个，不用antd的了
