### ISSUE TITLE
是否可以把数字键盘的组件提供出来。

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design-mobile#2422]

**Comment by ksh033** [comment]
不是，支付密码不是经常使用数字键盘。我现在只能把你们的源码通过input+customkeyboard拿来自己封装。我怕后面你们改了兼容。包括密码类输入框是否可以考虑单独再封装一个组件。经用的，例如支付密码，输入密码可以看密码原值的。

**Comment by ksh033** [comment]
@ant-design-bot 不是，支付密码不是经常使用数字键盘。我现在只能把你们的源码通过input+customkeyboard拿来自己封装。我怕后面你们改了兼容。包括密码类输入框是否可以考虑单独再封装一个组件。经用的，例如支付密码，输入密码可以看密码原值的。

**Comment by warmhug** [comment]
你这个情况 使用 Modal 可以吧？

**Comment by ksh033** [comment]
@warmhug 可以.我就是用了Modal组件+键盘组件封装了一个PassWordModel.只不过现在的键盘组件我是直接把你们的代码拷出来用的。所以才问一下数字键盘组件有不能开放出来。别外Modal还加了从左移入和从右移入动画.看看后面的版本能不能这两个动画也默认。

**Comment by zjxpcyc** [comment]
@warmhug   我觉得可以借鉴 有赞 的  https://www.youzanyun.com/zanui/vant#/zh-CN/number-keyboard
它们提供了很多组件，我们可以把比如数字键盘的这种，放到 业务组件里面，比如  antd-design-pro 公开的部分也可以拿过来

**Comment by doxiaodong** [comment]
InputNumber
