### ISSUE TITLE
ant-design-mobile   use  modal.alert，but   onpress  not work

### ISSUE THREAD

**Issue by RowgerGo** [ant-design/ant-design-mobile#2428]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
web  safari and wechat

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/issues/2416](https://github.com/ant-design/ant-design-mobile/issues/2416)

### Steps to reproduce
```
const aler = Modal.alert;
aler('please set you pwd', '', [
     { text: '确认', onPress: () =>  window.location.href = "#", style: { fontWeight: 'bold' } },
  ])
```

### What is expected?
onPress can work

### What is actually happening?
onPress can'n  work

**Comment by warmhug** [comment]
Use `fastclick`

**Comment by vince-fly** [comment]
`yarn add fastclick`
`let fastclick =require('fastclick'); fastclick.attach(document.body, {});`

**Comment by likezero** [comment]
@RowgerGo  please try `fastclick`

**Comment by warmhug** [comment]
Close for #2486
