### ISSUE TITLE
DatePicker:Hope, the choice of time accurate to the minute and seconds

### ISSUE THREAD

**Issue by HAPENLY** [ant-design/ant-design-mobile#2429]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
DatePicker:Hope, the choice of time accurate to the minute and seconds

### What does the proposed API look like?
```
 <DatePicker
            mode="time"
            format="mm:ss"
            title="minutes seconds"
            value={this.state.customChildValue}
            onChange={v => this.setState({ customChildValue: v })}
>
 </DatePicker>
```
>  **The value returned here should be minutes and seconds.**
`onChange={v => this.setState({ customChildValue: v })}`

**Comment by awmleer** [comment]
It has already been supported in v5:
https://next.mobile.ant.design/components/date-picker

(English version doc is coming soon.)
