### ISSUE TITLE
dependencies react-dom disabled the toggle inspector

### ISSUE THREAD

**Issue by tears743** [ant-design/ant-design-mobile#2433]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.6

### Environment
rn 0.48

### Reproduction link
[http://everywhere](http://everywhere)

### Steps to reproduce
when you debug and need toggle inspector

### What is expected?
nomarl

### What is actually happening?
crash

**Comment by warmhug** [comment]
It should be your project config problem.
