### ISSUE TITLE
alert message is not centered  in react native ios screen

### ISSUE THREAD

**Issue by flyinghawker** [ant-design/ant-design-mobile#2438]

**Comment by flyinghawker** [comment]
react native has alert component which has issue : ''unrecognized selector sent to instance...", so I take ant design alert but I have no way to style the message event put react component into it, very annoying: both rn and ant alert are bad to use

**Comment by warmhug** [comment]
Recommended RN Official Alert. 
Seems our `Modal.alert` also have not such a problem.
