### ISSUE TITLE
Model.Alert  close was not work

### ISSUE THREAD

**Issue by John-Base** [ant-design/ant-design-mobile#2442]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
ios 9.3.5,safari

### Reproduction link
[https://codepen.io/anon/pen/YavbRN](https://codepen.io/anon/pen/YavbRN)

### Steps to reproduce
use ios 9.3.5,safari ,antd-mobile use 2.1.8 .Modal.alert  is not work, didn't closed

### What is expected?
Modal.alert  cancel button onpress can close

### What is actually happening?
Modal.alert  cancel button onpress can't  close

**Comment by iamsjh** [comment]
same too，help!!!!!!!!

**Comment by zhaozilong123** [comment]
I have the same problem! antd-mobile 2.1.8version.please fix bug quikly,thank you!

**Comment by warmhug** [comment]
ref https://github.com/ant-design/ant-design-mobile/issues/2428#issuecomment-377132837

**Comment by feixinghong** [comment]
解决了iphone7微信里面alert的问题啦   通过添加fastclick  谢谢

**Comment by KurobaZhang** [comment]
same

**Comment by Derek-Hu** [comment]
same +1

**Comment by likezero** [comment]
@John-Base @madaono @KurobaZhang @Derek-Hu 
引入fastclick看看

**Comment by warmhug** [comment]
Close for #2486
