### ISSUE TITLE
It will not run to onRefresh when the first time I touch move up the list

### ISSUE THREAD

**Issue by tangshuang** [ant-design/ant-design-mobile#2443]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.2

### Environment
mac chrome65.0.3325.162

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/pull-to-refresh?lang=zh-CN#pull-to-refresh-demo-0](https://mobile.ant.design/kitchen-sink/components/pull-to-refresh?lang=zh-CN#pull-to-refresh-demo-0)

### Steps to reproduce
1. open the demo link which is given
2. change to use direction:up
3. touch scroll to up, scroll and scroll
4. notice the first time when to the end, it will show refresh finished, and onRefresh not invoked

### What is expected?
refresh invoked when the first time

### What is actually happening?
not invoked

**Comment by micooz** [comment]
该问题已有PR，请 @warmhug 及时 Review：

https://github.com/react-component/m-pull-to-refresh/pull/16
