### ISSUE TITLE
TabBar  TabBar.Item icon can not using 'uri'

### ISSUE THREAD

**Issue by Here21** [ant-design/ant-design-mobile#2444]
<img width="1673" alt="wx20180404-171234 2x" src="https://user-images.githubusercontent.com/12051024/38298981-789d0e70-382b-11e8-8b4a-c45ab659d779.png">

```js
"antd-mobile": "^2.1.8"
"react": "16.2.0",
"react-native": "0.52.0",
```

**Comment by warmhug** [comment]
Follow here https://facebook.github.io/react-native/docs/tabbarios-item.html#icon
We did not modify RN TabBarIOS.
