### ISSUE TITLE
Hope SegmentedControl could open more api for style

### ISSUE THREAD

**Issue by destinyd** [ant-design/ant-design-mobile#2446]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
SegmentedControl tintColor work not well for light color

sample:
```
<SegmentedControl
            values={['段落1', '段落', '段落']}
           tintColor="#FEFEA4"
          />
```

### What does the proposed API look like?
Hope add color（text color），backgroundColor，borderColor  for select/unselect API
```
<SegmentedControl
           values={['段落1', '段落1', '段落1']}
           backgroundColor="#FEFEA4"
           color="black"
           borderColor="black"
          />
```

**Comment by destinyd** [comment]
@warmhug Need in web too

**Comment by warmhug** [comment]
Close for https://github.com/ant-design/ant-design-mobile/commit/6ab912f9e1978ea6b7ea675f03970d1c66df897f
