### ISSUE TITLE
TabBar嵌套SearchBar样式异常

### ISSUE THREAD

**Issue by maxid** [ant-design/ant-design-mobile#2447]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
osx 10.13, node v6.10.2

### Reproduction link
[https://codepen.io/maxid/pen/aYPBQG?editors=0110](https://codepen.io/maxid/pen/aYPBQG?editors=0110)

### Steps to reproduce
只需要将SearchBar放置在TabBar的TabBar.Item内即可重现

### What is expected?
https://mobile.ant.design/kitchen-sink/components/search-bar?lang=zh-CN#search-bar-demo-0
样式不要走样

### What is actually happening?
Search Icon 移位，Clear Icon 移位

---
发现Search Icon和Clear Icon的宽高无效

![image](https://user-images.githubusercontent.com/927429/38477247-3d9e7a54-3be4-11e8-94ce-e2fee23bad76.png)
![image](https://user-images.githubusercontent.com/927429/38477308-7517b2a2-3be4-11e8-95ee-e893ae1f8d52.png)

**Comment by warmhug** [comment]
Maybe you need to override the style yourself ?

**Comment by maxid** [comment]
@warmhug 这个是ant-design-mobile组件本身组合引起的问题（理解是一个bug），不应该由使用人员重写样式去解决吧，毕境这么多组件，可能会有很多种组合，当然目前我会自己花时间解决这个问题 ...

**Comment by biubug123** [comment]
老哥，自己调样式吧，我也是自己调的，同样的情况

**Comment by maxid** [comment]
@biubug123 你是怎样调的，分享下～

**Comment by Breaker-93** [comment]
@maxid 你可以这样试试，找到 ant-mobile/lib/tabs/style/index.css,注掉第二个样式选择器，
`.am-tabs * {
     -webkit-box-sizing: border-box;
     box-sizing: border-box;
}`
或者ant-mobile/lib/tabs/style/index.less文件，注掉如下样式（大概在第26行左右）：
`* {
      box-sizing: border-box;
    }`

**Comment by Breaker-93** [comment]
@maxid 当然，如果你引入的是antd-mobile/dist/antd-mobile.css或.less这个合并后的文件，你就对应搜索找到 `.am-tabs * { box-sizing: border-box; }` ; 如果感觉这样麻烦，你还可以在引入SearchBar的地方增加优先级重定义覆盖掉antd-mobile对box-sizing的样式设定。
