### ISSUE TITLE
PullToRefresh 导致ListView使用react-sticky分组无效果

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design-mobile#2449]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
react

### Reproduction link
[http://react-component.github.io/m-list-view/examples/base-sticky.html](http://react-component.github.io/m-list-view/examples/base-sticky.html)

### Steps to reproduce
在ListView加上pullToRefresh组件

### What is expected?
分组效果

### What is actually happening?
分组标题看不到

---
由于 pullToRefresh 上的transform: translate3d(0px, 0px, 0px);样式导致sticky position: fixed无效

**Comment by micooz** [comment]
此问题原因是 `rmc-pull-to-refresh` 使用了 `transform: translate3d(0px, 0px, 0px)` 使 `react-sticky` 的 `position: fixed` 失效。

更具体的分析可参考：
https://stackoverflow.com/questions/15194313/transform3d-not-working-with-position-fixed-children

估计不太好修复，建议这两个功能不要同时使用。

**Comment by warmhug** [comment]
建议自己根据业务做个简单版本的 PullToRefresh 吧
