### ISSUE TITLE
rn是否支持icon组件，并且支持icon库本地化部署

### ISSUE THREAD

**Issue by zjsxfly** [ant-design/ant-design-mobile#245]
rn是否支持icon组件，并且支持icon库本地化部署

**Comment by silentcloud** [comment]
@zjsxfly antd-mobile 是纯 UI 的组件库，目前 icon 组件无法支持，web 的 icon 组件是利用的 font，而 native 这层第三方字体是需要 native 模块的做的；如果你的项目里需要 icon，可以使用这个库先：https://github.com/oblador/react-native-vector-icons
