### ISSUE TITLE
Calendar 组件缺少value属性，表单中无法使用

### ISSUE THREAD

**Issue by guxingke201** [ant-design/ant-design-mobile#2451]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表单中使用可以使用Calendar组件

### What does the proposed API look like?
类似其他Data Entry组件，提供value属性

**Comment by warmhug** [comment]
@zhang740 评估下是否需要

**Comment by guxingke201** [comment]
antd的[RangePicker](https://ant.design/components/date-picker-cn/)组件有value属性

**Comment by doxiaodong** [comment]
@likezero

**Comment by moldauder** [comment]
+1 ，类似antd calendar组件，目前无法实现月份切换的功能。实际业务场景中存在这样的需求（只展示一个月，通过切换实现上个月、下个月，如预订类业务）

**Comment by guxingke201** [comment]
@likezero 请问已经修复了吗？在哪个版本

**Comment by chen86860** [comment]
可以通过更新 `defaultDate ` 的值 + 给定 Calendar 一个  key 值来强制更新，以达到月份切换的目的。

例：
```jsx
<Calendar key={new Date(currentDate)} defaultDate={new Date(currentDate)} />
```
