### ISSUE TITLE
ListView 同时设置useBodyScroll,pullToRefresh时，导致同一个页面所有拥有onTouch事件的组件在拖动时，listView也会跟随拖动

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design-mobile#2452]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
react

### Reproduction link
[https://github.com/ksh033/test/blob/master/images/listviewBug2.png](https://github.com/ksh033/test/blob/master/images/listviewBug2.png)

### Steps to reproduce
同一个页面添加ListView,DatePicker组件，ListView同时设置useBodyScroll,pullToRefresh

### What is expected?
日期选择

### What is actually happening?
日期选择年、月、日时，ListView也会跟随拖动

---
ListView做分组是否一定需要设置useBodyScroll。有没有其它方式

**Comment by liangwd** [comment]
同样遇到这个问题
同一页面同时使用ListView(pullToRefresh)和DatePicker组件。
日期选择年、月、日时，ListView也会跟随拖动。
我的解决方法是使用datePicker时，隐藏ListView，以达到互不影响的目的。
但是这样只能是个临时解决方案：因为显示ListView时，长列表又重新第一列开始展示数据。
是不是能通过组件内部阻止事件传播解决这个问题？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
