### ISSUE TITLE
在react-native中使用antd-mobile替换全局主题色问题

### ISSUE THREAD

**Issue by HiMrHu** [ant-design/ant-design-mobile#2453]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
react-native 0.41 node8.9

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui#antd-mobile-with-rn-custom-ui](https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui#antd-mobile-with-rn-custom-ui)

### Steps to reproduce
根据官方提供的样例,并且在例子中加入Button组件之后组件的颜色没有变化,

对应的theme.js
```JavaScript
module.exports = {
  brand_primary: 'red',
  color_link: 'red',
  border_color_base: 'green',
};
```
并且通过 npm start 启动开发服务器
### What is expected?
![示例](http://wx2.sinaimg.cn/mw690/0060lm7Tly1fq7izr3z03j30al0iljsl.jpg
)

### What is actually happening?
预期Button组件颜色应该是红色的,或者和theme.js中  brand_primary 对象一致, 想问问应该怎么做.

**Comment by HiMrHu** [comment]
搞定收工

**Comment by HiMrHu** [comment]
@xiayuxiaoyan  就是使用组建的时候，如果出现和预期的不一致，那么就去看看组件对应的样式文件，里面用的那个样式名，然后再替换对应的，没效果是名字不对，教程的方法是脚本直接替换源文件的样式，那么就去找没起作用的那个到底叫什么名字。。。。嫌麻烦就直接搜颜色。然后在脚本里面添加上那个颜色对应的名字。

**Comment by xiayuxiaoyan** [comment]
@HiMrHu 嗯嗯这样的确可以。我现在解决了是用的另外一种方法。不知道是不是官方文档的bug，theme文件替换的哪个脚本有些问题，导致theme文件头部的var brandPrimary = "xxxx"; var brandPrimaryTap = "xxxx"在自定义修改的时候已经提前生效，所以自己重新定义主题色也没用，因为js中用到这个变量的地方提前被初始化为theme文件初始设置。
这是我重写后的脚本https://github.com/xiayuxiaoyan/--/blob/master/custom-rn-theme.js
