### ISSUE TITLE
在web应用中，不是（Rn）,使用2.x版本mobile listView组件，如何自动scrollview的高度？

### ISSUE THREAD

**Issue by qhy90223** [ant-design/ant-design-mobile#2454]

**Comment by vince-fly** [comment]
要么usebody，要么style添加height...使用zscroller，也同样需要设置
`componentDidMount() {
let height = document.documentElement.clientHeight - ReactDOM.findDOMNode(this.lv).parentNode.offsetTop;            
            this.setState({height});
}
......
<ListView
   .....
   style={{height:this.state.height}}
.....
`
