### ISSUE TITLE
Picker values inconsistent when scrolling and clicking ok before the picker lands on an item.

### ISSUE THREAD

**Issue by leedriscoll** [ant-design/ant-design-mobile#2456]
**Version**
2.1.8

**Environment**
iOS11 and Android

**Steps to reproduce**

- Create a long picker list (with 5 or more items)
- Open the picker and scroll from top to bottom and click OK before the picker stops animating / lands on an item - see gif.
- Please not it does happen every single time, it only happens when you do this really quickly.

**What is expected?**

Either the last item is selected or the first item is selected.
I'd expect the onOK event to pass through the value of the first picker item (because scrolling to the last didn't finish) but I'd expect onChange event to have the value of the last picker item.

What is actually happening?

The last item is selected on the picker popup but the first (or current value) is select on the top level picker. 

Both the onChange and onOk event passes the value of the first picker item - however the picker view shows the last picker item as selected

![ezgif-4-e45b9d4880](https://user-images.githubusercontent.com/940369/38636839-49c62122-3dc1-11e8-8329-c7569e7a4979.gif)

**Comment by warmhug** [comment]
Close for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452
