### ISSUE TITLE
ListView 组件 pageSize 属性在 iPhone X 和其他手机上表现不一致

### ISSUE THREAD

**Issue by xwartz** [ant-design/ant-design-mobile#2463]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.6

### Environment
iPhone X、Chrome 最新

### Reproduction link
[https://mobile.ant.design/components/list-view-cn/](https://mobile.ant.design/components/list-view-cn/)

### Steps to reproduce
ListView pageSize 设置为 10，实际数据 15 条。
1. iPhone X 只会显示 10 条
2. 其他手机显示 15 条

### What is expected?
iPhone X 和 其他手机显示一样

### What is actually happening?
iPhone X 和其他手机显示不一致

**Comment by xwartz** [comment]
设置 initialListSize 解决

**Comment by davychan1985** [comment]
@KgTong  你好，initialListSize、pageSize设置为10，为什么在安卓部分机型一开始只显示2个
