### ISSUE TITLE
Errors with typescript with Popover Modal Toast.info Modal.alert 

### ISSUE THREAD

**Issue by torque2** [ant-design/ant-design-mobile#2465]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
browser version

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo](https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo)

### Steps to reproduce
1)               <Popover.Item
                    className="test"
                    value={k}>
                    test
                </Popover.Item>);

error TS2339: Build:La propri�t� 'value' n'existe pas sur le type 'IntrinsicAttributes & IntrinsicClassAttributes<Item> & Readonly<{ children?: ReactNode; }>

1) value doesn't existe for <Popover.Item>
2) <Modal> the props "title" doesn't accept string / Modal.Alert ( x ...) doesn't accept string
3) Toast.info doesn't accept JSX.Element
4) <Popover.Item doesn't accept the fonction onClick

### What is expected?
No types errors like in mobile.antd 2.1.6

### What is actually happening?
remove type errors

**Comment by warmhug** [comment]
Trace #2407
