### ISSUE TITLE
微信多开，只有其中一个实例的内置浏览器能调起图片选择组件ImagePicker

### ISSUE THREAD

**Issue by Pysics** [ant-design/ant-design-mobile#2467]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
MIUI 9.5 Android 7.1.1 微信最新版 微信双开

### Reproduction link
[https://1drv.ms/v/s!AlUUKwiz7PMv5Toac37QeLplPKVR](https://1drv.ms/v/s!AlUUKwiz7PMv5Toac37QeLplPKVR)

### Steps to reproduce
使用官方demo代码，在99%手机上没问题

### What is expected?
微信多开不影响ImagePicker组件

### What is actually happening?
只有一个微信实例能正常使用

**Comment by warmhug** [comment]
特殊情况，不处理了...
