### ISSUE TITLE
datepicker 以及相關使用到 date 的 component 統一使用 moment

### ISSUE THREAD

**Issue by jackypan1989** [ant-design/ant-design-mobile#2470]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
讓 antd-mobile 在使用 date 的情境中用 moment 處理
這樣就會跟 antd 版本一致

### What does the proposed API look like?
https://ant.design/components/date-picker-cn/

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/commit/0a307f0bec477cd5e7cc90e94ee09b184ab0792c

Moment 是有意去掉的，因为对移动环境来说太大了。
