### ISSUE TITLE
RN Picker组件点击蒙板无法隐藏

### ISSUE THREAD

**Issue by androidwt** [ant-design/ant-design-mobile#2474]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
交互体现比较差,点击蒙板没法隐藏(隐藏方式 只可点击取消 或者确定),而对应的取消 或者确定 点击区域要小很多

### What does the proposed API look like?
添加属性  可控制 蒙板点击是否消失  另添加消失监听(消失时可自行选择重置或者不重置当前选中值)

**Comment by warmhug** [comment]
经测试，点击蒙板 可以隐藏。有 `onVisibleChange` 方法可用、忘了加到文档上了。
