### ISSUE TITLE
InputItem[type=money] 弹出键盘后再点击Modal[popup]组件, 键盘没有自动隐藏

### ISSUE THREAD

**Issue by xiaochunyong** [ant-design/ant-design-mobile#2475]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
随意

### Reproduction link
[https://github.com/xiaochunyong/antd-mobile-issue](https://github.com/xiaochunyong/antd-mobile-issue)

### Steps to reproduce
启动项目后,  点击额度输入框, 弹出金额数字键盘,  再点击右边的放大镜按钮, 会弹出一个Modal,  但是金额键盘却没有隐藏, 而且也无法隐藏了

### What is expected?
能正常隐藏

### What is actually happening?
没有隐藏

**Comment by xiaochunyong** [comment]
半年前我就提交过一次了https://github.com/ant-design/ant-design-mobile/issues/2065, 貌似一直没有修复....这个问题很困惑....麻烦快一点修复, 谢谢.

**Comment by warmhug** [comment]
首先 在 react 15 下没问题。这样 #2065 的修复应该是没起作用。
在 react 16 下、页面中产生多个实例键盘、多份 dom、出现隐藏错误，待确认是否改为像 react 15 下的单例 单份dom 方式。
