### ISSUE TITLE
使用Modal.alert()时，message参数传一个长列表需要滚动的组件，滚动失效

### ISSUE THREAD

**Issue by huangming1994** [ant-design/ant-design-mobile#2477]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
ios

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/alert.tsx](https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/alert.tsx)

### Steps to reproduce
1. 使用Modal.alert()时，message参数传一个长列表需要滚动的组件
2. 无法触发滚动

### What is expected?
可以滚动

### What is actually happening?
无法滚动

**Comment by huangming1994** [comment]
看了下，是modal.alert里阻止了touchmove，不过不是很明白下面这两段代码。
![antd1](https://user-images.githubusercontent.com/20809574/39010953-bbcbdb4a-4442-11e8-9359-88e8aa2384d3.jpeg)
![antd2](https://user-images.githubusercontent.com/20809574/39010961-c19c07fc-4442-11e8-8dc0-84a963ee4d5a.jpeg)

1. touchmove触发的时候，modal.alert的结构target是am-modal-wrap，父级找上去永远匹配不到am-modal-footer，导致ios下都被preventDefault。

2. 还有不是很明白为什么ios下找不到am-modal-footer的话，要阻止掉touchmove。

**Comment by huangming1994** [comment]
暂时用npm scoped package替换antd-mobile，添加alias: { 'antd-mobile': '@username/antd-mobile' },  babelrc中的按需加载`LibraryName`字段无须修改。

**Comment by warmhug** [comment]
Close for #2486
