### ISSUE TITLE
homepage 经常无法访问

### ISSUE THREAD

**Issue by 1ncounter** [ant-design/ant-design-mobile#2479]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
chrome  mac 

### Reproduction link
[https://mobile.ant.design/](https://mobile.ant.design/)

### Steps to reproduce
打开链接

### What is expected?
能正常访问

### What is actually happening?
无法访问

**Comment by paranoidjk** [comment]
Ant Design 系列官网由于某些众所周知的原因无法访问，建议翻墙或访问国内镜像站点。
## 官网
* Ant Design: https://ant.design
* Ant Design Pro: https://pro.ant.design
* Ant Design Mobile: https://mobile.ant.design
* Ant Motion: https://motion.ant.design
## 国内镜像
* Ant Design: http://ant-design.gitee.io
* Ant Design Pro: http://ant-design-pro.gitee.io
* Ant Design Mobile: http://antd-mobile.gitee.io
* Ant Motion: http://ant-motion.gitee.io
