### ISSUE TITLE
Calendar 日历控件 Firefox（59.0.2 (64 位) 下确认按钮部分被遮挡。

### ISSUE THREAD

**Issue by zyj1022** [ant-design/ant-design-mobile#2481]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
mac(10.13.4)  Firefox（59.0.2 (64 位)

### Reproduction link
[https://mobile.ant.design/components/calendar-cn/#components-calendar-demo-basic](https://mobile.ant.design/components/calendar-cn/#components-calendar-demo-basic)

### Steps to reproduce
打开官网 https://mobile.ant.design/components/calendar-cn/#components-calendar-demo-basic 
在 Firefox 中 代码演示部分，点击任意一个按钮，出现日历选择控件，选择日期区间，无法出现确认按钮部分。

### What is expected?
出现以上确认部分按钮。

### What is actually happening?
无法点击确认。

---
当前解决方案：
.am-calendar .confirm-panel {
    position: fixed;
    bottom: 0;
    width: 100%;
    padding: 5px 4%;
  }
以上样式即可解决这个问题，暂测试可以
请测试并修正这个bug。
谢谢。

**Comment by warmhug** [comment]
在手机上没相应问题。
在 Mac Firefox 上确实有展示问题，但你给的修复方法不可行，还不确定怎么修复。
先换用 Mac Chrome 浏览器。

**Comment by doxiaodong** [comment]
@likezero

**Comment by likezero** [comment]
尝试过移动端的效果吗
