### ISSUE TITLE
Import issue in Modal's PropTypes.d.ts

### ISSUE THREAD

**Issue by wfsm** [ant-design/ant-design-mobile#2488]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
MacOS 10.13.4, Chrome 65

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples/tree/master/web-typescript](https://github.com/ant-design/antd-mobile-samples/tree/master/web-typescript)

### Steps to reproduce
You could use your own sample to reproduce this issue.
1. git the sample repo, locate to web-typescript folder and `npm install`
2. `npm start`

### What is expected?
Webpack compile ok and show page in browser

### What is actually happening?
Webpack compile failed, got error: 
`ERROR in /Users/wanglei/projects/github/antd-mobile-samples/web-typescript/node_modules/antd-mobile/lib/modal/PropsType.d.ts
(3,38): error TS2307: Cannot find module 'react-native'`

---
I located the PropTypes.d.ts file, it doesn't separate into web and native version, and import PropTypes from 'react-native' as default.

**Comment by DasonCheng** [comment]
same ! 

## workspace
> config-overrides.js

```js
const tsImportPluginFactory = require('ts-import-plugin')
const {
  getLoader,
  injectBabelPlugin
} = require("react-app-rewired");

module.exports = function override(config, env) {
  // do stuff with the webpack config...
  const tsLoader = getLoader(
    config.module.rules,
    rule =>
    rule.loader &&
    typeof rule.loader === 'string' &&
    rule.loader.includes('ts-loader')
  );

  tsLoader.options = {
    getCustomTransformers: () => ({
      before: [
        tsImportPluginFactory([{
          libraryDirectory: 'es',
          libraryName: 'antd-mobile',
          style: 'css',
        }]),
      ]
    })
  };

  return config;
};
```
> import

```tsx
import { Button } from 'antd-mobile'
```

> error

```bash
Failed to compile.
**/node_modules/antd-mobile/lib/modal/PropsType.d.ts
(3,38): error TS2307: Cannot find module 'react-native'.
```

## antd-mobile

```ts
// antd-mobile/es/modal/index.d.ts
import Modal from './Modal';
export default Modal;

// antd-mobile/es/modal/Modal.d.ts
/// <reference types="react" />
import React from 'react';
import { Action, ModalComponent, ModalPropsType } from './PropsType';
...

// antd-mobile/es/modal/PropsType.d.ts
import React from 'react';
import { StyleProp, TextStyle } from 'react-native';
...
```

**Comment by bang88** [comment]
https://github.com/ant-design/ant-design-mobile/pull/2407
