### ISSUE TITLE
无障碍:Accordion组件在Android上不读出展开折叠状态

### ISSUE THREAD

**Issue by liwufu** [ant-design/ant-design-mobile#2491]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
Android系统

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/accordion?lang=zh-CN#accordion-demo-0](https://mobile.ant.design/kitchen-sink/components/accordion?lang=zh-CN#accordion-demo-0)

### Steps to reproduce
1、开启屏幕朗读（iOS的VoiceOver，Android的语言助手等）
2、选中Accordion组件的title部分进行朗读

### What is expected?
1.聚焦时朗读出展开折叠状态“已折叠/已展开”；
2.切换状态后读新状态“已折叠/已展开”。

### What is actually happening?
Android上展开折叠状态不朗读。
另：iOS上展开状态下回朗读，折叠不朗读

**Comment by KgTong** [comment]
有两个点
+ 官网的例子是在preact下运行，preact会忽略值为false的属性，导致iOS下折叠不朗读。Accordion组件底层依赖[Collapse](https://github.com/react-component/collapse)组件，Collapse中使用了`aria-expanded`无障碍属性，当为false时，在preact下被忽略，[已修复](https://github.com/react-component/collapse/pull/86)
+ Android下对于 `aria-expanded`属性支持不是很好。组件库暂不不支持
