### ISSUE TITLE
Unable to resolve module 'react-dom' from '.../node_modules/rc-animate/lib/AnimateChild.js

### ISSUE THREAD

**Issue by EnzzoPerez** [ant-design/ant-design-mobile#2492]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
Ubuntu 17.10, firefox 59.0.2, React Native 0.54.1

### Reproduction link
[https://github.com/EnzzoPerez/reverseWordRN](https://github.com/EnzzoPerez/reverseWordRN)

### Steps to reproduce
When running yarn start (for Expo) or yarn run android (for emulator) it returns the message of the image uploaded in another item

### What is expected?
I expected the emulator to boot, but it hangs in that message.

### What is actually happening?
attached link to the message image

https://ibb.co/dN19rx

**Comment by warmhug** [comment]
Why your Reproduction link repo not use antd-mobile ? ref https://mobile.ant.design/docs/react/introduce#3.-Usage 
Use babel-plugin-import https://github.com/ant-design/babel-plugin-import

**Comment by EnzzoPerez** [comment]
I deleted the project package because it can not solve the problem. Thank you anyway.

**Comment by warmhug** [comment]
The problem still exists?

**Comment by EnzzoPerez** [comment]
sincerely I did not try to make it work again in another project, at another time I may do it, for now I close the issue.
