### ISSUE TITLE
rmc-nuka-carousel import error

### ISSUE THREAD

**Issue by bazingaedward** [ant-design/ant-design-mobile#2498]
ant design 的Carousel 在gitlab中的源码底层调用的是rmc-nuka-carousel，而如果用户直接npm安装这个包的话会报错，提示：
Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

按照官方的说法要么是react 多版本依赖问题或是functional component 的ref引用问题，经检测，版本没问题，而是后面的引用出问题。

重新安装nuka-carousel后问题解决，奇怪的是nuka-carousel和rmc-nuka-carousel的介绍是同一个页面，很容易产生误导，而且通过npm安装的版本是不同的，也就是说这两个属于不同的包。

**Comment by warmhug** [comment]
包名是不一样的呀

**Comment by warmhug** [comment]
Close for https://github.com/react-component/nuka-carousel/commit/7316b7875c9e1c3744260190e349841d209b1694
