### ISSUE TITLE
无法使用自定义源码路径

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design-mobile#250]
用的脚手架：
https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo

当使用默认路径编译，可以成功运行，但如果把源码路径改掉则出现：
Cannot resolve module 'antd-mobile'

const appName = "csmobile";

const apps = {
    "csmobile":{
        entry:{index:"D:\\My_Develop\\project\\src4js\\mobile1.0\\test.web.js"},
        output:{
            path:"D:\\My_Develop\\project\\js"
        }
    }
}

webpackConfig.entry = apps[appName].entry;
webpackConfig.output.path = apps[appName].output.path;

**Comment by yiminghe** [comment]
项目源码必须在脚手架目录内
