### ISSUE TITLE
Picker and SearchBar do not pick up LocaleProvider context

### ISSUE THREAD

**Issue by jumpinjackie** [ant-design/ant-design-mobile#2502]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
Windows 10, Chrome

### Reproduction link
[https://codepen.io/anon/pen/JvEqXM](https://codepen.io/anon/pen/JvEqXM)

### Steps to reproduce
1. Modify `start` script in `package.json` to use `preact` instead of `react` for `DEMO_ENV` in both start configurations

```
cross-env NODE_ENV=development concurrently \"cross-env DEMO_ENV=react bisheng start -c ./site/bisheng.desktop.config.js\" \"cross-env DEMO_ENV=react bisheng start -c ./site/bisheng.kitchen.config.js\"
```

2. Open LocaleProvider demo
3. Switch to English (hit `切换到英文` button)

### What is expected?
All displayed components should be using english strings in `en_US` locale

### What is actually happening?
The `Picker` and `SearchBar` components still use chinese strings

---
This does not happen on the demo site because it is using Preact (not React) and the components in question must have used some preact-specific context API. The `Picker` and `SearchBar` components are missing contextTypes to pull in the current locale from the parent LocaleProvider

```
static contextTypes = {
  antLocale: PropTypes.object,
};
```

**Comment by CJY0208** [comment]
+1 看起来其他的组件可能也会有这样的问题，数字键盘中的“确定”按钮文案表现也有问题

**Comment by doxiaodong** [comment]
数字键盘， https://github.com/ant-design/ant-design-mobile/pull/2538

**Comment by doxiaodong** [comment]
@KgTong , 关联 pr 已经合并，这个修复了么
