### ISSUE TITLE
grid 默认给每个item一个height值为屏幕宽度/4 导致item超过这个Height部分无法正常显示

### ISSUE THREAD

**Issue by fangkyi03** [ant-design/ant-design-mobile#2503]
antd mobile中 将grid的height分割成了 屏幕的宽度/4
这种设计 导致 如果组件超过这个高度的话 就会出现显示不全的问题

**Comment by likezero** [comment]
can you provide a demo to reproduce the problem?

**Comment by fangkyi03** [comment]
不用麻烦的演示 直接在grid下面 插入一个超过height/4高度的组件 并且backgroundColor:'red' 以后你就可以看到 子组件的试图无法超过height定义的高度 除非在style里面 使用height:undefined 放弃掉 你们原有定义的height才可以

**Comment by likezero** [comment]
请这样试试
`<Grid square={false}`

**Comment by fangkyi03** [comment]
这个写着不是web only的 你确定rn可以用吗

**Comment by fangkyi03** [comment]
按你的方式加了以后 样式完全错乱了 必须在itemStyle中增加一个height:undefined才回复正常
而且比较头疼的是 你这个也设置不了底部的圆点组件 想移动一下位置 移动到最底部都不行 现在有点遮挡试图

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/39660303-7c817836-506e-11e8-8f10-b724268be888.png)
你们grid里面写的很清楚 height这个会在所有的item里面都增加一个屏幕宽度/4的值 会应用到所有的item上面 外部只能用height:undefind强制放弃掉height这个属性 不然item的视图永远超不出这个height设置

**Comment by warmhug** [comment]
@fangkyi03  请按 issue 模板写问题！特别是 RN 问题，要首先指明是 RN 平台！

**Comment by lingliMr** [comment]
我遇到了同样的问题。我是组建高度小于默认格子高度 屏幕宽度/ 4 时。
未铺满的行就会被默认高度撑开，导致很多空白出现。
像这样：
 <Grid data={this.data} isCarousel hasLine={false} columnNum={4} itemStyle={{height:100,backgroundColor:'red'}}

实际是这样的：
![image](https://user-images.githubusercontent.com/25763495/40476488-bbe9a342-5f76-11e8-8eec-907808343982.png)
当项目项目只有四个的时候显示是正常的。

**Comment by warmhug** [comment]
自己设置 itemStyle height，根据自己需求做覆盖吧。
或者组件怎么做、能解决这些问题呢？有建议吗？

**Comment by lingliMr** [comment]
@warmhug 我的自己设置了itemStyle height的，如果组件刚好铺满的话高度会覆盖掉，不会出现问题。
但是如果一行放四个格子，组件只占了两个，这时候另外两个会被默认组件的高度占用（没有被覆盖？）。
这时如果组件高度小于默认高度，那默认的就会将整个view的高度撑开，如果这时组件的高度大于默认的高度，高度会时组件的高度撑开。
建议修改成如果有 itemStyle的样式的时候，默认组件的样式不应被渲染。

**Comment by warmhug** [comment]
@lingliMr 你的描述最后部分还是不通顺、没理解，可以提 pr 来更好说明问题。
现在代码设置了 itemStyle 是会覆盖预设样式的、看这里
https://github.com/ant-design/ant-design-mobile/blob/eb0b1f28a870297cf8ce85686086745b07fe08f4/components/grid/index.native.tsx#L93
只是这里
https://github.com/ant-design/ant-design-mobile/blob/eb0b1f28a870297cf8ce85686086745b07fe08f4/components/grid/index.native.tsx#L102
没覆盖掉，是这里的问题吗？

**Comment by fangkyi03** [comment]
在itemStyle里面用height:undefined可以解决这个问题 就是舍弃掉你们组件自身赋予的那个高度就可以了
