### ISSUE TITLE
Calendar 在 ios(safari) 中 new Date('YYYY/MM') 或者 new Date('YYYY-M') 会是一个Invalid Date，导致组件报错

### ISSUE THREAD

**Issue by swdenglian** [ant-design/ant-design-mobile#2504]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
ios(safari)

### Steps to reproduce
```
 <Calendar
     defaultDate={new Date('2018/01')}
  />
```
或者
```
 <Calendar
     defaultDate={new Date('2018-1')}
  />
```

### What is expected?
抛出 Invalid Date 报错信息，并提示可能产生的问题  ios 中 对时间格式有要求

### What is actually happening?
rmc-calendar  es/DatePicker.base.js 第55行报错，使用者查找错误要一行一行的查找。

**Comment by warmhug** [comment]
日期格式，需要自己保证浏览器兼容性

**Comment by cca313** [comment]
DatePickerView组件
mode='time'的情况下 
onchange事件返回的值ios系统下是invalid date
ios系统12.0.1 
@warmhug @ziluo @doxiaodong

**Comment by swdenglian** [comment]
> DatePickerView组件
> mode='time'的情况下
> onchange事件返回的值ios系统下是invalid date
> ios系统12.0.1
> @warmhug @ziluo @doxiaodong

ios 系统下对Date 是有严格的要求，自己注意 时间字符串的问题。改成ios下标准的字符串就可以了。

**Comment by cca313** [comment]
好吧 百转千回终于把日期问题搞定了
