### ISSUE TITLE
使用Stepper时，ios11点击会触发2次onChange 

### ISSUE THREAD

**Issue by ningzhenyi** [ant-design/ant-design-mobile#2505]
只有在ios11和谷歌调试会出现。

**Comment by han88829** [comment]
我也遇到了同样的问题，更新两次数据，浏览器警告：
Unable to preventDefault inside passive event listener due to target being treated as passive；


I also encountered the same problem, updating the data twice, the browser warned:
Unable to preventDefault inside passive event listener due to target being treated as passive

**Comment by ningzhenyi** [comment]
@ant-design-bot

**Comment by ningzhenyi** [comment]
@paranoidjk

**Comment by warmhug** [comment]
Trace #2468
