### ISSUE TITLE
Add a link to ListView component in List docs

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design-mobile#2514]
What about a LazyList variation of List? That renders only ListItems in the viewport - like here: https://onsen.io/v2/api/react/LazyList.html

**Comment by warmhug** [comment]
Try `ListView`.

**Comment by avalanche1** [comment]
Thank you, that's exactly what I was looking for.

**Comment by avalanche1** [comment]
I would ask doc maintainers though to mention ListView component in List docs. Because it's rather unintuitive - as you can see by me posting an issue here.
Therefore a text like this sd be in List docs: `In case you need an infinite scroll list - consider using ListView(https://mobile.ant.design/components/list-view/) component`
