### ISSUE TITLE
Toast 打开之后不可以立即关闭

### ISSUE THREAD

**Issue by myLazyProgrammer** [ant-design/ant-design-mobile#2515]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
windows chrome: 66.0.3359.139

### Reproduction link
[https://codepen.io/mylazyprogrammer/pen/MGOYym](https://codepen.io/mylazyprogrammer/pen/MGOYym)

### Steps to reproduce
Toast.loading('lodaing',0)；
if(true){
Toast.hide()
}

### What is expected?
期望Toast可以立即关闭

### What is actually happening?
Toast不能立即关闭

---
打开页面之后有一个中转页判断是否登录，登录页面最开始使用Toast.loading()方法;
首先需要判断token标识是否存在;
如果判断token标识不存在的时候跳转到另一个路由页面 ;
此时使用Toast.hide(),无法关闭;
使用setTimeout 延时100毫秒之后可以实现 || 只有在token存在时使用Toast.loading()方法调用请求之后关闭可以实现;
希望可以有使用Toast之后可以立即关闭的机制;

**Comment by warmhug** [comment]
你这个需求适合用 ActivityIndicator 组件来做，请查看相应示例。使用 Toast 也不用延时100毫秒，有 setTimeout 就行。

**Comment by youshao** [comment]
升级antd-mobile后也遇到这个问题了。官方不打算处理这个bug吗？

**Comment by acmilank22** [comment]
+1
