### ISSUE TITLE
Type declaration file import react error(类型声明文件导入 React 报错)

### ISSUE THREAD

**Issue by linkFly6** [ant-design/ant-design-mobile#2518]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
@ types/react@16.3.5, antd-mobile@2.1.8,  typescript@2.8.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/38z1mkz0zp)

### Steps to reproduce
In vscode, create a new file `demo.tsx`:

在 vscode 中创建新文件 `demo.tsx`：

```tsx
import * as React from 'react'
import { Modal, Toast } from 'antd-mobile';

class Demo extends React.Component<any, any> {
  public render() {
    return (
      <div className="result">
         {/* [ts] JSX 元素类型“Modal”不是 JSX 元素的构造函数。类型“Modal”中缺少属性“setState”。 */}
        <Modal>
          <p>test</p>
        </Modal>
      </div>
    );
  }
}
```

install `typescript@2.8.3`, `antd-mobile@2.1.8`, `@types/react@16.3.5`, you can see an error in vscode.

安装对应的包，即可在 vscode 中看到上面代码中标记的报错。

**tsconfig.json**:

```json
{
  "include": [
    "**/*.ts",
    "**/*.tsx"
  ],
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "es5",
      "es6",
      "dom"
    ],
    "rootDir": ".",
    "allowJs": true,
    "jsx": "react",
    "sourceMap": true,
    "strict": true,
    "baseUrl": ".",
    "moduleResolution": "node",
    "importHelpers": true,
    "suppressImplicitAnyIndexErrors": true,
    "experimentalDecorators": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
  },
  "compileOnSave": true,
}
```

Because of the type declaration of antd-mobild, `import React from'react'` is used, and in the new version, TypeScript is recommended to use `import * as React from'react'`.

原因是因为 `antd-mobild` 的类型声明，使用的是 `import React from 'react'` 语法，而在新版中 TypeScript 中(在 TypeScript 2.5 以后)，推荐使用 `import * as React from 'react'`。

### What is expected?
`antd-mobile` components no error in TypeScript.

`antd-mobile` 在 TypeScript 环境中不会报错。

### What is actually happening?
`antd-mobile` components are wrongly reported in TypeScript.

`antd-mobile` 在 TypeScript 中报错。

---
fix Type declaration:  ` import React from 'react'`  modified to  `import * as React from  'react'`.

**Comment by doxiaodong** [comment]
这个改动比较大，涉及到更下层的依赖 rmc ，参考 https://github.com/ant-design/ant-design-mobile/pull/2507

**Comment by fujinxiang** [comment]
不准备改了吗？

**Comment by doxiaodong** [comment]
后面计划先改 rmc-xxx 的部分，由下往上，现在先加 allowSyntheticDefaultImports: true
