### ISSUE TITLE
List Item - ripple animation fires AFTER click event

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design-mobile#2519]
So, when I have onClick function on a List Item - it gets executed _before_ the ripple animation. That's not right.
Ripple animation = `<List.Item platform="android"`/>

**Comment by likezero** [comment]
yes, source code like this:
```js
<TouchFeedback
        {...touchProps}
        disabled={disabled || !onClick}
        activeStyle={activeStyle}
        activeClassName={`${prefixCls}-item-active`}
      >
        {content}
      </TouchFeedback>
```
ripple animation is fired on Component `TouchFeedback`
click is fired on `content`
