### ISSUE TITLE
移动端图片上传问题

### ISSUE THREAD

**Issue by shenke119** [ant-design/ant-design-mobile#252]
ImagePicker 暂不支持图片上传，请问有什么好的方法或组件 实现上传?

**Comment by pingan1927** [comment]
移动端的图片上传，一般都是通过ajax将`ImagePicker`返回的Base64图片数据异步上传给服务器，服务器返回一个图片url地址（可能包含id，具体视业务需要），也可以调用客户端容器提供的上传图片能力，这个后续会考虑集成进来。

**Comment by LayGit** [comment]
希望能将点击 “+” 号的操作开放出来，比如在微信中可以调用JSSDK的提供的方法上传，具体什么环境如何上传让开发者自行处理，当然可以默认 file input 方式。

**Comment by pingan1927** [comment]
这个功能会尽快提供

**Comment by pingan1927** [comment]
`0.9.3`会上

**Comment by nouh** [comment]
能否让上传的那个+号变成用户可替换的任意图标或是组件

**Comment by warmhug** [comment]
@nouh 自己覆盖样式
