### ISSUE TITLE
Docs - typo

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design-mobile#2522]
List - Input List code example sd be:
> callback(new Error('At least four charactErs for account'));

instead of 
> callback(new Error('At least four charactOrs for account'));

**Comment by avalanche1** [comment]
Dear @micooz, https://github.com/ant-design/ant-design-mobile/pull/2523/commits/f2a34899c77a48b96e28f8364ea0f0624217d436 doesnt fix the List component docs.

**Comment by KgTong** [comment]
@avalanche1 PR is Welcome~

**Comment by avalanche1** [comment]
Ah, I'm sorry - looks like the PR actually does fix it 😺
