### ISSUE TITLE
(建议)InputItem建议error属性使用方式改为error＝“true”  error＝“false”这种使用方式

### ISSUE THREAD

**Issue by miss61008596** [ant-design/ant-design-mobile#253]
#### 本地环境

- antd-mobile 版本："0.8.x"
- 操作系统及其版本：OSX 
- 浏览器及其版本：Google Chrome 51.0.2704.63 (64-bit)

#### 你做了什么？

InputItem 动态校验变化
#### 你期待的结果是：
error＝“true”  error＝“false” 生效

#### 实际上的结果：
有 error属性 ， 或者没有

#### 可重现的在线演示

![image](https://cloud.githubusercontent.com/assets/6361237/18478588/c3732454-7a0c-11e6-831d-cc2bdad16448.png)
改了以下两处  感觉控制起来简单点^_^
![image](https://cloud.githubusercontent.com/assets/6361237/18479393/c4fcd79a-7a0f-11e6-9183-8bdf276be88e.png)

![image](https://cloud.githubusercontent.com/assets/6361237/18479405/d31007ee-7a0f-11e6-83cd-9abd0143287e.png)

![image](https://cloud.githubusercontent.com/assets/6361237/18481423/18c305f0-7a17-11e6-98be-1b337d244530.png)

![image](https://cloud.githubusercontent.com/assets/6361237/18481604/afdc7ac0-7a17-11e6-97db-7162e0769b6e.png)

**Comment by yiminghe** [comment]
no，强类型

**Comment by miss61008596** [comment]
好的，我再研究下，谢谢
