### ISSUE TITLE
ListView 配合PullToRefresh 在企业微信环境中滑动显示错误

### ISSUE THREAD

**Issue by qqnp1100** [ant-design/ant-design-mobile#2536]
### Version
2.1.8

### Environment
企业微信2.4.18

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/pull-to-refresh?lang=zh-CN#pull-to-refresh-demo-0](https://mobile.ant.design/kitchen-sink/components/pull-to-refresh?lang=zh-CN#pull-to-refresh-demo-0)

### Steps to reproduce
就官网的例子

### What is expected?
正常显示

### What is actually happening?
滑动时顶部和底部不断抖动
![ezgif-1-6a94d264bc](https://user-images.githubusercontent.com/14014255/39904218-67119130-5509-11e8-8153-53389c44f444.gif)

---
在手机chrome浏览器、桌面chrome浏览器中均无问题，只在企业微信中打开会有问题

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
