### ISSUE TITLE
picker 选好下拉选项后值没有显示

### ISSUE THREAD

**Issue by Jessie-D** [ant-design/ant-design-mobile#254]
- antd-mobile 版本：
- 操作系统及其版本：win7,ios
- 浏览器及其版本：chrome,safari
   引入 antd-mobile 的 picker 
 期待的结果是： 
![picker](https://cloud.githubusercontent.com/assets/10069496/18498085/53b01e38-7a66-11e6-9539-a49ada6f4828.png)

  实际上的结果： 
![picker2](https://cloud.githubusercontent.com/assets/10069496/18498087/574282c0-7a66-11e6-9ae0-60e5f630f76b.png)

可重现的在线演示
官网：http://mobile.ant.design/components/picker/
重现步骤 
进入官网-picker组件，选择一个省市区

**Comment by warmhug** [comment]
closed #241
