### ISSUE TITLE
InputItem extra button unable to display properly

### ISSUE THREAD

**Issue by sp0cket** [ant-design/ant-design-mobile#2540]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
os:macOS 10.13.4; browser:chrome 67.0.3396.30/Safari 11.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6l30684zz3)

### Steps to reproduce
```
<InputItem
        extra={
          <Button type="primary" size="small">
            test
          </Button>
        }
      >
        test
 </InputItem>
```

### What is expected?
这个按钮应该与List.Item中的一样

### What is actually happening?
InputItem上的Button被遮挡一部分

---
业务场景：登录注册发送验证码按钮

**Comment by micooz** [comment]
自己覆盖一下下面的样式就可以了：

```css
.am-input-extra {
  max-height: 100%;
}
```

**Comment by duwei54** [comment]
@micooz 我在:global中用
.am-input-extra {
  max-height: 100%;
}
来进行覆盖,但是会被默认css重新覆盖掉呢

**Comment by duwei54** [comment]
@kennir 有点记不得了,应该是升级版本后解决了
