### ISSUE TITLE
PullToRefresh组件的damping props 还没放出来吗？我加上damping={120}还是可以无限往下滑

### ISSUE THREAD

**Issue by huangnan1994** [ant-design/ant-design-mobile#2542]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
PullToRefresh刷新组件可以限制有一个下拉的距离

### What does the proposed API look like?
PullToRefresh刷新组件可以限制有一个下拉的距离

**Comment by huangnan1994** [comment]
2.1.8版本

**Comment by huangnan1994** [comment]
我看了下，没有把这个api放上去，那么什么时候能放上去呢？

**Comment by warmhug** [comment]
2018-05-28

**Comment by huangnan1994** [comment]
嗯，好的谢谢

**Comment by huangnan1994** [comment]
今天没计划发版本吗？

**Comment by warmhug** [comment]
@huangnan1994  已经发了，看 changelog 、升级下试试再问！

**Comment by huangnan1994** [comment]
https://github.com/ant-design/ant-design-mobile/pull/2570/files   2.1.10 ，升级日志没有关于PullToRefresh的

**Comment by huangnan1994** [comment]
![image](https://user-images.githubusercontent.com/18899624/40640858-5d2f12d8-634a-11e8-8c47-1b9944fdaf43.png)

**Comment by huangnan1994** [comment]
![image](https://user-images.githubusercontent.com/18899624/40640870-672ae0b4-634a-11e8-9aad-63af999e335a.png)

**Comment by huangnan1994** [comment]
![image](https://user-images.githubusercontent.com/18899624/40640892-77465500-634a-11e8-9fcc-eb4faa7d3fbc.png)

**Comment by warmhug** [comment]
抱歉，已经修复了。

**Comment by huangnan1994** [comment]
![image](https://user-images.githubusercontent.com/18899624/40646097-d9fe9508-635a-11e8-89e0-5c09cb0ecbd1.png)
![image](https://user-images.githubusercontent.com/18899624/40646114-e1f908ba-635a-11e8-8aed-97503783dff0.png)
小米mix2s，iphone 8p ,谷歌浏览器，均无效果。

**Comment by warmhug** [comment]
十分抱歉，确实有 bug , @KgTong 正在修复中，修复好了，会再这里通知下。

**Comment by huangnan1994** [comment]
很佩服你们这种精神

**Comment by huangnan1994** [comment]
@KgTong @warmhug  只测一个(小米note2)就没效果，依然可以无限下拉，重装的是2.1.10版本。

**Comment by KgTong** [comment]
官网例子试下？https://mobile.ant.design/kitchen-sink/components/pull-to-refresh?lang=zh-CN#pull-to-refresh-demo-0

**Comment by KgTong** [comment]
依赖的`rmc-pull-to-refresh`, 看下是否为`1.0.9`版本

**Comment by huangnan1994** [comment]
1.0.8

**Comment by huangnan1994** [comment]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by KgTong** [comment]
需要升级到1.0.9，antd-mobile里面是通过`~`依赖的.

依赖都重新安装下吧

**Comment by huangnan1994** [comment]
我都是全部重新下的，但还是1.0.8，antd-mobile的依赖里面 "rmc-pull-to-refresh": "~1.0.1",不应该是装你恩1.0.x的最新版本吗？

**Comment by KgTong** [comment]
npm包更新不到，不是组件的问题，自行解决下？

**Comment by huangnan1994** [comment]
嗯，好的，谢谢
