### ISSUE TITLE
Tabs能不能自定义样式,  提供接口修改tabs所在的样式(Tabs can customize the style, provide interfaces to modify the styles of the tabs)

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design-mobile#2543]
Tabs能不能自定义样式,  提供接口修改tabs所在的样式，如下面所示样式，

 ![tabs样式更改](https://github.com/suwu150/static-resource/blob/master/images/tabs%E6%A0%B7%E5%BC%8F.png?raw=true)

请问怎么实现？谢谢🙏

---------
Tabs can customize the style, provide interfaces to modify the styles of the tabs, as shown below

 ![tabs样式更改](https://github.com/suwu150/static-resource/blob/master/images/tabs%E6%A0%B7%E5%BC%8F.png?raw=true)

How to achieve? Thank you very much  .

**Comment by suwu150** [comment]
能不能调整tabs的高度

**Comment by doxiaodong** [comment]
可覆盖默认样式，比如
```
.am-tabs-default-bar-tab {
  height: 100px;
}
```

**Comment by suwu150** [comment]
react-native中这个样式该往哪里放？有具体的入口吗？

**Comment by NiuYangYang** [comment]
这种功能我都是基于官方组件TouchableOpacity和ScrollView自己写的

**Comment by well-monkey** [comment]
@doxiaodong   不能覆盖样式吧。因为可能有一个项目里面有多个tabs
