### ISSUE TITLE
Carousel 的 props 与文档描述不一致

### ISSUE THREAD

**Issue by Darkbish** [ant-design/ant-design-mobile#2544]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
win10 chrome

### Reproduction link
[https://codepen.io/anon/pen/XqxPLo](https://codepen.io/anon/pen/XqxPLo)

### Steps to reproduce
这是 `antd-mobile` 的 `Carousel` 的类型定义

```
/// <reference types="react" />
import React, { CSSProperties } from 'react';
import { CarouselPropsType } from './PropsType';
export interface CarouselProps extends CarouselPropsType {
    className?: string;
    prefixCls?: string;
    beforeChange?: (from: number, to: number) => void;
    afterChange?: (current: number) => void;
    swipeSpeed?: number;
    easing?: () => void;
    style?: CSSProperties;
    dotStyle?: CSSProperties;
    dotActiveStyle?: CSSProperties;
}
```

这是 `rmc-nuka-carousel` 的 `Carousel` 的类型定义

```
export interface ICarouselProps {
    className?: string;
    style?: any;
    afterSlide?: (index: number) => void;
    autoplay?: boolean;
    resetAutoplay?: boolean;
    swipeSpeed?: number;
    autoplayInterval?: number;
    beforeSlide?: (currentIndex: number, endIndex: number) => void;
    cellAlign?: 'left' | 'center' | 'right';
    cellSpacing?: number;
    data?: () => void;
    decorators?: any[];
    dragging?: boolean;
    easing?: Function;
    edgeEasing?: Function;
    framePadding?: string;
    frameOverflow?: string;
    initialSlideHeight?: number;
    initialSlideWidth?: number;
    slideIndex?: number;
    slidesToShow?: number;
    slidesToScroll?: number | 'auto';
    slideWidth?: string | number;
    speed?: number;
    swiping?: boolean;
    vertical?: boolean;
    width?: string;
    wrapAround?: boolean;
}
```

`rmc-nuka-carousel` 是有 `cellSpacing` 等 `antd-mobile` 中 `Carousel` 定义的 `webOnly` 的 `props`，但是 `antd-mobile` 却没有定义，这是忘了还是不支持了，如果不支持，请更新下文档。

### What is expected?
`Carousel` 的 `d.ts` 包含 `cellSpacing` 等 `webOnly` 的属性。

### What is actually happening?
`Carousel` 的 `d.ts` 不包含 `cellSpaing` 等 `webOnly` 的属性。

**Comment by aqnaruto** [comment]
而且根本不支持垂直
牛头不对马嘴
我真无语了
https://mobile.ant.design/components/carousel-cn/#components-carousel-demo-vertical
这上面写的好清楚支持垂直

**Comment by ccys** [comment]
frameOverflow  cellSpacing  slideWidth
三个示例中的属性都不存在，版本2.2.3

**Comment by sikaco** [comment]
@doxiaodong long time no see.

所以这个问题有结论么
