### ISSUE TITLE
当data数组很大时，Picker组件弹出很慢

### ISSUE THREAD

**Issue by starzou** [ant-design/ant-design-mobile#2546]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
渲染一个超大的地区数组，动态生成

### What does the proposed API look like?
添加一个async属性，控制元素的动态生成

```javascript
<Picker data={data} value={value} async={true}>
    <List.Item arrow="horizontal">选择城市</List.Item>
</Picker>
```

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
