### ISSUE TITLE
InputItem能不能提供自定义光标颜色的接口，以及选中文字时文字和背景的颜色的接口

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design-mobile#2547]
InputItem能不能提供自定义光标颜色的接口，以及选中文字时文字和背景的颜色的接口

**Comment by yaoyuande** [comment]
请问，你的InputItem 报警告吗

Excuse me, is your InputItem newspaper warning

Unknown event handler property onExtraClick. It will be ignored.
Unknown event handler property onErrorClick. It will be ignored.
Unknown event handler property onVirtualKeyboardConfirm. It will be ignored.

**Comment by warmhug** [comment]
自己覆盖样式吧

**Comment by suwu150** [comment]
没有用过onExtraClick，onErrorClick，onVirtualKeyboardConfirm方法，没有报你说的这种警告

**Comment by yaoyuande** [comment]
@suwu150 我也没用那些方法，也没写那些方法，但是就是出警告了，你用的哪个版本，竟然没出警告

**Comment by suwu150** [comment]
@yaoyuande  "antd-mobile": "^2.1.8",

**Comment by yaoyuande** [comment]
<List>
            <InputItem
              clear
              placeholder="请输入口令"
              onChange={this.onKlChange}
              className="form_input_item"
            >
              <div className='icon_kl'></div>
            </InputItem>
            <InputItem
              clear
              type="phone"
              placeholder="请输入手机号"
              error={this.state.hasError}
              onErrorClick={this.onErrorClick}
              onChange={this.onChange}
              value={this.state.value}
              className="form_input_item form_input_item_margin"
            >
              <div className='icon_tel'></div>
            </InputItem>
            <Flex>
              <InputItem
                clear
                placeholder="请输入验证码"
                onChange={this.onCodeChange}
                value={this.state.codeValue}
                className="form_input_item form_input_item_border"
              >
                <div className='icon_code'></div>
              </InputItem>
              {/* <div className='get_code' onClick={this.codeClick}>{this.state.codeWord}</div> */}
              <Button className='get_code' onClick={this.codeClick} disabled={this.state.codeStatus}>{this.state.codeWord}</Button>
            </Flex>
          </List>

和你代码 类似吗？

**Comment by suwu150** [comment]
```
      <List
        renderHeader={renderHeader}
      >
        <InputItem
          {...this.props}
          style={[{ width: '100%' }, style]}
          value={this.state.value}
          placeholder={name}
          extra={suffix}
        />
      </List>
```
这样的一端

**Comment by yaoyuande** [comment]
可以提供一个链接吗？

**Comment by suwu150** [comment]
@yaoyuande 提供什么链接
