### ISSUE TITLE
rmc-date-picker中有itemStyle这个属性，为什么到date-picker中就没有itemStyle属性？

### ISSUE THREAD

**Issue by wangzhenggui** [ant-design/ant-design-mobile#2548]
![default](https://user-images.githubusercontent.com/26643553/40228090-e15a2a38-5ac2-11e8-8877-62bb895e923e.png)
ant-design-mobile 为什么没有这个接口开放
![default](https://user-images.githubusercontent.com/26643553/40228130-fe0aac34-5ac2-11e8-8f90-dc8d89e8d123.png)

**Comment by doxiaodong** [comment]
以 `antd-mobile` 为准，你对这个有什么样的需求么？
