### ISSUE TITLE
关于TabBar的hidden属性设计实现

### ISSUE THREAD

**Issue by xautlx** [ant-design/ant-design-mobile#2549]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
MacOS，Chrome

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/tab-bar](https://mobile.ant.design/kitchen-sink/components/tab-bar)

### Steps to reproduce
先点击"Click to switch fullscreen"切换全屏显示，再点击“Click to show/hide tab-bar”切换底部TabBar显示隐藏。
用Chrome开发者工具可以看到TabBar区域DOM .am-tab-bar-bar元素动态的添加或移除了.am-tab-bar-bar-hidden控制类，来实现TabBar的显示隐藏。
但是其父元素.am-tabs-tab-bar-wrap固定高度并且一直显示，导致TabBar区域的相关按钮虽然隐藏了，但是实际上内容区域还是被.am-tabs-tab-bar-wrap这个区域遮挡，好像并没有完整意义的实现TabBar的整体hidden

### What is expected?
TabBar包括.am-tabs-tab-bar-wrap整体隐藏，以便内容区域完整显示

### What is actually happening?
内容区域被.am-tabs-tab-bar-wrap遮挡

**Comment by doxiaodong** [comment]
fixed by https://github.com/ant-design/ant-design-mobile/pull/2564
