### ISSUE TITLE
Tabs 组件在IOS9 越狱的手机端不加载 tab 下的数据

### ISSUE THREAD

**Issue by luoandy** [ant-design/ant-design-mobile#2552]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
ios9.*

### Reproduction link
[http://h.test.ucuxin.com/CZComprehensive/analysis](http://h.test.ucuxin.com/CZComprehensive/analysis)

### Steps to reproduce
直接访问和在浏览器Safari  都不能访问

### What is expected?
能够加载数据

### What is actually happening?
不能加载数据,显示为空

**Comment by warmhug** [comment]
确认只在 iOS9 上有问题？其他系统没问题吧？

**Comment by 1427818207** [comment]
不是越狱的问题，是顶层tabs标签的display：flex不需要，害死我了

**Comment by ziluo** [comment]
ref: https://github.com/ant-design/ant-design-mobile/issues/2569
