### ISSUE TITLE
SearchBar能不能提供自定义取消文字样式和搜索框里边文字的样式

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design-mobile#2553]
SearchBar能不能提供自定义取消文字样式和搜索框里边文字的样式，最近的项目里边需要进行修改文字的颜色和大小，包括取消文字的样式，请问能不能提供修改的接口

**Comment by warmhug** [comment]
样式方面不方便提供 API，请自己 css 覆盖样式。

**Comment by HowkeWayne** [comment]
请问如何修改
![image](https://user-images.githubusercontent.com/18286445/61166341-41be2500-a55e-11e9-8de7-d115417412cb.png)这个灰底色
