### ISSUE TITLE
2.1.x final version plan

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#2556]
Before the end of May(Most likely it is on May 28), we will release the last version of `2.1.x` and **add a hint of big break change about the antd-mobile’s React Native version.**

After careful consideration. We decide to give up **official support** for react native version in  `antd-mobile@2.2.0` and will separate it into a  library called [antd-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn). Of course, don’t worry, we will try our best to fix all existing RN issues(they are labeled by `type: react native`). Subsequently, we really hope it is maintained by the community classmates 🤝🙏.

- [x] fix all RN issues (not include feature)
    - The feature request issues will be moved [antd-mobile-rn issues](https://github.com/ant-design/ant-design-mobile-rn/issues)

Here are some of the web version issues we need to solve:

#2555 
#2529

**Comment by quentinyang** [comment]
#2321 
#2285 
#2177 
#1954

**Comment by Manweill** [comment]
antd-mobile-rn这个名字感觉不怎样啊，antd-mobile-native怎样 @warmhug

**Comment by doxiaodong** [comment]
[ ] https://github.com/ant-design/ant-design-mobile/issues/2387
[ ] https://github.com/ant-design/ant-design-mobile/issues/2468
[ ] https://github.com/ant-design/ant-design-mobile/issues/2350

feat:
[ ] https://github.com/ant-design/ant-design-mobile/issues/2161
[ ] https://github.com/ant-design/ant-design-mobile/issues/2150
[ ] https://github.com/ant-design/ant-design-mobile/issues/2114
[ ] https://github.com/ant-design/ant-design-mobile/issues/2163

**Comment by likezero** [comment]
- [ ] #1974
- [x] #2498
- [x] #2434
- [x] #2320
- [x] #2414
- [x ] #2261
- [x] #2496
- [x] #2488
- [x] #2486
- [x] #2477
- [x] #2465
- [x] #2432
- [x] #2428
- [x] #8888
- [x] #8888
- [x] #8888

**Comment by warmhug** [comment]
@Manweill rn这个名字不怎么好听，但 native 指代的有些广泛也不太好吧。因为这个代码确实是专门给 RN 平台用的。

**Comment by quentinyang** [comment]
antd-mobile-rn计划什么时候开始？加我一个。

**Comment by Manweill** [comment]
或者让社区提交几个名字，然后投票，很难接受-rn这个后缀

**Comment by warmhug** [comment]
@gengjiawen WIP

**Comment by Manweill** [comment]
@warmhug  ant-react-native 如何？

**Comment by KurobaZhang** [comment]
切成两个包的话 那API还会统一吗？

**Comment by gengjiawen** [comment]
Any news for the new repo since this repo already remove the react native code ?

**Comment by takfate** [comment]
6月19日是什么鬼

**Comment by aqnaruto** [comment]
不知道大脑怎么想的，换成两个不就是远离初衷了么，而且rn 组件怎么看预览。是不是组件换人维护了？招的毕业生？

**Comment by gun321654** [comment]
没错的吧，web和rn本身就差距比较多，rn的初衷是好的，但是api能否统一关键在rn和web，antd只负责ui

**Comment by aqnaruto** [comment]
这有什么不同的，像人家rn官网  后缀加个 ios only ，android only，antd 文档也是一样，可以加web only ，rn only，为什么要分开呢 都不能预览效果了。现在换成应届生维护了么

**Comment by aqnaruto** [comment]
先不说抢上ts 导致改动 困难了，为毛写清楚一个文档这么费劲
