### ISSUE TITLE
antui-dialog 弹出框阴影部分使用的是position: absolute; 如果页面内容高度超过一屏幕，阴影部分是盖不住的

### ISSUE THREAD

**Issue by sm0210** [ant-design/ant-design-mobile#2561]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.9

### Environment
chrom

### Reproduction link
[https://antui.alipay.com/10.1.10/index.html#Dialog%20%E5%AF%B9%E8%AF%9D%E6%A1%86](https://antui.alipay.com/10.1.10/index.html#Dialog%20%E5%AF%B9%E8%AF%9D%E6%A1%86)

### Steps to reproduce
内容高度超过一屏幕，弹出antui-dialog ，发现超过一屏幕高度的内容，弹出框的阴影是盖不住的

### What is expected?
完全盖住内容区域

### What is actually happening?
弹出框的阴影是盖不住的

![image](https://user-images.githubusercontent.com/10410886/40346249-ce52a852-5dce-11e8-8576-861f9e882388.png)

**Comment by warmhug** [comment]
antui 的代码不是在这里，请提 issue 给他们文档上写的负责人。

**Comment by sm0210** [comment]
http://gitlab.alibaba-inc.com/antui/amui/issues

给得isuses 连接都打不开了。。。。。。

**Comment by warmhug** [comment]
antui不是对外的，建议直接使用 antd-mobile
