### ISSUE TITLE
InputItem  Unknown event handler property `onExtraClick`. It will be ignored.

### ISSUE THREAD

**Issue by yaoyuande** [ant-design/ant-design-mobile#2565]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.9

### Environment
win10 chrome

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile](http://new-issue.ant.design/?repo=ant-design-mobile)

### Steps to reproduce
  handleClick = () => {
    this.customFocusInst.focus();
  }
  render() {
    const { login, loading } = this.props;
    // const { getFieldProps } = this.props.form;

    return (
      <div className={styles.box}>
        <h3 className={styles.title}>图片直播品控</h3>
        <div className={styles.form}>
          <List renderHeader={() => 'Customize to focus'}>
            <InputItem
              clear
              placeholder="auto focus"
              ref={el => this.autoFocusInst = el}
            >标题</InputItem>
            <InputItem
              clear
              placeholder="click the button below to focus"
              ref={el => this.customFocusInst = el}
            >标题</InputItem>
            <List.Item>
              <div
                style={{ width: '100%', color: '#108ee9', textAlign: 'center' }}
                onClick={this.handleClick}
              >
                click to focus
              </div>
            </List.Item>
          </List>
        </div>
      </div>
    );
  }

运行后提示：
Unknown event handler property `onExtraClick`. It will be ignored.
Unknown event handler property `onErrorClick`. It will be ignored.
Unknown event handler property `onVirtualKeyboardConfirm`. It will be ignored.

### What is expected?
期望别报错

### What is actually happening?
运行后提示：
Unknown event handler property `onExtraClick`. It will be ignored.
Unknown event handler property `onErrorClick`. It will be ignored.
Unknown event handler property `onVirtualKeyboardConfirm`. It will be ignored.

**Comment by yaoyuande** [comment]
指定 type为 money 就没有下边的警告了，有别的解决方法吗？

**Comment by qiuziz** [comment]
这个问题怎么解决啊@warmhug

**Comment by zhangshuaidan** [comment]
I met the same problem, but I reinstall my node_modules just now ,the problems still here, what should I   do? @KgTong @warmhug @yaoyuande 
`index.js:2177 Warning: Unknown event handler property `onExtraClick`. It will be ignored.
    in input (created by Input)
    in Input (created by InputItem)
    in div (created by InputItem)
    in div (created by InputItem)
    in div (created by InputItem)
    in InputItem (at login.jsx:46)
    in div (created by List)
    in div (created by List)
    in List (at login.jsx:44)
    in div (created by WingBlank)
    in WingBlank (at login.jsx:43)
    in div (at login.jsx:38)
    in Login (created by Connect(Login))
    in Connect(Login) (created by Route)
    in Route (at index.js:39)
    in Switch (at index.js:36)
    in div (at index.js:34)
    in Router (created by BrowserRouter)
    in BrowserRouter (at index.js:33)
    in Provider (at index.js:32)`

**Comment by KgTong** [comment]
We have fixed this problem, and will release a new version in the end of this month

**Comment by yaoyuande** [comment]
@KgTong This problem still recure in 2.1.10

**Comment by KgTong** [comment]
not release yet

**Comment by Meyond** [comment]
InputItem onChange  triggers the next element onClcik
