### ISSUE TITLE
Icon 本地资源报错  Icon local resource error

### ISSUE THREAD

**Issue by yaoyuande** [ant-design/ant-design-mobile#2567]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.9

### Environment
win10 chrome

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/issues/](https://github.com/ant-design/ant-design-mobile/issues/)

### Steps to reproduce
const CustomIcon = ({ type, className = '', size = 'md', ...restProps }) => (
      <svg
        className={`am-icon am-icon-${type.substr(12)} am-icon-${size} ${className}`}
        {...restProps}
      >
        <use xlinkHref={type} /> {/* svg-sprite-loader@0.3.x */}
        {/* <use xlinkHref={#${type.default.id}} /> */} {/* svg-sprite-loader@latest */}
      </svg>
    );

<CustomIcon key="0" type={require('../../icons/logo.svg')} />

"svg-sprite-loader": "^3.7.3"

//error info
index.js:60 Uncaught TypeError: type.substr is not a function

### What is expected?
加载出本地svg资源

### What is actually happening?
//error info
index.js:60 Uncaught TypeError: type.substr is not a function

**Comment by ilaipi** [comment]
希望官方能改改这块升级指南。。一点都不够指南。。    

### 首先要确保`webpack`配置中有对`svg`配置`svg-sprite-loader`，并且确认版本，不同的版本在代码中使用方式不同：

```
- import { Icon } from 'antd-mobile';
- <Icon type={require('./foo.svg')} />

+ const CustomIcon = ({ type, className = '', size = 'md', ...restProps }) => (
+     <svg
+       className={`am-icon am-icon-${type.substr(1)} am-icon-${size} ${className}`}
+       {...restProps}
+     >
+       <use xlinkHref={type} /> {/* svg-sprite-loader@0.3.x */}
+       {/* <use xlinkHref={#${type.default.id}} /> */} {/* svg-sprite-loader@latest */}
+     </svg>
+ );
+ <CustomIcon type={require('./foo.svg')} />
```

改为：
```
- import { Icon } from 'antd-mobile';
- <Icon type={require('./foo.svg')} />

+ const CustomIcon = ({ type, className = '', size = 'md', ...restProps }) => (
+     <svg
+       className={`am-icon am-icon-${size} ${className}`}
+       {...restProps}
+     >
+       <use xlinkHref={type} /> {/* svg-sprite-loader@0.3.x */}
+       {/* <use xlinkHref={&#96;#${type.default.id}&#96;} /> */} {/* svg-sprite-loader@latest */}
+     </svg>
+ );
+ <CustomIcon type={require('./foo.svg')} />
```

### Tips：
1，`className=`去掉`am-icon-${type.substr(1)}`
2，使用`svg-sprite-loader@latest`(最新版)时，`xlinkHref`的值`{}`内需要`` ` ``符号，即`` <use xlinkHref={`#${type.default.id}`} /> ``
