### ISSUE TITLE
tabs下面的内容在ios10显示不出来

### ISSUE THREAD

**Issue by 1427818207** [ant-design/ant-design-mobile#2569]

**Comment by 1427818207** [comment]
？？

**Comment by 1427818207** [comment]
am-tabs-content-wrap 高度撑不起来，永远为0

**Comment by ziluo** [comment]
最好给个Demo，方便定位问题，也可以参考下官方实例：https://mobile.ant.design/components/tabs-cn/

**Comment by 1427818207** [comment]
demo我没地方放，我基本描述一下吧，就是你们把.tabs的display为flex了，然后它的子元素.am-tabs-content-wrap也flex了，这样就导致了在ios10上面.am-tabs-content-wrap里的内容高度为0，安卓和高版本ios是没事的，我把tabs的display恢复成block，问题就解决了，但为什么两层flex的嵌套会出现兼容问题这个根本原因还是没想清楚，希望你们能测一下，也告诉一下我

**Comment by ziluo** [comment]
@1427818207 你的Demo文件发错了吧，代码里面没找任何Tabs、flex的代码，另外Demo放到https://codepen.io/ 上吧
