### ISSUE TITLE
List api 调整

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#257]
http://facebook.github.io/react-native/docs/listview.html

- 去除 List.Body List.Footer List.Header
- title footer 改为 renderFooter renderHeader

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/issues/63#issue-170363531

直接 `title={<div></div} footer={<div></div>}` 吧，renderHeader 意义不大，因为函数没有传参。

**Comment by yiminghe** [comment]
同 ListView 保持一致

**Comment by pingan1927** [comment]
这个我认可修改，原先的`title`也会保留，`1.0`上

**Comment by yiminghe** [comment]
title 不保留的， 1.0 不考虑兼容以前

**Comment by pingan1927** [comment]
那又得再升一遍了。。 大悲剧啊！

**Comment by pingan1927** [comment]
尝试修改，感觉`renderFooter`、`renderHeader`、`title`、`footer`都没有`List.Footer`、`List.Header`来的实在好用。要定制样式，要套好多层，不能直接传入`style`，要添加`onClick`，都需要自己再封装一个`div`标签，
何必呢？

**Comment by susan-github** [comment]
虽然之前用title属性的时候，发现了它不可扩展这点不太友好，但是把List.Body List.Footer List.Header这些全部去掉了，实在是。。。。要升级的话，不是要改好多
