### ISSUE TITLE
ios中Button按钮在某些宽度情况下，右边框缺失

### ISSUE THREAD

**Issue by jackyr** [ant-design/ant-design-mobile#2574]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.10

### Environment
iphone8，safari

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/button?lang=zh-CN#button-demo-0](https://mobile.ant.design/kitchen-sink/components/button?lang=zh-CN#button-demo-0)

### Steps to reproduce
重现链接在iphone8（用simulator也可）的safari中打开，底部倒数第二个Regional manager右侧的Button按钮（type=ghost的那个），将按钮文案small改为111，即可重现

### What is expected?
右侧有边框

### What is actually happening?
右侧边框缺失

---
感觉是ios中浏览器的css精度处理问题，有什么好的解决方案？

**Comment by warmhug** [comment]
iOS 渲染问题，是已知问题，组件层面、无法彻底解决。
