### ISSUE TITLE
<PullToRefresh/> 在tab切换时使用、direction  up，切换后，按着屏幕一直往上拉中间不松手，第一次触发不了onRefresh.

### ISSUE THREAD

**Issue by wangxiaotian** [ant-design/ant-design-mobile#2575]
### Version
2.1.2

### Environment
Pc chrome, Mobile - Android & IOS

### Steps to reproduce

````
      <PullToRefresh
          className={css.list}
          ref={el => this.ptr = el}
          style={{
            overflow: 'auto',
          }}
          direction={direction}
          refreshing={refreshing}
          onRefresh={this.refresh}
          distanceToRefresh={30}
        >
````
- 背景：PullToRefresh 组件结合Tab切换（非and-mobiel）,每次tab切换组件用异步获取数据，拿到data后setState({ data })，

- 操作：由tab A 切换到tab B，手指按住页面不松手，一直滑到底部，`不会触发onRefresh`，底部提示完成，然后组件reset。此过程中如果中间分多次滑动，滑到页面底部时可以触发。

- 信息：中间会遇到`event.preventDefault()`的`warning`:   `Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted`

### What is expected?

每次tab切换，手指按住页面不松手向下滑动到页面底部`触发onRefresh`

### What is actually happening?

每次tab切换，手指按住页面不松手向下滑动到页面底部`没有触发onRefresh`

**Comment by davychan1985** [comment]
这个问题一直存在 @warmhug @KgTong  @doxiaodong

**Comment by YijiangWang** [comment]
我也遇到这问题，切换Tab，上拉然后不能刷新，通过改变Tab高度解决了这个问题

**Comment by YijiangWang** [comment]
我遇到的问题是：Android 上拉到内容底部时，再向上滑动不能触发 onrefresh；iOS 一切正常。解决方案：给顶部 tab 添加一个属性 ‘**box-sizing: border-box;**’，这样就可以触发 onrefresh 了。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
