### ISSUE TITLE
有人能解释一下为什么所有的控件源码都是那么大？这样做的目的是？

### ISSUE THREAD

**Issue by aqnaruto** [ant-design/ant-design-mobile#2578]
一个button两百多行
一个stepper几百行，在项目中我需要在stepper上稍微修改一下样式，看了源码半天都找不到，为什么几十行能解决的事情，搞的这么大一坨，这样还不如自己封装了。
而且我搜索<text 完全搜不到，根本找不到render的入口？
有大神能解释下吗

**Comment by warmhug** [comment]
因为要实现功能！欢迎有意义的吐槽和建议！

**Comment by aqnaruto** [comment]
谢谢，不好意思，那天我是找了好久的ts编译后的文件。找了很久，我想说的有意义的吐槽是 ，npm安装后 为什么不把ts编译前的 源文件也集成进去，这样便于用户修改 和自定义新样式和拓展。顺便写个简要说明 怎么编译 。

**Comment by warmhug** [comment]
npm 里不适合放 源文件、GitHub 上有其他仓库这么做吗。
仔细看看网站和仓库里各种文档吧！

**Comment by aqnaruto** [comment]
好吧，谢谢。其实一般，公司都会有自己的样式需求，一般慧改动一些样式和细微调整一下功能。话说antd-admin这个小ui框架其实不需要用ts，除非有很多的继承关系 代码量上万行了 才有用ts发挥静态类型的价值。这样做的副作用是 我想改一下样式我得自己去啃ts编译后的，要么去下源码重新编译，而官网并不是把所有源码都放进去了，比如stepper和pagination调用的一个组件，那个组件就在github源码上没有。这样就比较麻烦，如果是js 我大概十分钟就能解决，这样一搞 我可能需要半小时或者更长。
