### ISSUE TITLE
react-native 中 modal 不可以连续调用？

### ISSUE THREAD

**Issue by wanxsb** [ant-design/ant-design-mobile#2579]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.10

### Environment
react-native 0.55.4

ios

### Reproduction link
[https://github.com/wanxsb/bug-demo](https://github.com/wanxsb/bug-demo)

### Steps to reproduce
````
Modal.prompt('填写要绑定的手机号', null, (mobile) => { 
      console.log('going to bind mobile '   mobile);
      Modal.alert('确认绑定手机号', '绑定后不可更改', [
        {text: '取消', onPress: () => console.log('cancel')},
        {text: '立即绑定', onPress: () => console.log(`binded mobile ${mobile}`)}
      ]);
    }, 'default', '', ['手机号']);
````
### What is expected?
期望的结果是弹出输入手机号的提示框并确定后，弹出确认框

### What is actually happening?
确认框无法弹出，貌似被第一个提示框的一块给关闭了

---
类似Modal类连续调用时，后续的modal被第一个modal连带关闭的情况，一直出现。不仅仅是prompt, alert

**Comment by wanxsb** [comment]
同时原文说：

````
Modal.prompt(title, message, callbackOrActions, type?, defaultValue?, placeholders?, platform?).close() 可以在外部关闭 prompt`
````

实际情况是Modal.prompt返回的undefined

react-native 0.55.4

**Comment by warmhug** [comment]
cc @silentcloud 确实有问题

**Comment by silentcloud** [comment]
rn-topview 目前只能支持同时设置一个 view，Modal.alert 和 Modal.prompt 是 2 个 view

**Comment by warmhug** [comment]
Trace https://github.com/ant-design/ant-design-mobile-rn/issues/14
Close for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452
