### ISSUE TITLE
React Native Calendar 无法使用, 报错信息无法识别 div !  Invariant Violation: View config not found for name div.

### ISSUE THREAD

**Issue by NiuYangYang** [ant-design/ant-design-mobile#2580]
![111](https://user-images.githubusercontent.com/19486884/40533063-1365bc38-6034-11e8-9a1a-2e1ce083b32c.png)

**Comment by aqnaruto** [comment]
issue主能交流下吗我想改下组件，苦于源码里找不到render的入口。都是用ts写的完全不知道哪里引入的reactnative组件

**Comment by aqnaruto** [comment]
RMCInputNumber  github上的源码和自己安装后的 完全不一样 安装后的是编译后的，自己要改 还得重新编译不成？？

**Comment by warmhug** [comment]
Use `babel-plugin-import`.

**Comment by NiuYangYang** [comment]
@warmhug 我运行过 npm install babel-plugin-import --save-dev , 没啥用

**Comment by NiuYangYang** [comment]
@aqnaruto 公司想用, 但很多控件都报错div, 无奈啊

**Comment by NiuYangYang** [comment]
发现问题了, Mobile Ant Design 很多组件都是web专用的, 弃坑了0.0

**Comment by warmhug** [comment]
欢迎使用 web 版，大多是支持 RN 的，另外 Ref https://github.com/ant-design/ant-design-mobile/issues/2556 即将拆出单独的 RN 仓库，欢迎随后使用。
