### ISSUE TITLE
Picker 自定义输入行点击不起作用

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design-mobile#2581]
我在Picker中自定义了输入行，如下所示代码：
```
const CustomChildren = props => (
  <TouchableOpacity
    onPress={props.onClick}
    onClick={props.onPress}
    style={{
      backgroundColor: '#fff',
      paddingLeft: 15,
      justifyContent: 'center',
      alignItems: 'center',
      height: 36,
      lineHeight: 36,
    }}
  >
    <View
      style={{
        height: 36,
        flexDirection: 'row',
      }}
    >
      <Text
        style={{
          flex: 1, overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
          justifyContent: 'center',
          alignItems: 'center'
        }}
      >{props.children}
      </Text>
      <Text style={{ textAlign: 'right', color: '#888', marginRight: 15 }}>{props.extra}</Text>
    </View>
  </TouchableOpacity>
);
```
效果如下所示，但是点击时不起作用
![ant-design-mobile-picker-customer.png](https://github.com/suwu150/static-resource/blob/master/images/ant-design-mobile-picker-customer.png?raw=true)

希望官方能够对于自定义输入框的给出完整的说明文档，顺便帮我看看我这个事哪里出问题了，我点击的时候也不会弹出选择项

我的 Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.3.0
  Yarn: Not Found
  npm: 5.3.0
  Watchman: Not Found
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.0.0 => 16.3.2
  react-native: ^0.51.0 => 0.51.1

**Comment by yuzhiyi** [comment]
最近刚好遇到了这个问题，研究了一下源码，正好可以回答你这个问题．

在 Picker/AbstractPicker 中 triggerType 默认值是 'onClick'，在 rmc-picker/PopupMixin 中

```
newChildProps[props.triggerType!] = this.onTriggerClick

{React.cloneElement(child as any, newChildProps)}

onTriggerClick = (e) => {
      const child: any = this.props.children;
      const childProps = child.props || {};
      if (childProps[this.props.triggerType!]) {
        childProps[this.props.triggerType!](e);
      }
      this.fireVisibleChange(!this.state.visible);
}
```

就是说把 child 上 triggerType 所代表 prop 设置成 onTriggerClick 方法，而 onTriggerClick 里有变更状态Picker 的操作，因为 triggerType 默认值是 'onClick'，所以只能在手机 web 有效，而 rn TouchableOpacity 没有 onClick 这个 props，只有 onPress，所以会出现自定义输入行点击不起作用的问题．

同样 DatePicker 也存在同样的问题，而且特别奇怪的是在 date-picker/index.native 下，为什么 triggerType 默认值是 ' onClick'，而不是 'onPress'.

##解决办法：

如果你的代码只需要兼容 android ios 两个平台，那只需要将 Picker 的 triggerType prop 设置成 'onPress'．
```
<Picker
     triggerType={'onPress'}>
</Picker>
```

如果你的代码同时还需要兼容 web  平台，那需要判断一下平台．
```
<Picker
     triggerType={Platform.OS === 'web' ? 'onClick' : 'onPress'}>
</Picker>
```
同时得保证在 web 平台下的 TouchableOpacity.web 支持 onClick 这个 prop. 
我们这边目前三方跨平台，web 端使用的是 react-web，所以还得在 TouchableOpacity.web 增加一个 onClick 的 prop.
```
render() {

    return (
     <Animated.View
        onClick={this.props.onClick}>
        {this.props.children}
      </Animated.View>
    );
}
```

**Comment by yuzhiyi** [comment]
最近刚好遇到了这个问题，研究了一下源码，正好可以回答你这个问题．

在 Picker/AbstractPicker 中 triggerType 默认值是 'onClick'，在 rmc-picker/PopupMixin 中

```
newChildProps[props.triggerType!] = this.onTriggerClick

{React.cloneElement(child as any, newChildProps)}

onTriggerClick = (e) => {
      const child: any = this.props.children;
      const childProps = child.props || {};
      if (childProps[this.props.triggerType!]) {
        childProps[this.props.triggerType!](e);
      }
      this.fireVisibleChange(!this.state.visible);
}
```

就是说把 child 上 triggerType 所代表 prop 设置成 onTriggerClick 方法，而 onTriggerClick 里有变更状态Picker 的操作，因为 triggerType 默认值是 'onClick'，而 rn TouchableOpacity 没有 onClick 这个 props，只有 onPress，所以会出现自定义输入行点击不起作用的问题．

同样 DatePicker 也存在同样的问题，而且特别奇怪的是在 date-picker/index.native 下，为什么 triggerType 默认值是 ' onClick'，而不是 'onPress'.

##解决办法：

只需要将 Picker 的 triggerType prop 设置成 'onPress'．
```
<Picker
     triggerType={'onPress'}>
</Picker>
```

**Comment by warmhug** [comment]
Just delete `onClick={props.onPress}`
