### ISSUE TITLE
【 iOS 】TextareaItem component setting autoHeihgt attribute top and bottom padding invalidation

### ISSUE THREAD

**Issue by caoleic** [ant-design/ant-design-mobile#2582]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.7

### Environment
react-native: 0.55.2    iOS: iPhoneX

### Reproduction link
[https://github.com](https://github.com)

### Steps to reproduce
```
import { TextareaItem } from 'antd-mobile';

<TextareaItem
  autoHeight
  onChange={value => this.setState({ text: value })}
  value={this.state.text}
/>
```

### What is expected?
have top and bottom padding.

### What is actually happening?
top and bottom padding invalidation.

**Comment by warmhug** [comment]
It works correctly.
