### ISSUE TITLE
when the page is loaded for the first time, the drawer will flash then receive back

### ISSUE THREAD

**Issue by panjiefeng** [ant-design/ant-design-mobile#2585]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.10

### Environment
- OS: win10(64) 
- Broswer:63.0.3239.84（正式版本） （32 位） 
- react-native:^0.55.3 react: ^15.3.2  or react-native:^0.55.4 react: ^16.4.0

### Reproduction link
[https://github.com/panjiefeng/Reproduce-Bugs/tree/master/antd-mobile-test](https://github.com/panjiefeng/Reproduce-Bugs/tree/master/antd-mobile-test)

### Steps to reproduce
1. run 'npm start' command to run project
2. view in broswer with 'localhost:3000'
3. drawer demo will be shown, the drawer will flash and then receive back
but this can't reproduce in the Code Pen.

### What is expected?
when the page is loaded, the drawer should not flash

### What is actually happening?
the drawer flash anyway.

**Comment by harry91** [comment]
I meet the same problem.

**Comment by likezero** [comment]
react native吗

**Comment by harry91** [comment]
> react native吗

no, it's web version

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
