### ISSUE TITLE
模态框滑动出现穿透现象

### ISSUE THREAD

**Issue by 0625jing** [ant-design/ant-design-mobile#2587]

**Comment by Jmingzi** [comment]
I also encountered this problem, the modal component in your own demo, you can try it

**Comment by daqi** [comment]
```
body[style*='hidden'] {
  position: fixed;
}
```

**Comment by daqi** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1947#issuecomment-395382438

**Comment by LiLixikun** [comment]
I also met

**Comment by likezero** [comment]
please see #1947
