### ISSUE TITLE
Tab组件与listView组件组合使用后，在部分浏览器下无法上下滑动，怀疑是rc-gesture升级导致

### ISSUE THREAD

**Issue by amibug** [ant-design/ant-design-mobile#2589]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
safari IOS 10.1

### Reproduction link
[https://mobile.ant.design/components/tab-bar-cn/#components-tab-bar-demo-listview-tabbar](https://mobile.ant.design/components/tab-bar-cn/#components-tab-bar-demo-listview-tabbar)

### Steps to reproduce
antd-mobile依赖版本为2.1.8， 在一个需求迭代后，线上重新npm  install之后发现tab panel容器中无法上下滑动。
本地重新npm install后重现问题，发现rc-gesture版本最近有升级，目前是0.0.18. 切回0.0.15版本之后就没有问题

### What is expected?
tab panel容器中无法上下滑动

### What is actually happening?
tab panel容器中可以上下滑动。

**Comment by warmhug** [comment]
> 部分浏览器下
具体是指哪一部分，哪些浏览器没问题？

**Comment by quentinyang** [comment]
@amibug 刚试了本地和线上demo，这个是可用的。能否具体一下哪个及其或者浏览器不能用？可以帮助我们快速重现。
谢谢。

**Comment by amibug** [comment]
@quentinyang iPhone 6s safari、 华为P20 自带浏览器、 iPhone X UC浏览器

**Comment by quentinyang** [comment]
rc-gesture已经做了回滚，去掉了preventDefault的处理，发布了v0.0.19版本。你们业务可以再验证下。
谢谢你的反馈。

**Comment by JR0613** [comment]
Tabs组件与listView组件组合使用后,在苹果手机上下来之后往上滑动,tab会被卡住,呗listview遮挡
