### ISSUE TITLE
webpack4中按需加载样式不生效

### ISSUE THREAD

**Issue by wuhaohuang** [ant-design/ant-design-mobile#2595]
项目原本是使用 webpack2 打包没有任何问题，升级 webpack4 之后能跑起来，但是antd-mobile 的样式没有生效。

**Comment by wuhaohuang** [comment]
已经找到问题了

**Comment by MillionQW** [comment]
@wuhaohuang 请问是哪里出了问题呢，我也是用webpack4 发现无法实现按需加载。
我的 .babelrc 是这样的
`
{ 
    "plugins": ["react-hot-loader/babel", ["import", {
        "libraryName": "antd-mobile",
        "style": "css"
    }]]
}
`

**Comment by tianleiyiji123** [comment]
请问是怎么解决的？style: true的话less加载不了样式，但是js能引入进来，less编译也没有报错；如果单独引用antd-mobile中的less文件，也能预编译的，就是单独引用antd样式没效果，求解，大神先谢谢

**Comment by Kay622** [comment]
> 请问是怎么解决的？style: true的话less加载不了样式，但是js能引入进来，less编译也没有报错；如果单独引用antd-mobile中的less文件，也能预编译的，就是单独引用antd样式没效果，求解，大神先谢谢

我也是这样的问题，怎么解决的？

**Comment by 34678** [comment]
> 已经找到问题了

hello 请问是什么问题呢 能提供一下解决方案吗
