### ISSUE TITLE
carousel/index.native.tsx code error

### ISSUE THREAD

**Issue by John251314** [ant-design/ant-design-mobile#2597]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.10

### Environment
"antd-mobile": "^2.1.9"

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/master/components/carousel/index.native.tsx](https://github.com/ant-design/ant-design-mobile/blob/master/components/carousel/index.native.tsx)

### Steps to reproduce
1、react-native中使用Carousel，设置autoplay， infinite

### What is expected?
无缝循环滚动，不要出现闪动

### What is actually happening?
出现闪动

---
382行代码明显错误
```
      if (infinite) {
        childrenArray.unshift(childrenArray[count - 1]);
        childrenArray.push(childrenArray[0]);
      }
```
应当改为：
```
      if (infinite) {
        const firstItem = childrenArray[0];
        const lastItem = childrenArray[count - 1];
        childrenArray.unshift(lastItem);
        childrenArray.push(firstItem);
      }
```

**Comment by warmhug** [comment]
Ref https://github.com/ant-design/ant-design-mobile/issues/2174#issuecomment-391989525
