### ISSUE TITLE
SwipeAction 在调试工具中，选择iphone以外的机型，左右滑动按钮 dom结构不存在，无法出现按钮。

### ISSUE THREAD

**Issue by aimaodeyuer** [ant-design/ant-design-mobile#260]
#### 本地环境

- antd-mobile 版本：0.7.8
- 操作系统及其版本：os 10.11.2
- 浏览器及其版本：qq浏览器4.1.4132

#### 你做了什么？

 引入 antd-mobile 的 SwipeAction

#### 你期待的结果是：

像官网一样正常显示，左右滑动能出现按钮

#### 实际上的结果：

调试工具中 iphone能出现按钮，google以及三星无法出现按钮

**Comment by aimaodeyuer** [comment]
--galaxy note3
![image](https://cloud.githubusercontent.com/assets/12092562/18511120/933ef22e-7ab4-11e6-9ead-8a6976976813.png)

![image](https://cloud.githubusercontent.com/assets/12092562/18511312/9f9e322c-7ab5-11e6-8e28-4ac3de491c09.png)

--iphone6
![Uploading image.png…]()

对比发现少了left 和 right 属性形成的dom结构

**Comment by silentcloud** [comment]
见 LS 回答！
