### ISSUE TITLE
使用InputItem组件时控制台报错，Unknown event handler property `onErrorClick`. It will be ignored.

### ISSUE THREAD

**Issue by ht1131589588** [ant-design/ant-design-mobile#2601]
![image](https://user-images.githubusercontent.com/24310479/40760041-70b6ddbc-64c7-11e8-83d9-bd4fe5436cce.png)

试了很多次，显示正常，功能正常，但是控制台就一直报这个错，强迫症，不使用InputItem组件时就没有那个问题

**Comment by yaoyuande** [comment]
这个bug 已经修复了  等新版本发布

**Comment by warmhug** [comment]
Close for https://github.com/ant-design/ant-design-mobile/issues/2565#issuecomment-392227010
