### ISSUE TITLE
DatePicker选择器，在使用date模式时，滚轮中不能够显示具体某一天

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design-mobile#2602]
效果如下所示：
![xiaoguo](https://github.com/suwu150/static-resource/blob/master/images/react-native-ant-design-datePicker.gif?raw=true)

当我第一次点击进去的时候，不能够完全显示，在我上下滚动之后，才会出现最后一列

注意：我在iPhone 6,iPhone 7,iPhone 8的模拟器中都运行测试过了，都有问题，和上面的一样
我的ant-design mobile版本是 "antd-mobile": "^2.1.8",

datePicker代码：
```
      <DatePicker
        {...this.props}
        mode="date"
        format={format}
        title={label}
        value={this.state.value}
        onChange={v => this._handleChange(v)}
        visible={this.state.visible}
        onOk={v => this._handleChange(v)}
        onDismiss={() => this.setState({ visible: false })}
      >
        ....
     </DatePicker>
```

**Comment by warmhug** [comment]
web or RN ?

**Comment by suwu150** [comment]
@warmhug RN

**Comment by warmhug** [comment]
Close for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452
