### ISSUE TITLE
<BackTop/>在如下Layout布局中怎么使用才会有效

### ISSUE THREAD

**Issue by wyf675518264** [ant-design/ant-design-mobile#2604]
Layout>
       
        <Sider
          trigger={null}
          collapsible
          collapsed={this.state.collapsed}
        >

          <div className="logo" />
          <Menu 
            theme="dark" 
            mode="inline" 
            defaultSelectedKeys={['1']}
            onClick={this.handleClick}
            selectedKeys={[this.state.current]}
          >
            <Menu.Item key="1">
              <Icon type="user" />
              <span className="nav-text">我的收藏</span>
            </Menu.Item>
            <Menu.Item key="2">
              <Icon type="video-camera" />
              <span className="nav-text">热门收藏</span>
            </Menu.Item>
            <Menu.Item key="3">
              <Icon type="upload" />
              <span className="nav-text">设置</span>
            </Menu.Item>
          </Menu>
          
        </Sider>

        <Layout>
        
          <Header style={{ background: '#fff', padding: 0 }}>
            <Icon
              className="trigger"
              type={this.state.collapsed ? 'menu-unfold' : 'menu-fold'}
              onClick={this.toggle}
            />
              <Add/>
              <WrappedNormalLoginForm /> 
          </Header>

          <Content style={{ margin: '24px 16px', padding: 24, background: '#fff'}}>

           <MyBookMark/>

          </Content>
           
        </Layout>

      </Layout>

**Comment by warmhug** [comment]
ref https://github.com/ant-design/ant-design/issues
