### ISSUE TITLE
Tabs里嵌套Carousel,在安卓手机上手左右滑动冲突并且selectedIndex属性与实际页不匹配，默认显示最后一页内容

### ISSUE THREAD

**Issue by BonnieWeb** [ant-design/ant-design-mobile#2606]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.10

### Environment
react-native 0.52.2 ,react 16.2.0

### Reproduction link
[http://xxxx](http://xxxx)

### Steps to reproduce
在第一个TabItem里加入Carousel组件，

### What is expected?
1、手动滑动Carousel时，不触发Tabs的切换，而是自身滑动至下一页；
2、selectedIndex设置的值与显示的页对应。
3、dot的active状态与当前对应页应该保持一致。

### What is actually happening?
1、手动滑动Carousel时，触发了Tabs的切换，自身无变化。（安卓机上存在问题）
2、selectedIndex设置的值与显示的页对应。（安卓和ios都存在问题）
3、一切按默认值设置，在安卓上显示的是最后一页内容，当前dot却显示第一个为active状态。

**Comment by warmhug** [comment]
ref #2174 / https://github.com/ant-design/ant-design-mobile-rn/issues/10 / https://github.com/ant-design/ant-design-mobile-rn/issues/7

**Comment by warmhug** [comment]
Close for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452

**Comment by gaoxiaosong1113** [comment]
我也遇到了同样的问题，请问有解决办法呢？

**Comment by qreal829475** [comment]
same problem. I find another Carousel .But  Tabs is also be triggered. I do not know why, i'm so sad.

**Comment by SirYuye** [comment]
Wrap the Carousel in a layer of div and bubble the tissue
`
<div onTouchMove={(e) => e.stopPropagation()}>
   <Carousel
      style={styles.carouselImg}
      autoplay
      infinite
      dotActiveStyle={{ backgroundColor: '#ed715a' }}
    >
       {carouseList.map((item: { _id: string; imgUrl: string; types: string; }) => {
           return <img key={item._id} style={styles.carouselImg} src={item.imgUrl} alt={item.types} />
        })}
   </Carousel>
</div>
`
