### ISSUE TITLE
SearchBar 搜索栏 基本型  clear按钮功能不正常 点击位置偏移

### ISSUE THREAD

**Issue by miss61008596** [ant-design/ant-design-mobile#261]
#### 本地环境

- antd-mobile 版本："0.8.x"
- 操作系统及其版本：OSX 10.11.6
- 浏览器及其版本：Google Chrome 51.0.2704.63 (64-bit)
#### 你做了什么？

SearchBar 搜索栏 基本型
#### 你期待的结果是：

clear按钮功能及事件正常
#### 实际上的结果：

本地不正常，官网也不正常，
clear按钮功能不正常 点击位置偏移

#### 可重现的在线演示

![image](https://cloud.githubusercontent.com/assets/6361237/18580864/ec4de05c-7c38-11e6-8819-c42e1da5e6f2.png)
1.点击clear按钮后
![image](https://cloud.githubusercontent.com/assets/6361237/18580885/078e7d72-7c39-11e6-8bb7-7182cd830b82.png)
2.其实位置偏移到了取消按钮，点击取消按钮触发了onClear event，
![image](https://cloud.githubusercontent.com/assets/6361237/18580923/31060f94-7c39-11e6-84f1-2f7bca021e2f.png)
初步判断是位置偏移

**Comment by pingan1927** [comment]
“取消”按钮两个字对应的是onCancel行为，如果调用时不传入对应的回调，默认行为是清除input的内容（clear行为）外加blur掉input，

而onClear的行为就是清除input的内容并继续focus

**Comment by pingan1927** [comment]
“取消”按钮两个字对应的是onCancel行为，如果调用时不传入对应的回调，默认行为是清除input的内容（clear行为）外加blur掉input，

而onClear的行为就是清除input的内容并继续focus

**Comment by pingan1927** [comment]
“取消”按钮两个字对应的是onCancel行为，如果调用时不传入对应的回调，默认行为是清除input的内容（clear行为）外加blur掉input，

而onClear的行为就是清除input的内容并继续focus

**Comment by miss61008596** [comment]
我在官网上和自己本地又反复测试了好多次，发现不是每次都可以触发onClear，每次都能触发onBlur，所以我现在用的不是基本型，而是定制取消按钮型

**Comment by pingan1927** [comment]
好的，我再review下。

**Comment by pingan1927** [comment]
```
// todo
```

**Comment by warmhug** [comment]
0.9 已无问题
