### ISSUE TITLE
ListView 输出row不能大于10

### ISSUE THREAD

**Issue by Safircn** [ant-design/ant-design-mobile#2611]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.11

### Environment
Mac OS X 10_13_4 Chrome/66.0.3359.181

### Reproduction link
[https://codepen.io/anon/pen/YvyEwX?editors=0011](https://codepen.io/anon/pen/YvyEwX?editors=0011)

### Steps to reproduce
NUM_ROWS设置为20 界面输出只有10条

**Comment by cexoso** [comment]
我也遇到了这个问题啊

**Comment by likezero** [comment]
首屏显示的数量有个属性 `initialListSize`，
可以把这个属性的值，设置成分页查询的每页数量。

**Comment by likezero** [comment]
另外要注意下这个属性 `pageSize`。最后也设置成分页查询的每页数量。
