### ISSUE TITLE
rn项目webview 里 ImagePicker组件,Android设备打开不相册

### ISSUE THREAD

**Issue by Josin22** [ant-design/ant-design-mobile#2614]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.11

### Environment
mac os x :10.13.4  firfox:60.0.0.1   react-native :0.51

### Reproduction link
[https://mobile.ant.design/components/image-picker-cn/](https://mobile.ant.design/components/image-picker-cn/)

### Steps to reproduce
rn项目里 添加ImagePicker组价,其中某个h5用到了ImagePicker组件来选取图片,结果打包Android apk安装时候,运行在Android 设备上ImagePicker组件 却打不开相册

### What is expected?
ImagePicker 能在原生Android的webview实现打开相册

### What is actually happening?
点击ImagePicker组件,无响应

**Comment by warmhug** [comment]
应该是你自己生成 webview 时的参数设置、或权限问题？跟组件本身没关系。

**Comment by Josin22** [comment]
原来是rn 里webview组件 里边选取相册需要自己去实现
