### ISSUE TITLE
IOS ReactNative Modal.prompt 遮挡问题依然存在并且无法输入中文

### ISSUE THREAD

**Issue by suifengJC614** [ant-design/ant-design-mobile#2617]
> 首先抱歉，无法使用你们给的链接提交issue，因为无法上传截图

### 首先是键盘遮挡问题

下面是问题截图

<img width="447" alt="image" src="https://user-images.githubusercontent.com/19297667/40938253-ecbd01d4-6873-11e8-80d2-a94985060e6d.png">

以上就是问题的展现，弹出框依然有一部分被键盘所遮挡，这并不是所期望的

### 其次，输入框无法输入中文

+ 具体表现形式就是 输入拼音选字之前，貌似就提前确认了，结果就是文本框输入的全是拼音

**Comment by suifengJC614** [comment]
下面是上面问题的访问代码
```
        Modal.prompt('修改单价', '请输入需要的单价', [{
            text: '取消'
        }, {
            text: '提交',
            onPress: (value) => console.log(`pressEditPress to ${value}`)
        }], 'default');
```

**Comment by warmhug** [comment]
Trace https://github.com/ant-design/ant-design-mobile-rn/issues/8

**Comment by sej1228** [comment]
请问这个问题是怎么解决的？
