### ISSUE TITLE
RN android 多个 InputItem 组合 焦点问题

### ISSUE THREAD

**Issue by jindada** [ant-design/ant-design-mobile#2618]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
android 6.0 

### Reproduction link
[http://no-link](http://no-link)

### Steps to reproduce
多个InputItem 组合 比如 登陆（有用户名和密码2个InputItem）
当我输入完用户名时 点击输入密码时 需要点击2次 密码InputItem才能获取焦点 第一次点击键盘隐藏 第二次点击才获取焦点

### What is expected?
期望键盘不隐藏 直接获取焦点

### What is actually happening?
需要点击2次 密码InputItem才能获取焦点

**Comment by warmhug** [comment]
Trace https://github.com/ant-design/ant-design-mobile-rn/issues/13
Close for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452
