### ISSUE TITLE
ImagePicker component don`t support custom a row show more than four image

### ISSUE THREAD

**Issue by yuanman0109** [ant-design/ant-design-mobile#2619]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
because product demand is small image，if a row show four image，bad experience

### What does the proposed API look like?
add a props， provide custom image number on a row

**Comment by yuanman0109** [comment]
if (length !== 0 && length % 4 !== 0) {
      const blankCount = 4 - length % 4;
      const fillBlankEl: any[] = [];
      for (let i = 0; i < blankCount; i++) {
        fillBlankEl.push(<Flex.Item key={`blank-${i}`} />);
      }
      allEl = allEl.concat(fillBlankEl);
    }
    const flexEl: any[][] = [];
    for (let i = 0; i < allEl.length / 4; i++) {
      const rowEl = allEl.slice(i * 4, i * 4 + 4);
      flexEl.push(rowEl);
    }
    const renderEl = flexEl.map((item, index) => (
      <Flex key={`flex-${index}`}>{item}</Flex>
    ));
源码这里写死了，希望能改成可配置的，有的时候ui的确设计的图片尺寸比较小

**Comment by ziluo** [comment]
same question: https://github.com/ant-design/ant-design-mobile/issues/2668

**Comment by doxiaodong** [comment]
2.2.3 已支持

**Comment by adonis-lsh** [comment]
支持了到时说一下属性啊

**Comment by bellson0d** [comment]
> 支持了到时说一下属性啊

length
