### ISSUE TITLE
npm run compile报错

### ISSUE THREAD

**Issue by jackyr** [ant-design/ant-design-mobile#2626]
hi，我clone了ant-design-moblie项目，在master分支上，npm run compile报错无法进行编译。请问你们平时是怎么编译的？
![Uploading image.png…]()

**Comment by warmhug** [comment]
不能复现。Uploading image.png... 不接受`随意/不规范`的提问！

**Comment by jackyr** [comment]
今天尝试发现，compile报错是用yarn install安装依赖后才能复现，而使用npm i安装却表现正常。具体根由未进一步深究…

**Comment by jackyr** [comment]
今天尝试发现，compile报错是用yarn install安装依赖后才能复现，而使用npm i安装却表现正常。具体根由未进一步深究…

**Comment by m9rco** [comment]
同样遇到过此类问题 typescript的问题，在@type 包里看到的 @jackyr

**Comment by alun-430** [comment]
> 同样遇到过此类问题 typescript的问题，在@type 包里看到的 @jackyr

你好，你是怎么解决的
