### ISSUE TITLE
PullToRefresh: Warning: Unknown prop `damping` on <div> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by xianyuxmu** [ant-design/ant-design-mobile#2627]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.11

### Environment
Chrome 67

### Reproduction link
[http://none.com](http://none.com)

### Steps to reproduce
use PullToRefresh component, it occurs when page rendered! 

### What is expected?
non error console info!

### What is actually happening?
commons.ed3d24925a15de57093b5a36c8c1d57f.js:290 Warning: Unknown prop `damping` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by PullToRefresh)
    in PullToRefresh (created by PullToRefresh)

**Comment by alex86gbk** [comment]
出现版本 2.1.11

**Comment by KgTong** [comment]
@alex86gbk 提供个复现的demo？

**Comment by KgTong** [comment]
Sorry for that. we have fixed it.
Just reinstall the node_modules.

**Comment by alex86gbk** [comment]
看起来不是由版本差异导致的。我本机上一个SVN环境，一个GIT环境（两个环境分处不同文件夹）。
SVN环境下无论哪个版本均不报警告；
GIT环境把SVN环境的 node_modules 文件夹拷贝过来也不会报；
GIT环境 npm install 后运行会报警告！！

![image](https://user-images.githubusercontent.com/1990992/41212117-4ac09fbc-6d6e-11e8-84e1-c81a6a6c6330.png)

**Comment by KgTong** [comment]
@alex86gbk 重装下依赖，已经修复了

**Comment by alex86gbk** [comment]
@KgTong Good job!
重新安装要把 package-lock.json 也删掉。
另外 rmc-pull-to-refresh 的版本怎么从1.0.9 一下就到 1.0.11了！你们的版本管理这么定的？

**Comment by KgTong** [comment]
早上1.0.10发包有点失误，npm 回滚包有些问题，直接重发一个1.0.11

**Comment by zhanglina1990** [comment]
11版本上，删除package-lock.js 文件，重新install 之后，还是报‘damping'的警告.

**Comment by KgTong** [comment]
看看rmc-pull-to-refresh的版本

**Comment by zhanglina1990** [comment]
1.0.9的

**Comment by KgTong** [comment]
版本未更新，不是组件问题，自行解决下？
