### ISSUE TITLE
SwipeAction放在list中，数量多时，手机端无法往下滑动。

### ISSUE THREAD

**Issue by huangnan1994** [ant-design/ant-design-mobile#2628]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.10

### Environment
2.1.10

### Reproduction link
[https://antd-mobile.gitee.io/components/swipe-action-cn/#components-swipe-action-demo-basic](https://antd-mobile.gitee.io/components/swipe-action-cn/#components-swipe-action-demo-basic)

### Steps to reproduce
SwipeAction放在list中，数量超过屏幕时，手机端无法触发浏览器滑动事件。

### What is expected?
RT

### What is actually happening?
SwipeAction放在list中，数量超过屏幕时，手机端无法触发浏览器滑动事件。

**Comment by cdLVV** [comment]
我也碰到一样的问题了,确实是SwipeAction组件阻止了原生的滑动事件,我把SwipeAction包裹的区域缩小,拖动SwipeAction外面的区域就可以...

**Comment by huangnan1994** [comment]
@cdLVV 你这个操作不合理哦

**Comment by huangnan1994** [comment]
希望antd-mobile的开发大佬回一下怎么解决

**Comment by quentinyang** [comment]
@huangnan1994 谢谢你的反馈。
最近我们有修复过这个问题。ref #1954 。
你尝试删除本地node_modules/重新 npm install下。
看下安装后node_modules下依赖几个组件的版本，应该是rc-swipeout@v2.0.7和rc-gesture@v0.0.20版本。
如果还有问题，请告诉我，谢谢。

**Comment by huangnan1994** [comment]
@quentinyang 可以了

**Comment by huangnan1994** [comment]
@cdLVV 老哥，已经验证过了，可以了

**Comment by cdLVV** [comment]
@huangnan1994 你是删除了本地的node_modules/重新 npm install下,这样就可以了吗?你的antd-mobile的版本是多少?我的是在三星s8手机上不行,其他手机上是可以的
