### ISSUE TITLE
Antd官网，移动开发文档组件效果展示不出来，某个js资源加载不出来

### ISSUE THREAD

**Issue by Adam-Jin** [ant-design/ant-design-mobile#2630]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.11

### Environment
Win10 Chrome

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile](http://new-issue.ant.design/?repo=ant-design-mobile)

### Steps to reproduce
打开antd官网移动开发文档，点击某个组件

### What is expected?
可以看到组件的效果

### What is actually happening?
无法看到组件效果，js加载报错，貌似资源缺失

**Comment by lifuzhao100** [comment]
我也经常遇到这个问题，打开ant.design或者mobile.ant.design的时候，有时候行，某些时候不行
![image](https://user-images.githubusercontent.com/16594057/41188005-4d5c49aa-6be9-11e8-8f03-de1860dfcd5a.png)

**Comment by warmhug** [comment]
Close for #2632

**Comment by lifuzhao100** [comment]
@warmhug 不是科学上网的原因
![image](https://user-images.githubusercontent.com/16594057/41215308-563700d4-6d82-11e8-999f-1f886d43874a.png)
这个mobile.ant.design预览的网址，打不开

**Comment by warmhug** [comment]
@lifuzhao100 抱歉，确实是代码问题，之前 build site 出错。已经修复，刷新页面

**Comment by APJSDK** [comment]
在手机端还是不行啊？
import "antd/dist/reset.css"; 后还是没效果
