### ISSUE TITLE
吧rn分拆出去是一种粗暴的行为

### ISSUE THREAD

**Issue by zuoge85** [ant-design/ant-design-mobile#2631]
项目大量用ant-design-mobile进行跨rn和web 开发，现在这样的分拆行为感觉太粗暴了，这样下去两个项目的api 还能兼容不。如果不能兼容，那么使用ant-design-mobile 的必要性就没了。

**Comment by warmhug** [comment]
感谢建议，仍然会尽量做到兼容，rn api 会跟随 web 版本。
