### ISSUE TITLE
The homepage is broken (https://mobile.ant.design/)

### ISSUE THREAD

**Issue by ucanlendit** [ant-design/ant-design-mobile#2632]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.11

### Environment
The WWW

### Reproduction link
[https://mobile.ant.design/](https://mobile.ant.design/)

### Steps to reproduce
navigate to https://mobile.ant.design/ open console and see:

 Uncaught ReferenceError: React is not defined
    at Object.<anonymous> (index.js:1)
    at m (common.js:1)
    at Object.<anonymous> (index.js:1)
    at m (common.js:1)
    at window.webpackJsonp (common.js:1)
    at index.js:1

### What is expected?
https://mobile.ant.design/ should render 

### What is actually happening?
:S

**Comment by ucanlendit** [comment]
Even the mirror is not working:
Ant Design Mobile: http://antd-mobile.gitee.io

**Comment by SHITianhao** [comment]
React CDN is not included in production env ;)

**Comment by warmhug** [comment]
Ref #2513

**Comment by warmhug** [comment]
Fixed, please refresh page.
