### ISSUE TITLE
https://mobile.ant.design - Down

### ISSUE THREAD

**Issue by taufik-hidayat** [ant-design/ant-design-mobile#2634]
The official site of Mobile Ant Design is down. Anyone can fix it?

**Comment by chenqingspring** [comment]
404 -> https://mobile.ant.design/kitchen-sink.js

**Comment by warmhug** [comment]
Close for #2632

**Comment by warmhug** [comment]
@chenqingspring It really is 404, But this is right.

**Comment by chenqingspring** [comment]
@warmhug  I can't understand what you mean by "But this is right", But I saw this link "https://mobile.ant.design/kitchen-sink/kitchen-sink.js" GET 200
