### ISSUE TITLE
antd mobile website not working

### ISSUE THREAD

**Issue by aibrahim3546** [ant-design/ant-design-mobile#2635]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.11

### Environment
browser version

### Reproduction link
[https://mobile.ant.design/](https://mobile.ant.design/)

### Steps to reproduce
please fix this asap

### What is expected?
nothing

### What is actually happening?
cannot open the page.
Uncaught ReferenceError: React is not defined

**Comment by TUBB** [comment]
I have the same issue at most time.

**Comment by warmhug** [comment]
Fixed, please refresh page. ref #2632

**Comment by joebits** [comment]
@aibrahim3546 @TUBB Try to disable all your adblockers etc. That worked for me. They should probably still look into this but until then it's a workaround..

**Comment by aibrahim3546** [comment]
@TUBB this problem is their side problem no need to worry on your side.
