### ISSUE TITLE
Popover如何手动控制显示、隐藏?

### ISSUE THREAD

**Issue by starzou** [ant-design/ant-design-mobile#2639]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Popover不通过点击事件触发隐藏、显示，使用 this.setState({visible: true || false}); 来控制

### What does the proposed API look like?
<Popover visible={true} trigger="manually"></Popover>

使用新的 trigger 属性值 manually 来设置

**Comment by likezero** [comment]
没太明白你要的效果。通过visible 不能满足？

**Comment by wangdanting** [comment]
还有一种暴力方法，不到万不得已不推荐使用。

``` javascript
// 暴力隐藏所有 Popover
const elements = document.getElementsByClassName('ant-popover');
for (let i = 0, len = elements.length; i < len; i++) {
  let classVal = elements[i].getAttribute('class');
  classVal = classVal.concat(' ant-popover-hidden');
  elements[i].setAttribute('class', classVal);
}
```
