### ISSUE TITLE
rn的tabs卡顿严重

### ISSUE THREAD

**Issue by zjsxfly** [ant-design/ant-design-mobile#264]
多个地方都试了，原来还以为是ListView的原因，后来发现只要用到tabs的地方都卡顿。

**Comment by zjsxfly** [comment]
测试用ios9.3模拟器

**Comment by silentcloud** [comment]
用真机试试

**Comment by meakchen** [comment]
在模拟器上久了就会出现这个问题，tabs切换很缓慢

**Comment by suwu150** [comment]
真心卡，有没有更好的解决办法

**Comment by warmhug** [comment]
Maybe same as https://github.com/ant-design/ant-design-mobile-rn/issues/10
Lock for https://github.com/ant-design/ant-design-mobile/issues/2556#issue-324881452
