### ISSUE TITLE
carousel cannot read property 'scrollTo' of null

### ISSUE THREAD

**Issue by showtan001** [ant-design/ant-design-mobile#2646]
**antd-mobile:  2.0.0
react-native:  0.46.4** 
![screenshot_2018-04-27-15-04-50-655_com yuecai](https://user-images.githubusercontent.com/32892347/41412960-3cc1e6a2-7014-11e8-876f-54b0ef34ce04.png)

**Comment by KgTong** [comment]
RN 移步 https://github.com/ant-design/ant-design-mobile-rn/issues
