### ISSUE TITLE
When I use pullToRefresh，（direction：up）,the list is less than whole page ,How to prohibit pullup to load more?

### ISSUE THREAD

**Issue by PPPenny** [ant-design/ant-design-mobile#2648]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I use pullToRefresh，（direction：up）,the listItem is less than whole page ,How to prohibit pullup to load more?
当列表页面不足一页的时候，禁止上拉加载更多，或者下拉刷新

### What does the proposed API look like?
Add  an attribute loadMore(direction:up) ||  toRefresh (direction:down)；if true,represent it can't loadMore or refresh when list is less than whole page 。

**Comment by KgTong** [comment]
这种建议使用ListView的renderFooter来做加载样式
