### ISSUE TITLE
Type errors

### ISSUE THREAD

**Issue by danielreichhart** [ant-design/ant-design-mobile#2649]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
Windows 10, Chrome 67,  React 16.4.1, TypeScript 2.9.2

### Reproduction link
[https://github.com/danielreichhart/antd-mobile-type-error](https://github.com/danielreichhart/antd-mobile-type-error)

It is a minimal reproduction, bootstrapped with the Create React App (TypeScript version), and the integration of ant design mobile.

### Steps to reproduce
- Clone the repo
- npm install
- npm start

### What is expected?
That the app compiles and runs.

### What is actually happening?
Failed to compile.

C:/Workspace/antd-mobile-type-error/node_modules/antd-mobile/lib/_util/types.d.ts
(8,63): Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

**Comment by Kanchil** [comment]
same question

**Comment by k644606347** [comment]
同样的问题

**Comment by doxiaodong** [comment]
The fast way is back typescript to ~2.8.x rather than 2.9.

**Comment by doxiaodong** [comment]
fixed after 2.2.1
