### ISSUE TITLE
toast打包的时候offline.png出错

### ISSUE THREAD

**Issue by daofeng125** [ant-design/ant-design-mobile#2652]
打包的时候出错
/Users/weidong/www/Trade/android/app/build/intermediates/res/merged/release/drawable-xhdpi/node_modules_antdmobile_lib_toast_images_offline.png: error: Duplicate file.
/Users/weidong/www/Trade/android/app/build/intermediates/res/merged/release/drawable-xhdpi-v4/node_modules_antdmobile_lib_toast_images_offline.png: Original is here. The version qualifier may be implied.

**Comment by ziluo** [comment]
RN or Web ?

**Comment by daofeng125** [comment]
RN

**Comment by daofeng125** [comment]
error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.

**Comment by KgTong** [comment]
RN移步[这里](https://github.com/ant-design/ant-design-mobile-rn/issues)
