### ISSUE TITLE
 Carousel组件向左和向右滑动均没有效！！！

### ISSUE THREAD

**Issue by hst-Sunday** [ant-design/ant-design-mobile#2654]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
IOS11.4，chrome最新版

### Reproduction link
[https://mobile.ant.design/components/carousel/](https://mobile.ant.design/components/carousel/)

### Steps to reproduce
创建最新的脚手架，直接贴官网上的carousel的demo代码。

### What is expected?
左右滑动和你们官网的一致

### What is actually happening?
滑动后无任何效果

**Comment by likezero** [comment]
官方demo在chrome最新版本  67.0.3396.87 版本正常的。
demo地址：https://mobile.ant.design/kitchen-sink/components/carousel?lang=en-US#carousel-demo-0

**Comment by hst-Sunday** [comment]
我加了一些组件进去貌似就失灵了，具体问题还在研究中

**Comment by hst-Sunday** [comment]
请问怎么消除fied对Carousel组件的影响

**Comment by missmimia** [comment]
> 请问怎么消除Tabbar的样式 position: fied 对Carousel组件的影响

emmmm 请问楼主最后是怎么解决的？？

**Comment by hst-Sunday** [comment]
@missmimia 我记得好像是去掉了那个fastClick的插件就可以，好久了，我也忘记了
