### ISSUE TITLE
Calendar 日历组件 滑动后 点击确认或者关闭报错

### ISSUE THREAD

**Issue by wangyue1994** [ant-design/ant-design-mobile#2655]
Uncaught TypeError: Cannot read property 'style' of null
   at DatePicker.js:138
onFinish里有异步函数

**Comment by Aditya-Shah** [comment]
I'm facing the similar problem. A reproduce for the same (Try using mobile mode and swiping between tabs):

https://codepen.io/aditya-shah/pen/vrpwxZ?editors=0111

**Comment by likezero** [comment]
@wangyue1994  can you provide a preproduce demo ?

@Aditya-Shah  I can't find any error in your demo . can you provide more information ?

**Comment by wangyue1994** [comment]
3q

**Comment by likezero** [comment]
@Aditya-Shah, this is fixed ,  please update node_modules
