### ISSUE TITLE
antd-mobile的Popover，ios上点击遮罩层不触发onVisibleChange事件

### ISSUE THREAD

**Issue by StoneBeGiant** [ant-design/ant-design-mobile#2659]
antd-mobile的Popover，ios上点击遮罩层不触发onVisibleChange事件
朋友安卓上却是可以的
用了官方的文档上的例子在苹果手机上也是有这个问题

**Comment by 791060555** [comment]
现在ios没有问题，但是android点击可以打开弹框，但是，点击mask和内容重叠的地方不能关闭弹框，点击没有重叠部分的mask可以关闭
