### ISSUE TITLE
webpack为什么无法按需加载ant-mobile样式

### ISSUE THREAD

**Issue by NANASE-TAKESI** [ant-design/ant-design-mobile#2660]

**Comment by ziluo** [comment]
有使用`bable-plugin-import`吗 https://github.com/ant-design/babel-plugin-import

**Comment by NANASE-TAKESI** [comment]
有引入这个组件，不知道是不是还需不需要在webpack的配置文件里配置一下，按照官方文档的写法，把那句引入文件的代码也写进去了。

**Comment by ziluo** [comment]
把你的用法贴出来看下

**Comment by NANASE-TAKESI** [comment]
@ziluo 
<img width="733" alt="_491f3917-7c91-4c71-bff5-85b3e0187108" src="https://user-images.githubusercontent.com/38271786/41712568-72603f8e-757d-11e8-9e78-15babb1df381.png">

**Comment by NANASE-TAKESI** [comment]
@ziluo 
<img width="733" alt="_491f3917-7c91-4c71-bff5-85b3e0187108" src="https://user-images.githubusercontent.com/38271786/41712685-bbd254fe-757d-11e8-91db-ad10a8087276.png">

**Comment by ziluo** [comment]
看了用法，和`babel-plugin-import`的用法相同，是否和`HappyPack`有关，建议提个Issue到 https://github.com/ant-design/babel-plugin-import/issues 问下
