### ISSUE TITLE
Tabs 跟随手势滑动，划出屏幕时，界面会停留在两个tab中间

### ISSUE THREAD

**Issue by cpd0101** [ant-design/ant-design-mobile#2661]
- [ ] I have searched the [issues](https://github.com/ant-design/antd-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
支付宝容器内

### Reproduction link
[https://render.alipay.com/p/h5/materielShop/www/apply.html](https://render.alipay.com/p/h5/materielShop/www/apply.html)

### Steps to reproduce
在切换tabs时划出屏幕，有一定几率让界面卡在两个tab中间

![image](https://user-images.githubusercontent.com/7753002/41655840-c0f63bde-74c0-11e8-9f3a-0f2f097e5edb.png)

### What is expected?
要么滚动到上一个tab，要么滚动到下一个tab

### What is actually happening?
处于tab切换的中间态

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
