### ISSUE TITLE
can't find variable:document

### ISSUE THREAD

**Issue by JiaHuaU** [ant-design/ant-design-mobile#2663]
![image](https://user-images.githubusercontent.com/13389128/41711052-c10fcd10-7579-11e8-83a6-4f70fe17af76.png)
this is install react-dom and run my device,but my project show it.

**Comment by JiaHuaU** [comment]
antd-mobile : 2.x
react-native : 0.53.0

**Comment by KgTong** [comment]
RN移步[这里](https://github.com/ant-design/ant-design-mobile-rn/issues)

**Comment by 15738039217** [comment]
can't find variable:document 找到问题解决的办法了吗

**Comment by zhangyanni666** [comment]
> can't find variable:document 找到问题解决的办法了吗

**Comment by awmleer** [comment]
rn 相关问题请移步：https://github.com/ant-design/ant-design-mobile-rn/issues
