### ISSUE TITLE
Iphone6 下 Modal 被金额键盘覆盖穿透

### ISSUE THREAD

**Issue by wSLecHayfIeNdock** [ant-design/ant-design-mobile#2664]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
Iphone6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/42wyo3ml07)

### Steps to reproduce
https://42wyo3ml07.codesandbox.io/

### What is expected?
![image](https://user-images.githubusercontent.com/16831715/41763108-b754aa14-762f-11e8-96e9-7a8be2d6738c.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/16831715/41763230-441ce600-7630-11e8-8d0f-579356d19665.png)

**Comment by likezero** [comment]
这个问题还存在吗
