### ISSUE TITLE
Imagepicker cannot select an Android photo album in Alipay

### ISSUE THREAD

**Issue by LancerLiu** [ant-design/ant-design-mobile#2666]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
android 6.0 alipay 10.1.25 

### Reproduction link
[https://mobile.ant.design/index-cn](https://mobile.ant.design/index-cn)

### Steps to reproduce
1.open alipay
2.scan https://mobile.ant.design/index-cn
3.select a phote in album (not take a photo)

no image displayed

### What is expected?
The selected pictures can be displayed.

### What is actually happening?
no image displayed

---
Imagepicker works well in the Android system's browser， but not in alipay.

**Comment by ziluo** [comment]
It may be related to Alipay's privacy policy, or you can try to use Alipay's open api with photo

**Comment by LancerLiu** [comment]
I see
