### ISSUE TITLE
在入口页index.html上添加官网的meta配置和引入 FastClick后，Carousel的点击需要点两次才能触发！

### ISSUE THREAD

**Issue by hst-Sunday** [ant-design/ant-design-mobile#2667]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
IOS11.4，chrome最新版

### Reproduction link
[https://mobile.ant.design/components/carousel/](https://mobile.ant.design/components/carousel/)

### Steps to reproduce
新建一个DVA项目，在入口页index.html配置好官网上的代码，引入Carousel组件，设置跳转页面，点击一次并不会跳转，需要再点一次才会跳转

### What is expected?
Carousel点击一次就能跳转了！

### What is actually happening?
Carousel点击两次才能跳转！

**Comment by hst-Sunday** [comment]
demo: http://www.heshengtian.club

**Comment by ccys** [comment]
I have the same problem

**Comment by likezero** [comment]
@hst-Sunday  your site is unavailable.

**Comment by ccys** [comment]
最里层元素添加needsclick的class解决

**Comment by doxiaodong** [comment]
@ziluo @likezero

**Comment by AYWK** [comment]
Ios9.1 and chrom32 for android canceled the 300ms click delay, why use fastclick?

**Comment by hst-Sunday** [comment]
today, 
I made a demo and wanted to reproduce it, but no previous a problem.
