### ISSUE TITLE
[Safari IPhoneX] transform needs to be forced to open the GPU acceleration

### ISSUE THREAD

**Issue by Thunf** [ant-design/ant-design-mobile#2672]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
Mozilla/5.0 (iPhone; CPU iPhone OS 11_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15F79 ChannelId(10) Nebula WK PSDType(0) Language/zh-Hans

### Reproduction link
is.a.secret

### Steps to reproduce
```
<StickyContainer>
  <Tabs tabs={[{title: 1}, {title: 2}]} renderTabBar={ (props) => {
    return (<Sticky>
      {({ style }) => <div style={{ ...style, zIndex: 1 }}><Tabs.DefaultTabBar {...props} /></div>}
    </Sticky>);
  } }>
    <div>1</div>
    <div>2</div>
  </Tabs>
</StickyContainer>
```

When change the tabs, some slender lines appears.

### What is expected?
Don't show slender lines.

### What is actually happening?
Some slender lines appears

---
```
.am-tabs-default-bar-underline {
  transform: translate3d(0, 0, 0);
}
```

It can be resolved by code above.

**Comment by doxiaodong** [comment]
Not only the Tabs use 2d animate without opening GPU acceleration. Try to check other components. @KgTong @ziluo
