### ISSUE TITLE
ListView used in PullToRefresh 

### ISSUE THREAD

**Issue by landmass** [ant-design/ant-design-mobile#2673]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.11

### Environment
WeChat browser（android）

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/pull-to-refresh](https://mobile.ant.design/kitchen-sink/components/pull-to-refresh)

### Steps to reproduce
quick sliding list

### What is expected?
Listview does not use PullToRefresh, quick sliding list. Like diagram
![avatar](https://raw.githubusercontent.com/landmass/images/master/listview_1.png)

### What is actually happening?
ListView used in PullToRefresh .There are gray blocks up and down the list when it slips quickly; when the list stops sliding, the gray blocks disappear. Like diagram
![avatar](https://raw.githubusercontent.com/landmass/images/master/listview_2.png)
![avatar](https://raw.githubusercontent.com/landmass/images/master/listview_3.png)

---
Latest version 2.2.0, still reproduced

**Comment by landmass** [comment]
Is there a solution now? @KgTong @ziluo

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
