### ISSUE TITLE
InputItem 相关问题

### ISSUE THREAD

**Issue by GHLandy** [ant-design/ant-design-mobile#2675]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
IPhone 中最新 Chrome

### Reproduction link
[http://none.com/none](http://none.com/none)

### Steps to reproduce
使用自动输入法输入中文的时候，会连带输入的英文字母出现在输入框中

### What is expected?
输入时候仅输入中文

### What is actually happening?
英文字母和中文一起输入到了输入框

**Comment by micooz** [comment]
功能正常，没有重现，`自动输入法`是什么输入法？

**Comment by GHLandy** [comment]
> 功能正常，没有重现，自动输入法是什么输入法？

诶，手误，应该是 `系统自带的输入法`

我在 `InputItem` 使用 了先的方法去空白字符
```javascript
handleOnChange = (value, id) => {
  value = typeof value === 'object' ? value : value.replace(/\s+/g, '');

  this.setState({ clientInfo: {
    ...this.state.clientInfo,
    [id]: typeof value === 'object' ? value[0] : value,
  }})
}
```

然后，像 IPhone自带的输入法、微软拼音在输入的时候，它们的在选词之前的那些英文是最直接在输入框中的，所以选词后会在中文之前附带了一串英文。

或者说我的 onChange 方法的去空格方式不对？

还望解惑。

**Comment by GHLandy** [comment]
ok.

**Comment by fanmzdj** [comment]
去除空格的正则修改可以解决：String(value).replace(/(^\s*)|(\s*$)/g, '')

**Comment by fanmzdj** [comment]
尝试了去除空格的正则修改，是否解决：
```js
String(value).replace(/(^\s*)|(\s*$)/g, '')
```
