### ISSUE TITLE
是否能提供类似Ant Design Pro脚手架？

### ISSUE THREAD

**Issue by zhengjieyuan** [ant-design/ant-design-mobile#2679]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
新接触Ant Design Mobile ，有点不知道如何下手开发，希望能提供类似Ant Design Pro脚手架

参考了网上一些例子，在尝试Ant Design Pro 上开发Ant Design Mobile  ，但是对于上中下布局结构和路由方式不太明白。希望大神指导！

### What does the proposed API look like?
希望能提供dva, 布局，路由的脚手架

**Comment by ybning** [comment]
+1

**Comment by codepandy** [comment]
这个现在有吗？

**Comment by likezero** [comment]
脚手架暂时没有。demo有示例代码
