### ISSUE TITLE
Flex 组件去除 FlexItem

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#268]
在 Flex 组件上添加 `dataSource` 和 `renderItem: (rowId) => <a>{rowData}</a>` ，去除 FlexItem

为了能充分自定义，现在 flexitem 固定用了 div 包裹，里边放 a 标签等、需要设置其高度和包裹的 div 一致，比较多余。

**Comment by yiminghe** [comment]
Item 还是需要的，封装底层 dom 和样式
