### ISSUE TITLE
关于radio组件的一些问题！！！

### ISSUE THREAD

**Issue by hst-Sunday** [ant-design/ant-design-mobile#2680]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.1

### Environment
IOS11.4，chrome最新版

### Reproduction link
[https://mobile.ant.design/components/radio-cn/](https://mobile.ant.design/components/radio-cn/)

### Steps to reproduce
在你们官网的demo例子中测试数据data2中的extra属性添加多行字，
会发现右边的勾不会自动垂直居中，
而且extra输入多行字后，
点击radio框需要点击最上面的字体部分才能触发选择，
点击除最上面字体部分的区域均无法选择。

### What is expected?
选择后右边√自动居中，点击单个选项的任何区域都有效

### What is actually happening?
选择后右边√偏上，点击单个选项后，√以下的区域都无效

**Comment by micooz** [comment]
请提供具体实例演示如何在extra上添加多行字？
