### ISSUE TITLE
ImagePicker组建，调用摄像头拍照时，上传的照片会被旋转90度

### ISSUE THREAD

**Issue by LinLu1996** [ant-design/ant-design-mobile#2682]

**Comment by mazhy** [comment]
手机app上传图片, 如果选择照片没有问题, 选择拍照上传的, 图片会发生90度旋转

**Comment by Josemaker** [comment]
我这儿部分手机也出现了这个问题，微信内还是Safari打开，拍照或者直接上传都会出现，请问您这个问题解决了吗

**Comment by yxrgds** [comment]
偶尔会出现上传图片后，图片带上了EXIF属性，导致图片在部分浏览器上会90度旋转
