### ISSUE TITLE
Carousel组件支持free自由滑动吗，即滑动停止时不自动贴边？

### ISSUE THREAD

**Issue by zywu2** [ant-design/ant-design-mobile#2686]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Carousel组件支持free自由滑动，即滑动停止时不自动贴边

### What does the proposed API look like?
Carousel组件支持free自由滑动，即滑动停止时不自动贴边

**Comment by ziluo** [comment]
你描述的场景和Carousel的目标场景不太一致，建议直接使用`overflow: scroll; -webkit-overflow-scrolling: touch;` CSS来实现即可
