### ISSUE TITLE
Gird组件的activeStyle和activeClassName产生冲突

### ISSUE THREAD

**Issue by BlackHole1** [ant-design/ant-design-mobile#2689]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.1

### Environment
win10、chrome

### Reproduction link
[https://codepen.io/anon/pen/YvRJXx](https://codepen.io/anon/pen/YvRJXx)

### Steps to reproduce
设置了activeStyle={false} 后，再设置activeClassName属性。将会无效

### What is expected?
activeStyle为false后，activeClassName照样可以可以使用。毕竟两个属性本不该关联起来

### What is actually happening?
当activeStyle为false后，activeClassName无效

**Comment by BlackHole1** [comment]
根据问题，我跟踪了下为什么会导致这样，发现Grid组件使用了`TouchFeedback`组件来完成的。

代码位置: [https://github.com/ant-design/ant-design-mobile/blob/master/components/grid/index.tsx#L122-L127](https://github.com/ant-design/ant-design-mobile/blob/master/components/grid/index.tsx#L122-L127)

`TouchFeedback`组件来自`rmc-feedback` package。
跟踪这个包的源码，发现了问题所在的源码位置:
[https://github.com/react-component/m-feedback/blob/master/src/TouchFeedback.tsx#L83-L87](https://github.com/react-component/m-feedback/blob/master/src/TouchFeedback.tsx#L83-L87)

```javascript
if (activeStyle !== false) {
  if (activeStyle) {
    style = {...style, ...activeStyle };
  }
  className = classNames(className, activeClassName);
}
```

代码的逻辑是错误的，当activeStyle为false时，那么`activeClassName`将无法被应用。

个人觉得，这个问题应该由你们团队向`rmc-feedback` package提出PR修复。而不是由我进行提出。

PS:
> 英语不是太好，无法针对此issues使用英语说明。如果使用翻译软件，可能会扭曲我的意思。很抱歉。

**Comment by afc163** [comment]
@BlackHole1 不用担心，rmc-feedback 也是我们维护的。

**Comment by BlackHole1** [comment]
好的，那需要我这边在给rmc-feedback提交PR么

**Comment by likezero** [comment]
后续应该考虑把样式和功能禁用分开，目前暂时不变更。文档中也有说明
![image](https://user-images.githubusercontent.com/2275857/56498901-71005f80-6536-11e9-8e69-418d45d8b74f.png)

**Comment by BlackHole1** [comment]
如果后续考虑的话，那是不是应该建立一个相关的feat或者refactor在3.0.0的Project里。不然后续的结果可能所有人都将忘记

**Comment by BlackHole1** [comment]
且去年6月份提出来的问题，现在才能给结论的话，是不是中间时间过长了。
