### ISSUE TITLE
将ListView 放在Modal 里面 ListView 的onEndReached 方法不执行

### ISSUE THREAD

**Issue by Elvin1993** [ant-design/ant-design-mobile#269]
#### 本地环境

- antd-mobile 版本：0.8.2
- 操作系统及其版本：Mac OS
- 浏览器及其版本：Google Chrome 版本 52.0.2743.116 (64-bit)

#### 你做了什么？
 将ListView 放在Modal 里面 ListView 的onEndReached 方法不执行

#### 你期待的结果是：
滚动条 滚动到底部时 ListView 能正常执行onEndReached方法

#### 实际上的结果：
滚动条 滚动到底部时 ListView不执行onEndReached方法

#### 可重现的在线演示

```
 <Modal className="noPadding" animated transparent={true} visible={show} style={{height: '90%', width: '95%', marginBottom: '1rem'}} >
  {show ? 
    <ListView
      dataSource={dataSource}
      renderRow={this.handlerItem}
      renderFooter={this.renderFooter}
      pageSize={size}
      scrollEventThrottle={size}
      onEndReached={this.onEndReached}
      onEndReachedThreshold={20}
      stickyHeader
      stickyProps={{
        stickyStyle: { zIndex: 999, top: 43 },
        topOffset: -43,
        // isActive: false, // 关闭 sticky 效果
      }}
    /> : null}
</Modal>
```

**Comment by warmhug** [comment]
http://mobile.ant.design/components/list-view#components-list-view-demo-basic  
![image](https://cloud.githubusercontent.com/assets/2011119/18622050/aaeca482-7e5d-11e6-9fc0-f86d92a57128.png)

先仔细看下文档
