### ISSUE TITLE
Popover example not closing when clicking outside of it

### ISSUE THREAD

**Issue by msurdi** [ant-design/ant-design-mobile#2690]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.1

### Environment
Mac OS 10.13.5 (17F77) / google Chrome 67.0.3396.99 

### Reproduction link
[https://github.com/msurdi/antd-mobile-issue-example](https://github.com/msurdi/antd-mobile-issue-example)

### Steps to reproduce
npm install && npm start on the example project, click outside of the popup

### What is expected?
It should close as in the example provided at https://mobile.ant.design/components/popover/#components-popover-demo-basic

### What is actually happening?
It is not closing

---
Probably I'm doing something wrong or something is assumed in the docs that I'm missing.

**Comment by kartik2014** [comment]
Hi @msurdi , could you please let me know what is the fix for this issue? Popover is not closing on phone when I click on mask .

**Comment by msurdi** [comment]
Hi! I was just trying it out for using it in my project when I found this issue. Having not had any kind of answer after a couple days I've just decided to use something else. Anyways, I was probably doing something wrong given the live example seems to work fine. Sorry for not being of any help.
