### ISSUE TITLE
Flex组件的justify属性，在2.1.11版本上效果错误

### ISSUE THREAD

**Issue by zhanglina1990** [ant-design/ant-design-mobile#2691]
版本：2.1.11
`<Flex
              direction='row'
             // align='center'
              justify='between'
        >
          <div className='placeholder inline'>block</div>
          <div className='placeholder inline'>block</div>
          <div className='placeholder inline'>block</div>
        </Flex>`
第一个子元素的左边距没有

**Comment by skidxjq** [comment]
给定的代码片段未复现问题，请给出demo链接
