### ISSUE TITLE
部分组件1px 边框在某些手机上不显示

### ISSUE THREAD

**Issue by LowkeyY** [ant-design/ant-design-mobile#2694]
Checkbox组件在部分手机中不能正常显示选择框的边框

**Comment by zhanglina1990** [comment]
我也遇到同样问题

**Comment by paranoidjk** [comment]
伪类加 transform 是实现 1px 边框的方案之一，也是我们综合对比权衡成本之后选择的，部分手机渲染不正常这个可能无解。

如果在高清屏上能接受普通的边框效果，你可以在检测 UserAgent 在对应的设备上给你的页面  html 标签加上 data-scale 属性，antd-mobile 则不会再对边框做任何处理。

**Comment by ZooTopiaGG** [comment]
antd-mobile 是我用过体验最差的组件库 没有之一，哈哈哈
