### ISSUE TITLE
Picker选中问题

### ISSUE THREAD

**Issue by lhwu** [ant-design/ant-design-mobile#2695]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.1

### Environment
os: win10,浏览器：微信

### Reproduction link
[https://codepen.io/lhwu/pen/yEGWxB?editors=1111](https://codepen.io/lhwu/pen/yEGWxB?editors=1111)

### Steps to reproduce
1. Picker赋值 value=[undefined]
2. 运行后，点击Picker
3. 直接点击ok

### What is expected?
onChange方法的value 应该为 [1]

### What is actually happening?
onChange方法的value 为[undefined]

---
不太会使用codepen，大概就是这么个意思、、、、、

**Comment by yejing2017** [comment]
用 2.2.2 版本 ，picker 的 返回值 还是 `[undefined]`
