### ISSUE TITLE
智障的antd-mobile总结

### ISSUE THREAD

**Issue by fangkyi03** [ant-design/ant-design-mobile#2697]
先说一下 几个开发中遇到的智障的点
目前自己版本:2.1.8
rn:0.51
1.升级版本问题 升级到最新版以后 发现提示用了react-dom 需要安装一下ok 安装以后 发现又报找不到
document 哎 这个问题搞了半天 从2.1.8就是升不到最新版本 只能放弃

2. 2.1.8版本的代码 也不知道是哪个脑残写的 真的 
![image](https://user-images.githubusercontent.com/30390014/42131690-949ca398-7d3a-11e8-9e93-c63759d1c781.png)
手风琴这边返回的居然是个null 其次手风琴无法对title的字体做出限制 我也是醉了 只能用默认rn自带的 导致样式显示特别丑

3. grid
![image](https://user-images.githubusercontent.com/30390014/42131701-f1e62e20-7d3a-11e8-83f2-a1ac7ba3b6bb.png)
gridj居然限制了你的高度 我也是醉了取的是屏幕宽度/4 然后你的东西如果超过这个值就会显示不正常 需要手动把这个height设为undefined才可以

现在我版本想升级都不行 垃圾的要死 谁用谁知道 被坑惨了

**Comment by cncolder** [comment]
@fangkyi03 你说的最新版本在这 https://github.com/ant-design/ant-design-mobile-rn

ant-design-mobile 从 2.2.0 开始只包含 web 部分.

**Comment by ziluo** [comment]
RN移步到：https://github.com/ant-design/ant-design-mobile-rn/issues
