### ISSUE TITLE
Carousel 滑动报错

### ISSUE THREAD

**Issue by guanjp** [ant-design/ant-design-mobile#2699]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.1

### Environment
windows10 专业版

### Reproduction link
[https://blog.guanjp.com/](https://blog.guanjp.com/)

### Steps to reproduce
左右滑动Carousel组件，控制台报 `[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.` 

### What is expected?
正常滑动，控制台无报错信息

### What is actually happening?
正常滑动，控制台报错

---
不影响用户操作，但是控制台会一直报错，对错误收集会有影响

**Comment by ziluo** [comment]
Related to [Passive Event Listeners](https://zhuanlan.zhihu.com/p/24385322), fix it later

**Comment by territoryfan** [comment]
I met too, version: "antd-mobile": "^2.1.9"

**Comment by hellosean1025** [comment]
什么时候能够修好？

**Comment by hellosean1025** [comment]
@750973092 @territoryfan @guanjp 
等官方修复黄花菜都凉了，大家直接老外的吧，还有 antd-mobile carousel组件也是基于这个开发的 
https://github.com/FormidableLabs/nuka-carousel

**Comment by qhy90223** [comment]
me too

**Comment by toFrankie** [comment]
应该不是官方的锅，好像是Chrome浏览器新版本的原因，试看一下这篇文章：[chrome 监听touch类事件报错：无法被动侦听事件preventDefault](https://segmentfault.com/a/1190000007621605)。我在Safari控制台是看不到同样的error的。

**Comment by watsonhaw** [comment]
好像这个是浏览器的问题，请问有方法可以让浏览器不提示error吗？ant的大大们

**Comment by vnues** [comment]
`touch-action: pan-y;`
加上这段样式就能屏蔽了

**Comment by alexchen1875** [comment]
> `touch-action: pan-y;`
> 加上这段样式就能屏蔽了

worked for me .

anyway ,there are many bugs waiting to be fixed

**Comment by hansinhu** [comment]
rmc-nuka-carousel源码在哪里，nuka-carousel 已经 v4+了，rmc-nuka-carousel 始终未更新

**Comment by Shuo-Mr** [comment]
> `touch-action: pan-y;`
> 加上这段样式就能屏蔽了

请问加在哪里？我加在Carousel上面没有效果，Carcousel下的每个子项也都测试加过，并没有效果。
也试过监听Carousel的touchmove事件，并设置passive : false, 也没有效果。

最后我找到node_modules 下的 rmc-nuka-carousel 包，删除event.preventDefault(), 的确抛出错误了，但是这并无意义。

**Comment by Shuo-Mr** [comment]
@vnues 
> `touch-action: pan-y;`
> 加上这段样式就能屏蔽了

请问加在哪里？我加在Carousel上面没有效果，Carcousel下的每个子项也都测试加过，并没有效果。
谢谢。

其他尝试：
也试过监听Carousel的touchmove事件，并设置passive : false, 也没有效果。
最后我找到node_modules 下的 rmc-nuka-carousel 包，删除event.preventDefault(), 的确抛出错误了，但是这并无意义。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
