### ISSUE TITLE
Stepper onChange callback is never called

### ISSUE THREAD

**Issue by romu70** [ant-design/ant-design-mobile#2702]
- [ X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.1

### Environment
macOS, Firefox   Chromium

### Reproduction link
[https://codepen.io/anon/pen/WdxqLP?editors=0010](https://codepen.io/anon/pen/WdxqLP?editors=0010)

### Steps to reproduce
Just try the code from the Stepper demo or this one from the issue #2189: https://github.com/ant-design/ant-design-mobile/issues/2189

### What is expected?
A click on   should increment the Stepper value I guess.

### What is actually happening?
Nothing. The onChange event seems to never be fired. if I replace the code by onChange={console.log}, I get nothing.

---
I'm a React and Ant newbie. I'm just playing with Ant mobile on Firefox (or Chromium) to see how I can use it to make some prototypes.

**Comment by micooz** [comment]
Please try again in mobile or enable mobile mode on browser, this is probably caused by fastclick.

**Comment by romu70** [comment]
Thanks a lot for the help. It works !
I can close this ticket.

**Comment by jimmyshen007** [comment]
I encountered the same problem. Digging into the source code, I figured out a workaround which might help people using it on computer browser:

Basically we need to write a wrapper for the original antd stepper (to modify its upHandler and downHandler so we can register our own onClick handlers.), and we also need a ref to the antd Stepper instance to access its current value and step. code as following:

import StepperAnt from 'antd-mobile/lib/stepper';
import Icon from 'antd-mobile/lib/icon';

class Stepper extends Component{

  onUpClick = (e) => {
    e.preventDefault();
    const {onChange} = this.props;
    const {value, step} = this.stepper.props;
    onChange(value+step);
  }

  onDownClick = (e) => {
    e.preventDefault();
    const {onChange} = this.props;
    const {value, step} = this.stepper.props;
    onChange(value-step);
  }

  render() {
    const { value, onChange } = this.props;
    return (
      <StepperAnt
        ref={node => this.stepper = node}
        value={value}
        onChange={onChange}
        showNumber
        upHandler={<Icon type="plus" size="xxs" onClick={this.onUpClick} />}
        downHandler={<Icon type="minus" size="xxs" onClick={this.onDownClick} />}
      />
    );
  }
}

Of course, you could deal with min/max bound in your own onChange function passed in.
