### ISSUE TITLE
Carouse 切换动画

### ISSUE THREAD

**Issue by mdj11j** [ant-design/ant-design-mobile#2703]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前Carouse通过设置 selectedIndex改变内容时 缺少动画

### What does the proposed API look like?
无

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
