### ISSUE TITLE
Slider 如何显示tip

### ISSUE THREAD

**Issue by lgp2016** [ant-design/ant-design-mobile#2705]
请问如何让Slider组件显示tip，或者是如何给加上一个tip，就想ant desgin 一样的（如图）
![qq 20180704174416](https://user-images.githubusercontent.com/19548051/42269950-395b4b40-7fb2-11e8-99af-9691d08b102a.png)

**Comment by ziluo** [comment]
`antd`是针对PC页面，`antd-mobile`是针对Mobile页面，所以在一些视觉交互是有所不同的，关于上面的说`top`，可以使用`antd-mobile`的`Popover`尝试下
