### ISSUE TITLE
为什么只有InputItem组件不能引用

### ISSUE THREAD

**Issue by lgp2016** [ant-design/ant-design-mobile#2706]
报错如下
./node_modules/antd-mobile/lib/input-item/style/index.less
Module build failed: 

        &.keyboard-delete {
          .encoded-svg-background('input_item_kb_backspace');
        ^
Inline JavaScript is not enabled. Is it set in your options?
      in D:\Work\Work_Midai_H5\src\jiebei-h5\node_modules\antd-mobile\lib\input-item\style\custom-keyboard.less (line 136, column 10)

**Comment by lgp2016** [comment]
@ziluo 已经知道问题出在哪里，如下
![qq 20180705115145](https://user-images.githubusercontent.com/19548051/42301792-d8466964-8049-11e8-805c-553229c647d5.png)
如果设置成ture，就不能引用InputItem;
但是我需要设置成true，来定制主题，真的好尴尬

**Comment by micooz** [comment]
请提供一下 less 的版本。

尝试在 less-loader 里添加一个配置开启 `Inline JavaScript`：

```js
{ loader: 'less-loader', options: { modifyVars: true, javascriptEnabled: true  }}
```

参考文档：
- https://github.com/webpack-contrib/less-loader#examples
- http://lesscss.org/usage/

**Comment by lgp2016** [comment]
@micooz 
 "less": "^3.0.4",
 "less-loader": "^4.1.0",
试过了，成功了，可以调用了，谢谢回复
