### ISSUE TITLE
Input onBlur和onPressEnter逻辑相同，如何简写

### ISSUE THREAD

**Issue by SwinBlackSea** [ant-design/ant-design-mobile#2709]
<Input defaultValue={text} key={record.productId + record.language} size={1}
                    onPressEnter ={(e => {
                        let value = e.target.value
                        const reg = /(^(?:\d{1,3}|1000)$)/;
                        if (reg.test(value)) {
                            const payload = {
                                productId: record.productId,
                                language: record.language,
                                sortNum: value
                            }
                            dispatch({
                                type: `${namespace}/updateSortNum`,
                                payload: payload
                            })
                        } else {
                            message.error("请输入0 ~ 1000范围内的整数")
                        }
                    })}
                    onBlur={(e => {
                        let value = e.target.value
                        const reg = /(^(?:\d{1,3}|1000)$)/;
                        if (reg.test(value)) {
                            const payload = {
                                productId: record.productId,
                                language: record.language,
                                sortNum: value
                            }
                            dispatch({
                                type: `${namespace}/updateSortNum`,
                                payload: payload
                            })
                        } else {
                            message.error("请输入0 ~ 1000范围内的整数")
                        }
                    })}
                />

**Comment by micooz** [comment]
抽到一个方法里：

```js
function onCheck(e) {
  let value = e.target.value
  const reg = /(^(?:\d{1,3}|1000)$)/;
  if (reg.test(value)) {
    const payload = {
      productId: record.productId,
      language: record.language,
      sortNum: value
    }
    dispatch({
      type: ${namespace}/updateSortNum,
      payload: payload
    })
  } else {
    message.error("请输入0 ~ 1000范围内的整数")
  }
}

return (
  <Input
    defaultValue={text}
    key={record.productId + record.language}
    size={1}
    onPressEnter={onCheck}
    onBlur={onCheck}
  />
);
```
