### ISSUE TITLE
antd-mobile broken with react-native 0.56.0

### ISSUE THREAD

**Issue by CodingPapi** [ant-design/ant-design-mobile#2712]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.1

### Environment
react-native cli ,, 'react-native init command'  created template project on Fedora 27

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
use 'react-native init projectname' to create a new react project that react-native dependence is 0.56.0.

use yarn add antd-mobile react-dom to setup antd-mobile Environment.

use WhiteSpace component in App.js

run react-native run-android

Red box shows up

### What is expected?
No crash

### What is actually happening?
Crashed for output:
Invariant Violation: View config not found for name div

**Comment by hermanthotan** [comment]
I have this issue after upgrade react-native to latest one.
How you solved the issue "View config not found for name div"

**Comment by CodingPapi** [comment]
@hermanthotan replace with https://github.com/ant-design/ant-design-mobile-rn
 newest rn will crash ant-design-mobile
