### ISSUE TITLE
picker的change事件能不能返回label值

### ISSUE THREAD

**Issue by 1067011734** [ant-design/ant-design-mobile#2713]
picker的children组件默认是List.item,而我目前需要自定义组件，遗憾的是回调函数只返回value值，能不能同时返回label和value值？非常感谢。

**Comment by jogasa** [comment]
同问... 目前也碰到同样的问题，需要取label的值，却不知道怎样可以取到

**Comment by ziluo** [comment]
嗯，可以把`label`作为第二个参数返回，放到`2.3.x`做掉

**Comment by YDJSZY** [comment]
这个是非常非常常见的需求吧，选中就应该返回value和label或者提供自定义返回的函数吧

**Comment by themevan** [comment]
现在有方法了吗？同样有这个需求

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
