### ISSUE TITLE
运行报错 Unable to resolve module `react-dom` from `F:\xxxxx\node_modules\antd-mobile\lib\modal\alert.js`: Module does not exist in the module map

### ISSUE THREAD

**Issue by nfq6612** [ant-design/ant-design-mobile#2714]
版本：antd-mobile: "^2.1.8",
执行命令 react-native run-android 后准备启动app报如下错误，严重影响项目调试：
![tim 20180709151228](https://user-images.githubusercontent.com/21963633/42435853-8ca9a644-838a-11e8-847d-1658732bf169.png)

 Unable to resolve module `react-dom` from `F:\xxxxx\node_modules\antd-mobile\lib\modal\alert.js`: Module does not exist in the module map

**Comment by ziluo** [comment]
`npm install react react-dom --save`

**Comment by gogogous88** [comment]
rect-dom 会导致这个报错:Expected to find exactly one React Native renderer on DevTools hook
[https://forums.expo.io/t/error-message-when-trying-to-inspect-element/7574](url)
怎么解决这个问题呢？
