### ISSUE TITLE
 Module `react-dom` does not exist in the Haste module map

### ISSUE THREAD

**Issue by aoarashi1988** [ant-design/ant-design-mobile#2715]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.1

### Environment
OS： windows 7 , RN: 0.55.4 

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
1. yarn add antd-mobile
2. use Action-sheet component in anywhere of your project 
3. cd android ./gradlew installRelease

### What is expected?
installRelease succeeded

### What is actually happening?
installRelease failed

---
I checked the package.json of antd-mobile module, the 'react-dom' is in the devDependencies list , so I consider it as a develop dependency.  But in fact , when I try to make a release APK, it still require the module, is that a bug or anything wrong? Or,  it is just  someting I mistake ?

**Comment by ziluo** [comment]
RN相关问题请移步：https://github.com/ant-design/ant-design-mobile-rn/issues
