### ISSUE TITLE
在2.2.2版本中使用less报错

### ISSUE THREAD

**Issue by Spicely** [ant-design/ant-design-mobile#2721]
![image](https://user-images.githubusercontent.com/10075622/42728813-7d64b2da-87f6-11e8-8559-2088a6813ac6.png)
![image](https://user-images.githubusercontent.com/10075622/42728815-91dcaf06-87f6-11e8-8bc1-c2f5d6c9f0ff.png)
我使用的是typescript +   ##create-react-app创建的项目

**Comment by ziluo** [comment]
使用`create-react-app`创建的项目默认不支持`less`，需要额外配置，如：https://segmentfault.com/a/1190000010162614

**Comment by Spicely** [comment]
@ziluo 首先在create-react-app中如果不支持less你引入后是不会报错的并不会影响代码运行，其次我这配置把antd-mobile还原到2.2.0版本是能正常运行的 除了需要修改type.d.ts的代码
