### ISSUE TITLE
Tabs.DefaultTabBar goToTab can't work

### ISSUE THREAD

**Issue by RayChristian** [ant-design/ant-design-mobile#2722]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
chrome

### Reproduction link
[https://mobile.ant.design/components/tabs-cn/](https://mobile.ant.design/components/tabs-cn/)

### Steps to reproduce
Tabs.DefaultTabBar goToTab can't work

### What is expected?
At a given time, tab automatically goes to another one, but Tabs.DefaultTabBar goToTab can't work.

### What is actually happening?
Tabs.DefaultTabBar goToTab can't work

**Comment by doxiaodong** [comment]
请提供一个最小的 demo 。

**Comment by RayChristian** [comment]
realize it in another way

**Comment by kevin611003** [comment]
@RayChristian  can you tell me how to do it?

**Comment by iamwangkj** [comment]
> have realized it in another way

How to do so that tab can go to another one when componentDidMount?
