### ISSUE TITLE
DatePicker 只要设置了maxDate、minDate 就会报错

### ISSUE THREAD

**Issue by LuHugo** [ant-design/ant-design-mobile#2724]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
系统：Mac OS X 10.13.6 , 浏览器版本：Chrome 67， react版本：16.4

### Reproduction link
[https://codepen.io/LuHugo/pen/YjqaOx](https://codepen.io/LuHugo/pen/YjqaOx)

### Steps to reproduce
在列表中使用DatePicker设置maxDate或者minDate ， 然后选择日期页面出现空白（在console里看已经报错）

### What is expected?
正确显示DatePicker

### What is actually happening?
无法显示DatePicker并且整个页面无法渲染二出现空白，console里显示了报错信息

**Comment by ziluo** [comment]
`maxDate`和`minDate`都必须是`Date`实例，即`new Date('2017-12-21')`这种写法
