### ISSUE TITLE
Popover组件支持完全受控模式

### ISSUE THREAD

**Issue by cpd0101** [ant-design/ant-design-mobile#2725]
- [ ] I have searched the [issues](https://github.com/ant-design/antd-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以由应用程序自己控制Popover的显隐

### What does the proposed API look like?
visible属性是一个完全受控属性

**Comment by ziluo** [comment]
![image](https://user-images.githubusercontent.com/1201309/42928273-70b2a5d0-8b69-11e8-813d-31510223e349.png)

这个也一起考虑吧

**Comment by doxiaodong** [comment]
@likezero

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
