### ISSUE TITLE
Picker 动态加载数据时 ios下不显示

### ISSUE THREAD

**Issue by qqnp1100** [ant-design/ant-design-mobile#2726]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
ios 11.2.3 系统浏览器

### Reproduction link
[https://codepen.io/qqnp1100/pen/OwNrya](https://codepen.io/qqnp1100/pen/OwNrya)

### Steps to reproduce
看demo，滑动到第一列2014时开始加载数据

### What is expected?
请求数据时第二列正常显示

### What is actually happening?
第二列不显示，需要滑动一下才显示

---
在安卓和桌面浏览器中请求数据后均可正常显示，ios需要滑一下第二列才显示

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
