### ISSUE TITLE
antd-mobile stepper 无法触发事件

### ISSUE THREAD

**Issue by zouzhiwu** [ant-design/ant-design-mobile#2728]
![image](https://user-images.githubusercontent.com/37652554/42855821-d8ffb308-8a74-11e8-802a-15944aae0573.png)
点击左右的加减无法触发事件。

**Comment by zouzhiwu** [comment]
要在手机模式下才可以正常响应。

**Comment by jimmyshen007** [comment]
遇见相同问题 写了一个wrapper 自己传upHandler和downHandler进去 在wrapper里自行处理点击事件 官方可以考虑支持电脑浏览器

```javascript
import StepperAnt from 'antd-mobile/lib/stepper';
import Icon from 'antd-mobile/lib/icon';

class Stepper extends Component{

  onUpClick = (e) => {
    e.preventDefault();
    const {onChange} = this.props;
    const {value, step} = this.stepper.props;
    onChange(value+step);
  }

  onDownClick = (e) => {
    e.preventDefault();
    const {onChange} = this.props;
    const {value, step} = this.stepper.props;
    onChange(value-step);
  }

  render() {
    const { value, onChange } = this.props;
    return (
      <StepperAnt
        ref={node => this.stepper = node}
        value={value}
        onChange={onChange}
        showNumber
        upHandler={<Icon style={{width: 30, height: 30, padding: 8}} type="plus" size="xxs" onClick={this.onUpClick} />}
        downHandler={<Icon style={{width: 30, height: 30, padding: 8}} type="minus" size="xxs" onClick={this.onDownClick} />}
      />
    );
  }
}
```

**Comment by HUANGYAQI** [comment]
> 遇见相同问题 写了一个wrapper 自己传upHandler和downHandler进去 在wrapper里自行处理点击事件 官方可以考虑支持电脑浏览器
> 
> ```js
> import StepperAnt from 'antd-mobile/lib/stepper';
> import Icon from 'antd-mobile/lib/icon';
> 
> class Stepper extends Component{
> 
>   onUpClick = (e) => {
>     e.preventDefault();
>     const {onChange} = this.props;
>     const {value, step} = this.stepper.props;
>     onChange(value+step);
>   }
> 
>   onDownClick = (e) => {
>     e.preventDefault();
>     const {onChange} = this.props;
>     const {value, step} = this.stepper.props;
>     onChange(value-step);
>   }
> 
>   render() {
>     const { value, onChange } = this.props;
>     return (
>       <StepperAnt
>         ref={node => this.stepper = node}
>         value={value}
>         onChange={onChange}
>         showNumber
>         upHandler={<Icon style={{width: 30, height: 30, padding: 8}} type="plus" size="xxs" onClick={this.onUpClick} />}
>         downHandler={<Icon style={{width: 30, height: 30, padding: 8}} type="minus" size="xxs" onClick={this.onDownClick} />}
>       />
>     );
>   }
> }
> ```

貌似传不进去？ 它的源码里就覆盖了

**Comment by jimmyshen007** [comment]
> > 遇见相同问题 写了一个wrapper 自己传upHandler和downHandler进去 在wrapper里自行处理点击事件 官方可以考虑支持电脑浏览器
> > ```js
> > import StepperAnt from 'antd-mobile/lib/stepper';
> > import Icon from 'antd-mobile/lib/icon';
> > 
> > class Stepper extends Component{
> > 
> >   onUpClick = (e) => {
> >     e.preventDefault();
> >     const {onChange} = this.props;
> >     const {value, step} = this.stepper.props;
> >     onChange(value+step);
> >   }
> > 
> >   onDownClick = (e) => {
> >     e.preventDefault();
> >     const {onChange} = this.props;
> >     const {value, step} = this.stepper.props;
> >     onChange(value-step);
> >   }
> > 
> >   render() {
> >     const { value, onChange } = this.props;
> >     return (
> >       <StepperAnt
> >         ref={node => this.stepper = node}
> >         value={value}
> >         onChange={onChange}
> >         showNumber
> >         upHandler={<Icon style={{width: 30, height: 30, padding: 8}} type="plus" size="xxs" onClick={this.onUpClick} />}
> >         downHandler={<Icon style={{width: 30, height: 30, padding: 8}} type="minus" size="xxs" onClick={this.onDownClick} />}
> >       />
> >     );
> >   }
> > }
> > ```
> 
> 貌似传不进去？ 它的源码里就覆盖了

你试一下就知道了 他其实还传了 {...restProps} 是从上层传下来的 可以重新覆盖upHandler和downHandler

**Comment by seeya** [comment]
我也遇到了支个问题。使用一个wrapper不是很好，点加减的时候会增加两次。
因为stepper在mobile上没有问题，我就直接用了 touch emulator, https://github.com/hammerjs/touchemulator.

**Comment by jimmyshen007** [comment]
@seeya 我也修改了一下用wrapper的方法 不在StepperAnt里添加onChange就可以避免触发两次了。当然用touch emulator可以
