### ISSUE TITLE
 Modal.prompt 组件在钉钉端， ios 11 上，input 框无法聚焦且click失效

### ISSUE THREAD

**Issue by imink** [ant-design/ant-design-mobile#2730]
- [ ] I have searched the [issues](https://github.com/ant-design/antd-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
钉钉最新客户端 4.5.3， ios 11.4、 ios 11.2 均有

### Reproduction link
[https://mobile.ant.design/components/modal-cn/#components-modal-demo-alert](https://mobile.ant.design/components/modal-cn/#components-modal-demo-alert)

### Steps to reproduce
钉钉直接扫码官方的 demo，选择 Modal.prompt 的demo，尝试输入

### What is expected?
自动focus，键盘呼出，click有相应

### What is actually happening?
无 focus，键盘不呼出，click 会失效

---
目前确定和 ios 11 引入的新功能和 fastclick 有冲突，但是同样的页面，在支付宝客户端以及safari下，都没有click失效的问题，及时加入了 fastclick 补丁包 http://web.npm.alibaba-inc.com/package/@alipay/xmas-fastclick， 钉钉下依然有问题

**Comment by 349989153** [comment]
@imink https://www.jianshu.com/p/5b578e656966

**Comment by likezero** [comment]
有解决方案吗？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
