### ISSUE TITLE
公司已用这套组件，开发H5App,现在想入住支付宝小程序，是否能复用，还是要重写

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design-mobile#2731]

**Comment by quentinyang** [comment]
支付宝小程序架构和H5是有区别的，所以目前antdmobile无法直接支持小程序。如果想用小程序，还是得重新开发。
但是，antdmobile有考虑对接支付宝小程序，目前正在规划中。有新消息我们会第一时间通知大家。
谢谢。

**Comment by ksh033** [comment]
@quentinyang 好的谢谢.持续关注
