### ISSUE TITLE
how to use Accordion in Tabs Component

### ISSUE THREAD

**Issue by lhwu** [ant-design/ant-design-mobile#2732]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
in codepen for test, not in wechat-page

### Reproduction link
[https://codepen.io/lhwu/pen/QBKQmE?editors=0010](https://codepen.io/lhwu/pen/QBKQmE?editors=0010)

### Steps to reproduce
1、click the third tab
2、click the second tab

### What is expected?
1、can show content1, content2, content3 in normal
2、switch tab，the accordion should be close

### What is actually happening?
1、can not show content1, content2 like a drop-down list 
2、change tab, the accordion is open

---
the third tab should like a drop-down list, and the page show different data list

**Comment by doxiaodong** [comment]
暂时不支持这么使用， 这个具体点想做成什么？

**Comment by lhwu** [comment]
类似微信二级菜单那种，一级菜单下存在多个二级菜单，不过菜单位置在顶部

**Comment by doxiaodong** [comment]
https://raw.githubusercontent.com/doxiaodong/react-native-smart-list/master/snap.png  你是想要这样的吧，暂时没有，你可以配合 tabBar 实现一个~

**Comment by Pneumatic95** [comment]
我也遇到这个问题，并排的手风琴样式不正确

**Comment by lhwu** [comment]
替换方式，还是可以的。
