### ISSUE TITLE
有官网使用的演示DEMO的代码工程吗？

### ISSUE THREAD

**Issue by cesar-blog** [ant-design/ant-design-mobile#2733]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
想用antd mobile 和 Dva 一起做个脚手架，所以询问下有没有官网DEMO（https://mobile.ant.design/kitchen-sink/）的项目代码！谢谢

### What does the proposed API look like?
如上！

**Comment by doxiaodong** [comment]
官网的代码就在 这个 repo 里，你clone 下来 npm start 就可以看到

**Comment by ybning** [comment]
#2679 
+1

**Comment by likezero** [comment]
脚手架暂时没有，本仓库有独立组件的示例代码。在每个组件的readme.md里面。官网也能看到示例代码
