### ISSUE TITLE
react-dom cause a issue 

### ISSUE THREAD

**Issue by gogogous88** [ant-design/ant-design-mobile#2734]
react-dom 导致了这个报错:
Expected to find exactly one React Native renderer on DevTools hook
链接：
[https://forums.expo.io/t/error-message-when-trying-to-inspect-element/7574](url)
请问，怎么解决这个问题

**Comment by doxiaodong** [comment]
地址不正确，如果是  react-native 的请到  https://github.com/ant-design/ant-design-mobile-rn
