### ISSUE TITLE
InputItem的type为money时，如果InputItem在最底部，将会被完全遮挡，有何解决办法？

### ISSUE THREAD

**Issue by hst-Sunday** [ant-design/ant-design-mobile#2737]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
IOS11.4.1，chrome最新版

### Reproduction link
[http://antd-mobile.gitee.io/components/input-item-cn/](http://antd-mobile.gitee.io/components/input-item-cn/)

### Steps to reproduce
把InputItem放到界面最底部，设置它的type为money时，InputItem将会被money键盘完全遮挡

### What is expected?
像普通键盘那样输入框不被遮挡

### What is actually happening?
money键盘遮挡了输入框

**Comment by Catlc** [comment]
没人解决么 我也遇到了

**Comment by zhanglina1990** [comment]
我也遇到了

**Comment by zhanglina1990** [comment]
我暂时把存放键盘的容器的高度设成200了，这样后面的数据就可以滚动了，滚动之后显示出原来的输入框。有没有更好的办法？？？？

**Comment by Catlc** [comment]
还没有很好的解决方案么？？？

**Comment by linqiang007** [comment]
InputItem 新增了一个属性 `moneyKeyboardHeader ` ,可以把数字绑定在头部。  


可惜不支持多个money；

> 注意:使用 moneyKeyboardHeader 时，页面中只能有一个 type=money 的 InputItem
