### ISSUE TITLE
carousel cannot read property 'scrollTo' of null,跑马灯轮播着就会报这个错，到了其他页面也会报这个错

### ISSUE THREAD

**Issue by zhangqing1991** [ant-design/ant-design-mobile#2741]
![image](https://user-images.githubusercontent.com/28287510/43247975-ee1e9f18-90e8-11e8-8a07-189ef999e86d.png)

**Comment by doxiaodong** [comment]
RN 的问题请到 https://github.com/ant-design/ant-design-mobile-rn 谢谢
