### ISSUE TITLE
不能在Android Gradle构建工具3.1.3构建通过。

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [ant-design/ant-design-mobile#2744]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
RN16.3.1，com.android.tools.build:gradle:3.1.3

### Reproduction link
[http://xiandedanteng.com/我确定没有必要，因为这是个很常见的问题](http://xiandedanteng.com/我确定没有必要，因为这是个很常见的问题)

### Steps to reproduce
把com.android.tools.build:gradle升级到3.1.3及以上。

### What is expected?
当然是assembleRelease通过咯，这些问题问的太傻

### What is actually happening?
error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..

连截图上传都不支持还要求同用这破玩意儿上传反馈也是够蠢的了，明明issue就足够好用了。

![image](https://user-images.githubusercontent.com/12682063/43264538-0ab00cc2-9119-11e8-837c-dfb05f8cd01d.png)

---
就是各种图标资源，在新版本上要求很严格，不能通过编译。顺便，除了你们这个仓库自带的图标外，这条依赖里也有这样的图标："react-native-camera-roll-picker": "^1.2.1"。
![image](https://user-images.githubusercontent.com/12682063/43264680-5a49631e-9119-11e8-90a9-c8c8de6d5ce4.png)

**Comment by zhengxiaoyao0716** [comment]
[这里可以参考](https://github.com/react-navigation/react-navigation/issues/3097)

**Comment by doxiaodong** [comment]
@zhengxiaoyao0716  https://github.com/ant-design/ant-design-mobile-rn RN 的问题现在已经拆出去了。 @warmhug
