### ISSUE TITLE
imagePicker 上传图片报错

### ISSUE THREAD

**Issue by HeZai** [ant-design/ant-design-mobile#2746]
描述：
上传下面的图片报错
![testforupload](https://user-images.githubusercontent.com/18695195/43298076-1abefe7a-9187-11e8-86a6-b53a4d796fff.jpeg)

报错信息：
<img width="518" alt="qq20180727-102444 2x" src="https://user-images.githubusercontent.com/18695195/43298138-53e11558-9187-11e8-846f-4fbed8a0014e.png">

**Comment by HeZai** [comment]
version: 2.1.9
Environment: all

**Comment by doxiaodong** [comment]
@skidxjq
