### ISSUE TITLE
modal 的蒙层 onClick 回调失效

### ISSUE THREAD

**Issue by yipengmu** [ant-design/ant-design-mobile#2747]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.10(最新版2.2.2 也存在该问题)

### Environment
iOS,Web

### Reproduction link
[https://gw.alipayobjects.com/zos/rmsportal/oxsFCkdJWFkgCZcHqhOU.png](https://gw.alipayobjects.com/zos/rmsportal/oxsFCkdJWFkgCZcHqhOU.png)

### Steps to reproduce
使用modal时多封装了一层组件时，mask无法关闭（maskClosable =true），onClick 函数无法回调;

同样的代码，如果未对modal组件进行单独拆出来的话，回调事件可以正常响应。
通过对m-dialog的源码查看，怀疑是https://github.com/react-component/m-dialog/blob/master/src/Dialog.tsx#L205 这里事件冒泡判断时给拦截掉了

### What is expected?
在m-dialog内部，的onMaskClick的 e.target === e.currentTarget 逻辑 ，能否去掉或者cover掉如题的case

### What is actually happening?
对于将Modal组件额外封装后，onClose事件能够正常回调

---
使用modal时多封装了一层组件，应该是走到 下面的if判断 没进去的逻辑里了
onMaskClick = (e) => {
    if (e.target === e.currentTarget) {
      this.close(e);
    }
  }

**Comment by quentinyang** [comment]
2.2.2试下来是ok的

**Comment by yipengmu** [comment]
今天升级到2.2.2 ，ok了， 很奇怪的case
