### ISSUE TITLE
Picker  is closed that doesn't animate

### ISSUE THREAD

**Issue by HighWarmModel** [ant-design/ant-design-mobile#2749]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
macOs、chrome  67.0.3396.99

### Reproduction link
[https://codepen.io/EmperorOfEuropa/pen/EpwvGQ](https://codepen.io/EmperorOfEuropa/pen/EpwvGQ)

### Steps to reproduce
点击取消 遮罩 确定等都没有消失动画，直接不见了

### What is expected?
跟官网demo一样

### What is actually happening?
没有任何动画直接消失

---
create-react-app脚手架创建的react项目 直接安装引用 Picker或DatePicker 然后点击取消、遮罩、确定都没有消失动画

**Comment by HighWarmModel** [comment]
> @HighWarmModel It's a compatible problem with React 16, u can have a try on this demo which is using React 15.5.4 https://codepen.io/anon/pen/WgyqdO?editors=0010

ok, thanks.

**Comment by puhahalx** [comment]
Why is React16 not supported yet,Also, clicking masks on react16.7 and antd-mobile2.2.11 doesn't turn off the picker component, and fastclick doesn't work
