### ISSUE TITLE
onClick无效

### ISSUE THREAD

**Issue by J-zin** [ant-design/ant-design-mobile#2750]
在使用tabBar后，所有页面被tabBar的浮层覆盖，onClick设置后点击无效，这个问题怎么解决

**Comment by doxiaodong** [comment]
请提供一个 可访问的 最小 demo ,方便我们排查

**Comment by thewindsword** [comment]
问题demo应该如下：
[DEMO](https://codesandbox.io/s/4wpmon7z2w)
由于官方示例中div样式设置的问题
`<div style={this.state.fullScreen ? { position: 'fixed', height: '100%', width: '100%', top: 0 } : { height: 400 }}>`
问题应该是在直接复制官方示例之后导致的，需要人为修改div样式，应在文档上加以声明。
而且可能大部分人并不习惯于将页面相关路由全部放到`TabBar`组件来控制吧。

**Comment by Aledenn** [comment]
请问这个问题解决了吗

**Comment by doxiaodong** [comment]
如果要这样使用 TabBar 的话，请把 其他页面放在 tabbar 内

**Comment by J-zin** [comment]
你好 我还是不是很明白解决的方案是什么  我现在的一个新项目再次遇到这个问题了  问题和上面的demo一样  请问解决方法是什么

**Comment by doxiaodong** [comment]
`style={{ position: 'fixed', height: '100%', width: '100%', top: 0 }}` 你把这段代码删掉 @J-zin

**Comment by doxiaodong** [comment]
给看一下 `TabBar` 那段的代码呀。正常是不占高度的

**Comment by J-zin** [comment]
@doxiaodong 
这是tabbr的代码
`import React from "react";
import propTypes from "prop-types";
import {withRouter} from "react-router-dom";
import {TabBar} from "antd-mobile";

class NavLinkBar extends React.Component {
  static propTypes = {
    data: propTypes.array.isRequired
  };

  render() {
    const navList = this.props.data.filter((v) => v.type === "linkBar");
    const {pathname} = this.props.location;
    return (
      <TabBar>
        {navList.map((v) => (
          <TabBar.Item
            key={v.path}
            title={v.text}
            icon={{uri: require(`./img/${v.icon}.png`)}}
            selectedIcon={{uri: require(`./img/${v.icon}-active.png`)}}
            selected={pathname === v.path}
            onPress={() => {
              this.props.history.push(v.path);
            }}
          />
        ))}
      </TabBar>
    );
  }
}

export default withRouter(NavLinkBar);`

css如下：
`.am-tab-bar {
    position: fixed;
	bottom: 0;
	width: 100%;
	height:auto;
}

.page-content{
    z-index: 10;
	padding:0px 2px 45px 2px;
}`

**Comment by J-zin** [comment]
@doxiaodong 
你好，这是tabbar的代码
```javascript
import React from "react";
import propTypes from "prop-types";
import {withRouter} from "react-router-dom";
import {TabBar} from "antd-mobile";

class NavLinkBar extends React.Component {
  static propTypes = {
    data: propTypes.array.isRequired
  };

  render() {
    const navList = this.props.data.filter((v) => v.type === "linkBar");
    const {pathname} = this.props.location;
    return (
      <TabBar>
        {navList.map((v) => (
          <TabBar.Item
            key={v.path}
            title={v.text}
            icon={{uri: require(`./img/${v.icon}.png`)}}
            selectedIcon={{uri: require(`./img/${v.icon}-active.png`)}}
            selected={pathname === v.path}
            onPress={() => {
              this.props.history.push(v.path);
            }}
          />
        ))}
      </TabBar>
    );
  }
}

export default withRouter(NavLinkBar);

```
css如下
```css
.am-tab-bar {
    position: fixed;
	bottom: 0;
	width: 100%;
	height:auto;
}

.page-content{
    z-index: 10;
	padding:0px 2px 45px 2px;
}
```

**Comment by J-zin** [comment]
@doxiaodong 
height 我尝试改过成45px  但是失效了

**Comment by Aledenn** [comment]
@J-zin 
```
 /* 
.am-tab-bar{
    position:fixed;
    bottom:0;
    width: 100%;
} */
...
把这段注释掉就好了，有点忘记了

**Comment by J-zin** [comment]
@Aledenn 
注释调确实可以 如果注释掉的话  但是问题是我想固定在底部改怎么办呢

这是未注释掉的情况下的图片，tabbar确实把所有页面都覆盖了
![1536216463 1](https://user-images.githubusercontent.com/30493522/45140186-95e0d600-b1e4-11e8-97c9-19379e1415a5.png)

**Comment by J-zin** [comment]
@Aledenn 
@doxiaodong 
这是注释后的效果，虽然没有覆盖整个页面，但是navbar无法固定到底部
![1536216941 1](https://user-images.githubusercontent.com/30493522/45140343-0e479700-b1e5-11e8-9af3-d53860fbaa71.jpg)

**Comment by doxiaodong** [comment]
你把你加的这段样式权重加大，高度设置为 'auto' 这样的。

**Comment by Aledenn** [comment]
@J-zin 
我好像是这么解决的,我加了个div包裹了一下，然后把CSS那里注释掉
```
    return (
      <div style={{ position: "fixed", width: "100%", bottom: 0 }}>
        <TabBar>
 
        </TabBar>
      </div>
    );
```

**Comment by J-zin** [comment]
@doxiaodong 
@Aledenn 
啊。。解决了，非常感谢
