### ISSUE TITLE
IPHONE 6 IOS8.2 Modal 组件淡入淡出背景会闪烁

### ISSUE THREAD

**Issue by doxiaodong** [ant-design/ant-design-mobile#2755]
http://antd-mobile.gitee.io/components/modal-cn/ 手机扫一下即可

**Comment by lcyh** [comment]
我的也是,modal和modal.alert弹窗会出现闪屏的bug,请问怎么解决

**Comment by xyy721** [comment]
> 我的也是,modal和modal.alert弹窗会出现闪屏的bug,请问怎么解决
解决了吗？遇到同样的问题

**Comment by lcyh** [comment]
没有,自己封装了 弹窗组件






------------------ 原始邮件 ------------------
发件人: "xyy721"<notifications@github.com>; 
发送时间: 2019年7月25日(星期四) 中午1:40
收件人: "ant-design/ant-design-mobile"<ant-design-mobile@noreply.github.com>; 
抄送: "不同的选择"<173408798@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ant-design/ant-design-mobile] IPHONE 6 IOS8.2 Modal 组件淡入淡出背景会闪烁 (#2755)



 
我的也是,modal和modal.alert弹窗会出现闪屏的bug,请问怎么解决
 解决了吗？遇到同样的问题
