### ISSUE TITLE
antd-mobile DatePicker日期选择组件iios低于8.1.1（包含8.1.1）不可使用

### ISSUE THREAD

**Issue by chen12538** [ant-design/ant-design-mobile#2756]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
微信公众号

### Reproduction link
[https://wechat.wuuxiang.com/i5xwxplus/cards/gxqbjky/center/index.html](https://wechat.wuuxiang.com/i5xwxplus/cards/gxqbjky/center/index.html)

### Steps to reproduce
点击链接关注公众号故乡情北京烤鸭，点击加入会员，点击请输入生日

### What is expected?
在ios版本为8.1.1时能正常使用

### What is actually happening?
不可使用

**Comment by doxiaodong** [comment]
这个 demo 可以简单一点么，还要加入会员。

**Comment by doxiaodong** [comment]
@skidxjq
