### ISSUE TITLE
荣耀手机的华为浏览器打不开官方实例listView。在实际项目中，listview无法上下滚动。

### ISSUE THREAD

**Issue by benfang928** [ant-design/ant-design-mobile#2757]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
EMUI 8.0.0 浏览器版本 4.0.181

### Reproduction link
[https://mobile.ant.design/components/list-view-cn/](https://mobile.ant.design/components/list-view-cn/)

### Steps to reproduce
打不开官方实例 listView， 一直在加载。
应用到项目中后，listView使用局部容器时无法上下滚动

### What is expected?
能加载
能上下滚动

### What is actually happening?
无法加载
无法上下滚动

---
listView结合了tab

**Comment by doxiaodong** [comment]
@KgTong

**Comment by sprout-echo** [comment]
Samsung mobile phone is also

**Comment by PullToRefreshSample** [comment]
+1 安卓手机 vivo X7 结合tabs,只能渲染首屏数据，下滑卡住

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
