### ISSUE TITLE
Tabs 和 ListView组合使用时，可否在左右滑动切换Tab的时候，禁止ListView的上下滑动

### ISSUE THREAD

**Issue by tequilaNiu** [ant-design/ant-design-mobile#2759]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tabs 和 ListView组合使用时，可否在左右滑动切换Tab的时候，禁止ListView的上下滑动。
或者listView上下滑动时，禁止Tabs useOnPan=false 时的左右滑动？解决过于灵活，而且版面不好看的问题。

### What does the proposed API look like?
onSwipe: (e) => {}

**Comment by acmilank22** [comment]
+1

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
