### ISSUE TITLE
Drawer异常，无法排错

### ISSUE THREAD

**Issue by sniperyan** [ant-design/ant-design-mobile#276]
#### 本地环境

- antd-mobile 版本：0.8.4
- 操作系统及其版本：win7
- 浏览器及其版本：chrome 50.0.2661.75 (64-bit)

#### 你做了什么？

跑官网示例代码 drawer

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

nav的按钮无法点击，无法弹出抽屉，手动修改抽屉的state为true使抽屉弹出，单击空白区域报错，说open没有定义，打断点查看后发现很奇怪的一个现象，onOpenChange里的this不是组件名称，而是一个object，Open变成了该object的属性，而不是在state下面（唯一和官网区别的是我用了es6的extend components创建的class）

#### 可重现的在线演示

本地跑的，没上线

**Comment by warmhug** [comment]
> onOpenChange里的this不是组件名称

用 es6 需要 bind this
