### ISSUE TITLE
I found a bug ,please fix it

### ISSUE THREAD

**Issue by LastStranger** [ant-design/ant-design-mobile#2760]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
chrome,版本 67.0.3396.99（正式版本） （64 位）

### Reproduction link
[https://mobile.ant.design/components/pull-to-refresh-cn/](https://mobile.ant.design/components/pull-to-refresh-cn/)

### Steps to reproduce
in this page, if you pull to the end, and pull up, you will find the simulator drop down, 在这个页面下，下滑到浏览器最下面，然后向上划，你会发现那个模拟器掉下来了，尤其是你往上缓慢滑的时候，

### What is expected?
normal expect

### What is actually happening?
the simulator drop down,

---
the pullToRefresh component  is so  hard to use, it is so shity

**Comment by LastStranger** [comment]
![image](https://user-images.githubusercontent.com/29811304/43814320-511778de-9afc-11e8-8567-9d1cc40a8d90.png)
can't you see the problem?

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
