### ISSUE TITLE
Core-js is included via dependencies

### ISSUE THREAD

**Issue by mlucool** [ant-design/ant-design-mobile#2766]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
Browser

### Reproduction link
[https://github.com/react-component/tooltip/blob/master/package.json#L44](https://github.com/react-component/tooltip/blob/master/package.json#L44)

### Steps to reproduce
Build any antd mobile project with a popover and core-js is included in the bundle from the dependency on tooltip (and other) libraries that compile with babel-runtime.

### What is expected?
Developers choose define what is in their supported browsers and a strategy for polyfilling

### What is actually happening?
Core-js is included. This adds ~15kb cost for using popover in environments that support ES6.

**Comment by doxiaodong** [comment]
babel-runtime 依赖 core-js , 目前 antd-mobile 的 polyfill 需要 babel-runtime 来做. 不过这个我倒是建议让用户来做 @ziluo  你觉得呢

**Comment by doxiaodong** [comment]
@paranoidjk @warmhug  你们看一下这个？

**Comment by mlucool** [comment]
Hi,

Any update on this?

**Comment by wangmingxu** [comment]
我也遇到了这个问题，我目前的暂时解决方法是在webpack alias把babel-runtime映射到@babel/runtime，当然最好是希望官方能解决这个问题

**Comment by chen86860** [comment]
组件库专有的 Polyfil l应该在内部引入，除此之外应该由引入的应用去做 Polyfill。建议下次更新时去掉一些通用的 Polyfill :D
