### ISSUE TITLE
Modal不能主动触发

### ISSUE THREAD

**Issue by banli17** [ant-design/ant-design-mobile#2770]
点击按钮可以触发，好像是只能再组件内触发。比如 ajax返回啥的时候，我想触发一下，就不行。ajax.js是个公共方法。

**Comment by doxiaodong** [comment]
请提供最小的 可访问的 demo 或 repo

**Comment by doxiaodong** [comment]
@likezero

**Comment by likezero** [comment]
通过状态可以控制modal的显示、隐藏与否
