### ISSUE TITLE
当我点击超过一定数目的时候，我要禁用checkout要怎么弄

### ISSUE THREAD

**Issue by MaZhengA** [ant-design/ant-design-mobile#2771]

**Comment by doxiaodong** [comment]
请描述清楚一些，最好提供可访问的例子，使用什么组件等

**Comment by MaZhengA** [comment]
就是说我选了10个checkbox，但是到11个的时候我点了checkbox，就不能再点了，也就是选了10个就要把复选框禁用，要怎么弄，我用原生给他解决了，不过还是希望可以使用checkbox组件来做会优雅

**Comment by doxiaodong** [comment]
你这个应该也是一个列表吧，到10个的时候把其他未操作的像设置为 disabled 呀
