### ISSUE TITLE
Adding individual read only prop for input element in Stepper

### ISSUE THREAD

**Issue by antiphoton** [ant-design/ant-design-mobile#2772]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The `<Stepper>` of current version allows `<input>` element to get focus. However, showing the keyboard significantly reduces viewport size, and then moving some page content out of user's vision.

Is it possible to add an individual read only prop for the `<input>` element? This allows user to change `<Stepper>` value by clicking the up and down buttons, and forbids the `<input>` element to show keyboard.

### What does the proposed API look like?
Add a new prop to Stepper

```javascript
propTypes = {
  ...,
  inputCanGetFocus?: bool,
}
defaultProps = {
  ...,
  inputCanGetFocus: true,
}
```

For implementation, changing [this line](https://github.com/react-component/m-input-number/blob/71e3f9cffb25d75cbf12c17c144ba8cc87e25f8c/src/index.tsx#L205) to 
```javascript
readOnly={props.readOnly || !props.inputCanGetFocus}
```

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
