### ISSUE TITLE
PickerView's data prop does not support one-dimension array

### ISSUE THREAD

**Issue by Moicen** [ant-design/ant-design-mobile#2775]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
Mac OS 10.13.6, Chrome 68.0.3440.106

### Reproduction link
[https://codepen.io/anon/pen/bjJjxp](https://codepen.io/anon/pen/bjJjxp)

### Steps to reproduce
1. Copy the demo code of  PickerView on official doc site, then modify the `seasons` to one dimension array
   
     ```
    [
        { label: '春',value: '春'},
        { label: '夏',value: '夏'}
    ]

2. view the demo

### What is expected?
should display an picker view just like  demo

### What is actually happening?
nothing display, error on console: 
PickerView.js:40 Uncaught TypeError: col.map is not a function
    at PickerView.js:40
    at Array.map (<anonymous>)
    at PickerView._this.getCol (PickerView.js:36)
    at PickerView.render (PickerView.js:66)
![image](https://user-images.githubusercontent.com/3773928/44098115-e7d55d12-a011-11e8-8c4d-878c21f4c8d2.png)



---
Under official doc's description, `PickerView`'s `data` prop can be `Array<{value, label}> / Array<Array<{value, label}>>`，so  `[{},{}]` should be  effective as data source.


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by lirenhao** [comment]
这个问题在2.3.5中也出现了

**Comment by lirenhao** [comment]
> 这个问题在2.3.4中也出现了

（我真的很想问候你们，你们的文档真的是垃圾啊）我使用Picker是将cascade参数设置为false时，data参数只能传递Array<Array<{value, label}>>类型的数据，如果data的类型是Array<{value, label}>时，就会报col.map is not a function（你们是真的想做好antd-mobile吗，再次问候）

**Comment by qduck** [comment]
+1
