### ISSUE TITLE
InputItem's defaultValue is not the same as React's defaultValue？

### ISSUE THREAD

**Issue by mingenesis** [ant-design/ant-design-mobile#2776]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
web

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
目前InputItem的defaultValue只有在初始化的时候才会赋值到value上，而React的defaultValue逻辑是defaultValue变化时，value也能对应作出变化。

### What is expected?
希望能与React的逻辑一致

### What is actually happening?
目前InputItem的defaultValue只有在组件componentDidMount的时候才会赋值给value，如果在componentDidUpdate处监听defaultValue变化，如果变化就赋值给value，就能达到与React一致的逻辑

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
