### ISSUE TITLE
npm install antd-mobile 失败了，怎么办

### ISSUE THREAD

**Issue by showtan001** [ant-design/ant-design-mobile#2778]
环境  mac
npm 版本 6.3.0
85 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '....x","rc-tools":"4.x",'
85 verbose stack     at JSON.parse (<anonymous>)
85 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
85 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
85 verbose stack     at <anonymous>
85 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
86 verbose cwd /Users/pro/Documents/pro/jordina
87 verbose Darwin 17.6.0
88 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "antd-mobile" "--save"
89 verbose node v8.11.3
90 verbose npm  v6.3.0
91 error Unexpected end of JSON input while parsing near '....x","rc-tools":"4.x",'
92 verbose exit [ 1, true ]

**Comment by likezero** [comment]
尝试使用tnpm安装，npm在国内不稳定
