### ISSUE TITLE
Picker、DatePicker的web组件在手机上，在滑动界面时不时滑动完后又自动回到初始值的位置，但是点确定后是滑动过的值

### ISSUE THREAD

**Issue by wq1308786830** [ant-design/ant-design-mobile#2779]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
ios11，Android8，Android7。微信内置浏览器。react16.2、dva2.1.0

### Steps to reproduce
在滑动界面，滑动任意一列

### What is expected?
期望滑动后停留在滑动最后的位置，且点击确定后选定的值是最后滑动停留位置的值

### What is actually happening?
实际结果是：偶现滑动后又返回到最初的位置，且点击确定后选定的值是最后滑动位置的值不是最后停留位置的值

**Comment by wq1308786830** [comment]
这个比较急，有人来看看嘛？

**Comment by SynChron1zed** [comment]
@sorrycc

**Comment by wq1308786830** [comment]
@sorrycc https://share.weiyun.com/51etqZi

**Comment by wq1308786830** [comment]
我看到rmc-picker/lib/Picker.js 的componentWillReceiveProps生命周期里，在nextProps.selectedValue变化第一次setState后nextProps.selectedValue又变成初始值又执行了一次setState导致回弹的现象，不知道该怎么解决好一点 @cncolder

**Comment by jackliuqh** [comment]
请问您解决这个问题了吗？

**Comment by qhxin** [comment]
同样遇到这个问题

**Comment by YUFENGWANG** [comment]
一样的问题。。。

**Comment by violetqqy** [comment]
同样遇到这个问题 请问是怎么解决的 @wq1308786830

**Comment by jackliuqh** [comment]
@YUFENGWANG 可以设个中间变量
![image](https://user-images.githubusercontent.com/24776966/45340076-ac61a580-b5c7-11e8-8596-e5c4304b0253.png)
滑动时给datapicker的value设置中间变量，最终点确定的时候，调用onChange设置确定后的value

**Comment by YUFENGWANG** [comment]
@jackliuqh 我之前的原因是因为组件重渲染了，后来解决掉了

**Comment by galenjiang** [comment]
也碰到这个问题了，很严重的样子了

**Comment by galenjiang** [comment]
> @jackliuqh 我之前的原因是因为组件重渲染了，后来解决掉了
@YUFENGWANG 确实是组件rerender了，我也用pureComponent解决了这个问题。我的情况是用redux包了一层，会出现这个问题。一般情况下不会。我没有搞清楚的是，为什么Picker组件的状态变化能让父组件触发render呢？

**Comment by wq1308786830** [comment]
> 同样遇到这个问题 请问是怎么解决的 @wq1308786830

我发现是因为我的页面重新调用了render所以页面会重新渲染，然后自然会回到初始值。
解决的方法是：将时间组件单独使用，让父组件的state不会影响子组件的state，就不会重新render

**Comment by chengOnLine** [comment]
我也遇到这个问题了，而且不知道怎么复现。
