### ISSUE TITLE
如何定制自己的UI风格

### ISSUE THREAD

**Issue by goldingking** [ant-design/ant-design-mobile#278]
#### 本地环境

- antd-mobile 版本：0.8.x
- 操作系统及其版本：android 4.0+
- 浏览器及其版本：webkit

#### 你做了什么？

引入 antd-mobile 的 Button，但是button的样式不能修改，只能使用预定的那几种，希望可以控制button的大小，圆角的度数，背景色，按下效果，文字颜色等属性，该如何做？

#### 你期待的结果是：
可以自己定义button的一些属性，覆盖默认的属性，比如我可以单独定义button背景色为红色，其他属性还保留原来的样子。

#### 实际上的结果：
不能定制。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/components/style/themes/default.less#L114-L118

**Comment by pingan1927** [comment]
https://github.com/ant-tool/atool-build/issues/176

**Comment by pingan1927** [comment]
for example:
`"theme": "./node_modules/kb-merchant-theme/index.js",`在package.json做配置
