### ISSUE TITLE
antd-mobile 引入组件样式报错，.encoded-svg-background('image_picker_delete');是报错的源头，请问这个怎么解决，你们有没有遇到过呢

### ISSUE THREAD

**Issue by shenruiling** [ant-design/ant-design-mobile#2783]
<img width="770" alt="_20180817144856" src="https://user-images.githubusercontent.com/42233515/44251882-b09add00-a22c-11e8-836f-0eaaf98b91a2.png">

**Comment by alun-430** [comment]
请问这个问题解决了吗？
我也出现了这个问题。
有一种解决方式不是很完美：“style”:  "true", 给true加个双引号，但是自定义的主题就会失效了
[ // 按需加载组件，style 必须是 true, 可以加载less文件,
      "import", {
      libraryName: "antd-mobile",
      "libraryDirectory": "lib",
      "style": true
    }
    ],

所以同问有没有更好的解决方式

**Comment by PeakTan** [comment]
有人出来回答吗

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
