### ISSUE TITLE
modal.alert 点击蒙版报错

### ISSUE THREAD

**Issue by qinshihuangwc** [ant-design/ant-design-mobile#2787]
![image](https://user-images.githubusercontent.com/37623746/44323020-af62ed80-a482-11e8-971c-78c9f751602b.png)

在modal.alert 中如何捕捉到点击蒙版事件

**Comment by qinshihuangwc** [comment]
![image](https://user-images.githubusercontent.com/37623746/44617041-985f3980-a88e-11e8-9015-e58c0817ca40.png)
已解决

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
