### ISSUE TITLE
ant design modile picker component isSupport value and label format   ????

### ISSUE THREAD

**Issue by aiqin-bao** [ant-design/ant-design-mobile#2789]
数据源中对的data 是否只单单支持 label value 的属性 ？？

是否可以支持format ？？？

**Comment by oMaten** [comment]
@aiqin-bao provide a live example to reproduce the problem?

**Comment by aiqin-bao** [comment]
select的中的data 是不是只能以label 和value 的字段 ？

**Comment by zhaoqize** [comment]
@aiqin-bao 同样的问题，请问你是怎么处理的？
