### ISSUE TITLE
ListView 自定义容器的吸顶问题

### ISSUE THREAD

**Issue by tequilaNiu** [ant-design/ant-design-mobile#2790]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在自定义容器里面的吸顶功能，react-sticky 是可以在相对容器里面吸顶的```<Sticky relative={true}>```，此时有N个```<Sticky>``` 都放在一个<StickyContainer>内部时，可以实现相对容器的吸顶，例如：
```
<StickyContainer style={{height: '500px', overflowY: 'auto'}}>
{
    [1,2,3,4,5].map(i => (
        <Sticky relative={true}>
    ))
}
</StickyContainer>
```
但是在我们ListView组件里面，由于Sticky 和 StickyContainer分别设置在renderSectionHeader和renderSectionWrapper中，这样就会导致有多个StickyContainer。
我还分别尝试了将StickyContainer放在renderBodyComponent中或者包裹在```<ListView>```组件外，都有问题。

### What does the proposed API look like?
renderBodyComponent: () => (
  <StickyContainer>{this.props.children}</StickContainer>
)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
