### ISSUE TITLE
ListView 组件horizontal属性不生效

### ISSUE THREAD

**Issue by yefengxing** [ant-design/ant-design-mobile#2793]

**Comment by zhaiyjgithub** [comment]
same issue.

**Comment by 750973092** [comment]
me to

**Comment by 750973092** [comment]
@yefengxing 这个是BUG来的，拿官方的DEMO然后加个horizontal={true}它不变横向滚动，这个需要是第二个项目都用到了，望下一版本修补

**Comment by pcegarra** [comment]
any news?

**Comment by conioX** [comment]
any news on this issue?

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by huanghly** [comment]
> 

升级到v5版本？ v5没有listview了

**Comment by awmleer** [comment]
噢 sorry 我之前关 issue 的时候没有太看仔细，v5 目前的确不支持 ListView，而且未来大概率也不会做这样的一个组件，目前已经有的相关的组件是：List PullToRefresh InfiniteScroll，也就是说对于 ListView 的部分功能是有对应的新组件的，至于虚拟滚动，目前 v5 是没有提供这样的组件的，可以考虑用社区上的 react 虚拟滚动库
