### ISSUE TITLE
Grid with isCarousel props only show dot while using SegmentedControl and TabBar 

### ISSUE THREAD

**Issue by thewindsword** [ant-design/ant-design-mobile#2794]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
win10, chrome 68.0.3440.106,react 16.4.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ov4vpyo4q5)

### Steps to reproduce
1. click https://codesandbox.io/s/ov4vpyo4q5
2. click Life Tab
3. click Segment2
4. The Grid only show dot,then click button change some state.

### What is expected?
The Grid with isCarousel props should fully displayed.

### What is actually happening?
The Grid only show dot.

---
# zh-cn
##### Step to reproduce：
1. 点击进入示例 https://codesandbox.io/s/ov4vpyo4q5
2. 点击左边的TabBar.Item
3. 点击分段器的右边
4. 你将看到丢失宽度只显示dot的Grid组件（走马灯模式），通过任意的setState操作都可以让组件恢复正常

#### What is expected?
Grid组件（走马灯模式）应该正常展示。
#### What is actually happening?
Grid组件只显示了dot部分，丢失高度。

**Comment by The-Punk-and-The-Monk** [comment]
hi, have you solved the problem, running into the same problem : (

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
