### ISSUE TITLE
I can't open the  mobile-ant-design website in IOS9(SE) and IOS10(6plus), but it works in android and PC.

### ISSUE THREAD

**Issue by LastStranger** [ant-design/ant-design-mobile#2798]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
IOS

### Reproduction link
[https://mobile.ant.design/components/modal-cn/](https://mobile.ant.design/components/modal-cn/)

### Steps to reproduce
open the website on IOS device

### What is expected?
works fine

### What is actually happening?
only the title show up

---
about the modal component,  you guys said already fixed the "fix touch to scroll background page on iOS", but it wasn't, I can still scroll the background when I touch starting from the modal. This bug didn't show up in Android,  please fix it ASAP

**Comment by LastStranger** [comment]
here is my code,  the BUG("touch to scroll background page on iOS"), it still there, it never fixed;

import React from "react";
import { Modal, List, Button, WhiteSpace, WingBlank } from 'antd-mobile';

function closest(el, selector) {
    const matchesSelector = el.matches || el.webkitMatchesSelector || el.mozMatchesSelector || el.msMatchesSelector;
    while (el) {
        if (matchesSelector.call(el, selector)) {
            return el;
        }
        el = el.parentElement;
    }
    return null;
}

class InviteFriends extends React.Component {
    constructor() {
        super();
        this.state = {
            modal: false,
        };
    }
    showModal = (e) => {
        e.preventDefault(); // 修复 Android 上点击穿透
        this.setState({
            modal: true,
        });
    };
    onClose = () => {
        this.setState({
            modal: false,
        });
    };

    onWrapTouchStart = (e) => {
        // fix touch to scroll background page on iOS
        if (!/iPhone|iPod|iPad/i.test(navigator.userAgent)) {
            return;
        }
        const pNode = closest(e.target, '.am-modal-content');
        if (!pNode) {
            e.preventDefault();
        }
    };


    render() {
        return (
            <div className="invite-friends">
                <div>he</div>
                <Button onClick={(event) => this.showModal(event)}>basic</Button>
                <Modal
                    visible={this.state.modal}
                    transparent
                    maskClosable={false}
                    onClose={(e) => this.onClose(e)}
                    title="Title"
                    footer={[{ text: 'Ok', onPress: () => { console.log('ok'); this.onClose(); } }]}
                    wrapProps={{ onTouchStart: this.onWrapTouchStart }}
                >
                    <div style={{ height: 100, overflow: 'scroll' }}>
                        what we have lost will never be returned to us ,it's the real life<br />
                        what we have lost will never be returned to us ,it's the real life<br />
                        what we have lost will never be returned to us ,it's the real life<br />
                        what we have lost will never be returned to us ,it's the real life<br />
                        what we have lost will never be returned to us ,it's the real life<br />
                        what we have lost will never be returned to us ,it's the real life<br />
                    </div>
                </Modal>
            </div>
        )
    }
}

export default InviteFriends;

**Comment by likezero** [comment]
you need fastclick
