### ISSUE TITLE
tabs 的 prerenderingSiblingsNumber 有问题

### ISSUE THREAD

**Issue by jamieYou** [ant-design/ant-design-mobile#2799]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
node - v10.0.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l2k5qnk1pm)

### Steps to reproduce
tabs 组件的 prerenderingSiblingsNumber 设为 0时，从第一个 tab 切换到第二个 tab，这时候第一个 tab 对应的内容的组件不会触发更新，明明传递的props是新的。

### What is expected?
切换 tab 时，应该 alert(false) 然后 alert(true)

### What is actually happening?
切换 tab 时，只 alert(true)

---
我想切换 tab 时，让上一个 tab 的状态发生改变。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
