### ISSUE TITLE
引入之后提示没有改模块 但是在node_modules确实存在

### ISSUE THREAD

**Issue by yy-hh** [ant-design/ant-design-mobile#28]
#### 本地环境

- antd-mobile 版本：0.7.2
- 操作系统及其版本：osx EI Capitan
- 浏览器及其版本：谷歌 版本 51.0.2704.103 (64-bit)

#### 你做了什么？

import { Toast } from 'antd-mobile';
#### 你期待的结果是：
使用toast组件能正常调用

#### 实际上的结果：
报错 提示antd-mobile 模块不存在
Module not found: Error: Cannot resolve module 'antd-mobile' in /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/src/containers
resolve module antd-mobile in /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/src/containers
  looking for modules in /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules
    resolve 'file' antd-mobile in /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules
      resolve file
        /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile is not a file
        /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile.js doesn't exist
        /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile.jsx doesn't exist
    resolve 'file' or 'directory' /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile
      resolve file
        /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile is not a file
        /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile.js doesn't exist
        /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile.jsx doesn't exist
      resolve directory
        directory default file index
          resolve file index in /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile
            /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile/index doesn't exist
            /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile/index.js doesn't exist
            /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile/index.jsx doesn't exist
    resolve 'bower component' antd-mobile manifest files using [bower.json]
      resolve file
        /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/src/containers/bower_components/antd-mobile/bower.json doesn't exists
        /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/src/bower_components/antd-mobile/bower.json doesn't exists
        /Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/bower_components/antd-mobile/bower.json doesn't exists
        /Users/yangyangliang/apps/1mdata-frontend/bower_components/antd-mobile/bower.json doesn't exists
        /Users/yangyangliang/apps/bower_components/antd-mobile/bower.json doesn't exists
        /Users/yangyangliang/bower_components/antd-mobile/bower.json doesn't exists
        /Users/bower_components/antd-mobile/bower.json doesn't exists
        /bower_components/antd-mobile/bower.json doesn't exists
[/Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile.js]
[/Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile.js]
[/Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile.jsx]
[/Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile.jsx]
[/Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile/index]
[/Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile/index.js]
[/Users/yangyangliang/apps/1mdata-frontend/xlt-wechat-doctor/node_modules/antd-mobile/index.jsx]
 @ ./src/containers/sendDrug.js 39:18-40

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile#use-babel-plugin-antd

**Comment by tao2581** [comment]
查阅了相关问题，都是提到语法问题，下载官方示例跑通后，配置 antd和antd-mobile 共存，结果一样报错，最终发现是 babel-plugin-antd 版本不对，默认安装的是0.4.1 ， 共存问题在0.5.1才被支持，升级后解决问题 ，供大家参考 少走弯路
npm install babel-plugin-antd@0.5.1
