### ISSUE TITLE
引用list、radio组件报错 求解

### ISSUE THREAD

**Issue by zhenzp** [ant-design/ant-design-mobile#2802]
/node_modules/antd-mobile/lib/list/style/index.less
Module build failed: 

      margin-left: @h-spacing-md;
      .encoded-svg-background('right');
    ^
Inline JavaScript is not enabled. Is it set in your options?
      in /test/node_modules/antd-mobile/lib/list/style/index.less (line 181, column 6)

报这个错 请问是什么问题 多谢

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
