### ISSUE TITLE
复选框

### ISSUE THREAD

**Issue by xiaozhendong** [ant-design/ant-design-mobile#2807]
单个复选框值我知道怎么取到，假设我有很多个复选框，如何像ant design那样使用checkbox.group类似的收集到已勾选的复选框的值

**Comment by oMaten** [comment]
@xiaozhendong https://codepen.io/anon/pen/ZMKEom?editors=0011

**Comment by likezero** [comment]
@oMaten 的方案能解决你的问题吗

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
