### ISSUE TITLE
IOS9下iPhoneSE，点击蒙层关闭不了modal（iPhoneSE with IOS9system , click the background can't close the modal）

### ISSUE THREAD

**Issue by LastStranger** [ant-design/ant-design-mobile#2808]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
IOS9下iPhoneSE，

### Reproduction link
[https://mobile.ant.design/components/modal-cn/](https://mobile.ant.design/components/modal-cn/)

### Steps to reproduce
                <Modal
                    className="exam-modal"
                    visible={this.state.modal}
                    transparent
                    maskClosable={true}
                    onClose={(e) => this.onClose(e)}
                    title="兑换成功"
                    // footer={[{
                    //     text: 'Ok', onPress: () => {
                    //         console.log('ok');
                    //         this.onClose();
                    //     }
                    // }]}
                    wrapProps={{onTouchStart: this.onWrapTouchStart}}
                >
                    <div className="exam-modal-text">
                        真题试卷在书里可以
                        看到。
                    </div>
                </Modal>

    onWrapTouchStart = (e) => {
        // fix touch to scroll background page on iOS
        if (!/iPhone|iPod|iPad/i.test(navigator.userAgent)) {
            return;
        }
        const pNode = closest(e.target, '.am-modal-content');
        if (!pNode) {
            e.preventDefault();
        }
    };

上面这个onWrapTouchStart方法如果去掉，可以实现点击蒙层modal消失，但是如果去掉，就会出现滑动背景这个BUG，(if I remove the "onWrapTouchStart", I can click the background to make the modal disappear, but at the same time, "touch to scroll background page" this bug will show up )

### What is expected?
点击蒙层，madal消失 (click the background , modal disappear)

### What is actually happening?
点击蒙层无效果(click the background nothing happend)

**Comment by likezero** [comment]
@LastStranger  有引入fastclick吗

**Comment by LastStranger** [comment]
没有，需要引入fastclick吗？之前没看到文档内有要求引入fastclick，安卓上功能是正常的

**Comment by likezero** [comment]
@LastStranger  是需要引入fastclick
https://antd-mobile.gitee.io/docs/react/introduce-cn#3.-%E4%BD%BF%E7%94%A8

**Comment by jackYouth** [comment]
用onClose这个回调，手动将关掉
