### ISSUE TITLE
ant mobile NoticeBar 不支持无缝滚动

### ISSUE THREAD

**Issue by shenzekun** [ant-design/ant-design-mobile#2809]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
类似marquee的效果

### What does the proposed API look like?
类似marquee的效果

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
