### ISSUE TITLE
在安卓2.3版本的手机浏览器上不能显示网页

### ISSUE THREAD

**Issue by goldingking** [ant-design/ant-design-mobile#281]
#### 本地环境

- antd-mobile 版本：0.8.x
- 操作系统及其版本：android 2.3
- 浏览器及其版本：webkit

#### 你做了什么？

http://mobile.ant.design/components/accordion 通过扫描这个页面的二维码打开样例，不能显示
换了一个4.0版本以上的手机可以正常显示
#### 你期待的结果是：
在低版本手机的浏览器中也可以正常显示

#### 实际上的结果：
2.3手机浏览器中无法正常显示

**Comment by pingan1927** [comment]
支持Android4.0以上系统
