### ISSUE TITLE
SearchBar 里面的的取消按钮建议去除.或者加属性控制是否需要.

### ISSUE THREAD

**Issue by pheromone** [ant-design/ant-design-mobile#2811]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
SearchBar 里面的的取消按钮建议去除.或者加属性控制是否需要. 我们不需要取消的功能存在.能否加个属性控制.

### What does the proposed API look like?
我希望有个属性可以控制是否需要添加取消功能.

**Comment by oMaten** [comment]
@ziluo 看下是否需要引入 `hideCancel` 属性来控制

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
