### ISSUE TITLE
toast 字数超过6个时建议自动换行

### ISSUE THREAD

**Issue by yaoshanliang** [ant-design/ant-design-mobile#2812]
目前不换号、高度不适应，是否feature为自动换行？

![image](https://user-images.githubusercontent.com/5028569/44966540-65900200-af6e-11e8-93eb-b6d8a36fa4ac.png)

**Comment by oMaten** [comment]
@yaoshanliang https://codepen.io/anon/pen/GXmgYB?editors=0011 I can't reproduce your problem. Do u have any css rule affect?

**Comment by likezero** [comment]
@yaoshanliang  麻烦提供一个可复现的例子。demo中不会出现你截图的现象。

![image](https://user-images.githubusercontent.com/2275857/45012863-a578e700-b04b-11e8-82e8-52bb51a1fcd6.png)

**Comment by yaoshanliang** [comment]
奇怪了，估计我其他样式影响了吧
