### ISSUE TITLE
Carousel 带间距 轮播问题

### ISSUE THREAD

**Issue by DarkLove** [ant-design/ant-design-mobile#2814]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
iphone6,最新谷歌浏览器

### Reproduction link
[https://new-issue.ant.design/?repo=ant-design-mobile](https://new-issue.ant.design/?repo=ant-design-mobile)

### Steps to reproduce
项目中轮播图的数量有5张的时候有异常，1. 显示倒数第二张的时候，左边完全是空白的。 2. 最后一张切换到第一张的时候，过度的极不平缓。

### What is expected?
不管几张图片都能和官网展示的  带间距的 走马灯 一个效果

### What is actually happening?
1

**Comment by DarkLove** [comment]
就是你们官方的demo， data: ['AiyWuByWklrrUDlFignR', 'TekJlZRVCjLFexlOCuWn', 'IJOtIlfsYdTyaDTRVrLI', 'IJOtIlfsYdTyaDTRVrLI', 'IJOtIlfsYdTyaDTRVrLI'],我多加了几张图片就有这个问题了

**Comment by shurong-kavout** [comment]
实际与图片多少都存在此问题。如官网只有三张图片，当设置了 infinite 属性，轮播图每次从尾图切换到首图都会有停顿

**Comment by shurong-kavout** [comment]
https://github.com/ant-design/ant-design-mobile/issues/3101

**Comment by shurong-kavout** [comment]
> Hello @DarkLove. Please provide a re-producible demo: https://codepen.io/pen?template=LWpaKe&editors=0010
其实，不论图片多少张，都存在此问题。
如：官网只有三张图片，当设置了 infinite 属性，轮播图每次从尾图切换到首图（或首图切换到尾图），都会有停顿产生。
实际上是问题为：当设置了 infinite 属性，尾图和首图的相互切换，存在停顿不流畅现象

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
