### ISSUE TITLE
ＬistＶｉｅｗ在ＱＱ浏览器上的ＢＵＧ

### ISSUE THREAD

**Issue by 750973092** [ant-design/ant-design-mobile#2816]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
ＩＯＳ和ＱＱ浏览器的任一版本(经测试安卓也不可以)

### Reproduction link
[https://antd-mobile.gitee.io/kitchen-sink/?lang=zh-CN](https://antd-mobile.gitee.io/kitchen-sink/?lang=zh-CN)

### Steps to reproduce
在苹果手机上的ＱＱ浏览器点进任何一个组件然后右滑返回（注意不是左下角的返回箭头），然后再点进ＬiｓｔＶｉｅｗ组件，再随便点ＬiｓｔＶｉｅｗ里的任何一个标题进去（我点的是ｂｏｄｙ容器），再右滑返回（ＢＵＧ在这里，这里返回切换的时候先出现之前点的任何一个组件的页面，然后它再切换到ＬisｔＶｉｅｗ里的页面）
注：我开发的网站同样出现上面的问题
### What is expected?
切换后退的时候不出现先前几步前点过的页面，希望是上一页的界面

### What is actually happening?
切换有之前点过的界面，不是上一级界面

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
