### ISSUE TITLE
No cascade effect on PickerView

### ISSUE THREAD

**Issue by oMaten** [ant-design/ant-design-mobile#2817]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/anon/pen/yxbQov?editors=0011](https://codepen.io/anon/pen/yxbQov?editors=0011)

### Steps to reproduce
Follow the example, swipe the first column to the `浙江` field but sub column has no cascade effect

### What is expected?
sub column should change as data expressed

### What is actually happening?
sub column has no cascade effect as expected

**Comment by oMaten** [comment]
link to the lower level component issue https://github.com/react-component/m-cascader/issues/21

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
