### ISSUE TITLE
toast 闪两下怎么解决,先调用 Toast.hide,在调用 toast.info()也是 会闪两下

### ISSUE THREAD

**Issue by lcyh** [ant-design/ant-design-mobile#2818]
toast 闪两下怎么解决,先调用 Toast.hide,在调用 toast.info()也是 会闪两下,请问有好的解决方法吗

**Comment by ziluo** [comment]
提供一下设备平台、操作系统版本等信心

**Comment by lcyh** [comment]
小米手机  MI 5s Plus

**Comment by lcyh** [comment]
![127477032471604768](https://user-images.githubusercontent.com/26177202/45023630-7d987c00-b069-11e8-88c4-9d758f9c10d9.png)

**Comment by lcyh** [comment]
![127477032471604768](https://user-images.githubusercontent.com/26177202/45023702-b0427480-b069-11e8-885f-136de5e60293.png)

**Comment by lcyh** [comment]
![1536054316](https://user-images.githubusercontent.com/26177202/45023963-6908b380-b06a-11e8-8b80-30fc2092d856.png)

**Comment by lcyh** [comment]
modal.alert组件的弹窗,背景没显示

**Comment by lcyh** [comment]
![1536054711 1](https://user-images.githubusercontent.com/26177202/45024288-4034ee00-b06b-11e8-834b-f2933b532f75.jpg)

**Comment by HoChine** [comment]
问题解决了吗？ 没看到解决方案阿， 为什么issues被关了
