### ISSUE TITLE
modal.alert 弹窗在某些机型,弹窗背景没显示

### ISSUE THREAD

**Issue by lcyh** [ant-design/ant-design-mobile#2819]
modal.alert 弹窗在某些机型,弹窗背景没显示

**Comment by lcyh** [comment]
![1536054711 1](https://user-images.githubusercontent.com/26177202/45024510-c5b89e00-b06b-11e8-91e3-c9f24ee88f2f.jpg)

**Comment by likezero** [comment]
@lcyh 有具体的机型吗？

**Comment by lcyh** [comment]
1.oppo r7s,vivo x5v,上面提供的图片的机型都是有问题的机型,
2.并且modal弹窗和toast轻提示会闪两下;

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
