### ISSUE TITLE
【微信】【滑动输入条】显示异常

### ISSUE THREAD

**Issue by luqin** [ant-design/ant-design-mobile#282]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：Android 6/微信
- 浏览器及其版本：

#### 你做了什么？

微信访问，快速拖动滑动输入条

#### 实际上的结果：

![image](https://cloud.githubusercontent.com/assets/2267688/18656182/a3f61c20-7f21-11e6-90a9-0c876f691777.png)

**Comment by benjycui** [comment]
5s ios10 正常。

**Comment by benjycui** [comment]
版本信息都不提供一下。。

**Comment by benjycui** [comment]
长时间没有提供有效信息，先关了，有问题再开。
