### ISSUE TITLE
SearchBar 初始加载时样式混乱,获取焦点后变正常

### ISSUE THREAD

**Issue by codeloved** [ant-design/ant-design-mobile#2824]
![image](https://user-images.githubusercontent.com/20904467/45079068-1b508180-b124-11e8-972c-4cfa055f140d.png)
```
<SearchBar
            placeholder="Search"
 />
```
第一次进入会出现样式一次,当获取焦点取消后,样式是正常的,ant-mobile版本为2.2.3
![image](https://user-images.githubusercontent.com/20904467/45079198-72565680-b124-11e8-8dc2-5eea43aa77dc.png)
![image](https://user-images.githubusercontent.com/20904467/45079222-826e3600-b124-11e8-890b-92f81f40e0dd.png)
100%width并没有正确的设置宽度

**Comment by codeloved** [comment]
第一次是375,第二次是40
![image](https://user-images.githubusercontent.com/20904467/45080962-a895d500-b128-11e8-9bed-1d3d4b611743.png)

**Comment by weiq** [comment]
同样的问题，有什么办法么

**Comment by tyuexingzhe** [comment]
同样的问题，为啥没人重视呢。请问解决了吗？

**Comment by weiq** [comment]
@tyuexingzhe 自已实现了一个[searchbar](https://github.com/LANIF-UI/dva-boot-mobile/blob/master/src/components/SearchBar/SearchBar.js),没用这个

**Comment by lgbcscs** [comment]
mshare-search-input 样式中的width：100%，改为max-width：100%，可以解决

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
