### ISSUE TITLE
SearchBar: the source "... this.rightBtnRef.offsetWidth ..." has an error in webpack-dev-env

### ISSUE THREAD

**Issue by DrReMain** [ant-design/ant-design-mobile#2826]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
win10、chrome 68、webpack development enviroment、react server side render

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/master/components/search-bar/index.tsx#L94](https://github.com/ant-design/ant-design-mobile/blob/master/components/search-bar/index.tsx#L94)

### Steps to reproduce
Normally, the value of "this.rightBtnRef.offsetWidth" is 40px，but when the CSS has not finished loading, the value is wrong.
As when we use style in webpack and don`t use extract-text-webpack-plugin, the style in js need to create Link and insert to Head in execution is slow.

### What is expected?
default: this.rightBtnRef.offsetWidth === 40px

### What is actually happening?
this.rightBtnRef.offsetWidth === 100% width of the container

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
