### ISSUE TITLE
android uc modal 样式错乱

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#283]
http://mobile.ant.design/kitchen-sink/modal/

点输入框

**Comment by warmhug** [comment]
modal 里有 输入框，在 手淘容器 里测测

**Comment by warmhug** [comment]
https://github.com/imweb/mobile/blob/master/docs/ios-input-fixed.md

**Comment by silentcloud** [comment]
@yiminghe 指的是这里么？

![image](https://cloud.githubusercontent.com/assets/1698185/18702689/62d3dd5a-8015-11e6-968f-28bcdefee67a.png)

我这边只能在模拟器里用 uc 瞅瞅

**Comment by silentcloud** [comment]
e0c711ecc7c676120159006b2bfc458ca7215e56
