### ISSUE TITLE
Picker关闭没有动画效果

### ISSUE THREAD

**Issue by kenstar2017** [ant-design/ant-design-mobile#2831]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
MacOs、chrome 68.0.3440.106、react 16.0.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x9z27vwp4o)

### Steps to reproduce
react 16.0.0 版本都会有

### What is expected?
可以实现关闭动画

### What is actually happening?
没有关闭动画

**Comment by zack24q** [comment]
Can you give me a way to reproduce this problem?

**Comment by kenstar2017** [comment]
Install react16.0.0+ version

**Comment by kenstar2017** [comment]
@zack24q please run this demo https://codesandbox.io/s/x9z27vwp4o

**Comment by zack24q** [comment]
Link to the same issue #2749

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
