### ISSUE TITLE
InputItem clear not working if text is very long

### ISSUE THREAD

**Issue by heuuLZP** [ant-design/ant-design-mobile#2832]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
android

### Reproduction link
[https://mobile.ant.design/components/input-item-cn/](https://mobile.ant.design/components/input-item-cn/)

### Steps to reproduce
1. In InputItem A iput a very long text.
2. Click Another Input Item B, let InputItem A to blur.
3. Click on the rightmost of InputItem A,  show the clear Icon ,but can't clear text.

![step](https://user-images.githubusercontent.com/18410118/45217618-5e9f2180-b2d7-11e8-89de-4eda9d25d55a.png)

### What is expected?
If InputItem has a long text, click on the rightmost of InputItem,  show the clear icon , click clearIcon can clear text.

### What is actually happening?
 click clearIcon can't clear text.
![image](https://user-images.githubusercontent.com/18410118/45217825-24824f80-b2d8-11e8-9c87-607d4a6b19c9.png)

**Comment by zack24q** [comment]
Sorry, I can't follow this step to reproduce this issue. Can you give me a way to reproduce this problem?

**Comment by heuuLZP** [comment]
@zack24q @ant-design-bot 
Hello, about this issue , I think it is a bug of wechat.

Please click [here](https://www.jianshu.com/p/8110d19268c0) to read detail.
