### ISSUE TITLE
input组件，第一次进入页面不能autofocus

### ISSUE THREAD

**Issue by collinsyu** [ant-design/ant-design-mobile#2835]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
h5手机浏览器

### Reproduction link
[http://kaoyan.masteryu.site/home](http://kaoyan.masteryu.site/home)

### Steps to reproduce
第一次进入页面，输入框没有自动获取焦点，点击返回按钮返回首页，再次进入该页面，可以自动焦点，键盘弹出。

### What is expected?
第一次进入就可以使得input 获得自动焦点，弹出手机键盘

### What is actually happening?
第一次不行，第二次加载了第二个页面的js之后，再次进入第二个页面，才会自动获取焦点

---
源代码：https://github.com/collinsyu/antd_mobile_input_autofocus_bug.git

**Comment by Roxyhuang** [comment]
是否有特定机型？，用你的demo测试安卓7.0 chrome好像测试没问题

**Comment by collinsyu** [comment]
不好意思，我的锅，在ios上面就会出现这个问题，我刚找了个安卓的测试确实没有问题，真是不好意思

**Comment by collinsyu** [comment]
@Roxyhuang 不好意思，我的锅，在ios上面就会出现这个问题，我刚找了个安卓的测试确实没有问题，真是不好意思

**Comment by chf007** [comment]
> @Roxyhuang 不好意思，我的锅，在ios上面就会出现这个问题，我刚找了个安卓的测试确实没有问题，真是不好意思

ios上后来怎么处理的？我也遇到这个问题

**Comment by chf007** [comment]
> @Roxyhuang 不好意思，我的锅，在ios上面就会出现这个问题，我刚找了个安卓的测试确实没有问题，真是不好意思
@collinsyu 
ios上后来怎么处理的？我也遇到这个问题

**Comment by chf007** [comment]
@collinsyu ios上后来怎么处理的？我也遇到这个问题

**Comment by sysuzero** [comment]
> @collinsyu ios上后来怎么处理的？我也遇到这个问题

ios好像无法解决
