### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive

### ISSUE THREAD

**Issue by wanliyunyan** [ant-design/ant-design-mobile#2836]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
chrome 69  "antd-mobile": "^2.2.5 react 16.5.0

### Steps to reproduce
Calendar 组件下拉，chrome报错

### What is expected?
期望不报错

### What is actually happening?
 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

---
我的不会用codepen，但是Calendar组件下拉确实有这个问题，本来想用官网的codepen重现，但是报错，用不了

**Comment by wanliyunyan** [comment]
![image](https://user-images.githubusercontent.com/10751248/45461955-4a747d80-b738-11e8-9a6e-62daec35dd1a.png)
官网的虽然没有出警告，但是多次以后已经无法向上翻页了，跟我本地的bug一模一样

**Comment by wanliyunyan** [comment]
没人管了吗？？？？组件报错啊！！！

**Comment by wanliyunyan** [comment]
不是antd-mobile 的问题，是react目前尚不支持

**Comment by zhonggithub** [comment]
兄弟解决了这个问题

**Comment by zhonggithub** [comment]
找到原因了，应该是自定义的样式跟ant 重叠了

**Comment by wanliyunyan** [comment]
@zhonggithub 怎么解决的？大神！！！

**Comment by zhonggithub** [comment]
@wanliyunyan 我出现这个问题是样式的名称有问题，样式名称写成了title，把样式名称改掉就没问题了，你看下是不是那个地方样式命名有问题

**Comment by wanliyunyan** [comment]
@zhonggithub 我不是你这问题，我没有写样式
