### ISSUE TITLE
Carsousel轮播问题

### ISSUE THREAD

**Issue by rongzhx123** [ant-design/ant-design-mobile#2838]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
无

### Reproduction link
[https://mobile.ant.design/components/carousel-cn/](https://mobile.ant.design/components/carousel-cn/)

### Steps to reproduce
1，设置轮播的item尽量多，8个
2，带间距轮播

### What is expected?
根据前几个一样，带间距轮播时，当前的item应该要都能看到上一个、下一个item的部分内容

### What is actually happening?
轮播3~4个后，会出现当前轮播的item的左侧看不到上一个item的部分内容

**Comment by SUNAnne** [comment]
使用antd mobile carousel “带间距”的carousel
我有多个栏目，点击每个栏目都会遍历carousel一次，每个carousel里面有多个可以轮播的图片
当我在第一个栏目滑动carousel后，再去点击第二个栏目，carousel的图片不从第一张轮播，而是继续使用第一个栏目carousel滑动图片的位置（下标）
请问如何在切换栏目时重置carousel的位置？

**Comment by rongzhx123** [comment]
所以这是个bug还是什么问题？？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
