### ISSUE TITLE
ant-design-mobile 导致ios端input无法正常输入（phonegap项目，input是普通input）

### ISSUE THREAD

**Issue by qingwenje2008** [ant-design/ant-design-mobile#2839]
我用phonegap框架对h5项目进行包壳，h5端用的ant-design-mobile ，在android端一切正常，在ios端出现了一个奇葩问题，当第一次点击input弹出键盘可以正常输入，再次点击input，键盘不会消失，但是input无法输入，输入没有任何反应，如果去掉当前页面下的ant-design-mobile组件（比如：TabBar）,input可以正常输入了。这个问题困扰了我很久，费了很大力气才定位到与ant-design-mobile有关，也查了很多资料可是依旧无法解决，求帮助

**Comment by linronglang** [comment]
同样是这个问题 ios 第一次点击可以 后面在点就会没反应 什么鬼

**Comment by linronglang** [comment]
原来是在微信端 才会这样 不知道有没有解决办法

**Comment by linronglang** [comment]
在浏览器 正常

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
