### ISSUE TITLE
文档里示例代码高度可以调高吗？看着非常难受，让它跟右边的模拟器一样高可以吗？

### ISSUE THREAD

**Issue by miaojiuchen** [ant-design/ant-design-mobile#2841]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
文档优化

### What does the proposed API look like?
文档优化

**Comment by paranoidjk** [comment]
来个 PR ？

**Comment by likezero** [comment]
代码区域有个代码放大按钮，之前不是太明显。这个PR 进行了优化。
PR : https://github.com/ant-design/ant-design-mobile/pull/2894
