### ISSUE TITLE
http://new-issue.ant.design?repo=ant-design-mobile

### ISSUE THREAD

**Issue by qq578023708** [ant-design/ant-design-mobile#2843]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.5

### Environment
android8.0  browser

### Reproduction link
[http://mobile.ant.design/kitchen-sink/](http://mobile.ant.design/kitchen-sink/)

### Steps to reproduce
android8.0 自带浏览器预览空白呢，其他浏览器就可以

### What is expected?
能完美兼容自带浏览器

### What is actually happening?
不能很好兼容呢

**Comment by nieruqing** [comment]
魅族手机不兼容MX5 不兼容，打开白屏
