### ISSUE TITLE
I can't stop Modal's close when using Modal.prompt function with a callbackOrActions that is function(not array)

### ISSUE THREAD

**Issue by awakn123** [ant-design/ant-design-mobile#2847]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
win10, Chrome  69.0.3497.92（正式版本） （64 位）

### Reproduction link
[https://codepen.io/awakn123/pen/YOOmpP?editors=0010](https://codepen.io/awakn123/pen/YOOmpP?editors=0010)

### Steps to reproduce
call this function: 
Modal.prompt('title', 'desc', ()=>{
  return new Promise((resolve, reject)=>{
    reject('a error.');
  });
});

### What is expected?
When I click the button "确定", it should stay in the Modal.

### What is actually happening?
The Modal hides.

**Comment by awakn123** [comment]
I have readed the source code, prompt.tsx's 170 line lacks a "return", that caused the problem(if it is).

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
