### ISSUE TITLE
ant-mobile not support traditional Chinese(zh_HK, zh_MO)

### ISSUE THREAD

**Issue by xingyesh** [ant-design/ant-design-mobile#2849]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
LocaleProvider support zh_HK.

### What does the proposed API look like?
```javascript
import zhHK from 'antd-mobile/lib/locale-provider/zh_HK';
return <LocaleProvider locale={zhHK}><App /></LocaleProvider>;


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by awmleer** [comment]
5.x 版本已经支持 zh_HK 和 zh_TW
