### ISSUE TITLE
TextareaItem在弹出窗口后报警告问题

### ISSUE THREAD

**Issue by zhwb36** [ant-design/ant-design-mobile#285]
代码：

    Modal.alert('确认驳回',   <TextareaItem
                              rows={2}
                              placeholder="驳回理由(非必录)"
                              clear
                              onChange={this.handleTextChange.bind(this)}
                            />,
      [
        { text: '取消'},
        { text: '确定', onPress: () => this.handleRejectAction('reject') },
      ]);

在确认窗口加入输入框，如果不输入直接确定，不报任何错误警告，如果输入后再确定，会报以下警告：
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the TextareaItem component

是否为控件BUG，请分析！

**Comment by pingan1927** [comment]
这个先请忽略，下一个大版本进行修复。

**Comment by pingan1927** [comment]
下一个版本已经修复，不是bug，请忽略，issues先关了
