### ISSUE TITLE
DatePicker bug

### ISSUE THREAD

**Issue by daqi** [ant-design/ant-design-mobile#2852]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
chrome最新

### Reproduction link
[https://codepen.io/daqi/pen/MqZYym](https://codepen.io/daqi/pen/MqZYym)

### Steps to reproduce
先选择8月20日，点确定，然后把月份选成“9月”，“日列”停在了“1日”上，不要动“日列”，直接点击确定

### What is expected?
回调返回9月1日

### What is actually happening?
回调返回9月20日

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
