### ISSUE TITLE
TabBar 标签栏 Quick switch error

### ISSUE THREAD

**Issue by Su-Hao** [ant-design/ant-design-mobile#2855]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
Google Chrome

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/tab-bar?lang=zh-CN#tab-bar-demo-1](https://mobile.ant.design/kitchen-sink/components/tab-bar?lang=zh-CN#tab-bar-demo-1)

### Steps to reproduce
Quickly switch the TAB bar to error

### What is expected?
Don't complain

### What is actually happening?
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
