### ISSUE TITLE
listview 与 tabbar 结合使用的问题

### ISSUE THREAD

**Issue by breeze-yang** [ant-design/ant-design-mobile#2856]
期望向上滑动的时候，先把listview上面的部分给滑上去。再接着展示listview中下面的数据

请问我需要怎么做呢。

有个gif图说明。请耐心等待加载出来
![listview](https://user-images.githubusercontent.com/25073547/45860697-31547800-bd9b-11e8-88db-0a77c7661d7f.gif)

**Comment by KDWangBoss** [comment]
我也有这样的问题，求指教

**Comment by czy0729** [comment]
不要用useBodyScroll这种容器, 这种用transform模拟的容器绝大部分情况都不好用

**Comment by luweiCN** [comment]
有人能给出解决方案吗

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
