### ISSUE TITLE
Stepper 在 pc  浏览器上直接输入小数点没反应

### ISSUE THREAD

**Issue by XueMary** [ant-design/ant-design-mobile#2858]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
wind  pc  chrome

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/stepper?lang=zh-CN#stepper-demo-0](https://mobile.ant.design/kitchen-sink/components/stepper?lang=zh-CN#stepper-demo-0)

### Steps to reproduce
直接在默认值后面输入小数点

### What is expected?
输入小数点有反应

### What is actually happening?
输入小数点没反应

---
我们更希望在pc端也能正常使用，毕竟用户各种骚操作都有，不能保证不会在pc去访问移动页面，像我有时候就是这样的奇葩，这bug也是我们的测试奇葩测出来的

**Comment by seeya** [comment]
一样的问题，有没有什么解决方法？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
