### ISSUE TITLE
Picke多列时，第一列onPickerChange事件触发时改变第二列的value之后，onOK传过来的值不正确

### ISSUE THREAD

**Issue by kimiyang** [ant-design/ant-design-mobile#2859]
复现步骤：
在react下
1. 创建一个两列的picker，设置onPickerChange和onOK事件，传value属性是一个二维数组(this.state.pickerValue == [0,0])
2. 滑动第一列的值触发onPickerChange事件，在事件中改变pickerValue: this.setState({pickerValue: [2,2]})
3. 点击确定触发onOK事件，打印传过来的value看到的是[2,0]

再picker绑定的value改变之后，马上触发onOK应该传过来改变后的值[2,2]

**Comment by ysxhd** [comment]
动态获取省市区的值，onPickerChange事件时候只是选择第一级省的数据，给后面的市区赋值就会失败，有遇到过么？

**Comment by duzliang** [comment]
有这种情况，如果选取了第一列省的数据，然后自动获取下面第一个市，和市下面第一个县的数据。但是不手动触发，onOk只能获得第一列省的数据，只有手动触发改变了第二列，第三列值，onOK才能获得三列的值

**Comment by duzliang** [comment]
这个省市县三列选择的`Pikcer`，在`Preact`下也有闪现的问题：
改变第一列的值，`Picker`会先消失，然后展现，选择市的数据时，同样的问题，以此类推。
把`Preact`改为`React`后就没问题，但是`React`的库比较大

**Comment by ysxhd** [comment]
最后我同事解决了这个问题，获取数据后重新调下onPickerChange事件，就可以了

**Comment by duzliang** [comment]
@ysxhd 你们用的也是`Preact`吗？

**Comment by ysxhd** [comment]
不是哦，就是react

**Comment by duzliang** [comment]
React没有上面描述的问题😀

**Comment by beezenD** [comment]
也遇到类似的问题，取onOk回调的数据时只有["22"],应该是["22","01"]。 我做了个兼容处理，当cols为2，而回调数据还只有一个，则取onPickerChange函数中保存的 asyncValue值。
asyncValue值为，当添加children时，默认先添加的第一个值。
`for (let i = 0; i < parentNode.length; i++) {
                if (parentNode[i].value == val[0]) {
                    if (!parentNode[i].children) {
                        parentNode[i].children = children
                    }
                    children[0] && asyncValue.push(children[0].value);
                    colNum = 2;
                    break;
                }
            }
            if (children.length == 0) {
                colNum = 1
            }
            this.setState({
                pickerData: parentNode,
                asyncValue,
                cols: colNum,
            });`

**Comment by guoxiangwen** [comment]
> onPickerChange

有代码么？

**Comment by guoxiangwen** [comment]
@ysxhd 你们怎么处理的？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
