### ISSUE TITLE
按照高清方案引入相关代码后，antd-mobile中的尺寸样式并没有转为rem

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#286]
如题，自己写的样式没有问题，但是由于antd-mobile上样式由于单位px没有转化为rem，导致antd-m的组件看起来很小。

![image](https://cloud.githubusercontent.com/assets/9410091/18664334/c73ada12-7f54-11e6-801f-ef7f546b70ac.png)
![image](https://cloud.githubusercontent.com/assets/9410091/18664356/dd780bba-7f54-11e6-8bbd-48e92e730020.png)

**Comment by minooo** [comment]
@silentcloud 可以给个解释吗？谢谢！

**Comment by mewtwo-chi** [comment]
同问这个问题，看源码里写的都是px，之前还有缩放方式，现在style下的css.js也没有了，页面的样式现在是怎么适配移动端呢？求科普

**Comment by silentcloud** [comment]
看一下前面 issue 里的 demo 吧

**Comment by yiminghe** [comment]
https://github.com/ant-design/ant-design-mobile/issues/56
