### ISSUE TITLE
当最大日期的时钟小于最小日期的时钟的时候，时钟显示不出来

### ISSUE THREAD

**Issue by mybedhome** [ant-design/ant-design-mobile#2861]
在DatePicker组件mode为time的情况下,如果最小日期和最大日期是这样的：
~~~
const minDate = new Date(2018,9,27,19,0,0); 
const maxDate= new Date(2018,9,28,7,59,59)
~~~

这种情况下时钟显示不出来:
![image](https://user-images.githubusercontent.com/6857151/46124750-6f004780-c258-11e8-8c81-6ffe9253f772.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
