### ISSUE TITLE
Carousel onChange不能改变位置

### ISSUE THREAD

**Issue by zhengzhuoxing** [ant-design/ant-design-mobile#2863]
`_this.onChange = function (index) {
            _this.setState({
                selectedIndex: index
            }, function () {
                if (_this.props.afterChange) {
                    _this.props.afterChange(index);
                }
            });
        };`
<!--
调用之后并没有改变 内部view的位置

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
