### ISSUE TITLE
Tabbar fullscreen mode will overlay by 支付宝 in IOS

### ISSUE THREAD

**Issue by thewindsword** [ant-design/ant-design-mobile#2867]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.3

### Environment
IOS 12/9

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/tab-bar?lang=zh-CN#tab-bar-demo-0](https://mobile.ant.design/kitchen-sink/components/tab-bar?lang=zh-CN#tab-bar-demo-0)

### Steps to reproduce
使用支付宝扫码打开官方的tabbar示例。
点击Click to switch fullscreen。
往上拉，会有灰色遮罩层盖住tabbar部分。

### What is expected?
效果应如安卓效果一致

### What is actually happening?
灰色遮罩层盖住了tabbar部分

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
