### ISSUE TITLE
这体验真的好？

### ISSUE THREAD

**Issue by leejaen** [ant-design/ant-design-mobile#2869]
你们试过在这么一点点的代码区域内找想要的东西好用？
![image](https://user-images.githubusercontent.com/1638970/46251925-25e80780-c493-11e8-938f-5b8a390b90e2.png)

**Comment by leejaen** [comment]
鼠标一点击就飘

**Comment by GHLandy** [comment]
以前可以点击放大，现在可以点击跳转到 codepen。当然，找到固定的节点把那个 `max-height ` 去勾选掉就行。

**Comment by zjxpcyc** [comment]
早就发现不好了

**Comment by zhushichuan** [comment]
写文档能不能用点心？

**Comment by shen-lan** [comment]
> 哈哈哈哈哈，你们真可爱，难道你们都没有发现有个近乎透明的小圈圈吗，点击了就能放大。我都看到楼主的截图有这个小圈圈的，就在滚动条旁边。不过这个设计是有点坑

为我的无知道歉。
确实这个小圆点可以弹出具体选择复制。。。。
希望官方把它做的明显些

**Comment by likezero** [comment]
我们会优化，感谢提意见。也欢迎提MR~
