### ISSUE TITLE
remove ListItem last prop

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#287]
https://github.com/ant-design/ant-design-mobile/blob/master/components/list/index.tsx#L40

https://github.com/ant-design/ant-design-mobile/blob/master/components/swipe-action/demo/basic.tsx#L12

React.cloneElement conflict

or change to SwipeableItem

**Comment by yiminghe** [comment]
@pingan1927 last 能去么，和 web api 一致

**Comment by pingan1927** [comment]
我继续想想，mac os RN运行不起来，囧

**Comment by silentcloud** [comment]
last prop 我已经去掉了  commit in:  4aa10378460096db09fd357430395d02d3f8d552
