### ISSUE TITLE
关于listview修改粘性布局设置

### ISSUE THREAD

**Issue by KDWangBoss** [ant-design/ant-design-mobile#2871]
我有个问题是在listview的滚动布局那里，我的问题是在哪设置Sticky的动态样式，以下是我的问题截图。
页面加载。。。
![pq7qorpwy8u yzhhx6i2 mm](https://user-images.githubusercontent.com/40023056/46253803-6194c880-c4b7-11e8-9c29-f33fe1581ee4.png)

往上拉的时候是这样的
![s 6ihzdioa8z s vd 04ojq](https://user-images.githubusercontent.com/40023056/46253805-72453e80-c4b7-11e8-8cb1-fd658f4468d6.png)

请问我要在哪修改absolute的top值呢

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
