### ISSUE TITLE
Repeated date on calendar 

### ISSUE THREAD

**Issue by Stidro** [ant-design/ant-design-mobile#2875]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
Browser (Chrome, Safari, iOS Safari)

### Reproduction link
[https://mobile.ant.design/components/calendar/](https://mobile.ant.design/components/calendar/)

### Steps to reproduce
* Open Calendar
* Scroll to October (2018)
* Last Sunday and Monday are the same (28 on 2018)

### What is expected?
Display month days without repeating them

### What is actually happening?
Last Sunday and Monday are the same. On 2018, 28 is repeated.

![Calendar bug Example](https://i.imgur.com/2Mxxheh.png)

---
Also selecting any date beyond this repeated date causes ` selected-end` class to not be set.

**Comment by likezero** [comment]
sorry, it can not be reproduced. does this problem  still exist ?

**Comment by sebas-deedee** [comment]
@likezero @Stidro this looks like is a problem with the daylight saving time

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
