### ISSUE TITLE
Range Component's defaultValue type in range/PropsType.tsx differ with range/index.en-US.md

### ISSUE THREAD

**Issue by magicly** [ant-design/ant-design-mobile#2876]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
any

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/tree/master/components/range](https://github.com/ant-design/ant-design-mobile/tree/master/components/range)

### Steps to reproduce
check code

### What is expected?
Range Component's defaultValue type should be:
defaultValue?: [number, number];
not
defaultValue?: number;

### What is actually happening?
Range Component's defaultValue type is :
defaultValue?: number?

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
