### ISSUE TITLE
企业微信mac版本（2.5.8）通过小程序进入ListView内容不能完全渲染

### ISSUE THREAD

**Issue by LingYun** [ant-design/ant-design-mobile#2880]
<!--
注意：请使用下面的链接来新建 issue：

  http://new-issue.ant.design?repo=ant-design-mobile

不是用上面的链接创建的 issue 会被立即关闭。
![_43ae811a-f018-4123-a703-90fc1808318a](https://user-images.githubusercontent.com/1118261/46711737-26955080-cc80-11e8-85b6-abdc55552e28.png)
**ListView代码如下**
![_9bd0e8f7-acb9-4b46-99e8-278eb3aa0fd4](https://user-images.githubusercontent.com/1118261/46711776-5d6b6680-cc80-11e8-9f7f-94755025d275.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
