### ISSUE TITLE
tabBarUnderlineStyle 属性修改下划线样式无效

### ISSUE THREAD

**Issue by shengwenzheng** [ant-design/ant-design-mobile#2883]

**Comment by umebfl** [comment]
react antive tabBarUnderlineStyle属性修改下划线样式无效

**Comment by Yezhenwei** [comment]
使用backgroundColor跟color都无效的，看源码就知道下横线其实就是个border，比如你要修改颜色：
tabBarUnderlineStyle={{ borderColor: '#FE6A00' }}

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
