### ISSUE TITLE
suggest to add image view component

### ISSUE THREAD

**Issue by MailKiller** [ant-design/ant-design-mobile#2885]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when you use ImagePicker to add pictures on your mobile, then you want to view those pictures you added and you could swipe or scale it

### What does the proposed API look like?
imageViewer

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
