### ISSUE TITLE
2.0以后最新版到底如何使用高清方案？

### ISSUE THREAD

**Issue by shen-lan** [ant-design/ant-design-mobile#2887]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
win 

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/wiki/HD](https://github.com/ant-design/ant-design-mobile/wiki/HD)

### Steps to reproduce
https://github.com/ant-design/ant-design-mobile/wiki/HD
0. create-reat-app生成的项目
1. 按照上述官方文档安装 postcss-pxtorem，webpack配置。
2. index.html
  `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" />`
3. 配置完毕发现页面炸了 ，各个元素都非常小。F12查看，确实都已经转换成rem了。
4. 于是想到可能是viewport问题。重新改2步骤，换成 `antm-viewport.min.js`（即使官方说2.0以后 不需要这样做了），发现正常很多了，但是！！元素还是小了一半左右。。。。
5. 问下大佬，这个到底怎么配置？谢谢

### What is expected?
元素大小合适，rem单位。

### What is actually happening?
rem单位没有正常缩放。

**Comment by likezero** [comment]
https://antd-mobile.gitee.io/docs/react/upgrade-notes-cn#%E9%AB%98%E6%B8%85%E6%96%B9%E6%A1%88

**Comment by liuyanming9551** [comment]
@shen-lan 请问这个问题是怎么解决的，使用楼上的方式，好像没有成功。请看到了指导一下

**Comment by citrusjunoss** [comment]
使用后, 大部分成功了, 但是发现Tabbar 的内容缩小了, 能帮忙看下是什么问题么


![image](https://user-images.githubusercontent.com/18432488/53212563-5e75c100-3680-11e9-9ed7-b2aa17df8c77.png)

![image](https://user-images.githubusercontent.com/18432488/53212605-8402ca80-3680-11e9-9bf9-af167ba070c9.png)

![image](https://user-images.githubusercontent.com/18432488/53212614-90872300-3680-11e9-8012-768198b24f15.png)

**Comment by shen-lan** [comment]
> 决的



> @shen-lan 请问这个问题是怎么解决的，使用楼上的方式，好像没有成功。请看到了指导一下

我没有用高清方案了。这个项目用的px
不过 可以参考我在另外一个vant UI项目 中的rem方案配置

> postcss.config.js
```
const autoprefixer = require('autoprefixer');
const pxtorem = require('postcss-pxtorem');
module.exports = ({ file }) => {
    let ROOTValue;
    if (file && file.dirname && file.dirname.indexOf('vant') > -1) {
        ROOTValue = 37.5
    } else {
        ROOTValue = 75
    }
    return {
        plugins: [
            autoprefixer(),
            pxtorem({
              rootValue: ROOTValue,
              propList: ['*']
            })
        ]
    }
}
```
> main.js
```
import 'amfe-flexible';
```
ant  应该是类似的

**Comment by liuyanming9551** [comment]
感谢回复，问题已解决，跟你这种方式是差不多的。

**Comment by zhangfaliang** [comment]
@liuyanming9551  能帖一下你的解决方案吗？
