### ISSUE TITLE
Popover组件，离开页面时不会消失

### ISSUE THREAD

**Issue by six-666** [ant-design/ant-design-mobile#2890]
使用了Popover组件，离开页面并不会消失，而是存在body中，我把它用在了list里面，由于是无限的，导致DOM过多。

**Comment by likezero** [comment]
尝试设置一下 `destroyTooltipOnHide` 属性

**Comment by six-666** [comment]
@likezero 没有作用，官网也没这个属性。
```
<Popover 
            mask
            visible={this.state.visiblePopover} 
            overlayClassName="notice-popover" destroyTooltipOnHide 
            overlay={
              .......
            }>
              <div>....</div>
          </Popover>
```

**Comment by likezero** [comment]
https://github.com/react-component/m-tooltip#api

**Comment by nanyuantingfeng** [comment]
![image](https://user-images.githubusercontent.com/10877047/48182970-21532080-e368-11e8-92f4-ffb036d6fee2.png)
![image](https://user-images.githubusercontent.com/10877047/48182984-329c2d00-e368-11e8-8959-a631e73e4d33.png)
destroyTooltipOnHide 已经设置, Node卸载的时候,确实已经走了所有的 componentWillUnmount 生命周期,但是界面上依然残留最外层的  container div...
现在就是这种局面.

**Comment by lvze1992** [comment]
![image](https://user-images.githubusercontent.com/14118535/49367134-26687d00-f726-11e8-9b4e-b23424110a76.png)
和tabs组件配合。。每一次加入有popup的页面 都会追加dom。。导致dom越来越多

**Comment by ayawai** [comment]
@lvze1992 同样的问题，请问是否解决？

**Comment by quicklearning123** [comment]
tips上同遇到了，概率性不消失

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
