### ISSUE TITLE
希望改进带间距的Carousel组件，最后一张滚动到第一张时过度不正常。超出官网的3张图片后，问题更多了

### ISSUE THREAD

**Issue by DarkLove** [ant-design/ant-design-mobile#2891]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望改进带间距的Carousel组件，最后一张滚动到第一张时过度不正常。超出官网的3张图片后，问题更多了

### What does the proposed API look like?
希望改进带间距的Carousel组件，最后一张滚动到第一张时过度不正常。超出官网的3张图片后，问题更多了

**Comment by shurong-kavout** [comment]
官网最新版本 demo 仍存在此问题

**Comment by shurong-kavout** [comment]
https://github.com/ant-design/ant-design-mobile/issues/3101

**Comment by shurong-kavout** [comment]
其实，不论图片多少张，都存在此问题。
如：官网只有三张图片，当设置了 infinite 属性，轮播图每次从尾图切换到首图（或首图切换到尾图），都会有停顿产生。
实际上是问题为：当设置了 infinite 属性，尾图和首图的相互切换，存在停顿不流畅现象

**Comment by baimiao91** [comment]
【190816】当我设置了
frameOverflow="visible"
autoplay
autoplayInterval={6000}
infinite
cellSpacing={8}
slideWidth={0.8}
这些之后我数据比较多，比如12条，当自动播放前4张时左侧盒子得侧边都能正常显示出来，当轮播到第5张时，你会发现第4张的侧边就会消失（所谓的卡顿现象），后来发现当使用Carousel 组件的带间距时，最多设置5张不会出现我这样的情况，然后一旦超过5张就会出现我的上述问题了，望各位大佬们，给"搬砖"的我提提意见，怎么解决，或者官方给予一定的解决方案

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
