### ISSUE TITLE
Image-Picker onChange可以支持异步函数

### ISSUE THREAD

**Issue by AtarisMio** [ant-design/ant-design-mobile#2895]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在选择文件即时上传情况下，异步onChange会导致setState不阻塞在选择多张图片时，每次收到的files都是当前已有图片加一张新图片

### What does the proposed API look like?
希望可以在触发onChange的时候可以支持一个异步的onChange回调，或者一次性把所有添加的图片都返回，只触发一次onChange。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
