### ISSUE TITLE
Actionsheet component problem, written in the example of official website, clicks invalid under iphone8s.

### ISSUE THREAD

**Issue by zjb19970804** [ant-design/ant-design-mobile#2900]
`const isIPhone = new RegExp('\\biPhone\\b|\\biPod\\b', 'i').test(window.navigator.userAgent);
let wrapProps;
if (isIPhone) {
  wrapProps = {
    onTouchStart: e => e.preventDefault(),
  };
}`

`  showActionSheet = () => {
    const BUTTONS = ['Operation1', 'Operation2', 'Operation2', 'Delete', 'Cancel'];
    ActionSheet.showActionSheetWithOptions({
      options: BUTTONS,
      cancelButtonIndex: BUTTONS.length - 1,
      destructiveButtonIndex: BUTTONS.length - 2,
      message: 'I am description, description, description',
      maskClosable: true,
      wrapProps,
    },
    (buttonIndex) => {
      this.setState({ clicked: BUTTONS[buttonIndex] });
    });
  }`

**Comment by likezero** [comment]
引入fastclick测试

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
