### ISSUE TITLE
请问ant design mobile 是否可以用到react native app中？

### ISSUE THREAD

**Issue by zhengjieyuan** [ant-design/ant-design-mobile#2901]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
是否可以运行到react native app 工程中？目前在用ant design mobile rn  ，但是停止维护，想替换成ant design mobile。
ant design mobile 只能通过nodejs或其他web方式访问？
是否可以将build的资源文件加入到 react native app 工程中打包成apk文件？
是否可以与react native 、 android、ios接口互相调用？
谢谢！~

### What does the proposed API look like?
无

**Comment by ziluo** [comment]
@zhengjieyuan ant design mobile rn没有停止维护，只是主要由社区来维护，目前已恢复正常更新，欢迎关注
