### ISSUE TITLE
ListView下拉刷新, 内容被遮盖了

### ISSUE THREAD

**Issue by xoptimal** [ant-design/ant-design-mobile#2905]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
window10, chorme last

### Reproduction link
[https://codepen.io/xoptimal/pen/vVzpdj](https://codepen.io/xoptimal/pen/vVzpdj)

### Steps to reproduce
```
<ListView
        ref={this.rcv}
        pullToRefresh={<PullToRefresh refreshing={refreshing} onRefresh={this.onRefresh.bind(this)} />}
        dataSource={ds.cloneWithRows(list)}
        renderBodyComponent={() => <div>{this.props.children}</div>}
        renderRow={this.renderRow}
        style={{ height, overflow: 'auto' }}
        pageSize={10}
        initialListSize={20}
        onEndReachedThreshold={10}
        scrollRenderAheadDistance={500} />
```

### What is expected?
ListView, 在增加下拉刷新后,  内容没有满屏的情况下, 下拉刷新, 内容显示完全(ITEM没有遮盖)

### What is actually happening?
ListView, 在增加下拉刷新后,  内容没有满屏的情况下, 下拉刷新, 内容会显示不全 ~ 遮盖了内容!

**Comment by win7killer** [comment]
+1

**Comment by shenqihui** [comment]
+1

**Comment by shenqihui** [comment]
配置 initialListSize 能解决。

**Comment by gaojihao** [comment]
+1

**Comment by beysong** [comment]
+1

**Comment by beysong** [comment]
> 配置 initialListSize 能解决。

好像不行吧

**Comment by LiYanGang** [comment]
我也遇到了，这个没人解答吗？

**Comment by wyl530197181** [comment]
how can i reslove this questions?

**Comment by wyl530197181** [comment]
+1

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
