### ISSUE TITLE
使用react Native 引入ant-design-mobile老报主件错误，请问是怎么回事？

### ISSUE THREAD

**Issue by duanlr** [ant-design/ant-design-mobile#2907]
import React, {Component} from 'react';
import {View, AppRegistry,StyleSheet,icons} from 'react-native';
import { Button } from 'antd-mobile';

class HelloWorldApp extends Component {
    render() {
        return (
            <View style={{flex: 1, flexDirection: 'column',alignItems: 'center',backgroundColor:'#eee'}}>
                <Button>123</Button>

            </View>
        );
    }
}

**Comment by likezero** [comment]
react native版本请用 https://github.com/ant-design/ant-design-mobile-rn
