### ISSUE TITLE
DatePicker 没有时间单位，求解

### ISSUE THREAD

**Issue by deerW** [ant-design/ant-design-mobile#291]
#### 本地环境

- antd-mobile 版本：0.0.8
- 操作系统及其版本：mac
- 浏览器及其版本：chrome

#### 你做了什么？

引入 antd-mobile 的 DatePicker, 没有使用rc-form。
![image](https://cloud.githubusercontent.com/assets/20079361/18700333/451fec24-8009-11e6-9c92-42a976ec5e5b.png)
![image](https://cloud.githubusercontent.com/assets/20079361/18700355/63d9e96c-8009-11e6-9547-112f20f04c01.png)
#### 你期待的结果是：

像官网一样正常显示 

#### 实际上的结果：
木有时间单位……T^T
![image](https://cloud.githubusercontent.com/assets/20079361/18700323/34eb75a8-8009-11e6-9b23-5ffb0dba620c.png)

**Comment by yiminghe** [comment]
升级到最新
