### ISSUE TITLE
SegmentedControl：在onValueChange或者onChange中调用setState方法SegmentedControl切换异常

### ISSUE THREAD

**Issue by lcw2004** [ant-design/ant-design-mobile#2910]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.4

### Environment
Window10, Chrome

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
# 问题描述
使用SegmentedControl组件的时候，如果在onValueChange或者onChange中调用setState方法，会导致出现以下问题：**点击第二个Segment之后的任何一个Segment，第一次点击的时候都会激活第一个Segment，再次点击这个Segment，才会激活这个Segment**。

测试的时候去掉 this.setState 就能正常使用。

# 代码如下
```
const {SegmentedControl, WingBlank} = window["antd-mobile"];

class SegmentedControlExample extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            value: 0
        }
    }

    onValueChange= (value) => {
        this.setState({value})
    }

    render() {
        return (
            <WingBlank size="lg" className="sc-example">
                <p className="sub-title">SelectedIndex</p>
                {this.state.value} <br/>
                <SegmentedControl values={['Segment1', 'Segment2', 'Segment3', 'Segment4', 'Segment5', 'Segment6']} onValueChange={this.onValueChange}/>
            </WingBlank>
        );
    }
}

ReactDOM.render(<SegmentedControlExample/>, mountNode);
```

### What is expected?
在onValueChange或者onChange中调用setState方法不影响SegmentedControl的切换

### What is actually happening?
在onValueChange或者onChange中调用setState方法会影响SegmentedControl的切换。
点击第二个Segment之后的任何一个Segment，第一次点击的时候都会激活第一个Segment，再次点击这个Segment，才会激活这个Segment

**Comment by wisefin-yu** [comment]
+1

**Comment by LNlinaa** [comment]
我也是，不添加 this.setState正常，添加之后总是会跳转到第一个，出现混乱

**Comment by LNlinaa** [comment]
楼上用selectedIndex控制状态方可行，亲测有效。
