### ISSUE TITLE
使用ListView.IndexedList的时候，在更新state后，renderRow里的state数据不会刷新

### ISSUE THREAD

**Issue by zyfpopq** [ant-design/ant-design-mobile#2913]
不知道这是bug，还是为啥，renderRow里如果有state数据，每次setState更新后，里面的数据都不会刷新的

**Comment by web-display** [comment]
我也遇到了，搞定没

**Comment by guoweiwen** [comment]
也有此问题，不过好像有时有，有时会调用renderRow。<Listview />组件是渲染的，但就renderRow没有被调用

**Comment by cookcc** [comment]
const datasource = new ListView.DataSource({
      rowHasChanged: (row1, row2) => true;
    })

目前只能人为的将rowHasChanged让其返回true能解决这个问题

**Comment by live680g** [comment]
兄台请问rowHasChanged 直接返回true有啥副作用没，要上生产环境了

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
