### ISSUE TITLE
Mismatch of mobile terminal adaptation

### ISSUE THREAD

**Issue by gmars** [ant-design/ant-design-mobile#2914]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
chrome

### Reproduction link
[http://git.sikukeji.com/marswill/react-baibianshangji](http://git.sikukeji.com/marswill/react-baibianshangji)

### Steps to reproduce
The official high-definition solution was used. In iphone6, the HTML font-size=100px, so 7.5rem is 100% width. But on a device with a resolution of 441x823 DPR of 3.5, the HTML font-size=175px. 7.5rem is not 100%

## Here's part of my code
~index.html~
```
<script>
      !function(e){function t(a){if(i[a])return i[a].exports;var n=i[a]={exports:{},id:a,loaded:!1};return e[a].call(n.exports,n,n.exports,t),n.loaded=!0,n.exports}var i={};return t.m=e,t.c=i,t.p="",t(0)}([function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var i=window;t["default"]=i.flex=function(e,t){var a=e||100,n=t||1,r=i.document,o=navigator.userAgent,d=o.match(/Android[\S\s] AppleWebkit\/(\d{3})/i),l=o.match(/U3\/((\d |\.){5,})/i),c=l&&parseInt(l[1].split(".").join(""),10)>=80,p=navigator.appVersion.match(/(iphone|ipad|ipod)/gi),s=i.devicePixelRatio||1;p||d&&d[1]>534||c||(s=1);var u=1/s,m=r.querySelector('meta[name="viewport"]');m||(m=r.createElement("meta"),m.setAttribute("name","viewport"),r.head.appendChild(m)),m.setAttribute("content","width=device-width,user-scalable=no,initial-scale=" u ",maximum-scale=" u ",minimum-scale=" u),r.documentElement.style.fontSize=a/2*s*n "px"},e.exports=t["default"]}]);
      flex(100, 1);
    </script>
```

~config-overrides.js~
```
//加载postcss的pxtorem
  require('react-app-rewire-postcss')(config, {
    "plugins": loader => [
      require("postcss-pxtorem")({
        rootValue: 100,
        propWhiteList: [],
      })
    ]
  })
```

~theme property~
```
"hd": "2px",
```

### What is expected?
The adaption scheme should be 7.5rem with a ratio of 100% width at different resolutions

### What is actually happening?
The official high-definition solution was used. In iphone6, the HTML font-size=100px, so 7.5rem is 100% width. But on a device with a resolution of 441x823 DPR of 3.5, the HTML font-size=175px. 7.5rem is not 100%

**Comment by gmars** [comment]
在' antm-viewport.min.js'中是这样计算fontsize的(```doc.documentElement.style.fontSize = `${_baseFontSize / 2 * dpr * _fontscale}px`;```)，这样计算不能兼容所有设备。改成这样就可以按照750px的设计稿来适配(```r.documentElement.style.fontSize=(document.documentElement.clientWidth * a)/750 +"px"}```)。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
