### ISSUE TITLE
华为荣耀9青春版Datepicker改变“日列”后，点确定不触发onChange

### ISSUE THREAD

**Issue by daqi** [ant-design/ant-design-mobile#2920]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
华为荣耀9青春版

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/date-picker?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/date-picker?lang=zh-CN)

### Steps to reproduce
点开Datepicker,改变“日列”，点击确定

### What is expected?
日期改变

### What is actually happening?
日期没有改变

---
华为荣耀9青春版哪里阉割了？

**Comment by nathanvogel** [comment]
I'm consistently unable to change the value of a DatePicker using touch (mouse is ok) if it's inside a swipeable Tab.

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
