### ISSUE TITLE
ImagePicker在ios端，偶发现调取拍照上传图片时（偶尔会出现），造成页面卡死空白；

### ISSUE THREAD

**Issue by DuduStyle** [ant-design/ant-design-mobile#2921]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
ios12 

### Reproduction link
[https://mobile.ant.design/components/image-picker-cn/](https://mobile.ant.design/components/image-picker-cn/)

### Steps to reproduce
在真机点击上传图片，拍照-使用图片-卡死

### What is expected?
正常上传或者报错提示，或者是否可以在调取原生时设置某个参数，只保留浏览图片的功能，拍照功能取消；

### What is actually happening?
页面空白，卡死页面

**Comment by Ding-Jun** [comment]
有相同的问题

**Comment by dabenlu803** [comment]
+1

**Comment by eret9616** [comment]
.imagePicker {
.am-flexbox {
display: block;
// white-space: nowrap;
align-items: none;
overflow: none;
.am-flexbox-item {
flex: none;
width: 23%;
display: inline-block;
}
}
}

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
