### ISSUE TITLE
Toast cannot be closed when invoked multiple times with React 16

### ISSUE THREAD

**Issue by gera2ld** [ant-design/ant-design-mobile#2930]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
React 16

### Reproduction link
[https://gist.github.com/gera2ld/46a77f5c84188e988b1619d0e15aafc8](https://gist.github.com/gera2ld/46a77f5c84188e988b1619d0e15aafc8)

### Steps to reproduce
在一次渲染过程中连续触发几次 Toast ，会出现多个 Toast，且 `Toast.hide` 只能关闭最后一个。
```js
export default class App extends React.Component {
  componentWillMount() {
    Toast.info('hello', 0);
    Toast.info('hello', 0);
    Toast.hide();
  }

  render() {
    return null;
  }
}
```

### What is expected?
只展示一个toast，Toast.hide 可以关闭所有 toast

### What is actually happening?
展示了多个toast，且 Toast.hide 只能关闭最后一个 toast 。因为 React 16 下 ReactDOM.render 变成了异步操作。

**Comment by chauchakching** [comment]
Same here.

Temporary solution:
replace `Toast.hide()` by `setTimeout(Toast.hide)`

**Comment by hengkx** [comment]
@afc163 这个项目 还维护吗？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
