### ISSUE TITLE
大神请入：Module build failed:   ...    .encoded-svg-background('right');  ^ Inline JavaScript is not enabled. Is it set in your options?

### ISSUE THREAD

**Issue by alun-430** [ant-design/ant-design-mobile#2932]
**问题：**
引用 antd-mobile 组件，部分组件的  antd-mobile/lib/组件名/style/index.less  中只要存在
```
{
    ...
     .encoded-svg-background('....');
    ....
 }
```

就会报错
比如：

![image](https://user-images.githubusercontent.com/29272929/47907537-6a1d5c00-dec6-11e8-9a2c-73f48b8a887b.png)

为什么会产生这个：
项目架构：dva+antd 移动端项目
在配置 按需加载和自定义主题 完成之后，都已经生效。
但是引入antd-mobile的 Icon，Button会没有关系，引入List，InputItem...等会报错

**上代码：**
_入口文件 index.js：_
![image](https://user-images.githubusercontent.com/29272929/47907787-db5d0f00-dec6-11e8-8573-a01b9ddc76d6.png)

按需加载 和 配置自定义主题 文件配置(将 .webpackrc 文件改成了 .webpackrc.js 文件)：

![image](https://user-images.githubusercontent.com/29272929/47907917-27a84f00-dec7-11e8-9b15-f1d8961dd0b0.png)

主题文件配置：
/src/theme/default.less:

![image](https://user-images.githubusercontent.com/29272929/47908004-51fa0c80-dec7-11e8-9a7b-b670ad0a6c03.png)

./src/thene/theme.config.js:
![image](https://user-images.githubusercontent.com/29272929/47908041-6938fa00-dec7-11e8-9bf2-45afa3f77d14.png)

package,json 文件配置：
![image](https://user-images.githubusercontent.com/29272929/47908102-8968b900-dec7-11e8-9cbd-1c1946a8ffb6.png)

git项目代码：
https://github.com/alun-430/antdMobileCli.git

大神留步看一下，不胜感激！！！

**Comment by xuxuewen** [comment]
添加less-loader 配置，代码如下：

```javascript
 { 
   loader: "less-loader", 
    options: { 
        javascriptEnabled:true 
    } 
}
```
**javascriptEnabled** 这配置很重要
