### ISSUE TITLE
带间距的走马灯，其中第一幅图第二次以后的轮播都会卡顿一下，不流畅，不是无缝滑动。

### ISSUE THREAD

**Issue by LeezhiWen** [ant-design/ant-design-mobile#2933]

**Comment by DarkLove** [comment]
兄弟，这个问题我也问过，然而没人鸟我。

**Comment by LeezhiWen** [comment]
换了个插件，还可以 https://github.com/FormidableLabs/nuka-carousel

**Comment by shurong-kavout** [comment]
官网最新版本 demo 仍存在此问题

**Comment by shurong-kavout** [comment]
https://github.com/ant-design/ant-design-mobile/issues/3101

**Comment by shurong-kavout** [comment]
当设置了 infinite 属性，轮播图每次从尾图切换到首图（或首图切换到尾图），都会有停顿产生。
实际上是问题为：当设置了 infinite 属性，尾图和首图的相互切换，存在停顿不流畅现象

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
