### ISSUE TITLE
antd-mobile 在ios9,ios10上部分页面空白，无法显示

### ISSUE THREAD

**Issue by tanzhiling** [ant-design/ant-design-mobile#2936]
ios11登录页
![image](https://user-images.githubusercontent.com/31690439/47973927-f192e700-e0e1-11e8-9928-6aabce0c81a2.png)
ios10 登录页
![image](https://user-images.githubusercontent.com/31690439/47973934-fb1c4f00-e0e1-11e8-89a7-fc5d12dab831.png)
但是首页都可以显示
![image](https://user-images.githubusercontent.com/31690439/47973944-05d6e400-e0e2-11e8-9851-48f1602c61a9.png)
但大部分页面无法显示，之前以为是es6语法问题，但也加入babel-polyfill 依旧无效

**Comment by likezero** [comment]
具体看一下页面报错
