### ISSUE TITLE
why TabBar not position fixed?

### ISSUE THREAD

**Issue by allenpzx** [ant-design/ant-design-mobile#2937]
below is the situation
![image](https://user-images.githubusercontent.com/24787963/47977425-ec8a6380-e0f2-11e8-849f-b37078fdaa29.png)
![image](https://user-images.githubusercontent.com/24787963/47977439-fa3fe900-e0f2-11e8-8c4e-648a58708110.png)

no config and i find the document is description the default props tabBarPosition is 'bottom'
whatever i set props is not work
and i try to use css styled the component that the full screen can't click......
how to make the Tabbar position fixed on bottom

react version 16.5.2
ant-mobile version 2.2.5
used create-react-app to build this app

**Comment by assmdx** [comment]
Have you solved this problem ? I meet the same problem

**Comment by allenpzx** [comment]
![image](https://user-images.githubusercontent.com/24787963/48249800-1b784080-e437-11e8-9ac9-c0a233fa0405.png)
wrap a styled container but don't pass routes  in TabBar children

**Comment by allenpzx** [comment]
> Have you solved this problem ? I meet the same problem

![image](https://user-images.githubusercontent.com/24787963/48321185-a6d21b80-e65b-11e8-9a9d-135ec8e9505e.png)
wrap a styled container but don't pass route as children inside here
