### ISSUE TITLE
defaultValue doesn't work when the parameter visible doesn't switch in calendar component.

### ISSUE THREAD

**Issue by swk777** [ant-design/ant-design-mobile#2938]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
any

### Reproduction link
[https://codepen.io/swk777/pen/wQBmMB](https://codepen.io/swk777/pen/wQBmMB)

### Steps to reproduce
set visible to true at the first time

### What is expected?
defaultValue dates are selected

### What is actually happening?
defaultValue dates are not selected

**Comment by KingAmo** [comment]
same here:
```
this.state.visible && 
          <Calendar
            visible={true}
            onSelect={onDateSelect}
            defaultValue={[new Date(+now - 86400000 * 3),now]}
          />
```

when use `Calendar` like this, `defaultValue` do not work

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
