### ISSUE TITLE
TabBar tabBarPosition属性失效?

### ISSUE THREAD

**Issue by assmdx** [ant-design/ant-design-mobile#2940]
![image](https://user-images.githubusercontent.com/19722693/48036240-60377980-e1a2-11e8-85a2-8419befd7c7e.png)

**Comment by assmdx** [comment]
解决方法：
index.css :  
```
.am-tab-bar{
    position:fixed;
    bottom:0;
    width:100%;
}
```

在index.js中引入 index.css

```
import '../index.css'
```

**Comment by MattJin** [comment]
我看了下，是在2.2.6里面做了改动导致的。这是官方解决方案吗？

**Comment by Rookie-haoran** [comment]
> 我看了下，是在2.2.6里面做了改动导致的。这是官方解决方案吗？

2021年了那个属性还是失效，我服了
