### ISSUE TITLE
走马灯 滑动到边缘时如何禁止滑动 

### ISSUE THREAD

**Issue by yirenyiyi** [ant-design/ant-design-mobile#2941]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
iOS11.3 

### Reproduction link
[https://mobile.ant.design/components/carousel-cn/](https://mobile.ant.design/components/carousel-cn/)

### Steps to reproduce
带间距的走马灯，取消无限滑动和自动滑动，当在最左端时，手势向右滑动不松开，控件会跟手移动，会看不到控件，右侧同理

### What is expected?
走马灯 滑动到边缘时禁止继续向该方向滑动 

### What is actually happening?
走马灯 滑动到边缘时继续向该方向滑动 控件跟手滑动，导致页面看不到控件

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
