### ISSUE TITLE
Tabs组件设置了swipeable为true，distanceToChangeTab：0.8（任意值）。水平滑动时：如果手指滑动很快则一定会引起tab切换，滑动很慢时distanceToChangeTab才生效，当tab下的内容较长，手指上下滑动时该问题更明显，很容易引起误操作，本来是想上下滑动结果导致了切换tab

### ISSUE THREAD

**Issue by automation2013** [ant-design/ant-design-mobile#2943]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.2

### Environment
iOS 12.*  浏览器自带

### Reproduction link
[https://antd-mobile.gitee.io/components/tabs-cn/](https://antd-mobile.gitee.io/components/tabs-cn/)

### Steps to reproduce
<Tabs
                            distanceToChangeTab={0.8}
                            initialPage={initialPage}
                            tabs={TABS}
                            tabBarUnderlineStyle={{width: '20vw', marginLeft: '15vw'}}
                            onChange={this.onTabsChange}
                            renderTabBar={renderTabBar}
                        >
/**子组件**/
</Tabs>

### What is expected?
当手指横向滑动很快检测手指滑动的水平距离大于distanceToChangeTab时再切换tab

### What is actually happening?
水平滑动时：如果手指滑动很快则一定会引起tab切换，滑动很慢时distanceToChangeTab才生效，当tab下的内容较长，手指上下滑动时该问题更明显，很容易引起误操作，本来是想上下滑动结果导致了切换tab

---
麻烦解答后邮件告知（1271547283@qq.com）

**Comment by leetia316** [comment]
遇到同样的问题，望官方能给予解答

**Comment by leetia316** [comment]
找到一种方案： tab content所在的div，监听tachstart，tachend， 在tachend里面检查滑动的tan角度来确定当前滑动方向，如果是左右，则将 swipeable设为true，否则，设为false且阻止掉冒泡。 此方案有个弊端，下拉的时候容易出现卡在tab1和tab2之前这种情况， 如果产品不在意这个问题可以考虑试试...

**Comment by rootsli** [comment]
这个问题很影响体验，咋没人解决了~

**Comment by batchina** [comment]
这个问题有人解决了吗

**Comment by ShiChenCong** [comment]
same question

**Comment by weihomechen** [comment]
same question +1

**Comment by forforforStudy** [comment]
same question + 1

**Comment by eightHundreds** [comment]
这个问题在于, 手势速度太快会被判定为需要Swipe
https://github.com/react-component/gesture/blob/master/src/util.tsx#L60

有人尝试修复,但官方就是不管,诶,就是玩儿
https://github.com/react-component/m-tabs/pull/249

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by rongwei-alisa** [comment]
> v2 已停止维护了，可以考虑升级一下

v5支持swpie吗，滑动TabPane的内容区可以切换tab
