### ISSUE TITLE
modal with InputItem based on preact has render problem.

### ISSUE THREAD

**Issue by ehlilier** [ant-design/ant-design-mobile#2945]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
preact@8.3.1, umi@2.2.4

### Reproduction link
[https://github.com/ehlilier/umiForModal](https://github.com/ehlilier/umiForModal)

### Steps to reproduce
use umi@2.2.4 create a project,
use the modal and InputItem of antd-mobile@2.2.6
set the .umirc config with 'library: preact' 

### What is expected?
hope it can work normally

### What is actually happening?
The InputItem in the modal, when type sth, the modal disppeared.

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
