### ISSUE TITLE
能不能出个Flutter版的antd-mobile?

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-mobile#2946]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决用flutter快速搭建页面

### What does the proposed API look like?
闲鱼的大佬们更有经验

**Comment by a3596287** [comment]
Yes, can you do a Flutter version of the antd-mobile?
