### ISSUE TITLE
PullToRefresh how  get&set scroll position？

### ISSUE THREAD

**Issue by yyhuaisha** [ant-design/ant-design-mobile#2951]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
移动端浏览器

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/pull-to-refresh?lang=zh-CN#pull-to-refresh-demo-0](https://mobile.ant.design/kitchen-sink/components/pull-to-refresh?lang=zh-CN#pull-to-refresh-demo-0)

### Steps to reproduce
PullToRefresh 怎么获取滚动后的位置？

### What is expected?
获取和设置 PullToRefresh 的scrollTop

### What is actually happening?
没有找到可以设置scrollTop的方法

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
