### ISSUE TITLE
Ant design mobile listview uses body as a container to pull down the problem

### ISSUE THREAD

**Issue by Funny-dot** [ant-design/ant-design-mobile#2952]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
省略

### Reproduction link
[https:asasa.com](https:asasa.com)

### Steps to reproduce
Ant design mobile listview uses body as a container to pull down the problem

### What is expected?
使用listview 把body作为容器的时候，下拉刷新(pullToRefresh)有问题，下拉的时候停顿一次，拉一次停顿一次

### What is actually happening?
谷歌了，没找到结果，

**Comment by zhushichuan** [comment]
> I also have this problem, more serious than you, USES body as a container to pull down without reaction.

I canceled the pulldown refresh

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
