### ISSUE TITLE
PullToRefresh type error

### ISSUE THREAD

**Issue by jkvim** [ant-design/ant-design-mobile#2955]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
mac 10.14.1, chrome 70

### Reproduction link
[https://github.com/jkvim/WLM-TypeScript-React-Starter](https://github.com/jkvim/WLM-TypeScript-React-Starter)

### Steps to reproduce
复现代码
```jsx
<PullToRefresh
  damping={60}
  style={{
    height: this.state.height,
    overflow: 'auto',
  }}
  indicator={this.state.down ? {} : { deactivate: '上拉可以刷新' }}
  direction={this.state.down ? 'down' : 'up'}
  refreshing={this.state.refreshing}
  onRefresh={this.handleRefresh}
>

```

### What is expected?
如果没有传 getScrollContainer 或者 distanceToRefresh 则使用默认值，ts 类型检查没有报错

### What is actually happening?
如果没有传 getScrollContainer 或者 distanceToRefresh, 都会报错，因为 rmc-pull-to-refresh 定义的类型是必传的

**Comment by beierweiwei** [comment]
遇到同样的问题。

**Comment by abellee** [comment]
看来都不用ts写的啊

**Comment by franckXu** [comment]
遇到同样的问题,我暂时用下面来代码先把它们声明，来解决的
```
    getScrollContainer={() => undefined}
     distanceToRefresh={25}
```

**Comment by bytebook** [comment]
在vscode里，command顺着点进去，就找到interface了，一目了然
`export interface Indicator {
    activate?: React.ReactNode;
    deactivate?: React.ReactNode;
    release?: React.ReactNode;
    finish?: React.ReactNode;
}
export interface PropsType {
    getScrollContainer: () => React.ReactNode;
    direction: 'down' | 'up';
    refreshing?: boolean;
    distanceToRefresh: number;
    onRefresh: () => void;
    indicator: Indicator;
    prefixCls?: string;
    className?: string;
    style?: React.CSSProperties;
    damping: number;
}`

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
