### ISSUE TITLE
TabBar.Item scrolling will stop immediately when touch ended on Safari

### ISSUE THREAD

**Issue by Ding-Jun** [ant-design/ant-design-mobile#2957]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
IOS 12, Safari

### Reproduction link
[https://codepen.io/ding-jun/full/ZMgBbE/](https://codepen.io/ding-jun/full/ZMgBbE/)

### Steps to reproduce
1. TabBar.Item's content height > 100%
2. touch scroll the content 

### What is expected?
scrolling stop with ease animation

### What is actually happening?
scrolling stop immediately

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
