### ISSUE TITLE
建议：TabBar  是否可以添加一个隐藏tab-bar-bar方法~

### ISSUE THREAD

**Issue by Jessie-D** [ant-design/ant-design-mobile#296]
- antd-mobile 版本：0.8.5
- 操作系统及其版本：windows/mac
- 浏览器及其版本：chrome / safari
建议：TabBar  添加一个隐藏tab-bar-bar方法~

 am-tab-bar-bar 在主模块的时候显示，从主模块跳到详情页的情况下，底部的tabBar-bar 是不显示的，在回退到主模块的时候再显示

**Comment by silentcloud** [comment]
下个版本加入

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/pull/303/commits/beaedb859ea32aacf23a0b5cb33b514c22f3776c

**Comment by afc163** [comment]
`{this.state.visible ? <TabBar /> : null}`

直接交给父级控制感觉更合理一些。

**Comment by silentcloud** [comment]
@afc163 不行的，这样会把内容去也隐藏掉

**Comment by afc163** [comment]
hidden => barHidden or barVisible

**Comment by Jessie-D** [comment]
为什么0.9.0-beta加入了隐藏， 而1.0.0-alpha却没有加这个hidden呢

**Comment by GuangWuLin** [comment]
为什么 1.0.0 版本的 antd-mobile 不支持 TabBar 隐藏功能？

**Comment by silentcloud** [comment]
@GuangWuLin 有的啊

![test](https://cloud.githubusercontent.com/assets/1698185/23255056/19ab91e0-f9f5-11e6-8be6-897828fab0b9.gif)

**Comment by hellobbq** [comment]
能告诉我tabbar隐藏后，原来位置所在的浅灰色部分怎么让出来

**Comment by warmhug** [comment]
cc @zhang740
