### ISSUE TITLE
listview 不使用换行 里面的组件（List,Accordion）显示异常 会将整个页面撑开可以左滑

### ISSUE THREAD

**Issue by AlexJavaer** [ant-design/ant-design-mobile#2960]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
ant-design-mobile：2.2.6 浏览器：chrome

### Reproduction link
[http://22x692w132.imwork.net:44588](http://22x692w132.imwork.net:44588)

### Steps to reproduce
访问链接f12模拟手机页面

### What is expected?
可以实现在listview下不换行显示（多的内容隐藏）

### What is actually happening?
不换行全部显示并撑开页面

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
