### ISSUE TITLE
Add support for danish locale

### ISSUE THREAD

**Issue by michaelkrog** [ant-design/ant-design-mobile#2961]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The lack of danish locale.

### What does the proposed API look like?
I expect the API to be consistent with other locales.

**Comment by doxiaodong** [comment]
https://github.com/ant-design/ant-design-mobile/pull/2962

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
