### ISSUE TITLE
InputItem 中 type='digit'， maxLength 属性设置无效

### ISSUE THREAD

**Issue by wangwenyue** [ant-design/ant-design-mobile#2966]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
macOS 10.14.1 Chrome 70.0.3538 

### Reproduction link
[https://codepen.io/wangwenyue/pen/JeOaQB?editors=0010](https://codepen.io/wangwenyue/pen/JeOaQB?editors=0010)

### Steps to reproduce
在输入框输入 eeeeeeeee 

### What is expected?
不能输入除了数字和小数点以外的任何字符，并且输入长度不能超过5

### What is actually happening?
在已经设置type='digit'， maxLength={5} 的情况下，
在输入框输入 eeeeeeeee 可以正常显示

---
输入框要求只能输入正小数或正整数

**Comment by likezero** [comment]
digit 底层仍是type="number"，根据现有的浏览器特性。type="number"时不是所有浏览器都会校验字符的是不是有效的数字字符。
chrome目前是有校验的，但是你这个比较特殊，字母e 恰好是有效的数字字符，记得科学计数法中的e吗？

具体可以参考：
https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number
https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number)

**Comment by likezero** [comment]
你目前的需求可以在onchange中自行校验
