### ISSUE TITLE
“TabBar标签栏”组件的“与ListView结合使用”示例中，sectionIDs = [...sectionIDs];和rowIDs = [...rowIDs];这两个扩展运算符赋值是否多余？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-mobile#2969]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
win10、chrome70

### Reproduction link
[https://antd-mobile.gitee.io/components/tab-bar-cn/#components-tab-bar-demo-listview-tabbar](https://antd-mobile.gitee.io/components/tab-bar-cn/#components-tab-bar-demo-listview-tabbar)

### Steps to reproduce
1、打开链接 https://antd-mobile.gitee.io/components/tab-bar-cn/#components-tab-bar-demo-listview-tabbar   
2、点击“与ListView结合使用”示例的全屏显示按钮   
3、找到sectionIDs = [...sectionIDs];和rowIDs = [...rowIDs];两个语句，两个语句挨在一起的。   

### What is expected?
```
let sectionIDs = [];
let rowIDs = [];
//...
sectionIDs.push(sectionName);
rowIDs[ii].push(rowName);
//...
sectionIDs = [...sectionIDs];
rowIDs = [...rowIDs];
```   
   
上面的代码我是这样解读的：   
1、首先定义了sectionIDs和rowIDs两个空数组   
2、往两个数组里面push元素   
3、用扩展运算符把自己赋值给自己   
    
**问题：**      
不太明白第3步用扩展运算符再赋值一次的用意是什么。

**Comment by doxiaodong** [comment]
浅复制
