### ISSUE TITLE
建议：ImagePicker 图片选择，增加一个属性，是否显示上传按钮

### ISSUE THREAD

**Issue by miss61008596** [ant-design/ant-design-mobile#297]
#### 本地环境

－antd-mobile 版本："0.8.x"
－操作系统及其版本：OSX 10.11.6
－浏览器及其版本：Google Chrome 51.0.2704.63 (64-bit)

#### 你做了什么？

ImagePicker 图片选择

#### 你期待的结果是：

增加一个属性，是否显示上传按钮框，用以上传一定数量图片后将上传按钮隐藏，控制上传数量的限制
例如 disabled＝｛false||true｝

#### 实际上的结果：

没有相关的控制参数选项

#### 可重现的在线演示

目前自己加了一个简陋的处理方法生效

![image](https://cloud.githubusercontent.com/assets/6361237/18709975/be0730f0-803d-11e6-88ba-688c7479be86.png)

![image](https://cloud.githubusercontent.com/assets/6361237/18710078/3b82262a-803e-11e6-801a-99cccd1a6b69.png)

![image](https://cloud.githubusercontent.com/assets/6361237/18710086/46c5bfce-803e-11e6-90c3-f0697893db48.png)

![image](https://cloud.githubusercontent.com/assets/6361237/18710108/5ed5a3b8-803e-11e6-95f5-48d96f6458cc.png)

![image](https://cloud.githubusercontent.com/assets/6361237/18710122/6ab858a6-803e-11e6-8aef-ac74c287caa5.png)

![image](https://cloud.githubusercontent.com/assets/6361237/18710159/8e674ae6-803e-11e6-99ab-6494b319de35.png)

![image](https://cloud.githubusercontent.com/assets/6361237/18710177/a7d37040-803e-11e6-9c6b-6f6a33a1aeb4.png)

简单满足了只上传两张的需求，建议增加一个属性控制

**Comment by pingan1927** [comment]
有点道理，就是说超过最大值就隐藏选图按钮！记着了！

**Comment by silentcloud** [comment]
加个 max 的属性，disabled 这个属性不太合适 @pingan1927 @miss61008596

**Comment by miss61008596** [comment]
最大数自己控制就好了，也许不仅是数量场景不允许上传呢？假如是其他复杂场景max就不不好使了，应该添加的属性是各个场景都能使用，属性应该通用而精简，特定的就不通用了，@silentcloud

**Comment by yiminghe** [comment]
disabled 表示按钮致灰（需要实现）
隐藏按钮可以用 selectable={false}

@pingan1927

**Comment by pingan1927** [comment]
// todo

**Comment by pingan1927** [comment]
+ 了个`selectable`

**Comment by pingan1927** [comment]
`0.9.3`会上
