### ISSUE TITLE
“ListView长列表”的“body容器”示例代码，一个div的style有两个display属性，webstorm报错

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-mobile#2970]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
win10、chrome70

### Reproduction link
[https://antd-mobile.gitee.io/components/list-view-cn/#components-list-view-demo-basic-body](https://antd-mobile.gitee.io/components/list-view-cn/#components-list-view-demo-basic-body)

### Steps to reproduce
1、打开链接： https://antd-mobile.gitee.io/components/list-view-cn/#components-list-view-demo-basic-body   
2、全屏显示“body容器”示例   
3、按ctrl f，搜索 `display: '-webkit-box', display: 'flex'`   

**问题：**      
因为有两个display，所以webstorm提示duplicate declaration   

### What is expected?
期望得到确认这样写两个display正确与否。

### What is actually happening?
实际结果就是webstorm对这种写法有报错

**Comment by doxiaodong** [comment]
为了兼容性的问题，样式还是有 class 写
