### ISSUE TITLE
“ListView长列表”里面的“body容器”示例代码index = data.length - 1

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-mobile#2971]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
win10、chrome70

### Reproduction link
[https://antd-mobile.gitee.io/components/list-view-cn/#components-list-view-demo-basic-body](https://antd-mobile.gitee.io/components/list-view-cn/#components-list-view-demo-basic-body)

### Steps to reproduce
1、打开链接 https://antd-mobile.gitee.io/components/list-view-cn/#components-list-view-demo-basic-body   
2、全屏显示“body容器”示例
3、Ctrl+F 搜索 index = data.length - 1      

问题：   
下面这段代码：   
```
let index = data.length - 1;
    const row = (rowData, sectionID, rowID) => {
      if (index < 0) {  
        index = data.length - 1;
      }
//...
}
```
第1行声明变量index并赋值为data.length - 1。   
第3行if判断后，再次对index赋同样的值，作用是什么？   //问题

**Comment by zyfpopq** [comment]
我理解得第一行是获取数组中总共有多少个对象
第三行得index赋值是，在列表index取完之后（后面有个取数组中每一个对象是从后面向前取得，看数组[index-1]），然后又重新赋值，是循环列表得作用

**Comment by doxiaodong** [comment]
后续有操作 index-- 。
