### ISSUE TITLE
文档中“ListView长列表”的dataSource API链接失效

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-mobile#2972]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

**问题1：** 
文档中“ListView长列表”的dataSource API链接失效：https://mobile.ant.design/components/list-view-cn/#API   ，API表格的第一个属性 `dataSource`的说明有两个链接，一个404，一个不是对应的内容

**问题2：**   
“ListView长列表”的“ body容器”示例 https://mobile.ant.design/components/list-view-cn/#components-list-view-demo-basic-body ，里面的`cloneWithRows()`是怎么来的，ListView源码中没看到，webstorm也提示“Unresloved function or method”：

![snipaste_2018-11-25_14-59-10](https://user-images.githubusercontent.com/13177997/48976484-9726ee00-f0c3-11e8-8c60-5e2d487b23e5.png)

**Comment by doxiaodong** [comment]
https://github.com/ant-design/ant-design-mobile/blob/d3cbd3124c9bbe7bb40d8ac732a7844f4a9933fc/components/list-view/index.tsx#L23

**Comment by doxiaodong** [comment]
指向rn的链接失效了

**Comment by jackie19** [comment]
https://facebook.github.io/react-native/docs/listview.html

**Comment by jackie19** [comment]
![image](https://user-images.githubusercontent.com/2063608/50409010-14ac5e00-082a-11e9-8d2f-0a6c7ef7d710.png)
ListView有没有升级计划?
