### ISSUE TITLE
SegmentedControl 组件连续快速点击会出现，回调value值与页面选中的值不一致

### ISSUE THREAD

**Issue by lifengsbotlp** [ant-design/ant-design-mobile#2974]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
 
![image](https://user-images.githubusercontent.com/29885219/49019129-2ddcd300-f1c8-11e8-8dd0-a4966529f810.png)
![image](https://user-images.githubusercontent.com/29885219/49019162-451bc080-f1c8-11e8-803b-deb9f8b80205.png)

### Steps to reproduce
SegmentedControl 组件连续快速点击会出现，回调value值与页面选中的值不一致

### What is expected?
回调value值与页面选中的值一致

### What is actually happening?
回调value值与页面选中的值不一致

**Comment by doxiaodong** [comment]
https://github.com/ant-design/ant-design-mobile/issues/2973
