### ISSUE TITLE
the barStyle props doesn't work in the Progress 

### ISSUE THREAD

**Issue by wanliyunyan** [ant-design/ant-design-mobile#2977]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
chrome 70 react 16.6.3

### Reproduction link
[https://codepen.io/wanliyunyan/pen/JemQGG?&editors=001](https://codepen.io/wanliyunyan/pen/JemQGG?&editors=001)

### Steps to reproduce
<Progress percent={60} position="normal"barStyle={{backgroundColor:'red'}}  /></div>
<Progress percent={40} barStyle={{color:'red'}} position="normal" />

### What is expected?
期望进度条改变颜色

### What is actually happening?
但实际上这两个属性backgroundColor，color都不好使

**Comment by likezero** [comment]
进度条颜色是borderColor
```
const barStyle = {
      borderColor: 'red',
};
 <div className="progress"><Progress percent={percent} position="normal" barStyle={barStyle} /></div>
```
