### ISSUE TITLE
ListView 组件 如果数据为空 会报错

### ISSUE THREAD

**Issue by 763139102** [ant-design/ant-design-mobile#2978]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.2

### Environment
react

### Reproduction link
[http://10.15.100.21:3000/portal/theme?userId=19f5ef31-d2a6-43bb-ba52-9c4de73cc9b9&token=$2a$10$pba6Iu.4a3o5h56fOy4eUedyn4LZFLw&id=861195](http://10.15.100.21:3000/portal/theme?userId=19f5ef31-d2a6-43bb-ba52-9c4de73cc9b9&token=$2a$10$pba6Iu.4a3o5h56fOy4eUedyn4LZFLw&id=861195)

### Steps to reproduce
ListView 组件 如果数据为空 会报错

### What is expected?
如果是空，不应该报错

### What is actually happening?
ListView 组件 如果数据为空 会报错

**Comment by 763139102** [comment]
![111111111111](https://user-images.githubusercontent.com/25519902/49198145-cd6ab300-f3cc-11e8-8e4d-c6dd70e43f56.png)

**Comment by doxiaodong** [comment]
暂时可以不渲染组件
```
false && <ListView />
```
