### ISSUE TITLE
postcss-pxtorem 把我的样式px转为了rem，但是antd-mobile的样式px没有转为rem

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#298]
#### 本地环境

- antd-mobile 版本：
- windows·：
- chrome最新版：

#### 你做了什么？

引用了antd-mobile的高清方案

#### 你期待的结果是

像官网一样正常显示 

#### 实际上的结果：

页面确实“高清了”，但是由于`postcss-pxtorem`没有把antd-mobile的样式px转为rem，导致ant-m的组件看起来要小一号，但是自己写的组件，样式是正常的（`postcss-pxtorem`把我样式里的px转为rem了）。

#### 可重现的在线演示

https://github.com/minooo/React-Study/tree/master/step-03

这是我的配置地址，其实问题一句话就是，为什么`postcss-pxtorem`对antd-mobile的样式px转rem没有生效？ 该如何做？

**Comment by zhaotoday** [comment]
昨天晚上刚处理好高清问题，可以看看，希望对你有帮助：
https://github.com/zhaotoday/react-antd-mobile
在线地址：http://996.me/

**Comment by minooo** [comment]
@zhaotoday 谢谢，刚找到原因了，，，就是因为webpack需要加个这样的配置 
```
{
        test: /\.css$/,
        include: /node_modules/,
        loader: 'style!css!postcss'
      },
```

**Comment by wq199151** [comment]
{
                test: /\.css$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader!postcss")
            },

这样呢

**Comment by wq199151** [comment]
is not a PostCSS plugin
    at Processor.normalize (/Users/wangqian/Project/CBD_Project/node_modules/postcss/lib/processor.js:60:23)
    at new Processor (/Users/wangqian/Project/CBD_Project/node_modules/postcss/lib/processor.js:23:29)
    at Object.postcss (/Users/wangqian/Project/CBD_Project/node_modules/postcss/lib/postcss.js:55:12)
 @ ../~/antd-mobile/lib/modal/style/index.css 4:14-109



    module: {
        loaders: [
            {
                test: /\.js?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ['react', 'stage-2', 'es2015']
                },
                "plugins": [["import", {
                    "libraryName": "antd-mobile",
                    "libraryDirectory": "lib",
                    "style": "css"
                }]]
            },
            //{
            //    test: /\.css$/,
            //    loader: ExtractTextPlugin.extract("style-loader", "css-loader!postcss")
            //},
            {
                test: /\.css$/,
                loader: "style!css!postcss"
            },
            {
                test: /\.(gif|jpg|png|woff|svg|eot|ttf)\??.*$/,
                loader: 'url?limit=204800'
            }

        ]
    },
    postcss: [
        pxtorem({
            rootValue: 100,
            propWhiteList: [],
        }),
        require('postcss-font-magician')()
    ],

为什么不行呀

**Comment by SynChron1zed** [comment]
你好， {
    test: /\.css$/,
    include: /node_modules/,
    loader: 'style!css!postcss'
},
这个配置是在哪个文件里面加

**Comment by jiaozhouzhou** [comment]
请问这段代码
{
    test: /\.css$/,
    include: /node_modules/,
    loader: 'style!css!postcss'
},
是加到webpack.config.js 的哪里呢？

**Comment by benjycui** [comment]
感觉前端的工作流已经复杂到需要 IDE 托管了。。

**Comment by lichengit** [comment]
{
test: /.css$/,
include: /node_modules/,
loader: 'style!css!postcss'
},
这段代码加入到webpack.config.js 的什么位置？感觉都没地方放，跪求！

**Comment by SynChron1zed** [comment]
根本不需要这段代码

**Comment by lichengit** [comment]
我按照官网的高清方案设置
![image](https://cloud.githubusercontent.com/assets/19262380/23541832/ca76d9d2-0024-11e7-80a6-58c38aa9502b.png)

这是我出来的效果，小了好多倍，是缩放比例太大了吗？
![image](https://cloud.githubusercontent.com/assets/19262380/23541821/c18b8322-0024-11e7-9c6c-25a9039cc02b.png)

**Comment by pingan1927** [comment]
@lichengit 如截图，宽度只有375，表明高清方案设置没有生效。https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-以上版本「高清」方案设置 再根据wiki仔细推敲下哈

**Comment by lichengit** [comment]
@pingan1927  以ipone6为基准，控制台输出document.documentElement.clientWidth  为 750，好像是对的，但是还是有这个问题
![image](https://cloud.githubusercontent.com/assets/19262380/23543329/abe1cbd2-002c-11e7-806d-96557a1b306e.png)

**Comment by donggw2030521** [comment]
对于此类问题，webpack2和3当中，不支持支持在webpackConfig上扩展postcss属性，所以有三个方法
- 一个使用postcssrc,
```
{
  plugins: {
    "autoprefixer": {
      "remove": false,
      "browsers": [ 'iOS >= 8', 'Android >= 4' ],
    },
    "postcss-pxtorem":{
     rootValue: 100,
     propWhiteList: [],
    }
  }
}

```

- 一个使用postcss.config.js
```
module.exports = {
   plugins:{
"autoprefixer": {
      "remove": false,
      "browsers": [ 'iOS >= 8', 'Android >= 4' ],
    },
    "postcss-pxtorem":{
     rootValue: 100,
     propWhiteList: [],
    }
}
}
```

- 一个是在postcss-loader的option中使用postcss:()=>[]
```
 {
                    loader: 'postcss-loader',
                    options: {
                        ident: 'postcss', // https://webpack.js.org/guides/migrating/#complex-options
                        plugins: () => [
                            autoprefixer({
                               browsers: ['last 2 versions', 'Firefox ESR', '> 1%', 'ie >= 8', 'iOS >= 8', 'Android >= 4'],
                            }),
                            pxtorem({rootValue: 100, propWhiteList: ['*']})
                        ]
                    }
                },
```
