### ISSUE TITLE
h5在钉钉端修改title的时候，用document.title不起作用

### ISSUE THREAD

**Issue by misswyy** [ant-design/ant-design-mobile#2980]
![image](https://user-images.githubusercontent.com/17445601/49276366-48a99300-f4b9-11e8-93e9-1cedd14a112c.png)
用了这段代码，ios title可以正常切换，安卓不起作用

**Comment by rubyless** [comment]
钉钉端有api可以修改title

**Comment by doxiaodong** [comment]
这个跟 antd-mobile 没有关系吧

**Comment by misswyy** [comment]
这个是用react-antd开发的，然后把项目的url在钉钉端透出的，钉钉端的api用不了呀

**Comment by misswyy** [comment]
> 这个跟 antd-mobile 没有关系吧
项目是用的antd-mobile,只不过是在钉钉端透出的，类似于在微信端透出一样

**Comment by doxiaodong** [comment]
我是说你这个问题不是 antd-mobile 引起的

**Comment by WStreet** [comment]
@misswyy 请问一下这个问题是怎么解决的
