### ISSUE TITLE
index.d.ts文件写法有误

### ISSUE THREAD

**Issue by kwng** [ant-design/ant-design-mobile#2981]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
win7

### Reproduction link
[https://github.com/kwng/Antd-mobile-typescript.git](https://github.com/kwng/Antd-mobile-typescript.git)

### Steps to reproduce
编译时tslint会报错,提示react没有default export,原因是因为项目的index.d.ts文件都是使用import React from 'react' 而不是 import * as React from 'react'

### What is expected?
正确编译

### What is actually happening?
编译报错

**Comment by 26903651** [comment]
同样问题

**Comment by han3367775** [comment]
Typescript刚刚发布了3.2.1,应该是这个导致的. 之前 3.1.6版本之前都没有问题

**Comment by kwng** [comment]
在tsconfig.json中加了一条:
    "allowSyntheticDefaultImports": true
已经解决
