### ISSUE TITLE
Picker data(数据源) does not custom 'value' and 'label'?

### ISSUE THREAD

**Issue by zhaoqize** [ant-design/ant-design-mobile#2982]
**antd-mobule version: @latest**
**os: mac os**

issue:

my data like this:
```
const data = [
 {
   id: 1,
   text: '数字1',
 },
 {
  {
   id: 2,
   text: '数字2',
   }
 },
...
]
```

the API show 

![image](https://user-images.githubusercontent.com/17929687/49338829-7c73ec80-f662-11e8-8203-bb1fb9a88bd1.png)

the `value` 和 `label` filed must be? cannot customize them?

**Comment by doxiaodong** [comment]
The key must be value(for selected) and label(for show)
