### ISSUE TITLE
antd-mobile 2.1.8 Tabs underline position error 

### ISSUE THREAD

**Issue by fascinatedby** [ant-design/ant-design-mobile#2983]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
react-navtive:0.55.4

### Reproduction link
[https://codepen.io/kuroba12345/pen/eGJPaB](https://codepen.io/kuroba12345/pen/eGJPaB)

### Steps to reproduce
Click on the corresponding Tabs navigation, the font is highlighted, but the underline is always in the position of the first Tabs.
Looked at issues, but did not solve my problem, because my version is higher than the version on issues.

点击对应的Tabs导航，字体高亮，但下划线一直在第一个Tabs的位置上，
看了issues，但没有解决我的问题，因为我的版本比issues上的版本都要高

### What is expected?
Hopefully when switching, the underline will be cut over

希望当切换后下划线切过去

### What is actually happening?
The Tabs underline position error

**Comment by oMaten** [comment]
@fascinatedby Is that a problem reproduced on React-Native ?

**Comment by fascinatedby** [comment]
@oMaten 
yes,

**Comment by fascinatedby** [comment]
@oMaten 
yes,
