### ISSUE TITLE
DatePicker do not support second

### ISSUE THREAD

**Issue by XuChunxiao** [ant-design/ant-design-mobile#2984]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Set time format like 'hh:mm:ss' or 'YYYY-MM-DD hh:mm:ss', it is necessary for some cases such as timer.

### What does the proposed API look like?
add mode datesecond and timesecond

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
