### ISSUE TITLE
我想知道create-react-app 2+版本中，开启了cssModule后，cssModuleRegex该怎么配置才可以使得该UI的CSS生效

### ISSUE THREAD

**Issue by allfornaruto** [ant-design/ant-design-mobile#2985]

**Comment by allfornaruto** [comment]
没描述好，{
            test: cssRegex,
            exclude: cssModuleRegex,
            use: getStyleLoaders({
              importLoaders: 1,
                modules:true,//改动,css模块化
                localIdentName:'[name]_[local]_[hash:base64:5]'//改动,css模块化
            }),
          },
这段代码使得antd-mobile的css也加上了hash，然后就失效了，我该怎么做？

**Comment by doxiaodong** [comment]
antd-mobile 的样式不能加上 hash，
