### ISSUE TITLE
Listview  renderHeader 添加 Carousel 滑动 闪动

### ISSUE THREAD

**Issue by LubinPark** [ant-design/ant-design-mobile#2989]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
react 

### Reproduction link
[http:// null](http:// null)

### Steps to reproduce
  <ListView
         .....
          renderHeader={() => this._renderHeader(banners)}
       />

  _renderHeader(banners) {
     return (
        <Carousel className='am-list-header'
                  style={{width: '100%', height: 200}}
                  infinite autoplay
                  selectedIndex={0}
                  dotStyle={{marginBottom: 10}}
                  dotActiveStyle={{marginBottom: 10}}
                  autoplayInterval={3000}>
           <img className='home-carousel'
                     style={{width: '100%', height: 200}}
                     key={'banner' index}
                     src={banner.image.thumb200}/>
        </Carousel>
   )
}

###
//替换 antd css 中的样式
.am-list-header {
width: 100%;
  margin: 0px;
  padding: 0px;
  overflow: hidden;
}

### What is expected?
正常滑动

### What is actually happening?
滑动过程中 列表闪动，上下跳。不用Carousel 换其他的组件，自定义，三方，都是这样的。单独使用Carousel 和 listview 都能正常使用

**Comment by doxiaodong** [comment]
这个不是常规用法，暂时不支持的
