### ISSUE TITLE
现在官方的稳定版提供的是基于px布局的，我看官网提供的例子却是基于rem布局的，基于rem布局的版本能下载到么

### ISSUE THREAD

**Issue by minzhang2** [ant-design/ant-design-mobile#299]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/blob/a5ac2b1e155be8e9b7004620b54e9d528abf6a23/site/bisheng.config.js#L75-L79

**Comment by minzhang2** [comment]
现在基于mobile的框架配置说明太少了，能否适当的增加些说明文档

**Comment by pingan1927** [comment]
会陆续完善相关文档

**Comment by minzhang2** [comment]
用移动端遇到按需加载ant-mobile的相应组件的问题，能帮助解决下么

**Comment by pingan1927** [comment]
`const pxtorem = require('postcss-pxtorem');`

```
  webpackConfig.postcss.push(pxtorem({
    rootValue: 100,
    propWhiteList: [],
  }));
```

**Comment by pingan1927** [comment]
https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8%E9%AB%98%E6%B8%85%E6%96%B9%E6%A1%88%E5%AE%9E%E8%B7%B5

**Comment by minzhang2** [comment]
js依赖模块按需加载时怎么处理的，我搞了半天没搞出来
![image](https://cloud.githubusercontent.com/assets/15793061/18743846/953d04e6-80ed-11e6-997a-1fb78763ea02.png)

**Comment by pingan1927** [comment]
```
  webpackConfig.babel.plugins.push(['antd', {
    style: true, // if true, use less
    libraryName: 'antd-mobile'
  }]);
```

**Comment by minzhang2** [comment]
我现在是这样配置的
![image](https://cloud.githubusercontent.com/assets/15793061/18770643/ea6c3c7a-816a-11e6-885d-2348be7ce3b1.png)
但是我想做到官网demo的这种方式，想请教下怎么配置
![image](https://cloud.githubusercontent.com/assets/15793061/18770667/0b416448-816b-11e6-9dee-74883487070a.png)

**Comment by yiminghe** [comment]
参考 https://github.com/ant-design/ant-design-mobile/issues/56

**Comment by offbye** [comment]
同问，我们webapp也是用rem

**Comment by silentcloud** [comment]
@offbye 最新版本已经有 rem 版本了

**Comment by SynChron1zed** [comment]
@pingan1927  
const pxtorem = require('postcss-pxtorem');

  webpackConfig.postcss.push(pxtorem({
    rootValue: 100,
    propWhiteList: [],
  }));

为什么我配置这个项目就报错

**Comment by pingan1927** [comment]
install 这个模块了吗
