### ISSUE TITLE
tabs组件在安卓上体验很不友好！

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design-mobile#2991]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当内容区域过多，快速向上滚动的时候，tabs组件会出现闪动，ios正常，安卓很不友好！

### What does the proposed API look like?
体验友好！！

**Comment by xcyn** [comment]
解决了？

**Comment by steady-join** [comment]
> 解决了？

目前不清楚，反正现在移动端基本手写UI，没用这个库了。

**Comment by xcyn** [comment]
> > 解决了？
> 
> 目前不清楚，反正现在移动端基本手写UI，没用这个库了。

我这边解决了，我这边不是定位到不是组件库的问题，是安卓webview的问题，安卓关闭了硬件加速导致的问题，打开硬件加速就可以了。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
