### ISSUE TITLE
what about add jsdoc?

### ISSUE THREAD

**Issue by rainmanhhh** [ant-design/ant-design-mobile#2992]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
improve ide tips

### What does the proposed API look like?
just add jsdoc for existing classes & functions

**Comment by doxiaodong** [comment]
You need a typescipt friendly editor just like vscode. And sorry for that we do not consider jsdoc recently.
