### ISSUE TITLE
修改组件样式

### ISSUE THREAD

**Issue by DarkLove** [ant-design/ant-design-mobile#2993]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
官方的组件样式修改及其不方便。比如 InputItem ，当我在几个页面都是使用了他的情况下，由于设计上的原因，在每个页面需要该控件的高度是不一样的。但是我现在就只能覆盖这个控件的class,但是这样也只是符合其中一个页面的高度需求，求解其他几个页面的该控件高度怎么办？？？？

### What does the proposed API look like?
能够提供一个属性修改样式

**Comment by ziluo** [comment]
是否可以详细提供一下你期望的实现方式，一起评估下技术实现可能性
