### ISSUE TITLE
Accordion手风琴箭头icon是否改为字体图标

### ISSUE THREAD

**Issue by six-666** [ant-design/ant-design-mobile#2994]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前手风琴的右侧箭头是采用的背景图片实现的，这样就太死了。 想改颜色都得替换默认的图标， 应该采用字体图标。

### What does the proposed API look like?
 应该采用字体图标，从而更灵活。

**Comment by doxiaodong** [comment]
现在用的 svg 做的背景，确实不好改颜色。如果想改的话，可以复写样式。可以参考 https://github.com/ant-design/ant-design-mobile/blob/master/components/style/mixins/icon.less#L35
