### ISSUE TITLE
Popover点击穿透问题，会触发蒙层下的事件！！！

### ISSUE THREAD

**Issue by hst-Sunday** [ant-design/ant-design-mobile#2995]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
IOS最新版，Android6.0以上

### Reproduction link
[https://codepen.io/hst-Sunday/pen/aPdYPX](https://codepen.io/hst-Sunday/pen/aPdYPX)

### Steps to reproduce
打开重现连接，F12开发模式，点击Toggle device toolbar切换为移动模式，点击第二行按钮

### What is expected?
点击后蒙层关闭，不触发蒙层下的DOM事件

### What is actually happening?
点击后蒙层关闭，触发蒙层下的DOM事件

**Comment by lgbcscs** [comment]
同问，是否有方案

**Comment by huangguan1996** [comment]
很急，有没有其他解决的方法

**Comment by dc198689** [comment]
@likezero @doxiaodong @zack24q 
求跟進, 或者有沒有另一點取巧的方法暫代使用
萬分感謝

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
