### ISSUE TITLE
vivo x9  imagepicker选择图片后不回显

### ISSUE THREAD

**Issue by 406224330** [ant-design/ant-design-mobile#2998]
Version
2.2.6

Environment
手机：vivo x9 系统：funtouch OS 安卓版本：7.1.2 微信内置浏览器

Reproduction link
https://mobile.ant.design/kitchen-sink/c
![_20181217101749](https://user-images.githubusercontent.com/21120585/50062976-08e6e900-01e5-11e9-8951-a309ea622254.jpg)
omponents/image-picker

Steps to reproduce
imagepicker点击进入图库选择完成图片后回到当前页，图片不回显。

What is expected?
目前发现这个手机有这个问题，希望能正常选择图片回显。

What is actually happening?
选择图片后图片不回显

**Comment by YangHeLi** [comment]
你使用imagepicker 可以拿到手机给你返回的数据？

**Comment by stelalae** [comment]
我也遇到了，antd-mobile的版本号是2.1.10。使用ImagePicker选择照片后，照片在ImagePicker上显示白屏。

**Comment by stelalae** [comment]
![image](https://user-images.githubusercontent.com/5012217/52842035-c84e1200-3138-11e9-8926-72a7f2544fdd.png)

**Comment by eret9616** [comment]
解决方法:

// imagePicker *flex布局 bug
.imagePicker {
    .am-flexbox {
        display: block;
        white-space: nowrap; 
        align-items: none;
        overflow: none;
        .am-flexbox-item {
            flex: none;
            width: 23%;
            display: inline-block;
        }
    }
}

**Comment by zjdschnappi** [comment]
anyone can give a solution for this?

**Comment by stelalae** [comment]
> anyone can give a solution for this?

我用上面的样式就可以了

**Comment by zjdschnappi** [comment]
> > anyone can give a solution for this?
> 
> 我用上面的样式就可以了

上面的样式 把原来的flex布局 直接换成inline-block 了 就是因为flex的原因吗 ？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
