### ISSUE TITLE
加入Bootstrap (v4.1.3) 框架后，Button border 会出现部分不显示的问题

### ISSUE THREAD

**Issue by hezzze** [ant-design/ant-design-mobile#2999]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
macOS 10.14.1, chrome Version 70.0.3538.110, react 16.6

### Reproduction link
[https://codepen.io/hezzze/pen/OrXmOE](https://codepen.io/hezzze/pen/OrXmOE)

### Steps to reproduce
加入 Bootstrap CSS 后问题出现

### What is expected?
Button border 应该完整显示

### What is actually happening?
Button 右边border 消失，详见附上的codepen链接

---
很棒的框架，感恩开源，加油👍

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
