### ISSUE TITLE
官方脚手架 MobileDemo 无法运行：无法找到 antd-mobile

### ISSUE THREAD

**Issue by qiuchengw** [ant-design/ant-design-mobile#300]
#### 本地环境

- antd-mobile 版本：0.8.5
- 操作系统及其版本：android 4.4

#### 你做了什么？

从https://github.com/ant-design/antd-init 下载项目，进入 MobileDemo，进行npm install。
执行react－native run－android

#### 你期待的结果是：

像官网一样正常显示 

#### 实际上的结果：

编译通过，在android虚拟机上提示错误：require unknown module 'antd-mobile'

-------------------
原来的项目使用的0.7x版本的antd，后来升级到0.8.5 之后就不行了，都是提示antd-mobile找不到。

**Comment by yiminghe** [comment]
用这个 https://npm.taobao.org/

**Comment by qiuchengw** [comment]
@yiminghe 有什么不同吗？这个是在运行期间提示找不到 antd-mobile。不是npm 找不到antd-mobile

**Comment by qiuchengw** [comment]
已回退到0.8.2 一切正常。

**Comment by zhaoyao91** [comment]
@qiuchengw 我查看了一下package.json，里面没有main声明，所以无法直接import包名。
