### ISSUE TITLE
InputItem软键盘唤起，完成隐藏后，依然占据页面；

### ISSUE THREAD

**Issue by DuduStyle** [ant-design/ant-design-mobile#3000]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
ios12 

### Reproduction link
[https://mobile.ant.design/components/input-item-cn/#components-input-item-demo-error](https://mobile.ant.design/components/input-item-cn/#components-input-item-demo-error)

### Steps to reproduce
官网扫码手机输入内容，点击软键盘右侧完成按钮；

### What is expected?
正常回滚

### What is actually happening?
不会回滚，需要手动划一下；

**Comment by DuduStyle** [comment]
![img_9733](https://user-images.githubusercontent.com/31200868/50129540-541bfd00-02b4-11e9-91b5-ef7393309a43.PNG)
![img_9732](https://user-images.githubusercontent.com/31200868/50129542-58e0b100-02b4-11e9-8f18-22c122979f40.PNG)

**Comment by doxiaodong** [comment]
Cannot reappear on IOS 12.1.1 6sp Safari. Please provide the complete env.

**Comment by DuduStyle** [comment]
@doxiaodong 官方的这个就能复现，你输入手机号码那的值，然后点击完成即可看到效果   
The official one reappears, you enter the value of your phone number and click finish to see the effect

**Comment by thewindsword** [comment]
我提交的PR应该可以暂时解决这个问题，并且该问题目前应该仅出现在微信端页面。
#3017
