### ISSUE TITLE
TabPane do not works!!!!

### ISSUE THREAD

**Issue by uraidiot** [ant-design/ant-design-mobile#3003]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
macOS Chrome Version 70.0.3538.102

### Reproduction link
[https://codepen.io/anon/pen/REGYGm?editors=1111](https://codepen.io/anon/pen/REGYGm?editors=1111)

### Steps to reproduce
import { Tabs } from 'antd-mobile";

const { TabPane } = Tabs;

console.log('TabPane', TabPane);

### What is expected?
TabPane is an element;

### What is actually happening?
undefined

**Comment by uraidiot** [comment]
https://mobile.ant.design/docs/react/introduce-cn,
https://design.alipay.com/develop/mobile/introduce
different??

**Comment by likezero** [comment]
please visit https://mobile.ant.design/components/tabs-cn/ for help
