### ISSUE TITLE
rmc-trigger touchOutsideHandler.remove 会抛异常

### ISSUE THREAD

**Issue by swchen** [ant-design/ant-design-mobile#3004]
* [x]  I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
设备: Huawei/Huawei EML-AL00 
操作系统: Android 8.1.0 
客户端: DingTalk 4.6 
内核版本: 0.5.3

### What is actually happening?
https://github.com/react-component/m-trigger/blob/e001ce7fcd5dc805e970bbfdd5031f0f52769d68/src/Trigger.tsx#L87

this.touchOutsideHandler.remove();  抛出异常: `this.touchOutsideHandler.remove is not a function`

### 原因
https://github.com/react-component/m-trigger/blob/e001ce7fcd5dc805e970bbfdd5031f0f52769d68/src/Trigger.tsx#L74

`setTimeout` 返回的是 timeout id

**Comment by ziluo** [comment]
same question: https://github.com/ant-design/ant-design-mobile/issues/3004
