### ISSUE TITLE
DatePickerView 国际化不了

### ISSUE THREAD

**Issue by ningjianwen** [ant-design/ant-design-mobile#3005]
在做国际化的时候，发现DatePickerView 这个组件国际化不了，其他组件的国际化都已经生效了。

**Comment by ziluo** [comment]
需要支持哪些语言，马上跟进

**Comment by ningjianwen** [comment]
英文的设置了不生效，泰文的没有找到对应的语言标识。

在 2018-12-20 11:35:39，"Ziluo" <notifications@github.com> 写道：


需要支持哪些语言，马上跟进

**Comment by cca313** [comment]
在加入LocaleProvider之后，语法检查报错 
`ERROR in /mnt/projects/m-catmall-universal/node_modules/antd-mobile/lib/locale-provider/en_US.d.ts(52,22):
TS2307: Cannot find module '../../../../../../Users/ziluo/github/ant-design-mobile/node_modules/rmc-calendar/lib/date/DataTypes'.`

**Comment by doxiaodong** [comment]
@cca313  可以先设置 skipLibCheck 绕过

**Comment by doxiaodong** [comment]
@ziluo

**Comment by ningjianwen** [comment]
> 英文的设置了不生效，泰文的没有找到对应的语言标识。 在 2018-12-20 11:35:39，"Ziluo" <notifications@github.com> 写道： 需要支持哪些语言，马上跟进 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

需要支持泰语，不过项目组已经在二月中旬解散了，为后来人提供便利吧。

**Comment by HamHwong** [comment]
近期有国际化泰语的计划么?
