### ISSUE TITLE
Export Lib Depending on Projects having allowSyntheticDefaultImports=true

### ISSUE THREAD

**Issue by larkintuckerllc** [ant-design/ant-design-mobile#3006]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.6

### Environment
N/A

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
In the Ant Design Mobile npm package, the files, e.g., 

`lib/button/index.d.ts` uses a React import like:

`import React, { CSSProperties, MouseEventHandler } from 'react';`

In the similar Ant Design npm package, the files, e.g., 

`lib/button/button.d.ts` uses a React import like:

`import * as React from 'react';`

The implication is that projects, e.g., Framer X, that don't have the TS compiler option `allowSyntheticDefaultImports` set, will fail.

While I have reported an issue to Framer X that they should be using `allowSyntheticDefaultImports`, it looks like the folks on the  Ant Design project solved this problem by using the safer way of importing React.

### What is expected?
In the Ant Design Mobile npm package, the files, e.g., 

`lib/button/index.d.ts` should use a React import like:

`import * as React from 'react';`

And references to `CSSProperties`, etc. should be changed to `React.CSSProperties`.

### What is actually happening?
In the Ant Design Mobile npm package, the files, e.g., 

`lib/button/index.d.ts` uses a React import like:

`import React, { CSSProperties, MouseEventHandler } from 'react';`

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
