### ISSUE TITLE
Calendar The close and clear buttons when customizing the renderHeader are gone and the clear event cannot be performed

### ISSUE THREAD

**Issue by lilixikun** [ant-design/ant-design-mobile#3007]

**Comment by LiLixikun** [comment]
I can't do this when I want to perform a cleanup event on a custom renderHeader on Calendar

**Comment by LiLixikun** [comment]
@ant-design-bot 就是当我自定义了renderHeader后 想实现清除事件，查看源码只有清除后的回调函数 该组件只暴露了默认defaultValue 能否提供 Value属性 供使用者自己重置清空。

**Comment by awmleer** [comment]
看起来这个问题 v5 已经解决了
