### ISSUE TITLE
ImagePicker图片上传通过capture属性限制只能拍照上传

### ISSUE THREAD

**Issue by Twining** [ant-design/ant-design-mobile#3008]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用上传某些图片时需要获取的是当时拍照的图片，而不是相册图片，使用capture属性可以限制前置拍照，后置拍照。

### What does the proposed API look like?
<ImagePicker
    files={files}
   onChange={()=>{}}
   onImageClick={()=>{}}
   selectable={false}
   multiple={false}
  capture='camera'
 />

**Comment by stelalae** [comment]
同求此功能

**Comment by stelalae** [comment]
临时解决办法，在有ImagePicker的页面增加 
```
  componentDidMount () {
    const sda = document.getElementsByTagName('input');
    for (let index = 0; index < sda.length; index++) {
      const element = sda[index];
      element.setAttribute("capture", true); 
    }
  }
```
