### ISSUE TITLE
表格在微信中无法横向滚动

### ISSUE THREAD

**Issue by summerinsect** [ant-design/ant-design-mobile#301]
微信版本：6.3.15

**Comment by warmhug** [comment]
建议使用其他组件替代 table，移动端用 table 只适合简单场景、不需要滚动。

@afc163 看看是不是 rc-table 的问题。

**Comment by silentcloud** [comment]
@warmhug 我这会正好在看这个问题，先等我瞅瞅

**Comment by warmhug** [comment]
关联 #169

**Comment by silentcloud** [comment]
最终确认只在 iOS  真机 webView 会出现，解决方法：只能手动给 table 元素加一个 min-width: 200% 之类的，这个样式也不能写死在 less 里，放在用户自己来设置样式吧 @summerinsect

**Comment by warmhug** [comment]
可以改下 demo @silentcloud

**Comment by silentcloud** [comment]
@warmhug ok

**Comment by silentcloud** [comment]
上面的解决方法后来发现锁定标题列处理不了，原因是：

![image](https://cloud.githubusercontent.com/assets/1698185/20007629/106e74ae-a2d8-11e6-83fc-09af3d0e4305.png)

代码里 style 写死了宽度，去除 width，min-width 设置为 100% 就正常了

@afc163 看哈 col 写成 min-width: 100%  有什么影响

**Comment by afc163** [comment]
@yesmeck 来看下。

**Comment by silentcloud** [comment]
@yesmeck  是否有进展？

**Comment by yesmeck** [comment]
囧，没注意这里有 issue，我等会看看。

**Comment by yesmeck** [comment]
> 最终确认只在 iOS 真机 webView 会出现

这个要怎么重现？

**Comment by afc163** [comment]
https://github.com/react-component/table/commit/e4aea833abe504d0f7b9acac9602791650c92ce3

当时加了 minWidth 貌似是解决某些浏览器的排版问题。

**Comment by silentcloud** [comment]
@yesmeck  支付宝钱包，扫码打开

**Comment by yesmeck** [comment]
我用支付宝和微信试了官网里横向滚动的例子都没问题。

iOS：10.11

支付宝：9.9.6

微信：6.3.31

**Comment by silentcloud** [comment]
@yesmeck 用 iphone plus，chrome 的调试器，plus 就有问题，貌似会出现在 plus 下面

**Comment by silentcloud** [comment]
这个关掉了，是 demo 数据在 plus 下数据太少导致的，我加点数据
