### ISSUE TITLE
Carousel 走马灯样式问题

### ISSUE THREAD

**Issue by shengxiao3587** [ant-design/ant-design-mobile#3019]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/tree/master/components/carousel](https://github.com/ant-design/ant-design-mobile/tree/master/components/carousel)

### Steps to reproduce
指示点位置问题

### What is expected?
希望让指示点位置可配置

### What is actually happening?
现在的指示点位置统一在整个组件的下方，且该定位样式是内联样式，外部不好覆盖。

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.4.2 |
| System | mac os |
| Browser | Chrome |

---
希望尽量减少内联样式的使用，这样在即使没有可配置的参数，在样式上我们使用时也可以做一些改动以适应自己的需求。

**Comment by miaoyuxinbaby** [comment]
@shengxiao3587 内联样式可以通过 !important 覆盖

**Comment by shengxiao3587** [comment]
> @shengxiao3587 内联样式可以通过 !important 覆盖

!important过于丑陋和暴力，应该尽量减少使用

**Comment by miaoyuxinbaby** [comment]
@shengxiao3587  我觉得，单独针对某个页面的某个 Carousel , 做好样式命名空间的隔离，完全是可以使用!important的。这并无大碍、

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
