### ISSUE TITLE
关于最新版本 0.9.2 的组件 Carousel 的高度问题，急！急！急！

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#302]
此前列举的问题新版本已经修复，占位一楼，具体问题请看二楼~

**Comment by minooo** [comment]
Great work~

**Comment by minooo** [comment]
@yiminghe @foriacus @silentcloud 后续，0.8.6版本中，组件Carousel依旧有一个问题。**就是当路由切换后，Carousel 组件只显示dots，等待数秒后图片才会显示出来（这让人感觉很不爽！），这个问题，版本0.8.5中也存在，当我把版本会退到0.8.2时候，就不会出现这种问题**。为了更好的说明问题，我做了gif。

0.8.6 版本下（这感觉让人难受）
![1](https://cloud.githubusercontent.com/assets/9410091/18790235/97339a6e-81e0-11e6-95a6-176bc0377d2a.gif)

-------------------------------------------

0.8.2 版本下（这是我想要的感觉）
![2](https://cloud.githubusercontent.com/assets/9410091/18790179/643f0b70-81e0-11e6-94f3-830b3c754ef8.gif)

**Comment by foriacus** [comment]
加initialSlideHeight试试呢？https://github.com/FormidableLabs/nuka-carousel#props

**Comment by minooo** [comment]
@foriacus  `initialSlideHeight` 在0.8.6下无效。不过我觉`initialSlideHeight`即便有效，也不是解决这个问题的最好办法，因为这定死了组件Carousel的高度。而实际中的carousel 应该随着设备屏幕宽度的不同，它的高度也应该会有所不同。（类似于等比例缩放）

另外意外发现，版本0.8.6中 选项 `dots`的值无论是true还是false。这个指示器始终显示！ antd-mobile 版本会退到0.8.2后，此问题不存在。选项`autoplaySpeed`也有类似问题。当然不排除其他属性也有此问题。

**Comment by hnsylitao** [comment]
你可以先把里面高度固定死。

**Comment by minooo** [comment]
@hnsylitao @foriacus @yiminghe  高度固定死当然能“解决”，比如固定高度300px，接着，这个全屏宽的图片在iphone5下，高度是300px，在iphone6 plus下高度还是300px，然而图片的宽度是随着设备的宽度变化而变化，这就导致了图片的令人难以接受的**变形**问题，而不是想要的**自适应**。

**Comment by warmhug** [comment]
`initialSlideHeight`如果只是初始高度，随后的高度、应该是要根据图片在不同屏幕下的尺寸而改变的，这个 initialSlideHeight 是否有问题？或者设置`min-height`能否解决？ @minooo @foriacus

**Comment by minooo** [comment]
@yiminghe 0.9+ 下依然有此问题，0.8.2下此问题不存在，望修复。

**Comment by warmhug** [comment]
0.9 哪个有问题？NavBar 还是 Carousel ，描述要清楚点

**Comment by minooo** [comment]
@warmhug 好的，此问题在二楼有说明，已@你了。麻烦看下，谢谢了。

**Comment by afc163** [comment]
新问题应该开 issue 。

旧的问题不影响移除，影响沉淀和搜索引擎。

**Comment by minooo** [comment]
@afc163 我看版本更新修复了，就懒省事儿了，以后注意了，多谢提醒！
