### ISSUE TITLE
IOS上InputItem过多，打开软键盘，收回时底部有个跟键盘等高的黑色背景块，官网例子打开也有这问题

### ISSUE THREAD

**Issue by wangmingdong** [ant-design/ant-design-mobile#3020]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item?lang=zh-CN#input-item-demo-0](https://mobile.ant.design/kitchen-sink/components/input-item?lang=zh-CN#input-item-demo-0)

### Steps to reproduce
IOS 支付宝打开如上链接，focus输入框，打开系统默认键盘，然后点击ok关闭，此时页面底部出现和键盘等高的黑色背景块；

### What is expected?
键盘关闭样式正常

### What is actually happening?
底部出现和键盘等高的黑色背景块

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 15.4.2 |
| System | IOS 12.1.2 |
| Browser | 70.0.3538.110（正式版本） （64 位） |

---
微信默认浏览器打开正常，安卓正常，IOS才会出现

**Comment by wangmingdong** [comment]
![img](http://static.weqianduan.com/WechatIMG15.jpeg)

**Comment by wangmingdong** [comment]
补充一下，支付宝10.1.3打开是正常的，最新版本10.1.52打开会有此问题

**Comment by socalledPF** [comment]
今天也遇到了这个问题，这个是部分ios支付宝环境特有的，这个库作者应该没法解决这个问题。

**Comment by JayenLee** [comment]
IOS 12.1.4 的都有吧，我这边也有，你们是不是做了定位，然后没有办法恢复

**Comment by pimkle** [comment]
刚刚出现了同样的问题，检查项目代码后，发现页面里某一层 div，高度是用 js 计算的屏幕高度，估计是 iOS 某些 App 内嵌 webview 返回的屏幕高度没有及时更新引起的。把该 div 的高度从用 js 计算改为用 CSS 的 100vh 得以解决。另一个解决方案是 scrollTo(0, 0)。但是还是得找到带黑块的那个 div，把 div 设定为不可滚动，才能防止用户往下滚的时候又看到黑块。

**Comment by gdabs** [comment]
> IOS 12.1.4 的都有吧，我这边也有，你们是不是做了定位，然后没有办法恢复
现在我iphonex微信打开一直是键盘隐藏了多了个空白地方，你们是怎么解决的

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by fraser666** [comment]
这个问题在最新版上解决了么？
