### ISSUE TITLE
about New version antM use Svg  way className should use className={am-icon am-icon-${type.default.id}

### ISSUE THREAD

**Issue by ghost** [ant-design/ant-design-mobile#3025]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/docs/react/upgrade-notes-cn#1.x-=%3E-2.0](https://mobile.ant.design/docs/react/upgrade-notes-cn#1.x-=%3E-2.0)

### Steps to reproduce
`const CustomIcon = ({ type, className = '', size = 'md', ...restProps }) => (
    <svg
      className={`am-icon am-icon-${type.substr(1)} am-icon-${size} ${className}`}
      {...restProps}
     >
       <use xlinkHref={type} /> {/* svg-sprite-loader@0.3.x */}
       {/* <use xlinkHref={#${type.default.id}} /> */} {/* svg-sprite-loader@latest */}
     </svg>
 );
 <CustomIcon type={require('./foo.svg')} />`

### What is expected?
期望能够正确的显示出该svg图片

### What is actually happening?
实际结果并不能正确显示该svg图片

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.X |
| System | mac |
| Browser | chrome 56 |

---
此时当.roadhogrc已经配置好相关的svg打包设置后，该svg图片并不能正确的显示。 问题出现在
` <svg
      className={`am-icon am-icon-${type.substr(1)} am-icon-${size} ${className}`}
      {...restProps}`
在svg-sprite-loader@latest 的最近版本中 type.substr(1)已经不存在 只存在type.default 对象 
` <svg
      className={`am-icon am-icon-${type.default.id} am-icon-${size} ${className}`}
      {...restProps}`

**Comment by zhangchinhan** [comment]
any body fixed this issued ?

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
