### ISSUE TITLE
2.2.7版本更新后，InputItem onChange事件无法监听。

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design-mobile#3026]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zhang504988670/pen/QzqQBe](https://codepen.io/zhang504988670/pen/QzqQBe)

### Steps to reproduce
在输入框内输入内容，调用onChange事件，渲染setState方法。

### What is expected?
能够正常调用onChange事件

### What is actually happening?
onChange事件不触发。

| Environment | Info |
|---|---|
| antd | 2.2.7 |
| React | React16.7.0 |
| System | win10 |
| Browser | chrome71.0.3578.80 |

**Comment by ziluo** [comment]
OK，马上跟进处理下 @zack24q

**Comment by ziluo** [comment]
已发布`2.2.8`解决该问题

**Comment by bobbychan** [comment]
刚装了2.2.8，用rc-form的getFieldDecorator包裹的input还是无法触发onChange, getFieldProps是可以触发的

**Comment by zack24q** [comment]
@bobbychan 能否提供一个复现链接呢？

**Comment by bobbychan** [comment]
不好意思，刚做复现例子的时候发现又正常了
