### ISSUE TITLE
Carousel item missing when the props infinite ,slideWidth and cellSpacing be set in small width box

### ISSUE THREAD

**Issue by rojer95** [ant-design/ant-design-mobile#3028]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/rojer95/pen/OrOPbb](https://codepen.io/rojer95/pen/OrOPbb)

### Steps to reproduce
Like recreating the parameter settings in the demo while the width of the parent box is small (eg 750px)

### What is expected?
carousel item will not miss

### What is actually happening?
carousel item missing
![image](https://user-images.githubusercontent.com/20662049/50546280-01e9bd00-0c60-11e9-9fef-bfb922fdcfa4.png)

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16 |
| System | window 10 |
| Browser | chrome |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
