### ISSUE TITLE
 ListView组件，用reack hooks重写，ReactDOM.findDOMNode(this.lv)应该怎么修改？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-mobile#3029]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/tab-bar-cn/#components-tab-bar-demo-listview-tabbar](https://mobile.ant.design/components/tab-bar-cn/#components-tab-bar-demo-listview-tabbar)

### Steps to reproduce
1、打开重现链接
2、在“与ListView结合使用”代码中，搜索`ReactDOM.findDOMNode(this.lv)`即可

### What is expected?
用reack hooks方式重写ListView组件，下面这句话应该怎么修改？
```
const hei = document.documentElement.clientHeight - ReactDOM.findDOMNode(this.lv).parentNode.offsetTop;
```

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | next |
| System | win10 |
| Browser | chrome71 |

**Comment by ziluo** [comment]
为什么要用React Hook重写，或者，可以把你用React Hook重写的代码贴出来，一起看下问题在哪？

**Comment by littlepoolshark** [comment]
额，React Hook是为了代码复用。就你这句代码这的有必要用hook封装起来复用吗？

**Comment by wowtrxqn** [comment]
我用了useRef， 这里 listViewRef.current.offsetTop  是undefined
