### ISSUE TITLE
ant-mobile顶部导航和底部导航内容是同一个怎么办？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-mobile#3030]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

ant-mobile顶部导航和底部导航内容是同一个怎么办？

![snipaste_2019-01-04_17-26-36](https://user-images.githubusercontent.com/13177997/50682160-f1af5480-1048-11e9-9415-9ce7039244a4.png)

底部菜单放了个 <ArticleList />
```
<TabBar>
   <TabBar.Item>
      <ArticleList />
   </TabBar.Item>
</TabBar>        
```

顶部菜单也放了个 <ArticleList />
```
function TopTabs() {
  const tabs = [
    { title: '首页' },
    { title: '频道1' },
    { title: '频道2' },
    { title: '频道3' },
    { title: '频道4' },
    { title: '频道5' },

  ];

  return (
    <>
      <WhiteSpace />
      <Tabs tabs={tabs} renderTabBar={props => <Tabs.DefaultTabBar {...props} page={6} />}>
        <ArticleList />
      </Tabs>
      <WhiteSpace />
    </>
  );
}
```
这两个<ArticleList />是同一个组件，怎么让它只显示一个？
我想使用react-router v4，但不知怎么和antd-mobile结合。

**Comment by doxiaodong** [comment]
只写一个不就只显示一个了呀。提问请到  https://stackoverflow.com/
