### ISSUE TITLE
tabs组件中tabbar增加惯性滚动效果是不是更好一些？

### ISSUE THREAD

**Issue by OPY-bbt** [ant-design/ant-design-mobile#3032]
在使用tabs组件的过程中，由于tab选项过多，碰到两个问题。
- 当需要选中最后几个tab时，滑动多次才行。很麻烦。
- 在safari中 滚动Tabbar，会引起页面的上下滚动，效果很不好。

对于第一个问题 是不是增加惯性滚动效果会好一些，或者当数量大于一定值时，显示一个更多按钮，用点击的方式去替代滑动。

**Comment by tsy77** [comment]
同求【惯性滑动】

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
