### ISSUE TITLE
在微信中modal中带input框，当input失去焦点后，造成整个页面假死，无法触发事件,必现

### ISSUE THREAD

**Issue by agooddream** [ant-design/ant-design-mobile#3033]

**Comment by agooddream** [comment]
1，在微信中打开官方示例，https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN
2，点击输入弹窗中 promise示例，
3，点击input 使其获取焦点，微信会出现防欺诈提示
4，点击hold on 使input 失去焦点
5，微信防欺诈提示消失，整个页面假死，无法触发相应的事件， 
6，滚动一下背景页即可正常

**Comment by yewenhua** [comment]
请问你现在解决了这个问题吗，我也碰到过，感觉这个框架好垃圾，好多坑

**Comment by agooddream** [comment]
> 请问你现在解决了这个问题吗，我也碰到过，感觉这个框架好垃圾，好多坑

没有真正解决，还没时间一点一点去看源码，目前临时解决方案是给input加blur事件，事件中用代码延时500ms 滚动一下页面 document.body.scrollTo(0,0) 可根据自己的情况来处理一下，

**Comment by yewenhua** [comment]
好的 ，我也试下，谢谢

**Comment by xinggangling** [comment]
> 请问你现在解决了这个问题吗，我也碰到过，感觉这个框架好垃圾，好多坑

blur事件中document.body.scrollTo(0, currentScrollTop - 1)，antd 已经很好了，而且越来越好

**Comment by aiqin-bao** [comment]
难道这个问题到现在还没有新的版本修复吗？？？？

**Comment by yukai-w** [comment]
还没修复！！！！！来人呐

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
