### ISSUE TITLE
移动端浏览器 Modal 弹出时背景依旧可以滚动

### ISSUE THREAD

**Issue by sjfkai** [ant-design/ant-design-mobile#3034]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/modal](https://mobile.ant.design/kitchen-sink/components/modal)

### Steps to reproduce
点击任何按钮弹出modal，背景依旧可以滚动

### What is expected?
背景不能滚动

### What is actually happening?
背景可以滚动

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.6 |
| System | ios12 |
| Browser | safari |

---
pc浏览器没有问题，但是移动端浏览器几乎都有这个问题。似乎是一个比较普遍的问题，有什么解决方法吗？

**Comment by gaopeng0108** [comment]
可以在modal出现的时候，将背景设置为overflow: hidden，然后modal消失的时候恢复

**Comment by likezero** [comment]
可以参考 @gaopeng0108 的方案 或者 看下官方demo，可以把事件阻止掉。

**Comment by daiyu7hao** [comment]
移动端modal弹出时，背后的内容依然可以滚动的问题，我找了一个方法，希望对大家有用：
`
// 打开弹窗的时候，就调用 convertMouseMove('forbidden')
// 关闭弹窗的时候，就调用 convertMouseMove('allow')
function myFunction(e) {
  e.preventDefault();
}
export function convertMouseMove(flag) {
  if (flag === 'forbidden') {
    document.body.addEventListener('touchmove', myFunction, { passive: false });  //passive 参数不能省略，用来兼容ios和android
  } else if (flag === 'allow') {
    document.body.removeEventListener('touchmove', myFunction)
  }
}`
