### ISSUE TITLE
Tabs标签页组件，initialPage还是initalPage？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-mobile#3035]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

文档中写的`initialPage`（单词拼写正确）
![image](https://user-images.githubusercontent.com/13177997/50681682-57024600-1047-11e9-9cfc-26ec4054a303.png)

示例代码中写的`initalPage`（单词拼写错误）
![snipaste_2019-01-04_17-42-56](https://user-images.githubusercontent.com/13177997/50681982-50c09980-1048-11e9-8811-00ce046918cb.png)

### 重现链接：
[https://mobile.ant.design/components/tabs-cn/](https://mobile.ant.design/components/tabs-cn/)

### 重现步骤
按ctrl+f分别搜索`initialPage`和`initalPage`即可。

### 问题：
1、示例代码并没有报错，那么以哪个为准？
2、`initalPage={'t2'}`中的t2表示什么意思？

| Environment | Info |
|---|---|
| antd | 2.2.6 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
