### ISSUE TITLE
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by YoungCC2** [ant-design/ant-design-mobile#3039]
我在使用and-mobile是 出现异常,错误信息如下.
![2](https://user-images.githubusercontent.com/13192993/50751522-21e33700-1285-11e9-972a-b72c71f0a23e.png)
 下面是我的配置
![1](https://user-images.githubusercontent.com/13192993/50751494-f52f1f80-1284-11e9-880d-44a1c3f5b6cf.png)

请告诉我 如何解决这个问题.

**Comment by doxiaodong** [comment]
Provide a demo repo please.
