### ISSUE TITLE
0.8.5的html标签的class="pixel-ratio-2"怎么不见啦

### ISSUE THREAD

**Issue by bigbigbo** [ant-design/ant-design-mobile#304]
之前的antd-mobile版本是0.7.8，样式都正常。
这两天升级到0.8.5，发现所有的样式都变了，发现0.8.5版本的html标签的pixel-ratio-2的class怎么不见了...

**Comment by pingan1927** [comment]
请看changeLog。升级请参考wiki
https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8%E9%AB%98%E6%B8%85%E6%96%B9%E6%A1%88%E5%AE%9E%E8%B7%B5
