### ISSUE TITLE
用create-react-app脚手架生成模版，按需引入antd-mobile会报错injectBabelPlugin is not a function

### ISSUE THREAD

**Issue by wangzhe13555313322** [ant-design/ant-design-mobile#3041]

**Comment by doxiaodong** [comment]
Provide a demo repo please.

**Comment by wangzhe13555313322** [comment]
| |
王哲
|
|
15595504667@163.com
|
签名由网易邮箱大师定制


在2019年01月8日 13:42，毒枭东<notifications@github.com> 写道：

Provide a demo repo please.

**Comment by wangzhe13555313322** [comment]
The screenshot is the code of the key place, which was generated directly through the create-react app. Please help me to solve it. Thank you


| |
王哲
|
|
15595504667@163.com
|
签名由网易邮箱大师定制


在2019年01月8日 13:55，王哲<15595504667@163.com> 写道：
| |
王哲
|
|
15595504667@163.com
|
签名由网易邮箱大师定制


在2019年01月8日 13:42，毒枭东<notifications@github.com> 写道：

Provide a demo repo please.

**Comment by SuperPoet** [comment]
I have the same question

**Comment by VinceFanZ** [comment]
const { override, fixBabelImports } = require('customize-cra')

module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd-mobile',
    style: 'css',
  }),
)

**Comment by crudboy** [comment]
//This is the configuration of using less in antd Design. Prerequisites To install less and less-loader
const {
	override,
	fixBabelImports,
	addLessLoader,
} = require("customize-cra");


module.exports = override(
	fixBabelImports("babel-plugin-import", {
		libraryName: "antd-mobile",
		style: true
	}),
	addLessLoader({
		
		javascriptEnabled: true
	})
	
);

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
