### ISSUE TITLE
ant-mobile长列表组件，点击item怎么跳转到详情页，并且详情页返回长列表页时，长列表页不刷新，并还在上次滑动到的位置？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/ant-design-mobile#3043]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

ant-mobile长列表组件，点击item怎么跳转到详情页，并且详情页返回长列表页时，长列表页不刷新，并还在上次滑动到的位置？
https://mobile.ant.design/components/list-view-cn/#components-list-view-demo-basic-body

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | next |
| System | win10 |
| Browser | chrome71 |

**Comment by doxiaodong** [comment]
这个不是 antd-mobile 的问题，你可以去 https://stackoverflow.com 等论坛提问
