### ISSUE TITLE
Modal 遮罩层的层级在ios上有问题

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-mobile#3046]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/hqwlkj/pen/bOjqPJ?&editable=true&editors=001](https://codepen.io/hqwlkj/pen/bOjqPJ?&editable=true&editors=001) 

请使用 Safari 浏览器查看本链接

### Steps to reproduce
在页面使用 Modal 布局好一个弹窗提示信息，再在这个 Modal 上触发一个 Modal.alert() 提示函数，这时你会发现 Modal.alert()的遮罩曾没有体现出来，在 Chrome 浏览器中没有问题。

### What is expected?
每一个 Modal 是独立，不要相互影响。

### What is actually happening?
受 Modal mask 样式层级影响。

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.5.1 |
| System | Mac OS |
| Browser | Safari 浏览器 12.0.2 |

---
具体问题看issue补充的截图。

Chrome 效果（期望效果）：
![image](https://user-images.githubusercontent.com/12181423/50871378-53c7db00-13f6-11e9-9ba2-10f04570f3de.png)

Safari  效果（不正常的效果）：
![image](https://user-images.githubusercontent.com/12181423/50871527-b9b46280-13f6-11e9-8b39-58a8d7d831f7.png)

**Comment by hqwlkj** [comment]
@warmhug   能否及时处理一下？

**Comment by IamDLY** [comment]
兄弟，这个问题解决没？

**Comment by hqwlkj** [comment]
自己重写样式处理的。

**Comment by yytt968** [comment]
有可能是在safair浏览器中，webkit-overflow-scrolling: touch;这个属性引发的zIndex值不正常。

**Comment by yytt968** [comment]
是.am-modal-wrap下的transform: translateZ(1px);影响的。

**Comment by duwenbin0316** [comment]
> 是.am-modal-wrap下的transform: translateZ(1px);影响的。

同时解决了IOS下模态框内容无法滚动的问题，赞👍
