### ISSUE TITLE
Carousel走马灯 竖向&抽奖模块 动态请求拿到的数据不能轮播

### ISSUE THREAD

**Issue by libw** [ant-design/ant-design-mobile#3047]

**Comment by libw** [comment]
按照官网展示的数据结构，写成静态的数据，数据被渲染出来，且可以滚动。一但换成通过axios请求获取的数据，数据依旧会被渲染，但是无法滚动，将获取的数据处理成和官网展示的一样也无法进行轮播

**Comment by mengwuhen** [comment]
建议在render渲染的时候判断一下 数组是否为空，非空在渲染 应该可以解决你目前的问题
