### ISSUE TITLE
网站重新设计

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#305]
现在的网站太 PC 了。

参照：http://framework7.io/ 或 http://mint-ui.github.io/docs/#!/zh-cn/action-sheet 重新搞下？
1. 信息架构更精简一些（最好极简），首页不要 scroll 动画，把手机界面放在首屏，首屏再加个二维码。
2. 内页演示区域固定，演示代码直接展示出来。
3. 重用 iframe, iframe 切换地址即可。
4. 减少代码加载 https://github.com/ant-design/ant-design-mobile/issues/243

**Comment by afc163** [comment]
http://m.sui.taobao.org/components/

**Comment by shuwenliu** [comment]
https://designlab.alipay.com/luohui.luohui/ant_designmobile/assets/82113533/pages/1

偏老师的意见 +1。我们yy了新的pc和手机端设计，设计稿会同步更新在这里。

**Comment by benjycui** [comment]
@Chinglik 好像提过以后不会有 mobile 这个网站了？

**Comment by Chinglik** [comment]
其实是这个首页未来会有其他规划，我觉得暂时可以不用考虑这个，下周勺子可能会跟大家同步一下的。

**Comment by warmhug** [comment]
以后推广 https://design.alipay.com/
