### ISSUE TITLE
PullToRefresh快速两次下拉刷新，第二次会直接跳回去。

### ISSUE THREAD

**Issue by chanchangxing** [ant-design/ant-design-mobile#3050]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/pull-to-refresh-cn/](https://mobile.ant.design/components/pull-to-refresh-cn/)

### Steps to reproduce
当第一次下拉刷新之后，快速再次下拉刷新，但不放开手指

### What is expected?
第二次的下拉刷新状态不消失。

### What is actually happening?
下拉刷新状态消失。

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.4.1 |
| System | 各种手机。 |
| Browser | h5 |

---
我看了一下是因为onTouchEnd会有个setTimeout的操作，时间为一秒，能不能将这个时间给到我们自己去设置，或者刷新组件必须出现一秒再收回。

**Comment by wangweida** [comment]
同样的问题，没看懂那个setTimeout一秒的意义，接口快的话连续刷新总是会回弹

**Comment by qianxuemin** [comment]
me too

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
