### ISSUE TITLE
drawer组件z-index问题

### ISSUE THREAD

**Issue by BronzeCui** [ant-design/ant-design-mobile#3052]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/bronzecui/pen/dwaKKM](https://codepen.io/bronzecui/pen/dwaKKM)

### Steps to reproduce
打开drawer组件，点击drawer组件sidebar区域或者overlay区域，底部radio和CheckBox响应点击事件（如果底部放置button或其他可点击组件，不会响应点击）

### What is expected?
sidebar区域或者overlay区域响应点击区域

### What is actually happening?
底部radio和CheckBox响应点击事件

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 15 |
| System | mac |
| Browser | chrome |

---
sidebar对应z-index:2  overlay对应z-index: 1  radioItem和checkbox对应z-index:2  ，升高sidebar/overlay的z-index可以解决该问题，组件内部样式是否应该调整对应层级

**Comment by ystarlongzi** [comment]
`<Drawer />` 还有个问题：默认不是挂在 `<body />`  上的

另外，如果 `antd` 和 `antd-mobile` 如果有相同的组件，建议接口尽量保持一致吧，感觉现在有学习成本
