### ISSUE TITLE
IOS 12.1.2 SearchBar 进入页面 用focus无法获取焦点

### ISSUE THREAD

**Issue by viccsen** [ant-design/ant-design-mobile#3054]
直接用微信打开官方的demo页，自动获取焦点栏没有获取到焦点，键盘也不会弹出

https://mobile.ant.design/kitchen-sink/components/search-bar?lang=zh-CN#search-bar-demo-0

**Comment by zhangyi-2012** [comment]
你好，这个问题暂时没有找到理想的解决方案

**Comment by Nick110** [comment]
### iOS的input会限制自动focus，只有在用户手动触发某些事件时调用focus方法才会生效
### 解决方案
> 在公共页面中加一个隐藏的input，在其他页面的点击事件或者其他事件里调用这个input的focus方法调起键盘，再跳转页面，调用该页面里的相应focus，在已经调起键盘的情况下再调用focus就能成功。
