### ISSUE TITLE
Calendar: customizing the date Cell

### ISSUE THREAD

**Issue by xcheukx** [ant-design/ant-design-mobile#3055]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
add some festival, holiday or another custom label on this

### What does the proposed API look like?
see: antd - calendar - (dateCellRender / dateFullCellRender)

**Comment by xianghongai** [comment]
any upgrade?

**Comment by panda6412** [comment]
why close this issue?
