### ISSUE TITLE
df

### ISSUE THREAD

**Issue by yujiahan** [ant-design/ant-design-mobile#3056]
设定minDate为上一年时间eg minDate={new Date(new Date() - 5184000000)} 不生效 最小仍为2019-1-1

**Comment by coderzzp** [comment]
translate:

**Comment by coderzzp** [comment]
translate:

**Comment by coderzzp** [comment]
@yujiahan 怎么把问题关了？

**Comment by coderzzp** [comment]
ok...when i pull down it works~
