### ISSUE TITLE
the mask would be flash in Modal.alert()

### ISSUE THREAD

**Issue by AlbertLin0923** [ant-design/ant-design-mobile#3057]
在使用antd-mobile时候，发现Modal组件淡入淡出的时候，mask蒙层闪烁；
后来我用chrome的animation查看动画，发现mask层的动画执行了两遍，也就是先白色=》灰色=》白色=》灰色，而正常的应该是只执行一次 白色=》灰色；

``      Modal.alert("xxx", "XXX", [
       {
          text: "xxx"
        }
      ]);
``
![image](https://user-images.githubusercontent.com/24648689/51439582-955e5d00-1cf7-11e9-9861-e109dc2da981.png)
![image](https://user-images.githubusercontent.com/24648689/51439584-998a7a80-1cf7-11e9-85cf-826cbe10ce91.png)
如上图所示，第一张是没问题的情况；第二张就是出现问题的情况
代码如下：

` handleRegister = () => {
    Modal.alert("提示", "您输入的账号格式错误", [
      {
        text: "确定"
      }
    ]);
    // }
  };`

是什么原因会导致动画执行两遍了？

**Comment by fairySusan** [comment]
怎么就关闭了，还没解决呢，我也遇到这个问题

**Comment by ykx456654** [comment]
只有fadeIn  fadeOut没有

**Comment by hyl1374961656** [comment]
我在ipad上也有这个问题，不过是偶现的
