### ISSUE TITLE
建议在Tab组件加disable的api，可以设置不可点击状态

### ISSUE THREAD

**Issue by davychan1985** [ant-design/ant-design-mobile#3059]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
快速切换tab时，请求滞后导致数据被覆盖。

### What does the proposed API look like?
如题

**Comment by likezero** [comment]
在业务层代码处理。类似防重复提交
