### ISSUE TITLE
Tag组件建议提供约束性组件的解决方案

### ISSUE THREAD

**Issue by Evanxuke** [ant-design/ant-design-mobile#3062]
* [x]  I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tag是一个非约束性组件，这在将它做成表单组件的时候让我产生了一些困惑
 
### What does the proposed API look like?
 提供类似Value的约束性属性

**Comment by Evanxuke** [comment]
> * [x]   I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> Tag是一个非约束性组件，这在将它做成表单组件的时候让我产生了一些困惑
> ### What does the proposed API look like?
> 提供类似Value的约束性属性

**Comment by shuaizhouliu** [comment]
这个组件不能受控是个问题！！！

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
