### ISSUE TITLE
使用antd-mobile里的tabs和pulltorefresh做h5页面出现的问题

### ISSUE THREAD

**Issue by qqis314860100** [ant-design/ant-design-mobile#3065]
当我使用antd-mobile里的组件tabs和pulltorefresh，左右滑动tabs的同时还能下拉，会导致全部tabs都下拉一段距离暴露出“下拉刷新”那个div，这种情况该怎么解决？

**Comment by qqis314860100** [comment]
![qq 20190125112953](https://user-images.githubusercontent.com/26587045/51733597-c1455e00-20bc-11e9-8c15-420cc87c893c.png)
![qq 20190125161752](https://user-images.githubusercontent.com/26587045/51733614-cc988980-20bc-11e9-891a-0d5caffa539d.png)

**Comment by citrusjunoss** [comment]
怎么解决呀， 上下滚动也会引起tabs 切换

**Comment by ananiy** [comment]
同问。。。

**Comment by zycjiayou** [comment]
我也有这个情况，下拉或上拉只要有一点点左右滑动，就会触发tab切换

**Comment by RicoLiu** [comment]
禁用左右滑动可行否？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
