### ISSUE TITLE
ios 上用到 dialog 的组件，上拉后下边出现空白遮挡

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#307]
![11](https://cloud.githubusercontent.com/assets/2011119/18754925/e06d982a-811c-11e6-9b8a-75cea75471ec.png)

**Comment by silentcloud** [comment]
初步看了哈，应该就是同一个问题 https://github.com/ant-design/ant-design-mobile/issues/163

**Comment by yiminghe** [comment]
阻止 popup 内容的 ontouchmove @silentcloud

**Comment by silentcloud** [comment]
这个问题从 rc-dialog 上解决会比较好，绑在 div[role=dialog] 上， @yiminghe 

Dialog.tsx: 

```javascript
onTouchMove(e) {
    e.preventDefault();
}
<div
    tabIndex="-1"
    onTouchMove={this.onTouchMove}
    onKeyDown={this.onKeyDown}
```

**Comment by silentcloud** [comment]
@yiminghe 不能笼统的去阻止 touchmove，如果内容里有 overflow: scroll 就不好搞了

**Comment by yiminghe** [comment]
不能放到 rc-dialog

评估下 popup/action-sheet 会不会有 scroll 的东西，如果有，此 issue 无解关闭

**Comment by silentcloud** [comment]
恩 是不能放到 rc-dialog 里，popup 应该会存在 scroll 的东西， sheet 应该不会

**Comment by warmhug** [comment]
怎么会无解？在 mask 层上支持用户设置 onTouchStart 阻止事件

**Comment by silentcloud** [comment]
@warmhug react-component/dialog 的 commit 这样修是 ok 的，发个 rc-dialog 的小版本？

**Comment by warmhug** [comment]
一种解决方法 https://github.com/ant-design/ant-design-mobile/wiki/FAQ#ios-fixed-bug ，缺点是 dialog 还会有穿透滚动问题。

穿透滚动问题解法：https://github.com/ant-design/ant-design-mobile/commit/89ed1c72049bb4606dcf77c30da5833e5f7e8122

**Comment by yiminghe** [comment]
穿透滚动 的局限性需要说明（弹层内容也不能滚动了） @warmhug

**Comment by warmhug** [comment]
已加

**Comment by yiminghe** [comment]
@warmhug 不要让用户设置 wrapProps，加个配置？ preventScroll?

**Comment by warmhug** [comment]
想想还是自己设置好些，更灵活，毕竟组件内部做不到全部浏览器兼容

**Comment by lyboy2012** [comment]
通过wrapProps 在webview 阻止 onTouchStart onTouchMove ，页面还是会滚动，有人遇到吗

**Comment by Ariel-zhangyue** [comment]
还是加 onTouchMove吧，ios 10.3.3  里禁止了 onTouchStart 之后，click 也不会触发

**Comment by ourfeel** [comment]
ios9 不增加 fastclick。 单纯增加onTouchStart 会导致点击不触发。
