### ISSUE TITLE
更新版本2.2.7后，InputItem报错 

### ISSUE THREAD

**Issue by jihfgz** [ant-design/ant-design-mobile#3071]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/input-item-cn/](https://mobile.ant.design/components/input-item-cn/)

### Steps to reproduce
InputItem 的value为空会报错，但不影响使用
使用rc-form 没设默认值时，value都是空的，type为phone number的这种都会先报一次错
![tim 20190213135134](https://user-images.githubusercontent.com/35723666/52690059-6904cc00-2f97-11e9-8568-190a01f75874.png)

### What is expected?
无错

### What is actually happening?
index.js:184 Uncaught TypeError: Cannot read property 'length' of undefined
    at InputItem._this.calcPos (index.js:184)
    at eval (index.js:121)

| Environment | Info |
|---|---|
| antd | 2.2.7 |
| React | react 15.3.2 |
| System | windows |
| Browser | chrome |

**Comment by jin-benben** [comment]
我也遇到，请问您的解决了吗

**Comment by hunao0221** [comment]
Same with you!
