### ISSUE TITLE
IOS 微信内置浏览器 modal 框中的表单控件（input,textarea,select），会出现输入内容后，弹出层无法关闭以及控件无法再次点击的bug。

### ISSUE THREAD

**Issue by full-stop** [ant-design/ant-design-mobile#3072]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN](https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN)

### Steps to reproduce
1. 在微信中打开重新链接
2. 点击“输入弹窗”下的 promise 按钮，唤起输入弹窗
3. 点击 input 框，唤起软键盘。
4. 输入完成后，再去点击关闭按钮或者是Input框发现无反应。

### What is expected?
完美的修复问题。

### What is actually happening?
自己通过临时的方法来解决。

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.4.1 |
| System | IOS 12.x |
| Browser | 微信 X5内核浏览器 |

---
通过我自身搜索资料查证，原因有以下几点共参考：
1. fixed 定位在IOS下有bug
2. 软键盘弹起时会导致fixed定位元素的实际位置错乱（虽然显示还在原位置，但实际上已经偏移了）

自己临时的解决方案：
1. fixed 定位改为 absolute
2. input失去焦点时，对页面进行快速的滚动（scrollTop）

**Comment by builden** [comment]
+1，希望这个bug能尽早修复，体验很差

**Comment by chenvd** [comment]
+1 缺失遇到这个问题，希望尽快修复

**Comment by mouyong** [comment]
+1 确实遇到这个问题，希望尽快修复

**Comment by agooddream** [comment]
前后有不少人报这个问题了，一直没有修复，不知道是否在跟进中

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
