### ISSUE TITLE
多个ajax同时请求 Toast hide第二次没用 一直loading

### ISSUE THREAD

**Issue by liufeisprit** [ant-design/ant-design-mobile#3073]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/weiq/pen/NddyXw?editors=0010](https://codepen.io/weiq/pen/NddyXw?editors=0010)

### Steps to
```

fetchData(url) {
Toast.loading("请求中...",0);
  $.ajax({ url, success: function(){
    Toast.hide();
  });
}

componentWillMount() {
  this.fetchData("url1");
  this.fetchData("url2");
}
```
### What is expected?
多个toast.loading('xxx',0) toast.hide全部关闭 

### What is actually happening?
toast.hide没用 一直loading

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.7.0 |
| System | window 10 |
| Browser | chrome |

**Comment by doxiaodong** [comment]
你给的 demo 没有发现问题呀。

**Comment by luocongjay** [comment]
我也发现有这样的问题，建议不要这样用

**Comment by WeiFei365** [comment]
也遇到了相同的问题，当同时显示多个 toast 时（ duration = 0），调用 Toast.hide() 只会关闭一个：
这里是 demo： https://codesandbox.io/s/ll9kw1p75q?fontsize=14

**Comment by WeiFei365** [comment]
查看源码，貌似是只允许一个 Toast 实例存在，所以同时实例化多个 Toast 时，不能够正确的 destroy 之前的（猜测应该是异步渲染导致）
https://github.com/ant-design/ant-design-mobile/blob/master/components/toast/index.tsx#L13

不过，考虑到 Toast 的摆放位置，是不可以有多个 Toast 同时显示的，因为会被互相遮盖住；

所以，可以考虑单例的方式，用队列控制，一次只显示一个 Toast，hide后再显示队列中的下一个，草稿代码参考：
https://codesandbox.io/s/j7q45pk1vw?fontsize=14

但是，草稿代码里面还有个问题，如果使用 antd-mobile 内置的 setTimeout，会报错：

![image](https://user-images.githubusercontent.com/6710699/56847836-8e0ca800-6913-11e9-892a-a1d29764f6fb.png)

神奇！所以使用了传给 antd-mobile 的 Toast 的 duration = 0，然后自己用 setTimeout 控制，算是解决了！

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
