### ISSUE TITLE
SwipeAction typescript type error 有问题的 ts 类型定义

### ISSUE THREAD

**Issue by iugo** [ant-design/ant-design-mobile#3074]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/BMGLbb?editors=0010#0](https://codepen.io/anon/pen/BMGLbb?editors=0010#0)

### Steps to reproduce
打开支持 ts 的编辑器, 通过 JSX 的方式使用 SwipeAction 组件.

### What is expected?
ts 检查不报错.

### What is actually happening?
```
[ts]
JSX element type 'SwipeAction' is not a constructor function for JSX elements.
  Type 'SwipeAction' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more. [2605]
```

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.7.0-alpha.2 |
| System | macOS |
| Browser | Chrome 71 |

---
version 2.2.8

**Comment by doxiaodong** [comment]
try `import React from 'react';`
and `allowSyntheticDefaultImports: true` in tsconfig.json.

**Comment by iugo** [comment]
> try `allowSyntheticDefaultImports: true` in tsconfig.json.

It works.

But the module should be ES6 style. https://github.com/Microsoft/TypeScript/issues/10895

**Comment by doxiaodong** [comment]
This is a legacy. antd-mobile need `allowSyntheticDefaultImports` config until we change all components and dep components to write import.
