### ISSUE TITLE
listview useBodyScroll pullToRefresh 组合问题

### ISSUE THREAD

**Issue by LubinPark** [ant-design/ant-design-mobile#3075]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/pull-to-refresh-cn/](https://mobile.ant.design/components/pull-to-refresh-cn/)

### Steps to reproduce
listview 使用 useBodyScroll 为true 时，onScroll 事件监听不到了。
listview 使用 pullToRefresh 组件 快速滑动会产生 白边，滑动底部页面卡死，无法滑动

### What is expected?
列表滑动，当进入下一页面，返回计算高度滑动，现在 onScroll 事件监听不到

### What is actually happening?
listview 使用 useBodyScroll 为true 时，onScroll 事件监听不到了。
listview 使用 pullToRefresh 组件 快速滑动会产生 白边，当快结束 慢慢减少到没有。

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | react |
| System | mac |
| Browser | google chrome safari |

---
版本是    "antd-mobile": "^2.2.8"

**Comment by LubinPark** [comment]
[短视频]

**Comment by LubinPark** [comment]
![Uploading 1.gif…]()
![Uploading 2.gif…]()
图一，图二均为 官方实例 浏览器使用无此问题，出现在andorid和ios 真机中
图一滑动，向下上方有空白，向上滑动下方有空白
图二滑动使用body，当滑动停止，直接上滑页面无反应，只能向下滑动 onscroll 事件也不触发

**Comment by LubinPark** [comment]
![Uploading 1.gif…](http://ae01.alicdn.com/kf/HTB1ZCbebdzvK1RkSnfo5jbMwVXac.gif)
![Uploading 2.gif…](http://ae01.alicdn.com/kf/HTB1iP2bbdjvK1RjSspi5jcEqXXas.gif)

图一，图二均为 官方实例 浏览器使用无此问题，出现在andorid和ios 真机中
图一滑动，向下上方有空白，向上滑动下方有空白
图二滑动使用body，当滑动停止，直接上滑页面无反应，只能向下滑动 onscroll 事件也不触发

**Comment by wpnl** [comment]
遇到同样的问题，请问题主解决了吗

**Comment by JiangMengLei** [comment]
同样的 useBodyScroll onScroll和onEndReached都不触发

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
