### ISSUE TITLE
TextareaItem 留言中删除中间某个文本后，光标自动跳到最后面

### ISSUE THREAD

**Issue by wangyapeng** [ant-design/ant-design-mobile#3076]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://inte-cloud.chanjet.com/hsy/uhy0270pep4e/qw99vlcb4r/shop/index.html#/order?promoRuleId=0](https://inte-cloud.chanjet.com/hsy/uhy0270pep4e/qw99vlcb4r/shop/index.html#/order?promoRuleId=0)

### Steps to reproduce
留言中删除中间某个文本后，光标自动跳到最后面

### What is expected?
光标不跳到最后面

### What is actually happening?
光标跳了

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.7 |
| System | android, ios |
| Browser | 微信浏览器 |

**Comment by wangyapeng** [comment]
antd-mobile 版本为最新版本 2.2.8

**Comment by doxiaodong** [comment]
@zack24q  看一下这个

**Comment by zack24q** [comment]
不是新版本更新导致的，计划支持这个特性中

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
