### ISSUE TITLE
tabs 如何修改选中tab的字体大小

### ISSUE THREAD

**Issue by yinxh2016** [ant-design/ant-design-mobile#3077]
如何修改选中tab的字体大小，tabBarActiveTextColor 修改文字颜色是可以的？

**Comment by doxiaodong** [comment]
No font-size prop. you can rewrite style by css. eg. `.am-tabs-default-bar-tab-active`

**Comment by yinxh2016** [comment]
.am-tabs-default-bar-tab-active 如何使用？

**Comment by YuYingLu** [comment]
我使用global 直接覆蓋掉設定，但外層用div包起以防影響到其他Tabs
Less

.box {
  :global { //cover ant offical setting
    .ant-tabs-tab-active {
      border-bottom: 2px solid #00D1B2 !important;
      z-index: 2;
      .ant-tabs-tab-btn{
        color: red;  //改被選的字
      }
  }
}
