### ISSUE TITLE
引入antd组件的时候出现Unable to resolve module `./index.css` 错误

### ISSUE THREAD

**Issue by ablikim915** [ant-design/ant-design-mobile#3082]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/15664144/53000740-006c9200-3464-11e9-893a-508df8c54fdc.png)

初始化项目之后，安装了antd-mobile 和 babel-plugin-import("^1.11.0")。然后在app.js文件里引入antd-mobile的随便一个组件使用后一直报这个错误。

### What is actually happening?
![image](https://user-images.githubusercontent.com/15664144/53000800-22feab00-3464-11e9-83d8-7941255bcd37.png)

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.6.3 |
| System | windows |

**Comment by doxiaodong** [comment]
使用  https://github.com/ant-design/ant-design-mobile-rn

**Comment by showtan001** [comment]
@doxiaodong antd-mobile-rn 没有 PullToRefresh 拉动刷新，后期会增加吗？

**Comment by doxiaodong** [comment]
@showtan001 RN 现已交由社区维护，你去那边问问吧
