### ISSUE TITLE
为什么我按照文档create-react-app实现amtd-mobile按需加载报错

### ISSUE THREAD

**Issue by yuejianjian** [ant-design/ant-design-mobile#3084]

**Comment by yuejianjian** [comment]
我按照文档create-react-app实现amtd-mobile按需加载步骤,最后npm start启动就报错

**Comment by sunshixiong789** [comment]
![image](https://user-images.githubusercontent.com/31101988/53058349-a7e1d700-34ed-11e9-9ef8-50965ad300b4.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
