### ISSUE TITLE
SearchBar组件第一次加载显示不正确，点击过后又显示正确

### ISSUE THREAD

**Issue by sunshixiong789** [ant-design/ant-design-mobile#3085]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
安装相应的mobile
![image](https://user-images.githubusercontent.com/31101988/53058277-68b38600-34ed-11e9-83ad-2340f59b6f2c.png)

### What is expected?
能够正确显示
![image](https://user-images.githubusercontent.com/31101988/53058294-75d07500-34ed-11e9-8922-b6d44751c682.png)
![image](https://user-images.githubusercontent.com/31101988/53058307-7f59dd00-34ed-11e9-8bff-a30be2db81ac.png)

### What is actually happening?
无法正确显示

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.8.2 |
| System | windows |
| Browser | chrome |

**Comment by sunshixiong789** [comment]
antd-mobile版本是2.2.8

**Comment by jiwenjiang** [comment]
我这里也有同样的问题，开始里面的搜索图标和文字不显示，要点一下才显示！

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
