### ISSUE TITLE
IOS can't find variable:document 

### ISSUE THREAD

**Issue by 15738039217** [ant-design/ant-design-mobile#3087]
"antd-mobile": "^2.2.9",
  "react": "^16.3.1",
    "react-dom": "^16.8.2",
    "react-native": "^0.55.3",

**Comment by 15738039217** [comment]
用的就是这个组件antd-mobile，不要给我把问题移到其他地方，谢谢

**Comment by likezero** [comment]
哪个组件？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
