### ISSUE TITLE
Picker 在华为手机浏览器导航栏显示的情况下，无法点击确定按钮

### ISSUE THREAD

**Issue by joey-lucky** [ant-design/ant-design-mobile#3089]
https://mobile.ant.design/kitchen-sink/components/picker?lang=zh-CN

在华为浏览器打开这个网站，就会出现点不了确定按钮的问题，感觉按钮的实际位置向下移动了。

**Comment by silinabai** [comment]
怎么解决的？

**Comment by joey-lucky** [comment]
> 怎么解决的？

当需要用到picker的页面的时候，我会通过api让页面全屏，全屏下就不会有这个问题。
还是希望官方尽快修复这个问题。

**Comment by silinabai** [comment]
> > 怎么解决的？
> 
> 当需要用到picker的页面的时候，我会通过api让页面全屏，全屏下就不会有这个问题。
> 还是希望官方尽快修复这个问题。
@joey-lucky  太棒了解决了，多谢！望官方尽快修复

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
