### ISSUE TITLE
用下拉刷新RefreshControl，页面高度增加了，可以用滚动条往下滚，但是手滑动不能往下滚

### ISSUE THREAD

**Issue by small752** [ant-design/ant-design-mobile#309]
<RefreshControl
        loadingFunction={this.loadingFunction}
        resistance={1}
        className="maa-history-refresh-control"
      >
       
        {maa_history_list.length>0 ?
        	<List>
	        <List.Body style={{background:'#F5F5F9'}}>
	            {this.state.items}
			    {maa_history_list}  
	         </List.Body>
	         </List>
        :
        	<div className="nomaa">您还没有预约过哦</div>
        }
        
      </RefreshControl>

代码比较简单，**数据加载多了之后不能手滑往下翻屏**，查看dom对象div的height已经很大了，拖动滚动条也可以往下滚

**Comment by warmhug** [comment]
什么版本？

**Comment by small752** [comment]
"version": "0.8.5",

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/issues/295  重复了，#295 我先关了

**Comment by warmhug** [comment]
![image](https://cloud.githubusercontent.com/assets/2011119/18773348/eb8d7e32-8180-11e6-97e8-8bce582e60e0.png)
设置下高度，我本地测试没大问题（除了不能冒泡到 html body 的 scroll，所以顶不掉浏览器的工具栏和状态栏，但也可以试试设置 body 元素的 `overflow:hidden` 解决）

**Comment by small752** [comment]
哦 我试试
