### ISSUE TITLE
Referring to the wiki HD solution, the font and Icon of the Tabbar component become smaller

### ISSUE THREAD

**Issue by citrusjunoss** [ant-design/ant-design-mobile#3090]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/citrusjunoss/ant-design-demo](https://github.com/citrusjunoss/ant-design-demo)

### Steps to reproduce
1. Referring to the wiki HD solution, configure the project.(https://github.com/ant-design/ant-design-mobile/wiki/HD)
2. the font and Icon of the Tabbar component become smaller

### What is expected?
the font and Icon of the Tabbar component  become normal

### What is actually happening?
the font and Icon of the Tabbar component become smaller

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.8.2 |
| System | windows10 |
| Browser | chrome |

**Comment by citrusjunoss** [comment]
![image](https://user-images.githubusercontent.com/18432488/53213019-4c951d80-3682-11e9-9b7b-1e0869cae831.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
