### ISSUE TITLE
InputItem type="password"  开发者模式下显示明文密码

### ISSUE THREAD

**Issue by ganyanchuan1989** [ant-design/ant-design-mobile#3091]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ganxunzou/antd-mobile-boilerplate](https://github.com/ganxunzou/antd-mobile-boilerplate)

### Steps to reproduce
1. git clone https://github.com/ganxunzou/antd-mobile-boilerplate
2. npm i
3. 增加一个InputItem组件，并设置type="password"
4. F12 查看

### What is expected?
应该不可见

### What is actually happening?
明文可见， 如下图：
![2019-02-22_144057](https://user-images.githubusercontent.com/5092728/53225247-4ba6c080-366f-11e9-85c2-62c95a7700dd.png)

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16 |
| System | win7 |
| Browser | Chrome 71 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
