### ISSUE TITLE
Picker组件优化建议

### ISSUE THREAD

**Issue by silinabai** [ant-design/ant-design-mobile#3092]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以在onOk方法中同时获取label值和value值，value可以自定义功能所需要的参数，label作为显示，更方便使用

### What does the proposed API look like?
可以在onOk方法中同时获取label值和value值，value可以自定义功能所需要的参数，label作为显示， 更方便使用

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
