### ISSUE TITLE
Picker支持不可用选项

### ISSUE THREAD

**Issue by ppxu** [ant-design/ant-design-mobile#3093]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Picker 组件很常用的场景，某些选项是不可选中的，比如 WeUI 的 Picker 组件，选到不可用选项时会自动回退上上一次的选项 

### What does the proposed API look like?
Picker 的 data 增加 disabled，Array<{value, label, disabled, children: Array}>

**Comment by awmleer** [comment]
Picker 暂时不会增加 disabled 逻辑，相关的讨论可以看这里： #4502
