### ISSUE TITLE
antd-mobile按需加载 The "injectBabelPlugin" helper has been deprecated as of v2.0

### ISSUE THREAD

**Issue by Calinas** [ant-design/ant-design-mobile#3094]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/docs/react/introduce-cn](https://mobile.ant.design/docs/react/introduce-cn)

### Steps to reproduce
按照文档安装`babel-plugin-import` 之后，npm start之后无法启动服务。报错：The "injectBabelPlugin" helper has been deprecated as of v2.0. You can use customize-cra plugins in replacement - https://github.com/arackaf/customize-cra#available-plugins。 injectBabelPlugin已经不支持了，要换成customize-cra。

### What is expected?
希望文档更新一下。config-overrides.js配置如下：
```
const {
  override,
  fixBabelImports
} = require("customize-cra");

module.exports = override(
  fixBabelImports("babel-plugin-import", {
    libraryName: "antd-mobile",
    style: "css"
  })
);
```
### What is actually happening?
The "injectBabelPlugin" helper has been deprecated as of v2.0. You can use customize-cra plugins in replacement

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.8.3 |
| System | 不涉及 |
| Browser | 不涉及 |

---
实际版本2.2.9

**Comment by arfaWong** [comment]
```shell
yarn add less
yarn add --dev react-app-rewired customize-cra less-loader 
```

```javascript

// config-overrides.js

const {
  addLessLoader,
  fixBabelImports,
  override
} = require("customize-cra");

module.exports = {
  webpack: override(
    addLessLoader({
      javascriptEnabled: true
    }),
    fixBabelImports("babel-plugin-import", {
      libraryName: "antd-mobile",
      style: true
    })
  )
};



```

**Comment by jsxiao** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> https://mobile.ant.design/docs/react/introduce-cn
> 
> ### Steps to reproduce
> 按照文档安装`babel-plugin-import` 之后，npm start之后无法启动服务。报错：The "injectBabelPlugin" helper has been deprecated as of v2.0. You can use customize-cra plugins in replacement - [https://github.com/arackaf/customize-cra#available-plugins。](https://github.com/arackaf/customize-cra#available-plugins%E3%80%82) injectBabelPlugin已经不支持了，要换成customize-cra。
> 
> ### What is expected?
> 希望文档更新一下。config-overrides.js配置如下：
> 
> ```
> const {
>   override,
>   fixBabelImports
> } = require("customize-cra");
> 
> module.exports = override(
>   fixBabelImports("babel-plugin-import", {
>     libraryName: "antd-mobile",
>     style: "css"
>   })
> );
> ```
> ### What is actually happening?
> The "injectBabelPlugin" helper has been deprecated as of v2.0. You can use customize-cra plugins in replacement
> 
> Environment	Info
> antd	2.2.6
> React	16.8.3
> System	不涉及
> Browser	不涉及
> 实际版本2.2.9

非常感谢提供的解决办法！

**Comment by meijiangyan** [comment]
const {
  override,
  fixBabelImports
} = require("customize-cra");

module.exports = override(
  fixBabelImports("babel-plugin-import", {
    libraryName: "antd-mobile",
    style: "css"
  })
);

thanks

**Comment by meiminjun** [comment]
style-loader 升级了，导致dev 环境antd-mobile 按需引入的样式获取不到，降级即可，bye bye!
