### ISSUE TITLE
The source code compiler error after cloning

### ISSUE THREAD

**Issue by m9rco** [ant-design/ant-design-mobile#3096]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design](https://mobile.ant.design)

### Steps to reproduce
# Step 1
```bash
git clone https://github.com/ant-design/ant-design-mobile
```

# Step 2

```bash
/usr/local/bin/yarn  && /usr/local/bin/yarn run lint
```

Error log as follows

```bash
/Users/anonymous/ant-design-mobile/node_modules/@types/react/index.d.ts(3743,19): error TS2320: Interface 'Element' cannot simultaneously extend types 'ReactElement<any>' and 'ReactElement<any, any>'.
  Named property 'type' of types 'ReactElement<any>' and 'ReactElement<any, any>' are not identical.
/Users/anonymous/ant-design-mobile/node_modules/@types/react/index.d.ts(3744,19): error TS2320: Interface 'ElementClass' cannot simultaneously extend types 'Component<any, {}>' and 'Component<any, {}, any>'.
  Named property 'componentDidUpdate' of types 'Component<any, {}>' and 'Component<any, {}, any>' are not identical.
/Users/anonymous/ant-design-mobile/node_modules/@types/react/index.d.ts(3744,19): error TS2320: Interface 'ElementClass' cannot simultaneously extend types 'Component<any, {}>' and 'Component<any, {}, any>'.
  Named property 'props' of types 'Component<any, {}>' and 'Component<any, {}, any>' are not identical.
/Users/anonymous/ant-design-mobile/node_modules/@types/react/index.d.ts(3744,19): error TS2320: Interface 'ElementClass' cannot simultaneously extend types 'Component<any, {}>' and 'Component<any, {}, any>'.
  Named property 'refs' of types 'Component<any, {}>' and 'Component<a
```

### What is expected?

1. Create a lib folder
2. bable-import to be able to introduce

### What is actually happening?
error

| Environment | Info |
|---|---|
| antd | 2.2.9 |
| React | react |
| System | macOS |
| Browser | chrome |
|node -v|v8.11.3|
|npm -v | 5.6.0|
|yarn -v |1.13.0|

**Comment by m9rco** [comment]
I want to compile the project，Because for my needs, there are a lot of personalized needs

**Comment by m9rco** [comment]
depend|version
---|---
node -v|v8.11.3
npm -v | 5.6.0
yarn -v |1.13.0

**Comment by m9rco** [comment]
![image](https://user-images.githubusercontent.com/18391791/53298045-b66c1d80-3862-11e9-95bc-5ce1e4205c3e.png)

**Comment by m9rco** [comment]
I want to know how the official running environment，I think the compiled meet [npm source](https://www.npmjs.com/package/antd-mobile
) with respect to OK

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
