### ISSUE TITLE
ListView的renderRow中放入<List><Item></Item></List>出现border双线

### ISSUE THREAD

**Issue by JensenWei** [ant-design/ant-design-mobile#3097]
https://mobile.ant.design/components/list-view-cn/#components-list-view-demo-basic
https://mobile.ant.design/components/list-cn/#components-list-demo-basic

ListView的renderRow中放入 <List> <Item> </Item> </List>，在PC端会出现border双线，手机端正常；
在表单中则正常

**Comment by likezero** [comment]
antd-mobile仅支持移动端
