### ISSUE TITLE
Toast 穿透问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#31]
![](https://zos.alipayobjects.com/rmsportal/njyNApDTFkIYYJb.png)

线貌似还是穿透了。

重现页面：http://mobile.ant.design/components/menu/

**Comment by silentcloud** [comment]
![image](https://cloud.githubusercontent.com/assets/1698185/17357488/621e8966-598f-11e6-9a73-f78a64fc9771.png)

**Comment by silentcloud** [comment]
我这看着没穿啊 @afc163

**Comment by afc163** [comment]
我在 master 上看的，没合并过来？

**Comment by silentcloud** [comment]
@afc163 pull 一下，之前提交 0.7 忘记 cherry-pick 了
