### ISSUE TITLE
modal 组件如何修改遮罩层的高度？

### ISSUE THREAD

**Issue by yiwoxia** [ant-design/ant-design-mobile#3100]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决ios底部不被遮罩层遮盖，因为ios的不兼容fixed，容易拖拽页面导致底部消失。

### What does the proposed API look like?
修改样式可以写清楚如何修改组件一下样式

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
