### ISSUE TITLE
带间距的 Carousel 组件，尾图到首图的切换存在停顿，过渡不流畅

### ISSUE THREAD

**Issue by shurong-kavout** [ant-design/ant-design-mobile#3101]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe  it has never been fixed.

### Reproduction link
[https://codepen.io/anon/pen/EMxqZj?&editable=true&editors=001#anon-login](https://codepen.io/anon/pen/EMxqZj?&editable=true&editors=001#anon-login)

### Steps to reproduce
官网示例 [Carousel 走马灯 - 带间距](https://mobile.ant.design/components/carousel-cn/#components-carousel-demo-basic-space) 本身就存在此问题：
从第最后一张图切换到第一张图，或从第一张图切换到最后一张图时，会产生停顿。
如果感觉不明显，对比从第一张图切换到第二张图（或从第二张图切换到第三张图）即可发现区别

### What is expected?
消除尾图到首图的切换时的额外停顿，像其他两张相邻图片的切换一样流畅

### What is actually happening?
尾图到首图的切换存在停顿，过渡不流畅

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.4.2 |
| System | MacOS Mojave 10.14.3 |
| Browser | Google Chrome 72.0.3626.109（正式版本） （64 位） |

---
其实，手动向右切换轮播图时，从首图到未图的切换，也存在此问题。
因此，也可以描述为“带间距的 Carousel 组件，首图和尾图的相互切换存在停顿、过渡不流畅问题”

**Comment by baimiao91** [comment]
【190816】当我设置了
                  frameOverflow="visible"
                  autoplay
                  autoplayInterval={6000}
                  infinite
                  cellSpacing={8}
                  slideWidth={0.8}
这些之后我数据比较多，比如12条，当自动播放前4张时左侧盒子得侧边都能正常显示出来，当轮播到第5张时，你会发现第4张的侧边就会消失（所谓的卡顿现象），后来发现当使用Carousel 组件的带间距时，最多设置5张不会出现我这样的情况，然后一旦超过5张就会出现我的上述问题了，望各位大佬们，给搬砖的我提提意见，怎么解决，或者官方给予一定的解决方案

**Comment by wenlei0617** [comment]
现在没有解决办法吗？只有换组件？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
