### ISSUE TITLE
Toast loading 和全局品牌色同步

### ISSUE THREAD

**Issue by 3lang3** [ant-design/ant-design-mobile#3104]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
统一视觉效果

### What does the proposed API look like?
默认统一全局色设置
可以单独设置覆盖

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
