### ISSUE TITLE
关于Modal.prompt  type 值设置为login-password 如何让input的type属性为text

### ISSUE THREAD

**Issue by sunflower-tc** [ant-design/ant-design-mobile#3107]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 弹框填写用户验证信息。

### What does the proposed API look like?
希望关于Modal.prompt  type 多添加属性可配置 弹框输入框的type属性

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
