### ISSUE TITLE
SeacrhBar value is not effect, not a controlled component

### ISSUE THREAD

**Issue by shenqihui** [ant-design/ant-design-mobile#3116]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/shenqihui/pen/jJLKzd](https://codepen.io/shenqihui/pen/jJLKzd)

### Steps to reproduce
输入一个然后回车搜索。之后点击取消，这个时候会清空 value 指向的 state 。再次点击输入，这时候 input 居然还是旧的值。

### What is expected?
再次点击输入的时候，需要清空 input 的值， value 属性受控组件生效。

### What is actually happening?
input 输入框没有受控。

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.3.2 react |
| System | mac 10.14.3 |
| Browser | Google Chrome	72.0.3626.121 (正式版本) （64 位） |

---
无上下文。

**Comment by melchior-voidwolf** [comment]
@shenqihui 是这样的，如果你读了源代码，你会注意到这个组件在大部分情况下表现是受控的，但是实际上显示的value是内部根据外部的props计算出的state。当你的value数值更新为undefined情况下，会认为外部并未传入value，从而脱离受控组件模式。

**Comment by shenqihui** [comment]
thanks @melchior-voidwolf
