### ISSUE TITLE
TabBar嵌套Tabs组件后Tabs组件中的内容不显示

### ISSUE THREAD

**Issue by mrarronz** [ant-design/ant-design-mobile#3118]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/issues/2140](https://github.com/ant-design/ant-design-mobile/issues/2140)

### Steps to reproduce
我现在有一个H5应用，主界面是一个TabBar控制两个页面内容，TabBar的position为bottom。两个页面分别为“任务”和“统计”。在“任务”中使用了Tabs组件，Tabs的position为top，Tabs控制两个页面。

按照antd-mobile的官方文档，在Tabs里面嵌套两个div组件，可以实现左右切换。但是页面上根本显示不出来，在chrome中调试，查看Element元素时这两个div压根就不存在。

官方文档代码如下：
```
<Tabs tabs={tabs} initialPage={2} animated={false} useOnPan={false}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '250px', backgroundColor: '#fff' }}>
        Content of first tab
      </div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '250px', backgroundColor: '#fff' }}>
        Content of second tab
      </div>
</Tabs>
```

### What is expected?
Page1和Page2嵌套在Tabs中能够正常显示

### What is actually happening?
1、同时嵌套Page1和Page2，页面在Tabs中不显示
2、只保留一个Page1或Page2，页面能够在Tabs中显示出来，但达不到我的目的。我想要的是两个页面都能够显示并且能够左右滑动或点击tab切换。

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | react 16.7.0 |
| System | mac os |
| Browser | chrome |

---
这个问题是否跟Tabs组件嵌套在TabBar中有关？我这里是用antd-mobile做webapp，并非是React Native，Tabs的组件中也不存在TabPanel。[#2140](https://github.com/ant-design/ant-design-mobile/issues/2140)跟我的问题可能类似但并有任何解决方案不了了之了。

**Comment by mrarronz** [comment]
我的代码如下，首先是主界面使用TabBar，这里贴出主要代码：
```
<TabBar
          unselectedTintColor="#929292"
          tintColor="#3474bc"
          barTintColor="#f9f9f9"
          tabBarPosition="bottom"
          hidden={false}
          prerenderingSiblingsNumber={0}
        >
          <TabBar.Item
            title="任务"
            key="mission"
            icon={<Icon type={'check'}/>}
            selectedIcon={<Icon type={'check'}/>}
            selected={this.state.selectedTab === 'mission'}
            onPress={this._missionTapped}
          >
            <MissionList/>
          </TabBar.Item>
          <TabBar.Item
            title="统计"
            key="statistic"
            icon={<Icon type={'user'}/>}
            selectedIcon={<Icon type={'user'}/>}
            selected={this.state.selectedTab === 'statistic'}
            onPress={this._statisticTapped}
          >
            <Statistic/>
          </TabBar.Item>
        </TabBar>
```
<MissionList/>和<Statistic/>就是主界面TabBar容器内显示的两个页面，即“任务”和“统计”。现在我要在MissionList中使用Tabs组件嵌套两个页面，使其左右切换，代码如下：
```
<div className={styles.content}>
          <Tabs
            tabs={tabs}
            initialPage={0}
            onChange={this._handleTabChangeAction}
          >
            <Page1 />
            <Page2 />
          </Tabs>
</div>
```
Page1和Page2的用法和上述官方文档的两个div是一样的，为什么显示不了呢？

当我去掉Page2只保留Page1时，Page1就显示出来了，左右滑动显示的都是Page1。

**Comment by mrarronz** [comment]
antd-mobile verson 2.2.9

**Comment by mrarronz** [comment]
找到原因了，Tabs组件在设置tabs属性时，tabs数组中的数据只需要设置title字段就可以了
```
const tabs = [
  { title: '进行中' },
  { title: '已完成' },
];
```

而之前设置的tabs是这样的
```
const tabs = [
  { key: 'working',  title: '进行中' },
  { key: 'completed',  title: '已完成' },
];
```
key字段导致Tabs组件渲染时出现了问题

**Comment by iplus26** [comment]
what...why? 
Facing the same bug...

**Comment by sparGuan** [comment]
坚持重新打开，antd的tabs就是存在这个bug！！！！！

**Comment by CrazyCoderShi** [comment]
重新打开, 我今天也遇到这个bug了

**Comment by mrarronz** [comment]
这个问题还是多看文档，把代码逐步精简，保留最基本的使用方式，多调试下

**Comment by wfk007** [comment]
> 这个问题还是多看文档，把代码逐步精简，保留最基本的使用方式，多调试下

文档上 tabs 的 page 不是可以通过 index 和 key 指定么？如果添加key会导致div不显示，那page怎么通过key指定？为什么要close？

**Comment by LiuZhenyan-Wuzhong** [comment]
不能设置key意味着不能通过activeKey来控制tabs，这非常没用。
