### ISSUE TITLE
TabBar 标签栏 在google浏览器（ 版本73.0.3683.75）中无法正常渲染

### ISSUE THREAD

**Issue by wangzongming** [ant-design/ant-design-mobile#3119]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/tab-bar-cn/ （这是官网案列地址，我自己本地的也一样不显示）](https://mobile.ant.design/components/tab-bar-cn/ （这是官网案列地址，我自己本地的也一样不显示）)

### Steps to reproduce
直接就不出来

### What is expected?
解决

### What is actually happening?
为止

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.8 |
| System | window10 |
| Browser | 73.0.3683.75 |

**Comment by jicheng1014** [comment]
i got this bug too, 

the tabbar disappear from view when the height of contents in the tab-bar greater than browsers height.  (chrome 73.0.3683.75)

safari work correctly

fixed when i added @kyktommy code in css

**Comment by wangzongming** [comment]
@kyktommy  的方法果然好使

**Comment by wangzongming** [comment]
> I added these css, and it works well
> 
> ```
> .am-tabs-bottom > .am-tabs-tab-bar-wrap {
>   position: absolute;
>   width: 100%;
>   height: 50px;
>   bottom: 0;
>   left: 0;
> }
> ```

这么写还是不对，当设置TabBar 属性hidden为true时不会隐藏

**Comment by wangzongming** [comment]
.am-tabs-bottom > .am-tabs-tab-bar-wrap {
            position: absolute;
            width: 100%;
            height: 50px;
            bottom: 0;
            left: 0;
        }
        .am-tab-bar-bar-hidden-bottom{
            display: none;
        }

**Comment by R-o-y** [comment]
+1  为何没人管

**Comment by wangzongming** [comment]
> +1 为何没人管
加段样式就行

.am-tabs-bottom > .am-tabs-tab-bar-wrap {
position: absolute;
width: 100%;
height: 50px;
bottom: 0;
left: 0;
}
.am-tab-bar-bar-hidden-bottom{
display: none;
}

**Comment by R-o-y** [comment]
> > +1 为何没人管
> > 加段样式就行
> 
> .am-tabs-bottom > .am-tabs-tab-bar-wrap {
> position: absolute;
> width: 100%;
> height: 50px;
> bottom: 0;
> left: 0;
> }
> .am-tab-bar-bar-hidden-bottom{
> display: none;
> }

加了可行感谢，但这issue不会就这样一直安排在这？

**Comment by wangzongming** [comment]
> > > +1 为何没人管
> > > 加段样式就行
> > 
> > 
> > .am-tabs-bottom > .am-tabs-tab-bar-wrap {
> > position: absolute;
> > width: 100%;
> > height: 50px;
> > bottom: 0;
> > left: 0;
> > }
> > .am-tab-bar-bar-hidden-bottom{
> > display: none;
> > }
> 
> 加了可行感谢，但这issue不会就这样一直安排在这？

我觉得他们是不是忙不过来了，看他们首页还有招聘信息

**Comment by likezero** [comment]
最简单的方式是设置 `am-tabs-content-wrap`的样式 
```css
min-height: 0;
```
后面我们会发布版本解决这个问题。这个bug的产生是由于浏览器变更导致的
https://bugs.chromium.org/p/chromium/issues/detail?id=927066
