### ISSUE TITLE
[TabBar] lib目录下缺少index.js文件

### ISSUE THREAD

**Issue by zhaoyao91** [ant-design/ant-design-mobile#312]
没有lib/tab-bar/index.js文件，导致使用import plugin报错

**Comment by silentcloud** [comment]
按照 readme 配置 webpack

**Comment by zhaoyao91** [comment]
antd难道是面向webpack的么，我们用Meteor的就不管了？

**Comment by silentcloud** [comment]
不用 webpack 的话就引用 antd-mobile/lib/xxxx/index.web

**Comment by zhaoyao91** [comment]
了解，好的。

**Comment by motorguo** [comment]
按照 `README` 配置 还是找不到
```
ERROR in ./~/.0.9.6@antd-mobile/lib/tab-bar/index.web.js
```
```
[
    "import", {
        "style": "css",
        "libraryName": "antd-mobile"
    }
],
```

**Comment by seanjsong** [comment]
@silentcloud 关于你的建议“不用 webpack 的话就引用 antd-mobile/lib/xxxx/index.web”，我试过了还是不行。我可以import index.web，但你们的index.web.js里面在require其它代码时有些没有加上.web后缀。

比如antd-mobile/lib/modal/index.web.js里有require('./Modal')而不是require('./Modal.web')

比如
antd-mobile/lib/button/style/index.web.js里有require('../../style/')而不是require('../../style/index.web')

这样的话不用webpack把extension配置为.web.js就没法用。所以你们这个库还是依赖webpack。
