### ISSUE TITLE
华为荣耀play刘海屏遮挡内容

### ISSUE THREAD

**Issue by heyizhiyuan** [ant-design/ant-design-mobile#3121]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
123

### What is expected?
华为荣耀play刘海屏不遮挡内容

### What is actually happening?
华为荣耀play刘海屏遮挡内容

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 15.4.0 |
| System | Android9 |
| Browser | 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36 |

**Comment by heyizhiyuan** [comment]
![image](https://user-images.githubusercontent.com/39208129/54410137-29abd580-4725-11e9-8e32-1670698a4518.png)

**Comment by likezero** [comment]
这个在业务代码中处理

**Comment by heyizhiyuan** [comment]
问题已经解决了，是打包方式的问题
