### ISSUE TITLE
<InputItem type="money" /> 模拟键盘两个问题

### ISSUE THREAD

**Issue by WihteCrow** [ant-design/ant-design-mobile#3122]
1、模拟键盘没有像原生键盘那样占位，导致弹出会压到底部UI
![image](https://user-images.githubusercontent.com/3975498/54503522-91069700-496a-11e9-87f6-61831580a49d.png)

2、模拟键盘在IOS端，和 ```<Modal popup>``` 使用，会看不到模拟键盘，但是可以点击，应该是兼容性问题，Android可以的，可能和z-index 有关系

**Comment by WihteCrow** [comment]
第二个问题：问题代码：https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/style/Dialog.less#L38

**Comment by ganxunzou** [comment]
@WihteCrow   你遇到再webview中使用，数字键盘卡的问题吗？

**Comment by WihteCrow** [comment]
> @WihteCrow 你遇到再webview中使用，数字键盘输入卡的问题吗？我按正常的按键速度，总是会掉数字。

暂时没有遇到过

**Comment by ganxunzou** [comment]
@

> > @WihteCrow 你遇到再webview中使用，数字键盘输入卡的问题吗？我按正常的按键速度，总是会掉数字。
> 
> 暂时没有遇到过

你应该在WKWebView中使用，所以没有卡顿问题。在iOS的UIWebView中使用问题会很明显。

**Comment by WihteCrow** [comment]
> @
> 
> > > @WihteCrow 你遇到再webview中使用，数字键盘输入卡的问题吗？我按正常的按键速度，总是会掉数字。
> > 
> > 
> > 暂时没有遇到过
> 
> 你应该在WKWebView中使用，所以没有卡顿问题。在iOS的UIWebView中使用问题会很明显。

我这边试了 iphone8+ 和 iphone7 没有出现你说的情况

**Comment by likezero** [comment]
问题1应该修复了。
问题2麻烦另外开一个issue，这个issue我先关闭了
