### ISSUE TITLE
Tabs的title消失

### ISSUE THREAD

**Issue by fycligmh** [ant-design/ant-design-mobile#3125]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/fycligmh/pen/MxqBOj?editors=0010](https://codepen.io/fycligmh/pen/MxqBOj?editors=0010)

### Steps to reproduce
手风琴收起展开

### What is expected?
tabs正常显示

### What is actually happening?
浏览器中正常显示无误，在iphone的微信里打开页面，伸缩手风琴后Tabs的title消失，点击其它空白处的title后又能正常出现

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.7 |
| System | iphone |
| Browser | 微信及qq内浏览 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
