### ISSUE TITLE
want to control Picker with cypress

### ISSUE THREAD

**Issue by luania** [ant-design/ant-design-mobile#3127]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I use Cypress to test my app, but with it i can not control the Picker component.Any one can help me?

### What does the proposed API look like?
want to control Picker with cypress

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
