### ISSUE TITLE
<InputItem type="money" /> 在UIWebView中巨卡

### ISSUE THREAD

**Issue by ganyanchuan1989** [ant-design/ant-design-mobile#3128]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item](https://mobile.ant.design/kitchen-sink/components/input-item)

### Steps to reproduce
正常速度点击数字键盘，比如：123456。会出现数据丢失。

### What is expected?
123456

### What is actually happening?
1246中间会有丢失。

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.8.0 |
| System | ios 11，iphone 7plus |
| Browser | safari |

---
不仅是点击，删除也是感觉不是很流畅

**Comment by ganxunzou** [comment]
一整天都没人管，这个库用的心里很不放心

**Comment by ganxunzou** [comment]
@zack24q 有空帮忙看看哈

**Comment by ganxunzou** [comment]
@zack24q 测试发现卡的原因是在UIWebView中展示。增加FastClick并没有解决。不过通过以下`hacked`方式可以解决。https://medium.com/@mihai/disabling-the-click-delay-in-uiwebview-5cd6b18a8c19。

不知道还有没有更好的解决方案？

**Comment by ganxunzou** [comment]
@zack24q 
原来是onClick和onTouchStart这两个事件。onClick在UIWebView中存在300ms delay问题，而onTouchStart不存在这个问题。虚拟键盘为什么不使用onTouchStart呢？或者加个逻辑判断，如果支持onTouchStart的，用onTouchStart，不支持在选用onClick。

**Comment by Nutlee** [comment]
同遇到这个问题，一个项目入口在钉钉工作台，iOS 打开输入金额很卡...   安卓没问题，直接扫码从钉钉打开也没问题，猜测和楼上原因类似，目前换组件绕过了，大哥有时间给解决下啊 😿

**Comment by Daniel-Kao** [comment]
我这边解决了，在模版文件里加了fastclick

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
