### ISSUE TITLE
InputItem money 数字键盘布局异常

### ISSUE THREAD

**Issue by ganyanchuan1989** [ant-design/ant-design-mobile#3129]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item](https://mobile.ant.design/kitchen-sink/components/input-item)

### Steps to reproduce
点击数字键盘，出来的界面顶部1,2,3键盘位置不正确

### What is expected?
正常显示

### What is actually happening?
异常显示

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.8.0 |
| System | ios |
| Browser | safari |

**Comment by ganxunzou** [comment]
![微信图片_20190321104845](https://user-images.githubusercontent.com/5092728/54731013-e7025700-4b83-11e9-83ad-e486c528589e.jpg)

**Comment by zack24q** [comment]
我这边重现不出，你试的ios版本是多少？

**Comment by zack24q** [comment]
好像是切到后台，切回来就会出现样式错误了，是吗？

**Comment by ganxunzou** [comment]
对的

**Comment by ganxunzou** [comment]
#3129 这个问题能看看吗

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
