### ISSUE TITLE
card组件包含Button、tag组件安卓手机下border不显示

### ISSUE THREAD

**Issue by liuyanming9551** [ant-design/ant-design-mobile#3131]
**Reproduction link**
https://mobile.ant.design/components/card-cn/

**Steps to reproduce**
card组件里面使用Button、tag组件安卓手机下显示有问题，ios没问题
![image](https://user-images.githubusercontent.com/23226540/54738932-3468dd80-4bf1-11e9-990a-de25bd2eabb9.png)

**What is expected?**
安卓下正确显示

**What is actually happening?**
安卓下border部分不显示

Environment | Info
-- | --
antd | 2.2.9
React | 16.8.2
System | Android
Browser | Android

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
