### ISSUE TITLE
How to preventDefault() and stopPropagation() in Stepper Component ? 

### ISSUE THREAD

**Issue by dc198689** [ant-design/ant-design-mobile#3133]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/moQgRv?editors=0011](https://codepen.io/anon/pen/moQgRv?editors=0011)

### Steps to reproduce
1. Bind onClick event in the 'div' tag.
2. Put the Stepper Component into 'div' tag.
3. When Stepper onChange, 'div' onClick also fire in the same time.

### What is expected?
Stepper Component  can run stopPropagation() and preventDefault() in the onChange props

### What is actually happening?
When Stepper onChange, 'div' onClick also fire in the same time

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.8 |
| System | window 10 & macOS |
| Browser | chrome & safari |

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
