### ISSUE TITLE
ImagePicker 图片选择器----报错bug

### ISSUE THREAD

**Issue by NeverGiveUp1995** [ant-design/ant-design-mobile#3135]
### ImagePicker 图片选择器----报错bug
进入官网，点击ImagePicker 图片选择器组件时，演示直接报错了！！！

**Comment by likezero** [comment]
报错截图一下

**Comment by zhaohes** [comment]
我也遇到了图片选择器报错的问题

![error](https://user-images.githubusercontent.com/19921766/69477451-75209280-0e21-11ea-9bed-014004358003.png)

使用的是下面的这张图片：
![qi](https://user-images.githubusercontent.com/19921766/69477460-87023580-0e21-11ea-9356-3e21148779e8.jpg)

**Comment by jianhao** [comment]
两年过去了，官网的示例中依然存在这个问题，选取图片时，DataView.getStringUtf16() 超出了偏移量，无语了，难道是不再维护了？只能自己封装个组件了，不敢用了

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
