### ISSUE TITLE
NavBar onLeftClick 点击方法无效

### ISSUE THREAD

**Issue by sevennights** [ant-design/ant-design-mobile#314]
#### 本地环境

- antd-mobile 版本：0.7.5
- 操作系统及其版本：ios
- 浏览器及其版本：chrome

**Comment by silentcloud** [comment]
ios 10， antd 0.7.5 ，chrome 53.0.2785 测试无问题

**Comment by warmhug** [comment]
Android 上也没问题，检查是否用法不对
