### ISSUE TITLE
TabBar App型选项卡标签栏在 谷歌和火狐浏览器下面不显示。

### ISSUE THREAD

**Issue by AlertConsole** [ant-design/ant-design-mobile#3140]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/tab-bar-cn/](https://mobile.ant.design/components/tab-bar-cn/)

### Steps to reproduce
可以查看antd官网的 TabBar App型选项卡效果 直接用浏览器查看是不显示的，，昨天发现突然不显示的。但是在safari浏览器下发现是正常的，暂时解决方案是给 .am-tabs-content-wrap设置高度不为100%，目前我设置的是91%。但是该方案在火狐浏览器下仍然不能显示TabBar。

### What is expected?
正常显示TabBar App型选项卡

### What is actually happening?
底部TabBar App型选项卡不显示。

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.60 |
| System | macOs Mojave |
| Browser | 谷歌浏览器 和 火狐浏览器 |

---
该bug我只测试了谷歌浏览器和火狐浏览器。在这两种浏览器下面不显示。在手机上显示正常，不存在此bug。希望尽快给出回复。我的email：dujuxin@gamil.com

**Comment by WihteCrow** [comment]
.am-tabs-pane-wrap { height: 100%; } 加上这个可以

**Comment by likezero** [comment]
close in #3188

**Comment by huanzheke** [comment]
我2.2.5版本也这样, 整个页面的高度没显示全, bottom少了50px,有解决办法吗
