### ISSUE TITLE
Chrome 73版本下Calendar弹出框按钮消失

### ISSUE THREAD

**Issue by Zexoius** [ant-design/ant-design-mobile#3147]
官网上如是，73版本下按钮消失

**Comment by Zexoius** [comment]
因为手机上版本远低于73，所以手机端正常显示，但是调试不方便。
所以开发时只能将就用：找到button父盒子所在，绝对定位即可显示
无奈之举(#｀-_ゝ-)

**Comment by ChrisShen93** [comment]
> 因为手机上版本远低于73，所以手机端正常显示，但是调试不方便。
> 所以开发时只能将就用：找到button父盒子所在，绝对定位即可显示
> 无奈之举(#｀-_ゝ-)
@Zexoius 你可以尝试这样：

.date-picker {
  overflow: auto;
}

**Comment by Zexoius** [comment]
> > 因为手机上版本远低于73，所以手机端正常显示，但是调试不方便。
> > 所以开发时只能将就用：找到button父盒子所在，绝对定位即可显示
> > 无奈之举(#｀-_ゝ-)
> > @Zexoius 你可以尝试这样：
> 
> .date-picker {
> overflow: auto;
> }

ok，感谢建议，已解决
