### ISSUE TITLE
PickerView not selected row not masked as expected

### ISSUE THREAD

**Issue by uuau99999** [ant-design/ant-design-mobile#3150]
![image](https://user-images.githubusercontent.com/6498327/55219785-c0f24c00-5240-11e9-8d21-0638af132daa.png)
As the image show, in Galaxy S5 and some low-end Huawei cellphone there are highlighted rows more than one while displaying correctly in iPhone.

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
