### ISSUE TITLE
ImagePicker图片选择器

### ISSUE THREAD

**Issue by anlate** [ant-design/ant-design-mobile#3153]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ng.mobile.ant.design/#/components/image-picker/image-picker-demo-zh?lang=zh-CN](https://ng.mobile.ant.design/#/components/image-picker/image-picker-demo-zh?lang=zh-CN)

### Steps to reproduce
部分安卓手机用微信打开官网imagePicker组件（自定义组件），不能唤起拍照，选择图库照片后不能回显。但是在浏览器或者pc端打开没有问题

### What is expected?
正常唤起拍照和相册

### What is actually happening?
直接唤起图库，并且在图库选择照片后不能回显

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.2.0 |
| System | 安卓 |
| Browser | 微信浏览器 |

---
原因是设置了accept=“image/gif,image/jpeg,image/jpg,image/png”，改成accept="image/*"就能正常使用。这个问题在微信升级后安卓手机集中爆发了这个问题，许多机型都能复现，请问是和微信的兼容问题吗？

**Comment by women-public-enemy** [comment]
没多选功能 demo 写可以多选

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
