### ISSUE TITLE
微信小程序只能用于ReactNative吗，能否用于微信小程序和支付宝小程序

### ISSUE THREAD

**Issue by jervainy** [ant-design/ant-design-mobile#3154]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
小程序开发

### What does the proposed API look like?
能够在小程序上使用antd mobile进行开发

**Comment by likezero** [comment]
暂不支持，谢谢关注
