### ISSUE TITLE
crousel第一页可以左滑最后一页可以右滑

### ISSUE THREAD

**Issue by aliceflaviawang** [ant-design/ant-design-mobile#3155]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://gitlab.alipay-inc.com/h5_release/wealth/merge_requests/688/diffs#23dd45790f67e1a4d968de1db12e75bdc6cc137b_16_27](http://gitlab.alipay-inc.com/h5_release/wealth/merge_requests/688/diffs#23dd45790f67e1a4d968de1db12e75bdc6cc137b_16_27)

### Steps to reproduce
都可以重现

### What is expected?
期望第一个页可以禁止左滑，最后一个禁止右滑

### What is actually happening?
第一页可以左滑最后一个能右滑，且滑动幅度特别大

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 所有 |
| System | 所有 |
| Browser | 所有 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
