### ISSUE TITLE
Picker 组件  onChange 只能传递一个值

### ISSUE THREAD

**Issue by yehoan** [ant-design/ant-design-mobile#3159]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了当需要同时需要2个值得尴尬

### What does the proposed API look like?
希望能根据data得结构来获取不同得值

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/55873437-40c5d200-5bc2-11e9-8b94-74c899e0555c.png)

**Comment by yehoan** [comment]
data 得结构如下  
![image](https://user-images.githubusercontent.com/22631753/55873448-4cb19400-5bc2-11e9-8946-876564fa502b.png)

**Comment by yehoan** [comment]
希望大佬能看下这个问题谢谢

**Comment by YiField** [comment]
解决了吗 好像现在还是这样诶...

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
