### ISSUE TITLE
Ant Design Mobile  ImagePicker component  IosApp uploads image to report error

### ISSUE THREAD

**Issue by baizhiyou** [ant-design/ant-design-mobile#3160]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/image-picker/#components-image-picker-demo-basic](https://mobile.ant.design/components/image-picker/#components-image-picker-demo-basic)

### Steps to reproduce
iosAPP使用Ant Design Mobile  ImagePicker 组件上传图片报错导致图片不能上传，xcode报错信息是errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled} 。ios访问相片和摄像头的权限也开通了。尝试解决方法：xcode中Edit Scheme 中设置OS_ACTIVITY_MODE为disable也不能解决。

### What is expected?
iosAPP使用Ant Design Mobile  ImagePicker 组件上传图片可以成功上传，不重新加载webview

### What is actually happening?
iosAPP使用Ant Design Mobile  ImagePicker 组件上传图片选择图片，重新加载了webview。导致不能成功上传图片。

| Environment | Info |
|---|---|
| antd | 2.2.3 |
| React | react |
| System | AndroidApp ，iPhone App |
| Browser | chrome |

**Comment by baizhiyou** [comment]
iosAPP访问相册和相机的权限也给了，react就是ios选择图片的时候闪退

**Comment by baizhiyou** [comment]
哪位朋友成功解决了这个问题，可以加我微信打赏作为感谢！
Ant Design Mobile ImagePicker组件 ios移动端选择相片以后重新加载webview导致上传附件失败。

**Comment by likezero** [comment]
你是用的reactNative版本吗
