### ISSUE TITLE
Wrong type for Toast.info's onClose parameter

### ISSUE THREAD

**Issue by thewashingtonhua** [ant-design/ant-design-mobile#3163]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/toast-cn/](https://mobile.ant.design/components/toast-cn/)

### Steps to reproduce
Write `Toast.info(text, duration, null, false)` in VS Code.

PS: I'm using antd-mobile 2.2.11 actually, which is not among the 'version' above.

### What is expected?
The third parameter (onClose) should accept `null` as input. (Like the document says) Or update the document to use 'undefined' instead.

### What is actually happening?
IDE would raise an error saying "Argument of type 'null' is not assignable to parameter of type '(() => void) | undefined'". passing 'undefined' instead would work.

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.8.6 |
| System | macOS |
| Browser | Chrome |

---
Just informing you guys there's a mismatch between the document and the actual code.

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
