### ISSUE TITLE
iphone7 ios版本11 发现inputItem 的控件 moneyKeyboardWrapProps 再所有浏览器下 点击了 没法传值...

### ISSUE THREAD

**Issue by yehoan** [ant-design/ant-design-mobile#3165]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
点击那个虚拟键盘没法传值

### What is expected?
期望能找到为什么再ios 11.0版本下点击虚拟点击有效但是没法传值

### What is actually happening?
实际点击了 但是没法传值

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.4.2 |
| System | ios |
| Browser | safari  chrome |

**Comment by Devil000** [comment]
同样的问题 5se ios 10版本 ，你解决了吗

**Comment by wuhao5436** [comment]
同样问题ios10.2 iphone 6 ，求解决方案

**Comment by wuhao5436** [comment]
问题已解决 错误复制了antd mobile 官网的代码
https://mobile.ant.design/components/input-item-cn/ 中
// 通过自定义 moneyKeyboardWrapProps 修复虚拟键盘滚动穿透问题的代码
