### ISSUE TITLE
Model 组件的 transparent 不起作用

### ISSUE THREAD

**Issue by jswxwxf** [ant-design/ant-design-mobile#3166]
我想不要 mask 层，所以设置了 transparent 属性，但是 mask 层还在啊~

```<Modal popup visible={visible} transparent onClose={this.handleClose} animationType="slide-up" className={styles['pets-picker']} wrapClassName={styles['pets-picker-container']}>```

**Comment by likezero** [comment]
有复现的代码吗

**Comment by ziluo** [comment]
@jswxwxf 如果不想要mask层，设置`mask={false}`既可以
