### ISSUE TITLE
ImagePicker multiple,the mobile terminal cannot be multi-selected

### ISSUE THREAD

**Issue by liuxiayang** [ant-design/ant-design-mobile#3168]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/image-picker?lang=zh-CN#image-picker-demo-0](https://mobile.ant.design/kitchen-sink/components/image-picker?lang=zh-CN#image-picker-demo-0)

### Steps to reproduce
The link will generate a qr code to scan the phone code

### What is expected?
Can arouse the mobile terminal to select pictures

### What is actually happening?
Mobile terminal can only be selected

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.2.0 |
| System | android ios |
| Browser | 73.0.3683.86 |

---
The API would be great if there were a limit to the number of images you can upload!

**Comment by liuxiayang** [comment]
只有我一个PC端可多选图片 而移动端不行吗

**Comment by liuxiayang** [comment]
无论multiple属性为true或false 安卓系统只能上传一张 ios系统可上传多张无限制。

**Comment by Fun005** [comment]
> 无论multiple属性为true或false 安卓系统只能上传一张 ios系统可上传多张无限制。

同样的问题，请问解决了吗？

**Comment by 18710790412** [comment]
https://github.com/ant-design/ant-design-mobile/issues/3168#issuecomment-483548917

同样的问题，请问解决了吗？

**Comment by 18710790412** [comment]
> 无论multiple属性为true或false 安卓系统只能上传一张 ios系统可上传多张无限制。

同样的问题，请问解决了吗？

**Comment by baixiaoshi** [comment]
同样的问题，请问解决了吗？

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
