### ISSUE TITLE
CI broken for a long time

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#3169]
https://travis-ci.org/ant-design/ant-design-mobile/builds

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/507615/56182005-a0006800-6042-11e9-9091-9ec525b92927.png">

**Comment by likezero** [comment]
#3186

**Comment by afc163** [comment]
<img width="304" alt="图片" src="https://user-images.githubusercontent.com/507615/62376495-56954380-b573-11e9-997f-eb8b1ca1e0b8.png">

还是挂的，CI 没有起到保护代码质量的作用。

**Comment by afc163** [comment]
我开启了，现在貌似好了。
