### ISSUE TITLE
下拉刷新在uc上无法使用

### ISSUE THREAD

**Issue by minzhang2** [ant-design/ant-design-mobile#317]
#### 本地环境

- antd-mobile 版本：0.8.5
- 操作系统及其版本：android
- 浏览器及其版本：uc最新版本

#### 你期待的结果是：

正常下拉

#### 实际上的结果：

下拉状态显示异常，还经常无法下拉，除了uc其他浏览器正常

**Comment by yiminghe** [comment]
载入 promise polyfill
