### ISSUE TITLE
Input item couldn't get focus until 3-4 times touch，in  ios 12.2 

### ISSUE THREAD

**Issue by ld8878** [ant-design/ant-design-mobile#3170]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item](https://mobile.ant.design/kitchen-sink/components/input-item)

### Steps to reproduce
As the demo, after the page load. (the page was opened first time). Touch on the item " phone number".  Need to touch many time to input。

### What is expected?
Response sensitivity。

### What is actually happening?
No focus , until many times touch.
第一次打开页面，点击多次才能让控件获取焦点，输入键盘才会弹出。 造成卡顿 非常不灵敏的感觉

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 15.4.0 |
| System | IOS 12.x |
| Browser | Wechat |

**Comment by ld8878** [comment]
ps： Format phone input

**Comment by AYWK** [comment]
Did you use fastclick?

**Comment by skdream** [comment]
> Did you use fastclick?
I have meet the same issue, used fastclick

**Comment by likezero** [comment]
have a try as @skdream said
