### ISSUE TITLE
Calendar 组件在chrome中无法滚动

### ISSUE THREAD

**Issue by xgAnd** [ant-design/ant-design-mobile#3173]
antd-mobile Calendar 不能再chrome中滚动 在 safari中可以 官方的例子在chrome也不能滚动

**Comment by xgAnd** [comment]
可以下拉 不可以上滑

**Comment by wonder-sy0618** [comment]
遇到了同样的问题

**Comment by sword-J** [comment]
Galaxy S10 微信浏览器中打开也滚动异常

**Comment by zhzhwwqq2** [comment]
@doxiaodong 加油，我也遇到同样问题

**Comment by defghy** [comment]
+1

**Comment by ziluo** [comment]
@xgAnd @wonder-sy0618 @sword-J @zhzhwwqq2 @defghy 在移动设备上的表现正常么，目前`antd-mobile`是不支持PC场景的，特别是一些手势操作
