### ISSUE TITLE
picker 组件，有时不会触发 onPickerChange 事件

### ISSUE THREAD

**Issue by zw130633** [ant-design/ant-design-mobile#3174]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/picker-cn/](https://mobile.ant.design/components/picker-cn/)

### Steps to reproduce
不需要特别的场景和特别的代码段。picker 组件，选择每列数据时（滚动每列数据时），刚好滚动到它所属区域的最中间位置时，不会触发 onPickerChange 事件，联动效果失效。就用官方的省市区联动示例就可以试出来。

### What is expected?
picker 组件，当每项数据滚动到它所属区域的最中间位置时，依然能触发 onPickerChange 事件

### What is actually happening?
picker 组件，当每项数据滚动到它所属区域的最中间位置时，没有触发 onPickerChange 事件

| Environment | Info |
|---|---|
| antd | 2.2.1 |
| React | 16.2.0 |
| System | windows |
| Browser | 所有浏览器 |

**Comment by zhou-yg** [comment]
感谢反馈，确认是依赖的底层组件rmc-picker/Picker的bug引起的，已修复并提交

**Comment by yijinc** [comment]
我依旧存在这个问题
"antd-mobile": "^2.3.1"

**Comment by daoke0818** [comment]
我这里也偶现过……

**Comment by oscar92420aaa** [comment]
这个问题还是存在啊，create react app , ts, 2.3.3 antd mobile
