### ISSUE TITLE
picker 组件当列数据字数多的时候，展示不下

### ISSUE THREAD

**Issue by zw130633** [ant-design/ant-design-mobile#3176]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/picker-cn/](https://mobile.ant.design/components/picker-cn/)

### Steps to reproduce
省市区联动。省市区名称特别长的时候。例如：自治区名称

### What is expected?
picker 组件当列数据字数多的时候，展示不下，举例说明：省市区联动，新疆下面的自治区名称特别长，显示不下。能像微信地址那样，当列字数多的时候，把字数多的当前列字号变小吗？

### What is actually happening?
picker 组件当列数据字数多的时候，展示不下，举例说明：省市区联动，新疆下面的自治区名称特别长，显示不下

| Environment | Info |
|---|---|
| antd | 2.2.1 |
| React | 16.2.0 |
| System | windows |
| Browser | 所有浏览器 |

能像微信地址那样，当列字数多的时候，把字数多的当前列字号变小吗？

**Comment by doxiaodong** [comment]
如果某一行字数太多就变小，那其他行不变小感觉也不是很合适。变小了，逻辑又有点怪。
建议通过自定义样式修改默认的字体大小
