### ISSUE TITLE
List组件 Typescript 支持问题

### ISSUE THREAD

**Issue by jameslongyoung** [ant-design/ant-design-mobile#3182]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jameslongyoung/antd-list-typescript-error](https://github.com/jameslongyoung/antd-list-typescript-error)

### Steps to reproduce
just clone and run npm start

### What is expected?
no errors

### What is actually happening?
have Typescript errors 
64,42): Type '() => string' is not assignable to type 'string | Element | (() => ElementType<any>) | undefined'.
  Type '() => string' is not assignable to type '() => ElementType<any>'.
    Type 'string' is not assignable to type 'ElementType<any>'.

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.6.3 |
| System |  MacOS 10.14.3 |
| Browser | Chrome  73.0.3683.103 |

**Comment by likezero** [comment]
你给的代码无法重现

**Comment by likezero** [comment]
![image](https://user-images.githubusercontent.com/2275857/56494922-84a3ca00-6526-11e9-8fa7-cbb5c9a35b2c.png)

**Comment by jameslongyoung** [comment]
我又提交了部分代码，现在可以复现了

**Comment by jameslongyoung** [comment]
我又提交了部分代码片段，现在可以复现了




------------------ 原始邮件 ------------------
发件人: "zero"<notifications@github.com>;
发送时间: 2019年4月22日(星期一) 下午5:47
收件人: "ant-design/ant-design-mobile"<ant-design-mobile@noreply.github.com>;
抄送: "吴旭"<249652952@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design-mobile] List组件 Typescript 支持问题 (#3182)
