### ISSUE TITLE
PullToRefresh touchMove代码导致控制台频繁报错

### ISSUE THREAD

**Issue by MrZhouChiBang** [ant-design/ant-design-mobile#3184]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/pull-to-refresh?lang=zh-CN#pull-to-refresh-demo-0](https://mobile.ant.design/kitchen-sink/components/pull-to-refresh?lang=zh-CN#pull-to-refresh-demo-0)

### Steps to reproduce
1、list先向上移动一点，松开左键
2、鼠标拖住list，在模拟器下方边缘上下拖动

### What is expected?
没有错误

### What is actually happening?
控制台就会报如下错误，[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | react |
| System | macOS 10.14 |
| Browser | chrome 73.0.3683.103 |

---
建议：在rmc-pull-to-refresh组件的onTouchMove事件中，在e.preventDefault();这段之前增加if (e.cancelable) {e.preventDefault();}判断

**Comment by phongloihong** [comment]
I have same problem when open drawe.

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
