### ISSUE TITLE
Tabs 增加与 SegmentedControl 一样的胶囊型按钮样式

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#319]
业务需要 SegmentedControl 的样式，也需要 tabs 的手势滑动切换功能。这样 SegmentedControl 的存在可以看做只为了匹配 rn 的 SegmentedControl 。

**Comment by afc163** [comment]
给 SegmentedControl 加上手势滑动开关。

**Comment by silentcloud** [comment]
那就不应该再叫 segementedControl 了 @warmhug ；

native 还有 rn 都是目前这样的，或者就直接像之前一样做在 tabs 里，加 type

**Comment by yiminghe** [comment]
和 ios/rn 保持一致.

SegmentedControl 的样式，也需要 tabs 的手势滑动切换功能?? 这个交互合理么

**Comment by silentcloud** [comment]
@yiminghe 这个交互跟 native seg 不一致，native seg 只存在 bar，不存在 content

**Comment by yiminghe** [comment]
不合理不做
