### ISSUE TITLE
Type definition error in ListPropsType

### ISSUE THREAD

**Issue by wanliyunyan** [ant-design/ant-design-mobile#3193]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/commit/3eba6f4ad91bc738c3085c379faea48fa281a76e](https://github.com/ant-design/ant-design-mobile/commit/3eba6f4ad91bc738c3085c379faea48fa281a76e)

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8.4 |
| System | windows 10  |
| Browser | chrome74 |

![image](https://user-images.githubusercontent.com/10751248/56877679-3fc9e700-6a82-11e9-99a6-75368f7e128a.png)

**Comment by doxiaodong** [comment]
2.2.13
