### ISSUE TITLE
ListView.DataSource中rowHasChanged的确切输入是什么

### ISSUE THREAD

**Issue by cookcc** [ant-design/ant-design-mobile#3195]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
使用ListView时，rowHasChanged: (row1, row2) => console.log(row1, row2);打印出来的row1和row2的数据是一样的，也就是说如果我通过return row1 !== row2（或者row1.like !== row2.like)来判断是否更新数据，那么无论如何数据都不会被更新，尽管我数据已经被更新了

### What is expected?
期望的结果是，当你的源数据被更新时，也就是<this.state.datasource.cloneWithRows(result.data)>这里的result.data已经是更新过的了，比如一个点赞的操作，使用data里的某一项数据的like被置为true(初始值是false),理论上这时的row1和row2的like值是不同的

### What is actually happening?
实际结果是打印出来的 row1和row2的值完全一样，是更新后的like为true的值，即row1.like == row2.like且都为true

| Environment | Info |
|---|---|
| antd | 2.2.3 |
| React | 15.4.0 |
| System | mac 10.14.4  |
| Browser | 73.0.3683.103（正式版本） （64 位） |

---
投票操作，操作后投票数即投票状态更新，实际是不更新

**Comment by ziChen0422** [comment]
listview数据源,改变重新setState数据源, listView不生效 +1

**Comment by arllen007** [comment]
我这个问题也找了好长时间，现在只能直接返回true来更新了

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
