### ISSUE TITLE
ios 10.3版本， actionSheet的callback函数不生效，点击弹出的选项无反应

### ISSUE THREAD

**Issue by lumia3555** [ant-design/ant-design-mobile#3196]
const buttons = ['是', '否', '取消'];
    const values = ['Y', 'N'];
    console.log('in action sheet');
 
    ActionSheet.showActionSheetWithOptions({
      options: buttons,
      cancelButtonIndex: buttons.length - 1,
      maskClosable: true,
      'data-seed': 'logId',
      wrapProps,
    }, 
    function(index) {
      console.log('hahahaha');
      console.log(index);
    }
    );

**Comment by HaiXuan123** [comment]
遇到了同样的问题，不支持IOS11，请问解决了吗？

**Comment by wanglin447563345** [comment]
> 遇到了同样的问题，不支持IOS11，请问解决了吗？

解决了吗？？

**Comment by zhushiyao** [comment]
同样遇到了ios11使用ActionSheet.showActionSheetWithOptions时不能触发点击事件，通过调试发现去掉组件上推荐的iPhone点击事件处理方法后可以正常使用
![image](https://user-images.githubusercontent.com/15229141/106224091-9e0a9780-621d-11eb-926f-4c09f2b55bcd.png)

**Comment by Marszht** [comment]
遇到了同样的问题，callback 并没有生效。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
