### ISSUE TITLE
Related issues for TabBar and Carousel

### ISSUE THREAD

**Issue by LiJiahaoCoder** [ant-design/ant-design-mobile#3197]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/LiJiahaoCoder/Graduation-Project](https://github.com/LiJiahaoCoder/Graduation-Project)

### Steps to reproduce
Install packages after cloning project in app directory, and run `node server.js` after setting up the mongodb. And then run `npm start` command.

### What is expected?
TabBar will show on the bottom, and Carousel will stretch images to adjust Carousel size.

### What is actually happening?
TabBar will show on the top of device, tabBarPosition property is invalid, and TabBar will block other components which results in an inability to trigger click event or touch event. Besides, the images in Carousel won't be stretched to the size of largest images, so this problem will lead to show a blank block in Carousel.

| Environment | Info |
|---|---|
| antd | 2.1.1 |
| React | react |
| System | Windows |
| Browser | Chrome 74.0.3729.131(64bit) |

---
The problem that TabBar blocks other components has been resolved by set z-index of other components, and position is also handled by customing scss attributes.

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
