### ISSUE TITLE
ImagePicker can't select pictures in Android Wechat built-in browse

### ISSUE THREAD

**Issue by sunflower-tc** [ant-design/ant-design-mobile#3200]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[ http://218.93.209.11:8875/wx.php/Guess/detail]( http://218.93.209.11:8875/wx.php/Guess/detail)

### Steps to reproduce
安卓手机内置浏览器中无法选择图片，图片至灰无法选择 ios设备可以
demo 是示例中

### What is expected?
安卓 ios设备都可以正常选择图片

### What is actually happening?
安卓不可以正常选择图片

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 15 |
| System | Mac OS X |
| Browser | 安卓手机内置浏览器 |

**Comment by moutaiclub** [comment]
相同的问题 android 微信环境选择图片之后没有任何反应

**Comment by harperKKK** [comment]
Use default accept property

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
