### ISSUE TITLE
searchBar在聚焦时页面会被弹起

### ISSUE THREAD

**Issue by xiaobao66** [ant-design/ant-design-mobile#3202]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/search-bar](https://mobile.ant.design/kitchen-sink/components/search-bar)

### Steps to reproduce
点击手动聚焦的那个搜索栏，页面就会被抬起

### What is expected?
显示软键盘，但是页面不升高

### What is actually happening?
软键盘会将页面抬高

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.6.0 |
| System | android |
| Browser | 微信浏览器 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
