### ISSUE TITLE
DatePicker怎么不把visible属性写进API

### ISSUE THREAD

**Issue by hxqbeyond** [ant-design/ant-design-mobile#3205]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/date-picker-cn/#components-date-picker-demo-basic](https://mobile.ant.design/components/date-picker-cn/#components-date-picker-demo-basic)

### Steps to reproduce
https://mobile.ant.design/components/date-picker-cn/#components-date-picker-demo-basic

### What is expected?
完善API

### What is actually happening?
完善API

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16 |
| System | Mac |
| Browser | chrome 60 |

**Comment by likezero** [comment]
具体场景可以描述下吗

**Comment by Major01** [comment]
> 具体场景可以描述下吗

展示demo里面有通过设置visible来控制DatePicker显示隐藏，但是api文档上面没有相关属性说明，实际使用中，貌似visible属性也无效；希望可以支持visible

**Comment by wanxue0804** [comment]
这个问题还没有结果吗？我也希望能有个参数控制datepicker是否弹出了，由于现在同一个页面用了DatePicker 和 PullToRefresh 组件 现在的问题是DatePicker向下滚动选择的时候会穿透到触发PullToRefresh，找了一圈没找到禁用穿透的处理方式 我目前的想法是当DatePicker 弹出则禁用下拉刷新，关闭弹出再开启下拉刷新 
然后问题点在于 点击遮罩层关闭DatePicker的时候无法被感知到

**Comment by wanxue0804** [comment]
> 这个问题还没有结果吗？我也希望能有个参数控制datepicker是否弹出了，由于现在同一个页面用了DatePicker 和 PullToRefresh 组件 现在的问题是DatePicker向下滚动选择的时候会穿透到触发PullToRefresh，找了一圈没找到禁用穿透的处理方式 我目前的想法是当DatePicker 弹出则禁用下拉刷新，关闭弹出再开启下拉刷新
> 然后问题点在于 点击遮罩层关闭DatePicker的时候无法被感知到

不好意思！不好意思！实在不好意思！
仔细看了下组件源码是有一个onVisibleChange事件可以监听弹窗是否打开的，只是文档没写说明

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
