### ISSUE TITLE
设置 tabBarTextStyle 后 tabBarActiveTextColor 无效

### ISSUE THREAD

**Issue by js1121302139** [ant-design/ant-design-mobile#3206]

**Comment by js1121302139** [comment]
<Tabs
                        
                        renderUnderline={(s): any => {
                            return <Animated.View style={{ left: s.left, marginLeft: s.width._value / 2 - Px2Dp(24), position: 'absolute', bottom: 0, width: Px2Dp(48), height: Px2Dp(4), backgroundColor: '#FFC53E' }}></Animated.View>
                        }}
                        tabBarTextStyle={{
                            color: colors.C333,
                            fontSize: Px2Dp(28),
                            fontWeight:'400'
                        }}
                        tabBarActiveTextColor='#FFC53E'
                        tabs={[
                            { title: '全部' },
                            { title: '已支付' },
                            { title: '待支付' }
                        ]}>

                    </Tabs>


 "@ant-design/react-native": "^3.1.7",
    "react": "16.8.3",
    "react-native": "0.59.3",

**Comment by likezero** [comment]
RN 版本请前往 https://github.com/ant-design/ant-design-mobile-rn 提问
