### ISSUE TITLE
Popover和Modal.alert同时使用问题

### ISSUE THREAD

**Issue by chenlizan** [ant-design/ant-design-mobile#3207]
通过Popover组件弹出一个Modal.alert，Popover菜单不消失。如下图
![image](https://user-images.githubusercontent.com/10942164/57695694-7e19f580-7681-11e9-8317-2fcf3259968a.png)

在线demo例子
https://codesandbox.io/s/0xxkk561kl

**Comment by chenlizan** [comment]
帮我关了吧，我解决了

**Comment by dyjliningwei** [comment]
我也遇到了，你那边怎么解决的

**Comment by miaomiao12345** [comment]
怎么解决的呀
