### ISSUE TITLE
modal 支持配置在特定容器上加上 overflow: hidden;

### ISSUE THREAD

**Issue by shaozj** [ant-design/ant-design-mobile#3208]
ios 上，我为了让弹性滚动不会盖住底部 fixed 的部分，让页面在内部容器中滚动，而不是在 body 中滚动。modal 框弹出的时候，会在body上加  overflow: hidden; 从而保证底层页面不滚动，现在我的底层页面是在页面内部容器中滚动的，加在 body 上就失效了，modal 能提供一个统一的接口配置后当 modal 弹出后，我可以统一设置需要加 overflow: hidden;  的容器吗？

**Comment by Jemair** [comment]
hi, @shaozj ，感谢你提出的 issue

但是你提的这个 issue 我认为有两个问题
1. 你想要在 modal 弹出时给你页面上的某个元素添加 `overflow: hidden`，其实在先有框架下是可以用代码解决的 比如你想要 `overflow: hidden` 的元素是下面的这个 `.wrap`
```js
class App extends PureComponent {
  state = {
    modalVisible: false,
  }

  openModal = () => {
    document.querySelector('.wrap').style.overflow = 'hidden'
    this.setState({modalVisible: true})
  }

  render() {
    return <div class="wrap">
        <Modal visible={this.modalVisible} />
        <button onCick={this.openModal} />
    </div>
  }
}
```
当然你也可以选择使用装饰器语法，在所有 `openModal` 方法之前添加 `overflow: hidden` 的语法逻辑；或者你也可以将 `Modal` 封装一层，在 `componentDidUpdate` 生命周期内监听 `visible` 的变化，当 `visible` 从 false 变为 true 时，添加你想要的函数

2. `overflow: hidden` 确实可以在某些情况下解决滚动穿透的问题，但是这个方法本身并不完美。当 `Modal` 内部存在滚动条时，这个方法其实是不生效的。更好的方法其实是监听 `Modal` 的 `touchmove` 事件，如果发现滚动已经到两边端点了，将 `touchmove` 事件 prevent 掉

基于以上两点考虑，可能我并不准备支持你提出的这个 issue，如果你有更多理由支持你的看法，欢迎继续 comment

**Comment by Somnus007** [comment]
modal弹出时，mask下的页面会瞬间滚动回到顶部，但是似乎也不一定，我看更像是滚动到上次modal弹出时scroll的位置，如何让modal在弹出和关闭时，mask下的页面保持不动，这个有解么
