### ISSUE TITLE
Main ant.design website could use some improvement in mobile

### ISSUE THREAD

**Issue by sushruth** [ant-design/ant-design-mobile#3212]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design](https://ant.design)

### Steps to reproduce
View the website landing page on mobile 1080p

### What is expected?
Buttons should be fully visible

### What is actually happening?
Buttons are partially visible

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | Na |
| System | Android 8.1 |
| Browser | Edge mobile |

---
Please check the screenshot for info - 

![screen](https://i.imgur.com/N5HFzj7.png)

**Comment by ziluo** [comment]
ant design is for pc， ant design mobile is for mobile，your issue should be at https://github.com/ant-design/ant-design
