### ISSUE TITLE
modal.alert

### ISSUE THREAD

**Issue by f-e-dev-ly** [ant-design/ant-design-mobile#3214]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com?message=抱歉暂无提供](http://www.baidu.com?message=抱歉暂无提供)

### Steps to reproduce

页面中新建div，style={{position: 'absolute',zIndex: '1000',width: '100vw',height: '100vh',backgroundColor: 'rgba(255,0,0,.3)'}}，在页面中使用Modal.alert(xxxxx)即可重现

### What is expected?
Modal.alert()的弹窗根据层级zIndex正常显示

### What is actually happening?
Modal.alert()弹窗覆盖在div之上，即使div的zindex远比弹窗层级大

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 15.3.2 |
| System | ios |
| Browser | safari |

---
安卓不复现，目前测试过的ios机型有ipod、iphone6s

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
