### ISSUE TITLE
Accordion组件中的Panel能否升级一下，目前不支持自定义下拉图标

### ISSUE THREAD

**Issue by superNever** [ant-design/ant-design-mobile#3217]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Accordion组件中的Panel能否升级一下，目前不支持自定义下拉图标，最新的rc-panel是支持自定义下拉图标了（expandIcon）

### What does the proposed API look like?
升级一下mobile中的Accordion，使其依赖的rc-panel版本高一点

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
