### ISSUE TITLE
ListView renderSectionHeader 只能被render一次吗，

### ISSUE THREAD

**Issue by leeqj** [ant-design/ant-design-mobile#322]
#### 本地环境

- antd-mobile 版本：0.8.7
- 操作系统及其版本：mac
- 浏览器及其版本：chrome  53.0.2785.116 

#### 你做了什么？

ListView 的 renderSectionHeader 中 使用 Checkbox

#### 你期待的结果是：

点击SectionHeader中的Checkbox，并在Checkbox onChange方法中 调用 setState ，更新状态  能再次执行 renderSectionHeader方法, 以便更新SectionHeader中的内容

#### 实际上的结果：

点击SectionHeader中的Checkbox，并在Checkbox的 onChange 方法中 调用了 setState 更新了状态，但是并没有再次调用 renderSectionHeader

**Comment by warmhug** [comment]
fork 重现一下 https://codepen.io/warmhug/pen/bwRPvx

**Comment by leeqj** [comment]
@warmhug  看了下 react-native 的文档 根据业务改变 DataSource 的 sectionHeaderHasChanged 方法的返回值即可, 3Q!
