### ISSUE TITLE
当html的overflow被设置为auto时，ListView组件无法调起onEndReached

### ISSUE THREAD

**Issue by weijunext** [ant-design/ant-design-mobile#3221]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antd-mobile.gitee.io/components/list-view-cn/](https://antd-mobile.gitee.io/components/list-view-cn/)

### Steps to reproduce
css中设置 html {overflow: auto}，滑动ListView渲染新数据，发现无法调起onEndReached。

### What is expected?
css中设置 html {overflow: auto}，这种情况下ListView能调起onEndReached。

### What is actually happening?
css中设置 html {overflow: auto}，这种情况下ListView不能调起onEndReached。

| Environment | Info |
|---|---|
| antd | 2.2.0 |
| React | 16.2.0 |
| System | windows 10 |
| Browser | chrome  74.0.3729.157 |

**Comment by ziluo** [comment]
我看你是在PC浏览器上验证的，请确认下移动设备上表现是否正常？

**Comment by ArronHsiao** [comment]
相同的問題.. 請問有解決了嗎？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
