### ISSUE TITLE
Calendar 组件 在ios 版本为8.1.3时候无效

### ISSUE THREAD

**Issue by Running00** [ant-design/ant-design-mobile#3222]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/calendar?lang=zh-CN#calendar-demo-0](https://mobile.ant.design/kitchen-sink/components/calendar?lang=zh-CN#calendar-demo-0)

### Steps to reproduce
用safari打开上面链接， 点击任意 Item, Calendar 未出现

### What is expected?
点击任意 Item, Calendar 出现

### What is actually happening?
点击任意 Item, Calendar 未出现,页面无反应。

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8.4 |
| System | ios |
| Browser | safari |

**Comment by likezero** [comment]
页面有报错吗？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
