### ISSUE TITLE
有些组件不支持自定义prefix,以及样式类名写死，对于样式前缀需要自定义时会比较麻烦

### ISSUE THREAD

**Issue by doryZJ** [ant-design/ant-design-mobile#3227]
Index.js中prefixCls用的var变量的组件
1. Modal.alert
2. Modal.operation
3. Modal.prompt
4. Toast

Less文件类名写死的组件
1. Accordion组件中使用的.am-list-body样式
2. Badge
3. Carousel
4. Grid组件中使用的.am-carousel样式
5. Icon
6. ImagePicker组件中使用的.am-flexbox样式
7. ListView组件中使用的am-list-body，.am-list-item样式
8. SwipeAction组件中使用的.am-list-item-active样式
9. Tag组件使用的.am-icon样式

**Comment by wyl530197181** [comment]
怎么更改ListView组件中的am-list-body，.am-list-item样式

**Comment by awmleer** [comment]
不会支持自定义 prefix
