### ISSUE TITLE
Modal.prompt在iOS8 12.0上被键盘覆盖

### ISSUE THREAD

**Issue by wrshi** [ant-design/ant-design-mobile#3230]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://gitlab.alipay-inc.com/AssetProfile/shroder_test/tree/sprint_shroder_test_S904354752_20190507](http://gitlab.alipay-inc.com/AssetProfile/shroder_test/tree/sprint_shroder_test_S904354752_20190507)

### Steps to reproduce
联系@霨然

### What is expected?
期望弹框和页面上移，不被键盘遮挡。（遮挡情况目前只在一台ios12.0 ip8上看到了，尝试用ios12.3 ip8没有复现）

### What is actually happening?
弹框被键盘遮挡，无法看到输入的数字

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8.6 |
| System | iOS12.0 |
| Browser | iphone8 |

---
有视频，转给@无延 了

**Comment by doxiaodong** [comment]
@zack24q  交给你啦~

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
