### ISSUE TITLE
请问可以给ImagePicker 指定的图片设置状态或添加描述嘛

### ISSUE THREAD

**Issue by tender001** [ant-design/ant-design-mobile#3233]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
上传成功后的图片显示多样化

### What does the proposed API look like?
开放图片自定义显示

**Comment by ziluo** [comment]
可以具体描述下你的需求么，或者你希望`ImagePicker`要怎么改？

**Comment by xietianyao** [comment]
> 可以具体描述下你的需求么，或者你希望`ImagePicker`要怎么改？

就是每张图片下面可以自定义显示内容，类似这样
![image](https://user-images.githubusercontent.com/34930210/80169630-8eb84700-8618-11ea-98c5-a8f9eeac5391.png)
