### ISSUE TITLE
(Inputitem) some device throw error:  does not support selection

### ISSUE THREAD

**Issue by zack24q** [ant-design/ant-design-mobile#3236]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item?lang=zh-CN#input-item-demo-0](https://mobile.ant.design/kitchen-sink/components/input-item?lang=zh-CN#input-item-demo-0)

### Steps to reproduce
test input(format)

### What is expected?
no error

### What is actually happening?
Get error: Failed to read the 'selectionEnd' property from 'HTMLInputElement': The input element's type ('number') does not support selection

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.x |
| System | android |
| Browser |   |

**Comment by likezero** [comment]
close by #3237
