### ISSUE TITLE
Popover 希望增加trigger属性

### ISSUE THREAD

**Issue by jiangzm** [ant-design/ant-design-mobile#3238]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在popover 或者 m-tooltip 默认增加了click事件触发显示popover，如果增加trigger属性能控制触发类型，因为有些场景需要其他方式触发或者需要监听click 做其他操作（现在children节点即使给了onclick事件或被popover默认的click覆盖掉）。
我看到web版的tooltip是有这个控制属性，不清楚移动版为什么移除了这个属性。

### props
name | type | default | description
------------ | ------------- | ------------- | -------------
trigger | string[] | ['click'] | which actions cause tooltip shown. enum of 'click','focus','longpress'

**Comment by ziluo** [comment]
移动端没有`hover`吧，另外，你也可以通过动态设置`visible`来控制PopOver的显隐

**Comment by jiangzm** [comment]
> 移动端没有`hover`吧，另外，你也可以通过动态设置`visible`来控制PopOver的显隐

移动端是没有`hover`行为， 希望增加这个属性是把child node的click事件能交给用户控制， 然后通过`visible`来控制PopOver显隐。

如果`trigger`属性不合理， 是否能增加`defaultTrigger` 来控制是否需要默认的触发事件

**Comment by awmleer** [comment]
v5 已支持
