### ISSUE TITLE
listview与pullToRefresh一起使用时，报类型检查错误，官网例子植入项目

### ISSUE THREAD

**Issue by WTxiaomage** [ant-design/ant-design-mobile#3241]
https://mobile.ant.design/components/pull-to-refresh-cn/

![image](https://user-images.githubusercontent.com/20138139/58773412-8d8cbe80-85ef-11e9-8109-717064a981bd.png)

**Comment by doxiaodong** [comment]
rmc-pullToRefresh 的问题，尚未发布

**Comment by chengliting** [comment]
解决了吗

**Comment by JslinSir** [comment]
+1

**Comment by WTxiaomage** [comment]
二话不多说，上代码
![image](https://user-images.githubusercontent.com/20138139/62278166-2322be00-b47a-11e9-8f96-5fbc09c4913c.png)
这个要把官网pulltorefresh中的属性写完，ts的检测就不报错
