### ISSUE TITLE
React16下虚拟键盘首次渲染会创建多个Dom节点

### ISSUE THREAD

**Issue by Alex-xd** [ant-design/ant-design-mobile#3247]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/alex-xd/pen/vwMZEz](https://codepen.io/alex-xd/pen/vwMZEz)

### Steps to reproduce
首次渲染，多个虚拟键盘dom实例
![https://img.alicdn.com/tfs/TB1aggCbv1G3KVjSZFkXXaK4XXa-1209-810.png](https://img.alicdn.com/tfs/TB1aggCbv1G3KVjSZFkXXaK4XXa-1209-810.png)

对某个InputItem聚焦再失焦后，dom恢复为一个，正常了。

### What is expected?
首次渲染只有一个虚拟键盘dom实例

### What is actually happening?
首次渲染创建了多个虚拟键盘dom实例

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8.x |
| System | Mac 10.13.6  |
| Browser | 74.0.3729.169（正式版本） （64 位） |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
