### ISSUE TITLE
Iphone手机input框需要点击两次

### ISSUE THREAD

**Issue by ApophisX** [ant-design/ant-design-mobile#3248]
inputitem 在 组件在ios手机中需要点击两次才能聚焦，严重影响用户体验，input高度不够高，点击区域太小，placeholder在ios手机中还不垂直居中。这样的体验你们是怎么让发布的，害的我们开发背了太多的锅了

**Comment by ziluo** [comment]
项目中是否引入Fastclick https://mobile.ant.design/docs/react/introduce-cn#3.-使用

**Comment by skdream** [comment]
我这边也遇到了这个问题，把fastclick去掉就可以了

**Comment by ZoneLabyrinth** [comment]
fastclick问题，去掉就行。还有毕竟是开源的，要符合个人要求有些东西需要自己改改，别总想着张手就来，人家也不容易

**Comment by jing-wu** [comment]
我也遇到了这个问题，大家建议去掉fastclick，但是官方文档上写明要加上fastclick，该听谁的

**Comment by PLQin** [comment]
vant 也遇到这个问题, Android下没有这个情况  /捂脸
