### ISSUE TITLE
ListView组件经常无法上拉加载更多

### ISSUE THREAD

**Issue by luqin** [ant-design/ant-design-mobile#325]
#### 本地环境
在线demo http://mobile.ant.design/kitchen-sink/list-view/

- antd-mobile 版本：最新版本
- 操作系统及其版本：
- 浏览器及其版本：chrome53

#### 你做了什么？

上拉列表

#### 实际上的结果：

经常出现加载完毕，重新上拉一点了上拉才能加载更多

![image](https://cloud.githubusercontent.com/assets/2267688/18978877/00beca18-86f9-11e6-9f17-539ca82cebb2.png)

#### 可重现的在线演示

http://mobile.ant.design/kitchen-sink/list-view/

**Comment by warmhug** [comment]
升级到 antd-mobile@0.9.0 ，底层已修复 https://github.com/react-component/m-list-view/commit/415dcdd04c23dd49b8a47ba9c58d12809b9a8a5f

**Comment by GZWZC** [comment]
@luqin 你好 我想问一下你，你是用react开发还是react-native开发，使用listView的时候有依赖react-native吗
