### ISSUE TITLE
Toast.loading  loading  style Shaking and looking uncomfortable

### ISSUE THREAD

**Issue by QShengW** [ant-design/ant-design-mobile#3251]
Toast.loading  loading  style Shaking and looking uncomfortable
Hope to amend

**Comment by QShengW** [comment]
components -> icon -> loadSprite.tsx :

**Comment by QShengW** [comment]
components -> icon -> loadSprite.tsx :  
 loading replace  loading:  '<svg viewBox="-2.125 -1.875 64 64"><path fill="#CCC" d="M29.875-1.875c-17.673 0-32 14.327-32 32s14.327 32 32 32 32-14.327 32-32-14.327-32-32-32zm0 60.7c-15.85 0-28.7-12.85-28.7-28.7s12.85-28.7 28.7-28.7 28.7 12.85 28.7 28.7-12.85 28.7-28.7 28.7z"/><path fill="#108ee9" d="M61.858 30.34c.003-.102.008-.203.008-.305 0-11.43-5.996-21.452-15.01-27.113l-.013.026a1.629 1.629 0 0 0-.81-.22 1.646 1.646 0 1 0-.713 3.132c7.963 5.1 13.247 14.017 13.247 24.176 0 .147-.01.293-.01.44h.022c0 .01-.004.02-.004.03 0 .91.74 1.65 1.65 1.65s1.65-.74 1.65-1.65c0-.06-.012-.112-.018-.167z"/></svg>',

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
