### ISSUE TITLE
InputItem/TextareaItem 文本，唤起原生键盘时输入域被键盘遮挡

### ISSUE THREAD

**Issue by zhaoxm2016** [ant-design/ant-design-mobile#3255]
IOS12

**Comment by zhaoxm2016** [comment]
[短视频已加密，请点击查看.mp4.zip](https://github.com/ant-design/ant-design-mobile/files/3284086/mp4.zip)
现象x小视频

**Comment by ziluo** [comment]
原生键盘处理方案可先参考 https://segmentfault.com/a/1190000018959389

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
