### ISSUE TITLE
Toast没有全局配置接口

### ISSUE THREAD

**Issue by 704826318** [ant-design/ant-design-mobile#3257]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/toast-cn/#components-toast-demo-basic](https://mobile.ant.design/components/toast-cn/#components-toast-demo-basic)

### Steps to reproduce
——

### What is expected?
想要配置toast的全局配置，关闭全局toast遮罩层。说实话遮罩层太影响体验了，必须要等Toast读秒自动关闭用户才能操作页面，不是很友好

### What is actually happening?
 

| Environment | Info |
|---|---|
| antd | 2.2.13 |
| React | 16 |
| System | windows10 |
| Browser | chrome |

**Comment by doxiaodong** [comment]
你是想要在 Toast 的时候，有个按钮可以立马关闭 Toast ?

**Comment by 704826318** [comment]
> 你是想要在 Toast 的时候，有个按钮可以立马关闭 Toast ?

不，我是想要全局关闭Tosat的遮罩层，说实话目前这个项目遮罩层很影响用户体验

**Comment by doxiaodong** [comment]
那你不调用 Toast.xxx 方法不就行啦？

**Comment by fanzkday** [comment]
@doxiaodong 他的意思是: 能不能提供一个全局设置toast.mask = false.
我们也很急需, 如果你们计划近期更新, 我们就不逐个修改了.
等待你们的回复.
