### ISSUE TITLE
TabBar.Item 不能通过变量来进行隐藏

### ISSUE THREAD

**Issue by 52FTT** [ant-design/ant-design-mobile#3258]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/52FTT/antdMobileTabbarDemo.git](https://github.com/52FTT/antdMobileTabbarDemo.git)

### Steps to reproduce
1.  render函数里定义一个变量 visible , 为false（当visible为true的时候，正常）
2.  根据visible变量控制其中一个tab-bar item是否显示
3.  报错 “TypeError: Cannot read property 'props' of null”

### What is expected?
TabBar.Item 能通过变量来进行隐藏或者显示

### What is actually happening?
当变量为false的时候，报错

| Environment | Info |
|---|---|
| antd | 2.2.2 |
| React | 16 |
| System | win10 |
| Browser | 72 |

**Comment by 52FTT** [comment]
我想问一下这个是不是还没好啊？我uninstall又重新install了，然后好像还是之前的报错
![image](https://user-images.githubusercontent.com/39822342/60415584-2b36d600-9c0e-11e9-867f-138d1bacfb52.png)
![image](https://user-images.githubusercontent.com/39822342/60415637-44d81d80-9c0e-11e9-9e0a-3a871b97b6d9.png)

**Comment by Fun005** [comment]
同问，升级了版本也不行

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
