### ISSUE TITLE
caleandar timePicker bug

### ISSUE THREAD

**Issue by 2b2b2b2b** [ant-design/ant-design-mobile#3259]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/calendar?lang=zh-CN#calendar-demo-0](https://mobile.ant.design/kitchen-sink/components/calendar?lang=zh-CN#calendar-demo-0)

### Steps to reproduce
Open any calendar  with timePicker, then set the hour to the 12 o’clock . The page will crash ,cause infinite loop

### What is expected?
regular  work 

### What is actually happening?
the page crash 

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8.6 |
| System | macos |
| Browser | safari/ Android / chrome  |

**Comment by coldfannn** [comment]
when will this issue be released

**Comment by ziluo** [comment]
Related to https://github.com/react-component/m-picker/pull/120
