### ISSUE TITLE
SegmentedControl`s inline style 无法被覆盖

### ISSUE THREAD

**Issue by deerW** [ant-design/ant-design-mobile#326]
#### 本地环境

- antd-mobile 版本：0.8.7
- 操作系统及其版本：mac
- 浏览器及其版本：chrome wechat

#### 你做了什么？

 引入 antd-mobile 的 SegmentedControl ，并做样式覆盖

#### 你期待的结果是：

样式可以覆盖。

#### 实际上的结果：

只有将行内样式关掉，外链样式才有作用。
![image](https://cloud.githubusercontent.com/assets/20079361/18979099/a925a95a-86fa-11e6-8053-ccaa3a27d167.png)
![image](https://cloud.githubusercontent.com/assets/20079361/18979103/af23a41a-86fa-11e6-836f-b3420177ecf5.png)

**Comment by afc163** [comment]
直接修改 https://github.com/ant-design/ant-design-mobile/wiki/%E8%AE%BE%E8%AE%A1%E5%8F%98%E9%87%8F%E8%A1%A8%E5%8F%8A%E5%91%BD%E5%90%8D%E8%A7%84%E8%8C%83#segmentedcontrol less 变量值。

**Comment by silentcloud** [comment]
自定义的这种样式用 api 覆盖，看文档 `tintColor` (主色调)

@deerW

**Comment by deerW** [comment]
thanks,没有想到会是API的方式。。
