### ISSUE TITLE
Is there any way to make TabBar's title 'line break'?

### ISSUE THREAD

**Issue by LuBangTao** [ant-design/ant-design-mobile#3264]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If so ,when use tabbar ,we can show both "English" and "Chinese" languages at the same time,,,with line break.
(I've tried to directly edit code(the title part) ,just add `<br>`、`<br/>`、"\l\n",but it shows as I edited....however if i run the page,edit as html,it works fine...I don't know how to reach it // )

### What does the proposed API look like?
filter the `<br>` tag or add some Escape character,just dont let this "shows whatever I input",I want to break it...
Sincerely,Thanks all to help me with this func,

**Comment by 623636245** [comment]
Sorry for the `<br>` tag make the line breaked above...

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
