### ISSUE TITLE
picker 组件文本过长，切换第一列并同时切换第二列反复几次第二列就不能滑动选择了

### ISSUE THREAD

**Issue by 37972547** [ant-design/ant-design-mobile#3265]
### Reproduction link
https://mobile.ant.design/changelog-cn

### What is actually happening?
picker 组件文案过长，切换第一列并同时切换第二列反复几次第二列就不能滑动选择

Environment | Info
------------ | -------------
antd | 2.2.13
React | 16.8.5
System | mac, ios
Browser | mac chrome 模拟器, 微信

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
