### ISSUE TITLE
如何在 ReactNative 的项目工程里面，调用antd-mobile里面的相关组件？

### ISSUE THREAD

**Issue by yangsamuellu** [ant-design/ant-design-mobile#3269]
import { List, Switch, Calendar } from 'antd-mobile';

如何在 ReactNative的项目工程里面，调用antd-mobile里面的相关组件？请问有没有官方的 Demo  ?

**Comment by yangsamuellu** [comment]
@sorrycc @cncolder @ko @andriijas @

**Comment by likezero** [comment]
目前没有，RN请使用组件库 https://github.com/ant-design/ant-design-mobile-rn/

**Comment by yangsamuellu** [comment]
@likezero 您好。我们确实是在使用您说的这个组件库，但是我们想使用如下图中的组件，那可以使用Calendar吗？
![image](https://user-images.githubusercontent.com/12060258/60250277-e0108080-98f8-11e9-93d8-8c568383ad1c.png)

**Comment by pantaopt** [comment]
好像没有rn版本的antd-mobile calendar组件
目前的antd-mobile-rn也不维护了吧
