### ISSUE TITLE
BrowserslistError: Unknown browser query `android all`

### ISSUE THREAD

**Issue by empty-back** [ant-design/ant-design-mobile#3271]
BrowserslistError: Unknown browser query `android all`

**Comment by chen86860** [comment]
add this following config in `package.json` will resolve this problem.

```json 
"resolutions": {
    "browserslist": "4.6.2",
    "caniuse-lite": "1.0.30000974"
  }
```

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
