### ISSUE TITLE
不能使用className吗？

### ISSUE THREAD

**Issue by HHuiHao** [ant-design/ant-design-mobile#3273]
背景颜色没变化
```
<NavBar className="app__nav">发现</NavBar>

.app__nav {
  background-color: #e2664b;
}

```

**Comment by likezero** [comment]
测试了下是可以的。
![image](https://user-images.githubusercontent.com/2275857/60077581-e10cab00-975c-11e9-89bd-4cf87d9e13a5.png)
![image](https://user-images.githubusercontent.com/2275857/60077592-e79b2280-975c-11e9-9bdc-b25196eb1e29.png)

![image](https://user-images.githubusercontent.com/2275857/60077556-d3572580-975c-11e9-813d-cce3d63bfe27.png)

**Comment by HHuiHao** [comment]
好的，谢谢回复，是我导入css文件出了问题.
