### ISSUE TITLE
Throw ReferenceError in graceful-fs when installing dependencies 

### ISSUE THREAD

**Issue by yeomanyang** [ant-design/ant-design-mobile#3274]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/gulpjs/vinyl-fs/blob/master/package.json](https://github.com/gulpjs/vinyl-fs/blob/master/package.json)

### Steps to reproduce
```
$ node version：12.2.0
$ npm i
```

### What is expected?
Dependent installed success.

### What is actually happening?
```
fs.js:27
const { Math, Object } = primordials;
                         ^
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/gongcheng/Repositories/ant-design-mobile/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/gongcheng/Repositories/ant-design-mobile/node_modules/natives/index.js:55:10)
```

| Environment | Info |
|---|---|
| antd | 2.2.14 |
| React | 16.8.6 |
| System | Mac OS 10.14.5 |
| Browser | Chrome |

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
