### ISSUE TITLE
webpack externals antd 打包不能移除antd的组件吗？

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#3278]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
webpack
```
  externals: {
    'react': 'React',
    'react-dom': 'ReactDOM',
    'react-router-dom':'ReactRouterDOM',
    'antd': 'antd'
  }
```

项目引入
```
import {Button as AntdButton} from 'antd-mobile';
```

打包结果
```
  b.defaultProps = {prefixCls: 'am-button', size: 'large', inline: !1, disabled: !1, loading: !1, activeStyle: {}}, e.default = b, n.exports = e.default;
```
![image](https://user-images.githubusercontent.com/12706830/60085244-8464bc80-976b-11e9-833c-cb442d59140a.png)

### What does the proposed API look like?
期望打包的时候移除有关antd的相关组件

**Comment by NeroSolomon** [comment]
@codedart2018 请问你是如何解决这个问题的呢？
