### ISSUE TITLE
antd mobile 访问web组件慢的不行

### ISSUE THREAD

**Issue by xgAnd** [ant-design/ant-design-mobile#3279]
https://mobile.ant.design/components/flex-cn/  访问ReactNative组件的网站速度还行 访问web的组件慢的不行可以维护一下子嘛，文档，什么的根本访问不了啊

**Comment by xgAnd** [comment]
![A5F3F832-19F2-407A-9E8E-2FCDAE1DBC30](https://user-images.githubusercontent.com/27660602/60088953-2091c200-9772-11e9-9e95-1217c9cc2f8d.png)

**Comment by ziluo** [comment]
确认下，是所有页面都很慢还是特定页面比较慢呢，前段时间确实刚切换了DNS服务商 https://github.com/ant-design/ant-design-mobile/issues/3226

**Comment by xgAnd** [comment]
> 确认下，是所有页面都很慢还是特定页面比较慢呢，前段时间确实刚切换了DNS服务商 #3226

昨晚在家里测试了一下，访问还可以。但是公司的网还是不行，所有页面都很慢。一个都打不开
![A1F9EF5F-8E08-4C38-9D64-063B517F24B4](https://user-images.githubusercontent.com/27660602/60144083-b15cb200-97f3-11e9-99fc-5d51fe8960ed.png)

![1B13160D-738F-4057-A6C3-5125F3BE880C](https://user-images.githubusercontent.com/27660602/60144047-99852e00-97f3-11e9-9375-63f4a38d2172.png)

**Comment by xgAnd** [comment]
![E931099B-5122-4895-B7B6-89CFE63DC749](https://user-images.githubusercontent.com/27660602/60144198-1a442a00-97f4-11e9-9df1-3721987b877a.png)

**Comment by yesmeck** [comment]
看下访问 https://ant.design 的速度如何

**Comment by xgAnd** [comment]
> https://ant.design
访问这个网站速度还不错 打开的挺快  
但是https://mobile.ant.design/components/modal-cn/ 这个还是不行 现在首页都进不去了。
![E74FEF1B-41A2-4782-BFF8-79DA2DDB4629](https://user-images.githubusercontent.com/27660602/60417675-9931cc00-9c13-11e9-963d-8b6320cefb21.png)

**Comment by xgAnd** [comment]
![11](https://user-images.githubusercontent.com/27660602/60417801-e746cf80-9c13-11e9-9f73-99db91014eed.jpg)

**Comment by xgAnd** [comment]
![B188EB4D-4A4F-4627-8CAF-611FBAE73CBE](https://user-images.githubusercontent.com/27660602/60417909-26752080-9c14-11e9-9505-b4bf0aa826b6.png)

**Comment by yesmeck** [comment]
@ziluo 网站生成的有问题，所有 cn 目录都没生成出来

https://github.com/ant-design/ant-design-mobile/tree/gh-pages/components

对照 antd 的：

https://github.com/ant-design/ant-design/tree/gh-pages/components

**Comment by likezero** [comment]
这个访问还慢吗

**Comment by xgAnd** [comment]
可以了  速度不慢了。
![44CE8C10EA0C049F90E1F6A3CDCF43A2](https://user-images.githubusercontent.com/27660602/61772954-12dd6400-ae26-11e9-8be8-a9759fc22458.gif)
