### ISSUE TITLE
Uncaught ReferenceError: antd is not defined

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#3281]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gitee.com/myxingke/webpack_react_template](https://gitee.com/myxingke/webpack_react_template)

### Steps to reproduce
step:1
```
import React from 'react';
import ReactDOM from 'react-dom';
//import routers from './routers';
//自定义scss
import './assets/styles/scss.scss';
//import 'antd-mobile/dist/antd-mobile.css';
import {Button} from 'antd-mobile';

//全局视图路径基于 src 目录
window.viewsPath = 'views';

const App = () => {
  return (
    <Button type="primary">default</Button>
  )
}

ReactDOM.render(<App/>, document.getElementById('root'));
if (module.hot) {
  module.hot.accept();
}

```

step:2
run build

step:3
run index.html

result:
```
Uncaught ReferenceError: antd is not defined
```

我看到有说要引入 moment 实际我引入 moment 结果还是一样
```
<!doctype html>
<html lang=zh-CN>
<head>
    <meta charset=utf-8>
    <meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title>webpack react template demo</title>
    <link rel="shortcut icon" href="favicon.ico">
    <link href="https://cdn.staticfile.org/antd-mobile/2.2.13/antd-mobile.min.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
</head>
<body>
<noscript> You need to enable JavaScript to run this app.</noscript>
<div id=root></div>
<script src="https://cdn.staticfile.org/react/16.7.0/umd/react.production.min.js"></script>
<script src="https://cdn.staticfile.org/react-dom/16.7.0/umd/react-dom.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-router-dom/4.3.1/react-router-dom.min.js"></script>
<script src="https://cdn.bootcss.com/moment.js/2.24.0/moment.min.js"></script>
<script src="./antd-mobile.min.js"></script>
<script type="text/javascript" src="js/main.js"></script>
</body>
</html>

```

result:
```
Uncaught ReferenceError: antd is not defined
```

![image](https://user-images.githubusercontent.com/12706830/60145879-10bdc080-97fa-11e9-9b46-1c35ba31d50a.png)
![image](https://user-images.githubusercontent.com/12706830/60145914-28954480-97fa-11e9-909b-e523a6c9c4ba.png)

### 开发环境
![image](https://user-images.githubusercontent.com/12706830/60145939-3945ba80-97fa-11e9-968f-52bb909101b6.png)

### What is expected?
正常运行

### What is actually happening?
```
Uncaught ReferenceError: antd is not defined
```

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.7.0 |
| System | macos |
| Browser | 版本 75.0.3770.100（正式版本） （64 位） |

**Comment by tolerious** [comment]
你好，解决了么？

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
