### ISSUE TITLE
Menu菜单多选模式下底部的两个按钮文案能不能改成可配置的

### ISSUE THREAD

**Issue by viccsen** [ant-design/ant-design-mobile#3282]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前是确定取消，如果能动态更改按钮文案，能适应更多场景。

### What does the proposed API look like?
希望Menu新增两个属性，okText, cancelText。

**Comment by QiuZi619** [comment]
+1

**Comment by awmleer** [comment]
Menu 组件在新版的 antd-mobile 中已经移除掉了，这个 issue 我关闭掉了
