### ISSUE TITLE
Missing codesandbox example for Result component

### ISSUE THREAD

**Issue by Pranit-Harekar** [ant-design/ant-design-mobile#3283]
The documentation for `Result` component for React Native Ant design has missing codesandbox example. 

Please check here:
https://rn.mobile.ant.design/components/result/ 

![image](https://user-images.githubusercontent.com/17886017/60184266-be7aa080-97f5-11e9-8c10-036243999c7c.png)

It will be great if you guys can add an example. Thank you!

**Comment by Pranit-Harekar** [comment]
I created one sample, https://codesandbox.io/s/result-6t8n0

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
