### ISSUE TITLE
Picker组件问题

### ISSUE THREAD

**Issue by L-Hknu** [ant-design/ant-design-mobile#3291]
Picker 的事件只返回了value 的内容。但是实际使用中经常遇到label，value都需要的场景。
再一步开发者自己处理是就非常麻烦 建议暴露第二参数

**Comment by xyj404** [comment]
@L-Hknu Picker的format属性可以获取label的数组

**Comment by L-Hknu** [comment]
> @ L-Hknu Picker的格式属性可以获取label的数组

时序呢？format和其他事件相比。label value 需要合成新的数据。怎么解决这个时许性的问题

**Comment by xyj404** [comment]
> > @ L-Hknu Picker的格式属性可以获取label的数组
> 
> 时序呢？format和其他事件相比。label value 需要合成新的数据。怎么解决这个时许性的问题

什么时序性？不太理解你的问题

**Comment by L-Hknu** [comment]
> > > @ L-Hknu Picker的格式属性可以获取label的数组
> > 
> > 
> > 时序呢？format和其他事件相比。label value 需要合成新的数据。怎么解决这个时许性的问题
> 
> 什么时序性？不太理解你的问题

他的执行顺序呢。是否在其他事件之前

**Comment by xyj404** [comment]
> > > > @ L-Hknu Picker的格式属性可以获取label的数组
> > > 
> > > 
> > > 时序呢？format和其他事件相比。label value 需要合成新的数据。怎么解决这个时许性的问题
> > 
> > 
> > 什么时序性？不太理解你的问题
> 
> 他的执行顺序呢。是否在其他事件之前

我试了一下，format在onChange和onOk之后，如果是获取选择的value和label是可以的，看你的实际需求，可能需要自己组装下数据。

**Comment by L-Hknu** [comment]
> > > > > @ L-Hknu Picker的格式属性可以获取label的数组
> > > > 
> > > > 
> > > > 时序呢？format和其他事件相比。label value 需要合成新的数据。怎么解决这个时许性的问题
> > > 
> > > 
> > > 什么时序性？不太理解你的问题
> > 
> > 
> > 他的执行顺序呢。是否在其他事件之前
> 
> 我试了一下，format在onChange和onOk之后，如果是获取选择的value和label是可以的，看你的实际需求，可能需要自己组装下数据。

谢谢

**Comment by 91Bruce** [comment]
为什么我使用format  选择后无法显示选中的值

**Comment by L-Hknu** [comment]
> 为什么我使用格式选择后无法显示选中的值

你使用回调把参数传到函数里

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
