### ISSUE TITLE
是否考虑用react-scripts-rewired 来改写webpack 实现按需加载

### ISSUE THREAD

**Issue by Yangzhi1997** [ant-design/ant-design-mobile#3299]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前需要 react-scripts  react-app-rewired customize-cra 三个库来实现按需加载 是否可以通过'react-scripts-rewired' 来实现,就只需要一个库了

### What does the proposed API look like?
按需加载方式

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
v5 的按需加载是不需要做额外配置的
