### ISSUE TITLE
Carousel .slider-list height 第一次计算正确，路由切换回来的时候height 计算错误

### ISSUE THREAD

**Issue by hnsylitao** [ant-design/ant-design-mobile#330]
#### 本地环境

- antd-mobile 版本：0.8.7
- 操作系统及其版本：OSX
- 浏览器及其版本：Chrome 53.0.2785.116
#### 你做了什么？

<img width="747" alt="a1" src="https://cloud.githubusercontent.com/assets/17537749/19020424/0b9c07f0-88db-11e6-864b-febe72623005.png">

用了React－Router 
切换 地址的时候在切换回来 slider-list

![a3](https://cloud.githubusercontent.com/assets/17537749/19020465/08930a8a-88dc-11e6-893e-2a841633b812.gif)

**Comment by hnsylitao** [comment]
第一次路由是／home
第二次是／user
但是 第二次切换回来的时候 ul 的高度就不正确了。

**Comment by silentcloud** [comment]
我用最新版的写了一个简单的例子，没能重现
@hnsylitao 升级到新版试试，如果还有问题的话，麻烦把有问题的代码项目精简打包上传上来，我们再排查哈

issue 我先关了，有问题，再 reopen
