### ISSUE TITLE
TabBar Position bottom fail

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design-mobile#3300]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/MMqLXW](https://codepen.io/anon/pen/MMqLXW)

### Steps to reproduce
see https://codepen.io/anon/pen/MMqLXW

### What is expected?
at bottom by default

### What is actually happening?
at top

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | latest |
| System | Mac |
| Browser | Chrome 75 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
