### ISSUE TITLE
ImagePicker组件 url中存在空格无法显示问题

### ISSUE THREAD

**Issue by baoxiangyang** [ant-design/ant-design-mobile#3302]
url ： http://pkms.oss-cn-shenzhen.aliyuncs.com/resource/affiliate/d016828a5aecac91/96e309f9c086f909timg%20(6).jpg
就算我给链接地址进行encodeURI 图片还是不展示。
看了ImagePicker 的源码，在dom上background-image样式也没有添加上。
原因是没有给图片地址添加“”
给antd-mobile/es/image-picker/inex.js的176行 的style添加上“ 就好了。望修复
` var imgStyle = {
                    backgroundImage: 'url("' + image.url + '")',
                    transform: 'rotate(' + _this2.getRotation(image.orientation) + 'deg)'
                };`

**Comment by Evanna51** [comment]
@likezero @ziluo 请问这个Fix将在哪个版本发呢？大概时间是什么时候？因为比较影响用户使用，所以除了等待发版还有别的解决办法吗，谢谢
