### ISSUE TITLE
drawer 可以增加一个动画完成后的回调吗

### ISSUE THREAD

**Issue by ppbl** [ant-design/ant-design-mobile#3303]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. 比如我模拟手机端搜索页，在抽屉中放了一个 InputItem
2. 我想让抽屉打开后自动获取焦点
3. 我现在直接 inputRef.foucs 样式会乱掉

### What does the proposed API look like?
比如 提供一个方法 onTransitionEnd 的回调方法，等 过渡动画完成后执行

**Comment by ppbl** [comment]
我又测试了下 ，在抽屉没有划出的时候强行给 input 焦点，抽屉会直接出来

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
