### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by a728384698** [ant-design/ant-design-mobile#3306]
![屏幕快照 2019-07-12 上午9 55 00](https://user-images.githubusercontent.com/7380874/61097014-31d61080-a48c-11e9-8932-efa4f6d20656.png)
![2019-07-12 上午9 55 09](https://user-images.githubusercontent.com/7380874/61117253-b181d080-a4c8-11e9-8e34-3890cce0b357.png)

![屏幕快照 2019-07-12 上午9 55 19](https://user-images.githubusercontent.com/7380874/61117298-c5c5cd80-a4c8-11e9-9bdc-cf64d584aa1f.png)

![屏幕快照 2019-07-12 上午10 02 03](https://user-images.githubusercontent.com/7380874/61117304-c9595480-a4c8-11e9-88da-70e9badaee5c.png)

完全不知道问题出在哪儿，用2.2.13 还是出这个问题
直接使用没有配置babel-plugin-import 也是这个问题
配置了babel-plugin-import 一样的错误

**Comment by likezero** [comment]
看报错，是组件名首字母用了小写。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
