### ISSUE TITLE
backtop一键返回顶部组件

### ISSUE THREAD

**Issue by artdong** [ant-design/ant-design-mobile#3314]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
list很长时可以很方便回到顶部

### What does the proposed API look like?
<BackTop/>

**Comment by liujiayii** [comment]
@awmleer @xiaohuoni 这个可以支持一下吗？

**Comment by awmleer** [comment]
暂时没有计划支持，得业务项目自己实现了～

**Comment by xiaohuoni** [comment]
```
const el = document.scrollingElement || document.documentElement;
    if (el.scrollTop !== 0) {
      el.scrollTop = 0;
    }
```
