### ISSUE TITLE
Error in ListView,when react(16.8.0)

### ISSUE THREAD

**Issue by yuweilan** [ant-design/ant-design-mobile#3317]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/ffb6a671](https://riddle.alibaba-inc.com/riddles/ffb6a671)

### Steps to reproduce
渲染listView吸顶功能的时候报错

### What is expected?
加入吸顶功能时，listview可以正常显示

### What is actually happening?
listView Sticky报错，标题无法正常显示

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8.0 |
| System | 无 |
| Browser | 无 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
