### ISSUE TITLE
Add new disabled prop to PullToRefresh component

### ISSUE THREAD

**Issue by zechau** [ant-design/ant-design-mobile#3320]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
my page has  two more componnets includes PullToRefresh and One of them can swipe. When I was swiping, I don't wanna trigger "pull to refresh”.

### What does the proposed API look like?
if I set disabled true, the pull to refresh action will not be triggered.

**Comment by zechau** [comment]
#3065

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
