### ISSUE TITLE
Carousel component can not be used in mobile browser with right-sliding return function. Left-right sliding will switch pages  router instead of switch  Carousel. The test machine is MI8.

### ISSUE THREAD

**Issue by icedJuice** [ant-design/ant-design-mobile#3321]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/icedJuice/react-deom.git](https://github.com/icedJuice/react-deom.git)

### Steps to reproduce
Open and Slide it.

### What is expected?
Can function properly in that browers

### What is actually happening?
when you slide it ,  brower will switch page router  instead of switch Carousel

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8 |
| System | MUI 10.3.3 |
| Browser | MI8 browser  V10.8.3,   UC browser  V12.5.61036 |

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
