### ISSUE TITLE
Tabs的underline如何自定义宽度且能居中修改样式后的文字下面

### ISSUE THREAD

**Issue by ZhangMingZhao1** [ant-design/ant-design-mobile#3322]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
更好的扩展tabs

### What does the proposed API look like?
当修改了tabbar的宽度后，文字由原来的各占一半变成偏向居中一点，但是underline的线还是一半的宽度，改了underline的线宽度也不能跟在文字的正下方。

**Comment by ZhangMingZhao1** [comment]
比如想要下面这个样式：
![A31490E251B440C0F182E249F02EFA98](https://user-images.githubusercontent.com/29058747/61787223-f51df800-ae41-11e9-8ce0-a27f0bc7f39e.jpg)

我修改覆盖样式后只能这样：
![image](https://user-images.githubusercontent.com/29058747/61787522-88572d80-ae42-11e9-9792-acb381c55bd7.png)

am-tabs-default-bar-underline 是绝对定位的，要修改好这个感觉还要修改js事件？

**Comment by ilvseyinfu** [comment]
怎么解决的？ 同问

**Comment by ilvseyinfu** [comment]
我有一个解决方案：
1. 先计算出你需要偏移的量 m （m可以达到居中）
2.  查看每次 antd 自动偏移的量 n
3.  onChange 后 手动更新 left为 n * index + m 
4. 需要注意回到index = 0 时 需要手动指定 left 为 m

```html
<Tabs tabs={tabs} onChange={(tab, index) => { this.changeTabs(tab, index); }} tabBarUnderlineStyle={{ borderBottomWidth: 0.7, borderBottomColor: 'rgba(255, 64, 2, 1)', width: '0.3rem', textAlign: 'center', left: '10%' }} />}>
```

```
  changeTabs(tab, index) {
    if(index === 0) {
      document.getElementsByClassName('am-tabs-default-bar-underline')[0].style.left = '10%';
    }
    document.getElementsByClassName('am-tabs-default-bar-underline')[0].style.left = 25 * index + 10 + '%';
  }
```

**Comment by xilianxiaoli** [comment]
建议官方能支持设置，这是刚需呀

**Comment by syhsghr1993** [comment]
tabBarUnderlineStyle={{ transform: 'scaleX(0.x)' }}

**Comment by dinglino1** [comment]
> 我有一个解决方案：
> 
> 1. 先计算出你需要偏移的量 m （m可以达到居中）
> 2. 查看每次 antd 自动偏移的量 n
> 3. onChange 后 手动更新 left为 n * index + m
> 4. 需要注意回到index = 0 时 需要手动指定 left 为 m
> 
> ```
> <Tabs tabs={tabs} onChange={(tab, index) => { this.changeTabs(tab, index); }} tabBarUnderlineStyle={{ borderBottomWidth: 0.7, borderBottomColor: 'rgba(255, 64, 2, 1)', width: '0.3rem', textAlign: 'center', left: '10%' }} />}>
> ```
> 
> ```
>   changeTabs(tab, index) {
>     if(index === 0) {
>       document.getElementsByClassName('am-tabs-default-bar-underline')[0].style.left = '10%';
>     }
>     document.getElementsByClassName('am-tabs-default-bar-underline')[0].style.left = 25 * index + 10 + '%';
>   }
> ```

为什么我这样写无效呢？am-tabs-default-bar-underline的left虽然是改变了 但是页面效果还是组件自带的

**Comment by hustcer** [comment]
> tabBarUnderlineStyle={{ transform: 'scaleX(0.x)' }}

Thanks a lot.

**Comment by wyh-skr** [comment]
设置伪元素就可以了，完美解决   
 .am-tabs-default-bar-underline {
      border: 0;
      display: flex;
      justify-content: center;
      &::after {
        content: '';
        width: 20%;
        height: 4px;
        display: block;
        background: @primary-color;
      }
    }

**Comment by Xiaocaiji2333** [comment]
厄特

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by Jennifer249** [comment]
.ant-tabs .ant-tabs-ink-bar {
      transform: translateX(6px);
    }

相对位移
