### ISSUE TITLE
定制主题后的button组件primary类型active状态色值不对

### ISSUE THREAD

**Issue by helen1283** [ant-design/ant-design-mobile#3323]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/button-cn/](https://mobile.ant.design/components/button-cn/)

### Steps to reproduce
定制主题--><Button type="primary">primary</Button>，点击按钮

### What is expected?
button组件primary类型active状态应该是主题相关色

### What is actually happening?
button组件primary类型active状态是默认的蓝色

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | react |
| System | os 10.13.6 |
| Browser |  Chrome 75.0.3770.142 |

**Comment by helen1283** [comment]
![image](https://user-images.githubusercontent.com/15864408/61839951-2ccc8480-aec2-11e9-8128-c39841912c6c.png)

**Comment by syhsghr1993** [comment]
+1

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
