### ISSUE TITLE
Calendar getDateExtra How to fetch data using ReactHooks and Async

### ISSUE THREAD

**Issue by sujing219** [ant-design/ant-design-mobile#3327]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/sujing219/pen/aemGpx](https://codepen.io/sujing219/pen/aemGpx)

### Steps to reproduce
1. 不用看上面连接，文字描述很好理解；
2. Calendar 在日期下面添加日期对应的自定义数据，如添加近半年可预订信息；
3. Async Fetch 半年可预订数据   useEffect   getDateExtra 不能适时把可预定信息渲染进组件；
4. 点一个月份中的日期，就能显示当月部分数据；
5. 在滚动到下一个月份，没有扩展数据，点击之后，方能显示出来；

![1-nodata.png](https://i.loli.net/2019/07/26/5d3ab79088fb397559.png)

没有显示近半年可预订数据

![2-diff.png](https://i.loli.net/2019/07/26/5d3ab790a322a54457.png)

点击月份中日期，可显示，但没有点击的月份，不能显示

### What is expected?
getDateExtra 能显示异步数据

### What is actually happening?
getDateExtra 不能显示异步数据

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8.0 |
| System | Windows 10 |
| Browser | Chrome 75 |

**Comment by lee-Tony** [comment]
我也遇到了这个问题，题主解决没有

**Comment by sunflower-tc** [comment]
我也遇到了这个问题，题主解决没有 同样问题

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
