### ISSUE TITLE
react native 问题

### ISSUE THREAD

**Issue by github-gage** [ant-design/ant-design-mobile#333]
#### 本地环境

- antd-mobile 版本：0.9.0
- 操作系统及其版本：macOS Sierra
- 浏览器及其版本：Chrome 53

#### 你做了什么？

按 照README.md 配置

`import Button from 'antd-mobile/lib/button';` 正常

`import {Button} from 'antd-mobile';` 不正常

#### 你期待的结果是：

 像官网一样正常显示 

#### 实际上的结果：

Unable to resolve module antd-mobile from ****** /rn_test/index.ios.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/antd-mobile and its parent directories

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

RCTFatal + 104
-[RCTBatchedBridge stopLoadingWithError:] + 1138
__25-[RCTBatchedBridge start]_block_invoke_2 + 65
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_main_queue_callback_4CF + 1054
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
__CFRunLoopRun + 2205
CFRunLoopRunSpecific + 420
GSEventRunModal + 161
UIApplicationMain + 159
main + 111
start + 1
0x0 + 1

**Comment by warmhug** [comment]
https://github.com/ant-design/ant-design-mobile#use-babel-plugin-import

**Comment by github-gage** [comment]
之前按照这个配置了的，一直是报错

**Comment by silentcloud** [comment]
@github-gage  https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo 这个 demo 你能跑起么？

**Comment by github-gage** [comment]
也跑不起来，实在不行只有这样写了：
`import Button from 'antd-mobile/lib/button'; `

**Comment by yiminghe** [comment]
npm3 node 4.x 运行 https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo

**Comment by smalltide** [comment]
我目前這樣搭配可以運行
https://github.com/smalltide/react-native-antd
