### ISSUE TITLE
InputItem 会自动生成  pattern 属性的问题，导致浏览器不能提交！

### ISSUE THREAD

**Issue by tyua07** [ant-design/ant-design-mobile#334]
#### 本地环境

- antd-mobile 版本：0.9.0
- 操作系统及其版本：macOS
- 浏览器及其版本：53.0.2785.116 (64-bit)

#### 你做了什么？

引入了 ``` InputItem ``` ,  ``` input ```  默认生成了 ``` pattern ``` 

源码如下

```
pattern: type === 'number' ? '[0-9]*' : '' 

```

#### 你期待的结果是：

当我 ``` type ``` 定义的是非number的时候,可以允许提交 form 。

#### 实际上的结果：

浏览器会提示 ``` 请输入所请求的格式保持一致 ``` 的错误提示！

**Comment by pingan1927** [comment]
马上修复，尽快发布小版本修复
