### ISSUE TITLE
输入框在ios中轻触不能focus

### ISSUE THREAD

**Issue by ZH4L** [ant-design/ant-design-mobile#3347]
输入框在ios中轻触不能focus，要重按或者点击时间长一点才行，安卓中没有这个问题

官方示例就有这个问题

**Comment by 13007640364** [comment]
我也遇到了这个问题，解决方法是，在输入框外包一个di，,然后在div的点击事件中手动给输入框聚焦

**Comment by caicai199604** [comment]
我也遇到了。在ios 12.4以上  ，text 类型特别明显.

**Comment by ioing** [comment]
看了下源码，有设置了setTimeout，不知道是不是怕滚动时误触，但这个做法真的不适当，目前造成ios上点击不中的概率非常高！

**Comment by wenhc** [comment]
楼主是不是轻触的时候还伴随这键盘弹起，但是挡住输入框

**Comment by 6201** [comment]
我也遇到这个问题，但是发现和引入的另一个库fastclick有关系，停用 掉 fastclick 就可以。

**Comment by yhuaxing** [comment]
我也遇到了，在ios中，有时点好几次或几秒都不能focus

**Comment by waynehong** [comment]
这个bug也太严重了吧，影响很大，我自己没有用到fastclick，都不知道怎么停用，请维护团队尽快修复！

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
