### ISSUE TITLE
InputItem，表单正常输入，输入一半或者输入错误，按clear清除，清除失败（校验规则触发条件：onBlur）

### ISSUE THREAD

**Issue by renyangmei** [ant-design/ant-design-mobile#3351]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/renyangmei/pen/bXvxjg?editors=0110](https://codepen.io/renyangmei/pen/bXvxjg?editors=0110)

### Steps to reproduce
校验规则触发条件：onBlur
操作步骤：表单正常输入，输入一半或者输入错误，按clear清除，清除失败

### What is expected?
输入错误或者输入一半，按clear可清除，然后再做error错误提醒

### What is actually happening?
error错误提醒出现，清除失败

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | react |
| System | Windows 7 旗舰版 64-bit (6.1, Build 7601)  和 android 9 和ios  |
| Browser | Google Chrome 版本 75.0.3770.100（正式版本） （32 位） |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
