### ISSUE TITLE
程序切出Slider滑动bug

### ISSUE THREAD

**Issue by JiaLinJason** [ant-design/ant-design-mobile#3354]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/slider-cn/](https://mobile.ant.design/components/slider-cn/)

### Steps to reproduce
移动端滑动Slider的时候切出(pc端模拟器使用alt tab)，移动端环境在拖拽滑块的状态下切出程序(测试过的有按下锁屏按钮和下拉状态栏)

### What is expected?
Slider在其范围内正常滑动

### What is actually happening?
slider操作范围扩大到整个屏幕，并且在多个Slider的同时故障的情况下几个Slider会一起滑动

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8.16 |
| System | iPhone; CPU iPhone OS 11_0 like Mac OS X |
| Browser | AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1 |

**Comment by wickedcode01** [comment]
slider在移动端触摸经常失灵，你彭没碰到过啊？3次里面能成功滑动一次就算好了，很影响用户体验啊。到底什么原因？这个项目没人维护了吗？

**Comment by JiaLinJason** [comment]
@wickedcode01 失灵的情况没碰到过，就是有个这个切出bug，我这个bug报告了这么长时间也没官方一句回复，估计差不多没人维护了

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by G21iwenjun** [comment]
> v2 已停止维护了，可以考虑升级一下
升级到antd-mobile@^5.0.0-rc.18，或者使用的是https://mobile.ant.design/zh/components/slider页面在手机滑动slider不放手，下拉手机状态栏依然会导致整个屏幕可以操作slider组件

**Comment by awmleer** [comment]
@G21iwenjun 目前的确有这个问题，后面我们会修复，详见这个 issue：#4642
