### ISSUE TITLE
Tabs里面的div没有被渲染

### ISSUE THREAD

**Issue by sparGuan** [ant-design/ant-design-mobile#3355]
![83A0C43F638A7EC354D29E32EDBD6978](https://user-images.githubusercontent.com/28480563/62830132-d5f1d980-bc3b-11e9-8c02-216042a9c50b.jpg)
![image](https://user-images.githubusercontent.com/28480563/62830133-e2763200-bc3b-11e9-99d1-2168887ae15e.png)
我是完全按照官网的demo写的代码，但是里面的div没有被渲染，然后放到codepen里面去就可以渲染出来
![image](https://user-images.githubusercontent.com/28480563/62830143-0cc7ef80-bc3c-11e9-846b-ad4af9de3b99.png)
怀疑是不是react版本支持的bug？

**Comment by sparGuan** [comment]
找到原因了，这个antd-mobile的一个bug@！！！！
![image](https://user-images.githubusercontent.com/28480563/62830204-477e5780-bc3d-11e9-82be-a84cd192f20f.png)
设置的key是wu'xiao无效的！！！

**Comment by pkl93** [comment]
我也遇到同样问题， 只要tabs里带key的，都不显示，官网带key的例子也没有渲染出来。

**Comment by wenyanqi** [comment]
+1

**Comment by wfk007** [comment]
+1

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
