### ISSUE TITLE
Picker不支持自定义数组key值

### ISSUE THREAD

**Issue by alan89757** [ant-design/ant-design-mobile#3357]
Picker组件只支持[{label: 'aaa', value: 1}, {label: 'bbb', value: 2} ...]键值对格式
接口返回的不一定是这样的格式[{cityName: 'shanghai', val: '30100'}, {cityName: 'tiantian', val: '30200'} ...]，能否支持自定义，来前端还要组装下，好麻烦啊
谁有好的解决方法吗？

**Comment by lixuecn** [comment]
您好 Picker组件通过后端获取的数据在手机不显示 ，您有遇到么？电脑上没问题

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
