### ISSUE TITLE
DatePicker user12hours后minDate描述不准确

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design-mobile#3358]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-zumt2)

### Steps to reproduce
开始时间选则11点后，结束时间无法选则下午时间

### What is expected?
合理判断时间范围

### What is actually happening?
不能选则相对较晚的下午时间

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8  |
| System | win |
| Browser | chrome |

**Comment by Fled8617** [comment]
感觉应该属于rcm date picker的问题，希望mobile同步升级

**Comment by awmleer** [comment]
新版的 DatePicker 不再支持 12 小时限制了，这个 issue 先关闭了
