### ISSUE TITLE
mobile兼容性咨询

### ISSUE THREAD

**Issue by asoqa** [ant-design/ant-design-mobile#336]
咨询一下，antd的mobile版本对android和ios同时兼容吗? 分别支持的最低版本是多少？是否经过充分测试？

**Comment by pingan1927** [comment]
Android4.0及iOS8.4以上。
已经有很多线上产品在使用

**Comment by warmhug** [comment]
欢迎帮忙一起测试，欢迎提具体的问题 issue ，谢谢

**Comment by Glisterzh** [comment]
目前使用版本是2.1.8，但是在ios9和iOS10都出现很多页面空白的情况，请问如何完善？
