### ISSUE TITLE
https://mobile.ant.design/components/tabs-cn/ Demo 报错

### ISSUE THREAD

**Issue by mrzzcn** [ant-design/ant-design-mobile#3364]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/tabs-cn/](https://mobile.ant.design/components/tabs-cn/)

### Steps to reproduce
https://mobile.ant.design/components/tabs-cn/

### What is expected?
正常展示？

### What is actually happening?
预览Demo 空白

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.8 |
| System | Mac |
| Browser | Chrome  |

---
kitchen-sink.js:1 Uncaught ReferenceError: ReactRouter is not defined
    at Object.<anonymous> (kitchen-sink.js:1)
    at t (common.js:1)
    at Object.<anonymous> (kitchen-sink.js:1)
    at t (common.js:1)
    at window.webpackJsonp (common.js:1)

**Comment by ziluo** [comment]
Sorry，已修复发布上线

**Comment by EndlessTJ** [comment]
依然无法打开

**Comment by ZH4L** [comment]
> Sorry，已修复发布上线

还是进不去
