### ISSUE TITLE
 Does Carousel have functions similar to swiper4  threshold?

### ISSUE THREAD

**Issue by jesome** [ant-design/ant-design-mobile#3366]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I slide on the mobile side, sometimes the slide is not straight line, and other pages appear.

### What does the proposed API look like?
refer to https://www.swiper.com.cn/api/touch/62.html

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
