### ISSUE TITLE
文档报错诶 大家的都没有问题么

### ISSUE THREAD

**Issue by CiciIvory** [ant-design/ant-design-mobile#3368]

**Comment by CiciIvory** [comment]
![image](https://user-images.githubusercontent.com/40973214/63234829-9180c200-c269-11e9-9879-e962314df763.png)

**Comment by CiciIvory** [comment]
右边的演示页面一直没办法显示出来！！！！

**Comment by jesome** [comment]
没 你换手机看看

**Comment by xiaoshan100** [comment]
我都打不开了

**Comment by CiciIvory** [comment]
> 没 你换手机看看

手机看不了代码啊

**Comment by Daiyichen** [comment]
试了一上午，都没打开，以为网络问题。现在看，报同样的错误啊，picker选择器、DatePicker好多都不好使

**Comment by chenfengami** [comment]
同样的问题 只能去对应的组件里面看md了

**Comment by k983551019** [comment]
是不是这被放弃了

**Comment by wd1336791007** [comment]
换个浏览器试试，我用谷歌就不行，但是我同事他们还可以打开，我换了idge就又可以了，估计火狐啥的乱试一下都可以（PS：和翻不翻墙无关）

**Comment by CiciIvory** [comment]
> 换个浏览器试试，我用谷歌就不行，但是我同事他们还可以打开，我换了idge就又可以了，估计火狐啥的乱试一下都可以（PS：和翻不翻墙无关）

可以！！！！用IE真的可以欸。。。

**Comment by wd1336791007** [comment]
> > 换个浏览器试试，我用谷歌就不行，但是我同事他们还可以打开，我换了idge就又可以了，估计火狐啥的乱试一下都可以（PS：和翻不翻墙无关）
> 
> 可以！！！！用IE真的可以欸。。。

可以关注我博客哈，很多踩坑记录我都会写出来的~     https://blog.csdn.net/weixin_43606158

**Comment by 549830579** [comment]
官网示例与本地安卓模拟器显示不一致,被关闭，给的答复真的非常敷衍"web 用的是 react native web 表现不一致比较正常",实际情况是整个官网的picker,datepicker等多个组件表现与本地完全不一样

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
