### ISSUE TITLE
stepper在手机中，按住按钮不放，会一直增加减少

### ISSUE THREAD

**Issue by littleGitYxr** [ant-design/ant-design-mobile#3371]
stepper在手机中，按住按钮不放，会一直增加减少，onchange一直触发，期望不可重复或连续点击进步器的加减按钮，以免一直触发，导致程序卡死或报错

**Comment by zhangzhixia** [comment]
我也有这个问题，啥时候修复一下啊各位大神

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
