### ISSUE TITLE
stepper在手机中，按住按钮不放，会一直增加减少

### ISSUE THREAD

**Issue by littleGitYxr** [ant-design/ant-design-mobile#3372]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://beta.51hexuan.com/m/goodsDetail.html#/25782e7ac5624463afd934cbc0e31d90](http://beta.51hexuan.com/m/goodsDetail.html#/25782e7ac5624463afd934cbc0e31d90)

### Steps to reproduce
stepper在手机中，按住按钮不放，会一直增加减少，onchange一直触发

### What is expected?
不可重复或连续点击进步器的加减按钮，以免一直触发，导致程序卡死或报错

### What is actually happening?
stepper在手机中，按住按钮不放，会一直增加减少，onchange一直触发

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16 |
| System | ios |
| Browser | 微信 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
