### ISSUE TITLE
alert 组件点击空白处报错

### ISSUE THREAD

**Issue by hepeng10** [ant-design/ant-design-mobile#3373]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN#modal-demo-0](https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN#modal-demo-0)

### Steps to reproduce
点击confirm弹出alert窗口，点击除Cancle和Ok两个按钮的任意位置控制台会输出错误信息

### What is expected?
不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.8.6 |
| System | win7 |
| Browser | 最新版chrome |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
