### ISSUE TITLE
backend.js:1 Warning: componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by flyingCrp** [ant-design/ant-design-mobile#3374]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://codepen.io/paranoidjk/pen/LWpaKe](http://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
update package.json:

       "antd-mobile": "^2.3.1",
       "rc-form": "^2.4.8",
        "react": "^16.9.0",       
        "react-dom": "^16.9.0",
        "react-router-dom": "^5.0.1",
        "react-scripts": "^3.1.1",

### What is expected?
no warning 

### What is actually happening?
got warning:

backend.js:1 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: SearchBar

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | ^16.9.0 |
| System | windows 10 |
| Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36 |

---
Update supports the  react v16.x  version

**Comment by alexchen1875** [comment]
ListView &  ScrollView &Animate  has the same problem
![image](https://user-images.githubusercontent.com/3668637/63329757-1dc3df80-c365-11e9-8718-5311b72b5375.png)

**Comment by hasstart** [comment]
Route, Router, Switch , Form, InputItem, Progress, Checkbox 

 "antd-mobile": "^2.3.1",
 "react": "^16.8.6",
 "react-dom": "^16.8.6",

**Comment by everlose** [comment]
the same in

antd 3.8.2
react: ^16.2.0,
react-dom: ^16.2.0,

**Comment by DemoHu** [comment]
Toast is the same

"antd-mobile": "^2.3.1",
"react": "^16.9.0",
"react-dom": "^16.9.0",

**Comment by Indigo744** [comment]
It's been several month and this lib has not seen an update for React 16.9 (it's 16.11 now). Is anybody still maintaining this lib? This is worrying.

**Comment by qiuziz** [comment]
Carousel has the same problem，hope to fix the issue
![image](https://user-images.githubusercontent.com/13669987/69615358-af7f6f00-106f-11ea-8a3a-4c6db1d06223.png)

**Comment by IceCrystal0k** [comment]
Same problem have Checkbox, Tag and probably most of  the components.
Using React 16.11.0.
  
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_
name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source
folder.
    
    Please update the following components: Tag
```

**Comment by hlipeter** [comment]
same as top.

**Comment by hopperhuang** [comment]
Is there a solution on this problem ?  Countinue focusing on the issue.

**Comment by Gu-Miao** [comment]
the same in

antd-mobile: `2.3.3`  
react: `16.13.1`

And the last line of warning:
`Please update the following components: InputItem, NumberInput`

**Comment by doxiaodong** [comment]
This is a huge action.

**Comment by paul4156** [comment]
Any updates?

**Comment by jianhao** [comment]
2021年八月，会有人更新么？

**Comment by awmleer** [comment]
@jianhao 等等v5吧～
https://next.mobile.ant.design

**Comment by Indigo744** [comment]
Any chance to have an English version of the documentation for this "next" v5?...

**Comment by awmleer** [comment]
> Any chance to have an English version of the documentation for this "next" v5?...

@Indigo744 Of course. We plan to add English documentation during the beta phase (around October in this year).

**Comment by Indigo744** [comment]
@awmleer thank you, we look forward to it 😸

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
