### ISSUE TITLE
toast组件能否提供指定关闭某个的功能

### ISSUE THREAD

**Issue by xianjie-li** [ant-design/ant-design-mobile#3376]
一个比较常见的情况是在请求开始时调用Toast.loading()，请求结束后调用Toast.hide()来隐藏提示框，但有时候请求结束后会使用Toast.info()等方法发起一个新的提示框，这时候如果调用Toast.hide()的话会提示框会被立即关闭
<br>
所以能否考虑提供类似下面这样的接口:
```js
const fn = Toast.loading();
fn() // 关闭指定的弹窗

// ..或者是这样

const flag = Toast.loading();
Toast.hide(flag);
```

**Comment by cuixbo** [comment]
支持，这样就可以具体的控制隐藏了

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
