### ISSUE TITLE
ActivityIndicator toast能否生成在body里？

### ISSUE THREAD

**Issue by ZH4L** [ant-design/ant-design-mobile#3378]
ActivityIndicator toast现在生成在调用的地方，很容易遇到transform对fixed产生影响的bug（父元素用了transform，fixed不再相对视口定位）,比如在Tabs中使用时，就有问题

**Comment by LukerSpringtree** [comment]
不是说提 issues 很严的吗?
为什么你这个能提 . 哈哈
很好奇

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
