### ISSUE TITLE
react +ts 使用PullToRefresh的缺少getScrollContainer,文档也没说这玩意啊

### ISSUE THREAD

**Issue by 374046604** [ant-design/ant-design-mobile#3379]

**Comment by 374046604** [comment]
(alias) class PullToRefresh
import PullToRefresh
Property 'getScrollContainer' is missing in type '{ children: Element; distanceToRefresh: number; damping: number; indicator: {}; ref: (el: PullToRefresh | null) => PullToRefresh | null; style: { height: string; overflow: string; }; direction: "down" | "up"; refreshing: boolean; onRefresh: () => void; }' but required in type 'Pick<Readonly<PropsType> & Readonly<{ children?: ReactNode; }>, "refreshing" | "style" | "children" | "className" | "getScrollContainer" | "direction" | "distanceToRefresh" | "onRefresh" | "indicator" | "damping">'.ts(2741)
PropsType.d.ts(9, 5): 'getScrollContainer' is declared here.

**Comment by yuzhou721** [comment]
..我今天想用这个的时候也发现这个问题

**Comment by xcodebin** [comment]
the same

**Comment by thelittlepandaisbehind** [comment]
同react+typescript，虽然把所有参数补全了，但是运行起来报错：PullToRefresh.js:138 Uncaught TypeError: ele.addEventListener is not a function

**Comment by superermiao** [comment]
the same

**Comment by Ignorance-of-Dong** [comment]
大佬们，有解决方法没？

**Comment by aSmallPing** [comment]
the same

**Comment by Heavn13** [comment]
一样 而且就算加入该属性之后 整个组件报错 显示TypeError: ele.addEventListener is not a function [PullToRefresh.js:119] 是不是这个组件开发的时候没有很好的适配ts？ 希望尽快解决

**Comment by wuhuaranran** [comment]
// @ts-ignore  可以正常使用

**Comment by liuruchao** [comment]
同问

**Comment by Winnie-nana** [comment]
我研究了一下,页面刷新功能至少能正常了,我是给PullToRefresh的标签上加了一个getScrollContainer={()=>undefined} 至少不报错,可以刷新了

**Comment by heyuuuu** [comment]
官方文档没更新，组件更新了，我也遇到这个问题，这个函数的声明: `getScrollContainer: () => React.ReactNode;`，你阔以看一下http://react-component.github.io/m-pull-to-refresh/examples/base.html这个，，或许就知道了该怎么使用了。

**Comment by yangfan-coder** [comment]
我也是遇到了这个问题 请问解决了吗？

**Comment by yangfan-coder** [comment]
我查阅资料得到 好像需要把`pullToRefresh`**参数写全不然会报错**
具体请看：[http://haoqiao.me/2018/12/03/pc-to-mobile.html](TS与antd-mobile的冲突)

**Comment by heyuuuu** [comment]
我上面不是回复了哇



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨老汉儿"<notifications@github.com&gt;; 
发送时间: 2020年12月30日(星期三) 上午10:44
收件人: "ant-design/ant-design-mobile"<ant-design-mobile@noreply.github.com&gt;; 
抄送: "当浮一大白"<664475324@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design-mobile] react +ts 使用PullToRefresh的缺少getScrollContainer,文档也没说这玩意啊 (#3379)





 
我也是遇到了这个问题 请问解决了吗？

**Comment by heyuuuu** [comment]
恩，你用的ts的话，要写全，那个就是获取一个父级节点的回调函数，你createref就行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨老汉儿"<notifications@github.com&gt;; 
发送时间: 2020年12月30日(星期三) 上午10:49
收件人: "ant-design/ant-design-mobile"<ant-design-mobile@noreply.github.com&gt;; 
抄送: "当浮一大白"<664475324@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design-mobile] react +ts 使用PullToRefresh的缺少getScrollContainer,文档也没说这玩意啊 (#3379)





 
我查阅资料得到 好像需要把pullToRefresh参数写全不然会报错
 具体请看：http://haoqiao.me/2018/12/03/pc-to-mobile.html

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by creeperyang** [comment]
> v2 已停止维护了，可以考虑升级一下

也许还是要升级下文档？

`getScrollContainer` 的返回值是当作 DOMElement 在代码中使用的，但是目前的类型却标注为 ReactNode。

**Comment by creeperyang** [comment]
> v2 已停止维护了，可以考虑升级一下

也许还是要升级下文档？

`getScrollContainer` 的返回值是当作 DOMElement 在代码中使用的，但是目前的类型却标注为 ReactNode。

**Comment by awmleer** [comment]
@creeperyang 你是说 v2 的文档么？不会更新了……
