### ISSUE TITLE
TextareaItem点击的时候无法快速获得焦点，弹起键盘

### ISSUE THREAD

**Issue by huberystyle** [ant-design/ant-design-mobile#3381]
TextareaItem快速点击的时候无法快速获得焦点并弹起键盘，整体感觉反应迟钝

**Comment by huberystyle** [comment]
输入框在ios中轻触不能focus #3347


3347 中网友反应说把 fastclick关掉就可以了，确实比之前快了点

官网可以解释下吗？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
