### ISSUE TITLE
Tabs中的列表PullToRefresh下拉刷新的时候，如果带上一点左右滑动，有一定几率会同时出发下拉刷新，和Tabs的左右切换

### ISSUE THREAD

**Issue by yjzzcao** [ant-design/ant-design-mobile#3383]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-i1k7u)

### Steps to reproduce
ListView下拉刷新时，如果不小心带上一点左右滑动，很容易出发外层Tabs的左右切换功能

### What is expected?
单次手势移动只触发一个事件

### What is actually happening?
PullToRefresh的手势与Tabs的手势冲突

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | latest |
| System | IOS |
| Browser | latest Chrome |

**Comment by yjzzcao** [comment]
#3065

**Comment by yjzzcao** [comment]
同 #3065

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
