### ISSUE TITLE
picker组件的问题

### ISSUE THREAD

**Issue by 91Bruce** [ant-design/ant-design-mobile#3386]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以同时获取value 和label

### What does the proposed API look like?
希望能说明下我遇到的问题的原因

**Comment by 91Bruce** [comment]
我再使用format的时候  无法显示选中的值

**Comment by 91Bruce** [comment]
而且 使用format更新state时会陷入死循环  是我的处理方式不对吗

**Comment by 91Bruce** [comment]
defaultFormat(values) {
        // label is JSX.Element or other
        if (values.length > 0 && typeof values[0] !== 'string') {
          return values;
        }
        else{
            this.setState({sexVal:values})
            return values.join(',');
        }
    }

**Comment by 91Bruce** [comment]
为什么不可以这样设置state的值  我该怎么操作

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
