### ISSUE TITLE
Drawer抽屉组件基本例子官网正常本地不正常，求更正，另外证明官网环境与本地确实有差异，不能用官网正常来成为功能正常的衡量指标 

### ISSUE THREAD

**Issue by xvusrmqj** [ant-design/ant-design-mobile#3387]
我不知道为啥要关 https://github.com/ant-design/ant-design-mobile/issues/408 这个issue，2016年的问题，现在依然这样，但是issue是关了？

**Comment by xvusrmqj** [comment]
不好使的解决方式如下：注释的为官网的，修改为下面即可。
![image](https://user-images.githubusercontent.com/2316516/64510092-dac9ac00-d313-11e9-856b-a81d21a3e12a.png)

**Comment by ferried** [comment]
就感觉 drawer 这个组件的使用方式很奇怪。。。非常奇怪

**Comment by gao-junfeng** [comment]
这东西一用 点击事件全部报废

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
