### ISSUE TITLE
textarea-item 组件计数问题

### ISSUE THREAD

**Issue by robinv8** [ant-design/ant-design-mobile#3388]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/textarea-item-cn/](https://mobile.ant.design/components/textarea-item-cn/)

### Steps to reproduce
```
 const entValue = value ? value.replace(regexAstralSymbols, '_') : '';
        const entLen = entValue ? entValue.split('_').length - 1 : 0;
        lengthCtrlProps.maxLength =
          count!   entLen - characterLength   (value ? value.length : 0);
```

Why should you use underscores?

### What is expected?
When count=10 can only enter ten characters

### What is actually happening?
Input unlimited
![image](https://user-images.githubusercontent.com/12277531/64511541-1fa31200-d317-11e9-8df4-1a4a521a6c27.png)
| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | react |
| System | ios 12.4 |
| Browser | null |

**Comment by shaolunyedd01** [comment]
I'm met this problem too,is there are anyone can solve this problem?

**Comment by ritingliudd01** [comment]
I met with this issue too. Wonder if would be possible to have it fixed very soon. Thanks for your efforts.

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
