### ISSUE TITLE
部分样式变量未提供

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#339]
包括但不限于：

### [Button](https://github.com/ant-design/ant-design-mobile/wiki/%E8%AE%BE%E8%AE%A1%E5%8F%98%E9%87%8F%E8%A1%A8%E5%8F%8A%E5%91%BD%E5%90%8D%E8%A7%84%E8%8C%83#button)：

- @primary-button-fill
- @primary-button-fill-tap
- @ghost-button-color
- @ghost-button-fill-tap 			
- @link-button-font-size 
- @link-button-fill-tap

**Comment by warmhug** [comment]
link-button 还没有这种按钮

**Comment by afc163** [comment]
那就先不搞，现有的先做上。

**Comment by afc163** [comment]
ping~
