### ISSUE TITLE
react-native 无法link @ant-design/icons-react-native

### ISSUE THREAD

**Issue by xiaoyaox** [ant-design/ant-design-mobile#3390]
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-amap3d: https://npmjs.com/package/react-native-amap3d
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. Run CLI with --verbose flag for more details.
无法link到，但是node_modules里面有这个icons-react-native文件夹，这个是什么原因

**Comment by onlyLiru** [comment]
我也遇到同样的问题，怎么解决？

**Comment by ryhnatwoods** [comment]
也遇到同样无法link@ant-design/icons-react-native

**Comment by awmleer** [comment]
rn 相关问题请移步：https://github.com/ant-design/ant-design-mobile-rn/issues
