### ISSUE TITLE
tabs组件官方demo“固定高度”没有展示content内容

### ISSUE THREAD

**Issue by zldream1106** [ant-design/ant-design-mobile#3393]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/tabs-cn/#components-tabs-demo-fixedheight](https://mobile.ant.design/components/tabs-cn/#components-tabs-demo-fixedheight)

### Steps to reproduce
查看“固定高度”类型，右边的模拟器内tab的content内容没有展示

### What is expected?
查看“固定高度”类型，右边的模拟器内tab的content内容正常展示“Content of second tab”等内容

### What is actually happening?
模拟器内tab的content内容没有展示

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 在线demo版本，与业务无关 |
| System | macOS Mojave 10.14 |
| Browser | 版本 76.0.3809.132（正式版本） （64 位） |

**Comment by zwj7181** [comment]
在content标签添加key值
```
<Tabs
      tabs={tabs}
      initialPage={'t1'}
      swipeable={false}
      renderTabBar={renderTabBar}
      tabBarInactiveTextColor="#787878"
      tabBarUnderlineStyle={{ width: '25%', height: '5px', marginLeft: '12.5%', backgroundColor: '#FFCC4A' }}
 >
          <div key="t1" style={{ backgroundColor: '#fcf', width: '100vw', height: '200vh' }}>1221212</div>
          <div key="t2" style={{ backgroundColor: '#f00', width: '100vw', height: '200vh' }}>1221212</div>
</Tabs>
```

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
