### ISSUE TITLE
pullToRefresh 在小米手机上上拉触发不了加载

### ISSUE THREAD

**Issue by RQAccount** [ant-design/ant-design-mobile#3394]

**Comment by xcodebin** [comment]
the same

**Comment by xcodebin** [comment]
没人看，没人解决吗？

**Comment by shotarich** [comment]
我前段时间也遇到了,在PullToRefresh的children里面包裹自己返回的div死活拉不动,无奈之下使用了List模块的List.Item却奇迹般的可以拉动. 用了这个ant-mobile, 感觉好多bug

**Comment by liangzhuang327** [comment]
@shotarich @xcodebin https://github.com/ant-design/ant-design-mobile/issues/3521

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
