### ISSUE TITLE
ListView 下拉刷新中如何使用手风琴

### ISSUE THREAD

**Issue by yangjunjie520** [ant-design/ant-design-mobile#3395]
在ListView 中的  renderRow  循环中 添加< Accordion ><Accordion.Panel>< Accordion /><Accordion.Panel/>  他就变成了 单一的一个组件 无法设置 手风琴 效果
而写成 < Accordion ><ListView />< Accordion />  组件又会报错  请问有什么其他方法没

**Comment by wwdlook** [comment]
> 在ListView 中的 renderRow 循环中 添加< Accordion ><Accordion.Panel>< Accordion /><Accordion.Panel/> 他就变成了 单一的一个组件 无法设置 手风琴 效果
> 而写成 < Accordion >< Accordion /> 组件又会报错 请问有什么其他方法没

可以在“renderSectionWrapper”这个方法内定义用来包装的元素，比如< Accordion />。我遇到的问题是：accordian无法点击。。。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
