### ISSUE TITLE
Calendar 下拉加载月，拉不动

### ISSUE THREAD

**Issue by lhbxs** [ant-design/ant-design-mobile#3396]
在iso 机器上，安卓尚未测试。
当body因内容多出现滚动条的时，在打开calendar。来回上滑、下滑。发现下滑很难回到原为甚至滑不动了。注意，来回滑的时候一定要松手，向上滑，然后手离开，在向下滑。

**Comment by Zejia** [comment]
请问您这个问题解决了吗 两年了

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by GOWxx** [comment]
> v2 已停止维护了，可以考虑升级一下

请问v5里有Calendar组件吗，我阅读了v5的文档，搜索了v5的代码，没有 日历Calendar组件 相关的信息

**Comment by awmleer** [comment]
@GOWxx 噢sorry目前v5还没做日历组件，不过已经准备开始开发了

**Comment by GOWxx** [comment]
> @GOWxx 噢sorry目前v5还没做日历组件，不过已经准备开始开发了

感谢如此迅速的回复，请问大概会在哪个时间段内推出呢？

**Comment by awmleer** [comment]
@GOWxx 快的话 11 月底之前，慢的话 12 月中上旬

**Comment by GOWxx** [comment]
> @GOWxx 快的话 11 月底之前，慢的话 12 月中上旬

收到回复，那我先略过这个地方，希望可以赶上用antd-mobile5的组件，祝开发顺利
