### ISSUE TITLE
grid组件可不可以一栏3个而不是固定4个

### ISSUE THREAD

**Issue by lianpen** [ant-design/ant-design-mobile#34]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

**Comment by dyf2015** [comment]
给我个电话

发自我的 iPhone

在 2016年8月3日，19:41，lianpen <notifications@github.com<mailto:notifications@github.com>> 写道：

本地环境

  *   antd-mobile 版本：
  *   操作系统及其版本：
  *   浏览器及其版本：

你做了什么？
你期待的结果是：
实际上的结果：
可重现的在线演示

―

**Comment by pingan1927** [comment]
可以考虑适配下

**Comment by warmhug** [comment]
一栏多少个，多少栏，都应该要可以配置的

**Comment by lianpen** [comment]
Uncaught Invariant Violation: Main.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

**Comment by silentcloud** [comment]
这个目前什么进度 @pingan1927

**Comment by pingan1927** [comment]
这个 @linfaxin 来跟进。

**Comment by linfaxin** [comment]
已支持。
