### ISSUE TITLE
rn0.60以上切换tab报错

### ISSUE THREAD

**Issue by SYshengyang** [ant-design/ant-design-mobile#3403]

**Comment by SYshengyang** [comment]
UIManager.dispatchViewManagerCommand was called with 2 arguments but expects 3 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

**Comment by likezero** [comment]
please report bug  at https://github.com/ant-design/ant-design-mobile-rn
