### ISSUE TITLE
组件代码demo能弄成通俗易懂复制后能打开看到效果，listView看的都快疯了

### ISSUE THREAD

**Issue by xiesantao** [ant-design/ant-design-mobile#3408]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望能对新手友好些，文档太难读懂了

### What does the proposed API look like?
#希望文档通俗易懂些

**Comment by pakyo-pan** [comment]
牛逼

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
