### ISSUE TITLE
关于antd mobile 0.8高清方案的疑问

### ISSUE THREAD

**Issue by ctq123** [ant-design/ant-design-mobile#341]
#### 本地环境

- antd-mobile 版本：^0.8.0
- 操作系统及其版本：android/4.4
- 浏览器及其版本：QQ浏览器X5内核（微信），chrome 45.0.2454.101

#### 你做了什么？

 我之前是引用antd-design框架来做移动端的（那时antd-mobile还没有出来），现在将antd-design框架改为antd-mobile框架，然而问题就来了：0.8以上的版本采用了高清方案（web demo 采用 rem 和页面 scale 缩放方案，达到页面高清效果），我原来的自定义字体及高度宽度都缩小了 ，布局自然就混乱掉了………

#### 你期待的结果是：

 我期待的结果其实就是能顺利的移植系统，像官网一样显示；
同时我对此有几个疑问，希望大神能帮忙解答一下：
1、我想知道采用高清方案的具体原因是什么？（解决兼容性？还是？希望能给个不是高清效果的确切例子）
2、若想采用自定义的px像素值，该如何处理？（由于UI设计师的需求，比如他给字体就是14px，间隔距离2px，那我们的自定义像素值与你们显示的像素值又如何对应上去？放大原来的2倍还是不行）

#### 实际上的结果：

 采用rem打包及scale缩放导致字体和布局混乱，不能顺利地移植系统

**Comment by pingan1927** [comment]
请参考这个wiki做一次性处理下

https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8%E9%AB%98%E6%B8%85%E6%96%B9%E6%A1%88%E5%AE%9E%E8%B7%B5

**Comment by pingan1927** [comment]
* 高清方案的实现很多，这个选择经过很多权衡，相比下来，整个页面缩放兼组件样式兼容性会少很多。
* code时都是写px，构建时由工具自动转换为rem。

具体请参考wiki

**Comment by ctq123** [comment]
thanks
