### ISSUE TITLE
TabBar中的一级页面，把页面滚动到最底部，再向上滑动时，页面就会卡住！

### ISSUE THREAD

**Issue by HHuiHao** [ant-design/ant-design-mobile#3410]
卡死大概3秒左右，才能点击
![image](https://user-images.githubusercontent.com/8486113/65811088-db07e980-e1e5-11e9-91b7-9cd3a38db95d.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
