### ISSUE TITLE
Modal里写CheckboxItem，CheckboxItem就只能点击复选框，不能点选文字部分

### ISSUE THREAD

**Issue by YUD1112** [ant-design/ant-design-mobile#3411]
如以下代码所示，在Modal中套写CheckboxItem,只有复选按钮可点击；文字区域不可点击
```
<Modal
          visible={this.state.modal1}
          transparent
          maskClosable={false}
          onClose={this.onClose('modal1')}
          title="Title"
          footer={[{ text: 'Ok', onPress: () => { console.log('ok'); this.onClose('modal1')(); } }]}
          wrapProps={{ onTouchStart: this.onWrapTouchStart }}
          afterClose={() => { alert('afterClose'); }}
>
          <div style={{ height: 100, overflow: 'scroll' }}>
                 {data.map(i => (
                  <CheckboxItem key={i} onChange={() => this.onChange(i)}>
                         {i.label}
                  </CheckboxItem>
                  ))}
                 <CheckboxItem key="disabled" data-seed="logId" disabled defaultChecked multipleLine>
                        Undergraduate<List.Item.Brief>Auxiliary text</List.Item.Brief>
                  </CheckboxItem>
          </div>
</Modal>
```

**Comment by DAHU123** [comment]
我这边也是遇到了这个问题，出现这个问题的业务场景不是在弹框里面，在普通的组件中去引用CheckboxItem，也是只能点击复选框，不能点选文字部分使这个复选框选中

**Comment by DAHU123** [comment]
我们项目应用的antd-mobile的版本号是@2.2.6

**Comment by DAHU123** [comment]
我这边给出的解决方案是：
`<CheckboxItem
          onChange={this.handleCheckedAll}
          checked={children.length === len}
          disabled={children.length === disLen}
          id="checkBoxItem"
        >
          <label for="checkAll">{i18n.get('全选')}</label>
</CheckboxItem>`
在组件的componentDidMount阶段加上这段代码：
`    const dom = document.getElementById('checkBoxItem')
    // @ts-ignore
    dom && dom.childNodes[0].childNodes[0].childNodes[0].childNodes[0].setAttribute('id', 'checkAll')
`
整体的原理是为checkbox的表单加上一个label，这样子的话，就能实现点击全选两个字，也能使checkbox选中。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
