### ISSUE TITLE
安卓的webview的元素scrollTop存在小数点导致PullToRefresh组件无效

### ISSUE THREAD

**Issue by ayahua** [ant-design/ant-design-mobile#3412]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
就是根据组件文档很正常的使用情况下。一开始发现在h5和ios内正常，但是安卓的app内无效，然后查看了rmc-pull-to-refresh的代码之后，发现onTouchMove时有一个isEdge的判断，里面在上拉刷新的情况下，有一个判断：
```js
if (direction === UP) {
      return ele.scrollHeight - ele.scrollTop === ele.clientHeight;
}
```
然后根据我页面输出的结果，scrollTop一直都是有多位小数的，导致这个判断一直都无法通过

### What is expected?
能在安卓app内正常使用

### What is actually happening?
但是在安卓的webview内无效，滑动到底部的时候，也没有继续拖动的效果。

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.9.0 |
| System | MacOS 10.14 |
| Browser | no |

---
不知道是否是安卓的webview设置问题

**Comment by ayahua** [comment]
下面图片的scrollData后面的三个数据，从第一个开始分别是scrollHeight、scrollTop、clientHeight
![image](https://user-images.githubusercontent.com/36917157/65847995-98c1e200-e376-11e9-9bbe-4b9460cb15ea.png)

**Comment by miaoyuxinbaby** [comment]
the same problem

**Comment by liangzhuang327** [comment]
@ayahua @miaoyuxinbaby 可以看看这个能否解决
https://github.com/ant-design/ant-design-mobile/issues/3521

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
