### ISSUE TITLE
Tabs 设置page 为string值无效，貌似只能用index才能正常

### ISSUE THREAD

**Issue by zh1047842950** [ant-design/ant-design-mobile#3414]
![908D3817-1198-4724-B09C-F9656FB00519](https://user-images.githubusercontent.com/19948238/65862742-7abda700-e3a1-11e9-820a-6912eab334d7.jpeg)

**Comment by YellowPure** [comment]
i have the same issue,please fix this bug. thanks~

**Comment by GuiJu** [comment]
遇到同样的问题，而且antd-mobile官网里使用string为索引的例子也是异常显示的

**Comment by LNlinaa** [comment]
准确来说是number类型才行

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
