### ISSUE TITLE
页面加入PullToRefresh组件后滑动不畅，上滑滑不动

### ISSUE THREAD

**Issue by xiesantao** [ant-design/ant-design-mobile#3416]

**Comment by xiesantao** [comment]
页面加入PullToRefresh组件后滑动不畅，上滑滑不动

**Comment by lwj6666456** [comment]
我也碰到了，android，ios好像没问题

**Comment by chen504554911** [comment]
请问下楼主是怎么解决的呢

**Comment by Lemonreds** [comment]
给 PullToRefresh 组件加一个固定的height，比如 document.clientHeight

**Comment by Z-HNAN** [comment]
PullToRefresh 组件添加一个css
```css
height: calc(100vh - 50px);
overflow: auto;
```
我是这么解决的

**Comment by ITZengWei** [comment]
为什么 我的平板上 上拉就能滑动 而有的手机 上拉是 划不动的 纠结了 2 天了

**Comment by liangzhuang327** [comment]
@xiesantao @lwj6666456  @chen504554911  可以看下这个能否解决你们的场景
https://github.com/ant-design/ant-design-mobile/issues/3521

**Comment by yuanzhiheng1993** [comment]
怎么解决的啊

**Comment by Tammy-world** [comment]
PullToRefresh 组件添加一个css

height: calc(100vh - 50px);
overflow: auto;
-------------------------------
加了样式也没有生效，有解决的吗
