### ISSUE TITLE
Multi select menu buttons cannot be customized

### ISSUE THREAD

**Issue by ChrisCardoz** [ant-design/ant-design-mobile#3417]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There seems to be no documentation for customizing the buttons in the Menu object when multiSelect is enabled. The current defaults are not in english and this is a huge deal for my project because I've been working using antd and I can't move forward if there is no way to change the language on one of the components. 
https://mobile.ant.design/components/menu/#components-menu-demo-multiSelect

### What does the proposed API look like?
Similar to some of your other components, you could add the fields okText={"Okay"} and cancelText={"Cancel"} if you wanted to change the button text.

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
