### ISSUE TITLE
Drawer component compatibility with preact@10.0.0

### ISSUE THREAD

**Issue by kumarvi** [ant-design/ant-design-mobile#3418]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
- Use preact@next (10.0.0-rc.3)
- Use antd-mobile Drawer component

### What is expected?
Component renders

### What is actually happening?
Component fails to load due to the use of string refs in [m-drawer repo](https://github.com/react-component/m-drawer/blob/master/src/Drawer.jsx#L425)

```
TypeError: Cannot read property 'sidebar' of undefined
    at Drawer._this.saveSidebarSize (Drawer.js:136)
    at Drawer.componentDidMount (Drawer.js:282)
    at j (preact.module.js:1)
    at I (preact.module.js:1)
    at Object._ (compat.module.js:1)
```

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| react | latest |
| preact| latest|
| System | Windows |
| Browser | Chrome/FF latest |

---
I've created a [PR](https://github.com/react-component/m-drawer/pull/38) for this in the m-drawer repo

**Comment by kumarvi** [comment]
@likezero can you review this? thanks.

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
