### ISSUE TITLE
Stepper 长按按钮数字不断变化，仅在开始的时候调用一次 onChange

### ISSUE THREAD

**Issue by leeqj** [ant-design/ant-design-mobile#342]
#### 本地环境

- antd-mobile 版本：0.9.0
- 操作系统及其版本：mac os
- 浏览器及其版本：chrome

#### 你做了什么？
单击 和 长按  Stepper 的 ＋ － 按钮 
#### 你期待的结果是：

长按 松开后调用 其 onChange 方法 

#### 实际上的结果：
单击可以正常调用 onChange 回调方法  ， 但长按的时候数字在不断变化，仅开始调用了一次onChange， 数字改变到最大或最小后，均没有再调用 onChange 
如 ： 现在Stepper数字是9 长按－按钮，onChange执行一次值为8的回调后， 直到数字变为0 松开 都不再调用 onChange方法

**Comment by warmhug** [comment]
组件应该要在长按结束后，再调用 onChange 吧？

**Comment by silentcloud** [comment]
@leeqj 参看这个 demo

http://react-component.github.io/input-number/examples/decimal.html
