### ISSUE TITLE
[Popover] Popover mask 事件穿透，没有阻止事件冒泡

### ISSUE THREAD

**Issue by swdenglian** [ant-design/ant-design-mobile#3424]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/white-tree-5n702](https://codesandbox.io/s/white-tree-5n702)

### Steps to reproduce
https://github.com/react-component/m-trigger/blob/b5852d9365a855cc69700f0cc668f085adbd42b9/src/Trigger.tsx#L102

### What is expected?
点击 mask 只关闭 Popover, 阻止事件冒泡

### What is actually happening?
事件穿透，底下的组件也触发了该点击事件

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | react |
| System | ios |
| Browser | ios 微信浏览器 |

---
导致该问题的代码段
https://github.com/react-component/m-trigger/blob/b5852d9365a855cc69700f0cc668f085adbd42b9/src/Trigger.tsx#L102

希望该行代码为
```jsx

...
if (!contains(root, target) && !contains(popupNode, target)) {
      this.close();
      event.preventDefault();
}
....
```
该问题影响到 3个库  antd-mobile ,  m-tooltip , m-trigger

**Comment by swdenglian** [comment]
@ziluo 是一个库一个库pr吗？

**Comment by wswax** [comment]
是还没有解决这个问题吗？

**Comment by RicoLiu** [comment]
> 是还没有解决这个问题吗？

应该还没有吧

**Comment by RicoLiu** [comment]
这个可以自己处理一下，阻止 mask 点击事件冒泡

**Comment by FairyMeili** [comment]
+1

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
