### ISSUE TITLE
都9102年了，还不支持react 16 吗？Picker 组件消失没有动画，react 兼容问题 还能解决吗

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design-mobile#3426]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/picker-cn/#components-picker-demo-basic](https://mobile.ant.design/components/picker-cn/#components-picker-demo-basic)

### Steps to reproduce
点击消失按钮

### What is expected?
消失有动画。。。

### What is actually happening?
消失没有动画。。。

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.9.0 |
| System | mac |
| Browser | chrome |

**Comment by awmleer** [comment]
v5 都支持了，升级一下吧
