### ISSUE TITLE
Z-Order of List Split Line is too Height, in Mobile Devices.

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design-mobile#3429]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://2g8rz.csb.app](https://2g8rz.csb.app)

### Steps to reproduce
1. Use mobile device open page.
2. Just see it...

### What is expected?
Not show the split line, when something cover List.

### What is actually happening?
split line appear even something cover List.

| Environment | Info |
|---|---|
| antd | 2.3.1 |
| React | 16.9.0 |
| System | Mac OS X 10_14_6 |
| Browser | Chrome/77.0.3865.120 |

---
This is to be compatible with the problem that the device has a pixel ratio of 2.

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
