### ISSUE TITLE
TabBar引入图标问题

### ISSUE THREAD

**Issue by guangming21** [ant-design/ant-design-mobile#343]
#### 本地环境 

- antd-mobile 版本：0.8.6
- 操作系统及其版本：win10
- 浏览器及其版本：chrome

#### 你做了什么？

引入TabBar icon 请求不到本地图片
 <TabBar.Item
            title="视频库"
            key="视频库"
            icon={require('./icons/video.png')}
            selectedIcon={require('./icons/video_blue.png')}
  ...

#### 你期待的结果是：

 可以更换本地图片

#### 实际上的结果：

 请求不到本地图片，显示一个方框跟title第一个字

**Comment by silentcloud** [comment]
@guangming21  Tabbar 图片部分本质上是使用的 <img  src="" /> 方式的

**Comment by guangming21** [comment]
@silentcloud 你试一下icon={require('./icons/xxxxx.png')}这样可以去到图片吗

**Comment by silentcloud** [comment]
恩这里是有点问题，目前没做直接 require 的方式，你可以先这样写：
```
icon={{ uri: require('./icons/xxxxx.png') }}
```

下一个版本将支持直接写 require

**Comment by guangming21** [comment]
@silentcloud 哦哦，原来是这样，谢谢啊

**Comment by silentcloud** [comment]
a4cff9fdb14c68ca86d8dabbe42b1b7fdc51346e
