### ISSUE TITLE
Popover Component TS declaration missing attribute

### ISSUE THREAD

**Issue by woshilaoge** [ant-design/ant-design-mobile#3430]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/popover-cn/](https://mobile.ant.design/components/popover-cn/)

### Steps to reproduce
Using examples in TS environment

### What is expected?
No error is reported in TS type detection

### What is actually happening?
TS type detection and measurement error

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome 75 |

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
