### ISSUE TITLE
[PullToRefresh] PullToRefresh 快速连续下拉刷新会产生bug

### ISSUE THREAD

**Issue by swdenglian** [ant-design/ant-design-mobile#3431]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-nash-u5pr6)

### Steps to reproduce
迅速连续下拉（间隔时间1s内，且loading时间在 1s 内），第二次下拉刷新会迅速回弹一段距离，或者（华为p30）在finish的时候会闪动。

### What is expected?
无上述现象

### What is actually happening?
迅速连续下拉（间隔时间1s内，且loading时间在 1s 内），第二次下拉刷新会迅速回弹一段距离，或者（华为p30）在finish的时候会闪动。

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | react |
| System | all |
| Browser | wechat |

---
在m-pull-to-refresh中
onTouchStart 以及 triggerPullToRefresh 中调用finish的时候需要清除定时器。
具体代码如下：
onTouchStart：
https://github.com/react-component/m-pull-to-refresh/blob/e5ee243ae8cc7cd9e24dfb04bc4a22fec68ec9e0/src/PullToRefresh.tsx#L141
```jsx
 onTouchStart = (_ele: any, e: any) => {
  // ------这里有变化
   if(this._timer){
       clearTimeout(this._timer);
       this2.reset();
   }
  //------

    this._ScreenY = this._startScreenY = e.touches[0].screenY;
    // 一开始 refreshing 为 true 时 this._lastScreenY 有值
    this._lastScreenY = this._lastScreenY || 0;
  }
```

triggerPullToRefresh:
https://github.com/react-component/m-pull-to-refresh/blob/e5ee243ae8cc7cd9e24dfb04bc4a22fec68ec9e0/src/PullToRefresh.tsx#L95
```jsx
if (!this.state.dragOnEdge && this._isMounted) {
      if (this.props.refreshing) {
        if (this.props.direction === UP) {
          this._lastScreenY = - this.props.distanceToRefresh - 1;
        }
        if (this.props.direction === DOWN) {
          this._lastScreenY = this.props.distanceToRefresh   1;
        }
        // change dom need after setState
        this.setState({ currSt: 'release' }, () => this.setContentStyle(this._lastScreenY));
      } else {
         // ------这里有变化
           if(this._timer){
              clearTimeout(this._timer);
          }
         //------
         this.setState({ currSt: 'finish' }, () => this.reset());
      }
    }
```

**Comment by renrenguiwei** [comment]
设置滑动区域的 z-index 层级，这个很重要；不然会出现手势滑动的区域是父层div的误操作

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
