### ISSUE TITLE
[tabs][需求] 希望将 rc-gesture 的 config.js 中的 SWIPE 开放出来在组件外部配置

### ISSUE THREAD

**Issue by swdenglian** [ant-design/ant-design-mobile#3432]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
10 的触发距离太小了, 和 tabs   listView 一起使用将会导致非常容易触发侧滑

### What does the proposed API look like?
tabs 添加api 
```jsx
onSwipeThresholdConfig = { 
    distance: number,
    velocity: number
    absAngle: number, // 角度斜率绝对值
}
```

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
