### ISSUE TITLE
Carousel not  transition animate when set ‘selectedIndex’ by manual.

### ISSUE THREAD

**Issue by CareyToboo** [ant-design/ant-design-mobile#3434]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I hope add a prop "animated". Whether to use animated transitions when setting 'selectIndex'.

### What does the proposed API look like?
```
< Carousel
    selectedIndex={stateIndex}
    animated={true}  //  Whether to use animated transitions 
>
...
</Carousel>
```

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
