### ISSUE TITLE
ReactNative组件页面打不开

### ISSUE THREAD

**Issue by xgAnd** [ant-design/ant-design-mobile#3437]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/](https://rn.mobile.ant.design/)

### Steps to reproduce
https://rn.mobile.ant.design/ 切换到ReactNative组件页面

### What is expected?
显示界面内容

### What is actually happening?
此网站无法提供安全连接rn.mobile.ant.design 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | web页面打不开 |
| System | mac0s 10.14.6 |
| Browser | 版本 77.0.3865.120（正式版本） （64 位） |

**Comment by xgAnd** [comment]
web组件的页面可以 native的打不开  
此网站无法提供安全连接rn.mobile.ant.design 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
协议不受支持
客户端和服务器不支持一般 SSL 协议版本或加密套件。

**Comment by xgAnd** [comment]
![9DFD2679-994D-43A4-B8A4-66788BD850B6](https://user-images.githubusercontent.com/27660602/67615520-1e16a600-f800-11e9-8b56-6f85b2650fc0.png)

**Comment by xiaohuoni** [comment]
应该恢复了
![image](https://user-images.githubusercontent.com/11746742/83334861-f4fd4d00-a2db-11ea-9a20-9e2379df33f5.png)

**Comment by smithyj** [comment]
@xiaohuoni https://08x.mobile.ant.design/  https://07x.mobile.ant.design/ https://09x.mobile.ant.design/ 这几个页面都一样 打不开 报SSL协议错误

**Comment by awmleer** [comment]
rn 相关问题请移步：https://github.com/ant-design/ant-design-mobile-rn/issues
