### ISSUE TITLE
Document link typo on docs/react/upgrade-notes.en-US.md

### ISSUE THREAD

**Issue by dididy** [ant-design/ant-design-mobile#3438]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://tva1.sinaimg.cn/large/006y8mN6gy1g8bw57ylv2j31ca0ca0un.jpg](https://tva1.sinaimg.cn/large/006y8mN6gy1g8bw57ylv2j31ca0ca0un.jpg)
I already fixed it

### Steps to reproduce
redirect to chinese from english document link

### What is expected?
redirect to chinese from english document link

### What is actually happening?
redirect to chinese from english document link

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | N/A |
| System | N/A |
| Browser | N/A |

**Comment by awmleer** [comment]
v2 is no longer maintained.
