### ISSUE TITLE
2016-10-09升级antd-mobile为什么还是0.8.7？

### ISSUE THREAD

**Issue by zhwb36** [ant-design/ant-design-mobile#344]
执行升级操作：
npm update antd-mobile -save
升级后提示版本号是：
-- antd-mobile@0.8.7

怎么升级到0.9？

**Comment by warmhug** [comment]
`npm i antd-mobile@0.9.0 --save`

你 package.json 里写的是 0.8 ，怎么会 update 到 0.9 呢。。
