### ISSUE TITLE
ImagePicker在安卓中无法单选的问题

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-mobile#3440]
在ios中将multiple设置为false后，调用系统相册能单选(无法多选)。但在安卓中可以多选，请问如何在安卓中调成只能单选。

一、代码
![image](https://user-images.githubusercontent.com/20454290/67648666-54bffe00-f971-11e9-833a-bed3998cc95e.png)

![image](https://user-images.githubusercontent.com/20454290/67648683-60132980-f971-11e9-810e-dc93f82487d6.png)

二、安卓表现：还能多选
![image](https://user-images.githubusercontent.com/20454290/67648828-c435ed80-f971-11e9-9ffa-02d31f924d20.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
