### ISSUE TITLE
Modal 里面的 InputItem的type 为 money 时，看不到虚拟键盘，但可以点击

### ISSUE THREAD

**Issue by cjm61177** [ant-design/ant-design-mobile#3443]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/](https://codepen.io/)

### Steps to reproduce
import React, {PureComponent} from 'react';
import { List, InputItem,Modal } from 'antd-mobile';

const isIPhone = new RegExp('\\biPhone\\b|\\biPod\\b', 'i').test(window.navigator.userAgent);
let moneyKeyboardWrapProps;
if (isIPhone) {
  moneyKeyboardWrapProps = {
    onTouchStart: e => e.preventDefault(),
  };
}

import styles from './test.less';

class Test extends PureComponent {
  constructor(props) {
    super(props);
    this.state = {
    }
  }

  componentDidMount() {

    this.clientHeight = window.document.body.clientHeight;
  }

  render() {
    return (
      <Modal
        visible
        closable
        animationType="slide-up"

        wrapProps={{onTouchStart: this.onWrapTouchStart}}
      >
        <div style={{height:'8rem'}}>
          <List renderHeader={()=>(<div style={{fontSize:'0.32rem'}}>批量设置佣金</div>)}>
            <InputItem
              type="number"
              placeholder="请输入分佣比例"
              onChange={this.handleChangeCP}
              moneyKeyboardWrapProps={moneyKeyboardWrapProps}
              extra="%"
            >百分比
            </InputItem>
            <InputItem
              type="money"
              placeholder="请输入分佣比例"
              onChange={this.handleChangeCP}
              moneyKeyboardWrapProps={moneyKeyboardWrapProps}
              extra="%"
            >百分比
            </InputItem>
          </List>
        </div>
      </Modal>

    );
  }
}

export default Test;

### What is expected?
能正常显示虚拟键盘

### What is actually happening?
看不到虚拟键盘，但可以点击

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.5.1 |
| System | iOS |
| Browser | Safari  iOS一系列机型 |

**Comment by BZSZ** [comment]
遇见了同样的问题。键盘被popup弹窗遮挡了，键盘的z-index: 10000, popup的z-index: 999

**Comment by BryanHoo** [comment]
I had the same problem. Is there a solution?

**Comment by sanshuiwang** [comment]
ios 系统版本是多少？

**Comment by sanshuiwang** [comment]
我这边一切正常啊！

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by zhiyongsun** [comment]
真的是天坑。
.am-modal-wrap 下的 transform: translateZ(1px)覆盖下为transform: translateZ(0)。
不知道这里本意是不是为了开启3d加速。为什么要有1px？
原理就是：transform: translateZ(1px) 会创建比z-index更高层级的stacking context（堆叠上下文），所以z-index会失效。
![Screenshot 2024-04-22 at 19 23 51](https://github.com/ant-design/ant-design-mobile/assets/14730091/7e26d762-084a-4a25-8fd4-2e830d3a1390)
