### ISSUE TITLE
把ActionSheet 写成一个公用的方法，android物理返回键隐藏不了

### ISSUE THREAD

**Issue by a728384698** [ant-design/ant-design-mobile#3445]
![屏幕快照 2019-11-01 下午5 20 21](https://user-images.githubusercontent.com/7380874/68014972-edd17a80-fccb-11e9-96ad-dc55f98a8490.png)
前面——ref 还是无效
![image](https://user-images.githubusercontent.com/7380874/68015372-fd04f800-fccc-11e9-83b5-32556e537c35.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
