### ISSUE TITLE
SearchBar 组件在华为p30手机上获取焦点后input框消失

### ISSUE THREAD

**Issue by zhaijinsong** [ant-design/ant-design-mobile#3446]

**Comment by zhaijinsong** [comment]
![111572938919_ pic](https://user-images.githubusercontent.com/35650904/68187195-fa621580-ffe0-11e9-9a2e-f829a3d3478a.jpg)
上图是原页面
![101572938829_ pic](https://user-images.githubusercontent.com/35650904/68187204-051caa80-ffe1-11e9-856f-8ac29178a17c.jpg)
上图是搜索框获取焦点之后的状态

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
