### ISSUE TITLE
使用Grid创建网格  生成4*4的网格用手机qq点进去少一条分割线

### ISSUE THREAD

**Issue by limj0825** [ant-design/ant-design-mobile#3449]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/limj0825/Evans2048](https://github.com/limj0825/Evans2048)

### Steps to reproduce
npm install
npm start
npm build后放到服务器上
使用手机qq点进去  就能看到第三行和第四行的格子少一条分割线

### What is expected?
完整的分割线

### What is actually happening?
少一条

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.11.0 |
| System | mac 10.14.6  phone miui 11  qq  8.1.8.4260   |
| Browser | qq 8.1.8.4260 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
