### ISSUE TITLE
0.9.x changelog

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#345]

**Comment by silentcloud** [comment]
- 修复 tabbar `icon`、`selectedIcon` 直接 require 图片不显示问题；

**Comment by warmhug** [comment]
### 0.9.1
- 修复 tabbar `icon`、`selectedIcon` 直接 require 图片不显示问题
- 修复`InputItem` pattern bug https://github.com/ant-design/ant-design-mobile/commit/e2b1d4336f6a19ee80667c3383c12861448937e0
- 修复`Button` css 变量未引用问题 #339 
- 修复`Picker`样式 https://github.com/ant-design/ant-design-mobile/commit/e7cf959fb6978b5b6fa37294007b8f214477f625 , 新增`onPickerChange`api https://github.com/ant-design/ant-design-mobile/commit/69e142cddc99b0d99ae23f3435e801ddd6ab014d
- 更新 rn list-view demo https://github.com/ant-design/ant-design-mobile/commit/c0b4ae4797a9fac3a00c8272becc2709c2846039

**Comment by silentcloud** [comment]
### 0.9.2 

- Tag 增加 closable 支持 #348 
-  package 中 dist 目录 css 样式以 rem 为主要单位，方便直接引用样式而不会放大

**Comment by offbye** [comment]
> package 中 dist 目录 css 样式以 rem 为主要单位，方便直接引用样式而不会放大

这个具体怎么用啊？ 我项目就是用rem的，0.9.2是不是不需要用pxtorem 了？？

**Comment by silentcloud** [comment]
@offbye 不用 pxtorem 的话，直接引用 dist 下面的 css

**Comment by warmhug** [comment]
### 0.9.3 (wip)

- 部分组件支持`data-api` https://github.com/ant-design/ant-design-mobile/commit/8972f980d0dddee30fd61ebaa0f75fc07a7a36b3

**Comment by warmhug** [comment]
### 0.9.4 (wip)
- Button 组件新增`touchFeedback(web)` API, 修复 #396

**Comment by linfaxin** [comment]
修复 rn-checkbox, rn-radio 支持受控组件 https://github.com/ant-design/ant-design-mobile/commit/6f47c36b8e3729674dc63eaaa39cfac05b125f3c

**Comment by warmhug** [comment]
### 0.9.5 (wip)
- 修复点击反馈属性 warning, #416

**Comment by warmhug** [comment]
### 0.9.6
- 修复 Stepper 组件弹出键盘和点击反馈问题 https://github.com/ant-design/ant-design-mobile/commit/94f4e54ab6bb9800fc987cc57d806b5921b11c9d
- 修复 Tabs选项卡高度不一致问题 https://github.com/ant-design/ant-design-mobile/commit/f4bb4bc86e2a8400fb74a69e9f0a2359ce512b0b
- 修复 InputItem, TextareaItem value 不接受 undefined 问题 https://github.com/ant-design/ant-design-mobile/commit/114fb1ed871acd94433129fda95a30649420aa2a
- 修复 android textInput underlineColorAndroid https://github.com/ant-design/ant-design-mobile/commit/8095c924fda68f1b38acae1af09822daae95c3d2
- 优化  Accordion, Checkbox, Popup, Badge, InputItem, TextareaItem, ListView 等组件演示文档和部分核心实现。

**Comment by motorguo** [comment]
> package` 中 dist 目录 css 样式以 rem 为主要单位，方便直接引用样式而不会放大。 

 @silentcloud

```
"antd-mobile": "^0.9.6",
```
我不是使用官方推荐的脚手架，我也在 `webpack.config` 中添加了相应配置，也添加了高清方案脚本。
```
const pxtorem = require('postcss-pxtorem');
postcss: [
        pxtorem({
            rootValue: 100,
            propWhiteList: [],
        })
    ],
```
然而呈现出来的结果很不理想：
**组件的字体单位还是 `px`，自己添加的样式转为了 `em`.**
请问是否 `0.9.x` 都已全面支持 `rem` , 在 wiki 那个高清方案基础上还需要添加些什么，希望添加相应说明文档。
还是需要使用官方的脚手架的基础上 ，加上那个方案的所说的配置才能使用。
非常感谢

**Comment by motorguo** [comment]
今天弄了 demo ，发现 `0.9.6` 的直接 `defaultActiveKey="0"` 显示都没问题，
之前 `0.9.5` 得像下面这样写才有效：

```
<Accordion defaultActiveKey=".$0" accordion>
    <Accordion.Panel key='0' header="标题一">1</Accordion.Panel>
    <Accordion.Panel key='1' header="标题二">2</Accordion.Panel>
</Accordion>
```
升级到 `0.9.6` 
通过 `react` 插件看，还是这样：` key=".$.$.0"`

**Comment by warmhug** [comment]
### 0.9.7 (wip)
- 修复 ListView 遗漏 ref 设置问题 https://github.com/ant-design/ant-design-mobile/commit/2e32956d405880f2fdca3cc88cd7c3b1b7784b7f

**Comment by warmhug** [comment]
### 0.9.9
- 改进 Popup 样式 #525 , 默认禁止掉 popup 遮罩层的 onTouchStart 事件、优化在拖动时的体验
- 修复 Radio 同 Accordion 一起使用样式冲突问题 #542 , 优化 List.Body 样式
- 修复 Checkbox、Radio、Tag、InputItem 等组件样式细节问题；优化 Flex 组件 demo 
- 增加 React基础、相关工具、应用架构文档指南；并优化“安装&使用”文档、使之更紧凑清晰

**Comment by warmhug** [comment]
### 0.9.10
- 重构 SearchBar ，改为模拟的 placeholder 实现，并将其默认居中对齐
- 修复 Popup 组件点击遮罩层不会自动关闭 #555 #558
- 更正 RefreshControl 文档；修复部分组件 demo 在 pc 和 mobile 上展示不一致问题
- 修复 Toast 在 Modal 中使用被覆盖问题 #547
- 优化 Button、List 代码的 rn 实现；修正部分 demo 细节问题

**Comment by warmhug** [comment]
### 0.9.11
- 修复 List 底部边线重叠显示问题、重构 List 点击反馈的实现方法；同步修复 ListView.IndexedList 边线重叠问题 
- 修复 Checkbox 勾选箭头偏移问题 #581
- 修复 Steps 组件内部逻辑、改进部分样式设置
- 修复 SearchBar 动画表现不准确问题
- 改进[上手和使用文档](https://mobile.ant.design/docs/react/introduce#使用)写法
- 优化 Pagination、RefreshControl、Radio、Drawer、Popover、Result、NoticeBar 等组件实现和相应 demo

**Comment by warmhug** [comment]
### 0.9.12
- 修复 SearchBar 的 PropsType 文件里对 react-native 多余引用的问题
- 修复 Checkbox、Radio 在某些设备上点击 label 不会选中的兼容性问题
- 修复 InputItem 最后一项多余边线问题；重构 Carousel、Menu 核心实现
- 修复 NoticeBar 文字大小问题；修复 RN Radio 受控状态实现错误的问题
- 修复 RefreshControl 的`distanceToRefresh`设置，使其能自适应不同分辨率的屏幕
- 恢复 Picker、DatePicker 的 extra 设置并更新其文档，并增加自定义 children 的 demo
- 修复 Steps status error 状态展示问题；对 Popup 点击遮罩层的回调函数`onMaskClose`进行功能补充
- 优化 InputItem、TextareaItem、Picker、DatePicker 等组件 demo ，优化各组件文档细节

**Comment by warmhug** [comment]
### 0.9.13 (wip)
- 全面替换 touchableFeedback 为 `rc-touchable`
- 修复 Modal 文档错误，优化 Modal、SegmentedControl、TabBar (#646) 的实现和示例
- 修复 ListItem 没有 onClick 事件时也会触发点击反馈问题 #220#issuecomment-267587198
- 优化 ListView 等组件文档

**Comment by silentcloud** [comment]
### 0.9.14
- 修复 Carousel afterChange 不触发问题， #711

**Comment by warmhug** [comment]
@silentcloud 0.9 分支两个问题：rn Popup 组件和 demo 问题；`npm run build-rn` 失败问题(tab-bar 问题)，抓紧修复下。明天下午发 0.9.14

**Comment by warmhug** [comment]
### 0.9.15
- 修复并优化 TextareaItem, Accordion, Popover, ListView, InputItem 等组件细节问题 #724 #725 #788 #426
- 修复 RN Grid 的 onClick点击失效问题 #755
- Toast 组件修改成单例模式，避免多个 toast 同时或无序出现的问题 #745
- Modal 组件在 alert / prompt 的 action 里增加 Promise 支持
- TabBar 组件 Android 代码新增 iconStyle 属性支持 #776
- SwipeAction 组件增加遮罩背景样式，并优化 demo

**Comment by pingan1927** [comment]
### 0.9.16
- 修复带跑马灯效果的 Grid 组件初始化时跑马灯初始宽度为0的问题

**Comment by paranoidjk** [comment]
Close this.

Basicly, we hope no more update on branch 0.9.x, unless there is very seriously problem.
