### ISSUE TITLE
The `default.less` stylesheet is out of date. I cannot change the primary text color.

### ISSUE THREAD

**Issue by thisissami** [ant-design/ant-design-mobile#3450]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://there-is-no-minimal-reproduction-because-this-is-far-too-complex-a-setup-and-it-is-very-straightforward-to-explain.com](https://there-is-no-minimal-reproduction-because-this-is-far-too-complex-a-setup-and-it-is-very-straightforward-to-explain.com)

### Steps to reproduce
1) Create a project using `ant-design-mobile`. Configure with `webpack` and `babel` to allow you to change `less` variables.
2) Set up `webpack` with the following:

```typescript
        use: [
          'style-loader',
          'css-loader',
          {
            loader: 'less-loader',
            options: {
              modifyVars: {
                'brand-primary': color.logoTextGreen,
                'color-text-base': color.logoTextGreen,
                'color-text-secondary': color.logoTextGreen,
                'color-text-caption': color.logoTextGreen,
                'color-text-paragraph': color.logoTextGreen,
                'body-background': color.lightGrey,
                'font-family': 'RobotoRegular, RobotoBold, RobotoLight, RobotoBlack'
              },
              javascriptEnabled: true
            }
          }
        ]
```
3) Run the webpack project using `webpack-dev-server`.
4) Load your webpage

I should note that I am using `code splitting` - and the "antd overriding my `body`" only happens when new chunks download after I make a change that is tracked and updated by `webpack-dev-server`.

### What is expected?
I expect my text color to be the color that I am setting. If `color.logoTextGreen === 'green'`, then `color: 'green'` to be set on the `body`.

### What is actually happening?
`ant-design-mobile` is setting `color: rgba(0, 0, 0, 0.65)` on the `body`. I have no idea how to change it. It's very frustrating, as I now need to add a manual `color` css on *every single element*. The value `rgba(0, 0, 0, 0.65)` does not exist anywhere in this document: https://github.com/ant-design/ant-design-mobile/blob/master/components/style/themes/default.less Clearly something is missing.

How can I actually set the primary color that I want?

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.10 |
| System | Linux |
| Browser | Firefox |

---
Honestly - I think it is a major major design shortcoming of `antd` (both desktop and mobile) that you set `antd`s own CSS on the `body`. this should be something optional - not forced. It's made more frustrating when things like this come up. I hope that for the next major release, your team will address this.

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
