### ISSUE TITLE
imagePicker ios端上传图片偶尔出现白屏，怎么破？

### ISSUE THREAD

**Issue by circlexia** [ant-design/ant-design-mobile#3452]

**Comment by Fuphoenixes** [comment]
是因为ios端拍的图片太大了吗？一般都近1到2M了，可以考虑用小一点的图片试试，如果没问题，则可以考虑利用canvas压缩图片后在上传

**Comment by circlexia** [comment]
主要是只有ios 13.1.2和13.1.3版本上才有这种大于10M出现白屏的bug

**Comment by Fuphoenixes** [comment]
10M的图片一般不让上传了吧，或者你最好给它压缩了在上传

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
