### ISSUE TITLE
SearchBar placeholder 获取焦点后，显示重复

### ISSUE THREAD

**Issue by HuZhangRong** [ant-design/ant-design-mobile#3454]
代码：
` <SearchBar placeholder="111111111111" className={styles.amSearch}
                    maxLength={50}
                    showCancelButton={true}
                    onSubmit={this.onSubmit}
                    onCancel={this.clickSearch}
                    cancelText={<span className={styles.cancelText}>搜索</span>}
                    ref={ref => this.autoFocusInst = ref} />`
结果： 点击输入，或者初始化页面时，自动获取焦点后，按理说，我将不会看到11111111111，但是，现在不仅能看到，还会有两个重复的11111111111存在

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
