### ISSUE TITLE
PullToRefresh 在未升级IOS13的iPhone上正常，但在已升级IOS13的IPhone上异常

### ISSUE THREAD

**Issue by tsn0106** [ant-design/ant-design-mobile#3455]

**Comment by HuZhangRong** [comment]
其他手机也会处理这个问题，，我也遇到了，不仅仅是IOS13 苹果的问题

**Comment by fkdswfwqfet** [comment]
怎么解决呢？

**Comment by tsn0106** [comment]
弃用了。。。
使用了以下组件:
https://github.com/soluteli/react-bscroll

https://better-scroll.github.io/docs/zh-CN/guide/base-scroll-api.html#%E5%B1%9E%E6%80%A7
&nbsp;




唐胜男
前端
河南艺境空间


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fkdswfwqfet"<notifications@github.com&gt;; 
发送时间: 2019年12月6日(星期五) 晚上7:39
收件人: "ant-design/ant-design-mobile"<ant-design-mobile@noreply.github.com&gt;; 
抄送: "尘世"<2308092717@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design-mobile] PullToRefresh 在未升级IOS13的iPhone上正常，但在已升级IOS13的IPhone上异常 (#3455)




怎么解决呢？

**Comment by zhangshuaidan** [comment]
目前在ios13上我的项目也遇到了这种问题，其余低版本的ios 暂时未发现，android也ok

**Comment by mmmaomao21** [comment]
> 目前在ios13上我的项目也遇到了这种问题，其余低版本的ios 暂时未发现，android也ok

能说一下具体是什么问题嘛 正好要做这个需求

**Comment by HuZhangRong** [comment]
就是列表渲染出来是空白页面，但是，其实数据是已经出来了，点击空白的地方，还是会像点击跳转到原本该渲染出来的页面，比如：列表页，点击，跳转到详情页面。但是，当我往下拉刷新的时候，渲染不出来，然后，又往上滑，原本渲染出来的东西，也会不见了。最后，我的不同的列表试了这个东西，奇怪的是，有的地方可以，有的地方不行，就是很奇怪
解决方式：找了很多了没找到，然后就避开了，用其他的东西做了。

**Comment by mmmaomao21** [comment]
> 就是列表渲染出来是空白页面，但是，其实数据是已经出来了，点击空白的地方，还是会像点击跳转到原本该渲染出来的页面，比如：列表页，点击，跳转到详情页面。但是，当我往下拉刷新的时候，渲染不出来，然后，又往上滑，原本渲染出来的东西，也会不见了。最后，我的不同的列表试了这个东西，奇怪的是，有的地方可以，有的地方不行，就是很奇怪
> 解决方式：找了很多了没找到，然后就避开了，用其他的东西做了。

后来用了什么？我看这个真的很多人提bug 不敢用了

**Comment by HuZhangRong** [comment]
listView

**Comment by mmmaomao21** [comment]
> listView

listview数据结构好复杂，我需要的结构就是一层结构的，可以修改嘛？然后样式上和他demo完全不一样，可以修改嘛

**Comment by HuZhangRong** [comment]
`listview数据结构好复杂，我需要的结构就是一层结构的，可以修改嘛？然后样式上和他demo完全不一样，可以修改嘛`

一层结构是什么意思

**Comment by mmmaomao21** [comment]
@HuZhangRong  dataSource = new ListView.DataSource  这个组件需要的数据得是new ListView.DataSource  然后这个数据结构又是 { sectionID_1: { rowID_1: <rowData1>, ... }, ... } 这种有多重得，但是我的需求数据结构就是平铺的{name:'',age:12}这种，如果我用ListView.DataSource ，我是不是得编造结构啊

**Comment by HuZhangRong** [comment]
@mmmaomao21 
那如果你要用listView肯定就得按照别人的标准来撒，不然呢，你也可以用其他的啊，只要满足你的要求不就行了吗？

**Comment by tclyjy** [comment]
样式里面增加一行 可解决
.am-pull-to-refresh {
  // IOS13 重绘问题，hack 触发重绘 
  transform: translate3d(0,0,0)
}

**Comment by SuXiZheng** [comment]
> 样式里面增加一行 可解决
> .am-pull-to-refresh {
> transform: translate3d(0,0,0)
> }

群众里面有高人呐。此方案可行。

**Comment by sanshuiwang** [comment]
> 样式里面增加一行 可解决
> .am-pull-to-refresh {
> transform: translate3d(0,0,0)
> }

此方案吊炸天

**Comment by ShaunZh** [comment]
> 样式里面增加一行 可解决
> .am-pull-to-refresh {
> transform: translate3d(0,0,0)
> }

方案可行👍👍👍

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by helloworldcyj** [comment]
> 样式里面增加一行 可解决 .am-pull-to-refresh { transform: translate3d(0,0,0) }

为什么会这样呢？遇见了同样的问题，但是找不到具体原因
