### ISSUE TITLE
InputItem组件确认按钮状态出现bug

### ISSUE THREAD

**Issue by 592192890** [ant-design/ant-design-mobile#3457]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item](https://mobile.ant.design/kitchen-sink/components/input-item)

### Steps to reproduce
官网demo即可重现该问题：
1. 我让inputitem聚焦，但不输入数字，确定按钮是灰色的，
2. 但当我不输入数字，直接点击确定按钮，确定按钮不在是灰色的了。

### What is expected?
当我没有输入数字时，确定按钮应该是灰色的

### What is actually happening?
点击两次确定按钮后，就算没有输入数字，确定按钮不在是灰色的了。

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.8.6 |
| System | 任意系统 |
| Browser | 任意浏览器 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
