### ISSUE TITLE
calendar组件改变visible不会切换展示状态—iphone5

### ISSUE THREAD

**Issue by suvllian** [ant-design/ant-design-mobile#3458]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/calendar-cn/](https://mobile.ant.design/components/calendar-cn/)

### Steps to reproduce
通过一个state属性控制calendar组件的visible，state初始值为false，再通过点击按钮切换该state为true

### What is expected?
点击按钮时，state已经为true，应该展示calendar组件。

### What is actually happening?
点击按钮没有任何反应。当我在calendar组件添加一个动态的key属性，强制刷新组件时，点击按钮就可以展示calendar组件了。

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.11.0 |
| System | iPhone5 |
| Browser | 钉钉端H5页面 |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
