### ISSUE TITLE
使用NextJS以及react-intl-universal时在服务器端输出List组件时如果元素中包含翻译那么class会被放到错误的地方

### ISSUE THREAD

**Issue by yyss8** [ant-design/ant-design-mobile#3459]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/yyss8/antd-mobile-bug](https://github.com/yyss8/antd-mobile-bug)

### Steps to reproduce
1. `git clone https://github.com/yyss8/antd-mobile-bug.git`
2. `npm install`.
3. `npm run dev`
4. 访问[localhost:3000](http://localhost:3000).

只有在SSR渲染环境下才会出现这个错误, 所以刷新页面才会看到错误的样式

### What is expected?
1. 如果在header中使用翻译内容, am-list-body被放置到正确的元素上
2. 如果在list中的Input中使用翻译内容, am-input-control被放置到input的wrapper div上

### What is actually happening?
1. 如果在header中使用翻译内容, am-list-body会被am-list-header代替
![image](https://user-images.githubusercontent.com/13445723/69003230-6fc8c280-08cc-11ea-92f8-2af1a40fb248.png)

2. 如果在list中的Input中使用翻译内容, am-input-control不会添加至input的wrapper div上
![image](https://user-images.githubusercontent.com/13445723/69003247-ac94b980-08cc-11ea-87e4-41e8f60d4ac8.png)

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | ^16.11.0 |
| System | Windows |
| Browser | Chrome |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
