### ISSUE TITLE
Tabs的title如何实现置顶

### ISSUE THREAD

**Issue by ludaima** [ant-design/ant-design-mobile#346]
#### 本地环境

- antd-mobile 版本：0.9.0
- 操作系统及其版本：Mac 10.12
- 浏览器及其版本：Chrome 

####  我的问题？
当滚动页面时，tabs的title能够一直置顶。

![代码](http://hoop8.com/1610B/yFc4EFQc.png)

因为目前api这样的实现，无法使用Sticky进行置顶（😜或者，我没找到实现的方式）
查看ListView，有属性可以直接。
谢谢

**Comment by silentcloud** [comment]
@ludaima 你的意思是只想让 tab 的内容区域滚动?

**Comment by ludaima** [comment]
@silentcloud 谢谢解答。
是的。类似https://mobile.ant.design/components/list-view/ 里的【标题吸顶（body 容器）】效果

**Comment by warmhug** [comment]
可以使用这个库 https://github.com/captivationsoftware/react-sticky ，list-view 内部就是依赖的这个

**Comment by ludaima** [comment]
@warmhug 谢谢解答。
已经使用这个库了。
已经能让<NavBar>进行置顶，但是<Tabs>不知道如何进行处理。

**Comment by warmhug** [comment]
为什么不用 <Sticky></Sticky> 包起 Tabs 来？

**Comment by ludaima** [comment]
@warmhug 之前尝试了下把Tabs也包进去，但是发现没有效果。

**Comment by warmhug** [comment]
自己调试下排查原因吧

**Comment by ludaima** [comment]
@warmhug 好的。谢谢。
包完之后，Tabs的内容区域也会跟着置顶。
猜想，需要有办法实现，只“包”到Tabs的Header部分。
