### ISSUE TITLE
DatePickerView 组件不显示 1 月，且所有月份都没有 31 号

### ISSUE THREAD

**Issue by hellohejinyu** [ant-design/ant-design-mobile#3462]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/date-picker-view](https://mobile.ant.design/kitchen-sink/components/date-picker-view)

### Steps to reproduce
官网首页的 demo 地址打开就能看到 DatePickerView 这个组件不正常了
![image](https://user-images.githubusercontent.com/8766034/69048429-6197b500-0a38-11ea-971d-0e485571929f.png)

### What is expected?
能正常显示

### What is actually happening?
没有 1 月，且我本地跑的时候每个月都没有 31 号

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.8.6 |
| System | macOS |
| Browser | Chrome 78 |

**Comment by wenJonSnow** [comment]
遇到了同样的问题，都只显示到29号，日期也没有对应变动

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
