### ISSUE TITLE
城市组件pick组件联级选择城市滑动过快bug

### ISSUE THREAD

**Issue by wudigongchengshi** [ant-design/ant-design-mobile#3463]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/master/components/picker/AbstractPicker.tsx](https://github.com/ant-design/ant-design-mobile/blob/master/components/picker/AbstractPicker.tsx)

### Steps to reproduce
城市组件pick组件联级选择城市滑动过快点击确定可能以为区的code还是上一个code，导致区的信息数组遍历不到，页面渲染只有省和市，（没有区），

### What is expected?
市滑动过快，区会自动默认当前市第一个区

### What is actually happening?
市滑动过快，区内容不显示

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.8 |
| System | android8.0 |
| Browser | 最新版本 |

---
用户操作过快会出现bug

**Comment by sir-ran** [comment]
今天也遇到这个问题了，
三级联动的时候，列滑动过快，将不能选择，

**Comment by wudigongchengshi** [comment]
这个问题，官方没有解释么？

**Comment by a4825917** [comment]
写的自定义 picker 滑动过快 -> 滑动过程中点击确定 -> 会出现内存泄漏的错误

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
