### ISSUE TITLE
PullToRefresh 组件direction=up在小米手机自带浏览器中上拉不动

### ISSUE THREAD

**Issue by q364237398** [ant-design/ant-design-mobile#3468]
<PullToRefresh  damping={60}  direction={'up'}></PullToRefresh>

_this2.isEdge = function (ele, direction) {
            ...
            if (direction === UP) {
                return ele.scrollHeight - ele.scrollTop === ele.clientHeight;
            }
            ...
        };
ele.scrollTop在浏览器中是小数，造成底部判断返回 false

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
