### ISSUE TITLE
rn-topview open source

### ISSUE THREAD

**Issue by huliyou** [ant-design/ant-design-mobile#347]
在哪里可以获取 rn-topview 的源码

**Comment by silentcloud** [comment]
这个不提供源码，属于内部代码

**Comment by laiyifeng77** [comment]
highly recommend to open source of rn-topview

**Comment by paranoidjk** [comment]
@silentcloud 考虑下。

**Comment by silentcloud** [comment]
closed for patent

**Comment by lucasleelz** [comment]
I hope it can open the source code

**Comment by listenzz** [comment]
topview 可能存在问题，返回的结果可能不是只有一个 view。我们的项目中使用了原生导航组件，每个页面就是一个 ReactRootView，当在最上面的 ReactRootView 使用 Toast 组件时，Toast 的 onClose 的回调次数是 ReactRootView 的个数

**Comment by ngyikp** [comment]
Can the license be changed to not GPL? https://cdn.jsdelivr.net/npm/rn-topview@0.1.6/package.json
