### ISSUE TITLE
IOS手机Modal中滑动后数据消失，dom节点还在（IOS mobile phone Modal data is not displayed after scrollingshou）

### ISSUE THREAD

**Issue by ming16019** [ant-design/ant-design-mobile#3471]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://cemobiletest.lzlj.com](http://cemobiletest.lzlj.com)

### Steps to reproduce
用ios进入事前申请，点击申请人

### What is expected?
正常滚动并显示数据

### What is actually happening?
能够滑动但是数据不显示，往下拉控件都不显示了

| Environment | Info |
|---|---|
| antd | 2.3.1 |
| React | react |
| System | ios |
| Browser | chrome |

**Comment by ming16019** [comment]
![error](https://user-images.githubusercontent.com/56812146/69770830-778a4000-11c5-11ea-9916-9313684e2eec.jpg)

**Comment by ming16019** [comment]
加上onWrapTouchStart ，用最原生的在ios上没问题，但是加上<Item><Item/>之类的修饰，就会变成一片白
![onWrapTouchStart ](https://user-images.githubusercontent.com/56812146/69772073-e073b700-11c9-11ea-8a40-dbe0d722c6a5.png)

**Comment by ming16019** [comment]
原生数据可显示 里面的组件滑动后全部空白

**Comment by ming16019** [comment]
const test2=                   test.map((data, index) => {
      return (
          <Item value={data.empName} key={index}>
            <Flex>
              <Flex.Item className="center">
                <div  value={data.text} id={data.id}>{data.text}</div>
              </Flex.Item>
              <Flex.Item className="center">
                <div  value={data.text} id={data.id}>{data.id}</div>
              </Flex.Item>
            </Flex>
          </Item>
      )
    })



            <Modal
                visible={this.state.applicantModal}
                onClose={this.onClose('applicantModal')}
                // animationType="up"
                // platform='ios'
                                maskClosable={false}
                                title="Title"
                                wrapProps={{ onTouchStart: this.onWrapTouchStart }}


              >
                 <div style={{ height: 100, overflow: 'scroll' }}>
                   {test2}
                </div>
              </Modal>


数据遍历后 ios显示有问题 滑动后空白，直接写固定值 没问题

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
