### ISSUE TITLE
ListView和pullToRefresh组合使用，当我的列表滑动一定高度之后我想下拉看之前划过去的内容，这时却触发了下拉刷新导致我不能往上翻了，这是什么原因？

### ISSUE THREAD

**Issue by BeingForever** [ant-design/ant-design-mobile#3472]

**Comment by fedQu** [comment]
我也遇到了这个问题，您解决了吗

**Comment by taixw2** [comment]
这是因为 `PullToRefresh` 的容器没有设置高度，容器没有出现滚动条，**下滑的时候容器的 scrollTop 一直是 0**，所以会触发下拉刷新的操作，解决方法就是给容器设置高度，让 `PullToRefresh` 接管滚动条

```javascript
    <PullToRefresh
      style={{ height: '100vh', overflowY: 'auto' }}
     ...
    >
      {props.children}
    </PullToRefresh>
```

**Comment by Tammy-world** [comment]
ListView里设置了PullToRefresh的style ,<PullToRefresh
      style={{ height: '100vh', overflowY: 'auto' }}
     ...
    >
      {props.children}
    </PullToRefresh>没有生效，ListView用的useBodyScroll属性，设置ListView的PullToRefresh 的高度后，仍旧会出现不能上翻的问题，安卓和ios都有此问题

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级到 v5
