### ISSUE TITLE
Tabs引用失败

### ISSUE THREAD

**Issue by chenbo000302** [ant-design/ant-design-mobile#3474]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
import { Tabs} from 'antd-mobile-rn';
<Tabs></Tabs>

### What is expected?
期望结果tab正常显示

### What is actually happening?
报错：
TypeError:undefined is not an object(evaluating 'this._scrollResponder')

This error is located at:
 in AnimatedComponent（ created by tabs）
 in RCTView (created by tabs)
 in tabs(created by tags)
 in ScrollView(at commodity)

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | react16.6.0/react-native0.61.4 |
| System | windows |
| Browser | 安卓手机端 |

**Comment by awmleer** [comment]
rn 相关问题请移步：https://github.com/ant-design/ant-design-mobile-rn/issues
