### ISSUE TITLE
In Typescript env,overlayClassName and some rmc-tooltip props can't work

### ISSUE THREAD

**Issue by YellowPure** [ant-design/ant-design-mobile#3477]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:3001](http://localhost:3001)

### Steps to reproduce
use Popover Component and overlayClassName prop.

### What is expected?
like example.

### What is actually happening?
tslint tips me "don't have property overlayClassName."

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | react-16.8.18 |
| System | macOS 10.15.1  |
| Browser | chrome@lasest |

**Comment by YellowPure** [comment]
```javascript
import { ITooltipProps } from 'rmc-tooltip/lib/Tooltip';

export interface PopoverPropsType extends ITooltipProps {
```
this can worked. please add it

**Comment by mufson** [comment]
这个要怎么添加

**Comment by YellowPure** [comment]
like this:
node_modules/antd-mobile/lib/popover/PropsType.d.ts
or
node_modules/antd-mobile/es/popover/PropsType.d.ts

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
