### ISSUE TITLE
rmc-nuka-carousel 是否开源？有个问题涉及内部的代码

### ISSUE THREAD

**Issue by gyh9457** [ant-design/ant-design-mobile#3478]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gyh9457.github.io/carousel-demo/build/index.html](https://gyh9457.github.io/carousel-demo/build/index.html)

### Steps to reproduce
demo 上即可重现 源码请看 https://github.com/gyh9457/carousel-demo/blob/master/src/App.js

### What is expected?
设置了每项的高度，在子项 index !==  selectedIndex 时，高度变小, 子项 index === selectedIndex 时，高度变大

### What is actually happening?
当前项的高度取的是子元素第一项的 offsetHeight

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.11.0 |
| System | win10 |
| Browser | chrome |

**Comment by gyh9457** [comment]
![image](https://user-images.githubusercontent.com/13557235/69965591-8e2af100-154f-11ea-9ba4-cfaf5e2a8f80.png)

初步判断这边要做一个修改

**Comment by gyh9457** [comment]
期望效果：

![height](https://user-images.githubusercontent.com/13557235/70013671-640b1a80-15b3-11ea-805c-bcd470fdd1d9.gif)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
