### ISSUE TITLE
DatePicker 和 Picker 的 disabled 属性应该注入 List.Item

### ISSUE THREAD

**Issue by theprimone** [ant-design/ant-design-mobile#3479]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
List.Item 在 disabled 后会将字段标签置灰以标示该项不可用。DatePicker 和 Picker disabled 在 disabled 后逻辑上实现了不可用，但是没有像 List.Item 那样将标签置灰

### What does the proposed API look like?
为 DatePicker 和 Picker 等包裹的子组件注入 disabled 属性

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
