### ISSUE TITLE
antm由0.7.2升级0.9.0后，组件Tag不支持"关闭功能"

### ISSUE THREAD

**Issue by DanielJyc** [ant-design/ant-design-mobile#348]
#### 问题描述
antm由0.7.2升级0.9.0后，组件Tag不支持`关闭功能`

希望对此支持，或者其它解决方案。

**Comment by silentcloud** [comment]
设计师在0.8上给砍掉了，我这边跟设计师沟通，尽量今天在 0.9 的上发个小版本

**Comment by warmhug** [comment]
注意不要贴内网地址，issue模板 里写了公网演示地址 https://github.com/ant-design/ant-design-mobile/issues/new 
![image](https://cloud.githubusercontent.com/assets/2011119/19226704/677d3a38-8ee1-11e6-9f8e-3a882b394a67.png)

**Comment by silentcloud** [comment]
`0.9.2`
