### ISSUE TITLE
Customize Ant Design Mobile Theme for ReactJS

### ISSUE THREAD

**Issue by KaizenTamashi** [ant-design/ant-design-mobile#3481]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/kvnlee777/issue](https://github.com/kvnlee777/issue)

### Steps to reproduce
yarn start

### What is expected?
the customized theme should be applied

### What is actually happening?
it does not show error in the terminal, but the theme is not applied.

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.1 |
| Browser | Google Chrome Version 78.0.3904.108 (Official Build) (64-bit) |

---
i'm trying to customize the theme of Ant Design React Mobile Web. I tried the provided instruction by Ant Design https://mobile.ant.design/docs/react/customize-theme#How-to-do-it. It does not show any error in the terminal but the theme is not applied. Here is the link to the reproduction of repo https://github.com/kvnlee777/issue

**Comment by awmleer** [comment]
v2 is no longer maintained. For v5 users please refer here: https://mobile.ant.design/guide/theme
