### ISSUE TITLE
1.x官网无法打开，无法查看api

### ISSUE THREAD

**Issue by zhaoguangyue** [ant-design/ant-design-mobile#3482]
http://new-issue.ant.design?repo=ant-design-mobile

**Comment by zhaoguangyue** [comment]
麻烦修一下，1.x还有人用

**Comment by ziluo** [comment]
感谢反馈，我们跟进修复下

**Comment by zhaoguangyue** [comment]
> 感谢反馈，我们跟进修复下

需要查看api，麻烦及时更近，仍未修复

**Comment by wZi** [comment]
这个里面有 [点我](https://www.bookstack.cn/read/antd-mobile-v1.x/66cfa2589ea1da65.md)

@zhaoguangyue 

FYI~
