### ISSUE TITLE
Carousel组件在华为自带浏览器左右滑动无效

### ISSUE THREAD

**Issue by xiangxingchen** [ant-design/ant-design-mobile#3483]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/carousel](https://mobile.ant.design/kitchen-sink/components/carousel)

### Steps to reproduce
左右滑动幻灯片，无法滑动。向左下方滑动可以成功

### What is expected?
左右正常滑动

### What is actually happening?
左右无法正常滑动，向左下方滑动可以成功

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.7.0 |
| System | Android9.1 |
| Browser | 华为畅享10P原生浏览器 |

**Comment by SilvesterChiao** [comment]
应该是跟前进后退冲突，我在小米8上也碰到了

**Comment by awmleer** [comment]
https://mobile.ant.design/zh/components/swiper
