### ISSUE TITLE
Modal组件中如果有图片，在ios的微信上无法显示

### ISSUE THREAD

**Issue by hiBruce** [ant-design/ant-design-mobile#3485]
ios版本：13.1.3
微信版本：7.0.4
问题描述：所有Modal组件中的图片，不管是项目内的地址，还是网络图片，都无法显示。如果给了图片宽高，在图片位置长按是可以正常保存，保存到本机后的图片也是正确的，就是页面Modal里显示是空白。

**Comment by awmleer** [comment]
https://mobile.ant.design/zh/components/dialog
