### ISSUE TITLE
小米9 pro 和 红米note7 pro 在聚焦 type=password 的 inputitem 时卡死

### ISSUE THREAD

**Issue by z0nka1** [ant-design/ant-design-mobile#3486]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/](https://mobile.ant.design/)

### Steps to reproduce
点击 type=password 的 inputitem

### What is expected?
可以正常输入密码

### What is actually happening?
页面卡死

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | 16.4.2 |
| System | MIUI 11 |
| Browser | webview |

**Comment by awmleer** [comment]
v2 已停止维护了
