### ISSUE TITLE
inputItem 在 type=password 时，在iPhone 11 Pro Max上弹出的键盘一片空白，但是点击空白处可以输入

### ISSUE THREAD

**Issue by z0nka1** [ant-design/ant-design-mobile#3488]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/](https://mobile.ant.design/)

### Steps to reproduce
1，有一个 type=password 的 inputItem 输入框
2，iPhone 11 Pro Max手机上点击这个输入框

### What is expected?
期望可以弹出正常键盘

### What is actually happening?
弹出的键盘一片空白

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.4.2 |
| System | IOS 13.2.3 |
| Browser | webview |

![image](https://user-images.githubusercontent.com/24217059/70693044-96c1bb00-1cf7-11ea-91b4-70a68d7d3822.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
