### ISSUE TITLE
InputItem数字格式希望支持小数点

### ISSUE THREAD

**Issue by foriacus** [ant-design/ant-design-mobile#349]

**Comment by pingan1927** [comment]
@yiminghe InputItem的数字格式 期望的是唤起数字键盘，这个和支持小数点 会冲突，
我们要不要换下？

已经有好几个用户反馈要支持小数点了。

之前的做法是如果要支持小数点，在使用默认的格式，自己做校验

**Comment by yiminghe** [comment]
ok

**Comment by pingan1927** [comment]
那我就把parttern换成数字正则校验，放弃弹出数字键盘的特性

**Comment by warmhug** [comment]
`0.9.6` 支持接收所有合法的 input 属性，包括 pattern，可以自己设置了。

**Comment by gebilaoxiong** [comment]
ping @warmhug 我们这边用的1.0.5还是不支持小数点呢  

onChange的正则也没有修改

https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.web.tsx#L81

**Comment by paranoidjk** [comment]
@pingan1927 InputItem 的文档和 demo 里补充关于数字键盘 以及 小数点这块的内容
