### ISSUE TITLE
npm run build时会报警告：[mini-css-extract-plugin] Conflicting order bettween: .....

### ISSUE THREAD

**Issue by alwaysRemember** [ant-design/ant-design-mobile#3493]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/index-cn 非前端浏览问题](https://mobile.ant.design/index-cn 非前端浏览问题)

### Steps to reproduce
npm run build

### What is expected?
不报警告：[mini-css-extract-plugin] Conflicting order bettween: .....

### What is actually happening?
[mini-css-extract-plugin] Conflicting order bettween: .....
 * css ./node_modules/css-loader??ref--5-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/antd-mobile/lib/modal/style/index.css
 * css ./node_modules/css-loader??ref--5-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/antd-mobile/lib/button/style/index.css

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.8.3 |
| System | macos |
| Browser | chrome |

**Comment by awmleer** [comment]
v2 已经不再维护了
