### ISSUE TITLE
在react-native中使用tabs组件报错RNCViewPaper was not found in the UIManager

### ISSUE THREAD

**Issue by PursuitLife** [ant-design/ant-design-mobile#3494]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/tabs-cn/](https://rn.mobile.ant.design/components/tabs-cn/)

### Steps to reproduce
在react-native中使用tabs组件报错RNCViewPaper was not found in the UIManager

### What is expected?
在react-native中使用tabs组件

### What is actually happening?
在react-native中使用tabs组件报错RNCViewPaper was not found in the UIManager

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 0.61.5 |
| System | windows |
| Browser | 谷歌 |

**Comment by wuaonan** [comment]
找到tabs的源码 修改tabs.js文件  第34行 改成 const { ViewPagerAndroid } = _reactNative; 就好了 亲测有效
