### ISSUE TITLE
Listview滚动之后renderRow不重新渲染

### ISSUE THREAD

**Issue by chuhanan** [ant-design/ant-design-mobile#3495]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://192.168.6.211:9001/listview?q=此问题必现](http://192.168.6.211:9001/listview?q=此问题必现)

### Steps to reproduce
renderRow 中有类似交互组件如 Checkbox, 开始未选中, 页面未滚动或者滚动距离小时, 点击受控组件 Checkbox 可以选中并且更新渲染, 当数据超过1页滚动到一定距离的时候, 点击 Checkbox 选中失效, 页面所有 Checkbox 都无法点击选中, 并且 renderRow 没有更新 

### What is expected?
renderRow 重新渲染, 滚动之后无异常情况

### What is actually happening?
renderRow 未重新渲染, 滚动之后页面嗝屁无法交互

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.x |
| System | window64 |
| Browser | google |

---
renderRow中有交互式UI 不重新渲染

**Comment by yzyzhby** [comment]
可以将renderRow 提取成独立的react 组件，状态在这个独立的组件里面管理就行了

**Comment by yursile** [comment]
解决了吗？@chuhanan

**Comment by chuhanan** [comment]
> 解决了吗？@chuhanan

解决了, 把Listview 干掉了

**Comment by yursile** [comment]
...我也刚干掉listview，依赖的底层rmc-list几年没更新了

**Comment by yzyzhby** [comment]
不用干掉吧。。。，我说的那种方式可以解决这个问题的

**Comment by yursile** [comment]
主要是当前row变换后，其他row也要跟着变换，播放列表

**Comment by yzyzhby** [comment]
应该是可以做到的，你多尝试一下
