### ISSUE TITLE
touchstart 页面其他位置时，应该立即隐藏 popover

### ISSUE THREAD

**Issue by hotoo** [ant-design/ant-design-mobile#3497]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不立即隐藏的情况下，拖放屏幕滚动时 Popover 一直固定在同一个位置上，和 trigger 分离。如图示：

![popover](https://user-images.githubusercontent.com/143572/71142610-d25a0900-2252-11ea-9c94-03bf6fe41b66.gif)

### What does the proposed API look like?
希望 touchstart 页面其他位置时，立即隐藏 Popover 组件。

**Comment by awmleer** [comment]
这个 issue 是 v2 版本当时提的了，不过 v5 版本现在也还存在这个问题

**Comment by hotoo** [comment]
3年了，不容易 😂
