### ISSUE TITLE
Calendar组件日历关闭的动画css错误

### ISSUE THREAD

**Issue by CC802** [ant-design/ant-design-mobile#3498]
**What problem ?**
原来的css代码
![image](https://user-images.githubusercontent.com/39610477/71163727-a48fb700-2288-11ea-97bc-458ccddebff9.png)
修改过后的代码
![image](https://user-images.githubusercontent.com/39610477/71163546-4662d400-2288-11ea-8fa4-a6692c728a6d.png)
**What problem does this feature solve?**
修改过后的日历关闭后顺利往下滑

**Comment by awmleer** [comment]
v2 已经停止维护了，v5 很快会发布 Calendar 组件
