### ISSUE TITLE
旧版本苹果手机grid异常

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design-mobile#35]
#### 官方演示demo

- antd-mobile 版本：0.7.2
- 操作系统及其版本：ios7.1.2
- 浏览器及其版本：ios7.1.2

#### 你做了什么？

进入grid demo

#### 你期待的结果是：

正常显示

#### 实际上的结果：

布局变形，元素文字越多变形越厉害，并且单击事件失效

#### 可重现的在线演示

官方的就有问题

![image](https://cloud.githubusercontent.com/assets/16314313/17367773/f794d034-59c3-11e6-8047-54f9ddacd734.png)

**Comment by dyf2015** [comment]
部分ios9也会有问题

**Comment by pingan1927** [comment]
这个是flex的兼容属性没考虑iOS8系统导致的。
`.am-flexbox` 需要 display: -webkit-flex;
缺失 -webkit- 前缀：
`.am-flexbox.am-flexbox-justify-around:`
增加 -webkit-justify-content: space-around;
以及 justify-content 可选的相关类应该同样问题
`.am-flexbox .am-flexbox-item:`
增加 `-webkit-flex: 1;`
可能还有其他类缺失 `-webkit-`

可以先加点样式兼容下，工具升级后马上就好

**Comment by dyf2015** [comment]
感谢

发自我的 iPhone

在 2016年8月4日，13:17，pingan1927 <notifications@github.com<mailto:notifications@github.com>> 写道：


这个是flex的兼容属性没考虑iOS8系统导致的。
.am-flexbox 需要 display: -webkit-flex;
缺失 -webkit- 前缀：
.am-flexbox.am-flexbox-justify-around:
增加 -webkit-justify-content: space-around;
以及 justify-content 可选的相关类应该同样问题
.am-flexbox .am-flexbox-item:
增加 -webkit-flex: 1;
可能还有其他类缺失 -webkit-

可以先加点样式兼容下，工具升级后马上就好

―

**Comment by yiminghe** [comment]
atool-build 0.8.x
