### ISSUE TITLE
DatePickerView组件设置mode="time", minuteStep>1时（例如30），结束时间选择不了24:00

### ISSUE THREAD

**Issue by YufeeXing** [ant-design/ant-design-mobile#3501]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
DatePickerView组件设置mode="time", minuteStep>1时（例如30），结束时间选择不了24:00

### What does the proposed API look like?
如果间隔的结束时间可以是24:00，例如5，10，15，30，结束时间可以时24:00. 但是目前例如间隔时30分钟，那么最后可选的时间只能时23:30.

**Comment by xiaohuoni** [comment]
`24:00` 就是 `00:00` 吧？

**Comment by awmleer** [comment]
可以考虑升级到新版的 DatePicker 组件
