### ISSUE TITLE
移动端禁用多选后，手机还可以多选

### ISSUE THREAD

**Issue by locozan** [ant-design/ant-design-mobile#3502]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/image-picker-cn/](https://mobile.ant.design/components/image-picker-cn/)

### Steps to reproduce
ImagePicker 图片选择器禁用多选后点击上传图片点击图后正常 只能点击一张图，但是用手滑动屏幕就允许多选了

### What is expected?
ImagePicker 图片选择器禁用多选后，用手滑动屏幕不允许多选

### What is actually happening?
ImagePicker 图片选择器禁用多选后点击上传图片点击图后正常 只能点击一张图，但是用手滑动屏幕就允许多选了

| Environment | Info |
|---|---|
| antd | 2.3.1 |
| React | 2.3.1 |
| System | 13.3 |
| Browser | safari,IE10,Google Chrome版本 69.0.3497.92 |

**Comment by xiaohuoni** [comment]
可重现，系统行为。最终返回的也是一张图片。暂不处理。
