### ISSUE TITLE
antd-mobile中less语法中@modalPrefixClass希望可以写在外部支持用户自定义配置 

### ISSUE THREAD

**Issue by Createwj** [ant-design/ant-design-mobile#3503]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd-mobile中less语法中@modalPrefixClass希望可以写在外部支持用户自定义配置 
```
@import '../../style/mixins';
@import '../../style/themes/default';

@modalPrefixClass: am-modal;

@import './Dialog.less';
```
@modalPrefixClass变量希望能够放在一起 支持高度用户自定义

### What does the proposed API look like?
```
@import '../../style/mixins';
@import '../../style/themes/default';

// @modalPrefixClass: am-modal;
@import '../../config/支持用户配置的方式';

@import './Dialog.less';
```

**Comment by xiaohuoni** [comment]
什么样的场景会需要它？

**Comment by awmleer** [comment]
v5 采用的是 CSS 变量，已经不再暴露 less 源文件了，prefix class 也不支持修改的

**Comment by awmleer** [comment]
如果真的有这种场景，可以说说具体是希望达到什么样的目的，我们来一起看看有没有别的办法
