### ISSUE TITLE
TabBar与ListView结合使用，在iOS微信浏览器里面出现滑动卡死现象

### ISSUE THREAD

**Issue by designersmallweb** [ant-design/ant-design-mobile#3505]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/tab-bar#tab-bar-demo-1](https://mobile.ant.design/kitchen-sink/components/tab-bar#tab-bar-demo-1)

### Steps to reproduce
打开链接，等待一段时间，手指向下多次滑动，接着手指向上滑动页面就会卡死现象

### What is expected?
无论向上滑动还是向下滑动都要保持流畅

### What is actually happening?
打开链接，等待一段时间，手指向下多次滑动，接着手指向上滑动页面就会卡死现象

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | ^16.8.6 |
| System | windows |
| Browser | 微信浏览器 |

**Comment by xiaoshui222** [comment]
请问你解决了吗，我的在Tabs里用ListView也出现了上下滑动卡顿问题

**Comment by sunhaibao123456** [comment]
手指向上滑动没遇到问题，但是向下滑动会和微信浏览器的下拉冲突，每次要滑两次才行，哎

**Comment by designersmallweb** [comment]
> 请问你解决了吗，我的在Tabs里用ListView也出现了上下滑动卡顿问题

没有解决

**Comment by designersmallweb** [comment]
> 手指向上滑动没遇到问题，但是向下滑动会和微信浏览器的下拉冲突，每次要滑两次才行，哎

你的问题跟我一样

**Comment by JiangMengLei** [comment]
> 请问你解决了吗，我的在Tabs里用ListView也出现了上下滑动卡顿问题

你们都是ios系统吗？

**Comment by xiaohuoni** [comment]
ios 系统版本多少呢？我在ios13.4.1 iphonex上无法复现。

**Comment by awmleer** [comment]
建议升级到 v5 的 TabBar 和 InfiniteScroll 组件
