### ISSUE TITLE
SearchBar第一次加载完成之后，需要点击两三次才能输入

### ISSUE THREAD

**Issue by wforguo** [ant-design/ant-design-mobile#3507]
第一次加载完成之后，需要点击两三次才能输入

**Comment by NodeMirai** [comment]
同学你解决了吗，我这边也有这种情况，searchbar单独写了个demo就没这种情况

**Comment by dinglino1** [comment]
解决了吗？InputItem组件也是需要多次才能聚焦

**Comment by wforguo** [comment]
没解决





------------------ 原始邮件 ------------------
发件人: dinglino1 <notifications@github.com&gt;
发送时间: 2020年1月2日 10:58
收件人: ant-design/ant-design-mobile <ant-design-mobile@noreply.github.com&gt;
抄送: forguo <wforguo@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design-mobile] SearchBar第一次加载完成之后，需要点击两三次才能输入 (#3507)




解决了吗？InputItem组件也是需要多次才能聚焦

**Comment by wforguo** [comment]
没解决





------------------ 原始邮件 ------------------
发件人: nodemirai <notifications@github.com&gt;
发送时间: 2019年12月30日 17:51
收件人: ant-design/ant-design-mobile <ant-design-mobile@noreply.github.com&gt;
抄送: forguo <wforguo@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design-mobile] SearchBar第一次加载完成之后，需要点击两三次才能输入 (#3507)




同学你解决了吗，我这边也有这种情况，searchbar单独写了个demo就没这种情况

**Comment by dinglino1** [comment]
我暂时是加了一个点击事件然后自动聚焦            
onClick={()=>{this.focusInst.focus();}}

**Comment by NodeMirai** [comment]
@wforguo @dinglino1 是不是引入fasfclick了，这个问题和antd没关系

**Comment by NodeMirai** [comment]
@wforguo @dinglino1     在script标签里添加这个试试
`FastClick.prototype.focus = function(targetElement) {
    targetElement.focus();
  };`

**Comment by wforguo** [comment]
去了<script src="https://as.alipayobjects.com/g/component/fastclick/1.0.6/fastclick.js"></script>

就正常了

**Comment by awmleer** [comment]
v5 不再依赖 FastClick 了
