### ISSUE TITLE
请问各位大佬modal组件该如何使用服务方式创建 popup 弹窗

### ISSUE THREAD

**Issue by xmenbe** [ant-design/ant-design-mobile#3508]
请问各位大佬modal组件该如何使用服务方式创建 popup
![image](https://user-images.githubusercontent.com/41034951/71578257-5bfeb600-2b32-11ea-8d01-e55b1bc6ae05.png)
从官方文档没有找到方法，自己点出来的ModalService.showPopup（），但不知道具体该如何使用，向各位请教一下

**Comment by xiaohuoni** [comment]
ModalService 哪来的？文档中应该没有体现它！
