### ISSUE TITLE
InputItem组件无法聚焦

### ISSUE THREAD

**Issue by dinglino1** [ant-design/ant-design-mobile#3509]
按照官方引入了  <script src="https://as.alipayobjects.com/g/component/fastclick/1.0.6/fastclick.js"></script>然后InputItem组件无法聚焦，去掉以后也是需要多次才能聚焦

**Comment by riddler2** [comment]
如果按照官方文档使用了FastClick.js,请添加以下代码阻止其默认focus事件

FastClick.prototype.focus = function (targetElement) {
  let length;
  if (targetElement.setSelectionRange && targetElement.type.indexOf('date') !== 0 && targetElement.type !== 'time' && targetElement.type !== 'month') {
    length = targetElement.value.length;
    targetElement.focus();
    targetElement.setSelectionRange(length, length);
  } else {
    targetElement.focus();
  }
}
![878C300A-2991-4156-9557-9230D8181923](https://user-images.githubusercontent.com/45554114/98903914-7c89f180-24f3-11eb-8920-4fdc1d2a2869.png)
