### ISSUE TITLE
Icon图标不正常

### ISSUE THREAD

**Issue by zhwb36** [ant-design/ant-design-mobile#351]
#### 本地环境

- antd-mobile 版本：0.9.1
- 操作系统及其版本：win10
- 浏览器及其版本：chrome 52
#### 你做了什么？

`<Button><Icon type="reload" />刷新</Button>`
#### 你期待的结果是：

像官网一样显示 
#### 实际上的结果：

![image](https://cloud.githubusercontent.com/assets/6262994/19226229/1a46f6c4-8edb-11e6-9b7b-7a2eb58c4eab.png)

图标显示为乱码符

但iphone 6s Safari显示正常

**Comment by warmhug** [comment]
图标建议项目中自己先用 图片/svg 等代替、兼容性更好。目前的图标将用 svg 替换，解决掉兼容问题 #156

**Comment by zhwb36** [comment]
图标用svg替换，什么时候能发布？

**Comment by warmhug** [comment]
尽量在这个月底前

**Comment by warmhug** [comment]
1.0.0-alpha 已经替换成 svg 图标，欢迎尝试。
