### ISSUE TITLE
请问DatePicker如何手动设置下拉列表的内容呀？

### ISSUE THREAD

**Issue by 419280377** [ant-design/ant-design-mobile#3510]
我想把DatePicker设置成只有"MM-DD HH:mm"的形式，没找到相关属性，请问能设置吗？
![image](https://user-images.githubusercontent.com/20454290/71720989-73a1ab80-2e5e-11ea-97ec-780ef7767bb2.png)

**Comment by SilvesterChiao** [comment]
试试locale属性

**Comment by awmleer** [comment]
v2 已经停止维护了，建议升级到 v5 吧
