### ISSUE TITLE
使用的 post2rem  部分安卓手机 pullToRefresh 上拉加载更多失效  求助

### ISSUE THREAD

**Issue by ITZengWei** [ant-design/ant-design-mobile#3512]
使用的 post2rem  部分安卓手机 pullToRefresh 上拉加载更多失效  求助, 谷歌模拟 是可以的

**Comment by xiaohuoni** [comment]
部分安卓手机？是指什么？给个重现demo

**Comment by liangzhuang327** [comment]
[你看看我的这个问题是否适用你](https://github.com/ant-design/ant-design-mobile/issues/3521)

**Comment by Web-Delevan** [comment]
> 部分安卓手机？是指什么？给个重现demo

官方pullToRefresh up demo在Android9和10微信浏览器内无法上拉，Android8可以，ios没问题

**Comment by Web-Delevan** [comment]
> 部分安卓手机？是指什么？给个重现demo

官方pullToRefresh up demo在Android9和10微信浏览器内无法上拉，Android8可以，ios没问题

**Comment by Web-Delevan** [comment]
> > 部分安卓手机？是指什么？给个重现demo
> 
> 官方pullToRefresh up demo在Android9和10微信浏览器内无法上拉，Android8可以，ios没问题

非X5内核引起的，开启X5内核就没问题了....

**Comment by awmleer** [comment]
v2 已经停止维护了，建议升级到 v5 吧
