### ISSUE TITLE
Tabs 属性 swipeable={false} 安卓系统无效

### ISSUE THREAD

**Issue by yuanbolin** [ant-design/ant-design-mobile#3513]

**Comment by wuaonan** [comment]
追加 usePaged={false}

**Comment by yxiawen** [comment]
我也遇到同样的问题

**Comment by yxiawen** [comment]
我也遇到同样的问题
![image](https://user-images.githubusercontent.com/21170741/91274671-a283dd80-e7b1-11ea-9f83-744e8c05c519.png)

**Comment by yxiawen** [comment]
我也是同样的问题
![image](https://user-images.githubusercontent.com/21170741/91274738-bb8c8e80-e7b1-11ea-8646-ef48d0527349.png)
swipeable值为false了还是能滑动

**Comment by awmleer** [comment]
v2 已经停止维护了，建议升级到 v5 吧
