### ISSUE TITLE
跑仓库内的web项目报错

### ISSUE THREAD

**Issue by dancinglone** [ant-design/ant-design-mobile#352]
#### 本地环境

windows 10 
npm 2.5.18
node 4.4.7

- antd-mobile 版本：    10月10日拉的版本
- 操作系统及其版本：
- 浏览器及其版本：
#### 你做了什么？

想跑一下demo项目，按这个步骤：
https://github.com/ant-design/ant-design-mobile/blob/master/development.md
跑web的

#### 实际上的结果：

`ERROR in ./~/bisheng/tmp/entry.index.js
Module not found: Error: Cannot resolve module 'C:UsersDCLDocumentsdclgitant-design-mobilesite  he                             me/template/NotFound' in C:\Users\DCL\Documents\dcl\git\ant-design-mobile\node_modules\bisheng\tmp
 @ ./~/bisheng/tmp/entry.index.js 14:15-96

ERROR in ./~/bisheng/lib/utils/data.js
Module parse failed: C:\Users\DCL\Documents\dcl\git\ant-design-mobile\node_modules\bisheng\lib\loa                             ders\bisheng-data-loader.js?config=C:\Users\DCL\Documents\dcl\git\ant-design-mobile\site\bisheng.c                             onfig.js!C:\Users\DCL\Documents\dcl\git\ant-design-mobile\node_modules\bisheng\lib\utils\data.js L                             ine 53: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
|   });
| },
|   'components\badge\demo\99plus': function () {
|   return new Promise(function (resolve) {
|     require.ensure([], function (require) {
 @ ./~/bisheng/tmp/entry.index.js 15:11-42

ERROR in ./~/bisheng/tmp/entry.index.js
Module not found: Error: Cannot resolve module 'C:UsersDCLDocumentsdclgitant-design-mobilesite  he                             me' in C:\Users\DCL\Documents\dcl\git\ant-design-mobile\node_modules\bisheng\tmp
 @ ./~/bisheng/tmp/entry.index.js 51:17-129

ERROR in ./~/bisheng/tmp/entry.index.js
Module not found: Error: Cannot resolve module 'C:UsersDCLDocumentsdclgitant-design-mobilesite  he                             me' in C:\Users\DCL\Documents\dcl\git\ant-design-mobile\node_modules\bisheng\tmp
 @ ./~/bisheng/tmp/entry.index.js 70:12-75

ERROR in ./~/bisheng/tmp/entry.kitchen-sink.js
Module not found: Error: Cannot resolve module 'C:UsersDCLDocumentsdclgitant-design-mobilesitemobi                             le/template/NotFound' in C:\Users\DCL\Documents\dcl\git\ant-design-mobile\node_modules\bisheng\tmp
 @ ./~/bisheng/tmp/entry.kitchen-sink.js 14:15-96

ERROR in ./~/bisheng/tmp/entry.kitchen-sink.js
Module not found: Error: Cannot resolve module 'C:UsersDCLDocumentsdclgitant-design-mobilesitemobi                             le' in C:\Users\DCL\Documents\dcl\git\ant-design-mobile\node_modules\bisheng\tmp
 @ ./~/bisheng/tmp/entry.kitchen-sink.js 51:17-129

ERROR in ./~/bisheng/tmp/entry.kitchen-sink.js
Module not found: Error: Cannot resolve module 'C:UsersDCLDocumentsdclgitant-design-mobilesitemobi                             le' in C:\Users\DCL\Documents\dcl\git\ant-design-mobile\node_modules\bisheng\tmp
 @ ./~/bisheng/tmp/entry.kitchen-sink.js 70:12-75
`

**Comment by yiminghe** [comment]
npm3

**Comment by dancinglone** [comment]
好的，我试试看看
