### ISSUE TITLE
Modal.alert is called multiple times and will display multiple

### ISSUE THREAD

**Issue by Fullsize** [ant-design/ant-design-mobile#3522]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/modal-cn/](https://mobile.ant.design/components/modal-cn/)

### Steps to reproduce
called in a method (method may be executed multiple times)

### What is expected?
show only once

### What is actually happening?
show multiple popups

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by awmleer** [comment]
v2 已经停止维护了，建议升级到 v5 吧
