### ISSUE TITLE
ListView下拉刷新样式异常

### ISSUE THREAD

**Issue by robinv8** [ant-design/ant-design-mobile#3523]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://tva1.sinaimg.cn/large/006tNbRwly1gb0oer42xdg308c0euq83.gif](https://tva1.sinaimg.cn/large/006tNbRwly1gb0oer42xdg308c0euq83.gif)

### Steps to reproduce
下拉刷新样式异常

### What is expected?
期望..am-pull-to-refresh-content-wrapper 删除样式 overflow: hidden,使其下拉操作底部样式不受影响

### What is actually happening?
下拉刷新，显示断层

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | react |
| System | 所有 |
| Browser | 所有 |

**Comment by wyl530197181** [comment]
最后是怎么处理的 下拉断层的问题

**Comment by zyanfly** [comment]
同问，解决了吗？
