### ISSUE TITLE
在微信浏览器环境中 tabs组件下的InputItem 组件没有下边框

### ISSUE THREAD

**Issue by xiaminxi** [ant-design/ant-design-mobile#3527]
![微信图片没有边框](https://user-images.githubusercontent.com/37994820/73820425-b7f0e480-482c-11ea-9cee-ef95bd1abc61.jpg)

**Comment by xiaohuoni** [comment]
是否使用List 包裹？

**Comment by xiaohuoni** [comment]
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN
