### ISSUE TITLE
antd及antd-mobile共用问题

### ISSUE THREAD

**Issue by carlos121493** [ant-design/ant-design-mobile#353]
#### 本地环境

- antd-mobile 版本：0.9
- 操作系统及其版本：mac
- 浏览器及其版本：

#### 你做了什么？
用高清方案后
antd和antd-mobile共用的时候会有问题
![](https://zos.alipayobjects.com/rmsportal/pFTfZFyqEqVpQtd.png)
antd或者第三方用px的话都会缩小一倍，能不能以基准dpi为1来做，这样将所有的px转为rem就正常了。

**Comment by carlos121493** [comment]
发现只要这样
```
webpackConfig.postcss.push(pxtorem({
    rootValue: 100,
    propWhiteList: [],
    selectorBlackList: [/^\.ant-/],
  }));
```
就好了

**Comment by pingan1927** [comment]
好了就关了。

**Comment by guangming21** [comment]
antd与antd-mobile怎么共用

**Comment by guangming21** [comment]
@pingan1927 antd与antd-mobile怎么共用

**Comment by pingan1927** [comment]
一个repo里，既有PC页面，也有H5页面。引入两个库，该怎么用怎么用...
