### ISSUE TITLE
Action Sheet not visible when opened in Modal in Safari (iOS/MacOS)

### ISSUE THREAD

**Issue by hexsprite** [ant-design/ant-design-mobile#3532]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-cache-x1bfb)

### Steps to reproduce
- in a modal, request an action sheet

### What is expected?
In Chrome it shows the Action Sheet over the modal.

### What is actually happening?
In Safari (iOS/MacOS) the Action Sheet is not visible.

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.12.0 |
| System | MacOS 10.14.6 |
| Browser | 13.0.5 |

---
It seems related to the translateZ parameter. When I add a translateZ parameter to the action sheet it works.

**Comment by hexsprite** [comment]
Confirmed that adding:

```
.am-action-sheet-mask, .am-action-sheet-wrap
  transform: translateZ(1px)
```

Solves the issue for me

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
