### ISSUE TITLE
ant-design-mobile 缺少form组件，为什么不提供一个form组件呢

### ISSUE THREAD

**Issue by xuanxuan321** [ant-design/ant-design-mobile#3533]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表单组件值的校验以及收集

### What does the proposed API look like?
同antd的form

**Comment by xuanxuan321** [comment]
可以私用rc-form来实现，官方文档里面有写

**Comment by NsNe** [comment]
同问，为啥没有 form， formitem ？ 想要和formliy结合一起 😢
