### ISSUE TITLE
Chinese language selected as default in the documentation 

### ISSUE THREAD

**Issue by alikadir** [ant-design/ant-design-mobile#3535]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/calendar?lang=en-US#calendar-demo-0](https://mobile.ant.design/kitchen-sink/components/calendar?lang=en-US#calendar-demo-0)

### Steps to reproduce
0

### What is expected?
all of documentation to be in english language

### What is actually happening?
at the documentation, some component in chinese language
example https://mobile.ant.design/kitchen-sink/components/calendar?lang=en-US#calendar-demo-0

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | 0 |
| System | 0 |
| Browser | 0 |

**Comment by awmleer** [comment]
We'll make sure all the documentation has an English version. For v2 documentation site, it is no longer maintained. And for v5, we are still translating it.
