### ISSUE TITLE
While using Tabs: getting Warning componentWillReceivedProps has been renamed

### ISSUE THREAD

**Issue by lovelyKarthi** [ant-design/ant-design-mobile#3536]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://- node_modules/@ant-design/react-native/lib/tabs/Tabs.ts](http://- node_modules/@ant-design/react-native/lib/tabs/Tabs.ts)

### Steps to reproduce
common issues for this version

### What is expected?
componentWillReceivedProps warning should not come

### What is actually happening?
componentWillReceivedProps has been renamed is not recommended for use

| Environment | Info |
|---|---|
| antd | 3.2.2 |
| React | 0.61.5 |
| System | Android |
| Browser | Android App |

**Comment by lovelyKarthi** [comment]
My code const HomeScreen = (props, navigation) => {

        const tabs = [
            {title: 'First test'},
            {title: 'Second Tab'},
            {title: 'Third Tab'},
        ];
        return (
                <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
                    <Tabs tabs={tabs} initialPage={0} prerenderingSiblingsNumber={0} tabBarPosition={'bottom'}>
                        <View style={[Styles.flex1, {height: 100}]}>
                            <Text>Content of First Tab dfdfsdffsdf </Text>
                        </View>
                        <View style={[Styles.flex1, {height: 100}]}>
                            <Text>Content of Second Tab</Text>
                        </View>
                        <View style={[Styles.flex1, {height: 100}]}>
                            <Text>Content of Third Tab</Text>
                        </View>
                    </Tabs>
                <Button
                    title="Go to About"
                    onPress={() => navigation.navigate('About')}
                />
                </View>
        );
};
![WhatsApp Image 2020-02-13 at 3 29 43 PM](https://user-images.githubusercontent.com/20126427/74423100-b3a07900-4e75-11ea-96ad-cc0666043ecd.jpeg)

**Comment by awmleer** [comment]
Seem like you are using ant-design-mobile-rn?
Please consider opening an issue in this repo: https://github.com/ant-design/ant-design-mobile-rn
