### ISSUE TITLE
The Calendar component can't slide down to load last month sometimes，especially in iphone

### ISSUE THREAD

**Issue by ZhaiXiaoyuan** [ant-design/ant-design-mobile#3544]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/calendar-cn/](https://mobile.ant.design/components/calendar-cn/)

### Steps to reproduce
Open the calendar and slide down

### What is expected?
Slide down to load last month sensitively

### What is actually happening?
Can't slide down to load last month sometimes

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.10.2 |
| System | IOS |
| Browser | safari |

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
