### ISSUE TITLE
Adding locale de_DE

### ISSUE THREAD

**Issue by tkempken** [ant-design/ant-design-mobile#3547]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Missing locale support for de_DE

### What does the proposed API look like?
Raised pull request 3545 with necessary changes

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.

However, v5 hasn't supported de_DE yet either. If you'd like to help us translating, you can add a locale pack here: https://github.com/ant-design/ant-design-mobile/tree/master/src/locales
