### ISSUE TITLE
Picker & DatePicker in React 16.13.0 has bug

### ISSUE THREAD

**Issue by Chryseis** [ant-design/ant-design-mobile#3548]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/billowing-platform-ggtf9)

### Steps to reproduce
直接点击Picker

### What is expected?
关闭时出现弹框向下的动画

### What is actually happening?
关闭时不会产生动画

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.13.0 |
| System | mac |
| Browser | chrome 80.0.3987.122 |

**Comment by awmleer** [comment]
v2 已经停止维护了，建议升级到 v5 吧
