### ISSUE TITLE
都是用的click 事件， 不用考虑300ms延迟吗?

### ISSUE THREAD

**Issue by huiop368** [ant-design/ant-design-mobile#355]
## 环境:
在支付宝容器里跑的h5应用, 主要是用 ant-mobile搭的...

## 问题:
1. 像 nav-bar 组件的 onLeftClick, 组件里看都是直接绑 onClick,  发现是有延迟现象的.
2. action-sheet展现过渡的动画，在容器里面没有过渡动画

请问是有啥考究？ 还是我哪里搞错啦?

谢谢~!!

**Comment by warmhug** [comment]
项目中自己引用 Fastclick 库

**Comment by huiop368** [comment]
好的，果然是得 额外引~!!  谢谢~!!

**Comment by huiop368** [comment]
然后 第2个问题有啥 线索吗?

**Comment by warmhug** [comment]
我用支付宝和手淘扫码查看，action-sheet 动画没问题

**Comment by silentcloud** [comment]
是不是没有引用到动画样式？看看有没有 anim.less 里的 css @huiop368

**Comment by huiop368** [comment]
用的是  simulator 模拟的 iPhone 6s, 支付宝版本装的是 9.93
(动画样式应该是加载到的)

1. 同一应用在浏览器里 动画是没问题的
2. 用simulator 安装的guoguo open 这个应用地址， 也是有动画的..  (真的醉了)

我再测几种情况看看....
