### ISSUE TITLE
ListView 第一次加载条数过少，渲染界面未超过屏幕，不能进行滑动加载

### ISSUE THREAD

**Issue by ZhangNanBin** [ant-design/ant-design-mobile#3553]
ListView 第一次加载条数过少，渲染界面未超过屏幕，界面不能滑动， 触发不了onEndReached事件

重现链接
<https://codepen.io/zhangnanbin/pen/RwPZeyg?editable=true&editors=001>

**Comment by action-hong** [comment]
老哥你这个问题解决了吗 @ZhangNanBin

**Comment by ZhangNanBin** [comment]
> 老哥你这个问题解决了吗@ZhangNanBin

没有呢

**Comment by yang200258** [comment]
请问解决了没？我也遇到这个问题了

**Comment by yang200258** [comment]
已找到解决方案：
获取到ListView的offsetTop，如果第一次加载后还是0，再次调用加载数据函数，直到超出屏幕，即offsetTop>0

**Comment by renrenguiwei** [comment]
```
componentDidMount() {
    // 此处省略加载、渲染数据
    const element = document.querySelector('.listview-style')
    if (element instanceof HTMLElement) {
        console.log(element.offsetTop)
    }
}
```
假如规定分页后1页有3条数据，offsetTop获取不为0，还是不能进行上拉加载啊！
![image](https://user-images.githubusercontent.com/7834109/97067688-a9cd3900-15f2-11eb-851a-6d1979dca97b.png)

**Comment by yang200258** [comment]
> ```
> componentDidMount() {
>     // 此处省略加载、渲染数据
>     const element = document.querySelector('.listview-style')
>     if (element instanceof HTMLElement) {
>         console.log(element.offsetTop)
>     }
> }
> ```
> 
> 假如规定分页后1页有3条数据，offsetTop获取不为0，还是不能进行上拉加载啊！
> ![image](https://user-images.githubusercontent.com/7834109/97067688-a9cd3900-15f2-11eb-851a-6d1979dca97b.png)

用的时机不对，需要监听，如果不为0，就一直模拟下拉加载的函数

**Comment by renrenguiwei** [comment]
> > ```
> > componentDidMount() {
> >     // 此处省略加载、渲染数据
> >     const element = document.querySelector('.listview-style')
> >     if (element instanceof HTMLElement) {
> >         console.log(element.offsetTop)
> >     }
> > }
> > ```
> > 
> > 
> > 假如规定分页后1页有3条数据，offsetTop获取不为0，还是不能进行上拉加载啊！
> > ![image](https://user-images.githubusercontent.com/7834109/97067688-a9cd3900-15f2-11eb-851a-6d1979dca97b.png)
> 
> 用的时机不对，需要监听，如果不为0，就一直模拟下拉加载的函数

能上下代码吗？

**Comment by yang200258** [comment]
> > > ```
> > > componentDidMount() {
> > >     // 此处省略加载、渲染数据
> > >     const element = document.querySelector('.listview-style')
> > >     if (element instanceof HTMLElement) {
> > >         console.log(element.offsetTop)
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > > 假如规定分页后1页有3条数据，offsetTop获取不为0，还是不能进行上拉加载啊！
> > > ![image](https://user-images.githubusercontent.com/7834109/97067688-a9cd3900-15f2-11eb-851a-6d1979dca97b.png)
> > 
> > 
> > 用的时机不对，需要监听，如果不为0，就一直模拟下拉加载的函数
> 
> 能上下代码吗？

useEffect(() => {
    // 解决ListView初始化数据未占满屏幕无法下拉刷新问题
    if (viewElement?.current && !last && pageIndex === 0 && isLess) {
      // eslint-disable-next-line react/no-find-dom-node
      const dom = findDOMNode(viewElement.current);
      if (dom.offsetTop === 0) {
        setIsLoading(true);
        getListFunc(pageIndex += 1);
        setIsLoading(false);
      }
    }
    // 初始化数据
    setDataSource(dataSource.cloneWithRows(data));
    setIsLess(true);
  }, [data]);

**Comment by awmleer** [comment]
v5 不存在这个问题了
