### ISSUE TITLE
(严重)Modal.prompt离场动画在react 16版本之后都不会产生效果

### ISSUE THREAD

**Issue by Chryseis** [ant-design/ant-design-mobile#3555]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-meitner-nsou1)

### Steps to reproduce
点击按钮

### What is expected?
产生离场动画

### What is actually happening?
离场动画失效

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | >=16 |
| System | mac |
| Browser | chrome 80.0.3987.122 |

**Comment by awmleer** [comment]
v2 已经停止维护了，建议升级到 v5 吧
