### ISSUE TITLE
toast 中文和数组较多时，会出现混乱

### ISSUE THREAD

**Issue by yulingyiyi** [ant-design/ant-design-mobile#3556]
Toast.show("【CSAE7582734782934728347293478234239492423492348294】就按技能大师大师大都是拿上来的那句是的那老师都拿的卡老师你的啦·脑残的辣酸奶·");

【CSAE7582734782934728347293478234239492423492348294】 显示会超出弹窗范围

**Comment by awmleer** [comment]
v2 已经停止维护了，建议升级到 v5 吧
