### ISSUE TITLE
Upgrade core-js version to 3.x

### ISSUE THREAD

**Issue by chen86860** [ant-design/ant-design-mobile#3558]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The version of core-js below 3.0 is no longer maintained, upgrade newest version for support as soon as.

### What does the proposed API look like?
None

**Comment by awmleer** [comment]
2.x is no longer maintained. And 5.x doesn't depends on core-js.
