### ISSUE TITLE
InputItem type=phone 输入时闪烁

### ISSUE THREAD

**Issue by daisybaicai** [ant-design/ant-design-mobile#3559]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item?lang=zh-CN#input-item-demo-0](https://mobile.ant.design/kitchen-sink/components/input-item?lang=zh-CN#input-item-demo-0)

### Steps to reproduce
手机打开链接，找到手机号输入框，输入时键盘部分频繁闪烁

### What is expected?
跟普通输入一样，无闪烁

### What is actually happening?
频繁闪烁

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.9 |
| System | ios |
| Browser | 手机浏览器 |

**Comment by Cooper-beiyuan** [comment]
闪烁不好吗？

**Comment by daisybaicai** [comment]
![20200311_sight_390182](https://user-images.githubusercontent.com/25605435/76388806-ef5f2d80-63a4-11ea-9473-ebda8a19be76.gif)

**Comment by xiaohuoni** [comment]
这是 ios 系统的问题吧。同时存在一个 password input 和tel input 的时候就会闪。
