### ISSUE TITLE
checkbox可以自定义样式吗

### ISSUE THREAD

**Issue by guangming21** [ant-design/ant-design-mobile#356]
#### 本地环境

- antd-mobile 版本：0.8.6
- 操作系统及其版本：win10
- 浏览器及其版本：谷歌

#### 你做了什么？

引入checkbox多选框

#### 你期待的结果是：

多选框样式可以做成单选框那样的
![qq 20161011100641](https://cloud.githubusercontent.com/assets/18028721/19256536/7477f124-8f9a-11e6-9e63-c0118f93ae51.png)

#### 实际上的结果：
![qq 20161011100307](https://cloud.githubusercontent.com/assets/18028721/19256518/47a5ec50-8f9a-11e6-883b-d4663ee79256.png)

**Comment by pingan1927** [comment]
现有的组件是可以支持的，还可以直接使用`Radio`，而不是封装好的`RadioItem`
```
import { List, Radio } from 'antd-mobile';

const RadioItem = Radio.RadioItem;

const Test = React.createClass({
  getInitialState() {
    return {
      checked: false,
    };
  },
  handleChange(e) {
    this.setState({
      checked: !this.state.checked,
    });
  },
  render() {
    return (
      <div>
        <List
          renderHeader={() => '请选择学历'}
        >
          <RadioItem
            checked={this.state.checked}
            onChange={(e) => {this.handleChange(e);}}
          >
            博士
          </RadioItem>
        </List>
      </div>
    );
  },
});

ReactDOM.render(<Test />, mountNode);
```
