### ISSUE TITLE
Table passive touch event preventing

### ISSUE THREAD

**Issue by maxminty** [ant-design/ant-design-mobile#3561]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
Open chrome console -> Toggle device toolbar (Doing it to simulate touch actions).
Try to scroll the page via dragging a table.

### What is expected?
Everything working fine, a console is clear

### What is actually happening?
You`ll get a lot of same error in a console - [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome |

---
I note sure, will it affect any performance, but this is looking not OK.
Should be simply fixed via changing event adding
```
window.addEventListener('touchmove', func, { passive: false })
```

**Comment by awmleer** [comment]
This is the repo of `antd-mobile` and seems the issue is about `antd`.
