### ISSUE TITLE
DatePicker返显在安卓正常，在ios表现为NaN-NaN

### ISSUE THREAD

**Issue by guozhenqianga** [ant-design/ant-design-mobile#3563]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://hbzx.ictbda.com/office/](http://hbzx.ictbda.com/office/)

### Steps to reproduce
进入用户信息，填写信息提交，再进来，（身份证可以用模拟身份证号）返程时间为NaN-NaN

### What is expected?
正常显示

### What is actually happening?
日期显示正常

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.13.0 |
| System | IOS |
| Browser | qq扫一扫 |

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/83367859-316a9f00-a3e9-11ea-80f4-2278c83e3900.png)
没法重现。

**Comment by wannagu** [comment]
ios不支持 2020-06-04 这种格式，先转成 2020/06/04再转成时间戳就可以

**Comment by awmleer** [comment]
v2 已经停止维护了，建议升级到 v5 吧
