### ISSUE TITLE
InputItem类型定义冲突

### ISSUE THREAD

**Issue by rainmanhhh** [ant-design/ant-design-mobile#3565]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-antd-typescript-t4rkb)

### Steps to reproduce
定义函数function wrap<T>(comp: ComponentType<T>) {}，传入InputItem

### What is expected?
编译通过

### What is actually happening?
编译错误

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.13.0 |
| System | win10 |
| Browser | chrome80 |

---
建议将InputItem.defaultProps中的type: string;改为type: InputItemPropsType['type']

**Comment by rainmanhhh** [comment]
ref的类型定义也冲突

**Comment by awmleer** [comment]
v2 已经停止维护了，建议升级到 v5 吧
