### ISSUE TITLE
库不再更新了吗？会不会出hooks版本？

### ISSUE THREAD

**Issue by pcjser** [ant-design/ant-design-mobile#3567]

**Comment by DongShi** [comment]
Same question, is this lib still alive?

**Comment by 10086XIAOZHANG** [comment]
react hooks typescript 版本移动端组件库 https://github.com/10086XIAOZHANG/CP-DESIGN

**Comment by xiaohuoni** [comment]
你指的hooks版本是什么意思呢？

**Comment by running-snail-sfs** [comment]
pc版本不是出了吗？移动端这个更新真的慢

**Comment by shopshow** [comment]
同问，希望能出hooks版本

**Comment by awmleer** [comment]
已出：http://next.mobile.ant.design
