### ISSUE TITLE
Flutter version please.

### ISSUE THREAD

**Issue by a3596287** [ant-design/ant-design-mobile#3568]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Flutter becomes more and more popular, and it's over taken React Native. 

We want to develop on Flutter, therefore need UI kit for Flutter. 

Like Ant Design very much, don't want to use other alternatives.

### What does the proposed API look like?
same as Native API will be fine.

**Comment by xiaohuoni** [comment]
暂时应该没有这个打算。

**Comment by OrionWambert** [comment]
Is there anything planned regarding the development of a flutter version for the ant design?

**Comment by edwardchew97** [comment]
如果能够支持flutter那真的是极好的。Flutter的应用增长非常快。而Ant Design的组件也非常优美，容易上手。可能的话，真的希望Ant Design团队能考虑支持flutter，万分感激！

**Comment by hhstore** [comment]
> here is Ant Design for RN: 

- https://github.com/ant-design/ant-design-mobile-rn
- https://rn.mobile.ant.design/index-cn

> Would anyone be interested in implementing a version of flutter based on the above project?

> Or are there other similar alternatives?

**Comment by awmleer** [comment]
There is no plan for flutter version of antd-mobile currently. Since the technology they use differs quite a lot, building a flutter version antd-mobile is almost like building another project.

**Comment by xyun52** [comment]
什么时候支持 flutter web 和 flutter desktop

**Comment by pd4d10** [comment]
Recently I've been trying to implement a Flutter version of antd-mobile, mainly for use in my app [GitTouch](https://github.com/git-touch/git-touch).

Repo here: https://github.com/pd4d10/ant-design-mobile-flutter

Just noticed this issue, and hope it will be helpful to you. It's still in early stages, and I'll probably keep maintaining it. And also, welcome to contribute together!
