### ISSUE TITLE
Toast.loading onClose的回调中再调用Toast.info， 会报错

### ISSUE THREAD

**Issue by DualWield** [ant-design/ant-design-mobile#3574]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-mahavira-dbnum)

### Steps to reproduce
正常打开

### What is expected?
没有报错

### What is actually happening?
报错：
NotFoundError  Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node

| Environment | Info |
|---|---|
| antd | 2.3.1 |
| React | 16.12 |
| System | macos |
| Browser | chrome |

**Comment by xiaohuoni** [comment]
应该是共用同一个节点的问题。试试延时调用 `Toast.info`
```
  setTimeout(()=>{
    Toast.info('反馈成功')
  },100)
```

**Comment by BruceCham** [comment]
```js
onClose: function onClose() {
                if (_onClose) {
                    _onClose();
                }
                notification.destroy();
                notification = null;
                messageInstance = null;
            }
```
执行 _onClose 之后，在部分业务场景中destroy操作的节点已经不存在了，没有做兼容

**Comment by awmleer** [comment]
v2 已经停止维护了，建议升级到 v5 吧
