### ISSUE TITLE
小米9 SE imagePicker 组件 拍照，会造成页面回退，官方demo能重现

### ISSUE THREAD

**Issue by beysong** [ant-design/ant-design-mobile#3575]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/image-picker](https://mobile.ant.design/kitchen-sink/components/image-picker)

### Steps to reproduce
imagePicker组件，上传图片，选择拍照

### What is expected?
正常上传图片

### What is actually happening?
造成页面回退

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.12 |
| System | 安卓 |
| Browser | 微信内置浏览器 |

**Comment by Web-Delevan** [comment]
这个问题有没有解决？

**Comment by awmleer** [comment]
试下 v5 的 ImageUploader 组件吧

**Comment by zhuchuanlei** [comment]
5.28.0版，也会出现闪退呀
