### ISSUE TITLE
ImagePicker组件，限制选择图片数量上限（selectable={images.length < 3} ）失败

### ISSUE THREAD

**Issue by GoodnIght-CG** [ant-design/ant-design-mobile#3577]
通过 selectable={images.length < 3} 限制了选择图片数量的上限为3，但是设置了 multiple={true} 属性，用户可以一次性大于3张图片，这样就突破了图片上限。代码如下：
`
<ImagePicker
	files={files}
	onChange={this.onChange}
        selectable={images.length < 3}
        length={3}
	multiple={true}
/>
`

**Comment by xiaohuoni** [comment]
试试
```
selectable={files.length < 3}
```

**Comment by yxrgds** [comment]
> 通过 selectable={images.length < 3} 限制了选择图片数量的上限为3，但是设置了 multiple={true} 属性，用户可以一次性大于3张图片，这样就突破了图片上限。代码如下：
> `<ImagePicker files={files} onChange={this.onChange} selectable={images.length < 3} length={3} multiple={true} />`

在onChange事件里面加校验
`
              <ImagePicker
                multiple
                files={files}
                onChange={this.pictureOnChange}
                selectable={files.length < 10}
              />

  pictureOnChange = (files: {}[], operationType: string) => {
    let allowedFiles = files;
    if (operationType === 'add') {
      const fileTooBig = files.some((file: any) => file.file.size > 1024 * 1000 * 10);
      if (fileTooBig) {
        notification.error({
          message: '上传图片大小不可超过10M',
        });
        allowedFiles = files.filter((file: any) => file.file.size <= 1024 * 1000 * 10);
      }
      if (allowedFiles.length > 10) {
        notification.error({
          message: '最多上传10张图片',
        });
        allowedFiles = allowedFiles.slice(0, 10);
      }
    }
    this.setState({
      files: allowedFiles,
    });
  }
`

**Comment by baixiaoshi** [comment]
如何解决的

**Comment by awmleer** [comment]
试下 v5 的 ImageUploader 组件吧
