### ISSUE TITLE
DatePicker组件BUG

### ISSUE THREAD

**Issue by LayGit** [ant-design/ant-design-mobile#358]
#### 本地环境

- antd-mobile 版本：0.8.7
- 操作系统及其版本：iOS 10.0.2
- 浏览器及其版本：微信内置浏览器

#### 你做了什么？

限制了选择时间从明天开始，例如 2016年10月12日，最大限制到50年后的今天 2066年10月11日

点击日历选择控件（第一次）

这时候滚动年份到2017年，发现月份自动跑到3月去了，日还是没变12日。

点击确定，选择的时间是 2017年10月12日，然而日历控件上显示的是 2017年3月12日。

再次点击日历选择就没有这个问题了。

#### 你期待的结果是：

月份显示正常

#### 实际上的结果：

月份显示错误

#### 可重现的在线演示

步骤一：
![image](https://cloud.githubusercontent.com/assets/6624161/19256816/e51d433c-8f9c-11e6-9302-58c29ad23c45.png)

步骤二：
![image](https://cloud.githubusercontent.com/assets/6624161/19256827/fad74830-8f9c-11e6-87a1-c52a8386ac46.png)

步骤三：
![image](https://cloud.githubusercontent.com/assets/6624161/19256962/6707dfa0-8f9e-11e6-8a15-ff3e4ae6f716.png)

**Comment by warmhug** [comment]
在最小时间和正常时间之间切换年份时、月份的变化不对。最大时间也是这样。 @yiminghe

**Comment by yiminghe** [comment]
fixed.

重装

**Comment by motorguo** [comment]
@warmhug 在使用 `DatePicker` 遇到个小问题 ， `mode` 怎样才能支持 [YearMonth](https://ant.design/components/date-picker-cn/#MonthPicker),   `format` 也不管用。


[mode -- The date picker mode. -- String -- 'date' enum('date', 'time', 'datetime')](https://github.com/react-component/m-date-picker#datepicker-props)

![76 5 t k jvl g 39pvkoos](https://cloud.githubusercontent.com/assets/16831715/21517619/66c1ffac-cd1b-11e6-8418-ffe4a32fa153.png)
