### ISSUE TITLE
imagepicker 在android 手机中偶尔点击没反映，也不报错

### ISSUE THREAD

**Issue by pikeCol** [ant-design/ant-design-mobile#3580]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/image-picker-cn/](https://mobile.ant.design/components/image-picker-cn/)

### Steps to reproduce
点击image-picker组建偶尔会没有反应

### What is expected?
点击image-picker能稳定得到响应

### What is actually happening?
在android webview总大部分点击image-picker组建能得到响应，弹出图片选择的页面，但是点击image-picker组建偶尔会没有反应

| Environment | Info |
|---|---|
| antd | 2.2.6 |
| React | react 16.8.2 |
| System | android |
| Browser | android webview |

---
<List>
  <Item multipleLine>
    上传凭证:
    <Brief>
      <ImagePicker files={this.state.files}
        onChange={(files, type, index) => this.onUploadFileChange(files, type, index)}
        selectable={this.state.files.length < 4}/>
      <p className="add-explain">
        (单个文件不能超过5M，上传图片不能超过4张)
      </p>
    </Brief>
  </Item>
</List>

**Comment by cloydlau** [comment]
一样的问题 满足小程序web-view和安卓手机这两个条件可以复现

**Comment by zihuahuahua** [comment]
类似的问题 在Android手机里调起相册后取消 再点击不再弹出相册

**Comment by luckyGTL** [comment]
你们解决了吗，我也是遇到了这个问题。点击之后没有响应

**Comment by OXFord88** [comment]
有没有解决了呀 我的在小米max3 上面闪退了

**Comment by luckyGTL** [comment]
我的已经解决。调不起相册是由于安卓没给权限。然后选择相册之后没有反显是因为没有触发onchange事件，也要原生支持。

**Comment by zihuahuahua** [comment]
> 我的已经解决。调不起相册是由于安卓没给权限。然后选择相册之后没有反显是因为没有触发onchange事件，也要原生支持。

我也是通过客户端给了权限解决的问题

**Comment by NsNe** [comment]
如果是微信上用，可以用 微信的 api 。如果是客户端的页面，可以客户端解决

**Comment by awmleer** [comment]
可以试下 v5 的 ImageUploader 组件

**Comment by NARUTOyuyang** [comment]
> 

antd mobile 5, ImageUploader 在 android 点击直接没反应，没任何提示

**Comment by zihuahuahua** [comment]
> > 
> 
> antd mobile 5, ImageUploader 在 android 点击直接没反应，没任何提示

如果是在客户端webview打开 需要客户端的权限支持

**Comment by huanghly** [comment]
> > 
> 
> antd mobile 5, ImageUploader 在 android 点击直接没反应，没任何提示

+1
