### ISSUE TITLE
Tabs 组件在部分 iphone 8 & X 机型， ios 13^ 上会有抖动问题

### ISSUE THREAD

**Issue by xartd** [ant-design/ant-design-mobile#3581]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/tabs-cn/](https://mobile.ant.design/components/tabs-cn/)

### Steps to reproduce
官方第一个 demo 就有这个问题，动画会抖动

### What is expected?
正常跳转Tab

### What is actually happening?
抖动问题

| Environment | Info |
|---|---|
| antd | 2.3.1 |
| React | 16.8^ |
| System | ios 13^ |
| Browser | 最新 |

**Comment by awmleer** [comment]
可以试下 v5 的 Tabs 组件
