### ISSUE TITLE
modal animationType not working

### ISSUE THREAD

**Issue by destpat** [ant-design/ant-design-mobile#3583]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/destpat/pen/pojJboV?editors=0010](https://codepen.io/destpat/pen/pojJboV?editors=0010)

### Steps to reproduce
Create modal with animationType="fade"

### What is expected?
The modal should display with fade animation

### What is actually happening?
The modal display with slide down animation

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.13.1 |
| System | Mac OS 10.15.2 |
| Browser | Chrome |

**Comment by awmleer** [comment]
Please try the Dialog component of v5.
