### ISSUE TITLE
请问Ant Design Mobile 哪个版本可以同时支持Native和Web？

### ISSUE THREAD

**Issue by LxKev** [ant-design/ant-design-mobile#3584]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A version that will support both mobile native and web.

### What does the proposed API look like?
A version that will support both mobile native and web.

**Comment by xiaohuoni** [comment]
web 用这个库，React Native 用 https://rn.mobile.ant.design/ 。
我不确定哪个版本同时支持，但是太早的版本意味着更多的bug。

**Comment by Jidahan** [comment]
mobile v5是否考虑支持一波 react native

**Comment by awmleer** [comment]
> mobile v5是否考虑支持一波 react native

明确回复一下哈，现在不支持，未来也不会支持
