### ISSUE TITLE
Unable to resolve module `./index.css` from `node_modules/antd-mobile/lib/button/style/css.js`

### ISSUE THREAD

**Issue by KaizenTamashi** [ant-design/ant-design-mobile#3585]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://github.com/TamashiKaizen/antd-mobile-issue1

### Steps to reproduce
yarn ios

### What is expected?
The custom button from antd-mobile should be loaded.

### What is actually happening?
Unable to resolve module `./index.css` from `node_modules/antd-mobile/lib/button/style/css.js`: 

None of these files exist:
  * node_modules/antd-mobile/lib/button/style/index.css(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/antd-mobile/lib/button/style/index.css/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

| Environment | Info |
|---|---|
| antd | undefined |
| React | react-native 0.62.2 |
| System | macOS Catalina 10.15.1 |
| Browser | Google Chrome Version 80.0.3987.163 (Official Build) (64-bit) |

**Comment by minhnguyenvan95** [comment]
same to me

**Comment by awmleer** [comment]
For ant-design-mobile-rn, please go to https://github.com/ant-design/ant-design-mobile-rn.
