### ISSUE TITLE
Carousel 走马灯 滑动

### ISSUE THREAD

**Issue by quanbo518** [ant-design/ant-design-mobile#3586]
Carousel 走马灯 带间距的当图片数量大于4个继续滑动左面图片不见了,定位到别的地方
![1586941315(1)](https://user-images.githubusercontent.com/29518301/79319506-014f6580-7f3b-11ea-867e-81675fa4fb0a.jpg)

**Comment by awmleer** [comment]
试试 v5 的 Swiper 组件吧
