### ISSUE TITLE
tabs组件开启左右滑动会导致pickyer选择器选项回弹

### ISSUE THREAD

**Issue by guomengzhen** [ant-design/ant-design-mobile#3587]
在tabs组件开启左右滑动导致
内部的组件里使用pickyer选择器的时候， 值可以选中但是视图上的选项回弹。
有可能是这两个组件都使用了tranlate3D属性。
目前无奈只能先关闭了tabs的左右滑动。能否解决下

**Comment by awmleer** [comment]
试试 v5 吧
