### ISSUE TITLE
import ReactQuill from 'react-quill';  ReactQuill在ios触屏设备上双击才能获取焦点，可以处理成单击获取焦点吗？

### ISSUE THREAD

**Issue by baizhiyou** [ant-design/ant-design-mobile#3588]
import ReactQuill from 'react-quill';  ReactQuill在ios触屏设备上双击才能获取焦点，可以处理成单击获取焦点吗？
 <ReactQuill
                  className="requestDesc"
                  theme="snow"  //编辑器主题
                  readOnly={false}
                  value={this.state.requestDesc}
                  onChange={this.requestDescChange}
                  placeholder='请输入描述...'
                  style={{borderBottom: "1px solid #ddd"}}
                  modules={{toolbar: tools.toolbarOptions}}
                />
大佬们有遇到过吗？谢谢

**Comment by awmleer** [comment]
看起来和 antd-mobile 本身没有关系，先关掉了
