### ISSUE TITLE
建议增加 PhotoBrowser 图片浏览器

### ISSUE THREAD

**Issue by LayGit** [ant-design/ant-design-mobile#359]
RT.
这个组件应该比较实用的吧
例如 F7 的图片浏览控件，提供滑动切换、缩放等功能。

[http://framework7.taobao.org/docs/photo-browser.html#.V_xnLZN95E4](http://framework7.taobao.org/docs/photo-browser.html#.V_xnLZN95E4)

**Comment by offbye** [comment]
这个确实需要啊  特别是RN的

**Comment by pingan1927** [comment]
我先评估下

**Comment by warmhug** [comment]
可以结合 Pagination 和 Navbar 组件自己实现。暂不考虑增加此组件。
