### ISSUE TITLE
Picker会无限跳回第一个，导致无法选择

### ISSUE THREAD

**Issue by yxyufo110** [ant-design/ant-design-mobile#3592]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gitee.com/yxyufo110/edu.git](https://gitee.com/yxyufo110/edu.git)

### Steps to reproduce
有时候会复现有时候不会

### What is expected?
正常结果

### What is actually happening?
不正常

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.8.6 |
| System | ios and Android |
| Browser | 微信 及其他 |

---
  <Picker
              title="地区"
              data={province}
              cols={3}
              {...getFieldProps('addr')}
              onOk={e => console.log('ok', e)}
              onDismiss={e => console.log('dismiss', e)}
              format={l => l.join(' | ')}
            >
              <List.Item arrow="horizontal"></List.Item>
            </Picker>

**Comment by yxyufo110** [comment]
难以复现，但是确实存在这个问题

**Comment by wanxue0804** [comment]
有webscoket 必现 或者你在页面设置一个定时器修改data 可能也会出现

**Comment by xiaohuoni** [comment]
复现地址是私有库

**Comment by jimhj** [comment]
加定时器，100% 复现

> 有webscoket 必现 或者你在页面设置一个定时器修改data 可能也会出现

**Comment by wudashuaige** [comment]
有解决方案吗

**Comment by aiqin-bao** [comment]
页面内加个定时器 必现， 可能因为重新render的问题， 有解决方案吗 ？

**Comment by wanxue0804** [comment]
建议自己再封装一下，就能解决

**Comment by aiqin-bao** [comment]
将包含定时器的逻辑单独封装一个组件， 与picker组件不包在一起 就可以解决

**Comment by awmleer** [comment]
建议升级到 v5 的 Picker 组件
