### ISSUE TITLE
InputItem type={'money'} disable and editable not work

### ISSUE THREAD

**Issue by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [ant-design/ant-design-mobile#3593]
InputItem type={'money'} disable and editable not work.  I see someone mentioned this problem before. The previous problem was closed and said it was solved, but it's still hard to solve now

how  to do  it

**Comment by sanshuiwang** [comment]
工作的啊！

**Comment by awmleer** [comment]
Please try the `Input` component of v5.
