### ISSUE TITLE
>可以开放ImagePicker图片自定义显示吗

### ISSUE THREAD

**Issue by xietianyao** [ant-design/ant-design-mobile#3594]
就是每张图片下面可以自定义显示内容，类似这样
![image](https://user-images.githubusercontent.com/34930210/80169630-8eb84700-8618-11ea-98c5-a8f9eeac5391.png)

_Originally posted by @xietianyao in https://github.com/ant-design/ant-design-mobile/issues/3233#issuecomment-618771063_

**Comment by xiaohuoni** [comment]
这个在移动端不是很常见吧，自己实现起来难度不大。
