### ISSUE TITLE
It's something wrong with Range Component's declare of RangePropsType

### ISSUE THREAD

**Issue by KanekiSam** [ant-design/ant-design-mobile#3595]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/range-cn/](https://mobile.ant.design/components/range-cn/)

### Steps to reproduce
file position in origin: range -> PropsType.d.ts
export interface RangePropsType {
    onChange?: (value?: number) => void;
    onAfterChange?: (value?: number) => void;
    defaultValue?: number;
    tipFormatter?: ((value?: number) => React.ReactNode);
    value?: number;
    min?: number;
    max?: number;
    step?: number;
    disabled?: boolean;
}
value is not a number,it's a Number Array with two member

### What is expected?
i'd like RangePropsType is correct

### What is actually happening?
value is a number

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | react |
| System | win10 |
| Browser | Chrome 81.0.4044.113 |

---
the version is 2.3.1 exactly; 重现链接应该不需要,就是你们的ts类型标注错了

**Comment by awmleer** [comment]
建议升级到 v5 的 Slider 组件
