### ISSUE TITLE
省市区级联Picker，快速滑动省，此时市还没有选择我直接点击【确定】，onChange拿到的值不是最新的

### ISSUE THREAD

**Issue by yangwend** [ant-design/ant-design-mobile#3597]
省市区级联Picker选择器，省市区数据都是从接口获取的，我传入onChange，获取到当前pciker的value进行处理。此时如果我快速滑动picker的省这一列，此时市和区还没有滑动到第一列，我点击【确定】按钮，此时onChange拿到的值不是最新的

**Comment by xiaohuoni** [comment]
loading状态加一个吧？感觉也不能算bug？
