### ISSUE TITLE
上手很麻烦，装包运行老是异常，建议提供几个demo，分RN和web版

### ISSUE THREAD

**Issue by haomiaozhichen** [ant-design/ant-design-mobile#360]
#### window 7

- antd-mobile 版本：0.9.2
- 操作系统及其版本：window 7
- 浏览器及其版本：firfox

#### 你做了什么？
尝试使用antd-mobile创建一个web项目

#### 你期待的结果是：
项目能正常运行

#### 实际上的结果：
webpack编译时，各种报错

**Comment by silentcloud** [comment]
#56  这里有实例

**Comment by kingj1261** [comment]
使用太烂了，折腾了半天没搞好，各种报错

**Comment by warmhug** [comment]
@kingj1261 示例集合 https://github.com/ant-design/antd-mobile-samples
