### ISSUE TITLE
Modal.Alert doesn't show the animation when close

### ISSUE THREAD

**Issue by ykx456654** [ant-design/ant-design-mobile#3600]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ykx456654/pen/dyYWwXR](https://codepen.io/ykx456654/pen/dyYWwXR)

### Steps to reproduce
1.点击alert
2.点击确认

### What is expected?
alert  mask消失的时候有动画

### What is actually happening?
alert  mask消失的时候没有动画

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.9.0 |
| System | mac |
| Browser | chrome |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
