### ISSUE TITLE
Flex.Item should not have any margin-left

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [ant-design/ant-design-mobile#3601]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
Nothing...

### Steps to reproduce
**Link to minimal reproduction is not true**

Its simple, Look at Flex.Item (Not first one), these elements has a margin-left: 8px; which its not good idea to set margin to flex items.

### What is expected?
No margin to flex items, if this is need developed can add anytime

### What is actually happening?
Flex.Items has a default margin-left (Not first one)

| Environment | Info |
|---|---|
| antd | 2.3.1 |
| React | 16.13.1 |
| System | any |
| Browser | any |

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
