### ISSUE TITLE
ios下，手机号码键入时，数字键盘不断闪烁，官方demo能重现

### ISSUE THREAD

**Issue by Kilims** [ant-design/ant-design-mobile#3602]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item](https://mobile.ant.design/kitchen-sink/components/input-item)

### Steps to reproduce
官方demo可以重现。步骤如下：
1. 微信内打开上述链接（https://mobile.ant.design/kitchen-sink/components/input-item），下滑到Fomat -》手机号码 输入栏。
2. 输入11位手机号码，你会发现在键入过程中，弹起的数字键盘不断随着键入而闪烁

### What is expected?
手机号码键入时，数字键盘不会闪烁

### What is actually happening?
手机号码键入时，数字键盘随着键入不停闪烁

| Environment | Info |
|---|---|
| antd | 2.3.1 |
| React | 16.11.0 |
| System | IOS 13.3（17C54） |
| Browser | 微信内置浏览器 |

---
经查验、测试，当且仅当：

在IOS下、同页面存在密码输入栏、目标输入栏设置了patern='[0-9]*'这一调起数字键盘的属性后，才有这种情况。

（上述手机号码的例子是设置了type='phone'，进而设置了patern='[0-9]*'导致的）

**Comment by xiaohuoni** [comment]
跟这个库没什么关系。系统13.3可以重现，13.4.1不会有这问题。
```
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    <input type="tel">
    <input type="password">
</body>
</html>
```

**Comment by xiaohuoni** [comment]
https://tieba.baidu.com/p/6345464235?traceid=

**Comment by Kilims** [comment]
cool ! thx.
