### ISSUE TITLE
这个仓库已经弃更了吗

### ISSUE THREAD

**Issue by Magin-CC** [ant-design/ant-design-mobile#3603]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用这个依赖的人应该不少吧，在react16里面已经很难使用了

### What does the proposed API look like?
期望你们更新

**Comment by amyhuangxbd** [comment]
同问，
顺便问下现在还有哪些比较好的react mobile UI框架

**Comment by xiaohuoni** [comment]
听说最近有在内测（虽然我不太理解开源项目，为什么会有内测），应该过阶段会更新。基本都能用，我们项目中，没遇到特别处理不了的问题。

**Comment by Magin-CC** [comment]
> 解开源项目，为什么会有内测），应该过阶段

string ref，类型与rc组件不配套，太多问题了，你开个strict mode全是warning

**Comment by shen1986** [comment]
> 同问，
> 顺便问下现在还有哪些比较好的react mobile UI框架

感觉react 的 mobile ui 不是很多，比vue少多了，如果只是做h5网页的话，你可以尝试下onsen-ui. native 的我不太清楚。

**Comment by cnscorpions** [comment]
taro-ui + taro 写h5，哈哈

**Comment by cnscorpions** [comment]
可以取https://www.docschina.org/看下，react mobile web组件库不多，能打的可能就这个了吧

**Comment by fancy-rabbit** [comment]
+1. 依赖的 babel 还是 6.x，有些 rc 组件的 polyfill 会出问题。目前是很 hacky 解决的
听说已经内测很久了 期待公测

**Comment by fred8617** [comment]
你们都在哪听见的内测。。。

**Comment by kobezhu** [comment]
bug真的无数……很多时候想换框架但是又不知道欢什么

**Comment by Magin-CC** [comment]
一边气它不更新，一边起项目又默默yarn add antd-mobile了，好可悲，移动端真的好窘迫

**Comment by yxyufo110** [comment]
希望开源项目还是负责一点，弃更或者什么的说明一下，大量Bug根本无法使用，换组件花费时间

**Comment by xiaohuoni** [comment]
哪里有大量的bug？🤦‍♂️基本还是能用的。

**Comment by Magin-CC** [comment]
> 哪里有大量的bug？🤦‍♂️基本还是能用的。

建议使用最新版本react并开启严格模式，打开控制台就可以看到问题了

**Comment by fancy-rabbit** [comment]
@xiaohuoni 所以，有更新计划么？

**Comment by H-Sven** [comment]
同问，官网看到最新的更新日志还是去年9月

**Comment by daoke0818** [comment]
谁来代表官网回复一下呢？感觉更新远远赶不上antd的PC端

**Comment by citrusjunoss** [comment]
有什么其他推荐的React UI 框架不

**Comment by doxiaodong** [comment]
详见 https://github.com/ant-design/ant-design-mobile/issues/3671

**Comment by ssiije** [comment]
ionic 算不算一个选择
