### ISSUE TITLE
定制主题 - 配置文档更新

### ISSUE THREAD

**Issue by snowtreetree** [ant-design/ant-design-mobile#3609]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
主题色，按照antd-mobile官网上的配置，一路下来，并没有生效，倒是根据antd的配置，调整下才生效。  
部分代码：
```js
const { override, fixBabelImports, addLessLoader } = require('customize-cra');
module.exports = override(
    fixBabelImports('antd-mobile', {
      libraryDirectory: 'es',
        style: 'css',
    }),    
    addLessLoader({
      javascriptEnabled: true,
        modifyVars: { '@brand-primary': '#ccc' },
      }),
);

```

### What does the proposed API look like?
更新文档

**Comment by xiaohuoni** [comment]
没看出来，两份文档有什么太大差异

**Comment by heng5120** [comment]
那如何配置才是正确的呢？

**Comment by xiaohuoni** [comment]
他给出的应该就是正确的。umi 中的话，可以配置 theme

**Comment by snowtreetree** [comment]
@xiaohuoni 你这边按着官方上面的文档能够配置成功吗？😂

**Comment by xiaohuoni** [comment]
@snowtreetree 我都用 umi 的 theme 配置 😂

**Comment by heng5120** [comment]
` addLessLoader({
        lessOptions:{
            javascriptEnabled: true,
            modifyVars: {"brand-primary": "#7d2dcc"},
        }
    }),`
less-loader这个格式成功了，哎，搞了好久

**Comment by snowtreetree** [comment]
> ` addLessLoader({ lessOptions:{ javascriptEnabled: true, modifyVars: {"brand-primary": "#7d2dcc"}, } }),`
> less-loader这个格式成功了，哎，搞了好久

我当时也是弄了好久。。。一直觉得自己的打开方式有问题。
