### ISSUE TITLE
ListView组件只支持垂直滚动，不能横向滚动，建议尽快解决

### ISSUE THREAD

**Issue by haomiaozhichen** [ant-design/ant-design-mobile#361]
#### 本地环境

- antd-mobile 版本：0.9.2
- 操作系统及其版本：win 7
- 浏览器及其版本：

**Comment by warmhug** [comment]
支持的，要自己覆盖样式。例子：http://react-component.github.io/m-list-view/examples/simple-horizontal.html

**Comment by AlexTMing** [comment]
那安卓上面怎么覆盖呢

**Comment by warmhug** [comment]
Android 上边参考 RN listview 文档里写了
