### ISSUE TITLE
Tabs cannot be styled 

### ISSUE THREAD

**Issue by jyclam** [ant-design/ant-design-mobile#3610]
#### Reproduction link
https://codesandbox.io/s/boring-wing-wf9i5?file=/src/App.js

#### Steps to reproduce
1. Try to style Tabs component via inline style or styled-component

#### What is expected?
For styles to be applied. 

#### What is actually happening?
No styles are applied 

Environment | Info
-- | --
antd-mobile | 2.3.1
React | 16.13.1
styled-components | 5.0.1
System | mac
Browser | chrome

**Comment by danielsimao** [comment]
@jyclam for some reason they apply an inline style on the tabs bar. So, for you to override the inline style you would have to use the following.

(styles.css)
`
.am-tabs-default-bar {
  background-color: red !important;
}
`
