### ISSUE TITLE
关于组件库默认引入normalize.css问题

### ISSUE THREAD

**Issue by ahwgs** [ant-design/ant-design-mobile#3616]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ahwgs/pen/oNjmKdV](https://codepen.io/ahwgs/pen/oNjmKdV)

### Steps to reproduce
1.安装antd-mobile
2.编写一个简单的组件，使用h1标签
3.控制台打开，查看h1标签的样式
4.发现h1标签有默认样式，并且来自normalize.css

### What is expected?
没有默认样式，或有正确的默认样式

### What is actually happening?
有默认样式，造成刚安装完antd-mobile,页面异常，并且查看控制台看到：
```css
    font-size: 2em;
    margin: .67em 0;
```

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.12.0 |
| System | windows |
| Browser | Google Chrome 版本 83.0.4103.61 |

---
就是想请问一下为什么在`/components/style/index.tsx`中引入`normalize.css`包，因为并没有在其他地方看到该包的使用，下面贴两张图
![](https://static.ahwgs.cn/blogImage/20200523002512.png)
![](https://static.ahwgs.cn/blogImage/20200523002552.png)

**Comment by ahwgs** [comment]
![](https://static.ahwgs.cn/blogImage/20200523002749.png)
在补上一张组件库引入路径

**Comment by doxiaodong** [comment]
所有样式基于 normalize 开发的

**Comment by iajun** [comment]
遇到了同样的问题，怎么去掉 normalize

**Comment by ahwgs** [comment]
> 遇到了同样的问题，怎么去掉 normalize

我是覆盖了normalize的默认样式

**Comment by dickeylth** [comment]
> 我就是觉得吧，作为组件库不应该有 html 全局的样式，这样到 html body h1 h2 这些全局标签上，造成全局污染不说，还覆盖了我自定义的。。。。

+1，我只是用一个 action sheet 的组件，为啥要把 body 也污染了？？？

**Comment by dickeylth** [comment]
暂时先用 https://www.npmjs.com/package/string-replace-loader hack 掉了

**Comment by qiwang97** [comment]
我在使用 nextjs 开发的时候报错 
```sh
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: ../../node_modules/antd-mobile/lib/icon/style/css.js
../../node_modules/normalize.css/normalize.css
```

建议 `normalize.css`  文件由用户手动引入

**Comment by Fire-Kirin** [comment]
> 暂时先用 https://www.npmjs.com/package/string-replace-loader hack 掉了

你好，请问一下 hack 的具体设置是什么？
