### ISSUE TITLE
Problem on using Ref for Flex component

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [ant-design/ant-design-mobile#3617]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/amirhosseinkarimi/pen/BaoEZpr](https://codepen.io/amirhosseinkarimi/pen/BaoEZpr)

### Steps to reproduce
Create a ref in component constructor method and then use as <Flex ref={this.myRef} ...   then console.log the this.myRef on component did mount. You can see this does not work.

### What is expected?
Normal Ref

### What is actually happening?
this return wrong or plain Ref object.

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | React 16.13.1 |
| System | Debian 10 |
| Browser | Firefox 76.0.1 |

**Comment by xiaohuoni** [comment]
Reproduction link Error！

**Comment by AmirHosseinKarimi** [comment]
Hi @xiaohuoni , the problem is not from link, I forgot to save the progress, anyway, Now its Okay, you can check it and see the example.

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/83210099-91183e80-a18c-11ea-93f4-fa74fc39e2d1.png)
Hi @AmirHosseinKarimi ,It seems to work

**Comment by AmirHosseinKarimi** [comment]
@xiaohuoni , No its not, check the object, you will see its not attached to element.

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
