### ISSUE TITLE
利用antd-mobile做H5页面，import 导入antd-mobile打包提示找不到

### ISSUE THREAD

**Issue by leilihuang** [ant-design/ant-design-mobile#363]
#### 本地环境_
利用webpack DLL插件分离出第三方组件库
![1](https://cloud.githubusercontent.com/assets/13639327/19260380/9db2af2c-8fbb-11e6-80f5-a5e239d85f1b.png)
这个是webpack的配置文件
![3](https://cloud.githubusercontent.com/assets/13639327/19260448/2f2ca52a-8fbc-11e6-9cd0-d165c0a7fddd.png)

- antd-mobile 版本：0.9.1
- 操作系统及其版本：win10
- 浏览器及其版本：谷歌最新版本

#### 你做了什么？
我在代码里面直接引用antd-mobile
![2](https://cloud.githubusercontent.com/assets/13639327/19260455/42e61808-8fbc-11e6-9111-2e8f22b66949.png)

#### 你期待的结果是：
像官网一样正常使用

#### 实际上的结果：
运行时报错
![2](https://cloud.githubusercontent.com/assets/13639327/19260482/77c98b90-8fbc-11e6-8438-20fce6ad0e27.png)

**Comment by silentcloud** [comment]
使用 readme 里提的插件以及配置好 webpack

**Comment by leilihuang** [comment]
使用antd-mobile需要安装react-native么？

**Comment by leilihuang** [comment]
要使用antd-mobile，哪些是必须要安装的插件

**Comment by silentcloud** [comment]
@leilihuang web 项目是不用安装 react-native 的

**Comment by leilihuang** [comment]
好的，我试试，谢谢

**Comment by leilihuang** [comment]
![image](https://cloud.githubusercontent.com/assets/13639327/19266650/143bb7d0-8fdd-11e6-909f-7cacaee24009.png)
antd-mobile不能用webpack Dll插件分离出来嘛？

**Comment by silentcloud** [comment]
@leilihuang 应该还是缺少 extension 引起的吧

**Comment by leilihuang** [comment]
@silentcloud 
添加进来了还是报错
![image](https://cloud.githubusercontent.com/assets/13639327/19295371/bd13d0d4-9066-11e6-871d-2c4963d67099.png)

**Comment by yiminghe** [comment]
参考 https://github.com/ant-design/ant-design-mobile/issues/56

**Comment by silentcloud** [comment]
@leilihuang Dll 具体没怎么用过，可能需要你自己研究尝试一下，正常的 ok 的话，这个 issue 我就先 close 了

**Comment by superNever** [comment]
@leilihuang  dll好用了吗
