### ISSUE TITLE
Picker Component style can't set

### ISSUE THREAD

**Issue by jsonParseTo** [ant-design/ant-design-mobile#3631]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/jsonparseto/pen/qBbWZbj](https://codepen.io/jsonparseto/pen/qBbWZbj)

### Steps to reproduce
click the ulr, the style is that i want to (default style).
then open a new window, add the css style that i had annotated，compare these，you can see the wrong style.

### What is expected?
set the height and line-height to 48px, 
and the selected item should show at the middle,
and the hight-light lines should be one ,not three. 

### What is actually happening?
height and line-height is right,
selected is't at the middle,
hight-line isn't one.

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8.6 |
| System | mac  |
| Browser | chrome |

**Comment by daoke0818** [comment]
我在PickerView 选择器中也遇到这样的问题，通过api中的itemStyle和indicatorStyle设置也无效。发现主要原因是am-picker-col-content的属性transform：translate3d(0px, -68px, 0px)，其中第二个只只知道按照step34像素变化，没有跟随height或line-height来变化。

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
