### ISSUE TITLE
TS2769: No overload matches this call

### ISSUE THREAD

**Issue by antiantian** [ant-design/ant-design-mobile#3634]
按照官方文档引用Popover组件ts报错

`import { Popover } from 'antd-mobile'

       <Popover
              overlayClassName="city-tip-popover"

              align={{

                offset: [50, 5]
              }}
              placement="bottom"
              overlay={[<span className="tip-content" key={city}>{city}</span>]}
            >
              <i className="tip-icon"></i>
     </Popover>`

TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<PopOverPropsType>): Popover', gave the following error.
    Type '{ offset: number[]; }' is not assignable to type '{ overflow: { adjustY: number; adjustX: number; }; }'.
      Object literal may only specify known properties, and 'offset' does not exist in type '{ overflow: { adjustY: number; adjustX: number; }; }'.
  Overload 2 of 2, '(props: PopOverPropsType, context?: any): Popover', gave the following error.
    Type '{ offset: number[]; }' is not assignable to type '{ overflow: { adjustY: number; adjustX: number; }; }'.
      Object literal may only specify known properties, and 'offset' does not exist in type '{ overflow: { adjustY: number; adjustX: number; }; }'.

**Comment by seven0404** [comment]
I have the same issue

`import { Toast, PullToRefresh } from 'antd-mobile';

        <PullToRefresh
          damping={100}
          indicator={{}}
          direction='down'
          refreshing={this.state.refreshing}
          onRefresh={() => {
            this.setState({ refreshing: true });
            setTimeout(() => {
              this.setState({ refreshing: false });
            }, 1000);
          }}
        >

    <div>my Node</div>

        </PullToRefresh> `

No overload matches this call.
  Overload 1 of 2, '(props: Readonly<PropsType>): PullToRefresh', gave the following error.
    Type '{ children: Element[]; damping: number; indicator: {}; direction: "down"; refreshing: boolean; onRefresh: () => void; }' is missing the following properties from type 'Pick<Readonly<PropsType> & Readonly<{ children?: ReactNode; }>, "children" | "style" | "getScrollContainer" | "direction" | "refreshing" | ... 5 more ... | "scale">': getScrollContainer, distanceToRefresh
  Overload 2 of 2, '(props: PropsType, context?: any): PullToRefresh', gave the following error.
    Type '{ children: Element[]; damping: number; indicator: {}; direction: "down"; refreshing: boolean; onRefresh: () => void; }' is missing the following properties from type 'Pick<Readonly<PropsType> & Readonly<{ children?: ReactNode; }>, "children" | "style" | "getScrollContainer" | "direction" | "refreshing" | ... 5 more ... | "scale">': getScrollContainer, distanceToRefresh

**Comment by seven0404** [comment]
in node_modules>rmc-pull-to-refresh>lib>PropsType.d.ts>PropsType
when i change these two terms, it's running,the problem solved

`export interface PropsType {
    getScrollContainer?: () => React.ReactNode;
    direction: 'down' | 'up';
    refreshing?: boolean;
    distanceToRefresh?: number;
    onRefresh: () => void;
    indicator: Indicator;
    prefixCls?: string;
    className?: string;
    style?: React.CSSProperties;
    damping?: number;
    scale?: number;
}
`

    getScrollContainer?: () => React.ReactNode;
    distanceToRefresh?: number;

the two terms is not necessary, so I add "?" ,  I don't know if my answer is the answer to this question, please the author to check and updete

ant  "version": "2.3.3",

**Comment by sanshuiwang** [comment]
希望作者尽快处理一下，其实有些时候不需要我们传很多参数，PullToRefresh

![image](https://user-images.githubusercontent.com/20984566/86109349-de266200-baf6-11ea-9c57-c381401ce91c.png)

**Comment by cat-walk** [comment]
hope to be resolved

**Comment by renrenguiwei** [comment]
I have the same problem with "listview" renderRow property.
![Uploading Xnip2020-10-23_13-49-14.jpg…]()

**Comment by renrenguiwei** [comment]
I have the same problem with "ListView" renderRow property.
![renderrow](https://user-images.githubusercontent.com/7834109/96961261-cefc7180-1536-11eb-9b6a-a469e6a53693.jpg)

**Comment by sanshuiwang** [comment]
我们只能自己改改啦哈😄



---Original---

**Comment by renrenguiwei** [comment]
> I have the same problem with "ListView" renderRow property.
> ![renderrow](https://user-images.githubusercontent.com/7834109/96961261-cefc7180-1536-11eb-9b6a-a469e6a53693.jpg)

找到解决办法了，因为renderRow要求return一个JSX Element
1. 错误写法：
`renderRow = (rowData, sectionID, rowID) => {
        <SearchResultCeil key={rowID} />
 }`
这样是return了一个对象包裹，不是JSX Element

2. 正确写法：
`renderRow = (rowData, sectionID, rowID) => <SearchResultCeil key={rowID} />`
或者
`renderRow (rowData, sectionID, rowID) {
       return (
           <SearchResultCeil key={rowID} />
       )
 }`

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
