### ISSUE TITLE
Carousel组件，设置为带间距类型，再最后一张图片到第二轮图片切换，图片会闪烁

### ISSUE THREAD

**Issue by carrollcai** [ant-design/ant-design-mobile#3635]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/carousel-cn/#components-carousel-demo-basic](https://mobile.ant.design/components/carousel-cn/#components-carousel-demo-basic)

### Steps to reproduce
直接查看官方带间距的Demo，滑动过程中，左右的图片均可能发生闪烁。（主要是用了绝对定位，当进入新一轮图片循环时，图片要重新计算位置，可以考虑用transform实现，或者float布局）

### What is expected?
滑动过程中不闪烁

### What is actually happening?
滑动过程中闪烁

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.8 |
| System | macOS 10.15.3 |
| Browser | Chrome 83 |

---
希望可以得到回复，carroll.cai@outlook.com

**Comment by woshixixi** [comment]
这库感觉没人维护了 我已经准备用 Swiper 了 太扯了 这个组件

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
