### ISSUE TITLE
希望Picker组件在不级联的时候也能触发onPickerChange事件，并返回操作列的index。谢谢！

### ISSUE THREAD

**Issue by daoke0818** [ant-design/ant-design-mobile#3638]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如我使用Picker组件要实现一个三列选择器，第一列选择模式，第二列和第三列分别是此模式的时间范围和温度范围。目前，如果不使用级联模式，则无法响应每列改变的事件；使用及联模式的话必须按照级联结构封装大量重复的数据。希望此功能可以同步到PickerView。谢谢工作人员们！

### What does the proposed API look like?
```
onPickerChange = (v,index) => {
        // v 是改变后的值
        // index 是当前操作列的下标
    }
```

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
