### ISSUE TITLE
inputItem的标题超过4个字就显示...

### ISSUE THREAD

**Issue by guangming21** [ant-design/ant-design-mobile#364]
#### 本地环境

- antd-mobile 版本：0.8.6
- 操作系统及其版本：win10
- 浏览器及其版本：谷歌

#### 你做了什么？

inputItem 组件title超过4个字就显示。。。

#### 实际上的结果：

![qq 20161011151036](https://cloud.githubusercontent.com/assets/18028721/19261657/3e5ffb92-8fc5-11e6-89d4-253afbd82b67.png)

**Comment by warmhug** [comment]
可以自己覆盖样式

**Comment by pingan1927** [comment]
labelNumber 默认值是4个文字，
win10 是指操作系统是win10 mobile吗？

**Comment by guangming21** [comment]
@pingan1927 做的mobile web, win10 pc 机， 用的谷歌浏览器

**Comment by silentcloud** [comment]
@guangming21  这种自己在 css 覆盖一下样式吧，我们只能提供一种默认方式

**Comment by pingan1927** [comment]
`labelNumber`可以控制左侧最多可以显示的字数。你可以设置成5、6、7等
