### ISSUE TITLE
PullToRefresh 拉动刷新组件，下拉滚动与下拉刷新事件重复，导致意外刷新列表

### ISSUE THREAD

**Issue by jokingzhang** [ant-design/ant-design-mobile#3640]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
- [预览地址](https://jokingzhang.github.io/react-h5-test)
- demo地址：https://github.com/jokingzhang/react-h5-test

### Steps to reproduce
1、打开Demo，选择左边的列表（Demo底部可切换列表）
2、上滑列表，等待列表停止之后，下滑列表

![image](https://user-images.githubusercontent.com/10766546/84164930-ae5ede00-aaa5-11ea-8a19-3cdb296542b3.png)

### What is expected?
滑动正常，等滑动的列表顶部才会触发刷新（参考右边列表）

### What is actually happening?
下滑列表马上触发刷新

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.13.1 |
| System | Android 9 华为Nova3 |
| Browser | Android Chrome 浏览器 76.0 |

**Comment by jokingzhang** [comment]
我设置容器的高度了，但还是不行

**Comment by jokingzhang** [comment]
```
  const wrapperStyle = {
    height: `calc(100vh - ${46.5}px)`,
    overflow: 'auto',
  };
... 

      <PullToRefresh
        getScrollContainer={() => undefined}
        distanceToRefresh={50}
        damping={100}
        indicator={{}}
        direction={'down'}
        refreshing={state.loading}
        onRefresh={state.retry}
        style={wrapperStyle}
      >
         <div>一个列表</div>
      </PullToRefresh>
```
已经解决了，感谢大佬

**Comment by sanshuiwang** [comment]
1. 可以自己计算固定高度
2. 也可以根据设备clientHeight减去节点的offsetTop去计算

**Comment by xqwIOS** [comment]
你好 你最后是怎么改的
