### ISSUE TITLE
InputItem ts增加inputmode属性

### ISSUE THREAD

**Issue by tong233** [ant-design/ant-design-mobile#3641]
inputmode has been a [WHATWG](https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-inputmode-attribute) spec for a couple of years, and has finally been implemented by Chrome as of version 66
browser support data is from [Caniuse](https://caniuse.com/#feat=input-inputmode)
inputmode作为[WHATWG](https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-inputmode-attribute) 规范已经有几年了，最终在 Chrome 66版本中实现

**Comment by awmleer** [comment]
v5 已支持
