### ISSUE TITLE
表单中的 label 和 value[input]  的文本 没有对齐，上下label 的位置 高 2px

### ISSUE THREAD

**Issue by ranckprogram** [ant-design/ant-design-mobile#3642]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/input-item-cn/](https://mobile.ant.design/components/input-item-cn/)

### Steps to reproduce
直接观察

### What is expected?
表单中的 label 和 value[input]  的文本 对齐

.am-list-item .am-input-control input {
  margin-bottom: 2px;
}

### What is actually happening?
表单中的 label 和 value[input]  的文本 没有对齐，上下label 的位置 高 2px

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | react |
| System | windows  和 Android |
| Browser | chrome 和 weixin |

**Comment by ranckprogram** [comment]
![0c6c576fb69fc33143781f4ab3d8e49](https://user-images.githubusercontent.com/22071583/84249488-67bcc280-ab3d-11ea-85ab-8a3fbfa5ae20.jpg)

**Comment by ranckprogram** [comment]
![image](https://user-images.githubusercontent.com/22071583/84249559-828f3700-ab3d-11ea-95d9-d21fbe4ee9a7.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
