### ISSUE TITLE
官网更新日志还停留在19年9月，请问还在保持维护吗

### ISSUE THREAD

**Issue by H-Sven** [ant-design/ant-design-mobile#3644]
官网更新日志还停留在19年9月，请问还在保持维护吗

**Comment by doxiaodong** [comment]
网站版本未更新，我更新下

**Comment by alexchen1875** [comment]
什么时候能 [支持react16.x](https://github.com/ant-design/ant-design-mobile/issues/3374)呢?

when will support the latest react  version  ?

**Comment by doxiaodong** [comment]
react 16.x 本来就支持呀

**Comment by ibesty** [comment]
是因为更新的原因吗，网站崩了打不开

**Comment by alexchen1875** [comment]
> react 16.x 本来就支持呀

抱歉,我是想表达是基础组件的升级,现在有很多警告.详情查看关联issue

**Comment by comtnt** [comment]
同网站打不开了

**Comment by doxiaodong** [comment]
更新挂了，稍等一下啊

**Comment by BengBu-YueZhang** [comment]
https://mobile.ant.design/components/tabs-cn/ 打不开

**Comment by jeanys** [comment]
@doxiaodong  InputItem 还在使用 componentWillReceiveProps，导致有警告，react 版本 16.13，antd mobile 版本 2.3.3

**Comment by citrusjunoss** [comment]
> 更新挂了，稍等一下啊

有什么版本规划计划么

**Comment by jigsaw-china** [comment]
不更新了？控制台一堆警告

**Comment by doxiaodong** [comment]
见 https://github.com/ant-design/ant-design-mobile/issues/3671

**Comment by specialgirlgotoheaven** [comment]
> 网站版本未更新，我更新下

请问antd 3.0有在更新吗
