### ISSUE TITLE
定制主题后Button组件等在长按状态下会还原成primary（标蓝）色

### ISSUE THREAD

**Issue by cliek** [ant-design/ant-design-mobile#3646]
**Reproduction link**

[](https://mobile.ant.design/components/button-cn/)

**Steps to reproduce**
定制主题后-->primary，长按按钮

**What is expected?**
长按按钮后底色会显示对应颜色的高亮色彩

![image](https://user-images.githubusercontent.com/29326163/84377390-17189880-ac15-11ea-9f58-4e6d1cdd6acd.png)

![image](https://user-images.githubusercontent.com/29326163/84377743-b2aa0900-ac15-11ea-92f6-c691793451ef.png)

我检查源码后修改了Button文件
`node_modules\@ant-design\react-native\lib\button\index.js`
在代码123行处原来：
`var underlayColor = _reactNative.StyleSheet.flatten(activeStyle ? activeStyle : _styles[type + 'Highlight']).backgroundColor;`
改成
`var underlayColor = _reactNative.StyleSheet.flatten(activeStyle ? activeStyle : _styles[type + 'Raw']).backgroundColor;`
这样就好了

我覆盖theme的color的时候覆盖这几个属性，
`theme: {
brand_primary: color,
primary_button_fill: color,
ghost_button_color: color,
ghost_button_fill_tap: `${color}99`,
segmented_control_color: color
}`
![image](https://user-images.githubusercontent.com/29326163/84378843-65c73200-ac17-11ea-9fba-c17e72423d46.png)

是还有哪些没有改到吗？

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
