### ISSUE TITLE
在IOS设备上InputItem 失焦的时候页面会自动回到顶部，软键盘点“完成”时也是。

### ISSUE THREAD

**Issue by daoke0818** [ant-design/ant-design-mobile#3647]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/input-item-cn/](https://mobile.ant.design/components/input-item-cn/)

### Steps to reproduce
官网的demo就可以。

### What is expected?
在IOS设备上InputItem 失焦的时候，页面可以不自动滚到顶部，或有选项控制。

### What is actually happening?
在IOS设备上InputItem 失焦的时候，页面会自动滚到顶部。

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome 76.0.3809.87（正式版本） （32 位） |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
