### ISSUE TITLE
ListView组件的renderSectionBodyWrapper属性不起作用

### ISSUE THREAD

**Issue by Rongger** [ant-design/ant-design-mobile#3648]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/rongger/pen/oNbxEqO?editors=0010](https://codepen.io/rongger/pen/oNbxEqO?editors=0010)

### Steps to reproduce
在ListView下新增属性renderSectionBodyWrapper={() => <div className="aaa">123</div>}

按官网文档可以渲染自定义的区块 body 包裹组件

但是在开发者工具中Elements中找不到 sectionHeader 外层有class为aaa的div

也就是说renderSectionBodyWrapper不起作用

### What is expected?
renderSectionBodyWrapper可以渲染自定义的区块 body 包裹组件

### What is actually happening?
renderSectionBodyWrapper不起作用

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.13.1 |
| System | win10 教育版 1903 |
| Browser | 版本 83.0.4103.97（正式版本） （64 位） |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
