### ISSUE TITLE
新放入的跑马灯插件总是出现ref的警告提示，是需要什么配置解决还是没有改进的BUG

### ISSUE THREAD

**Issue by luochenLing** [ant-design/ant-design-mobile#3649]
<img width="625" alt="微信截图_20200614183852" src="https://user-images.githubusercontent.com/20987700/84591138-948b1580-ae6e-11ea-9ad4-5d89c62ad05c.png">
<img width="523" alt="微信截图_20200614183921" src="https://user-images.githubusercontent.com/20987700/84591141-9654d900-ae6e-11ea-92f4-a8bf49d5e329.png">

**Comment by awmleer** [comment]
试试 v5 吧：
http://next.mobile.ant.design
