### ISSUE TITLE
官方后续的开发计划是什么

### ISSUE THREAD

**Issue by zsytssk** [ant-design/ant-design-mobile#3650]
公司最近项目， 需要选择一个移动端react ui框架， pc端用的是antd；
我看antd-mobile开发不怎么活跃，几乎两年没有更新，最近又更新了；
不知道官方对antd-mobile的定位是什么，后面会主力维护它吗

现在移动端没有一个和antd相同地位的框架，我相信很多人都希望能用到antd类似的api， 同时稳定可靠

**Comment by doxiaodong** [comment]
后续有个大胆的计划，还没整理好

**Comment by xiaohuoni** [comment]
大胆的计划，删库跑路嘛，哈哈哈😂

**Comment by zkeyword** [comment]
隔壁的vant 功能还是没美观度 都甩antd-mobile

**Comment by zkeyword** [comment]
antd-mobile感觉被遗弃 现在基本直接用antd来做移动端 始终怪怪的

**Comment by zsytssk** [comment]
@zkeyword @doxiaodong 有什么好用的react mobile 组件库吗
vant的确很好，如果react移动端有一个类似的就好了

**Comment by zkeyword** [comment]
> @zkeyword @doxiaodong 有什么好用的react mobile 组件库吗
> vant的确很好，如果react移动端有一个类似的就好了

隔壁的taro-ui貌似不错

**Comment by DreamPWJ** [comment]
react 移动端UI库 被vue  vant帅一条街  PC端如果没有antd  真心不会用react

**Comment by lizy0329** [comment]
`官方对antd-mobile的定位是什么？`
定位就是同人作品

**Comment by huanghdm88** [comment]
真的不打算出黑色版吗？

**Comment by crecreek** [comment]
抱着和antd 一样的期许，准备用，越看越觉得 会与坑，连简单的单选，多选 都不支持、、、

**Comment by gouflv** [comment]
阿里的移动端 ，弃用 react 多久了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/issues/3671
