### ISSUE TITLE
android 手机 在 app里webview引入Carousel，无法滑动

### ISSUE THREAD

**Issue by amyhuangxbd** [ant-design/ant-design-mobile#3651]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/carousel-cn/](https://mobile.ant.design/components/carousel-cn/)

### Steps to reproduce
app 里引入 Carousel h5 页面，android手机里无法滑动

### What is expected?
app 里引入 Carousel h5 页面，android手机里正常滑动

### What is actually happening?
app 里引入 Carousel h5 页面，android手机里无法滑动

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.10.2 |
| System | android  |
| Browser | app webview |

**Comment by amyhuangxbd** [comment]
android 手机 在 app 里webview引入Carousel，无法滑动

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
