### ISSUE TITLE
‘TabBar sticky’ Examples cannot be used correctly

### ISSUE THREAD

**Issue by zhengkuo1990** [ant-design/ant-design-mobile#3655]
‘TabBar sticky’ Examples cannot be used correctly，In the example, the content data can appear normally after the 'key' of the object array tabs is changed to 'sub'

**Comment by yursile** [comment]
content cannot be presented
from the codepen: https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Fmobile.ant.design%2Fcomponents%2Ftabs-cn%2F

**Comment by Unfantasy** [comment]
我发现移除 tabs 的 key 字段就可以使用 sticky 效果了

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
