### ISSUE TITLE
使用antd-mobile，界面显示和官网不一样

### ISSUE THREAD

**Issue by leilihuang** [ant-design/ant-design-mobile#366]
#### 本地环境

配置如下
![image](https://cloud.githubusercontent.com/assets/13639327/19294783/423eafb8-9062-11e6-9988-78c42bb3931c.png)

- antd-mobile 版本：0.9.1
- 操作系统及其版本：win10
- 浏览器及其版本：google

#### 你做了什么？
代码是复制官网的顶部导航栏
![image](https://cloud.githubusercontent.com/assets/13639327/19294853/d8e78fac-9062-11e6-974e-fb60893da693.png)

#### 你期待的结果是：
像官网一样正常显示

#### 实际上的结果：

界面显示如下
![image](https://cloud.githubusercontent.com/assets/13639327/19294749/0e5278d8-9062-11e6-952c-aa799b22d264.png)

我对比了一下官网的demo发现少了NavBar的样式，但是运行没有报错

**Comment by silentcloud** [comment]
没引用 antd-mobile 的样式吧？

import 'antd-mobile/dist/antd-mobile.css'

**Comment by leilihuang** [comment]
不是这里
![image](https://cloud.githubusercontent.com/assets/13639327/19295094/c7e0b916-9064-11e6-8ef2-451ebfe04912.png)
配置了，就不用在js里面引用css嘛

**Comment by leilihuang** [comment]
在入口JS里面添加了样式还是显示不正常
![image](https://cloud.githubusercontent.com/assets/13639327/19295192/6ede30fe-9065-11e6-9d83-81c1b2965693.png)

**Comment by leilihuang** [comment]
@silentcloud 在JSX入口文件里面引用了css也没效果

**Comment by yiminghe** [comment]
参考 https://github.com/ant-design/ant-design-mobile/issues/56

不要引 dist css

**Comment by leilihuang** [comment]
@yiminghe  去掉了显示也不对

**Comment by liuyaoao** [comment]
我也遇到了同样的问题，请问下有什么好的解决办法吗？
