### ISSUE TITLE
手风琴报错

### ISSUE THREAD

**Issue by luochunquan** [ant-design/ant-design-mobile#3663]
使用Accordion.Panel 会报如下错误
index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: Animate

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
