### ISSUE TITLE
关于2.3.3版本不能适应最新版本的react的建议

### ISSUE THREAD

**Issue by luochenLing** [ant-design/ant-design-mobile#3668]
里面很多引入的第三方插件会在严格模式下爆出警告，比如list，比如跑马灯，有些react会爆出不安全的生命周期警告，例如输入框、DatePicker等，建议重新引入第三方的插件，使其适应最新版本的react框架

**Comment by awmleer** [comment]
v2 已经停止维护了，v5 支持的
