### ISSUE TITLE
ImagePicker选择完图片显示完整图片而不是缩略图

### ISSUE THREAD

**Issue by sologuy** [ant-design/ant-design-mobile#3670]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
选择的图片完整显示

### What does the proposed API look like?
缩略图能够完整显示

**Comment by awmleer** [comment]
试试 v5 吧：
http://next.mobile.ant.design
