### ISSUE TITLE
antd-mobile v3 建设

### ISSUE THREAD

**Issue by doxiaodong** [ant-design/ant-design-mobile#3671]
3.0.0-alpha.8 2020-11-19
https://next.mobile.ant.design

经过一段时间的前期工作， antd-mobile v3 正式启动，主要在以下方面<br />

<a name="fQACu"></a>
### 视觉规范
遵循最新的 alipay-design 视觉规范 [https://design.alipay.com](https://design.alipay.com/)，对各个组件的使用以及实现彻底的更新，当然，由于视觉变更很大，因此 v3 版本基本上都是破坏性的升级<br />新版设计稿见 sketch 插件 [https://dapollo.alipay.com](https://dapollo.alipay.com/)<br />

<a name="hOqVR"></a>
### 代码升级
新版本全部采用 Function-base 组件写法，也就是 react-hooks ，这样从根本上解决 react 新版本关于 Class-base 组件的生命周期提示<br />

<a name="PTgQi"></a>
### 新的交互 Touchable
在 v2 版本中，基础交互事件是 onClick ，我们推荐引入 fastclick 来解决古老设备上点击延时的体验问题。本来这没什么问题来着，但是我们的一些依赖组件中使用了 touch 为基础的事件交互，导致出现过非常多的点击穿透 issue 。同时由于 fastclick 也是很长时间没有维护，考虑到我们本身定位移动设计，因此全面切换到 touch 事件交互，这个实现是从 react-native-web 的 [Pressable](https://github.com/necolas/react-native-web/tree/master/packages/react-native-web/src/exports/Pressable) 修改而来。

<a name="3jQtj"></a>
### 样式上的收敛
删除所有的 props.style，考虑 style 修改样式的能力有限（深层次的样式无能为力）。但是尽可放心的是你仍然可以快捷的修改样式，通过外挂 className<br />同时抽取全局变量与组件级别变量，同时配合变量自定义的平台，可以实现快速定制皮肤的需求<br />

<a name="0S1RN"></a>
### 按需加载
经常使用 antd 相关的同学应该都知道一个插件 `babel-plugin-import`，虽然它很优秀，但是还是有一些理解成本的。现在我们把这个理解成本降到了 0 ，因为我们不再需要它了。<br />我们的包遵从 webpack 的 tree-shaking 规范，因此，你只需要按最简单的使用方式，即可自动做到按需加载 比如以下使用只会把 Button 相关的代码打包
```json
import { Button } from 'antd-mobile'
<Button></Button>
```

<br />
<br />当然，前提是你的构建工具得开启 tree-shaking。值得高兴的是，现代构建工具基本上都可以轻松支持<br />
<br />

<a name="tfyNZ"></a>
### 更新的 Icon , 更丰富的 Icon
类似 antd v4 的设计，支持图标的按需加载，同时支持自定义的 iconfont
```json
import { Right } from 'antd-mobile-icons'
<Right size="md" />

// 或者
import { Icon } from 'antd-mobile'

const MyIcon = Icon.createFromIconfontCN(
  '//at.alicdn.com/t/font_1511412_ksruzvafwng.js',
)
export default () => <MyIcon type="close-fill" color="red" />
```

<br />

<a name="17eig"></a>
### 多语言设计
组件的文字信息支持中英文显示(默认中文)，实现依赖于 Context，仅需要在应用最外层包裹一次即可全局生效
```typescript
import { LocaleProvider } from 'antd-mobile'
import { en_US, zh_CN } from 'antd-mobile-languages'
const [lang, setLang] = React.useState(zh_CN)
<LocaleProvider value={lang}>
<!-- ... -->
</LocaleProvider>
```

<br />

<a name="KlnSN"></a>
### 暗黑模式
目前 dark-mode 已经成为了每个 app 的标配，作为基础 ui 组件，自然是需要支持的<br />

<a name="IhzJJ"></a>
### 数据统计
轻量级的数据统计，由各组件挂载组件使用统计的钩子，但是官方不提供钩子的具体实现，由使用者自行实现上报方法<br />之所以做数据统计，是为了大家对自己的页面有更好的监控手段，能及时发现组件的问题。当然也能反映出组件的使用热度
> 官方绝对不会默认内置任何上报方法

<br />

<a name="hdJtt"></a>
### 官网设计
采用 [dumi ](https://github.com/umijs/dumi)方案，但是需要做好 iframe 预览以及二维码预览的方案<br />有条件的话可以实现 组件实时构建与预览<br />
<br />

<a name="vxPlb"></a>
### 组件迁移
v2 版本中有不少优秀的组件在新版设计稿中没有体现，我们需要逐步地把这些组件迁移过来<br />
<br />
<br />基本上就是这些了，我们将在不久的将来新建 next 分支，并往上开始添加代码，希望新版本的实现能带给大家带来更好的体验<br />以上任何问题可以直接在下边留言<br />

**Comment by fred8617** [comment]
流弊

**Comment by atom-shanghai** [comment]
流弊 +1

**Comment by Magin-CC** [comment]
考虑啥时候开源，想参与一下

**Comment by alexchen1875** [comment]
希望尽快能把roadmap规划好,在react上,移动端antd-mobile是一个非常好的选择,可以借助社区的力量进行完善和升级.
感谢团队带来这么优秀的库. :)

**Comment by doxiaodong** [comment]
现在 react 的最佳测试代码的实践有推荐么

**Comment by citrusjunoss** [comment]
今年能落地么

**Comment by chenqincheng** [comment]
希望尽快能把roadmap规划好 +1
今年能落地么 +1

**Comment by memotail** [comment]
迫不及待，roadmap、第一个版本

**Comment by afc163** [comment]
> antd-mobile-icons

这个和 antd 的 icons 有啥区别，能不能共享一份就行？

**Comment by afc163** [comment]
```diff
- import { en_US, zh_CN } from 'antd-mobile-languages'
- import { en_US, zh_CN } from 'antd-mobile/locales';
```

建议这样。

**Comment by afc163** [comment]
`antd-mobile` 考虑改成 `@ant-design/mobile` 不？

**Comment by alexchen1875** [comment]
> > antd-mobile-icons
> 
> 这个和 antd 的 icons 有啥区别，能不能共享一份就行？

现在自带的icon太少,只能通过[iconfont](https://www.iconfont.cn/)来自定义实现为了整体的样式统一还是需要内置

**Comment by xiaohuoni** [comment]
> 采用 dumi 方案，但是需要做好 iframe 预览以及二维码预览的方案

<img width="1438" alt="version01" src="https://user-images.githubusercontent.com/11746742/88038937-7f925800-cb79-11ea-83ab-7495c18889be.png">

> 有条件的话可以实现 组件实时构建与预览

![vension01bug](https://user-images.githubusercontent.com/11746742/88039003-a05aad80-cb79-11ea-8639-9e2e046c801a.gif)

不知道你们打算怎么设计，我搞了个方案， https://github.com/alitajs/dumi-theme-alita 如果这一块还没有人做，可以给我提需求，我来实现。

**Comment by flasco** [comment]
非常期待。目前 react 在移动端的 ui 库方面感觉比较欠缺

**Comment by doxiaodong** [comment]
@xiaohuoni 功能就是 多起一个 server 来运行带 hd 等移动端特有的配置，然后通过 iframe 加载。

**Comment by doxiaodong** [comment]
@偏右
> 另外其他衍生包也可以考虑放 @ant-design 下

改名是可以的，本来就因为要考虑 2和3 可能共存的情况也要改个名

**Comment by doxiaodong** [comment]
预计下周三上传初版代码

**Comment by xiaohuoni** [comment]
> @xiaohuoni 功能就是 多起一个 server 来运行带 hd 等移动端特有的配置，然后通过 iframe 加载。

功能实现了，看看布局要怎么比较好。

**Comment by Mr-Kapok** [comment]
样式变量是否考虑使用css变量，更方便换肤已经重新定制

**Comment by leesama** [comment]
顶

**Comment by ypli0629** [comment]
> 预计下周三上传初版代码

期待

**Comment by ditoukanyun** [comment]
终于有更新了,期待

**Comment by DreamPWJ** [comment]
1. 新版有没有新增组件或者对 组件属性增强
2. 新版是否探索微信或支付宝小程序原生组件上运行 而不是H5嵌入方式 @doxiaodong

**Comment by chenqincheng** [comment]
> 预计下周三上传初版代码

等不到啊`  今天周四

**Comment by doxiaodong** [comment]
here: https://github.com/ant-design/ant-design-mobile/tree/next

**Comment by afc163** [comment]
我建议是新包名都放 @ant-design 这个 scope 下，可以找我加 npm 权限。

**Comment by doxiaodong** [comment]
好，我把 Form 写了开始 alpha，到时候找你

**Comment by panZongLin** [comment]
期待中，加油啊

**Comment by liucien** [comment]
DatePicker 与 Calendar 组件能支持到秒数么，现在没有秒的选项

**Comment by doxiaodong** [comment]
> DatePicker 与 Calendar 组件能支持到秒数么，现在没有秒的选项

👌

**Comment by chenqincheng** [comment]
什么时候可以通过npm install 使用呢

**Comment by doxiaodong** [comment]
> 什么时候可以通过npm install 使用呢

如果现在像尝试早期版本的话，我晚点时候发一个 alpha 包吧

**Comment by zytjs** [comment]
@doxiaodong 请问V3是什么规划？想参与一下，有什么我能做的吗

**Comment by doxiaodong** [comment]
> @doxiaodong 请问V3是什么规划？想参与一下，有什么我能做的吗

可以看一下这里 https://github.com/ant-design/ant-design-mobile/projects/5

**Comment by chenqincheng** [comment]
> > 什么时候可以通过npm install 使用呢
> 
> 如果现在像尝试早期版本的话，我晚点时候发一个 alpha 包吧
发一个 alpha 包，想尝试早期版本，如果有issue，也能及时反馈给社区，谢谢了~

**Comment by chenqincheng** [comment]
> > 什么时候可以通过npm install 使用呢
> 
> 如果现在像尝试早期版本的话，我晚点时候发一个 alpha 包吧


@doxiaodong 发一个 alpha 包，想尝试早期版本，如果有issue，也能及时反馈给社区，谢谢了~

**Comment by hopperhuang** [comment]
长期跟中此issue

**Comment by atom-shanghai** [comment]
今年能落地吗？

**Comment by atom-shanghai** [comment]
> > @doxiaodong 请问V3是什么规划？想参与一下，有什么我能做的吗
> 
> 可以看一下这里 https://github.com/ant-design/ant-design-mobile/projects/5

今年能落地吗？

**Comment by lirunwin** [comment]
说好的的alpha呢

**Comment by chenqincheng** [comment]
> 说好的的alpha呢

@doxiaodong 我也在等alpha版本

**Comment by doxiaodong** [comment]
![image](https://user-images.githubusercontent.com/6927481/90417710-b57a1c00-e0e6-11ea-82ec-ded20dbcaf79.png)
尝试好几天了，公司的电脑和家里的 windows 都不行

**Comment by lirunwin** [comment]
> ![image](https://user-images.githubusercontent.com/6927481/90417710-b57a1c00-e0e6-11ea-82ec-ded20dbcaf79.png)
> 尝试好几天了，公司的电脑和家里的 windows 都不行

vpn香

**Comment by doxiaodong** [comment]
手动发布  @ant-design/mobile  3.0.0-alpha.1

**Comment by atom-shanghai** [comment]
手动发布 @ant-design/mobile 3.0.0-alpha.1

**Comment by benx-wang** [comment]
大佬，升级文档，能否给一个？

> 手动发布 @ant-design/mobile 3.0.0-alpha.1

**Comment by TnWah** [comment]
期待V3落地，跟Vue的比起来的确感觉react的mobile端好少~~

**Comment by Wuguanghua** [comment]
啥时候能落地呀，迫不及待想要用了，react的移动端组件库太少了~

**Comment by moonlitusun** [comment]
第一次用v2 就用了几个组件 bug也太多了 希望有时间和精力的话可以处理下

**Comment by doxiaodong** [comment]
> 大佬，升级文档，能否给一个？
> 
> > 手动发布 @ant-design/mobile 3.0.0-alpha.1

没有升级文档，变动很大。

**Comment by liuqh0609** [comment]
很期待啊，会持续关注的，希望有机会可以参与到项目的建设中来~

**Comment by Rannie** [comment]
支持，持续关注下，辛苦了~

**Comment by citrusjunoss** [comment]
ListView 好像新版找不到了

**Comment by feibi** [comment]
v3 主题如何改

**Comment by spikespiegel5112** [comment]
迫切希望对表单功能做完善。现在的表单验证只能验证input控件，我需要能对radio，picker，checkbox，以及自定义组件的表单验证机制。现在的这个漏洞百出。

**Comment by arcsin1** [comment]
什么时候正式版啊

**Comment by lirunwin** [comment]
啥时候beta就好了。等不及了。react做h5太痛苦。v2蛋疼

**Comment by atom-shanghai** [comment]
还停留在v3.0.0-alpha.4，加油

**Comment by zemelLeong** [comment]
加油  奥里给

**Comment by GreatAuk** [comment]
散了吧，v3.0.0 已经一个多月没更新了😭

**Comment by steady-join** [comment]
更新了记得踹我一下

**Comment by zemelLeong** [comment]
ant-mobile 更新日，家祭勿忘告乃翁

**Comment by zhanghesong** [comment]
加油

**Comment by xclw2000** [comment]
我等的花都开了，啥时候能release呀

**Comment by lcx-seima** [comment]
- API 设计希望尽可能和 antd 对齐，如 Modal 的 actions 就很特殊
- 类似 Drawer 的组件更简洁点，就是个容器
- 长 List 的使用成本较高
- 希望通过 props 多预设几个 Modal （比如需要一个 slide 动画，现在要传很多多余的 props）
- Modal 的 iOS 穿透滑动问题

**Comment by doxiaodong** [comment]
v3.0.0-alpha.5 重构了表单相关的组件

**Comment by Viin-zx** [comment]
加油，期待ing...

**Comment by chj-damon** [comment]
真棒！加油！

**Comment by legend80s** [comment]
品牌色能否更新下呢？

**Comment by doxiaodong** [comment]
@legend80s https://next.mobile.ant.design/wiki/less-variables 可以通过变量修改，但是目前的变量我们可能会做一次 review。

**Comment by darkmice** [comment]
https://next.mobile.ant.design 今天无法打开了

**Comment by WinterWoods** [comment]
测试一下，整体流畅度与成熟度还是不及antd，加油，期待正式上线。移动端是刚需，现在在用Vant Weapp

**Comment by shengxinjing** [comment]
给力给力，一起贡献，为antd-mobile添砖加瓦

**Comment by xclw2000** [comment]
有没有进入明细页面，然后顶部可以返回上一步，并且具有渐变效果的组件？

**Comment by xclw2000** [comment]
怎么和umi集成呀。有没有类似pc端的安装工作或者脚手架？

**Comment by GreatAuk** [comment]
为什么不在 2.0 的文档上放一个 3.0 文档的入口呢？不看 issue, 估计大多数人都不知道 3.0 已经更新了。我看现在 3.0 下载量少的可怜。
![image](https://user-images.githubusercontent.com/20253809/102175804-1bcb4b80-3edb-11eb-9a49-27736ff54691.png)

**Comment by steadyzeus** [comment]
next 3.0 什么时候发正式版呢？

**Comment by whevether** [comment]
> 怎么和umi集成呀。有没有类似pc端的安装工作或者脚手架？
可以看看我自己配置的一个简易模版。webpack 都暴露出来了。打包之后体积要比umi小。直接clone 下来之后安装@antd/mobile引入就能用了。支持多种布局.
https://github.com/whevether/react-template

**Comment by Jairwin-L** [comment]
有计划支持类似`popup`弹出层组件？
https://youzan.github.io/vant/#/zh-CN/popup

**Comment by aushion** [comment]
期待正式发布

**Comment by vvni** [comment]
现在立刻马上开始使用-。-

**Comment by vvni** [comment]
@doxiaodong 请问什么时候添加Navbar组件呀？

**Comment by zzzzyp** [comment]
希望InputItem能加个maxLength限制

**Comment by vvni** [comment]
next.js使用该组件库报错

```
error - ./node_modules/normalize.css/normalize.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@ant-design/mobile-styles/lib/base/index.js
```

**Comment by pecora9264** [comment]
大佬们，今年还有希望看见稳定版本吗？

**Comment by kokiy** [comment]
期待 ali react 开源生态做得很棒啦 antd antd-mobile formily , antv umijs dumi 等等

**Comment by xclw2000** [comment]
建议参考[http://www.framework7.cn/](http://www.framework7.cn/)中某些组件的功能

**Comment by Dootechdev** [comment]
真是尴尬的时期... 好像2个月没动静了; 春节前还有希望看到正式版？

**Comment by kokiy** [comment]
> 建议参考http://www.framework7.cn/中某些组件的功能

现在都ios 14 le

**Comment by whevether** [comment]
烂尾了？ 两个月没动静了

**Comment by xclw2000** [comment]
> > 建议参考[http://www.framework7.cn/中某些组件的功能](http://www.framework7.cn/%E4%B8%AD%E6%9F%90%E4%BA%9B%E7%BB%84%E4%BB%B6%E7%9A%84%E5%8A%9F%E8%83%BD)
> 
> 现在都ios 14 le

ios 14跟framework7啥关系

**Comment by steady-join** [comment]
没动静了吗？

**Comment by steady-join** [comment]
没动静了吗？

**Comment by sky185959** [comment]
期待早点正式发布。。。

**Comment by codedart2018** [comment]
新项目直接上嘛。好期待呀！

**Comment by GreatAuk** [comment]
拉倒，三个多月没更新了

**Comment by codedart2018** [comment]
> 拉倒，三个多月没更新了

哈哈，我新项目拿来试试手。　yarn add @ant-design/mobile 走起。现在的react版本都到17.x去了。这个2.x还在用16.x

**Comment by codedart2018** [comment]
喵了一眼。看了下源码不是很有源码都看了。但是好多组件都没有把默认的className style给挂载上去啊。我自己想额外挂载样式类我还得在外面套一层div。这就太过分了吧！

**Comment by atom-shanghai** [comment]
可以考虑下 zarm，基于React、React-Native 研发的一款适用于企业级的移动端UI组件库

**Comment by jivinliu** [comment]
v3大概什么时候会正式发布？

**Comment by alexchen1875** [comment]
> 可以考虑下 zarm，基于React、React-Native 研发的一款适用于企业级的移动端UI组件库
如果antd这边不在有新的计划的话,zarm应该是个不错的选择.至少一直在进行更新,但是star太少了.还没有很多的issue

**Comment by zmyjs** [comment]
```
import {
  unstable_Button as Button,
  unstable_Modal as Modal,
} from '@ant-design/mobile'
```
这种使用方式只是临时吧？

**Comment by jockey100332** [comment]
> ```
> import {
>   unstable_Button as Button,
>   unstable_Modal as Modal,
> } from '@ant-design/mobile'
> ```
> 
> 这种使用方式只是临时吧？

感觉这样的引入方式更像某一个插件.感觉很别扭

**Comment by shuaizhouliu** [comment]
> 有没有进入明细页面，然后顶部可以返回上一步，并且具有渐变效果的组件？

这个确实是需求很强的功能

**Comment by yeml5** [comment]
居然还不更新，我太失望了

**Comment by kokiy** [comment]
@yeml5 自己提pr

**Comment by atom-shanghai** [comment]
这么久了，还没更新

**Comment by kokiy** [comment]
有没有知道 ionic react 可以直接结合umijs 框架吗

**Comment by kokiy** [comment]
我今天搞了一下 umi 集成 ionic react, 感觉很棒 路由动画啥都有,

**Comment by vvni** [comment]
> 我今天搞了一下 umi 集成 ionic react, 感觉很棒 路由动画啥都有,

发出来观摩一下

**Comment by kokiy** [comment]
https://github.com/kokiy/umi-h5-template/tree/main-ionic  @vvni  先简单测试了一下没有啥问题 后期还要完善

**Comment by vvni** [comment]
> https://github.com/kokiy/umi-h5-template/tree/main-ionic @vvni 先简单测试了一下没有啥问题 后期还要完善

我感觉可以用vite+ionic代替这些了. 回头试试

**Comment by liaokaime** [comment]
快4个月了，一直停留在alpha.8版本，看起来要流产了

**Comment by droidsde** [comment]
太监了？

**Comment by dengshicheng1996** [comment]
> 新项目直接上嘛。好期待呀！

你在新项目上上了v3?

**Comment by tangdw** [comment]
现在 h5 的 react 组件库还有那些选择呢？

**Comment by kokiy** [comment]
> 现在 h5 的 react 组件库还有那些选择呢？

ionic

**Comment by vvni** [comment]
Zarm，可暂时替代.

**Comment by vvni** [comment]
白嫖怪们，自己写靠谱🤧

**Comment by jianghai** [comment]
关注

**Comment by specialgirlgotoheaven** [comment]
> here: https://github.com/ant-design/ant-design-mobile/tree/next

请问什么时候继续更新？

**Comment by skywalkerlw** [comment]
有进一步计划吗？

**Comment by specialgirlgotoheaven** [comment]
有进一步计划吗？

**Comment by lifegit** [comment]
你们有结合umi ssr的吗？

[SSR] stream render / start: 134.98ms
ERROR [SSR] ReferenceError: window is not defined
    at Module../node_modules/@ant-design/mobile/es/PullToRefresh/dep/index.js (/Users/yxs/WebstormProjects/myapptt/dist/umi.server.js:15709:27)
    at __webpack_require__ (/Users/yxs/WebstormProjects/myapptt/dist/umi.server.js:21:30)
    at Module../node_modules/@ant-design/mobile/es/PullToRefresh/index.js (/Users/yxs/WebstormProjects/myapptt/dist/umi.server.js:15726:62)
    at __webpack_require__ (/Users/yxs/WebstormProjects/myapptt/dist/umi.server.js:21:30)
    at Module../node_modules/@ant-design/mobile/es/index.js (/Users/yxs/WebstormProjects/myapptt/dist/umi.server.js:18952:73)
    at __webpack_require__ (/Users/yxs/WebstormProjects/myapptt/dist/umi.server.js:21:30)
    at Module../src/pages/index.tsx (/Users/yxs/WebstormProjects/myapptt/dist/umi.server.js:110940:76)
    at __webpack_require__ (/Users/yxs/WebstormProjects/myapptt/dist/umi.server.js:21:30)
    at render (/Users/yxs/WebstormProjects/myapptt/dist/umi.server.js:110179:20)
    at runMicrotasks (<anonymous>)

**Comment by shuaizhouliu** [comment]
为什么太监了，好想知道原因。。。。

**Comment by aladdin-add** [comment]
莫名其妙就没有下文了，做事能不能专业一点。既然是开源项目，决策流程/开发进度应该尽可能透明。在这点上，好好学学react团队吧。

issue也没人维护，antd的招牌快被你们这样搞的**** trust - it is easy to be destroyed, but hard to be restored.

**Comment by isxiaoxin** [comment]
今年能落地么 +1

**Comment by hqwlkj** [comment]
v3大概什么时候会正式发布？

**Comment by msdlisper** [comment]
哎, 有进展么

**Comment by atom-shanghai** [comment]
憋大招呢，说不准给大家个惊喜

**Comment by codedart2018** [comment]
> 憋大招呢，说不准给大家个惊喜

你怕是昨晚没睡醒

**Comment by langengel** [comment]
移植出问题了

**Comment by WinterWoods** [comment]
官方给个消息也行啊。如果难产就开源出来，让大家维护么

**Comment by codedart2018** [comment]
> 官方给个消息也行啊。如果难产就开源出来，让大家维护么

这就是阿里的风格，我最后去用众安的了。但是众安版本开发完了，我想我还是去用vue的了吧。必定vue ui选择更多些。react端的可选择实在可怜。

**Comment by lmxyjy** [comment]
气抖冷，react移动端ui组件库什么时候能站起来！

**Comment by lifegit** [comment]
偷偷告诉你，10月就会有消息

**Comment by codedart2018** [comment]
> 偷偷告诉你，10月就会有消息

信你个鬼

**Comment by liaokaime** [comment]
> 偷偷告诉你，10月就会有消息

到时候的消息不会是宣布放弃吧（狗头）

**Comment by lifegit** [comment]
当然不是，

> > 偷偷告诉你，10月就会有消息
> 
> 到时候的消息不会是宣布放弃吧（狗头）

当然不是啦，你也可以看看别的ui库
[UI 库](https://www.yuque.com/mingzibaliao/web/xavd4o)

**Comment by shuaizhouliu** [comment]
> 当然不是，
> 
> > > 偷偷告诉你，10月就会有消息
> > 
> > 
> > 到时候的消息不会是宣布放弃吧（狗头）
> 
> 当然不是啦，你也可以看看别的ui库
> [UI 库](https://www.yuque.com/mingzibaliao/web/xavd4o)

原来太监了是因为负责人已离职了吗？

**Comment by zjfjiayou** [comment]
web版本没人管了，现在主要维护的是rn版本 
https://github.com/ant-design/ant-design-mobile-rn/

**Comment by HaishengLiang** [comment]
V3 还有后续规划吗？

**Comment by zjjjjjjjjjjd** [comment]
不想再用antd-moblie了，一堆问题还不更新，求问大佬们 zarm好用吗？QAQ（公司要求一定要react）

**Comment by codedart2018** [comment]
> 不想再用antd-moblie了，一堆问题还不更新，求问大佬们 zarm好用吗？QAQ（公司要求一定要react）

不是太好用！但总比没得选择好！　这个看起来不错　https://nsfi.github.io/fishd-mobile-site/index.html#/zh-CN/home　但里面有个致命的缺点，少listview 　上拉加载　下拉刷新。其它看起来还不错。我这个版本做完要么投到 京东怀抱　还么跑去uniapp.　react 移动端基本没选择的。

**Comment by lmxyjy** [comment]
> 不想再用antd-moblie了，一堆问题还不更新，求问大佬们 zarm好用吗？QAQ（公司要求一定要react）

或许你可以试一试这个，https://github.com/alitajs/alita

**Comment by shuaizhouliu** [comment]
> 不想再用antd-moblie了，一堆问题还不更新，求问大佬们 zarm好用吗？QAQ（公司要求一定要react）

因为react好用啊

**Comment by awmleer** [comment]
大家再等等，我们正在对整个组件库进行重写

**Comment by codedart2018** [comment]
> 大家再等等，我们正在对整个组件库进行重写

确定　还是逗大家的

**Comment by awmleer** [comment]
@codedart2018 确定，目前大概40%的进展了

**Comment by atom-shanghai** [comment]
计划什么时候发版？

**Comment by awmleer** [comment]
@atom-shanghai 目前还没有明确的时间节点，但是按照目前的进度，大概还需要3个月的时间

**Comment by lmxyjy** [comment]
> @atom-shanghai 目前还没有明确的时间节点，但是按照目前的进度，大概还需要3个月的时间

会更新到本仓库吗，还是新发布一个仓库？

**Comment by awmleer** [comment]
@lmxyjy 目前还不确定是否会继续沿用这个仓库，我们现在是在另一个内部的仓库中进行开发的

**Comment by shuaizhouliu** [comment]
只要没太监就行，能等😂

**Comment by liaokaime** [comment]
要为react移动端的荣誉而战

**Comment by awmleer** [comment]
> 要为react移动端的荣誉而战

嗯嗯目标就是做全世界最好的React移动端组件库

**Comment by froyo-naux** [comment]
希望drawer组件改成和antd的drawer一样

**Comment by CaicoLeung** [comment]
现在React的移动端UI组件都没有vue的丰富啊, 求antd mobile3快出

**Comment by codedart2018** [comment]
> > 要为react移动端的荣誉而战
> 
> 嗯嗯目标就是做全世界最好的React移动端组件库

听你吹牛逼

**Comment by zemelLeong** [comment]
> > 要为react移动端的荣誉而战
> 
> 嗯嗯目标就是做全世界最好的React移动端组件库

加油啊，为移动端而战的大哥哥

**Comment by ppbl** [comment]
@awmleer 重写是把现在放出来的的 3.x 的 alpha 版本也给推翻了吗

**Comment by awmleer** [comment]
@ppbl 是的

**Comment by 0x219** [comment]
> @ppbl 是的

底层基础组件也都自己写？不用rc-component?

**Comment by awmleer** [comment]
@0x219 只有非常少量的依赖

**Comment by 0x219** [comment]
> @0x219 只有非常少量的依赖

可以的。仓库地址有计划什么时候公开嘛？

**Comment by awmleer** [comment]
@0x219 目前还没有准确的计划

**Comment by G-G-boy** [comment]
@awmleer 支持RN吗？

**Comment by awmleer** [comment]
> @awmleer 支持RN吗？

不支持

**Comment by yangdepp** [comment]
> > @awmleer 支持RN吗？
> 
> 不支持

请问这个放出来的V5版本就是新版本的吗？

**Comment by atom-shanghai** [comment]
5.0是重新写的？

**Comment by awmleer** [comment]
> 请问这个放出来的V5版本就是新版本的吗？

@yangdepp 是的，还在开发中

**Comment by awmleer** [comment]
> 5.0是重新写的？

@atom-shanghai 是的

**Comment by uptonking** [comment]
>  只有非常少量的依赖

@awmleer 
那太好了，ant-design里的组件普遍依赖太多了，理解和修改都会搞得人心态爆炸；
我最近对adobe的react-spectru组件库看得比较多，将组件的样式、行为、状态尽可能拆开复用，他们花了很大精力实现a11y，我觉得适合antd-mobile可以先直接拿过来用，以后再用自研的替换他们的

**Comment by awmleer** [comment]
@uptonking 嗯嗯可以多交流交流～未来 antd-mobile 也肯定是需要支持 a11y 的

**Comment by lifegit** [comment]
老哥，继续用 https://next.mobile.ant.design/ 是不是不太美妙呀！
要是有人用了上个版本在生产里。那人家现在修个bug，连个文档都没了。。
@awmleer

**Comment by awmleer** [comment]
> 老哥，继续用 https://next.mobile.ant.design/ 是不是不太美妙呀！
> 要是有人用了上个版本在生产里。那人家现在修个bug，连个文档都没了。。
> @awmleer

@lifegit 部署到另一个站点了：https://antd-mobile-v3.surge.sh
后面我在文档上也注明一下，感谢反馈～

**Comment by kokiy** [comment]
@awmleer 啥时候发一个版本 体验一下哈

**Comment by steady-join** [comment]
恕我直言，UI需要优化。

**Comment by awmleer** [comment]
> 恕我直言，UI需要优化。

嗯嗯我们还会再仔细打磨的

**Comment by JiangJingxuan** [comment]
v5版本跟umi一起使用会报错，请问有解决办法吗
`* antd-mobile/es/button in ./src/pages/index.tsx
* antd-mobile/es/button/style in ./src/pages/index.tsx`
@awmleer

**Comment by awmleer** [comment]
> v5版本跟umi一起使用会报错，请问有解决办法吗
> `* antd-mobile/es/button in ./src/pages/index.tsx
> 
> * antd-mobile/es/button/style in ./src/pages/index.tsx`
>   @awmleer

@JiangJingxuan 把 babel-plugin-import 关掉就可以了，现在 v5 还不支持 babel-plugin-import，文档上我也写一下

**Comment by JiangJingxuan** [comment]
> > v5版本跟umi一起使用会报错，请问有解决办法吗
> > `* antd-mobile/es/button in ./src/pages/index.tsx
> > 
> > * antd-mobile/es/button/style in ./src/pages/index.tsx`
> >   @awmleer
> 
> @JiangJingxuan 把 babel-plugin-import 关掉就可以了，现在 v5 还不支持 babel-plugin-import，文档上我也写一下

搞定了，谢了，生产环境在用，希望越来越完善

**Comment by awmleer** [comment]
如果需要访问 v3 的文档站点的话，可以去这里：https://antd-mobile-v3.surge.sh/
