### ISSUE TITLE
外部事件触发Accordion 折叠

### ISSUE THREAD

**Issue by shenzheniapps** [ant-design/ant-design-mobile#3673]
外部事件触发Accordion 折叠 ，自己找了很久但是没有发现有人遇到这个问题，或者说没有人和我有一样的需求， 这里粘贴我的解决方案，希望能帮助有需要的人。

`componentDidMount() {
        this.accordionElement = null
        // page completed ...
    }`

`<Accordion className="delivery-accordion" onChange={this.onChange}>
                                                                <Accordion.Panel ref={accordion => this.accordionElement = accordion}  key="0" header={}>
                                                                    <List className="delivery-list">
                                                                    </List>
                                                                </Accordion.Panel>
                                                            </Accordion>`

主要是 给ref={accordion => this.accordionElement = accordion} 
然后在 外部事件的时候需要关闭的话

`this.accordionElement.handleItemClick()   `
执行这句话 ，就可以了。看着很简单吧， 但是让我自己研究了很久， 哎！！！！
送人玫瑰~~~~什么来着😂

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
