### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by doxiaodong** [ant-design/ant-design-mobile#3685]
切换至 https://github.com/nolimits4web/swiper

**Comment by zytjs** [comment]
这个我来试一下？不知道能不能胜任😂，大佬有时间限制吗

**Comment by doxiaodong** [comment]
> 这个我来试一下？不知道能不能胜任😂，大佬有时间限制吗

你先把你想要做出来的 api 列出来，然后提交后我先 review

**Comment by zytjs** [comment]
OK

**Comment by zytjs** [comment]
@doxiaodong 整理了一部分API，突然发现 https://github.com/nolimits4web/swiper 的参数有很多，分的很详细，有什么依据来整理吗？应该用不到所有的参数吧

**Comment by doxiaodong** [comment]
这个我写了个初版的

**Comment by zytjs** [comment]
后期是要把swiper依赖替换掉吗

**Comment by beimuaihui** [comment]
v3 alpha8分支上面 import '@ant-design/mobile-styles/dist/antd-mobile-style.css';没有swiper样式？
