### ISSUE TITLE
Skeleton support for antd-mobile

### ISSUE THREAD

**Issue by srameshr** [ant-design/ant-design-mobile#3687]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Introduce Skeleton component for mobile browsers.

### What does the proposed API look like?
Same as the antd web / desktop version

**Comment by srameshr** [comment]
Anything on this?

**Comment by GOWxx** [comment]
> Anything on this?

https://mobile.ant.design/zh/components/skeleton/skeleton
