### ISSUE TITLE
日期 range 查询bug

### ISSUE THREAD

**Issue by SlimJason** [ant-design/ant-design-mobile#369]
#### 本地环境

- antd版本：1.1.0
- 操作系统及其版本：safari 10.0
- 浏览器及其版本：mac os 10.12

#### 你做了什么？

日期查询range，选了开始、结束日期时候，占位符和所选日期重叠，而且，传到后台的是undefied

#### 你期待的结果是：

![image](https://cloud.githubusercontent.com/assets/5801796/19302470/db1cd294-9096-11e6-9def-536efabd9177.png)

#### 实际上的结果：
![image](https://cloud.githubusercontent.com/assets/5801796/19302433/a80c247c-9096-11e6-9716-0c901f0f7e33.png)

**Comment by SlimJason** [comment]
有时候会出现，有时候不会，新版safari

**Comment by warmhug** [comment]
pc 的提到这里 https://github.com/ant-design/ant-design/issues
