### ISSUE TITLE
[v3] 文件引用错误

### ISSUE THREAD

**Issue by lirunwin** [ant-design/ant-design-mobile#3691]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/tab-bar/](https://mobile.ant.design/components/tab-bar/)

### Steps to reproduce
链接随便填的, 这个应该不需要重现链接

### What is expected?
-

### What is actually happening?
This relative module was not found:

* ../../antd-mobile-styles/lib/Icon in ./node_modules/@ant-design/mobile-icons/es/BaseIcon.js

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.x |
| System | windows |
| Browser | chorme |

---
我猜应该是想引用 ../../mobile-styles/lib/Icon 这个文件

**Comment by awmleer** [comment]
感谢反馈，但是 v3 已不再维护
