### ISSUE TITLE
Calendar 日历组件 在时区不同的电脑上会出现月份日期显示错误

### ISSUE THREAD

**Issue by xiayuegit** [ant-design/ant-design-mobile#3692]
Reproduction link
https://mobile.ant.design/components/calendar-cn/

Steps to reproduce
Switch the computer's time zone to Vancouver, and then refresh the page to view November 2020. It is found that there are two No.1 in November, and the end date cannot be selected

What is expected?
The display is normal

What is actually happening?
When viewing the underlying library m-calendar, it is found that DatePicker.base.tsx There is a problem with the genweekdata method in. The increment of days may be affected by the time zone. You can use moment to solve this problem

Environment | Info
-- | --
System | mac
Browser | chrome

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
