### ISSUE TITLE
InputItem 里的样式与官方演示的不一致，而且清除按钮的样式严重变形

### ISSUE THREAD

**Issue by CherishTheYouth** [ant-design/ant-design-mobile#3695]
![image](https://user-images.githubusercontent.com/41944818/91279686-656f1980-e7b8-11ea-800c-3cb67aa00dd9.png)
![image](https://user-images.githubusercontent.com/41944818/91279726-73249f00-e7b8-11ea-83da-f865f17f8dec.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
