### ISSUE TITLE
picker 加载大数据 会有卡顿

### ISSUE THREAD

**Issue by hms181231** [ant-design/ant-design-mobile#3699]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能否支持虚拟dom加载 或者 自定义picker的数据展示组件

### What does the proposed API look like?
增加虚拟dom加载处理

**Comment by awmleer** [comment]
可以考虑升级到 v5 版本的 Picker 组件试试
