### ISSUE TITLE
ListView 无限列表问题 web环境下

### ISSUE THREAD

**Issue by weiq** [ant-design/ant-design-mobile#370]
#### 本地环境

- antd-mobile 版本：最新
- 操作系统及其版本：chrome

#### 你做了什么？
使用官网https://mobile.ant.design/components/list-view/无限列表示例，并修改渲染函数
1. 当ListView出现滚动条时可以无限下拉，当回到最上一条时发现是从row -20开始的，而不是最初的第一条row - 0。
2.  当ListView不出现滚动条时即让CodePen下方区域最大时，只显示了10条数据（应该是20条数据）并且不能无限滚动。

#### 可重现的在线演示
https://codepen.io/weiq/pen/WGJqLb?editors=0010

**Comment by warmhug** [comment]
在手机上测试，不要在 pc 上测

**Comment by guangming21** [comment]
无限列表怎么解决的

**Comment by warmhug** [comment]
对照下 demo ，看看是不是高度设置有问题
