### ISSUE TITLE
在 create-react-app 中使用 标题 按需加载 文字有语病

### ISSUE THREAD

**Issue by danielgzd** [ant-design/ant-design-mobile#3707]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/docs/react/use-with-create-react-app-cn](https://mobile.ant.design/docs/react/use-with-create-react-app-cn)

### Steps to reproduce
引入 react-app-rewired 并修改 package.json 里的启动配置。。由于新的 react-app-rewired@2.x 版本的关系，你需要还需要安装 customize-cra。

### What is expected?
引入 react-app-rewired 并修改 package.json 里的启动配置。。由于新的 react-app-rewired@2.x 版本的关系，你还需要安装 customize-cra。

### What is actually happening?
引入 react-app-rewired 并修改 package.json 里的启动配置。。由于新的 react-app-rewired@2.x 版本的关系，你需要还需要安装 customize-cra。

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 无 |
| System | 无 |
| Browser | chrome85 |

---
需要还需要是什么？？？？

**Comment by awmleer** [comment]
Outdated
