### ISSUE TITLE
在React Native中使用TabBar多个界面的内容重叠在了一起

### ISSUE THREAD

**Issue by lukecheng** [ant-design/ant-design-mobile#371]
#### 本地环境

- antd-mobile 版本：0.9.2
- 操作系统及其版本：红米Note2， Android4.4
- 浏览器及其版本：

#### 你做了什么？

在React Native中使用TabBar显示多个界面

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

多个界面的内容重叠在了一起

#### 可重现的在线演示

![2016101201](https://cloud.githubusercontent.com/assets/1140785/19304701/60dd7344-90a0-11e6-848a-a59b975efb4b.png)

**Comment by lukecheng** [comment]
附上代码：
`import React, { Component } from 'react';
import {
    AppRegistry,
    Text,
    View
} from 'react-native';

import TabBar from 'antd-mobile/lib/tab-bar';

class FirstPage extends Component {
	render() {
		return <View>
			<Text>First page</Text>
		</View>;
	}
}

class SecondPage extends Component {
	render() {
		return <View>
			<Text>Second page</Text>
		</View>;
	}
}

class ThirdPage extends Component {
	render() {
		return <View>
			<Text>Third page</Text>
		</View>;
	}
}

class TabBarExample extends Component {
  constructor(props) {
	super(props)
	
    this.state = {
      selectedTab: 'redTab',
      hidden: false,
    };
  }
  
  renderContent(pageId) {
    switch (pageId) {
		case 0:
			return <FirstPage />;
		case 1:
			return <SecondPage />;
		case 2:
			return <ThirdPage />
	}
  }
  
  render() {
    return (
      <TabBar
        unselectedTintColor="#949494"
        tintColor="#33A3F4"
        barTintColor="white"
        hidden={this.state.hidden}
      >
        <TabBar.Item
          icon={{ uri: 'https://zos.alipayobjects.com/rmsportal/UNQhIatjpNZHjVf.png' }}
          selectedIcon={{ uri: 'https://zos.alipayobjects.com/rmsportal/HLkBvJOKnmOfBPO.png' }}
          title="口碑"
          key="口碑"
          badge={1}
          selected={this.state.selectedTab === 'redTab'}
          onPress={() => {
            this.setState({
              selectedTab: 'redTab',
            });
          }}
        >
          {this.renderContent(0)}
        </TabBar.Item>
        <TabBar.Item
          icon={{ uri: 'https://zos.alipayobjects.com/rmsportal/EljxLrJEShWZObW.png' }}
          selectedIcon={{ uri: 'https://zos.alipayobjects.com/rmsportal/LWNaMdwAFSmYBFw.png' }}
          title="朋友"
          key="朋友"
          selected={this.state.selectedTab === 'greenTab'}
          onPress={() => {
            this.setState({
              selectedTab: 'greenTab',
            });
          }}
        >
          {this.renderContent(1)}
        </TabBar.Item>
        <TabBar.Item
          icon={{ uri: 'https://zos.alipayobjects.com/rmsportal/YWpPVCVOnJoCYhs.png' }}
          selectedIcon={{ uri: 'https://zos.alipayobjects.com/rmsportal/WadBBxOIZtDzsgP.png' }}
          title="我的"
          key="我的"
          selected={this.state.selectedTab === 'yellowTab'}
          onPress={() => {
            this.setState({
              selectedTab: 'yellowTab',
            });
          }}
        >
          {this.renderContent(2)}
        </TabBar.Item>
      </TabBar>
    );
  }
}

AppRegistry.registerComponent('rtest', () => TabBarExample);`

**Comment by silentcloud** [comment]
react-native 用的什么版本？ @lukecheng

**Comment by weiq** [comment]
是不是背景透明的原因

**Comment by lukecheng** [comment]
@silentcloud react-native用的是0.35

**Comment by silentcloud** [comment]
@lukecheng  Tabbar 用了 zIndex 的 css 属性，确保版本 ok，还有楼上说的背景问题

![image](https://cloud.githubusercontent.com/assets/1698185/19305031/b9bf8bcc-90a1-11e6-9c39-8791278059b6.png)

**Comment by lukecheng** [comment]
Tx，是@weiq 说的背景透明的问题
