### ISSUE TITLE
通过CDN引入antd-mobile，会报错Uncaught ReferenceError: mobile is not defined

### ISSUE THREAD

**Issue by Kilims** [ant-design/ant-design-mobile#3710]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://106.55.10.117/tlink_loan/RegistPage](http://106.55.10.117/tlink_loan/RegistPage)

### Steps to reproduce
在create-react-app脚手架，成功引入antd和antd-mobile后，将两者都换成CDN形式引入，模仿"通过CDN引入antd"的步骤来引入antd-mobile：
1. 在index.html引入CDN链接：

```index.html
<script crossorigin src="https://cdn.bootcdn.net/ajax/libs/antd/4.3.5/antd.min.js"></script>
<script crossorigin src="https://cdn.bootcdn.net/ajax/libs/antd-mobile/2.3.3/antd-mobile.min.js"></script>
```
2. 在cra 的 config-overrides 中，external antd-mobile
```
config.plugins.push(new HtmlWebpackExternalsPlugin({
    externals: [
        {
            module: "antd",
            entry: "https://cdn.bootcdn.net/ajax/libs/antd/4.3.5/antd.min.js",
            global: "antd"
        }, {
            module: "antd-mobile",
            entry: "https://cdn.bootcdn.net/ajax/libs/antd-mobile/2.3.3/antd-mobile.min.js",
            global: "antd-mobile"
        },
    ]
})
...
module.exports = override(
....
addWebpackExternals({
    "antd": "antd",
    "antd-mobile": "antd-mobile"
})
...
```
3. 注释掉babel import
```
module.exports = override(
    //   fixBabelImports("antd", {
//     libraryName: "antd",
//     libraryDirectory: "es",
//     style: true,
//   }),
//   fixBabelImports("antd-mobile", {
//     libraryName: "antd-mobile",
//     libraryDirectory: "es",
//     style: true,
//   }),
)
```

### What is expected?
antd和antd-mobile都能正常引入，无报错且页面正常

### What is actually happening?
antd通过上述方法能正常引入且无报错
antd-mobile报错 `Uncaught ReferenceError: mobile is not defined`

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.13.1 |
| System | MAC OS Catalina |
| Browser | Chrome |

---
antd成功引入，在控制台能console出`window.antd`，无报错，然而antd-mobile换成CDN的话，`console.log(window.antd-mobile)`会出现`Uncaught ReferenceError: mobile is not defined`错误，经查看window对象，是已经定义了antd-mobile的全局变量的，通过`window["antd-mobile"]`是可以看到对应的方法，但是`window.antd-mobile`不行，貌似默认是`window.antd-mobile`？怎么解决呢？
上面的网址，是已经在index.html引入了antd-mobile，但是webpack打包没有exclude的例子，所以页面能正常显示哈。进去后进入控制台，打印出window对象的话，是可以看到window里有antd-mobile对象的。但是如果我webpack打包exclude了antd-mobile，就会报跟`window.antd-mobile`一样的`Uncaught ReferenceError: mobile is not defined `错误

![image](https://user-images.githubusercontent.com/22916814/93153690-6b5f7700-f734-11ea-8c81-7366edc4a3d0.png)

![image](https://user-images.githubusercontent.com/22916814/93153847-baa5a780-f734-11ea-84c1-06a9e61b05d6.png)

应该是语法的问题，js里如果window.antd-mobile的话，-后的字符会undefined，但是antd-mobile cdn引入后默认是antd-mobile这个对象，需要通过window["antd-mobile"]才能调用到这个对象，这怎么解决呢？

**Comment by CHU295** [comment]
坑爹项目没人维护了；
我是这样解决的
在html下面重新定义全局变量`window.AntdMobile = window['antd-mobile']`
然后吧externals 改成"antd-mobile" ： "AntdMobile"

**Comment by awmleer** [comment]
v5 支持 umd 引入，是 `window.antdMobile`，可以参考这个 codepen：
https://codepen.io/awmleer/pen/zYwpMMd

**Comment by Pateo-fanyang** [comment]
> v5 支持 umd 引入，是 `window.antdMobile`，可以参考这个 codepen： https://codepen.io/awmleer/pen/zYwpMMd

进去看了, 有报错: Uncaught ReferenceError: antdMobile is not defined
