### ISSUE TITLE
在同时显示两个及以上的modal时，后面的modal均没有遮罩层，此bug只在ios上出现。

### ISSUE THREAD

**Issue by gq123** [ant-design/ant-design-mobile#3711]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
https://codepen.io/paranoidjk/pen/LWpaKe

### What is expected?
每个modal的遮罩层正常显示

### What is actually happening?
在同时显示两个及以上的modal时，后面的modal均没有遮罩层，此bug只在ios上出现。

| Environment | Info |
|---|---|
| antd-mobile | 2.3.1 |
| React | 16.9.11 |
| System | iphone11 |
| Browser | safari |

**Comment by staiv1** [comment]
ios上 z-index属性与transform： translateZ 冲突。 ant 在 
.am-modal-wrap 使用了  transform： translateZ(1px) 在.am-modal-mask没有使用导致。目前解决办法 添加css .am-modal-mask,
.am-modal-wrap {
  transform: translateZ(1px);
}

**Comment by awmleer** [comment]
建议升级到 v5：
https://next.mobile.ant.design/components/dialog
