### ISSUE TITLE
Picker 不支持设置 defaultValue

### ISSUE THREAD

**Issue by zwj7181** [ant-design/ant-design-mobile#3715]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
类似地址选择，默认滚动到预期的省份

### What does the proposed API look like?
Picker 支持设置 defaultValue（rmc-picker实际上是支持defaultVAlue的）

**Comment by awmleer** [comment]
v5 支持了：
http://next.mobile.ant.design
