### ISSUE TITLE
Taro 里面引入后 使用组件一直报错

### ISSUE THREAD

**Issue by z782223468** [ant-design/ant-design-mobile#3728]
![47921604280723_ pic](https://user-images.githubusercontent.com/14816434/97823920-6e6af280-1cf5-11eb-95ca-022e8a702b39.jpg)

**Comment by doxiaodong** [comment]
不确定支不支持 Taro

**Comment by pokect** [comment]
taro项目里边使用配套的taroui呀

**Comment by z782223468** [comment]
> taro项目里边使用配套的taroui呀

taroui的时间picker只能选日期或者时间 不能一次性选取年月日时分秒 看到这个可以就想引用了试下的 结果也不行

**Comment by kokiy** [comment]
@doxiaodong  next doc 站点打不开了
![image](https://user-images.githubusercontent.com/15773714/99143859-e93ff000-269b-11eb-835b-687bea778c67.png)

**Comment by awmleer** [comment]
目前不支持小程序，未来目前也没有支持的计划

**Comment by tanwei0425** [comment]
> taro项目里边使用配套的taroui呀

taro ui. 都半年没维护了
