### ISSUE TITLE
Calendar - Friday "Fir" is misspelled, it should be "Fri"

### ISSUE THREAD

**Issue by carlosalvarez91** [ant-design/ant-design-mobile#3740]
![image](https://user-images.githubusercontent.com/17145410/100143048-a5fc3300-2e8c-11eb-8572-aebe1f9e8181.png)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
