### ISSUE TITLE
官方还有计划来维护RN版本的组件库么

### ISSUE THREAD

**Issue by Jiyr0119** [ant-design/ant-design-mobile#3741]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
个人维护的版本一年多没更新了

### What does the proposed API look like?
阿里团队合作肯定比个人维护要稳定

**Comment by xiaohuoni** [comment]
现在交给bang88维护了，感觉还行。最近也更新了吧？
