### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCPicker" was not found in the UIManager

### ISSUE THREAD

**Issue by terrencebob** [ant-design/ant-design-mobile#3743]
"@ant-design/react-native": "^4.0.6",
"react-native": "0.63.3",

**Comment by believeyourself** [comment]
try @ant-design/react-native@3.2.0

**Comment by prasad456** [comment]
Having same issue, how to fix this
` "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "moment": "^2.29.1",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-check-box": "^2.1.7",
    "react-native-datepicker": "^1.7.2",
    "react-native-dropdown-picker": "^3.7.1",
    "react-native-form-select-picker": "^0.0.10",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.15.0",
    "react-native-simple-radio-button": "^2.7.4"`
