### ISSUE TITLE
Calender日历组件

### ISSUE THREAD

**Issue by LiShaoLong123** [ant-design/ant-design-mobile#3745]
Calender日历组件怎么设置在回显时只显示年月日，不要时间

**Comment by yangfuxiong** [comment]
日历组件设置pickTime属性，用的是12小时格式会有bug就是11点，12点，切换到下午到时候小时那一列不可以滚动

**Comment by NOLDOR-orc** [comment]
Calendar 日历 组件，如果区间选用同一天，第二次打开日期不会回填的问题?

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
