### ISSUE TITLE
[Bug] InputItem有输入内容时，点击右侧清除x，则输入内容固化为placeholder

### ISSUE THREAD

**Issue by zhaoyao91** [ant-design/ant-design-mobile#375]
[Bug] InputItem有输入内容时，点击右侧清除x，则输入内容固化为placeholder

![image](https://cloud.githubusercontent.com/assets/3808838/19339628/202e35f6-9157-11e6-9b8c-53c2a6e70462.png)
![image](https://cloud.githubusercontent.com/assets/3808838/19339635/2958f724-9157-11e6-83b3-aefb8b0a2fef.png)
![image](https://cloud.githubusercontent.com/assets/3808838/19339637/2e4c40ce-9157-11e6-8c7a-a27e7063f00a.png)

**Comment by pingan1927** [comment]
这个是交互上有意为之的，既然你提出来了，后续我们会再考虑要不要再改回去。

**Comment by LayGit** [comment]
增加一个配置项来设置是否更合适，每个人需求不一样

**Comment by pingan1927** [comment]
回头加上

**Comment by hotoo** [comment]
囧rZ  这是什么样的需求，谁会需要这样的交互

**Comment by hotoo** [comment]
谁能举个例子，什么时候需要这种交互的场景

**Comment by afc163** [comment]
这种配置项反人类的，不要加。最多加个 onClear 属性，让用户在业务代码中自己控制。

**Comment by pingan1927** [comment]
@afc163 我也觉得很反人类啊，已经默认关闭掉

**Comment by afc163** [comment]
移除掉，这个肯定是交流上误解了，不可能有这种需求，你可以让提需求的人来找我。
