### ISSUE TITLE
Calendar 日历插件在移动端使用时  滑动情况下持续触发错误提示

### ISSUE THREAD

**Issue by MrZhaoGit** [ant-design/ant-design-mobile#3752]
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.

**Comment by MrZhaoGit** [comment]
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.
新版本谷歌浏览器对触摸事件的机制有不同解释  求大佬解决

**Comment by Zejia** [comment]
* {
	touch-action: pan-y;
}
can fix it

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
