### ISSUE TITLE
antd-mobile的里Calendar组件在Tabs切换时出现问题不显示的问题

### ISSUE THREAD

**Issue by LiShaoLong123** [ant-design/ant-design-mobile#3753]
antd-mobile的里Calendar组件在Tabs切换时出现问题不显示的问题？
在我使用Tab切换时，有三个tab标签页，在第一个tab使用Calendar组件时，弹出来正常，到切换到第二个tab标签页时，在点击日期选择，弹出里的日历选择窗却出现在第一个tab标签页里。

**Comment by liang511** [comment]
我也遇到了这个问题，在第二个tab标签里显示Calendar，却出现在了第一个tab里，请问解决了吗

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
