### ISSUE TITLE
form表单添加新属性问题

### ISSUE THREAD

**Issue by lingqiongfang** [ant-design/ant-design-mobile#3754]
form表单，通过form.setFieldsValue({key:''}) 新增一个属性值，但是form 表单对应的values  ，没有新增的属性，只能通过form.getFieldValue('key'), 单独获取。如果直接提交form表单值，是没有新加的属性。有什么方法设置，且直接提交的form的时候有新增的属性吗？

**Comment by tedonggo** [comment]
同问？我用的最笨的方法就是 再复制一个 a-form-item 设置成 v-show="false" 就可以了，里面塞上你新增的属性就可以嗨皮setFieldsValue了🥱
`<a-form-item v-show="false"></a-form-item>`

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
