### ISSUE TITLE
date-picker 组件formatMonth 没有暴露出该方法

### ISSUE THREAD

**Issue by Hxiaotong** [ant-design/ant-design-mobile#3757]
源码中有格式化日期的方法，但是创建组件的时候却没有暴露出该属性，能不能帮忙加一下😝
value: function getDateData() {
            var _props = this.props,
                locale = _props.locale,
                formatMonth = _props.formatMonth,
                formatDay = _props.formatDay,
                mode = _props.mode;

var datePicker = React.createElement(RCDatePicker, { minuteStep: props.minuteStep, locale: DatePickerLocale, minDate: props.minDate, maxDate: props.maxDate, mode: props.mode, pickerPrefixCls: props.pickerPrefixCls, prefixCls: props.prefixCls, defaultDate: value || new Date(), use12Hours: props.use12Hours, onValueChange: props.onValueChange, onScrollChange: this.setScrollValue });

**Comment by awmleer** [comment]
v5 已经支持了，可以考虑升级一下
