### ISSUE TITLE
PullToRefresh  下拉刷新  垂直下拉没有问题  斜着拉拉不动

### ISSUE THREAD

**Issue by Mariah-feifei** [ant-design/ant-design-mobile#3759]
![1609136340(1)](https://user-images.githubusercontent.com/30531971/103193527-b08c6b00-4917-11eb-8fe4-38e161282ab7.jpg)
![1609135997(1)](https://user-images.githubusercontent.com/30531971/103193552-bd10c380-4917-11eb-88cd-a45ae32ae9c9.jpg)

**Comment by Mariah-feifei** [comment]
![image](https://user-images.githubusercontent.com/30531971/103193409-5be8f000-4917-11eb-8cd8-55cdc6997e8a.png)

![image](https://user-images.githubusercontent.com/30531971/103193416-60150d80-4917-11eb-8a6e-21ec440ea7f8.png)

**Comment by awmleer** [comment]
建议升级到 v5 的 PullToRefresh 组件：
https://next.mobile.ant.design/components/pull-to-refresh
