### ISSUE TITLE
请问用typescript使用ant-design-mobile的时候d.ts文件去哪里获得？

### ISSUE THREAD

**Issue by tungh** [ant-design/ant-design-mobile#376]
请问用typescript使用ant-design-mobile的时候d.ts文件去哪里获得？搜了github、npmjs都没有

**Comment by xjl271314** [comment]
好像是的 暂时没找到解决这个问题 不过ts可以使用谷歌的Material Design

**Comment by yiminghe** [comment]
npm i antd-mobile

check node_modules/antd-mobile/lib/xx/xx.d.ts
