### ISSUE TITLE
modal.alert在ios11.2系统下 弹窗内容无法下滑

### ISSUE THREAD

**Issue by Horace1997** [ant-design/ant-design-mobile#3760]
在alert的第二个参数中使用reactDom，无法使用overflow:scroll的划动

**Comment by Horace1997** [comment]
在alert的第二个参数中使用reactDom，无法使用overflow:scroll的划动

**Comment by awmleer** [comment]
建议升级到 v5 的 Dialog 组件：
https://next.mobile.ant.design/components/dialog#dialogalert
