### ISSUE TITLE
carousel  dragging、swiping属性报ts错误

### ISSUE THREAD

**Issue by libertassss** [ant-design/ant-design-mobile#3761]
Type '{ children: Element[]; vertical: true; dots: false; dragging: boolean; swiping: boolean; autoplay: true; infinite: true; autoplayInterval: number; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Carousel> & Pick<Readonly<CarouselProps> & Readonly<...>, "style" | ... 11 more ... | "initialSlideWidth"> & Partial<...> & Partial<...>'.
  Property 'dragging' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttribut

**Comment by yaogengzhu** [comment]
我也遇到了同样的问题， 应该是这个属性还没有被发布到正式版本上！

**Comment by awmleer** [comment]
建议升级到 v5 的 Swiper 组件：
https://next.mobile.ant.design/components/swiper
