### ISSUE TITLE
 ant-design   有 AutoComplete 自动完成， 而 ant-design-mobile 没有这个功能， 希望也能增加上

### ISSUE THREAD

**Issue by manxihuanchi** [ant-design/ant-design-mobile#3763]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. 需要一个输入框而不是选择器， 需要输入建议/辅助提示。
2. 和 Select 的区别是：
AutoComplete 是一个带提示的文本输入框，用户可以自由输入，关键词是辅助输入。
Select 是在限定的可选项中进行选择，关键词是选择。

Autocomplete function of input field.
When there is a need for autocomplete functionality.

### What does the proposed API look like?
Ant Design PC端有这个功能， 而 ant-design-mobile 没有这个功能， 希望手机端也能加上这个功能

**Comment by awmleer** [comment]
这种场景更适合弹出一个新的页面，或者是在搜索框下面增加一些 Tag，后面我们做 pro 的时候可以考虑加个 demo

cc @crazylxr

**Comment by zhangle1** [comment]
有了吗
