### ISSUE TITLE
Popover点击mask，会点击到下层元素

### ISSUE THREAD

**Issue by tenghuan123** [ant-design/ant-design-mobile#3764]
官方案例上都可发现这个问题，popover上，点击下面的主菜单的按钮，我们可以直接点击去，但是这是popover啊，我点击的是mask层只是想关掉popover而已，为什么你就像事件穿透的一样，直接到下一层了呢？我后面再自己代码上调试的时候发现，那个popover层根本就不在顶层，所以不管我们怎么阻塞冒泡都没办法解决穿透，（或者说它本来就不是穿透问题），希望官方能注意到这个bug吧

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by andy7076** [comment]
这个问题在5.x也存在
