### ISSUE TITLE
Input、textarea等组件在iOS的wkwebview中，事件响应问题

### ISSUE THREAD

**Issue by liuxiaoer** [ant-design/ant-design-mobile#3768]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/textarea-item](https://mobile.ant.design/kitchen-sink/components/textarea-item)

### Steps to reproduce
打开链接后，快速点击可输入的元素

### What is expected?
在快速点击的情况下，也可以获取元素焦点

### What is actually happening?
在快速点击的情况下，无法获取焦点

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.9.0 |
| System | iOS wkwebview |
| Browser | wkwebview release |

---
只有wkWebview中存在这个问题

**Comment by lliuYuuan** [comment]
#3248
