### ISSUE TITLE
NavBar and Drawler doesn't work in it is together

### ISSUE THREAD

**Issue by sarankup** [ant-design/ant-design-mobile#3769]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile](https://github.com/ant-design/ant-design-mobile)

### Steps to reproduce
Even the below example doesn't work
https://mobile.ant.design/components/drawer/

```this.onOpenChange() function is not working even if I have the below
onOpenChange = () => {
    console.log(11);
  }
```

If I remove the drawer then the same click works better.

### What is expected?
onLeftClick={() => console.log('onLeftClick')} yet to work

### What is actually happening?
function is not getting executed

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17.0.1 |
| System | Macintosh |
| Browser | Chrome |

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
