### ISSUE TITLE
TextareaItem 设置 autoFocus 无效

### ISSUE THREAD

**Issue by meikidd** [ant-design/ant-design-mobile#377]
antd-mobile 0.9.2

TextareaItem 设置 autoFocus 无效

**Comment by pingan1927** [comment]
H5通过脚本设置autoFocus一般都无效的吧

**Comment by meikidd** [comment]
那通过脚本让TextareaItem获得焦点，要怎么做，如果是原生textarea可以这样，
```
this.refs.textarea.getDOMNode().focus(); 
```
在antd-mobile中应该怎么做呢

**Comment by warmhug** [comment]
`setState({}, () => this.refs.textarea.getDOMNode().focus())`

**Comment by pingan1927** [comment]
我试试看。

**Comment by warmhug** [comment]
`0.9.6` 已修复
