### ISSUE TITLE
calendar 如何拿到当前加载年月

### ISSUE THREAD

**Issue by zhibo59** [ant-design/ant-design-mobile#3771]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我需要一个change方法来让我知道何时做了下拉加载上一月的操作

### What does the proposed API look like?
change 时间来告诉我用户下拉加载上一个月了

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
