### ISSUE TITLE
search bar怎么正定义搜索框下方的提示文字

### ISSUE THREAD

**Issue by gugu-lee** [ant-design/ant-design-mobile#3772]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在api中没有找到怎么定义搜索框下方的提示文字的属性。

### What does the proposed API look like?
无

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
