### ISSUE TITLE
accessbility-support

### ISSUE THREAD

**Issue by ManDevon** [ant-design/ant-design-mobile#3774]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对眼神不好的人的辅助

### What does the proposed API look like?
picker针对盲人辅助（accessbility）有很好的支持体验

**Comment by awmleer** [comment]
Duplicated #3775
