### ISSUE TITLE
accessbility-support

### ISSUE THREAD

**Issue by ManDevon** [ant-design/ant-design-mobile#3775]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples](https://github.com/ant-design/antd-mobile-samples)

### Steps to reproduce
毕现
本地链接都可以测试   picker组件不支持accessibility 

### What is expected?
日期picker 跟viewpicker对盲人辅助的支持

### What is actually happening?
日期picker 跟viewpicker对盲人辅助不支持

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.13.1 |
| System | android & IOS  |
| Browser | 微信浏览器 |

**Comment by awmleer** [comment]
v2 已经停止维护了，accessibility 的支持我们没有办法增加了，v5 在考虑支持，但是因为我们的精力有限，很难在短时间内实现全部组件很完善的无障碍支持
