### ISSUE TITLE
accessbility-support for date picker and viewpicker

### ISSUE THREAD

**Issue by ManDevon** [ant-design/ant-design-mobile#3777]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples](https://github.com/ant-design/antd-mobile-samples)

### Steps to reproduce
sames components can not support accessibility,  do you have some plan to support it ?

### What is expected?
I wish the components can support accessibility as soon as possible

### What is actually happening?
Now all the components can not support the accessibility

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.13.1 |
| System | android & IOS  |
| Browser | wechat webview |

**Comment by awmleer** [comment]
Duplicated #3775
