### ISSUE TITLE
Tabs标题设计成不等宽

### ISSUE THREAD

**Issue by Panfen** [ant-design/ant-design-mobile#3778]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果Tabs很多，且存在某个标题过长，显示效果很差，只能减少page的值，希望Tab标题设为不等宽

### What does the proposed API look like?
无

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
