### ISSUE TITLE
SwipeAction左滑之后的删除按钮在部分手机上需要点击两次才能触发点击事件

### ISSUE THREAD

**Issue by daimayaojing** [ant-design/ant-design-mobile#3779]
使用SwipeAction后,左滑之后的删除按钮部分手机需要点击两次才有效果，具体手机型号有：荣耀V20，华为p40,华为nova7-pro,应该还有部分安卓手机都有这个问题

**Comment by CassielLee** [comment]
我用的时间选择组件也有这个问题，首次切换时间要点击两次才生效

**Comment by Haoxuan8** [comment]
同样问题，添加 fastclick 后可以暂时解决问题，不知道具体原因

**Comment by awmleer** [comment]
建议升级到 v5 的 SwipeAction 组件：
https://next.mobile.ant.design/components/swipe-action
