### ISSUE TITLE
建议增加web版ScrollView滚动视图组件

### ISSUE THREAD

**Issue by haomiaozhichen** [ant-design/ant-design-mobile#378]

**Comment by warmhug** [comment]
web版任何元素都是 ScrollView、为什么还要增加？不过是 API 跟 rn 的不一样。

**Comment by haomiaozhichen** [comment]
就是想增加web版ScrollView，且和rn统一

**Comment by warmhug** [comment]
统一起来成本收益比不大，目前先不考虑。

**Comment by billgo** [comment]
如果真的想把web做成app, 这个scrollview是挺有必要的，我自己实现了一个，但是性能一直不是很好，希望有大神造这个轮子。
