### ISSUE TITLE
Calendar组件展示年月日问题

### ISSUE THREAD

**Issue by ouyang1016** [ant-design/ant-design-mobile#3780]
![image](https://user-images.githubusercontent.com/43235284/105680413-a9fb0e80-5f2a-11eb-9ed5-46598bc2b603.png)

**Comment by ouyang1016** [comment]
<Calendar
        pickTime
        visible={calendShow}
        onCancel={onCancel}
        onConfirm={onConfirm}
        minDate={new Date('2018-01-01')}
        maxDate={new Date(+now + 31536000000)}
      />

**Comment by ouyang1016** [comment]
`<Calendar
        pickTime
        visible={calendShow}
        onCancel={onCancel}
        onConfirm={onConfirm}
        minDate={new Date('2018-01-01')}
        maxDate={new Date(+now + 31536000000)}
      />`

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
