### ISSUE TITLE
InputItem uses require cause 'require is not defined' error(build with vite)

### ISSUE THREAD

**Issue by rainmanhhh** [ant-design/ant-design-mobile#3784]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/rainmanhhh/vite-antd-mobile-demo](https://github.com/rainmanhhh/vite-antd-mobile-demo)

### Steps to reproduce
npm run build && npm run serve

### What is expected?
page displaying without error

### What is actually happening?
'require is not defined'

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.14.0 |
| System | win10 |
| Browser | edge 87 |

---
InputItem uses require(which is not supported by browser) in `https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.tsx`:
```
 // tslint:disable-next-line:variable-name
    const _locale = getComponentLocale(
      this.props,
      this.context,
      'InputItem',
      () => require('./locale/zh_CN'),
    );
```
btw, there's no similar problem in antd

**Comment by hsian** [comment]
And one! +1

**Comment by hsian** [comment]
It works for me, [https://vitejs.dev/config/#build-commonjsoptions](https://vitejs.dev/config/#build-commonjsoptions)

code:

`build: {
  commonjsOptions: {
    transformMixedEsModules: true
  }
}`

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
