### ISSUE TITLE
ImagePicker 建议返回File对象

### ISSUE THREAD

**Issue by huliyou** [ant-design/ant-design-mobile#379]
目前ImagePicker 返回的上传的图片是DataURL，能增加返回File Object吗

**Comment by huliyou** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/components/image-picker/index.web.tsx#L81-L109

建议返回上传的文件 file object

**Comment by zhuyunxiang** [comment]
请问做RN图片上传时仅根据获得的上传的图片的本地URL如何进行上传？

**Comment by silentcloud** [comment]
@zhuyunxiang 这个需要写 native 模块，github 有很多，搜哈 `react native upload`
