### ISSUE TITLE
为什么在Input框内点击 clear（叉×）会调用onBlur方法呢？

### ISSUE THREAD

**Issue by ahshy1996** [ant-design/ant-design-mobile#3797]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现有状态下，点击叉 会调用onBlur方法，如果在onBlur内有alert方法，点击弹框确定后，会再次调用onBlur方法

### What does the proposed API look like?
和 type="money"里的逻辑相同，点击clear/叉 不会调用onBlur方法

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
