### ISSUE TITLE
Vertical carousel can't autoplay when fetch the dynamic data.

### ISSUE THREAD

**Issue by renrenguiwei** [ant-design/ant-design-mobile#3799]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/carousel/#components-carousel-demo-basic](https://mobile.ant.design/components/carousel/#components-carousel-demo-basic)

### Steps to reproduce
nothing

### What is expected?
when use the useState or Mobx to change the state, I hope the carousel autoplay again

### What is actually happening?
Data map: 
1. 0 -> 1, can't autoplay, It's normal
2. 1 -> 2, can't autoplay, It's weird
3. 2 -> 1, autoplay, It's weird; when the data's length is 1, the autoplay should stop, because play one block is userless

| Environment | Info |
|---|---|
| antd | 3.26.1 |
| React | 16.12.0 |
| System | macbook pro 16 |
| Browser | chrome |

**Comment by renrenguiwei** [comment]
Solved this problem. 
1. Find the map point '2'，It's very important. No matter is the '0 -> 2' or '3 -> 2', It's all about 'x -> 2'
2. So when the map's length is 2, re-render the 'carousel'
```
if (data.length === 2) {
   setDataView([])
   setTimeout(() => {
      setDataView(data)
   }, 0)
}
```

Side-Effect:
1. Only the length is 2, that block will blink

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
