### ISSUE TITLE
建议增加web版Navigator导航器组件

### ISSUE THREAD

**Issue by haomiaozhichen** [ant-design/ant-design-mobile#380]

**Comment by warmhug** [comment]
NavBar + https://github.com/ReactTraining/react-router  怎么样？

**Comment by haomiaozhichen** [comment]
react-router 在很多低端安卓机上都不能用，兼容性不好，所以建议增加web版Navigator导航器组件

**Comment by benjycui** [comment]
`antd-mobile` 本身也不支持低版本的 Android https://github.com/ant-design/ant-design-mobile#browser-support

**Comment by haomiaozhichen** [comment]
@benjycui 在很多Android 4.0+设备上，antd-mobile都能用，但是react-router不能用，所以需要web版Navigator导航器组件

**Comment by warmhug** [comment]
react-router 会变得更好，安卓机也会变得更好，这里暂不提供Navigator组件
