### ISSUE TITLE
控件底边线粗细不一致问题（component bottom line width not same）

### ISSUE THREAD

**Issue by yatsov** [ant-design/ant-design-mobile#3800]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/kitchen-sink/components/input-item?lang=en-US#input-item-demo-0](https://mobile.ant.design/kitchen-sink/components/input-item?lang=en-US#input-item-demo-0)

### Steps to reproduce
https://mobile.ant.design/kitchen-sink/components/input-item?lang=en-US#input-item-demo-0
使用 小米或者一加 8t 安卓 11 自带浏览器打开链接 
https://codesandbox.io/s/antd-reproduction-template-forked-t605h
看sanbox 里面的那张图

### What is expected?
控件底边线一致

### What is actually happening?
部分底边线粗细不一致且没有规律。
麻烦指点一下 问题在哪里 本人移动端经验少一些，指点了之后我去尝试着适配一下 感谢

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | ^16.13.1 |
| System | Android |
| Browser | 手机自带浏览器（Mobile phone's basic browser） |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
