### ISSUE TITLE
[BUG}PullToRefresh在小米手机上上拉失效

### ISSUE THREAD

**Issue by firstmetcs** [ant-design/ant-design-mobile#3803]
小米自带浏览器，下拉可以生效，上滑不能使用

代码如下：

`<PullToRefresh
            damping={60}
            style={{
              height: 400,
              overflow: 'auto',
            }}
            indicator={{ deactivate: '上拉可以刷新' }}
            direction={'up'}
            onRefresh={() => {
              console.log("========================================");
            }}
          >
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
            <div>test</div>
          </PullToRefresh>`

**Comment by awmleer** [comment]
建议升级到 v5 的 PullToRefresh 组件哈：
https://next.mobile.ant.design/components/pull-to-refresh
