### ISSUE TITLE
[BUG}PullToRefresh在小米手机上上拉加载失效

### ISSUE THREAD

**Issue by firstmetcs** [ant-design/ant-design-mobile#3804]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/firstmetcs/pen/VwPPObK](https://codepen.io/firstmetcs/pen/VwPPObK)

### Steps to reproduce
小米自带浏览器打开，无法上拉，只能下滑

### What is expected?
希望支持下滑的相应

### What is actually happening?
直接无法响应下滑操作

| Environment | Info |
|---|---|
| antd-mobile | ^2.3.4 |
| React | ^16.8.6 |
| System | 小米 |
| Browser | 自带浏览器 |

**Comment by awmleer** [comment]
建议升级到 v5 的 PullToRefresh 组件哈：
https://next.mobile.ant.design/components/pull-to-refresh
