### ISSUE TITLE
ListView 控制所有行内容对显示、隐藏 ,只对最新一页对记录有效

### ISSUE THREAD

**Issue by hulk-yin** [ant-design/ant-design-mobile#3805]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/hulk-yin/pen/JjEyRbN](https://codepen.io/hulk-yin/pen/JjEyRbN)

### Steps to reproduce
滑动页面,加载第2页, 点击 showmore 按钮

### What is expected?
所有记录行 全面展开详细信息

### What is actually happening?
只有最新一页数据展开详细信息

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | macos |
| Browser | chrome |

---
通过按钮控制 记录行选择按钮,只能时效最后一页状态对控制

**Comment by awmleer** [comment]
建议升级到 v5：
https://next.mobile.ant.design/components/infinite-scroll
