### ISSUE TITLE
SwipeAction在安卓上无效

### ISSUE THREAD

**Issue by xjl271314** [ant-design/ant-design-mobile#381]
#### 本地环境

- antd-mobile 版本：0.9.0
- 操作系统及其版本：Android 版本5.0
- 浏览器及其版本：微信内置浏览器
#### 你做了什么？

引入 antd-mobile 的 SwipeAction
#### 你期待的结果是：

 像官网一样正常显示 
#### 实际上的结果：

在苹果手机上左滑右滑 长按有效 在安卓手机上无效
#### 可重现的在线演示

请修改并 Fork https://mobile.ant.design/components/swipe-action/

**Comment by xjl271314** [comment]
请官方测试检查在安卓上的结果

**Comment by silentcloud** [comment]
@xjl271314 Android 上长按是否有效？

**Comment by xjl271314** [comment]
长按有效 滑动无效

**Comment by silentcloud** [comment]
@xjl271314 android 是和自身平台匹配，所以只会长按，下一个大版本会改成统一的滑动

**Comment by zaxlct** [comment]
+1
同发现不能滑动，只能长按

**Comment by silentcloud** [comment]
1.0 保持 android 和 iOS 操作效果一致，android 后期会进行 UI 设计和 gmail 类似
