### ISSUE TITLE
文档的跳转url不存在

### ISSUE THREAD

**Issue by mfoonirlee** [ant-design/ant-design-mobile#3810]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/list-view-cn/#components-list-view-demo-basic-body](https://mobile.ant.design/components/list-view-cn/#components-list-view-demo-basic-body)

### Steps to reproduce
https://mobile.ant.design/components/list-view-cn/#components-list-view-demo-basic-body链接中 api里的 ListView.DataSource 实例跳转url显示404

### What is expected?
正常打开页面

### What is actually happening?
404

| Environment | Info |
|---|---|
| antd | undefined |
| React | 任意 |
| System | 任意 |
| Browser | 任意 |

**Comment by awmleer** [comment]
v2 版本站点归档：https://antd-mobile-v2.surge.sh/
