### ISSUE TITLE
强烈建议 ant-design-mobile 增加对“可滑动的表格”的支持

### ISSUE THREAD

**Issue by ximenchuixue** [ant-design/ant-design-mobile#3811]
强烈建议 ant-design-mobile 增加对“可滑动的表格”的支持，移动端目前很多应用有这个需求点。
该组件大致操作方式是：手指按住表格，水平滑动时第一列固定、垂直滑动时第一行固定。
以下是一个demo（chrome控制台切换到移动端模式运行）以及运行的效果图：
[table_mobile.zip](https://github.com/ant-design/ant-design-mobile/files/6322810/table_mobile.zip)

![image](https://user-images.githubusercontent.com/1296597/114977667-9f616d00-9eba-11eb-9a38-00947ab3be39.png)
![image](https://user-images.githubusercontent.com/1296597/114977697-adaf8900-9eba-11eb-92e3-c9cc5588c9dc.png)

**Comment by awmleer** [comment]
统一汇总到了 #4016 中，这个 issue 先 close 了哈
