### ISSUE TITLE
antd-mobile 'indexof' package cause build error with vite build

### ISSUE THREAD

**Issue by lichenbuliren** [ant-design/ant-design-mobile#3813]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/lichenbuliren/vite-test-demo](https://github.com/lichenbuliren/vite-test-demo)

### Steps to reproduce
1. download the repo [vite-test-demo](https://github.com/lichenbuliren/vite-test-demo)
2. npm run build:qa
3. cd dist & http-server .

### What is expected?
the dist dir can normal run

### What is actually happening?
it console error:

```
# build error
transforming (115) node_modules/core-js/library/modules/_to-primitive.jsndexof' is imported by indexof?commonjs-external, but could not be resolved – treating it as an external dependency

// chrome console error
Uncaught TypeError: Failed to resolve module specifier "indexof". Relative references must start with either "/", "./", or "../".
```

| Environment | Info |
|---|---|
| antd | 2.3.4 |
| React | 17.0.0 |
| System | macOS Big Sur |
| Browser | chrome |

---
cause this issue is that 
- antd-mobile deps commonjs package "indexof";
- antd-mobile ：esm and commonjs require mixed using

**Comment by xiaosenzhang** [comment]
我也遇到了这种问题

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
