### ISSUE TITLE
麻烦ant-design-mobile重写吧

### ISSUE THREAD

**Issue by mtsee** [ant-design/ant-design-mobile#3818]
react连一个像样的移动端库都没有，ant-design-mobile这个库怎么说呢，问题特别多，感觉设计上也有很多缺陷，就拿Tabs来说吧，为什么不能借鉴antd那种方式，非要默认给预设的div加一个外壳作为TabPane，这样就导致很多方法没法预置到组件中，比如要加个className都很麻烦，另外如果tabs里面是动态的，比如
```javascript
<Tabs ...>
   {tab1 && <div>tab1</div>}
   {tab2 && <div>tab2</div>}
</Tabs>
```
就会有BUG，虽然用的是rmc-tabs，怎么说呢，选择好的轮子也非常关键的，
吐槽点还是比较多的，我只是举例一个，建议重新这个库，不要沦为KPI的产物，我们很愿意贡献自己的代码。

**Comment by xiaohaoo** [comment]
支持

**Comment by mtsee** [comment]
发现 Picker 在多级联动的时候，设置cols无效，啊~~~

**Comment by Lemonreds** [comment]
hhh，看了commit已经很久没有更新了

**Comment by firstmetcs** [comment]
+++++1，PullToRefresh兼容性好差……

**Comment by chentogit** [comment]
+1重写，跟antd差远了

**Comment by xueyou2000** [comment]
react移动端可以试试我的http://xueyou2000.gitee.io/weui-react-v2/

**Comment by brickspert** [comment]
我猜最新版本很快就来了

**Comment by awmleer** [comment]
#3924
