### ISSUE TITLE
Carousel一点击就会触发afterChange事件，搞不懂为什么这么设计？？

### ISSUE THREAD

**Issue by Issho-lin** [ant-design/ant-design-mobile#3819]
carousel组件内的元素绑定点击事件，点击会触发afterChange事件，甚至是最快被触发的，即使什么click事件也没有绑定，单纯地点击组件也会触发，搞不懂为什么这么设计

**Comment by awmleer** [comment]
建议升级到 v5 的 Swiper 组件吧……
https://mobile.ant.design/zh/components/swiper
