### ISSUE TITLE
Calendar time picker format

### ISSUE THREAD

**Issue by krustevgeorgi** [ant-design/ant-design-mobile#3821]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Inability to have a 24 h format time picker and also step between minutes to be 5. Currently I am using the Calendar component which prompts a default time picker, unfortunately I cannot change the hour format from 12 hour am/pm to 24h. I would also find it useful to change the minutes step. As an example we can refer to the DatePicker components props: 'use12Hours' and 'minuteStep'.

### What does the proposed API look like?
<Calendar use12Hours={false} minuteStep={5} />

**Comment by awmleer** [comment]
v2 is no longer maintained. Please consider upgrading to v5.
