### ISSUE TITLE
Tabs使用key关键字后，content无法渲染出，官方demo也是如此。

### ISSUE THREAD

**Issue by fackerZuo** [ant-design/ant-design-mobile#3822]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/tabs-cn/#components-tabs-demo-basic](https://mobile.ant.design/components/tabs-cn/#components-tabs-demo-basic)

### Steps to reproduce
点击到“固定高度”模块，里面tabs使用了key，但是content无法渲染。

### What is expected?
可以渲染出内容

### What is actually happening?
什么都没渲染

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.9.0 |
| System | mac |
| Browser | chrome |

**Comment by Hexi1997** [comment]
我也是这个问题，这个怎么解决呢，去掉key可以么

**Comment by lihqi** [comment]
加上key就好了[#3828](https://github.com/ant-design/ant-design-mobile/pull/3828)

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
