### ISSUE TITLE
ImagePicker上传照片预览报错

### ISSUE THREAD

**Issue by httol** [ant-design/ant-design-mobile#3824]
使用这个组件上传后，发现base64后面竟然少了逗号，造成url无法解析报错。请问怎么解决啊
![image](https://user-images.githubusercontent.com/4971746/119637051-d460c800-be47-11eb-9c5d-a6dd67f11770.png)

![image](https://user-images.githubusercontent.com/4971746/119635886-b181e400-be46-11eb-9a74-11392b0dc6c6.png)
![image](https://user-images.githubusercontent.com/4971746/119636967-bdba7100-be47-11eb-913d-21d5ffa9bdef.png)

**Comment by awmleer** [comment]
看起来是 v2 的组件？可以考虑升级一下
