### ISSUE TITLE
手风琴不能展开

### ISSUE THREAD

**Issue by nuonuonuonuoyan** [ant-design/ant-design-mobile#3826]
用了ant-mobile3.0，直接复制的官方的例子，结果手风琴完全无法展开

import * as React from 'react'
import {
    unstable_Collapse as Collapse,
    unstable_List as List,
} from '@ant-design/mobile'

export default () => (
    <div>
        <Collapse onChange={key => console.log('key', key)} defaultActiveKey="0">
            <Collapse.Panel header="Title 1">
                <List className="my-list">
                    <List.Item>content 1</List.Item>
                    <List.Item>content 2</List.Item>
                    <List.Item>content 3</List.Item>
                </List>
            </Collapse.Panel>
            <Collapse.Panel header="Title 2">
                this is panel content2 or other
            </Collapse.Panel>
            <Collapse.Panel header="Title 3">
                text text text text text text text text text text text text text text
                text
            </Collapse.Panel>
        </Collapse>
    </div>
)

这个真的是让人无语。。。。。
根据页面元素的定位来看，Collapse.Panel 这个标签里面添加的内容并没有在页面中展示出来，完全没有这些内容

**Comment by awmleer** [comment]
可以考虑升级到 v5 的 Collapse 组件：
https://next.mobile.ant.design/components/collapse
