### ISSUE TITLE
Search bar X button not calling onClear

### ISSUE THREAD

**Issue by Cactice** [ant-design/ant-design-mobile#3827]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/search-bar](https://mobile.ant.design/components/search-bar)

### Steps to reproduce
Click the x button in the searchbar.

### What is expected?
onClear and onBlur shows on console

### What is actually happening?
onClear does not show up, only onBlur

| Environment | Info |
|---|---|
| antd | 2.3.4 |
| React | 17.0.1 |
| System | macOS 10.15 |
| Browser | 90.04 |

**Comment by Y-MY** [comment]
me too,click clear ，click clear, the result triggers onblur.

**Comment by awmleer** [comment]
antd-mobile v5 is going to be released in the near future. Please consider upgrading to the new Search component:
https://next.mobile.ant.design/components/search
