### ISSUE TITLE
Carousel内容为embed，会导致手动左右滑动失效

### ISSUE THREAD

**Issue by DongxuYI** [ant-design/ant-design-mobile#3835]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
Carousel包含多个内容，其中一个为embed引入的html，其他为图片，此情况下embed内容无法手动滑动，其余正常

### What is expected?
包含embed的内容也可以正常滑动

### What is actually happening?
包含embed的内容不可以正常滑动

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | ^16.8.6 |
| System | macOS |
| Browser | chrome版本 91.0.4472.114（正式版本） (x86_64) |

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
