### ISSUE TITLE
app端 虚拟键盘 在 modal 中显示的兼容性问题

### ISSUE THREAD

**Issue by QMSFish** [ant-design/ant-design-mobile#3837]
1、使用 antd 组件库的 modal 标签和 inputItem 标签
2、在 modal 标签的内容中写入 inputItem 标签，inputItem 标签获得焦点
3、安卓中，获得焦点后，虚拟键盘会弹出，不会被 modal 遮挡
4、ios中，获得焦点后，虚拟键盘不显示，点击虚拟键盘本应该显示所在的地方，发现虚拟键盘还是可以触发，只是不显示

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
