### ISSUE TITLE
antd-mobile组件示例 - 代码演示框太小，查看代码不方便

### ISSUE THREAD

**Issue by Azir1** [ant-design/ant-design-mobile#3838]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
组件示例代码框太小，需上下滚动查看代码，不便于用户查看

### What does the proposed API look like?
无

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/127472079-69fcfe69-1bf6-442c-8361-0f761c5f5ef3.png)
点这里
