### ISSUE TITLE
关于最新版本 0.9.2 的组件 Carousel 的高度问题

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#384]
0.9+版本中，组件Carousel依旧有一个问题。**就是当路由切换后，Carousel 组件只显示dots，等待数秒后图片才会显示出来（这让人感觉很不爽！）当我把版本会退到0.8.2时候，就不会出现这种问题**。为了更好的说明问题，我做了gif。

0.9+ 版本下（这感觉让人难受）
![1](https://cloud.githubusercontent.com/assets/9410091/18790235/97339a6e-81e0-11e6-95a6-176bc0377d2a.gif)

---

0.8.2 版本下（这是我想要的感觉）
![2](https://cloud.githubusercontent.com/assets/9410091/18790179/643f0b70-81e0-11e6-94f3-830b3c754ef8.gif)

**Comment by LayGit** [comment]
+1

**Comment by minooo** [comment]
@foriacus 目前版本更新到0.9.6 ，此问题依然没有解决。

**Comment by minooo** [comment]
通过我自己加了点方法，解决了。

**Comment by wjljack** [comment]
@minooo 如何解决的？

**Comment by minooo** [comment]
@wjljack [一句话，说不清楚，你看代码吧，在Home.js中](https://github.com/minooo/React-Study/tree/1d08bee0a510bfc8e022f9a10cb49962e1edcaa8/step-03)
