### ISSUE TITLE
Tabs在微信浏览器样式错误，无法显示标签页内容、underLine的位置错误

### ISSUE THREAD

**Issue by rangyf** [ant-design/ant-design-mobile#3841]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://apk.hsm1997.com/test/test](https://apk.hsm1997.com/test/test)

### Steps to reproduce
在微信内置浏览器内打开

### What is expected?
在微信开发者工具、手机浏览器和手机微信内置浏览器中都可以正常显示

### What is actually happening?
在微信开发者工具和手机浏览器（Safari、Chrome）中都可以正常显示，但是在手机微信内置浏览器中无法显示标签页内容、tabBarUnderline的位置错误，如图：https://apk.hsm1997.com/a880d4fc1f1739a617cfe6ed1b26a4f.jpg

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 17 |
| System | 安卓10/iOS 13 |
| Browser | 微信内置浏览器（微信8.0.7） |

---
使用的umijs 3.4.13，umijs config中使用默认polyfill和target选项，导出静态页面。虽然主要问题应该是微信浏览器比较特殊，但其实我感觉是umijs的配置哪里不对，因为在手机微信浏览器访问https://mobile.ant.design/kitchen-sink/components/tabs 这里是没有问题的。

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
