### ISSUE TITLE
How to use image-viewer?

### ISSUE THREAD

**Issue by victorykong** [ant-design/ant-design-mobile#3849]
https://next.mobile.ant.design/components/image-viewer

**Comment by awmleer** [comment]
@victorykong 你具体是想问？

**Comment by victorykong** [comment]
哪个版本可以用到这个组件

**Comment by awmleer** [comment]
> 哪个版本可以用到这个组件

```
npm install --save antd-mobile@alpha
```

**Comment by victorykong** [comment]
好的，这个不是你们这边在维护吗？`  "@ant-design/mobile": "^3.0.0-alpha.8",`

**Comment by awmleer** [comment]
> 好的，这个不是你们这边在维护吗？` "@ant-design/mobile": "^3.0.0-alpha.8",`

3.0 alpha 已经不维护了，现在我们在做 5.0 alpha，具体的相关背景和未来规划我们后续会逐步发出来

**Comment by victorykong** [comment]
好的，这里有点混乱

**Comment by awmleer** [comment]
嗯嗯是有一点，5.0 alpha 暂时还只是我们内部在用，还不足够稳定和成熟，我们还在逐步完善中

**Comment by victorykong** [comment]
nextjs 引入会报错，应该是没兼容到 ssr 渲染
![image](https://user-images.githubusercontent.com/50655436/126932348-84e0c32c-d253-4c27-bc5b-805616d41b20.png)

**Comment by awmleer** [comment]
@victorykong SSR 还没验证过，很可能是不兼容的，后面我们会支持
