### ISSUE TITLE
Navbar 组件自定义的右侧图标添加点击事件没有执行

### ISSUE THREAD

**Issue by zjfjiayou** [ant-design/ant-design-mobile#385]
MacBook 10.11.6
谷歌浏览器版本 53.0.2785.143 (64-bit)
ant:1.0.0-alpha.5

Navbar 组件自定义的右侧图标添加点击事件没有执行

**Comment by afc163** [comment]
不要用 1.0.0-alpha.5 ，用 0.9.x 。
