### ISSUE TITLE
建议Selector增加radio用法

### ISSUE THREAD

**Issue by Coco-rq** [ant-design/ant-design-mobile#3857]
目前的selector点击是可以被取消的，建议增加类似radio不可取消的用法

**Comment by awmleer** [comment]
`onChange` 里加一下判断就可以了，Demo 我去补充下

```jsx
<Selector
  options={ItemList}
  value={value}
  onChange={(v) => {
    if (v.length === 0) return
    setValue(v)
  }}
/>
```

**Comment by awmleer** [comment]
Close via e015f4b7b

**Comment by YiField** [comment]
如果selector在form表单中这个不适用

**Comment by ch1ny** [comment]
> 如果selector在form表单中这个不适用

遇到了同样的原因，在 `Form.Item` 和 `Selector` 中间再包一层 `div` 就能正常使用了，目前还不清楚什么原因，待会儿看看代码
