### ISSUE TITLE
Popover 的系列样式问题

### ISSUE THREAD

**Issue by Coco-rq** [ant-design/ant-design-mobile#3858]
1.kitchen上的分割线是不到边的，且v5版本的图标变成了上下布局
![image](https://user-images.githubusercontent.com/37095432/127278582-d1581bae-0d86-482c-b1cd-40573e145bff.png)
2.在kitchen上引导提示和气泡菜单是两个组件，所以设计上圆角不一样，但由于我们用同一个组件，这个设计以哪个为准？
3.黑色模式的三角形和矩形之间位置发生了重叠，且内容过多的话，就会与触发元素距离过远

**Comment by awmleer** [comment]
最新版本已修复
