### ISSUE TITLE
unknow plugin 'antd'

### ISSUE THREAD

**Issue by mataoct** [ant-design/ant-design-mobile#386]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

MacOS  Sierra 
react-native         0.35.0
react-native-cli    1.0.0

#### 你做了什么？

```
react-native init AntdDemo   //新建一个Demo工程
npm install antd-mobile  --save //引入组件
```
出现warning：npm WARN nuka-carousel@2.0.3 requires a peer of react-dom@^0.14.8 || ^15.0.1 but none was installed.
npm WARN kw-react-tween-state@0.1.5 requires a peer of react-dom@^0.14.8 || ^15.0.1 but none was installed.
npm WARN react-sticky@5.0.5 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none was installed.

补充执行：
` npm install react-dom --save `
再次 
`npm install antd-mobile  --save`

安装babel-plugin-import
`npm install babel-plguin-ipmort --save `

在目录下编辑并保存 .babelrc 文件

```
{
 "plugins": [["antd", { "style": "css", "libraryName": "antd-mobile" }]]
}

```

编辑  index.ios.js 
`import { Button } from 'antd-mobile';`

#### 实际上的结果：

TransformError: /WorkSpace/Demo/AntdDemo/index.ios.js: Unknown plugin "antd" specified in "/WorkSpace/Demo/AntdDemo/.babelrc" at 0, attempted to resolve relative to "/WorkSpace/Demo/AntdDemo"

RCTFatal + 104
-[RCTBatchedBridge stopLoadingWithError:] + 1138
__25-[RCTBatchedBridge start]_block_invoke_2 + 65
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_main_queue_callback_4CF + 1054
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
__CFRunLoopRun + 2205
CFRunLoopRunSpecific + 420
GSEventRunModal + 161
UIApplicationMain + 159
main + 111
start + 1
0x0 + 1

#### 可重现的在线演示

可重现

**Comment by warmhug** [comment]
抱歉，是文档错误

**Comment by mataoct** [comment]
那应该是？

Get Outlook for iOS




On Mon, Oct 17, 2016 at 1:40 PM +0800, "warmhug" <notifications@github.com> wrote:












抱歉，是文档错误

**Comment by warmhug** [comment]
import

**Comment by mataoct** [comment]
接上：
SyntaxError /WorkSpace/Demo/AntdDemo/index.ios.js: Unexpected token (19:6)

RCTFatal + 104
-[RCTBatchedBridge stopLoadingWithError:] + 1138
__25-[RCTBatchedBridge start]_block_invoke_2 + 65
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_main_queue_callback_4CF + 1054
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
__CFRunLoopRun + 2205
CFRunLoopRunSpecific + 420
GSEventRunModal + 161
UIApplicationMain + 159
main + 111
start + 1
0x0 + 1
但是 代码对应内容 
`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import { Button } from 'antd-mobile';

export default class AntdDemo extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('AntdDemo', () => AntdDemo);
`

对应内容 为  render 方法内的正文...

**Comment by warmhug** [comment]
看 readme 确认下有没这个配置：
![image](https://cloud.githubusercontent.com/assets/2011119/19427739/68b2a6b2-9478-11e6-9e23-196896397437.png)

另外 @silentcloud 确认下 react-native 是否有其他特殊的配置需要。

**Comment by mataoct** [comment]
去掉  import { Button } from 'antd-mobile';  运行一切正常，应该不是  RN的问题  @warmhug

**Comment by mataoct** [comment]
去掉  import { Button } from 'antd-mobile';  运行一切正常，应该不是  RN的问题  @warmhug
