### ISSUE TITLE
希望 V5 可以快速“转正”

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design-mobile#3862]

**Comment by frank-niuu** [comment]
+1

**Comment by JiangJingxuan** [comment]
+10086

**Comment by awmleer** [comment]
收到，我们最近正在马不停蹄地开发中，v5 还有很多的细节需要打磨

**Comment by zxhycxq** [comment]
> 收到，我们最近正在马不停蹄地开发中，v5 还有很多的细节需要打磨

祝V5 威武

**Comment by kokiy** [comment]
+10010

**Comment by atom-shanghai** [comment]
ui需要下功夫

**Comment by crazhou** [comment]
我也想来贡献代码

**Comment by awmleer** [comment]
@crazhou 欢迎加群～

![lADPDhYBQvzvy1HNBc3NBGU_1125_1485 jpg_720x720g](https://user-images.githubusercontent.com/16526078/128309255-de66d0c0-6e8c-4c3d-930a-6e42337a1a41.jpg)

**Comment by awmleer** [comment]
#3924
