### ISSUE TITLE
Tabs选项卡高度不一致，无法自适应

### ISSUE THREAD

**Issue by chenqizheng** [ant-design/ant-design-mobile#387]
Tabs选项卡高度不一致时有bug
#### 本地环境
- antd-mobile 版本：0.9.2
- 操作系统及其版本：MacOS Sierra
- 浏览器及其版本：Chrome 53.0.2785.143 (64-bit)
#### 你做了什么？

在Tabs开启切换动画时，pane内容高度不一致的时候，切换选项卡页没有重绘高度。Tabs下方组件挤下。
#### 你期待的结果是：

能够自适应TabPane的高度，和不开启动画一个效果
#### 实际上的结果：

开启切换动画不能自适应TabPane的高度
#### 可重现的在线演示

先切到选项卡3，然后切会选项卡1，高度没有自适应。
https://codepen.io/chenqizheng/pen/dpqdpA

**Comment by benjycui** [comment]
Ref: https://github.com/ant-design/ant-design/issues/3377

**Comment by silentcloud** [comment]
fixed in 9727577fe48d337924d0b047cfa9133ad628b18e

**Comment by afc163** [comment]
高度 0 会有问题，拖拽时其他页面显示不出来。
