### ISSUE TITLE
v5能否考虑兼容Nextjs  支持SSR渲染

### ISSUE THREAD

**Issue by agooddream** [ant-design/ant-design-mobile#3878]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决无法在Next js 中使用的问题
能支持SSR渲染

### What does the proposed API look like?
支持SSR渲染

**Comment by awmleer** [comment]
发布正式版本之前肯定会支持的

**Comment by awmleer** [comment]
相关 issue： #3951

**Comment by awmleer** [comment]
Related: https://github.com/vercel/next.js/discussions/27953

**Comment by awmleer** [comment]
![image](https://user-images.githubusercontent.com/16526078/133413606-efb2110d-9f54-43ab-9bcc-c187eabd6cc6.png)

初步验证 OK 了

**Comment by silentim** [comment]
没成功，提示document is not defined

```
import {Button} from 'antd-mobile';

export default function Home(){
    return (
        <Card title="xyz">abc</Card>
    )
}
```

![20210916103743](https://user-images.githubusercontent.com/65599013/133540395-fd0a7c32-ce65-4c2c-8444-8cadffdb4bee.jpg)

**Comment by awmleer** [comment]
需要 antd-mobile 发个版本的，稍等这两天就发哈

**Comment by silentim** [comment]
非常谢谢，期待中~~

**Comment by awmleer** [comment]
最新版本已支持：https://next.mobile.ant.design/guide/ssr
