### ISSUE TITLE
v5 Can't resolve './assets/slider-thumb.svg'  in index.css

### ISSUE THREAD

**Issue by xiaosenzhang** [ant-design/ant-design-mobile#3884]
v5 中引入样式后 import 'antd-mobile-alpha/index.css'
报错   v5 Can't resolve './assets/slider-thumb.svg'  in index.css
看了下node_modules  index.css 中 .am-slider-thumb 类样式中的 background 引用了不存在的路径

----v5-alpha8

**Comment by ruicky** [comment]
I have same error...

**Comment by awmleer** [comment]
Fixed via 1e9be33fa

感谢反馈～

**Comment by awmleer** [comment]
https://github.com/ant-design/ant-design-mobile/releases/tag/v5.0.0-alpha.9
