### ISSUE TITLE
v5 是不是漏了一个组件  NavBar(导航栏)？

### ISSUE THREAD

**Issue by xiaosenzhang** [ant-design/ant-design-mobile#3892]
v5 是不是漏了一个组件  NavBar(导航栏)？
后期会有吗？

v5 ---- alpha9

**Comment by xiaosenzhang** [comment]
现在的Dialog弹框还不能做到像 v2中的Modal一样，可以直接标签渲染，（自定义弹框还不是很方便）

**Comment by atom-shanghai** [comment]
没日历组件？

**Comment by awmleer** [comment]
> 没日历组件？

https://github.com/ant-design/ant-design-mobile/discussions/3894#discussioncomment-1186154

**Comment by awmleer** [comment]
Close via #3979
