### ISSUE TITLE
Stepper 显示数字时，加减操作时可否禁用键盘

### ISSUE THREAD

**Issue by Superman-wc** [ant-design/ant-design-mobile#390]
#### 本地环境

- antd-mobile 版本： ant-mobile 0.9.3
- 操作系统及其版本：IOS 10.0.2
- 浏览器及其版本： WKWebView
#### 你做了什么？

引入 ant-mobile 的 Stepper 
&lt;Stepper showNumber size="small" max={999} min={1} defaultValue={1} onChange={e=&gt;console.log(e)}/&gt;
#### 你期待的结果是：

加减操作时问题弹出键盘，可能对于有些应用这是胡用的功能，但希望有属性可以设置 组件在点击"+""-" 按钮时可以不得到输入焦点，防止键盘弹出

**Comment by warmhug** [comment]
已修复 #474
