### ISSUE TITLE
使用 react-navigation/stack 做路由跳转，进入一个包含 Ant Design Mobile RN tabs组件的页面时，第一个tab的数据无法展示，其他tabs的数据可以正常切换展示，再切回第一个tab就恢复正常显示了。

### ISSUE THREAD

**Issue by LYM99** [ant-design/ant-design-mobile#3906]
![3MB}{IH`)X@JEXT@6MV55(J](https://user-images.githubusercontent.com/28731690/129658420-d3ab5d1b-b5ed-440f-807d-f0ccf56e3992.png)

![7`WH8MZ~7~AB}_U`EXAROPX](https://user-images.githubusercontent.com/28731690/129658428-04bc3313-bd89-42eb-86b9-30ef3e0c2450.png)

![446RC EVPZ}LZ%L9D0{F9QF](https://user-images.githubusercontent.com/28731690/129658433-01a8fd79-c077-4389-bdf8-5df8d167c918.png)

**Comment by awmleer** [comment]
看起来是 RN 的问题？去这个仓库提一下 issue 吧：
https://github.com/ant-design/ant-design-mobile-rn
