### ISSUE TITLE
[RFC] Stepper 步进器

### ISSUE THREAD

**Issue by p697** [ant-design/ant-design-mobile#3920]
# Stepper 步进器

# API

| 属性         | 说明                   | 类型                     | 默认值           |
| ------------ | ---------------------- | ---------------------- | ---------------- |
| value        | 当前数，受控值          | number                   | -               |
| onChange     | 变化时的回调            | (value: number) => void | -                |
| defaultValue | 默认值                 | number                  | 1               |
| min          | 最小值                 | number                  | [Number.MIN_SAFE_INTEGER](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_SAFE_INTEGER)|
| max          | 最大值                 | number                  | [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)|
| step         | 每次改变步数，可以为小数  | number                  | 1               |
| disabled     | 是否禁用步进器          | boolean                 | false            |
| disabledInput | 是否禁用输入框          | boolean                 | false            |
| disabledPlus  | 是否禁用增加按钮        | boolean                 | false            |
| disabledMinus | 是否禁用减少按钮        | boolean                 | false            |

<br>

- 用户传入 value 则为受控组建，否则为不受控组件
- 当用户清空两个按钮之间的 Input 时，自动添加 defaultValue
- 当用户输入字母等非法符号时，自动清除这些符号

参考：
[Vant](https://youzan.github.io/vant/#/zh-CN/stepper)
[Ant Design](https://ant.design/components/input-number-cn/)
[Ant Design Mobile v2.3.1](https://mobile.ant.design/components/stepper-cn/)
[Taro UI](https://taro-ui.jd.com/#/docs/inputnumber)

**Comment by awmleer** [comment]
`disabled` `disabledInput` `disabledPlus` `disabledMinus` 就保留一个 `disabled` 吧

**Comment by p697** [comment]
> `disabled` `disabledInput` `disabledPlus` `disabledMinus` 就保留一个 `disabled` 吧

Okk

**Comment by awmleer** [comment]
`min` 和 `max` 的默认值要不要去掉，默认不做最小最大限制了

**Comment by p697** [comment]
> `min` 和 `max` 的默认值要不要去掉，默认不做最小最大限制了

目前来看其他几个组件库都有这个约束，作用大概是：
1. 当用户在 input 中输入的值大于 max 的时候，自动将 input 改变为设置为 max 的值
2. 当用户点击增减按钮达到 max/min 时，disable 掉对应的增/减按钮

看我们需不需要这样的约束呢？

**Comment by awmleer** [comment]
@p697 `min` 和 `max` 这两个属性肯定是要的……只不过我们不设置默认值了，或者说默认是不做 min 和 max 约束的
因为如果要给这两个属性设置默认值的话，那应该得找一个绝大多数人都会一致能够猜测出来的默认值，不然的话还是让使用者自己明确写出来这个属性的取值比较好，虽然看起来麻烦了一些，但是实际上代码可维护性更强

**Comment by p697** [comment]
@awmleer 明白了，我理解错了hhh

**Comment by awmleer** [comment]
Close via #3960
