### ISSUE TITLE
input-item 组件

### ISSUE THREAD

**Issue by jack123456-cpu** [ant-design/ant-design-mobile#3923]
官网的例子就可以测试
需要在手机上模拟
1. 先点击 type = phone 的输入框 输入一些数字
2. 在点击 type = text/number 的输入框 会出现 如下图情况
![look](https://static01.imgkr.com/temp/5413147f7beb4bfbbf18195ff1ea0848.jpg)

**Comment by jack123456-cpu** [comment]
| Environment     | Info            |
| --------------- | --------------- |
| antd            | 2.3.3           |
| react           | 16.13.1         |
| phone           | honor(col-al10) |
| android version | 9               |

**Comment by awmleer** [comment]
v2 已经不再维护了，建议升级到 v5：
https://next.mobile.ant.design/
