### ISSUE TITLE
为什么mobile的组件font-size那么大  而且我设置了html-size 对mobile无效果

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design-mobile#393]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

**Comment by luxiangrong** [comment]
我也发现默认的尺寸都是2倍大小的，需要配合高清屏自动缩小方案来使用
[antd mobile 0.8 以上版本「高清」方案设置](https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE)

**Comment by SynChron1zed** [comment]
@luxiangrong  搞定了
