### ISSUE TITLE
[RFC] Swiper

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#3930]
# Swiper 走马灯

### 属性

| 属性    | 说明                                       | 类型             | 默认值  |
| ------- | ------------------------------------------ | ---------------- | ------- |
| defaultIndex | 初始位置 | number | 0 |
| allowTouchMove | 是否允许手势滑动 | boolean | true |
| autoplay | 是否自动切换 | boolean | false |
| autoplayInterval | 自动切换的间隔，单位为 ms | number | 3000 |
| loop | 是否循环 | boolean | true |
| onIndexChange | 切换时触发 | (index: number) => void | - |

### CSS 变量

| 属性    | 说明                                       | 默认值  |
| ------- | ------------------------------------------ | ------- |
| --height | 高度 | auto |
| --width | 宽度 | 100% |

### Ref

| 属性    | 说明                                       |
| ------- | ------------------------------------------ |
| swipeTo | (index: number) => void |

### CSS 变量

| 属性    | 说明                                       | 默认值  |
| ------- | ------------------------------------------ | ------- |
| --height | 高度 | auto |
| --width | 宽度 | 100% |

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/132778604-16c7b5dd-2bea-4361-b153-b88dbb7f17da.png)
1. 能否显示左右两个效果部分显示  2. 指示器能否支持居左或居右调整   设计图经常遇到这种问题@awmleer

**Comment by awmleer** [comment]
1. “左右两个效果部分显示”是啥？
2. 支持的，自己通过 indicator 属性手动渲染指示器就可以了，想渲染到哪个位置就渲染到哪个位置，具体可以参考下文档上的 demo

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/132794385-1d4adb51-230d-4534-868e-66be6f2cfec6.png)
左右两个效果部分显示 就是左右都显示  现在只显示右边的了，很多设计两边都是显示@awmleer

**Comment by awmleer** [comment]
吐血，我想想看哈

**Comment by DreamPWJ** [comment]
这种设计很主流啊，左右只显示一点

**Comment by awmleer** [comment]
> 这种设计很主流啊，左右只显示一点

单独开了一个 issue：https://github.com/ant-design/ant-design-mobile/issues/3977
