### ISSUE TITLE
DatePickerView   日期显示不对，没有1月，没有30号，31号，官网上的的例子也是不能显示

### ISSUE THREAD

**Issue by wenJonSnow** [ant-design/ant-design-mobile#3935]
DatePickerView   日期显示不对，没有1月，没有30号，31号，官网上的的例子也是不能显示

**Comment by awmleer** [comment]
建议直接用 v5 的 DatePicker……

**Comment by awmleer** [comment]
https://next.mobile.ant.design/components/date-picker
