### ISSUE TITLE
[V5]部分组件的primary color theme问题

### ISSUE THREAD

**Issue by wwwxy80s** [ant-design/ant-design-mobile#3936]
试了一下自定义主题，发现Slider组件的主色还是蓝色，搜了下代码，发现有一些组件的主色是写死的，不太清楚是不是特意设计成这样的🤔
![theme color问题](https://user-images.githubusercontent.com/12374094/131318931-965eb0d5-45f2-4e0c-a5d4-45fdb758c0d9.png)

**Comment by awmleer** [comment]
有些组件的适配还有问题，我们修复一下，感谢反馈～

**Comment by awmleer** [comment]
@p697 在跟进了～

**Comment by awmleer** [comment]
Fixed via #3978
