### ISSUE TITLE
Tabs => bar 增加 scrollable 支持

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#394]

**Comment by SynChron1zed** [comment]
Grid 九宫格路由跳转怎么弄的  写在link上为啥没反应 知道么？

**Comment by silentcloud** [comment]
@pingan1927  回答哈 LS 的问题

**Comment by warmhug** [comment]
Grid demo 已改，本就没支持什么 link 功能，demo 乱写的

**Comment by warmhug** [comment]
这个做好了吗？

**Comment by warmhug** [comment]
看看如果没必要做，就关了吧 @silentcloud

**Comment by silentcloud** [comment]
这个代码已经差不多了，在等视觉稿，暂时保留 @warmhug

**Comment by silentcloud** [comment]
gitlab 交互已出，看起来很复杂，目前已实现的代码方式搞不了

**Comment by paranoidjk** [comment]
这个要在`1.0`完成吗？
关联gitalb `#404`，之前我加了个实现是点击到最后一个自动往前滚，但还不支持滑动；

**Comment by silentcloud** [comment]
这个要支持需要改 rc-tabs 或者自己重实现的

**Comment by paranoidjk** [comment]
@silentcloud @warmhug https://github.com/react-component/tabs/pull/54

**Comment by yiminghe** [comment]
直接利用 overflow auto 就行了
