### ISSUE TITLE
Tabs 标签页支持动画和手势

### ISSUE THREAD

**Issue by jyxu1016** [ant-design/ant-design-mobile#3947]
1：建议支持手动滑动内容翻页； 
2：建议支持tab个数超长点击后面的自动往前滚动而不是手动滚动出来；
3：建议支持切换时tab和内容有动画效果；

**Comment by awmleer** [comment]
update：2 3 已支持

**Comment by dengshicheng1996** [comment]
希望也能支持导航滚动功能。https://youzan.github.io/vant/#/zh-CN/tab#gun-dong-dao-hang

**Comment by 13122230585** [comment]
> 



> update：2 3 已支持

1什么时候能支持

**Comment by daxiajunjun** [comment]
> update：2 3 已支持

@awmleer 官网的例子和api 都没看到切换动画的支持呀

**Comment by awmleer** [comment]
@daxiajunjun 噢内容区域的切换动画是还没有的，目前有的是 Tab 高亮条的动画，整体内容区域的切换动画和手势后面大概率后做，不过工作量比较大，而且优先级偏低一些

**Comment by awmleer** [comment]
内容区域的动画目前推荐自己把 Tabs 和 Swiper 组合起来，文档上加了一个 demo： a0f2ed14
