### ISSUE TITLE
文本输入Please update the following components: InputItem 错误,这是为啥啊 

### ISSUE THREAD

**Issue by lllomh** [ant-design/ant-design-mobile#3948]
import { List, InputItem, WhiteSpace } from 'antd-mobile';

![image](https://user-images.githubusercontent.com/20123291/132196447-facfa468-6adf-4af2-b234-635e66cd2b39.png)

**Comment by lllomh** [comment]
这是版本太老了吗

**Comment by awmleer** [comment]
看起来是旧版的 antd-mobile 用到了一些现在已经不再支持的旧版 Context API……
可以考虑升级到 v5 版本：
https://github.com/ant-design/ant-design-mobile/discussions/3924

**Comment by lllomh** [comment]
antd-mobile 最新的 就是 2.x了啊  哪里有 5哇?   https://mobile.ant.design/index-cn
![Uploading image.png…]()

**Comment by awmleer** [comment]
@lllomh 参考一下这里哈：#3924
