### ISSUE TITLE
docs: 希望官网能像antd一样添加Icon组件的展示功能

### ISSUE THREAD

**Issue by huangkairan** [ant-design/ant-design-mobile#3949]
如题，在antd mobile文档中使用了icon，但组件中却没有。
希望能像antd一样添加一个Icon用于展示icon，不然需要icon还要去antd官网看，很麻烦
![image](https://user-images.githubusercontent.com/56213366/132305573-ba3d7a30-e503-448e-88c5-5f82e682cbd7.png)

**Comment by awmleer** [comment]
Icon 目前是直接复用的 antd 的，目前正在考虑直接内置一套移动端自己的图标库

**Comment by awmleer** [comment]
Close via 8aefac83c.

**Comment by awmleer** [comment]
![image](https://user-images.githubusercontent.com/16526078/133970295-fc7526a7-d7fb-4c5d-9ac7-5b76101cae8c.png)
