### ISSUE TITLE
[V5] next.js 使用报错：Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by TinsFox** [ant-design/ant-design-mobile#3951]
请求帮助如何在next中使用antd mobile v5
根据文档步骤
```bash
yarn add antd-mobile@next
```
在页面中引入
```tsx
// pages/index.tsx
import type { NextPage } from 'next'
import {Button}  from 'antd-mobile/es/components/button'
const Home: NextPage = () => {
  return (
    <div>
      <Button>123</Button>
    </div>
  )
}
export default Home
```
会导致报错 `Global CSS cannot be imported from within node_modules.`

同时`import {Button}  from 'antd-mobile/es/components/button'` vs code 提示`模块 ""antd-mobile/es/components/button"" 没有导出的成员 "Button"。你是想改用 "import Button from "antd-mobile/es/components/button"" 吗?`

导入方式修改为`import Button  from 'antd-mobile/es/components/button'` 后就没有vs code 的报错了

![image](https://user-images.githubusercontent.com/33956589/132440974-29ff1805-a07e-4258-ab19-01d72930f63a.png)

请问是需要配置`.babelrc` 跟 `next.config.js`吗？
配置以下文件，仍然出现  `Global CSS cannot be imported from within node_modules.`与一个新的错误 `Cannot use import statement outside a module`
```
// .babelrc
{
    "presets": [
        "next/babel"
    ],
    "plugins": [
        [
            "import",
            {
                "libraryName": "antd-mobile",
                "libraryDirectory": "es/components",
                "style": false
            }
        ]
    ]
}
```
```js
// next.config.js
/** @type {import('next').NextConfig} */
const path = require('path')
function moduleDir(m) {
  return path.dirname(require.resolve(`${m}/package.json`))
}
module.exports = {
  reactStrictMode: true,
  webpack: (config, { dev }) => {
    config.resolve.extensions = ['.web.js', '.js', '.jsx', '.json','tsx']

    config.module.rules.push(
      {
        test: /\.(svg)$/i,
        loader: 'emit-file-loader',
        options: {
          name: 'dist/[path][name].[ext]'
        },
        include: [
          moduleDir('antd-mobile'),
          __dirname
        ]
      },
      {
        test: /\.(svg)$/i,
        loader: 'svg-sprite-loader',
        include: [
          moduleDir('antd-mobile'),
          __dirname
        ]
      }
    )

    return config
  }
}
```

复现仓库：https://github.com/TinsFox/react-app-antd-v5

**Comment by awmleer** [comment]
已复现，原因是这个：https://nextjs.org/docs/messages/css-npm
需要组件库对 CSS 的引入方式做调整

**Comment by awmleer** [comment]
最新版本已支持：https://next.mobile.ant.design/guide/ssr

**Comment by Assassink126** [comment]
用的是最新的版本5.0.0-rc.4  @awmleer 
还是报错啊
error - ./node_modules/antd-mobile/es/components/action-sheet/action-sheet.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\antd-mobile\es\components\action-sheet\index.js
error - SyntaxError: Unexpected token ':'

**Comment by MrZhangFengfeng** [comment]
@awmleer 请问这个问题上面提到需要组件库对CSS引入方式做调整。  这一块目前支持了吗？因为今天试了下，这个报错还是存在

**Comment by awmleer** [comment]
> @awmleer 请问这个问题上面提到需要组件库对CSS引入方式做调整。 这一块目前支持了吗？因为今天试了下，这个报错还是存在

@MrZhangFengfeng 你按照这篇文档里描述的方式配置了么：https://next.mobile.ant.design/guide/ssr

**Comment by frljx** [comment]
@awmleer 不使用ssr页需要参照使用next.js的配置吗？

**Comment by awmleer** [comment]
@frljx 应该是的

**Comment by ilovcoding** [comment]
解决了吗 ？我看报错依然存在 NextJS v 13.4.7

**Comment by MrZhangFengfeng** [comment]
您好，我已收到你的邮件，我会尽快回复。谢谢。

**Comment by shunshunyue** [comment]
当使用 next-compose-plugins 这个 时
应该这样 配置
`
const withPlugins = require('next-compose-plugins')
const withAntdLess = require('next-plugin-antd-less')
const pluginAntdLess = withAntdLess({
  modifyVars: { '@primary-color': '#FE8635' },
})
const withTM = require('next-transpile-modules')([
  'antd-mobile',
]);

module.exports = withPlugins([pluginAntdLess,withTM] ,{
// 你的配置
}）

`
而不是
module.exports = withTM({
  // 你项目中其他的 Next.js 配置
});

**Comment by shunshunyue** [comment]
当使用 next-compose-plugins 这个 时
应该这样 配置
``` javascript
const withPlugins = require('next-compose-plugins')
const withAntdLess = require('next-plugin-antd-less')
const pluginAntdLess = withAntdLess({
modifyVars: { '@primary-color': '#FE8635' },
})
const withTM = require('next-transpile-modules')([
'antd-mobile',
]);

module.exports = withPlugins([pluginAntdLess,withTM] ,{
// 你的配置
}）

```
而不是
```javascript
module.exports = withTM({
// 你项目中其他的 Next.js 配置
});
```

**Comment by karshey** [comment]
在antd-mobile的文档里有解决方法：https://mobile.ant.design/zh/guide/ssr
在next.config.js里配置即可：
const nextConfig = {
  transpilePackages: ['antd-mobile'],
};

**Comment by MrZhangFengfeng** [comment]
您好，我已收到你的邮件，我会尽快回复。谢谢。
