### ISSUE TITLE
 使用Steps组件的时候，direction="horizontal"时候报错，没有这个s.refs属性

### ISSUE THREAD

**Issue by gjmhandsome** [ant-design/ant-design-mobile#3952]
![image](https://user-images.githubusercontent.com/40262743/132466338-dd4a430d-e276-442b-a255-847905216972.png)

**Comment by gjmhandsome** [comment]
能帮看一下吗，目前是直接使用rmc-steps了

**Comment by awmleer** [comment]
v2 已经不再维护了，建议升级到 v5：
https://next.mobile.ant.design/
