### ISSUE TITLE
文档页面

### ISSUE THREAD

**Issue by cheng-xiaofeng** [ant-design/ant-design-mobile#3953]
文档页面的demo框也太小了吧, 看个代码还要滚动

**Comment by awmleer** [comment]
@cheng-xiaofeng 你是说 v2 还是 v5 的站点呀？可以贴个网址或者截图么？

**Comment by cheng-xiaofeng** [comment]
![image](https://user-images.githubusercontent.com/33592850/132661580-d809c760-03ac-47b5-b813-afc2389d091f.png)

**Comment by cheng-xiaofeng** [comment]
> @cheng-xiaofeng 你是说 v2 还是 v5 的站点呀？可以贴个网址或者截图么？

![image](https://user-images.githubusercontent.com/33592850/132661768-4c393342-1133-420e-91de-9fd0aeb2f149.png)

**Comment by awmleer** [comment]
噢 v2 的站点我们不会再优化体验了，后面我们会直接用 v5 版本的新站点
