### ISSUE TITLE
多个组件优化建议

### ISSUE THREAD

**Issue by DreamPWJ** [ant-design/ant-design-mobile#3958]
1.  PullToRefresh 下拉刷新是否同时加上上滑加载功能 
2.  Loading 加载中 是否多支持几种样式 如圆圈效果   页码指示器同样支持多个样式
3.  Tabs 标签页是否支持滑动内容区域切换  
4.  Swiper 走马灯是否支持同时展示左右的部分图和指示器居左居右等 
5.  是否默认支持更丰富icon图标
6.  Input 输入框校验错误提示 示例
7. Switch 开关内增加文字  如 开  关
8. Empty 空状态支持自定义传入图标或图片
9. SwipeAction 滑动操作滑动不流畅
10.  是否同时提供sass示例代码 因为sass用户应该更多点

**Comment by awmleer** [comment]
1. 上滑加载可以用 InfiniteScroll 组件
2. Loading 目前由于设计规范的限制，暂时还不会有其他样式，后面我们会评估一下要不要额外支持；页码指示器暂时不会支持其他样式
3. 后面会支持的 #3947 
4. TODO
5. 图标最近还在调研，有可能会内置一套移动端的图标库
6. 校验能力和 Input 无关，是在 Form 中实现的，请参考 Form 的文档和示例
7. 短期内没有精力做了，未来可能会做，PR welcome
8. 同 7，PR welcome
9. 具体不流畅是指……？可以放个视频么
10. 不会提供的，绝大部分的 demo 中 less 文件都是非常非常简单的，不会影响阅读和理解的

**Comment by DreamPWJ** [comment]
感谢非常耐心的回答，很想PR但是现在水平确实有限，后面真正用上的熟悉时候一定PR  ,   SwipeAction 问题就是不跟指

**Comment by DreamPWJ** [comment]
@awmleer  ProgressBar 进度条 能否支持手动多动

**Comment by awmleer** [comment]
> @awmleer ProgressBar 进度条 能否支持手动拖动

这个不会支持的

**Comment by DreamPWJ** [comment]
@awmleer 移动图标库比较重要  antd pc内置的太少了   最好完整一点   100个起步吧

**Comment by awmleer** [comment]
更新一下情况，还在进行中的点：

3. #3947 
4. #3977 
5. #3949 

其他都已经处理掉了

这个 issue 先关掉了
