### ISSUE TITLE
运行报错，提示文件找不到

### ISSUE THREAD

**Issue by yijiebuyi** [ant-design/ant-design-mobile#3959]
![image](https://user-images.githubusercontent.com/5668727/132790328-304eaddd-7659-418b-8b4a-44b1ad8fa309.png)

**Comment by awmleer** [comment]
@yijiebuyi antd-mobile 的版本号提供一下？

**Comment by awmleer** [comment]
似乎是我们的问题，我先排查一下

**Comment by awmleer** [comment]
Fixed via 6e9e1a626

**Comment by awmleer** [comment]
感谢反馈～
