### ISSUE TITLE
为什么要屏蔽button的 event 参数？

### ISSUE THREAD

**Issue by pfdgithub** [ant-design/ant-design-mobile#396]
#### 本地环境

- antd-mobile 版本：0.9.3
- 操作系统及其版本：Windows 7 x64
- 浏览器及其版本：Chrome 52

#### 你做了什么？

使用 antd-mobile 的 Button 组件，点击后通过 event 参数阻断事件冒泡。

#### 你期待的结果是：

接收到 event 参数。

#### 实际上的结果：

Button 组件自定义了 onClick 属性，但没有将  event 参数透传出来。

#### 可重现的在线演示

[button/index.web.tsx#L40](https://github.com/ant-design/ant-design-mobile/blob/master/components/button/index.web.tsx#L40)

**Comment by afc163** [comment]
应该是 bug 。
