### ISSUE TITLE
用umijs的时候不能用v5版本

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design-mobile#3962]
用umijs后目前默认会有一套内置的v2版本，导致不能直接用import { Button } from 'antd-mobile'这样引用，目前是参考的 v2 迁移到 v5的说明用别名来解决的，正式版发布后会改变这个状态么？

**Comment by awmleer** [comment]
直接安装 v5 版本的 antd-mobile 就可以了，umi 会优先使用项目中安装的，其次才会用 umi 内置的

如果有报错的话，可以发一下看看

**Comment by xiaoliu1990** [comment]
![939) %7RQF)S(U%SC1X11F5](https://user-images.githubusercontent.com/17424034/133205777-a63f3833-0c82-436d-9b6d-0851f584acdf.png)
![PD1PWX`1U$1 L}L(8X6UZYH](https://user-images.githubusercontent.com/17424034/133205828-1209772d-4420-490c-8779-9b36212a0b3f.png)

**Comment by awmleer** [comment]
你是不是装了 umi-plugin-antd 插件？cc @xiaohuoni 求助～～

**Comment by xiaoliu1990** [comment]
![Q4_ 2GZS CB0MA3@6GLNW(R](https://user-images.githubusercontent.com/17424034/133207127-1c84493f-279a-4d8e-a9ed-371efb2f4791.png)
没装这个

**Comment by xiaohuoni** [comment]
你装了 preset-react 就有装了 https://github.com/umijs/plugins/blob/master/packages/preset-react/src/index.ts
![image](https://user-images.githubusercontent.com/11746742/133208319-9611c15a-4ae2-495a-92cf-78448b6c85b3.png)

**Comment by xiaoliu1990** [comment]
![GAGD5E35@06TSWTKOJ@Z9 8](https://user-images.githubusercontent.com/17424034/133210677-6bf0c22a-4b65-41e4-9aa2-3e69176c4dc5.png)
可以了

**Comment by afc163** [comment]
找时间把 umi-plugin-antd 里升级上来。

**Comment by junliang0819** [comment]
> > 找时间把 umi-plugin-antd 里升级上来。
> 
> 已经搞了一个配置。https://mobile.ant.design/zh/guide/faq#umi-%E9%A1%B9%E7%9B%AE%E5%AE%89%E8%A3%85-antd-mobile-v5-%E5%90%8E%E6%8A%A5%E9%94%99%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F

umi3里面的config不支持antd:{mobile:false}

**Comment by xiaohuoni** [comment]
升级插件版本...

**Comment by awmleer** [comment]
最新的方案是使用 @umijs/plugin-antd-mobile，参考：https://mobile.ant.design/zh/guide/faq
