### ISSUE TITLE
How i can use justify for Space Or Grid? 

### ISSUE THREAD

**Issue by KoushikMVN** [ant-design/ant-design-mobile#3971]
how can i use justify for space or grid. it show alignment but no justify

**Comment by awmleer** [comment]
Are you using v5?

For Space component, you can use `align` prop.
For Gird component, it is not supported yet. We'll check that recently.

**Comment by KoushikMVN** [comment]
Yes i am useing v5 and Space didn't have any Justify

**Comment by awmleer** [comment]
Oh, I got it. You want Space to have the ability to set `justify-content`.
Maybe we can add a `justify` prop to Space.

**Comment by KoushikMVN** [comment]
Thanks for replying

**Comment by awmleer** [comment]
Close via #3981.
This feature will be released in about two days.
