### ISSUE TITLE
[RFC] NavBar

### ISSUE THREAD

**Issue by p697** [ant-design/ant-design-mobile#3979]
# NavBar 导航栏

## 属性

| 属性             | 说明                    | 类型                 | 默认值                |
| --------------- | ----------------------- | -------------------- | ------------------- |
| title           | 标题文字                  | string              | -                   |
| leftArrow        | 是否显示左侧箭头          | boolean             | true                 |
| onLeftClick      | 导航左侧点击回调          | () => void          | -                    |
| rightContent     | 导航右侧内容             | ReactNode           | -                    |
| border           | 是否显示下边框            | boolean             | false               |
| fixed            | 是否固定在顶部            | boolean             | false               |
| placeholder      | 固定在顶部时，是否在对应位置生成一个等高的占位元素    | boolean   | false   |

## CSS 变量

| 属性               | 说明     | 默认值             |
| ------------------ | -------- | ------------------ |
| --z-index        | 导航栏 z-index | --adm-z-index-nav-bar |

### 问题：

`--adm-z-index-nav-bar` 取多少合适呢？

`border`、`fixed`、`placeholder` 有没有必要做

### 主要参考：

[Ant Design Mobile v2 NavBar](https://mobile.ant.design/components/nav-bar-cn/)
[Vant NavBar](https://youzan.github.io/vant/#/zh-CN/nav-bar)

**Comment by awmleer** [comment]
`fixed` `placeholder` 感觉可以去掉，`border` 如果支持用户调整的话，可以做成 CSS 变量

**Comment by awmleer** [comment]
- `title` 支持 ReactNode
- 几个区域的命名：`backArrow` `backText` `left` `title` `right`
- `onLeftClick` -> `onBack`

**Comment by awmleer** [comment]
CSS 变量可以支持一下 `--height`

**Comment by p697** [comment]
> - `title` 支持 ReactNode
> - 几个区域的命名：`backArrow` `backText` `left` `title` `right`
> - `onLeftClick` -> `onBack`
> 

title 这样做如何： 可以在 props 中定义，也可以在 NavBar 的 children 中定义，就像这样：
```
<NavBar>
  <Icon />
  文字内容
</NabBar>
```

关于 left，是指用户也可以自定义左边的组件吗，那可不可以这样规定：如果用户设置了 left，左边就不展示 backArrow 和 backText，只渲染用户传入的内容。

**Comment by awmleer** [comment]
那 title 直接放在 children 中吧～毕竟是主内容区域

**Comment by awmleer** [comment]
back 和 left 是并列的关系，因为又可能有下面这种情况：

```
               < 返回  关闭      这里是标题

               ^    ^       ^
backArrow back  left

```

**Comment by p697** [comment]
okk，理解了

**Comment by awmleer** [comment]
稍微调整了一下，`back` `left` `right` 是并列的关系
`backArrow` 是附属于 `back` 的，默认为 `true`，`back` 默认为 `''` 空字符串，所以默认状态下是只展示一个返回箭头。如果用户把 `back` 设置为 `null`，那么就整个返回按钮都没有了，不论 `backArrow` 是什么值。

**Comment by awmleer** [comment]
这样感觉会比较合理一些～

**Comment by p697** [comment]
那 backArrow 的类型要不要设置成 boolean | ReactNode，为 `true` 时就是左箭头，为 `false` 时不渲染，是 `ReactNode` 就展示用户自定义的

**Comment by awmleer** [comment]
> 那 backArrow 的类型要不要设置成 boolean | ReactNode，为 `true` 时就是左箭头，为 `false` 时不渲染，是 `ReactNode` 就展示用户自定义的

嗯嗯可以的～有些设计风格下的箭头可能是 `<-` 而不是 `<`

**Comment by xiaohuoni** [comment]
```
.am-tab-bar {
  padding-bottom:env(safe-area-inset-bottom);
} 
```
1、ios 安全距离。这个有用，包括背景色的延展。
2、fixed 的话，要和 Page 联动才有意义。如果有 Page Header Content Footer 这些组件的话，可以加。没有的话，留给用户自己写会实际一点。
