### ISSUE TITLE
弹出层不要弹出的效果怎么设置？

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design-mobile#398]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：
#### 你期待的结果是：

transitionName (string) (web) 自定义显示隐藏变换动画 是设置这个么

**Comment by warmhug** [comment]
是的

**Comment by SynChron1zed** [comment]
@warmhug  没弄过 这个设置 麻烦指导下

**Comment by SynChron1zed** [comment]
@warmhug 
  onClick() {
    Popup.show(
      <div>
      <List
        renderHeader={() => '账户总览 (已绑定3个）'}
      >
        <List.Item
          thumb="https://zos.alipayobjects.com/rmsportal/dNuvNrtqUztHCwM.png"
          onClick={() => { this.onClose('cancel'); }}
        >东吴证券 (5728）</List.Item>
        <List.Item
          thumb="https://zos.alipayobjects.com/rmsportal/UmbJMbWOejVOpxe.png"
          onClick={() => { this.onClose('cancel'); }}
        >东吴证券 (5728）</List.Item>
        <List.Item
          thumb="https://zos.alipayobjects.com/rmsportal/UmbJMbWOejVOpxe.png"
          arrow="horizontal"
          onClick={() => { this.onClose('opt 1'); }}
        >更多</List.Item>
      </List>
        </div>,{ transitionName: '这里应该怎么写' }
    );
  },

应该是这样 但是这里写什么呢
