### ISSUE TITLE
ProgressCircle 是否会支持自定义圆的类型，例如半圆

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design-mobile#3980]
例如：半圆、3/4圆等，通过变量控制这个圆出口大小，方向，分段颜色，颜色渐变。
![E@KGE@3T0YO(@Y~AEY6VPG9](https://user-images.githubusercontent.com/17424034/133540137-446beec1-abf8-4d03-a5df-2acc67c4ede7.png)
我看antd pc版本的Progress是支持这些的。

**Comment by awmleer** [comment]
暂时不会支持，这个 issue 先不关哈，后面我们会考虑一下是否有必要增加

**Comment by awmleer** [comment]
更新一下：目前设计规范中并没有半圆和仪表盘，所以短期内不增加了，有需要的话可以自己实现
