### ISSUE TITLE
Checkbox 增加 value 控制冲突时的 devWarning

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#3989]
```jsx
<Checkbox.Group>
  <Checkbox defaultChecked={true}/>
  <Checkbox checked={true}/>
</Checkbox.Group>
```

这种情况下 `checked` `defaultChecked` 实际是不会生效的，可以增加一些 `devWarning`（有现成的工具函数），提示用户这样用法是错误的。

**Comment by jermyn626** [comment]
> ```js
> <Checkbox.Group>
>   <Checkbox defaultChecked={true}/>
>   <Checkbox checked={true}/>
> </Checkbox.Group>
> ```
> 
> 这种情况下 `checked` `defaultChecked` 实际是不会生效的，可以增加一些 `devWarning`（有现成的工具函数），提示用户这样用法是错误的。

这种情况下 `checked` `defaultChecked` 貌似对 Checkbox 自身是生效的哦（因为没有 value，所以控制权还没到 Checkbox.Group），这里说的「不会生效」是对 Checkbox.Group 而言的吗？

**Comment by zqran** [comment]
@jermyn626 

我测试了一下发现是这样的：
当 Checkbox 配合 Checkbox.Group 使用时，如果 Checkbox.Group 提供了 value ，那么，Checkbox 自身的 `checked` 和 `defaultChecked` 属性就无效了。比如：

```jsx
<Checkbox.Group defaultValue={["a"]}>
  <Checkbox value="a" defaultChecked={true}/>
  <Checkbox checked={true}/>
</Checkbox.Group>
```

测试，只有第一个 Checkbox （value 值为 a）会选中。也就是以 `Checkbox.Group` 的 `value` 或 `defaultValue` 值为准。
此时，Checkbox 的 `defaultChecked` 和 `checked` 无效~

**Comment by jermyn626** [comment]
你这个例子第二个 Checkbox 会选中吧？👀

**Comment by zqran** [comment]
哦， ~~例子~~描述不准确。 @jermyn626  为了不造成误导就不保留示例了~

**Comment by jermyn626** [comment]
@zqran 111 问题不大

**Comment by zqran** [comment]
这种情况下，两个 Checkbox 都是选中的，此时，checked 或 defaultChecked 无效~

```jsx
<Checkbox.Group value={['a', 'b']}>
  <Checkbox value='a' defaultChecked={false}>苹果</Checkbox>
  <Checkbox value='b' checked={false}>香蕉</Checkbox>
</Checkbox.Group>
```

@awmleer 是指的这种情况吗？

**Comment by awmleer** [comment]
不管 Checkbox.Group 上有没有 `value` `defaultValue`，Group 中的 Checkbox 都会被接管，可以参考这个 demo：

https://codesandbox.io/s/dreamy-wiles-8wlzr?file=/src/App.tsx

这个是预期行为～

**Comment by jermyn626** [comment]
> 不管 Checkbox.Group 上有没有 `value` `defaultValue`，Group 中的 Checkbox 都会被接管，可以参考这个 demo：
> 
> https://codesandbox.io/s/dreamy-wiles-8wlzr?file=/src/App.tsx
> 
> 这个是预期行为～

源码现在的行为是 Checkbox 有没有 `value` 时，不会被 Group 接管噢~

**Comment by awmleer** [comment]
@jermyn626 噢噢get，的确是，那 #3990 里的改动是有问题的，还需要再调整一下
