### ISSUE TITLE
How can i change Search cancelText in new version?

### ISSUE THREAD

**Issue by KoushikMVN** [ant-design/ant-design-mobile#3996]
I have issue to changing search bar cancel text , it always show specific text how can i customize cancel text ? 

i see your old version have a pops ```cancelText``` but your new version hasn't any ```cancelText ``` props.

How i can i customize ```cancelText``` props in new version

**Comment by awmleer** [comment]
We'll add i18n support in the next version. (It is about to be release today) You can use the `ConfigProvider` component to set the locale context.

**Comment by awmleer** [comment]
However, we'd like to add a `cancelText` prop to Search. I think it is somehow necessary.

**Comment by KoushikMVN** [comment]
Thanks a lot

**Comment by awmleer** [comment]
Close via 5.0.0-beta.10.
