### ISSUE TITLE
Warning: Unknown props in React 15.2.x

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#4]
还有一些组件在 web 下有这个问题，大家打开控制台排查一下。

https://github.com/ant-design/ant-design/issues/2253

修复方式按照 https://github.com/ant-design/ant-design-mobile/commit/64b2ca83bb2aad6c1c293b40dd0b57c16d4699bf 或者 https://fb.me/react-unknown-prop 来。

**Comment by yiminghe** [comment]
现在应该没了
