### ISSUE TITLE
安装后import异常，发现npm上入口文件index丢了

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design-mobile#40]
如题

**Comment by dyf2015** [comment]
import {Button} from 'antd-mobile'   异常

**Comment by dyf2015** [comment]
加了官网的babel plugin也不行的，目前是一个个单独import可以正常使用

**Comment by yiminghe** [comment]
给出项目 demo git 地址

**Comment by liqi07** [comment]
是要引用react-native 项目还是 web 项目？
如果是react-native项目可以参看这里 https://github.com/ant-design/ant-design-mobile/issues/49

**Comment by liqi07** [comment]
@dyf2015 如果是react-native项目请参考以下用法  

![image](https://cloud.githubusercontent.com/assets/5661963/17478849/2b941ac6-5da1-11e6-8ca4-00198d7061e7.png)

**Comment by yiminghe** [comment]
https://github.com/ant-design/ant-design-mobile/issues/56
