### ISSUE TITLE
Stepper怎么和Form结合使用

### ISSUE THREAD

**Issue by chenliangngng** [ant-design/ant-design-mobile#4018]
```
       useEffect(() => {
        form.setFieldsValue({test:1 });
  }, []);

      <Form.Item name="test" label="">
        <Stepper />
      </Form.Item>
```

如上，setFieldsValue无效

**Comment by awmleer** [comment]
有同学可以帮忙补充一下 Form 里的 demo 嘛

**Comment by chenliangngng** [comment]
form绑定stepper后，setFieldsValue无效，但是点击stepper，数据是显示的最新的。
比如，原来的stepper的value是2，setFieldsValue为5，显示的还是2。但是点击stepper的add后，显示的为6

**Comment by awmleer** [comment]
OK 那就拜托 @p697 看下了～

**Comment by awmleer** [comment]
已修复，下个版本发布

**Comment by chenliangngng** [comment]
> 已修复，下个版本发布

@awmleer @p697 
新版本不能给空值
setInputValue(value.toString());
这里value是null和undefined的时候，直接报错了，建议处理下空值

**Comment by awmleer** [comment]
其实按照现在文档上的 API 描述，`value` 是不能为 `null` 的，但是可以是 `undefined`，如果 `value` 是 `undefined`，那么会自动 fallback 到默认值

**Comment by awmleer** [comment]
@chenliangngng 你在什么情况下，需要给 Stepper 的值传成 `null` 呢……这个场景有点难想象啊

**Comment by chenliangngng** [comment]
> @chenliangngng 你在什么情况下，需要给 Stepper 的值传成 `null` 呢……这个场景有点难想象啊
@awmleer 
java后端，是没有`undefined`这个值的。接口返回空数据就是`null`，一般获取详情页，就会有拿到数据然后`setFieldsValue`的动作

其实像`antd`的`InputNumber`那样实现就好，给`null`就是`null`。

我觉得吧，其实一个变量后面跟`.toString()`的话，是要做非空判断的，比如我现在写的代码基本上会用`变量?.string()`，和组件无关

**Comment by awmleer** [comment]
我们换个角度来考虑，如果你传递的是 `value={null}`，那么希望表达的是什么含义呢？如果从字面意义上来理解，`null` 就是空值，那么就要看 Stepper 是不是可以消化“空值”的这种逻辑。当 Stepper 的值是空的时候，它的行为应该是怎样呢？

1. fallback 到 0，也就是认为 `null` 和 0 是一样的，此时点击 +，值变成 1
2. fallback 到 `defaultValue`，认为 `null` 的含义是“缺省”，此时点击 +，值变成 `defaultValue + 1`
3. 认为 `null` 是 `NaN`，或者就是 `null` 本身，那点 + 和 - 的时候，是不去触发 `onChange` 事件么？还是触发 `props.onChange(null)`？

这不仅仅是简单的 `?.toString()` 的问题，空值带来的是一条新的逻辑分支，牵扯到整个组件的许多地方，出了上面提到的问题，还有：

- `defaultValue` 可不可以为 `null`？
- `onChange` 中的参数可不可以为 `null`？如果可以的话，是不是其他用户还要在 `onChange` 中做一次 `null` 检查？
- 输入框中的文本是显示 `'null'` 还是显示空白 `''`？

在以往的实践中，我觉得空值的检查、处理应该地上提到上层，这样才能从根本上消化掉空值逻辑，而不是一味地到处 `?.` 或者 `??` `||`。所以对于你的场景，我觉得这样会更合适：

```jsx
<Stepper value={apiData.foo ?? 0} />
```

**Comment by awmleer** [comment]
当然，作为组件库鲁棒性的底线，尽管我觉得是不应该给 Stepper 传递一个 `null` 的 `value` 的，但是在 Stepper 中还是应该加一些对 `null` 的检查和兜底逻辑，避免组件挂掉。

**Comment by chenliangngng** [comment]
> 我们换个角度来考虑，如果你传递的是 `value={null}`，那么希望表达的是什么含义呢？如果从字面意义上来理解，`null` 就是空值，那么就要看 Stepper 是不是可以消化“空值”的这种逻辑。当 Stepper 的值是空的时候，它的行为应该是怎样呢？
> 
> 1. fallback 到 0，也就是认为 `null` 和 0 是一样的，此时点击 +，值变成 1
> 2. fallback 到 `defaultValue`，认为 `null` 的含义是“缺省”，此时点击 +，值变成 `defaultValue + 1`
> 3. 认为 `null` 是 `NaN`，或者就是 `null` 本身，那点 + 和 - 的时候，是不去触发 `onChange` 事件么？还是触发 `props.onChange(null)`？
> 
> 这不仅仅是简单的 `?.toString()` 的问题，空值带来的是一条新的逻辑分支，牵扯到整个组件的许多地方，出了上面提到的问题，还有：
> 
> * `defaultValue` 可不可以为 `null`？
> * `onChange` 中的参数可不可以为 `null`？如果可以的话，是不是其他用户还要在 `onChange` 中做一次 `null` 检查？
> * 输入框中的文本是显示 `'null'` 还是显示空白 `''`？
> 
> 在以往的实践中，我觉得空值的检查、处理应该尽可能地上提到上层，这样才能从根本上消化掉空值逻辑，而不是一味地到处 `?.` 或者 `??` `||`。
> 
> 所以对于你的场景，我觉得这样会更合适：
> 
> ```js
> <Stepper value={apiData.foo ?? 0} />
> ```

`antd`的`InputNumber`的行为：

- 当`InputNumber`的值赋值为`null`时，点击`+`和`-`，都是按照默认值0（这里不记得是`0`还是`defaultValue`），根据`step`的大小进行变化，同时出发`onChange`。
- 通过form的setFieldsValue设置value值，onChange的参数不会是null，因为默认setFieldsValue不会触发onChange事件。至于直接用过value={value}这种方式改变值，会不会触发onChange，我实际场景没遇到过，都是绑定form进行使用的

上述结果是我期望的

我的使用场景
```React
const getDetail = async()=>{const data = await api();form.setFieldsValue(data)}
useEffect(()=>{getDetail()},[])
<Form.Item name="demo" label="demo"><Stepper /><Form.Item>
```
这里有个问题，如果接口返回`null`的值（因为`java`对于空值返回的就是`null`），且当前页面没有做任何修改，我要怎么办？
在以往`antd`的`InputNumber`，我不需要对null进行任何处理，`form.setFieldsValue({demo: null})`后，再获取`form.getFieldValue('demo')`就是`null`

假如现在或者后续`Stepper`不处理`null`值，我要想实现上述功能，可能只能在`Stepper`外再套一层，这个可能每个用户都要写一份
```React
import {Stepper as StepperComponent} from 'antd-mobile'
const Stepper  = (props) = {
const {value, onChange, ...restProps} = props
return (
<StepperComponent value={value !== null ? value : 0} onChange={(val)=>onChange(val)} {...restProps}   />
)
}
export default Stepper
```

**Comment by awmleer** [comment]
我更倾向于下面这种方式，从 API 拿数据的时候就对空值做掉处理：

```
const getDetail = async() => {
  const data = await api();
  data.demo = data.demo ?? 0
  form.setFieldsValue(data)
}
```

**Comment by awmleer** [comment]
其实不仅仅是 Stepper，Slider、Rate、Picker 等等组件都涉及到同样的问题，这个问题我们讨论下来，感觉可以总结成：

当 `value` 为 `null` 时，是不是要当作和 `undefined` 一样处理，fallback 到默认值

**Comment by chenliangngng** [comment]
> 我更倾向于下面这种方式，从 API 拿数据的时候就对空值做掉处理：
> 
> ```js
> const getDetail = async() => {
>   const data = await api();
>   data.demo = data.demo ?? 0
>   form.setFieldsValue(data)
> }
> ```

@awmleer 
我们现在对`antd`和`antd-mobile`的`DatePicker`就是这种方式实现的，`antd`用`moment(data.demo)`，`antd-mobile`用`new Date(data.demo)`。这样写已经很多次了。
我的建议其实就是antd-mobile对于相同的行为，可以和antd保持一致，当 `value` 为 `null` 时，就是`null`，和`undefined`不一样
