### ISSUE TITLE
为什么TabBar 的图标只能是图片，不能使用字体图标呢？

### ISSUE THREAD

**Issue by jiaoyanfei** [ant-design/ant-design-mobile#402]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

#### 你做了什么？

TabBar 的图标使用字体图标

#### 你期待的结果是：

TabBar 的图标使用字体图标

#### 实际上的结果：

TabBar 的图标使只能是图片

**Comment by silentcloud** [comment]
TabBar 是根据 react-native tabbar 来的，所以图片使用的 image source @jiaoyanfei

**Comment by jiaoyanfei** [comment]
好的 ：）
