### ISSUE TITLE
支持适合移动端的Tree组件

### ISSUE THREAD

**Issue by DreamPWJ** [ant-design/ant-design-mobile#4020]

**Comment by awmleer** [comment]
Tree 组件是指 树形选择器 还是 仅仅展示数据的组件？

**Comment by GOWxx** [comment]
有没有什么好的移动端上的树形选择器的实现，想学习下

我这设计的树形选择器是
三部分组成
<面包屑 /> // 知道目前的层级，也可以通过点击面包屑回到某一层级
<分支节点list /> // 每一条分支节点的右侧有个 "下级” 按钮，可以进入下级
<IndexBar 序列 /> // 本层级下的叶子节点

这样功能是可以实现的，也可以展示的，但看着还是有点繁琐，第一次用会茫然

**Comment by awmleer** [comment]
#4376
