### ISSUE TITLE
DatePicker 如果没有默认值，点开会自动选择第一项而不是当前时间

### ISSUE THREAD

**Issue by chenliangngng** [ant-design/ant-design-mobile#4025]
建议默认使用当前时间，提供修改方法

**Comment by awmleer** [comment]
用 defaultValue 设置

请参考官网文档上的 demo：
https://next.mobile.ant.design/components/date-picker

**Comment by xiaohuoni** [comment]
```

const now = new Date('Mon Sep 24 2018')

function BasicDemo() {
  const [visible, setVisible] = useState(false)
  return (
    <>
      <Button
        onClick={() => {
          setVisible(true)
        }}
      >
        选择
      </Button>
      <DatePicker
        visible={visible}
        onClose={() => {
          setVisible(false)
        }}
        defaultValue={now}
        max={now}
        onConfirm={val => {
          Toast.show(val.toDateString())
        }}
      />
    </>
  )
}
```
![image](https://user-images.githubusercontent.com/11746742/134648591-28313430-95c5-4aef-8451-9a9692f66c53.png)

**Comment by chenliangngng** [comment]
> 用 defaultValue 设置
> 
> 请参考官网文档上的 demo：
> https://next.mobile.ant.design/components/date-picker

@awmleer 
设置了defaultValue会跑到下面的value上去，显示的是defaultValue的值。只要设置了defaultValue不需要点开就会显示了，这种交互不对呀
这个问题，我觉得应该组件使用了min设置的值，看代码是默认用的当前时间-10年

**Comment by awmleer** [comment]
@chenliangngng 我大概理解你的意思了，这个是 Picker 的行为，默认选中的是第一项

**Comment by chenliangngng** [comment]
> @chenliangngng 我大概理解你的意思了，这个是 Picker 的行为，默认选中的是第一项

@awmleer 如下图，设置了defaultValue在不进行任何操作的情况下，就直接通过value显示出来了
![企业微信截图_6dd195bb-7c58-4158-bb3b-9a15aa268a1c](https://user-images.githubusercontent.com/49113930/134651369-d2b661f2-4c5d-4da7-9e7a-785e10eb919a.png)

      <DatePicker
        visible={pickerVisible}
        onClose={() => {
          setPickerVisible(false);
        }}
        onClick={(e) => {
          e.stopPropagation();
        }}
        defaultValue={new Date()}
        {...restProps}
      >
        {(value) => value?.toDateString()}
      </DatePicker>

**Comment by awmleer** [comment]
@chenliangngng 嗯嗯是的，这个也是预期的行为，你是希望默认值还是 null 或者 undefined，但是用户弹出 DatePicker 的时候，是默认滑到当前日期

**Comment by awmleer** [comment]
这个 issue 我重新打开吧，目前不太好支持，后面看看有没有可能支持一下

**Comment by chenliangngng** [comment]
> @chenliangngng 嗯嗯是的，这个也是预期的行为，你是希望默认值还是 null 或者 undefined，但是用户弹出 DatePicker 的时候，是默认滑到当前日期

嗯嗯是的，3q

**Comment by wansers** [comment]
这个问题还没解决嘛，选个生日从100年前开始滚动

**Comment by GOWxx** [comment]
> 这个问题还没解决嘛，选个生日从100年前开始滚动

使用的 antd-mobile 版本是？

**Comment by awmleer** [comment]
还没解决的

**Comment by awmleer** [comment]
先标个 help wanted

**Comment by xiaohuoni** [comment]
有解法嘛？看上面记录好像是观望中....

**Comment by xiaohuoni** [comment]
有解法嘛？看上面记录好像是观望中....

**Comment by awmleer** [comment]
应该有解法，我还没顾上看

**Comment by swufexlm** [comment]
我现在暂时采用的方法，显示 picker 时，先将 min 属性更新为当前时间，然后设置 visible 属性，最后设一个 timeout 更新 min 为 undefined，效果还可以
