### ISSUE TITLE
在类组件中无法通过 ref 获取 Form 的引用

### ISSUE THREAD

**Issue by carrot7454** [ant-design/ant-design-mobile#4033]
在官网Form组件引用的rc-field-form网站中, https://www.npmjs.com/package/rc-field-form, 其中useForm部分写明
For class component user, you can use ref to get form instance:

```jsx
class Demo extends React.Component {
  setRef = form => {
    // Form instance here
  };

  render() {
    return <Form ref={this.setRef} />;
  }
}
```

当时在实际的component组件中Form上使用ref却从createRef上得不到组件实例呢，难道antd-mobile暂时不支持类组件，因为用useForm只支持函数组件

**Comment by awmleer** [comment]
这块的确应该是我们需要完善一下支持

**Comment by awmleer** [comment]
Close via #4047.
