### ISSUE TITLE
使用Picker组件级联模式的时候样式会错位

### ISSUE THREAD

**Issue by carrot7454** [ant-design/ant-design-mobile#4035]
如图所示，在Picker组件中级联菜单会样式错乱
![微信图片编辑_20210925210827](https://user-images.githubusercontent.com/47313062/134772713-e9f59acd-9e4f-40d0-84e5-128d777cac58.jpg)

**Comment by awmleer** [comment]
看起来你是用的 vw 布局？可能和这个有关

**Comment by carrot7454** [comment]
我用的是rem布局，html标签font-size是8px

**Comment by awmleer** [comment]
@carrot7454 看起来不是 rem 布局啊……你截图里样式都是 vw 的

**Comment by carrot7454** [comment]
![QQ截图20210926092646](https://user-images.githubusercontent.com/47313062/134790046-46239ea6-9158-4d06-8411-2f86379795c1.png)
我看组件自身好像也是用的vw布局

**Comment by awmleer** [comment]
adm 的样式里变成了 vw 单位是因为你自己项目配置了某些 postcss 插件做转换
