### ISSUE TITLE
请问能提供一个扫描二维码的功能吗，感激。

### ISSUE THREAD

**Issue by HiroBaby** [ant-design/ant-design-mobile#404]
#### 本地环境

- antd-mobile 版本：0.9.3
- 操作系统及其版本：mac
- 浏览器及其版本：safari

#### 你期待的结果是：

请问能提供一个扫描二维码的功能吗，感激。

**Comment by warmhug** [comment]
web 是不支持的。 react native 里可能某些场景会用到？如果有能开放的 API 倒是可以考虑。

**Comment by silentcloud** [comment]
react-native 的也是没办法做成纯 UI 组件的，需要 native 模块支持，antd-mobile 是纯 UI 组件，这类的需求可以去找一下开源库，比如 react-native-camera @HiroBaby
