### ISSUE TITLE
[v5]PullToRefresh 期望children的父级div元素加一个className

### ISSUE THREAD

**Issue by LwcReber** [ant-design/ant-design-mobile#4040]
PullToRefresh的children是一个div包裹的,导致如果children的高度100%这种方式来撑开的情况下,很难去改下他的父级div元素的高度，如果有class的情况下，则可以通过css来进行修改
![image](https://user-images.githubusercontent.com/22888671/134800190-16a73fd2-33a1-41c9-9b83-100eee9bdee1.png)
源码这里添加下
![image](https://user-images.githubusercontent.com/22888671/134800218-05925b7c-ef32-4f38-b615-be4e4386e95d.png)

**Comment by awmleer** [comment]
#4042
