### ISSUE TITLE
v5.0.0-beta.10  的Mask组件中缺少afterShow

### ISSUE THREAD

**Issue by zq12580** [ant-design/ant-design-mobile#4044]
`
import { NativeProps } from '../../utils/native-props';
import React from 'react';
export declare type MaskProps = {
    visible?: boolean;
    onMaskClick?: (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => void;
    destroyOnClose?: boolean;
    forceRender?: boolean;
    disableBodyScroll?: boolean;
    opacity?: 'default' | 'dark' | number;
    getContainer?: HTMLElement | (() => HTMLElement) | undefined;
    afterClose?: () => void;
} & NativeProps;
export declare const Mask: React.FC<MaskProps>;
`
组件代码没有暴露出来 ，但文档已显示

**Comment by awmleer** [comment]
你的 antd-mobile 的版本号是？

**Comment by awmleer** [comment]
更新一下到最新的版本试试？最近才新增的
