### ISSUE TITLE
ListView点击俩下之后才更新

### ISSUE THREAD

**Issue by guangming21** [ant-design/ant-design-mobile#406]
#### 本地环境

- antd-mobile 版本：0.8.6
- 操作系统及其版：win10
- 浏览器及其版本：谷歌

#### 你做了什么？

引入ListView组件，请求数据

#### 你期待的结果是：

![qq 20161020165134](https://cloud.githubusercontent.com/assets/18028721/19553158/9a1d6218-96e5-11e6-9eef-137756f45181.png)

#### 实际上的结果：

搜索点击俩下周后得到想要的结果
![qq 20161020165156](https://cloud.githubusercontent.com/assets/18028721/19553165/9f9ee98c-96e5-11e6-93fb-ba204ea9be37.png)
点击一下
![qq 20161020165217](https://cloud.githubusercontent.com/assets/18028721/19553166/a00a21c0-96e5-11e6-9bcd-047ed7eb35a1.png)

**Comment by warmhug** [comment]
点击哪里两下？

**Comment by guangming21** [comment]
这个可能是我代码的问题，你们能提供es6的写法吗

**Comment by warmhug** [comment]
/(ㄒoㄒ)/~~ es5 es6 这些自己学习下吧
