### ISSUE TITLE
[feature]会支持动态主题么

### ISSUE THREAD

**Issue by ratelgogo** [ant-design/ant-design-mobile#4061]
ConfigProvider 只支持国际化

**Comment by awmleer** [comment]
https://mobile.ant.design/zh/guide/theme

**Comment by awmleer** [comment]
是基于 CSS 变量实现的，不是在 ConfigProvider 中配置的

**Comment by ratelgogo** [comment]
运行时修改css 变量

**Comment by ratelgogo** [comment]
还有其他更加优雅的方式么

**Comment by awmleer** [comment]
在 CSS 文件里设置啊……上面的文档链接里有写

**Comment by ratelgogo** [comment]
> 在 CSS 文件里设置啊……上面的文档链接里有写

我们的场景是需要运行时变更，color是接口返回的，css文件里怎么设置呢？

**Comment by awmleer** [comment]
可以参考下这里～
https://mobile.ant.design/zh/guide/css-variables

**Comment by awmleer** [comment]
直接写 `style` 属性

**Comment by ratelgogo** [comment]
> 直接写 `style` 属性

所有用到的组件都要设置一遍😢

**Comment by awmleer** [comment]
你在最外层加个 `div`，然后给这个 `div` 设置 `style` 就可以了：

```jsx
function Root() {
  return (
    <div style={{...}}> // 在这里设置
      <YourApp />
    </div>
  )
}
```
