### ISSUE TITLE
Button按钮 loading状态下可触发点击事件 

### ISSUE THREAD

**Issue by zjp1300** [ant-design/ant-design-mobile#4062]
不清楚是不是bug，参照了element和vant，loading状态下是不可点击的， mobile.ant就是这么设计的吗

**Comment by awmleer** [comment]
是预期行为的，需要自己同时设置 disabled

**Comment by zjp1300** [comment]
> 是预期行为的，需要自己同时设置 disabled

了解 个人感觉loading状态可触发点击事件  感觉不符合常理吧

**Comment by awmleer** [comment]
嗯嗯这个我们再考虑一下

**Comment by awmleer** [comment]
Fixed via b689dfd7d
