### ISSUE TITLE
[RFC] SideBar 侧边导航

### ISSUE THREAD

**Issue by p697** [ant-design/ant-design-mobile#4063]
# SideBar 侧边导航

### SideBar

| 属性             | 说明                                             | 类型                    | 默认值             |
| ---------------- | ------------------------------------------------ | ----------------------- | ------------------ |
| activeKey        | 当前激活 `item` 的 `key`                           | `string \| null`        | -                  |
| defaultActiveKey | 初始化选中 `item` 的 `key`，如果没有设置 `activeKey`  | `string \| null`       | 第一个 `item` 的 `key` |
| onChange         | 切换面板的回调                                   | `(key: string) => void`   | -                  |

### SideBar.Item

| 属性        | 说明                        | 类型        | 默认值  |
| ----------- | --------------------------- | ----------- | ------- |
| key         | 对应 `activeKey`            | `string`    | -       |
| title       | 显示内容                    | `ReactNode` | -       |
| disabled    | 是否禁用                    | `boolean`   | `false` |
| badge       | 徽标                       | `ReactNode` | -      |

## CSS 变量

| 属性            | 说明         | 默认值 |
| --------------- | ------------ | ------ |
| --width        | 侧边导航宽度   | `80px` |

**Comment by awmleer** [comment]
侧边导航的高度是多少嘞？默认占满高度么？
要不加个 `--height` CSS 变量，默认是 `100%`

**Comment by awmleer** [comment]
其他没啥问题～

**Comment by p697** [comment]
> 侧边导航的高度是多少嘞？默认占满高度么？
> 要不加个 `--height` CSS 变量，默认是 `100%`

嗯嗯呐~
