### ISSUE TITLE
Error: Cannot find module 'antd-mobile/lib/dialog'

### ISSUE THREAD

**Issue by Gchangjian** [ant-design/ant-design-mobile#4064]
![image](https://user-images.githubusercontent.com/17879551/135060238-9cc0e2e6-116d-4ace-b2a1-ff5cc70f14c8.png)

dev的时候没有问题，但是build之后 再跑起来的时候就有问题

**Comment by awmleer** [comment]
https://mobile.ant.design/zh/guide/faq#umi-%E9%A1%B9%E7%9B%AE%E5%AE%89%E8%A3%85-antd-mobile-v5-%E5%90%8E%E6%8A%A5%E9%94%99%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F

**Comment by Gchangjian** [comment]
> https://mobile.ant.design/zh/guide/faq#umi-%E9%A1%B9%E7%9B%AE%E5%AE%89%E8%A3%85-antd-mobile-v5-%E5%90%8E%E6%8A%A5%E9%94%99%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F

config.js指的是什么？webpck的config还是哪里的config？项目里没有类似这种的文件

**Comment by Mark24Code** [comment]
Node Modules里面压根没打包进去。

真是活久见

**Comment by awmleer** [comment]
@Gchangjian 你是自己配置的 webpack 么？是不是装了 babel-plugin-mobile？

**Comment by awmleer** [comment]
这个报错大概率是错误的配置了 babel-plugin-import 导致的，如果可以的话，发一下 webpack 配置文件和 babel 的配置文件？

**Comment by Gchangjian** [comment]
> 这个报错大概率是错误的配置了 babel-plugin-import 导致的，如果可以的话，发一下 webpack 配置文件和 babel 的配置文件？

// common modules
const path = require('path')
const webpack = require('webpack')
const { resolveApp } = require('@ke/anubis/utils')

// webpack plugins
const ManifestPlugin = require('webpack-manifest-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const ModuleNotFoundPlugin = require('react-dev-utils/ModuleNotFoundPlugin')
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin')
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin')
const WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeModulesPlugin')
const ReactLoadablePlugin = require('react-loadable/webpack').ReactLoadablePlugin

// default configs
const NODE_ENV = process.env.NODE_ENV
const shouldUseSourceMap = process.env.GENERATE_SOURCEMAP !== 'false'
const isWATCH = process.env.WATCH === 'true'
const isEnvDevelopment = NODE_ENV === 'development'
const isEnvProduction = NODE_ENV === 'production' || NODE_ENV === 'testing' || NODE_ENV === 'preview'
const appNodeModules = resolveApp('node_modules')
const htmlIndex = resolveApp('./src/client/public/index.html')
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')

// style files regexes
const cssRegex = /\.css$/
const cssModuleRegex = /\.d\.css$/
const sassRegex = /\.(scss|sass)$/
const sassModuleRegex = /\.d\.(scss|sass)$/

const getWebpackSetting = customerConfig => {
  const { staticConfig, devPublicPath, outputClientDir, styleLoaders, propRules, propPlugins, staticPort, customerAlias } = customerConfig

  // tsconfig path
  const tsconfig = resolveApp(customerConfig.tsconfigName)
  const devAbsolutePublicPath = resolveApp(devPublicPath)

  // core functions
  const getStyleLoaders = (cssOptions, preProcessor) => {
    const loaders = [
      isEnvProduction && {
        loader: MiniCssExtractPlugin.loader
      },
      isEnvDevelopment && {
        loader: MiniCssExtractPlugin.loader,
        options: {
          publicPath: `/${devPublicPath}`,
          hmr: NODE_ENV === 'development'
        }
      },
      {
        loader: require.resolve('css-loader'),
        options: cssOptions
      }
    ]
      .concat(styleLoaders)
      .filter(Boolean)

    if (preProcessor) {
      loaders.push({
        loader: require.resolve(preProcessor),
        options: {
          sourceMap: isEnvProduction && shouldUseSourceMap
        }
      })
    }
    return loaders
  }
  // webpack core setting
  const setting = {
    mode: isEnvProduction ? 'production' : isEnvDevelopment && 'development',
    entry: resolveApp('./src/client/entry.tsx'),
    output: {
      path: isEnvDevelopment ? devAbsolutePublicPath : path.resolve(devAbsolutePublicPath, outputClientDir),
      publicPath: staticConfig[NODE_ENV],
      filename: isEnvProduction ? 'client/js/[name].[contenthash:8].js' : isEnvDevelopment && 'client/js/[name].js',
      chunkFilename: isEnvProduction ? 'client/js/[name].[contenthash:8].chunk.js' : isEnvDevelopment && 'client/js/[name].chunk.js'
    },
    module: {
      rules: [
        {
          test: /\.(tsx|ts)?$/,
          use: {
            loader: 'ts-loader',
            options: {
              configFile: tsconfig
            }
          }
        },
        {
          test: /\.js$/,
          exclude: [/node_modules/],
          use: {
            loader: 'babel-loader'
          }
        },
        {
          test: cssRegex,
          exclude: cssModuleRegex,
          use: getStyleLoaders({
            importLoaders: 1,
            sourceMap: isEnvProduction && shouldUseSourceMap
          }),
          sideEffects: true
        },
        {
          test: cssModuleRegex,
          use: getStyleLoaders({
            importLoaders: 1,
            sourceMap: isEnvProduction && shouldUseSourceMap,
            modules: true
          })
        },
        {
          test: sassRegex,
          exclude: sassModuleRegex,
          use: getStyleLoaders(
            {
              importLoaders: 2,
              sourceMap: isEnvProduction && shouldUseSourceMap
            },
            'sass-loader'
          ),
          sideEffects: true
        },
        {
          test: sassModuleRegex,
          use: getStyleLoaders(
            {
              importLoaders: 2,
              sourceMap: isEnvProduction && shouldUseSourceMap,
              modules: true
            },
            'sass-loader'
          )
        },
        {
          loader: require.resolve('file-loader'),
          exclude: [/\.(js|mjs|jsx|ts|tsx|css|scss)$/, /\.html$/, /\.json$/],
          options: {
            name: 'client/media/[path][name].[hash:8].[ext]'
          }
        }
      ]
        .concat(propRules)
        .filter(Boolean)
    },
    watch: isWATCH,
    devtool: isEnvProduction ? (shouldUseSourceMap ? 'source-map' : false) : isEnvDevelopment && 'cheap-module-source-map',
    optimization: {
      minimize: isEnvProduction,
      minimizer: [new OptimizeCSSAssetsPlugin({}), new UglifyJsPlugin()],
      splitChunks: {
        cacheGroups: {
          default: false,
          vendors: false,
          vendor: {
            // name of the chunk
            name: 'vendor',
            // async + async chunks
            chunks: 'all',
            // import file path containing node_modules
            test: /node_modules/,
            // priority
            priority: 20
          }
        }
      }
    },
    plugins: [
      new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify(NODE_ENV)
      }),
      // Generates an `index.html` file with the <script> injected.
      new HtmlWebpackPlugin(
        Object.assign(
          {},
          {
            inject: true,
            template: htmlIndex
          },
          isEnvProduction
            ? {
                minify: {
                  removeComments: true,
                  collapseWhitespace: true,
                  removeRedundantAttributes: true,
                  useShortDoctype: true,
                  removeEmptyAttributes: true,
                  removeStyleLinkTypeAttributes: true,
                  keepClosingSlash: true,
                  minifyJS: true,
                  minifyCSS: true,
                  minifyURLs: true
                }
              }
            : undefined
        )
      ),
      new ModuleNotFoundPlugin('./'),
      isEnvDevelopment && new webpack.HotModuleReplacementPlugin(),
      isEnvDevelopment && new CaseSensitivePathsPlugin(),
      isEnvDevelopment && new WatchMissingNodeModulesPlugin(appNodeModules),
      new MiniCssExtractPlugin({
        filename: isEnvProduction ? 'client/css/[name].[contenthash:8].css' : isEnvDevelopment && 'client/css/[name].css',

        chunkFilename: isEnvProduction ? 'client/css/[name].[contenthash:8].chunk.css' : isEnvDevelopment && 'client/css/[name].chunk.css'
      }),
      new ManifestPlugin({
        fileName: 'asset-manifest.json',
        publicPath: isEnvDevelopment ? `${devAbsolutePublicPath}/` : staticConfig[NODE_ENV],
        generate: (seed, files) => {
          const manifestFiles = files.reduce(function(manifest, file) {
            manifest[file.name] = file.path
            return manifest
          }, seed)

          return {
            files: manifestFiles
          }
        }
      }),
      new ReactLoadablePlugin({
        filename: isEnvDevelopment
          ? path.resolve(devAbsolutePublicPath, 'react-loadable.json')
          : path.resolve(devAbsolutePublicPath, outputClientDir, 'react-loadable.json')
      })
    ]
      .concat(propPlugins)
      .filter(Boolean),
    resolve: {
      extensions: ['.tsx', '.ts', '.jsx', '.js', '.json'],
      alias: customerAlias
    }
  }

  isEnvDevelopment &&
    !isWATCH &&
    (setting.devServer = {
      host: '0.0.0.0',
      contentBase: devAbsolutePublicPath,
      hot: true,
      publicPath: `/${devPublicPath}/`,
      compress: true,
      disableHostCheck: true,
      clientLogLevel: 'none',
      quiet: true,
      port: staticPort,
      index: htmlIndex,
      inline: true,
      headers: {
        'Access-Control-Allow-Origin': '*'
      }
    })
  return setting
}
module.exports = getWebpackSetting

不支持服务端渲染？

**Comment by awmleer** [comment]
@Gchangjian babel 的配置文件也发一下？

**Comment by Gchangjian** [comment]
> @Gchangjian babel 的配置文件也发一下？

{
  "presets": [
    [
      "@babel/typescript",
      {
        "isTSX": true,
        "allExtensions": true
      }
    ],
    [
      "@babel/env",
      {
        "targets": {
          "node": "current"
        },
        "loose": true
      }
    ],
    "@babel/react"
  ],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd-mobile",
        "libraryDirectory": "lib"
      },
      "antd-mobile"
    ],
    [
      "babel-plugin-transform-require-ignore",
      {
        "extensions": [".less", ".css", ".scss"]
      }
    ],
    [
      "module-resolver",
      {
        "root": ["./src"],
        "alias": {
          "components": ["./src/client/components"],
          "pages": ["./src/client/pages"],
          "styles": ["./src/client/statics/styles"],
          "utils": ["./src/client/statics/utils"],
          "client": ["./src/client"]
        }
      }
    ],
    "react-loadable/babel",
    "module:@ke/transform-media-imports"
  ]
}

**Comment by awmleer** [comment]
你自己错误地配置了 `babel-plugin-import` 啊……把这几行删掉：

```
    [
      "import",
      {
        "libraryName": "antd-mobile",
        "libraryDirectory": "lib"
      },
      "antd-mobile"
    ],
```
