### ISSUE TITLE
有木有让div超出宽度横向可以拖动的插件

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design-mobile#407]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

**Comment by warmhug** [comment]
可以尝试下这个 https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L62 和 iscroll 类似

**Comment by SynChron1zed** [comment]
@warmhug 你发我的这个json
