### ISSUE TITLE
打包忘记了 Dialog组件  Module not found: Can't resolve 'antd-mobile/lib/dialog' 

### ISSUE THREAD

**Issue by Mark24Code** [ant-design/ant-design-mobile#4075]
你们打包忘记了 Dialog组件  Module not found: Can't resolve 'antd-mobile/lib/dialog' 
![截屏2021-09-29 下午3 41 33](https://user-images.githubusercontent.com/7592004/135224554-287fbc39-741e-4acf-936a-4fda4f4105ab.png)

![截屏2021-09-29 下午3 41 53](https://user-images.githubusercontent.com/7592004/135224599-6e35c948-d590-4f7b-bc35-52d7abaacab3.png)

**Comment by awmleer** [comment]
@Mark24Code 可以发一下你安装的 antd-mobile 的版本号么？在 node_modules/antd-mobile/package.json 中

**Comment by awmleer** [comment]
看你发的截图，应该是 v2 的

**Comment by Mark24Code** [comment]
"antd-mobile": "^2.3.4",  @awmleer

**Comment by zzzgydi** [comment]
v2是没有Dialog吧，有个Modal

**Comment by Mark24Code** [comment]
原来是这样。我用v5好了。
