### ISSUE TITLE
v5 Input maxLength 属性 不生效

### ISSUE THREAD

**Issue by ayyslz** [ant-design/ant-design-mobile#4076]
版本：
"antd-mobile": "^5.0.0-beta.13",
"react": "^17.0.1",

使用位置：Form.Item 中 使用 Input

代码：
 ```
              <Form.Item
                      name="newPass"
                      label="密码："
                      rules={[
                          {
                              required: true,
                              message: '密码不正确',
                              validator: numberPasswordValidator,
                          },
                      ]}>
                      <Input
                          type="number"
                          maxLength={6}
                          clearable
                          placeholder="请输入6位纯数字，作为登录密码"
                      />
             </Form.Item>
```
                  
 maxLength 没有达成预期的结果

**Comment by jermyn626** [comment]
@ayyslz 在原生 input 中，maxLength 只在 type 为 text, email, search, password, tel, url 时生效。
[input#attr-maxlength - MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength)

**Comment by awmleer** [comment]
感谢 @jermyn626 

补充一下～对于 `number` 类型的 Input，可以通过设置 `max` 和 `min` 来达到限制的效果：
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-max

**Comment by awmleer** [comment]
噢我们现在 Input 还没支持，我来加一下

**Comment by awmleer** [comment]
Close via a16fdab47.
