### ISSUE TITLE
taro里面使用imageUploader组件报错

### ISSUE THREAD

**Issue by lzzhanglin** [ant-design/ant-design-mobile#4077]
![image](https://user-images.githubusercontent.com/21311138/135241510-585127f2-6146-4f93-b981-070f908c3cdb.png)
本来我以为是taro不支持async await的问题，后面排除掉是taro的问题
![image](https://user-images.githubusercontent.com/21311138/135241950-6cbbb5ca-a100-44aa-b4ad-b252fce0e5e0.png)
代码wan'q完全按照示例写的

**Comment by awmleer** [comment]
目前我们没有对 taro 环境做过兼容性验证，也不确定所有组件都在 taro 环境下表现正常，短期内我们精力有限，没有办法提供对 taro 环境的支持

可以尝试在 codesandbox 中复现一下，如果能排除是 taro 的问题，我们会尽快修复

**Comment by lzzhanglin** [comment]
我在codesandbox试了一下，在纯react版本下没问题，那应该还是taro的问题，抱歉

**Comment by lzzhanglin** [comment]
我来填个坑，taro 里面使用这个组件需要yarn add @tarojs/async-await,然后再在入口文件import '@tarojs/async-await' 即可
