### ISSUE TITLE
Drawer抽屉组件基本例子官网正常本地不正常，求更正，另外证明官网环境与本地确实有差异，不能用官网正常来成为功能正常的衡量指标

### ISSUE THREAD

**Issue by miss61008596** [ant-design/ant-design-mobile#408]
本地环境

antd-mobile 版本："0.8.x"
操作系统及其版本：OSX 10.11.6
浏览器及其版本：Google Chrome 51.0.2704.63 (64-bit)
你做了什么？

Drawer 抽屉组件

你期待的结果是：

Drawer 抽屉组件正常

实际上的结果：

本地不正常，官网正常，
Drawer  抽屉组件按钮被一个div遮住
给其增加style="margin-top:42px"后，可以正常使用，

可重现的在线演示

![image](https://cloud.githubusercontent.com/assets/6361237/19570962/b806b81c-972e-11e6-937f-79850d5694ec.png)

给其增加style="margin-top:42px"后，可以正常使用，

![image](https://cloud.githubusercontent.com/assets/6361237/19571088/4e39a5d8-972f-11e6-9b73-ad0d9f12231e.png)

等有空了我也查下源码，55555
另外证明官网环境与本地确实有差异，不能总是用官网正常来成为功能正常的衡量指标！

**Comment by miss61008596** [comment]
<div style={{height:42,position:'relative',zIndex:1}}>
                <NavBar iconName="ellipsis" onLeftClick={this.onOpenChange}>
                    基本
                </NavBar>
            </div>
我暂时这么搞的。。。源码没看懂

**Comment by warmhug** [comment]
![image](https://cloud.githubusercontent.com/assets/2011119/19586770/3d56002a-978b-11e6-8a7c-0159df8afbd4.png)

 position: absolute 元素一般都需要有 relative 的父元素包裹，注意 css 设置，这个问题本就该业务来自己设置解决的。

**Comment by miss61008596** [comment]
好的，回头我再研究下，我觉得官网的Demo需要改改，毕竟不能正常运行，毕竟很多我这样的菜鸟在看好和使用这款框架，源码易懂一些，Demo可以正常运行，利于框架降低门槛，😂

**Comment by warmhug** [comment]
多谢建议
