### ISSUE TITLE
Modal中alert和prompt的ios兼容问题

### ISSUE THREAD

**Issue by bywwcnll** [ant-design/ant-design-mobile#409]
[antdMobileModal.zip](https://github.com/ant-design/ant-design-mobile/files/543360/antdMobileModal.zip)

#### 本地环境

- antd-mobile 版本：0.9.3
- 操作系统及其版本：win10专业版
- 浏览器及其版本：Chrome 版本 53.0.2785.143 m，Safari 5+

#### 你做了什么？

> 使用Modal组件的alert或prompt

    import { Button, Modal } from 'antd-mobile'
    const alert = Modal.alert;
    render(
        <div>
            <Button onClick={ ()=>{
                alert('删除', '确定删除么???', [
                    { text: '取消', onPress: () => console.log('cancel') },
                    { text: '确定', onPress: () => console.log('ok') },
                ]);
           } }>点我</Button>
        </div>,
        document.querySelector("#app")
    );    

#### 你期待的结果是：

> Chrome中的IPhone模拟界面（或Safari浏览器中）和Android或pc界面中一样可以点击Modal.alert中的取消或确定按钮

#### 实际上的结果：

> Chrome中的IPhone模拟界面（或Safari浏览器中）不能点击Modal.alert中的取消或确定按钮来隐藏对话框

#### 可重现的在线演示

https://codepen.io/w2233540467/pen/vXvKQN

**Comment by silentcloud** [comment]
![test](https://cloud.githubusercontent.com/assets/1698185/19584294/09950f3e-9776-11e6-8394-93714092b9be.gif)

**Comment by silentcloud** [comment]
有可能和 issue 415 是一个情况，目前已经提交修复

**Comment by pfdgithub** [comment]
遇到有同样的问题，点击按钮无法关闭弹窗，且控制台报错。什么时候能修复发布？
`warning.js:36 Warning: Unknown prop `activeStyle` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in a (created by FooterButton)
    in FooterButton (created by TouchableFeedbackComponent)
    in TouchableFeedbackComponent (created by Modal)
    in div (created by Modal)
    in div (created by Dialog)
    in div (created by Dialog)
    in div (created by LazyRenderBox)
    in LazyRenderBox (created by Dialog)
    in AnimateChild (created by Animate)
    in Animate (created by Dialog)
    in div (created by Dialog)
    in div (created by Dialog)
    in Dialog`

**Comment by afc163** [comment]
@pfdgithub +1

**Comment by silentcloud** [comment]
0.9.5

**Comment by motorguo** [comment]
有个小小的建议：
建议给 `Modal.alert()` 添加个选项 `maskClosable` , `弹出多个按钮` 不像其它的 都有个取消按钮，可关闭。
` 弹出多个按钮` 这个成必选了。
感谢
