### ISSUE TITLE
关于样式的一些问题

### ISSUE THREAD

**Issue by DaDanLiu** [ant-design/ant-design-mobile#4090]
# antd-mobile ^2.3.4
![飞书20211001-082313](https://user-images.githubusercontent.com/78400194/135547638-4832efd4-3fdf-4d48-93a6-c844eea72d37.png)
 想问下这些媒体查询的@media 下挂的样式，怎么直接干掉，或者一口气覆盖掉，伪类的样式会和其他元素的border重合，导致跟ui要的表现不一致

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
