### ISSUE TITLE
mobile demo 切换改变 router

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#41]
![](https://zos.alipayobjects.com/rmsportal/sesuoaEIFfdegkL.png) 
现在 点击下边的按钮，url 不会更新，需要更新掉，不然刷新页面就又回到了切换前的页面。

**Comment by liqi07** [comment]
1.0中网站会优化navbar处理，这块交互会用其他方式代替，目前就不特别做修改了。
调试某一特定demo的时候直接在url加md文件名吧，如http://127.0.0.1:8001/kitchen-sink/badge/dot

**Comment by liqi07** [comment]
1.0 中展示做优化，这个先close了
