### ISSUE TITLE
expo 项目 导入antd moblie 直接报错

### ISSUE THREAD

**Issue by sangyuren** [ant-design/ant-design-mobile#4113]
![image](https://user-images.githubusercontent.com/53714134/136399330-d79a7253-0b8c-4c96-8c93-12857dc25eca.png)

**Comment by awmleer** [comment]
antd-mobile 不支持 react-native
如果是 antd-mobile-rn 相关的问题，请移步：https://github.com/ant-design/ant-design-mobile-rn/issues
