### ISSUE TITLE
期望dropdown组件，点击每个drop-item的下拉内容可以关闭组件，给与事件回调

### ISSUE THREAD

**Issue by xiaobaohui** [ant-design/ant-design-mobile#4114]

**Comment by ahui4367** [comment]
强烈期望添加drop-item 关闭功能，

**Comment by jermyn626** [comment]
可以外部控制 Dropdown 的 `activeKey` 值实现
```tsx
const exmaple = () => {
  const [activeKey, setActiveKey] = useState<string | undefined>()
  const hideDropdownItem = () => {
    setActiveKey(undefined)
  }
  return (
    <Dropdown
      activeKey={activeKey}
      onChange={key => {
        setActiveKey(key)
      }}
    >
      <Dropdown.Item key='sorter' title='排序'>
        <div
          onClick={() => {
            hideDropdownItem()
          }}
        >
          排序
        </div>
      </Dropdown.Item>
      <Dropdown.Item key='bizop' title='商机筛选'></Dropdown.Item>
    </Dropdown>
  )
}
```

**Comment by awmleer** [comment]
如果直接给 Dropdown.Item 增加一个 `onContentClick` 属性，可以解决这个 issue 提到的问题么？

**Comment by awmleer** [comment]
@jermyn626 get～那你的思路会更好一些，不过命名上需要小调整一下，叫做 `closeOnContentClick` 吧，更严谨一些

> ### Dropdown.Item 添加属性
> 属性	说明	类型	默认值
> closeOnClick	是否点击下拉内容后关闭，传函数表示点击关闭后的回调	`boolean` | `(key: string) => void`	`false`

**Comment by jermyn626** [comment]
@awmleer  ok～

**Comment by sunjianfengHub** [comment]
同理期望dropdown组件能增加@xiaobaohui 所说的功能

**Comment by jermyn626** [comment]
@sunjianfengHub 现在 `Dropdown.Item` 已支持 `closeOnContentClick` 属性了～
![image](https://user-images.githubusercontent.com/18393754/141601963-ca3efc9c-64e6-4127-91d7-689308200953.png)

**Comment by awmleer** [comment]
感谢 @jermyn626
