### ISSUE TITLE
Radio 和 Checkbox 的图标样式问题

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#4118]
同时还可以暴露出一些 CSS 变量支持配置大小

**Comment by zqran** [comment]
看了下 Radio 和 Checkbox 组件，如果要配置大小的话，可能有以下内容需要配置：
分为 3 种情况：
1. 默认图标
2. Checkbox 的 indeterminate 效果
3. 自定义图标

其中，默认图标，需要修改以下内容：
1.  小圆圈的大小【对应：width和height 22px】
2.  小圆圈选中时内部 icon 的大小【对应：font-size 12px】
3. 文字大小【17px】

Checkbox 的 indeterminate 效果，需要修改以下内容（类似于 默认图标 的情况）：
1.  小圆圈的大小【对应：width和height 22px】
2.  小圆圈半选时，内部实心圆的大小【对应：width和height 12px】
3. 文字大小【17px】

自定义图标，需要修改以下内容：
1. 自定义 icon 时的大小【font-size 22px】
2. 文字大小【17px】

通过以上情况的分析，共有 3 个大小配置：

```css
`--icon-size: 22px`           /* 对应图标外圈或自定义 icon 的大小 */
`--icon-inner-size: 12px` /* 对应图标内圈的大小 */
`--font-size: 17px`           /* 对应文字的大小 */
```

**Comment by zqran** [comment]
> 应该可以统一成两个变量 `--circle-size` 和 `--icon-size`，intermediate 状态的内圈大小应该是可以复用 `--icon-size` 的，我来搞这个吧，有点蛋疼

好的

**Comment by awmleer** [comment]
02a339c01
