### ISSUE TITLE
使用5.0.0-beta.14版本页面报错

### ISSUE THREAD

**Issue by jianxingcyj** [ant-design/ant-design-mobile#4119]
项目中引用 import {Popup} from 'antd-mobile'，报错：merge-locale.js:3 Uncaught TypeError: Cannot read properties of undefined (reading 'merge')

**Comment by awmleer** [comment]
重新装一下 node_modules 试试？看起来是没有找到 lodash 的问题

**Comment by awmleer** [comment]
报错原文可以尽可能详细的贴一下么？
你项目的具体环境是？
是否使用了脚手架？如果使用了，使用的是什么，配置文件是什么样的；如果没有使用，webpack 配置是什么样的？
