### ISSUE TITLE
安装了ant-design-mobile时出现红色错误，会有什么影响吗？

### ISSUE THREAD

**Issue by xubuhang** [ant-design/ant-design-mobile#412]
安装ant-design-mobileb时出现了一些错误，不知道对我接下来的开发有没有影响？
<img width="570" alt="qq20161021-0 2x" src="https://cloud.githubusercontent.com/assets/4189632/19594983/501be6d2-97ba-11e6-9ddd-4f00fe35f5f1.png">
<img width="570" alt="qq20161021-1 2x" src="https://cloud.githubusercontent.com/assets/4189632/19595005/69f68c2e-97ba-11e6-8bc2-85e4abff6a7f.png">
<img width="566" alt="qq20161021-2 2x" src="https://cloud.githubusercontent.com/assets/4189632/19595011/75998c52-97ba-11e6-8487-ad4443bb1404.png">

**Comment by silentcloud** [comment]
这是 npm3 peerDependecy 的提示，装了 react 和 react-dom 的话应该没问题
