### ISSUE TITLE
Image组件的placeholder问题

### ISSUE THREAD

**Issue by wode0weiyi** [ant-design/ant-design-mobile#4124]
Image标签的placeholder属性，能不能和Taro-Ui类似，传入的是图片地址，而不是一个node，而且现在传入node，样式还要自己再写一遍，placeholder是否能和fallback合并为一个参数，组件内部进行判断和显隐

**Comment by awmleer** [comment]
1. `placeholder` 和 `fallback` 逻辑是不一样的，前者是在图片加载的时候展示一个占位，后者是图片加载失败的时候展示一个兜底的提示，所以不能合并为一个参数
2. `placeholder` 和 `fallback` 组件本身都提供了默认的，如果你希望自定义，那自然要自己对样式负责
