### ISSUE TITLE
MobileDemo中的DatePicker在android下卡出翔了

### ISSUE THREAD

**Issue by gzbifang** [ant-design/ant-design-mobile#413]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：mac
- 浏览器及其版本：
#### 实际上的结果：

MobileDemo中的DatePicker在android下卡出翔了,这是为什么？ios非常流程

**Comment by warmhug** [comment]
你那里是所有 Android 都卡，还是低端 Android 卡？为什么我的不到一千块的华为 Android 机很流畅呢。。

**Comment by cheft** [comment]
卡，坚果 Pro 中端机很卡，我用的是 React-Native 版
