### ISSUE TITLE
Input 组件　AutoComplete　失效

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#4130]
![image](https://user-images.githubusercontent.com/12706830/136643416-5faef6a3-ddaa-4863-b17e-42f4ae1554d9.png)
![image](https://user-images.githubusercontent.com/12706830/136643432-7922d324-4bf6-468e-b9ec-0bbaf3faa765.png)
![image](https://user-images.githubusercontent.com/12706830/136643446-6aa60ef4-3046-4ae8-8c9d-2aead9088c5c.png)

**Comment by awmleer** [comment]
<img width="113" alt="image" src="https://user-images.githubusercontent.com/16526078/136648095-de293df1-f32a-462a-82ae-dd68b112162b.png">

这里是 `autoCapitalize` 啊

**Comment by codedart2018** [comment]
我瞎了
