### ISSUE TITLE
webpack5.x打包产物多了几张svg图片

### ISSUE THREAD

**Issue by yaogengzhu** [ant-design/ant-design-mobile#4147]
项目代码实际没有用到相关组件
```json
"webpack": "^5.44.0",
"antd-mobile": "^5.0.0-beta.6",

```
![image](https://user-images.githubusercontent.com/42566669/136727369-9a17e9a0-6f7a-4c4f-a1b5-ef2849337afd.png)

**Comment by yaogengzhu** [comment]
> @yaogengzhu 你是不是用到了 ErrorBlock 组件

没有用到这个组件！

**Comment by yaogengzhu** [comment]
> 那可不可以发一下你项目中引入了哪些组件？

import { TabBar } from 'antd-mobile';
import { AppOutline, MessageOutline, UnorderedListOutline, UserOutline } from 'antd-mobile-icons';

目前就用到这个

**Comment by jermyn626** [comment]
你试下手动按需加载，再看打包结果
```js
import TabBar from 'antd-mobile/es/components/tab-bar'
```

**Comment by yaogengzhu** [comment]
> 你试下手动按需加载，再看打包结果
> 
> ```js
> import TabBar from 'antd-mobile/es/components/tab-bar'
> ```

按你这个方式试了，也是不行。不过我改了下webpack配置可以了！
```js
{
        test: /\.(ico|png|jpe?g|gif|svg)$/,
        type: 'asset/resource',
        generator: {
          filename: 'image/[hash:4].[name][ext]',
        },
        // use: [
        //   {
        //     loader: 'file-loader', // 路径返回
        //     options: {
        //       name: '[name].[ext]',
        //       outputPath: './image',
        //       limit: 1024 * 10,
        //     },
        //   },
        // ],
},

```
