### ISSUE TITLE
【Question】Will there be css conflicts when using two versions of the antd-mobile in a project? 

### ISSUE THREAD

**Issue by freshlymadebread** [ant-design/ant-design-mobile#4148]
At the beginning i use antd-mobile2.3.1, but there are some problems when i use SwipeAction Component. So i add 5.0.0beta1.4, and use SwipeAction of 5.0.0.  Now it looks good. But I am not sure if there is a css conflact problem！
so help help me ! help help me ! help help me !

**Comment by freshlymadebread** [comment]
一开始项目里用的是antd-mobile2.3.1，但是在使用SwipeAction组件的时候出现了一些问题。 所以我添加了 5.0.0beta1.4，并使用了 5.0.0 的 SwipeAction。 运行起来没啥问题。 但是不知道会不会有css冲突问题！
救救我！ 救救我！ 救救我！

**Comment by awmleer** [comment]
组件级别的样式冲突时不会有的，v2 和 v5 使用的是不同的 css 类名前缀，但是全局性的样式（比如说整个页面的默认字体大小）可能会出现冲突覆盖的情况，目前很多项目都在两个版本混合使用，没有遇到过样式冲突的 bug
