### ISSUE TITLE
Picker选择器在移动端自动适配方案下会错乱

### ISSUE THREAD

**Issue by cuiyueshuai** [ant-design/ant-design-mobile#4149]
当使用移动端flexible和rem的方案做屏幕大小适配的时候，有对html的dpr也进行对应高清设置1，2，3，并在webpack中配置px到rem的自动转换的时候，包含了nodemodules内容，即包含了对antd-mobile也进行自动转换的时候，picker弹出后会发生内容和高度错乱，整个无法使用，

![image](https://user-images.githubusercontent.com/13741688/136748490-943e582f-d178-4b52-a9a8-928ffcc49b90.png)

但是当我去除对antd-mobile进行自动转换的时候，虽然内容正常了，但是无法在进行移动端各屏幕适配了

![image](https://user-images.githubusercontent.com/13741688/136748055-1d3c2965-fa97-4860-8a60-405e5d7ae0de.png)

其中，关于px到rem的插件使用配置如下：

```
 require('postcss-plugin-px2rem')({
                  rootValue: 23.4375, // 换算基数， 默认100  ，这样的话把根标签的字体规定为1rem为50px,这样就可以从设计稿上量出多少个px直接在代码中写多上px了。
                  propBlackList: [], // 黑名单
                  exclude: false, // 默认false，可以（reg）利用正则表达式排除某些文件夹的方法，例如/(node_module)/ 。如果想把前端UI框架内的px也转换成rem，请把此属性设为默认值
                  mediaQuery: false, // （布尔值）允许在媒体查询中转换px。
                  minPixelValue: 2, // 设置要替换的最小像素值(3px会被转rem)。 默认 0
                }),
```

所以我应该去改动picker的相关高度计算方式吗？，还是如何解决这个问题

**Comment by awmleer** [comment]
目前这个 `convertPx` 的逻辑已经是尽可能通用了

> 可以通过当前视窗viewmeta的宽度和实际的屏幕宽度来计算这个值吗？

具体是怎么实现嘞？愿闻其详

**Comment by mushan0x0** [comment]
@awmleer 这个问题不解决一下吗就关掉了
