### ISSUE TITLE
textarea V5 没有保留V2 版本的showCount 样式

### ISSUE THREAD

**Issue by amyhuangxbd** [ant-design/ant-design-mobile#4154]
v2的am-textarea-count DOM结构中count是用<span>包的，可以根据UI自定义样式。
v5的adm-text-area-count没有保留DOM结构，
例子中DOM：<div class="adm-text-area-count">13/30</div>
无法自定义13数字样式

**Comment by awmleer** [comment]
@jermyn626 可以的～PR welcome
