### ISSUE TITLE
web环境下的单元测试不会加载web版本的组件，而是加载RN版本

### ISSUE THREAD

**Issue by mhcgrq** [ant-design/ant-design-mobile#417]
#### 本地环境

- antd-mobile 版本：0.9.3
- 操作系统及其版本：macOS 10.12.1
- 浏览器及其版本：Chrome v56 Node v6.7.0
#### 你做了什么？

component.jsx

```
  import React, { PropTypes } from 'react';
  import { Button } from 'antd-mobile';

  export default function MyComponent(){
    return (
        <Button />
    );
  }
```

component.spec.js

```
import React from 'react';
import { shallow } from 'enzyme';

import MyComponent from './component';

describe('<MyComponent />', () => {
    it('render <MyComponent />', () => {
        const wrapper = shallow(<MyComponent />);
        expect(wrapper)...;
    });
});
```

.babelrc

```
"test": {
            "presets": ["es2015-ie", "react", "stage-0", "stage-3"],
            "plugins": [
                "add-module-exports",
                "babel-plugin-transform-decorators-legacy",
                "transform-class-properties",
                ["transform-runtime", {
                    "polyfill": false,
                    "regenerator": true
                }],
                ["import", [
                    {"libraryName": "antd"},
                    {"libraryName": "antd-mobile"}
                ]]
            ]
        }
```
#### 你期待的结果是：

测试环境下也可以指定加载正确的文件
#### 实际上的结果：

web环境下无法进行单元测试，在webpack中可以通过配置`extensions: ['', '.web.js', '.js', '.jsx']`来指定加载web版本的组件，但是跑单元测试的时候根本不会走webpack，所以还是加载了RN版本的组件，会报错：

```
● Test suite failed to run

    ReferenceError: __DEV__ is not defined

      at Object.<anonymous> (node_modules/react-native/Libraries/react-native/react-native.js:15:5)
      at Object.<anonymous> (node_modules/antd-mobile/lib/tag/index.js:24:20)
```

**Comment by warmhug** [comment]
extensions 要确认是配在测试 config 里

**Comment by mhcgrq** [comment]
还是不行，按照jest的文档https://facebook.github.io/jest/docs/configuration.html#modulefileextensions-array-string，
在这里改成`["", "jsx", "web.js", "js"]`，依然会加载RN的文件

**Comment by warmhug** [comment]
这个有用吗？https://facebook.github.io/jest/docs/tutorial-webpack.html#content
![image](https://cloud.githubusercontent.com/assets/2011119/19674291/a3e80424-9ab9-11e6-93a3-9e3b3ba6f586.png)

**Comment by mhcgrq** [comment]
没用，`"moduleFileExtensions": ["web.js", "js", "jsx"]`和`"moduleFileExtensions": [".web.js", ".js", ".jsx"]`这两种都试过，前者依旧报`ReferenceError: __DEV__ is not defined`，后者直接连js文件也识别不了

**Comment by warmhug** [comment]
`__DEV__ is not defined` 是另外的问题，`__DEV__` 定义要配置下、查下怎么配置

**Comment by mhcgrq** [comment]
问题不在这里，即使我在package.json中加上
```
"jest": {
    "globals": {
      "__DEV__": true
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "jsx"
    ]
  }
```
这时候会报`Cannot find module 'throwOnWrongReactAPI' from 'react-native.js'`，这里还是加载了RN，并没有加载web版本的组件

**Comment by warmhug** [comment]
随后我们在 antd-mobile 脚手架里加上 jest 试试看

**Comment by silentcloud** [comment]
@mhcgrq  我在 #56 里的 demo 实例里本地尝试用最新 jest ，测试没问题，先看结果：

![image](https://cloud.githubusercontent.com/assets/1698185/19957851/2abcc120-a1d5-11e6-88e4-d031e0c45351.png)

![image](https://cloud.githubusercontent.com/assets/1698185/19957857/366b55a4-a1d5-11e6-8083-d58b8ed1c174.png)
![image](https://cloud.githubusercontent.com/assets/1698185/19957859/3e5ae31a-a1d5-11e6-81c5-bf401d4ec4ea.png)


package.json:

```json
"scripts": {
  ...
  "test": "jest"
},
"devDependencies": {
  ...
  "babel-jest": "^16.0.0",
  "jest": "^16.0.2",
  "react-addons-test-utils": "^15.3.2"
},
"jest": {
  "verbose": true,
  "moduleFileExtensions": ["web.js", "js", "json", "ts", "tsx"]
}
```

**Comment by silentcloud** [comment]
moduleFileExtensions 是关键，没有这个字段，就会报 "__DEV__"的错误
