### ISSUE TITLE
lodash 打包是否可以使用lodash-es来支持webpack5的tree shaking

### ISSUE THREAD

**Issue by smilelmz** [ant-design/ant-design-mobile#4175]
lodash 打包是否可以使用lodash-es来支持webpack5的tree shaking

**Comment by awmleer** [comment]
不知道在 SSR 模式下会不会有问题，后面我调研一下

**Comment by smilelmz** [comment]
@awmleer ok

**Comment by awmleer** [comment]
应该没啥问题，可以冲

**Comment by awmleer** [comment]
update

https://github.com/ant-design/ant-design-mobile/pull/4723#issuecomment-1019667925
