### ISSUE TITLE
[V5]: PullToRefresh头部内容期望可以添加用户自定义的方式

### ISSUE THREAD

**Issue by LwcReber** [ant-design/ant-design-mobile#4176]
下拉刷新时,如果是使用了图片的方式来替换不同状态的文案会导致下拉过程中,不同状态的图片一直闪烁
查看源码发现不同状态都会生成新的节点导致
![image](https://user-images.githubusercontent.com/22888671/137287974-3b7337fb-e840-4771-b39a-492fa1c643d0.png)

如果可以提供一个自定义的函数,把状态都传到这个函数里面,用户就可以根据状态自定义了
图片就在函数里面通过display:none来自行控制了

**Comment by zqran** [comment]
> 逻辑是没有问题的，`onStatusChange` 命名可以改成 `renderText` ，这样会更统一

好的~

那关于 `PullStatus` 枚举中的成员与组件 prop 命名不同的处理呢？比如，枚举是 `PullStatus.idle` 而 prop 是 `pullingText`
