### ISSUE TITLE
Search组件showCancelButton问题

### ISSUE THREAD

**Issue by 1548583993** [ant-design/ant-design-mobile#4178]
Search组件，showCancelButton置为true后，取消按钮会随输入框聚焦/失焦而出现/消失，请问是故意设计如此么？似乎大部分App以及其他一些UI库的搜索框，若有取消按钮则取消按钮是一直存在的。

**Comment by awmleer** [comment]
这个的确是目前的预期行为，不过我可以调整一下 API，支持多种的逻辑

**Comment by awmleer** [comment]
已支持 #4317
