### ISSUE TITLE
ImageUploader组件期望暴露用户自定义按钮内容api.

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#4182]
![image](https://user-images.githubusercontent.com/12706830/137332094-5981543b-12b1-42fa-a61a-121247cbc4f4.png)
上传 按钮+号无法替换，且按钮line-hight无效。建议改成flex。

checkbox组件　css变量

--icon-size 
--font-size

无效

**Comment by cheng-xiaofeng** [comment]
这个组件是怎么使用的? action的地址是加在哪里?
