### ISSUE TITLE
Picker组件滑动报错

### ISSUE THREAD

**Issue by excellnn** [ant-design/ant-design-mobile#4186]
Column组件内部convertPx函数计算出来的高为0的时候，无法滑动

**Comment by Luckingyl** [comment]
问题解决了吗？ 我也也到和你一样的问题。

**Comment by awmleer** [comment]
@Luckingyl 你的设备环境是……？系统和浏览器的版本号可以提供一下不？这样我们更好排查

**Comment by awmleer** [comment]
看报错信息的话，应该和 #4370 是同一个问题，请仔细阅读一下这篇文档：
https://mobile.ant.design/zh/guide/import-on-demand
