### ISSUE TITLE
怎么不让它根据不同的设备获取不同的font-size

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design-mobile#419]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：
#### 实际上的结果：

![image](https://cloud.githubusercontent.com/assets/18717051/19624316/c4ba13a6-9922-11e6-8543-f2103b8c3f2c.png)
![image](https://cloud.githubusercontent.com/assets/18717051/19624320/d4d2a276-9922-11e6-8e89-b4286f590071.png)

**Comment by SynChron1zed** [comment]
我想要个固定的 font-size

**Comment by silentcloud** [comment]
那就把 html 顶部的那部分 js 代码去除
