### ISSUE TITLE
新增PasscodeInput组件

### ISSUE THREAD

**Issue by faremax** [ant-design/ant-design-mobile#4190]
# PasscodeInput 密码、验证码输入框
![image](https://user-images.githubusercontent.com/9269277/137448281-4e76b60f-cc1a-49e4-b997-ac94b29d70a5.png)
![image](https://user-images.githubusercontent.com/9269277/137448314-e6e953c6-98fc-4e24-8924-ba57a3d22d42.png)

## 属性

| 属性                 | 说明                                        | 类型                               | 默认值        |
| -------------- | --------------------------- | ---------------------- | ----------- |
| length               | 输入框长度                            | number                          | 6                |
| value                 | 受控值                                    | string                             | -                |
| defaultValue     | 非受控值                                | string                             | -                |
| className       | 外层className                      | string                             | -               |
| style                  | 外层style                                | CSSProperties             | -                |
| plain                  | 是否展示明文                         | boolean                         | false          |
| error                  | 是否有错                                | boolean                          | false         |
| caret                  | 是否展示光标                         | boolean                          | true          |
| onChange        | 输入时回调                              | (value) => void             | false         |
| onFocus           | 获取焦点回调                          | () => void                      | false         |
| onBlur               | 失去焦点回调                          | () => void                      | false         |
| onFill                 | 填写完成回调                          | () => void                      | false         |

## Ref

| 属性               | 说明                                                    | 类型                                |
| ------------- | ----------------------------------- | ---------------------  |
| focus              | 让输入框获得焦点                               | () => void                     |
| blur                 | 让输入框失去焦点                               | () => void                     |

## CSS变量

| 属性               | 说明                                                     | 默认值                          |
| ------------- | ----------------------------------- | --------------------- |
| --cell-gap     | 单元格间距                                           | 0                                  |
| --cell-size     | 单元格大小                                           | 120                              |

Edit on Nov. 5

**Comment by awmleer** [comment]
`mask` 改成叫 `plain` （是否展示原文）吧，默认是 false，不然可能会和 Mask 组件产生语义上的混淆

**Comment by awmleer** [comment]
`gutter` 属性改为 `separated` 吧，类型就是 `true | false`～

**Comment by awmleer** [comment]
`clearOnError` 这个有必要支持嘛

**Comment by awmleer** [comment]
是不是可以增加一个事件，在用户填满内容之后触发，很多验证码的页面都是用户输入了六位的数字之后就自动提交了，可以需要这个事件
比如叫 `onFill`

**Comment by faremax** [comment]
> `gutter` 属性改为 `separated` 吧，类型就是 `true | false`～

gutter可以支持自定义间距，boolean就不行了。确定不要自定义间距了么

**Comment by faremax** [comment]
> 是不是可以增加一个事件，在用户填满内容之后触发，很多验证码的页面都是用户输入了六位的数字之后就自动提交了，可以需要这个事件 比如叫 `onFill`

没问题

**Comment by faremax** [comment]
> > gutter可以支持自定义间距，boolean就不行了。确定不要自定义间距了么
> 
> 自定义间距后面可以支持的，但是应该通过 CSS 变量来支持～ 比如增加一个 `--gap`

可以的

**Comment by faremax** [comment]
> `mask` 改成叫 `plain` （是否展示原文）吧，默认是 false，不然可能会和 Mask 组件产生语义上的混淆

没问题
