### ISSUE TITLE
Form 相关建议

### ISSUE THREAD

**Issue by Haoxuan8** [ant-design/ant-design-mobile#4192]
1. `Form.Item` 能否增加 `allowClear` 相关 api，`Form` 与 `Picker` 共同使用时，选择了选项后不能清空。希望选择后能将箭头变成叉号。
2. 同样是 `Form` 与 `Picker` 共同使用，希望 `Picker` 的显隐能由内部控制。
3. `Form.Item` 的 `disabled` 与 `onClick` 共同使用时，点击仍有背景颜色变化与 `onClick` 方法的回调。

**Comment by awmleer** [comment]
1. allowClear 是字段组件的内部逻辑，不同的字段需要的效果、交互、甚至逻辑都是不同的，很难在 Form 层面统一支持一个类似于 `allowClear` 的特性
2. 我考虑一下怎么支持，先记在这个单独的 issue 上了： #4211
3. #4207 这个 PR 修复了
