### ISSUE TITLE
为什么在这个框架 我引用别的比如echarts echarts是用px 算的 这样就会出现不兼容的问题 这个怎么解决

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design-mobile#420]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

**Comment by warmhug** [comment]
写下不用高清方案的方法 @pingan1927

**Comment by warmhug** [comment]
关联 #419

**Comment by carlos121493** [comment]
webpackConfig.postcss.push(pxtorem({
    rootValue: 100,
    propWhiteList: [],
    selectorBlackList: [/^(?!\.(am))/],
  }));
