### ISSUE TITLE
umi 同时使用antd-mobile-v2 和 antd-mobile 报错

### ISSUE THREAD

**Issue by echooys** [ant-design/ant-design-mobile#4206]
error  in ./node_modules/async-validator/dist-web/index.js

Module parse failed: Unexpected token (847:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| class Schema {
|   // ========================= Static =========================
>   static register = function register(type, validator) {
|     if (typeof validator !== 'function') {
|       throw new Error('Cannot register a validator by type, validator is not a function');

 @ ./node_modules/rc-field-form/es/utils/validateUtil.js 6:0-48 12:21-38
 @ ./node_modules/rc-field-form/es/Field.js
 @ ./node_modules/rc-field-form/es/index.js
 @ ./node_modules/antd-mobile/es/components/form/index.js
 @ ./node_modules/antd-mobile/es/index.js

**Comment by fladower** [comment]
我也是同样的问题，使用的是 beta13的版本，开始用的没任何问题，最近删除node_modules 重新安装后就一直报这个错了

**Comment by awmleer** [comment]
应该是 async-validator 的 bug，4.0.5 的版本似乎意外地引入了一个 break change：
https://github.com/yiminghe/async-validator/issues/295

目前应该在 4.0.6 修复了，所以可以再删掉 node_modules 重新安装一下依赖试试

**Comment by echooys** [comment]
已经解决了。
第一步：
关闭umi自带mobile
antd: {
    mobile: false,
  },
第二步：
umirc.ts 添加babel配置
  extraBabelPlugins: [
    [
      'import',
      {
        libraryName: 'antd-mobile',
        libraryDirectory: 'es/components',
        style: false,
      },
      'antd-mobile',
    ],
    [
      'import',
      {
        libraryName: 'antd-mobile-v2',
        style: 'css',
      },
      'antd-mobile-v2',
    ],
  ],
第三步：
安装 antd-mobile-v2 antd-mobile 就可以了

**Comment by echooys** [comment]
> > 这一部分的 antd-mobile 配置非常不推荐使用：
> > ```
> > [
> >       'import',
> >       {
> >         libraryName: 'antd-mobile',
> >         libraryDirectory: 'es/components',
> >         style: false,
> >       },
> >       'antd-mobile',
> >     ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以删掉的，具体可以参考这篇文档：https://mobile.ant.design/zh/guide/import-on-demand

我没看出来这两个配置有什么区别，不都是配置babel  只是umijs 的写法而已

**Comment by echooys** [comment]
> @echooys 就是，现在 antd-mobile v5 已经不需要再手动配置 babel-plugin-import 来实现按需加载了，默认就有按需加载的能力，所以不用对 v5 做这个配置了

需要配置的 不然找不到组件，不确定什么问题

**Comment by echooys** [comment]
> 如果真的需要手动的按需加载的话，可以参考这里的说明，不然可能使用上会出现问题：[https://mobile.ant.design/zh/guide/import-on-demand#手动的按需加载](https://mobile.ant.design/zh/guide/import-on-demand#%E6%89%8B%E5%8A%A8%E7%9A%84%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD)

他这个说明不适用umi  目前我使用的配置没问题，可以使用了

**Comment by awmleer** [comment]
[umi 项目安装 antd-mobile v5 后报错如何解决？](https://mobile.ant.design/zh/guide/faq#umi-%E9%A1%B9%E7%9B%AE%E5%AE%89%E8%A3%85-antd-mobile-v5-%E5%90%8E%E6%8A%A5%E9%94%99%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F)

**Comment by echooys** [comment]
> [umi 项目安装 antd-mobile v5 后报错如何解决？](https://mobile.ant.design/zh/guide/faq#umi-%E9%A1%B9%E7%9B%AE%E5%AE%89%E8%A3%85-antd-mobile-v5-%E5%90%8E%E6%8A%A5%E9%94%99%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F)

一样有问题哦 会找不到style

**Comment by ZY0118** [comment]
遇到一样的问题 style失效
