### ISSUE TITLE
ant-design-mobile  v5 Toast没有全局配置接口

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#4212]
v5版本，想要配置toast的全局配置，duration，maskClickable，需要全局配置，只能封装组件实现，如果项目中没有引用自己封装的组件，会导致项目整体toast不一致。希望能尽快安排解决这个问题。

**Comment by awmleer** [comment]
嗯嗯后面会支持的

**Comment by awmleer** [comment]
已支持
