### ISSUE TITLE
tabbar实现路由跳转 v5.0.0

### ISSUE THREAD

**Issue by xuanfengkou** [ant-design/ant-design-mobile#4225]
tabbar 实现路由跳转能否提供demo，本地调试使用onchange事件，路由挑战可以，底部的icon的active显示不对

**Comment by suisuinian123** [comment]
> 我们可以在文档上的 FAQ 里加一些说明，提供一下配合 react- router 使用的指引
什么时候提供react-router使用的指引啊，项目上正用到这个 55
