### ISSUE TITLE
Carousel组件用createClass方式，将其包装为组件打包引入其他项目报错getInitialState was defined on Carousel

### ISSUE THREAD

**Issue by carlos121493** [ant-design/ant-design-mobile#423]
#### 本地环境

- antd-mobile 版本：0.9.4
- 操作系统及其版本：mac os
- 浏览器及其版本：chromium
#### 你做了什么？

第三方组件引入antd-mobile后，再进行打包上传到npm。
在项目中使用第三方组件时报错。getInitialState was defined on Carousel
发现Carousel组件是用React.createClass写的，经过一次webpack用libraryTarget='umd'方式打包后，给其他应用用的时候出现报错
![](https://zos.alipayobjects.com/rmsportal/YygiKYzWLiWrNke.png)

**Comment by warmhug** [comment]
用不用 createClass 方式没问题吧，确认下包装组件的方式是否有误？

**Comment by carlos121493** [comment]
引入运作正常，只是如果打包的时候是以umd方式，然后供别的网站使用会有这样的问题。

**Comment by afc163** [comment]
升级 react

**Comment by silentcloud** [comment]
@carlos121493 问题是否已解决?

**Comment by warmhug** [comment]
没响应，先关掉
