### ISSUE TITLE
antd-mobile v5 does not work with nexjs, Why?

### ISSUE THREAD

**Issue by ahmadabudraya** [ant-design/ant-design-mobile#4237]
Please any hint to work v5 with nextJs ?

**Comment by zhaomenglu** [comment]
next15，next.config.js中配置了transpilePackages: ['antd-mobile'],页面上加了"use client"，报错，
![image](https://github.com/user-attachments/assets/046c9650-ef3a-4cea-8edf-143ba404871f)emm

**Comment by zhaomenglu** [comment]
> next15，next.config.js中配置了transpilePackages: ['antd-mobile'],页面上加了"use client"，报错， ![image](https://private-user-images.githubusercontent.com/39189837/382248803-046c9650-ef3a-4cea-8edf-143ba404871f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTUzNTEsIm5iZiI6MTczMDQ1NTA1MSwicGF0aCI6Ii8zOTE4OTgzNy8zODIyNDg4MDMtMDQ2Yzk2NTAtZWYzYS00Y2VhLThlZGYtMTQzYmE0MDQ4NzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5NTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNjhlN2NlNzA4ZTAyNzM1OTE5YTczZWFhYTkyNTllMzMwMTRhMThlOWQ4Y2Q0YTEyM2I0NjM2MTZmMGEzZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8zlMJVhONuv5rMhofE4QevB7HV8JhM-yQUvv2Wvm66c)emm

就只是在useEffect中使用了Toast.show({
        icon: 'fail',
        content: 'error',
      })
