### ISSUE TITLE
建议 TabBar 组件增加对 IconFont 的支持

### ISSUE THREAD

**Issue by LayGit** [ant-design/ant-design-mobile#424]
目前 TabBar 组件的图标强制使用 img 标签渲染，使用起来并不是非常方便。 IconFont 的优势不用说了，是否考虑支持一下，例如：
`<TabBar.Item icon={<i className="iconfont icon-home" />} selectedIcon={<i className="iconfont icon-home-fill" />} />`

这样既方便又优雅，也节省空间，还不用考虑图标图片的高清适配。

**Comment by silentcloud** [comment]
起初是为了保持和 rn 一致；这个需求之前也有人提及，下一个版本将支持，感谢反馈

**Comment by silentcloud** [comment]
added in f9da3de7148acf40a599f075a63560857302d40a; 

next version

**Comment by motorguo** [comment]
`List` 组件也添加支持一下吧  `iconfont` 图标
