### ISSUE TITLE
如果选择的省份或者地址正好处于选中后的中间位置，则不更新其下级的地市/区县

### ISSUE THREAD

**Issue by guojinxin-hub** [ant-design/ant-design-mobile#4245]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antd-mobile-doc-v2.gitee.io/kitchen-sink/components/picker?lang=zh-CN#picker-demo-0](https://antd-mobile-doc-v2.gitee.io/kitchen-sink/components/picker?lang=zh-CN#picker-demo-0)

### Steps to reproduce
如果选择的省份或者地址正好处于选中后的中间位置，不触发onChange事件

### What is expected?
如果选择的省份则更新其下级的地市/区县

### What is actually happening?
如果选择的省份在中间位置，不更新其下级的地市/区县，没有触发onChange事件

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | react 16.13.0 |
| System | windows |
| Browser | 94.0.4606.81（正式版本） |

---
缓慢选中组件列表中间位置，无法触发onChange事件

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下
