### ISSUE TITLE
为什么我的样式这么大？

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design-mobile#425]
不管是查询 还是list  文字和padding都特别大 跟挂网demo完全不一样，
我改用了 babel-plugin-import   但是还是非常大

**Comment by qq645381995** [comment]
@luolonghao @sorrycc @lifesinger @yiminghe @pingan1927

**Comment by qq645381995** [comment]
http://bj.crazyair.cn/#/search

**Comment by silentcloud** [comment]
#56 中 html 的头部 js 加了么

**Comment by qq645381995** [comment]
加什么js ？

**Comment by silentcloud** [comment]
@qq645381995 

https://github.com/ant-design/antd-init/blob/master/boilerplates/MobileDemo/index.html

**Comment by jozhi** [comment]
@silentcloud   如果是 dva 中如何配置 postcss-pxtorem

**Comment by silentcloud** [comment]
@jozhi pxtorem 跟 dva 没啥关系的，主要是配在 webpack.config 里

**Comment by jozhi** [comment]
@silentcloud    没有结合 dva 的那个 demo 中 pxtorem 是可以直接在 webpack.config 中运行的，但是基于 dva 再跑 ant-mobile 就配置不成功了，比较苦恼。我尝试过在 .roadhogrc  .roadhogrc.js 以及webpack.config.js里面进行配置，但是都没有成功。麻烦能不能给一个示例或者写法参考一下。。

**Comment by paranoidjk** [comment]
@jozhi https://github.com/sorrycc/roadhog#extrapostcssplugins

**Comment by jozhi** [comment]
@paranoidjk   能不能贴一下你的 .roadhogrc.js 配置文件
