### ISSUE TITLE
InputItem的控件，placeholder的文本，显示不全

### ISSUE THREAD

**Issue by HiroBaby** [ant-design/ant-design-mobile#426]
#### 本地环境

- antd-mobile 版本：0.9.3
- 操作系统及其版本：mac
- 浏览器及其版本：Safari
#### 你期待的结果是：

![image](https://cloud.githubusercontent.com/assets/20576666/19640722/9b38d000-9a10-11e6-8f56-b1fc0b7ca792.png)

#### 实际上的结果：

![image](https://cloud.githubusercontent.com/assets/20576666/19640626/2b4d0946-9a10-11e6-80ef-396b62733a37.png)

**Comment by pingan1927** [comment]
稍微调整了下

**Comment by LayGit** [comment]
0.9.6 版本，还是有一点点问题 @pingan1927 

![image](https://cloud.githubusercontent.com/assets/6624161/20137935/7cffa3d4-a6b8-11e6-854d-7c6bcb6bea5e.png)

**Comment by sosohime** [comment]
0.9.14版本依旧有此问题
测试机型：
iphone5
iphone6 plus

**Comment by warmhug** [comment]
@sosohime 是在真机上测试有问题吗？

**Comment by sosohime** [comment]
@warmhug 对，真机上有问题，另外开发环境是windows，chrome55.0.2883.87。
在pc调试的时候没有出现问题。

**Comment by pingan1927** [comment]
@sosohime 解决了，下一个小版本和大版本发布之后，再试试看
