### ISSUE TITLE
Form.Item 的 hidden属性build后不生效

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/ant-design-mobile#4260]
<Form.Item
  name='id'
  label='id'
  hidden
>
在开发环境中启动后生效，build后不生效

**Comment by anysunflower** [comment]
> 升级到20后，问题好了

请问是什么的版本升级到20呢？我也出现了这个情况

**Comment by anysunflower** [comment]
打包之后：
.adm-form-item-hidden {
display:none
}
display会被adm-list-item覆盖，但是在本地是正常的
.adm-list-item {
display:block
}

版本："antd-mobile": "^5.0.0-rc.1",

把另外再设置FormItem style display none就可以了
问题代码：
```
            <Item
                name="valid"
                noStyle
                hidden
                valuePropName="checked"
                label="ocr"
                style={{display: 'none'}}
                rules={[{required: true, message: 'ocr'}]}
            >
                <Checkbox>营业执照OCR是否通过</Checkbox>
            </Item>
```

**Comment by awmleer** [comment]
看起来是 CSS 优先级不够高

**Comment by awmleer** [comment]
@anysunflower d936b50a9 里修复了一下，下个版本发布之后可以更新试一下哈
