### ISSUE TITLE
v5 没法作为一个外部库在nodejs中使用

### ISSUE THREAD

**Issue by zyw00001** [ant-design/ant-design-mobile#4266]
v5没法作为一个外部库在nodejs中使用(不需要将antd-mobile代码打包进nodejs运行的代码中)，原因是无论怎样包含文件都会导入css文件。之前v2版本是可以独立作为一个外部库在nodejs中运行的。v5版本为什么要强制导入css文件呢?

**Comment by hold-baby** [comment]
```
/Users/ez/workspace/h5hub/node_modules/antd-mobile/cjs/global/global.css:1
:root {
SyntaxError: Unexpected token ':'
```
vite3 给的事例做 SSG 的时候也会有同样的问题 @awmleer

**Comment by awmleer** [comment]
@hold-baby SSR 或者 SSG 的话，都需要对 css 文件做一些特殊处理，具体得看不同框架提供的能力和 API

在这篇文档里有一些介绍：https://mobile.ant.design/zh/guide/ssr/

你所说的“ vite3 给的示例”可以发一下链接么

**Comment by hold-baby** [comment]
@awmleer 好，我试试
https://github.com/vitejs/vite-plugin-vue/blob/main/playground/ssr-vue/prerender.js 这是示例

**Comment by awmleer** [comment]
vue……？😅

可以试试这个：https://www.npmjs.com/package/node-css-require

**Comment by hold-baby** [comment]
和 Vue 没什么关系，道理都是一样的
我试下这个包😊

**Comment by mywei1989** [comment]
> 用MiniCssExtractPlugin和 isomorphic-style-loader都可以，但是太麻烦了，不如以前使用那么简单

具体的用法?
最近在开发  基于 vite-plugin-ssr 生成ssg的相关项目  目前也卡在这 看了所有相关issue 还不知道如何处理  
next.js 有对应的方法 不知道 vite 有没有?

**Comment by mywei1989** [comment]
> > 用MiniCssExtractPlugin和 isomorphic-style-loader都可以，但是太麻烦了，不如以前使用那么简单
> 
> 具体的用法? 最近在开发 基于 vite-plugin-ssr 生成ssg的相关项目 目前也卡在这 看了所有相关issue 还不知道如何处理 next.js 有对应的方法 不知道 vite 有没有?

这样解决 使用  noExternal 配置项
`
return defineConfig({
    plugins: [
      react(),
      vitePluginImp({
        libList: [
          {
            libName: "antd-mobile",
            style: () => false,
            libDirectory: "es/components",
            replaceOldImport: true,
          }]
      }),
      ssr({
        prerender: {
          parallel: 1,
          partial: true,
        },
        includeAssetsImportedByServer: true
      })
    ],
    ssr: {
      noExternal: ['antd-mobile']  
    }
  })
`
