### ISSUE TITLE
ImageViewer 组件在 react16.14.0 无法进行缩放

### ISSUE THREAD

**Issue by CirnoBreak** [ant-design/ant-design-mobile#4273]
ImageViewer 组件在 react 16.14.0 时无法进行双指缩放，但是在 react 17.x 没问题

**Comment by awmleer** [comment]
或许有哪位同学可以帮忙提供一个复现 demo 嘛？

**Comment by CirnoBreak** [comment]
> 或许有哪位同学可以帮忙提供一个复现 demo 嘛？

https://codepen.io/CirnoBreak/full/YzxYmmg 在移动端浏览器尝试双指缩放即可复现

**Comment by awmleer** [comment]
感谢～我看下

**Comment by awmleer** [comment]
复现出来了，我来修复一下

**Comment by awmleer** [comment]
似乎和这里相关：https://use-gesture.netlify.app/docs/gestures/#about-the-pinch-gesture

> Because React doesn't support proprietary Webkit GestureEvents, you will need to attach the gesture using a ref, with the target option.

**Comment by awmleer** [comment]
Fixed via 571a42d0a.
