### ISSUE TITLE
Form.Item内的Input增加一些附属元素，例如解释文本，或者操作Button，造成form.getFieldsValue()

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/ant-design-mobile#4278]
如表体，在Input旁增加一个按钮或者文字的原因是一些注释，或者通过Button自动给Input赋值，目前在Form.Item内Input旁增加了其他内容后，都造成form.getFieldsValue()无法获取值。

**Comment by awmleer** [comment]
这是你用法的问题，可以参考下 ant design 的文档：
https://ant.design/components/form-cn/

**Comment by awmleer** [comment]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/16526078/139813525-4282a613-987d-465d-8b89-b9cf56bcabef.png">

**Comment by zwjsoft** [comment]
ok！
