### ISSUE TITLE
Toast字体大小有些问题

### ISSUE THREAD

**Issue by LGDddd** [ant-design/ant-design-mobile#4280]
Toast组件未设置默认字体大小，提示内容偏小 2x模式下也是同样问题
![image](https://user-images.githubusercontent.com/30409967/139373207-a5003afa-b876-43f1-9c4e-f8e3c11ce7e6.png)

**Comment by awmleer** [comment]
可以提供一个复现 demo 么？
https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by awmleer** [comment]
先 close 了
