### ISSUE TITLE
增加一个简单的支持label和value的下拉组件，主要方便提供显示和值分离模式

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/ant-design-mobile#4286]
为方便显示内容和值分开的表单组件，建议增加一个类似下拉组件解决这个问题，这种需求常用。

**Comment by awmleer** [comment]
可以具体描述一下么？你是希望 antd-mobile 提供一个类似于桌面端的那种 Select 组件么？

**Comment by zwjsoft** [comment]
对，就是类似标准的pc下来组件，主要有这么几个好处，一是支持大量的选择项，现有的组件大多不支持大量选择项，二是lable和value模式，方便使用，三是外观上就是一个Input，不占空间，现有的选择项组件都会占用比较大的屏幕空间。

**Comment by awmleer** [comment]
之前也有很多同学反馈过类似的需求，我们认为 Select 是不符合移动端的交互规范的，暂时不会增加 Select 组件，不过这个问题我们还是会再长期考虑的

**Comment by skyfore** [comment]
@awmleer 请问这个规范是什么，感觉这个场景还挺常见的，特别是在表单复杂场景，我理解 PC 有的场景应该在 H5 都考虑如何呈现，而且现在越来越多都偏向于移动办公，这些能力更应该具备。
