### ISSUE TITLE
怎么调整Input和Search组件的高度，默认的行高太小

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/ant-design-mobile#4287]

**Comment by p697** [comment]
感觉这个问题值得重视一下，真机上的表现要更明显

SearchBar 的表现是这样的：

![qq_pic_merged_1638454091110](https://user-images.githubusercontent.com/51314472/144438081-2379aa6b-c200-4720-886a-a70b4bd9c46a.jpg)

肉眼可的严重上移了

Input 表现是这样：

![qq_pic_merged_1638454166800](https://user-images.githubusercontent.com/51314472/144438152-d6a05131-2a13-4250-88f5-0d3310b547e6.jpg)

也有一点点不协调的感觉

**Comment by awmleer** [comment]
+1 是要修复一下

**Comment by awmleer** [comment]
9489413c9 修复了一下对齐的问题

**Comment by awmleer** [comment]
#4672
