### ISSUE TITLE
InfiniteScroll 触发阈值计算出错

### ISSUE THREAD

**Issue by sarufarr** [ant-design/ant-design-mobile#4291]
`InfiniteScroll@5.0.0-beta.21`  loadmore 阈值计算出错

pr here https://github.com/ant-design/ant-design-mobile/pull/4290

**Comment by yangyipeng001** [comment]
同理InfiniteScroll@5.0.0-beta.21 loadmore 阈值计算出错，导致循环的请求接口，直到数据加载完。希望能快速解决一下

**Comment by awmleer** [comment]
#4290
