### ISSUE TITLE
求指教: ImageUploader组件上传的图片去哪了?也没有action指定地址, 那怎么上传图片, 这个组件怎么使用呢?

### ISSUE THREAD

**Issue by cheng-xiaofeng** [ant-design/ant-design-mobile#4296]

**Comment by zemelLeong** [comment]
我猜是使用`ImageUploader.upload`？

**Comment by cheng-xiaofeng** [comment]
> 我猜是使用`ImageUploader.upload`？

不是那个方法,  而是存在服务器的位置. 怎么传上去. pc端不是有个action来指定上传地址嘛, 移动端的第一左, 就不知道怎么做了

**Comment by zemelLeong** [comment]
你可能得自定义上传逻辑，类似这样：
```javascript
const upload = (file) => {
  const formData = new FormData();
  formData.append('file', file);
  request.post(url, formData);
}
```

**Comment by cheng-xiaofeng** [comment]
> 你可能得自定义上传逻辑，类似这样：
> 
> ```js
> const upload = (file) => {
>   const formData = new FormData();
>   formData.append('file', file);
>   request.post(url, formData);
> }
> ```

我也在想是不是这样, 找了一个开源项目, 也是差不过这样,我去问问我们的后台的接口怎么写吧
