### ISSUE TITLE
 bug：NoticeBar 组件，content动态赋值，更新后的内容，不会滚动

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#4298]
NoticeBar 组件，content动态赋值，更新后的内容，不会滚动，应该根据content变化处理，代码里useUpdateLayoutEffect，只是对key做依赖，应该要监听content公告内容变化的情况。

**Comment by zqran** [comment]
[https://codesandbox.io/s/notice-bar-smcgh?file=/src/App.tsx](https://codesandbox.io/s/notice-bar-smcgh?file=/src/App.tsx)

我测试了下，动态修改 content 的内容，是可以滚动的~

**Comment by liangskyli** [comment]
const [content, setContent] = useState(() => lorem.generateWords(5));//这里设置5，就有问题

**Comment by liangskyli** [comment]
> https://codesandbox.io/s/notice-bar-smcgh?file=/src/App.tsx
> 
> 我测试了下，动态修改 content 的内容，是可以滚动的~ #4229

const [content, setContent] = useState(() => lorem.generateWords(5));//这里设置5，就有问题

**Comment by zqran** [comment]
哦 get~

**Comment by awmleer** [comment]
Fixed via dd52ea211
