### ISSUE TITLE
rn ListView demo 改进

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#43]
现在 demo 的 demo 在手机上会造成卡顿甚至卡死

**Comment by warmhug** [comment]
直接在最外层使用是没这问题的，放进里边有问题，估计是因为首页也用了 ListView 的缘故？

**Comment by silentcloud** [comment]
@warmhug 应该不会是这个原因，一个 rn app 不可能只有一个 listview

**Comment by warmhug** [comment]
demo 已经改了，现在体验好一些。但 listView 的流畅度感觉还没达到理想，是否和 底层 oc 或 Android 组件的实现有关？
