### ISSUE TITLE
vite和parcel 2下tree shaking对css失效

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#4300]

**Comment by 0x219** [comment]
🐾 M

**Comment by awmleer** [comment]
怀疑是 `sideEffects` 配置导致的，这里调整了一下： 69bbdfd39

**Comment by 0x219** [comment]
> 怀疑是 `sideEffects` 配置导致的，这里调整了一下： [69bbdfd](https://github.com/ant-design/ant-design-mobile/commit/69bbdfd392e4753e891c00085648b2da80d1b51b)

感觉不太像是这里的问题吧 有效果吗？

**Comment by zzzgydi** [comment]
Vite项目需要处理一下才能支持css tree shaking，安装`vite-plugin-style-import`插件

```typescript
// vite.config.ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import styleImport from "vite-plugin-style-import";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    styleImport({
      libs: [
        {
          libraryName: "antd-mobile",
          base: "antd-mobile/es/global",
          resolveComponent: (name) => `antd-mobile/es/components/${name}`,
          resolveStyle: () => "antd-mobile/es/global/global.css",
        },
      ],
    }),
  ],
});
```

以上是基于`vite-plugin-style-import@1.3.0`对antd-mobile v5的一个处理。对antd-mobile v5来说，其实只要按需引入组件（如配置里的`resolveComponent`处理），再加上引入global就完事了。但，这个插件不设置`resolveStyle`会不生效，设置成`() => ''`之类的也不生效，而且antd mobile又不是每个组件都导出对应的css，所以这里除了设置`base`之外，只能额外再导入一遍`global.css`，反正vite会处理，问题不大。

**Comment by 0x219** [comment]
有木有大手子来解释一下原因。

**Comment by 0x219** [comment]
> Vite项目需要处理一下才能支持css tree shaking，安装`vite-plugin-style-import`插件
> 
> ```ts
> // vite.config.ts
> import { defineConfig } from "vite";
> import react from "@vitejs/plugin-react";
> import styleImport from "vite-plugin-style-import";
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [
>     react(),
>     styleImport({
>       libs: [
>         {
>           libraryName: "antd-mobile",
>           base: "antd-mobile/es/global",
>           resolveComponent: (name) => `antd-mobile/es/components/${name}`,
>           resolveStyle: () => "antd-mobile/es/global/global.css",
>         },
>       ],
>     }),
>   ],
> });
> ```
> 
> 以上是基于`vite-plugin-style-import@1.3.0`对antd-mobile v5的一个处理。对antd-mobile v5来说，其实只要按需引入组件（如配置里的`resolveComponent`处理），再加上引入global就完事了。但，这个插件不设置`resolveStyle`会不生效，设置成`() => ''`之类的也不生效，而且antd mobile又不是每个组件都导出对应的css，所以这里除了设置`base`之外，只能额外再导入一遍`global.css`，反正vite会处理，问题不大。

这种方式的确可以做到vite的按需引入，其实我比较关心的问题出现原因是啥。因为不止是vite有这个问题。

**Comment by zzzgydi** [comment]
我测试了一下parcel 2，现在（antd mobile beta25）是没有问题的。也测试了一下esbuild，也是没有问题的。vite还是有问题，可能和rollup不支持`sideEffects`有关。

**Comment by awmleer** [comment]
rollup 是可以支持 `sideEffects` 的……这个我验证过

**Comment by zzzgydi** [comment]
又测试了一下，vite是可以支持sideEffects里的css tree shaking，我把antd-mobile的依赖包单独拉出来，然后修改dependencies里为`"antd-mobile": "file:./antd-mobile"`，这样build出来的css是可以被shake掉的。但安装到直接npm install到node_modules里css就不被shake了。

**Comment by 0x219** [comment]
> 又测试了一下，vite是可以支持sideEffects里的css tree shaking，我把antd-mobile的依赖包单独拉出来，然后修改dependencies里为`"antd-mobile": "file:./antd-mobile"`，这样build出来的css是可以被shake掉的。但安装到直接npm install到node_modules里css就不被shake了。

😳

**Comment by awmleer** [comment]
看群友的反馈，现在 vite 在 production 模式下是可以 tree shaking 的

**Comment by awmleer** [comment]
至于 parcel，有大佬可以帮忙验证一下么

**Comment by zzzgydi** [comment]
parcel 2是支持的，dev时css是没有tree shaking，但build的时候是支持的

**Comment by awmleer** [comment]
@zzzgydi ook 感谢老哥

issue 我 close 了

**Comment by 0x219** [comment]
好的

卡晨 ***@***.***>于2022年1月11日 周二下午7:15写道：
