### ISSUE TITLE
BUG: Picker 选择器在 iPhone 8 上无法滑动

### ISSUE THREAD

**Issue by a1ooha** [ant-design/ant-design-mobile#4303]
在 iPhone 8（iOS 13.1.1）上 Picker 选择器无法滑动。 #4180 

https://user-images.githubusercontent.com/13401668/139780958-d14706b8-f842-4c33-8dc5-8f66c7708e46.mp4

**Comment by awmleer** [comment]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/16526078/139782050-859c2af0-1f91-43d6-9f96-44531926bfac.png">

iOS 13.1 对 pointer events 的支持看起来不够完善，尝试升级一下到 13.2 + 试试看？

**Comment by awmleer** [comment]
相关：https://github.com/pmndrs/use-gesture/issues/103

**Comment by a1ooha** [comment]
Ant Design Mobile 目前的兼容性标准不是 iOS >= 10 和 Android >= 5 吗？这个需要自己去 polyfill 吗？

**Comment by awmleer** [comment]
这个其实算是 iOS 13.1 或者 react-use-gesture 的 bug，推荐还是用户使用每个大版本的 iOS 下最新的小版本，或者 react-use-gesture 可以增加一下兼容性
很无奈的是，这个问题 antd-mobile 本身没有办法可以修复

**Comment by a1ooha** [comment]
> 这个其实算是 iOS 13.1 或者 react-use-gesture 的 bug，推荐还是用户使用每个大版本的 iOS 下最新的小版本，或者 react-use-gesture 可以增加一下兼容性 很无奈的是，这个问题 antd-mobile 本身没有办法可以修复

我刚试了一下，是 `useDrag` 的参数有问题，加上 `pointer: { touch: true }` 就可以了，我一会儿提个 PR。

**Comment by miusuncle** [comment]
加上 `pointer: { touch: true }` 后会引入一个更普遍的 bug：在带有 Home Indicator 的 iOS 设备中，打开 Picker 选择器 demo 页面，从 Home Indicator 处往斜上方滑碰触 Picker 某一列，松开手指，这时再试着滑动该列，发现已经滑不动了。类似使用了 `pointer: { touch: true }` 的使用了*纵向滑动*的组件都有类似的问题。

**Comment by awmleer** [comment]
> 加上 `pointer: { touch: true }` 后会引入一个更普遍的 bug：在带有 Home Indicator 的 iOS 设备中，打开 Picker 选择器 demo 页面，从 Home Indicator 处往斜上方滑碰触 Picker 某一列，松开手指，这时再试着滑动该列，发现已经滑不动了。类似使用了 `pointer: { touch: true }` 的使用了_纵向滑动_的组件都有类似的问题。

听起来似乎是个 bug，我先单独记一个 issue 吧： #4642
