### ISSUE TITLE
ImagePicker在Android微信内置浏览器中无法实现图片选择

### ISSUE THREAD

**Issue by deerW** [ant-design/ant-design-mobile#431]
#### 本地环境

- antd-mobile 版本：0.9.3
- 操作系统及其版本：android
- 浏览器及其版本：微信内置浏览器
#### 你做了什么？

引入 antd-mobile 的 ImagePicker
#### 你期待的结果是：

可以上传图片
期待不要像官网一样显示，官网给的mobile web demo就是无法正常显示。。
#### 实际上的结果：

Android无法上传图片，图片置灰无法选择。
#### 可重现的在线演示

用安卓机微信扫mobile web demo二维码

**Comment by silentcloud** [comment]
尝试升级到最新版还有问题么？
我这边测试 0.9.5 下面没有问题， android 4.4.4 微信最新版

issue 我先关了，有问题，你再 reopen @deerW
