### ISSUE TITLE
指示器跑到swiper组件之外了

### ISSUE THREAD

**Issue by Z-LianYan** [ant-design/ant-design-mobile#4311]
### Version of antd-mobile

5.0.0-beta.19

### What happened?

我有个测试平板型号lenovo X304 android 9.0，指示器跑到swiper组件之外了，测试过的其它手机是正常的,不知道有没有人用这款平板

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
需要提供一个复现的方法哈，最好是 codesandbox 上的 demo（你提交 issue 界面上应该提示你去 codesandbox 上写个 demo 了）

现在这个描述实在太过模糊了，我们也没办法帮你排查

**Comment by awmleer** [comment]
先关闭了，后续如果有更新可以继续回复在这里
