### ISSUE TITLE
ant-design-mobile 有没有rem配置的

### ISSUE THREAD

**Issue by Z-LianYan** [ant-design/ant-design-mobile#4312]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
https://mobile.ant.design/zh/guide/hd

**Comment by awmleer** [comment]
antd-mobile 本身是不会做 rem 相关的处理的，如果你希望使用 rem 布局，可以自己通过一些工具来实现，例如 postcss-px-to-rem
