### ISSUE TITLE
Dialog 弹窗组件支持 prompt 方法

### ISSUE THREAD

**Issue by a1ooha** [ant-design/ant-design-mobile#4314]
### Version of antd-mobile

5.0.0-beta.19

### What is this feature about?

V2 版本的 ant-mobile 支持 `Modal.prompt()` 调用输入弹窗，V5 版本的 Dialog 弹窗组件不支持这个方法。

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
v5 里是 `Dialog.show()`
