### ISSUE TITLE
ImageUploader组件onChange方法里面拿到upload返回的数据

### ISSUE THREAD

**Issue by Big-Bear-2019** [ant-design/ant-design-mobile#4316]
### What is this feature about?

现状：ImageUploader组件的upload里面返回uid或者其他对象属性，在onChange里面拿不到
![image](https://user-images.githubusercontent.com/52909947/140025597-13709cb7-776e-4119-bb24-3d02d6075bf2.png)

期望：ImageUploader组件的onChange回调里面能拿到upload返回的完整数据

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
5975dcd5a 中增加了一个 `extra` 字段，可以用来携带用户自定义的数据
