### ISSUE TITLE
Dialog 弹窗 content无法撑开内容区域。

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#4318]
### Version of antd-mobile

eg 5.0.0-beta.22

### Description

content区域无法width:100%.导致内容多宽，content就多宽，原因是父级div　使用了flex 未进行flex: 1.导致内容无法撑开。
场景截图
![image](https://user-images.githubusercontent.com/12706830/140030986-39046b5f-098d-4d0e-a564-34728cf5a588.png)
正常应该
![image](https://user-images.githubusercontent.com/12706830/140031151-1cf80999-d19a-441a-8886-620e8fe84218.png)

建议移除　adm-dialog-body-message-wrapper　adm-dialog-body-message　使用text-align:center .如果要使用这两个类div 建议flex: 1; text-align:center

**Comment by awmleer** [comment]
Fixed via 92c106d1d.

现在只有 `props.content` 为 `string` 时才会加上这套自动居中的容器
