### ISSUE TITLE
去掉 SegmentedControl 默认的 tintColor

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#432]
https://github.com/ant-design/ant-design-mobile/blob/fb6a2a316f8b6cee99d388110e055ae62a8af119/components/segmented-control/index.web.tsx#L15

这样 js 里不设置 tintColor 时，色彩走的是 less 样式，方便变量配置。

**Comment by silentcloud** [comment]
aeb3a35f60a866b3616f0b4bcc1e26d557517add
