### ISSUE TITLE
Module not found: Can't resolve 'antd-mobile/lib/*

### ISSUE THREAD

**Issue by bianliuzhu** [ant-design/ant-design-mobile#4320]
### Version of antd-mobile

5.0.0-beta.22

### Description

使用CRA创建的react项目,安装5.0的版本, 安装成功,使用时会报,对应模块找不到: `Module not found: Can't resolve 'antd-mobile/lib/toast`有没有比较好的解决办法

**Comment by awmleer** [comment]
你是不是配置过什么 babel 插件？可以发一下你的 babel 配置么？
