### ISSUE TITLE
打包出来的文件貌似很多重复helpers，没有计划用Babel插件去掉吗？

### ISSUE THREAD

**Issue by ZhangTaibin** [ant-design/ant-design-mobile#4322]
打包出来的文件貌似很多重复helpers，没有计划用Babel插件去掉吗？

**Comment by awmleer** [comment]
重复 helpers 是指？可以更具体一点描述一下么？

**Comment by ZhangTaibin** [comment]
就是Babel转换语法使用的那些辅助函数，每个文件里面都会重复定义。有些用库@babel/plugin-transform-runtime进行抽离引入，可以降低打包后的文件大小。我尝试引入，发现打包后文件大小并没有变，还以为你们用了其他的方法去除，但是看了打包后的代码，发现cjs每个组件都在组件js中定义了某些辅助方法

**Comment by awmleer** [comment]
@ZhangTaibin 具体是那些辅助函数嘞？可以把代码发下么？

**Comment by ZhangTaibin** [comment]
![image](https://user-images.githubusercontent.com/34602394/140282987-070e219f-cb6c-47ee-9d62-6f2b41e0db1e.png)
上面这张图中发现几乎每个js里面都定义了一个_interopRequireDefault的辅助函数，大可以进行抽离，只定义一次，每个文件中引入。目前是发现了这个编译import的辅助函数，可能存在别的辅助函数。

**Comment by awmleer** [comment]
这个是 [@babel/plugin-transform-modules-commonjs](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs) 生成的，这个辅助函数只会在 cjs 版本的产物里出现，对性能影响几乎可以忽略，如果使用 webpack 等打包工具进行打包的话，会自动使用 es 版本的产物的，我们也推荐你尽可能地优先使用 es 版本的产物，cjs 版本的存在目前只是为了适配一些 node 环境下的使用场景。
