### ISSUE TITLE
NumberKeyboard 的 closeOnBlur 逻辑被意外地触发了

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#4323]
### Version of antd-mobile

5.0.0-beta.19

### Operating system and its version

Others

### Browser and its version

Desktop Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yulinfeng000** [comment]
NumberKeyboard 在和其他组件绑定一起使用的时候(如div), 其他组件的onClick（或者onFocus等）触发NumberKeyboard方法中 一定要阻止事件冒泡
```js
<div
       onClick={(e) => {
            setKeyboardVisible(true); 
            e.stopPropagation(); // important !
       }}
></div>
```
我也是研究文档好久才发现，希望官方文档能提一嘴

**Comment by awmleer** [comment]
移除了 `onBlur` 和 `closeOnBlur`

0684b3382
