### ISSUE TITLE
表单禁用后、多次点击、可以获取到焦点、输入内容

### ISSUE THREAD

**Issue by hhf-ggt** [ant-design/ant-design-mobile#4329]
### Version of antd-mobile

5.0.0-beta.21

### Operating system and its version

Others

### Browser and its version

chrome: 94.0.4606.81

### Sandbox to reproduce

https://codesandbox.io/s/exciting-breeze-r8f2e?file=/src/App.js&resolutionWidth=360&resolutionHeight=675

### What happened?

- 禁用状态下、多次点击输入框、偶现光标、可以介入内容
- 官网demo也是有这个问题

### Relevant log output

```shell
无
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jermyn626** [comment]
难道是 `pointer-events` 的兼容问题？啥设备呢？
![image](https://user-images.githubusercontent.com/18393754/140542982-7cb11045-2db2-4d53-8b38-21b358702aa2.png)

**Comment by hhf-ggt** [comment]
chrome: 94.0.4606.81
谷歌浏览器、开启移动端调试

> 难道是`pointer-events`什么问题？啥设备呢？ ![图片](https://user-images.githubusercontent.com/18393754/140542982-7cb11045-2db2-4d53-8b38-21b358702aa2.png)

**Comment by jermyn626** [comment]
我这边还是复现不出来，用的 mac

Chrome 95.0.4638.69 & 移动端调试

**Comment by awmleer** [comment]
我用 iOS 15 的机器也没有复现出来

**Comment by zzzgydi** [comment]
我测试了一下，确实存在这个问题。（以下使用的是v5 beta 24）

下图为mac chrome(95.0.4638.69)的录屏(window chrome一样存在)：

![mac chrome](https://user-images.githubusercontent.com/27361820/140637156-d3914da4-43bb-4121-9746-399c0fd80776.gif)

下图是mac Safari的录屏：

![mac Safari](https://user-images.githubusercontent.com/27361820/140637237-df9807e2-c3d4-48be-856b-20c2ffe2232d.gif)

### 复现步骤

pc浏览器：

1. 表单禁用，input里得有placeholder文本，且没有value
2. pc模式访问
3. 对着placeholder文本做选中动作，就是点击该文本后向左或向右滑动

结果：

- Chrome可以获得焦点且可以输入内容
- Safari不能输入只是鼠标光标变成了text（这个问题不大）

移动端浏览器：好像只看到Android Chrome有点问题，可以获得焦点，但输入法不会弹出来。操作步骤是长按后向左或向右移动。

总结一下就是，首先假装要选中placeholder的文本，然后就出bug了。`List.Item`的disabled样式除了设置`pointer-events: none`之外，再设置一个`user-select: none`可以解决这个问题，但不知道这样是否符合该组件设计原意。

个人感觉`Form.Item`可以不提供disabled（我看那个antd就没提供），目前的disabled好像只用于样式没啥特别的逻辑处理。用户可以直接将disabled设置在子组件上，还能利用上原组件的disabed样式，也不会出现上述bug。

**Comment by awmleer** [comment]
感觉是浏览器的 bug，我测试了一下在 macOS 下的最新版 Chrome（96.0.4664.55）和 Android 设备下的浏览器（最新版钉钉内置浏览器）中都没复现出这个问题……

**Comment by zzzgydi** [comment]
我在Windows的Chrome（96.0.4664.45）里按我之前的方法也复现不了了。但是换一种方式还是可以的，比如通过切换焦点的方式，还是可以选中并且可以输入的......

**Comment by awmleer** [comment]
如果用户使用 Tab 键切换焦点，或者是使用屏幕阅读器（例如 iOS 的旁白）切换焦点，都是可以触发表单底层组件的焦点获取的，进而可以对表单组件进行控制
我尝试修复了一下，发现很困难，无论是试图阻止元素获取焦点，还是拦截 onChange 事件我都试了一下，不过都没有很好的效果
所以这个问题在 v5 版本暂时还是先不做修复了，因为对无障碍的支持不是 v5 版本的重点，可能要放到 v6 版本了，如果未来发现 `disabled` 这个属性很难在无障碍模式下有比较好的效果，还可能会在 v6 版本删掉这个属性，不过鉴于现在已经发布了 rc 版本，现在还是不现在删掉这个属性了
