### ISSUE TITLE
Modal.prompt auto-focus

### ISSUE THREAD

**Issue by zhaoyao91** [ant-design/ant-design-mobile#433]
期待的用户体验是，prompt弹出，则应该在输入框focus

**Comment by silentcloud** [comment]
这个需求在下一个版本中添加 props

**Comment by afc163** [comment]
直接默认属性好了，不用加 props。

**Comment by silentcloud** [comment]
那 ok

**Comment by silentcloud** [comment]
2117967dcf065bd991eb5657b7a9e7c2a1fa200e

android ok, ios 自身不支持 autofocus
