### ISSUE TITLE
数据录入型组件，是否应该支持 undefined 赋值

### ISSUE THREAD

**Issue by Hoo1nKyoma** [ant-design/ant-design-mobile#4332]
### What is this feature about?

```tsx
// src/utils/use-props-value.ts
import { useState, useCallback, useEffect } from 'react'

type Options<T> = {
  value?: T
  defaultValue: T
  onChange?: (v?: T) => void
}

export function usePropsValue<T>(options: Options<T>) {
  const { value: outerValue, defaultValue, onChange } = options

  const [value, setValue] = useState<T | undefined>(outerValue !== undefined ? outerValue : defaultValue)

  const setState = useCallback((v?: T) => {
    setValue(v)
    onChange?.(v)
  }, [onChange])

  useEffect(() => {
    if ('value' in options) {
      setValue(outerValue)
    }
  }, [outerValue])

  return [value, setState] as const
}
```

表单组件调用的 `usePropsValue` 是否这样实现会更合理些，开发者不用关心该组件的合法空值应该是什么类型，而是无脑的赋予 undefined 即可。
对于 input 组件赋予 undefined 的问题，应该使用类似 antd 的解决方案（ value == undefined ? '' : value）。

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
这有两个问题：

1. 在受控模式下，因为既 `setValue` 更新了组件的内部状态，又 `onChange` 更新了组件的外部状态，会导致组件重渲染两次，会有性能上的额外开销
2. 当 `outerValue` 变化时，组件是在 `useEffect` 中调用了 `setValue` 来更新内部状态，这样的话会慢一个渲染周期，这个一致性是肯定不符合预期的，会导致很多潜在的 bug

另外就是，你提到的“开发者不用关心该组件的合法空值应该是什么类型，而是无脑的赋予 undefined 即可”，其实我不太理解，可不可以再稍微具体解释一下？

**Comment by Hoo1nKyoma** [comment]
> 这有两个问题：
> 
> 1. 在受控模式下，因为既 `setValue` 更新了组件的内部状态，又 `onChange` 更新了组件的外部状态，会导致组件重渲染两次，会有性能上的额外开销
> 2. 当 `outerValue` 变化时，组件是在 `useEffect` 中调用了 `setValue` 来更新内部状态，这样的话会慢一个渲染周期，这个一致性是肯定不符合预期的，会导致很多潜在的 bug
> 
> 另外就是，你提到的“开发者不用关心该组件的合法空值应该是什么类型，而是无脑的赋予 undefined 即可”，其实我不太理解，可不可以再稍微具体解释一下？

1. 这个不会发生吧，因为受控组件的 `setValue` 和 `onChange` 的值是一样的，`setValue`（`React.setState`）会做一次全等比较
2. 这个我不太明白会出现什么问题，当然我觉得更适合的是 `static getDerivedStateFromProps` 

比如我想将一个输入型组件设置为空值，目前我必须通过将 input 设置为 `value = ''` ，rate 组件设置为`value = 0`，但是如果可以仅对这些 `value` 赋予 `undefined` 就能达到目的会更合理些。

**Comment by awmleer** [comment]
> 这个不会发生吧，因为受控组件的 setValue 和 onChange 的值是一样的，setValue（React.setState）会做一次全等比较

可以参考这个 issue：https://github.com/alibaba/hooks/issues/984

> 比如我想将一个输入型组件设置为空值，目前我必须通过将 input 设置为 value = '' ，rate 组件设置为value = 0，但是如果可以仅对这些 value 赋予 undefined 就能达到目的会更合理些。

现在应该也是可以的呀，你 `value` 如果传 `undefined` 的话，组件就会 fallback 到 `defaultValue` 了，可以试试看哈

**Comment by Hoo1nKyoma** [comment]
https://codesandbox.io/s/recursing-snow-o2blx?file=/src/App.js
antd-mobile 5.0.0-beta.24

**Comment by awmleer** [comment]
get 我来看下

**Comment by awmleer** [comment]
如果 `value` 从一个正常值（defined）变为了 `undefined`，其实意味着组件从受控模式切换为了非受控模式，这是一种应该避免的情况。我用原生 input 测试了一下，可以看到 React 弹出了一条 warning：

```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
```

并且输入框中的值并没有清空。

具体 demo 见：https://codesandbox.io/s/zealous-feather-g2roe?file=/src/App.js

**Comment by Hoo1nKyoma** [comment]
我觉得 Input 这个场景需要额外处理，也就是说用户传 `undefined` 给组件，组件内部传空字符串给原生 input 组件。以下是 antd 的实现
```tsx
export function fixControlledValue<T>(value: T) {
  if (typeof value === 'undefined' || value === null) {
    return '';
  }
  return value;
}
```

其它（Rate、Select）组件不存在这种问题，我觉得是应该实现的。

**Comment by awmleer** [comment]
我个人也是觉得应该去处理 `value` 变为 `undefined` 的情况的，但是担心会和 React 中一些原生组件的行为不一致，会带来一些理解成本和问题

**Comment by awmleer** [comment]
从另一个角度考虑，当 `value` 从 defined 变为 undefined 时，其实真正的含义是，**组件变为非受控模式**，而不是**清空组件内部的状态**。那么如果一个组件实例，原本是处于受控模式，并且有 `value` 为 `123`，此时进入非受控模式，它所显示的值应该是保持 `123` 呢，还是应该重置为 `defaultValue` 呢？

如果这样来理解和分析这个问题的话，我觉得前者的逻辑才是真正合理的。

**Comment by awmleer** [comment]
（前者也是当前 antd-mobile 的行为）

**Comment by awmleer** [comment]
顺便附一下 antd 的 demo，行为和 antd-mobile 是不一样的：
https://codesandbox.io/s/antd-input-value-set-to-undefined-mzf3y?file=/index.js

**Comment by awmleer** [comment]
这个 issue 先 close 了，目前来看不应该调整这块的逻辑～
anyway，非常感谢反馈

**Comment by brickspert** [comment]
我觉得 antd mobile 现在的行为肯定是不对的。如果组件传递了 `value` 属性，那就是受控组件。

这个行为和 antd 保持一致即可。 我觉得现在 antd mobile 的实现非常非常不合理。  

对于用户来说，感知 `undefined`、`null` 的类型不同，行为不同，是反人类的。😋

**Comment by awmleer** [comment]
按照 ReactDOM 现在对 `input` 的实现，`<input value={undefined} />` 和 `<input />` 都是非受控模式，antd mobile 现在和 ReactDOM 的处理是保持一致的

**Comment by brickspert** [comment]
cc @zombieJ

**Comment by zombieJ** [comment]
antd 里重构过的组件按照这个规则来：
* `value` 为非 `undefined` 时（包括 `null`）为受控模式
* `value` 为 `undefined` 时（包括不设置）为非受控模式
* `value` 由非 `undefined` 变为 `undefined` 时，清空值并变为非受控
* 非受控 < `defaultValue` < `value` 且 `defaultValue` 仅在首次 render 生效

**Comment by awmleer** [comment]
> `value` 由非 `undefined` 变为 `undefined` 时，清空值并变为非受控

这个逻辑是为啥需要嘞……特别是“清空”这个动作本身的含义其实有些模糊，是指把值重置为 `defaultValue` 么

其他的几点现在 antd-mobile 的逻辑也是这样的

**Comment by zombieJ** [comment]
> 这个逻辑是为啥需要嘞……特别是“清空”这个动作本身的含义其实有些模糊，是指把值重置为 defaultValue 么
>
> 其他的几点现在 antd-mobile 的逻辑也是这样的

清空是等同于 `null` 的表现，只是重置后不再受控。不是 `defaultValue`。
