### ISSUE TITLE
Button 组件希望支持圆角

### ISSUE THREAD

**Issue by dobble11** [ant-design/ant-design-mobile#4335]
### What is this feature about?

例如antd  shape 属性
https://ant.design/components/button-cn/#API

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zqran** [comment]
Button 的圆角可以通过 CSS 变量 `--border-radius` 自定义

**Comment by awmleer** [comment]
+1 目前可以先用 `--border-radius` 自定义，后面我们考虑一下要不要加个 `shape` 属性

**Comment by dobble11** [comment]
👌，只是属性比较简洁直观些

**Comment by awmleer** [comment]
增加一个属性：

```
shape: 'default' | 'rounded' | 'rectangular'
```

**Comment by dobble11** [comment]
> 增加一个属性：
> 
> ```
> shape: 'default' | 'rounded' | 'rectangular'
> ```

👍
