### ISSUE TITLE
input 不存在 extra 类型，但是官网上有，很迷惑

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [ant-design/ant-design-mobile#4336]
### Version of antd-mobile

5.0.0-beta21

### Operating system and its version

Android

### Sandbox to reproduce

https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

### What happened?

![image](https://user-images.githubusercontent.com/32830366/140681670-f0f7e46f-2f9c-4cf4-90f8-2ce811ba87e5.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zqran** [comment]
要用 extra 的话，需要配合 List.Item 使用

**Comment by awmleer** [comment]
#4348 给 Form.Item 增加了 `extra` 属性，以后就更方便了
