### ISSUE TITLE
Tabs 组件 activeKey 类型定义缺少 number 类型支持及 key 值问题

### ISSUE THREAD

**Issue by dobble11** [ant-design/ant-design-mobile#4337]
### What is this feature about?

Tabs 的 activeKey 属性定义为 string | null ，而 TabPane 的 key 定义为 React.Key ，缺少对 number 类型的定义；

另外 TabPane 不给 key 时，TabPane 不会渲染，缺少默认值行为，代码

```tsx
     <Tabs>
        <Tabs.TabPane title="全部"  />
        <Tabs.TabPane title="可使用" />
      </Tabs>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by miracles1919** [comment]
1、React.Key 的定义虽然是 `string | number`，但实际 createElement 的时候会将 key 转成 string 类型（key = '' + key）

可以看下源码 https://github.com/facebook/react/blob/main/packages/react/src/ReactElement.js#L225-L237

2、TabPane（现已改名为 Tab） 缺少 key 时不会渲染，这是预期行为，对不存在 key 的 children 做了过滤

可以看下代码 https://github.com/ant-design/ant-design-mobile/blob/master/src/components/tabs/tabs.tsx#L66-L75

**Comment by dobble11** [comment]
> 1、React.Key 的定义虽然是 `string | number`，但实际 createElement 的时候会将 key 转成 string 类型（key = '' + key）
> 
> 可以看下源码 https://github.com/facebook/react/blob/main/packages/react/src/ReactElement.js#L225-L237
> 
> 2、TabPane（现已改名为 Tab） 缺少 key 时不会渲染，这是预期行为，对不存在 key 的 children 做了过滤
> 
> 可以看下代码 https://github.com/ant-design/ant-design-mobile/blob/master/src/components/tabs/tabs.tsx#L66-L75

👍
