### ISSUE TITLE
Picker 滑动崩溃

### ISSUE THREAD

**Issue by Luckingyl** [ant-design/ant-design-mobile#4339]
>5.0.0-beta.14 后的版本,滑动会报错
![Uploading image.png…]()

**Comment by Luckingyl** [comment]
column.js:77 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at scrollSelect (column.js:77)
    at DragEngine.Column.Object.axis (column.js:90)
    at DragEngine.emit (actions-49482b72.esm.js:407)
    at DragEngine.pointerUp (actions-494

**Comment by GOWxx** [comment]
图片没有成功上传诶
或许可以给个codesandbox复现demo

**Comment by GOWxx** [comment]
> 5.0.0-beta.14 后的版本,滑动会报错

图片没有成功上传诶
或许可以给个codesandbox复现demo

**Comment by Luckingyl** [comment]
我发现和 #4186  提的问题原因应该是一样的。 
![Uploading WX20211108-160248@2x.png…]()

**Comment by awmleer** [comment]
看报错信息的话，应该和 #4370 是同一个问题，请仔细阅读一下这篇文档：
https://mobile.ant.design/zh/guide/import-on-demand
