### ISSUE TITLE
@tabs-prefix-cls 变量名冲突

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#434]
- https://github.com/ant-design/ant-design-mobile/blob/702b6965ac14d81c693c7fe256f976cdf14ab92e/components/tab-bar/style/index.less#L4
- https://github.com/ant-design/ant-design-mobile/blob/fb6a2a316f8b6cee99d388110e055ae62a8af119/components/tabs/style/index.less#L4

**Comment by silentcloud** [comment]
333c90b12d0864b59d99c52262480d2d41ba0ede
