### ISSUE TITLE
InfiniteScroll 添加手动加载更多

### ISSUE THREAD

**Issue by zcrkey** [ant-design/ant-design-mobile#4340]
### Version of antd-mobile

5.0.0-beta.24

### What is this feature about?

1、使用 InfiniteScroll 组件，页面在首次加载的就会触发loadMore方法，按道理这个时候页面没有滚动，不会触发的才对（首次加载数据应该由开发者自己去获取）
2、当页面上已经有加载多条数据（有滚动条的情况 下），其他操作去更新列表数据的时候（例如用户点击搜索按钮），就会触发到oadMore方法，按道理不是用户触发其他的操作，应该由开发者自己去处理数据就好，而不是自动去触发oadMore方法

综上，还是建议有一个可以上拉加载更多的功能，类似 PullToRefresh 组件一样的效果

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
> 使用 InfiniteScroll 组件，页面在首次加载的就会触发loadMore方法，按道理这个时候页面没有滚动，不会触发的才对（首次加载数据应该由开发者自己去获取）

你可以把 InfiniteScroll 理解为一个无情的数据加载机器人，它唯一的指责就是判断当前页面是不是被填充了足够多的内容，如果没有，就继续调用 `loadMore` 加载数据，除非内容已经被全部加载完了。如果你想让页面首次加载的时候不触发 `loadMore`，我觉得应该是不去渲染 InfiniteScroll 组件。当然，其实我不是特别理解你的使用场景，所以如果可以提供一个 demo 的话，会更方便我们沟通，不然太泛泛了。

**Comment by awmleer** [comment]
> 当页面上已经有加载多条数据（有滚动条的情况 下），其他操作去更新列表数据的时候（例如用户点击搜索按钮），就会触发到oadMore方法，按道理不是用户触发其他的操作，应该由开发者自己去处理数据就好，而不是自动去触发oadMore方法

这一点上，我大概理解你的应用场景，不过我觉得应该是这样来实现：当用户重新触发了搜索时，应该通过 `key` 来让子组件完全销毁并重新创建，而不是非常繁琐且不可靠的去对组件状态进行 patch。
同理哈，这里也是最好能提供一个 codesandbox 上的 demo。

> 还是建议有一个可以上拉加载更多的功能，类似 PullToRefresh 组件一样的效果

这个我还是不太理解你的意思，最好可以具体一点？

**Comment by awmleer** [comment]
issue 先 close 了哈，不过有问题的话我们还是继续在这里沟通的

**Comment by zcrkey** [comment]
您好，我在 codesandbox 上的写了一个demo，地址是：https://codesandbox.io/s/lucid-wright-itko5?file=/src/test.js
当页面上已经有加载多条数据（有滚动条的情况 下），在搜索框内输入数据，回车，这个时候就会触发到oadMore方法，按道理用户触发了其他的操作，应该由开发者自己去处理数据就好，而不是自动去触发oadMore方法

**Comment by zcrkey** [comment]
您好，我在 codesandbox 上的写了一个demo，地址是：https://codesandbox.io/s/lucid-wright-itko5?file=/src/test.js
当页面上已经有加载多条数据（有滚动条的情况 下），在搜索框内输入数据，回车，这个时候就会触发到oadMore方法，按道理用户触发了其他的操作，应该由开发者自己去处理数据就好，而不是自动去触发oadMore方法

**Comment by awmleer** [comment]
我去你这个 codesandbox 里试了一下，搜索的时候并没有进入到 `loadMore` 的 `debugger` 断点啊

**Comment by ycshill** [comment]
> > 使用 InfiniteScroll 组件，页面在首次加载的就会触发loadMore方法，按道理这个时候页面没有滚动，不会触发的才对（首次加载数据应该由开发者自己去获取）
> 
> 你可以把 InfiniteScroll 理解为一个无情的数据加载机器人，它唯一的指责就是判断当前页面是不是被填充了足够多的内容，如果没有，就继续调用 `loadMore` 加载数据，除非内容已经被全部加载完了。如果你想让页面首次加载的时候不触发 `loadMore`，我觉得应该是不去渲染 InfiniteScroll 组件。当然，其实我不是特别理解你的使用场景，所以如果可以提供一个 demo 的话，会更方便我们沟通，不然太泛泛了。

我也觉得不应该在每次渲染的时候就check ，毕竟我们使用这个组件只是想用上滑加载更多的功能。
