### ISSUE TITLE
antd-mobile-icons 几年没维护了，文档也404了，弄个自定义icon都找不到怎么办啊

### ISSUE THREAD

**Issue by XueMeijing** [ant-design/ant-design-mobile#4341]
### What is this feature about?

官网上icon太少，而且没有写怎么自定义icon的教程，可以参考下PC端antd的

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xiaohuoni** [comment]
直接用 antd 的 icon 不行吗？

**Comment by awmleer** [comment]
这个包是新发布的啊 https://www.npmjs.com/package/antd-mobile-icons

**Comment by XueMeijing** [comment]
> 这个包是新发布的啊 https://www.npmjs.com/package/antd-mobile-icons

好吧谢谢，我在官网 https://mobile.ant.design/zh/components/icon 上没看到链接，然后去github搜了下看到时老版本的 https://github.com/ant-design/antd-mobile-icons 以为没有更新。那这个新发布的包支持自定义Icon吗
