### ISSUE TITLE
Card、Image 等数据展示类组件加入 loading 属性

### ISSUE THREAD

**Issue by p697** [ant-design/ant-design-mobile#4342]
### Version of antd-mobile

5.0.0-beta.21

### What is this feature about?

可以借助 [react-loading-skeleton](https://github.com/dvtng/react-loading-skeleton) 为 Card、Image、List、Steps 等数据展示类组件加入 loading 属性，该属性为受控属性，当数据正在请求或计算的时候设置为 true，此时组件就会处于 loading 状态。当请求逻辑完成后设置为 false，渲染数据。

也可以考虑加入 defaultLoading 属性，当设置为 true 时，若组件中的值为 undefined，则默认开启 loading 状态。

加入方式和效果可以参考：https://codesandbox.io/s/react-loading-skeleton-3xwil?file=/src/App.tsx:154-176

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GOWxx** [comment]
与 #4343 重复了

**Comment by p697** [comment]
> 与 #4343 重复了

感谢提醒，可能是网络问题多点了
