### ISSUE TITLE
Switch 组件不受 Form 组件 initialValues 控制

### ISSUE THREAD

**Issue by wanghaida** [ant-design/ant-design-mobile#4344]
### Version of antd-mobile

5.0.0-beta.17

### What happened?

在 Form 组件 initialValues 属性初始化值时，Switch 组件并没有进行相应变化，但修改 Switch 状态，可以同步修改 Form 值。

```jsx
<Form initialValues={{ isDefault: true }}>
    <Form.Item label="设置默认地址" name="isDefault">
        <Switch />
    </Form.Item>
</Form>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zzzgydi** [comment]
Form Item增加`valuePropName="checked"`

```jsx
    <Form.Item label="设置默认地址" name="isDefault" valuePropName="checked">
        <Switch />
    </Form.Item>
```

**Comment by wanghaida** [comment]
@zzzgydi 🌹 还有种解决方案就是加 `defaultChecked`

```jsx
<Form.Item label="设置默认地址" name="isDefault">
    <Switch defaultChecked />
</Form.Item>
```

**Comment by zzzgydi** [comment]
加这个defaultChecked只是让它默认为真了，但这个组件到底还是不受form控制的。

**Comment by awmleer** [comment]
还是要给 `Form.Item` 加 `valuePropName="checked"` 的～这个是正确的使用姿势

**Comment by wanghaida** [comment]
是的，`defaultChecked` 需要修改两个地方，麻烦易出错。在不知道 `valuePropName="checked"` 时的无奈之举
