### ISSUE TITLE
ListView, SegmentedControl

### ISSUE THREAD

**Issue by frank-niuu** [ant-design/ant-design-mobile#4345]
### What is this feature about?

希望v5新版本可以增加v2版本有的SegmentedControl 分段器,ListView 长列表

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
SegmentedControl 不在新版本的设计规范中，目前确定是不会做了，可以考虑用 Tabs、CapsuleTabs、Selector 替代

ListView 是不会做的，可以考虑用社区上其他的虚拟滚动库，例如 [react-virtualized](https://bvaughn.github.io/react-virtualized/)
