### ISSUE TITLE
react-spring-core.esm.js:811 Uncaught SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by 244686710** [ant-design/ant-design-mobile#4347]
### Version of antd-mobile

5.0.0-base21

### Operating system and its version

Others

### Browser and its version

"Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36 QBCore/4.0.1326.400 QQBrowser/9.0.2524.400 Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36 wxwork/3.1.11 (MicroMessenger/6.2) WindowsWechat"

### Sandbox to reproduce

无

### What happened?

在低版本中的打开会报这个错误，发现mask组件有依赖这个react-spring这个插件
![image](https://user-images.githubusercontent.com/20982796/140859309-cd4b6ec8-8280-404b-957a-9962d39e73a0.png)

### Relevant log output

```shell
Uncaught SyntaxError: Unexpected token (          react-spring-core.esm.js:811
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
你上面发的 UA 太复杂了……可以发一下具体的版本号和设备信息么

我在 Chrome 53 on Windows 10 下测试是完全正常的

**Comment by yeaaaling** [comment]
发现了相同问题，在window版本的企业微信下面，浏览器是chrome 53

**Comment by GOWxx** [comment]
> 发现了相同问题，在window版本的企业微信下面，浏览器是chrome 53

把这个包配一下bable

**Comment by GOWxx** [comment]
> 发现了相同问题，在window版本的企业微信下面，浏览器是chrome 53

把这个包配babel，转义一下

**Comment by Aaron674092290** [comment]
> > 发现了相同问题，在window版本的企业微信下面，浏览器是chrome 53
> 
> 把这个包配babel，转义一下

想问下怎么配置呢 @GOWxx

**Comment by gauseen** [comment]
![image](https://user-images.githubusercontent.com/22701565/204781387-6b1a8236-ad4f-4e18-b44b-9d24a809e107.png)
@Aaron674092290 按照这个配置就行，注意红框里的提示
