### ISSUE TITLE
使用Flex布局的时候，怎么像栅格一样设置不同的宽度

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design-mobile#435]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

#### 实际上的结果：
![image](https://cloud.githubusercontent.com/assets/18717051/19679284/ce518144-9ad3-11e6-9646-e1dffaeb3663.png)

**Comment by warmhug** [comment]
建议仔细学下 flex 布局吧，Flex 组件也只是简单的 flex 布局应用。
