### ISSUE TITLE
ImageViewer 组件在 5.0.0-beta-23和24 都无法在移动端设备拖动

### ISSUE THREAD

**Issue by CirnoBreak** [ant-design/ant-design-mobile#4350]
### Version of antd-mobile

5.0.0-beta-24

### Operating system and its version

Others

### Browser and its version

both Android and iOS browsers

### Sandbox to reproduce

https://github.com/CirnoBreak/image-viewer-issue

### What happened?

antd-mobile升级到5.0.0-beta23之后的版本开始无法在移动端设备进行手势滑动切换图片，PC Chrome/Edge 浏览器没打开移动端调试时可以正常滑动切换图片，猜测是这次修改导致的 [https://github.com/ant-design/ant-design-mobile/pull/4304](https://github.com/ant-design/ant-design-mobile/pull/4304)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
目前推测的原因是 `@use-gesture/react` 的 `10.1.4` 版本存在 bug，我直接在 antd-mobile 中锁住版本了： da0ec4ae3
升级一下 antd-mobile 到 beta.25 就不会存在这个问题了

**Comment by CirnoBreak** [comment]
> 目前推测的原因是 `@use-gesture/react` 的 `10.1.4` 版本存在 bug，我直接在 antd-mobile 中锁住版本了： [da0ec4a](https://github.com/ant-design/ant-design-mobile/commit/da0ec4ae39eda4228e3d15868c060e919cbfcfc6) 升级一下 antd-mobile 到 beta.25 就不会存在这个问题了

刚刚试了下，没问题了

**Comment by awmleer** [comment]
https://github.com/pmndrs/use-gesture/pull/393
