### ISSUE TITLE
beta.20， beta.22， beta.24 的下拉刷新全部不能用，降级到beta.19才能用，测试能不能认真点

### ISSUE THREAD

**Issue by JohnJiang900526** [ant-design/ant-design-mobile#4352]
### Version of antd-mobile

beta.20， beta.22， beta.24 

### Browser and its version

beta.20， beta.22， beta.24 的下拉刷新全部不能用，降级到beta.19才能用，测试能不能认真点

### Sandbox to reproduce

beta.20， beta.22， beta.24 的下拉刷新全部不能用，降级到beta.19才能用，测试能不能认真点

### What happened?

下拉刷新 PullToRefresh 组件

### Relevant log output

```shell
beta.20， beta.22， beta.24 的下拉刷新全部不能用，降级到beta.19才能用，测试能不能认真点
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
https://github.com/ant-design/ant-design-mobile/issues/4350#issuecomment-963980051

目前的推测是，拖拽手势失效不是 antd-mobile 的问题，是底层依赖的升级直接出了严重的 bug

目前已经锁住 `@use-gesture/react` 的版本了，升级 antd-mobile 到 beta.25 即可

**Comment by awmleer** [comment]
https://github.com/pmndrs/use-gesture/pull/393
