### ISSUE TITLE
[Search Component] onChange event is triggered by cancel button.

### ISSUE THREAD

**Issue by keepmood** [ant-design/ant-design-mobile#4353]
### Version of antd-mobile

5.0.0-beta.24

### Operating system and its version

Others

### Browser and its version

Windows10x64 Chrome v95.0.4638.69

### Sandbox to reproduce

https://codesandbox.io/s/reverent-panka-8lwnw?file=/src/App.js

### What happened?

Click the cancel button to trigger the cancel event, but the onChange event will also be triggered.
![image](https://user-images.githubusercontent.com/6124209/140934692-2a4e7902-71a4-442b-b7ed-fa92c2c6e988.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by p697** [comment]
Maybe it's not a bug, here is another api: onSearch.

Refer to the doc:

![image](https://user-images.githubusercontent.com/51314472/141030495-b7078929-9341-46ba-aeaa-316996617b79.png)

If cancel button trigger the onSearch event, that would be a bug.

**Comment by keepmood** [comment]
> Maybe it's not a bug, here is another api: onSearch.
> 
> Refer to the doc:
> 
> ![image](https://user-images.githubusercontent.com/51314472/141030495-b7078929-9341-46ba-aeaa-316996617b79.png)
> 
> If cancel button triggered the onSearch event, that would be a bug.

Do you think it is reasonable for the cancel button to trigger the onSearch event? 😃

**Comment by p697** [comment]
My point is:  It's not reasonable to trigger onSearch event,  but it's reasonable to trigger onChange event.

**Comment by awmleer** [comment]
Currently this is the intended behavior. When you click the cancel button, the content get cleared. So the `onChange` event is triggered. But we could add a `clearOnCancel` prop to control this behavior.

**Comment by keepmood** [comment]
> My point is: It's not reasonable to trigger onSearch event, but it's reasonable to trigger onChange event.

Sorry, i read it wrong.

**Comment by awmleer** [comment]
Close via #4360.
