### ISSUE TITLE
Checkbox组件的禁用状态能不能不要出现已勾选的Icon，有歧义。

### ISSUE THREAD

**Issue by luopc1218** [ant-design/ant-design-mobile#4365]
### What is this feature about?

出现了禁用状态的同时有已选中和未选中两种情况的需求，而Checkbox组件目前的禁用状态是默认带了已选中的那个勾的，会出现状态歧义。
![image](https://user-images.githubusercontent.com/49462546/141399759-e3e09aba-d3d6-4bda-8902-403a0714f382.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
应该是个 bug
