### ISSUE TITLE
PickerView 选择器视图相关

### ISSUE THREAD

**Issue by wangibook** [ant-design/ant-design-mobile#4367]
### What is this feature about?

![image](https://user-images.githubusercontent.com/34546550/141406372-0285e4ed-fd21-4f2b-8f57-653f52cca0a3.png)
columns 数组里面是名称，需求是选择后拿到名称对应的id，之前版本可以，新版本如何做

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by p697** [comment]
对应的 id 具体指什么呢？好像在你的代码里没有体现出来～

**Comment by awmleer** [comment]
#4375

**Comment by p697** [comment]
#4381
