### ISSUE TITLE
Picker 中 onSelect、onConfirm 相关

### ISSUE THREAD

**Issue by p697** [ant-design/ant-design-mobile#4368]
### Version of antd-mobile

latest

### Description

文档中描述，这两个回调函数都拥有第二个入参：`context`

![image](https://user-images.githubusercontent.com/51314472/141414834-3436f563-d52d-4058-bd14-8455ebbaa84a.png)

其类型为：

![image](https://user-images.githubusercontent.com/51314472/141415028-04367316-e9c0-4f5f-9921-e327c1d6ad37.png)

但当前实际的返回值全部都是：

![image](https://user-images.githubusercontent.com/51314472/141415302-fed9d0c8-6c5d-417d-8305-1a72c4ca63a8.png)

这可能是一个 bug。如果是 bug，那么这个参数的期望值是什么呢？是不是返回当前选择的这一列的所有值，即当前 `column` 的所有 `item`。

**Comment by p697** [comment]
刚刚翻到了 #4153，解决了我的困惑😅

**Comment by awmleer** [comment]
@p697 诶？现在 `context` 拿到的是空对象嘛？

**Comment by p697** [comment]
> @p697 诶？现在 `context` 拿到的是空对象嘛？

不完全是，可以说在没有 confirm 一个选项之前拿到的都是空的

**Comment by p697** [comment]
confirm 就是点右上角确定，确定一个选项

**Comment by awmleer** [comment]
噢噢我看到 PR 了 #4374
我来研究一下

**Comment by awmleer** [comment]
因为是 getter，所以 `console.log` 出来看起来是个空对象了，实际上展开是有 `items` 这个 getter 的

**Comment by p697** [comment]
> 因为是 getter，所以 `console.log` 出来看起来是个空对象了，实际上展开是有 `items` 这个 getter 的

这个我后来知道了hhh，我之后输出 onSelect 和 onConfirm 的 context 的时候遇到了其他的问题，感觉pr里讲的比较晦涩🙈

**Comment by p697** [comment]
大概就是，输出 context 还是不对劲，怎么都不对劲😂

**Comment by awmleer** [comment]
嗯嗯 get～ PR 里是另一个问题
