### ISSUE TITLE
List 中多余的边框

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#437]
<img width="931" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19680785/a506f980-9ad9-11e6-90e8-9d47d2c5a9f6.png">

当 List 里只有一项 ListItem 时，会有一条多余的边框。

**Comment by afc163** [comment]
又重现不了了。

**Comment by afc163** [comment]
https://mobile.ant.design/components/input-item

最后一项。

**Comment by warmhug** [comment]
目前只能手工覆盖样式，这个做法方便成本低

**Comment by afc163** [comment]
这算是样式 bug，不能让业务线来做修复。

**Comment by pingan1927** [comment]
我再研究下

**Comment by pingan1927** [comment]
https://github.com/ant-design/ant-design-mobile/commit/083b2156cec459b030f7a79536e028707a406150

**Comment by afc163** [comment]
`fix input-item last-child 1px border, close #437`

commit 信息最好关联 issue，这样既不需要手动关闭 issue，后续查找代码改动也容易看到原因。
