### ISSUE TITLE
Picker选择器无法滑动

### ISSUE THREAD

**Issue by PhoenixSlade** [ant-design/ant-design-mobile#4370]
### Version of antd-mobile

v5.0.0-beta.25

### What is this feature about?

按例子写了个demo
![image](https://user-images.githubusercontent.com/10954901/141424760-ee267239-25d4-4ad3-9247-3d4587758615.png)
效果如下:
![image](https://user-images.githubusercontent.com/10954901/141424655-c29c1eff-cd19-4130-ad12-41c379d3465f.png)
滑动的时候报如下错误
![image](https://user-images.githubusercontent.com/10954901/141424061-b804afa0-eb60-463e-bf21-27236d21daae.png)
调试时发现是
![image](https://user-images.githubusercontent.com/10954901/141424213-bfc73048-c5f4-42d0-9cfc-2ecb65b350ed.png)
中的index为 NAN, 请问如何解决，急!!!

React版本:
![image](https://user-images.githubusercontent.com/10954901/141425642-e9f3a425-ce0b-4305-8558-8e0ef7b45827.png)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by PhoenixSlade** [comment]
测试后发现，我的项目是运行在webpack5上的，降成4.x好像可以了
![image](https://user-images.githubusercontent.com/10954901/141714772-6b8046b8-d1e4-49e6-8d97-3eb3b35c2bd7.png)

**Comment by PhoenixSlade** [comment]
已确定原因，为按需加载的时候报错, 其中webpack5中babel使用如下:
![image](https://user-images.githubusercontent.com/10954901/141733141-bb7621c7-3f1d-4fb6-9b51-0356681c364c.png)

vite2.x如下:
![image](https://user-images.githubusercontent.com/10954901/141733179-55f4f713-921b-4224-993e-5bd9c364eb4c.png)

**Comment by PhoenixSlade** [comment]
另外, antd-mobile使用时，如何用Postcss把px转成lib-flexible对应的视口大小???

**Comment by awmleer** [comment]
@PhoenixSlade 你是手动做的按需加载？是严格按照这里的文档指引操作的么？https://mobile.ant.design/zh/guide/import-on-demand
有没有引入 `global` 文件？
```ts
import 'antd-mobile/es/global'
```

**Comment by PhoenixSlade** [comment]
> @PhoenixSlade 你是手动做的按需加载？是严格按照这里的文档指引操作的么？https://mobile.ant.design/zh/guide/import-on-demand 有没有引入 `global` 文件？
> 
> ```ts
> import 'antd-mobile/es/global'
> ```
babel按需加载啊

**Comment by awmleer** [comment]
@PhoenixSlade 你确定你完整地阅读了这篇文档……？

![image](https://user-images.githubusercontent.com/16526078/141743286-b70cb030-cbe8-45b8-9b07-23031e8618eb.png)

**Comment by awmleer** [comment]
我本地复现了这个问题，解法就是加一下：

```ts
import 'antd-mobile/es/global'
```

**Comment by PhoenixSlade** [comment]
> 我本地复现了这个问题，解法就是加一下：
> 
> ```ts
> import 'antd-mobile/es/global'
> ```
哥哥，我是用的babel-import-plugin, 结合babel使用的，你那种是手动引入的，这种按需每次引个组件都要到目录的，
![image](https://user-images.githubusercontent.com/10954901/142364147-ea2eba5e-35df-4d3f-889a-4743a6f84d4f.png)

**Comment by awmleer** [comment]
@PhoenixSlade 
![image](https://user-images.githubusercontent.com/16526078/142364303-d0ab8aae-d9b3-419b-89ca-fd1eb2f6dc76.png)

**Comment by awmleer** [comment]
😓请你把这个文档仔细看一下……
https://mobile.ant.design/zh/guide/import-on-demand

**Comment by PhoenixSlade** [comment]
> 😓请你把这个文档仔细看一下…… https://mobile.ant.design/zh/guide/import-on-demand

这文档写的，我以为是或关系的

**Comment by awmleer** [comment]
你自己文档都不读完整……这能怪文档么

**Comment by PhoenixSlade** [comment]
> > 😓请你把这个文档仔细看一下…… https://mobile.ant.design/zh/guide/import-on-demand
> 
> 这文档写的，我以为是或关系的
现在我改成手动按需引入的了，但有个问题，就是说我结合lib-flexible,通过postcss中的postcss-px-to-viewport想把px转rem或vw,以前2.x的时候视口大小是w: 320 h: 568，如果按这样配置的话，picker转换成的rem很小

**Comment by PhoenixSlade** [comment]
只能滑到这里了，下面下不去了
![image](https://user-images.githubusercontent.com/10954901/142365622-1522451c-a82d-41f5-bd15-6682824140f9.png)
![image](https://user-images.githubusercontent.com/10954901/142365561-5d38a446-f3f9-4feb-90fc-45b6f367334b.png)
![image](https://user-images.githubusercontent.com/10954901/142365694-d1538d85-4d37-4d2d-9cd7-b2120d93c932.png)

**Comment by awmleer** [comment]
统一在这里回复吧：https://github.com/ant-design/ant-design-mobile/issues/4389#issuecomment-972579310
