### ISSUE TITLE
ImageViewer组件，ios下，图片尺寸大时，放大后图片会模糊

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#4373]
### Version of antd-mobile

5.0.0-beta.26

### Operating system and its version

iOS

### Browser and its version

微信里网页

### What happened?

代码：

```
<ImageViewer.Multi
        images={['https://gd-filems.dancf.com/mcm79j/mcm79j/49603/81b69b6b-9108-4070-8fc1-64043c0fcddb1207580.jpg']}
        visible={visible}
        defaultIndex={1}
        onClose={() => {
          setVisible(false)
        }}
      />
```

ImageViewer组件，ios下，图片尺寸大时，放大后图片会模糊

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
的确可以复现

**Comment by awmleer** [comment]
codesandbox：https://codesandbox.io/s/summer-leftpad-g6n1n?file=/src/App.tsx

**Comment by awmleer** [comment]
直接通过 width height 设置 image 的大小就不会模糊了，推测是 Safari 出于性能考虑做的优化，后面我重构一下 ImageViewer 的实现方案

**Comment by awmleer** [comment]
感谢反馈，还提供了用来测试的数据

**Comment by awmleer** [comment]
已修复，预计下个 patch 版本发布
