### ISSUE TITLE
Picker 的 cols 建议可以从 data 中读出来

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#438]
如果都没有 children 就是 1。

**Comment by afc163** [comment]
应该直接利用 flex ，判断没有后面的数据时 dom 直接移除。

**Comment by warmhug** [comment]
这样会有两个问题：一是灵活性不够（数据要求严格）；二是随着 数据有没有 children 、 ui 展示上变化跳动显得不稳定、体验不够好。

**Comment by afc163** [comment]
ok，那先保持现状。
