### ISSUE TITLE
tab切换bug

### ISSUE THREAD

**Issue by NomadLau** [ant-design/ant-design-mobile#4382]
![image](https://user-images.githubusercontent.com/46842308/141889274-25d95638-f813-4fa1-afa4-bc27d568740f.png)
tab切换组件active状态，下划线位置不准确

**Comment by awmleer** [comment]
可以提供一下复现 demo 么：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by aaagan** [comment]
怀疑是复写了样式 设置了adm-tabs-tab-list 的 padding 值导致获取的位置不准确了，我这边也是因为这个问题导致偏移到后面了。

**Comment by gao-junfeng** [comment]
我也怀疑是复写的样式 而且很大程度上是因为使用了 `postcss-px-to-viewport` 造成的 转义后变成了vw属性  对原来的属性无疑是破坏性的 😢 
- #4389 看下我这个问题我感觉和你的问题差不多 在配置文件中去掉相应的css转换就可以了 🐌
