### ISSUE TITLE
postcss-px-to-viewport 使用转换后 出现DatePicker选择滚动错位

### ISSUE THREAD

**Issue by gao-junfeng** [ant-design/ant-design-mobile#4389]
### Description

- 正常
![image](https://user-images.githubusercontent.com/53894275/142090557-4722ebde-bfac-453b-b2c2-bdbd2c15705c.png)
![image](https://user-images.githubusercontent.com/53894275/142090639-754a4df2-872d-4dcb-876f-85edd5af77fa.png)
- 转换后 出现错误 height属性引起
![image](https://user-images.githubusercontent.com/53894275/142090732-56beb413-4180-4e53-a6a2-69869eb5fc72.png)
![image](https://user-images.githubusercontent.com/53894275/142090774-6504a9dd-7785-4c78-bffb-6527379ff6d0.png)
- 现有的解决方案是对此属性不进行转换
- config-overrides.js 不对该类名转换
![image](https://user-images.githubusercontent.com/53894275/142090891-1a71422c-6cf9-453b-a588-815080691607.png)

**Comment by gao-junfeng** [comment]
- 版本 5.0.0-beta.20
需要demo吗 ❓

**Comment by awmleer** [comment]
@gao-junfeng 嗯嗯如果能提供一个 demo 那最好了，可以很方便我们以及社区同学一起来帮你看看这个 bug

**Comment by gao-junfeng** [comment]
### 复现demo
- https://codesandbox.io/s/upbeat-matsumoto-zwgnc?file=/config-overrides.js&resolutionWidth=320&resolutionHeight=675
- 没找到 `"react-app-rewired": "^2.1.6"` 这个插件无法改变webpack的配置  `
- adm-picker-view-column-item` 这个属性height 从px 变成vm 后出现问题

**Comment by PhoenixSlade** [comment]
我这直接用lib-flexible, 再结合 postcss中的postcss-px-to-viewport设置px转rem或vw，直接错位, antd-mobile 2.x版本可以设置视口大小320/568, 如果直接用这个直接错位，滚不到最下面，服了
![image](https://user-images.githubusercontent.com/10954901/142363330-d63fa5ff-9a83-4b04-9bc6-cd8e21520a0a.png)

**Comment by awmleer** [comment]
看起来是这个导致的：
<img width="594" alt="image" src="https://user-images.githubusercontent.com/16526078/142364647-2a07de3d-f671-4b05-9706-6b45189156ee.png">

**Comment by awmleer** [comment]
我稍微调整一下吧，现在很多人都对 `1px` 选择了特殊的放过逻辑

**Comment by awmleer** [comment]
7d0a46752

**Comment by PhoenixSlade** [comment]
> [7d0a467](https://github.com/ant-design/ant-design-mobile/commit/7d0a4675223229d13c28151e95b25110661b4837)

我现在需要升级到最新版本你的代码才能生效吗？

**Comment by awmleer** [comment]
等我发布一下

**Comment by awmleer** [comment]
@PhoenixSlade 升级到 5.0.0-beta.27 试一下吧

**Comment by PhoenixSlade** [comment]
> 等我发布一下

好的，我先试试
