### ISSUE TITLE
有没有关于antd-mobile的CDN？

### ISSUE THREAD

**Issue by raoenhui** [ant-design/ant-design-mobile#439]
#### 本地环境

- antd-mobile 版本：0.9.4
- 操作系统及其版本：W7
- 浏览器及其版本：chrome
#### 你做了什么？

想找到关于antd-mobile的CDN
#### 你期待的结果是：

如antd的web端有cdn：//cdn.bootcss.com/antd/2.0.1/antd.min.js
#### 实际上的结果：

没有找到关于antd-mobile的CDN

**Comment by silentcloud** [comment]
你可以拿 dist 后的去传一份

**Comment by raoenhui** [comment]
传到哪个cdn网站上去，我可以以个人身份上传吗

**Comment by silentcloud** [comment]
@raoenhui 比如这里 https://cdnjs.com/

**Comment by afc163** [comment]
@raoenhui 可以去给 cdnjs PR：https://github.com/cdnjs/cdnjs/pull/8047
