### ISSUE TITLE
ImageUpload  preview the same file cause Unique key error

### ISSUE THREAD

**Issue by anysunflower** [ant-design/ant-design-mobile#4390]
### Version of antd-mobile

5.0.0-beta.26

### Operating system and its version

Others

### Browser and its version

chrome 96.0.4664.45

### What happened?

ImageUpload initial value with two item which display the same picture throw Unique key error

code

```
    const value = [{
        url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    }, {
        url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
    }]
<ImageUploader
                    accept="image/gif,image/jpeg,image/jpg,image/png"
                    maxCount={2}
                    value={value}
                    onChange={props.onChange}
                    upload={uploadFile}
                    // onDelete={props.onChange}
                />
```

ImageUpload如果初始值当中两个图片URL一样，会报key重复的错误，由此附加的错误是，并且maxCount为多个的时候，上传三个图片之后，如果有图片地址一样，删除一个图片之后，就可以一直继续上传，并不能限制上传个数。

如果根因是因为，previewItem的key指定为图片的URL，感觉还是应该另外指定，如果是初始化图片数据，是存在list当中有重复展示的图片

### Relevant log output

```shell
Encountered two children with the same key, ``. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at div
    at Space
    at div
    at ImageUploader
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gao-junfeng** [comment]
### 复现demo
- https://codesandbox.io/s/upbeat-matsumoto-zwgnc?file=/config-overrides.js&resolutionWidth=320&resolutionHeight=675
- 没找到 `"react-app-rewired": "^2.1.6"` 这个插件无法改变webpack的配置  `
- adm-picker-view-column-item` 这个属性height 从px 变成vm 后出现问题

**Comment by awmleer** [comment]
支持了用户自己配置 key： 0a3fa2e14
