### ISSUE TITLE
virtual-input.css warn: start value has mixed support, consider using flex-start instead

### ISSUE THREAD

**Issue by ryozm** [ant-design/ant-design-mobile#4391]
### Version of antd-mobile

5.0.0-beta26

### What happened?

![image](https://user-images.githubusercontent.com/22736296/142149880-3ad8cede-f682-4675-8e8b-76e39cd93ca4.png)
Warning when running the project

` justify-content: start;`
=>
`justify-content: flex-start;`

### Relevant log output

```shell
./node_modules/antd-mobile-v5/es/components/virtual-input/virtual-input.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/antd-mobile-v5/es/components/virtual-input/virtual-input.css)
Warning

(10:3) start value has mixed support, consider using flex-start instead
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ryozm** [comment]
![企业微信20211117-150547](https://user-images.githubusercontent.com/22736296/142150553-c1e2d685-3d6d-4468-826b-9f45516d1520.png)

**Comment by awmleer** [comment]
已经在 0f37ea177 中修复了，还没发布
