### ISSUE TITLE
VirtualInput 初始光标位置不能右对齐

### ISSUE THREAD

**Issue by faremax** [ant-design/ant-design-mobile#4393]
### Version of antd-mobile

5.0.0-beta.26

### Operating system and its version

iOS

### Browser and its version

iphone13 pro max simulator

### What happened?

2个问题：

1. 输入框文字右对齐时，初始光标出现在了最左边，期望出现在最右边；
2.  使用 <ref>.focus() 聚焦时，没有出现光标；

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faremax** [comment]
新增BUG：调整输入框高度后，光标高度不能跟随变高

**Comment by awmleer** [comment]
> 新增BUG：调整输入框高度后，光标高度不能跟随变高

现在的光标高度是跟随 `font-size` 变化的……这个其实也算是预期行为

**Comment by awmleer** [comment]
Close via d6c732122.

下个版本发布
