### ISSUE TITLE
Attempted import error: 'NavBar' is not exported from 'antd-mobile'.

### ISSUE THREAD

**Issue by bostonlf** [ant-design/ant-design-mobile#4397]
### Description

I copied code from the example of this page
https://mobile.ant.design/zh/components/tab-bar
but , this error MSG displays after I start my app
how can I fix this issue?

![image](https://user-images.githubusercontent.com/11455688/142209875-0e3e7a8e-524e-4623-886f-1098ba7a34d9.png)

**Comment by awmleer** [comment]
可以提供一下你的 antd-mobile 的版本号么？
