### ISSUE TITLE
Uncaught TypeError: column.map is not a function

### ISSUE THREAD

**Issue by milsevol** [ant-design/ant-design-mobile#4399]
### Description

Picker组件的columns属性，取下面的IdCardTypesColumns 值
`export const IdCardTypes = [{
    text: '身份证', value: '0'
}, {
    text: '中国护照', value: '1'
}, {
    text: '港澳居民来往内地通行证', value: '4'
}, {
    text: '台胞证', value: 'A'
}];

const IdCardTypesColumns = IdCardTypes.map((x: any) => {
    return x.text
})`
报了Uncaught TypeError: column.map is not a function错误，不能动态获取？

**Comment by milsevol** [comment]
搞错了，应该这样写
`const IdCardTypesColumns = [IdCardTypes.map((x: any) => {
    return x.text
})]`

**Comment by awmleer** [comment]
是的，`columns` 是二维数组
