### ISSUE TITLE
构建体积很大

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design-mobile#44]
官网文档有写
构建后总体积：~110KB

但我们实际按需构建后，css有缩小了，但js还有400kb。

**Comment by dyf2015** [comment]
gzip后勉强压缩到100kb，在移动端确实过大了。

**Comment by dyf2015** [comment]
官网说明的构建体积是gzip之后的吗？

**Comment by warmhug** [comment]
官网说的是 amr 文件体积

**Comment by warmhug** [comment]
https://github.com/ant-design/ant-design-mobile#use-babel-plugin-antd

**Comment by dyf2015** [comment]
啥是amr

发自我的 iPhone

在 2016年8月5日，17:45，warmhug <notifications@github.com<mailto:notifications@github.com>> 写道：


官网说的是 amr 文件体积

―

**Comment by dyf2015** [comment]
是不是我没做这个处理导致？

Set webpack to resolve .web.js suffix

发自我的 iPhone

在 2016年8月5日，17:46，warmhug <notifications@github.com<mailto:notifications@github.com>> 写道：


https://github.com/ant-design/ant-design-mobile#use-babel-plugin-antd

―

**Comment by dyf2015** [comment]
采用
import 'antd-mobile/lib/button/style';
import Button from 'antd-mobile/lib/button';
方式

Set webpack to resolve .web.js suffix

大小没改变。。

**Comment by warmhug** [comment]
确认下构建后文件里，是不是只有你引入的组件代码，其他未引入的组件代码不应该包含进来

**Comment by dyf2015** [comment]
是的，只有用到的组件。。

发自我的 iPhone

在 2016年8月5日，20:13，warmhug <notifications@github.com<mailto:notifications@github.com>> 写道：


确认下构建后文件里，是不是只有你引入的组件代码，其他未引入的组件代码不应该包含进来

―

**Comment by warmhug** [comment]
公共依赖（如 react ）要单独拿出去，只保留组件的js，还有这么大吗？引入了多少个组件？

**Comment by dyf2015** [comment]
react有踢出，引入了大概8个组件，400kb，样式也有踢出。

**Comment by dyf2015** [comment]
单独测试了下 ，table就占了20kb。。

**Comment by dyf2015** [comment]
css很小，js非常大，感觉和pc antd端的差不多大。。

**Comment by warmhug** [comment]
好的，我先仔细测试下、再给你反馈

**Comment by dyf2015** [comment]
感谢，希望可以逐步缩小，毕竟移动端阉割了很多功能。

**Comment by dyf2015** [comment]
经过测试这些组件压缩后总共176kb

import Menu from 'antd-mobile/lib/menu'
import'antd-mobile/lib/menu/style'
import Grid from 'antd-mobile/lib/grid'
import'antd-mobile/lib/grid/style'
import Button from 'antd-mobile/lib/button'
import'antd-mobile/lib/button/style'
import ActivityIndicator from 'antd-mobile/lib/activity-indicator'
import'antd-mobile/lib/activity-indicator/style'
import NavBar from 'antd-mobile/lib/nav-bar'
import'antd-mobile/lib/nav-bar/style'
import Icon from 'antd-mobile/lib/icon'
import'antd-mobile/lib/icon/style'
import RefreshControl from 'antd-mobile/lib/refresh-control'
import'antd-mobile/lib/refresh-control/style'
import SearchBar from 'antd-mobile/lib/search-bar'
import 'antd-mobile/lib/search-bar/style'
import Tabs from 'antd-mobile/lib/tabs'
import'antd-mobile/lib/tabs/style'
import Timeline from 'antd-mobile/lib/timeline'
import'antd-mobile/lib/timeline/style'
import Steps from 'antd-mobile/lib/steps'
import'antd-mobile/lib/steps/style'
import Carousel from 'antd-mobile/lib/carousel'
import'antd-mobile/lib/carousel/style'
import Table from 'antd-mobile/lib/table'
import'antd-mobile/lib/table/style'

**Comment by warmhug** [comment]
我试试，确实有这么大，很多是 es6 到 es5 的支持代码，欢迎探索更优化的 babel 编译方法

**Comment by warmhug** [comment]
https://github.com/ant-design/ant-design/issues/2656
