### ISSUE TITLE
希望 DatePicker 增加精度选项 'week'

### ISSUE THREAD

**Issue by GOWxx** [ant-design/ant-design-mobile#4406]
### Version of antd-mobile

v5.0.0-beta.27

### What is this feature about?

目前的 DatePicker 精度 precision 的值没有 'week'
希望增加 周 的选项
期望如下：
![datePicker周](https://user-images.githubusercontent.com/12870715/142586313-254a9487-add8-448e-a305-c34141868fbe.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
已支持
