### ISSUE TITLE
The px tester is not rendering properly. Please make sure you have imported `antd-mobile/es/global`.

### ISSUE THREAD

**Issue by Z-LianYan** [ant-design/ant-design-mobile#4407]
### Version of antd-mobile

5.0.0-beta.27

### Description

这是什么原因
The px tester is not rendering properly. Please make sure you have imported `antd-mobile/es/global`.

**Comment by awmleer** [comment]
就是报错的意思，你是不是自己搞的手动的按需加载？
请**仔细**读一下这篇文档哈（不要略过任何一句）：https://mobile.ant.design/zh/guide/import-on-demand

**Comment by Z-LianYan** [comment]
之前5.0.0-beta.22的时候是没问题的后来升级了，就有这个报错了。再安装回5.0.0-beta.22也是这样

**Comment by awmleer** [comment]
@Z-LianYan 先确认一下，上面发的这篇文档你有仔细读过么？

**Comment by awmleer** [comment]
你遇到的这个报错，是我们故意加上的，是为了提示用户，避免错误地使用 antd-mobile

**Comment by Z-LianYan** [comment]
已经仔细读过文档了，迫症看到错误就想干掉它，不能把它去掉嚒

**Comment by awmleer** [comment]
这个错误说明你用法有问题的……😓如果你用法正常的话，是不会有这个报错的

请你先回答一下上面刚刚提到的这两个问题，我们才能帮你排查是什么情况：
- 你是否在项目引入了 `antd-mobile/es/global` 这个文件？
- 你是否使用了 babel-plugin-import 等插件，或者是做了手动的按需加载？

顺便再问一下：

- 能不能把构建出来的 html 文件贴一份上来？怀疑是如果 script 标签被插入到 head 中，也是可能会导致这个问题

**Comment by Z-LianYan** [comment]
import "antd-mobile/es/global"; //在入口文件中引入的 global

在.babelrc 中配置
{
    "presets": [
        "react-app"
    ],
    "plugins": [
        ["import", { "libraryName": "antd-mobile", "libraryDirectory": "es/components", "style": false}]
    ]
}

以下是构建出来的html

<html lang="en" style="font-size:100px">

<head>
  <meta charset="utf-8" />
  <link rel="icon" href="http://baidu.com/20200911182118789.jpeg" />
  <meta name="theme-color" content="#000000" />
  <meta name="description" content="Web site created using create-react-app" />
  <meta name="viewport"
    content="viewport-fit=cover,width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1" />
  <link rel="stylesheet" href="//at.alicdn.com/t/font_1778027_ytw9zbu8heg.css" />
  <title>React App</title>
  <script src="https://webapi.amap.com/maps?v=2.0&key=777777777777&plugin=AMap.CitySearch"></script>
  <link href="/static/css/2.d4f7b6bc.chunk.css" rel="stylesheet">
  <link href="/static/css/main.46354d87.chunk.css" rel="stylesheet">
</head>

<body><noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
  <script>!function (e) { function t(t) {  }}([])</script>
  <script src="/static/js/2.ae8a0105.chunk.js"></script>
  <script src="/static/js/main.6aa24695.chunk.js"></script>
</body>
<style>
  :root {
    --adm-color-primary: #ff5f16;
    --adm-color-success: #00b578;
    --adm-color-warning: #ff8f1f;
    --adm-color-danger: #ff3141;
    --adm-color-white: #ffffff;
    --adm-color-weak: #999999;
    --adm-color-light: #cccccc;
    --adm-border-color: #eeeeee;
    --adm-font-size-main: 13px;
    --adm-color-text: #333333;
    --adm-font-family: -apple-system, blinkmacsystemfont, 'Helvetica Neue', helvetica, segoe ui, arial, roboto, 'PingFang SC', 'miui', 'Hiragino Sans GB', 'Microsoft Yahei', sans-serif;
    --adm-z-index-mask: 1000;
    --adm-z-index-popup: 1000;
    --adm-z-index-popover: 1030;
    --adm-z-index-floating-panel: 900
  }
</style>

</html>

**Comment by lijicheng123** [comment]
我也遇到了同样的问题，我debugger发现这个问题主要是因为px tester引起的，代码在这里：
https://github.com/ant-design/ant-design-mobile/blob/8a3f426aadb07b4f3d9727f7db569cba88763dbf/src/utils/convert-px.ts#L16
调试的时候发现是js先执行，css还没有准备好，导致position的判断不是fixed，所以我在项目入口处就先导入这个global的css，就解决了

```
import './../node_modules/antd-mobile/es/global/global.css'
import App from './App.tsx'
import './index.scss'
```
