### ISSUE TITLE
tabs 组件报错

### ISSUE THREAD

**Issue by Z-LianYan** [ant-design/ant-design-mobile#4409]
### Version of antd-mobile

5.0.0-beta.27

### Description

index.js:1 Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by awmleer** [comment]
这个报错啥都看不出来……看起来你是引入错组件了
给个复现 demo 吧：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by Z-LianYan** [comment]
import React from "react";
import { Tabs } from "antd-mobile";

export default function App() {
  return (
    <Tabs
      defaultActiveKey={"hot"}
      onChange={(val) => {
        console.log("123");
      }}
    >
      <Tabs.TabPane title="title1" key="hot" />
      <Tabs.TabPane title="title2" key="soon" />
    </Tabs>
  );
}



重新看了下文档 Tabs.TabPane 弄错了，升了级连以前 5.0.0-beta.22版本都变了用 Tabs.Tab；
......

**Comment by awmleer** [comment]
旧版本是没有变的，新版才改成的 `Tabs.Tab`，至于你说的影响到了旧版本，怀疑是你自己安装版本没装对，例如你在 package.json 里写 `^5.0.0-beta.22` 实际并不会安装 `beta.22` 版本，而是装的最新的符合 `^` 的范围的版本

有三个小建议：
1. 文档站点有时候有缓存，需要强制刷新一下页面才能看到最新的，这个先麻烦你临时刷新下哈，后面我们想办法解决一下
2. 每次升级 antd-mobile 依赖版本的时候阅读一下[发布日志](https://github.com/ant-design/ant-design-mobile/releases)，需要特别留意其中标了 ⚠️ 的地方
3. 了解一下 npm 的 semver 相关的资料，了解一下怎么去查看自己项目中指定依赖当前被安装的准确版本
