### ISSUE TITLE
PullToRefresh 在ios12mini 上有抖动问题

### ISSUE THREAD

**Issue by Remaineey** [ant-design/ant-design-mobile#4410]
### Version of antd-mobile

5.0.0-beta.26

### Operating system and its version

iOS

### Browser and its version

12mini

### What happened?

下拉时会抖动

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
12mini？你是说 iOS 12 还是 iPhone 12 mini？

**Comment by Remaineey** [comment]
iPhone 12 mini

 

 

发件人: ***@***.***> 代表 卡晨 ***@***.***>
答复: ant-design/ant-design-mobile ***@***.***>
日期: 2021年11月22日 星期一 下午12:21
收件人: ant-design/ant-design-mobile ***@***.***>
抄送: Remaineey ***@***.***>, Author ***@***.***>
主题: Re: [ant-design/ant-design-mobile] PullToRefresh 在ios12mini 上有抖动问题 (Issue #4410)

 

12mini？你是说 iOS 12 还是 iPhone 12 mini？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by awmleer** [comment]
@Remaineey 可以录个视频么？以及，iOS 的版本号是多少？

**Comment by awmleer** [comment]
@Remaineey 是官网的文档上的 demo 就可以复现么？如果不是的话，需要提供一个复现 demo 哈：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by Remaineey** [comment]
是按照官网的demo上来的，即使只是给内容设置了高，不给刷新的回调，下拉还是会抖动
ios版本是 14.3
视频我晚点发一下

**Comment by Remaineey** [comment]
是在native开发中，webview容器中出现的

**Comment by Remaineey** [comment]
@awmleer ios版本 14.3 

视频地址： https://s3-cxyx-cdn.didistatic.com/basic-material/87497c17aa0444b3ab78a1d666957d6f.mp4

 

发件人: ***@***.***> 代表 卡晨 ***@***.***>
答复: ant-design/ant-design-mobile ***@***.***>
日期: 2021年11月22日 星期一 下午2:37
收件人: ant-design/ant-design-mobile ***@***.***>
抄送: Remaineey ***@***.***>, Mention ***@***.***>
主题: Re: [ant-design/ant-design-mobile] PullToRefresh 在ios12mini 上有抖动问题 (Issue #4410)

 

@Remaineey 可以录个视频么？以及，iOS 的版本号是多少？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Remaineey** [comment]
@awmleer  可以看到视频吗

**Comment by awmleer** [comment]
@Remaineey 看到了，sorry 昨天有点忙，没顾上看这个问题

这个看起来是 webview 容器的问题，你有没有办法尝试关闭掉这个 webview 容器的弹性效果？

**Comment by awmleer** [comment]
应该是同时触发了 PullToRefresh 的下拉逻辑和浏览器原生的下拉逻辑，所以关键就在于要把浏览器默认的弹性下拉行为禁用掉
