### ISSUE TITLE
PullToRefresh组件 可以通过按钮点击触犯onRefresh吗

### ISSUE THREAD

**Issue by Z-LianYan** [ant-design/ant-design-mobile#4412]
### Version of antd-mobile

5.0.0-beta.27

**Comment by awmleer** [comment]
不支持的。按钮点击刷新的话，为何不自己直接调用 refresh 的逻辑？何必让 PullToRefresh 来中转一下？

**Comment by Z-LianYan** [comment]
建议把 PullToRefresh 组件改成能拿到它的实例的组件，这样可以灵活使用

**Comment by awmleer** [comment]
加 Ref 么？那你希望 Ref 上有哪些方法/属性呢？可以具体说一下不？
