### ISSUE TITLE
[RFC] FloatingBubble

### ISSUE THREAD

**Issue by JasonYan2015** [ant-design/ant-design-mobile#4413]
## 浮动提示组件

距离屏幕左/右边距固定，可上下拖动，自定义点击操作，比如跳转新页面等
> 未来可支持隐藏，以及任意拖动之类的能力

### 属性

| 属性 | 描述 | 类型 | 默认值 |
| -- | -- | -- | -- |
| children | 内容区域 | ReactNode | - |

### CSS 变量

| 变量名 | 描述 | 默认值 |
| -- | -- | -- |
| --initial-position-left | 初始状态组件距离屏幕左边的距离 | - |
| --initial-position-right | 初始状态组件距离屏幕左边的距离 | - |
| --initial-position-top | 初始状态组件距离屏幕上边的距离 | - |
| --initial-position-bottom | 初始状态组件距离屏幕下边的距离 | - |
> --initial-position-top 和 --initial-position-bottom 在使用时必填其中一项
> --initial-position-left 和 --initial-position-right 在使用时必填其中一项，且组件拖拽时会固定这个左/右边距来拖拽

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
#4417
