### ISSUE TITLE
npm的版本必须是0.9.4吗？

### ISSUE THREAD

**Issue by feilongOnMoudu** [ant-design/ant-design-mobile#442]
#### 

- antd-mobile 版本：0.9.4
- 操作系统及其版本：mac
- 浏览器及其版本：谷歌
#### 我用的node.js版本为v4.4.4

npm 版本为2.15.1
引入组件后就报错
<img width="311" alt="ee75cc58-2a09-4af0-ab63-b18da6a6bb58" src="https://cloud.githubusercontent.com/assets/16435428/19720929/c684d2ac-9ba2-11e6-93aa-5e5a1306fdbc.png">

安装上面的操作做完还是不行，是版本的原因还是什么啊

**Comment by silentcloud** [comment]
用 npm3
