### ISSUE TITLE
switch组件onchange都被改成了异步执行了，现在切换不了，官网上也是这样，麻烦修改一下

### ISSUE THREAD

**Issue by 1092624539Zz** [ant-design/ant-design-mobile#4420]
### Version of antd-mobile

v5.0.0-beta.30

### What happened?

switch组件onchange都被改成了异步执行了，现在切换不了，官网上也是这样，麻烦修改一下

### Relevant log output

```shell
switch组件onchange都被改成了异步执行了，现在切换不了，官网上也是这样，麻烦修改一下
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
马上发个版本哈，非常感谢反馈

**Comment by awmleer** [comment]
5.0.0-beta.31
