### ISSUE TITLE
ImageView组件侧滑切换图片需要touchMove的距离太大了

### ISSUE THREAD

**Issue by Yixeu** [ant-design/ant-design-mobile#4422]
如题。侧滑切换图片需要touchmove 很大的量才能切换。希望能开放API

**Comment by awmleer** [comment]
ImageView？你是说 ImageViewer？
BTW，提供一下你正在使用的 antd-mobile 的版本号？

**Comment by Yixeu** [comment]
5.0.0-beta.20 ，麻烦好哥哥看下

**Comment by sRect** [comment]
还有，安卓手机，钉钉App微应用内，ImageViewer双指图片放大，体验贼差，图片都不听使唤了

**Comment by awmleer** [comment]
> 还有，安卓手机，钉钉App微应用内，ImageViewer双指图片放大，体验贼差，图片都不听使唤了

哈？求录个屏

**Comment by sRect** [comment]
> > 还有，安卓手机，钉钉App微应用内，ImageViewer双指图片放大，体验贼差，图片都不听使唤了
> 
> 哈？求录个屏

公司docker推送有异常，导致线上不是最新版本。修复后，就好了。图片没有不听使唤，正常了。

但是ImageViewer的图片放大后能把图片移出手机可视区外，这样体验不好，类似钉钉的dd.biz.util.previewImage这个api，图片放大后不把图片移出可视区外，就好了

**Comment by awmleer** [comment]
> 但是ImageViewer的图片放大后能把图片移出手机可视区外，这样体验不好，类似钉钉的dd.biz.util.previewImage这个api，图片放大后不把图片移出可视区外，就好了

嗯嗯是的，这个是已知的体验问题，后面我们会优化的

**Comment by awmleer** [comment]
那 issue 我关闭掉了
