### ISSUE TITLE
[IndexBar]：当 IndexBar.Panel 的 index 字符过多时 sidebar 的样式展示是否需要优化

### ISSUE THREAD

**Issue by GOWxx** [ant-design/ant-design-mobile#4425]
### Version of antd-mobile

v5.0.0-beta.31

### What is this feature about?

基于官网demo，修改了 index 的长度
https://codesandbox.io/s/zealous-mclean-0dpm0?file=/src/indexbox.tsx
效果如下

indexbarIndex为汉字：
![indexbarIndex为汉字](https://user-images.githubusercontent.com/12870715/143392807-4fd2af21-459f-43a1-925d-ac2c5fc3648b.png)

indexbarIndex字符过长：
![indexbarIndex字符过长](https://user-images.githubusercontent.com/12870715/143392830-f0471107-f8dc-47f6-8882-707b728fe202.png)

被选中的项限制了宽度，可能展示不全或错位

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
通过 #4450 解决了
