### ISSUE TITLE
[Ellipsis] 尾部省略、中间省略、头部省略 只有省略号

### ISSUE THREAD

**Issue by GOWxx** [ant-design/ant-design-mobile#4428]
### Version of antd-mobile

v5.0.0-beta.30

### Operating system and its version

Others

### Browser and its version

win10 chrome V96 模拟移动端设备

### Sandbox to reproduce

https://codesandbox.io/s/competent-bird-h8ykq?file=/src/ellipsis.tsx

### What happened?

Ellipsis组件 尾部省略、中间省略、头部省略 只有省略
![ellipsis](https://user-images.githubusercontent.com/12870715/143407624-9ef1ba53-d7d3-4b53-b617-c241446ba42d.png)
号

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
Fixed via 4a0eae983
