### ISSUE TITLE
Tabs里面的TabPane怎么才能滑动

### ISSUE THREAD

**Issue by 1610449813** [ant-design/ant-design-mobile#443]
#### 本地环境

- antd-mobile 版本：0.9.3 react-native
- 操作系统及其版本：android
- 浏览器及其版本：
#### 你做了什么？

 引入 antd-mobile 的 Tabs
#### 你期待的结果是：

 tabs里面的内容可以滑动

**Comment by silentcloud** [comment]
内容还是 title 那块？内容的话 swipeable 属性，title 那块的话目前不支持，下一个大版本计划

**Comment by silentcloud** [comment]
链接到这 https://github.com/ant-design/ant-design-mobile/issues/394，此 issue 关闭
