### ISSUE TITLE
Search组件 ios设备下 软键盘没有显示“搜索”文字。目前显示换行

### ISSUE THREAD

**Issue by wangyong315** [ant-design/ant-design-mobile#4435]
### Version of antd-mobile

5.0.0-beta.31

### Operating system and its version

iOS

### Browser and its version

iOS safari  系统版本14.8

### Sandbox to reproduce

https://codesandbox.io/s/brave-christian-li7m6?file=/src/App.tsx

### What happened?

![7CC54548-2467-4B8E-B9D2-21BCA0ECE8FB](https://user-images.githubusercontent.com/27543698/143533476-2ca709cc-86f5-4d14-96d2-9455811f1a49.png)

手机端展示如图所示

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
Close via #4455.
