### ISSUE TITLE
icon图标鼠标houer时显示了默认title

### ISSUE THREAD

**Issue by darkmice** [ant-design/ant-design-mobile#4436]
### Version of antd-mobile

所有版本

### Browser and its version

all

### Sandbox to reproduce

https://mobile.ant.design/zh/components/icon

### What happened?

[[官方]()](https://mobile.ant.design/zh/components/icon)  鼠标移动图标上，就能看到效果

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xiaohuoni** [comment]
啥意思？我这里只显示文件名称？

**Comment by awmleer** [comment]
贴一下，icons 是在另一个仓库：
https://github.com/awmleer/antd-mobile-icons

**Comment by awmleer** [comment]
这个可能要后面再改了，现在 icons 没有原始的 svg 文件，要等之后上游的工具链解决

**Comment by awmleer** [comment]
2262837 fixed
