### ISSUE TITLE
ImageView 图片预览做放大手势后无法侧滑图片切换

### ISSUE THREAD

**Issue by Yixeu** [ant-design/ant-design-mobile#4437]
### Version of antd-mobile

5.0.0-beta.20

### Browser and its version

企业微信浏览器

### What happened?

ImageView 组件 图片预览 做放大手势后 无法再侧滑切换预览图片

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
这个其实不算 bug，是目前的预期行为，后面可以优化一下

**Comment by awmleer** [comment]
BTW，是 ImageViewer 不是 ImageView，表述还是要严谨一些哈

**Comment by Yixeu** [comment]
好的。但是我认为放大手势无效可以接受，但是不能做了放大手势再无法滑动切换图片

**Comment by Yixeu** [comment]
好的。我认为放大手势无效可以接受，但是不能做了放大手势后无法滑动切换图片。您能理解我的意思嘛，问题出在无法滑动切换图片了

**Comment by awmleer** [comment]
你是说现在图片放大之后，就不能滑动切换到下一张或者上一张了是么？

**Comment by Yixeu** [comment]
对的

**Comment by awmleer** [comment]
和 #4437 重复了，这个 issue 先关闭了，后面可以继续关注 #4437 哈
