### ISSUE TITLE
InputItem clear property now work when different between ssr and csr.

### ISSUE THREAD

**Issue by taoliujun** [ant-design/ant-design-mobile#4438]
### Version of antd-mobile

2.3.4

### Operating system and its version

Others

### Browser and its version

chrome

### What happened?

The 2.x source for InputItem was:
![image](https://user-images.githubusercontent.com/5689134/143547322-79dd30d0-9b28-4968-a03b-dff6283c365e.png)

clear node was overrided by extra node in browser like:
![image](https://user-images.githubusercontent.com/5689134/143547490-73e82215-31d7-4579-bca6-84e49370f104.png)

i think that the condition for clear was false in ssr because value was empty, but was true in csr. because value was not empty.
why clear node was overrided by extra node, I think that no key for them.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by taoliujun** [comment]
> 

v5 beta中，怎么升

**Comment by awmleer** [comment]
v5 提供了 Input List Form 组件，可以组合起来使用，具体可以参考文档中 Input 的例子
