### ISSUE TITLE
input 组件接受 undefined

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#444]
现象：
https://mobile.ant.design/components/list/#components-list-demo-form
![image](https://cloud.githubusercontent.com/assets/2011119/19727495/3bfe1e52-9bc2-11e6-8578-d35cb15fc954.png)
输入密码、控制台报错(开发环境)，而且不能 重置 这个密码框。

代码这样判断有问题
![image](https://cloud.githubusercontent.com/assets/2011119/19727439/071c611c-9bc2-11e6-9dbd-82b5dd02d30a.png)

涉及 InputItem / TextareaItem 组件

**Comment by pingan1927** [comment]
@yiminghe this.props.form.resetFields();  重置的意思是啥？恢复到默认值吗？
