### ISSUE TITLE
Ellipsis 文本省略 组件单行文本超出省略有 bug，没发正常显示出文案

### ISSUE THREAD

**Issue by Xiaolong145682** [ant-design/ant-design-mobile#4445]
### Version of antd-mobile

5.0.0-rc.0

### Operating system and its version

iOS, Android, Others

### Sandbox to reproduce

https://codesandbox.io/embed/awesome-panka-og2xz?fontsize=14&hidenavigation=1&theme=dark

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xiaolong145682** [comment]
5.0.0-rc.0 最新版 fork 到本地，发现是正常显示的，可能是打包环境出问题了

**Comment by GOWxx** [comment]
> 5.0.0-rc.0 最新版 fork 到本地，发现是正常显示的，可能是打包环境出问题了

这个bug已经修复了

在这之前提过 issue https://github.com/ant-design/ant-design-mobile/issues/4428
然后卡神修复了这个bug Fixed via 4a0eae9

所以现在拉 5.0.0-rc.0 最新版到本地的话是没问题的

**Comment by iamzhoufei** [comment]
![image](https://user-images.githubusercontent.com/81286048/143726672-69c1dc52-d0c7-4576-a639-f0d8e97fb1e5.png)
官网的示例好像还是展示不正确

**Comment by awmleer** [comment]
已经修复了，还没发布哈，rc.1 发

**Comment by Xiaolong145682** [comment]
👌
