### ISSUE TITLE
请教一下关于Picker组件, 切换浏览器的tab标签, Picker会加一层是为什么?

### ISSUE THREAD

**Issue by cheng-xiaofeng** [ant-design/ant-design-mobile#4446]
### Description

![image](https://user-images.githubusercontent.com/33592850/143671690-f466a112-4198-4d45-ab9d-96a7605ae092.png)

**Comment by awmleer** [comment]
感觉是你自己逻辑实现的问题，提供一个复现 demo 吧：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx
