### ISSUE TITLE
在tabs组件中使用collapse会导致tab切换时下划线失去动画效果

### ISSUE THREAD

**Issue by iamzhoufei** [ant-design/ant-design-mobile#4448]
### Version of antd-mobile

5.0.0-rc.0

### Operating system and its version

iOS, Android

### Browser and its version

Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1

### Sandbox to reproduce

https://codesandbox.io/s/intelligent-lehmann-3sf4k?file=/src/App.tsx

### What happened?

在tabs组件中使用collapse组件会导致tab切换时下划线失去动画效果，移除collapse组件则正常展示

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
Fixed via #4449
