### ISSUE TITLE
IndexBar 支持分别控制列表分组标题和按下的气泡内展示的内容

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#4450]
初步的思路是，增加 `briefTitle` 属性，和 `title` 配合使用：

- 这两个属性都是可以缺省的，`title` 默认取 `index`，`briefTitle` 默认取 `index` 的第一个字符
- `briefTitle` 和 `title` 都支持 ReactNode
- 边栏中的小字不支持多个字，固定形状一定是正圆形，超出的部分 overflow hidden

**Comment by p697** [comment]
有一个小问题，在提示的气泡里是展示 index 还是 title 比较好呢

比如这个 Icon 的例子：
```js
{
  index: 'star',
  briefTitle: <StarOutline />,
  title: '标星朋友',
}
```
展示在侧边栏里的就是一个 Star 的 Icon，这时提示气泡貌似是 `title` 更好

但这样的话对于多数简单的情况又不太适用，气泡提示可能变为 “标题A” 而不是 “A”

或许可以再加一个 API：
```js
bubbleContent: 'index' | 'title' | 'briefTitle'
```
让用户可以指定气泡里展示的内容

**Comment by awmleer** [comment]
我比较倾向于：气泡里和边栏小字都展示 briefTitle，左边内容区展示 title

为了避免用户搞混淆，也可以考虑把 briefTitle 直接改成叫 brief

**Comment by awmleer** [comment]
我觉得从技术能力上考虑，支持三处内容的完全的独立控制肯定是能力最强最彻底的，但是如果从交互的角度考虑，气泡其实应该和小字的内容是一致的，气泡只是提供了类似于“放大镜”的效果

**Comment by p697** [comment]
> 气泡只是提供了类似于“放大镜”的效果

有道理

**Comment by awmleer** [comment]
那确定一下结论好了：
- 增加 `brief` 属性，展示的是右侧边栏的小字以及按住时的气泡内展示的内容
- `title` 属性逻辑不变，仅控制左侧列表中标题的内容
- `briefTitle` 和 `title` 都支持 ReactNode
- 这两个属性都是可以缺省的，`title` 默认取 `index`，`briefTitle` 默认取 `index` 的第一个字符
- 边栏中的小字、气泡，都固定形状一定是正圆形，超出的部分 overflow hidden

**Comment by awmleer** [comment]
@p697 有兴趣做一下嘛

**Comment by p697** [comment]
我来冲冲冲

**Comment by awmleer** [comment]
4cdf49fd3
