### ISSUE TITLE
Dropdown 支持在 Dropdown.Item 内部关闭自己

### ISSUE THREAD

**Issue by shabbyaaa** [ant-design/ant-design-mobile#4451]
### Version of antd-mobile

5.0.0-beta.27

### What is this feature about?

在CheckList下拉菜单的内容区域中，可以添加一个受控属性使得我们可以控制下拉菜单的关闭？
例如，在下拉菜单内有一个按钮，点击按钮使下拉菜单关闭
现在只能通过activeKey来实现，如果有多个Dropdown.Item，那么维护activeKey比较麻烦，需要在title文字上动态得改变activeKey

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by p697** [comment]
> 在CheckList下拉菜单的内容区域中

这里是指 Dropdown 的内容区域嘛

**Comment by shabbyaaa** [comment]
是指Dropdown的api，就是我可以在内容区域中，例如一个按钮来触发事件使得这个下拉菜单关闭，而不借助于activeKey来实现。
因为如果使用activeKey，那么我需要额外来维护这个属性，例如在点击Dropdown.Item的title使得下拉菜单关闭和显示

**Comment by awmleer** [comment]
这个也不算是“受控”吧，我来把 issue 的标题改一下

**Comment by awmleer** [comment]
> 是指Dropdown的api，就是我可以在内容区域中，例如一个按钮来触发事件使得这个下拉菜单关闭，而不借助于activeKey来实现。
> 因为如果使用activeKey，那么我需要额外来维护这个属性，例如在点击Dropdown.Item的title使得下拉菜单关闭和显示

提供一个 Ref 如何？

```
const dropdownRef = useRef(null)

<Dropdown ref={dropdownRef}>
  ...
</Dropdown>
```

然后调用 `dropdownRef.current.close()` 来关闭

这样如何？

**Comment by awmleer** [comment]
@shabbyaaa

**Comment by shabbyaaa** [comment]
嗯嗯 可以的

**Comment by xiaoyao96** [comment]
我试试开发看看
