### ISSUE TITLE
当input的type="number"时，max不生效

### ISSUE THREAD

**Issue by fzy-cloud** [ant-design/ant-design-mobile#4452]
### Version of antd-mobile

5.0.0-beta.28

### Operating system and its version

Others

### Sandbox to reproduce

https://codesandbox.io/embed/frosty-williams-3mfps?fontsize=14&hidenavigation=1&theme=dark

### What happened?

当input的type="number"时，max不生效,maxlength也不生效

### Relevant log output

```shell
<Input type="number" max={6} placeholder="看看" clearable />
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yaogengzhu** [comment]
原生的input对 type = number 也不支持max呢。可以考虑自己限制下

**Comment by fzy-cloud** [comment]
> 原生的输入对类型=数量也不支持最大呢。可以考虑自己限制下

原生是支持的哦https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-max

**Comment by awmleer** [comment]
number 模式下，maxLength 的确是不支持的，不过 max 应该是支持的：
![image](https://user-images.githubusercontent.com/16526078/143806558-46145e9a-7f37-4448-992e-d69c6fa901c3.png)

**Comment by awmleer** [comment]
看起来是个 bug

**Comment by awmleer** [comment]
应该是 React 的问题，我写了个原生的 `input`，也是一样的行为：

![image](https://user-images.githubusercontent.com/16526078/143806772-4dac6a76-9ead-425d-98f8-66b4469e5f3c.png)

![image](https://user-images.githubusercontent.com/16526078/143806778-bc1ad19a-2402-497e-89a8-b96b1484de1e.png)

**Comment by yaogengzhu** [comment]
> > 原生的输入对类型=数量也不支持最大呢。可以考虑自己限制下
> 
> 原生是支持的哦https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-max

支持箭头的取值是支持max最大值,不支持手动输入😂。

**Comment by awmleer** [comment]
是的
