### ISSUE TITLE
Form 表单和 Switch共用的时候，有时候水平布局右边内容需要靠右显示。

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design-mobile#4453]
### Version of antd-mobile

^5.0.0-beta.31

### What is this feature about?

![SPQ0J JO KDOCF{2KWWIVH](https://user-images.githubusercontent.com/17424034/143805131-a9add288-866b-4e28-b8cd-008cfe34481c.png)
有时候表单需要如图红色框所属效果，希望提供一个参数判断右边区域内容靠左、靠右、居中显示。

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by feibi** [comment]
Form.Item 是不是增加个右箭头配置

**Comment by awmleer** [comment]
我需要和设计师先确认一下这块的设计规范

**Comment by awmleer** [comment]
c85a4839 已完成
