### ISSUE TITLE
form表单希望增加“手机或者座机区号+号码，数值+单位的布局模式”

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design-mobile#4458]
### Version of antd-mobile

^5.0.0-beta.31

### What is this feature about?

![97125860506c19b66dc446f30e1b989f60c111b1ec30f32b0c9563574e1dc8c4QzpcVXNlcnNcNTQzNDJcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDgzNTYyNDE2X3YyXEltYWdlRmlsZXNcMTYzODE2NzYyNTkyNl81RjVFQTI4Ri1BOTczLTRiZjQtQTk3Ny1DQUFCQ0U5RjEwOTEucG5n](https://user-images.githubusercontent.com/17424034/143820239-9b760e91-44a1-49c6-a123-54b178cf245a.png)
表单建议支持如图所示的两种模式，这种需求在表单录入的时候是有需求的！

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangdepp** [comment]
https://github.com/ant-design/ant-design-mobile/pull/4463
可以试一下自定义表单控件的方式
