### ISSUE TITLE
使用ListView无限循环加载数据的问题

### ISSUE THREAD

**Issue by guangming21** [ant-design/ant-design-mobile#446]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

#### 你做了什么？

引入ListView组件

#### 你期待的结果是：

正常显示数据

#### 实际上的结果：

俩个组件用到了ListView，第一个组件没有这样的情况，同样的实现，第二个组件就会循环无限重复加载数据，很奇怪，有什么可能的原因影响了吗

**Comment by warmhug** [comment]
这就得你自己仔细对照 demo 和正常例子排查下了。。
