### ISSUE TITLE
Tag 增加一些 CSS 变量

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#4464]
CSS 变量：
--border-color
--background-color
--text-color
--border-radius（需支持全局 CSS 变量）

**Comment by p697** [comment]
> 需支持全局 CSS 变量

这个是啥意思呢

**Comment by p697** [comment]
![image](https://user-images.githubusercontent.com/51314472/143967546-a3c55315-9e40-48ec-b782-3f4feaec090d.png)

懂了懂了
