### ISSUE TITLE
InfiniteScroll：滚动组件所在的容器需要有overflow: hidden属性

### ISSUE THREAD

**Issue by shabbyaaa** [ant-design/ant-design-mobile#4465]
### Version of antd-mobile

5.0.0-beta.27

### What is this feature about?

InfiniteScroll 使用自定义List组件时，需要在其容器中添加overflow：hidden
否则其滚动条会一直在最底部，即一直执行loadMore函数
以下是我的开发环境版本：
antd-mobile, 5.0.0 beta.27
react, v17.0.2
react-dom, v17.0.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
看起来是你自己用法的问题？

**Comment by shabbyaaa** [comment]
等晚上我看一下 应该我父容器哪里写的样式影响到了

**Comment by WebGamer** [comment]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/56241499/221463411-4fd60210-5612-4f0f-ae45-4e122798bf62.png">
现在是搜索，总是会触发多次
