### ISSUE TITLE
Input组件使用中enterKeyHint报错

### ISSUE THREAD

**Issue by LaughingZhu** [ant-design/ant-design-mobile#4467]
### Version of antd-mobile

5.0.0-beta.32

### Operating system and its version

Others

### Browser and its version

web chrome

### What happened?

在使用Input组件时报错，umi 是3.3.4版本的
![image](https://user-images.githubusercontent.com/20132891/143966492-eebd8038-9aed-44a8-9a64-034acccb531e.png)
![image](https://user-images.githubusercontent.com/20132891/143966578-54a604b6-9496-4e5b-8af7-cfabb8253c6f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jacob-lcs** [comment]
这个跟 React 版本有关系，React 17 才添加了 enterKeyHint 属性

https://github.com/facebook/react/pull/18634

**Comment by awmleer** [comment]
47a57120f 中优化了一下，之后 React 16 中也可以正常使用了
