### ISSUE TITLE
InfiniteScroll 组件下拉 抖动 就我一个遇到这个问题吗

### ISSUE THREAD

**Issue by Z-LianYan** [ant-design/ant-design-mobile#4476]
### Version of antd-mobile

^5.0.0-rc.0

### What happened?

数据多能正常使用，但是数据刚好占满一个屏幕的时候下拉就抖动了。
Chrome浏览器 iPhone 678测试

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
复现 demo please

**Comment by Z-LianYan** [comment]
<InfiniteScroll
          threshold="200"
          loadMore={async () => {
            fetchOptionsHot.page += 1;
            this.setState({ fetchOptionsHot });
            let result = await get_film_hot({
              ...fetchOptionsHot,
              city_id: this.props.locationInfo.city_id,
            });
            this.setState({
              hotList:
                fetchOptionsHot.page === 1
                  ? result.rows
                  : hotList.concat(result.rows),
            });
            if (this.state.hotList.length >= result.count) {
              this.setState({
                isHotHasMore: false,
              });
            }
          }}
          hasMore={isHotHasMore}
        >
          <InfiniteScrollContent
            text="暂无内容"
            noContent={!isHotHasMore && !this.state.hotList.length}
            hasMore={isHotHasMore}
          />
        </InfiniteScroll>

**Comment by awmleer** [comment]
@Z-LianYan 在这里写 demo 哈：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by sarufarr** [comment]
这个我有描述类似的目击场景，目前只发现在小米上有此类问题，当时定位到或许和小米系统内置浏览器的长宽计算的迷之误差有关
