### ISSUE TITLE
Navbar 标题换行

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#448]
<img width="372" alt="image" src="https://cloud.githubusercontent.com/assets/507615/19770454/e74b073c-9c91-11e6-9a43-47e072f4d8ae.png">

**Comment by warmhug** [comment]
这个是有意这么做的，一行显示不下、省略显示也不好。 让设计师再确认下吧 @ 下设计师

**Comment by afc163** [comment]
感觉六个字有点短，直接强制不换行好了，也不用省略号。
