### ISSUE TITLE
使用nostyle 后，必填字段*号没有了

### ISSUE THREAD

**Issue by zwjsoft** [ant-design/ant-design-mobile#4482]
### Version of antd-mobile

5.0.0-rc.0

### Description

![1638348186](https://user-images.githubusercontent.com/35764692/144201446-3fb56e15-d07e-4efa-a68c-a9ff714c1761.png)

**Comment by zwjsoft** [comment]
<Form.Item
            label='编码'

          >
            <Grid columns={2} gap={12}>
              <Grid.Item>
                <Form.Item name='ceqcode'  rules={[{ required: true, message: '编码不能为空' }]}  noStyle >
                  <Input   />

                </Form.Item>    </Grid.Item> 
                <Grid.Item>
                <Button ><ScanCodeOutline fontSize={24}/></Button>  </Grid.Item>
            </Grid>

          </Form.Item>

**Comment by zzzgydi** [comment]
```javascript
<Form.Item label="设备编码" required>
    <Grid>
        <Grid.Item>
            <Form.Item name='ceqcode'  rules={[{ required: true, message: '编码不能为空' }]}  noStyle >
                <Input   />
            </Form.Item>
        </Grid.Item>
    </Grid>
</Form.Item>
```

第一行这里加个required可以加个星号，仅做ui展示的功能。

**Comment by awmleer** [comment]
@zzzgydi 说的这个思路是正解～
