### ISSUE TITLE
按照官网的教程 方法一 从 v2 迁移，但是报错

### ISSUE THREAD

**Issue by lolinice** [ant-design/ant-design-mobile#4484]
![1638359679(1)](https://user-images.githubusercontent.com/33769498/144230099-5619b27f-1232-4a3d-8515-45b9f179ad0e.png)

**Comment by lolinice** [comment]
![1638359723(1)](https://user-images.githubusercontent.com/33769498/144230212-4e693236-6e6f-4717-af73-4cd420ecb038.png)

**Comment by awmleer** [comment]
是 umi 项目么？
![image](https://user-images.githubusercontent.com/16526078/144350080-dc1fcbf0-1852-4704-a774-c388df041668.png)

**Comment by MaskHao** [comment]
也是报错。在umirc.ts中配置 antd: {mobile: false}，结果提示我Validate config "antd" failed, "mobile" is not allowed

**Comment by GOWxx** [comment]
> 

你的 umi 是什么版本？
升级版本试试？我在用的版本是
```"umi": "^3.5.20"```
```.umirc.ts``` 配置 ```antd: { mobile: false }``` 没问题

**Comment by awmleer** [comment]
@MaskHao 看起来是 umi 插件/preset 版本过低了，升级一下就支持 mobile 配置了

**Comment by MaskHao** [comment]
> 

升级过了哦

**Comment by MaskHao** [comment]
发现迁移后，样式没有了，难道要手动import下antd-mobile-v2 样式么？

**Comment by MaskHao** [comment]
![image](https://user-images.githubusercontent.com/20870972/145551681-e033f857-c299-463f-9c75-5fff585ae568.png)

**Comment by awmleer** [comment]
@MaskHao 样式没有了是指 v2 还是 v5 的样式？如果是 v2 的，是需要手动引入一下 css 文件的，参考：

https://antd-mobile-doc-v2.gitee.io/docs/react/introduce-cn#3.-使用

<img width="955" alt="image" src="https://user-images.githubusercontent.com/16526078/145556798-0432d70c-8a24-49f0-a734-eafebae7a37a.png">
