### ISSUE TITLE
demos 发布到 npm 包中

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#4485]
现在文档中出现的 `import xxx from 'demos'` 太容易让人误解有个 npm 包叫 demos 了，干脆发到 antd-mobile 的 npm 包里面好了

变为 `antd-mobile/demos`

**Comment by xiaohuoni** [comment]
这么处理好像也没办法消除误解！

**Comment by awmleer** [comment]
@xiaohuoni 对的，是这个意思

**Comment by brickspert** [comment]
这个解决方案不太好~~

**Comment by xiaohuoni** [comment]
我觉得 demo 组件就这么几个，还不如另外发一个包。应该万年不更新。就是给演示用。

**Comment by GOWxx** [comment]
目前 demos 里有的是 lorem, DemoBlock, DemoDescription, sleep, createPropsTable

  createPropsTable：目前似乎没在哪里使用，可以先不管它  
  sleep ：在需要的页面声明并使用，毕竟只有几行代码  
  lorem：是基于 lorem-ipsum 在需要使用的页面里引入 lorem-ipsum 并封装 lorem
  （这个想法是看有些同学会尝试 yarn add demos，那么应该也会很自然的会认为lorem-ipsum也是一个包）

把 DemoBlock 和 DemoDescription 升级为一个UI组件发布出来 例如
<Card>
  <Card.Description>描述内容</Card.Description >
  <Card.Description content='描述内容'/>
</Card>

这样文档可以正常展示，阅读文档的同学也可以简单的复制粘贴出来使用

我认为 antd-mobile5 有这样的模块展示的需求，实际开发项目的时候也是有这种需求的

**Comment by KaZeKaMi-666** [comment]
请问这个demos是不是还没集成在antd-mobile v5里面？我试了下新版的Swiper直接报错。

**Comment by awmleer** [comment]
放到组件库里作为一个普通组件还是要考虑很多事情的：

1. 要同时纳入设计规范，这块涉及到设计师方面的考虑
2. 要确保未来不产生 break change，对于一个仅仅 demo 自己用的组件来说，有些过于限制了

**Comment by xiaohuoni** [comment]
不用 demo 这几个组件不行吗？用现有的组件去搞，demo演示一定要长现在这个样子吗？

**Comment by awmleer** [comment]
现有组件能用来搞 demo 布局也就是 List 了，但是使用起来可繁琐的多了

**Comment by 904192063** [comment]
我的项目才刚开始搭建，直接引用ant的官方示例代码，可是仍然提示Module找不到，尝试替换成'antd-mobile/demos'仍然报错，我的版本是"antd-mobile": "^5.0.0-rc.26",希望问题能解决

[https://mobile.ant.design/zh/components/tab-bar](url)


报错信息
Module not found: Can't resolve 'demos'
或Module not found: Can't resolve 'antd-mobile/demos'

**Comment by awmleer** [comment]
想了一下，`demos` 还是不能发到 `antd-mobile` 的 npm 包中的，不然跟随的一些依赖（比如 `lorem`）也得放到 `dependencies` 里，就有点不太干净了

我先文档上加个说明好了 bd4e8eea0
