### ISSUE TITLE
Tag 是不是统一下 line-height

### ISSUE THREAD

**Issue by lwQin** [ant-design/ant-design-mobile#4487]
### Version of antd-mobile

5.0.0-rc.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lwQin** [comment]
<img width="368" alt="Xnip2021-12-02_14-03-32" src="https://user-images.githubusercontent.com/11586662/144366779-e4730879-ce4d-4fd4-a21c-82846f4e0e27.png">

**Comment by awmleer** [comment]
Fixed via b58b64ccb.
