### ISSUE TITLE
Vertical Swiper doesn't show the card after the first one. 

### ISSUE THREAD

**Issue by abhieshekumar** [ant-design/ant-design-mobile#4489]
### Version of antd-mobile

5.0.0-rc.1

### Operating system and its version

Android

### What happened?

Hi, I am using [swiper](https://mobile.ant.design/components/swiper#vertical) in vertical mode and it only shows the first card/item. Thank you

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by z1006** [comment]
Please add a demo

**Comment by kuse95** [comment]
官方示例就可以复现: https://mobile.ant.design/zh/components/swiper#%E7%AB%96%E5%90%91

**Comment by abhieshekumar** [comment]
Yes, if you visit the link mentioned and start swiping up, 2,3 and 4 do not show up. It just shows 1 and then blank white spaces.

**Comment by awmleer** [comment]
@abhieshekumar When `loop` is disabled, its behavior is correct. You can set `loop={false}` temporarily as a workaround. We'll fix this in the next release, which is about to be published a few days later.

**Comment by awmleer** [comment]
Fixed via 65263b6e0.
