### ISSUE TITLE
Icon 文档加入模糊搜索和点击复制

### ISSUE THREAD

**Issue by p697** [ant-design/ant-design-mobile#4498]
### Version of antd-mobile

5.0.0-rc.1

### What is this feature about?

感觉现在找 Icon 和复制 Icon 都有点鸡肋，可以参考 antd 加入图标搜索和复制

![image](https://user-images.githubusercontent.com/51314472/144426481-e8a5ecdd-57e7-43be-a29c-766c32124084.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yangdepp** [comment]
复制到剪贴板的内容如果是这个图标的名字或者一条完整引用语句就更好了，至少我翻antd的图标的时候，主要就是为了复制引入，而antd每次都是都会加上`<xxx />`
