### ISSUE TITLE
react 项目引入组件后，样式没有自动引入

### ISSUE THREAD

**Issue by duyu123** [ant-design/ant-design-mobile#4499]
### Version of antd-mobile

5.0.0-rc.1

### Browser and its version

谷歌

### What happened?

```
import { Mask, Button } from "antd-mobile";
...

        <Button color="primary">Primary</Button>

```
![image](https://user-images.githubusercontent.com/21079129/144431197-8f72bc24-0ec6-43a3-954d-d6db274ac541.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
发一下你项目的配置文件？webpack 配置或者 umi 配置
