### ISSUE TITLE
官方steps组件没有export

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design-mobile#45]
如题

**Comment by warmhug** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/components/index.web.tsx
https://github.com/ant-design/ant-design-mobile/blob/master/index.web.js

为什么存在两个文件，能否合并？ 导出到包里的、是需要在第一个里边写进去？
@yiminghe

**Comment by yiminghe** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/index.web.js 永远不要对，

改 https://github.com/ant-design/ant-design-mobile/blob/master/components/index.web.tsx 用于类型导出
