### ISSUE TITLE
Stepper 组件 BUG

### ISSUE THREAD

**Issue by LayGit** [ant-design/ant-design-mobile#450]
Stepper 组件设置了 readOnly=true，按照文档意思应该是输入框只读，但是因为 input 是受控组件，导致加减功能也失效。

期望效果：
设置了 showNumber 同时 readOnly=true
文本框只读用于显示，加减号可正常操作

antd-mobile 版本：0.9.4

**Comment by benjycui** [comment]
`readOnly` 意味着 not editable，加减号无效是预期行为才对。

**Comment by LayGit** [comment]
我的理解是 限制 input 只读，现在是这么一种场景：用户通过 Stepper 组件调整股票数量，每次步长100股（即一手），但是不开放自定义输入，input 只作为显示用。 现在我把input隐藏了，另外放了个 Label 用于显示。 但是最好是能显示在加减号中间，这样比较直观。

如果 not editable ，且加减号无效的话，那就应该是 disabled。不然交互上加减号不变灰，操作又无效，这体验岂不是很怪。

**Comment by LayGit** [comment]
@pingan1927  希望能解释一下 readOnly 和 disabled 的区别，官网 Demo 上也并无 readOnly 的示例。

**Comment by silentcloud** [comment]
@afc163  rc-input-number

**Comment by afc163** [comment]
readOnly 和 disabled 是 input 组件 html 规范内的属性，区别可搜索相关规范文档。

**Comment by MrKou47** [comment]
但是这个 `Stepper` 组件 的 readOnly 和 disabled 参数的作用不就一样了么？ 都是不能操作数字加减只能看数字是多大。正常理解 readOnly 就是input不可点击，按钮可以操作数字加减才对啊

**Comment by afc163** [comment]
@MrKou47 https://www.w3schools.com/code/tryit.asp?filename=FEK13ZJ97A9G 试试原生控件就明白了。

**Comment by MrKou47** [comment]
但是我就想让 `Stepper` 的input只做显示的作用，现在能实现么？

**Comment by kandroid29** [comment]
> 但是我就想让 `Stepper` 的input只做显示的作用，现在能实现么？

我也想实现这个效果，请问你怎么解决的？

**Comment by awmleer** [comment]
@kandroid29 你是用的 v2 还是 v5？v5 是支持的，具体可以看官网上的这个 demo：

![image](https://user-images.githubusercontent.com/16526078/159867984-57ceef3f-a37d-4c7e-a582-be7bacf6a0ab.png)

```jsx
<Stepper inputReadOnly />
```
