### ISSUE TITLE
希望DatePicker增加不可选择日期和时间

### ISSUE THREAD

**Issue by ChuangShiOS** [ant-design/ant-design-mobile#4502]
### Version of antd-mobile

5.0.0-rc.2

### What is this feature about?

希望DatePicker增加不可选择日期和时间，和PC版ant-design的DatePicker组件一样，可用 disabledDate 和 disabledTime 分别禁止选择部分日期和时间
![WechatIMG2258](https://user-images.githubusercontent.com/65151203/144578205-1068dc2c-9c91-4070-920b-1defb7ff0db6.jpeg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
Picker 中似乎是没有 disabled 的，不过可以考虑加一个 filter 属性

**Comment by awmleer** [comment]
对于 DatePicker，filter 的类型是 `(val: Date) => boolean`，思路有点类似 js 数组的 `.filter()`
而对于 Picker 和 CascadePicker，如果硬要加 filter 的话，类型是 `(val: string[]) => void`，不过我其实觉得这两个 Picker **完全没必要**加 `filter` 属性，因为它们的 columns 都是完全可以用户自己配置的

**Comment by p697** [comment]
那要不先给 DatePicker 加个 filter，我来搞一下~

**Comment by awmleer** [comment]
> 那要不先给 DatePicker 加个 filter，我来搞一下~

嗯嗯OK

**Comment by p697** [comment]
这应该是 Picker 式的 DatePicker 特有的问题：`(val: Date) => boolean` 这样的 `filter` 好像没法正确实现过滤。

比如我想要过滤掉所有的周末，但是个别月份的第一天或者这个月里对应今天的日期刚好是周末，`filter` 就会把这整个月都过滤掉。

详细来说，`filter` 的作用是决定给 Picker 的 `columns` 内放入什么值。在加入 `filter` 之前，对于每一列只需要 ` generateIntArray` 就可以，但现在需要将每个 ` generateIntArray` 中的值放在 `filter` 内判断一下，如果返回 false 就不放入对应的 column 中。

回到上面的问题，当 `filter` 判断某个月份是否合法时，由于入参是一个 Date，那么 `filter` 其实并不是在判断这个月是否合法，而是在判断这个月中的某个 Date 是否合法。

有一个解法，可以告诉 `filter` 自己想要过滤的是什么精度。比如上面这个例子，假如 `filter` 知道要过滤的是日期，那么他就不会判断月份是否合法

**API 可以是这样：**
``` js
(val: Date, type: Precision) => boolean
```
然后用户在写 `filter` 的时候，需要加入对 `type` 的判断

之前的写法是这样：
``` js
const dateFilter = (val: Date) => {
  // 过滤掉所有周末
  if (val.getDay() > 5 || val.getDay() === 0) {
    return false
  }
  return true
}
```
现在这样写：
``` js
const dateFilter = (val: Date, type: Precision) => {
  // 过滤掉所有周末
  if (type === 'day') {
    if (val.getDay() > 5 || val.getDay() === 0) {
      return false
    }
  }
  return true
}
```

**API 还可以是这样：**
``` js
{
  year?: (val: Date) => boolean
  month?: (val: Date) => boolean
  day?: (val: Date) => boolean
  ...
}
```

有点像 antd 禁用 Time 的格式

<img src='https://user-images.githubusercontent.com/51314472/144958981-253ede43-5446-418a-ab3e-f6527f8d7e57.png' width='550px'></img>

**Comment by awmleer** [comment]
我之前想的是只对最后一级进行 filter 处理，然后再进行归约

比如说，我们想过滤掉 2 月整个月
那原始数据是这样的：

- 2021年
  - 1月
    - 1日
    - 2日
    - 3 日
    - ...
  - 2月
    - 1日
    - 2日
    - 3 日
    - ...
  - 3月
    - 1日
    - 2日
    - 3 日
    - ...

经过 `filter` 过滤之后，变成了：

- 2021年
  - 1月
    - 1日
    - 2日
    - 3 日
    - ...
  - 2月
  - 3月
    - 1日
    - 2日
    - 3 日
    - ...

因为 2 月的 children 是空数组了，所以 2 月也被移除掉，最终得到：

- 2021年
  - 1月
    - 1日
    - 2日
    - 3 日
    - ...
  - 3月
    - 1日
    - 2日
    - 3 日
    - ...

不过这样虽然能实现功能，但是性能可能会比较差

**Comment by p697** [comment]
相当于一次把所有可能选择的时间都判断一遍嘛

**Comment by awmleer** [comment]
> 相当于一次把所有可能选择的时间都判断一遍嘛

是的，这样太暴力了，行不通的，性能应该会差到爆表

**Comment by awmleer** [comment]
感觉 object 这样似乎更好用一些？

```js
{
  year?: (val: Date) => boolean
  month?: (val: Date) => boolean
  day?: (val: Date) => boolean
  ...
}
```

不过这里的 `val` 是不是直接用 number 就可以了，date 作为一个额外参数：

```js
{
  year?: (val: number, date: Date) => boolean,
  ...
}
```

**Comment by p697** [comment]
有道理，直接是 number 可以减少很多计算，那就先这样！
