### ISSUE TITLE
不能运行antd mobile

### ISSUE THREAD

**Issue by g00152362** [ant-design/ant-design-mobile#4503]
### Version of antd-mobile

5.00 最新版本

### Operating system and its version

Android

### What happened?

代码

import React, { PureComponent } from 'react'
import { StyleSheet, View, Image, Text } from 'react-native'
import { Button } from 'antd-mobile'

class MineScene extends PureComponent<Props, State> {

    render() {
        return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'white' }}>
                {/* <Text>Mine</Text> */}
				<Button color='primary'>Primary</Button>
            </View>
        )
    }

}

编译时候出现这个，无法运行

Error: Unable to resolve module ./global.css from D:\code\grid1\node_modules\antd-mobile\cjs\global\index.js:

None of these files exist:
  * node_modules\antd-mobile\cjs\global\global.css(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\antd-mobile\cjs\global\global.css\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  1 | "use strict";
  2 |
> 3 | require("./global.css");
    |          ^

### Relevant log output

```shell
编译时候出现这个，无法运行

Error: Unable to resolve module ./global.css from D:\code\grid1\node_modules\antd-mobile\cjs\global\index.js:

None of these files exist:
  * node_modules\antd-mobile\cjs\global\global.css(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\antd-mobile\cjs\global\global.css\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  1 | "use strict";
  2 |
> 3 | require("./global.css");
    |          ^
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xiaoyao96** [comment]
antd mobile v5 不支持react-native

**Comment by awmleer** [comment]
rn 相关问题请移步：https://github.com/ant-design/ant-design-mobile-rn/issues
