### ISSUE TITLE
dev-log.js?63d4:9 [antd-mobile: Global] The px tester is not rendering properly. Please make sure you have imported `antd-mobile/es/global`

### ISSUE THREAD

**Issue by erdang** [ant-design/ant-design-mobile#4504]
### Version of antd-mobile

5.0.0-rc.2

### Operating system and its version

Others

### Relevant log output

```shell
dev-log.js?63d4:9 [antd-mobile: Global] The px tester is not rendering properly. Please make sure you have imported `antd-mobile/es/global`

使用 "antd-mobile": "5.0.0-rc.2", ImageUploader组件  在入口文件 已经import 'antd-mobile/es/global';

还是报这个错误
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
@erdang 可以提供一个复现 demo 么？最好是一个简单的工程项目 repo （或者压缩包也可）

**Comment by weixiaopasta** [comment]
请问解决了没有  同样遇到了

**Comment by chaiguanpeng** [comment]
在webpack的 module中rules配置下这个
 module: {
                    rules: [
                        {test:/\.css$/,use:['style-loader','css-loader']},
                    ]
                }

**Comment by citrusjunoss** [comment]
+1

**Comment by airwaycai** [comment]
+1

**Comment by airwaycai** [comment]
umi开启 webpack5: {},就报这个错了

**Comment by awmleer** [comment]
> umi开启 webpack5: {},就报这个错了

😦 @xiaohuoni umi webpack 5 会做什么特殊的事情么？莫非是和 MFSU 有关？

**Comment by xiaohuoni** [comment]
@airwaycai @erdang 给个可以跑的 demo 吧，这信息太少了。不懂啥意思。

**Comment by huaTJ0210** [comment]
css-loader启用CSS 模块就会报上述错误：
{
            loader: 'css-loader',
            options: {
              modules:true 
          }
}
暂时方案:单独对less文件配置loader启用CSS 模块;

**Comment by huaTJ0210** [comment]
css-loader启用CSS 模块就会报上述错误：
{
loader: 'css-loader',
options: {
modules:true
}
}
暂时方案:如果想开启CSS模块，可以使用less、sass，单独对less、sass文件配置loader启用CSS 模块;

**Comment by awmleer** [comment]
@huaTJ0210 可以配置一下范围，只对你自己项目的 css 文件处理，忽略掉 node_modules 下的 css 文件

**Comment by majinxin8023** [comment]
我这边是因为使用了swc-loader 导致会报这个错误， 之后我换了babel 错误就消失了

**Comment by HHKG** [comment]
这个问题的原因是：项目启动了按需加载样式导致的，官网有解决方案，亲测可以解决问题，描述如下图：
![image](https://user-images.githubusercontent.com/34594823/234167416-65269a84-6293-46cb-89ec-6a79c6c09de3.png)
