### ISSUE TITLE
How to solve svg-sprite-loader problem ? 

### ISSUE THREAD

**Issue by Tonysmark** [ant-design/ant-design-mobile#4507]
### Version of antd-mobile

5.0.0-beta.16

### Operating system and its version

iOS, Android

### Browser and its version

Chrome v96.0.4664.45

### What happened?
svg-sprite-loader@6.0.0

There is some problems when using `svg-sprite-loader` , if you already using svg in your project, and configure `svg-sprite-loader` in your webpack, when using some components i.e Slider, an error will throw out through webpack and says "ERROR in ../../node_modules/antd-mobile/es/assets/slider-thumb.svg"

And I was trying to exclude `node_modules` in the config file, and then I got an  `.svg` file that need an loader problem

在使用了`svg-sprite-loader`， 导致一些组件在使用 svg 作为icon的时候报错 `"ERROR in ../../node_modules/antd-mobile/es/assets/slider-thumb.svg"` , 如果把 node_modules 排出的话，又报 `.svg` 需要一个 loader 的错误

### Relevant log output

```shell
ERROR in ../../node_modules/antd-mobile/es/assets/slider-thumb.svg
Module build failed (from ../../node_modules/svg-sprite-loader/lib/loader.js):
ExtractPluginMissingException: svg-sprite-loader exception. svg-sprite-loader in extract mode requires the corresponding plugin
    at Object.loader (D:\Sunglink\OSAP-SSP\node_modules\svg-sprite-loader\lib\loader.js:47:13)
 @ ../../node_modules/css-loader/dist/cjs.js!../../node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!../../node_modules/antd-mobile/es/components/slider/slider.css 5:0-74 7:73-102


and in webpack config

```js
{
    test: /\.svg$/,
    use: ['svg-sprite-loader'],
},
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarufarr** [comment]
建议仅使用 `svg-sprite-loader` 加载业务代码中的 `svg` 文件(比如 `/src`)
`test: /\.svg$/,` 是对所有 `xx.svg` 使用了

**Comment by Tonysmark** [comment]
> 建议仅使用 `svg-sprite-loader` 加载业务代码中的 `svg` 文件(比如 `/src`) `test: /\.svg$/,` 是对所有 `xx.svg` 使用了


webpack中排除了 node_modules 就会报 .svg 需要一个 handler 处理

**Comment by xiaohuoni** [comment]
我有个相似的问题: `webpack中排除了 node_modules 就会报 .svg `

**Comment by sarufarr** [comment]
排除 `node_modules ` 后或许你需要一个 `svgr` ?

**Comment by Tonysmark** [comment]
> 我有个相似的问题: `webpack中排除了 node_modules 就会报 .svg `

对, 是因为mobile源码中把 svg 当作 image 使用了，所以和 sprite-loader 冲突

**Comment by Tonysmark** [comment]
> 排除 `node_modules ` 后或许你需要一个 `svgr` ?

或者直接用 file-loader 只加载 node_modules 里的 svg ?

**Comment by sarufarr** [comment]
```
  &-thumb {
    background: #fff url('../../assets/slider-thumb.svg') no-repeat center
      center;
  }
```
看起来是这段的锅了
可是这只需要 `file-loader` 处理就可以了
我觉得试试  不要让雪碧的 `loader` 处理 `.less` 或许可行
不了解雪碧的使用

**Comment by Tonysmark** [comment]
> ```
>   &-thumb {
>     background: #fff url('../../assets/slider-thumb.svg') no-repeat center
>       center;
>   }
> ```
> 
> 看起来是这段的锅了 可是这只需要 `file-loader` 处理就可以了 我觉得试试 不要让雪碧的 `loader` 处理 `.less` 或许可行 不了解雪碧的使用

嗯嗯 你这么一说我好像知道怎么解了， 晚点我可以试一试

**Comment by Tonysmark** [comment]
> > ```
> >   &-thumb {
> >     background: #fff url('../../assets/slider-thumb.svg') no-repeat center
> >       center;
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看起来是这段的锅了 可是这只需要 `file-loader` 处理就可以了 我觉得试试 不要让雪碧的 `loader` 处理 `.less` 或许可行 不了解雪碧的使用
> 
> 嗯嗯 你这么一说我好像知道怎么解了， 晚点我可以试一试

不过好像又不对了， 怎么配置啊
```js
{
    test: /\.svg$/,
    use: {
        loader: 'svg-sprite-loader',
        options: {
            exclude: [/node_modules/],
        },
    },
},
{
    test: /\.svg$/,
    use: {
        loader: 'file-loader',
        options: {
            include: [/node_modules/],
        },
    },
},
```

肯定不是这样写

**Comment by sarufarr** [comment]
有`demo`的仓库地址吗

**Comment by Tonysmark** [comment]
> 有`demo`的仓库地址吗

晚点提供

**Comment by awmleer** [comment]
感觉思路是这样的，你项目中的 `.svg` 文件你正常使用 svg-sprite-loader，但是对于 `node_modules/**/*.svg`，让 webpack 用 file-loader

**Comment by Tonysmark** [comment]
> 有`demo`的仓库地址吗

https://github.com/Tonysmark/svg-demos

 大概是那个意思

**Comment by awmleer** [comment]
这样配置试试？

```js
{
    test: /node_modules\/.+\.svg$/,
    use: {
        loader: 'file-loader',
    },
},
{
    test: /\.svg$/,
    use: {
        loader: 'svg-sprite-loader',
        options: {
            exclude: [/node_modules/],
        },
    },
},
```

**Comment by Tonysmark** [comment]
> 这样配置试试？
> 
> ```js
> {
>     test: /node_modules\/.+\.svg$/,
>     use: {
>         loader: 'file-loader',
>     },
> },
> {
>     test: /\.svg$/,
>     use: {
>         loader: 'svg-sprite-loader',
>         options: {
>             exclude: [/node_modules/],
>         },
>     },
> },
> ```

思路应该是对的，但是这样配置也不行
![image](https://user-images.githubusercontent.com/22767695/144959059-02987bb8-eae6-4ff1-9bd2-4deb3fda1cc5.png)

**Comment by awmleer** [comment]
@Tonysmark 仓库地址是这个么：https://github.com/Tonysmark/svg-demos

**Comment by Tonysmark** [comment]
> @Tonysmark 仓库地址是这个么：https://github.com/Tonysmark/svg-demos

对

**Comment by zzzgydi** [comment]
> ```js
> {
>     test: /node_modules\/.+\.svg$/,
>     use: {
>         loader: 'file-loader',
>     },
> },
> {
>     test: /\.svg$/,
>     use: {
>         loader: 'svg-sprite-loader',
>         options: {
>             exclude: [/node_modules/],
>         },
>     },
> },
> ```

这个配置不生效是因为你是Windows，路径问题，可以将`file-loader`的test设置成`/node_modules[\\/].+\.svg$/`。然后就是exclude字段写在options里好像是没有用的，写在外面就有用了。所以可以写成下面这样：

```js
{
  test: /node_modules[\\/].+\.svg$/,
  use: "file-loader",
},
{
  test: /\.svg$/,
  exclude: /node_modules/,
  use: "svg-sprite-loader",
},
```

或者这样吧

```js
{
  test: /\.svg$/,
  exclude: /node_modules/,
  use: "svg-sprite-loader",
},
{
  test: /\.svg$/,
  include: /node_modules/,
  use: "file-loader",
},
```

**Comment by awmleer** [comment]
感谢 @zzzgydi 一针见血～

那这个 issue 我 close 掉了

**Comment by Tonysmark** [comment]
> > ```js
> > {
> >     test: /node_modules\/.+\.svg$/,
> >     use: {
> >         loader: 'file-loader',
> >     },
> > },
> > {
> >     test: /\.svg$/,
> >     use: {
> >         loader: 'svg-sprite-loader',
> >         options: {
> >             exclude: [/node_modules/],
> >         },
> >     },
> > },
> > ```
> 
> 这个配置不生效是因为你是Windows，路径问题，可以将`file-loader`的test设置成`/node_modules[\\/].+\.svg$/`。然后就是exclude字段写在options里好像是没有用的，写在外面就有用了。所以可以写成下面这样：
> 
> ```js
> {
>   test: /node_modules[\\/].+\.svg$/,
>   use: "file-loader",
> },
> {
>   test: /\.svg$/,
>   exclude: /node_modules/,
>   use: "svg-sprite-loader",
> },
> ```
> 
> 或者这样吧
> 
> ```js
> {
>   test: /\.svg$/,
>   exclude: /node_modules/,
>   use: "svg-sprite-loader",
> },
> {
>   test: /\.svg$/,
>   include: /node_modules/,
>   use: "file-loader",
> },
> ```

66666

**Comment by xiaohuoni** [comment]
> 我有个相似的问题

https://github.com/umijs/umi-next/pull/217
