### ISSUE TITLE
Toast 支持全局配置

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#4508]
### Version of antd-mobile

5.0.0-rc.2

### What is this feature about?

Toast 增加 `config` 方法：

```ts
config: (val: {
  duration?: ToastProps['duration']
  position?: ToastProps['position']
}) => void
```

类似于 antd 的 `message.config`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awmleer** [comment]
另外需要考虑的是，是不是需要同时支持通过 ConfigProvider 配置

**Comment by liangskyli** [comment]
maskClickable 这个属性希望也加上，谢谢！

**Comment by liangskyli** [comment]
> ### Version of antd-mobile
> 5.0.0-rc.2
> 
> ### What is this feature about?
> Toast 增加 `config` 方法：
> 
> ```ts
> config: (val: {
>   duration?: ToastProps['duration']
>   position?: ToastProps['position']
> }) => void
> ```
> 
> 类似于 antd 的 `message.config`
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

maskClickable 这个属性希望也加上，谢谢！

**Comment by awmleer** [comment]
@liangskyli OK
