### ISSUE TITLE
转圈形式的 loading

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#4509]
### Version of antd-mobile

5.0.0-rc.2

### What is this feature about?

可能叫做 Spin？为了避免和现在的 Loading 混淆

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DreamPWJ** [comment]
圆圈加载更通用更美观  支持

**Comment by bdxtx** [comment]
以前有个spin，里面有圆圈加载，现在能不能增一些，加载中的样式

**Comment by zjfjiayou** [comment]
建议增加全局loading，直接通过loading.show 和loading.hide去控制，然后现在的三个点的loading不是很好看

**Comment by awmleer** [comment]
1815f1f65
