### ISSUE TITLE
官方的demo能跑起来 但是自己的demo跑不起来

### ISSUE THREAD

**Issue by feilongOnMoudu** [ant-design/ant-design-mobile#451]
#### 本地环境

- antd-mobile 版本：0.9.4
- 操作系统及其版本：iOS
- 浏览器及其版本：
#### 官方的demo能跑起来 但是自己的demo跑不起来，运行就报

<img width="302" alt="a47bf55e-7266-4e76-b9f4-95280df95c9f" src="https://cloud.githubusercontent.com/assets/16435428/19798616/bc480cc2-9d24-11e6-99c2-8a9289492b62.png">

该怎么设置啊  ant design mobile 文件夹已经存在的

**Comment by silentcloud** [comment]
参看项目主页的 readme，babel-plugin-import

**Comment by fengyun2** [comment]
@silentcloud 安装官网 配置了 babel-plugin-import 插件, 引入插件还是报  ` Can't resolve 'antd-mobile/lib/nav-bar/style/css' in 'D:\test\js\1112\react-redux-antd-mobile\src\components\AntDesignMobile\NavBar'`, 

`.babelrc`:  ```json

{
  "presets": ["es2015", "stage-2", "react"],
  "plugins": [["import", { libraryName: "antd", style: "css" }],"transform-runtime", "transform-decorators-legacy", "transform-class-properties"],
  "comments": false
}
 ````
