### ISSUE TITLE
popup 不可见时 会自动卸载内容， destroyOnClose没有作用

### ISSUE THREAD

**Issue by freshlymadebread** [ant-design/ant-design-mobile#4512]
### Version of antd-mobile

5.0.0-beta.14

### What happened?

隐藏popup后 会触发FC的重新渲染，隐藏后会打印 destroy asd ，出来会打印create  asd

```tsx
const Asd: FC = memo(() => {

  useEffect(() => {
    console.log('creat  asd');
    return () => {
      console.log('destroy asd');
    };
  });

  return <div style={{ height: '200%' }}>123</div>;
});
```

**Comment by awmleer** [comment]
看起来你还在用 beta.14 的版本？尝试升级一下到最新版看看？

**Comment by awmleer** [comment]
我这里用最新版的并不能复现出来这个问题，或者你尝试在这里提供一个复现 demo？https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx
