### ISSUE TITLE
Dropdown 支持自定义箭头

### ISSUE THREAD

**Issue by Dreamvsforward** [ant-design/ant-design-mobile#4515]
### What is this feature about?

期望可以自定义那个动画小图标
![image](https://user-images.githubusercontent.com/18736580/144996436-abd978c3-1a6d-4ea3-9eca-812f90578655.png)

**Comment by awmleer** [comment]
是想自定义这个箭头的 icon 么？还是自定义动画嘞？

**Comment by wangyuan0108** [comment]
> 是想自定义这个箭头的 icon 么？还是自定义动画嘞？

我觉得是想自定义这个icon

**Comment by zqran** [comment]
@awmleer 现在 Dropdown 的 箭头 是通过 CSS ::after 来实现的，如果要自定义 arrow 的话，是否将默认的 ::after 替换为 icon 图标？

**Comment by awmleer** [comment]
@zqran 嗯嗯替换一下吧
