### ISSUE TITLE
对于手机号的Input框,从中间删除数据,是如何保持光标不移动到最右边的?(how to preserve the cursor from moving to right when I delete the data from the middle?)

### ISSUE THREAD

**Issue by LastStranger** [ant-design/ant-design-mobile#4516]
### Version of antd-mobile

2.X

### Description

我在源码里面没找到关于光标的一些处理,但是我自己copy代码发现从中间删除数据,光标会移动到最右边

**Comment by AglaiaWang** [comment]
我已收到邮件，将尽快阅读。谢谢您的来信！

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by LastStranger** [comment]
> 

我只是想弄懂一下是如何做到保存光标不移动到最右边的,因为最新版本我没看到有手机格式的input框,所以才去看v2的

**Comment by awmleer** [comment]
@LastStranger 噢get，v2 不是我写的，不过我帮你查了一下代码，实现逻辑是在这里哈：
https://github.com/ant-design/ant-design-mobile/blob/62420044f878805e06b62d28338984ab3f603cdd/components/input-item/index.tsx#L138-L150
