### ISSUE TITLE
请问v2版本后期还会维护吗？

### ISSUE THREAD

**Issue by zzMoon** [ant-design/ant-design-mobile#4517]
### Version of antd-mobile

5.0.0-beta.25

### Description

项目中都是用的v2版本，
目前v5还有很多小问题，是尽量升级为v5吗？后期v2还会更新维护吗？麻烦给一个建议，谢谢。

**Comment by awmleer** [comment]
v2 后续不会更新了，建议还是升级到 v5，可以渐进式地升级，具体的操作方法可以参考这里：https://mobile.ant.design/zh/guide/migration

如果遇到 v5 版本的 bug，可以直接提 issue，我们都会尽快修复的
