### ISSUE TITLE
Collapse 折叠面板右侧图标可以支持自定义吗？我看了下是svg渲染的，想改个图形的话如何做？

### ISSUE THREAD

**Issue by wangyuan0108** [ant-design/ant-design-mobile#4518]
### Version of antd-mobile

5.0.0-rc.2

### What is this feature about?

Collapse 折叠面板右侧图标可以支持自定义，可以改icon的图标

**Comment by awmleer** [comment]
可以加个 `arrow` 属性来支持自定义

**Comment by wangyuan0108** [comment]
> 可以加个 `arrow` 属性来支持自定义

ok，看了下代码是没有开这个属性的，有计划加这个arrow属性自定义icon吗？
