### ISSUE TITLE
Space 组件问题

### ISSUE THREAD

**Issue by sxfmao** [ant-design/ant-design-mobile#4519]
### Version of antd-mobile

v5.0.0-rc.2

### Description

我想用flex布局，没找到flex组件，只找到了Space，所以我用了Space，但是Sapce自动生成了子元素div，如图
![image](https://user-images.githubusercontent.com/32216262/145143089-b1b27639-d891-42f0-bc64-0110fd0500ac.png)
我想在第二个元素添加 flex: auto; ，我可以通过css操作，但是我觉得不够优雅，有什么比较好的方案吗？或者提供flex布局相关的组件

**Comment by awmleer** [comment]
flex 布局你自己写 CSS 实现啊……
你这种情况不应该用 Space 组件的
