### ISSUE TITLE
ListView  onEndReached Bug

### ISSUE THREAD

**Issue by MozzieCN** [ant-design/ant-design-mobile#452]
#### 本地环境

- antd-mobile 版本：0.9.x
- 操作系统及其版本： win7
- 浏览器及其版本：   ##Chrome 49.0.2623.110 m
#### 你做了什么？

引入 ListView ，并开启   onEndReached功能，每次从服务端获取小于12条数据 。
返回的数据渲染能占满整个屏幕。
#### 你期待的结果是：

当页面拉下最底下时，才触发 onEndReached事件
#### 实际上的结果：

首次渲染后，如果 dataSource中的数据少于 12 条，会循环触发 onEndReached事件（此时不管scoll是否在最底部)。 直到 dataSource中的数据 >=12条才停止。

后续onEndReched时，不论服务端 返回多少数据，都正常。

如果在循环onEndReached过程中，只要scoll一下.循环onEndReached也会停止。

关键参数配置如下： 
      scrollRenderAheadDistance={500}
      onEndReachedThreshold={1}
      scrollEventThrottle={10}
      onScroll={() => { console.log('scroll'); }}
      onEndReached={this._onEndReached}
#### 可重现的在线演示

通过多次日志 调试，100%可重现。

**Comment by leilihuang** [comment]
@MozzieCN 我出现了和你一样的问题，请问你解决了吗？

**Comment by guangming21** [comment]
@leilihuang @MozzieCN 请问你们解决了吗，全是bug,

**Comment by leilihuang** [comment]
@guangming21 我的已经弄好了

**Comment by guangming21** [comment]
@leilihuang 怎么做的

**Comment by leilihuang** [comment]
@guangming21 没有，我的加载更多一直都有问题

**Comment by guangming21** [comment]
@leilihuang 我不用ListView了，我都换List做了，这个onEndReached，我在里面做判断倒是不无限加载了，但是每次触发渲染的行数却不确定，我设置10行，但是log打印有时是30行，这样里面的数据就重复渲染了

**Comment by leilihuang** [comment]
@guangming21 我没弄过，我去看看

**Comment by silentcloud** [comment]
@warmhug 看看？

**Comment by warmhug** [comment]
没响应，先关掉

**Comment by leonardgithub** [comment]
Antd-mobile 0.9.6的ListView初始化分页数据的时候，也是第一次就调了多次onEndReached，导致发送了三次请求，第1页的请求一次，第2页的请求有两次，其中做了setState({isRefreshing: true})和setState({isRefreshing: false})的操作，否则onEndReached调用更多次。
貌似升级到1.4.x，问题依旧。
期望：onEndReached只调用1次
另，想问一个问题很久了，antd-mobile的维护者是不是很急着关闭issue？

**Comment by warmhug** [comment]
Trace https://github.com/ant-design/ant-design-mobile/issues/520#issuecomment-315678741
