### ISSUE TITLE
View config getter callback for component 'a' must be a function (received `undefined`)

### ISSUE THREAD

**Issue by rccardero** [ant-design/ant-design-mobile#4520]
### Description

Hi guys, 

By adding the following button:

import Button from 'antd-mobile/lib/button';
....

<Button style={styles.buttonStyle} onClick={this.myFunction}>
  <Text>Search</Text>
</Button>

it is throwing me the following error:

Invariant Violation: View config getter callback for component `a` must be a function (received `undefined`). Make sure to start component names with a capital letter.

Please, any idea what I can be doing wrong?

**Comment by GOWxx** [comment]
What version of the library(antd-mobile) are you using ?
if you are using antd-mobile@5, try this
```
import { Button } from 'antd-mobile';
```

**Comment by rccardero** [comment]
I am using version 2.3.4

**Comment by GOWxx** [comment]
> I am using version 2.3.4

antd-mobile@2.3.4 no more maintenance.
There's a new version available, version 5.0.0-rc*

You can read the document
https://mobile.ant.design/guide/migration

**Comment by rccardero** [comment]
thank you very much, i will migrate to the new version

**Comment by GOWxx** [comment]
> thank you very much, i will migrate to the new version

btw, do you plan to use it in a browser environment ?
ant-mobile5 is not supported for react-native

**Comment by rccardero** [comment]
I want to use it for react-native

**Comment by GOWxx** [comment]
> I want to use it for react-native
it is with regret that antd-mobile5 is not supported for react-native
