### ISSUE TITLE
ImageViewer 用指令式的情况下是否应该给一个全局销毁的方法

### ISSUE THREAD

**Issue by Yixeu** [ant-design/ant-design-mobile#4521]
### What is this feature about?

示例里的指令式打开ImageViewer 定义到了变量上，销毁也要从这个变量入手。夸组件的时候实在不太方便

**Comment by awmleer** [comment]
可以加个 `clear` 方法：`ImageViewer.clear()`

**Comment by Yixeu** [comment]
还有呀大佬，那个ImageViewer 放大手势能不能完善下呀，我放大之后不能回到原地大小，图片会在背景移动位置，切换不了下一张图片，等于用户做了个放大手势直接挂了

**Comment by awmleer** [comment]
@Yixeu 嗯嗯看到你提的另一个 issue 了，我后面优化一下 #4437
