### ISSUE TITLE
Cascader 长数据无法滚动

### ISSUE THREAD

**Issue by 462937186** [ant-design/ant-design-mobile#4522]
### Description

https://mobile.ant.design/zh/components/cascader

官网cascader 组件长数据无法滚动

**Comment by awmleer** [comment]
@p697 求 see see

**Comment by 462937186** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by p697** [comment]
还真是，之前是 ok 的，我看下
