### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

### ISSUE THREAD

**Issue by caijiami** [ant-design/ant-design-mobile#4527]
### Version of antd-mobile

4.2.0

### Operating system and its version

Android

### What happened?

最新版的react-native0.66.3上报错
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

### Relevant log output

```shell
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
```

**Comment by awmleer** [comment]
rn 相关问题请移步：https://github.com/ant-design/ant-design-mobile-rn/issues
