### ISSUE TITLE
PullToRefresh 下拉刷新，出现页面闪烁问题

### ISSUE THREAD

**Issue by DreamLee1997** [ant-design/ant-design-mobile#4528]
### Version of antd-mobile

5.0.0-beta.25

### Operating system and its version

iOS

### Browser and its version

ios 14

### What happened?

长滑动touchMove时不抖动，之前2x 3x 都没有抖动现象

**Comment by awmleer** [comment]
可以先参考下 #4410
不过我也再试试组件库能不能优化一下

**Comment by DreamLee1997** [comment]
![image](https://user-images.githubusercontent.com/47883119/145329417-1d44f460-8260-40e6-acc2-a09b683abbe8.png)
最后是啥解决办法？

**Comment by DreamLee1997** [comment]
> 先参考下#4410 不过我也可以再能力组件库能不能优化一下

![image](https://user-images.githubusercontent.com/47883119/145329516-496d5403-3561-4345-85bf-2070da8566cb.png)
zuihou最后是啥解决办法？讲的有点模糊

**Comment by awmleer** [comment]
@DreamLee1997 你用的浏览器是什么？是 iOS Safari 么，还是什么其他 app 的内置浏览器？

**Comment by DreamLee1997** [comment]
> @DreamLee1997你用的浏览器是什么？是iOS Safari么，还是什么其他app的内置浏览器？

是ios，Safari、还有 qq、微信app内打开都有这个问题

**Comment by sarufarr** [comment]
我遇到过类似的问题
解决的思路是
1.固定 `html` 不触发容器内默认浏览器下拉行为，比如下拉之后出现的浏览器自带的重载等功能交互区域
2.当前下拉功能在 `PullToRefresh` 的父级元素内实现

修改触发高度应该也可以一定程度饮鸩止渴

**Comment by hg2990656** [comment]
@DreamLee1997 @awmleer 遇到同样的问题，最后通过给外层的父容器添加一个 touchmove 事件监听解决了：
 const el = document.querySelector('.scrolled-main');
 if (el) {
      el.addEventListener('touchmove', () => {});
 }

**Comment by awmleer** [comment]
#4800 已修复
