### ISSUE TITLE
怎么在umi中引入国际化组件?

### ISSUE THREAD

**Issue by Kujo-Jotaro-AAAAA** [ant-design/ant-design-mobile#4531]
### Version of antd-mobile

2.3.4

### Description

https://mobile.ant.design/zh/components/config-provider
如何按照这个方式引入到umi里？

- app.tsx
`
export const dva = {
  config: {
    onError(err: any) {
      err.preventDefault()
      console.warn(err)
    }
  }
}
export function render(oldRender) {
  oldRender()
}

`

**Comment by awmleer** [comment]
v2 已停止维护了，可以考虑升级一下

**Comment by Kujo-Jotaro-AAAAA** [comment]
> v2 已停止维护了，可以考虑升级一下

3q。。。  但是老项目不敢升级
