### ISSUE TITLE
width使用fit-content在ios的safari或者webview时会出现样式bug

### ISSUE THREAD

**Issue by youmeigc** [ant-design/ant-design-mobile#4536]
### Version of antd-mobile

5.0.0.0-rc2.0

### Operating system and its version

iOS

### What happened?

![image](https://user-images.githubusercontent.com/34414026/145500892-3c884cfb-f0a1-4e3c-bed1-f15ddf25a465.png)

![image](https://user-images.githubusercontent.com/34414026/145500992-501458ab-475b-40ae-a36a-c4f2ab7457e1.png)

原因是：
.adm-toast-mask .adm-toast-wrap {
width: -webkit-fit-content;  // 这个属性
width: fit-content; // 这个属性
}
导致ios样式出现bug
将width的值改为auto后正常

**Comment by liangskyli** [comment]
fit-content确实在ios上部分机型有问题，之前忘记提bug

**Comment by awmleer** [comment]
Fixed via 6f4aa4b3a.

**Comment by awmleer** [comment]
同时把项目全部 `fit-content` 的使用都移除了：

https://caniuse.com/mdn-css_properties_width_fit-content
https://caniuse.com/mdn-css_properties_height_fit-content
