### ISSUE TITLE
InfiniteScroll 无限滚动无法处理异常情况

### ISSUE THREAD

**Issue by scliuyang** [ant-design/ant-design-mobile#4538]
### Description

InfiniteScroll 只有hasMore的属性，假如我接口请求出错loadmore抛出一个error，这时候InfiniteScroll会一直loading无法结束
![image](https://user-images.githubusercontent.com/12167648/145532161-c912b666-5605-41c9-b813-7cb729f13f5c.png)
希望能像vant一直支持error属性
https://youzan.github.io/vant/#/zh-CN/list
![image](https://user-images.githubusercontent.com/12167648/145532299-c87cad59-79a4-4f54-be26-4cf8093781da.png)

**Comment by awmleer** [comment]
@scliuyang 可以提供一下你使用的 antd-mobile 的版本号么？升级到最新版试试？这个 bug 之前修复过

**Comment by awmleer** [comment]
噢我知道了，之前修过的是 PullToRefresh，这个 bug 我来处理一下哈

**Comment by awmleer** [comment]
如果要增加 `error` 属性的话，涉及到交互和组件逻辑的调整了，短期内应该不会做，目前可以自己在 `loadMore` 的函数中 `catch` 一下报错，然后再做相应的处理（例如弹个 Toast）

**Comment by awmleer** [comment]
这个我后面和设计师讨论一下，等交互确定了再优化

**Comment by HiXiaoJ** [comment]
**版本**：antd-mobile@5.7.0
**出现原因**：InfiniteScroll组件源码并没有对错误进行处理。由于你的loadMore请求失败，await后面的不会进行，那么check()函数就没有存在的意义了，因为此时nextFlagRef.current !== flag一直为true。
![image](https://user-images.githubusercontent.com/30550752/158945190-d91bcfb0-534b-48a4-a4c3-f1685a86deb4.png)

**建议方法**
接口：
![image](https://user-images.githubusercontent.com/30550752/158946793-e58a998e-e6b5-4bde-b740-cf1ea8f3a990.png)

错误或加载展示：
![image](https://user-images.githubusercontent.com/30550752/158947003-ad0026bb-00ed-4ae3-a12a-82dbb7ea49d6.png)

**Comment by awmleer** [comment]
我最近来看一下

**Comment by Es-Rell** [comment]
loadMore函数内捕捉错误并且把hasMore设为false可以解决

**Comment by awmleer** [comment]
> loadMore函数内捕捉错误并且把hasMore设为false可以解决

这样未必合理，有可能用户网络不好导致某一次请求出现了错误，这时候并不能简单当作 hasMore 为 false

**Comment by awmleer** [comment]
update 一下，目前推荐的方案是业务中自己在 loadMore 内部做一层 try catch，至于有没有更好的方案，还得再看看……

**Comment by dingziqi** [comment]
> update 一下，目前推荐的方案是业务中自己在 loadMore 内部做一层 try catch，至于有没有更好的方案，还得再看看……

loadMore 里 catch 会有问题，我现在就是 loadMore 里 catch，然后返回一个 `Promise.resolve()`，但是这个时候就会继续执行后续的 `setFlag` 从而导致 reRender，reRender 后又执行了 useEffect 里的 check，因为实际是加载失败了，所以 check 里的 `current >= elementTop - props.threshold` 永远是 true，又进到下一轮的 reRender 了。这样就一个死循环了....

```js
  const check = useMemoizedFn(async () => {
    if (nextFlagRef.current !== flag) return
    if (!props.hasMore) return
    const element = elementRef.current
    if (!element) return
    if (!element.offsetParent) return
    const parent = getScrollParent(element)
    if (!parent) return
    const rect = element.getBoundingClientRect()
    const elementTop = rect.top
    const current = isWindow(parent)
      ? window.innerHeight
      : parent.getBoundingClientRect().bottom
    if (current >= elementTop - props.threshold) {
      const nextFlag = {}
      nextFlagRef.current = nextFlag
      await doLoadMore() // 如果这里不reject的话，会继续往下执行setState
      setFlag(nextFlag)
    }
  })
```

**Comment by awmleer** [comment]
的确会这样，或许应该加载失败的时候显示一个“加载失败，点击重试”之类的文案，我改天试试

**Comment by awmleer** [comment]
f6444f4a6 已支持，下个版本发布

**Comment by TMRnoMEM** [comment]
> [f6444f4](https://github.com/ant-design/ant-design-mobile/commit/f6444f4a6ec75e6dbc03a9f23d4db750a54469c5) 已支持，下个版本发布

```ts
  const doLoadMore = useLockFn(async (isRetry: boolean) => {
    try {
      await props.loadMore(isRetry)
    } catch (e) {
      setFailed(true)
      throw e
    }
  })
```

这里throw 导致这个问题还是没有解决

**Comment by awmleer** [comment]
@TMRnoMEM 具体是啥问题？

**Comment by TMRnoMEM** [comment]
> @TMRnoMEM 具体是啥问题？

loadMore 里面抛出一次异常以后 点击重新加载可以正常加载一次 然后就无法再次触发loadMore了
```
nextFlagRef.current !== flag
```
因为这个条件永远是 `true`

**Comment by awmleer** [comment]
@TMRnoMEM 感谢反馈，我又修复了一下： 773a675b

**Comment by TMRnoMEM** [comment]
> @TMRnoMEM 感谢反馈，我又修复了一下： [773a675](https://github.com/ant-design/ant-design-mobile/commit/773a675bf14fb1648ef547b961806817fdf9242a)

似乎还是有点问题，重试如果不成功的话，就进入死循环了，是不是应该是这样子的

```ts
  function retry() {
    setFailed(false)
    doLoadMore(true).then(() => setFlag(nextFlagRef.current));
  }
```

**Comment by awmleer** [comment]
诶我这里正常啊，并没有出现死循环

**Comment by TMRnoMEM** [comment]
在重试的时候 `doLoadMore(true)` 之后的 `setFlag` 会触发重新渲染
重新渲染触发check的时候 如果满足 `current >= elementTop - props.threshold`这个条件 就会进入死循环

**Comment by awmleer** [comment]
我发现在 React 18 下才会出现这个死循环的问题，React 17 就正常 @TMRnoMEM 你的环境是不是也是 React 18？

**Comment by TMRnoMEM** [comment]
是的

**Comment by awmleer** [comment]
感谢指正，已修复 434b9805

**Comment by awmleer** [comment]
还顺便优化了一下 `check()` 的性能，加了个 100ms 的限流： 6412725b

**Comment by YernarT** [comment]
问题从代码层面得到了解决。但是官方文档并没有更新文案和示例代码。都一年了.. 就没人贡献个示例嘛, 哈哈啊哈

**Comment by shinymm** [comment]
所以要怎么解决这个loadMore 接口失败后，无限重试的问题？
