### ISSUE TITLE
Picker选择器可否支持当前选中项样式处理

### ISSUE THREAD

**Issue by mzl2333** [ant-design/ant-design-mobile#4539]
### Version of antd-mobile

5.0.0-beta19

### What is this feature about?

当前选中条目样式与未选中样式类名一致，无法单独处理，修改后会影响所有类目样式，可否单独增加选中类目样式

**Comment by awmleer** [comment]
直接加 CSS 类的话感觉不是很优雅，倒是可以加个 `data-selected="true"`

**Comment by yangdepp** [comment]
https://github.com/ant-design/ant-design-mobile/pull/4547

**Comment by yangdepp** [comment]
> 直接加 CSS 类的话感觉不是很优雅，倒是可以加个 `data-selected="true"`

我看了一下，其实当前是支持自定义选中类目样式的，只是实现起来比较麻烦
利用`columns`的第二个类型`(value: PickerValue[]) => PickerColumn[]`

以下是代码：
```jsx
const customColumnItem = [
  ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N'],
]

function RenderCustomColumnItem() {
  const [visible, setVisible] = useState(false)
  const [value, setValue] = useState<(string | null)[]>([])
  const [selectedValue, setSelectedValue] = useState<(string | null)[]>(['A'])

  const renderColumns = () => {
    return customColumnItem.map(item => {
      return item.map(item => {
        return {
          label: (
            <div
              style={{
                color: `${item === selectedValue[0] ? 'blue' : 'red'}`,
              }}
            >
              {item}
            </div>
          ),
          value: item,
        }
      })
    })
  }

  return (
    <Space align='center'>
      <Button
        onClick={() => {
          setVisible(true)
        }}
      >
        选择
      </Button>
      <Picker
        columns={renderColumns}
        visible={visible}
        onCancel={() => {
          setVisible(false)
          if (value[0]) {
            setSelectedValue(value)
          }
        }}
        onClose={() => {
          setVisible(false)
        }}
        onConfirm={setValue}
        onSelect={setSelectedValue}
      />
      {value ? value : '未选择'}
    </Space>
  )
}
```


目前我觉得存在的问题：
1. 如果传入的数据有重复的值如`['1', '1', '2']`，这时候控制台会报错，这个是要靠用户在传入前自觉去重一下吗？还是说提供一个`api`允许用户指定`key`，例如上面例子`renderColumns`中，手动指定一个`key`后就按用户这个`key`来。
2. 或者是否考虑给`PickerColumnItem`加一个用户可以自定义的属性，例如用户想要在`onConfirm` 或者 `onSelect`的回调中拿到选中项的索引，在上面例子`renderColumns`中用户指定一个`index`属性，就可以在`onConfirm` 或者 `onSelect`的回调中拿到自己自定义的属性了。

**Comment by awmleer** [comment]
首先第一个问题哈
`['1', '1', '2']` 这其实不是一个合法的参数，因为它等效于：
```
[
  {value: '1', label: '1'},
  {value: '1', label: '1'},
  {value: '2', label: '2'},
]
```
这其中 `value` 出现了重复，而 Picker 组件是不允许 `value` 重复的，这肯定是不合乎逻辑的
所以在内部的渲染中，我们是用的 `value` 作为元素的 `key`，这是基于 `value` 是唯一的前提下的

**Comment by yangdepp** [comment]
> 而第二个问题，我感觉暂时还是先不要加比较好，如果用户有需求自己附加一些额外的数据，可以考虑自行维护一个 `value -> 自定义数据` 的 map

嗯，如果1不是问题，那2放心大胆的自己维护确实也没啥关系。
