### ISSUE TITLE
Picker 选择器点开，当前选中条目上面的条目默认与选中条目颜色一样，之后马上变更为灰色

### ISSUE THREAD

**Issue by mzl2333** [ant-design/ant-design-mobile#4540]
### Version of antd-mobile

5.0.0-beta19

### Browser and its version

app内部webview

### What happened?

预期效果：选中条目上方直接展示为灰色，不要闪烁
描述：在浏览器上展示无任何问题
但在app内部的webview里展示会存在这个问题

https://user-images.githubusercontent.com/26270385/145541803-056796c8-beab-436b-aec3-b4b7e0a51d5b.mp4

**Comment by mzl2333** [comment]
Picker选择器

**Comment by awmleer** [comment]
这个是已知问题，之前我排查过，感觉大概率是 iOS Safari 的 bug

**Comment by awmleer** [comment]
Fixed via 6aa775b89.

**Comment by wwwxy80s** [comment]
确定这个修好了么，试了下官网的DatePicker的自定义每列的渲染内容demo，依然能复现。
自行尝试设置了value/defaultValue也能复现。
设备iphone 12、chrome 96.0.4664.116

**Comment by GOWxx** [comment]
> 确定这个修好了么，试了下官网的DatePicker的自定义每列的渲染内容demo，依然能复现。

用的哪一版本的 antd-mobile 呀

**Comment by wwwxy80s** [comment]
> > 确定这个修好了么，试了下官网的DatePicker的自定义每列的渲染内容demo，依然能复现。
> 
> 用的哪一版本的 antd-mobile 呀

v5.0.0-rc.7

**Comment by GOWxx** [comment]
> v5.0.0-rc.7

这就是我没有双持设备的劣处了，我 Android 设备复现不了，没得看

**Comment by awmleer** [comment]
@wwwxy80s 我这里官网 demo 是正常的，iOS 15.1.1 Safari

**Comment by wwwxy80s** [comment]
https://user-images.githubusercontent.com/12374094/147313309-df6ca9da-5c10-4a54-8f6f-36cc3c76adcf.MOV
https://user-images.githubusercontent.com/12374094/147313340-f2bd8a74-93c7-4d2e-9154-1a896919a2d9.MOV

我这能复现ios15.2

**Comment by wwwxy80s** [comment]
> Upload.from.GitHub.for.iOS.MOV 
>  Upload.from.GitHub.for.iOS.MOV 
> 我这能复现ios15.2

试了另一个Iphone，也没问题，可能只是特定版本的safari有问题

**Comment by awmleer** [comment]
https://user-images.githubusercontent.com/16526078/147318555-5d570f8f-e355-465c-b133-431544f56731.MOV

感觉是的

**Comment by whao0329** [comment]
这个问题解决了吗?

**Comment by awmleer** [comment]
@whao0329 后来已经彻底解决了，你遇到这个 bug 了么？

**Comment by whao0329** [comment]
> @whao0329 后来已经彻底解决了，你遇到这个 bug 了么？

用的是17版本, 目前在企业微信内嵌浏览器中还是可以复现

**Comment by awmleer** [comment]
@whao0329 升级到最新版本，这个修复是在 rc.23 版本中发布的

<img width="709" alt="image" src="https://user-images.githubusercontent.com/16526078/154401212-70f21ed7-46af-44f8-a04f-0b5078e64547.png">
