### ISSUE TITLE
Collapse 折叠面板想在展开和关闭时显示不同图标，能不能支持？以及这个是否支持动画？

### ISSUE THREAD

**Issue by wangyuan0108** [ant-design/ant-design-mobile#4545]
### Version of antd-mobile

5.0.0-rc.4

### What is this feature about?

上次更新加入了自定义图标，但是看到有这样的使用场景，比如没有展开的时候显示`+`，展开之后显示`-`。或者展开的时候是显示上三角，而不展开显示的是下三角。

**Comment by GOWxx** [comment]
展开和关闭时是可以显示不同图标的，通过控制 ```arrow``` 属性的值
例如 [这个demo里](https://codesandbox.io/s/infallible-bhaskara-c2lg9?file=/src/App.tsx)  如果所示
![image](https://user-images.githubusercontent.com/12870715/145762643-6ef5bbf1-a34a-4e01-b976-e364e2c6b170.png)

但现在有个问题是，它自带一个旋转动画，这不友好
在自定义icon的时候应该去掉旋转动画，或者加个参数并多加几个参数来控制旋转动画? 用字符串来表示角度吗?

| 属性				| 说明					| 类型																									| 默认值	|
| ----------------	| --------------------	| ------------------------------------------------------------------------------------------------------| -------|
| rotate			| 旋转动画			    | `"0" \| "90" \| "180"`																				| `"90"`|

或者是布尔值，```true``` 或 ```false```
 或者是函数作为参数？ 这里得等 @awmleer 看一下怎么设计

**Comment by yangdepp** [comment]
> ### Version of antd-mobile
> 5.0.0-rc.4
> 
> ### What is this feature about?
> 上次更新加入了自定义图标，但是看到有这样的使用场景，比如没有展开的时候显示`+`，展开之后显示`-`。或者展开的时候是显示上三角，而不展开显示的是下三角。



以手风琴为例：使`Collapse`受控，根据`activeKey`自定义`Collapse.Panel`的arrow即可
```jsx
      const [activeKey, setActiveKey] = useState<string | null>('')
      <Collapse accordion activeKey={key} onChange={setActiveKey}>
        {['1', '2', '3'].map((item, index) => {
          return (
            <Collapse.Panel
              key={`${index}`}
              title={`第${index + 1}项`}
              arrow={activeKey=== `${index}` ? <MinusCircleOutline /> : <PlayOutline />}
            >
              手风琴模式只能同时展开一个
            </Collapse.Panel>
          )
        })}
      </Collapse>
```
非手风琴样式，判断`index`是否存在activeKey的数组中就可以了。

**Comment by awmleer** [comment]
挂个之前讨论的链接，当时 @zqran 的确是考虑到了这个 issue 里描述的这种情况了，但是 API 最后被砍了……

https://github.com/ant-design/ant-design-mobile/pull/4526#discussion_r765396451

**Comment by awmleer** [comment]
可以考虑把 `(active: boolean) => React.ReactNode` 这个类型再加上……让 arrow 的类型变成

```ts
ReactNode | ((active: boolean) => React.ReactNode)
```

如果是 ReactNode，就还是由 antd-mobile 来控制旋转动画的，而如果是 function，就由用户自己完全来控制不同状态下的动画、图标等各种效果
就是不知道这样会不会有些隐晦

@zqran 老哥很有先见之明……

**Comment by zqran** [comment]
@awmleer 我来改下吧~

> 就是不知道这样会不会有些隐晦

这点是不是得看 `render-props` 的普及程度~

**Comment by awmleer** [comment]
@zqran ook 那到时候我们文档上注明一下

**Comment by zqran** [comment]
@awmleer 是不是允许 `render-props` 和 ReactNode 的混用？比如，像下面示例一样：

```tsx
<Collapse
  defaultActiveKey={['1']}
  arrow={active => active ? <CheckCircleOutline /> : <CloseCircleOutline />}
>
  <Collapse.Panel key='1' title='第一项'>
    这里是第一项的内容
  </Collapse.Panel>
  <Collapse.Panel key='2' title='第二项' arrow={<MinusCircleOutline />}>
    这里是第二项的内容
  </Collapse.Panel>
  <Collapse.Panel key='3' title='第三项' arrow={active => active ? <SomeOpenIcon /> : <SomeCloseIcon />}>
    这里是第三项的内容
  </Collapse.Panel>
</Collapse>
```

**Comment by wangyuan0108** [comment]
之前看到@zqran说这个点了，最后想了下，确实有使用场景，就提出来了

**Comment by awmleer** [comment]
> 

@zqran 嗯嗯是的，可以混用的
