### ISSUE TITLE
Dialog组件的getContainer失效

### ISSUE THREAD

**Issue by 1548583993** [ant-design/ant-design-mobile#4546]
### Version of antd-mobile

v5.0.0-rc.4

### Description

v5.0.0-rc.4，Dialog组件的getContainer属性失效了，设置自定义父容器无效。

**Comment by GOWxx** [comment]
给个复现 Demo ? https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx
我 [在这里写了下demo](https://codesandbox.io/s/thirsty-dewdney-px9pm?file=/src/App.tsx) 没能复现
是可以通过 ```getContainer``` 属性父容器的
![image](https://user-images.githubusercontent.com/12870715/145765527-b8335286-b275-4c45-8c91-cce17df7f43d.png)

**Comment by 1548583993** [comment]
似乎只是遮罩层在父容器里，adm-dialog还是在外面（adm-mask-content是空div）
![796480201](https://user-images.githubusercontent.com/70678070/145815991-8bb3f461-6952-4175-bfa8-c3c0aa769237.jpg)

**Comment by GOWxx** [comment]
> 似乎只是遮罩层在父容器里，adm-dialog还是在外面（adm-mask-content是空div） ![796480201](https://user-images.githubusercontent.com/70678070/145815991-8bb3f461-6952-4175-bfa8-c3c0aa769237.jpg)

抱歉，我之前没看遮罩层里面的内容，你说的对
只有遮罩层在父容器里，我这也复现了
![image](https://user-images.githubusercontent.com/12870715/145817599-bf3a1b35-4f75-41b7-880c-4100e78b0611.png)

**Comment by awmleer** [comment]
看起来是个 bug

**Comment by awmleer** [comment]
Fixed via b9d50d4ab

**Comment by awmleer** [comment]
下个版本就发布掉了哈，可以关注一下发布日志

**Comment by 1548583993** [comment]
谢谢

**Comment by jinjinyike** [comment]
> > 似乎只是遮罩层在父容器里，adm-dialog还是在外面（adm-mask-content是空div） ![796480201](https://user-images.githubusercontent.com/70678070/145815991-8bb3f461-6952-4175-bfa8-c3c0aa769237.jpg)
> 
> 抱歉，我之前没看遮罩层里面的内容，你说的对 只有遮罩层在父容器里，我这也复现了 ![image](https://user-images.githubusercontent.com/12870715/145817599-bf3a1b35-4f75-41b7-880c-4100e78b0611.png)

版本：5.0.0-rc.12  Modal组件 有同样的问题呢

**Comment by awmleer** [comment]
> 版本：5.0.0-rc.12 Modal组件 有同样的问题呢

@jinjinyike 感谢反馈，Modal 刚刚也修复了： b0e4ffcbf
