### ISSUE TITLE
Switch 提供非受控模式 

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#455]
现在只能是受控组件。

https://github.com/ant-design/ant-design-mobile/blob/68efda75d9135a9664f4ba0eb86652ad0cf51384/components/switch/index.tsx#L8

https://github.com/ant-design/ant-design-mobile/blob/68efda75d9135a9664f4ba0eb86652ad0cf51384/components/switch/index.web.tsx#L9

**Comment by silentcloud** [comment]
fixed in f8cb412f8360719140e17eef22df59bda75191f1
