### ISSUE TITLE
ProgressCircle组件的build上线后circle标签的adm-progress-circle-track和adm-progress-circle-fill的CSS 变量计算属性失效

### ISSUE THREAD

**Issue by sailormillet** [ant-design/ant-design-mobile#4551]
### Version of antd-mobile

^5.0.0-rc.4

### What happened?

Version of antd-mobile
^5.0.0-rc.4

Description
^5.0.0-rc.4，ProgressCircle组件本地demo样式是好的，打包上线后，circle标签的adm-progress-circle-track和adm-progress-circle-fill的CSS 变量计算属性失效
本地开发
![image](https://user-images.githubusercontent.com/16287657/145819625-f26d715b-5653-4341-a52e-c36baa42911d.png)
build上线后
![image](https://user-images.githubusercontent.com/16287657/145819737-e996a3a2-2c27-4122-8b5d-48ced1bf1186.png)

**Comment by awmleer** [comment]
很奇怪，根据你的截图来看，CSS 变量似乎是没有失效的

**Comment by awmleer** [comment]
可以给个复现 demo 么

**Comment by sailormillet** [comment]
> demo很普通,开始觉得是可能是我webpack配置导致的，然后我就重新起了一个新项目
 npx create-react-app demo-fed
安装and-mobile最新版本，直接写下面的代码
`
import {  ProgressCircle } from 'antd-mobile'
<ProgressCircle percent={50}>50%</ProgressCircle>

`
本地开发看着没问题，很顺利展示出来了，所以就没写Sandbox ，build上线后发现还是没有进度圈。样式打包的看着都是对的，引用的变量也是对的，circle标签的样式正常来说应该是47px，但是却是94px

**Comment by awmleer** [comment]
莫非你混用了 `antd-mobile` 和 `antd-mobile/2x` ？

**Comment by sailormillet** [comment]
没有混用,但是我排查了一下，其他的css变量都生效了，我的项目这样修改了一下，build上线展示没问题
![image](https://user-images.githubusercontent.com/16287657/146005021-c90c3438-4c46-4fdb-95b7-d9417989ed3f.png)
但是本地看进度条83%却
![image](https://user-images.githubusercontent.com/16287657/146005261-cc95c5df-fb2e-4d2b-bd88-a5d937ef89c5.png)
上线后进度展示正常83%
![image](https://user-images.githubusercontent.com/16287657/146005410-4a1a1aee-ab11-40ba-91b7-29dbc785d999.png)
很奇怪，我看变量都设置的是一样的从chrome上看，本地和线上的css

**Comment by awmleer** [comment]
感觉不是 antd-mobile 的问题……像是你自己项目中打包构建的逻辑问题
可以看看是不是加了 postcss 什么的配置

**Comment by sailormillet** [comment]
没有加,我后来直接用的react-scripts build构建上线的

**Comment by awmleer** [comment]
@sailormillet 要不给个可以复现的工程包 zip？

**Comment by allenpzx** [comment]
遇到类似的问题，按照官方的写法，页面上是px不是vw或rmb，确实存在v5和v2共存的情况，因为过去的一些组件还没来的及更新，本地是好的，线上就挂
<img width="1855" alt="image" src="https://user-images.githubusercontent.com/24787963/159876660-eabe6c82-acbf-4a9b-ba34-0cd9e8358f43.png">

**Comment by allenpzx** [comment]
> 莫非你混用了 `antd-mobile` 和 `antd-mobile/2x` ？

确实混用了，出现线上样式失效的问题，请问有什么好的解决方法吗

**Comment by awmleer** [comment]
@allenpzx v2 和 v5 共存是可以的，不会有任何问题，但是 `antd-mobile` 和 `antd-mobile/2x` 是一定不能同时使用的

你的项目为什么要同时使用 `antd-mobile` 和 `antd-mobile/2x`？可以具体描述一下么

**Comment by allenpzx** [comment]
> @allenpzx v2 和 v5 共存是可以的，不会有任何问题，但是 `antd-mobile` 和 `antd-mobile/2x` 是一定不能同时使用的
> 
> 你的项目为什么要同时使用 `antd-mobile` 和 `antd-mobile/2x`？可以具体描述一下么

我不知道理解的对不对，现在项目用的是v5官方的推荐迁移方案，是这两个版本，这两个版本可以共存的吧，我遇到了上述圆环组件的展示问题了
<img width="368" alt="image" src="https://user-images.githubusercontent.com/24787963/160052662-3ccd324b-228a-4fee-853c-8196f0961416.png">

**Comment by awmleer** [comment]
@allenpzx 看你截图的 package.json 是正确的，不太清楚为什么会有你所说的问题，要不你提供一个完整的复现仓库吧（最好单独开一个 issue 哈，这个 issue 会通知到之前参与过的朋友）

**Comment by allenpzx** [comment]
> 

谢谢回复，公司项目没法分享，我邮件回您

**Comment by awmleer** [comment]
@allenpzx 你别发我你公司的真实项目代码呀……精简一下提供一个最小复现 demo 就可以了

**Comment by H-Sven** [comment]
遇到同样的问题， 请求解决了吗  我也是v2和v5共存

**Comment by qzai666** [comment]
我也遇到这个问题了 我打包后 ProgressCircle 的 percent 属性完全没用

**Comment by qzai666** [comment]
找到问题了 和https://github.com/ant-design/ant-design-mobile/issues/5577一样

我手动把var(--pi) 改成 3.1415926 就好了
