### ISSUE TITLE
提议: FloatingPanel新增onAnchorChange属性

### ISSUE THREAD

**Issue by ryozm** [ant-design/ant-design-mobile#4557]
### Version of antd-mobile

5.0.0-rc.5

### What is this feature about?

当改变当前anchor位置时,即高度改变时,执行onAnchorChange

属性 | 说明 | 类型 | 默认值
-- | -- | -- | --
onAnchorChange | 锚点高度发生改变时的事件 | (sourceHeight: number, targetHeight: number) => void | -

**Comment by awmleer** [comment]
改个名字会更好，`onAnchorChange` 会容易理解为是 anchor 配置变化时触发，改叫 `onHeightChange` 吧

```ts
onHeightChange: (height: number, still: boolean) => void
```

`still` 参数表示的是是否处于静止状态

应该实现方式直接基于 `useSpring` 的一些配置参数就可以了
