### ISSUE TITLE
一个完善的<input type="number"/>的数字输入框

### ISSUE THREAD

**Issue by i-nodejs** [ant-design/ant-design-mobile#4558]
### What is this feature about?

您好，ant-design-mobile的大咖。 版本2+中关于inputItem中的使用，没有得到一个关于<input type="number"/>良好的体验。为了使用数字、负号、点，我们必须让input type=“number”问题如下：

1:数字输入过程中小数点不会change。
2:当输入的数值已不是标准浮点数时，change的值是空串，导致输入框的内容和上游state不一致。
3:chang的信息与输入框的内容不一致，无法校验一个合法的浮点数。
4:input="text"能解决change信息一致问题，但键盘不再是数字键盘。

对于原生input这些问题，虚拟自定义键盘是唯一的解决办法了吗？ 而虚拟键盘现在看来也不是完美的解决方案。 autoFocusSelectAll全选问题、光标移动问题、切换input键盘闪烁问题。

对于以上问题，鄙人胜似头大>_< ，期待可以被启发。

**Comment by i-nodejs** [comment]
曾尝试唤起键盘之后让input type动态改为text已便能实时获取的用户输入字符，iphone看似可以。但是android手机会跟随type的改变实时改变键盘。

**Comment by xiaoyao96** [comment]
可以了解下 `inputMode="numeric"`规定键盘类型，antd-mobile v2是支持的。

**Comment by awmleer** [comment]
```jsx
<input
  type='text'
  pattern='[0-9]*'
  inputMode='numeric'
/>
```

**Comment by awmleer** [comment]
可以考虑升级一下用 v5 的 Input……

**Comment by awmleer** [comment]
这个 issue 先 close 了哈

**Comment by i-nodejs** [comment]
> 可以了解下原生 input的`inputMode`属性，用于设置键盘类型，设置值为`numeric`则使用数字键盘。antd-mobile v2是支持的。
> 
> https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/inputmode

ios下缺失负号。

**Comment by i-nodejs** [comment]
> ```js
> <input
>   type='text'
>   pattern='[0-9]*'
>   inputMode='numeric'
> />
> ```

v2和v5使用此配置，均缺少负号按键。

**Comment by GOWxx** [comment]
> v2和v5使用此配置，均缺少负号按键。

新开一个 issues 吧老哥
