### ISSUE TITLE
提议: FloatingPanel新增visible属性

### ISSUE THREAD

**Issue by ryozm** [ant-design/ant-design-mobile#4559]
### Version of antd-mobile

5.0.0-rc.5

### What is this feature about?

新增visible属性控制是否显示FloatingPanel

属性 | 说明 | 类型 | 默认值
-- | -- | -- | --
visible | 是否可见 | boolean | false

**Comment by awmleer** [comment]
可以用户自己通过 `display: none` 来实现的，而且这种场景太小众了，我觉得 FloatingPanel 不应该支持的
