### ISSUE TITLE
建议加个地图组件

### ISSUE THREAD

**Issue by xubuhang** [ant-design/ant-design-mobile#456]
你好，建议加个地图组件。

**Comment by warmhug** [comment]
这种组件比较独立，自己实现更加灵活

**Comment by chengaide** [comment]
自己加了个百度地图，但是地图好小，不是宽高小，也是地图的缩放比例问题，是视图小，去掉高清解决方案就能用肉眼正常看到地图里的内容，加了高清解决方案就得拿放大镜才能看清地图的内容，请问有遇到这问题，知道怎么解决吗？

**Comment by warmhug** [comment]
@chengaide 建议贴下代码到 github ，会一起看看怎么解决
