### ISSUE TITLE
ImageUploadView 在 Android 上点击没反应

### ISSUE THREAD

**Issue by NARUTOyuyang** [ant-design/ant-design-mobile#4561]
### Description

ImageUploadView 在 Android 上点击没反应

**Comment by GOWxx** [comment]
看到在其他3个 issue 下面也发了同样的内容，但这样多发几遍也没法帮助到你，因为提供的信息是一样的。
如果提供更多的信息，可以更好的帮助到你。

提 bug issue 的页面有指出可以提供哪些基本信息，例如具体哪个版本，手机什么环境，安卓也有很多版本，最好附加一下 demo 或者录像之类的
其中有一句
If possible, please try to attach a sandbox link to reproduce. You can create one from this: https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx
可以通过这个链接来创建一个 demo

**Comment by awmleer** [comment]
@NARUTOyuyang 请提供更详细的信息，我们才能帮你确认问题或是修复

你需要提供的是，你所使用的 antd-mobile 的准确的版本号，一个复现 demo

你在其他 issue 中的重复或不相关的评论我删除掉了哈

**Comment by NARUTOyuyang** [comment]
> @NARUTOyuyang 请提供更详细的信息，我们才能帮你确认问题或是修复
> 
> 你需要提供的是，你所使用的 antd-mobile 的准确的版本号，一个复现 demo
> 
> 你在其他 issue 中的重复或不相关的评论我删除掉了哈

版本 5.0

**Comment by NARUTOyuyang** [comment]
这个问题是在 Android APP 内置浏览器点击没反应，但是在手机浏览器是可以的

**Comment by NARUTOyuyang** [comment]
> @NARUTOyuyang 请提供更详细的信息，我们才能帮你确认问题或是修复
> 
> 你需要提供的是，你所使用的 antd-mobile 的准确的版本号，一个复现 demo
> 
> 你在其他 issue 中的重复或不相关的评论我删除掉了哈

这个问题是在 Android APP 内置浏览器点击没反应，但是在手机浏览器是可以的，版本是 antd mobile 5

**Comment by awmleer** [comment]
v5 哪有 ImageUploadView 组件啊？猜测你是想说 ImageUploader？

**Comment by awmleer** [comment]
而且你说“Android APP 内置浏览器”，可以说一下具体是什么 APP 的什么内置浏览器么？你看起来是你 APP 的限制

**Comment by NARUTOyuyang** [comment]
@awmleer 对的，现在 app 原生在看，请问这个支持上传 pdf 么

**Comment by zhangmei1021** [comment]
请问下  Android APP 内置浏览器点击没反应，但是在手机浏览器是可以的，这个问题你们最后是怎么解决的？

> > @NARUTOyuyang 请提供更详细的信息，我们才能帮你确认问题或是修复
> > 你需要提供的是，你所使用的 antd-mobile 的准确的版本号，一个复现 demo
> > 你在其他 issue 中的重复或不相关的评论我删除掉了哈
> 
> 这个问题是在 Android APP 内置浏览器点击没反应，但是在手机浏览器是可以的，版本是 antd mobile 5

请问下  Android APP 内置浏览器点击没反应，但是在手机浏览器是可以的，这个问题你们最后是怎么解决的？

**Comment by JesusCracker** [comment]
在某些app内置浏览器里面（就拿微信为例），不要设置multiple属性，就可以正常拉起系统文件选项。猜测可能因为微信里面浏览器的逻辑层内核有差异。
