### ISSUE TITLE
Ellipsis 组件文本不展示

### ISSUE THREAD

**Issue by Liyi-up** [ant-design/ant-design-mobile#4562]
### Version of antd-mobile

5.0.0-rc.0

### Browser and its version

Edge

### What happened?

Ellipsis组件再传入两属性direction="end" content='内容'时，页面上并不展示内容，而是只有省略符号...如下
<br>
  其中item?.houseAddress!变量对应的是效果图中下方红框部分，在效果图中能够清晰的看到，变量存在值，且H6标签正常渲染但是Ellipsis组件渲染出现问题，检查发现dom节点中的内容只有"..."
![代码](https://s4.ax1x.com/2021/12/15/TS49R1.png)<br>
效果图如下：
![效果图](https://s4.ax1x.com/2021/12/15/TS4EZD.png)
<br>
dom节点：![TS5PYj.png](https://s4.ax1x.com/2021/12/15/TS5PYj.png)

**Comment by GOWxx** [comment]
v5.0.0-rc.1 中已修复了这个bug，可以看一下 release
https://github.com/ant-design/ant-design-mobile/releases/tag/v5.0.0-rc.1
