### ISSUE TITLE
[DatePicker] 当 datePickerPrecision 是 week 时组件的值错误

### ISSUE THREAD

**Issue by GOWxx** [ant-design/ant-design-mobile#4563]
### Version of antd-mobile

5.0.0-rc.5

### Operating system and its version

Android

### Browser and its version

win10 chrome V96 模拟移动端设备

### Sandbox to reproduce

https://codesandbox.io/s/red-cache-stwuv?file=/src/App.tsx

### What happened?

```const now = new Date(); // 以当前时间为初始值 now``` 
点击按钮呼的预期行为：
点击按钮呼出浮窗 -> ```datePicker```展示此时的年/月/周/日 -> 点击确定 值不变

在精度是 年、月、日 时，该行为正确
但当精度是周时：
点击按钮呼出浮窗 -> ```datePicker```展示了错误时间 -> 点击确定 时间值也被改变成错误的时间。

![image](https://user-images.githubusercontent.com/12870715/146189773-9485b3d9-c516-4e40-9125-4a96c303c690.png)

观察：
1. 第一次点击 自然周按钮 时，```datePicker```是错误的时间，取消浮窗后，再点 自然周按钮呼出```datePicker```，时间会正确。
2. 在第一步操作结束，自然周```datePicker```正确后，取消浮窗，点击 自然月按钮 此时```datePicker```展示的时间错误。
3. 第二步中的自然月，换成自然日也可以，当周正确后，自然日也会错误。
3. 有使用 ```dayjs```，并使用 ```isoWeek``` 插件，但我也打印了原生 ```Date``` 的数据，可以看出二者时间是相同的。

**Comment by awmleer** [comment]
是 React 的 batch update 导致的，这里加一下 `flushSync` 会发现就正常了：

<img width="401" alt="image" src="https://user-images.githubusercontent.com/16526078/146337601-45321e0b-8806-4d10-b98b-6e0e8a390e04.png">

我想想看组件库怎么优化一下

**Comment by awmleer** [comment]
Fixed via 41b36de72
