### ISSUE TITLE
TabBar在Android端flex失效

### ISSUE THREAD

**Issue by crazysunnylong** [ant-design/ant-design-mobile#4564]
### Version of antd-mobile

v5.0.0-rc.4

### Description
使用Android端的webview内嵌h5的链接的方式；
TabBar在Android端没有沉底，首页的高度样式只有文字的高度，见如下图所示：
![image](https://user-images.githubusercontent.com/8319984/146295496-ccce813b-c50b-4cdd-8ba0-99d7514f334e.png)

**Comment by crazysunnylong** [comment]
使用Android端的webview内嵌h5的链接的方式时出现如上问题

**Comment by GOWxx** [comment]
TabBar 组件只是一个块级元素，不会自动沉底的，你需要自己写样式来达到这个需求
可以参照文档 ```TabBar``` 组件的 [demo2](https://mobile.ant.design/zh/components/tab-bar), 看 demo2.less 里的内容

**Comment by crazysunnylong** [comment]
@GOWxx 你好大神，感谢能解答。
demo2.less我也引用了，现在出现的情况是，普通浏览器Chrome没有问题，可能是Android app壳不兼容的问题，有没有这方面的解决方案？

**Comment by GOWxx** [comment]
> @GOWxx 你好大神，感谢能解答。 demo2.less我也引用了，现在出现的情况是，普通浏览器Chrome没有问题，可能是Android app壳不兼容的问题，有没有这方面的解决方案？

我不是大神噶，我是以为你没写这部分样式。
app壳不兼容这种我不会处理，等懂的老哥们过来看啦

**Comment by crazysunnylong** [comment]
已经解决了，thx！@GOWxx 加上display: -webkit-flex; 问题解决
`
.box{
  display: -webkit-flex; /* Safari */
  display: flex;
}`
