### ISSUE TITLE
TextArea组件字数限制在ios中输入表情出现超出字数的情况

### ISSUE THREAD

**Issue by zk8080** [ant-design/ant-design-mobile#4570]
### Version of antd-mobile

v5.0.0-rc.4

### Operating system and its version

iOS

### Browser and its version

safari

### What happened?

在Ios中，设置字数限制后，输入文字和ios自带表情，会出现超出字数限制的情况。在官网demo中即可复现：
![](https://cdn.mobilemd.cn/tos-design/WechatIMG143.jpeg)

**Comment by awmleer** [comment]
超出字数限制是指？

**Comment by zk8080** [comment]
> 超出字数限制是指？

截图中的字数限制一栏，maxLength属性为30，应该是最多输入30个字符，现在输入表情的话，出现了46个字符。使用文字就没有这个问题。

**Comment by awmleer** [comment]
噢还真是，我看下

**Comment by awmleer** [comment]
在 Chrome 和 Safari 中的行为是不一样的，浏览器的蜜汁问题

Chrome：
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/16526078/146345818-9bd9938c-59a7-4409-bf7a-8584ef622bc9.png">

Safari：
<img width="430" alt="image" src="https://user-images.githubusercontent.com/16526078/146345847-562ee702-7ab5-49fe-aa23-ab7d6b31df16.png">

**Comment by zk8080** [comment]
那这个会解决吗😂，目前项目里使用onchange判断value的长度来阻止输入，又会导致输入的时候不流畅。

**Comment by awmleer** [comment]
@zk8080 容我最近先调研一下哈

**Comment by zk8080** [comment]
> @zk8080 容我最近先调研一下哈

好的，谢谢大佬🙏

**Comment by tangyefei** [comment]
@awmleer 应用开发过程同样遇到此类问题，版本是 v5.0.0-rc.3，求修复计划。

**Comment by awmleer** [comment]
似乎和这个 issue 相关：https://github.com/whatwg/html/issues/1467

**Comment by awmleer** [comment]
antd 相关的 issue：https://github.com/ant-design/ant-design/issues/27612

**Comment by awmleer** [comment]
Fixed via 870f6864f
