### ISSUE TITLE
DatePicker 不能正确回显

### ISSUE THREAD

**Issue by khckz** [ant-design/ant-design-mobile#4573]
### Version of antd-mobile

v5.0.0-rc.6

### Browser and its version

chrome 95

### What happened?

![WechatIMG19](https://user-images.githubusercontent.com/37645424/146354639-4daaa5f7-99c4-4caf-bbe8-edb9d450790c.png)

![WechatIMG20](https://user-images.githubusercontent.com/37645424/146354650-bf5fc010-f672-42c8-9523-fa3a6571d151.jpeg)

![WechatIMG23](https://user-images.githubusercontent.com/37645424/146355229-09f19904-4ab1-44b4-a02c-9ac759d4f4e8.jpeg)

![WechatIMG22](https://user-images.githubusercontent.com/37645424/146354656-eae16736-baf2-4490-a70c-37fcfd15e285.jpeg)

如果直接使用 new Date() 当前日期是可以正确回显的。

**Comment by GOWxx** [comment]
确认项目里用的是 v5.0.0-rc.6 吗？
v5.0.0-rc.6 刚修复了一个 ```DatePicker``` 的 bug
情况与你这个遇到的很相似

**Comment by khckz** [comment]
> 确认项目里用的是 v5.0.0-rc.6 吗？ v5.0.0-rc.6 刚修复了一个 `DatePicker` 的 bug 情况与你这个遇到的很相似

是的

**Comment by GOWxx** [comment]
> > 确认项目里用的是 v5.0.0-rc.6 吗？ v5.0.0-rc.6 刚修复了一个 `DatePicker` 的 bug 情况与你这个遇到的很相似
> 
> 是的

你 `setFieldsValue` 的值是 `{birthday: d}`
这里  `DatePicker` 的 `value` 类型应该是 `Date`
你传进去个 `number`

**Comment by khckz** [comment]
> > > 确认项目里用的是 v5.0.0-rc.6 吗？ v5.0.0-rc.6 刚修复了一个 `DatePicker` 的 bug 情况与你这个遇到的很相似
> > 
> > 
> > 是的
> 
> 你 `setFieldsValue` 的值是 `{birthday: d}` 这里 `DatePicker` 的 `value` 类型应该是 `Date` 你传进去个 `number`

我又包了一层 new Date(), 看图中打印的“d” 就是 date 类型的

**Comment by GOWxx** [comment]
> > > > 确认项目里用的是 v5.0.0-rc.6 吗？ v5.0.0-rc.6 刚修复了一个 `DatePicker` 的 bug 情况与你这个遇到的很相似
> > > 
> > > 
> > > 是的
> > 
> > 
> > 你 `setFieldsValue` 的值是 `{birthday: d}` 这里 `DatePicker` 的 `value` 类型应该是 `Date` 你传进去个 `number`
> 
> 我又包了一层 new Date(), 看图中打印的“d” 就是 date 类型的

抱歉，我发现了，于是删除了

**Comment by GOWxx** [comment]
> 我又包了一层 new Date(), 看图中打印的“d” 就是 date 类型的

你用这种写法试一下呢，我写了个 demo
https://codesandbox.io/s/brave-hoover-7md2n?file=/src/App.tsx

不监听 `DatePicker` 的 `visible` 的变化
直接设置值，在 `onClick` 的时候
另外不用 `ref` 的方式去获取 `form` 的实例
可以用这个 demo 里的写法
```javascript
const [form] = Form.useForm();
<form form={form}> </form>
```

**Comment by khckz** [comment]
> > 我又包了一层 new Date(), 看图中打印的“d” 就是 date 类型的
> 
> 你用这种写法试一下呢，我写了个 demo https://codesandbox.io/s/brave-hoover-7md2n?file=/src/App.tsx
> 
> 不监听 `DatePicker` 的 `visible` 的变化 直接设置值，在 `onClick` 的时候 另外不用 `ref` 的方式去获取 `form` 的实例 可以用这个 demo 里的写法
> 
> ```js
> const [form] = Form.useForm();
> <Form form={form}> </Form>
> ```
你好，这是DatePicker API中min和max前后10年限制出现的，设置了最小值就可以正常显示了。非常感谢你的帮忙

**Comment by GOWxx** [comment]
> 你好，这是DatePicker API中min和max前后10年限制出现的，设置了最小值就可以正常显示了。非常感谢你的帮忙

原来如此，感谢告知
那这个 issue 你可以 closed 了噶~
