### ISSUE TITLE
ImageViewer图片预览，只能看，缩放图片功能问题太大了。

### ISSUE THREAD

**Issue by luciferyue** [ant-design/ant-design-mobile#4574]
### What is this feature about?

// master/src/components/image-viewer/slide.tsx,第58行代码，这个d的值，在onPinch取出来，很大的，需要加工一下吧，否则，直接用d，每次缩放的比例特别大。maxZoom，就没有意义了，而且好多坑
const [d] = state.offset;
if (d < 0) return;
const zoom = state.last ? Math.max(Math.min(d, props.maxZoom), 1) : d;
api.start({
  zoom,
  immediate: !state.last,
});

**Comment by awmleer** [comment]
Fixed via ae3157b7e

**Comment by Zddu** [comment]
现在安装还是有bug？

**Comment by GOWxx** [comment]
> 现在安装还是有bug？

是用的什么版本呀， bug指的是这条 issue 的内容吗？
这个修复只是提交了，还没发布包含这个修复的版本，可以等待下一版本发布

**Comment by Zddu** [comment]
> > 现在安装还是有bug？
> 
> 是用的什么版本呀， bug指的是这条 issue 的内容吗？ 这个修复只是提交了，还没发布包含这个修复的版本，可以等待下一版本发布

好吧，今天刚用发现这个bug了。。。

**Comment by GOWxx** [comment]
> 

嗯~ 关注一下版本发布哦~

**Comment by awmleer** [comment]
@Zddu 一般 bugfix 一周之内都会发布的哈，可以关注一下发布日志

**Comment by QingGao-github** [comment]
太好啦，今天发的最新版已经把这个bug修掉了！神速，点赞！
