### ISSUE TITLE
ProgressBar 支持通过 css 变量 设置未填充区域的颜色

### ISSUE THREAD

**Issue by preciousmouse** [ant-design/ant-design-mobile#4575]
### Version of antd-mobile

5.0.0-rc.6

### What is this feature about?

目前支持通过 --fill-color 指定填充部分的颜色。
但通过的需求中，需要一同定制未填充区域颜色，希望添加相应 css变量 支持。

**Comment by awmleer** [comment]
可以加个 `--track-color`
