### ISSUE TITLE
Radio文字内容不会自动换行

### ISSUE THREAD

**Issue by JustinXiang** [ant-design/ant-design-mobile#4578]
### Description

Radio的内部内容不会自动换行，设置width百分比值失效，只有设置固定px才有效果，包括Radio本身设置width百分比值也无效，得设置固定px。希望出个--width属性值，可以设置RadioGroup一行可以有多少个Radio，内容可以自动换行

**Comment by lwQin** [comment]
是这个问题吧
<img width="474" alt="Xnip2021-12-22_17-24-16" src="https://user-images.githubusercontent.com/11586662/147069219-298b923a-e666-436d-97b7-2a20dcd98752.png">
我个人比较喜欢用 [Seletor](https://mobile.ant.design/zh/components/selector) 替代 Radio
