### ISSUE TITLE
列表List 建议添加个属性，带 iconfont 图标飞吧

### ISSUE THREAD

**Issue by motorguo** [ant-design/ant-design-mobile#458]
现在只有个 `thumb` ,
iconfont+ 现在的图标可自定义颜色
我觉得这个小小建议，还是个不错的

**Comment by xiaochanghai** [comment]
maybe you could write it like this
i test ,it's work;
----------------------------------------------------------
 <List renderHeader={() => ''} className="my-list">
                            <Item
                                thumb={<Image source={require('../../assets/Mine/icon_mine_friends@2x.png')} style={{ marginRight: 5 }} ></Image>}
                                extra={'创采软件'}
                                arrow="horizontal"
                                onClick={() => { }}
                                onLongPress={this.handleLongPress}>
                                我加入的团队
                                </Item>
                        </List>
------------------------------------------------------------------------------------------------------
