### ISSUE TITLE
 Image组件是否可以添加点击图片预览功能(可以移动，放大，缩小)

### ISSUE THREAD

**Issue by youmeigc** [ant-design/ant-design-mobile#4581]
### What is this feature about?

 Image组件是否可以添加一个与antd组件Image一样的点击图片预览功能（可以移动，放大，缩小）

**Comment by awmleer** [comment]
是另外一个组件 ImageViewer

**Comment by awmleer** [comment]
https://mobile.ant.design/zh/components/image-viewer
