### ISSUE TITLE
Swiper 垂直滚动 设置 loop 为false 直接内容白屏 

### ISSUE THREAD

**Issue by wansuiasdn** [ant-design/ant-design-mobile#4585]
### Version of antd-mobile

5.0.0-beta.27

### Browser and its version

PC firefox

**Comment by awmleer** [comment]
升级一下到最新版试试吧，之前好像修复过这个 bug，可以查一下发布日志

**Comment by yangyipeng001** [comment]
垂直滚动，loop设为true, 滚动计算的位置错误，导致有的不会显示，v5.0.0-rc.12

**Comment by awmleer** [comment]
> 垂直滚动，loop设为true, 滚动计算的位置错误，导致有的不会显示，v5.0.0-rc.12

@yangyipeng001 给个复现 demo？

**Comment by yangyipeng001** [comment]
@awmleer 大佬，https://codesandbox.io/s/objective-neumann-owzqe?file=/src/App.js，简单写了一个demo。

**Comment by yangyipeng001** [comment]
@awmleer 大佬，简单写了一个demo，https://codesandbox.io/s/objective-neumann-owzqe?file=/src/App.js

**Comment by awmleer** [comment]
@yangyipeng001 在使用竖向的 Swiper 的时候，必须得手动设置一下 `--height` CSS 变量，可以看下这个改之后的 sandbox：
https://codesandbox.io/s/antd-mobile-swiper-forked-sld2h?file=/src/App.js

我补充一下官网文档的说明，提示一下大家

**Comment by yangyipeng001** [comment]
@awmleer 👌
