### ISSUE TITLE
Dropdown 点击Dropdown.item需要做额外操作再弹出popup

### ISSUE THREAD

**Issue by denglai** [ant-design/ant-design-mobile#4587]
### Version of antd-mobile

5.0.0-beta.28

### What is this feature about?

场景：点击Dropdown.item元素，菜单栏先吸顶，再弹出下拉菜单，缺少功能

**Comment by awmleer** [comment]
可以再具体描述一下么？现在这说的有点模糊……

**Comment by denglai** [comment]
默认情况是点击菜单，弹出下拉菜单列表，现在有个场景，点击菜单默认菜单栏先吸顶然后再弹出下拉菜单列表

**Comment by awmleer** [comment]
那你可以这样哈：
在 `onChange` 事件里，先让菜单滚动到顶部，然后再触发 `setState` 更新 `activeKey`

**Comment by denglai** [comment]
![image](https://user-images.githubusercontent.com/20442608/146878942-16f02e53-6e53-4d55-9888-aefe2d666a18.png)
默认是直接触发popup，外层onChange不可以

**Comment by awmleer** [comment]
@denglai 你是用的受控模式么？在这里给一个复现 demo 吧：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by denglai** [comment]
用的是受控模式,稍后我模拟一下吧
