### ISSUE TITLE
NumberKeyboard 组件支持两个自定义按键

### ISSUE THREAD

**Issue by hellohejinyu** [ant-design/ant-design-mobile#4588]
### Version of antd-mobile

5.0.0-rc.7

### What is this feature about?

![image](https://user-images.githubusercontent.com/8766034/146906098-9b392530-6299-4951-ac34-4334534fa2fb.png)

`NumberKeyboard` 这个组件能否支持一下最多自定义两个按键呢，现在的组件没法同时支持输入负数+小数。

**Comment by awmleer** [comment]
的确，我们考虑一下

**Comment by miracles1919** [comment]
可以拓展下 `customKey`，`customKey?: string | [string, string]`
