### ISSUE TITLE
[TextareaItem]自动高度只在unblur时触发

### ISSUE THREAD

**Issue by zhaoyao91** [ant-design/ant-design-mobile#459]
按回车换行时或删除文本时没有触发，而只有点击其他区域，unblur时才触发。

**Comment by silentcloud** [comment]
![test](https://cloud.githubusercontent.com/assets/1698185/19846476/95abb0f2-9f7a-11e6-8985-7a14a7f037a4.gif)

请提供一下对应环境信息  @zhaoyao91

**Comment by zhaoyao91** [comment]
我发现了，我当时是不受控模式，就是我说的那样，用rc-form改受控模式就跟演示一样了。
但是这还是算bug吧。

**Comment by pingan1927** [comment]
可以考虑支持
