### ISSUE TITLE
希望能将所有使用List的组件的mode=”card“都能自定义

### ISSUE THREAD

**Issue by jinxiangqiang** [ant-design/ant-design-mobile#4593]
### Version of antd-mobile

5.0.0-RC.7

### What is this feature about?

如Collapse。
form的--prefix-width:6em;能支持自定义

**Comment by awmleer** [comment]
我个人还是更推荐自己写个 div 容器，里面放 Collapse，`overflow: hidden` 一下，也可以达到一样的效果
