### ISSUE TITLE
使用Picker组件的时候给columns传空数组，界面在滑动的时候会报错

### ISSUE THREAD

**Issue by JackEqualsSparrow** [ant-design/ant-design-mobile#4594]
![image](https://user-images.githubusercontent.com/84223804/147049054-74eefd57-8d3f-4f60-a6c1-d0bb6ce5ae15.png)
在模仿上述例子的时候，我把columns的值置为[[]]，此时打开界面的时候UI渲染正常，如下图；
![image](https://user-images.githubusercontent.com/84223804/147049174-a11bd306-9be2-49ba-af57-767c776c7085.png)
but！
当我用鼠标在滑动区域内拖动/滑动 的时候，就报错了，如下图；
![image](https://user-images.githubusercontent.com/84223804/147049283-93c0bca1-89b8-4ac5-a80d-f480d60a8859.png)

**Comment by awmleer** [comment]
Close via bb9757bb2.
