### ISSUE TITLE
ImageUploader组件bug

### ISSUE THREAD

**Issue by xjx530** [ant-design/ant-design-mobile#4597]
### Version of antd-mobile

v5.0.0-rc.7

### Operating system and its version

Android

### Browser and its version

支付宝网页

### What happened?

支付宝打开的网页中使用ImageUploader组件会出现如下问题
1、上传的按钮出现多个
![image](https://user-images.githubusercontent.com/22742008/147182781-5e82c5bd-59a5-475e-ab72-ca2b0d1fb069.png)

2、选择的图片上传会提示失败
![image](https://user-images.githubusercontent.com/22742008/147182804-4774a4be-d71d-4df4-b5ad-aaefea4771e5.png)

手机浏览器和微信未见此问题

**Comment by awmleer** [comment]
“上传的文件不能为空”这个不是 antd-mobile 的报错诶

**Comment by xjx530** [comment]
> “上传的文件不能为空”这个不是 antd-mobile 的报错诶

那可能是我们这边后端的报错，但是在支付宝里面图片上传不上去，其他的就可以

**Comment by awmleer** [comment]
上传因为是原生的能力，所以在不同的设备、操作系统、浏览器下可能都会有比较大的差异，这些也都是 antd-mobile 基本没办法控制的

这个 issue 我先关闭了哈
