### ISSUE TITLE
PullToRefresh 增加 disabled 属性

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#4601]
### Version of antd-mobile

5.0.0-rc.7

**Comment by lweijian** [comment]
What is this property used for? Disable pull-down or disable pull-down refresh?

**Comment by GOWxx** [comment]
> What is this property used for? Disable pull-down or disable pull-down refresh?

The property used for disable pull-down.
The meaning of this property is that pull-down refreshes are not allowed.

One case where this property is required:
When using the `PullToRefresh` component, if you swipe your finger over a video that is playing while you are pulling down to refresh, `refresh` will not be triggered.
This video is played by [xgplayer](https://github.com/bytedance/xgplayer).
It's not clear that native `<video>` will have this problem.
