### ISSUE TITLE
IndexBar 序列侧边栏显示不完整

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design-mobile#4606]
### Version of antd-mobile

v5.0.0-rc.7

### Operating system and its version

iOS, Android

### Browser and its version

Google Chrome 版本 96.0.4664.110（正式版本） (x86_64)

### Sandbox to reproduce

https://mobile.ant.design/zh/components/index-bar

### What happened?

侧边栏显示不全
![image](https://user-images.githubusercontent.com/12181423/147307451-38ad5e31-5481-45b3-b79f-3422da6e7a1c.png)

### Relevant log output

```shell
无
```

**Comment by hqwlkj** [comment]
该问题已经在此 [PR](https://github.com/ant-design/ant-design-mobile/pull/4605) 中修复。 #4605

**Comment by xiaoyao96** [comment]
不同组件的bug修复，建议用独立从master切分支提PR。

**Comment by hqwlkj** [comment]
> 不同组件的bug修复，建议分别从master单独切分支提交，分别提PR。

好的

**Comment by xiaoyao96** [comment]
你可以现在从master切个新分支，用于修复这个issues。在PR的内容里关联当前issues，如:
`close #4605`，
如果pr合并，这个issue将会自动close。可以参考下其他人的pr

**Comment by hqwlkj** [comment]
好的
