### ISSUE TITLE
受控Picker组件在打开状态下无法监听到外部value的变更

### ISSUE THREAD

**Issue by wwwxy80s** [ant-design/ant-design-mobile#4607]
### Version of antd-mobile

v5.0.0-rc.7

### Operating system and its version

iOS, Android

### Sandbox to reproduce

https://codesandbox.io/s/agitated-carson-z3ul2?file=/src/App.tsx

### What happened?

受控picker组件在打开状态下，外部value变更，picker组件没有设置innerValue值。

在排查picker另一个bug的时候写demo发现的，不清楚这种场景算不算bug。
看了应该下是[这行代码](https://github.com/ant-design/ant-design-mobile/blob/68bce0382e679505fd97fc4dbd568de2b5443239/src/components/picker/picker.tsx?_pjax=%23repo-content-pjax-container#L72)导致的

**Comment by awmleer** [comment]
这个是预期行为哈
