### ISSUE TITLE
tabs组件css变量 --fixed-active-line-width 不起作用

### ISSUE THREAD

**Issue by woshichenxu2016** [ant-design/ant-design-mobile#4612]
### Version of antd-mobile

5.0.0-rc7

### Operating system and its version

iOS, Android, Others

### What happened?

看了下tabs.css 的代码，发现文档中说的--title-font-size，--content-padding和变量都有使用，但是--fixed-active-line-width没有用到，辛苦把这个变量设置下

**Comment by awmleer** [comment]
`--fixed-active-line-width` 只有在 `activeLineMode` 为 `'fixed'` 时才有效，文档上我加一下标注，应该是之前漏写了

**Comment by awmleer** [comment]
fbb7ed32d

**Comment by woshichenxu2016** [comment]
> `--fixed-active-line-width` 只有在 `activeLineMode` 为 `'fixed'` 时才有效，文档上我加一下标注，应该是之前漏写了

tab bar被选tab下面的小横条能支持自定义样式吗？

**Comment by awmleer** [comment]
具体是想怎么自定义？颜色？粗细？长度？还是啥？

**Comment by woshichenxu2016** [comment]
> 具体是想怎么自定义？颜色？粗细？长度？还是啥？

长度 ，例如是每个tab文案宽度的80%。 还有 高度 和 小横条的border-radius

**Comment by awmleer** [comment]
> 每个tab文案宽度的80%

这个支持不了

> 高度 和 小横条的border-radius

这两个目前不支持，但是后面可以支持，加一些 CSS 变量就可以了

PR welcome~

**Comment by awmleer** [comment]
单独记了个 issue，可以订阅一下：#4616

**Comment by woshichenxu2016** [comment]
好的多谢， 为你们的响应速度点赞
