### ISSUE TITLE
toast弹窗有遮罩层的时候，在遮罩层底部设置一个onClick事件，会穿透遮罩层

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design-mobile#4615]
### Version of antd-mobile

antd-mobile 5.0.0-rc.7

### What happened?

![e8d3ca2359f11348176cf1c89cfa6d07f12c353d241b345208ad8a49a25cc7f4QzpcVXNlcnNcNTQzNDJcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDgzNTYyNDE2X3YyXEltYWdlRmlsZXNcMTY0MDMzNzQ2OTcxN183NzVDRUYyRi1BOUM1LTQ1NDQtODg2Ni0wQzUxMTU4REY0RDYucG5n](https://user-images.githubusercontent.com/17424034/147339987-4b8ae8ab-a4c0-4381-a374-48b6a24491ef.png)
如图，有遮罩的时候，还是穿透了遮罩，激活了底部onClick事件，打开了Picker

**Comment by awmleer** [comment]
给个复现 demo 吧：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by xiaoliu1990** [comment]
我的问题，没设置maskClickable: false这个属性，加上这个就不能穿透了

**Comment by awmleer** [comment]
OK那issue我关了～
