### ISSUE TITLE
DatePicker组件选中的日期可以自定义样式

### ISSUE THREAD

**Issue by houchaowei** [ant-design/ant-design-mobile#4617]
### Version of antd-mobile

v5.0.0-rc.6

### What is this feature about?

DatePicker组件选中的日期可以自定义样式，目前DatePicker组件选中的日期的样式不可更改为自定义的样式，可以加个属性去自定义样式

**Comment by yangdepp** [comment]
已经在这个[PR-4547](https://github.com/ant-design/ant-design-mobile/pull/4547)中解决了。
`f12`审查元素可以看到，选中项有 `data-selected="true"` 的属性，未选中项为`false`，根据这个可以自定义选中和未选中的css样式。

**Comment by awmleer** [comment]
> 已经在这个[PR-4547](https://github.com/ant-design/ant-design-mobile/pull/4547)中解决了。
> 
> `f12`审查元素可以看到，选中项有 `data-selected="true"` 的属性，未选中项为`false`，根据这个可以自定义选中和未选中的css样式。
> 
> 

嗯嗯是这样的，文档上现在还没注明，我最近补一下文档

**Comment by awmleer** [comment]
b27a02426

**Comment by 1352313349** [comment]
> > 已经在这个[PR-4547](https://github.com/ant-design/ant-design-mobile/pull/4547)中解决了。
> > `f12`审查元素可以看到，选中项有 `data-selected="true"` 的属性，未选中项为`false`，根据这个可以自定义选中和未选中的css样式。
> 
> 嗯嗯是这样的，文档上现在还没注明，我最近补一下文档

请问能不能加一个demo说明一下如何使用这个属性
