### ISSUE TITLE
form组件在xcode的Safari浏览器里面label属性和placeholder属性没有对齐？

### ISSUE THREAD

**Issue by Jairwin-L** [ant-design/ant-design-mobile#4621]
### Version of antd-mobile

^5.0.0-rc.8

### Operating system and its version

iOS

### Browser and its version

xcode 12.3 safari 13.1.2

### Sandbox to reproduce

https://github.com/Jairwin-L/ant-mobile-demo

### What happened?
左：浏览器网页，右：xcode Safari
![image](https://user-images.githubusercontent.com/32570960/147378042-e4245841-34c8-4110-8a3f-82b8d7fea1b8.png)

**Comment by awmleer** [comment]
右侧模拟器的 iOS 版本具体是多少？

**Comment by Jairwin-L** [comment]
> 右侧模拟器的 iOS 版本具体是多少？

14.3
![image](https://user-images.githubusercontent.com/32570960/147403367-ddc311c5-0fad-4d45-bf8a-5f3f614d9420.png)

**Comment by awmleer** [comment]
复现出来了，我看下

**Comment by awmleer** [comment]
似乎和模拟器没有关系，我最后用官网的 demo，在桌面端 Safari 也能复现

**Comment by awmleer** [comment]
Fixed via e087bdd3f
