### ISSUE TITLE
setDefaultConfig 设置中英文切换无效

### ISSUE THREAD

**Issue by thbgh** [ant-design/ant-design-mobile#4625]
### Version of antd-mobile

v5.0.0-rc.7

### Operating system and its version

Others

### Browser and its version

chrome 96

### Sandbox to reproduce

https://mobile.ant.design/zh/components/config-provider

### What happened?

切换组件中英文无效，文档无示例，希望能给一个解决方案，谢谢！
[
![image](https://user-images.githubusercontent.com/9399517/147431720-b581373f-426e-4fbf-b20f-f9bc293be3b6.png)
](url)
[
![image](https://user-images.githubusercontent.com/9399517/147431828-9163f986-bd59-4a93-afeb-b98588a7c3b3.png)
](url)

### Relevant log output

```shell
https://mobile.ant.design/zh/components/config-provider
```

**Comment by awmleer** [comment]
你是说官网文档上的 demo 有问题么？我试了一下是正常的
