### ISSUE TITLE
希望UMD打包的时候多一种选择，把js和css分开打包

### ISSUE THREAD

**Issue by zjfjiayou** [ant-design/ant-design-mobile#4626]
### Description

如题

**Comment by awmleer** [comment]
@zjfjiayou 可以说一下原因么？

**Comment by zjfjiayou** [comment]
用webpack抽离了样式文件后，:root 下定义的css变量会被antd-mobile中的覆盖，看了一下原因是因为webpack抽离的css以link标签的方式先加载，antd-mobile的样式以style标签后加载。所以我想能有单独的样式文件，我可以自己控制加载顺序

**Comment by zjfjiayou** [comment]
用webpack抽离了样式文件后，:root 下定义的css变量会被antd-mobile中的覆盖，看了一下原因是因为webpack抽离的css以link标签的方式先加载，antd-mobile的样式以style标签后加载。所以我想能有单独的样式文件，我可以自己控制加载顺序

**Comment by awmleer** [comment]
可以看下这篇文档：https://mobile.ant.design/zh/guide/css-variables
写两次 `:root` 可以提高你的 CSS 的优先级，让它可以正确的覆盖 antd-mobile 默认的变量值：
![image](https://user-images.githubusercontent.com/16526078/147521281-6f2603b3-5776-4ee5-b42f-c63317773a84.png)

**Comment by zjfjiayou** [comment]
好的，谢谢大哥
