### ISSUE TITLE
loading状态

### ISSUE THREAD

**Issue by cheng-xiaofeng** [ant-design/ant-design-mobile#4628]
### What is this feature about?

希望可以添加转圈的loading状态
![image](https://user-images.githubusercontent.com/33592850/147445155-8014bf65-0380-4b11-9bec-6598236b94b6.png)
![未标题-2](https://user-images.githubusercontent.com/33592850/147446659-c4d70754-be8b-441d-9841-15e7e22ad07e.jpg)

**Comment by awmleer** [comment]
和 #4509 重复了，这个 issue 我关闭了
