### ISSUE TITLE
build时tree shaking失败

### ISSUE THREAD

**Issue by piscessss** [ant-design/ant-design-mobile#4634]
### Version of antd-mobile

5.0.0-rc.9

### What happened?

使用next 12.x去引入antd-mobile的es入口的文件，如果不用bable插件的话，tree shaking会失败。
是next使用了swc的原因还是库本身的原因导致的?
[my-app.zip](https://github.com/ant-design/ant-design-mobile/files/7784065/my-app.zip)

**Comment by awmleer** [comment]
hi 你现在还存在这个问题么？因为看起来提 issue 时的 antd-mobile 版本还是 5.0.0 rc，或许可以升级一下到最新版试试

后来有很多朋友在 next.js 中使用了 antd-mobile，貌似没有其他人遇到这个问题，所以推测大概率升级到最新版之后就可以解决这个问题了，因为我实在精力有限，再加上对 next.js 不甚了解，所以没有办法亲自去验证一下了

这个 issue 我先关闭掉，如果后续还有更新的话可以随时再 reopen

**Comment by piscessss** [comment]
> 

好的，先关闭吧，要是升级后还有问题的话我再在这儿反馈
