### ISSUE TITLE
【建议】希望antd-mobile-icons能和@ant-design/icons增加自定义 font 图标功能

### ISSUE THREAD

**Issue by Jairwin-L** [ant-design/ant-design-mobile#4635]
### What is this feature about?

https://ant.design/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-font-%E5%9B%BE%E6%A0%87

**Comment by awmleer** [comment]
自定义图标可以自己使用诸如 iconfont、直接引入 svg 等等的方案，和 antd-mobile 本身没有关系

**Comment by awmleer** [comment]
目前还不会增加 Icon 组件支持传入一个自定义的图标素材，更推荐使用三方库哈

**Comment by Jairwin-L** [comment]
> 目前还不会增加 Icon 组件支持传入一个自定义的图标素材，更推荐使用三方库哈

好的。
