### ISSUE TITLE
FloatingBubble 浮动气泡 希望支持全屏位置范围内两个方向同时拖动功能

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#4636]
### Version of antd-mobile

5.0.0-rc.9

### What is this feature about?

FloatingBubble 浮动气泡 目前只支持一个方向拖动功能（水平或垂直），希望支持全屏位置范围内两个方向同时拖动功能！

**Comment by awmleer** [comment]
这个在考虑中了，后面 FloatingBubble 能力会增强一大波，再等等哈

**Comment by liangskyli** [comment]
亲，这个功能提升会在正式版前实现吗？

**Comment by awmleer** [comment]
不会……估计最快也要下月份了

**Comment by awmleer** [comment]
已支持 81d7fa7f
