### ISSUE TITLE
Toast 轻提示 默认最大宽度70%无效

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#4637]
### Version of antd-mobile

5.0.0-rc.9

### Browser and its version

chrome 95.0

### Sandbox to reproduce

https://codesandbox.io/s/mystifying-hypatia-2sv4f?file=/src/App.tsx

### What happened?

Toast 轻提示 默认最大宽度70%无效，文档例子里可复现：https://mobile.ant.design/zh/components/toast
样式max-width: 70%，实际不是70%宽度：
.adm-toast-mask .adm-toast-wrap {
max-width: 70%;
}
<img width="598" alt="QQ20211228-204245@2x" src="https://user-images.githubusercontent.com/31531283/147568127-fe9cc317-6d7a-451e-aa3c-8fd626932d7a.png">

**Comment by GOWxx** [comment]
这个链接
https://codesandbox.io/s/mystifying-hypatia-2sv4f?file=/src/App.tsx
没保存你的变更？

**Comment by xiaoyao96** [comment]
确实无效，目测最大宽度是50%，绝对定位的元素需提前预设足够的width和height。我来改改看

**Comment by awmleer** [comment]
Fixed via 11d5f89c3

**Comment by sphenginx** [comment]
> Fixed via [11d5f89](https://github.com/ant-design/ant-design-mobile/commit/11d5f89c3a8ee9c182a1e684232d05555abab3a9)

请教个问题，fit-content属性我看适用的浏览器是 chrome 和 FireFox， Safari 适用么？
