### ISSUE TITLE
RN里添加navbar组件不识别

### ISSUE THREAD

**Issue by xubuhang** [ant-design/ant-design-mobile#464]
#### 本地环境

- antd-mobile 版本："^0.9.5",
- 操作系统及其版本：ReactNative
- 浏览器及其版本：

#### 你期待的结果是：

像官网一样正常显示 

#### 实际上的结果：

报红色错误

#### 可重现的在线演示

<img width="765" alt="qq20161031-0 2x" src="https://cloud.githubusercontent.com/assets/4189632/19845323/c7c723aa-9f70-11e6-9010-bf854eb39787.png">

**Comment by silentcloud** [comment]
Navbar 只提供了 web 版本的，因为 RN 有自己的 navigator，有自己的行为，无需提供 web 版那个 NavBar

**Comment by xubuhang** [comment]
那我问一句：lib下面这么多组件哪个RN 能用哪个不能用我不知道，有没有办法一眼就看得出来呀？

**Comment by silentcloud** [comment]
@xuhuhang  lib 下面组件有 index.js  的都是 react-native 支持的，web 的是 index.web.js

**Comment by xubuhang** [comment]
@silentcloud 谢谢
