### ISSUE TITLE
InfiniteScroll 中loadMore函数只能支持Promise有设计缺陷

### ISSUE THREAD

**Issue by Teal-H** [ant-design/ant-design-mobile#4641]
### Version of antd-mobile

5.0.0-rc.9

### What happened?

loadMore这个函数只能支持Promise，但是在react，hooks用法中存在缺陷，比如我在loadMore时，仅仅需要通过setParams，改变查询参数params。参数被作为依赖再求情接口，这种状态无法封装成Promise函数，导致无限加载
`
useEffect(() => {
        getList(params)
    }, [params])
`
`const loadMore = async () => {
         setParams(val => ({...val, page: val.page + 1}))
    }`

**Comment by awmleer** [comment]
那你觉得该怎么设计 InfiniteScroll 的 API 才可以满足你的这个场景呢？

**Comment by xiaoyao96** [comment]
我个人建议，这种场景不使用监听变化去请求，可控性较差，如你所说容易引起无限加载。
顺手写了个条件搜索+分页的demo:
https://codesandbox.io/s/pedantic-hellman-pr7ui?file=/src/App.tsx
