### ISSUE TITLE
v5 打包的时候可以带上 less 源文件吗？让 Next.js 也可以使用。Can v5 be package with less source files? Make Next.js available as well.

### ISSUE THREAD

**Issue by SolidZORO** [ant-design/ant-design-mobile#4643]
### Version of antd-mobile

5.0.0-rc.12

### What is this feature about?

在我维护的一个让 next.js 支持 antd 的项目 `next-plugin-antd-less`  中有人提到了可不可以支持 antd-mobile https://github.com/SolidZORO/next-plugin-antd-less/issues/101

我研究了一下发现是 Next.js 不支持导入 css，然后 antd-mobole 包里面又没有 less 源文件，所以报了以下错误：

```
Failed to compile
./node_modules/antd-mobile/es/components/button/button.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/antd-mobile/es/components/button/index.js
This error occurred during the build process and can only be dismissed by fixing the error.
```

但是 antd 的确是可以的，看了下 antd 的包，是有带 less 的：

```
antd        --> `node_modules/antd/es/button/style/index.less`
antd-mobile --> `node_modules/antd-mobile/es/components/button/button.css`
```

然后就是 babel-plugin-import 这个插件，antd 用起来比较方便简单配置一下就可以了，就像这样：

```
[
  'import',
  { 
    libraryName: 'antd', style: true 
  },
  'antd'
]
```

antd-mobile 这边如果想要用 less，其实得这样配置一下（当然目前还没有 less）：

```
 [
  'import',
  {
    libraryName: 'antd-mobile',
    libraryDirectory: 'es/components',
    style: (filePath) => {
      const fileName = `${filePath}`.split('/').pop();

      return `${filePath}/${fileName}.less`;
    },
  },
  'antd-mobile',
],
```

__所以，我想请求一下，是可否打包样式的时候使用类似 antd 的风格？或者放一份 less 在组件中？__

**Comment by awmleer** [comment]
回复一下你提到的两个疑问哈：

1. antd-mobile 未来**确定是不会打包 less 到 npm 包中的**，后面 antd-mobile 甚至可能不再使用 less，而尝试别的 CSS 方案
2. 关于 babel-plugin-import 相关的用法问题，可以查阅官网文档上的[这篇文档](https://mobile.ant.design/zh/guide/import-on-demand)，上面不仅有如何配合 babel-plugin-import 使用 antd-mobile 的指引，还有按需加载的完整介绍，整体而言，我们并不推荐使用 babel-plugin-import 做手动的按需加载

**Comment by SolidZORO** [comment]
好明白了，谢谢回复。
