### ISSUE TITLE
CascaderView支持前面放单选框直接截断选择

### ISSUE THREAD

**Issue by jinxiangqiang** [ant-design/ant-design-mobile#4644]
### Version of antd-mobile

5.0.0-RC.12

### What is this feature about?

如省市区级联，我在选择长沙市的时候点击前面的单选按钮即可只选择湖南省长沙市，不一定要全部选择完

**Comment by awmleer** [comment]
没太理解你的意思……签名的单选按钮是什么？你是说 Checkbox 组件么？你是希望把这个“单选框”放到哪里？
