### ISSUE TITLE
Picker支持disabled属性，之前有相关issue，现在是否已经支持？

### ISSUE THREAD

**Issue by chenent** [ant-design/ant-design-mobile#4645]
### What is this feature about?

Picker支持disabled属性，之前有想过issue，现在是否已经支持？

之前issue：
https://github.com/ant-design/ant-design-mobile/issues/119

**Comment by awmleer** [comment]
之前的 issue 应该是 v1 或者 v2 版本的，v5 版本目前没有计划给 Picjer 增加 disabled 属性，不过你可以通过 filter 属性过滤掉某些选项
