### ISSUE TITLE
引用5.0.0版本，使用组件报错：regeneratorruntime is not undefined

### ISSUE THREAD

**Issue by zhouengineer** [ant-design/ant-design-mobile#4646]
### Version of antd-mobile

5.0.0-rc.12

### Operating system and its version

Android

### Browser and its version

都有

### Sandbox to reproduce

暂时没有

### What happened?

在下载antd-mobile @5.0.0-rc.12，引用Modal组件了，报错：regeneratorruntime is not undefined，我的项目值vite框架，为啥出现这样问题呢，不能兼容babel吗，现在如何处理呢

### Relevant log output

```shell
<Modal
        visible={false}
        content={<div>{followInfo.msg}</div>}
        closeOnAction
        onClose={() => {
          setVisible(false);
          closeWindow();
        }}
        actions={[
          {
            key: 'confirm',
            text: '我知道了',
          },
        ]}
      />
```

**Comment by xiaoyao96** [comment]
原因是使用了async/await 语法，需配置babel。

vite支持配置babel:
https://github.com/vitejs/vite/tree/main/packages/plugin-react#babel-configuration

配置async/await支持：
https://github.com/babel/babel/issues/8829#issuecomment-456524916

**Comment by zhouengineer** [comment]
只在调用modal组件中的action事件而产生的这样的报错，在调用其他 的组件同时使用async/await,并没有报这样的错，这是为何呢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月31日(星期五) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-mobile] 引用5.0.0版本，使用组件报错：regeneratorruntime is not undefined (Issue #4646)





 
原因是使用了async/await 语法，需配置babel。
 
vite支持配置babel:
 https://github.com/vitejs/vite/tree/main/packages/plugin-react#babel-configuration
 
配置async/await支持：
 babel/babel#8829 (comment)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moonlitusun** [comment]
+1, Switch component

**Comment by awmleer** [comment]
的确可以说是组件库的打包问题，我优化了一下，下个版本发布之后应该就不存在这个问题了 19b7ca5e5

**Comment by zhongning7924** [comment]
> 的确可以说是组件库的打包问题，我优化了一下，下个版本发布之后应该就不存在这个问题了 [19b7ca5](https://github.com/ant-design/ant-design-mobile/commit/19b7ca5e5f55dcefa7f9e2df5087958dec2bbb9e)
`{
  "presets": ["@nrwl/react/babel"],
  "plugins": [
    ["@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ]
}
`
什么时候发新包，在nx框架中写入的babel也不生效，

**Comment by awmleer** [comment]
@zhongning7924 预计今天发
