### ISSUE TITLE
Modal footer排列

### ISSUE THREAD

**Issue by Xmtd** [ant-design/ant-design-mobile#4647]
### Version of antd-mobile
V5
_No response_

### What is this feature about?

现在Modal footer的button排列是vertical模式，希望支持horizontal模式，或footer可自定义

**Comment by xiaoyao96** [comment]
v2版本 目前已不再增加新功能，可考虑使用v5版本。

**Comment by awmleer** [comment]
似乎说的是 v5 版本的 Modal 组件？ @Xmtd 你需要填一下你使用的 antd-mobile 的版本号

**Comment by Xmtd** [comment]
> 似乎说的是 v5 版本的 Modal 组件？ @Xmtd 你需要填一下你使用的 antd-mobile 的版本号

V5版本的Modal

**Comment by awmleer** [comment]
@Xmtd 暂时不会支持哈，如果有这种特殊需求的话可以考虑自己在内容区中实现一下，antd-mobile 的设计规范目前是不支持横向并排的。不过 Dialog 是支持的，可以考虑用 Dialog。
