### ISSUE TITLE
[Ellipsis] 页面有大量 Ellipsis 时，渲染卡顿

### ISSUE THREAD

**Issue by GOWxx** [ant-design/ant-design-mobile#4649]
### Version of antd-mobile

5.0.0-rc.12

### Operating system and its version

Others

### Browser and its version

win10 chrome V96 模拟移动端设备

### Sandbox to reproduce

https://codesandbox.io/s/headless-bird-h3hx7?file=/src/App.tsx

### What happened?

在这个 demo 中，随机生成了400条文字数据
切换到 Ellipsis 或者 List & Ellipsis 时，都会卡顿，卡顿时间接近，应该只是 Ellipsis 的问题

![image](https://user-images.githubusercontent.com/12870715/147848968-61654d43-dd02-4ca6-bfd6-0ede69f3956e.png)

**Comment by awmleer** [comment]
这个确实是预期行为，目前的 Ellipsis 组件是通过 js 进行计算溢出的，不可避免的会带来一些性能开销，这种大量数据的场景，可以考虑用 CSS 来实现 ellipsis，或者是增加虚拟滚动
