### ISSUE TITLE
atool-build打包web项目缺少index.html(demo 项目示例 #56)

### ISSUE THREAD

**Issue by ctq123** [ant-design/ant-design-mobile#465]
#### 本地环境

- antd-mobile 版本：antd-mobile@0.8.7
- 操作系统及其版本： win7 64bit, atool-build@0.8.1
- 浏览器及其版本：

#### 你做了什么？

按照demo 项目示例 #56下载的实例，运行npm run build打包缺少index.html文件，是不是使用antd-mobile打包web项目时需要另外配置什么才会有这个index.html文件

#### 你期待的结果是：
使用antd-mobile框架打包web项目有index.html首页（使用hash打包能自动替换hash码，即这个index.html是打包生成的）

**Comment by silentcloud** [comment]
默认不会提供的，如果需要，请自行扩展 webpack.config.js
