### ISSUE TITLE
2.x版本 modal组件transparent props的功能异常

### ISSUE THREAD

**Issue by yuchiXiong** [ant-design/ant-design-mobile#4652]
### Version of antd-mobile

2.3.1

### Operating system and its version

iOS, Android, Others

### Sandbox to reproduce

https://codesandbox.io/s/ce-shi-antd-mobile-modalzu-jian-trans-fy69z?file=/src/index.js

### What happened?

根据官方文档中对 Modal 组件 props 的描述：

> transparent 是否背景透明

在codesandbox演示中很容易发现，该 prop 并不能达到降背景 mask 层置为透明的目的，同时还出现了预期以外的更改 Modal 显隐动效的结果。

查阅[源码此处](https://github.com/ant-design/ant-design-mobile/blob/2.3.x/components/modal/Modal.tsx#L131)，代码逻辑并不符合文档对于该 prop 的描述，请问此处是功能缺陷还是文档描述错误呢？

另外该版本所依赖的 rmc-dialog 组件中支持 mask prop ，实际使用过程中该属性是有效且实用的，是否会考虑将其加入到文档 prop 属性列表中呢？

**Comment by awmleer** [comment]
v2 已停止维护了，这些问题我们没有精力去修复了，可以考虑升级一下哈：https://mobile.ant.design/zh/guide/migration
