### ISSUE TITLE
ImageUploader在预览上传的图片时，切换路由导致预览的mask未关闭

### ISSUE THREAD

**Issue by tangyefei** [ant-design/ant-design-mobile#4654]
### Version of antd-mobile

5.0.0-rc.3

### Operating system and its version

iOS

### What happened?

antd-mobile 结合 react-router 的场景下：

1. 使用 ImageUploader 上传一张图片，点击图片，弹出预览的mask (图1）
2. 使用浏览器回退功能，切换到另一个，但是body下的mask没被销毁（图2）

![image](https://user-images.githubusercontent.com/3982987/148023303-8ab0128e-5f2d-428a-8c9d-25dd75f9aec5.png)

![image](https://user-images.githubusercontent.com/3982987/148023341-e3c556d9-b5c7-4bf0-b2c2-8bf0105f2b73.png)

**Comment by tangyefei** [comment]
目前仅能通过手动删除dom解决

```
  useEffect(() => {
    return () => {
      // 注：antd-mobile uploader 自带的 preview 离开时，不检测 mask 关闭，需要手动处理
      const previewMask = document.querySelector('.adm-mask');
      if (previewMask && previewMask.parentElement) {
        previewMask.parentElement.remove();
      }
    };
  }, []);
```

**Comment by xiaoyao96** [comment]
可以尝试使用 `ImageViewer.Multi.clear()`：
```js
useEffect(() => {
    return () => {
      ImageViewer.Multi.clear()
    };
  }, []);
```

**Comment by awmleer** [comment]
Fixed via e6745e5e6
