### ISSUE TITLE
Image 组件 在 next.js 使用的问题

### ISSUE THREAD

**Issue by yanzhenqing66** [ant-design/ant-design-mobile#4656]
### Description

在nextjs 中使用 antd mobile v5 的 Image 组件和 next/image 功能一样吗?

**Comment by awmleer** [comment]
不一样的哈

next/image 的相关介绍：https://nextjs.org/docs/basic-features/image-optimization

**Comment by HellCatVN** [comment]
@yanzhenqing66 Cause ` Image`  is same with `next/image` 
So try to `import { Image as AntImage } from "antd-mobile"`
