### ISSUE TITLE
希望popup组件提供onClose方法

### ISSUE THREAD

**Issue by zjfjiayou** [ant-design/ant-design-mobile#4658]
### Version of antd-mobile

v5.0.0-rc.12

### What is this feature about?

希望popup组件提供onClose方法

**Comment by awmleer** [comment]
具体是啥场景需要 `onClose`？可以具体描述一下么？

**Comment by zjfjiayou** [comment]
在低版本的浏览器，例如钉钉的h5里面多个popup会导致最后一个popup内容渲染不全。所以这边做了一个处理，多个popup只会渲染最上层popup，其他的用css隐藏内容，当最上层的点击关闭的时候，需要用onClose触发一下还原
