### ISSUE TITLE
vite+antd-mobile v5 ，打包之后，组件没有默认主题色

### ISSUE THREAD

**Issue by JuSanZhi** [ant-design/ant-design-mobile#4659]
### Version of antd-mobile

^5.0.0-rc.12

### What happened?

配置了按需加载，
![image](https://user-images.githubusercontent.com/24559368/148328016-18330009-2c5a-49d6-8246-5c514e2785dd.png)
本地项目组件使用正常，但是打包之后没有主题色了，我看样式是加载了，就是没有颜色
![image](https://user-images.githubusercontent.com/24559368/148328299-f24668da-959a-4565-b393-c65ced867907.png)
![image](https://user-images.githubusercontent.com/24559368/148328338-6e79b4ad-b197-4ca9-bceb-0030a0ee2af3.png)

### Relevant log output

```shell
![image](https://user-images.githubusercontent.com/24559368/148328299-f24668da-959a-4565-b393-c65ced867907.png)
![image](https://user-images.githubusercontent.com/24559368/148328338-6e79b4ad-b197-4ca9-bceb-0030a0ee2af3.png)

```

**Comment by awmleer** [comment]
![image](https://user-images.githubusercontent.com/16526078/148482417-dd6f1fab-aa0a-4be0-ae54-712779c8bb0d.png)

这个你引入了么？
