### ISSUE TITLE
Badge 组件颜色改成css变量

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#4663]
### Version of antd-mobile

latest

### What is this feature about?

https://github.com/ant-design/ant-design-mobile/blob/3f58f67de6e7e81c56493b296ac0673fc37355c4/src/components/badge/badge.tsx#L16

希望能把 Badge 组件默认颜色改成css变量，而不是现在这种作用在style上的，优先级太高了

**Comment by awmleer** [comment]
可以给 Badge 增加一个 `--color` 的 CSS 变量，以及对应的 `--adm-badge-color` 的全局 CSS 变量

当然，为了保持 API 的兼容，color 属性还是要保留的，不过 color 属性底层的实现也是帮用户设置了 `--color` CSS 变量

**Comment by IronKinoko** [comment]
ok,我晚点处理
