### ISSUE TITLE
希望popup可以加个滑动关闭效果

### ISSUE THREAD

**Issue by whao0329** [ant-design/ant-design-mobile#4666]

**Comment by awmleer** [comment]
滑动关闭？你是说通过手势关闭 Popup 么

**Comment by zjfjiayou** [comment]
我也想要这个功能，目前是配合react router做的，要是popup支持就太好了

**Comment by awmleer** [comment]
@zjfjiayou 可以具体描述一下你想要的效果是啥么？

**Comment by zjfjiayou** [comment]
@awmleer 好的

**Comment by awmleer** [comment]
> 通过手势滑动屏幕默认是返回到首页

@zjfjiayou 你是说 iOS 下从屏幕的左侧边缘向右滑动返回上一页的这个手势么？

这个是系统原生的能力，我们没有办法干涉的

**Comment by zjfjiayou** [comment]
![5424805032_50715478254_Screenshot_2022_0115_170315](https://user-images.githubusercontent.com/7593789/149616276-b8963e0c-2812-4f37-9cb7-3c07b533a485.gif)
@awmleer 就是这样的效果

**Comment by awmleer** [comment]
这个得你自己配合路由使用了，才能实现路由返回的时候触发弹层关闭，不是 Popup 本身的功能
