### ISSUE TITLE
NoticeBar 通告栏希望能支持纵向滚动

### ISSUE THREAD

**Issue by atom-shanghai** [ant-design/ant-design-mobile#4668]
### What is this feature about?

NoticeBar 通告栏希望能支持纵向滚动

**Comment by awmleer** [comment]
这个不会支持的哈

但是未来可能会做一个这样的组件，它是上下滚动的：

![1641298354566-4371d0fb-d224-4c50-8657-f781d8e9c207](https://user-images.githubusercontent.com/16526078/148912280-16bef913-c6b2-484e-b30c-bc42a22ba8b9.png)
