### ISSUE TITLE
modal 和dialog弹窗打开都会出现闪动现象

### ISSUE THREAD

**Issue by wansers** [ant-design/ant-design-mobile#4669]
### Version of antd-mobile

v5.0.0-rc.16

### Browser and its version

h5

### Sandbox to reproduce

https://codesandbox.io/s/bold-mirzakhani-dnkmx?file=/src/App.tsx

### What happened?

modal 和dialog弹窗打开都会出现闪动现象

**Comment by awmleer** [comment]
抖动是指……？我这里试了一下是正常的

要不你贴个录屏视频？

**Comment by wansers** [comment]
https://user-images.githubusercontent.com/23227251/148930332-e3835de4-fde7-4b77-a4d9-4b9c530fee1c.mov

手机端看起来没问题（不知道是不明显还是没有），PC端会抖动1px左右，在分辨率低的屏幕会更明显一点

**Comment by awmleer** [comment]
噢 PC 端的确是有这个问题，移动端是不会有的，先忽略就好了哈，毕竟这个库主要是面向移动端设备的

**Comment by conkyliu** [comment]
https://user-images.githubusercontent.com/26617741/157426283-f89ec079-9a53-4542-8ed5-f73ebc2e87ee.mp4

我这里的modal闪动的好明显

**Comment by awmleer** [comment]
@conkyliu 你这个问题应该和这个 issue 所描述的不是同一个问题，你这个抖动的原因可能是浏览器的 video 对缩放效果的支持存在一些问题，可以考虑别用 Modal 了，改成用 Mask 组件

**Comment by conkyliu** [comment]
> @conkyliu 你这个问题应该和这个 issue 所描述的不是同一个问题，你这个抖动的原因可能是浏览器的 video 对缩放效果的支持存在一些问题，可以考虑别用 Modal 了，改成用 Mask 组件

是Mask组件，目前Modal。

**Comment by awmleer** [comment]
@conkyliu mask 组件的话不应该啊，要不你再单独提个 issue 吧，就不在这个 issue 下讨论了，顺便提供一下复现 demo 吧
