### ISSUE TITLE
发现个安卓和ios的兼容性问题，关于Flex布局

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design-mobile#467]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

#### 你做了什么？
![image](https://cloud.githubusercontent.com/assets/18717051/19849303/64dc38f8-9f8d-11e6-91ad-32786f973fd1.png)
这是我引入列表 用的FlEX布局 ，浏览器显示效果正常 

#### 你期待的结果是：
这个是ios 效果  显示正常

#### 实际上的结果：
这个是安卓机型显示的效果  字体的上方会被削去一点点 ，试了好几个安卓机型都是同样效果
![image](https://cloud.githubusercontent.com/assets/18717051/19849350/bfd8b5ec-9f8d-11e6-83d9-ec49d383a693.png)

#### 可重现的在线演示

 不知道这个是什么原因造成的，感觉应该是兼容问题，不知道有没有解决方式，还是自己重新写个布局

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/19849466/7265b700-9f8e-11e6-98bf-cc7b843d7203.png)


IOS机型的图  上面没显示出来

**Comment by pingan1927** [comment]
麻烦把具体的antd-mobile版本号说下哈

**Comment by SynChron1zed** [comment]
@pingan1927    "antd-mobile": "^0.9.3",

**Comment by guangming21** [comment]
@SynChron1zed 大哥，你的tabbar怎么写的

**Comment by SynChron1zed** [comment]
@guangming21  手写的

**Comment by warmhug** [comment]
@SynChron1zed 还有问题吗？也有可能是多个组件互相影响出问题

**Comment by warmhug** [comment]
没响应，先关掉

**Comment by weishijun14** [comment]
@SynChron1zed 大哥长沙哪家公司的啊

**Comment by SynChron1zed** [comment]
@weishijun14  怎么了

**Comment by weishijun14** [comment]
@SynChron1zed 想共同学习下~

**Comment by SynChron1zed** [comment]
@weishijun14 加我qq把278844023
