### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by moonlitusun** [ant-design/ant-design-mobile#4675]
### Version of antd-mobile

5.0.0

### What happened?

![image](https://user-images.githubusercontent.com/22940470/149064971-29da371c-a11f-4118-913f-3407e3194b69.png)

### Relevant log output

```shell
请问下为啥你们的库打包出来有 regeneratorRuntime 。文档上没有说需要适配这个吧
```

**Comment by awmleer** [comment]
的确可以说是组件库的打包问题，我优化了一下，下个版本发布之后应该就不存在这个问题了 19b7ca5e5
