### ISSUE TITLE
省略组件内容出现无法更新的问题

### ISSUE THREAD

**Issue by jinxiangqiang** [ant-design/ant-design-mobile#4676]
### Version of antd-mobile

5.0.0-RC.17

### Operating system and its version

Others

### Sandbox to reproduce

https://codesandbox.io/embed/elated-wood-se93m?fontsize=14&hidenavigation=1&theme=dark

### What happened?

链接已重现，内容长度变化一次超出后就无法正常显示内容

**Comment by awmleer** [comment]
的确可以复现……应该是组件库的 bug

**Comment by awmleer** [comment]
Fixed via 3d1cf9c9c
