### ISSUE TITLE
DotLoading 和SpinLoading 无法引入

### ISSUE THREAD

**Issue by ch634421335** [ant-design/ant-design-mobile#4678]
### Version of antd-mobile

5.0.0-rc.17

### Operating system and its version

Others

### Browser and its version

chrome  97.0.4692.71

### What happened?

引入DotLoading和SpinLoading 报错

### Relevant log output

```shell
Uncaught SyntaxError: The requested module '/node_modules/.vite/antd-mobile.js?v=82bc1f11' does not provide an export named 'DotLoading'
```

**Comment by zzzgydi** [comment]
可以试试删掉`node_modules/.vite`这个文件夹 再dev

**Comment by awmleer** [comment]
或者提供一个完整的可以复现的工程项目吧
