### ISSUE TITLE
popup 组件中嵌套按钮点击跳转(单页跳转)后，pop up组件的display还是unset不是none

### ISSUE THREAD

**Issue by woshichenxu2016** [ant-design/ant-design-mobile#4679]
### Version of antd-mobile

5.0.0-rc9

### Operating system and its version

iOS, Android, Others

### What happened?

popup 组件中嵌套按钮点击跳转(单页跳转)后，pop up组件的display还是unset不是none，导致跳到了新页面后页面内容被popup的遮罩覆盖无法点击

**Comment by awmleer** [comment]
提供一个复现 demo 吧，按理说不应该会出现这个问题的，有点怀疑是你的用法问题

**Comment by woshichenxu2016** [comment]
<Popup
              visible={visible}
            >
              <div className="sheet-list" onClick={(e) => {
                e.stopPropagation()
                setVisible(false)
                props.history.push(`/report?sourceType=q`)
              }}>点击</div>
            </Popup>

**Comment by awmleer** [comment]
@woshichenxu2016 在这里提供一个 codesandbox 的 demo……

https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by woshichenxu2016** [comment]
我用react-router-dom 是好的 ，用react-router-cache-route 的CacheSwitch不行，而且在sandbox中不能复现，在我本地可以复现。 查了下popup组件源码大概定位到， withStopPropagation里面的active的值和props.visible不一致的原因导致。使用react-router-cache-route 的时候，在popup浮层中的按钮点击事件同步执行 setVisible(false)后使用history.push 跳转到另一个页面时因为react-router-cache-route 会将shouldComponentUpdate设置为false，所以执行完useSpring的onRest回调setActive(props.visible)后并不会执行render方法，导致withStopPropagation返回的node 对象 style {display: active ? 'unset' : 'none'} active一直是true。不知道将 display: active ? 'unset' : 'none' 中的active直接换成props.visible是否可行？

**Comment by awmleer** [comment]
> 不知道将 display: active ? 'unset' : 'none' 中的active直接换成props.visible是否可行？

如果改成这样的话会导致关闭的时候动画效果缺失，所以是不可以的

**Comment by woshichenxu2016** [comment]
方便加个微吗？

**Comment by woshichenxu2016** [comment]
我的微信号hibernate_tiger

**Comment by woshichenxu2016** [comment]
方便加个微吗？我的微信号hibernate_tiger, 关于popup的问题想和您电话聊下

**Comment by awmleer** [comment]
<img src="https://gw.alipayobjects.com/mdn/rms_25513e/afts/img/A*fo-tQ5wRk5QAAAAAAAAAAAAAARQnAQ" alt="ding-group" width="360" />

@woshichenxu2016 可以加上面这个钉群哈
