### ISSUE TITLE
master stepper 依赖老版 iconfont 导致 icon 出不来

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#468]
![image](https://cloud.githubusercontent.com/assets/1698185/19850923/318111aa-9f96-11e6-854f-5dcbae4481bb.png)

![image](https://cloud.githubusercontent.com/assets/1698185/19851011/af3ee20c-9f96-11e6-8629-38a23fd90db3.png)

**Comment by hldzlk** [comment]
同样的问题

**Comment by silentcloud** [comment]
暂时使用“ + - “ 字符修复， fixed in c8ed9008e4ffa41039c43e30e140af222ca8a17a

**Comment by freestyle21** [comment]
这个改动在`1.0.0-beta2`上，但是npm install安装后的是`0.9.14`版本...
