### ISSUE TITLE
antd-mobile由2.3.4升级最新的版本显示无法解析css文件

### ISSUE THREAD

**Issue by houxiaoxing** [ant-design/ant-design-mobile#4680]
### Version of antd-mobile

v5.0.0-rc.17

### What happened?

在最新的antd-mobile里面是没有lib文件的，但是在运行时我本地还是会查找对应文件然后报错，是对应babel配置问题吗？

### Relevant log output

```shell
Module not found: Error: Can't resolve 'antd-mobile/lib/card/style/css'
Module not found: Error: Can't resolve 'antd-mobile/lib/tabs'
```

**Comment by GOWxx** [comment]
https://mobile.ant.design/zh/guide/migration
