### ISSUE TITLE
Popover和Radio 一起使用在真机上会出现点击无法选择Radio问题。

### ISSUE THREAD

**Issue by Link-X** [ant-design/ant-design-mobile#4682]
### Version of antd-mobile

5.0.0-rc.16

### Operating system and its version

iOS, Android

### Browser and its version

ios 15.0.1 微信内置浏览器

### Sandbox to reproduce

https://codesandbox.io/s/nifty-water-y0237?file=/src/App.tsx

### What happened?

注意本问题，只有在手机上才能重新。请使用手机打开这个链接。window测试时正常的。
问题：
Popover内有Radio的时候, 第一次点击不会选中Radio,需要再次点击才能选中Radio。

期望：
正确的状态是，点击Radio组件时，选中Radio状态，并且弹出Popover组件的提示。

hack
如果维护组没有及时解决。我这里提供一个hack方法。不确定是否有问题。但是能暂时解决。
`
 <Popover
                          content="提示"
                          placement="top"
                          onVisibleChange={(v) => {
                            if (v) {
                              // 这是我现在的hack
                              const inp: any = document.querySelector(`.radio-box-${i} input`);
                              inp.click();
                            }
                          }}
                        >
                          <div
                            className="matrix-radio_fill"
                            style={{
                              width
                            }}
                          >
                            <Radio className={`radio-box-${i}`} value={v} />
                          </div>
                        </Popover>
`

**Comment by Link-X** [comment]
` <Popover
                          content="提示"
                          placement="top"
                          onVisibleChange={(v) => {
                            if (v) {
                              // 这是我现在的hack
                              // const inp: any = document.querySelector(`.radio-box-${i} input`);
                              // inp.click();
                            }
                          }}
                        >
                          <div
                            className="matrix-radio_fill"
                            style={{
                              width
                            }}
                          >
                            <Radio className={`radio-box-${i}`} value={v} />
                          </div>
                        </Popover>`

**Comment by zzzgydi** [comment]
![image](https://user-images.githubusercontent.com/27361820/149262333-e9e6f69d-4de9-4dc1-93c4-95aaf4640bd5.png)

![image](https://user-images.githubusercontent.com/27361820/149262822-89051b95-a6e8-4cd8-b401-fb0140a9e895.png)

你这里是对这整个div套一个popover， 移动端两次点击才触发radio的状态，这里有没有可能是第一次点击都是点的radio以外的空白区，这些空白区能触发popover。pc端不会是因为pc端popover响应的是hover事件

**Comment by awmleer** [comment]
这个应该是 rc-tooltip 的问题，我记得在 antd 中也有同样的问题

还有一个小问题是目前的 Popover 如果不传 trigger 属性，其实应该是要不会自动做显示和隐藏的处理，而全部交给用户控制的，但是现在是 fallback 到了 rc-tooltip 的默认，变成是默认为 hover 了，在移动端的组件库中是不应该支持的 hover 的，这个我改一下

**Comment by awmleer** [comment]
08856ae79

**Comment by Link-X** [comment]
> ![图片](https://user-images.githubusercontent.com/27361820/149262333-e9e6f69d-4de9-4dc1-93c4-95aaf4640bd5.png)
> 
> ![图片](https://user-images.githubusercontent.com/27361820/149262822-89051b95-a6e8-4cd8-b401-fb0140a9e895.png)
> 
> 你这里是对这整个div套一个popover，移动端这些空白区才可以点击触发收音机的状态，这里都没有是第一次点的收音机除了空白的地方，点击popover就可以触发了。pc不会是因为pc端popover响应是hover事件
这里之所以用一个div包裹是因为，在Popover里直接包裹Radio好像会报错 我记得.

**Comment by Link-X** [comment]
> 这个应该是 rc-tooltip 的问题，我记得在 antd 中也有同样的问题
> 
> 还有一个小问题是目前的 Popover 如果不传 trigger 属性，其实应该是要不会自动做显示和隐藏的处理，而全部交给用户控制的，但是现在是 fallback 到了 rc-tooltip 的默认，变成是默认为 hover 了，在移动端的组件库中是不应该支持的 hover 的，这个我改一下

是的antd也有类似的问题。

**Comment by Link-X** [comment]
不好意思 不小心把这个问题关闭了!

**Comment by awmleer** [comment]
通过 d995fd90 和 f7898d4e 修复了
