### ISSUE TITLE
input[type="search"] 样式问题

### ISSUE THREAD

**Issue by xiaoyindong** [ant-design/ant-design-mobile#4684]
### Version of antd-mobile

all

### Browser and its version

IOS 15 +

### What happened?

描述: ios 15+ 系统 input[type="search"] 设置背景色失败。

组件: SearchBar

<img width="382" alt="屏幕快照 2022-01-13 下午5 02 11" src="https://user-images.githubusercontent.com/27474244/149298900-b6774034-3c6f-4ed5-a4c5-124df0560534.png">

**Comment by Przeblysk** [comment]
https://codesandbox.io/s/winter-cdn-cslzv?file=/src/styles.css 可以设置啊

**Comment by awmleer** [comment]
可以提供一下复现 demo 么？
