### ISSUE TITLE
PullToRefresh 组件 antd-mobile 更新到^5.0.0-rc.17 下拉不下来了

### ISSUE THREAD

**Issue by Z-LianYan** [ant-design/ant-design-mobile#4686]
### Version of antd-mobile

^5.0.0-rc.17

### Description

antd-mobile 更新到^5.0.0-rc.17 下拉不下来了

**Comment by awmleer** [comment]
请提供一个复现 demo

**Comment by Z-LianYan** [comment]
从^5.0.0-rc.0升级到^5.0.0-rc.17升级后就下拉不了了，每次更新都有一些改变，原来有些是正常的升级后却有问题，体验...

**Comment by onlyoneHawk** [comment]
直接官方的demo copy下来贴到页面中，也是拉不下来

**Comment by awmleer** [comment]
官方文档上的 demo 我这里是可以正常拖拽的啊？你得给个准确的复现环境啊
在这里写个 codesandbox 吧：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx
