### ISSUE TITLE
Result 图标色彩问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#469]
现在用的是图片，如何更换色彩？希望支持 less 变量配置。

**Comment by silentcloud** [comment]
估计要重新改造，目前是传的 imgUrl，最好支持传 elment，比如 Icon type=xxx

**Comment by afc163** [comment]
例子要改成 Icon 的实现，否则这些例子还是不能配置变量。

**Comment by warmhug** [comment]
这些例子想怎么配置变量的？最后一个例子是 icon 实现

**Comment by afc163** [comment]
就是成功、失败这些经典例子不要用图片实现，否则真实场景复制过去，改颜色都没办法。

> 总不能自己下载图片颜色吧。
