### ISSUE TITLE
ImageViewer  ImageViewer.Multi 图片查看器只能在第一次初始化的时候，默认展示第几张图片，希望多加一个index可以改变展示的第几张图片

### ISSUE THREAD

**Issue by 1263781648** [ant-design/ant-design-mobile#4694]
### Version of antd-mobile

5.0.0-rc.9

### What is this feature about?

 ImageViewer.Multi 希望可以多加一个index控制当前展示第几张图片的参数
场景：多张图片展示，点击查看某一张的时候，应该默认从这一张图片开始展示

**Comment by awmleer** [comment]
受控模式暂时不会支持，不过后面我们可以加个 ref，通过 `ref.swipeTo(index)` 来手动调整 index
