### ISSUE TITLE
苹果手机图片上传组件有bug

### ISSUE THREAD

**Issue by pangyutong** [ant-design/ant-design-mobile#4697]
### Version of antd-mobile

5.0.0-beta.21

### Operating system and its version

iOS

### Browser and its version

钉钉嵌入浏览器

### What happened?

版本环境：iphone 系统13.6版本 钉钉-6.3.20版本 
必现方式：钉钉扫码进入我们h5项目 使用ImageUploader组件 上传图片
上传的请求体的格式不对 
导致后端报服务器异常

其他表现：iphone 13.6版本 微信上传正常 iphone 13.6版本手机自带浏览器正常 iphone 13.6版本dchart正常 android正常

代码如下：1、 // 上传图片

```
  async function mockUpload(file: File) {
    if (file instanceof File && file.size * 1) {
      const formData = new FormData();
      formData.append('file', file);
      await sleep(100);
      let imgUrl = '';
      await HTTP.post(api.upload.uploadFile, {
        data: formData,
        requestType: 'form',
        state: true,
      }).then(res => {
        if (res.code === 10000) {
          imgUrl = res.data + '';
        }
      });
      return {
        url: imgUrl,
      };
    } else {
      return {
        url: '',
      };
    }
  }
```

2、
```
    <ImageUploader
        value={fileList[0] && fileList[0].url ? fileList : []}
        onChange={setFileList}
        accept={'image/jpeg,image/jpg,image/png'}
        maxCount={1}
        upload={mockUpload}
        // beforeUpload={beforeUpload}
      >
```

### Relevant log output

```shell
日志是：Body: appendData%5Bname%5D=file&appendData%5BfileName%5D=18FBCF57-FA32-4F0D-80FC-AF6227E8074B.jpeg&appendData%5Btype%5D=object
```

**Comment by pangyutong** [comment]
怀疑是：钉钉6.3.20 内嵌浏览器内核版本过低，不支持某些代码片段

**Comment by awmleer** [comment]
在这里写一下 demo 吧：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by pangyutong** [comment]
demo已经上传，但是钉钉打不开codesandbox。

**Comment by pangyutong** [comment]
> 在这里写一下 demo 吧：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

demo已经上传，但是钉钉打不开codesandbox。

**Comment by awmleer** [comment]
所以你遇到的报错是这个么？

```
Body: appendData%5Bname%5D=file&appendData%5BfileName%5D=18FBCF57-FA32-4F0D-80FC-AF6227E8074B.jpeg&appendData%5Btype%5D=object
```

**Comment by pangyutong** [comment]
1、不正常的curl 
curl -H "Host: xx.xx.xx" -H "Accept: application/json" -H "Accept-Language: zh-cn" -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -H "Origin: http://xx.xx.xx" -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 AliApp(DingTalk/6.3.20) com.laiwang.DingTalk/22475258 Channel/201200 language/zh-Hans-CN UT4Aplus/0.0.6 WK" -H "DingTalk-Flag: 1" -H "Cookie: token=xxx; current=xxx; shopNo=xxx; merchantnNo=xxx; ticket=xxx" --data-binary "appendData%5Bname%5D=file&appendData%5BfileName%5D=1480E920-66CB-4A1F-97F1-5547B8D228E5.jpeg&appendData%5Btype%5D=object" --compressed "http://xx.xx.xx/api/cloud-base/open-api/gift/upload"
2、正常的curl
curl -H "Host: xx.xx.xx" -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryyCY1zYY7ywkdtt53" -H "Origin: http://xx.xx.xx" -H "Cookie: token=xxx; current=xxx; shopNo=xxx; merchantnNo=xxx; ticket=xxx-xxx-xxx" -H "Accept: application/json" -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.16(0x18001042) NetType/WIFI Language/zh_CN" -H "Accept-Language: zh-cn" --data-binary "------WebKitFormBoundaryyCY1zYY7ywkdtt53
Content-Disposition: form-data; name=\"file\"; filename=\"F4AF32EF-6994-4A70-81D2-60753FC3E4E5.jpeg\"
Content-Type: image/jpeg

����JFIF�����ExifMM*JR(�iZ���Ϡ���8Photoshop 3.08BIM8BIM%��ُ��	���B~��4ICC_PROFILE$applmntrRGB XYZ �
 acspAPPLAPPL���-appl���%M8�����
desc�ecprtd#wtpt�rXYZ�gXYZ�bXYZ�rTRC� chad�,bTRC� gTRC� descDisplay P3textCopyright Apple Inc., 2017XYZ �Q�XYZ ��=�����XYZ J��7
�XYZ (8ȹparaff�
Y� 
..... 省略......

**Comment by pangyutong** [comment]
> 所以你遇到的报错是这个么？
> 
> ```
> Body: appendData%5Bname%5D=file&appendData%5BfileName%5D=18FBCF57-FA32-4F0D-80FC-AF6227E8074B.jpeg&appendData%5Btype%5D=object
> ```

是的，按照官方api，在钉钉使用上传组件，拿到并且传递给后端的数据格式有问题

**Comment by awmleer** [comment]
看起来是 `data-binary` 有问题？不确定是不是 antd-mobile 的问题

**Comment by awmleer** [comment]
<img width="406" alt="image" src="https://user-images.githubusercontent.com/16526078/149725314-7dc9fdc7-30d1-4eb7-a20e-622e35111b31.png">

这里的 HTTP 是你自己封装的还是啥？ `formData` 可能不能这样传吧，或许是需要通过别的参数传进去？

大概率是这里的问题，不是 antd-mobile 的锅

**Comment by pangyutong** [comment]
> <img alt="image" width="406" src="https://user-images.githubusercontent.com/16526078/149725314-7dc9fdc7-30d1-4eb7-a20e-622e35111b31.png">
> 
> 这里的 HTTP 是你自己封装的还是啥？ `formData` 可能不能这样传吧，或许是需要通过别的参数传进去？
> 
> 大概率是这里的问题，不是 antd-mobile 的锅

axios的，稍微封装了一下。哈哈哈，查细致了，发现还真是const formData = new FormData(); formData.append('file', file);这两句的锅。哈哈哈 对不住大佬 耽搁您时间了
