### ISSUE TITLE
ImageViewer长按（想要保存图片）后无法滑动预览

### ISSUE THREAD

**Issue by GoldMinerXun** [ant-design/ant-design-mobile#4698]
### Version of antd-mobile

v5.0.0-rc.18

### Operating system and its version

iOS

### Browser and its version

IOS15 Safari

### What happened?

ImageViewer预览图片时长按图片后无法滑动预览

**Comment by awmleer** [comment]
怀疑和 #4642 是同一个问题，后面统一解决

**Comment by awmleer** [comment]
已修复
