### ISSUE TITLE
内嵌iframe样式改变

### ISSUE THREAD

**Issue by qussers** [ant-design/ant-design-mobile#470]
#### 本地环境
- antd-mobile 版本：0.8以上
- 操作系统及其版本：iOS,android
- 浏览器及其版本：safari

#### 你做了什么？
通过iframe的方式引入其他的网页，发现网页的样式在高清方案下变形

#### 你期待的结果是：

能不变形显示，或者iframe能不受高清方案影响

#### 实际上的结果：

变形

**Comment by qussers** [comment]
我现在采取了一种临时理方案，将高清脚本独立出来，按需加载~~

**Comment by warmhug** [comment]
iframe 下文档操作对象可能不对，建议自己修改高清脚本，或者去掉 iframe

**Comment by zhoujingchao** [comment]
@qussers 有好的解决方案么？这么多页面需要antd-mobile组件按需加载很蓝瘦啊
