### ISSUE TITLE
Picker在IOS某些情况无法滑动

### ISSUE THREAD

**Issue by crysad** [ant-design/ant-design-mobile#4701]
### Version of antd-mobile

5.0.0-beta.26

### Operating system and its version

iOS

### What happened?

IOS环境，在一个webview中，picker处于打开的状态，应用切到后台，然后重新打开，picker就无法滑动

**Comment by awmleer** [comment]
和 #4642 重复了，可以订阅一下那个 issue 哈，这个我关掉了

**Comment by crysad** [comment]
好的
