### ISSUE TITLE
v5版本Popover Menu点击事件冒泡

### ISSUE THREAD

**Issue by w611363303798** [ant-design/ant-design-mobile#4702]
### Version of antd-mobile

5.0.0-rc.18

### Operating system and its version

Others

### Browser and its version

Chrome 97.0.4692.71

### Sandbox to reproduce

https://codesandbox.io/s/agitated-borg-8zlhd?file=/src/App.js

### What happened?

点击 -- 更多 -- 编辑，会触发父元素click事件

**Comment by awmleer** [comment]
复现出来了，的确有这个问题，后面我们给 Popover.Menu 也加个 `stopPropagation` 属性

**Comment by awmleer** [comment]
Close via c4b6847cb
