### ISSUE TITLE
ImageViewer 放大图片后没办法滑动到下张图，必须缩放到原大小才能切换下张图

### ISSUE THREAD

**Issue by feng0100** [ant-design/ant-design-mobile#4707]
### Version of antd-mobile

5.0.0-rc.17

### Operating system and its version

Android

### What happened?

ImageViewer 放大图片后没办法滑动到下张图，必须缩放到原大小才能切换下张图。比较友好的交互应该是放大图片后，滑动图片到图片边缘再滑动就可切换到下一张图。但是现在是放大图片后空间无限大，滑动后图片出视窗了也切不到下张图。
![img1](https://user-images.githubusercontent.com/63195648/149897346-0e948673-8087-44dd-9326-ff8a64e10b5d.png)

**Comment by awmleer** [comment]
后面我们优化一下，这个实现起来稍有点难

**Comment by feng0100** [comment]
加油加油 支持你们！

**Comment by saxon-y** [comment]
这个放大图片后空间被无限放大，是不论单张还是多张都存在的一个 bug，多张图片放大后支持滑动切换现在暂时未实现，但是我觉得可以先修复上述 bug

**Comment by liangskyli** [comment]
ImageViewer 放大图片后没办法滑动到下张图，这个希望能优化下

**Comment by 1587315093** [comment]
移步 6310
