### ISSUE TITLE
--adm-button-border-width 设置0时，Button 点击样式有问题

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#4709]
### Version of antd-mobile

5.0.0-rc.19

### Browser and its version

all

### Sandbox to reproduce

https://codesandbox.io/s/amazing-dream-fk4qu?file=/src/App.tsx

### What happened?

```
<Button style={{'--adm-button-border-width': '0'}}>有问题</Button>
```

点击样式有问题
应该是这里有问题

```
top: calc(var(--border-width) * -1);
left: calc(var(--border-width) * -1);
```

**Comment by awmleer** [comment]
Fixed via 50b19ecf2
