### ISSUE TITLE
Switch组件自带的loading图片地址失效

### ISSUE THREAD

**Issue by kingbooqin** [ant-design/ant-design-mobile#4710]
### Version of antd-mobile

5.0.0-rc.16

### Operating system and its version

Others

### What happened?

Switch组件自带的loading图片地址失效

![image](https://user-images.githubusercontent.com/63731419/150080521-b161f12e-d3ed-47af-942a-a177f18b8c68.png)

**Comment by awmleer** [comment]
这个其实问题应该出在你自己项目的打包构建逻辑，不过等后面我们把 svg 文件的引入逻辑调整之后，就不存在这个问题了

你可以先检查一下你自己项目中对静态文件的打包逻辑

**Comment by awmleer** [comment]
b5db1155
