### ISSUE TITLE
ImageViewer 图片预览translate 移动的px有问题

### ISSUE THREAD

**Issue by LoveRecall** [ant-design/ant-design-mobile#4711]
### Version of antd-mobile

5.0.0 rc.20

### What happened?

![image](https://user-images.githubusercontent.com/17865339/150252971-67c3f0c3-f5e4-413c-ab29-8998d7f4827e.png)
![image](https://user-images.githubusercontent.com/17865339/150255425-a121e6a1-9539-4563-8a27-cf08ac11d604.png)
第一张是官网的 移动的px是计算上了 margin-right   一个-391
第二张是在自己项目中使用时就没有计算上了 margin-right 一个-375

**Comment by awmleer** [comment]
来个复现 demo 吧：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by LoveRecall** [comment]
// extraBabelPlugins: [
  //   [
  //     'import',
  //     {
  //       libraryName: 'antd-mobile',
  //       libraryDirectory: 'es/components',
  //       style: false,
  //     },
  //   ],
  // ],
抱歉！是我们开发人员自己配置的问题，导致antd出了这个错误
The px tester is not rendering properly.  Please make sure you have imported `antd-mobile/es/global`.

**Comment by awmleer** [comment]
OK 那 issue 我关闭了
