### ISSUE TITLE
Modal和Dialog组件设置image属性后，当图片过长，无法显示内容

### ISSUE THREAD

**Issue by frog-warm** [ant-design/ant-design-mobile#4712]
### Version of antd-mobile

5.0.0-rc.20

### Operating system and its version

Others

### Sandbox to reproduce

https://codesandbox.io/embed/zealous-saha-ktm4v?fontsize=14&hidenavigation=1&theme=dark

### What happened?

Modal和Dialog组件设置image属性后，当图片过长，无法显示内容，图片未放入组件body容器，没办法通过bodyStyle来设置最大高度和图片轮动

**Comment by awmleer** [comment]
复现出来了，我看看

**Comment by awmleer** [comment]
26def6b12 优化了一下，现在超长的话图片会上下滚动

下个版本发布
