### ISSUE TITLE
v5.0.0-rc.20 版本 是不是缺少css文件,npm下载后没有

### ISSUE THREAD

**Issue by youdianfan** [ant-design/ant-design-mobile#4714]
v5.0.0-rc.20 版本 是不是缺少css文件,npm下载后没有

**Comment by awmleer** [comment]
没缺失啊 https://unpkg.com/browse/antd-mobile@5.0.0-rc.20/es/components/button/

<img width="973" alt="image" src="https://user-images.githubusercontent.com/16526078/150296145-1e5a28e6-2072-41df-893e-8f6ab7302d06.png">

**Comment by youdianfan** [comment]
@awmleer 
![image](https://user-images.githubusercontent.com/27018910/150336086-7bf2c102-abe7-4ff6-bcbd-868f5e696bf4.png)
npm下载下来,是真没有

**Comment by awmleer** [comment]
噢你这个是cjs版本的，我之前检查的是es版本的，我明天看下哈
估计是打包构建的问题

**Comment by awmleer** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/16526078/150468589-c5784b26-5f56-46ee-a353-4fae280087f2.png">

https://unpkg.com/browse/antd-mobile@5.0.0-rc.20/cjs/components/auto-center/

cjs 版本的也是有 css 文件的啊，要不你重装一下看看？

**Comment by awmleer** [comment]
顺便，我也把构建脚本调整了一下，避免这种情况出现的可能： 5f7a0816f

issue 我先关掉了哈，如果还有问题的话，还是可以直接回复的
