### ISSUE TITLE
希望 Dialog 能提供 clear 之类的全局清理方法

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#4715]
### Version of antd-mobile

latest

### What is this feature about?

希望 `Dialog` 能提供 `clear` 之类的全局清理方法

`Dialog.clear()` 类似这种，能全局注销已经存在的Dialog

主要是因为路由切换的时候，`Dialog.confirm()` 并不会消失。他已经挂载在 `body` 上面了。

虽然 `getContainer` 能解决这个问题，但还是希望能够提供一种其他的选择

**Comment by awmleer** [comment]
OK，这个我们考虑一下

**Comment by liangskyli** [comment]
提供的话，就方便很多了，希望支持
