### ISSUE TITLE
图片上传后无法预览

### ISSUE THREAD

**Issue by 651882960luo** [ant-design/ant-design-mobile#4716]
### Version of antd-mobile

v5.0.0-rc.17

### Operating system and its version

Android

### Browser and its version

小米浏览器 v15.8.12

### What happened?

图片上传之后无法预览上传的图片

[新建文本文档.txt](https://github.com/ant-design/ant-design-mobile/files/7903867/default.txt)

```jsx
<FormListWrapper
  className={`${state.className} uploadBox`}
  value={fileList}
  required={state.required}
  label={label}
  ref={valideRef}
>
  <div style={{ padding: '0 10px' }}>
    <ImageUploader
      value={fileList}
      onChange={$fileList}
      multiple={checkType === '1' ? false : true}
      maxCount={checkType === '1' ? 1 : 0}
      upload={uploadService}
      onPreview={previewList}
      preview
      onDelete={onDelete}
    />
  </div>
</FormListWrapper>
```

**Comment by awmleer** [comment]
无法预览具体是指……？有截图么？

**Comment by awmleer** [comment]
是不是你上传的逻辑写错了？发一下 `uploadService` 这里吧

**Comment by 651882960luo** [comment]
这张是点击后没有反应，我按照上面加过preview属性，但没用






 
罗移&nbsp;&nbsp;研发部



Mobile:&nbsp;&nbsp;13594751071

***@***.***

Tel:&nbsp;&nbsp;400-886-1516

Web:&nbsp;&nbsp;www.macrowing.com


 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Jan 20, 2022 06:06 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ant-design/ant-design-mobile] 图片上传后无法预览 (Issue #4716)

&nbsp;



 
是不是你上传的逻辑写错了？发一下 uploadService 这里吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 651882960luo** [comment]
点击上传后的图片没有响应，用onPreview事件监听也没有去执行








 
罗移&nbsp;&nbsp;研发部



Mobile:&nbsp;&nbsp;13594751071

***@***.***

Tel:&nbsp;&nbsp;400-886-1516

Web:&nbsp;&nbsp;www.macrowing.com


 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Jan 20, 2022 06:05 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ant-design/ant-design-mobile] 图片上传后无法预览 (Issue #4716)

&nbsp;



 
无法预览具体是指……？有截图么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by awmleer** [comment]
你这是邮件回复的……？没看到图片啊？你点进来GitHub看看？

**Comment by 651882960luo** [comment]
> 你这是邮件回复的……？没看到啊？你点进来看看图片？

[uploadService.txt](https://github.com/ant-design/ant-design-mobile/files/7909534/uploadService.txt)
![微信图片_20220121090750](https://user-images.githubusercontent.com/96764476/150447139-ca451103-23a8-4278-b36f-18b68812a688.jpg)
这个是我通过ImageUploader上传的图片，但点击之后没有预览效果

**Comment by awmleer** [comment]
点击图片之后，浏览器中有报错么？

**Comment by 651882960luo** [comment]
> 点击图片之后，浏览器有报错么？

没有报错，就是没反应，连onPreview这个都没有反应

**Comment by awmleer** [comment]
还是尝试给一个能复现 demo 吧，根据目前的这些信息看不出来有啥问题

**Comment by 651882960luo** [comment]
> 还是试试看给一个能复现的演示吧，根据目前的这些信息不出来啥问题

不好意思，目前我已经找到问题了，麻烦了

**Comment by cgstian** [comment]
> 我现在遇到相同的问题，麻烦指点一下问题在哪里，非常感谢

**Comment by cgstian** [comment]
> > 还是试试看给一个能复现的演示吧，根据目前的这些信息不出来啥问题
> 
> 不好意思，目前我已经找到问题了，麻烦了

我现在遇到相同的问题，麻烦指点一下问题在哪里，非常感谢

**Comment by 651882960luo** [comment]
当时的问题是由于父级元素样式设置了禁用交互





      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2023年2月12日(周日) 凌晨5:13写道:

  


还是试试看给一个能复现的演示吧，根据目前的这些信息不出来啥问题

不好意思，目前我已经找到问题了，麻烦了


Message ID: ***@***.***&gt;
我现在遇到相同的问题，麻烦指点一下问题在哪里，非常感谢
