### ISSUE TITLE
ImageUploader 图片上传   value 写死了空数组  页面上还会显示上传的图片

### ISSUE THREAD

**Issue by 2401345934** [ant-design/ant-design-mobile#4717]
### Version of antd-mobile

ImageUploader 图片上传   value 写死了空数组  页面上还会显示上传的图片

### Sandbox to reproduce

ImageUploader 图片上传   value 写死了空数组  页面上还会显示上传的图片

### What happened?

ImageUploader 图片上传   value 写死了空数组  页面上还会显示上传的图片

**Comment by awmleer** [comment]
可以提供一下复现 demo 么？至少，提供一下你的代码片段？不然我们没有办法帮你排查问题

**Comment by 651882960luo** [comment]
对存数据的数组进行判断然后splice删掉不就好了
