### ISSUE TITLE
InfiniteScroll 组件父级设置overflow: overlay 滚动加载失效

### ISSUE THREAD

**Issue by whao0329** [ant-design/ant-design-mobile#4718]
### Version of antd-mobile

5.0.0-rc.17

### Operating system and its version

Others

**Comment by awmleer** [comment]
来个复现 demo？https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by whao0329** [comment]
> 来个复现 demo？https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

https://codesandbox.io/s/wandering-https-gr1oi?file=/src/App.tsx

**Comment by whao0329** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/src/utils/get-scroll-parent.ts
<img width="496" alt="截屏2022-01-21 下午2 23 05" src="https://user-images.githubusercontent.com/35947891/150476929-c220b11b-a547-443a-bafd-8636026c5305.png">
是因为这个正则里没有overlay

**Comment by awmleer** [comment]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/16526078/150477390-689a0ab3-2e51-48ea-b1f5-90989a21d23a.png">

看起来 overlay 已经弃用了

不过我还是支持一下吧

**Comment by awmleer** [comment]
91b8fbbd8

下个版本发布之后可以试一下效果
