### ISSUE TITLE
连个下拉框组件都没有

### ISSUE THREAD

**Issue by chunsenye** [ant-design/ant-design-mobile#4720]

**Comment by fonghehe** [comment]
你说的是select么，移动端基本都是pickerview的

**Comment by awmleer** [comment]
移动端的设计规范中是没有下拉框的，你可以使用 Selector、Picker、Checkbox、CheckList，也可以使用 Dropdown、Popup 自己封装一个符合你的需求的组件

**Comment by chunsenye** [comment]
> 你说的是select么，移动端基本都是pickerview的

好的谢谢

**Comment by chunsenye** [comment]
> 移动端的设计规范中是没有下拉框的，你可以使用 Selector、Picker、Checkbox、CheckList，也可以使用 Dropdown、Popup 自己封装一个符合你的需求的组件

好的谢谢
