### ISSUE TITLE
Swiper组件设置autoplay后，onIndexChange事件间隔autoplayInterval持续触发，不会停止

### ISSUE THREAD

**Issue by LuChunYu** [ant-design/ant-design-mobile#4722]
### Version of antd-mobile

5.0.0-rc.18

### Browser and its version

所有

### Sandbox to reproduce

https://codesandbox.io/s/quizzical-jang-nz0dm?file=/src/App.tsx

### What happened?

问题：
在autoplay为TRUE，非loop情况，onIndexChange事件一直触发，不会停止

预期：
autoplay为true非loop的情况下，最后一个swiperItem播放结束，不能触发onIndexChange事件

**Comment by awmleer** [comment]
Fixed via 089133681
