### ISSUE TITLE
V5版 Calendar 组件，切换月、年问题。

### ISSUE THREAD

**Issue by allan8212** [ant-design/ant-design-mobile#4725]
### Version of antd-mobile

v5.0.0-rc.21

### What is this feature about?

V5版 Calendar 组件，切换年、月没有触发onChange事件，也没找到单独的捕获事件。
这个怎么处理呢？

**Comment by Przeblysk** [comment]
感觉你的需求 DatePicker 更加合适，Calendar 就是为了选择明确的日期或者日期区间。

**Comment by allan8212** [comment]
> 感觉你的需求 DatePicker 更加合适，Calendar 就是为了选择明确的日期或者日期区间。

我是要做一个类似日程的内容展示，切换年份、月份需要重新加载数据，这个事件捕获不到。

**Comment by awmleer** [comment]
这个我们可以加个 `onPageChange` 属性暴露出来

**Comment by allan8212** [comment]
> 这个我们可以加个 `onPageChange` 属性暴露出来

目前有什么补救办法嘛？

**Comment by awmleer** [comment]
没有……等后面的版本发布吧

**Comment by saxon-y** [comment]
#4786
