### ISSUE TITLE
Why can't I see the old documents?

### ISSUE THREAD

**Issue by sukiy** [ant-design/ant-design-mobile#4726]
### Version of antd-mobile

antd-mobile 2.3.4

### What is this feature about?

Why can't I see the old documents?   antd-mobile 2.3.4

**Comment by Przeblysk** [comment]
![CleanShot 2022-01-22 at 17 24 35@2x](https://user-images.githubusercontent.com/18001272/150632945-a757d6d9-5a47-4aea-b9d5-58ec9310f4f5.png)

**Comment by Przeblysk** [comment]
![CleanShot 2022-01-22 at 17 28 10@2x](https://user-images.githubusercontent.com/18001272/150633056-4be6d453-8837-4661-a8a5-6404c46e749a.png)
