### ISSUE TITLE
Tag 只读型标签，为什么有点击选中效果？

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#473]

**Comment by warmhug** [comment]
提供只读功能。加 readOnly 配置项，或者修改 selected 的表现

**Comment by silentcloud** [comment]
@warmhug 现在没有只读型标签了啊，你这是 0.几的版本

现在只有这几种 

![image](https://cloud.githubusercontent.com/assets/1698185/19914366/0762a6ea-a0e5-11e6-8a56-495cbad4a383.png)

**Comment by warmhug** [comment]
https://mobile.ant.design/components/tag/
![image](https://cloud.githubusercontent.com/assets/2011119/19915208/9896b6be-a0eb-11e6-97d5-5db08e1afc1c.png)

**Comment by warmhug** [comment]
（demo 里的文案显示还有），加个只读类型，钉钉那边有需求

**Comment by silentcloud** [comment]
c716e623f23332e4fd7afd2a6ecfec96d72fe472 

这个在 alpha 上修了，不做在 0.9 上，表现有点不一样

**Comment by warmhug** [comment]
只有 小号标签 有只读类型？正常大小的标签也应该有吧

**Comment by silentcloud** [comment]
小号标签这个目前已经修复，大号的等设计师来评估，issue 先关了
