### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by Akunv** [ant-design/ant-design-mobile#4730]
### Version of antd-mobile

5.0.0-rc.21

### Description

nextjs + ant design mobile，使用swiper下item组件出现以下警告
`Warning: useLayoutEffect does nothing on the server, because its effect 
cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes. `

除了一个warn之外暂时没发现其他问题，组件是正常渲染使用的，只是有个警告
组件如下
`import { NextPage } from 'next'
import { Swiper, Toast } from 'antd-mobile'

export const Notice: NextPage = () => {
  const notices = ['公告1', 2, 3, 4, 5]

  return (
    <div className="w-full !h-30 flex p-2 ">
      <Swiper className="!rounded-lg border  border-gray-500">
        {notices.map((value, index) => (
          <Swiper.Item key={index}>
            <div
              className="flex justify-center items-center w-auto h-full"
              onClick={() => Toast.show(‘你点击了卡片 ${index + 1}’)}
            >
              {value}
            </div>
          </Swiper.Item>
        ))}
      </Swiper>
    </div>
  )
}`

**Comment by awmleer** [comment]
和 #4166 重复了，这个 issue 我关闭了哈，可以订阅一下那个 issue

**Comment by Akunv** [comment]
> 和#4166重复了，这个 issue 我关闭了哈，可以订阅一下那个 issue

#4166的issue去年10月提的到现在也没有解决a

**Comment by awmleer** [comment]
@Akunv 嗯嗯是的，因为这个几乎对业务没有影响，忽略掉这个 warning 就好

而且目前我们还没有找到比较优雅的解决方法

**Comment by Akunv** [comment]
> @Akunv嗯嗯是的，因为这个几乎对业务没有影响，忽略掉这个 warning 就好
> 
> 而且目前我们还没有找到比较优雅的解决方法

https://ahooks.js.org/zh-CN/hooks/use-isomorphic-layout-effect
康康这个？

**Comment by awmleer** [comment]
这个我知道的，不过也未必是最好的解法
