### ISSUE TITLE
Calendar has error: `o. isoWeekday is not a function` in production mode.

### ISSUE THREAD

**Issue by ArtemKha** [ant-design/ant-design-mobile#4733]
### Version of antd-mobile

5.0.0-rc.21

### What happened?

When I use `Calendar` in my app build and run it with yarn build --mode=production – app crashes. And build is ok when I use `antd-mobile/cjs` instead. Check it please, thank you.

**Comment by ArtemKha** [comment]
import { Calendar } from "antd-mobile/cjs" - OK
import { Calendar } from "antd-mobile" - NOT OK

**Comment by ChenGongWei** [comment]
[复现demo](url
[atd-next.zip](https://github.com/ant-design/ant-design-mobile/files/7930268/atd-next.zip)
)

**Comment by awmleer** [comment]
找到问题了，是因为在 Calendar 中没有给 dayjs 引入插件导致的，在 production 模式下，因为经过了 tree shaking，就暴露出这个问题了

**Comment by awmleer** [comment]
f750f9777
