### ISSUE TITLE
picker不支持只选'时-分'

### ISSUE THREAD

**Issue by mushan0x0** [ant-design/ant-design-mobile#4738]
### Version of antd-mobile

5.0.0-rc.22

### What happened?

antd-mobile2.x支持的time picker现在v5不支持了
![image](https://user-images.githubusercontent.com/29084441/151092766-ff0f1f61-faf7-4fd7-a168-02754b56e364.png)

**Comment by awmleer** [comment]
请阅读文档：
https://mobile.ant.design/zh/components/picker
![image](https://user-images.githubusercontent.com/16526078/151102443-e999016a-9309-41b8-9dc2-be806b306fe1.png)

**Comment by awmleer** [comment]
可以直接自己用 Picker 实现，非常简单
