### ISSUE TITLE
DatePicker visible时，选中值之前的日期，字体会先变黑后变灰。

### ISSUE THREAD

**Issue by farmercz** [ant-design/ant-design-mobile#4741]
### Version of antd-mobile

v5.0.0-rc.19

### Operating system and its version

iOS

### What happened?

DatePicker visible时，选中值之前的日期，字体会先变黑后变灰。
期望：直接置灰同安卓效果一致

**Comment by awmleer** [comment]
这个问题之前修复过，可以提供一下你 iOS 的具体版本么？

**Comment by awmleer** [comment]
噢我这里也复现了，我来看一下

**Comment by awmleer** [comment]
总算找到问题了，之前这个问题遇到好久了，甚至一度以为已经通过很 hacky 的方式解决掉了，今天再排查了一下，终于找到问题的根源了：
react-spring 中，`style={{ y }}` 其实真实渲染在 DOM 中会变成 `translate3d`，从而导致了 Safari 的一些样式问题（具体是为什么会有如此奇怪的效果就不得而知了，大概率是 Safari 把这个元素当作一个 3d 图层了，从而在计算图层的上下关系时出现了一些问题）

a42000281 中已修复

**Comment by farmercz** [comment]
棒棒棒 感谢
