### ISSUE TITLE
Next.js 使用中报Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by mokinzhao** [ant-design/ant-design-mobile#4743]
### Version of antd-mobile

^5.0.0-rc.22

### Operating system and its version

Others

### What happened?

Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at Tabs (webpack-internal:///./node_modules/antd-mobile/cjs/components/tabs/tabs.js:72:51)

### Relevant log output

```shell
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at Tabs (webpack-internal:///./node_modules/antd-mobile/cjs/components/tabs/tabs.js:72:51)
```

**Comment by awmleer** [comment]
和 #4730 #4166 重复了，可以看这两个 issue
