### ISSUE TITLE
Form.Item无法关闭箭头arrow

### ISSUE THREAD

**Issue by jinxiangqiang** [ant-design/ant-design-mobile#4745]
### Version of antd-mobile

5.0.0-RC.22

### What is this feature about?

Form.Item没办法修改内部List.Item的一些属性，比如arrow如果不需要的话没办法取消

**Comment by yangdepp** [comment]
@卡晨，感觉跟这个PR有关联
https://github.com/ant-design/ant-design-mobile/pull/4537

**Comment by awmleer** [comment]
@yangdepp 嗯嗯我来看一下
