### ISSUE TITLE
高清方案Picker表现异常

### ISSUE THREAD

**Issue by mushan0x0** [ant-design/ant-design-mobile#4748]
### Version of antd-mobile

5.0.0-rc.22

### What happened?

https://user-images.githubusercontent.com/29084441/151472206-0fe27d6b-e51a-4f70-8c49-91a0632dd163.mp4

有人提过这个，https://github.com/ant-design/ant-design-mobile/issues/4149 这个不修复的话高清方案没法用了

**Comment by awmleer** [comment]
麻烦提供一下你项目的具体信息？你所谓的高清方案，具体是什么样的配置？在蚂蚁内部有很多很多项目都使用了高清方案，但是目前 Picker 组件都是可以正常工作的。所以无法确定是你自己项目的问题还是 antd-mobile 的问题

另外，关于如何提交 issue 的指引，请查阅[这里](https://github.com/ant-design/ant-design-mobile/blob/master/.github/HOW_TO_ASK_QUESTIONS.md)

**Comment by mushan0x0** [comment]
![image](https://user-images.githubusercontent.com/29084441/151476875-972dd853-ad6b-43d6-a825-47737638b82d.png)
用的`babel-plugin-import`插件做的高清方案搭配的`postcss-px-to-viewport`
![image](https://user-images.githubusercontent.com/29084441/151477042-bf0f9eb0-c293-4609-9c96-1bfd75442824.png)

**Comment by mushan0x0** [comment]
目前临时的方案是手动放大`adm-px-tester `
```css
.adm-px-tester {
  transform: scale(2);
}
```

**Comment by awmleer** [comment]
引入 `global.css` 了么？控制台有没有 error 或者 warning 提示？

![image](https://user-images.githubusercontent.com/16526078/151477179-182cdc10-d8d1-42be-a0ee-14c70564b77f.png)

https://mobile.ant.design/zh/guide/import-on-demand

**Comment by mushan0x0** [comment]
![image](https://user-images.githubusercontent.com/29084441/151477228-dd8b2b07-c342-44f5-a1c0-1d6cfd6e76b1.png)
引入了的

**Comment by awmleer** [comment]
对于你这种配置方式，应该引入 `antd-mobile/2x/es/global` 而不是 `antd-mobile/es/global`，可以试一下看看

**Comment by mushan0x0** [comment]
> 对于你这种配置方式，应该引入 `antd-mobile/2x/es/global` 而不是 `antd-mobile/es/global`，可以试一下看看

还是一样的会有问题，只不过偏移得更大了

**Comment by awmleer** [comment]
顺便，现在已经不推荐使用 FastClick 了哈：

<img width="871" alt="image" src="https://user-images.githubusercontent.com/16526078/151477406-9aed96f8-f909-4a98-aca7-cb6a6f819bd8.png">

FastClick 自己的仓库首页上都注明了不推荐大家使用，除非真的有必要：https://github.com/ftlabs/fastclick

**Comment by awmleer** [comment]
> > 对于你这种配置方式，应该引入 `antd-mobile/2x/es/global` 而不是 `antd-mobile/es/global`，可以试一下看看
> 
> 还是一样的会有问题，只不过偏移得更大了

那给个最小复现的项目压缩包吧，不然我们在这里就是猜谜

**Comment by mushan0x0** [comment]
> > > 对于你这种配置方式，应该引入 `antd-mobile/2x/es/global` 而不是 `antd-mobile/es/global`，可以试一下看看
> > 
> > 
> > 还是一样的会有问题，只不过偏移得更大了
> 
> 那给个最小复现的项目压缩包吧，不然我们在这里就是猜谜

解决了似乎是改成`antd-mobile/2x/es/global`就行了

**Comment by mushan0x0** [comment]
> 顺便，现在已经不推荐使用 FastClick 了哈：
> 
> <img alt="image" width="871" src="https://user-images.githubusercontent.com/16526078/151477406-9aed96f8-f909-4a98-aca7-cb6a6f819bd8.png">
> 
> FastClick 自己的仓库首页上都注明了不推荐大家使用，除非真的有必要：https://github.com/ftlabs/fastclick

还是有必要，在remax的web端上用了响应变快了

**Comment by awmleer** [comment]
好，那 issue 我关闭了
