### ISSUE TITLE
自定义主题没有生效

### ISSUE THREAD

**Issue by CodingMonkeyzh** [ant-design/ant-design-mobile#475]
#### 本地环境

- antd-mobile 版本：0.9.3
- 操作系统及其版本：macOS sierra 10.12
- 浏览器及其版本：Chrome 54.0.2840.71 (64-bit)
- 脚手架：dva

#### 你做了什么？

我根据 [自定义主题这个文档](https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme) 的介绍，按照 “package.theme” 的方式对主题色进行定制：
**webpack.config.js：**
```javascript
  // 引入 antd-mobile
  webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd-mobile',
    style: true,
  }]);
```
**package.json：**
```json
"theme": "./src/assets/uiConfig.js",
```
**uiConfig.js：**
```javascript
var brandPrimary = '#30A080';
var brandPrimaryTap = '#2C9577';

module.exports = function() {
  return {
    brand_primary: brandPrimary,
    brand_primary_tap: brandPrimaryTap,
  };
};
```
我通过 `import { NavBar } from 'antd-mobile';` 这种方来来引人组件。

#### 你期待的结果是：

我希望我所做的更改能够生效，NavBar 的背景色为我自定义的颜色。

#### 实际上的结果：

控制台输出的loader其实以及包含了自定义的样式信息：
`"modifyVars":{"brand_primary":"#30A080","brand_primary_tap":"#2C9577"}`
但是，浏览器中并没有生效。
![image](https://cloud.githubusercontent.com/assets/2787386/19935623/b013008a-a155-11e6-8084-ccb4d6ed028a.png)

**Comment by afc163** [comment]
`'@brand-primary': brandPrimary,`

**Comment by CodingMonkeyzh** [comment]
@afc163 Hi, 为什么添加了`@`后还是没有生效？
loader 信息如下：
```json
{
    "test": new RegExp(/\.module\.less$/), 
    "loader": "/path/to/node_modules/extract-text-webpack-plugin/loader.js?{\"remove\":true}!css?sourceMap&modules&localIdentName=[local]___[hash:base64:5]&-autoprefixer!postcss-loader!less-loader?{\"sourceMap\":true,\"modifyVars\":{\"@brand_primary\":\"#30A080\",\"@brand_primary_tap\":\"#2C9577\"}}"
}
```

**Comment by afc163** [comment]
```diff
- "@brand_primary"
+"@brand-primary"
```

**Comment by CodingMonkeyzh** [comment]
非常感谢！没有注意到分隔符这里的细节。

**Comment by CodingMonkeyzh** [comment]
一开始以为直接把 `antd-mobile/lib/style/themes/default.js` 下的变量覆盖就行了，没注意到变量名要做这样一个处理

**Comment by afc163** [comment]
default.js 里的变量是 native 用的，你这里覆盖的是 antd-mobile/lib/style/themes/default.less 里的。

**Comment by xjdata** [comment]
貌似 brand-primary-tap 设置没有效果啊。。。

```
// theme.js
module.exports = function () {
    return {
        "@brand-primary": '#526178', //这个是生效的
        "@brand-primary-tap": '#1284d6', // 这一行及下一行都不行
        "@primary-button-fill-tap": '#1284d6'// 
    };
};
```

我也看了 源码
`@primary-button-fill-tap` 由
https://github.com/ant-design/ant-design-mobile/blob/4172539f52fbd3ff7a0f4bc76c475eb01a37c0e2/components/style/themes/default.less#L115
由  `@brand-primary-tap` 集成而来的 `@primary-button-fill-tap`
然后应用的到
https://github.com/ant-design/ant-design-mobile/blob/master/components/button/style/index.less#L34

```
&-primary {
    color: @color-text-base-inverse;
    background-color: @primary-button-fill;
    border: @border-width-sm solid @primary-button-fill;
    // &:active, // uc browser not work normal
    &.@{buttonPrefixCls}-active {
      background-color: @primary-button-fill-tap; //这里了。。。 但是没有生效.
    }
  }

```

**Comment by kingdujiabo** [comment]
请问这个方法必须使用webpack才可以么?

**Comment by afc163** [comment]
本质上 http://lesscss.org/ 的 modifyVars 功能。

**Comment by kingdujiabo** [comment]
我刚开始接触react-native, 对webpack不熟悉, 请问我在react-native项目中引用了ant-mobile,  想修改SegmentedControl组件中的字体大小, 按上面的方法, 没有起作用,麻烦你帮我看下有没有明显的问题

直接添加的文件webpack.config.js：
```
//webpack.config.js：
module.exports = function(webpackConfig) {
//  webpackConfig.babel.plugins.push('transform-runtime');
  webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd-mobile',
    style: true,
  }]);

  return webpackConfig;
};

```

theme.js
```
// theme.js
module.exports = () => {
  return {
    '@font_size_caption_sm': '12',
  };
};

```
package.json
```
//package.json
{
  "name": "MobileUi",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "antd-mobile": "^0.9.10",
    "react": "~15.4.0-rc.4",
    "react-dom": "~15.4.0-rc.4",
    "react-native": "0.38.0",
    "react-native-vector-icons": "^3.0.0"
  },
  "devDependencies": {
    "babel-jest": "17.0.2",
    "babel-plugin-import": "^1.1.0",
    "babel-preset-react-native": "1.9.0",
    "jest": "17.0.3",
    "jest-react-native": "17.0.3",
    "atool-build": "^0.9.0",
    "react-test-renderer": "~15.4.0-rc.4"
  },
  "jest": {
    "preset": "react-native"
  },
  "theme":"./theme.js"
}

```

**Comment by afc163** [comment]
上面的用法应该只适用于 web 项目，native 的项目如何修改配置需要 @warmhug 和 @silentcloud 来回答一下。

**Comment by kingdujiabo** [comment]
好的, 十分感谢

**Comment by silentcloud** [comment]
@kingdujiabo react-native 组件自定义样式目前只能通过传 styles 的 prop 来进行覆盖，`<SegmentedControl styles={你的样式文件} />`，暂时没有其他更好的办法；样式覆盖要参考组件 style 目前下面的 index.tsx
