### ISSUE TITLE
TextArea 文本域 maxLength问题

### ISSUE THREAD

**Issue by farmercz** [ant-design/ant-design-mobile#4750]
### Version of antd-mobile

v5.0.0-rc.19

### Operating system and its version

iOS

### Browser and its version

ios 15.2.1

### What happened?

TextArea 文本域 maxLength问题
比如maxLength=200,此时复制粘贴以下内容两次后就不能再手动输入了。实际此时长度198.

1、产品或者研发可通过口头或者邮件方式提出测试需求，对于熟悉的研发可以接收反馈我，对于不想接收的需求可以直接让提出人联系我，我这边统一评估；
2、对于提测系统第一时间加入待排期系统中，相关测试人员跟

**Comment by awmleer** [comment]
看起来的确存在这个问题，在 Chrome 下正常，在 Safari 下有问题

**Comment by awmleer** [comment]
Fixed via 870f6864f
