### ISSUE TITLE
希望Picker中通过css修改条目高度后，滑动时偏移距离能自适应(It is hoped that after modifying the item height through CSS in picker, the offset distance can be adaptive during sliding)

### ISSUE THREAD

**Issue by daoke0818** [ant-design/ant-design-mobile#4751]
### Version of antd-mobile

5.0.0-rc.23

### What is this feature about?

此功能在V2版本里已实现，希望V5也能实现，方便项目迁移，谢谢！
This feature has been implemented in V2 version. I hope V5 can also be implemented to facilitate project migration. Thank you!

![v2 png](https://user-images.githubusercontent.com/21966011/151653267-ad991c6b-381d-43e2-9180-28ae3ff8ba5b.png)
![v5](https://user-images.githubusercontent.com/21966011/151653268-9897faab-193c-42ef-ad0a-a3a3fb7cc767.png)

```.picker-v50023.adm-picker {
    .adm-picker-view-column-item {
        height: 2.75rem;
        line-height: 2.75rem;
        font-size: 1.0625rem;
        outline: 1px dashed orange;
    }

    .adm-picker-view-mask-middle {
        height: 2.75rem;
    }
}

.picker-v2 .am-picker {
    .am-picker-col{
        height: 13.75rem;
    }
    .am-picker-col-item {
        height: 2.75rem;
        line-height: 2.75rem;
        outline: 1px dashed skyblue;
    }

    .am-picker-col-indicator {
        height: 2.75rem;
    }
}```

项目demo：https://gitee.com/daoke0818/antd-mobile-loving

**Comment by saxon-y** [comment]
是否可以新增一个只支持 px 单位的 css 变量 `--item-height`

**Comment by awmleer** [comment]
不能只支持 px 单位的，毕竟有些项目里会通过 postcss 把 px 全都替换成 rem

这个我来搞吧～

**Comment by saxon-y** [comment]
> 不能只支持 px 单位的，毕竟有些项目里会通过 postcss 把 px 全都替换成 rem
> 
> 这个我来搞吧～

我觉得你太忙了，我想分担一些，哈哈哈
