### ISSUE TITLE
Sketch UI Kit download button does not work

### ISSUE THREAD

**Issue by spetushkov** [ant-design/ant-design-mobile#4752]
### Version of antd-mobile

4.2.0

### Description

Follow http://rn.mobile.ant.design/,

find Sketch UI Kit section and Download Immediately button, 

click on the button.

Result: nothing happens, files are not downloading.

Expected: files are downloaded in the .sketch format (zipped).

**Comment by awmleer** [comment]
The repo of `antd-mobile-rn` is here:
https://github.com/ant-design/ant-design-mobile-rn/issues

Please consider opening an issue there. This repo is for `antd-mobile` only.
