### ISSUE TITLE
TextArea的placeholder不起作用，没显示

### ISSUE THREAD

**Issue by zheng594** [ant-design/ant-design-mobile#4754]
### Version of antd-mobile

 v5.0.0-rc.24

### What happened?

如题，官网的demo示例placeholder就没起作用
![image](https://user-images.githubusercontent.com/11880516/151945087-b4ca1bd8-8b07-4835-a501-3723c90d8043.png)

**Comment by awmleer** [comment]
Fixed via e66c059c5
