### ISSUE TITLE
FloatingPanel 支持背景透明度变化

### ISSUE THREAD

**Issue by jing-wu** [ant-design/ant-design-mobile#4755]
### Version of antd-mobile

v5.0.0-rc.25

### What is this feature about?

希望支持背景色及透明度设置。随着上拉，背景色透明度由 0% 逐渐变化至设置的透明度。

**Comment by awmleer** [comment]
这个我们后面考虑一下，目前你可以使用 `onHeightChange` 事件自己实现这个效果

**Comment by awmleer** [comment]
update：打算在文档上加个 demo，组件本身不包含这块的逻辑了，不然就太臃肿了

**Comment by awmleer** [comment]
demo 已加，下个版本发布
