### ISSUE TITLE
Input readOnly为true时，clearable还能生效

### ISSUE THREAD

**Issue by farmercz** [ant-design/ant-design-mobile#4756]
### Version of antd-mobile

v5.0.0-rc.22

### Operating system and its version

iOS, Android

### Browser and its version

ios 15.2.1

### What happened?

Input readOnly为true时，clearable还能生效，当有value时直接默认显示出来了清空标志。
期望readOnly时，clearable不再生效

**Comment by awmleer** [comment]
Fixed via 69f8296b8
