### ISSUE TITLE
forceRender和destroyOnClose这两个有区别吗？

### ISSUE THREAD

**Issue by heyushuo** [ant-design/ant-design-mobile#4758]
### Version of antd-mobile

5.0.0

### Operating system and its version

iOS

### Sandbox to reproduce

https://codesandbox.io/s/eloquent-dewdney-b6y2o?file=/src/App.tsx

### What happened?

forceRender设置为true和false，没有区别，Mask的子组件表现形式相同，destroyOnClose设置为true的时候会卸载组件，是不是可以理解强制渲染的时候直接卸载组件即可？

**Comment by awmleer** [comment]
最准确的逻辑可以参考这段代码：（src/utils/use-should-render.tsx）

```ts
export function useShouldRender(
  active: boolean,
  forceRender?: boolean,
  destroyOnClose?: boolean
) {
  const initialized = useInitialized(active)
  if (forceRender) return true
  if (active) return true
  if (!initialized) return false
  return !destroyOnClose
}
```

说人话的话，就是 `forceRender` 优先级最高，如果开启了它，那么内容区会始终渲染，而当 `forceRender` 为 `false` 时，会走默认的行为，也就是“懒加载”，首次 `visible`（或者是 `active`，名字不重要）为 `true` 之前，内容不会被渲染，而且一旦内容区出现过之后，就会一直保持渲染，不会被卸载掉。
而 `destroyOnClose` 参数此时的效果就是，如果开启了 `destroyOnClose`，那么当 `visible` 变为 `false` 之后，内容会被卸载掉，而不仅仅是视觉上的“隐藏”。

举几个更具体的例子：

### Case 1

forceRender: false
destroyOnClose: fasle

| visible | 内容是否渲染 |
| --- | --- |
| false | false |
| true | true |
| false | true |
| true | true |
| false | true |

### Case 2

forceRender: true
destroyOnClose: fasle

| visible | 内容是否渲染 |
| --- | --- |
| false | true |
| true | true |
| false | true |
| true | true |
| false | true |

### Case 3

forceRender: false
destroyOnClose: true

| visible | 内容是否渲染 |
| --- | --- |
| false | false |
| true | true |
| false | false |
| true | true |
| false | false |

**Comment by Deja-vuuu** [comment]
> 最准确的逻辑可以参考这段代码：（src/utils/use-should-render.tsx）
> 
> ```ts
> export function useShouldRender(
>   active: boolean,
>   forceRender?: boolean,
>   destroyOnClose?: boolean
> ) {
>   const initialized = useInitialized(active)
>   if (forceRender) return true
>   if (active) return true
>   if (!initialized) return false
>   return !destroyOnClose
> }
> ```
> 
> 说人话的话，就是 `forceRender` 优先级最高，如果开启了它，那么内容区会始终渲染，而当 `forceRender` 为 `false` 时，会走默认的行为，也就是“懒加载”，首次 `visible`（或者是 `active`，名字不重要）为 `true` 之前，内容不会被渲染，而且一旦内容区出现过之后，就会一直保持渲染，不会被卸载掉。 而 `destroyOnClose` 参数此时的效果就是，如果开启了 `destroyOnClose`，那么当 `visible` 变为 `false` 之后，内容会被卸载掉，而不仅仅是视觉上的“隐藏”。
> 
> 举几个更具体的例子：
> 
> ### Case 1
> forceRender: false destroyOnClose: fasle
> 
> visible	内容是否渲染
> false	false
> true	true
> false	true
> true	true
> false	true
> ### Case 2
> forceRender: true destroyOnClose: fasle
> 
> visible	内容是否渲染
> false	true
> true	true
> false	true
> true	true
> false	true
> ### Case 3
> forceRender: false destroyOnClose: true
> 
> visible	内容是否渲染
> false	false
> true	true
> false	false
> true	true
> false	false

我今天看 Mask 组件也支持 forceRender 设置了之后弹窗一直弹起 感觉弹窗就没意义了
