### ISSUE TITLE
ImageUploader 图片上传组件，在IPhone 11 Pro MAX机型上兼容性问题

### ISSUE THREAD

**Issue by Dengkang-git** [ant-design/ant-design-mobile#4759]
### Version of antd-mobile

Ant Design Mobile v5.0.0-rc.25

### Browser and its version

IPhone 11 Pro MAX

### Sandbox to reproduce

无

### What happened?

ImageUploader 图片上传组件，在IPhone 11 Pro MAX机型上，点击图片预览后，再次点击无法关闭预览。

### Relevant log output

```shell
无
```

**Comment by awmleer** [comment]
请提供一个可以复现这个问题的 codesandbox：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

以及，最好可以录个屏看看？
