### ISSUE TITLE
关于 Stepper 和 Accordion 组件的建议

### ISSUE THREAD

**Issue by LayGit** [ant-design/ant-design-mobile#476]
1、Stepper 组件，点击加减能否不自动设置文本框焦点，键盘隐藏弹出在手机上容易引起页面晃动
2、Accordion 组件能否增加一个属性，设置开启/关闭动画效果。Panel 一多，里面的东西稍微复杂一点，动画看起来就不是那么平滑有点卡。

ant-mobile 0.9.4

**Comment by warmhug** [comment]
第一个问题已经接近，重装 node_modules 即可。

**Comment by LayGit** [comment]
重装了 好像还是不行哦！ 0.9.5版本 @warmhug

**Comment by warmhug** [comment]
明天发个版本，现在版本可以自己加 focusOnUpDown={false} 能直接生效

**Comment by warmhug** [comment]
关闭 Accordion 动画，设置`openAnimation={{}}`
