### ISSUE TITLE
Dialog.confirm配合Input组件使用时，无法正常绑定 state

### ISSUE THREAD

**Issue by zhangshichun** [ant-design/ant-design-mobile#4762]
### Version of antd-mobile

5.0.0-rc.18

### Operating system and its version

Others

### Browser and its version

Chrome Version 98.0.4758.82 (Official Build) (64-bit)

### Sandbox to reproduce

https://codesandbox.io/s/tender-leftpad-ltjyg?file=/src/App.tsx:373-378

### What happened?

期望：
1. 点击按钮
2. 在弹框内Input里输入，能正确将值绑定到state

实际：
2. 无法正常绑定

希望得到指点，应该怎么使用，感谢！

-----------------------------------------------
2022 -02-11 补充： 声明式写法没问题，只有函数式写法有问题

**Comment by awmleer** [comment]
这是一个挺常见的使用误区，可以简单理解为，通过 `Dialog.confirm`，我们是创建了一个独立的 React app，这意味着 创建出来的 Dialog 组件并不是 App 组件的子组件。
所以 `captcha` 这个 state 的更新，虽然触发了 `App` 组件的重渲染，但并不会导致 Dialog 组件重渲染，自然 Dialog 中的 Input 也就不会更新显示的内容了。

而解决方法有两种：

1. 正如你自己在补充中提到的，使用声明式的语法可以保持 App 和 Dialog 的父子组件关系，从而避免了这种问题
2. 对 Input 部分的逻辑独立封装一个组件出来，这样就不会出现“数据和状态在 App 中，Input 组件本身在 Dialog 中”这种割裂的情况了

**Comment by awmleer** [comment]
文档上现在加了一些说明：42a28aab

**Comment by zhangshichun** [comment]
> 这是一个挺常见的使用误区，可以简单理解为，通过 `Dialog.confirm`，我们是创建了一个独立的 React app，这意味着 创建出来的 Dialog 组件并不是 App 组件的子组件。 所以 `captcha` 这个 state 的更新，虽然触发了 `App` 组件的重渲染，但并不会导致 Dialog 组件重渲染，自然 Dialog 中的 Input 也就不会更新显示的内容了。
> 
> 而解决方法有两种：
> 
> 1. 正如你自己在补充中提到的，使用声明式的语法可以保持 App 和 Dialog 的父子组件关系，从而避免了这种问题
> 2. 对 Input 部分的逻辑独立封装一个组件出来，这样就不会出现“数据和状态在 App 中，Input 组件本身在 Dialog 中”这种割裂的情况了

谢谢指导，收益很多

**Comment by xuchao996** [comment]
mark

**Comment by blackskins** [comment]
> 方法2要怎么实现呢？ 即便我封装一个`MyInput`组件出来，它拥有自己的内部数据状态，能正确显示用户输入的验证码，但是在用户点确认后，App里收到`onConfirm`回调时也无法把`MyInput`的内部数据传出来呀。`MyInput`和`Dialog`一样不是App的子组件，`MyInput`的内部状态要如何传给App里的回调函数呢？

直接操作 MyInput组件的实例，ref。
