### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by 904192063** [ant-design/ant-design-mobile#4763]
### Version of antd-mobile

v5.0.0-rc.26

### Description

[https://mobile.ant.design/zh/components/tab-bar](url)
标签栏中，配合路由使用介绍页面，我的待办页面代码中的文字为”我的代办”，应改为“我的待办”
`function Todo() {
  return <div>我的代办</div>
}`

**Comment by awmleer** [comment]
Fixed via e41987b6
