### ISSUE TITLE
mask可以设置显示或消失透明度变化快一点吗，现在看是有延迟的

### ISSUE THREAD

**Issue by Emensionyu** [ant-design/ant-design-mobile#4764]
### Version of antd-mobile

5.0.0-rc.25

### What is this feature about?

mask组件

**Comment by awmleer** [comment]
暂时还没办法开放出来动画相关的配置，后面版本大概率会加上

**Comment by awmleer** [comment]
统一记在 https://github.com/ant-design/ant-design-mobile/issues/5090 了
