### ISSUE TITLE
TextArea 的 value 不能为 null, 否则会抛出异常

### ISSUE THREAD

**Issue by lujun2** [ant-design/ant-design-mobile#4765]
### Version of antd-mobile

5.0.0-beta.26

### Operating system and its version

iOS

### Browser and its version

Chrome 98.0.4758.80

### Sandbox to reproduce

https://codesandbox.io/s/relaxed-browser-u97gr?file=/src/App.tsx

### What happened?

`TextArea`的 value 不能为 `null`，会抛出异常

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/34977084/153759054-d62cbd29-1f4f-4cb6-8950-ce2e635b12c7.png">

在类型声明中有标记为 `string | undefined`，但在实际的开发过程中，`value` 通常为后端返回，经常会是null
并且其他组件如 `Input` 是支持 `value = null` 的

**Comment by awmleer** [comment]
我们不希望 Input 和 TextArea 存在 `value` 为 `null` 这种模棱两可的状态，虽然看起来方便，但是实际上会让项目和组件库本身都变得不够严谨，也增加了更多的边界情况中出现意外的可能性

**Comment by chenliangngng** [comment]
> 我们不希望 Input 和 TextArea 存在 `value` 为 `null` 这种模棱两可的状态，虽然看起来方便，但是实际上会让项目和组件库本身都变得不够严谨，也增加了更多的边界情况中出现意外的可能性

刚升级到rc.27发现了这个问题，除了上面的后端接口返回null问题，还有：
1.接口参数undefined值对于request来说是会把属性值去除的，比如{a: undefined,b: null}，参数会转换为{b: null}。如果现在不能使用null，因为undefined删除属性的原因导致接口不可用，所有依赖此特性的地方，都需要调整
2.原本null可以用来清空组件值，现在对于textArea要用''清空，这个改变习惯了，我不确定这会影响多少地方。未来如果input也这样做，类似number类型的input可能学习成本更高

改动三思呀，个人建议可以还原或者提供一个配置项吧，这个改动影响挺大的 @awmleer

**Comment by awmleer** [comment]
回答一下你新提出来的这两种情况的问题哈：

1. **上面的回复中也提到了，`value={undefined}` 的含义并不是表示 Input 的值为空，而是表示 Input 处于非受控模式。** 这两者是完全不可以等同的，所以本来就不能把 `undefined` 当作一种“值”来看待。而至于发送接口请求的时候，`undefined` 的字段被自动剔除掉了，这的确是 `JSON.stringify` 的默认行为，但是你本来也不应该把输入框的空值（也就是空字符串）和 `undefined` 混为一谈啊，这是需要从源头上解决和处理的。我的建议是设置默认值 `''`，你可以通过 Input 的 defaultValue 属性，也可以通过 `useState` 的 `defaultValue` 参数，而在 Form 表单中，可以通过 `initialValues` 属性，或者是，在数据获取的源头进行处理，具体取决于你的业务逻辑。
2. **用 `null` 来清空组件值是非常不严谨的。** 在有些组件中，`null` 是有正确含义的，例如在 Tabs 中，`activeKey` 为 `null` 表示没有 Tab 处于选中状态，但在 Input 和 TextArea 中，`null` 是没有正确含义的，空值是 `''`，如果 `''` 和 `null` 都表示空值，那么反倒更容易搞混。再举另一个例子，对于 Selector 组件来说，空值是 `[]` 而非 `null`，不要把 `null` 当作万金油，不然的话你的代码会渐渐腐蚀。这不是习惯不习惯的问题，是正确不正确、严谨不严谨的问题。
3. **额外再说一下学习成本的问题。** 首先我不觉得组件的空值类型变得更严格后，会增加很多额外的学习成本，空值的处理是不仅仅是业务项目在使用组件库时会遇到的问题，在很多其他的业务逻辑中（例如业务项目中自己封装的抽象组件），也同样存在，对于一个成熟的 React 开发者，应该不会在这里遇到学习成本的问题。

结论：

在 ts 类型上，确定不会把 Input 和 TextArea 的 `value` 类型调整为 `string | null | undefined`，但是考虑到鲁棒性，未来可能会给组件做一些额外边界保护，当用户真的传了 `value={null}`，我们至少不会让组件报错导致页面挂掉。但是请注意，这是边界情况下的组件保护，**应该尽量避免把这种保护逻辑当作组件的功能特性来使用**。

附上一个相关 issue #4332 ，是之前的讨论，和这个 issue 有点相似

**Comment by lujun2** [comment]
> 如果你的 ts 项目中开启了 `strictNullChecks`，那么 `null` 是不可以赋值给一个 `string | undefined` 类型的属性的
> 
> 不论是 Input 还是 TextArea，`value` 都只支持 `string` 或者 `undefined` 类型，而不支持 `null`，`string` 类型表示的是正常值，此时组件会进入受控模式，而 `undefined` 或者不传 `value` 属性则表示的是 `value` 属性未设置，此时组件会进入非受控模式

实际校验不住，在项目中是通过FormItem传递的属性值，在编译期是无法识别出来的

```ts
<Form>
  <Form.Item name={"xxx"}>
    <TextArea />
  </Form.Item>
</Form>
```

**Comment by lujun2** [comment]
> 如果你的 ts 项目中开启了 `strictNullChecks`，那么 `null` 是不可以赋值给一个 `string | undefined` 类型的属性的
> 
> 不论是 Input 还是 TextArea，`value` 都只支持 `string` 或者 `undefined` 类型，而不支持 `null`，`string` 类型表示的是正常值，此时组件会进入受控模式，而 `undefined` 或者不传 `value` 属性则表示的是 `value` 属性未设置，此时组件会进入非受控模式

实际校验不住，在项目中是通过FormItem传递的属性值，在编译期是无法识别出来的

```ts
<Form>
  <Form.Item name={"xxx"}>
    <TextArea />
  </Form.Item>
</Form>
```

**Comment by awmleer** [comment]
@lujun2 是的，在很多情况下都可能不会被 ts 校验出来，所以上面的结论里也提到了，边界处理后面还是会做的

**Comment by awmleer** [comment]
补一个 React 原生 input 的例子，`<input value={null} />` 会导致 React 提示一个 warning：

![image](https://user-images.githubusercontent.com/16526078/154185902-3df90e67-c57a-4e2f-890f-9e998b012ec2.png)

https://codesandbox.io/s/quizzical-firefly-0z2oqi?file=/src/App.js

**Comment by awmleer** [comment]
32a57ffd 已加对 `null` 的特殊处理和相应的测试用例

**Comment by chenliangngng** [comment]
> 未来如果input也这样做，类似number类型的input可能学习成本更高

接上面type为number类型的Input问题，目前组件库的处理是，可以赋值null，如果不能赋值null要怎么处理空值呢？
java对于number类型，''和null是不一样的，''会导致错误@awmleer

**Comment by awmleer** [comment]
@chenliangngng Input type=nubmer，value 的类型也是 string，并不是 number

**Comment by chenliangngng** [comment]
> @chenliangngng Input type=nubmer，value 的类型也是 string，并不是 number

我是说antd-mobile未来要怎么处理<Input type="number" />的参数和返回

**Comment by awmleer** [comment]
@chenliangngng 不会做特殊处理，你写的这个情况，判断逻辑是这样的：

```
<Input type="number" />
```

Input 没有设置 value，所以 fallback 到 defaultValue，defaultValue 未设置，所以再 fallback 到 defaultValue 的默认值 ''。

不知道你指的处理是具体什么逻辑的处理？
