### ISSUE TITLE
[ImageUploader] onPreview 增加 fileInfo 参数

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#4768]
### Version of antd-mobile

latest

### What is this feature about?

https://github.com/ant-design/ant-design-mobile/blob/494cb4debfd67bda23715630420370e8b87dbadc/src/components/image-uploader/image-uploader.tsx#L184-L189

`onPreview` 的参数，应该把 `fileInfo` 给传递出来。而不仅仅是 `index`

**Comment by awmleer** [comment]
噢的确可以，加上之后在有些场景下就更方便了
