### ISSUE TITLE
[ImageUploader] 默认的 preview 在控制台弹出警告

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#4769]
### Version of antd-mobile

latest

### What happened?

![image](https://user-images.githubusercontent.com/32838658/153820721-4729c8bc-b229-4b8e-90c5-ba740c56a8b9.png)

**Comment by awmleer** [comment]
2ac30eb9 已修复

**Comment by awmleer** [comment]
感谢反馈
