### ISSUE TITLE
Rate组件不支持背景色配置

### ISSUE THREAD

**Issue by w611363303798** [ant-design/ant-design-mobile#4771]
### What is this feature about?

目前只支持填充色配置，希望新增一个配置

**Comment by saxon-y** [comment]
这个背景色源于主题色 `--adm-color-light`，可自定义主题色 https://mobile.ant.design/zh/guide/theming

**Comment by w611363303798** [comment]
> 

背景色不应该跟主题色强关联，多个评分组件也不能区分了

**Comment by awmleer** [comment]
嗯嗯最好的方案肯定是单独加一个 `--inactive-color`
