### ISSUE TITLE
Popover组件倒三角存在0.5px左右空隙

### ISSUE THREAD

**Issue by w611363303798** [ant-design/ant-design-mobile#4773]
### Version of antd-mobile

5.0.0-rc.27

### Operating system and its version

Android

### Browser and its version

Edge 45.09.4.5079

### What happened?

在部分安卓机型存在该问题，小米10 MIUI12.0.11稳定版，系统浏览器和Edge浏览器
![image](https://user-images.githubusercontent.com/24557962/153983541-d39e88ce-71ed-4eba-944b-eefb6167ad9d.png)
![image](https://user-images.githubusercontent.com/24557962/153983559-d4e2d798-9795-4dd4-a258-55c4a78da404.png)

**Comment by miracles1919** [comment]
我也遇到了，发现通过调整屏幕大小可以复现

- 正常
![image](https://user-images.githubusercontent.com/22469543/154644893-685e3dd0-1bc2-4b27-bde8-e8ffd7c20604.png)

- 缩小
![image](https://user-images.githubusercontent.com/22469543/154644637-db73569d-300e-4324-be50-78c8bc9e5187.png)

- 放大
![image](https://user-images.githubusercontent.com/22469543/154644957-e962732c-dd6a-4d9d-8edd-9660b11a4824.png)


于是我把这个 svg 复制了下来，底部确实有空白，或许是这个原因 @awmleer 
![image](https://user-images.githubusercontent.com/22469543/154645677-9d4a5ba7-d8ee-44c1-be7a-62ea0c3a39a9.png)

**Comment by awmleer** [comment]
@miracles1919 这个空白是箭头顶端的，可是上面截图里的空隙其实是箭头底部位置和 Popover 主体之间的，感觉不是这个问题导致的

**Comment by miracles1919** [comment]
确实不是 svg 的问题

**Comment by awmleer** [comment]
嗯嗯是挺玄学的，感觉是和浏览器的渲染机制有关，可能在计算元素位置或者大小时出现了偏差

**Comment by saxon-y** [comment]
> @miracles1919 这个空白是箭头顶端的，可是上面截图里的空隙其实是箭头底部位置和 Popover 主体之间的，感觉不是这个问题导致的

感觉是这个 svg 内容高度没撑满导致的，只要放大就能看见有间隙， @awmleer 
![Snipaste_2022-02-23_18-52-51](https://user-images.githubusercontent.com/49136621/155305863-21e376df-15a3-4109-b5e1-e69d633a6a9f.png)

**Comment by xiaoyao96** [comment]
> 这个空白是箭头顶端的，可是上面截图里的空隙其实是箭头底部位置和 Popover 主体之间的，感觉不是这个问题导致的

svg用了旋转，箭头顶端的空白是不是有一定影响...

**Comment by awmleer** [comment]
我也复现出来了，似乎只在某些缩放比率下面有问题

**Comment by awmleer** [comment]
发现 antd 也有这个 bug：

![image](https://user-images.githubusercontent.com/16526078/155934907-0974fe3d-8387-4831-b808-21e346f70e88.png)

![image](https://user-images.githubusercontent.com/16526078/155934950-4433b912-3bb2-41d5-a3d8-2f81461770f5.png)

**Comment by awmleer** [comment]
先不 help wanted 了吧，后面我重构底层实现的时候再看一下

**Comment by awmleer** [comment]
目前的技术方案，感觉很难解决这个问题，主要是黑色的 Popover 背景是半透明的，没办法让箭头和内容块重叠，除非是背景单独作为一层，文字内容作为另一层，但是感觉这样改造性价比太低了

这个先 issue 关掉了，暂时不打算解决这个问题了

**Comment by awmleer** [comment]
感谢各位朋友们一起讨论～

**Comment by HappyYA** [comment]
为了关issue而关issue?

**Comment by awmleer** [comment]
@HappyYA 上上上条评论里已经解释过情况了：



> 目前的技术方案，感觉很难解决这个问题，主要是黑色的 Popover 背景是半透明的，没办法让箭头和内容块重叠，除非是背景单独作为一层，文字内容作为另一层，但是感觉这样改造性价比太低了
> 
> 这个先 issue 关掉了，暂时不打算解决这个问题了
