### ISSUE TITLE
关于Drawer使用碰到的问题

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#478]
#### 本地环境

- antd-mobile 版本：0.9.4
- 操作系统及其版本：mac
- 浏览器及其版本：chrome

#### 你做了什么？
根据官方例子复制了代码

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：
发现.drawer-container中height：100%，不起效果，内容无法显示，如果将height改为Nrem就可以显示，但这样就不能自适配了

**Comment by warmhug** [comment]
使用 flex 布局，自己查查这么用

**Comment by motorguo** [comment]
看到了这么多个关于 `Drawer` 的 issues，然而并没有一个是 ok 的。怀疑人生ing

**Comment by liubin1023** [comment]
@motorguo 你的OK吗，我其他的浏览器都可以了，但是在android上面不行，包括android的原生浏览器、qq浏览器、微信浏览器，不过安装chrome是可以的。郁闷中

**Comment by motorguo** [comment]
@liubin1023 我的是 web 端的，之前的项目是可以了，昨天摘官网的示例代码测试不行，怀疑人生中... 它们官网的 demo 是另外改造过的，展示效果的代码不一定与示例代码一样使用。
