### ISSUE TITLE
ant-design-mobile V5 给到的迁移方案有失稳妥

### ISSUE THREAD

**Issue by pigcan** [ant-design/ant-design-mobile#4780]
### Description

> 而对于之前还在使用 antd-mobile v2 的项目，我们也提供了完备的[迁移指南](https://mobile.ant.design/zh/guide/migration)

不知道我们对完备这个词的理解是否一致

换个 xx-design 我还能理解，给到的唯一迁移方案就是共存这我无法理解

站在开发者角度，既然选择了继续使用 antd-mobile 这个品牌，那么就建议写 antdmobile-codemod，应该让更多的开发者看到维护团队的责任心，让更多的开发者感受到担当，并有信心一直用下去。

**Comment by awmleer** [comment]
v2 和 v5 几乎是完全两套组件库，除了品牌上的延续，技术上是没有关联的，你提到的 codemod 我们没有做，背后的原因是这样的：

- v5 和 v2 API 差异过大，甚至组件能力都是不对等的，codemod 能不能写出来，写出来好不好用，这本身的**可行性**是挺大的问题。v5 到 v2 的升级，更像是 angular.js 到 Angular 的升级，已经不是一个 codemod 可以解决的问题了。
- 即便 codemod 能写，但想必会需要投入非常多的时间和精力，作为 v5 版本的开发者，坦白而言**我的精力是有限的**，在这个前提下，我更希望的是**把 v5 版本的组件本身做好**，也相信对于大多数的使用者来说，也是希望如此的。我觉得这里直接因为我们没有提供 codemod，就直接扣“没有责任心和担当”的帽子，未免有失偏颇。
- “给到的唯一迁移方案就是共存”。这我也挺无奈的，能确保两个版本可以良好的实现共存，我觉得已经很不错了。而且如果我作为业务项目中的使用者，我其实更希望能够采用这种共存+逐步替换“的迁移方式，更可靠也更可控。当然，如果你有更好的迁移方案的思路，也欢迎我们一起做**技术上的客观讨论**。
