### ISSUE TITLE
Input 组件字体过小时高度问题

### ISSUE THREAD

**Issue by miracles1919** [ant-design/ant-design-mobile#4785]
### Version of antd-mobile

5.0.0-rc.27

### Operating system and its version

Others

### Sandbox to reproduce

https://codesandbox.io/s/input-xdkr1s?file=/src/App.tsx

### What happened?

`Input` 组件 `clearable` = `true`， `--font-size` 设置成 `12px` 时，`input` 的高度会随着图标的出现发生变化

造成原因是因为 `ytm-input-clear` 的高度超过了 `input`

**Comment by miracles1919** [comment]
我的想法是加个 `min-height` 或者用`visibility` 控制

**Comment by awmleer** [comment]
`visibility` 不太合适，会导致左右的空间也被占用

感觉只能通过 `min-height` 先临时解决一下了
