### ISSUE TITLE
add form.getFieldsState、form.setFieldsState method to FormInstance

### ISSUE THREAD

**Issue by NexxLuo** [ant-design/ant-design-mobile#4788]
### Version of antd-mobile

5.0.0-rc.27

### What is this feature about?

提供  `getFieldsState` 、`setFieldsState`更便捷、灵活的管理字段状态，目前只能管理字段的value；

场景1：动态设置某字段的disabled、visible状态
场景2：获取当前所有字段的disabled、visible、value

如果能提供一个 `setFieldsComponentProps` 方法给所有字段控件传递组件props会更好。

**Comment by awmleer** [comment]
disabled 和 visible 状态是在 Form.Item 上设置的，如果提供了 `setFieldsState`，就违背了 single source of truth 的原则了，所以不会加这个方法的

`setFieldsComponentProps` 同理

至于 `getFieldsState`，似乎没有什么必要？`disabled` 都是完全受你自己控制的，为啥需要组件库再额外暴露出来？可以考虑举个具体的例子，我们看看目前的问题是什么，以及如果用 `getFieldsState` 的话能不能解决？

**Comment by NexxLuo** [comment]
个人认为，`disabled`、`hidden`这类状态本身就和`value`一样属于表单字段的标准状态，既然如此，交由表单来管理也是理所应当。这些状态当然也可以自己控制，但会带来一些额外代码量。 如果不能管理这些标准状态，`getFieldState`也就没有必要了。
