### ISSUE TITLE
RangePicker 是否可以手填开始和结束年月日

### ISSUE THREAD

**Issue by eddyzhang1986** [ant-design/ant-design-mobile#479]
#### 本地环境

- antd-mobile 版本： ant designer 2.0.1
- 操作系统及其版本：windows 7旗舰版
- 浏览器及其版本：Chrome最新版

#### 你做了什么？

RangePicker 是否可以手填开始和结束年月日

#### 你期待的结果是：

RangePicker 可以手填开始和结束年月日，
因为我想输入 2016年12月1日~2099年12月1日，这样选择太繁琐啦

#### 实际上的结果：

RangePicker 貌似不可手动输入年月日

#### 可重现的在线演示

官网就可以。

**Comment by afc163** [comment]
初始状态也应该可以手填。

**Comment by afc163** [comment]
提错地方了。

**Comment by eddyzhang1986** [comment]
OK，我重新填一下
