### ISSUE TITLE
node 无法 require 包进行服务端渲染

### ISSUE THREAD

**Issue by snadn** [ant-design/ant-design-mobile#48]
因为需要对 .web.js 后缀进行处理，以及 .web.js 中直接 require 了 less 文件等。
导致服务端的node无法直接require 此包进行服务端渲染。

不知道后续会考虑针对 **服务端渲染** 进行相关的处理吗？

**Comment by warmhug** [comment]
会考虑，是有必要的。

**Comment by snadn** [comment]
写了个脚本把 xxx.web.js 转成 xxx.js
https://gist.github.com/snadn/ad79f3847ffa191bb1d3082df9ceadbc
