### ISSUE TITLE
0.9.4 => 0.9.5 Accordion Bug

### ISSUE THREAD

**Issue by LayGit** [ant-design/ant-design-mobile#480]
刚升级了 antd-mobile 到 0.9.5版本，然后 Accordion 组件传入 style 属性
`<Accordion accordion style={{ marginBottom:'1.1rem' }}>`
就报错：
warning.js:36 Warning: Failed prop type: Invalid prop `style` of type `object` supplied to `Collapse`, expected `string`.

大概翻了下源码
`Accordion.prototype.render = function render() {
        return _react2["default"].createElement(_rcCollapse2["default"], __assign({}, this.props));
    };`

Accordion 引用了 `rc-collapse` 并把自己的 props 传过去了，此时 style 是个 React.CSSProperties

而在 `rc-collapse` 中
`propTypes: {
    ...
    style: _react.PropTypes.string
  },`

定义的是 string

**Comment by silentcloud** [comment]
@afc163

https://github.com/react-component/collapse/blob/master/src/Collapse.jsx#L30

**Comment by silentcloud** [comment]
@LayGit 已经修了 rc-collapse@1.6.9， 你重装试试
