### ISSUE TITLE
当元素容器下滑一定距离时再上滑，无法触发PullToRefresh

### ISSUE THREAD

**Issue by Haoxuan8** [ant-design/ant-design-mobile#4802]
### Version of antd-mobile

v5.0.0-rc.28

### Operating system and its version

iOS, Android

### Sandbox to reproduce

https://mobile.ant.design/~demos/pull-to-refresh-demo1

### What happened?

1. 当元素容器下滑一定距离时再上滑，无法触发PullToRefresh
![pulltorefresh1](https://user-images.githubusercontent.com/47069259/154895591-b14e0454-acde-4382-be28-4947414f40c6.gif)

2. 触发PullToRefresh后再往下滑时容器无法滚动
![pulltorefresh2](https://user-images.githubusercontent.com/47069259/154895822-9d658b3f-1d26-415a-b92c-c60758f7fcfd.gif)

**Comment by awmleer** [comment]
1. 这个是目前的预期行为，后面可能会开放一个 API 出来让用户选择行为
2. 我没 get 到问题是出在哪里……要不你具体再描述下？

**Comment by Haoxuan8** [comment]
> 2. 我没 get 到问题是出在哪里……要不你具体再描述下？

是希望在持续下滑的过程中，在 head 消失后，能继续滚动列表

**Comment by awmleer** [comment]
噢我理解你的意思了，我来看下

**Comment by miracles1919** [comment]
试了一下，下滑**一定**距离，再上滑的时候，就跟滚轮滑动效果一样，这应该是浏览器行为吧

在微信中就是这个页面下滑了

![image](https://user-images.githubusercontent.com/22469543/156139617-755c0412-139d-43b7-8731-a8db33cc8b07.png)

**Comment by awmleer** [comment]
不做特殊处理的话的确是浏览器默认的行为，不知道能不能做拦截和处理（做了也不太清楚稳不稳）

**Comment by shusiwei** [comment]
> 不做特殊处理的话的确是浏览器默认的行为，不知道能不能做拦截和处理（做了也不太清楚稳不稳）

很难做，副作用一大堆，说白了就是不用浏览器本身的body scroll，模拟一个scroll

**Comment by awmleer** [comment]
嗯嗯，还是先不做了
