### ISSUE TITLE
popup组件弹出警告

### ISSUE THREAD

**Issue by A1yangshuang** [ant-design/ant-design-mobile#4805]
### Description

渲染弹出的提示：
In Popup you are calling useMemo/useCallback without passing arguments.
This is a noop since it will not be able to memoize, it will execute it every render.

这是什么原因导致的？
每次渲染会出现很多的警告

**Comment by awmleer** [comment]
看起来是你自己的业务逻辑？

提供一个最小复现 demo 吧
