### ISSUE TITLE
[移动端demo页面] 希望在页面里增加搜索框或者输入框增加按关键字过滤的能力

### ISSUE THREAD

**Issue by GOWxx** [ant-design/ant-design-mobile#4809]
### Version of antd-mobile

v5.0.0

### What is this feature about?

提升组件 demo 页面在移动端下的体验
<img width="446" alt="image" src="https://user-images.githubusercontent.com/12870715/155012513-a1485c8b-6c45-4898-beef-cfa0744abb8d.png">

**Comment by awmleer** [comment]
这个可以有
