### ISSUE TITLE
请问ListView 的文档中所述的不支持特性 包含下方那几条吗？

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design-mobile#481]
https://mobile.ant.design/components/list-view/#不支持的特性

onChangeVisibleRows
stickyHeaderIndices
ScrollView props:
keyboardDismissMode (not support control keyboard)
keyboardShouldPersistTaps (not support control keyboard)
onContentSizeChange (use onLayout instead)
removeClippedSubviews
showsHorizontalScrollIndicator (use css style instead)
showsVerticalScrollIndicator (use css style instead)
View props: 注意：只支持onLayout prop

这些是说不支持的对吧？

**Comment by warmhug** [comment]
是的，更新了下文档、描述更清晰点
