### ISSUE TITLE
兼容性页面文档错误

### ISSUE THREAD

**Issue by chentianxin** [ant-design/ant-design-mobile#4815]
### Version of antd-mobile

5.0.0

### Operating system and its version

iOS

### Browser and its version

iOS Safari 9.1

### What happened?

https://mobile.ant.design/zh/guide/quick-start#%E5%85%BC%E5%AE%B9%E6%80%A7
说明和示例代码不匹配
![FDB7E8FE-F125-4BF9-8085-0B928F96268B](https://user-images.githubusercontent.com/49486355/155111360-8020390a-bf1c-447d-8af9-928c9959f60c.png)

**Comment by awmleer** [comment]
感谢，已改 5780eef0
