### ISSUE TITLE
Form.Item组件内部元素自带border-top属性，导致每一个表单项上面都有细线，且无法隐藏

### ISSUE THREAD

**Issue by wwz223** [ant-design/ant-design-mobile#4819]
### Version of antd-mobile

5.0.0

### What is this feature about?

从代码中看是在Form组件内部又套了一个list.item组件，list.item组件内有默认的border-top，但是在Form组件使用中没有地方可以设置这个属性，希望可以在form层可以对内部使用的list.item的组件的样式进行配置

**Comment by wwz223** [comment]
https://mobile.ant.design/zh/components/form

**Comment by ottomao** [comment]
+1 

border-top好烦人

![image](https://user-images.githubusercontent.com/1622697/155253428-8a44e1ea-a7bb-47c5-8ced-bcc3bf1d7474.png)

**Comment by awmleer** [comment]
@ottomao 这种情况其实推荐是 Form 的 `mode` 设置为 `'card'`，然后用 `Form.Header` 做间隔……类似下面这样：

```jsx
<Form mode='card'>
  <Form.Item>...</Form.Item>
  <Form.Item>...</Form.Item>
  <Form.Header/>
  <Form.Item>...</Form.Item>
  <Form.Item>...</Form.Item>
</Form>
```

![image](https://user-images.githubusercontent.com/16526078/155272013-6416f106-4977-4511-b378-e0af9bf458c9.png)

就不会出现奇怪的 border 效果了

**Comment by wwz223** [comment]
> 

倒是一种临时的解决方案，但Form组件优化还是有必要的

**Comment by awmleer** [comment]
已加 #4823
