### ISSUE TITLE
ListView组件 会重复渲染

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design-mobile#482]
- antd-mobile 版本：0.9.5
- 操作系统及其版本：win10
- 浏览器及其版本：chrome 54
- react 环境 ： dva，并应用了dva中的router。

#### 你做了什么？

引入 antd-mobile 的 ListView

#### 实际上的结果：
Page2个A,B， A中引用了ListView 并设置了 滚动刷新。 目前除了个别属性有点不理解外，运行还是正常的。

B中 引用了 List。

 首先router到PageA，加载了一些数据。 

之后router到B。B中的list加载了另一些数据， 

不论使用routerRedux.push或routerRedux.replace到b后。拖动页面到达底部时， 并未在页面上显示的A中的ListView  会触发onEndReached事件。

#### 你期待的结果是：
不知道 是不是我的用法不对， 希望的结果是 当ListView不在当前显示的区域内时， 下拉到页面底部 不会触发ListView的onEndReached事件。

**Comment by warmhug** [comment]
重装 node_modules 。另外自己调试下、确认切换走 router 后、listview 组件会被销毁掉（即 rmc-list-view 的 componentWillUnmount 方法执行到）

**Comment by xjdata** [comment]
重装 node_modules  解决了。。。。 

呃。 win下开发的原因？  我晕了。

**Comment by GZWZC** [comment]
@xjdata 你好 我想问一下你  你是react开发还是react-native开发

**Comment by xjdata** [comment]
react
