### ISSUE TITLE
tabbar的文档是不是少了一点啊

### ISSUE THREAD

**Issue by haodan123** [ant-design/ant-design-mobile#4821]
### What is this feature about?

为什么不能固定在最底部啊

**Comment by awmleer** [comment]
可以看下 demo 对应的 less 文件，布局是自己在业务中实现的，组件本身不包含定位逻辑：

![image](https://user-images.githubusercontent.com/16526078/155256548-5dc35e04-19ee-448d-8b5b-5acdd2a16b8b.png)

**Comment by awmleer** [comment]
文档上也注明了一下，经常有同学来问这个问题： 3811c8ca0

**Comment by haodan123** [comment]
大佬,tabbar组件,点击切换,组件和下面的东西都能切换,但是url地址栏的路由不变是啥情况,

**Comment by awmleer** [comment]
@haodan123 听起来是另外一个问题了，单独提一个 issue 吧，然后提供一下复现 demo
