### ISSUE TITLE
tabbar组件,点击图标,组件高亮可以切换,但是路由不变是啥情况啊

### ISSUE THREAD

**Issue by haodan123** [ant-design/ant-design-mobile#4824]
### Description

代码完全复制文档上的,只是吧组件换成自己的了

**Comment by miracles1919** [comment]
提供一下复现的 demo

**Comment by awmleer** [comment]
[提问指引](https://github.com/ant-design/ant-design-mobile/blob/master/.github/HOW_TO_ASK_QUESTIONS.md)
