### ISSUE TITLE
picker组件修改选项高度时，wheel大小没变

### ISSUE THREAD

**Issue by xsbest** [ant-design/ant-design-mobile#4827]
### Version of antd-mobile

v5.0.0

### Operating system and its version

Others

### Browser and its version

chrome

### What happened?

使用picker组件，在全局修改选项高度（column）时，wheel大小没变，猜测是没获取到更新的dom的高度（dummyRef的高度）

**Comment by awmleer** [comment]
提供一个具体的复现 demo？
https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx
