### ISSUE TITLE
antd-mobile按照第一种方法从@2.0升级到@5.0使用任意组件都报错

### ISSUE THREAD

**Issue by liuyingdiandian** [ant-design/ant-design-mobile#4828]
### Version of antd-mobile

5.0.0

### Operating system and its version

Others

### What happened?

![image](https://user-images.githubusercontent.com/44707467/155286915-4819003f-6ed2-4dcf-a9ea-7ffc25e267f2.png)

这是引入：import { Card } from 'antd-mobile';
这是版本改造，package.json：
"antd-mobile": "^5.0.0",
"antd-mobile-v2": "^2.3.4",

**Comment by liuyingdiandian** [comment]
引用任意组件都报上面的错，还有这个：
![image](https://user-images.githubusercontent.com/44707467/155287264-88aa70fa-2247-4451-b371-c471d6e89c94.png)

这个是node_modules:
![image](https://user-images.githubusercontent.com/44707467/155287389-c7c8ff79-1d1b-42f8-88d9-d0cdecba5fd3.png)

**Comment by awmleer** [comment]
@liuyingdiandian 你的项目是 umi 的么？如果是的话，可以参考文档上的[这里](https://mobile.ant.design/zh/guide/faq#umi-%E9%A1%B9%E7%9B%AE%E5%AE%89%E8%A3%85-antd-mobile-v5-%E5%90%8E%E6%8A%A5%E9%94%99%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F)

如果不是的话，可以检查一下你项目中的 babel 配置，是否有配置 babel-plugin-import，同时，可以读一下[这篇文档](https://mobile.ant.design/zh/guide/import-on-demand)

**Comment by liuyingdiandian** [comment]
项目不是umi，仅仅是react和dva，使用的第二种方法迁移成功了，第一种没配babel
