### ISSUE TITLE
SearchBar里面的输入如何将autoCapitalize置为none？

### ISSUE THREAD

**Issue by anhuiliujun** [ant-design/ant-design-mobile#483]
SearchBar在rn之下使用的时候发现无法取消自动大写

**Comment by silentcloud** [comment]
由于TextInput 的 API 比较多，所以目前只内置了其中一部分，后期会考虑设置成比较灵活的方式

**Comment by warmhug** [comment]
特木最近没空。

@silentcloud 还是你来做吧，把 TextInput 上的 props 设置开放给用户。

**Comment by anhuiliujun** [comment]
@warmhug @silentcloud SearchBar在rn上也不能定制样式吧

**Comment by silentcloud** [comment]
@anhuiliujun 目前只能定制 theme，我稍后把 styles 做成 prop，可以自己传样式，不过 class 名还得照着来
