### ISSUE TITLE
为什么 antd 和 antd-mobile 提供的 Icon 图标不是同一套？

### ISSUE THREAD

**Issue by wuzhao** [ant-design/ant-design-mobile#4830]
### Description

如题。
目前我们需要通过 antd 和 antd-mobile 提供同一个中后台应用的两个端（PC + mobile）的应用，因为图标不匹配无法很好地完成转换～

想了解是否有计划互通，如果有预期时间吗？如果没有是出于什么考虑？

antd icon: https://ant.design/components/icon/
antd-mobile icons: https://mobile.ant.design/zh/components/icon

**Comment by awmleer** [comment]
目前还没有计划互通的，站在技术的角度上我其实蛮理解你的说的这种情况和问题，但是这需要设计规范的调整，估计短期内难以实现
