### ISSUE TITLE
Calendar 组件期待提供渲染每个date的props，renderLabel并不好用

### ISSUE THREAD

**Issue by wljing** [ant-design/ant-design-mobile#4831]
### Version of antd-mobile

5.0.0

### What is this feature about?

场景：只有固定的某些日期需要高亮时。
建议：参考 antd 的Calendar的dateFullCellRender

**Comment by awmleer** [comment]
这个我们评估一下，看看能不能放开限制，估计优先级不会很高

**Comment by awmleer** [comment]
确认了一下，Calendar 组件只能做有限的槽位开放，不然的话太难以维护了，这个 issue 我先关闭了哈，如果有很定制的需求，可以考虑自己 fork 一份 Calendar 的源代码到自己的业务仓库里
