### ISSUE TITLE
[CheckList]添加activeClassName和activeStyle方便定制选中列表项样式

### ISSUE THREAD

**Issue by caijf** [ant-design/ant-design-mobile#4833]
### Version of antd-mobile

5.1.0

### What is this feature about?

如题，readOnly和disabled都有对应的className，但是active没有

![image](https://user-images.githubusercontent.com/5070722/155451517-13b906fe-de69-4d8f-b8e0-0a5693668948.png)

**Comment by miracles1919** [comment]
@awmleer 这个需要加么

**Comment by awmleer** [comment]
@miracles1919 嗯嗯加吧～就先加个默认的 -active 的 class
