### ISSUE TITLE
NextJs 调用自己封装后的组件会报Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by hugejile** [ant-design/ant-design-mobile#4836]
### Version of antd-mobile

5.1.0

### What happened?

因为我有多个前端项目，有些通用的控件需要封装成包，给各个项目统一使用。NextJs 调用自己封装后的组件，会报 /node_modules/antd-mobile/es/components/water-mark/water-mark.css
Global CSS cannot be imported from within node_modules. 查文档发现NextJS不会编译node_module中的css，请问这个问题该怎么解决？

### Relevant log output

```shell
../../../xxx-xxx-xxx/node_modules/antd-mobile/es/components/water-mark/water-mark.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: ../../../xxx-xxx-xxx/node_modules/antd-mobile/es/components/water-mark/index.js
```

**Comment by awmleer** [comment]
你是否读过这篇文档？https://mobile.ant.design/zh/guide/ssr

**Comment by hugejile** [comment]
读过了，也配置了，ant-design是可以正确载入的，但是窝子的package里封装的component，里面有Toast或者ActionSheet等控件，就会报错，导致我无法封装一些自己的通用控件

**Comment by hugejile** [comment]
再补充一下：
纯nextjs下没有问题
但是环境是nodemon+express+nextjs，会有问题，目前我先不用express了

**Comment by awmleer** [comment]
OK 那 issue 我关闭了

**Comment by ht1131589588** [comment]
最后怎么解决的呢？
