### ISSUE TITLE
Picker组件展示错乱

### ISSUE THREAD

**Issue by lx544690189** [ant-design/ant-design-mobile#4837]
### Version of antd-mobile

5.1.0

### Operating system and its version

Android

### Sandbox to reproduce

https://codesandbox.io/s/picker-jmux21?file=/src/App.tsx

### What happened?

Picker组件设置--item-height后，并且Picker存在默认值情况下，高度计算不正确导致展示错乱

**Comment by miracles1919** [comment]
看了下是因为 `display: none` 的时候获取的 dummy item 高度为 0，所以打开的时候 如果 targetIndex = 1，wheel 就是 `transform: translateY(-34px);`

picker-view 就没这个问题了

@awmleer

**Comment by awmleer** [comment]
我来看下

**Comment by xsbest** [comment]
感觉碰到了同款问题

**Comment by awmleer** [comment]
这个问题有点难解，如果内容不渲染出来，就没办法获得 `computedStyle`，但是 `dumnyItem` 又必须是放在组件内部，不然如果用户设置的高度数是 `em` 就会出现问题

**Comment by awmleer** [comment]
看来 `--item-height` 并不应该做，或许还是作为一个组件属性比较合适？

**Comment by awmleer** [comment]
这样就可以限制用户只能传一个 px 单位的数字进来，而且还不会被业务中的 CSS 预处理影响

**Comment by awmleer** [comment]
还有一种性能不好的解法

把原来的：

```tsx
<animated.div
  style={{
    translateY: y,
  }}
>
```

改为：

```tsx
<animated.div
  style={{
    translateY: y.to(
      y => `calc(${y / itemHeight.current} * var(--item-height))`
    ),
  }}
>
```

**Comment by miracles1919** [comment]
使用 `visibility` 控制的 popup 是不是一种解法

**Comment by awmleer** [comment]
还有另外一种思路，让 `conertPx` 支持 `px` 和 `rem` 单位

**Comment by awmleer** [comment]
> 使用 `visibility` 控制的 popup 是不是一种解法

会有性能问题的

**Comment by awmleer** [comment]
@lx544690189 @xsbest 可以先给 Picker 加上 `forceRender={true}` 来临时绕过这个 bug

**Comment by awmleer** [comment]
9b2ff421 先采用这种方法修复了
