### ISSUE TITLE
nav

### ISSUE THREAD

**Issue by Freudzhu** [ant-design/ant-design-mobile#484]
问个比较新手的问题，安装配置完了ant-design-mobile，用了下nav这个组件。看了下nav这个组件的样式，手机浏览器上导航栏显示的非常宽，看了下css默认的am-navbar的height: 90px，一般我们设置成44px就差不多了。其他的组件也都显示的大一号。难道默认的组件都比较大么？这样基本的样式都要自己修改么？

**Comment by silentcloud** [comment]
设置高清方案 @Freudzhu

**Comment by jozhi** [comment]
项目 demo 貌似是跑不起来的。。

**Comment by jozhi** [comment]
项目 demo 貌似是跑不起来的。

**Comment by warmhug** [comment]
@jozhi 我现在更新下 demo
