### ISSUE TITLE
v5版本是否默认开启了按需加载

### ISSUE THREAD

**Issue by huabingtao** [ant-design/ant-design-mobile#4845]
### Version of antd-mobile

5.0.0

### Operating system and its version

iOS, Android, Others

### Browser and its version

谷歌

### What happened?

您好我想问下组件库的开发人员，

1. 如何判断出我配置按需加载起了效果？为什么会这么问是因为我用webpack-bundle-analyzer分析过配置了按需加载后和没配置打出来的包体积是一样的。
2. 你们的组件库打包后为什么没有生成一个大的js文件了？也就是这个js文件包含了所有的组件。
3. customize-cra 包下的fixBabelImports 配置是不是升级过了，我发现现在fixBabelImports函数要求传入的第一个参数是libraryName 我也看了很多网上的方式传入 "import" or "antd-mobile" 的都有所以我觉得很难知道哪个是对的😭。

下面是我的一些截图，期待您团队的回复😁
<img width="2118" alt="image" src="https://user-images.githubusercontent.com/19888505/155663732-bb65fb57-2d45-4a6a-8f74-587a4784859f.png">
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/19888505/155665236-f6fd9e88-cea5-4880-b2e1-10ffa3bfb159.png">

**Comment by bobroccoddup** [comment]
![image](https://user-images.githubusercontent.com/72988525/155670283-7148c35e-9386-45a5-9480-c44a9ad6e702.png)
https://mobile.ant.design/zh/guide/import-on-demand
先看文档哦

暴露个人信息了哦
![image](https://user-images.githubusercontent.com/72988525/155670700-f3457432-c8cd-4910-bc7d-9e5f2f1eb9ec.png)

**Comment by huabingtao** [comment]
> ![image](https://user-images.githubusercontent.com/72988525/155670283-7148c35e-9386-45a5-9480-c44a9ad6e702.png) https://mobile.ant.design/zh/guide/import-on-demand 先看文档哦
> 
> 暴露个人信息了哦 ![image](https://user-images.githubusercontent.com/72988525/155670700-f3457432-c8cd-4910-bc7d-9e5f2f1eb9ec.png)

thanks,居然看漏了这一行

**Comment by awmleer** [comment]
关于 webpack tree shaking 的概念，可以看下[这篇文档](https://webpack.js.org/guides/tree-shaking/)
应该能解答你的第 1 点疑惑

第 2 点的话，猜测你是想说 umd 版本的产物？其实是有的，在 umd 目录下

第 3 点的话，和 antd-mobile 无关，可以去问 customize-cra 的社区

issue 我先关闭了，有问题可以再 reopen

**Comment by huabingtao** [comment]
> 关于 webpack tree shaking 的概念，可以看下[这篇文档](https://webpack.js.org/guides/tree-shaking/) 应该能解答你的第 1 点疑惑
> 
> 第 2 点的话，猜测你是想说 umd 版本的产物？其实是有的，在 umd 目录下
> 
> 第 3 点的话，和 antd-mobile 无关，可以去问 customize-cra 的社区
> 
> issue 我先关闭了，有问题可以再 reopen

ok thanks
