### ISSUE TITLE
存在js重复引用的问题

### ISSUE THREAD

**Issue by gaominrn** [ant-design/ant-design-mobile#4846]
### Version of antd-mobile

v5.1.0

### What happened?

![image](https://user-images.githubusercontent.com/24311966/155671235-6f8feece-dd24-4662-886d-c63a797973be.png)

**Comment by awmleer** [comment]
看起来是 ahooks 的问题 @brickspert

**Comment by brickspert** [comment]
这里要检查的问题就是 CircularDependencyPlugin 插件，不应该去检查 node_modules 里面的文件。
