### ISSUE TITLE
ImageUploader 在真机显示问题

### ISSUE THREAD

**Issue by promiseLC** [ant-design/ant-design-mobile#4847]
### Version of antd-mobile

5.0.0

### Operating system and its version

iOS, Android

### Browser and its version

all

### What happened?

![WechatIMG18](https://user-images.githubusercontent.com/56290517/155672935-2d061aa6-b0d2-4cd7-8f7d-cf3fb9602c02.jpeg)
![Uploading WechatIMG18.jpeg…]()

真机显示不全  第二张图片就可以触发,所有真机都可以 感觉是 heigth没有生效
解决代码 

 .adm-image-img {
    min-width: 100%;
    min-height: 100%;
  }

**Comment by promiseLC** [comment]
![80c60d7899f1e6b9f3e92f141164fd44](https://user-images.githubusercontent.com/56290517/155673799-e92a0f62-db27-42af-94d0-70e7286c37c0.jpg)
抱歉,这个图片之前上传失败

**Comment by awmleer** [comment]
所以问题解决了是么？那 issue 我关闭了哈

**Comment by promiseLC** [comment]
@awmleer 抱歉,我之前看错了,这个问题没有解决,不过对我影响不大我们项目只是一个小活动无所谓的,主要看你们想否想解决,因为这个是组件问题(我觉得是这样,你们可以真机复现一下),再次抱歉一下,上面图片传的不严谨问题,打扰

**Comment by awmleer** [comment]
OK 我们后面留意一下
