### ISSUE TITLE
官方最新版体验demo中React Native部分组件展示异常

### ISSUE THREAD

**Issue by OUZICHENG** [ant-design/ant-design-mobile#485]
平台：android
手机：小米，安装的最新系统
异常描述：
1、demo的ReactNative部分中在组件列表中点击Checkbox,Radio两个选项时demo直接异常退出，重复多次，每次都一样。另外这两个组件前面的图标是不是对调了，Checkbox应该是方的，Radio是圆的才对吧。
2、Stepper 组件左侧文字显示不全，现下面有部分补遮挡

**Comment by OUZICHENG** [comment]
3、Picker左侧提示文字也有下部分补遮挡的问题

**Comment by silentcloud** [comment]
@OUZICHENG 请提供一下 android 版本，谢谢

**Comment by OUZICHENG** [comment]
![screenshot_2016-11-07-11-38-31-604_com android se](https://cloud.githubusercontent.com/assets/6308331/20045753/e4ef4354-a4de-11e6-8e3b-64a3cfe19e34.png)

**Comment by OUZICHENG** [comment]
![screenshot_2016-11-07-11-42-14-318_com android se](https://cloud.githubusercontent.com/assets/6308331/20045852/50de8cfa-a4df-11e6-9d11-fbe75af0621e.png)
直接在github扫码安装的，刚刚安装的时候有出来升级提醒，点了升级之后没再有什么提示，是静默更新还是更新失败了呢？现在显示的版本号是0.8版，是最新的吗？

**Comment by OUZICHENG** [comment]
我先卸载，重新安装下看看

**Comment by OUZICHENG** [comment]
同一台机子，重新安装之后，异常退出（闪退）情况没有了。文字底部被遮挡情况好像加重了。第一屏列表页面就有。另外，还是想提下，Checkbox,Radio两个示例是不是反过来了。下面是新安装后的截图。
![screenshot_2016-11-07-11-51-56-111_com antm](https://cloud.githubusercontent.com/assets/6308331/20046161/deeae64a-a4e1-11e6-8dbf-dc8969645ed8.png)
![screenshot_2016-11-07-11-55-29-877_com antm](https://cloud.githubusercontent.com/assets/6308331/20046168/ea0253ce-a4e1-11e6-80fe-bb13bf853ad0.png)
![screenshot_2016-11-07-11-55-39-229_com antm](https://cloud.githubusercontent.com/assets/6308331/20046172/f0c826a2-a4e1-11e6-9ac8-d72e20e18e5d.png)

**Comment by OUZICHENG** [comment]
一般情况Checkbox是方的，可多选，Radio圆的单选，对吧

**Comment by silentcloud** [comment]
@OUZICHENG 感谢反馈，文字遮挡的问题我刚在本地已经修复了，图标有无反我 check 一下

**Comment by silentcloud** [comment]
fixed in 4aa10378460096db09fd357430395d02d3f8d552;

图标的问题，我 check 过了，是 ok 的，没问题，图标是根据组件里的样式做的。

更新是静默更新，点了更新后，后台进行 bundle 下载，下次重新打开程序就是最新的内容

**Comment by OUZICHENG** [comment]
虽然重装那一会儿Radio和Checkbox示例从列表点击后闪退没有了，但是后面这几天进去还是会闪退。原因不明，有没有同样情况的同学在
