### ISSUE TITLE
希望可以开放一个像 ant-design-pro 这样开箱即用的模板

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-mobile#4851]
希望可以开放一个像 ant-design-pro 这样开箱即用的模板

**Comment by awmleer** [comment]
目前可以用这个：https://github.com/ant-design/ant-design-mobile/discussions/4699

更完善的模板 @crazylxr 正在做

**Comment by crazylxr** [comment]
> 希望可以开放一个像 ant-design-pro 这样开箱即用的模板

你期望模板有哪些功能？
