### ISSUE TITLE
Modal 弹窗希望增加左右间距大小和弹窗位置自定义，目前左右间距是固定的，弹窗位置也是居中。

### ISSUE THREAD

**Issue by xiaoliu1990** [ant-design/ant-design-mobile#4858]
### Version of antd-mobile

^5.2.1

### What is this feature about?

![lQLPDhsxXCdnHdbNAk3NAfWwZjTBTG1TLt4CIYtplYDrAA_501_589](https://user-images.githubusercontent.com/17424034/155963262-4c16ff91-07fd-479b-8d03-ce8f81bf02a2.png)

**Comment by shusiwei** [comment]
这种需求看不出来有什么意义

**Comment by awmleer** [comment]
用新出的 CenterPopup 组件，就可以解决这个 issue 里提到的问题了

**Comment by 1609960351** [comment]
新出的 CenterPopup 为什么引入失败

**Comment by zemelLeong** [comment]
> 新出的 CenterPopup 为什么引入失败

同样的问题，看了下node_modules里没有CenterPopup
![image](https://user-images.githubusercontent.com/26835087/174313115-7a2ecbb9-be51-48bc-ae9f-0fce7a5b2ee0.png)
