### ISSUE TITLE
自定义主题时，brand-primary-tap怎么不生效呢？

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design-mobile#486]
貌似 brand-primary-tap 设置没有效果啊。。。

```
// theme.js
module.exports = function () {
    return {
        "@brand-primary": '#526178', //这个是生效的
        "@brand-primary-tap": '#1284d6', // 这一行及下一行都不行
        "@primary-button-fill-tap": '#1284d6'// 
    };
};
```

我也看了 源码 自
https://github.com/ant-design/ant-design-mobile/blob/4172539f52fbd3ff7a0f4bc76c475eb01a37c0e2/components/style/themes/default.less#L115  从 `@brand-primary-tap` 继承而来的 `@primary-button-fill-tap`  然后应用的到 https://github.com/ant-design/ant-design-mobile/blob/master/components/button/style/index.less#L34

```
&-primary {
    color: @color-text-base-inverse;
    background-color: @primary-button-fill;
    border: @border-width-sm solid @primary-button-fill;
    // &:active, // uc browser not work normal
    &.@{buttonPrefixCls}-active {
      background-color: @primary-button-fill-tap; //这里了。。。 但是没有生效.
    }
  }

```

**Comment by afc163** [comment]
我在[这个例子](https://github.com/ant-design/antd-init/blob/master/boilerplates/MobileDemo/theme.js)里试了一下，三个变量都是生效的，你可以试试。

确保引入的样式是 less 而且 antd-mobile 的版本是最新的稳定版。

**Comment by xjdata** [comment]
我晕。。。。 又好了。 node_modules 删了重新装了下。

**Comment by xjdata** [comment]
谢谢。

**Comment by igo903** [comment]
一定要用atool-build么？
