### ISSUE TITLE
本地调试可以正常下拉加载触发获取列表接口，但是部署以后下拉一直显示加载中也不会触发调接口

### ISSUE THREAD

**Issue by KIngCrzy** [ant-design/ant-design-mobile#4863]
### Version of antd-mobile

^5.0.0-rc.16

### Description

本地和线上的代码完全一样 不清楚什么原因导致

**Comment by GOWxx** [comment]
线上部署的代码是在哪里打包的？有没有比对打包的服务器用的包版本和本地的包版本？

**Comment by KIngCrzy** [comment]
> 线上部署的代码是在哪里打包的？有没有比对打包的服务器用的包版本和本地的包版本？
线上打包的 对比了线上的package.json 一致

**Comment by awmleer** [comment]
- 你使用的包管理器是什么？本地和线上构建时是否是使用的相同的包管理器？
- 是否使用了 lockfile？如果使用了，lockfile 是否 commit 到仓库中了？

**Comment by awmleer** [comment]
另外再提供两个思路：

- 最好把相关的录屏（本地和线上分别的）发出来，或许能帮助大家帮你排查问题
- 线上环境看下网络请求面板，确定是完全没有触发接口的调用而不是接口报错了么？
- 把你项目中相关的代码发出来，尽可能详细一些

**Comment by KIngCrzy** [comment]
> * 你使用的包管理器是什么？本地和线上构建时是否是使用的相同的包管理器？
> * 是否使用了 lockfile？如果使用了，lockfile 是否 commit 到仓库中了？

npm，是相同的包管理器，无使用，暂时没找到原因 着急上线改用react-infinite-scroller了
