### ISSUE TITLE
Input开启clearable, 带清除按钮模式下,  输入完成, 收起键盘失去焦点,   清空按钮仍然存在

### ISSUE THREAD

**Issue by gongwlin** [ant-design/ant-design-mobile#4865]
### Version of antd-mobile

5.0.0-rc.27

### Operating system and its version

Android

### Browser and its version

安卓11, PC端

### Sandbox to reproduce

https://codesandbox.io/s/trusting-noether-vgpg1k?file=/src/App.tsx

### What happened?

**问题**:  设置clearable, 带清除按钮下,   收起键盘失去焦点,   清空按钮仍然存在

**期望**:   收起键盘失去焦点时,   隐藏清空按钮

**Comment by awmleer** [comment]
我在 iOS 下也复现出来了

**Comment by awmleer** [comment]
诶等等……这个是预期行为的

**Comment by awmleer** [comment]
和设计师确认了一下交互，我优化一下吧，失去焦点就隐藏掉

**Comment by awmleer** [comment]
c5f4d382
