### ISSUE TITLE
国际化多语言方案是否继续采用antd的方案？

### ISSUE THREAD

**Issue by szwork2013** [ant-design/ant-design-mobile#487]
国际化多语言方案是否继续采用antd的方案？即：
https://github.com/ant-design/intl-example/blob/master/docs/understanding-antd-i18n.md

**Comment by benjycui** [comment]
Web 版必然可以，RN 版我测试一下。

@jaredleechn @ChrisFan 我往 intl-example 里面增加 antd-mobile 的 Web 版和 RN 版的 demo?

**Comment by jaredleechn** [comment]
好

antd-mobile 直接加在 [现有代码里](https://github.com/ant-design/intl-example/blob/master/src/entry/index.jsx) 就可以了

RN 版可以直接在 v8 里跑起来吗？

**Comment by benjycui** [comment]
@warmhug `antd-mobile` 没有类似于 https://ant.design/components/locale-provider/ 的东西？这样组件内部的文案只能逐个配置了？

**Comment by benjycui** [comment]
React Native 暂时无法使用 `react-intl`，trace: https://github.com/yahoo/react-intl/issues/119

**Comment by warmhug** [comment]
没有 locale-provider ，需要的话你可以加下 @benjycui

**Comment by silentcloud** [comment]
搜了哈，貌似目前 RN 用的比较多的就 [react-native-i18n](https://github.com/AlexanderZaytsev/react-native-i18n)

**Comment by benjycui** [comment]
> React Native 暂时无法使用 react-intl，trace: yahoo/react-intl#119

其实我觉得能统一是最好的。。

毕竟 react-intl 已经有支持的计划了。

**Comment by bang88** [comment]
RN也可以使用`react-intl`配置一下`Intl`就可以了

**Comment by benjycui** [comment]
react-intl 已支持 RN https://github.com/yahoo/react-intl/pull/739

待发布即可用。

**Comment by liubin1023** [comment]
@silentcloud @warmhug @bccsafe 

ReactNative 国际化在1.0版本中会添加吗
1.0正式版几号发布

**Comment by warmhug** [comment]
@liubin1023 国际化支持没在 1.0 中，在之后的版本加入。 1.0 本周五发布

**Comment by liubin1023** [comment]
@warmhug 那国际化有计划没，预计在几号，那个版本上面增加

**Comment by paranoidjk** [comment]
@liubin1023 @szwork2013 
- RN组件内置文案的国际化已经完成，将在本周的1.0.2release，文档和方案同web一致，参考https://mobile.ant.design/components/locale-provider
- 业务代码的国际化仍然建议采用antd的方案 https://github.com/ant-design/intl-example/blob/master/docs/understanding-antd-i18n.md
