### ISSUE TITLE
按需加载antd-mobile样式，样式引入失败

### ISSUE THREAD

**Issue by AliyaLiu** [ant-design/ant-design-mobile#4870]
### Version of antd-mobile

5.2.1

### Description

在config-overrides.js中配置如下
```
const { override, fixBabelImports } = require('customize-cra');
module.exports = {
  webpack: override(
    fixBabelImports('import', {
      libraryName: 'antd-mobile',
      libraryDirectory: 'es/components',
      style: true, // change importing css to less
    }),
)}
```
启动项目提示：
Cannot find module 'antd-mobile/es/components/button/style'
<img width="949" alt="image" src="https://user-images.githubusercontent.com/39554660/156352896-e4007aba-f447-494e-bc73-a58cb7214f7b.png">

找到node_modules中的antd-mobile如图
<img width="316" alt="image" src="https://user-images.githubusercontent.com/39554660/156352994-3f0246e5-8218-4bed-9c0d-4c3edc270574.png">

~~目前看到是组件下无less文件，且没有style这一级，请问这个要怎么处理~

**Comment by awmleer** [comment]
请读文档：https://mobile.ant.design/zh/guide/import-on-demand
