### ISSUE TITLE
CascaderView 能否添加onloadData 实现动态数据的加载

### ISSUE THREAD

**Issue by gitpayson** [ant-design/ant-design-mobile#4874]
### Version of antd-mobile

5.0.0

**Comment by awmleer** [comment]
没理解你想要实现什么功能？具体描述一下吧

**Comment by gitpayson** [comment]
在Ant-design 上的Cascader组件有一个onloadData属性可以实现动态加载数据


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-mobile] CascaderView 能否添加onloadData 实现动态数据的加载 (Issue #4874)





 
没理解你想要实现什么功能？具体描述一下吧
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gitpayson** [comment]
在Ant-design 上的Cascader组件有一个onloadData&nbsp; Api&nbsp; 可以实现动态加载数据
但是在Mobile 上的CascaderView 组件没有这个API&nbsp;
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ant-design/ant-design-mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-mobile] CascaderView 能否添加onloadData 实现动态数据的加载 (Issue #4874)





 
没理解你想要实现什么功能？具体描述一下吧
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gitpayson** [comment]
在Ant-design 上的Cascader组件有一个onloadData&nbsp; Api&nbsp; 可以实现动态加载数据
但是在Mobile 上的CascaderView 组件没有这个API 


现在我要用这个 mobile 的CascaderView组件 实现数据的动态加载，没有想到很好的方案，您看是否可以提供一个类似于Ant-design 上的Cascader组件的onloadData&nbsp; Api 去实现数据的动态加载
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ant-design/ant-design-mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-mobile] CascaderView 能否添加onloadData 实现动态数据的加载 (Issue #4874)





 
没理解你想要实现什么功能？具体描述一下吧
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by awmleer** [comment]
loadData 目前不会做的，关于动态加载的用法，可以参考 Cascader 的第二个 demo：

![image](https://user-images.githubusercontent.com/16526078/156694052-784c8284-31ff-47c1-a067-0453c8106be6.png)

**Comment by ratelgogo** [comment]
前端省市区的选择都是静态数据吗？4级的话也不少了，动态加载在这种场景还是有必要的吧

**Comment by awmleer** [comment]
动态加载是支持的，只不过不是通过 `loadData` 这种写法来实现的，文档中有个 demo 来展示如何实现动态加载数据，上面已经回复了
