### ISSUE TITLE
Swiper引入未生效，DOM结构没有出来

### ISSUE THREAD

**Issue by xingqiangqiang** [ant-design/ant-design-mobile#4876]
### Version of antd-mobile

5.2.1

### Operating system and its version

iOS

### What happened?

<img width="721" alt="image" src="https://user-images.githubusercontent.com/73377464/156694888-02c05b62-07c3-4891-bdd4-6dcfe081768f.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/73377464/156694932-d8dd0aaf-92c7-4b04-8134-005802e4685d.png">
<img width="667" alt="image" src="https://user-images.githubusercontent.com/73377464/156694966-043ed2c8-6057-49ed-b63a-64a77298fcfd.png">
nothing have!!!

**Comment by zzzgydi** [comment]
给个可以复现的demo会好排查一点，单看图一的代码，感觉没啥问题，看图三的节点，你是套在Tabs里使用的吧，还是给个demo好一点

**Comment by xingqiangqiang** [comment]
> 给个可以复现的demo会好排查一点，单看图一的代码，感觉没啥问题，看图三的节点，你是套在Tabs里使用的吧，还是给个demo好一点

[git@github.com:xingqiangqiang/test.git](https://github.com/xingqiangqiang/test)
测试用例，使用cra创建的应用并引入antd-mobile使用swiper组件是可以出来，在项目中不能出现，我试着将例子放在其他各个位置最终都没有出现swiper的DOM结构，我排查一下

**Comment by Jiangluowen623** [comment]
![image](https://user-images.githubusercontent.com/11747853/156978129-cbac2a73-441b-42e0-9ec9-d5c95b555277.png)
我这边也是  ， 用的官方demo  一直提示Swiper组件的子节点必须是Swiper.Item

**Comment by Jiangluowen623** [comment]
> ![image](https://user-images.githubusercontent.com/11747853/156978129-cbac2a73-441b-42e0-9ec9-d5c95b555277.png) 我这边也是 ， 用的官方demo 一直提示Swiper组件的子节点必须是Swiper.Item

原因是 用到react-hot-loader 组件被包装了一层 Proxy Component ，有什么解决办法么？

**Comment by zzzgydi** [comment]
Swiper的子组件必须得是Swiper.Item，只能这样了

```
<Swiper>
  <Swiper.Item>
    <ProxyComp />
  </Swiper.Item>
</Swiper>
```

**Comment by awmleer** [comment]
我知道了，应该就是 react-hot-loader 导致的，之前在群里也有其他同学反馈这个问题，后来排查出现是 react-hot-loader 的锅，建议去掉 react-hot-loader，或者替换成 React Fast Refresh

react-hot-loader 项目本身的 README 中已经不建议大家使用了：
https://github.com/gaearon/react-hot-loader
<img width="858" alt="image" src="https://user-images.githubusercontent.com/16526078/157014010-d60340dc-c803-4bd1-8b7e-2e390b4e82db.png">
