### ISSUE TITLE
Dialog 内使用 DatePicker 无法弹出 日期选择框

### ISSUE THREAD

**Issue by JuSanZhi** [ant-design/ant-design-mobile#4877]
### Version of antd-mobile

^5.3.0

### Operating system and its version

Others

### Sandbox to reproduce

https://codesandbox.io/s/icy-frog-8y63zx?file=/src/App.tsx:574-587

**Comment by shiyiya** [comment]
https://codesandbox.io/s/late-paper-87y61d?file=/src/App.tsx

**Comment by awmleer** [comment]
感谢～ @shiyiya 

另附一下文档上的说明：

![image](https://user-images.githubusercontent.com/16526078/156961139-229d6f94-f9f2-49d5-b4a5-d8b34bd59798.png)

用之前还是要好好地完整地读一下文档的 @JuSanZhi
