### ISSUE TITLE
listView 如何滚动到具体的位置

### ISSUE THREAD

**Issue by dotaeye** [ant-design/ant-design-mobile#488]
#### 本地环境

- antd-mobile 版本：0.94
- 操作系统及其版本：Mac
- 浏览器及其版本：Chrome

#### 你做了什么？

引入 antd-mobile 的 ListView, 使用了RefeshControl,默认启用了zscroller, 然后定义一个事件，要过滤掉原有的数据，只显示其中一部分的数据， 在过滤之前如果滚动了一定的距离，过滤完之后listview 还保持了原有的滚动位置

#### 你期待的结果是：
是否有API让 listView 重设 滚动的位置？
或者能否在ListView 直接暴露出 rmc-list-view 的 引用

我当前的解决方案，
在listView 增加ref的引用
```
export default class ListView extends React.Component<tsPropsType, any> {
  static defaultProps = {
    prefixCls: 'am-list-view',
    listPrefixCls: 'am-list',
  };
  static DataSource = MListView.DataSource;
  static IndexedList = IndexedList;
  render() {
    const { restProps, extraProps } = handleProps(this.props, false);
    let { useZscroller, refreshControl } = this.props;
    if (refreshControl) {
      useZscroller = true;
    }
    return <MListView {...restProps} {...extraProps} useZscroller={useZscroller} ref="listview" />;
  }
}
```
其中 ref='listview' 是我新增的，因为属性中的 ref 不会被传递到子组件。

代码中调用

```
 this.refs.listview.refs.listview.refs.listviewscroll.domScroller.scroller.scrollTo(0, 0);
```
不知是否有更好的方式？

**Comment by warmhug** [comment]
这样挺好的，我在组件里把 ref 加下

**Comment by warmhug** [comment]
可以在现有版本里，试试用 `React.cloneElement`方法把自己的 ref 传进去。新版本周五发

**Comment by dotaeye** [comment]
反馈的如此之快,谢谢。
``` React.cloneElement ``` 这个如何传？顶级的ListView 好像不太好clone

**Comment by warmhug** [comment]
组件套组件，没什么顶级之分吧。试试看

**Comment by dead-horse** [comment]
这个是否能够提供一个 API，否则通过 refs 链过去很容易被一些小修改导致不兼容？

**Comment by warmhug** [comment]
已支持在组件实例上进行调用 scrollTo 方法，例如 this.refs.your_listview_name.scrollTo(0, 0) ，更新 node_modules 即可
