### ISSUE TITLE
期望　CascaderView组件在选中最后一级的情况下，返回一个标识给我，告诉我已经选择完毕。

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#4881]
### Version of antd-mobile

eg 5.4.0

### What is this feature about?

期望 CascaderView组件在选中最后一级的情况下，返回一个标识给我，告诉我已经选择完毕。
![image](https://user-images.githubusercontent.com/12706830/156978118-d7e9f25a-f955-4128-a93b-be4e614bac1f.png)

这样的组件我用CascaderView配合Popup组件，在用户选择完后，我无法感知是否选择完，如果选择完毕用户点确实我将关允许用户关闭popup层。

Cascader组件虽然和我截图类似，但我也无法感知用户是否选择到最后一个了，期望在CascaderView　Cascader组件能返回一个值感知，数据已经被选择到最后一个了。

**Comment by awmleer** [comment]
CascaderView 和 Cascader 的 `onChange` 事件中，现在第二个参数会返回一个 `extend` 对象，用来暴露一些额外信息，不过现在的 `extend` 对象中只有 `items` 数据

现在在 `extend` 中再增加一个 `isLeaf` 属性，就可以了，当选择到了最后一级时，`isLeaf` 为 `true`，否则为 `false`

**Comment by li-yu-tfs** [comment]
> CascaderView 和 Cascader 的 `onChange` 事件中，现在第二个参数会返回一个 `extend` 对象，用来暴露一些额外信息，不过现在的 `extend` 对象中只有 `items` 数据
> 
> 现在在 `extend` 中再增加一个 `isLeaf` 属性，就可以了，当选择到了最后一级时，`isLeaf` 为 `true`，否则为 `false`

现在不是只有onSelect事件了吗？ 而且onSelect事件，第二个参数我也无法获取到，只能获取到当前选中的value
