### ISSUE TITLE
nextjs12.1.0 引入 Button报错

### ISSUE THREAD

**Issue by wulisensen** [ant-design/ant-design-mobile#4882]
### Version of antd-mobile

5.4.5

### Operating system and its version

Others

### Browser and its version

chrome

### Sandbox to reproduce

https://github.com/wulisensen/test-next.git

### What happened?

./node_modules/antd-mobile/es/components/action-sheet/action-sheet.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/antd-mobile/es/components/action-sheet/index.js

**Comment by zzzgydi** [comment]
https://mobile.ant.design/zh/guide/ssr
