### ISSUE TITLE
Calendar: add date select UI like ant-design

### ISSUE THREAD

**Issue by shikelong** [ant-design/ant-design-mobile#4884]
### Version of antd-mobile

5.0.0-beta.21

### What is this feature about?

Ant Mobile's Calendar Component only supports switch month view by clicking the `pre` or `next` buttons.
![image](https://user-images.githubusercontent.com/4499997/157163880-f985e70f-e41b-47d6-b219-93a6c732b57b.png)

Ant Design's Calendar support quickly date toggle UI like this:

![image](https://user-images.githubusercontent.com/4499997/157163958-c7f7dfd6-8501-4586-8349-006726a9dfc1.png)

I know Ant Mobile provider ref for quickly jump. But providing built-in UI is a more intuitive way.

**Comment by awmleer** [comment]
目前的设计规范中是没有这种交互的，我理解下来其实你本质上是觉得现在 Calendar 跳转年月太繁琐了？

**Comment by shikelong** [comment]
> 目前的设计规范中是没有这种交互的，我理解下来其实你本质上是觉得现在 Calendar 跳转年月太繁琐了？

是的。比如说需要往前跳 10 年，连续点击 10 次太繁琐了。

**Comment by awmleer** [comment]
看起来这更像是一个设计上的问题，后面我和设计师反馈一下，目前的设计规范中是只能这样点按钮跳转的
