### ISSUE TITLE
关于Drawer Android无法显示的问题

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#489]
#### 本地环境

- antd-mobile 版本：0.9.4
- 操作系统及其版本：mac
- 浏览器及其版本：android 原生浏览器、QQ内置浏览器、微信内置浏览器

#### 你做了什么？

使用Drawer组件

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：
android系统4.4.4

在android内置浏览器、QQ内置浏览器、微信内置浏览器都只能显示一片空白
不过在android上面安装chrome是可以正常显示的

**Comment by warmhug** [comment]
有些浏览器不支持 flex ，先查下相关代码？

**Comment by warmhug** [comment]
网站用的 drawer ，在微信内置浏览器等 Android 浏览器里，没问题。

**Comment by liubin1023** [comment]
@warmhug  网站预览的网址我在android上面试过，可以的， 但是我参照官网提供的例子复制，发现只有android内置浏览器、微信、qq访问有异常，其他都正常

**Comment by warmhug** [comment]
关联 issue #478 #408 #226 

细节上注意对照下，实在觉得有问题、请贴代码、修改并 Fork https://codepen.io/warmhug/pen/bwRPvx

**Comment by liubin1023** [comment]
@warmhug 找到问题了`...Array(20).keys()` 换掉就好了

**Comment by warmhug** [comment]
Array(20).keys() 这个在有些特别老的浏览器里需要 polyfill 。找问题要有针对性，这里有问题就是没渲染出来，跟样式没什么关系。
