### ISSUE TITLE
希望Picker能够像DatePicker一样提供一个renderLabel方法供自己渲染一些特殊样式

### ISSUE THREAD

**Issue by yochor** [ant-design/ant-design-mobile#4891]
### Version of antd-mobile

5.4.0

### What is this feature about?

如题，Picker目前没有提供renderLabel方法，只能按照默认的label样子展示，如果想给某条option增加一些额外展示样式的时候，实现起来有些麻烦，如果能提供一个renderLabel方法就会方便很多

**Comment by awmleer** [comment]
求各位社区朋友们一起帮忙评估一下，如果加上 `renderLabel` 之后，会不会存在什么意外的副作用

**Comment by miracles1919** [comment]
如果给 Picker 加上 renderLabel， type 大概是这样  `renderLabel?: (label, extend) => ReactNode`

DatePicker 目前的 renderLabel 是 `renderLabel?: (type: Precision, data: number) => ReactNode`，所以这里可能有个 break change

**Comment by awmleer** [comment]
应该只是影响 Picker 和 CascadePicker……？DatePicker 的 `renderLabel` 保持不变

**Comment by yochor** [comment]
options=[[{label: '北京', value: 'bj', hot: true}]];
两种思路，一种是提供rendLabel，
renderLabel?: (label, data) => ReactNode
一种是增加一个pre或者extend属性支持在label的前边或者后边增加额外渲染的方法
extend=(data)=>ReactNode
