### ISSUE TITLE
幽灵包和多余包

### ISSUE THREAD

**Issue by komagic** [ant-design/ant-design-mobile#4893]
### Description

master 分支：
1. test中的 ’axe-core‘不在package.json 声明中，是不是幽灵包了？

2. @types/resize-observer-browser 和 use-async-memo 声明在package 中，但是似乎没有使用，是否是冗余包

**Comment by awmleer** [comment]
1. use-async-memo 现在已经不需要了，移除了 d21c298dd
2. @types/resize-observer-browser 其实是有用的，是给 window.ResizeObserver 手动加 ts 类型的
3. axe-core 这个看起来是 jest-axe 的内部依赖，不过 testing.tsx 中使用到了它的类型定义，额外在 package.json 装的话感觉有点多余了，就先保持现状吧
