### ISSUE TITLE
Modal.clear doesn't close all modal in async function

### ISSUE THREAD

**Issue by venmax** [ant-design/ant-design-mobile#4896]
### Version of antd-mobile

v5.4.0

### Operating system and its version

iOS

### Sandbox to reproduce

https://codesandbox.io/s/antd-mobile-modal-clear-udve6s?file=/src/App.tsx

### What happened?

when trigger "clear and show" in async function severval times, not all previous modal closed.

```js
    setTimeout(() => {
      Modal.clear();
      Modal.alert({
        content: "abc",
        confirmText: "confirm"
      });
    }, 10);
    setTimeout(() => {
      Modal.clear();
      Modal.alert({
        content: "abc",
        confirmText: "confirm"
      });
    }, 10);
```

In addition, antd(4.19.1) `Modal.destroyAll` works fine.
https://codesandbox.io/s/antd-modal-destroyall-4bcvur

**Comment by miracles1919** [comment]
to be precisem, the problem is that the close is too fast

```
Modal.alert({
  // ...
})
Modal.clear();  // not work
```

---

问题在这里，执行 close 的时候，ref.current 是 null
```
function show() {
  // ...
  const ref = createRef<ModalShowRef>()
  const unmount = renderToBody(<Wrapper ref={ref} />)
  const close = () => {
    ref.current?.close()
  }
}

```

**Comment by miracles1919** [comment]
to be precisem, the problem is that the close is too fast
```
Modal.alert({
  // ...
})
Modal.clear();  // not work
```
