### ISSUE TITLE
CascadePicker 组件可否支持在renderLabel中获取当前的所有选项

### ISSUE THREAD

**Issue by xiaolizi9** [ant-design/ant-design-mobile#4899]
### What is this feature about?

<img width="411" alt="image" src="https://user-images.githubusercontent.com/46665565/157583801-c09a489a-33aa-4976-9e72-cb83c248abfc.png">
比如想在当前日期后面加周几，在renderLabel拿取不到当前选择的所有选项值，只能获取到当前的type值

**Comment by xiaolizi9** [comment]
因为要拿到当前picker选择的所有值，才能调用getDay方法获取当前周几，但是在renderLabel的回调里是拿不到的

**Comment by 1247748612** [comment]
看起来像是要在每日都加上星期几，暴露出当前选择的picker的value也没用

我觉得这种情况应该是自己先便利一遍添加一个week属性 renderLabel展示day(week
)，应该能实现你的需求

**Comment by awmleer** [comment]
如果要完全可定制化，可以基于 Picker 的 `columns` 函数来实现

如果简单粗暴一点的话，可以按照楼上 @1247748612 所说的这种方案

renderLabel 暂时还是先不改了吧

**Comment by xiaolizi9** [comment]
> 看起来像是要在每日都加上星期几，暴露出当前选择的picker的value也没用
> 
> 我觉得这种情况应该是自己先便利一遍添加一个week属性 renderLabel展示day(week )，应该能实现你的需求

这是日期，不是自己的column，日期怎样遍历

**Comment by 1247748612** [comment]
> 这是日期，不是自己的column，日期怎样遍历

我看你说的是CascadePicker不是自己传otpions吗？

如果是DatePicker的话renderLabel好像确实要支持的更全面些

**Comment by xiaolizi9** [comment]
> > 这是日期，不是自己的column，日期怎样遍历
> 
> 我看你说的是CascadePicker不是自己传otpions吗？
> 
> 如果是DatePicker的话renderLabel好像确实要支持的更全面些

这个是日期级联组件，不是我传的column生成的日期

**Comment by 1247748612** [comment]
> 这个是日期级联组件，不是我传的column生成的日期

了解了

> CascaderPicker 和 DatePicker 是两个不同的组件，CascaderPicker是自己传options去渲染选项，而DatePicker是内部自动生成的选项。按照你的标题说的是CascaderPicker所以我的解释应该没错。但你现在用的是DatePicker。

**Comment by 1247748612** [comment]
@awmleer 考虑 reopen吗，外部实现不了

**Comment by awmleer** [comment]
哈？我绕晕了， @xiaolizi9 你到底用的是 DatePicker 还是 CascadePicker 啊？

**Comment by awmleer** [comment]
要不写个 codesandbox 吧，我们直接看看你现在的实现逻辑：
https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx
