### ISSUE TITLE
import { TextareaItem } from 'antd-mobile' 异常

### ISSUE THREAD

**Issue by Aaaaaashu** [ant-design/ant-design-mobile#49]
#### 本地环境

- antd-mobile 版本： "^0.7.2"
- 操作系统及其版本：OSX 10.11.5
- react native 版本："^0.30.0"

#### 你做了什么？
import { TextareaItem } from 'antd-mobile'，同时已安装 babel-plugin-antd ，并配置 .babelrc : 

```js
{
  "plugins": [
    ["antd", {
      style: 'css',  // 'less',
      libraryName: 'antd-mobile',
    }]
  ]
}
```

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

![Screen Shot 2016-08-06 at 18.27.38.png](http://upload-images.jianshu.io/upload_images/8133-0bc310fc54309095.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by silentcloud** [comment]
你是要跑 react-native 项目还是 web 项目？

**Comment by Aaaaaashu** [comment]
@silentcloud react native  项目。

**Comment by silentcloud** [comment]
@Aaaaaashu 包针对 rn 缺少了 lib/index.js，目前暂时可以先这样用： 
```
import TextareaItem from 'antd-mobile/lib/textarea-item';
```

后面发个新版本修复  import { xx } 这种形式

**Comment by Aaaaaashu** [comment]
@silentcloud 了解，期待你们的更新。

**Comment by yiminghe** [comment]
看 readme ，使用 babel-plugin-antd

**Comment by Aaaaaashu** [comment]
@yiminghe 我已经按 README 上说的，安装 babel-plugin-antd，并配置对应的 .babelrc 。
依然报错，这在 issue 中已经说明。

按 @silentcloud 的方式使用 button 这样的组件是没问题，但使用 
```
import TextareaItem from 'antd-mobile/lib/textarea-item';
```
会出现 Unable to resolve module ./images/error.png  这样的错误提示。

**Comment by silentcloud** [comment]
@yiminghe rn 不走 webpack 的，配 plugin-antd 没啥用的

**Comment by yiminghe** [comment]
和 webpack 没关系的，是 babel-plugin-antd

**Comment by liqi07** [comment]
Unable to resolve module ./images/error.png 应该是组件内部逻辑图片找不到

https://github.com/ant-design/ant-design-mobile/commit/23daac47c06e2dc4c17a94976dad20a399f48c52 这个commit里input-item也一起做了更改，应该有同样问题 麻烦@pingan1927 看看

**Comment by yiminghe** [comment]
https://github.com/ant-design/ant-design-mobile/issues/56
