### ISSUE TITLE
使用 babel-plugin-import 按需加载的样式和压缩过的样式 给定的像素单位不一样

### ISSUE THREAD

**Issue by arno-react** [ant-design/ant-design-mobile#490]
#### 本地环境

- antd-mobile 版本：0.9.6
- 操作系统及其版本：windows7
- 浏览器及其版本： chrome 54.0.2840.71 m

#### 你做了什么？

 引入 antd-mobile 的 NavBar 

#### 你期待的结果是：

 像官网一样正常显示 

#### 实际上的结果：

样式已给定了像素单位为px  和压缩过的样式不一样 rem
查看原代码
压缩过的样式
.am-navbar-left {
  margin-left: 0.3rem;
  font-size: 0.32rem;
}
按需加载的样式
.am-navbar-left {
  margin-left: 30px;
  font-size: 32px;
}

**Comment by warmhug** [comment]
https://mobile.ant.design/docs/react/introduce#使用

请仔细阅读下文档，谢谢。

**Comment by ImJoeHs** [comment]
使用#

import { Button } from 'antd-mobile';

ReactDOM.render(<Button>按钮</Button>, mountNode);
无需单独引入样式，使用 babel-plugin-import 按需加载。
{
  "plugins": [
    ["import", {
      style: 'css',  // 'less',
      libraryName: 'antd-mobile',
    }]
  ]
}
更多常见问题（高清方案设置、环境配置等），请查看 wiki pages

@warmhug 冒昧说一声，建议稍微更新下文档，上面那个‘高清方案设置’的表述有些模糊，初次看以为是额外选项直接略过了，实际上这个应该是直接写在首页的必备配置吧

**Comment by warmhug** [comment]
@ImJoeHs 谢谢建议，稍后会更新下
