### ISSUE TITLE
FloatingBubble　希望增加两个参数，一个背景色，一个禁止拖动参数

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#4900]
### Version of antd-mobile

eg 5.4.0

### What is this feature about?

1.增加一个自定义背景色，如果为false的清况下禁止背景色。如果为16进制字符串的时候为自定义的背景色。
<img width="390" alt="image" src="https://user-images.githubusercontent.com/12706830/157601618-41bb528c-878c-4300-b7fb-6911e73b2cb2.png">
2.增加一个参数可禁止x y轴拖动。单纯的就是一个浮动按钮。

**Comment by awmleer** [comment]
1. 可以加一个 `--background` 的 CSS 变量
2. 可以加个 `draggable` 属性（不过不知道意义大不大，毕竟如果不需要拖动的话，那其实自己搞一个 `position: fixed` 的元素就行了）
