### ISSUE TITLE
Badge content 传入数字 0 展示徽标

### ISSUE THREAD

**Issue by a145789** [ant-design/ant-design-mobile#4902]
### Version of antd-mobile

5.4.0

### What is this feature about?

[这里](https://github.com/ant-design/ant-design-mobile/blob/36bb79177175762dd66cdbf93821d0c47d128852/src/components/badge/badge.tsx#L27) 会把数字 0 也给过滤掉，数字 0 应该也展示出来，需不需要展示可以由外层使用者控制

**Comment by yaogengzhu** [comment]
我修改下，确实是一个bug！
