### ISSUE TITLE
InfiniteScroll、List支持虚拟滚动

### ISSUE THREAD

**Issue by NexxLuo** [ant-design/ant-design-mobile#4903]
### Version of antd-mobile

5.5.0

### What is this feature about?

移动端列表数据量超过300条时，Android浏览器滚动会比较卡。建议列表相关组件支持虚拟滚动

**Comment by awmleer** [comment]
虚拟滚动 antd-mobile 本身不会支持的，但是可以我们在文档上补一个 List + react-virtualized 的 demo

**Comment by awmleer** [comment]
文档已加

**Comment by gongwlin** [comment]
看了文档的内容,   List不支持翻页,  而业务场景更多是长列表支持翻页,  即无限滚动与虚拟滚动的结合,  在满足功能的同时,  也有最佳的性能

**Comment by awmleer** [comment]
那后面再补一个 InfiniteScroll + List + react-virtualize 的例子好了

**Comment by miracles1919** [comment]
安排
