### ISSUE TITLE
纵向 divider 或者 Space 支持自定义的分隔符

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design-mobile#4915]
### Version of antd-mobile

5.6.0

### What is this feature about?
![image](https://user-images.githubusercontent.com/11746742/158014854-12b4b0a2-28ff-4ac1-bfce-bf16b2439acd.png)

编写页面的时候发现这个需求在登录页面很常见，尝试的查找了 mobile5 的组件，发现没有找到相关的组件。
和群友讨论之后，觉得应该提供纵向 divider 或者 Space 支持自定义的分隔符。

**Comment by awmleer** [comment]
设计规范里没有这块，所以暂时还先不做了～业务项目中自己实现好了

**Comment by xiaohuoni** [comment]
离谱。
