### ISSUE TITLE
日历组件不受控

### ISSUE THREAD

**Issue by hellohejinyu** [ant-design/ant-design-mobile#4916]
### Version of antd-mobile

5.6.0

### Operating system and its version

Others

### Browser and its version

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

### What happened?

<img width="552" alt="image" src="https://user-images.githubusercontent.com/8766034/158053293-5084a943-6b8c-4e18-a885-6b997d7b1c28.png">

`value` 提供一个固定的值，受控模式的话，理论上这个日历组件就被锁死在这个选择上了，除非 `onChange` 去改变 `value`。

![image](https://user-images.githubusercontent.com/8766034/158053348-0f3289f9-9cc9-4ac6-a605-1ecdca3f2d9b.png)

但是实际上日历组件仍然可以随便选择日期，没有受控。

**Comment by miracles1919** [comment]
发现 `value` `defaultValue` `onChange` 的类型不太好处理...

**Comment by awmleer** [comment]
2f6a928d 已修复
