### ISSUE TITLE
Cascader选择省市区

### ISSUE THREAD

**Issue by uithen** [ant-design/ant-design-mobile#4917]
### Version of antd-mobile

5.6.0

### Description

项目中使用Cascader实现省市区级联选择，提前给options设置了children属性，但只有第一级可以正常展示出来，点击第一级动态渲染下一级的时候并不能实现数据渲染出来。想问下是我写法出问题了吗？
ps：看官网上的demo，里面有个sleep函数，按理说应该只是个模拟异步延迟加载的函数，并不会影响功能，但注释掉了，官网下载的示例就无法正常跑起来了，这个函数是做什么的呢？

**Comment by uithen** [comment]
相关代码：
```javascript
  const onSelect = async (val, valExtend) => {
    // 首次获取省份列表
    getProvinces()
    // 保存当前选择的省或市（只须做到二级）
    const realVal = 
      (val.length) 
        && val.length === 1
        ? val[0] 
        : val[1]
    // 根据选择到的省或市从后台数据检索出对应的id
    const code = filterCode(selectedAddr, realVal)
    // 根据拿到的id请求对应市
    const cityRes = await reqArea(code)
    // 拿到城市列表
    const cityList = transformData(cityRes.data)
    console.log('cityList', cityList)
    // 将城市列表追加到对应省份的children里
    const provinceList = [...selectedAddr]
    const currentProvince = provinceList.find(item => item.code === code)
    currentProvince.children = cityList
    setSelectedAddr(prev => [...prev, currentProvince.children])
    console.log('selectedAddr', selectedAddr)
  }
```
是我代码写的有问题吗？麻烦帮忙看看，卡这里两天了。。。

**Comment by uithen** [comment]
[效果](https://github.com/uithen/blog/blob/master/charts/11.png)
[相关代码](https://github.com/uithen/blog/blob/master/charts/2222.png)

**Comment by xiaoyao96** [comment]
尝试给个复现demo吧~
https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json

**Comment by uithen** [comment]
@xiaoyao96 https://codesandbox.io/s/purple-sun-5uifrg?file=/src/App.jsx 已传，感谢指正

**Comment by uithen** [comment]
@xiaoyao96 https://codesandbox.io/s/purple-sun-5uifrg?file=/src/App.jsx 已传，感谢指正

**Comment by awmleer** [comment]
提供一个完整的复现 demo 吧
