### ISSUE TITLE
[Grid] wrapper没有撑到100%

### ISSUE THREAD

**Issue by zhaoyao91** [ant-design/ant-design-mobile#492]
```
  return <Grid data={files} columnNum={3} renderItem={(item, index)=>(
    <div>
      <img src={Helper.getThumbUrl(item)}/>
      <p>{item.name}</p>
    </div>
  )}/>
```
![1](https://cloud.githubusercontent.com/assets/3808838/20086033/39438202-a5a8-11e6-94b1-063a5f5d4a9a.png)
![2](https://cloud.githubusercontent.com/assets/3808838/20086034/39452850-a5a8-11e6-822c-e12b7301a217.png)

**Comment by warmhug** [comment]
设置`columnNum={1}`，再不行自己覆盖样式

**Comment by zhaoyao91** [comment]
不是……不关columnNum的事，你注意看我截图，不是column没撑满，是row和column中间那层wrapper没撑满。按理它应该撑满row的宽度是吧。

**Comment by warmhug** [comment]
不懂你的意思，先确认 demo 有没你说的问题。尝试自己排查下你自己业务代码哪里的问题
