### ISSUE TITLE
[Input]在Form表单中，点击列表项内间距也要触发 Input 聚焦

### ISSUE THREAD

**Issue by caijf** [ant-design/ant-design-mobile#4920]
### Version of antd-mobile

5.5.0

### What is this feature about?

![image](https://user-images.githubusercontent.com/5070722/158097019-03f97749-6718-49ea-8fda-329eea1ca691.png)

Form表单水平或垂直布局，Input 在列表项中点击边缘不会触发聚焦，希望能支持下！

**Comment by awmleer** [comment]
图中的绿色已经是外层容器的 padding 了，很难实现你说的这种效果，这个近期内不会支持的，issue 我关闭了哈

**Comment by caijf** [comment]
@awmleer 

那可以加个 clickable 或 自定义嵌套标签 吗？有些配置了 arrow 或 onClick 但是又不要 a 标签嵌套

**Comment by awmleer** [comment]
@caijf get 那的确可以把 List.Item 的 `clickable` 属性暴露出来，这样应该你就可以自己处理这块的逻辑了？

**Comment by caijf** [comment]
如果支持 clickable 也就不需要处理边缘焦点问题了。

因为一些特殊场景，给Form.Item绑定了onClick，但又不要有a标签的点按背景。（如果有点按背景容易误以为触发了焦点）

**Comment by awmleer** [comment]
嗯嗯那我了解了，我加一下 `clickable` 属性

**Comment by caijf** [comment]
谢谢！

**Comment by awmleer** [comment]
212d2c75
