### ISSUE TITLE
[CascadePicker] 首次加载展示弹窗直接按确定 onConfirm 触发的回调函数里第二个参数 extend 值不正确

### ISSUE THREAD

**Issue by GOWxx** [ant-design/ant-design-mobile#4924]
### Version of antd-mobile

v5.6.0

### Browser and its version

win10 chrome V99 模拟移动端设备

### Sandbox to reproduce

https://codesandbox.io/s/affectionate-snow-dwfhn4?file=/src/App.tsx

### What happened?

复现步骤：

点击`选择`按钮，展示弹窗后直接按确定，可以看到`onConfirm`的回调函数里，`extend` 的值里第二个数组元素是null。
第二次展示弹窗后，按确定按钮，`onConfirm`的值是正确的。

期望：
首次展示弹窗按确定按钮就可以返回正确的值。

![image](https://user-images.githubusercontent.com/12870715/158296809-deea8888-e52c-4126-95fb-d2c6dc820c06.png)

**Comment by awmleer** [comment]
通过 2e654ce1 和 0293ee9c 解决了
