### ISSUE TITLE
Stepper组件在输入框和加减按钮之间切换输入时不能保证同步

### ISSUE THREAD

**Issue by mhcgrq** [ant-design/ant-design-mobile#493]
#### 本地环境

- antd-mobile 版本：0.9.6
- 操作系统及其版本：macOS 10.12.2
- 浏览器及其版本：56.0.2912.0 canary (64-bit)

#### 你做了什么？

使用Stepper组件的时候，比如初始值是0，step为1，这时候用输入框输入50，然后保持focus状态，直接点+按钮

#### 你期待的结果是：

值为51

#### 实际上的结果：

值为1

#### 可重现的在线演示

[例子](https://codepen.io/mhcgrq/pen/mOJBVX)

**Comment by warmhug** [comment]
https://github.com/react-component/input-number/issues/25

**Comment by silentcloud** [comment]
@mhcgrq  重新 install
