### ISSUE TITLE
Collapse组件展开或关闭时Pannel抖动明显

### ISSUE THREAD

**Issue by ZG-frank** [ant-design/ant-design-mobile#4931]
### Version of antd-mobile

5.4.0

### Operating system and its version

Others

### Browser and its version

Chrome 99.0.4844.51（正式版本） （64 位）

### Sandbox to reproduce

https://codesandbox.io/s/compassionate-frost-hpyfwo?file=/src/App.tsx

### What happened?

当使用Collapse组件进行开发时，若条目较多，Pannel有背景/文字较多时，展开或关闭组件都会有明显的延迟视觉效果，猜测是动画效果使用height的高度变化导致浏览器重绘多次；是否可以用css来控制这个动画效果呢

**Comment by awmleer** [comment]
延迟效果是指啥……？

**Comment by awmleer** [comment]
你是想说动画最后的那几帧有点迟缓么？

**Comment by awmleer** [comment]
我稍微调整了一下动画的参数，现在应该利索一些了： 9032bd28

**Comment by ZG-frank** [comment]
> 你是想说动画最后的那几帧有点迟缓么？

是的，我弄了个gif  
![demo](https://user-images.githubusercontent.com/15084040/158729630-eb7eb395-eb14-4e9a-83ec-51578785fafe.gif)

**Comment by awmleer** [comment]
嗯嗯，那应该下个版本就解决了，到时候你升级一下试试～

**Comment by ZG-frank** [comment]
> 我稍微调整了一下动画的参数，现在应该利索一些了： [9032bd2](https://github.com/ant-design/ant-design-mobile/commit/9032bd2809ec9ac8a65f932db7a8ea560ac5cadd)

另外想问下不采用transition方法的原因是

**Comment by awmleer** [comment]
有很多原因，但是最主要的还是 CSS 动画难以获取和操作内部的动画状态，具体可以看[这篇文章](https://mp.weixin.qq.com/s/gn2yLVqehLekD5025vmOqw)里的介绍

**Comment by ZG-frank** [comment]
> 有很多原因，但是最主要的还是 CSS 动画难以获取和操作内部的动画状态，具体可以看[这篇文章](https://mp.weixin.qq.com/s/gn2yLVqehLekD5025vmOqw)里的介绍

还有个建议，可以给展开的pannel加个展开状态吗（class

**Comment by awmleer** [comment]
你需要依赖这个状态干啥……？ @ZG-frank
