### ISSUE TITLE
[Button] v5 版本，button组件某些情况下文字不居中

### ISSUE THREAD

**Issue by KingAmo** [ant-design/ant-design-mobile#4939]
### Version of antd-mobile

5.6.0

### Operating system and its version

Others

### Browser and its version

chorme 99

### Sandbox to reproduce

https://codesandbox.io/s/laughing-joliot-55eulf?file=/src/App.tsx

### What happened?

Button高度比较小的时候，button中的文字不居中
期望：文字正确的居中显示

**Comment by awmleer** [comment]
这是预期行为……你要是想改 Button 大小的话，可以通过 `size` 属性
