### ISSUE TITLE
Image组件css变量无效

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#4940]
### Version of antd-mobile

eg 5.7.0

### What is this feature about?

Image组件css变量无效，请检查下

**Comment by yaogengzhu** [comment]
Image组件css变量 验证了 是OK的

只提供了 
```css
'--width' | '--height'
```

**Comment by awmleer** [comment]
@codedart2018 你是设置的啥变量？

**Comment by codedart2018** [comment]
--size --border-raduis

**Comment by codedart2018** [comment]
难道我昨天看错文档了？我刚去看只有--width --height呢

**Comment by awmleer** [comment]
估计你看错文档了 😓
