### ISSUE TITLE
[Picker]组件增加loading属性

### ISSUE THREAD

**Issue by honorsuper** [ant-design/ant-design-mobile#4945]
### Version of antd-mobile

5.7.1

### What is this feature about?

Picker组件中，columns对应的数据有些场景是请求接口获取的，所以可以通过loading属性，来渲染等待态

**Comment by awmleer** [comment]
等待态是啥，给 Picker 整体加个 Mask 和 loading 的转圈么？

**Comment by honorsuper** [comment]
> 等待态是啥，给 Picker 整体加个 Mask 和 loading 的转圈么？

是的

**Comment by awmleer** [comment]
OK 这个我们考虑一下，如果做的话，得先做一个 LoadingMask 组件出来

**Comment by yangdepp** [comment]
https://github.com/ant-design/ant-design-mobile/discussions/5399

**Comment by awmleer** [comment]
> #5399

+1 这样的话感觉就不需要 loading 属性了？
