### ISSUE TITLE
Popover 组件报错 函数错误

### ISSUE THREAD

**Issue by yuyiqun** [ant-design/ant-design-mobile#4947]
### Version of antd-mobile

5.7.0"

### Operating system and its version

Others

### Browser and its version

谷歌浏览器

### What happened?

![image](https://user-images.githubusercontent.com/65887472/159224248-271961d1-b9b7-4f9e-b869-8d3767574262.png)
报错 
![image](https://user-images.githubusercontent.com/65887472/159224483-83837482-1302-48f3-b834-ba5256799c3a.png)
官网的例子

### Relevant log output

```shell
jsx： <span
              className="close"
            >
                 <Popover.Menu
                     actions={actions}
                     onAction={node => Toast.show(`选择了 ${node.text}`)}
                     placement='left'
                     trigger='click'
                 >
              <Icon type="iconbtn_essay_close" />
                     </Popover.Menu>
            </span>
scss： .close {
        position: absolute;
        right: 0;
        top: 50%;
        margin-top: -7px;
        font-size: 14px;
      }
```

**Comment by yuyiqun** [comment]
报错点击过去 
<img width="384" alt="Snipaste_2022-03-21_16-19-13" src="https://user-images.githubusercontent.com/65887472/159225217-28f471cf-3ef8-4fe6-a069-70fa904d14cf.png">

**Comment by miracles1919** [comment]
@yuyiqun  给个复现demo吧
https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json

**Comment by awmleer** [comment]
@yuyiqun 看起来和构建打包可能有关系，也可以考虑把项目精简一下，然后打个 zip 包上传上来

**Comment by miracles1919** [comment]
似乎是 cra 的bug，见这个 [11889](https://github.com/facebook/create-react-app/issues/11889)

我试了下，确实能复现，在最新的 cra，[写了个 demo](https://github.com/miracles1919/cra-with-demos) 

`const core = require('@floating-ui/core')` ❎

core 打印出来是个字符串 `/static/media/floating-ui.core.2fede1fcf03614c34e96.cjs`

`import core from '@floating-ui/core` ✅

---
等后面改成直接 import @floatin-ui/dom 应该就可以了

**Comment by awmleer** [comment]
get，那很快就会改成正常的 import from @floatin-ui/dom 了

**Comment by awmleer** [comment]
已修复： c0ef3fca2

升级 antd-mobile 到 5.8.0 就可以了
