### ISSUE TITLE
整理 ts PropsType 文件

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#495]
现在有的放在 index(.web).tsx 文件内，如 https://github.com/ant-design/ant-design-mobile/blob/master/components/accordion/index.web.tsx#L4

有的加了 组件名前缀，如 https://github.com/ant-design/ant-design-mobile/blob/master/components/activity-indicator/ActivityIndicatorPropTypes.tsx 这个 ActivityIndicator 前缀没必要加。

有的在一个组件里 有多个 验证文件 存在，如:  checkbox 组件有三个验证文件 AgreeItemPropsType.tsx  / CheckboxItemPropsType.tsx / CheckboxPropsType.tsx 

建议都整理成 **一个文件、文件名统一为 PropsType.tsx**、有多种验证也放一个文件里像这样 export 出来多个 interface 即可 https://github.com/ant-design/ant-design-mobile/blob/master/components/search-bar/SearchBarPropTypes.tsx

**Comment by warmhug** [comment]
如果没什么意见，就这样做。 @pingan1927 你的组件我帮你整理。这个整理也 pick 到 0.9.x 分支去 @silentcloud

**Comment by silentcloud** [comment]
69b2ff6f95565ea329423a189001b06769c92466
