### ISSUE TITLE
当前版本不支持国际化吗，没有在文档中看到对应的api

### ISSUE THREAD

**Issue by manzxiao** [ant-design/ant-design-mobile#4953]
### Version of antd-mobile

v5.7.2

**Comment by miracles1919** [comment]
可以通过 [ConfigProvider](https://mobile.ant.design/zh/components/config-provider ) 配置

指南里是不是可以加一个 @awmleer

**Comment by manzxiao** [comment]
好的，谢谢。

**Comment by manzxiao** [comment]
目前在国际化中的文件只看到中英文，其他语言是要自己添加么

**Comment by miracles1919** [comment]
[5.7.2](https://github.com/ant-design/ant-design-mobile/releases/tag/v5.7.2) 新增了 zh-HK zh-TW fa-IR 这三个

我打包了试了下，应该是有的

![image](https://user-images.githubusercontent.com/22469543/159443421-53fc75cc-05fc-4111-91e5-7eb0c2f939f4.png)

**Comment by awmleer** [comment]
> 可以通过 [ConfigProvider](https://mobile.ant.design/zh/components/config-provider ) 配置
> 
> 
> 
> 指南里是不是可以加一个国际化 @awmleer 

嗯嗯的确是应该单独加一篇文档的

**Comment by miracles1919** [comment]
那我来吧 ~

**Comment by manzxiao** [comment]
@miracles1919 嗯，感谢。新版本有了，但是除了ErrorBlock的国际化做了，其他的默认值类似Modal的confirmText目前还是`我知道了` 。是不是可以考虑也改成国际化的了。

**Comment by miracles1919** [comment]
@manzxiao Modal.xxx 这种静态方法目前是不支持 ConfigProvider 的，获取不到 context

**Comment by manzxiao** [comment]
好的，感谢

**Comment by awmleer** [comment]
@manzxiao Modal 和 Dialog 这种通过指令式使用的组件，需要用 `setDefaultConfig` 来设置默认语言，类似这样：

```js
setDefaultConfig({
  locale: enUS,
})
```

具体可以看下文档上 ConfigProvider 的第二个例子
