### ISSUE TITLE
[Feature Request] 希望 Slider 组件支持自定义ThumbIcon

### ISSUE THREAD

**Issue by KingAmo** [ant-design/ant-design-mobile#4954]
### Version of antd-mobile

5.6.0

### What is this feature about?

![image](https://user-images.githubusercontent.com/29938227/159431984-c1c4417d-b0c1-4629-a184-fbfdbbc01e48.png)

Slider 组件目前默认的 ThumbIcon 组件，大概率不是开发者想要的样式，希望能支持自定义这个icon

**Comment by yaogengzhu** [comment]
我来支持试一试

**Comment by awmleer** [comment]
#4957
