### ISSUE TITLE
Input 和 TextArea 为什么要将 NamePath 转为 id 属性？

### ISSUE THREAD

**Issue by caijf** [ant-design/ant-design-mobile#4956]
### Version of antd-mobile

5.7.0

### Description

Input 和 TextArea 为什么要将 NamePath 转为 id 属性？

同页面不同表单存在相同的 name 时，会有警告。

![image](https://user-images.githubusercontent.com/5070722/159443545-9ae295eb-1947-401e-9490-ef55d42b3fdb.png)

如果是为了 focus ，可以使用 element.focus

**Comment by awmleer** [comment]
你遇到的这个问题，可以使用 Form 的 name 属性解决：

![image](https://user-images.githubusercontent.com/16526078/159444963-2cb7fc8f-5a75-401d-a9cf-60ec8e55a11c.png)

**Comment by caijf** [comment]
试了 Form 设置 name 也没用

![image](https://user-images.githubusercontent.com/5070722/159449949-df739c1a-a4f0-492b-883e-ea9a13d571a8.png)

**Comment by awmleer** [comment]
看起来是个 bug，codesandbox 的链接可以发一下么 @caijf

**Comment by caijf** [comment]
@awmleer 

https://codesandbox.io/s/test-antd-mobile-id0r4z
