### ISSUE TITLE
请问 TabBar.Item  在 React native 中使用 icon 是只能使用本地图片吗?

### ISSUE THREAD

**Issue by wslw** [ant-design/ant-design-mobile#496]
TabBar.Item 的 icon 文档中描述 [ Image Source(rn)  ]这个在 react native 中如何使用没有明白.我想在 React native 使用网络图片 我该怎么做?

**Comment by silentcloud** [comment]
rn 的 tabbar 具体可以参考 react native 官方

http://facebook.github.io/react-native/docs/tabbarios.html

@wslw
