### ISSUE TITLE
SearchBar不能清除输入内容，报Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by kunmingblue** [ant-design/ant-design-mobile#4961]
### Version of antd-mobile

5.7.1

### Operating system and its version

Android

### Browser and its version

goole chrome 版本 98.0.4758.102

### What happened?

点击清除按钮，不能清除已输入内容，也无法触发onClear事件，如果设置showCancelButton，点击取消按钮，则报Unable to preventDefault inside passive event listener invocation

### Relevant log output

```shell
Unable to preventDefault inside passive event listener invocation.
```

**Comment by yaogengzhu** [comment]
@kunmingblue  
https://codesandbox.io/s/zealous-brahmagupta-4lktko?file=/src/App.tsx
最好能提供一个复现demo

**Comment by awmleer** [comment]
请提供一个具体的复现 demo：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

附：[提问指引](https://github.com/ant-design/ant-design-mobile/blob/master/.github/HOW_TO_ASK_QUESTIONS.md)

**Comment by shengbenqiang** [comment]
我遇到了相同的问题，请问有解决的方法了嘛？

**Comment by Phil-Pu** [comment]
同样的问题，直接把样例代码复制到新项目中运行就会碰到这个错误提示，不管onCancel是否有函数。
已经测试过react-dom v17和v18，都存在这个情况。
