### ISSUE TITLE
InfiniteScroll with useThrottleFn

### ISSUE THREAD

**Issue by Aftea-c** [ant-design/ant-design-mobile#4972]
### Version of antd-mobile

[v5.8.1](https://mobile.ant.design/zh)

### Description

```
const { run } = useThrottleFn(handleScroll) 

<InfiniteScroll
    loadMore={run}
    ...
/>

```
> Type Error: DebouncedFunc<() => Promise<void>> is not assignable to type () => Promise<void>

这种情况怎么处理比较好

**Comment by zzzgydi** [comment]
ahooks的`useThrottleFn`的run的类型，应该和你的输入是一样的，不应该是`DebouncedFunc`吧。

或者说你的 `handleScroll` 就是 `DebouncedFunc`？

**Comment by Aftea-c** [comment]
刚看了下 useThrottleFn 源码 run 应该是  throttle(fn)

**Comment by zzzgydi** [comment]
翻到这个PR https://github.com/alibaba/hooks/pull/1509 

用的lodash的类型，确实都是`DebouncedFunc`，这个类型推导出的fn是`(P) => T | undefined`，和`(P) => T`不兼容。

**Comment by awmleer** [comment]
InfiniteScroll 组件本身就包含了防止重复请求的逻辑，**不应该**配合 ahooks 的 `useThrottleFn` 使用啊

以及，ahooks 现在改之后的 `useThrottleFn` 返回的 `run` 函数的类型是对的，的确应该是 `(P) => T | undefined`，之前类型定义是不严谨的

**Comment by awmleer** [comment]
应该是这个版本之后出现的类型定义变更：https://github.com/alibaba/hooks/releases/tag/v3.1.14

**Comment by 1247748612** [comment]
默认加了个undefined类型，没太理解

可以把undefined类型去掉，像这样
```typescript
export default () => {
  const { run } = useThrottleFn(async () => {})

  type RemoveTypes<T, RT> = T extends RT ? never : T

  type ReturnTypeRequired<T extends (...args: any[]) => any> = {
    (...args: Parameters<T>): RemoveTypes<ReturnType<T>, undefined>
  } & Pick<T, keyof T>

  return (
    <div>
      <InfiniteScroll
        loadMore={run as ReturnTypeRequired<typeof run>}
        hasMore={true}
      />
    </div>
  )
}
```

**Comment by awmleer** [comment]
更新了一下 FAQ： c1ff75dd

这个 issue 关闭了～
