### ISSUE TITLE
InfiniteScroll组件 无限触发 loadMore

### ISSUE THREAD

**Issue by KingAmo** [ant-design/ant-design-mobile#4973]
### Version of antd-mobile

5.8.1

### Operating system and its version

Others

### Browser and its version

chorme 99

### Sandbox to reproduce

https://codesandbox.io/s/focused-rain-j7xdld?file=/src/App.tsx

### What happened?

InfiniteScroll组件 无限触发了 loadMore，见上面的 sandbox 链接，往下滑动时，控制台无限在打印

**Comment by awmleer** [comment]
你在 `loadMore` 里没有 await，所以才导致了这个问题，改之后的正确代码：https://codesandbox.io/s/young-dawn-rmoosm?file=/src/App.tsx
