### ISSUE TITLE
Global css in antdesign mobile not working

### ISSUE THREAD

**Issue by perryaryee** [ant-design/ant-design-mobile#4974]
Unable to resolve module ./global.css from C:\Users\PERRY ARYEE\Desktop\My Files\Expo React Native 3\Ignitelines\ignitelines\node_modules\antd-mobile\cjs\global\index.js:

**Comment by awmleer** [comment]
Are you using antd-mobile in a react native project? Currently antd-mobile doesn't support react native. You can use antd-mobile-rn instead: https://github.com/ant-design/ant-design-mobile-rn

**Comment by pick958128** [comment]
有用
