### ISSUE TITLE
Stepper组件不要删除小数点后的0

### ISSUE THREAD

**Issue by kitty-sheldon** [ant-design/ant-design-mobile#4983]
### Version of antd-mobile

5.8.1

### What is this feature about?

1. 现状 14.90 -> 14.9， 14.00 -> 14
2. 期望 14.90 -> 14.90 ，14.00 -> 14.00
3. 期望优化parseFloat 、Math.max、Math.min 过程，可以根据digits设置精确位数补0，或不设置精确位数时不要对用户传来的原数据value进行1中改变

**Comment by awmleer** [comment]
诶？你设置 `digits` 属性为 `2` 了么

**Comment by kitty-sheldon** [comment]
> 诶？你设置 `digits` 属性为 `2` 了么

设置了，看了下设digits的时候用的parseFloat，所以0没了。
没设置自己格式化好的也试了，用Math.max/min， 0 也没了。

**Comment by awmleer** [comment]
看起来是个 bug

**Comment by 1247748612** [comment]
目前实现好像不只存在以上问题，还有精度问题

我尝试使用rc-input-number的一些utils修复一下

**Comment by awmleer** [comment]
Fixed via 5fee695d

**Comment by awmleer** [comment]
update：上一个 commit 是修复的精度问题，这个 commit 修复了 digits 没生效的问题： 2a319986

不过需要注意的是，如果不传 `digits`，的确是会默认把末尾的 0 抹去的，这是 `toString()` 的默认逻辑，不调整了，如果需要保留 0 的话，可以设置一下 `digits`
