### ISSUE TITLE
Ellipsis 组件，不支持点击事件

### ISSUE THREAD

**Issue by KingAmo** [ant-design/ant-design-mobile#4985]
### Version of antd-mobile

5.8.1

### Operating system and its version

Others

### Browser and its version

chorme 99

### Sandbox to reproduce

https://codesandbox.io/s/competent-snowflake-9xzy9i

### What happened?

Ellipsis 组件，不支持点击事件

期望：点击 Ellipsis 组件的内容（content）时，支持点击事件

**Comment by awmleer** [comment]
@KingAmo 为啥不直接在 Ellipsis 外层自己套一个 div 然后绑定点击事件嘞？

**Comment by yaogengzhu** [comment]
可能不想多加一层不必要的dom

**Comment by awmleer** [comment]
所以你想要的只点击文字内容的时候触发么？点击展开收起按钮的时候要触发事件么？

**Comment by KingAmo** [comment]
> 所以你想要的只点击文字内容的时候触发么？点击展开收起按钮的时候要触发事件么？

是的，只想点击内容的时候触发，不影响展开和收起

**Comment by awmleer** [comment]
那看起来应该是加一个 `onContentClick` 的属性……这个倒是的确可以，因为如果没有这个属性的话，在 Ellipsis 组件外部进行处理其实挺难的

**Comment by awmleer** [comment]
实现思路大概是在 div 的 `onClick` 里加一下判断……？如果 `e.target` 是 `div` 元素本身的话就触发 `onContentClick`

**Comment by yaogengzhu** [comment]
> onContentClick

我修改了下！

**Comment by awmleer** [comment]
Close via #4986
