### ISSUE TITLE
datePicker回调的value值不对

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design-mobile#4987]
### Version of antd-mobile

5.7.2

### Operating system and its version

iOS

### Browser and its version

mac chrome92

### Sandbox to reproduce

https://mobile.ant.design/zh/components/picker#datepicker

### What happened?

date-picker 精度选择到月，在本月为3月的情况下选择2月， 第一次获取到的value值是 3月1号，第二次再选到2月才获取到2月1号值，官网的demo即可复现
![Mar-29-2022 10-06-53](https://user-images.githubusercontent.com/22299421/160518449-d3c1dc4c-d8df-4919-8088-c976297a20c8.gif)

**Comment by awmleer** [comment]
复现出来了，的确有 bug
感谢反馈～

**Comment by awmleer** [comment]
已修复： 17f18ce6
