### ISSUE TITLE
PasscodeInput在iOS系统的浏览器会出现键盘重复触发问题

### ISSUE THREAD

**Issue by duanliang** [ant-design/ant-design-mobile#4988]
### Version of antd-mobile

5.8.2

### Operating system and its version

iOS

### Browser and its version

15.4

### Sandbox to reproduce

https://mobile.ant.design/~demos/passcode-input-demo1

### What happened?

正常线上的demo，会出现键盘重复触发问题；
复现视频：

https://user-images.githubusercontent.com/13715221/160520371-edb7f636-e634-490e-ac3f-b35d5468a8ff.mp4

**Comment by awmleer** [comment]
复现出来了，我这里是按删除键的时候会多次触发，输入数字的时候是正常的
