### ISSUE TITLE
升级最新版本的antd-mobile，突然报错

### ISSUE THREAD

**Issue by JuSanZhi** [ant-design/ant-design-mobile#4990]
### Version of antd-mobile

^5.9.1

### What happened?

vite（^2.7.2） + antd-mobile搭建。  升级antd-mobile最新版本 ，报找不到 antd-mobile/es/global文件错误
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/24559368/160568808-877f3c54-6792-4282-a662-bbe40d3e3585.png">

**Comment by awmleer** [comment]
@JuSanZhi 可以把项目打个包上传一下么？（或者 push 到一个 GitHub 仓库里？）

@3lang3 老哥求助攻～

**Comment by 3lang3** [comment]
> @JuSanZhi 可以把项目打个包上传一下么？（或者 push 到一个 GitHub 仓库里？）
> 
> @3lang3 老哥求助攻～

在回家路上 回家看下

**Comment by 3lang3** [comment]
@JuSanZhi 
```js
import 'antd-mobile/es/global/global.css'
```
这样是可以的，先这样解决下，虽然我感觉这里不需要单独引入，vite支持按需加载的

**Comment by beidan** [comment]
同样遇到，回退到之前版本即可。 不知道做了什么处理

**Comment by 3lang3** [comment]
@beidan 支持remix的feature影响到了，参考上面先兼容下

**Comment by awmleer** [comment]
@3lang3 我们不是设置了 `./es/` 了么，奇怪：

```json
{
  "exports": {
    ".": {
      "node": {
        "import": "./bundle/antd-mobile.es.js",
        "require": "./bundle/antd-mobile.cjs.js"
      },
      "import": "./es/index.js",
      "require": "./cjs/index.js",
      "types": "./es/index.d.ts"
    },
    "./es": "./es/index.js",
    "./cjs": "./cjs/index.js",
    "./es/": "./es/", // <- 这里没有生效么
    "./cjs/": "./cjs/",
    "./bundle/": "./bundle/",
    "./package.json": "./package.json",
    "./package": "./package.json",
    "./2x": "./2x"
  }
}
```

**Comment by awmleer** [comment]
先公告一下：在这个 issue close 之前，可以先手动把版本降级到 5.8.2 临时避免这个问题

**Comment by awmleer** [comment]
@beidan 可以发一下你项目更具体的环境信息么？比如是 vite 还是 webpack？是在 dev 模式还是 prod 模式遇到的这个问题？

**Comment by 3lang3** [comment]
> 

我已经复现了 vite + pnpm直接就出来了，我上面给的兼容方法可以解决报错问题。

不知道是不是vite解析有问题，我用umi试试

**Comment by 3lang3** [comment]
> @3lang3 我们不是设置了 `./es/` 了么，奇怪：
> 
> ```json
> {
>   "exports": {
>     ".": {
>       "node": {
>         "import": "./bundle/antd-mobile.es.js",
>         "require": "./bundle/antd-mobile.cjs.js"
>       },
>       "import": "./es/index.js",
>       "require": "./cjs/index.js",
>       "types": "./es/index.d.ts"
>     },
>     "./es": "./es/index.js",
>     "./cjs": "./cjs/index.js",
>     "./es/": "./es/", // <- 这里没有生效么
>     "./cjs/": "./cjs/",
>     "./bundle/": "./bundle/",
>     "./package.json": "./package.json",
>     "./package": "./package.json",
>     "./2x": "./2x"
>   }
> }
> ```

生效了
```js
// 启用 exports后
import 'antd-mobile/es/global'
等于
import 'antd-mobile/es/global.js'
并不是我们认为的
import 'antd-mobile/es/global/index.js'
```

**Comment by 3lang3** [comment]
@awmleer https://github.com/ant-design/ant-design-mobile/pull/4992#issuecomment-1081876840

**Comment by JuSanZhi** [comment]
> @JuSanZhi
> 
> ```js
> import 'antd-mobile/es/global/index.js'
> ```
> 
> 这样是可以的，先这样解决下，虽然我感觉这里不需要单独引入，vite支持按需加载的

但是又有新的 问题
![image](https://user-images.githubusercontent.com/24559368/160784348-d64b7d7e-67ba-4e13-a689-48d9e62bcce2.png)

**Comment by 3lang3** [comment]
@JuSanZhi 
这个bug正在修复。

可以先用下面这样修复下？
```js
import { Toast } from 'antd-mobile';
```
上面的 `import 'antd-mobile/es/global'` 可以删了

**Comment by JuSanZhi** [comment]
> ```js
> import { Toast } from 'antd-mobile';
> ```

我就是用这个的 import { Toast } from 'antd-mobile';然后他提示我截图那种用法

**Comment by 3lang3** [comment]
> > ```js
> > import { Toast } from 'antd-mobile';
> > ```
> 
> 我就是用这个的 import { Toast } from 'antd-mobile';然后他提示我截图那种用法

去node_modules下看下具体的vite版本，然后vite.config.ts里面有配置alias吗？

我用vite `2.8.6` 没复现出来

**Comment by JuSanZhi** [comment]
> > > ```js
> > > import { Toast } from 'antd-mobile';
> > > ```
> > 
> > 
> > 我就是用这个的 import { Toast } from 'antd-mobile';然后他提示我截图那种用法
> 
> 去node_modules下看下具体的vite版本，然后vite.config.ts里面有配置alias吗？
> 
> 我用vite `2.8.6` 没复现出来

<img width="569" alt="image" src="https://user-images.githubusercontent.com/24559368/160789186-a77988ea-7b97-4cb9-9f2a-b0fd4ccba8de.png">
<img width="741" alt="image" src="https://user-images.githubusercontent.com/24559368/160789309-6890d4f0-3ae9-400b-8cd3-17ed0becd19d.png">
要不我试下升级vite？

**Comment by 3lang3** [comment]
@JuSanZhi 试试吧 看着没啥问题  `import { Toast } from 'antd-mobile';` 做个按理说不会有问题的 诡异
