### ISSUE TITLE
表单校验后，手动修改 Picker 值不会清空必填提示

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design-mobile#4991]
### Version of antd-mobile

latest

### What happened?

表单校验后，手动修改 Picker 值不会清空必填提示

### Relevant log output

```shell
手动修改 Picker 值需要清空必填提示
```

**Comment by awmleer** [comment]
https://user-images.githubusercontent.com/16526078/160600166-e0bb141b-4ffc-44d0-b3eb-9385a34cbe6c.mp4

**Comment by findmio** [comment]
这里加一个 [validateTrigger 的属性](https://mobile.ant.design/zh/components/form#%E5%B1%9E%E6%80%A7-1) 应该就可以了吧

```
validateTrigger='onConfirm'
```

**Comment by awmleer** [comment]
@crazyair

**Comment by crazyair** [comment]
> @crazyair

上面说加那个属性可以实现，不过建议用户传了 `trigger="onConfirm"` 就自动使用 onConfirm 校验比较好

**Comment by awmleer** [comment]
`validateTrigger` 默认值自动取 `trigger`？感觉🉑️
