### ISSUE TITLE
 版本号不规范导致升级异常

### ISSUE THREAD

**Issue by FrominXu** [ant-design/ant-design-mobile#4993]
### Version of antd-mobile

5.x

### Description

从5.2.x-5.9.x版本，组件的引用位置、属性、方法、样式等都有发生变化，这种不兼容变更的版本这样管理，会导致工程构建时出现各种异常。建议功能整合发布以及按正确的版本号管理

**Comment by awmleer** [comment]
> 组件的引用位置、属性、方法、样式等都有发生变化

可以具体说一下“变化”是指什么吗？

> 会导致工程构建时出现各种异常

你遇到的异常具体是什么？

> 按正确的版本号管理

你认为哪次发布的版本号不正确？正确的版本号管理你认为应该是怎样的？

**Comment by gooddaddy** [comment]
@awmleer  是不是升级到 5.9.1后 组件样色丢失了，是不是你的package.json文件 配置得有问题：
```  
"exports": {
    ".": {
      "node": {
        "import": "./bundle/antd-mobile.es.js",
        "require": "./bundle/antd-mobile.cjs.js"
      },
      "import": "./es/index.js",
      "require": "./cjs/index.js",
      "types": "./es/index.d.ts"
    },
   ...
  }
```

是不是应该写成：
```
"exports": {
    ".": {
      "node": {
        "import": "./bundle/antd-mobile.es.js",
        "require": "./bundle/antd-mobile.cjs.js"
      },
    "default":{
      "import": "./es/index.js",
      "require": "./cjs/index.js",
      "types": "./es/index.d.ts"
      }
    },
   ...
  }
```
不然 在brower 环境下编译的时候 都是使用 ./bundle/antd-mobile.cjs.js 来引入的，这样就没办法自动引入组件的样色，从而导致样色丢失。

**Comment by 3lang3** [comment]
> @awmleer 我这边升级到 5.9.1后 组件样色丢失了，是不是 package.json文件 配置得有问题：
> 
> ```
> "exports": {
>     ".": {
>       "node": {
>         "import": "./bundle/antd-mobile.es.js",
>         "require": "./bundle/antd-mobile.cjs.js"
>       },
>       "import": "./es/index.js",
>       "require": "./cjs/index.js",
>       "types": "./es/index.d.ts"
>     },
>    ...
>   }
> ```
> 
> 是不是应该写成：
> 
> ```
> "exports": {
>     ".": {
>       "node": {
>         "import": "./bundle/antd-mobile.es.js",
>         "require": "./bundle/antd-mobile.cjs.js"
>       },
>     "default":{
>       "import": "./es/index.js",
>       "require": "./cjs/index.js",
>       "types": "./es/index.d.ts"
>       }
>     },
>    ...
>   }
> ```
> 
> 不然 在brower 环境下编译的时候 都是使用 ./bundle/antd-mobile.cjs.js 来引入的，这样就没办法自动引入组件的样色，从而导致样色丢失。

你是vite构建的吗？
browser下是走/es/index.js或者cjs/index.js的 node下的配置是针对ssr框架(remix)的

**Comment by FrominXu** [comment]
> > @awmleer 我这边升级到 5.9.1后 组件样色丢失了，是不是 package.json文件 配置得有问题：
> > ```
> > "exports": {
> >     ".": {
> >       "node": {
> >         "import": "./bundle/antd-mobile.es.js",
> >         "require": "./bundle/antd-mobile.cjs.js"
> >       },
> >       "import": "./es/index.js",
> >       "require": "./cjs/index.js",
> >       "types": "./es/index.d.ts"
> >     },
> >    ...
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 是不是应该写成：
> > ```
> > "exports": {
> >     ".": {
> >       "node": {
> >         "import": "./bundle/antd-mobile.es.js",
> >         "require": "./bundle/antd-mobile.cjs.js"
> >       },
> >     "default":{
> >       "import": "./es/index.js",
> >       "require": "./cjs/index.js",
> >       "types": "./es/index.d.ts"
> >       }
> >     },
> >    ...
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不然 在brower 环境下编译的时候 都是使用 ./bundle/antd-mobile.cjs.js 来引入的，这样就没办法自动引入组件的样色，从而导致样色丢失。
> 
> 你是vite构建的吗？ browser下是走/es/index.js或者cjs/index.js的 node下的配置是针对ssr框架(remix)的

这个问题我也遇到了，应该是这样：

**Comment by FrominXu** [comment]
> > @awmleer 我这边升级到 5.9.1后 组件样色丢失了，是不是 package.json文件 配置得有问题：
> > ```
> > "exports": {
> >     ".": {
> >       "node": {
> >         "import": "./bundle/antd-mobile.es.js",
> >         "require": "./bundle/antd-mobile.cjs.js"
> >       },
> >       "import": "./es/index.js",
> >       "require": "./cjs/index.js",
> >       "types": "./es/index.d.ts"
> >     },
> >    ...
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 是不是应该写成：
> > ```
> > "exports": {
> >     ".": {
> >       "node": {
> >         "import": "./bundle/antd-mobile.es.js",
> >         "require": "./bundle/antd-mobile.cjs.js"
> >       },
> >     "default":{
> >       "import": "./es/index.js",
> >       "require": "./cjs/index.js",
> >       "types": "./es/index.d.ts"
> >       }
> >     },
> >    ...
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不然 在brower 环境下编译的时候 都是使用 ./bundle/antd-mobile.cjs.js 来引入的，这样就没办法自动引入组件的样色，从而导致样色丢失。
> 
> 你是vite构建的吗？ browser下是走/es/index.js或者cjs/index.js的 node下的配置是针对ssr框架(remix)的

这个问题我也遇到了，我觉得应该是这样
"exports": {
    ".": {
      "import": "./es/index.js",
      "require": "./cjs/index.js",
      "types": "./es/index.d.ts",
      "node": {
        "import": "./bundle/antd-mobile.es.js",
        "require": "./bundle/antd-mobile.cjs.js"
      },
     default: '"./cjs/index.js"
    },
   ...

**Comment by awmleer** [comment]
#4992 正在改了

**Comment by awmleer** [comment]
这和版本号也没关系啊，如果是讨论 `exports` 的配置问题的话，请去 #4990

这个 issue 我关了
