### ISSUE TITLE
Ant Design Mobile 5.0 中会支持 ListView 组件吗？

### ISSUE THREAD

**Issue by ronghang** [ant-design/ant-design-mobile#4994]
### What is this feature about?

ListView 是 antd-mobile-v2 里面的长列表组件

https://antd-mobile-v2.surge.sh/components/list-view-cn/

但是最新的 antd-mobile-v5 却取消了这个组件，请问后续会支持吗？

**Comment by awmleer** [comment]
不会的，可以自己把 List 和 react-virtualized 组合起来使用，具体可以参考 List 文档上最后一个 demo

**Comment by ronghang** [comment]
> 不会的，可以自己把 List 和 react-virtualized 组合起来使用，具体可以参考 List 文档上最后一个 demo

ListView 最大的便利就在于它对于分页的处理和 section 的处理，不是所有的列表展示都是平铺的List能搞定的，List+react-virtualized 解决长列表虚拟滚动的问题，但在实际的使用过程中，我这边需要的是一个带请求翻页能力的 List 组件，并且要求翻页顺滑（用户感知不到有请求翻页的卡顿）

**Comment by awmleer** [comment]
听起来是 InfiniteScroll + react- virtualized？
