### ISSUE TITLE
打包出来的代码带有 ES6 字样，如 let，const 等导致白屏

### ISSUE THREAD

**Issue by brownbo** [ant-design/ant-design-mobile#4999]
### Version of antd-mobile

5.8.1

### Browser and its version

ios 10.3.3

### What happened?

打包的代码里面，会增加 let，const，等 es6 字样，导致低版本手机浏览器上出现白屏
期望打包正常

**Comment by awmleer** [comment]
请提供复现 demo

**Comment by brownbo** [comment]
[test.zip](https://github.com/ant-design/ant-design-mobile/files/8386252/test.zip)

**Comment by brownbo** [comment]
> 请提供复现 demo

已提供

**Comment by 1247748612** [comment]
加一行这个配置，umi默认好像不走babel编译了

![image](https://user-images.githubusercontent.com/29533304/161037187-bd46a99c-b656-453c-b771-42a7bed5deb5.png)

我认为libary不需要主动兼容到这么低的版本，否则会造成代码量增多的。
