### ISSUE TITLE
组件变更

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#50]
- [x] FloatMenu http://mobile.ant.design/components/float-menu 改名为 Popover http://framework7.io/docs/popover.html

- [x] Collapse http://mobile.ant.design/components/collapse 改名为 Accordion http://framework7.io/docs/accordion.html#accordion-layout

**Comment by yiminghe** [comment]
👍

**Comment by afc163** [comment]
补充几个：

胶囊型选项卡 http://mobile.ant.design/components/tabs#components-tabs-demo-capsule  独立并命名为 Segments：https://developer.apple.com/ios/human-interface-guidelines/ui-controls/segmented-controls/

APP型选项卡 http://mobile.ant.design/components/tabs/#components-tabs-demo-tabbar 独立并命名为 TabBar：https://developer.apple.com/ios/human-interface-guidelines/ui-bars/tab-bars/

**Comment by yiminghe** [comment]
高大上

**Comment by afc163** [comment]
Form 合并到 List 中去。

**Comment by silentcloud** [comment]
@afc163 tab那个改的很合理，之前想这么干的，不过设计师就那么写的

**Comment by afc163** [comment]
嗯，1.0 所有组件都会重新梳理过。

**Comment by afc163** [comment]
PageResult => Result

**Comment by dyygtfx** [comment]
建议折叠组件和手风琴组件可以合成一个，对外暴露 Collapse， Accordion 两个 API，因为这两个组件都有需求用到

**Comment by afc163** [comment]
SwipeAction 整合到 List.Item 组件中，不再作为一个独立组件。

```
<List.Item swipe={...} />
```

**Comment by pingan1927** [comment]
> PageResult => Result

那最好再区分下类型


> SegmentedControl 

本来有，后来合在一起了，现在又分开，哈哈。

既然要改，我建议这些比较简单的UI组件，遵从RN的设计，如果集成`react-component`会产生比较多冗余代码的话，就在antd-mobile层面解决。

**Comment by warmhug** [comment]
> 嗯，1.0 所有组件都会重新梳理过。

@afc163 如果有些组件跟 antd pc 的一致，可以顺便 review 下代码，提些建议、尽量搞的 **性能好一点**（像 checkbox 的优化一样）

**Comment by afc163** [comment]
其实还好，移动端不会出现大量控件叠加的页面，一般不会有这些性能问题。

**Comment by afc163** [comment]
Timeline 移除，相关演示整合到 Steps。

**Comment by silentcloud** [comment]
赞成 tooltip 移出掉，native 没有看到类似的，只有 menu 形式的

**Comment by silentcloud** [comment]
> 从 ActionSheet 中拆出 ShareSheet。

这个建议不要拆，要跟 RN 保持一致；@afc163

**Comment by afc163** [comment]
@silentcloud 👌
