### ISSUE TITLE
LocaleProvider

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design-mobile#500]
Something like https://ant.design/components/locale-provider/

ref: https://github.com/ant-design/ant-design-mobile/issues/487

* [x] [Pagination](https://mobile.ant.design/components/pagination/)
* [x] [DatePicker](https://mobile.ant.design/components/date-picker/)

**Comment by benjycui** [comment]
空了再做吧。。

**Comment by paranoidjk** [comment]
这个我来搞 @warmhug 现在拉 `1.1.0`出来继续往前迭代ok？

**Comment by warmhug** [comment]
来得及的话、就做到 1.0 里来吧，可以修改 milestone

**Comment by paranoidjk** [comment]
done https://github.com/ant-design/ant-design-mobile/pull/820
