### ISSUE TITLE
vite (rollup) 在 5.9.1 和 5.9.2 下 build 时无法解析 locales 文件的 import，而 5.9.0 正常

### ISSUE THREAD

**Issue by leviathan-n** [ant-design/ant-design-mobile#5000]
### Version of antd-mobile

5.9.2

### Operating system and its version

Others

### Browser and its version

edge 99.0.1150.55 

### Sandbox to reproduce

https://stackblitz.com/edit/vitejs-vite-ixsqtt?file=vite.config.ts

### What happened?

vite build 时出错，rollup 报无法解析 locales 文件

### Relevant log output

```shell
[vite]: Rollup failed to resolve import "antd-mobile/es/locales/zh-CN" from "src/main.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "antd-mobile/es/locales/zh-CN" from "src/main.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/projects/vitejs-vite-ixsqtt/node_modules/vite/dist/node/chunks/dep-9c153816.js:39242:19)
    at onwarn (/home/projects/vitejs-vite-ixsqtt/node_modules/vite/dist/node/chunks/dep-9c153816.js:39020:13)
    at Object.eval [as onwarn] (/home/projects/vitejs-vite-ixsqtt/node_modules/rollup/dist/shared/rollup.js:23129:13)
    at ModuleLoader.handleResolveId (/home/projects/vitejs-vite-ixsqtt/node_modules/rollup/dist/shared/rollup.js:22419:26)
    at eval (/home/projects/vitejs-vite-ixsqtt/node_modules/rollup/dist/shared/rollup.js:22380:26)
```

**Comment by awmleer** [comment]
@3lang3 老问题又来了～除了 utils 之外，看来还得处理 locales，我打算之间写脚本全量遍历一遍生成 exports 了……不然未来还是很容易出现类似的问题

**Comment by awmleer** [comment]
@leviathan-n 先回退一下版本吧，保险一点的话可以推到 5.8.2 版本，我这两天修复一下重新发布个版本

**Comment by leviathan-n** [comment]
@awmleer 好的 感谢回复

**Comment by 3lang3** [comment]
> @leviathan-n 先回退一下版本吧，保险一点的话可以推到 5.8.2 版本，我这两天修复一下重新发布个版本

是vite(or esbuild)的问题，exports子路径解析不正确，我去那边反映下

主动申明所有导出也只是为了给vite兜底，我觉得先加个locale path规则好了。

怪我没仔细看文档，遗留了locale

**Comment by awmleer** [comment]
那先临时加下 locales 好了

**Comment by houxd1992** [comment]
我仍然有这个问题

**Comment by houxd1992** [comment]
> @houxd1992 那可以再新开一个 issue 哈，然后提供个复现 demo

我尝试出来了，我项目里还用了antd
`vitePluginImp({
      libList: [
        {
          libName: "antd",
          libDirectory: "es",
          style: (name) => `antd/es/${name}/style`,
        },
      ],
    }),`
上面这样就会报错

改成了：
`vitePluginImp({
      libList: [
        {
          libName: "antd-mobile",
          libDirectory: "es/components",
          style: () => false,
        },
        {
          libName: "antd",
          libDirectory: "es",
          style: (name) => `antd/es/${name}/style`,
        },
      ],
    }),`
就能build了，是因为libName都匹配到了antd？
