### ISSUE TITLE
希望Collapse的children不要都处理为Panel，这样会导致Panel不能抽离为子组件，数据通信会变的很麻烦。

### ISSUE THREAD

**Issue by InuYashaDo** [ant-design/ant-design-mobile#5004]
### Version of antd-mobile

5.9.2

### What is this feature about?

<img width="339" alt="image" src="https://user-images.githubusercontent.com/51562481/160982206-c211a844-cd05-422c-b0ca-e64dbc69319c.png">
如上，想要把panel抽离到LbelItem无法实现，这样导致自定义的title处理的数据想要跟父组件做隔离变的相当困难。

**Comment by awmleer** [comment]
目前是通过 `React.Children.forEach()` 遍历的，所以如果封装到自定义的组件之中，的确就会有问题了，很多组件都有这个限制，比如 Form 和 IndexBar

后面我再看看有没有什么办法优化一下吧，Form 和 IndexBar 是很难做优化的，这个是已知的，不知道 Collapse 能不能

**Comment by 1247748612** [comment]
采用React.children实现是考虑到什么情况？

**Comment by awmleer** [comment]
@1247748612 可以看下 Form 和 IndexBar 的实现逻辑，Form 是需要把 `Form.Header` 转成分组，IndexBar 的具体解释在[这里](https://www.yuque.com/awmleer/rgdap2/gffgeh)

**Comment by awmleer** [comment]
update 一下结论，这里的逻辑是预期行为，而且也没有计划调整了

如果你遇到了一些情况需要做自定义的封装，可以考虑封装成一个 render function 而不是自定义组件，你 issue 里描述的这个场景应该是可以通过这种思路解决的，可以试一下，如果发现搞不定的话，可以写一个完整的 [demo](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 出来，发到这里大家一起看一下

issue 我先关闭了
