### ISSUE TITLE
引入中文包出错

### ISSUE THREAD

**Issue by xingqiangqiang** [ant-design/ant-design-mobile#5008]
### Version of antd-mobile

5.9.2

### Operating system and its version

Others

### What happened?

我尝试升级版本至5.9.2，项目启动后报错
<img width="605" alt="image" src="https://user-images.githubusercontent.com/73377464/161041753-3d9fe36c-287e-4d7b-b004-ac1bd013f03d.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/73377464/161042360-3d0edcf8-d7c2-4a6f-b338-38bd16c987a0.png">

**Comment by awmleer** [comment]
@xingqiangqiang 你是 vite 的项目么？

**Comment by awmleer** [comment]
升级到 v5.9.3 版本试试？
