### ISSUE TITLE
package.json export field

### ISSUE THREAD

**Issue by javaxiu** [ant-design/ant-design-mobile#5009]
### Version of antd-mobile

5.9.2

### Description

为什么这个地方有这样一个写法
```json
{
exports: {
"./es/*": "./es/*/index.js",
}
}
```
这导致我在独立引用指定文件时会出现异常 
`import { InternalToast } from 'antd-mobile/es/components/toast/toast';`
报错 module not found
因为这样的引用被改成了指向 antd-mobile/es/components/toast/toast/index.js

**Comment by awmleer** [comment]
@3lang3 😵

**Comment by awmleer** [comment]
BTW @3lang3 老兄可以考虑加一波我们的[开发者钉钉群](https://github.com/ant-design/ant-design-mobile/blob/master/.github/CONTRIBUTING.md#加入我们的社区钉钉群)～

**Comment by 3lang3** [comment]
> BTW @3lang3 老兄可以考虑加一波我们的[开发者钉钉群](https://github.com/ant-design/ant-design-mobile/blob/master/.github/CONTRIBUTING.md#加入我们的社区钉钉群)～

好的 明天加下 今天在外面还没回去
