### ISSUE TITLE
list列表组件建议支持拖拽排序功能，或者新增拖拽组件

### ISSUE THREAD

**Issue by cassieyang13** [ant-design/ant-design-mobile#5014]
### Version of antd-mobile

5.9.x

### What is this feature about?

移动端还没有一个带有拖拽属性的组件，建议可以增加一个

**Comment by awmleer** [comment]
不知道可不可以直接搭配 react-dnd 来实现

**Comment by awmleer** [comment]
有兴趣的朋友可以试一下配合其他库（例如上面提到的 react-dnd）来实现一个 demo，加到文档里，antd-mobile 本身是不会支持这个功能的

**Comment by yaogengzhu** [comment]
我尝试支持写下
