### ISSUE TITLE
error in all reactnative Ant components

### ISSUE THREAD

**Issue by deppimaracanau** [ant-design/ant-design-mobile#5018]
### Version of antd-mobile

5.0.0

### Operating system and its version

Win 10/11 or ubuntu 21.04/21.10/22.04
### Browser and its version

 Chrome  Versão 99.0.4844.84 (Compilação oficial) (64 bits)

### What happened?

When checking the code examples of any component, the following error appears in codsandbox: Error
Could not fetch dependencies, please try again in a couple seconds: Dependency @babel/plugin-transform-flow-strip-types not found.

### Relevant log output

```shell
Error
Could not fetch dependencies, please try again in a couple seconds: Dependency @babel/plugin-transform-flow-strip-types not found
▼ 4 stack frames were expanded.
re
https://codesandbox.io/static/js/sandbox.b02c05706.js:1:168333
(anonymous function)
https://codesandbox.io/static/js/sandbox.b02c05706.js:1:171831
(anonymous function)
https://codesandbox.io/static/js/sandbox.b02c05706.js:1:172078
i
https://codesandbox.io/static/js/sandbox.b02c05706.js:1:169269
▲ 4 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
```

**Comment by awmleer** [comment]
Seems like this issue is not related with antd-mobile.
