### ISSUE TITLE
date-picker list状态和外部状态不一致

### ISSUE THREAD

**Issue by xueqingxiao** [ant-design/ant-design-mobile#502]
#### 本地环境

- antd-mobile 版本：最新版
- 操作系统及其版本：macOS 最新版本 
- 浏览器及其版本： Chrome 最新版本
官网demo (https://mobile.ant.design/components/date-picker/)

快速滑动picker 还没停下来点击确定，再次点开date picker 就会发现list组件里的显示的日期和外面显示的日期不一致。

**Comment by xueqingxiao** [comment]
@yiminghe

**Comment by yiminghe** [comment]
重装
