### ISSUE TITLE
[ImageUploader] pic preview object-fit can be pass by uploader

### ISSUE THREAD

**Issue by anysunflower** [ant-design/ant-design-mobile#5020]
### What is this feature about?

https://github.com/ant-design/ant-design-mobile/blob/master/src/components/image-uploader/preview-item.tsx

<img width="531" alt="image" src="https://user-images.githubusercontent.com/40011822/161266241-16b1dcd1-471a-43a4-985c-7b2675990176.png">

fit可以允许用户自己传，否则编辑完的结果是在style上，不方便hack

<img width="412" alt="image" src="https://user-images.githubusercontent.com/40011822/161266370-95109587-3f9a-40b6-ab35-1d3629e499ce.png">

**Comment by awmleer** [comment]
你是想自定义 ImageUploader 组件中，Image 的 fit 属性？

或许给 ImageUploader 加个 `imageFit` 属性来解决你的问题？

**Comment by anysunflower** [comment]
> 你是想自定义 ImageUploader 组件中，Image 的 fit 属性？
> 
> 或许给 ImageUploader 加个 `imageFit` 属性来解决你的问题？

对的，希望修改上传完图片之后图片展示的fit

**Comment by miracles1919** [comment]
我来加一下 ~

**Comment by miracles1919** [comment]
@awmleer 这个 issue 可以关了吧
