### ISSUE TITLE
qiankun 子应用shadowDOM下使用passive导致滚动条不能滚动

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#5021]
### Version of antd-mobile

5.9.3

### Browser and its version

手机andriod ios都有问题

### What happened?

qiankun 子应用shadowDOM环境下，
文件ant-design-mobile/src/utils/use-lock-scroll.ts里，supportsPassive使用{ passive: false }导致div滚动条不能滚动，
这样就没问题，
document.addEventListener(
      'touchmove',
      onTouchMove,
      false
    )
这个看如何处理？提供全局配置来是否使用supportsPassive？

**Comment by awmleer** [comment]
React 目前还不支持 Shadow DOM，请不要在项目中使用
