### ISSUE TITLE
希望为PickerView增加鼠标滚轮支持

### ISSUE THREAD

**Issue by shusiwei** [ant-design/ant-design-mobile#5024]
### Version of antd-mobile

v5.7

### Description

有的人在PC端鼠标滑动不来，硬逼着我在PC端支持鼠标滚轮代替滑动

**Comment by shusiwei** [comment]
或者暴露个钩子出来，就也可以自己写事件

**Comment by awmleer** [comment]
理论上是可行的，use-gesture 提供了 `useWheel`，不知道会不会对包体积有很大的影响

**Comment by shusiwei** [comment]
原来是使用mac笔记本的情况下没有鼠标支持下确实不太方便

**Comment by shusiwei** [comment]
![image](https://user-images.githubusercontent.com/6745335/162100967-25560996-c6a3-43ea-9cba-3973ab9f6f35.png)
已经实现了，简单复用了一下useDrag里的方法

**Comment by awmleer** [comment]
Mask 组件里应该已经默认 disableBodyScroll 了，所以应该是不需要处理的，可以试试看？

**Comment by shusiwei** [comment]
> Mask 组件里应该已经默认 disableBodyScroll 了，所以应该是不需要处理的，可以试试看？

现在使用在Popup组件内没有问题，但如果应用场景只是常规布局（就像我们的示例中的一样）的话就不好办了。

**Comment by awmleer** [comment]
噢的确～那直接复用 `useLockScroll` 这个 hook 就可以了

**Comment by awmleer** [comment]
噢不对，`useLockScroll` 是只要组件渲染了，就会 lock 掉页面的滚动，但是实际上我们需要的是，如果用户没有在和 PickerView 进行交互，是不应该 lock 页面滚动的

**Comment by shusiwei** [comment]
#5052

**Comment by shusiwei** [comment]
PR #5052

**Comment by shusiwei** [comment]
> 稍晚一些我再看下（估计几天之内），看起来改动有点大～

嗯嗯
