### ISSUE TITLE
Form.Item 中通过onClick调用组件形式的值无法清除

### ISSUE THREAD

**Issue by shusiwei** [ant-design/ant-design-mobile#5025]
### Version of antd-mobile

5.7.2

### What is this feature about?

![image](https://user-images.githubusercontent.com/6745335/161363265-f0a9ed7a-24f4-476b-a7e8-1addc6b72420.png)
上图中的值无法清除，尝试使用SwipeAction组件清除，清除后Form.Item中的onClick事件无响应。

也尝试使用使用children给出onClear事件，可以清除，但是调用onClick无法阻止冒泡，导致Form.Item的onClick事件再次响应弹出控件。

Form.Array有没有办法提供内置的clear方法？现在清除Form.Array中的值非常复杂。

**Comment by crazyair** [comment]
那这样的话点击事件放在 Form.Item 上真的有必要吗？ @awmleer

**Comment by yangdepp** [comment]
由于没有完整的复现demo，我没太懂你的描述，你看看这里这个清除时间的demo能解决你的问题不？当然你最好提供一个复现demo，这样解决起来快一些。

**Comment by awmleer** [comment]
> 那这样的话点击事件放在 Form.Item 上真的有必要吗？ @awmleer

Form.Item 只是提供了 `onClick` 事件，但是并没有强制用户使用（虽然我们推荐这样做，因为视觉效果会比较好），完全可以自己实现一个自定义表单字段组件，然后在这个自定义组件中去处理 `onClick`

```jsx
<Form.Item>
  <MyField />
</Form.Item>
```

function MyField() {
  return (
    <div onClick={...}>...</div>
  )
}

**Comment by shusiwei** [comment]
提供一个demo:
https://codesandbox.io/s/loving-panka-c938ho?file=/src/App.tsx

**Comment by yangdepp** [comment]
> 提供一个demo: https://codesandbox.io/s/loving-panka-c938ho?file=/src/App.tsx click清除无法阻止事件冒泡的，使用SwipeAction清除值造成无响应
> 
> 另外Form.Array中的数据清除有能不能提供内置的方法

你写的代码有些冗余，可以读读`Form`的文档，我给你改了一版 [https://codesandbox.io/s/charming-snow-undwl7?file=/src/App.tsx](url)

**Comment by shusiwei** [comment]
> > 提供一个demo: https://codesandbox.io/s/loving-panka-c938ho?file=/src/App.tsx click清除无法阻止事件冒泡的，使用SwipeAction清除值造成无响应
> > 另外Form.Array中的数据清除有能不能提供内置的方法
> 
> 你写的代码有些冗余，可以读读`Form`的文档，我给你改了一版 https://codesandbox.io/s/charming-snow-undwl7?file=/src/App.tsx

确实有点，不过我那写的目的是由于From.Array中的值好像没有较好的动手修改方式

**Comment by yangdepp** [comment]
你可以提供下 `From.Array`的示例demo，写一下你感觉不好手动修改的地方在哪里，我从你第一个demo里面，没看到 `From.Array`所以`get`不到你的点。

**Comment by shusiwei** [comment]
感谢各位，问题解决了！虽然Form.Item中元素的click冒泡不能阻止，但还有解决方式。谢谢各位！
