### ISSUE TITLE
Form组件中footer自动执行submit事件

### ISSUE THREAD

**Issue by shusiwei** [ant-design/ant-design-mobile#5026]
### Version of antd-mobile

5.7.2

### Operating system and its version

iOS

### Sandbox to reproduce

https://codesandbox.io/embed/sharp-sammet-uncs9t?fontsize=14&hidenavigation=1&theme=dark

### What happened?

点击显示提交按钮后，自动执行了一个显示后的提交按钮中的submit事件,如果提交按钮没有type属性则不执行

**Comment by awmleer** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type

<img width="810" alt="image" src="https://user-images.githubusercontent.com/16526078/161365861-c7f268b7-a724-410b-9e9d-b654577bf4d1.png">

如果 Button 没有设置 type 属性的话，也会被当作 submit，所以理论上这样可以解决这个问题：

```
<Button type="button" />
```

但是我在你发的 codesandbox 里试了一下，发现依旧还是有问题，怀疑是底层的 rc-form 的问题 🤔

**Comment by yangdepp** [comment]
如果你的目标需求是：想要在切换提交按钮显示隐藏状态时，不自动提交`form`表单
要把提交按钮上的 `type={"submit"}`去掉，然后自定义提交事件，绑定`form`后，依然可以收集表单数据


```tsx
import React from "react";
import { Button, Form, Input } from "antd-mobile";

export default function App() {
  const [type, setType] = React.useState(false);
  const [form] = Form.useForm();
  const footer =
    type === false ? (
      <React.Fragment>
        <Button onClick={submit} color="primary">
          提交
        </Button>
        <Button onClick={() => setType(true)}>隐藏提交按钮</Button>
      </React.Fragment>
    ) : (
      <Button onClick={() => setType(false)}>显示提交按钮</Button>
    );

  function submit() {
    const values = form.getFieldsValue();
    console.log(values, type);
  }

  return (
    <div className="App">
      <Form footer={footer} form={form}>
        <Form.Item name="name">
          <Input placeholder="placeholder" />
        </Form.Item>
      </Form>
    </div>
  );
}


```

**Comment by yangdepp** [comment]
另外这个样例我在 `antd`的表单上也试了一下，只要提交按钮绑定`htmlType="submit"`，都会在切换显示隐藏状态时触发表单提交的`onFinish`，目前不知道这是不是预期行为，如果不是，推测应该是`rc-form`的bug。

**Comment by awmleer** [comment]
有 `htmlType="submit"` 的话，的确是会触发 Form 的 `onFinish`，这个是预期行为的

只不过我试了一下，遇到了非常玄学的问题，可以看[这个 codesandbox](https://codesandbox.io/s/bold-lumiere-x4qj7r?file=/src/App.tsx)

```jsx
// 这种模式是异常的
const footer1 =
  type === false ? (
    <React.Fragment>
      <Button type="submit" color="primary">
        提交
      </Button>
      <Button type="button" onClick={() => setType(true)}>
        隐藏提交按钮
      </Button>
    </React.Fragment>
  ) : (
    <Button type="button" onClick={() => setType(false)}>
      显示提交按钮
    </Button>
  );

// 这种模式是正常的
const footer2 = (
  <Button type="button" onClick={() => setType(false)}>
    测试一下
  </Button>
);
```

**Comment by yangdepp** [comment]
> 有 `htmlType="submit"` 的话，的确是会触发 Form 的 `onFinish`，这个是预期行为的
> 
> 只不过我试了一下，遇到了非常玄学的问题，可以看[这个 codesandbox](https://codesandbox.io/s/bold-lumiere-x4qj7r?file=/src/App.tsx)
> 
> ```js
> // 这种模式是异常的
> const footer1 =
>   type === false ? (
>     <React.Fragment>
>       <Button type="submit" color="primary">
>         提交
>       </Button>
>       <Button type="button" onClick={() => setType(true)}>
>         隐藏提交按钮
>       </Button>
>     </React.Fragment>
>   ) : (
>     <Button type="button" onClick={() => setType(false)}>
>       显示提交按钮
>     </Button>
>   );
> 
> // 这种模式是正常的
> const footer2 = (
>   <Button type="button" onClick={() => setType(false)}>
>     测试一下
>   </Button>
> );
> ```

还有一个玄学问题，我这么写，就在切换显示隐藏的时候，就不会触发onFinish，链接：https://codesandbox.io/s/admiring-dirac-k5b9ps?file=/src/App.tsx

```tsx

import React from "react";
import { Button, Form, Input } from "antd-mobile";

export default function App() {
  const [type, setType] = React.useState(false);
  // 这种模式切换显示隐藏不会触发onFinish，除非点击提交按钮
  const footer = (
    <>
      {type === false && (
        <Button type="submit" color="primary">
          提交
        </Button>
      )}
      <Button type="button" onClick={() => setType(!type)}>
        {type ? "显示" : "隐藏"}提交按钮
      </Button>
    </>
  );

  function submit(values: any) {
    console.log(values, type);
  }

  return (
    <div className="App">
      <Form footer={footer} onFinish={submit}>
        <Form.Item name="name">
          <Input placeholder="placeholder" />
        </Form.Item>
      </Form>
    </div>
  );
}

```

**Comment by yangdepp** [comment]
猜测 点击 `显示提交按钮`的时候，基于未知的原因，触发点击了 `提交` 按钮，所以触发了`onFinish`
我随便改了点结构就不会复现这个问题了，好奇怪~

```tsx
  const footer =
    type === false ? (
      <React.Fragment>
        {" 这里随便加点什么都不会触发"}
        <Button type="submit" color="primary">
          提交
        </Button>
        <Button type="button" onClick={() => setType(true)}>
          隐藏提交按钮
        </Button>
      </React.Fragment>
    ) : (
      // {" 这里随便加点什么都不会触发"}
      <Button type="button" onClick={() => setType(false)}>
        显示提交按钮
      </Button>
    );

```

**Comment by awmleer** [comment]
莫非……是 React 渲染机制导致的？`显示提交按钮` 和 `提交` 正好位置是对应着的，所以……在重渲染的过程中，React 是做了元素的更新而不是销毁重建？

**Comment by awmleer** [comment]
验证了一下，确实是这样的：
![image](https://user-images.githubusercontent.com/16526078/161376111-7fff65f5-eaa7-4f58-9caa-a8077be79585.png)

**Comment by awmleer** [comment]
给三个 Button 加上 `key` 也可以解决这个问题：https://codesandbox.io/s/happy-sun-muiipl?file=/src/App.tsx

**Comment by shusiwei** [comment]
问题解决，感谢大家分析原因！
