### ISSUE TITLE
FormItem 上的 RuleConfig 设置 validateTrigger 失效

### ISSUE THREAD

**Issue by nervouself** [ant-design/ant-design-mobile#5027]
### Version of antd-mobile

5.9.4

### Operating system and its version

Others

### Browser and its version

chrome 99.0

### What happened?

```jsx
<Form validateTrigger="onChange">
  <Form.Item
    name="name"
    label="name"
    rules={[
      {
        validateTrigger: 'onBlur',
        validator: (_: any, value: string) => {
          return Promise.reject(new Error('onBlur不正确'));
        },
      },
      {
        validateTrigger: 'onChange',
        validator: (_: any, value: string) => {
          return Promise.reject(new Error('onChange不正确'));
        },
      },
    ]}
  >
    <Input  />
  </Form.Item>
</Form>
```

这种情况下只有 "onChange不正确" 会触发，期望 onBlur 在 blur 时也会触发；validateTrigger 在 form 和 formItem 上设置效果都一样

**Comment by nervouself** [comment]
另试了下，直接在 Form 上加 validateTrigger="onBlur" 好像不管用了，加在 FormItem 上才好使，不是到是不是我本地操作的有问题

**Comment by nervouself** [comment]
> 另试了下，直接在 Form 上加 validateTrigger="onBlur" 好像不管用了，加在 FormItem 上才好使，不知道是不是我本地操作的有问题

实测 5.9.3 是好的，应该是默认 trigger 的这次改动引入的问题

**Comment by miracles1919** [comment]
@nervouself  加个这个 

```
<Form.Item
  // ...
  validateTrigger={['onBlur', 'onChange']}
</Form.Item>
```

**Comment by awmleer** [comment]
5.9.5应该修复了这个问题，可以升级试一下

**Comment by liuwei1025** [comment]
请问 `validateTrigger`都能取哪些值呢？文档上并没有这块儿的介绍
