### ISSUE TITLE
请教问题,使用官网TabBar例子在 React Native 中,发生错误.

### ISSUE THREAD

**Issue by wslw** [ant-design/ant-design-mobile#503]
#### 本地环境

- antd-mobile 版本：0.9.5
- 操作系统及其版本：Mac OS 10.12.1
- 浏览器及其版本：React Native 0.36
- 运行环境: IPHONE6 模拟器  9.3

#### 你做了什么？

 使用 TabBar 中的 TabBar.Item 

#### 你期待的结果是：

 像官网一样正常显示 

#### 实际上的结果：

运行时报错:
JSON value '{uri = "https://xxxx.xxx.xxx/xxx.png;";}'  of type NSMutableDictonary cannot be converted to an image. Only local files or data URIs are supported.

#### 部分源码 
`<TabBar.Item
                        icon={{ uri: 'https://zos.alipayobjects.com/rmsportal/UNQhIatjpNZHjVf.png;' }}
                        selectedIcon={{ uri: 'https://zos.alipayobjects.com/rmsportal/HLkBvJOKnmOfBPO.png' }}
                        title="口碑"
                        key="口碑"
                        badge={1}
                        selected={this.state.selectedTab === 'redTab'}
                        onPress={() => {
            this.setState({
              selectedTab: 'redTab',
            });
          }}
                        data-seed="logId1"
                    >`

**Comment by silentcloud** [comment]
@wslw react-native 官方现在不支持 `{uri: 'https://xxx'}` 这种形式，只能是 {uri: base64} 或者 reqiure 的形式，antd-mobile TabBar iOS 用的官方的 TabBarIOS

**Comment by leonardgithub** [comment]
antd-mobile组件还能在RN用吗？
