### ISSUE TITLE
Popover 的 content 内容较多时没有居中

### ISSUE THREAD

**Issue by KingAmo** [ant-design/ant-design-mobile#5030]
### Version of antd-mobile

5.8.1

### Operating system and its version

Others

### Sandbox to reproduce

https://codesandbox.io/s/amazing-glitter-idubc2?file=/src/App.tsx

### What happened?

Popover 组件的 content 内容较多时，content 没有居中

期望：内容正确居中

**Comment by jjkbb123** [comment]
const content = (
  <div
    style={{
      textAlign: "center"
    }}
  >
    Hello WorldHello WorldHello WorldHello WorldHello WorldHello WorldHello WorldHello WorldHello WorldHello WorldHello World
  </div>
)
可以考虑为content添加一个dom元素自己写样式

**Comment by jjkbb123** [comment]
const content = (<div style={{ textAlign: "center" }}>Hello WorldHello WorldHello WorldHello WorldHello WorldHello WorldHello WorldHello WorldHello WorldHello WorldHello World<\/div>)
考虑给content添加一个dom元素自己写样式吧

**Comment by awmleer** [comment]
这是默认行为，如果需要文字居中的话，是需要自己加一下样式的（可以看下楼上所说的）

**Comment by backstageman** [comment]
Popover 组件的 content 内容较多时，content 没有居中

期望：内容正确居中
