### ISSUE TITLE
webpack3.12.0打包出错

### ISSUE THREAD

**Issue by HSQCoollaughing** [ant-design/ant-design-mobile#5031]
### Version of antd-mobile

5.9.5

### Operating system and its version

iOS

### Browser and its version

ios

### Sandbox to reproduce

none

### What happened?

webpack3.12.0版本
![image](https://user-images.githubusercontent.com/29752874/161474086-b99e44fb-fa2d-4374-b2be-ea6dd7d70256.png)

### Relevant log output

```shell
none
```

**Comment by miracles1919** [comment]
能把项目打个包上传一下么？ 这样方便排查 ~
