### ISSUE TITLE
Picker组件没法自定义数据源的key

### ISSUE THREAD

**Issue by atom-shanghai** [ant-design/ant-design-mobile#5032]
### What is this feature about?

Picker组件，比如要弄个国际电话区号的下拉，没法自定义数据源的key，组件应该是自动拿value作为key。但比如美国和加拿大的区号都是1，这个时候会提示key重复

**Comment by awmleer** [comment]
get，那看起来可以让 `PickerItem` 额外加个属性 `key?: string | number`

**Comment by 1247748612** [comment]
> get，那看起来可以让 `PickerColumnItem` 额外加个属性 `key?: string | number`

不能用key，react会管理key属性

**Comment by awmleer** [comment]
> 不能用key，react会管理key属性

哈？

**Comment by 1247748612** [comment]
> > 不能用key，react会管理key属性
> 
> 哈？

看错了😩

**Comment by yaogengzhu** [comment]
我帮忙加下！🔨
