### ISSUE TITLE
首页这两个菜单 hover 无效

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#5036]
<img width="513" alt="图片" src="https://user-images.githubusercontent.com/507615/161884775-8744be72-557b-48de-9ed5-fbfa3c60329a.png">

目测是 z-index 问题。

**Comment by awmleer** [comment]
4551473 这个 commit 调整之后就不会存在这个问题了，还顺便解决了一下小屏幕下左右溢出的问题（还没发布）
