### ISSUE TITLE
v2迁移v5包读取异常

### ISSUE THREAD

**Issue by BloodNoteII** [ant-design/ant-design-mobile#5039]
### Version of antd-mobile

5.9.5

### Description

项目启动报错Module not found: Can't resolve 'antd-mobile/es/button'，v5项目应该是/es/component/button吧

**Comment by awmleer** [comment]
是 umi 项目么？
有没有配 babel-plugin-import？

**Comment by awmleer** [comment]
![image](https://user-images.githubusercontent.com/16526078/162112575-fdf26cc2-a9a7-4ab3-a1fd-42cefcb6f59b.png)

**Comment by BloodNoteII** [comment]
babel-plugin-import 配置问题已修改
