### ISSUE TITLE
Form.Subscribe 在调用 children render function 的时候，自动把 values 解构掉

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#5043]
### Version of antd-mobile

5.10.0

### What is this feature about?

**下个大版本**升级的时候，可以优化一下，先记在这里

demo 链接：https://codesandbox.io/s/clever-cannon-0imxfb?file=/src/App.tsx:684-879

现在：

```jsx
<Form.Subscribe to={[["plants", index, "taskStatus"]]}>
  {(values) => {
    const taskStatus = values.plants[index].taskStatus;
    // ...
  })
</From.Subscribe>
```

未来：

```jsx
<Form.Subscribe to={[["plants", index, "taskStatus"]]}>
  {(items) => {
   const [taskStatus] = items
    // ...
  })
</From.Subscribe>
```

**Comment by crazyair** [comment]
https://github.com/react-component/field-form/pull/405

**Comment by awmleer** [comment]
@crazyair 如果有了 `useWatch`，可以改写一下上面的例子看看么？

**Comment by crazyair** [comment]
> @crazyair 如果有了 `useWatch`，可以改写一下上面的例子看看么？

还没发版，理论上是支持的，可以等发版试下。

**Comment by crazyair** [comment]
@awmleer https://github.com/ant-design/ant-design-mobile/pull/5074

**Comment by awmleer** [comment]
https://github.com/ant-design/ant-design-mobile/issues/5275#issuecomment-1151175123

**Comment by awmleer** [comment]
后面废弃掉 Form.Subscribe，这个 issue 关闭掉了 #5317
