### ISSUE TITLE
支持 React 18

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#5044]
### Version of antd-mobile

5.10.0

### Description

一些项目已经开始升级到 React 18 了，而新创建的项目（特别是 create-react-app 创建的）应该已经默认是 React 18 了，所以 antd-mobile 也需要着手对 React 18 进行一些适配改造

[How to Upgrade to React 18](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html)

[React v18.0](https://reactjs.org/blog/2022/03/29/react-v18.html)

当前阶段的支持只能是确保在 React 18 环境下正常的运行，但还是不能在 antd-mobile 中依赖任何 React 18 新增的特性（除非进行了特殊的环境判断并且有 fallback 逻辑），在我们基本确保了在 React 18 下兼容性是正常的之后，会把 package.json 中的 `peerDependencies` 进行调整，用户在 npm 或 yarn 安装时将不会再遇到报错

**Comment by Phil-Pu** [comment]
CascadePickerView在react 18下面无法立即渲染默认值，在react 17下面正常。

**Comment by awmleer** [comment]
https://github.com/facebook/react/issues/24347

**Comment by 329639010** [comment]
无法安装mobile，不兼容18

**Comment by xiaohaoo** [comment]
大约什么时候发布适配React 18呢

**Comment by awmleer** [comment]
PR 还在调整中，估计快了 https://github.com/ant-design/ant-design-mobile/pull/5046

**Comment by Scout-szz** [comment]
关注一下

**Comment by dingyanhe** [comment]
请问2.3.2版本有计划支持react18嘛

**Comment by awmleer** [comment]
> 请问2.3.2版本有计划支持react18嘛

没有
