### ISSUE TITLE
Toast.show 会清除之前的提示，这样处理特殊场景里会有问题。

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#5047]
### Version of antd-mobile

5.9.5

### Browser and its version

all

### Sandbox to reproduce

https://codesandbox.io/s/zealous-sea-yob75v?file=/src/App.tsx

### What happened?

特殊场景下：
1、请求接口成功，需要Toast提示（会不会有Toast提示，根据内部逻辑不同判断）
2、在请求接口，请求接口里有loading提示
3、这样，第一个请求接口成功的Toast提示不会显示，直接被后面接口请求的loading提示覆盖了。
注：接口请求不能在Toast.show的afterClose事件里做，因为两个是不同的公共组件。

期望：Toast.show方法支持显示时，提供该提示是否自动被后面的Toast.show提示覆盖的参数配置
如：
`Toast.show({
                content: '这条提示，后面有其它的Toast.show提示时，不会被覆盖，3秒后才会消失',
                duration: 3000,
               // 是否自动被后面的Toast.show提示覆盖
               isCover: false,
              })`

**Comment by awmleer** [comment]
现在的 toast 之所以设计成是单例的，是因为从设计上来看，一个页面内是不能同时展示两个 toast 的，并不是技术上做不了

感觉你的场景并不是很适合用 toast 组件，更像是需要类似于 [snackbar](https://www.material.io/components/snackbars) 这样的组件
