### ISSUE TITLE
TextArea组件在一些旧版安卓系统上双行显示时右侧会出现一条黑线

### ISSUE THREAD

**Issue by zhengxiangqi** [ant-design/ant-design-mobile#5049]
### Version of antd-mobile

5.9.2

### Operating system and its version

Android

### Browser and its version

机型：华为nova2s，系统：Android9 ，详细信息：Mozilla/5.0 (Linux; Android 9; HWI-AL00 Build/HUAWEIHWI-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/79.0.3945.116 Mobile Safari/537.36

### What happened?

问题：TextArea组件在一些旧版安卓系统上双行显示时右侧会出现一条黑色竖线，单行或超过双行显示时则黑色竖线消失。
期望：TextArea组件无论显示成几行，右侧都不应该出现黑色竖线。

**Comment by awmleer** [comment]
提供一下截图看看？

**Comment by zhengxiangqi** [comment]
截图中联行号位置





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 卡晨 ***@***.***&gt;
发送时间: 2022年4月11日 18:46
收件人: ant-design/ant-design-mobile ***@***.***&gt;
抄送: ZhengXiangQi ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ant-design/ant-design-mobile] TextArea组件在一些旧版安卓系统上双行显示时右侧会出现一条黑线 (Issue #5049)





 
提供一下截图看看？

**Comment by zhengxiangqi** [comment]
奇怪，发件箱里面看正文确实有图片呢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-mobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-mobile] TextArea组件在一些旧版安卓系统上双行显示时右侧会出现一条黑线 (Issue #5049)





   
只看到一句 "发自我的iPhone"

**Comment by wzl13211** [comment]
同问，有解决方法吗
