### ISSUE TITLE
dialog对话框中超长文本演示问题

### ISSUE THREAD

**Issue by honghong999** [ant-design/ant-design-mobile#5054]
### Version of antd-mobile

5.0.0

### Description

![微信图片_20220412100655](https://user-images.githubusercontent.com/73335348/162864681-31b562ad-8859-4510-a775-9e28e142993e.png)
dialog对话框中超长文本演示中没有关闭弹框的按钮，点击遮罩层也不能关闭，内容不全

**Comment by yaogengzhu** [comment]
是不是版本问题？升级看看呢？目前版本是v5.10.1..   `closeOnMaskClick` 是否支持点击遮罩关闭对话框 默认为 `false`

**Comment by awmleer** [comment]
看你文档的截图是 5.0.0 版本的，升级一下应该就没有这个问题了，我记得我后来修复过

**Comment by honghong999** [comment]
> 是版本问题吗？升级看看呢？当前版本是v5.10.1.. `closeOnMaskClick`是否默认支持遮住点击关闭罩框为`false`

新版本里面没有超长文本这个啦，哈哈，这个网页是之前收藏的，就是这两天学习用到了，偶然发现了这个问题😭

**Comment by honghong999** [comment]
> 你看文档的截图是5.0.0版本的，一下应该就没有这个问题了，我记得我后来修复过

看到了看到了，哈哈哈，谢谢
