### ISSUE TITLE
form表单的css属性如何设置

### ISSUE THREAD

**Issue by LBjadehare** [ant-design/ant-design-mobile#5064]
### Version of antd-mobile

^5.0.0-beta.14

### Description

https://mobile.ant.design/zh/components/form#css-%E5%8F%98%E9%87%8F
![image](https://user-images.githubusercontent.com/69783678/163154803-7e59d5cb-728f-436f-96da-517bafc5432c.png)
该属性没有实例，不知道如何配置

**Comment by yaogengzhu** [comment]
参考指南中 如何使用 CSS 变量
https://mobile.ant.design/zh/guide/css-variables

**Comment by LBjadehare** [comment]
> 参考指南中 如何使用 CSS 变量 https://mobile.ant.design/zh/guide/css-variables

![image](https://user-images.githubusercontent.com/69783678/163175329-2f263040-171a-4aff-a0f8-be7afb9dd161.png)
'--border-top':'0px'和'--border-top':'none'的行内都没有生效，那个上边框还在，我在<Form>和<Form.Item>设置都不行

**Comment by awmleer** [comment]
@LBjadehare 那写一个复现 demo 吧：

https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by LBjadehare** [comment]
> @LBjadehare 那写一个复现 demo 吧：
> 
> https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

codesandbox引入没问题🤣而且我项目中使用的<Radio />也无法取消选择😨，不知道是不是项目中有其他引入导致的冲突？
![image](https://user-images.githubusercontent.com/69783678/163306193-a0ce1a96-b8ec-46be-a274-36b42d0b2a63.png)

**Comment by awmleer** [comment]
你本地的 antd-mobile 是最新版本的么？

**Comment by LBjadehare** [comment]
> 你本地的 antd-mobile 是最新版本的么？

    "antd-mobile": "^5.0.0-beta.14",

**Comment by awmleer** [comment]
你发的这个是版本范围，需要提供准确的版本

**Comment by LBjadehare** [comment]
> 你发的这个是版本范围，需要提供准确的版本

PS E:\HY\平台\watersBackground> npm list antd-mobile
watersBackground@ E:\HY\平台\watersBackground
+-- @umijs/preset-react@1.8.29
| `-- @umijs/plugin-antd@0.12.1
|   `-- antd-mobile@2.3.4
`-- antd-mobile@5.0.0-beta.27

**Comment by awmleer** [comment]
看起来是 `5.0.0-beta.27` 这个版本，升级到最新版吧，直接在项目中

```
npm install --save antd-mobile
```

**Comment by LBjadehare** [comment]
> 看起来是 `5.0.0-beta.27` 这个版本，升级到最新版吧，直接在项目中
> 
> ```
> npm install --save antd-mobile
> ```

确实是这个问题，十分感谢你的回答！😊👍

**Comment by LBjadehare** [comment]
> 参考指南中 如何使用 CSS 变量 https://mobile.ant.design/zh/guide/css-variables

谢谢你的回答😊
