### ISSUE TITLE
Swiper组件在侧滑的同时，用另一只手指点击卡片，会导致侧滑卡住

### ISSUE THREAD

**Issue by Gong-Elory** [ant-design/ant-design-mobile#5066]
### Version of antd-mobile

5.10.2

### Operating system and its version

iOS

### What happened?

测滑的那个手指在屏幕上，用另外一只手指点击屏幕，就会必现这种问题。

**Comment by Gong-Elory** [comment]
![origin_img_v2_71f5ec7b-496d-4131-bf95-663202dd2abg](https://user-images.githubusercontent.com/22674497/163170340-fb655f37-97fd-406f-bcbc-47dc4b9abbc4.jpg)必现

**Comment by Gong-Elory** [comment]
![origin_img_v2_cae83174-de42-48c0-a679-4f068e7e42ag](https://user-images.githubusercontent.com/22674497/163170593-194ae256-d95a-4dfb-880a-6ecb32c64ada.jpg)
必现，复现注意：测滑的那个手指依然在屏幕上，用另外一只手指点击屏幕

**Comment by awmleer** [comment]
我复现出来了，感觉是另一只手指点击后被认定为了拖拽结束，所以就手势中断了，估计是底层库的逻辑，暂时不太好解决

在卡住之后，松开两只手指，再重新进行拖拽的话是可以正常再进行交互的，所幸问题的严重性还不算高

**Comment by Gong-Elory** [comment]
> 我复现出来了，感觉是另一只手指点击后被认定为了拖拽结束，所以就手势中断了，估计是底层库的逻辑，暂时不太好解决
> 
> 在卡住之后，松开两只手指，再重新进行拖拽的话是可以正常再进行交互的，所幸问题的严重性还不算高

那后续有计划修复吗？

**Comment by awmleer** [comment]
我先标个 help wanted 吧，推测是 use-gesture 的问题，不知道有没有社区朋友可以帮忙确定一下，然后给 use-gesture 写个复现 demo 提个 issue

**Comment by jacob-lcs** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/src/components/swiper/swiper.tsx#L181-L202

目前来看是 `use-gesture` 库提供的 `preventScroll` 属性导致的，`SwipeAction` 组件也存在同样的问题，如果把 `preventScroll` 去掉或者设置为 `false` 即可解决该问题。

另外从代码上看，`SwipeAction` 和 `Swiper` 组件都是对水平方向设置了 `preventScroll: true`，而没有对垂直方向做处理，请问是为了应对什么使用场景呢？ @awmleer

**Comment by awmleer** [comment]
@jacob-lcs preventScroll 的文档：https://use-gesture.netlify.app/docs/options/#preventscroll

**Comment by jacob-lcs** [comment]
https://github.com/pmndrs/use-gesture/issues/485
