### ISSUE TITLE
使用Form组件渲染Picker组件后面的紧跟的Input组件不见了

### ISSUE THREAD

**Issue by tylerpanpan** [ant-design/ant-design-mobile#5071]
### Version of antd-mobile

5.7.2+所有版本

### Browser and its version

Chrome

### What happened?

<img width="388" alt="image" src="https://user-images.githubusercontent.com/7157473/163320335-24a610ec-be12-4967-bb13-44a2f301fcf6.png">
这是代码
<img width="396" alt="image" src="https://user-images.githubusercontent.com/7157473/163320336-beb7abec-014e-4a52-8068-08680de521ae.png">
本来应该渲染手机input，然后邮箱input，现在少了东西

**Comment by qiyexuelei** [comment]
可以通过  this.formRef.current?.setFieldsValue去改变表单的值

onConfirm={(val, extend) => {
            debugger
            this.formRef.current?.setFieldsValue({ property_right_type: extend.items[0].label })
            this.setState({
              property_right_type_id: extend.items[0].value
            })

          }}

**Comment by tylerpanpan** [comment]
> 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/7157473/163322098-04096ae8-15fa-4fcc-aa99-94a905c6b765.png">
是我的手机输入框这个表单都不见了

**Comment by tylerpanpan** [comment]
> 

是我的手机输入框这个表单都不见了
<img width="457" alt="image" src="https://user-images.githubusercontent.com/7157473/163322373-db006341-7dea-41a3-8920-4bb4bbaa3fbe.png">

**Comment by qiyexuelei** [comment]
我不是你这种写法，我没解决你的问题，可以参考我这种写法
/* eslint no-dupe-keys: 0, no-mixed-operators: 0 */
import React from 'react';
import { Button,Card,TextArea,ImageUploader,Image,Form,Input,Toast,Picker,DatePicker,DotLoading} from 'antd-mobile';
import { UnorderedListOutline,RightOutline} from 'antd-mobile-icons'
import { Select } from 'antd';
import { connect } from 'dva';
import styles from './index.less'
import ip from '../../config/IpManager'
import postQuery from '../../utils/postQuery'; 
import moment from "moment";
import request from '../../utils/request'; // get
const item = {
  avatar:
    'https://images.unsplash.com/photo-1548532928-b34e3be62fc6?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ',
  name: 'Novalee Spicer',
  description: 'Deserunt dolor ea eaque eos',
}
const { Option } = Select;
const now = new Date()
class peopleAdd extends React.Component {
  constructor(props) {
    super(props);
    const { query = {} } = props.location;
    this.buildid =query.id
    this.formRef = React.createRef()
    this.state = {
      detail:{
      },
      hasMore: true,
      url:'https://images.unsplash.com/photo-1620476214170-1d8080f65cdb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3150&q=80',
      height: document.documentElement.clientHeight ,
      visiblesex:false,
      visiblecreatetime:false,
      visiblenationType:false,
      visiblemaritalType:false,
      visiblenationType:false,
      visiblepoliticalType:false,
      visibleeducationType:false,
      visiblereligionType:false,
      visibleoccupationType:false,
      sexOption:[],//性别
      nativeTypeOption:[],//民族
      maritalTypeOption:[],
      politicalTypeOption:[],
      politicalTypeOption:[],
      educationTypeOption:[],
      religionTypeOption:[],
      occupationTypeOption:[],
      fileList:[]
    };
  }


  componentDidMount() {
    this.getDic("424")//性别
    this.getDic("425")//民族
    this.getDic("426")//婚姻状况
    this.getDic("427")//政治
    this.getDic("428")//学历
    this.getDic("415")//宗教
    this.getDic("429")//职业类型
  }
 
  toFloor=(item)=>{
    Toast.show(item.bldName)
  }
  getDic=(dictType)=>{
    let stepsUrl = `${ip.qysServer + '/dict/tree/' + dictType}`;
    //获取字典
    request(stepsUrl).then((res) => {
        if (res.data && res.data.length > 0) {
          if(dictType=="424"){
            
            var newarray =this.convertArray(res.data[0].childList)
            this.setState({
              sexOption:newarray
            })
            
          }else if(dictType=="425"){
            var newarray =this.convertArray(res.data[0].childList)
            this.setState({
              nativeTypeOption:newarray
            })
          }else if(dictType=="426"){
            this.setState({
              maritalTypeOption:res.data[0].childList
            })
          }else if(dictType=="427"){
            this.setState({
              politicalTypeOption:res.data[0].childList
            })
          }else if(dictType=="428"){
            this.setState({
              educationTypeOption:res.data[0].childList
            })
          }else if(dictType=="415"){
            this.setState({
              religionTypeOption:res.data[0].childList
            })
          }else if(dictType=="429"){
            this.setState({
              occupationTypeOption:res.data[0].childList
            })
          }
           
        }
        
    })
  }
    edit=()=>{
    


    }
    setVisible=()=>{
      this.setState({
         visiblesex:!this.state.visiblesex
      })
    }
    setVisiblecreatetime=()=>{
      this.setState({
        visiblecreatetime:!this.state.visiblecreatetime
      })
    }
    setVisiblenationType=()=>{
      this.setState({
        visiblenationType:!this.state.visiblenationType
      })
    }
    setVisiblemaritalType=()=>{
      this.setState({
        visiblemaritalType:!this.state.visiblemaritalType
      })
    }
    setVisibleeducationType=()=>{
      this.setState({
        visibleeducationType:!this.state.visibleeducationType
      })
    }
    setVisiblepoliticalType=()=>{
      this.setState({
        visiblepoliticalType:!this.state.visiblepoliticalType
      })
    }
    setVisiblereligionType=()=>{
      this.setState({
        visiblereligionType:!this.state.visiblereligionType
      })
    }
    setVisibleoccupationType=()=>{
      this.setState({
        visibleoccupationType:!this.state.visibleoccupationType
      })
    }
    //提交
    submit=()=>{
      var value=this.formRef.current?.getFieldsValue()
      let params = value
      params.gender_type_id = this.state.gender_type_id
      params.nation_type_id = this.state.nation_type_id
      params.marital_type_id = this.state.marital_type_id
      params.political_type_id = this.state.political_type_id
      params.education_type_id = this.state.education_type_id
      params.religion_type_id = this.state.religion_type_id
      params.occupation_type_id = this.state.occupation_type_id
      
      debugger
      postQuery(`${ip.qysServer + '/crud/insert/bdPerson'}`, params).then((res) => {
        
        if(res.code=='200'){
          // code: 200
          // data: 1
          // msg: ""
          Toast.show("新增成功")
          history.back()
        }else{
          Toast.show("新增失败")
        }
        
      })
    }
    convertArray=(objArr)=>{
      var newobjArr = [...objArr];
      // 旧 key 到新 key 的映射
      const keyMap = {
        dictValue: "label",
        dictKey: "value",
      };
      for (let i = 0; i < newobjArr.length; i++) {
        let obj = newobjArr[i];
        for (let key in obj) {
          let newKey = keyMap[key];
          if (newKey) {
            obj[newKey] = obj[key];
          }
        }
      }
      console.log(newobjArr)
      return newobjArr;
      
    }
    setFileList=()=>{

    }
    upload=()=>{

    }
  render() {
    const {bldUnderFloorTotal}=this.state;
    console.log(this.formRef.current,'==============')
    return (
      <div >
     
      
          <div style={{paddingLeft:5,paddingRight:5}}>
              <Card
                  style={{ borderRadius: '2px',alignContent:'center'}}
                >
                <ImageUploader
                  value={this.state.fileList}
                  onChange={this.setFileList}
                  upload={this.upload}
                />
              </Card>
              <Form    
                    ref={this.formRef} 
                    layout='horizontal' mode=''  
                    footer={
                    <Button block type='submit' color='primary' size='large' onClick={this.submit}>
                      提交
                    </Button>
              }>
               
                        <Form.Item 
                          name='p_name' 
                          label='姓名'
                          className={styles.formitemstyle} 
                          rules={[{ required: true, message: '姓名不能为空!' }]} >
                            <Input placeholder='请输入' style={{ '--text-align': 'right',"--font-size":15 }} />
                        </Form.Item>
                     
                        <Form.Item 
                            name='gender_type' 
                            label='性别' 
                            className={styles.formitemstyle} 
                            onClick={() => {this.setVisible()}}
                        >
                            <Input   style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
                        </Form.Item>
                        
                        <Form.Item 
                            name='birthday' 
                            label='出生日期'
                            className={styles.formitemstyle} 
                            onClick={() => {this.setVisiblecreatetime()}}
                            > 
                            <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
                        </Form.Item>
                        <Form.Item 
                            name='nation_type' 
                            label='民族'  
                            className={styles.formitemstyle} 
                            onClick={() => {this.setVisiblenationType()}}
                            > 
                            <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
                        </Form.Item>
                        <Form.Item  
                            name='phone_num_list' 
                            label='手机号码'
                            className={styles.formitemstyle} 
                            >
                            <Input  style={{ '--text-align': 'right',"--font-size":15 }} type="number"/>
                        </Form.Item>
                        <Form.Item 
                            name='marital_type' 
                            label='婚姻状况'
                            className={styles.formitemstyle}   
                            onClick={() => {this.setVisiblemaritalType()}}
                            > 
                            <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
                        </Form.Item>
                        <Form.Item 
                            name='political_type' 
                            label='政治面貌'  
                            className={styles.formitemstyle} 
                            onClick={() => {this.setVisiblepoliticalType()}}
                            > 
                            <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
                        </Form.Item>
                        <Form.Item 
                            name='education_type' 
                            label='文化程度'  
                            className={styles.formitemstyle} 
                            onClick={() => {this.setVisibleeducationType()}}
                            > 
                            <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
                        </Form.Item>
                        <Form.Item 
                            name='religion_type' 
                            label='宗教信仰'  
                            className={styles.formitemstyle} 
                            onClick={() => {this.setVisiblereligionType()}}
                            > 
                            <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
                        </Form.Item>
                        <Form.Item 
                            name='occupation_type' 
                            label='职业类型'  
                            className={styles.formitemstyle} 
                            onClick={() => {this.setVisibleoccupationType()}}
                            > 
                            <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
                        </Form.Item>
                        
                
                        <Form.Item 
                            name='native_place' 
                            label='籍贯'
                            className={styles.formitemstyle} 
                            >
                            <TextArea
                                    placeholder='请输入籍贯'
                                    onClear={true}
                                    style={{ '--text-align': 'right',"--font-size":15}}
                                    autoSize={{ minRows: 3, maxRows: 5 }}
                              />
                        </Form.Item>
                        <Form.Item 
                            name='residence_addr' 
                            label='户籍地址'   
                            className={styles.formitemstyle} 
                            >
                            <TextArea
                                placeholder='请输入户籍地址'
                                style={{ '--text-align': 'right',"--font-size":15}}
                                autoSize={{ minRows: 3, maxRows: 5 }}
                              />
                        </Form.Item>
                        <Form.Item 
                            name='current_addr' 
                            label='现居住地'   
                            className={styles.formitemstyle} >
                            <TextArea
                                placeholder='请输入现居住地址'
                                style={{ '--text-align': 'right',"--font-size":15}}
                                autoSize={{ minRows: 3, maxRows: 5 }}
                              />
                        </Form.Item>
                     
                        <Picker
                            columns={[
                              this.convertArray(this.state.sexOption)
                            ]}
                            visible={this.state.visiblesex}
                            onClose={() => {
                              this.setVisible()
                            }}
                            onConfirm={(val, extend) => {
                              debugger
                              this.formRef.current?.setFieldsValue({gender_type:extend.items[0].label})
                              this.setState({
                                gender_type_id:extend.items[0].value
                              })

                            }}
                          />
                        <DatePicker
                          title='时间选择'
                          visible={this.state.visiblecreatetime}
                          onClose={() => {
                            this.setVisiblecreatetime()
                          }}
                          max={now}
                          min={new Date('1900-01-01')}
                          onConfirm={val => {
                            this.formRef.current?.setFieldsValue({birthday:moment(val.toDateString()).format('YYYY-MM-DD') })
                          }}
                        />
                        <Picker
                            columns={[
                              this.convertArray(this.state.nativeTypeOption)
                            ]}
                            visible={this.state.visiblenationType}
                            onClose={() => {
                              this.setVisiblenationType()
                            }}
                            onConfirm={(val, extend) => {
                              debugger
                              this.formRef.current?.setFieldsValue({nation_type:extend.items[0].label})
                              this.setState({
                                nation_type_id:extend.items[0].value
                              })

                            }}
                        />
                        <Picker
                            columns={[
                              this.convertArray(this.state.maritalTypeOption)
                            ]}
                            visible={this.state.visiblemaritalType}
                            onClose={() => {
                              this.setVisiblemaritalType()
                            }}
                            onConfirm={(val, extend) => {
                              debugger
                              this.formRef.current?.setFieldsValue({marital_type:extend.items[0].label})
                              this.setState({
                                marital_type_id:extend.items[0].value
                              })

                            }}
                        />
                         <Picker
                            columns={[
                              this.convertArray(this.state.politicalTypeOption)
                            ]}
                            visible={this.state.visiblepoliticalType}
                            onClose={() => {
                              this.setVisiblepoliticalType()
                            }}
                            onConfirm={(val, extend) => {
                              debugger
                              this.formRef.current?.setFieldsValue({political_type:extend.items[0].label})
                              this.setState({
                                political_type_id:extend.items[0].value
                              })

                            }}
                        />
                         <Picker
                            columns={[
                              this.convertArray(this.state.educationTypeOption)
                            ]}
                            visible={this.state.visibleeducationType}
                            onClose={() => {
                              this.setVisibleeducationType()
                            }}
                            onConfirm={(val, extend) => {
                              debugger
                              this.formRef.current?.setFieldsValue({education_type:extend.items[0].label})
                              this.setState({
                                education_type_id:extend.items[0].value
                              })

                            }}
                        />
                         <Picker
                            columns={[
                              this.convertArray(this.state.religionTypeOption)
                            ]}
                            visible={this.state.visiblereligionType}
                            onClose={() => {
                              this.setVisiblereligionType()
                            }}
                            onConfirm={(val, extend) => {
                              debugger
                              this.formRef.current?.setFieldsValue({religion_type:extend.items[0].label})
                              this.setState({
                                religion_type_id:extend.items[0].value
                              })

                            }}
                        />
                         <Picker
                            columns={[
                              this.convertArray(this.state.occupationTypeOption)
                            ]}
                            visible={this.state.visibleoccupationType}
                            onClose={() => {
                              this.setVisibleoccupationType()
                            }}
                            onConfirm={(val, extend) => {
                              debugger
                              this.formRef.current?.setFieldsValue({occupation_type:extend.items[0].label})
                              this.setState({
                                occupation_type_id:extend.items[0].value
                              })

                            }}
                        />
                        
                </Form>
            </div>
          
   
      </div>
    );
  }
}


const mapStateToProps = (state) => {
  return {
  }
}

export default connect(mapStateToProps)(peopleAdd)

**Comment by tylerpanpan** [comment]
> 我不是你这种写法，我没解决你的问题，可以参考我这种写法 /* eslint no-dupe-keys: 0, no-mixed-operators: 0 */ import React from 'react'; import { Button,Card,TextArea,ImageUploader,Image,Form,Input,Toast,Picker,DatePicker,DotLoading} from 'antd-mobile'; import { UnorderedListOutline,RightOutline} from 'antd-mobile-icons' import { Select } from 'antd'; import { connect } from 'dva'; import styles from './index.less' import ip from '../../config/IpManager' import postQuery from '../../utils/postQuery'; import moment from "moment"; import request from '../../utils/request'; // get const item = { avatar: 'https://images.unsplash.com/photo-1548532928-b34e3be62fc6?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ', name: 'Novalee Spicer', description: 'Deserunt dolor ea eaque eos', } const { Option } = Select; const now = new Date() class peopleAdd extends React.Component { constructor(props) { super(props); const { query = {} } = props.location; this.buildid =query.id this.formRef = React.createRef() this.state = { detail:{ }, hasMore: true, url:'https://images.unsplash.com/photo-1620476214170-1d8080f65cdb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3150&q=80', height: document.documentElement.clientHeight , visiblesex:false, visiblecreatetime:false, visiblenationType:false, visiblemaritalType:false, visiblenationType:false, visiblepoliticalType:false, visibleeducationType:false, visiblereligionType:false, visibleoccupationType:false, sexOption:[],//性别 nativeTypeOption:[],//民族 maritalTypeOption:[], politicalTypeOption:[], politicalTypeOption:[], educationTypeOption:[], religionTypeOption:[], occupationTypeOption:[], fileList:[] }; }
> 
> componentDidMount() { this.getDic("424")//性别 this.getDic("425")//民族 this.getDic("426")//婚姻状况 this.getDic("427")//政治 this.getDic("428")//学历 this.getDic("415")//宗教 this.getDic("429")//职业类型 }
> 
> toFloor=(item)=>{ Toast.show(item.bldName) } getDic=(dictType)=>{ let stepsUrl = `${ip.qysServer + '/dict/tree/' + dictType}`; //获取字典 request(stepsUrl).then((res) => { if (res.data && res.data.length > 0) { if(dictType=="424"){
> 
> ```
>         var newarray =this.convertArray(res.data[0].childList)
>         this.setState({
>           sexOption:newarray
>         })
>         
>       }else if(dictType=="425"){
>         var newarray =this.convertArray(res.data[0].childList)
>         this.setState({
>           nativeTypeOption:newarray
>         })
>       }else if(dictType=="426"){
>         this.setState({
>           maritalTypeOption:res.data[0].childList
>         })
>       }else if(dictType=="427"){
>         this.setState({
>           politicalTypeOption:res.data[0].childList
>         })
>       }else if(dictType=="428"){
>         this.setState({
>           educationTypeOption:res.data[0].childList
>         })
>       }else if(dictType=="415"){
>         this.setState({
>           religionTypeOption:res.data[0].childList
>         })
>       }else if(dictType=="429"){
>         this.setState({
>           occupationTypeOption:res.data[0].childList
>         })
>       }
>        
>     }
>     
> })
> ```
> 
> } edit=()=>{
> 
> ```
> }
> setVisible=()=>{
>   this.setState({
>      visiblesex:!this.state.visiblesex
>   })
> }
> setVisiblecreatetime=()=>{
>   this.setState({
>     visiblecreatetime:!this.state.visiblecreatetime
>   })
> }
> setVisiblenationType=()=>{
>   this.setState({
>     visiblenationType:!this.state.visiblenationType
>   })
> }
> setVisiblemaritalType=()=>{
>   this.setState({
>     visiblemaritalType:!this.state.visiblemaritalType
>   })
> }
> setVisibleeducationType=()=>{
>   this.setState({
>     visibleeducationType:!this.state.visibleeducationType
>   })
> }
> setVisiblepoliticalType=()=>{
>   this.setState({
>     visiblepoliticalType:!this.state.visiblepoliticalType
>   })
> }
> setVisiblereligionType=()=>{
>   this.setState({
>     visiblereligionType:!this.state.visiblereligionType
>   })
> }
> setVisibleoccupationType=()=>{
>   this.setState({
>     visibleoccupationType:!this.state.visibleoccupationType
>   })
> }
> //提交
> submit=()=>{
>   var value=this.formRef.current?.getFieldsValue()
>   let params = value
>   params.gender_type_id = this.state.gender_type_id
>   params.nation_type_id = this.state.nation_type_id
>   params.marital_type_id = this.state.marital_type_id
>   params.political_type_id = this.state.political_type_id
>   params.education_type_id = this.state.education_type_id
>   params.religion_type_id = this.state.religion_type_id
>   params.occupation_type_id = this.state.occupation_type_id
>   
>   debugger
>   postQuery(`${ip.qysServer + '/crud/insert/bdPerson'}`, params).then((res) => {
>     
>     if(res.code=='200'){
>       // code: 200
>       // data: 1
>       // msg: ""
>       Toast.show("新增成功")
>       history.back()
>     }else{
>       Toast.show("新增失败")
>     }
>     
>   })
> }
> convertArray=(objArr)=>{
>   var newobjArr = [...objArr];
>   // 旧 key 到新 key 的映射
>   const keyMap = {
>     dictValue: "label",
>     dictKey: "value",
>   };
>   for (let i = 0; i < newobjArr.length; i++) {
>     let obj = newobjArr[i];
>     for (let key in obj) {
>       let newKey = keyMap[key];
>       if (newKey) {
>         obj[newKey] = obj[key];
>       }
>     }
>   }
>   console.log(newobjArr)
>   return newobjArr;
>   
> }
> setFileList=()=>{
> 
> }
> upload=()=>{
> 
> }
> ```
> 
> render() { const {bldUnderFloorTotal}=this.state; console.log(this.formRef.current,'==============') return (
> 
> ```
>       <div style={{paddingLeft:5,paddingRight:5}}>
>           <Card
>               style={{ borderRadius: '2px',alignContent:'center'}}
>             >
>             <ImageUploader
>               value={this.state.fileList}
>               onChange={this.setFileList}
>               upload={this.upload}
>             />
>           </Card>
>           <Form    
>                 ref={this.formRef} 
>                 layout='horizontal' mode=''  
>                 footer={
>                 <Button block type='submit' color='primary' size='large' onClick={this.submit}>
>                   提交
>                 </Button>
>           }>
>            
>                     <Form.Item 
>                       name='p_name' 
>                       label='姓名'
>                       className={styles.formitemstyle} 
>                       rules={[{ required: true, message: '姓名不能为空!' }]} >
>                         <Input placeholder='请输入' style={{ '--text-align': 'right',"--font-size":15 }} />
>                     </Form.Item>
>                  
>                     <Form.Item 
>                         name='gender_type' 
>                         label='性别' 
>                         className={styles.formitemstyle} 
>                         onClick={() => {this.setVisible()}}
>                     >
>                         <Input   style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
>                     </Form.Item>
>                     
>                     <Form.Item 
>                         name='birthday' 
>                         label='出生日期'
>                         className={styles.formitemstyle} 
>                         onClick={() => {this.setVisiblecreatetime()}}
>                         > 
>                         <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
>                     </Form.Item>
>                     <Form.Item 
>                         name='nation_type' 
>                         label='民族'  
>                         className={styles.formitemstyle} 
>                         onClick={() => {this.setVisiblenationType()}}
>                         > 
>                         <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
>                     </Form.Item>
>                     <Form.Item  
>                         name='phone_num_list' 
>                         label='手机号码'
>                         className={styles.formitemstyle} 
>                         >
>                         <Input  style={{ '--text-align': 'right',"--font-size":15 }} type="number"/>
>                     </Form.Item>
>                     <Form.Item 
>                         name='marital_type' 
>                         label='婚姻状况'
>                         className={styles.formitemstyle}   
>                         onClick={() => {this.setVisiblemaritalType()}}
>                         > 
>                         <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
>                     </Form.Item>
>                     <Form.Item 
>                         name='political_type' 
>                         label='政治面貌'  
>                         className={styles.formitemstyle} 
>                         onClick={() => {this.setVisiblepoliticalType()}}
>                         > 
>                         <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
>                     </Form.Item>
>                     <Form.Item 
>                         name='education_type' 
>                         label='文化程度'  
>                         className={styles.formitemstyle} 
>                         onClick={() => {this.setVisibleeducationType()}}
>                         > 
>                         <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
>                     </Form.Item>
>                     <Form.Item 
>                         name='religion_type' 
>                         label='宗教信仰'  
>                         className={styles.formitemstyle} 
>                         onClick={() => {this.setVisiblereligionType()}}
>                         > 
>                         <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
>                     </Form.Item>
>                     <Form.Item 
>                         name='occupation_type' 
>                         label='职业类型'  
>                         className={styles.formitemstyle} 
>                         onClick={() => {this.setVisibleoccupationType()}}
>                         > 
>                         <Input  style={{ '--text-align': 'right',"--font-size":15}} disabled={true}/>
>                     </Form.Item>
>                     
>             
>                     <Form.Item 
>                         name='native_place' 
>                         label='籍贯'
>                         className={styles.formitemstyle} 
>                         >
>                         <TextArea
>                                 placeholder='请输入籍贯'
>                                 onClear={true}
>                                 style={{ '--text-align': 'right',"--font-size":15}}
>                                 autoSize={{ minRows: 3, maxRows: 5 }}
>                           />
>                     </Form.Item>
>                     <Form.Item 
>                         name='residence_addr' 
>                         label='户籍地址'   
>                         className={styles.formitemstyle} 
>                         >
>                         <TextArea
>                             placeholder='请输入户籍地址'
>                             style={{ '--text-align': 'right',"--font-size":15}}
>                             autoSize={{ minRows: 3, maxRows: 5 }}
>                           />
>                     </Form.Item>
>                     <Form.Item 
>                         name='current_addr' 
>                         label='现居住地'   
>                         className={styles.formitemstyle} >
>                         <TextArea
>                             placeholder='请输入现居住地址'
>                             style={{ '--text-align': 'right',"--font-size":15}}
>                             autoSize={{ minRows: 3, maxRows: 5 }}
>                           />
>                     </Form.Item>
>                  
>                     <Picker
>                         columns={[
>                           this.convertArray(this.state.sexOption)
>                         ]}
>                         visible={this.state.visiblesex}
>                         onClose={() => {
>                           this.setVisible()
>                         }}
>                         onConfirm={(val, extend) => {
>                           debugger
>                           this.formRef.current?.setFieldsValue({gender_type:extend.items[0].label})
>                           this.setState({
>                             gender_type_id:extend.items[0].value
>                           })
> 
>                         }}
>                       />
>                     <DatePicker
>                       title='时间选择'
>                       visible={this.state.visiblecreatetime}
>                       onClose={() => {
>                         this.setVisiblecreatetime()
>                       }}
>                       max={now}
>                       min={new Date('1900-01-01')}
>                       onConfirm={val => {
>                         this.formRef.current?.setFieldsValue({birthday:moment(val.toDateString()).format('YYYY-MM-DD') })
>                       }}
>                     />
>                     <Picker
>                         columns={[
>                           this.convertArray(this.state.nativeTypeOption)
>                         ]}
>                         visible={this.state.visiblenationType}
>                         onClose={() => {
>                           this.setVisiblenationType()
>                         }}
>                         onConfirm={(val, extend) => {
>                           debugger
>                           this.formRef.current?.setFieldsValue({nation_type:extend.items[0].label})
>                           this.setState({
>                             nation_type_id:extend.items[0].value
>                           })
> 
>                         }}
>                     />
>                     <Picker
>                         columns={[
>                           this.convertArray(this.state.maritalTypeOption)
>                         ]}
>                         visible={this.state.visiblemaritalType}
>                         onClose={() => {
>                           this.setVisiblemaritalType()
>                         }}
>                         onConfirm={(val, extend) => {
>                           debugger
>                           this.formRef.current?.setFieldsValue({marital_type:extend.items[0].label})
>                           this.setState({
>                             marital_type_id:extend.items[0].value
>                           })
> 
>                         }}
>                     />
>                      <Picker
>                         columns={[
>                           this.convertArray(this.state.politicalTypeOption)
>                         ]}
>                         visible={this.state.visiblepoliticalType}
>                         onClose={() => {
>                           this.setVisiblepoliticalType()
>                         }}
>                         onConfirm={(val, extend) => {
>                           debugger
>                           this.formRef.current?.setFieldsValue({political_type:extend.items[0].label})
>                           this.setState({
>                             political_type_id:extend.items[0].value
>                           })
> 
>                         }}
>                     />
>                      <Picker
>                         columns={[
>                           this.convertArray(this.state.educationTypeOption)
>                         ]}
>                         visible={this.state.visibleeducationType}
>                         onClose={() => {
>                           this.setVisibleeducationType()
>                         }}
>                         onConfirm={(val, extend) => {
>                           debugger
>                           this.formRef.current?.setFieldsValue({education_type:extend.items[0].label})
>                           this.setState({
>                             education_type_id:extend.items[0].value
>                           })
> 
>                         }}
>                     />
>                      <Picker
>                         columns={[
>                           this.convertArray(this.state.religionTypeOption)
>                         ]}
>                         visible={this.state.visiblereligionType}
>                         onClose={() => {
>                           this.setVisiblereligionType()
>                         }}
>                         onConfirm={(val, extend) => {
>                           debugger
>                           this.formRef.current?.setFieldsValue({religion_type:extend.items[0].label})
>                           this.setState({
>                             religion_type_id:extend.items[0].value
>                           })
> 
>                         }}
>                     />
>                      <Picker
>                         columns={[
>                           this.convertArray(this.state.occupationTypeOption)
>                         ]}
>                         visible={this.state.visibleoccupationType}
>                         onClose={() => {
>                           this.setVisibleoccupationType()
>                         }}
>                         onConfirm={(val, extend) => {
>                           debugger
>                           this.formRef.current?.setFieldsValue({occupation_type:extend.items[0].label})
>                           this.setState({
>                             occupation_type_id:extend.items[0].value
>                           })
> 
>                         }}
>                     />
>                     
>             </Form>
>         </div>
>       
> 
>   </div>
> );
> ```
> 
> } }
> 
> const mapStateToProps = (state) => { return { } }
> 
> export default connect(mapStateToProps)(peopleAdd)

恩，你这种写法是没问题的，我那种写法是按官方的写法弄的，只要用了那三种Picker组件，后面跟着的Input表单项都会有问题

**Comment by qiyexuelei** [comment]
被设置了 name 属性的 Form.Item 包装的控件，表单控件会自动添加 value（或 valuePropName 指定的其他属性） onChange（或 trigger 指定的其他属性），数据同步将被 Form 接管，因此，如果你给 Form.Item 设置了 name 属性，那么请确保它的 children 是一个有效的 ReactElement 控件，并且能够接受上文中提到的 value 和 onChange 属性（或指定的其他属性）
按官方文档的说明，我觉得Packer组件没有onChange属性，所以不能用Form.Item包装，所以你那种写法不对

**Comment by qiyexuelei** [comment]
![image](https://user-images.githubusercontent.com/30651534/163324250-9fb837ec-c51f-4244-931b-7578d8c58932.png)

**Comment by awmleer** [comment]
看起来是用法问题，可以再仔细读一下 Form 的文档

如果你觉得是 antd-mobile 的 bug 的话，尝试在这里写一个最小复现 demo 吧：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

issue 我先关了～

**Comment by tylerpanpan** [comment]
> 看起来是用法问题，可以再仔细读一下 Form 的文档
> 
> 如果你觉得是 antd-mobile 的 bug 的话，尝试在这里写一个最小复现 demo 吧：https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx
> 
> issue 我先关了～

奇怪了，在sandbox里面看是好的，我是在nextjs里面用的，就出现了图中的问题，不过我已经用了取巧的方式解决了
