### ISSUE TITLE
Picker 选择器增加搜索功能

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design-mobile#5073]
### Version of antd-mobile
N/A

### What is this feature about?
效果类似这样，可以根据搜索框输入的条件对选项进行筛选。
![image](https://user-images.githubusercontent.com/50612752/163351728-baa04097-8e22-4ab1-b02e-2da1ff5e05ca.png)

**Comment by awmleer** [comment]
这个不会支持的，你所说的这种使用场景，感觉可以自己组合一下 Popup + SearchBar + CheckList 组件

**Comment by li-yu-tfs** [comment]
> 这个不会支持的，你所说的这种使用场景，感觉可以自己组合一下 Popup + SearchBar + CheckList 组件

但是我popup使用searchbar， 在chrome android 移动端上面， 弹起的键盘会遮挡住popup内容。
