### ISSUE TITLE
List增加可以修改背景样式，增加listitem点击修改样式

### ISSUE THREAD

**Issue by limit81995** [ant-design/ant-design-mobile#5077]
### Version of antd-mobile

5.10.2

### What is this feature about?

List可以自己修改样式。直接把自己写的scss样式直接添加进去。
ListItem 也支持自己修改样式，点击后触发的样式也可以自己修改。

目前只有特定的参数修改，比如List修改背景颜色麻烦，listitem点击后的样式只能修改背景颜色。 透明度和动画都无法自己去添加和修改

**Comment by awmleer** [comment]
组件库只能做“有限的开放”，这是效率、可维护性、质量与可定制化之间平衡的结果

如果你希望 List 增加一些 CSS 变量的话，可以再提个 issue 描述一下具体想增加哪些 CSS 变量，这个 issue 我关掉了
