### ISSUE TITLE
日历组件跳转指定年月，无法显示完整的月份

### ISSUE THREAD

**Issue by pxy-hjx** [ant-design/ant-design-mobile#5079]
### Version of antd-mobile

5.3.0

### Operating system and its version

iOS, Android

### What happened?

<img width="353" alt="image" src="https://user-images.githubusercontent.com/71257999/163539217-db645e7e-afe8-4273-986a-6ab05bd6798c.png">
<img width="860" alt="image" src="https://user-images.githubusercontent.com/71257999/163539413-22ea1cdf-51ef-4b4c-b9c7-75db475dcb33.png">

**Comment by miracles1919** [comment]
这个改了，下个版本应该会修复的，见这个 PR #5067
