### ISSUE TITLE
List在react-native中是空白

### ISSUE THREAD

**Issue by gutenye** [ant-design/ant-design-mobile#508]
#### 本地环境

- antd-mobile 版本：1.0.0-alpha.10
- 操作系统及其版本：iOS 10
- 浏览器及其版本：

#### 你做了什么？

```
import React, { Component } from 'react'
import { View, Text } from 'react-native'
import { List, Button } from 'antd-mobile'

class App extends Component {
  render() {
    return (
      <View>
         <Button>hello</Button>
         <List>
            <List.Item><Text>foo</Text></List.Item>
         <List>
      </View>
    )
  }
}
```
#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

Button正常显示
List显示不出来

**Comment by warmhug** [comment]
官网 demo 如果没问题，那就需要你仔细排查自己代码问题了

**Comment by gutenye** [comment]
@warmhug 哪里可以看到官网的demo源代码?

**Comment by silentcloud** [comment]
看看 #56 的 demo 能运行么？ @gutenye

**Comment by gutenye** [comment]
经测试, 在react-native 0.35.0下正常, 0.37.0下面显示空白.

**Comment by gutenye** [comment]
可能和 https://github.com/react-native-community/react-native-tab-view/issues/54#issuecomment-256919009 有关?

**Comment by silentcloud** [comment]
目前进行antd-mobile > rn 0.34 版本的兼容性测试，0.35 兼容性测试已经通过，接下来会测试 0.36和0.37

**Comment by silentcloud** [comment]
#589 在这里处理，这个 issue 先关了
