### ISSUE TITLE
Picker组件closeOnMaskClick和onCancel同时使用时， closeOnMaskClick设置false失效

### ISSUE THREAD

**Issue by ahhhhz** [ant-design/ant-design-mobile#5080]
### Version of antd-mobile

5.6.0

**Comment by awmleer** [comment]
请提供一个复现 demo

[提问指引](https://github.com/ant-design/ant-design-mobile/blob/master/.github/HOW_TO_ASK_QUESTIONS.md)

**Comment by awmleer** [comment]
由于未能收到回复，issue 先关闭了
