### ISSUE TITLE
Modal to support duration property to control animation duration

### ISSUE THREAD

**Issue by Dunqing** [ant-design/ant-design-mobile#5081]
### Version of antd-mobile

latest

### Operating system and its version

iOS, Android

### Browser and its version

all

### Sandbox to reproduce

https://mobile.ant.design/zh/components/modal

### What happened?

现无法改变动画时长

另外我发现这个动画是动态改变opacity的值从0到1实现的？
期望使用css原生属性 transitaion或animation实现

**Comment by awmleer** [comment]
统一记在 #5090 了
