### ISSUE TITLE
一些组件TS报错不存在children 属性 如Card

### ISSUE THREAD

**Issue by Haerden** [ant-design/ant-design-mobile#5082]
### Version of antd-mobile

5.10.2

### Description

![image](https://user-images.githubusercontent.com/45613575/163584705-f672ef90-25ca-4cc1-899c-5b5575c95430.png)

**Comment by myGitZone** [comment]
看下node_modules下面@types中react相关的类型库里面的node_modules里面是不是有18版本的react类型库。应该是类型冲突了

**Comment by miracles1919** [comment]
react 18 的 types 有 breaking changes，先用 17 吧，18 的兼容还在进行中 ，统一记录在这个 [issue](https://github.com/ant-design/ant-design-mobile/issues/5044)

**Comment by awmleer** [comment]
update 一下：types 的兼容问题 @miracles1919 在 #5088 这个 PR 里修复了

**Comment by awmleer** [comment]
这个 issue 应该可以先关闭了，完整的 react 18 适配的进度在 #5044 这个 issue 里
