### ISSUE TITLE
这个List 不好使，还不如手动写个ul li， flexbox 的column-reverse，  transform scale 用来实现聊天上滚动都不好使，高度也不设置100%

### ISSUE THREAD

**Issue by komagic** [ant-design/ant-design-mobile#5083]
### What is this feature about?

可以把list 改了

**Comment by komagic** [comment]
一、List为什么要改？
1. list 应该支持上滚动或下滚动，加个reverse属性就能改变。demo里的list 滚动依赖的不是List本身的滚动条，这样会导致实现聊天上滚动很麻烦，不能默认在滚动底部，还不如自己手写个ul li的方便。
2. infinite scoll 就不说了，实现方式不是很好

**Comment by awmleer** [comment]
并没有看到具体的问题和提议，先关掉了

**Comment by komagic** [comment]
好吧，这么还不睡，辛苦了，我看看

**Comment by awmleer** [comment]
噢昨天回复的时候错过了一条评论，再回复一下

- List 组件是有一定的适用场景限制的，看你所说像是要做一个类似聊天界面的东西？听起来不太适合用 List 组件
- InfiniteScroll 的实现具体有什么提议么？可以单独再提个 issue 展开聊聊

**Comment by komagic** [comment]
#5084 这里codesandbox大致实现了，再稍微修饰下就ok了
