### ISSUE TITLE
能否不用window的滚动，而是默认使用 inner 那层作为滚动？

### ISSUE THREAD

**Issue by komagic** [ant-design/ant-design-mobile#5084]
### What is this feature about?

s: 目前组件List只支持下滚动，不能支持类似聊天那样的上滚动（微信那样下拉出现loading然后加载数据，并保持lastscolltop）。而聊天那样的上滚动，在移动端很常见

当滚动层为window而不是列表元素的直接父级，设置使用flex的 column-reverse 或 transform scale(1,-1) 都无法实现类似聊天那样，列表初始化时候，滚动起始位置就在底部。

t：使用list-item的父级作为滚动的元素，而不是window

**Comment by komagic** [comment]
然后那个， infinite-scroll，我有个建议，使用 Intersection Observer + scrollIntoView 来判断 组件里的loader 是否出现在视口中，然后就加载loadmore，这种方式利于理解。也非常容易做出各种不同情况（如左右横拉加载）的加载组件，嘿嘿

而且移动端浏览器几乎都是自动升级的，这些功能几乎都是支持的

**Comment by komagic** [comment]
实现地址 ：https://codesandbox.io/s/vigilant-frost-88e3ih?file=/src/App.js

在基础上稍微修复一些小bug就可以了，这种是比较方便的

**Comment by awmleer** [comment]
1. IntersectionObserver 只在 Safari 12.1 及以上才支持，目前不能使用这套方案
2. List 组件本身没有任何滚动的逻辑或者功能，更何谈“只支持下滚动，不能支持类似聊天那样的上滚动”
3. 如果你需要实现的是聊天界面，请不要使用 List 组件，你不能期望把锤子当斧头用，还怪它不够锋利

**Comment by komagic** [comment]
1、关于intersction observer,可以用 判断infinite-scoll的边是否进入了父组件的可视范围内来代替，逻辑类似canvas判断两个物体相交

2、List是列表的意思吧？剑桥词典说 List 是
a record of short pieces of information, such as people's names, usually written or printed with **a single thing on each line** and often **ordered in a way** that makes a particular thing easy to find

那么根据这个意思，list 是按照一定顺序排列，并没有说只能从上往下排列。 
根据一般习惯，list 既可以从上往下排列，也应该可以从下往上排列，还可以从左往右，亦或者从右往左。

那么目前的infinite-scroll的实现方式，显然是不支持的。

**Comment by awmleer** [comment]
关于 List，每一个单词都有狭义上和广义上的定义，不能期望 antd-mobile 的 List 组件和词典上 list 定义中的内涵和外延都完全相等

关于 InfiniteScroll 的反方向滚动加载问题，很久之前就有 issue 了，可以关注一下： #4770

**Comment by komagic** [comment]
啊~，感觉要是给你写出一个现成的你也不会放进去

**Comment by komagic** [comment]
intersection observer 我看移动端大组件库都有用，比如ionic

微软也有用

你这不是都antd-mobile 5了吗

**Comment by awmleer** [comment]
有很多千万级 UV 的项目在用 antd-mobile，目前 iOS 10 11 是没办法忽略不计的

**Comment by komagic** [comment]
我实现一个兼容版本的 intersection obsserver，给整好，你发不发

**Comment by awmleer** [comment]
你是说 polyfill？https://github.com/w3c/IntersectionObserver/tree/main/polyfill

**Comment by awmleer** [comment]
![image](https://user-images.githubusercontent.com/16526078/164143257-b5c71011-5a4d-403d-90ae-369c6294da99.png)

看起来有点太大了，而且 polyfill 还有潜在的性能问题，一般还在用 iOS 10 11 的设备都是很老的机型了，不得不考虑性能上的影响

所以做 polyfill 的话，感觉成本和收益不对等啊，不然我们早就做了

**Comment by komagic** [comment]
用判断父dom和子dom是否碰撞的方式，也可以实现检测loader rect是否在视野之中好吧

**Comment by awmleer** [comment]
没太懂你的意思，要是感兴趣的话，可以来个 PR 看看？猜测你是想替换这里的逻辑？

https://github.com/ant-design/ant-design-mobile/blob/a734b24e396d281ff9d81bcbf276a510ee9bc4ab/src/components/infinite-scroll/infinite-scroll.tsx#L47-L66

**Comment by awmleer** [comment]
现在的滚动事件，是通过 `getScrollParent` 找到最近一层的可滚动的父级元素，绑定在它上面的，并非直接绑定在 window 上的：

https://github.com/ant-design/ant-design-mobile/blob/a734b24e396d281ff9d81bcbf276a510ee9bc4ab/src/components/infinite-scroll/infinite-scroll.tsx#L73-L85

**Comment by awmleer** [comment]
可能还是直接提 PR 比较好，我不太清楚你是想实现什么样的逻辑

**Comment by komagic** [comment]
我就是想

把list逻辑改了，infinite-scroll 就会很好写
