### ISSUE TITLE
响应式布局

### ISSUE THREAD

**Issue by DaDanLiu** [ant-design/ant-design-mobile#5086]
### Description

Antd Mobile 或者Antd 有支持到响应式布局的方案么，pc到移动端网页的

**Comment by awmleer** [comment]
响应式布局是业务逻辑的一部分，不太清楚你指的‘响应式布局方案“是什么？如果你期望的是用了组件库之后就再也不用关心响应式适配的话，那现在没有这种能力未来也不太可能会有
