### ISSUE TITLE
使用 Toast 组件给出提示是出现警告

### ISSUE THREAD

**Issue by shengbenqiang** [ant-design/ant-design-mobile#5089]
### Version of antd-mobile

5.10.2

### Operating system and its version

Android, Others

### Browser and its version

chrome  100.0.4896.127（正式版本）64位

### What happened?

`Toast.show({
                content: '该城市暂无房源',
            })`
使用后出现警告
我希望使用后没有警告，我在 antd-design 看到它的 Notification 也出现相同情况，不知道有没有被修复

### Relevant log output

```shell
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

**Comment by awmleer** [comment]
https://mobile.ant.design/zh/guide/quick-start#%E5%85%BC%E5%AE%B9%E6%80%A7

![image](https://user-images.githubusercontent.com/16526078/163746361-7362ddfd-ed3c-4bf3-8b04-ae7fb7c87395.png)
