### ISSUE TITLE
Search组件：无法在输入框内左右滑动到最左侧

### ISSUE THREAD

**Issue by GoldMinerXun** [ant-design/ant-design-mobile#5094]
### Version of antd-mobile

v5.10.2

### Operating system and its version

iOS

### Browser and its version

IOS15 Safari

### Sandbox to reproduce

/

### What happened?

Search组件：无法在输入框内左右滑动，输入内容超出可视范围的长度情况下，无法移动光标到最左侧起始位置。

### Relevant log output

```shell
/
```

**Comment by awmleer** [comment]
听起来像是系统的输入框的行为？提供一下视频和复现 demo 吧

**Comment by GoldMinerXun** [comment]
> 
上传一个不能回到最左侧的视频。demo就是官网的例子。
我自己验证了最简原生h5 input标签，ios上表现与v5 searchBar一致，理论上是原生控件input的问题，但是v2 searchBar没问题...麻烦看下v5怎么修复？


https://user-images.githubusercontent.com/47557265/164183511-1b089136-c81e-46e2-beb1-fe96af6c1217.mp4

**Comment by awmleer** [comment]
排查出来了，视频里访问的是 gallery 页面，而 gallery 页面是通过 iframe 加载的 demo 页面，导致了 Safari 出现 bug，由于正常情况下业务项目是不会这么玩的，所以可以忽略这个问题了
（而且这其实是底层浏览器的 bug，而不是 antd-mobile 的）
