### ISSUE TITLE
InfiniteScroll 组件loadMore连续执行

### ISSUE THREAD

**Issue by liuchenx** [ant-design/ant-design-mobile#5095]
### Version of antd-mobile

^5.9.1

### Operating system and its version

Others

### Sandbox to reproduce

https://stackblitz.com/edit/react-ts-eu8wxf?file=app.tsx

### What happened?

```
html, body {
  overflow-x: hidden;
}
```

页面html和body标签如果设置了overflow-x: hidden属性，会导致InfiniteScroll的loadMore连续执行

### Relevant log output

```shell
已经提交stackblitz地址，可以发现console.log('1111111111111111111111111111');不停输出
```

**Comment by komagic** [comment]
这个就是 getScrollParent 的不确定性导致的。

思路是，让List这个element成为overflow：auto，infinite-scroll 作为被观察的target，target进入了parent的范围后就调用loadmore

我觉得list 和 infinite-scroll 都得改，我愿意提一个pr

**Comment by komagic** [comment]
list 和 inifite-scroll 都改，就能实现 其他人提的bug，和功能需求，以及解决这个bug

**Comment by awmleer** [comment]
感谢反馈， fd5b55e2 已修复
