### ISSUE TITLE
InputItem的editable与OnPressIn事件在ios与android上面行为不一致

### ISSUE THREAD

**Issue by daselang** [ant-design/ant-design-mobile#5096]
### Version of antd-mobile

4.2.0

### Operating system and its version

iOS, Android

### Browser and its version

React Native

### What happened?

在ios上面editable为false 是可以触发onPressIn方法。true也可以触发此方法。
但是在android上面editalbe为false时，不会触发此事件方法。
如果修改为true，在android上面onPressIn方法才可响应。但是弹出键盘。
希望fix此bug,与ios保持一致，editable为false时，可触发onPressIn,且不弹出键盘。

其他的onPressOut等没有做过测试。

**Comment by jacob-lcs** [comment]
react native？

应该到这里提 issue

https://github.com/ant-design/ant-design-mobile-rn
