### ISSUE TITLE
button 组件加载中的状态能否支持下自定义loadingIcon

### ISSUE THREAD

**Issue by jsoyoy** [ant-design/ant-design-mobile#5098]
### Version of antd-mobile

5.10.2

### What is this feature about?

如题，业务需求方要求使用自定义的加载中icon。

**Comment by awmleer** [comment]
或许可以在 ConfigProvider 中加个配置 `buttonLoadingIcon`

**Comment by miracles1919** [comment]
> 或许可以在 ConfigProvider 中加个配置 `buttonLoadingIcon`

这里有点疑惑，为什么不是在 Button 上加一个 prop，而是选择 ConfigProvider

**Comment by awmleer** [comment]
在 Button 上加个 prop 也行……其实就是看一般是需要全局修改还是只改个别地方

**Comment by miracles1919** [comment]
主要是考虑到这样的场景，ConfigProvider 就会一直维护
- button loading 支持全局配置了，Switch、Toast 等组件加载中能不能也支持下...
- button loading 支持全局配置了，loadingText  能不能也支持下...

可能我考虑多了 - - 
- - - 
如果要加的全局配置的话，这样的定义是不是更好一点
```
type Config = {
  button?: {
    loadingIcon?: ReactNode
  },
  ...otherComponent: ...
}
```

**Comment by awmleer** [comment]
我一开始也在想要不要分成两级，但是有些时候可能以组件分组并不是很合适（有些情况下还是合适的），比如动画变量，可能适合这样：

```
{
  animation: {
    dialog: {...},
    mask: {...}
  }
}
```

**Comment by awmleer** [comment]
回到这个 case，感觉你说的是对的，还是放在 Button 组件上作为一个 `loadingIcon` 属性更合适

**Comment by jsoyoy** [comment]
> 在 Button 上加个 prop 也行……其实就是看一般是需要全局修改还是只改个别地方

个人认为只是个别改动prop即可，不需要全局修改，props更为灵活。配置成全局样式，不是很通用的逻辑。
若需要全局修改，可基于此作定制的业务组件。
