### ISSUE TITLE
[网站] mobile icon 报错

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#51]
http://localhost:8001/kitchen-sink/icon/

![image](https://cloud.githubusercontent.com/assets/2011119/17470070/f619b25a-5d6b-11e6-86e8-f1c49e71be98.png)

icon 没有 demo 目录、引起报错，是否可以改成直接用 `./icon/index.md` 里的demo ？

**Comment by zlessa** [comment]
亲，这个kitchen-sink我跑不起来，在npm install的时候会报错
antd-tools run guard
npm WARN unmet dependency D:\page_space\ant-design-mobile-master\
sheng-plugin-react requires react@'~15.2.1' but will load
npm WARN unmet dependency D:\page_space\ant-design-mobile-master\
act,
npm WARN unmet dependency which is version 15.0.2
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\study_install\\nodejs\\node.exe" "E:\\study_in
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.2 does not satisfy it
rDependencies requirements!
npm ERR! peerinvalid Peer react-hammerjs@0.5.0 wants react@^0.14.
npm ERR! peerinvalid Peer react-slick@0.12.2 wants react@^0.14.0
npm ERR! peerinvalid Peer react-dom@15.2.1 wants react@^15.2.1
npm ERR! peerinvalid Peer react-addons-test-utils@15.3.0 wants re
npm ERR! peerinvalid Peer react-stateless-wrapper@1.0.7 wants rea
14.x || ^15.x
npm ERR! peerinvalid Peer qrcode.react@0.6.1 wants react@0.12 - 0
npm ERR! peerinvalid Peer react-router@2.6.1 wants react@^0.14.0
npm ERR! peerinvalid Peer react-copy-to-clipboard@4.2.2 wants rea

npm ERR! peerinvalid Peer react-intl@2.1.3 wants react@^0.14.0 ||
npm ERR! peerinvalid Peer bisheng-plugin-antd@0.2.2 wants react@^
npm ERR! peerinvalid Peer react-native@0.30.0 wants react@~15.2.0

各个插件需要的react的版本不一样，请问这个要怎么解决呢？

**Comment by liqi07** [comment]
bisheng现在的规则是以demo文件下的md文件名作为key值传回demo代码，直接引用./icon/index.md可能改造比较大，能否直接增加icon对应的demo目录，适配无线端展示 @warmhug

**Comment by warmhug** [comment]
那就增加下吧 @liqi07

**Comment by warmhug** [comment]
@zlessa 的问题是 windows 系统的问题吗？ @yiminghe

**Comment by afc163** [comment]
@zlessa 用 npm3

**Comment by liqi07** [comment]
@warmhug  网站icon已fix 
@zlessa 用npm3安装运行
