### ISSUE TITLE
Popup组件如何挂在到指定组件下方，文档中的getContainer属性无效，请问如何使用。 

### ISSUE THREAD

**Issue by SparkChenZ** [ant-design/ant-design-mobile#5100]
### Version of antd-mobile

5.10.1

### Operating system and its version

Others

### Browser and its version

chrome版本 100.0.4896.127（正式版本） (x86_64)

### What happened?

如何使用，目前无法挂载到指定组件下进行pop操作

**Comment by GOWxx** [comment]
写了个 [复现demo](https://codesandbox.io/s/divine-sky-vkrjv1?file=/src/App.tsx)，
`getContainer`传入的dom并没有作为父节点，作为了兄弟节点。
![image](https://user-images.githubusercontent.com/12870715/164704171-7e28d7cb-1b7b-4dd5-ae25-50f74c793373.png)
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/12870715/164704221-bbc7a334-9155-4286-8d59-8bc421562a3d.png">

**Comment by GOWxx** [comment]
写了个 [demo](https://codesandbox.io/s/divine-sky-vkrjv1?file=/src/App.tsx)，可以参考下
需要准备一个空的节点，作为父节点。
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/12870715/164704482-fd3139c4-e39e-404b-89eb-41685d4f8894.png">
![image](https://user-images.githubusercontent.com/12870715/164704548-74fd30cc-69f6-4f3a-84d0-47883dc85e3a.png)

**Comment by GOWxx** [comment]
写了一个 [bug复现demo](https://codesandbox.io/s/divine-sky-vkrjv1?file=/src/App.tsx)

复现步骤：
1. 打开复现链接，打开开发者工具，选中 `popover`组件，观察 dom 树，可见 `div.adm-popover` 没有挂载成功
2. 点击底部按钮，更新界面，可见 `div.adm-popover` 挂载到目标节点下

附图：
1.
![image](https://user-images.githubusercontent.com/12870715/164708214-91aa3d79-0d6f-452b-895d-11d9e6fecf3c.png)
2.
![image](https://user-images.githubusercontent.com/12870715/164708542-0768440c-e12d-45a3-a9e3-68c19f50dc72.png)

**Comment by SparkChenZ** [comment]
您demo到这个是Popover组件，没问题的。我这边碰到的是Popup弹出层组件，指定挂载节点后，实际显示效果还是从body节点开始显示。
![image](https://user-images.githubusercontent.com/12554145/164887190-08e2a088-2c4d-4280-b0eb-d3f3f2741ebb.png)
![image](https://user-images.githubusercontent.com/12554145/164887202-89c36fcc-78fb-4fc3-8525-4f58b933ca44.png)

![image](https://user-images.githubusercontent.com/12554145/164887244-650e09f8-e400-48fb-a54e-2de65c50dc9c.png)
 
理解的效果是从挂载节点向下弹出，如图3，蒙板以及弹出内容是在标题栏向下弹出显示。
请教下改如何使用。版本是5.10.1，谢谢。

**Comment by awmleer** [comment]
请在 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或者 [stackblitz](https://stackblitz.com/edit/antd-mobile) 上写一个 demo

**Comment by awmleer** [comment]
由于未能收到回复，issue 先关闭了
