### ISSUE TITLE
ImageViewer  长图放大，图片向左偏移

### ISSUE THREAD

**Issue by smilelmz** [ant-design/ant-design-mobile#5105]
### Version of antd-mobile

5.10

### Browser and its version

小米10

### What happened?

![WechatIMG89](https://user-images.githubusercontent.com/15361002/164975153-79a91067-4738-44bf-b257-4d68380b9196.jpeg)

**Comment by awmleer** [comment]
没太看出来你想表达的是啥问题……要不录个视频吧？

**Comment by smilelmz** [comment]
https://user-images.githubusercontent.com/15361002/165014100-bbb64c83-a433-4147-aa79-294b70a81922.mp4

@awmleer 我用手势放大，我觉得正常应该放大的部分应该居中显示，实际偏移很大

**Comment by awmleer** [comment]
get，看起来是个 bug

**Comment by smilelmz** [comment]
@awmleer 这个问题已经在修复了吗

**Comment by awmleer** [comment]
还没顾上，我先标个 help wanted

**Comment by zhengjitf** [comment]
@smilelmz 可以试下[这个](https://antd-mobile-preview-pr-5461.surge.sh/~demos/image-viewer-demo1/), 之前没有考虑缩放中心，以及不同类型的变换顺序对结果的影响导致了问题。
> 我看 vant 的 [ImagePreview](https://youzan.github.io/vant/v4/#/zh-CN/image-preview) 也有这个问题 😂
