### ISSUE TITLE
使用IndexBar example 的一个问题, 找不到'demo.function'

### ISSUE THREAD

**Issue by Hunter-857** [ant-design/ant-design-mobile#5107]
### Version of antd-mobile

5.10.3

### Description

在使用案例代码时, 有个方法找不到? 我应该怎么解决呢?我怎能调用到这个方法? 
![截屏2022-04-25 上午1 10 45](https://user-images.githubusercontent.com/12094603/164988224-fcfcca11-cd48-4959-bd24-58828c7b7c43.png)

而去我尝试2个String也不行,似乎是因为类型不匹配

![截屏2022-04-25 上午1 10 45](https://user-images.githubusercontent.com/12094603/164988350-82131676-a1ea-4533-9c1b-a57f56c70bb0.png)
求指导一下~
十分感谢

**Comment by GOWxx** [comment]
`lorem` 实际上是 `lorem-ipsum` 再封装的
可以参考
https://github.com/ant-design/ant-design-mobile/blob/master/src/demos/utils/lorem.ts

项目里实际在用的版本是
```json
"lorem-ipsum": "^2.0.4",
```

结合这两个内容，你就可以写个自己的 `lorem` 方法了。

**Comment by big-hunter** [comment]
是的 ,多谢,我刚才吧它添加上了,这个方法应该是用来生成随机的字符的,
但是我看到<IndexBar.Panel> 里需要的类型似乎不太匹配
![截屏2022-04-25 上午1 29 59](https://user-images.githubusercontent.com/12094603/164988884-f836f080-abf1-4539-b5d9-2cde87adbec9.png)
.

**Comment by GOWxx** [comment]
> 是的 ,多谢,我刚才吧它添加上了,这个方法应该是用来生成随机的字符的, 但是我看到<IndexBar.Panel> 里需要的类型似乎不太匹配 !

请在 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或者 [stackblitz](https://stackblitz.com/edit/antd-mobile) 上写一个 demo

可以参考\
[如何在 codesandbox 上写一个复现 demo](https://mobile.ant.design/zh/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-codesandbox-%E4%B8%8A%E5%86%99%E4%B8%80%E4%B8%AA%E5%A4%8D%E7%8E%B0-demo)

**Comment by big-hunter** [comment]
我想应该是我本地ts 的问题,
在这里也不会报错的.
https://codesandbox.io/embed/winter-tdd-yp4s7o?fontsize=14&hidenavigation=1&theme=dark

在我本地需要加上  // @ts-ignore 才可以编译成功

```
     // @ts-ignore
        <IndexBar.Panel
            index={title}
            title={`标题${title}`}
            key={`标题${title}`}
        >
```

**Comment by awmleer** [comment]
@big-hunter 你本地用的 react 18 么？

**Comment by miracles1919** [comment]
> @big-hunter 你本地用的 react 18 么？

@awmleer 我看了下 `IndexBarPanelProps` 漏了个 children 定义 - -

**Comment by awmleer** [comment]
@Hunter-857 先本地用 react 17 吧，等下个版本发布之后再考虑升级到 react 18

**Comment by Hunter-857** [comment]
好的,只是练练手,不太影响
