### ISSUE TITLE
List.Item 的 prefix 判断方式错误

### ISSUE THREAD

**Issue by dingziqi** [ant-design/ant-design-mobile#5111]
### Version of antd-mobile

5.10.1

### Operating system and its version

iOS

### What happened?

List.Item 的 prefix 判断方式有问题，会产生隐式类型转换，比如我传入的是 `0`，最终渲染出来的是字符节点 `0`，丢失了 prefix 的父容器，导致样式也错乱了。
![image](https://user-images.githubusercontent.com/16345383/165034013-8260720e-6bbb-45c0-892b-d56d97302497.png)

### Relevant log output

```shell
https://github.com/ant-design/ant-design-mobile/blob/v5.10.1/src/components/list/list-item.tsx#L28
```

**Comment by awmleer** [comment]
请在 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或者 [stackblitz](https://stackblitz.com/edit/antd-mobile) 上写一个 demo

**Comment by IronKinoko** [comment]
```js
Array(10).fill(0).map((_, i) =>  <List.Item prefix={i} />)
```

因为传递的是数字的，第一个数字是0 ，不满足 &&，但又不是 nil，所以渲染了个 0 出来

```js
{props.prefix && (
  <div className={`${classPrefix}-content-prefix`}>{props.prefix}</div>
)}
```

**Comment by awmleer** [comment]
那看起来这里的判断应该改成下面这样……？

```tsx
props.prefix !== undefined && props.prefix !== null && props.prefix !== false
```

稍有点繁琐，不过可以抽成一个通用函数放到 utils 里去

**Comment by dingziqi** [comment]
> 那看起来这里的判断应该改成下面这样……？
> 
> ```tsx
> props.prefix !== undefined && props.prefix !== null && props.prefix !== false
> ```
> 
> 稍有点繁琐，不过可以抽成一个通用函数放到 utils 里去

可以这样：`![undefined, null].includes(props.prefix)`，在 `render` 里面用 `&&` 一定要保证前面的值为 bool，不然就会和我一样掉坑里 😂

**Comment by miracles1919** [comment]
undefined 和 null 的判断可以是不是可以直接用 lodash 的 `isNil`

`isNil(props.prefix) && props.prefix  !== false`

**Comment by awmleer** [comment]
这倒问题不大，自己也也就两行代码的事，还能把 `!== false` 包括进去

**Comment by awmleer** [comment]
我来搞一下吧

**Comment by awmleer** [comment]
887db312
