### ISSUE TITLE
[Button] 希望能根据 onClick Promise 状态自动渲染loading状态

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#5112]
### What is this feature about?

就像是 Dialog.confirm 的 onConfirm 就处理了这个逻辑

**Comment by awmleer** [comment]
感觉可以搞诶，有了这个特性之后方便很多，`loading` 属性目前是 `boolean`，是不是可以改成 `boolean | 'auto'`，然后如果是 `loading='auto'`，就走自动 loading 的模式，根据 `onClick` 返回的 Promise 来控制 loading 状态

**Comment by IronKinoko** [comment]
需要把 auto 当成默认值吗？

**Comment by awmleer** [comment]
还是不要当成默认值比较好：

- 会造成 break change
- 很多时候用户未必需要 loading 或者希望手动控制 loading

**Comment by IronKinoko** [comment]
ok
