### ISSUE TITLE
form表单怎么给Picker设置默认值

### ISSUE THREAD

**Issue by Web-Delevan** [ant-design/ant-design-mobile#5116]
### Version of antd-mobile

5.10.4

### Operating system and its version

Android

### Browser and its version

Android

### What happened?

![企业微信截图_16508943738292](https://user-images.githubusercontent.com/41311561/165102158-a32544b9-b5f6-4390-99bf-0856d5c10e9d.png)

**Comment by lemonig** [comment]
为什么close了。我也想知道如何设置
