### ISSUE TITLE
Steps组件当title或者description较长时，连接线会断掉

### ISSUE THREAD

**Issue by xingqiangqiang** [ant-design/ant-design-mobile#5120]
### Version of antd-mobile

5.10.0

### Sandbox to reproduce

https://stackblitz.com/edit/antd-mobile-xqjp5t?file=index.tsx

### What happened?

当给.adm-step设置min-width:33.33%时即固定宽度时，线不会乱掉，线的宽度为33.33%，但是对应的title或者description过长时会折行展示。类似
<img width="514" alt="image" src="https://user-images.githubusercontent.com/73377464/165287423-85e699ac-1009-4771-92f3-082f2fa06a8a.png">
可以实现一行展示吗，这里的线的宽度看出是和title或者description的父元素宽度一样

**Comment by awmleer** [comment]
看起来你对 antd-mobile 做了大面积的样式覆盖……？这种情况下看起来不是 antd-mobile 本身的 bug

**Comment by awmleer** [comment]
如果你对 antd-mobile 做了大量的样式覆盖，那 antd-mobile 就没有办法对组件做任何质量上的保证了，我们建议尽量不要做“样式魔改”

**Comment by awmleer** [comment]
如果你认为你需要的效果和 antd-mobile 提供的组件差异非常大，那可以考虑自己完全重新实现一个组件，不要使用 antd-mobile 的组件
而如果你认为是 antd-mobile 组件的能力有所缺失，那可以再提个 issue 描述一下你的 feature request
