### ISSUE TITLE
[CascadePicker] options里不同层级如果有相同的value，后面的覆盖了前面的value

### ISSUE THREAD

**Issue by lyjjjj** [ant-design/ant-design-mobile#5124]
### Version of antd-mobile

 "antd-mobile": "5.5.1"

### Operating system and its version

Others

### Browser and its version

windows chromeV100

### Sandbox to reproduce

https://codesandbox.io/s/purple-https-8eqits?file=/src/App.tsx

### What happened?

![image](https://user-images.githubusercontent.com/29419586/165463763-63eece10-f9e1-42fc-8602-8b2fe807026a.png)

**Comment by IronKinoko** [comment]
https://github.dev/ant-design/ant-design-mobile/blob/f5b09ef814a379ebd823c357fe5ea4bd72818a23/src/components/cascade-picker/use-cascade-picker-options.tsx#L7-L12

L12 在赋值的时候，相同的id会覆盖
