### ISSUE TITLE
DatePicker的closeOnMaskClick属性不生效，设置为true的时候点击mask依然会触发onClickMask方法

### ISSUE THREAD

**Issue by Flash3** [ant-design/ant-design-mobile#5125]
### Version of antd-mobile

5.10.1

### Operating system and its version

iOS, Android, Others

### Browser and its version

iOS 15.3.1

### What happened?

DatePicker的closeOnMaskClick属性不生效，设置为true的时候点击mask依然会触发onClickMask方法。我希望picker可以提供className来供使用者自定义picker样式。并且能提供mask的点击方法用于控制mask的点击事件

**Comment by awmleer** [comment]
`onClickMask` 是啥？似乎并不是 antd-mobile 提供的东西？

**Comment by Flash3** [comment]
> `onClickMask` 是啥？似乎并不是 antd-mobile 提供的东西？

closeOnMaskClick是DatePicker组件的一个属性值，用于禁用Modal里面的Mask的点击事件。看源码是通过Picker组件传给Modal的。但是DatePicker在使用Picker的时候并没有把closeOnMaskClick传过去，Modal点击Mask的时候依然会触发onClickMask事件。
![图片](https://user-images.githubusercontent.com/19513616/165530199-e60dc39e-d80a-42db-969e-86f2baa06942.png)
![图片](https://user-images.githubusercontent.com/19513616/165530453-bd3d9596-a911-4767-a4ef-70670818bc1a.png)
![图片](https://user-images.githubusercontent.com/19513616/165530980-8b1133b5-2f0c-488b-84c1-d6903b78723e.png)
![图片](https://user-images.githubusercontent.com/19513616/165531966-6d67ea85-0a68-452b-ace3-31b47df61a84.png)

**Comment by awmleer** [comment]
get 已修复 7a268364
