### ISSUE TITLE
无限滚动 InfiniteScroll,   List能不能第一次不要加载 

### ISSUE THREAD

**Issue by TryChai** [ant-design/ant-design-mobile#5126]
### What is this feature about?

无限滚动 InfiniteScroll,   List能不能第一次不要加载  有种情况是第一次进来 需要搜索 空值 请求会报错 触发滚动再加载

**Comment by awmleer** [comment]
可以再更具体地描述一下，如果你能在 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或者 [stackblitz](https://stackblitz.com/edit/antd-mobile) 上写一个 demo 的话，我可以帮你看下怎么解决

**Comment by TryChai** [comment]
昨晚搞了一晚，其他页面都可以就一个页面不能，很奇怪，后来我自己写了滚动监听的方法，因为这个项目要赶五一搞好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月28日(周四) 上午10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ant-design/ant-design-mobile] 无限滚动 InfiniteScroll,   List能不能第一次不要加载  (Issue #5126)




 
可以再更具体地描述一下，如果你能在 codesandbox 或者 stackblitz 上写一个 demo 的话，我可以帮你看下怎么解决

**Comment by awmleer** [comment]
没有更具体的描述或 demo 的话，我们没有办法提供有效的分析和帮助，issue 我先关闭了
