### ISSUE TITLE
无限滚动 滚动到底不会触发请求 

### ISSUE THREAD

**Issue by TryChai** [ant-design/ant-design-mobile#5127]
### Version of antd-mobile

5.7.2

### Operating system and its version

Others

### Browser and its version

谷歌100

### What happened?

滚动到底部 没有异常 没有报错 接口返回正常 渲染正常 但是不会触发请求 我期望 能触发请求

**Comment by awmleer** [comment]
请在 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或者 [stackblitz](https://stackblitz.com/edit/antd-mobile) 上写一个 demo

[提问指引](https://github.com/ant-design/ant-design-mobile/blob/master/.github/HOW_TO_ASK_QUESTIONS.md)

**Comment by awmleer** [comment]
由于未能收到回复，issue 先关闭了
