### ISSUE TITLE
下拉选择器组件添加一个被选中的类名，方便自定义样式

### ISSUE THREAD

**Issue by doncaoyi** [ant-design/ant-design-mobile#5134]

**Comment by awmleer** [comment]
下拉选择器？你是想说 CheckList？

**Comment by doncaoyi** [comment]
不是哦，是picker组件

**Comment by doncaoyi** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/53499965/166858984-c8c51ffc-fc4c-4a09-9c83-5314075117b5.png">

**Comment by awmleer** [comment]
那你发的这截图看起来是 List 组件的……？

**Comment by doncaoyi** [comment]
对的对的，节前看的，昨天看错了，我用的是CheckList，需要个被选中的类名

**Comment by yaogengzhu** [comment]
> 对的对的，节前看的，昨天看错了，我用的是CheckList，需要个被选中的类名

`adm-check-list-item-active` checkList 组件存在被选中的类名呀？
