### ISSUE TITLE
建议给 table 组件添加一些操作事件

### ISSUE THREAD

**Issue by motorguo** [ant-design/ant-design-mobile#514]
[react-component/table#properties](https://github.com/react-component/table#properties)

使用场景：列表数据需要点击行（`onRowClick`）跳转。

移动端的 `Table` 应该不仅仅是展示数据。
just some advice.

**Comment by silentcloud** [comment]
@motorguo  有的 `onRowClick`，更多 api 参看这里 https://github.com/react-component/table#api

**Comment by motorguo** [comment]
@silentcloud thk.

`我见文档上没有，原文件也没暴露使用，以为不能用呢。`
