### ISSUE TITLE
有没有大佬知道，ant-mobile里的Form 组件是否支持ios11

### ISSUE THREAD

**Issue by merryGirl** [ant-design/ant-design-mobile#5141]
### Version of antd-mobile

5.7.0

**Comment by merryGirl** [comment]
项目里使用了一个依赖包内的表单，看了下表单内基于ant-mobile的Form表单开发的，ios11.1会白屏，定位到去掉这个Form引入ios底版本渲染就正常了

各位大佬是否晓得，Form是不支持ios11么，还是我需要添加别的依赖包辅助
（感谢~）

**Comment by awmleer** [comment]
https://mobile.ant.design/zh/guide/quick-start#%E5%85%BC%E5%AE%B9%E6%80%A7
