### ISSUE TITLE
[Tabs] 当父元素为flex布局时，超长自动滚动失效

### ISSUE THREAD

**Issue by KingAmo** [ant-design/ant-design-mobile#5142]
### Version of antd-mobile

5.11.0

### Operating system and its version

Others

### Browser and its version

chorme 99

### Sandbox to reproduce

https://codesandbox.io/s/dazzling-boyd-vvwee6?file=/src/App.tsx

### What happened?

问题：当Tabs的父元素为flex布局时，Tabs的超长自动滚动功能失效

期望：自动滚动功能正常

**Comment by miracles1919** [comment]
你提供的链接似乎没保存，打开只有一个按钮

**Comment by KingAmo** [comment]
> 你提供的链接似乎没保存，打开只有一个按钮

已更新链接

**Comment by miracles1919** [comment]
> 已更新链接

老哥你自己点下看看.. 我试了下还是一个按钮..

**Comment by KingAmo** [comment]
https://codesandbox.io/s/dazzling-boyd-vvwee6?file=/src/App.tsx

**Comment by KingAmo** [comment]
![image](https://user-images.githubusercontent.com/29938227/167056617-a38a35b7-d3e3-40f8-a9e8-66b628862069.png)

**Comment by KingAmo** [comment]
那就奇怪了，你确定链接对的吗
@miracles1919

**Comment by KingAmo** [comment]
或者我把代码贴出来
```
import React from "react";
import { Button, Tabs } from "antd-mobile";

export default function App() {
  return (
    <div className="App" style={{display: 'flex'}}>
      <Tabs defaultActiveKey='1'>
          <Tabs.Tab title='Espresso' key='1'>
            1
          </Tabs.Tab>
          <Tabs.Tab title='Coffee Latte' key='2'>
            2
          </Tabs.Tab>
          <Tabs.Tab title='Cappuccino' key='3'>
            3
          </Tabs.Tab>
          <Tabs.Tab title='Americano' key='4'>
            4
          </Tabs.Tab>
          <Tabs.Tab title='Flat White' key='5'>
            5
          </Tabs.Tab>
          <Tabs.Tab title='Caramel Macchiato' key='6'>
            6
          </Tabs.Tab>
          <Tabs.Tab title='Cafe Mocha' key='7'>
            7
          </Tabs.Tab>
        </Tabs>
    </div>
  );
}

```

**Comment by miracles1919** [comment]
> ![image](https://user-images.githubusercontent.com/29938227/167056617-a38a35b7-d3e3-40f8-a9e8-66b628862069.png)

你看这个 App.tsx 右边有个灰色的小圆点，说明没保存呢，按下 ctrl + s

**Comment by KingAmo** [comment]
谢谢提醒，我还真不知道是这个原因，已保存 @miracles1919

**Comment by miracles1919** [comment]
父元素为 flex 布局时，tabs 的宽度会变为实际宽度，是不是可以给 tabs 加一个 `overflow: hidden` @awmleer

**Comment by miracles1919** [comment]
一开始没想那么多，发现宽度变了，下意识加了个 `overflow: hidden` ，发现可以...

---

刚刚去查了下 flex 的规范 [4.5. Automatic Minimum Size of Flex Items](https://www.w3.org/TR/css-flexbox-1/#min-size-auto)

<img width="861" alt="image" src="https://user-images.githubusercontent.com/22469543/167159631-78f86c12-318d-43a7-ab72-1904e17fb900.png">

- 对于非滚动的 flex item，`min-width` 默认为 `auto`
- 对于滚动的 flex item，`min-width` 默认为 0

> For the purpose of calculating an intrinsic size of the box (e.g. the box’s [min-content size](https://www.w3.org/TR/css-sizing-3/#min-content)), a [content-based minimum size](https://www.w3.org/TR/css-flexbox-1/#content-based-minimum-size) causes the box’s size in that axis to become indefinite (even if e.g. its [width](https://www.w3.org/TR/CSS21/visudet.html#propdef-width) property specifies a [definite](https://www.w3.org/TR/css-flexbox-1/#definite) size). Note this means that percentages calculated against this size will [behave as auto](https://www.w3.org/TR/css-sizing-3/#behave-as-auto).

当 `min-width` 为 `auto` 时，其最小宽度是基于内容的

---

回到 Tabs 这个组件，外层是 flex 布局时，它的最小宽度就会基于内容，内容多的时候就会溢出。有两种解法：

- 设置为滚动元素：`overflow: hidden | auto | scroll`
- `min-width: 0`

**Comment by awmleer** [comment]
噢原来如此 👍👍👍
