### ISSUE TITLE
TextArea useLayoutEffect does nothing on the server 

### ISSUE THREAD

**Issue by taoliujun** [ant-design/ant-design-mobile#5144]
### Version of antd-mobile

5.11.2

### What happened?

`error: Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.`

when `<TextArea...` worked in ssr.

**Comment by awmleer** [comment]
26cffc144 已修复
