### ISSUE TITLE
InputItem能否提供一个配置用以表示表单中该字段必填，并在样式上体现出必填？

### ISSUE THREAD

**Issue by zhenzong** [ant-design/ant-design-mobile#515]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

**Comment by warmhug** [comment]
不提供配置项。 必填验证、用示例中提供的 rc-form 来做。 展现上，可以模仿 pc 做法，自己写 `<span style={{ color: 'red' }}>*</span>` 这样的红色星号之类，表示此项必填。

**Comment by zhenzong** [comment]
实现上是很好弄的。但是，表单是否必填，这个选择 在每个表单项里基本都会有用到，为何不一起封装到组件里呢？并且，用表单与后端进行交互的时候，后端的接口描述里，一般也有字段是否必须。

**Comment by warmhug** [comment]
谢谢建议。考虑到 验证组件是用独立的 rc-form 、而且没有和 inputItem 绑定起来，这种必填与否属于验证，所以也不该和 inputItem 绑定起来的吧。

**Comment by zhenzong** [comment]
感谢耐心解释。

我的想法是：如下代码：
``` javascript
<InputItem clear type="phone"
    placeholder="请输入手机"
    {
        ...getFieldProps('mobile', {
            initialValue: contact.mobile,
            rules: [{
                'required': true,
                'pattern': validator._mobileRe,
                'transform': function(value) {
                    return value ? value.replace(/ /g, '') : value;
                }
            }]
        })
    }>
    手机
</InputItem>
```

既然已经使用了rc-form依赖的asyc-validator的 required的配置，实际上我很清楚这个配置将要求这个字段必填，如果为空，则将无法通过校验，这也正是我期望的。如果能在InputItem 直接提供这个配置，并且有额外的样式，那也挺好的呀，比较省事。

ps： InputItem 配置type=“phone”， 内部的value 会包含空格，比如 “135 0000 0000”， 导致在校验或者使用该值的时候需要先transform

再次感谢 ！

**Comment by zmGitHub** [comment]
这个是不是解决下, 每次拿数据都得 transform 一把, 而且 validator 每次输入 change 都会发生事件 这个是否防抖下 在 RN 下体验不好 而且文档写的真的是....

**Comment by warmhug** [comment]
> rc-form 由于体积比较大，后续将不推荐使用，相应使用示例将会移除

这个组件部分 API 细节设计的确实不够完善。个人觉得可以这样修改：

- onChange 回调里加入第二个参数，表示未格式化的原始值 即`(val: string, rawVal?: string): void`
- 类似 Picker / DatePicker 组件，加入`format`函数，来处理类似 type=“phone” 的特殊显示格式问题，支持用户自定义显示格式。

@pingan1927

**Comment by paranoidjk** [comment]
> 既然已经使用了rc-form依赖的asyc-validator的 required的配置，实际上我很清楚这个配置将要求这个字段必填，如果为空，则将无法通过校验，这也正是我期望的。如果能在InputItem 直接提供这个配置，并且有额外的样式，那也挺好的呀，比较省事。

没有通用的必填设计，暂不支持。

> InputItem 配置type=“phone”， 内部的value 会包含空格，比如 “135 0000 0000”， 导致在校验或者使用该值的时候需要先transform

组件内部暂不做处理，加上 transformr 或者 formatter api， 必然要支持反向的 parser，增加复杂度，在用户代码过滤下数据反而简单很多。

> 这个是不是解决下, 每次拿数据都得 transform 一把, 而且 validator 每次输入 change 都会发生事件 这个是否防抖下 在 RN 下体验不好 而且文档写的真的是....

防抖是 rc-form 层面的事情。

**Comment by paranoidjk** [comment]
@timmyz 用 extra https://mobile.ant.design/components/input-item-cn/#API 自己实现
