### ISSUE TITLE
[Picker] 拓展 children 属性，实现内部控制 visible 

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#5152]
## 想法
- Form 组件和 Picker 的结合并不好用，官网的例子上需要手动控制 visible 状态

```js
<Form.Item
  name='birthday'
  label='生日'
  trigger='onConfirm'
  onClick={() => {
    setPickerVisible(true)
  }}
>
  <DatePicker
    visible={pickerVisible}
    onClose={() => {
      setPickerVisible(false)
    }}
  >
    {value =>
      value ? dayjs(value).format('YYYY-MM-DD') : '请选择日期'
    }
  </DatePicker>
</Form.Item>
```

## 基础用法
这是我项目里自己拓展的类型
```ts
export interface PickerProps extends Omit<AntPickerProps, 'children'> {
  children?: (items: (PickerColumnItem | null)[], onClick: () => void) => ReactNode
}
```

```jsx
<Picker>
  {(value, showPicker) => (
    <>
      <Button onClick={showPicker}>显示Picker</Button>
      {value.toString()}
    </>
  )}
</Picker>
```

**Comment by awmleer** [comment]
嗯嗯之前 #4211 也提到这个问题了，感觉这个思路好像可以诶

可以在你的基础上再稍微优化一下，`children` 函数的第二个参数可以提供更丰富的操作：

```jsx
<Picker>
  {(value, { open, close, toggle }) => (
    <>
      <Button onClick={open}>显示Picker</Button>
      {value.toString()}
    </>
  )}
</Picker>
```

我目前能想到的唯一一个问题，就是这种方案下，能不能有效的区分受控和非受控，换句话说，如果用户既用了 `children` 函数，又手动传了 `visible`，该怎么处理

**Comment by IronKinoko** [comment]
> children 函数的第二个参数可以提供更丰富的操作

确实，只是Picker展开后占满全屏，`close` `toggle` 使用频率应该很少。

> 区分受控和非受控

这个应该以 `props.visible` 为主，当传递 `props.visible` 并调用 `open` 可以给个 warn 提示。

还有个弊端
- 当与 `Form` 结合的时候，`onClick` 的作用范围不一致。区别是整个 `Form.Item` 与 `Form.Item` 的 `content-main` 区域

**Comment by awmleer** [comment]
> 当与 `Form` 结合的时候，`onClick` 的作用范围不一致。区别是整个 `Form.Item` 与 `Form.Item` 的 `content-main` 区域

噢有道理，这个问题感觉还挺严重的

**Comment by awmleer** [comment]
想到了另一种方案：

```jsx
<Form.Item onClick={widgetRef => { widgetRef.current.open() }}> // 这里的 widgetRef 就是内层 Picker 的 ref
  <Picker />
</Form.Item>
```

**Comment by IronKinoko** [comment]
感觉也不太好，如果 `<Form.Item noStyle />` `onClick`就失效了

**Comment by awmleer** [comment]
`noStyle` 就不管了，让用户自己处理吧……要么再包一层 `Form.Item`，要么就完全自己控制 `visible`

**Comment by awmleer** [comment]
当然也可以在 `children` 函数中也暴露 `ref`：

```jsx
<Picker>
  {(value, ref) => (
    <>
      <Button onClick={ref.current?.open}>显示Picker</Button>
      {value.toString()}
    </>
  )}
</Picker>
```

这样就可以把两种方案结合起来了

**Comment by IronKinoko** [comment]
可以，两种结合非常棒

还有这里的 onClick 应该保持原有结构，再添加 `widgetRef`
```jsx
<Form.Item onClick={(event, widgetRef) => { widgetRef.current.open() }}>
  <Picker />
</Form.Item>
```

**Comment by awmleer** [comment]
嗯嗯有道理

**Comment by Dunqing** [comment]
Good idea

**Comment by IronKinoko** [comment]
`Form.Item` 的 `children` 的 `ref` 该如何收集？

**Comment by awmleer** [comment]
应该可以在 `cloneElement` 的时候做一层 ref 的中转？

https://github.com/ant-design/ant-design-mobile/blob/master/src/components/form/form-item.tsx#L461

不过直接覆盖 `ref` 应该不行，还得考虑到用户自己也传了 `ref` 的情况：

```jsx
<Form.Item onClick={(e, widgetRef) => { ... }}>
  <Input ref={inputRef} />
</Form.Item>
```

**Comment by IronKinoko** [comment]
```jsx
const childProps = {
  ...children.props,
  ...control,
  ref: (instance: any) => {
    const originRef = (children as any).ref
    if (originRef) {
      if (typeof originRef === 'function') {
        originRef(instance)
      }
      if ('current' in originRef) {
        originRef.current = instance
      }
    }
    widgetRef.current = instance
  },
}
```

我通过修改 childProps 实现传递 ref，但是很多组件不是 `forwardRef` 或 `Class Component`，他们在接收到 ref 的时候 React 会提示警告

<img width="1180" alt="截屏2022-05-08 20 34 04的副本" src="https://user-images.githubusercontent.com/32838658/167296319-9689f9b0-213d-4ceb-b2c9-a8f0a6ebc1fe.png">

**Comment by IronKinoko** [comment]
在源码里找到了判断的 function component 方法。

```jsx
```

**Comment by IronKinoko** [comment]
下面这两种用法，哪个会好些？

```ts
// 传递整个 widgetRef
interface props {
  onClick: (e: React.MouseEvent, widgetRef: React.React.MutableRefObject<any>) => void
}

widgetRef.current.xxx()


// 传递 widget.current 
interface props {
  onClick: (e: React.MouseEvent, widgetRef: any) => void
}

widgetRef.xxx()
```

**Comment by awmleer** [comment]
我比较倾向于第一种：

- 毕竟变量名是叫 `xxxRef` 了，业务中使用的时候就能反应过来它是一个 React ref，感觉比较好理解
- 万一 `onClick` 中有异步逻辑，那通过 ref 的方式也能保证用户能拿到最新的值

写法上的确是稍微繁琐了一点，但是感觉也还好

**Comment by awmleer** [comment]
> 通过 `isForwardRef` 可以判断的出组件是否被 `forwardRef` 包裹，暂时不知道 `Class` 组件该如何判断。以及是否有更好的方法判断是否能够注入 `ref`

`isForwardRef` 原来是 react-is 提供的啊，那应该很稳的，class 组件实在不行就不支持了，到时候我们文档上注明一下

**Comment by luoye00** [comment]
> ### Version of antd-mobile
> _No response_
> 
> ### What is this feature about?
> ## 想法
> * Form 组件和 Picker 的结合并不好用，官网的例子上需要手动控制 visible 状态
> 
> ```js
> <Form.Item
>   name='birthday'
>   label='生日'
>   trigger='onConfirm'
>   onClick={() => {
>     setPickerVisible(true)
>   }}
> >
>   <DatePicker
>     visible={pickerVisible}
>     onClose={() => {
>       setPickerVisible(false)
>     }}
>   >
>     {value =>
>       value ? dayjs(value).format('YYYY-MM-DD') : '请选择日期'
>     }
>   </DatePicker>
> </Form.Item>
> ```
> 
> ## 基础用法
> 这是我项目里自己拓展的类型
> 
> ```ts
> export interface PickerProps extends Omit<AntPickerProps, 'children'> {
>   children?: (items: (PickerColumnItem | null)[], onClick: () => void) => ReactNode
> }
> ```
> 
> ```js
> <Picker>
>   {(value, showPicker) => (
>     <>
>       <Button onClick={showPicker}>显示Picker</Button>
>       {value.toString()}
>     </>
>   )}
> </Picker>
> ```

This works for, also can use Form.Item with Picker  like pc select.

**Comment by luoye00** [comment]
> 可以，两种结合非常棒
> 
> 还有这里的 `onClick` 应该保持原有结构，再添加 `widgetRef`
> 
> ```js
> <Form.Item onClick={(event, widgetRef) => { widgetRef.current.open() }}>
>   <Picker />
> </Form.Item>
> ```

This works for, also can use Form.Item with Picker like pc select.
