### ISSUE TITLE
Cascader选择option，再取消选择option，样式出现淡蓝色

### ISSUE THREAD

**Issue by Chincegen** [ant-design/ant-design-mobile#5153]
### Version of antd-mobile

5.11.2

### Description

![image](https://user-images.githubusercontent.com/26915429/167235732-39234fe3-b426-423e-a1d5-f7eda6d2ed44.png)
我点击了一次，再点击一次，交互产生的颜色有问题；按正常状态，取消选择该项，应该显示黑色

**Comment by miracles1919** [comment]
我试了下是正常的 

在 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或者 [stackblitz](https://stackblitz.com/edit/antd-mobile) 上提供一个复现 demo，或者录个视频吧

**Comment by awmleer** [comment]
由于未能收到回复，issue 先关闭了
