### ISSUE TITLE
[优化]Picker 和 Modal初始化的时候, 不要注入dom 到body

### ISSUE THREAD

**Issue by zm8** [ant-design/ant-design-mobile#5155]
### Version of antd-mobile

5.11.2

### What is this feature about?

还没打开Picker 和 Modal的时候，发现已经有 Picker和 Modal 相关的 dom 注入到body 了
antd-mobile 2版本没有这个问题。

地址: 
https://mobile.ant.design/~demos/picker-demo1
https://mobile.ant.design/~demos/modal-demo1

截图: 
![image](https://user-images.githubusercontent.com/32337542/167242389-a574b90b-dee8-4875-a6eb-dfd22d149887.png)
![image](https://user-images.githubusercontent.com/32337542/167242615-c5ab73e6-6466-4485-b106-04e74259aab5.png)

**Comment by awmleer** [comment]
get 看起来可以加个 `forceRender` 和 `destroyOnClose` 来控制行为，默认是 `forceRender` 为 `false` 的，也就是你另一个 issue #5158 提到的

**Comment by Shunjun** [comment]
同样遇到这个问题, 不止Modal Picker ，Popup ImageViewer 等组件都有这个问题
Popup 有个 destroyOnClose 的属性,但是只会销毁容器内的内容, 并不是销毁容器的.
现在的问题是页面中弹窗非常多, 所有的节点都被预先插入到body中了, body 中的节点就非常多.  并且层级在插入是就已经固定了,导致显示多个弹窗时会有遮挡问题,  现在只能手动阻止 Popup 组件渲染
但是手动渲染 ImageViewer  时又遇到别的问题, 每次打开 ImageViewer 都是重新渲染导致, 每次打开时去重新加载了图片内容.

**Comment by awmleer** [comment]
#5217

**Comment by awmleer** [comment]
ffe3ca07 这里又完善了一下，目前 Modal 和 Dialog 在初始状态下不会渲染任何 DOM 元素了，如果 `destroyOnClose` 启用了，销毁时也会销毁整个 DOM 元素

不过 Popup 相关的组件还没改，issue 我先 reopen
