### ISSUE TITLE
Modal 和 Dialog 支持属性 destroyOnClose

### ISSUE THREAD

**Issue by zm8** [ant-design/ant-design-mobile#5158]
### Version of antd-mobile

5.11.2

### What is this feature about?

参考 antd PC 版本 Modal，有一个属性 ```destroyOnClose```，关闭时销毁 Modal 里的子元素。

原因:
通常稍微复杂的业务代码都是**声明式**的**受控**组件，弹层每次打开的时候，希望**重新渲染**弹层里面的组件。

虽然可以通过以下的代码模拟实现```destroyOnClose```，其中关键代码是: ```content={visible && <Comp />}```，
但是当弹层关闭时，由于```visible``` 变为 ```false```,  弹层高度马上会变成0，而关闭又有个渐变的动画，造成体验的效果不是很好。

感谢!

``` js
const Declarative = () => {
  const [visible, setVisible] = useState(false);
  return (
    <>
      <Modal
        visible={visible}
        content={visible && <Comp />}
        closeOnAction
        onClose={() => {
          setVisible(false)
        }}
      />
    </>
  )
}
```

**Comment by awmleer** [comment]
#5217

**Comment by awmleer** [comment]
再补充一个 commit ffe3ca07
