### ISSUE TITLE
icon图标如何自适应屏幕大小

### ISSUE THREAD

**Issue by qq382724935** [ant-design/ant-design-mobile#5167]
### Description

目前icons大小在组件上使用fontsize配置，无法做到屏幕适配，请问如何适配呢

**Comment by awmleer** [comment]
没太懂你说的“屏幕适配”是指什么，Icon 默认是取的当前的 font-size，如果你想调整它的大小，那设置 font-size 就可以了

**Comment by qq382724935** [comment]
> 没太懂你说的“屏幕适配”是指什么，Icon 默认是取的当前的 font-size，如果你想调整它的大小，那设置 font-size 就可以了

比如在Icon组件中设置了fontSize。当切换不同设备，大小不会变动。
