### ISSUE TITLE
Can I use UmiJs and pro component?

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design-mobile#5168]
### Description

Hello, is it possible to set up a build with Ant Design Mobile React Native just like in the Javascript version?

For example, the ProForm components in Ant Design Pro component are very useful. Is it possible to use it for React Native?

Thanks.

**Comment by awmleer** [comment]
For issues related to antd-mobile-rn, please go here: https://github.com/ant-design/ant-design-mobile-rn/issues
