### ISSUE TITLE
tabbar+listview不能高度自适应

### ISSUE THREAD

**Issue by leonardgithub** [ant-design/ant-design-mobile#517]
#### 本地环境
antd-mobile 版本：├─┬ antd-mobile@0.9.6
操作系统及其版本：Ubuntu 16.04
浏览器及其版本：Chrome Versión 52.0.2743.116 (64-bit)

#### 你做了什么？
引入 antd-mobile 的 Tabbar和listview

#### 你期待的结果是：
listview高度自适应

#### 实际上的结果：
Tabbar要么挡住了listview，要么listview过短。原因在于listview貌似要设置一个height，但是这个height在不同浏览器上不能通用。
<ListView
	style={{
		height: '540',
	}}

#### 可重现的在线演示
no

**Comment by silentcloud** [comment]
listView 的高度等于 body - tabbar 的高度，计算一下

**Comment by leonardgithub** [comment]
@silentcloud tarbar的高度怎么求

**Comment by leonardgithub** [comment]
这样？
export function getListViewHeight() {
  if (document.getElementsByClassName('am-tab-bar-bar')[0]) {
    const result = document.body.clientHeight - document.getElementsByClassName('am-tab-bar-bar')[0].offsetHeight
    console.log('-----------------result:-----------------' + result)
    return result
  } else {
    const result = document.body.clientHeight - 35
    console.log('-----------------result:-----------------' + result)
    return result
  }
}

做了一个判断的原因是，有可能<List渲染的时候，document.getElementsByClassName('am-tab-bar-bar')[0]可能为空。

**Comment by silentcloud** [comment]
```
<TabBar>
   <TabBar.Item>
      <ListView style={{height: 计算出来的高度就可以了}}></ListView>
  </TabBar.Item>
</TabBar>
```

**Comment by leonardgithub** [comment]
是的，我们都知道要计算高度的差值。可是这个有没有最佳实践，而不是一句"计算一下"就好了。
即如何准确无误地获取tab的高度。
另，比起这个，能否看下
https://github.com/ant-design/ant-design-mobile/issues/520
https://github.com/ant-design/ant-design-mobile/issues/519
更紧急

**Comment by silentcloud** [comment]
tab-bar 如果你自己没有改变 theme 的话，默认 100px（高清方案下）；另外，listView 渲染的时候，tabbar 不可能还没渲染吧（按照我上面的写法）

**Comment by silentcloud** [comment]
有问题，再 reopen
