### ISSUE TITLE
InfiniteScroll  死循环

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-mobile#5170]
### Version of antd-mobile

^5.11.2",

### Sandbox to reproduce

https://github.com/lovesL/InfiniteScrollDemo

### What happened?

上面是复现的demo
 const [hasMore, setHasMore] = useState(true); 然后注意看控制打印的log

**Comment by miracles1919** [comment]
你这个 Demo 有两个问题
- hasMore 一直是 true
- 一直处于底部状态（data 一直是空数组）

组件里每次 render 的时候会做一些 check，都符合的情况下调用 doLoadMore
```jsx
useEffect(() => {
    // 简化代码，保留跟本次相关的内容
    if (!props.hasMore) return
    
    // 是否到达底部
    if (current >= elementTop - props.threshold) {
      await doLoadMore()
    }
})

```

结合你这个例子就是
`Tower render` -> `InfiniteScroll useEffect` -> 执行 doLoadMore （hasMore = true && 处于底部）-> 执行 useRequest，造成`Tower render` -> `InfiniteScroll useEffect` -> doLoadMore ...

**Comment by lovesL** [comment]
> 你这个 Demo 有两个问题
> 
> * hasMore 一直是 true
> * 一直处于底部状态（data 一直是空数组）
> 
> InfiniteScroll 里每次 render 的时候会做一些 check，都符合的情况下调用 doLoadMore
> 
> ```js
> useEffect(() => {
>     // 简化代码，保留跟本次相关的内容
>     // ...
>     if (!props.hasMore) return
>     
>     // 是否到达底部
>     if (current >= elementTop - props.threshold) {
>       await doLoadMore()
>     }
> })
> ```
> 
> 结合你这个例子就是 `Tower render` -> `InfiniteScroll useEffect` -> 执行 doLoadMore （hasMore = true && 处于底部）-> 执行 useRequest，造成`Tower render` -> `InfiniteScroll useEffect` -> doLoadMore ...

我明白了 谢谢 。但是我 搞不懂
<img width="855" alt="image" src="https://user-images.githubusercontent.com/27960630/167521672-888c4193-e945-451f-bba4-a9dccdaadad1.png">
我 如果走if返回就会死循环 但是 走else 就不会。result.data.list  就是个数组 是有数据的
![image](https://user-images.githubusercontent.com/27960630/167521863-ac8d36f2-59c7-4bd9-9bd3-ecbaec14416e.png)

**Comment by lovesL** [comment]
> *

![image](https://user-images.githubusercontent.com/27960630/167523197-9434c53b-ae39-495b-bc28-33cd8e246b7a.png)
<img width="601" alt="image" src="https://user-images.githubusercontent.com/27960630/167523287-0035606a-dda3-410e-994f-cbada27577e7.png">

InfiniteScroll 的loadMore初始会执行2次 大佬

**Comment by miracles1919** [comment]
github 上的代码再更新下？

**Comment by lovesL** [comment]
> github 上的代码再更新下？

好的  晚些时 我更新一些

**Comment by lovesL** [comment]
> github 上的代码再更新下？

已更新代码。发现2个问题 
1.初始加载页面后 打开模拟器 然后将页面滑动一点点 控制就开始 一直调接口了
2.将mock里的数据留 3 -4条数据 其他的注掉，然后重新打开页面 会直接一直调接口

以上我发现 的问题我不知道是不是哪用的不对  我觉得是不是这个组件很依赖布局   大佬看看
@miracles1919

**Comment by manzxiao** [comment]
@lovesL 是否可以尝试下，在loadMore中，添加
`
if (loading) return;
`

**Comment by miracles1919** [comment]
@lovesL 跟之前是一样的问题

- hasMore 一直是 true
- 一直处于底部状态（首次获取数据后，后面的 data 长度一直没变化的）

```js
// 你代码里的 page 一直为 1，不会进入 else 分支了
if (page == 1) {
    return result;
} else {
    return [...x, ...result];
}
```

**Comment by lovesL** [comment]
> ```js
> result
> ```
第一次进页面page是1 if  往下滑动 page++ 变2 进else   这个if 我需要这个判断 我其他条件需要重置data数据

**Comment by lovesL** [comment]
> @lovesL 跟之前是一样的问题
> 
> * hasMore 一直是 true
> * 一直处于底部状态（首次获取数据后，后面的 data 长度一直没变化的）
> 
> ```js
> // 你代码里的 page 一直为 1，不会进入 else 分支了
> if (page == 1) {
>     return result;
> } else {
>     return [...x, ...result];
> }
> ```

谢谢 我知道我的问题在哪了 有点钻牛角了 感谢大佬

**Comment by miracles1919** [comment]
@lovesL  你的代码是这样的

```
const Tower = () => {
    let page = 0;
    
    const loadMore = async () => {
         page++
         if (page == 1) {} 
         else {}
    }
}
```

每次 render 的时候都会重新执行 `let page = 0`

**Comment by lovesL** [comment]
> 

是的 是的我 也刚发现这个问题了  谢谢大佬
