### ISSUE TITLE
SearchBar组件，点击取消按钮控制台报错Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by Phil-Pu** [ant-design/ant-design-mobile#5174]
### Version of antd-mobile

5.11.2

### Operating system and its version

Others

### Browser and its version

Chrome 103.0.5042.0/Edge 101.0.1210.39

### Sandbox to reproduce

https://codesandbox.io/s/pensive-johnson-rllmsy?file=/src/App.tsx

### What happened?

点击取消按钮，能正常触发onCancel绑定事件，但是控制台报错“Unable to preventDefault inside passive event listener invocation.”。

已测试过react/react-dom 17和18，都存在这个bug。

无法在在线代码平台复现bug，但是已测试过本地新建的项目直接运行代码也存在这个bug。

### Relevant log output

```shell
react-dom.development.js:6202
Unable to preventDefault inside passive event listener invocation.
```

**Comment by awmleer** [comment]
似乎和这个 issue 有点像 #4961 

有没有哪位朋友能复现出来，求帮忙排查一下～

**Comment by IronKinoko** [comment]
https://github.com/ant-design/ant-design-mobile/blob/8f77b0e286d04c2f652aabe28fa1aca2b246dd0f/src/components/search-bar/search-bar.tsx#L93-L95

重现步骤
使用devtool移动端开发模式点击**取消按钮**就能重现

把这个注释后就不报错了

**Comment by IronKinoko** [comment]
相关的文章

https://stackoverflow.com/questions/42101723/unable-to-preventdefault-inside-passive-event-listener
https://chromestatus.com/feature/5093566007214080

**Comment by Dunqing** [comment]
### 原因
react-dom 对 `touchstart`事件默认设置passive为true

https://github.com/facebook/react/blob/44f99d75fa4528b82810edd03eccf82f7ea21ea0/packages/react-dom/src/events/DOMPluginEventSystem.js#L436-L442

https://github.com/facebook/react/blob/44f99d75fa4528b82810edd03eccf82f7ea21ea0/packages/react-dom/src/events/DOMPluginEventSystem.js#L491-L498

https://github.com/facebook/react/blob/44f99d75fa4528b82810edd03eccf82f7ea21ea0/packages/react-dom/src/events/EventListener.js#L41-L51

这将导致执行preventDefault出现 `Unable to preventDefault inside passive event listener invocation.` 这个错误

### 解决方案

- 改成浏览器原生监听事件，并设置passive为false
```tsx
elementRef.current?.addEventListener('touchstart', (event) => {
  event.preventDefault()
}, { passive: false })
```

- 删掉这行代码 https://github.com/ant-design/ant-design-mobile/issues/5174#issuecomment-1123452341
还不太清楚是什么情况下需要执行preventDefault

**Comment by awmleer** [comment]
当时加 preventDefault 应该是为了避免点击清除按钮（输入框里的那个小 clear 图标）时导致输入框失去焦点，不过取消按钮，感觉点击之后就应该让输入框失去焦点？

这么说的话，SearchBar 直接去掉 preventDefault 逻辑应该就行了

**Comment by Dunqing** [comment]
> 当时加 preventDefault 应该是为了避免点击清除按钮（输入框里的那个小 clear 图标）时导致输入框失去焦点，不过取消按钮，感觉点击之后就应该让输入框失去焦点？
> 
> 这么说的话，SearchBar 直接去掉 preventDefault 逻辑应该就行了

取消按钮在input框外，所以点击取消后失去焦点是正常现象。
另外因为有这个错误，所以其实一直都没有保留焦点成功，所以用户也是能接受这种情况的。

**Comment by awmleer** [comment]
有道理，那我改一下

**Comment by awmleer** [comment]
de25b2db 已修复
