### ISSUE TITLE
nextjs框架使用image组件或者avatar组件无法显示图片

### ISSUE THREAD

**Issue by ChinaBygones** [ant-design/ant-design-mobile#5176]
### Version of antd-mobile

v5.11.2

### Operating system and its version

Others

### Browser and its version

Google Chrome   101.0.4951.54（正式版本） (x86_64)

### What happened?

nextjs框架使用image组件或者avatar组件无法显示图片

`import user_avatar from "../public/avatar.png";`
`<Image width={100} height={100} src={user_avatar.src} fit="fill" />`

 "antd-mobile": "^5.11.2",
  "next": "12.1.6",
  "react": "18.1.0",
  "react-dom": "18.1.0"

**Comment by awmleer** [comment]
请提供完整的、可运行的复现 demo
