### ISSUE TITLE
建议List、Form组件在功能上能够更统一

### ISSUE THREAD

**Issue by Phil-Pu** [ant-design/ant-design-mobile#5177]
### Version of antd-mobile

5.11.2

### What is this feature about?

因为List和Form组件经常配合使用，但这两个组件部分相同功能的实现方法却不够统一。

比如List组件的标题是直接给<List>标签添加header属性，但Form组件却要单独使用<Form.Header>标签添加标题。

另外部分Form组件的功能能否让List组件也支持。

比如Form组件可以给<Form.Item>添加label属性来实现标签功能，而List并不行，Form实际生成的label也是在一个div里，而并不是在任何表单元素里。

又比如Form组件支持布局模式，但List不可以。

**Comment by awmleer** [comment]
List 和 Form 的职责、使用场景还是有挺大不同的，你提到的几个具体问题，我来回复一下吧

> List组件的标题是直接给标签添加header属性，但Form组件却要单独使用<Form.Header>标签添加标题。

因为一个 Form 可能包括多个 List（详见 Form 文档中分组的 demo），所以 API 自然会不一样

> Form组件可以给<Form.Item>添加label属性来实现标签功能，而List并不行，Form实际生成的label也是在一个div里，而并不是在任何表单元素里

List 面向的是通用场景，而 label 元素这种很显然是 Form 场景特定需要的，所以 List 自然不会在 API 上支持 label，但是如果你需要用的话，可以自己渲染 `<label />`

> Form组件支持布局模式，但List不可以

Form 对布局增加了很多限制，这也是为什么可以支持布局模式，灵活性和一键到位的布局调整是没有办法兼得的
