### ISSUE TITLE
升级到antd-mobile 5.12.0

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-mobile#5178]
### Version of antd-mobile

5.12.0

### Description

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/27960630/167799752-1df4bf78-4473-43ac-8377-9f7b229ffbf0.png">

 "umi": "^3.5.23",
"react": "17.x",
"react-dom": "17.x",

**Comment by H-Sven** [comment]
同样遇到这个问题

**Comment by awmleer** [comment]
已修复，升级到 [5.12.1](https://github.com/ant-design/ant-design-mobile/releases/tag/v5.12.1) 就不会再出现这个警告了
