### ISSUE TITLE
升级到5.12.0后react-dom报错

### ISSUE THREAD

**Issue by wangpanhb** [ant-design/ant-design-mobile#5179]
项目一直用的是react17，自动升级了ant-design后报错

**Comment by wangpanhb** [comment]
![WOA20220511-165858](https://user-images.githubusercontent.com/12654333/167811974-ee6484b2-f70c-482b-9753-0fd76d2b257d.png)

**Comment by Phil-Pu** [comment]
一看react-dom/client我就知道了……回退5.11.2正常了

**Comment by wangpanhb** [comment]
> 

是的，只能锁定版本到5.11.2了，但是后面要是有mobile库有组件升级都没法更新了

**Comment by awmleer** [comment]
已修复，升级到 [5.12.1](https://github.com/ant-design/ant-design-mobile/releases/tag/v5.12.1) 就不会再出现这个警告了
