### ISSUE TITLE
错误提示

### ISSUE THREAD

**Issue by WJayWJay** [ant-design/ant-design-mobile#518]
#### 本地环境

ERROR in ./~/bisheng/lib/utils/data.js
Module parse failed: $CWD\node_modules\bisheng\lib\loaders\bisheng-data-loader.js?config=D:\sourceproject\js\ant\test3\ant-design-mobile\site\bisheng.config.js!D:\sourceproject\js\ant\test3\ant-design-mobile\node_modules\bisheng\lib\utils\data.js Line 949: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
|   });
| },
|   'docs\pattern\unit': function () {
|   return new Promise(function (resolve) {
|     require.ensure([], function (require) {
 @ ./~/bisheng/tmp/entry.index.js 21:11-39

why can't find  bisheng/lib/utils/data.js 
- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

**Comment by benjycui** [comment]
bisheng 现在不支持 windows

**Comment by benjycui** [comment]
trace: https://github.com/benjycui/bisheng/issues/26
