### ISSUE TITLE
antd-mobile升级到5.12.0与react-dom17.x不兼容

### ISSUE THREAD

**Issue by Kurtzyf** [ant-design/ant-design-mobile#5180]
### Version of antd-mobile

5.12.0

### Operating system and its version

Others

### What happened?

![image](https://user-images.githubusercontent.com/38988175/167811180-1a51e370-5ca7-4a16-b9a0-e3d600257efa.png)

项目依赖版本：
"react": "^17.0.2",
"react-dom": "^17.0.2",

antd-mobile升级到5.12.0后其依赖的react和react-dom版本升级到了18.x，与主项目依赖版本不兼容

**Comment by awmleer** [comment]
是 warning 么？阻塞构建了么

**Comment by Kurtzyf** [comment]
> 是 warning 么？阻塞构建了么

因为报错的地方是import type所以没有阻塞构建，但是开发模式报了这个warning项目会跑不起来， 我目前先锁到5.11.2的版本了。antd-mobile5后续迭代是都会基于react 18.x了吧。

**Comment by awmleer** [comment]
已修复，升级到 [5.12.1](https://github.com/ant-design/ant-design-mobile/releases/tag/v5.12.1) 就不会再出现这个警告了

**Comment by awmleer** [comment]
> antd-mobile5后续迭代是都会基于react 18.x了吧。

会 16（16.8 及以上） 17 18 都支持的
