### ISSUE TITLE
image-viewer.css 兼容性警告

### ISSUE THREAD

**Issue by H-Sven** [ant-design/ant-design-mobile#5181]
### Version of antd-mobile

v5

### What happened?

<img width="2293" alt="image" src="https://user-images.githubusercontent.com/26042365/167812422-661bee65-1b51-46d1-9366-bc49e8a9d0e2.png">

**Comment by H-Sven** [comment]
需要加上  /*! autoprefixer: off */

<img width="629" alt="image" src="https://user-images.githubusercontent.com/26042365/167816432-a7f5999c-4044-4ef7-b674-8c1b8cee197d.png">

**Comment by H-Sven** [comment]
@awmleer  请在下次版本更新中， 加入  /*! autoprefixer: off */， 可以吗？ 消除warning警告

**Comment by awmleer** [comment]
可能的确是 antd-mobile CSS 写的有问题，我们先确认下情况～

（求支援）

**Comment by miracles1919** [comment]
是不是可以直接去掉 🤔

**Comment by awmleer** [comment]
可以试试……我也忘了当时是什么情况下加的这个样式了（可能是为了适配那种很高很长的图？）

**Comment by awmleer** [comment]
fc623d614 已修复
