### ISSUE TITLE
ImageUploader 图片上传组件，多图上传bug

### ISSUE THREAD

**Issue by listar** [ant-design/ant-design-mobile#5188]
### Version of antd-mobile

5.11.2

### Browser and its version

Chrome

### What happened?

批量选择多图上传的时候，  onChange回调函数的的图片数量不准确，偶发

**Comment by awmleer** [comment]
请在 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或者 [stackblitz](https://stackblitz.com/edit/antd-mobile) 上写一个 demo

**Comment by listar** [comment]
> 请在 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或者 [stackblitz](https://stackblitz.com/edit/antd-mobile) 上写一个 demo

就多图上传代码。 不要用mock上传，选个五张图片以上进行上传就可以看到onchange回调函数的第一个参数的长度不是逐步递增的

**Comment by awmleer** [comment]
那录个视频看看吧？

**Comment by awmleer** [comment]
具体是官网文档上的哪个 demo？具体是怎么操作的？

**Comment by awmleer** [comment]
由于未能收到回复，issue 先关闭了

**Comment by Jungzl** [comment]
https://codesandbox.io/s/priceless-cookies-h1d552?file=/src/App.tsx

https://user-images.githubusercontent.com/35426360/172980205-19a42966-fdb6-4ed5-a84b-e7c42de0b49a.mp4

React 18可以复现

**Comment by awmleer** [comment]
@Jungzl 感谢反馈，issue 我先 reopen

**Comment by yaogengzhu** [comment]
确实存在问题：

https://github.com/yaogengzhu/ant-design-mobile/blob/b73f5978d83a7a862901637e81983d4fa33718a9/src/utils/use-props-value.ts#L15


这个value 和 defaultValue 是否应该有一个合并的操作呢？

如果不用value. 使用 defalutValue 应该没有上述问题

https://codesandbox.io/s/dawn-grass-0g6msn

**Comment by awmleer** [comment]
我大概知道了，应该是受控模式下，外部 value 更新不及时，导致内部调用 onChange 时，取到了旧的值

我来试着修一下

**Comment by awmleer** [comment]
我发现这个问题只在 React 18 下会出现，我在上面的 demo 的基础上改了个 React 17 的 [demo](https://codesandbox.io/s/infallible-kepler-49j1p0?file=/src/index.tsx)，发现是不存在这个问题的

**Comment by awmleer** [comment]
大概率是 `usePropsValue` 的实现问题，不过应该和 defaultValue 没有关系 @yaogengzhu ，我试了一下你的提供的这个 demo 发现一样存在这个 bug

**Comment by awmleer** [comment]
推测是一个通用的问题，不仅限于 ImageUploader，还得再进一步排查下

**Comment by awmleer** [comment]
b841bdec fixed
