### ISSUE TITLE
react-router和tabbar配合使用问题

### ISSUE THREAD

**Issue by leonardgithub** [ant-design/ant-design-mobile#519]
#### 本地环境
antd-mobile 版本：├─┬ antd-mobile@0.9.6
操作系统及其版本：Ubuntu 16.04
浏览器及其版本：Chrome Versión 52.0.2743.116 (64-bit)
 

#### 你做了什么？
react-router和tabbar配合使用问题
我现在tabbar有四个tab，但是第四个tab会进入不同的页面，例如根据用户等级跳转到不同的路由页面，并且这些不同的页面底部都带有tabbar。
现在的情况是：定义tabbar的component是一个路由页面，用户不同等级的多个页面也都分别是不同的路由页面。
我在这些页面的底部加上tabbar的component，如<MyTabbar/>，但是有时会出现一个画面显示了多个tab的页面，可能是嵌套问题。
到底是tabbar嵌套component，还是component嵌套tabbar。现在感觉相互嵌套了。
react-router和tabbar配合使用，有没有最佳实践？如果没有最佳实践，还不如就不用tabbar了，用css重构这个tabbar的样式，component(路由页面)的最底部嵌套它，还简单明了一些。

#### 可重现的在线演示
no

**Comment by leonardgithub** [comment]
顺便建议tabbar封装一个切换tab能改变url，以及根据url跳转到不同tab的功能

**Comment by silentcloud** [comment]
```
<TabBar>
  <TabBar.Item><Component /></TabBar.Item>
  <TabBar.Item><Component /></TabBar.Item>
</TabBar>
```

目前 TabBar 的实现是这样的，类似 tabs，如果你想其中一个 Tab 展现不同页面，那可以让这个 tab 的内容变成一个容器，容器里包含不同的 component，根据条件切换成不同的

**Comment by SynChron1zed** [comment]
自己手写吧

**Comment by yvanwangl** [comment]
这里有我的一个实践，欢迎大家讨论：
https://github.com/yvanwangl/AntMobileDemo
