### ISSUE TITLE
Calendar 日历组件 是否支持快捷切换日期的想法？

### ISSUE THREAD

**Issue by mgu-x** [ant-design/ant-design-mobile#5191]
### Version of antd-mobile

v5.12.2

### What is this feature about?

Calendar 日历组件是否可以支持日期快捷切换的功能？
我尝试点击上一个月的日期，并不能切换到上一个月对应的日期
<img width="370" alt="image" src="https://user-images.githubusercontent.com/44564391/168482587-7ec33317-064d-4d90-b734-03c71c90252b.png">
我在代码中找到了对这个点击事件的处理
这里是对点击事件的判断
https://github.com/ant-design/ant-design-mobile/blob/4a11804217c01ad42d20c5181686a5703a630fb6/src/components/calendar/calendar.tsx#L206
这里是对点击事件的执行
https://github.com/ant-design/ant-design-mobile/blob/4a11804217c01ad42d20c5181686a5703a630fb6/src/components/calendar/calendar.tsx#L225

我看见[react-calender](https://projects.wojtekmaj.pl/react-calendar/)demo支持了快速切换日期，并在源码中找到了对应的功能执行
https://github.com/wojtekmaj/react-calendar/blob/b10cb99a43b079b9c36655a48590315150b625c4/src/Calendar.jsx#L463

除此之外，我看见[rc-picker](https://react-component.github.io/picker/?selectedKind=rc-picker&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)demo中也是支持日期快捷切换的。
不知antd-mobile会不会支持这个想法？

**Comment by awmleer** [comment]
是之前某次改动引入的 bug， 0030bd4b 已修复，感谢反馈
