### ISSUE TITLE
Jtest [antd-mobile: Global] The px tester is not rendering properly. Please make sure you have imported `antd-mobile/es/global`.

### ISSUE THREAD

**Issue by ykrank** [ant-design/ant-design-mobile#5192]
### Version of antd-mobile

5.12.2

### Operating system and its version

Others

### Browser and its version

console

### What happened?

使用create-react-app创建的demo，build运行时正常，但是在运行test时会提示
`console.error
    [antd-mobile: Global] The px tester is not rendering properly. Please make sure you have imported `antd-mobile/es/global`.

      at devError (node_modules/antd-mobile/cjs/utils/dev-log.js:19:13)
      at Object.<anonymous> (node_modules/antd-mobile/cjs/utils/convert-px.js:28:28)
      at Object.<anonymous> (node_modules/antd-mobile/cjs/components/popover/popover.js:36:18)`

### Relevant log output

```shell
console.error
    [antd-mobile: Global] The px tester is not rendering properly. Please make sure you have imported `antd-mobile/es/global`.

      at devError (node_modules/antd-mobile/cjs/utils/dev-log.js:19:13)
      at Object.<anonymous> (node_modules/antd-mobile/cjs/utils/convert-px.js:28:28)
      at Object.<anonymous> (node_modules/antd-mobile/cjs/components/popover/popover.js:36:18)
```

**Comment by ykrank** [comment]
`
{
  "name": "webview-demo",
  "version": "0.1.0",
  "homepage": "./",
  "private": true,
  "dependencies": {
    "@craco/craco": "^6.4.3",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.7.13",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "antd-mobile": "^5.12.2",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-router": "^6.3.0",
    "react-router-dom": "^6.3.0",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0"
  },
  "scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^14.1.1",
    "react-scripts": "5.0.1"
  }
}

`

**Comment by awmleer** [comment]
目前的确是会这样，因为在 jest 环境下是不会引入 css 文件的，我们后面再想想办法

**Comment by awmleer** [comment]
应该可以参考 #5208 这个 PR 的做法，先手动过滤一下

**Comment by perezpz** [comment]
![image](https://user-images.githubusercontent.com/10556818/199226860-640a2739-ea6d-4e71-b2e3-e138972ed995.png)
true - enable CSS modules for all files matching /\.module\.\w+$/i.test(filename) and /\.icss\.\w+$/i.test(filename) regexp.

**Comment by callmevari** [comment]
For thoose who just started a Next.js 13 + antd-mobile app and see this error, I solved it by putting this at the beggining of the **app/page.tsx** file.

```
'use client'

import 'antd-mobile/es/global';
import { Button } from 'antd-mobile'
...
```
