### ISSUE TITLE
children dose not exist on TabBarItemProps [React 18]

### ISSUE THREAD

**Issue by csc-bo** [ant-design/ant-design-mobile#5193]
### Version of antd-mobile

5.12.2

### Operating system and its version

Others

### What happened?

Add children?: React.ReactNode to TabBarItemProps.

**Comment by miracles1919** [comment]
从[代码](https://github.com/ant-design/ant-design-mobile/blob/master/src/components/tab-bar/tab-bar.tsx)看，Item 是不支持的 children 的

**Comment by awmleer** [comment]
TabBar.Item 不支持 `children` 属性
