### ISSUE TITLE
Picker columns 类型限制

### ISSUE THREAD

**Issue by a145789** [ant-design/ant-design-mobile#5199]
### Version of antd-mobile

5.12.2 

### Description

Picker columns 的 PickerColumnItem 类型 label key 都挺宽松，只有 value 限制为 string，这个有什么特殊场景么？业务里 value 为 number 类型也挺常见的，感觉放宽一点会少写一些 Number String 转换代码
```ts
export declare type PickerColumnItem = {
    label: ReactNode;
    value: string;
    key?: string | number;
};
```

**Comment by awmleer** [comment]
其实从开发者方便的角度考虑，的确应该放开成 `string | number`，之所以一直没有放开，是因为会影响到 `onChange` 的类型：

```tsx
const [v, setV] = useState<string[]>()

<Picker
  onChange={(value) = {
    setV(value) // <- 这里 ts 的类型检测会报错，因为 value 是 (string | number)[]，不能作为 setV 的参数 string[]
  }}
/>
```

如果现在调整的话，应该会导致已有的项目中出现很多报错

**Comment by awmleer** [comment]
和 #4864 重复了，这个 issue 我先关闭掉，后面可以继续订阅 & 关注那个 issue
