### ISSUE TITLE
ListView onEndReached不停调用

### ISSUE THREAD

**Issue by leonardgithub** [ant-design/ant-design-mobile#520]
本地环境

antd-mobile 版本：├─┬ antd-mobile@0.9.6
操作系统及其版本：Ubuntu 16.04
浏览器及其版本：Chrome Versión 52.0.2743.116 (64-bit)

你做了什么？

引入 antd-mobile 的 ListView, 并上拉

你期待的结果是：
ListView onEndReached使用正常

实际上的结果：
onEndReached不停调用，无法停止

可重现的在线演示
no

**Comment by dotaeye** [comment]
我也碰到这个问题，我的环境是有RefreshControl的时候 ，并且手动设置了ListView的高

**Comment by leonardgithub** [comment]
Can anyone fix this quickly? It's urgent

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/issues/452 @warmhug

**Comment by leonardgithub** [comment]
@afc163 没响应

**Comment by warmhug** [comment]
@leonardgithub  官方 demo，在你的平台和浏览器里有没有问题？需要给出能重现的例子

**Comment by leonardgithub** [comment]
官方 demo数据都是死的。我们的例子有点复杂不好贴，我想想看怎么粘到这里。我们的例子是套用了ant mobile的Tabbar, tabs, listview多种组件。

**Comment by leonardgithub** [comment]
不够活跃啊。这应该不是我一个人遇到的问题吧

**Comment by warmhug** [comment]
仔细对照 listView 的几个 demo 再结合自己代码，如果你不是用 body 滚动，你可以设置个定高、再试试看有没问题。 你这样提问题、怎么让人解答呢。。

@leonardgithub 很欢迎你把自己出问题的 demo 抽象下、欢迎提 pr ，套用了ant mobile的Tabbar, tabs, listview多种组件的 demo 我们也很需要，有 pr 我会积极合并哈。 (我看你给 tensorflow 提的 [pr](https://github.com/tensorflow/tensorflow/commits?author=leonardgithub&since=2016-10-31T16:00:00Z&until=2016-11-19T16:00:00Z) 就挺好~ )

@dotaeye 也欢迎提 RefreshControl 有问题的 demo 地址或 pr .

**Comment by leonardgithub** [comment]
@warmhug 3Q。可能是这段时间比较忙，这个问题又比较难描述，涉及较多代码，比较零散，就没有把问题描述清楚。我看下如何表达一下。谢谢

**Comment by warmhug** [comment]
ListView 在滑动到达 onEndReachedThreshold 指定的距离后，继续滑动，会通过 scroll 事件、每隔 scrollEventThrottle 设置的时间、就会触发一次 onEndReached 回调。这个行为和 react-native ListView 表现一致。所以 onEndReached 是可能会调用许多次的，如果要 Ajax 请求数据，自己在里边做判断、确保只用请求一次。

这种行为看似不合理，其实没什么问题，实际项目里可以结合一次 Ajax 请求开始到结束的 loading 状态来做。

**Comment by zhangda47** [comment]
@leonardgithub 我也碰到了这个问题，最后是如何解决的

**Comment by dreamllq** [comment]
这个onEndReached太坑了。。我理解的 ：你们判断渲染的DOM长度和datasource里的长度一致时，调用onEndReached函数，是为了预加载一页的数据，但是现在 你预加载一页数据的时候，没有按照pageSize的大小进行渲染，然后就导致渲染的DOM长度和datasource里的长度同时增加，然后就出现了递归调用，而这个递归又没有出口 ，就会导致循环调用onEndReached函数。

**Comment by jxintang** [comment]
@warmhug  貌似不能通过Ajax的请求开始和介乎的loading状态来判断吧？
因为ajax结束时loading状态为false，但是此时onEndReached方法可能仍然在执行（被循环调用），但这时loading状态已经为false

**Comment by dancinglone** [comment]
@jxintang 是的，我也是像你这样理解，并且遇到这样的问题。ajax结束时，loading状态变为false，onEndReached 还是会执行。   并且，refreshControl组合在一起用的时候，下拉刷新清空了列表，同样会触发onEndReached，但这时并不是“onEndReachedThreshold 指定的距离后，继续滑动”.   求解。

**Comment by warmhug** [comment]
@dancinglone @jxintang 可以看下上边这个新的 commit 的做法

**Comment by zhengxianyu** [comment]
在onEndReached里面判定一下你的数据长度是不是已经到了最后，不是最后再把isLoading设置为true，就可以了，不能再没有条件的情况下把isLoading直接设置为true，会导致一直循环。

**Comment by zhengxianyu** [comment]
在onEndReached里面判断一下数据是否已经加载完全，如果没有加载完毕再把isLoading设置为true，就可以了。就是，在设置isLoading为true前加个条件，不要直接写

**Comment by dancinglone** [comment]
@warmhug 还是不太理解呢。

**Comment by dancinglone** [comment]
@warmhug 
感谢回复！
我的场景可能有点不一样。
是这样的。我是列表是整合了refreshControl和上拉加载更多，用redux管理状态。 下拉刷新的时候，为了更新列表，会清空列表。数据未返回的时候，可以通过状态判断去阻止onEndReadched回调中接口请求的发起。但问题是，数据返回后，我把刷新状态设为“非刷新中”状态后，会在短暂的时间内，列表界面还没渲染出来，还是会发生onEndReached的回调，并且状态已经是“非刷新中”，所以会导致发起了数据请求。

@jxintang 你的问题是否也一样？

**Comment by 35860368** [comment]
我也碰到了类型的问题，但是我是在下拉刷新的时候出现下拉刷新无法结束的情况，我们的列表是套用了ant mobile的ListView, RefreshControl组件。数据方面，数据官方demo的写死的数据，我这里通过异步请求的数据

**Comment by leonardgithub** [comment]
@dancinglone 应该是这种情况。个人认为，即使不是fetch获取数据，onEndReached也不应该不停地被调用才对。

**Comment by dancinglone** [comment]
@leonardgithub 嗯，这个需要慢慢完善吧。我更着急现在问题怎样解决呢，有什么idea不，求指点。 我怀疑只是我没有理解清楚一些什么 。这个是比较常规的东西，如果有问题应该好多人会遇到啊。

**Comment by warmhug** [comment]
> 数据返回后，我把刷新状态设为“非刷新中”状态后，会在短暂的时间内，列表界面还没渲染出来，还是会发生onEndReached的回调

@dancinglone  这个可能会出现，设置下`scrollEventThrottle`，或者 settimeout 试试。

@35860368  现在 demo 的数据虽然是写死，但已经用 settimeout 模拟 ajax 返回了、基本和真实场景一样。另外 RefreshControl 遇到的问题，建议做个能跑的 demo，放到 GitHub 上我一起看下，可以参考 https://github.com/ant-design/antd-mobile-samples/tree/master/web-webpack 这里做下。

@leonardgithub  onEndReached 多次被调用 和 react-native ListView  表现一致，至于这样是否合理正确，也认为有待确认。

**Comment by 35860368** [comment]
@warmhug  
这是我的代码
onRefresh = () => {
    this.initData = [];
    this.setState({
      refreshing: true,
    });
    const param = { pageIndex: 1, pageSize: 10, listTitile: '美食' };
    this.props.dispatch({ type: 'list/fetchonRefresh', payload: param });
  };
我的意思是settimeout 只是模拟ajax数据返回，但是在实际情况中，我这边的情况是，只有当有请求返回的时候才去执行  this.setState({refreshing: false, });

**Comment by 35860368** [comment]
@warmhug 页面代码

import React, { Component } from 'react';
import { connect } from 'dva';
import { RefreshControl, ListView } from 'antd-mobile';

// let index = data.length - 1;

// const pageIndex = 0;

class List extends Component {
  constructor(props) {
    super(props);
    const dataSource = new ListView.DataSource({
      rowHasChanged: (row1, row2) => row1 !== row2,
    });

    this.initData = [];
    this.state = {
      dataSource: dataSource.cloneWithRows(this.initData),
      refreshing: false,
      pageIndex: 0,
      index: 0,
    };
  }

  componentDidMount() {
    const param = { pageIndex: 1, pageSize: 10, listTitile: '美食' };
    this.props.dispatch({ type: 'list/fetchList', payload: param });
  }
  componentWillReceiveProps(nextProps) {
    // console.log('componentWillReceiveProps');
    const { resData } = nextProps;
    // console.log('componentWillUpdate==>', resData);
    this.initData = [];
    if (resData.length > 0) {
      for (const v of resData) {
        this.initData.push(v.id);
      }
      this.setState({
        dataSource: this.state.dataSource.cloneWithRows(this.initData),
        index: this.initData.length - 1,
      });
      // console.log('componentWillUpdate.initData==>', this.initData);
      // this.state = {
      //   dataSource: this.state.dataSource.cloneWithRows(this.initData),
      //   index: this.initData.length - 1,
      // };
    }
  }
  shouldComponentUpdate(nextProps, nextState) {
    // console.log('shouldComponentUpdate.resData==>', nextProps.resData);
    // console.log('shouldComponentUpdate.nextState==>', nextState.refreshing);
    if (nextProps.route.path === '/main/list') {
      return true;
    }
    if (this.props.resData
      !== nextProps.resdata
      || this.state.refreshing
      !== nextState.refreshing) {
      return true;
    }
    return false;
  }
  componentWillUpdate(nextProps, nextState) {
    // console.log('componentWillUpdate==>', nextState.refreshing);
    // this.setState({ refreshing: false });
  }
  componentDidUpdate() {

  }
  onRefresh = () => {
    this.setState({ refreshing: true });
    setTimeout(() => {
      this.initData = [];
      const param = { pageIndex: 1, pageSize: 10, listTitile: '美食' };
      this.props.dispatch({ type: 'list/fetchonRefresh', payload: param });
    }, 1000);
  };
  onScroll = () => {
    // console.log('sss');
  };
  render() {
    // console.log('1');
    const { resData } = this.props;
    // console.log('render_resDate==>', resData);
    // if (resData) {
    //   this.state = {
    //     dataSource: this.state.dataSource.cloneWithRows(this.initData),
    //   };
    // }
    const separator = (sectionID, rowID) => (
      <div
        key={`${sectionID}-${rowID}`}
        style={{
          backgroundColor: '#F5F5F9',
          height: 8,
          borderTop: '1px solid #ECECED',
          borderBottom: '1px solid #ECECED',
        }}
      />
    );
    const row = (rowData, rowID) => {
      if (this.state.index >= 0) {
        const obj = resData[this.state.index--];
        return (
          <div key={rowID} style={{ padding: '0.08rem 0.16rem', backgroundColor: 'white' }}>
            <h3 style={{ padding: 2, marginBottom: '0.08rem', borderBottom: '1px solid #F6F6F6' }}>
              {obj.title}
            </h3>
            <div style={{ display: '-webkit-box', display: 'flex' }}>
              <img style={{ height: '1.28rem', marginRight: '0.08rem' }} src={obj.img} />
              <div style={{ display: 'inline-block' }}>
                <p>{obj.des}-{rowData}</p>
                <p><span style={{ fontSize: '1.6em', color: '#FF6E27' }}>{obj.price}</span>元/任务</p>
              </div>
            </div>
          </div>
        );
      }
    };
    console.log(this.props.loading);
    return (
      <ListView
        dataSource={this.state.dataSource}
        renderRow={row}
        renderSeparator={separator}
        initialListSize={5}
        pageSize={5}
        scrollRenderAheadDistance={200}
        scrollEventThrottle={20}
        onScroll={this.onScroll}
        style={{
          height: document.documentElement.clientHeight,
          border: '1px solid #ddd',
          margin: '0.1rem 0',
        }}
        scrollerOptions={{ scrollbars: true }}
        refreshControl={<RefreshControl
          refreshing={this.props.loading}
          onRefresh={this.onRefresh}
        />}
      />
    );
  }
}

export default connect(({ list }) => ({
  resData: list.resdata,
  loading: list.loading,
}))(List);

**Comment by 35860368** [comment]
@warmhug
//页面代码 ，然后this.setState({refreshing: false, });我是通过yield put({ type: 'loading', payload: false });
//来实现改变刷新状态
import React, { Component } from 'react';
import { connect } from 'dva';
import { RefreshControl, ListView } from 'antd-mobile';

// let index = data.length - 1;

// const pageIndex = 0;

class List extends Component {
  constructor(props) {
    super(props);
    const dataSource = new ListView.DataSource({
      rowHasChanged: (row1, row2) => row1 !== row2,
    });

    this.initData = [];
    this.state = {
      dataSource: dataSource.cloneWithRows(this.initData),
      refreshing: false,
      pageIndex: 0,
      index: 0,
    };
  }

  componentDidMount() {
    const param = { pageIndex: 1, pageSize: 10, listTitile: '美食' };
    this.props.dispatch({ type: 'list/fetchList', payload: param });
  }
  componentWillReceiveProps(nextProps) {
    // console.log('componentWillReceiveProps');
    const { resData } = nextProps;
    // console.log('componentWillUpdate==>', resData);
    this.initData = [];
    if (resData.length > 0) {
      for (const v of resData) {
        this.initData.push(v.id);
      }
      this.setState({
        dataSource: this.state.dataSource.cloneWithRows(this.initData),
        index: this.initData.length - 1,
      });
      // console.log('componentWillUpdate.initData==>', this.initData);
      // this.state = {
      //   dataSource: this.state.dataSource.cloneWithRows(this.initData),
      //   index: this.initData.length - 1,
      // };
    }
  }
  shouldComponentUpdate(nextProps, nextState) {
    // console.log('shouldComponentUpdate.resData==>', nextProps.resData);
    // console.log('shouldComponentUpdate.nextState==>', nextState.refreshing);
    if (nextProps.route.path === '/main/list') {
      return true;
    }
    if (this.props.resData
      !== nextProps.resdata
      || this.state.refreshing
      !== nextState.refreshing) {
      return true;
    }
    return false;
  }
  componentWillUpdate(nextProps, nextState) {
    // console.log('componentWillUpdate==>', nextState.refreshing);
    // this.setState({ refreshing: false });
  }
  componentDidUpdate() {

  }
  onRefresh = () => {
    this.setState({ refreshing: true });
    setTimeout(() => {
      this.initData = [];
      const param = { pageIndex: 1, pageSize: 10, listTitile: '美食' };
      this.props.dispatch({ type: 'list/fetchonRefresh', payload: param });
    }, 1000);
  };
  onScroll = () => {
    // console.log('sss');
  };
  render() {
    // console.log('1');
    const { resData } = this.props;
    // console.log('render_resDate==>', resData);
    // if (resData) {
    //   this.state = {
    //     dataSource: this.state.dataSource.cloneWithRows(this.initData),
    //   };
    // }
    const separator = (sectionID, rowID) => (
      <div
        key={`${sectionID}-${rowID}`}
        style={{
          backgroundColor: '#F5F5F9',
          height: 8,
          borderTop: '1px solid #ECECED',
          borderBottom: '1px solid #ECECED',
        }}
      />
    );
    const row = (rowData, rowID) => {
      if (this.state.index >= 0) {
        const obj = resData[this.state.index--];
        return (
          <div key={rowID} style={{ padding: '0.08rem 0.16rem', backgroundColor: 'white' }}>
            <h3 style={{ padding: 2, marginBottom: '0.08rem', borderBottom: '1px solid #F6F6F6' }}>
              {obj.title}
            </h3>
            <div style={{ display: '-webkit-box', display: 'flex' }}>
              <img style={{ height: '1.28rem', marginRight: '0.08rem' }} src={obj.img} />
              <div style={{ display: 'inline-block' }}>
                <p>{obj.des}-{rowData}</p>
                <p><span style={{ fontSize: '1.6em', color: '#FF6E27' }}>{obj.price}</span>元/任务</p>
              </div>
            </div>
          </div>
        );
      }
    };
    console.log(this.props.loading);
    return (
      <ListView
        dataSource={this.state.dataSource}
        renderRow={row}
        renderSeparator={separator}
        initialListSize={5}
        pageSize={5}
        scrollRenderAheadDistance={200}
        scrollEventThrottle={20}
        onScroll={this.onScroll}
        style={{
          height: document.documentElement.clientHeight,
          border: '1px solid #ddd',
          margin: '0.1rem 0',
        }}
        scrollerOptions={{ scrollbars: true }}
        refreshControl={<RefreshControl
          refreshing={this.props.loading}
          onRefresh={this.onRefresh}
        />}
      />
    );
  }
}
export default connect(({ list }) => ({
  resData: list.resdata,
  loading: list.loading,
}))(List);

**Comment by warmhug** [comment]
@35860368 多为别人想一下，请把这里贴的代码删掉吧。没有格式化 或 太长的代码不用贴出来，影响别人看 issue 。

另外按我说的贴在你 GitHub 上能直接下载下来跑的代码、给我连接地址。避免其他问题带来的干扰

**Comment by xoptimal** [comment]
@warmhug  参考最新 commit ~  仍然有不解的地方, 还请指教 !

场景:  ListView 列表  -> 滑动到底部 -> 加载更多 -> 触发 onEndReached  关键代码:

```
onEndReached = (event) => {
    if (event && this.props.loadMore) {
      const {isLoadMore, loadMore} = this.props.loadMore;
      if (isLoadMore) {
        if (!this.state.isLoading) {
          this.setState({isLoading: true, loadMoreValue: '加载中...'});
          loadMore(this.onLoadMoreCallback.bind(this));
        }
      } else {
        this.setState({loadMoreValue: '加载完毕'});
      }
    }
  }
```

说明:  
* 判断条件有三个( 是否使用加载更多, 是否正在加载, 是否还有更多) ... 
* 在测试网络断开的情况下,  就出现了 onEndReached  被触发多次的问题 ~

网络请求关键代码 (dva -> fetch):
```
try {
  const result = yield call(FindService.requestCommodity, {page: tempPage});

  yield put({
    type   : 'saveFindList',
    payload: {
      list     : result.list,
      pageCount: result.pageCount,
      page     : tempPage,
      hasLoadMore
    }
  });
  yield callback(SUCCESS);
} catch (err) {
  yield callback(FAILED);
}

```

回调处理关键代码:
```
  onLoadMoreCallback(state) {
    const stateValue = state == 1 ? '加载中' : state == 2 ? '没有更多' : state == 3 ? '加载失败' : '加载更多';
    this.setState({isLoading: false, loadMoreValue: stateValue});
  }
```


**问题: **
网络异常, 直接抛Error ,  走 callback , 导致 isLoading 为 true, 然后 onEndReached  自动被触发, 而且触发多次

**期待结果:** 
请问如何让它只触发一次 ~

**Comment by warmhug** [comment]
@xoptimal  网络异常 回调里，能把 isLoading、loadMore 这些都设为 false 吗？

**Comment by xoptimal** [comment]
@warmhug  每次请求结果, 都会判断是否还有加载更多,  以及设置isLoading 为false ,   我目前的做法是为了避免多次请求,  在请求结果上, 做了个延迟的处理,  是失败的情况下, 需要过5秒才可重新请求,  但是这个用户体验感觉并不好 .... 后续的5秒用户只能等待 ~

**Comment by GZWZC** [comment]
@xoptimal 我也是用状态管理着，noMore isLoading哈哈，但是我想问问你有没有做服务端渲染

**Comment by GZWZC** [comment]
@leonardgithub 你好 我想问一下你，你是用react开发还是react-native开发，使用listView的时候有依赖react-native吗

**Comment by leonardgithub** [comment]
@GZWZC web用react, app用RN

**Comment by GZWZC** [comment]
@leonardgithub 那你用react的时候，有没有安装react-native?  import{ listView } from antd-mobile 会不会 Can't resolve 'react-native'    ，

**Comment by leonardgithub** [comment]
没安装RN

**Comment by liuming0712** [comment]
尝试把每页的条数增大一些，请求的数据填充的页面高度少于设定容器的高度会自动触发onEndReached事件

**Comment by szqiuboshi** [comment]
请问这个问题解决了没

**Comment by ylquankai** [comment]
+1

**Comment by leonardgithub** [comment]
I do know why this problem still exist now, can't fix this bug?

**Comment by warmhug** [comment]
@leonardgithub this is not a bug, it's Normal behavior.

**Comment by leonardgithub** [comment]
Not a bug? But why so many users encounter this problem?

**Comment by leonardgithub** [comment]
My issue was referred by other user, I am not the only user which encounter the problem, please check https://github.com/TerryBeanX2/Webpack-React-Router-Redux-ES6#几点心得

**Comment by leonardgithub** [comment]
If such a problems exists, can the antd-mobile's ListView be used in the production environment?

**Comment by Jude214** [comment]
使用以下代码貌似可以解决
`//hide the toast in a short time delay,otherwise loading toast won't be shown if hidden immediately
	hideLoading = (msg) => {
		setTimeout(()=>{ 
			Toast.hide();
			if (msg) {
				Toast.info(msg, 1.5);
			}
		}, 1000);
	};
	setNoLoading = (msg) => {
		this.hideLoading(msg);
		setTimeout(()=>{
			this.setState({isLoading: false});
		},3000);
	};
	onReachEnd = (e) => {
		console.log('上拉',this.state.isLoading);
		if (this.state.isLoading) {
			return
		}
		if (!this.hasMore) {
			Toast.info('无更多数据', 1.5);
			return;
		}
		this.setState({isLoading: true});
		let last = this.recordData[this.recordData.length - 1];
		if (last && last.time) {
			Toast.loading('加载中', 10);
			Service.traceList('0', last.time).then((response) => {
				if (response.code == 1) {
					this.setNoLoading();
					this.hasMore = response.hasMore || false;
					let newL = response.info || [];
					this.recordData = this.recordData.concat(newL);
					this.setState({
						dataSource: this.state.dataSource.cloneWithRows(this.recordData)
					});
				} else {
					this.setNoLoading(response.msg);
				}
			}, (error) => {
				this.setNoLoading();
			});
		}
	};`

**Comment by Jude214** [comment]
使用以下代码似乎能解决不断请求的问题
//hide the toast in a short time delay,otherwise loading toast won't be shown if hidden immediately
hideLoading = (msg) => {
       setTimeout(()=>{ 
             Toast.hide();
             if (msg) {
                  Toast.info(msg, 1.5);
			}
		}, 1000);
	};
	setNoLoading = (msg) => {
		this.hideLoading(msg);
		setTimeout(()=>{
			this.setState({isLoading: false});
		},3000);
	};
	onReachEnd = (e) => {
		console.log('上拉',this.state.isLoading);
		if (this.state.isLoading) {
			return
		}
		if (!this.hasMore) {
			Toast.info('无更多数据', 1.5);
			return;
		}
		this.setState({isLoading: true});
		let last = this.recordData[this.recordData.length - 1];
		if (last && last.time) {
			Toast.loading('加载中', 10);
			Service.traceList('0', last.time).then((response) => {
				if (response.code == 1) {
					this.setNoLoading();
					this.hasMore = response.hasMore || false;
					let newL = response.info || [];
					this.recordData = this.recordData.concat(newL);
					this.setState({
						dataSource: this.state.dataSource.cloneWithRows(this.recordData)
					});
				} else {
					this.setNoLoading(response.msg);
				}
			}, (error) => {
				this.setNoLoading();
			});
		}
	};

**Comment by allan2coder** [comment]
is there anyone who solve this problem?

**Comment by warmhug** [comment]
In antd-mobile@2.0 , you can use PullToRefersh and [react-infinite](https://github.com/seatgeek/react-infinite) or your custom infinite-scroll.
@paranoidjk will add them soon.

**Comment by camnpr** [comment]
关于onEndReached 我的处理是：
`onEndReached = (event) => {
      // load new data
      // hasMore: from backend data, indicates whether it is the last page, here is false
      // 没有任何在加载的状态，  event对象不会空， 数据集大于等于每页的个数， 没有更多记录
      if (this.state.isLoading || !event || dataList.length<10 || !this.state.hasMore) {
        return;
      }
      this.setState({ isLoading: true });
      this.fetchData('Home/Search', {action:'quanziList', pageNo: ++pageIndex, uid:this.state.uid, type:this.state.type});
    }`
测试滑动加载，不会重复请求多次。
你的接口数据，要返回总数，以在componentWillReceiveProps里来更新hasMore。
例子地址：https://www.kuabaobao.com/quanzi
关于：cloneWithRowsAndSections 弄数据，有点怪怪的。
参考说明：https://github.com/ant-design/ant-design-mobile/blob/master/components/list-view/index.zh-CN.md
也许这个RefreshControl和ListView终要被PullToRefersh和react-infinite代替。

**Comment by Tsionhe** [comment]
监测滚动的距离
```
onScroll = (event) => {
   if(this.state.isLoading) {
      this.state.scrollTop = event.target.scrollTop
    }
}
```

页面渲染完执行滚动到原位置
```
this.lv.scrollTo(0, this.state.scrollTop)
```

**Comment by yibingxiong** [comment]
It's too hard!(我太难了)
