### ISSUE TITLE
SearchBar 搜索框 取消功能不生效

### ISSUE THREAD

**Issue by githubqh** [ant-design/ant-design-mobile#5201]
### Description

![image](https://user-images.githubusercontent.com/105548468/168722982-ac72253f-11cf-4dbf-aeff-627ef37e5530.png)
import React, { useState, Component } from "react";
import { Card, Toast, Space, Button, Tabs, SearchBar } from "antd-mobile";
import { render } from "react-dom";

export default class App extends Component {
  state = {
    arr: [
      {
        title: "测试环境池",
        content: "123"
      },
      {
        title: "移动化环境池",
        content: "456"
      },
      {
        title: "话务量工具环境池",
        content: "789"
      }
    ]
  };
  handleSearch(val) {
    const { arr } = this.state;
    const oldarr = arr
    if (!val.trim()) {
      Toast.show({
        content: "搜索内容不能为空！"
      });
      return;
    }
    const newarr = arr.filter((item) => {
      return item.title.includes(val);
    });

    this.setState({ arr: newarr });
  }

  handleCancelSearch() {
    Toast.show({
      content: "取消搜索"
    });
    // this.setState({ arr: oldarr });
  }
  render() {
    const { arr } = this.state;
    
    
    return (
      < >
        <SearchBar
          onSearch={(val) => this.handleSearch(val)}
          onCancel={() => this.handleCancelSearch()}
          placeholder="请输入内容"
          showCancelButton
        />
        {arr.map((item) => {
          return <Card title={item.title}>{item.content}</Card>;
        })}
      </>
    );
  }
}

**Comment by GOWxx** [comment]
官网即可复现 版本[v5.12.3]
https://mobile.ant.design/zh/components/search-bar
<img width="1682" alt="image" src="https://user-images.githubusercontent.com/12870715/168724171-1316321c-ccf8-483c-9896-379983f05bc9.png">

**Comment by awmleer** [comment]
又改了一下 8337f706
