### ISSUE TITLE
自定义label后，报错信息 显示 undefined

### ISSUE THREAD

**Issue by wulisensen** [ant-design/ant-design-mobile#5202]
### Version of antd-mobile

5.10.2

### Operating system and its version

Others

### Browser and its version

chrome101.0.4951.64

### What happened?

自定义label，传入了dom，结果 报错显示 undefined 
![image](https://user-images.githubusercontent.com/22022130/168795870-ff3e37db-3313-4f0b-8edc-8b106c00cbf4.png)

原因是代码里 判断 label 是string才会使用
![image](https://user-images.githubusercontent.com/22022130/168796067-c7c9a124-6645-44aa-b18a-f52960e83bad.png)

**Comment by 13725102796** [comment]
你应该把你自定义label的代码发出来

**Comment by awmleer** [comment]
估计是传了个 ReactNode

**Comment by awmleer** [comment]
e8e2810f 已修复

**Comment by wulisensen** [comment]
> 你应该把你自定义label的代码发出来

![image](https://user-images.githubusercontent.com/22022130/169193475-2ea4453a-a2a5-4696-aadd-2a4e727c3e50.png)
