### ISSUE TITLE
自定义数组在选择器中没有显示

### ISSUE THREAD

**Issue by githubqh** [ant-design/ant-design-mobile#5206]
### Description

![image](https://user-images.githubusercontent.com/105548468/168991162-93d54eea-168d-499c-8a88-4a8390072ce6.png)
![image](https://user-images.githubusercontent.com/105548468/168991178-fc4d745c-30d1-42c0-b514-dd7e175641b5.png)

demo如下：
import React, { RefObject,useState } from 'react'
import {
  Form,
  Input,
  Button,
  Dialog,
  Picker,
  DatePicker,
  Selector,
  Slider,
  Stepper,
  Switch,
} from 'antd-mobile'
import dayjs from 'dayjs'

export default () => {
  const onFinish = (values: any) => {
    Dialog.alert({
      content: <pre>{JSON.stringify(values, null, 2)}</pre>,
    })
  }
  const [visible1, setVisible1] = useState(false);
  const [value, setValue] = useState<(string | null)[]>(['M'])
  const longOptions = [[]]
  for (let i = 1; i <= 3; i++) {
    longOptions[0].push({ lable:i.toString(),value: i.toString() })
}
const basicColumns = [
  [
    { label: 'Foo', value: 'foo' },
    { label: 'Bar', value: 'bar' },
  ]
]
console.log(longOptions)
console.log(basicColumns)
  return (
    <>
      <Form
        name='form'
        onFinish={onFinish}
        footer={
          <Button block type='submit' color='primary' size='large'>
            提交
          </Button>
        }
      >
        <Form.Header>基础用法</Form.Header>
       
        <Form.Item
          name='scheduledTime'
          label='申请时长'
          trigger='onConfirm'
          onClick={() => {
              setVisible1(true);
          }}
          rules={[{ required: true }]}
        >
          <Picker
        columns={longOptions
          }
        visible={visible1}
        onClose={() => {
          setVisible1(false)
        }}
        value={value}
        onConfirm={v => {
          setValue(v)
        }}
      />
        </Form.Item>
       
      </Form>
    </>
  )
}

**Comment by yaogengzhu** [comment]
建议写一个复现一个demo. 不用贴这么多代码
https://mobile.ant.design/zh/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-codesandbox-%E4%B8%8A%E5%86%99%E4%B8%80%E4%B8%AA%E5%A4%8D%E7%8E%B0-demo

**Comment by githubqh** [comment]
> 建议写一个复现一个demo. 不用贴这么多代码 https://mobile.ant.design/zh/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-codesandbox-%E4%B8%8A%E5%86%99%E4%B8%80%E4%B8%AA%E5%A4%8D%E7%8E%B0-demo
请查看链接demo
https://codesandbox.io/embed/cocky-swirles-u4ezed?fontsize=14&hidenavigation=1&theme=dark

**Comment by yaogengzhu** [comment]
看下你的demo , 你写错了。
![image](https://user-images.githubusercontent.com/42566669/169006875-dfacc583-46ea-4434-9995-e2dbfcfcf345.png)

**Comment by githubqh** [comment]
> 看下你的demo , 你写错了。 ![image](https://user-images.githubusercontent.com/42566669/169006875-dfacc583-46ea-4434-9995-e2dbfcfcf345.png)

。。。。。写了一天代码都晕了。。。感谢
