### ISSUE TITLE
Web 下和taobaofed 的 react-web区别

### ISSUE THREAD

**Issue by IDrinkMoreWater** [ant-design/ant-design-mobile#521]
**taobaofed 之前有个 react-web,做了react native 语法和api的compatible,和react native保持一致,包括css layout输出成web样式,编译时直接输出android,ios,web展现一致的bundle.真正做到三端的Learn Once, Write Anywhere**

**ant-design-mobile的web支持是否类似,还是说只是实现了风格一致的组件,以后web部分是否有计划实现react native的compatible**

**Comment by silentcloud** [comment]
@IDrinkMoreWater 大部分组件的 API 都是 web 端和 RN 端通用的，也就是同样的写法都能 ok

**Comment by IDrinkMoreWater** [comment]
@silentcloud 有个困惑如果要API一致的话是要实现如下全部的API的:

```
APIs:

Alert - ReactAlert
AlertIOS - ReactAlert
Animated - ReactAnimated
AppRegistry - ReactAppRegistry
AsyncStorage - ReactAsyncStorage
Dimensions - ReactDimensions
Easing - ReactEasing
InteractionManager - ReactInteractionManager
LayoutAnimation - ReactLayoutAnimation
PanResponder - ReactPanResponder
PixelRatio - ReactPixelRatio
StyleSheet - ReactStyleSheet
```
而我在ant-design-mobile的源码里面没有看到这些

**Comment by silentcloud** [comment]
我们是以 antd-mobile 的组件写的页面来渲染 web 端和 rn 端，而不是以 rn  页面来适配 antd-mobile，也就是说 antd-mobile => rn，而不是  rn => antd-mobile

**Comment by IDrinkMoreWater** [comment]
谢谢,可以这样理解吧,antd-mobile自身只是rn自带组件不足的扩展,antd-mobile的web也是(对h5的扩展),所以antd-mobile => rn(原生web),但如果要实现移动端和web端(毕竟rn和web的语法不一样,单layout部分就差很多了,rn的layout是web的css的阉割加变种)的话必须写两套src了;但如果像taobaofed 的 react-web那样的话就可以实现共用一份src了(单要做扩展的就很累的,同样的组件都得扩展一遍),两者的目标不一样喽;不知道我这样理解对不对

**Comment by silentcloud** [comment]
恩，antd-mobile 跟 react-web 是相反的，他们是 rn=>web；antd-mobile 同一个组件(比如: Flex)，需要实现两个平台(web,rn)的代码，Flex.web.js (web) 和 Flex.js (rn)，但暴露给用户最终使用的时候只需要写一份 `<Flex>...</Flext>` 这样即能跑在 web 端，又能跑在 rn 端

**Comment by IDrinkMoreWater** [comment]
@silentcloud 嗯嗯,taobaofed的想法很好,那样子的话逻辑上生产力有提高,但是太折腾了,会出不少问题facebook官方react-native都没去兼容web是有原因的;还是分开实现,分开扩展问题少些;但谁知道以后呢,前端的人就是喜欢折腾,哈哈,问题我关闭了哈.

**Comment by leonardgithub** [comment]
很赞同上边 @IDrinkMoreWater 说的。
react-web貌似目前能实现简单的东西，并且之前在ubuntu执行CLI都报错。
类似的有个react-native-web，老外的。
用React和RN，还是建议界面分开做。毕竟APP和web实现差别还是有点大，过于兼容可能会导致性能下降。
