### ISSUE TITLE
Input 组件在 IOS 原生拼音输入法中输入几个拼音，先不上屏中文，然后点击 Input 的清除按钮，再输入几个拼音，发现无法输入。

### ISSUE THREAD

**Issue by zzbo** [ant-design/ant-design-mobile#5212]
### Version of antd-mobile

5.12.4

### Operating system and its version

iOS 13.6.1 

### Browser and its version

iOS 13.6.1 Safari

**Comment by zzbo** [comment]
类似于这个问题 https://stackoverflow.com/questions/63527069/ios-safari-input-typing-issue-when-clear-value

**Comment by awmleer** [comment]
需要提供一个复现 demo 和录屏视频，不然我们没有办法帮你排查

**Comment by zzbo** [comment]
https://user-images.githubusercontent.com/3053640/169471545-0da4bb1a-ecc3-4fb8-a91b-17018aa11f5b.mp4

**Comment by zzbo** [comment]
代码如下：
https://codesandbox.io/s/autumn-bird-y07yfm?file=/src/styles.css

**Comment by zzbo** [comment]
代码如下：
https://codesandbox.io/s/autumn-bird-y07yfm?file=/src/App.js

**Comment by zzbo** [comment]
@awmleer

**Comment by awmleer** [comment]
我先标上 help wanted 求支援

@zzbo 你可以再补充一下更具体的信息，例如机型、iOS 的具体版本、使用的哪个浏览器

**Comment by awmleer** [comment]
不知道哪位朋友能复现出来，issue 先继续挂在这里吧

**Comment by zzbo** [comment]
@awmleer  iOS 13.6.1 Safari，一定要使用系统自带的原生输入法，才有这个问题。

**Comment by awmleer** [comment]
要不你用原生的input对比一下试试？确认一下是不是iOS系统的问题

**Comment by miracles1919** [comment]
试了下是原生 input 的问题，[codesandbox](https://codesandbox.io/s/input-xdkr1s?file=/public/index.html)

System: IOS 13.3 Safari

复现步骤
1. 连接 mac，进入 Safari 调试模式
2. 输入中文 `ceshi`
3. 在 mac safari 控制台执行 `document.getElementById('input').value = ''` （清除手机 Safari 里 input 的 value）
4. 再次输入中文，会发现失去焦点，无法输入内容
5. 手动触发焦点后，才能再次输入

**Comment by miracles1919** [comment]
https://user-images.githubusercontent.com/22469543/169785072-6460e95e-4b19-4c9b-869f-098ce98f59cd.mp4

**Comment by miracles1919** [comment]
诶.. 我的 IOS 15.4.1 也有这个问题..

**Comment by miracles1919** [comment]
是不是可以加个字段控制下，在输入拼音的时候（`onCompositionStart`、`onCompositionEnd`），不展示 clear icon

**Comment by awmleer** [comment]
加个字段感觉有点挫……我过段时间试试看有没有别的办法能规避这个问题

**Comment by miracles1919** [comment]
试了下 React 组件库普遍有这个问题，Vue 组件库如果通过 `onInput` 获取 value 也会有这个问题，通过 `v-model` 获取就不会

> 对于需要使用[输入法](https://en.wikipedia.org/wiki/Input_method) (如中文、日文、韩文等) 的语言，你会发现 v-model 不会在输入法组织文字过程中得到更新。如果你也想响应这些更新，请使用 input 事件监听器和 value 绑定来替代 v-model。

**Comment by zzbo** [comment]
之前试过重渲染这个 input 控件：在 onClear 事件之后，修改 input 的 key 值。但这样没法 focus，貌似现在Chrome, Safari 禁掉了 foucs() 。

**Comment by xiaoyao96** [comment]
我实操发现有两个解决方案有效：
1、如果在拼音过程按下clear按钮，则主动让input失焦
2、在拼音过程中不显示clear按钮

**Comment by awmleer** [comment]
看起来方案 1 比较稳 🐮

**Comment by xiaoyao96** [comment]
我用官网的demo，测了一下安卓和mac系统，在点击清除后，均能正常显示输入值。
目前只有ios有这个问题，要不要只判断ios系统使用下述方案？

> 1、如果在拼音过程按下clear按钮，则主动让input失焦（nativeInputRef.current.blur)

**Comment by xiaoyao96** [comment]
我用官网的demo，测了一下安卓和mac系统，在点击清除后，均能继续输入并正常显示输入值。
目前只有ios有这个问题，要不要只判断ios系统使用下述方案？

> 1、如果在拼音过程按下clear按钮，则主动让input失焦（nativeInputRef.current.blur)

**Comment by miracles1919** [comment]
> 看起来方案 1 比较稳 🐮

这个拼音中.. 不得加个字段么 👀

**Comment by awmleer** [comment]
“拼音中”可以在组件内部加个 ref 来存储状态……？onCompositionStart onCompositionEnd 的时候设置一下 ref 的值

**Comment by miracles1919** [comment]
> “拼音中”可以在组件内部加个 ref 来存储状态……？onCompositionStart onCompositionEnd 的时候设置一下 ref 的值

我就这个意思... 👐

**Comment by awmleer** [comment]
噢噢，我还以为是说要增加一个属性 😅
