### ISSUE TITLE
PickerView内onChange的触发判断

### ISSUE THREAD

**Issue by ChaoqiYin** [ant-design/ant-design-mobile#5215]
### Version of antd-mobile

5.10.4

### What is this feature about?

代码示例：
`<PickerView value={aValue} onChange={(value): void => setAValue(value)}/>`

pickerView内部是直接判断value是否全等，即`if (props.value === innerValue)`。
但是value是一个数组类型，全等判断的是引用是否相等。导致必须在onChange时将返回的value直接set。如果做了其他处理或不使用此value数组，会导致无限onChange。是否可以通过在内部判断数组内值是否都对等来触发onChange

**Comment by awmleer** [comment]
可以提供一个更具体的 demo 么？
https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by ChaoqiYin** [comment]
抱歉，看起来应该是项目自身代码问题导致的无限刷新
