### ISSUE TITLE
ant-mobile的设计稿是多少？

### ISSUE THREAD

**Issue by wangweizm** [ant-design/ant-design-mobile#5219]
### Description

请问我在umi做移动端适配，是配置750还是375呢，使用了：postcss-px-to-viewport

**Comment by awmleer** [comment]
因为不太清楚你说的配置是指什么，所以没有办法给你确定的回答，高清适配相关的文档在[这里](https://mobile.ant.design/zh/guide/hd)

**Comment by wangweizm** [comment]
375
&nbsp;


﹏﹏若即√
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月4日(星期一) 下午3:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-mobile] ant-mobile的设计稿是多少？ (Issue #5219)





  
Version of antd-mobile
 
No response
 
Description
 
请问我在umi做移动端适配，是配置750还是375呢，使用了：postcss-px-to-viewport
  
请问解决了吗？
