### ISSUE TITLE
Card.Footer 组件content传入React.Element报错

### ISSUE THREAD

**Issue by F-happy** [ant-design/ant-design-mobile#522]
#### 本地环境

- antd-mobile 版本：0.9.8
- 操作系统及其版本：10.12.1
- 浏览器及其版本：56.0.2906.0 dev (64-bit)

#### 你做了什么？

我在 Card 组件的 Card.Footer 中的 content 中传入了一个 button 按钮， 例如这样
```
<Card.Footer
content={<Button type="ghost" onClick={this.upload.bind(this)}>导出</Button>} 
extra={<Button type="primary" onClick={this.onSublime.bind(this)}>搜索</Button>}/>
```

官网上面的文档上说是允许传入一个React.Element的额。。。
#### 你期待的结果是：

不报错

#### 实际上的结果：

```
Warning: Unknown prop `focusOnUpDown` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in input (created by InputNumber)
    in div (created by InputNumber)
    in div (created by InputNumber)
    in InputNumber (created by Stepper)
```

**Comment by silentcloud** [comment]
这个不是 Card 的报错，鹅湖 InputNumber 的 @F-happy 

>  Unknown prop `focusOnUpDown` on <input> tag
> in input (created by InputNumber)

**Comment by F-happy** [comment]
可是 我把 content 里面的内容删掉了之后就不报错了额  @silentcloud

**Comment by F-happy** [comment]
好吧，我发现是Stepper组件报错了，可是我看到更新日志上写着已经修复了这个问题，为什么我在最新版本中还是会遇到呢？ @silentcloud

**Comment by silentcloud** [comment]
我这边本地是 ok 的，你删除 node_modules  重新 install 试试？

**Comment by F-happy** [comment]
我用 
```
npm remove antd-mobile

npm cache clean

npm install antd-mobile
```
之后还是一样，难道一定要 remove node_modules嘛？这样的话我还要重新编译其他的包。。。 @silentcloud

**Comment by silentcloud** [comment]
要不你把你的代码贴到 codepen，直接 fork 改这个： https://codepen.io/silentcloud/pen/RoRydz

**Comment by F-happy** [comment]
我最后删除掉node_modules 重新 install之后就好了。。。 @silentcloud
