### ISSUE TITLE
打包后， css变量失效

### ISSUE THREAD

**Issue by H-Sven** [ant-design/ant-design-mobile#5224]
### Version of antd-mobile

5.10.0

### What happened?

<img width="397" alt="image" src="https://user-images.githubusercontent.com/26042365/169752612-43d3a9f9-90e3-4772-8e87-ed91122e392e.png">

<img width="521" alt="image" src="https://user-images.githubusercontent.com/26042365/169752676-a8bb351c-c4f2-4368-b802-9ea250fb2ffd.png">

项目中v2和v5共存， v5使用了别名。 本地环境正常，打包到线上失效

**Comment by awmleer** [comment]
根据你目前提供的信息判断不出来问题可能出在哪里，如果可以的话，请打包上传一下完整的项目，这样大家才可以帮助到你
