### ISSUE TITLE
 Form.Item 的 onClick 事件中，无法获取到内部 children 的 ref

### ISSUE THREAD

**Issue by xuewenjie123** [ant-design/ant-design-mobile#5225]
### Version of antd-mobile

5.7.0

### Operating system and its version

Others

### Browser and its version

google

### What happened?

 Form.Item 的 onClick 事件中，无法获取到内部 children 的 ref

**Comment by awmleer** [comment]
请在 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或者 [stackblitz](https://stackblitz.com/edit/antd-mobile) 上写一个 demo

**Comment by xuewenjie123** [comment]
之前使用~5.7.0  版本 Form.Item 的 onClick 事件 回调参数中 无法获取到内部 children 的 ref ；
5.12.5版本没有该问题
