### ISSUE TITLE
Can't resolve '@babel/runtime/helpers/esm/regeneratorRuntime'

### ISSUE THREAD

**Issue by lunhui1994** [ant-design/ant-design-mobile#5227]
### Version of antd-mobile

5.12.6

### What happened?
通过别名的方式安装
"antd-mobile-v5": "npm:antd-mobile@^5.2.2",

固定版本号为5.2.2就不会出现这个问题了，但是是因为今天（5.24）才出现该问题，可能更新的版本也是正常的。

能确定的出问题的版本是5.12.6（lock文件中的版本）。

具体的报错信息是：Module not found: Can't resolve '@babel/runtime/helpers/esm/regeneratorRuntime' in '/xxx/node_modules/rc-field-form/es/utils'

无法直接安装 @babel/runtime/helpers/esm/regeneratorRuntime 会失败。

**Comment by xiaohaoo** [comment]
我也遇到了相似的问题，在升级5.12.6以后出现Module not found: Can't resolve '@babel/runtime/helpers/esm/regeneratorRuntime'，经过我的多次试验，首先在package.json去除antd-mobile依赖安装好其他依赖，然后再安装antd-mobile就不会报错！

**Comment by lunhui1994** [comment]
> 我也遇到了相似的问题，在升级5.12.6以后出现Module not found: Can't resolve '@babel/runtime/helpers/esm/regeneratorRuntime'，经过我的多次试验，首先在package.json去除antd-mobile依赖安装好其他依赖，然后再安装antd-mobile就不会报错！

我把版本号固定了，分开安装的话编译打包就很尴尬了。

**Comment by LJJCherry** [comment]
遇到了同样的问题

**Comment by javaxiu** [comment]
我们无法修改 antd-mobile 的 package 加 resolution 锁版本，那是不是只能锁 antd-mobile 的版本了

**Comment by LJJCherry** [comment]
> 

没太理解呢

**Comment by LJJCherry** [comment]
> 我也遇到了相似的问题，在升级5.12.6以后出现Module not found: Can't resolve '@babel/runtime/helpers/esm/regeneratorRuntime'，经过我的多次试验，首先在package.json去除antd-mobile依赖安装好其他依赖，然后再安装antd-mobile就不会报错！

我是新加的包，按理说也是你这种操作流程，同样报这个错

**Comment by lunhui1994** [comment]
> > 我也遇到了相似的问题，在升级5.12.6以后出现Module not found: Can't resolve '@babel/runtime/helpers/esm/regeneratorRuntime'，经过我的多次试验，首先在package.json去除antd-mobile依赖安装好其他依赖，然后再安装antd-mobile就不会报错！
> 
> 我是新加的包，按理说也是你这种操作流程，同样报这个错

先试试5.12.6之前的版本吧，固定版本号先用。

**Comment by awmleer** [comment]
看起来是 rc-field-form 的问题？

**Comment by awmleer** [comment]
先手动在 package.json 里加一下 resolutions 吧：

```json
{
  "resolutions": {
    "rc-field-form": "1.26.4"
  },
}
```

**Comment by awmleer** [comment]
来自 rc-field-form 中的这条评论：

https://github.com/react-component/field-form/issues/445#issuecomment-1135618356

**Comment by awmleer** [comment]
还可以试一下在自己的项目中手动安装 @babel/runtime `^7.18.0` 版本，应该可以临时解决这个问题，等后面 rc-field-form 修复之后再去掉

**Comment by awmleer** [comment]
噢 rc-field-form 已经发布了，那直接重装一下依赖到最新版就可以了（如果有 lock 文件的话，可以先删掉 antd-mobile 再重装，避免 upgrade 不到深层的依赖）

**Comment by awmleer** [comment]
issue 我先关闭了，各位朋友如果发现重装依赖之后还不行的话，可以再继续在这里反馈

**Comment by LJJCherry** [comment]
> 来自 rc-field-form 中的这条评论：
> 
> [react-component/field-form#445 (comment)](https://github.com/react-component/field-form/issues/445#issuecomment-1135618356)

我也看到了，正想来贴，https://github.com/react-component/field-form/issues/445
