### ISSUE TITLE
ESLint 报错 Unable to resolve path to module 'antd-mobile' import/no-unresolved

### ISSUE THREAD

**Issue by xwartz** [ant-design/ant-design-mobile#523]
#### 本地环境

Mac

antd-mobile:  0.9.4

ESLint: 2.10.1

babel-eslint: 6.0.4

在 react-native 中使用

#### 你做了什么？

引入模块 

```js
import { Popup } from 'antd-mobile'
```

ESLint parse 使用的是 babel-eslint

#### 你期待的结果是：

ESLint 不报错

#### 实际上的结果：

Unable to resolve path to module 'antd-mobile' import/no-unresolved

**Comment by warmhug** [comment]
#414 #56 #510

**Comment by warmhug** [comment]
仔细对照看文档。

**Comment by xwartz** [comment]
感谢回复，在提这个 issue 之前我已经搜索过相关问题，没有 eslint 相关的。
麻烦再看一下我的问题，谢谢。

**Comment by xwartz** [comment]
你意思是使用
```
"import/no-unresolved": 0
```
这个规则吗？

如果是这样的话，并不认为是好的解决方案

**Comment by warmhug** [comment]
欢迎你提供更好的方案建议~

**Comment by afc163** [comment]
把 main 设为 lib/index.js 或 lib/index.web.js

**Comment by xwartz** [comment]
@afc163   额，没懂你说的 `main` 指的是什么

**Comment by afc163** [comment]
我是和 @warmhug 说的。

**Comment by xwartz** [comment]
有什么进展吗

**Comment by xwartz** [comment]
目前暂时在引入 antd 的地方使用 eslint-disable-line

**Comment by yoniji** [comment]
@xwartz 
.eslintrc 中可以这样设置
```
  "rules": {
    "import/extensions": [2, "never", { "web.js": "never", "json": "never" }],
    "import/no-extraneous-dependencies": [2, { "devDependencies": true }],
    "import/no-unresolved": [2, { "ignore": ["antd-mobile"] }]
  }
```
"import/no-extraneous-dependencies" 和 "import/extensions" 的设置和本问题无关，只是现在的我们的项目里 "import/no-unresolved" 和  "import/no-extraneous-dependencies" 都设置为 0 不妥当

**Comment by xwartz** [comment]
@yoniji  谢谢，你的方式比我的好多了
