### ISSUE TITLE
在Dropdown.Item 这个组件中，打开的面板如果长度过长，没有滚动条。

### ISSUE THREAD

**Issue by limit81995** [ant-design/ant-design-mobile#5242]
### Version of antd-mobile

5.10.2

### What is this feature about?

在Dropdown.Item 这个组件中。
1.打开的面板如果长度过长，没有滚动条。
2.并且Dropdown.Item打开的面板应该始终跟着Dropdown组件的位置移动，而不是固定在屏幕的某个位置。
3.打开面板后，应该有一个参数，是否可以在外部区域滑动，如果true的话，外部可以操作滑动，如果false的话 应该是外部不可操作。

**Comment by yaogengzhu** [comment]
https://codesandbox.io/s/falling-paper-4gjn85?file=/src/App.tsx

你说的加这个参数，我Dropdown组件这个组件应该不会去实现，这个滑动应该由开发者本身去处理好了！🤣

**Comment by awmleer** [comment]
@limit81995 可以看下上面的 demo，是业务项目中自己对容器处理 overflow 样式的，issue 我关闭了
