### ISSUE TITLE
v5 版本为啥没了 pagination 分页组件

### ISSUE THREAD

**Issue by iiDestiny** [ant-design/ant-design-mobile#5251]
### Version of antd-mobile

5.12.6

### What is this feature about?

v5 版本为啥没了 pagination 分页组件，是推荐使用无限加载所以移除了它吗？

**Comment by awmleer** [comment]
移动端几乎不会出现桌面端那样的分页器，所以从设计层面直接去掉了这个组件，未来大概率也不会做
