### ISSUE TITLE
ImageUploader 只调起摄像机，部分安卓机型还是会带上文件选项

### ISSUE THREAD

**Issue by foreverjcx** [ant-design/ant-design-mobile#5254]
### Version of antd-mobile

5.10.3

### Operating system and its version

Android

### What happened?

ImageUploader 设置capture属性，期望只调用摄像机，部分安卓机型还是带上了文件选项

**Comment by foreverjcx** [comment]
以下代码展示：
![image](https://user-images.githubusercontent.com/35125128/170939004-b774168c-952a-405f-ba87-2da7a8a52415.png)

**Comment by MuxinFeng** [comment]
对于`capture`的支持说明如下：
1. https://blog.csdn.net/qq_38382380/article/details/104759170
2. https://caniuse.com/?search=HTML%20element%3A%20input%3A%20capture

**Comment by MuxinFeng** [comment]
属实是旧时代的残党了，我这边提个 PR 补充下文档

**Comment by gengfanbin** [comment]
`<ImageUploader
          showUpload={!this.state.value}
          value={this.state.value ? [{ url: this.state.value }] : []}
          upload={this.handleChange.bind(this)}
          onDelete={this.onDelete.bind(this)}
          maxCount={1}
          beforeUpload={file => {
            if (file.size > 5 * 1024 * 1024) {
              Toast.show('请选择小于 5M 的图片')
              return null
            }
            return file
          }}
        />}`

**Comment by gengfanbin** [comment]
为什么我上传一张图片会导致上传按钮变成上传图片的样子？
![Dingtalk_20230316095547](https://user-images.githubusercontent.com/37883676/225489743-f26212d4-8f5c-41d4-9840-ff0ae74742e2.jpg)

**Comment by gengfanbin** [comment]
这是我的代码
![image](https://user-images.githubusercontent.com/37883676/225489995-ed866e80-a362-4ddd-b608-8a055f9907cd.png)
