### ISSUE TITLE
input组件，autoFocus自动获取焦点不起作用

### ISSUE THREAD

**Issue by Mr-Nobody-li** [ant-design/ant-design-mobile#5256]
### Version of antd-mobile

5.12.6

### Operating system and its version

iOS15.5 苹果11

### Browser and its version

任何浏览器

### What happened?

使用`autoFocus`原生属性会引起`ts`类型检查报错

使用`ref.focus()`在苹果11（不分浏览器）上不起作用
```
<Input
    // autoFocus
    value={renameValue}
    onChange={(val) => {
        setRenameValue(val);
    }}
    ref={(ref) => setTimeout(() => ref.focus())}
    />
```
文档上说支持`autoFocus`原生属性，为什么ts会报错

### Relevant log output

```shell
不能将类型“{ autoFocus: true; value: string; onChange: (val: string) => void; ref: (ref: InputRef) => Timeout; }”分配给类型“IntrinsicAttributes & Pick<NativeInputProps, "pattern" | "type" | "onCompositionEnd" | "onCompositionStart" | "onFocus" | "onBlur" | ... 7 more ... | "minLength"> & { ...; } & NativeProps<...> & RefAttributes<...>”。
  类型“IntrinsicAttributes & Pick<NativeInputProps, "pattern" | "type" | "onCompositionEnd" | "onCompositionStart" | "onFocus" | "onBlur" | ... 7 more ... | "minLength"> & { ...; } & NativeProps<...> & RefAttributes<...>”上不存在属性“autoFocus”。ts(2322)
```

**Comment by awmleer** [comment]
你使用的 typescript 版本是？

**Comment by miracles1919** [comment]
> 使用ref.focus()在苹果11（不分浏览器）上不起作用

IOS 上默认不支持 autoFocus 的，focus 需要用户主动触发的事件，
例如 
```
<input
  ref={ref}
/>
<button onClick={() => ref.current.focus()}>button</button>
```

**Comment by awmleer** [comment]
看 [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) 上描述的是支持的……？

**Comment by miracles1919** [comment]
属性是支持的，但是自动获取焦点这个行为，会被 IOS 阻止

**Comment by awmleer** [comment]
啊这，那在 `useEffect` 里手动调用 `ref` 的 `focus()` 呢……？

**Comment by xiaoyao96** [comment]
IOS系统下的浏览器对聚焦有限制，需要用户行为如：click、touchstart、touchend事件监听回调内，`同步`执行聚焦才有效。
任何非用户行为下执行聚焦、或用户行为中异步执行聚焦都会无效。

如果是IOS APP内，可以对UIWebview配置keyboardDisplayRequiresUserAction为false来关闭这个限制：
https://developer.apple.com/documentation/uikit/uiwebview/1617967-keyboarddisplayrequiresuseractio

但如果只靠H5，是没办法规避这个限制的。

**Comment by awmleer** [comment]
get 那看起来只能是文档上注明一下了
