### ISSUE TITLE
ios下使用Input type=‘number’ ，输入小数，报输入有效值

### ISSUE THREAD

**Issue by Fmk1998** [ant-design/ant-design-mobile#5263]
### Description

![image](https://user-images.githubusercontent.com/38979245/171573169-d7eb1fa3-9a49-48e9-97da-ee0c5d00fe09.png)
ios下使用Input type=‘number’ ，输入小数，报输入有效值

**Comment by awmleer** [comment]
请提供使用的 antd-mobile 的具体版本，以及复现 demo

**Comment by one-smiling** [comment]
设置step="0.00.1"就行了
