### ISSUE TITLE
依赖的库 @react-spring/web 里有使用 Object.values，而它是 ES8（2017），所以造成低版本的手机就报错。

### ISSUE THREAD

**Issue by zm8** [ant-design/ant-design-mobile#5268]
### Version of antd-mobile

5.13.1

### Operating system and its version

Android

### What happened?

这个有什么好的解决方案吗？ 目前是手动添加 ```Object.values``` 的 shim。

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/32337542/172056448-cdd0c057-7c5d-4176-b528-aa928faf8a60.png">

**Comment by miracles1919** [comment]
看下文档，[兼容性](https://mobile.ant.design/zh/guide/quick-start#%E5%85%BC%E5%AE%B9%E6%80%A7)

**Comment by gaoxianglyx** [comment]
请问解决了吗？
