### ISSUE TITLE
antd-mobile-icons 里的图标在PC中hover，会展示title

### ISSUE THREAD

**Issue by cutpictureboy** [ant-design/ant-design-mobile#5270]
### Version of antd-mobile

5.9.1

### Operating system and its version

Others

### Browser and its version

Chrome 101.0.4951.64

### What happened?

ICON 在PC或者其他有鼠标的场景，会展示title元素，导致鼠标移入icon就会出现字符串，而且字符串不存在意义，例如：8C01EF67-304C-465C-BFE3-6D9C53F88E3D@2x，期望删除
<img width="283" alt="image" src="https://user-images.githubusercontent.com/21117504/172089572-ae8d8838-c336-4dc6-8ade-936579618529.png">

**Comment by awmleer** [comment]
2262837b fixed
