### ISSUE TITLE
[Form] `useWatch` 与 `Subscribe` 无法正确响应 `form.setFieldsValue`

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#5275]
### Version of antd-mobile

latest

### Sandbox to reproduce

https://codesandbox.io/s/serene-mclaren-f9uxqh

### What happened?

```tsx
<Button onClick={()=>form.setFieldsValue({account:Math.random()})}>set</Button>
```

Form 组件的 demo `demos/demo-subscribe` `demos/demo-use-watch` 分别加上上面的代码。

## `Form.Subscribe`

点击Button更新值， `Form.Subscribe` 里的内容不会更新

## `useWatch`

`useWatch` 在组件注销后再重新注册，值就消失了
```tsx
<>
  {loginMethod === 'mobile' && (
    <Form.Item name='account' label='手机号'>
      <Input placeholder='请输入手机号' />
    </Form.Item>
  )}
  {loginMethod === 'email' && (
    <Form.Item name='account' label='邮箱'>
      <Input placeholder='请输入邮箱' />
    </Form.Item>
  )}
</>
```

感觉这 issue 得提到 `rc-field-form`

**Comment by awmleer** [comment]
@crazyair 有空来看下这个问题不～

**Comment by crazyair** [comment]
ok

**Comment by linliwei999** [comment]
Q：useWatch 在组件注销后再重新注册，值就消失了
额外加一个noStyle的Form.Item？@IronKinoko 
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/61395805/172293479-9717d9ba-b131-4ae0-a465-822d68f17fcc.png">

**Comment by crazyair** [comment]
field-form 目前在 dependencies 下，执行 setFieldsValue 不会 rerender，应该是跟 https://ant-design.antgroup.com/components/form-cn/#setFieldsValue-%E4%B8%8D%E4%BC%9A%E8%A7%A6%E5%8F%91-onFieldsChange-%E5%92%8C-onValuesChange%EF%BC%9F 一致。

**Comment by IronKinoko** [comment]
https://github.com/react-component/field-form/blob/1f773edf434ba9d26d672361e865cf25db3e8446/src/useForm.ts#L738-L753

```tsx
// Let all child Field get update.
private setFieldsValue = (store: Store) => {
  this.warningUnhooked();

  const prevStore = this.store;

  if (store) {
    const nextStore = setValues(this.store, store);
    this.updateStore(nextStore);
  }

  this.notifyObservers(prevStore, null, {
    type: 'valueUpdate',
    source: 'external',
  });

  // 看源码估计是不好计算 namePath 导致的没有写 triggerDependenciesUpdate
  // this.triggerDependenciesUpdate(prevStore, namePath)

  this.notifyWatch();
};
```

**Comment by IronKinoko** [comment]
useWatch 在组件注销后再重新注册，值就消失了是以下bug导致的

https://github.com/react-component/field-form/blob/master/src/useWatch.ts#L94-L102

```tsx
function useWatch(dependencies: NamePath = [], form?: FormInstance) {
  const [value, setValue] = useState<any>();

  const valueStr = useMemo(() => stringify(value), [value]);
  const valueStrRef = useRef(valueStr);
  valueStrRef.current = valueStr;

  // ... 省略不重要的内容

  useEffect(
    () => {
      // Skip if not exist form instance
      if (!isValidForm) {
        return;
      }

      const { getFieldsValue, getInternalHooks } = formInstance;
      const { registerWatch } = getInternalHooks(HOOK_MARK);

      const cancelRegister = registerWatch(store => {
        const newValue = getValue(store, namePathRef.current);
        const nextValueStr = stringify(newValue);

        // 组件的注销/重注册都会触发 registerWatch 回调，但因为回调太快，react在一个更新流程里处理掉了。
        // 这就导致 `valueStrRef.current` 这个值不是最新的。再重注册比较的时候就出现bug了 
        // 1. unmount 
        //  - nextValueStr //=> undefined; 
        //  - valueStrRef.current //=> value ; 
        //  - valueStrRef.current !== nextValueStr //=> setValue(undefined);

        // 2. mount
        //  - nextValueStr //=> value
        //  - valueStrRef.current //=> value  // 这里速度太快导致值没更新，还是前一个值
        //  - valueStrRef.current === nextValueStr //=> void

        // 3. result //=> 最新的值因上一轮的错误比较，导致没有执行 setValue

        // Compare stringify in case it's nest object
        if (valueStrRef.current !== nextValueStr) {
          setValue(newValue);
        }
      });

      // TODO: We can improve this perf in future
      const initialValue = getValue(getFieldsValue(), namePathRef.current);
      setValue(initialValue);

      return cancelRegister;
    },

    // We do not need re-register since namePath content is the same
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [],
  );

  return value;
}
```

**Comment by crazyair** [comment]
```
<>
  {loginMethod === 'mobile' && (
    <Form.Item name='account' label='手机号'>
      <Input placeholder='请输入手机号' />
    </Form.Item>
  )}
  {loginMethod === 'email' && (
    <Form.Item name='account' label='邮箱'>
      <Input placeholder='请输入邮箱' />
    </Form.Item>
  )}
</>
```
不能相同 name 存在 2 处，一个字段不能同时卸载时候再加载，也不会在 Input 带出来之前的值，跟 useWatch 无关。

**Comment by IronKinoko** [comment]
> 相同 name 不能存在多处
name 不是同时存在的，


https://github.com/react-component/field-form/blob/master/src/useForm.ts#L632
从源码看，Form 默认 preserve === true ，组件注销再注册的时候，是不会清空之前的值。
```tsx
const cancelRegister = registerWatch(store => {
        const newValue = getValue(store, namePathRef.current);
        const nextValueStr = stringify(newValue);
```
此处的 store 并不等于 FormStore 里的 this.store，[他是 this.getFieldsValue() 生成出来的](https://github.com/react-component/field-form/blob/master/src/useForm.ts#L198-L207)，只包含注册的字段。
注销后就是返回undifned。
当重新注册的时候，store又可以重新拿到值。
所以 registerWatch 触发的两次回调中，他们的值分别是 undefined 和 value. 
```tsx
// Compare stringify in case it's nest object
if (valueStrRef.current !== nextValueStr) {
  setValue(newValue);
}
```
在同一次更新流程中 `valueStrRef.current` 值并不会改变，再两次比较中产生了bug

```tsx
// Compare stringify in case it's nest object
if (valueStrRef.current !== nextValueStr) {
  valueStrRef.current = nextValueStr
  setValue(newValue);
}
```
通过添加这一行代码，可以解决比较时候的bug

**Comment by crazyair** [comment]
这里被认为是2个组件了所以会卸载，你可以修改如下，让他认为是一个组件
```
{loginMethod === 'mobile' ? (
    <Form.Item name='account' label='手机号'>
      <Input placeholder='请输入手机号' />
    </Form.Item>
  ): null }
{loginMethod === 'email' ? (
    <Form.Item name='account' label='邮箱'>
      <Input placeholder='请输入邮箱' />
    </Form.Item>
  ): null}
```
或者

```
<>
  {loginMethod === 'mobile' && (
    <Form.Item name='account' label='手机号' key='account'>
      <Input placeholder='请输入手机号' />
    </Form.Item>
  )}
  {loginMethod === 'email' && (
    <Form.Item name='account' label='邮箱' key='account'>
      <Input placeholder='请输入邮箱' />
    </Form.Item>
  )}
</>
```

**Comment by yangdepp** [comment]
`useWatch`时，使用`hidden`显示隐藏值就不会消失了
```jsx
    <Form.Item
      name="account"
      label="手机号"
      hidden={loginMethod !== "mobile"}
    >
      <Input placeholder="请输入手机号" />
    </Form.Item>

    <Form.Item name="account" label="邮箱" hidden={loginMethod !== "email"}>
      <Input placeholder="请输入邮箱" />
    </Form.Item>
```

还可以
```jsx
      <Form.Item
        name="account"
        label={`${loginMethod === "mobile" ? "手机号" : "邮箱"}`}
      >
        <Input placeholder={`请输入${loginMethod === "mobile" ? "手机号" : "邮箱"}`} />
      </Form.Item>
```

**Comment by yangdepp** [comment]
`Form.Subscribe`时应该使用`shouldUpdate`
```jsx
          <Form.Item
            noStyle
            shouldUpdate={(prevValues, curValues) =>
              prevValues.loginMethod !== curValues.loginMethod ||
              prevValues.account !== curValues.account
            }
          >
            {({ getFieldValue }) => (
              <div
                style={{
                  marginBottom: "24px",
                  fontSize: "15px",
                  color: "var(--adm-color-weak)"
                }}
              >
                你将使用{" "}
                {getFieldValue("loginMethod") === "mobile" ? "手机号" : "邮箱"}{" "}
                {getFieldValue("account")} 登录
              </div>
            )}
          </Form.Item>
```

```jsx
      <Form.Item
        noStyle
        shouldUpdate={(prevValues, curValues) =>
          prevValues.loginMethod !== curValues.loginMethod
        }
      >
        {({ getFieldValue }) => {
          return getFieldValue("loginMethod") === "emial" ? (
            <Form.Item name="account" label="邮箱" key="account">
              <Input placeholder="请输入邮箱" />
            </Form.Item>
          ) : (
            <Form.Item name="account" label="手机号" key="account">
              <Input placeholder="请输入手机号" />
            </Form.Item>
          );
        }}
      </Form.Item>
```

**Comment by crazyair** [comment]
> `Form.Subscribe`那个例子其实应该使用`shouldUpdate`
> 
> ```js
>           <Form.Item
>             noStyle
>             shouldUpdate={(prevValues, curValues) =>
>               prevValues.loginMethod !== curValues.loginMethod ||
>               prevValues.account !== curValues.account
>             }
>           >
>             {({ getFieldValue }) => (
>               <div
>                 style={{
>                   marginBottom: "24px",
>                   fontSize: "15px",
>                   color: "var(--adm-color-weak)"
>                 }}
>               >
>                 你将使用{" "}
>                 {getFieldValue("loginMethod") === "mobile" ? "手机号" : "邮箱"}{" "}
>                 {getFieldValue("account")} 登录
>               </div>
>             )}
>           </Form.Item>
> ```
> 
> ```js
>       <Form.Item
>         noStyle
>         shouldUpdate={(prevValues, curValues) =>
>           prevValues.loginMethod !== curValues.loginMethod
>         }
>       >
>         {({ getFieldValue }) => {
>           return getFieldValue("loginMethod") === "emial" ? (
>             <Form.Item name="account" label="邮箱" key="account">
>               <Input placeholder="请输入邮箱" />
>             </Form.Item>
>           ) : (
>             <Form.Item name="account" label="手机号" key="account">
>               <Input placeholder="请输入手机号" />
>             </Form.Item>
>           );
>         }}
>       </Form.Item>
> ```
`shouldUpdate` 使用比较麻烦，`Form.Subscribe` 底层没有什么逻辑，你可以自己封装一个，或者推荐用`useWatch`

**Comment by crazyair** [comment]
> > 相同 name 不能存在多处
> 
> name 不是同时存在的，可以理解成只存在一个account，但是发生了 unmount mount
> 
> https://github.com/react-component/field-form/blob/master/src/useForm.ts#L632 从源码看，Form 默认 preserve === true ，组件注销再注册的时候，是不会清空之前的值。
> 
> ```tsx
> const cancelRegister = registerWatch(store => {
>         const newValue = getValue(store, namePathRef.current);
>         const nextValueStr = stringify(newValue);
> ```
> 
> 此处的 store 并不等于 FormStore 里的 this.store，[他是 this.getFieldsValue() 生成出来的](https://github.com/react-component/field-form/blob/master/src/useForm.ts#L198-L207)，只包含注册的字段。 注销后就是返回undifned。 当重新注册的时候，store又可以重新拿到值。 所以 registerWatch 触发的两次回调中，他们的值分别是 undefined 和 value.
> 
> ```tsx
> // Compare stringify in case it's nest object
> if (valueStrRef.current !== nextValueStr) {
>   setValue(newValue);
> }
> ```
> 
> 在同一次更新流程中 `valueStrRef.current` 值并不会改变，再两次比较中产生了bug
> 
> ```tsx
> // Compare stringify in case it's nest object
> if (valueStrRef.current !== nextValueStr) {
>   valueStrRef.current = nextValueStr
>   setValue(newValue);
> }
> ```
> 
> 通过添加这一行代码，可以解决比较时候的bug

https://github.com/react-component/field-form/pull/451

**Comment by IronKinoko** [comment]
## 解决方案
### `Form.Subscribe`
```tsx
const [form] = useForm()
const [,update] = useState()

const setValue = (values)=> {
   form.setFieldsValue(values)
   update(Math.random())
}

```
执行 `form.setFieldsValue` 的时候，一起执行 `update(Math.random())`，这样 `Form` 会全部刷新一遍，`Subscribe` 也跟着一起刷新

### `useWatch`

https://github.com/react-component/field-form/pull/451 解决了，antd-mobile 已经更新了

**Comment by crazyair** [comment]
> 诶那这么说的话，是不是 `Form.Subscribe` 如果底层改成基于 `useWatch` 来实现，就能规避这个问题了？
> 
> @IronKinoko @crazyair

是，useWatch 本身也可以单独组建使用，达到单独 render 效果。

**Comment by crazyair** [comment]
目前 useWatch 没开发支持多 namePath，所以 dependencies 不能传多个 name

**Comment by awmleer** [comment]
现在的话 `useWatch` 和 `Subscribe` 都会行为正常了

获取后面可以加个 `Form.Watch` 组件，直接对应 `useWatch`，只能订阅单个字段，就不会存在额外渲染一次的问题了，然后 `Form.Subscribe` 弃用掉，等下个大版本移除

**Comment by crazyair** [comment]
> 是的，所以我用了一种稍微麻烦一点的做法来实现了 [8a968d4](https://github.com/ant-design/ant-design-mobile/commit/8a968d4f7c8c1c0149e2ffa9441fa1ccb85336e6)
> 
> 目前的问题是在正常情况下会在订阅的值变化时额外多渲染一次，性能上稍微差点，但是应该是可以接受的

dependencies={props.to}>  => shouldUpdate = false

**Comment by crazyair** [comment]
```tsx
<>
    <Form.Item noStyle>{children(form?.getFieldsValue(to), form)}</Form.Item>
    {to.map(name => (
        <Watcher key={name.toString()} name={name} onChange={() => setUpdate({})} />
    ))}
</>
```
如果不用 dependencies，其实可以分开写

**Comment by IronKinoko** [comment]
这样少了 form 参数， useWatch 没法用。不然还得在内部 const [form] = useForm()

**Comment by awmleer** [comment]
@crazyair 这样确实可以了～ 👍

**Comment by awmleer** [comment]
cb7a3011

**Comment by Jerryqun** [comment]
> 是的，所以我用了一种稍微麻烦一点的做法来实现了 [8a968d4](https://github.com/ant-design/ant-design-mobile/commit/8a968d4f7c8c1c0149e2ffa9441fa1ccb85336e6)
> 
> 目前的问题是在正常情况下会在订阅的值变化时额外多渲染一次，性能上稍微差点，但是应该是可以接受的

多渲染一次的问题能解决吗？ 这会导致如果组件里面有请求会发两次

**Comment by crazyair** [comment]
> 

watch 确实会执行2次render，这个是预期的
