### ISSUE TITLE
[List] extra css 属性 flex:none 导致无法正确换行

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#5276]
### Version of antd-mobile

latest

### Browser and its version

ios 15.4

### Sandbox to reproduce

https://codesandbox.io/s/cocky-boyd-yg3cyd?file=/src/App.tsx

### What happened?

https://github.com/ant-design/ant-design-mobile/blob/f5d37a19ab77be0e42335e01817fd0fc570bdab0/src/components/list/list.less#L70-L75

## 样式问题
- 文字过长造成 `main` 区域中文被挤成一列文字
- `flex: none;` 造成无法正常换行
- extra 没有 `padding-top` `padding-bottom`，多行文本会触到 `List.Item` 上下边

**Comment by yaogengzhu** [comment]
我尝试改了下！
