### ISSUE TITLE
希望ImagePicker加上crop功能，并支持crop预览，可以设置开启或关闭crop功能

### ISSUE THREAD

**Issue by guangming21** [ant-design/ant-design-mobile#528]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

**Comment by warmhug** [comment]
mobile 感觉没必要有 crop 功能，你可以给个其他有这个的例子看看

**Comment by guangming21** [comment]
上传头像会用到，裁剪图片

**Comment by benjycui** [comment]
像 `antd.Upload` 那样，提供个 `beforeUpload` 之类的钩子，让用户自行增加 crop 行为？

**Comment by warmhug** [comment]
@benjycui  这个组件不包含上传功能，只是个 Image 的 picker，其 onChange 事件跟 antd upload 的 beforeUpload 作用相似。

所以，crop功能 还是自己实现。
