### ISSUE TITLE
Drawer 内容高度问题

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#529]
#### 本地环境

- antd-mobile 版本：0.9.7
- 操作系统及其版本：mac
- 浏览器及其版本：chrome

#### 你做了什么？

引用了Drawer组件，但其高度没有减去NavBar的高度以及Drawer组件之上的所有组件的高度

#### 你期待的结果是：

官网Demo也没有减去NavBar的高度，出现了滚动条，希望正确计算高度，不要出现滚动条

**Comment by warmhug** [comment]
在内容里设置 margin 或 padding，drawer 不负责减去其他组件高度

**Comment by liubin1023** [comment]
@warmhug  设置了之后就不会产生滚动条了吗

**Comment by warmhug** [comment]
Drawer 高度需要自己想办法计算
