### ISSUE TITLE
Badge 没有支持 className 和 style 属性

### ISSUE THREAD

**Issue by brickspert** [ant-design/ant-design-mobile#5290]
### Version of antd-mobile

5.12.2

**Comment by yaogengzhu** [comment]
支持的！

**Comment by GOWxx** [comment]
写了个 demo，可以的

https://codesandbox.io/s/confident-glitter-jm9nx4?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/12870715/172654792-70c24d47-d565-4bca-ad19-280307c881cc.png)

**Comment by brickspert** [comment]
正常应该是加到 `adm-badge-wrap` 上面的吧。 现在加到内层了~

**Comment by awmleer** [comment]
不能加到 wrap 上的……wrap 是纯布局用的，没有 `children` 的时候是不会有 wrap 的

感觉还是单独给 wrapper 加两个属性比较好 `wrapperClassName` `wrapperStyle`
