### ISSUE TITLE
希望可以新增 classPrefix 修改的功能 

### ISSUE THREAD

**Issue by ht1131589588** [ant-design/ant-design-mobile#5291]
### What is this feature about?

请问后续能否支持样式名完全自定义的功能？比如像antd-design一样可以全局修改className前缀，或者组件可以单独传入 classPrefix

**Comment by ht1131589588** [comment]
主要原因有：
1. 因为功能基本上都可以用，但样式风格很多要重写，用覆盖的方式，css文件大小会多一些
2. 如果不引入css文件，完全按照antd-mobile组件的样式来重写，开发成本会比较大
3. 现在用于自己的业务组件库，有多个业务都需要用到，但每个业务的风格是不同的，想根据业务来定义自己的样式及样式类名，以便于业务工程中不包含antd的样式覆盖，而只有我们自己的业务组件库的类名样式覆盖
4. 也是为了可以更好的扩展，以便于外部使用统一的组件库，但内部可以引入第三方UI组件库、第三方组件、及内部封装的组件等待

**Comment by awmleer** [comment]
听起来你是想只基于 antd-mobile 的逻辑封装一套自己业务组件库？如果想调整视觉效果的话，可以使用 antd-mobile 已经暴露出来 CSS 变量，这是有可靠性保证的，当然，只能做有限度的调整。如果你想完全把 antd-mobile 样式都重写掉，那感觉已经不是 class prefix 的问题了，我们也不会为了这种场景支持修改 class prefix。可以考虑自己 fork 一份 antd-mobile 的项目自行维护。

**Comment by madocto** [comment]
hi，有用户反馈页面交互没有反应，发现用户浏览器有屏蔽广告的功能，组件的 class 以 ad 开头导致被当成广告了，希望可以增加 classPrefix 来自定义，谢谢
