### ISSUE TITLE
当前如何使用typescript?

### ISSUE THREAD

**Issue by ImJoeHs** [ant-design/ant-design-mobile#531]
#### 本地环境
dva+typescript

- antd-mobile 版本： 0.9.8

#### 你做了什么？

tsx中引入antd-mobile

#### 你期待的结果是：

正常使用

#### 实际上的结果：

ERROR in ./src/routes/IndexPage.tsx
Module not found: Error: Cannot resolve module 'antd-mobile' in D:\cs\src\routes
 @ ./src/routes/IndexPage.tsx 5:20-42

使用antd没有任何问题，去掉ts也能正常使用，antd-mobile+ts则出错

**Comment by silentcloud** [comment]
参考一下这里： https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#%E5%AE%89%E8%A3%85

**Comment by ImJoeHs** [comment]
我确认都看过了。去掉typescript是没问题的，应该说明该有的的都有了吧？只有使用typescript才有这种情况。
我做的事情有：
1.dva-cli new
2.install antd-mobile
3.配置typescript环境，js(x) => ts(x)

3开始才报错，尝试将 antd-mobile 换成 antd 也跑得通的。

**Comment by warmhug** [comment]
更新到 antd-mobile 0.9 的最新版，另外麻烦给出更详细的错误日志

**Comment by warmhug** [comment]
关联 #523

**Comment by warmhug** [comment]
dva 生成的项目带有 typescript 配置，https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js#L63 这里有支持。参考这个能正常跑的示例 https://github.com/warmhug/__/blob/master/_react/dva-ts/package.json

**Comment by ImJoeHs** [comment]
抱歉没有及时回复，我的问题出在自己配置了tsconfig，其中module选项应为es2015；
我沿用了之前使用antd时的配置，也难怪antd能跑而mobile不行==。
建议在文档中提醒一下~ 十分感谢回复！
