### ISSUE TITLE
swiper + tabs 实现手势滑动，内容区域比较长时，滑动后无法定位到顶部

### ISSUE THREAD

**Issue by letica** [ant-design/ant-design-mobile#5310]
### Version of antd-mobile

5.12.5

### Description

1. 怎么支持滑动后自动回到顶部？
2. 两个tab下的内容高度不同时，高度会默认为大的那个高度，导致另一个下方有较大的空白，有什么解决办法

**Comment by letica** [comment]
css控制局部滚动解决

**Comment by kingw1020** [comment]
同样有这个问题，怎么解决的啊
