### ISSUE TITLE
SpinLoading 使用报错

### ISSUE THREAD

**Issue by Jerryqun** [ant-design/ant-design-mobile#5312]
### Version of antd-mobile

5.14.3

### Operating system and its version

iOS

### Browser and its version

Chrome 版本 102.0.5005.61（正式版本） (x86_64)

### What happened?

引用SpinLoading报错

### Relevant log output

```shell
TypeError: dispatcher.useSyncExternalStore is not a function
 at useSyncExternalStore
```

**Comment by awmleer** [comment]
需要提供一复现 demo
