### ISSUE TITLE
建议将 CSS 的动画改为 3D 模式，提升顺畅度

### ISSUE THREAD

**Issue by dongkun** [ant-design/ant-design-mobile#5322]
### Version of antd-mobile

5.10.2

### Description

如题，`transform: translate3d(0, 100%, 0);` 要比 `transform: translate(0, 100%);` 顺畅很多，目前的版本在有些端内掉帧太严重了。

**Comment by awmleer** [comment]
有录屏视频么？

`translate3d` 在 iOS Safari 下会存在闪烁问题： https://github.com/ant-design/ant-design-mobile/issues/4540
所以当时通过改成 `translateY` 规避了这个 bug： a4200028

**Comment by awmleer** [comment]
以及，你具体说的是哪个组件的哪个动画？

**Comment by 53tang** [comment]
> 以及，你具体说的是哪个组件的哪个动画？

Popup的transform: translate在iOS Safari 会掉帧，改成transform: translate3d就好了

**Comment by Ruler1020730** [comment]
> > 以及，你具体说的是哪个组件的哪个动画？
> 
> Popup的transform: translate在iOS Safari会掉屏，改成transform: translate3d就好了

我的版本是5.29.0;

同样的, 我在微信浏览器 或者 Safari 展开收起动画严重掉帧，最后我在bodyStyle 加上 transition 做过渡 也可以流畅一些
