### ISSUE TITLE
WeChat H5 environment， SafeArea component not work

### ISSUE THREAD

**Issue by 94Rabbit** [ant-design/ant-design-mobile#5327]
### Version of antd-mobile

5.14.3

### Description

WeChat H5 environment， SafeArea component not work

**Comment by awmleer** [comment]
Please write a reproduce [demo](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx).

**Comment by 94Rabbit** [comment]
> Please write a reproduce [demo](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx).

 <h3>code show as below</h3>

![image](https://user-images.githubusercontent.com/25635994/173795823-672a1f02-32c0-4d0c-ae2b-aad5a24ed5a4.png)

+ Wechat environment result:
![image](https://user-images.githubusercontent.com/25635994/173796443-609ef1c4-23fd-4548-9fd1-1b6fce3ad140.png)

+ common Browser result:
![image](https://user-images.githubusercontent.com/25635994/173796618-4f63e82f-5469-4060-8244-492e00548da1.png)

**Comment by awmleer** [comment]
看起来是微信容器的问题，你可以试试直接用 `env(safe-area-inset-bottom)`，相关的文档在[这里](https://developer.mozilla.org/en-US/docs/Web/CSS/env#usage)

**Comment by qingweiSun** [comment]
解决方案
```
  metas: [{
    name: "viewport",
    content: "width=device-width, initial-scale=1.0, viewport-fit=cover"
  }],
```
