### ISSUE TITLE
RN版本：List下面InputItem样式在6plus上显示错乱

### ISSUE THREAD

**Issue by pannz** [ant-design/ant-design-mobile#533]
#### 本地环境

- antd-mobile 版本：^0.9.6
- 操作系统及其版本： 用的是react-native: 0.37

#### 你做了什么？
```
<List>
    <InputItem {props}>手机号</InputItem>
    <InputItem {props}>密码</InputItem>
</List>
```
#### 你期待的结果是：

这是6/6s/7上的截图， 左边的黑条是模拟器外面的桌面背景:
![image](https://cloud.githubusercontent.com/assets/5423451/20302127/12eea1a4-ab61-11e6-8554-1d2b9705572a.png)

#### 实际上的结果：

在6Plus/6sPlus/7Plus上:
![image](https://cloud.githubusercontent.com/assets/5423451/20302264/8829e9e2-ab61-11e6-935d-7cc91bdaf408.png)

应该问题出现在borderWidth上，在Plus系列，pixelRatio为3，如果设置borderWidth为0.5，这时候会出现这种渲染问题，设置为`StyleSheet.hairlineWidth`就不会又这种问题，因为 hairlineWidth = 1 / pixelRatio 得到

**Comment by silentcloud** [comment]
之前遇到过这种问题，估计有些组件没修复，我 check 一下，感谢反馈

**Comment by silentcloud** [comment]
fixed in 9b30cec0cb0fa920afe7a35e41a69cf4e0a4d24a

**Comment by afc163** [comment]
message 写成 `..., close #xx` `..., fix #xx` 可以直接关掉。
