### ISSUE TITLE
用ts创建的项目中，标签中间写东西会有类型报错

### ISSUE THREAD

**Issue by RenJie-Z** [ant-design/ant-design-mobile#5330]
### Version of antd-mobile

5.0.0-rc.28

### Description

import { Button } from 'antd-mobile'
const Login = () => {
    return (
        div>
            Button color="primary">123</Button>
        /div>
    )
}
export default Login

比如说这样，按钮中间如果加了123或者其他的任何东西就会报错，不加不会报错

(alias) const Button: React.FC<ButtonProps>
import Button
不能将类型“{ children: string; color: "primary"; }”分配给类型“IntrinsicAttributes & { color?: "primary" | "default" | "success" | "warning" | "danger" | undefined; fill?: "solid" | "outline" | "none" | undefined; size?: "small" | ... 3 more ... | undefined; ... 6 more ...; shape?: "default" | ... 2 more ... | undefined; } & NativeProps<...>”。
  类型“IntrinsicAttributes & { color?: "primary" | "default" | "success" | "warning" | "danger" | undefined; fill?: "solid" | "outline" | "none" | undefined; size?: "small" | ... 3 more ... | undefined; ... 6 more ...; shape?: "default" | ... 2 more ... | undefined; } & NativeProps<...>”上不存在属性“children”。ts(2322)

**Comment by IronKinoko** [comment]
5.0.0-rc.28 不支持react18，可以更新到最新版本

如果你没使用react18，可能是你安装的 @types/react 版本有误。请检查下 @types/react 版本

**Comment by RenJie-Z** [comment]
> 5.0.0-rc.28 不支持react18，可以更新到最新版本
> 
> 如果你没有使用react18，可能是你安装的@types/react 版本有错误。请检查下@types/react 版本

谢谢，已降级，已解决
