### ISSUE TITLE
升级antd-mobile至v5引用组件运行项目报错

### ISSUE THREAD

**Issue by chen-jieyi** [ant-design/ant-design-mobile#5334]
### Version of antd-mobile

5.15.0

### Description

问题如图所示
<img width="870" alt="image" src="https://user-images.githubusercontent.com/35585258/173794886-56004adc-c615-49b1-a39d-e6f1609f3239.png">
在把原antd-mobile改成antd-mobile-v2 没有问题能运行
然后update antd-mobile依赖包至 v5.15.0 没有问题，引入组件也不报错
在运行项目时报错了，如上图
删除所有依赖包重装了几次试过npm，cnpm，yarn还是一样运行不起来
去看了umi的antd-mobile文档 步骤也是一样的

package配置如下
{
  "name": "ant-design-pro",
  "version": "4.5.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "cross-env UMI_ENV=prod umi build",
    "deploy": "npm run site && npm run gh-pages",
    "dev": "npm run start:dev",
    "fetch:blocks": "pro fetch-blocks && npm run prettier",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier --check \"src/**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "precommit": "lint-staged",
    "prettier": "prettier -c --write \"src/**/*\"",
    "start": "cross-env UMI_ENV=dev umi dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev umi dev",
    "start:no-ui": "cross-env UMI_UI=none UMI_ENV=dev umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev umi dev",
    "pretest": "node ./tests/beforeTest",
    "test": "umi test",
    "test:all": "node ./tests/run-tests.js",
    "test:component": "umi test ./src/components",
    "tsc": "tsc --noEmit"
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@fullcalendar/core": "^5.7.2",
    "@fullcalendar/daygrid": "^5.7.2",
    "@fullcalendar/react": "^5.7.0",
    "@types/lodash.debounce": "^4.0.6",
    "@types/lodash.isequal": "^4.5.5",
    "@umijs/route-utils": "^1.0.33",
    "ace-builds": "^1.4.13",
    "antd": "^4.21.0",
    "antd-mobile": "^5.15.0",
    "antd-mobile-v2": "^2.3.4",
    "array-move": "^4.0.0",
    "classnames": "^2.2.6",
    "dva": "^2.4.0",
    "echarts": "^4.7.0",
    "echarts-wordcloud": "^1.1.3",
    "immutability-helper": "^3.1.1",
    "js-cookie": "^2.2.1",
    "lodash": "^4.17.11",
    "lodash-decorators": "^6.0.0",
    "lodash.debounce": "^4.0.8",
    "lodash.isequal": "^4.5.0",
    "mockjs": "^1.0.1-beta3",
    "moment": "^2.25.3",
    "ns-chart": "^0.0.5",
    "numeral": "^2.0.6",
    "nzh": "^1.0.3",
    "omit.js": "^2.0.2",
    "prop-types": "^15.5.10",
    "qs": "^6.9.0",
    "rc-form": "^2.4.12",
    "rc-resize-observer": "^1.0.0",
    "react": "^17.0.0",
    "react-ace": "^9.5.0",
    "react-color": "^2.19.3",
    "react-dev-inspector": "^1.1.1",
    "react-dnd": "^14.0.1",
    "react-dnd-html5-backend": "^14.0.0",
    "react-dom": "^17.0.0",
    "react-fittext": "^1.0.0",
    "react-helmet-async": "^1.0.4",
    "react-json-view": "^1.21.3",
    "react-router": "^4.3.1",
    "react-sortable-hoc": "^2.0.0",
    "sortablejs": "^1.13.0",
    "umi": "^3.2.14",
    "umi-request": "^1.0.8",
    "wangeditor-for-react": "1.4.1",
    "wecomjsdk": "^1.0.2",
    "weixin-js-sdk": "^1.6.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^1.0.28",
    "@types/classnames": "^2.2.7",
    "@types/echarts": "^4.9.10",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/qs": "^6.5.3",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.3.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "chalk": "^4.0.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "pro-download": "1.0.1",
    "puppeteer-core": "^5.0.0",
    "stylelint": "^13.0.0",
    "terser-brunch": "^4.0.0",
    "typescript": "^4.0.3"
  },
  "engines": {
    "node": ">=10.0.0"
  },
  "checkFiles": [
    "src/**/*.js*",
    "src/**/*.ts*",
    "src/**/*.less",
    "config/**/*.js*",
    "scripts/**/*.js"
  ],
  "__npminstall_done": false
}

**Comment by GOWxx** [comment]
请查看文档，按照文档中描述的操作试试
[umi 项目安装 antd-mobile v5 后报错如何解决？](https://mobile.ant.design/zh/guide/faq#umi-%E9%A1%B9%E7%9B%AE%E5%AE%89%E8%A3%85-antd-mobile-v5-%E5%90%8E%E6%8A%A5%E9%94%99%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)

**Comment by chen-jieyi** [comment]
> 请查阅文档，并按照文档描述内容操作 [umi 项目安装 antd-mobile v5 后报错如何解决？](https://mobile.ant.design/zh/guide/faq#umi-%E9%A1%B9%E7%9B%AE%E5%AE%89%E8%A3%85-antd-mobile-v5-%E5%90%8E%E6%8A%A5%E9%94%99%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)

好的，按照文档解决了，感谢感谢
