### ISSUE TITLE
Input组件type为password时，提供小眼睛，提供用户查看原文密码 

### ISSUE THREAD

**Issue by qiaodaima** [ant-design/ant-design-mobile#5339]
### Version of antd-mobile

v5.15.0

### What is this feature about?

原生Input密码框无法查看原文密码，
在交互上体验不是很友好，需要有一个操作可以查看密码原文

**Comment by awmleer** [comment]
感觉做在组件里未必合适，Input 的定位是一个非常基础的底层组件，小眼睛算是外层的功能了，不过我们倒是可以先在文档上写个 demo

**Comment by qiaodaima** [comment]
PC版antd的其实就有这个功能了,就是动态的修改下  type属性

**Comment by awmleer** [comment]
antd-mobile 和 antd 的 Input 定位是不一样的
