### ISSUE TITLE
针对rn的文档能不能补充下

### ISSUE THREAD

**Issue by anhuiliujun** [ant-design/ant-design-mobile#534]
我发现文档大多数都没有针对rn的事例，特别是对于rn下如何定制样式，真是一头雾水，很期待把文档补全

**Comment by warmhug** [comment]
@silentcloud  在此处修改或补充 rn 文档 https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#react-native-示例

**Comment by silentcloud** [comment]
@warmhug 这个是需要每个组件 check 的，rn 的组件文档目前比较弱，readme 里是没问题的

**Comment by silentcloud** [comment]
链接到这里  #536
