### ISSUE TITLE
希望 Cascader 组件可以增加最后一级多选功能

### ISSUE THREAD

**Issue by StarCoderLn** [ant-design/ant-design-mobile#5342]
### What is this feature about?

现在的 Cascader 组件只能支持单选，希望能够支持多选

**Comment by awmleer** [comment]
目前来看不会支持多选，因为会影响到交互，后面（可能是下个大版本）的 Cascader 会改成点击最后一级的选项之后立刻收起面板并触发 `onConfirm`，这种交互是无法支持多选的

如果需要多选，可以考虑基于 Popup Tabs CheckList Selector 这些组件自己实现一个定制化的选择器，不会很难的
