### ISSUE TITLE
[Data Entry] - CheckList value with array of objects as default value 

### ISSUE THREAD

**Issue by 00010100** [ant-design/ant-design-mobile#5344]
### Version of antd-mobile

5.15.0

### What is this feature about?

Component `CheckList` accepts only array of `strings`  as value, but it works with array of objects partly.
The issue is - when you wanted to add some array of objects as checked value by default it doesn't work.
Would be great if you can add this opportunity

```
const value = [{ id: "1", value: "1", label: "1" }]

<CheckList value={value} onChange={onChange}>
  <CheckList.Item item={item}>{item.label}</CheckList.Item>
</CheckList>
```

**Comment by awmleer** [comment]
We'll not likely to support this feature. Currently `CheckList` uses `value` as the `key` of items. And only `string` and `number` can be used as a React element key. You have to write something like a map or object record for mapping the string `value`s to objects.
