### ISSUE TITLE
安卓微信中TextArea使用autoSize时，页面闪动

### ISSUE THREAD

**Issue by bmw335** [ant-design/ant-design-mobile#5347]
### Version of antd-mobile

5.0.0

### Operating system and its version

Android

### Browser and its version

微信浏览器

### Sandbox to reproduce

https://codesandbox.io/s/dazzling-bell-642mwc?file=/src/App.tsx

### What happened?

输入或者删除文字，有明显闪动。可以见[录屏](https://imagetest.youshikoudai.com/test/testTextArea.mp4)

**Comment by awmleer** [comment]
@bmw335 可不可以麻烦试一下如果把 `autoSize` 属性去掉，还会不会出现闪烁的问题？

**Comment by awmleer** [comment]
我只能推测出来是哪里导致的这个问题，先这样尝试修复了一下： 86c70fcf

后面你可以升级一下版本再验证下，如果有问题的话，可以再 reopen 这个 issue
