### ISSUE TITLE
组件Tabs在项目使用中有点问题

### ISSUE THREAD

**Issue by xfcdxg** [ant-design/ant-design-mobile#535]
#### 本地环境

- antd-mobile 版本：0.8.7
- 操作系统及其版本：mac os 
- 浏览器及其版本：chrome lastest

#### 你做了什么？

引入 antd-mobile 的 Tabs

#### 你期待的结果是：

1.  纵向滑动不触发切换tab。
2.  数据量较大的页面滑动时不会有卡顿的现象。

#### 实际上的结果：

1.  当纵向滑动某一个tab content的时候会左右偏移（滑动切换tab）。
2.  通过滑动来切换tab的时候会有卡顿的现象。

#### 可重现的在线演示

http://boluome.otosaas.com/waimai

进入页面后随便点击一家餐厅，选食物的那页就是用了tabs组件。
左右滑动会有卡顿现象，上下滑动会造成content偏移。

注：手机进入页面效果会更加明显

**Comment by xfcdxg** [comment]
0 0~求互动。。

**Comment by CodingMonkeyzh** [comment]
我也希望 `Tabs` 组件能够处理这个问题， 一旦进入垂直滚动，应该锁定，就不能在进入切换 tab 的动画了。 
看源码发现 `Tabs` 引用了 `rc-tabs`，而 `rc-tabs` 在处理 tab content 区域滑动切换时，用了 `react-hammerjs` 这个库。

**Comment by silentcloud** [comment]
卡顿的现象我这边手机 ( iP6+) 看了哈，还好，垂直滚动偏移，我看 demo 链接禁用了 swipeable？

**Comment by CodingMonkeyzh** [comment]
@silentcloud 应该是后来禁用了，之前我看题主发的 demo 是可左右滑动的，不过效果表现得很糟糕。

**Comment by warmhug** [comment]
@silentcloud review 下，没问题了关掉

**Comment by warmhug** [comment]
上下滑动会造成content偏移  ，这个问题确实存在。 手势的角度要控制下的  @yiminghe

**Comment by warmhug** [comment]
> 上下滑动会造成content偏移 ，这个问题确实存在。 手势的角度要控制下

@silentcloud 跟进修复下

**Comment by yeyuguo** [comment]
我也遇到了这个问题。求解决办法，我看 @xfcdxg  你的demo 操作是正常的，是如何解决的？

**Comment by xfcdxg** [comment]
我禁用了滑动切换。。

**Comment by paranoidjk** [comment]
@warmhug @yeyuguo @xfcdxg  @CodingMonkeyzh 
- 并不是bug，而是by design, `rc-tabs`在 tab content `onPan`的时候会加一个`translateX`的动画
- 而`onPan`这个手势本来在垂直(带点倾斜)滑动都是可以触发的，参看 http://hammerjs.github.io/ 官网下面的demo滑动

解决方案：
- 用户可以先`animated={false}` 禁用动画

后续:
- 我会修改组件可接收`hammerOption`，让用户可以配置手势触发的阈值http://hammerjs.github.io/recognizer-pan/

**Comment by Yixeu** [comment]
这个问题为什么关掉了，2.3.1的tabs还是有这个问题啊
