### ISSUE TITLE
input在modal里无法工作

### ISSUE THREAD

**Issue by hu-tu-yi-shi** [ant-design/ant-design-mobile#5350]
### Version of antd-mobile

5.15.1

### Operating system and its version

Others

### Browser and its version

chrome,safari

### Sandbox to reproduce

https://codesandbox.io/s/magical-swartz-rgk16z?file=/src/App.js

### What happened?

input放到modal里， 就没法正常输入了，  
 
<img width="780" alt="image" src="https://user-images.githubusercontent.com/104620424/174432530-fd46f3ff-462f-4bb0-a521-9043dcc4594a.png">

我在这个输入框，不管怎么输入， 输入框都没有反应

**Comment by GOWxx** [comment]
指令式创建出来的 Modal，并不会感知父组件的重渲染和其中 state 的更新

如果你需要在 Dialog 中包含很多复杂的状态和逻辑，那么可以使用声明式的语法，或者考虑自己将内部状态和逻辑单独封装一个组件出来，详见 [#4762](https://github.com/ant-design/ant-design-mobile/issues/4762)

在你的代码基础上改了下，抽成了个单独的组件，就可以了，可以参考这个 [demo](https://codesandbox.io/s/goofy-newton-wnwgcg?file=/src/App.js)
