### ISSUE TITLE
Modal.confirm里面的按钮 不要用 button，请用div

### ISSUE THREAD

**Issue by hu-tu-yi-shi** [ant-design/ant-design-mobile#5353]
### Version of antd-mobile

5.15

### Operating system and its version

Others

### Browser and its version

所有

### Sandbox to reproduce

无

### What happened?

目前的[ Modal.confirm ](https://mobile.ant.design/zh/components/modal#modalconfirm), 可以设置 取消 和确定按钮的文字

他们接受 ReactNode , 而不是 string
 
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/104620424/174446924-a1ac9bd5-628a-44ce-9ea9-d11313cc0ee8.png">

我们项目里， button 是设置了样式的(有样式，有背景图)， 所以我直接把 我们的按钮传给了 cancelText、confirmText, 结果导致报错：
`devScripts.js:6523 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.`

<img width="663" alt="image" src="https://user-images.githubusercontent.com/104620424/174447003-37117cf8-39e1-444b-a1dc-71f150b0d400.png">

这是因为 我的 button 被 modal的 button包裹了，  所以才报错

我希望，可以修改这2个属性，不要用button ，或者 新增 2个属性，用户可以传入自己的按钮

或者加个判断，如果传入的是string，那就套个button， 如果是reactnode，那就不套button

----

虽然 有  [centerpopup]( https://mobile.ant.design/zh/components/popup#centerpopup )  可以自己定制，但是 只因为2个按钮，就专门去制作一个modal，有些麻烦

谢谢

**Comment by hu-tu-yi-shi** [comment]
Modal.alert   应该也有这个问题

**Comment by hu-tu-yi-shi** [comment]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/104620424/174447283-16a4d87d-ea9e-4a02-bb42-68a845a6b7f8.png">

**Comment by yangdepp** [comment]
@awmleer 感觉是会有这个问题，我感觉这里可以更加灵活一下，用户传入`string`类型就使用`Button`包裹，传入`ReactNode`用户自己控制样式，因为本来`Action`的类型就是支持`className`的。
另外：我看`Modal.confirm`的`cancelText` `confirmText`最后都是传给了`actions`的`text`，这里有点不够统一，`cancelText` `confirmText`的类型是`ReactNode`，`actions`的`text`类型又是`string`，这里应该是可以改成`ReactNode`做一下增强。

**Comment by awmleer** [comment]
> 用户传入`string`类型就使用`Button`包裹，传入`ReactNode`用户自己控制样式

这样的话，如果用户只是想把默认的 “确定” 改成 “确定”+一个图标，实际写起来就会麻烦很多了

而且 Button 的渲染还受 `Action` 上的 `disabled` `danger` `primary` 这些属性控制，没有办法直接 `text` 属性的 ReactNode 覆盖整个 Button 元素，`text` 顾名思义，就是用来调整按钮里面的文案的，不是用来设置背景图的，如果想设置背景图，可以考虑加个 `className`，然后通过 CSS 加 `background-image`

> 我看Modal.confirm的cancelText confirmText最后都是传给了actions的text，这里有点不够统一，cancelText confirmText的类型是ReactNode，actions的text类型又是string，这里应该是可以改成ReactNode做一下增强

@yangdepp 这个感觉 OK 的～应该是之前写的时候不太严谨，ts 类型是要保持一致的

**Comment by yangdepp** [comment]
> 这样的话，如果用户只是想把默认的 “确定” 改成 “确定”+一个图标，实际写起来就会麻烦很多了

确实，这样更改的话，还会造成`breakchange`，用户可能传入的就是`ReactNode `升级后样式会失效

> 如果想设置背景图，可以考虑加个 className，然后通过 CSS 加 background-image

这个其实改成用`Modal.show`，传入`actions`时候，是支持传入`className`的，把`text`改成`ReactNode `应该可以支持自定义`button`，我先写个例子试试。

**Comment by yangdepp** [comment]
@hu-tu-yi-shi 
你原先的`Modal.confirm`可以改成`Modal.show`形式，`Modal.show`是支持传入`actions`的，在传入的`actions`中，可以传入自定义的`className`，但是在发版前`actions`的`text`还只支持`string`，当然如果你没使用`TS`也可以直接传入`ReactNode`

```jsx
    <Button
      block
      onClick={() => {
        Modal.show({
          content: '人在天边月上明，风初紧，吹入画帘旌',
          closeOnAction: true,
          actions: [
            {
              key: 'confirm',
              text: '确认',
              className: 'with-confirm-image-background',
            },
            {
              key: 'cancel',
              text: '取消',
              className: 'with-cancel-image-background',
            }
          ],
        })
      }}
    >
      带背景图按钮
    </Button>

```
然后在`css`中设置背景图及你自定义的样式即可。

**Comment by hu-tu-yi-shi** [comment]
@yangdepp 

 谢谢

我的项目用到了ts，   

我主要的痛点是， 我传入的button 和 modal里自带的button， 导致了2个button包裹， 结果 react报错 ， 虽然不影响使用，但总觉得有点强迫症

**Comment by yangdepp** [comment]
> 我主要的痛点是， 我传入的button 和 modal里自带的button， 导致了2个button包裹， 结果 react报错 ， 虽然不影响使用，但总觉得有点强迫症

我知道，我的意思就是你可以把你自定义的那个`button`的样式，改成`Modal.show`的形式后，转移到你传入的`className`里面，这样就不会有包裹的`button`警吿了。

**Comment by hu-tu-yi-shi** [comment]
@yangdepp 

谢谢老哥
