### ISSUE TITLE
tabs组件是否可以支持header扩展

### ISSUE THREAD

**Issue by Jackie-llv** [ant-design/ant-design-mobile#5358]
<img width="266" alt="image" src="https://user-images.githubusercontent.com/28420052/174583288-0b975701-3848-4527-8cdd-1d1b1515b0ed.png">
类似这种

**Comment by miracles1919** [comment]
title 是 ReactNode 类型，可以这样 `<Tabs.Tab title={<div>title <Icon /></div} /> `

**Comment by Jackie-llv** [comment]
> title 是 ReactNode 类型，可以这样 `<Tabs.Tab title={<div>title <Icon /></div} /> `

哪个icon得固定在右边，而且tab项还有好多个，可以滑动的那种，title实现不了吧

**Comment by miracles1919** [comment]
固定右边的话，这样？
```
<div>
  <Tabs />
  <Icon />
</div>
```
