### ISSUE TITLE
List + InfiniteScroll 初始化数据后滚动条会记忆上次的滚动距离，导致一直加载数据，直到之前的滚动位置

### ISSUE THREAD

**Issue by zyanfly** [ant-design/ant-design-mobile#5360]
### Version of antd-mobile

5.10.0

### Operating system and its version

Others

### Browser and its version

chrome 102.0.5005.115

### Sandbox to reproduce

[demo](https://codesandbox.io/s/condescending-darkness-k8fl5j)

### What happened?

一个很常见的业务场景：
list 列表 + InfiniteScroll上拉加载更多
当往下滚动了多组数据后，如果触发了某个条件需要重新初始化页面，重新进入第一组数据，list的滚动条会记忆（不正常）之前的滚动距离，导致一直加载更多，直到滚动条滚动到上一次数据滚动条的位置才会停止。

**Comment by Gianna-w** [comment]
遇到了类似问题，蹲一下

**Comment by zyanfly** [comment]
写了个[demo](https://codesandbox.io/s/condescending-darkness-k8fl5j)
如果直接替换数据，比如一个长度为100的数据替换为长度为10的数据，就会复现上面的问题，这在场景中很场景，比如我更新了筛选条件，那么数据请求回来后会直接设置，这就会有上面的bug
暂时的解决方案：
判断是否是重新请求数据，而不是加载更多，若是重新请求，在请求前先置空数据，比如：setData([])，然后再请求数据并将数据填充。

**Comment by zyanfly** [comment]
> ### 可以看看这个 [demo](https://codesandbox.io/s/mystifying-glitter-knpc7u?file=/src/components/getPullToRefreshlData.tsx)
> 在这个 demo 里并没有复现你说的问题，这会记忆，但并没有导致加载更多
> 
> [Tabs 怎么配合 Swiper、PullToRefresh、InfiniteScroll 实现一个复杂的信息流界面？](https://mobile.ant.design/zh/components/tabs#tabs-%E6%80%8E%E4%B9%88%E9%85%8D%E5%90%88-swiperpulltorefreshinfinitescroll-%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E5%A4%8D%E6%9D%82%E7%9A%84%E4%BF%A1%E6%81%AF%E6%B5%81%E7%95%8C%E9%9D%A2)
> 
> 在 tabs 这个组件的 FAQ 部分 ![image](https://github.com/assets/12870715/99d38512-9445-40fe-860d-1d445e542cca)
> 
> ### 或者你可以在在线环境写一个复现 demo？
> 不用配置本地环境，直接创建一个 [sandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile) 项目，就可以在线写 demo 了

**Comment by zyanfly** [comment]
> 遇到了类似问题，蹲一下

可以试试我上面提供的暂时解决方案

**Comment by miracles1919** [comment]
我试了下 PC 端有这个问题，但手机上是正常的

**Comment by GOWxx** [comment]
miui@12 google chrome 和 微信内 可复现问题

https://user-images.githubusercontent.com/12870715/174743627-3e5897cb-bb34-4a23-a18a-be2d6bf17b0d.mp4


https://user-images.githubusercontent.com/12870715/174743640-d2e9df6f-ff2f-43b8-8546-aae53539c2d1.mp4

**Comment by GOWxx** [comment]
> 比如：setData([])，然后再请求数据并将数据填充。

我试了下你说的，我这里试了下 `setData([])` 不行

我写了个 (demo)[https://codesandbox.io/s/mystifying-sid-nkyh3v?file=/src/App.tsx]
来解决这个问题，每次重新请求的时候，先把 `scrollTop` 设成0，就会到了列表最顶部

```typescript
  const resetScrollTop = () => {
    const admList = document.querySelector(".adm-list");
    if (admList) {
      admList.scrollTop = 0;
    }
  };
```

这样重新请求的时候，就不会一直请求到原位置才停止了

**Comment by awmleer** [comment]
不要给 List 加 `overflow-y: scroll`，也不要把 `InfiniteScroll` 放在 List 中，List 的 children 中应该只有 `List.Item`，不应该有其他元素或组件

更合适的做法是在外层包一个 div，当重置时，通过 `key` 的变化让 React 销毁整个 DOM 元素并重建，可以看下这个 [demo](https://codesandbox.io/s/awesome-margulis-oigfxz?file=/src/App.tsx) 我改之后的
