### ISSUE TITLE
官方的NavBar例子跑不起来

### ISSUE THREAD

**Issue by ssjjnn** [ant-design/ant-design-mobile#538]
本地环境

- antd-mobile 版本：0.9.8
- 操作系统及其版本：iOS
- 浏览器及其版本：chrome 版本 54.0.2840.71 (64-bit)

官方的NavBar例子跑不起来
![image](https://cloud.githubusercontent.com/assets/22025844/20340227/97a75818-ac1b-11e6-9a6f-0432baadba26.png)
![image](https://cloud.githubusercontent.com/assets/22025844/20340239/9ee7b92e-ac1b-11e6-90fa-246db0d082c0.png)
![image](https://cloud.githubusercontent.com/assets/22025844/20340246/a311e2a4-ac1b-11e6-9bff-526293ba5f29.png)

你期待的结果是：

**Comment by silentcloud** [comment]
@ssjjnn Icon 没有对应的 RN 版本，纯 UI 组件做不了 Icon 组件的，需要 native 支持 custom font
