### ISSUE TITLE
Ellipsis组件在Link下点击展开如何阻止跳转页面

### ISSUE THREAD

**Issue by Sxxiong** [ant-design/ant-design-mobile#5384]
Ellipsis组件在Link下点击展开如何阻止跳转页面
Ellipsis 组件有提供 stopPropagationForActionButtons

- 文档描述是<html>
<body>

stopPropagationForActionButtons | 阻止展开操作，收起操作引发的事件冒泡 | PropagationEvent[] | []
-- | -- | -- | --

</body>
</html>

但是不知道怎么使用 有大佬教教么
代码片段如下:
```
<Link to="/">
  <Ellipsis
    direction="end"
    content={content}
    expandText="展开"
    collapseText="收起"
  />
</Link>
```
[复现demo](https://codesandbox.io/s/fervent-dijkstra-sqdf84?file=/src/Home/index.jsx:287-451)

_Originally posted by @Sxxiong in https://github.com/ant-design/ant-design-mobile/discussions/5383_

**Comment by awmleer** [comment]
https://github.com/ant-design/ant-design-mobile/discussions/5383#discussioncomment-3006942
