### ISSUE TITLE
支持深色模式

### ISSUE THREAD

**Issue by miracles1919** [ant-design/ant-design-mobile#5390]
### What is this feature about?

目前[深色模式](https://mobile.ant.design/zh/guide/dark-mode)还在试验性阶段，某些组件对深色模式的适配不够完善，统一记录在这

PR welcome ~

**Comment by GOWxx** [comment]
# 优化列表（组件部分）

**有些组件记录在此相同的原因，并没有多加分辨，只尽可能全的记录现象。**

## 组件

### 图标

- [ ] 图标 - 图标列表选择器按钮 选中状态

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/12870715/175236802-218cba8d-4195-48b5-8437-11cb4b376ca2.png">

### 安全区

- [ ] 安全区 - 说明 - 是否需要更换说明图片

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/12870715/175237806-0902452e-3581-4158-9899-53c01b5d0ab1.png">

### 侧边导航

- [ ] 侧边导航 - demo3 demo4 页面背景色

<img width="1690" alt="image" src="https://user-images.githubusercontent.com/12870715/175238194-1f329eda-8ef8-4ca7-879f-345cee58c906.png">

### 标签栏

- [ ] 标签栏 - dmeo2 没在暗黑模式

<img width="1718" alt="image" src="https://user-images.githubusercontent.com/12870715/175238534-d177ed2e-5496-434c-9c92-e0f8f922f8ed.png">

### 头像

- [ ] 头像 - 占位头像颜色是否合理

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/12870715/175238766-08542856-bce9-4dc2-b560-8f0f091955e9.png">

### 浮动面板

- [ ] 浮动面板 - 浮动面板 header 和 滚动条颜色
- [ ] 浮动面板 - demo2 底色和列表颜色

<img width="1568" alt="image" src="https://user-images.githubusercontent.com/12870715/175239426-bd38fa2a-b354-4f09-ad2a-712b1ca6c66d.png">

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/12870715/175239683-f0342a49-eb08-4bad-bb55-3898e136d4b5.png">

### 列表

- [ ] 列表 - demo4 滚动条颜色

<img width="1570" alt="image" src="https://user-images.githubusercontent.com/12870715/175241304-667471ab-50cb-47d1-a167-b91da4b198f9.png">

### 页码指示器

- [ ] 页码指示器 - 这个条条颜色是否需要优化

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/12870715/175242219-0d48cd01-6ac3-4afa-baaf-23c693121c7b.png">

### 走马灯

- [ ] 走马灯 - 全屏引导 - 弹出层第三张 底色

<img width="1708" alt="image" src="https://user-images.githubusercontent.com/12870715/175242621-f9c2cf9a-7d06-48ce-8c0c-9062c520bd03.png">

### 级联选择

- [ ] 级联选择 - 长列表滚动轴

![image](https://user-images.githubusercontent.com/12870715/175243283-f58627b0-cf75-4642-b8d2-1378052fd783.png)

### 可勾选列表

- [ ] 可勾选列表 - 长列表滚动轴

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/12870715/175245949-69e1b81c-01f9-4be3-808f-610e448724ff.png">

### 表单

- [ ] 表单 -  demo1  - 点击生日弹出 picker-view, picker 组件暗黑模式缺失
- [ ] 表单 -  demo1  - selector 组件选中模式颜色是否需要优化

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/12870715/175247232-657cd6e5-6dbc-45b6-97a9-e1bd45e5138c.png">

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/12870715/175247536-02412509-c8b0-44c6-9b45-fb54a47a4682.png">

### Picker 选择器

- [ ] Picker 选择器暗黑样式缺失

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/12870715/175248299-5069762c-5db4-4964-99bb-75a43f286f29.png">

### PickerView 选择器视图

- [ ] PickerView 选择器视图暗黑样式缺失

![image](https://user-images.githubusercontent.com/12870715/175248537-a6302bc8-3833-4ed4-9a60-9019463b1f56.png)

###  搜索框

- [ ] SearchBar 搜索框 adm-search-bar 暗黑模式指定了背景色是白色

<img width="1563" alt="image" src="https://user-images.githubusercontent.com/12870715/175248832-d58245c3-066c-45a7-9eda-034ef09a69e0.png">

### 选择器组

- [ ] 选择器组选中样式是否需要优化

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/12870715/175249227-4041042b-91b3-46ff-bff8-dc083dca10b5.png">

### Slider 滑动输入条

- [ ] adm-slider-thumb 颜色是否需要优化

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/12870715/175250137-188c91e5-51a2-471f-93e3-04a8291d1291.png">

### Stepper 步进器

- [ ] demo2 - 自定义颜色 背景色是白色

<img width="1609" alt="image" src="https://user-images.githubusercontent.com/12870715/175250450-38c51f17-8ca7-4de0-82b9-85c3009a9a14.png">

### ActionSheet 动作面板

- [ ] 点击时背景色需要优化

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/12870715/175251031-8d27d4e9-37df-4680-8e46-3a4f8b4900d7.png">

### Dialog 对话框

- [ ] demo2 超长文本 滚动条颜色

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/12870715/175251531-735fd818-fc51-426a-b4b1-27b4a72c7720.png">

### ErrorBlock 异常

- [ ] demo2 背景色是白色

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/12870715/175251918-9aff50b4-0085-4552-b235-9d7504d4a486.png">

### Mask 遮罩层

- [ ] 显示带内容的遮罩层 背景色是白色

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/12870715/175252285-d591d8ef-779a-4a31-bb4a-821aeec194ce.png">

### Modal 弹窗

- [ ] 超长文本滚动条颜色

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/12870715/175252626-ec89c904-7c9e-4e52-a284-a5f22ed3b452.png">

### Popover 气泡弹出框

- [ ] demo 1 第一个 「点我」 和 「气泡位置」气泡背景色
- [ ] demo 2 第一个和第三个「点我」弹出气泡背景色
- [ ] demo 3 图标是否需要更换

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/12870715/175252892-c65d47d5-1198-4970-899d-249ea963209d.png">

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/12870715/175253331-b3064b7e-27c7-4a3a-a36a-443ec887846d.png">

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/12870715/175253566-54c5f9c4-225f-4acf-a48e-5b841be2d6c7.png">

### Popup 弹出层

- [ ] 内容超长滚动滚动条颜色

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/12870715/175253750-2bdf46c2-e3b8-43d4-9017-aa0aebebf570.png">

### PullToRefresh 下拉刷新

- [ ] demo3 处理刷新失败的情况 背景色
- [ ] demo4 内容区域存在多层嵌套 面板颜色


<img width="1460" alt="image" src="https://user-images.githubusercontent.com/12870715/175254297-0fa2ac0b-0570-4b19-9684-33b3f0c532e9.png">

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/12870715/175254347-609ffe02-73bc-4176-9482-35cf5cbde88b.png">

### Result 结果

- [ ] 所有 demo 背景色

![image](https://user-images.githubusercontent.com/12870715/175254607-5c81bda3-2254-49cd-b71c-677cb1e02b25.png)

### Badge 徽标

- [ ] 颜色是否需要更改

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/12870715/175254873-e14d2618-903e-4dea-978f-61b26746f413.png">

### NoticeBar 通告栏

- [ ] 背景色是否需要更改

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/12870715/175255155-837f9231-8614-4e44-8fce-dd9ed71aa4aa.png">

## 试验性组件

### Dropdown 下拉菜单

- [ ] 组件缺少暗黑模式样式 

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/12870715/175255541-823c344d-e719-4daf-9661-cc7c928e28bc.png">

### ImageUploader 图片上传

- [ ] 自定义上传按钮颜色是否需要优化

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/12870715/175256333-78dcecde-3406-4d39-bbb6-9648fbea533d.png">

### NumberKeyboard 数字键盘

- [ ] 缺少暗黑模式样式

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/12870715/175256651-fd97239a-4f11-4daf-88e1-a8fdbe4a4526.png">

### PasscodeInput 密码输入框

- [ ] 缺少暗黑模式样式

<img width="1602" alt="image" src="https://user-images.githubusercontent.com/12870715/175256803-44ac8264-d1fa-4ee4-8540-cee717c77656.png">

### VirtualInput 虚拟输入框

- [ ] 缺少暗黑模式样式

<img width="1587" alt="image" src="https://user-images.githubusercontent.com/12870715/175257819-dd8bb0a6-4d25-438a-b22e-d002d142dc67.png">

**Comment by awmleer** [comment]
这个 issue 是不是可以关闭了 👀
