### ISSUE TITLE
CheckBox 配合List用法checkbox冒泡问题

### ISSUE THREAD

**Issue by smilelmz** [ant-design/ant-design-mobile#5391]
### Version of antd-mobile

5.16

### What is this feature about?

![image](https://user-images.githubusercontent.com/15361002/175290119-3e724a43-e246-4800-81dc-60a112ba0f1b.png)
![image](https://user-images.githubusercontent.com/15361002/175290408-1fb9ea84-614a-4085-8afa-46914b8fb7d6.png)
应该因为事件冒泡，导致点击左侧checkbox无法选中

**Comment by GOWxx** [comment]
[写了个复现dmo](https://codesandbox.io/s/romantic-kate-vjfi73?file=/src/App.tsx)

实际发生的不是无法选中，而是 `Checkbox` 状态改变了两次。

```typescript
    <List.Item
      prefix={<Checkbox value={props.item} ref={checkboxRef} />}
      onClick={() => {
        checkboxRef.current?.toggle()
      }}
      arrow={false}
    >
      {props.item}
    </List.Item>
```

点击在 `List.Item` ，改变一次选中状态。

点击在 `Checkbox` ，`Checkbox` 改变一次状态，冒泡到 `List.Item` 上触发点击事件，又改变一次状态
看上去就像无法选中。

https://user-images.githubusercontent.com/12870715/175354521-cd7c923c-a3f9-4c1c-ae22-7eac303c9714.mov

**Comment by smilelmz** [comment]
@GOWxx 就是事件冒泡，导致ListItem事件也触发了，其实我第二个截图就是这个意思

**Comment by awmleer** [comment]
@smilelmz 可以看下 https://github.com/ant-design/ant-design-mobile/pull/5396
