### ISSUE TITLE
Popover能否增加一个控制它如何关闭的API

### ISSUE THREAD

**Issue by mik-myp** [ant-design/ant-design-mobile#5394]
### Version of antd-mobile

5.12.4

### What is this feature about?

触发click事件或者touchstart事件等，基于不同的需求去关闭

**Comment by yaogengzhu** [comment]
看下这个文档 是否有帮助 https://mobile.ant.design/zh/components/popover/#ref

**Comment by mik-myp** [comment]
如果是遍历出来的按钮去实现popover呢？
