### ISSUE TITLE
[Empty] iOS 11.4 版本的 svg 图标具有默认 150px 高度，这影响了 Empty 的渲染

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#5400]
### Version of antd-mobile

5.16.1

### Operating system and its version

iOS

### Browser and its version

iOS safari 11.4

### What happened?

```tsx
<Empty />
```

![image](https://user-images.githubusercontent.com/32838658/175488291-963639a0-12e6-4940-aaff-ef20182421b1.png)

## 解决方案

- 通过设置 `height: 41px` 解决

![image](https://user-images.githubusercontent.com/32838658/175488666-85bb2cbf-1d49-47a4-953e-34788f7b6f1d.png)

- 通过设置 `height: intrinsic` 解决

![image](https://user-images.githubusercontent.com/32838658/175488592-9d5c435d-e41b-442a-ac91-946fe1fcb768.png)

**Comment by awmleer** [comment]
诶 `height: intrinsic` 是啥？`height: auto` 可以不？

**Comment by IronKinoko** [comment]
![image](https://user-images.githubusercontent.com/32838658/175505506-13a134c2-5533-4869-922d-d8157764e3cf.png)

**Comment by awmleer** [comment]
> Older webkit browsers also support the unofficial intrinsic value which acts the same as max-content.

来自 [Can I Use](https://caniuse.com/intrinsic-width)

根据这个说明的话，是不是直接用 `height: max-content` 就可以了？

**Comment by IronKinoko** [comment]
试过不生效

![image](https://user-images.githubusercontent.com/32838658/175506686-51d08edb-3988-4b97-ad79-be28dbbce5e4.png)

**Comment by awmleer** [comment]
离谱，那就 `height: intrinsic` 吧…… 1b78356c

**Comment by creeperyang** [comment]
`height: intrinsic` 虽然解决了iOS11的样式兼容问题，但是有几率在iOS14导致页面崩溃。

这里标记一下：去除`height: intrinsic` 解决iOS页面反复崩溃问题。
