### ISSUE TITLE
关于数字键盘的一些问题

### ISSUE THREAD

**Issue by tiany900125** [ant-design/ant-design-mobile#5401]
### Description

1、当我输入框在页面底部时，点击会唤起数字键盘，当input框距离底部的距离小于数字键盘高度时，会遮盖input框内容，能否支持自动计算并适当抬高input 框
2、目前看到input 框是 只读状态所以输入内容只能逐个删除增加，能否支持可编辑状态下 输入呢？并且若是光标可选择中间删除某个内容，计算光标index 和 剩余val 位置？同时计算是否要考虑 居左居右样式问题
3、后期是否有支持 英文和符号效果，交互与系统键盘相同
4、思考一个问题，若是页面中同时使用多个数字键盘输入框，当页面是滚动状态时会不会因为误触碰导致键盘唤起

**Comment by tiany900125** [comment]
have a look

**Comment by awmleer** [comment]
1. 看起来和 #4696 重复了
2. 你指的 input 是 VirtualInput 组件么？目前我们没有想到太好的办法来支持选择中间的某个位置，欢迎来提 RFC 和 PR
3. 不会支持
4. 如果你遇到了 bug，欢迎写个复现 demo 再来提个 issue
