### ISSUE TITLE
UI 组件 FloatingPanel

### ISSUE THREAD

**Issue by wwb-xigua** [ant-design/ant-design-mobile#5405]
### Version of antd-mobile

5.16.1

### What is this feature about?

UI 组件 FloatingPanel 是一个很好的面板，我想用来做一个上滑抽屉，如果可以的话，希望添加以下功能。
1.头部“adm-floating-panel-header”无法控制，希望可以接收dom；
2.children api功能使用说明，起初以为是content内用api，后来发现不生效。想问问这个是干啥用的

**Comment by miracles1919** [comment]
1、还在考虑，#4560
2、children api 指的是什么？

**Comment by wwb-xigua** [comment]
我不确定是不是，我在看floating-panel.d.js,文件的时候发现可以接收一个“ children: ReactNode;”的参数。

**Comment by awmleer** [comment]
就是 React 组件的 `children` 啊

**Comment by awmleer** [comment]
你是想说为什么 ts 类型定义里有 `children` 属性，但是文档上没有写么？ @wwb-xigua

**Comment by wwb-xigua** [comment]
是的

**Comment by awmleer** [comment]
文档上是都统一省略掉了
