### ISSUE TITLE
[Ellipsis]  当父元素为flex布局时，在tab切换时，表现异常

### ISSUE THREAD

**Issue by KingAmo** [ant-design/ant-design-mobile#5407]
### Version of antd-mobile

5.16.1

### Operating system and its version

Others

### Browser and its version

chorme 103

### Sandbox to reproduce

https://codesandbox.io/s/blue-platform-0zvg36?file=/src/App.tsx

### What happened?

如上codesandbox链接中的案例所示， Ellipsis的父元素为flex布局，切换tab时，Ellipsis变短；去掉父元素的display:flex，则表现正常。

**Comment by KingAmo** [comment]
@awmleer 求帮助，有临时的workaround吗

**Comment by miracles1919** [comment]
本质上是由于 Ellipsis 外层 div 宽度变化导致的，你可以这样

```
<div style={{ display: "flex"}}>
  <Ellipsis content={content} style={{ flex: 1 }}  />
</div>
```

**Comment by miracles1919** [comment]
这应该是预期行为

- `Ellipsis` 是动态计算的，`Tabs` 正常切换的时候，会将不可见的 `Tab` 设置为 `display: none`，此时 `Ellipsis` 宽度为 0，所以变成了 `图...` （父元素为 block 的时候也是如此）
- [之前有提过](https://github.com/ant-design/ant-design-mobile/issues/5142#issuecomment-1119729924)，flex-item 的宽度是基于内容的，也就是 `图...` 的宽度，所以再次点击的时候，还是显示 `图...`

**Comment by KingAmo** [comment]
所以当不可见的 Tab 设置为 `display: none`的时候，可以不计算`Ellipsis `的宽度吗

**Comment by awmleer** [comment]
> 所以当不可见的 Tab 设置为 `display: none`的时候，可以不计算`Ellipsis `的宽度吗
> 
> 

不可以

**Comment by KingAmo** [comment]
> 本质上是由于 Ellipsis 外层 div 宽度变化导致的，你可以这样
> 
> ```
> <div style={{ display: "flex"}}>
>   <Ellipsis content={content} style={{ flex: 1 }}  />
> </div>
> ```
> 
> 或者这样
> 
> ```
> <Tabs.tab forceRender={true}>
>   <div style={{ display: "flex"}}>
>     <Ellipsis content={content}   />
>   </div>
> </Tabs.tab>
> ```

前者会改变页面样式，后者不起作用

**Comment by KingAmo** [comment]
Tabs.tab用 destroyOnClose 可以勉强解决问题，业务上但是tab再次聚焦要重新请求接口，体验很差

**Comment by miracles1919** [comment]
我写错了，是 `destroyOnClose` .. 

可以看下你真实的场景么..

**Comment by KingAmo** [comment]
我认为在当前提供的案例的场景就是一个bug....

**Comment by awmleer** [comment]
我仔细看了一下你的 demo，更倾向于认为这是 Ellipsis 的预期行为，而出现问题的原因是你 CSS 写的有问题，你改成这样就可以了：

```jsx
<div style={{ display: "flex" }}>
  <div style={{ flex: 'auto' }}>
    <Ellipsis content={content} />
  </div>
</div>
```
