### ISSUE TITLE
TabBar 的 onChange 为什么在同 key 的情况也会触发

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#5409]
### Discussed in https://github.com/ant-design/ant-design-mobile/discussions/5408

<div type='discussions-op-text'>

<sup>Originally posted by **a145789** June 27, 2022</sup>
连续点击 TabBar 的某一 Item ,即使是 key 值相同，onChange 也会触发，onChange 事件应该是在 key 值不同的时候触发吧。

疑惑的点是，顺便看了下其他的 UI 库，除了 vant 其他的也都是相同逻辑，只有 vant 在 key 值相同时不触发。设计如此么？</div>

**Comment by miracles1919** [comment]
看了下 `usePropsValue` 的逻辑.. 其他用到的组件应该也会这样，我改下试试
