### ISSUE TITLE
使用ListView加载一定数据后，能通过什么方法回到之前的滚动条的滚动位置？

### ISSUE THREAD

**Issue by dianjie** [ant-design/ant-design-mobile#541]
#### 本地环境
- antd-mobile 版本：0.9.7
- 操作系统及其版本：window
- 浏览器及其版本：chrome

#### 你做了什么？

ListView的`dataSource`有一定数量后，离开页面返回显示的时候滚动条位置能跳到指定位置？

#### 你期待的结果是：
好比如：使用ListView显示文章列表，用户看到了第150个文章的时候点进去看详情，返回列表的时候滚动条位置定位到第150的文章

**Comment by warmhug** [comment]
浏览器返回键应该可以吧

**Comment by dianjie** [comment]
@warmhug 
我录了一个gif,每次看详情的时候数据还是存留着的，且返回不存在再次获取数据问题，但是默认还是渲染10条数据！！难道只有通过`initialListSize`动态设置？

![test2](https://cloud.githubusercontent.com/assets/16601627/20415974/c540e490-ad76-11e6-8345-6be85f2018b9.gif)

关键代码：
`render() {
        let {topics}=this.props;
        let {list}=topics;
        console.log(list.length);
        const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        return (
            <div className="pt_09">
                <ListView
                    ref="topicList"
                    dataSource={ds.cloneWithRows(list)}
                    useBodyScroll
                    renderRow={this._renderRow.bind(this)}
                    renderSeparator={(sectionID, rowID)=>{return(
                    <div key={`${sectionID}-${rowID}`} style={{height:'.15rem',backgroundColor:"#f5f5f9"}}></div>
                    )}}
                    onEndReached={this.onEndReached.bind(this)}
                    scrollRenderAheadDistance={900}
                    onEndReachedThreshold={10}
                    scrollEventThrottle={30}
                />
            </div>
        )
    }`

**Comment by warmhug** [comment]
对无尽列表来说，返回到原来位置比较难搞。。

**Comment by leonardgithub** [comment]
@dianjie 你用的是react-router吗？话说tabs和tabbar是能够缓存ListView的位置的

**Comment by dianjie** [comment]
@leonardgithub tabs和tabbar是可以的，ListView就不行，现在只有通过`initialListSize`来设置加载足够数量的数据，再自己重置`scrollTop`位置

**Comment by leonardgithub** [comment]
@dianjie 能否看下react-router有没有缓存的设置？以及listView的component有没有每次componentWillMount都重新渲染了一次listView，如果有，试试取消，即只渲染一次，之后的componentWillMount都不渲染

**Comment by dianjie** [comment]
@leonardgithub  [路由设置](https://github.com/dianjie/cnode/blob/master/src/router.js)
[列表代码](https://github.com/dianjie/cnode/blob/master/src/page/topic/topic.list.js)

**Comment by warmhug** [comment]
关联 #488
ListView 有三种类型的滚动容器：1. html 的 body 容器 2. 局部 div 容器 (通过 ref 获取到) 3. 使用 [zscroller](https://github.com/yiminghe/zscroller) 的模拟滚动容器 。前两种获取到相应元素后，调用 scrollTo 方法、滚动到指定位置；第三种通过 ref 获取到组件对象、再获取到 domScroller 、调用 scrollTo 方法。 但滚动到具体什么位置，业务上其实也比较难确定。
