### ISSUE TITLE
TimePicker是否会实现

### ISSUE THREAD

**Issue by tenkiss258** [ant-design/ant-design-mobile#5412]
### Version of antd-mobile

5.16.1

### What is this feature about?

想实现一个时间选择器，目前在DatePicker上有一个写法，但样式不美观。
附上代码

**Comment by tenkiss258** [comment]
想实现一个时间选择器，目前在DatePicker上有一个写法，但样式不美观。
附上代码
```
 const labelRenderer = useCallback((type: string, data: number) => {
    switch (type) {
      case 'hour':
        return data + '时'
      case 'minute':
        return data + '分'
      case 'second':
        return data + '秒'
      default:
        return false
    }
  }, [])
<DatePicker
    visible={visible}
    onClose={() => {
      setVisible(false);
    }}
    renderLabel={labelRenderer}
    precision="second"
  >
    {value =>
      value ? moment(value).format('HH:mm:ss') : '请选择时间'
    }
  </DatePicker>
```

**Comment by tenkiss258** [comment]
只有代码了，图片上不去。

**Comment by GOWxx** [comment]
> 只有代码了，图片上不去。

想写 demo 的话可以考虑 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx) , 已经是一个 antd-mobile 的默认模版了.

**Comment by tenkiss258** [comment]
https://stackblitz.com/edit/antd-mobile-hzpyoc?file=index.tsx
`demo` 链接

**Comment by awmleer** [comment]
请读文档 [日期选择器为什么没有 "时-分" 或者 "月-日" 选择？](https://mobile.ant.design/zh/components/picker#%E6%97%A5%E6%9C%9F%E9%80%89%E6%8B%A9%E5%99%A8%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89-%E6%97%B6-%E5%88%86-%E6%88%96%E8%80%85-%E6%9C%88-%E6%97%A5-%E9%80%89%E6%8B%A9)

**Comment by tenkiss258** [comment]
我的标题是，以后会不会实现TimePicker。

**Comment by awmleer** [comment]
> 我的标题是，以后会不会实现TimePicker。

不会的
