### ISSUE TITLE
dialog onConfirm回调函数无法正常获取useState定义的变量

### ISSUE THREAD

**Issue by Mr-Nobody-li** [ant-design/ant-design-mobile#5420]
### Version of antd-mobile

5.16.1

### Operating system and its version

Android

### Browser and its version

chrome

### Sandbox to reproduce

https://codesandbox.io/s/twilight-browser-orydcw?file=/src/App.tsx

### What happened?

使用指令式创建dialog时，onConfirm无法正常获取useState定义的变量

详见demo

与[#4762](https://github.com/ant-design/ant-design-mobile/issues/4762)类似，应该也是dialog组件没有更新原因，请问如何在确认回调中获取正确的state

**Comment by Przeblysk** [comment]
用 ref

**Comment by miracles1919** [comment]
#4762 里不是回答了么..

> 而解决方法有两种：
> 1. 正如你自己在补充中提到的，使用声明式的语法可以保持 App 和 Dialog 的父子组件关系，从而避免了这种问题
> 2. 对 Input 部分的逻辑独立封装一个组件出来，这样就不会出现“数据和状态在 App 中，Input 组件本身在 Dialog 中”这种割裂的情况了

**Comment by miracles1919** [comment]
建议你先看下官网 [声明式的demo](https://mobile.ant.design/zh/components/dialog#%E7%A4%BA%E4%BE%8B)

![image](https://user-images.githubusercontent.com/22469543/176149924-2c73012b-4734-46f4-9e08-b22f1277a783.png)

**Comment by hhhawaii** [comment]
> 建议你先看下官网 [声明式的demo](https://mobile.ant.design/zh/components/dialog#%E7%A4%BA%E4%BE%8B)
> 
> ![image](https://user-images.githubusercontent.com/22469543/176149924-2c73012b-4734-46f4-9e08-b22f1277a783.png)
大佬可以详细说说吗 我怎么没看懂
