### ISSUE TITLE
Popover 在 Mask 里面时，无法点击其它空白地方关闭浮层

### ISSUE THREAD

**Issue by viewweiwu** [ant-design/ant-design-mobile#5424]
### Version of antd-mobile

5.16.1

### Browser and its version

Mac Chrome 103

### Sandbox to reproduce

https://codesandbox.io/s/eloquent-forest-8greee?file=/src/App.js

### What happened?

点击其它空白地方应该关闭 Popover 的浮层

### Relevant log output

```shell
-
```

**Comment by IronKinoko** [comment]
因为 `Mask` 组件默认阻止了 `click` 事件冒泡，你可以设置 `<Mask stopPropagation={[]}>` 解决这个问题
