### ISSUE TITLE
为什么所有的字体和空隙都很大

### ISSUE THREAD

**Issue by songlipeng2003** [ant-design/ant-design-mobile#543]
![image](https://cloud.githubusercontent.com/assets/89021/20382025/0c1f44f2-ace5-11e6-905d-04397667de7f.png)

字号都是30px+的。太夸张了。我看demo里面是好的。

- antd-mobile 版本：0.9.8
- 操作系统及其版本：mac
- 浏览器及其版本：chrome

**Comment by afc163** [comment]
@warmhug 老师快去搞一下这个: https://github.com/ant-design/ant-design-mobile/issues/367

**Comment by warmhug** [comment]
哎，高清方案。。

**Comment by songlipeng2003** [comment]
@warmhug 啥意思？

**Comment by warmhug** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#使用

先仔细翻看下文档吧

**Comment by songlipeng2003** [comment]
谢谢了，@warmbug 只是不太懂为啥会有这个高清方案？

**Comment by warmhug** [comment]
或许就像为什么要有 Retina 屏幕呢

**Comment by songlipeng2003** [comment]
好吧。或许明白你点你意思了。我是按照web浏览器来看的。分辨率本身会缩放，你其实相当于用实际分辨率来搞的。react native下估计会ok。
