### ISSUE TITLE
[Bug] 组件Badge比组件TabBar的z-index大

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#544]
#### 本地环境

- antd-mobile 版本：0.9.7
- 操作系统及其版本：mac
- 浏览器及其版本：chrome

#### 你做了什么？

将Badge组件放入ListView滚动到下方TabBar组件时Badge组件出现在TabBar组件上方
#### 实际上的结果：
将Badge组件放入ListView滚动到下方TabBar组件时Badge组件出现在TabBar组件上方

**Comment by warmhug** [comment]
Badge 的 z-index 取决于放它的容器， TabBar 的 z-index 可以自己设置。

**Comment by silentcloud** [comment]
@liubin1023  Tab-bar 图标上面也会有 Badge，所以两种情况都会有，建议自己根据情况设置一下 z-index
