### ISSUE TITLE
在DatePicker增加选择日/月/年的选项

### ISSUE THREAD

**Issue by eejoylim** [ant-design/ant-design-mobile#5441]
### Version of antd-mobile

5.0.0

### What is this feature about?

从我目前看来 只能让弹出来的视窗显示 从年开始到时间 因为客户要求 希望选择视窗可以从日开始

![Screenshot 2022-07-05 170151](https://user-images.githubusercontent.com/107380914/177296848-81a84ce8-de5f-4b69-9563-c6fb4f714559.png)

**Comment by GOWxx** [comment]
可以阅读文档
[日期选择器为什么没有 "时-分" 或者 "月-日" 选择？](https://mobile.ant.design/zh/components/picker#%E6%97%A5%E6%9C%9F%E9%80%89%E6%8B%A9%E5%99%A8%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89-%E6%97%B6-%E5%88%86-%E6%88%96%E8%80%85-%E6%9C%88-%E6%97%A5-%E9%80%89%E6%8B%A9)

不同于 Picker 组件，DatePicker 的值的类型是 Date 对象，所以需要从年开始一直往下选择，只有时、分的参数是不能构建一个 Date 对象的。

如果你需要使用这样的选择器，可以通过 Picker 组件自行实现。

**Comment by GOWxx** [comment]
same #5412

**Comment by GOWxx** [comment]
抱歉，我之前理解错了，错误的 close 了你的 issues.

**Comment by awmleer** [comment]
暂时不会支持的，我目前想到的几个问题：

1. 交互上很奇怪，用户需要先转动最右边的拨轮，再转动中间的，再转动左边的，这个从右往左的级联顺序违背了我们其他组件的交互一致性，而如果还需要同时展示时间，操作顺序就会变得更加混乱
2. 语义的准确性可能会受影响，因为现在默认是只显示数字，不显示“月”、“日”之类的文字，所以如果支持你所说的这个特性的话，用户很难区别第一列和第二列哪个是月哪个是日，特别是如果初始值是都是 1 的话，月和日这两列看上去是一模一样的
3. 实现成本可能会比较高，对后续的可维护性的影响也不能忽略不计，而功能本身可能又是一个非常小众的场景

或许你的客户认为这是一个合理的需求/交互，但站在组件库本身的角度考虑，这个交互目前来看没有办法纳入，我们会留意看看后面有没有其他场景也有类似的需求，但这个 issue 我先关闭完结掉

最后，如果你一定要实现这样的效果，可以考虑在你的业务项目中基于 Picker 组件自己封装一个

**Comment by eejoylim** [comment]
那请问有没有可能允许第二排的月换成MMM（例如: Jan, Feb, Mar, etc）呢？

**Comment by GOWxx** [comment]
> 那请问有没有可能允许第二排的月换成MMM（例如: Jan, Feb, Mar, etc）呢？

这个可以用 `renderLabel` 来实现吧


属性 | 说明 | 类型 | 默认值
-- | -- | -- | --
renderLabel | 自定义渲染每列展示的内容。其中 `type` 参数为 `precision` 中的任意值，`data` 参数为默认渲染的数字 | `(type: string, data: number) => ReactNode` | -



可以阅读[参考文档](https://mobile.ant.design/zh/components/picker#%E5%B1%9E%E6%80%A7-2)，页面内也包括使用demo

**Comment by eejoylim** [comment]
好的 非常感谢！
