### ISSUE TITLE
在浏览器开启翻译插件时，Button的loading属性改变会导致报错

### ISSUE THREAD

**Issue by frontlich** [ant-design/ant-design-mobile#5442]
### Version of antd-mobile

5.13.1

### Description

https://xfrhns.csb.app/
用浏览器打开上面的链接，先开启浏览器的翻译，然后点击按钮就会报错

https://codesandbox.io/s/gallant-drake-xfrhns?file=/src/App.tsx
源码地址

问题原因：
Button组件部分源码如下：
```js
{loading ? (
  <div className={`${classPrefix}-loading-wrapper`}>
    {props.loadingIcon}
    {props.loadingText}
  </div>
) : (
  props.children
)}
```

浏览器的翻译会给文本节点加上`font`标签，然后改变`loading`属性，react-dom在移除`props.children`时，找不到对应的文本节点就会报错

```js
NotFoundError
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

解决方案？
可否给`props.children`加上一个`span`标签或者`div`标签？这样loading改变时，移除`span`或`div`节点就不会报错。

**Comment by awmleer** [comment]
感觉可以
