### ISSUE TITLE
display由none变为block，InfiniteScroll一直显示加载中

### ISSUE THREAD

**Issue by sdwfqin** [ant-design/ant-design-mobile#5447]
### Version of antd-mobile

5.17.2

### Operating system and its version

iOS, Android, Others

### Browser and its version

windows 11 edge 103 设备仿真

### Sandbox to reproduce

https://github.com/sdwfqin/antd-mobile-InfiniteScroll

### What happened?

布局css的display由none变为block（或tabitem设置forceRender=true），InfiniteScroll一直显示加载中，没有调用加载方法。
![image](https://user-images.githubusercontent.com/13191807/177461155-378e8993-00ee-4c7a-8716-de7bd8dc3030.png)

### Relevant log output

```shell
无
```

**Comment by happycatTI** [comment]
页面使用cdn缓存时也遇到这个问题，在点击浏览器的返回上一个页面时也遇到这个问题，loadMore不再执行，目前只想到刷新页面或者重新装载InfiniteScroll来解决

**Comment by zqran** [comment]
看了下，是因为 `InfiniteScroll` 组件中检查 `offsetParent` 值为 `null`，导致后面 loadMore 函数未调用导致的

https://github.com/ant-design/ant-design-mobile/blob/ea463ee9bb45b79f9767472a5cbdb24d45f5bdd8/src/components/infinite-scroll/infinite-scroll.tsx#L66

为什么 `offsetParent` 值为 `null`？
因为在 @sdwfqin 提供的复现代码中，为 `<Tabs.Tab>` 添加了 `forceRender` 属性，并且改 Tab 在初次渲染时处于非激活状态，所以，其内容被渲染且为隐藏，也就是 `display: none`。而 `display: none` 时，`offsetParent` 获取到的值为 `null`。

如何解决？
1. 去掉 `InfiniteScroll` 组件所在 Tab 的 `forceRender`（ **只在激活并展示 Tab 时，再渲染 `InfiniteScroll` 组件，避免 `offsetParent` 为 `null`** ）
2. 通过受控组件模式使用 `Tabs` 组件（ **切换 Tab 时，重新触发 `InfiniteScroll` 组件检测是否需要加载更多数据的机制** ），示例如下：

```jsx
const [activeKey, setActiveKey] = useState('fruits')

<Tabs activeKey={activeKey} onChange={setActiveKey}>
  ...
</Tabs>
```

**Comment by awmleer** [comment]
感谢 @zqran 解答～issue 我关掉了
