### ISSUE TITLE
使用ListView组件时报错Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by laolu87** [ant-design/ant-design-mobile#545]
#### 本地环境
系统: ubuntu 14.04
浏览器: chromium 53  
antd-mobile版本: 0.9.8

#### 问题描述
使用ListView做了一个demo,结果报错:  
```
vendors.js:683 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```
有使用react-router做路由,然后在一个组件里(这个组件有`import react`,去掉import的react直接报错找不到React)引入官方的ListView组件示例代码.报了上面的错误,请问要怎么解决呢?

**Comment by warmhug** [comment]
`you have multiple copies of React loaded`  请确认下

**Comment by laolu87** [comment]
@warmhug 我确认了,应该是没有呀!就我描述的那样,去掉组件import的react又不能工作了!不知道哪里重复引用了react!

**Comment by njustzl** [comment]
@laolu87 请问您解决了没？怎么解决的？我们也遇到了相同的问题，求，在线等。

**Comment by laolu87** [comment]
@njustzl 没解决，估计要去看源码才能知道问题所在，只能自己实现这个功能了！

**Comment by silentcloud** [comment]
@laolu87 把实例代码打个包，发出来，我们定位一下，或者参看一下 #562

**Comment by silentcloud** [comment]
@laolu87 参见 #562  的解决方案
