### ISSUE TITLE
版本更新后webpack报错

### ISSUE THREAD

**Issue by wwb-xigua** [ant-design/ant-design-mobile#5452]
### Version of antd-mobile

5.16.1

### Operating system and its version

Others

### What happened?

升级了版本，从2.3.4->5.16.1,
需求：同时保留了两个版本
方法： "antd-mobile": "^5.16.1",
    "antd-mobile-v2": "^2.3.4",

impot {***} from 'antd-mobile'
错误：导入插件的时候找不到lib文件（node-modules）

尝试：手动修改了webpack中 
{
                        libraryName: "antd-mobile",
                        libraryDirectory: 'es',
                        style: true
                    }

第二报错 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/76981528/177741949-c0f4a9ad-dd13-4618-9238-e5af0d2eaa6c.png">

**Comment by miracles1919** [comment]
可以把你的项目打个 zip 发到这里，不然没有办法排查

**Comment by wwb-xigua** [comment]
> 加载-E6加载请看这里[https://mobileant.design/zh/guide/import-on demand/#%E%8C%89%9%9C%80%E%A0%E8%BD% BD](https://mobile.ant.design/zh/guide/import-on-demand/#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD)

我按照文档添加了入口与query，本地运行没有问题，打包的时候出现以上找不到antd-mobile/lib/***

以下是图样
1.webpack
<img width="709" alt="image" src="https://user-images.githubusercontent.com/76981528/177897453-982ea62f-1691-4df1-9028-2099861ec818.png">
2.main.jsx
<img width="768" alt="image" src="https://user-images.githubusercontent.com/76981528/177897492-01bbd274-6fe5-46cf-a104-b7657411b625.png">
3.组件的使用
<img width="868" alt="image" src="https://user-images.githubusercontent.com/76981528/177897696-e9e12ab3-df74-46bc-aee5-1f93878d8cf0.png">

**Comment by wwb-xigua** [comment]
> 可以把你的项目打个 zip 发到这里，不然没有办法排查



> 你的截图没有看出问题。可以把你的项目打个 zip 发到这里，不然没有办法排查

项目超过25m
无法使用评论提交

**Comment by IronKinoko** [comment]
可以将代码提交到一个新仓库，方便我们 clone

**Comment by IronKinoko** [comment]
请提交到github。。。。你这链接还需要登录验证

**Comment by wwb-xigua** [comment]
> 请提交到github。。。。你这链接还需要登录验证

https://github.com/wwb-xigua/--bug.git

**Comment by IronKinoko** [comment]
你 `webpack.prod.js` 文件里的配置没有修改

**Comment by wwb-xigua** [comment]
好的，但是仅仅引用了空组件就会报错
<img width="570" alt="image" src="https://user-images.githubusercontent.com/76981528/177902570-8e062611-3dcd-4d7b-ac1a-c17322b1dd63.png">

![image](https://user-images.githubusercontent.com/76981528/177902658-2dc5af50-4432-4323-a82f-bc8ae8d1ae72.png)

**Comment by bearguo** [comment]
> 好的，但是仅仅引用了空组件就会报错 <img alt="image" width="570" src="https://user-images.githubusercontent.com/76981528/177902570-8e062611-3dcd-4d7b-ac1a-c17322b1dd63.png">
> 
> ![image](https://user-images.githubusercontent.com/76981528/177902658-2dc5af50-4432-4323-a82f-bc8ae8d1ae72.png)

tabs组件会出现这个问题，我也复现了

**Comment by IronKinoko** [comment]
@bearguo 提供一下最小复现代码

**Comment by awmleer** [comment]
@wwb-xigua 你的问题看起来 @IronKinoko 已经在[这里](https://github.com/ant-design/ant-design-mobile/issues/5452#issuecomment-1178449337)回复了

@bearguo 如果你还遇到了类似的问题，可以考虑单独再提个 issue，并且附上复现 demo
