### ISSUE TITLE
使用Chrome 在SearchBar內輸入繁體中文錯誤

### ISSUE THREAD

**Issue by jeffnian88** [ant-design/ant-design-mobile#5453]
### Version of antd-mobile

5

### Operating system and its version

Others

### Browser and its version

chrome 105.0.5148.2 (正式版本) dev (x86_64)

### Sandbox to reproduce

https://mobile.ant.design/zh/components/search-bar

### What happened?

使用SearchBar的Demo出現重複繁體中文兩遍
<img width="349" alt="截圖 2022-07-07 下午8 36 44" src="https://user-images.githubusercontent.com/11887909/177774930-9bdb361d-03c6-4a2a-948d-a30fc91f94b1.png">

**Comment by miracles1919** [comment]
我试了正常的诶， 要么再录个屏？

**Comment by jeffnian88** [comment]
Uploading 螢幕錄製 2022-07-07 下午11.25.04.mov…

**Comment by jeffnian88** [comment]
Firefox正常

https://user-images.githubusercontent.com/11887909/177812485-a1aa1708-797f-498a-8bcb-363772df6931.mov

**Comment by jeffnian88** [comment]
https://user-images.githubusercontent.com/11887909/177812722-cdcf0c7d-1a09-43ba-a50d-4da9155142ab.mov

**Comment by awmleer** [comment]
要不在 codesandbox 上写个 demo，试试原生的 input 会不会也有这个问题，因为 antd-mobile 并没有对 Input 输入逻辑这里做特殊的处理，理论上不应该会有这种问题，所以可以和原生 input 对照实验一下

**Comment by jeffnian88** [comment]
https://www.w3school.com.cn/tiy/t.asp?f=eg_html_form_submit
原生input似乎沒問題，我用chrome debug看看

**Comment by miracles1919** [comment]
确实有这个问题..  使用拼音，然后回车也能复现

<img width="362" alt="image" src="https://user-images.githubusercontent.com/22469543/178100068-3d5b6e8c-c1cf-46c4-a936-987673d3b859.png">

<img width="342" alt="image" src="https://user-images.githubusercontent.com/22469543/178100064-aefc1525-74e1-48e7-a200-b494a0cdbcd4.png">

@jeffnian88 有兴趣来个 PR 嘛
