### ISSUE TITLE
官方的Grid例子跑不起来

### ISSUE THREAD

**Issue by ssjjnn** [ant-design/ant-design-mobile#546]
#### 本地环境

antd-mobile 版本：0.9.8
操作系统及其版本：iOS
浏览器及其版本：chrome 版本 54.0.2840.71 (64-bit)

官方的Grid例子跑不起来,也是因为没有对应的RN版本么？
![image](https://cloud.githubusercontent.com/assets/22025844/20384671/a3fa7828-acef-11e6-98ec-c0f675a4eb1c.png)
![image](https://cloud.githubusercontent.com/assets/22025844/20384685/adc24caa-acef-11e6-8b42-675b6640658e.png)

**Comment by warmhug** [comment]
`import Grid from 'antd-mobile/lib/grid/index.web.js'`

请仔细查看文档
