### ISSUE TITLE
时间日期选择器

### ISSUE THREAD

**Issue by zedream** [ant-design/ant-design-mobile#5463]
### What is this feature about?

希望能增加一个时间日期的选择器

**Comment by GOWxx** [comment]
“时间日期的选择器” 是指什么？不能清楚的理解你的需求。
有什么例子可以参考吗？

**Comment by zedream** [comment]
> > 希望能增加一个时间日期的选择器
> 
> “时间日期的选择器” 是指什么？不能清楚的理解你的需求。
> 
> 有什么例子可以参考吗？

好像不需要  找到一个叫 PickerView 的组件可以实现选择时间
类似下图这样的效果
![image](https://user-images.githubusercontent.com/45782249/178455360-eb650531-1f19-4a1f-8883-30659e1edac9.png)

**Comment by GOWxx** [comment]
> 好像不需要 找到一个叫 PickerView 的组件可以实现选择时间 类似下图这样的效果

属性 | 说明 | 类型 | 默认值
-- | -- | -- | --
`renderLabel` | 自定义渲染每列展示的内容。其中 `type` 参数为 `precision` 中的任意值，`data` 参数为默认渲染的数字 | `(type: string, data: number) => ReactNode` | -



[参考文档](https://mobile.ant.design/zh/components/picker#%E5%B1%9E%E6%80%A7-2)，页面内也包括使用demo

<hr>

如果能够实现需求可以反馈下，关闭 issues.  :heart:

**Comment by zedream** [comment]
closed
