### ISSUE TITLE
Rate 评分组件支持手指滑动调整值

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#5469]
### Version of antd-mobile

5.18.0

### What is this feature about?

现在只能通过点击来改变选中的星星，可以加上拖动手势，手指在 Rate 上左右滑动时，选中的星星会跟随手指的位置而变化，这样在移动端上体验会好很多

**Comment by miracles1919** [comment]
与组件无关... 单纯分享下之前用  input type="range" 实现过的 Rate，超级丝滑

https://codepen.io/miracles1919/pen/BaRJdwL
