### ISSUE TITLE
Toast 在Modal中使用 被覆盖

### ISSUE THREAD

**Issue by xiaoyangzi** [ant-design/ant-design-mobile#547]
#### 本地环境

- antd-mobile 版本：0.9.6
- 操作系统及其版本：OSX 10.10.5 (14F2009)
- 浏览器及其版本：IOS 9.2

#### 你做了什么？
在弹框Modal（RN自带组件）中使用Toast

#### 你期待的结果是：
Toast出现在Modal之上

#### 实际上的结果：
Toast出现在Modal之下，被覆盖。

**Comment by silentcloud** [comment]
@xiaoyangzi RN 没有目前没有类似 document.body.appendChild   的东西，所以 Toast 组件用了 hack 的方式，以便能直接通过 api 的形式 `Toast.xxx()` 来使用 Toast，但是 RN 的 Modal 层级太高，hack 添加的层没办法在 Modal 之上，稍后我会把  Toast 组件里 `ToastContainer` 抽出单个文件，RN Modal 里使用该 Component 来实现，类似如下：

```
import { Modal } from 'react-native';
import ToastContainer from 'antd-mobile/lib/toast/ToastContainer'
<Modal>
    {
        this.state.show ? (
            <ToastContainer 
                content="测试。。。。" 
                duration={100}
                type='success'
                onAnimationEnd={() => {
                   this.setState({
                       show: false,
                   });
                }}
            /> 
        ) : null }
<Modal>

```
