### ISSUE TITLE
renderImperatively 中的 afterClose 不会被调用

### ISSUE THREAD

**Issue by miusuncle** [ant-design/ant-design-mobile#5471]
### Version of antd-mobile

5.18.0

### What happened?

```tsx
useEffect(() => {
  if (!closedRef.current) {
    setVisible(true)
  } else {
    afterClose()
  }
}, [])
```

`renderImperatively` 上述代码，从逻辑上看它只会调用一次，`afterClose` 分支始终不会被调用。

**Comment by zqran** [comment]
使用 `renderImperatively` 指令式打开对话框，关闭时，组件总是销毁的

关闭对话框时，修改了 `closedRef` 的值，但关闭后改该组件就销毁了，再次打开对话框时，又是一个全新的组件，全新的 `closedRef`。因此，感觉此处的 `closedRef` 可以不用~

**Comment by awmleer** [comment]
#5475
