### ISSUE TITLE
Popover气泡设置深色背景时会有白色细线

### ISSUE THREAD

**Issue by LetTTGACO** [ant-design/ant-design-mobile#5487]
### Version of antd-mobile

5.18.0

### Operating system and its version

iOS, Android

### Browser and its version

PC Google Chrome 103.0.5060.114 、IOS Safari 16.0、安卓

### What happened?

![image](https://user-images.githubusercontent.com/37357188/179929516-9d51d24a-6b3f-46d4-a0e5-4e8da3927b68.png)
这里会有一条细小的白线，气泡的高度根据文字自适应

**Comment by miracles1919** [comment]
#4773 之前有过讨论

**Comment by LetTTGACO** [comment]
好的了解了
