### ISSUE TITLE
React 15.4.x下报红屏错误: Can't find variable:process

### ISSUE THREAD

**Issue by loopArray** [ant-design/ant-design-mobile#549]
#### 本地环境

- antd-mobile 版本：0.9.8
- 操作系统及其版本：Windows 7
- 浏览器及其版本：Chrome 54
- Node及其版本：4.4
- NPM及其版本：3.10.8
- React及其版本："react": "^15.4.x", "react-dom": "^15.4.x","react-native": "^0.37.0",

#### 你期待的结果是：

React Native 15.4 版本能正常显示

#### 实际上的结果：
报错，无法走的通。
按照MobileDemo能跑的通，自己用react-native init AwesomeProject了一个项目，运行并报错，出错截图:
![screenshot_2016-11-18-14-41-42](https://cloud.githubusercontent.com/assets/7822744/20422072/0501bd76-ada3-11e6-8892-b44a180bd401.png)

后来对比package.json文件尽量保持一致的时候是成功的。逐个升级包的版本最后发现只需要减低react的版本就行了。其他nodejs版本和操作系统下为测试是否有同样的问题。

**Comment by silentcloud** [comment]
@loopArray react-native 0.37 官方依赖为 15.3 的 react，https://github.com/facebook/react-native/blob/0.37-stable/package.json#L134
