### ISSUE TITLE
SwipeAction 滑动问题

### ISSUE THREAD

**Issue by wangjiaxu666** [ant-design/ant-design-mobile#5490]
### Version of antd-mobile

5.19.0

### Description

当第一次滑动后关闭，第二次轻轻划一下，直接弹出

https://user-images.githubusercontent.com/33649392/180118849-3a17870e-3d59-4835-b52e-aa2cee06d452.mp4

**Comment by awmleer** [comment]
复现出来了

1. 先滑出来 SwipeAction
2. 点击删除按钮，SwipeAction 自动关闭了（符合预期）
3. 再次轻轻滑动，发现 SwipeAction 没有动画效果，直接变成了完全展开状态（不符合预期）

**Comment by zqran** [comment]
这个问题可以解决了，但是，我又发现了一个新问题，以下步骤可以复现：

1. 右滑列表项 C
2. 点击列表项 B，关闭列表项 C 的动画
3. 再次右滑列表项 C，发现列表项B也跟着滑动（不符合预期）

**Comment by awmleer** [comment]
`from: [0, 0]` 写死肯定是不行的～

我今天下午排查了另一个 Swiper 的问题，感觉和这个非常相似，我来试着改下

**Comment by zqran** [comment]
哦~ 对哈，写成 `[0, 0]` 就导致其他手势情况，出问题了

**Comment by awmleer** [comment]
嗯嗯，我这样解决了 64172e7b1

排查了一下午，Swiper 也是类似的问题和类似的解法 be9011675

附一下 Swiper 的复现 demo：
https://codesandbox.io/s/strange-bogdan-v3x35g

**Comment by awmleer** [comment]
那这个 issue 和那个 PR 我都关闭了～

**Comment by awmleer** [comment]
刚刚的 commit 有点问题，再 force push 了一下，是这个 commit： f58011004
