### ISSUE TITLE
[RFC]使用IntersectionObserver重构InfiniteScroll组件

### ISSUE THREAD

**Issue by LadyChatterleyLover** [ant-design/ant-design-mobile#5498]
### Version of antd-mobile

5.19.0

### What is this feature about?

目前InfiniteScroll组件是监听scroll事件来做无限滚动，触发频率太高，消耗性能太大，可以使用IntersectionObserver来优化，降低性能消耗，如果认可这个方案的话，我可以提一个pr。

**Comment by ONLY-yours** [comment]
看起来兼容性还行 
![image](https://user-images.githubusercontent.com/52664827/180426230-3862e24d-812f-4bfe-9c5c-7f0906c392ff.png)

**Comment by LadyChatterleyLover** [comment]
我提了一个pr，重构了以下

**Comment by miracles1919** [comment]
兼容性不行的 

<img width="912" alt="image" src="https://user-images.githubusercontent.com/22469543/180590476-bf9c8567-470f-42bc-9379-8d1fe7cd6568.png">

**Comment by miracles1919** [comment]
> 目前InfiniteScroll组件是监听scroll事件来做无限滚动，触发频率太高，消耗性能太大

用了节流 `useThrottleFn`，性能问题应该还好

**Comment by LadyChatterleyLover** [comment]
@miracles1919 虽然节流，还是会不停的触发滚动事件，不过兼容性也是个问题

**Comment by awmleer** [comment]
兼容性不行的，等过两年我们不需要支持 iOS 11 了才能用 IntersectionObserver

至于你说的性能问题，有具体的可以验证的 demo 不？理论上现在性能影响应该是完全可控的 🤔
