### ISSUE TITLE
Ellipsis组件 文本省略内容如果是ascii字符不会自动省略

### ISSUE THREAD

**Issue by xhh0223** [ant-design/ant-design-mobile#5499]
### Version of antd-mobile

v5.5.0

### Browser and its version

Edge 103.0.1264.62

### What happened?

文本内容是全是英文字符时，不被省略。中文字符就会被省略。
希望都被省略

**Comment by xhh0223** [comment]
```html
<div>
        <Ellipsis content={'a'.repeat(1000)} rows={4}></Ellipsis>
      </div>
      <div>
        <Ellipsis content={'你'.repeat(1000)} rows={4}></Ellipsis>
</div>
```

**Comment by GOWxx** [comment]
写了个 [demo](https://codesandbox.io/s/ancient-rgb-2ggfgi?file=/src/App.tsx)

这个可以通过给 `Ellipsis` 加 css样式 `word-break: break-all` 来正确的省略

有关 `word-break` 的文档可以阅读：
https://developer.mozilla.org/zh-CN/docs/Web/CSS/word-break

**Comment by awmleer** [comment]
我感觉默认加 `word-break: break-all` 样式并不合适……举个例子：

默认（`break-word`）：

![image](https://user-images.githubusercontent.com/16526078/180679466-5e98989d-9ce1-4166-824b-609221d21549.png)

强制 `break-all`：

![image](https://user-images.githubusercontent.com/16526078/180679509-c7122d3c-579b-4f4b-8daa-a237a81de25d.png)

会发现一个英文单词会被从中间直接截断，非常影响可阅读性

这个 issue 提到的这种特殊情况下，还是建议用户自己在 Ellipsis 外层的元素上加 `word-break: break-all`

**Comment by GOWxx** [comment]
> 我感觉默认加 `word-break: break-all` 样式并不合适……

是的，这里默认加一个属性也会遇到场景不符合，到时候还是用户额外去写样式

**Comment by awmleer** [comment]
嗯嗯 issue 我关闭了
