### ISSUE TITLE
官网进不去

### ISSUE THREAD

**Issue by 17671881483** [ant-design/ant-design-mobile#5508]
### Version of antd-mobile

5.7.2

### Operating system and its version

iOS

### Browser and its version

google

### Sandbox to reproduce

官网进不去

### What happened?

官网进不去

### Relevant log output

```shell
官网进不去
```

**Comment by yaogengzhu** [comment]
啥环境进不去？ 这边可以正常访问呢！

https://mobile.ant.design/zh

**Comment by awmleer** [comment]
网络不好的话，可以访问国内镜像站点：
http://ant-design-mobile.antgroup.com/zh
