### ISSUE TITLE
npm包中含有const、箭头函数等 es6+ 语法

### ISSUE THREAD

**Issue by luckymore** [ant-design/ant-design-mobile#5509]
### Version of antd-mobile

5.19.0

### Operating system and its version

iOS

### What happened?

![image](https://user-images.githubusercontent.com/5390013/180965955-04d6a966-b3c6-429c-894d-346fe970495b.png)

**Comment by awmleer** [comment]
预期行为，关于兼容性，请读文档上“指南-快速上手-兼容性”部分
