### ISSUE TITLE
1.0 Feature & Changelog

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#551]
https://github.com/ant-design/ant-design-mobile/milestone/3

## New Feature
- Icon 从 iconfont 转为使用 svg 图片 #156
- Button 新增`across`API，支持通栏按钮
- Progress 组件新增`appearTransition` API，支持初始显示的动画效果
- Checkbox / Radio 组件支持 children #499 
- NoticeBar 支持 marquee；Steps 支持横向图标
- TabBar web icon 属性新增 React.Node 支持（可以使用 Icon 或者 background）
- Toast 新增 duration = 0 效果（不会自动消失）
- 各组件 RN 版本加入`styles`属性，支持完全自定义组件细节样式 #560
- 增加 Icon 组件 RN 版本，接入指南见： https://github.com/ant-design/ant-design-mobile/blob/master/components/icon/index.md#如何使用-rn
- 新增 [LocaleProvider](https://mobile.ant.design/components/locale-provider)，内置中英语言包（默认中文)。且所有组件可以用 `props.locale` 覆盖全局 `LocaleProvider` 配置
- `Tabs`超过5个自动分页，新增 `props.hammerOptions ` 可配置手势变量, 参考 [API文档](https://mobile.ant.design/components/tabs)
- `TabBar` 新增 `props.dot` 支持 dot 类型的 Badge
- Modal alert&prompt onPress 支持 promise；
- RN Flex 支持更多 touchableWithOutFeedback props；

## Break Change
- NoticeBar type 变为 icon ，支持完全的自定义内容
- Popover iconName 变为 icon ；分割线的 css 设置从 border 底边线修改为顶边线
- 修改部分 css 变量名和变量值、如：zindex 等
- RN List 去除 last 属性
- `DatePicker`, `Pagination` 不再接受`okText`, `dismissText`属性，`DatePicker`的`locale`属性结构变化，参见 [升级文档](https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/upgrade-notes.md#其他常用组件更新注意事项)
- Web `Slider` 拆分成 `Slider`, `Range`, `createTooltip`, 使用方式参见 [Slider文档](https://mobile.ant.design/components/slider), [Range文档](https://mobile.ant.design/components/range)
- Toast 更改为 single instance，新显示的 toast 会覆盖老的；同时增加 mask 特性；
- Modal & Switch 增加 android 平台独立 UI；

## Improve & Bugfix
- 各组件核心实现、样式、demo 等全面优化
- 各输入类组件受控与非受控状态问题修复
- RN Carousel 支持根据子视图高度自适应，去除 height，width 设置
- 修复部分组件(多为依赖 List)的多余边线等细节问题
- 网站重新设计、更加轻盈简洁；优化了网站资源大小、加载速度更快
- 修复 RN `CheckBox` 受控模式下的bug https://github.com/ant-design/ant-design-mobile/issues/784
- RN android tabbar 添加 iconStyle 支持；
- Modal，Toast，ActionSheet 从 api中 拆分出 component 形式；

**Comment by pannz** [comment]
一些控件（RN）不支持自定义样式hin蛋疼，想着快速用antd-mobile出活，结果还是得自己重写，希望1.0版本能够给各个组件不支持style props添加上style

**Comment by silentcloud** [comment]
@pannz 进行中

**Comment by warmhug** [comment]
@silentcloud 
NoticeBar 增加 `marqueeProps` api，并增加 fps 或 timeout 控制， 使用示例
```js
<NoticeBar marqueeProps={{
  loop: false,
  leading: 1000,
  trailing: 1000,
  fps/timeout: 30
}}>long long text.....</NoticeBar>
```

**Comment by yiminghe** [comment]
需要完成的放到 next milestone，发布前检查

**Comment by ninjai001** [comment]
@pannz 有些组件样式太多，根本没法全部style

**Comment by afc163** [comment]
icon 技术方案升级后涉及的 webpack.config 的相关变化（svg-sprite-loader ），要体现到文档里。

**Comment by warmhug** [comment]
RN Icon 是否也支持下？现在自己切 2x 3x png 图片不太方便。 @silentcloud

**Comment by silentcloud** [comment]
@warmhug RN Icon 没办法做纯 UI 组件，需要 native 端支持自定义字体的，能支持的话，最初都搞了

**Comment by afc163** [comment]
搞一个详细的升级指南。

**Comment by silentcloud** [comment]
RN Icon 我也做了支持，接入文档我也写好了 https://github.com/ant-design/ant-design-mobile/blob/master/components/icon/index.md#如何使用-rn

**Comment by paranoidjk** [comment]
# 整理中....
## Feature
- 新增 [LocaleProvider](https://mobile.ant.design/components/locale-provider)，内置中英语言包（默认中文)。且所有组件可以用 `props.locale` 覆盖全局 `LocaleProvider` 配置

## Break Change
- `DatePicker`, `Pagination` 不再接受`okText`, `dismissText`属性，`DatePicker`的`locale`属性结构变化，参见 [升级文档](https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/upgrade-notes.md#其他常用组件更新注意事项)

**Comment by silentcloud** [comment]
之前已经写过一些，遗漏的我直接在上面补充编辑了
