### ISSUE TITLE
希望form.item支持validaFirst的声明，现在可用，但类型提示有问题，同理望支持掉getValueFromEvent属性的声明

### ISSUE THREAD

**Issue by qs970623** [ant-design/ant-design-mobile#5511]
### Version of antd-mobile

5.19.0

### Description

![image](https://user-images.githubusercontent.com/44828251/181014398-81e999f2-7cf4-4e35-a527-2de2696d041d.png)
![image](https://user-images.githubusercontent.com/44828251/181014554-5af10710-6e04-491f-a477-ff1387c0ebf1.png)

**Comment by awmleer** [comment]
`getValueFromEvent` 目前不打算支持，比较推荐自己封装一层组件，举个例子：

FooInput 的 onChange 参数是个 event 对象而不是 string，那么可以封装一层 FooInputField 组件

```jsx
const FooInputField = (props) => {
  return (
    <FooInput {...props} onChange={(e) => props.onChange(e.target.value)} />
  );
};
```

然后就可以在 Form 中正常使用了

```jsx
<Form.Item>
  <FooInputField />
</Form.Item>
```

**Comment by IronKinoko** [comment]
`getValueFromEvent` 为什么不支持？代码里也没看到特殊处理，所有剩余的属性 `...fieldProps` 都传递到了 `Field` 组件上

```tsx
<Field
      {...fieldProps}
     // ...
/>
```
其实所有剩余的 `Field` 属性都能生效，只是声明类型的时候没有写进来

```ts
export type FormItemProps = Pick<
  RcFieldProps,
  | 'dependencies'
  | 'valuePropName'
  | 'name'
  | 'rules'
  | 'messageVariables'
  | 'trigger'
  | 'validateTrigger'
  | 'shouldUpdate'
  | 'initialValue'
> & // ...
```

也许应该考虑使用 `Omit` 而不是 `Picker`

**Comment by awmleer** [comment]
`{...fieldProps}` 这个的确不太合理，应该只传递 ts 类型定义里允许的属性，而 `getValueFromEvent` 之所以不打算支持，主要是两方面的考虑：

1. 有其他方法（而且并不麻烦）可以解决这个问题（上面回复里发的那个），`getValueFromEvent` 并不是非支持不可
2. `getValueFromEvent` 对 ts 很不友好，做不了 ts 校验

**Comment by IronKinoko** [comment]
如果从使用者角度来看，getValueFromEvent 参数类型可以自己指定

如果从组件开发者的角度来看这些属性其实可以支持的，对组件也没有影响，用户的可选择性也多了。类型校验取舍交给用户不也挺好的吗？

**Comment by awmleer** [comment]
嗯嗯那加上也行
