### ISSUE TITLE
Picker not update label

### ISSUE THREAD

**Issue by UtopiaEH** [ant-design/ant-design-mobile#5512]
### Version of antd-mobile

5.19.0

### Operating system and its version

Others

### Browser and its version

Chrome: latest

### What happened?

Then select something from picker the component got updated data but picker not update label using renderLabel also after second select the value in renderLabel apply prev state :

For example i set a bg for selected value  the default value show bg correct at the first time after first pick do not update bg to the new value after second pick bg updated for prev selected value, sorry for grammar use google translate 😅

**Comment by awmleer** [comment]
Need a reproduce demo before we can investigate into this issue. You can write one here: https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

**Comment by UtopiaEH** [comment]
> Need a reproduce demo before we can investigate into this issue. You can write one here: https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx

https://codesandbox.io/embed/infallible-sun-f0bje2?fontsize=14&hidenavigation=1&theme=dark

**Comment by zqran** [comment]
Hi, @UtopiaEH 

This is because the `Picker` component will call `renderLabel` first and then `onSelect`. Because `renderLabel` executes first, when you get the state in `renderLabel`, you get the last state.

We can expose the value for `renderLabel` prop to get the current state. @awmleer

**Comment by awmleer** [comment]
`renderLabel` should be a **pure** function, not depending on outer states and not causing side effects. You can use the `data-selected` attribute to add some custom styles. See this [demo](https://codesandbox.io/s/bitter-https-tpus7y?file=/src/styles.css).
