### ISSUE TITLE
Form表单中Picker默认值不生效

### ISSUE THREAD

**Issue by lemonig** [ant-design/ant-design-mobile#5518]
### Version of antd-mobile

5.16.1

### Operating system and its version

Others

### Browser and its version

chrome 103.0.5060.134

### Sandbox to reproduce

https://codesandbox.io/s/hungry-pike-qut5x4?file=/src/App.tsx

### What happened?

在表单初始化时给表单项 用form.setFieldsValue方法给Form中的Picker 设置了默认值，页面报错。
期望能正常设置表单默认值

**Comment by yangdepp** [comment]
改成数组
```tsx
  useEffect(() => {
    form.setFieldsValue({
      id: ["1"]
    });
  }, []);
``

**Comment by lemonig** [comment]
感谢。知道了。
