### ISSUE TITLE
Drawer组件position位置问题

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#552]
#### 本地环境

- antd-mobile 版本：0.9.8
- 操作系统及其版本：mac
- 浏览器及其版本：chrome，iPhone qq内置浏览器

#### 你做了什么？

修改Drawer组件的position为’right‘

#### 你期待的结果是：
手机上或电脑上手势从右往左滑动不会显示Drawer组件

#### 实际上的结果：
当position为‘left’时手势从左往右滑动不会显示Drawer组件
当position为‘right’时手势从右往左滑动**显示**Drawer组件

**Comment by warmhug** [comment]
Drawer 建议不要用手势，支持的不太好，而且和系统手势会有冲突

**Comment by liubin1023** [comment]
@warmhug  已经禁用手势了，应该是系统手势，而且目前只发现position为‘right’时会触发，默认的‘left’就不会

**Comment by warmhug** [comment]
Drawer 使用按钮触发

**Comment by motorguo** [comment]
@warmhug 关于Drawer 提个小小的建议，目前这两种展示方式太局限了，不够活。
常见 Drawer 基本都是生成在 hook 外面的，**弹出在最顶层**，不知如何在你们看来。
如果不希望盖住 `Navbar` 可以加个 `top`.

现在我 `Drawer`  里面不放内容，把它弄到最顶层，虽然能实现...

[其实是想要这种效果](https://react-md.mlaursen.com/components/drawers)

**Comment by warmhug** [comment]
@motorguo 感谢建议。会考虑增加个配置项，把 drawer 弹出层放到 dom 最顶层、像 modal 一样。不过我们有 docked 模式、是要占相应位置内容宽度的、这个模式下还是展示到相应放置的 dom 位置比较好。

**Comment by gebilaoman** [comment]
最后怎么解决的呢，关于系统手势问题

**Comment by qianjujun** [comment]
.my-drawer .am-drawer-sidebar {
    background-color: #fff;
    overflow: hidden;
    -webkit-overflow-scrolling: touch;
  }
  .my-drawer .am-drawer-sidebar .am-list {
    width: 580px;
    padding: 0;
  }

overflow  auto->hidden 可以解决此问题
