### ISSUE TITLE
下拉刷新组件在生产模式(打包后)不工作

### ISSUE THREAD

**Issue by YernarT** [ant-design/ant-design-mobile#5525]
### Version of antd-mobile

5.20.0

### Operating system and its version

Android

### Browser and its version

Google Chrome 103

### Sandbox to reproduce

https://codesandbox.io/s/pull-to-refresh-codesanbox-h7fn7d?file=/src/App.tsx

### What happened?

下拉刷新(PullToRefresh)组件在生产模式(打包后)不工作。
当我执行 npm run build 之后, 再运行 dist (打包后的目录), 下拉刷新就不起作用了。
在谷歌devTools里也不行, 安卓真机上也不行。
就是往下拉是拉不动了, 但那个节点还在, 就是 height 属性不变化, 然后有没有触发组件内的监听事件我也不知道如何去检查。

这是我部署的页面, 需要在小屏幕下打开, https://orm-community.web.app/
首页(话题页), 的列表是PullToRefresh组件包裹的, 在本地开发时没有任何问题, 但是打包后发现就不工作了。

### 打包相关

目前项目用的是 React和TypeScript写的, 具体依赖如下

- "typescript": "^4.6.2",
- "react": "^17.0.2",
- "react-dom": "^17.0.2",

其次我使用的包管理器是 pnpm 6.28.0
打包用的是 vite, 相关依赖

- "vite": "^2.8.6",
- "@vitejs/plugin-react": "^1.2.0",
- "vite-plugin-imp": "^2.1.8"

和打包相关的 vite配置:
```
plugins: [
	react(),
	vitePluginImp({
		optimize: true,
		libList: [
		{
		  libName: 'antd-mobile',
		  libDirectory: 'es/components',
	 	  style: () => false,
		},
	      ],
          }),
	],

esbuild: {
	logOverride: { 'this-is-undefined-in-esm': 'silent' },
},
```

### Relevant log output

```shell
没有任何报错, 就是开发模式和生产模式效果不一致。生产模式下完全不工作。
```

**Comment by awmleer** [comment]
看起来你使用了手动的按需加载？确认一下[这篇文档](https://mobile.ant.design/zh/guide/import-on-demand)有完整仔细读过么？

**Comment by zqran** [comment]
@YernarT 我按照你的配置试了下，确实会有你说的这个问题。

解决方式：按照 @awmleer 提到这个文档，进行配置即可修复

> 看起来你使用了手动的按需加载？确认一下[这篇文档](https://mobile.ant.design/zh/guide/import-on-demand)有完整仔细读过么？

具体操作：在 `main.tsx` （vite 项目入口文件）中，导入以下内容即可：

```ts
import 'antd-mobile/es/global'
```

**Comment by YernarT** [comment]
十分感谢, 我的问题得到了完美的解决~!
[那篇文档](https://mobile.ant.design/zh/guide/import-on-demand/)我刚开始接触 antd mobile 时, 配置启动文件时读过一次, 可能当时粗心了, 没注意到需要引入 global 文件 ;)
