### ISSUE TITLE
listview连续下拉两次，listview的头部位置变低了

### ISSUE THREAD

**Issue by leonardgithub** [ant-design/ant-design-mobile#553]
本地环境

antd-mobile 版本：├─┬ antd-mobile@0.9.6
操作系统及其版本：Ubuntu 16.04
浏览器及其版本：Chrome Versión 52.0.2743.116 (64-bit)

你做了什么？

引入 antd-mobile的listview

你期待的结果是：
listview连续下拉两次，listview的头部位置回到原来初始的位置

实际上的结果：
listview连续下拉两次，listview的头部位置变低了

		<ListView
			style={{
				// height: util.getListViewHeight(),
				// height: document.body.clientHeight - 80
				height: 540
			}}
			renderSectionHeader={(sectionData, sectionID) => {
				const title = sectionID
				return (
					<p className="timeTeam">{title}
						<Span reactIf={title.indexOf(nowStr)!=-1}>(今天)</Span>
						<Span reactIf={title.indexOf(tomorrowStr)!=-1}>(明天)</Span>
					</p>
				)}
			}
			refreshControl={
				<RefreshControl
					refreshing={$scope.isRefreshing}
					onRefresh={_onRefresh}
				/>
			}
			// scrollRenderAheadDistance={500}
			onChangeVisibleRows={null}
			onEndReachedThreshold={50}
			onEndReached={_fetchMoreData}
			// onScroll={}
			dataSource={_self.dataSource.cloneWithRowsAndSections(map || {}, sectionIDs)}
			renderRow={_renderRow}
			// renderFooter={_renderFooter}
			// initialListSize={10}
			enableEmptySections = {true}
		/>

可重现的在线演示
none

**Comment by warmhug** [comment]
注意样式设置

**Comment by leonardgithub** [comment]
初始化页面的时候是好的，还要怎么设置？多拖动几次第一行数据就被盖住了，还要自己去控制拖动时的高度？FB react-native官方的ListView也不需要类似的高度设置。

**Comment by warmhug** [comment]
没明白你的意思，官方 demo 能复现吗？
