### ISSUE TITLE
ImageUploader 是否能支持用户头像上传与修改

### ISSUE THREAD

**Issue by haiting** [ant-design/ant-design-mobile#5532]
### Version of antd-mobile
v5.20.0
_No response_

### What is this feature about?

遇到问题：目前 ImageUploader 只能上传多张图片，或者是超过指定图片后，添加按钮默认被隐藏，不适合用户头像上传与修改，因为avatar是单张图片

诉求：是否考虑支持用户头像上传与修改，或者当设置了图片数量限制，不要默认隐藏添加按钮，让用户自己定义是否隐藏

**Comment by miracles1919** [comment]
你看下官网 “限制图片数量” 那个例子，`maxCount = 1` 就好了

**Comment by haiting** [comment]
> 你看下官网 “限制图片数量” 那个例子，`maxCount = 1` 就好了

`maxCount = 1` 图片按钮都隐藏了，怎么更改avatar呢？所以我意思是，能不能`showUpload `可以用户自己设定，这样就算图片数量超过`maxCount`，用户操作upload btn

**Comment by miracles1919** [comment]
<img width="104" alt="image" src="https://user-images.githubusercontent.com/22469543/183033618-2a98283d-09d4-41a6-9ec8-c594f75832c0.png">

1. 右上角有个 ❎ 
2. `showUpload` 支持自己设置的

**Comment by haiting** [comment]
> <img alt="image" width="104" src="https://user-images.githubusercontent.com/22469543/183033618-2a98283d-09d4-41a6-9ec8-c594f75832c0.png">
> 
> 1. 右上角有个 ❎
> 2. `showUpload` 支持自己设置的

好，虽然 `showUpload` 可以设置，但是设置“限制图片数量” `maxCount = 1 `时，按钮就会默认被隐藏，这时候用户必须每次都要点击❎后，才能再次显示 `upload btn`，这样感觉挺奇怪的

**Comment by miracles1919** [comment]
目前设计如此

**Comment by awmleer** [comment]
目前的确是要这样操作的，而且大概率交互不会调整了～如果需要实现定制化的交互逻辑的话，可以直接读一下 ImageUploader 的源码，自己实现一个类似的组件，其实很简单的

issue 我关闭掉了
