### ISSUE TITLE
Input组件输入数字时，对应的value还是string类型，与Form.Item的rule校验规则type:'number'有冲突吧？

### ISSUE THREAD

**Issue by 1587315093** [ant-design/ant-design-mobile#5533]
### Version of antd-mobile

"antd-mobile": "^5.20.0"

### Operating system and its version

iOS, Android, Others

value输入的永远是string，无法通过rule校验
![image](https://user-images.githubusercontent.com/77056991/182542351-9b4a9100-0557-4f43-a8cb-7d3df7ade1c3.png)
![image](https://user-images.githubusercontent.com/77056991/182542654-84e6b9d9-42c3-41d4-8eec-bcf104a20051.png)
![image](https://user-images.githubusercontent.com/77056991/182542696-5121ad7d-6556-4456-825e-d347500a674f.png)

**Comment by zqran** [comment]
Form 组件没有做处理，不过，可以这样解决：

```diff
{
  type: 'number',
  message: '请输入正确的车辆当前里程',
+ transform: value => +value // 校验之前，将 string 转化为 number
}
```
