### ISSUE TITLE
关于 ImageViewer 的放大功能

### ISSUE THREAD

**Issue by yuanjiu041** [ant-design/ant-design-mobile#5540]
### What is this feature about?

ImageViewer 放大之后，关闭再打开，图片还是放大后的样子，不是很合理，是否可以支持一下例如 resetZoomAfterClose 之类的属性，在 afterClose 之后自动将图片的缩放归位。

**Comment by awmleer** [comment]
应该是 bug……关闭之后再打开正常肯定是要归位的
