### ISSUE TITLE
swiper  indicator

### ISSUE THREAD

**Issue by dylanass** [ant-design/ant-design-mobile#5544]
### Description

比如 list 长度为1 ，不显示指示器，> 1 ，显示默认指示器

**Comment by miracles1919** [comment]
我提供两个方案

1. indicator 根据 length 传入不同的值
```jsx
<Swiper indicator={items.length > 1 ? undefined : () => null}>...</Swiper>
```

2. 根据 length 渲染不同的组件
```jsx
{items.length > 1 ? <Swiper>...</Swiper> : <Swiper.Item key={1}>...</Swiper.Item>}
```

**Comment by awmleer** [comment]
@dylanass Swiper 本身不会提供这种能力的，还是要业务里自己去判断（而且其实也不难判断），可以参考 @miracles1919 上面发的方案

**Comment by dylanass** [comment]
第一种,undifined ，会展示默认值吗

**Comment by awmleer** [comment]
噢 `undefined` 会展示默认样式的，这里得改成传 `null`
