### ISSUE TITLE
[SearchBar] iOS11 搜索按钮文本不是搜索

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#5545]
### Version of antd-mobile

latest

### Operating system and its version

iOS

### Browser and its version

iOS11.4

### What happened?

最基础用法
```tsx
<SearchBar />
```

![32964287-0785-4684-9DED-6884904DF143](https://user-images.githubusercontent.com/32838658/183396908-37f034d7-bcc8-4c11-b60e-e1a0263be49e.png)

## 修复方案

```tsx
<form action="#">
  <SearchBar />
</form>
```

![A3F623B0-19DD-4C1E-8974-AD5D03B83A41](https://user-images.githubusercontent.com/32838658/183396927-aac97cb9-dc60-4a88-aebc-21d63386af74.png)

我觉得 SearchBar 需要一个内置的 form 包裹它，而不是用户去提供 form

**Comment by IronKinoko** [comment]
如果增加 form 标签，可能出现 form 嵌套的情况

```tsx
<Form>
   <SearchBar/>
</Form>
``` 

上面这种情况就会控制台报错

**Comment by awmleer** [comment]
诶这个问题是只有 iOS 11 上存在么

**Comment by IronKinoko** [comment]
手头只有 iOS11.4 的模拟器，较老的浏览器应该都会有这种情况吧，网络上搜索相关的内容，也只有 iOS 相关的讨论
https://caniuse.com/?search=enterkeyhint

**Comment by MuxinFeng** [comment]
目前我也只找到这个办法，如果用 `enterkeyhinit` ,只对 iOS13 以后的版本生效
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input/search#incremental

**Comment by awmleer** [comment]
看起来 iOS 13.4 以上就不会出现这个问题了，要不这个问题我们加到 FAQ 里，然后就不修复了？（等待时间⏳慢慢消化）毕竟对用户来说影响也不是特别大
