### ISSUE TITLE
Input clearable无效

### ISSUE THREAD

**Issue by angelporo** [ant-design/ant-design-mobile#5547]
### Version of antd-mobile

5.20.0

### Operating system and its version

iOS, Others

### Browser and its version

google 103.0.5060.134

### Sandbox to reproduce

无

### What happened?

Input 开启 `clearable` 浏览器内打开手机模式无法清楚内容
<img width="636" alt="image" src="https://user-images.githubusercontent.com/16830481/183563087-62cce9de-c172-4b6b-845a-1a20b0e17f2c.png">
不在手机模式下可以正常操作

### Relevant log output

```shell
没有任何报错内容
```

**Comment by guojunhao118** [comment]
解决了？
