### ISSUE TITLE
Input  组件获取焦点报错

### ISSUE THREAD

**Issue by angelporo** [ant-design/ant-design-mobile#5548]
### Version of antd-mobile

5.20.0

### Operating system and its version

Others

### Browser and its version

chrome  104.0.5112.79

### Sandbox to reproduce

无

### What happened?

Input 获取焦点报错，使用了已被启用的api
在手机模式下会有报错，不在手机模式下没有这个warning，导致获取焦点卡顿，点击清楚功能无效

<img width="714" alt="image" src="https://user-images.githubusercontent.com/16830481/183571786-c4bb31fb-74d5-46ac-989d-c315dd7ead5e.png">

**Comment by awmleer** [comment]
看起来不像是 Input 组件导致的，Input 没写过获取 event.path 的逻辑

莫非是你安装的一些 Chrome 插件导致的？

需要提供一个复现 demo
