### ISSUE TITLE
期望Selector组件暴露出grid组件的参数。

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#5549]
### Version of antd-mobile

5.20.0

### What is this feature about?

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/12706830/183592988-d628fa7e-da04-4ed9-bfef-25d7f71f9636.png">
这样写成了style样式，导致我外部无法调整。期望暴露出gird组件的参数出来！

**Comment by MuxinFeng** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/46584765/183628949-4bb3c926-5bd8-420b-b354-c042a3665fb2.png">
我觉得已经算是把`Grid`的参数暴露出来了，这里的`column`就是给`selector`的`column`

**Comment by codedart2018** [comment]
> <img alt="image" width="554" src="https://user-images.githubusercontent.com/46584765/183628949-4bb3c926-5bd8-420b-b354-c042a3665fb2.png">
> 
> 我觉得已经算是把`Grid`的参数暴露出来了，这里的`column`就是给`selector`的`column`

gap写死的，无法修改

**Comment by MuxinFeng** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/46584765/183628949-4bb3c926-5bd8-420b-b354-c042a3665fb2.png">
我觉得已经算是把`Grid`的参数暴露出来了，这里的`column`就是给`selector`的`column`

**Comment by MuxinFeng** [comment]
嗷嗷嗷，对滴，看大佬们咋说了，如果觉得可行的话，我可以提个PR~
