### ISSUE TITLE
antd-mobile v0.9.9 的Popup组件点击遮罩层不会自动关闭

### ISSUE THREAD

**Issue by 16code** [ant-design/ant-design-mobile#555]
#### 本地环境

- antd-mobile 版本：0.9.9
- react 版本: 15.4.0
- 操作系统及其版本：macOS
- 浏览器及其版本：Chrome 54.x

#### 你做了什么？

- antd-mobile 的 Popup 组件 点击遮罩层不能自动关闭

#### 你期待的结果是：

- 使用默认的Popup option 点击遮罩层可以自动关闭

#### 实际上的结果：

- 点击遮罩层不能自动关闭
- 并且 react-dom会报错 
   react-dom.min.js:15 Unable to preventDefault inside passive event listener due to target being     treated as passive. 

- 在很多组件中操作都会报 Unable to preventDefault inside passive event listener due to target being treated as passive. 错误

#### 可重现的在线演示

- 官网给的DEMO效果也是一样

**Comment by silentcloud** [comment]
@16code  react@15.3 试试？

**Comment by 16code** [comment]
@silentcloud 都一样 antd-mobile 0.9.8 不存在这个问题

**Comment by barrysfinalhome** [comment]
我在 windows chrome 54 的上也有这种情况，步进器以及 InputItem 都会提示
![image](https://cloud.githubusercontent.com/assets/3283628/20513808/5cda6caa-b0c3-11e6-9ba2-6af4dd2e01fb.png)

 chrome的模拟器下要 touch 两次 input 才会 focus 到输入框里

在安卓的chrome 54上步进器失效（点＋没反应）

https://www.chromestatus.com/features/5093566007214080

**Comment by warmhug** [comment]
升级到 0.9.10

**Comment by RByers** [comment]
As for the warning from Chrome: sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  There's probably a missing `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), which is necessary to support touch on IE/Edge anyway.
