### ISSUE TITLE
图片查看组件优化

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-mobile#5553]
### Version of antd-mobile

^5.12.6

### What is this feature about?

在使用ImageViewer.Multi 组件时  查看图片放大 图片模糊 。期望能返回高保真图片

**Comment by miracles1919** [comment]
看你之前也提过... 先提供下可复现的 demo 吧 

[codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx)

**Comment by lovesL** [comment]
> 我这个不好提供 因为我这个是传阿里oss的 我们是内网  demo 在外网上传图片都传不了 。。。。

**Comment by lovesL** [comment]
其实 我这个没有很复杂的逻辑  就是传上去 后 拿到oss返回签名后的图片地址 预览显示就这样了....

**Comment by lovesL** [comment]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/27960630/183798399-49fbeaf0-fe1d-46d7-b746-c6c1129cb96d.png">
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/27960630/183798619-6fd2985d-affe-47fb-a1d5-459a0227f166.png">
。。。就这么点代码

**Comment by lovesL** [comment]
https://codesandbox.io/s/awesome-sunset-lziqu2?file=/src/App.tsx&resolutionWidth=320&resolutionHeight=675  我弄了一个 只是不知道 有没有用

**Comment by miracles1919** [comment]
图片过期了

**Comment by lovesL** [comment]
我换了一个

**Comment by awmleer** [comment]
之前有过类似的 issue #4373

**Comment by awmleer** [comment]
图片请求 403 了，放到公开的 OSS 上吧

**Comment by lovesL** [comment]
。。。没有公开OSS的大佬 我们都是内网开发 对安全要求高

**Comment by miracles1919** [comment]
你可以试下原生 img 在移动端的表现

我看你用的是 png，这是由像素点构成的，在 dpr > 1 （例如 Retina）的屏幕上，一个像素可能由多个物理像素来渲染

而这些物理像素只能取到近似值，所以会模糊

**Comment by lovesL** [comment]
![image](https://user-images.githubusercontent.com/27960630/183807737-27df4783-355b-4b35-a326-13d64e5cad07.png)
我kan看组件自带的是用的img呀

**Comment by miracles1919** [comment]
我的意思是，图片模糊这个情况**不一定**是组件带来的，在 dpr > 1 的屏幕上，有些图片就会模糊，理由上面说了。

因为你没有公开的 OSS，所以你可以自己写个 `<img />` 比较一下

**Comment by lovesL** [comment]
明白 多谢大佬  我试试
