### ISSUE TITLE
Picker组件onConfirm回调没给出最新选择的数据

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design-mobile#5560]
### Version of antd-mobile

5.7.2

### What happened?

Picker组件onConfirm回调没给出最新选择的数据，给的是初始的数据。只能在onSelect时去设置选中的数据，然后onConfirm时去拿这个数据。

**Comment by awmleer** [comment]
请在 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx) 或者 [stackblitz](https://stackblitz.com/edit/antd-mobile) 上写一个 demo

**Comment by semdy** [comment]
线上demo未复现

**Comment by kevin82008** [comment]
> 线上demo未复现

碰到了类似的问题，选择的时候，拖动选择第一次拖动不触发onSelect，第二次触发onSelect，第三次不触发，第四次触发，很有规律。代码写法和官网示例写法一模一样，官网就是对的，自己的代码就是不对

**Comment by kevin82008** [comment]
> ### Version of antd-mobile
> 5.7.2
> 
> ### Operating system and its version
> _No response_
> 
> ### Browser and its version
> _No response_
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> Picker组件onConfirm回调没给出最新选择的数据，给的是初始的数据。只能在onSelect时去设置选中的数据，然后onConfirm时去拿这个数据。
> 
> ### Relevant log output
> _No response_

试下升级 react 版本到当前最新版，大概率可以解决问题
我类似问题升级react后可以了
