### ISSUE TITLE
请教一下 怎么修改Grid的item的高度？

### ISSUE THREAD

**Issue by feilongOnMoudu** [ant-design/ant-design-mobile#557]
怎么修改Grid的每个item的高度？
 <Grid style={{height:200}} data={data} columnNum={3} />

这样设置高度没有变化的？

**Comment by warmhug** [comment]
grid 九宫格，代码里默认设置了和宽度一样的高度，适用于常用情形。你可以用 !important 之类覆盖默认样式。 另外如果你个性化要求比较多，建议不使用这个组件，自己实现也是比较简单的。
