### ISSUE TITLE
通过cdn引入读取window['antd-mobile']为空对象

### ISSUE THREAD

**Issue by DaJianWu** [ant-design/ant-design-mobile#5571]
### Version of antd-mobile

5.21.0

### Operating system and its version

Others

### Browser and its version

chrome最新版

### What happened?

通过<script src="https://cdn.jsdelivr.net/npm/antd-mobile@5.21.0/bundle/antd-mobile.compatible.umd.min.js"></script>引入，读取window['antd-mobile']为空对象，期望可以正确读取window['antd-mobile']

**Comment by IronKinoko** [comment]
请使用 `window. antdMobile`

**Comment by DaJianWu** [comment]
> 请使用 `window.antdMobile`

我试了一下，window.antdMobile和window.AntdMobile都读取不到

**Comment by miracles1919** [comment]
目前的 umd 确实有问题

**Comment by DaJianWu** [comment]
> window.antdMobile和window.AntdMobile都读取不到

有解决方法吗？还是说只能把antd-mobile打包到项目里

**Comment by awmleer** [comment]
eeaf90054 已修复，过两天发个版本

**Comment by DaJianWu** [comment]
> [eeaf900](https://github.com/ant-design/ant-design-mobile/commit/eeaf900541f8d96286761d497d88aa1402e39d6d) 已修复，过两天发个版本

请问这个bug现在解决了 我现在试了还是不行呢

**Comment by awmleer** [comment]
@DaJianWu 来个复现 demo

**Comment by DaJianWu** [comment]
> @DaJianWu 来个复现 demo

我这个问题只有ios10的safari中才能复现，就是很正常的使用：

在项目入口通过cdn引入
`  <script src="https://cdn.jsdelivr.net/npm/antd-mobile@5.24.0/bundle/antd-mobile.compatible.umd.min.js"></script>
`

在页面模块中导入
`import { Button } from 'antd-mobile';`

`console.log(window.React, window.AntdMobile, window.AntdMobile?.Button, Button);`
打印结果为只有React有值，后面的都没有值

在其它高版本的ios系统中没有这样的问题，很奇怪。。。

**Comment by DaJianWu** [comment]
> @DaJianWu 来个复现 demo

我试了下不通过构建工具编译打包，直接cdn引入然后使用都有问题

`<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>demo/title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/antd-mobile@5.24.0/bundle/css-vars-patch.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/antd-mobile@5.24.0/bundle/style.min.css">
  <script src="//lib.baomitu.com/react/18.2.0/umd/react.production.min.js"></script>
  <script src="//lib.baomitu.com/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
</head>

<body>
  <div id="app"></div>
  <script src="https://cdn.jsdelivr.net/npm/antd-mobile@5.24.0/bundle/antd-mobile.compatible.umd.min.js"></script>
  <script>
    console.log(window.antdMobile);
  </script>
</body>

</html>
`

在iso10.0.2的safari中会读取不到

**Comment by DaJianWu** [comment]
这个问题有解吗。。。

**Comment by DaJianWu** [comment]
https://stackblitz.com/edit/js-av8kee?file=index.html 这个地址可以在ios10的safari中可以复现

**Comment by awmleer** [comment]
@DaJianWu 浏览器 console 里有报错么

**Comment by DaJianWu** [comment]
pc的浏览器是正常的 ios10中可能在cdn引入的js中就报错了 看不到日志

**Comment by DaJianWu** [comment]
> @DaJianWu 浏览器 console 里有报错么

`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>demo</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/antd-mobile@5.24.0/bundle/css-vars-patch.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/antd-mobile@5.24.0/bundle/style.min.css"
    />
    <script src="https://unpkg.com/vconsole@latest/dist/vconsole.min.js"></script>
    <script>
      var vConsole = new window.VConsole();
    </script>
    <script src="https://lib.baomitu.com/react/18.2.0/umd/react.production.min.js"></script>
    <script src="https://lib.baomitu.com/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
  </head>

  <body>
    <div id="app"></div>
    <script src="https://cdn.jsdelivr.net/npm/antd-mobile@5.24.0/bundle/antd-mobile.compatible.umd.min.js"></script>
    <script>
      console.log('React', window.React);
      console.log('ReactDOM', window.ReactDOM);
      console.log('antdMobile', window.antdMobile);
      document.write(`
      React: ${JSON.stringify(window.React)},
      ReactDOM: ${JSON.stringify(window.ReactDOM)},
      antdMobile: ${JSON.stringify(window.antdMobile)},
    `);
    </script>
  </body>
</html>
`

上面这段代码在ios10中React和ReactDOM可以正常打印出值，antdMobile为一个空对象

**Comment by DaJianWu** [comment]
> @DaJianWu 浏览器 console 里有报错么

https://stackblitz.com/edit/js-av8kee?file=index.html

这里面的代码在ios10中React和ReactDOM可以正常打印出值，antdMobile为一个空对象

**Comment by DaJianWu** [comment]
请问有排查出原因了吗 在安卓版本6和7的手机上也有同样的问题。。

**Comment by DaJianWu** [comment]
请问有排查出原因了吗 在安卓版本6和7的手机上也有同样的问题 影响范围有点大的。。

**Comment by IronKinoko** [comment]
![image](https://user-images.githubusercontent.com/32838658/191710389-448e5bf5-d792-41c4-86a9-c8c5a7dcb87a.png)

**Comment by DaJianWu** [comment]
> ![image](https://user-images.githubusercontent.com/32838658/191710389-448e5bf5-d792-41c4-86a9-c8c5a7dcb87a.png)

你这个是在pc的浏览器里面模拟ios环境复现的吗 我用的是 /antd-mobile@5.24.0/bundle/antd-mobile.compatible.umd.min.js

**Comment by DaJianWu** [comment]
@awmleer 在线急等解决方法。。

**Comment by miracles1919** [comment]
我试了下安卓 7 和 5，都是正常的

<img width="700" alt="image" src="https://user-images.githubusercontent.com/22469543/191919366-0f2768d4-16ce-4d93-8fb9-548a7eb452d5.png">

**Comment by DaJianWu** [comment]
> 我试了下安卓 7 和 5，都是正常的
> 
> <img alt="image" width="700" src="https://user-images.githubusercontent.com/22469543/191919366-0f2768d4-16ce-4d93-8fb9-548a7eb452d5.png">

通过模拟的不太准确 在真机上打开是不行的

**Comment by DaJianWu** [comment]
/antd-mobile@5.24.0/bundle/antd-mobile.compatible.umd.min.js

这个文件能重新构建一下吗 解决下兼容性的问题

**Comment by miracles1919** [comment]
![image](https://user-images.githubusercontent.com/22469543/191924544-dc4236c7-8458-484b-9816-dbd4a70b56ec.png)

是真机

---

而且感觉 stackblitz 加载 umd 有点问题，我在 PC chrome 上**有时候**也会出现 undefined

**Comment by miracles1919** [comment]
> /antd-mobile@5.24.0/bundle/antd-mobile.compatible.umd.min.js
> 
> 这个文件能重新构建一下吗 解决下兼容性的问题

经过 babel 处理过了，兼容性为 Chrome >= 49 iOS >= 9

**Comment by DaJianWu** [comment]
ios10 是不行的 我在好几个手机上都试了

**Comment by DaJianWu** [comment]
读取window.antdMobile是个空对象 又没有任何报错信息 很奇怪

**Comment by miracles1919** [comment]
![image](https://user-images.githubusercontent.com/22469543/191926109-8a7ff768-bd17-46df-8c77-15f7dcd56c8a.png)

> 读取window.antdMobile是个空对象 又没有任何报错信息 很奇怪

我现在用火狐打开就是这样，所以这个应该是 stackblitz 的问题，看起来是没加载完就输出了

**Comment by IronKinoko** [comment]
> ![image](https://user-images.githubusercontent.com/32838658/191710389-448e5bf5-d792-41c4-86a9-c8c5a7dcb87a.png)

vite配置可能有点问题，打包后把 this 转成了 globalThis，导致兼容性出问题了
https://caniuse.com/?search=globalthis

**Comment by DaJianWu** [comment]
> 所以这个应该是 stackblitz 的问题，

我在本地起的服务在手机上访问也是不行的

**Comment by miracles1919** [comment]
@IronKinoko 你用的是没被 babel 处理的 dev umd

他用的是 compatible，用 babel 处理过的

https://github.com/ant-design/ant-design-mobile/blob/master/gulpfile.js#L172-L175

**Comment by IronKinoko** [comment]
一样的，compatible文件里也能找到 globalThis

![image](https://user-images.githubusercontent.com/32838658/191927902-270bbd52-94ca-410b-ab08-969c97a36d92.png)

**Comment by DaJianWu** [comment]
https://dajianwu.github.io/ 这个里面只有一个静态的html文件 在ios10的浏览器上点开就能复现了 @miracles1919

**Comment by IronKinoko** [comment]
![B424BEB7-1077-400D-A51D-6E33AA88C731](https://user-images.githubusercontent.com/32838658/191928861-b72f17ae-637e-4f00-9e7e-f8b9b6770be4.png)

**Comment by DaJianWu** [comment]
你这个是访问我给的那个链接吗 我倒是看不到这个报错日志

**Comment by IronKinoko** [comment]
![image](https://user-images.githubusercontent.com/32838658/191929982-c474fa56-ed82-4df3-9f69-c31f9a66e9d6.png)

**Comment by DaJianWu** [comment]
你这个是ios多少的版本？

**Comment by DaJianWu** [comment]
`  <script>
    this.globalThis || (this.globalThis = this)
  </script>
  <script>
    ! function (t) {
      function e() {
        var e = this || self;
        e.globalThis = e, delete t.prototype._T_
      }
      "object" != typeof globalThis && (this ? e() : (t.defineProperty(t.prototype, "_T_", {
        configurable: !0,
        get: e
      }), _T_))
    }(Object);
  </script>`

在项目入口加上以上代码可暂时解决

**Comment by miracles1919** [comment]
我刚想说.. 你在自己的代码里先兼容一下吧

**Comment by DaJianWu** [comment]
@IronKinoko @miracles1919 目前暂时在自己的项目中兼容了一下globalThis的问题 多谢大佬

**Comment by DaJianWu** [comment]
@awmleer 这个有计划修复吗 影响面有点大的 我能否尝试下来个PR

**Comment by awmleer** [comment]
@DaJianWu 可以来提个 PR～

**Comment by DaJianWu** [comment]
打包报这个错，有遇到过这样的情况吗

![image](https://user-images.githubusercontent.com/55335768/192677136-07c52b2b-020f-40d3-a1a4-bf99eab6d55c.png)

**Comment by miracles1919** [comment]
window 环境确实有这个问题，相关 issue #5628 

---

另外关于 vite 打包生成的 umd 产物，存在以下问题

- 用 babel polyfill 会包含 require，没法直接用
- 官方提供的 @vitejs/plugin-legacy 不支持 library 模式

所以感觉还是用回 webpack 打包 umd

**Comment by awmleer** [comment]
vite 构建是在 https://github.com/ant-design/ant-design-mobile/pull/4955 这个 PR 里引入的

at 一下 @3lang3 求助攻～～

**Comment by 3lang3** [comment]
@awmleer 假期中，回应比较慢哈 抱歉
@DaJianWu 麻烦试下 5.9.4版本的产物看是否可行，现在项目的 `vite` 依赖版本变成了v3，构建产物target官方有[调整](https://vitejs.dev/guide/migration.html#modern-browser-baseline-change)

如果还不行的话，像@miracles1919所说，可能需要调整umd方案

**Comment by DaJianWu** [comment]
@3lang3 我看现在发布的最新版本是`5.24.0`吧

**Comment by 3lang3** [comment]
> @3lang3 我看现在发布的最新版本是`5.24.0`吧

对 你试试我上面说的之前版本看能不能行

**Comment by miracles1919** [comment]
> 麻烦试下 5.9.4版本的产物看是否可行

umd [v5.19.0](https://github.com/ant-design/ant-design-mobile/releases/tag/v5.19.0) 才支持.. 不过我去看了 5.9.4 的 [cjs](https://unpkg.com/browse/antd-mobile@5.9.4/bundle/antd-mobile.cjs.js)，里面也是有 `globalThis` 的，应该是不行的

**Comment by DaJianWu** [comment]
有`globalThis`的话那肯定是不兼容低版本浏览器的了
