### ISSUE TITLE
[RFC] Footer 页脚

### ISSUE THREAD

**Issue by liangchaofei** [ant-design/ant-design-mobile#5574]
### Version of antd-mobile
latest
## 设计
页面中 分 上下两部分，上面是 content，下面是description
如果没有 description，只有 content，则 content 水平垂直居中显示
## 使用方式
```javascript
import Footer from 'ant-design-mobile';

// 文字 不带分割线
<Footer 
  content='@ 2004-2020 Alipay.com All rights reserved'
/>

// 文字 带 水平的 分割线
<Footer 
  hasDivider={true}
  content='没有更多了'
/>

// 品牌 带 水平的 分割线 和 描述
<Footer 
  type='brand'
  hasDivider={true}
  content='蚂蚁财富'
  icon={<Icon />}
  description='过往业绩不预示产品未来表现，市场有风险，投资需谨慎'
/>

// 标签  纯展示
<Footer 
  type='tag'
  content='没找到想要的？搜一下试试'
  description = [{label: '备用金', value: 1}]
/>
// 标签 可跳转
<Footer 
  type='tag'
  content='没找到想要的？搜一下试试'
  description = [{label: '备用金', value: 1}]
  isTagLink={true}
/>
// 链接 页脚
<Footer 
  type='link'
  content=[{label: '链接', value: 'www.alipay.com'}]
  description='@ 2004-2020 Alipay.com All rights reserved'
/>
```
## 属性
| **属性** | **说明** | **类型** | 是否必填 | **默认值** | 备注 |
| --- | --- | --- | --- | --- | --- |
| type | 类型 | 'text' &#124; 'brand' &#124; 'tag' &#124; 'link' | 否 | 'text' |  |
| hasDivider | 是否有分割线 | true &#124; false | 否 | false | 给 content 添加分割线 |
| direction | 分割线水平还是垂直类型 | 'horizontal' &#124; 'vertical' | 否 | 'horizontal' |  |
| content | 页脚内容 | ReactNode  &#124; any[] | 是 | - |  |
| description | 描述 | ReactNode  &#124; any[] | 否 | - |  |
| isTagLink | 标签类型是否可跳转 | true &#124; false | 否 | false |  |
| icon | 品牌的icon | ReactNode  | 否 | - | 需要单独提供一个属性？ |
| onTagClick | 品牌tag点击事件 | (item, index) => void; | 否 | - |  |

### CSS 变量
| **属性** | **说明** | **默认值** |
| --- | --- | --- |
| --background-color | 背景颜色 | var(--adm-color-primary) |
| --description-color | 描述文字的颜色 | #84b9ff |
| --tag-background-color | 标签背景颜色 | 待定 |
| --tag-description-color | 标签描述文字颜色 | 待定 |
| --link-text-color | 链接的文字颜色 | 待定 |

**Comment by awmleer** [comment]
补几张效果图：

![1651890497273-9875ad42-61e0-443c-a9c0-9a50cdb74507](https://user-images.githubusercontent.com/16526078/185070524-5835d022-d388-4f9f-a776-14537cc6e598.png)
![1651890540331-dc4dc640-dd0e-42cf-befc-957f6c659f7d](https://user-images.githubusercontent.com/16526078/185070538-abacfff1-0d20-42e3-9776-5cefbac16ce4.png)
![1653293938751-42354ed0-4ad8-45cc-9920-2e3a860a1065](https://user-images.githubusercontent.com/16526078/185070542-7d1c4a73-cf1e-416b-b08f-50baf760a57c.png)
![1654770471050-d4b78dc8-9146-4db0-94f1-49bee4c60b52](https://user-images.githubusercontent.com/16526078/185070545-b3bb0e24-8846-467c-8943-a2272a6be1f6.png)

**Comment by awmleer** [comment]
应该可以底层复用 [Divider 组件](https://mobile.ant.design/zh/components/divider)

**Comment by awmleer** [comment]
要不分成四部分处理，每个部分分别对应一个属性？

1. label：最顶上的一块，也就是带左右分割线的这部分，而且 label 强制带分割线，不开放配置
2. links：链接部分，这里的链接自带中间的竖直分割线，这个属性的类型是一个数组
3. content：普通的内容部分
4. chips：和 links 类似，也是一个数组

额外的一些解释：

- 上面所有的内容都是文字居中的
- 每个属性都是可以缺省的，不传就不会渲染对应的模块
- 四个部分的相对顺序看起来只能定死了，而且不能重复出现两行 links 或者两行 chips

**Comment by liangchaofei** [comment]
新增 一个 isChipsLink（名称待定） 属性 来区分 chips 是 纯展示 还是 可跳转

**Comment by awmleer** [comment]
> 新增 一个 isChipsLink（名称待定） 属性 来区分 chips 是 纯展示 还是 可跳转

可以考虑叫 `type`，可选值是 `plain` 或者 `link`……？

**Comment by LadyChatterleyLover** [comment]
我来开发这个组件吧

**Comment by awmleer** [comment]
这个组件 @liangchaofei 其实已经在开发了……😅

**Comment by LadyChatterleyLover** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月22日(星期一) 中午11:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-mobile] [RFC] Footer 页脚 (Issue #5574)





 
这个组件 @liangchaofei 其实已经在开发了……😅

**Comment by awmleer** [comment]
不过可以互相借鉴一下代码～我们到时候合并 PR 的时候会把你加到 co-author 里的 ❤️

**Comment by LadyChatterleyLover** [comment]
好的，谢谢哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月22日(星期一) 中午11:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-mobile] [RFC] Footer 页脚 (Issue #5574)





 
不过可以互相借鉴一下代码～我们到时候合并 PR 的时候会把你加到 co-author 里的 ❤️

**Comment by awmleer** [comment]
#5611 #5599
