### ISSUE TITLE
在 roadhog 环境下，打包时报 uglifyjs 错误，原因是 antd-mobile 发布的包不包括 es5 产物

### ISSUE THREAD

**Issue by smithyj** [ant-design/ant-design-mobile#5575]
### Version of antd-mobile

5.21.0

### Operating system and its version

Others

**Comment by smithyj** [comment]
在 roadhog 开启了按需加载，然后打包会报 uglifyjs 错误，因为按需加载的组件没有es5产物

**Comment by awmleer** [comment]
#5577
