### ISSUE TITLE
Roadhog 2.5.0-beta.4 环境下，打包 antd-mobile 5.x 版本项目，出现  var(--radius) * var3.141592653589793 * 2

### ISSUE THREAD

**Issue by smithyj** [ant-design/ant-design-mobile#5577]
### Version of antd-mobile

5.21.0

### What happened?

就是这个组件引起的

```
<ProgressCircle percent={+progress || 0} />
```

![image](https://user-images.githubusercontent.com/9820142/185087969-95326ef1-c584-44ce-a83b-08d471d0ea39.png)

**Comment by awmleer** [comment]
提供一下完整的项目吧

**Comment by smithyj** [comment]
找到问题了，webpack 3 只能使用 `optimize-css-assets-webpack-plugin:3.2.1`，去掉了就没问题
