### ISSUE TITLE
form lable 会出现折行

### ISSUE THREAD

**Issue by dadanliu** [ant-design/ant-design-mobile#5579]
### Version of antd-mobile

5.21.0

### Description

![image](https://user-images.githubusercontent.com/78400194/185292093-5df0aaf9-5fef-4c6e-9ce1-6c83baed76a5.png)
这块

```jsx
 <Form
            layout='horizontal'
            form={form}
            onFinish={onFinish}
            mode='card'
            footer={
                <Button block type='submit' color='primary' size='large'>
                    提交
                </Button>
            }
        >
            <Form.Item label='短信验证码'>
                <Input placeholder='请输入' />
            </Form.Item>
            <Form.Item name='comment' label="客户名称A">
                <TextArea placeholder='请输入内容' rows={5} />
            </Form.Item>
            <Form.Item name='comment' label="客户名称B">
                <TextArea placeholder='请输入内容' rows={5} />
            </Form.Item>
            <Form.Item name='comment' label="客户名称C">
                <TextArea placeholder='请输入内容' rows={5} />
            </Form.Item>
        </Form>
```

想问下这块布局是怎么设计的，我看官方给的demo没有折行；
还有能支持 像后台的form一样的 layout 属性么？

**Comment by miracles1919** [comment]
1、`Form` 和 `Form.Item` 都有 layout 属性的，支持 `'vertical' | 'horizontal'`，你代码里不是也用了么...

2、目前 label 是有这个问题，是不是可以暴露个 CSS 变量 `--label-width`，传给 ListItem(`--prefix-width`) @awmleer

**Comment by awmleer** [comment]
感觉的确可以把 List 的 `--prefix-width` 暴露出来：
![image](https://user-images.githubusercontent.com/16526078/185317330-cd0fb0f1-d93f-4eb2-9a18-83f0d608e34a.png)

**Comment by dadanliu** [comment]
> 1、`Form` 和 `Form.Item` 都有 layout 属性的，支持 `'vertical' | 'horizontal'`，你代码里不是也用了么...
> 
> 2、目前 label 是有这个问题，是不是可以暴露个 CSS 变量 `--label-width`，传给 ListItem(`--prefix-width`) @awmleer

是啊 不是很完美兼容啊，需要暴露一下 @miracles1919 @awmleer

**Comment by DaoxingHuang** [comment]
@dadanliu  临时的解决方案直接在 FormItem 添加 style 属性即可
如：`  <Form.Item label='短信验证码' style={{
              '--prefix-width': '4.8em'
            }}>`

**Comment by DaoxingHuang** [comment]
@awmleer 单独给form item 提供 --label-width 其实有点尴尬...用户在使用过程 可能会导致整个 form 不对齐 ，Form提供 吧，目前难度还比较大，改动也比较大，属性传透好几层

**Comment by awmleer** [comment]
@DaoxingHuang 嗯嗯是的，肯定是暴露在 Form 上体验最好，我先打个 help wanted 的标签

**Comment by awmleer** [comment]
（噢已经有了
