### ISSUE TITLE
Input value 设置为null,无法生效

### ISSUE THREAD

**Issue by NewPrototype** [ant-design/ant-design-mobile#5580]
### Version of antd-mobile

5.2.1

### Operating system and its version

iOS, Android, Others

### Sandbox to reproduce

https://stackblitz.com/edit/react-ts-hwqzao?file=index.tsx

### What happened?

我们使用input 的时候，可能某些逻辑需要把input 的value 清空，但是失效了，如图
![image](https://user-images.githubusercontent.com/24884785/185306466-d3d7b870-c3c0-4fc7-8b41-3cfbd45de888.png)

查看了源码，似乎就是这样设计的，那么上面这样的场景如何解决呢？
![image](https://user-images.githubusercontent.com/24884785/185306495-9314d595-c70b-4467-a6d0-8d1dfc70d19b.png)

**Comment by awmleer** [comment]
用 `setValue('')`

**Comment by NewPrototype** [comment]
但是我们更复杂的场景可能是 ：某个操作去请求了一个接口，接口返回格式为```{ a : null , b : null , c : 100 , d : 'aaa' }```, 前端使用接口返回的数据覆盖表单的值， 使用setValue('')的话就需要我们对后端接口做一层转换

**Comment by awmleer** [comment]
是的，就是应该如此的

**Comment by miracles1919** [comment]
补充一下，在 React 中，value 由非空值转为 `undefined` 和 `null`  时，组件就是非受控的

**Comment by NewPrototype** [comment]
看到v2版中的处理方式，学习到了
