### ISSUE TITLE
Project DEMO

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#56]
update to antd-mobile 1.0 for QA

https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo

**Comment by tungh** [comment]
请问如何一起打包antd和antd-mobile 两个样式文件进css？
这个是https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo

```
// Learn more on how to config.
// - https://github.com/ant-tool/atool-build#配置扩展

const webpack = require('atool-build/lib/webpack');

module.exports = function (webpackConfig) {
  webpackConfig.babel.plugins.push('transform-runtime');
  webpackConfig.babel.plugins.push(['antd', {
    style: 'css',  // if true, use less
    libraryName: 'antd-mobile',
  }]);
  return webpackConfig;
};

```

**Comment by warmhug** [comment]
纯 web 版、纯 webpack + babel + antd-mobile 示例：https://github.com/warmhug/__/tree/master/_react/demo

纯 web 版、最原始的 js 引用示例（仅做参考、不推荐完全搬到线上）：https://github.com/warmhug/__/blob/master/_react/demo/src/antd-mobile-cdn-demo.html

**Comment by afc163** [comment]
https://github.com/smalltide/react-native-antd

**Comment by afc163** [comment]
http://blog.shaochuancs.com/browserify-antd-mobile/

**Comment by itxuye** [comment]
请问RN的完整Demo在哪里啊，过去地址看了mobiledemo里面的RN部分没有具体的代码啊？

**Comment by ninjai001** [comment]
![image](https://cloud.githubusercontent.com/assets/12545571/21292589/1d8b6724-c546-11e6-8adf-34e100d4b6fc.png)
模块找不到，
我先clone ，然后npm install ，然后npm start  就出现这个问题，能不能把demo配置做的好一些

**Comment by warmhug** [comment]
@benjycui 看下 bisheng 是不是不支持 windows ？

**Comment by ninjai001** [comment]
@warmhug 看错误提示是，路径被解析错了？
1：我们想应用部分组件，不想要全家桶
2：我们想修改其中组件的样式，但是我们很难覆盖。所有想要源码进行修改

**Comment by webgzh907247189** [comment]
import { NoticeBar, WhiteSpace } from 'antd-mobile'; 
报错，出现not found antd-mobile in D:\workSpace\wechat\wechatProduct\src\routes

**Comment by bestotem** [comment]
android 的webview加载 kitchen-sink的时候加载不对，android的版本是6.0

![wechatimg2](https://cloud.githubusercontent.com/assets/18134604/23006919/b816c34c-f43f-11e6-9365-9bf8dc88a196.jpeg)

**Comment by warmhug** [comment]
这个 issue 已锁定。不再接受 外部人员 新的问题或评论，如有问题、先搜索其它 issue 里是否有人提出过，没有再新提 issue .
