### ISSUE TITLE
国际化不允许扩展吗。还是有别的方法。

### ISSUE THREAD

**Issue by manzxiao** [ant-design/ant-design-mobile#5600]
### What is this feature about?

```
import { cloneDeep, merge } from 'lodash'

export function mergeLocale<T, P>(base: T, patch: P): T {
  return merge(cloneDeep(base), patch)
}
```

此时返回的类型是T，但是我在写的过程中，如果沿用mergeLocale 方法使用了另外一个变量比如`{demo: 'demo'}`,这时候的`locale.demo` 类型就不存在

返回的类型应该是 T & P ？ 

顺带问下这个 ` default: "Field validation error for ${label}",` 变量是怎么带进去了 =.=

**Comment by awmleer** [comment]
如果想新增一个字段的话，需要改 `src/locales/base.ts`

`default: "Field validation error for ${label}"` 是传给 `rc-field-form` 的，它会对其中的 `${xxx}` 做解析和替换具体值

**Comment by manzxiao** [comment]
用户如果是用ant design mobile 就没办法用这个  merge 去扩展自己的额外国际化json了？

**Comment by awmleer** [comment]
“扩展自己的额外国际化json” 这个是指啥啊……？我感觉可能没太理解你的意思
