### ISSUE TITLE
ImageUploader无法获取是否有上传中的图片

### ISSUE THREAD

**Issue by neilwang543** [ant-design/ant-design-mobile#5608]
### Version of antd-mobile

5.18.0

### Description

需求是ImageUploader存在上传中图片时，表单无法提交。但value: ImageUploadItem[]中没有返回对应的status,我看源码是有task存在的，能否暴露这个task。或者ImageUploader能返回task的ref。
![1661156406469](https://user-images.githubusercontent.com/29112920/185874220-0b29f232-8ad8-455f-8b8d-255a443a7222.jpg)

**Comment by Alubb77** [comment]
+1，我也遇到这个问题了，只能临时解决一下：在触发上传接口时加loading，上传结束后取消loading

**Comment by awmleer** [comment]
get，感觉可以加个类似于 `onUploadQueueChange` 的属性？或者就是给 `ref` 加个字段表示有多个文件正处于上传队列中？（当然也可以都加）

**Comment by zqran** [comment]
@awmleer 两个疑问：

1. `onUploadQueueChange: (isUploading: boolean) => void` 这样的签名吗？
2. `ImageUploader` 组件目前没有 ref，需要暴露吗？

**Comment by awmleer** [comment]
@zqran 

1 的话，感觉是不是只暴露 `isUploading` 信息有点少了，我最开始想的是暴露一下上传队列的长度，或者整个上传队列的完整数组（不知道好不好做，我代码有点记忆模糊了，如果原本组件中就有这个队列 state 的话，应该就好做了）

2 的话，如果有需要，理论上任何一个组件都可以加上 `forwardRef` 的～

**Comment by zqran** [comment]
> 1 的话，感觉是不是只暴露 `isUploading` 信息有点少了，我最开始想的是暴露一下上传队列的长度，或者整个上传队列的完整数组（不知道好不好做，我代码有点记忆模糊了，如果原本组件中就有这个队列 state 的话，应该就好做了）

是可以直接拿到 Task 的，所以，暴露整个上传队列的完整数组数据不难~ 目前，Task 的状态只有两个：`'pending' | 'fail'`，在图片上传成功时，没有对应的状态（默认缺省？），是不是添加一个成功的状态（`'success'`）？

**Comment by awmleer** [comment]
成功的话，就不在这个队列里了

**Comment by zqran** [comment]
按照目前的逻辑，图片上传的过程的 tasks 应该是：先 pengding（没有 url），然后图片上传成功（有 url），然后清空 tasks。会经历这3个步骤，目前，pending 和 图片上传成功时，status 都是 `pending`，是否不太合理？

https://github.com/ant-design/ant-design-mobile/blob/fb39f3990d51bcc3254c8419e77c7683eb569225/src/components/image-uploader/image-uploader.tsx#L139-L174
