### ISSUE TITLE
Modal.alert和Modal.confirm指令式写法不好定制化

### ISSUE THREAD

**Issue by yoghurtxu** [ant-design/ant-design-mobile#5612]
### Version of antd-mobile

5.20.0

### What is this feature about?

Modal.alert
Modal.confirm
的props并不是完全继承Modal的，导致扩展性不如Modal组件，且文档写的较为简单，作为antd-mobile
的老用户表示很少用Modal.alert/Modal.confirm的指令式写法，基本都是这么写`<Modal></Modal>`，然后内容自定义。
后期会改善么

**Comment by miracles1919** [comment]
如果你不习惯用指令式，完全可以继续使用 `<Modal></Modal>`，并不影响啊

> Modal.alert、Modal.confirm 的 props 并不是完全继承 Modal 的

设计如此... 

`alert` `confirm` 本身就表示 Modal 里更细分的场景，肯定是有一些限制的。如果你想要完全继承 Modal props，可以用 `Modal.show`

另外你说的改善是指什么？

**Comment by awmleer** [comment]
issue 先关闭了～ Modal Dialog 之类的很多组件都同时支持指令式和声明式的使用方法，可以根据自己实际场景选择
