### ISSUE TITLE
TextArea（有内容），自动聚焦功能，光标聚焦在开头，而不是内容最后

### ISSUE THREAD

**Issue by qianfengg** [ant-design/ant-design-mobile#5617]
### Version of antd-mobile

5.20.0

### Operating system and its version

Others

### Browser and its version

Chrome 104.0.5112.101

### What happened?

期望自动聚焦在内容的末端

**Comment by qianfengg** [comment]
> 

https://codesandbox.io/s/vigorous-williamson-7dprdp?file=/src/App.tsx

**Comment by miracles1919** [comment]
我试了下，原生的 textarea 就是这样的

**Comment by qianfengg** [comment]
> 

这。。。。我试了下，原生的好像不是这样，才提了issue

**Comment by miracles1919** [comment]
@qianfengg https://codesandbox.io/s/wonderful-black-2hbijz?file=/src/App.tsx  我在你的 demo 上改成了原生的 textarea

**Comment by qianfengg** [comment]
> @qianfengg https://codesandbox.io/s/wonderful-black-2hbijz?file=/src/App.tsx 我在你的 demo 上改成了原生的 textarea

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>textarea</title>
</head>

<body>
    <textarea name="" id="" cols="30" rows="10"></textarea>
    <button>focus</button>
    <script>
        const textarea = document.querySelector('textarea')
        const button = document.querySelector('button')
        textarea.value = 'test textarea focus'
        console.log({ textarea, button });
        button.addEventListener('click', () => {
            textarea.focus()
        })
    </script>
</body>

</html>
```

可以试试看这个

**Comment by miracles1919** [comment]
我试了确实是原生行为

你上面的这个例子，之所以是正常的，是因为 value 的值设置的时机变了

如果 textarea 有初始 value，光标就会在最前面

```html
<textarea name="" id="" cols="30" rows="10"> textarea </textarea>
    <button>focus</button>
    <script>
        const textarea = document.querySelector('textarea')
        const button = document.querySelector('button')
        button.addEventListener('click', () => {
            textarea.focus()
        })
    </script>
```

**Comment by miracles1919** [comment]
我去查了下 [textarea 的规范](https://html.spec.whatwg.org/multipage/form-elements.html#the-textarea-element)，对于光标位置是有描述的

> If the new [API value](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-api-value) is different from oldAPIValue, then move the [text entry cursor position](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-textarea/input-cursor) to the end of the text control

刚好和上面的例子吻合了

![image](https://user-images.githubusercontent.com/22469543/188796692-7008ceb8-0d09-4553-a570-4c2c2ea7d89b.png)

---

另外，https://github.com/ant-design/ant-design-mobile/pull/5626 这个 pr 通过 `setSelectionRange` 确实可以控制光标位置

但这种 hack 的方法只能在 `focus()` 方法里有效，还有 `autoFocus` 这样的属性.. 

综合起来考虑还是保持原生行为了，有需要可以参考这个 PR ，自行处理一下

**Comment by qianfengg** [comment]
嗯好，谢谢大佬
