### ISSUE TITLE
TabBar 的问题 （dva）

### ISSUE THREAD

**Issue by LayGit** [ant-design/ant-design-mobile#562]
#### 本地环境

- antd-mobile 版本：0.9.9
- 操作系统及其版本：macOS Sierra
- 浏览器及其版本：chrome 50.0.2661

#### 你做了什么？

通过 dva 创建的项目，在 components  里创建一个组件，引入 TabBar

    import React from 'react'
    import { TabBar } from 'antd-mobile'
    
    function Test() {
        return (
            <TabBar
            ...
             />
        )
    }
    ...

#### 你期待的结果是：

不报错

#### 实际上的结果：

控制台报错：

    invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

试了下 NavBar 组件就不会有问题

**Comment by silentcloud** [comment]
应该是和 #545 一个情况

**Comment by LayGit** [comment]
@silentcloud  React 版本是 15.3.2，我是用 dva new project 直接创建的项目

**Comment by silentcloud** [comment]
@LayGit  我用 https://github.com/dvajs/dva-cli 创建测试项目，pkg 添加了 
```json
{
  "antd-mobile": "0.9.9",
  "postcss-pxtorem": "^3.3.1",
  "babel-plugin-import": "~1.0.1"
}

```

routes/IndexPage.js 加了：

```javascript
import { TabBar, Icon } from 'antd-mobile'
function IndexPage() {
  return (
    <div className={styles.normal}>
     <TabBar
        unselectedTintColor="#949494"
        tintColor="#33A3F4"
        barTintColor="white"
        hidden={false}
      >
        <TabBar.Item
          icon={<Icon type="koubei-o" size="md" />}
          selectedIcon={<Icon type="koubei" size="md" />}
          title="口碑"
          key="口碑"
        >
          口碑
        </TabBar.Item>
        <TabBar.Item
          icon={
            <div style={{
              width: '0.44rem',
              height: '0.44rem',
              background: 'url(https://zos.alipayobjects.com/rmsportal/EljxLrJEShWZObW.png) center center /  0.44rem 0.35rem no-repeat' }}
            />
          }
          selectedIcon={
            <div style={{
              width: '0.44rem',
              height: '0.44rem',
              background: 'url(https://zos.alipayobjects.com/rmsportal/LWNaMdwAFSmYBFw.png) center center /  0.44rem 0.35rem no-repeat' }}
            />
          }
          title="朋友"
          key="朋友"
          selected={true}
        >
          朋友
        </TabBar.Item>
        <TabBar.Item
          icon={{ uri: 'https://zos.alipayobjects.com/rmsportal/YWpPVCVOnJoCYhs.png' }}
          selectedIcon={{ uri: 'https://zos.alipayobjects.com/rmsportal/WadBBxOIZtDzsgP.png' }}
          title="我的"
          key="我的"
        >
          我的
        </TabBar.Item>
      </TabBar>
    </div>
  );
}
```

没报错，不过我是 chrome 54.0.2840.98

**Comment by silentcloud** [comment]
[myapp.zip](https://github.com/ant-design/ant-design-mobile/files/608071/myapp.zip)

你下下来跑跑，看是否出错

**Comment by LayGit** [comment]
@silentcloud 好的，我试试。 咦  TabBar 支持 iconfont 了嘛？

**Comment by silentcloud** [comment]
>  TabBar 支持 iconfont 了嘛 

这个是 1.0.0-alpha 的特性，上面的 myapp 里的代码从master 分支拷过来的 

问题解决了的话，那我关掉了
