### ISSUE TITLE
FloatingBubble无法阻止冒泡

### ISSUE THREAD

**Issue by xiahller** [ant-design/ant-design-mobile#5622]
### Version of antd-mobile

5.18.0

### Operating system and its version

Others

### Browser and its version

Chrome 104.0.5112.102（正式版本） （64 位）

### What happened?

1.背景：在页面中嵌入iframe展示第三方内容，同时需要在此页面加入一个FloatingBubble做收藏功能。当把FloatingBubble拖入iframe上时，无法移动和点击FloatingBubble，只能移动下方的iframe内容
2.解决思路：考虑到是否是冒泡问题，阻止冒泡后，仍然无法解决。

3.期望：当移动FloatingBubble到iframe上层时，仍能正常使用FloatingBubble的拖拽移动和点击事件。

**Comment by miracles1919** [comment]
先提供下可复现的 demo 吧

[codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx)

**Comment by xiahller** [comment]
> 先提供下可复现的 demo 吧
> 
> [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx)

刚刚试了下无法复现，而我本身的代码今天什么都没改，就又可以正常操作了，不知道为啥。谢谢回复。
