### ISSUE TITLE
Modal 弹窗 支持 wrapClassName  属性

### ISSUE THREAD

**Issue by baopingchen** [ant-design/ant-design-mobile#5623]
### Version of antd-mobile

5.22.0

### What is this feature about?

Modal 弹窗 需要 支持 wrapClassName  属性 ，希望支持

**Comment by MuxinFeng** [comment]
是啥使用场景呢？
如果不具备通用性，还是自己在业务代码里改样式吧

**Comment by miracles1919** [comment]
有 `bodyClassName` 和 `maskClassName` ，应该能满足了

**Comment by baopingchen** [comment]
主要是修改 最外层的max-width 目前已经在业务里通过重新class样式的方式解决
