### ISSUE TITLE
pnpm 作为 npmClient 时， build 失败 

### ISSUE THREAD

**Issue by chanv11** [ant-design/ant-design-mobile#5628]
### Version of antd-mobile

5.22.0

### Operating system and its version

Others

**Comment by chanv11** [comment]
![image](https://user-images.githubusercontent.com/30683609/187818660-f14e8579-14e0-4a84-b56f-1d5933795460.png)

**Comment by miracles1919** [comment]
来个复现的包吧

**Comment by chanv11** [comment]
我是直接把 master clone 下来 ，install 后 去 build 就出现这种情况

**Comment by chanv11** [comment]
> 来个复现的包吧


我是直接把 master clone 下来 ，install 后 去 build 就出现这种情况

**Comment by miracles1919** [comment]
我们都是用 pnpm 的.. 要不你删了 node_modules，重新 `pnpm install`、`pnpm build` 试试？

**Comment by chanv11** [comment]
> 我们都是用 pnpm 的.. 要不你删了 node_modules，重新 `pnpm install`、`pnpm build` 试试？

您好，我这边尝试了下，npmClient 为 pnpm 我分辨用 `windows ` 和 `centOS ` 作为 系统对同一份 node_modules 进行 `pnpm build`.
问题出现在了 buildDeclaration 这一步。
猜想是否和 
![image](https://user-images.githubusercontent.com/30683609/187820999-81aa917a-5d44-495d-8cd9-bba2d645e176.png)
`typeRoots` 有关，`Symlink` 在 `windows `上会有问题？

**Comment by awmleer** [comment]
社区里应该也有朋友用 Windows 作为开发环境的，可以等等看其他人有没有遇到这个问题，是不是稳定复现的

issue 先挂在这里好了
