### ISSUE TITLE
关于Picker组件的建议

### ISSUE THREAD

**Issue by 16code** [ant-design/ant-design-mobile#563]
现在Picker 组件对data的格式固定的很死 只能是下边这样:
```js
{
  label: 'my label',
  value: 123456,
  children: [...]
}
```
官方组件根据 label 字段来显示列表的文字, onChange 选中回调事件返回的是 value,
这个时候 value , 但是这个 value里边的数据信息有限, 这时候我们会用这个 value 去源数据中找对应的数据
所以不太方便 ;

#### 现存的问题

value 字段可以配置成一个对象  比如 value: {name: 'name',  other: '...', id: 123} 目前也支持这样配置
这样返回的数据基本上就不需要再去别的地方取了;

### 但是 react 在循环数据的时候需要一个 key , 这个时候由于 key 是一个对象 所以 会报错

Encountered two children with the same key, `[object Object]`. Child keys must be unique; when two children share a key, only the first child will be used.

#### 我的建议 
- 在数据里边可以指定 要使用的 key字段, 或者拿默认提供的key字段
```js
{
  label: 'my label',
  key: 123456,
  value: 123456,
  children: [...]
}
```

希望官方酌情考虑.

**Comment by warmhug** [comment]
value 就是一个 id、不支持复杂对象，这样能保持 view 层比较纯粹，数据处理还是要自己单独做的。这是一个比较常见的问题，不过感觉还是目前的做法比较好，谢谢建议。
