### ISSUE TITLE
IOS 13.7 自动轮播会造成indicator 不显示 第一个又会显示

### ISSUE THREAD

**Issue by HChen318** [ant-design/ant-design-mobile#5631]
### Version of antd-mobile

5.22.0

### Browser and its version

IOS 13.7

**Comment by zqran** [comment]
可以提供下可复现的 demo~

[codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx)
