### ISSUE TITLE
Swiper 支持更细节化的样式定制？

### ISSUE THREAD

**Issue by miusuncle** [ant-design/ant-design-mobile#5632]
### Version of antd-mobile

5.22.0

### What is this feature about?

使用 Swiper 的时候，我想对每个 Item 添加缩放过渡，如中间大、两边小，滑动时缩放效果能即时反馈，目前貌似没提供勾子实现这样的效果。

**Comment by awmleer** [comment]
这种情况下看起来不太适合使用 antd-mobile 的 Swiper 了，可以考虑：

1. 自己基于 react-spring 和 use-gesture 之类的动画和手势库来实现
2. 使用更重一些的库例如 swiper.js
