### ISSUE TITLE
Slider 滑动输入条，启用popover属性后默认能否自动显示？

### ISSUE THREAD

**Issue by ikangjie** [ant-design/ant-design-mobile#5637]
### Version of antd-mobile

antd-mobile 5.22.0

### What is this feature about?

使用场景：用户进来后能第一直观看到目前的金额大小

**Comment by MuxinFeng** [comment]
这种我感觉进页面后，在`useEffect`里给个`toast`就可以了吧

**Comment by ikangjie** [comment]
就是有一个游戏场景，用户选择了本次的投注金币，下次他进来的时候需要记住他上次投注的金币，因为数值比较大，100-5000之间，他上次选择了3020，刻度也不可能精确到这个数值上，用户进来之后，他看到默认的投注其实是他上次的投注数值，此时用户是不太清楚他上次投注了多少金币，如果popover有个默认显示，我想会直观很多。而且也不单单只是这个场景，比如还有需要还原上次的用户操作...

**Comment by ikangjie** [comment]
期望能有一个默认显示popover的属性，比如default show popover...

**Comment by MuxinFeng** [comment]
有道理，或许可以加个`residentPopover`属性来控制`popover`是否常驻？
@awmleer 大佬觉得呢

**Comment by awmleer** [comment]
@MuxinFeng +1 大佬有空来提个 PR 不～

**Comment by MuxinFeng** [comment]
好滴~
