### ISSUE TITLE
TabBar.Item 的icon 图标不能自定义吗？

### ISSUE THREAD

**Issue by haojingxue** [ant-design/ant-design-mobile#5646]
### Version of antd-mobile

5.22.0

### Operating system and its version

iOS

### What happened?

TabBar.Item 的icon 图标不能自定义吗？

**Comment by MuxinFeng** [comment]
可以的，你写个`demo`我帮你看看

**Comment by haojingxue** [comment]
谢谢！我已经实现了

 {
      key: '/main/mine',
      title: '我的',
      // icon: <TeamOutline/>,
      icon: (active) =>  active ? <img className='bar-item-icon' src={require('../../assets/img/icon_history_s.png')}/> : <img className='bar-item-icon' src={require('../../assets/img/icon_history.png')}/>
    },
