### ISSUE TITLE
Swiper 竖屏滚动且轮播图宽度没有铺满设置--track-padding不能分离指示器

### ISSUE THREAD

**Issue by hcxmj** [ant-design/ant-design-mobile#5647]
### Version of antd-mobile

5.21.0

### Operating system and its version

iOS, Android, Others

### Browser and its version

Mac chrome: 104.0.5112.101

### What happened?

需求是轮播图竖向展示且宽度不是满屏宽居中展示，指示器需要分离在右侧，如图所示，根据--track-padding设置后发现会被轮播图右边盖住
`          <div className="banner">
                <Swiper 
                    direction='vertical' 
                    style={{ 
                        '--height': '560px',
                     }} 
                    onIndexChange={bannerChange}
                    autoplay={true}
                    loop={true}
                    indicatorProps={{
                        style: {
                            '--dot-color': '#fff',
                            '--dot-size': '12px',
                            '--dot-spacing': '12px',
                            '--dot-border-radius': '50%',
                            '--active-dot-size': '32px',
                            '--active-dot-border-radius': '16px',
                            '--active-dot-color': 'rgba(255,255,255,0.50)',
                        }
                    }}
                >
                    {demoData.map((item: any, index) => {
                        return (
                            <Swiper.Item key={index}>
                                <img src={item.imgSrc} alt="" className="image" />
                            </Swiper.Item>
                        )
                    })}
                </Swiper>
         </div>
`
`    .banner {
        margin: 390px 95px 0;

        .image {
            width: 100%;
            display: block;
        }
    }`
<img width="510" alt="image" src="https://user-images.githubusercontent.com/58494807/189030513-3a5805d4-56d1-4e98-8150-7b45ce2c7b81.png">

**Comment by miracles1919** [comment]
提供下可复现的 demo 吧，[codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx)

**Comment by hcxmj** [comment]
> 提供下可复现的 demo 吧，[codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx)

已经曲线处理

**Comment by awmleer** [comment]
OK，那 issue 我关闭了～如果有兴趣的话可以分享下你的解决思路嘛？

**Comment by hcxmj** [comment]
> OK，那 issue 我关闭了～如果有兴趣的话可以分享下你的解决思路嘛？

解决方式就睡轮播图整体区域除了左边距的剩余宽度，而不是图片宽度就代表整个轮播区域，相当于图片并没有占满整个区域空了一部分出来放这个指示器，就可以正常展示，否则就像是超出隐藏一样会被右边距盖住
