### ISSUE TITLE
[calendar] 限制日历是否可以翻页

### ISSUE THREAD

**Issue by wine-fall** [ant-design/ant-design-mobile#5651]
### Version of antd-mobile

5.22.0

### What is this feature about?

- 想要禁止日历的翻页，比如当前的需求限制用户只能看当前月份，无法实现，试过一些方法，详见：https://github.com/ant-design/ant-design-mobile/discussions/5649
- 新增两个 props：prevFarthestDate，nextFarthestDate。分别表示**最前**能看到的日期，和**最后**能看到的日期，该区间为左闭右闭，也即为 [prevFarthestDate, nextFarthestDate]
- 已提pr：https://github.com/ant-design/ant-design-mobile/pull/5650

**Comment by awmleer** [comment]
#5650
