### ISSUE TITLE
 Conflict styled-component vs antd-mobile

### ISSUE THREAD

**Issue by trinhnhatsinh** [ant-design/ant-design-mobile#5654]
### Version of antd-mobile

5.22.0

### Description

I have installed antd-mobile in nextjs project and lost css of styled-component when i import a compoent of antd-mobile

**Comment by zqran** [comment]
did you follow this guide: [antd-mobile SSR with Next.js](https://mobile.ant.design/guide/ssr#nextjs)

**Comment by awmleer** [comment]
Can you provide a reproduce demo? Maybe push a demo project to GitHub and share its link here.
