### ISSUE TITLE
Picker不兼容IOS9

### ISSUE THREAD

**Issue by hubyq** [ant-design/ant-design-mobile#5657]
### Version of antd-mobile

5.21.0

**Comment by hubyq** [comment]
Picker可选项目全部挤在顶部

**Comment by afc163** [comment]
https://mobile.ant.design/zh/guide/css-variables/#css-%E5%8F%98%E9%87%8F%E8%87%AA%E5%8A%A8%E9%99%8D%E7%BA%A7

**Comment by hubyq** [comment]
> https://mobile.ant.design/zh/guide/css-variables/#css-%E5%8F%98%E9%87%8F%E8%87%AA%E5%8A%A8%E9%99%8D%E7%BA%A7

加了引用了，还是不行呢，下面有个组件范围，不包含Picker

**Comment by awmleer** [comment]
简单排查了一下发现是这里的兼容性问题：

https://github.com/ant-design/ant-design-mobile/blob/6aede4217fbae29b238965e1f79efd65af1cebd8/src/components/picker-view/wheel.tsx#L52

写了个简单的 demo，iOS 10.3 真机的效果：

![image](https://user-images.githubusercontent.com/16526078/190077497-77d45799-e9d3-46ae-9ffa-ee236de7f3b8.png)

我本机的效果：

![image](https://user-images.githubusercontent.com/16526078/190077535-c5f8bbd7-3831-4c5b-a9bf-1e3f3fcbd589.png)

**Comment by awmleer** [comment]
92d6290f7 Fixed
