### ISSUE TITLE
Avatar组件中引用Image组件路径方式有问题，导致会自动引入默认global.css, 导致高清适配失效

### ISSUE THREAD

**Issue by febear** [ant-design/ant-design-mobile#5658]
### Version of antd-mobile

5.22.0

### What happened?

问题：
Avatar组件中引用Image组件路径方式有问题，导致会自动引入global.css, 导致高清适配方案失效
![image](https://user-images.githubusercontent.com/8869285/190088190-3d087969-6797-4806-99a3-484e5d3f1b61.png)

具体文件位置
https://github.com/ant-design/ant-design-mobile/blob/master/src/components/avatar/avatar.tsx#L3

期望改成
import { Image } from '../image';

这样就不会执行到index文件的【import './global';】语句了

**Comment by awmleer** [comment]
这是谁写的弱智代码……让我 blame 看一下

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/16526078/190123655-565a1581-5489-4f73-9260-b46ad728da68.png">

噢……是我自己 😅
