### ISSUE TITLE
antd-mobile 该配合哪个版本的react native 使用？

### ISSUE THREAD

**Issue by qiuchengw** [ant-design/ant-design-mobile#566]
#### 本地环境

- antd-mobile 版本：0.9.3 ／0.9.9
- 操作系统及其版本：
andriod 4.4 
react native ：0.37.0 
react:15.3.2

#### 你做了什么？

使用antd-mobile 0.9.9版本，List - InputItem控件做用户名输入。
0.9.9版本连光标都无法显示，像是一直无法获取焦点似的，也无法输入任何字符。
回退到0.9.6的时候，能显示光标了，但是依然无法输入任何字符。
一直回退到0.9.3 版本，才能够正常使用了。这个跟RN的版本有关系吗？

看到antd 最近更新了很多东西，请问下各位，你们测试／发布／使用0.9.9版本的时候，以下的版本环境都是什么呢？
------
RN版本
配合的React版本
Android／Ios版本
虚拟机版本（genymotion？ios simulator？）
宿主系统版本（win／mac）

**Comment by qiuchengw** [comment]
现在升级RN代码真的超级痛苦，各个组件包括RN本身，每次升级总是出现各种问题。今天只在这试验版本搭配都试了1个多小时。我现在主要使用antd-mobile库的控件开发，还是很喜欢antd这款产品的。各位发布antd新版本的时候能否带上你们运行通过的RN+react的版本呢，可以省了我们使用者很多时间啊。请考虑下，多谢。

**Comment by benjycui** [comment]
看下 [`package.json`](https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L113)?

**Comment by qiuchengw** [comment]
@benjycui 😭  我都给气糊涂了。这么简单的办法居然没想到。多谢多谢。

另外刚看了，依赖RN 0.34版本。现在的RN是0.38了，各位开发大大能否考虑下升级呢？

**Comment by afc163** [comment]
感觉可以加上 `peerDependencies`.

**Comment by silentcloud** [comment]
@qiuchengw pkg 里的 react-native 版本仅仅是用给 demo app 用的，组件自身的 rn 版本是用户来自定义的，如果发现某个组件在自己引入的 rn 版本中使用不了，反馈 issue 即好，我们会排查，感谢

**Comment by warmhug** [comment]
rn 保持支持最新版

**Comment by smalltide** [comment]
我目前這樣搭配可以運行
https://github.com/smalltide/react-native-antd
