### ISSUE TITLE
ImageUploader iOS15.6.1 上传内存特别大的图不触发onChange事件

### ISSUE THREAD

**Issue by AspirinMrmi** [ant-design/ant-design-mobile#5661]
### Version of antd-mobile

5.22.0

### Operating system and its version

iOS

### Browser and its version

iOS Safari 15.6.1

### What happened?

ImageUploader在iOS15.6.1上传内存特别大的图片（大于30MB）时不会触发input的onChange事件，有没有什么hack方案？在同事的iOS13.6版本上是没问题的。

**Comment by awmleer** [comment]
想先确认下，用官方文档上的 demo 可以复现么？

**Comment by awmleer** [comment]
以及，最好能提供个录屏视频，这样可以帮助大家排查帮你问题

**Comment by AspirinMrmi** [comment]
> 以及，最好能提供个录屏视频，这样可以帮助大家排查帮你问题


https://user-images.githubusercontent.com/20723883/190124724-e2f9d00e-d6a9-4280-8454-a55a7645c626.mp4

**Comment by AspirinMrmi** [comment]
@awmleer 加了multiple属性居然可以选择，我更加费解了🤔。

**Comment by awmleer** [comment]
这么离谱？？试试系统原生的 input 吧～我感觉大概率是 Safari 或者 iOS 的 bug

**Comment by AspirinMrmi** [comment]
> 这么离谱？？试试系统原生的 input 吧～我感觉大概率是 Safari 或者 iOS 的 bug

原生的表现和antd mobile的表现一致😂，就很诡异。

**Comment by awmleer** [comment]
那看起来不是 antd-mobile 的 bug 了 😅

**Comment by jinrichardJIN** [comment]
上传组件的内部代码 貌似根本就没 处理外部props.onChange 
是我看错了吗？

**Comment by zqran** [comment]
@jinrichardJIN 在 `usePropsValue` 中统一处理了

**Comment by awmleer** [comment]
各位～ issue 我先关闭了哈，看起来不是 antd-mobile 力所能及的范畴了
