### ISSUE TITLE
Swiper in Swiper doesn't work

### ISSUE THREAD

**Issue by anhhtrduc** [ant-design/ant-design-mobile#5663]
### Version of antd-mobile

5.22.0

### Description

I have a Tabs and Swiper as parents.
In child of parents, I have a Swiper to display image, but when I swipe in Swiper child, it doesn't work.
What should I do ?

**Comment by awmleer** [comment]
Could you please write a reproduce demo at https://codesandbox.io/s/antd-mobile-snrxr?file=/src/App.tsx or https://stackblitz.com/edit/antd-mobile ?

**Comment by anhhtrduc** [comment]
https://codesandbox.io/s/admiring-ride-88gt3q?file=/src/App.tsx
It looks like this. When you swipe in child Swiper , parents Swiper swipe itself.

**Comment by HuberTRoy** [comment]
看起来阻止一下冒泡可以解决这个问题。

感觉还可以在子`Swiper`滑动到头时允许父Swiper恢复滑动？

@awmleer 大佬觉得呢。

P.S ̋(ˊ•͈ ꇴ •͈ˋ)想提这个PR。

**Comment by awmleer** [comment]
@HuberTRoy 欢迎来贡献呀～可以改改试试看，不过还是要提个醒，如果直接阻止全部事件冒泡的话其实不太合适，举个例子，目前对于一个水平方向的 Swiper，我们如果用手指在它上面上下滑动，是可以正常触发整个页面的滚动的，如果完全阻止了所有事件，那可能就无法上下滑动了，对于全屏的 Swiper，这个影响可能会很严重

**Comment by awmleer** [comment]
不知道这个 discussion 是不是相关：https://github.com/pmndrs/use-gesture/discussions/474

**Comment by anhhtrduc** [comment]
Please support me by english, I can't understand Chinese  (ˊ•͈ ꇴ •͈ˋ) @awmleer

**Comment by awmleer** [comment]
@anhhtrduc Sorry for that. 😅 We have been working on solving this bug and it should be fixed after the next release.
