### ISSUE TITLE
项目引入的  @floating-ui/core  和 @floating-ui/dom  打包后包含 es6代码 导致低版本android 手机报错

### ISSUE THREAD

**Issue by gyf30827** [ant-design/ant-design-mobile#5666]
### Version of antd-mobile

5.23.0

### Operating system and its version

Android

### What happened?

项目引入的  @floating-ui/core  和 @floating-ui/dom  打包后包含 es6代码 导致低版本android 手机报错
包含 const 以及 let 还有箭头函数等

**Comment by awmleer** [comment]
[文档](http://localhost:8000/zh/guide/quick-start#%E5%85%BC%E5%AE%B9%E6%80%A7)上有说明的，读一下哈～

**Comment by gyf30827** [comment]
> [文档](http://localhost:8000/zh/guide/quick-start#%E5%85%BC%E5%AE%B9%E6%80%A7)上有说明的，读一下哈～
已经配置，只有上面说的两个包没有被处理， 你这边方便的可以试一下

**Comment by awmleer** [comment]
@gyf30827 那需要你来提供一个复现 demo 哈

**Comment by miusuncle** [comment]
`babel-loader` 的 test 配置是否命中了 `.mjs` 后缀文件？

**Comment by Marszht** [comment]
> @gyf30827 那需要你来提供一个复现 demo 哈

你好我这边也出现了这个问题，@floating-ui/dom 中的 computePosition 这个没有被编译，但是其他的内容被编译了
![image](https://user-images.githubusercontent.com/38552120/190989420-5d18d74e-5047-4860-969d-4cfa2ea06759.png)

**Comment by awmleer** [comment]
> `babel-loader` 的 test 配置是否命中了 `.mjs` 后缀文件？

@Marszht @gyf30827 可以确认下这个，大概率是这个导致的

**Comment by gyf30827** [comment]
> `babel-loader` 的 test 配置是否命中了 `.mjs` 后缀文件？

是的，增加了个单独的rule 处理这个文件就可以了

**Comment by Marszht** [comment]
> 
`
        {
          loader: "babel-loader",
          test: /\.(js|jsx|mjs)$/,
          include: path.resolve(projectRootDir, "src"),
          exclude: [
            path.resolve(projectRootDir, "node_modules_patch"),
            path.resolve(projectRootDir, "node_modules_raw"),
            path.resolve(projectRootDir, "vendor"),
          ],
          options: {
            cacheDirectory: true,
          }
        },`
        你好我这样 /\.(js|jsx|mjs)$/  处理后好像还是没有生效呢

**Comment by Marszht** [comment]
> > `babel-loader` 的 test 配置是否命中了 `.mjs` 后缀文件？
> 
> 是的，增加了个单独的rule 处理这个文件就可以了

{ loader: "babel-loader", test: /\.(js|jsx|mjs)$/, include: path.resolve(projectRootDir, "src"), exclude: [ path.resolve(projectRootDir, "node_modules_patch"), path.resolve(projectRootDir, "node_modules_raw"), path.resolve(projectRootDir, "vendor"), ], options: { cacheDirectory: true, } },
你好我这样 /.(js|jsx|mjs)$/ 处理后好像还是没有生效呢

**Comment by Marszht** [comment]
> > `babel-loader` 的 test 配置是否命中了 `.mjs` 后缀文件？
> 
> 是的，增加了个单独的rule 处理这个文件就可以了
        {
          loader: "babel-loader",
          test: /\.(js|jsx|mjs)$/,
          include: path.resolve(projectRootDir, "src"),
          exclude: [
            path.resolve(projectRootDir, "node_modules_patch"),
            path.resolve(projectRootDir, "node_modules_raw"),
            path.resolve(projectRootDir, "vendor"),
          ],
          options: {
            cacheDirectory: true,
          }
        },
  你好  这样增加这个rule 之后好像还是没有生效呢？

**Comment by awmleer** [comment]
@Marszht 可以把你的项目上传一下，有复现 demo 大家才能帮你排查问题的～

这个 issue 是 @gyf30827 提的，目前来看他的问题已经解决了，那 issue 我就先关闭掉了， @Marszht 你可以再单独开个 issue 哈，这样方便跟踪
