### ISSUE TITLE
上传组件的内部代码 貌似根本就没 处理外部props.onChange  是我看错了吗？

### ISSUE THREAD

**Issue by jinrichardJIN** [ant-design/ant-design-mobile#5668]
### Version of antd-mobile

master

**Comment by miracles1919** [comment]
对 `value` `onChange` `defaultValue` 的处理在 [usePropsValue](https://github.com/ant-design/ant-design-mobile/blob/master/src/utils/use-props-value.ts) 

可以看下作者的文章，[React 组件的受控与非受控](https://www.yuque.com/awmleer/rocket/xmx2gb#xOywi)
