### ISSUE TITLE
SwipeAction在Android上长按弹出的dialog出现空白按钮

### ISSUE THREAD

**Issue by jinkin1995** [ant-design/ant-design-mobile#567]
#### 本地环境

- antd-mobile 版本： 0.9.2
- 操作系统及其版本：Android
- 浏览器及其版本：Chrome, 微信内置浏览器

#### 你做了什么？

- SwipeAction长按

#### 你期待的结果是：

- 出现操作用的dialog

#### 实际上的结果：

- 除了自己定义的按钮还有个空白按钮

#### 可重现的在线演示

![qq 20161124102251](https://cloud.githubusercontent.com/assets/7165022/20584699/51fa474c-b230-11e6-8345-a3e6a00837fe.png)

**Comment by silentcloud** [comment]
@jinkin1995 麻烦贴一下你的代码，我这边无法重现

**Comment by jinkin1995** [comment]
@silentcloud 

`<SwipeAction
            key={key}
            style={{
              backgroundColor: '#eeeeee'
            }}
            title="是否决定删除？"
            autoClose
            right={[{
              "text": '取消',
              "onPress": () => {},
              "style": {
                "backgroundColor": '#cccccc',
                "color": 'white'
              }
            },{
              "text": '删除',
              "onPress": () => {this.toDelBill(billType, m["DocID"], key)},
              "style": {
                "backgroundColor": '#F4333C',
                "color": 'white'
              }
            }
          ]}>
            <div>
              <List.Item
                className="bill_item"
                thumb={icon}
                extra={
                  <div className="bill_meta">
                    {/* <span className="status">{m["ApproveStatus"]}</span> */}
                    <span className="t">{time_show}</span>
                    <span className="amount">{m["OccurMoney"]}</span>
                  </div>
                }
                align="top"
                onClick={this.toDetail.bind(this, m["BusinessTypeName"], m["DocID"], m["CID"], m["MID"], m["IsCanEdit"])}
                >
                  <span className="title">
                    {m["DocNo"]}
                  </span>
                <List.Item.Brief>
                  {m["Title"].slice(0,12)+".."}
                </List.Item.Brief>
              </List.Item>
            </div>
          </SwipeAction>`

**Comment by afc163** [comment]
https://segmentfault.com/markdown

**Comment by jinkin1995** [comment]
```html
<SwipeAction 
    key={key} 
    style={{ backgroundColor: '#eeeeee' }}    
    title="是否决定删除？" 
    autoClose 
    right={[{ 
        "text": '取消', 
        "onPress": () => {}, 
        "style": { "backgroundColor": '#cccccc', "color": 'white' } 
        },{ 
        "text": '删除', 
        "onPress": () => {
            this.toDelBill(billType, m["DocID"], key)
        }, 
        "style": { "backgroundColor": '#F4333C', "color": 'white' } } 
      ]}> 
      <div> 
          <List.Item className="bill_item" thumb={icon} 
          extra={ 
              <div className="bill_meta">
                  <span className="t">{time_show}</span> 
                  <span className="amount">{m["OccurMoney"]}</span> 
              </div> } 
          align="top" 
          onClick={this.toDetail.bind(this, m["BusinessTypeName"], m["DocID"], m["CID"], m["MID"], m["IsCanEdit"])} > 
              <span className="title"> {m["DocNo"]} </span> 
              <List.Item.Brief> {m["Title"].slice(0,12)+".."} </List.Item.Brief> 
          </List.Item> 
      </div>
 </SwipeAction>
```

**Comment by jinkin1995** [comment]
@silentcloud  关闭issues吧，是我这边的问题，不好意思:no_mouth:

**Comment by afc163** [comment]
@jinkin1995 建议自行关闭 😃

**Comment by jinkin1995** [comment]
closes #567
