### ISSUE TITLE
Stepper 默认弹出数字键盘

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#5675]
### Discussed in https://github.com/ant-design/ant-design-mobile/discussions/5671

<div type='discussions-op-text'>

<sup>Originally posted by **qq382724935** September 19, 2022</sup>
Stepper选中input希望能弹出数字键盘。但是好像设置不了input type或者其它原生属性</div>

**Comment by Julycc41** [comment]
您好 这个问题解决了吗，现在弹出并不是数字键盘
