### ISSUE TITLE
在webpack的umd构建模式下，tree-shaking貌似失效。

### ISSUE THREAD

**Issue by semdy** [ant-design/ant-design-mobile#5681]
### Version of antd-mobile

5.12.5

### Description

在webpack的umd构建模式下，tree-shaking失效了。所有组件及antd-mobile-icons里所有图标都打进了bundle里。

webpack: 5.73.0
antd-mobile: 5.12.5

**Comment by miracles1919** [comment]
应该是你使用的问题，可以提供个项目压缩包，让大家帮你看下

**Comment by miracles1919** [comment]
可以看下 webpack 的[文档](https://webpack.docschina.org/guides/tree-shaking/#conclusion)

![image](https://user-images.githubusercontent.com/22469543/191638047-bc44bc04-fc34-4fa7-b4b2-4ec9e5ea83e1.png)
