### ISSUE TITLE
InfiniteScroll 初始化的时候会加载两页数据

### ISSUE THREAD

**Issue by haiting** [ant-design/ant-design-mobile#5684]
### Version of antd-mobile

v5.21.0

### What happened?

问题：InfiniteScroll 初始化的时候会加载第二页的数据

期望：初始化的时候，只加载第一页数据，滚动到阈值才加载第二页数据

重现步骤：官网的第一个例子就能重现，刷新页面，等待一会，会发现第一个例子的滚动条有跳动
http://ant-design-mobile.antgroup.com/zh/components/infinite-scroll

**Comment by miracles1919** [comment]
这不是 bug 哈，这是因为第一页数据加载后，元素高度不够，仍然符合 `doLoadMore` 执行的条件，所以又执行了一次 `doLoadMore`

具体的代码判断在这里 https://github.com/ant-design/ant-design-mobile/blob/master/src/components/infinite-scroll/infinite-scroll.tsx#L75
