### ISSUE TITLE
Picker PickerView等组件能否支持一下number类型。　PickerValue string太难受了！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#5688]
### Version of antd-mobile

eg 5.24.0

### What is this feature about?

现在picker 类型是 ``` string | null; ```但实际开发中的 value  更多的是number　int类型的。数据库存的也是int类型。在ant design使用都是 {label: string, value: number} 但是到了mobile v5 就是{label: string, value: string}，逼得我要么从数据库取出来转一次，要么自己在前端循环转一次。这样的工作太繁重了，希望能改掉这个类型加入支持number类型。跟ant design 同步！
<img width="552" alt="image" src="https://user-images.githubusercontent.com/12706830/192154428-7eb2df7f-5434-4b48-9d03-a07340191014.png">

ant design 的
<img width="767" alt="image" src="https://user-images.githubusercontent.com/12706830/192154552-1ebdd443-66b5-4a40-8e1f-41e8bf9912f1.png">

**Comment by codedart2018** [comment]
@awmleer 你怎么不在群里了？

**Comment by MuxinFeng** [comment]
这类问题我在业务开发里也遇到过，有的时候枚举值默认就是 0、1、2....，然后用起来就很不方便，同理还有 `Radio` 组件，感觉 `value`  的类型都可以放开些~
如果大佬觉得可以，小弟提个 PR 做下增强~

**Comment by miracles1919** [comment]
之前有讨论 https://github.com/ant-design/ant-design-mobile/issues/5199#issuecomment-1136660423

这个问题能改么 @MuxinFeng

**Comment by afc163** [comment]
来个 PR 吧

**Comment by MuxinFeng** [comment]
我晚点看看哈 @miracles1919

**Comment by MuxinFeng** [comment]
根据历史 `issue` 的讨论来看，其实更改难度不大，只是涉及的面比较广，几乎用到 `PickerView` 的地方都需要做些调整，包括 `props`、`setState`、`demo`文件这些地方。
我打算一并改一下，然后走下 lint 和 test，请问还有什么我没注意到的地方吗？

**Comment by MuxinFeng** [comment]
没整明白，我的 pr 先关啦。等大佬们搞吧

**Comment by 1587315093** [comment]
#6089 已添加
