### ISSUE TITLE
TextArea 组件在pc chrome浏览器中maxLength属性失效

### ISSUE THREAD

**Issue by ananiahfox** [ant-design/ant-design-mobile#5694]
### Version of antd-mobile

5.20.0

### Browser and its version

版本 106.0.5249.61（正式版本） (arm64)

### What happened?

TextArea 组件在pc chrome浏览器中maxLength属性失效
`
<Form.Item name="remark">
        <TextArea
          placeholder="请填写意见或建议"
          showCount
          maxLength={20}
          autoSize={true}
          rows={4}
        />
 </Form.Item>
`

https://user-images.githubusercontent.com/41354027/192677782-66680268-5deb-4b2b-85ac-2573780a70d7.mov

**Comment by miracles1919** [comment]
我试了下正常的，能提供下可复现的 demo 么，[codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx)

**Comment by ananiahfox** [comment]
抱歉 是我没有描述清楚。我是在nextjs + preact + TS中使用的，他们的版本分别为： "antd-mobile": "^5.20.0", "next": "12.2.3", "next-plugin-preact": "^3.0.6", "preact": "^10.5.15", "preact-render-to-string": "^5.1.19", "next-transpile-modules": "^9.0.0", "typescript": "4.7.4" 。 我刚在codesandbox 上尝试建立一个demo，但是next.config.js 需要引入的文件报错（package.json有引入这个依赖，Cannot find module 'next-transpile-modules'）。所以我无法提供可复现的demo。我会再次进场尝试建立一个可复现的demo。
