### ISSUE TITLE
Popup组件显示关闭按钮，有时会遮挡掉内容区域

### ISSUE THREAD

**Issue by DaJianWu** [ant-design/ant-design-mobile#5695]
### Version of antd-mobile

5.24.0

### Operating system and its version

iOS

### Browser and its version

ios13

### What happened?

Popup组件显示关闭按钮，有时会遮挡掉内容区域。期望可以适当增大内容区域的内边距

![image](https://user-images.githubusercontent.com/55335768/192681984-fbdde86e-f082-4bc9-b37f-48622e4fb9dd.png)

**Comment by afc163** [comment]
这感觉是设计问题。

**Comment by DaJianWu** [comment]
> 这感觉是设计问题。

意思是说antd内部的设计就是这样的吗？那感觉也不能遮挡住内容吧。。。不然使用的话需要手动调整一下内边距，很麻烦
