### ISSUE TITLE
Tabs组件关于key的类型问题

### ISSUE THREAD

**Issue by DaJianWu** [ant-design/ant-design-mobile#5696]
### Version of antd-mobile

5.24.0

### Operating system and its version

iOS

### Browser and its version

ios13

### Sandbox to reproduce

https://stackblitz.com/edit/react-ts-efrahg?file=App.tsx%3AL7

### What happened?

`Tabs`组件的`activeKey/defaultActiveKey`和`Tabs.Tab`组件的`key`的类型在文档上定义的是只支持`string`，但在使用过程中`Tabs.Tab`组件的`key`的类型其实是`React.Key`，应该是和`react`中的`key`混淆了，感觉会产生误解。

不过实际上不管是`string`还是`number`类型，组件都是可以正常受控的

![image](https://user-images.githubusercontent.com/55335768/192684137-ec14879c-03e9-4473-8d93-2e3a229570ee.png)

![image](https://user-images.githubusercontent.com/55335768/192684177-e3a5a249-ce55-45d1-90dc-eb9019a99d96.png)

**Comment by miracles1919** [comment]
不管 key 传入什么类型，React 都会转换成 string 的

**Comment by zqran** [comment]
他的意思可能是说：文档中 Tabs.Tab 的 `key` 属性的类型是 `string` 而实际使用时传入 `number` 类型的数据也可以，也就是**文档描述可能不准确**~ 希望文档可能在准确一些，对吧？@DaJianWu

**Comment by DaJianWu** [comment]
差不多是这个意思吧 感觉和`React`内部转换没啥关系 我是觉得`Tabs`的`activeKey/defaultActiveKey`和`Tabs.Tab`的`key`  它们不管是支持什么类型 但是在类型定义应当是一样的

**Comment by miracles1919** [comment]
后面补个 FAQ

**Comment by DaJianWu** [comment]
#5775
