### ISSUE TITLE
建议 ImageUploader 内Item组件由 Space 替换成 Grid组件！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#5702]
### Version of antd-mobile

eg 5.24.0

## 话不多说，直接看默认的！
![image](https://user-images.githubusercontent.com/12706830/193178796-cf2d262d-00e5-4ebb-9e79-b84cedb13046.png)
## 默认的用的dispaly: flex 自动换行的最后一个依然有margin-right. 导致撑坏到下一行去了！
![image](https://user-images.githubusercontent.com/12706830/193179077-ed4c42f6-b665-4a65-9ee9-734f3d982b95.png)
## 看了下代码是用的 Space。但期望用Grid组件，至少这样才是好看的吧！
![image](https://user-images.githubusercontent.com/12706830/193179358-902073f9-94e8-4e13-8373-28c904dd6443.png)
![image](https://user-images.githubusercontent.com/12706830/193179394-c4227bce-2cdb-40b9-9853-906ab210d642.png)

## 另如果用了Grid组件，期望把gird组件的参数给暴露出来！我现在的方法是自己重写样式给覆盖的。但我更期望不重写样式！

**Comment by afc163** [comment]
来个 PR 吧

**Comment by MuxinFeng** [comment]
codedart2018 姐好强的洞察力！小弟提个 pr 吧，正好上次改过 `Selector`，情况很类似

**Comment by MuxinFeng** [comment]
不知道为啥 `Selector` 里是 `Space` 和 `Grid` 是同时保留，然后让用户自由选择的，大佬们能讲解下嘛~这次的 PR 里我按照`Selector`来改了哈

**Comment by codedart2018** [comment]
> 

你可以顺便在可以把　ImageUploadItem　增加返回一个　status 状态嘛。其实我更建议像and design 的　Item 参数一样。如果两边参数一致的话，后台就不用分别处理前端上传返回值和后端上传返回值了，希望增加status 是希望上传失败后本身上传的图片，可以有一个提示。

现在的情况是upload 直接返回的一个本地的blob url 或　远程的url。但是实际情况下，可能上传多个导致失败，后端没有反回url.虽然空url 会有一个默认的占位格，但我觉得不够醒目，导致人为认为网络加载失败，并不是上传失败的情况。
<img width="388" alt="image" src="https://user-images.githubusercontent.com/12706830/193228508-659608fa-babf-4f5d-be8d-07408d74ddfd.png">
期望内部能有一个失败的机制来显示告知上传失败。

**Comment by miracles1919** [comment]
> 期望内部能有一个失败的机制来显示告知上传失败

可以用 `onUploadQueueChange`

**Comment by awmleer** [comment]
我也想用 Grid……但是 Grid 组件底层是用的 CSS Grid 特性，兼容性比较差，如果真的打算这么搞的话，务必文档上标明一下兼容性问题……就像 Grid 的文档上写的：

> Grid 组件依赖了 CSS Grid 特性，所以兼容性标准是 iOS Safari >= 10.3 和 Chrome >= 57。

**Comment by MuxinFeng** [comment]
好嘞，我补个 FAQ
