### ISSUE TITLE
[LoginPage]希望提供一个完整的登录页

### ISSUE THREAD

**Issue by tiyee** [ant-design/ant-design-mobile#5705]
### What is this feature about?

手机h5页面一般都需要登录页，
但是目前adm缺乏这个页面，
form和input控件都只适合于数据提交，
用这些控件拼出来的登录页十分丑陋，
目前已经提供了一个`ResultPage`，希望提供一个基本可用的`LoginPage`

类似于
![login](https://user-images.githubusercontent.com/2190710/193323282-446597bb-3856-48c0-ad25-647d6d3265a5.jpg)

**Comment by awmleer** [comment]
感觉适合放到 [antd-mobile-pro](https://github.com/ant-design/antd-mobile-pro) 里？ @xiaohuoni

**Comment by xiaohuoni** [comment]
pro 里面有一个登录页面，是支付宝的登录页面，感觉不太适合，我们需要更合适的模版。

**Comment by afc163** [comment]
不属于基础组件负责的范围，先关了。
