### ISSUE TITLE
ImageUploader多张图片上传显示重复

### ISSUE THREAD

**Issue by GitVitality** [ant-design/ant-design-mobile#5710]
### Version of antd-mobile

5.22.0

### Operating system and its version

iOS

### Browser and its version

任意浏览器

### What happened?

移动端选择多张图片同时上传时，最后onChange事件返回的value值都是同一张图片的value值，这段代码有竞争关系，在赋值时可能拿到的是上一次的value值，导致多张图片部分值有丢失，麻烦看一下这个地方应该如何解除这种竞争关系。
![image](https://user-images.githubusercontent.com/14938077/194685210-1b7ec3ef-5989-46c7-a250-56bbc6600b38.png)

**Comment by afc163** [comment]
有重现么

**Comment by zombieJ** [comment]
重现 + 1，这边看起来 setState 用的是 prev 应该是新的才对：

https://github.com/ant-design/ant-design-mobile/blob/fcb9921b7bf9d2b54125d03f252f9b65d7b1045f/src/components/image-uploader/image-uploader.tsx#L169

**Comment by GitVitality** [comment]
重现demo，
![微信图片_20221008124827](https://user-images.githubusercontent.com/14938077/194688939-c3b82b8f-4370-4a56-9005-9a58a2df8b81.jpg)

https://codesandbox.io/s/pedantic-monad-d0b8qw?file=/src/App.tsx

**Comment by GitVitality** [comment]
经过排查，是业务上传函数的问题，可关闭此issue。
