### ISSUE TITLE
Modal组件 ios下 Modal.prompt无法输入中文

### ISSUE THREAD

**Issue by lishiyanlishiyan** [ant-design/ant-design-mobile#5711]
### Version of antd-mobile

5.0.1

### Operating system and its version

ios15.2

### What happened?
https://rn.mobile.ant.design/components/modal-cn/
输入法26键 ios下 无法输入中文

https://user-images.githubusercontent.com/43063974/194700092-7d16b7d4-170b-48e5-8028-f5963fe87d06.mov

**Comment by afc163** [comment]
给个重现

**Comment by lishiyanlishiyan** [comment]
> 给个重现

官网modal组件 代码演示的Preview 切换为ios就可以看到  需要添加中文键盘

**Comment by afc163** [comment]
5.x 版本里貌似没有提供 Modal.prompt 这个方法。 https://mobile.ant.design/zh/components/modal

**Comment by lishiyanlishiyan** [comment]
> 5.x 版本里貌似没有提供 Modal.prompt 这个方法。 https://mobile.ant.design/zh/components/modal

https://rn.mobile.ant.design/components/modal-cn/  抱歉 是rn.mobile

**Comment by afc163** [comment]
那提错地方了。

**Comment by lishiyanlishiyan** [comment]
> 那提错地方了。

应该在哪里提呢，点rn.mobile官网下面的报告bug 就到这里了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile-rn/issues
