### ISSUE TITLE
日期控件弹出卡顿问题，在部分机型上出现

### ISSUE THREAD

**Issue by baoxiangyang** [ant-design/ant-design-mobile#5712]
### Version of antd-mobile

5.12.6

### Operating system and its version

Android

### Browser and its version

企业微信4.0.16(19901) 内置浏览器

### What happened?

Popup弹出动画卡顿，导致日期框控件卡顿，卡顿时间较长
#### 手机为 OnePlus 7T
![微信图片_20221008154040](https://user-images.githubusercontent.com/17821360/194696186-e2d07025-5f59-41d1-a722-ed8dd54902ef.jpg)
#### 动画打印位置
![微信图片_20221008154033](https://user-images.githubusercontent.com/17821360/194696202-88e60470-1725-4067-a061-bd2251782d62.png)
#### 动画执行时间
![微信图片_20221008154024](https://user-images.githubusercontent.com/17821360/194696226-9d2a1fa6-16b2-4909-8df2-b68c21a144de.png)

**Comment by awmleer** [comment]
看起来这种性能的设备不应该会出现卡顿啊

可以试一下给 Popup 加上 `forceRender={true}`

BTW，你发的“动画执行时间”这张图里的行为是预期的，虽然执行过很多次样式的计算，但是并不会触发 React 组件的重渲染的，react-spring 会直接操作 DOM 的
