### ISSUE TITLE
ImageViewer 图片查看器：提取图片颜色，应用到遮罩层背景色

### ISSUE THREAD

**Issue by luckymore** [ant-design/ant-design-mobile#5713]
### What is this feature about?

逛 twitter 发现个有趣的功能，能否纳入 ant

## ImageViewer
属性 | 说明 | 类型 | 是否必填 | 默认值 | 备注
-- | -- | -- | -- | -- | --
averageColor | 是否取图片平均色，应用到遮罩层的背景色上 | `string` | 否 | - | `simple` \| `sqrt` \| `dominant` (对应取色的三种算法)

## 效果如图：
[🔗链接](https://twitter.com/DailyLoud/status/1578448912527958016/photo/2)
![image](https://user-images.githubusercontent.com/5390013/194705072-48f65828-b822-4334-b553-b88cd3b9dbbc.png)

## 其它
> 有需要的话，就继续调研
- 图像格式支持：能转canvas的应该都支持(图片格式、svg)
- 性能：略

**Comment by zombieJ** [comment]
的确有趣~

**Comment by codedart2018** [comment]
有意思，我觉得ImageViewer可以更丰富些，做社交用得上！

**Comment by afc163** [comment]
可以做个 demo 先

**Comment by atom-shanghai** [comment]
支持

**Comment by luckymore** [comment]
@afc163 嗯嗯，估计下周能提代码

https://user-images.githubusercontent.com/5390013/194755296-0f92af02-8bf8-4ed0-a909-00f50b2354dc.mp4

**Comment by codedart2018** [comment]
> @afc163 嗯嗯，估计下周能提代码
> 
>  Jietu20221009-194527.mp4

niubity plus

**Comment by luckymore** [comment]
> 可以做个 demo 先

@afc163 功能实现了，大佬抽空给审查下，有没有什么偏差
https://github.com/luckymore/ant-design-mobile/tree/feat/image-viewer-average-color

**Comment by luckymore** [comment]
#5765
