### ISSUE TITLE
NavBar组件back参数期望修改成ReactNode

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#5714]
### Version of antd-mobile

eg 5.24.0

### What is this feature about?

话不多说，直接上效果图！
![image](https://user-images.githubusercontent.com/12706830/194736864-22a4dcfb-7e7e-492a-90ae-ee331f8c696a.png)

![image](https://user-images.githubusercontent.com/12706830/194736912-dcab823f-8d05-4d11-9253-074d581c53f4.png)
这样虽然也能 渲染，但是类型报错警告就不舒服了！

**Comment by afc163** [comment]
来个 PR
