### ISSUE TITLE
FloatingBubble 支持提供拖动后的偏移值，支持刷新页面回绑

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#5717]
### Version of antd-mobile

5.24.0

### What is this feature about?

FloatingBubble浮动气泡支持提供拖动后的偏移值，支持刷新页面回绑，
有些场景，需要多个页面进入的位置一致，最后拖动位置需要存储。

加如下属性来支持特性

| 属性       | 描述                                     | 类型                           | 默认值  |
|----------|----------------------------------------| ------------------------------ |------|
| defaultOffset | 默认偏移位置                                                                         | `{ x: number; y: number;}`                  | `{ x: 0, y: 0 }` |
| onDragEnd     | 拖动结束回调                                                                         | `(offset:{ x: number; y: number;}) => void` | -                |

## Ref

| 属性   | 说明             | 类型                                                  |
| ------ | ---------------- | ----------------------------------------------------- |
| dragTo | 拖动到指定位置   | `(x: number, y: number, immediate?: boolean) => void` |
| offset | 当前拖动偏移位置 | `{ x: number; y: number;}`                            |

**Comment by miracles1919** [comment]
感觉是想变成受控组件，看看有啥问题不 @awmleer @zombieJ

**Comment by liangskyli** [comment]
问下，这个问题有结论了没？

**Comment by awmleer** [comment]
@miracles1919 受控组件你是说 x 和 y 受控么，那性能会有比较大的问题

**Comment by awmleer** [comment]
`defaultDragOffset` 其实有点容易和 `--initial-position-bottom` `--initial-position-left` 这些 CSS 变量混淆（当然他们作用和含义是完全不同的）

其实我比较倾向通过 Ref 加个类似于 `dragTo` 的方法：

```ts
dragTo: (x: number, y: number, immediate?: boolean) => void
```

```tsx
useEffect(() => {
  floatingBubbleRef.dragTo(x, y, true)
}, [])

<FloatingBubble ref={floatingBubbleRef} />
```

这样的话用途更广泛一些，不仅可以用来解决这个 issue 里提到的问题，还能用来手动让 FloatingBubble 归位

甚至，还可以直接把 x, y 暴露在 ref 上，这样就不需要手动监听 `onDragEnd` 然后手动存储 x y 的值了

**Comment by liangskyli** [comment]
我改成Ref了，再看下

**Comment by miracles1919** [comment]
```jsx
useEffect(() => {
  floatingBubbleRef.dragTo(x, y, true)
}, [])
```

我试了下偶尔会闪一下，感觉需要一个初始值 @awmleer 

https://github.com/ant-design/ant-design-mobile/blob/master/src/components/floating-bubble/floating-bubble.tsx#L42-L43

```tsx
useSpring(() => ({
    x: defaultOffset.x,
    y: defaultOffset.y,
  }))
```

**Comment by liangskyli** [comment]
代码优化了些，加了初始值，后面设置是会存在闪动的问题，我之前没用Ref也考虑这个问题

**Comment by awmleer** [comment]
@miracles1919 `useLayoutEffect` 试试？

**Comment by miracles1919** [comment]
@awmleer `useLayoutEffect` 是可以的，但 SSR 场景下或有 warning 的 ~

**Comment by awmleer** [comment]
噢确实

而且如果是多页应用的话，应该也没办法在离开页面的时候去读取 ref 的值

**Comment by awmleer** [comment]
那感觉全都要也可以……成年人不做选择，想用哪个 API 就用哪个

**Comment by liangskyli** [comment]
我把onDragEnd也加上吧，多一个方法使用，避免没办法在离开页面的时候去读取 ref 的值

**Comment by miracles1919** [comment]
#5718
