### ISSUE TITLE
【期待antM达到antd的timepicker的效果】

### ISSUE THREAD

**Issue by shuohe123** [ant-design/ant-design-mobile#572]
#### 本地环境

- antd-mobile 版本：0.9.9
- 操作系统及其版本：ios
- 浏览器及其版本：chrome

#### 你做了什么？
现阶段antM没有timepicker主键，不能支持时间分片禁用。
![kkk](https://cloud.githubusercontent.com/assets/23718507/20620175/613e6d60-b333-11e6-9006-cae51763590c.png)

#### 你期待的结果是：
期待antM达到antd的timepicker的效果
<img width="428" alt="2016-11-24 6 06 56" src="https://cloud.githubusercontent.com/assets/23718507/20620258/cfc1bef4-b333-11e6-8b51-6a8eadb9e054.png">

<img width="859" alt="2016-11-24 6 07 53" src="https://cloud.githubusercontent.com/assets/23718507/20620337/2ca3351c-b334-11e6-848c-637713514c8b.png">

**Comment by warmhug** [comment]
@afc163 能否整理下核心逻辑，ui 部分独立点，也能方便这里用 https://github.com/react-component/time-picker

**Comment by afc163** [comment]
具体怎么独立，可以明确一点。

**Comment by warmhug** [comment]
@shuohe123 基于 https://github.com/react-component/time-picker 这个自己在业务中实现、或者建议业务改交互。这样的组件不常用、不适合放到 antd-mobile 里。
