### ISSUE TITLE
antd-mobile从v2升级到v5之后 yarn start报错 提示./node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js Module parse failed: Unexpected token (306:11) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by liuyafeis** [ant-design/ant-design-mobile#5720]
### Version of antd-mobile

5.24.0

### Operating system and its version

Android

### Browser and its version

antd-mobile 版本 5.24.0
antd-mobile-v2 版本 2.3.4

![image](https://user-images.githubusercontent.com/22736992/194972400-9ef6a7c9-9839-4538-a8c7-a2b9e1ba7994.png)

**Comment by miracles1919** [comment]
可以将你的项目打个 zip 发到这里，帮你排查一下

**Comment by afc163** [comment]
原来 pending 标签是做这个用的。

**Comment by liuyafeis** [comment]
> 可以将你的项目打个 zip 发到这里，帮你排查一下

切到"antd-mobile": "5.4.0"版本正常运行了，只要"5.5.0"及之上版本就不行，肯定是这个版本出了问题

**Comment by miracles1919** [comment]
检查下 `bable-loader` 的 test 配置是否命中了 `.mjs`，感觉是这个问题

等有复现包了再帮你排查，这个 issue 我先关了

**Comment by WEIXii** [comment]
你好，我也遇到了找个问题，请问找到解决方法了吗？
