### ISSUE TITLE
Cascader、TreeSelect级联选择器期望支持多选

### ISSUE THREAD

**Issue by GitVitality** [ant-design/ant-design-mobile#5725]
### What is this feature about?

交互设计可参考上图
![lQDPJxbEiCHj2lLNBQDNAtCwobpi90C0_ncDQxBfH8CRAQ_720_1280](https://user-images.githubusercontent.com/14938077/195022029-8ccc5cf5-9ab9-4038-a60d-a8d818280d3d.jpg)

**Comment by zombieJ** [comment]
需求已同步设计师，待设计稿反馈。

**Comment by zombieJ** [comment]
Update. 设计师认为移动端展示区域有限，多选很难清晰展示。暂无计划支持。

**Comment by SolitaryScripter** [comment]
多选希望可以支持一下，不是ui的问题，难道手机上就不能多选了吗。。。
![截屏2023-09-26 15 34 31](https://github.com/ant-design/ant-design-mobile/assets/22770979/3372385e-3c06-4643-9581-6adc0ee1a747)
多选可以存在多个右边✅的选中台，上面的tab切换也能提供跨类别的选择

**Comment by xiaohua001** [comment]
很有多选的必要哦~

**Comment by selye** [comment]
你们是怎么解决级联多选的问题的。。。

**Comment by selye** [comment]
期望支持多选的情况
