### ISSUE TITLE
FloatingBubble 组件添加用于监听x、y轴变化方法

### ISSUE THREAD

**Issue by ikangjie** [ant-design/ant-design-mobile#5736]
### What is this feature about?

感谢作者为开源做出的贡献

添加一个onChange方法，回调 x、y值，用于实现气泡的位置记忆功能，其特性类似 vConsole 插件

**Comment by liangskyli** [comment]
这个应该和我提的一样的功能， #5717

**Comment by miracles1919** [comment]
#5718
