### ISSUE TITLE
`Form` 组件在不同的 `layout` 布局下，`label` 的字体大小不同

### ISSUE THREAD

**Issue by MuxinFeng** [ant-design/ant-design-mobile#5740]
### Version of antd-mobile

5.24.0

### What happened?

![image](https://user-images.githubusercontent.com/46584765/196083325-33d650d8-c48a-4c42-bbf7-c0845dc34e14.png)
<img width="693" alt="image" src="https://user-images.githubusercontent.com/46584765/196083580-07497435-40b1-4f8d-8bd6-ae2743913e0b.png">

 请问是设计如此还是这里的 `font-size` 需要再调整下

**Comment by zombieJ** [comment]
多谢反馈，设计如此哈。垂直会比水平更小一些哈~
