### ISSUE TITLE
关于`Form.Item`的`childElementPosition `属性的兼容性讨论

### ISSUE THREAD

**Issue by MuxinFeng** [ant-design/ant-design-mobile#5744]
### Version of antd-mobile

5.24.0

### Description

目前`Form.Item`的`childElementPosition `属性是通过`justify-content`特性实现的，但是这个特性的[兼容性比较差](https://caniuse.com/?search=justify-content)，在企业微信之类的内置浏览器里无法生效，是否可以用`float`实现呢~
<img width="480" alt="image" src="https://user-images.githubusercontent.com/46584765/196142300-5decdb33-28bb-4780-9e91-01afa2fc7f24.png">

**Comment by miracles1919** [comment]
> justify-content 兼容性比较差

这个结论是怎么得出来的... ? 

![image](https://user-images.githubusercontent.com/22469543/196151757-16a8ae5e-855a-4396-8159-6b134e640838.png)

**Comment by MuxinFeng** [comment]
![image](https://user-images.githubusercontent.com/46584765/196154465-a351ee87-765c-48fb-9354-4b47357f9711.png)
例如这里，我理解为从 chrome106 版本才支持这个特性，然后我找了两个安卓机，企微浏览器的版本在 chrome89 这样子，所以这个特性没生效。我这样理解有啥问题不...

**Comment by MuxinFeng** [comment]
手机浏览器内核版本查看工具 https://ie.icoa.cn/

**Comment by miracles1919** [comment]
> 我理解为从 chrome106 版本才支持这个特性，我这样理解有啥问题不...

不是的，Chrome for Android 只保留了最新的版本，[理由见这里](https://github.com/Fyrd/caniuse/issues/2413#issuecomment-206673558) 

从 [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#browser_compatibility) 上看，chrome 29 就完全支持了

**Comment by MuxinFeng** [comment]
感谢大佬的解答，我发现是我弄错版本了（写 demo 的时候才发现），这个问题已经被您修复好了https://github.com/ant-design/ant-design-mobile/pull/5102

**Comment by MuxinFeng** [comment]
我还一直疑惑来着，是什么操作把`justify-content: flex-end;`编译成`justify-content: right;` 😭
