### ISSUE TITLE
form -》form.item中使用Picker组建

### ISSUE THREAD

**Issue by Julycc41** [ant-design/ant-design-mobile#5747]
### Description

form.item中使用Picker组建，设置默认值的时候打印value 一直为[null]
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/80231740/196576172-34bd4fad-5ba5-4afd-a6db-24c86d0f0f00.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/80231740/196576235-8435f5aa-eb86-4f1a-8225-d38bbc00aecf.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/80231740/196576258-777d4bbd-999f-436d-b95a-831929182620.png">

**Comment by MuxinFeng** [comment]
建议写个 demo，方便调试~
我觉得获取 value 的方式有些奇怪 😂

**Comment by zqran** [comment]
可以给出一个复现的 demo：[codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx)~

**Comment by IronKinoko** [comment]
从截图上可以看出 `Form` 的 `initialValues` 填写错误导致出现预期外的结果

`Picker` 组件的 `value` 字段声明
```ts
type PickerValue = string | null
interface PickerProps {
  value?: PickerValue[] | undefined;
}
```

所以 `Form` 的 `initialValues` 应该填 `initialValues={{ timeType: [ '早上' ] }}`

具体可以查看[这个例子](https://codesandbox.io/s/confident-bessie-5q3ijx?file=/src/App.tsx)
