### ISSUE TITLE
Button子组件里的事件触发不了

### ISSUE THREAD

**Issue by tianleiwufeng** [ant-design/ant-design-mobile#5749]
### Version of antd-mobile

5.24.1

### Operating system and its version

iOS

### Browser and its version

chrome

### Sandbox to reproduce

https://codesandbox.io/s/react-project-forked-dvq37p

### What happened?

点击Button子元素的事件无法触发，换成原生的button可以

**Comment by MuxinFeng** [comment]
请问下这是什么场景呢

**Comment by tianleiwufeng** [comment]
chrome浏览器就会出现哈，你想表达的意思是？

**Comment by MuxinFeng** [comment]
你的 demo 能成功复现这个问题，但我比较好奇的是，点击事件绑定在 button 能不能满足你的需求

**Comment by MuxinFeng** [comment]
我感觉使用场景特别少或者可以通过其他办法实现的特性，维护者们可能不会把它放到一个很高的优先级，所以你可以讲讲你的场景

**Comment by tianleiwufeng** [comment]
确实场景比较少，我就是很好奇是在哪一步卡掉了里面的事件，以及有什么办法可以规避这个

**Comment by miracles1919** [comment]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/22469543/196939313-7dcdaa56-57ba-4ffe-826c-5bb95d61c062.png">

这里有个蒙层，感觉设计如此... 就像上面说的，什么样的场景需要在 Button 子元素里点击？

**Comment by MuxinFeng** [comment]
验证了一下，确实是这个蒙层的问题，要不要调整一下蒙层的 z-index

**Comment by MuxinFeng** [comment]
必要性：
从使用场景上来说，能不能触发子元素的事件感觉都可以；但从用户预期来说，感觉还是要加上，因为大家会下意识的觉得 `antd` 系列的组件库应该保持一致，然后 `ant-design` 那边是可以的触发的。

解决方案：
上面提到的改变蒙层的 `z-index` 可能会产生负作用，用 `pointer-event` 会更合适些(ant-design 也是这种做法)，大佬觉得呢 @miracles1919

**Comment by miracles1919** [comment]
我感觉有具体的场景再去讨论会比较好，现在看起来没什么问题.. 所以这个 issue 我先关了，有问题可以再讨论
