### ISSUE TITLE
使用Card组件,报错：Expected a component class

### ISSUE THREAD

**Issue by ssjjnn** [ant-design/ant-design-mobile#575]
#### 本地环境

- antd-mobile 版本：0.9.8
- 操作系统及其版本：iOS
- 浏览器及其版本：chrome 版本 54.0.2840.71 (64-bit)

#### 你做了什么？

![image](https://cloud.githubusercontent.com/assets/22025844/20655775/de3252da-b560-11e6-9580-40f2bfd21750.png)
![image](https://cloud.githubusercontent.com/assets/22025844/20655835/62182ab6-b561-11e6-9df0-0cb8ad81c5c4.png)

command点进去是index.d.ts文件，红框下面其他几个组件没什么问题

![image](https://cloud.githubusercontent.com/assets/22025844/20655878/d391799a-b561-11e6-83c6-9207d099a4c8.png)

**Comment by silentcloud** [comment]
@ssjjnn 你这是跑的 react-native 环境，怎么会出现 `div` 标签？换 `Text`
