### ISSUE TITLE
form.validateFields始终都会走catch吗？

### ISSUE THREAD

**Issue by larryspace** [ant-design/ant-design-mobile#5752]
### Version of antd-mobile

5.21.0

### Description

我想实现一个表单提交按钮默认为disabled状态的，表单通过验证后enable
在form.onValuesChange时调用form.validateFields来检查是否有未通过校验的字段
但是发现不管有没有通过校验，即使 errorFields为空，也会抛异常

**Comment by zqran** [comment]
你要实现的效果是类似 [antd Form 内联登录栏](https://ant.design/components/form-cn/#components-form-demo-inline-login) 这种效果吗？
如果是的话，可以参考 antd 的示例用法~

**Comment by zombieJ** [comment]
`onValuesChange` 里触发校验会使上一次校验变成 `outOfDate`，校验永远都会以最新的为准，老的没跑完都会标记为 failed。
