### ISSUE TITLE
Add others in Modal.alert

### ISSUE THREAD

**Issue by ruoru** [ant-design/ant-design-mobile#5753]
### Version of antd-mobile

2.3.4

### What is this feature about?

It is not easy to use because it does not support many interfaces. It is recommended to add the fifth parameter `others` and destruct it in the Modal component.

like:

```js
- Modal.alert(title, message, actions?, platform?)
+ Modal.alert(title, message, actions?, platform?, others?)

...

<Modal
  ...
+  ...others
/>
```

**Comment by miracles1919** [comment]
v2 is out of maintenance, you can consider upgrading v5，ref: https://mobile.ant.design/zh/guide/migration
