### ISSUE TITLE
希望支持小程序 Taro For React平台

### ISSUE THREAD

**Issue by DreamPWJ** [ant-design/ant-design-mobile#5757]
### What is this feature about?

微信小程序大面积流行，体验和使用率都有超过H5的趋势，面向未来应该考虑支持小程序运行，打造移动端第一UI库.

**Comment by miracles1919** [comment]
暂时没这个计划哈

<img width="506" alt="image" src="https://user-images.githubusercontent.com/22469543/197333817-8b982696-bafc-4d24-8f7e-12348776fcf8.png">

**Comment by dzcpy** [comment]
用taroify吧，这个不行

**Comment by jsLWQ** [comment]
> 用taroify吧，这个不行

不维护了吧
