### ISSUE TITLE
modal 点击黑幕无法隐藏

### ISSUE THREAD

**Issue by zavven** [ant-design/ant-design-mobile#576]
#### 本地环境

- antd-mobile 版本：0.9.6
- 操作系统及其版本：macOS sierra 10.12.1
- 浏览器及其版本：chrome  54.0.2840.98 (64-bit) 开发工具下模拟ios设备，xcode 模拟器

#### 你做了什么？

引入官网的例子：modal对话框，可关闭示例。

#### 你期待的结果是：

点击黑幕，modal对话框隐藏。

#### 实际上的结果：

点击黑幕，对话框没有隐藏。（浏览器正常模式访问没有问题，模拟安卓设备没有问题）

#### 可重现的在线演示

官网上的demo：用chrome的开发者工具模拟ios设备，官网上的demo也无法正常工作。

**Comment by silentcloud** [comment]
@zavven 用最新版试试，我这边没问题

**Comment by ibufu** [comment]
version:1.0.0-alpha.26,同样的问题
@silentcloud

**Comment by motorguo** [comment]
```
"antd-mobile": "^0.9.11"
```
@warmhug Modal Web 在 IOS 点击蒙层 `maskClosable` 无法关闭。

[demo](https://mobile.ant.design/kitchen-sink/modal/)

**Comment by warmhug** [comment]
@motorguo 不用看这个 demo，有点老。你本地重装 node_modules ，没问题的

**Comment by motorguo** [comment]
@warmhug 感谢你的回复！就刚刚我尝试  ` rimraf node_modules `, 通过 `cnpm` 重装，**IOS** 下还是不行。
```
"antd-mobile": "^0.9.11"

// 应该跟版本无关吧
node v6.2.0 
cnpm 4.4.2
npm 3.8.9
```

**Comment by eclanp** [comment]
我也遇到这个问题，在web页面不开启模拟器可以正常关闭，开启模拟或者直接在手机上测试，就不行。目前测试了iphone5s/iphone6s，都一样不能关闭。

**Comment by warmhug** [comment]
@eclanp @motorguo 确认用了 fastclick ，没用会有问题。

**Comment by motorguo** [comment]
@warmhug 还要单独引用这个库 `fastclick`  么？

**Comment by warmhug** [comment]
先再确认下官方 demo 在你们的环境里有没这个问题。

fastclick 正常不是必须的，但现在有些问题还没解决。麻烦先引入 fastclick 、并正确绑定 dom 里，参考下 官方 demo 里 fastclick 用法；再确认下有没能解决你们这个问题。

**Comment by eclanp** [comment]
@warmhug 引入 react-fastclick后一切正常了。谢谢！

**Comment by motorguo** [comment]
@warmhug 感谢，明天试下。

**Comment by warmhug** [comment]
注意，不要使用 [react-fastclick](https://www.npmjs.com/package/react-fastclick) (有 bug)，要用这个 [fastclick](https://github.com/ftlabs/fastclick)

**Comment by motorguo** [comment]
`ok`

**Comment by kpaxqin** [comment]
@warmhug 
fastclick现在仍然是必需的吗？我发现引用fastclick后在iOS webview、chrome桌面版点击input元素focus有时无反应，去掉fastclick后正常

**Comment by warmhug** [comment]
@kpaxqin 在另一个 issue 跟进你说的这个问题，这个 issue 有点老了 lock 掉
