### ISSUE TITLE
README 里的钉钉二维码是否已经失效？

### ISSUE THREAD

**Issue by xhwgood** [ant-design/ant-design-mobile#5760]
### Description

还有官网的钉钉二维码，https://mobile.ant.design/zh/guide/quick-start
建议更新下
感觉 figma 资源里的组件和实际的组件区别还是有点大啊，比如图片查看器里会有左上角的左箭头，但实际组件里没有左箭头
![image](https://user-images.githubusercontent.com/39004078/197467396-67c7f1f6-ebd0-4ec6-8843-3761423b37fe.png)

**Comment by miracles1919** [comment]
二维码 #5758
