### ISSUE TITLE
使用FloatingPanel后，页面无法滚动

### ISSUE THREAD

**Issue by pengxueshan** [ant-design/ant-design-mobile#5761]
### Version of antd-mobile

5.24.1

### Description

使用FloatingPanel后，整个页面scroll失效（在body上加了adm-overflow-hidden类名），有办法让body的滚动不失效吗？

**Comment by pengxueshan** [comment]
close

**Comment by hellowuxin** [comment]
怎么解决的？

**Comment by Chinvaejay** [comment]
> 怎么解决的？

滚动没问题, 但是移动端的touch不行

在body上加adm-overflow-hidden类名只是一个方面

```ts
  const lock = () => {
    document.addEventListener('touchstart', touch.start)
    document.addEventListener(
      'touchmove',
      onTouchMove,
      supportsPassive ? { passive: false } : false
    )

    if (!totalLockCount) {
      document.body.classList.add(BODY_LOCK_CLASS)
    }

    totalLockCount++
  }
```

![Image](https://github.com/user-attachments/assets/8acf5e6a-c400-4c13-bc99-56659a24014e)

`ant-design-mobile/src/components/floating-panel/floating-panel.tsx`
如果这里的true改为prop传递就好了

![Image](https://github.com/user-attachments/assets/b69d7deb-23f9-4da3-abcf-f1c4c4f1bef0)
