### ISSUE TITLE
Mask Popup组件里套Popover组件，导致点击组件外其他地方无法关闭

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#5762]
### Version of antd-mobile

eg 5.24.0

### Operating system and its version

Others

### Browser and its version

chorme

### What happened?

![image](https://user-images.githubusercontent.com/12706830/197699430-d7768c7d-1eb5-4a0d-bbc9-64f33e3e8bf8.png)
上面只有点击，送多少朵选择框才会正常显示或关闭popover组件。如果不使用mask或popup组件包裹的情况下则正常。只要一包裹就出问题。如果点击mask 或　popup组件内容之外区域就会关闭mask或popup但popover内容还悬浮页面中。应该禁止popover事件穿透到下层去。但我用``` stopPropagation={['click']} ``` 没起作用。

**Comment by codedart2018** [comment]
# 我上传了一个视频上来

[礼物墙.webm](https://user-images.githubusercontent.com/12706830/197700494-728dd3a3-aceb-4859-9836-fb72c8725dfb.webm)

**Comment by IronKinoko** [comment]
```diff
<Popup
+ stopPropagation={[]}
 >
</Popup>
```

`Popup` 组件设置 `stopPropagation={[]}` 可以解决问题

现象产生的原因：
`Popover` 的点击事件是挂在 `document` 上的，事件被 `Popover` 底下的 `Popup` 组件默认阻止了 `click` 事件传播，导致 `document` 没有接收到 `click` 事件，没有触发 `Popover` 关闭。
所以从你的视频上看，先是关闭了 `Popup` 再点击才关闭 `Popover`

**Comment by codedart2018** [comment]
> ```diff
> <Popup
> + stopPropagation={[]}
>  >
> </Popup>
> ```
> 
> `Popup` 组件设置 `stopPropagation={[]}` 可以解决问题
> 
> 现象产生的原因： `Popover` 的点击事件是挂在 `document` 上的，事件被 `Popover` 底下的 `Popup` 组件默认阻止了 `click` 事件传播，导致 `document` 没有接收到 `click` 事件，没有触发 `Popover` 关闭。
> 
> 所以从你的视频上看，先是关闭了 `Popup` 再点击才关闭 `Popover`

```
stopPropagation={[]}
```
### 这样确实解决问题了，
但我用
```
stopPropagation={['click']}
```
就不生效，当时我看参数只有click 我默认给了click反而不生效。
