### ISSUE TITLE
请教个ReactNative的问题

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#577]
#### 本地环境

- antd-mobile 版本：0.9.9
- 操作系统及其版本：mac
- 浏览器及其版本：android 4.4.4

#### 你做了什么？

根据ReactNative的Android的打包教程生成的apk安装后第一次启动运行正常，结束该apk的进程或者手机重启后再次打开，显示白屏，后黑屏，最后提示无响应

烦请各位大牛有空帮忙分析一下

#### 实际上的结果：
根据ReactNative的Android的打包教程生成的apk安装后第一次启动运行正常，结束该apk的进程或者手机重启后再次打开，显示白屏，后黑屏，最后提示无响应

**Comment by silentcloud** [comment]
装的是 release 的包？这样简单的描述，没办法帮忙分析的

**Comment by liubin1023** [comment]
谢了，知道问题出在哪里了，是和一个第三方的包有些冲突
