### ISSUE TITLE
TextArea 期待暴露出它textarea 原生标签的style或className出来

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design-mobile#5772]
### Version of antd-mobile

eg 5.24.1

### What is this feature about?

# 先上传个视频看需求。
[积恋.webm](https://user-images.githubusercontent.com/12706830/198497935-ab7bd6e1-82ec-4ae1-99f4-24f2c807611a.webm)

#### 我需要在选择话题后，计算出话题所占用的空间，然后给textarea style text-indent 给上我计算出来的宽度。但现在的AreaText组件是无法给到textarea原生标签样式的。只能给到外围包起来。
所以现在期望给出原生textarea标签的style or class props出来。这样方便我们操作。视频当中的 text-indent 是我手动给上的。
<img width="788" alt="image" src="https://user-images.githubusercontent.com/12706830/198498307-00fc358e-9d35-41fc-abea-81144bd84051.png">
## 这显示是我们想要的需求。

**Comment by miracles1919** [comment]
你也可以给 `TextArea` 加一个 class

```less
.class {
  textarea {
    // ...
  }
}
```

**Comment by codedart2018** [comment]
> 你也可以给 `TextArea` 加一个 class
> 
> ```css-less
> .class {
>   textarea {
>     // ...
>   }
> }
> ```

加class没用　我要动态style。话题dom width不是固定的。可能5个字的话题是50px 但是10个字的话题可能是100px　我要动态设置　textarea 的　text-idtend 来达到首行顶出的距离，以保证用户话题内容正常输入！

**Comment by miracles1919** [comment]
这样的话可以通过 ref 获取原始 textarea，直接设置 style

`ref.current.nativeElement`
