### ISSUE TITLE
antd-mobile真机测试报红

### ISSUE THREAD

**Issue by haiifeng** [ant-design/ant-design-mobile#578]
#### 本地环境

- antd-mobile 版本：0.9.10
- 操作系统及其版本：华为荣耀4X 安卓4.4.4
- 浏览器及其版本：react 15.4.0；react-native 0.38.0

#### 你做了什么？

引入 antd-mobile 的 Button
#### 你期待的结果是：

- 像官网一样正常显示，出现start按钮

#### 实际上的结果：

- 红屏：Unknow named module:'antd-mobile

#### 可重现的在线演示
 - 无法重现
-  真机测试

**Comment by dianjie** [comment]
认真看文档：[按需引入](https://mobile.ant.design/docs/react/introduce#使用)

**Comment by warmhug** [comment]
#56

**Comment by haiifeng** [comment]
@dianjie 
通过init来引入的antd-mobile，看实例特别卡，而且native不用没有必要配置webpack。文档里写的不清楚，究竟是移动端web还是native，还是两者都是。
直接在自己的项目中引入antd-mobile红屏报错，这个看文档，可是看不出来为什么的。

**Comment by warmhug** [comment]
文档在持续不断优化，请关注更新：https://mobile.ant.design/docs/react/introduce#使用

**Comment by smalltide** [comment]
我目前這樣搭配可以運行
https://github.com/smalltide/react-native-antd
