### ISSUE TITLE
[NoticeBar] 希望文字超长时是否滚动受控，可以折行

### ISSUE THREAD

**Issue by GOWxx** [ant-design/ant-design-mobile#5796]
### Version of antd-mobile

5.25.1

## demo:
https://codesandbox.io/s/modern-currying-rdh0if?file=/src/App.tsx

如图
- 超长文字没有属性控制是否折行
- `speed` 值为 `0` 时会导致文字内容不展示
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/12870715/200514970-f4d2b1f1-ff29-483f-8578-b8857d49054f.png">

## expectation:

- 超长文字不滚动
- 超长文字可以折行

![image](https://user-images.githubusercontent.com/12870715/200513814-a6795563-5b26-4c3e-8da3-a0bfdac7b1ad.png)

**Comment by miracles1919** [comment]
可以加个 `wrapable` 属性开启多行展示

**Comment by afc163** [comment]
speed={0} 应该就够了，不需要单加属性了。

**Comment by miracles1919** [comment]
@afc163 我觉得两个的语义是不一样的

比如下面这个例子，本身就不会滚动，但它是需要换行的，虽然通过 `speed={0}` 是可以做到换行，但是用起来怪怪的

```jsx
<NoticeBar
  content={
    <>
      <div>1</div>
      <div>2</div>
    </>
  }
/>
```

**Comment by afc163** [comment]
确实，现在竟然不支持

```
    <>
      <div>1</div>
      <div>2</div>
    </>
```
