### ISSUE TITLE
Tabs APP型选项卡能自适屏幕大小吗？

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design-mobile#58]
#### 本地环境

- antd-mobile 版本：0.7.x
- 操作系统及其版本：
- 浏览器及其版本：谷歌

#### 你做了什么？
`  <Tabs type="tabbar" mode="dark" defaultActiveKey="1" >
          <TabPane tab={<span><Icon type="home" />首页</span>} key="1"><div style={{ width: '100%', height:"100%" }}>sdfsdfsdf</div></TabPane>
          <TabPane tab={<span><Icon type="team" />好友</span>} key="2">选项好友内容</TabPane>
          <TabPane tab={<span><Icon type="setting" />设置</span>} key="3">选项设置的内容</TabPane>
        </Tabs>`

#### 你期待的结果是：
TabPane 能自适应大小

**Comment by silentcloud** [comment]
@ksh033 目前是自适应大小的

**Comment by ksh033** [comment]
@silentcloud 用type="tabbar"时标签标题都不会到屏幕底部，是不是需要再设置什么样式

**Comment by silentcloud** [comment]
@ksh033 定位到屏幕底部，是需要自己写样式处理的，组件不会帮你做这些，这个属于业务需求了

**Comment by ksh033** [comment]
好的谢谢。我自己样式调整一下
