### ISSUE TITLE
关于国际化

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#580]
#### 本地环境

- antd-mobile 版本：0.9.9
- 操作系统及其版本：mac
- 浏览器及其版本：android 4.4.4  手机qq或微信内置浏览器

#### 你做了什么？

想问下，如果做国际化的话应该怎么弄，使用第三方的nodejs的包，还是要自己开发，你们最近有关于这方面的计划没

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design-mobile/issues/487
