### ISSUE TITLE
onVirtualKeyboardConfirm	虚拟键盘点击确认时的回调函数  无法使用呢。

### ISSUE THREAD

**Issue by lioyiphy** [ant-design/ant-design-mobile#5801]
### Version of antd-mobile

5.0.1

### Description

onVirtualKeyboardConfirm	虚拟键盘点击确认时的回调函数  无法使用呢。
onChange的函数时可以用的，但是这个不可以用呢。

**Comment by miracles1919** [comment]
你说的是哪个组件？
