### ISSUE TITLE
TextArea在更新完版本后  show-count异常

### ISSUE THREAD

**Issue by heyuan374** [ant-design/ant-design-mobile#5802]
### Version of antd-mobile

5.25.1

**Comment by GOWxx** [comment]
v2 已停止维护了，可以考虑升级一下：https://mobile.ant.design/zh/guide/migration

**Comment by heyuan374** [comment]
对，目前升级到了5.25.1，但是原属性 show-count 异常，之前是show-count = ‘false’ ，我目前不使用是不是也可以
