### ISSUE TITLE
ImageUpload 删除图片

### ISSUE THREAD

**Issue by Frank17008** [ant-design/ant-design-mobile#5813]
### Version of antd-mobile

5.25.1

### Operating system and its version

Others

### Browser and its version

PC Chrome:  107.0.5304.107

### Sandbox to reproduce

https://codesandbox.io/s/lthlhj?file=/app.tsx&resolutionWidth=375&resolutionHeight=700

### What happened?

复现环境：
官方demo(限制图片数量)  http://ant-design-mobile.antgroup.com/zh/components/image-uploader#%E5%B1%9E%E6%80%A7
问题：上传多张图片时，若不按倒序删除，会出现最后一张图片展示错误；如上传了【1，2，3】,先删除1或者2会导致图片3展示失败

**Comment by IronKinoko** [comment]
demo 里的上传是使用 `URL.createObjectURL(file)` 生成 blob 资源, 节点删除的时候 `PreviewItem` 组件执行了`URL.revokeObjectURL(src)` 把本地生成的 `blob` 资源释放了，所以最后一张图片就裂了

https://github.com/ant-design/ant-design-mobile/blob/4577154691130c792a945b70d3428566c13c9cfb/src/components/image-uploader/preview-item.tsx#L25-L39
