### ISSUE TITLE
怎么处理swiper组件对图片预览组件的影响

### ISSUE THREAD

**Issue by SingleShadow** [ant-design/ant-design-mobile#5825]
### Version of antd-mobile

5.25.1

### Operating system and its version

Others

### Browser and its version

Google Chrome 105.0.5195.102

### Sandbox to reproduce

https://codesandbox.io/s/dreamy-brook-0c8xpd

### What happened?

在swiper中使用ImageViewer.Multi，图片预览组件的定位异常，应该是swiper影响的

项目场景的dom结构是
<tabs />
<swiper>内容区<swiper />

现在的需求是要在内容区使用图片预览组件

**Comment by 1587315093** [comment]
用法很奇怪。。
