### ISSUE TITLE
安卓机型input 会被键盘遮挡 页面不会被推起 

### ISSUE THREAD

**Issue by gdc1998** [ant-design/ant-design-mobile#5844]
### Version of antd-mobile

antd-mobile @5.26.0

**Comment by hxmhxm1** [comment]
同样是android手机中input框被键盘遮挡，通过如下方式解决
const [isFocus, setIsFocus] = useState(false);
const feedbackRef = useRef<HTMLDivElement>(null);

const handleFocus = () => {
  if (!isEmpty(feedbackRef.current)) {
    setIsFocus(true);
    setTimeout(() => {
      feedbackRef.current!.scrollIntoView({
        behavior: "smooth",
        block: "end",
      });
    }, 500); // 延迟是为了等待键盘弹起
  }
};

const handleBlur = () => {
  setIsFocus(false);
};

<Input
  style={{
    background: "white",
    borderRadius: 8,
    padding: 12,
    fontSize: 12,
    marginBottom: isFocus ? 400 : 0
  }}
  placeholder="请输入联系方式"
  onChange={(value) => contact.current = value}
  onFocus={isIOS ? undefined : handleFocus}
  onBlur={isIOS ? undefined : handleBlur}
/>
