### ISSUE TITLE
ImageUploader 在form中使用

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-mobile#5848]
### Version of antd-mobile

^5.26.0

### What is this feature about?

<img width="931" alt="image" src="https://user-images.githubusercontent.com/27960630/205002405-8e63dec5-099c-4e37-93bb-0b43710c524a.png">
upload属性 改成不必传 我希望是beforeUpload拿到File 直接传OSS拿到地址后 最后和表单一起提交  类似antd的Upload

**Comment by miracles1919** [comment]
> 我希望是beforeUpload拿到File 直接传OSS拿到地址后 最后和表单一起提交

这段逻辑用 upload 处理呢

**Comment by lovesL** [comment]
了改
