### ISSUE TITLE
不是react-navtive可以使用antd-mobile吗？

### ISSUE THREAD

**Issue by yqwoe** [ant-design/ant-design-mobile#585]
#### 本地环境

- antd-mobile 版本：
- 操作系统及其版本：
- 浏览器及其版本：

**Comment by warmhug** [comment]
可以，支持 web 和 rn

**Comment by yqwoe** [comment]
@warmhug 有没有demo呢？我老是跑不起来

**Comment by warmhug** [comment]
#56 和 文档 https://mobile.ant.design/docs/react/introduce#使用
