### ISSUE TITLE
antd-mobile 5.5.0 以上版本引入 floating-ui 导致 antd-mobile 无法支持低版本浏览器 

### ISSUE THREAD

**Issue by f2egxz** [ant-design/ant-design-mobile#5856]
### Version of antd-mobile

^5.5 

### Description

我这边发现 antd-mobile 引用的   floating-ui/core 中使用了对象展开语法。查了下在移动端浏览器这个语法需要 Chrome Android >= 60 才支持，导致低于这个版本的浏览器打开页面报错了。

**Comment by IronKinoko** [comment]
与 #5062 重复

babel 兼容适配查看[文档](https://mobile.ant.design/zh/guide/quick-start#%E5%85%BC%E5%AE%B9%E6%80%A7)
