### ISSUE TITLE
关于Cascader  Picker 这种类似选择的组件 onConfirm onSelect回调的第二个参数都是{} 

### ISSUE THREAD

**Issue by lovesL** [ant-design/ant-design-mobile#5862]
### What is this feature about?

Cascader  Picker 这种类似选择的组件 onConfirm onSelect回调的第二个参数都是{},为啥不能给到当前选择这条option呢  希望能加上吧，虽然自己也能根据选中的key 从数据源里面取出来  但是  如果一个页面有多个类似这样的组件 都需要用到option里面的一些信息 那不得每个都从数据源去取呀

**Comment by li-yu-tfs** [comment]
我这里确实取不到第二个值。。只有选中的value
