### ISSUE TITLE
PullToRefresh能否提供手动触发refresh的能力

### ISSUE THREAD

**Issue by InModeration** [ant-design/ant-design-mobile#5863]
### Version of antd-mobile

5.24.0

### What is this feature about?

类似微博、知乎，底部Tab 激活首页的时候，再次点击首页，会触发下拉刷新。

https://user-images.githubusercontent.com/41774233/205592050-1d4c6ef9-ec77-4f4a-93e1-0549cd2816e2.mp4

希望PullToRefresh提供手动刷新的能力，比如，通过ref调用doRefresh

**Comment by miracles1919** [comment]
不一定要通过 PullToRefresh，可以自己加个 loading

```jsx
{tab 切换 && <Loading />}
<PullToRefresh>{data.map()}</PullToRefresh>
```

--- 

试了下知乎，如果在激活首页的时候，在往下拉，其实会有两个状态

<img src="https://user-images.githubusercontent.com/22469543/205598445-b62b0601-5c00-4510-81ad-fd7d808467a0.png"  width="300px" />

**Comment by InModeration** [comment]
Get，这种方式可行，但这个Loading如果自行开发，感觉会对每个接入的项目都造成一定的冗余。
比如具备和PullToRefresh相同的 pullingText、refreshingText 以及completeText，还是期望后续可以将这点考虑进迭代

**Comment by spadeACE7** [comment]
急需这个功能，就不需要自己再自行去做开发了，集成在PullToRefresh这个组件真的甚好啊
