### ISSUE TITLE
Form.Array operation.remove方法并没有将form 值删除 

### ISSUE THREAD

**Issue by Julycc41** [ant-design/ant-design-mobile#5867]
### Description

当我第一次渲染 Form.Array 只有一条数据的时候 我是想给删除按钮禁用掉，当我进行form.getFieldsValue().contacts.length 进行判断的时候 发现值好像并没有更新    
![1670385257028](https://user-images.githubusercontent.com/80231740/206084330-5acf3fdd-734b-44eb-a9a5-b6022a5ad38b.png)
![1670385312716](https://user-images.githubusercontent.com/80231740/206084429-ae09d83d-0843-4f2b-949c-e9d0d26582bf.png)

**Comment by miracles1919** [comment]
推荐用 `useWatch` 

```tsx
const [form] = Form.useForm<FieldType>()
const contacts = Form.useWatch('contacts', form)

console.log(contacts.length)

```

**Comment by wangxuehao** [comment]
请问最后是怎么解决的呢？
