### ISSUE TITLE
use rc-touchable

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#587]
@ant-design/ant-design-team 

https://github.com/ant-design/ant-design-mobile/commit/f19867571fa33e0e1adf3d2ff2c0b70be9110ba5

**Comment by yiminghe** [comment]
目前还有 action-sheet/modal/popover/segmented-control @silentcloud 

image-picker @pingan1927

**Comment by warmhug** [comment]
跟进新引起的问题，这个关掉
