### ISSUE TITLE
Calendar是否可以支持自定义渲染内容

### ISSUE THREAD

**Issue by qq382724935** [ant-design/ant-design-mobile#5879]
### Version of antd-mobile

5.26.0

### What is this feature about?

日历组件会出现使用签到的场景，需要根据已签到日期自定义渲染天数内容。
比如天数的调整背景，文字等。

**Comment by miracles1919** [comment]
`renderLabel` 能用不

**Comment by qq382724935** [comment]
> renderLabel

这个只能修改标注信息，修改不了adm-calendar-cell或者adm-calendar-cell-top的元素和样式

> `renderLabel`能用不

**Comment by miracles1919** [comment]
能看看你想要的效果不

**Comment by qq382724935** [comment]
> 能看看你想要的效果不

![image](https://user-images.githubusercontent.com/24310904/207997821-e7e914b3-0b81-4024-9f2c-7c5a57ecd3c5.png)
如截图中篮筐所示，已签到需要显示对应的背景色，目前我通过多选模式然后再调整样式可以实现正在进行中的，连续签到的时间范围。但是签到会中断，我要查看历史的签到记录就没办法显示了。

**Comment by qq382724935** [comment]
目前就是多组时间的背景色无法实现，其它的通过其它api或者覆盖antd样式都还能处理出来。

**Comment by qq382724935** [comment]
如图现在是显示1-7号，在显示1-7号的同时，我可能22-24号也要显示。27-30也要显示

**Comment by miracles1919** [comment]
后面应该会开放一个 `renderDate` API

**Comment by qq382724935** [comment]
好的，期待ing

**Comment by wanglihuaya** [comment]
统一大厂呀
