### ISSUE TITLE
NumberKeyboard customKey 多个 不生效

### ISSUE THREAD

**Issue by shzjj82** [ant-design/ant-design-mobile#5881]
### Version of antd-mobile

5.27.0

### What happened?

期望: customKey string｜[string,string]
支持多个自定义按钮

实际: customKey 只能支持第一个参数
`  <NumberKeyboard
        getContainer={null}
        customKey={['.', '-']}
        visible={status}
        onInput={onInput}
        onDelete={onDelete}
        onConfirm={onConfirm}
        showCloseButton={false}
        confirmText='确定'
      />`

**Comment by shzjj82** [comment]
![image](https://user-images.githubusercontent.com/24771532/208408684-5fc2d4af-721b-4a6c-8924-f546e1a8f109.png)

**Comment by shzjj82** [comment]
通过 codesandbox 无法复现问题 但是本地仍然有当前的问题 断点至代码内部  NumberKeyboard 多次执行时 customKey 数量被修改导致最后一次渲染的时候 数量为1 实际customKey数量为2

**Comment by shzjj82** [comment]
建议修改成这样的 const customKeys = Array.isArray(customKey) ? customKey.slice(0) : [customKey];
./components/number-keyboard/number-keyboard.js
![image](https://user-images.githubusercontent.com/24771532/208593221-eda44fcf-4eb1-4639-880d-0100c0cca76c.png)

**Comment by miracles1919** [comment]
没法复现我先关了哈，另外代码优化可以提个 pr 看看

**Comment by a3596287** [comment]
别关，我也发现无法实现重复的customKeys ， 只能显示array的第一个customkeys, 第二个就显示不出来了
