### ISSUE TITLE
Swiper组件能否暴露一个stopPropagation属性？

### ISSUE THREAD

**Issue by FirstClear** [ant-design/ant-design-mobile#5884]
### Version of antd-mobile

5.12.4

### What is this feature about?

当Swiper组件放置于一个可拖拽的组件之上，Drag事件会优先触发在Swiper的父级，希望能够暴露一个stopPropagation，避免这种情况的出现。

**Comment by MuxinFeng** [comment]
是否能给个 demo 呢

**Comment by FirstClear** [comment]
> 是否能给个 demo 呢

```
import * as React from "react";
import Draggable from "react-draggable";
import { Swiper } from "antd-mobile";
import "./App.css";

function App() {
  const swiperItems = [
    <Swiper.Item style={{ height: "100px", backgroundColor: "green" }}>
      first
    </Swiper.Item>,
    <Swiper.Item style={{ height: "100px", backgroundColor: "green" }}>
      second
    </Swiper.Item>,
    <Swiper.Item style={{ height: "100px", backgroundColor: "green" }}>
      third
    </Swiper.Item>,
  ];

  return (
    <div
      className="container"
      style={{ width: "500px", height: "500px", backgroundColor: "blue" }}
    >
      <Draggable bounds=".container">
        <div
          className="parent"
          style={{
            width: "250px",
            height: "250px",
            backgroundColor: "red",
            padding: "10px",
          }}
        >
          <Swiper>{swiperItems}</Swiper>
        </div>
      </Draggable>
      ;
    </div>
  );
}

export default App;
```

**Comment by FirstClear** [comment]
Swiper组件是嵌套在一个可拖拽的Div内的，当Swiper触发内部的Drag事件时也会触发外层Div的Drag，实际上我并不希望拖动Swiper时触发外层的Drag事件，希望能够暴露一个stopPropagation解决该问题

**Comment by MuxinFeng** [comment]
我觉得问题出在 `react-draggable` 这个库。`swiper`里默认做了阻止事件冒泡的处理，见下图
<img width="600" alt="image" src="https://user-images.githubusercontent.com/46584765/208894033-39727b05-75d4-4da6-ba87-370d80a3af2c.png">
另外，你可以试试这个
<img width="576" alt="image" src="https://user-images.githubusercontent.com/46584765/208894290-26050354-769f-471b-a2f1-18a88a629eb7.png">

**Comment by FirstClear** [comment]
我试着调了一下antd-mobile的源码，加上这几个就好了，ClickCapture里仅仅阻止了点击冒泡。拖动事件是通过mouse/touch-up/move/down实现的，如果父容器支持拖动的话，是会出现我这种情况的。或者swiper能否提供一个event Control的属性，让使用者自己控制具体需要阻止冒泡的事件呢？
<img width="954" alt="image" src="https://user-images.githubusercontent.com/32212332/208928711-e42fdf4e-89ca-408a-b990-b691bf4220ca.png">

**Comment by miracles1919** [comment]
可以来个 PR

**Comment by FirstClear** [comment]
> 可以来个 PR
大佬您好，已经提交了一个pr，[feat/add-stopPropagation-to-Swiper](https://github.com/ant-design/ant-design-mobile/pull/5889)，有时间的话，麻烦看下是否有问题
