### ISSUE TITLE
组件 RN 版本兼容性测试记录

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#589]
测试环境 iOS simulator:  10.1，android simulator： 4.4.2

### 0.35
  
  - [x] ActivityIndicator 点击 toast button 无效；(`iOS`, `Android`)
  - [x] Badge 不太圆 (`iOS`)
  - [x] Button (default) 点击后 app 卡死 (`iOS`, `Android`)
  - [x] ActionSheet  带分享功能的操作列表，点击 close ActionSheet 报错； (`Android`)
  - [x] ~~ListView 长列表 “任务 x” 不能固定 (`Android`)~~
  - [x] Modal alet 按钮缺少上边线  (`Android`)
  - [x] InputItem demo 例子无法输入 (`Android`)
  - [ ] ~~SwipeAction 长按无效  (`Android`)，点击不能收回（`iOS`）~~ `单独修复`
  - [x] GridList Android 和 iOS demo 展示不一致；
  - [x] SearchBar 输入的文字偏低；  (`Android`)

### 0.36 （只列出 0.35 没有的）

  - [x] demo app 首页展示问题 （`iOS`、`Android`）
  - [x] Card 样式错乱 (`iOS`, `Android`)
  - [x] Modal transparent 问题 (`iOS`, `Android` )
  - [x] Popup 出不来内容 (`iOS`, `Android`)
  - [x] Carousel 失效；(`iOS`, `Android`)
  - [x] DatePicker、Picker 样式问题  (`iOS`, `Android`)
  - [x] Radio demo 展示错乱； (`iOS`, `Android`)
  - [x] Stepper demo 展示错乱 (`iOS`, `Android`)
  - [x] Switch demo 展示错乱 (`iOS`, `Android`)
  - [x] SwipeAction demo 展示错乱 (`iOS`, `Android`)
  - [ ] ~~Popover 弹出时会闪烁 2 下 (`Android`)~~ `外部库`

### 0.39
  
  - [x] DatePicker、Picker 数据不能滚动 (`Android`) `rmc-picker scrollView 设置了 overflow 引起的，待更新版本`

**Comment by silentcloud** [comment]
@warmhug 一起把这些问题修复了，不然影响使用者使用 rn 新版本特性， 这些问题的修复，先不要直接提交 master，提交到 `fix-and-update-rn` 这个分支上，解决完这些问题之后，再一并合 master

**Comment by silentcloud** [comment]
Popup 出不来内容、Modal transparent 问题有可能是 rc-dialog 的问题，这个最后查

**Comment by warmhug** [comment]
ListView 固定，只在 iOS 上有效

**Comment by silentcloud** [comment]
- [ ] Carousel initialIndex 不对 (`android`)

**Comment by ml1314** [comment]
大概什么时候适配react native的0.38版本

**Comment by silentcloud** [comment]
@ml1314 master 分支已经适配了，正式版为 1.0，不过 1.0 还要等一段时间

**Comment by silentcloud** [comment]
- SwipeAction 长按无效 (Android)，点击不能收回（iOS)

关联到这里修复 #596

**Comment by ml1314** [comment]
react-native 0.35版本的不能使用InputItem （无法输入值），是版本不支持吗？在哪个版本可以用

**Comment by ml1314** [comment]
react-native0.35版本（android）使用DatePicker卡顿半天都出不了时间选择区（出来也无法选择）???这个在哪个版本已经修复了？

**Comment by warmhug** [comment]
![image](https://cloud.githubusercontent.com/assets/2011119/21302410/91cc6718-c5f1-11e6-93e5-a9059a8ff8e6.png)

react-native0.35版本（android）使用DatePicker 测试没问题，重装下 node_modules 试试看 @ml1314

**Comment by ml1314** [comment]
[react-native0.35版本（android）使用DatePicker还是卡顿；InputItem组件能让placeholder和value值像DatePicker组件一样值右对齐
![qq 20161220174947](https://cloud.githubusercontent.com/assets/23412577/21345867/dfca231a-c6dc-11e6-947f-71fe101b8758.png)

**Comment by andylidong** [comment]
popup在toast弹出的时候，会自动消失，能不能让toast置于popup上面,而popup不消失

**Comment by silentcloud** [comment]
@andylidong 目前暂时不可以，这个在计划中
