### ISSUE TITLE
在modal组件或Dialog组件中使用Input时，无法使用value和onChange的方式修改state。

### ISSUE THREAD

**Issue by KangXinzhi** [ant-design/ant-design-mobile#5891]
### Version of antd-mobile

5.26.0

### Sandbox to reproduce

https://eglly9.csb.app/

**Comment by miracles1919** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/22469543/209291279-40d2f913-fb2c-4daf-9fd3-265ef30c709f.png">

**Comment by YYvue** [comment]
为啥不在文档上备注一下，我鸡了一整个晚上QAQ
