### ISSUE TITLE
Uploading images show chinese text in ImageUploader

### ISSUE THREAD

**Issue by franz101** [ant-design/ant-design-mobile#5897]
### Version of antd-mobile

5 alpha

### Operating system and its version

Android

### Browser and its version

Chrome latest

### Sandbox to reproduce

https://franz101.github.io/pet-ai

### What happened?

When you upload an image, it will show a loading text, which has not been translated yet.
Happy to open a PR.

**Comment by franz101** [comment]
can be fixed by importing base language and passing it in

**Comment by miracles1919** [comment]
https://mobile.ant.design/guide/i18n
