### ISSUE TITLE
DatePicker ios value指定时间

### ISSUE THREAD

**Issue by ye-admin** [ant-design/ant-design-mobile#5899]
### Version of antd-mobile

5.27.0

### Operating system and its version

iOS

### Browser and its version

safari 微信

### Sandbox to reproduce

https://codesandbox.io/s/lucid-galois-4rvns1?file=/src/App.tsx

### What happened?

在单独使用DatePicker时(不适用Form包裹)，给value指定时间(比如 new Date('2022-1-1'))，而不是new Date()。当第一次打开选择面板时，显示的不是指定的时间而是每列的第一个。安卓正常，ios有问题

**Comment by miracles1919** [comment]
Safari 并不支持 YYYY-MM-DD 这样的日期格式

<img width="178" alt="image" src="https://user-images.githubusercontent.com/22469543/209619004-e8b9f7a3-638b-4378-9a0e-7e3e36e2a310.png">
