### ISSUE TITLE
0.7.2 webpack 中报错

### ISSUE THREAD

**Issue by zhanjiaxia** [ant-design/ant-design-mobile#59]
### 本地环境

- antd-mobile：0.72
- webpack: ^1.13.1,
- node: 6.3.1

### 报错信息

ERROR in ./~/react-hot-loader!./~/babel-loader!./src/containers/ArtisanList/index.jsx
Module not found: Error: Cannot resolve module 'antd-mobile' in /Users/admin/Workspace/asm_wx_fe/src/containers/ArtisanList
 @ ./~/react-hot-loader!./~/babel-loader!./src/containers/ArtisanList/index.jsx 15:18-40

### 出错代码

```js
import { ListView, Toast } from 'antd-mobile'
```

目测是 package.json 文件中没有添加 main 字段, 添加以下字段到 package.json 后可以使用

`"main": "dist/antd-mobile.js",`

使用 `npm` 与 `cnpm` 皆出现此问题

**Comment by warmhug** [comment]
https://github.com/ant-design/ant-design-mobile#use-babel-plugin-antd
