### ISSUE TITLE
RN demo app source code?

### ISSUE THREAD

**Issue by smalltide** [ant-design/ant-design-mobile#590]
請問，有無提供官方 RN demo app source code?

目前官方文件以web mobile為主，

使用上，很多設定都得用猜的

如果有提供，使用RN組件，會比較容易入門

**Comment by silentcloud** [comment]
doc 文档里没有，但是源代码里有，组件 demo 下面的 js 文件即 RN 版本组件的 demo @smalltide

**Comment by smalltide** [comment]
thanks~
