### ISSUE TITLE
打包后组件的样式全变了

### ISSUE THREAD

**Issue by TripleniuTech** [ant-design/ant-design-mobile#5900]
### Version of antd-mobile

5.27

### Operating system and its version

iOS

### What happened?

1. 本地上yarn start 跑起来的样式是正常的
2. yarn build 之后放到远端全部样式都变了
3. 例如这个stepper的样式
<img width="129" alt="209489191-599c8c9c-2e53-41f7-b03f-f00a1b3e8e9c" src="https://user-images.githubusercontent.com/101740777/209890048-0f04f593-88be-42fa-b8fb-7cca1155c03e.png">

4. 正常应该是这个样子的
<img width="137" alt="209489212-9f752eb2-019a-4007-b35e-8126aa0d61f4" src="https://user-images.githubusercontent.com/101740777/209890054-f03fe951-f201-4b08-9732-bc8051baf0e9.png">

**Comment by miracles1919** [comment]
感觉是你打包的问题，可以把你的项目放个 zip 传上来看看

**Comment by TripleniuTech** [comment]
> 感觉是你打包的问题，可以把你的项目放个 zip 传上来看看

[myapp.zip](https://github.com/ant-design/ant-design-mobile/files/10325018/myapp.zip)
你看看这是我建的demo 项目，yarn start:dev 是好的，yarn build之后放到服务器上看就什么都不行了。我用的是antd pro design 按理来说应该内置了antd design mobile的

**Comment by miracles1919** [comment]
> antd pro design 按理来说应该内置了antd design mobile的

两者没有关系的

**Comment by nextdooroldwang** [comment]
出现同样的问题。例：badge组件。
dev：
<img width="820" alt="image" src="https://user-images.githubusercontent.com/18671240/212788497-e7920718-a5da-4373-9592-73ce08c8ecb2.png">

build：
<img width="857" alt="image" src="https://user-images.githubusercontent.com/18671240/212788626-f164a63d-d01e-4cb6-ab33-35d8c189dabc.png">

打包后样式加载顺序变了，导致样式异常：
<img width="464" alt="image" src="https://user-images.githubusercontent.com/18671240/212788730-5d1f0608-d390-4279-95bd-0270a21e5e3d.png">

@miracles1919
