### ISSUE TITLE
datePicker周维度时，选择2022年任一周，会选择上2021年的值

### ISSUE THREAD

**Issue by 544211707** [ant-design/ant-design-mobile#5907]
### Version of antd-mobile

v5.18.0

### Operating system and its version

iOS

### Browser and its version

safari

### Sandbox to reproduce

datePicker周维度时，选择2022年任一周，会选择上2021年的值，如第52周

### What happened?

datePicker周维度时，选择2022年任一周，如第52周：会选择2021年的值， 应为2022年的值。

**Comment by 1587315093** [comment]
请给复现链接再打开这个issue @544211707
