### ISSUE TITLE
Android5.x 部分浏览器（系统自带浏览器、百度浏览器等）样式问题

### ISSUE THREAD

**Issue by API1234** [ant-design/ant-design-mobile#5911]
### Version of antd-mobile

v5.27.0

### Operating system and its version

Android

### Browser and its version

vivo系统自带浏览器、百度浏览器

### What happened?

![image](https://user-images.githubusercontent.com/45424002/210497733-844a0d30-5afe-49ce-a2f4-89fe2590650e.png)

**Comment by miracles1919** [comment]
应该是不支持 CSS 变量，看下[降级方案 ](https://mobile.ant.design/zh/guide/css-variables#css-%E5%8F%98%E9%87%8F%E8%87%AA%E5%8A%A8%E9%99%8D%E7%BA%A7)
