### ISSUE TITLE
SearchBar组件潜在Bug

### ISSUE THREAD

**Issue by JaneLee0324** [ant-design/ant-design-mobile#5913]
### Version of antd-mobile

5.27.0

### Browser and its version

Chrome

### What happened?

https://mobile.ant.design/zh/components/search-bar 官网中的第一个demo中「事件监听和Ref」中，在搜索框中输入任意文字后，点击键盘的“搜索”按钮，不会如预期触发「Toast: 你搜索了xxxx」（而是触发Toast：失去焦点）；需要再次点击输入框后点击键盘的“搜索”按钮，才会触发预期中的 Toast。（也可能是多次Toast的问题）

**Comment by miracles1919** [comment]
`onSearch` 和 `onBlur` 都触发了，导致多次 Toast
