### ISSUE TITLE
电脑端浏览器无法上下拖动或者滚动

### ISSUE THREAD

**Issue by yeyuanhuais** [ant-design/ant-design-mobile#5915]
### Version of antd-mobile

5.27.0

### Operating system and its version

Others

### Browser and its version

谷歌浏览器

### What happened?

![image](https://user-images.githubusercontent.com/60806722/210685788-bb7d3374-19b5-40e7-aed9-b83adc00d945.png)
无法上下拖动或者滚动

**Comment by fengzehao** [comment]
电脑端需要按住鼠标左键进行拖动

**Comment by yyh28** [comment]
> 电脑端需要按住鼠标左键进行拖动

windows 按住鼠标左键拖动不了

**Comment by fengzehao** [comment]
> > 电脑端需要按住鼠标左键进行拖动
> 
> windows 按住鼠标左键拖动不了
我这里可以

https://user-images.githubusercontent.com/23555315/215994942-9e164ded-7a24-4b4a-9099-5b111557d1e1.mp4

**Comment by tylerrrkd** [comment]
看看是不是有鼠标事件相关的浏览器插件
