### ISSUE TITLE
search图标在微信和qq内置浏览器内变白

### ISSUE THREAD

**Issue by mtboom** [ant-design/ant-design-mobile#593]
#### 本地环境

- antd-mobile 版本：0.9.5
- 操作系统及其版本：安卓系统
- 浏览器及其版本：微信浏览器及qq内置浏览器

#### 你做了什么？

在NavBar里添加了按钮Icon search 

#### 你期待的结果是：

icon search正常显示
![正常显示](http://p1.bqimg.com/567571/94a672a8074aaa30.png)

#### 实际上的结果：

icon search整体变白
![实际显示](http://p1.bqimg.com/567571/76381ba04e039809.png)

#### 尝试修复
查看css样式时发现
[type=search] { 
/* -webkit-appearance:none; */ //该行隐藏样式生效,去掉该行后icon search样式恢复正常
    outline-offset: -.02rem
}

**Comment by warmhug** [comment]
升级到 0.9.10 ，尽量保持最新版，再看看

**Comment by mtboom** [comment]
![](http://i1.piimg.com/567571/5e0faa0496a13d68.png)
升级到 0.9.10 后 如上

**Comment by warmhug** [comment]
为什么变白？是不兼容问题吗

**Comment by warmhug** [comment]
@afc163 Search 图标确实有问题、有白色背景，帮忙看下 iconfont 文件是不是能更新下。
https://github.com/ant-design/ant-design-mobile/blob/0.9.x/components/icon/style/index.less

**Comment by regrex** [comment]
@afc163 我们也遇到类似问题了，研究发现iconfont的命名不要叫search，换个名字就好了。怀疑是QQ浏览器有内置样式，影响了这个iconfont的样式。

**Comment by afc163** [comment]
感觉是默认样式问题 `-webkit-appearance:none;`

@mtboom 所以 antd-mobile 如何修复比较好，来个 PR 如何？

**Comment by warmhug** [comment]
只有 search 图标有问题、其他 iconfont 没发现问题，是什么原因？需不需要设计师看看？ @afc163

**Comment by paranoidjk** [comment]
@mtboom @regrex 

Going to close this, since `antd-mobile`  1.x  had replaced iconfont with svg, please try the latest version `1.0.4`.  If the problem still exist, then just comment at here,  and I will reopen.
