### ISSUE TITLE
list组件下边框左右不对齐

### ISSUE THREAD

**Issue by KangXinzhi** [ant-design/ant-design-mobile#5936]
### Version of antd-mobile

latest

### What happened?

![image](https://user-images.githubusercontent.com/50164727/212017843-053e79a0-74d2-4287-9f5d-f7e1c58a5ef3.png)
![image](https://user-images.githubusercontent.com/50164727/212017985-f2ef2dcf-b61a-4f8a-8f4b-321713a0a0e1.png)

**Comment by KangXinzhi** [comment]
清问是否需要修复呢，我可以提pr

**Comment by miracles1919** [comment]
设计如此

**Comment by KangXinzhi** [comment]
> 设计如此

好的
