### ISSUE TITLE
打包后组件的样式全变了(css加载顺序不一致)

### ISSUE THREAD

**Issue by nextdooroldwang** [ant-design/ant-design-mobile#5943]
### Version of antd-mobile

"antd-mobile": "^5.28.0",

[https://github.com/nextdooroldwang/web.git](url)

https://github.com/ant-design/ant-design-mobile/issues/5900#issuecomment-1384719605

**Comment by miracles1919** [comment]
你提供的项目里没看到相关的样式... 

从你的截图看，如果你想覆盖 CSS 变量，可以这样

```jsx
<Badge style={{ '--top': '6px'}} ></Badge>
```
