### ISSUE TITLE
生产环境Picker组件样式与开发环境不一致

### ISSUE THREAD

**Issue by bigpigOne** [ant-design/ant-design-mobile#5945]
### Version of antd-mobile

5.28.0

### Operating system and its version

Android, Others

### Browser and its version

android9.0    web:edge

### What happened?

![1](https://user-images.githubusercontent.com/92560015/213636642-e3d631da-da31-4197-93fa-d1fbafc06026.png)
生产环境

![2](https://user-images.githubusercontent.com/92560015/213636703-671f616a-e875-45b3-8d98-4f342b16aa4e.png)
开发环境

期望生产环境样式与开发环境一致

**Comment by bigpigOne** [comment]
我的 adm-picker-view-mask-bottom css没编译。
    
-webkit-mask: linear-gradient(180deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0.8) 50%, #000000 100%);

**Comment by dingxyang** [comment]
我打包的时候用了postcss的autoprefixer插件解决这个问题
