### ISSUE TITLE
使用antd-mobile部分组件会导致咋部分机型上白屏比如Android9 

### ISSUE THREAD

**Issue by MarkLogin** [ant-design/ant-design-mobile#5950]
### Version of antd-mobile

5.28.0

### Operating system and its version

Android

### Browser and its version

Android9 内置浏览器

### What happened?

新建一个ReactH5项目，再使用antd-mobile部分组件在Android9内置浏览器上白屏，其他的机型无问题报错信息：
I/chromium: [INFO:CONSOLE(2)] "Uncaught SyntaxError: 'super' keyword unexpected here",
"Uncaught (in promise) Error: ChunkLoadError: Loading chunk 2 failed.

比如使用Popup、Tabs、Mask等组件时，仅使用Input、Button、SearchBar等组件无该问题。

**Comment by MarkLogin** [comment]
bug 复现仓库 ： https://gitee.com/YeGuCheng2018/taro-android9-white-screen.git

**Comment by miracles1919** [comment]
试试把 node_modules 里的内容加入到 babel 编译中，另外我看你在 Taro 也提了 [Issue](https://github.com/NervJS/taro/issues/13186)，这个我关了哈

**Comment by tangbei** [comment]
我也遇到了该问题，想问下是具体那个包或者那几个包需要过babel？我针对性的处理下。

**Comment by tangbei** [comment]
我也遇到了该问题，想问下是具体那个包或者那几个包需要过babel？我针对性的处理下。

**Comment by tangbei** [comment]
我也遇到了该问题，想问下是具体那个包或者那几个包需要过babel？我针对性的处理下。

<img width="537" height="486" alt="Image" src="https://github.com/user-attachments/assets/a727e826-790a-44df-91b8-7cda2f752863" />
