### ISSUE TITLE
DatePicker兼具性问题-部分机型(ios,iphone11)出现年份不显示的问题

### ISSUE THREAD

**Issue by mushan520** [ant-design/ant-design-mobile#5959]
### Version of antd-mobile

^5.27.0

### Operating system and its version

iOS

### Browser and its version

safari   15.4.1  和 15.0

### Sandbox to reproduce

https://codesandbox.io/s/eloquent-bogdan-38zvx9?file=/src/App.tsx

### What happened?

问题: 在使用datepicker中，限制了min和max值，并且再使用min/max值时，通过new Date去转换dayjs，不兼容导致年份没有出来
解决办法：通过dayjs的toDate转换
![image](https://user-images.githubusercontent.com/55680267/217194135-e70bf3b5-4cd5-4ae6-adea-9139d65dd526.png)

![ae4c19a38368eac886efdda7967e532](https://user-images.githubusercontent.com/55680267/217193751-c59c5cf3-57d8-44fc-a1a7-870067569f79.jpg)

![76cf017e976811679a8e9ae09bae16b](https://user-images.githubusercontent.com/55680267/217193781-9c34aac3-04df-4f63-ac09-f6c8bf853796.jpg)

**Comment by mushan520** [comment]
iphone11 中使用的new  Date，在datepicker中都会有问题，包括value

**Comment by Feafortecsy** [comment]
> iphone11 中使用的new Date，在datepicker中都会有问题，包括value

```
format("2023/04/24")

```

**Comment by miracles1919** [comment]
max/min 要求的就是 `Date` 类型，看起来是你 dayjs 转换的问题

**Comment by miracles1919** [comment]
> iphone11 中使用的new Date，在datepicker中都会有问题，包括value

我试了下也是正常的：iphone 11 pro max, iOS, v14.7, Safari

![image](https://github.com/ant-design/ant-design-mobile/assets/22469543/cbc786cd-61de-477d-af13-3ca57a939fc0)
