### ISSUE TITLE
动态渲染 Tabs 组件报错

### ISSUE THREAD

**Issue by gauseen** [ant-design/ant-design-mobile#5963]
### Version of antd-mobile

5.28.0

### Browser and its version

chrome 109.0.5414.119

### Sandbox to reproduce

https://codesandbox.io/s/interesting-cherry-m6l7dw?file=/src/App.tsx

### What happened?

渲染报错

**Comment by miracles1919** [comment]
看了下是这里报错了 

```js
children: [
        {
          component: () => "content test",
          componentId: "node_21_1_1"
        }
      ]
```

**Comment by gauseen** [comment]
@miracles1919 报错是因为 children 字段跟 Tab 组件逻辑矛盾导致的，我把 children 改成 childs 就不报错了，但是 tab 组件还是无法渲染，麻烦看下，这里是 demo https://codesandbox.io/s/elated-feather-swwkeg?file=/src/App.tsx
