### ISSUE TITLE
【feature request】希望增加解决 Safari  100vh 问题的组件

### ISSUE THREAD

**Issue by KingAmo** [ant-design/ant-design-mobile#5969]
### Version of antd-mobile

5.28.0

### Operating system and its version

iOS

### What happened?

参考： https://github.com/mvasin/react-div-100vh

**Comment by MuxinFeng** [comment]
我觉得在自己的项目里做处理比较好，如果在 antd-mobile 改，会造成 break-change 的。
可以参考下这个
```
  padding-bottom: constant(safe-area-inset-bottom); /* 兼容 iOS < 11.2 */
  padding-bottom: env(safe-area-inset-bottom); /* 兼容 iOS >= 11.2 */

**Comment by KingAmo** [comment]
> 我觉得在自己的项目里做处理比较好，如果在 antd-mobile 改，会造成 break-change 的。 可以参考下这个
> 
> ```
>   padding-bottom: constant(safe-area-inset-bottom); /* 兼容 iOS < 11.2 */
>   padding-bottom: env(safe-area-inset-bottom); /* 兼容 iOS >= 11.2 */
> ```

这个解决不了100vh的问题哦

**Comment by miracles1919** [comment]
直接用你发的的 [react-div-100vh](https://github.com/mvasin/react-div-100vh)  有什么问题
