### ISSUE TITLE
ListView 向上滚动 的 Bug

### ISSUE THREAD

**Issue by JenJieJu** [ant-design/ant-design-mobile#597]
#### 本地环境

- antd-mobile 版本：0.9.8
- 操作系统及其版本：iOS Andriod
- 浏览器及其版本：所有

ListView 向上滚动直到手指移到超过 webkit 浏览器，ListView不触发回弹。

<img width="523" alt="qq20161201-0 2x" src="https://cloud.githubusercontent.com/assets/12652367/20790051/a02557b0-b7f1-11e6-8697-bea356d691b8.png">

**Comment by warmhug** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/573#issuecomment-263501851

**Comment by devinRex** [comment]
有同样的问题，但是发现如果listView内部元素的高度超过100%，就不会出现这种情况，目前暂时没有找到解决办法。。。
