### ISSUE TITLE
UploadImage上传顺序未和图片选择顺序对应

### ISSUE THREAD

**Issue by oneQiu** [ant-design/ant-design-mobile#5970]
### Version of antd-mobile

5.27.0

### Operating system and its version

iOS, Android, Others

### Browser and its version

Chrome版本 109.0.5414.119（正式版本）

### What happened?

问题：我选择了多个图片，并且是有顺序的，上传过程展示的也没问题，但是上传成功后却安装上传快慢来排序，这并不合理。
![image](https://user-images.githubusercontent.com/50658231/218427411-1582a4b1-973c-45ad-a87b-f66927f8a7d7.png)
![image](https://user-images.githubusercontent.com/50658231/218427437-9e604310-3b1c-42a6-843d-2eba1e358d81.png)

期望：和Antd组件对其，能够按照选择的顺序。
PS：看了onChange方法，发现它只是把上传成功的传回了，所以丢失了顺序

**Comment by heiyu4585** [comment]
i want to try  this

**Comment by heiyu4585** [comment]
can close  this
