### ISSUE TITLE
[RFC] when double sliders show all popover

### ISSUE THREAD

**Issue by ohlyf** [ant-design/ant-design-mobile#5980]
### Version of antd-mobile

5.28.0

### What is this feature about?

**灵感**：看了[issues #5973](https://github.com/ant-design/ant-design-mobile/issues/5973)，两个滑块滑动不松鼠标的时候当前一个超过后一个，或后一个低于前一个的时候，`popover`只会显示在相交位置，本意想解决这个bug
**过程**：做出很多修改都不太满意，最后尝试当两个滑块的时候，滑动时都显示popover，希望采纳
**结果**：新增都显示popover的功能并新增两个测试用例，都能跑通
**代码**：https://github.com/ant-design/ant-design-mobile/pull/5979

**Comment by 1587315093** [comment]
pr 关了的话这个也关了 
![image](https://github.com/ant-design/ant-design-mobile/assets/77056991/85b8df73-88d4-44c6-aea5-2aa2add7da5d)
