### ISSUE TITLE
InfiniteScroll  loadMore 初始化调用两次接口

### ISSUE THREAD

**Issue by zxh0125** [ant-design/ant-design-mobile#5983]
### Version of antd-mobile

5.28.0

### Operating system and its version

Others

### Browser and its version

微信

### What happened?

/*
 * @Author: nhsoft.zhangxh
 * @Date: 2023-02-06 10:27:27
 * @LastEditors: nhsoft.zhangxh
 * @LastEditTime: 2023-02-20 09:55:03
 * @Description: 我的页面
 */
import { InfiniteScroll, List } from 'antd-mobile'
import { memo, useState } from 'react'
import { sleep } from 'antd-mobile/es/utils/sleep'
import { history } from 'umi'

import styles from './index.less'
import ListItem from './ListItem'

import { getOrders } from '@/services/order'
import type { ISaveOrderRes } from '@/types/sale/sumbitOrder'

let count = 0

export async function mockRequest() {
  if (count >= 5) {
    return []
  }
  await sleep(2000)
  count++
  return [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
  ]
}

export default memo(function Me() {
  const offset = 0
  const limit = 4

  const [hasMore, setHasMore] = useState(true)

  // const [offset, setOffset] = useState(0)
  // const [limit, setLimit] = useState(10)

  const [orderData, setOrderData] = useState<ISaveOrderRes[]>([])

  // const getOrders=()=>{

  // }

  const loadMore = async () => {
    count++

    const res = await getOrders({
      limit: count * limit,
      offset: count * offset
    })
    if (res.isSuccess()) {
      setOrderData(p => [...p, ...res.data])
    }
    setHasMore(res?.data?.length > 0)
  }

  const goDetail = (id: string) => {
    history.push(`/purchasedetail/${id}`)
  }
  return (

    <div className={styles.me_content}>
      <div className={styles.me_content_list}>
        <List>
          {orderData?.map((item) => (
            <List.Item key={item.id}>
              <div onClick={() => goDetail(item.id)}>
                <ListItem orderInfo={item} />
              </div>
            </List.Item>
          ))}
        </List>
        <InfiniteScroll loadMore={loadMore} hasMore={hasMore} /> 
      </div>
    </div>

  )
})

**Comment by miracles1919** [comment]
有可能是第一次调用 `loadMore` 后，高度还是不够，所以调用了第二次 

具体的可以来个复现 demo, [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) or [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx).

**Comment by ycshill** [comment]
我也有同样的问题，不是调用两次啊，如果高度不够一致调，可怎么处理

**Comment by ycshill** [comment]
> 有可能是第一次调用 `loadMore` 后，高度还是不够，所以调用了第二次
> 
> 具体的可以来个复现 demo, [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) or [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx).

你后来怎么解决的呢

**Comment by ycshill** [comment]
> Hi, zxh0125.
> 
> Please provide a online reproduction so that we can help you troubleshoot the problem. You can create a demo by [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) or [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx).
> 
> 我们需要你提供一个在线的重现实例，以便于我们帮你排查问题。你可以通过 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx) 创建一个实例。

把你们官网的demo1， setData([1]).就复现了
