### ISSUE TITLE
SafeArea 在微信浏览器中不生效问题

### ISSUE THREAD

**Issue by lwQin** [ant-design/ant-design-mobile#5985]
### Version of antd-mobile

5.28.0

### Operating system and its version

iOS

### Browser and its version

微信浏览器(AppleWebKit 605.1.15)

### Sandbox to reproduce

https://mobile.ant.design/gallery/safe-area

### What happened?

直接进入 demo 页正常
![IMG_2400](https://user-images.githubusercontent.com/11586662/220801275-06996581-92ee-431d-9f01-f364e690cc17.PNG)
经过路由跳转底部出现控制条后 SafeArea 失效
![IMG_2401](https://user-images.githubusercontent.com/11586662/220801318-c8bf5d4b-2b80-4121-92b7-b527098209a2.PNG)

**Comment by lwQin** [comment]
好像只能自己手动处理了。。这个算是苹果的 feature

**Comment by JimmyZDD** [comment]
参照: https://segmentfault.com/a/1190000022191869#item-5
需要将viewport设置为cover，env和constant才能生效。
<meta name="viewport" content="width=device-width,initial-scale=1.0,viewport-fit=cover">

**Comment by lwQin** [comment]
> 参照: https://segmentfault.com/a/1190000022191869#item-5 需要将viewport设置为cover，env和constant才能生效。 `<meta name="viewport" content="width=device-width,initial-scale=1.0,viewport-fit=cover">`

一直都是这个配置
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, viewport-fit=cover">`

这个是路径跳转过就会出现这个问题
