### ISSUE TITLE
【Feature】ErrorBlock 组件的文字描述样式是否可以开放 css 变量定义

### ISSUE THREAD

**Issue by tulies** [ant-design/ant-design-mobile#5986]
### What is this feature about?

如题：ErrorBlock 组件的文字描述样式是否可以开放css变量定义

![image](https://user-images.githubusercontent.com/8286897/220881217-312cd508-b851-449f-9ec2-dbbf8f477fa2.png)

**Comment by miracles1919** [comment]
`title` `description` 都是 `ReactNode`，自己改吧
