### ISSUE TITLE
依赖的@react-spring报错，看了一下是昨天发了一个新版本@9.7.0 导致打包失败

### ISSUE THREAD

**Issue by oliver34** [ant-design/ant-design-mobile#5988]
### Version of antd-mobile

latest

### What happened?

![image](https://user-images.githubusercontent.com/12234456/221080584-a1370010-f4b2-4f21-a0f3-b7b54e366c07.png)

**Comment by BobiY** [comment]
我也碰到了这个问题，打包的时候是直接将 @react-spring 固定在了 9.5.5 暂时解决了

**Comment by oliver34** [comment]
我把锁在了9.6.1修复了
`"resolutions": {
    "@react-spring/web": "9.6.1"
  },`

>

**Comment by codinglilong** [comment]
同样的问题，脑壳痛

**Comment by zombieJ** [comment]
我先发个 patch 锁一下版本好了
