### ISSUE TITLE
引入SearchBar组件，样式异常

### ISSUE THREAD

**Issue by valsun2016** [ant-design/ant-design-mobile#599]
#### 本地环境

- antd-mobile 版本：0.9.10
- 操作系统及其版本：windows7  
- 浏览器及其版本：chrome54 模拟 iPhone6

#### 你做了什么？

import { SearchBar } from 'antd-mobile';

#### 你期待的结果是：

搜索框效果如下：
https://mobile.ant.design/kitchen-sink/search-bar/

#### 实际上的结果：
搜索框样式变大很多（项目除了ant design mobile官方样式，无任何自定义样式干扰）：

<img style="user-select: none; cursor: zoom-in;" src="http://h.hiphotos.baidu.com/image/pic/item/7c1ed21b0ef41bd5f22ab0e758da81cb39db3da3.jpg" width="375" height="584">
<br/>使用其他的ant design mobile组件则不会有异常，其他正常的：<br/> <img style="-webkit-user-select: none" src="http://c.hiphotos.baidu.com/image/pic/item/f2deb48f8c5494eeea3e4b0a24f5e0fe99257e80.jpg">

 #### 可重现的在线演示
 暂无发布

**Comment by warmhug** [comment]
测试无此问题。 有时候模拟器会异常，重启下模拟器，或者直接在手机上确认是否有次问题

**Comment by valsun2016** [comment]
不是模拟器或者浏览器缓存的问题，彻底清除过，手机测试也一样。

我仔细对比了一下浏览器dom的解析输出，

正常的样式（未引入SearchBar组件前）：

只有系统样式输出在页面head间： antd-mobile v0.9.10 

异常的样式（引入SearchBar组件后）：

除了 antd-mobile v0.9.10  样式，会多出：
好多样式,,, 下面三图：

<img style="-webkit-user-select: none" src="http://f.hiphotos.baidu.com/image/pic/item/0d338744ebf81a4ca49b97ddde2a6059252da67d.jpg">
<img style="-webkit-user-select: none" src="http://e.hiphotos.baidu.com/image/pic/item/838ba61ea8d3fd1f1df0d92e394e251f95ca5f2c.jpg">
<img style="-webkit-user-select: none" src="http://a.hiphotos.baidu.com/image/pic/item/4b90f603738da977896cfd3fb951f8198618e367.jpg">

然后，我动态把dom中多出上面三图的样式全去掉：结果，正常了：

<img style="-webkit-user-select: none" src="http://h.hiphotos.baidu.com/image/pic/item/eaf81a4c510fd9f920be2e7d2c2dd42a2834a47d.jpg">

我怀疑是不是我的 webpack.config 配置问题？
query: {
     presets: ['es2015', 'react'],
     plugins: [["import", { "libraryName": "antd-mobile"}]]
}

另外样式我是在入口页面手动引入一次：import "antd-mobile/dist/antd-mobile.min.css"

如果  webpack.config 配置 改成 ：
....
 plugins: [["import", { "libraryName": "antd-mobile",style: 'css' }]]
 
那页面输出的样式就更多了，感觉在重复，，除SearchBar组件，其他组件也不正常了

所以我怀疑是我哪里配置 使用的不对？但是我没任何外部样式干扰啊？求指点

**Comment by warmhug** [comment]
不要 `import "antd-mobile/dist/antd-mobile.min.css"` 这样引用。看文档 https://mobile.ant.design/docs/react/introduce#%E4%BD%BF%E7%94%A8  用  babel-plugin-import

**Comment by valsun2016** [comment]
// .babelrc
{"plugins": [["import", { "style": "css", "libraryName": "antd-mobile" }]]}
这种也不行，最后直接在起始页 index.html 开始引入     
 <link href="build/antd-mobile.min.css" rel="stylesheet" /> ， 一切ok。

**Comment by warmhug** [comment]
不要一次引入 antd-mobile.min.css  。贴一下 webpack 配置吧

**Comment by valsun2016** [comment]
@warmhug 

var path = require('path');
var root_path = path.resolve(__dirname);
var src_path = path.resolve(root_path, 'src');
var build_path = path.resolve(root_path, 'build');
var webpack = require('webpack');
module.exports = {
    entry: {
        app: path.resolve(src_path, 'entry.jsx')
    },
    output: {
        path: build_path,
        publicPath: '/build/',
        filename: 'bundle.js'
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery",
            reqwest: 'reqwest'
        }),
        new webpack.optimize.UglifyJsPlugin({ test: /(\.jsx|\.js)$/, compress: { warnings: false } }),
        new webpack.optimize.DedupePlugin(),
        new webpack.DefinePlugin({
            "process.env": {
                NODE_ENV: JSON.stringify("production")
            }
        })
    ],
    resolve: {
        alias: {
            react: __dirname + '/node_modules/react'
        }
    },
    jshint: {
        "esnext": true
    },
    module: {
        perLoaders: [
           { test: /\.jsx?$/, include: src_path, loader: 'jshint-loader' }
        ],
        loaders: [
            {
                test: /\.(jsx|js)$/,
                include: src_path,
                loader: 'babel',
                query: {
                    presets: ['es2015', 'react'],
                    plugins: [["import", { "libraryName": "antd-mobile",style: 'css' }]]
                }
            },
            { test: /\.(css|less)$/, loader: 'css!less' },
            { test: /\.(png|jpg|jpeg|gif)$/, loader: 'file-loader?limit=8192&name=images/[name].[ext]' },
            { test: /\.(ttf|eot|svg|woff)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000" }
        ]
    }
}

**Comment by warmhug** [comment]
这样格式的代码怎么读。。

**Comment by warmhug** [comment]
参考这里文档重新配置下 https://mobile.ant.design/docs/react/introduce#%E4%BD%BF%E7%94%A8

**Comment by hjue** [comment]
遇到同样的问题。这是我的webpack.config.js的配置，这个配置是使用`dva new `生成的。  antd-mobile的版本是0.9.12。我也同样是直接在起始页 index.html 引入 antd-mobile.min.css 一切ok。

```
const webpack = require('atool-build/lib/webpack');

module.exports = function(webpackConfig, env) {
  webpackConfig.babel.plugins.push('transform-runtime');

  webpackConfig.babel.plugins.push(['import', {
    style: 'css',  // if true, use less
    libraryName: 'antd-mobile',
  }]);

  // Support hmr
  if (env === 'development') {
    webpackConfig.devtool = '#eval';
    webpackConfig.babel.plugins.push('dva-hmr');
  } else {
    webpackConfig.babel.plugins.push('dev-expression');
  }

  // Don't extract common.js and common.css
  webpackConfig.plugins = webpackConfig.plugins.filter(function(plugin) {
    return !(plugin instanceof webpack.optimize.CommonsChunkPlugin);
  });

  // Support CSS Modules
  // Parse all less files as css module.
  webpackConfig.module.loaders.forEach(function(loader, index) {
    if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.less$') > -1) {
      loader.include = /node_modules/;
      loader.test = /\.less$/;
    }
    if (loader.test.toString() === '/\\.module\\.less$/') {
      loader.exclude = /node_modules/;
      loader.test = /\.less$/;
    }
    if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.css$') > -1) {
      loader.include = /node_modules/;
      loader.test = /\.css$/;
    }
    if (loader.test.toString() === '/\\.module\\.css$/') {
      loader.exclude = /node_modules/;
      loader.test = /\.css$/;
    }
  });

  return webpackConfig;
};

```

![image](https://cloud.githubusercontent.com/assets/1135045/21354324/90d48a34-c704-11e6-9407-4f9fcce9a293.png)

@warmhug

**Comment by warmhug** [comment]
https://github.com/warmhug/__/blob/master/_react/dva-ts/webpack.config.js#L49
![image](https://cloud.githubusercontent.com/assets/2011119/21358737/9986be80-c714-11e6-94c4-5e359c0ab292.png)

**Comment by hjue** [comment]
我的问题解决了，感谢 @warmhug。
样式值都写成和视觉稿上标注的值（视觉稿标注一般以设备物理点为单位，像 iPhone6 屏幕 750 的宽度）一样即可。这样太棒了 👍
