### ISSUE TITLE
htm标签上设置data-prefers-color-scheme="dark"，背景色还是白色

### ISSUE THREAD

**Issue by viviuolo** [ant-design/ant-design-mobile#5995]
### Version of antd-mobile

5.28.1

### Operating system and its version

Others

### Browser and its version

Chrome 版本 110.0.5481.100

### What happened?

[字体颜色变化了，但是背景色还是白色
<img width="1699" alt="截屏2023-02-27 上午11 06 35" src="https://user-images.githubusercontent.com/22727579/221463786-297b7c46-d44f-48d0-adf3-e0898ca0be43.png">

**Comment by miracles1919** [comment]
属性错了，应该是`prefers-color-scheme`
