### ISSUE TITLE
Image组件onload事件在nextjs ssr模式下不会被触发/ image component onload event not firing in ssr mode with nextjs

### ISSUE THREAD

**Issue by galaxynova1999** [ant-design/ant-design-mobile#5996]
### Version of antd-mobile

^5.28.1

### Operating system and its version

iOS, Android, Others

### Browser and its version

Chrome/Safari

### Sandbox to reproduce

https://github.com/galaxynova1999/next-js-antd-image

### What happened?

image组件在ssr模式下 由于hydrate发生在native onload事件之后 react后挂载的事件监听器不会被触发

![image](https://user-images.githubusercontent.com/45778220/221502833-08174fc9-5a44-4bed-a7f8-ea31676eec24.png)

参考回答
1. https://stackoverflow.com/questions/59787642/nextjs-images-loaded-from-cache-dont-trigger-the-onload-event
2. https://github.com/vercel/next.js/issues/7047
3. https://github.com/facebook/react/issues/15446

ant-design正在修复的pr: https://github.com/ant-design/ant-design/issues/40555

可能的解决方案：在useEffect中通过img元素的complete属性来重置loaded状态

```js
useEffect(() => {
    if(imgRef.current.complete) {
      setLoaded(true);
    }
  }, []);
```

**Comment by 666hxw** [comment]
image属性complete在CSR场景，其实不准确，在一些安卓webview，complete可能在图片加载过程中就为true，这样子会导致未加载完的图片直接被渲染出来
