### ISSUE TITLE
v5.28.1 使用reduceMotion 报错 Module not found: Can't resolve 'antd-mobile/es/components/reduce-motion'

### ISSUE THREAD

**Issue by Emensionyu** [ant-design/ant-design-mobile#6004]
### Version of antd-mobile

5.28.1

### What is this feature about?

减弱动效使用

**Comment by miracles1919** [comment]
`import { reduceMotion } from 'antd-mobile'`

**Comment by Emensionyu** [comment]
imort的了，后来改成import { reduceMotion } from 'antd-mobile/es/utils/reduce-and-restore-motion';
可以了

**Comment by hardmanhong** [comment]
> imort的了，后来改成import { reduceMotion } from 'antd-mobile/es/utils/reduce-and-restore-motion'; 可以了

俺也一样
