### ISSUE TITLE
下拉框Dropdown，列表内容太宽，无法自定义宽度

### ISSUE THREAD

**Issue by xiefangzhenz** [ant-design/ant-design-mobile#6007]
### Version of antd-mobile

5.28.1

### Operating system and its version

iOS, Android, Others

### Browser and its version

chrome

### What happened?

dropdown之后，有一个下拉列表。屏幕宽度1000px，dropdown的宽度是400px，但是下拉的内容占了屏幕的100%，也就是1000px，如何进行调节，让他与dropdown等宽呢

**Comment by miracles1919** [comment]
有效果图么，get 不到你的效果...

**Comment by xiefangzhenz** [comment]
![QQ20230306-145250](https://user-images.githubusercontent.com/13177194/223039299-d69fe15e-fd7d-4304-af34-ca364dbd50ba.png)
@miracles1919 大佬，有办法让红色区域，可以调节为绿色区域那么宽吗，并且不出现穿透现象

**Comment by xiefangzhenz** [comment]
@miracles1919  建议加一个width属性，可以让下拉框自适应不同宽度的div

**Comment by xiefangzhenz** [comment]
![WechatIMG27384](https://user-images.githubusercontent.com/13177194/223059841-a511e2a1-1cde-4b37-b618-45e1d9ae08c7.png)
类似于这样UI效果
