### ISSUE TITLE
实验性日历 ，区间选择，onChange 回调中  能不能给第二个参数区分是选择开始时间回调，还是结束时间回调

### ISSUE THREAD

**Issue by ty01** [ant-design/ant-design-mobile#6008]
### Version of antd-mobile

5.28.0

**Comment by miracles1919** [comment]
`val[0] !== val[1]` 的时候就是结束回调

**Comment by ty01** [comment]
@miracles1919 这逻辑还是有点问题  只选择一天的时候   val[0] 永远 === val[1]    因为同一日期第二次点击 值为null

**Comment by miracles1919** [comment]
补充下 null 的逻辑就好了呀 

`val === null || val[0] !== val[1]`

**Comment by ty01** [comment]
@miracles1919 不行     场景：用户原本选的六号一天   再次进来他准备选六号七号两天   这时他点击六号值为null（本来有值，再次点击就是null）

**Comment by ty01** [comment]
@miracles1919 不行     场景：用户原本选的六号一天   再次进来他准备选六号七号两天   这时他点击六号值为null（本来有值，再次点击就是null）

**Comment by miracles1919** [comment]
不是很懂... 提供个在线 demo 看看，[codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx)
