### ISSUE TITLE
Popup气泡框是否支持修改border

### ISSUE THREAD

**Issue by linzhixin** [ant-design/ant-design-mobile#6021]
### Version of antd-mobile

5.28.1

### Description

目前有需求需要做一个有颜色边框的气泡框，但是我尝试了一下似乎无法达到预期的样式，上面那个尖尖的icon好像没有办法修改它的border

https://codesandbox.io/s/purple-lake-n5plfu?file=/src/styles.css

**Comment by zombieJ** [comment]
魔改的话箭头要额外处理一下：
https://codesandbox.io/s/reverent-cdn-mv1yng?file=/src/styles.css
