### ISSUE TITLE
ImageUploader 组件在ios上拍照上传图片后会刷新页面

### ISSUE THREAD

**Issue by breezefeng** [ant-design/ant-design-mobile#6026]
### Version of antd-mobile

5.24.1

### Browser and its version

ios 12

### What happened?

ImageUploader 组件在ios上拍照上传图片后会刷新页面，导致上传的图片数据丢失

**Comment by xiaoyao96** [comment]
这个应该是IOS系统层面的bug。在Safari、钉钉、QQ、微信等浏览器，通过h5 <input type="file" /> 唤起相机后（不论是否拍照）返回，都高概率刷新网页，但从相册里选择照片不会刷新。

推测原因：IOS系统在打开相机时需要较高的运行内存，webview作为高内存占用的后台进程会被优先自动杀掉，来确保 相机 能正常运行。从相机返回时，检测webview已被杀死，所以触发了webview进程重启（刷新）。

这个问题暂无有效解决方案，如果用户遇到了，可以建议他使用相册再试。

**Comment by xiaoyao96** [comment]
> 如果我不想给予选择相机的选项呢，需要怎么配置

h5应该没有这个能力，目前我了解到的关于选择图片的方案有以下两种：

1、点击直接唤起拍照：
``` html
<input type="file" accept="image/*" capture="environment" /> 后置摄像头
<input type="file" accept="image/*" capture="user" /> 前置摄像头
```

2、点击出现 相册、拍照、文件 选择弹框
``` html
<input type="file" accept="image/*" /> 
```

目前这个刷新问题仅存在于IOS部分系统，如IOS16.2，概率较高的偶现。
但其他大部分手机是能正常使用拍照的，可以考虑给用户多个选择，如果无法正常拍照，可以引导他选择相册、文件等。选择方案2较合适。

**Comment by zhuchuanlei** [comment]
这就close了？是怎么解决的呀？

**Comment by funkyfun** [comment]
小程序webview可以试试这个方案
https://mp.weixin.qq.com/s?__biz=MzkwMDM3Njc0MQ==&mid=2247483730&idx=1&sn=4c9ed4e3522ee1e9bbf88ab8b5932fc4&chksm=c045b098f732398ec7056af5236caa09294410f3f17adcd0dd8204c7071c355ddf5cecdf33e2#rd
