### ISSUE TITLE
使用<form>报错：Expected a component class以及用InputItem无法输入内容

### ISSUE THREAD

**Issue by ssjjnn** [ant-design/ant-design-mobile#603]
#### 本地环境

- antd-mobile 版本：0.9.10
- 操作系统及其版本：iOS
- 浏览器及其版本：chrome 版本 54.0.2840.71 (64-bit)

#### 你做了什么？

![image](https://cloud.githubusercontent.com/assets/22025844/20826610/114104a2-b8a7-11e6-97e0-8856d7743e65.png)
![image](https://cloud.githubusercontent.com/assets/22025844/20826629/26fa49fc-b8a7-11e6-8b11-3e8df5d533fc.png)
无法输入内容

然后根据List组件里面的例子，在最外面套了个<form>,报错：Expected a component class

**Comment by ssjjnn** [comment]
在最外面套了个form

**Comment by warmhug** [comment]
react-native 没有 form 标签

**Comment by silentcloud** [comment]
RN  InputItem Android 下面不能输入的话有可能是组件里设置了 maxLength 默认 -1 的原因 https://github.com/ant-design/ant-design-mobile/blob/0.9.x/components/input-item/index.tsx#L21，我先 check 一下，这个我在 master 上已修了 @ssjjnn

**Comment by warmhug** [comment]
把代码也同步到 0.9.x 分支 @silentcloud

**Comment by silentcloud** [comment]
等待 0.9.11 发布

**Comment by ssjjnn** [comment]
![image](https://cloud.githubusercontent.com/assets/22025844/20873115/63962aae-badf-11e6-847b-58ca14c7c451.png)
我升到0.9.11了，可还是有问题，能输进去，但是立马就消失了，就像闪一下
@silentcloud @warmhug

**Comment by ssjjnn** [comment]
![image](https://cloud.githubusercontent.com/assets/22025844/20873493/c2f85712-bae2-11e6-8af6-861faa77355a.png)
这个也是一样的结果
