### ISSUE TITLE
建议popup加入向下滑动关闭的功能

### ISSUE THREAD

**Issue by wr719152280** [ant-design/ant-design-mobile#6033]
### Version of antd-mobile

5.27.0

### What is this feature about?

建议popup加入向下滑动关闭的功能 类似floatingpanel可以通过顶部滑动 但是内容又可以自适应高度

**Comment by miracles1919** [comment]
啥意思？ 你看看 示例 - 自定义样式 - 内容超长滚动 是你想要的不

**Comment by wr719152280** [comment]
> 啥意思？ 你看示范 - 自定义样式 - 内容超长滚动是你想要的不

类似于floatingpanel顶部可以拖动 然后可以拖动关闭 而不是像floatingpanel必须指定高度

**Comment by yinrenzhangsir** [comment]
强烈支持

**Comment by miracles1919** [comment]
这个要考虑的点还蛮多的，看社区有没有同学优化了 ~

- 弹出位置有"向下左右"四个方向
- 很容易跟内容区的手势发生冲突，比如 Picker

---

自己实现也比较容易，我写了个 demo，https://codesandbox.io/s/sharp-turing-of96uh?file=/src/App.tsx

**Comment by HuberTRoy** [comment]
@miracles1919 

感觉沿用大佬这个轻触思路~，上下左右实现起来较为容易，手势冲突上Picker，Slider，超长滚动这些预期行为都是长滑动触发的组件都可以很好的兼容。然后是否可以轻触关闭由一个prop控制(默认为false与旧有行为保持一致)，这样内容区真的有需要轻触的组件与关闭行为冲突了也可以用capture提前捕获设为false来关闭。大佬觉得怎样？(ˊ•͈ ꇴ •͈ˋ)

**Comment by miracles1919** [comment]
@HuberTRoy 可以来个 PR

**Comment by HuberTRoy** [comment]
@miracles1919 

https://github.com/ant-design/ant-design-mobile/pull/6056 提了大佬~。
