### ISSUE TITLE
 使用reduceMotion后下拉刷新不消失

### ISSUE THREAD

**Issue by Emensionyu** [ant-design/ant-design-mobile#6035]
### Version of antd-mobile

5.28.1

### Operating system and its version

iOS

**Comment by zhengjitf** [comment]
repro: https://codesandbox.io/s/pulltorefreshwithskipanimation-onh7n2?file=/app.tsx

问题：下拉释放后一直停留在 complete 状态（"刷新成功"）
<img width="426" alt="image" src="https://user-images.githubusercontent.com/17249775/225180846-f97673a3-e034-420a-a9c0-7241cd2a33e3.png">

原因：这里的 `to` 参数使用异步函数，在设置 skipAnimation 为 true 的情况下，不会被执行（貌似是个 bug 🤔）
https://github.com/ant-design/ant-design-mobile/blob/e0c35eb1cb247d6e998a6bca2249784fb2e34ed0/src/components/pull-to-refresh/pull-to-refresh.tsx#L94-L99

<img width="480" alt="image" src="https://user-images.githubusercontent.com/17249775/225183134-195c7858-e070-4c77-b49e-0c0eef306c04.png">

修复：`to` 使用异步函数，应该是想等动画结束后再更改状态，应该可使用 onResolve 回调实现相同效果

我补下 test，提个 pr 吧

**Comment by Emensionyu** [comment]
下个版本大概什么时候发布

**Comment by miracles1919** [comment]
本周会发个 patch 版本
