### ISSUE TITLE
Vertical Alignement on SVG icon in Button

### ISSUE THREAD

**Issue by Looxor** [ant-design/ant-design-mobile#6039]
### Version of antd-mobile

5.28.1

### Description

Hello Everyone ! 

I have an issue for align custom SVG icon into button.

The Vertical alignement is not well centered even if i apply ( display: flex; align-items: center; ) on the parent space div
It work and centered the text correctly , but never the icon.
I tried a lot of tests on différents parameters , but none of them worked

If you have the solution , i m taker

CodeSandbox here : [https://codesandbox.io/s/winter-monad-brs0vy?file=/app.tsx](url)

<img width="1291" alt="Capture d’écran 2023-03-14 à 4 39 42 PM" src="https://user-images.githubusercontent.com/1319853/225057052-c917b5fd-9188-4f93-86d2-98379a5a80eb.png">
<img width="318" alt="Capture d’écran 2023-03-14 à 4 45 42 PM" src="https://user-images.githubusercontent.com/1319853/225057142-44490191-7213-48d7-b782-b2ef4a253856.png">

**Comment by miracles1919** [comment]
1、svg has extra space below in div, you can set `display: block` or `vertical-align: middle` in svg
ref: https://stackoverflow.com/questions/24626908/how-to-get-rid-of-extra-space-below-svg-in-div-element

2、incorrect props for Space, e.g.
`<Space align="center">`
