### ISSUE TITLE
nextjs中使用阿里云图标切换页面时会变框

### ISSUE THREAD

**Issue by HLDQZ** [ant-design/ant-design-mobile#6049]
### Version of antd-mobile

5.28.1

### Operating system and its version

Others

### Browser and its version

edge

### What happened?

在nextjs项目开发过程中，使用阿里图标库，在切换页面时图标会变成小框，字体颜色也会发生改变

**Comment by miracles1919** [comment]
阿里图标库跟 antd-mobile 有啥关系

**Comment by HLDQZ** [comment]
> 阿里图标库跟 antd-mobile 有啥关系
antd里的global.css会改变图标的样式和页面的字体颜色

**Comment by miracles1919** [comment]
全局样式都是通过 CSS 变量的，不会影响其他内容的，或者你提供个 demo 帮你看看

[codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx)
