### ISSUE TITLE
TextArea设置autoSize后删除文字时，高度未自适应

### ISSUE THREAD

**Issue by Mr-Cui-ZX** [ant-design/ant-design-mobile#6051]
### Version of antd-mobile

5.28.1

### Operating system and its version

iOS, Others

### Browser and its version

Chrome 111.0.5563.64

### Sandbox to reproduce

https://mobile.ant.design/zh/components/text-area

### What happened?

问题现象：TextArea删除文字时高度未自适应
期望现象：TextArea删除文字时高度自适应

**Comment by miracles1919** [comment]
设置下 `autoSize`

**Comment by Mr-Cui-ZX** [comment]
说的就是设置autoSize后的情况，官网的示例可以复现，官网demo是最小3行，最大5行，输入内容超过5行后进行删除，无法恢复到3行

**Comment by wotermelon** [comment]
> 

+1，官网示例也是有bug
