### ISSUE TITLE
Enhance: CheckList Item support custom defaultIcon as extra

### ISSUE THREAD

**Issue by eJayYoung** [ant-design/ant-design-mobile#6055]
### Version of antd-mobile

5.28.0

### What is this feature about?

https://github.com/ant-design/ant-design-mobile/blob/master/src/components/check-list/check-list-item.tsx#L38

能否增加一个 `defaultIcon` prop 用于自定义`CheckList.Item`初始的`extra`
eg: 
```
const extra = (
    <div className={`${classPrefix}-extra`}>
      {active ? context.activeIcon : context.defaultIcon}
    </div>
  )

```

如果可以的话，我可以提个PR

**Comment by eJayYoung** [comment]
> 我建议加个 `extra` prop
> 
> extra: (active ?: boolean) => ReactNode

不过对于后续`activeIcon` prop如何处理，是先和`extra`共存，然后逐步下线吗？还是一直保持共存？

**Comment by miracles1919** [comment]
现在的 `activeIcon` 其实就是 default extra

**Comment by eJayYoung** [comment]
[PR](https://github.com/ant-design/ant-design-mobile/pull/6067) is coming @miracles1919
