### ISSUE TITLE
SwipeAction有没有api去控制显示或不显示

### ISSUE THREAD

**Issue by steven-Zzz** [ant-design/ant-design-mobile#606]
#### 本地环境

- antd-mobile 版本：
      antd-mobile@0.9.8
- 操作系统及其版本：
     mac os 10.11.6
- 浏览器及其版本：
     chrome  54.0.2840.98 
#### 你做了什么？
     我想通过api去操作控制SwipeAction的显示或不显示。

     引入antd-mobile的SwipeAction
#### 你期待的结果是：
     通过一个button去控制SwipeAction的显示或不显示。

#### 实际上的结果：
        官网好像没有提供

**Comment by silentcloud** [comment]
@steven-Zzz  不想显示就设置 disabled

**Comment by steven-Zzz** [comment]
@silentcloud 嗯，但我想通过一个button去操作，比如一个编辑按钮，然后click一下，所有的SwipeAction都全部显示出来。然后再点一下，就全部hide。

**Comment by silentcloud** [comment]
这个暂时没有，因为既然是 swipe，所以应该不会提供手动触发显示的 api

**Comment by steven-Zzz** [comment]
@silentcloud 好的吧，因为我之前用过，然后我以为都会提供，那我找个其他的代替一下。
