### ISSUE TITLE
Toast默认为居中显示能否增加顶部和底部显示的参数配置

### ISSUE THREAD

**Issue by chinacoolboyzz** [ant-design/ant-design-mobile#607]
#### 本地环境

- antd-mobile 版本：0.9.11
- 操作系统及其版本：Android
- 浏览器及其版本：react-native

#### 你期待的结果是：

Toast默认为居中显示能否增加顶部和底部显示的参数配置

**Comment by silentcloud** [comment]
@chinacoolboyzz 目前没有提供位置参数，toast 显示在应用底部或者顶部的场景貌似很少，没怎么见到；如果你希望自己 custom 位置的话，你可以用 `ActivityIndicator` 来做

**Comment by kkkelicheng** [comment]
说实话，不能说因为应用在某些场景的情况比较少就这样敷衍别人。
你就敢一定说你们自己项目不会用这些参数吗？

我现在有这样一个问题
keyboard will mask toast， I want position it to top.

既然你们那么忙，我觉得你们没必要开源出来让我们找bug。

**Comment by warmhug** [comment]
@kkkelicheng 我们也是按照内部设计规范来做的，不可能做到面面俱到。
至于增加配置项 使之更灵活，这是可以讨论和实现的。这不是 bug ，开源除了回馈社区，也希望能得到社区的帮助。希望相互理解！

**Comment by kkkelicheng** [comment]
感谢 reopen
这个不是bug。我措辞可能有点问题，抱歉。
我觉得这个仅仅是个小的调整。
