### ISSUE TITLE
we can't access the component in our mobile as well as your web apitze component its not working

### ISSUE THREAD

**Issue by sakthivgts** [ant-design/ant-design-mobile#6074]
### Version of antd-mobile

11

### Operating system and its version

Android

### What happened?

![Screenshot from 2023-03-28 14-07-13](https://user-images.githubusercontent.com/115778406/228179404-fb8cc3ea-e281-4de8-bdc4-56ac3e47cdf4.png)

**Comment by miracles1919** [comment]
you should go to this repo:https://github.com/ant-design/ant-design-mobile-rn
