### ISSUE TITLE
imageupload在上传失败后还显示了图片

### ISSUE THREAD

**Issue by Dpandaz** [ant-design/ant-design-mobile#6075]
### Version of antd-mobile

5.28.1

### Description

imageupload组件在upload中实现上传方法，当上传失败后怎么去阻止往下进行。如果像我这么写的话，上传失败了，但是还是会显示刚刚上传的图片

![image](https://user-images.githubusercontent.com/86767747/228186026-e5dce514-2906-4f39-8b63-fa4889962792.png)

  
    const [fileList, setFileList] = useState([])    
    const onChange = fileLists => {
          setFileList(fileLists.filter(i => i.url))
        }
  
    const imageUpload = async (file) => {
      const formData = new FormData()
      formData.append('file', file)
      const res = await uploadFileApi(formData)
      if(res.code === 0) {
        return {
          url: res?.data?.url,
          thumbnailUrl: res?.data?.url
        }
      }else {
        Dialog.alert({
          content: `${res.msg || '上传失败，请重新上传'}`,
        })
        return {url: ''}
      }
    }
  
    const uploadProps = {
      onChange: onChange,
      upload: imageUpload,
    }
  
    return (
      <div className='upload-wrap'>
        <ImageUploader
          {...uploadProps}
          value={fileList}
        >
        </ImageUploader>
      </div>
    )

**Comment by Dpandaz** [comment]
在uplod中上传失败之后抛出异常

  `throw new Error('上传失败，请重新上传')`

然后在ImageUpload中加入属性 showFailed: false
果然得多看官方文档

**Comment by Del-te** [comment]
调半天，原来还有这个属性作用 showFailed。pc端的用习惯了，这个和pc端行为不太一致
