### ISSUE TITLE
[SearchBar] suport all Input props in SearchBar

### ISSUE THREAD

**Issue by KingAmo** [ant-design/ant-design-mobile#6076]
### Version of antd-mobile

5.28.1

### What is this feature about?

我想解决 `SearchBar`输入中文时，因输入法合成输入事件触发了多次`onChange`，导致搜索多次的问题。然而 `SearchBar` 组件不支持 `onCompositionEnd ` `onCompositionStart ` 等`props`, 无法解决上述问题。 希望`SearchBar` 组件支持 `Input`组件的所有 `props`

**Comment by miracles1919** [comment]
合成事件做了处理的 

https://github.com/ant-design/ant-design-mobile/blob/548b6a6e9032304a4d4c43b8bc2df9405f6c9f3e/src/components/search-bar/search-bar.tsx#L144-L156

**Comment by KingAmo** [comment]
@miracles1919 
你引用的代码很清晰的显示` onCompositionStart`,  ` onCompositionEnd`没有做处理，我需要这两个事件来处理输入中文时，还在拼写的时候就触发了 `onChange事件`的问题...

**Comment by KingAmo** [comment]
是如下图的问题
![image](https://user-images.githubusercontent.com/29938227/229673705-7ad9990d-3cf8-40b5-97ce-0f9354455ccf.png)

**Comment by miracles1919** [comment]
凹.. 我看错了.. 直接用 `onSearch` 不行么

**Comment by KingAmo** [comment]
不行的，需要知道是否在输入汉字，参见`mdn`文档 [compositionstart](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/compositionstart_event)、[compositionend](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/compositionend_event)

**Comment by miracles1919** [comment]
除了 `onCompositionStart` `onCompositionEnd` 还需要啥？`Input` 的 `props` 太多了，缺啥补啥吧  😯

**Comment by miracles1919** [comment]
也可以来个 PR 支持 ~
