### ISSUE TITLE
Cascader 级联选择能否支持 fieldNames 属性

### ISSUE THREAD

**Issue by lilixikun** [ant-design/ant-design-mobile#6079]
### Version of antd-mobile

5.22.0

### What is this feature about?

Cascader 默认数据类型如下
```typescript
 type CascaderOption = {
  label: string
  value: string
  disabled?: boolean
  childre
}
```
能否支持 fieldNames 属性、支持自定义传入 `label`、`value` 等属性

**Comment by miracles1919** [comment]
那和直接传入 `label`、`value` 有什么区别吗

**Comment by lilixikun** [comment]
> 那和直接传入 `label`、`value` 有什么区别吗

后端数据不能准确给到该字段、需要手动去转换、能够像 antd 一样支持 fieldNames 属性

**Comment by 1587315093** [comment]
> 那和直接传入`label`、`value`有什么区别吗

开发者体验上来说就是少了一个 `map` 处理 这个 `list` 变为 `CascaderOption` 想要的属性

`antd` 那边的`fieldNames` 就是交给组件内部处理了
