### ISSUE TITLE
InputItem输入内容立马消失

### ISSUE THREAD

**Issue by ssjjnn** [ant-design/ant-design-mobile#608]
#### 本地环境

- antd-mobile 版本：0.9.11
- 操作系统及其版本：iOS
- 浏览器及其版本：

#### 你做了什么？

![image](https://cloud.githubusercontent.com/assets/22025844/20911770/7aa6f784-bba5-11e6-806a-790f482de066.png)
![image](https://cloud.githubusercontent.com/assets/22025844/20911776/87202fd0-bba5-11e6-8f0b-5b5634458d73.png)
我升到0.9.11了，可还是有问题，能输进去，但是立马就消失了，就像闪一下，两个结果都一样

**Comment by silentcloud** [comment]
@ssjjnn  

```
onChange={(text) => this.setState({ text })}
```
掉了 `{}`

**Comment by ssjjnn** [comment]
![image](https://cloud.githubusercontent.com/assets/22025844/20912450/6a67c560-bbaa-11e6-80ea-f3a65a50e9d8.png)
结果还是一样额，数字还是立马就消失掉了
@silentcloud

**Comment by afc163** [comment]
```diff
- onchange
+ onChange
```

**Comment by ssjjnn** [comment]
非常不好意思，我太粗心了
