### ISSUE TITLE
rows 设置不生效，默认是两行，期望：根据我设置的rows显示行数

### ISSUE THREAD

**Issue by gq123** [ant-design/ant-design-mobile#6084]
### Version of antd-mobile

5.28.2

### Operating system and its version

iOS

### What happened?

textarea 的 rows 设置不生效，默认是两行，期望：根据我设置的rows显示行数

**Comment by yuanbaojin123** [comment]
我也碰到了这个问题，rows传入1，展示的确实两行。这个问题的解决办法应该是要将传入的rows属性传入给Textarea组件库中隐藏的那个textarea标签。
其次，这个Textarea组件还有一个问题，组件内部模拟的textarea标签应该和实际展示的textarea长度一样，所以，根节点需要加入position：relative这个css样式。不然如果使用宽度不为100%的Textarea组件时，自适应的高度也会有问题。

**Comment by GloryXia** [comment]
me too
