### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by shaniuyan** [ant-design/ant-design-mobile#609]
#### 本地环境

- antd-mobile 版本：
- 浏览器 (或标明是 react-native) 及其版本：
- 操作系统及其版本：

#### 你做了什么？

Toast报错，提示Provider no support changing store on the fly

**Comment by warmhug** [comment]
给出更详细信息，另外包括报错代码截图、堆栈
![image](https://cloud.githubusercontent.com/assets/2011119/20956387/8c66cbc2-bc84-11e6-8b74-db85f1b078ba.png)

**Comment by warmhug** [comment]
没响应，先关掉
