### ISSUE TITLE
DatePicker设置rules的validateTrigger，选择了也会触发错误提示

### ISSUE THREAD

**Issue by GraciaMeng** [ant-design/ant-design-mobile#6098]
### Version of antd-mobile

5.29.0

### Browser and its version

chrome

### Sandbox to reproduce

https://codesandbox.io/s/amazing-feistel-j56oh9?file=/app.tsx

### What happened?

问题：
![image](https://user-images.githubusercontent.com/91103148/231325996-cc773dd1-f084-4512-94bd-3c2e9a56186d.png)
日期组件设置rules的validateTrigger之后，尽管选择了日期也form校验提示错误

期望：
设置validateTrigger且选择日期form校验成功，如果没有选择日期form校验错误并提示错误

**Comment by zombieJ** [comment]
定义一下 type 为 `date`：
https://codesandbox.io/s/cocky-merkle-c2753l?file=/app.tsx
