### ISSUE TITLE
uploader同一张图片不能再次选择

### ISSUE THREAD

**Issue by 214132049** [ant-design/ant-design-mobile#61]
#### 本地环境

- antd-mobile 版本：0.7.2
- 操作系统及其版本：osx 10.11.6 
- 浏览器及其版本：chrome 51.0

#### 你做了什么？
uploader组件，同一张图片，选择后删除，不能再次选择，没有触发onchange事件，官网示例有同样问题

#### 你期待的结果是：
能再次选择

#### 实际上的结果：
不能再次选择

#### 可重现的在线演示
同一张图片，选择后删除，不能再次选择，没有触发onchange事件

**Comment by liqi07** [comment]
@pingan1927 cc 官网可重现

**Comment by pingan1927** [comment]
嗯 我看看

**Comment by qq645381995** [comment]
有重置事件  就可以了

**Comment by yiminghe** [comment]
@pingan1927 看下 https://github.com/react-component/upload ，直接用 require('upload/lib/AjaxUploader')

**Comment by pingan1927** [comment]
@yiminghe 移动端的图片选择组件，后续会进行容器能力加强，如果在容器内，会使用到容器的各种photo API。比如说在支付宝客户端用支付宝容器的`photo` API，在钉钉容器内用钉钉容器的`fetchImageData`API。准确讲，这并不是图片上传组件，而仅仅是图片选择组件。

明天我们再具体讨论下这个组件。

**Comment by silentcloud** [comment]
这个组件命名为 uploder 欠妥，因为仅仅是一个 UI 展现层，并没有实现和后端 ajax 交互，应该改个名称；还有，对于移动端确实不是合 rc 里的 upload，要用到容器，还有 rn 这边 api 的一致性，rn 这边也不能直接 upload base64的

**Comment by yiminghe** [comment]
imagepicker？

**Comment by 214132049** [comment]
Carousel 走马灯  这个组件  里面的图片必须要事先写死吗  不能后台获取的然后遍历出来的？

**Comment by afc163** [comment]
FileInput?

**Comment by silentcloud** [comment]
imagePicker 的名字比较合理，rn 这边其实也就是调用了哈 imagepicker，这个组件仅仅就是选图片然后展示，不存在上传

**Comment by pingan1927** [comment]
`imagePicker`好

**Comment by pingan1927** [comment]
Input的value 每次选择后没有清除，导致下一次选择同一张图片时，`onChange`不会触发，代码已经修复，具体小版本发布请关注下。

**Comment by 214132049** [comment]
👍
