### ISSUE TITLE
Picker or DatePicker 禁止选中的功能

### ISSUE THREAD

**Issue by fladower** [ant-design/ant-design-mobile#610]
- antd-mobile 版本：0.9.x
- 浏览器 (或标明是 react-native) 及其版本：chrome 55.0.2883.75 m
- 操作系统及其版本：win7

Picker or DatePicker 有没有可以将选择内容置灰，禁止选中的功能？我看了源码，貌似没有提供这种方法

**Comment by warmhug** [comment]
放到 m-picker 的 issue 里，这里关闭
