### ISSUE TITLE
Popup + SearchBar issue ,when i use android chrome,  focus searchBar , will open virtual keyboard , But the virtual keyboard will block the popup content 

### ISSUE THREAD

**Issue by li-yu-tfs** [ant-design/ant-design-mobile#6118]
### Version of antd-mobile

5.29.0

### Operating system and its version

Android

### Browser and its version

android chrome

### What happened?

Popup + SearchBar issue ,when i use android chrome,  focus searchBar , will open virtual keyboard , But the virtual keyboard will block the popup content .
then , I used chrome on my computer to debug mobile chrome . I found the html nodes scrollable, drag it to the bottom, popup is on top of the virtual keyboard . 

![chromedebug](https://user-images.githubusercontent.com/108653248/233600651-7ab103e1-2fd7-4db7-9382-a084f0acb87c.png)
![mobile](https://user-images.githubusercontent.com/108653248/233600667-12c54370-7609-4079-99fe-c5fdae696847.jpeg)

**Comment by miracles1919** [comment]
Look like an Android keyborad problem, can you try it with native input ?

**Comment by li-yu-tfs** [comment]
> Look like an Android keyborad problem, can you try it with native input ?

by native input , do you mean HTML5 input tag ?

**Comment by miracles1919** [comment]
yes

**Comment by li-yu-tfs** [comment]
no.  same effect . I think the possible problem is that the popup poisition is fixed

**Comment by li-yu-tfs** [comment]
> yes

no. same effect . I think the possible problem is that the popup poisition is fixed

**Comment by li-yu-tfs** [comment]
i found a solution. 
we can do this in the onFouces callback function of the SearchBar component. 
onFocus={() => {
	setTimeout(() => {
		document.getElementsByClassName('adm-popup')[0].scrollIntoView();
	}, 100);
}}
