### ISSUE TITLE
RN Modal问题

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#612]
#### 本地环境

- antd-mobile 版本：0.9.11
- 浏览器 (或标明是 react-native) 及其版本：RN 0.39.0
- 操作系统及其版本：mac

#### 你做了什么？

![image](https://cloud.githubusercontent.com/assets/6219316/20954500/df71184e-bc76-11e6-90ba-dad453f38cc4.png)

#### 你期待的结果是：

能正常显示

#### 实际上的结果：
只有一个白条
![image](https://cloud.githubusercontent.com/assets/6219316/20954570/6cfc78b6-bc77-11e6-9cfd-6e4fce0c3435.png)

**Comment by warmhug** [comment]
demo 没问题，注意查看下样式设置

**Comment by liubin1023** [comment]
@warmhug 需要增加什么样式

**Comment by warmhug** [comment]
@liubin1023 自己先尝试搞搞

**Comment by chinacoolboyzz** [comment]
我的也是RN0.39同样问题，直接粘贴的官网DEMO代码

**Comment by liubin1023** [comment]
@chinacoolboyzz 我直接改成ReactNative原生的了，antd-mobile的怎么改都不行

**Comment by silentcloud** [comment]
@liubin1023 0.9.x  的 antd-mobile 用 0.34的 rn，rn 官方有不兼容改动的

https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#react-native-使用场景
