### ISSUE TITLE
pickerview能否加入3d效果 或景深效果

### ISSUE THREAD

**Issue by wr719152280** [ant-design/ant-design-mobile#6120]
### What is this feature about?

如题

**Comment by miracles1919** [comment]
欢迎 PR

**Comment by 1587315093** [comment]
你的项目直接给这个类名加景深不能满足需求吗
![image](https://user-images.githubusercontent.com/77056991/233826615-7cae1a84-998c-4138-ad83-8591759d7cdc.png)
