### ISSUE TITLE
表单校验无法达到预期的效果，控制台日志打印出不是一个有效的type的警告

### ISSUE THREAD

**Issue by kennyhonghui** [ant-design/ant-design-mobile#6123]
### Version of antd-mobile

5.29.1

### Operating system and its version

iOS, Android

### Sandbox to reproduce

https://codesandbox.io/embed/interesting-snowflake-v5eiwt?fontsize=14&hidenavigation=1&theme=dark

### What happened?

背景：我这边需要用到其中一个表单字段只允许输入正整数
实现：通过Form.Item 的 rules 中 type:"integer" 实现表单校验
代码：
`<Form
        layout="horizontal"
        footer={
          <Button block type="submit" color="primary" size="large">
            提交
          </Button>
        }
      >
        <Form.Header>水平布局表单</Form.Header>
        <Form.Item
          name="name"
          label="只允许输入整数"
          rules={[
            { required: true, type: "integer", message: "请输入一个整数" }
          ]}
        >
          <Input type="number" min={0} placeholder="只允许输入整数" />
        </Form.Item>
      </Form>`
系统结果：即使输入了一个正整数，仍然无法通过表单校验

前端展示：
![image](https://user-images.githubusercontent.com/10722796/233822656-36a9268f-b303-4b8a-a876-60c952c20b50.png)

控台截获到的日志：
![image](https://user-images.githubusercontent.com/10722796/233822671-95d843cb-87bf-4687-b6d1-d828f1848327.png)

### Relevant log output

```shell
控制台打印出的日志： async-validator: ['${label}不是一个有效的${type}']
```

**Comment by kennyhonghui** [comment]
![image](https://user-images.githubusercontent.com/10722796/233822811-3c46f862-1895-4f2c-b40e-526c603c46fe.png)

**Comment by miracles1919** [comment]
input 的值本身就是 string 类型，要用 `getValueFromEvent` 转换一下
