### ISSUE TITLE
Steps 步骤条使用icon模式，进度线盖在了icon上

### ISSUE THREAD

**Issue by majiang666** [ant-design/ant-design-mobile#6128]
### Version of antd-mobile

5.29.1

### Operating system and its version

iOS, Android

### Browser and its version

ios 安卓都有

### Sandbox to reproduce

官方demo已经有了，参考：https://mobile.ant.design/zh/components/steps/

### What happened?

![image](https://user-images.githubusercontent.com/6973077/234188034-3ba25f69-3962-4bd3-ab73-30c9296dd62f.png)
1：线在一些安卓机上不展示，存在兼容问题，目前解决是重新设置了组件的这根线，但是组件层面解决是最好的
2：线盖在icon上，是因为伪元素和z-index的层级问题，目前尝试:after设置z-index:-1无效，其他办法也有尝试，目前没解决，也希望从组件层面解决，不然开发者需要重置样式
感谢！

**Comment by majiang666** [comment]
不是层级问题，是icon是空心，视觉差

**Comment by 1587315093** [comment]
我觉得是svg绘制的原因，其实换成不透明的图片就可以解决了

**Comment by majiang666** [comment]
> 我觉得是svg绘制的原因，其实换成不透明的图片就可以解决了

1：icon确实是svg空心的问题导致的视觉差，更换就好了
2：线在一些设备上不兼容的问题，通过重新自定义line就好了，需要自己处理

**Comment by 1587315093** [comment]
> 



> > 我觉得是svg绘制的原因，其实换成不透明的图片就可以解决了
> 
> 1：icon确实是svg空心的问题导致的视觉差，更换就好了 2：线在一些设备上不兼容的问题，通过重新自定义line就好了（需要自己处理）



> > 我觉得是svg绘制的原因，其实换成不透明的图片就可以解决了
> 
> 1：icon确实是svg空心的问题导致的视觉差，更换就好了 2：线在一些设备上不兼容的问题，通过重新自定义line就好了（需要自己处理）

第二点可以复现以下然后看看怎么解决
