### ISSUE TITLE
Dialog.show渲染出来的控件无法修改内容

### ISSUE THREAD

**Issue by mu1004** [ant-design/ant-design-mobile#6129]
### Version of antd-mobile

5.29.1

### Operating system and its version

iOS, Android

### Sandbox to reproduce

https://codesandbox.io/s/focused-ardinghelli-bisi59?file=/app.tsx

### What happened?

通过Dialog.show的action中的click操作，对content的内容进行修改， content内容不变。

操作：
例子中，对title的值进行设置，无法生效

**Comment by miracles1919** [comment]
这是一个常见的使用误区哈，看下文档 https://mobile.ant.design/zh/components/dialog#dialogconfirm
