### ISSUE TITLE
List.Item显示不出来

### ISSUE THREAD

**Issue by ssjjnn** [ant-design/ant-design-mobile#613]
#### 本地环境

- antd-mobile 版本：0.9.11
- 浏览器 (或标明是 react-native) 及其版本：iOS
- 操作系统及其版本：

#### 你做了什么？

![image](https://cloud.githubusercontent.com/assets/22025844/20998415/a198cbac-bd48-11e6-8d07-18a346b9f05f.png)
![image](https://cloud.githubusercontent.com/assets/22025844/20998417/a6e75cc2-bd48-11e6-88db-b68001d15c2a.png)
list.item内容无法显示
RN版本是0.39

**Comment by warmhug** [comment]
demo 无此问题，请排查自己环境是否有问题

**Comment by liubin1023** [comment]
@warmhug 同样碰到该问题，antd-mobile和ReactNative 都是最新版

**Comment by ssjjnn** [comment]
我把ReactNative降到0.35可以显示出来，但是用最新的不行

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#react-native-使用场景
