### ISSUE TITLE
ImageUploader 多图上传在微信内置浏览器无效

### ISSUE THREAD

**Issue by wdz6531** [ant-design/ant-design-mobile#6132]
### Version of antd-mobile

5.17.2

### Operating system and its version

Android

### Browser and its version

小米手机，微信内置浏览器

### Sandbox to reproduce

官方 ImageUploader 多图上传

### What happened?

选择单张图片上传测试正常，多图选择后，上传无效

**Comment by miracles1919** [comment]
用原生 input 试试 

`<input type='file' multiple/>`

**Comment by believeZJP** [comment]
> 

安卓手机大部分都不支持多选

**Comment by miracles1919** [comment]
native 不支持就没办法了
