### ISSUE TITLE
noticeBar 加个 onClick 吧

### ISSUE THREAD

**Issue by zhyyyq** [ant-design/ant-design-mobile#6138]
### What is this feature about?

需要点击noticeBar  跳转

**Comment by 1587315093** [comment]
`content` 可以接受一个 `jsx` 能实现自己的 `click` 事件
![image](https://user-images.githubusercontent.com/77056991/236591988-a98c26d3-f1d7-4984-94e3-67c9f931ba89.png)

希望是点击整个 `NoticeBar` 的话确实取药添加
