### ISSUE TITLE
真机兼容性自动化测试服务

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#614]
看到的几个：

https://www.browserstack.com/
腾讯云真机调试：http://wetest.qq.com/product/cloudphone
阿里 https://github.com/alibaba/f2etest

http://www.keynote.com/
同步操作状态：https://browsersync.io/

https://www.xamarin.com/test-cloud  
https://saucelabs.com/

> 调试方法总结：http://yujiangshui.com/multidevice-frontend-debug/

**Comment by benjycui** [comment]
macaca 不考虑么，达峰得多伤心。

**Comment by warmhug** [comment]
需要运行在真机上，能看到页面展示效果的，不是写测试用例的测试

**Comment by warmhug** [comment]
参考内网有人提的利用 Tensorflow 做“截图”测试服务，也可部署到实际业务里

**Comment by paranoidjk** [comment]
since no progress, close.
