### ISSUE TITLE
文档字段描述错误

### ISSUE THREAD

**Issue by one-season** [ant-design/ant-design-mobile#6146]
### Version of antd-mobile

v5.30.0

### What happened?

指南/css变量/方法一：在 CSS 文件中设置

描述是给Input添加一个className

但用的示例组件却是Button，如下图：

![QQ图片20230508163014](https://user-images.githubusercontent.com/59212996/236775736-106172ab-efaa-44d8-84b4-dd23661703d5.png)

**Comment by miracles1919** [comment]
来个 PR

**Comment by one-season** [comment]
来了

**Comment by one-season** [comment]
> 来个 公关

来了。
