### ISSUE TITLE
PullToRefresh 组件下拉时页面元素有明显抖动/掉帧卡顿

### ISSUE THREAD

**Issue by blackskins** [ant-design/ant-design-mobile#6149]
### Version of antd-mobile

5.29.1

### Description
中端和低端机体感有点差，高端机也有点抖
期望1：下拉的阻尼感可以提供一个属性，供开发者自定义设置
期望2：下拉有丝滑的感觉～

**Comment by zombieJ** [comment]
机型提供一下？

**Comment by blackskins** [comment]
> 

OPPO R11s 安卓9 骁龙660

**Comment by blackskins** [comment]
> 机型提供一下？

主要是页面页面元素抖动明显，卡顿这个可以忽略

**Comment by zombieJ** [comment]
> OPPO R11s 安卓9 骁龙660

有录屏么？
