### ISSUE TITLE
image组件在CSR模式，lazy模式生效有问题，会先展示一张空image出来，在触发懒加载逻辑

### ISSUE THREAD

**Issue by 666hxw** [ant-design/ant-design-mobile#6156]
### Version of antd-mobile

5.30.0

### Operating system and its version

Android

### Browser and its version

所有安卓机型

### What happened?

在处理这里[兼容SSR模式下图片不展示的bug](https://github.com/ant-design/ant-design-mobile/issues/5996)引入的，实测了几台安卓手机发现image的complete属性，即使在图片加载过程中也是返回true这样子，会直接展示出来，这样子懒加载的功能就失去意义了；
可以考虑把原来这段代码

> useEffect(() => {
>     if(imgRef.current.complete) {
>       setLoaded(true);
>     }
>   }, []);

改成这样子的写法，兼容SSR模式

> useEffect(() => {
> if (typeof process !== 'undefined' && process.release.name === 'node') {
> setLoaded(true);
> }
> }, []);

### Relevant log output
![image](https://github.com/ant-design/ant-design-mobile/assets/5918116/6caa9332-0e47-407e-9c55-929dd6c1ee45)

_No response_

**Comment by miracles1919** [comment]
可以来个 PR

**Comment by zombieJ** [comment]
来个重现看看哈~

**Comment by 1587315093** [comment]
ssr 判断 window 不行吗
