### ISSUE TITLE
在IOS平台上 所有的transform 动画都很不流畅，存在丢帧问题

### ISSUE THREAD

**Issue by Ruler1020730** [ant-design/ant-design-mobile#6157]
### Version of antd-mobile

5.30.0

### Description

多台设备目前在ios 16(15版本没测试，没有机器)平台上 所有的transform 动画都很不流畅，存在丢帧问题
以下只是部分比较明显的组件：
Dialog、Modal、Popup、ActionSheet...等等涉及到动画的都很卡顿丢帧

官方文档在手机浏览器访问Demo 是一样。自己目前开发的项目，实测在真机(包括用户)也是存在这个问题，希望官方能够解决

**Comment by zombieJ** [comment]
有兴趣来帮忙优化一下不~

**Comment by Ruler1020730** [comment]
> 有兴趣来帮忙优化一下不~

我看issue 其实2022年就有人提出过动画丢帧不流畅的问题，这块好像一直没改
我比较菜，可以先瞅瞅 哈哈

**Comment by 1587315093** [comment]
感觉用了动画库 也没啥优化的地方了吧，或许跟 `useSpring` 的 `config` 数值设置有关系吗 @zombieJ 
```js
 config: {
      precision: 0.1,
      mass: 0.4,
      tension: 300,
      friction: 30,
    },
```

**Comment by Ruler1020730** [comment]
> 感觉用了动画库 也没啥优化的地方了吧，或许跟 `useSpring` 的 `config` 数值设置有关系吗 @zombieJ
> 
> ```js
>  config: {
>       precision: 0.1,
>       mass: 0.4,
>       tension: 300,
>       friction: 30,
>     },
> ```

抱歉，我今天意外的发现 只要开启IOS的省电模式，或者电量低于一定值 才会存在该问题，后面我在源码试了一下换成使用transition 代替 频繁的 transform: translate 能在该情况下也流畅 不会存在省电模式丢帧的情况

**Comment by 1587315093** [comment]
> transition

ios 省电模式确实是这样的，省电模式降低了手机性能，  不过Dialog 弹出的动画有些不流畅是感受到了

**Comment by Ruler1020730** [comment]
> > transition
> 
> ios 省电模式确实是这样的，省电模式降低了手机性能， 不过Dialog 弹出的动画有些不流畅是感受到了

我看了一些其他的移动端组件库，transform: translate 是从0直接到100，再加的transition 做过渡，省电模式就不会出现这种情况，目测应该是ios 对频繁的transform 做了限制 过渡动画没有做处理，表现会更好

**Comment by guangzan** [comment]
实测大多数中端安卓机也存在掉帧现象～

**Comment by KingAmo** [comment]
实测iOS开启`省电模式`，`Popup`、`Modal` 等组件的动画丢帧明显

**Comment by miracles1919** [comment]
试了下发现省电模式下，fps 会锁定在 30（用 `requestAnimationFrame` 算的）

**Comment by 1587315093** [comment]
省电模式锁性能，感觉卡顿正常，平时玩游戏也是一样的，开省电模式会卡

**Comment by 1587315093** [comment]
省电模式下锁性能，很正常
