### ISSUE TITLE
Form表单中Input为number时出现的校验信息

### ISSUE THREAD

**Issue by sagit-zhx** [ant-design/ant-design-mobile#6162]
### Version of antd-mobile

5.28.2

### Operating system and its version

Others

### Browser and its version

Microsoft Edge 版本 113.0.1774.42 (正式版本) (arm64)

### Sandbox to reproduce

https://codesandbox.io/embed/relaxed-babbage-rl5tec?fontsize=14&hidenavigation=1&theme=dark

#### 在demo中，提供了一个简易表单，包括
- `<Input type='number' />`
- `<Button type='submit'>提交</Button>`

#### 问题描述：
- 输入小数，并在按下回车的时候，该Input的校验提示如下（没有设置任何rules规则，点击提交的时候没有问题）
![image](https://github.com/ant-design/ant-design-mobile/assets/112457263/192b120d-02a1-4dc6-bab4-1a56bb00215c)
![image](https://github.com/ant-design/ant-design-mobile/assets/112457263/b1276934-db71-459f-9cc3-54ab33272517)
![image](https://github.com/ant-design/ant-design-mobile/assets/112457263/3108fb5e-0259-4f87-a77e-d5cc4e532fbc)

#### 操作如下
1. 在Input中输入任意数字（整数或小数）
2. 按下提交Button
3. 在Input中修改数字
4. 按下回车（不点击Button），出现图中提示（若操作1输入的是整数，则提示只能输入整数；若操作1输入的是小数，则提示本输入框只能输入小数点后与操作1一样的小数）

- 它不影响按下提交Button的校验以及后续操作，但是在按下回车后会出现
- 每次按下提交Button就会以当前值作为它的提示规则

**Comment by 1587315093** [comment]
你需要给 `Input` 设置一个 `step` 属性
![image](https://github.com/ant-design/ant-design-mobile/assets/77056991/ba9e4a16-22ce-4a2c-a836-d6dcfae00801)

**Comment by sagit-zhx** [comment]
> 你需要给 `Input` 设置一个 `step` 属性 ![image](https://user-images.githubusercontent.com/77056991/238352831-ba9e4a16-22ce-4a2c-a836-d6dcfae00801.png)

谢谢建议。但从使用规范标准来看我不必为我的Input设置setup；从业务角度而言我的Input需要录入WGS84经纬度坐标，它可以是小数点后无穷位数的值

**Comment by miracles1919** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/22469543/5d2ccfe8-7c2f-44da-8062-cf7300b978f7)

看起来就是浏览器行为，用原生 input 试了下就是这样的

**Comment by zombieJ** [comment]
感觉是需要 preventDefault 一下，原生校验的确是没有必要。

**Comment by miracles1919** [comment]
https://codesandbox.io/s/cranky-night-22l46w?file=/src/App.js

试了下原生 `form`、`input type="number"` 浏览器会自动校验的

![image](https://github.com/ant-design/ant-design-mobile/assets/22469543/82953e04-aa2c-4e21-b7a5-b3cc0b10672e)

不过发现了一个属性 `noValidate`，加上去就不校验了

**Comment by sagit-zhx** [comment]
> https://codesandbox.io/s/cranky-night-22l46w?file=/src/App.js
> 
> 试了下原生 `form`、`input type="number"` 浏览器会自动校验的
> 
> ![image](https://user-images.githubusercontent.com/22469543/245692695-82953e04-aa2c-4e21-b7a5-b3cc0b10672e.png)
> 
> 不过发现了一个属性 `noValidate`，加上去就不校验了

原生form中确实可以，但ant-d的form并不支持该属性，且还需要ant-d-form其他校验功能

**Comment by miracles1919** [comment]
原生属性都支持的，而且 `noValidate` 并不影响 Form 组件的校验

**Comment by sagit-zhx** [comment]
> 

👌明白了，非常感谢
