### ISSUE TITLE
ImageUploader图片选择不触发beforeUpload 

### ISSUE THREAD

**Issue by renzp94** [ant-design/ant-design-mobile#6167]
### Version of antd-mobile

5.28.2

### Operating system and its version

Android

### What happened?

问题：
App通过webview加载前端页面，当设置accept="image/*"时，可以调起相册选择，但是选择之后回到应用中时没有触发beforeUpload，而且再次点击之后无法调起相册或者照相机。
期望：
选择相册之后，可以触发beforeUpload

**Comment by renzp94** [comment]
我试了浏览器内打开网站可以触发，是不是因为套壳的权限不够？

**Comment by renlimina** [comment]
我遇到一个问题是这个组件拍照可以成功上传图片 ，但是从图库中选择的话缺不能上传图片，目前不确定的是哪款手机型号

**Comment by miracles1919** [comment]
看起来是容器的问题，试试原生 `<input type='file' />` 的 onChange 事件能否触发，beforeUpload 就是在 onChange 里判断的
