### ISSUE TITLE
无法添加 id 属性吗?

### ISSUE THREAD

**Issue by 1587315093** [ant-design/ant-design-mobile#6169]
### Description

![image](https://github.com/ant-design/ant-design-mobile/assets/77056991/222ca7c1-3568-4c16-ab51-8f66863e5f57)

不能将类型“{ children: string; id: string; }”分配给类型“IntrinsicAttributes & { color?: "default" | "primary" | "success" | "warning" | "danger" | undefined; fill?: "none" | "solid" | "outline" | undefined; size?: "small" | ... 3 more ... | undefined; ... 8 more ...; children?: ReactNode; } & Pick<...> & { ...; } & AriaAttributes & RefAttributes<...>”。
  类型“IntrinsicAttributes & { color?: "default" | "primary" | "success" | "warning" | "danger" | undefined; fill?: "none" | "solid" | "outline" | undefined; size?: "small" | ... 3 more ... | undefined; ... 8 more ...; children?: ReactNode; } & Pick<...> & { ...; } & AriaAttributes & RefAttributes<...>”上不存在属性“id”。ts(2322)

**Comment by miracles1919** [comment]
可以支持一波~
