### ISSUE TITLE
Stepper ReactNative Android

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#617]
#### 本地环境

- antd-mobile 版本：0.9.11
- 浏览器 (或标明是 react-native) 及其版本：0.39  android 4.4.2
- 操作系统及其版本：mac

#### 你做了什么？
引入Stepper
![image](https://cloud.githubusercontent.com/assets/6219316/21006165/9d6ffb3e-bd72-11e6-857e-ad6448c52244.png)

#### 你期待的结果是：
正常显示和操作

#### 实际上的结果：
可以正常显示，但不能操作

**Comment by silentcloud** [comment]
0.9.11 使用 rn0.34 的版本，官方从 0.36 做了不兼容改动，要用0.39 目前只能用 1.0 alpha

https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#react-native-使用场景
