### ISSUE TITLE
5.30.0版本安装后报错，提示【runes2】没有默认导出。

### ISSUE THREAD

**Issue by SonDemigods** [ant-design/ant-design-mobile#6170]
### Version of antd-mobile

13

### What happened?

安装最新版本的包之后，会报错。提示【runes2】没有默认导出。
5.29.1版本不存在这个问题。

### Relevant log output

```shell
./node_modules/antd-mobile/es/components/ellipsis/ellipsis.js
Attempted import error: 'runes2' does not contain a default export (imported as 'runes').
```

**Comment by 1587315093** [comment]
具体咋出现的，我 npm yarn pnpm 都试了没出现呀
或者试试重新下一边包能不能解决

**Comment by SonDemigods** [comment]
这是报错的示例：[https://github.com/SonDemigods/bug-6170.git](https://github.com/SonDemigods/bug-6170.git)

启动报错信息：
```
./node_modules/antd-mobile/es/components/ellipsis/ellipsis.js
Attempted import error: 'runes2' does not contain a default export (imported as 'runes').
```

现在的package.json配置如下：
```
"antd-mobile-v5": "npm:antd-mobile@5.30.0",
```
修改为如下配置后不报错：
```
"antd-mobile-v5": "npm:antd-mobile@5.29.1",
```

**Comment by 1587315093** [comment]
试试   "antd-mobile": "^5.30.0",

**Comment by 1587315093** [comment]
> 这是报错的示例：https://github.com/SonDemigods/bug-6170.git
> 
> 启动报错信息：
> 
> ```
> ./node_modules/antd-mobile/es/components/ellipsis/ellipsis.js
> Attempted import error: 'runes2' does not contain a default export (imported as 'runes').
> ```
> 
> 现在的package.json配置如下：
> 
> ```
> "antd-mobile-v5": "npm:antd-mobile@5.30.0",
> ```
> 
> 修改为如下配置后不报错：
> 
> ```
> "antd-mobile-v5": "npm:antd-mobile@5.29.1",
> ```

试试    
```bash
 "antd-mobile": "^5.30.0",
```

**Comment by miracles1919** [comment]
重新 install 下，`runes` 升级成 `runes2` 了

**Comment by SonDemigods** [comment]
> > 这是报错的示例：https://github.com/SonDemigods/bug-6170.git
> > 启动报错信息：
> > ```
> > ./node_modules/antd-mobile/es/components/ellipsis/ellipsis.js
> > Attempted import error: 'runes2' does not contain a default export (imported as 'runes').
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 现在的package.json配置如下：
> > ```
> > "antd-mobile-v5": "npm:antd-mobile@5.30.0",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 修改为如下配置后不报错：
> > ```
> > "antd-mobile-v5": "npm:antd-mobile@5.29.1",
> > ```
> 
> 试试
> 
> ```shell
>  "antd-mobile": "^5.30.0",
> ```

这个项目混用了v2和v5。所以不能直接升级。
```
"antd-mobile": "^2.3.1",
"antd-mobile-v5": "npm:antd-mobile@5.30.0",
```
之前试过，全都替换成v5也会报这个错。

**Comment by SonDemigods** [comment]
> 重新 install 下， 升级成 了`runes``runes2`

安装v5.30.0版本后，已经重新安装过依赖。
.lock文件如下：
```
"node_modules/runes2": {
      "version": "1.1.2",
      "resolved": "https://registry.npmmirror.com/runes2/-/runes2-1.1.2.tgz",
      "integrity": "sha512-v6XIdRpUKdFLNhgF2AC9XvntZsDzxyTpVlpQ8HD592XD6vHiW8jEcHFnTV5ztUjWJC5cGOcdi9YKIwxWVh0f9w=="
    },
```

**Comment by miracles1919** [comment]
看起来就是这个脚手架不支持 `import runes from 'runes2'`
