### ISSUE TITLE
nextjs v13 没有样式

### ISSUE THREAD

**Issue by yejiang1015** [ant-design/ant-design-mobile#6172]
### Version of antd-mobile

5.30.0

### Operating system and its version

iOS, Android

### What happened?

nextjs v13.4.3
antd-mobile 5.30.0

没有样式

### Relevant log output

```shell
[antd-mobile: Global] The px tester is not rendering properly. Please make sure you have imported `antd-mobile/es/global`.
```

**Comment by cwjjjjj** [comment]
我也遇见了

**Comment by bigbigbo** [comment]
+1

**Comment by afc163** [comment]
我这个 codesandbox 里看着是好的，是么？

**Comment by miracles1919** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/22469543/0020d372-fdc2-4875-b570-6aa9fead79a6)

这个蓝色的就是样式呀

**Comment by cwjjjjj** [comment]
但是我每次使用 antd 组件的时候都需要引入一下这个文件吗

**Comment by miracles1919** [comment]
我自己试了下是不用的，参考 https://github.com/miracles1919/antd-mobile-examples/tree/master/next-13

可能是 codesandbox 的问题

**Comment by bigbigbo** [comment]
> 我自己试了下是不用的，参考 https://github.com/miracles1919/antd-mobile-examples/tree/master/next-13
> 
> 可能是 codesandbox 的问题

我看demo中，next.config.js已经不需要配置`transpilePackages: ['antd-mobile'],`了吗？我把这个配置删除之后倒是没再出现这个提醒了

**Comment by dislido** [comment]
看起来是因为`import {xxx} from 'antd-mobile'`在模块解析时变成直接引入了`antd-mobile/es/components/xxx`, 没有通过`antd-mobile/es/index`,而`antd-mobile/es/global`是在`antd-mobile/es/index`中引入了

**Comment by Ruler1020730** [comment]
实测 开发环境  使用 --turbo 会有样式 也不用 引入antd-mobile/es/global， webpack模式还得按照官网12的方式走 才有样式

**Comment by miracles1919** [comment]
这个应该是 nextjs 的问题，使用 `next: 13.4.6` 或最新的版本无需 `import antd-mobile/es/global`

--- 

经过我的测试发现（`next: 13.4.5` ），`page` 如果不使用 css module 或 import css，就不会生成 `page.css`，从而丢失了 mobile 的样式

```jsx
'use client';

import { Button } from 'antd-mobile';

export default function Home() {
  return (
   <main>
     <Button>btn</Button>
   </main>
  }
)
```

--- 

解决方法1：使用最新版本 nextjs

解决方法2：使用 css module

```diff
'use client';

import { Button } from 'antd-mobile';
+ import styles from './page.module.css';

export default function Home() {
  return (
+   <main className={styles.main}>
     <Button>btn</Button>
   </main>
  }
)

```

解决方法3：在 layout 加载 global 样式

```diff
// layout.tsx
+ import 'antd-mobile/es/global';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

```
