### ISSUE TITLE
[input] input组件 当 type=number 时，无法输入纯数字的内容

### ISSUE THREAD

**Issue by 13725102796** [ant-design/ant-design-mobile#6175]
### Version of antd-mobile

最新版本

### What is this feature about?

希望加多一个属性，支持原生input的内容
<img width="784" alt="WeChat67c0feb3dbfd8f23be6c33b982d8ccc7" src="https://github.com/ant-design/ant-design-mobile/assets/23430123/db85e1a7-4df4-4ad6-8234-9f3d7d2d1ec7">

``` bash 
#  原生是支持 输入 0 开头的数字的，在某些纯数字验证码场景，会导致0开头的验证码自动过滤掉
#  原因是在 onBlur 时 parseFloat 了输入的值
# components/input/input.tsx     - line:121
function checkValue() {
    let nextValue = value
    if (props.type === 'number') {
      nextValue =
        nextValue &&
        bound(parseFloat(nextValue), props.min, props.max).toString()
    }
    if (nextValue !== value) {
      setValue(nextValue)
    }
  }

```
而且原生的input框，在设置number类型时，貌似也不会出现 #6162 的问题

**Comment by 1587315093** [comment]
>而且原生的input框，在设置number类型时，貌似也不会出现 https://github.com/ant-design/ant-design-mobile/issues/6162 的问题

原生 input 就有哦

![image](https://github.com/ant-design/ant-design-mobile/assets/77056991/8bbf0917-8009-4f14-90df-b228ef021837)

**Comment by 13725102796** [comment]
> > 而且原生的input框，在设置number类型时，貌似也不会出现 #6162 的问题
> 
> 原生 input 就有哦
> 
> ![image](https://user-images.githubusercontent.com/77056991/240480014-8bbf0917-8009-4f14-90df-b228ef021837.png)

你试着创建一个普通的html 试试
