### ISSUE TITLE
我用dva框架，antd-mobile组件写得H5页面在支付宝的浏览器里打开是一片空白

### ISSUE THREAD

**Issue by small752** [ant-design/ant-design-mobile#618]
我用dva框架，antd-mobile组件写得H5页面在支付宝的浏览器里打开是一片空白，
其他浏览器都是正常显示的。
之前同事说是不能用calc函数，但是我去掉这个函数还是显示不了。  不是缓存的原因。

**Comment by warmhug** [comment]
没遇到过 calc函数，这种 “太泛” 的问题不解答，请仔细看相关使用文档
