### ISSUE TITLE
SwipeAction 的 Action 被点击后若执行 setState, 后续子组件的事件会被劫持无法执行

### ISSUE THREAD

**Issue by lwQin** [ant-design/ant-design-mobile#6184]
### Version of antd-mobile

5.30.0

### Operating system and its version

iOS, Android, Others

### Browser and its version

PC Chrome 113

### Sandbox to reproduce

https://codesandbox.io/s/happy-butterfly-es1i1z

### What happened?

复现步骤
- 正常点击列表项有日志输出
- 滑动之后点击编辑显示出弹出层
- 点击蒙层关闭弹出层后点击原本的列表项无法点击和输出日志
- 滑动原本的列表项后恢复可点击

![屏幕录制2023-05-30 10 20 27](https://github.com/ant-design/ant-design-mobile/assets/11586662/770712ef-947c-4efb-9edb-58c9dc5b5255)

**Comment by linjson** [comment]
不是跟Popup配合有问题,只要执行setXXXX方法都有问题

**Comment by 1587315093** [comment]
感觉是react-spring/web 的问题 ，给他们提了 issue 

复现 https://codesandbox.io/s/awesome-joana-t28gsz?file=/src/App.tsx

**Comment by 1587315093** [comment]
https://github.com/pmndrs/react-spring/issues/2187

**Comment by caocong1** [comment]
有个治标不治本的方式是加个setTimeout(fn, 0)
```
onClick: () => {
  setTimeout(() => {
    setVisible(true);
  }, 0);
}
```
或者在swipe-action源码里给子组件外的animated.div用memo做个缓存
[https://github.com/ant-design/ant-design-mobile/blob/master/src/components/swipe-action/swipe-action.tsx#L249](https://github.com/ant-design/ant-design-mobile/blob/master/src/components/swipe-action/swipe-action.tsx#L249)
```
            {React.useMemo(() => (
              <animated.div
                style={{
                  pointerEvents: x.to(v =>
                    v !== 0 && x.goal !== 0 ? 'none' : 'auto'
                  ),
                }}
              >
                {props.children}
              </animated.div>
            ), [x, props.children])}
```

**Comment by 1587315093** [comment]
> 有个治标不治本的方式是加个setTimeout(fn, 0)
> 
> ```
> onClick: () => {
>   setTimeout(() => {
>     setVisible(true);
>   }, 0);
> }
> ```
> 
> 或者在swipe-action源码里给子组件外的animated.div用memo做个缓存 https://github.com/ant-design/ant-design-mobile/blob/master/src/components/swipe-action/swipe-action.tsx#L249
> 
> ```
>             {React.useMemo(() => (
>               <animated.div
>                 style={{
>                   pointerEvents: x.to(v =>
>                     v !== 0 && x.goal !== 0 ? 'none' : 'auto'
>                   ),
>                 }}
>               >
>                 {props.children}
>               </animated.div>
>             ), [x, props.children])}
> ```
应该开发者自己加setTimeout包裹set更合适
