### ISSUE TITLE
feature: full support Preact

### ISSUE THREAD

**Issue by cbbfcd** [ant-design/ant-design-mobile#6185]
### Version of antd-mobile

5.30.0

### What is this feature about?

`preact/compat` 没有导出 `isFragment` 的方法，看是否有必要 `antd-mobile` 内部处理一下。如果有这个必要，我可以提一个 `PR`

**Comment by miracles1919** [comment]
欢迎 PR 👏🏻

**Comment by cbbfcd** [comment]
我觉得应该是 Preact 去兼容最新的 react-is 更合适，我给 Preact 提 PR 修复一下。

**Comment by cbbfcd** [comment]
https://github.com/preactjs/preact/releases/tag/10.17.0 PR 合入，preact 已经支持到
