### ISSUE TITLE
CascadePickerView组件onChange事件bug：初始化自动执行一次

### ISSUE THREAD

**Issue by slivens** [ant-design/ant-design-mobile#6188]
### Version of antd-mobile

5.30.0

### Sandbox to reproduce

https://codesandbox.io/s/elastic-black-p18kk8?file=/app.tsx:36-53

### What happened?

CascadePickerView组件onChange事件bug：初始化自动执行一次

**Comment by kampiu** [comment]
我看他的设计就是当初始化value不存在的时候，默认value选中的就是所有options的第一个，那就是 [ 0, 0 ]。方便说一下你的业务需求吗，我可以提供点建议。

**Comment by miracles1919** [comment]
这是预期行为，因为你没设置初始 value，所以当成 `[]` 处理。而 Picker 组件会默认选择第一项，所以触发了 `onChange`

你可以设置一个默认的 value，这样初始化的时候就不会触发 `onChange` 了
