### ISSUE TITLE
在input 设置为 type='number' 与 type='email' 之类的确实会出现意外的提示

### ISSUE THREAD

**Issue by 1587315093** [ant-design/ant-design-mobile#6196]
### Version of antd-mobile

5.30

### Description

 像 #6162 这样，自己开发加 email 时也看到了

![74bcb93bd8f72270185a8e311934e64](https://github.com/ant-design/ant-design-mobile/assets/77056991/491997eb-807d-4226-b8be-c2a4d1d009a6)

目前就是不加 type 了，警告就没有，那应该是原生自带的警告吧~

测试了一下 antd 的 input 加type 不会出现，可能是终端也有区别吗

**Comment by zombieJ** [comment]
印象里是调用 Form 的 validate 才会有，默认不会去校验。
https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#the_required_attribute

**Comment by 1587315093** [comment]
> https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#the_required_attribute

是的，确实实在 Form 中使用就会出现·

**Comment by miracles1919** [comment]
https://github.com/ant-design/ant-design-mobile/issues/6162#issuecomment-1590534947
