### ISSUE TITLE
form是否能支持静默校验

### ISSUE THREAD

**Issue by zjcrender** [ant-design/ant-design-mobile#6197]
### Version of antd-mobile

5.30.0

### What is this feature about?

form表单能不能提供一个不触发error describe的校验方法，只是返回是否校验通过

**Comment by miracles1919** [comment]
`hasFeedback` 文档有写的

![image](https://github.com/ant-design/ant-design-mobile/assets/22469543/92fd6c99-b0cf-47d1-857d-2c69d7debc54)
