### ISSUE TITLE
如何手动出触发 form.array 表单中的某一项校验

### ISSUE THREAD

**Issue by 1455287434** [ant-design/ant-design-mobile#6199]

**Comment by 1587315093** [comment]
用 ` form.validateFields([""]);` 传入需要校验的字段名
![image](https://github.com/ant-design/ant-design-mobile/assets/77056991/cb28c2f0-4425-4f7b-997a-a974d0d1fc60)

**Comment by 1455287434** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/60095252/1af80ca0-b07c-4e51-bba7-e73621a53b28)
手动校验这种**带index的name**
