### ISSUE TITLE
在react native－android下 warning Button 无效，Toast 无法找到图片资源

### ISSUE THREAD

**Issue by qiuchengw** [ant-design/ant-design-mobile#62]
#### 本地环境

- antd-mobile 版本：0.7.3
- 操作系统及其版本：osx 10.11.6 ／ react native: 0.31.0 / react : 15.2.1 / android : 4.4+
- 浏览器及其版本：无（react native端）

#### 你做了什么？

引入了Toast和Button，并执行：
`
   <Button type='warning' onClick={()=>Toast.fail('xxxx')}>click</Button>
`

#### 你期待的结果是：

显示warning button，点击后显示一个toast 提示。

#### 实际上的结果：

1，Warning Button显示不正常, 警告信息为：“Failed prop type, invalid prop type of value 'warning' supplied to Button, expected one of ['primary', 'default']”

2，Toast显示错误，错误信息：‘Require unknown module './images/success.png' ....’

#### 可重现的在线演示
使用mobile demo，引入以下代码即可重现：
`
   <Button type='warning' onClick={()=>Toast.fail('xxxx')}>click</Button>
`

**Comment by liqi07** [comment]
1. type类型是 ['primary', 'default']中的一个，没有warning. 
 
2. Toast图片资源问题 @silentcloud cc

**Comment by silentcloud** [comment]
Get! 正在弄！

**Comment by silentcloud** [comment]
Button 无 warning 类型；
Toast 图片报错问题，工具已经升级；下个版本应该 ok 的

**Comment by qiuchengw** [comment]
@silentcloud 好的。了解了。
我是看到官方网站的Button例子中有写 type=“warning”，所以以为RN版本也是有的。看来是只有web端才有。

不过话说回来，为什么web端有这个类型，而RN端不给提供呢？

**Comment by warmhug** [comment]
@qiuchengw 我看看能否加下
