### ISSUE TITLE
Toast中的loading 图标问题

### ISSUE THREAD

**Issue by aimaodeyuer** [ant-design/ant-design-mobile#621]
#### 本地环境

- antd-mobile 版本：0.9.11
- 浏览器 (或标明是 react-native) 及其版本：ios微信自带浏览器 chrome移动界面调试工具
- 操作系统及其版本：ios微信X5 

#### 你做了什么？

引入了antd.mobile的Toast

#### 你期待的结果是：

像官网一样正常显示 

#### 实际上的结果：

图片是一个图钉，不是loading
![image](https://cloud.githubusercontent.com/assets/12092562/21044500/49898466-be37-11e6-9205-ab9b46d6fe61.png)

**Comment by benjycui** [comment]
大头针同学乱入很多次了。。

**Comment by aimaodeyuer** [comment]
@benjycui  so ... 咋解决

**Comment by warmhug** [comment]
是不是引入了其他字体文件和样式、把这个覆盖了？

**Comment by warmhug** [comment]
没反馈，先关掉

**Comment by vnice** [comment]
@ warmhug 相同的问题。在内网中按照本地部署 Iconfont的方式引入下载的iconfont文件后发现图标对不上。loading这个图标的content ‘\E6A1’在 https://ant.design/docs/resource/download下载的webfont文件中是一个图钉。
