### ISSUE TITLE
antd-mobile Ellipsis多行省略有问题

### ISSUE THREAD

**Issue by 123liyuan123** [ant-design/ant-design-mobile#6211]
### Version of antd-mobile

5.31.0

### Description

<Ellipsis
                            direction="end"
                            rows={3}
                            content={cons}
                            expandText={
                                <>
                                    展开
                                    < DownOutline  />
                                </>
                            }
                        />
省略效果直接失效，文本全部被展示出来
![b15f1d8c2503b78af41c23bfd16bb97](https://github.com/ant-design/ant-design-mobile/assets/33047039/123012a1-fb70-4aa1-b412-82389841b736)

**Comment by miracles1919** [comment]
我试了下是正常的 

https://codesandbox.io/s/exciting-nightingale-92zy9m?file=/app.tsx&resolutionWidth=320&resolutionHeight=675
