### ISSUE TITLE
antd-mobile not working

### ISSUE THREAD

**Issue by cslim0527** [ant-design/ant-design-mobile#6214]
### Version of antd-mobile

^5.31.1

**Comment by vitalijalbu** [comment]
<img width="998" alt="Screenshot 2023-06-28 alle 10 48 38" src="https://github.com/ant-design/ant-design-mobile/assets/40239902/1648574a-9699-4e6e-972c-4b5bb6108b4b">

Just installed the library and got this error

**Comment by miracles1919** [comment]
@vitalijalbu https://github.com/ant-design/ant-design-mobile/issues/5220#issuecomment-1133872039
