### ISSUE TITLE
ListView onEndReached 没有初次加载

### ISSUE THREAD

**Issue by zhangda47** [ant-design/ant-design-mobile#622]
#### 本地环境

- antd-mobile 版本：0.9.11
- 浏览器 (或标明是 react-native) 及其版本：mac chrome 54、 ios 10.1.1 chrome & safari
- 操作系统及其版本：同上

#### 你做了什么？
使用自定义容器
页面没有初次加载，rn 文档说初始值为空也会渲染
手动下拉加载时，加载第二页会不断刷新(一个请求完了之后，继续请求)，只有在下拉之后，再上拉回一点才不会继续请求

代码有点长，我认为可能是使用的姿势不对

``` jsx
class ReceiptList extends React.Component {
  constructor (props) {
    super(props)
    this.dataSource = new ListView.DataSource({
      rowHasChanged: (row1, row2) => row1.receipt_id !== row2.receipt_id
    })
    this.state = {
      isLoading: false,
      pageNum: 1,
      previewImageUrl: null,
      dataSource: this.dataSource.cloneWithRows(props.er_receipts)
    }
  }

  async getCurrentReceipts (e) {
    console.log(e)
    if (this.state.isLoading) {
      return
    }

    const getUrl = API_GET_CURRENT_USER_RECEIPTS + '?' + queryString.stringify({
        begin_index: (this.state.pageNum - 1) * 10,
        end_index: (this.state.pageNum - 1) * 10 + 9
      })
    Toast.loading('正在加载')
    this.setState({isLoading: true})
    const {result:{er_receipts}} = await fetchData(getUrl, {credentials: 'include'})
    this.setState({isLoading: false})
    Toast.hide()

    if (er_receipts.length) { // 有返回结果，页码 + 1
      this.setState({pageNum: ++this.state.pageNum})
      this.props.saveReceipts([...this.props.er_receipts, ...er_receipts])
    }

    this.setState({
      dataSource: this.dataSource.cloneWithRows(this.props.er_receipts),
      isLoading: false
    })
  }

  renderListViewRow (rowData) {
    const urlSplits = rowData.file_url.split('/')
    const fileName = urlSplits[urlSplits.length - 1]
    const fileUrl = `/expense_reimbursement/files/${fileName}`

    return (
      <SwipeAction
        key={rowData.receipt_id}
        autoClose
        right={[{
          text: '删除',
          onPress: () => console.log('删除'),
          style: {backgroundColor: '#F4333C', color: 'white'},
        }]}
      >
        <ListViewItem imageUrl={fileUrl} title={rowData.receipt_name} desc={rowData.receipt_desc}
                      onClickImage={::this.handleClickImage}/>
        <Modal
          onClose={() => {
            this.setState({previewImageUrl: null})
          }}
          visible={!!this.state.previewImageUrl}
          animated={false}
        >
          <img className={classes.modalImage} src={this.state.previewImageUrl}/>
        </Modal>
      </SwipeAction>

    )
  }

  render () {
    if (location.pathname === '/expense_reimbursement/receipt/add') {
      return this.props.children
    } else {
      return (
        <ListView
          dataSource={this.state.dataSource}
          renderHeader={() => <span>发票列表</span>}
          renderRow={::this.renderListViewRow}
          renderSeparator={this.renderListViewSeparator}
          onEndReached={::this.getCurrentReceipts}
          onEndReachedThreshold={30}
          style={{
            height: document.body.clientHeight - 190,
            overflow: 'auto',
          }}
          pageSize={10}
        />
      )
    }
  }
}
```
#### 实际上的结果：
![](http://115.159.120.229:8000/f/7501a9f617/?dl=1)

**Comment by zhangda47** [comment]
第二页不断刷新的问题解决， event.preventDefault()
目前还有第一页没有默认刷新
![](http://115.159.120.229:8000/f/3dda74d511/?dl=1)

**Comment by warmhug** [comment]
页面没有初次加载。 确认有没有数据传进来？

**Comment by zhangda47** [comment]
@warmhug 只有在拖动容器div的时候才会加载，代码中的fetch方法只在onEndReached中调用了

**Comment by wongben** [comment]
@zhangda47 而且在拖动div有时会不停发送请求这个我也遇到，我的代码如下：
import { ListView } from 'antd-mobile';
import React, { PropTypes } from 'react';
import PoolItem from './PoolItem';

import styles from './PoolList.less';

const poolListView = ({ dataSource, isLoading, onEndReached }) => {
  const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });
  const renderRow = (rowData, sectionId, rowId) => (<PoolItem rowData={rowData} sectionId={sectionId} rowId={rowId} />);
  //列表Footer

  console.info('poolListView isLoading', isLoading);
  const renderFooter = () => (<div style={{ padding: 5, textAlign: 'center' }}>
    {isLoading ? '加载中...' : '加载完毕'}</div>);

  return (
    <div className={styles.listView}>
      <ListView
        style={{ flex: 1 }}
        dataSource={ds.cloneWithRows(dataSource)}
        useBodyScroll
        renderRow={renderRow}
        renderFooter={renderFooter}
        scrollRenderAheadDistance={900}
        onEndReached={onEndReached}
        onEndReachedThreshold={600}
        initialListSize={12}
        pageSize={20}
        scrollEventThrottle={30}
      />
    </div>
  );
};

export default poolListView;

----------------------------------------------------------------
import React, { PropTypes } from 'react';
import { connect } from 'dva';
import PoolList from '../components/Pools/PoolList';
import styles from './Pools.less';

const Pools = ({ location, dispatch, pools }) => {
  const { dataSource, isLoading, pageNo, pageSize, total, currentItem } = pools;
  const onEndReached = (event) => {
    if (!isLoading) {
      dispatch({
        type: 'pools/query',
        payload: { pageNo: pageNo + 1, pageSize }
      });
    }
  };
  const poolListProps = { dataSource, onEndReached, isLoading };
  return (
    <div className={styles.normal}>
      <PoolList {...poolListProps} />
    </div>
  );
};


Pools.propTypes = {
};

const mapStateToProps = ({ pools }) => ({ pools });

export default connect(mapStateToProps)(Pools);

**Comment by warmhug** [comment]
#541

**Comment by warmhug** [comment]
不停发请求没问题 https://github.com/ant-design/ant-design-mobile/issues/520#issuecomment-263510596

**Comment by warmhug** [comment]
> rn 文档说初始值为空也会渲染
这里文档链接发下，为空渲染什么？

**Comment by zhangda47** [comment]
@warmhug 
我发现在0.39版本的译注中有[onendreached](https://reactnative.cn/docs/0.39/listview.html#onendreached)
0.26中的没有提，可能不是我理解的默认加载第一页

我想默认加载第一页数据，尝试在componentWillMount中做，发现有重复的列表项

不停发送请求，我是通过ajax的状态做的，是不是要在ajax之后，需要控制一下滚动的位置防止再次触发onEndReached

**Comment by warmhug** [comment]
@zhangda47 看这里的描述：https://github.com/ant-design/ant-design-mobile/issues/520#issuecomment-263510596

**Comment by zhangda47** [comment]
@warmhug 问题解决了

初次加载的问题：因为空容器不会自动触发`onEndReached`，需要在组件加载完毕后手动发送请求初始化。为了避免手动加载发送两次请求，通过构造函数中传给 `cloneWithRows` 一个空数组，同时在ListView组件中指定 `initialListSize=0` 

不断刷新的问题：不但要通过 fetch loading 状态保证 onEndReached 方法不会无限执行，还要指定 `scrollRenderAheadDistance=0` 保证只有在下拉容器的时候 onEndReached 才会被调用

**Comment by 13320282511** [comment]
@zhangda47 正解
