### ISSUE TITLE
关于布局问题

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#623]
#### 本地环境

- antd-mobile 版本：0.9.11
- 浏览器 (或标明是 react-native) 及其版本：0.39 Android 4.4.2
- 操作系统及其版本：mac

#### 你做了什么？

`<View>
<Button>按钮</Button>
<Tabs>
...
</Tabs>
</View>`
#### 你期待的结果是：
正常显示

#### 实际上的结果：
上面的按钮可以显示，下面的标签页无法正常显示，如果将标签页组件改为其他组件则可以正常显示

**Comment by warmhug** [comment]
使用 react-native 0.34 版本， #634
