### ISSUE TITLE
nextjs 13 + antd-mobile 样式重复引入

### ISSUE THREAD

**Issue by mszsnn** [ant-design/ant-design-mobile#6234]
### Version of antd-mobile

5.31.1

### Operating system and its version

Others

### Browser and its version

chrome 114.0.5735.133

### Sandbox to reproduce

https://codesandbox.io/p/sandbox/magical-cloud-y4cm7f?file=%2Fapp%2Fdemo%2Fpage.js%3A4%2C33

### What happened?

当从 index 页面点击跳转到 demo页面，demo页面的 button 样式会引入两次，已测试。antd 不会出现这个问题
![image](https://github.com/ant-design/ant-design-mobile/assets/16608730/e474099f-0f3a-4d22-a062-fde33f530a46)
sandbox 线上不能复现， 本地可复现， 代码一样

**Comment by miracles1919** [comment]
我本地试了下 `next: 13.4.5` 还是正常的，后面的版本就会出现加载多次的问题，看起来是 nextjs 的问题

相关 issue：https://github.com/vercel/next.js/issues/51030
