### ISSUE TITLE
TextArea的最外层容器.adm-text-area未加position: relative;会导致auoSize异常。

### ISSUE THREAD

**Issue by GloryXia** [ant-design/ant-design-mobile#6238]
### Version of antd-mobile

5.31.1

### Operating system and its version

iOS, Android

### What happened?

如题，你们简单修复下吧，我就不蹭PR了

**Comment by zombieJ** [comment]
别介，PR 千万别客气 😁

**Comment by 1587315093** [comment]
你不蹭我可要蹭了奥 🤣
