### ISSUE TITLE
Menu data props引用变化时不支持动态更新

### ISSUE THREAD

**Issue by aaronz** [ant-design/ant-design-mobile#624]
#### 本地环境

- antd-mobile 版本：0.9.8
- 浏览器 (或标明是 react-native) 及其版本：浏览器
- 操作系统及其版本：windows

#### 你做了什么？

使用antd mobile的Menu，当更新this.state.menus的引用后menu item不会动态更新。
`<Menu data={this.state.menus} level={1} value={this.state.selectedMenu} />

  componentDidMount() {
    this.loadItems();
  }

  loadItems = () => {
    const menus = [{
      label: 'menu',
      value: '21',
    }];
    // sets a new menus object
    this.setState({ menus, selectedMenu: ['33'] });
  }`

#### 你期待的结果是：

Menu的data支持动态绑定，随着this.state.menus的变化动态更新。

#### 实际上的结果：

没有动态更新

#### 问题可能原因
Menu的Item根据SubMenuData构建，SubMenuData只在构造函数中赋值，render过程中没有通过props.data重新赋值。

**Comment by warmhug** [comment]
对组件进行重构，将去掉组件中的 state 。
