### ISSUE TITLE
TextArea rows 存在默认值 2，导致  autoSize >  minRows 传入 1 无效，组件高度应为 rows为1，但实际上是rows为2的高度

### ISSUE THREAD

**Issue by xiyangranhongyan** [ant-design/ant-design-mobile#6249]
### Version of antd-mobile

5.29.1

### Operating system and its version

iOS, Android

### Browser and its version

ios chrome 110.0

### What happened?

[官网示例](https://mobile.ant.design/zh/components/text-area) 的codeSandBox即可复现.

```
 <TextArea
    placeholder='请输入内容'
    value={value}
    onChange={val => {
      setValue(val)
    }}
    autoSize={{ minRows: 1 }}
  />
```
![image](https://github.com/ant-design/ant-design-mobile/assets/31724313/7d86d507-10e1-4eb8-827b-8310c5896c5f)
![image](https://github.com/ant-design/ant-design-mobile/assets/31724313/26a9b552-ad7c-4ede-bdde-7b110d46c5c6)
![image](https://github.com/ant-design/ant-design-mobile/assets/31724313/966ad6a0-69a6-4ec5-b846-b8e1e81a8cc3)

**Comment by miracles1919** [comment]
和 @zombieJ 讨论了一下，min 和 max 表示的是范围，并不是当前值，所以是预期行为哈~
