### ISSUE TITLE
react-native 缺少入口文件

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design-mobile#626]
- antd-mobile 版本：0.9.11

`node_modules` 下面没有`antd-mobile/lib/index.js`文件.

**Comment by warmhug** [comment]
#602

**Comment by bang88** [comment]
不是应该有一个index.js文件吗。 如果直接使用react-native init 的项目不需要配置webpack吧.

**Comment by warmhug** [comment]
#56

**Comment by afc163** [comment]
可以看下 https://github.com/ant-design/ant-design-mobile/issues/602 的讨论。
