### ISSUE TITLE
组件的示例，无法展示了。

### ISSUE THREAD

**Issue by mei3** [ant-design/ant-design-mobile#6265]
### Version of antd-mobile

5.0.4

### Browser and its version

chrome

### What happened?

<img width="1788" alt="image" src="https://github.com/ant-design/ant-design-mobile/assets/12680925/6c1381a4-87e0-441f-9b7e-30e6a02b9509">

**Comment by 1587315093** [comment]
不是 v5的文档，是[Ant Design Mobile RN ](https://github.com/ant-design/ant-design-mobile-rn/)的

而且我也能打开

![image](https://github.com/ant-design/ant-design-mobile/assets/77056991/c5e73a5a-9026-4339-9a97-2e414ae221da)

**Comment by mei3** [comment]
您好！您的邮件我已经收到，我会尽快回复。^o^Hello! I have received your email.^o^

**Comment by 1587315093** [comment]
移步到 [Ant Design Mobile RN ](https://github.com/ant-design/ant-design-mobile-rn/) 提 issue
@mei3
