### ISSUE TITLE
IOS 微信浏览器Picker确认按钮点击 出发按钮蒙层下面的事件问题

### ISSUE THREAD

**Issue by deerW** [ant-design/ant-design-mobile#627]
#### 本地环境

- antd-mobile 版本：0.9.11
- 浏览器 (或标明是 react-native) 及其版本：微信内置浏览器
- 操作系统及其版本：IOS

#### 你做了什么？

引入 antd-mobile 的 Picker

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

点击picker确认按钮时会触发确认健对应蒙层下面的动作

**Comment by huliyou** [comment]
```
npm un antd-mobile
npm cache clean
npm i -S antd-mobile
```
重新安装后就好了，虽然是同一个版本0.9.11，antd-mobile的依赖部分版本更新了，fix了微信里点击事件冒泡的问题。
