### ISSUE TITLE
ImagePicker没有像antd的Upload一样的配置Action属性吗

### ISSUE THREAD

**Issue by small752** [ant-design/ant-design-mobile#628]
ImagePicker组件 选择图片后如果转化成图片服务器的url

**Comment by warmhug** [comment]
不支持，ImagePicker 只是一个 picker ，上传功能需要自己实现

**Comment by benjycui** [comment]
https://mobile.ant.design/components/image-picker

文档会让人误会有上传功能。。

**Comment by warmhug** [comment]
我更新下文档。。。
