### ISSUE TITLE
Input的值无法恢复成undefined

### ISSUE THREAD

**Issue by zzcwzhang** [ant-design/ant-design-mobile#6283]
### Version of antd-mobile

5.21.0

### Operating system and its version

iOS, Android, Others

### Browser and its version

Google Chrome 115 IOS 16.2

### What happened?

Input组value与显示不同步
当我在第一个页面编辑Input后，通过其他方式将缓存的value设置为undefined
![Xnip2023-08-04_12-03-21](https://github.com/ant-design/ant-design-mobile/assets/16473938/f740d049-9124-4cec-aabc-abb69090b94a)
再次进入这个页面发现Input显示的还是上次的value值，实际上value已经是undefined了
![2](https://github.com/ant-design/ant-design-mobile/assets/16473938/2cbad1bb-4612-4158-99df-73f390d22c20)

![image](https://github.com/ant-design/ant-design-mobile/assets/16473938/c3fdc79d-b602-4199-9ed0-f1e1eadc8517)

**Comment by IronKinoko** [comment]
设置 `undefined` 会成为非受控状态，你需要设置成 `''` 空字符串

**Comment by zzcwzhang** [comment]
> 设置 `undefined` 会成为非受控状态，你需要设置成 `''` 空字符串

抱歉，这种方案在我们目前的系统中并不可取，因为undefined和空字代表着截然不同的两种状态，对于我们都有特殊含义。能否像antd的input一样支持undefined？

**Comment by 1587315093** [comment]
> Author

自己 typeof 一下吧，总有办法来解决得

**Comment by 1587315093** [comment]
> > 设置 `undefined` 会成为非受控状态，你需要设置成 `''` 空字符串
> 
> 抱歉，这种方案在我们目前的系统中并不可取，因为undefined和空字代表着截然不同的两种状态，对于我们都有特殊含义。能否像antd的input一样支持undefined？

自己 typeof 一下吧，总有办法来解决得

**Comment by zzcwzhang** [comment]
好的好的，感谢你们伟大的工作
