### ISSUE TITLE
Popup组件内定义的元素设置overflow-x: auto;后无法滑动

### ISSUE THREAD

**Issue by ikangjie** [ant-design/ant-design-mobile#6288]
### Version of antd-mobile

antd-mobile 5.32.0

### Operating system and its version

iOS

### Browser and its version

chrome 115.x

### Sandbox to reproduce

https://codesandbox.io/s/weathered-cloud-8gmgdj

### What happened?

问题：Popup组件内定义的元素设置overflow-x: auto;后无法滑动，鼠标滑动可以，手势无法滑动
期望：手势能正常滑动

**Comment by 1587315093** [comment]
是红色的区域吗？我手机打开好像是可以滚动的~

或者样式加个 `  WebkitOverflowScrolling: "touch"` 试试

**Comment by ikangjie** [comment]
@1587315093 加了也不行，很奇怪，我用手机也是可以正常滑动，但是在 webview 里面的就不行，很正常的样式，我现在已经用 swiper 组件解决了这个奇怪的问题

**Comment by 1587315093** [comment]
> @1587315093 加了也不行，很奇怪，我用手机也是可以正常滑动，但是在 webview 里面的就不行，很正常的样式，我现在已经用 swiper 组件解决了这个奇怪的问题

swiper 能用 是不是touch事件问题呀

**Comment by miracles1919** [comment]
看起来像是 webview 禁用了滚动，试试不用组件，单独用滚动元素

**Comment by listenecho** [comment]
我也是遇到了这种情况 使用overflow-x: auto 在ios真机无法滑动,         -webkit-overflow-scrolling: touch;
加上也不行

**Comment by wqjiao** [comment]
> WebkitOverflowScrolling
我也出现了这个问题，在钉钉里面打开滚动不了

**Comment by cwjjjjj** [comment]
iOS 内横向好像依然无法滑动

**Comment by chuyaoe** [comment]
真机测试ios和安卓都没法横向滑

**Comment by patchBig** [comment]
可以试试把页面高度设置成 100vh，overflow scroll。

**Comment by Agroo** [comment]
如何解决这个问题？

**Comment by Jungzl** [comment]
```tsx
disableBodyScroll={false}
```

**Comment by qzai666** [comment]
试试把popup 节点设置到页面层级里 默认是body
getContainer 这个属性

**Comment by Cloudyttt** [comment]
> 试试把popup 节点设置到页面层级里 默认是body getContainer 这个属性

感恩🥹，解决了我的问题
