### ISSUE TITLE
steps显示不出来

### ISSUE THREAD

**Issue by ssjjnn** [ant-design/ant-design-mobile#629]
#### 本地环境

- antd-mobile 版本：0.9.11
- 浏览器 (或标明是 react-native) 及其版本：react-native 0.39
- 操作系统及其版本：ios

#### 你做了什么？

![image](https://cloud.githubusercontent.com/assets/22025844/21090844/73540f62-c07d-11e6-9933-3148c8d0b3b0.png)
![image](https://cloud.githubusercontent.com/assets/22025844/21090850/7ac2b6b8-c07d-11e6-9b18-12cedec04d91.png)
Steps组件显示不出来

**Comment by ssjjnn** [comment]
![image](https://cloud.githubusercontent.com/assets/22025844/21090910/db142c90-c07d-11e6-9d35-43468cf45ad0.png)
![image](https://cloud.githubusercontent.com/assets/22025844/21090917/e8455cd6-c07d-11e6-87ea-8031e4980c9f.png)
用其他的组件没问题

**Comment by ssjjnn** [comment]
我把ReactNative降到0.35可以显示出来，用最新的就不行

**Comment by afc163** [comment]
> 操作系统及其版本：ios

这个写错了？

**Comment by ssjjnn** [comment]
操作系统及其版本：OS X EI Capitan  版本 10.11.5

**Comment by afc163** [comment]
不是，是运行环境，我看你截图是 Android？

**Comment by ssjjnn** [comment]
![image](https://cloud.githubusercontent.com/assets/22025844/21127780/a24037ca-c130-11e6-830a-02557672c3f4.png)
两个都用，结果都是一样的

**Comment by silentcloud** [comment]
关掉了，@ssjjnn 看哈 react-native 的 release note

https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#react-native-使用场景
