### ISSUE TITLE
示例代码没办法看，报 No default export of 'App.js' to render!

### ISSUE THREAD

**Issue by zhangjuns** [ant-design/ant-design-mobile#6299]
### Version of antd-mobile

Ant Design Mobile RN of React 5.0.4

### Operating system and its version

iOS, Others

### Browser and its version

google 浏览器

### What happened?

Ant Design Mobile RN of React的官网示例代码没办法看，报 No default export of 'App.js' to render!，有没有处理办法

### Relevant log output

```shell
查看官网示例代码报的
```

**Comment by 1587315093** [comment]
Ant Design Mobile RN 的地址在这儿 ，到那里去提吧~ https://github.com/ant-design/ant-design-mobile-rn/issues
