### ISSUE TITLE
List API 调整

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#63]
## List

```jsx
<List>
  <List.Header />
  <List.Body>
    <List.Item />
    <List.Item />
  </List.Body>
</List>
```

改成 =>

```jsx
<List title="原来的 header">
  <List.Item />
  <List.Item />
</List>
```

## List.Item

从

```jsx
<List.Item>
  <div>
    垂直居中对齐
    <div className="am-list-brief">辅助文字内容</div>
  </div>
</List.Item>
```

改为：

```jsx
// 去掉 `.am-list-brief`，改为 description
<List.Item description={} extra={} arrow={} >
```

---

```jsx
// 此用法保持不变
<List.Item>
  <InputItem />
</List.Item>
```

去处 swipeAction，增加 ListActionItem
```
<ListActionItem actions={}/>
```

**Comment by pingan1927** [comment]
这样可扩展性比较差吧。
要考虑下各种xxItem 基于list.item进行扩展。
API调整的目的是什么？

**Comment by afc163** [comment]
> 这样可扩展性比较差吧。

什么扩展性差？扩展性应该是一样的。

>  API调整的目的是什么？

美化。

**Comment by pingan1927** [comment]
> 什么扩展性差？扩展性应该是一样的。

比如，需要定制某个`List.Header`的样式，辣么就选择在`List`上加一个`className`再选择到`am-list-header`? 再比如，`List.Header`要加一个`onClick`，`title=""`则需要再包一个`div`标签。

> 美化。

这个目的，顶！

**Comment by afc163** [comment]
`<List title={<span className="xx">标题</span>}`

**Comment by yiminghe** [comment]
尽量使用 children ，不要空 children 反而 属性

**Comment by afc163** [comment]
有些 children 很难定义，可以保留 title 作为 children。

```jsx
<List.Item description={} extra={} arrow={} />
  title
</List>
```

**Comment by pingan1927** [comment]
> 有些 children 很难定义，可以保留 title 作为 children。

`list.item`的`children`里内容千变万化，`extra`也是千变万化，改为`<div className="am-list-brief">辅助文字内容</div>`改为`description`无法解决问题，很多情况下需要3行、4行，其中有两行是brief。children里也会有brief，extra里也可能有。限定死了用户就根本不够用了。

**Comment by afc163** [comment]
`description={<div><p>第一行</p><p>第二行</p></div>}`

`extra={<div><div>第一行</p><div>第二行</p></div>}`

尽量不要有 `className="约定值"` 暴露给用户。

**Comment by afc163** [comment]
`description={<div><p>第一行</p><p>第二行</p></div>}`

`extra={<div><div>第一行</p><div>第二行</p></div>}`

尽量不要有 `className="约定值"` 暴露给用户。

**Comment by pingan1927** [comment]
List.Item我是偷懒了，直接把AntUI的一些约定值拿过来。

`className="约定值"`，这个恰恰是我觉得需要整理出来一份文档提供出来的。
例如一些很简单的约定。比如a标签的各种场景颜色、各种字号大小，不值得给出一个组件，但是要有规范。

或者 @afc163 有更好的方案吗？

**Comment by afc163** [comment]
1. 能全局设置就全局设置。
2. 大一点点就给小组件。
3. 剩下让使用方用变量自己设。

**Comment by pingan1927** [comment]
```
// 去掉 children，改为 title
// 去掉 `.am-list-brief`，改为 description
<List.Item title={} description={} extra={} arrow={} />
```

extra中的`.am-list-brief`的如何安排？

**Comment by pingan1927** [comment]
再搞个`extraDescription`？

**Comment by afc163** [comment]
```jsx
const { Brief } = List.Item;

<List.Item title={<div>快捷键 <Brief>说明</Brief></div>} description={<div>快捷键 <Brief>说明</Brief></div>} extra={<div>快捷键 <Brief>说明</Brief></div>} arrow={} />
```

抛砖引玉一下，`brief` 貌似都是一样的？靠右浮动 + 小字体？

**Comment by pingan1927** [comment]
```
const { Brief } = List.Item;

<List.Item
  extra={<div>快捷键 <Brief>说明</Brief></div>}
  arrow={}
>
    <div>快捷键 <Brief>说明</Brief></div>
</List.Item>
```
这样差不多，扩展性也好，升级也不难， 就是把原来的`am-list-brief`包装下。

**Comment by silentcloud** [comment]
这个最终的结论？ @pingan1927 

搞好了就把 issue close 了
