### ISSUE TITLE
Jenkins打包antd-mobile-v5报错

### ISSUE THREAD

**Issue by heartWant** [ant-design/ant-design-mobile#6301]
### Version of antd-mobile

5.10.3

### Description

在Jenkins上打包会出现 Support for the experimental syntax 'classProperties’ isn't currently enabled
![企业微信截图_16914924775143](https://github.com/ant-design/ant-design-mobile/assets/33016938/3b4dfc89-dc94-4bf7-b461-d050e4faeb31)
Jenkins上node版本是 v14.15.1，是因为node版本太低的原因才导致打包失败的吗

**Comment by 1587315093** [comment]
看报错是 react-spring 报的，本地换个node 版本打包试试
