### ISSUE TITLE
使用Drawer导致手机上线拖拽时  焦点在Drawer的遮罩层 使得不能拖拽内层布局滚动条

### ISSUE THREAD

**Issue by wcdhm** [ant-design/ant-design-mobile#631]
#### 本地环境

- antd-mobile 版本：0.9.10
- 浏览器 (或标明是 react-native) 及其版本：微信内置浏览器
- 操作系统及其版本：ios10.1.1

#### 你做了什么？

引入 antd-mobile 的 Drawer，并且在drawer中添加了其他内容a, 且a的高度超过屏幕高度，将屏幕拖拽到超过最顶层或最底层时，往返反向再次拖拽屏幕

#### 你期待的结果是：

任然能够拖拽在Drawer中的a

#### 实际上的结果：

当前操作的焦点在drawer的遮罩层，无法继续往上拖动，需要轻点a任意部分后才能正常拖拽a

**Comment by warmhug** [comment]
重装 node_modules

**Comment by wcdhm** [comment]
是重装所有模块  还是ant-design  如果是后者是否有版本要求

**Comment by warmhug** [comment]
最好重装所有模块。或者 删掉再重装 rc-drawer

**Comment by wcdhm** [comment]
仍然是这样  已经重装
![wechatimg6](https://cloud.githubusercontent.com/assets/24520863/21127396/79fcecb6-c12d-11e6-969d-bae16a33f11f.png)
![wechatimg7](https://cloud.githubusercontent.com/assets/24520863/21127397/7a3f61a4-c12d-11e6-94de-0a6f0715d441.jpeg)

**Comment by warmhug** [comment]
给出可重现 demo

**Comment by warmhug** [comment]
没反馈，先关掉。焦点问题应该可以手动设置。
