### ISSUE TITLE
Popup 弹出时候被遮挡 ios

### ISSUE THREAD

**Issue by Julycc41** [ant-design/ant-design-mobile#6312]
### Version of antd-mobile

5.25.1

### Operating system and its version

iOS

### Browser and its version

16.6

### What happened?

弹出的时候 被遮挡住了 zindex也没用
![image](https://github.com/ant-design/ant-design-mobile/assets/80231740/951bbb11-bb96-411f-a6f7-5178acb1c16a)

**Comment by Julycc41** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/80231740/76c686da-1f3e-4f89-8f51-3639bcf34969)
这是正确的效果

**Comment by 1587315093** [comment]
把 审批状态 的zindex降一下？
