### ISSUE TITLE
VirtualInput 的 keyboard参数的getContainer失效

### ISSUE THREAD

**Issue by TivonJJ** [ant-design/ant-design-mobile#6318]
### Version of antd-mobile

v5.32.0

### Browser and its version

All

### What happened?

该代码设置后keyboard还是渲染在了子元素内，未append到body。 这样键盘可能会继承input的一些自定义样式。

```tsx
<VirtualInput
  keyboard={
    <NumberKeyboard
      className={classnames('NumberKeyboard', keyboardClassName)}
      getContainer={document.body}
    />
  }
/>
```

https://mobile.ant.design/zh/components/number-keyboard

https://mobile.ant.design/zh/components/virtual-input

**Comment by 1587315093** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/src/components/virtual-input/virtual-input.tsx#L113

看这段代码应该是预期行为？

**Comment by TivonJJ** [comment]
> [97398a0](https://github.com/ant-design/ant-design-mobile/commit/97398a0c95266f388e81161c760515e4e01dbd81)
> 
> 应该是预期行为？

为什么会如此做？  我觉得这个还是开放可控更好，因为这种浮窗在子组件内可能会产生很多不必要的麻烦。

**Comment by 1587315093** [comment]
> > [97398a0](https://github.com/ant-design/ant-design-mobile/commit/97398a0c95266f388e81161c760515e4e01dbd81)
> > 应该是预期行为？
> 
> 为什么会如此做？ 我觉得这个还是开放可控更好，因为这种浮窗在子组件内可能会产生很多不必要的麻烦。

刻意加的代码总有它的道理~ 看commit msg意思是 防止长按使输入元素丢失...

**Comment by TivonJJ** [comment]
> > > [97398a0](https://github.com/ant-design/ant-design-mobile/commit/97398a0c95266f388e81161c760515e4e01dbd81)
> > > 应该是预期行为？
> > 
> > 
> > 为什么会如此做？ 我觉得这个还是开放可控更好，因为这种浮窗在子组件内可能会产生很多不必要的麻烦。
> 
> 刻意加的代码总有它的道理~ 看commit msg意思是 防止长按使输入元素丢失...

然而那个问题并没有完全解决

**Comment by TivonJJ** [comment]
曲线解决了此问题

`
const NumberKeyboardWithContainer = (
    props: Omit<NumberKeyboardProps, 'getContainer'> & {
        container: NumberKeyboardProps['getContainer'];
    },
) => {
    return <NumberKeyboard {...props} getContainer={props.container} />;
};

<VirtualInput
            keyboard={
                <NumberKeyboardWithContainer
                    data-key={uniqueKey}
                    className={classnames('numberkeyboard', keyboardClassName)}
                    container={getContainer}
                    {...restKeyboardProps}
                />
            }
        />
`

**Comment by 1587315093** [comment]
> 曲线解决了此问题
> 
> ```tsx
> const NumberKeyboardWithContainer = (
>     props: Omit<NumberKeyboardProps, 'getContainer'> & {
>         container: NumberKeyboardProps['getContainer'];
>     },
> ) => {
>     return <NumberKeyboard {...props} getContainer={props.container} />;
> };
> 
> <VirtualInput
>             keyboard={
>                 <NumberKeyboardWithContainer
>                     data-key={uniqueKey}
>                     className={classnames('numberkeyboard', keyboardClassName)}
>                     container={getContainer}
>                     {...restKeyboardProps}
>                 />
>             }
>         />
> ```

思路挺好~

那个问题没解决能说说吗
