### ISSUE TITLE
card组件外面套了个view,内容显示不全

### ISSUE THREAD

**Issue by ssjjnn** [ant-design/ant-design-mobile#632]
#### 本地环境

- antd-mobile 版本：0.9.11
- 浏览器 (或标明是 react-native) 及其版本：react-native 0.39
- 操作系统及其版本：ios

#### 你做了什么？

react-native 0.39下
1.card组件外面套了个view,内容显示不全，默认高度只有100左右，要给他加个height才能显示全
2.card组件外面套了个scrollView,内容显示正常

react-native 0.35下
1.card组件外面套了个view,内容显示正常
2.card组件外面套了个scrollView,内容显示正常

**Comment by warmhug** [comment]
#589

**Comment by silentcloud** [comment]
0.9.11 建议用 0.34 的版本，rn 官方 > 0.36 做了很多不兼容改动 @ssjjnn
