### ISSUE TITLE
form has an error formItem stopping the check，and return result

### ISSUE THREAD

**Issue by liyoy** [ant-design/ant-design-mobile#6321]
### Version of antd-mobile

5.29.1

**Comment by 19Qingfeng** [comment]
单个字段检查失败后停止继续检查么？ 有需要的话我可以贡献这个 `PR`

**Comment by IronKinoko** [comment]
需要更清晰的描述信息。

目前我有两种理解

1. 整个表单遇到某个字段校验错误立即停止校验，并显示错误。

这是不可取的，表单并非一定要按序填写，其他字段也需要独立校验，阻止整个表单并不合理
换一种思路，把你可以通过 `onFinishFailed` 收集提交时的错误信息，按需显示

```tsx
<Form hasFeedback={false} onFinishFailed={({ values, errorFields, outOfDate })=>{
  // 关闭FeedBack，自行处理 errorFields 信息
}}>
</Form>
```

2. 单个字段有多个规则，当某一规则校验不通过时，停止剩下的规则的校验

目前已有该功能，设置 `validateFirst` 既可
```tsx
<Form.Item validateFirst rules={[{ required: true }, { max: 5, min: 1, type: 'number' }]}>
</Form.Item>
```
