### ISSUE TITLE
ImageUploader可以将upload设为可选值，而不是必选值吗

### ISSUE THREAD

**Issue by huhaoda-creat** [ant-design/ant-design-mobile#6322]
### Version of antd-mobile

^5.25.1

### Description

有一些场景并不需要upload，只需要imageUoloader这个组件样式及一些其他的操作
![image](https://github.com/ant-design/ant-design-mobile/assets/83128628/b3636451-55f8-4c3f-b9d1-74548195eeed)

**Comment by miracles1919** [comment]
传个空函数呗
