### ISSUE TITLE
WaterMark 水印 全局变量--adm-water-mark-z-index 和CSS 变量--z-index失效

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#6329]
### Version of antd-mobile

5.32.0

### Sandbox to reproduce

https://codesandbox.io/s/flamboyant-mclean-snlzc8?file=/demo1.less

### What happened?

WaterMark 水印 全局变量--adm-water-mark-z-index 和CSS 变量--z-index失效
![image](https://github.com/ant-design/ant-design-mobile/assets/31531283/b393ece0-627e-46ff-8ea9-959b709b2e12)

**Comment by 1587315093** [comment]
参考下https://ant-design-mobile.antgroup.com/zh/components/picker 的css变量使用方法

**Comment by liangskyli** [comment]
> 参考下https://ant-design-mobile.antgroup.com/zh/components/picker 的css变量使用方法

不就是下面，这两个使用方法吗？这两个都不生效啊
```
 <WaterMark
    content={'Ant Design Mobile'}
    style={{
      '--adm-water-mark-z-index': 2020,
    }}
  />
 <WaterMark
    content={'Ant Design Mobile'}
    style={{
      '--z-index': 2020,
    }}
  />
```

**Comment by liangskyli** [comment]
加了一个例子：https://codesandbox.io/s/dazzling-bhaskara-24qh88

<img width="1037" alt="image" src="https://github.com/ant-design/ant-design-mobile/assets/31531283/5a195ef5-4379-4f03-8808-b61cc70c9d7f">
