### ISSUE TITLE
ListView 通过onEndReached加载item超过100条时，不能继续加载，并且无限循环调用onEndReached

### ISSUE THREAD

**Issue by wongben** [ant-design/ant-design-mobile#633]
#### 本地环境

- antd-mobile 版本：0.9.11 + Dvajs
- 浏览器 (或标明是 react-native) 及其版本：Chrome最新和微信浏览器
- 操作系统及其版本：Windows

#### 你做了什么？
ListView onEndReached 加载数据到第5页每次20条，供100条左右会无限加载数据，但加载的数据并不能通过concat()增加到dataSource上，也不会显示到页面上。而后台还在无限加载数据。此外，把分页数据改为50条时，第二次onEndReached 到达100条左右时就会触发此现象。

#### 你期待的结果是：
正常加载接下来的100条至更多数据

#### 实际上的结果：
见下截图
![111](https://cloud.githubusercontent.com/assets/1499531/21101257/339f2e48-c0b3-11e6-985a-7db6b7aac5df.gif)

核心代码
```
/* eslint import/extensions: 0, no-dupe-keys: 0, no-mixed-operators: 0*/
import { ListView } from 'antd-mobile';
import React, { PropTypes } from 'react';
import PoolItem from './PoolItem';

import styles from './PoolList.less';

const poolListView = ({ dataSource, isLoading, onEndReached }) => {
  const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });
  const renderRow = (rowData, sectionId, rowId) => (<PoolItem rowData={rowData} sectionId={sectionId} rowId={rowId} />);
  //列表Footer

  console.info('poolListView isLoading is', isLoading);
  const renderFooter = () => (<div style={{ padding: 5, textAlign: 'center' }}>
    {isLoading ? '加载中...' : '加载完毕'}</div>);

  return (
    <div className={styles.listView}>
      <ListView
        dataSource={ds.cloneWithRows(dataSource)}
        useBodyScroll
        renderSeparator={(sectionID, rowID) => (
          <div key={`${sectionID}-${rowID}`} style={{ height: '1px', backgroundColor: '#f5f5f9' }} />
        )}
        renderRow={renderRow}
        renderFooter={renderFooter}
        scrollRenderAheadDistance={900}
        onEndReached={onEndReached}
        onEndReachedThreshold={10}
        initialListSize={dataSource.length - 4}
        scrollEventThrottle={30}
      />
    </div>
  );
};

export default poolListView;


-----------------------------------------------
import React, { PropTypes } from 'react';
import { connect } from 'dva';
import PoolList from '../components/Pools/PoolList';
import styles from './Pools.less';

const Pools = ({ location, dispatch, pools }) => {
  const { dataSource, isLoading, pageNo, pageSize, total, currentItem } = pools;
  const onEndReached = (event) => {
    if (!isLoading) {
      dispatch({
        type: 'pools/query',
        payload: { pageNo: pageNo + 1, pageSize }
      });
    }
  };
  const poolListProps = { dataSource, onEndReached, isLoading };
  return (
    <div className={styles.normal}>
      <PoolList {...poolListProps} />
    </div>
  );
};


Pools.propTypes = {
};

const mapStateToProps = ({ pools }) => ({ pools });

export default connect(mapStateToProps)(Pools);
```
#### 可重现的在线演示
1.git clone https://github.com/wongben/swimming.git
2.npm install 
3.npm start
4.浏览器打开http://127.0.0.1:8989/#/pools
5.浏览器F12观察至100条数据问题重现

**Comment by warmhug** [comment]
注意看你 100 条之后，返回的数据里没有新数据。 

这里涉及到 ListView 的实现细节：ListView 在 componentWillReceiveProps 里会监听  dataSource 对象的变化，并做一次 [`this._renderMoreRowsIfNeeded()`](https://github.com/react-component/m-list-view/blob/90badfdb6e94093136c86e5874ce6054eae88a0d/src/ListView.js#L156) ，由于此时[`this.state.curRenderedRowsCount === this.props.dataSource.getRowCount()`](https://github.com/react-component/m-list-view/blob/90badfdb6e94093136c86e5874ce6054eae88a0d/src/ListView.js#L348) 即已经渲染的数据与 dataSource 里已有的数据项个数相同，所以 ListView 认为应该再调用 onEndReached 方法。

再次调用之后，你返回了新的 dataSource 对象，但 dataSource 里数据项个数没改变，所以 ListView 认为应该再调用 onEndReached 方法。你仍旧返回数据项个数相同的 dataSource，也就再次触发此调用，形成死循环。

解决办法：没有新的数据项，不要再产生新的 dataSource 对象出来。

**Comment by wongben** [comment]
谢谢@warmhug，我mock的数据果然有问题，也谢谢普及了ListView实现细节

**Comment by szqiuboshi** [comment]
没有新的数据项，不要再产生新的 dataSource 对象出来。--有没有样例代码

**Comment by cncolder** [comment]
@szqiuboshi 就是没有新数据了就别再更新 dataSource 了。

```js
if (this.state.noMoreData) return
this.state = {
  dataSource: dataSource.cloneWithRows()
}
```
