### ISSUE TITLE
Toast文本对齐方式由左对齐变为居中对齐，发生了breakchange

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#6337]
### Version of antd-mobile

5.32.1

### Sandbox to reproduce

https://codesandbox.io/s/unruffled-moon-2hnjjv?file=/app.tsx 和 https://codesandbox.io/s/quirky-panna-d3kwxr?file=/package.json

### What happened?

Toast文本对齐方式breakchange,
5.32.0版本：左对齐：见https://codesandbox.io/s/unruffled-moon-2hnjjv?file=/app.tsx
5.32.1版本：居中对齐了：见https://codesandbox.io/s/quirky-panna-d3kwxr?file=/package.json
#6287 这个提交导致的样式变更问题！

**Comment by Fog3211** [comment]
#6345 
不好意思，我的锅
