### ISSUE TITLE
关于 antd-mobile 对应的 RN 版本使用说明

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#634]
RN 官方从 0.36 有不兼容版本，所以使用 antd-mobile 0.9.x 的推荐使用 0.34 版本；
1.0-alpha 可以使用 0.39

https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#react-native-使用场景

#632 #629 #617 #613 #612

**Comment by silentcloud** [comment]
这个说明 issue ，暂时不要关 @warmhug @afc163

**Comment by afc163** [comment]
加上 peerDependencies ?

**Comment by warmhug** [comment]
@afc163 在 0.9.x 上加一下

**Comment by warmhug** [comment]
https://github.com/facebook/react-native/releases/tag/v0.36.0
![image](https://cloud.githubusercontent.com/assets/2011119/21471038/1eca5aea-cadd-11e6-9e37-4c3d81cb7421.png)

是不是把代码里使用 flex: 1 的地方改成 flexGrow: 1 就能兼容 0.34 - 0.39 版本了？我看其他没什么大的变动。

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/commit/6d1b7e75a55db4f2a581ffc9e0488235df74f7b8 这是对应的改动，只不过 `是不是把代码里使用 flex: 1 的地方改成 flexGrow: 1 就能兼容 0.34 - 0.39 版本了` 没尝试；

最好还是各用各的版本比较保险，我在 introduce 文档里也有说明

**Comment by warmhug** [comment]
试一下，尽量做到兼容。代码一致，能减少后续 0.9 的维护成本

**Comment by warmhug** [comment]
List / Radio / Checkbox / TextAreaItem / SearchBar 几个组件的 RN 实现需要完善。 @pingan1927

**Comment by silentcloud** [comment]
`flexGrow: 1 ` 试过了，兼容 0.34 ~ 0.39，已保持 master 和 0.9.x 一致
