### ISSUE TITLE
Popup  shou出来的组件不会实时render吗，state里的值改变了，show里面的组件不会触发render

### ISSUE THREAD

**Issue by small752** [ant-design/ant-design-mobile#635]
Popup  shou出来的组件不会实时render吗，state里的值改变了，show里面的组件不会触发render

**Comment by warmhug** [comment]
show 参数里是自己的组件，自己组件里控制重新渲染。

**Comment by small752** [comment]
恩，后来实现了，之前主要是因为调用的地方是用dva框架写得，model里数据变不会触发  打开pop的函数，后来自己再组件内部解决了

**Comment by small752** [comment]
可以close了  ^^

**Comment by yazhengwang** [comment]
@small752 请问是怎么解决的？谢谢

**Comment by yazhengwang** [comment]
解决了，把弹出内容单独写在一个class去通过state渲染就可以了

**Comment by handoudou** [comment]
@small752 @yazhengwang 能不能详细说一下解决方法？

**Comment by yazhengwang** [comment]
我是把 show 的组件单独定义出来了

在 2017-04-10 17:33:05，"handoudou" <notifications@github.com> 写道：


@small752@yazhengwang 能不能详细说一下解决方法？

**Comment by xiaochunyong** [comment]
@yazhengwang 我也是单独定义出来的, 但是无法connect, 方便留个联系方式么? 看看你是如何实现的~

**Comment by kaigekong** [comment]
thanks 
@small752 @yazhengwang  

ex: <Regional /> 自定义组件
Popup.show(<Regional />, { animationType: 'slide-up', maskClosable: true})

**Comment by horizon0514** [comment]
@kaigekong  这样我试了不行呀=。=

**Comment by warmhug** [comment]
升级到 2.0，是用 Modal popup 代替

**Comment by horizon0514** [comment]
使用state 代替吧，然后在componentwillreceiveprops 改state
