### ISSUE TITLE
使用antd-mobile中组件提示错误

### ISSUE THREAD

**Issue by gonyua** [ant-design/ant-design-mobile#6356]
### Version of antd-mobile

    "antd-mobile": "^2.3.3","typescript": "~3.4.0",

### Description

  第 1 个重载(共 2 个)，“(props: ButtonProps | Readonly<ButtonProps>): Button”，出现以下错误。
    不能将类型“{ children: string; type: "primary"; className: any; onClick: () => Promise<void>; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<Button> & Pick<Readonly<ButtonProps>, "style" | ... 5 more ... | "onClick"> & InexactPartial<...> & InexactPartial<...>”。
      类型“IntrinsicAttributes & IntrinsicClassAttributes<Button> & Pick<Readonly<ButtonProps>, "style" | ... 5 more ... | "onClick"> & InexactPartial<...> & InexactPartial<...>”上不存在属性“children”。
<img width="1000" alt="image" src="https://github.com/ant-design/ant-design-mobile/assets/4038121/c1085c7a-edc2-4b0e-8b2b-9a179d089821">

**Comment by IronKinoko** [comment]
可能是 react 版本不匹配，请使用 react 16 版本和对应的@types。

```shell
npm i react@16 react-dom@16 @types/react@16 @types/react-dom@16
```

v2 已经不再维护了，建议升级到 v5：
https://mobile.ant.design/
