### ISSUE TITLE
新增的global background

### ISSUE THREAD

**Issue by elelel0** [ant-design/ant-design-mobile#6363]
### Version of antd-mobile

5.32.3

### Operating system and its version

Others

### What happened?

想问下为什么5.32.2 版本 global.less 新增了background：#fff，导致我的页面global background被覆盖了

**Comment by IronKinoko** [comment]
#6346

**Comment by zombieJ** [comment]
这个是为了修复暗色主题背景色没有跟着变化的问题。组件库的样式是可以被覆盖的，你需要看一下样式加载，为什么 mobile 没有出现在前面。
