### ISSUE TITLE
总是提示Cannot resolve module 'antd-mobile'

### ISSUE THREAD

**Issue by loyldg** [ant-design/ant-design-mobile#637]
#### 本地环境
- antd-mobile 版本：0.9.11
- 浏览器 ：chrome54
- 运行环境及其版本：Windows平台,node：6.9.1 ,npm：3.10.8
#### 你做了什么？
引入 antd-mobile 的 任意组件
#### 你期待的结果是：
能够编译通过
#### 实际上的结果：
提示Cannot resolve module 'antd-mobile'
1.引用babel-plugin-import后能够正常编译，但是我想同其他组件一样，引入后就能编译通过，而不用额外做处理
2.即使我引入了import插件，antd-mobile与eslint也不兼容，必须要在rules里添加"import/no-unresolved": 0屏蔽错误才行，否则还是会报相同的错误
3.我要通过DllPlugin插件打包antd-mobile，这时又出现了相同的错误，怎么配置才能通过DllPlugin打包？
4.能否调整antd-mobile的相关配置或者代码，在不额外做处理的情况下，能够正常编译？

**Comment by warmhug** [comment]
antd-mobile 是按需加载里边引用到的组件，而不是全部组件。不建议和 react fastclick 等一样当做 vendor 处理。

**Comment by warmhug** [comment]
关联 #363

**Comment by loyldg** [comment]
即使我不打包antd-mobile，使用airbnb验证时，也没法通过啊，必须要添加import/no-unresolved处理。我只是希望antd-mobile和其他库一样，从npm安装后，引用组件，然后编译通过。而现在的情况是：我需要做额外处理，还无法与airbnb的验证兼容。

**Comment by warmhug** [comment]
#602

**Comment by loyldg** [comment]
目前通过在antd-mobile的package.json里添加 "main": "lib/index.web.js"解决的，暂时就先这样处理吧

**Comment by warmhug** [comment]
建议添加import/no-unresolved ，方便以为维护和升级

**Comment by loyldg** [comment]
之前是通过添加import/no-unresolved方式处理的，添加之后还需要引入babel-plugin-import插件才能通过编译，后来想通过DllPlugin插件打包antd-mobile，发现处理起来还是麻烦，然后就改成了添加main字段

**Comment by warmhug** [comment]
babel-plugin-import 一定需要引入，不然不能按需加载组件

**Comment by loyldg** [comment]
谢谢，此问题算是解决了。
