### ISSUE TITLE
ImageUploader在iphone13，拍照后卡死，无法点击使用照片或者重拍

### ISSUE THREAD

**Issue by wuwenjia** [ant-design/ant-design-mobile#6374]
### Version of antd-mobile

5.30.0

### Description

如题，偶尔关闭app再启动能好使，但是总出问题

<img width="420" alt="image" src="https://github.com/ant-design/ant-design-mobile/assets/28593292/a6f6c0ce-de04-404f-a0ff-2031489e272f">

**Comment by 1587315093** [comment]
哪来的 ImagePicker？

**Comment by wuwenjia** [comment]
> 哪来的 ImagePicker？

ImageUploader

**Comment by 1587315093** [comment]
注意看控制台报错，把复现代码贴上来吧

**Comment by zombieJ** [comment]
录个屏看看？
