### ISSUE TITLE
多选希望可以支持一下，不是ui的问题，难道手机上就不能多选了吗。。。

### ISSUE THREAD

**Issue by SolitaryScripter** [ant-design/ant-design-mobile#6385]
多选希望可以支持一下，不是ui的问题，难道手机上就不能多选了吗。。。
![截屏2023-09-26 15 34 31](https://github.com/ant-design/ant-design-mobile/assets/22770979/3372385e-3c06-4643-9581-6adc0ee1a747)
多选可以存在多个右边✅的选中态，上面的tab切换也能提供跨类别的选择

_Originally posted by @SolitaryScripter in https://github.com/ant-design/ant-design-mobile/issues/5725#issuecomment-1734992529_

**Comment by miracles1919** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/22469543/f6c0e53b-af9b-4313-85e6-84b8ad76a9a8)
如果是多选，怎么切换到下一级呢？比如选了浙江、江苏，又怎么展示浙江、江苏的城市呢？

**Comment by SolitaryScripter** [comment]
上面的tab切换

**Comment by SolitaryScripter** [comment]
和pc一样加上复选框？不同的点击热区

**Comment by SolitaryScripter** [comment]
或者加一个前往下一级的icon点击

**Comment by yuqi17** [comment]
俺也一样, 不过貌似有点难, pc对应的组件是Cascader

**Comment by SolitaryScripter** [comment]
<img width="405" alt="image" src="https://github.com/ant-design/ant-design-mobile/assets/22770979/4c9f5f2e-baea-43bf-aa0b-aaeed0e0a2c1">

**Comment by yuqi17** [comment]
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/22770979/273841632-4c9f5f2e-baea-43bf-aa0b-aaeed0e0a2c1.png">

这个是你改造的吗?

**Comment by ZhichaoOuyang** [comment]
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/22770979/273841632-4c9f5f2e-baea-43bf-aa0b-aaeed0e0a2c1.png">

咋改的老哥，能提供下代码参考参考吗
