### ISSUE TITLE
PickView选中项支持背景颜色自定义

### ISSUE THREAD

**Issue by slivens** [ant-design/ant-design-mobile#6390]
### What is this feature about?

![2023 10 09_沈礼文 dff0bbe63b275858e7d63f457e3c96e6](https://github.com/ant-design/ant-design-mobile/assets/32921512/476a28a0-c3c2-4b84-b6e2-d532044582b8)
使用覆盖样式字体无法显示

**Comment by 1587315093** [comment]
试试这个方法呢

https://mobile.ant.design/zh/components/picker#%E5%A6%82%E4%BD%95%E9%AB%98%E4%BA%AE%E5%BD%93%E5%89%8D%E9%80%89%E9%A1%B9

![image](https://github.com/ant-design/ant-design-mobile/assets/77056991/fec8983b-3147-4ec1-9b95-5ed35f9698e0)

**Comment by 1587315093** [comment]
询问过大佬 说可以支持个activeClass之类的属性

**Comment by 1587315093** [comment]
使用新的activeClass 可以改样式
