### ISSUE TITLE
Textarea设置最大长度，文本框仍可在非尾部光标处输入内容

### ISSUE THREAD

**Issue by yy-array** [ant-design/ant-design-mobile#6391]
### Version of antd-mobile

v5.32.4

### What happened?

问题：
Textarea设置最大长度，文本框仍可在非尾部光标处输入内容，并对新的全部内容进行最大长度截取

期望行为：
达到最大长度时，无法输入新内容

**Comment by yy-array** [comment]
https://codesandbox.io/p/sandbox/inspiring-brahmagupta-khjcqy?file=%2Fsrc%2FApp.tsx%3A26%2C37

**Comment by zbw-zbw** [comment]
> https://codesandbox.io/p/sandbox/inspiring-brahmagupta-khjcqy?file=%2Fsrc%2FApp.tsx%3A26%2C37 问题复现步骤和期望场景可在该链接中查看

好像确实有点问题，我来修复下？ @1587315093
