### ISSUE TITLE
Modal的几个指令式方法，如果不传入对应的Text，按钮上的文字只能显示默认值，而不是多语言

### ISSUE THREAD

**Issue by legolasNg** [ant-design/ant-design-mobile#6394]
### Version of antd-mobile

5.23.4

### Operating system and its version

iOS, Android

### Browser and its version

IOS

### What happened?

不知道这个是bug，还是原本就希望调用者传入对应的confirmText。我看了下源码，在mergerProps之前获取的是 `getDefaultConfig`的`locale`属性，而不是`useConfig`返回的locale属性

**Comment by IronKinoko** [comment]
https://github.com/ant-design/ant-design-mobile/blob/9c994eb19a81a5ea0087da199d862ee185231513/src/components/config-provider/config-provider.tsx#L46-L48

指令方法生成的节点不在原先的树中，获取不到 ConfigProvider 上下文，可以通过设置默认值解决这个问题。

```tsx
import { ConfigProvider, setDefaultConfig } from 'antd-mobile'
import enUS from 'antd-mobile/es/locales/en-US'

setDefaultConfig({ locale: enUS }) // 设置默认的语言

const rootElement = document.getElementById('root')
render(
  <ConfigProvider locale={enUS}>
    <App />
  </ConfigProvider>,
  rootElement,
)
```

**Comment by legolasNg** [comment]
明白了，谢谢解答。

> https://github.com/ant-design/ant-design-mobile/blob/9c994eb19a81a5ea0087da199d862ee185231513/src/components/config-provider/config-provider.tsx#L46-L48
> 
> 指令方法生成的节点不在原先的树中，获取不到 ConfigProvider 上下文，可以通过设置默认值解决这个问题。
> 
> ```tsx
> import { ConfigProvider, setDefaultConfig } from 'antd-mobile'
> import enUS from 'antd-mobile/es/locales/en-US'
> 
> setDefaultConfig({ locale: enUS }) // 设置默认的语言
> 
> const rootElement = document.getElementById('root')
> render(
>   <ConfigProvider locale={enUS}>
>     <App />
>   </ConfigProvider>,
>   rootElement,
> )
> ```
