### ISSUE TITLE
这个库与fastclick的兼容如何？我测试过，但不知道全不全面

### ISSUE THREAD

**Issue by p2227** [ant-design/ant-design-mobile#64]
#### 本地环境

- antd-mobile 版本：0.7.3
- 操作系统及其版本：win7,android 4.2,android5.0
- 浏览器及其版本：chrom 54.0.2824.2 canary，uc，及安卓默认自带的浏览器

#### 你做了什么？

```
import React from 'react';
import ReactDom from 'react-dom';
import { Button } from 'antd-mobile'; //已经配置好babel-plugin-antd
import FastClick from 'fastclick';

if ('addEventListener' in document) {
    document.addEventListener('DOMContentLoaded', function() {
        FastClick.attach(document.body);
    }, false);
}

ReactDom.render(<div>
  <Button>一般</Button>
</div>,document.getElementById('xxx'));

```

#### 你期待的结果是：

都有点击反馈

#### 实际上的结果：

pc上不会（开模拟器），uc不会，但默认的浏览器会（4.2,5.0结果一致）

#### 可重现的在线演示

本机代码。没有在线演示

然后我关注的是，官方有没有关于这方面（加入fastclick仍然有点击反馈）的兼容性说明，比如“IOS几，安卓几以上版本是有点击反馈的”？

另外说一下，这个issue https://github.com/ant-design/ant-design-mobile/issues/32 里面只引入了fastclick，但没有进行初始化，是遗留了还是出于什么原因？

**Comment by yiminghe** [comment]
@liqi07 attach 下

@pingan1927 看下 button 兼容性

**Comment by warmhug** [comment]
建议使用 chrome 稳定版（canary 经常会有bug），表现正常的；uc 浏览器是有点问题
