### ISSUE TITLE
ListView 使用吸顶时候出现问题

### ISSUE THREAD

**Issue by wcdhm** [ant-design/ant-design-mobile#640]
#### 本地环境

- antd-mobile 版本：0.9.10
- 浏览器 (或标明是 react-native) 及其版本：微信内置浏览器
- 运行环境及其版本：ios10.1.1

#### 你做了什么？
引入 antd-mobile 的 ListView,并且使用吸顶

#### 你期待的结果是：
正常使用

#### 实际上的结果：
![bug1](https://cloud.githubusercontent.com/assets/24520863/21213318/75bb9876-c2ce-11e6-810e-8071ee1ff2ca.png)
![bug2](https://cloud.githubusercontent.com/assets/24520863/21213319/75cd299c-c2ce-11e6-8681-40835f6451aa.png)

**Comment by warmhug** [comment]
描述不清楚！

**Comment by wcdhm** [comment]
在手机上向下拖拽就会出现这种问题    在线DEMO  http://mm-test.hec.com.cn/#/cart?_k=6cri7f

**Comment by warmhug** [comment]
如果方便的话、建议把代码放到 github 上，容易帮忙调试。或者自己试下把在 node_modules 里的 截图代码 这段去掉、再看看有没问题
![image](https://cloud.githubusercontent.com/assets/2011119/21219960/cb25b486-c2f1-11e6-8bb5-c86764a5719e.png)

**Comment by wcdhm** [comment]
恩  去掉那段代码确实好了  但是向下滚动时候   吸顶会消失

**Comment by warmhug** [comment]
可以恢复 node_modules 里的代码，通过在 ListView 属性上添加这样设置看下能否解决问题：
![image](https://cloud.githubusercontent.com/assets/2011119/21261305/79fa23a6-c3c5-11e6-8aa6-304942f4ee55.png)

**Comment by warmhug** [comment]
@wcdhm 麻烦确认下、最后那个截图的方法，能解决问题吗？
