### ISSUE TITLE
请问如何调整组件的样式

### ISSUE THREAD

**Issue by rurusgit** [ant-design/ant-design-mobile#641]
#### 本地环境

windows10，npm，webpack

- antd-mobile 版本：^0.9.11
- 浏览器 (或标明是 react-native) 及其版本：safari
- 运行环境及其版本：ios

#### 你做了什么？

import { List, InputItem} from 'antd-mobile';
<InputItem prefixListCls='ok'>
	<div className={ styles.accpswinput }></div>
</InputItem>

在.css中写 .ok-item input{} 样式无效，因为css的class打包后变成了 .ok-item__yu3324这样的类名。
请问下，是否有其它方法设置样式？

#### 你期待的结果是：

可以设置List和InputItem的样式

#### 实际上的结果：

无法设置

**Comment by warmhug** [comment]
对组件样式覆盖，使用 css module 的 global 来做
```css
:global {
  .ok-item input{}
}
```

**Comment by liyanxi** [comment]
@warmhug
 DatePicker 组件的样式怎么覆盖？？
因为它是依赖的Picker的样式，这个改起来没有效果，求助。。。

**Comment by anewcoder1992** [comment]
> 
> 
> @warmhug
> 环境：react-native
> 版本：antd-mobile 2.1.8
> DatePicker 组件的样式怎么覆盖？？
> 因为它是依赖的Picker的样式，这个改起来没有效果，求助。。。

我也碰到这个问题了 ant-mobile 无法覆盖 datepicker 组件的样式 有啥好的解决方案吗
