### ISSUE TITLE
安卓部分机型 Image组件图片加载不出来偶现

### ISSUE THREAD

**Issue by chencheng666** [ant-design/ant-design-mobile#6413]
### Version of antd-mobile

5.28.0

### Operating system and its version

Android

### Browser and its version

安卓系统： MIUI 12.5.12     机型：MI11Pro

### What happened?

安卓的h5界面使用的Image组件的列表，部分图片加载不出来 使用的是lazy加载模式 ，调试后发现image标签的src没有 style的display为none  将这个none的样式去除后 图片就出来了，ios上没有这个问题 本地浏览器调试也没有 只有部分的安卓机型会存在

### Relevant log output

```shell
<Image src={url} lazy={lazy} fallback={fallback} fit={fit} placeholder={fallback} style={{'borderRadius':radius}} height={resultHeight} width={resultWidth} {...rest}/>
调用的地方
```

**Comment by bjfxgao** [comment]
同样出现这个问题  只有在安卓手机  谷歌浏览器上  图片不渲染src

**Comment by Sneaken** [comment]
谷歌浏览器 横向滚动 IntersectionObserver 不触发 不知道为什么
