### ISSUE TITLE
Switch的checkedText和uncheckedText相同时，开关状态下组件宽度不一致，影响布局

### ISSUE THREAD

**Issue by KilianShen** [ant-design/ant-design-mobile#6418]
### Version of antd-mobile

5.33.0

### Operating system and its version

Others

### Browser and its version

edge 118.0.2088.76 

### What happened?

![image](https://github.com/ant-design/ant-design-mobile/assets/86402559/2c5ba675-84e0-49c2-aaab-7ed95bb25929)
![image](https://github.com/ant-design/ant-design-mobile/assets/86402559/420782af-9998-49ac-ac20-d806b4c52ec5)

**Comment by zombieJ** [comment]
试了一下的确宽度变了...

**Comment by KilianShen** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/86402559/236ec1a2-9a5a-4768-a5d8-02686532ad80)
