### ISSUE TITLE
使用抽屉导致微信闪退

### ISSUE THREAD

**Issue by wcdhm** [ant-design/ant-design-mobile#642]
#### 本地环境

- antd-mobile 版本：0.9.10
- 浏览器 (或标明是 react-native) 及其版本：微信内置浏览器
- 运行环境及其版本：

#### 你做了什么？
引入 antd-mobile 的 drawer

#### 实际上的结果：
闪退  使用浏览器没异常

#### 可重现的在线演示
http://mm-test.hec.com.cn/#/product_category_type?_k=csjeex

**Comment by warmhug** [comment]
iOS 10 和 Android 微信里都重现不了，请帮忙排查下，h5 页面不太可能导致微信闪退

**Comment by warmhug** [comment]
没反馈，先关掉
