### ISSUE TITLE
Tooltip 会增加多实例共存么，连续调用Toast.show，所有content都显示在页面上，类似于Ant Design的Message

### ISSUE THREAD

**Issue by mxmxixixi** [ant-design/ant-design-mobile#6420]
### What is this feature about?

Tooltip 会增加多实例共存么，连续调用Toast.show，所有content都显示在页面上，类似于Ant Design的Message

**Comment by zombieJ** [comment]
Toast 设计上是单例，只是没有去阻止。可以加，不过感觉同时出多个并不是设计的初衷。

**Comment by mxmxixixi** [comment]
不过现在连续调用Toast.show，页面支持出现第二次调用的内容，我想要
![A0E4FD8F-CF53-4158-8B62-50917B5953AB](https://github.com/ant-design/ant-design-mobile/assets/44132969/8e2287dc-e379-469c-83e5-e46283a5e4d0)
这种效果，怎么写呢

**Comment by 1587315093** [comment]
> 不过现在连续调用Toast.show，页面只出现第二次调用的内容，我想要 ![A0E4FD8F-CF53-4158-8B62-50917B5953AB](https://user-images.githubusercontent.com/44132969/279841012-8e2287dc-e379-469c-83e5-e46283a5e4d0.png) 这种效果，怎么写呢

感觉移动端很少这种一直堆信息的交互，要么就是把上一条清掉那种

**Comment by miracles1919** [comment]
用 Modal 或者 CenterPopup 自己封装下
