### ISSUE TITLE
ConfigProvider组件在nextjs13.4 app目录项目中能像antd-design一样，提供类似AntdRegistry.tsx来支持ssr配置多语言嘛

### ISSUE THREAD

**Issue by henniliu** [ant-design/ant-design-mobile#6423]
### Version of antd-mobile

5.33

### Operating system and its version

Others

### What happened?

![image](https://github.com/ant-design/ant-design-mobile/assets/50318028/c50754e4-8547-45d1-ae73-918fc108a911)

我在next.js 中像antd-design一样配置ConfigProvider组件，但却提示必须要添加‘use client’
能否像antd-design一样，支持让ConfigProvider组件可以不需要添加‘use client’ 
https://ant-design.antgroup.com/docs/react/use-with-next-cn

下面是报错信息：
![image](https://github.com/ant-design/ant-design-mobile/assets/50318028/213e1c24-6a3d-4bdb-8647-124caac0a3b0)

**Comment by zombieJ** [comment]
感觉可以加一个

**Comment by henniliu** [comment]
> 感觉可以加一个

现有方案上，有啥好思路可以不升级解决嘛～

**Comment by henniliu** [comment]
这个是我的解决方案，在next项目中，创建configProvider.tsx，然后将组件挂载到layout.tsx中，参考的是next官网给的例子：https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-context-providers
这个我先关闭了。
`
'use client';
//type
import { Locale } from 'antd-mobile/es/locales/base';

//ts
import { ConfigProvider } from 'antd-mobile';
import { createContext } from 'react';
import en from 'antd-mobile/es/locales/en-US';
import cn from 'antd-mobile/es/locales/zh-CN';

interface AntdLngConfigProps {
  [key: string]: Locale;
}
interface MobileConfigProviderType {
  children: React.ReactNode;
  lng: string;
}
const AntdMobileLngConfig: AntdLngConfigProps = {
  en,
  cn,
};

export const mobileConfigContext = createContext<string>();
export default function MobileConfigProvider({ children, lng }: MobileConfigProviderType) {
  return (
    <mobileConfigContext.Provider value={lng}>
      <ConfigProvider locale={AntdMobileLngConfig[lng]}>{children}</ConfigProvider>
    </mobileConfigContext.Provider>
  );
}
`

**Comment by bingqichen** [comment]
> 这个是我的解决方案，在next项目中，创建configProvider.tsx，然后将组件挂载到layout.tsx中，参考的是next官网给的例子：https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-context-providers 这个我先关闭了。 ` 'use client'; //type import { Locale } from 'antd-mobile/es/locales/base';
> 
> //ts import { ConfigProvider } from 'antd-mobile'; import { createContext } from 'react'; import en from 'antd-mobile/es/locales/en-US'; import cn from 'antd-mobile/es/locales/zh-CN';
> 
> interface AntdLngConfigProps { [key: string]: Locale; } interface MobileConfigProviderType { children: React.ReactNode; lng: string; } const AntdMobileLngConfig: AntdLngConfigProps = { en, cn, };
> 
> export const mobileConfigContext = createContext(); export default function MobileConfigProvider({ children, lng }: MobileConfigProviderType) { return ( <mobileConfigContext.Provider value={lng}> {children} </mobileConfigContext.Provider> ); } `

你好，问一下你这个是完整的吗，我反复试了一下没有效果，想请教一下有没有最小实现的代码参考一下

**Comment by loakliu** [comment]
> > 这个是我的解决方案，在next项目中，创建configProvider.tsx，然后将组件挂载到layout.tsx中，参考的是next官网给的例子：https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-context-providers 这个我先关闭了。 ` 'use client'; //type import { Locale } from 'antd-mobile/es/locales/base';
> > //ts import { ConfigProvider } from 'antd-mobile'; import { createContext } from 'react'; import en from 'antd-mobile/es/locales/en-US'; import cn from 'antd-mobile/es/locales/zh-CN';
> > interface AntdLngConfigProps { [key: string]: Locale; } interface MobileConfigProviderType { children: React.ReactNode; lng: string; } const AntdMobileLngConfig: AntdLngConfigProps = { en, cn, };
> > export const mobileConfigContext = createContext(); export default function MobileConfigProvider({ children, lng }: MobileConfigProviderType) { return ( <mobileConfigContext.Provider value={lng}> {children} </mobileConfigContext.Provider> ); } `
> 
> 你好，问一下你这个是完整的吗，我反复试了一下没有效果，想请教一下有没有最小实现的代码参考一下



> > 这个是我的解决方案，在next项目中，创建configProvider.tsx，然后将组件挂载到layout.tsx中，参考的是next官网给的例子：https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-context-providers 这个我先关闭了。 ` 'use client'; //type import { Locale } from 'antd-mobile/es/locales/base';
> > //ts import { ConfigProvider } from 'antd-mobile'; import { createContext } from 'react'; import en from 'antd-mobile/es/locales/en-US'; import cn from 'antd-mobile/es/locales/zh-CN';
> > interface AntdLngConfigProps { [key: string]: Locale; } interface MobileConfigProviderType { children: React.ReactNode; lng: string; } const AntdMobileLngConfig: AntdLngConfigProps = { en, cn, };
> > export const mobileConfigContext = createContext(); export default function MobileConfigProvider({ children, lng }: MobileConfigProviderType) { return ( <mobileConfigContext.Provider value={lng}> {children} </mobileConfigContext.Provider> ); } `
> 
> 你好，问一下你这个是完整的吗，我反复试了一下没有效果，想请教一下有没有最小实现的代码参考一下

方便的话，你可以把你的demo贴出来下，我可以抽空帮你看看

**Comment by bingqichen** [comment]
@loakliu 可以了，感谢兄弟相助！！
