### ISSUE TITLE
[SearchBar] 点击 取消的时候 输入框的值被清空

### ISSUE THREAD

**Issue by xiyangranhongyan** [ant-design/ant-design-mobile#6433]
### Version of antd-mobile

5.33.0

### Operating system and its version

iOS

### Browser and its version

ios chrome 110.0

### Sandbox to reproduce

https://codesandbox.io/s/nostalgic-haze-n47jch?file=/src/App.tsx

### What happened?

点击 取消 的时候输入框的值被清空了，我认为取消的作用应该只是将取消按钮隐藏，`SearchBar`样式 恢复，清空值的操作应由清除图标完成，否则功能是有交叉的。

另外，预期的是 防止用户误操作点到了输入框，然后点击取消，这时候 取消操作 并保留原来的值，从这个场景看 不清空值是比较合理的，否则 输入框的值被清空之后，那么我们的数据就 需要重新进行搜索并更新页面。

![image](https://github.com/ant-design/ant-design-mobile/assets/31724313/57ad94c7-c936-428e-b11b-c157783b168d)

**Comment by zombieJ** [comment]
预设行为都可以通过受控改掉了：

https://codesandbox.io/s/broken-haze-l8zvch?file=/src/App.tsx
