### ISSUE TITLE
version: https://antd-mobile-v2.surge.sh/components/radio-cn

### ISSUE THREAD

**Issue by vinal123** [ant-design/ant-design-mobile#6435]
### Version of antd-mobile

version: ^2.3.4

### What happened?

我们这是一个4年前的老项目，偶尔在维护。
从本周开始，组件网站无法访问了 https://antd-mobile-v2.surge.sh/components/radio-cn， 
yarn的第三方依赖也不能用了 运行就报错 导致现在无法开发
![image](https://github.com/ant-design/ant-design-mobile/assets/12440227/b4887d78-57ff-461a-b2db-ccf7b6e86273)

**Comment by afc163** [comment]
我实测可以访问，你可能需要翻墙。

**Comment by zombieJ** [comment]
翻一下墙，这边试了可以访问哈。
