### ISSUE TITLE
Picker组件mask样式在legacy mode下不生效

### ISSUE THREAD

**Issue by Pulset** [ant-design/ant-design-mobile#6443]
### Version of antd-mobile

5.32.4

### Operating system and its version

iOS, Android

### What happened?

<img width="1911" alt="image" src="https://github.com/ant-design/ant-design-mobile/assets/21022593/7cefc37a-ff82-4dee-9de7-2176c46484a7">

picker-view.css中是有样式的，但是浏览器没有生效
.adm-picker-view-mask-top {
  background: var(--adm-color-background);
  -webkit-mask: linear-gradient(0deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0.8) 50%, #000000 100%);
          mask: linear-gradient(0deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0.8) 50%, #000000 100%);
}
当umi legacy mode开启的时候会出现问题，关闭的时候正常

**Comment by zombieJ** [comment]
`mask` 属性在 Chrome 下是 `-webkit-mask` 前缀。这个在 postcss 里会自动加上，看截图没有。推测是框架配置的问题。

我估计是 legacy 外 postcss 还要加什么，可以去 umi 文档搜一搜或者 github 问一问哈。

**Comment by day-xue** [comment]
怎么解决的最后。。。我也是umi 没开启legacy
