### ISSUE TITLE
ProgressCircle 进度圈能否有渐变色

### ISSUE THREAD

**Issue by TangDeYu** [ant-design/ant-design-mobile#6447]
### Version of antd-mobile

5.33.0

能否像ProgressBar 进度条一样使用渐变色 
 <ProgressBar
    percent={70}
      style={{
        '--fill-color':
          'linear-gradient(to right, var(--adm-color-primary), var(--adm-color-success))',
      }}
  />

**ProgressCircle组件设置不生效**

**Comment by 1587315093** [comment]
ProgressCircle的颜色是 svg stroke 写的

CSS Stroke 不支持渐变效果。这是因为 CSS Stroke 主要用于定义图形元素的轮廓线样式，而不是填充样式。因此，无法使用渐变效果来改变图形元素的边框线条样式。

这里有个canvas 支持渐变的，希望对你有用
https://codepen.io/miaoduanwang/pen/vpgYBB
