### ISSUE TITLE
closeOnSwiper 在popup上设置了没有效果

### ISSUE THREAD

**Issue by wanlixi** [ant-design/ant-design-mobile#6452]
### Description

closeOnSwiper 在popup上设置了没有效果

**Comment by wanlixi** [comment]
版本是v5.33.0

**Comment by kongdemin** [comment]
这还用复现？直接加上后真机就是没效果呀

**Comment by ZHOUKAIZHI** [comment]
<img width="479" alt="image" src="https://github.com/user-attachments/assets/7e8e4d41-4f19-441d-ba6a-11a4c2b7adc9">
