### ISSUE TITLE
TabBar使用badge时，加入badge属性的TabBar图片不显示

### ISSUE THREAD

**Issue by pzhgugu** [ant-design/ant-design-mobile#646]
#### 本地环境

- antd-mobile 版本：0.9.12
- 浏览器 (或标明是 react-native) 及其版本：windows web
- 运行环境及其版本：chrome

#### 你做了什么？
TabBar使用badge时，加入badge属性的TabBar图片不显示，去除badge后显示正常

**Comment by warmhug** [comment]
`icon={{uri: require('./TabBar_HomeBar_web.png')}}`或`icon={{uri: 'https://xxxx.png'}}`

**Comment by warmhug** [comment]
@silentcloud 已把 tabbar master 上的代码同步到 0.9.x 上，除了 web demo 的 svg icon 不同、其他都相同。
