### ISSUE TITLE
antd-mobile.umd.js，Chrome 62报错

### ISSUE THREAD

**Issue by whyer11** [ant-design/ant-design-mobile#6465]
### Version of antd-mobile

5.33.0

### Operating system and its version

Android

### Browser and its version

Chrome 61

### What happened?

![image](https://github.com/ant-design/ant-design-mobile/assets/5457239/c92ed717-fa3d-4cb4-baf3-c01e2f318e36)
![image](https://github.com/ant-design/ant-design-mobile/assets/5457239/d39ca8d0-daa5-47ea-922e-50d7b002d924)

**Comment by zombieJ** [comment]
旧版浏览器请参考打包框架的兼容配置，antd mobile 侧做不了什么哈~

**Comment by whyer11** [comment]
> 旧版浏览器请参考打包框架的兼容配置，antd mobile 侧做不了什么哈~

![image](https://github.com/ant-design/ant-design-mobile/assets/5457239/545f7059-1489-4114-8f03-72ae0c9a66b9)

指南中是声明最低支持到chrome61
