### ISSUE TITLE
ImageUploader 设置 deletable 无效

### ISSUE THREAD

**Issue by H2orange** [ant-design/ant-design-mobile#6469]
### Version of antd-mobile

5.33.0

### Operating system and its version

iOS, Android, Others

### Browser and its version

Microsoft Edge 版本 119.0.2151.44

### What happened?

设置ImageUploader组件的 deletable 属性 无效，设置为false后仍然显示右上角删除按钮，点击后仍然可删除

**Comment by chk4658** [comment]
+1

**Comment by 1587315093** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/77056991/e52d2d85-722d-4dc5-8c7e-d4cc169b46f5)

这里看没问题唉。

咋用的，提供下复现代码
