### ISSUE TITLE
请问Switch组件能否等比缩放大小？

### ISSUE THREAD

**Issue by ssjjnn** [ant-design/ant-design-mobile#647]
如题

**Comment by warmhug** [comment]
什么意思？现在不是可以根据 rem 设置自适应吗？

**Comment by ssjjnn** [comment]
就是类似于button的size（设置按钮大小，可选值为 small large 或者不设），我不想改变整体rem的基准值，只想改变其中某一个，我要手动调它的宽高么？

**Comment by warmhug** [comment]
恩，这个手动调整吧，还没见过小的 switch 的需求

**Comment by ssjjnn** [comment]
![image](https://cloud.githubusercontent.com/assets/22025844/21310735/9a9a6e12-c61e-11e6-863a-38785b898df9.png)
![image](https://cloud.githubusercontent.com/assets/22025844/21310788/c490c554-c61e-11e6-9f33-ee9a2efd358c.png)
我修改了html标签里面的font-size的值，为什么switch组件并没有相应的放大或缩小呢？它的单位不是rem么，font-size不是它的基准值么？

**Comment by warmhug** [comment]
会的

**Comment by warmhug** [comment]
组件没问题，请确认自己代码是否有问题
