### ISSUE TITLE
Picker组件 下载后 mask 没有带上 -webkit-mask 导致mask 这个属性在谷歌浏览器失效

### ISSUE THREAD

**Issue by day-xue** [ant-design/ant-design-mobile#6479]
### Version of antd-mobile

5.33

### Operating system and its version

iOS

### Browser and its version

谷歌

### Sandbox to reproduce

复线不出 我本地是这样的

### What happened?

期望能带上mask。。。

**Comment by miracles1919** [comment]
Picker 没有 mask 这个属性

**Comment by day-xue** [comment]
> Picker 没有 mask 这个属性

是css

**Comment by 1587315093** [comment]
提供代码或者截图

**Comment by 1587315093** [comment]
提供代码或者截图

**Comment by day-xue** [comment]
> 提供代码或者截图

<img width="1533" alt="image" src="https://github.com/ant-design/ant-design-mobile/assets/95938844/6241cef9-0e78-430a-b36d-f0260b756b64">

.adm-picker-view-mask-top,.adm-picker-view-mask-bottom 这个mask 不被谷歌兼容 需要加-webkit- 前缀

**Comment by sean-skkk** [comment]
确实我也发现这个问题了

**Comment by 1587315093** [comment]
https://www.npmjs.com/package/antd-mobile?activeTab=code
