### ISSUE TITLE
VirtualInput 和 NumerKeyBoard 无障碍模式下的问题

### ISSUE THREAD

**Issue by majiang666** [ant-design/ant-design-mobile#6486]
### Version of antd-mobile

5.33.1

### Operating system and its version

iOS, Android

### Browser and its version

支付宝

### Sandbox to reproduce

官方示例即可复现

### What happened?

1.输入框在无障碍模式下，单指双击不生效，拉不起来数字键盘
2.数字键盘中的收起和删除都是英文，读取也是英文，预期中文
3.输入 input 默认会读两次，需要优化掉 title
4.无障碍下的其他的一些问题

**Comment by majiang666** [comment]
5: VirtualInput 和 NumerKeyBoard一起使用时，两个模块读取耦合在一起，会先读input文案然后读数字1234567890

**Comment by zombieJ** [comment]
有兴趣来个 PR 吗~

**Comment by gyk0818** [comment]
Android环境下NumberKeyBoard组件数字按钮读取不正确，一直朗读“表格”

**Comment by majiang666** [comment]
> 有兴趣来个 PR 吗~

可以的哈

**Comment by gyk0818** [comment]
> > 有兴趣来个 PR 吗~
> 
> 可以的哈

帮忙关注下数字按钮朗读哈～

**Comment by majiang666** [comment]
> Android环境下NumberKeyBoard组件数字按钮读取不正确，一直朗读“表格”

是的，要改成 button

**Comment by gyk0818** [comment]
> > Android环境下NumberKeyBoard组件数字按钮读取不正确，一直朗读“表格”
> 
> 是的，要改成 button

应该还得朗读出内容，1、2这种，现在Android端只朗读出表格两个字。

**Comment by 1587315093** [comment]
> > 有兴趣来个 PR 吗~
> 
> 帮忙给下提交权限？谢谢

提PR不需要开权限的，fork下仓库push到自己的分支,然后就可以提pull request了

**Comment by 1587315093** [comment]
#6494
