### ISSUE TITLE
adm-px-tester的bottom样式导致打印时多出一个空白页面

### ISSUE THREAD

**Issue by taterboom** [ant-design/ant-design-mobile#6487]
### Version of antd-mobile

5.31.1

### Browser and its version

Chrome 120.0.6099.109 (Official Build) (arm64) 

### What happened?

如果该网页的内容只有一页，会在打印时多出一个空白页面。

实际测试发现去掉 .adm-px-tester的样式 `bottom: -100vh` 就表现正常了。

**Comment by zombieJ** [comment]
给个重现看看，如何打印的？

**Comment by taterboom** [comment]
使用官方 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 即可。
使用浏览器打印，比如在macOS上用快捷键 cmd+P
