### ISSUE TITLE
Stepper 的值可以为空

### ISSUE THREAD

**Issue by ShadowRambler** [ant-design/ant-design-mobile#649]
#### 本地环境

- antd-mobile 版本：0.9.12
- 浏览器 (或标明是 react-native) 及其版本：chrome 54.0.2840.98
- 运行环境及其版本：

#### 你做了什么？

通过input将可以将stepper的值设为空

#### 你期待的结果是：

stepper的值保持原始值不变

#### 实际上的结果：

 
 stepper的值变成空值

**Comment by warmhug** [comment]
onChange 在 value 删除到空时，不会触发 https://github.com/react-component/input-number/blob/master/src/mixin.js#L115 @afc163

**Comment by afc163** [comment]
给代码或重现

**Comment by warmhug** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/components/stepper/demo/form.md
![image](https://cloud.githubusercontent.com/assets/2011119/21309951/4364e990-c61b-11e6-850f-7ab25ab02f06.png)
console.log 去掉，把 value 退格到空值，这里 console.log 不会被执行，blur 后会执行

**Comment by afc163** [comment]
是这样的啊，input-number 的逻辑一直都是这样。

**Comment by warmhug** [comment]
这样不对吧
