### ISSUE TITLE
SreachBar less处理问题 以及取消按钮显示不全问题

### ISSUE THREAD

**Issue by deerW** [ant-design/ant-design-mobile#650]
#### 本地环境

- antd-mobile 版本：0.9.*
- 浏览器 (或标明是 react-native) 及其版本：iphone7 plus 微信浏览器
- 运行环境及其版本：mac

#### 你做了什么？

引入 antd-mobile 的 SearchBar
在 iphone7 plus微信浏览器上 “取消”按钮显示不全

#### 你期待的结果是：

1.不需要自己处理less
2.样式显示跟官网一样

#### 实际上的结果：

1.需要自己处理less
2.![](https://static.dingtalk.com/media/lADOk3rlD80FAM0C0A_720_1280.jpg_620x10000q90.jpg)

**Comment by warmhug** [comment]
模拟器里没发现此问题，欢迎帮忙排查下，多谢

**Comment by deerW** [comment]
有一台手机出现了这个问题，其他手机木有问题。但是less的问题希望可以处理一下，谢谢。 @warmhug

**Comment by warmhug** [comment]
less 问题和这个一样吗？https://github.com/ant-design/ant-design-mobile/issues/599#issuecomment-268289190

**Comment by deerW** [comment]
我的配置是没有问题的，当时引入searchBar的时候报错。后来在webpack.json中加了less配置才好
![image](https://cloud.githubusercontent.com/assets/20079361/21380548/069c337a-c791-11e6-91d4-eb81f0f9de27.png)

**Comment by deerW** [comment]
使用searchBar的时候又发现一个bug 找的我好辛苦= =

**Comment by deerW** [comment]
使用searchBar的时候又发现了一个bug，找的我好辛苦。。是这样的：
placeholder 属性会使input框内的文字无法获取焦点
当placeholder设置较长时，再输入文字，点击placeholder范围内的区域是无法输入的。只有点击后面的空白部分才可以获取焦点，官方demo可以复现，只要把placeholder的值再加长一些更好复现。这个问题需要帮忙解决一下，谢谢。 @warmhug

**Comment by warmhug** [comment]
已发现问题，下个版本修复。你可以本地先覆盖下样式、可临时解决问题
```css
.am-search-synthetic-ph {
  z-index: 1!important;
}
```

**Comment by deerW** [comment]
好的，谢谢。
