### ISSUE TITLE
淘汰 lodash/lodash-es 依赖

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design-mobile#6523]
### Version of antd-mobile

5.33.0

### What is this feature about?

不管是 lodash 还是 lodash-es, 即使正确的 tree-shaking, 都会带来几十 KB 的体积（antd-mobile 实际上只用了 4 个 lodash 函数），是否可以用更轻量化的库来替换，或者使用原生代码替代 https://youmightnotneed.com/lodash/

**Comment by afc163** [comment]
+1

**Comment by Michael18811380328** [comment]
+1

**Comment by guoyunhe** [comment]
antd-mobile 产物已不再依赖 lodash
