### ISSUE TITLE
表单项点击label文字时，能否不自动定焦表单

### ISSUE THREAD

**Issue by yeesunday** [ant-design/ant-design-mobile#6548]
### Version of antd-mobile

5.34.0

### Sandbox to reproduce

https://codesandbox.io/p/sandbox/clever-sky-q4t5wl

### What happened?

![image](https://github.com/ant-design/ant-design-mobile/assets/1524720/af52ee90-81a8-4d30-b413-3dbcabe2a75b)

如图，我想点击帮助icon查看提示信息，结果激活了表单，底下弹出了轮盘把提示信息遮挡了

**Comment by damonyoungcc** [comment]
这里似乎源码没有阻止冒泡，看下要不要修这个bug
```
  const labelElement = !!label && (
    <label className={`${classPrefix}-label`} htmlFor={htmlFor}>
      {label}
      {requiredMark}
      {help && (
        <Popover content={help} mode='dark' trigger='click'>
          <span
            className={`${classPrefix}-label-help`}
            onClick={e => {
              // 这里源码没有阻止冒泡
              e.preventDefault()
            }}
          >
            <QuestionCircleOutline />
          </span>
        </Popover>
      )}
    </label>
  )
```

或者还有一个办法，你可以传一个定制的label进去，不要用help属性，把label定制成你想要的文本和图标，然后图标点击事件的时候阻止冒泡

**Comment by yeesunday** [comment]
@damonyoungcc 感谢回复~自定义 label 这个方案在业务里可能不太行，因为我是通过 form-render-mobile 生成的表单。从 antd mobile 库本身修复会更合适，其他用户应该也有类似问题
