### ISSUE TITLE
List 组件使用 flex 将 content 和 extra 平分导致的空间浪费

### ISSUE THREAD

**Issue by hotoo** [ant-design/ant-design-mobile#655]
#### 本地环境

- antd-mobile 版本：1.0.0-alpha.33
- 浏览器 (或标明是 react-native) 及其版本：任意浏览器
- 运行环境及其版本：

#### 你做了什么？

ListItem 有 extra 时，将 content 和 extra 使用 flex 布局平分了左右空间，会导致内容较多一方显示 ... 而内容较少一方空间闲置。

#### 你期待的结果是：

希望能做到左右按需占用空间。

#### 实际上的结果：

左右平分空间，内容多的一方显示 ...，内容少的一方空间闲置。

#### 可重现的在线演示

https://codepen.io/hotoo/pen/PbLwPR

**Comment by hotoo** [comment]
![image](https://cloud.githubusercontent.com/assets/143572/21344494/02c5b86c-c6d7-11e6-825b-5075d2128583.png)

**Comment by warmhug** [comment]
这个空间分配可以讨论下，可以把靠右的`am-list-extra`样式去掉 flex: 1 设置，那`am-list-extra`部分就是根据自身内容多少来占空间；这样靠左边的`am-list-content`占据剩余的所有宽度（有可能大有可能小）、来显示主要内容。

@pingan1927 @silentcloud

**Comment by warmhug** [comment]
可以只改一个地方把`am-list-extra`的 flex: 1 改为 flex-basis: 36%; 分配接近 1/3 的总宽度

**Comment by pingan1927** [comment]
```
.am-list {
  .am-list-item.shop-item {
    .am-list-content {
      -webkit-box-flex: 3;
      -webkit-flex: 3;
    }
  }
}
```

一般我会添加class，做下定制

**Comment by hotoo** [comment]
我给你提了个问题，但是你们的解决方案带来了新的问题。。。

![image](https://cloud.githubusercontent.com/assets/143572/21498162/2992b128-cc65-11e6-88dc-79e7b9a8b56d.png)
