### ISSUE TITLE
卡片没有边框的设定

### ISSUE THREAD

**Issue by yetrun** [ant-design/ant-design-mobile#6550]
### What is this feature about?

https://mobile.ant.design/zh/components/card 的示例上能看到边框，但实践效果却没有边框。建议添加边框的设定。

**Comment by 1587315093** [comment]
没理解 是这个边框吗，你是不是得加标题才有边框

![image](https://github.com/ant-design/ant-design-mobile/assets/77056991/61bbb61f-b6ff-4856-a298-1aa596d2a4b5)
