### ISSUE TITLE
1.0 Steps组件问题

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#656]
#### 本地环境

- antd-mobile 版本：1.0.0-alpha.33
- 浏览器 (或标明是 react-native) 及其版本：0.39.2
- 运行环境及其版本：mac

#### 实际上的结果：
问题一：一个界面需要如果只有Steps组件则页面显示空白
问题二：界面中增加了ScrollView组件后可以显示出来，但无法使用水平显示
问题三：使用组件Steps.Step的status属性，直接报错

**Comment by silentcloud** [comment]
问题1，2 已修复，至于水平的 steps，目前没有 rn 版本；
问题3 没问题，参见官方 demo
