### ISSUE TITLE
Tabs.Tab作为一个组件封装后，引入到Tabs下显示不出来

### ISSUE THREAD

**Issue by SingleShadow** [ant-design/ant-design-mobile#6566]
### Version of antd-mobile

 v5.34.0

### Operating system and its version

Others

### Browser and its version

Google Chrome 116.0.5845.187

### Sandbox to reproduce

https://codesandbox.io/p/sandbox/dawn-paper-367ysn?file=%2Fsrc%2FApp.tsx%3A36%2C46

**Comment by 1587315093** [comment]
Tabs 会传递一些props进去给子组件 Tab，拆出来缺少了某些属性了
