### ISSUE TITLE
同时使用 antd 和 antd mobile 后，antd 的 icon 会被替换

### ISSUE THREAD

**Issue by markzhai** [ant-design/ant-design-mobile#657]
#### 本地环境

- antd-mobile 版本：0.9.12
- antd 版本：2.5.2
- 浏览器版本：Chrome 版本 55.0.2883.95 (64-bit)
- 运行环境及其版本：MacOS

#### 你做了什么？

引入 antd-mobile 的 Navbar 后，全局的 iconfont 部分改变了，下拉框从原来的黑色变成了奇怪的圆圈内套着箭头

#### 你期待的结果是：

不影响 ant design 的 Icon。
![2016-12-20 17 45 27](https://cloud.githubusercontent.com/assets/1106500/21345756/5fe7e88a-c6dc-11e6-9c0b-7c0cea5277c5.png)

#### 实际上的结果：

ant design 被改变了。
![2016-12-20 17 44 32](https://cloud.githubusercontent.com/assets/1106500/21345750/5c1899b6-c6dc-11e6-982a-6f10c239b646.png)
![2016-12-20 17 44 45](https://cloud.githubusercontent.com/assets/1106500/21345760/62517d84-c6dc-11e6-8d47-c53189d7d37d.png)

#### 可重现的在线演示

https://pai.bigins.cn/
测试账号：87224330@qq.com
密码：123456

**Comment by warmhug** [comment]
navbar 组件比较简单，可以自己实现下，就不用引入 antd-mobile 了

**Comment by warmhug** [comment]
没反馈，先关掉

**Comment by markzhai** [comment]
@warmhug 那如果也需要使用其他组件呢？两个库的 icon 为什么会冲突？

**Comment by warmhug** [comment]
@markzhai  1.0 正式版即将发布，采用了 svg icon 不会跟 antd 有冲突，现在可以先试用下 1.0beta 版的
