### ISSUE TITLE
InputItem组件在支付宝应用中extra右边注释为node类型的问题

### ISSUE THREAD

**Issue by ctq123** [ant-design/ant-design-mobile#659]
#### 本地环境

- antd-mobile 版本：@0.9.11
- 浏览器 (或标明是 react-native) 及其版本：支付宝应用内置的UC浏览器，web应用
- 运行环境及其版本：支付宝应用

#### 你做了什么？

引入antd-mobile的InputItem组件，在其属性extra后使用node类型（<span></span>）

#### 你期待的结果是：

像微信web应用一样正常显示 

#### 可重现的在线演示

http://membermobile-test.800best.com/#/binding

**Comment by ctq123** [comment]
正常
![image](https://cloud.githubusercontent.com/assets/12124169/21376087/3539135c-c76d-11e6-878d-6604a38eb6a3.png)

**Comment by ctq123** [comment]
![image](https://cloud.githubusercontent.com/assets/12124169/21376124/733c2dd8-c76d-11e6-8cbe-45221cec8064.png)
这是正常情况

**Comment by ctq123** [comment]
![image](https://cloud.githubusercontent.com/assets/12124169/21376134/8a3a40ec-c76d-11e6-98a8-e1099d178003.png)
这是支付宝情况

**Comment by ctq123** [comment]
![image](https://cloud.githubusercontent.com/assets/12124169/21376165/c1627e9a-c76d-11e6-813d-c3621c854092.png)
这是支付宝情况

**Comment by warmhug** [comment]
重现示例打不开

**Comment by warmhug** [comment]
没响应，关掉
