### ISSUE TITLE
selector组件选中高亮存在因包含关系判断错误问题

### ISSUE THREAD

**Issue by aofong** [ant-design/ant-design-mobile#6590]
### Version of antd-mobile

5.35.0

### Operating system and its version

iOS

### What happened?

如图所示我选择1000的时候会高亮100和1000，组件并没有设置多项属性
查看源码发现使用的是遍历选项值是否包含在选中值中
```js
 const items = props.options.map(option => {
    const active = (value || []).includes(option[valueName])
    const disabled = option[disabledName] || props.disabled
    const itemCls = classNames(`${classPrefix}-item`, {
      [`${classPrefix}-item-active`]: active && !props.multiple,
      [`${classPrefix}-item-multiple-active`]: active && props.multiple,
      [`${classPrefix}-item-disabled`]: disabled,
    })
})
```
[查看源码位置](https://github.com/ant-design/ant-design-mobile/blob/cf550e43989cbe9f0cc2c78cb84dd57ac5b4fff9/src/components/selector/selector.tsx#L74)

![WX20240408-093959@2x](https://github.com/ant-design/ant-design-mobile/assets/3070161/518f596d-8f1d-46a2-a480-7ba3c1f197e8)

**Comment by Przeblysk** [comment]
![CleanShot2024-04-08at11 02 29@2x](https://github.com/ant-design/ant-design-mobile/assets/18001272/36f0e9a3-fc2c-4a65-88f2-cb39fafd94f4)
没有复现 [demo](https://codesandbox.io/p/sandbox/sleepy-flower-pdpncr?file=%2Fapp.tsx%3A9%2C7-15%2C19&resolutionHeight=700&resolutionWidth=375&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluqd8gxf00073b6pfaqukzqd%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluqd8gxf00033b6p4j0tmdco%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluqd8gxf00043b6pu4qt3wgc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluqd8gxf00063b6psfbzijw5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluqd8gxf00033b6p4j0tmdco%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluqd8gxf00023b6ptatxni3l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A7%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A19%257D%255D%257D%255D%252C%2522id%2522%253A%2522cluqd8gxf00033b6p4j0tmdco%2522%252C%2522activeTabId%2522%253A%2522cluqd8gxf00023b6ptatxni3l%2522%257D%252C%2522cluqd8gxf00063b6psfbzijw5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluqd8gxf00053b6p1g5v5gx7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluqd8gxf00063b6psfbzijw5%2522%252C%2522activeTabId%2522%253A%2522cluqd8gxf00053b6p1g5v5gx7%2522%257D%252C%2522cluqd8gxf00043b6pu4qt3wgc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluqd8gxf00043b6pu4qt3wgc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by aofong** [comment]
@Przeblysk 
这里有复现的[demo](https://stackblitz.com/edit/remix-run-remix-mn91wc?file=app%2Froutes%2F_index.tsx) remix框架中运行的，选中demo中的1000或者5000都可以复习

**Comment by Przeblysk** [comment]
> @Przeblysk 这里有复现的[demo](https://stackblitz.com/edit/remix-run-remix-mn91wc?file=app%2Froutes%2F_index.tsx) remix框架中运行的，选中demo中的1000或者5000都可以复习

你demo的外层form去掉没有问题~

**Comment by aofong** [comment]
@Przeblysk 我是想要放到 form 表单里面使用的，去掉了 form，就不方便了吧

**Comment by Przeblysk** [comment]
> @Przeblysk 我是想要放到 form 表单里面使用的，去掉了 form，就不方便了吧

你用法不对嘛兄弟 [form demo](https://stackblitz.com/edit/remix-run-remix-szcw8h?file=app%2Froutes%2F_index.tsx)

**Comment by aofong** [comment]
> > @Przeblysk 我是想要放到 form 表单里面使用的，去掉了 form，就不方便了吧
> 
> 你用法不对嘛兄弟 [form demo](https://stackblitz.com/edit/remix-run-remix-szcw8h?file=app%2Froutes%2F_index.tsx)

谢谢，是这里的问题
<img width="299" alt="image" src="https://github.com/ant-design/ant-design-mobile/assets/3070161/b47d3c6f-9617-46d0-add6-b2eb4f57710c">
