### ISSUE TITLE
ios 16.5.1 input 输入框中光标是白色，选择键盘提示文本有空格 怎么处理

### ISSUE THREAD

**Issue by lhb11** [ant-design/ant-design-mobile#6595]
### Version of antd-mobile

^5.31.0

### Description

 input 输入框中光标是白色，键盘的工具兰字体也是白色，这个怎么设置，键盘提示的文案确定有空格

**Comment by zombieJ** [comment]
我理解这个不是 antd-mobile 的问题，可以去 知乎 或者 stackoverflow 提问如何修改样式哈~
