### ISSUE TITLE
帮人解决问题时，发现antd-mobile缺少package.js里的main节点，导致webpack打包报错

### ISSUE THREAD

**Issue by xpcode** [ant-design/ant-design-mobile#660]
#### 本地环境

- antd-mobile 版本：0.9
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：

#### 你做了什么？

使用webpack打包插件DllPlugin生成js

#### 你期待的结果是：

打包正常

#### 实际上的结果：

找不到antd-mobile包

**解决方案：npm install时生成的package.json文件中，加入 main: 'lib/index.web.js'（默认是index，所以找不到）**

**Comment by motorguo** [comment]
加这个了么
```
resolve: {
    extensions: ['', '.web.js', '.js', 'json'],
}
```

**Comment by xpcode** [comment]
@motorguo 加了试了下也不行啊，package.json里加入main: 'lib/index.web.js'就行了

**Comment by huangshunping** [comment]
我来补充下，使用npm install antd-mobile后，在生成的node_modules\antd-mobile\package.json文件里面添加："main": "lib/index.web.js"
另外，我正好也在用antd，antd的package.json脚本里面有这么一句："main": "dist/antd"
是不是大侠漏掉了呀~~~~

**Comment by warmhug** [comment]
参考讨论 #602
