### ISSUE TITLE
在Form.Item中联动Picker出现问题

### ISSUE THREAD

**Issue by Tejimeng** [ant-design/ant-design-mobile#6600]
### Version of antd-mobile

5.34.0

### Description

![ba68c3b33a8471ecd43f7136f7364ec](https://github.com/ant-design/ant-design-mobile/assets/137048130/9c4a1437-e48b-4e8b-8cf9-e97689d615d2)
![53f8849314b7bb961458663be6ad380](https://github.com/ant-design/ant-design-mobile/assets/137048130/e66ea029-5b1f-49e0-bc0b-813ebe566e30)
![d04c48209607c8057960dc9bb3e93fc](https://github.com/ant-design/ant-design-mobile/assets/137048130/2c9b1167-7b7e-44f9-8835-c429484e81f7)
我按照官网的Form中的FAQ来的，但是不知道为什么出问题了

**Comment by Tejimeng** [comment]
已经解决了

**Comment by daidaic** [comment]
咋解决的 🥺源码
