### ISSUE TITLE
chunk styles [mini-css-extract-plugin] 关于 antd-mobile 样式冲突问题,

### ISSUE THREAD

**Issue by PineyZhang** [ant-design/ant-design-mobile#6610]
### Version of antd-mobile

5.34.0

### Description

使用 npm run dev 时，控制台提示以下错误信息：

chunk styles [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/@zeit/next-css/node_modules/css-loader??ref--7-2!./node_modules/antd-mobile/es/global/global.css
 * css ./node_modules/@zeit/next-css/node_modules/css-loader??ref--7-2!./node_modules/antd-mobile/es/components/dot-loading/dot-loading.css
 * css ./node_modules/@zeit/next-css/node_modules/css-loader??ref--7-2!./node_modules/antd-mobile/es/components/spin-loading/spin-loading.css
 * css ./node_modules/@zeit/next-css/node_modules/css-loader??ref--7-2!./node_modules/antd-mobile/es/components/auto-center/auto-center.css
 * css ./node_modules/@zeit/next-css/node_modules/css-loader??ref--7-2!./node_modules/antd-mobile/es/components/mask/mask.css

其他信息：
antd-mobile: 5.34.0
react: 16.8.0
next: 9.5.3
系统：macOS 13.6

**Comment by zombieJ** [comment]
antd 系的 css 文件都是独立的，对 order 没有强制要求。这个 warning 对 antd-mobile 是没有意义的哈~

**Comment by PineyZhang** [comment]
什么意思呢？请问那改如何处理这个冲突呢？
