### ISSUE TITLE
Ellipsis组件在Collapse里使用时，第一次打开页面加载时，会出现展开一下空白，然后再收起得

### ISSUE THREAD

**Issue by yangqiyyds** [ant-design/ant-design-mobile#6619]
### Version of antd-mobile

5.36.0

### Operating system and its version

iOS, Android, Others

### Browser and its version

chrome 124.0.6367.119

### Sandbox to reproduce

https://codesandbox.io/p/sandbox/ellipsis-collapse-use-tzt3px?file=%2Fsrc%2FApp.js%3A10%2C16

### What happened?

![复现](https://github.com/ant-design/ant-design-mobile/assets/108038139/e0c6e68b-6b34-46ec-9b6f-eb3df094988b)

**Comment by yezhonghu0503** [comment]
俺来试试，似乎计算高度的时候把content完整的高度计算进去了

**Comment by yezhonghu0503** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/61587068/c55a85eb-1c64-4f09-a3e0-5e2f140219c4)
大概看了下，Collapse的是用useSpring来做动画的渲染，这里是用height.to来动态计算传入的props的内容的高度，但是在收起时，这里props.children是没有内容的，并且Ellipsis也要计算高度，是在组件初始化时计算的，所以这里的冲突应该是Ellipsis计算好高度之后使用了默认传入的content，导致Collapse组件认为content是实际高度，所以就有一个高度计算的错误，后续Ellipsis计算好高度后，Collapse才得到真正的被收缩的content的内容，才更新了真正的高度，而且Ellipsis计算高度的函数是在useIsomorphicLayoutEffect钩子函数里面调用的，在内容没有更新之前，它的高度是不会变化的，因此只有第一次会发生这种高度错误的情况

**Comment by yezhonghu0503** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/61587068/683ee477-3178-47aa-ab5f-359b492fccf7)
