### ISSUE TITLE
InputItem组件能够添加一个属性来改变value的对齐方式？

### ISSUE THREAD

**Issue by ml1314** [ant-design/ant-design-mobile#664]
#### 本地环境

- antd-mobile 版本：1.0.0
- 浏览器 (或标明是 react-native) 及其版本：0.39
- 运行环境及其版本：android or ios

#### 你做了什么？
在InputItem组件添加一个属性用于设置组件value的对齐方式（可以像DatePicker右对齐）
![qq 20161220174947](https://cloud.githubusercontent.com/assets/23412577/21381554/f2c6a23a-c796-11e6-8791-008ee0431cdf.png)；
还有placeholder的字体样式，value的样式（如：字体颜色）

**Comment by afc163** [comment]
你这样简约的提问，别人如何能知道需求是什么？

**Comment by warmhug** [comment]
InputItem 的 placeholder和value 一般都是左对齐，包括 label 文字也是。组件只覆盖通常的使用方式，而且已经有很多配置项，有特殊的展现自己写 css 覆盖
