### ISSUE TITLE
h5页面使用ImageUploader安卓上传直接进入文件夹，不能使用相机拍照，ios可以

### ISSUE THREAD

**Issue by LMLGM** [ant-design/ant-design-mobile#6641]
### Version of antd-mobile

5.36.0

### Description

![image](https://github.com/ant-design/ant-design-mobile/assets/58587791/29dd6138-87f9-436e-9180-092fdaf37533)
![image](https://github.com/ant-design/ant-design-mobile/assets/58587791/0b65b4a1-2def-4a39-9689-b22594e34536)

https://github.com/ant-design/ant-design-mobile/assets/58587791/c19cd577-6456-4e39-817f-5d5d70632123

https://github.com/ant-design/ant-design-mobile/assets/58587791/e787b5d0-f39f-496d-9aab-7f45671eba83

**Comment by liqiuqiui** [comment]
我刚试了下官网demo，是可以选择用相机拍照还是现有图片的，大概率是你的设备的问题，我的手机是小米

**Comment by LMLGM** [comment]
定位到是容器问题，容器不支持

**Comment by HaRries07** [comment]
这个问题我也遇到了，大佬，你解决了吗，教教我
