### ISSUE TITLE
含泪跪求大佬们, 请支持flutter

### ISSUE THREAD

**Issue by gailiuziaa007** [ant-design/ant-design-mobile#6642]
### What is this feature about?

请出flutter版本, 跪求

**Comment by zombieJ** [comment]
感谢反馈，但是精力有限。暂时没有计划支持 flutter 哈。

**Comment by fengxiaotx** [comment]
antd 风格的 flutter 组件库 https://github.com/trionesdev/triones-antd-mobile-flutter
