### ISSUE TITLE
能否增加顶部提示： Notify 消息通知

### ISSUE THREAD

**Issue by arlin123** [ant-design/ant-design-mobile#6648]
### What is this feature about?

能否增加顶部提示： Notify 消息通知

**Comment by afc163** [comment]
https://mobile.ant.design/zh/components/toast 里可以设置顶部弹出。

**Comment by arlin123** [comment]
https://vant-ui.github.io/vant/#/zh-CN/notify
![07d429c7-cd3c-4e5c-a64f-a61169d73840](https://github.com/ant-design/ant-design-mobile/assets/12249165/447a1315-6b19-4ad1-ad22-b257558cb6b5)
