### ISSUE TITLE
CalendarPicker未设置最小日期的情况不能选择当前月份之前的日期，设置了最小值的情况，并且设置了默认日期，打开显示了最小日期的最小月份

### ISSUE THREAD

**Issue by stovd2** [ant-design/ant-design-mobile#6654]
### Version of antd-mobile

5.36.0

### Operating system and its version

Others

### Browser and its version

Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1

### Sandbox to reproduce

https://codesandbox.io/p/sandbox/upbeat-lena-kxs7fs?file=%2Fsrc%2FApp.tsx%3A4%2C1

### What happened?

我希望日历面板默认显示在当前月份的日期，上下滚动可以选择以设置的最小日期之后的日期

**Comment by zombieJ** [comment]
没开 public：
<img width="721" alt="截屏2024-07-02 10 51 18" src="https://github.com/ant-design/ant-design-mobile/assets/5378891/d5c7f34f-59fd-4edb-a078-4f2c8fd5cfc1">

**Comment by harity** [comment]
https://codesandbox.io/p/devbox/intelligent-lucy-sxydt6?file=%2Fsrc%2FApp.js%3A22%2C29
ref 里面的几个方法也是不生效，比如jumpToToday，demo 里有，
