### ISSUE TITLE
tsx separated from demo markdown

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#666]
like  https://github.com/ant-design/ant-design-mobile/blob/master/components/button/demo/complex.md

to check whether component's tsx is correct

change
```
import { Button, List } from 'antd-mobile';
```

to

```
import { Button, List } from '../../';
```

need @benjycui to change bisheng

@ant-design/ant-design-team

**Comment by warmhug** [comment]
ref  #636

**Comment by afc163** [comment]
typescript 有没有 resolve 的配置？

**Comment by benjycui** [comment]
把这个 feature https://github.com/benjycui/bisheng/issues/63 完成后，demo 的格式或者可以改成下面这样？

```tsx
demo
  .meta({ ... })
  .intro({
    'zh-CN': `
Markdown syntax
`,
    'en-US': `
Markdown syntax
`
  })
  .code(() => {
    // tsx goes here
  })
  .style(`

  `)
```

还是说希望继续在 Markdown 里面写？

**Comment by paranoidjk** [comment]
Markdown +1

**Comment by paranoidjk** [comment]
discuss demo syntax at  https://github.com/ant-design/ant-design/issues/5390

close this for no more further activity.
