### ISSUE TITLE
安全漏洞

### ISSUE THREAD

**Issue by canyueduhong** [ant-design/ant-design-mobile#6668]
### Version of antd-mobile

5.37.1

### Operating system and its version

Others

### Browser and its version

服务器插件漏洞

### What happened?

我们的安全团队扫描发现了一个关于 intersection-observer 0.12.2插件存在木马的问题。然而，根据我们查看 intersection-observer 的官方信息，并没有发现可用的更新版本进行升级。请问是否有替换这个插件的方案，或者其他的解决方法？

期待您的回复。

**Comment by canyueduhong** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/28993317/ba363328-7c2d-41fe-9933-17ee06fc2f96)

**Comment by zombieJ** [comment]
看了一下没有相关的报告，推测是 [test.html](https://unpkg.alipay.com/browse/intersection-observer@0.12.2/intersection-observer-test.html) 误触发了 `polyfill.io` 安全警告，可以再确认一下：

ref: https://security.snyk.io/package/npm/intersection-observer

**Comment by canyueduhong** [comment]
你的意思是说/node_modules/intersection-observer-test.html文件里的https://cdn.polyfill.io/v2/polyfill.min.js?features=es5,getComputedStyle链接误触发了安全警告导致的吗？
可是我们的安全团队不认可该解释，麻烦问下假如我尝试在package.lock.json中去掉这个插件，会导致ant-mobile除了ahooks相关的组建失效，或者其它影响吗？

**Comment by canyueduhong** [comment]
搜索了下居然能搜到相关新闻（手动捂脸哭）😭
https://baijiahao.baidu.com/s?id=1803720749750686030&wfr=spider&for=pc

**Comment by zombieJ** [comment]
可以考虑自己发一个包，然后 npm 里 override 成自己的试试。这个包是 google 的，本身是没啥问题的。 issue 这边就先关了哈~

**Comment by canyueduhong** [comment]
好的，感谢
