### ISSUE TITLE
tsx props声明错误汇总

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#667]
* `DataPicker`: 
    * `defaultDate`非必须，缺少`onChange`

**Comment by afc163** [comment]
另外为啥是 value 和 defaultDate，这样不是很配对。

https://github.com/react-component/m-date-picker 里是 date 和 defaultDate。

**Comment by pingan1927** [comment]
* `Picker`
  * `children`  不需要专门声明，现在报错

**Comment by pingan1927** [comment]
* `maxLength`
  * 缺少`maxLength`

**Comment by pingan1927** [comment]
* `List.Item`
  * `align`属性类型要是可枚举的，而不是字符串

**Comment by pingan1927** [comment]
* `Flex`整个声明文件需要重新整理

**Comment by pingan1927** [comment]
* `Tabs`中的`TabPane`声明出错

**Comment by bccsafe** [comment]
* TabBar
缺少TabBar.Item声明

**Comment by paranoidjk** [comment]
@silentcloud 

`TabBar.Item` 的类型声明好像的确有问题，我这边测试没生效;

参见[这里]( https://github.com/ant-design/ant-design-mobile/blob/master/components/tab-bar/index.web.tsx#L19) ，下面实际是取 `this.props.children`  渲染到`Tab`组件的，[这里](https://github.com/ant-design/ant-design-mobile/blob/master/components/tab-bar/index.web.tsx#L51)  给`Tab`加上类型应该ok

**Comment by silentcloud** [comment]
@paranoidjk ok 那你这边顺便改一下

**Comment by pingan1927** [comment]
`Modal`缺少`Modal.alert`等声明

**Comment by bccsafe** [comment]
* Tabs
缺少Tabs.TabPane声明

**Comment by bccsafe** [comment]
* Button
缺少className声明

**Comment by paranoidjk** [comment]
@bccsafe 来个PR？ 😄

**Comment by bccsafe** [comment]
@paranoidjk 好 😄
#792

**Comment by bccsafe** [comment]
* ListView
缺了很多声明
#807

**Comment by bccsafe** [comment]
* Picker
缺少disabled以及IPopupCascaderProps下的部分声明
#812

**Comment by paranoidjk** [comment]
close. 随时发现随时改

**Comment by MrKou47** [comment]
为什么最新的antd-mobile的tab 的声明文件还是没有定义tabpane？不是已经fix了 么

**Comment by paranoidjk** [comment]
@bccsafe would you like to fix `Tabs` tsx error? I remember yout last pr was closed because of refactor.

**Comment by bccsafe** [comment]
@paranoidjk 好 😃

**Comment by paranoidjk** [comment]
@bccsafe https://github.com/ant-design/ant-design-mobile/issues/1068

**Comment by MrKou47** [comment]
`SearchBar` 的 `defaultValue` 声明缺失

**Comment by bccsafe** [comment]
@MrKou47 fixed
#1106

**Comment by AliasT** [comment]
![2017-12-05 19 33 03](https://user-images.githubusercontent.com/8329204/33605159-73e430a2-d9f3-11e7-9113-257be6975238.png)

版本：2.1.0

**Comment by paranoidjk** [comment]
@AliasT 等待 https://github.com/ant-design/ant-design-mobile/issues/2147 完成。你可以临时关闭 noImplicitAny
