### ISSUE TITLE
5.30 以后，会报一个错误

### ISSUE THREAD

**Issue by smithyj** [ant-design/ant-design-mobile#6671]
### Version of antd-mobile

5.37.1

### Operating system and its version

iOS, Android, Others

### What happened?

调用了 TextArea 组件，然后页面会报错，错误如下：
45.js:425 Uncaught (in promise) 
TypeError: (0 , _runes.default) is not a function

跟踪到里面了，发现是由于 runes 换成了 runes2 导致的问题，runes2 这个包esm产物没有正确的 export default 
https://github.com/ant-design/ant-design-mobile/blob/c1958aadb91c4e0e8510e39dc4b8d5445d28bb85/src/components/text-area/text-area.tsx#L143

**Comment by bluelovers** [comment]
![image](https://github.com/ant-design/ant-design-mobile/assets/167966/900871f5-adcb-4b4a-b738-7bf88a085e60)

https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json

**Comment by smithyj** [comment]
解决了，项目中 webpack 不支持 mjs 产物
