### ISSUE TITLE
floating-panel 拖动到最高时，里面内容出现滚动条，滚动条滚到最底部时，在手机上，当我想往下滚动的时候，会出现直接收起floating-panel，而不是滚动我里面的内容

### ISSUE THREAD

**Issue by harity** [ant-design/ant-design-mobile#6672]
### Version of antd-mobile

5.37.1

### Browser and its version

IOS 17.2.1

### What happened?

电脑浏览器因为有鼠标滚轮或者笔记本的磁控版，内容可以正常上下滚动，只有在手机上才会有这个内容，所以无法提供一个 demo

**Comment by zombieJ** [comment]
我这边重现不出来，这个官方例子也有这个问题吗？  https://mobile.ant.design/~demos/floating-panel-demo1/

**Comment by harity** [comment]
这个 demo 我打不开，您是在手机看的吗，我在电脑上是可以的，只有在手机上是重现。

**Comment by harity** [comment]
是我们的问题，不好意思

**Comment by richardliu66** [comment]
你好我们也碰到了这个问题，请问这个问题你们解决了吗？

**Comment by harity** [comment]
我记得当时好像是我给里面的 div 加了overflow：auto 导致的，但是时间有点久了，记不清楚了，确实我当时自己的问题导致的
