### ISSUE TITLE
常驻提示noticebar 滚动时很模糊

### ISSUE THREAD

**Issue by likeechizenbest** [ant-design/ant-design-mobile#6682]
### Version of antd-mobile

官网示例

### What is this feature about?

![飞书20240725-190124](https://github.com/user-attachments/assets/48e02ba4-0527-4182-b0bf-d8f974ec77ba)

**Comment by zombieJ** [comment]
这个设备的刷新率有关系，组件库做不了什么。你点击暂停会发现它是没有模糊的。
