### ISSUE TITLE
Form.Array组件删除表单项后onValuesChange拿到的allValues不是最新值

### ISSUE THREAD

**Issue by lcylamb** [ant-design/ant-design-mobile#6687]
### Version of antd-mobile

5.37.1

### Sandbox to reproduce

https://stackblitz.com/edit/react-3qvhsi?file=demo.tsx

### What happened?

![demo](https://github.com/user-attachments/assets/f4e8b4de-684e-48ce-a5b7-c9e12b133721)
在使用Form.Array组件时，添加表单项后（此时数组长度为2），再删除表单项，此时在onValuesChange回调中拿到的allValues不是最新值，期望拿到删除后的数组

**Comment by Layouwen** [comment]
> ### Version of antd-mobile
> 5.37.1
> 
> ### Operating system and its version
> _No response_
> 
> ### Browser and its version
> _No response_
> 
> ### Sandbox to reproduce
> https://stackblitz.com/edit/react-3qvhsi?file=demo.tsx
> 
> ### What happened?
> ![demo](https://private-user-images.githubusercontent.com/88578457/353748959-f4e8b4de-684e-48ce-a5b7-c9e12b133721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTQ4NDksIm5iZiI6MTcyMjQxNDU0OSwicGF0aCI6Ii84ODU3ODQ1Ny8zNTM3NDg5NTktZjRlOGI0ZGUtNjg0ZS00OGNlLWE1YjctYzllMTJiMTMzNzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA4MjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZjFiYTg4MjEwYjE0OWUzZTFlZjczZWE0NWQzMWQzMDNkZDJmYWFjYjQ0N2NiYTZjNjZiMTFhNzQwNjA3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IH1N5fzeUdOwhBZMyIh5K1neNlJy6vPYD-Wm18d-ga4) 在使用Form.Array组件时，添加表单项后（此时数组长度为2），再删除表单项，此时在onValuesChange回调中拿到的allValues不是最新值，期望拿到删除后的数组
> 
> ### Relevant log output
> _No response_

![image](https://github.com/user-attachments/assets/f378764e-1681-4592-9b88-6082bed5cd63)

复现地址是不是填错了, 打开跟上面内容不一样

**Comment by lcylamb** [comment]
> > ### Version of antd-mobile
> > 5.37.1
> > ### Operating system and its version
> > _No response_
> > ### Browser and its version
> > _No response_
> > ### Sandbox to reproduce
> > https://stackblitz.com/edit/react-3qvhsi?file=demo.tsx
> > ### What happened?
> > ![demo](https://private-user-images.githubusercontent.com/88578457/353748959-f4e8b4de-684e-48ce-a5b7-c9e12b133721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTQ4NDksIm5iZiI6MTcyMjQxNDU0OSwicGF0aCI6Ii84ODU3ODQ1Ny8zNTM3NDg5NTktZjRlOGI0ZGUtNjg0ZS00OGNlLWE1YjctYzllMTJiMTMzNzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA4MjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZjFiYTg4MjEwYjE0OWUzZTFlZjczZWE0NWQzMWQzMDNkZDJmYWFjYjQ0N2NiYTZjNjZiMTFhNzQwNjA3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IH1N5fzeUdOwhBZMyIh5K1neNlJy6vPYD-Wm18d-ga4) 在使用Form.Array组件时，添加表单项后（此时数组长度为2），再删除表单项，此时在onValuesChange回调中拿到的allValues不是最新值，期望拿到删除后的数组
> > ### Relevant log output
> > _No response_
> 
> ![image](https://private-user-images.githubusercontent.com/60692794/353756160-f378764e-1681-4592-9b88-6082bed5cd63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTg2ODgsIm5iZiI6MTcyMjQxODM4OCwicGF0aCI6Ii82MDY5Mjc5NC8zNTM3NTYxNjAtZjM3ODc2NGUtMTY4MS00NTkyLTliODgtNjA4MmJlZDVjZDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA5MzMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNDc2YWExZjJmMzgzOWZhN2FjNGE0NzkxN2MwM2E5ZGNhMTI5MGFlN2I0NWE3MDg2MTJjODNmMDMyMjExMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kx4Tbmrp16wCtN7ZS0CFURfpig7T9BR4Uwgz8cVs9YU)
> 
> 复现地址是不是填错了, 打开跟上面内容不一样

是的，不好意思我复制错了，这是正确的地址https://codesandbox.io/s/new-sound-wn93j9

**Comment by Layouwen** [comment]
> > > ### Version of antd-mobile
> > > 5.37.1
> > > ### Operating system and its version
> > > _No response_
> > > ### Browser and its version
> > > _No response_
> > > ### Sandbox to reproduce
> > > https://stackblitz.com/edit/react-3qvhsi?file=demo.tsx
> > > ### What happened?
> > > ![demo](https://private-user-images.githubusercontent.com/88578457/353748959-f4e8b4de-684e-48ce-a5b7-c9e12b133721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTQ4NDksIm5iZiI6MTcyMjQxNDU0OSwicGF0aCI6Ii84ODU3ODQ1Ny8zNTM3NDg5NTktZjRlOGI0ZGUtNjg0ZS00OGNlLWE1YjctYzllMTJiMTMzNzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA4MjkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZjFiYTg4MjEwYjE0OWUzZTFlZjczZWE0NWQzMWQzMDNkZDJmYWFjYjQ0N2NiYTZjNjZiMTFhNzQwNjA3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IH1N5fzeUdOwhBZMyIh5K1neNlJy6vPYD-Wm18d-ga4) 在使用Form.Array组件时，添加表单项后（此时数组长度为2），再删除表单项，此时在onValuesChange回调中拿到的allValues不是最新值，期望拿到删除后的数组
> > > ### Relevant log output
> > > _No response_
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/60692794/353756160-f378764e-1681-4592-9b88-6082bed5cd63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTg2ODgsIm5iZiI6MTcyMjQxODM4OCwicGF0aCI6Ii82MDY5Mjc5NC8zNTM3NTYxNjAtZjM3ODc2NGUtMTY4MS00NTkyLTliODgtNjA4MmJlZDVjZDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA5MzMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNDc2YWExZjJmMzgzOWZhN2FjNGE0NzkxN2MwM2E5ZGNhMTI5MGFlN2I0NWE3MDg2MTJjODNmMDMyMjExMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kx4Tbmrp16wCtN7ZS0CFURfpig7T9BR4Uwgz8cVs9YU)
> > 复现地址是不是填错了, 打开跟上面内容不一样
> 
> 是的，不好意思我复制错了，这是正确的地址https://codesandbox.io/s/new-sound-wn93j9

![image](https://github.com/user-attachments/assets/9611e3cc-62c5-41a6-8e1b-e17891808785)

你看看怎么调整复现步骤, 我这边看着似乎没什么问题

[https://codesandbox.io/p/sandbox/sweet-jepsen-jlgdwc](https://codesandbox.io/p/sandbox/sweet-jepsen-jlgdwc)

**Comment by lcylamb** [comment]
https://github.com/user-attachments/assets/b2423fa5-4631-4531-a35e-7e8ecdb5b0fc

可以查阅本视频

**Comment by Layouwen** [comment]
> 1722496965718.mp4 
> 可以查阅本视频

#6690 该问题已经修复了, 可以等后续发版后更新一下版本~

**Comment by lcylamb** [comment]
你好，请问什么时候新版本呀在 2024年8月1日，16:06，Avan ***@***.***> 写道：﻿

1722496965718.mp4
可以查阅本视频

#6690 该问题已经修复了, 可以等后续发版后更新一下版本~
