### ISSUE TITLE
Grid组件中icon设定

### ISSUE THREAD

**Issue by FOCUSWEB** [ant-design/ant-design-mobile#669]
环境：react-native+antd-mobile 1.0.0-alpha.33
`<Grid
          data={[
            {
              icon: <Image source={{uri:require('../images/airplane@3x.png')}}/>,
              text:'机票预订',
            },
          {
icon:'https://os.alipayobjects.com/rmsportal/IptWdCkrtkAUfjE.png',
text:'火车购票'
          },
          {
            icon:'https://os.alipayobjects.com/rmsportal/IptWdCkrtkAUfjE.png',
            text:'酒店预订',
          }]}
/>`

如上所示，data里面的icon属性能否直接使用本地图片，不用远程加载。

**Comment by warmhug** [comment]
可以的，下个版本支持
