### ISSUE TITLE
react-native-web 下使用 antd-mobile  有问题，无效果

### ISSUE THREAD

**Issue by flyjennyetn** [ant-design/ant-design-mobile#670]
react-native-web 下使用 antd-mobile  有问题，无效果

**Comment by warmhug** [comment]
描述遇到的具体问题

**Comment by flyjennyetn** [comment]
@warmhug  应该是冲突吧   react-native-web是支持web的    antd-mobile是支持 native   ，他们一起用相互有冲突

**Comment by warmhug** [comment]
有可能，建议只选一个
