### ISSUE TITLE
Carousel 图片和父元素之间有间隙 怎么解决？

### ISSUE THREAD

**Issue by onlyLiru** [ant-design/ant-design-mobile#672]
#### 本地环境

- antd-mobile 版本：
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：

#### 你做了什么？

class ImgScroll extends React.Component {
	constructor(props) {
		super(props);
		this.state = {

		};
	}
	render() {
		let imgHtml=this.props.data.map( (d,i)=> {
			return <div key={i} className="item">
				<a href={d.link}><img className="autoImg" src={d.img} /></a>
			</div>;
		} );
		return (<div>
			<Carousel className="my-carousel">
				{imgHtml}
			</Carousel>

		</div>)
	}
	componentWillMount() {
		
	}
};

其中数据源是:
banner:[
			{
				img:'http://img.fancyedu.com/sys/ic/operation/1482377088291_banner1.png',
				link:'lessonDetail'
			}
		]

#### 你期待的结果是：

轮播图片下沿与父元素无缝

#### 实际上的结果：

轮播图片下沿与父元素有大概6px对缝隙

**Comment by warmhug** [comment]
给出示例

**Comment by warmhug** [comment]
img 比较特殊，记得设置`vertical-align: top;` 来避免 offsetHeight 计算错误。
