### ISSUE TITLE
在 m1芯片  webview 里走马灯组件无法长按滚动到下一页

### ISSUE THREAD

**Issue by j-joker** [ant-design/ant-design-mobile#6722]
### Version of antd-mobile

5.37.1

### Operating system and its version

iOS

### What happened?

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/7e74e259-c3db-4124-8559-18384dce4421">

在m1 webview 里打开官网可以复现，无法长按触控板拖动到下一页

**Comment by zombieJ** [comment]
打开新窗口，然后开启移动模拟。antd mobile 的事件没有全部对 PC 做兼容哈~
