### ISSUE TITLE
聚焦input最右侧的内容时，光标被clear按钮遮挡

### ISSUE THREAD

**Issue by CoCoManYY** [ant-design/ant-design-mobile#6728]
### Version of antd-mobile

5.37.1

### Description

复现地址：https://codesandbox.io/p/sandbox/youthful-hill-9y4k3f?file=%2Fapp.tsx%3A3%2C42
复现视频：
![20240827155759_rec_](https://github.com/user-attachments/assets/fb637f49-222e-4765-bdbd-8c13745aaf81)

**Comment by Layouwen** [comment]
看了一下这个不是遮挡, 只是没滚动到底部. 你 focus 后, input 是可以移动到最后字符的位置的.

**Comment by CoCoManYY** [comment]
嗯嗯是的，光标没在视图里，滚动到后面了。这种情况下有考虑自动把光标移动到可视范围吗？

**Comment by Layouwen** [comment]
> 嗯嗯是的，光标没在视图里，滚动到后面了。这种情况下有考虑自动把光标移动到可视范围吗？

好像不太好设计这个交互。有时候用户就是要编辑前面的内容，自动滚动最后会很别扭
