### ISSUE TITLE
carousel 高度不正确

### ISSUE THREAD

**Issue by wcdhm** [ant-design/ant-design-mobile#673]
#### 本地环境

- antd-mobile 版本： 1.0
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：

#### 你做了什么？
引入carousel

#### 你期待的结果是：
![2](https://cloud.githubusercontent.com/assets/24520863/21448166/77e8fa38-c91a-11e6-9ec1-7162636d4357.png)

#### 实际上的结果：
![1](https://cloud.githubusercontent.com/assets/24520863/21448170/80dd2312-c91a-11e6-865b-5cb619d6a083.png)

当翻自动切换到第二个对象时，高度恢复正常

**Comment by silentcloud** [comment]
RN 的 Carousel 需要子 view 高度一致 @wcdhm ，最好是给内层子 view 设置高度

**Comment by warmhug** [comment]
web 版也是要设置高度，demo 已更新、可以参考。

**Comment by xiaozhouwu** [comment]
请问最后你们是怎么解决这个问题了？
