### ISSUE TITLE
Popover 打开时即使数据没有任何变化，content也会重新渲染

### ISSUE THREAD

**Issue by Parmerlee** [ant-design/ant-design-mobile#6742]
### Version of antd-mobile

5.37.1

### Operating system and its version

iOS, Android, Others

### Browser and its version

所有手机上均不生效

### What happened?

![Uploading image.png…]()

即使加上memo的第二个参数也不行。

**Comment by Parmerlee** [comment]
![Uploading image.png…]()

**Comment by Layouwen** [comment]
#6743 重复
