### ISSUE TITLE
文本省略组件存在失效bug

### ISSUE THREAD

**Issue by Wu-hj** [ant-design/ant-design-mobile#6748]
### Version of antd-mobile

5.37.1

### Operating system and its version

Others

### Sandbox to reproduce

https://stackblitz.com/edit/antd-mobile-r2huqf?file=index.tsx

### What happened?

当传入的content为中文时文本省略生效，当传入的content为英文单词或者字符串类型的数字文本时，文本省略失效

**Comment by 2020191543223** [comment]
Ellipsis 组件内部会读取 word-break 这个 CSS 属性的值，如果未设置该样式属性的值，默认值为：normal。所以，当文本内容中包含大量数字或英文时，文本内容无法省略（浏览器的默认行为）。此时，如果需要让文本省略生效，可以手动在 Ellipsis 组件或其外层元素中，添加 word-break 样式（比如，word-break: break-word），Ellipsis 组件会完全遵循样式继承行为，拿到你设置的 word-break，从而实现自动省略。
