### ISSUE TITLE
经过mini-css-extract-plugin后css命中错误

### ISSUE THREAD

**Issue by Songkunda** [ant-design/ant-design-mobile#6749]
### Version of antd-mobile

5.37.1

### What happened?

tabbar设置badge后,在通过webpack mini-css-extract-plugin后css样式压缩,且声明顺序被改变,导致开发环境与生产环境样式显示不一致.
开发模式:  ![正常样式/开发模式下](https://github.com/user-attachments/assets/9fbf2979-580f-42aa-8c08-d03f7a30d29f)
打包后:  ![打包后](https://github.com/user-attachments/assets/80d86a55-9087-4353-bef0-44a1dac548ed)
重现请见[dome.zip REAME](https://github.com/user-attachments/files/17175584/demo.zip)

**Comment by Layouwen** [comment]
如果确定压缩前是正常的, 压缩后 mini-css-extract-plugin 编译逻辑造成的不一致, 建议去该插件的仓库提个 issue 可能解决速度会快一点
