### ISSUE TITLE
FloatingPanel的header和content之间有间隙

### ISSUE THREAD

**Issue by KilianShen** [ant-design/ant-design-mobile#6751]
### Version of antd-mobile

5.37.1

### Operating system and its version

Others

### Browser and its version

edge 129.0.2792.65

### Sandbox to reproduce

https://codesandbox.io/p/sandbox/d97mqk

### What happened?

浮动面板的header和content之间有间隙
![image](https://github.com/user-attachments/assets/98c48347-c718-418e-bb9f-0f2f47bfa70d)

**Comment by Layouwen** [comment]
![image](https://github.com/user-attachments/assets/88c7282b-5ac4-4678-a3ea-54353e8b9dc2)
你是指这块缝隙吗?
这块是你用了 h1 标签. 它的样式撑开的, 你可以重写一下 h1 样式或者换其他标签试试
