### ISSUE TITLE
should revert - fix(Popup): set pointer-events none while animating

### ISSUE THREAD

**Issue by ekko2665** [ant-design/ant-design-mobile#6754]
### Version of antd-mobile

5.37.1

### Operating system and its version

iOS, Others

### Browser and its version

eg.IOS Safari 13.1

### Sandbox to reproduce

https://github.com/ant-design/ant-design-mobile/pull/6416

### What happened?

class name of adm-popup-body, will had a style pointer-events: none,  then u can't click content。
why can not ？ when user  click something animation not end , and there is no action ,  they will think something wrong 

### Relevant log output

```shell
class name of adm-popup-body, will had a style pointer-events: none,  then u can't click content。
why can not ？ when user  click something animation not end , and there is no action ,  they will think something wrong
```

**Comment by zombieJ** [comment]
It's by design since some old mobile device user may miss touch the content when animating. Consider user may not keep updating device, we may keep the prevent events. If you are sure not need this, you can:

```css
.adm-popup-body {
  pointer-events: unset !important;
}
```

**Comment by liangskyli** [comment]
This should not be rolled back, not just this component.
In addition to the style rewriting scheme mentioned above, there is another option to remove the animation，See [reduce-motion](https://mobile.ant.design/guide/reduce-motion/)
```
import { reduceMotion } from 'antd-mobile'

reduceMotion()
```

**Comment by ekko2665** [comment]
> It's by design since some old mobile device user may miss touch the content when animating. Consider user may not keep updating device, we may keep the prevent events. If you are sure not need this, you can:
> 
> ```
> .adm-popup-body {
>   pointer-events: unset !important;
> }
> ```

dropdown also will happen this problem?
