### ISSUE TITLE
DatePicker组件给了max属性会导致ios环境下年份不显示问题 年限的部分dom消失

### ISSUE THREAD

**Issue by LvZhenXiang** [ant-design/ant-design-mobile#6756]
### Version of antd-mobile

5.37.1

### Operating system and its version

iOS

### Sandbox to reproduce

https://codesandbox.io/p/sandbox/solitary-fast-j3d58w?workspaceId=79a15877-e219-4681-94f4-0b01786add99

### What happened?

![微信图片_20241009142233](https://github.com/user-attachments/assets/b6f672aa-7d8b-4f5f-a9b3-188f354933fe)

**Comment by LvZhenXiang** [comment]
> Hi, LvZhenXiang.
> 
> Please provide a online reproduction so that we can help you troubleshoot the problem. You can create a demo by [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) or [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx).
> 
> 我们需要你提供一个在线的重现实例，以便于我们帮你排查问题。你可以通过 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx) 创建一个实例。

在ios环境下可复现
https://codesandbox.io/p/sandbox/solitary-fast-j3d58w?workspaceId=79a15877-e219-4681-94f4-0b01786add99

**Comment by Layouwen** [comment]
> > Hi, LvZhenXiang.
> 
> > 
> 
> > Please provide a online reproduction so that we can help you troubleshoot the problem. You can create a demo by [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) or [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx).
> 
> > 
> 
> > 我们需要你提供一个在线的重现实例，以便于我们帮你排查问题。你可以通过 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx) 创建一个实例。
> 
> 
> 
> 在ios环境下可复现
> 
> https://codesandbox.io/p/sandbox/solitary-fast-j3d58w?workspaceId=79a15877-e219-4681-94f4-0b01786add99

链接 not found 了

**Comment by LvZhenXiang** [comment]
> > > Hi, LvZhenXiang.
> > 
> > 
> > > 
> > 
> > 
> > > Please provide a online reproduction so that we can help you troubleshoot the problem. You can create a demo by [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) or [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx).
> > 
> > 
> > > 
> > 
> > 
> > > 我们需要你提供一个在线的重现实例，以便于我们帮你排查问题。你可以通过 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx) 创建一个实例。
> > 
> > 
> > 在ios环境下可复现
> > https://codesandbox.io/p/sandbox/solitary-fast-j3d58w?workspaceId=79a15877-e219-4681-94f4-0b01786add99
> 
> 链接 not found 了

实例忘记public了 现在可以了

**Comment by Layouwen** [comment]
> > > > Hi, LvZhenXiang.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Please provide a online reproduction so that we can help you troubleshoot the problem. You can create a demo by [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) or [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx).
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 我们需要你提供一个在线的重现实例，以便于我们帮你排查问题。你可以通过 [codesandbox](https://codesandbox.io/s/antd-mobile-snrxr?file=/package.json) 或 [stackblitz](https://stackblitz.com/edit/antd-mobile?file=index.tsx) 创建一个实例。
> > > 
> > > 
> > > 在ios环境下可复现
> > > https://codesandbox.io/p/sandbox/solitary-fast-j3d58w?workspaceId=79a15877-e219-4681-94f4-0b01786add99
> > 
> > 
> > 链接 not found 了
> 
> 实例忘记public了 现在可以了

手机端 Date 解析跟 pc 有点区别, 字符串格式, 需要按标准格式写 'xxxx-xx-xx' 现在 'xxxx-x-x' 会解析为无效时间
或者你可以使用 `new Date(2100, 1, 1, 0, 0, 0)`
