### ISSUE TITLE
虚拟输入框，无法输入内容

### ISSUE THREAD

**Issue by nuonuonuonuoyan** [ant-design/ant-design-mobile#6758]
### Version of antd-mobile

5.37.1

### Operating system and its version

Others

### Browser and its version

官网组件示例

### Sandbox to reproduce

https://mobile.ant.design/zh/components/passcode-input

### What happened?

点击虚拟键盘，无法键入任何内容

**Comment by zombieJ** [comment]
用移动模拟访问哈：

https://mobile.ant.design/~demos/passcode-input-demo1/

<img width="117" alt="截屏2024-10-12 10 52 07" src="https://github.com/user-attachments/assets/015036ac-9898-423f-a4da-9a996ccee248">
