### ISSUE TITLE
ReactRouter切换,如何加入过场动画?

### ISSUE THREAD

**Issue by AdamChrist** [ant-design/ant-design-mobile#677]
RT,在不同页面切换.如何加入动画?
求指导.
尝试过:[http://react-component.github.io/queue-anim/examples/router.html](url)
但是在第一个TabBar的页面布局就乱了...

**Comment by AdamChrist** [comment]
研究了一下 rc-queue-anim 在父元素增加的transform属性，会导致子元素的fixed失效。而且也没有什么解决办法..

**Comment by jljsj33** [comment]
动画结束后把 transform 设回 none 就可以了

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/issues/3088

**Comment by AdamChrist** [comment]
@jljsj33  谢谢.把动画加入到TabBar中去渲染了..
在动画过程中 还是会影响Fixed的元素.看来不是很友好.

**Comment by silentcloud** [comment]
具体是什么样的过渡动画？类似 Tabs 切换的动画效果？

**Comment by AdamChrist** [comment]
@silentcloud 差不多..就是手机APP中页面切换是有过渡效果的..

**Comment by warmhug** [comment]
点击 tabbar 切换，然后让页面有转场动画，这种貌似不是很常见、而且在移动端问题可能会很多，建议换成其他交互方式。。先关闭，若有问题再打开讨论。

**Comment by AdamChrist** [comment]
@warmhug 不是tab切换的动画..是不同页面之间的切换
