### ISSUE TITLE
Slider组件h5页面，在海外某些机型上面直接白屏

### ISSUE THREAD

**Issue by object-li** [ant-design/ant-design-mobile#6788]
### Version of antd-mobile

5.38.0

### Operating system and its version

Android

### Sandbox to reproduce

直接使用Slider

**Comment by zombieJ** [comment]
感谢反馈，但是这么描述过于语焉不详。这边也没有办法来排查问题，这里就先关了。欢迎提供更详细的信息再开 issue 哈~
