### ISSUE TITLE
放开或放宽对依赖版本的限制

### ISSUE THREAD

**Issue by pfdgithub** [ant-design/ant-design-mobile#679]
ant-design-mobile 对于自己的依赖限制的很紧，很多都限制在小版本范围内。  
很多依赖都已经更新了大版本，默认情况下新建的项目都是使用最新版本，且限制依赖在大版本范围内。  
比如 "normalize.css": "~4.2.0" 现在最新的是 "normalize.css": "^5.0.0" ，构建后的代码依赖同一库的不同版本，除非将项目依赖降级为同一版本。

**Comment by warmhug** [comment]
感谢建议，对于第三方依赖、后续改为 ^

**Comment by pfdgithub** [comment]
你还真只改一个啊，还有很多依赖也是这样，希望能尽量放开限制。  

"array-tree-filter": "~1.0.0",  
"babel-runtime": "6.x",  
"classnames": "~2.2.1",  
"css-vendor": "~0.3.4",  
"moment": "~2.15.1",  
"normalize.css": "~4.2.0",  
"nuka-carousel": "~2.0.3",  
"object-assign": "~4.1.0",  
"omit.js": "~0.1.0",  
"rc-checkbox": "~1.4.1",  
"rc-collapse": "~1.6.6",  
"rc-dialog": "~6.5.0",  
"rc-drawer": "~0.4.8",  
"rc-input-number": "~2.7.0",  
"rc-notification": "~1.3.5",  
"rc-slider": "~4.0.1",  
"rc-steps": "~2.2.0",  
"rc-swipeout": "~1.1.5",  
"rc-table": "~4.6.0",  
"rc-tabs": "7.0.x",  
"rc-tooltip": "~3.4.2",  
"rc-touchable": "~1.0.8",  
"react-hammerjs": "^0.5.0",  
"react-native-camera-roll-picker": "~1.1.6",  
"react-native-drawer-layout": "~1.0.0",  
"react-native-menu": "~0.20.1",  
"react-native-scrollable-tab-view": "^0.6.0",  
"react-timer-mixin": "~0.13.3",  
"rmc-cascader": "3.0.x",  
"rmc-date-picker": "5.0.x",  
"rmc-list-view": "~0.7.0",  
"rmc-picker": "3.4.x",  
"rn-topview": "^0.1.0",  
"zscroller": "~0.2.2"

**Comment by warmhug** [comment]
这些现在不能放开
