### ISSUE TITLE
Popover 内容高度变化时，无法重新定位

### ISSUE THREAD

**Issue by guoyunhe** [ant-design/ant-design-mobile#6794]
### Version of antd-mobile

5.38.1

### Operating system and its version

Android

### Browser and its version

15

### Sandbox to reproduce

https://codesandbox.io/p/sandbox/fervent-darwin-gj2x7v

### What happened?

Popover 内容为异步加载，即在展开之后高度会发生变化，这时 Popover 的气泡并不会动态调整位置，导致错位

![image](https://github.com/user-attachments/assets/06074297-ce4e-4b5c-a372-edd0857bbeb9)

![image](https://github.com/user-attachments/assets/1a9315de-875b-4d6f-a83e-3aefeff4b789)

**Comment by zombieJ** [comment]
感觉加个 ResizeObserver 能解，不过移动端上比较关注性能，是不是应该做一个开关来支持？

**Comment by guoyunhe** [comment]
@zombieJ 底层的 @floating-ui/dom 是支持 ResizeObserver 动态检测大小变化的，我测试它的例子是生效的 https://codesandbox.io/p/sandbox/elegant-goodall-m72vgy 但是不知道为什么到了 antd-mobile 里没有生效，不只是大小变化没有更新，滚动页面也没有更新。怀疑是这段代码逻辑没有生效：

https://github.com/ant-design/ant-design-mobile/blob/c75f300e6d19174796444de7e9d2a261f28c7f10/src/components/popover/popover.tsx#L188
