### ISSUE TITLE
List.Item hover效果优化

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#68]
通过监听`onClick`事件，设置`state.hover`，react频繁报错。移除。
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ListItem component.`

**Comment by pingan1927** [comment]
#72

**Comment by afc163** [comment]
用样式来实现按下效果。

**Comment by pingan1927** [comment]
`用样式来实现`，之前研究过好几次。尝试过，效果不好。

**Comment by afc163** [comment]
https://github.com/nolimits4web/Framework7/blob/a18dd955aa78461336535177845fb1ed0907c05f/src/js/fast-clicks.js

https://github.com/nolimits4web/Framework7/blob/master/src/less/ios/lists.less#L139

感觉可以写个工具组件来管这个事，framework7 也是多管齐下。

**Comment by afc163** [comment]
还真有：

https://github.com/JedWatson/react-tappable

https://github.com/zilverline/react-tap-event-plugin

**Comment by pingan1927** [comment]
`tappable`这种组件随着浏览器升级慢慢就会过时，之前我加过， @yiminghe 明确不要用。又移除了，移动端UI组件尽量少依赖，最后构建的文件要尽可能小！

我的实现就是参照framework7来搞的，就一个hover的改变，而且我们是react组件，没必要搞那么复杂！

**Comment by afc163** [comment]
就是每个组件里都要写，比较麻烦。提成一个 Tap 高阶组件，方便其他组件使用。

**Comment by yiminghe** [comment]
这个应该 touchstart hover true touchend hover false

**Comment by pingan1927** [comment]
> 这个应该 touchstart hover true touchend hover false

还有个touchCancel hover false。

@afc163 其他组件用&:active 貌似没的问题
