### ISSUE TITLE
日期范围选择

### ISSUE THREAD

**Issue by kavilee** [ant-design/ant-design-mobile#6803]
### Version of antd-mobile

5.38.1

### Description

![image](https://github.com/user-attachments/assets/b95a6856-1ec5-4fd7-9711-aa3d97509f5b)
设计同学在官网下载的设计资源里的日期范围选择组件在组件列表里找不到

**Comment by zombieJ** [comment]
范围选择器是通过 PickerView 和 Input 组合而出的，不是一个现成组件哈：

ref https://mobile.ant.design/zh/components/picker-view#datepickerview
