### ISSUE TITLE
DatePicker选择周日期Bug

### ISSUE THREAD

**Issue by bgyl99999** [ant-design/ant-design-mobile#6807]
### Version of antd-mobile

5.38.1

### Operating system and its version

Others

### Browser and its version

官网

### Sandbox to reproduce

https://mobile.ant.design/zh/components/picker#datepicker

### What happened?

https://github.com/user-attachments/assets/80f2f2e4-5e27-43ec-9c6b-14ac4982d5f3

日期处理从2024年开始就对不上了，选中的和展示的对不上

**Comment by bgyl99999** [comment]
https://github.com/user-attachments/assets/bcf3ecec-0240-412b-871d-892c960fe366

19年的处理也有问题

**Comment by zombieJ** [comment]
嗯，周的年月和普通日期的年月是不一样的，这里的确有问题。

**Comment by bgyl99999** [comment]
> 嗯，周的年月和普通日期的年月是不一样的，这里的确有问题。

下个小版本能带上这个修复吗

**Comment by zombieJ** [comment]
不太好修，dayjs 少一个填年的方法，目前是自行实现导致一些边界情况。
