### ISSUE TITLE
Modal组件

### ISSUE THREAD

**Issue by Sdoy** [ant-design/ant-design-mobile#681]
https://mobile.ant.design/components/modal/

Modal组件的closable属性,文档描述错误?-是否显示右上角的关闭按钮,实际是UI显示的是左上角的关闭按钮

建议:添加 x按钮的位置选择,左边还是右边.

workaround:.am-modal-close{right:0.3rem}

**Comment by Sdoy** [comment]
Modal的maskClosable属性,在chrome下,版本 55.0.2883.95,非调试模式下,点击蒙版可以隐藏,在调试模式下点击蒙版没有反应
https://codepen.io/SDOY000/pen/QGXvbJ

**Comment by silentcloud** [comment]
测试无问题，建议先把官方 demo 写进代码做测试试试；issue 先关了，若还有问题，麻烦回复 & reopen

![test](https://cloud.githubusercontent.com/assets/1698185/21513669/570366a2-ccf6-11e6-96a6-b42edc79437b.gif)

**Comment by warmhug** [comment]
> x按钮的位置选择,左边还是右边.

业务里自己覆盖。 

文档描述将会把 「右上角」几个字去掉
