### ISSUE TITLE
<Tag>只读标签貌似没有啊

### ISSUE THREAD

**Issue by wongben** [ant-design/ant-design-mobile#682]
> 说明文档里标签类型分为选择型标签和只读型标签，只读型标签无交互过程，仅展示内容。

**Comment by silentcloud** [comment]
![image](https://cloud.githubusercontent.com/assets/1698185/21513455/b92c23ee-ccf3-11e6-85c5-100baf6f22d4.png)

目前来自设计师的需求只读标签只存在于小号标签，你可以使用1.0-alpha
