### ISSUE TITLE
3x高清方案在 iPhone Plus 系列显示的问题

### ISSUE THREAD

**Issue by u0x01** [ant-design/ant-design-mobile#683]
- antd-mobile 版本：0.9.13
- 浏览器 (或标明是 react-native) 及其版本：iOS Safari / Chrome
- 运行环境及其版本：

我参照 [antd mobile 0.8 以上版本「高清」方案设置](https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE) 的

    !function(e){function t(a){if(i[a])return i[a].exports;var n=i[a]={exports:{},id:a,loaded:!1};return e[a].call(n.exports,n,n.exports,t),n.loaded=!0,n.exports}var i={};return t.m=e,t.c=i,t.p="",t(0)}([function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var i=window;t["default"]=i.flex=function(e,t){var a=e||100,n=t||1,r=i.document,o=navigator.userAgent,d=o.match(/Android[\S\s]+AppleWebkit\/(\d{3})/i),l=o.match(/U3\/((\d+|\.){5,})/i),c=l&&parseInt(l[1].split(".").join(""),10)>=80,p=navigator.appVersion.match(/(iphone|ipad|ipod)/gi),s=i.devicePixelRatio||1;p||d&&d[1]>534||c||(s=1);var u=1/s,m=r.querySelector('meta[name="viewport"]');m||(m=r.createElement("meta"),m.setAttribute("name","viewport"),r.head.appendChild(m)),m.setAttribute("content","width=device-width,user-scalable=no,initial-scale="+u+",maximum-scale="+u+",minimum-scale="+u),r.documentElement.style.fontSize=a/2*s*n+"px"},e.exports=t["default"]}]);
    flex(100, 1);

设置 Viewport，在 iPhone 7 Plus 上确实实现了 0.33333 这样的比例，但是浏览器似乎是按照 2x 进行渲染的，于是出现了下面的效果：

![image](https://cloud.githubusercontent.com/assets/9703404/21501026/51078908-cc7f-11e6-91f5-edebb69f9e43.PNG)

如果scale设置为 0.5   则正常，相关的讨论可以参见：https://github.com/amfe/lib-flexible/issues/32

因此应该加上这个判断：

    if (isIos && dpr == 3 ) {
      // 如果为 iOS, 按 2x 处理，dpr 设为 2;
      dpr = 2;
    }

**Comment by silentcloud** [comment]
![img_2244](https://cloud.githubusercontent.com/assets/1698185/21513434/734c09fc-ccf3-11e6-8229-0bbc66ed901f.PNG)

我这里用 0.9.13 测试没问题

**Comment by warmhug** [comment]
antd-mobile 的高清脚本，和 https://github.com/amfe/lib-flexible/blob/afd83fad831e43d759c24fe8fe9bdd7ca6acefee/src/flexible.js#L69 这里的不太一样，比如这段 
![image](https://cloud.githubusercontent.com/assets/2011119/21609302/9b53bbbc-d1fc-11e6-99bb-d7144ce6e0b3.png)
会使得同为 3x 屏的不同设备点数的设备，会计算出不同的结果，设置不同的 html fontSize 作为 rem 基准。在 6plus / 7plus / 3x安卓设备上的结果可能都不同。但 antd-mobile 脚本计算出的结果应该是都一样。 不同做法、感觉各有优劣。

**Comment by wangcongyi** [comment]
@warmhug  最近的项目上   正好两种方案都使用了下 
 antd-mobile的方案 在iphone5 和iphone6上都 把基准值 设置为100px （还是我要另外写配置？）
所以我觉得flexible的方案比较好
