### ISSUE TITLE
unable resolve module ant-mobile/lib/notice-bar/style/css

### ISSUE THREAD

**Issue by cooperding** [ant-design/ant-design-mobile#684]
#### 本地环境
使用react-native-cli命令，构建的项目。此项目是ios、安卓应用。

- antd-mobile 版本：0.9.13
- 浏览器 (或标明是 react-native) 及其版本：0.39
已设置

"plugins": [
    [
      "import", {"style": "css","libraryName": "antd-mobile"}
    ]
  ]

问题1、如何配置resolve？
问题2、import {NoticeBar} from 'antd-mobile';这种方式引入，提示错误：unable resolve module ant-mobile/lib/notice-bar/style/css.
如果使用import NoticeBar from 'antd-mobile/lib/notice-bar/index';测运行正常。
建议官方构建工具不要那么复杂，既然是以UI为主，仅可以基于react生态系统构建简单的配置。antd-mobile拆分为H5,和mobile（ios+安卓）。方便开发。

**Comment by silentcloud** [comment]
步骤：

1. react-native init 
2. npm install antd-mobile@xxx -S
3. npm install babel-plugin-import -SD
4. add `"plugins": [["import", { "libraryName": "antd-mobile" }]]` to `.babelrc` file
