### ISSUE TITLE
antd-mobile的InputItem的clear  那个圆叉  在iphone5下面特别难点到

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#685]
来自使用者反馈，特此记录

**Comment by pingan1927** [comment]
我cc

**Comment by warmhug** [comment]
统一 review 下其他组件是否也存在类似情况，都要改下

**Comment by silentcloud** [comment]
这里我记录哈另外反馈的一个问题：

> 在真机上 两个input之间切换的时候 右侧的clear部分消失的很慢。这个有解决方法么

**Comment by pingan1927** [comment]
> 在真机上 两个input之间切换的时候 右侧的clear部分消失的很慢。

统一改了，加上`setTimout`，延迟从300ms改为100ms。 @silentcloud 到时反馈性下效果哈
