### ISSUE TITLE
web 项目无法使用 antd-mobile

### ISSUE THREAD

**Issue by colorfuljava** [ant-design/ant-design-mobile#686]
#### 本地环境

npm 3.10.8
dva 脚手架生成的项目

- antd-mobile 版本：

0.9.13

- 浏览器 (或标明是 react-native) 及其版本：

chremo

- 运行环境及其版本：
mac
#### 你做了什么？
`import Button from 'antd-mobile/lib/button';`

   `return (
          <Button>Start</Button>
   );` 
  

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

Module not found: 'react-native'

**Comment by afc163** [comment]
#602

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#web-使用方式
