### ISSUE TITLE
时间选择器样式有问题

### ISSUE THREAD

**Issue by YoFoon** [ant-design/ant-design-mobile#688]
#### 本地环境

- antd-mobile 版本：
- 浏览器 谷歌浏览器（或微信）
- 运行环境及其版本：*版本

#### 你做了什么？

 引入 antd-mobile 的 DatePicker 

#### 你期待的结果是：

 像官网一样正常显示 

#### 实际上的结果：

![image](https://cloud.githubusercontent.com/assets/9361203/21542516/46ef3062-cdf9-11e6-9233-0208125af9da.png)

#### 可重现的在线演示

@luolonghao @sorrycc @lifesinger @yiminghe @pingan1927

**Comment by warmhug** [comment]
问题需要描述清楚，并给出错误的 demo

**Comment by YoFoon** [comment]
``
<DatePicker
  mode={item.formatDate ? "date" : "datetime"}
  title="选择日期"
  extra="可选,小于结束日期"
  {...getFieldProps(item.code, {
    initialValue: zhNow,
  })}
>
  <ListItem arrow="horizontal">{item.name}</ListItem>
</DatePicker>
`

就是这样子用的，正常引用

**Comment by warmhug** [comment]
fork https://codepen.io/warmhug/pen/bwRPvx 给出可运行错误示例
