### ISSUE TITLE
CheckboxItem组件的onChange事件响应了两次且事件对象不一致

### ISSUE THREAD

**Issue by xaviertung** [ant-design/ant-design-mobile#689]
#### 本地环境

-操作系统：windows 10 pro
- antd-mobile 版本：0.9.13
- 浏览器 (或标明是 react-native) 及其版本：Chrome
- 运行环境及其版本：

#### 你做了什么？
组件中引入了CheckboxItem组件，并且组件调用了handleIsMemberChange方法：
`<CheckboxItem onChange={this.handleIsMemberChange.bind(this)}>demo</CheckboxItem>`
`  handleIsMemberChange(e) {
    console.log("member is:", e);}`

#### 你期待的结果是：
点击复选框时，触发一次onChange方法

#### 实际上的结果：
点击复选框时，触发了两次onChange方法，经打印对象可以确定，事件对象e不是同一种：
1：member is: Object {target: Object}
2：member is: Object {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchListeners: Array[2], _dispatchInstances: Array[2], nativeEvent: MouseEvent…}

**Comment by warmhug** [comment]
感谢反馈，已修复
