### ISSUE TITLE
高清方案在android的系统webView中没有起作用

### ISSUE THREAD

**Issue by Sdoy** [ant-design/ant-design-mobile#692]
#### 本地环境

- antd-mobile 版本：0.9.12
- 浏览器 (或标明是 react-native) 及其版本：安卓6.0 webview
- 运行环境及其版本：模拟器

#### 你做了什么？
使用高清方案

#### 你期待的结果是：
页面正确缩放

#### 实际上的结果：
meta标签似乎没有在安卓的webview上起作用

#### 可重现的在线演示

webview访问的url:(http://m.test5.laobai.com/grouppurchase/detail/?orderNo=9945393368643482)

![image](https://cloud.githubusercontent.com/assets/10302939/21564994/5223685c-cecd-11e6-8b26-4c51ffa709ea.png)
```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        WebView webView = (WebView) findViewById(R.id.wb);
        webView.setWebViewClient(new WebViewClient());
        webView.getSettings().setJavaScriptEnabled(true);
        webView.setWebChromeClient(new WebChromeClient());
        webView.loadUrl("http://m.test5.laobai.com/grouppurchase/detail/?orderNo=9945393368643482");
    }
}
```
![image](https://cloud.githubusercontent.com/assets/10302939/21565008/7991d0fe-cecd-11e6-9e62-460641e525c2.png)

**Comment by warmhug** [comment]
Java 代码少了设置，加上`webView.getSettings().setUseWideViewPort(true);`
