### ISSUE TITLE
List组件里面的item border 1px 会被转换成rem 然后变成0

### ISSUE THREAD

**Issue by cjd6568358** [ant-design/ant-design-mobile#695]
#### 本地环境

- antd-mobile 版本：0.9.13
- 浏览器 (或标明是 react-native) 及其版本：手机QQ浏览器
- 运行环境及其版本：

#### 你做了什么？

引入 antd-mobile 的 List 

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

border-bottom 消失

#### 可重现的在线演示

http://cjd6568358.coding.me/xgj-client/my

**Comment by warmhug** [comment]
查看下官网源代码，写成 1PX ，避免被转为 rem

**Comment by cjd6568358** [comment]
写成大写的吗？但是这个样式是你们内置的啊

**Comment by warmhug** [comment]
组件里的 list 1px border 都是写的大写 1PX ，你需要改写组件样式也这么写就好

**Comment by cjd6568358** [comment]
但是我确实是用的你们默认的样式，没有自己追加，同样不行，用手机QQ浏览器打开你们的demo也一样看不到1px

**Comment by warmhug** [comment]
我在 Android 6 手机 QQ 里看是有线的，表现正常。

**Comment by cjd6568358** [comment]
今晚又看了一下，官网的demo确实是1px,但是我npm 下载你们的包 打包出来后就变成 0.01rem了，不清楚怎么回事，要不你们从npm拉下来再试试，版本是0.9.13？
![image](https://cloud.githubusercontent.com/assets/3970494/21685822/ff114ac8-d39d-11e6-8303-16c8f5accf84.png)

**Comment by warmhug** [comment]
0.9.13试过，没问题的。看下你 pxtorem 设置是不是有问题？

**Comment by cjd6568358** [comment]
这是我的webpack配置文件
`
const webpack = require('webpack');
const path = require('path')
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const HtmlWebpackPlugin = require('html-webpack-plugin')
const HappyPack = require('happypack')
const CopyWebpackPlugin = require('copy-webpack-plugin');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');
const pxtorem = require('postcss-pxtorem');

const ENV = process.env.NODE_ENV = process.env.ENV = 'development';

module.exports = {
    entry: {
        index: ['babel-polyfill', path.resolve(__dirname, 'src/app')]
    },
    devtool: 'source-map',
    output: {
        path: path.resolve(__dirname, 'build/js'),
        filename: 'js/[name].js',
        // chunkFilename: 'js/[name].[chunkhash:5].chunk.js'
    },
    resolve: {
        extensions: ['', '.web.js', '.jsx', '.js', '.json'],
        alias: {
            "H5lock": path.resolve(__dirname, 'src/lib/H5lock.publish.js'),
            "hidpi-canvas-polyfill": path.resolve(__dirname, 'src/lib/hidpi-canvas.min.js')
        }
    },
    module: {
        loaders: [
            // {
            //   test: /\.jsx?$/,
            //   loader: 'babel',
            //   exclude: /node_modules/,
            //   query: {
            //     presets: ['es2015', 'stage-0', 'react'],
            //     plugins: [
            //       "transform-decorators-legacy",
            //       "transform-class-properties",
            //       ["import", { libraryName: "antd-mobile", style: "css" }]
            //     ]
            //   },
            //   include: __dirname
            // }, 
            {
                test: /\.jsx?$/,
                loader: 'happypack/loader?id=js',
                exclude: /node_modules/,
                include: __dirname
            },
            {
                test: /\.scss/,
                exclude: /node_modules/,
                loader: ExtractTextPlugin.extract('style', 'css!postcss!sass')
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract('style', 'css!postcss')
            },
            {
                test: /\.jpe?g$|\.gif$|\.png$/i,
                exclude: /node_modules/,
                loader: 'url?limit=8192&name=images/[hash:8].[name].[ext]'
            }
        ]
    },
    postcss: function() {
        return [
            autoprefixer({
                browsers: ['last 3 versions', '> 1%']
            }),
            cssnano,
            pxtorem({
                rootValue: 100,
                propWhiteList: [],
            })
        ]
    },
    plugins: [
        // new CopyWebpackPlugin([
        //     { from: 'src/images', to: 'images' },
        //     { from: 'src/fonts', to: 'fonts' }
        // ]),
        new HtmlWebpackPlugin({
            title: "",
            hash: true,
            baseUrl: process.env.NODE_ENV == 'development' ? '/' : '/xgj-client/',
            template: path.resolve(__dirname, 'src/index.html')
        }),
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify(ENV)
            }
        }),
        new webpack.DllReferencePlugin({
            context: __dirname,
            manifest: require('./build/vendor-manifest.json')
        }),
        new ExtractTextPlugin("css/[name].css"),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        }),
        new webpack.NoErrorsPlugin(),
        new HappyPack({
            id: 'js',
            threads: 8,
            loaders: [{
                path: 'babel',
                query: {
                    presets: ['es2015', 'stage-0', 'react'],
                    plugins: [
                        "transform-decorators-legacy",
                        "transform-class-properties", ["import", { libraryName: "antd-mobile", style: "css" }]
                    ]
                }
            }]
        })
    ]
};
`

**Comment by warmhug** [comment]
这样难以看出问题。建议整理个简单能跑起来的错误 demo 发到 GitHub 上，我 clone 下来跑跑看。

**Comment by cjd6568358** [comment]
https://git.coding.net/cjd6568358/xgj-client.git
这是我的项目，请帮忙看下

**Comment by warmhug** [comment]
@cjd6568358 你的项目跑不起来， npm run dev

**Comment by cjd6568358** [comment]
需要先跑 npm run dll  然后 npm run dev

**Comment by cjd6568358** [comment]
@warmhug

**Comment by cjd6568358** [comment]
@warmhug 需要先跑 npm run dll 然后 npm run dev

**Comment by warmhug** [comment]
https://coding.net/u/cjd6568358/p/xgj-client/git/blob/master/webpack.config.js#L74  
![image](https://cloud.githubusercontent.com/assets/2011119/21765409/a3f63f5a-d6a3-11e6-9be6-84a7f5f20e40.png)

cssnano 放到 pxtorem 之后

**Comment by cjd6568358** [comment]
@warmhug 感谢！

**Comment by warmhug** [comment]
@cjd6568358 你这个项目工具配置挺全面的，不知能否提到这里 https://github.com/ant-design/antd-mobile-samples/tree/master/web-webpack-pro 作为官方 sample ？

**Comment by cjd6568358** [comment]
@warmhug 可以的，多谢

**Comment by cjd6568358** [comment]
@warmhug 需要我自己提交吗？

**Comment by silentcloud** [comment]
@cjd6568358 欢迎自己提交
