### ISSUE TITLE
antd mobile的搜索栏在安卓下没法点击

### ISSUE THREAD

**Issue by bf185003** [ant-design/ant-design-mobile#696]
华为 mate 8 手机，安卓6.0

antd mobile是最新版本。

搜索栏只能看到放大镜，无法点击。

**Comment by warmhug** [comment]
麻烦确认下官网 demo 是否正常？

**Comment by warmhug** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/576#issuecomment-273081970 https://github.com/ant-design/ant-design-mobile/issues/576#issuecomment-274005841

没反馈，先关掉
