### ISSUE TITLE
抽屉drawer效果按照官网的方法点击事件失效

### ISSUE THREAD

**Issue by duxianwei520** [ant-design/ant-design-mobile#697]
- antd-mobile 版本：0.9.13
- 浏览器 (或标明是 react-native) 及其版本：chrome54.0
- 运行环境及其版本：windows10

#### 你做了什么？
把官网demo的抽屉drawerdemo放在codepan里面运行

#### 你期待的结果是：
运行正常，可以跟官网一样点击侧边栏可以推出来

#### 实际上的结果：
点击没有任何响应，还望指点一下

#### 可重现的在线演示
http://codepen.io/dupi/pen/WRNYzm

**Comment by warmhug** [comment]
你的 demo 上一些 css 样式没加上、官网上是有的，官网文档上遗漏展示出来，已更改。

**Comment by duxianwei520** [comment]
加上了css样式在哪里可以看到demo的呢

**Comment by warmhug** [comment]
https://mobile.ant.design/components/drawer/

**Comment by duxianwei520** [comment]
> .my-drawer {
  position: relative;
  height: 100%;
  overflow: auto;
}
.my-drawer .am-drawer-sidebar {
  max-width: 4.6rem;
  background-color: #fff;
  overflow: auto;
}
.my-drawer .am-drawer-sidebar .am-list {
  padding: 0;
}

就加这几句css样式就好了的意思么？好像只是onOpenChange这个方法起作用了，弹窗还是没有推出来

**Comment by warmhug** [comment]
这是比较基础的东西，建议自己多研究下

**Comment by duxianwei520** [comment]
增加了官网的样式之后，onOpenChange事件确实起作用了，open这个state也在切换变化，但是，即使我手动把open值设置为true，侧边栏依旧不能弹出来的呀，在上面我写的在线的demo地址里面已经添加了亲说的样式，功能依旧不正常，是我没设置对么

**Comment by warmhug** [comment]
注意元素高度设置

**Comment by duxianwei520** [comment]
@warmhug 感谢亲的耐心指导，现在在线的demo已经可以运行起来了，只是我本地用npm包import跑出来的demo，点击左上角按钮确实可以push出来侧边栏，但点击am-drawer-overlay这个半透明的黑色遮罩层并没有关闭drawer，不知道是框架的问题呢还是我自己的问题，好像点击事件没有触发

**Comment by warmhug** [comment]
继续对照下你是否哪里用错了。官方 demo 和组件没发现问题。
