### ISSUE TITLE
antd-mobile 报错说模块没找到

### ISSUE THREAD

**Issue by JSlife23** [ant-design/ant-design-mobile#699]
#### 本地环境

- antd-mobile 版本："antd-mobile": "^0.9.13",
- 浏览器 (或标明是 react-native) 及其版本：chrome 最新版 55.0.2883.87 m
- 运行环境及其版本：

#### 你做了什么？
 我用create-react-app 脚手架 然后安转了antd-mobile 在代码里面引入

import { Slider,WingBlank,WhiteSpace } from 'antd-mobile'
#### 实际上的结果：
   报错说没找到antd-mobile 模块 可是我明明安装了是我姿势不对吗？

**Comment by afc163** [comment]
#602

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#使用
