### ISSUE TITLE
SPA kitchen sink

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#7]
http://mobile.ant.design/kitchen-sink/

Like https://weui.io/

现在打开要刷半天，体验很不好。

**Comment by dyf2015** [comment]
weui????

???? iPhone

? 2016?7?31??20:28??? <notifications@github.com<mailto:notifications@github.com>> ???


http://mobile.ant.design/kitchen-sink/

Like https://weui.io/

???????????????

-

**Comment by yiminghe** [comment]
@benjycui http://mobile.ant.design/kitchen-sink/ 好慢，每次点击都是重新加载，链接数还很多

**Comment by liqi07** [comment]
https://github.com/ant-design/ant-design-mobile/commit/fa36f23ab8355c3adfdf444d172e1322b5e6e00c 已用react-router的Link代替页面刷新

**Comment by yiminghe** [comment]
@liqi07  0.7.x 网站发布下

**Comment by liqi07** [comment]
done
