### ISSUE TITLE
请问下，InputItem有没有补全提示的功能，antd-mobile是否有其他组件有这种功能？

### ISSUE THREAD

**Issue by rurusgit** [ant-design/ant-design-mobile#702]
#### 本地环境
    dva 

- antd-mobile 版本：0.9.13
- 浏览器 (或标明是 react-native) 及其版本： Chrome
- 运行环境及其版本：windows10

#### 你做了什么？

    引入 antd-mobile 的 InputItem

#### 你期待的结果是：

    例如，当输入'a'的时候，会下拉出'abc','abc','abcde这类的补全输入

#### 实际上的结果：

    官方文档中并没有类似功能的描述

**Comment by warmhug** [comment]
没有。需求简单的自己可以实现下
