### ISSUE TITLE
对Picker的建议，当列过长时希望换行

### ISSUE THREAD

**Issue by weiq** [ant-design/ant-design-mobile#703]
当前样式：
![image](https://cloud.githubusercontent.com/assets/1697158/21673329/610041c0-d363-11e6-8259-b6160ec5dcac.png)

希望是下面样式：
![image](https://cloud.githubusercontent.com/assets/1697158/21673348/7ccbe102-d363-11e6-92ed-1c4f4809720a.png)

**Comment by warmhug** [comment]
换行会影响高度计算。不过可以考虑下

**Comment by weiq** [comment]
@warmhug 我覆盖了一下 `.am-picker-col-item` 样式
```
.am-picker-col-item {
  line-height: 1;
  white-space: normal;
  display: flex;
  justify-content: center;
  align-content: center;
  flex-direction: column;
  overflow: hidden;
}
```
效果如下：
![image](https://cloud.githubusercontent.com/assets/1697158/21704941/77cf526c-d3f7-11e6-9dc4-1c4a0e515e3b.png)

**Comment by warmhug** [comment]
这样不是挺难看么，能搞定就好

**Comment by silentcloud** [comment]
iOS native 没见过换行这种 UI，一般都是 

![image](https://cloud.githubusercontent.com/assets/1698185/21710299/b4abc9ce-d422-11e6-8cd2-3eb20ded2d00.png)

**Comment by weiq** [comment]
@silentcloud 咱现在的例子结尾缺少省略号，应该是没有overflow: hidden;造成的

**Comment by silentcloud** [comment]
恩，目前是 overflow hidden 了，后面改成 省略号

**Comment by warmhug** [comment]
web 的不要改成 省略号，否则在有些机器上会导致少显示最后一两个字(本来很可能是正常的)，因为省略号导致信息被隐藏这样不好、也没实际场景需要。
@weiq 如果需要省略号，业务自己覆盖加上即可。组件不建议这么做。
