### ISSUE TITLE
web版本如何获取到listView的滑动位移（如iOS中的contentOffset）

### ISSUE THREAD

**Issue by qussers** [ant-design/ant-design-mobile#704]
#### 本地环境
MAC

- antd-mobile 版本：9.0
- 浏览器 (或标明是 react-native) 及其版本：chrome
- 运行环境及其版本：node

#### 你做了什么？

时时监听listView位置

#### 你期待的结果是：

能够获取

#### 实际上的结果：

没能找到对应api

**Comment by warmhug** [comment]
没有对应的 API ，自己可以从 dom ref 里获取到

**Comment by qussers** [comment]
能不能给下示例代码？

**Comment by wongben** [comment]
可以参考这个http://jjboom.net/cnode/#/tab=all?_k=ngnnzs

https://github.com/dianjie/cnodeapp

**Comment by warmhug** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/488#issuecomment-267558738 。由于 contentOffset 只是 iOS 特有的，这里不实现。解决办法更新在 demo 里
