### ISSUE TITLE
我觉得我用你们的 ant-design-mobile，我个人觉得写react都简单，就是用你antd 太辛苦 太心累了

### ISSUE THREAD

**Issue by yeyuguo** [ant-design/ant-design-mobile#706]
#### 本地环境

- antd-mobile 版本：
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：

#### 你做了什么？
我想启动 启动 启动 启动 启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动启动 启动 启动 启动

我就想简单的自动化的 跑起来监测，文档上全是些说些逼格很高的东西，我就想要个纯净的ant-mobile，可以有吗？可以有吗？能可以有吗？
我真的快要从 ant 入门到放弃了

**Comment by warmhug** [comment]
按照文档步骤来做，没问题的。复杂度是大点、因为直接包含了很多对项目来说是额外优化的东西。

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#使用
