### ISSUE TITLE
add react-native component for api call

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#708]
```
Modal.alert(...)
```

==

```
<ModalAlert .../>
```

**Comment by silentcloud** [comment]
`https://github.com/ant-design/ant-design-mobile/blob/master/components/popup/PopupContainer.tsx`
`https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/AlertContainer.tsx`
`https://github.com/ant-design/ant-design-mobile/blob/master/components/action-sheet/AndroidContainer.tsx`

@yiminghe
