### ISSUE TITLE
有计划做CollectionView的控件么

### ISSUE THREAD

**Issue by wongben** [ant-design/ant-design-mobile#709]
如iOS的 UICollectionView

**Comment by wongben** [comment]
这样可以实现类似石工布局等

**Comment by paranoidjk** [comment]
抱歉，准备 close 这个。
- 短期内不考虑新增组件，优先考虑目前组件的性能，体验，稳定性优化。
- 新增组件需要 业务 / 社区  比较普通的需求和投票。

当然，Pull Request 帮助我们做是随时欢迎的 😄
