### ISSUE TITLE
Module not found: Error: Cannot resolve module 'antd-mobile'

### ISSUE THREAD

**Issue by yeyuguo** [ant-design/ant-design-mobile#713]
#### 本地环境

- antd-mobile 版本：antd-mobile@0.9.13
- 浏览器 (或标明是 react-native) 及其版本：react-native-scrollable-tab-view@0.6.0
- 运行环境及其版本：node@v7.2.1  
想在 pc 端运行调试
$ cnpm ls react
@0.0.1 e:\gitlab\ant-chat
├─┬ antd-mobile@0.9.13
│ ├─┬ nuka-carousel@2.0.4
│ │ └── react@15.4.2
│ ├── react@15.4.2
│ ├─┬ react-native-scrollable-tab-view@0.6.0
│ │ └── react@15.4.2
│ └─┬ rmc-list-view@0.7.4
│   └── react@15.4.2
└── react@15.4.2

#### 你做了什么？
我用的 yoman 快速构建的项目结构   
![image](https://cloud.githubusercontent.com/assets/8602918/21812640/8dddced6-d78e-11e6-964f-7715410fc035.png)

#### 实际上的结果：

![image](https://cloud.githubusercontent.com/assets/8602918/21812282/60b5029a-d78d-11e6-95c2-2fbce4e28808.png)

#### 可重现的在线演示
https://github.com/yeyuguo/antd-chat   
你们可以下载这个配置文件看，我实在是找不出来问题了，我在使用antd 时候是使用你们的 dva，但是我用这个 antd-mobile 不想要你们的 dva 了，用的是 yoman 创建的

**Comment by afc163** [comment]
#602

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/docs/react/introduce.zh-CN.md#web-使用方式

**Comment by yeyuguo** [comment]
[#602](https://github.com/ant-design/ant-design-mobile/issues/602)   这篇Issue 描述的比较清楚明白，并且解决办法也都有效  @afc163  赞
