### ISSUE TITLE
会考虑开发这种组件吗。。

### ISSUE THREAD

**Issue by YoFoon** [ant-design/ant-design-mobile#714]
![image](https://cloud.githubusercontent.com/assets/9361203/21839102/f0f5dc0c-d810-11e6-93aa-85fc1d549327.png)

**Comment by Aaaaaashu** [comment]
@YoFoon 
https://mobile.ant.design/components/checkbox/

**Comment by silentcloud** [comment]
已经有了 CheckboxItem， 见 LS 地址

**Comment by YoFoon** [comment]
哦，就是有点和我想的不一样。这个东西

然后我只能来问一下
![image](https://cloud.githubusercontent.com/assets/9361203/21876256/75ecf2d2-d8bc-11e6-8e58-592b49942445.png)
![image](https://cloud.githubusercontent.com/assets/9361203/21876285/a89d9bf0-d8bc-11e6-8639-89e2419355d0.png)

我就是这样写的，然后下拉选项特别多的时候，在移动端上滑动起来会特别慢QAQ。

**Comment by warmhug** [comment]
@YoFoon 确认一下，不用 fixed ，其他一样、是否也慢？
