### ISSUE TITLE
List.Item在RN中能否增加是否显示border的属性，或者用样式来控制更加灵活 

### ISSUE THREAD

**Issue by meakchen** [ant-design/ant-design-mobile#717]
#### 本地环境

- antd-mobile 版本：
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：

**Comment by silentcloud** [comment]
这个关系到自定义 RN 组件样式，目前这块的方案不是太好确定，我们这边在计划了

**Comment by silentcloud** [comment]
这个 issue 链接 #698 ，这里就先关了
