### ISSUE TITLE
1.0.0-beta.0图标不显示

### ISSUE THREAD

**Issue by szwork2013** [ant-design/ant-design-mobile#718]
1.0.0-beta.0，最新的实验版图标都不显示，发布版0.9.13可以，
<Icon type="home" size="md" />

**Comment by silentcloud** [comment]
1.0.0 用了 svg，图标使用需要换一下方式，Icon 组件自带的图标减少了很多个，需要自定义 svg 图标 @szwork2013

**Comment by afc163** [comment]
图标找设计师补齐一下吧，功能上最好向下兼容。

**Comment by warmhug** [comment]
@afc163 移动端图标大多都是来自业务、不通用，原来的图标绝大多数都没什么用。这里不用补齐，故意去掉的，另外图标多了、最终的包大小也会太大。
