### ISSUE TITLE
antd-mobile v0.9.13 的Popup组件在react native下点击遮罩层不会自动关闭

### ISSUE THREAD

**Issue by tungh** [ant-design/ant-design-mobile#719]
#### 本地环境

- antd-mobile 版本：0.9.13
- 浏览器 (或标明是 react-native) 及其版本：react native 0.37
- 运行环境及其版本：mac

#### 你做了什么？

antd-mobile 的 Popup 组件 点击遮罩层不能自动关闭

#### 你期待的结果是：

使用默认的Popup option 点击遮罩层可以自动关闭

#### 实际上的结果：

点击遮罩层不能自动关闭

直接使用代码里面的自带demo都不能关闭

{
              maskClosable: true,
              animationType: 'slide-up',
              onMaskClose: () => new Promise(resolve => {
                 setTimeout(resolve, 1000);
                 console.log("请求关闭提示");
               }),
            }
#### 可重现的在线演示

直接通过二维码下载的官方demo却正常的

**Comment by silentcloud** [comment]
https://github.com/ant-design/ant-design-mobile/commit/7fd8fc56832e0f7cf1a104a940c43cce2d15f992

等待 0.9.14
