### ISSUE TITLE
react移动端点击穿透,Grid不能用onTouchStart

### ISSUE THREAD

**Issue by DemosBin** [ant-design/ant-design-mobile#720]
#### 本地环境

- antd-mobile 版本：0.9.13
- 浏览器 (或标明是 react-native) 及其版本：IOS微信浏览器
- 运行环境及其版本：IOS

#### 你做了什么？
引用Grid组件，点击跳转一个表单页面，点击事件会穿透到表单页，使得表单页的input框获得焦点，
已经引用了fastclick,并不能解决，发现Grid并不能用onTouchStart事件

#### 你期待的结果是：
点击Grid后跳转表单，点击事件不会穿透，点击处的input不会获得焦点

#### 实际上的结果：
点击Grid后跳转表单，点击事件穿透，点击处的input获得焦点

**Comment by warmhug** [comment]
组件 Grid 一直用的 click 事件，没用到 onTouchStart 事件

**Comment by warmhug** [comment]
注意，不要使用 [react-fastclick](https://www.npmjs.com/package/react-fastclick) (有 bug)，要用这个 [fastclick](https://github.com/ftlabs/fastclick)

没反馈，先关掉
