### ISSUE TITLE
在两个 button 之间快速点击会报错

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design-mobile#723]
#### 本地环境

- antd-mobile 版本：0.9.13
- 浏览器 (或标明是 react-native) 及其版本：浏览器
- 运行环境及其版本： Chrome Version 55.0.2883.95 (64-bit)

#### 你做了什么？

https://codepen.io/yesmeck/pen/KaMgNQ?editors=0010 

上面的 demo，快速点击 Button1 和 Button2。

#### 你期待的结果是：

不报错。

#### 实际上的结果：

```
Uncaught TypeError: Cannot read property 'pageX' of undefined
    at touchableHandleResponderRelease (index.js:335)
    at t.onMouseUp (index.js:271)
touchableHandleResponderRelease @ index.js:335
onMouseUp @ index.js:271
```

#### 可重现的在线演示

https://codepen.io/yesmeck/pen/KaMgNQ?editors=0010

另外拉取了 master 的代码跑起 Demo 来也会报错。

**Comment by paranoidjk** [comment]
- 奇怪，快速点击报错我这没法复现，说下你的浏览器型号和版本？ 
- 但是根据你的error stack来看，是`rc-touchable`的这一行报错了 https://github.com/react-component/touchable/blob/master/src/index.tsx#L384  
- 另外，master的demo我刚跑了没报错，给下详细信息？

**Comment by yesmeck** [comment]
原因是在[这里](https://github.com/react-component/touchable/blob/3d9e608b9b0d8de97ddb8084889a604afb04866c/src/index.tsx#L333-L342)，第一个按钮点击后马上再点击第二个按钮的时候，可能还在 delay 时间内，导致第二个的按钮不允许点击，第二个按钮就跑不到下面的 `this._remeasureMetricsOnInit`, `this.touchable` 没有初始化，所以[这里](https://github.com/react-component/touchable/blob/3d9e608b9b0d8de97ddb8084889a604afb04866c/src/index.tsx#L384)读不到`this.touchable.startMouse.page`。

@yiminghe

**Comment by yiminghe** [comment]
reinstall
