### ISSUE TITLE
关于多行输入的建议。。

### ISSUE THREAD

**Issue by YoFoon** [ant-design/ant-design-mobile#724]
![image](https://cloud.githubusercontent.com/assets/9361203/21952176/93c167a8-da50-11e6-91bb-47d666cf4037.png)

TextareaItem 多行输入 

多行输入为空的时候不显示0，而是直接不显示了，
这是不是有点不好啊，QAQ
只是建议，感觉特别丑。。。

**Comment by paranoidjk** [comment]
感谢反馈，RN 的组件是正常的，Web组件有这个问题，我们会修复
