### ISSUE TITLE
ListView renderBodyComponent 没有文档

### ISSUE THREAD

**Issue by yjj5855** [ant-design/ant-design-mobile#725]
官方文档只写了 是一个function 

#### 本地环境

- antd-mobile 版本：0.9.12
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：

#### 你做了什么？

```
 <ListView
                    dataSource={dataSource1}
                    renderRow={this.renderRow}
                    renderBodyComponent={()=> <h1>renderBodyComponent</h1>}

                    refreshControl={<RefreshControl
                        refreshing={this.state.refreshing}
                        onRefresh={this.onRefresh}
                    />}
                />
```

#### 你期待的结果是：

body变成 h1

#### 实际上的结果：

没反应

#### 可重现的在线演示
无

**Comment by paranoidjk** [comment]
- sorry， 这里有点问题，fix中
- 但是提醒下，`renderBodyComponent`的设计意图只是渲染listview body 的`包裹元素`，你写在h1中间的文字是不会渲染的，正确用法是类似如下：

```js
renderBodyComponent={() => <h1 className="for-body-demo" />}
```

**Comment by warmhug** [comment]
renderBodyComponent 可以很自由的使用，参考 commit 里用法：
![image](https://cloud.githubusercontent.com/assets/2011119/22015219/1484bc4a-dcdc-11e6-8447-a6868d378dd7.png)

**Comment by paranoidjk** [comment]
ok，@warmhug 是对的，我对`React.cloneElement`理解有误，删除旧的评论避免误导
