### ISSUE TITLE
react依赖版本问题

### ISSUE THREAD

**Issue by lileilei** [ant-design/ant-design-mobile#729]
#### 本地环境

- antd-mobile 版本：0.9.14
- 浏览器 (google)
- 运行环境及其版本：

#### 你做了什么？
默认安装的react版本15.0.0（为了支持antd）,安装antd-mobile 的react版本不一致导致冲突！

#### 你期待的结果是：

希望与antd 的依赖react版本一致。

#### 实际上的结果：

不一致的react导致引入两个版本的react ，出现冲突！

**Comment by warmhug** [comment]
组件并没有指定依赖哪个版本的 react ，不会出现你说的冲突的

**Comment by warmhug** [comment]
没反馈，先关掉
