### ISSUE TITLE
images 重复

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#73]
#61 input-item/images/error.png

textarea-item/images/error.png

统一放倒 components/style/images/error.png

**Comment by pingan1927** [comment]
@silentcloud 我看你master改了，但是0.7.x没有改。有其它提交，不好cherry-pick。

**Comment by silentcloud** [comment]
恩 我已经改了，放在 1.0 好了，不用在0.7上改 @pingan1927

**Comment by silentcloud** [comment]
fixed b104c316fa3cc60f3cb76527191e3284ad0164f3
