### ISSUE TITLE
新手请问字超级大是怎么解决？

### ISSUE THREAD

**Issue by maddemon** [ant-design/ant-design-mobile#731]
#### 本地环境

- antd-mobile 版本："antd-mobile": "^0.9.14",
- 浏览器 (或标明是 react-native) 及其版本：chrome 50
- 运行环境及其版本：

#### 你做了什么？
我就随便用了个Navbar Accordion 两个组件，发现我的组件的样式font-size的单位是px，而官网演示的都是rem，我这特别大，怎么解决？

**Comment by warmhug** [comment]
仔细看下文档，需要引入高清方案脚本及插件

**Comment by fangbao-0418** [comment]
Thank you
