### ISSUE TITLE
高清方案在微信上的一个特别奇葩的问题。

### ISSUE THREAD

**Issue by minooo** [ant-design/ant-design-mobile#732]
高清方案在手机位上的一个奇葩问题，当字数变多，会莫名其妙的变大，直接上gif 
![11111](https://cloud.githubusercontent.com/assets/9410091/21974085/94babd48-dbff-11e6-83ba-d3f3b90243c9.gif)

大神可在微信开发者工具中打开这个网址，完美重现gif上的问题（一定保证字数足够多啊）
http://s.codepen.io/minooo/debug/PWGEgp/bZAQWjRzYWJM

源码：http://codepen.io/minooo/pen/PWGEgp 

其他： win10系统， 微信开发者工具版本是 0.12.130400

（当然，万能的谷歌没有问题。。。）

**Comment by minooo** [comment]
@silentcloud 有什么解决方案么。

**Comment by silentcloud** [comment]
开发者工具也只是辅助调试性工具，最好在真机里测试。
你先在真机里试试会不会出现这种情况 @minooo

**Comment by minooo** [comment]
@silentcloud 测试了周围好多人的微信（安卓机），都有这种字数变多，字体就变大的问题。我的手机之前也是这种问，然后升级维新后，清除了缓存后才正常起来的。

**Comment by silentcloud** [comment]
@minooo  我在真机 （ip6+）测试没问题，手上没 android 机，你拿这个地址试试 android

http://s.codepen.io/boomerang/948392cb8f25e8298c509ed78b4a71a71484553349284/index.html

**Comment by minooo** [comment]
@silentcloud 安卓打不开啊。这个问题真头疼，安卓微信上（很多机型）用了高清方案，字数一多，字体就变大（他们的微信都是最新版）。

**Comment by minooo** [comment]
问题已解决。
问题原因：以微信默认X5刘浏览器为首的新一代“IE6”， 在高清方案下，如果你不给元素一个高度或者最大高度，字一多，字就会失控变的很大
解决方案：
![image](https://cloud.githubusercontent.com/assets/9410091/22090017/020bb98e-de2a-11e6-8803-096e36c9bcd7.png)

**Comment by afc163** [comment]
腾讯莫名其妙的规则。

**Comment by lqzhgood** [comment]
Chrome  61.0.3113.0（正式版本）canary （64 位）  在做 Sticky Footer 的时候也遇到了.
指定 0.24rem 字体大小，但是去 computed 里面看 却是 36px； 
指定  #main  -> max-height:10000000px 解决。

**Comment by czy0729** [comment]
UC字体莫名放大的问题终于解决了，感谢@minooo

**Comment by xifu** [comment]
也遇到过这个问题，当时发现的问题是，单行文字设置高度和行高后正常，多行文本不限定高度，会出现文字放大效果，我的粗暴决方法是：height:0; display:table;
