### ISSUE TITLE
Tabs 在切换时，一个选项卡用到 ListView 里的"索引列表" 异常

### ISSUE THREAD

**Issue by yeyuguo** [ant-design/ant-design-mobile#733]
#### 本地环境

- antd-mobile 版本：antd-mobile@0.9.13
- 浏览器 (或标明是 react-native) 及其版本：react-native-scrollable-tab-view@0.6.0
- 运行环境及其版本：react@15.4.2,   rmc-list-view@0.7.4

#### 你做了什么？
引入 Tabs 组件和 ListView 组件同时使用，在 Tabs 选项卡里使用 ListView 索引列表  

#### 你期待的结果是：
![image](https://cloud.githubusercontent.com/assets/8602918/21975814/d0431586-dc09-11e6-8fff-abb8e8a17e6c.png)

#### 实际上的结果：  

索引的 ul 跑到了第一个选项卡里了（fixed定位的问题）：  

![image](https://cloud.githubusercontent.com/assets/8602918/21975852/fe4867e2-dc09-11e6-8a38-cb0ddae8927b.png)

![image](https://cloud.githubusercontent.com/assets/8602918/21975867/16b05e0c-dc0a-11e6-845f-d8897135fc64.png)

**Comment by warmhug** [comment]
本地改一下、不用 fixed 定位

**Comment by warmhug** [comment]
没反馈，先关掉
