### ISSUE TITLE
希望对ImagePicker  增加图片多选的功能

### ISSUE THREAD

**Issue by scholar-ink** [ant-design/ant-design-mobile#735]
#### 本地环境

- antd-mobile 版本：
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：

**Comment by pingan1927** [comment]
这个短时间内支持不了。需要有容器能力才好实现

**Comment by pingan1927** [comment]
@scholar-ink 你可以看看 自定义选择图片的方法 `onAddImageClick ` 这个示例，如果容器提供图片多选(例如支付宝或者微信客户端)的功能，就可以支持到。
