### ISSUE TITLE
Card 组件的图片/body/footer,如何添加各自的onclik事件?

### ISSUE THREAD

**Issue by xttianma** [ant-design/ant-design-mobile#737]
#### 你做了什么？

参考组件card的demo 写了一个cad组件

#### 你期待的结果是：

Card 组件的图片/body/footer,如何添加各自的onclik事件?
图像(头像)),内容,底部信息,分别可以点击.

#### 实际上的结果：

当前,我还没有找到办法. 如果能实现,可否给一个demo参考?

**Comment by AdamChrist** [comment]
可以自己传 React.Element 进去.

**Comment by silentcloud** [comment]
LS 正解

```js
< Card.Footer content="这是卡尾" extra={<div onClick={}>这是尾部介绍</div>} / >
```

**Comment by warmhug** [comment]
![image](https://cloud.githubusercontent.com/assets/2011119/22006420/cb6c409a-dca5-11e6-99bd-f76ebce9c96c.png)
@silentcloud 看了下 Card.Header / Footer / Body 这几个组件的 restProps 都没设置、现在外围元素只设置了个 className 。这样不能在外围设置 onClick 等，最好要设置下。包括 RN 的。

**Comment by xttianma** [comment]
@AdamChrist 说的太高深,又碰到新的知识点了. 好在 @silentcloud 补充的这个,自己增加div标签上挂onclick,一下就明白了. 赶紧试试去.

**Comment by xttianma** [comment]
@warmhug 你说的意思是 onclick不能用,仅仅可以修改样式? 怎么设置?怎么解决呢???

**Comment by silentcloud** [comment]
@warmhug 不能在 header footer 等直接加 restprops，基本都是分区域的，直接 `<Card.Header onClick` 是不对的

**Comment by warmhug** [comment]
支持了功能就是完善的、用户可以不用的，但现在这样是不完善的。其他组件基本都有这种支持

**Comment by xttianma** [comment]
图片,标题,内容, foot内容, 都可以支持{}内写入如上{<div onclick=....>}
这样,card作为一个灵活的复合组件, 后续自定义包含的其他组件,也可以有自己的事件.

这样好吗?

**Comment by szwork2013** [comment]
但是在{}里面加内容的样式表不起作用，style这种写法可以，className这种不行。
