### ISSUE TITLE
Search-bar onChange bug

### ISSUE THREAD

**Issue by HengCC** [ant-design/ant-design-mobile#739]
**原生的TextInput也支持onChange, 按照现在的写法,在render的时候没有过滤掉onChange事件. 会导致在某些情况下(_比如一个组件中仅仅包含了一个search-bar和一个展示框. 展示框展示的是search-bar中onChange的值, 这时候这个展示框渲染值的速度无比的慢. 测试IOS和Android都是这样_)组件渲染特别的慢.

因为search-bar暴露出去的onChange和原生的重叠了.导致onChangeText 和 onChange都执行的是一个方法..

解决办法有2个.第一个修改search-bar暴露出去的onChange->onValueChange,这个是目前的解决方案. 另外个办法就是过滤掉onChange. 

但是这样原生的onChange就无法支持了.**

[修改方案](https://github.com/HengCC/ant-design-mobile/commit/9afdd13d0951fe48a3a1d72bdc0d1fb7c221b3bb)

**Comment by silentcloud** [comment]
@HengCC 你是指的，下面这样用有问题么?

```js
<SearchBar  />
<TextInput />
```

**Comment by HengCC** [comment]
` <SearchBar onChange={(e) => { dispatch({ type: "accountTab/test", value: e }) } } />
      <Text>{value}</Text>`


reducer:

`reducers: {
    test(state, action) {
      return {
        ...state,
        value: action.value
      }
    }
  }`

不要开调试模式,调试模式渲染速度正常. 非调试模式下<Text>{value}</Text> 这个基本在searchbar中输入的值大概3秒后才能出来

**Comment by paranoidjk** [comment]
我来fix吧，最初设计意图可能是`SearchBar`对外暴露的API统一是`onChange(value)`

但对应RN的是`onChangeText(value)`和`onChange(e)`

 所以在 [这里](https://github.com/ant-design/ant-design-mobile/blob/master/components/search-bar/index.tsx#L44) 做了一个转换，但在[这里](https://github.com/ant-design/ant-design-mobile/blob/master/components/search-bar/index.tsx#L77) 没有把`onChange`过滤掉，导致每次输入，RN的`onChangeText`和`onChange`同时执行
