### ISSUE TITLE
rn Toast Android ios 问题

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#74]
master 分支，toast 在 Android 点击打不开。另外 listView 组件调用 `Toast.info('加载新数据')` 在 Android 上不显示；在 ios 上显示后，页面不能交互、背景层不能滚动、显示结束后才能动、有点像模态框一样阻塞页面交互。

**Comment by silentcloud** [comment]
android  显示的问题，我瞧瞧；

iOS 显示后不能交互，是有意这样做的，toast 显示的时候不应该有交互操作

**Comment by silentcloud** [comment]
fixed b104c316fa3cc60f3cb76527191e3284ad0164f3

**Comment by warmhug** [comment]
为什么不能交互？这样不对吧？这毕竟不是模态框。

**Comment by silentcloud** [comment]
@warmhug native 都是这样的交互；有什么场景需要在显示 toast 的时候去做交互么，除了返回？

**Comment by warmhug** [comment]
listview 滚动到底时，用 toast 提示、正在加载

**Comment by silentcloud** [comment]
滚动到底，不应该用toast去提示正在加载，你参考一下别的上拉加载更多的展示方式
