### ISSUE TITLE
mobile.ant.design/kitchen-sink有提供项目下载吗?

### ISSUE THREAD

**Issue by Liuthx** [ant-design/ant-design-mobile#740]
#### Mac OS

- 浏览器 (或标明是 react-native) 及其版本：浏览器

#### 我希望能参考下mobile.ant.design/kitchen-sink的项目, 但我在这个git中只找到了旧版本的示例代码. 现在提供的示例网站有源码可以下载吗?

**Comment by warmhug** [comment]
kitchen-sink 是官方专门做 demo 的，不容易使用。参考这里提供的一些项目模板 https://github.com/ant-design/ant-design-mobile/issues/56
