### ISSUE TITLE
 引入高清方案后Tabs组件左右滑动切换失败，停留滑动后的位置

### ISSUE THREAD

**Issue by sosohime** [ant-design/ant-design-mobile#741]
- antd-mobile 版本：0.9.14
Android, sony xperia Z3及其他高分辨率手机

引入高清方案后Tabs组件左右滑动切换失败，停留滑动后的位置
![axzddg_1484731761692_77](https://cloud.githubusercontent.com/assets/13673257/22058396/b479a0a4-dda3-11e6-99eb-902cfd02cbe9.png)

**Comment by silentcloud** [comment]
真机没重现

**Comment by hldzlk** [comment]
发现同样问题
- 项目也配了高清方案
- chrome(58)：开手机模拟就会出现这种问题，取消手机模拟就正常(高清方案应该也自动取消了)，
- iPhone7P: 微信中只有第一页有滑动，然后就没反应了
- 猜测: touch事件是在最外层Tabs上的  可能是touch事件的兼容问题
![2503a1f5-20cc-4974-b3c5-52beace5494b](https://cloud.githubusercontent.com/assets/3941672/23216955/aac225ca-f952-11e6-949a-8791ba261c20.png)

**Comment by sosohime** [comment]
https://mobile.ant.design/components/tabs/
这里的demo也一样
- win10
- chrome(56.0.2924.87)开启手机模拟
- 配置了高清方案
- 取消手机模拟则正常

另外在手机上面chrome也是有问题，微信浏览器就没关系

**Comment by silentcloud** [comment]
- iPhone7P: 微信中只有第一页有滑动，然后就没反应了 `没重现`

**Comment by CodingMonkeyzh** [comment]
http://codepen.io/CodingMonkeyzh/full/KWMWBK/
这个 demo 拷贝至官方示例。
- One Plus 3T: 微信下正常
- One Plus 3T: Chrome 55 下出现上述问题，滑动时卡住，极不流畅
- chrome 模拟有问题，取消手机模拟表现正常

**Comment by paranoidjk** [comment]
chrome模拟器的问题暂时不管。

请各位优先看下真机上最新版 `antd-mobile` `1.0.5` 是否还有此问题

**Comment by paranoidjk** [comment]
close for no response.

@sosohime 
If you still have any further problems, just comment, and i will reopen.

**Comment by CodingMonkeyzh** [comment]
@paranoidjk One Plus 3T(Android 7.0.0): Chrome 55 依然存在出现上述问题

**Comment by paranoidjk** [comment]
@CodingMonkeyzh chrome模拟器先不管，真机上最新 1.0.6 滑动有啥问题？能给个gif吗？感谢

**Comment by CodingMonkeyzh** [comment]
@paranoidjk 下面的截图是 1.0.5 下的，刚刚升级到 1.0.6 也存在这个问题（Android 7.0.0 Chrome 55）
![1.0.6  左右滑动切换失败](http://cuntuku.com/images/2017/03/21/ScreenRecord_2017-03-21-00-23-38.gif)

**Comment by paranoidjk** [comment]
@CodingMonkeyzh https://mobile.ant.design/kitchen-sink/components/tabs?lang=zh-CN#tabs-demo-0

**Comment by CodingMonkeyzh** [comment]
@paranoidjk 打开上面的￼ demo 依然是一样卡顿
![image](https://cloud.githubusercontent.com/assets/2787386/24392173/50c354e4-13c5-11e7-8541-9dc7cbb2a8e0.png)

**Comment by warmhug** [comment]
在微信 支付宝里打开看是没问题。新的 Android chrome 里确实有问题，估计是新的浏览器或新的 webview 有兼容问题

**Comment by jyz1508** [comment]
^1.0.8  魅蓝note3，chrome浏览器仍有此问题，自带浏览器无此问题

**Comment by and80506** [comment]
同问题+1，ant-mobile0.9.15，高清方案tabs打开动画效果，在安卓真机上，滑动切换tab时qq和微信打开稍有卡顿，仍然可以正常切换，而微博打开时，滑动被卡住。
![screenshot-3](https://cloud.githubusercontent.com/assets/1769410/26235526/490eedb0-3c9e-11e7-99bd-80dc9f33a40c.png)

**Comment by markwangen** [comment]
My mobile-antd version is 1.5.0, still have this problem!  Does that means we should not use swipe function of tabs?

**Comment by paranoidjk** [comment]
This is caused by hammer.js bug: https://github.com/hammerjs/hammer.js/issues/1103

Since antd-mobile@2.0 will rewrite tabs, and replace hammer.js with [rc-geture](https://github.com/react-component/gesture), this problem should be fixed.

cc @zhang740

**Comment by paranoidjk** [comment]
https://github.com/react-component/tabs/issues/70

**Comment by paranoidjk** [comment]
https://github.com/hammerjs/hammer.js/issues/1050
