### ISSUE TITLE
请问当前是否做了页面跳转的效果，多谢

### ISSUE THREAD

**Issue by rurusgit** [ant-design/ant-design-mobile#742]
#### 本地环境

windows10

- antd-mobile 版本：^0.9.14
- 浏览器 (或标明是 react-native) 及其版本：Chrome
- 运行环境及其版本：npm + webpack

#### 你做了什么？

准备做页面跳转

#### 你期待的结果是：

点击页面某个元素跳转到另一个页面时，能够有一个“推出”和“推入”的效果，类似IOS中的跳转。

#### 实际上的结果：

没有找到类似的组件，请问是否有，或者能否推荐一个，多谢。

**Comment by warmhug** [comment]
https://github.com/ReactTraining/react-router

**Comment by CodingMonkeyzh** [comment]
@warmhug , @rurusgit 的意思应该是页面路由/页面跳转的效果（能够有一个“推出”和“推入”的效果）。 我觉得这个效果应该是APP提供的吧

**Comment by warmhug** [comment]
这个按说我们组件库也可以提供，但觉得类似 react-router 的库提供更好
