### ISSUE TITLE
Toast设置duration为0时，手动隐藏不好使

### ISSUE THREAD

**Issue by weiq** [ant-design/ant-design-mobile#745]
Toast设置duration为0时，手动隐藏不好使。
如果只有一个Toast提示时可以隐藏，如果有两个的时候最先出来的Toast隐藏不了。

示例：
https://codepen.io/weiq/pen/NddyXw?editors=0010

**Comment by paranoidjk** [comment]
内存里面只保留了对最新的Toast实例的引用，所以你调用 `Toast.hide()`只能隐藏最新的那个Toast

@weiq 对于你的需求，应该写成这样

```    
Toast.hide();  // 请求结束的时候先隐藏加载中loading
Toast.fail("加载错误1！", 400); // 再显示加载错误的toast
```

@silentcloud 是不是可以考虑改下Api的设计，类似这样
```
const toast = Toast.loading('text');
toast.hide();
```

**Comment by silentcloud** [comment]
实际业务中用到的情况，一般页面中都只是有一个 toast 当前在显示中，应该很难看到两个 toast 同时显示吧，第二种方式在使用中还要保存引用实例，用起来略显麻烦

**Comment by weiq** [comment]
@paranoidjk @silentcloud 很多时候会有同时发多个ajax时，在请求前loading提示的并发问题，不可能按顺序隐藏。
例如：
```
fetchData(url) {
  Toast.loading("请求中...");
  $.ajax({ url, success: function(){
    Toast.hide();
  }});
}

componentWillMount() {
  this.fetchData("url1");
  this.fetchData("url2");
}
```
下面这种方式可以满足要求
```
const toast = Toast.loading('text');
toast.hide();
```

**Comment by paranoidjk** [comment]
从移动端的场景来看，实际上一个页面的确不太可能同时两个Toast

@silentcloud  另一种方案，或者把Toast做成单例？每次调用都销毁/覆盖之前的？

**Comment by silentcloud** [comment]
@paranoidjk 恩，这个方案可行，也不会存在兼容性改动，我稍后改一下

**Comment by paranoidjk** [comment]
@silentcloud 💯  忙的话也可以assign给我，你来review
