### ISSUE TITLE
把SearchBar搜索组件放在Popup里根本无法输入内容

### ISSUE THREAD

**Issue by szwork2013** [ant-design/ant-design-mobile#746]
把SearchBar搜索组件放在Popup里根本无法输入内容
![popup](https://cloud.githubusercontent.com/assets/8146801/22097487/43c3c150-de5c-11e6-84b1-ad1a4d2057f1.jpeg)

**Comment by warmhug** [comment]
测试可以输入，没发现问题

**Comment by paranoidjk** [comment]
@szwork2013 
- 请参考这个给一个可复现的demo： https://codepen.io/paranoidjk/pen/BpZrjQ
- 另外，如果不是必现，建议提供设备和浏览器版本等相关信息方便排查

**Comment by paranoidjk** [comment]
没有反馈，有问题再open。
