### ISSUE TITLE
讨论：Modal.alert/Modal.Prompt Api设计

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#747]
## 问题
- 现有Modal.prompt的接口定义是这样的

```
Modal.prompt(title?, message?, callbackOrActions, type?, defaultValue?) ( 适用平台：WEB )
```
> 实际上目前这个可选参数的实现是有bug的，比如打开这个[demo](http://codepen.io/paranoidjk/pen/WRRyMd?editors=1010) ,  去掉title或者message参数就会发现有bug

- 其次，typescript是不允许函数optional的参数后面有必选的参数的，会有如下错误（**目前Modal.prompt没写ts类型，所以没报错**）
```
 error TS1016: A required parameter cannot follow an optional parameter.
```

- 第三，可选参数这种不仅会让实现的[代码混乱](https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/prompt.web.tsx#L15)，给用户也不太好， 如果不是为了兼容RN或者Web原生的Api的语法，参数还是都改成Object配置比较好，比如参考Antd的Modal接口设计

@warmhug  **也有可能是文档写错了，这两个参数都不是可选的**?

**Comment by silentcloud** [comment]
@paranoidjk  http://facebook.github.io/react-native/docs/alert.html

**Comment by paranoidjk** [comment]
@silentcloud 
- RN的这种是可以的，可选参数后面没有必选
```
static alert(title, message?, buttons?, options?, type?) 
```

- 但是我们已经有一个`Modal.alert`来适配RN了，`Modal.prompt`是 web only，应该没必要模仿RN的设计，我还是建议这种多个参数可传可不传的做成JSON

- 现实问题是，我们没法给Modal.Prompt加上类型定义... ref #667 这里提出来的

**Comment by silentcloud** [comment]
Modal.prompt web only 只是没时间做，当时只做了 web，所以写 web only，后期还是要加上的

**Comment by paranoidjk** [comment]
@silentcloud  你这个描述还是有问题，按正确的设计意图更新下文档吧

> 恩 文档是有点问题，实际中 title 和 message 必有一项， callbackOrActions 是可选的

按这个schema，怎么决定第一个参数是 title 还是 message ...
`Modal.prompt(title?, message?, callbackOrActions, type?, defaultValue?) ( 适用平台：WEB )#`
