### ISSUE TITLE
升级 antd-tools 至最新版

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#748]
更新 antd-tools 版本（ts）版本

**Comment by paranoidjk** [comment]
写死版本有什么特殊缘由吗？ https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L72

**Comment by silentcloud** [comment]
之前有 lock，见 https://github.com/ant-design/ant-design/commit/b5fcb85c2417a5c35fded11ae00d506502327886#diff-b9cfc7f2cdf78a7f4b91a753d10865a2，具体原因 @benjycui

**Comment by silentcloud** [comment]
@paranoidjk @warmhug fix 只能一部分，手动要改错误太多了，好几百，一起搞吧

分支 antd-tool-16

**Comment by paranoidjk** [comment]
好，可以按组件认领，避免大家工作重复

**Comment by silentcloud** [comment]
@paranoidjk 你先帮忙改 @pingan1927 这些 

![image](https://cloud.githubusercontent.com/assets/1698185/22101522/c8c5aa50-de6e-11e6-9958-5a8352df6195.png)

**Comment by paranoidjk** [comment]
@silentcloud ok

**Comment by paranoidjk** [comment]
@silentcloud 
`Checkbox` `Flex` `ImagePicker` `InputItem` `List` `Menu` `Radio` `SearchBar` `TextareaItem` 这部分done。 see #736
