### ISSUE TITLE
希望能有明确的前端规范，供大家参考

### ISSUE THREAD

**Issue by dingyiming** [ant-design/ant-design-mobile#75]
*  在ant-design中有提到一些代码规范，不过都比较笼统

*  已经看到wiki里有了less变量的命名规范，希望能进一步对外开放前端规范来更好地帮助大家融合ant-design-mobile

*  然后是希望能更进一步开源基于ant-design-mobile的技术方案，更好地让其落地，用起来也会顺畅些

*  谢谢

**Comment by warmhug** [comment]
请问你说的 规范，指的具体是哪些？希望说的更具体点~

**Comment by dingyiming** [comment]
哦哦，就是在进行ant-design-mobile开发和使用ant-design-mobile开发时，团队所去遵循的前端规范，包括，CSS规范，JS规范，HTML规范，这一类，或者说是否遵循现有的某种规范来开发，类似已经在wiki中的less变量命名规范这种。
然后，进一步的就是基于ant-design-mobile上面，对于手机前端开发是否也会沉淀下一些注意点，值得进一步分享经验，比如以什么样的标准去定义或划分组件，以什么样的准则去新建、开发、完善组件，希望能更加理解ant-design-mobile的经验与态度一些。
因为看ant-design-mobile已经有了一套风格，但相信要具体落地，肯定还有更细致的约束来明确开发工作，也肯定需要有一套方案来规范。

**Comment by yiminghe** [comment]
暂缓
