### ISSUE TITLE
这是toast样式出现问题了吗？

### ISSUE THREAD

**Issue by canfoo** [ant-design/ant-design-mobile#750]
![to](https://cloud.githubusercontent.com/assets/16999086/22104793/ecb0578c-de7b-11e6-9ea8-fa12f35e1ea7.png)

**Comment by canfoo** [comment]
按照introduce.md里面的步骤将ant-design引入到我自己项目中，试了toast，出现上面图片显示的问题，这是样式没有成功引进来吗？感谢回答～

**Comment by paranoidjk** [comment]
可能是字体没加载成功，看下console里面的报错

**Comment by paranoidjk** [comment]
某些域名可能访问不到alicdn， 如果确认是字体请求被block，
请参考这个本地部署指南 https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

**Comment by canfoo** [comment]
谢谢，确实是字体没有加载进来～

**Comment by paranoidjk** [comment]
cc @warmhug @silentcloud 

在Wiki的Faq里面加上这个问题，然后提issue的模板里面给出Faq的链接怎样？
一些常见通用，有模式的答疑可以沉淀下来

**Comment by warmhug** [comment]
加在 wiki 的 FAQ 文档里吧 @paranoidjk

**Comment by paranoidjk** [comment]
done. https://github.com/ant-design/ant-design-mobile/wiki/FAQ
