### ISSUE TITLE
Web 环境，Flex 不支持Android 4.4.4 以下版本

### ISSUE THREAD

**Issue by fanmingfei** [ant-design/ant-design-mobile#751]
没有支持旧版的Flex，09版的。

**Comment by warmhug** [comment]
用的是自动工具处理，https://github.com/ant-tool/atool-build/blob/e4bd2959689b6a95cb5c1c854a5db8c98676bdb3/src/getWebpackCommonConfig.js#L177 你可以在自己项目里单独设置下

**Comment by fanmingfei** [comment]
@warmhug 其实我就是想问问 如何支持...需要引用新的包吗？还是有类似工具但是没开启。或者推荐一个包。

**Comment by fanmingfei** [comment]
@warmhug 我想支持的是4.4.4 以下。而不是 4.4以下。

**Comment by pingan1927** [comment]
`autoprefixer`这个模块会在构建时帮助我们处理兼容写法，研究下

**Comment by warmhug** [comment]
抱歉，官方不提供旧版 Flex 支持了，实在需要，麻烦自行修改实现。
