### ISSUE TITLE
mocha+enzyme+webpack 测试antd-mobile组件，出现找不到组件css的错误

### ISSUE THREAD

**Issue by donnydfwx** [ant-design/ant-design-mobile#752]
#### 本地环境

- antd-mobile 版本：0.9.10
- 浏览器 (或标明是 react-native) 及其版本：chrome最新版
- 运行环境及其版本：Mac, node最新版

#### 你做了什么？
- 用mocha和enzyme测试Tabs组件

- 测试代码：
```javascript
  import React from 'react'
  import { expect } from 'chai'
  import { shallow } from 'enzyme'
  import { Tabs } from 'antd-mobile'

  describe ("enzyme example", function() {
    it ("use Tabs component", function() {
      const wrapper = shallow(<Tabs />)
      expect(wrapper.find('.foo')).to.have.length(0)
    })
  })
```
- 启动运行：
mocha  test/.setup.js test/**/*-test.js

#### 你期待的结果是：
- 测试通过

#### 实际上的结果：
- Error: Cannot find module 'antd-mobile/lib/tabs/style/css'

#### 备注
1. Tabs组件在项目中是可以正常引入，不会出现找不到css问题。只有在mocha命令下才会出现
2. 将Tabs组件的引入方式改成 import Tabs from 'antd-mobile/lib/tabs', 出现以下错误
![image](https://cloud.githubusercontent.com/assets/8174685/22134999/4b29f0f4-df06-11e6-9640-f004d955c040.png)

**Comment by warmhug** [comment]
确认使用了 babel-plugin-import

**Comment by donnydfwx** [comment]
@warmhug  使用了，组件都可以正常引用。还需提供什么信息？

**Comment by warmhug** [comment]
@sorrycc 帮忙看下

**Comment by sorrycc** [comment]
babel 没配对吧，JSX 都没解析成功。

**Comment by silentcloud** [comment]
@donnydfwx web 版本测试纯 mocha，没办法配置 webpack 的 extensions，你可以改用 karma 或者 https://github.com/ant-tool/atool-test

**Comment by zoujianliang94** [comment]
@eastling 
兄弟这个问题是怎么解决的

**Comment by OPY-bbt** [comment]
@eastling  问题解决了嘛

**Comment by paranoidjk** [comment]
@silentcloud 到官方sample里面加一个业务代码测试配置的例子？

**Comment by OPY-bbt** [comment]
在package.json 中 jest中加入
"moduleFileExtensions": [
      "web.js",
      "js",
      "jsx",
      "json"
 ],
主要是web.js；antd-mobile 不同于 antd，以web.js结尾。

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/.jest.web.json#L2

**Comment by GZWZC** [comment]
@OPY-bbt 
hello 你的意思是把mocha->转换为jest吗

**Comment by silentcloud** [comment]
@GZWZC  mocha 的话，看我上面的回复

**Comment by ccicc** [comment]
https://leozdgao.me/modern-karma/  这里有篇帖子，使用了karma可以解决
