### ISSUE TITLE
List 组件在服务端渲染场景中的问题

### ISSUE THREAD

**Issue by inJs** [ant-design/ant-design-mobile#757]
#### 本地环境

- antd-mobile 版本： 0.9.14
- 浏览器 (或标明是 react-native) 及其版本：chrome 55.0.2883.95 (64-bit)
- 运行环境及其版本：node 6.9.2 dev

#### 你做了什么？
引入 lib/list/index.web

#### 你期待的结果是：

无 react-native 依赖（因为指明是引入 .web）

#### 实际上的结果：
cannot find module 'react-native'

**Comment by warmhug** [comment]
关联 #602 。 确认下这个是否只是「在服务端渲染场景」有问题？

**Comment by inJs** [comment]
@warmhug 将 lib/list 下 import Item from './ListItem' ===》  import Item from './ListItem.web'; 即可吧？代码已 pull request .

**Comment by inJs** [comment]
@warmhug 这个应该只能在服务端渲染的场景下会“出现”的问题吧？ 目前 构建服务器并没有报错， node server 启动时会报这个错。

**Comment by warmhug** [comment]
PR 暂时先不关闭，issue 先关掉
