### ISSUE TITLE
Picker 省市区三列越向下滑, 越对不齐

### ISSUE THREAD

**Issue by wv1124** [ant-design/ant-design-mobile#759]
Picker 省市区三列越向下滑, 越对不齐, web方式引用

http://oepspd8cd.bkt.clouddn.com/2017-01-22-074308.jpg

**Comment by warmhug** [comment]
调试确认下没有其他样式扰乱这个。官方 demo 无此问题。

**Comment by silentcloud** [comment]
记得这个问题之前提过，貌似已经修了的吧 @warmhug

**Comment by paranoidjk** [comment]
@wv1124 请参考这个给一个可复现的demo： https://codepen.io/paranoidjk/pen/BpZrjQ

**Comment by wv1124** [comment]
新版本是好的, 我用的0.8.3
