### ISSUE TITLE
请问，在.js文件中使用相对路径，解析不正确，该如何解决，谢谢。

### ISSUE THREAD

**Issue by rurusgit** [ant-design/ant-design-mobile#762]
#### 本地环境

win10

- antd-mobile 版本：0.9.14
- 浏览器 (或标明是 react-native) 及其版本：Chrome
- 运行环境及其版本：nodejs + webpack + atools

#### 你做了什么？

在.js文件中使用相对路径，例如 img src='../images/a.png'

#### 你期待的结果是：

能够正确解析相对路径

#### 实际上的结果：

解析相对路径不正确，必须使用绝对路径。

**Comment by silentcloud** [comment]
@rurusgit  require

**Comment by rurusgit** [comment]
@silentcloud 多谢，require和import都可以吧？

**Comment by paranoidjk** [comment]
@rurusgit  webpack不会解析你的html，require和import内联图片是`webpack url-loader`所做的事情

非Antd相关的问题请上： https://segmentfault.com/
Antd使用相关请上： https://segmentfault.com/t/antd
