### ISSUE TITLE
React Native的TouchableOpacity组件中嵌套antd-mobile的View点击问题

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#769]
#### 本地环境

- antd-mobile 版本：1.0.0-alpha.33
- 浏览器 (或标明是 react-native) 及其版本：0.39.2
- 运行环境及其版本：mac

#### 你做了什么？
React Native的TouchableOpacity组件中嵌套antd-mobile的View

#### 你期待的结果是：
可以正常点击

#### 实际上的结果：
View区域中的内容无法点击，View之外TouchableOpacity之中的内容可以点击

**Comment by liubin1023** [comment]
如果把View组件换成Text组件就没有嵌套无法点击的问题

**Comment by silentcloud** [comment]
View 用的 RN 官方的，理论上应该没问题

**Comment by liubin1023** [comment]
![image](https://cloud.githubusercontent.com/assets/6219316/22277669/60afa7b6-e2f8-11e6-93f1-4039177e4b38.png)

**Comment by silentcloud** [comment]
@liubin1023  Flex.Item 组件已经用 `TouchableWithoutFeedback` 包裹了， https://github.com/ant-design/ant-design-mobile/blob/master/components/flex/FlexItem.tsx#L15

**Comment by liubin1023** [comment]
@silentcloud 如果增加长按事件怎么办？

**Comment by silentcloud** [comment]
@liubin1023  要改造 FlexItem  这个组件

**Comment by liubin1023** [comment]
@silentcloud 这个要等1.0发布吗，大概几号发布？

**Comment by silentcloud** [comment]
@liubin1023 正式版 20号发布，如果你等不及，我可以先发个 alpha

**Comment by liubin1023** [comment]
@silentcloud  十分感谢

**Comment by warmhug** [comment]
这样修改可能引起其他使用 flex 的组件问题、比如 https://github.com/ant-design/ant-design-mobile/pull/756

**Comment by silentcloud** [comment]
@liubin1023 @warmhug 还是先暂时改成内置，不然有些组件不好处理（比如 Grid 单个 Item 不能实现满点击），现在改成内置的 touchableWithoutFeedback 支持更多原生 prop

**Comment by liubin1023** [comment]
@silentcloud  
![image](https://cloud.githubusercontent.com/assets/6219316/23007229/365a6676-f442-11e6-8c14-45dc93767ea7.png)
无点击效果
方法无触发

![image](https://cloud.githubusercontent.com/assets/6219316/23007251/57add45c-f442-11e6-8c5a-0e4aaf213cf6.png)
