### ISSUE TITLE
listview 滑动的某个位置，进入下个页面，再返回到listview页面，listview回到头部

### ISSUE THREAD

**Issue by ninjai001** [ant-design/ant-design-mobile#770]
listview 滑动的某个位置，
进入下个页面，再返回到listview页面，listview回到头部；
返回之后我不对state做更改，但是listview还是回到了头部
不知道这个问题如何解决

**Comment by warmhug** [comment]
关联 #541 ，麻烦先搜索下之前有没提过类似问题的 issue ，谢谢
