### ISSUE TITLE
ListView的scrollTo能有动画吗?

### ISSUE THREAD

**Issue by Liuthx** [ant-design/ant-design-mobile#772]
#### 本地环境MacOS

- antd-mobile 版本：0.9.14
- 浏览器 (或标明是 react-native) 及其版本：chrome

#### 你做了什么？

使用ListView的scrollTo函数, 可以正常滚动, 但动画无效
`scrollTo: function (left, top, animate, zoom, callback)` animate参数设置为true无效
#### 你期待的结果是：
滚动能有动画

#### 实际上的结果：
没有动画

**Comment by paranoidjk** [comment]
web 版的 ListView 调用的实际是 `window.scrollTo`,  所以只支持  `scrollTo(x-coord,y-coord )`
