### ISSUE TITLE
Card 组件不能点击？

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#773]
如题

**Comment by silentcloud** [comment]
放在 extra 里或者 content 里

`content={<div onClick />}`

**Comment by liubin1023** [comment]
@silentcloud 
如果想让整个Card都是可以点击的怎么办

**Comment by silentcloud** [comment]
@liubin1023 master 已经添加了整个 card 可点击的支持，等发布

**Comment by superlbr** [comment]
@silentcloud  让整个card可以点击，我该怎么用，有示例吗

**Comment by silentcloud** [comment]
@superlbr `<Card onClic={} />`

**Comment by superlbr** [comment]
@silentcloud click事件完全没反应。。。

**Comment by superlbr** [comment]
https://codepen.io/superlbr/pen/KqPwZQ?editors=1111

**Comment by paranoidjk** [comment]
~~`onClick={console.log('hello');}`~~  --> `onClick={() => console.log('hello');}` 

onClick should a function, suggest you learn react or javascript syntax at first.

**Comment by superlbr** [comment]
@paranoidjk works on web , but not react-native way

**Comment by silentcloud** [comment]
@superlbr react-native 自己在外层加一个 TouchableWithoutFeedback

**Comment by superlbr** [comment]
@silentcloud  That' what I want, much thanks
