### ISSUE TITLE
server-rendering error

### ISSUE THREAD

**Issue by dreamjser** [ant-design/ant-design-mobile#775]
问题：使用antd-mobile时，server-rendering会报错，导致server-rendering失败。换成antd就可以正常运行。

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `App`

代码：

`import React, {Component} from 'react';`
`import ReactDOM from 'react-dom';`
`import Navbar from '../components/layouts/navbar';`
`import {Button} from 'antd-mobile';`

`class App extends Component{`
`render(){`
`const pathname = this.props.location.pathname;`
`return (`
`<div className="ixiao">`
`<Button type="primary"> 1111 </Button>`
`<div className="wrap">`
`{this.props.children}`
`</div>`
`<Navbar pathname = {pathname} />`
`</div>`
`)`
`}`
`}`

`export default App;`

antd-mobile版本：0.9.14
浏览器：最新版chrome
运行环境：centos 7.0

**Comment by paranoidjk** [comment]
@dreamjser 确认使用[babel-plugin-import](https://github.com/ant-design/babel-plugin-import)了吗？

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/602

**Comment by dreamjser** [comment]
@paranoidjk 用了，客户端可以成功渲染，只是在服务器端渲染会失败

**Comment by paranoidjk** [comment]
@dreamjser 
官方暂时没有正式支持服务端渲染， 你先试试如下引用？

```
import {Button} from 'antd-mobile/lib/button/index.web.js';
```

**Comment by dreamjser** [comment]
@paranoidjk OK，了解

**Comment by warmhug** [comment]
关联 #757 #758

这里先关闭。我会在文档里添加下注释。
