### ISSUE TITLE
TabBar 需要可以设置barIcon size的参数

### ISSUE THREAD

**Issue by rendongsc** [ant-design/ant-design-mobile#776]
react-native，版本：1.0.0-beta.2。
使用react-native-vector-icons图标，antd-mobile默认尺寸是28*28，图标显示特别大。
![20170128153817](https://cloud.githubusercontent.com/assets/12553638/22395142/c46d83d0-e56f-11e6-96aa-215899a409dd.png)
希望可以增加一个参数，可以设置icon图片的大小。

**Comment by silentcloud** [comment]
iOS 用的 RN 官方 TabBar，没有 icon size 的 prop，建议调整 icon 大小

**Comment by rendongsc** [comment]
TabBar icon 用的是image，调整icon的大小不起作用。

**Comment by T-o-T** [comment]
我用的是
    react-native，版本：1.0.0-beta.1
正好也在写TabBar，看到了这个问题。我试了一下，在ios模拟器Simulator中，设置Icon.getImageSource的尺寸是有作用的。

**Comment by rendongsc** [comment]
@T-o-T  我的是android环境。

**Comment by silentcloud** [comment]
@rendongsc 确实，iOS 应该没问题，android 是自实现的应该确实 有问题，我给 android 单独处理一下
