### ISSUE TITLE
slider refactor

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#777]
## current problem
- too big for common usage: http://facebook.github.io/react-native/docs/slider.html

## solution
- split tooltip/range functionality from simple usage

```
import {Slider, Ranger, SliderTooltipPlugin} from 'antd-mobile'

<Slider plugin={[TooltipPlugin]}>

<Ranger plugin={[TooltipPlugin]}>
```

**Comment by benjycui** [comment]
不兼容升级，所以要在 1.0 之前搞完。

**Comment by paranoidjk** [comment]
@benjycui rc这个group我没权限，给我加个？顺便看下这个pr https://github.com/react-component/select/pull/162

**Comment by benjycui** [comment]
More: `createSliderWithTooltip` http://react-component.github.io/slider/examples/handle.html

**Comment by paranoidjk** [comment]
@yiminghe  @benjycui   https://github.com/ant-design/ant-design-mobile/pull/805
 
- `plugin=[]`数组有什么必要？还有其他插件？
- 如果就只有`ToolTip`可插拔，那么也没必要依赖注入，直接一个`props.showToolTip=boolean`的开关更友好点?

**Comment by yiminghe** [comment]
需求 import { Slider } from 'antd-mobile' 不载入 range 和 tooltip 的代码

**Comment by paranoidjk** [comment]
@yiminghe ok，这个可以做到，代码实际上已经分离了
@warmhug 看下这个需求，在  https://github.com/ant-design/ant-design-mobile/pull/805 我会把`range`从`slider`里面拆出来，新增一个独立组件

**Comment by warmhug** [comment]
Ok, get

**Comment by benjycui** [comment]
Tooltip 支持不是以插件的形式而是 HOC 的形式存在，see: https://github.com/react-component/slider#createsliderwithtooltipslider--range--reactcomponent

**Comment by benjycui** [comment]
也可以按需加载 https://github.com/react-component/slider/tree/master/src

```jsx
import createSliderWithTooltip from 'rc-slider/lib/createSliderWithTooltip'
```
