### ISSUE TITLE
Modal组件中不能嵌套Flex吗

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#778]
#### 本地环境

- antd-mobile 版本：1.0.0-alpha.42
- 浏览器 (或标明是 react-native) 及其版本：react-native 0.39.2 
- 运行环境及其版本：android

#### 你做了什么？
如题

#### 你期待的结果是：
正常显示

#### 实际上的结果：
使用了Flex后Modal弹出后占全屏

#### 可重现的在线演示

![image](https://cloud.githubusercontent.com/assets/6219316/22617498/96d605fe-eb01-11e6-876d-c3dbd6e609ab.png)

**Comment by liubin1023** [comment]
还有一个问题，Modal组件中使用Stepper一样有问题，加号减号之间的数字不显示

**Comment by silentcloud** [comment]
@liubin1023 占全屏，是因为你的 transparent 不是 `true` 吧？Stepper 我这边也 ok 的

![image](https://cloud.githubusercontent.com/assets/1698185/22676697/fa74dfb8-ed27-11e6-908f-63467303f25a.png)

**Comment by liubin1023** [comment]
@silentcloud 
一样的代码
![image](https://cloud.githubusercontent.com/assets/6219316/22684537/b74bcf46-ed57-11e6-9052-f80da644ef59.png)
直接就报错了。。。
![image](https://cloud.githubusercontent.com/assets/6219316/22684551/c0b97146-ed57-11e6-8113-46379a70f482.png)

**Comment by silentcloud** [comment]
@liubin1023 恩 这个版本重现问题了，我排查一下
