### ISSUE TITLE
InputItem组件在RN环境下警告

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#779]
#### 本地环境

- antd-mobile 版本：1.0.0-alpha.42
- 浏览器 (或标明是 react-native) 及其版本：0.39.2
- 运行环境及其版本：android RN

#### 你做了什么？
![image](https://cloud.githubusercontent.com/assets/6219316/22617960/f819a078-eb0b-11e6-93ba-a638554778f7.png)

![image](https://cloud.githubusercontent.com/assets/6219316/22617974/3b1c4da8-eb0c-11e6-9238-4fea55d116db.png)

#### 你期待的结果是：
正常使用没有警告，界面上显示时可以根据value的值进行显示

#### 实际上的结果：
![image](https://cloud.githubusercontent.com/assets/6219316/22617949/be3fa0be-eb0b-11e6-8e62-abe6b9e621ea.png)

**Comment by paranoidjk** [comment]
value是个`string`
