### ISSUE TITLE
高清需求修改

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design-mobile#78]
mobile.ant.design/kitchen-sink/ ， demo http://yiminghe.me/lab/playground/2016-exams/6.html

px 转 rem 工具使用 https://github.com/ant-tool/postcss-plugin-px2rem

设计按照 750 设计。kitchen-sink 使用 anima 高清方案。pc 嵌入时外层 transform scale(0.5) 为 375 宽度.

**Comment by pingan1927** [comment]
这个我一并改了吧。本地已经改好了
