### ISSUE TITLE
【RN】水平布局 Steps

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#780]
#### 本地环境

- antd-mobile 版本：1.0.0-alpha.42
- 浏览器 (或标明是 react-native) 及其版本：0.39.2
- 运行环境及其版本：android

#### 你做了什么？
在RN中使用Steps组件

#### 你期待的结果是：
可以水平布局

#### 实际上的结果：
只能垂直布局

**Comment by silentcloud** [comment]
@liubin1023 目前 RN 暂时没有实现水平方向的布局

**Comment by liubin1023** [comment]
@silentcloud 在1.0正式版发布时会实现吗？

**Comment by paranoidjk** [comment]
@liubin1023 并没有，参见1.0更新日志 https://mobile.ant.design/changelog#1.0.0

**Comment by paranoidjk** [comment]
使用少，优先级低，暂时不做，后续还有需求再打开。

另外，欢迎 PR。
