### ISSUE TITLE
快一个月没更新了

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design-mobile#782]
是否因为春节

**Comment by paranoidjk** [comment]
1.0一直在beta中的，请期待~ https://github.com/ant-design/ant-design-mobile/releases

@warmhug 我们有固定的版本迭代计划吗？

**Comment by silentcloud** [comment]
1.0 初步定在 2月20

**Comment by paranoidjk** [comment]
@silentcloud 恩，这个我知道的。我的意思是要不要保持类似每周一个 patch release 这样的迭代？

**Comment by warmhug** [comment]
可以的，有 patch 的话
