### ISSUE TITLE
关于antd-mobile的主题样式更改

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design-mobile#783]
使用的最新版dva-cli 构建的项目，但是我想更改antd-mobile的主题样式
package.json代码如下，并没有生效
```
{
  "private": true,
  "dependencies": {
    "antd-mobile": "^0.9.0",
    "babel-runtime": "^6.20.0",
    "dva": "^1.0.0",
    "react": "^15.1.0",
    "react-dom": "^15.1.0"
  },
  "devDependencies": {
    "babel-plugin-dva-hmr": "^0.2.1",
    "babel-plugin-import": "^1.0.1",
    "babel-plugin-transform-runtime": "^6.15.0",
    "expect": "^1.20.2",
    "redbox-react": "^1.2.10",
    "roadhog": "^0.3.2"
  },
  "scripts": {
    "start": "roadhog server",
    "build": "roadhog build",
    "test": "roadhog test"
  }
  ,
  "theme": {
    "@brand-primary": "#64bfae"
  }
}
```

https://github.com/ant-design/ant-design/issues/4786

**Comment by paranoidjk** [comment]
@ddcat1115 关联 https://github.com/ant-design/ant-design-mobile/issues/475

**Comment by paranoidjk** [comment]
@ddcat1115 是`roadhug`吗？ 参考这个commit试下 https://github.com/dvajs/dva-example-user-dashboard/commit/d6da33b3a6e18eb7f003752a4b00b5a660747c31

**Comment by warmhug** [comment]
theme 配置需要使用 https://github.com/ant-design/antd-tools 或 https://github.com/ant-tool/atool-build 工具，或者参考下在自己工具里进行实现。

roadhog 也支持 theme 设置，不过这个工具目前只适合 pc 项目，不适合 mobile 使用，参考 
https://github.com/sorrycc/blog/issues/17

**Comment by paranoidjk** [comment]
官方Demo已增加与Roadhog配合使用的demo

https://github.com/ant-design/antd-mobile-samples/tree/master/antm-roadhog

包括：
- svg 配置
- rem 配置
- theme 配置

**Comment by paranoidjk** [comment]
关联 https://github.com/sorrycc/roadhog/issues/136
