### ISSUE TITLE
CheckboxItem初始未选中的不能切换选中状态

### ISSUE THREAD

**Issue by rendongsc** [ant-design/ant-design-mobile#784]
#### 本地环境

- antd-mobile 版本：react-native
- 浏览器 (或标明是 react-native) 及其版本：1.0.0-beta.2
- 运行环境及其版本：android 4.4

#### 问题描述
- 官方的BasicCheckboxExample可以重现问题（ <CheckboxItem>物料铺设</CheckboxItem>）。
- 如果初始状态checked=true，是OK的。
- onChange的event.target.checked始终为true。

**Comment by paranoidjk** [comment]
@rendongsc 是 RN 的组件有问题吗？ 贴一个简单的示例代码吧，你描述的太混乱了没法帮你

**Comment by rendongsc** [comment]
@paranoidjk 写的稍微多了些，简化一下：
1、RN的CheckboxItem组件，版本：1.0.0-beta.2
2、重现问题示例：官方demo（ant-design-mobile\components\checkbox\demo）
