### ISSUE TITLE
Stepper组件为啥突然不好使了？

### ISSUE THREAD

**Issue by StarryF** [ant-design/ant-design-mobile#785]
#### 本地环境

- antd-mobile 版本：0.9.13
- 浏览器 (或标明是 react-native) 及其版本：chrome
- 运行环境及其版本：node

#### 你做了什么？
```
constructor(props) {
    super(props)
    this.state = {
      num: 0
    }
  }

  onNumChange = (num) => {
    console.log(num)
    this.setState({num})
  }

  render() {
    return (
      <div>
        <List>
          <Item><Stepper
              showNumber 
              min={0} 
              value={this.state.num} 
              onChange={this.onNumChange} /></Item>         
        </List>
      </div>
    )
  }
```

#### 你期待的结果是：
点击一次，每次渐变为1，像官网那样

#### 实际上的结果：
Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

![image](https://cloud.githubusercontent.com/assets/8469660/22721722/57dba568-eded-11e6-8d8e-e95b946c47ae.png)

![image](https://cloud.githubusercontent.com/assets/8469660/22721693/42187a62-eded-11e6-8c6b-8438f90b35f7.png)

点击一次会触发两次事件。

**Comment by silentcloud** [comment]
stepper 支持连续点击的

**Comment by StarryF** [comment]
@silentcloud 我只是点击了一下，不算连续点击的吧，每次点击的step都是默认值=1。我现在需要以1为单位递增或递减，而不是点一下➕，就变成了2。

**Comment by paranoidjk** [comment]
@StarryF 
could you give us a re-producible online demo like this http://codepen.io/paranoidjk/pen/WRLoVq ?
thanks~

**Comment by Sdoy** [comment]
同样的问题,
chrome:版本 56.0.2924.87 (64-bit)

**Comment by paranoidjk** [comment]
@Sdoy chrome版本和你一样，我这边试了`0.9.14`和`1.0.beta-3`都无法复现，给我们提供一个可复现的demo？http://codepen.io/paranoidjk/pen/WRLoVq  谢谢

**Comment by bktoky** [comment]
android 版本有问题，首页的demo就可以复现

**Comment by pwz1985** [comment]
@paranoidjk   

android 版本有问题，首页的demo就可以复现   +1

**Comment by paranoidjk** [comment]
@bktoky @pwz1985  手边现在没带android机.... 请问是说RN的组件在Android上有bug，还是Web的组件在Android浏览器上有bug？

**Comment by pwz1985** [comment]
RN的组件在Android上有bug
@paranoidjk

**Comment by RByers** [comment]
Sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  You can probably fix this by adding an appropriate `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action).

**Comment by silentcloud** [comment]
web chrome 模拟 android 和 rn android 版本有问题，我这边来 check

**Comment by paranoidjk** [comment]
@silentcloud 周末看了下，android下有，chrome没有，android下开启debug js remote就没法复现了，可能还是setTimeout的逻辑有问题，btw，发现另外一个bug https://github.com/react-component/input-number/issues/42

**Comment by silentcloud** [comment]
这个确认问题了，是连续点按的时候，settimeout 延迟太小，造成的，speed 改大一点就 ok 了，我提个 pr 修复一下

**Comment by silentcloud** [comment]
重装一下 node_modules ，已解决

**Comment by freestyle21** [comment]
现在 `npm` 拉到的 `antd-mobile 1.0.0`版本，依赖的 `rc-input-number`还是 ^2.8.8 ，能不能更新下？

**Comment by paranoidjk** [comment]
@freestyle21 https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L44
