### ISSUE TITLE
求官方提供的mobile  web实例https://mobile.ant.design/kitchen-sink/的代码供学习

### ISSUE THREAD

**Issue by liangxp** [ant-design/ant-design-mobile#786]
官方提供的实例在线访问地址为https://mobile.ant.design/kitchen-sink/
是否有对应的GitHub地址？如果有，麻烦分享下，项目参考学习使用

**Comment by warmhug** [comment]
官方的网站代码在这里 https://github.com/ant-design/ant-design-mobile/tree/master/site/kitchen
