### ISSUE TITLE
InputItem 手动触发blur

### ISSUE THREAD

**Issue by jsers** [ant-design/ant-design-mobile#788]
#### 本地环境

- antd-mobile 版本：0.9.14
- 浏览器 (或标明是 react-native) 及其版本：react-native@0.40.0
- 运行环境及其版本：IOS 10.2

#### 问题描述

我希望外部手动触发 InputItem 的blur来关闭虚拟键盘，看目前貌似没办法实现。
可否让InputItem本身支持，或是把TextInput暴露出来

**Comment by warmhug** [comment]
通过 ref 获取到 input 元素

**Comment by jsers** [comment]
@warmhug 
通过ref只能取到 InputItem，然而对 InputItem.blur() 就报错了，InputItem并没有挂载这个方法
![image](https://cloud.githubusercontent.com/assets/7424634/22735714/e5fd8b3e-ee35-11e6-9b67-b0559829ce1c.png)

**Comment by warmhug** [comment]
取到 inputItem 再 refs.input

**Comment by pengshaosu** [comment]
> @warmhug
> 通过ref只能取到 InputItem，然而对 InputItem.blur() 就报错了，InputItem并没有挂载这个方法
> ![image](https://cloud.githubusercontent.com/assets/7424634/22735714/e5fd8b3e-ee35-11e6-9b67-b0559829ce1c.png)

@jsers 
你通过这种方式实现了关闭虚拟键盘了吗？
多谢

**Comment by youngList** [comment]
所以说blur()到底是能不能用？通过ref没能找到input呀。。

**Comment by youngList** [comment]
现在出现了blur()调用成功（在onBlur事件里边有执行），但是焦点没有消失，antd-mobile： 2.2.9
