### ISSUE TITLE
babel-plugin-import同时加载antd和antd-mobile引起的样式错乱问题

### ISSUE THREAD

**Issue by aimaodeyuer** [ant-design/ant-design-mobile#789]
#### 本地环境

- antd-mobile 版本：0.9.14
- 浏览器 (或标明是 react-native) 及其版本：chrome
- 运行环境及其版本：mac 10.12

#### 你做了什么？

同时引入 antd 和ant-mobile 用babel-plugin-import 按需加载
.babelrc代码
```{
  "plugins": [
    "transform-runtime",
    "transform-decorators-legacy",
    ["import",
            [
            {
               "libraryName": "antd",
               "libraryDirectory": "lib",
               "style":true
             },
             {
               "libraryName": "antd-mobile",
               "libraryDirectory": "lib",
               "style":"css"
             }
           ]
          ]
  ],
  "presets": [
    "es2015",
    "react",
    "stage-0",
    "react-hmre"
  ]
}

#### 你期待的结果是：

样式正常显示

#### 实际上的结果：

样式崩了，字体都大了好几号

#### 可重现的在线演示

**Comment by warmhug** [comment]
antd-mobile 需要高清方案设置，仔细参考下文档。

关联 #657 。

**Comment by paranoidjk** [comment]
@aimaodeyuer 链接： [wiki](https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE) 

@warmhug wiki入口太深，这个加到快速上手里面？

**Comment by aimaodeyuer** [comment]
@warmhug 我是想在pc端也用antd-mobile做一些手机端模拟组件，结果就是组件都放大了好几倍，这个高清方案应该是用在移动端的吧。能解决我这个问题吗？
![image](https://cloud.githubusercontent.com/assets/12092562/22766902/0a71d862-eeb3-11e6-810c-09cffeb6250b.png)

**Comment by warmhug** [comment]
不建议在 pc 上用 antd-mobile ，实在需要，自己研究修改下工具、把字体处理成正常大小即可。

**Comment by aimaodeyuer** [comment]
@warmhug 问题已经解决，在weback里面加了postcss px转成rem了，勉强用下吧。在pc端用antd-mobile是为了拖拽组件放在模拟移动端大小的画布上布局。感谢！
