### ISSUE TITLE
Carousel 组件在切换的过程中render会卡死

### ISSUE THREAD

**Issue by nikogu** [ant-design/ant-design-mobile#79]
// -> 种族歧视 ？

#### 本地环境
- antd-mobile 版本：0.7.2
- 操作系统及其版本：macos 10.11.1
- 浏览器及其版本： Chrome 51.0.2704.106

#### 现象描述
Carousel 组件切换的过程中（动画执行的时候），如果触发render（其它组件改变），会导致 Carousel卡死（不能切换），原因猜测是：componentWillUnmount 未对动画清理导致

#### 可重现的在线演示
没得，重现方式就是在 Carousel 执行动画（autoplay比较容易操作）的时候 render，比如改其它组件的state

**Comment by nikogu** [comment]
@silentcloud

**Comment by jljsj33** [comment]
这鬼东西有新bug了。。。react-slick 坑中大坑

**Comment by jljsj33** [comment]
你有空写个 rc-slick 呼？？@nikogu。。。

**Comment by nikogu** [comment]
额，才看到 🐒

**Comment by liqi07** [comment]
@nikogu 提个PR？

**Comment by 214132049** [comment]
这个走马灯   里面的内容 不能是从后台获取的吗？

**Comment by liqi07** [comment]
@jljsj33 在跟进底层依赖的rc-slick ，麻烦 @foriacus 跟进处理下Carousel 组件
