### ISSUE TITLE
List组件 换行问题

### ISSUE THREAD

**Issue by jsers** [ant-design/ant-design-mobile#790]
#### 本地环境

- antd-mobile 版本：0.9.14
- 浏览器 (或标明是 react-native) 及其版本：react-native@0.40.0
- 运行环境及其版本：IOS 10.2

#### 问题描述
List.Item的wrap multipleLine 都开启，但是没有如期的换行，还是被隐藏省略掉

![image](https://cloud.githubusercontent.com/assets/7424634/22735568/3a9c6b66-ee35-11e6-9a67-7f77414a317d.png)
![image](https://cloud.githubusercontent.com/assets/7424634/22735575/444faf1a-ee35-11e6-88f7-4f4bb30bde6f.png)

**Comment by warmhug** [comment]
先看下官方 demo 有没你说的问题。若没有、给出你自己代码的错误演示

**Comment by paranoidjk** [comment]
刚跑了ios的demo，没有问题。

**Comment by jsers** [comment]
@warmhug 更新了代码和效果图

**Comment by paranoidjk** [comment]
@jsers 我这边测试没有问题，将`antd-mobile`升级至`1.0.0-beta.2`试试？

**Comment by jsers** [comment]
既然没办法复现，也许是版本问题。
暂时先关了吧。
