### ISSUE TITLE
Requiring unknown module "antd-mobile/lib/nav-bar"

### ISSUE THREAD

**Issue by naWang1227** [ant-design/ant-design-mobile#791]
#### 本地环境

- antd-mobile 版本：0.9.4
- 浏览器 (或标明是 react-native) 及其版本：react-native
- 运行环境及其版本：android6.0

#### 你做了什么？
使用官网提供的MobileDemo，直接在index.android.js里面加入写入代码：
import { View, AppRegistry } from 'react-native';
import { NavBar } from 'antd-mobile';
import React from 'react';
import { createForm } from 'rc-form';

let MobileDemo = React.createClass({
  render() {
    return (<View style={{ marginTop: 20 }}>
       <NavBar leftContent="返回" mode="light" onLeftClick={() => console.log('onLeftClick')}
      rightContent={[<Icon key="0" type="search" />, <Icon key="1" type="ellipsis" />]}
    >NavBar</NavBar>
    </View>);
  }
});

MobileDemo = createForm()(MobileDemo);

AppRegistry.registerComponent('MobileDemo', () => MobileDemo);

#### 你期待的结果是：

运行“react-native run-android”命令，真机上显示报错。

#### 实际上的结果：

![screenshot_2017-02-08-18-20-16](https://cloud.githubusercontent.com/assets/25194203/22733550/29a388d8-ee2d-11e6-816b-236f8579136a.png)

报错信息：Requiring unknown module "antd-mobile/lib/nav-bar"

**Comment by paranoidjk** [comment]
`babel-plugin-import`正确配置了吗？

**Comment by warmhug** [comment]
NavBar 没有 RN 版本。麻烦仔细看下文档

![image](https://cloud.githubusercontent.com/assets/2011119/22734680/88f35b34-ee31-11e6-9e48-109000d83931.png)

**Comment by paranoidjk** [comment]
@warmhug 😅  还是像1.x这样加个placeholder比较好 https://github.com/ant-design/ant-design-mobile/blob/master/components/nav-bar/index.tsx

**Comment by naWang1227** [comment]
谢谢，原来是NavBar适用平台目前只支持web，不支持react-native。

**Comment by fjl716** [comment]
NavBar什么时候支持rn啊？

**Comment by silentcloud** [comment]
@fjl716 Navbar RN 下面不太常用啊，一般 RN 都有自己的 navigationbar 的，不管官方的还是 react-navigation 之类的
