### ISSUE TITLE
RN 0.4x 下 List.Item 带 onClick 时无点击高亮反馈

### ISSUE THREAD

**Issue by u0x01** [ant-design/ant-design-mobile#793]
- react native version: 0.41.2
- antd version: ^0.9.14
- OS and its version: iOS 10.2 / Android 6.0.1
and-mobile 的 demo 是有点击反馈的，但是我使用时 iOS / Android 下均无反馈，另外 Android 下长按时会有 红框error。

同时，样式显示也有异常，即使用 List 包裹 List.Item 时 Bottom 处会有两条线：
![simulator screen shot 2017 2 9 5 39 25](https://cloud.githubusercontent.com/assets/9703404/22758581/3a765110-ee8a-11e6-9b96-df2a06274d32.png)

这个是 and-mobile 的 demo，经测试有反馈：
![img_2446](https://cloud.githubusercontent.com/assets/9703404/22758637/885300fe-ee8a-11e6-8e68-efcb904c3210.PNG)

安卓下长按报错：
![wechatimg12](https://cloud.githubusercontent.com/assets/9703404/22759077/227ab78e-ee8c-11e6-97b7-a72d781e03ff.jpeg)

示例代码：

          <List>
            <List.Item
              thumb="https://zos.alipayobjects.com/rmsportal/UIqwcqpVsIjvyYZ.png"
              arrow="horizontal"
              onClick={() => {}}
            >H5 组件</List.Item>
            <List.Item
              thumb="https://zos.alipayobjects.com/rmsportal/lSsJiCJnOzSnBJG.png"
              arrow="horizontal"
              onClick={() => {}}
            >React Native 组件</List.Item>
          </List>

**Comment by silentcloud** [comment]
master 最新代码已经将 List.Item 内置的 touchable  移除了

**Comment by u0x01** [comment]
@silentcloud 我自己试了下外面包一个 touchablehighlight 也不行啊

**Comment by u0x01** [comment]
所以现在如果要加高亮反馈应该怎么做？

**Comment by silentcloud** [comment]
@u0x01 master 上的代码目前还没有发版本，所以应该是不生效的，要等个版本，或者发个 alpha？

**Comment by u0x01** [comment]
@silentcloud 好的呀，发alpha版本分支我就可以直接拉了。
另外，tabbarItem 的 icon 渲染能不能加render函数，如果要用SVG图标的话用不了（另开issue？）

**Comment by silentcloud** [comment]
u0x01 RN svg 不行的，web （1.0）的是支持 svg 的

**Comment by u0x01** [comment]
@silentcloud 所以我的意思是增加 renderIcon 这个参数，SVG可以自己去渲染。

**Comment by silentcloud** [comment]
@u0x01 RN（iOS） 目前是直接采用的 rn 官方的 TabBar

**Comment by u0x01** [comment]
这样啊，那只能自己实现个tabbar了。主要在RN里面用图片会有延迟感。

**Comment by silentcloud** [comment]
@u0x01 离线图片怎么会有延迟感？本地资源

**Comment by u0x01** [comment]
@silentcloud 部分低端 Android 机型会出现，即便关掉 Dev 模式

**Comment by u0x01** [comment]
@silentcloud alpha 分支啥时候发呀 😬

**Comment by silentcloud** [comment]
@u0x01 稍等还在改，发现不能单纯去掉 flex 的 touchable，影响到其他组件了，我正在将内置的 touchableWithoutFeedback 切换成 Highlight ，稍等

**Comment by u0x01** [comment]
感谢，公司新项目可以用上了 😄

**Comment by silentcloud** [comment]
@pingan1927 touchableWithoutFeedback 切换为 touchableHighLight

**Comment by u0x01** [comment]
1.0.0-beta3 已修复。

**Comment by pingan1927** [comment]
@silentcloud OK
