### ISSUE TITLE
Add Web PopupContainer

### ISSUE THREAD

**Issue by rendongsc** [ant-design/ant-design-mobile#794]
#### 本地环境

- 运行环境及其版本：RN组件，版本1.0.0-beta.2

````
showPopup = () => {
    Popup.show(this.getPopupContent()
      , {
        animationType: 'slide-up', maskClosable: true,
        onMaskClose: () => { }
      }
    );
  }
  getPopupContent = () => {
    return (
      <View>
        <ImagePicker
          onChange={this.handleFileChange}
          files={this.state.files}
        />
      </View>
    );
  }
````
![image](https://cloud.githubusercontent.com/assets/12553638/22772370/41c56788-eed7-11e6-98f9-480a8a671238.png)

**Comment by paranoidjk** [comment]
ios 10.2，`Image-Picker`放到 `Popup`里，每次setState都需要Popup `hide/show`一次 UI 才重新渲染

**Comment by silentcloud** [comment]
这种场景没办法使用 Popup.show 这种 api 形式的，需要使用 `lib/popup/PopupContainer` 的 component 形式来自定义实现 @rendongsc

**Comment by xttianma** [comment]
我也遇到这个问题, 使用popup,弹出对象不能使用函数式组件(因为它自身没有状态), 必须用react.component的组件. 
如何优化这个组件,可以支持函数式组件呢?

**Comment by paranoidjk** [comment]
@silentcloud popUp web 没有提供 popupContainer, 你要改这个吗？https://github.com/ant-design/ant-design-mobile/issues/1479

**Comment by silentcloud** [comment]
这个 issue 在这里跟踪吧 https://github.com/ant-design/ant-design-mobile/issues/1125
