### ISSUE TITLE
高清方案在iphone6 plus中出现问题

### ISSUE THREAD

**Issue by freestyle21** [ant-design/ant-design-mobile#796]
#### 本地环境

iphone6 plus

- antd-mobile 版本：0.9.14
- 浏览器 (或标明是 react-native) 及其版本：safari
- 运行环境及其版本：iphone6 plus

#### 你做了什么？

引入antd-mobile，同时引入高清配置方案代码段，[高清方案](https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-以上版本「高清」方案设置)

#### 你期待的结果是：

html 的 `font-size: 100px`

#### 实际上的结果：

html 的 `font-size: 150px`

原因是，window.devicePixelRatio 在 iphone5、iphone6 为 2 ，但是在 iphone6 plus中为 3，导致根元素 html 的 `font-size：150px`，页面样式乱了。

**Comment by warmhug** [comment]
这是正常的，你 html 元素的 css 设置是否有问题？

**Comment by freestyle21** [comment]
没有设置过 html 元素的 css 样式，页面 style 全部设置用 `rem`，当 html元素 fontSize=150px 时会导致 cascader 样式出现问题

**Comment by paranoidjk** [comment]
@freestyle21 
could you give us a re-producible online demo like this http://codepen.io/paranoidjk/pen/WRLoVq ?
thanks~

**Comment by warmhug** [comment]
> 页面 style 全部设置用 rem

建议源码用 px ，编译阶段用工具转为 rem . 参考高清方案文档

**Comment by paranoidjk** [comment]
@warmhug 这个最终结论是一样的， 只是谁来执行 `100px -> 1 rem` 的转换过程的问题，不应该是样式错乱的原因

另外我们的高清方案，3dpr就150px --> 1rem了，但开发者脑中可能还是100px ~ 1rem，这会不会有问题？

**Comment by warmhug** [comment]
不仔细理解，是可能会带来混淆。这个细节需要用户自己仔细理解下。

**Comment by paranoidjk** [comment]
Going to close this, if you have any further questions - please just ask, or feel free to open a issue :)

**Comment by warmhug** [comment]
关联 #683
