### ISSUE TITLE
使用了rn-topview的组件会导致react-native-router-flux Router重建

### ISSUE THREAD

**Issue by rendongsc** [ant-design/ant-design-mobile#797]
#### 本地环境

- antd-mobile 版本：RN 1.0.0-beta.2
- 运行环境及其版本：android 4.4

#### 问题描述
- 凡是使用了rn-topview的组件（Toast、ActionSheet、Popup）显示都会导致react-native-router-flux Router重建。
````
Toast.success('测试！');
````
![2](https://cloud.githubusercontent.com/assets/12553638/22808708/66989e18-ef68-11e6-9189-114c34b5543e.png)

**Comment by Lxxyx** [comment]
同样的问题

**Comment by silentcloud** [comment]
Toast 实现 api 形式的方式，目前是一种 hack（类似 rn 没有 js document.body.append），在调用的时候，app 的根会执行 setState 进行重新 render，目前是已知问题，没好的方案，如果想避免这个问题，那就只能直接使用 组件里面的 component 来自己实现 @rendongsc @Lxxyx

**Comment by silentcloud** [comment]
@rendongsc @Lxxyx ，这个问题已经在 rn-topview  里做了修复

**Comment by paranoidjk** [comment]
@silentcloud rn-topview 的代码没开源？

**Comment by Lxxyx** [comment]
@silentcloud 重新安装了，问题依旧。安装命令：`yarn add antd-mobile@latest`，并重新打包安装测试应用。

**Comment by rendongsc** [comment]
我也是 yarn add antd-mobile@latest，问题还是同样的！

**Comment by silentcloud** [comment]
@Lxxyx @rendongsc 确认一下本地安装后的 rn-topView 版本 @paranoidjk 这个没开源

**Comment by paranoidjk** [comment]
@silentcloud 钉我下发个repo地址我看看吧~

**Comment by rendongsc** [comment]
@paranoidjk  @Lxxyx 
OK了！
我先前没有这个：rm -rf node_modules/rn-topview

**Comment by Lxxyx** [comment]
rm -rf 后已正常。谢谢~

**Comment by yuche** [comment]
这个 issue 的问题在老版本的 `antd-mobile` 可以用 `react-native-router-flux` 的 `Actions.create` 方法解决。
ref: https://github.com/aksonov/react-native-router-flux/issues/768#issuecomment-223093731

`rn-topview` 的 re-render 问题新版本没有代码我不知道是如何解决的。但我觉得可以把 [AppComponent](https://facebook.github.io/react-native/docs/appregistry.html#registercomponent) 套在一个 [StaticContainer](https://github.com/reactjs/react-static-container) 里应该可以避免 re-render。算是一个思路吧。

另外给 `antd-mobile` 一个建议：

类似于 `Popup` 这样的组件可以返回一个带生命周期的 `React.Component` class：

- `render`方法返回 `null`；
-  `props` 和 `PopupContainer` 一样但多了一个 `visible`；
- `componentWillMount`  topview 生成一个带 `props` 的 `PopupContainer` 并缓存起来；
- `componentWillReceiveProps` update 之前缓存的 topview；
- `componentWillUnmount` 销毁 topview；
- `show` 和 `hide` 作为静态方法调用

这样 `PopupContainer` 就多了一层 `componentWillReceiveProps` 的 `visible` 判断，但`Popup` 既可以 api 调用也可以作为 component 调用，开发者不管是做测试还是和 Redux 交互都会更灵活。

虽然我们都知道 `antd` 是久经考验 well tested 的组件库，但给予开发者更多的选项和便利也会给 `antd` 带来更多的社区回馈。一点点小小的建议，还望 @silentcloud @yiminghe 稍加考虑。

**Comment by paranoidjk** [comment]
@yuche 来个 PR 呗 😄

**Comment by paranoidjk** [comment]
@yuche btw，有这类建议和讨论可以新开issue，不建议在close的下面回复，关联这个就好了，避免我们忘了处理

**Comment by yuche** [comment]
@paranoidjk 我写完了也是这样想的。等空了我开一个 PR 大家一起讨论一下。🙂

**Comment by silentcloud** [comment]
@yuche 

> rn-topview 的 re-render 问题新版本没有代码我不知道是如何解决的。但我觉得可以把 AppComponent 套在一个 StaticContainer 里应该可以避免 re-render。算是一个思路吧

目前基本就是这么干的

**Comment by mrxuyong** [comment]
.set(< AComponent / >) 方法，每次都会加载两次 组件 AComponent，这个问题解决了吗？

**Comment by mrxuyong** [comment]
你好，rn-topview中的 set(< AComponent / >) 方法，每次都会加载两次 组件 AComponent，这个问题解决了吗？
