### ISSUE TITLE
引入高清方案地图插件里的元素均有缩小 影响视觉效果

### ISSUE THREAD

**Issue by Aus0049** [ant-design/ant-design-mobile#799]
#### 本地环境

iphone6s

- antd-mobile 版本：0.9.14
- 浏览器 (或标明是 react-native) 及其版本：safari
- 运行环境及其版本：iphone6s

#### 你做了什么？

网页中使用了百度地图插件（高德地图同样）
引入antd-mobile，同时引入高清配置方案代码段 之后
地图中的各种元素 大头针 建筑物 道路 相对于之前均有所缩小
视野相对于之前则变大 
调整地图zoom数值 仍无效 

#### 你期待的结果是：

地图中的各种元素尺寸恢复使用高清方案之前的尺寸大小

#### 实际上的结果：

使用高清方案之前的地图上的大头针和引入高清方案之后的大头针 尺寸都是19*25
但是高清方案上的地图元素显示就是很小 
影响地图的使用 

#### 可重现的在线演示

引入高清方案之前地图显示：
![引入高清方案之前](http://static.xinrenxinshi.com/mobile/issue_before.png)
引入之后显示：
![引入高清方案之后](http://static.xinrenxinshi.com/mobile/issue_after.png)

**Comment by paranoidjk** [comment]
@Aus0049 调试一下地图插件自带的样式是不是用的`rem`，通过什么方式引入的?

`antd-mobile`的高清方案只会设置`html`的`font-size`和`viewport`, 业务代码里不正确使用`rem`才会错乱。

could you give us a re-producible online demo like this http://codepen.io/paranoidjk/pen/WRLoVq ?
thanks~

**Comment by Aus0049** [comment]
用调试器看了下 百度地图里的样式使用的px 而且是内联样式 
![截图](http://static.xinrenxinshi.com/mobile/issue_screen_shot.png)
这个有办法解决吗

**Comment by Aus0049** [comment]
百度和高德的地图样式均是使用px 内联样式

**Comment by paranoidjk** [comment]
给个简单可重现的demo吧，这样说明不了问题，你的截图两边的缩放比例看起来都不同

**Comment by warmhug** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/456#issuecomment-270045000

@pingan1927 以前遇到过类似问题？关注下

**Comment by xiaoguozi** [comment]
应该是高德地图样式px没有转成对应的rem引起的，不知道有解决方案没？

**Comment by pingan1927** [comment]
@Aus0049 首先高德地图canvas部分已经支持高清方案，
其他dom部分目前仍需自行处理下，正在推动做下更新，不确定何时会支持，目前公司产品使用antd-mobile+高德地图已有案例，仅仅需要做少部分样式覆盖工作即可。

主要就是把需要更新的dom元素的值倍乘下，这个倍数可以通过以下脚本得到。主要是检查当前网页是否启用高清方案（有些旧Android机器不启用）。
`
if ((/android/i).test(navigator.userAgent) || (/iphone|ipad/i).test(navigator.userAgent)) {
  const meta = document.querySelector('meta[name="viewport"]');
  const content = meta.content;
  if (!(/initial-scale=1,/g.test(content))) {
    isMobile = true;
  }
}

export const DPR = isMobile ? window.devicePixelRatio || 1 : 1;
`
然后具体通过样式覆盖下。

**Comment by yc850k** [comment]
我还有个问题请教下 @pingan1927
第三方组件如果是内联的style如何处理，比如这个https://github.com/callemall/material-ui/blob/master/src/List/ListItem.js#L53

**Comment by pingan1927** [comment]
@yc850k 那估计只能祭上``` *important```大法了

**Comment by paranoidjk** [comment]
close,  这个与 antd-mobile 已经无关了。

**Comment by liuxingling** [comment]
请问问题解决了吗？
