### ISSUE TITLE
Button 放在 Flex.Item 里在真机里点击的时候会闪一下

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design-mobile#801]
#### 本地环境

- antd-mobile 版本：1.0.0-beta.3
- 浏览器 (或标明是 react-native) 及其版本：Safari
- 运行环境及其版本：iPhone6s iOS 10.2.1

#### 你做了什么？

```javascript
import React from 'react';
import { Button, Flex } from 'antd-mobile';

export default () => {
  return (
    <div>
      <Flex>
        <Flex.Item>
          <Button type="ghost" inline>10元</Button>
        </Flex.Item>
      </Flex>
    </div>
  );
}
```

#### 你期待的结果是：

不闪烁

#### 实际上的结果：

![button mov](https://cloud.githubusercontent.com/assets/465125/22874111/41b1bc62-f1ff-11e6-9109-e638fcdd470a.gif)

#### 可重现的在线演示

https://codepen.io/yesmeck/pen/RKEJLZ

**Comment by paranoidjk** [comment]
你说的`闪一下`就是说active的蓝色样式？那是正常的

**Comment by iyutao** [comment]
@yesmeck  这个能否满足你需求 `<Button className="btn" activeStyle={false}>10 元</Button>`

**Comment by yesmeck** [comment]
@iyutao 这样就没点击反馈了。

**Comment by paranoidjk** [comment]
@yesmeck  自定义点击反馈吧` activeStyle={{ backgroundColor: 'red' }}`， 设为false，内部会判断，然后不加active 的 classname

**Comment by yesmeck** [comment]
问题是在不应该闪烁。我知道点击的时候背景色会变，现在是会来回变两次（看起来像闪烁）。

**Comment by paranoidjk** [comment]
@yesmeck 一次点击那不应该有两次active反馈，我这边 iPhone6sp, 10.2.1访问你的codepen试了没复现
你要不帮忙调下？看下点击后的class变化过程

**Comment by yesmeck** [comment]
奥。codepen 上不是 `1.0.0-beta.3` 吧。

**Comment by paranoidjk** [comment]
@silentcloud  刚release的1.0.0-beta.3，看下

**Comment by yesmeck** [comment]
奇怪，codepen 上换成 `1.0.0-beta.3` 确实没重现。

**Comment by warmhug** [comment]
确定下哪个版本有问题

**Comment by yesmeck** [comment]
`1.0.0-beta.3`

**Comment by iyutao** [comment]
我 6s `~1.0.0-alpha.9` 复现了，把 flex 去掉就没这个问题了...

**Comment by warmhug** [comment]
我没真机 iPhone ，写死版本号为 1.0.0-beta.2 测试下有没问题  (~ 前缀会自动升级到 beta.3的)  @iyutao

**Comment by silentcloud** [comment]
6Plus  0.9 ， 1.0-beta.2/3 均没重现

**Comment by paranoidjk** [comment]
@yesmeck 昨天下午访问你的本地页面的确有，后来我自己本地写的demo没法复现，肯定还是有某些不太同，放出你昨天的demo地址到群里看看？

**Comment by yesmeck** [comment]
发现只要 Button 的外面一层加了 `onClick` 就会有问题：

```javascript
<div onClick={() => {}}>
  <Button type="ghost" inline>10元</Button>
</div>
```

**Comment by yesmeck** [comment]
加了 fastclick 就好了。。。

**Comment by warmhug** [comment]
😔 关联 #576
