### ISSUE TITLE
missing some icon

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#802]
missing `frown`, `smile` icon for slider demo,  [this css file](https://github.com/ant-design/ant-design-mobile/blob/0.9.x/site/mobile/static/template.html#L50) is removed at `master` which exist in `0.9.x`.

check https://github.com/ant-design/ant-design-mobile/blob/master/components/slider/demo/icon-slider.md

**Comment by warmhug** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/718#issuecomment-272098556

自定义 icon 不用一定是 frown, smile 这两个 icon 名，修改下 demo 换个已经有的 icon 名即可

**Comment by paranoidjk** [comment]
ok， 我来改吧
