### ISSUE TITLE
InputItem 上传图片问题

### ISSUE THREAD

**Issue by lnssh2** [ant-design/ant-design-mobile#806]
#### 本地环境

- antd-mobile 版本：
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：
浏览器 
#### 你做了什么？

InputItem组件， 
  <InputItem
        {...getFieldProps('upload') }
        type='file'
        onExtraClick={this.upimg.bind(this)}
        extra={<img src="https://os.alipayobjects.com/rmsportal/mOoPurdIfmcuqtr.png" />}
      >上传照片</InputItem>
没有file 或者上传图片功能还是BUG呢
#### 实际上的结果：

InputItem 可以有上传图片控件可以正常使用上传图片

**Comment by paranoidjk** [comment]
- 贴下格式化的完整demo代码？
- 描述信息完整清晰一点，否则很难帮你

could you give us a re-producible online demo like this http://codepen.io/paranoidjk/pen/WRLoVq ?
thanks~

**Comment by pingan1927** [comment]
> InputItem 可以有上传图片控件可以正常使用上传图片

目前inpuItem 还不支持 `type`为`file`

**Comment by iyutao** [comment]
@lnssh2 看下这个组件 https://mobile.ant.design/components/image-picker/

**Comment by paranoidjk** [comment]
Going to close this since no response, if you have any further question, feel free to repoen :)
