### ISSUE TITLE
TypeScript中引用ListView会有接口定义的报错

### ISSUE THREAD

**Issue by feit** [ant-design/ant-design-mobile#808]
#### 本地环境

- antd-mobile 版本：1.0.0-beta3
- 浏览器 (或标明是 react-native) 及其版本：chrome
- 运行环境及其版本：chrome56

#### 你做了什么？

引入ListView组件

#### 你期待的结果是：

无接口报错

#### 实际上的结果：

![screen shot 2017-02-14 at 12 27 39](https://cloud.githubusercontent.com/assets/4183342/22915324/5e4351ee-f2b1-11e6-8bbe-71d9c0cee4d2.png)

**Comment by paranoidjk** [comment]
检查下是否未正确配置`babel-plugin-import`而误引用了`RN`版的`ListView`？

**Comment by warmhug** [comment]
代码已经加了，等下个版本 https://github.com/ant-design/ant-design-mobile/commit/3b05bf9fda0fe35b23691e410323174c2522d8e2
