### ISSUE TITLE
建议: 能否增加一个面包屑组件?

### ISSUE THREAD

**Issue by xttianma** [ant-design/ant-design-mobile#811]
场景:  一颗组织树,每个节点都有叶子, 

问题：
1. 选择器组件: 如果有3列, 只能选择最末列的节点,不能选择第一列或者中间一列的节点. 
2. 找不到更合适的组件

期望: XX省>XX市>XX县＞XX乡 ...
1. 点击节点,返回选中的ID. 用于控制页面内的其他组件显示.
2. 点击 ... ： 选择次级子项目

**Comment by paranoidjk** [comment]
移动端很少有用面包屑的场景吧

**Comment by xttianma** [comment]
少,但是碰到树形对象的操作, 那就需要了. 
想来想去,只有面包屑是最合适的体验了. 
参考:　钉钉（管理员) 的管理部和人员的功能 .

**Comment by paranoidjk** [comment]
即将发布的`1.0`肯定是不会加这个feature了，你有兴趣来个PR吗？ 😄

**Comment by warmhug** [comment]
建议参考 https://ant.design/components/breadcrumb-cn/ pc 组件自己实现。不常用组件一般不考虑加进来的。

**Comment by xttianma** [comment]
@paranoidjk 
1. 来个pr是什么意思? 
2. 关于warmhug的建议,我十分无奈, 我自己不会写这个组件实现呀. 
----
面包屑是钉钉里面的UI规范, 并且确实用于类似组织架构的管理上的移动端体验非常好.(节点树的节点属性和叶子管理), 否则其他组件
1. 层次特别的深
2. 中间节点不能进行选择: 例如选择器: 省/市/县, 只能选择县,而不能选择省/市节点.

**Comment by paranoidjk** [comment]
pr 是指 pull request，就是帮我们贡献代码的意思

钉钉的ui规范之类可以给个链接或demo看看吗？

新增组件需要设计师评审设计，抱歉

**Comment by xttianma** [comment]
@paranoidjk  请参考:  http://dingtalk.amazeui.org 的面包屑组件. github有源码

**Comment by paranoidjk** [comment]
@warmhug 设计师 id 是多少？ping一下看看我们做不做，做的话可以放`1.0`之后

**Comment by warmhug** [comment]
设计师相关的 issue ，链接直接发给 万焱 或发内部群里 @ 他们

**Comment by xttianma** [comment]
我认为有没有必要性主要是antd ui的大场景方向的问题
如果定位于快速的数据管理的中后台管理,这个组件难以审核通过.
如果适用于OA场景和树装业务为核心的应用(OA场景是深度依赖组织树的应用系统),就有必要性.

**Comment by silentcloud** [comment]
这种不通用的组件，建议用户自己实现
