### ISSUE TITLE
建议自定义的本地svg支持默认type="svgname"写法,否则每个都要写一长串代码

### ISSUE THREAD

**Issue by szwork2013** [ant-design/ant-design-mobile#813]
看了ant-design-mobile/components/icon/index.web.tsx源代码才知道，本地自定义的svg只支持 <Icon type={require('./reload.svg')} />或<Icon type={require('!svg-sprite!./reload.svg')} />这样的写法。为什么不能修改一下源代码能支持跟默认的type="svgname" ，否则书写太麻烦了。

**Comment by warmhug** [comment]
自定义的 svg 做不到像内置 svg 的字符串引用写法。
可以参考下其他资源路径引用方式，都是自己写 require 的，因为路径是自己可以随意设置的。
