### ISSUE TITLE
如何实现非ListView的下拉刷新效果？

### ISSUE THREAD

**Issue by git-lt** [ant-design/ant-design-mobile#814]
普通页面怎样实现下拉刷新？

**Comment by paranoidjk** [comment]
暂不支持，你可以参考代码自己实现 https://github.com/react-component/m-list-view/blob/master/src/RefreshControl.jsx

**Comment by warmhug** [comment]
自己实现，可参考这里 https://github.com/react-component/m-pull-to-refresh

**Comment by git-lt** [comment]
谢谢了
