### ISSUE TITLE
RN Grid 样式定制问题

### ISSUE THREAD

**Issue by u0x01** [ant-design/ant-design-mobile#815]
RN 下的 Grid 线条想改成 .5，可是不像 Web 可以直接改，求个方案。

**Comment by silentcloud** [comment]
可以先引用 组件内的 Grid 样式，然后覆盖，再重新给组件传 `styles` prop

**Comment by warmhug** [comment]
关联 #560

**Comment by silentcloud** [comment]
@u0x01 方案已经写了对应的 demo，参见 demo： https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui
