### ISSUE TITLE
SwipeAction滑动或长按操作 在RN android是滑动，没有长按

### ISSUE THREAD

**Issue by lixiaoyang1992** [ant-design/ant-design-mobile#817]
#### 本地环境
 
- antd-mobile 版本：1.0.0-beta.3
- 浏览器 (或标明是 react-native) 及其版本：react-native: 0.41.1
- 运行环境及其版本：android

#### 你做了什么？

在ListView的renderRow中使用了Swipeout包裹了一个TouchableHighlight

#### 你期待的结果是：

长按出现对话框，
或者点击和滑动都可以正常触发

#### 实际上的结果：

在真机上用手指点击不触发onPress，
模拟器上用鼠标正常。

SwipeAction的rn的源码中没有找到长按的相关代码

#### 可重现的在线演示

无

**Comment by silentcloud** [comment]
@lixiaoyang1992 android 的长按已经取消了，之前因为会和 list 的 touch 冲突，所以改成两平台一样的了
