### ISSUE TITLE
按照官网项目实战npm下载的，为什么没有webpack文件呢

### ISSUE THREAD

**Issue by files3** [ant-design/ant-design-mobile#819]
#### 本地环境

- antd-mobile 版本：beta1.0
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：

**Comment by silentcloud** [comment]
你要自定义 webpack？参考 https://github.com/ant-design/antd-mobile-samples  这里面的例子

**Comment by afc163** [comment]
这里要修改一下：https://mobile.ant.design/docs/react/practical-projects#%E4%BD%BF%E7%94%A8-antd-mobile

dva-cli 现在没有 webpack.config.js 了。
