### ISSUE TITLE
在内网中使用图标

### ISSUE THREAD

**Issue by vnice** [ant-design/ant-design-mobile#822]
#### 本地环境

公司内网里面使用antd-mobile.

- antd-mobile 版本：0.9.14

#### 你做了什么？

引入Button组件并设置 loading 属性 ,不能显示loading框 

#### 你期待的结果是：
可以使用内网下载好的字体文件，需要怎样配置才能正常像外网那样使用图标

#### 实际上的结果：
因为内网里面alicdn两个字体文件不能下载，所以无法显示loading

**Comment by paranoidjk** [comment]
请看 https://github.com/ant-design/ant-design-mobile/wiki/FAQ 第二条
