### ISSUE TITLE
路霸的高清方案怎么配置，和webpack一样吗？

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design-mobile#823]
#### 本地环境

- antd-mobile 版本：
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：

**Comment by paranoidjk** [comment]
一样的，只需要把postcss plugin配置到roadhog，参考https://github.com/sorrycc/roadhog/ 文档里关于
extraPostCSSPlugins部分

高清方案文档https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE

**Comment by SynChron1zed** [comment]
@paranoidjk  .roadhog.js 在哪？ 是 .roadhog.mock.js么

**Comment by paranoidjk** [comment]
.roadhogrc 看文档 https://github.com/sorrycc/roadhog/
