### ISSUE TITLE
文档中的示例代码没有更新到es6版本,是没有及时维护么?

### ISSUE THREAD

**Issue by kinop112365362** [ant-design/ant-design-mobile#824]
hi,同学们,我看到文档示例中的代码,还是es5的版本,这部分之后会更新么?感觉文档不及时更新,会让新的使用者有顾虑

**Comment by paranoidjk** [comment]
会的，也欢迎你给我们pull request ：）

**Comment by paranoidjk** [comment]
- [ ] drawer 
- [ ] menu 
- [ ] nav-bar 
- [ ] pagination 
- [ ] popover 
- [ ] segmented-control 
- [ ] tabs 
- [ ] tab-bar 
- [ ] button 
- [ ] checkbox 
- [ ] date-picker 
- [ ] input-item 
- [ ] image-picker 
- [ ] picker 
- [ ] picker-view 
- [ ] radio 
- [ ] range 
- [ ] switch 
- [ ] search-bar 
- [ ] slider 
- [ ] stepper 
- [ ] textarea-item 
- [ ] accordion 
- [ ] badge 
- [ ] carousel 
- [ ] card 
- [ ] grid 
- [ ] icon 
- [ ] list 
- [ ] notice-bar 
- [ ] steps 
- [ ] table 
- [ ] tag 
- [ ] action-sheet 
- [ ] activity-indicator 
- [ ] modal 
- [ ] progress 
- [ ] popup 
- [ ] toast 
- [ ] refresh-control 
- [ ] swipe-action 
- [ ] list-view 
- [ ] result 
- [ ] locale-provider 
- [ ] flex 
- [ ] wing-blank 
- [ ] white-space 
- [ ] github.com

**Comment by paranoidjk** [comment]
@bccsafe 有兴趣的话可以帮忙认领几个 :）

**Comment by paranoidjk** [comment]
thanks for @bccsafe 👍 you can mark what you have done as completed at here

**Comment by bccsafe** [comment]
* [x] Accordion
* [x] ActionSheet
* [x] ActivityIndicator
* [x] Button
* [x] Carousel
* [x] CheckBox

**Comment by silentcloud** [comment]
这个只是写代码的方式问题，其实没必要非得把  React.createClass 改成 class extend

**Comment by paranoidjk** [comment]
@silentcloud 
目的就是为了统一「写代码的方式」
另外好处也有，写成 class 的方式代码会更简洁，与typescript配合也更好，以及 这个迁移我认为必然是要进行的，只是时间早晚的问题
关联 https://github.com/ant-design/ant-design/issues/4878

**Comment by benjycui** [comment]
React 官方似乎也不建议使用 React.createClass 了 https://github.com/facebook/react/issues/8854

**Comment by benjycui** [comment]
心疼西部世界，代码都得重写了。

![image](https://cloud.githubusercontent.com/assets/3580607/23195073/e45fd810-f8ec-11e6-83f8-42661253b6da.png)

**Comment by paranoidjk** [comment]
@benjycui 快上你的 codemod

**Comment by silentcloud** [comment]
恩，既然都官方都推荐了，那就改吧，我那部分组件我来改

**Comment by paranoidjk** [comment]
@silentcloud https://github.com/ant-design/ant-design-mobile/commit/be5d29533a6999f10be8d7c817dc97958f5531b0 这个你可以review下，我把`react-timer-mixin`去掉了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/d7694d4c3b24270b36fd80055af0d2ee5bb97ddb

**Comment by paranoidjk** [comment]
所有demo代码的修改已经完成，组件的修改放在后续维护的过程中慢慢迁移，包括一些mixin的逻辑，可能也要慢慢替换掉
