### ISSUE TITLE
TextareaItem组件title属性native端不显示

### ISSUE THREAD

**Issue by eWeiMe** [ant-design/ant-design-mobile#828]
#### 本地环境

- antd-mobile 版本：
- 浏览器 (或标明是 react-native) 及其版本：1.0.0
- 运行环境及其版本：IOS 10.2模拟器

#### 你做了什么？
使用TextareaItem组件
```
<TextareaItem
   {...getFieldProps('feedback')}
  placeholder="请输入您的反馈意见"
  title="反馈意见"
  rows={5}
  count={280}
/>
```

#### 你期待的结果是：
像官网一样正常显示

#### 实际上的结果：
title没有显示

**Comment by paranoidjk** [comment]
`TextareaItem`使用的是 React-Native 的 [TextInput](https://facebook.github.io/react-native/docs/textinput.html), 暂时不支持 `tite`属性，文档应该是有误，抱歉
