### ISSUE TITLE
PickerView,没有默认的样式.

### ISSUE THREAD

**Issue by xttianma** [ant-design/ant-design-mobile#829]
- antd-mobile ：1.0   钉钉内置浏览器

#### 你做了什么？
import { PickerView ,  } from "antd-mobile"; 

#### 你期待的结果是：
像官网一样正常显示

#### 实际上的结果：
缺少样式,不像其他组件的风格,提供附加的样式支持, 
![image](https://cloud.githubusercontent.com/assets/22427990/23091208/975d8f02-f5eb-11e6-9ad2-28bbbd0376e5.png)

**Comment by paranoidjk** [comment]
- 没看出缺少样式？
- 业务可以通过以下两个 props 自定义样式

```js
    prefixCls: 'am-picker',
    pickerPrefixCls: 'am-picker-col',
```
