### ISSUE TITLE
picker组件绑定表单后onChange事件失效

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design-mobile#83]
#### 本地环境

- antd-mobile 版本：0.7.2
- 操作系统及其版本：
- 浏览器及其版本：

#### 你做了什么？
`<Picker data={data} cols={1} extra="请选择"  value={["1"]} onChange={this.selectUserType} {...getFieldProps('userType', {
            initialValue: ['1'],
          })}>`
onChange没办法调用到，如果想要调用需要怎么做呢

**Comment by benjycui** [comment]
http://ant.design/components/form/#this.props.form.getFieldProps(id,-options)

![image](https://cloud.githubusercontent.com/assets/3580607/17611503/662f7370-607a-11e6-940c-1f531f493add.png)

**Comment by ksh033** [comment]
明白，如果自己绑定完onChange事件后，原来表单默认绑定的onChange事件还会执行吗。

**Comment by choukin** [comment]
><Picker data={data} cols={1} extra="请选择" value={["1"]} {...getFieldProps('userType', { initialValue: ['1'], onChange：this.selectUserType})}>

这样写才对

**Comment by ksh033** [comment]
好的我是看了api有onChange的属性可以设置。哈哈api应该备注一下。
我发现在这样设置后调用this.props.form.getFieldsValue()的时候userType的值都不会变了。

**Comment by ksh033** [comment]
可以了谢谢

**Comment by motorguo** [comment]
@ksh033 不是值不变，而是**慢一拍** `setState`
@benjycui 请教一下这个问题，有没有什么好的解决办法
多个表单，当改变某个 `Picker` 值的时候就需要做点什么的时候；请问这时候该怎么处理呢
我觉得 `setState` 的时机应该得在 `onPickerChange` 的时候。

**Comment by benjycui** [comment]
`setState` 的工作机制的又 React 决定的，建议先学习下 React。

**Comment by motorguo** [comment]
场景：用户选择 `picker` 更换值的时候就去更新页面。
通常很多都是下面还有一个 `button` 确定提交，这种情况下这个组件是没有问题的。
建议给 `picker` 组件添加 `okonClick` .
