### ISSUE TITLE
1.0版本InputItem输入框, safari浏览器中，清除功能无效

### ISSUE THREAD

**Issue by godkillCK** [ant-design/ant-design-mobile#830]
#### 本地环境
- antd-mobile 版本：1.0.0
- 浏览器 (或标明是 react-native) 及其版本：safari
- 运行环境及其版本：各终端safari浏览器

#### 你做了什么？
InputItem clear功能无效

#### 可重现的在线演示
[官网就可重现](https://mobile.ant.design/components/input-item/)

**Comment by paranoidjk** [comment]
@pigcan PC clear 失效，onTouchStart 改成 onClick 还是没点到的感觉

**Comment by paranoidjk** [comment]
抱歉，这个 Bug 只在 PC 浏览器上会有，目前已修复，下周五会 release 新版本。
