### ISSUE TITLE
ListView renderSectionHeader extra问题

### ISSUE THREAD

**Issue by lst0214** [ant-design/ant-design-mobile#831]
0.9版本 renderSectionHeader 不会渲染出 extra 但是1.0版本会出现 `<div class="am-list-extra"></div>` 如何在1.0版本设置取消`<div class="am-list-extra"></div>`

**Comment by lst0214** [comment]
0.9版本 renderSectionHeader 不会渲染出 extra 但是1.0版本会出现 <div class="am-list-extra"></div> 如何在1.0版本设置取消<div class="am-list-extra"></div>

**Comment by lst0214** [comment]
1.0版本 renderSectionHeader 会出现<div class="am-list-extra"></div>

**Comment by paranoidjk** [comment]
抱歉，1.0目前没有开放这个配置，可以先通过css解决

```css
.am-list-extra {
 display: none
}
```

**Comment by paranoidjk** [comment]
@pingan1927 https://github.com/ant-design/ant-design-mobile/commit/7ba6eb567912c22f09dbfd2548cbbd34beacd8c5 

这个是为了修复什么bug？ 为什么 `extra !== null` ? undefined 的情况没有考虑到？

关联这个 https://github.com/ant-design/ant-design-mobile/commit/c62c8b408a9db231d1f10943b5754805e21a5848

**Comment by paranoidjk** [comment]
抱歉，已修复，下周五会 release 新版本。

临时方案可以这样：

```css
.am-list-extra {
    display: none;
}
```

**Comment by paranoidjk** [comment]
关联这个 https://github.com/ant-design/ant-design-mobile/commit/c62c8b408a9db231d1f10943b5754805e21a5848
release新版本之后也要跟进修复
