### ISSUE TITLE
图标显示错误

### ISSUE THREAD

**Issue by vnice** [ant-design/ant-design-mobile#833]
#### 本地环境

- antd-mobile 版本：0.9.14
- 浏览器 (或标明是 react-native) 及其版本：chrome 
- 运行环境及其版本：公司内网

#### 你做了什么？

根据https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont
使用https://github.com/ant-design/ant-design/releases/download/resource/iconfont-2.x.zip
下载的iconfont文件
引入Button 组件设置loading 和Toas.loading 发现loading图标变成了图钉
查看css发现antd-mobile中loading图标的content值为E6A1,而下载的iconfont中的E6A1是图钉，对不上。
#### 你期待的结果是：

能够像官网里面正确显示图标

#### 实际上的结果：
如图
![image001](https://cloud.githubusercontent.com/assets/5074080/23093593/ce1e405e-f622-11e6-8a30-b8fb15b530a5.png)

**Comment by paranoidjk** [comment]
@vnice 先使用这几个字体试试，我从 http://09x.mobile.ant.design/components/icon 复制的
https://at.alicdn.com/t/font_1463992151_360388.woff
http://at.alicdn.com/t/font_1457169990_5499172.woff
http://at.alicdn.com/t/font_1457169990_5499172.woff

@afc163 https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont 下载的iconfont文件变更了？

check了0.9.x的文档http://09x.mobile.ant.design/components/icon，`E6A1`的确应该是loading

**Comment by afc163** [comment]
antd 和 antd-mobile 使用的 iconfont 不是同一份。

**Comment by vnice** [comment]
@paranoidjk  好的，从cdn中下载的文件应该是没问题的。希望后面antd-mobile的字体文件有更新的话能够提供下载地址在wiki中说明。

**Comment by paranoidjk** [comment]
@vnice 1.0 已经切换到 svg icon，且大量减少了内置icon，以便用户贴合业务定制icon，具体参看文档
https://mobile.ant.design/components/icon

**Comment by silentcloud** [comment]
除 1.0 Icon 内置的 svg 外，其他非内置的，稍后我会放在 根目录 svg-icon 下面，方便用户直接取用 antd 对应的 iconfont 那套图标样子

**Comment by paranoidjk** [comment]
@vnice 老版本icon的取用地址已放出 https://github.com/ant-design/ant-design-mobile/issues/866
