### ISSUE TITLE
如何在gulp+jspm中使用svg的icon？

### ISSUE THREAD

**Issue by zydest** [ant-design/ant-design-mobile#834]
本地是gulp+jspm+es6。启动程序后不显示icon，在antd-mobile@1.0.0/lib/icon/index.web.js里加入了catch语句，显示错误信息是
Module ./style/assets/check-circle-o.svg not declared as a dependency of http://localhost:3000/jspm_packages/npm/antd-mobile@1.0.0/lib/icon/index.web.js

请问改如何解决，谢谢。

- antd-mobile 版本： 1.0.0
- 浏览器 (或标明是 react-native) 及其版本：chrome
- 运行环境及其版本：gulp+jspm

**Comment by paranoidjk** [comment]
抱歉，jspm 并不在我们的支持范围内。

我们提供的方案是用 webpack loader 来处理 svg 的引用，参见文档 https://mobile.ant.design/components/icon

**Comment by paranoidjk** [comment]
going to close this, if you have any further question, feel free to reopen this.  :)
