### ISSUE TITLE
关于 tab-bar的问题

### ISSUE THREAD

**Issue by xoptimal** [ant-design/ant-design-mobile#836]
#### 本地环境

- antd-mobile 版本：最新
- 浏览器 (或标明是 react-native) 及其版本：google chrome
- 运行环境及其版本：最新

#### 你做了什么？

1. 引用了 tab-bar , 直接 copy 了实例代码, 去掉了badge属性,  设置title属性三个以上中文字符,
2. 设置 tab-bar 高度

#### 你期待的结果是：

1. 文字和图标居中对齐
2. 设置成功

#### 实际上的结果：

1. 图标还有文字没有居中对齐
2. 设置失败

--------------------------------------------------------------------------------------------------

项目搭建流程:  
1. dva new webTest 
2. $ npm install antd-mobile --save
    $ npm install babel-plugin-import --save-dev
3. ["import", { "style": "css", "libraryName": "antd-mobile" }]

除开这个问题, 还有个高清方案设置不懂, 请指教 : 

我在 index.html 加入了: !function(e){function t(a){if(i[a])retur.......

并且配置了 : 
```
extraPostCSSPlugins: [
  pxtorem({
    rootValue: 100,
    propWhiteList: [],
  })
]
```
我现在的问题是, 我的设计稿是 1080 * 1920 的

请问我现在的 less 的转换是否是正确的 ?  如果不是, 请问我该怎么去计算 ~  

eg. 
```css
.px2rem(@name, @px) {
    @{name}: @px / 100 * 1rem;
}

.px2px(@name, @px) {

  @{name}: round(@px) * 1px;
  
  [data-dpr="2"] & {
      @{name}: @px * 2px;
  }
  [data-dpr="3"] & {
      @{name}: round(@px * 3) * 1px
  }
  [data-dpr="4"] & {
      @{name}: round(@px * 4) * 1px
  }
}
```

**Comment by paranoidjk** [comment]
- 抱歉，居中的问题已经fix，每周五会release新版本
- 高清方案，配置了pxtorem，代码里css可以都用px为单位（100px => 1rem），建议设计师给750px的设计稿或者自己缩放到750，效果是750的标注多宽css就可以写多少px，不用计算

ref https://github.com/ant-design/ant-design-mobile/issues/796

**Comment by xoptimal** [comment]
我想问下如何自己缩放到 750 ?   数学不太好, 请指教 !!   @paranoidjk

**Comment by paranoidjk** [comment]
或者这样：
- css里就以你1080设计稿标注的实际宽度写px
- pxtorem插件的 rootvalue 配置为  `100 * （1080 / 750 ）`

不懂可以看看文档里贴的 [脚本代码 ](https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE)

**Comment by xoptimal** [comment]
@paranoidjk  感谢 ~   还有个疑问, 我看不是适配字体的单独处理的 ,  我想知道字体大小也是跟着设计稿标的写对吧 ?

**Comment by paranoidjk** [comment]
不需要单独处理字体

**Comment by xoptimal** [comment]
还有个关于 tab-bar 设置样式的问题~   通过 className / style  (外部/内部) 写入均无效 ,  我想请问怎么修改它的高度  ~

在API下, 我看见有这么一个参数 `prefixCls`  , 设置是成功的, 但是其余的样式被清空了, 

我想保留其余的样式, 只想更改高度, 请问怎么实现~    @paranoidjk

**Comment by paranoidjk** [comment]
更改什么高度？给个例子？内容的高度是由你自己控制的，可以看看demo的代码

`prefixCls`是用来自定义样式的，定义你自己的prefixCls，整个组件的样式就要你自己接管

**Comment by xoptimal** [comment]
我想更改tab-bar 高度 ~

**Comment by paranoidjk** [comment]
这个需求很奇怪，我们的组件是带有设计规范的，目前的TabBar高度为什么需要修改？

一定要修改，你可以选择`prefixCls `，或者你业务代码的css去覆盖

**Comment by xoptimal** [comment]
好吧 , 清楚明白～ 感谢解答

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-mobile/blob/c50e61e7ea41ade22d7f3b8b4047368f74acec20/components/style/themes/default.less#L158

**Comment by paranoidjk** [comment]
@xoptimal sorry， 没注意到这个变量提供配置了，还可以按上面@afc163 提供的自定义主题方案，文档在这 https://ant.design/docs/react/customize-theme-cn

**Comment by xoptimal** [comment]
@paranoidjk   感谢说明 ~   但是根据设置, 没有发生改变 , 配置如下:

```
{
  "entry": "src/index.js",
   "theme": {
     "@tab-bar-height": "400px"
    },
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "style": "css", "libraryName": "antd-mobile" }],
        ["import", { "style": true, "libraryName": "antd-mobile" }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime"
      ]
    }
  }
}
```

还有根据你的高清方案设置,   发觉还是按照750设计稿的适配,  并不是按照1080 , 配置如下:

.roadhogrc.js : 
```
extraPostCSSPlugins: [
  pxtorem({
    rootValue    : 100 * (1080 / 750),
    propWhiteList: []
  })
]
```

该文件(roadhogrc.js) , 是在项目根目录存放吧, 跟.roadhogrc文件是同级吧 ?

**Comment by xoptimal** [comment]
纠正 ~  高清设置下 ~  是按 1080的来做适配 ~ 这个没错 ....

但是iphone7 并没缩放,  显示的1080的, 所以整体的显示都被放大了 ~
