### ISSUE TITLE
360 OS 2.0 108版，运行 App 查看 ReactNative 版组件，点击 复选框 和 单选框 闪退

### ISSUE THREAD

**Issue by winnie2012** [ant-design/ant-design-mobile#837]
#### 本地环境

- antd-mobile 版本：
- 浏览器 (或标明是 react-native) 及其版本：
- 运行环境及其版本：360 OS 2.0 108版

#### 你做了什么？

查看 ReactNative 版组件，点击 复选框 和 单选框

#### 实际上的结果：

闪退

**Comment by paranoidjk** [comment]
360os....没有调试环境，能帮忙看下么？：）

**Comment by silentcloud** [comment]
这个环境太特殊，没有相应的设备；或者能不能把闪退日志发上来

**Comment by winnie2012** [comment]
再被充一个系统同样的问题：华为 EMUI 4.0.1 Android 版本：6.0.1

**Comment by warmhug** [comment]
华为系统，最新的 RN demo 不会闪退，关注最新 RN 二维码

**Comment by winnie2012** [comment]
@warmhug 果然是二维码地址的问题，感谢，此单可以关闭了。
