### ISSUE TITLE
safari打不开

### ISSUE THREAD

**Issue by gonghtianqi** [ant-design/ant-design-mobile#838]
safari 打不开 http://antm.alipay.net/

页面都是灰色的，报错：
Failed to load resource: the server responded with a status of 404 (Not Found)
Invariant Violation: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.
See: http://formatjs.io/guides/runtime-environments/

**Comment by silentcloud** [comment]
官方网站地址： [mobile.ant.design](mobile.ant.design)， 请问你是在哪里看到这个地址的？
