### ISSUE TITLE
normalize.css报错

### ISSUE THREAD

**Issue by Lzzzzzq** [ant-design/ant-design-mobile#843]
#### 本地环境

- antd-mobile 版本：1.0.0
- 浏览器 (或标明是 react-native) 及其版本：chrome
- 运行环境及其版本：windows node v6.9.2 npm v3.10.9

#### 你做了什么？

引入了 ListView 组件，官方示例原样代码。

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

normalize.css报错

`ERROR in ./~/.5.0.0@normalize.css/normalize.css`
`Module build failed: ReferenceError: window is not defined`

#### 可重现的在线演示

https://github.com/Lzzzzzq/ant-mobile-Test 我的git仓库

**Comment by paranoidjk** [comment]
https://github.com/Lzzzzzq/ant-mobile-Test/search?utf8=%E2%9C%93&q=normalize.css

你业务代码都没有加载normalize.css，这个错误跟 antd-mobile 没有任何关系，建议check你的webpack配置

> Recommend to read [*How To Ask Questions The Smart Way*](http://www.catb.org/~esr/faqs/smart-questions.html) and [How to Ask a Question in Open Source Community](https://github.com/seajs/seajs/issues/545) and [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html), a smart question will get right answer quickly.

**Comment by xusai2014** [comment]
报错了

**Comment by xusai2014** [comment]
同求
