### ISSUE TITLE
给tabs组件提个建议

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design-mobile#844]
antd-mobile:  1.0.0

目标模块：Tabs

惊喜：
      实现了滑动功能，下一步希望能搞定滚动功能

建议：
       希望能够提供一个可以设置一屏显示的标签数，因为有时候标签的长度可能需要4-6个字，再加上自定义样式，远远超出了默认设定的5个标签数，导致出现冲突，
0.9.x版本我给am-tabs-bar样式加上overflow: scroll;  am-tabs-tab的样式加上display: inline-table，可以实现滚动。

但是升级到1.0.0后，由于设置的标签长度超出了5个标签的长度（即超出了界面）导致页面不美观

结尾：
      不知工程师们 下一步是否有这方面的优化？

**Comment by paranoidjk** [comment]
1. 滑动目前只支持内容滑动，你说的滚动是指顶部的滚动？这个work in progress https://github.com/ant-design/ant-design-mobile/issues/394

2. tab标签数可以考虑，默认5个是我们的设计规范

**Comment by MotorFu** [comment]
对的，是顶部滚动。
设置标签数的问题，希望能在下个版本出来

**Comment by MotorFu** [comment]
@paranoidjk 发现一个样式问题：

TabBar组件的返回按钮
.am-navbar-left样式的 
 margin-left: .3rem;  改成     padding-left: .3rem;
否则返回的点击区域少了15px的宽度

**Comment by paranoidjk** [comment]
很好的提议，已经修改 👍  有优化的地方非常欢迎给我们提pull request
