### ISSUE TITLE
ListItem的Extra里的Button的onClick事件不能被阻止传播

### ISSUE THREAD

**Issue by huang475** [ant-design/ant-design-mobile#845]
#### 本地环境

- antd-mobile 版本：1.0.0
- 浏览器 (或标明是 react-native) 及其版本：Chrome  56.0.2924.87
- 运行环境：MacOs 10.12.2

#### 你做了什么？

在一个ListItem的Extra里放了一个Button, ListItem和这个Button有各自的onClick事件

#### 你期待的结果是：

点Button的时候如果阻止了事件的传播的话只有Button的onClick事件可以被触发

#### 实际上的结果：

ListItem的onClick事件仍然会被触发

#### 可重现的在线演示
https://codepen.io/anon/pen/JEgROR?editors=1111

**Comment by paranoidjk** [comment]
在官网demo的基础上，实测没问题
```jsx
<List renderHeader={() => '基本样式'} className="my-list">
    <Item onClick={()=>alert('xx')} extra={<Button onClick={()=>alert('yy')}>测试</Button>}>标题文字</Item>
</List>
```

请提供可复现的实例 https://codepen.io/warmhug/pen/bwRPvx

**Comment by huang475** [comment]
@paranoidjk 感谢。 我重新修改了一下Issue的描述。

**Comment by paranoidjk** [comment]
@warmhug 帮忙看下，测试是有问题，两个 rc-touchable 嵌套

**Comment by warmhug** [comment]
从现在的代码实现上看，比较难解决。 @yiminghe 看下这个问题？

**Comment by yiminghe** [comment]
可以解决，把 click 的原生事件对象给 item button 的onClick 参数

**Comment by paranoidjk** [comment]
@yiminghe 你的意思是这里改成 `e.nativeEvent` ? https://github.com/react-component/touchable/blob/f0be1ab33dc23c17c2e2f97f3858df0183f8ac1a/src/index.tsx#L266

**Comment by benjycui** [comment]
其实 @huang475 可以直接使用 `e.nativeEvent` 的吧。

**Comment by huang475** [comment]
@benjycui  not working

**Comment by benjycui** [comment]
[`e.nativeEvent.stopImmediatePropagation`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation)

**Comment by huang475** [comment]
@benjycui https://codepen.io/anon/pen/JEgROR?editors=1111

**Comment by benjycui** [comment]
Interesting, I fork @huang475 's CodePen and update https://codepen.io/benjycui/pen/KWgPYm?editors=0011

When I click Button and then click it again, log:

```bash
"clicking button"
"clicking listItem"
"clicking button"
```

But If I click Button, then click outside List, and then click Button, log:

```bash
"clicking button"
"clicking button"
```

**Comment by paranoidjk** [comment]
关联  https://github.com/ant-design/ant-design-mobile/issues/937

**Comment by paranoidjk** [comment]
@huang475  

这个已经和 https://github.com/ant-design/ant-design-mobile/issues/937 一起修复了，只要在 Button 的 onClick 里面 `e.stopPropagation()` 就行了。

请使用最新的 `1.0.5` 验证下。
