### ISSUE TITLE
1.0版本toast图标不显示

### ISSUE THREAD

**Issue by Gj-tutu** [ant-design/ant-design-mobile#846]
#### 本地环境

linux

- antd-mobile 版本： 1.0.0
- 浏览器 (或标明是 react-native) 及其版本：chrome

#### 你做了什么？

    Toast.loading('加载中...', 0)

#### 你期待的结果是：

像官网一样显示

#### 实际上的结果：

![image](https://cloud.githubusercontent.com/assets/19498440/23119930/376ee41e-f795-11e6-8cf5-b936332d8400.png)
![image](https://cloud.githubusercontent.com/assets/19498440/23119948/44c835ca-f795-11e6-9492-b271190585c9.png)

先用了0.9.14版本，显示也发生问题，loading的图标不会转动，就更新成了1.0版本，图标就不显示

**Comment by silentcloud** [comment]
有没有配置 svg loader？

**Comment by Gj-tutu** [comment]
我用webpack打包的
  {
    test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
    loader: 'url',
    query: {
      limit: 10240,
      name: `img/[name].[${config.compiler_hash_type}].[ext]`
    }
  }
添加了svg

**Comment by Gj-tutu** [comment]
多谢，有劳了，文档没找仔细。。

**Comment by paranoidjk** [comment]
svg icon 的使用文档已更新，进行了配置的简化和尽可能兼容到window以及cnpm等各种情况

https://mobile.ant.design/components/icon
