### ISSUE TITLE
antd-mobile图标不显示

### ISSUE THREAD

**Issue by PatWu16** [ant-design/ant-design-mobile#847]
本地环境
nodejs+dva+antd-mobile

- antd-mobile 版本：1.0.0
- 浏览器 (或标明是 react-native) 及其版本：最新谷歌

<NavBar
        leftContent="返回"
        mode="light"
        onLeftClick={() => console.log('onLeftClick')}
        rightContent={[
          <Icon key="0" type="search" />,
          <Icon key="1" type="ellipsis" />
        ]}
/>

运行时Icon不显示
![default](https://cloud.githubusercontent.com/assets/23301139/23121062/eaf17e4e-f799-11e6-88ee-7d2e4dcc517f.png)

**Comment by silentcloud** [comment]
和这个同样的 https://github.com/ant-design/ant-design-mobile/issues/846

**Comment by paranoidjk** [comment]
@PatWu16 看你的代码压根没有定义iconName，仔细看下demo代码
https://mobile.ant.design/components/nav-bar

**Comment by Gj-tutu** [comment]
1.0里面无法使用ant-design原本的icon了，看了下目前只支持几个svg，有什么兼容方案是可以使用ant-design的icon么

**Comment by paranoidjk** [comment]
@Gj-tutu 精简的原因在这里 https://github.com/ant-design/ant-design-mobile/issues/718#issuecomment-272098556

自己添加icon的方案在这里 https://mobile.ant.design/components/icon#本地部署

**Comment by silentcloud** [comment]
@Gj-tutu 支持 type={require('path/to/svg')} 的，0.9 对应的 svg 我明天会放出来，稍等

**Comment by Gj-tutu** [comment]
@paranoidjk 恩，看到原因了，只是项目里已经使用了之前的，这次是因为更新成1.0发现不见了。。
@silentcloud 多谢，因为项目中已经使用了，突然没了的确会有困扰，其他开发者也就无法更新至最新版了，有劳了！

**Comment by paranoidjk** [comment]
@Gj-tutu 
我们遵循 [semver](http://semver.org/lang/zh-CN/) 语义化版本的规范，升级大版本之前请一定关注 [更新日志](https://mobile.ant.design/changelog) 和 [升级指南](https://mobile.ant.design/docs/react/upgrade-notes)，尤其是 break change 部分

going to close this, if you have any further question, feel free to reopen it :)

**Comment by Gj-tutu** [comment]
@paranoidjk 恩，我没注意，应该大版本升级前考虑清楚的，不好意思

**Comment by PatWu16** [comment]
@paranoidjk 

import React, { PropTypes } from 'react';
import { NavBar, Icon } from 'antd-mobile';
import { connect } from 'dva';

import styles from './Header.css';

function Header({ location }) {
  return (
    <div className={styles.normal}>
      <NavBar
        leftContent="返回"
        mode="light"
        onLeftClick={() => console.log('onLeftClick')}
        rightContent={[
          <Icon key="0" type="search" />,
          <Icon key="1" type="ellipsis" />
        ]}
      />
    </div>
  );
}

Header.propTypes = {
  location: PropTypes.object.isRequired
};

function mapStateToProps() {
  return {};
}

export default connect(mapStateToProps)(Header);

图标什么的都有导入

**Comment by PatWu16** [comment]
@silentcloud
我目前就是这样配置的
![default](https://cloud.githubusercontent.com/assets/23301139/23126294/fb352956-f7b0-11e6-918b-2077ec862b2a.png)

**Comment by paranoidjk** [comment]
check下你的 node_modules/antd-mobile/lib 是不是存在？

**Comment by felixzxk** [comment]
我的情况也是一样的，不过用的roadhog，安装了glob和svg-sprite-loader，在node_modules/roadhog/src/conf/webpack.config.dev.js做了同样配置，图标不显示

**Comment by paranoidjk** [comment]
@PatWu16 windows先参照这里处理一下 https://github.com/ant-design/ant-design-mobile/issues/840#issuecomment-281248538

**Comment by paranoidjk** [comment]
svg icon 的使用文档已更新，进行了配置的简化和尽可能兼容到window以及cnpm等各种情况

https://mobile.ant.design/components/icon

**Comment by paranoidjk** [comment]
@felixzxk svg icon 的文档已更新，添加了 `roadhog` 的支持 https://mobile.ant.design/components/icon

**Comment by dancinglone** [comment]
我按最新文档安装的，用cnpm，  windows，关键配置如下：
const svgDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''),  // 1. 属于 antd-mobile 内置 svg 文件
  // path.resolve(__dirname, 'src/my-project-svg-foler'),  // 2. 自己私人的 svg 存放目录
];

module: {
    loaders: [
      {test: /\.jsx?$/, exclude: /node_modules/, loaders: ['babel']},
      {test: /\.eot(\?v=\d+.\d+.\d+)?$/, loader: 'file'},
      {test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url?limit=10000&mimetype=application/font-woff"},
      {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/octet-stream'},
      {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=image/svg+xml'},
      {test: /\.(jpe?g|png|gif)$/i, loader: 'url-loader?limit=15000&name=build/[name].[ext]'},
      {test: /\.ico$/, loader: 'file?name=[name].[ext]'},
      {test: /(\.css|\.scss)$/, loaders: ['style', 'css', 'postcss', 'sass']},
      {
        test: /\.(svg)$/i,
        loader: 'svg-sprite',
        include: svgDirs,  // 把 svgDirs 路径下的所有 svg 文件交给 svg-sprite-loader 插件处理
      }
    ]
  },


没有任何报错。

但图标就是显示不出来。（升级前是正常的）

有遇到同样问题的朋友吗，求解。

**Comment by paranoidjk** [comment]
@dancinglone 贴代码格式化是最基本的尊重

**Comment by dancinglone** [comment]
@paranoidjk 抱歉，我删掉整理一下。谢谢提醒！

我按最新文档安装的，用**_cnpm_**， **_windows_**，关键配置如下：
```
//目录定义部分
const svgDirs = [
    require.resolve('antd-mobile').replace(/warn.js$/, ''), // 1. 属于 antd-mobile 内置 svg 文件
    // path.resolve(__dirname, 'src/my-project-svg-foler'), // 2. 自己私人的 svg 存放目录
];

// loader定义部分
module: {
loaders: [
    {
        test: /.(svg)$/i,
        loader: 'svg-sprite',
        include: svgDirs, // 把 svgDirs 路径下的所有 svg 文件交给 svg-sprite-loader 插件处理
    }
]
}
```

没有任何报错。

但图标就是显示不出来。（升级前是正常的）

有遇到同样问题的朋友吗，求解。会不会是因为用了cnpm， 或者因为windows路径不是这样定义？
求指导

**Comment by paranoidjk** [comment]
@dancinglone 你的配置看起来没问题，图标没显示需要你自己调试下。或者你可以在你机器上跑一下官方demo看看 https://github.com/ant-design/antd-mobile-samples/tree/master/rn-web

**Comment by dancinglone** [comment]
试了一下官方的demo，在我的机子上跑是正常的。 
我对比了一下，发现我跑起来的代码里面，根本就没有 svg的symbol 标签，只有这个：
```
<svg class="am-icon am-icon-check am-icon-md">
     <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#check"></use>
</svg>
```

请问可能是什么原因？ （跟我分开开发、生产两个webpack配置应该不会有关系吧？我两边都加了同样的svg配置的）

另外，我看上那个demo，loader的写法是有点不一样的，是：
`loader: require.resolve('svg-sprite-loader'),`
sprite后面多了 loader
效果是一样的？ 但我试了都不行。

另，会不会与我整个项目的webpack配置是import 引入的风格有关？ 不能两种风格夹杂？
```
import webpack from 'webpack';
import HtmlWebpackPlugin from 'html-webpack-plugin';
import autoprefixer from 'autoprefixer';
import pxtorem from 'postcss-pxtorem';

// bad code?
const svgDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''),  // 1. 属于 antd-mobile 内置 svg 文件
  // path.resolve(__dirname, 'src/my-project-svg-foler'),  // 2. 自己私人的 svg 存放目录
];
```

但我在组件内有这样写的地方，是正常的：
```
import { ImagePicker } from 'antd-mobile';
import './WechatImagePicker.scss';
const wx = require('weixin-js-sdk');
```

我尽力先自己调试一下，如有相关经验，求指点迷津！

**Comment by dancinglone** [comment]
现有调整后可以了。 发现我的项目的webpack 配置里面已经有svg相关的loader了，把原来的注释了才可以：

```
loaders: [
      {test: /\.jsx?$/, exclude: /node_modules/, loader: 'babel'},
      {test: /\.eot(\?v=\d+.\d+.\d+)?$/, loader: 'url?name=[name].[ext]'},
      {test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url?limit=10000&mimetype=application/font-woff&name=[name].[ext]"},
      {test: /\.ttf(\?v=\d+.\d+.\d+)?$/, loader: 'url?limit=10000&mimetype=application/octet-stream&name=[name].[ext]'},
      **{test: /\.svg(\?v=\d+.\d+.\d+)?$/, loader: 'url?limit=10000&mimetype=image/svg+xml&name=[name].[ext]'},**
      {test: /\.(jpe?g|png|gif)$/i, loader: 'url-loader?limit=15000&name=build/[name].[ext]'},
      {test: /\.ico$/, loader: 'file?name=[name].[ext]'},
      {test: /(\.css|\.scss)$/, loader: ExtractTextPlugin.extract('css?sourceMap!postcss!sass?sourceMap')},
      {
        test: /\.(svg)$/i,
        loader: 'svg-sprite',
        include: svgDirs,  // 把 svgDirs 路径下的所有 svg 文件交给 svg-sprite-loader 插件处理
      }
    ]
```

因为原来是没有用到svg的，所以应该没什么问题。但如果原来有，怕不怕有问题？ webpack的配置了解的还不够多，我自行了解一下。

先把经历贴出来，让有同样问题的朋友可以参考。

**Comment by xiaojingzhao** [comment]
@paranoidjk 根据提供的文档描述

> Android 项目将 anticon.ttf 放在 android/app/src/main/assets/fonts/ 目录下;
 但是 android/app/src/main/ 下没有assets／fonts。
而且根据你提供的例子，我在rn例子下的 android/app/src/main/  也没有找到，我想知道关于rn到底怎么配？
是文档写错了吗？
