### ISSUE TITLE
引用carousel这个组件 出新bug了。。。报react-slick 出错

### ISSUE THREAD

**Issue by 201030740221** [ant-design/ant-design-mobile#85]
#### 本地环境

- antd-mobile 版本："antd-mobile": "^0.7.5",
- 操作系统及其版本： windows 7 企业版
- 浏览器及其版本：chrome 30.0.1599.101

#### 你做了什么？

 引入 antd-mobile 的 Carousel 

#### 你期待的结果是：

像官网一样正常显示 

#### 实际上的结果：
报react-slick 出错
 
#### 可重现的在线演示
webpack
npm start
Uncaught Error: Cannot find module "react-slick"

**Comment by 201030740221** [comment]
麻烦看看

**Comment by 214132049** [comment]
这个组件里的内容   能是动态遍历出来的吗？

**Comment by 201030740221** [comment]
可以啊，只是引用这个组件 报错了

**Comment by 214132049** [comment]
嗯  我的可以  没有错误
