### ISSUE TITLE
safari 浏览器 高清样式

### ISSUE THREAD

**Issue by marsal1212** [ant-design/ant-design-mobile#856]
safari 浏览器开发 响应设计模式下，选择6sp机型 样式问题。
https://mobile.ant.design/kitchen-sink/components/tab-bar

**Comment by paranoidjk** [comment]
什么问题？ 我6sp访问正常

**Comment by marsal1212** [comment]
选择之后刷新，tabbar.Item 变得特别大。

**Comment by marsal1212** [comment]
http://www.sino-assist.com/img/WechatIMG1.jpeg
如图。

**Comment by paranoidjk** [comment]
@marsal1212 你的截图是在什么工具下？
