### ISSUE TITLE
给Toast提个建议 

### ISSUE THREAD

**Issue by jokerapi** [ant-design/ant-design-mobile#857]
- antd-mobile 版本：0.9.6

建议：可否给Toast的方法的onClose支持promise。这样在api调用时写法更连贯。

**Comment by paranoidjk** [comment]
@silentcloud 好像改过一波？

**Comment by silentcloud** [comment]
@paranoidjk  改过一波，只改了 alert 和 prompt，toast 的我稍后加上 @jokerapi

**Comment by silentcloud** [comment]
最终考虑不加 promise: 原因，加了 promise 指定的 duration 就有歧义了，你想 promise 之后 close 的话就类似这样写：

```
Toast.info('xxxxxx', 0, () => {
   setTimeout(() => {
      doSth(); 
     Toast.hide();
  }, 100);
})
```

duration 为 0 的时候 toast 会一直显示，处理完事情后，手动调 hide
