### ISSUE TITLE
listView里面是多选列表，怎么去维护每个多选的状态啊。。。

### ISSUE THREAD

**Issue by YoFoon** [ant-design/ant-design-mobile#858]
那个row函数里面不能维护啊。

**Comment by warmhug** [comment]
给出在线 demo 或具体的问题，这种笼统的提问没法回答。。提问前麻烦请先认真阅读提问说明~

**Comment by paranoidjk** [comment]
>强烈推荐阅读 [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)、[《如何向开源社区提问题》](https://github.com/seajs/seajs/issues/545) 和 [《如何有效地报告 Bug》](http://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)，更好的问题更容易获得帮助。
>Recommend to read [*How To Ask Questions The Smart Way*](http://www.catb.org/~esr/faqs/smart-questions.html) and [How to Ask a Question in Open Source Community](https://github.com/seajs/seajs/issues/545) and [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html), a smart question will get right answer quickly.

**Comment by paranoidjk** [comment]
Going to close this, if you have any further questions - please just ask :)
