### ISSUE TITLE
Can't set "className" prop to <Tabs/> at version 1.0.0

### ISSUE THREAD

**Issue by CodingMonkeyzh** [ant-design/ant-design-mobile#861]
#### Environment(required)

- antd-mobile version: 1.0.0
- Browser (or mark react-native) and its version: Google Chrome 56.0.2924.87 (64-bit)
- Operating environment (e.g. OS name) and its version: Mac OS Sierra

#### What did you do? Please provide steps to re-produce your problem.
I have set a `className` prop to `<Tabs/>` component,  and it worked fine (version `0.9.13`). But when I update `antd-mobile` to `1.0.0`, the custom `class` has gone...

#### Re-producible online demo
see it:
http://codepen.io/CodingMonkeyzh/pen/GrVNZP?editors=0010

**Comment by paranoidjk** [comment]
sorry，i will fix this. 

but you should notice that `className` is not in our api doc, so you should not rely on it
