### ISSUE TITLE
Steps组件的样式有问题

### ISSUE THREAD

**Issue by StarryF** [ant-design/ant-design-mobile#862]
![image](https://cloud.githubusercontent.com/assets/8469660/23158787/5e151482-f85b-11e6-89ae-1c7cfcb6a4b8.png)
只有我的Steps组件长成这样么？没有引入其他react组件

**Comment by warmhug** [comment]
什么版本？官方 demo 是否有类似问题？

**Comment by StarryF** [comment]
直接把官方的demo拷贝到我的系统里就这样，目前是0.9.13的版本，之前尝试用了1.0.0的版本可能是因为svg图标没有引入进来所以显示有问题。但是项目中最终还是不打算升级，就用0.9.13的版本开发。

**Comment by paranoidjk** [comment]
close this since i couldn't  reproduce this problem on official demo, please provide a reproducible online demo, then feel free to reopen this.

for example:
http://codepen.io/paranoidjk/pen/LWpaKe
