### ISSUE TITLE
【公告】老版本 iconfont 对应的 svg 图标地址：https://github.com/ant-design/ant-design-icons

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#866]
[全部 svg 图标地址]( https://github.com/ant-design/ant-design-icons)

**Comment by paranoidjk** [comment]
svg icon 的使用文档已更新，进行了配置的简化和尽可能兼容到window以及cnpm等各种情况

https://mobile.ant.design/components/icon

**Comment by paranoidjk** [comment]
svg icon 的文档已更新，添加了 `roadhog` 的支持 https://mobile.ant.design/components/icon
