### ISSUE TITLE
建议： 各个组件的demo代码的css内容还附加上吧. 

### ISSUE THREAD

**Issue by xttianma** [ant-design/ant-design-mobile#868]
例如 使用组件: 
listview  (还有几个记不清了), 没有demo附加的css样式
tabbar :　有demo的样式

有附加的demo样式, 都复制到本地,效果很直观. 没有这个demo的css样式, 好难看. 

是否给各个组件都附带demo的css, 这个好习惯, 已经厌倦不在提供了?

**Comment by paranoidjk** [comment]
组件的demo有一些通用的布局样式，我们不可能在每隔demo文件里写一遍，效率太低，我们采用添加classname的方式做的，这部分样式你可以在这里找到 https://github.com/ant-design/ant-design-mobile/blob/master/site/kitchen/src/static/demo.less

**Comment by xttianma** [comment]
这样也ok, 就是纳闷你的默认className里面都是什么.
是否可以在文档的左侧列表里面附加写说明?
amaze ui 里面很清楚, 全局的样式设置和修改使用. 
salt ui里面, 所有的自带的样式做了详细说明并且重新封装了.

**Comment by benjycui** [comment]
不建议直接使用 antd 或者 antd-mobile 样式表里面的 className。

组件才是我们暴露的功能，不然就不会有 Layout Grid 这些纯样式的组件了。
