### ISSUE TITLE
直接使用Object.assign 有兼容性问题（Android5，iOS8.4）

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#87]
直接使用Object.assign 有兼容性问题（Android5，iOS8.4）

**Comment by pingan1927** [comment]
项目代码目前通过`atool-build`构建，`antd-mobile`包的源文件中如果使用`Object.assign`，然而`antd-mobile`的组件内部的`Object.assign`并不会被babel自动转成es5的代码。在iOS8-,Android 5.1-，都会脚本报错，导致整个跑不起来。

所以，这个问题请各个直接使用了`Object.assign`，而不是使用npm模块`object-assign`的组件维护者尽快，最好今天就修复掉。

**Comment by silentcloud** [comment]
是不是 babel 转换的时候的问题？

**Comment by yiminghe** [comment]
统一使用 object-assign
