### ISSUE TITLE
私有 icon 配置说明文档有错

### ISSUE THREAD

**Issue by joahCN** [ant-design/ant-design-mobile#870]
![image](https://cloud.githubusercontent.com/assets/2697255/23206444/a04cc200-f928-11e6-807a-29e032439957.png)
启动发现有些loader没有test属性，导致启动失败。文档应该改下，加个判断：
```
if (loader.test && loader.test.toString() === '/\\.svg(\\?v=\\d+\\.\\d+\\.\\d+)?$/') {
            loader.exclude = svgDirs;
        }
```

**Comment by paranoidjk** [comment]
thanks, i will fix this right now

**Comment by paranoidjk** [comment]
by the way, if you came across doc problem  liken this, welcome to give us a pr to fix it :)

**Comment by joahCN** [comment]
Sure.
