### ISSUE TITLE
自定义icon已经配置了，但仍报错

### ISSUE THREAD

**Issue by joahCN** [ant-design/ant-design-mobile#871]
**问题：**
自定义icon已经配置在webpack config文件中用svg-sprite的加载了，但仍报错

**webpack.config.js中的配置**
![image](https://cloud.githubusercontent.com/assets/2697255/23206748/d2a995b0-f929-11e6-8351-44b034cf7f8e.png)

**component 中的使用**
![image](https://cloud.githubusercontent.com/assets/2697255/23206779/f29549d2-f929-11e6-845b-776e8d0f9596.png)

**运行结果：**
![image](https://cloud.githubusercontent.com/assets/2697255/23206803/0578853c-f92a-11e6-92de-9f861a785fd1.png)

**note: 资源文件加 svg-sprite loader却可以正常加载**
![image](https://cloud.githubusercontent.com/assets/2697255/23206902/5a3562e8-f92a-11e6-964b-1ab50ef03d99.png)

**Comment by paranoidjk** [comment]
能给出详细的报错信息吗？

**Comment by paranoidjk** [comment]
建议你把 webpackConfig console log 出来看一看，atool-build 内置的svg-loader exclude可能没有配置成功

这个报错可能是svg被处理两遍 https://github.com/kisenka/svg-sprite-loader/issues/31

**Comment by joahCN** [comment]
原因如你所说，svg被处理了两次
上述的exclude没匹配成功，按下面的修改可以fix, 但不确定是否未来是否会有冲突：

```
webpackConfig.module.loaders.forEach(loader => {
        if (loader.test && **loader.test.toString().startsWith("/\\.svg")**) {
            loader.exclude = svgDirs;
        }
});
```

**Comment by paranoidjk** [comment]
ok，i will upgrade doc  later

**Comment by steadyzeus** [comment]
我还是遇到同样的问题，用的atool-build,
 WARNING in Unexpected token {
     @ ./~/antd-mobile/lib/icon/style/assets ^\.\/.*\.svg$

    ERROR in Unexpected token {
     @ ./src/routes/page01.jsx 36:60-88

    ERROR in Unexpected token {
     @ ./~/antd-mobile/lib/toast/index.web.js 24:8-45
