### ISSUE TITLE
Tabs 超出界面宽度，多于5个标签 不自动隐藏  如图

### ISSUE THREAD

**Issue by HongXiaoMing** [ant-design/ant-design-mobile#872]
![200486083142209629](https://cloud.githubusercontent.com/assets/24834470/23210516/dd796902-f938-11e6-8cba-c4963215dad6.jpg)

代码
import React from 'react';
import { connect } from 'dva';
import { Tabs, WhiteSpace } from 'antd-mobile';

const TabPane = Tabs.TabPane;

function news() {
  return <div>
    <Tabs defaultActiveKey="1" >
      <TabPane tab="选项卡一" key="1">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
          选项卡一内容
        </div>
      </TabPane>
      <TabPane tab="选项卡二" key="2">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
          选项卡二内容
        </div>
      </TabPane>
      <TabPane tab="选项卡三" key="3">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
          选项卡三内容
        </div>
      </TabPane>
      <TabPane tab="选项卡三" key="4">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
          选项卡三内容
        </div>
      </TabPane>
      <TabPane tab="选项卡三" key="5">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
          选项卡三内容
        </div>
      </TabPane>
      <TabPane tab="选项卡三" key="6">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
          选项卡三内容
        </div>
      </TabPane>
    </Tabs>
         </div>
}

function mapStateToProps() {
  return {};
}

export default connect(mapStateToProps)(news);

**Comment by paranoidjk** [comment]
- 代码格式化是最基本的尊重
- 建议提供可复现的demo，否则没法帮你 https://codepen.io/warmhug/pen/bwRPvx

**Comment by paranoidjk** [comment]
你的代码问题很多， `news` return 的只是一堆普通的div，都没有引用`Tab`和`TabPane`，请参考官方demo
https://mobile.ant.design/components/tabs

**Comment by HongXiaoMing** [comment]
不好意思  https://github.com/HongXiaoMing/antmobile/blob/master/news.js   这个是代码

**Comment by HongXiaoMing** [comment]
已经解决   版本问题
