### ISSUE TITLE
TabBar和Tabs新增beforeOnPress，afterOnPress的props

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#876]
需求描述，
`Tabs`,`TabBar`在切换`TabPane`、`Tab.Item`时，目前情况下会互相影响scrollTop的值。虽然可以通过设置每个内部模块的DOM进行局部滚动解决，但是当整个业务非常复杂的时候，设置局部滚动会倒追渲染非常卡，效果无法接受。

需要`Tabs`,`TabBar`提供切换前后的回调，一个使用场景是用于记录每个`TabPane`、`Tab.Item`的scrollTop值，达到页面互相不影响scrollTop值的效果。

**Comment by paranoidjk** [comment]
其实名字不应该是 before/after onPress, 而是类似 react-router onEnter onLeave 这类hook的作用？

**Comment by paranoidjk** [comment]
> 这里的一个处理是将切换tab后的渲染和数据请求的时机，由change（ Function - runs at slide change）改为transitionEnd（Function - runs at the end slide transition，使浏览器主线程优先处理过渡动画。
> 这个改动使slide transition流畅了很多，但一些组件如：react-swipeable-views和antd-mobile Tabs并没有提供transitionEnd相关接口。

这篇文章也有提到 https://zhuanlan.zhihu.com/p/22640911

**Comment by paranoidjk** [comment]
cc @yiminghe

**Comment by pingan1927** [comment]
这个可以好好优化下，现在的TabBar+Tabs的性能实在堪忧

**Comment by benjycui** [comment]
在 [`onPrevClick` 和 `onNextClick`](https://github.com/ant-design/ant-design/issues/4395) 里记录 active 的 TabPane 的 scrollTop，然后在 TabPane 的 `componentDidUpdate/componentDidMount` 里面读出来设置可以？

**Comment by paranoidjk** [comment]
@zhang740 考虑下 antd-mobile@2.0 是否可以加这个 api

**Comment by zhang740** [comment]
@pingan1927 重构后的Tabs组件支持的固定高度方式会处理滚动位置的问题，而且组件支持受控组件方式，这两个API可以变相实现。这组API还是否有加的必要？
[Tabs组件](http://beta.mobile.ant.design/components/tabs-cn)

**Comment by zhang740** [comment]
后续有需求再开吧
