### ISSUE TITLE
Android原生发送事件给ReactNativc

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#878]
![image](https://cloud.githubusercontent.com/assets/6219316/23255257/de948ade-f9f5-11e6-9569-3acaa32ddf67.png)
![image](https://cloud.githubusercontent.com/assets/6219316/23255280/f29c8c3e-f9f5-11e6-8303-d9251e0e7a39.png)
![image](https://cloud.githubusercontent.com/assets/6219316/23255289/fe6e9fde-f9f5-11e6-910d-7a6f056f4816.png)

求助，这个问题怎么解决...

**Comment by liubin1023** [comment]
android 设备版本 4.4.2

**Comment by silentcloud** [comment]
这里能帮到你么？http://facebook.github.io/react-native/releases/next/docs/native-modules-android.html#sending-events-to-javascript

我也不是很懂 android

**Comment by liubin1023** [comment]
@silentcloud 谢谢

**Comment by paranoidjk** [comment]
@liubin1023  can you close this issue if your problem is solved ?

and like this kind of problem,  you may  can ask for help at https://segmentfault.com/t/react-native

**Comment by liubin1023** [comment]
@paranoidjk @silentcloud 
感谢，已经解决了
实现接口LifecycleEventListener就可以了
