### ISSUE TITLE
webpack2 打包支持

### ISSUE THREAD

**Issue by darin-lao** [ant-design/ant-design-mobile#880]
现在webpack 以升级到version 2 ，请官方给出自定义webpack2打包相关配置，还有webpack2自义定theme修改的配置方式

**Comment by paranoidjk** [comment]
right now, we will focus on improving  the functionality and experience.
we won't consider upgrade to webpack2 until it's very stable. ref https://github.com/sorrycc/blog/issues/23

however, PR to help us do it earlier  is welcome any way :)
