### ISSUE TITLE
1.0.x changelog

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#887]

**Comment by paranoidjk** [comment]
# 更新中

## New Feature

## Improve 
- 所有 demo 代码迁移到 ES6 class 和 Pure function，去除 React.createClass ([#824](https://github.com/ant-design/ant-design-mobile/issues/824))
- NavBar 返回间隔从 margin 改为 padding，增大点击区域 ([#844](https://github.com/ant-design/ant-design-mobile/issues/844))
## Bugfix
- 修复 List extra 为空的判断逻辑 ([#831](https://github.com/ant-design/ant-design-mobile/issues/831))
- 修复 Toast 不居中的问题 ([#827](https://github.com/ant-design/ant-design-mobile/issues/827))
- 修复 InputItem PC 上无法 clear 的 bug ([#832](https://github.com/ant-design/ant-design-mobile/pull/832))
- 修复 React-Native SearchBar onChange 重复触发的 bug ([#739](https://github.com/ant-design/ant-design-mobile/issues/739))
- 修复 TabBar icon 居中的问题 ([#836](https://github.com/ant-design/ant-design-mobile/issues/836))

**Comment by pingan1927** [comment]
# 1.0.2

## Bugfix
- 修复Grid在较老旧Android版本上宽度计算的问题。

**Comment by paranoidjk** [comment]
@pingan1927 

# 1.0.2
## Feature
- Tabs 新增 `pageSize` API，新增支持 swipeableTabBar 滑动头部。 （[#882](https://github.com/ant-design/ant-design-mobile/pull/882)）

## Bug Fix
- Stepper `onChange` 重复触发 （[#891](https://github.com/ant-design/ant-design-mobile/issues/891)）
- 修复 CheckboxItem 与 BrowserSync 不兼容的问题 ([#350](https://github.com/ant-design/ant-design-mobile/issues/350))
- 修复 Tabs `className` 校验的 bug ([#904](https://github.com/ant-design/ant-design-mobile/issues/904))
- RN stepper `readOnly` 默认改为 `false` ([#890](https://github.com/ant-design/ant-design-mobile/issues/890))

## Improve && Enhancement
- Icon 增加 try catch，避免控制台报错 ([#895](https://github.com/ant-design/ant-design-mobile/issues/895))
- 官网重构支持国际化，自动检测浏览器语言并支持中/英文切换
- 文档翻译进行中，欢迎参与贡献~ ([#329](https://github.com/ant-design/ant-design-mobile/issues/329))

**Comment by afc163** [comment]
一般来说，新增 API 应该发 minor 版本。

**Comment by paranoidjk** [comment]
@afc163  minor 也可以，不过这个 pageSize 是无缝升级的，用户其实可以完全不感知，发patch也不会有问题

**Comment by afc163** [comment]
像 antd 一样建一个 feature-x.x 分支，任何新增功能都 push 到这上面。这样 patch 版本不会混杂新功能。

**Comment by silentcloud** [comment]
@pingan1927  changelog 可以看哈每个人的 commit 么？我修的都没在 log 里 

- RN Carousel 修复 componentWillUnmount 不执行问题 #906 
- RN android Carousel 修复闪烁问题 #899；
- 修复 RN Android Tabbar 和 ActionSheet\Toast\Popup\Modal.alert 混合使用时 zIndex 混乱问题， #910 
- Modal 新增 Modal.operation #925

**Comment by paranoidjk** [comment]
@silentcloud 看我写的最新的，已经release，有问题可以去补充

**Comment by paranoidjk** [comment]
@silentcloud 这次我帮大家写了...以后看怎样样运作比较好，是轮值的人根据commit log来写还是大家各自写

**Comment by paranoidjk** [comment]
另外我新建了`feature-1.1`分支，如果有不能在 `1.0.x` 上的 feature 往这个上面合 https://github.com/ant-design/ant-design-mobile/tree/feature-1.1

**Comment by paranoidjk** [comment]
# 1.0.5 

## Feature
- 补全 `accordion` React-Native 版本 ([#931](https://github.com/ant-design/ant-design-mobile/pull/931))
- `stepper` 图标支持用户自定义 ([链接](https://github.com/ant-design/ant-design-mobile/commit/78ab295f69cd1441b600aa6c2d921c7d658096ca))
- 补全 React-Native `Button` 的 loading 样式 （[#946](https://github.com/ant-design/ant-design-mobile/issues/946)）
- React-Native `InputItem` 支持输入小数 （[950](https://github.com/ant-design/ant-design-mobile/issues/950)）
- `Icon` 支持直接添加事件 ([#955](https://github.com/ant-design/ant-design-mobile/issues/955))
- React-Native `InputItem`, `TextItem` 支持自定义 style ([#949](https://github.com/ant-design/ant-design-mobile/issues/949))

## Bug Fix
- React Native `SearchBar` 自动显示取消按钮 ([#957](https://github.com/ant-design/ant-design-mobile/issues/957))
- 修复 `Tabs` 在低版本 Android 浏览器兼容性问题 ([#940](https://github.com/ant-design/ant-design-mobile/issues/940))
- React Native 修复 `Card` extra 覆盖的bug ([#969](https://github.com/ant-design/ant-design-mobile/issues/969))
- 修复 `ImagePicker` 图片旋转方向问题 ([#944](https://github.com/ant-design/ant-design-mobile/issues/944))
- 修复 `Step` 水平溢出的问题 ([#952](https://github.com/ant-design/ant-design-mobile/issues/952))

## Improve && Enhancement
- 新增 Web && React Native 组件的 snapshot 测试，覆盖率 59% ([#921](https://github.com/ant-design/ant-design-mobile/pull/921))
- 文档翻译进度 ([#329](https://github.com/ant-design/ant-design-mobile/issues/329))
- [官方 Demo 集合](https://github.com/ant-design/antd-mobile-samples) 新增 roadhog 示例

**Comment by afc163** [comment]
这段话可以去掉了：https://github.com/ant-design/ant-design-mobile/blob/master/CHANGELOG.zh-CN.md#%E5%8F%91%E5%B8%83%E5%91%A8%E6%9C%9F

**Comment by paranoidjk** [comment]
@afc163 为啥，时不时还有人来问多久发版本之类的，丢个链接方便点...

**Comment by silentcloud** [comment]
# 1.0.6

## Feature

- Modal 添加 close api，方便手工销毁，#995

## Bug Fix

- 修复 ImagePicker clear icon 旋转问题，#944

## Improve && Enhancement

- 优化 Modal button 长按的默认行为；
- Stepper、Toast、Modal 依赖的 rc-util 升级，去除控制台中 warning，#959
- 部分文档优化；#997 #993 #984 #1009；部分 demo 优化；

**Comment by paranoidjk** [comment]
# 1.0.7

## Feature
- Steps 支持自定义颜色。（[#1024](https://github.com/ant-design/ant-design-mobile/pull/1024)）
- ListItem 在 Android 上点击新增水波纹动效。（[链接](https://github.com/ant-design/ant-design-mobile/commit/d8fd66992fdfe53745fb43d9e27bffd025b8fdb0)）
## Bug Fix
- DatePicker 接收 `minuteStep`。 ([#1020](https://github.com/ant-design/ant-design-mobile/issues/1020))
- 修复 Stepper 的 icon 多重边框问题。（[#1038](https://github.com/ant-design/ant-design-mobile/issues/1038)）
- 修复 SearchBar placeholder 在聚焦时显示不全的问题。（[#1047](https://github.com/ant-design/ant-design-mobile/issues/1047)）
## Improve && Enhancement
- Modal, Switch, ListItem 新增 `platform` 参数，可自定义组件样式是否区分 Android/iOS 平台。([#1030](https://github.com/ant-design/ant-design-mobile/issues/1030))
- SearchBar 自定义主题时的布局优化。 ([#1014](https://github.com/ant-design/ant-design-mobile/issues/1014))
- InputItem, TextareaItem, SearchBar 组件样式优化，增大可点击区域。 ([#1017](https://github.com/ant-design/ant-design-mobile/issues/1017))
- React-Native Steps 支持 React.Node 类型的 `title`, `description`。 [#1008](https://github.com/ant-design/ant-design-mobile/issues/1008)
- DatePicker 确保默认日期在 `minDate`, `maxDate` 范围内 （[#1033](https://github.com/ant-design/ant-design-mobile/issues/1033)）

**Comment by silentcloud** [comment]
# 1.0.7

## Feature
- RN modal 增加 Modal.prompt #1089 
- 更新 rc-slider 版本，增加 `minimumTrackStyle`、`maximumTrackStyle`、`handleStyle` 属性；
- ListItem 在 Android 上点击新增水波纹动效。（[链接](https://github.com/ant-design/ant-design-mobile/commit/d8fd66992fdfe53745fb43d9e27bffd025b8fdb0)）
## Bug Fix
- 修复 InputItem、TextareaItem、Search autofocus 的 bug #1103 
- 修复 SearchBar 点击 `x` 取消时，placeholder 显示不正确的 bug #1047 
- 修复 TextareaItem 输入 emoji 表情，字符统计错误问题 #1085
## Improve && Enhancement
-

**Comment by afc163** [comment]
新 feature 不要发到 patch 版本上。

**Comment by paranoidjk** [comment]
close this. Prefer use PR to add new changelog, eg https://github.com/ant-design/ant-design/pull/5671
