### ISSUE TITLE
官方demo中tabs超出界面宽度，多于5个标签没有作用，所有标签都会挤在屏幕中，代码和基础的tabs代码完全一样

### ISSUE THREAD

**Issue by jackYouth** [ant-design/ant-design-mobile#888]
#### Environment(required)

- antd-mobile version:
- Browser (or mark react-native) and its version:
- Operating environment (e.g. OS name) and its version:

**Comment by paranoidjk** [comment]
please give us a reproducible online demo https://codepen.io/warmhug/pen/bwRPvx

or we have on way to help you location the problem

**Comment by ldgoooo** [comment]
![image](https://cloud.githubusercontent.com/assets/2022063/23398789/d67c7e60-fdd8-11e6-8a0c-c6d30ba2d876.png)
我也遇到了这个问题，多余5个标签，按照官方demo的写法根本就不起租用。用上面codepeng工具试了下确实是这样的

**Comment by paranoidjk** [comment]
@ldgoooo 方便发你的codepen我看下？

**Comment by ldgoooo** [comment]
const {
  Button,Tabs
} = window['antd-mobile'];


const TabPane = Tabs.TabPane;

var Hello = React.createClass({
  render() {
    return <div style={{margin: 10}}>
      <Tabs defaultActiveKey="4">
              <TabPane tab="曼妥思" key="1">
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
                    aaa
                </div>
              </TabPane>

              <TabPane tab="极度" key="2">
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff'  }}>
                  bbb
                </div>
              </TabPane>

              <TabPane tab="麻麻小灶" key="3">
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff'  }}>
                  ccc
                </div>
              </TabPane>

              <TabPane tab="医疗器材及消耗1" key="4">
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff'  }}>
                  ddd
                </div>
              </TabPane>
              <TabPane tab="医疗器材及消耗2" key="5">
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff'  }}>
                  ddd
                </div>
              </TabPane>
        <TabPane tab="医疗器材及消耗3" key="6">
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff'  }}>
                  ddd
                </div>
              </TabPane>
              
            </Tabs>
    </div>;
  }
});

ReactDOM.render(<Hello />,
  document.getElementById('container')
);
if ('addEventListener' in document) {
  window.addEventListener('load', function() {
    FastClick.attach(document.body);
  }, false);
}

**Comment by paranoidjk** [comment]
@ldgoooo 请不要贴没有格式化的代码，并没有任何作用。你完全可以在 https://codepen.io/warmhug/pen/bwRPvx 给我一个可重现的demo。

另外，请check版本是不是 `1.0.1`, 尝试 `rm -rf node_modules && npm i`

官方的这个demo我刚测试没有任何问题
https://github.com/ant-design/antd-mobile-samples/blob/master/rn-web/index.web.js#L50

**Comment by ldgoooo** [comment]
https://codepen.io/anon/pen/qrOLjK
在codepen就不行

**Comment by paranoidjk** [comment]
@ldgoooo sorry，codepen上antd-mobile的版本没有更新，我刚从 0.9.x 更新到了1.0.1，works fine
http://codepen.io/paranoidjk/pen/LWpaKe?editors=0110

**Comment by paranoidjk** [comment]
close for no response, if you have any further question, feep free to reopen.
