### ISSUE TITLE
Badge 使用反馈

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#89]
- RN： 

  - 太大；出几个标准场景的大小？ （比如 list 的时候多大，bar 的时候多大）
    
    ![image](https://cloud.githubusercontent.com/assets/1698185/17654084/92083b7c-62d1-11e6-9a5a-457496f85ea3.png)

  - 数字会换行
    
    ![image](https://cloud.githubusercontent.com/assets/1698185/17654133/35fccd56-62d2-11e6-84a5-b1856a28cd17.png)

- WEB：

  - 同样需要几套大小；
  - 未适配新的高清方案；（表现：chrome 和 chrome mobile debug 模式表现不一致）

**Comment by silentcloud** [comment]
@liqi07 今天修复一下，badge 要用在 tabbar 上

**Comment by liqi07** [comment]
OK, get
