### ISSUE TITLE
Invalid prop `className` of type `object` supplied to `Tabs`, expected `string`.

### ISSUE THREAD

**Issue by Sdoy** [ant-design/ant-design-mobile#893]
#### Environment(required)

- antd-mobile version:1.0.1
- Browser (or mark react-native) and its version:版本 56.0.2924.87 (64-bit)
- Operating environment (e.g. OS name) and its version:mac

#### What did you do? Please provide steps to re-produce your problem.

```
<Tabs defaultActiveKey="1" onChange={callback}>
      <TabPane tab="选项卡一" key="1">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
          选项卡一内容
        </div>
      </TabPane>
      <TabPane tab="选项卡二" key="2">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
          选项卡二内容
        </div>
      </TabPane>
      <TabPane tab="选项卡三" key="3">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
          选项卡三内容
        </div>
      </TabPane>
    </Tabs>
```

#### What do you expected?

正常运行

#### What happen?

![image](https://cloud.githubusercontent.com/assets/10302939/23347179/43a2a0f4-fcdb-11e6-9eab-d27dff12ed94.png)

**Comment by paranoidjk** [comment]
- 官方demo并无此问题
- 从你的实例代码看你也没有传className
- 请check下你的版本，最好给出可重现的在线demo https://codepen.io/warmhug/pen/bwRPvx

**Comment by paranoidjk** [comment]
报错是 `props.className` 非法，请check是不是string

没回应先close掉。

**Comment by liuxingling** [comment]
我也遇到了这个问题，用到tabs的地方就报错了
在pc浏览器上和ios上虽然不会影响程序运行。
但是在安卓手机的uc浏览器，连页面都无法进入。

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/904，sorry 本周五新版本修复
