### ISSUE TITLE
组件在Android 4.2 - 4.3 中 flex的兼容性问题

### ISSUE THREAD

**Issue by frankxin** [ant-design/ant-design-mobile#894]
#### Environment(required)

- antd-mobile version: 1.0.1
- Browser (or mark react-native) and its version: 安卓原生浏览器
- Operating environment (e.g. OS name) and its version: Android 4.2

#### What did you do? Please provide steps to re-produce your problem.

举个例子，使用图片选择器组件，添加多张图片，样式显示不正确

#### What do you expected?

样式正常

#### What happen?
根据caniuse上的描述:
![image](https://cloud.githubusercontent.com/assets/6349036/23348218/f787748a-fce2-11e6-896b-49d5a427187d.png)

#### Re-producible online demo

官网demo

**Comment by paranoidjk** [comment]
你可以尝试配置 autoprefixer 来支持： https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js#L178

关联 https://github.com/ant-design/ant-design-mobile/issues/751

**Comment by frankxin** [comment]
看起来你们的demo： https://mobile.ant.design/kitchen-sink/components/image-picker#image-picker-demo-0
应该是也用了autoprefixer，而且兼容性很高，除了android 4.2-4.3不能兼容
flex我们也在一直也在配合autoprefixer使用。
**但是问题是：** 使用autoprefixer并不能解决flex-wrap的问题
你们要不再确认下，真机测试我是都做了的。

期待你的回复
谢谢～

**Comment by frankxin** [comment]
实在抱歉，可能我一开始没说清楚，我的意思是**flex-wrap**的问题，你也可以找一台android 4.2或4.3的手机测试一下你们用到flex-wrap的页面

**Comment by warmhug** [comment]
Android 2.1 - Android 4.3 不支持 `flex-wrap: wrap` 换行，也不支持 `display: -webkit-box;` 旧语法里的 `-webkit-box-lines: multiple;` 换行，所以需要自己实现这个效果。

**Comment by frankxin** [comment]
@warmhug 你的意思是即使设置了`browsers: ['last 2 versions', 'Firefox ESR', '> 1%', 'ie >= 8', 'iOS >= 8', 'Android >= 4']`换行这个效果在antd-mobile也是不能实现的吗？
如果现在我要用antd-mobile并且需要兼容android4.2+有现成的解决方案吗？

**Comment by warmhug** [comment]
只是少了这一个换行的功能。目前看来先判断是 Android < 4.4 时、就自己计算总宽度、每个项目宽度等，手动设置换行。我们也将在官方 demo 里尝试下看看。

**Comment by frankxin** [comment]
好的，明白了～感谢～ @warmhug

**Comment by paranoidjk** [comment]
已经添加到 Faq， close。

https://github.com/ant-design/ant-design-mobile/wiki/FAQ#web-flex-wrap-%E5%9C%A8android-21---android-43%E5%85%BC%E5%AE%B9%E6%80%A7%E9%97%AE%E9%A2%98
