### ISSUE TITLE
Icon组件加载本地资源报错

### ISSUE THREAD

**Issue by mhcgrq** [ant-design/ant-design-mobile#895]
#### Environment(required)

- antd-mobile version: 1.0.0
- Browser (or mark react-native) and its version: chrome 56
- Operating environment (e.g. OS name) and its version: OS X 10.12.3

#### What did you do? Please provide steps to re-produce your problem.

Icon组件加载任意本地svg资源，使用webpack打包，在Chrome中代开，并同时打开devtool。

#### What do you expected?

无报错

#### What happen?

报错： `Cannot find module './#xxx.svg'`，如果这时候点击Resume，该资源能够正常加载

Icon组件源码中的`renderSvg`方法使用了try-finally，然而没有catch块，应该是这个原因导致的上述问题

**Comment by paranoidjk** [comment]
`报错： Cannot find module './#xxx.svg'，如果这时候点击Resume，该资源能够正常加载`

这段话的逻辑看不懂，既然svg存在为什么会进catch

**Comment by mhcgrq** [comment]
```
renderSvg = () => {
    let svg;
    try {
      svg = require(`./style/assets/${this.props.type}.svg`);
    } finally {
      return svg;
    }
  }
```
以上为`renderSvg`源码。
如果我使用`<Icon type={require('./xxx.svg')} />`，那么此时的`this.props.type`已经是一个合法路径，这样的话`try`代码块中又require了一次，就会报错，所以这里应该加入`catch`块来捕获这种错误。

**Comment by paranoidjk** [comment]
你应该没有正确配置 svg-sprite-loader，如果配置成功
```
import { Icon } from 'antd-mobile'

<Icon type={require('./src/svg/foo.svg')}/> // 在 Icon 内部 this.props.type === 'foo'
```

**Comment by paranoidjk** [comment]
最新版本 1.0.1, 请参考 [Icon文档](https://mobile.ant.design/components/icon) 使用

先close， 如果还有问题再repoen

**Comment by mhcgrq** [comment]
按照文档配置了webpack，还是会有问题。我使用webpack2.2.1，但我觉得应该不是webpack的问题。刚才又看了一下报错，我觉得这里的问题是这样的：
使用`<Icon type={require('./src/svg/foo.svg')}/>`，此时`this.props.type === #foo`。然而，源码中`svg = require(`./style/assets/${this.props.type}.svg`);`，也就是`svg = require(`./style/assets/#foo.svg`);`，然而`style/asserts`下并没有`foo.svg`，而是在`src/svg`下。此时，虽然`finally`块中返回了`undefined`，从而保证在`render`方法中正确判断为加载外部资源，但是由于缺少`catch`块，该错误依然会被抛出。并且这种错误只有在打开Chrome的devtool时才能看到，影响开发体验。

**Comment by paranoidjk** [comment]
@mhcgrq  是可以优化，但是跑下官方demo https://github.com/ant-design/antd-mobile-samples/tree/master/rn-web 并没有报错，你可以跑下试试

**Comment by mhcgrq** [comment]
@paranoidjk 我这里报错了，`Cannot find module './#money.svg'`
