### ISSUE TITLE
image-picker 华为不能调用相机只能选图库

### ISSUE THREAD

**Issue by jinchaoxiang** [ant-design/ant-design-mobile#896]
#### Environment(required)

- antd-mobile version:1.0.0
- Browser (or mark react-native) and its version:华为手机微信6.3
- Operating environment (e.g. OS name) and its version:

#### What do you expected?
希望既能调用摄像头也能调用图库

#### What happen?
只能调用图库

**Comment by paranoidjk** [comment]
@pingan1927 如果有测试机的话帮忙看下

**Comment by pingan1927** [comment]
@jinchaoxiang 
`
<input
  style={itemStyle}
  ref="fileSelectorInput"
  type="file"
  accept="image/jpg,image/jpeg,image/png,image/gif"
  onChange={() => { this.onFileChange(); }}
/>
`
底层实现是file类型的input，如果不能调用摄像头，好像js端也没有啥办法。

**Comment by pingan1927** [comment]
自定义选择图片的方法 `onAddImageClick`，看看示例，然后调用微信客户端提供的图片选择功能，应该就可以了。
https://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html#.E6.8B.8D.E7.85.A7.E6.88.96.E4.BB.8E.E6.89.8B.E6.9C.BA.E7.9B.B8.E5.86.8C.E4.B8.AD.E9.80.89.E5.9B.BE.E6.8E.A5.E5.8F.A3
