### ISSUE TITLE
antd-mobile toast api 取名问题

### ISSUE THREAD

**Issue by pigcan** [ant-design/ant-design-mobile#898]
Toast.offline 并不适合， 改为 Toast.exception 更合适些

**Comment by paranoidjk** [comment]
1.0.x 肯定不会做改api名字这种break change了
可以讨论下，如果合理，可以先多加一个 alias

**Comment by silentcloud** [comment]
@pigcan 如果你实在想用 exception，那后面加一个 exception 指向好了

**Comment by paranoidjk** [comment]
@silentcloud 你决定吧
也不一定组件加，可以暂时业务代码加，后续如果大版本要正式改名把alias去掉就好了
```js
import { Toast } from 'antd-mobile';

Toast.exception = Toast.offline;
```

**Comment by afc163** [comment]
offline 合适多了，exception 和 fail 语义不是一样的么？
