### ISSUE TITLE
[RN-Android ] Carousel 走马灯在做轮播图时，有明显的撕裂与闪烁感

### ISSUE THREAD

**Issue by Lxxyx** [ant-design/ant-design-mobile#899]
#### Environment(required)

- antd-mobile version: 1.0.1
- Browser (or mark react-native) and its version: 0.41.2
- Operating environment (e.g. OS name) and its version: MacOS 10.12.3 (16D32)

#### What did you do? Please provide steps to re-produce your problem.
使用Carousel 走马灯组件，嵌套三张图片实现轮播图效果，**安卓上在过渡时会有明显的撕裂与闪烁感** 而ios正常。

#### What do you expected?
安卓上轮播图过渡效果正常。

#### Re-producible online demo
https://gist.github.com/Lxxyx/478704897e583e6cfb619d598f9cb23f

**Comment by silentcloud** [comment]
你用什么设备？ 我试了模拟器和小米的一个设备都还 ok 的

**Comment by Lxxyx** [comment]
@silentcloud 

刚对多种情况进行了测试，
均是网络图片不会有问题，
本地图片的话，三张不一样不会有问题，如果三张是一样的图片则会有明显的撕裂与闪烁感。

这是测试用的本地图片：
![](http://7xoxxe.com1.z0.glb.clouddn.com/2017-02-28-1.png)

**Comment by Lxxyx** [comment]
再次确认，rm -rf node_modules/ant-design 然后重新安装ant-design后，本地图片闪烁的BUG也消失了。
谢谢~

**Comment by Lxxyx** [comment]
最后是安装的 0.9.17版本

**Comment by silentcloud** [comment]
@Lxxyx 好，我测试一下相同图片看看

**Comment by Lxxyx** [comment]
@silentcloud 最后的测试结果，应该是版本的问题。具体可以看回复，我修改了回复。

**Comment by silentcloud** [comment]
@Lxxyx 找到问题所在了， ScrollView 的 `removeClippedSubviews={true}` 的问题，这里改成 `false`  就 ok 了，你试试直接改 antd-mobile/lib/carousel/index.js 试试；

等周五的 1.0.2

**Comment by Lxxyx** [comment]
@silentcloud Ok。谢谢啦
