### ISSUE TITLE
npm install 报错并卡住

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design-mobile#9]
npm install antd-mobile --save

npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:492:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
fetchMetadata -> vacuum-f - |#################-----------------------------------------|

**Comment by benjycui** [comment]
试下 CNPM 先？ https://npm.taobao.org/

**Comment by dyf2015** [comment]
CNPM 没启动。。。

**Comment by benjycui** [comment]
> CNPM 没启动。。。

???

不就是个安装么？

**Comment by dyf2015** [comment]
网站进不去 https://npm.taobao.org/

cnpm安装报错

**Comment by dyf2015** [comment]
ResponseError: read ECONNRESET (req "error"), GET https://registry.npm.taobao.org/antd-mobile/* -1 (connected: true, keepalive socket: false)
headers: {}
Error: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at TLSWrap.onread (net.js:563:26)

**Comment by silentcloud** [comment]
@dyf2015  
![image](https://cloud.githubusercontent.com/assets/1698185/17281721/77645ad2-57d0-11e6-8b88-d0eb597fa9be.png)
你网络有无问题

**Comment by dyf2015** [comment]
网络正常的

**Comment by silentcloud** [comment]
![image](https://cloud.githubusercontent.com/assets/1698185/17281768/e69a26de-57d0-11e6-82e0-1f6aa472de0f.png)

你 cnpm info antd-mobile 能查到么

**Comment by dyf2015** [comment]
这个可以查到

**Comment by dyf2015** [comment]
D:\My_Develop>cnpm install antd-mobile --save
ResponseError: read ECONNRESET (req "error"), GET https://registry.npm.taobao.org/antd-mobile/* -1 (connected: true, keepalive socket: false)
headers: {}
Error: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at TLSWrap.onread (net.js:563:26)

**Comment by dyf2015** [comment]
但安装报这个，奇怪

**Comment by silentcloud** [comment]
![image](https://cloud.githubusercontent.com/assets/1698185/17281815/6962b0b8-57d1-11e6-86e0-1109089a614d.png)

我能安装

**Comment by dyf2015** [comment]
我这对这个网站的访问 不稳定 https://npm.taobao.org/package/antd-mobile

时好时坏

**Comment by dyf2015** [comment]
换了2种网络

**Comment by dyf2015** [comment]
![image](https://cloud.githubusercontent.com/assets/16314313/17281873/188f2850-57d2-11e6-9104-ce3c94bb5aee.png)
大部分情况是这样的

**Comment by dyf2015** [comment]
抱歉，找到原因了是公司网络的问题

**Comment by silentcloud** [comment]
@dyf2015 ok
