### ISSUE TITLE
picker组件 disabled 支持

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design-mobile#90]
#### 本地环境

- antd-mobile 版本：0.7.2
- 操作系统及其版本：
- 浏览器及其版本：

#### 你做了什么？

` <Picker data={data} cols={1} extra="请选择" value={["1"]} visible={userTypevisible} {...formFiledInfo.userType}>
                        <List.Item arrow="horizontal">用户类型</List.Item>
                    </Picker>`
由于没有editable属性，所以我使用visible状态控制可操作或不可操作，当visible从true切换成false时，
下拉的选项面板会出现再隐藏。感觉是做了一次点击事件后显示下拉的选项面板，再隐藏下拉的选项面板.
还有就是能这样做吗？

**Comment by warmhug** [comment]
> 感觉是做了一次点击事件后显示下拉的选项面板，再隐藏下拉的选项面板

这么做很怪。
是需要 list.Item 支持 editable 或 disabled 吗？ @pingan1927 看下

**Comment by ksh033** [comment]
@warmhug 是我自己使用有问题，我现在自己判断用不同组件去做显示。
因为我看 InputItem 组件是有editable。picker组件同样是绑定到表单是不是也可以提供editable。这样做一些表单类的页面从编辑切换查看会更方便一点。

**Comment by pingan1927** [comment]
InpuntItem是受控表单类组件，List.Item主要用来展示，本身已经提供了onClick。业务上使用，可以在render的时候，控制List.Item 要不要套上一个Picker。

不知道我是不是说到点子上了

**Comment by yiminghe** [comment]
@pingan1927 补充个 demo

**Comment by yiminghe** [comment]
建议加个 disabled 属性，所有组件都要有

**Comment by ksh033** [comment]
@pingan1927 是。可能是我的做法有问题，把编辑页和查看页做在一起，我想直接用一个状态去控制组件是否是可编辑。我现在已经改了做法了，根据状态去render不同的界面，不过比较麻烦就是所有元素我要写两次。

**Comment by pingan1927** [comment]
`<Picker><List.Item /></Picker>`和<List.Item />的区别。

不过<List.Item />是可以加个`disabled`属性。
这样`<Picker><List.Item /></Picker>`只需写这个就够了。

感谢反馈。

**Comment by yiminghe** [comment]
ListItem 不是输入型组件，最好加在 Picker 上

**Comment by pingan1927** [comment]
`Picker`加， @warmhug 来改吧
