### ISSUE TITLE
测试方案

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design-mobile#900]
1. 引入 jest 对所有的 demo 做 snapshot 测试（同 antd 的做法）；
1. 引入 enzyme 用于 web 组件的测试；

@ant-design/ant-design-team 其他还有什么想法吗？

**Comment by afc163** [comment]
native 的测试方案？

**Comment by yesmeck** [comment]
native 也可以用 jest 的 snapshot 的。不过不能用 enzyme，类似的行为测试需要研究下。

**Comment by paranoidjk** [comment]
可以尝试下能不能跑 https://github.com/airbnb/enzyme/blob/master/docs/guides/react-native.md

**Comment by warmhug** [comment]
@yesmeck 找个组件写个例子？方便大家参考一起做

**Comment by yesmeck** [comment]
@warmhug 👌

**Comment by paranoidjk** [comment]
建议 rc-tools 内置的测试方案也切换到 jest + enzyme 统一下，体验也更好

https://github.com/react-component/tabs/commit/7677efe487bd059d4c95030a067f3e8cc52a3413

**Comment by yesmeck** [comment]
之前提过，jest 配置比较简单，就没没内置。

**Comment by GZWZC** [comment]
用jest跑测试的时候 会遇到引入css.web.js的问题吗
