### ISSUE TITLE
Drawer 组件在React Native上运行时，不能通过按钮点击弹出，从左侧向右滑动可弹出，想问一下就是这样的吗？能通过点击按钮弹出吗？

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design-mobile#902]

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/components/drawer/demo/basic.tsx

**Comment by silentcloud** [comment]
![test](https://cloud.githubusercontent.com/assets/1698185/23389862/9d4a6518-fda5-11e6-8d45-61baa74523f4.gif)

代码见楼上

**Comment by paranoidjk** [comment]
@silentcloud 话说手机录屏咋录的？模拟器？

**Comment by silentcloud** [comment]
@paranoidjk 模拟器用 LICEcap (mac)，真机用 Airshou (iOS)

**Comment by zhulichao** [comment]
能弹出了，非常感谢！
