### ISSUE TITLE
tabs升级到1.0.1版本后，初始化就报错：Failed prop type: Invalid prop `className` of type `object` supplied to `Tabs`, expected `string`.

### ISSUE THREAD

**Issue by liuxingling** [ant-design/ant-design-mobile#904]
Environment(required)

antd-mobile version:1.0.1
Browser (or mark react-native) and its version:版本 56.0.2924.87 (64-bit)
Operating environment (e.g. OS name) and its version:mac
What did you do? Please provide steps to re-produce your problem.

就用的官方示例代码
<Tabs defaultActiveKey="1">
          <TabPane tab="选项卡一" key="1">
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
              选项卡一内容
            </div>
          </TabPane>
          <TabPane tab="选项卡二" key="2">
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
              选项卡二内容
            </div>
          </TabPane>
          <TabPane tab="选项卡三" key="3">
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '5rem', backgroundColor: '#fff' }}>
              选项卡三内容
            </div>
          </TabPane>
        </Tabs>
What do you expected?

正常运行

What happen?

![image](https://cloud.githubusercontent.com/assets/26077947/23392665/582ed49c-fdb8-11e6-82fe-97b79d0c3a8d.png)

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/893

**Comment by paranoidjk** [comment]
能给出完整的示例代码吗？最好格式化一下，谢谢

**Comment by paranoidjk** [comment]
https://codepen.io/warmhug/pen/bwRPvx

**Comment by liuxingling** [comment]
![image](https://cloud.githubusercontent.com/assets/26077947/23393609/fc229b64-fdbe-11e6-9e26-93072a4d1d91.png)

我就copy的官方demo这一段

**Comment by liuxingling** [comment]
@paranoidjk  我直接copy的官方demo

**Comment by zhouzefei** [comment]
请问解决了么？我也有同样的
![image](https://cloud.githubusercontent.com/assets/8566935/23400059/90975622-fddd-11e6-8969-f25f9a54407b.png)

**Comment by paranoidjk** [comment]
sorry， 将在本周五的release `1.0.2` 修复这个问题

**Comment by liuxingling** [comment]
@paranoidjk  能不能帮忙紧急解决下这个bug啊，我们今天已经进入测试阶段了。
在安卓机的uc和app里，只要用到tabs的页面都进不去

**Comment by paranoidjk** [comment]
@liuxingling  那我给你发一个beta版本，你先用这个beta吧

**Comment by paranoidjk** [comment]
@liuxingling 或者你参考这个commit自己改一下源码？ https://github.com/ant-design/ant-design-mobile/commit/a0f43fdd6b919a8cf6f1b3ba217d3d5ba7726af2
