### ISSUE TITLE
Steps 组件在RN环境下还是不能水平排列吗

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#905]
#### Environment(required)

- antd-mobile version:1.0.1
- Browser (or mark react-native) and its version:react-native 0.39.2
- Operating environment (e.g. OS name) and its version:android 4.4

**Comment by silentcloud** [comment]
暂时没有，目前先处理现有组件的问题，后面抽时间加上

当然  pr welcome， 有相同的 issue 了，这个就关掉了  

#780
