### ISSUE TITLE
Carousel -> Cannot read property 'scrollTo' of undefined

### ISSUE THREAD

**Issue by rendongsc** [ant-design/ant-design-mobile#906]
#### Environment(required)

- antd-mobile version: 1.0.1
- Browser (or mark react-native) and its version: RN 0.40
- Operating environment (e.g. OS name) and its version:
#### 问题描述
 Android系统，按返回键退出App后，再次进入App，Carousel 报错：
![qq 20170228150120](https://cloud.githubusercontent.com/assets/12553638/23394926/cd9b5c9c-fdc6-11e6-9c03-d2fd3abca128.png)

**Comment by silentcloud** [comment]
@paranoidjk `componentWillUnMount` =>  `componentWillUnmount`

**Comment by paranoidjk** [comment]
@rendongsc  sorry...

肯定是迁移es6那次大改动, @silentcloud 你修了吗？

**Comment by silentcloud** [comment]
@paranoidjk 修了

**Comment by paranoidjk** [comment]
@silentcloud 辛苦，RN的改动因为只涉及语法所以当时没跑app来测试，后面尽量自测+MR
