### ISSUE TITLE
ActionSheet 中点击蒙层关闭时是否可以增加相关返回

### ISSUE THREAD

**Issue by pigcan** [ant-design/ant-design-mobile#908]
可以在 callback 中设置返回字段

也可以是个相关的事件

**Comment by paranoidjk** [comment]
意思需要点击蒙层关闭的回调？

用`onClose`就可以的

**Comment by silentcloud** [comment]
不应该有 onClose 这样的 api，应该是通过回调的 index 来判断 @pigcan ，参考 native，RN

**Comment by paranoidjk** [comment]
@silentcloud 有啊，rc-dialog 的 `onClose` https://github.com/react-component/dialog#rc-dialogweb

**Comment by silentcloud** [comment]
@paranoidjk api 尽量平台通用保持一致性，这也是最初做这个库的出发点

**Comment by silentcloud** [comment]
@warmhug 来参与一下讨论

**Comment by pigcan** [comment]
@silentcloud  现在点击蒙层关闭，并没有在回调中体现 index 吧，按理是需要和 cancelButton 保持一致的.

**Comment by silentcloud** [comment]
@pigcan 恩，点击蒙层应该是返回取消的 index，web 是有 bug 的，这个我等会改

**Comment by warmhug** [comment]
index 有的，看 demo 写法

**Comment by wu1991924** [comment]
为什么点击蒙层没办法关闭
