### ISSUE TITLE
Stepper要指定readOnly={false}才可修改值，省略该属性不能修改，不知道本身是这样设计的吗，还是我有哪里写的不对呢？

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design-mobile#909]
```
<Stepper key="0" max={10} min={1} defaultValue={3} value={this.state.stepperValue} onChange={this.onStepperChange} />
```

这样是不能修改的，添加了readOnly={false}才能修改。

小米Note手机，Antd Mobile 1.0.1。

**Comment by silentcloud** [comment]
@zhulichao 你是指这个同样的问题？ https://github.com/ant-design/ant-design-mobile/issues/890

**Comment by paranoidjk** [comment]
@silentcloud 感觉要在patch里改掉，这个默认值应该都会觉得不正常，没人会这么用的

**Comment by silentcloud** [comment]
@paranoidjk 那就在 patch 里改吧，有人有问题再反馈好了

我来改吧

**Comment by zhulichao** [comment]
@silentcloud  跟您说的那个890是同样的问题。
