### ISSUE TITLE
Stepper 支持 input 输入，和长按连续增加步长

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile#91]
如图：
![image](https://cloud.githubusercontent.com/assets/2011119/17659564/023dc43c-6306-11e6-81d4-d3d614a618c0.png)

**Comment by yiminghe** [comment]
input-number 支持连按 @afc163

**Comment by afc163** [comment]
参考：https://github.com/vlad-ignatov/react-numeric-input/blob/master/src/NumericInput.jsx
