### ISSUE TITLE
Accordion 手风琴 不能默认展开

### ISSUE THREAD

**Issue by zjxpcyc** [ant-design/ant-design-mobile#911]
#### Environment(required)

- antd-mobile version: 1.0.0
- Browser (or mark react-native) and its version: chrome 或者 微信内置浏览器
- Operating environment (e.g. OS name) and its version: win10 x64, node(64) 6.9.5
- Dva 1.2.1

#### What did you do? Please provide steps to re-produce your problem.

// example
const foo = bar => bar

Accordion defaultActiveKey = {foo(bar)}

#### What do you expected?

Accordion 可以正常展开

#### What happen?

Accordion 没有展开, 只有  defaultActiveKey = 'key_xxx' 这种写死的字串，才能展开

#### Re-producible online demo

无

**Comment by paranoidjk** [comment]
请认真阅读issue模板，给我们一个可重现的demo会极大提高效率，参考这个 http://codepen.io/paranoidjk/pen/LWpaKe

**Comment by zjxpcyc** [comment]
真是x了狗了。
demo [http://codepen.io/anon/pen/vxNqoa?editors=0010](http://codepen.io/anon/pen/vxNqoa?editors=0010) 这边显示是正常的。
但是我环境上的代码，跟demo的逻辑是一样的。
关了

**Comment by paranoidjk** [comment]
@zjxpcyc check版本是不是最新1.0.1？尝试`rm -rf node_modules && npm i`重装依赖
