### ISSUE TITLE
Input 组件 ref 无法获取值

### ISSUE THREAD

**Issue by shichenda** [ant-design/ant-design-mobile#915]
<Input  ref="name" />

this.refs.name.value  获取组件的值是 undefinde

**Comment by paranoidjk** [comment]
这是正常的，refs获取到的只是instance

**Comment by benjycui** [comment]
可以增加 `Input[innerRef]`, see: [`styled-component`](https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#refs-to-dom-nodes)

事实上，对于需要使用 ref 的组件，比如大多数的表单控件都是，都可以考虑增加 `innerRef`。

**Comment by paranoidjk** [comment]
stringRef 我是不倾向加的。callbackRef 可以考虑，但没那么必要，目前我们还没碰到有需求要去接触到Input的真实dom
