### ISSUE TITLE
Tabs组件出现 className的警告

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design-mobile#916]
antd-mobile:1.0.1

Tabs组件：

出现警告：
 Warning: Failed prop type: Invalid prop `className` of type `object` supplied to `Tabs`, expected `string`.

**Comment by paranoidjk** [comment]
Duplicate with https://github.com/ant-design/ant-design-mobile/issues/893

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/904 sorry 本周五新版本修复
