### ISSUE TITLE
Picker 组件 快速滑动到一个选项的时候点击确定，数据没有改变。

### ISSUE THREAD

**Issue by vnice** [ant-design/ant-design-mobile#918]
#### Environment(required)

- antd-mobile version:antd-mobile 1.01
- Browser (or mark react-native) and its version: Iphone6p Safair
- Operating environment (e.g. OS name) and its version:

#### What did you do? Please provide steps to re-produce your problem.

在使用Picker 组件的时候，需要选择一项，有时候滑动太快，看到滑动到一个项目，点了确定，
发现值没有改变。再次点开Picker，回显的时候又是刚刚选择的值。以下是我的测试步骤。

官方demo中的Picker选择器 ，用第三个 `选择地区(单列)` 这个测试
从第一个选项安徽省快速滑动到最后面的浙江省，**在浙江省这三个字放大前一刻快速点击确定**，Picker的值没有改变的，但是再打开Picker又是选中的，造成了不一致的效果
发现Picker 滑动到一项等字体变大才代表真的选中，在这之前有一个时间差会造成用户以为选中了那一项，点了确定，其实没有选中。

#### Re-producible online demo
使用Iphone 浏览器访问官方demo中的Picker选择器 ，用第三个 `选择地区(单列)` 这个测试

**Comment by paranoidjk** [comment]
实测了几次很难重现 @warmhug 看下，没啥影响就关掉

**Comment by vnice** [comment]
@paranoidjk 有影响的，我们用户反馈发生过几次了，用户点击确认太快以为选择了那一个选项，但是那个选项的滑动动画还未执行完点击了确定关闭了picker，其实没有选中。
发生频率挺高的。我用自己手机访问官网上的Picker demo  录制了一个gif，不知道能不能看到
![antd-mobile](https://cloud.githubusercontent.com/assets/5074080/23593205/a49ea900-0246-11e7-9214-39e02779d873.gif)

**Comment by Liuqing650** [comment]
这个BUG确实有，不知道咋解决，我这里也遇到了

**Comment by paranoidjk** [comment]
@Liuqing650 @vnice 看了下 IOS 原生的 DatePicker, 也是需要等待动画完毕的，antd-mobile 决定不做修改，保持一致。

**Comment by a4825917** [comment]
我也遇到了，报的错误是内存溢出，有人解决了吗 - -！！
