### ISSUE TITLE
Tabs标签项目中使用报错，ios页面正常使用，安卓手机页面无法显示

### ISSUE THREAD

**Issue by manan1234** [ant-design/ant-design-mobile#922]
#### Environment(required)

- antd-mobile version: 1.0.0
- Browser (or mark react-native) and its version: 
- Operating environment (e.g. OS name) and its version:

#### What did you do? Please provide steps to re-produce your problem.

使用antd-mobile中的Tabs标签页的时候组件有bug，在Riddle中使用的时候，提供的例子是，报错。
![Uploading image.png…]()

#### What do you expected?

希望优化修改一下，

#### What happen?

报错时，安卓手机页面完全无法显示，ios可以正常显示

**Comment by manan1234** [comment]
报错内容为：
Warning: Failed prop type: Invalid prop `className` of type `object` supplied to `Tabs`, expected `string`.
    in Tabs (created by Tabs)
    in Tabs (created by TabExample)
    in div (created by TabExample)
    in TabExample

**Comment by silentcloud** [comment]
@manan1234 已知问题 

https://github.com/ant-design/ant-design-mobile/issues/916
https://github.com/ant-design/ant-design-mobile/issues/904
