### ISSUE TITLE
InputItem 弹出虚拟键盘位置不准

### ISSUE THREAD

**Issue by wangcongyi** [ant-design/ant-design-mobile#923]
#### Environment(required)

- antd-mobile version:
1.0.1
- Browser (or mark react-native) and its version:
IOS 10.2.1 内置Safari浏览器

#### What did you do? Please provide steps to re-produce your problem.

使用InputItem组件 弹出的虚拟键盘挡住了页面
本以为是自己使用有误
用手机浏览官网，也是一样会遮住的
使用原生的 input 则没有此问题

![image](https://cloud.githubusercontent.com/assets/13843979/23500489/411c171a-ff6b-11e6-916d-d6be48c794ec.png)

#### What do you expected?

保持和原生一样的效果

**Comment by silentcloud** [comment]
@wangcongyi 这个不是组件的问题，组件不会去控制键盘显示之类的；需要你自己去处理排查

**Comment by silentcloud** [comment]
@pingan1927 这个问题你看哈，我直接在 safari 调试，删除生成的 input，然后手动再加上 input 就没没问题了，直接生成的确实有 LZ 反馈的问题在

**Comment by iyutao** [comment]
输入框被键盘遮挡是通病，业务上可用 `input.scrollIntoView` 来解决

**Comment by wangcongyi** [comment]
@iyutao  呃...那我为什么不用原生的？

**Comment by paranoidjk** [comment]
scrollIntoView在移动端兼容性如何？可以考虑集成到inputitem onfocus里

**Comment by pingan1927** [comment]
```
this.scrollIntoViewTimeout = setTimeout(() => {
  try {
    (document.activeElement as any).scrollIntoViewIfNeeded();
  } catch (e) { }
}, 0);

**Comment by pingan1927** [comment]
@wangcongyi 在iOS 10.3 beta原生safari浏览器上的确表现有点异常，但是通过支付宝或者微信客户端打开，表现符合预期，Android原生浏览器也基本表现正常。

**Comment by silentcloud** [comment]
@pingan1927 10.2 正式版，包括模拟器都是异常的

**Comment by pingan1927** [comment]
我查查`scrollIntoViewIfNeeded`和`scrollIntoView`用哪个好点

**Comment by wangcongyi** [comment]
@pingan1927 如果是内核问题 就有点蛋疼了....

> 但是通过支付宝或者微信客户端打开，表现符合预期，
如果 APP里嵌入HTML5页面会有问题么？

**Comment by silentcloud** [comment]
@wangcongyi  APP 里嵌入 HTML5，相当于使用的 webview，和 微信 支付宝相同的，应该不会有问题

**Comment by paranoidjk** [comment]
@wangcongyi 碰上某个特殊内核有问题，那你可以在业务代码里用js来模拟scrollIntoView的功能

**Comment by pingan1927** [comment]
@wangcongyi 如图，还是忍忍吧，`scrollIntoView`这个方法的效果相比下更加不好，会将活动的`input`移动到很靠上的位置

![input](https://cloud.githubusercontent.com/assets/347649/23539503/c21392c0-0016-11e7-8182-6845f74767b0.png)

![img_0253](https://cloud.githubusercontent.com/assets/347649/23539505/c6a10138-0016-11e7-89d7-c53d62759b09.PNG)

![img_0252](https://cloud.githubusercontent.com/assets/347649/23539509/c9befeec-0016-11e7-8882-b88a18ce679b.PNG)

**Comment by pingan1927** [comment]
如 @paranoidjk 所说，如果在iOS的safari中运行业务，确实需要解决这个问题，可以在onFocus 时再次执行下`scrollIntoView`,组件内部还是使用`scrollIntoViewIfNeeded`合理点。

**Comment by wangdicoder** [comment]
键盘遮挡在IOS React Native中还是有问题，你们官方的Expo展示的例子都有bug。“格式”section下方的那些输入组件根本看不见🙈。

![img_15cdb001e1fb-1](https://user-images.githubusercontent.com/7374042/36624871-481896a6-1969-11e8-94fe-b623af7e175a.jpeg)

**Comment by wangcongyi** [comment]
@wangdicoder  并没有真正解决问题，只是规避了。你试试用用原生的
