### ISSUE TITLE
Picker,DatePicker组件在android手机浏览器中无法正常弹出

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design-mobile#924]
antd-mobile:v1.0.0  ，v1.0.1

Picker,DatePicker组件在android手机浏览器中无法正常弹出，点击弹出，然后就自动关闭了，

版本回退到v0.9.X，是没有问题的。

但是将Demo放在Android浏览器中，这个两组件是没有出现问题的。

请问可能是什么情况导致？

**Comment by paranoidjk** [comment]
描述清楚一点？ 到底 什么组件 什么版本 在 什么设备 什么浏览器 有什么问题

**Comment by paranoidjk** [comment]
请花点时间阅读issue模板，给我们提供一个在线demo有助于我们帮你快速定位问题 http://codepen.io/paranoidjk/pen/LWpaKe

**Comment by MotorFu** [comment]
版本：1.0.0和1.0.1
组件：Picker和DataPicker
设备：android
浏览器：android上所有浏览器
问题：点击后，弹窗出现后立即又关闭了

疑问：组件上的onClick事件变成了onTouch事件？

备注：你给的在线demo不能重现这个问题。

附言：升级到1.0.0以后，在其他组件上写的onClick事件都变成onTouch事件了，导致会出发到下一个页面的按钮，从而进入下一级页面。
但是，我将antd-monile降到0.9.x版本后，就没有出现这些问题。

**Comment by warmhug** [comment]
看文档，引用 fastclick 。不行再在下个页面按钮点击里设置 e.preventDefault(); 试试

**Comment by MotorFu** [comment]
都使用了，，但是在android 浏览器上还是会自动触发到下个页面的按钮上

**Comment by paranoidjk** [comment]
@MotorFu  在codepen上提供你的代码demo， http://codepen.io/paranoidjk/pen/LWpaKe  我找台android手机调试下，刚看了官方的demo在android上并没有重现

**Comment by MotorFu** [comment]
是的，我也看了官方demo，
①目前解决Android事件穿透的问题，只能在当前 按钮跳转时加上setTimeout延迟。

②至于临时解决DatePicker和Picker的弹出问题是使用自定义子组件
export const PickerChildren = (props) => (
    <div onClick={props.onClick}>
      <List.Item extra={props.extra} arrow={props.arrow}>{props.label}</List.Item>
    </div>
);
<Picker data={StatureData} 
              cols={1}
              {...getFieldProps('stature', {
                        initialValue: [initStature]
              })}>
       <PickerChildren label="身高" arrow="horizontal"/>
</Picker>
用上面的方式就解决了点击Picker触发两次的问题。

③出现的问题：              
不能直接在Picker组件中加入<List.Item  arrow="horizontal">日期</List.Item>,加上就出现问题了。

**Comment by MotorFu** [comment]
在codeopen上好像不能重现这个问题、、

**Comment by paranoidjk** [comment]
@MotorFu 我的意思是你Demo托管在codepen上，我用Android设备来调试

**Comment by paranoidjk** [comment]
不能重现的都close，还有问题请回复或者reopen

**Comment by MotorFu** [comment]
Picker组件问题已经解决了，删除node_modules，重新nmp一下就好了，但是在android浏览器上点击事件触发到下一个页面的问题还没有解决，正在研究中...

**Comment by jinchaoxiang** [comment]
请问楼主是怎么解决问题的 
我现在也有这个问题 部分ios用户点击picker就关闭 
安卓是点击picker的确定按钮后自动聚焦上次点击过的input 
react-15.3 antd-mobile 1.0.0
