### ISSUE TITLE
use 'Tabs' components's bug

### ISSUE THREAD

**Issue by jaune001** [ant-design/ant-design-mobile#926]
#### Environment(required)

- antd-mobile version:
- Browser (or mark react-native) and its version:
- Operating environment (e.g. OS name) and its version:

#### What do you expected?
how to solve this error?

#### What happen?
antd-mobile@1.0.1

show error when i use 'Tabs' component

![image](https://cloud.githubusercontent.com/assets/19927938/23537787/7363fde8-0009-11e7-810e-4a018c20dbec.png)

#### Re-producible online demo
![image](https://cloud.githubusercontent.com/assets/19927938/23537805/86c6f64c-0009-11e7-99df-aa52ecc184e8.png)

**Comment by paranoidjk** [comment]
duplicated https://github.com/ant-design/ant-design-mobile/issues/916

**Comment by paranoidjk** [comment]
今天会release新版修复
