### ISSUE TITLE
[RN] Carousel组件在切换场景后，定时器依然运行，导致应用报错崩溃

### ISSUE THREAD

**Issue by Lxxyx** [ant-design/ant-design-mobile#927]
#### Environment(required)

- antd-mobile version: 1.0.1
- Browser (or mark react-native) and its version: 0.41
- Operating environment (e.g. OS name) and its version: MacOS 12

#### What did you do? Please provide steps to re-produce your problem.
使用react-native-router-flux和Carsoul组件，然后跳转到别的页面。

**跳转的时候用的是react-native-router-flux的reset模式，会清空历史栈。**

#### What do you expected?
应用正常运行

#### What happen?
应用报错崩溃
提示：` Cannot read property 'scrollTo' of undefined`

查看Ant源代码发现:

```typescript
    this.autoplayTimer = setTimeout(() => {
      if (!infinite && (selectedIndex === count - 1)) {
        // !infinite && last one, autoplay end
        return this.setState({ autoplayEnd: true });
      }
      this.scrollNextPage(); // !!!报错的这行
    }, autoplayTimeout * 1000);
```
在`scrollNextPage函数`中，

```typescript
 (this.refs as any).scrollview.scrollTo({ x, y })
```
this.refs.scrollview是不存在的。

#### Re-producible online demo
无demo。

**Comment by Lxxyx** [comment]
通过打断点时发现没有执行componentWillUnmount函数，导致了出错

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/issues/906

**Comment by paranoidjk** [comment]
sorry，今天会release新版本修复

**Comment by Lxxyx** [comment]
@paranoidjk 好的……没想到是拼写错误……
