### ISSUE TITLE
Progress如何结合路由使用？

### ISSUE THREAD

**Issue by wanrengang** [ant-design/ant-design-mobile#929]
如题
我现在不知道如何把Progress消失掉，在外层加样式控制没用不知道为什么

**Comment by paranoidjk** [comment]
无意义的提问，请仔细阅读issue模板；

隐藏progress有很多方法，样式 display:none 之类的不可能没用，请提供一个可复现的在线demo（参见issue模板）

一般建议js来控制，类似如下
```
<div>
{this.state.showProgress && <Progress/>}
</div>
```

**Comment by wanrengang** [comment]
@paranoidjk 不好意思  是我弄错了，是可以隐藏的，
