### ISSUE TITLE
升级ant.design.mobile后并使用高清方案后页面效果在iphone6p上的效果为什么比iphone6上的看着要小

### ISSUE THREAD

**Issue by lichengit** [ant-design/ant-design-mobile#930]
本地环境

antd-mobile 版本：1.0.1
mac
chrome最新版：
你做了什么？
antd-mobile 0.7.x升级到1.0.1并引用了antd-mobile的高清方案

你期待的结果是

像官网一样正常显示

实际上的结果：

页面确实“高清了”，但是iphone6p比iphone6上看着还要小，没有自适应

**Comment by paranoidjk** [comment]
* 异常排查：通常以iPhone6模拟器为基准，查看`document.documentElement.clientWidth`（浏览器渲染出来的网页宽度），
  * 如果是750，则代表高清方案设置成功，接下来就是webpack的设置。
  * 如果是350，代表可能写死了meta标签，请先完成动态设置viewport这一步。
  * 如果是980左右，代表没有生成meta标签也没有写死meta标签，按照PC浏览器来渲染网页宽度。请先完成动态设置viewport这一步。


https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE
