### ISSUE TITLE
Steps.Step: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by safarishi** [ant-design/ant-design-mobile#934]
#### Environment(required)

- antd-mobile version: antd-mobile@0.9.16
- Browser (or mark react-native) and its version: chrome 版本 56.0.2924.87 (64-bit)
- Operating environment (e.g. OS name) and its version: OS X 10.11.6

#### What did you do? Please provide steps to re-produce your problem.

```
import { Icon, Steps } from 'antd-mobile'

const { Step } = Steps

<Steps>
  <Step title="第一步" />
  <Step title="第二步" />
  {
    Array(3).fill(1).map(v => (
      <Step key={Math.random()} title="第三步" />
   ))
  }
</Steps>
```

#### What do you expected?

I want it to render with 5 steps

#### What happen?

But it got an error with "Cannot read property 'status' of undefined"

**Comment by paranoidjk** [comment]
have you tried the latest version `1.0.1` ?

**Comment by safarishi** [comment]
yes I try it but got the same error

**Comment by paranoidjk** [comment]
can you give us a online demo ? http://codepen.io/paranoidjk/pen/LWpaKe

**Comment by safarishi** [comment]
ok, I try it

**Comment by safarishi** [comment]
the demo is here http://codepen.io/safarishi/pen/QpNPyP
it not working will

**Comment by paranoidjk** [comment]
I have found the problem, you can't this
```js
{
  Array(3).fill(1).map(v => (
     <Step key={Math.random()} title="第三步" />))
  }
```

this will cause this.props.children to be something like this `[Step, Step, Step, [Step, Step, Step]]`, but the outter `Steps` need all it's children to be `Step`

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/components/steps/index.web.tsx#L47

**Comment by paranoidjk** [comment]
Or maybe we can change code to support usage like this, but it's need to be dicussed，I will consider about this in next week release

cc @warmhug

**Comment by safarishi** [comment]
Ok, thanks.

**Comment by paranoidjk** [comment]
@safarishi sorry, i was wrong, `React.children` will auto flattens the array, but our code have a bug to deal with this.  so actually you can write cod like this, i will fix it

**Comment by paranoidjk** [comment]
will release on 03/10 version 1.0.4
