### ISSUE TITLE
Tabs bar 修改标签数 右侧出现空白间隙

### ISSUE THREAD

**Issue by zhouzefei** [ant-design/ant-design-mobile#935]
#### Environment(required)

- antd-mobile version:1.0.2
- Browser (or mark react-native) and its version: chrome
- Operating environment (e.g. OS name) and its version: all

#### What did you do? Please provide steps to re-produce your problem.
按照demo来没问题
![image](https://cloud.githubusercontent.com/assets/8566935/23577240/e1639ee8-00f4-11e7-8e68-5b1e7bc62aa3.png)
![image](https://cloud.githubusercontent.com/assets/8566935/23577242/f5054136-00f4-11e7-8a62-172190c01a88.png)
<br/>
---------------------------------------

但是：我修改pageSize，以及显示的标签数量
![image](https://cloud.githubusercontent.com/assets/8566935/23577252/1c5450f6-00f5-11e7-8fb8-7726bc9d00ed.png)
![image](https://cloud.githubusercontent.com/assets/8566935/23577256/2496ddd8-00f5-11e7-8f5b-380ad5bc4e91.png)
<br/>
---------------------------------------

而且，标签内容值少的情况，既然设置了pageSize，不是应该等分的么
![image](https://cloud.githubusercontent.com/assets/8566935/23577409/60cd5e22-00f9-11e7-88fb-4abe8d66ee33.png)

#### What do you expected?
pageSize与标签数之间的关系？？？如何去掉这个空白的间隙

#### What happen?
标签数好像大于10都没问题，小于10，，就会存在问题

**Comment by paranoidjk** [comment]
sorry, please try `1.0.3`

**Comment by zhouzefei** [comment]
thanks
