### ISSUE TITLE
高清适配问题

### ISSUE THREAD

**Issue by xshua06** [ant-design/ant-design-mobile#936]
在iphone6（750px）,设置某个元素7rem;显示正常，不会出现横向滚动条。
但是在iphone 5s（640px）下显示就会出现滚动条，7rem = 700px > 640px
原因是baseFontSize都是100；基准的BaseREM = 100;

**Comment by pingan1927** [comment]
`window.devicePixelRatio`都是2，决定了iPhone6，iPhone5s的rem都是100px，7rem这个是700px，我不知道你这个issue想问什么问题，某个元素的宽度一般都用flex布局。要写死x rem的话就需要考虑到最小屏幕即320px的适配情况。
