### ISSUE TITLE
在Android浏览器，List.Item,Button组件的onClick事件传递到下一界面，导致自动触发点击事件

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design-mobile#937]
版本：1.0.x版本
设备：android浏览器

问题：在List.Item,Button组件上的onClick事件传递到下一级相同位置的按钮，
导致下一级页面按钮触发点击事件。

demo：https://codepen.io/motorfu/pen/gmrZNJ

**Comment by paranoidjk** [comment]
加下 fastclick 试试？
关联以下
https://github.com/ant-design/ant-design-mobile/issues/720
https://github.com/ant-design/ant-design-mobile/issues/924

**Comment by MotorFu** [comment]
demo 中已经加了，难道添加的方法错了？？？？

**Comment by paranoidjk** [comment]
@pingan1927 @warmhug @iyutao @silentcloud 
对使用了`rc-touchable`相关的组件，`Fastclick`没生效，`touch`事件还是点击穿透到下一个页面了。
有解决经验吗？

**Comment by MotorFu** [comment]
我目前使用的解决方法是使用setTimeout延迟50ms,避免穿透

**Comment by MotorFu** [comment]
我在Demo中补充了
demo：https://codepen.io/motorfu/pen/gmrZNJ

**Comment by warmhug** [comment]
@paranoidjk 还是这里的问题 https://github.com/ant-design/ant-design-mobile/blob/ed0ec4e3144f18444f3124b3eaa5d3083c87acc2/components/list/ListItem.web.tsx#L72 ，不加这个是好的，上次那么改还是有问题的。

**Comment by warmhug** [comment]
@MotorFu 你这个 demo 挺不错，我加入到官方 sample 里去，感谢

**Comment by paranoidjk** [comment]
@warmhug 上次是为了改这个disable的问题https://github.com/ant-design/ant-design-mobile/pull/795

正常情况理解，Fastclick加进来之后，300ms的延迟应该就没有，那么这个点击穿透到下个页面应该就不存在，所以可能还是rc-touchable的实现有些不同，还没来得及细看

**Comment by paranoidjk** [comment]
还可以关联这个 https://github.com/ant-design/ant-design-mobile/issues/845

**Comment by jinchaoxiang** [comment]
请问楼主是怎么解决问题的 
我现在也有这个问题 部分ios用户点击picker就关闭 
安卓是点击picker的确定按钮后自动聚焦上次点击过的input 
react-15.3 antd-mobile 1.0.0

**Comment by MotorFu** [comment]
@jinchaoxiang 在native上使用antd-mobile,不清楚

**Comment by paranoidjk** [comment]
@yiminghe 看下这个问题，`rc-touchable`在切换页面的时候会有点击穿透，现象是这样的：

- 两个页面相同位置有A，B两个`rc-rouchable`元素, 点击上层页面的A，router change，切换到下层页面
- A的`onPress`会触发，这是正常的，是`touchend`
- 但B的`onPress`也会触发，是`mouseup`
- 加不加FastClick都是一样

**Comment by paranoidjk** [comment]
@yiminghe 这是 [demo](https://github.com/react-component/touchable/blob/click-delay/examples/demo.tsx#L34),  在Android手机上可以复现

**Comment by yiminghe** [comment]
你之前改的回退，onClick 加到 a 上而不是 touchable 上，

**Comment by paranoidjk** [comment]
@yiminghe 那 [这个](http://gitlab.alibaba-inc.com/react-ui/ant-mobile/issues/408) 需要修复下？

**Comment by yiminghe** [comment]
提 pr 到 touchable 修复

**Comment by paranoidjk** [comment]
@MotorFu 

please try `antd-mobile@1.0.4`, it should be fixed, if still have problem, just reopen

**Comment by MotorFu** [comment]
感谢！！！！！

**Comment by SevenUMR** [comment]
版本：iOS 10.1手机为iPhone5C。点击picker。会有明显的闪烁。感觉和这个issue的问题是一致的。
