### ISSUE TITLE
react native demo 下载地址 404

### ISSUE THREAD

**Issue by kimown** [ant-design/ant-design-mobile#938]
官方 [demo](https://github.com/ant-design/ant-design-mobile/#react-native-demo) 的二维码地址是 https://mobile.ant.design/rn-kitchen-sink/qrcode.html 

但是用手机扫描后，显示 你找的页面不存在

**Comment by paranoidjk** [comment]
我这边ios扫描可以正常安装

你是什么设备？

**Comment by paranoidjk** [comment]
android的确不行

**Comment by kimown** [comment]
@paranoidjk 的确是android

**Comment by paranoidjk** [comment]
已经修复

**Comment by zhangyezeng** [comment]
react native demo 请问这个的源码在哪下啊？

**Comment by paranoidjk** [comment]
@zhangyezeng https://github.com/ant-design/ant-design-mobile/tree/master/rn-kitchen-sink

**Comment by zhangyezeng** [comment]
@paranoidjk 非常感谢！但是这个我能运行起来吗？

**Comment by paranoidjk** [comment]
@zhangyezeng 看 Readme 里面的开发文档，以及wiki。有问题请先搜索查阅，没有答案再提问
