### ISSUE TITLE
关于Tabs自适应高度的一点建议

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design-mobile#94]
#### 本地环境

- antd-mobile 版本：0.7.2
- 操作系统及其版本：
- 浏览器及其版本：

#### 你做了什么？
App型的tab
`<Tabs type="tabbar" mode="dark" defaultActiveKey="2" onChange={callback}>
          <TabPane tab={<span><Icon type="home" />首页</span>} key="1">选项首页内容</TabPane>
          <TabPane tab={<span><Icon type="team" />好友</span>} key="2">选项好友内容</TabPane>
          <TabPane tab={<span><Icon type="setting" />设置</span>} key="3">选项设置的内容</TabPane>
        </Tabs>`

Tabs高度我只能通过复盖你们的样式名才有做到适应屏幕高度，而且内容体.am-tab-content的高度也没办法做到自适应高度（tabs高度-tab标签高度）。我也有通过样式去做过这样的处理，但是内容页的高度很难处理。
是不是可以考虑做一个类似react-container的布局。现在的Flex是人列布局，行布布没办法做。或提供一个tabs自适应的demo。

**Comment by silentcloud** [comment]
你是希望 app 型的 tab 占满整个屏幕宽高？

**Comment by ksh033** [comment]
@silentcloud 是的。我们开发中经常有使用就是占满整个屏幕宽高。类似网易客户端的tab，手机支付宝的首页也不是一个tab页。

**Comment by silentcloud** [comment]
0.7 的 app tab 要实现占满屏幕确实需要重新覆盖 `am-tab-bar` 的样式

```css
position: fixed;
bottom: 0;
width: 100%;
```

1.0 重新拆分了 app tabs 出来 => `tabbar` 到时候会占满屏幕，0.7 目前只能覆盖样式了 @ksh033

**Comment by ksh033** [comment]
@silentcloud 好的我已经是这样做的了。只不过处理.am-tab-content的高度比较麻烦就是了。哈哈期待1.0有更多好用的东西，非常感谢。
