### ISSUE TITLE
魅族m1 使用最新版本的antd-mobile tabs组件，页面无法显示

### ISSUE THREAD

**Issue by manan1234** [ant-design/ant-design-mobile#940]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:1.0.3
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:安卓

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

e.g. What components are imported and what configurations are made（例如：引入了什么组件，传入了何种参数和配置）
引入了tabs标签页组件demo
#### What do you expected?（预期的正常效果）
安卓系统和ios系统正常显示页面，但安卓系统中页面无法展现

#### Re-producible online demo (可复现的在线demo)
官方Tabs标签页demo

Compile or tool configuration issues: Put the sample code on GitHub/Coding.net, so we can figure it out.（构建工具或环境配置类问题请提供 github 项目示例源码偏于排查）

Runtime issues: Please fork this [Codepen](http://codepen.io/paranoidjk/pen/LWpaKe) to re-produce you issue.（其他问题建议fork 此 [在线demo](http://codepen.io/paranoidjk/pen/LWpaKe) ）

**Comment by paranoidjk** [comment]
请提供可复现的在线demo http://codepen.io/paranoidjk/pen/LWpaKe

**Comment by paranoidjk** [comment]
用心写的issue模版就是不看吗……你这样一个标题怎么帮你解决问题

**Comment by paranoidjk** [comment]
galaxy s3测试官方demo正常

**Comment by manan1234** [comment]
不好意思，新人。。。 下次注意，我在项目中直接引用的tabs组件提供的官方demo（“超出界面宽度，多于5个标签”）

**Comment by manan1234** [comment]
demo1 demo2 是正确的，但是demo3 在安卓手机上是一片空白

**Comment by paranoidjk** [comment]
安卓手机具体什么型号？Android什么版本？ 你直接访问官方demo看看 https://mobile.ant.design/kitchen-sink/components/tabs

**Comment by paranoidjk** [comment]
测了几台android手机都是正常的，确认你使用的最新版本1.0.3
`rm -rf node_modules && npm i antd-mobile@1.0.3 --save && npm i`

**Comment by manan1234** [comment]
魅族手机 ，安卓版本6.0 ，支付宝版本10.0.5，支付宝扫一扫你上边提供的官方demo库中第三个组件点击切换的tab出错，全部滚动到左边只留下了选项11

**Comment by paranoidjk** [comment]
Meizu U10, Android 6.0 自带浏览器测试正常。

截图或者录个屏看看？

**Comment by manan1234** [comment]
![Uploading S70306-112237.jpg…]()

**Comment by paranoidjk** [comment]
图片上传错了？看不见

另外多给一些详细信息便于我们复现，比如你魅族的详细型号，flymeui的版本，以及魅族自带浏览器或者chrome上有没有这个问题

**Comment by manan1234** [comment]
魅族型号：m1
系统版本：Flyme OS 4.2.1.2Y
魅族自带浏览器有这个问题

**Comment by manan1234** [comment]
图片我是直接拖进去的这样不可以么

**Comment by manan1234** [comment]
![s70306-112237](https://cloud.githubusercontent.com/assets/23091201/23596037/cc5e4138-0261-11e7-8d0b-e692393155fb.jpg)

**Comment by paranoidjk** [comment]
我这边试了几台魅族都没问题，m1的设备我这边没有。你的设备能复现的话帮忙调试一下？

**Comment by manan1234** [comment]
怎么做？

**Comment by paranoidjk** [comment]
http://wiki.jikexueyuan.com/project/chrome-devtools/remote-debugging-on-android.html

**Comment by manan1234** [comment]
sorry，我这边弄不了。。。

**Comment by paranoidjk** [comment]
@manan1234 你这 m1 我在官网都没搜到，而且 Flyme4应该不是Android 6.0。从你的截图来看，文字都没有居中，感觉是浏览器不支持flex。
建议你提供一个完整详细的截屏或gif，包括Tab的三个demo是否都正常

**Comment by paranoidjk** [comment]
cc @pingan1927 @iyutao @silentcloud 谁有这测试机的可以帮看下..云测上测了没复现

**Comment by manan1234** [comment]
魅族型号：PRO 6
安卓版本：6.0
版本号：Flyme 6.0.1.0A
同样的问题

**Comment by manan1234** [comment]
设备名称：Galaxy Note3
型号：SM-N9009
安卓版本：5.0
支付宝版本：10.0.3
也是这个问题

**Comment by zhouzefei** [comment]
原因是tabs里面的findIndex不支持，引入一下es6-shim即可

**Comment by paranoidjk** [comment]
@zhouzefei 来个pr呗，帮我们把findIndex替换掉
