### ISSUE TITLE
使用Tabs组件时我当前设置的是一共5个tab，每个tab由4个汉字组成。在iphone5、6上每个tab的内容显示不全

### ISSUE THREAD

**Issue by wuxia510** [ant-design/ant-design-mobile#941]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

{ Tabs} from 'antd-mobile'

   <Tabs defaultActiveKey="1" onChange={that.tabCallback}>
                        <TabPane tab="我处理的" key="1">
                            <div>
                                <MyDealTask></MyDealTask>
                            </div>
                        </TabPane>
                        <TabPane tab="我创建的" key="2">
                            <div>
                                <CreateTaskList></CreateTaskList>
                                {/*<div>{taskList}</div>*/}
                            </div>
                        </TabPane>
                        <TabPane tab="我参与的" key="3">
                            <div>
                                <MyDealTask></MyDealTask>
                                {/*<div>{taskList}</div>*/}
                            </div>
                        </TabPane>
                        <TabPane tab="组内工单" key="4">
                            <div>
                                <MyDealTask></MyDealTask>
                                {/*<div>{taskList}</div>*/}
                            </div>
                        </TabPane>
                        <TabPane tab="完成工单" key="5">
                            <div>
                                <MyDealTask></MyDealTask>
                                {/*<div>{taskList}</div>*/}
                            </div>
                        </TabPane>
                    </Tabs>
#### What happen?（发生了何种非正常现象）

![image](https://cloud.githubusercontent.com/assets/16182215/23599765/ea9f1c82-027d-11e7-83aa-70e41fa78a10.png)

**Comment by paranoidjk** [comment]
please provide a reproducible demo http://codepen.io/paranoidjk/pen/LWpaKe

**Comment by wuxia510** [comment]
我设置 pageSize={2}没起作用。控制台报下边这个警告，会不会是跟这个错误有关？你看下，谢谢！
 <Tabs defaultActiveKey="1" onChange={that.tabCallback} pageSize={2}>
![image](https://cloud.githubusercontent.com/assets/16182215/23603625/e13e8426-0290-11e7-9f70-7ba2095fccfd.png)

**Comment by paranoidjk** [comment]
@wuxia510 使用最新 1.0.3

**Comment by wuxia510** [comment]
不好意思我是新手，但是我们也是上周才开始用这个插件，应该安装的是最新的。方便的话能告诉我下怎么查当前安装的哪个版本的吗？或者使用$ npm install antd-mobile --save   默认安装的是最新版本吗？

**Comment by paranoidjk** [comment]
@wuxia510 `rm -rf node_modules && npm i antd-mobile@1.0.3 --save && npm i` 建议去学习下npm的基本知识

**Comment by wuxia510** [comment]
好的，我试试，谢谢你！

**Comment by paranoidjk** [comment]
@wuxia510 模拟器测试正常，close掉，请提供可复现的demo。另外，5个Tab，每个标题4个字有点太多，很少见移动端业务有这么用的

![1](https://zos.alipayobjects.com/rmsportal/BBStcpVWwHDttFonVQNx.png)
![2](https://zos.alipayobjects.com/rmsportal/qKtoqUzebbUOUrFymlvS.png)
