### ISSUE TITLE
SwipeAction不太好用

### ISSUE THREAD

**Issue by Sdoy** [ant-design/ant-design-mobile#943]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:1.0.3
- Browser (or mark react-native) and its version（浏览器或react-native版本）:chrome
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:mac

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

官网SwipeAction说明下这一点，
![image](https://cloud.githubusercontent.com/assets/10302939/23609723/573abf5a-02aa-11e7-9875-d3c3ba705e38.png)
当我左划之后，除了点取消和删除2个按钮，无法恢复原来的样子，滑动后，在Item上加onClick事件也没法调用

#### What do you expected?（预期的正常效果）

除了点取消和删除2个按钮，还能怎样让滑动出来的东西消失

另外：能不能提供主动调出 按钮的 方法，（界面上有一个删除按钮，点击后所有List.Item进入删除状态）

**Comment by paranoidjk** [comment]
> 当我左划之后，除了点取消和删除2个按钮，无法恢复原来的样子，

用chrome的话开模拟器，或者真机，实测没问题。

> 另外：能不能提供主动调出 按钮的 方法，（界面上有一个删除按钮，点击后所有List.Item进入删除状态）

这个API暂时没有，也不太符合移动端常见交互，当然，PR 欢迎

**Comment by silentcloud** [comment]
@Sdoy 目前没有做 pc 的支持，只支持 mobile

**Comment by paranoidjk** [comment]
关联
https://github.com/react-component/swipeout/issues/28
https://github.com/react-component/swipeout/issues/17
