### ISSUE TITLE
imagepick通过wx选取照片接口问题

### ISSUE THREAD

**Issue by jinchaoxiang** [ant-design/ant-design-mobile#945]
#### Environment(required) | 环境（必填）
react-15.3.0 
- antd-mobile version（antd-mobile版本）:
antd-mobile 1.0.3
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
微信5.6.3内置浏览器
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:
ios android
#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

因为想让每个型号的手机都支持拍照或图库选取
使用imagepicker的onAddImageClick 调用wx.chooseImage接口返回本地localIds，然后显示在img里或者转成base64显示在img里
#### What do you expected?（预期的正常效果）
imagepicker正常显示图片或者有没有什么方法能把微信接口获取的localids转成base64

**Comment by pingan1927** [comment]
```
wx.chooseImage({
    count: 1, // 默认9
    sizeType: ['original', 'compressed'], // 可以指定是原图还是压缩图，默认二者都有
    sourceType: ['album', 'camera'], // 可以指定来源是相册还是相机，默认二者都有
    success: function (res) {
        var localIds = res.localIds; // 返回选定照片的本地ID列表，localId可以作为img标签的src属性显示图片
    }
});
```

https://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html 直接把localids设置到img不能正确显示？但是如果要上传的话 估计还是得用微信本身的。

哥只能帮你到这了，跟硬件和特定客户端打交道，H5有点爱莫能助了，可以反馈给微信客户端，提供返回base64格式图片而不是localids，或者看看微信API有没有隐藏参数，^^

**Comment by paranoidjk** [comment]
何必非要强求本地预览，拿到图片，上传cdn得到url，再给antd-mobile预览也行吧

**Comment by paranoidjk** [comment]
btw，issue模板里写明了这种问问题的建议上问答社区 😢
