### ISSUE TITLE
如何再onTextAreaChange方法中获取当前光标的位置，需要实现@某人的功能用

### ISSUE THREAD

**Issue by wuxia510** [ant-design/ant-design-mobile#947]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

{TextareaItem} from 'antd-mobile'

**Comment by paranoidjk** [comment]
组件暂不提供这方面的api，读取Dom的方案你可以尝试用 [Range api](https://developer.mozilla.org/en-US/docs/Web/API/Range) 自己写。

**Comment by paranoidjk** [comment]
或者 @RaoHai  有兴趣搞一个移动端的 `mention` 么？ 😄
