### ISSUE TITLE
iOS picker点击会出现两次明显闪烁现象

### ISSUE THREAD

**Issue by SevenUMR** [ant-design/ant-design-mobile#948]
版本：1.0.4
设备：iPhone5C 
设备版本：iOS 10.1

问题：picker点击后会有明显的两次闪烁现象 。
说明：之前1.0.3版本picker点击明显闪烁过后会直接被关闭。今天提升到1.0.4版本，不会关闭了但是闪烁现象仍旧存在。
和[#937](https://github.com/ant-design/ant-design-mobile/issues/937)应该是同个问题。

**Comment by paranoidjk** [comment]
先加下fastclick试试

https://github.com/ant-design/ant-design-mobile/wiki/FAQ#web-touchable-and-ghost-clicks

**Comment by paranoidjk** [comment]
我测试在iPhone6s plus safari上没问题

**Comment by SevenUMR** [comment]
加入fastclick以后好了。谢谢
