### ISSUE TITLE
InputItem type="number" 不能支持输入小数点

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#950]
bug

**Comment by warmhug** [comment]
以前说过这个问题，记得纯数字是为了唤起键盘

**Comment by silentcloud** [comment]
@warmhug 唤起数字键盘跟 input type 没关系的，只跟 class 有关系； @pingan1927 应该是正则问题 https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.tsx#L80

https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.web.tsx#L105

**Comment by paranoidjk** [comment]
考虑小数是不是还要考虑负数？

**Comment by silentcloud** [comment]
@paranoidjk 目前得到的需求是要支持 小数点

**Comment by paranoidjk** [comment]
尴尬了，ios弹出的数字键盘你没法输小数点
![x](https://zos.alipayobjects.com/rmsportal/tDuEDDYoOqoJlXFBczRx.PNG)

**Comment by paranoidjk** [comment]
这里的pattern也要改，但实测改了弹起的就不是数字键盘了
https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/index.web.tsx#L245

**Comment by silentcloud** [comment]
现在的状况就是在支付宝里，调起了带小数点的键盘却不能输入小数点

![image](https://cloud.githubusercontent.com/assets/1698185/23686798/a9884f42-03e6-11e7-93d3-19cecc4ae361.png)

**Comment by pingan1927** [comment]
@warmhug 说的对，目前的代码能最大概率保证唤起的默认键盘是数字的。
@silentcloud 那我试试看，把正则范围扩大下

**Comment by paranoidjk** [comment]
https://site.alipay.net/iat/open-nebula/fe/tips.html

**Comment by paranoidjk** [comment]
@silentcloud 支付宝里的webview唤起的是容器的虚拟键盘？我在safari里唤起的键盘都没有小数点...

**Comment by silentcloud** [comment]
@paranoidjk 支付宝里针对 wenview 唤起的键盘做了处理的，加了小数点的

**Comment by silentcloud** [comment]
这个我先处理 RN 的，web 的后面再看

**Comment by Liuqing650** [comment]
web用起来同样不支持小数点，心塞

**Comment by warmhug** [comment]
web 版、可以自己设置新的 pattern 来覆盖默认提供的。
关联 https://github.com/ant-design/ant-design-mobile/issues/349#issuecomment-258412048
