### ISSUE TITLE
Steps 时间轴右端超出问题

### ISSUE THREAD

**Issue by handoudou** [ant-design/ant-design-mobile#952]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.3

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
显示一个任务的进度；或者引导用户完成某个复杂任务。
最后的步骤完成后不应该超出
计提问题可参考官网：https://mobile.ant.design/components/steps/

#### What do you expected?（预期的正常效果）
最后的步骤完成后不应该超出

#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.3

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
显示一个任务的进度；或者引导用户完成某个复杂任务。
最后的步骤完成后不应该超出
具体问题问题可参考官网：https://mobile.ant.design/components/steps/

#### What do you expected?（预期的正常效果）
最后的步骤完成后不应该超出

#### What happen?（发生了何种非正常现象）

<img width="422" alt="2017-03-08 11 23 05" src="https://cloud.githubusercontent.com/assets/9360181/23688920/3a0521ca-03f2-11e7-8db3-05a80e281252.png">

**Comment by paranoidjk** [comment]
cc @warmhug Is this by design ? or a bug

**Comment by afc163** [comment]
https://github.com/react-component/steps/commit/474337b4f4f674aca35e0182fcdb91f839595a10

**Comment by warmhug** [comment]
![image](https://cloud.githubusercontent.com/assets/2011119/23706001/53aa89c6-0447-11e7-8f5f-0645adc5e820.png)
正确的是这样子的。检查下、现在还是有问题。 @paranoidjk

**Comment by paranoidjk** [comment]
@warmhug 升了 rc-steps 之后水平不会溢出了。不过step的样式需要调整的太多了.. 看gitlab设计师提的 `#448`
