### ISSUE TITLE
InputItem、TextareaItem 多个的时候，来回切换 focus，会出现 focus 无效，无光标显示

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design-mobile#953]
用 state 来控制 focus 感觉方案不是太好啊，大家有什么想法

![test](https://cloud.githubusercontent.com/assets/1698185/23688943/6cea9534-03f2-11e7-90a0-726a90533e9f.gif)

**Comment by pingan1927** [comment]
@silentcloud 
```
  componentDidUpdate() {
    if (this.state.focused) {
      (this.refs as any).input.focus();
    }
  }
```

只有在外部传入的focused属性为真时，才通过脚本主动触发focus，其他都是用户真实操作触发的获取光标

**Comment by paranoidjk** [comment]
@pingan1927 这一小段代码感觉有点别扭啊，会抢焦点吧...我看下源码

**Comment by pingan1927** [comment]
这个肯定得业务约定一个页面只有一个input或者可以获取焦点的组件设置了`focused`，非要弄到抢焦点也木有办法。

**Comment by silentcloud** [comment]
@pingan1927 约定一个页面只有一个 input 这个不现实；

那么具体一个页面 > 1 个的时候应该怎么使用？现在的感觉就是跟原生 input  切换的时候差别很大

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/issues/1243
