### ISSUE TITLE
SearchBar在 react-native 下不显示右侧按钮

### ISSUE THREAD

**Issue by F-happy** [ant-design/ant-design-mobile#957]
#### 环境

- antd-mobile版本: 1.0.4
- Breact-native版本:  0.39.0
- 操作系统版本或设备型号: mac 10.12.3 模拟器

#### 复现

我在页面中添加了SearchBar组件之后，点击组件并没有自动出现 demo 中右侧的按钮。

#### 预期的正常效果

期望像官方demo中一样正常展示

#### 结果

![wx20170308-170258](https://cloud.githubusercontent.com/assets/8241236/23697042/21f8a8f2-0421-11e7-8222-371e8cc29585.png)

**Comment by silentcloud** [comment]
是不是在这里 ，被挡住了？ 最好贴一下你的代码
![image](https://cloud.githubusercontent.com/assets/1698185/23698617/259f5ee6-0427-11e7-83ff-910512d38656.png)

**Comment by F-happy** [comment]
```javascript
class StoreManagePage extends Component {
    constructor(props){
        super(props);
        let ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1.a !== r2.a});
        this.state = {
            dataSource: ds.cloneWithRows([{a:1,b:2}, {a:1,b:2}]),
        };
    }

    render() {
        return (
            <ScrollView style={ViewStyle.homeView}>
                <SearchBar
                    placeholder="搜索"
                    onSubmit={()=>{alert('ha')}}
                />
                <ListView
                    dataSource={this.state.dataSource}
                    renderRow={(rowData) => <Text>{rowData.a}--{rowData.b}</Text>}
                />
            </ScrollView>
        )
    }
}
```
代码是这样的 @silentcloud

**Comment by F-happy** [comment]
不小心点错了给关了。。。

**Comment by paranoidjk** [comment]
右侧的删除按钮需要有文字才会显示 @F-happy

**Comment by paranoidjk** [comment]
@F-happy 如果你是说的右侧的取消按钮，目前自动显示的逻辑有问题，临时设置`showCancelButton`

@silentcloud web会自动显示取消按钮，RN不会

**Comment by F-happy** [comment]
所以也就是说 RN 上面没有自动显示是吧？需要我获得焦点后设置 ```showCancelButton ``` 为 true 咯？ @paranoidjk

**Comment by paranoidjk** [comment]
@F-happy 你暂时可以这样做，后续我们会修复

**Comment by paranoidjk** [comment]
@F-happy 可见如果你issue描述清楚，能省掉多少追问的时间.... 你的问题也能更快解决
