### ISSUE TITLE
引用 Checkbox  报错

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design-mobile#959]
只要用 Checkbox 就会有一个warning

warn.js?3dbb:6 `rcUtil PureRenderMixin` is deprecated, use `react-addons-pure-render-mixin` by `require('react-addons-pure-render-mixin')` instead

**Comment by silentcloud** [comment]
环境，代码，按照 issue 模板给哈

**Comment by qq645381995** [comment]
环境
antd-mobile 版本: 1.0.4
操作系统版本或设备型号: mac 10.12.4

代码
import {Checkbox} from 'antd-mobile';
const AgreeItem = Checkbox.AgreeItem;

只要用了 就会报 warning

**Comment by qq645381995** [comment]
@silentcloud

**Comment by paranoidjk** [comment]
实测1.0.4 没报错，请给出可复现的代码或在线demo

**Comment by paranoidjk** [comment]
https://github.com/ant-design/antd-mobile-samples/blob/master/web-webpack-pro/src/containers/player/player.component.jsx#L7

**Comment by qq645381995** [comment]
@paranoidjk  给你github 仓库 可以吗？ 那我整理一个

**Comment by qq645381995** [comment]
@paranoidjk  https://github.com/qq645381995/checkoutDemo

**Comment by silentcloud** [comment]
@qq645381995 已经好了？我看仓库代码跑着没问题
![image](https://cloud.githubusercontent.com/assets/1698185/23734726/08e82be4-04bc-11e7-9ece-7dd3f5fdf077.png)

**Comment by qq645381995** [comment]
@silentcloud   上面不是 warning 吗 我说的就是这个

**Comment by silentcloud** [comment]
@qq645381995 这个 warning 没关系的，而且目前要等下面这些依赖升级 rc-util 到 4.x

![image](https://cloud.githubusercontent.com/assets/1698185/23735264/7d8587c8-04bf-11e7-8234-80bc635002ef.png)

@afc163

**Comment by paranoidjk** [comment]
rc-input-number 我抽空升掉

**Comment by qq645381995** [comment]
@paranoidjk  按理说你升级了我这不会有那个 warning了 但是 我  rm -rf   node_modules  再装了一次 还是不行？已经升级 1.05 了

**Comment by paranoidjk** [comment]
@qq645381995 你锁死版本了 https://github.com/qq645381995/checkoutDemo/blob/master/yarn.lock 自己检查下

**Comment by qq645381995** [comment]
是 我下载的还是3.x 这个是哪个依赖的？  依赖没改吗
我删了 yarn.lock  重新下载的 还是不行

**Comment by qq645381995** [comment]
rc-notification  这个依赖还是 3.x  @paranoidjk

**Comment by paranoidjk** [comment]
@qq645381995 等本周五的 1.0.6

**Comment by qq645381995** [comment]
@paranoidjk  好的
