### ISSUE TITLE
魅族手机高清方案 bug 

### ISSUE THREAD

**Issue by zhouzefei** [ant-design/ant-design-mobile#963]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:1.0.3
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:mx pro4

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
直接访问antd-mobile事例地址https://mobile.ant.design/kitchen-sink/?lang=zh-CN

#### What do you expected?（预期的正常效果）
![image](https://cloud.githubusercontent.com/assets/8566935/23733420/bf9176ec-04b3-11e7-84dd-58eb297db196.png)

#### What happen?（发生了何种非正常现象）
![s70309-103105](https://cloud.githubusercontent.com/assets/8566935/23733425/c8a9d58a-04b3-11e7-8f2a-45a0f37904ee.jpg)

页面可以进行缩放，我看了源码有no-scale,不知道什么原因居然可以缩放

**Comment by paranoidjk** [comment]
感觉魅族自带浏览器是个大坑....

试试chrome或者支付宝打开有问题没，确认是android版本原因还是魅族魔改了啥...

**Comment by pingan1927** [comment]
@paranoidjk @zengyue 如果业务确实要在手机自带浏览器而不是微信/支付宝等客户端内打开，可以更新下高清脚本，找出魅族自带浏览器的ua，不走高清方案。

**Comment by zhouzefei** [comment]
iphone6
![image](https://cloud.githubusercontent.com/assets/8566935/23737631/43d8eaf0-04cf-11e7-9551-2672f3daba73.png)

iphone5
![image](https://cloud.githubusercontent.com/assets/8566935/23737617/2ee1845e-04cf-11e7-9152-f63529eb30ce.png)


 iphone5与iphone6的情况下，如果按照px转rem来做，这个宽度就会存在问题 @pingan1927 @paranoidjk

**Comment by paranoidjk** [comment]
@zhouzefei 并没有pro4的测试机，但测了几台其他魅族手机没复现。先close，如果还有问题，留言评论就行。或者欢迎PR来帮忙修复
