### ISSUE TITLE
Tabs组件和 css-loader?sourceMap 并用后，样式乱了。

### ISSUE THREAD

**Issue by jokerapi** [ant-design/ant-design-mobile#965]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.3
- Browser (or mark react-native) and its version（浏览器或react-native版本）: chrome
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）: mac

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

只有初始加载时会这样，点击后回复正常。(可以看到是蓝色的线宽度计算有误)
![2017-03-09 1 28 54](https://cloud.githubusercontent.com/assets/19544032/23737213/78b25430-04cc-11e7-8951-8d21b0d0a01f.png)

**Comment by paranoidjk** [comment]
please provide a reproducible demo

**Comment by paranoidjk** [comment]
sourceMap 理论上讲不会影响css，并不清楚你的配置和环境我们也无法排查。

请给出可重现的demo，如果确认是bug，我会reopen并处理，谢谢。

**Comment by paranoidjk** [comment]
@jokerapi 关联 https://github.com/ant-design/ant-design-mobile/issues/979
