### ISSUE TITLE
Picker 相关疑问

### ISSUE THREAD

**Issue by xoptimal** [ant-design/ant-design-mobile#966]
#### Environment(required) | 环境（必填）

1.03 / Browser  / window 10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

引用Picker , 关键代码:
```
<Picker
  {...getFieldProps('district', {
    initialValue: item ? [item.province, item.city, item.county] : '',
    rules       : [
      {required: true, message: '请选择所在地区'},
    ],
  })}
  error={!!getFieldError('district')}
  onErrorClick={() => {
    Toast.fail(getFieldError('district'), 1);
  }}
  extra="请选择所在地区"
  data={district}
>
  <List.Item arrow="horizontal">所在地区</List.Item>
</Picker>
```

#### What happen?（发生了何种非正常现象）

1. extra  描述文字, 输入文字颜色一致,  建议区分 ~  参考 InputItem ... 

2. 设置 error 后, 并未显示感叹号 ~

#### What do you expected?（预期的正常效果）

* error 设置生效 
* extra : 提示文字/输入文字 颜色区分

**Comment by paranoidjk** [comment]
请参考issue模版的codepen给一个可重现的在线demo

**Comment by xoptimal** [comment]
可以根据官方 Picker 案例, 进行测试 ~   暂未在线Demo

**Comment by paranoidjk** [comment]
http://codepen.io/paranoidjk/pen/LWpaKe

**Comment by paranoidjk** [comment]
close。

请给出可重现的demo，如果确认是bug，我会reopen并处理。
