### ISSUE TITLE
在iso10 safari中，SearchBar获取焦点后会自动放大并撑大整个页面，并且失去焦点后页面不会恢复

### ISSUE THREAD

**Issue by rurusgit** [ant-design/ant-design-mobile#967]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 0.9.x
- Browser (or mark react-native) and its version（浏览器或react-native版本）: ios10 safari
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）: windows10

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）
1. import {SearchBar } from 'antd-mobile';
2. <SearchBar   placeholder="搜索"   onSubmit={value => alert(value)} />；
3. 在PC端用Chrome模拟移动浏览器 没有问题，实际上手机后，当获取焦点后会撑大页面。

1. 引入SearchBar；
2. 只设置了placeholder

#### What do you expected?（预期的正常效果）
1. 正常显示，不要放大。

期望像 InputItem 一样正常展示

#### What happen?（发生了何种非正常现象）
获取焦点会放大，同时撑大整个页面，失去焦点后页面无法恢复

**Comment by warmhug** [comment]
官方 demo https://09x.mobile.ant.design/kitchen-sink/search-bar/ 这里是否也有你说的问题？请给出可重现 demo 。另外 建议升级到 1.0 版本

**Comment by paranoidjk** [comment]
@rurusgit 我在 ios 10 safari上测试了官方demo，没有问题。

且 **同时撑大整个页面** 这个现象不太科学，我们的高清方案是禁止了页面缩放的。

请参考issue模板提供可复现的在线demo，如果确认可复现，我们会第一时间处理，谢谢。

**Comment by rurusgit** [comment]
多谢，我后来是加了meta禁止缩放解决的。
后面要是还出现我再放个demo ：）
最近事情少点，准备升级下1.0，之前升级的时候自定义svg找不到。
ps：能否出个webpack / roadhog  完整的配置文件的示例。特别是webpack，现在dva脚手架默认使用roadhog，因此感觉webpack的配置比较零散。毕竟经常使用webpack的项目，要改成陌生的roadhog，心里还是比较没底。

**Comment by paranoidjk** [comment]
@rurusgut 官方demo库里面包括roadhog，webpack各种构建工具都有 https://github.com/ant-design/antd-mobile-samples

**Comment by miaoyuxinbaby** [comment]
@rurusgit  我也遇到了同样的问题。也是通过禁止页面缩放解决的。
