### ISSUE TITLE
picker问题

### ISSUE THREAD

**Issue by SevenUMR** [ant-design/ant-design-mobile#968]
版本：1.0.4

官网示例就有这个问题，1.0.4仍有这个bug。
步骤如下：
1.picker弹起以后，选择非第一行的item，点击确定。
2.再次点开该picker，点击上面的popup，picker会关闭。
3.此时再点开picker会默认回到第一个item。

目前我们项目上只有单行picker，多行的未进行测试。

**Comment by warmhug** [comment]
多组件混合使用的问题，建议给出可运行 demo

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/918

@SevenUMR 回到第一个说明你没真正选中，picker的选中是有一个动画延迟的，未选中任何的情况下默认会取第一个

**Comment by paranoidjk** [comment]
重复的issue close，这个进度情关注 #918

**Comment by SevenUMR** [comment]
可能是我描述问题。
我重新说一下：
1.打开picker
2.选择非第一个item。点击确定
3.第二次打开picker，此时item显示是正确的。
4.点击上方popup，picker关闭。
5.再次打开picker，item显示回到第一个。

至于你们说的demo。你们官网自己的就是很好的例子。按照我的步骤去做百分百重现。

在我的理解下我这个情况和没有选中不是一个问题。并不是一个重复的issue。

**Comment by paranoidjk** [comment]
@SevenUMR 说再多，不如提供设备型号，浏览器版本，可重现的demo或截图，录屏等有用信息。

比如这是我 iPhone6plus 真机录屏，一切正常。

![img](https://zos.alipayobjects.com/rmsportal/ZMwYyGbbCLkjtdAwanHv.gif)

**Comment by paranoidjk** [comment]
@SevenUMR 请关注 https://github.com/ant-design/ant-design-mobile/issues/978

**Comment by SevenUMR** [comment]
这次因为做项目期间提issue比较匆忙，传了一次录屏没成功就忘记了，以后会注意，让交流更简单一些。也感谢框架开发人员的耐心处理。
