### ISSUE TITLE
antd-mobile  range,按demo上调用后报错.求解决方案

### ISSUE THREAD

**Issue by AlanCoder** [ant-design/ant-design-mobile#970]
Uncaught TypeError: Failed to construct 'Range': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

**Comment by pingan1927** [comment]
相关环境请仔细再阅读下，https://mobile.ant.design/docs/react/introduce#使用
给出的信息不能有效说明问题。

**Comment by paranoidjk** [comment]
不阅读issue模版一律close，抱歉。

贴这段错误没什么作用，请参考issue模版，给出可重现的在线demo，说明版本，环境。
