### ISSUE TITLE
Android手机上switch开关的样式变成圆角长方形的了，跟demo中不一样。复现手机为OPPOr9 Android5.0系统  

### ISSUE THREAD

**Issue by wuxia510** [ant-design/ant-design-mobile#971]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:1.0.3
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:
Android5.0      手机型号魅族note2、OPPOr9

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

import {List, NavBar, InputItem, TextareaItem, Switch, Toast} from 'antd-mobile';

#### What do you expected?（预期的正常效果）
如demo中椭圆绿色的开关

https://mobile.ant.design/components/switch/
#### What happen?（发生了何种非正常现象）
Android手机上switch开关的样式变为蓝色圆角长方形的了！！！！

![screenshot_2017-03-09-18-38-15-69](https://cloud.githubusercontent.com/assets/16182215/23747578/2c9886ee-04fb-11e7-9f00-64da261ce666.png)

**Comment by pingan1927** [comment]
我用vivo x7试试看...

**Comment by paranoidjk** [comment]
@pingan1927 ....在slm上找了台oppo测了下还真是。。。变方形可能是border-radius不支持这还可以理解。。。颜色都变了这也太诡异了

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/pull/738

android switch 做了特殊处理

**Comment by paranoidjk** [comment]
@wuxia510 刚跟设计师确认了。我们的某些组件，包括 switch， modal等做了平台区分，以尽量和 android，ios平台的原生组件效果一致，所以这是by design。

**Comment by motorguo** [comment]
@paranoidjk @pingan1927 

```
"antd-mobile": "^1.0.4",
```

安卓 chrome 下的效果
![9ivefan8jzq0 oorl fcm](https://cloud.githubusercontent.com/assets/16831715/23797003/b8966a3e-05d8-11e7-8a74-491cd2ca2d66.png)

[期望效果](https://mobile.ant.design/components/modal/)

**Comment by paranoidjk** [comment]
@motorguo  这是正常的， by design。

Modal 和 Switch 我们针对 Android 和 IOS 平台做了区分处理，以更接近原生组件的样式。后续我们会补充完善文档和demo。

**Comment by motorguo** [comment]
@paranoidjk 这样啊。但是自定义四个按钮 or 多个按钮以上，都在一排并显示 `...`
