### ISSUE TITLE
体验反馈: 1.0.4版本去掉了左侧栏组件列表的中文名,很不习惯.

### ISSUE THREAD

**Issue by caohaijiang** [ant-design/ant-design-mobile#972]
建议,回复之前方式

**Comment by paranoidjk** [comment]
你是指手机访问？ 我们网站做了国际化，你访问到的是英文版本。

PC 访问会自动检测系统语言跳转的，移动端我做下优化吧，谢谢反馈。

临时你可以 https://mobile.ant.design/kitchen-sink/?lang=zh-CN 这样访问就是中文了

**Comment by caohaijiang** [comment]
不是pc访问的:https://mobile.ant.design/components/accordion/
左侧栏在组件名称列表,老版本是双语中英文的,1.04只有英文了.

**Comment by paranoidjk** [comment]
@caohaijiang https://mobile.ant.design/components/accordion-cn/
