### ISSUE TITLE
使用Range出现了一个bug,请各位帮忙分析下问题

### ISSUE THREAD

**Issue by AlanCoder** [ant-design/ant-design-mobile#974]
环境:
NODE v6.5.0
NPM v4.3.0
webpack 1.13.2

antd-mobile版本: 1.0.4
Browser: chrome
react 版本:15.3.0
操作系统版本: win8

重现方式:
官方demo上的JS部分一字不漏的调用了，但报了以下错误
Uncaught TypeError: Failed to construct 'Range': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

预期我是需要使用Range并结合createTooltip，如果单独使用Range没有问题,但使用createTooltip后编译,浏览器就报以上错误

https://mobile.ant.design/kitchen-sink/components/range#range-demo-0

暂时无法提供在线demo,我代码与官方demo是一致的

另外我特地做了尝试
const Slider = require('rc-slider');
const Range1 = createTooltip(Slider.Range);
如果我将官方的Range弃之不用,改用ANTD调用的rc的range是可以正常渲染出来的..

**Comment by paranoidjk** [comment]
参照这个提供demo  http://codepen.io/paranoidjk/pen/LWpaKe

**Comment by AlanCoder** [comment]
@paranoidjk 看了下你给的demo 是tabs的,我说的是新版1.x后把slider拆分后的range 结合tooltip的问题呢   还是说你要我参照语法?

**Comment by paranoidjk** [comment]
当然是参照语法。。。。

**Comment by AlanCoder** [comment]
是改成createClass?   别的没什么可调整了已经
刚才尝试过,错误依旧

**Comment by AlanCoder** [comment]
我在想,是不是我环境问题? 我把官方的demo直接放到codepen上运行却没有问题

**Comment by paranoidjk** [comment]
尝试 rm -rf node_modules 删除依赖重装，确保你使用的是最新版本。如果在线实在没法复现，提交你的demo代码到github我帮你看看

**Comment by AlanCoder** [comment]
好的 我尝试重装依赖,感谢

**Comment by AlanCoder** [comment]
node_modules删除后重装问题解决,原因可能是因为之前安装了0.9.x版本,升级后有残余文件没有更新...感谢 @paranoidjk
