### ISSUE TITLE
developer docs link broken in read.me

### ISSUE THREAD

**Issue by jasan-s** [ant-design/ant-design-mobile#975]
https://github.com/ant-design/ant-design-mobile/blob/master/development.md   is broken in read.me. Is there a english docs for using the components in react native?

**Comment by paranoidjk** [comment]
sorry, i will fix this .

by the way, the document translation is in progress, you can track it at  https://github.com/ant-design/ant-design-mobile/issues/329, and welcome PR to help us do it.

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/blob/master/development.en-US.md#developmentreact-native
