### ISSUE TITLE
Picker点击蒙板隐藏，选中值被初始化

### ISSUE THREAD

**Issue by MotorFu** [ant-design/ant-design-mobile#978]
版本：antd-mobile:1.0.x

问题：选中数据后，点击连续点击多次 遮罩层，Picker组件中选中的值与显示的数据没有一致，组件中的数据初始化了。
![image](https://cloud.githubusercontent.com/assets/3940888/23791817/7928b0be-05bf-11e7-9236-bb8675e42965.png)

官方Demo重现了这个问题。

**Comment by paranoidjk** [comment]
我点击并没有重现。至少给下gif或重现步骤？包括设备与浏览器信息，issue模版写的很清楚

**Comment by MotorFu** [comment]
浏览器Chrome 版本 56.0.2924.87 (64-bit)

在IOS微信中也出现了这种情况

![image](https://cloud.githubusercontent.com/assets/3940888/23793021/61366a64-05c4-11e7-9666-590eda3a5603.png)

使用codepen无法重现问题；

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/968

**Comment by paranoidjk** [comment]
update 点击蒙板可以复现，点击确认无法复现。

**Comment by MotorFu** [comment]
那这个问题能解决么？另外Picker组件有提供精致点击蒙版关闭窗口的属性吗？

**Comment by liumcb** [comment]
你们picker中的列表中城市也是这么少么？只有几个？为什么安装 antd-mobile-demo-data 安装之后没有效果？？？？

**Comment by warmhug** [comment]
@liumcb 对接自己服务端数据源，这里只是展示、用了部分数据

**Comment by paranoidjk** [comment]
@yiminghe https://github.com/react-component/m-picker/blob/master/src/PopupMixin.tsx#L60  picker 隐藏的时候为什么把值清空？是有什么特殊考虑吗？如果是 bug 我就修掉。

**Comment by yiminghe** [comment]
https://github.com/react-component/m-picker/commit/5640fc47cbd7c670dd3a77f4c1bec828a9b47d67

**Comment by yiminghe** [comment]
重新安装
