### ISSUE TITLE
默认开启css-loader的css modules之后，ant-mobile的效果全乱了，有什么好的配置方法吗？

### ISSUE THREAD

**Issue by loszer** [ant-design/ant-design-mobile#979]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.1
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What did you do? Please provide stedps to re-produce your problem.（请提供复现步骤）

webpack中的配置
![image](https://cloud.githubusercontent.com/assets/8136736/23819234/7919e7e4-063e-11e7-931c-7523a1933cda.png)
tabbar的效果变成这种诡异的了
![image](https://cloud.githubusercontent.com/assets/8136736/23819235/7c8a0580-063e-11e7-8335-3950293dbace.png)

#### What do you expected?（预期的正常效果）
原来的正常效果
![image](https://cloud.githubusercontent.com/assets/8136736/23819254/b7993b78-063e-11e7-94a2-cf25848b0387.png)
因为自动开启css modules之后，就不用给每个css class写个`:local`套在前面。
简而言之，有没有什么推荐的做法，可以在默认开启css-loader的css modules特性的同时保证不打乱ant-mobile的效果呢？

**Comment by paranoidjk** [comment]
试试在你自己的css module配置里面exclude掉antd-mobile自己的样式
```
exclude: require.resolve('antd-mobile').replace(/warn\.js$/, ''),
```

**Comment by paranoidjk** [comment]
关联 https://github.com/ant-design/ant-design-mobile/issues/965

**Comment by paranoidjk** [comment]
close for no response, it should be fine when you exclude antd-mobile css.

**Comment by ovaldi** [comment]
mark
