### ISSUE TITLE
SwipeAction滑动没反应

### ISSUE THREAD

**Issue by Raincal** [ant-design/ant-design-mobile#98]
#### 本地环境

- antd-mobile 版本：0.7.7
- 操作系统及其版本：Android 5.0.2; Redmi Note2
- 浏览器及其版本：Chrome 52.0.2743.98

#### 你做了什么？

引入 antd-mobile 的 SwipeAction, List

#### 你期待的结果是：

可以左右滑动

#### 实际上的结果：

左右滑动没有反应，长按后的弹窗样式有点问题，
官网在线demo长按正常
![screenshot_2016-08-16-14-36-49-178_com android ch](https://cloud.githubusercontent.com/assets/6279478/17690371/aedc9dca-63c0-11e6-9ca1-3d255a0b116d.png)

**Comment by silentcloud** [comment]
Android 做了类似原生长按的交互，至于样式问题，我这边排查一下

**Comment by silentcloud** [comment]
这个是由于有默认的 padding 引起的，需要自己 reset 一下默认的样式

![image](https://cloud.githubusercontent.com/assets/1698185/17797265/2ad6b4e8-65fa-11e6-8bc8-87a85416fb99.png)

@Raincal
