### ISSUE TITLE
使用Tabs组件的时候，chrome开发者工具报出warning

### ISSUE THREAD

**Issue by loszer** [ant-design/ant-design-mobile#980]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 1.0.1
- Browser (or mark react-native) and its version（浏览器或react-native版本）: chrome 56.0.2924.87 (64-bit)
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:  mac osx 12

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

这是jsx中用到了Tabs的一段，基本从文档上抄的
![image](https://cloud.githubusercontent.com/assets/8136736/23823840/e4a1e996-06a5-11e7-984e-407d7f574823.png)

#### What happen?（发生了何种非正常现象）
其实可以使用，就是chrome中打印出Warning
![image](https://cloud.githubusercontent.com/assets/8136736/23823855/2feac3e6-06a6-11e7-83c8-231279f04aef.png)
如图，并没有传给Tabs任何className

**Comment by paranoidjk** [comment]
please use latest version `1.0.5`, it had been fixed.

**Comment by loszer** [comment]
thanks, 解决了
