### ISSUE TITLE
组件ListView加载后，动态修改state后发现整个页面无法点击，如同有个透明的东西遮罩了

### ISSUE THREAD

**Issue by liubin1023** [ant-design/ant-design-mobile#982]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:1.0.5
- Browser (or mark react-native) and its version（浏览器或react-native版本）:0.39.2
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:android 4.4.2
初始化：
![image](https://cloud.githubusercontent.com/assets/6219316/23841639/ab0d7bd8-07e9-11e7-914d-08036a8046f3.png)
加载数据：
![image](https://cloud.githubusercontent.com/assets/6219316/23841644/b57c2998-07e9-11e7-8a49-a00bc3419e12.png)
页面调用：
![image](https://cloud.githubusercontent.com/assets/6219316/23841649/bdaf005e-07e9-11e7-8671-ca00462264db.png)

**Comment by paranoidjk** [comment]
没理解你的意思，官方demo就有动态加载数据的，没有问题 https://github.com/ant-design/ant-design-mobile/blob/master/components/list-view/demo/basic.tsx#L78

请给一个简单可重现的demo代码

**Comment by silentcloud** [comment]
@liubin1023 直接贴代码吧

**Comment by liubin1023** [comment]
`constructor(props) {
        super(props);
        var dataSourceTmp = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        const dataBlobTmp = [];
        this.state = {
            dataSource: dataSourceTmp.cloneWithRows(dataBlobTmp),
        }
}


loadListData() {
        var _this = this;
        RequestUtils.postRequestFun({
            url: WebConst.RequestPath() + '/mobile/stockDetail/pack/list/search/plpcd',
            params: {
                packingCaseId: _this.props.packingCaseId
            }
        }, _this.props.navigator, function (json) {
            if (json.success === true) {
                var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
                var results = json.results;
                var dataBlob = [];
                for (var i = 0; i < results.length; i++) {
                    var pressedText = {
                        title: results[i].productName,
                        des: results[i].productSn,
                        number: results[i].packedQuantity + '个',
                        id: results[i].id,
                    };
                    dataBlob.push(pressedText);
                }
                _this.setState({
                    dataSource: ds.cloneWithRows(dataBlob)
                });
            } else {
                let errors = json.errorInfos;
                for (var i in errors) {
                    Toast.fail(errors[i].errorMessage);
                }
            }
        })
    }


render() {
        const row = (rowData, sectionID, rowID) => {
            const obj = rowData;
            return (
                <TouchableHighlight onPress={() => alert(rowID)}>
                    <View key={rowID}
                          style={styles.rowView}
                          onPress={this.details}
                    >

                        <Text style={styles.rowTitle}>
                            {obj.title}
                        </Text>
                        <Flex style={styles.contentView}>
                            <Flex.Item><Text>{obj.des}</Text></Flex.Item>
                            <Flex.Item><Text style={styles.back}>{obj.number}</Text></Flex.Item>
                        </Flex>
                    </View>
                </TouchableHighlight>
            )
        }
 return (
<ListView
                    dataSource={this.state.dataSource}
                    renderRow={row}
                    enableEmptySections = {true}
                >
)
}`

**Comment by liubin1023** [comment]
@silentcloud  首次加载没有问题，但是如果我在这个界面点击按钮新添加一条记录然后手动调用this.loadListData() 方法后，ListView显示数据正常（比之前多一条记录）但是整个界面就无法点击了，感觉被一个透明的东西给遮罩了

**Comment by paranoidjk** [comment]
@liubin1023 代码格式化，这样子没法看。

**Comment by liubin1023** [comment]
@paranoidjk  我格式化后显示的更没法看，`字符冲突

**Comment by paranoidjk** [comment]
@liubin1023 至少阅读一遍 issue 模板 ，不要直接删掉

![xx](https://zos.alipayobjects.com/rmsportal/GXhzOPSrWlIviiJzTodq.png)

**Comment by afc163** [comment]
```
constructor(props) {
        super(props);
        var dataSourceTmp = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        const dataBlobTmp = [];
        this.state = {
            dataSource: dataSourceTmp.cloneWithRows(dataBlobTmp),
        }
}


loadListData() {
        var _this = this;
        RequestUtils.postRequestFun({
            url: WebConst.RequestPath() + '/mobile/stockDetail/pack/list/search/plpcd',
            params: {
                packingCaseId: _this.props.packingCaseId
            }
        }, _this.props.navigator, function (json) {
            if (json.success === true) {
                var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
                var results = json.results;
                var dataBlob = [];
                for (var i = 0; i < results.length; i++) {
                    var pressedText = {
                        title: results[i].productName,
                        des: results[i].productSn,
                        number: results[i].packedQuantity + '个',
                        id: results[i].id,
                    };
                    dataBlob.push(pressedText);
                }
                _this.setState({
                    dataSource: ds.cloneWithRows(dataBlob)
                });
            } else {
                let errors = json.errorInfos;
                for (var i in errors) {
                    Toast.fail(errors[i].errorMessage);
                }
            }
        })
    }


render() {
        const row = (rowData, sectionID, rowID) => {
            const obj = rowData;
            return (
                <TouchableHighlight onPress={() => alert(rowID)}>
                    <View key={rowID}
                          style={styles.rowView}
                          onPress={this.details}
                    >
                        <Text style={styles.rowTitle}>
                            {obj.title}
                        </Text>
                        <Flex style={styles.contentView}>
                            <Flex.Item><Text>{obj.des}</Text></Flex.Item>
                            <Flex.Item><Text style={styles.back}>{obj.number}</Text></Flex.Item>
                        </Flex>
                    </View>
                </TouchableHighlight>
            )
        }
 return (
<ListView
                    dataSource={this.state.dataSource}
                    renderRow={row}
                    enableEmptySections = {true}
                >
)
}
```

格式化一下有这么难么？

segmentfault.com/markdown

**Comment by warmhug** [comment]
RN ListView 直接用的 react-native 没有改动，在 react-native 仓库找答案
