### ISSUE TITLE
修改首页标题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design-mobile#986]
『移动端设计指南』貌似不存在？

**Comment by paranoidjk** [comment]
是说 title 吗？  
```html
<title>Ant Design Mobile | A Mobile Design Specification</title>
```

**Comment by afc163** [comment]
<img width="590" alt="image" src="https://cloud.githubusercontent.com/assets/507615/23848477/71e2ce5c-0812-11e7-8cfd-300695ac5c90.png">

**Comment by paranoidjk** [comment]
![home](https://zos.alipayobjects.com/rmsportal/hQfMkLbQAyYtcUObpQAV.png)

slogan一直就用的原来的，改成这样不太好吧。。。或者另想一句，大写的【前端框架】四个字 😅 

移动端设计指南在design.alipay是有的，看能不能放出来？

**Comment by warmhug** [comment]
不要删了、对外发布日志等一直都是说的 “设计 & 前端实现”，删了就少了设计这一块了。

移动端设计指南 ，可以考虑加个到 http://design.alipay.com/ 这里的链接。另外现在很多单个组件里的 rule 说的就是设计指南，内容少了点。
![image](https://cloud.githubusercontent.com/assets/2011119/24069140/9d8073a8-0bdb-11e7-884b-92ab70f90402.png)

发到内部和设计师讨论下怎么优化设计指南这块
