### ISSUE TITLE
List.Item的active状态

### ISSUE THREAD

**Issue by pingan1927** [ant-design/ant-design-mobile#989]
rc-touchable没有处理touchCancel事件。

一个List.Item内嵌套一个Icon，Icon的onClick触发一个Alert，这个时候List.Item外层的touchable没有接收到click事件结束的状态（我的理解是touchCancel没有做相应处理，一般发生在来电，alert==），`_endHighlight`方法没有执行。导致`List.Item`的`${prefixCls}-item-active`样式一直存在没有消失。

**Comment by paranoidjk** [comment]
@pingan1927 给个代码 demo 吧，文字描述太费劲了

**Comment by pingan1927** [comment]
```
<List.Item
            className="index-card index-main-card"
            arrow="horizontal"
            onClick={(el) => {
              // do something
            }}
            multipleLine={true}
            align="top"
          >
            <div className="card-tile">
              潜在顾客
              <span
                onClick={(ev) => {
                  ev.stopPropagation();
                  alert(111); // 套进setTimeout会减缓异常
                }}
              >
                <Icon
                  type={require('../common/svg/question.svg')}
                  size="xs"
                  style={{color: '#979797'}}
                />
              </span>
            </div>
          </List.Item>
        </List>
```

**Comment by pingan1927** [comment]
`ev.stopPropagation(); `复现的时候 把这个去掉，更能准确复现

**Comment by paranoidjk** [comment]
@pingan1927  我这边在模拟器上正常，是要在 android 上复现吗？
![xx](https://zos.alipayobjects.com/rmsportal/jrbsMmXsLpoHyiJrdOcI.gif)

**Comment by linfaxin** [comment]
+1 我这边业务里也出现了

iOS重现步骤：

1. 按住 List.Item 触发 active ，然后滑动滚动（滚动过程中会保持active态，因为移动端scroll事件回调延迟）
2. 在滚动过程中瞄准这个active的条目再次按上去滑动
3. 然后就会一直 active 态了

可以在钱包等App里的UIWebView上稳定重现，不能在Safari里重现，Safari里的WebView没有scroll延迟的问题

另外Android机子在点击进入新窗口页面的时候也出现过，暂时没有去尝试如何复现。

![截图](https://zos.alipayobjects.com/rmsportal/EidYDaMujeXFvOgDBqGn.png)

**Comment by paranoidjk** [comment]
@linfaxin 按你的描述我在 ios 钱包里没复现

**Comment by paranoidjk** [comment]
@pingan1927 你的代码去掉 stopPropagation 在钱包里复现了。

**Comment by paranoidjk** [comment]
@yiminghe 看下上面 @pingan1927 的问题，抽象模型就是 rc-touchable 内部嵌套的元素有 onClick 事件监听

- 正常情况下点击嵌套的元素  `onTouchStart`  -->  `onTouchEnd`
- 假如内部嵌套的元素 onClick 回调里面执行 window.alert，会导致active的class被保留，debug看了下是被当做长按中了，即如下的事件触发顺序

  - onTouchStart  
  - window.alert执行
  - window.alert 模态框关闭
  - onTouchEnd 
  - onTouchStart 
  - onMouseDown 
  - LONG_PRESS_DETECTED

**Comment by yiminghe** [comment]
这个应该没法处理，可以用容器的 bridge.alert

**Comment by paranoidjk** [comment]
close. @pingan1927 @linfaxin 有意向的话可以来个 PR。
