### ISSUE TITLE
引用个antd的bug 

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design-mobile#990]
https://github.com/ant-design/ant-design/issues/4475

这个在mobile 好像也有滚动条失效的问题 能否看一下？

**Comment by paranoidjk** [comment]
> 这个在mobile 好像也有滚动条失效的问题 能否看一下？

能否提供一个demo ？

**Comment by qq645381995** [comment]
@paranoidjk   那个 issues  就有demo的 不过用的是 antd的  你可以改成 mobile 试试

**Comment by qq645381995** [comment]
@paranoidjk  这个你能复现吗？

**Comment by paranoidjk** [comment]
@qq645381995 抱歉，最近特别忙。能否帮忙提供一个antd-mobile的demo，能复现的话我抽空帮你看小

**Comment by paranoidjk** [comment]
并没发现有问题。 http://codepen.io/paranoidjk/pen/zZWJNe

**Comment by qq645381995** [comment]
我看了你这没事 等遇到了再说吧
