### ISSUE TITLE
建议能添加个日历组件，最好可展开收起的。

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design-mobile#991]

**Comment by paranoidjk** [comment]
https://mobile.ant.design/components/date-picker

**Comment by zhulichao** [comment]
我说的不是日期选择，是日历，类似这样的，但是能展开收起。我用react-native-calendar关键词在github上搜索了一下，还没有具有这种功能的日历。有一个类似的组件但跑起来有问题，写的是RN兼容0.20。所以想问一下您这边有计划提供这种日历组件吗。
展开：
![image](https://cloud.githubusercontent.com/assets/18158633/23888813/def39a64-08c4-11e7-9dc8-b5813416eacc.png)
收起：
![image](https://cloud.githubusercontent.com/assets/18158633/23888839/f338a1a4-08c4-11e7-975d-6007e0a36479.png)

**Comment by paranoidjk** [comment]
新组件的优先级会比较低，我们人力和精力优先，目前重点暂时会优先处理已有组件的体验和bug问题。

欢迎 PR 贡献。

**Comment by zhulichao** [comment]
好的，谢谢回复。

**Comment by 520Yanxiaofei** [comment]
嗨，你好，我也是有这个需求，很急的功能。请问你这个实现了吗？十分感谢回复

**Comment by warmhug** [comment]
https://mobile.ant.design/components/calendar/
