### ISSUE TITLE
高清解决方案在 6/7 plus等一些大屏尺寸下有点失真

### ISSUE THREAD

**Issue by xfcdxg** [ant-design/ant-design-mobile#992]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）: 
- Browser (or mark react-native) and its version（浏览器或react-native版本）:
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What happen?（发生了何种非正常现象）
以下截图分别是 iPhone 4 6  6p的截图
看到scale算出是0.33，手动改成0.4就正常很多...

![image](https://cloud.githubusercontent.com/assets/16435465/23889052/11c54270-08c6-11e7-86d5-ce69a456f2cc.png)
![image](https://cloud.githubusercontent.com/assets/16435465/23889061/1a3547ca-08c6-11e7-82ed-527af32103a4.png)
![image](https://cloud.githubusercontent.com/assets/16435465/23889063/2053b952-08c6-11e7-8d63-e8a8f8a1fc77.png)

**Comment by paranoidjk** [comment]
这应该是正常的，iPhone6 pluswindow.devicePixelRatio 获取的dpr是3，但实际好像不是3

@pingan1927 可以解答下

**Comment by pingan1927** [comment]
@xfcdxg 首先，请拿真机测试下，仔细看了你的截图，其中chrome模拟器并不都是100%。
我想说的是，基于antd-mobile开发业务，目前并没有遇到严重的失真现象，反而可以说是效果很好。。。
PS: 切换机型后，请重新刷新下页面再看看效果

**Comment by xfcdxg** [comment]
这个是真机图，用了Tabs和List

![image](https://cloud.githubusercontent.com/assets/16435465/23899256/68233108-08ef-11e7-80d2-c64c87496dbc.png)

**Comment by sosohime** [comment]
@xfcdxg webpack配置里面加入pxtorem然后用px写试试
` const pxtorem = require('postcss-pxtorem');
  webpackConfig.postcss.push(pxtorem({
    rootValue: 100,
    propWhiteList: [],
  }));`
[https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE](url)

**Comment by xfcdxg** [comment]
@sosohime 可以了，但这个内联样式改不了吧？内联的尺寸需要像素除100+rem 来处理吧？
