### ISSUE TITLE
Icon 自定义 size  没效果 

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design-mobile#993]
看源码 
var sizeMap={'xxs':15,'xs':18,'sm':21,'md':22,'lg':36};
var fontSize=typeof size==='string'?sizeMap[size]:size;

就是不知道 size 获取的时候 是不是 string 
我是这样传的
<Icon size={25} type='check-circle'/>

**Comment by paranoidjk** [comment]
https://mobile.ant.design/components/icon#components-icon-demo-size

**Comment by qq645381995** [comment]
@paranoidjk  那要怎么用？ 我是 <Icon size={99}/>

**Comment by paranoidjk** [comment]
number 类型的size只有RN支持，web只支持 'xxs'/'xs'/'sm'/'md'/'lg'

**Comment by qq645381995** [comment]
@paranoidjk   哦  文档那句话没看懂。。。。

**Comment by paranoidjk** [comment]
抱歉，文档在优化的过程中。
也欢迎PR帮我们完善文档

**Comment by qq645381995** [comment]
帮忙 看下 https://github.com/ant-design/ant-design-mobile/issues/990
