### ISSUE TITLE
antd-m组件间耦合太严重，我公司项目只想使用antd-m的下拉刷新组件RefreshControl，引入antd-m后却发现把antd-m很多模块、资源都引入了，项目体积增大了太多，这个能优化解耦吗

### ISSUE THREAD

**Issue by haomiaozhichen** [ant-design/ant-design-mobile#994]
antd-m组件间耦合太严重，我公司项目只想使用antd-m的下拉刷新组件RefreshControl，引入antd-m后却发现把antd-m很多模块、资源都引入了，项目体积增大了太多，这个能优化解耦吗

**Comment by yesmeck** [comment]
请安文档说明来配置 https://mobile.ant.design/docs/react/introduce#Web-使用方式 组件是按需加载的。
