### ISSUE TITLE
Modal.alert弹出后，怎么在销毁事件时关闭弹窗

### ISSUE THREAD

**Issue by liuxingling** [ant-design/ant-design-mobile#995]
Modal.alert弹出后，如果不点击‘确定’，或者‘关闭’，浏览器前进或后退，弹窗会一直存在，想在销毁的时候手动关闭弹窗。

**Comment by paranoidjk** [comment]
给Modal加个ref，在你的页面componentWillUnmount的时候调一下this.refs.xxx.close（）

**Comment by liuxingling** [comment]
@paranoidjk 我用的Modal.alert，这个ref加到哪里啊。
<Button
          data-role="btnOrg" onClick={() => alert('提示', tip, [
          { text: '取消' },
          { text: '确定', onPress: () => callback(), style: { fontWeight: 'bold' } },
          ])}
        >删除</Button>

**Comment by paranoidjk** [comment]
@liuxingling 见我上面的回复，暂时加不了，我会添加一个API https://github.com/ant-design/ant-design-mobile/pull/998

类似这样
```
const alertInstance = Modal.alert();
alertInstance.close(); // 手动关闭
```

**Comment by liuxingling** [comment]
@paranoidjk 能临时解决我的问题不？

**Comment by paranoidjk** [comment]
@liuxingling 本周五，也就是明天会发新版本。

实在等不及的话你可以参照这个 https://github.com/ant-design/ant-design-mobile/blob/master/components/modal/alert.web.tsx#L23 自己销毁dom
