### ISSUE TITLE
modal弹出后，页面依然可以滚动(手机下)

### ISSUE THREAD

**Issue by jokerapi** [ant-design/ant-design-mobile#996]
#### Environment(required) | 环境（必填）

- antd-mobile version（antd-mobile版本）:1.0.5
- Browser (or mark react-native) and its version（浏览器或react-native版本）:手机浏览器
- Operating environment (e.g. OS name) and its version（操作系统版本或设备型号）:

#### What did you do? Please provide steps to re-produce your problem.（请提供复现步骤）

在手机打开官网的demo https://mobile.ant.design/kitchen-sink/components/modal?lang=zh-CN#modal-demo-0，
可以发现，modal弹出后页面依然可以滚动。

具体原因参考： https://www.douban.com/note/561975262/

**Comment by suncn** [comment]
问题比较多，有点头疼，明天我也提点issue吧，哎，今天就这样子了吧。

**Comment by paranoidjk** [comment]
iPhone 6sp Safari测试没问题。你是什么设备什么浏览器请写清楚

**Comment by warmhug** [comment]
是常见问题。自己搜索外部各种解决方案，或参考这里 https://github.com/ant-design/ant-design-mobile/blob/master/components/popup/demo/basic-up.md

![image](https://cloud.githubusercontent.com/assets/2011119/23992255/2d60196c-0a77-11e7-8815-561bc6228753.png)
