### ISSUE TITLE
TabBar.Item don't has  dot property in react native， but document has

### ISSUE THREAD

**Issue by piaoluoya** [ant-design/ant-design-mobile#997]
code:

       <TabBar.Item
          title="应用"
          key="应用"
          dot={true}
          icon={require('image!icon-special')}
          selected={this.state.selectedTab === 'blue1Tab'}
          style={{width:48,height:49}}
          onPress={() => {
            this.setState({
              selectedTab: 'blue1Tab',
            }); 
          }}  
          data-seed="logId-1"
        >   
          {this.renderContent('应用')}
        </TabBar.Item>

or 

       <TabBar.Item
          title="应用"
          key="应用"
          dot
          icon={require('image!icon-special')}
          selected={this.state.selectedTab === 'blue1Tab'}
          style={{width:48,height:49}}
          onPress={() => {
            this.setState({
              selectedTab: 'blue1Tab',
            }); 
          }}  
          data-seed="logId-1"
        >   
          {this.renderContent('应用')}
        </TabBar.Item>

上面两种代码都没有显示小红点

文档：https://mobile.ant.design/components/tab-bar/
代码我用的是：https://github.com/ant-design/antd-mobile-samples/tree/master/rn-web
代码在github上最新代码里没有也没有找到相关代码

antd-mobile :1.0.0
react native 版本:0.34.0
最新的xcode自带的iphone6 模拟器

**Comment by paranoidjk** [comment]
文档不准确。欢迎来个pr帮我们改下文档
